QuantLib: QuantLib::ForwardRateAgreement Class Reference
QuantLib::ForwardRateAgreement Class Reference
#include <forwardrateagreement.hpp>
Public Member Functions
ForwardRateAgreement (const Date &valueDate, const Date &maturityDate, Position::Type type, Rate strikeForwardRate, Real notionalAmount, const boost::shared_ptr< IborIndex > &index, const Handle< YieldTermStructure > &discountCurve=Handle< YieldTermStructure >())
Calculations
bool isExpired () const
Date settlementDate () const
Real spotIncome (const Handle< YieldTermStructure > &incomeDiscountCurve) const
Real spotValue () const
Spot value (NPV) of the underlying loan.
InterestRate forwardRate () const
Returns the relevant forward rate associated with the FRA term.
Protected Member Functions
void performCalculations () const
Protected Attributes
Position::Type fraType_
InterestRate forwardRate_
aka FRA rate (the market forward rate)
InterestRate strikeForwardRate_
aka FRA fixing rate, contract rate
Real notionalAmount_
boost::shared_ptr< IborIndex > index_
Detailed Description
Definition at line 76 of file forwardrateagreement.hpp.
Constructor & Destructor Documentation
QuantLib::ForwardRateAgreement::ForwardRateAgreement (const Date & valueDate, const Date & maturityDate, Position::Type type, Rate strikeForwardRate, Real notionalAmount, const boost::shared_ptr< IborIndex > & index, const Handle< YieldTermStructure > & discountCurve = Handle<YieldTermStructure>())
Definition at line 26 of file forwardrateagreement.cpp.
References QuantLib::Calendar::advance(), QuantLib::Forward::calendar_, QuantLib::InterestRate::compoundFactor(), QuantLib::Days, QuantLib::Forward::discountCurve_, forwardRate_, fraType_, QuantLib::Forward::incomeDiscountCurve_, index_, QuantLib::Forward::maturityDate_, notionalAmount_, QuantLib::Once, QuantLib::Forward::payoff_, QL_REQUIRE, QuantLib::Observer::registerWith(), QuantLib::Forward::settlementDays_, QuantLib::Simple, strikeForwardRate_, QuantLib::Forward::underlyingIncome_, and QuantLib::Forward::valueDate_.
    : Forward(index->dayCounter(), index->fixingCalendar(),
              index->businessDayConvention(),
              index->fixingDays(), boost::shared_ptr<Payoff>(),
              valueDate, maturityDate, discountCurve),
      fraType_(type), notionalAmount_(notionalAmount), index_(index) {
        QL_REQUIRE(notionalAmount > 0.0, "notionalAmount must be positive");
        // do I adjust this ?
        // valueDate_ = calendar_.adjust(valueDate_,businessDayConvention_);
        Date fixingDate = calendar_.advance(valueDate_,
            -static_cast<Integer>(settlementDays_), Days);
        forwardRate_ = InterestRate(index->fixing(fixingDate),
                                    index->dayCounter(),
                                    Simple, Once);
        strikeForwardRate_ = InterestRate(strikeForwardRate,
                                          index->dayCounter(),
                                          Simple, Once);
        Real strike = notionalAmount_ *
                      strikeForwardRate_.compoundFactor(valueDate_,
                                                        maturityDate_);
        payoff_ = boost::shared_ptr<Payoff>(new ForwardTypePayoff(fraType_,
                                                                  strike));
        // incomeDiscountCurve_ is irrelevant to an FRA
        incomeDiscountCurve_ = discountCurve_;
        // income is irrelevant to FRA - set it to zero
        underlyingIncome_ = 0.0;
        registerWith(index_);
    }
Member Function Documentation
InterestRate QuantLib::ForwardRateAgreement::forwardRate () const
Returns the relevant forward rate associated with the FRA term.
Definition at line 91 of file forwardrateagreement.cpp.
References QuantLib::Instrument::calculate(), and forwardRate_.
Referenced by spotValue(), and anonymous_namespace{piecewiseyieldcurve.cpp}::testCurveConsistency().
{
        calculate();
        return forwardRate_;
    }
bool QuantLib::ForwardRateAgreement::isExpired () const [virtual]
A FRA expires/settles on the valueDate
Reimplemented from QuantLib::Forward.
Definition at line 69 of file forwardrateagreement.cpp.
References QuantLib::Event::hasOccurred(), settlementDate(), and QuantLib::Forward::valueDate_.
{
        return detail::simple_event(valueDate_).hasOccurred(settlementDate());
    }
void QuantLib::ForwardRateAgreement::performCalculations () const [protected, virtual]
In case a pricing engine is not used, this method must be overridden to perform the actual calculations and set any needed results. In case a pricing engine is used, the default implementation can be used.
Reimplemented from QuantLib::Forward.
Definition at line 96 of file forwardrateagreement.cpp.
References QuantLib::Calendar::advance(), QuantLib::Forward::calendar_, QuantLib::Days, forwardRate_, index_, QuantLib::Once, QuantLib::Forward::settlementDays_, QuantLib::Simple, spotValue(), QuantLib::Forward::underlyingIncome_, QuantLib::Forward::underlyingSpotValue_, and QuantLib::Forward::valueDate_.
{
        Date fixingDate = calendar_.advance(valueDate_,
            -static_cast<Integer>(settlementDays_), Days);
        forwardRate_ = InterestRate(index_->fixing(fixingDate),
                                    index_->dayCounter(),
                                    Simple, Once);
        underlyingSpotValue_ = spotValue();
        underlyingIncome_    = 0.0;
        Forward::performCalculations();
    }
Date QuantLib::ForwardRateAgreement::settlementDate () const [virtual]
This returns evaluationDate + settlementDays (not FRA valueDate).
Reimplemented from QuantLib::Forward.
Definition at line 64 of file forwardrateagreement.cpp.
References QuantLib::Calendar::advance(), QuantLib::Forward::calendar_, QuantLib::Days, QuantLib::Singleton< Settings >::instance(), and QuantLib::Forward::settlementDays_.
Referenced by isExpired().
{
        return calendar_.advance(Settings::instance().evaluationDate(),
                                 settlementDays_, Days);
    }
Real QuantLib::ForwardRateAgreement::spotIncome (const Handle< YieldTermStructure > & incomeDiscountCurve) const [virtual]
Income is zero for a FRA
Implements QuantLib::Forward.
Definition at line 73 of file forwardrateagreement.cpp.
{
        return 0.0;
    }
Real QuantLib::ForwardRateAgreement::spotValue () const [virtual]
Spot value (NPV) of the underlying loan.
This has always a positive value (asset), even if short the FRA
Implements QuantLib::Forward.
Definition at line 84 of file forwardrateagreement.cpp.
References QuantLib::Instrument::calculate(), QuantLib::InterestRate::compoundFactor(), QuantLib::Forward::discountCurve_, forwardRate(), QuantLib::Forward::maturityDate_, notionalAmount_, and QuantLib::Forward::valueDate_.
Referenced by performCalculations().
{
        calculate();
        return notionalAmount_ *
               forwardRate().compoundFactor(valueDate_, maturityDate_) *
               discountCurve_->discount(maturityDate_);
    }
Member Data Documentation
InterestRate QuantLib::ForwardRateAgreement::forwardRate_ [mutable, protected]
aka FRA rate (the market forward rate)
Definition at line 108 of file forwardrateagreement.hpp.
Referenced by forwardRate(), ForwardRateAgreement(), and performCalculations().
Position::Type QuantLib::ForwardRateAgreement::fraType_ [protected]
Definition at line 106 of file forwardrateagreement.hpp.
Referenced by ForwardRateAgreement().
boost::shared_ptr<IborIndex> QuantLib::ForwardRateAgreement::index_ [protected]
Definition at line 112 of file forwardrateagreement.hpp.
Referenced by ForwardRateAgreement(), and performCalculations().
Real QuantLib::ForwardRateAgreement::notionalAmount_ [protected]
Definition at line 111 of file forwardrateagreement.hpp.
Referenced by ForwardRateAgreement(), and spotValue().
InterestRate QuantLib::ForwardRateAgreement::strikeForwardRate_ [protected]
aka FRA fixing rate, contract rate
Definition at line 110 of file forwardrateagreement.hpp.
Referenced by ForwardRateAgreement().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/forwardrateagreement.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/forwardrateagreement.cpp