QuantLib: QuantLib::CPICashFlow Class Reference
QuantLib::CPICashFlow Class Reference
Cash flow paying the performance of a CPI (zero inflation) index.
#include <cpicoupon.hpp>
Public Member Functions
CPICashFlow (Real notional, const boost::shared_ptr< ZeroInflationIndex > &index, const Date &baseDate, Real baseFixing, const Date &fixingDate, const Date &paymentDate, bool growthOnly=false, CPI::InterpolationType interpolation=CPI::AsIndex, const Frequency &frequency=QuantLib::NoFrequency)
virtual Real baseFixing () const
value used on base date
virtual Date baseDate () const
you may not have a valid date
virtual CPI::InterpolationType interpolation () const
do you want linear/constant/as-index interpolation of future data?
virtual Frequency frequency () const
virtual Real amount () const
redefined to use baseFixing() and interpolation
Protected Attributes
Real baseFixing_
CPI::InterpolationType interpolation_
Frequency frequency_
Detailed Description
Cash flow paying the performance of a CPI (zero inflation) index.
It is NOT a coupon, i.e. no accruals.
Definition at line 125 of file cpicoupon.hpp.
Constructor & Destructor Documentation
QuantLib::CPICashFlow::CPICashFlow (Real notional, const boost::shared_ptr< ZeroInflationIndex > & index, const Date & baseDate, Real baseFixing, const Date & fixingDate, const Date & paymentDate, bool growthOnly = false, CPI::InterpolationType interpolation = CPI::AsIndex, const Frequency & frequency = QuantLib::NoFrequency) [inline]
Definition at line 127 of file cpicoupon.hpp.
References QuantLib::CPI::AsIndex, baseFixing_, frequency_, interpolation_, QuantLib::NoFrequency, and QL_REQUIRE.
        : IndexedCashFlow(notional, index, baseDate, fixingDate,
                          paymentDate, growthOnly),
          baseFixing_(baseFixing), interpolation_(interpolation),
          frequency_(frequency) {
            QL_REQUIRE(fabs(baseFixing_)>1e-16,
                       "|baseFixing|<1e-16, future divide-by-zero error");
            if (interpolation_ != CPI::AsIndex) {
                QL_REQUIRE(frequency_ != QuantLib::NoFrequency,
                           "non-index interpolation w/o frequency");
            }
        }
Member Function Documentation
Real QuantLib::CPICashFlow::amount () const [virtual]
redefined to use baseFixing() and interpolation
Reimplemented from QuantLib::IndexedCashFlow.
Definition at line 114 of file cpicoupon.cpp.
References QuantLib::CPI::AsIndex, baseFixing(), QuantLib::Days, QuantLib::IndexedCashFlow::fixingDate(), frequency(), QuantLib::IndexedCashFlow::growthOnly(), QuantLib::IndexedCashFlow::index(), QuantLib::inflationPeriod(), interpolation(), QuantLib::CPI::Linear, and QuantLib::IndexedCashFlow::notional().
{
        Real I0 = baseFixing();
        Real I1;
        // what interpolation do we use? Index / flat / linear
        if (interpolation() == CPI::AsIndex ) {
            I1 = index()->fixing(fixingDate());
        } else {
            // work out what it should be
            //std::cout << fixingDate() << " and " << frequency() << std::endl;
            //std::pair<Date,Date> dd = inflationPeriod(fixingDate(), frequency());
            //std::cout << fixingDate() << " and " << dd.first << " " << dd.second << std::endl;
            // work out what it should be
            std::pair<Date,Date> dd = inflationPeriod(fixingDate(), frequency());
            Real indexStart = index()->fixing(dd.first);
            if (interpolation() == CPI::Linear) {
                Real indexEnd = index()->fixing(dd.second+Period(1,Days));
                // linear interpolation
                //std::cout << indexStart << " and " << indexEnd << std::endl;
                I1 = indexStart + (indexEnd - indexStart) * (fixingDate() - dd.first)
                / ( (dd.second+Period(1,Days)) - dd.first); // can't get to next period's value within current period
            } else {
                // no interpolation, i.e. flat = constant, so use start-of-period value
                I1 = indexStart;
            }
        }
        if (growthOnly())
            return notional() * (I1 / I0 - 1.0);
        else
            return notional() * (I1 / I0);
    }
Date QuantLib::CPICashFlow::baseDate () const [virtual]
you may not have a valid date
Reimplemented from QuantLib::IndexedCashFlow.
Definition at line 105 of file cpicoupon.cpp.
{
        // you may not have a valid date
        exit(-1);
    }
Real QuantLib::CPICashFlow::baseFixing () const [virtual]
value used on base date
This does not have to agree with index on that date.
Definition at line 110 of file cpicoupon.cpp.
References baseFixing_.
Referenced by amount().
{
        return baseFixing_;
    }
virtual Frequency QuantLib::CPICashFlow::frequency () const [inline, virtual]
Definition at line 158 of file cpicoupon.hpp.
References frequency_.
Referenced by amount().
{ return frequency_; }
virtual CPI::InterpolationType QuantLib::CPICashFlow::interpolation () const [inline, virtual]
do you want linear/constant/as-index interpolation of future data?
Definition at line 155 of file cpicoupon.hpp.
References interpolation_.
Referenced by amount().
{
            return interpolation_;
        }
Member Data Documentation
Real QuantLib::CPICashFlow::baseFixing_ [protected]
Definition at line 163 of file cpicoupon.hpp.
Referenced by baseFixing(), and CPICashFlow().
Frequency QuantLib::CPICashFlow::frequency_ [protected]
Definition at line 165 of file cpicoupon.hpp.
Referenced by CPICashFlow(), and frequency().
CPI::InterpolationType QuantLib::CPICashFlow::interpolation_ [protected]
Definition at line 164 of file cpicoupon.hpp.
Referenced by CPICashFlow(), and interpolation().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/cpicoupon.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/cpicoupon.cpp