QuantLib: QuantLib::G2 Class Reference
QuantLib::G2 Class Reference
Two-additive-factor gaussian model class.
#include <g2.hpp>
Classes
class Dynamics
class FittingParameter
Analytical term-structure fitting parameter \(\varphi(t) \).
class SwaptionPricingFunction
Public Member Functions
G2 (const Handle< YieldTermStructure > &termStructure, Real a=0.1, Real sigma=0.01, Real b=0.1, Real eta=0.01, Real rho=-0.75)
boost::shared_ptr
< ShortRateDynamics > dynamics () const
Returns the short-rate dynamics.
virtual Real discountBond (Time now, Time maturity, Array factors) const
Real discountBond (Time, Time, Rate, Rate) const
Real discountBondOption (Option::Type type, Real strike, Time maturity, Time bondMaturity) const
Real swaption (const Swaption::arguments &arguments, Rate fixedRate, Real range, Size intervals) const
DiscountFactor discount (Time t) const
Implied discount curve.
Real a () const
Real sigma () const
Real b () const
Real eta () const
Real rho () const
Protected Member Functions
void generateArguments ()
Real A (Time t, Time T) const
Real B (Real x, Time t) const
Private Member Functions
Real sigmaP (Time t, Time s) const
Real V (Time t) const
Private Attributes
Parameter & a_
Parameter & sigma_
Parameter & b_
Parameter & eta_
Parameter & rho_
Parameter phi_
Friends
class SwaptionPricingFunction
Detailed Description
Two-additive-factor gaussian model class.
This class implements a two-additive-factor model defined by
\[ dr_t = \varphi(t) + x_t + y_t \]
where \(x_t \) and \(y_t \) are defined by
\[ dx_t = -a x_t dt + \sigma dW^1_t, x_0 = 0 \]
\[ dy_t = -b y_t dt + \sigma dW^2_t, y_0 = 0 \]
and \(dW^1_t dW^2_t = \rho dt \).
Bug:
This class was not tested enough to guarantee its functionality.
Definition at line 53 of file g2.hpp.
Constructor & Destructor Documentation
QuantLib::G2::G2 (const Handle< YieldTermStructure > & termStructure, Real a = 0.1, Real sigma = 0.01, Real b = 0.1, Real eta = 0.01, Real rho = -0.75)
Definition at line 29 of file g2.cpp.
References a_, b_, eta_, generateArguments(), QuantLib::Observer::registerWith(), rho_, and sigma_.
    : TwoFactorModel(5), TermStructureConsistentModel(termStructure),
      a_(arguments_[0]), sigma_(arguments_[1]), b_(arguments_[2]),
      eta_(arguments_[3]), rho_(arguments_[4]) {
        a_     = ConstantParameter(a,     PositiveConstraint());
        sigma_ = ConstantParameter(sigma, PositiveConstraint());
        b_     = ConstantParameter(b,     PositiveConstraint());
        eta_   = ConstantParameter(eta,   PositiveConstraint());
        rho_   = ConstantParameter(rho,   BoundaryConstraint(-1.0, 1.0));
        generateArguments();
        registerWith(termStructure);
    }
Member Function Documentation
Real QuantLib::G2::a () const [inline]
Definition at line 90 of file g2.hpp.
References a_.
Referenced by discountBond(), dynamics(), generateArguments(), sigmaP(), swaption(), and V().
{ return a_(0.0); }
Real QuantLib::G2::A (Time t, Time T) const [protected]
Definition at line 100 of file g2.cpp.
References QuantLib::TermStructureConsistentModel::termStructure(), and V().
Referenced by discountBond(), and QuantLib::G2::SwaptionPricingFunction::SwaptionPricingFunction().
{
        return termStructure()->discount(T)/termStructure()->discount(t)*
            std::exp(0.5*(V(T-t) - V(T) + V(t)));
    }
Real QuantLib::G2::b () const [inline]
Definition at line 92 of file g2.hpp.
References b_.
Referenced by discountBond(), dynamics(), generateArguments(), sigmaP(), swaption(), and V().
{ return b_(0.0); }
Real QuantLib::G2::B (Real x, Time t) const [protected]
Definition at line 105 of file g2.cpp.
Referenced by discountBond(), and QuantLib::G2::SwaptionPricingFunction::SwaptionPricingFunction().
{
        return (1.0 - std::exp(-x*t))/x;
    }
DiscountFactor QuantLib::G2::discount (Time t) const [inline, virtual]
Implied discount curve.
Implements QuantLib::AffineModel.
Definition at line 86 of file g2.hpp.
References QuantLib::TermStructureConsistentModel::termStructure().
{
            return termStructure()->discount(t);
        }
virtual Real QuantLib::G2::discountBond (Time now, Time maturity, Array factors) const [inline, virtual]
Implements QuantLib::AffineModel.
Definition at line 66 of file g2.hpp.
References QL_REQUIRE, and QuantLib::Array::size().
{
            QL_REQUIRE(factors.size()>1,
                       "g2 model needs two factors to compute discount bond");
            return discountBond(now, maturity, factors[0], factors[1]);
        }
Real QuantLib::G2::discountBond (Time t, Time T, Rate x, Rate y) const
Definition at line 73 of file g2.cpp.
References a(), A(), b(), and B().
{
        return A(t,T) * std::exp(-B(a(),(T-t))*x-B(b(),(T-t))*y);
    }
Real QuantLib::G2::discountBondOption (Option::Type type, Real strike, Time maturity, Time bondMaturity) const [virtual]
Implements QuantLib::AffineModel.
Definition at line 77 of file g2.cpp.
References QuantLib::blackFormula(), anonymous_namespace{interpolations.cpp}::f(), sigmaP(), QuantLib::TermStructureConsistentModel::termStructure(), and anonymous_namespace{perturbativebarrieroptionengine.cpp}::v().
{
        Real v = sigmaP(maturity, bondMaturity);
        Real f = termStructure()->discount(bondMaturity);
        Real k = termStructure()->discount(maturity)*strike;
        return blackFormula(type, k, f, v);
    }
boost::shared_ptr< TwoFactorModel::ShortRateDynamics > QuantLib::G2::dynamics () const [virtual]
Returns the short-rate dynamics.
Implements QuantLib::TwoFactorModel.
Definition at line 46 of file g2.cpp.
References a(), b(), eta(), phi_, rho(), and sigma().
{
        return boost::shared_ptr<ShortRateDynamics>(new
            Dynamics(phi_, a(), sigma(), b(), eta(), rho()));
    }
Real QuantLib::G2::eta () const [inline]
Definition at line 93 of file g2.hpp.
References eta_.
Referenced by dynamics(), generateArguments(), sigmaP(), swaption(), and V().
{ return eta_(0.0); }
void QuantLib::G2::generateArguments () [protected, virtual]
Reimplemented from QuantLib::CalibratedModel.
Definition at line 51 of file g2.cpp.
References a(), b(), eta(), phi_, rho(), sigma(), and QuantLib::TermStructureConsistentModel::termStructure().
Referenced by G2().
{
        phi_ = FittingParameter(termStructure(),
            a(), sigma(), b(), eta(), rho());
    }
Real QuantLib::G2::rho () const [inline]
Definition at line 94 of file g2.hpp.
References rho_.
Referenced by dynamics(), generateArguments(), sigmaP(), swaption(), and V().
{ return rho_(0.0); }
Real QuantLib::G2::sigma () const [inline]
Definition at line 91 of file g2.hpp.
References sigma_.
Referenced by dynamics(), generateArguments(), sigmaP(), swaption(), and V().
{ return sigma_(0.0); }
Real QuantLib::G2::sigmaP (Time t, Time s) const [private]
Definition at line 57 of file g2.cpp.
References a(), b(), eta(), rho(), sigma(), and QuantLib::CalibratedModel::value().
Referenced by discountBondOption().
{
        Real temp = 1.0 - std::exp(-(a()+b())*t);
        Real temp1 = 1.0 - std::exp(-a()*(s-t));
        Real temp2 = 1.0 - std::exp(-b()*(s-t));
        Real a3 = a()*a()*a();
        Real b3 = b()*b()*b();
        Real sigma2 = sigma()*sigma();
        Real eta2 = eta()*eta();
        Real value =
            0.5*sigma2*temp1*temp1*(1.0 - std::exp(-2.0*a()*t))/a3 +
            0.5*eta2*temp2*temp2*(1.0 - std::exp(-2.0*b()*t))/b3 +
            2.0*rho()*sigma()*eta()/(a()*b()*(a()+b()))*
            temp1*temp2*temp;
        return std::sqrt(value);
    }
Real QuantLib::G2::swaption (const Swaption::arguments & arguments, Rate fixedRate, Real range, Size intervals) const
Definition at line 210 of file g2.cpp.
References a(), b(), anonymous_namespace{marketmodel.cpp}::dayCounter, eta(), QuantLib::VanillaSwap::arguments::fixedPayDates, QuantLib::VanillaSwap::arguments::floatingResetDates, QuantLib::G2::SwaptionPricingFunction::mux(), QuantLib::VanillaSwap::arguments::nominal, QuantLib::VanillaSwap::Payer, rho(), sigma(), QuantLib::TermStructureConsistentModel::termStructure(), QuantLib::VanillaSwap::arguments::type, and QuantLib::DayCounter::yearFraction().
{
        Date settlement = termStructure()->referenceDate();
        DayCounter dayCounter = termStructure()->dayCounter();
        Time start = dayCounter.yearFraction(settlement,
                                             arguments.floatingResetDates[0]);
        Real w = (arguments.type==VanillaSwap::Payer ? 1 : -1 );
        std::vector<Time> fixedPayTimes(arguments.fixedPayDates.size());
        for (Size i=0; i<fixedPayTimes.size(); ++i)
            fixedPayTimes[i] =
                dayCounter.yearFraction(settlement,
                                        arguments.fixedPayDates[i]);
        SwaptionPricingFunction function(a(), sigma(), b(), eta(), rho(),
                                         w, start,
                                         fixedPayTimes,
                                         fixedRate, (*this));
        Real upper = function.mux() + range*function.sigmax();
        Real lower = function.mux() - range*function.sigmax();
        SegmentIntegral integrator(intervals);
        return arguments.nominal*w*termStructure()->discount(start)*
            integrator(function, lower, upper);
    }
Real QuantLib::G2::V (Time t) const [private]
Definition at line 87 of file g2.cpp.
References a(), b(), eta(), rho(), sigma(), and QuantLib::CalibratedModel::value().
Referenced by A().
{
        Real expat = std::exp(-a()*t);
        Real expbt = std::exp(-b()*t);
        Real cx = sigma()/a();
        Real cy = eta()/b();
        Real valuex = cx*cx*(t + (2.0*expat-0.5*expat*expat-1.5)/a());
        Real valuey = cy*cy*(t + (2.0*expbt-0.5*expbt*expbt-1.5)/b());
        Real value = 2.0*rho()*cx*cy* (t + (expat - 1.0)/a()
                                         + (expbt - 1.0)/b()
                                         - (expat*expbt-1.0)/(a()+b()));
        return valuex + valuey + value;
    }
Friends And Related Function Documentation
friend class SwaptionPricingFunction [friend]
Definition at line 118 of file g2.hpp.
Member Data Documentation
Parameter& QuantLib::G2::a_ [private]
Definition at line 108 of file g2.hpp.
Referenced by a(), and G2().
Parameter& QuantLib::G2::b_ [private]
Definition at line 110 of file g2.hpp.
Referenced by b(), and G2().
Parameter& QuantLib::G2::eta_ [private]
Definition at line 111 of file g2.hpp.
Referenced by eta(), and G2().
Parameter QuantLib::G2::phi_ [private]
Definition at line 114 of file g2.hpp.
Referenced by dynamics(), and generateArguments().
Parameter& QuantLib::G2::rho_ [private]
Definition at line 112 of file g2.hpp.
Referenced by G2(), and rho().
Parameter& QuantLib::G2::sigma_ [private]
Definition at line 109 of file g2.hpp.
Referenced by G2(), and sigma().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/shortrate/twofactormodels/g2.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/shortrate/twofactormodels/g2.cpp