QuantLib: QuantLib::BlackVolSurface Class Reference
QuantLib::BlackVolSurface Class Reference
Black volatility (smile) surface.
#include <blackvolsurface.hpp>
Public Member Functions
Constructors
See the TermStructure documentation for issues regarding constructors.
BlackVolSurface (const Calendar &cal, BusinessDayConvention bdc=Following, const DayCounter &dc=DayCounter())
BlackVolSurface (BusinessDayConvention bdc=Following, const DayCounter &dc=DayCounter())
default constructor
BlackVolSurface (const Date &referenceDate, const Calendar &cal=Calendar(), BusinessDayConvention bdc=Following, const DayCounter &dc=DayCounter())
initialize with a fixed reference date
BlackVolSurface (Natural settlementDays, const Calendar &, BusinessDayConvention bdc=Following, const DayCounter &dc=DayCounter())
calculate the reference date based on the global evaluation date
Black spot volatility
boost::shared_ptr< SmileSection > smileSection (const Period &, bool extrapolate) const
returns the smile for a given option tenor
boost::shared_ptr< SmileSection > smileSection (const Date &, bool extrapolate) const
returns the smile for a given option date
boost::shared_ptr< SmileSection > smileSection (Time, bool extrapolate) const
returns the smile for a given option time
Visitability
void accept (AcyclicVisitor &)
Protected Member Functions
BlackAtmVolCurve interface
Real atmVarianceImpl (Time t) const
spot at-the-money variance calculation
Volatility atmVolImpl (Time t) const
spot at-the-money volatility calculation
Calculations
This method must be implemented in derived classes to perform the actual volatility calculations. When it is called, time check has already been performed; therefore, it must assume that time-extrapolation is allowed.
virtual boost::shared_ptr
< SmileSection > smileSectionImpl (Time) const =0
Detailed Description
Black volatility (smile) surface.
This abstract class defines the interface of concrete Black volatility (smile) surface which will be derived from this one.
Volatilities are assumed to be expressed on an annual basis.
Definition at line 42 of file blackvolsurface.hpp.
Constructor & Destructor Documentation
QuantLib::BlackVolSurface::BlackVolSurface (const Calendar & cal, BusinessDayConvention bdc = Following, const DayCounter & dc = DayCounter())
Warning:
term structures initialized by means of this constructor must manage their own reference date by overriding the referenceDate() method.
Definition at line 26 of file blackvolsurface.cpp.
    : BlackAtmVolCurve(cal, bdc, dc) {}
QuantLib::BlackVolSurface::BlackVolSurface (BusinessDayConvention bdc = Following, const DayCounter & dc = DayCounter())
default constructor
Warning:
term structures initialized by means of this constructor must manage their own reference date by overriding the referenceDate() method.
Definition at line 32 of file blackvolsurface.cpp.
    : BlackAtmVolCurve(bdc, dc) {}
QuantLib::BlackVolSurface::BlackVolSurface (const Date & referenceDate, const Calendar & cal = Calendar(), BusinessDayConvention bdc = Following, const DayCounter & dc = DayCounter())
initialize with a fixed reference date
Definition at line 36 of file blackvolsurface.cpp.
    : BlackAtmVolCurve(refDate, cal, bdc, dc) {}
QuantLib::BlackVolSurface::BlackVolSurface (Natural settlementDays, const Calendar & cal, BusinessDayConvention bdc = Following, const DayCounter & dc = DayCounter())
calculate the reference date based on the global evaluation date
Definition at line 42 of file blackvolsurface.cpp.
    : BlackAtmVolCurve(settlDays, cal, bdc, dc) {}
Member Function Documentation
void QuantLib::BlackVolSurface::accept (AcyclicVisitor & v) [virtual]
Reimplemented from QuantLib::BlackAtmVolCurve.
Reimplemented in QuantLib::EquityFXVolSurface, QuantLib::InterestRateVolSurface, and QuantLib::SabrVolSurface.
Definition at line 58 of file blackvolsurface.cpp.
References QL_FAIL, anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Visitor< T >::visit().
{
        Visitor<BlackVolSurface>* v1 =
            dynamic_cast<Visitor<BlackVolSurface>*>(&v);
        if (v1 != 0)
            v1->visit(*this);
        else
            QL_FAIL("not a BlackVolSurface term structure visitor");
    }
Real QuantLib::BlackVolSurface::atmVarianceImpl (Time t) const [protected, virtual]
spot at-the-money variance calculation
Implements QuantLib::BlackAtmVolCurve.
Definition at line 48 of file blackvolsurface.cpp.
References smileSectionImpl().
{
        const boost::shared_ptr<SmileSection>& s = smileSectionImpl(t);
        return s->variance(s->atmLevel());
    }
Volatility QuantLib::BlackVolSurface::atmVolImpl (Time t) const [protected, virtual]
spot at-the-money volatility calculation
Implements QuantLib::BlackAtmVolCurve.
Definition at line 53 of file blackvolsurface.cpp.
References smileSectionImpl().
{
        const boost::shared_ptr<SmileSection>& s = smileSectionImpl(t);
        return s->volatility(s->atmLevel());
    }
boost::shared_ptr< SmileSection > QuantLib::BlackVolSurface::smileSection (const Period & p, bool extrapolate) const [inline]
returns the smile for a given option tenor
Definition at line 115 of file blackvolsurface.hpp.
References QuantLib::VolatilityTermStructure::optionDateFromTenor().
Referenced by smileSection().
{
        return smileSection(optionDateFromTenor(p), extrapolate);
    }
boost::shared_ptr< SmileSection > QuantLib::BlackVolSurface::smileSection (const Date & d, bool extrapolate) const [inline]
returns the smile for a given option date
Definition at line 121 of file blackvolsurface.hpp.
References smileSection(), and QuantLib::TermStructure::timeFromReference().
{
        return smileSection(timeFromReference(d), extrapolate);
    }
boost::shared_ptr< SmileSection > QuantLib::BlackVolSurface::smileSection (Time t, bool extrapolate) const [inline]
returns the smile for a given option time
Definition at line 127 of file blackvolsurface.hpp.
References QuantLib::TermStructure::checkRange(), and smileSectionImpl().
{
        checkRange(t, extrapolate);
        return smileSectionImpl(t);
    }
virtual boost::shared_ptr<SmileSection> QuantLib::BlackVolSurface::smileSectionImpl (Time) const [protected, pure virtual]
Implemented in QuantLib::SabrVolSurface.
Referenced by atmVarianceImpl(), atmVolImpl(), and smileSection().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/volatility/blackvolsurface.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/volatility/blackvolsurface.cpp