QuantLib: QuantLib::FdmTimeDepDirichletBoundary Class Reference
QuantLib::FdmTimeDepDirichletBoundary Class Reference
#include <fdmtimedepdirichletboundary.hpp>
Public Types
typedef FdmLinearOp operator_type
typedef FdmLinearOp::array_type array_type
typedef BoundaryCondition
< FdmLinearOp >::Side Side
Public Member Functions
FdmTimeDepDirichletBoundary (const boost::shared_ptr< FdmMesher > &mesher, const boost::function< Real(Real)> &valueOnBoundary, Size direction, Side side)
FdmTimeDepDirichletBoundary (const boost::shared_ptr< FdmMesher > &mesher, const boost::function< Disposable< Array >(Real)> &valueOnBoundary, Size direction, Side side)
void setTime (Time)
void applyBeforeApplying (operator_type &) const
void applyBeforeSolving (operator_type &, array_type &) const
void applyAfterApplying (array_type &) const
void applyAfterSolving (array_type &) const
Private Attributes
const std::vector< Size > indices_
const boost::function< Real(Real)> valueOnBoundary_
const boost::function
< Disposable< Array >Real)> valuesOnBoundary_
Array values_
Detailed Description
Definition at line 38 of file fdmtimedepdirichletboundary.hpp.
Member Typedef Documentation
typedef FdmLinearOp::array_type QuantLib::FdmTimeDepDirichletBoundary::array_type
Reimplemented from QuantLib::BoundaryCondition< FdmLinearOp >.
Definition at line 42 of file fdmtimedepdirichletboundary.hpp.
typedef FdmLinearOp QuantLib::FdmTimeDepDirichletBoundary::operator_type
Reimplemented from QuantLib::BoundaryCondition< FdmLinearOp >.
Definition at line 41 of file fdmtimedepdirichletboundary.hpp.
typedef BoundaryCondition<FdmLinearOp>::Side QuantLib::FdmTimeDepDirichletBoundary::Side
Todo:
Generalize for n-dimensional conditions
Reimplemented from QuantLib::BoundaryCondition< FdmLinearOp >.
Definition at line 43 of file fdmtimedepdirichletboundary.hpp.
Constructor & Destructor Documentation
QuantLib::FdmTimeDepDirichletBoundary::FdmTimeDepDirichletBoundary (const boost::shared_ptr< FdmMesher > & mesher, const boost::function< Real(Real)> & valueOnBoundary, Size direction, Side side)
Definition at line 33 of file fdmtimedepdirichletboundary.cpp.
    : indices_(FdmIndicesOnBoundary(mesher->layout(),
                                    direction, side).getIndices()),
      valueOnBoundary_(valueOnBoundary),
      values_(indices_.size()) {
    }
QuantLib::FdmTimeDepDirichletBoundary::FdmTimeDepDirichletBoundary (const boost::shared_ptr< FdmMesher > & mesher, const boost::function< Disposable< Array >(Real)> & valueOnBoundary, Size direction, Side side)
Definition at line 43 of file fdmtimedepdirichletboundary.cpp.
    : indices_(FdmIndicesOnBoundary(mesher->layout(),
                                    direction, side).getIndices()),
      valuesOnBoundary_(valuesOnBoundary),
      values_(indices_.size()) {
    }
Member Function Documentation
void QuantLib::FdmTimeDepDirichletBoundary::applyAfterApplying (array_type &) const [virtual]
This method modifies an array \(u \) so that it satisfies the given condition.
Implements QuantLib::BoundaryCondition< FdmLinearOp >.
Definition at line 66 of file fdmtimedepdirichletboundary.cpp.
References indices_, QL_REQUIRE, QuantLib::Array::size(), and values_.
Referenced by applyAfterSolving().
{
        QL_REQUIRE(indices_.size() == values_.size(),
                   "values on boundary size (" << values_.size()
                   << ") does not match hypersurface size ("
                   << indices_.size() << ")");
        for (std::vector<Size>::const_iterator iter = indices_.begin();
             iter != indices_.end(); ++iter) {
            a[*iter] = values_[iter - indices_.begin()];
        }
    }
void QuantLib::FdmTimeDepDirichletBoundary::applyAfterSolving (array_type &) const [virtual]
This method modifies an array \(u \) so that it satisfies the given condition.
Implements QuantLib::BoundaryCondition< FdmLinearOp >.
Definition at line 77 of file fdmtimedepdirichletboundary.cpp.
References applyAfterApplying().
{
        this->applyAfterApplying(a);
    }
void QuantLib::FdmTimeDepDirichletBoundary::applyBeforeApplying (operator_type &) const [inline, virtual]
This method modifies an operator \(L \) before it is applied to an array \(u \) so that \(v = Lu \) will satisfy the given condition.
Implements QuantLib::BoundaryCondition< FdmLinearOp >.
Definition at line 56 of file fdmtimedepdirichletboundary.hpp.
{}
void QuantLib::FdmTimeDepDirichletBoundary::applyBeforeSolving (operator_type & , array_type & rhs) const [inline, virtual]
This method modifies an operator \(L \) before the linear system \(Lu' = u \) is solved so that \(u' \) will satisfy the given condition.
Implements QuantLib::BoundaryCondition< FdmLinearOp >.
Definition at line 57 of file fdmtimedepdirichletboundary.hpp.
{}
void QuantLib::FdmTimeDepDirichletBoundary::setTime (Time t) [virtual]
This method sets the current time for time-dependent boundary conditions.
Implements QuantLib::BoundaryCondition< FdmLinearOp >.
Definition at line 53 of file fdmtimedepdirichletboundary.cpp.
References QuantLib::Array::begin(), QuantLib::Array::end(), QL_FAIL, valueOnBoundary_, values_, and valuesOnBoundary_.
{
        if (valueOnBoundary_) {
            std::fill(values_.begin(), values_.end(), valueOnBoundary_(t));
        }
        else if (valuesOnBoundary_) {
            values_ = valuesOnBoundary_(t);
            std::cout << "now it s me" << std::endl;
        }
        else {
            QL_FAIL("no time dependent function is defined");
        }
    }
Member Data Documentation
const std::vector<Size> QuantLib::FdmTimeDepDirichletBoundary::indices_ [private]
Definition at line 62 of file fdmtimedepdirichletboundary.hpp.
Referenced by applyAfterApplying().
const boost::function<Real (Real)> QuantLib::FdmTimeDepDirichletBoundary::valueOnBoundary_ [private]
Definition at line 63 of file fdmtimedepdirichletboundary.hpp.
Referenced by setTime().
Array QuantLib::FdmTimeDepDirichletBoundary::values_ [private]
Definition at line 66 of file fdmtimedepdirichletboundary.hpp.
Referenced by applyAfterApplying(), and setTime().
const boost::function<Disposable<Array>Real)> QuantLib::FdmTimeDepDirichletBoundary::valuesOnBoundary_ [private]
Definition at line 64 of file fdmtimedepdirichletboundary.hpp.
Referenced by setTime().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/utilities/fdmtimedepdirichletboundary.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/utilities/fdmtimedepdirichletboundary.cpp