QuantLib: QuantLib::OneFactorGaussianCopula Class Reference
QuantLib::OneFactorGaussianCopula Class Reference
One-factor Gaussian Copula.
#include <onefactorgaussiancopula.hpp>
Public Member Functions
OneFactorGaussianCopula (const Handle< Quote > &correlation, Real maximum=5, Size integrationSteps=50)
Real density (Real m) const
Density function of M.
Real cumulativeZ (Real z) const
Cumulative distribution of Z.
Real cumulativeY (Real y) const
Real testCumulativeY (Real y) const
Real inverseCumulativeY (Real p) const
Private Member Functions
void performCalculations () const
Private Attributes
NormalDistribution density_
CumulativeNormalDistribution cumulative_
InverseCumulativeNormal inverseCumulative_
Detailed Description
One-factor Gaussian Copula.
The copula model
\[ Y_i = a_i\,M+\sqrt{1-a_i^2}\:Z_i \]
is specified here by setting the desnity function for all variables, \(M, Z,\) and also \(Y \) to the standard normal distribution \(\phi(x) = \exp(-x^2/2) / \sqrt{2\pi}. \)
Definition at line 40 of file onefactorgaussiancopula.hpp.
Constructor & Destructor Documentation
QuantLib::OneFactorGaussianCopula::OneFactorGaussianCopula (const Handle< Quote > & correlation, Real maximum = 5, Size integrationSteps = 50) [inline]
Definition at line 42 of file onefactorgaussiancopula.hpp.
References QuantLib::OneFactorCopula::correlation_, and QuantLib::Observer::registerWith().
        : OneFactorCopula (correlation, maximum, integrationSteps) {
            registerWith(correlation_);
        }
Member Function Documentation
Real QuantLib::OneFactorGaussianCopula::cumulativeY (Real y) const [inline, virtual]
overrides the base class implementation based on table data
Reimplemented from QuantLib::OneFactorCopula.
Definition at line 72 of file onefactorgaussiancopula.hpp.
References cumulative_.
{
        return cumulative_(y);
    }
Real QuantLib::OneFactorGaussianCopula::cumulativeZ (Real z) const [inline, virtual]
Cumulative distribution of Z.
Derived classes must override this method and ensure zero mean and unit variance.
Implements QuantLib::OneFactorCopula.
Definition at line 68 of file onefactorgaussiancopula.hpp.
References cumulative_.
{
        return cumulative_(z);
    }
Real QuantLib::OneFactorGaussianCopula::density (Real m) const [inline, virtual]
Density function of M.
Derived classes must override this method and ensure zero mean and unit variance.
Implements QuantLib::OneFactorCopula.
Definition at line 64 of file onefactorgaussiancopula.hpp.
References density_.
{
        return density_(m);
    }
Real QuantLib::OneFactorGaussianCopula::inverseCumulativeY (Real p) const [inline, virtual]
overrides the base class implementation based on table data
Reimplemented from QuantLib::OneFactorCopula.
Definition at line 76 of file onefactorgaussiancopula.hpp.
References inverseCumulative_.
{
        return inverseCumulative_(p);
    }
void QuantLib::OneFactorGaussianCopula::performCalculations () const [inline, private, virtual]
This method must implement any calculations which must be (re)done in order to calculate the desired results.
Implements QuantLib::LazyObject.
Definition at line 57 of file onefactorgaussiancopula.hpp.
{}
Real QuantLib::OneFactorGaussianCopula::testCumulativeY (Real y) const
Definition at line 25 of file onefactorgaussiancopula.cpp.
References anonymous_namespace{marketmodel.cpp}::c, QuantLib::OneFactorCopula::correlation_, QuantLib::OneFactorCopula::dm(), QuantLib::OneFactorCopula::m(), and QuantLib::OneFactorCopula::steps().
{
    //-----------------------------------------------------------------------
        Real c = correlation_->value();
        if (c == 0)
            return CumulativeNormalDistribution()(y);
        if (c == 1)
            return CumulativeNormalDistribution()(y);
        NormalDistribution dz;
        NormalDistribution dm;
        Real minimum = -10;
        Real maximum = +10;
        int steps = 200;
        Real delta = (maximum - minimum) / steps;
        Real cumulated = 0;
        if (c < 0.5) {
            // outer integral -> 1 for c -> 0
            // inner integral -> CumulativeNormal()(y) for c-> 0
            for (Real m = minimum; m < maximum; m += delta)
                for (Real z = minimum; z < (y - std::sqrt(c) * m) / std::sqrt (1. - c);
                     z += delta)
                    cumulated += dm (m) * dz (z);
        }
        else {
            // outer integral -> 1 for c -> 1
            // inner integral -> CumulativeNormal()(y) for c-> 1
            for (Real z = minimum; z < maximum; z += delta)
                for (Real m = minimum; m < (y - std::sqrt(1.0 - c) * z) / std::sqrt(c);
                     m += delta)
                    cumulated += dm (m) * dz (z);
        }
        cumulated *= (delta * delta);
        return cumulated;
    }
Member Data Documentation
CumulativeNormalDistribution QuantLib::OneFactorGaussianCopula::cumulative_ [private]
Definition at line 60 of file onefactorgaussiancopula.hpp.
Referenced by cumulativeY(), and cumulativeZ().
NormalDistribution QuantLib::OneFactorGaussianCopula::density_ [private]
Definition at line 59 of file onefactorgaussiancopula.hpp.
Referenced by density().
InverseCumulativeNormal QuantLib::OneFactorGaussianCopula::inverseCumulative_ [private]
Definition at line 61 of file onefactorgaussiancopula.hpp.
Referenced by inverseCumulativeY().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/onefactorgaussiancopula.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/onefactorgaussiancopula.cpp