QuantLib: QuantLib::FittedBondDiscountCurve::FittingMethod Class Reference
QuantLib::FittedBondDiscountCurve::FittingMethod Class Reference
Base fitting method used to construct a fitted bond discount curve.
#include <fittedbonddiscountcurve.hpp>
Classes
class FittingCost
Public Member Functions
virtual ~FittingMethod ()
virtual Size size () const =0
total number of coefficients to fit/solve for
Array solution () const
output array of results of optimization problem
Integer numberOfIterations () const
final number of iterations used in the optimization problem
Real minimumCostValue () const
final value of cost function after optimization
virtual std::auto_ptr
< FittingMethod > clone () const =0
clone of the current object
Protected Member Functions
FittingMethod (bool constrainAtZero=true)
constructor
void init ()
rerun every time instruments/referenceDate changes
virtual DiscountFactor discountFunction (const Array &x, Time t) const =0
derived classes must set this
Protected Attributes
bool constrainAtZero_
constrains discount function to unity at \(T=0 \), if true
FittedBondDiscountCurve * curve_
internal reference to the FittedBondDiscountCurve instance
Array solution_
solution array found from optimization, set in calculate()
Array guessSolution_
optional guess solution to be passed into constructor.
boost::shared_ptr< FittingCost > costFunction_
base class sets this cost function used in the optimization routine
Private Member Functions
void calculate ()
Private Attributes
Array weights_
Integer numberOfIterations_
Real costValue_
Friends
class FittedBondDiscountCurve
Detailed Description
Base fitting method used to construct a fitted bond discount curve.
This base class provides the specific methodology/strategy used to construct a FittedBondDiscountCurve. Derived classes need only define the virtual function discountFunction() based on the particular fitting method to be implemented, as well as size(), the number of variables to be solved for/optimized. The generic fitting methodology implemented here can be termed nonlinear, in contrast to (typically faster, computationally) linear fitting method.
Todo:
derive the special-case class LinearFittingMethods from FittingMethod. A linear fitting to a set of basis functions \(b_i(t) \) is any fitting of the form
\[ d(t) = \sum_{i=0} c_i b_i(t) \]
i.e., linear in the unknown coefficients \(c_i \). Such a fitting can be reduced to a linear algebra problem \(Ax = b \), and for large numbers of bonds, would typically be much faster computationally than the generic non-linear fitting method.
Warning:
some parameters to the Simplex optimization method may need to be tweaked internally to the class, depending on the fitting method used, in order to get proper/reasonable/faster convergence.
Definition at line 197 of file fittedbonddiscountcurve.hpp.
Constructor & Destructor Documentation
virtual QuantLib::FittedBondDiscountCurve::FittingMethod::~FittingMethod () [inline, virtual]
Definition at line 202 of file fittedbonddiscountcurve.hpp.
{}
QuantLib::FittedBondDiscountCurve::FittingMethod::FittingMethod (bool constrainAtZero = true) [protected]
constructor
Definition at line 178 of file fittedbonddiscountcurve.cpp.
    : constrainAtZero_(constrainAtZero) {}
Member Function Documentation
void QuantLib::FittedBondDiscountCurve::FittingMethod::calculate () [private]
Definition at line 225 of file fittedbonddiscountcurve.cpp.
References QuantLib::Problem::currentValue(), QuantLib::Problem::functionEvaluation(), QuantLib::Problem::functionValue(), QuantLib::Simplex::minimize(), and anonymous_namespace{optimizers.cpp}::simplex.
{
        FittingCost& costFunction = *costFunction_;
        Constraint constraint = NoConstraint();
        // start with the guess solution, if it exists
        Array x(size(), 0.0);
        if (!curve_->guessSolution_.empty()) {
            x = curve_->guessSolution_;
        }
        Simplex simplex(curve_->simplexLambda_);
        Problem problem(costFunction, constraint, x);
        Natural maxStationaryStateIterations = 100;
        Real rootEpsilon = curve_->accuracy_;
        Real functionEpsilon =  curve_->accuracy_;
        Real gradientNormEpsilon = curve_->accuracy_;
        EndCriteria endCriteria(curve_->maxEvaluations_,
                                maxStationaryStateIterations,
                                rootEpsilon,
                                functionEpsilon,
                                gradientNormEpsilon);
        simplex.minimize(problem,endCriteria);
        solution_ = problem.currentValue();
        numberOfIterations_ = problem.functionEvaluation();
        costValue_ = problem.functionValue();
        // save the results as the guess solution, in case of recalculation
        curve_->guessSolution_ = solution_;
    }
virtual std::auto_ptr<FittingMethod> QuantLib::FittedBondDiscountCurve::FittingMethod::clone () const [pure virtual]
clone of the current object
Implemented in QuantLib::SimplePolynomialFitting, QuantLib::CubicBSplinesFitting, QuantLib::SvenssonFitting, QuantLib::NelsonSiegelFitting, and QuantLib::ExponentialSplinesFitting.
virtual DiscountFactor QuantLib::FittedBondDiscountCurve::FittingMethod::discountFunction (const Array & x, Time t) const [protected, pure virtual]
derived classes must set this
user-defined discount curve, as a function of time and an array of unknown fitting coefficients \(x_i \).
Implemented in QuantLib::SimplePolynomialFitting, QuantLib::CubicBSplinesFitting, QuantLib::SvenssonFitting, QuantLib::NelsonSiegelFitting, and QuantLib::ExponentialSplinesFitting.
Referenced by QuantLib::FittedBondDiscountCurve::discountImpl().
void QuantLib::FittedBondDiscountCurve::FittingMethod::init () [protected]
rerun every time instruments/referenceDate changes
Definition at line 182 of file fittedbonddiscountcurve.cpp.
References QuantLib::Annual, QuantLib::Compounded, QuantLib::BondFunctions::duration(), QuantLib::Duration::Modified, and QuantLib::BondFunctions::yield().
{
        // yield conventions
        DayCounter yieldDC = curve_->dayCounter();
        Compounding yieldComp = Compounded;
        Frequency yieldFreq = Annual;
        Size n = curve_->bondHelpers_.size();
        costFunction_ = shared_ptr<FittingCost>(new FittingCost(this));
        costFunction_->firstCashFlow_.resize(n);
        weights_ = Array(n);
        Real squaredSum = 0.0;
        for (Size i=0; i<curve_->bondHelpers_.size(); ++i) {
            shared_ptr<Bond> bond = curve_->bondHelpers_[i]->bond();
            Leg leg = bond->cashflows();
            Real cleanPrice = curve_->bondHelpers_[i]->quote()->value();
            Date bondSettlement = bond->settlementDate();
            Rate ytm = BondFunctions::yield(*bond, cleanPrice,
                                            yieldDC, yieldComp, yieldFreq,
                                            bondSettlement);
            Time dur = BondFunctions::duration(*bond, ytm,
                                               yieldDC, yieldComp, yieldFreq,
                                               Duration::Modified,
                                               bondSettlement);
            weights_[i] = 1.0/dur;
            squaredSum += weights_[i]*weights_[i];
            const Leg& cf = bond->cashflows();
            for (Size k=0; k<cf.size(); ++k) {
                if (!cf[k]->hasOccurred(bondSettlement, false)) {
                    costFunction_->firstCashFlow_[i] = k;
                    break;
                }
            }
        }
        weights_ /= std::sqrt(squaredSum);
    }
Real QuantLib::FittedBondDiscountCurve::FittingMethod::minimumCostValue () const [inline]
final value of cost function after optimization
Definition at line 288 of file fittedbonddiscountcurve.hpp.
{
        return costValue_;
    }
Integer QuantLib::FittedBondDiscountCurve::FittingMethod::numberOfIterations () const [inline]
final number of iterations used in the optimization problem
Definition at line 283 of file fittedbonddiscountcurve.hpp.
References numberOfIterations_.
{
        return numberOfIterations_;
    }
virtual Size QuantLib::FittedBondDiscountCurve::FittingMethod::size () const [pure virtual]
total number of coefficients to fit/solve for
Implemented in QuantLib::SimplePolynomialFitting, QuantLib::CubicBSplinesFitting, QuantLib::SvenssonFitting, QuantLib::NelsonSiegelFitting, and QuantLib::ExponentialSplinesFitting.
Array QuantLib::FittedBondDiscountCurve::FittingMethod::solution () const [inline]
output array of results of optimization problem
Definition at line 292 of file fittedbonddiscountcurve.hpp.
{
        return solution_;
    }
Friends And Related Function Documentation
friend class FittedBondDiscountCurve [friend]
Definition at line 198 of file fittedbonddiscountcurve.hpp.
Member Data Documentation
bool QuantLib::FittedBondDiscountCurve::FittingMethod::constrainAtZero_ [protected]
constrains discount function to unity at \(T=0 \), if true
Definition at line 226 of file fittedbonddiscountcurve.hpp.
Referenced by QuantLib::ExponentialSplinesFitting::discountFunction(), QuantLib::CubicBSplinesFitting::discountFunction(), QuantLib::SimplePolynomialFitting::discountFunction(), and QuantLib::ExponentialSplinesFitting::size().
boost::shared_ptr<FittingCost> QuantLib::FittedBondDiscountCurve::FittingMethod::costFunction_ [protected]
base class sets this cost function used in the optimization routine
Definition at line 237 of file fittedbonddiscountcurve.hpp.
Real QuantLib::FittedBondDiscountCurve::FittingMethod::costValue_ [private]
Definition at line 247 of file fittedbonddiscountcurve.hpp.
FittedBondDiscountCurve* QuantLib::FittedBondDiscountCurve::FittingMethod::curve_ [protected]
internal reference to the FittedBondDiscountCurve instance
Definition at line 228 of file fittedbonddiscountcurve.hpp.
Array QuantLib::FittedBondDiscountCurve::FittingMethod::guessSolution_ [protected]
optional guess solution to be passed into constructor.
The idea is to use a previous solution as a guess solution to the discount curve, in an attempt to speed up calculations.
Definition at line 235 of file fittedbonddiscountcurve.hpp.
Integer QuantLib::FittedBondDiscountCurve::FittingMethod::numberOfIterations_ [private]
Definition at line 245 of file fittedbonddiscountcurve.hpp.
Referenced by numberOfIterations().
Array QuantLib::FittedBondDiscountCurve::FittingMethod::solution_ [protected]
solution array found from optimization, set in calculate()
Definition at line 230 of file fittedbonddiscountcurve.hpp.
Referenced by QuantLib::FittedBondDiscountCurve::discountImpl().
Array QuantLib::FittedBondDiscountCurve::FittingMethod::weights_ [private]
Definition at line 242 of file fittedbonddiscountcurve.hpp.
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/yield/fittedbonddiscountcurve.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/yield/fittedbonddiscountcurve.cpp