QuantLib: QuantLib::DeltaVolQuote Class Reference
QuantLib::DeltaVolQuote Class Reference
Class for the quotation of delta vs vol.
#include <deltavolquote.hpp>
Public Types
enum DeltaType { Spot, Fwd, PaSpot, PaFwd }
enum AtmType {
AtmNull, AtmSpot, AtmFwd, AtmDeltaNeutral,
AtmVegaMax, AtmGammaMax, AtmPutCall50
}
Public Member Functions
DeltaVolQuote (Real delta, const Handle< Quote > &vol, Time maturity, DeltaType deltaType)
DeltaVolQuote (const Handle< Quote > &vol, DeltaType deltaType, Time maturity, AtmType atmType)
void update ()
Real value () const
returns the current value
Real delta () const
Time maturity () const
AtmType atmType () const
DeltaType deltaType () const
bool isValid () const
returns true if the Quote holds a valid value
Private Attributes
Real delta_
Handle< Quote > vol_
DeltaType deltaType_
Time maturity_
AtmType atmType_
Detailed Description
Class for the quotation of delta vs vol.
It includes the various delta quotation types in FX markets as well as ATM types.
Definition at line 36 of file deltavolquote.hpp.
Member Enumeration Documentation
enum QuantLib::DeltaVolQuote::AtmType
Enumerator:
AtmNull
AtmSpot
AtmFwd
AtmDeltaNeutral
AtmVegaMax
AtmGammaMax
AtmPutCall50
Definition at line 46 of file deltavolquote.hpp.
                     {
            AtmNull,         // Default, if not an atm quote
            AtmSpot,         // K=S_0
            AtmFwd,          // K=F
            AtmDeltaNeutral, // Call Delta = Put Delta
            AtmVegaMax,      // K such that Vega is Maximum
            AtmGammaMax,     // K such that Gamma is Maximum
            AtmPutCall50     // K such that Call Delta=0.50 (only for Fwd Delta)
        };
enum QuantLib::DeltaVolQuote::DeltaType
Enumerator:
Spot
Fwd
PaSpot
PaFwd
Definition at line 39 of file deltavolquote.hpp.
                       {
            Spot,        // Spot Delta, e.g. usual Black Scholes delta
            Fwd,         // Forward Delta
            PaSpot,      // Premium Adjusted Spot Delta
            PaFwd        // Premium Adjusted Forward Delta
        };
Constructor & Destructor Documentation
QuantLib::DeltaVolQuote::DeltaVolQuote (Real delta, const Handle< Quote > & vol, Time maturity, DeltaType deltaType)
Definition at line 24 of file deltavolquote.cpp.
References QuantLib::Observer::registerWith(), and vol_.
    : delta_(delta), vol_(vol), deltaType_(deltaType), maturity_(maturity),
      atmType_(DeltaVolQuote::AtmNull) {
        registerWith(vol_); // observe vol
    }
QuantLib::DeltaVolQuote::DeltaVolQuote (const Handle< Quote > & vol, DeltaType deltaType, Time maturity, AtmType atmType)
Definition at line 35 of file deltavolquote.cpp.
References QuantLib::Observer::registerWith(), and vol_.
    : vol_(vol), deltaType_(deltaType), maturity_(maturity), atmType_(atmType) {
        registerWith(vol_);
    }
Member Function Documentation
DeltaVolQuote::AtmType QuantLib::DeltaVolQuote::atmType () const
Definition at line 65 of file deltavolquote.cpp.
References atmType_.
{
        return atmType_;
    }
Real QuantLib::DeltaVolQuote::delta () const
Definition at line 49 of file deltavolquote.cpp.
References delta_.
{
        return delta_;
    }
DeltaVolQuote::DeltaType QuantLib::DeltaVolQuote::deltaType () const
Definition at line 69 of file deltavolquote.cpp.
References deltaType_.
{
        return deltaType_;
    }
bool QuantLib::DeltaVolQuote::isValid () const [virtual]
returns true if the Quote holds a valid value
Implements QuantLib::Quote.
Definition at line 57 of file deltavolquote.cpp.
References QuantLib::Handle< T >::empty(), and vol_.
{
        return !vol_.empty() && vol_->isValid();
    }
Time QuantLib::DeltaVolQuote::maturity () const
Definition at line 53 of file deltavolquote.cpp.
References maturity_.
{
        return maturity_;
    }
void QuantLib::DeltaVolQuote::update () [virtual]
This method must be implemented in derived classes. An instance of Observer does not call this method directly: instead, it will be called by the observables the instance registered with when they need to notify any changes.
Implements QuantLib::Observer.
Definition at line 61 of file deltavolquote.cpp.
References QuantLib::Observable::notifyObservers().
{
        notifyObservers(); // let observers know, that something has changed
    }
Real QuantLib::DeltaVolQuote::value () const [virtual]
returns the current value
Implements QuantLib::Quote.
Definition at line 45 of file deltavolquote.cpp.
References vol_.
{
        return vol_->value();
    }
Member Data Documentation
AtmType QuantLib::DeltaVolQuote::atmType_ [private]
Definition at line 84 of file deltavolquote.hpp.
Referenced by atmType().
Real QuantLib::DeltaVolQuote::delta_ [private]
Definition at line 80 of file deltavolquote.hpp.
Referenced by delta().
DeltaType QuantLib::DeltaVolQuote::deltaType_ [private]
Definition at line 82 of file deltavolquote.hpp.
Referenced by deltaType().
Time QuantLib::DeltaVolQuote::maturity_ [private]
Definition at line 83 of file deltavolquote.hpp.
Referenced by maturity().
Handle<Quote> QuantLib::DeltaVolQuote::vol_ [private]
Definition at line 81 of file deltavolquote.hpp.
Referenced by DeltaVolQuote(), isValid(), and value().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/fx/deltavolquote.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/fx/deltavolquote.cpp