QuantLib: QuantLib::DiscretizedCallableFixedRateBond Class Reference
QuantLib::DiscretizedCallableFixedRateBond Class Reference
#include <discretizedcallablefixedratebond.hpp>
Public Member Functions
DiscretizedCallableFixedRateBond (const CallableBond::arguments &, const Date &referenceDate, const DayCounter &dayCounter)
void reset (Size size)
std::vector< Time > mandatoryTimes () const
Protected Member Functions
void preAdjustValuesImpl ()
void postAdjustValuesImpl ()
Private Member Functions
void applyCallability (Size i)
void addCoupon (Size i)
Private Attributes
CallableBond::arguments arguments_
Time redemptionTime_
std::vector< Time > couponTimes_
std::vector< Time > callabilityTimes_
Detailed Description
Definition at line 32 of file discretizedcallablefixedratebond.hpp.
Constructor & Destructor Documentation
QuantLib::DiscretizedCallableFixedRateBond::DiscretizedCallableFixedRateBond (const CallableBond::arguments & args, const Date & referenceDate, const DayCounter & dayCounter)
Definition at line 39 of file discretizedcallablefixedratebond.cpp.
References QuantLib::CallableBond::arguments::callabilityDates, callabilityTimes_, QuantLib::CallableBond::arguments::couponDates, couponTimes_, QuantLib::CallableBond::arguments::redemptionDate, redemptionTime_, QuantLib::anonymous_namespace{discretizedcallablefixedratebond.cpp}::withinNextWeek(), and QuantLib::DayCounter::yearFraction().
    : arguments_(args) {
        redemptionTime_ = dayCounter.yearFraction(referenceDate,
                                                  args.redemptionDate);
        couponTimes_.resize(args.couponDates.size());
        for (Size i=0; i<couponTimes_.size(); ++i)
            couponTimes_[i] =
                dayCounter.yearFraction(referenceDate,
                                        args.couponDates[i]);
        callabilityTimes_.resize(args.callabilityDates.size());
        for (Size i=0; i<callabilityTimes_.size(); ++i)
            callabilityTimes_[i] =
                dayCounter.yearFraction(referenceDate,
                                        args.callabilityDates[i]);
        // similar to the tree swaption engine, we collapse similar coupon
        // and exercise dates to avoid mispricing. Delete if unnecessary.
        for (Size i=0; i<callabilityTimes_.size(); i++) {
            Time exerciseTime = callabilityTimes_[i];
            for (Size j=0; j<couponTimes_.size(); j++) {
                if (withinNextWeek(exerciseTime, couponTimes_[j]))
                    couponTimes_[j] = exerciseTime;
            }
        }
    }
Member Function Documentation
void QuantLib::DiscretizedCallableFixedRateBond::addCoupon (Size i) [private]
Definition at line 148 of file discretizedcallablefixedratebond.cpp.
References arguments_, QuantLib::CallableBond::arguments::couponAmounts, and QuantLib::DiscretizedAsset::values_.
Referenced by postAdjustValuesImpl().
{
        values_ += arguments_.couponAmounts[i];
    }
void QuantLib::DiscretizedCallableFixedRateBond::applyCallability (Size i) [private]
Definition at line 126 of file discretizedcallablefixedratebond.cpp.
References arguments_, QuantLib::Callability::Call, QuantLib::CallableBond::arguments::callabilityPrices, QuantLib::Callability::Put, QuantLib::CallableBond::arguments::putCallSchedule, QL_FAIL, QuantLib::Array::size(), and QuantLib::DiscretizedAsset::values_.
Referenced by postAdjustValuesImpl().
{
        Size j;
        switch (arguments_.putCallSchedule[i]->type() ) {
          case Callability::Call:
            for (j=0; j<values_.size(); j++) {
                values_[j] =
                    std::min(arguments_.callabilityPrices[i],
                             values_[j]);
            }
            break;
          case Callability::Put:
            for (j=0; j<values_.size(); j++) {
                values_[j] = std::max(values_[j],
                                      arguments_.callabilityPrices[i]);
            }
            break;
          default:
            QL_FAIL("unknown callability type");
        }
    }
std::vector< Time > QuantLib::DiscretizedCallableFixedRateBond::mandatoryTimes () const [virtual]
This method returns the times at which the numerical method should stop while rolling back the asset. Typical examples include payment times, exercise times and such.
Note:
The returned values are not guaranteed to be sorted.
Implements QuantLib::DiscretizedAsset.
Definition at line 79 of file discretizedcallablefixedratebond.cpp.
References callabilityTimes_, couponTimes_, redemptionTime_, and anonymous_namespace{quantlibbenchmark.cpp}::t.
Referenced by QuantLib::TreeCallableFixedRateBondEngine::calculate().
{
        std::vector<Time> times;
        Time t;
        Size i;
        t = redemptionTime_;
        if (t >= 0.0) {
            times.push_back(t);
        }
        for (i=0; i<couponTimes_.size(); i++) {
            t = couponTimes_[i];
            if (t >= 0.0) {
                times.push_back(t);
            }
        }
        for (i=0; i<callabilityTimes_.size(); i++) {
            t = callabilityTimes_[i];
            if (t >= 0.0) {
                times.push_back(t);
            }
        }
        return times;
    }
void QuantLib::DiscretizedCallableFixedRateBond::postAdjustValuesImpl () [protected, virtual]
This method performs the actual post-adjustment
Reimplemented from QuantLib::DiscretizedAsset.
Definition at line 110 of file discretizedcallablefixedratebond.cpp.
References addCoupon(), applyCallability(), callabilityTimes_, couponTimes_, QuantLib::DiscretizedAsset::isOnTime(), and anonymous_namespace{quantlibbenchmark.cpp}::t.
{
        for (Size i=0; i<callabilityTimes_.size(); i++) {
            Time t = callabilityTimes_[i];
            if (t >= 0.0 && isOnTime(t)) {
                applyCallability(i);
            }
        }
        for (Size i=0; i<couponTimes_.size(); i++) {
            Time t = couponTimes_[i];
            if (t >= 0.0 && isOnTime(t)) {
                addCoupon(i);
            }
        }
    }
void QuantLib::DiscretizedCallableFixedRateBond::preAdjustValuesImpl () [protected, virtual]
This method performs the actual pre-adjustment
Reimplemented from QuantLib::DiscretizedAsset.
Definition at line 107 of file discretizedcallablefixedratebond.cpp.
{ }
void QuantLib::DiscretizedCallableFixedRateBond::reset (Size size) [virtual]
This method should initialize the asset values to an Array of the given size and with values depending on the particular asset.
Implements QuantLib::DiscretizedAsset.
Definition at line 73 of file discretizedcallablefixedratebond.cpp.
References QuantLib::DiscretizedAsset::adjustValues(), arguments_, QuantLib::CallableBond::arguments::redemption, and QuantLib::DiscretizedAsset::values_.
{
        values_ = Array(size, arguments_.redemption);
        adjustValues();
    }
Member Data Documentation
CallableBond::arguments QuantLib::DiscretizedCallableFixedRateBond::arguments_ [private]
Definition at line 45 of file discretizedcallablefixedratebond.hpp.
Referenced by addCoupon(), applyCallability(), and reset().
std::vector<Time> QuantLib::DiscretizedCallableFixedRateBond::callabilityTimes_ [private]
Definition at line 48 of file discretizedcallablefixedratebond.hpp.
Referenced by DiscretizedCallableFixedRateBond(), mandatoryTimes(), and postAdjustValuesImpl().
std::vector<Time> QuantLib::DiscretizedCallableFixedRateBond::couponTimes_ [private]
Definition at line 47 of file discretizedcallablefixedratebond.hpp.
Referenced by DiscretizedCallableFixedRateBond(), mandatoryTimes(), and postAdjustValuesImpl().
Time QuantLib::DiscretizedCallableFixedRateBond::redemptionTime_ [private]
Definition at line 46 of file discretizedcallablefixedratebond.hpp.
Referenced by DiscretizedCallableFixedRateBond(), and mandatoryTimes().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/callablebonds/discretizedcallablefixedratebond.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/callablebonds/discretizedcallablefixedratebond.cpp