QuantLib: ExtendedTreesTest Class Reference
ExtendedTreesTest Class Reference
#include <extendedtrees.hpp>
Static Public Member Functions
static void testJRBinomialEngines ()
static void testCRRBinomialEngines ()
static void testEQPBinomialEngines ()
static void testTGEOBinomialEngines ()
static void testTIANBinomialEngines ()
static void testLRBinomialEngines ()
static void testJOSHIBinomialEngines ()
static
boost::unit_test_framework::test_suite * suite ()
Detailed Description
Definition at line 28 of file extendedtrees.hpp.
Member Function Documentation
test_suite * ExtendedTreesTest::suite () [static]
Definition at line 386 of file extendedtrees.cpp.
References QUANTLIB_TEST_CASE, testCRRBinomialEngines(), testEQPBinomialEngines(), testJOSHIBinomialEngines(), testJRBinomialEngines(), testLRBinomialEngines(), testTGEOBinomialEngines(), and testTIANBinomialEngines().
Referenced by init_unit_test_suite().
{
    test_suite* suite = BOOST_TEST_SUITE("European option tests");
    suite->add(QUANTLIB_TEST_CASE(&ExtendedTreesTest::testJRBinomialEngines));
    suite->add(QUANTLIB_TEST_CASE(&ExtendedTreesTest::testCRRBinomialEngines));
    suite->add(QUANTLIB_TEST_CASE(&ExtendedTreesTest::testEQPBinomialEngines));
    suite->add(QUANTLIB_TEST_CASE(&ExtendedTreesTest::testTGEOBinomialEngines));
    suite->add(QUANTLIB_TEST_CASE(&ExtendedTreesTest::testTIANBinomialEngines));
    suite->add(QUANTLIB_TEST_CASE(&ExtendedTreesTest::testLRBinomialEngines));
    suite->add(QUANTLIB_TEST_CASE(
                               &ExtendedTreesTest::testJOSHIBinomialEngines));
    return suite;
}
void ExtendedTreesTest::testCRRBinomialEngines () [static]
Definition at line 284 of file extendedtrees.cpp.
References anonymous_namespace{europeanoption.cpp}::CRR, and anonymous_namespace{europeanoption.cpp}::testEngineConsistency().
Referenced by suite().
{
    BOOST_MESSAGE("Testing time-dependent CRR binomial European engines "
                  "against analytic results...");
    SavedSettings backup;
    EngineType engine = CRR;
    Size steps = 501;
    std::map<std::string,Real> relativeTol;
    relativeTol["value"] = 0.02;
    relativeTol["delta"] = 1.0e-3;
    relativeTol["gamma"] = 1.0e-4;
    relativeTol["theta"] = 0.03;
    testEngineConsistency(engine, steps, relativeTol);
}
void ExtendedTreesTest::testEQPBinomialEngines () [static]
Definition at line 301 of file extendedtrees.cpp.
References anonymous_namespace{europeanoption.cpp}::EQP, and anonymous_namespace{europeanoption.cpp}::testEngineConsistency().
Referenced by suite().
{
    BOOST_MESSAGE("Testing time-dependent EQP binomial European engines "
                  "against analytic results...");
    SavedSettings backup;
    EngineType engine = EQP;
    Size steps = 501;
    std::map<std::string,Real> relativeTol;
    relativeTol["value"] = 0.02;
    relativeTol["delta"] = 1.0e-3;
    relativeTol["gamma"] = 1.0e-4;
    relativeTol["theta"] = 0.03;
    testEngineConsistency(engine, steps, relativeTol);
}
void ExtendedTreesTest::testJOSHIBinomialEngines () [static]
Definition at line 369 of file extendedtrees.cpp.
References anonymous_namespace{europeanoption.cpp}::JOSHI, and anonymous_namespace{europeanoption.cpp}::testEngineConsistency().
Referenced by suite().
{
    BOOST_MESSAGE("Testing time-dependent Joshi binomial European engines "
                  "against analytic results...");
    SavedSettings backup;
    EngineType engine = JOSHI;
    Size steps = 251;
    std::map<std::string,Real> relativeTol;
    relativeTol["value"] = 1.0e-7;
    relativeTol["delta"] = 1.0e-3;
    relativeTol["gamma"] = 1.0e-4;
    relativeTol["theta"] = 0.03;
    testEngineConsistency(engine, steps, relativeTol);
}
void ExtendedTreesTest::testJRBinomialEngines () [static]
Definition at line 267 of file extendedtrees.cpp.
References anonymous_namespace{europeanoption.cpp}::JR, and anonymous_namespace{europeanoption.cpp}::testEngineConsistency().
Referenced by suite().
{
    BOOST_MESSAGE("Testing time-dependent JR binomial European engines "
                  "against analytic results...");
    SavedSettings backup;
    EngineType engine = JR;
    Size steps = 251;
    std::map<std::string,Real> relativeTol;
    relativeTol["value"] = 0.002;
    relativeTol["delta"] = 1.0e-3;
    relativeTol["gamma"] = 1.0e-4;
    relativeTol["theta"] = 0.03;
    testEngineConsistency(engine, steps, relativeTol);
}
void ExtendedTreesTest::testLRBinomialEngines () [static]
Definition at line 352 of file extendedtrees.cpp.
References anonymous_namespace{europeanoption.cpp}::LR, and anonymous_namespace{europeanoption.cpp}::testEngineConsistency().
Referenced by suite().
{
    BOOST_MESSAGE("Testing time-dependent LR binomial European engines "
                  "against analytic results...");
    SavedSettings backup;
    EngineType engine = LR;
    Size steps = 251;
    std::map<std::string,Real> relativeTol;
    relativeTol["value"] = 1.0e-6;
    relativeTol["delta"] = 1.0e-3;
    relativeTol["gamma"] = 1.0e-4;
    relativeTol["theta"] = 0.03;
    testEngineConsistency(engine, steps, relativeTol);
}
void ExtendedTreesTest::testTGEOBinomialEngines () [static]
Definition at line 318 of file extendedtrees.cpp.
References anonymous_namespace{europeanoption.cpp}::testEngineConsistency(), and anonymous_namespace{europeanoption.cpp}::TGEO.
Referenced by suite().
{
    BOOST_MESSAGE("Testing time-dependent TGEO binomial European engines "
                  "against analytic results...");
    SavedSettings backup;
    EngineType engine = TGEO;
    Size steps = 251;
    std::map<std::string,Real> relativeTol;
    relativeTol["value"] = 0.002;
    relativeTol["delta"] = 1.0e-3;
    relativeTol["gamma"] = 1.0e-4;
    relativeTol["theta"] = 0.03;
    testEngineConsistency(engine, steps, relativeTol);
}
void ExtendedTreesTest::testTIANBinomialEngines () [static]
Definition at line 335 of file extendedtrees.cpp.
References anonymous_namespace{europeanoption.cpp}::testEngineConsistency(), and anonymous_namespace{europeanoption.cpp}::TIAN.
Referenced by suite().
{
    BOOST_MESSAGE("Testing time-dependent TIAN binomial European engines "
                  "against analytic results...");
    SavedSettings backup;
    EngineType engine = TIAN;
    Size steps = 251;
    std::map<std::string,Real> relativeTol;
    relativeTol["value"] = 0.002;
    relativeTol["delta"] = 1.0e-3;
    relativeTol["gamma"] = 1.0e-4;
    relativeTol["theta"] = 0.03;
    testEngineConsistency(engine, steps, relativeTol);
}
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/extendedtrees.hpp
/home/deriversatile/QuantLib/QuantLibQt/test-suite/extendedtrees.cpp