QuantLib: QuantLib::ExtendedBlackVarianceCurve Class Reference
QuantLib::ExtendedBlackVarianceCurve Class Reference
Black volatility curve modelled as variance curve.
#include <extendedblackvariancecurve.hpp>
Public Member Functions
ExtendedBlackVarianceCurve (const Date &referenceDate, const std::vector< Date > &dates, const std::vector< Handle< Quote > > &volatilities, const DayCounter &dayCounter, bool forceMonotoneVariance=true)
DayCounter dayCounter () const
the day counter used for date/time conversion
Date maxDate () const
the latest date for which the curve can return values
Real minStrike () const
the minimum strike for which the term structure can return vols
Real maxStrike () const
the maximum strike for which the term structure can return vols
template<class Interpolator >
void setInterpolation (const Interpolator &i=Interpolator())
void accept (AcyclicVisitor &)
void update ()
Private Member Functions
Real blackVarianceImpl (Time t, Real) const
Black variance calculation.
void setVariances ()
Private Attributes
DayCounter dayCounter_
Date maxDate_
std::vector< Handle< Quote > > volatilities_
std::vector< Time > times_
std::vector< Real > variances_
Interpolation varianceCurve_
bool forceMonotoneVariance_
Detailed Description
Black volatility curve modelled as variance curve.
This class is similar to BlackVarianceCurve, but extends it to use quotes for the input volatilities.
Definition at line 38 of file extendedblackvariancecurve.hpp.
Constructor & Destructor Documentation
QuantLib::ExtendedBlackVarianceCurve::ExtendedBlackVarianceCurve (const Date & referenceDate, const std::vector< Date > & dates, const std::vector< Handle< Quote > > & volatilities, const DayCounter & dayCounter, bool forceMonotoneVariance = true)
Definition at line 25 of file extendedblackvariancecurve.cpp.
References QL_REQUIRE, QuantLib::Observer::registerWith(), setVariances(), QuantLib::TermStructure::timeFromReference(), times_, variances_, and volatilities_.
    : BlackVarianceTermStructure(referenceDate),
      dayCounter_(dayCounter), maxDate_(dates.back()),
      volatilities_(volatilities),
      forceMonotoneVariance_(forceMonotoneVariance) {
        QL_REQUIRE(dates.size() == volatilities_.size(),
                   "size mismatch between dates and volatilities");
        QL_REQUIRE(dates[0] > referenceDate,
                   "cannot have dates_[0] <= referenceDate");
        variances_ = std::vector<Real>(dates.size()+1);
        times_ = std::vector<Time>(dates.size()+1);
        times_[0] = 0.0;
        for (Size j=1; j<=dates.size(); ++j) {
            times_[j] = timeFromReference(dates[j-1]);
            QL_REQUIRE(times_[j]>times_[j-1],
                       "dates must be sorted unique!");
        }
        setVariances();
        setInterpolation<Linear>();
        for (Size j=0; j<volatilities_.size(); ++j)
            registerWith(volatilities_[j]);
    }
Member Function Documentation
void QuantLib::ExtendedBlackVarianceCurve::accept (AcyclicVisitor & v) [inline, virtual]
Reimplemented from QuantLib::BlackVarianceTermStructure.
Definition at line 86 of file extendedblackvariancecurve.hpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Visitor< T >::visit().
{
        Visitor<ExtendedBlackVarianceCurve>* v1 =
            dynamic_cast<Visitor<ExtendedBlackVarianceCurve>*>(&v);
        if (v1 != 0)
            v1->visit(*this);
        else
            BlackVarianceTermStructure::accept(v);
    }
Real QuantLib::ExtendedBlackVarianceCurve::blackVarianceImpl (Time t, Real strike) const [private, virtual]
Black variance calculation.
Implements QuantLib::BlackVolTermStructure.
Definition at line 75 of file extendedblackvariancecurve.cpp.
References times_, and varianceCurve_.
{
        if (t<=times_.back()) {
            return varianceCurve_(t, true);
        } else {
            return varianceCurve_(times_.back(), true)*t/times_.back();
        }
    }
DayCounter QuantLib::ExtendedBlackVarianceCurve::dayCounter () const [inline, virtual]
the day counter used for date/time conversion
Reimplemented from QuantLib::TermStructure.
Definition at line 47 of file extendedblackvariancecurve.hpp.
References dayCounter_.
{ return dayCounter_; }
Date QuantLib::ExtendedBlackVarianceCurve::maxDate () const [inline, virtual]
the latest date for which the curve can return values
Implements QuantLib::TermStructure.
Definition at line 74 of file extendedblackvariancecurve.hpp.
References maxDate_.
{
        return maxDate_;
    }
Real QuantLib::ExtendedBlackVarianceCurve::maxStrike () const [inline, virtual]
the maximum strike for which the term structure can return vols
Implements QuantLib::VolatilityTermStructure.
Definition at line 82 of file extendedblackvariancecurve.hpp.
References QL_MAX_REAL.
{
        return QL_MAX_REAL;
    }
Real QuantLib::ExtendedBlackVarianceCurve::minStrike () const [inline, virtual]
the minimum strike for which the term structure can return vols
Implements QuantLib::VolatilityTermStructure.
Definition at line 78 of file extendedblackvariancecurve.hpp.
References QL_MIN_REAL.
{
        return QL_MIN_REAL;
    }
template<class Interpolator > void QuantLib::ExtendedBlackVarianceCurve::setInterpolation (const Interpolator & i = Interpolator()) [inline]
Definition at line 53 of file extendedblackvariancecurve.hpp.
References QuantLib::Observable::notifyObservers(), times_, QuantLib::Interpolation::update(), varianceCurve_, and variances_.
{
            varianceCurve_ = i.interpolate(times_.begin(), times_.end(),
                                           variances_.begin());
            varianceCurve_.update();
            notifyObservers();
        }
void QuantLib::ExtendedBlackVarianceCurve::setVariances () [private]
Definition at line 58 of file extendedblackvariancecurve.cpp.
References forceMonotoneVariance_, QL_REQUIRE, anonymous_namespace{distributions.cpp}::sigma, times_, variances_, and volatilities_.
Referenced by ExtendedBlackVarianceCurve(), and update().
{
        variances_[0] = 0.0;
        for (Size j=1; j<=volatilities_.size(); j++) {
            Volatility sigma = volatilities_[j-1]->value();
            variances_[j] = times_[j] * sigma * sigma;
            QL_REQUIRE(variances_[j]>=variances_[j-1]
                       || !forceMonotoneVariance_,
                       "variance must be non-decreasing");
        }
    }
void QuantLib::ExtendedBlackVarianceCurve::update () [virtual]
This method must be implemented in derived classes. An instance of Observer does not call this method directly: instead, it will be called by the observables the instance registered with when they need to notify any changes.
Reimplemented from QuantLib::TermStructure.
Definition at line 69 of file extendedblackvariancecurve.cpp.
References QuantLib::Observable::notifyObservers(), setVariances(), QuantLib::Interpolation::update(), and varianceCurve_.
{
        setVariances();
        varianceCurve_.update();
        notifyObservers();
    }
Member Data Documentation
DayCounter QuantLib::ExtendedBlackVarianceCurve::dayCounter_ [private]
Reimplemented from QuantLib::TermStructure.
Definition at line 65 of file extendedblackvariancecurve.hpp.
Referenced by dayCounter().
bool QuantLib::ExtendedBlackVarianceCurve::forceMonotoneVariance_ [private]
Definition at line 71 of file extendedblackvariancecurve.hpp.
Referenced by setVariances().
Date QuantLib::ExtendedBlackVarianceCurve::maxDate_ [private]
Definition at line 66 of file extendedblackvariancecurve.hpp.
Referenced by maxDate().
std::vector<Time> QuantLib::ExtendedBlackVarianceCurve::times_ [private]
Definition at line 68 of file extendedblackvariancecurve.hpp.
Referenced by blackVarianceImpl(), ExtendedBlackVarianceCurve(), setInterpolation(), and setVariances().
Interpolation QuantLib::ExtendedBlackVarianceCurve::varianceCurve_ [private]
Definition at line 70 of file extendedblackvariancecurve.hpp.
Referenced by blackVarianceImpl(), setInterpolation(), and update().
std::vector<Real> QuantLib::ExtendedBlackVarianceCurve::variances_ [private]
Definition at line 69 of file extendedblackvariancecurve.hpp.
Referenced by ExtendedBlackVarianceCurve(), setInterpolation(), and setVariances().
std::vector<Handle<Quote> > QuantLib::ExtendedBlackVarianceCurve::volatilities_ [private]
Definition at line 67 of file extendedblackvariancecurve.hpp.
Referenced by ExtendedBlackVarianceCurve(), and setVariances().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/volatility/extendedblackvariancecurve.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/volatility/extendedblackvariancecurve.cpp