QuantLib: MarketModelSmmCapletHomoCalibrationTest Class Reference
MarketModelSmmCapletHomoCalibrationTest Class Reference
#include <marketmodel_smmcaplethomocalibration.hpp>
Static Public Member Functions
static void testFunction ()
static void testPeriodFunction ()
static void testSphereCylinder ()
static
boost::unit_test_framework::test_suite * suite ()
Detailed Description
Definition at line 28 of file marketmodel_smmcaplethomocalibration.hpp.
Member Function Documentation
test_suite * MarketModelSmmCapletHomoCalibrationTest::suite () [static]
Definition at line 817 of file marketmodel_smmcaplethomocalibration.cpp.
References QUANTLIB_TEST_CASE, testFunction(), testPeriodFunction(), and testSphereCylinder().
Referenced by init_unit_test_suite().
{
    test_suite* suite = BOOST_TEST_SUITE("SMM Caplet homogeneous calibration test");
    #if !defined(QL_NO_UBLAS_SUPPORT)
    suite->add(QUANTLIB_TEST_CASE(
                     &MarketModelSmmCapletHomoCalibrationTest::testFunction));
    suite->add(QUANTLIB_TEST_CASE(
               &MarketModelSmmCapletHomoCalibrationTest::testPeriodFunction));
    #endif
    // FLOATING_POINT_EXCEPTION
    suite->add(QUANTLIB_TEST_CASE(
               &MarketModelSmmCapletHomoCalibrationTest::testSphereCylinder));
    return suite;
}
void MarketModelSmmCapletHomoCalibrationTest::testFunction () [static]
Definition at line 417 of file marketmodel_smmcaplethomocalibration.cpp.
References anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::a_, anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::b_, anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::beta_, anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::c_, QuantLib::CTSMMCapletCalibration::calibrate(), QuantLib::CTSMMCapletCalibration::capletMaxError(), QuantLib::CTSMMCapletCalibration::capletRmsError(), anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::capletVols_, anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::d_, QuantLib::CTSMMCapletCalibration::deformationSize(), anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::displacement_, QuantLib::CTSMMCapletCalibration::failures(), anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::longTermCorrelation_, anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::numberOfFactors_, QuantLib::io::ordinal(), anonymous_namespace{marketmodel.cpp}::printReport_, QL_FIXED, QuantLib::io::rate(), anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::rateTimes_, QuantLib::io::sequence(), anonymous_namespace{inflationvolatility.cpp}::setup(), QuantLib::CTSMMCapletCalibration::swapPseudoRoots(), QuantLib::CTSMMCapletCalibration::swaptionMaxError(), QuantLib::CTSMMCapletCalibration::swaptionRmsError(), anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::todaysForwards_, and QuantLib::transpose().
Referenced by suite().
{
    BOOST_MESSAGE("Testing max homogeneity caplet calibration "
                  "in a lognormal coterminal swap market model...");
    setup();
    Size numberOfRates = todaysForwards_.size();
    EvolutionDescription evolution(rateTimes_);
    // Size numberOfSteps = evolution.numberOfSteps();
    boost::shared_ptr<PiecewiseConstantCorrelation> fwdCorr(new
        ExponentialForwardCorrelation(rateTimes_,
                                      longTermCorrelation_,
                                      beta_));
    boost::shared_ptr<LMMCurveState> cs(new LMMCurveState(rateTimes_));
    cs->setOnForwardRates(todaysForwards_);
    boost::shared_ptr<PiecewiseConstantCorrelation> corr(new
        CotSwapFromFwdCorrelation(fwdCorr, *cs, displacement_));
    std::vector<boost::shared_ptr<PiecewiseConstantVariance> >
                                    swapVariances(numberOfRates);
    for (Size i=0; i<numberOfRates; ++i) {
        swapVariances[i] = boost::shared_ptr<PiecewiseConstantVariance>(new
            PiecewiseConstantAbcdVariance(a_, b_, c_, d_,
                                          i, rateTimes_));
    }
    // create calibrator
    Real caplet0Swaption1Priority = 1.0;
    if (printReport_) {
        BOOST_MESSAGE("caplet market vols: " << QL_FIXED <<
                      std::setprecision(4) << io::sequence(capletVols_));
        BOOST_MESSAGE("caplet0Swapt1Prior: " << caplet0Swaption1Priority);
    }
    CTSMMCapletMaxHomogeneityCalibration calibrator(evolution,
                                                    corr,
                                                    swapVariances,
                                                    capletVols_,
                                                    cs,
                                                    displacement_,
                                                    caplet0Swaption1Priority);
    // calibrate
    Natural maxIterations = 10;
    Real capletTolerance = 1e-4; // i.e. 1 bp
    Natural innerMaxIterations = 100;
    Real innerTolerance = 1e-8;
    if (printReport_) {
        BOOST_MESSAGE("numberOfFactors:    " << numberOfFactors_);
        BOOST_MESSAGE("maxIterations:      " << maxIterations);
        BOOST_MESSAGE("capletTolerance:    " << io::rate(capletTolerance));
        BOOST_MESSAGE("innerMaxIterations: " << innerMaxIterations);
        BOOST_MESSAGE("innerTolerance:     " << io::rate(innerTolerance));
    }
    bool result = calibrator.calibrate(numberOfFactors_,
                                       maxIterations,
                                       capletTolerance,
                                       innerMaxIterations,
                                       innerTolerance);
    if (!result)
        BOOST_ERROR("calibration failed");
    const std::vector<Matrix>& swapPseudoRoots = calibrator.swapPseudoRoots();
    boost::shared_ptr<MarketModel> smm(new
        PseudoRootFacade(swapPseudoRoots,
                         rateTimes_,
                         cs->coterminalSwapRates(),
                         std::vector<Spread>(numberOfRates, displacement_)));
    boost::shared_ptr<MarketModel> flmm(new CotSwapToFwdAdapter(smm));
    Matrix capletTotCovariance = flmm->totalCovariance(numberOfRates-1);
    std::vector<Volatility> capletVols(numberOfRates);
    for (Size i=0; i<numberOfRates; ++i) {
        capletVols[i] = std::sqrt(capletTotCovariance[i][i]/rateTimes_[i]);
    }
    if (printReport_) {
        BOOST_MESSAGE("caplet smm implied vols: " << QL_FIXED <<
                      std::setprecision(4) << io::sequence(capletVols));
        BOOST_MESSAGE("failures: " << calibrator.failures());
        BOOST_MESSAGE("deformationSize: " << calibrator.deformationSize());
        BOOST_MESSAGE("capletRmsError: " << calibrator.capletRmsError());
        BOOST_MESSAGE("capletMaxError: " << calibrator.capletMaxError());
        BOOST_MESSAGE("swaptionRmsError: " << calibrator.swaptionRmsError());
        BOOST_MESSAGE("swaptionMaxError: " << calibrator.swaptionMaxError());
      }
    // check perfect swaption fit
    Real error, swapTolerance = 1e-14;
    Matrix swapTerminalCovariance(numberOfRates, numberOfRates, 0.0);
    for (Size i=0; i<numberOfRates; ++i) {
        Volatility expSwaptionVol = swapVariances[i]->totalVolatility(i);
        swapTerminalCovariance += swapPseudoRoots[i] * transpose(swapPseudoRoots[i]);
        Volatility swaptionVol = std::sqrt(swapTerminalCovariance[i][i]/rateTimes_[i]);
        error = std::fabs(swaptionVol-expSwaptionVol);
        if (error>swapTolerance)
            BOOST_ERROR("failed to reproduce " << io::ordinal(i+1) << " swaption vol:"
                        "\n expected:  " << io::rate(expSwaptionVol) <<
                        "\n realized:  " << io::rate(swaptionVol) <<
                        "\n error:     " << error <<
                        "\n tolerance: " << swapTolerance);
    }
    // check caplet fit
    for (Size i=0; i<numberOfRates; ++i) {
        error = std::fabs(capletVols[i]-capletVols_[i]);
        if (error>capletTolerance)
            BOOST_ERROR("failed to reproduce " << io::ordinal(i+1) << " caplet vol:"
                        "\n expected:         " << io::rate(capletVols_[i]) <<
                        "\n realized:         " << io::rate(capletVols[i]) <<
                        "\n percentage error: " << error/capletVols_[i] <<
                        "\n error:            " << error <<
                        "\n tolerance:        " << capletTolerance);
    }
    Size period =2;
    Size offset =0;
    std::vector<Spread> adaptedDisplacements;
    boost::shared_ptr<MarketModel> adapted(new FwdPeriodAdapter(flmm,period,offset,adaptedDisplacements));
   // FwdToCotSwapAdapter newSwapMM(adapted);
   // for (Size i=0; i < newSwapMM.numberOfRates(); ++i)
     //      BOOST_MESSAGE("swap MM time dependent vols: "<< i << QL_FIXED <<
       //               std::setprecision(6) << Array(newSwapMM.timeDependentVolatility(i)));
}
void MarketModelSmmCapletHomoCalibrationTest::testPeriodFunction () [static]
Definition at line 552 of file marketmodel_smmcaplethomocalibration.cpp.
References anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::a_, anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::b_, anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::beta_, anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::c_, QuantLib::capletSwaptionPeriodicCalibration(), anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::capletVols_, anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::d_, anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::displacement_, anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::longTermCorrelation_, anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::numberOfFactors_, QuantLib::io::ordinal(), anonymous_namespace{marketmodel.cpp}::printReport_, QL_FIXED, QuantLib::io::rate(), anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::rateTimes_, QuantLib::io::sequence(), anonymous_namespace{inflationvolatility.cpp}::setup(), and anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::todaysForwards_.
Referenced by suite().
{
    BOOST_MESSAGE("Testing max homogeneity periodic caplet calibration "
                  "in a lognormal coterminal swap market model...");
    setup();
    Size numberOfRates = todaysForwards_.size();
    Size period=2;
    Size offset = numberOfRates % period;
    Size numberBigRates = numberOfRates / period;
    EvolutionDescription evolution(rateTimes_);
    std::vector<Time> bigRateTimes(numberBigRates+1);
    for (Size i=0; i <= numberBigRates; ++i)
        bigRateTimes[i] = rateTimes_[i*period+offset];
    boost::shared_ptr<PiecewiseConstantCorrelation> fwdCorr(new
        ExponentialForwardCorrelation(rateTimes_,
                                      longTermCorrelation_,
                                      beta_));
    boost::shared_ptr<LMMCurveState> cs(new LMMCurveState(rateTimes_));
    cs->setOnForwardRates(todaysForwards_);
    boost::shared_ptr<PiecewiseConstantCorrelation> corr(new
        CotSwapFromFwdCorrelation(fwdCorr, *cs, displacement_));
    std::vector<PiecewiseConstantAbcdVariance >
                                    swapVariances;
    for (Size i=0; i<numberBigRates; ++i) {
        swapVariances.push_back(
            PiecewiseConstantAbcdVariance(a_, b_, c_, d_,
                                          i, bigRateTimes));
    }
    VolatilityInterpolationSpecifierabcd varianceInterpolator(period, offset, swapVariances, // these should be associated with the long rates
                                                                   rateTimes_ // these should be associated with the shorter rates
                                                                   );
    // create calibrator
    Real caplet0Swaption1Priority = 1.0;
    if (printReport_) {
        BOOST_MESSAGE("caplet market vols: " << QL_FIXED <<
                      std::setprecision(4) << io::sequence(capletVols_));
        BOOST_MESSAGE("caplet0Swapt1Prior: " << caplet0Swaption1Priority);
    }
     // calibrate
    Natural maxUnperiodicIterations = 10;
    Real toleranceUnperiodic = 1e-5; // i.e. 1 bp
    Natural max1dIterations = 100;
    Real tolerance1d = 1e-8;
    Size maxPeriodIterations = 30;
    Real periodTolerance = 1e-5;
     std::vector<Matrix> swapPseudoRoots;
     Real deformationSize;
     Real totalSwaptionError;
     std::vector<Real>  finalScales;  //scalings used for matching
     Size iterationsDone; // number of  period iteratations done
     Real errorImprovement; // improvement in error for last iteration
     Matrix modelSwaptionVolsMatrix;
       if (printReport_) {
        BOOST_MESSAGE("numberOfFactors:    " << numberOfFactors_);
        BOOST_MESSAGE("maxUnperiodicIterations:      " << maxUnperiodicIterations);
        BOOST_MESSAGE("toleranceUnperiodic:    " << io::rate(toleranceUnperiodic));
        BOOST_MESSAGE("max1dIterations: " << max1dIterations);
        BOOST_MESSAGE("tolerance1d:     " << io::rate(tolerance1d));
       }
       /*Integer failures =*/ capletSwaptionPeriodicCalibration(
        evolution,
        corr,
        varianceInterpolator,
        capletVols_,
        cs,
        displacement_,
        caplet0Swaption1Priority,
        numberOfFactors_,
        period,
        max1dIterations,
        tolerance1d,
        maxUnperiodicIterations,
        toleranceUnperiodic,
        maxPeriodIterations,
        periodTolerance,
        deformationSize,
        totalSwaptionError, // ?
        swapPseudoRoots,  // the thing we really want the pseudo root for each time step
        finalScales,  //scalings used for matching
        iterationsDone, // number of  period iteratations done
        errorImprovement, // improvement in error for last iteration
        modelSwaptionVolsMatrix // the swaption vols calibrated to at each step of the iteration
        );
    boost::shared_ptr<MarketModel> smm(new
        PseudoRootFacade(swapPseudoRoots,
                         rateTimes_,
                         cs->coterminalSwapRates(),
                         std::vector<Spread>(numberOfRates, displacement_)));
    boost::shared_ptr<MarketModel> flmm(new CotSwapToFwdAdapter(smm));
    Matrix capletTotCovariance = flmm->totalCovariance(numberOfRates-1);
    std::vector<Volatility> capletVols(numberOfRates);
    for (Size i=0; i<numberOfRates; ++i) {
        capletVols[i] = std::sqrt(capletTotCovariance[i][i]/rateTimes_[i]);
    }
    Real error;
    Real capletTolerance = 1e-4; // i.e. 1 bp
    // check caplet fit
    for (Size i=0; i<numberOfRates; ++i) {
        error = std::fabs(capletVols[i]-capletVols_[i]);
        if (error>capletTolerance)
            BOOST_ERROR("failed to reproduce " << io::ordinal(i+1) << " caplet vol:"
                        "\n expected:         " << io::rate(capletVols_[i]) <<
                        "\n realized:         " << io::rate(capletVols[i]) <<
                        "\n percentage error: " << error/capletVols_[i] <<
                        "\n error:            " << error <<
                        "\n tolerance:        " << capletTolerance);
    }
    std::vector<Spread> adaptedDisplacements(numberBigRates,displacement_);
    boost::shared_ptr<MarketModel> adaptedFlmm(new FwdPeriodAdapter(flmm,period,offset,adaptedDisplacements));
     boost::shared_ptr<MarketModel> adaptedsmm(new FwdToCotSwapAdapter(adaptedFlmm));
      // check perfect swaption fit
    Real  swapTolerance = 2e-5;
    Matrix swapTerminalCovariance(adaptedsmm->totalCovariance(adaptedsmm->numberOfSteps()-1));
    for (Size i=0; i<numberBigRates; ++i) {
        Volatility expSwaptionVol = swapVariances[i].totalVolatility(i);
        // Real cov = swapTerminalCovariance[i][i];
        Time time = adaptedsmm->evolution().rateTimes()[i];
        Volatility swaptionVol =  sqrt(swapTerminalCovariance[i][i]/time);
        error = std::fabs(swaptionVol-expSwaptionVol);
        if (error>swapTolerance)
            BOOST_ERROR("failed to reproduce " << io::ordinal(i) << " swaption vol:"
                        "\n expected:  " << io::rate(expSwaptionVol) <<
                        "\n realized:  " << io::rate(swaptionVol) <<
                        "\n error:     " << error <<
                        "\n tolerance: " << swapTolerance);
    }
}
void MarketModelSmmCapletHomoCalibrationTest::testSphereCylinder () [static]
Definition at line 721 of file marketmodel_smmcaplethomocalibration.cpp.
References QuantLib::SphereCylinderOptimizer::findByProjection(), QuantLib::SphereCylinderOptimizer::findClosest(), and anonymous_namespace{gaussianquadratures.cpp}::tolerance.
Referenced by suite().
{
    BOOST_MESSAGE("Testing sphere-cylinder optimization...");
    {
        Real R =1.0;
        Real S =0.5;
        Real alpha=1.5;
        Real Z1=1.0/sqrt(3.0);
        Real Z2=1.0/sqrt(3.0);
        Real Z3=1.0/sqrt(3.0);
        SphereCylinderOptimizer optimizer(R, S, alpha, Z1, Z2, Z3);
        Size maxIterations=100;
        Real tolerance=1e-8;
        Real y1, y2, y3;
        optimizer.findClosest(maxIterations, tolerance, y1, y2, y3);
        Real errorTol = 1e-12;
        if ( fabs(y1-1.0) > errorTol)
            BOOST_ERROR("\n failed to reproduce y1=1: "
            << y1 << ", " << y2 << ", "  << y3);
        if ( fabs(y2-0.0) > errorTol)
            BOOST_ERROR("\n failed to reproduce y2=0: "
            << y1 << ", " << y2 << ", "  << y3);
        if ( fabs(y3-0.0) > errorTol)
            BOOST_ERROR("\n failed to reproduce y3=0: "
            << y1 << ", " <<y2 << ", "  << y3);
        optimizer.findByProjection(y1, y2, y3);
        if ( fabs(y1-1.0) > errorTol)
            BOOST_ERROR("\nfindByProjection failed to reproduce y1=1: "
            << y1 << ", " << y2 << ", "  << y3);
        if ( fabs(y2-0.0) > errorTol)
            BOOST_ERROR("\n findByProjection failed to reproduce y2=0: "
            << y1 << ", " << y2 << ", "  << y3);
        if ( fabs(y3-0.0) > errorTol)
            BOOST_ERROR("\n findByProjection failed to reproduce y3=0: "
            << y1 << ", " <<y2 << ", "  << y3);
    }
   {
        Real R =5.0;
        Real S =1.0;
        Real alpha=1.0;
        Real Z1=1.0;
        Real Z2=2.0;
        Real Z3=sqrt(20.0);
        SphereCylinderOptimizer optimizer(R, S, alpha, Z1, Z2, Z3);
        Size maxIterations=100;
        Real tolerance=1e-8;
        Real y1,y2,y3;
        optimizer.findClosest(maxIterations, tolerance, y1, y2, y3);
        Real errorTol = 1e-4;
        if ( fabs(y1-1.03306) > errorTol)
            BOOST_ERROR("\n failed to reproduce y1=1.03306: "
            << y1 << ", " << y2 << ", "  << y3);
        if ( fabs(y2-0.999453) > errorTol)
            BOOST_ERROR("\n failed to reproduce y2=0.999453: "
            << y1 << ", " << y2 << ", "  << y3);
        if ( fabs(y3-4.78893) > errorTol)
            BOOST_ERROR("\n failed to reproduce y3=4.78893: "
            << y1 << ", " <<y2 << ", "  << y3);
        optimizer.findByProjection(y1, y2, y3);
        if ( fabs(y1-1.0) > errorTol)
            BOOST_ERROR("\n findByProjection failed to reproduce y1 =1: "
            << y1 << " " << y2 << " "  << y3);
        if ( fabs(y2-1.0) > errorTol)
            BOOST_ERROR("\n findByProjection failed to reproduce y2 =1: "
            << y1 << " " << y2 << " "  << y3);
        if ( fabs(y3-sqrt(23.0)) > errorTol)
            BOOST_ERROR("\n findByProjection failed to reproduce y3 =sqrt(23): "
            << y1 << " " <<y2 << " "  << y3);
    }
}
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/marketmodel_smmcaplethomocalibration.hpp
/home/deriversatile/QuantLib/QuantLibQt/test-suite/marketmodel_smmcaplethomocalibration.cpp