QuantLib: QuantLib::BlackKarasinski Class Reference
QuantLib::BlackKarasinski Class Reference
Standard Black-Karasinski model class.
#include <blackkarasinski.hpp>
Classes
class Dynamics
Short-rate dynamics in the Black-Karasinski model.
class Helper
Public Member Functions
BlackKarasinski (const Handle< YieldTermStructure > &termStructure, Real a=0.1, Real sigma=0.1)
boost::shared_ptr
< ShortRateDynamics > dynamics () const
returns the short-rate dynamics
boost::shared_ptr< Lattice > tree (const TimeGrid &grid) const
Return by default a trinomial recombining tree.
Private Member Functions
Real a () const
Real sigma () const
Private Attributes
Parameter & a_
Parameter & sigma_
Detailed Description
Standard Black-Karasinski model class.
This class implements the standard Black-Karasinski model defined by
\[ d\ln r_t = (\theta(t) - \alpha \ln r_t)dt + \sigma dW_t, \]
where \(alpha \) and \(sigma \) are constants.
Definition at line 41 of file blackkarasinski.hpp.
Constructor & Destructor Documentation
QuantLib::BlackKarasinski::BlackKarasinski (const Handle< YieldTermStructure > & termStructure, Real a = 0.1, Real sigma = 0.1)
Definition at line 57 of file blackkarasinski.cpp.
References a_, QuantLib::Observer::registerWith(), and sigma_.
    : OneFactorModel(2), TermStructureConsistentModel(termStructure),
      a_(arguments_[0]), sigma_(arguments_[1]) {
        a_ = ConstantParameter(a, PositiveConstraint());
        sigma_ = ConstantParameter(sigma, PositiveConstraint());
        registerWith(termStructure);
    }
Member Function Documentation
Real QuantLib::BlackKarasinski::a () const [inline, private]
Definition at line 57 of file blackkarasinski.hpp.
References a_.
Referenced by tree().
{ return a_(0.0); }
boost::shared_ptr<ShortRateDynamics> QuantLib::BlackKarasinski::dynamics () const [inline, virtual]
returns the short-rate dynamics
Implements QuantLib::OneFactorModel.
Definition at line 47 of file blackkarasinski.hpp.
References QL_FAIL.
{
            QL_FAIL("no defined process for Black-Karasinski");
        }
Real QuantLib::BlackKarasinski::sigma () const [inline, private]
Definition at line 58 of file blackkarasinski.hpp.
References sigma_.
Referenced by tree().
{ return sigma_(0.0); }
boost::shared_ptr< Lattice > QuantLib::BlackKarasinski::tree (const TimeGrid & grid) const [virtual]
Return by default a trinomial recombining tree.
Reimplemented from QuantLib::OneFactorModel.
Definition at line 69 of file blackkarasinski.cpp.
References a(), QuantLib::Parameter::implementation(), QuantLib::anonymous_namespace{bjerksundstenslandengine.cpp}::phi(), QuantLib::TermStructureFittingParameter::NumericalImpl::reset(), QuantLib::Solver1D< Impl >::setMaxEvaluations(), sigma(), QuantLib::TimeGrid::size(), QuantLib::Solver1D< Impl >::solve(), QuantLib::TermStructureConsistentModel::termStructure(), and QuantLib::CalibratedModel::value().
{
        TermStructureFittingParameter phi(termStructure());
        boost::shared_ptr<ShortRateDynamics> numericDynamics(
                                             new Dynamics(phi, a(), sigma()));
        boost::shared_ptr<TrinomialTree> trinomial(
                         new TrinomialTree(numericDynamics->process(), grid));
        boost::shared_ptr<ShortRateTree> numericTree(
                         new ShortRateTree(trinomial, numericDynamics, grid));
        typedef TermStructureFittingParameter::NumericalImpl NumericalImpl;
        boost::shared_ptr<NumericalImpl> impl =
            boost::dynamic_pointer_cast<NumericalImpl>(phi.implementation());
        impl->reset();
        Real value = 1.0;
        Real vMin = -50.0;
        Real vMax = 50.0;
        for (Size i=0; i<(grid.size() - 1); i++) {
            Real discountBond = termStructure()->discount(grid[i+1]);
            Real xMin = trinomial->underlying(i, 0);
            Real dx = trinomial->dx(i);
            Helper finder(i, xMin, dx, discountBond, numericTree);
            Brent s1d;
            s1d.setMaxEvaluations(1000);
            value = s1d.solve(finder, 1e-7, value, vMin, vMax);
            impl->set(grid[i], value);
            // vMin = value - 10.0;
            // vMax = value + 10.0;
        }
        return numericTree;
    }
Member Data Documentation
Parameter& QuantLib::BlackKarasinski::a_ [private]
Definition at line 60 of file blackkarasinski.hpp.
Referenced by a(), and BlackKarasinski().
Parameter& QuantLib::BlackKarasinski::sigma_ [private]
Definition at line 61 of file blackkarasinski.hpp.
Referenced by BlackKarasinski(), and sigma().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/shortrate/onefactormodels/blackkarasinski.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/shortrate/onefactormodels/blackkarasinski.cpp