QuantLib: QuantLib::BjerksundStenslandApproximationEngine Class Reference
QuantLib::BjerksundStenslandApproximationEngine Class Reference
Bjerksund and Stensland pricing engine for American options (1993)
#include <bjerksundstenslandengine.hpp>
Public Member Functions
BjerksundStenslandApproximationEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > &)
void calculate () const
Private Attributes
boost::shared_ptr
< GeneralizedBlackScholesProcess > process_
Detailed Description
Bjerksund and Stensland pricing engine for American options (1993)
Test:
the correctness of the returned value is tested by reproducing results available in literature.
Definition at line 39 of file bjerksundstenslandengine.hpp.
Constructor & Destructor Documentation
QuantLib::BjerksundStenslandApproximationEngine::BjerksundStenslandApproximationEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > & process)
Definition at line 81 of file bjerksundstenslandengine.cpp.
References process_.
    : process_(process) {
        registerWith(process_);
    }
Member Function Documentation
void QuantLib::BjerksundStenslandApproximationEngine::calculate () const
Definition at line 87 of file bjerksundstenslandengine.cpp.
References QuantLib::Exercise::American, QuantLib::anonymous_namespace{bjerksundstenslandengine.cpp}::americanCallApproximation(), QuantLib::Option::Call, QuantLib::BlackCalculator::delta(), QuantLib::BlackCalculator::deltaForward(), QuantLib::BlackCalculator::dividendRho(), QuantLib::BlackCalculator::elasticity(), QuantLib::BlackCalculator::gamma(), QuantLib::BlackCalculator::itmCashProbability(), process_, QuantLib::Option::Put, QL_REQUIRE, QuantLib::BlackCalculator::rho(), QuantLib::BlackCalculator::strikeSensitivity(), QuantLib::swap(), anonymous_namespace{quantlibbenchmark.cpp}::t, QuantLib::BlackCalculator::theta(), QuantLib::BlackCalculator::thetaPerDay(), QuantLib::BlackCalculator::value(), QuantLib::BlackCalculator::vega(), and QuantLib::DayCounter::yearFraction().
{
        QL_REQUIRE(arguments_.exercise->type() == Exercise::American,
                   "not an American Option");
        boost::shared_ptr<AmericanExercise> ex =
            boost::dynamic_pointer_cast<AmericanExercise>(arguments_.exercise);
        QL_REQUIRE(ex, "non-American exercise given");
        QL_REQUIRE(!ex->payoffAtExpiry(),
                   "payoff at expiry not handled");
        boost::shared_ptr<PlainVanillaPayoff> payoff =
            boost::dynamic_pointer_cast<PlainVanillaPayoff>(arguments_.payoff);
        QL_REQUIRE(payoff, "non-plain payoff given");
        Real variance =
            process_->blackVolatility()->blackVariance(ex->lastDate(),
                                                       payoff->strike());
        DiscountFactor dividendDiscount =
            process_->dividendYield()->discount(ex->lastDate());
        DiscountFactor riskFreeDiscount =
            process_->riskFreeRate()->discount(ex->lastDate());
        Real spot = process_->stateVariable()->value();
        QL_REQUIRE(spot > 0.0, "negative or null underlying given");
        Real strike = payoff->strike();
        if (payoff->optionType()==Option::Put) {
            // use put-call simmetry
            std::swap(spot, strike);
            std::swap(riskFreeDiscount, dividendDiscount);
            payoff = boost::shared_ptr<PlainVanillaPayoff>(
                                new PlainVanillaPayoff(Option::Call, strike));
        }
        if (dividendDiscount>=1.0) {
            // early exercise is never optimal - use Black formula
            Real forwardPrice = spot * dividendDiscount / riskFreeDiscount;
            BlackCalculator black(payoff, forwardPrice, std::sqrt(variance),
                                  riskFreeDiscount);
            results_.value        = black.value();
            results_.delta        = black.delta(spot);
            results_.deltaForward = black.deltaForward();
            results_.elasticity   = black.elasticity(spot);
            results_.gamma        = black.gamma(spot);
            DayCounter rfdc  = process_->riskFreeRate()->dayCounter();
            DayCounter divdc = process_->dividendYield()->dayCounter();
            DayCounter voldc = process_->blackVolatility()->dayCounter();
            Time t =
                rfdc.yearFraction(process_->riskFreeRate()->referenceDate(),
                                  arguments_.exercise->lastDate());
            results_.rho = black.rho(t);
            t = divdc.yearFraction(process_->dividendYield()->referenceDate(),
                                   arguments_.exercise->lastDate());
            results_.dividendRho = black.dividendRho(t);
            t = voldc.yearFraction(process_->blackVolatility()->referenceDate(),
                                   arguments_.exercise->lastDate());
            results_.vega        = black.vega(t);
            results_.theta       = black.theta(spot, t);
            results_.thetaPerDay = black.thetaPerDay(spot, t);
            results_.strikeSensitivity  = black.strikeSensitivity();
            results_.itmCashProbability = black.itmCashProbability();
        } else {
            // early exercise can be optimal - use approximation
            results_.value = americanCallApproximation(spot,
                                                       strike,
                                                       riskFreeDiscount,
                                                       dividendDiscount,
                                                       variance);
        }
    }
Member Data Documentation
boost::shared_ptr<GeneralizedBlackScholesProcess> QuantLib::BjerksundStenslandApproximationEngine::process_ [private]
Definition at line 46 of file bjerksundstenslandengine.hpp.
Referenced by BjerksundStenslandApproximationEngine(), and calculate().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/vanilla/bjerksundstenslandengine.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/vanilla/bjerksundstenslandengine.cpp