QuantLib: QuantLib::AmericanPathPricer Class Reference
QuantLib::AmericanPathPricer Class Reference
#include <mcamericanengine.hpp>
Public Member Functions
AmericanPathPricer (const boost::shared_ptr< Payoff > &payoff, Size polynomOrder, LsmBasisSystem::PolynomType polynomType)
Real state (const Path &path, Size t) const
Real operator() (const Path &path, Size t) const
std::vector< boost::function1
< Real, Real > > basisSystem () const
Protected Member Functions
Real payoff (Real state) const
Protected Attributes
Real scalingValue_
const boost::shared_ptr< Payoff > payoff_
std::vector< boost::function1
< Real, Real > > v_
Detailed Description
Definition at line 81 of file mcamericanengine.hpp.
Constructor & Destructor Documentation
QuantLib::AmericanPathPricer::AmericanPathPricer (const boost::shared_ptr< Payoff > & payoff, Size polynomOrder, LsmBasisSystem::PolynomType polynomType)
Definition at line 34 of file mcamericanengine.cpp.
References QuantLib::LsmBasisSystem::Chebyshev2nd, QuantLib::LsmBasisSystem::Hermite, QuantLib::LsmBasisSystem::Hyperbolic, QuantLib::LsmBasisSystem::Laguerre, QuantLib::LsmBasisSystem::Monomial, payoff(), payoff_, QL_REQUIRE, scalingValue_, and v_.
    : scalingValue_(1.0),
      payoff_      (payoff),
      v_           (LsmBasisSystem::pathBasisSystem(polynomOrder,
                                                    polynomType)) {
        QL_REQUIRE(   polynomType == LsmBasisSystem::Monomial
                   || polynomType == LsmBasisSystem::Laguerre
                   || polynomType == LsmBasisSystem::Hermite
                   || polynomType == LsmBasisSystem::Hyperbolic
                   || polynomType == LsmBasisSystem::Chebyshev2nd,
                   "insufficient polynom type");
        // the payoff gives an additional value
        v_.push_back(boost::bind(&AmericanPathPricer::payoff, this, _1));
        const boost::shared_ptr<StrikedTypePayoff> strikePayoff
            = boost::dynamic_pointer_cast<StrikedTypePayoff>(payoff_);
        if (strikePayoff) {
            // FLOATING_POINT_EXCEPTION
            scalingValue_/=strikePayoff->strike();
        }
    }
Member Function Documentation
std::vector< boost::function1< Real, Real > > QuantLib::AmericanPathPricer::basisSystem () const [virtual]
Implements QuantLib::EarlyExercisePathPricer< Path >.
Definition at line 77 of file mcamericanengine.cpp.
References v_.
{
        return v_;
    }
Real QuantLib::AmericanPathPricer::operator() (const Path & path, Size t) const [virtual]
Implements QuantLib::EarlyExercisePathPricer< Path >.
Definition at line 66 of file mcamericanengine.cpp.
References payoff(), and state().
{
        return payoff(state(path, t));
    }
Real QuantLib::AmericanPathPricer::payoff (Real state) const [protected]
Definition at line 62 of file mcamericanengine.cpp.
References payoff_, and scalingValue_.
Referenced by AmericanPathPricer(), and operator()().
{
        return (*payoff_)(state/scalingValue_);
    }
Real QuantLib::AmericanPathPricer::state (const Path & path, Size t) const [virtual]
Implements QuantLib::EarlyExercisePathPricer< Path >.
Definition at line 70 of file mcamericanengine.cpp.
References scalingValue_, and anonymous_namespace{quantlibbenchmark.cpp}::t.
Referenced by operator()().
{
        // scale values of the underlying
        // to increase numerical stability
        return path[t]*scalingValue_;
    }
Member Data Documentation
const boost::shared_ptr<Payoff> QuantLib::AmericanPathPricer::payoff_ [protected]
Definition at line 96 of file mcamericanengine.hpp.
Referenced by AmericanPathPricer(), and payoff().
Real QuantLib::AmericanPathPricer::scalingValue_ [protected]
Definition at line 95 of file mcamericanengine.hpp.
Referenced by AmericanPathPricer(), payoff(), and state().
std::vector<boost::function1<Real, Real> > QuantLib::AmericanPathPricer::v_ [protected]
Definition at line 97 of file mcamericanengine.hpp.
Referenced by AmericanPathPricer(), and basisSystem().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/vanilla/mcamericanengine.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/vanilla/mcamericanengine.cpp