QuantLib: RoundingTest Class Reference
RoundingTest Class Reference
#include <rounding.hpp>
Static Public Member Functions
static void testClosest ()
static void testUp ()
static void testDown ()
static void testFloor ()
static void testCeiling ()
static
boost::unit_test_framework::test_suite * suite ()
Detailed Description
Definition at line 28 of file rounding.hpp.
Member Function Documentation
test_suite * RoundingTest::suite () [static]
Definition at line 157 of file rounding.cpp.
References QUANTLIB_TEST_CASE, testCeiling(), testClosest(), testDown(), testFloor(), and testUp().
Referenced by init_unit_test_suite().
{
    test_suite* suite = BOOST_TEST_SUITE("Rounding tests");
    suite->add(QUANTLIB_TEST_CASE(&RoundingTest::testClosest));
    suite->add(QUANTLIB_TEST_CASE(&RoundingTest::testUp));
    suite->add(QUANTLIB_TEST_CASE(&RoundingTest::testDown));
    suite->add(QUANTLIB_TEST_CASE(&RoundingTest::testFloor));
    suite->add(QUANTLIB_TEST_CASE(&RoundingTest::testCeiling));
    return suite;
}
void RoundingTest::testCeiling () [static]
Definition at line 138 of file rounding.cpp.
References anonymous_namespace{rounding.cpp}::TestCase::ceiling, QuantLib::close(), LENGTH, anonymous_namespace{rounding.cpp}::TestCase::precision, QL_FIXED, and anonymous_namespace{rounding.cpp}::testData.
Referenced by suite().
{
    BOOST_MESSAGE("Testing ceiling decimal rounding...");
    for (Size i=0; i<LENGTH(testData); i++) {
        Integer digits = testData[i].precision;
        CeilingTruncation ceiling(digits);
        Real calculated = ceiling(testData[i].x);
        Real expected = testData[i].ceiling;
        if (!close(calculated,expected,1))
            BOOST_ERROR(QL_FIXED << std::setprecision(8)
                        << "Original number: " << testData[i].x << "\n"
                        << std::setprecision(digits)
                        << "Expected:        " << expected << "\n"
                        << "Calculated:      " << calculated);
    }
}
void RoundingTest::testClosest () [static]
Definition at line 66 of file rounding.cpp.
References QuantLib::close(), anonymous_namespace{rounding.cpp}::TestCase::closest, LENGTH, anonymous_namespace{rounding.cpp}::TestCase::precision, QL_FIXED, and anonymous_namespace{rounding.cpp}::testData.
Referenced by suite().
{
    BOOST_MESSAGE("Testing closest decimal rounding...");
    for (Size i=0; i<LENGTH(testData); i++) {
        Integer digits = testData[i].precision;
        ClosestRounding closest(digits);
        Real calculated = closest(testData[i].x);
        Real expected = testData[i].closest;
        if (!close(calculated,expected,1))
            BOOST_ERROR(QL_FIXED << std::setprecision(8)
                        << "Original number: " << testData[i].x << "\n"
                        << std::setprecision(digits)
                        << "Expected:        " << expected << "\n"
                        << "Calculated:      " << calculated);
    }
}
void RoundingTest::testDown () [static]
Definition at line 102 of file rounding.cpp.
References QuantLib::close(), anonymous_namespace{rounding.cpp}::TestCase::down, LENGTH, anonymous_namespace{rounding.cpp}::TestCase::precision, QL_FIXED, and anonymous_namespace{rounding.cpp}::testData.
Referenced by suite().
{
    BOOST_MESSAGE("Testing downward decimal rounding...");
    for (Size i=0; i<LENGTH(testData); i++) {
        Integer digits = testData[i].precision;
        DownRounding down(digits);
        Real calculated = down(testData[i].x);
        Real expected = testData[i].down;
        if (!close(calculated,expected,1))
            BOOST_ERROR(QL_FIXED << std::setprecision(8)
                        << "Original number: " << testData[i].x << "\n"
                        << std::setprecision(digits)
                        << "Expected:        " << expected << "\n"
                        << "Calculated:      " << calculated);
    }
}
void RoundingTest::testFloor () [static]
Definition at line 120 of file rounding.cpp.
References QuantLib::close(), anonymous_namespace{rounding.cpp}::TestCase::floor, LENGTH, anonymous_namespace{rounding.cpp}::TestCase::precision, QL_FIXED, and anonymous_namespace{rounding.cpp}::testData.
Referenced by suite().
{
    BOOST_MESSAGE("Testing floor decimal rounding...");
    for (Size i=0; i<LENGTH(testData); i++) {
        Integer digits = testData[i].precision;
        FloorTruncation floor(digits);
        Real calculated = floor(testData[i].x);
        Real expected = testData[i].floor;
        if (!close(calculated,expected,1))
            BOOST_ERROR(QL_FIXED << std::setprecision(8)
                        << "Original number: " << testData[i].x << "\n"
                        << std::setprecision(digits)
                        << "Expected:        " << expected << "\n"
                        << "Calculated:      " << calculated);
    }
}
void RoundingTest::testUp () [static]
Definition at line 84 of file rounding.cpp.
References QuantLib::close(), LENGTH, anonymous_namespace{rounding.cpp}::TestCase::precision, QL_FIXED, anonymous_namespace{rounding.cpp}::testData, and anonymous_namespace{rounding.cpp}::TestCase::up.
Referenced by suite().
{
    BOOST_MESSAGE("Testing upward decimal rounding...");
    for (Size i=0; i<LENGTH(testData); i++) {
        Integer digits = testData[i].precision;
        UpRounding up(digits);
        Real calculated = up(testData[i].x);
        Real expected = testData[i].up;
        if (!close(calculated,expected,1))
            BOOST_ERROR(QL_FIXED << std::setprecision(8)
                        << "Original number: " << testData[i].x << "\n"
                        << std::setprecision(digits)
                        << "Expected:        " << expected << "\n"
                        << "Calculated:      " << calculated);
    }
}
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/rounding.hpp
/home/deriversatile/QuantLib/QuantLibQt/test-suite/rounding.cpp