QuantLib: QuantLib::ZigguratRng Class Reference
QuantLib::ZigguratRng Class Reference
Ziggurat random-number generator.
#include <zigguratrng.hpp>
Public Types
typedef Sample< Real > sample_type
Public Member Functions
ZigguratRng (unsigned long seed=0)
sample_type next () const
Private Member Functions
Real nextGaussian () const
Private Attributes
MersenneTwisterUniformRng mt32_
Detailed Description
Ziggurat random-number generator.
This generator returns standard normal variates using the Ziggurat method. The underlying RNG is mt19937 (32 bit version). The algorithm is described in Marsaglia and Tsang (2000). "The Ziggurat Method for Generating Random Variables". Journal of Statistical Software 5 (8). Note that step 2 from the above paper reuses the rightmost 8 bits of the random integer, which creates correlation between steps 1 and 2. This implementation was written from scratch, following Marsaglia and Tsang. It avoids the correlation by using only the leftmost 24 bits of mt19937's output.
Note that the GNU GSL implementation uses a different value for the right-most step. The GSL value is somewhat different from the one reported by Marsaglia and Tsang because GSL uses a different tail. This implementation uses the same right-most step as reported by Marsaglia and Tsang. The generator was put through Marsaglia's Diehard battery of tests and didn't exibit any abnormal behavior.
Definition at line 52 of file zigguratrng.hpp.
Member Typedef Documentation
typedef Sample<Real> QuantLib::ZigguratRng::sample_type
Definition at line 54 of file zigguratrng.hpp.
Constructor & Destructor Documentation
QuantLib::ZigguratRng::ZigguratRng (unsigned long seed = 0)
Definition at line 209 of file zigguratrng.cpp.
    : mt32_(seed) {}
Member Function Documentation
sample_type QuantLib::ZigguratRng::next () const [inline]
Definition at line 56 of file zigguratrng.hpp.
References nextGaussian().
{
            return sample_type(nextGaussian(),1.0);
        }
Real QuantLib::ZigguratRng::nextGaussian () const [private]
Definition at line 212 of file zigguratrng.cpp.
References anonymous_namespace{marketmodel.cpp}::c, anonymous_namespace{interpolations.cpp}::f(), QuantLib::anonymous_namespace{zigguratrng.cpp}::f_, QuantLib::anonymous_namespace{zigguratrng.cpp}::k_, mt32_, QuantLib::MersenneTwisterUniformRng::nextInt32(), QuantLib::MersenneTwisterUniformRng::nextReal(), QuantLib::anonymous_namespace{zigguratrng.cpp}::p_, QuantLib::anonymous_namespace{zigguratrng.cpp}::q_, QuantLib::InverseCumulativeNormal::standard_value(), and QuantLib::anonymous_namespace{zigguratrng.cpp}::w_.
Referenced by next().
{
        static const int c[2] = {-1, 1};
        unsigned long i, j;
        int f;
        Real x;
        do {
            j = mt32_.nextInt32(); // generate 32 bits of randomness
            f = j & 1; // 1 bit to choose a tails
            j >>= 1;
            i = j & 0x7f; // 7 bits to choose a strip
            j >>= 7; // the last 24 bits for accepttion/rejection
            x = (c[f]*static_cast<long>(j))*w_[i]; // x is uniform
                                                   // within the i-th strip
            if (j < k_[i]) // if true, accept x
                break;
            // handle rejections
            if (i!=0) { // upper strips
                if ((f_[i-1]-f_[i])*mt32_.nextReal() + f_[i] < exp(-0.5*x*x))
                    break;
            } else { // base strip, sample from the tail
                x = c[f]*InverseCumulativeNormal::standard_value(
                                                      p_*mt32_.nextReal()+q_);
                break;
            }
        } while (true);
        return x;
    }
Member Data Documentation
MersenneTwisterUniformRng QuantLib::ZigguratRng::mt32_ [mutable, private]
Definition at line 60 of file zigguratrng.hpp.
Referenced by nextGaussian().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/math/zigguratrng.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/math/zigguratrng.cpp