QuantLib: TqrEigenDecompositionTest Class Reference
TqrEigenDecompositionTest Class Reference
#include <tqreigendecomposition.hpp>
Static Public Member Functions
static void testEigenValueDecomposition ()
static void testZeroOffDiagEigenValues ()
static void testEigenVectorDecomposition ()
static
boost::unit_test_framework::test_suite * suite ()
Detailed Description
Definition at line 28 of file tqreigendecomposition.hpp.
Member Function Documentation
test_suite * TqrEigenDecompositionTest::suite () [static]
Definition at line 103 of file tqreigendecomposition.cpp.
References QUANTLIB_TEST_CASE, testEigenValueDecomposition(), testEigenVectorDecomposition(), and testZeroOffDiagEigenValues().
Referenced by init_unit_test_suite().
{
    test_suite* suite = BOOST_TEST_SUITE("TQR eigendecomposition tests");
    suite->add(QUANTLIB_TEST_CASE(
                   &TqrEigenDecompositionTest::testEigenValueDecomposition));
    suite->add(QUANTLIB_TEST_CASE(
                   &TqrEigenDecompositionTest::testZeroOffDiagEigenValues));
    suite->add(QUANTLIB_TEST_CASE(
                   &TqrEigenDecompositionTest::testEigenVectorDecomposition));
    return suite;
}
void TqrEigenDecompositionTest::testEigenValueDecomposition () [static]
Definition at line 34 of file tqreigendecomposition.cpp.
References QuantLib::TqrEigenDecomposition::eigenvalues(), QuantLib::Array::size(), anonymous_namespace{quotes.cpp}::sub(), anonymous_namespace{gaussianquadratures.cpp}::tolerance, and QuantLib::TqrEigenDecomposition::WithoutEigenVector.
Referenced by suite().
{
    BOOST_MESSAGE("Testing TQR eigenvalue decomposition...");
    Array diag(5);
    Array sub(4,1);
    diag[0]=11; diag[1]=7; diag[2]=6; diag[3]=2; diag[4]=0;
    Real ev[5] = {11.2467832217139119,
                  7.4854967362908535,
                  5.5251516080277518,
                  2.1811760273123308,
                  -0.4386075933448487};
    TqrEigenDecomposition tqre(diag, sub,
                               TqrEigenDecomposition::WithoutEigenVector);
    for (Size i=0; i < diag.size(); ++i) {
        const Real expected(ev[i]);
        const Real calculated(tqre.eigenvalues()[i]);
        if (std::fabs(expected-calculated) > tolerance) {
            BOOST_FAIL(std::string("wrong eigenvalue \n")
                       << "calculated: "
                       << calculated
                       <<" expected  : "
                       << expected);
        }
    }
}
void TqrEigenDecompositionTest::testEigenVectorDecomposition () [static]
Definition at line 87 of file tqreigendecomposition.cpp.
References QuantLib::TqrEigenDecomposition::eigenvectors(), anonymous_namespace{quotes.cpp}::sub(), and anonymous_namespace{gaussianquadratures.cpp}::tolerance.
Referenced by suite().
{
    BOOST_MESSAGE("Testing TQR eigenvector decomposition...");
    Array diag(2,1);
    Array sub(1,1);
    TqrEigenDecomposition tqre(diag, sub);
    if (std::fabs(0.25 + tqre.eigenvectors()[0][0]
                       * tqre.eigenvectors()[0][1]
                       * tqre.eigenvectors()[1][0]
                       * tqre.eigenvectors()[1][1]) > tolerance) {
        BOOST_FAIL("wrong eigenvector");
    }
}
void TqrEigenDecompositionTest::testZeroOffDiagEigenValues () [static]
Definition at line 61 of file tqreigendecomposition.cpp.
References QuantLib::TqrEigenDecomposition::eigenvalues(), QuantLib::Array::size(), anonymous_namespace{quotes.cpp}::sub(), and anonymous_namespace{gaussianquadratures.cpp}::tolerance.
Referenced by suite().
{
    BOOST_MESSAGE("Testing TQR zero-off-diagonal eigenvalues...");
    Array diag(5);
    Array sub(4,1);
    sub[0] =sub[2]=0;
    diag[0]=12; diag[1]=9; diag[2]=6; diag[3]=3; diag[4]=0;
    TqrEigenDecomposition tqre1(diag, sub);
    sub[0]=sub[2]=1e-14;
    TqrEigenDecomposition tqre2(diag, sub);
    for (Size i=0; i < diag.size(); ++i) {
        const Real expected(tqre2.eigenvalues()[i]);
        const Real calculated(tqre1.eigenvalues()[i]);
        if (std::fabs(expected-calculated) > tolerance) {
            BOOST_FAIL(std::string("wrong eigenvalue \n")
                       << "calculated: "
                       << calculated
                       << " expected  : "
                       << expected);
        }
    }
}
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/tqreigendecomposition.hpp
/home/deriversatile/QuantLib/QuantLibQt/test-suite/tqreigendecomposition.cpp