QuantLib: QuantLib::LmLinearExponentialCorrelationModel Class Reference
QuantLib::LmLinearExponentialCorrelationModel Class Reference
linear exponential correlation model
#include <lmlinexpcorrmodel.hpp>
Public Member Functions
LmLinearExponentialCorrelationModel (Size size, Real rho, Real beta, Size factors=Null< Size >())
Disposable< Matrix > correlation (Time t, const Array &x=Null< Array >()) const
Disposable< Matrix > pseudoSqrt (Time t, const Array &x=Null< Array >()) const
Real correlation (Size i, Size j, Time t, const Array &x) const
Size factors () const
bool isTimeIndependent () const
Protected Member Functions
void generateArguments ()
Private Attributes
Matrix corrMatrix_
Matrix pseudoSqrt_
const Size factors_
Detailed Description
linear exponential correlation model
This class describes a exponential correlation model
\[ \rho_{i,j}=rho + (1-rho)*e^{(-\beta \|i-j\|)} \]
References:
Damiano Brigo, Fabio Mercurio, Massimo Morini, 2003, Different Covariance Parameterizations of Libor Market Model and Joint Caps/Swaptions Calibration, (<http://www.business.uts.edu.au/qfrc/conferences/qmf2001/Brigo_D.pdf>)
Definition at line 45 of file lmlinexpcorrmodel.hpp.
Constructor & Destructor Documentation
QuantLib::LmLinearExponentialCorrelationModel::LmLinearExponentialCorrelationModel (Size size, Real rho, Real beta, Size factors = Null<Size>())
Definition at line 25 of file lmlinexpcorrmodel.cpp.
References QuantLib::LmCorrelationModel::arguments_, and generateArguments().
   : LmCorrelationModel(size, 2),
     corrMatrix_(size, size),
     factors_((factors != Null<Size>()) ? factors : size) {
        arguments_[0] = ConstantParameter(rho, BoundaryConstraint(-1.0, 1.0));
        arguments_[1] = ConstantParameter(beta, PositiveConstraint());
        generateArguments();
    }
Member Function Documentation
Disposable< Matrix > QuantLib::LmLinearExponentialCorrelationModel::correlation (Time t, const Array & x = Null<Array>()) const [virtual]
Implements QuantLib::LmCorrelationModel.
Definition at line 35 of file lmlinexpcorrmodel.cpp.
References corrMatrix_.
{
        Matrix tmp(corrMatrix_);
        return tmp;
    }
Real QuantLib::LmLinearExponentialCorrelationModel::correlation (Size i, Size j, Time t, const Array & x) const [virtual]
Reimplemented from QuantLib::LmCorrelationModel.
Definition at line 41 of file lmlinexpcorrmodel.cpp.
References corrMatrix_.
{
        return corrMatrix_[i][j];
    }
Size QuantLib::LmLinearExponentialCorrelationModel::factors () const [virtual]
Reimplemented from QuantLib::LmCorrelationModel.
Definition at line 50 of file lmlinexpcorrmodel.cpp.
References factors_.
{
        return factors_;
    }
void QuantLib::LmLinearExponentialCorrelationModel::generateArguments () [protected, virtual]
Implements QuantLib::LmCorrelationModel.
Definition at line 61 of file lmlinexpcorrmodel.cpp.
References QuantLib::LmCorrelationModel::arguments_, anonymous_namespace{marketmodel.cpp}::beta, corrMatrix_, factors_, QuantLib::SalvagingAlgorithm::None, pseudoSqrt_, QuantLib::rankReducedSqrt(), QuantLib::LmCorrelationModel::size_, and QuantLib::transpose().
Referenced by LmLinearExponentialCorrelationModel().
{
        const Real rho = arguments_[0](0.0);
        const Real beta= arguments_[1](0.0);
        for (Size i=0; i<size_; ++i) {
            for (Size j=i; j<size_; ++j) {
                corrMatrix_[i][j] = corrMatrix_[j][i]
                    = rho + (1-rho)*std::exp(-beta*std::fabs(Real(i)-Real(j)));
            }
        }
        pseudoSqrt_ = rankReducedSqrt(corrMatrix_, factors_,
                                      1.0, SalvagingAlgorithm::None);
        corrMatrix_ = pseudoSqrt_ * transpose(pseudoSqrt_);
    }
bool QuantLib::LmLinearExponentialCorrelationModel::isTimeIndependent () const [virtual]
Reimplemented from QuantLib::LmCorrelationModel.
Definition at line 46 of file lmlinexpcorrmodel.cpp.
{
        return true;
    }
Disposable< Matrix > QuantLib::LmLinearExponentialCorrelationModel::pseudoSqrt (Time t, const Array & x = Null<Array>()) const [virtual]
Reimplemented from QuantLib::LmCorrelationModel.
Definition at line 55 of file lmlinexpcorrmodel.cpp.
References pseudoSqrt_.
{
        Matrix tmp(pseudoSqrt_);
        return tmp;
    }
Member Data Documentation
Matrix QuantLib::LmLinearExponentialCorrelationModel::corrMatrix_ [private]
Definition at line 63 of file lmlinexpcorrmodel.hpp.
Referenced by correlation(), and generateArguments().
const Size QuantLib::LmLinearExponentialCorrelationModel::factors_ [private]
Definition at line 64 of file lmlinexpcorrmodel.hpp.
Referenced by factors(), and generateArguments().
Matrix QuantLib::LmLinearExponentialCorrelationModel::pseudoSqrt_ [private]
Definition at line 63 of file lmlinexpcorrmodel.hpp.
Referenced by generateArguments(), and pseudoSqrt().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/legacy/libormarketmodels/lmlinexpcorrmodel.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/legacy/libormarketmodels/lmlinexpcorrmodel.cpp