QuantLib: QuantLib::AbcdAtmVolCurve Class Reference
QuantLib::AbcdAtmVolCurve Class Reference
Abcd-interpolated at-the-money (no-smile) volatility curve.
#include <abcdatmvolcurve.hpp>
Public Member Functions
AbcdAtmVolCurve (Natural settlementDays, const Calendar &cal, const std::vector< Period > &optionTenors, const std::vector< Handle< Quote > > &volsHandles, const std::vector< bool > inclusionInInterpolationFlag=std::vector< bool >(1, true), BusinessDayConvention bdc=Following, const DayCounter &dc=Actual365Fixed())
floating reference date, floating market data
std::vector< Real > k () const
Returns k adjustment factors for option tenors used in interpolation.
Real k (Time t) const
Returns k adjustment factor at time t.
Real a () const
Real b () const
Real c () const
Real d () const
Real rmsError () const
Real maxError () const
EndCriteria::Type endCriteria () const
TermStructure interface
virtual Date maxDate () const
the latest date for which the curve can return values
VolatilityTermStructure interface
Real minStrike () const
the minimum strike for which the term structure can return vols
Real maxStrike () const
the maximum strike for which the term structure can return vols
LazyObject interface
void update ()
void performCalculations () const
some inspectors
const std::vector< Period > & optionTenors () const
const std::vector< Period > & optionTenorsInInterpolation () const
const std::vector< Date > & optionDates () const
const std::vector< Time > & optionTimes () const
Visitability
virtual void accept (AcyclicVisitor &)
Protected Member Functions
BlackAtmVolCurve interface
virtual Real atmVarianceImpl (Time t) const
spot at-the-money variance calculation (k adjusted)
virtual Volatility atmVolImpl (Time t) const
spot at-the-money volatility calculation (k adjusted)
Private Member Functions
void checkInputs () const
void initializeOptionDatesAndTimes () const
void initializeVolatilities ()
void registerWithMarketData ()
void interpolate ()
Private Attributes
Size nOptionTenors_
std::vector< Period > optionTenors_
std::vector< Period > actualOptionTenors_
std::vector< Date > optionDates_
std::vector< Time > optionTimes_
std::vector< Time > actualOptionTimes_
Date evaluationDate_
std::vector< Handle< Quote > > volHandles_
std::vector< Volatility > vols_
std::vector< Volatility > actualVols_
std::vector< bool > inclusionInInterpolation_
boost::shared_ptr
< AbcdInterpolation > interpolation_
Detailed Description
Abcd-interpolated at-the-money (no-smile) volatility curve.
blah blah
Definition at line 39 of file abcdatmvolcurve.hpp.
Constructor & Destructor Documentation
QuantLib::AbcdAtmVolCurve::AbcdAtmVolCurve (Natural settlementDays, const Calendar & cal, const std::vector< Period > & optionTenors, const std::vector< Handle< Quote > > & volsHandles, const std::vector< bool > inclusionInInterpolationFlag = std::vector<bool>(1, true), BusinessDayConvention bdc = Following, const DayCounter & dc = Actual365Fixed())
floating reference date, floating market data
Definition at line 28 of file abcdatmvolcurve.cpp.
References checkInputs(), initializeOptionDatesAndTimes(), initializeVolatilities(), interpolate(), registerWithMarketData(), volHandles_, and vols_.
    : BlackAtmVolCurve(settlDays, cal, bdc, dc),
      nOptionTenors_(optionTenors.size()),
      optionTenors_(optionTenors),
      optionDates_(nOptionTenors_),
      optionTimes_(nOptionTenors_),
      actualOptionTimes_(nOptionTenors_),
      volHandles_(volsHandles),
      vols_(volsHandles.size()),
      actualVols_(volsHandles.size()),
      inclusionInInterpolation_(inclusionInInterpolationFlag),
      interpolation_(boost::shared_ptr<AbcdInterpolation>()) // do not initialize with nOptionTenors_
    {
        checkInputs();
        initializeOptionDatesAndTimes();
        initializeVolatilities();
        registerWithMarketData();
        for (Size i=0; i<vols_.size(); ++i)
            vols_[i] = volHandles_[i]->value();
        interpolate();
    }
Member Function Documentation
Real QuantLib::AbcdAtmVolCurve::a () const [inline]
Definition at line 172 of file abcdatmvolcurve.hpp.
References interpolation_.
{
        return interpolation_->a();
    }
void QuantLib::AbcdAtmVolCurve::accept (AcyclicVisitor & v) [virtual]
Reimplemented from QuantLib::BlackAtmVolCurve.
Definition at line 96 of file abcdatmvolcurve.cpp.
References QL_FAIL, anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Visitor< T >::visit().
{
        Visitor<AbcdAtmVolCurve>* v1 =
            dynamic_cast<Visitor<AbcdAtmVolCurve>*>(&v);
        if (v1 != 0)
            v1->visit(*this);
        else
            QL_FAIL("not a AbcdAtmVolCurve visitor");
    }
Real QuantLib::AbcdAtmVolCurve::atmVarianceImpl (Time t) const [inline, protected, virtual]
spot at-the-money variance calculation (k adjusted)
Implements QuantLib::BlackAtmVolCurve.
Definition at line 134 of file abcdatmvolcurve.hpp.
References atmVolImpl(), and anonymous_namespace{quantlibbenchmark.cpp}::t.
{
        Volatility vol = atmVolImpl(t);
        return vol*vol*t;
    }
Volatility QuantLib::AbcdAtmVolCurve::atmVolImpl (Time t) const [inline, protected, virtual]
spot at-the-money volatility calculation (k adjusted)
Implements QuantLib::BlackAtmVolCurve.
Definition at line 139 of file abcdatmvolcurve.hpp.
References QuantLib::LazyObject::calculate(), interpolation_, k(), and anonymous_namespace{quantlibbenchmark.cpp}::t.
Referenced by atmVarianceImpl().
{
        calculate();
        return k(t) * interpolation_->operator() (t, true);
    }
Real QuantLib::AbcdAtmVolCurve::b () const [inline]
Definition at line 176 of file abcdatmvolcurve.hpp.
References interpolation_.
{
        return interpolation_->b();
    }
Real QuantLib::AbcdAtmVolCurve::c () const [inline]
Definition at line 180 of file abcdatmvolcurve.hpp.
References interpolation_.
{
        return interpolation_->c();
    }
void QuantLib::AbcdAtmVolCurve::checkInputs () const [private]
Definition at line 57 of file abcdatmvolcurve.cpp.
References QuantLib::Days, inclusionInInterpolation_, nOptionTenors_, optionTenors_, QuantLib::io::ordinal(), QL_REQUIRE, and vols_.
Referenced by AbcdAtmVolCurve().
    {
        QL_REQUIRE(!optionTenors_.empty(), "empty option tenor vector");
        QL_REQUIRE(nOptionTenors_==vols_.size(),
                   "mismatch between number of option tenors (" <<
                   nOptionTenors_ << ") and number of volatilities (" <<
                   vols_.size() << ")");
        QL_REQUIRE(optionTenors_[0]>0*Days,
                   "negative first option tenor: " << optionTenors_[0]);
        for (Size i=1; i<nOptionTenors_; ++i)
            QL_REQUIRE(optionTenors_[i]>optionTenors_[i-1],
                       "non increasing option tenor: " << io::ordinal(i) <<
                       " is " << optionTenors_[i-1] << ", " <<
                       io::ordinal(i+1) << " is " << optionTenors_[i]);
        if (inclusionInInterpolation_.size()==1) {
            inclusionInInterpolation_.resize(nOptionTenors_);
            for(Size j=1; j<nOptionTenors_;++j)
                inclusionInInterpolation_[j] = inclusionInInterpolation_[0];
        } else
            QL_REQUIRE(nOptionTenors_==inclusionInInterpolation_.size(),
                       "mismatch between number of option tenors (" <<
                       nOptionTenors_ << ") and number of inclusion's flags (" <<
                       inclusionInInterpolation_.size() << ")");
    }
Real QuantLib::AbcdAtmVolCurve::d () const [inline]
Definition at line 184 of file abcdatmvolcurve.hpp.
References interpolation_.
Referenced by update().
{
        return interpolation_->d();
    }
EndCriteria::Type QuantLib::AbcdAtmVolCurve::endCriteria () const
void QuantLib::AbcdAtmVolCurve::initializeOptionDatesAndTimes () const [private]
Definition at line 119 of file abcdatmvolcurve.cpp.
References actualOptionTenors_, actualOptionTimes_, inclusionInInterpolation_, nOptionTenors_, QuantLib::VolatilityTermStructure::optionDateFromTenor(), optionDates_, optionTenors_, optionTimes_, and QuantLib::TermStructure::timeFromReference().
Referenced by AbcdAtmVolCurve(), and update().
    {
        // the input time data
        for (Size i=0; i<nOptionTenors_; ++i) {
            optionDates_[i] = optionDateFromTenor(optionTenors_[i]);
            optionTimes_[i] = timeFromReference(optionDates_[i]);
        }
        // the time data used for interpolation
        actualOptionTimes_.clear();
        for (Size i=0; i<nOptionTenors_; ++i) {
            if(inclusionInInterpolation_[i]==true) {
               actualOptionTimes_.push_back(optionTimes_[i]);
               actualOptionTenors_.push_back(optionTenors_[i]);
            }
        }
    }
void QuantLib::AbcdAtmVolCurve::initializeVolatilities () [private]
Definition at line 136 of file abcdatmvolcurve.cpp.
References actualVols_, inclusionInInterpolation_, nOptionTenors_, volHandles_, and vols_.
Referenced by AbcdAtmVolCurve().
{
        actualVols_.clear();
        for (Size i=0; i<nOptionTenors_; ++i) {
            vols_[i] = volHandles_[i]->value();
            if(inclusionInInterpolation_[i]==true)
               actualVols_.push_back(vols_[i]);
        }
    }
void QuantLib::AbcdAtmVolCurve::interpolate () [private]
Definition at line 88 of file abcdatmvolcurve.cpp.
References actualOptionTimes_, actualVols_, and interpolation_.
Referenced by AbcdAtmVolCurve().
    {
        interpolation_ = boost::shared_ptr<AbcdInterpolation>(new
                            AbcdInterpolation(actualOptionTimes_.begin(),
                                              actualOptionTimes_.end(),
                                              actualVols_.begin()));
    }
std::vector< Real > QuantLib::AbcdAtmVolCurve::k () const [inline]
Returns k adjustment factors for option tenors used in interpolation.
Definition at line 163 of file abcdatmvolcurve.hpp.
References interpolation_.
Referenced by atmVolImpl().
{
        return interpolation_->k();
    }
Real QuantLib::AbcdAtmVolCurve::k (Time t) const [inline]
Returns k adjustment factor at time t.
Definition at line 168 of file abcdatmvolcurve.hpp.
References actualOptionTimes_, and interpolation_.
{
        return interpolation_->k(t,actualOptionTimes_.begin(),actualOptionTimes_.end());
    }
Date QuantLib::AbcdAtmVolCurve::maxDate () const [inline, virtual]
the latest date for which the curve can return values
Implements QuantLib::TermStructure.
Definition at line 121 of file abcdatmvolcurve.hpp.
References QuantLib::LazyObject::calculate(), QuantLib::VolatilityTermStructure::optionDateFromTenor(), and optionTenors_.
{
        calculate();
        return optionDateFromTenor(optionTenors_.back());
    }
Real QuantLib::AbcdAtmVolCurve::maxError () const [inline]
Definition at line 191 of file abcdatmvolcurve.hpp.
References interpolation_.
{
        return interpolation_->maxError();
    }
Real QuantLib::AbcdAtmVolCurve::maxStrike () const [inline, virtual]
the maximum strike for which the term structure can return vols
Implements QuantLib::VolatilityTermStructure.
Definition at line 130 of file abcdatmvolcurve.hpp.
References QL_MAX_REAL.
{
        return QL_MAX_REAL;
    }
Real QuantLib::AbcdAtmVolCurve::minStrike () const [inline, virtual]
the minimum strike for which the term structure can return vols
Implements QuantLib::VolatilityTermStructure.
Definition at line 126 of file abcdatmvolcurve.hpp.
References QL_MIN_REAL.
{
        return QL_MIN_REAL;
    }
const std::vector< Date > & QuantLib::AbcdAtmVolCurve::optionDates () const [inline]
Definition at line 153 of file abcdatmvolcurve.hpp.
References optionDates_.
{
        return optionDates_;
    }
const std::vector< Period > & QuantLib::AbcdAtmVolCurve::optionTenors () const [inline]
Definition at line 144 of file abcdatmvolcurve.hpp.
References optionTenors_.
{
         return optionTenors_;
    }
const std::vector< Period > & QuantLib::AbcdAtmVolCurve::optionTenorsInInterpolation () const [inline]
Definition at line 148 of file abcdatmvolcurve.hpp.
References actualOptionTenors_.
{
        return actualOptionTenors_;
    }
const std::vector< Time > & QuantLib::AbcdAtmVolCurve::optionTimes () const [inline]
Definition at line 158 of file abcdatmvolcurve.hpp.
References optionTimes_.
{
        return optionTimes_;
    }
void QuantLib::AbcdAtmVolCurve::performCalculations () const [virtual]
This method must implement any calculations which must be (re)done in order to calculate the desired results.
Implements QuantLib::LazyObject.
Definition at line 146 of file abcdatmvolcurve.cpp.
References actualVols_, inclusionInInterpolation_, interpolation_, volHandles_, and vols_.
    {
        // check if date recalculation must be called here
        actualVols_.clear();
        for (Size i=0; i<vols_.size(); ++i) {
            vols_[i] = volHandles_[i]->value();
            if(inclusionInInterpolation_[i]==true)
               actualVols_.push_back(vols_[i]);
        }
        interpolation_->update();
    }
void QuantLib::AbcdAtmVolCurve::registerWithMarketData () [private]
Definition at line 82 of file abcdatmvolcurve.cpp.
References QuantLib::Observer::registerWith(), and volHandles_.
Referenced by AbcdAtmVolCurve().
    {
        for (Size i=0; i<volHandles_.size(); ++i)
            registerWith(volHandles_[i]);
    }
Real QuantLib::AbcdAtmVolCurve::rmsError () const [inline]
Definition at line 188 of file abcdatmvolcurve.hpp.
References interpolation_.
{
        return interpolation_->rmsError();
    }
void QuantLib::AbcdAtmVolCurve::update () [virtual]
This method must be implemented in derived classes. An instance of Observer does not call this method directly: instead, it will be called by the observables the instance registered with when they need to notify any changes.
Reimplemented from QuantLib::LazyObject.
Definition at line 105 of file abcdatmvolcurve.cpp.
References d(), QuantLib::Settings::evaluationDate(), evaluationDate_, initializeOptionDatesAndTimes(), QuantLib::Singleton< Settings >::instance(), and QuantLib::TermStructure::moving_.
    {
        // recalculate dates if necessary...
        if (moving_) {
            Date d = Settings::instance().evaluationDate();
            if (evaluationDate_ != d) {
                evaluationDate_ = d;
                initializeOptionDatesAndTimes();
            }
        }
        BlackAtmVolCurve::update();
        LazyObject::update();
    }
Member Data Documentation
std::vector<Period> QuantLib::AbcdAtmVolCurve::actualOptionTenors_ [mutable, private]
Definition at line 104 of file abcdatmvolcurve.hpp.
Referenced by initializeOptionDatesAndTimes(), and optionTenorsInInterpolation().
std::vector<Time> QuantLib::AbcdAtmVolCurve::actualOptionTimes_ [mutable, private]
Definition at line 107 of file abcdatmvolcurve.hpp.
Referenced by initializeOptionDatesAndTimes(), interpolate(), and k().
std::vector<Volatility> QuantLib::AbcdAtmVolCurve::actualVols_ [mutable, private]
Definition at line 112 of file abcdatmvolcurve.hpp.
Referenced by initializeVolatilities(), interpolate(), and performCalculations().
Date QuantLib::AbcdAtmVolCurve::evaluationDate_ [private]
Definition at line 108 of file abcdatmvolcurve.hpp.
Referenced by update().
std::vector<bool> QuantLib::AbcdAtmVolCurve::inclusionInInterpolation_ [mutable, private]
Definition at line 114 of file abcdatmvolcurve.hpp.
Referenced by checkInputs(), initializeOptionDatesAndTimes(), initializeVolatilities(), and performCalculations().
boost::shared_ptr<AbcdInterpolation> QuantLib::AbcdAtmVolCurve::interpolation_ [private]
Definition at line 116 of file abcdatmvolcurve.hpp.
Referenced by a(), atmVolImpl(), b(), c(), d(), interpolate(), k(), maxError(), performCalculations(), and rmsError().
Size QuantLib::AbcdAtmVolCurve::nOptionTenors_ [private]
Definition at line 102 of file abcdatmvolcurve.hpp.
Referenced by checkInputs(), initializeOptionDatesAndTimes(), and initializeVolatilities().
std::vector<Date> QuantLib::AbcdAtmVolCurve::optionDates_ [mutable, private]
Definition at line 105 of file abcdatmvolcurve.hpp.
Referenced by initializeOptionDatesAndTimes(), and optionDates().
std::vector<Period> QuantLib::AbcdAtmVolCurve::optionTenors_ [private]
Definition at line 103 of file abcdatmvolcurve.hpp.
Referenced by checkInputs(), initializeOptionDatesAndTimes(), maxDate(), and optionTenors().
std::vector<Time> QuantLib::AbcdAtmVolCurve::optionTimes_ [mutable, private]
Definition at line 106 of file abcdatmvolcurve.hpp.
Referenced by initializeOptionDatesAndTimes(), and optionTimes().
std::vector<Handle<Quote> > QuantLib::AbcdAtmVolCurve::volHandles_ [private]
Definition at line 110 of file abcdatmvolcurve.hpp.
Referenced by AbcdAtmVolCurve(), initializeVolatilities(), performCalculations(), and registerWithMarketData().
std::vector<Volatility> QuantLib::AbcdAtmVolCurve::vols_ [mutable, private]
Definition at line 111 of file abcdatmvolcurve.hpp.
Referenced by AbcdAtmVolCurve(), checkInputs(), initializeVolatilities(), and performCalculations().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/volatility/abcdatmvolcurve.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/volatility/abcdatmvolcurve.cpp