QuantLib: QuantLib::LevenbergMarquardt Class Reference
QuantLib::LevenbergMarquardt Class Reference
Levenberg-Marquardt optimization method.
#include <levenbergmarquardt.hpp>
Public Member Functions
LevenbergMarquardt (Real epsfcn=1.0e-8, Real xtol=1.0e-8, Real gtol=1.0e-8)
virtual EndCriteria::Type minimize (Problem &P, const EndCriteria &endCriteria)
minimize the optimization problem P
virtual Integer getInfo () const
void fcn (int m, int n, double *x, double *fvec, int *iflag)
Private Attributes
Problem * currentProblem_
Array initCostValues_
Integer info_
const Real epsfcn_
const Real xtol_
const Real gtol_
Detailed Description
Levenberg-Marquardt optimization method.
This implementation is based on MINPACK (<http://www.netlib.org/minpack>, <http://www.netlib.org/cephes/linalg.tgz>)
Definition at line 36 of file levenbergmarquardt.hpp.
Constructor & Destructor Documentation
QuantLib::LevenbergMarquardt::LevenbergMarquardt (Real epsfcn = 1.0e-8, Real xtol = 1.0e-8, Real gtol = 1.0e-8)
Definition at line 27 of file levenbergmarquardt.cpp.
    : info_(0), epsfcn_(epsfcn), xtol_(xtol), gtol_(gtol) {}
Member Function Documentation
void QuantLib::LevenbergMarquardt::fcn (int m, int n, double * x, double * fvec, int * iflag)
Definition at line 113 of file levenbergmarquardt.cpp.
References QuantLib::Array::begin(), QuantLib::Problem::constraint(), currentProblem_, QuantLib::Array::end(), initCostValues_, QuantLib::Constraint::test(), and QuantLib::Problem::values().
Referenced by minimize().
{
        Array xt(n);
        std::copy(x, x+n, xt.begin());
        // constraint handling needs some improvement in the future:
        // starting point should not be close to a constraint violation
        if (currentProblem_->constraint().test(xt)) {
            const Array& tmp = currentProblem_->values(xt);
            std::copy(tmp.begin(), tmp.end(), fvec);
        } else {
            std::copy(initCostValues_.begin(), initCostValues_.end(), fvec);
        }
    }
Integer QuantLib::LevenbergMarquardt::getInfo () const [virtual]
Definition at line 32 of file levenbergmarquardt.cpp.
References info_.
{
        return info_;
    }
EndCriteria::Type QuantLib::LevenbergMarquardt::minimize (Problem & P, const EndCriteria & endCriteria) [virtual]
minimize the optimization problem P
Implements QuantLib::OptimizationMethod.
Definition at line 36 of file levenbergmarquardt.cpp.
References QuantLib::Array::begin(), QuantLib::EndCriteria::checkMaxIterations(), QuantLib::Problem::costFunction(), currentProblem_, QuantLib::Problem::currentValue(), QuantLib::Array::end(), epsfcn_, fcn(), QuantLib::EndCriteria::functionEpsilon(), gtol_, info_, initCostValues_, QuantLib::MINPACK::lmdif(), QuantLib::EndCriteria::maxIterations(), QuantLib::EndCriteria::None, QL_REQUIRE, QuantLib::Problem::reset(), QuantLib::Problem::setCurrentValue(), QuantLib::Problem::setFunctionValue(), QuantLib::Array::size(), QuantLib::EndCriteria::StationaryFunctionValue, QuantLib::CostFunction::value(), QuantLib::CostFunction::values(), and xtol_.
Referenced by QuantLib::LocalBootstrap< Curve >::calculate(), OptimizersTest::nestedOptimizationTest(), and anonymous_namespace{optimizers.cpp}::OptimizationBasedCostFunction::values().
{
        EndCriteria::Type ecType = EndCriteria::None;
        P.reset();
        Array x_ = P.currentValue();
        currentProblem_ = &P;
        initCostValues_ = P.costFunction().values(x_);
        int m = initCostValues_.size();
        int n = x_.size();
        boost::scoped_array<double> xx(new double[n]);
        std::copy(x_.begin(), x_.end(), xx.get());
        boost::scoped_array<double> fvec(new double[m]);
        boost::scoped_array<double> diag(new double[n]);
        int mode = 1;
        double factor = 1;
        int nprint = 0;
        int info = 0;
        int nfev =0;
        boost::scoped_array<double> fjac(new double[m*n]);
        int ldfjac = m;
        boost::scoped_array<int> ipvt(new int[n]);
        boost::scoped_array<double> qtf(new double[n]);
        boost::scoped_array<double> wa1(new double[n]);
        boost::scoped_array<double> wa2(new double[n]);
        boost::scoped_array<double> wa3(new double[n]);
        boost::scoped_array<double> wa4(new double[m]);
        // requirements; check here to get more detailed error messages.
        QL_REQUIRE(n > 0, "no variables given");
        QL_REQUIRE(m >= n,
                   "less functions (" << m <<
                   ") than available variables (" << n << ")");
        QL_REQUIRE(endCriteria.functionEpsilon() >= 0.0,
                   "negative f tolerance");
        QL_REQUIRE(xtol_ >= 0.0, "negative x tolerance");
        QL_REQUIRE(gtol_ >= 0.0, "negative g tolerance");
        QL_REQUIRE(endCriteria.maxIterations() > 0,
                   "null number of evaluations");
        // call lmdif to minimize the sum of the squares of m functions
        // in n variables by the Levenberg-Marquardt algorithm.
        MINPACK::LmdifCostFunction lmdifCostFunction =
            boost::bind(&LevenbergMarquardt::fcn, this, _1, _2, _3, _4, _5);
        MINPACK::lmdif(m, n, xx.get(), fvec.get(),
                       static_cast<double>(endCriteria.functionEpsilon()),
                       static_cast<double>(xtol_),
                       static_cast<double>(gtol_),
                       static_cast<int>(endCriteria.maxIterations()),
                       static_cast<double>(epsfcn_),
                       diag.get(), mode, factor,
                       nprint, &info, &nfev, fjac.get(),
                       ldfjac, ipvt.get(), qtf.get(),
                       wa1.get(), wa2.get(), wa3.get(), wa4.get(),
                       lmdifCostFunction);
        info_ = info;
        // check requirements & endCriteria evaluation
        QL_REQUIRE(info != 0, "MINPACK: improper input parameters");
        //QL_REQUIRE(info != 6, "MINPACK: ftol is too small. no further "
        //                               "reduction in the sum of squares "
        //                               "is possible.");
        if (info != 6) ecType = QuantLib::EndCriteria::StationaryFunctionValue;
        //QL_REQUIRE(info != 5, "MINPACK: number of calls to fcn has "
        //                               "reached or exceeded maxfev.");
        endCriteria.checkMaxIterations(nfev, ecType);
        QL_REQUIRE(info != 7, "MINPACK: xtol is too small. no further "
                                       "improvement in the approximate "
                                       "solution x is possible.");
        QL_REQUIRE(info != 8, "MINPACK: gtol is too small. fvec is "
                                       "orthogonal to the columns of the "
                                       "jacobian to machine precision.");
        // set problem
        std::copy(xx.get(), xx.get()+n, x_.begin());
        P.setCurrentValue(x_);
        P.setFunctionValue(P.costFunction().value(x_));
        return ecType;
    }
Member Data Documentation
Problem* QuantLib::LevenbergMarquardt::currentProblem_ [private]
Definition at line 52 of file levenbergmarquardt.hpp.
Referenced by fcn(), and minimize().
const Real QuantLib::LevenbergMarquardt::epsfcn_ [private]
Definition at line 55 of file levenbergmarquardt.hpp.
Referenced by minimize().
const Real QuantLib::LevenbergMarquardt::gtol_ [private]
Definition at line 55 of file levenbergmarquardt.hpp.
Referenced by minimize().
Integer QuantLib::LevenbergMarquardt::info_ [mutable, private]
Definition at line 54 of file levenbergmarquardt.hpp.
Referenced by getInfo(), and minimize().
Array QuantLib::LevenbergMarquardt::initCostValues_ [private]
Definition at line 53 of file levenbergmarquardt.hpp.
Referenced by fcn(), and minimize().
const Real QuantLib::LevenbergMarquardt::xtol_ [private]
Definition at line 55 of file levenbergmarquardt.hpp.
Referenced by minimize().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/optimization/levenbergmarquardt.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/math/optimization/levenbergmarquardt.cpp