QuantLib: ConvertibleBondTest Class Reference
ConvertibleBondTest Class Reference
#include <convertiblebonds.hpp>
Static Public Member Functions
static void testBond ()
static void testOption ()
static void testRegression ()
static
boost::unit_test_framework::test_suite * suite ()
Detailed Description
Definition at line 28 of file convertiblebonds.hpp.
Member Function Documentation
test_suite * ConvertibleBondTest::suite () [static]
Definition at line 457 of file convertiblebonds.cpp.
References QUANTLIB_TEST_CASE, testBond(), testOption(), and testRegression().
Referenced by init_unit_test_suite().
{
    test_suite* suite = BOOST_TEST_SUITE("Convertible bond tests");
    suite->add(QUANTLIB_TEST_CASE(&ConvertibleBondTest::testBond));
    suite->add(QUANTLIB_TEST_CASE(&ConvertibleBondTest::testOption));
    suite->add(QUANTLIB_TEST_CASE(&ConvertibleBondTest::testRegression));
    return suite;
}
void ConvertibleBondTest::testBond () [static]
Definition at line 112 of file convertiblebonds.cpp.
References QuantLib::DateGeneration::Backward, QuantLib::MakeSchedule::backwards(), QuantLib::Bond::cashflows(), QuantLib::Following, QuantLib::MakeSchedule::from(), QuantLib::Instrument::NPV(), QuantLib::Once, QuantLib::setCouponPricer(), QuantLib::Instrument::setPricingEngine(), QuantLib::Bond::settlementValue(), QuantLib::MakeSchedule::to(), anonymous_namespace{gaussianquadratures.cpp}::tolerance, QuantLib::MakeSchedule::withCalendar(), and QuantLib::MakeSchedule::withFrequency().
Referenced by init_unit_test_suite(), and suite().
{
    /* when deeply out-of-the-money, the value of the convertible bond
       should equal that of the underlying plain-vanilla bond. */
    BOOST_MESSAGE(
       "Testing out-of-the-money convertible bonds against vanilla bonds...");
    CommonVars vars;
    vars.conversionRatio = 1.0e-16;
    boost::shared_ptr<Exercise> euExercise(
                                     new EuropeanExercise(vars.maturityDate));
    boost::shared_ptr<Exercise> amExercise(
                                     new AmericanExercise(vars.issueDate,
                                                          vars.maturityDate));
    Size timeSteps = 1001;
    boost::shared_ptr<PricingEngine> engine(
        new BinomialConvertibleEngine<CoxRossRubinstein>(vars.process,
                                                         timeSteps));
    Handle<YieldTermStructure> discountCurve(
         boost::shared_ptr<YieldTermStructure>(
             new ForwardSpreadedTermStructure(vars.riskFreeRate,
                                              vars.creditSpread)));
    // zero-coupon
    Schedule schedule =
        MakeSchedule().from(vars.issueDate)
                      .to(vars.maturityDate)
                      .withFrequency(Once)
                      .withCalendar(vars.calendar)
                      .backwards();
    ConvertibleZeroCouponBond euZero(euExercise, vars.conversionRatio,
                                     vars.no_dividends, vars.no_callability,
                                     vars.creditSpread,
                                     vars.issueDate, vars.settlementDays,
                                     vars.dayCounter, schedule,
                                     vars.redemption);
    euZero.setPricingEngine(engine);
    ConvertibleZeroCouponBond amZero(amExercise, vars.conversionRatio,
                                     vars.no_dividends, vars.no_callability,
                                     vars.creditSpread,
                                     vars.issueDate, vars.settlementDays,
                                     vars.dayCounter, schedule,
                                     vars.redemption);
    amZero.setPricingEngine(engine);
    ZeroCouponBond zero(vars.settlementDays, vars.calendar,
                        100.0, vars.maturityDate,
                        Following, vars.redemption, vars.issueDate);
    boost::shared_ptr<PricingEngine> bondEngine(
                                    new DiscountingBondEngine(discountCurve));
    zero.setPricingEngine(bondEngine);
    Real tolerance = 1.0e-2 * (vars.faceAmount/100.0);
    Real error = std::fabs(euZero.NPV()-zero.settlementValue());
    if (error > tolerance) {
        BOOST_ERROR("failed to reproduce zero-coupon bond price:"
                    << "\n    calculated: " << euZero.NPV()
                    << "\n    expected:   " << zero.settlementValue()
                    << "\n    error:      " << error);
    }
    error = std::fabs(amZero.NPV()-zero.settlementValue());
    if (error > tolerance) {
        BOOST_ERROR("failed to reproduce zero-coupon bond price:"
                    << "\n    calculated: " << amZero.NPV()
                    << "\n    expected:   " << zero.settlementValue()
                    << "\n    error:      " << error);
    }
    // coupon
    std::vector<Rate> coupons(1, 0.05);
    schedule = MakeSchedule().from(vars.issueDate)
                             .to(vars.maturityDate)
                             .withFrequency(vars.frequency)
                             .withCalendar(vars.calendar)
                             .backwards();
    ConvertibleFixedCouponBond euFixed(euExercise, vars.conversionRatio,
                                       vars.no_dividends, vars.no_callability,
                                       vars.creditSpread,
                                       vars.issueDate, vars.settlementDays,
                                       coupons, vars.dayCounter,
                                       schedule, vars.redemption);
    euFixed.setPricingEngine(engine);
    ConvertibleFixedCouponBond amFixed(amExercise, vars.conversionRatio,
                                       vars.no_dividends, vars.no_callability,
                                       vars.creditSpread,
                                       vars.issueDate, vars.settlementDays,
                                       coupons, vars.dayCounter,
                                       schedule, vars.redemption);
    amFixed.setPricingEngine(engine);
    FixedRateBond fixed(vars.settlementDays, vars.faceAmount, schedule,
                        coupons, vars.dayCounter, Following,
                        vars.redemption, vars.issueDate);
    fixed.setPricingEngine(bondEngine);
    tolerance = 2.0e-2 * (vars.faceAmount/100.0);
    error = std::fabs(euFixed.NPV()-fixed.settlementValue());
    if (error > tolerance) {
        BOOST_ERROR("failed to reproduce fixed-coupon bond price:"
                    << "\n    calculated: " << euFixed.NPV()
                    << "\n    expected:   " << fixed.settlementValue()
                    << "\n    error:      " << error);
    }
    error = std::fabs(amFixed.NPV()-fixed.settlementValue());
    if (error > tolerance) {
        BOOST_ERROR("failed to reproduce fixed-coupon bond price:"
                    << "\n    calculated: " << amFixed.NPV()
                    << "\n    expected:   " << fixed.settlementValue()
                    << "\n    error:      " << error);
    }
    // floating-rate
    boost::shared_ptr<IborIndex> index(new Euribor1Y(discountCurve));
    Natural fixingDays = 2;
    std::vector<Real> gearings(1, 1.0);
    std::vector<Rate> spreads;
    ConvertibleFloatingRateBond euFloating(euExercise, vars.conversionRatio,
                                           vars.no_dividends, vars.no_callability,
                                           vars.creditSpread,
                                           vars.issueDate, vars.settlementDays,
                                           index, fixingDays, spreads,
                                           vars.dayCounter, schedule,
                                           vars.redemption);
    euFloating.setPricingEngine(engine);
    ConvertibleFloatingRateBond amFloating(amExercise, vars.conversionRatio,
                                           vars.no_dividends, vars.no_callability,
                                           vars.creditSpread,
                                           vars.issueDate, vars.settlementDays,
                                           index, fixingDays, spreads,
                                           vars.dayCounter, schedule,
                                           vars.redemption);
    amFloating.setPricingEngine(engine);
    boost::shared_ptr<IborCouponPricer> pricer(new
        BlackIborCouponPricer(Handle<OptionletVolatilityStructure>()));
    Schedule floatSchedule(vars.issueDate, vars.maturityDate,
                           Period(vars.frequency),
                           vars.calendar, Following, Following,
                           DateGeneration::Backward, false);
    FloatingRateBond floating(vars.settlementDays, vars.faceAmount, floatSchedule,
                              index, vars.dayCounter, Following, fixingDays,
                              gearings, spreads,
                              std::vector<Rate>(), std::vector<Rate>(),
                              false,
                              vars.redemption, vars.issueDate);
    floating.setPricingEngine(bondEngine);
    setCouponPricer(floating.cashflows(),pricer);
    tolerance = 2.0e-2 * (vars.faceAmount/100.0);
    error = std::fabs(euFloating.NPV()-floating.settlementValue());
    if (error > tolerance) {
        BOOST_ERROR("failed to reproduce floating-rate bond price:"
                    << "\n    calculated: " << euFloating.NPV()
                    << "\n    expected:   " << floating.settlementValue()
                    << "\n    error:      " << error);
    }
    error = std::fabs(amFloating.NPV()-floating.settlementValue());
    if (error > tolerance) {
        BOOST_ERROR("failed to reproduce floating-rate bond price:"
                    << "\n    calculated: " << amFloating.NPV()
                    << "\n    expected:   " << floating.settlementValue()
                    << "\n    error:      " << error);
    }
}
void ConvertibleBondTest::testOption () [static]
Definition at line 303 of file convertiblebonds.cpp.
References QuantLib::MakeSchedule::backwards(), QuantLib::Option::Call, QuantLib::MakeSchedule::from(), QuantLib::Instrument::NPV(), QuantLib::Once, QuantLib::Instrument::setPricingEngine(), QuantLib::MakeSchedule::to(), anonymous_namespace{gaussianquadratures.cpp}::tolerance, QuantLib::MakeSchedule::withCalendar(), and QuantLib::MakeSchedule::withFrequency().
Referenced by suite().
{
    /* a zero-coupon convertible bond with no credit spread is
       equivalent to a call option. */
    BOOST_MESSAGE(
       "Testing zero-coupon convertible bonds against vanilla option...");
    CommonVars vars;
    boost::shared_ptr<Exercise> euExercise(new
                                    EuropeanExercise(vars.maturityDate));
    vars.settlementDays = 0;
    Size timeSteps = 1001;
    boost::shared_ptr<PricingEngine> engine(
        new BinomialConvertibleEngine<CoxRossRubinstein>(vars.process,
                                                         timeSteps));
    boost::shared_ptr<PricingEngine> vanillaEngine(
            new BinomialVanillaEngine<CoxRossRubinstein>(vars.process,
                                                         timeSteps));
    vars.creditSpread.linkTo(boost::shared_ptr<Quote>(new SimpleQuote(0.0)));
    Real conversionStrike = vars.redemption/vars.conversionRatio;
    boost::shared_ptr<StrikedTypePayoff> payoff(
                      new PlainVanillaPayoff(Option::Call, conversionStrike));
    Schedule schedule = MakeSchedule().from(vars.issueDate)
                                      .to(vars.maturityDate)
                                      .withFrequency(Once)
                                      .withCalendar(vars.calendar)
                                      .backwards();
    ConvertibleZeroCouponBond euZero(euExercise, vars.conversionRatio,
                                     vars.no_dividends, vars.no_callability,
                                     vars.creditSpread,
                                     vars.issueDate, vars.settlementDays,
                                     vars.dayCounter, schedule,
                                     vars.redemption);
    euZero.setPricingEngine(engine);
    VanillaOption euOption(payoff, euExercise);
    euOption.setPricingEngine(vanillaEngine);
    Real tolerance = 5.0e-2 * (vars.faceAmount/100.0);
    Real expected = vars.faceAmount/100.0 *
        (vars.redemption * vars.riskFreeRate->discount(vars.maturityDate)
         + vars.conversionRatio* euOption.NPV());
    Real error = std::fabs(euZero.NPV()-expected);
    if (error > tolerance) {
        BOOST_ERROR("failed to reproduce plain-option price:"
                    << "\n    calculated: " << euZero.NPV()
                    << "\n    expected:   " << expected
                    << "\n    error:      " << error);
    }
}
void ConvertibleBondTest::testRegression () [static]
Definition at line 363 of file convertiblebonds.cpp.
References QuantLib::August, QuantLib::Thirty360::BondBasis, anonymous_namespace{marketmodel.cpp}::calendar, anonymous_namespace{marketmodel.cpp}::dates, anonymous_namespace{marketmodel.cpp}::dayCounter, QuantLib::December, QuantLib::Settings::evaluationDate(), QuantLib::February, QuantLib::MakeSchedule::from(), QuantLib::Singleton< Settings >::instance(), QuantLib::January, QuantLib::July, QuantLib::June, QuantLib::March, QuantLib::Months, QuantLib::Instrument::NPV(), QuantLib::Instrument::setPricingEngine(), anonymous_namespace{distributions.cpp}::sigma, QuantLib::MakeSchedule::to(), QuantLib::Unadjusted, QuantLib::MakeSchedule::withCalendar(), QuantLib::MakeSchedule::withConvention(), and QuantLib::MakeSchedule::withTenor().
Referenced by suite().
{
    BOOST_MESSAGE(
       "Testing fixed-coupon convertible bond in known regression case...");
    using namespace boost;
    SavedSettings backup;
    Date today = Date(23, December, 2008);
    Date tomorrow = today + 1;
    Settings::instance().evaluationDate() = tomorrow;
    Handle<Quote> u(shared_ptr<Quote>(new SimpleQuote(2.9084382818797443)));
    std::vector<Date> dates(25);
    std::vector<Rate> forwards(25);
    dates[0] = Date(29,December,2008);   forwards[0] = 0.0025999342800;
    dates[1] = Date(5,January,2009);     forwards[1] = 0.0025999342800;
    dates[2] = Date(29,January,2009);    forwards[2] = 0.0053123275500;
    dates[3] = Date(27,February,2009);   forwards[3] = 0.0197049598721;
    dates[4] = Date(30,March,2009);      forwards[4] = 0.0220524845296;
    dates[5] = Date(29,June,2009);       forwards[5] = 0.0217076395643;
    dates[6] = Date(29,December,2009);   forwards[6] = 0.0230349627478;
    dates[7] = Date(29,December,2010);   forwards[7] = 0.0087631647476;
    dates[8] = Date(29,December,2011);   forwards[8] = 0.0219084299499;
    dates[9] = Date(31,December,2012);   forwards[9] = 0.0244798766219;
    dates[10] = Date(30,December,2013);  forwards[10] = 0.0267885498456;
    dates[11] = Date(29,December,2014);  forwards[11] = 0.0266922867562;
    dates[12] = Date(29,December,2015);  forwards[12] = 0.0271052126386;
    dates[13] = Date(29,December,2016);  forwards[13] = 0.0268829891648;
    dates[14] = Date(29,December,2017);  forwards[14] = 0.0264594744498;
    dates[15] = Date(31,December,2018);  forwards[15] = 0.0273450367424;
    dates[16] = Date(30,December,2019);  forwards[16] = 0.0294852614749;
    dates[17] = Date(29,December,2020);  forwards[17] = 0.0285556119719;
    dates[18] = Date(29,December,2021);  forwards[18] = 0.0305557764659;
    dates[19] = Date(29,December,2022);  forwards[19] = 0.0292244738422;
    dates[20] = Date(29,December,2023);  forwards[20] = 0.0263917004194;
    dates[21] = Date(29,December,2028);  forwards[21] = 0.0239626970243;
    dates[22] = Date(29,December,2033);  forwards[22] = 0.0216417108090;
    dates[23] = Date(29,December,2038);  forwards[23] = 0.0228343838422;
    dates[24] = Date(31,December,2199);  forwards[24] = 0.0228343838422;
    Handle<YieldTermStructure> r(shared_ptr<YieldTermStructure>(
                             new ForwardCurve(dates, forwards, Actual360())));
    Handle<BlackVolTermStructure> sigma(shared_ptr<BlackVolTermStructure>(
            new BlackConstantVol(tomorrow, NullCalendar(), 21.685235548092248,
                                 Thirty360(Thirty360::BondBasis))));
    shared_ptr<BlackProcess> process(new BlackProcess(u,r,sigma));
    Handle<Quote> spread(shared_ptr<Quote>(
                                     new SimpleQuote(0.11498700678012874)));
    Date issueDate(23, July, 2008);
    Date maturityDate(1, August, 2013);
    Calendar calendar = UnitedStates();
    Schedule schedule = MakeSchedule().from(issueDate)
                                      .to(maturityDate)
                                      .withTenor(6*Months)
                                      .withCalendar(calendar)
                                      .withConvention(Unadjusted);
    Integer settlementDays = 3;
    shared_ptr<Exercise> exercise(new EuropeanExercise(maturityDate));
    Real conversionRatio = 100.0/20.3175;
    std::vector<Rate> coupons(schedule.size()-1, 0.05);
    DayCounter dayCounter = Thirty360(Thirty360::BondBasis);
    CallabilitySchedule no_callability;
    DividendSchedule no_dividends;
    Real redemption = 100.0;
    ConvertibleFixedCouponBond bond(exercise, conversionRatio,
                                    no_dividends, no_callability,
                                    spread, issueDate, settlementDays,
                                    coupons, dayCounter,
                                    schedule, redemption);
    bond.setPricingEngine(shared_ptr<PricingEngine>(
             new BinomialConvertibleEngine<CoxRossRubinstein>(process, 600)));
    try {
        Real x = bond.NPV();  // should throw; if not, an INF was not detected.
        BOOST_FAIL("INF result was not detected: " << x << " returned");
    } catch (Error&) {
        // as expected. Do nothing.
        // Note: we're expecting an Error we threw, not just any
        // exception.  If something else is thrown, then there's
        // another problem and the test must fail.
    }
}
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/convertiblebonds.hpp
/home/deriversatile/QuantLib/QuantLibQt/test-suite/convertiblebonds.cpp