QuantLib: QuantLib::GenericRiskStatistics< S > Class Template Reference
QuantLib::GenericRiskStatistics< S > Class Template Reference
empirical-distribution risk measures
#include <riskstatistics.hpp>
Public Types
typedef S::value_type value_type
Public Member Functions
Real semiVariance () const
Real semiDeviation () const
Real downsideVariance () const
Real downsideDeviation () const
Real regret (Real target) const
Real potentialUpside (Real percentile) const
potential upside (the reciprocal of VAR) at a given percentile
Real valueAtRisk (Real percentile) const
value-at-risk at a given percentile
Real expectedShortfall (Real percentile) const
expected shortfall at a given percentile
Real shortfall (Real target) const
Real averageShortfall (Real target) const
Detailed Description
template<class S>
class QuantLib::GenericRiskStatistics< S >
empirical-distribution risk measures
This class wraps a somewhat generic statistic tool and adds a number of risk measures (e.g.: value-at-risk, expected shortfall, etc.) based on the data distribution as reported by the underlying statistic tool.
Todo:
add historical annualized volatility
Definition at line 42 of file riskstatistics.hpp.
Member Typedef Documentation
template<class S > typedef S::value_type QuantLib::GenericRiskStatistics< S >::value_type
Definition at line 44 of file riskstatistics.hpp.
Member Function Documentation
template<class S > Real QuantLib::GenericRiskStatistics< S >::averageShortfall (Real target) const
averaged shortfallness, defined as
\[ \mathrm{E}\left[ t-x \;|\; x<t \right] \]
Definition at line 218 of file riskstatistics.hpp.
References anonymous_namespace{matrices.cpp}::N, and QL_ENSURE.
Referenced by RiskStatisticsTest::testResults().
              {
        std::pair<Real,Size> result =
            this->expectationValue(std::bind1st(std::minus<Real>(),
                                                target),
                                   std::bind2nd(std::less<Real>(),
                                                target));
        Real x = result.first;
        Size N = result.second;
        QL_ENSURE(N != 0, "no data below the target");
        return x;
    }
template<class S > Real QuantLib::GenericRiskStatistics< S >::downsideDeviation () const [inline]
returns the downside deviation, defined as the square root of the downside variance.
Definition at line 146 of file riskstatistics.hpp.
{
        return std::sqrt(downsideVariance());
    }
template<class S > Real QuantLib::GenericRiskStatistics< S >::downsideVariance () const [inline]
returns the variance of observations below 0.0,
\[ \frac{N}{N-1} \mathrm{E}\left[ x^2 \;|\; x < 0\right]. \]
Definition at line 141 of file riskstatistics.hpp.
Referenced by RiskStatisticsTest::testResults().
{
        return regret(0.0);
    }
template<class S > Real QuantLib::GenericRiskStatistics< S >::expectedShortfall (Real centile) const
expected shortfall at a given percentile
returns the expected loss in case that the loss exceeded a VaR threshold,
\[ \mathrm{E}\left[ x \;|\; x < \mathrm{VaR}(p) \right], \]
that is the average of observations below the given percentile \(p \). Also know as conditional value-at-risk.
See Artzner, Delbaen, Eber and Heath, "Coherent measures of risk", Mathematical Finance 9 (1999)
Precondition:
percentile must be in range [90%-100%)
Definition at line 191 of file riskstatistics.hpp.
References anonymous_namespace{matrices.cpp}::N, QL_ENSURE, and QL_REQUIRE.
Referenced by RiskStatisticsTest::testResults().
{
        QL_REQUIRE(centile>=0.9 && centile<1.0,
                   "percentile (" << centile << ") out of range [0.9, 1.0)");
        QL_ENSURE(this->samples() != 0, "empty sample set");
        Real target = -valueAtRisk(centile);
        std::pair<Real,Size> result =
            this->expectationValue(identity<Real>(),
                             std::bind2nd(std::less<Real>(),
                                          target));
        Real x = result.first;
        Size N = result.second;
        QL_ENSURE(N != 0, "no data below the target");
        // must be a loss, i.e., capped at 0.0 and negated
        return -std::min<Real>(x, 0.0);
    }
template<class S > Real QuantLib::GenericRiskStatistics< S >::potentialUpside (Real centile) const
potential upside (the reciprocal of VAR) at a given percentile
Precondition:
percentile must be in range [90%-100%)
Definition at line 169 of file riskstatistics.hpp.
References QL_REQUIRE.
Referenced by RiskStatisticsTest::testResults().
              {
        QL_REQUIRE(centile>=0.9 && centile<1.0,
                   "percentile (" << centile << ") out of range [0.9, 1.0)");
        // potential upside must be a gain, i.e., floored at 0.0
        return std::max<Real>(this->percentile(centile), 0.0);
    }
template<class S > Real QuantLib::GenericRiskStatistics< S >::regret (Real target) const
returns the variance of observations below target,
\[ \frac{N}{N-1} \mathrm{E}\left[ (x-t)^2 \;|\; x < t \right]. \]
See Dembo and Freeman, "The Rules Of Risk", Wiley (2001).
Definition at line 153 of file riskstatistics.hpp.
References QuantLib::compose(), anonymous_namespace{matrices.cpp}::N, and QL_REQUIRE.
Referenced by RiskStatisticsTest::testResults().
{
        // average over the range below the target
        std::pair<Real,Size> result =
            this->expectationValue(compose(square<Real>(),
                                           std::bind2nd(std::minus<Real>(),
                                                        target)),
                                   std::bind2nd(std::less<Real>(),  target));
        Real x = result.first;
        Size N = result.second;
        QL_REQUIRE(N > 1,
                   "samples under target <= 1, unsufficient");
        return (N/(N-1.0))*x;
    }
template<class S > Real QuantLib::GenericRiskStatistics< S >::semiDeviation () const [inline]
returns the semi deviation, defined as the square root of the semi variance.
Definition at line 136 of file riskstatistics.hpp.
{
        return std::sqrt(semiVariance());
    }
template<class S > Real QuantLib::GenericRiskStatistics< S >::semiVariance () const [inline]
returns the variance of observations below the mean,
\[ \frac{N}{N-1} \mathrm{E}\left[ (x-\langle x \rangle)^2 \;|\; x < \langle x \rangle \right]. \]
See Markowitz (1959).
Definition at line 131 of file riskstatistics.hpp.
{
        return regret(this->mean());
    }
template<class S > Real QuantLib::GenericRiskStatistics< S >::shortfall (Real target) const
probability of missing the given target, defined as
\[ \mathrm{E}\left[ \Theta \;|\; (-\infty,\infty) \right] \]
where
\[ \Theta(x) = \left\{ \begin{array}{ll} 1 & x < t \\ 0 & x \geq t \end{array} \right. \]
Definition at line 209 of file riskstatistics.hpp.
References QuantLib::clip(), and QL_ENSURE.
Referenced by RiskStatisticsTest::testResults().
{
        QL_ENSURE(this->samples() != 0, "empty sample set");
        return this->expectationValue(clip(constant<Real,Real>(1.0),
                                           std::bind2nd(std::less<Real>(),
                                                        target)),
                                      everywhere()).first;
    }
template<class S > Real QuantLib::GenericRiskStatistics< S >::valueAtRisk (Real centile) const
value-at-risk at a given percentile
Precondition:
percentile must be in range [90%-100%)
Definition at line 180 of file riskstatistics.hpp.
References QL_REQUIRE.
Referenced by RiskStatisticsTest::testResults().
{
        QL_REQUIRE(centile>=0.9 && centile<1.0,
                   "percentile (" << centile << ") out of range [0.9, 1.0)");
        // must be a loss, i.e., capped at 0.0 and negated
        return -std::min<Real>(this->percentile(1.0-centile), 0.0);
    }
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/statistics/riskstatistics.hpp