QuantLib: QuantLib::PiecewiseConstantCorrelation Class Reference
QuantLib::PiecewiseConstantCorrelation Class Reference
#include <piecewiseconstantcorrelation.hpp>
Public Member Functions
virtual ~PiecewiseConstantCorrelation ()
virtual const std::vector< Time > & times () const =0
virtual const std::vector< Time > & rateTimes () const =0
virtual const std::vector
< Matrix > & correlations () const =0
virtual const Matrix & correlation (Size i) const
virtual Size numberOfRates () const =0
Detailed Description
Definition at line 32 of file piecewiseconstantcorrelation.hpp.
Constructor & Destructor Documentation
virtual QuantLib::PiecewiseConstantCorrelation::~PiecewiseConstantCorrelation () [inline, virtual]
Definition at line 34 of file piecewiseconstantcorrelation.hpp.
{}
Member Function Documentation
const Matrix & QuantLib::PiecewiseConstantCorrelation::correlation (Size i) const [inline, virtual]
Definition at line 43 of file piecewiseconstantcorrelation.hpp.
References correlations(), and QL_REQUIRE.
Referenced by QuantLib::CTSMMCapletOriginalCalibration::calibrationFunction(), QuantLib::CTSMMCapletAlphaFormCalibration::capletAlphaFormCalibration(), QuantLib::CTSMMCapletMaxHomogeneityCalibration::capletMaxHomogeneityCalibration(), and QuantLib::coterminalSwapPseudoRoots().
{
        const std::vector<Matrix>& results = correlations();
        QL_REQUIRE(i<results.size(),
                   "index (" << i <<
                   ") must be less than correlations vector size (" <<
                   results.size() << ")");
        return results[i];
    }
virtual const std::vector<Matrix>& QuantLib::PiecewiseConstantCorrelation::correlations () const [pure virtual]
Implemented in QuantLib::ExponentialForwardCorrelation, QuantLib::CotSwapFromFwdCorrelation, and QuantLib::TimeHomogeneousForwardCorrelation.
Referenced by correlation().
virtual Size QuantLib::PiecewiseConstantCorrelation::numberOfRates () const [pure virtual]
Implemented in QuantLib::ExponentialForwardCorrelation, QuantLib::CotSwapFromFwdCorrelation, and QuantLib::TimeHomogeneousForwardCorrelation.
Referenced by QuantLib::CTSMMCapletCalibration::performChecks().
virtual const std::vector<Time>& QuantLib::PiecewiseConstantCorrelation::rateTimes () const [pure virtual]
Implemented in QuantLib::ExponentialForwardCorrelation, QuantLib::CotSwapFromFwdCorrelation, and QuantLib::TimeHomogeneousForwardCorrelation.
virtual const std::vector<Time>& QuantLib::PiecewiseConstantCorrelation::times () const [pure virtual]
Implemented in QuantLib::ExponentialForwardCorrelation, QuantLib::CotSwapFromFwdCorrelation, and QuantLib::TimeHomogeneousForwardCorrelation.
Referenced by QuantLib::CTSMMCapletOriginalCalibration::calibrationFunction(), QuantLib::CTSMMCapletAlphaFormCalibration::capletAlphaFormCalibration(), QuantLib::CTSMMCapletMaxHomogeneityCalibration::capletMaxHomogeneityCalibration(), QuantLib::coterminalSwapPseudoRoots(), and QuantLib::CTSMMCapletCalibration::performChecks().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/piecewiseconstantcorrelation.hpp