QuantLib: QuantLib::MultiPath Class Reference
QuantLib::MultiPath Class Reference
Correlated multiple asset paths.
#include <multipath.hpp>
Public Member Functions
MultiPath ()
MultiPath (Size nAsset, const TimeGrid &timeGrid)
MultiPath (const std::vector< Path > &multiPath)
inspectors
Size assetNumber () const
Size pathSize () const
read/write access to components
const Path & operator[] (Size j) const
const Path & at (Size j) const
Path & operator[] (Size j)
Path & at (Size j)
Private Attributes
std::vector< Path > multiPath_
Detailed Description
Correlated multiple asset paths.
MultiPath contains the list of paths for each asset, i.e., multipath[j] is the path followed by the j-th asset.
Definition at line 38 of file multipath.hpp.
Constructor & Destructor Documentation
QuantLib::MultiPath::MultiPath () [inline]
Definition at line 40 of file multipath.hpp.
{}
QuantLib::MultiPath::MultiPath (Size nAsset, const TimeGrid & timeGrid) [inline]
Definition at line 63 of file multipath.hpp.
References QL_REQUIRE.
    : multiPath_(nAsset,Path(timeGrid)) {
        QL_REQUIRE(nAsset > 0, "number of asset must be positive");
    }
QuantLib::MultiPath::MultiPath (const std::vector< Path > & multiPath) [inline]
Definition at line 68 of file multipath.hpp.
    : multiPath_(multiPath) {}
Member Function Documentation
Size QuantLib::MultiPath::assetNumber () const [inline]
Definition at line 46 of file multipath.hpp.
References multiPath_.
Referenced by QuantLib::EuropeanPathMultiPathPricer::operator()(), QuantLib::HestonHullWhitePathPricer::operator()(), QuantLib::PagodaMultiPathPricer::operator()(), QuantLib::HimalayaMultiPathPricer::operator()(), QuantLib::EverestMultiPathPricer::operator()(), QuantLib::EuropeanMultiPathPricer::operator()(), anonymous_namespace{mclongstaffschwartzengine.cpp}::AmericanMaxPathPricer::state(), QuantLib::AmericanBasketPathPricer::state(), and QuantLib::LongstaffSchwartzMultiPathPricer::transformPath().
{ return multiPath_.size(); }
const Path& QuantLib::MultiPath::at (Size j) const [inline]
Definition at line 52 of file multipath.hpp.
References multiPath_.
{ return multiPath_.at(j); }
Path& QuantLib::MultiPath::at (Size j) [inline]
Definition at line 54 of file multipath.hpp.
References multiPath_.
{ return multiPath_.at(j); }
const Path& QuantLib::MultiPath::operator[] (Size j) const [inline]
Definition at line 51 of file multipath.hpp.
References multiPath_.
{ return multiPath_[j]; }
Path& QuantLib::MultiPath::operator[] (Size j) [inline]
Definition at line 53 of file multipath.hpp.
References multiPath_.
{ return multiPath_[j]; }
Size QuantLib::MultiPath::pathSize () const [inline]
Definition at line 47 of file multipath.hpp.
References multiPath_.
Referenced by QuantLib::MultiPathGenerator< GSG >::next(), QuantLib::EuropeanGJRGARCHPathPricer::operator()(), QuantLib::EuropeanHestonPathPricer::operator()(), QuantLib::EuropeanPathMultiPathPricer::operator()(), QuantLib::HestonHullWhitePathPricer::operator()(), QuantLib::PagodaMultiPathPricer::operator()(), QuantLib::HimalayaMultiPathPricer::operator()(), QuantLib::EverestMultiPathPricer::operator()(), QuantLib::EuropeanMultiPathPricer::operator()(), and QuantLib::EarlyExerciseTraits< MultiPath >::pathLength().
{ return multiPath_[0].length(); }
Member Data Documentation
std::vector<Path> QuantLib::MultiPath::multiPath_ [private]
Definition at line 57 of file multipath.hpp.
Referenced by assetNumber(), at(), operator[](), and pathSize().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/montecarlo/multipath.hpp