QuantLib: QuantLib::FdmVPPStepCondition Class Reference
QuantLib::FdmVPPStepCondition Class Reference
#include <fdmvppstepcondition.hpp>
Public Member Functions
FdmVPPStepCondition (Real heatRate, Real pMin, Real pMax, Size tMinUp, Size tMinDown, Size nStarts, Real startUpFuel, Real startUpFixCost, Real carbonPrice, Size stateDirection, const boost::shared_ptr< FdmMesher > &mesher, const boost::shared_ptr< FdmInnerValueCalculator > &gasPrice, const boost::shared_ptr< FdmInnerValueCalculator > &sparkSpreadPrice)
Size nStates () const
void applyTo (Array &a, Time t) const
Private Member Functions
Real evolveAtPMin (Real sparkSpread) const
Real evolveAtPMax (Real sparkSpread) const
Real evolve (const FdmLinearOpIterator &iter, Time t) const
Disposable< Array > changeState (Real gasPrice, const Array &state, Time t) const
Private Attributes
const Real heatRate_
const Real pMin_
const Real pMax_
const Size tMinUp_
const Size tMinDown_
const Size nStarts_
const Real startUpFuel_
const Real startUpFixCost_
const Real carbonPrice_
const Size stateDirection_
const boost::shared_ptr
< FdmMesher > mesher_
const boost::shared_ptr
< FdmInnerValueCalculator > gasPrice_
const boost::shared_ptr
< FdmInnerValueCalculator > sparkSpreadPrice_
const Size nStates_
std::vector< boost::function
< Real(Real)> > stateEvolveFcts_
Detailed Description
Definition at line 38 of file fdmvppstepcondition.hpp.
Constructor & Destructor Documentation
QuantLib::FdmVPPStepCondition::FdmVPPStepCondition (Real heatRate, Real pMin, Real pMax, Size tMinUp, Size tMinDown, Size nStarts, Real startUpFuel, Real startUpFixCost, Real carbonPrice, Size stateDirection, const boost::shared_ptr< FdmMesher > & mesher, const boost::shared_ptr< FdmInnerValueCalculator > & gasPrice, const boost::shared_ptr< FdmInnerValueCalculator > & sparkSpreadPrice)
Definition at line 34 of file fdmvppstepcondition.cpp.
References evolveAtPMax(), evolveAtPMin(), mesher_, nStates_, QL_REQUIRE, stateDirection_, stateEvolveFcts_, tMinDown_, and tMinUp_.
    : heatRate_        (heatRate),
      pMin_            (pMin),
      pMax_            (pMax),
      tMinUp_          (tMinUp),
      tMinDown_        (tMinDown),
      nStarts_         (nStarts),
      startUpFuel_     (startUpFuel),
      startUpFixCost_  (startUpFixCost),
      carbonPrice_     (carbonPrice),
      stateDirection_  (stateDirection),
      mesher_          (mesher),
      gasPrice_        (gasPrice),
      sparkSpreadPrice_(sparkSpreadPrice),
      nStates_         ((2*tMinUp + tMinDown)
                          *((nStarts == Null<Size>()) ? 1 : nStarts+1)),
      stateEvolveFcts_ (nStates_) {
        QL_REQUIRE(tMinUp_ > 1,   "minimum up time must be greater than one");
        QL_REQUIRE(tMinDown_ > 1, "minimum down time must be greater than one");
        QL_REQUIRE(stateEvolveFcts_.size() ==
                   mesher_->layout()->dim()[stateDirection_],
                   "mesher does not fit to vpp arguments");
        for (Size i=0; i < nStates_; ++i) {
            const Size j = i % (2*tMinUp + tMinDown);
            if (j < tMinUp) {
                stateEvolveFcts_[i] = boost::function<Real (Real)>(
                    boost::bind(&FdmVPPStepCondition::evolveAtPMin,this, _1));
            }
            else if (j < 2*tMinUp){
                stateEvolveFcts_[i] = boost::function<Real (Real)>(
                    boost::bind(&FdmVPPStepCondition::evolveAtPMax,this, _1));
            }
        }
    }
Member Function Documentation
void QuantLib::FdmVPPStepCondition::applyTo (Array & a, Time t) const [virtual]
Implements QuantLib::StepCondition< Array >.
Definition at line 88 of file fdmvppstepcondition.cpp.
References changeState(), evolve(), gasPrice_, mesher_, nStates(), and stateDirection_.
Referenced by VPPTest::testVPPPricing().
{
        boost::shared_ptr<FdmLinearOpLayout> layout = mesher_->layout();
        const Size nStates = layout->dim()[stateDirection_];
        const FdmLinearOpIterator endIter = layout->end();
        for (FdmLinearOpIterator iter=layout->begin();iter != endIter; ++iter) {
            a[iter.index()] += evolve(iter, t);
        }
        for (FdmLinearOpIterator iter=layout->begin();iter != endIter; ++iter) {
            if (!iter.coordinates()[stateDirection_]) {
                Array x(nStates);
                for (Size i=0; i < nStates; ++i) {
                    x[i] = a[layout->neighbourhood(iter, stateDirection_, i)];
                }
                const Real gasPrice = gasPrice_->innerValue(iter, t);
                x = changeState(gasPrice, x, t);
                for (Size i=0; i < nStates; ++i) {
                    a[layout->neighbourhood(iter, stateDirection_, i)] = x[i];
                }
            }
        }
    }
Disposable< Array > QuantLib::FdmVPPStepCondition::changeState (Real gasPrice, const Array & state, Time t) const [private]
Definition at line 129 of file fdmvppstepcondition.cpp.
References carbonPrice_, QuantLib::Array::front(), nStarts_, QuantLib::Array::size(), startUpFixCost_, startUpFuel_, tMinDown_, and tMinUp_.
Referenced by applyTo().
{
        const Real startUpCost
                = startUpFixCost_ + (gasPrice + carbonPrice_)*startUpFuel_;
        Array retVal(state.size());
        const Size sss = 2*tMinUp_ + tMinDown_;
        const Size n = sss * (nStarts_ == Null<Size>() ? 1 : nStarts_+1);
        for (Size i=0; i < n; ++i) {
            const Size j = i % sss;
            if (j < tMinUp_-1) {
                retVal[i] = std::max(state[i+1], state[tMinUp_+i+1]);
            }
            else if (j == tMinUp_-1) {
                retVal[i] = std::max(state[i+tMinUp_+1],
                                     std::max(state[i], state[i+tMinUp_]));
            }
            else if (j < 2*tMinUp_) {
                retVal[i] = retVal[i-tMinUp_];
            }
            else if (j <  2*tMinUp_+tMinDown_-1) {
                retVal[i] = state[i+1];
            }
            else if (nStarts_ == Null<Size>()) {
                retVal[i] = std::max(state[i],
                    std::max(state.front(), state[tMinUp_]) - startUpCost);
            }
            else if (i >= sss) {
                retVal[i] = std::max(state[i],
                    std::max(state[i+1-2*sss], state[i+1-2*sss+tMinUp_])
                            - startUpCost);
            }
            else {
                retVal[i] = state[i];
            }
        }
        return retVal;
    }
Real QuantLib::FdmVPPStepCondition::evolve (const FdmLinearOpIterator & iter, Time t) const [private]
Definition at line 115 of file fdmvppstepcondition.cpp.
References QuantLib::FdmLinearOpIterator::coordinates(), sparkSpreadPrice_, stateDirection_, and stateEvolveFcts_.
Referenced by applyTo().
{
        const Size state = iter.coordinates()[stateDirection_];
        if (stateEvolveFcts_[state].empty()) {
            return 0.0;
        }
        else {
            const Real sparkSpread = sparkSpreadPrice_->innerValue(iter, t);
            return stateEvolveFcts_[state](sparkSpread);
        }
    }
Real QuantLib::FdmVPPStepCondition::evolveAtPMax (Real sparkSpread) const [private]
Definition at line 176 of file fdmvppstepcondition.cpp.
References carbonPrice_, heatRate_, and pMax_.
Referenced by FdmVPPStepCondition().
{
        return pMax_*(sparkSpread - heatRate_*carbonPrice_);
    }
Real QuantLib::FdmVPPStepCondition::evolveAtPMin (Real sparkSpread) const [private]
Definition at line 172 of file fdmvppstepcondition.cpp.
References carbonPrice_, heatRate_, and pMin_.
Referenced by FdmVPPStepCondition().
{
        return pMin_*(sparkSpread - heatRate_*carbonPrice_);
    }
Size QuantLib::FdmVPPStepCondition::nStates () const
Definition at line 83 of file fdmvppstepcondition.cpp.
References nStates_.
Referenced by applyTo().
{
        return nStates_;
    }
Member Data Documentation
const Real QuantLib::FdmVPPStepCondition::carbonPrice_ [private]
Definition at line 68 of file fdmvppstepcondition.hpp.
Referenced by changeState(), evolveAtPMax(), and evolveAtPMin().
const boost::shared_ptr<FdmInnerValueCalculator> QuantLib::FdmVPPStepCondition::gasPrice_ [private]
Definition at line 72 of file fdmvppstepcondition.hpp.
Referenced by applyTo().
const Real QuantLib::FdmVPPStepCondition::heatRate_ [private]
Definition at line 63 of file fdmvppstepcondition.hpp.
Referenced by evolveAtPMax(), and evolveAtPMin().
const boost::shared_ptr<FdmMesher> QuantLib::FdmVPPStepCondition::mesher_ [private]
Definition at line 71 of file fdmvppstepcondition.hpp.
Referenced by applyTo(), and FdmVPPStepCondition().
const Size QuantLib::FdmVPPStepCondition::nStarts_ [private]
Definition at line 66 of file fdmvppstepcondition.hpp.
Referenced by changeState().
const Size QuantLib::FdmVPPStepCondition::nStates_ [private]
Definition at line 75 of file fdmvppstepcondition.hpp.
Referenced by FdmVPPStepCondition(), and nStates().
const Real QuantLib::FdmVPPStepCondition::pMax_ [private]
Definition at line 64 of file fdmvppstepcondition.hpp.
Referenced by evolveAtPMax().
const Real QuantLib::FdmVPPStepCondition::pMin_ [private]
Definition at line 64 of file fdmvppstepcondition.hpp.
Referenced by evolveAtPMin().
const boost::shared_ptr<FdmInnerValueCalculator> QuantLib::FdmVPPStepCondition::sparkSpreadPrice_ [private]
Definition at line 73 of file fdmvppstepcondition.hpp.
Referenced by evolve().
const Real QuantLib::FdmVPPStepCondition::startUpFixCost_ [private]
Definition at line 67 of file fdmvppstepcondition.hpp.
Referenced by changeState().
const Real QuantLib::FdmVPPStepCondition::startUpFuel_ [private]
Definition at line 67 of file fdmvppstepcondition.hpp.
Referenced by changeState().
const Size QuantLib::FdmVPPStepCondition::stateDirection_ [private]
Definition at line 69 of file fdmvppstepcondition.hpp.
Referenced by applyTo(), evolve(), and FdmVPPStepCondition().
std::vector<boost::function<Real (Real)> > QuantLib::FdmVPPStepCondition::stateEvolveFcts_ [private]
Definition at line 76 of file fdmvppstepcondition.hpp.
Referenced by evolve(), and FdmVPPStepCondition().
const Size QuantLib::FdmVPPStepCondition::tMinDown_ [private]
Definition at line 65 of file fdmvppstepcondition.hpp.
Referenced by changeState(), and FdmVPPStepCondition().
const Size QuantLib::FdmVPPStepCondition::tMinUp_ [private]
Definition at line 65 of file fdmvppstepcondition.hpp.
Referenced by changeState(), and FdmVPPStepCondition().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/finitedifferences/fdmvppstepcondition.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/finitedifferences/fdmvppstepcondition.cpp