QuantLib: QuantLib::SphereCylinderOptimizer Class Reference
QuantLib::SphereCylinderOptimizer Class Reference
#include <spherecylinder.hpp>
Public Member Functions
SphereCylinderOptimizer (Real r, Real s, Real alpha, Real z1, Real z2, Real z3, Real zweight=1.0)
bool isIntersectionNonEmpty () const
void findClosest (Size maxIterations, Real tolerance, Real &y1, Real &y2, Real &y3) const
bool findByProjection (Real &y1, Real &y2, Real &y3) const
Private Member Functions
Real objectiveFunction (Real x2) const
Private Attributes
Real r_
Real s_
Real alpha_
Real z1_
Real z2_
Real z3_
Real topValue_
Real bottomValue_
bool nonEmpty_
Real zweight_
Detailed Description
we are in r^3 sphere centred at O radius r
vertical cylinder centred at (alpha,0) radius s
Z some point in R3
find point on intersection that is closest to Z
the intersection may be empty!
Definition at line 40 of file spherecylinder.hpp.
Constructor & Destructor Documentation
QuantLib::SphereCylinderOptimizer::SphereCylinderOptimizer (Real r, Real s, Real alpha, Real z1, Real z2, Real z3, Real zweight = 1.0)
Definition at line 75 of file spherecylinder.cpp.
References bottomValue_, nonEmpty_, QL_REQUIRE, and topValue_.
    : r_(r), s_(s), alpha_(alpha), z1_(z1), z2_(z2), z3_(z3), zweight_(zweight)
    {
        QL_REQUIRE(r>0,
                   "sphere must have positive radius");
        s = std::max(s,0.0);
         QL_REQUIRE(alpha>0,
                   "cylinder centre must have positive coordinate");
        if (std::fabs(alpha-s) > r )
            nonEmpty_=false;
        else
            nonEmpty_=true;
        Real cylinderInside = r*r - (s + alpha)*(s+alpha);
        if (cylinderInside >0.0)
        {
            topValue_ = alpha+s;
            bottomValue_ = alpha-s;
        }
        else
        {
            bottomValue_ = alpha-s;
            Real tmp = r*r - (s *s+alpha*alpha);
            if (  tmp <=0)
            { // max to left of maximimum
                Real topValue2 = std::sqrt(s*s - tmp*tmp/(4*alpha*alpha));
                topValue_ = alpha -std::sqrt(s*s - topValue2*topValue2);
            }
            else
            {
                topValue_ = alpha+ tmp/(2.0*alpha);
            }
        }
    }
Member Function Documentation
bool QuantLib::SphereCylinderOptimizer::findByProjection (Real & y1, Real & y2, Real & y3) const
Definition at line 165 of file spherecylinder.cpp.
References alpha_, isIntersectionNonEmpty(), r_, s_, topValue_, z1_, and z2_.
Referenced by findClosest(), QuantLib::sphereCylinderOptimizerClosest(), and MarketModelSmmCapletHomoCalibrationTest::testSphereCylinder().
{
        Real z1moved = z1_-alpha_;
        Real distance = std::sqrt( z1moved*z1moved + z2_*z2_);
        Real scale = s_/distance;
        Real y1moved = z1moved*scale;
        y1 = alpha_+ y1moved;
        y2 = scale*z2_;
        Real residual = r_*r_ - y1*y1 -y2*y2;
        if (residual >=0.0) {
            y3 = std::sqrt(residual);
            return true;
        }
        // we are outside the sphere
        if (!isIntersectionNonEmpty()) {
            y3=0.0;
            return false;
        }
       // intersection is non-empty but projection point is outside sphere
       // so take rightmost point
       y3 = 0.0;
       y1 = topValue_;
       y2 = std::sqrt(r_*r_ -y1*y1);
       return true;
    }
void QuantLib::SphereCylinderOptimizer::findClosest (Size maxIterations, Real tolerance, Real & y1, Real & y2, Real & y3) const
Definition at line 131 of file spherecylinder.cpp.
References alpha_, bottomValue_, QuantLib::anonymous_namespace{spherecylinder.cpp}::BrentMinimize(), findByProjection(), objectiveFunction(), r_, s_, topValue_, QuantLib::x1, QuantLib::x2, and QuantLib::x3.
Referenced by QuantLib::sphereCylinderOptimizerClosest(), and MarketModelSmmCapletHomoCalibrationTest::testSphereCylinder().
    {
         Real x1,x2,x3;
         findByProjection(x1,x2,x3);
         y1 = BrentMinimize(
                bottomValue_, x1, topValue_,tolerance, maxIterations,
                boost::bind(
                      &SphereCylinderOptimizer::objectiveFunction, this, _1));
         y2 =std::sqrt(s_*s_ - (y1-alpha_)*(y1-alpha_));
         y3= std::sqrt(r_*r_ - y1*y1-y2*y2);
    }
bool QuantLib::SphereCylinderOptimizer::isIntersectionNonEmpty () const
Definition at line 127 of file spherecylinder.cpp.
References nonEmpty_.
Referenced by findByProjection(), and QuantLib::sphereCylinderOptimizerClosest().
{
        return nonEmpty_;
    }
Real QuantLib::SphereCylinderOptimizer::objectiveFunction (Real x2) const [private]
Definition at line 148 of file spherecylinder.cpp.
References alpha_, r_, s_, QuantLib::x2, QuantLib::x3, z1_, z2_, z3_, and zweight_.
Referenced by findClosest().
    {
   //     Real x1 = alpha_ - std::sqrt(s_*s_-x2*x2);
        Real x2sq = s_*s_ - (x1-alpha_)*(x1-alpha_);
         // a negative number will be minuscule and a result of rounding error
        Real x2 = x2sq >= 0.0 ? std::sqrt(x2sq) : 0.0;
        Real x3= std::sqrt(r_*r_ - x1*x1-x2*x2);
        Real err=0.0;
        err+= (x1-z1_)*(x1-z1_);
        err+= (x2-z2_)*(x2-z2_);
        err+= (x3-z3_)*(x3-z3_)*zweight_;
        return err;
    }
Member Data Documentation
Real QuantLib::SphereCylinderOptimizer::alpha_ [private]
Definition at line 60 of file spherecylinder.hpp.
Referenced by findByProjection(), findClosest(), and objectiveFunction().
Real QuantLib::SphereCylinderOptimizer::bottomValue_ [private]
Definition at line 63 of file spherecylinder.hpp.
Referenced by findClosest(), and SphereCylinderOptimizer().
bool QuantLib::SphereCylinderOptimizer::nonEmpty_ [private]
Definition at line 64 of file spherecylinder.hpp.
Referenced by isIntersectionNonEmpty(), and SphereCylinderOptimizer().
Real QuantLib::SphereCylinderOptimizer::r_ [private]
Definition at line 60 of file spherecylinder.hpp.
Referenced by findByProjection(), findClosest(), and objectiveFunction().
Real QuantLib::SphereCylinderOptimizer::s_ [private]
Definition at line 60 of file spherecylinder.hpp.
Referenced by findByProjection(), findClosest(), and objectiveFunction().
Real QuantLib::SphereCylinderOptimizer::topValue_ [private]
Definition at line 62 of file spherecylinder.hpp.
Referenced by findByProjection(), findClosest(), and SphereCylinderOptimizer().
Real QuantLib::SphereCylinderOptimizer::z1_ [private]
Definition at line 60 of file spherecylinder.hpp.
Referenced by findByProjection(), and objectiveFunction().
Real QuantLib::SphereCylinderOptimizer::z2_ [private]
Definition at line 60 of file spherecylinder.hpp.
Referenced by findByProjection(), and objectiveFunction().
Real QuantLib::SphereCylinderOptimizer::z3_ [private]
Definition at line 60 of file spherecylinder.hpp.
Referenced by objectiveFunction().
Real QuantLib::SphereCylinderOptimizer::zweight_ [private]
Definition at line 65 of file spherecylinder.hpp.
Referenced by objectiveFunction().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/optimization/spherecylinder.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/math/optimization/spherecylinder.cpp