QuantLib: QuantLib::FdmHestonHullWhiteSolver Class Reference
QuantLib::FdmHestonHullWhiteSolver Class Reference
#include <fdmhestonhullwhitesolver.hpp>
Public Member Functions
FdmHestonHullWhiteSolver (const Handle< HestonProcess > &hestonProcess, const Handle< HullWhiteProcess > &hwProcess, Rate corrEquityShortRate, const FdmSolverDesc &solverDesc, const FdmSchemeDesc &schemeDesc=FdmSchemeDesc::Hundsdorfer())
Real valueAt (Real s, Real v, Rate r) const
Real thetaAt (Real s, Real v, Rate r) const
Real deltaAt (Real s, Real v, Rate r, Real eps) const
Real gammaAt (Real s, Real v, Rate r, Real eps) const
Protected Member Functions
void performCalculations () const
Private Attributes
const Handle< HestonProcess > hestonProcess_
const Handle< HullWhiteProcess > hwProcess_
const Real corrEquityShortRate_
const FdmSolverDesc solverDesc_
const FdmSchemeDesc schemeDesc_
boost::shared_ptr< Fdm3DimSolver > solver_
Detailed Description
Definition at line 39 of file fdmhestonhullwhitesolver.hpp.
Constructor & Destructor Documentation
QuantLib::FdmHestonHullWhiteSolver::FdmHestonHullWhiteSolver (const Handle< HestonProcess > & hestonProcess, const Handle< HullWhiteProcess > & hwProcess, Rate corrEquityShortRate, const FdmSolverDesc & solverDesc, const FdmSchemeDesc & schemeDesc = FdmSchemeDesc::Hundsdorfer())
Definition at line 27 of file fdmhestonhullwhitesolver.cpp.
References QuantLib::Observer::registerWith().
    : hestonProcess_(hestonProcess),
      hwProcess_(hwProcess),
      corrEquityShortRate_(corrEquityShortRate),
      solverDesc_(solverDesc),
      schemeDesc_(schemeDesc) {
        registerWith(hestonProcess);
        registerWith(hwProcess);
    }
Member Function Documentation
Real QuantLib::FdmHestonHullWhiteSolver::deltaAt (Real s, Real v, Rate r, Real eps) const
Definition at line 61 of file fdmhestonhullwhitesolver.cpp.
References valueAt().
          {
        return (valueAt(s+eps, v, r) - valueAt(s-eps, v, r))/(2*eps);
    }
Real QuantLib::FdmHestonHullWhiteSolver::gammaAt (Real s, Real v, Rate r, Real eps) const
Definition at line 66 of file fdmhestonhullwhitesolver.cpp.
References valueAt().
          {
        return (valueAt(s+eps, v, r)+valueAt(s-eps, v,r )
                -2*valueAt(s, v, r))/(eps*eps);
    }
void QuantLib::FdmHestonHullWhiteSolver::performCalculations () const [protected, virtual]
This method must implement any calculations which must be (re)done in order to calculate the desired results.
Implements QuantLib::LazyObject.
Definition at line 43 of file fdmhestonhullwhitesolver.cpp.
References corrEquityShortRate_, QuantLib::Handle< T >::currentLink(), hestonProcess_, hwProcess_, QuantLib::FdmSolverDesc::mesher, schemeDesc_, solver_, and solverDesc_.
{
        const boost::shared_ptr<FdmLinearOpComposite> op(
            new FdmHestonHullWhiteOp(solverDesc_.mesher,
                                     hestonProcess_.currentLink(),
                                     hwProcess_.currentLink(),
                                     corrEquityShortRate_));
        solver_ = boost::shared_ptr<Fdm3DimSolver>(
                                new Fdm3DimSolver(solverDesc_, schemeDesc_, op));
    }
Real QuantLib::FdmHestonHullWhiteSolver::thetaAt (Real s, Real v, Rate r) const
Definition at line 72 of file fdmhestonhullwhitesolver.cpp.
References QuantLib::LazyObject::calculate(), and solver_.
{
        calculate();
        const Real x = std::log(s);
        return solver_->thetaAt(x, v, r);
    }
Real QuantLib::FdmHestonHullWhiteSolver::valueAt (Real s, Real v, Rate r) const
Definition at line 54 of file fdmhestonhullwhitesolver.cpp.
References QuantLib::LazyObject::calculate(), and solver_.
Referenced by deltaAt(), and gammaAt().
{
        calculate();
        const Real x = std::log(s);
        return solver_->interpolateAt(x, v, r);
    }
Member Data Documentation
const Real QuantLib::FdmHestonHullWhiteSolver::corrEquityShortRate_ [private]
Definition at line 65 of file fdmhestonhullwhitesolver.hpp.
Referenced by performCalculations().
const Handle<HestonProcess> QuantLib::FdmHestonHullWhiteSolver::hestonProcess_ [private]
Definition at line 63 of file fdmhestonhullwhitesolver.hpp.
Referenced by performCalculations().
const Handle<HullWhiteProcess> QuantLib::FdmHestonHullWhiteSolver::hwProcess_ [private]
Definition at line 64 of file fdmhestonhullwhitesolver.hpp.
Referenced by performCalculations().
const FdmSchemeDesc QuantLib::FdmHestonHullWhiteSolver::schemeDesc_ [private]
Definition at line 68 of file fdmhestonhullwhitesolver.hpp.
Referenced by performCalculations().
boost::shared_ptr<Fdm3DimSolver> QuantLib::FdmHestonHullWhiteSolver::solver_ [mutable, private]
Definition at line 70 of file fdmhestonhullwhitesolver.hpp.
Referenced by performCalculations(), thetaAt(), and valueAt().
const FdmSolverDesc QuantLib::FdmHestonHullWhiteSolver::solverDesc_ [private]
Definition at line 67 of file fdmhestonhullwhitesolver.hpp.
Referenced by performCalculations().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/solvers/fdmhestonhullwhitesolver.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/solvers/fdmhestonhullwhitesolver.cpp