QuantLib: QuantLib::SwapForwardMappings Class Reference
QuantLib::SwapForwardMappings Class Reference
#include <swapforwardmappings.hpp>
Static Public Member Functions
static Real annuity (const CurveState &cs, Size startIndex, Size endIndex, Size numeraireIndex)
compute annuity of arbitrary swap-rate
static Real swapDerivative (const CurveState &cs, Size startIndex, Size endIndex, Size forwardIndex)
compute derivative of swap-rate to underlying forward rate
static Disposable< Matrix > coterminalSwapForwardJacobian (const CurveState &cs)
static Disposable< Matrix > coterminalSwapZedMatrix (const CurveState &cs, const Spread displacement)
static Disposable< Matrix > coinitialSwapForwardJacobian (const CurveState &cs)
static Disposable< Matrix > coinitialSwapZedMatrix (const CurveState &cs, const Spread displacement)
static Disposable< Matrix > cmSwapForwardJacobian (const CurveState &cs, const Size spanningForwards)
static Disposable< Matrix > cmSwapZedMatrix (const CurveState &cs, const Size spanningForwards, const Spread displacement)
static Real swaptionImpliedVolatility (const MarketModel &volStructure, Size startIndex, Size endIndex)
Detailed Description
Definition at line 35 of file swapforwardmappings.hpp.
Member Function Documentation
Real QuantLib::SwapForwardMappings::annuity (const CurveState & cs, Size startIndex, Size endIndex, Size numeraireIndex) [static]
compute annuity of arbitrary swap-rate
Definition at line 33 of file swapforwardmappings.cpp.
References QuantLib::CurveState::discountRatio(), and QuantLib::CurveState::rateTaus().
Referenced by swapDerivative().
    {
        Real annuity = 0.0;
        for (Size i=startIndex; i<endIndex; ++i)
            annuity += cs.rateTaus()[i]*cs.discountRatio(i+1, numeraireIndex);
        return annuity;
    }
Disposable< Matrix > QuantLib::SwapForwardMappings::cmSwapForwardJacobian (const CurveState & cs, const Size spanningForwards) [static]
Returns the dsr[i]/df[j] jacobian between constant maturity swap rates and forward rates
Definition at line 131 of file swapforwardmappings.cpp.
References QuantLib::CurveState::numberOfRates(), and swapDerivative().
Referenced by cmSwapZedMatrix(), and SwapForwardMappingsTest::testForwardSwapJacobians().
    {
        Size n = cs.numberOfRates();
        Matrix jacobian = Matrix(n, n, 0.0);
        for (Size i=0; i<n; ++i)      // i = swap rate index
            for (Size j=0; j<n; ++j)  // j = forward rate index
                jacobian[i][j] =swapDerivative(cs, i, std::min(n,i+spanningForwards), j);
        return jacobian;
    }
Disposable< Matrix > QuantLib::SwapForwardMappings::cmSwapZedMatrix (const CurveState & cs, const Size spanningForwards, const Spread displacement) [static]
Returns the Z matrix to switch base from forward to constant maturity swap rates
Definition at line 163 of file swapforwardmappings.cpp.
References cmSwapForwardJacobian(), QuantLib::CurveState::cmSwapRate(), anonymous_namespace{marketmodel.cpp}::displacement, anonymous_namespace{interpolations.cpp}::f(), QuantLib::CurveState::forwardRates(), and QuantLib::CurveState::numberOfRates().
Referenced by swaptionImpliedVolatility().
    {
        Size n = cs.numberOfRates();
        Matrix zMatrix = cmSwapForwardJacobian(cs,spanningForwards);
        const std::vector<Rate>& f = cs.forwardRates();
        std::vector<Rate> sr(n);
        for (Size i=0; i<n; ++i)
            sr[i] = cs.cmSwapRate(i,spanningForwards);
        for (Size i=0; i<n; ++i)
            for (Size j=i; j<n; ++j)
                zMatrix[i][j] *= (f[j]+displacement)/(sr[i]+displacement);
        return zMatrix;
    }
Disposable< Matrix > QuantLib::SwapForwardMappings::coinitialSwapForwardJacobian (const CurveState & cs) [static]
Returns the dsr[i]/df[j] jacobian between coinitial swap rates and forward rates
Definition at line 118 of file swapforwardmappings.cpp.
References QuantLib::CurveState::numberOfRates(), and swapDerivative().
Referenced by coinitialSwapZedMatrix(), and SwapForwardMappingsTest::testForwardSwapJacobians().
    {
        Size n = cs.numberOfRates();
        Matrix jacobian = Matrix(n, n, 0.0);
        for (Size i=0; i<n; ++i)      // i = swap rate index
            for (Size j=0; j<n; ++j)  // j = forward rate index
                jacobian[i][j] =swapDerivative(cs, 0, i+1, j);
        return jacobian;
    }
Disposable< Matrix > QuantLib::SwapForwardMappings::coinitialSwapZedMatrix (const CurveState & cs, const Spread displacement) [static]
Returns the Z matrix to switch base from forward to coinitial swap rates
Definition at line 145 of file swapforwardmappings.cpp.
References QuantLib::CurveState::cmSwapRate(), coinitialSwapForwardJacobian(), anonymous_namespace{marketmodel.cpp}::displacement, anonymous_namespace{interpolations.cpp}::f(), QuantLib::CurveState::forwardRates(), and QuantLib::CurveState::numberOfRates().
    {
        Size n = cs.numberOfRates();
        Matrix zMatrix = coinitialSwapForwardJacobian(cs);
        const std::vector<Rate>& f = cs.forwardRates();
        std::vector<Rate> sr(n);
        for (Size i=0; i<n; ++i)
            sr[i] = cs.cmSwapRate(0,i+1);
        for (Size i=0; i<n; ++i)
            for (Size j=i; j<n; ++j)
                zMatrix[i][j] *= (f[j]+displacement)/(sr[i]+displacement);
        return zMatrix;
    }
Disposable< Matrix > QuantLib::SwapForwardMappings::coterminalSwapForwardJacobian (const CurveState & cs) [static]
Returns the dsr[i]/df[j] jacobian between coterminal swap rates and forward rates
Definition at line 73 of file swapforwardmappings.cpp.
References anonymous_namespace{marketmodel.cpp}::a, QuantLib::CurveState::coterminalSwapAnnuity(), QuantLib::CurveState::discountRatio(), anonymous_namespace{interpolations.cpp}::f(), QuantLib::CurveState::forwardRates(), QuantLib::CurveState::numberOfRates(), and QuantLib::CurveState::rateTaus().
Referenced by coterminalSwapZedMatrix().
    {
        Size n = cs.numberOfRates();
        const std::vector<Rate>& f = cs.forwardRates();
        const std::vector<Time>& tau = cs.rateTaus();
        // coterminal floating leg values
        std::vector<Real> a(n);
        for (Size k=0; k<n; ++k)
            a[k] = cs.discountRatio(k,n)-1.0;
        //p[k]-p[n];
        Matrix jacobian = Matrix(n, n, 0.0);
        for (Size i=0; i<n; ++i) {     // i = swap rate index
            for (Size j=i; j<n; ++j) { // j = forward rate index
                Real bi = cs.coterminalSwapAnnuity(n,i);
                Real bj = cs.coterminalSwapAnnuity(n,j);
                jacobian[i][j] =
                    //   p[j+1]*tau[j]/b[i] +
                    tau[j]/cs.coterminalSwapAnnuity(j+1,i) +
                    // tau[j]/(1.0+f[j]*tau[j]) *
                    tau[j]/(1.0+f[j]*tau[j]) *
                    //    (-a[j]*b[i]+a[i]*b[j])/(b[i]*b[i]);
                    (-a[j]*bi+a[i]*bj)/(bi*bi);
            }
        }
        return jacobian;
    }
Disposable< Matrix > QuantLib::SwapForwardMappings::coterminalSwapZedMatrix (const CurveState & cs, const Spread displacement) [static]
Returns the Z matrix to switch base from forward to coterminal swap rates
Definition at line 104 of file swapforwardmappings.cpp.
References coterminalSwapForwardJacobian(), QuantLib::CurveState::coterminalSwapRates(), anonymous_namespace{marketmodel.cpp}::displacement, anonymous_namespace{interpolations.cpp}::f(), QuantLib::CurveState::forwardRates(), and QuantLib::CurveState::numberOfRates().
Referenced by addCoterminalSwapsAndSwaptions(), QuantLib::CTSMMCapletOriginalCalibration::calibrationFunction(), QuantLib::CTSMMCapletAlphaFormCalibration::capletAlphaFormCalibration(), QuantLib::CTSMMCapletMaxHomogeneityCalibration::capletMaxHomogeneityCalibration(), QuantLib::CotSwapFromFwdCorrelation::CotSwapFromFwdCorrelation(), QuantLib::CotSwapToFwdAdapter::CotSwapToFwdAdapter(), QuantLib::FwdToCotSwapAdapter::FwdToCotSwapAdapter(), QuantLib::SwaptionPseudoDerivative::SwaptionPseudoDerivative(), SwapForwardMappingsTest::testForwardCoterminalMappings(), and SwapForwardMappingsTest::testSwaptionImpliedVolatility().
{
            Size n = cs.numberOfRates();
            Matrix zMatrix = coterminalSwapForwardJacobian(cs);
            const std::vector<Rate>& f = cs.forwardRates();
            const std::vector<Rate>& sr = cs.coterminalSwapRates();
            for (Size i=0; i<n; ++i)
                for (Size j=i; j<n; ++j)
                    zMatrix[i][j] *= (f[j]+displacement)/(sr[i]+displacement);
            return zMatrix;
    }
Real QuantLib::SwapForwardMappings::swapDerivative (const CurveState & cs, Size startIndex, Size endIndex, Size forwardIndex) [static]
compute derivative of swap-rate to underlying forward rate
Definition at line 45 of file swapforwardmappings.cpp.
References annuity(), QuantLib::CurveState::discountRatio(), QuantLib::CurveState::forwardRate(), and QuantLib::CurveState::rateTaus().
Referenced by cmSwapForwardJacobian(), and coinitialSwapForwardJacobian().
    {
        if (forwardIndex < startIndex)
            return 0.0;
        if (forwardIndex >= endIndex)
            return 0.0;
        Real numerator = cs.discountRatio(startIndex, endIndex)-1;
        Real swapAnnuity = annuity(cs, startIndex, endIndex,endIndex);
        Real ratio = cs.rateTaus()[forwardIndex] /
            (1 + cs.rateTaus()[forwardIndex] * cs.forwardRate(forwardIndex));
        Real part1 = ratio*(numerator+1)/swapAnnuity;
        Real part2 = numerator/(swapAnnuity*swapAnnuity);
        if (forwardIndex >=1)
            part2 *= ratio* annuity(cs, startIndex, forwardIndex, endIndex);
        else
            part2 = 0.0;
        return part1-part2;
    }
Real QuantLib::SwapForwardMappings::swaptionImpliedVolatility (const MarketModel & volStructure, Size startIndex, Size endIndex) [static]
computes the implied vol of a swaption specified by two indices using the freezing coefficients methdodology. This routine is easy to use but not very efficient and if you want to do a lot of cases, then a different approach should be used.
Tested in SwapForwardMappingsTest::testSwaptionImpliedVolatility() in swapforwardmappings.cpp
Definition at line 182 of file swapforwardmappings.cpp.
References cmSwapZedMatrix(), anonymous_namespace{marketmodel.cpp}::displacement, QuantLib::MarketModel::displacements(), QuantLib::MarketModel::evolution(), anonymous_namespace{interpolations.cpp}::f(), QuantLib::MarketModel::initialRates(), QuantLib::MarketModel::numberOfFactors(), QuantLib::MarketModel::pseudoRoot(), QL_REQUIRE, QuantLib::EvolutionDescription::rateTimes(), and QuantLib::LMMCurveState::setOnForwardRates().
Referenced by MarketModelTest::testPathwiseMarketVegas(), MarketModelTest::testPathwiseVegas(), and SwapForwardMappingsTest::testSwaptionImpliedVolatility().
      {
          QL_REQUIRE(startIndex < endIndex, "start index must be before end index in swaptionImpliedVolatility");
          LMMCurveState cs(volStructure.evolution().rateTimes());
          cs.setOnForwardRates(volStructure.initialRates());
          Real displacement = volStructure.displacements()[0];
          Matrix cmsZed(cmSwapZedMatrix(cs, endIndex-startIndex,displacement));
          Real variance=0.0;
          Size index=0;
          const EvolutionDescription& evolution(volStructure.evolution());
          Size factors = volStructure.numberOfFactors();
          while (index < evolution.numberOfSteps() && startIndex >= evolution.firstAliveRate()[index] )
          {
              const Matrix& thisPseudo = volStructure.pseudoRoot(index);
              Real thisVariance =0.0;
              for (Size f=0; f < factors; ++f)
              {
                  Real sum=0.0;
                  for (Size j=startIndex; j < endIndex;++j)
                  {
                      sum += cmsZed[startIndex][j]*thisPseudo[j][f];
                  }
                  thisVariance += sum*sum;
              }
              variance += thisVariance;
              ++index;
          }
          Real expiry = evolution.rateTimes()[startIndex];
          return std::sqrt(variance/expiry);
      }
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/swapforwardmappings.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/swapforwardmappings.cpp