QuantLib: QuantLib::SABRInterpolation Class Reference
QuantLib::SABRInterpolation Class Reference
SABR smile interpolation between discrete volatility points.
#include <sabrinterpolation.hpp>
Public Member Functions
template<class I1 , class I2 >
SABRInterpolation (const I1 &xBegin, const I1 &xEnd, const I2 &yBegin, Time t, const Real &forward, Real alpha, Real beta, Real nu, Real rho, bool alphaIsFixed, bool betaIsFixed, bool nuIsFixed, bool rhoIsFixed, bool vegaWeighted=true, const boost::shared_ptr< EndCriteria > &endCriteria=boost::shared_ptr< EndCriteria >(), const boost::shared_ptr< OptimizationMethod > &optMethod=boost::shared_ptr< OptimizationMethod >())
Real expiry () const
Real forward () const
Real alpha () const
Real beta () const
Real nu () const
Real rho () const
Real rmsError () const
Real maxError () const
const std::vector< Real > & interpolationWeights () const
EndCriteria::Type endCriteria ()
Private Attributes
boost::shared_ptr
< detail::SABRCoeffHolder > coeffs_
Detailed Description
SABR smile interpolation between discrete volatility points.
Definition at line 341 of file sabrinterpolation.hpp.
Constructor & Destructor Documentation
template<class I1 , class I2 > QuantLib::SABRInterpolation::SABRInterpolation (const I1 & xBegin, const I1 & xEnd, const I2 & yBegin, Time t, const Real & forward, Real alpha, Real beta, Real nu, Real rho, bool alphaIsFixed, bool betaIsFixed, bool nuIsFixed, bool rhoIsFixed, bool vegaWeighted = true, const boost::shared_ptr< EndCriteria > & endCriteria = boost::shared_ptr<EndCriteria>(), const boost::shared_ptr< OptimizationMethod > & optMethod = boost::shared_ptr<OptimizationMethod>()) [inline]
Definition at line 344 of file sabrinterpolation.hpp.
References alpha(), beta(), coeffs_, endCriteria(), forward(), QuantLib::Interpolation::impl_, nu(), rho(), and anonymous_namespace{quantlibbenchmark.cpp}::t.
{
            impl_ = boost::shared_ptr<Interpolation::Impl>(new
                detail::SABRInterpolationImpl<I1,I2>(xBegin, xEnd, yBegin,
                                                     t, forward,
                                                     alpha, beta, nu, rho,
                                                     alphaIsFixed, betaIsFixed,
                                                     nuIsFixed, rhoIsFixed,
                                                     vegaWeighted,
                                                     endCriteria,
                                                     optMethod));
            coeffs_ =
                boost::dynamic_pointer_cast<detail::SABRCoeffHolder>(
                                                                       impl_);
        }
Member Function Documentation
Real QuantLib::SABRInterpolation::alpha () const [inline]
Definition at line 378 of file sabrinterpolation.hpp.
References coeffs_.
Referenced by SABRInterpolation().
{ return coeffs_->alpha_; }
Real QuantLib::SABRInterpolation::beta () const [inline]
Definition at line 379 of file sabrinterpolation.hpp.
References coeffs_.
Referenced by SABRInterpolation().
{ return coeffs_->beta_; }
EndCriteria::Type QuantLib::SABRInterpolation::endCriteria () [inline]
Definition at line 386 of file sabrinterpolation.hpp.
References coeffs_.
Referenced by SABRInterpolation().
{ return coeffs_->SABREndCriteria_; }
Real QuantLib::SABRInterpolation::expiry () const [inline]
Definition at line 376 of file sabrinterpolation.hpp.
References coeffs_.
{ return coeffs_->t_; }
Real QuantLib::SABRInterpolation::forward () const [inline]
Definition at line 377 of file sabrinterpolation.hpp.
References coeffs_.
Referenced by SABRInterpolation().
{ return coeffs_->forward_; }
const std::vector<Real>& QuantLib::SABRInterpolation::interpolationWeights () const [inline]
Definition at line 384 of file sabrinterpolation.hpp.
References coeffs_.
{
            return coeffs_->weights_; }
Real QuantLib::SABRInterpolation::maxError () const [inline]
Definition at line 383 of file sabrinterpolation.hpp.
References coeffs_.
{ return coeffs_->maxError_; }
Real QuantLib::SABRInterpolation::nu () const [inline]
Definition at line 380 of file sabrinterpolation.hpp.
References coeffs_.
Referenced by SABRInterpolation().
{ return coeffs_->nu_; }
Real QuantLib::SABRInterpolation::rho () const [inline]
Definition at line 381 of file sabrinterpolation.hpp.
References coeffs_.
Referenced by SABRInterpolation().
{ return coeffs_->rho_; }
Real QuantLib::SABRInterpolation::rmsError () const [inline]
Definition at line 382 of file sabrinterpolation.hpp.
References coeffs_.
{ return coeffs_->error_; }
Member Data Documentation
boost::shared_ptr<detail::SABRCoeffHolder> QuantLib::SABRInterpolation::coeffs_ [private]
Definition at line 389 of file sabrinterpolation.hpp.
Referenced by alpha(), beta(), endCriteria(), expiry(), forward(), interpolationWeights(), maxError(), nu(), rho(), rmsError(), and SABRInterpolation().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/interpolations/sabrinterpolation.hpp