QuantLib: QuantLib::Bond Class Reference
QuantLib::Bond Class Reference
Base bond class.
#include <bond.hpp>
Classes
class arguments
class engine
class results
Public Member Functions
Bond (Natural settlementDays, const Calendar &calendar, const Date &issueDate=Date(), const Leg &coupons=Leg())
constructor for amortizing or non-amortizing bonds.
Bond (Natural settlementDays, const Calendar &calendar, Real faceAmount, const Date &maturityDate, const Date &issueDate=Date(), const Leg &cashflows=Leg())
old constructor for non amortizing bonds.
virtual Rate nextCouponRate (Date d=Date()) const
Rate previousCouponRate (Date d=Date()) const
Previous coupon already paid at a given date.
Date nextCashFlowDate (Date d=Date()) const
Date previousCashFlowDate (Date d=Date()) const
Instrument interface
bool isExpired () const
returns whether the instrument might have value greater than zero.
Inspectors
Natural settlementDays () const
const Calendar & calendar () const
const std::vector< Real > & notionals () const
virtual Real notional (Date d=Date()) const
const Leg & cashflows () const
const Leg & redemptions () const
const boost::shared_ptr
< CashFlow > & redemption () const
Date startDate () const
Date maturityDate () const
Date issueDate () const
bool isTradable (Date d=Date()) const
Date settlementDate (Date d=Date()) const
Calculations
Real cleanPrice () const
theoretical clean price
Real dirtyPrice () const
theoretical dirty price
Real settlementValue () const
theoretical settlement value
Rate yield (const DayCounter &dc, Compounding comp, Frequency freq, Real accuracy=1.0e-8, Size maxEvaluations=100) const
theoretical bond yield
Real cleanPrice (Rate yield, const DayCounter &dc, Compounding comp, Frequency freq, Date settlementDate=Date()) const
clean price given a yield and settlement date
Real dirtyPrice (Rate yield, const DayCounter &dc, Compounding comp, Frequency freq, Date settlementDate=Date()) const
dirty price given a yield and settlement date
Real settlementValue (Real cleanPrice) const
settlement value as a function of the clean price
Rate yield (Real cleanPrice, const DayCounter &dc, Compounding comp, Frequency freq, Date settlementDate=Date(), Real accuracy=1.0e-8, Size maxEvaluations=100) const
yield given a (clean) price and settlement date
virtual Real accruedAmount (Date d=Date()) const
accrued amount at a given date
Protected Member Functions
void setupExpired () const
void setupArguments (PricingEngine::arguments *) const
void fetchResults (const PricingEngine::results *) const
void addRedemptionsToCashflows (const std::vector< Real > &redemptions=std::vector< Real >())
void setSingleRedemption (Real notional, Real redemption, const Date &date)
void setSingleRedemption (Real notional, const boost::shared_ptr< CashFlow > &redemption)
void calculateNotionalsFromCashflows ()
Protected Attributes
Natural settlementDays_
Calendar calendar_
std::vector< Date > notionalSchedule_
std::vector< Real > notionals_
Leg cashflows_
Leg redemptions_
Date maturityDate_
Date issueDate_
Real settlementValue_
Detailed Description
Base bond class.
Derived classes must fill the uninitialized data members.
Warning:
Most methods assume that the cash flows are stored sorted by date, the redemption(s) being after any cash flow at the same date. In particular, if there's one single redemption, it must be the last cash flow,
Test:
price/yield calculations are cross-checked for consistency.
price/yield calculations are checked against known good values.
Definition at line 59 of file bond.hpp.
Constructor & Destructor Documentation
QuantLib::Bond::Bond (Natural settlementDays, const Calendar & calendar, const Date & issueDate = Date(), const Leg & coupons = Leg())
constructor for amortizing or non-amortizing bonds.
Redemptions and maturity are calculated from the coupon data, if available. Therefore, redemptions must not be included in the passed cash flows.
Definition at line 38 of file bond.cpp.
References addRedemptionsToCashflows(), cashflows_, QuantLib::Singleton< Settings >::instance(), issueDate_, maturityDate_, QL_REQUIRE, and QuantLib::Observer::registerWith().
    : settlementDays_(settlementDays), calendar_(calendar),
      cashflows_(coupons), issueDate_(issueDate) {
        if (!coupons.empty()) {
            std::sort(cashflows_.begin(), cashflows_.end(),
                      earlier_than<boost::shared_ptr<CashFlow> >());
            if (issueDate_ != Date()) {
                QL_REQUIRE(issueDate_<cashflows_[0]->date(),
                           "issue date (" << issueDate_ <<
                           ") must be earlier than first payment date (" <<
                           cashflows_[0]->date() << ")");
            }
            maturityDate_ = coupons.back()->date();
            addRedemptionsToCashflows();
        }
        registerWith(Settings::instance().evaluationDate());
    }
QuantLib::Bond::Bond (Natural settlementDays, const Calendar & calendar, Real faceAmount, const Date & maturityDate, const Date & issueDate = Date(), const Leg & cashflows = Leg())
old constructor for non amortizing bonds.
Warning:
The last passed cash flow must be the bond redemption. No other cash flow can have a date later than the redemption date.
Definition at line 64 of file bond.cpp.
References cashflows_, QuantLib::Singleton< Settings >::instance(), issueDate_, maturityDate(), maturityDate_, notionals_, notionalSchedule_, QL_REQUIRE, redemptions_, and QuantLib::Observer::registerWith().
    : settlementDays_(settlementDays), calendar_(calendar),
      cashflows_(cashflows), maturityDate_(maturityDate),
      issueDate_(issueDate) {
        if (!cashflows.empty()) {
            std::sort(cashflows_.begin(), cashflows_.end()-1,
                      earlier_than<boost::shared_ptr<CashFlow> >());
            if (maturityDate_ == Date())
                maturityDate_ = CashFlows::maturityDate(cashflows);
            if (issueDate_ != Date()) {
                QL_REQUIRE(issueDate_<cashflows_[0]->date(),
                           "issue date (" << issueDate_ <<
                           ") must be earlier than first payment date (" <<
                           cashflows_[0]->date() << ")");
            }
            notionals_.resize(2);
            notionalSchedule_.resize(2);
            notionalSchedule_[0] = Date();
            notionals_[0] = faceAmount;
            notionalSchedule_[1] = maturityDate_;
            notionals_[1] = 0.0;
            redemptions_.push_back(cashflows.back());
        }
        registerWith(Settings::instance().evaluationDate());
    }
Member Function Documentation
Real QuantLib::Bond::accruedAmount (Date d = Date()) const [virtual]
accrued amount at a given date
The default bond settlement is used if no date is given.
Definition at line 251 of file bond.cpp.
References notional().
Referenced by QuantLib::BondFunctions::atmRate(), QuantLib::BondFunctions::cleanPrice(), cleanPrice(), dirtyPrice(), settlementValue(), BondTest::testBrazilianCached(), QuantLib::BondFunctions::yield(), and QuantLib::BondFunctions::zSpread().
{
        Real currentNotional = notional(settlement);
        if (currentNotional == 0.0)
            return 0.0;
        return BondFunctions::accruedAmount(*this, settlement);
    }
void QuantLib::Bond::addRedemptionsToCashflows (const std::vector< Real > & redemptions = std::vector<Real>()) [protected]
This method can be called by derived classes in order to build redemption payments from the existing cash flows. It must be called after setting up the cashflows_ vector and will fill the notionalSchedule_, notionals_, and redemptions_ data members.
If given, the elements of the redemptions vector will multiply the amount of the redemption cash flow. The elements will be taken in base 100, i.e., a redemption equal to 100 does not modify the amount.
Precondition:
The cashflows_ vector must contain at least one coupon and must be sorted by date.
Definition at line 300 of file bond.cpp.
References calculateNotionalsFromCashflows(), cashflows_, notionals_, notionalSchedule_, and redemptions_.
Referenced by QuantLib::AmortizingCmsRateBond::AmortizingCmsRateBond(), QuantLib::AmortizingFixedRateBond::AmortizingFixedRateBond(), QuantLib::AmortizingFloatingRateBond::AmortizingFloatingRateBond(), Bond(), QuantLib::CallableFixedRateBond::CallableFixedRateBond(), QuantLib::CmsRateBond::CmsRateBond(), QuantLib::ConvertibleFixedCouponBond::ConvertibleFixedCouponBond(), QuantLib::ConvertibleFloatingRateBond::ConvertibleFloatingRateBond(), QuantLib::FixedRateBond::FixedRateBond(), and QuantLib::FloatingRateBond::FloatingRateBond().
{
        // First, we gather the notional information from the cashflows
        calculateNotionalsFromCashflows();
        // Then, we create the redemptions based on the notional
        // information and we add them to the cashflows vector after
        // the coupons.
        redemptions_.clear();
        for (Size i=1; i<notionalSchedule_.size(); ++i) {
            Real R = i < redemptions.size() ? redemptions[i] :
                     !redemptions.empty()   ? redemptions.back() :
                                              100.0;
            Real amount = (R/100.0)*(notionals_[i-1]-notionals_[i]);
            boost::shared_ptr<CashFlow> payment;
            if (i < notionalSchedule_.size()-1)
                payment.reset(new AmortizingPayment(amount,
                                                    notionalSchedule_[i]));
            else
                payment.reset(new Redemption(amount, notionalSchedule_[i]));
            cashflows_.push_back(payment);
            redemptions_.push_back(payment);
        }
        // stable_sort now moves the redemptions to the right places
        // while ensuring that they follow coupons with the same date.
        std::stable_sort(cashflows_.begin(), cashflows_.end(),
                         earlier_than<boost::shared_ptr<CashFlow> >());
    }
void QuantLib::Bond::calculateNotionalsFromCashflows () [protected]
used internally to collect notional information from the coupons. It should not be called by derived classes.
Definition at line 353 of file bond.cpp.
References cashflows_, QuantLib::close(), notional(), notionals_, notionalSchedule_, and QL_REQUIRE.
Referenced by addRedemptionsToCashflows().
{
        notionalSchedule_.clear();
        notionals_.clear();
        Date lastPaymentDate = Date();
        notionalSchedule_.push_back(Date());
        for (Size i=0; i<cashflows_.size(); ++i) {
            boost::shared_ptr<Coupon> coupon =
                boost::dynamic_pointer_cast<Coupon>(cashflows_[i]);
            if (!coupon)
                continue;
            Real notional = coupon->nominal();
            // we add the notional only if it is the first one...
            if (notionals_.empty()) {
                notionals_.push_back(coupon->nominal());
                lastPaymentDate = coupon->date();
            } else if (!close(notional, notionals_.back())) {
                // ...or if it has changed.
                QL_REQUIRE(notional < notionals_.back(),
                           "increasing coupon notionals");
                notionals_.push_back(coupon->nominal());
                // in this case, we also add the last valid date for
                // the previous one...
                notionalSchedule_.push_back(lastPaymentDate);
                // ...and store the candidate for this one.
                lastPaymentDate = coupon->date();
            } else {
                // otherwise, we just extend the valid range of dates
                // for the current notional.
                lastPaymentDate = coupon->date();
            }
        }
        QL_REQUIRE(!notionals_.empty(), "no coupons provided");
        notionals_.push_back(0.0);
        notionalSchedule_.push_back(lastPaymentDate);
    }
const Calendar & QuantLib::Bond::calendar () const [inline]
Definition at line 294 of file bond.hpp.
References calendar_.
{
        return calendar_;
    }
const Leg & QuantLib::Bond::cashflows () const [inline]
Note:
returns all the cashflows, including the redemptions.
Definition at line 302 of file bond.hpp.
References cashflows_.
Referenced by QuantLib::BondFunctions::accrualDays(), QuantLib::BondFunctions::accrualEndDate(), QuantLib::BondFunctions::accrualPeriod(), QuantLib::BondFunctions::accrualStartDate(), QuantLib::BondFunctions::accruedAmount(), QuantLib::BondFunctions::accruedDays(), QuantLib::BondFunctions::accruedPeriod(), QuantLib::AmortizingCmsRateBond::AmortizingCmsRateBond(), QuantLib::AmortizingFixedRateBond::AmortizingFixedRateBond(), QuantLib::AmortizingFloatingRateBond::AmortizingFloatingRateBond(), QuantLib::BondFunctions::atmRate(), QuantLib::BondFunctions::basisPointValue(), QuantLib::BondFunctions::bps(), QuantLib::BondFunctions::cleanPrice(), QuantLib::CmsRateBond::CmsRateBond(), QuantLib::BondFunctions::convexity(), QuantLib::BondFunctions::duration(), QuantLib::FixedRateBond::FixedRateBond(), QuantLib::FloatingRateBond::FloatingRateBond(), QuantLib::BondFunctions::maturityDate(), QuantLib::BondFunctions::nextCashFlow(), QuantLib::BondFunctions::nextCashFlowAmount(), QuantLib::BondFunctions::nextCashFlowDate(), QuantLib::BondFunctions::nextCouponRate(), QuantLib::BondFunctions::previousCashFlow(), QuantLib::BondFunctions::previousCashFlowAmount(), QuantLib::BondFunctions::previousCashFlowDate(), QuantLib::BondFunctions::previousCouponRate(), QuantLib::BondFunctions::referencePeriodEnd(), QuantLib::BondFunctions::referencePeriodStart(), QuantLib::CallableFixedRateBond::setupArguments(), QuantLib::ConvertibleBond::option::setupArguments(), QuantLib::BondFunctions::startDate(), ConvertibleBondTest::testBond(), BondTest::testCachedFloating(), QuantLib::BondFunctions::yield(), QuantLib::BondFunctions::yieldValueBasisPoint(), and QuantLib::BondFunctions::zSpread().
{
        return cashflows_;
    }
Real QuantLib::Bond::cleanPrice () const
theoretical clean price
The default bond settlement is used for calculation.
Warning:
the theoretical price calculated from a flat term structure might differ slightly from the price calculated from the corresponding yield by means of the other overload of this function. If the price from a constant yield is desired, it is advisable to use such other overload.
Definition at line 177 of file bond.cpp.
References accruedAmount(), dirtyPrice(), and settlementDate().
Referenced by cleanPrice(), dirtyPrice(), BondTest::testCached(), BondTest::testCachedFixed(), BondTest::testCachedFloating(), BondTest::testCachedZero(), anonymous_namespace{piecewiseyieldcurve.cpp}::testCurveConsistency(), BondTest::testTheoretical(), and yield().
{
        return dirtyPrice() - accruedAmount(settlementDate());
    }
Real QuantLib::Bond::cleanPrice (Rate yield, const DayCounter & dc, Compounding comp, Frequency freq, Date settlementDate = Date()) const
clean price given a yield and settlement date
The default bond settlement is used if no date is given.
Definition at line 215 of file bond.cpp.
References cleanPrice().
{
        return BondFunctions::cleanPrice(*this, y, dc, comp, freq, settlement);
    }
Real QuantLib::Bond::dirtyPrice () const
theoretical dirty price
The default bond settlement is used for calculation.
Warning:
the theoretical price calculated from a flat term structure might differ slightly from the price calculated from the corresponding yield by means of the other overload of this function. If the price from a constant yield is desired, it is advisable to use such other overload.
Definition at line 181 of file bond.cpp.
References notional(), settlementDate(), and settlementValue().
Referenced by cleanPrice(), and settlementValue().
{
        Real currentNotional = notional(settlementDate());
        if (currentNotional == 0.0)
            return 0.0;
        else
            return settlementValue()*100.0/currentNotional;
    }
Real QuantLib::Bond::dirtyPrice (Rate yield, const DayCounter & dc, Compounding comp, Frequency freq, Date settlementDate = Date()) const
dirty price given a yield and settlement date
The default bond settlement is used if no date is given.
Definition at line 223 of file bond.cpp.
References accruedAmount(), cleanPrice(), and notional().
{
        Real currentNotional = notional(settlement);
        if (currentNotional == 0.0)
            return 0.0;
        return BondFunctions::cleanPrice(*this, y, dc, comp, freq, settlement)
            + accruedAmount(settlement);
    }
void QuantLib::Bond::fetchResults (const PricingEngine::results * r) const [protected, virtual]
When a derived result structure is defined for an instrument, this method should be overridden to read from it. This is mandatory in case a pricing engine is used.
Reimplemented from QuantLib::Instrument.
Definition at line 289 of file bond.cpp.
References QL_ENSURE, QuantLib::Bond::results::settlementValue, and settlementValue_.
{
        Instrument::fetchResults(r);
        const Bond::results* results =
            dynamic_cast<const Bond::results*>(r);
        QL_ENSURE(results != 0, "wrong result type");
        settlementValue_ = results->settlementValue;
    }
bool QuantLib::Bond::isExpired () const [virtual]
returns whether the instrument might have value greater than zero.
Implements QuantLib::Instrument.
Definition at line 104 of file bond.cpp.
References cashflows_, and QuantLib::Singleton< Settings >::instance().
Referenced by QuantLib::CallableBond::impliedVolatility().
{
        // this is the Instrument interface, so it doesn't use
        // BondFunctions, and includeSettlementDateFlows is true
        // (unless QL_TODAY_PAYMENTS will set it to false later on)
        return CashFlows::isExpired(cashflows_,
                                    true,
                                    Settings::instance().evaluationDate());
    }
Date QuantLib::Bond::issueDate () const [inline]
Definition at line 310 of file bond.hpp.
References issueDate_.
{
        return issueDate_;
    }
bool QuantLib::Bond::isTradable (Date d = Date()) const
Definition at line 160 of file bond.cpp.
{
        return BondFunctions::isTradable(*this, d);
    }
Date QuantLib::Bond::maturityDate () const
Definition at line 153 of file bond.cpp.
References maturityDate_.
Referenced by QuantLib::BondFunctions::accrualDays(), QuantLib::BondFunctions::accrualEndDate(), QuantLib::BondFunctions::accrualPeriod(), QuantLib::BondFunctions::accrualStartDate(), QuantLib::BondFunctions::accruedAmount(), QuantLib::BondFunctions::accruedDays(), QuantLib::BondFunctions::accruedPeriod(), QuantLib::BondFunctions::atmRate(), QuantLib::BondFunctions::basisPointValue(), Bond(), QuantLib::BondFunctions::bps(), QuantLib::BondFunctions::cleanPrice(), QuantLib::BondFunctions::convexity(), QuantLib::BondFunctions::duration(), QuantLib::FixedRateBond::FixedRateBond(), QuantLib::FloatingRateBond::FloatingRateBond(), QuantLib::BondFunctions::referencePeriodEnd(), QuantLib::BondFunctions::referencePeriodStart(), QuantLib::BondFunctions::yield(), QuantLib::BondFunctions::yieldValueBasisPoint(), QuantLib::ZeroCouponBond::ZeroCouponBond(), and QuantLib::BondFunctions::zSpread().
{
        if (maturityDate_!=Null<Date>())
            return maturityDate_;
        else
            return BondFunctions::maturityDate(*this);
    }
Date QuantLib::Bond::nextCashFlowDate (Date d = Date()) const
Definition at line 267 of file bond.cpp.
{
        return BondFunctions::nextCashFlowDate(*this, settlement);
    }
Rate QuantLib::Bond::nextCouponRate (Date d = Date()) const [virtual]
Expected next coupon: depending on (the bond and) the given date the coupon can be historic, deterministic or expected in a stochastic sense. When the bond settlement date is used the coupon is the already-fixed not-yet-paid one.
The current bond settlement is used if no date is given.
Definition at line 259 of file bond.cpp.
{
        return BondFunctions::nextCouponRate(*this, settlement);
    }
Real QuantLib::Bond::notional (Date d = Date()) const [virtual]
Definition at line 113 of file bond.cpp.
References anonymous_namespace{marketmodel.cpp}::d, notionals_, notionalSchedule_, and settlementDate().
Referenced by QuantLib::CallableFixedRateBond::accrued(), QuantLib::BondFunctions::accruedAmount(), accruedAmount(), QuantLib::BondFunctions::bps(), calculateNotionalsFromCashflows(), QuantLib::BondFunctions::cleanPrice(), dirtyPrice(), QuantLib::BondFunctions::isTradable(), setSingleRedemption(), settlementValue(), QuantLib::BondFunctions::yield(), yield(), and QuantLib::BondFunctions::zSpread().
{
        if (d == Date())
            d = settlementDate();
        if (d > notionalSchedule_.back()) {
            // after maturity
            return 0.0;
        }
        // After the check above, d is between the schedule
        // boundaries.  We search starting from the second notional
        // date, since the first is null.  After the call to
        // lower_bound, *i is the earliest date which is greater or
        // equal than d.  Its index is greater or equal to 1.
        std::vector<Date>::const_iterator i =
            std::lower_bound(notionalSchedule_.begin()+1,
                             notionalSchedule_.end(), d);
        Size index = std::distance(notionalSchedule_.begin(), i);
        if (d < notionalSchedule_[index]) {
            // no doubt about what to return
            return notionals_[index-1];
        } else {
            // d is equal to a redemption date.
            // As per bond conventions, the payment has occurred;
            // the bond already changed notional.
            return notionals_[index];
        }
    }
const std::vector< Real > & QuantLib::Bond::notionals () const [inline]
Definition at line 298 of file bond.hpp.
References notionals_.
{
        return notionals_;
    }
Date QuantLib::Bond::previousCashFlowDate (Date d = Date()) const
Definition at line 271 of file bond.cpp.
{
        return BondFunctions::previousCashFlowDate(*this, settlement);
    }
Rate QuantLib::Bond::previousCouponRate (Date d = Date()) const
Previous coupon already paid at a given date.
Expected previous coupon: depending on (the bond and) the given date the coupon can be historic, deterministic or expected in a stochastic sense. When the bond settlement date is used the coupon is the last paid one.
The current bond settlement is used if no date is given.
Definition at line 263 of file bond.cpp.
{
        return BondFunctions::previousCouponRate(*this, settlement);
    }
const boost::shared_ptr< CashFlow > & QuantLib::Bond::redemption () const
returns the redemption, if only one is defined
Definition at line 143 of file bond.cpp.
References QL_REQUIRE, and redemptions_.
Referenced by QuantLib::CallableFixedRateBond::setupArguments(), and QuantLib::ConvertibleBond::option::arguments::validate().
{
        QL_REQUIRE(redemptions_.size() == 1,
                   "multiple redemption cash flows given");
        return redemptions_.back();
    }
const Leg & QuantLib::Bond::redemptions () const [inline]
returns just the redemption flows (not interest payments)
Definition at line 306 of file bond.hpp.
References redemptions_.
{
        return redemptions_;
    }
void QuantLib::Bond::setSingleRedemption (Real notional, Real redemption, const Date & date) [protected]
This method can be called by derived classes in order to build a bond with a single redemption payment. It will fill the notionalSchedule_, notionals_, and redemptions_ data members.
Definition at line 327 of file bond.cpp.
Referenced by QuantLib::CallableFixedRateBond::CallableFixedRateBond(), QuantLib::ConvertibleZeroCouponBond::ConvertibleZeroCouponBond(), and QuantLib::ZeroCouponBond::ZeroCouponBond().
{
        boost::shared_ptr<CashFlow> redemptionCashflow(
                         new Redemption(notional*redemption/100.0, date));
        setSingleRedemption(notional, redemptionCashflow);
    }
void QuantLib::Bond::setSingleRedemption (Real notional, const boost::shared_ptr< CashFlow > & redemption) [protected]
This method can be called by derived classes in order to build a bond with a single redemption payment. It will fill the notionalSchedule_, notionals_, and redemptions_ data members.
Definition at line 336 of file bond.cpp.
References cashflows_, notional(), notionals_, notionalSchedule_, and redemptions_.
{
        notionals_.resize(2);
        notionalSchedule_.resize(2);
        redemptions_.clear();
        notionalSchedule_[0] = Date();
        notionals_[0] = notional;
        notionalSchedule_[1] = redemption->date();
        notionals_[1] = 0.0;
        cashflows_.push_back(redemption);
        redemptions_.push_back(redemption);
    }
Date QuantLib::Bond::settlementDate (Date d = Date()) const
Definition at line 164 of file bond.cpp.
References QuantLib::Calendar::advance(), calendar_, QuantLib::Days, QuantLib::Settings::evaluationDate(), QuantLib::Singleton< Settings >::instance(), issueDate_, and settlementDays_.
Referenced by QuantLib::BondFunctions::accrualDays(), QuantLib::BondFunctions::accrualEndDate(), QuantLib::BondFunctions::accrualPeriod(), QuantLib::BondFunctions::accrualStartDate(), QuantLib::CallableFixedRateBond::accrued(), QuantLib::BondFunctions::accruedAmount(), QuantLib::BondFunctions::accruedDays(), QuantLib::BondFunctions::accruedPeriod(), QuantLib::BondFunctions::atmRate(), QuantLib::BondFunctions::basisPointValue(), QuantLib::BondFunctions::bps(), QuantLib::BondFunctions::cleanPrice(), cleanPrice(), QuantLib::BondFunctions::convexity(), dirtyPrice(), QuantLib::BondFunctions::duration(), QuantLib::BondFunctions::isTradable(), QuantLib::BondFunctions::nextCashFlow(), QuantLib::BondFunctions::nextCashFlowAmount(), QuantLib::BondFunctions::nextCashFlowDate(), QuantLib::BondFunctions::nextCouponRate(), notional(), QuantLib::BondFunctions::previousCashFlow(), QuantLib::BondFunctions::previousCashFlowAmount(), QuantLib::BondFunctions::previousCashFlowDate(), QuantLib::BondFunctions::previousCouponRate(), QuantLib::BondFunctions::referencePeriodEnd(), QuantLib::BondFunctions::referencePeriodStart(), settlementValue(), setupArguments(), BondTest::testCached(), BondTest::testTheoretical(), QuantLib::ConvertibleBond::option::arguments::validate(), QuantLib::BondFunctions::yield(), yield(), QuantLib::BondFunctions::yieldValueBasisPoint(), and QuantLib::BondFunctions::zSpread().
{
        if (d==Date())
            d = Settings::instance().evaluationDate();
        // usually, the settlement is at T+n...
        Date settlement = calendar_.advance(d, settlementDays_, Days);
        // ...but the bond won't be traded until the issue date (if given.)
        if (issueDate_ == Date())
            return settlement;
        else
            return std::max(settlement, issueDate_);
    }
Natural QuantLib::Bond::settlementDays () const [inline]
Definition at line 290 of file bond.hpp.
References settlementDays_.
Referenced by QuantLib::ConvertibleBond::option::arguments::validate().
{
        return settlementDays_;
    }
Real QuantLib::Bond::settlementValue () const
theoretical settlement value
The default bond settlement date is used for calculation.
Definition at line 189 of file bond.cpp.
References QuantLib::Instrument::calculate(), QL_REQUIRE, and settlementValue_.
Referenced by dirtyPrice(), and ConvertibleBondTest::testBond().
{
        calculate();
        QL_REQUIRE(settlementValue_ != Null<Real>(),
                   "settlement value not provided");
        return settlementValue_;
    }
Real QuantLib::Bond::settlementValue (Real cleanPrice) const
settlement value as a function of the clean price
The default bond settlement date is used for calculation.
Definition at line 196 of file bond.cpp.
References accruedAmount(), dirtyPrice(), notional(), and settlementDate().
{
        Real dirtyPrice = cleanPrice + accruedAmount(settlementDate());
        return dirtyPrice / 100.0 * notional(settlementDate());
    }
void QuantLib::Bond::setupArguments (PricingEngine::arguments *) const [protected, virtual]
When a derived argument structure is defined for an instrument, this method should be overridden to fill it. This is mandatory in case a pricing engine is used.
Reimplemented from QuantLib::Instrument.
Reimplemented in QuantLib::CallableFixedRateBond, and QuantLib::CallableBond.
Definition at line 280 of file bond.cpp.
References QuantLib::Bond::arguments::calendar, calendar_, QuantLib::Bond::arguments::cashflows, cashflows_, QL_REQUIRE, settlementDate(), and QuantLib::Bond::arguments::settlementDate.
Referenced by QuantLib::ConvertibleBond::option::setupArguments().
{
        Bond::arguments* arguments = dynamic_cast<Bond::arguments*>(args);
        QL_REQUIRE(arguments != 0, "wrong argument type");
        arguments->settlementDate = settlementDate();
        arguments->cashflows = cashflows_;
        arguments->calendar = calendar_;
    }
void QuantLib::Bond::setupExpired () const [protected, virtual]
This method must leave the instrument in a consistent state when the expiration condition is met.
Reimplemented from QuantLib::Instrument.
Definition at line 275 of file bond.cpp.
References settlementValue_.
{
        Instrument::setupExpired();
        settlementValue_ = 0.0;
    }
Date QuantLib::Bond::startDate () const
Definition at line 149 of file bond.cpp.
{
        return BondFunctions::startDate(*this);
    }
Rate QuantLib::Bond::yield (const DayCounter & dc, Compounding comp, Frequency freq, Real accuracy = 1.0e-8, Size maxEvaluations = 100) const
theoretical bond yield
The default bond settlement and theoretical price are used for calculation.
Definition at line 201 of file bond.cpp.
References cleanPrice(), notional(), and settlementDate().
Referenced by yield().
{
        Real currentNotional = notional(settlementDate());
        if (currentNotional == 0.0)
            return 0.0;
        return BondFunctions::yield(*this, cleanPrice(), dc, comp, freq,
                                    settlementDate(),
                                    accuracy, maxEvaluations);
    }
Rate QuantLib::Bond::yield (Real cleanPrice, const DayCounter & dc, Compounding comp, Frequency freq, Date settlementDate = Date(), Real accuracy = 1.0e-8, Size maxEvaluations = 100) const
yield given a (clean) price and settlement date
The default bond settlement is used if no date is given.
Definition at line 236 of file bond.cpp.
References notional(), and yield().
{
        Real currentNotional = notional(settlement);
        if (currentNotional == 0.0)
            return 0.0;
        return BondFunctions::yield(*this, cleanPrice, dc, comp, freq,
                                    settlement, accuracy, maxEvaluations);
    }
Member Data Documentation
Calendar QuantLib::Bond::calendar_ [protected]
Definition at line 257 of file bond.hpp.
Referenced by calendar(), QuantLib::CallableFixedRateBond::CallableFixedRateBond(), QuantLib::FixedRateBond::FixedRateBond(), QuantLib::FloatingRateBond::FloatingRateBond(), settlementDate(), setupArguments(), and QuantLib::ZeroCouponBond::ZeroCouponBond().
Leg QuantLib::Bond::cashflows_ [protected]
Definition at line 260 of file bond.hpp.
Referenced by QuantLib::CallableFixedRateBond::accrued(), addRedemptionsToCashflows(), QuantLib::AmortizingCmsRateBond::AmortizingCmsRateBond(), QuantLib::AmortizingFixedRateBond::AmortizingFixedRateBond(), QuantLib::AmortizingFloatingRateBond::AmortizingFloatingRateBond(), Bond(), calculateNotionalsFromCashflows(), QuantLib::CallableFixedRateBond::CallableFixedRateBond(), cashflows(), QuantLib::CmsRateBond::CmsRateBond(), QuantLib::ConvertibleFixedCouponBond::ConvertibleFixedCouponBond(), QuantLib::ConvertibleFloatingRateBond::ConvertibleFloatingRateBond(), QuantLib::ConvertibleZeroCouponBond::ConvertibleZeroCouponBond(), QuantLib::CPIBond::CPIBond(), QuantLib::FixedRateBond::FixedRateBond(), QuantLib::FloatingRateBond::FloatingRateBond(), isExpired(), setSingleRedemption(), and setupArguments().
Date QuantLib::Bond::issueDate_ [protected]
Definition at line 263 of file bond.hpp.
Referenced by Bond(), issueDate(), settlementDate(), and QuantLib::ConvertibleBond::option::setupArguments().
Date QuantLib::Bond::maturityDate_ [protected]
Definition at line 263 of file bond.hpp.
Referenced by QuantLib::AmortizingCmsRateBond::AmortizingCmsRateBond(), QuantLib::AmortizingFixedRateBond::AmortizingFixedRateBond(), QuantLib::AmortizingFloatingRateBond::AmortizingFloatingRateBond(), Bond(), QuantLib::CallableBond::CallableBond(), QuantLib::CallableFixedRateBond::CallableFixedRateBond(), QuantLib::CmsRateBond::CmsRateBond(), QuantLib::ConvertibleBond::ConvertibleBond(), QuantLib::ConvertibleZeroCouponBond::ConvertibleZeroCouponBond(), QuantLib::CPIBond::CPIBond(), QuantLib::FixedRateBond::FixedRateBond(), QuantLib::FloatingRateBond::FloatingRateBond(), maturityDate(), and QuantLib::ZeroCouponBond::ZeroCouponBond().
std::vector<Real> QuantLib::Bond::notionals_ [protected]
Definition at line 259 of file bond.hpp.
Referenced by addRedemptionsToCashflows(), Bond(), calculateNotionalsFromCashflows(), notional(), notionals(), and setSingleRedemption().
std::vector<Date> QuantLib::Bond::notionalSchedule_ [protected]
Definition at line 258 of file bond.hpp.
Referenced by addRedemptionsToCashflows(), Bond(), calculateNotionalsFromCashflows(), notional(), and setSingleRedemption().
Leg QuantLib::Bond::redemptions_ [protected]
Definition at line 261 of file bond.hpp.
Referenced by addRedemptionsToCashflows(), Bond(), QuantLib::CmsRateBond::CmsRateBond(), QuantLib::ConvertibleFixedCouponBond::ConvertibleFixedCouponBond(), QuantLib::ConvertibleFloatingRateBond::ConvertibleFloatingRateBond(), QuantLib::FixedRateBond::FixedRateBond(), QuantLib::FloatingRateBond::FloatingRateBond(), redemption(), redemptions(), and setSingleRedemption().
Natural QuantLib::Bond::settlementDays_ [protected]
Definition at line 256 of file bond.hpp.
Referenced by settlementDate(), settlementDays(), and QuantLib::ConvertibleBond::option::setupArguments().
Real QuantLib::Bond::settlementValue_ [mutable, protected]
Definition at line 264 of file bond.hpp.
Referenced by fetchResults(), QuantLib::ConvertibleBond::performCalculations(), settlementValue(), and setupExpired().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/bond.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/bond.cpp