QuantLib: QuantLib::OvernightIndexedCoupon Class Reference
QuantLib::OvernightIndexedCoupon Class Reference
overnight coupon
#include <overnightindexedcoupon.hpp>
Public Member Functions
OvernightIndexedCoupon (const Date &paymentDate, Real nominal, const Date &startDate, const Date &endDate, const boost::shared_ptr< OvernightIndex > &overnightIndex, Real gearing=1.0, Spread spread=0.0, const Date &refPeriodStart=Date(), const Date &refPeriodEnd=Date(), const DayCounter &dayCounter=DayCounter())
Inspectors
const std::vector< Date > & fixingDates () const
fixing dates for the rates to be compounded
const std::vector< Time > & dt () const
accrual (compounding) periods
const std::vector< Rate > & indexFixings () const
fixings to be compounded
const std::vector< Date > & valueDates () const
value dates for the rates to be compounded
FloatingRateCoupon interface
Date fixingDate () const
the date when the coupon is fully determined
Visitability
void accept (AcyclicVisitor &)
Private Attributes
std::vector< Date > valueDates_
std::vector< Date > fixingDates_
std::vector< Rate > fixings_
Size n_
std::vector< Time > dt_
Detailed Description
overnight coupon
Coupon paying the compounded interest due to daily overnight fixings.
Definition at line 36 of file overnightindexedcoupon.hpp.
Constructor & Destructor Documentation
QuantLib::OvernightIndexedCoupon::OvernightIndexedCoupon (const Date & paymentDate, Real nominal, const Date & startDate, const Date & endDate, const boost::shared_ptr< OvernightIndex > & overnightIndex, Real gearing = 1.0, Spread spread = 0.0, const Date & refPeriodStart = Date(), const Date & refPeriodEnd = Date(), const DayCounter & dayCounter = DayCounter())
Definition at line 114 of file overnightindexedcoupon.cpp.
References QuantLib::Schedule::dates(), QuantLib::Days, dt_, fixingDates_, QuantLib::MakeSchedule::from(), n_, QL_ENSURE, QuantLib::FloatingRateCoupon::setPricer(), QuantLib::MakeSchedule::to(), valueDates_, QuantLib::MakeSchedule::withCalendar(), QuantLib::MakeSchedule::withTenor(), and QuantLib::DayCounter::yearFraction().
    : FloatingRateCoupon(paymentDate, nominal, startDate, endDate,
                         overnightIndex->fixingDays(), overnightIndex,
                         gearing, spread,
                         refPeriodStart, refPeriodEnd,
                         dayCounter, false) {
        // value dates
        Schedule sch = MakeSchedule()
                    .from(startDate)
                    .to(endDate)
                    .withTenor(1*Days)
                    .withCalendar(overnightIndex->fixingCalendar())
                    .withConvention(overnightIndex->businessDayConvention())
                    .backwards();
        valueDates_ = sch.dates();
        QL_ENSURE(valueDates_.size()>=2, "degenerate schedule");
        // fixing dates
        n_ = valueDates_.size()-1;
        if (overnightIndex->fixingDays()==0) {
            fixingDates_ = vector<Date>(valueDates_.begin(),
                                             valueDates_.end()-1);
        } else {
            fixingDates_.resize(n_);
            for (Size i=0; i<n_; ++i)
                fixingDates_[i] = overnightIndex->fixingDate(valueDates_[i]);
        }
        // accrual (compounding) periods
        dt_.resize(n_);
        const DayCounter& dc = overnightIndex->dayCounter();
        for (Size i=0; i<n_; ++i)
            dt_[i] = dc.yearFraction(valueDates_[i], valueDates_[i+1]);
        setPricer(shared_ptr<FloatingRateCouponPricer>(new
                                            OvernightIndexedCouponPricer));
    }
Member Function Documentation
void QuantLib::OvernightIndexedCoupon::accept (AcyclicVisitor & v) [virtual]
Reimplemented from QuantLib::FloatingRateCoupon.
Definition at line 170 of file overnightindexedcoupon.cpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Visitor< T >::visit().
{
        Visitor<OvernightIndexedCoupon>* v1 =
            dynamic_cast<Visitor<OvernightIndexedCoupon>*>(&v);
        if (v1 != 0) {
            v1->visit(*this);
        } else {
            FloatingRateCoupon::accept(v);
        }
    }
const std::vector<Time>& QuantLib::OvernightIndexedCoupon::dt () const [inline]
accrual (compounding) periods
Definition at line 54 of file overnightindexedcoupon.hpp.
References dt_.
{ return dt_; }
Date QuantLib::OvernightIndexedCoupon::fixingDate () const [inline, virtual]
the date when the coupon is fully determined
Reimplemented from QuantLib::FloatingRateCoupon.
Definition at line 63 of file overnightindexedcoupon.hpp.
References fixingDates_.
{ return fixingDates_.back(); }
const std::vector<Date>& QuantLib::OvernightIndexedCoupon::fixingDates () const [inline]
fixing dates for the rates to be compounded
Definition at line 52 of file overnightindexedcoupon.hpp.
References fixingDates_.
{ return fixingDates_; }
const vector< Rate > & QuantLib::OvernightIndexedCoupon::indexFixings () const
fixings to be compounded
Definition at line 163 of file overnightindexedcoupon.cpp.
References fixingDates_, fixings_, QuantLib::FloatingRateCoupon::index_, and n_.
{
        fixings_.resize(n_);
        for (Size i=0; i<n_; ++i)
            fixings_[i] = index_->fixing(fixingDates_[i]);
        return fixings_;
    }
const std::vector<Date>& QuantLib::OvernightIndexedCoupon::valueDates () const [inline]
value dates for the rates to be compounded
Definition at line 58 of file overnightindexedcoupon.hpp.
References valueDates_.
{ return valueDates_; }
Member Data Documentation
std::vector<Time> QuantLib::OvernightIndexedCoupon::dt_ [private]
Definition at line 73 of file overnightindexedcoupon.hpp.
Referenced by dt(), and OvernightIndexedCoupon().
std::vector<Date> QuantLib::OvernightIndexedCoupon::fixingDates_ [private]
Definition at line 70 of file overnightindexedcoupon.hpp.
Referenced by fixingDate(), fixingDates(), indexFixings(), and OvernightIndexedCoupon().
std::vector<Rate> QuantLib::OvernightIndexedCoupon::fixings_ [mutable, private]
Definition at line 71 of file overnightindexedcoupon.hpp.
Referenced by indexFixings().
Size QuantLib::OvernightIndexedCoupon::n_ [private]
Definition at line 72 of file overnightindexedcoupon.hpp.
Referenced by indexFixings(), and OvernightIndexedCoupon().
std::vector<Date> QuantLib::OvernightIndexedCoupon::valueDates_ [private]
Definition at line 70 of file overnightindexedcoupon.hpp.
Referenced by OvernightIndexedCoupon(), and valueDates().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/overnightindexedcoupon.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/overnightindexedcoupon.cpp