QuantLib: QuantLib::QuantoVanillaOption Class Reference
QuantLib::QuantoVanillaOption Class Reference
quanto version of a vanilla option
#include <quantovanillaoption.hpp>
Public Types
typedef OneAssetOption::arguments arguments
typedef QuantoOptionResults
< OneAssetOption::results > results
typedef GenericEngine
< arguments, results > engine
Public Member Functions
QuantoVanillaOption (const boost::shared_ptr< StrikedTypePayoff > &, const boost::shared_ptr< Exercise > &)
void fetchResults (const PricingEngine::results *) const
greeks
Real qvega () const
Real qrho () const
Real qlambda () const
Private Member Functions
void setupExpired () const
Private Attributes
Real qvega_
Real qrho_
Real qlambda_
Detailed Description
quanto version of a vanilla option
Definition at line 49 of file quantovanillaoption.hpp.
Member Typedef Documentation
typedef OneAssetOption::arguments QuantLib::QuantoVanillaOption::arguments
Definition at line 51 of file quantovanillaoption.hpp.
typedef GenericEngine<arguments, results> QuantLib::QuantoVanillaOption::engine
Definition at line 53 of file quantovanillaoption.hpp.
typedef QuantoOptionResults<OneAssetOption::results> QuantLib::QuantoVanillaOption::results
Definition at line 52 of file quantovanillaoption.hpp.
Constructor & Destructor Documentation
QuantLib::QuantoVanillaOption::QuantoVanillaOption (const boost::shared_ptr< StrikedTypePayoff > & payoff, const boost::shared_ptr< Exercise > & exercise)
Definition at line 25 of file quantovanillaoption.cpp.
    : OneAssetOption(payoff, exercise) {}
Member Function Documentation
void QuantLib::QuantoVanillaOption::fetchResults (const PricingEngine::results * r) const [virtual]
When a derived result structure is defined for an instrument, this method should be overridden to read from it. This is mandatory in case a pricing engine is used.
Reimplemented from QuantLib::OneAssetOption.
Definition at line 56 of file quantovanillaoption.cpp.
References QL_ENSURE, QuantLib::QuantoOptionResults< ResultsType >::qlambda, qlambda_, QuantLib::QuantoOptionResults< ResultsType >::qrho, qrho_, QuantLib::QuantoOptionResults< ResultsType >::qvega, and qvega_.
{
        OneAssetOption::fetchResults(r);
        const QuantoVanillaOption::results* quantoResults =
            dynamic_cast<const QuantoVanillaOption::results*>(r);
        QL_ENSURE(quantoResults != 0,
                  "no quanto results returned from pricing engine");
        qrho_    = quantoResults->qrho;
        qvega_   = quantoResults->qvega;
        qlambda_ = quantoResults->qlambda;
    }
Real QuantLib::QuantoVanillaOption::qlambda () const
Definition at line 44 of file quantovanillaoption.cpp.
References QuantLib::Instrument::calculate(), QL_REQUIRE, and qlambda_.
Referenced by QuantoOptionTest::testGreeks().
{
        calculate();
        QL_REQUIRE(qlambda_ != Null<Real>(),
                   "quanto correlation sensitivity calculation failed");
        return qlambda_;
    }
Real QuantLib::QuantoVanillaOption::qrho () const
Definition at line 37 of file quantovanillaoption.cpp.
References QuantLib::Instrument::calculate(), QL_REQUIRE, and qrho_.
Referenced by QuantoOptionTest::testGreeks().
{
        calculate();
        QL_REQUIRE(qrho_ != Null<Real>(),
                   "foreign interest rate rho calculation failed");
        return qrho_;
    }
Real QuantLib::QuantoVanillaOption::qvega () const
Definition at line 30 of file quantovanillaoption.cpp.
References QuantLib::Instrument::calculate(), QL_REQUIRE, and qvega_.
Referenced by QuantoOptionTest::testGreeks().
{
        calculate();
        QL_REQUIRE(qvega_ != Null<Real>(),
                   "exchange rate vega calculation failed");
        return qvega_;
    }
void QuantLib::QuantoVanillaOption::setupExpired () const [private, virtual]
This method must leave the instrument in a consistent state when the expiration condition is met.
Reimplemented from QuantLib::OneAssetOption.
Definition at line 51 of file quantovanillaoption.cpp.
References qlambda_, qrho_, and qvega_.
{
        OneAssetOption::setupExpired();
        qvega_ = qrho_ = qlambda_ = 0.0;
    }
Member Data Documentation
Real QuantLib::QuantoVanillaOption::qlambda_ [mutable, private]
Definition at line 66 of file quantovanillaoption.hpp.
Referenced by fetchResults(), qlambda(), and setupExpired().
Real QuantLib::QuantoVanillaOption::qrho_ [mutable, private]
Definition at line 66 of file quantovanillaoption.hpp.
Referenced by fetchResults(), qrho(), and setupExpired().
Real QuantLib::QuantoVanillaOption::qvega_ [mutable, private]
Definition at line 66 of file quantovanillaoption.hpp.
Referenced by fetchResults(), qvega(), and setupExpired().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/quantovanillaoption.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/quantovanillaoption.cpp