QuantLib: QuantLib::TripleBandLinearOp Class Reference
QuantLib::TripleBandLinearOp Class Reference
#include <triplebandlinearop.hpp>
Public Member Functions
TripleBandLinearOp (Size direction, const boost::shared_ptr< FdmMesher > &mesher)
TripleBandLinearOp (const TripleBandLinearOp &m)
TripleBandLinearOp (const Disposable< TripleBandLinearOp > &m)
TripleBandLinearOp & operator= (const TripleBandLinearOp &m)
TripleBandLinearOp & operator= (const Disposable< TripleBandLinearOp > &m)
Disposable< Array > apply (const Array &r) const
Disposable< Array > solve_splitting (const Array &r, Real a, Real b=1.0) const
Disposable< TripleBandLinearOp > mult (const Array &u) const
Disposable< TripleBandLinearOp > add (const TripleBandLinearOp &m) const
Disposable< TripleBandLinearOp > add (const Array &u) const
void axpyb (const Array &a, const TripleBandLinearOp &x, const TripleBandLinearOp &y, const Array &b)
void swap (TripleBandLinearOp &m)
Disposable< SparseMatrix > toMatrix () const
Protected Member Functions
TripleBandLinearOp ()
Protected Attributes
Size direction_
boost::shared_array< Size > i0_
boost::shared_array< Size > i2_
boost::shared_array< Size > reverseIndex_
boost::shared_array< Real > lower_
boost::shared_array< Real > diag_
boost::shared_array< Real > upper_
boost::shared_ptr< FdmMesher > mesher_
Detailed Description
Definition at line 40 of file triplebandlinearop.hpp.
Constructor & Destructor Documentation
QuantLib::TripleBandLinearOp::TripleBandLinearOp (Size direction, const boost::shared_ptr< FdmMesher > & mesher)
Definition at line 29 of file triplebandlinearop.cpp.
References direction_, i0_, i2_, QuantLib::dsd::inner_product(), reverseIndex_, and QuantLib::FdmLinearOpLayout::spacing().
    : direction_(direction),
      i0_       (new Size[mesher->layout()->size()]),
      i2_       (new Size[mesher->layout()->size()]),
      reverseIndex_ (new Size[mesher->layout()->size()]),
      lower_    (new Real[mesher->layout()->size()]),
      diag_     (new Real[mesher->layout()->size()]),
      upper_    (new Real[mesher->layout()->size()]),
      mesher_(mesher) {
        const boost::shared_ptr<FdmLinearOpLayout> layout = mesher->layout();
        const FdmLinearOpIterator endIter = layout->end();
        std::vector<Size> newDim(layout->dim());
        std::iter_swap(newDim.begin(), newDim.begin()+direction_);
        std::vector<Size> newSpacing = FdmLinearOpLayout(newDim).spacing();
        std::iter_swap(newSpacing.begin(), newSpacing.begin()+direction_);
        for (FdmLinearOpIterator iter = layout->begin(); iter!=endIter; ++iter) {
            const Size i = iter.index();
            i0_[i] = layout->neighbourhood(iter, direction, -1);
            i2_[i] = layout->neighbourhood(iter, direction,  1);
            const std::vector<Size>& coordinates = iter.coordinates();
            const Size newIndex =
                  std::inner_product(coordinates.begin(), coordinates.end(),
                                     newSpacing.begin(), Size(0));
            reverseIndex_[newIndex] = i;
        }
    }
QuantLib::TripleBandLinearOp::TripleBandLinearOp (const TripleBandLinearOp & m)
Definition at line 63 of file triplebandlinearop.cpp.
References diag_, i0_, i2_, anonymous_namespace{libormarketmodelprocess.cpp}::len, lower_, mesher_, reverseIndex_, and upper_.
    : direction_(m.direction_),
      i0_   (new Size[m.mesher_->layout()->size()]),
      i2_   (new Size[m.mesher_->layout()->size()]),
      reverseIndex_(new Size[m.mesher_->layout()->size()]),
      lower_(new Real[m.mesher_->layout()->size()]),
      diag_ (new Real[m.mesher_->layout()->size()]),
      upper_(new Real[m.mesher_->layout()->size()]),
      mesher_(m.mesher_) {
        const Size len = m.mesher_->layout()->size();
        std::copy(m.i0_.get(), m.i0_.get() + len, i0_.get());
        std::copy(m.i2_.get(), m.i2_.get() + len, i2_.get());
        std::copy(m.reverseIndex_.get(), m.reverseIndex_.get()+len,
                  reverseIndex_.get());
        std::copy(m.lower_.get(), m.lower_.get() + len, lower_.get());
        std::copy(m.diag_.get(),  m.diag_.get() + len,  diag_.get());
        std::copy(m.upper_.get(), m.upper_.get() + len, upper_.get());
    }
QuantLib::TripleBandLinearOp::TripleBandLinearOp (const Disposable< TripleBandLinearOp > & m)
Definition at line 83 of file triplebandlinearop.cpp.
References swap().
{
        swap(const_cast<Disposable<TripleBandLinearOp>&>(from));
    }
QuantLib::TripleBandLinearOp::TripleBandLinearOp () [inline, protected]
Definition at line 69 of file triplebandlinearop.hpp.
{}
Member Function Documentation
Disposable< TripleBandLinearOp > QuantLib::TripleBandLinearOp::add (const TripleBandLinearOp & m) const
Definition at line 179 of file triplebandlinearop.cpp.
References diag_, direction_, lower_, mesher_, and upper_.
{
        TripleBandLinearOp retVal(direction_, mesher_);
        const Size size = mesher_->layout()->size();
        for (Size i=0; i < size; ++i) {
            retVal.lower_[i]= lower_[i] + m.lower_[i];
            retVal.diag_[i] = diag_[i]  + m.diag_[i];
            retVal.upper_[i]= upper_[i] + m.upper_[i];
        }
        return retVal;
    }
Disposable< TripleBandLinearOp > QuantLib::TripleBandLinearOp::add (const Array & u) const
Definition at line 208 of file triplebandlinearop.cpp.
References diag_, direction_, lower_, mesher_, and upper_.
{
        TripleBandLinearOp retVal(direction_, mesher_);
        const Size size = mesher_->layout()->size();
        for (Size i=0; i < size; ++i) {
            retVal.lower_[i]= lower_[i];
            retVal.upper_[i]= upper_[i];
            retVal.diag_[i] = diag_[i]+u[i];
        }
        return retVal;
    }
Disposable< Array > QuantLib::TripleBandLinearOp::apply (const Array & r) const [virtual]
Implements QuantLib::FdmLinearOp.
Definition at line 222 of file triplebandlinearop.cpp.
References diag_, i0_, i2_, lower_, mesher_, QL_REQUIRE, QuantLib::Array::size(), and upper_.
Referenced by QuantLib::FdmG2Op::apply(), QuantLib::FdmHullWhiteOp::apply(), QuantLib::FdmBlackScholesOp::apply(), QuantLib::FdmExtendedOrnsteinUhlenbackOp::apply(), QuantLib::FdmExtOUJumpOp::apply(), QuantLib::FdmHestonHullWhiteOp::apply(), QuantLib::FdmHestonOp::apply(), QuantLib::FdmG2Op::apply_direction(), QuantLib::FdmHullWhiteOp::apply_direction(), QuantLib::FdmBlackScholesOp::apply_direction(), QuantLib::FdmExtendedOrnsteinUhlenbackOp::apply_direction(), QuantLib::FdmExtOUJumpOp::apply_direction(), QuantLib::FdmHestonHullWhiteOp::apply_direction(), QuantLib::FdmHestonOp::apply_direction(), FdmLinearOpTest::testFirstDerivativesMapApply(), FdmLinearOpTest::testSecondDerivativesMapApply(), and FdmLinearOpTest::testTripleBandMapSolve().
{
        const boost::shared_ptr<FdmLinearOpLayout> index = mesher_->layout();
        QL_REQUIRE(r.size() == index->size(), "inconsistent length of r");
        const Real* lptr = lower_.get();
        const Real* dptr = diag_.get();
        const Real* uptr = upper_.get();
        const Size* i0ptr = i0_.get();
        const Size* i2ptr = i2_.get();
        array_type retVal(r.size());
        for (Size i=0; i < index->size(); ++i) {
            retVal[i] = r[i0ptr[i]]*lptr[i]+r[i]*dptr[i]+r[i2ptr[i]]*uptr[i];
        }
        return retVal;
    }
void QuantLib::TripleBandLinearOp::axpyb (const Array & a, const TripleBandLinearOp & x, const TripleBandLinearOp & y, const Array & b)
Definition at line 110 of file triplebandlinearop.cpp.
References QuantLib::Array::begin(), diag_, QuantLib::Array::empty(), lower_, mesher_, QuantLib::Array::size(), and upper_.
Referenced by QuantLib::FdmG2Op::setTime(), QuantLib::FdmHestonEquityPart::setTime(), QuantLib::FdmHullWhiteOp::setTime(), QuantLib::FdmHestonHullWhiteEquityPart::setTime(), QuantLib::FdmBlackScholesOp::setTime(), QuantLib::FdmExtendedOrnsteinUhlenbackOp::setTime(), QuantLib::FdmHestonVariancePart::setTime(), and FdmLinearOpTest::testTripleBandMapSolve().
{
        const Size size = mesher_->layout()->size();
        Real *diag(diag_.get());
        Real *lower(lower_.get());
        Real *upper(upper_.get());
        const Real *y_diag (y.diag_.get());
        const Real *y_lower(y.lower_.get());
        const Real *y_upper(y.upper_.get());
        if (a.empty()) {
            if (b.empty()) {
                for (Size i=0; i < size; ++i) {
                    diag[i]  = y_diag[i];
                    lower[i] = y_lower[i];
                    upper[i] = y_upper[i];
                }
            }
            else {
                Array::const_iterator bptr(b.begin());
                const Size binc = (b.size() > 1) ? 1 : 0;
                for (Size i=0; i < size; ++i) {
                    diag[i]  = y_diag[i] + bptr[i*binc];
                    lower[i] = y_lower[i];
                    upper[i] = y_upper[i];
                }
            }
        }
        else if (b.empty()) {
            Array::const_iterator aptr(a.begin());
            const Size ainc = (a.size() > 1) ? 1 : 0;
            const Real *x_diag (x.diag_.get());
            const Real *x_lower(x.lower_.get());
            const Real *x_upper(x.upper_.get());
            for (Size i=0; i < size; ++i) {
                const Real s = aptr[i*ainc];
                diag[i]  = y_diag[i]  + s*x_diag[i];
                lower[i] = y_lower[i] + s*x_lower[i];
                upper[i] = y_upper[i] + s*x_upper[i];
            }
        }
        else {
            Array::const_iterator bptr(b.begin());
            const Size binc = (b.size() > 1) ? 1 : 0;
            Array::const_iterator aptr(a.begin());
            const Size ainc = (a.size() > 1) ? 1 : 0;
            const Real *x_diag (x.diag_.get());
            const Real *x_lower(x.lower_.get());
            const Real *x_upper(x.upper_.get());
            for (Size i=0; i < size; ++i) {
                const Real s = aptr[i*ainc];
                diag[i]  = y_diag[i]  + s*x_diag[i] + bptr[i*binc];
                lower[i] = y_lower[i] + s*x_lower[i];
                upper[i] = y_upper[i] + s*x_upper[i];
            }
        }
    }
Disposable< TripleBandLinearOp > QuantLib::TripleBandLinearOp::mult (const Array & u) const
Definition at line 193 of file triplebandlinearop.cpp.
References diag_, direction_, lower_, mesher_, and upper_.
Referenced by QuantLib::FdmBlackScholesOp::setTime().
{
        TripleBandLinearOp retVal(direction_, mesher_);
        const Size size = mesher_->layout()->size();
        for (Size i=0; i < size; ++i) {
            const Real s = u[i];
            retVal.lower_[i]= lower_[i]*s;
            retVal.diag_[i] = diag_[i]*s;
            retVal.upper_[i]= upper_[i]*s;
        }
        return retVal;
    }
TripleBandLinearOp & QuantLib::TripleBandLinearOp::operator= (const TripleBandLinearOp & m)
Definition at line 88 of file triplebandlinearop.cpp.
References swap().
{
        TripleBandLinearOp tmp(m);
        swap(tmp);
        return *this;
    }
TripleBandLinearOp & QuantLib::TripleBandLinearOp::operator= (const Disposable< TripleBandLinearOp > & m)
Definition at line 95 of file triplebandlinearop.cpp.
References swap().
{
        swap(const_cast<Disposable<TripleBandLinearOp>&>(m));
        return *this;
    }
Disposable< Array > QuantLib::TripleBandLinearOp::solve_splitting (const Array & r, Real a, Real b = 1.0) const
Definition at line 259 of file triplebandlinearop.cpp.
References anonymous_namespace{marketmodel.cpp}::b, diag_, direction_, lower_, mesher_, QL_ENSURE, QL_REQUIRE, reverseIndex_, QuantLib::Array::size(), and upper_.
Referenced by QuantLib::FdmG2Op::solve_splitting(), QuantLib::FdmHullWhiteOp::solve_splitting(), QuantLib::FdmBlackScholesOp::solve_splitting(), QuantLib::FdmExtendedOrnsteinUhlenbackOp::solve_splitting(), QuantLib::FdmExtOUJumpOp::solve_splitting(), QuantLib::FdmHestonHullWhiteOp::solve_splitting(), QuantLib::FdmHestonOp::solve_splitting(), and FdmLinearOpTest::testTripleBandMapSolve().
{
        const boost::shared_ptr<FdmLinearOpLayout> layout = mesher_->layout();
        QL_REQUIRE(r.size() == layout->size(), "inconsistent size of rhs");
#ifdef QL_EXTRA_SAFETY_CHECKS
        for (FdmLinearOpIterator iter = layout->begin();
             iter!=layout->end(); ++iter) {
            const std::vector<Size>& coordinates = iter.coordinates();
            QL_REQUIRE(   coordinates[direction_] != 0
                       || lower_[iter.index()] == 0,"removing non zero entry!");
            QL_REQUIRE(   coordinates[direction_] != layout->dim()[direction_]-1
                       || upper_[iter.index()] == 0,"removing non zero entry!");
        }
#endif
        Array retVal(r.size()), tmp(r.size());
        const Real* lptr = lower_.get();
        const Real* dptr = diag_.get();
        const Real* uptr = upper_.get();
        // Thomson algorithm to solve a tridiagonal system.
        // Example code taken from Tridiagonalopertor and
        // changed to fit for the triple band operator.
        Size rim1 = reverseIndex_[0];
        Real bet=1.0/(a*dptr[rim1]+b);
        QL_REQUIRE(bet != 0.0, "division by zero");
        retVal[reverseIndex_[0]] = r[rim1]*bet;
        for (Size j=1; j<=layout->size()-1; j++){
            const Size ri = reverseIndex_[j];
            tmp[j] = a*uptr[rim1]*bet;
            bet=b+a*(dptr[ri]-tmp[j]*lptr[ri]);
            QL_ENSURE(bet != 0.0, "division by zero");
            bet=1.0/bet;
            retVal[ri] = (r[ri]-a*lptr[ri]*retVal[rim1])*bet;
            rim1 = ri;
        }
        // cannot be j>=0 with Size j
        for (Size j=layout->size()-2; j>0; --j)
            retVal[reverseIndex_[j]] -= tmp[j+1]*retVal[reverseIndex_[j+1]];
        retVal[reverseIndex_[0]] -= tmp[1]*retVal[reverseIndex_[1]];
        return retVal;
    }
void QuantLib::TripleBandLinearOp::swap (TripleBandLinearOp & m)
Definition at line 101 of file triplebandlinearop.cpp.
References diag_, direction_, i0_, i2_, lower_, mesher_, reverseIndex_, and upper_.
Referenced by operator=(), and TripleBandLinearOp().
{
        std::swap(mesher_, m.mesher_);
        std::swap(direction_, m.direction_);
        i0_.swap(m.i0_); i2_.swap(m.i2_);
        reverseIndex_.swap(m.reverseIndex_);
        lower_.swap(m.lower_); diag_.swap(m.diag_); upper_.swap(m.upper_);
    }
Disposable< SparseMatrix > QuantLib::TripleBandLinearOp::toMatrix () const [virtual]
Reimplemented from QuantLib::FdmLinearOp.
Definition at line 242 of file triplebandlinearop.cpp.
References diag_, i0_, i2_, lower_, mesher_, and upper_.
Referenced by QuantLib::FdmG2Op::toMatrix(), QuantLib::FdmHullWhiteOp::toMatrix(), QuantLib::FdmBlackScholesOp::toMatrix(), QuantLib::FdmExtendedOrnsteinUhlenbackOp::toMatrix(), QuantLib::FdmExtOUJumpOp::toMatrix(), QuantLib::FdmHestonHullWhiteOp::toMatrix(), and QuantLib::FdmHestonOp::toMatrix().
{
        const boost::shared_ptr<FdmLinearOpLayout> index = mesher_->layout();
        const Size n = index->size();
        SparseMatrix retVal(n, n, 3*n);
        for (Size i=0; i < n; ++i) {
            retVal(i, i0_[i]) += lower_[i];
            retVal(i, i     ) += diag_[i];
            retVal(i, i2_[i]) += upper_[i];
        }
        return retVal;
    }
Member Data Documentation
boost::shared_array<Real> QuantLib::TripleBandLinearOp::diag_ [protected]
Definition at line 74 of file triplebandlinearop.hpp.
Referenced by add(), apply(), axpyb(), QuantLib::FirstDerivativeOp::FirstDerivativeOp(), mult(), QuantLib::SecondDerivativeOp::SecondDerivativeOp(), solve_splitting(), swap(), toMatrix(), and TripleBandLinearOp().
Size QuantLib::TripleBandLinearOp::direction_ [protected]
Definition at line 71 of file triplebandlinearop.hpp.
Referenced by add(), QuantLib::FirstDerivativeOp::FirstDerivativeOp(), mult(), QuantLib::SecondDerivativeOp::SecondDerivativeOp(), solve_splitting(), swap(), and TripleBandLinearOp().
boost::shared_array<Size> QuantLib::TripleBandLinearOp::i0_ [protected]
Definition at line 72 of file triplebandlinearop.hpp.
Referenced by apply(), swap(), toMatrix(), and TripleBandLinearOp().
boost::shared_array<Size> QuantLib::TripleBandLinearOp::i2_ [protected]
Definition at line 72 of file triplebandlinearop.hpp.
Referenced by apply(), swap(), toMatrix(), and TripleBandLinearOp().
boost::shared_array<Real> QuantLib::TripleBandLinearOp::lower_ [protected]
Definition at line 74 of file triplebandlinearop.hpp.
Referenced by add(), apply(), axpyb(), QuantLib::FirstDerivativeOp::FirstDerivativeOp(), mult(), QuantLib::SecondDerivativeOp::SecondDerivativeOp(), solve_splitting(), swap(), toMatrix(), and TripleBandLinearOp().
boost::shared_ptr<FdmMesher> QuantLib::TripleBandLinearOp::mesher_ [protected]
Definition at line 76 of file triplebandlinearop.hpp.
Referenced by add(), apply(), axpyb(), mult(), solve_splitting(), swap(), toMatrix(), and TripleBandLinearOp().
boost::shared_array<Size> QuantLib::TripleBandLinearOp::reverseIndex_ [protected]
Definition at line 73 of file triplebandlinearop.hpp.
Referenced by solve_splitting(), swap(), and TripleBandLinearOp().
boost::shared_array<Real> QuantLib::TripleBandLinearOp::upper_ [protected]
Definition at line 74 of file triplebandlinearop.hpp.
Referenced by add(), apply(), axpyb(), QuantLib::FirstDerivativeOp::FirstDerivativeOp(), mult(), QuantLib::SecondDerivativeOp::SecondDerivativeOp(), solve_splitting(), swap(), toMatrix(), and TripleBandLinearOp().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/operators/triplebandlinearop.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/operators/triplebandlinearop.cpp