QuantLib: QuantLib::FDEuropeanEngine< Scheme > Class Template Reference
QuantLib::FDEuropeanEngine< Scheme > Class Template Reference
Pricing engine for European options using finite-differences.
#include <fdeuropeanengine.hpp>
Public Member Functions
FDEuropeanEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > &process, Size timeSteps=100, Size gridPoints=100, bool timeDependent=false)
Private Member Functions
void calculate () const
Private Attributes
SampledCurve prices_
Detailed Description
template<template< class > class Scheme = CrankNicolson>
class QuantLib::FDEuropeanEngine< Scheme >
Pricing engine for European options using finite-differences.
Test:
the correctness of the returned value is tested by checking it against analytic results.
Definition at line 43 of file fdeuropeanengine.hpp.
Constructor & Destructor Documentation
template<template< class > class Scheme = CrankNicolson> QuantLib::FDEuropeanEngine< Scheme >::FDEuropeanEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > & process, Size timeSteps = 100, Size gridPoints = 100, bool timeDependent = false) [inline]
Definition at line 46 of file fdeuropeanengine.hpp.
References QuantLib::Observer::registerWith().
        : FDVanillaEngine(process, timeSteps, gridPoints, timeDependent),
          prices_(gridPoints) {
            registerWith(process);
        }
Member Function Documentation
template<template< class > class Scheme> void QuantLib::FDEuropeanEngine< Scheme >::calculate () const [private, virtual]
Implements QuantLib::PricingEngine.
Definition at line 61 of file fdeuropeanengine.hpp.
References QuantLib::blackScholesTheta(), and QuantLib::FiniteDifferenceModel< Evolver >::rollback().
{
        setupArguments(&arguments_);
        setGridLimits();
        initializeInitialCondition();
        initializeOperator();
        initializeBoundaryConditions();
        FiniteDifferenceModel<Scheme<TridiagonalOperator> > model(
                                             finiteDifferenceOperator_, BCs_);
        prices_ = intrinsicValues_;
        model.rollback(prices_.values(), getResidualTime(),
                       0, timeSteps_);
        results_.value = prices_.valueAtCenter();
        results_.delta = prices_.firstDerivativeAtCenter();
        results_.gamma = prices_.secondDerivativeAtCenter();
        results_.theta = blackScholesTheta(process_,
                                           results_.value,
                                           results_.delta,
                                           results_.gamma);
        results_.additionalResults["priceCurve"] = prices_;
    }
Member Data Documentation
template<template< class > class Scheme = CrankNicolson> SampledCurve QuantLib::FDEuropeanEngine< Scheme >::prices_ [mutable, private]
Definition at line 55 of file fdeuropeanengine.hpp.
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/vanilla/fdeuropeanengine.hpp