QuantLib: QuantLib::YoYInflationCapFloor Class Reference
QuantLib::YoYInflationCapFloor Class Reference
Base class for yoy inflation cap-like instruments.
#include <inflationcapfloor.hpp>
Classes
class arguments
Arguments for YoY Inflation cap/floor calculation
class engine
base class for cap/floor engines
Public Types
enum Type { Cap, Floor, Collar }
Public Member Functions
YoYInflationCapFloor (Type type, const Leg &yoyLeg, const std::vector< Rate > &capRates, const std::vector< Rate > &floorRates)
YoYInflationCapFloor (Type type, const Leg &yoyLeg, const std::vector< Rate > &strikes)
virtual Rate atmRate (const YieldTermStructure &discountCurve) const
virtual Volatility impliedVolatility (Real price, const Handle< YoYInflationTermStructure > &yoyCurve, Volatility guess, Real accuracy=1.0e-4, Natural maxEvaluations=100, Volatility minVol=1.0e-7, Volatility maxVol=4.0) const
implied term volatility
Instrument interface
bool isExpired () const
returns whether the instrument might have value greater than zero.
void setupArguments (PricingEngine::arguments *) const
Inspectors
Type type () const
const std::vector< Rate > & capRates () const
const std::vector< Rate > & floorRates () const
const Leg & yoyLeg () const
Date startDate () const
Date maturityDate () const
boost::shared_ptr
< YoYInflationCoupon > lastYoYInflationCoupon () const
boost::shared_ptr
< YoYInflationCapFloor > optionlet (const Size n) const
Returns the n-th optionlet as a cap/floor with only one cash flow.
Private Attributes
Type type_
Leg yoyLeg_
std::vector< Rate > capRates_
std::vector< Rate > floorRates_
Detailed Description
Base class for yoy inflation cap-like instruments.
Note that the standard YoY inflation cap/floor defined here is different from nominal, because in nominal world standard cap/floors do not have the first optionlet. This is because they set in advance so there is no point. However, yoy inflation generally sets (effectively) in arrears, (actually in arrears vs lag of a few months) thus the first optionlet is relevant. Hence we can do a parity test without a special definition of the YoY cap/floor instrument.
Test:
the relationship between the values of caps, floors and the resulting collars is checked.
the put-call parity between the values of caps, floors and swaps is checked.
the correctness of the returned value is tested by checking it against a known good value.
Definition at line 55 of file inflationcapfloor.hpp.
Member Enumeration Documentation
enum QuantLib::YoYInflationCapFloor::Type
Enumerator:
Cap
Floor
Collar
Definition at line 57 of file inflationcapfloor.hpp.
{ Cap, Floor, Collar };
Constructor & Destructor Documentation
QuantLib::YoYInflationCapFloor::YoYInflationCapFloor (YoYInflationCapFloor::Type type, const Leg & yoyLeg, const std::vector< Rate > & capRates, const std::vector< Rate > & floorRates)
Definition at line 45 of file inflationcapfloor.cpp.
References capRates_, floorRates_, QuantLib::Singleton< Settings >::instance(), QL_REQUIRE, QuantLib::Observer::registerWith(), type_, and yoyLeg_.
Referenced by optionlet().
    : type_(type), yoyLeg_(yoyLeg),
    capRates_(capRates), floorRates_(floorRates) {
        if (type_ == Cap || type_ == Collar) {
            QL_REQUIRE(!capRates_.empty(), "no cap rates given");
            capRates_.reserve(yoyLeg_.size());
            while (capRates_.size() < yoyLeg_.size())
                capRates_.push_back(capRates_.back());
        }
        if (type_ == Floor || type_ == Collar) {
            QL_REQUIRE(!floorRates_.empty(), "no floor rates given");
            floorRates_.reserve(yoyLeg_.size());
            while (floorRates_.size() < yoyLeg_.size())
                floorRates_.push_back(floorRates_.back());
        }
        Leg::const_iterator i;
        for (i = yoyLeg_.begin(); i != yoyLeg_.end(); ++i)
            registerWith(*i);
        registerWith(Settings::instance().evaluationDate());
    }
QuantLib::YoYInflationCapFloor::YoYInflationCapFloor (YoYInflationCapFloor::Type type, const Leg & yoyLeg, const std::vector< Rate > & strikes)
Definition at line 70 of file inflationcapfloor.cpp.
References capRates_, floorRates_, QuantLib::Singleton< Settings >::instance(), QL_FAIL, QL_REQUIRE, QuantLib::Observer::registerWith(), type_, and yoyLeg_.
    : type_(type), yoyLeg_(yoyLeg) {
        QL_REQUIRE(!strikes.empty(), "no strikes given");
        if (type_ == Cap) {
            capRates_ = strikes;
            capRates_.reserve(yoyLeg_.size());
            while (capRates_.size() < yoyLeg_.size())
                capRates_.push_back(capRates_.back());
        } else if (type_ == Floor) {
            floorRates_ = strikes;
            floorRates_.reserve(yoyLeg_.size());
            while (floorRates_.size() < yoyLeg_.size())
                floorRates_.push_back(floorRates_.back());
        } else
            QL_FAIL("only Cap/Floor types allowed in this constructor");
        Leg::const_iterator i;
        for (i = yoyLeg_.begin(); i != yoyLeg_.end(); ++i)
            registerWith(*i);
        registerWith(Settings::instance().evaluationDate());
    }
Member Function Documentation
Rate QuantLib::YoYInflationCapFloor::atmRate (const YieldTermStructure & discountCurve) const [virtual]
Definition at line 216 of file inflationcapfloor.cpp.
References QuantLib::TermStructure::referenceDate(), and yoyLeg_.
{
        return CashFlows::atmRate(yoyLeg_, discountCurve,
                                  false, discountCurve.referenceDate());
    }
const std::vector<Rate>& QuantLib::YoYInflationCapFloor::capRates () const [inline]
Definition at line 75 of file inflationcapfloor.hpp.
References capRates_.
Referenced by optionlet().
{ return capRates_; }
const std::vector<Rate>& QuantLib::YoYInflationCapFloor::floorRates () const [inline]
Definition at line 76 of file inflationcapfloor.hpp.
References floorRates_.
Referenced by optionlet().
{ return floorRates_; }
Volatility QuantLib::YoYInflationCapFloor::impliedVolatility (Real price, const Handle< YoYInflationTermStructure > & yoyCurve, Volatility guess, Real accuracy = 1.0e-4, Natural maxEvaluations = 100, Volatility minVol = 1.0e-7, Volatility maxVol = 4.0) const [inline, virtual]
implied term volatility
Definition at line 163 of file inflationcapfloor.hpp.
References QL_FAIL.
{
            QL_FAIL("not implemented yet");
        }
bool QuantLib::YoYInflationCapFloor::isExpired () const [virtual]
returns whether the instrument might have value greater than zero.
Implements QuantLib::Instrument.
Definition at line 95 of file inflationcapfloor.cpp.
References yoyLeg_.
{
        for (Size i=yoyLeg_.size(); i>0; --i)
            if (!yoyLeg_[i-1]->hasOccurred())
                return false;
        return true;
    }
shared_ptr< YoYInflationCoupon > QuantLib::YoYInflationCapFloor::lastYoYInflationCoupon () const
Definition at line 111 of file inflationcapfloor.cpp.
References yoyLeg_.
{
        shared_ptr<CashFlow> lastCF(yoyLeg_.back());
        shared_ptr<YoYInflationCoupon> lastYoYInflationCoupon =
        boost::dynamic_pointer_cast<YoYInflationCoupon>(lastCF);
        return lastYoYInflationCoupon;
    }
Date QuantLib::YoYInflationCapFloor::maturityDate () const
Definition at line 106 of file inflationcapfloor.cpp.
References yoyLeg_.
{
        return CashFlows::maturityDate(yoyLeg_);
    }
shared_ptr< YoYInflationCapFloor > QuantLib::YoYInflationCapFloor::optionlet (const Size n) const
Returns the n-th optionlet as a cap/floor with only one cash flow.
Definition at line 118 of file inflationcapfloor.cpp.
References capRates(), floorRates(), QuantLib::io::ordinal(), QL_REQUIRE, type(), YoYInflationCapFloor(), and yoyLeg().
Referenced by InflationCapFloorTest::testConsistency().
{
        QL_REQUIRE(i < yoyLeg().size(),
                   io::ordinal(i+1) << " optionlet does not exist, only " <<
                   yoyLeg().size());
        Leg cf(1, yoyLeg()[i]);
        std::vector<Rate> cap, floor;
        if (type() == Cap || type() == Collar)
            cap.push_back(capRates()[i]);
        if (type() == Floor || type() == Collar)
            floor.push_back(floorRates()[i]);
        return shared_ptr<YoYInflationCapFloor>(new YoYInflationCapFloor(type(),
                                                    cf, cap, floor));
    }
void QuantLib::YoYInflationCapFloor::setupArguments (PricingEngine::arguments *) const [virtual]
When a derived argument structure is defined for an instrument, this method should be overridden to fill it. This is mandatory in case a pricing engine is used.
Reimplemented from QuantLib::Instrument.
Definition at line 134 of file inflationcapfloor.cpp.
References QuantLib::YoYInflationCapFloor::arguments::accrualTimes, QuantLib::YoYInflationCapFloor::arguments::capRates, capRates_, QuantLib::YoYInflationCapFloor::arguments::fixingDates, QuantLib::YoYInflationCapFloor::arguments::floorRates, floorRates_, QuantLib::YoYInflationCapFloor::arguments::gearings, QuantLib::YoYInflationCapFloor::arguments::nominals, QuantLib::YoYInflationCapFloor::arguments::payDates, QL_REQUIRE, QuantLib::YoYInflationCapFloor::arguments::spreads, QuantLib::YoYInflationCapFloor::arguments::startDates, QuantLib::YoYInflationCapFloor::arguments::type, type_, and yoyLeg_.
{
        YoYInflationCapFloor::arguments* arguments =
        dynamic_cast<YoYInflationCapFloor::arguments*>(args);
        QL_REQUIRE(arguments != 0, "wrong argument type");
        Size n = yoyLeg_.size();
        arguments->startDates.resize(n);
        arguments->fixingDates.resize(n);
        arguments->payDates.resize(n);
        arguments->accrualTimes.resize(n);
        arguments->nominals.resize(n);
        arguments->gearings.resize(n);
        arguments->capRates.resize(n);
        arguments->floorRates.resize(n);
        arguments->spreads.resize(n);
        arguments->type = type_;
        for (Size i=0; i<n; ++i) {
            shared_ptr<YoYInflationCoupon> coupon =
            boost::dynamic_pointer_cast<YoYInflationCoupon>(
                                                            yoyLeg_[i]);
            QL_REQUIRE(coupon, "non-YoYInflationCoupon given");
            arguments->startDates[i] = coupon->accrualStartDate();
            arguments->fixingDates[i] = coupon->fixingDate();
            arguments->payDates[i] = coupon->date();
            // this is passed explicitly for precision
            arguments->accrualTimes[i] = coupon->accrualPeriod();
            arguments->nominals[i] = coupon->nominal();
            Spread spread = coupon->spread();
            Real gearing = coupon->gearing();
            arguments->gearings[i] = gearing;
            arguments->spreads[i] = spread;
            if (type_ == Cap || type_ == Collar)
                arguments->capRates[i] = (capRates_[i]-spread)/gearing;
            else
                arguments->capRates[i] = Null<Rate>();
            if (type_ == Floor || type_ == Collar)
                arguments->floorRates[i] = (floorRates_[i]-spread)/gearing;
            else
                arguments->floorRates[i] = Null<Rate>();
        }
    }
Date QuantLib::YoYInflationCapFloor::startDate () const
Definition at line 102 of file inflationcapfloor.cpp.
References yoyLeg_.
{
        return CashFlows::startDate(yoyLeg_);
    }
Type QuantLib::YoYInflationCapFloor::type () const [inline]
Definition at line 74 of file inflationcapfloor.hpp.
References type_.
Referenced by optionlet().
{ return type_; }
const Leg& QuantLib::YoYInflationCapFloor::yoyLeg () const [inline]
Definition at line 77 of file inflationcapfloor.hpp.
References yoyLeg_.
Referenced by optionlet().
{ return yoyLeg_; }
Member Data Documentation
std::vector<Rate> QuantLib::YoYInflationCapFloor::capRates_ [private]
Definition at line 98 of file inflationcapfloor.hpp.
Referenced by capRates(), setupArguments(), and YoYInflationCapFloor().
std::vector<Rate> QuantLib::YoYInflationCapFloor::floorRates_ [private]
Definition at line 99 of file inflationcapfloor.hpp.
Referenced by floorRates(), setupArguments(), and YoYInflationCapFloor().
Type QuantLib::YoYInflationCapFloor::type_ [private]
Definition at line 96 of file inflationcapfloor.hpp.
Referenced by setupArguments(), type(), and YoYInflationCapFloor().
Leg QuantLib::YoYInflationCapFloor::yoyLeg_ [private]
Definition at line 97 of file inflationcapfloor.hpp.
Referenced by atmRate(), isExpired(), lastYoYInflationCoupon(), maturityDate(), setupArguments(), startDate(), YoYInflationCapFloor(), and yoyLeg().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/inflationcapfloor.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/inflationcapfloor.cpp