QuantLib: QuantLib::FloatingRateCoupon Class Reference
QuantLib::FloatingRateCoupon Class Reference
base floating-rate coupon class
#include <floatingratecoupon.hpp>
Public Member Functions
FloatingRateCoupon (const Date &paymentDate, Real nominal, const Date &startDate, const Date &endDate, Natural fixingDays, const boost::shared_ptr< InterestRateIndex > &index, Real gearing=1.0, Spread spread=0.0, const Date &refPeriodStart=Date(), const Date &refPeriodEnd=Date(), const DayCounter &dayCounter=DayCounter(), bool isInArrears=false)
void setPricer (const boost::shared_ptr< FloatingRateCouponPricer > &)
boost::shared_ptr
< FloatingRateCouponPricer > pricer () const
CashFlow interface
Real amount () const
returns the amount of the cash flow
Coupon interface
Rate rate () const
accrued rate
Real price (const Handle< YieldTermStructure > &discountingCurve) const
DayCounter dayCounter () const
day counter for accrual calculation
Real accruedAmount (const Date &) const
accrued amount at the given date
Inspectors
const boost::shared_ptr
< InterestRateIndex > & index () const
floating index
Natural fixingDays () const
fixing days
virtual Date fixingDate () const
fixing date
Real gearing () const
index gearing, i.e. multiplicative coefficient for the index
Spread spread () const
spread paid over the fixing of the underlying index
virtual Rate indexFixing () const
fixing of the underlying index
virtual Rate convexityAdjustment () const
convexity adjustment
virtual Rate adjustedFixing () const
convexity-adjusted fixing
bool isInArrears () const
whether or not the coupon fixes in arrears
Observer interface
void update ()
Visitability
virtual void accept (AcyclicVisitor &)
Protected Member Functions
Rate convexityAdjustmentImpl (Rate fixing) const
convexity adjustment for the given index fixing
Protected Attributes
boost::shared_ptr
< InterestRateIndex > index_
DayCounter dayCounter_
Natural fixingDays_
Real gearing_
Spread spread_
bool isInArrears_
boost::shared_ptr
< FloatingRateCouponPricer > pricer_
Detailed Description
base floating-rate coupon class
Definition at line 43 of file floatingratecoupon.hpp.
Constructor & Destructor Documentation
QuantLib::FloatingRateCoupon::FloatingRateCoupon (const Date & paymentDate, Real nominal, const Date & startDate, const Date & endDate, Natural fixingDays, const boost::shared_ptr< InterestRateIndex > & index, Real gearing = 1.0, Spread spread = 0.0, const Date & refPeriodStart = Date(), const Date & refPeriodEnd = Date(), const DayCounter & dayCounter = DayCounter(), bool isInArrears = false)
Definition at line 32 of file floatingratecoupon.cpp.
References dayCounter_, QuantLib::DayCounter::empty(), gearing_, index_, QuantLib::Singleton< Settings >::instance(), QL_REQUIRE, and QuantLib::Observer::registerWith().
    : Coupon(paymentDate, nominal,
             startDate, endDate, refPeriodStart, refPeriodEnd),
      index_(index), dayCounter_(dayCounter),
      fixingDays_(fixingDays==Null<Natural>() ? index->fixingDays() : fixingDays),
      gearing_(gearing), spread_(spread),
      isInArrears_(isInArrears)
    {
        QL_REQUIRE(gearing_!=0, "Null gearing not allowed");
        if (dayCounter_.empty())
            dayCounter_ = index_->dayCounter();
        registerWith(index_);
        registerWith(Settings::instance().evaluationDate());
    }
Member Function Documentation
void QuantLib::FloatingRateCoupon::accept (AcyclicVisitor & v) [inline, virtual]
Reimplemented from QuantLib::Coupon.
Reimplemented in QuantLib::CappedFlooredCmsCoupon, QuantLib::DigitalCoupon, QuantLib::CappedFlooredIborCoupon, QuantLib::CappedFlooredCoupon, QuantLib::SubPeriodsCoupon, QuantLib::RangeAccrualFloatersCoupon, QuantLib::AverageBMACoupon, QuantLib::OvernightIndexedCoupon, QuantLib::IborCoupon, QuantLib::CmsCoupon, QuantLib::DigitalCmsCoupon, and QuantLib::DigitalIborCoupon.
Definition at line 143 of file floatingratecoupon.hpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Visitor< T >::visit().
{
        Visitor<FloatingRateCoupon>* v1 =
            dynamic_cast<Visitor<FloatingRateCoupon>*>(&v);
        if (v1 != 0)
            v1->visit(*this);
        else
            Coupon::accept(v);
    }
Real QuantLib::FloatingRateCoupon::accruedAmount (const Date &) const [virtual]
accrued amount at the given date
Implements QuantLib::Coupon.
Definition at line 71 of file floatingratecoupon.cpp.
References QuantLib::Coupon::accrualEndDate_, QuantLib::Coupon::accrualStartDate_, dayCounter(), QuantLib::Coupon::nominal(), QuantLib::Coupon::paymentDate_, rate(), QuantLib::Coupon::refPeriodEnd_, QuantLib::Coupon::refPeriodStart_, and QuantLib::DayCounter::yearFraction().
{
        if (d <= accrualStartDate_ || d > paymentDate_) {
            return 0.0;
        } else {
            return nominal() * rate() *
                dayCounter().yearFraction(accrualStartDate_,
                                          std::min(d, accrualEndDate_),
                                          refPeriodStart_,
                                          refPeriodEnd_);
        }
    }
Rate QuantLib::FloatingRateCoupon::adjustedFixing () const [inline, virtual]
convexity-adjusted fixing
Definition at line 129 of file floatingratecoupon.hpp.
References gearing(), rate(), and spread().
Referenced by convexityAdjustmentImpl().
{
        return (rate()-spread())/gearing();
    }
Real QuantLib::FloatingRateCoupon::amount () const [inline, virtual]
returns the amount of the cash flow
Note:
The amount is not discounted, i.e., it is the actual amount paid at the cash flow date.
Implements QuantLib::CashFlow.
Definition at line 61 of file floatingratecoupon.hpp.
References QuantLib::Coupon::accrualPeriod(), QuantLib::Coupon::nominal(), and rate().
Referenced by price().
{ return rate() * accrualPeriod() * nominal(); }
Rate QuantLib::FloatingRateCoupon::convexityAdjustment () const [inline, virtual]
convexity adjustment
Reimplemented in QuantLib::DigitalCoupon, QuantLib::AverageBMACoupon, and QuantLib::CappedFlooredCoupon.
Definition at line 125 of file floatingratecoupon.hpp.
References convexityAdjustmentImpl(), and indexFixing().
{
        return convexityAdjustmentImpl(indexFixing());
    }
Rate QuantLib::FloatingRateCoupon::convexityAdjustmentImpl (Rate fixing) const [inline, protected]
convexity adjustment for the given index fixing
Definition at line 139 of file floatingratecoupon.hpp.
References adjustedFixing(), and gearing().
Referenced by convexityAdjustment().
{
        return (gearing() == 0.0 ? 0.0 : adjustedFixing()-fixing);
    }
DayCounter QuantLib::FloatingRateCoupon::dayCounter () const [inline, virtual]
day counter for accrual calculation
Implements QuantLib::Coupon.
Definition at line 68 of file floatingratecoupon.hpp.
References dayCounter_.
Referenced by accruedAmount().
{ return dayCounter_; }
Date QuantLib::FloatingRateCoupon::fixingDate () const [virtual]
fixing date
Reimplemented in QuantLib::OvernightIndexedCoupon, and QuantLib::AverageBMACoupon.
Definition at line 83 of file floatingratecoupon.cpp.
References QuantLib::Coupon::accrualEndDate_, QuantLib::Coupon::accrualStartDate_, QuantLib::Days, fixingDays_, index_, isInArrears_, and QuantLib::Preceding.
Referenced by QuantLib::BlackIborQuantoCouponPricer::adjustedFixing(), QuantLib::BlackIborCouponPricer::adjustedFixing(), QuantLib::GFunctionFactory::GFunctionExactYield::GFunctionExactYield(), QuantLib::GFunctionFactory::GFunctionWithShifts::GFunctionWithShifts(), QuantLib::IborCoupon::IborCoupon(), indexFixing(), QuantLib::HaganPricer::initialize(), QuantLib::BlackIborCouponPricer::optionletPrice(), QuantLib::DigitalCoupon::rate(), and RangeAccrualTest::testInfiniteRange().
{
        // if isInArrears_ fix at the end of period
        Date refDate = isInArrears_ ? accrualEndDate_ : accrualStartDate_;
        return index_->fixingCalendar().advance(refDate,
            -static_cast<Integer>(fixingDays_), Days, Preceding);
    }
Natural QuantLib::FloatingRateCoupon::fixingDays () const [inline]
fixing days
Definition at line 77 of file floatingratecoupon.hpp.
References fixingDays_.
Referenced by QuantLib::AverageBMACoupon::AverageBMACoupon(), QuantLib::RangeAccrualPricer::initialize(), and QuantLib::SubPeriodsPricer::initialize().
{ return fixingDays_; }
Real QuantLib::FloatingRateCoupon::gearing () const [inline]
index gearing, i.e. multiplicative coefficient for the index
Definition at line 81 of file floatingratecoupon.hpp.
References gearing_.
Referenced by adjustedFixing(), convexityAdjustmentImpl(), QuantLib::CappedFlooredCoupon::effectiveCap(), QuantLib::CappedFlooredCoupon::effectiveFloor(), QuantLib::BlackIborCouponPricer::initialize(), QuantLib::RangeAccrualPricer::initialize(), QuantLib::SubPeriodsPricer::initialize(), and QuantLib::HaganPricer::initialize().
{ return gearing_; }
const boost::shared_ptr< InterestRateIndex > & QuantLib::FloatingRateCoupon::index () const [inline]
floating index
Definition at line 121 of file floatingratecoupon.hpp.
References index_.
Referenced by QuantLib::BlackIborQuantoCouponPricer::adjustedFixing(), QuantLib::BlackIborCouponPricer::initialize(), QuantLib::RangeAccrualPricer::initialize(), and QuantLib::SubPeriodsPricer::initialize().
{
        return index_;
    }
Rate QuantLib::FloatingRateCoupon::indexFixing () const [virtual]
fixing of the underlying index
Reimplemented in QuantLib::AverageBMACoupon, and QuantLib::IborCoupon.
Definition at line 100 of file floatingratecoupon.cpp.
References fixingDate(), and index_.
Referenced by QuantLib::BlackIborQuantoCouponPricer::adjustedFixing(), QuantLib::BlackIborCouponPricer::adjustedFixing(), convexityAdjustment(), QuantLib::BlackIborCouponPricer::optionletPrice(), and QuantLib::RangeAccrualFloatersCoupon::priceWithoutOptionality().
{
        return index_->fixing(fixingDate());
    }
bool QuantLib::FloatingRateCoupon::isInArrears () const [inline]
whether or not the coupon fixes in arrears
Definition at line 91 of file floatingratecoupon.hpp.
References isInArrears_.
Referenced by QuantLib::BlackIborCouponPricer::adjustedFixing().
{ return isInArrears_; }
Real QuantLib::FloatingRateCoupon::price (const Handle< YieldTermStructure > & discountingCurve) const
Definition at line 96 of file floatingratecoupon.cpp.
References amount(), and QuantLib::Coupon::date().
Referenced by DigitalCouponTest::testAssetOrNothingDeepInTheMoney(), DigitalCouponTest::testAssetOrNothingDeepOutTheMoney(), DigitalCouponTest::testCallPutParity(), DigitalCouponTest::testCashOrNothingDeepInTheMoney(), DigitalCouponTest::testCashOrNothingDeepOutTheMoney(), RangeAccrualTest::testPriceMonotonicityWithRespectToLowerStrike(), RangeAccrualTest::testPriceMonotonicityWithRespectToUpperStrike(), and DigitalCouponTest::testReplicationType().
{
        return amount() * discountingCurve->discount(date());
    }
boost::shared_ptr< FloatingRateCouponPricer > QuantLib::FloatingRateCoupon::pricer () const [inline]
Definition at line 134 of file floatingratecoupon.hpp.
References pricer_.
Referenced by setPricer(), and QuantLib::DigitalCoupon::setPricer().
{
        return pricer_;
    }
Rate QuantLib::FloatingRateCoupon::rate () const [virtual]
accrued rate
Implements QuantLib::Coupon.
Reimplemented in QuantLib::DigitalCoupon, and QuantLib::CappedFlooredCoupon.
Definition at line 90 of file floatingratecoupon.cpp.
References pricer_, and QL_REQUIRE.
Referenced by accruedAmount(), adjustedFixing(), amount(), and RangeAccrualTest::testInfiniteRange().
{
        QL_REQUIRE(pricer_, "pricer not set");
        pricer_->initialize(*this);
        return pricer_->swapletRate();
    }
void QuantLib::FloatingRateCoupon::setPricer (const boost::shared_ptr< FloatingRateCouponPricer > & pricer)
Reimplemented in QuantLib::DigitalCoupon, and QuantLib::CappedFlooredCoupon.
Definition at line 61 of file floatingratecoupon.cpp.
References pricer(), pricer_, QuantLib::Observer::registerWith(), QuantLib::Observer::unregisterWith(), and update().
Referenced by QuantLib::AverageBMACoupon::AverageBMACoupon(), QuantLib::OvernightIndexedCoupon::OvernightIndexedCoupon(), RangeAccrualTest::testInfiniteRange(), RangeAccrualTest::testPriceMonotonicityWithRespectToLowerStrike(), RangeAccrualTest::testPriceMonotonicityWithRespectToUpperStrike(), and QuantLib::anonymous_namespace{couponpricer.cpp}::PricerSetter::visit().
{
        if (pricer_)
            unregisterWith(pricer_);
        pricer_ = pricer;
        if (pricer_)
            registerWith(pricer_);
        update();
    }
Spread QuantLib::FloatingRateCoupon::spread () const [inline]
spread paid over the fixing of the underlying index
Definition at line 83 of file floatingratecoupon.hpp.
References spread_.
Referenced by adjustedFixing(), QuantLib::CappedFlooredCoupon::effectiveCap(), QuantLib::CappedFlooredCoupon::effectiveFloor(), QuantLib::BlackIborCouponPricer::initialize(), QuantLib::RangeAccrualPricer::initialize(), QuantLib::SubPeriodsPricer::initialize(), and QuantLib::HaganPricer::initialize().
{ return spread_; }
void QuantLib::FloatingRateCoupon::update () [inline, virtual]
This method must be implemented in derived classes. An instance of Observer does not call this method directly: instead, it will be called by the observables the instance registered with when they need to notify any changes.
Implements QuantLib::Observer.
Reimplemented in QuantLib::DigitalCoupon, and QuantLib::CappedFlooredCoupon.
Definition at line 96 of file floatingratecoupon.hpp.
References QuantLib::Observable::notifyObservers().
Referenced by setPricer().
{ notifyObservers(); }
Member Data Documentation
DayCounter QuantLib::FloatingRateCoupon::dayCounter_ [protected]
Definition at line 110 of file floatingratecoupon.hpp.
Referenced by dayCounter(), and FloatingRateCoupon().
Natural QuantLib::FloatingRateCoupon::fixingDays_ [protected]
Definition at line 111 of file floatingratecoupon.hpp.
Referenced by fixingDate(), and fixingDays().
Real QuantLib::FloatingRateCoupon::gearing_ [protected]
Definition at line 112 of file floatingratecoupon.hpp.
Referenced by QuantLib::CappedFlooredCoupon::cap(), QuantLib::CappedFlooredCoupon::CappedFlooredCoupon(), FloatingRateCoupon(), QuantLib::CappedFlooredCoupon::floor(), gearing(), and QuantLib::RangeAccrualFloatersCoupon::priceWithoutOptionality().
boost::shared_ptr<InterestRateIndex> QuantLib::FloatingRateCoupon::index_ [protected]
Definition at line 109 of file floatingratecoupon.hpp.
Referenced by fixingDate(), FloatingRateCoupon(), QuantLib::IborCoupon::IborCoupon(), index(), QuantLib::IborCoupon::indexFixing(), indexFixing(), QuantLib::OvernightIndexedCoupon::indexFixings(), and QuantLib::AverageBMACoupon::indexFixings().
bool QuantLib::FloatingRateCoupon::isInArrears_ [protected]
Definition at line 114 of file floatingratecoupon.hpp.
Referenced by fixingDate(), QuantLib::IborCoupon::IborCoupon(), and isInArrears().
boost::shared_ptr<FloatingRateCouponPricer> QuantLib::FloatingRateCoupon::pricer_ [protected]
Definition at line 115 of file floatingratecoupon.hpp.
Referenced by pricer(), rate(), setPricer(), and QuantLib::DigitalCoupon::setPricer().
Spread QuantLib::FloatingRateCoupon::spread_ [protected]
Definition at line 113 of file floatingratecoupon.hpp.
Referenced by QuantLib::RangeAccrualFloatersCoupon::priceWithoutOptionality(), and spread().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/floatingratecoupon.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/floatingratecoupon.cpp