QuantLib: QuantLib::AnalyticDiscreteGeometricAverageStrikeAsianEngine Class Reference
QuantLib::AnalyticDiscreteGeometricAverageStrikeAsianEngine Class Reference
Pricing engine for European discrete geometric average-strike Asian option.
#include <analytic_discr_geom_av_strike.hpp>
Public Member Functions
AnalyticDiscreteGeometricAverageStrikeAsianEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > &process)
void calculate () const
Private Attributes
boost::shared_ptr
< GeneralizedBlackScholesProcess > process_
Detailed Description
Pricing engine for European discrete geometric average-strike Asian option.
This class implements a discrete geometric average-strike Asian option, with European exercise. The formula is from "Asian Option", E. Levy (1997) in "Exotic Options: The State of the Art", edited by L. Clewlow, C. Strickland, pag 65-97
Test:
the correctness of the returned value is tested by reproducing known good results.
Definition at line 45 of file analytic_discr_geom_av_strike.hpp.
Constructor & Destructor Documentation
QuantLib::AnalyticDiscreteGeometricAverageStrikeAsianEngine::AnalyticDiscreteGeometricAverageStrikeAsianEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > & process)
Definition at line 27 of file analytic_discr_geom_av_strike.cpp.
References process_, and QuantLib::Observer::registerWith().
    : process_(process) {
        registerWith(process_);
    }
Member Function Documentation
void QuantLib::AnalyticDiscreteGeometricAverageStrikeAsianEngine::calculate () const [virtual]
Implements QuantLib::PricingEngine.
Definition at line 33 of file analytic_discr_geom_av_strike.cpp.
References QuantLib::GenericEngine< DiscreteAveragingAsianOption::arguments, DiscreteAveragingAsianOption::results >::arguments_, QuantLib::DiscreteAveragingAsianOption::arguments::averageType, QuantLib::Option::Call, QuantLib::Continuous, QuantLib::Exercise::European, anonymous_namespace{interpolations.cpp}::f(), QuantLib::DiscreteAveragingAsianOption::arguments::fixingDates, QuantLib::Average::Geometric, anonymous_namespace{matrices.cpp}::N, QuantLib::NoFrequency, QuantLib::DiscreteAveragingAsianOption::arguments::pastFixings, process_, QuantLib::Option::Put, QL_FAIL, QL_REQUIRE, QuantLib::GenericEngine< DiscreteAveragingAsianOption::arguments, DiscreteAveragingAsianOption::results >::results_, QuantLib::DiscreteAveragingAsianOption::arguments::runningAccumulator, anonymous_namespace{quantlibbenchmark.cpp}::t, QuantLib::Instrument::results::value, QuantLib::io::volatility(), and QuantLib::DayCounter::yearFraction().
{
        QL_REQUIRE(arguments_.averageType == Average::Geometric,
                   "not a geometric average option");
        QL_REQUIRE(arguments_.exercise->type() == Exercise::European,
                   "not an European option");
        QL_REQUIRE(arguments_.runningAccumulator > 0.0,
                   "positive running product required: "
                   << arguments_.runningAccumulator << "not allowed");
        Real runningLog = std::log(arguments_.runningAccumulator);
        Size pastFixings = arguments_.pastFixings;
        QL_REQUIRE(pastFixings == 0, "past fixings currently not managed");
        boost::shared_ptr<PlainVanillaPayoff> payoff =
            boost::dynamic_pointer_cast<PlainVanillaPayoff>(arguments_.payoff);
        QL_REQUIRE(payoff, "non-plain payoff given");
        DayCounter rfdc  = process_->riskFreeRate()->dayCounter();
        DayCounter divdc = process_->dividendYield()->dayCounter();
        DayCounter voldc = process_->blackVolatility()->dayCounter();
        std::vector<Time> fixingTimes;
        for (Size i=0; i<arguments_.fixingDates.size(); i++) {
            if (arguments_.fixingDates[i]>=arguments_.fixingDates[0]) {
                Time t = voldc.yearFraction(arguments_.fixingDates[0],
                    arguments_.fixingDates[i]);
                fixingTimes.push_back(t);
            }
        }
        Size remainingFixings = fixingTimes.size();
        Size numberOfFixings = pastFixings + remainingFixings;
        Real N = static_cast<Real>(numberOfFixings);
        Real pastWeight   = pastFixings/N;
        Real futureWeight = 1.0-pastWeight;
        Time timeSum = std::accumulate(fixingTimes.begin(),
                                       fixingTimes.end(), 0.0);
        Time residualTime = rfdc.yearFraction(arguments_.fixingDates[pastFixings],
                                              arguments_.exercise->lastDate());
        Real underlying = process_->stateVariable()->value();
        QL_REQUIRE(underlying > 0.0, "positive underlying value required");
        Volatility volatility = process_->blackVolatility()->blackVol(
                                                arguments_.exercise->lastDate(),
                                                underlying);
        Date exDate = arguments_.exercise->lastDate();
        Rate dividendRate = process_->dividendYield()->
            zeroRate(exDate, divdc, Continuous, NoFrequency);
        Rate riskFreeRate = process_->riskFreeRate()->
            zeroRate(exDate, rfdc, Continuous, NoFrequency);
        Rate nu = riskFreeRate - dividendRate - 0.5*volatility*volatility;
        Real temp = 0.0;
        for (Size i=pastFixings+1; i<numberOfFixings; i++)
            temp += fixingTimes[i-pastFixings-1]*(N-i);
        Real variance = volatility*volatility /N/N * (timeSum + 2.0*temp);
        Real covarianceTerm = volatility*volatility/N * timeSum;
        Real sigmaSum_2 = variance + volatility*volatility*residualTime -
                                     2.0*covarianceTerm;
        Size M = (pastFixings == 0 ? 1 : pastFixings);
        Real runningLogAverage = runningLog/M;
        Real muG = pastWeight * runningLogAverage +
                   futureWeight * std::log(underlying) +
                   nu*timeSum/N;
        CumulativeNormalDistribution f;
        Real y1 = (std::log(underlying)+
                     (riskFreeRate-dividendRate)*residualTime-
                      muG - variance/2.0 + sigmaSum_2/2.0)
                      /std::sqrt(sigmaSum_2);
        Real y2 = y1-std::sqrt(sigmaSum_2);
        switch (payoff->optionType()) {
          case Option::Call:
            results_.value = underlying*std::exp(-dividendRate*residualTime)
                *f(y1)-
                std::exp(muG + variance/2.0 - riskFreeRate*residualTime)
                *f(y2);
            break;
          case Option::Put:
            results_.value = -underlying*std::exp(-dividendRate*residualTime)
                *f(-y1)+
                std::exp(muG + variance/2.0 - riskFreeRate*residualTime)
                *f(-y2);
            break;
          default:
            QL_FAIL("invalid option type");
        }
    }
Member Data Documentation
boost::shared_ptr<GeneralizedBlackScholesProcess> QuantLib::AnalyticDiscreteGeometricAverageStrikeAsianEngine::process_ [private]
Definition at line 52 of file analytic_discr_geom_av_strike.hpp.
Referenced by AnalyticDiscreteGeometricAverageStrikeAsianEngine(), and calculate().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/asian/analytic_discr_geom_av_strike.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/asian/analytic_discr_geom_av_strike.cpp