QuantLib: QuantLib::BoundaryConditionSchemeHelper Class Reference
QuantLib::BoundaryConditionSchemeHelper Class Reference
#include <boundaryconditionschemehelper.hpp>
Public Types
typedef OperatorTraits
< FdmLinearOp >::array_type array_type
typedef OperatorTraits
< FdmLinearOp >::operator_type operator_type
Public Member Functions
BoundaryConditionSchemeHelper (const OperatorTraits< FdmLinearOp >::bc_set &bcSet)
void applyBeforeApplying (operator_type &op) const
void applyBeforeSolving (operator_type &op, array_type &a) const
void applyAfterApplying (array_type &a) const
void applyAfterSolving (array_type &a) const
void setTime (Time t) const
Private Member Functions
BoundaryConditionSchemeHelper ()
Private Attributes
const OperatorTraits
< FdmLinearOp >::bc_set bcSet_
Detailed Description
Definition at line 30 of file boundaryconditionschemehelper.hpp.
Member Typedef Documentation
typedef OperatorTraits<FdmLinearOp>::array_type QuantLib::BoundaryConditionSchemeHelper::array_type
Definition at line 32 of file boundaryconditionschemehelper.hpp.
typedef OperatorTraits<FdmLinearOp>::operator_type QuantLib::BoundaryConditionSchemeHelper::operator_type
Definition at line 33 of file boundaryconditionschemehelper.hpp.
Constructor & Destructor Documentation
QuantLib::BoundaryConditionSchemeHelper::BoundaryConditionSchemeHelper (const OperatorTraits< FdmLinearOp >::bc_set & bcSet) [inline, explicit]
Definition at line 35 of file boundaryconditionschemehelper.hpp.
            : bcSet_(bcSet) {  }
QuantLib::BoundaryConditionSchemeHelper::BoundaryConditionSchemeHelper () [inline, private]
Definition at line 61 of file boundaryconditionschemehelper.hpp.
{}
Member Function Documentation
void QuantLib::BoundaryConditionSchemeHelper::applyAfterApplying (array_type & a) const [inline]
Definition at line 47 of file boundaryconditionschemehelper.hpp.
References bcSet_.
Referenced by QuantLib::CraigSneydScheme::step(), QuantLib::DouglasScheme::step(), QuantLib::ExplicitEulerScheme::step(), QuantLib::HundsdorferScheme::step(), and QuantLib::ModifiedCraigSneydScheme::step().
{
            for (Size i=0; i < bcSet_.size(); ++i)
                bcSet_[i]->applyAfterApplying(a);
        }
void QuantLib::BoundaryConditionSchemeHelper::applyAfterSolving (array_type & a) const [inline]
Definition at line 51 of file boundaryconditionschemehelper.hpp.
References bcSet_.
Referenced by QuantLib::CraigSneydScheme::step(), QuantLib::DouglasScheme::step(), QuantLib::ImplicitEulerScheme::step(), QuantLib::HundsdorferScheme::step(), and QuantLib::ModifiedCraigSneydScheme::step().
{
            for (Size i=0; i < bcSet_.size(); ++i)
                bcSet_[i]->applyAfterSolving(a);
        }
void QuantLib::BoundaryConditionSchemeHelper::applyBeforeApplying (operator_type & op) const [inline]
Definition at line 39 of file boundaryconditionschemehelper.hpp.
References bcSet_.
Referenced by QuantLib::CraigSneydScheme::step(), QuantLib::DouglasScheme::step(), QuantLib::ExplicitEulerScheme::step(), QuantLib::HundsdorferScheme::step(), and QuantLib::ModifiedCraigSneydScheme::step().
{
            for (Size i=0; i < bcSet_.size(); ++i)
                bcSet_[i]->applyBeforeApplying(op);
        }
void QuantLib::BoundaryConditionSchemeHelper::applyBeforeSolving (operator_type & op, array_type & a) const [inline]
Definition at line 43 of file boundaryconditionschemehelper.hpp.
References bcSet_.
Referenced by QuantLib::ImplicitEulerScheme::step().
{
            for (Size i=0; i < bcSet_.size(); ++i)
                bcSet_[i]->applyBeforeSolving(op, a);
        }
void QuantLib::BoundaryConditionSchemeHelper::setTime (Time t) const [inline]
Definition at line 55 of file boundaryconditionschemehelper.hpp.
References bcSet_.
Referenced by QuantLib::CraigSneydScheme::step(), QuantLib::DouglasScheme::step(), QuantLib::ExplicitEulerScheme::step(), QuantLib::ImplicitEulerScheme::step(), QuantLib::HundsdorferScheme::step(), and QuantLib::ModifiedCraigSneydScheme::step().
{
            for (Size i=0; i < bcSet_.size(); ++i)
                bcSet_[i]->setTime(t);
        }
Member Data Documentation
const OperatorTraits<FdmLinearOp>::bc_set QuantLib::BoundaryConditionSchemeHelper::bcSet_ [private]
Definition at line 62 of file boundaryconditionschemehelper.hpp.
Referenced by applyAfterApplying(), applyAfterSolving(), applyBeforeApplying(), applyBeforeSolving(), and setTime().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/schemes/boundaryconditionschemehelper.hpp