QuantLib: QuantLib::GaussKronrodNonAdaptive Class Reference
QuantLib::GaussKronrodNonAdaptive Class Reference
Integral of a 1-dimensional function using the Gauss-Kronrod methods.
#include <kronrodintegral.hpp>
Public Member Functions
GaussKronrodNonAdaptive (Real absoluteAccuracy, Size maxEvaluations, Real relativeAccuracy)
void setRelativeAccuracy (Real)
Real relativeAccuracy () const
Protected Member Functions
Real integrate (const boost::function< Real(Real)> &f, Real a, Real b) const
Private Attributes
Real relativeAccuracy_
Detailed Description
Integral of a 1-dimensional function using the Gauss-Kronrod methods.
This class provide a non-adaptive integration procedure which uses fixed Gauss-Kronrod abscissae to sample the integrand at a maximum of 87 points. It is provided for fast integration of smooth functions.
This function applies the Gauss-Kronrod 10-point, 21-point, 43-point and 87-point integration rules in succession until an estimate of the integral of f over (a, b) is achieved within the desired absolute and relative error limits, epsabs and epsrel. The function returns the final approximation, result, an estimate of the absolute error, abserr and the number of function evaluations used, neval. The Gauss-Kronrod rules are designed in such a way that each rule uses all the results of its predecessors, in order to minimize the total number of function evaluations.
Definition at line 52 of file kronrodintegral.hpp.
Constructor & Destructor Documentation
QuantLib::GaussKronrodNonAdaptive::GaussKronrodNonAdaptive (Real absoluteAccuracy, Size maxEvaluations, Real relativeAccuracy)
Definition at line 222 of file kronrodintegral.cpp.
    : Integrator(absoluteAccuracy, maxEvaluations),
      relativeAccuracy_(relativeAccuracy) {}
Member Function Documentation
Real QuantLib::GaussKronrodNonAdaptive::integrate (const boost::function< Real(Real)> & f, Real a, Real b) const [protected, virtual]
Implements QuantLib::Integrator.
Definition at line 229 of file kronrodintegral.cpp.
References anonymous_namespace{marketmodel.cpp}::a, QuantLib::Integrator::absoluteAccuracy(), anonymous_namespace{interpolations.cpp}::f(), QL_REQUIRE, relativeAccuracy(), QuantLib::rescaleError(), QuantLib::Integrator::setAbsoluteError(), QuantLib::Integrator::setNumberOfEvaluations(), QuantLib::w10, QuantLib::w21a, QuantLib::w21b, QuantLib::w43a, QuantLib::w43b, QuantLib::w87a, QuantLib::w87b, QuantLib::x1, QuantLib::x2, QuantLib::x3, and QuantLib::x4.
{
        Real result;
        //Size neval;
        Real fv1[5], fv2[5], fv3[5], fv4[5];
        Real savfun[21];  /* array of function values which have been computed */
        Real res10, res21, res43, res87;    /* 10, 21, 43 and 87 point results */
        Real err;
        Real resAbs; /* approximation to the integral of abs(f) */
        Real resasc; /* approximation to the integral of abs(f-i/(b-a)) */
        int k ;
        QL_REQUIRE(a<b, "b must be greater than a)");
        const Real halfLength = 0.5 * (b - a);
        const Real center = 0.5 * (b + a);
        const Real fCenter = f(center);
        // Compute the integral using the 10- and 21-point formula.
        res10 = 0;
        res21 = w21b[5] * fCenter;
        resAbs = w21b[5] * std::fabs(fCenter);
        for (k = 0; k < 5; k++) {
            Real abscissa = halfLength * x1[k];
            Real fval1 = f(center + abscissa);
            Real fval2 = f(center - abscissa);
            Real fval = fval1 + fval2;
            res10 += w10[k] * fval;
            res21 += w21a[k] * fval;
            resAbs += w21a[k] * (std::fabs(fval1) + std::fabs(fval2));
            savfun[k] = fval;
            fv1[k] = fval1;
            fv2[k] = fval2;
        }
        for (k = 0; k < 5; k++) {
            Real abscissa = halfLength * x2[k];
            Real fval1 = f(center + abscissa);
            Real fval2 = f(center - abscissa);
            Real fval = fval1 + fval2;
            res21 += w21b[k] * fval;
            resAbs += w21b[k] * (std::fabs(fval1) + std::fabs(fval2));
            savfun[k + 5] = fval;
            fv3[k] = fval1;
            fv4[k] = fval2;
        }
        result = res21 * halfLength;
        resAbs *= halfLength ;
        Real mean = 0.5 * res21;
        resasc = w21b[5] * std::fabs(fCenter - mean);
        for (k = 0; k < 5; k++)
            resasc += (w21a[k] * (std::fabs(fv1[k] - mean)
                        + std::fabs(fv2[k] - mean))
                        + w21b[k] * (std::fabs(fv3[k] - mean)
                        + std::fabs(fv4[k] - mean)));
        err = rescaleError ((res21 - res10) * halfLength, resAbs, resasc) ;
        resasc *= halfLength ;
        // test for convergence.
        if (err < absoluteAccuracy() || err < relativeAccuracy() * std::fabs(result)){
            setAbsoluteError(err);
            setNumberOfEvaluations(21);
            return result;
        }
        /* compute the integral using the 43-point formula. */
        res43 = w43b[11] * fCenter;
        for (k = 0; k < 10; k++)
            res43 += savfun[k] * w43a[k];
        for (k = 0; k < 11; k++){
            Real abscissa = halfLength * x3[k];
            Real fval = (f(center + abscissa)
                + f(center - abscissa));
            res43 += fval * w43b[k];
            savfun[k + 10] = fval;
            }
        // test for convergence.
        result = res43 * halfLength;
        err = rescaleError ((res43 - res21) * halfLength, resAbs, resasc);
       if (err < absoluteAccuracy() || err < relativeAccuracy() * std::fabs(result)){
            setAbsoluteError(err);
            setNumberOfEvaluations(43);
            return result;
        }
        /* compute the integral using the 87-point formula. */
        res87 = w87b[22] * fCenter;
        for (k = 0; k < 21; k++)
            res87 += savfun[k] * w87a[k];
        for (k = 0; k < 22; k++){
            Real abscissa = halfLength * x4[k];
            res87 += w87b[k] * (f(center + abscissa)
                + f(center - abscissa));
        }
        // test for convergence.
        result = res87 * halfLength ;
        err = rescaleError ((res87 - res43) * halfLength, resAbs, resasc);
        setAbsoluteError(err);
        setNumberOfEvaluations(87);
        return result;
    }
Real QuantLib::GaussKronrodNonAdaptive::relativeAccuracy () const
Definition at line 218 of file kronrodintegral.cpp.
References relativeAccuracy_.
Referenced by integrate().
{
        return relativeAccuracy_;
    }
void QuantLib::GaussKronrodNonAdaptive::setRelativeAccuracy (Real)
Member Data Documentation
Real QuantLib::GaussKronrodNonAdaptive::relativeAccuracy_ [private]
Definition at line 64 of file kronrodintegral.hpp.
Referenced by relativeAccuracy().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/integrals/kronrodintegral.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/math/integrals/kronrodintegral.cpp