QuantLib: QuantLib::CPILeg Class Reference
QuantLib::CPILeg Class Reference
Helper class building a sequence of capped/floored CPI coupons.
#include <cpicoupon.hpp>
Public Member Functions
CPILeg (const Schedule &schedule, const boost::shared_ptr< ZeroInflationIndex > &index, const Real baseCPI, const Period &observationLag)
CPILeg & withNotionals (Real notional)
CPILeg & withNotionals (const std::vector< Real > &notionals)
CPILeg & withFixedRates (Real fixedRate)
CPILeg & withFixedRates (const std::vector< Real > &fixedRates)
CPILeg & withPaymentDayCounter (const DayCounter &)
CPILeg & withPaymentAdjustment (BusinessDayConvention)
CPILeg & withFixingDays (Natural fixingDays)
CPILeg & withFixingDays (const std::vector< Natural > &fixingDays)
CPILeg & withObservationInterpolation (CPI::InterpolationType)
CPILeg & withSubtractInflationNominal (bool)
CPILeg & withSpreads (Spread spread)
CPILeg & withSpreads (const std::vector< Spread > &spreads)
CPILeg & withCaps (Rate cap)
CPILeg & withCaps (const std::vector< Rate > &caps)
CPILeg & withFloors (Rate floor)
CPILeg & withFloors (const std::vector< Rate > &floors)
operator Leg () const
Private Attributes
Schedule schedule_
boost::shared_ptr
< ZeroInflationIndex > index_
Real baseCPI_
Period observationLag_
std::vector< Real > notionals_
std::vector< Real > fixedRates_
DayCounter paymentDayCounter_
BusinessDayConvention paymentAdjustment_
std::vector< Natural > fixingDays_
CPI::InterpolationType observationInterpolation_
bool subtractInflationNominal_
std::vector< Spread > spreads_
std::vector< Rate > caps_
std::vector< Rate > floors_
Detailed Description
Helper class building a sequence of capped/floored CPI coupons.
Also allowing for the inflated notional at the end... especially if there is only one date in the schedule. If a fixedRate is zero you get a FixedRateCoupon, otherwise you get a ZeroInflationCoupon.
payoff is: spread + fixedRate x index
Definition at line 177 of file cpicoupon.hpp.
Constructor & Destructor Documentation
QuantLib::CPILeg::CPILeg (const Schedule & schedule, const boost::shared_ptr< ZeroInflationIndex > & index, const Real baseCPI, const Period & observationLag)
Definition at line 150 of file cpicoupon.cpp.
                                                                     :
    schedule_(schedule), index_(index),
    baseCPI_(baseCPI), observationLag_(observationLag),
    paymentDayCounter_(Thirty360()),
    paymentAdjustment_(ModifiedFollowing),
    fixingDays_(std::vector<Natural>(1,0)),
    observationInterpolation_(CPI::AsIndex),
    subtractInflationNominal_(true),
    spreads_(std::vector<Real>(1,0))
    {}
Member Function Documentation
QuantLib::CPILeg::operator Leg () const
Definition at line 245 of file cpicoupon.cpp.
References QuantLib::Calendar::adjust(), baseCPI_, QuantLib::Schedule::businessDayConvention(), QuantLib::Schedule::calendar(), anonymous_namespace{marketmodel.cpp}::calendar, caps_, QuantLib::Schedule::date(), QuantLib::detail::effectiveFixedRate(), fixedRates_, fixingDays_, floors_, QuantLib::detail::get(), index_, QuantLib::Schedule::isRegular(), QuantLib::detail::noOption(), notionals_, observationInterpolation_, observationLag_, paymentAdjustment_, paymentDayCounter_, QL_FAIL, QL_REQUIRE, schedule_, QuantLib::Schedule::size(), spreads_, subtractInflationNominal_, and QuantLib::Schedule::tenor().
{
        QL_REQUIRE(!notionals_.empty(), "no notional given");
        Size n = schedule_.size()-1;
        Calendar calendar = schedule_.calendar();
        Leg leg;
        leg.reserve(n+1);   // +1 for notional, we always have some sort ...
        if (n>0) {
            QL_REQUIRE(!fixedRates_.empty() || !spreads_.empty(),
                       "no fixedRates or spreads given");
            Date refStart, start, refEnd, end;
            for (Size i=0; i<n; ++i) {
                refStart = start = schedule_.date(i);
                refEnd   =   end = schedule_.date(i+1);
                Date paymentDate = calendar.adjust(end, paymentAdjustment_);
                if (i==0   && !schedule_.isRegular(i+1)) {
                    BusinessDayConvention bdc = schedule_.businessDayConvention();
                    refStart = schedule_.calendar().adjust(end - schedule_.tenor(), bdc);
                }
                if (i==n-1 && !schedule_.isRegular(i+1)) {
                    BusinessDayConvention bdc = schedule_.businessDayConvention();
                    refEnd = schedule_.calendar().adjust(start + schedule_.tenor(), bdc);
                }
                if (detail::get(fixedRates_, i, 1.0) == 0.0) { // fixed coupon
                    leg.push_back(boost::shared_ptr<CashFlow>
                                  (new FixedRateCoupon
                                   (paymentDate, detail::get(notionals_, i, 0.0),
                                    detail::effectiveFixedRate(spreads_,caps_,floors_,i),
                                    paymentDayCounter_, start, end, refStart, refEnd)));
                } else { // zero inflation coupon
                    if (detail::noOption(caps_, floors_, i)) { // just swaplet
                        boost::shared_ptr<CPICoupon> coup;
                        coup = boost::shared_ptr<CPICoupon>
                            (new CPICoupon(baseCPI_,    // all have same base for ratio
                                     paymentDate,
                                     detail::get(notionals_, i, 0.0),
                                     start, end,
                                     detail::get(fixingDays_, i, 0.0),
                                     index_, observationLag_,
                                     observationInterpolation_,
                                     paymentDayCounter_,
                                     detail::get(fixedRates_, i, 0.0),
                                     detail::get(spreads_, i, 0.0),
                                     refStart, refEnd));
                        // in this case you can set a pricer
                        // straight away because it only provides computation - not data
                        boost::shared_ptr<CPICouponPricer> pricer
                            (new CPICouponPricer);
                        coup->setPricer(pricer);
                        leg.push_back(boost::dynamic_pointer_cast<CashFlow>(coup));
                    } else  {     // cap/floorlet
                        QL_FAIL("caps/floors on CPI coupons not implemented.");
                    }
                }
            }
        }
        // in CPI legs you always have a notional flow of some sort
        Date paymentDate = calendar.adjust(schedule_.date(n), paymentAdjustment_);
        Date fixingDate = paymentDate - observationLag_;
        boost::shared_ptr<CashFlow> xnl(new CPICashFlow
                          (detail::get(notionals_, n, 0.0), index_,
                           Date(), // is fake, i.e. you do not have one
                           baseCPI_, fixingDate, paymentDate,
                           subtractInflationNominal_, observationInterpolation_,
                           index_->frequency())
                         );
        leg.push_back(xnl);
        return leg;
    }
CPILeg & QuantLib::CPILeg::withCaps (Rate cap)
Definition at line 224 of file cpicoupon.cpp.
References caps_.
{
        caps_ = std::vector<Rate>(1,cap);
        return *this;
    }
CPILeg & QuantLib::CPILeg::withCaps (const std::vector< Rate > & caps)
Definition at line 229 of file cpicoupon.cpp.
References caps_.
{
        caps_ = caps;
        return *this;
    }
CPILeg & QuantLib::CPILeg::withFixedRates (Real fixedRate)
Definition at line 169 of file cpicoupon.cpp.
References fixedRates_.
Referenced by QuantLib::CPIBond::CPIBond(), and QuantLib::CPISwap::CPISwap().
{
        fixedRates_ = std::vector<Real>(1,fixedRate);
        return *this;
    }
CPILeg & QuantLib::CPILeg::withFixedRates (const std::vector< Real > & fixedRates)
Definition at line 174 of file cpicoupon.cpp.
References fixedRates_.
{
        fixedRates_ =   fixedRates;
        return *this;
    }
CPILeg & QuantLib::CPILeg::withFixingDays (Natural fixingDays)
Definition at line 204 of file cpicoupon.cpp.
References fixingDays_.
{
        fixingDays_ = std::vector<Natural>(1,fixingDays);
        return *this;
    }
CPILeg & QuantLib::CPILeg::withFixingDays (const std::vector< Natural > & fixingDays)
Definition at line 209 of file cpicoupon.cpp.
References fixingDays_.
{
        fixingDays_ = fixingDays;
        return *this;
    }
CPILeg & QuantLib::CPILeg::withFloors (Rate floor)
Definition at line 234 of file cpicoupon.cpp.
References floors_.
{
        floors_ = std::vector<Rate>(1,floor);
        return *this;
    }
CPILeg & QuantLib::CPILeg::withFloors (const std::vector< Rate > & floors)
Definition at line 239 of file cpicoupon.cpp.
References floors_.
{
        floors_ = floors;
        return *this;
    }
CPILeg & QuantLib::CPILeg::withNotionals (Real notional)
Definition at line 179 of file cpicoupon.cpp.
References notionals_.
Referenced by QuantLib::CPIBond::CPIBond(), and QuantLib::CPISwap::CPISwap().
{
        notionals_ = std::vector<Real>(1,notional);
        return *this;
    }
CPILeg & QuantLib::CPILeg::withNotionals (const std::vector< Real > & notionals)
Definition at line 184 of file cpicoupon.cpp.
References notionals_.
{
        notionals_ = notionals;
        return *this;
    }
CPILeg & QuantLib::CPILeg::withObservationInterpolation (CPI::InterpolationType interp)
Definition at line 163 of file cpicoupon.cpp.
References observationInterpolation_.
Referenced by QuantLib::CPIBond::CPIBond(), and QuantLib::CPISwap::CPISwap().
{
        observationInterpolation_ = interp;
        return *this;
    }
CPILeg & QuantLib::CPILeg::withPaymentAdjustment (BusinessDayConvention convention)
Definition at line 199 of file cpicoupon.cpp.
References paymentAdjustment_.
Referenced by QuantLib::CPIBond::CPIBond(), and QuantLib::CPISwap::CPISwap().
{
        paymentAdjustment_ = convention;
        return *this;
    }
CPILeg & QuantLib::CPILeg::withPaymentDayCounter (const DayCounter & dayCounter)
Definition at line 194 of file cpicoupon.cpp.
References anonymous_namespace{marketmodel.cpp}::dayCounter, and paymentDayCounter_.
Referenced by QuantLib::CPIBond::CPIBond(), and QuantLib::CPISwap::CPISwap().
{
        paymentDayCounter_ = dayCounter;
        return *this;
    }
CPILeg & QuantLib::CPILeg::withSpreads (Spread spread)
Definition at line 214 of file cpicoupon.cpp.
References spreads_.
{
        spreads_ = std::vector<Spread>(1,spread);
        return *this;
    }
CPILeg & QuantLib::CPILeg::withSpreads (const std::vector< Spread > & spreads)
Definition at line 219 of file cpicoupon.cpp.
References spreads_.
{
        spreads_ = spreads;
        return *this;
    }
CPILeg & QuantLib::CPILeg::withSubtractInflationNominal (bool growthOnly)
Definition at line 189 of file cpicoupon.cpp.
References subtractInflationNominal_.
Referenced by QuantLib::CPIBond::CPIBond(), and QuantLib::CPISwap::CPISwap().
{
        subtractInflationNominal_ = growthOnly;
        return *this;
    }
Member Data Documentation
Real QuantLib::CPILeg::baseCPI_ [private]
Definition at line 204 of file cpicoupon.hpp.
Referenced by operator Leg().
std::vector<Rate> QuantLib::CPILeg::caps_ [private]
Definition at line 214 of file cpicoupon.hpp.
Referenced by operator Leg(), and withCaps().
std::vector<Real> QuantLib::CPILeg::fixedRates_ [private]
Definition at line 207 of file cpicoupon.hpp.
Referenced by operator Leg(), and withFixedRates().
std::vector<Natural> QuantLib::CPILeg::fixingDays_ [private]
Definition at line 210 of file cpicoupon.hpp.
Referenced by operator Leg(), and withFixingDays().
std::vector<Rate> QuantLib::CPILeg::floors_ [private]
Definition at line 214 of file cpicoupon.hpp.
Referenced by operator Leg(), and withFloors().
boost::shared_ptr<ZeroInflationIndex> QuantLib::CPILeg::index_ [private]
Definition at line 203 of file cpicoupon.hpp.
Referenced by operator Leg().
std::vector<Real> QuantLib::CPILeg::notionals_ [private]
Definition at line 206 of file cpicoupon.hpp.
Referenced by operator Leg(), and withNotionals().
CPI::InterpolationType QuantLib::CPILeg::observationInterpolation_ [private]
Definition at line 211 of file cpicoupon.hpp.
Referenced by operator Leg(), and withObservationInterpolation().
Period QuantLib::CPILeg::observationLag_ [private]
Definition at line 205 of file cpicoupon.hpp.
Referenced by operator Leg().
BusinessDayConvention QuantLib::CPILeg::paymentAdjustment_ [private]
Definition at line 209 of file cpicoupon.hpp.
Referenced by operator Leg(), and withPaymentAdjustment().
DayCounter QuantLib::CPILeg::paymentDayCounter_ [private]
Definition at line 208 of file cpicoupon.hpp.
Referenced by operator Leg(), and withPaymentDayCounter().
Schedule QuantLib::CPILeg::schedule_ [private]
Definition at line 202 of file cpicoupon.hpp.
Referenced by operator Leg().
std::vector<Spread> QuantLib::CPILeg::spreads_ [private]
Definition at line 213 of file cpicoupon.hpp.
Referenced by operator Leg(), and withSpreads().
bool QuantLib::CPILeg::subtractInflationNominal_ [private]
Definition at line 212 of file cpicoupon.hpp.
Referenced by operator Leg(), and withSubtractInflationNominal().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/cpicoupon.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/cpicoupon.cpp