QuantLib: QuantLib::FailureToPayEvent Class Reference
QuantLib::FailureToPayEvent Class Reference
#include <defaultevent.hpp>
Public Member Functions
FailureToPayEvent (const Date &creditEventDate, const Currency &curr, Seniority bondsSen, Real defaultedAmount, const Date &settleDate, const std::map< Seniority, Real > &recoveryRates)
FailureToPayEvent (const Date &creditEventDate, const Currency &curr, Seniority bondsSen, Real defaultedAmount, const Date &settleDate, Real recoveryRates)
Real amountDefaulted () const
bool matchesEventType (const boost::shared_ptr< DefaultType > &contractEvType) const
Private Attributes
Real defaultedAmount_
Detailed Description
Definition at line 198 of file defaultevent.hpp.
Constructor & Destructor Documentation
QuantLib::FailureToPayEvent::FailureToPayEvent (const Date & creditEventDate, const Currency & curr, Seniority bondsSen, Real defaultedAmount, const Date & settleDate, const std::map< Seniority, Real > & recoveryRates)
Definition at line 172 of file defaultevent.cpp.
    : DefaultEvent(creditEventDate,
                   DefaultType(AtomicDefault::FailureToPay,
                               Restructuring::XR),
                   curr,
                   bondsSen,
                   settleDate,
                   recoveryRates),
      defaultedAmount_(defaultedAmount) { }
QuantLib::FailureToPayEvent::FailureToPayEvent (const Date & creditEventDate, const Currency & curr, Seniority bondsSen, Real defaultedAmount, const Date & settleDate, Real recoveryRates)
Definition at line 189 of file defaultevent.cpp.
    : DefaultEvent(creditEventDate,
                   DefaultType(AtomicDefault::FailureToPay,
                               Restructuring::XR),
                   curr,
                   bondsSen,
                   settleDate,
                   recoveryRates),
      defaultedAmount_(defaultedAmount) { }
Member Function Documentation
Real QuantLib::FailureToPayEvent::amountDefaulted () const [inline]
Definition at line 214 of file defaultevent.hpp.
References defaultedAmount_.
{return defaultedAmount_;}
bool QuantLib::FailureToPayEvent::matchesEventType (const boost::shared_ptr< DefaultType > & contractEvType) const [virtual]
matches the event if this event would trigger a contract related to the requested event type. Notice the contractual event types are not neccesarily atomic. Notice it does not check seniority or currency only event type. typically used from Issuer
Reimplemented from QuantLib::DefaultEvent.
Definition at line 157 of file defaultevent.cpp.
References QuantLib::Settings::evaluationDate(), QuantLib::Event::hasOccurred(), and QuantLib::Singleton< Settings >::instance().
{
        boost::shared_ptr<FailureToPay> eveType =
            boost::dynamic_pointer_cast<FailureToPay>(contractEvType);
        // this chekcs the atomic types, no need to call parents method
        if(!eveType) return false;
        if(defaultedAmount_ < eveType->amountRequired()) return false;
        Date today = Settings::instance().evaluationDate();
        if(!this->hasOccurred(today - eveType->gracePeriod(), true))
            return false;
        return true;
    }
Member Data Documentation
Real QuantLib::FailureToPayEvent::defaultedAmount_ [private]
Definition at line 218 of file defaultevent.hpp.
Referenced by amountDefaulted().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/defaultevent.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/defaultevent.cpp