QuantLib: QuantLib::CotSwapToFwdAdapter Class Reference
QuantLib::CotSwapToFwdAdapter Class Reference
#include <cotswaptofwdadapter.hpp>
Public Member Functions
CotSwapToFwdAdapter (const boost::shared_ptr< MarketModel > &coterminalModel)
MarketModel interface
const std::vector< Rate > & initialRates () const
const std::vector< Spread > & displacements () const
const EvolutionDescription & evolution () const
Size numberOfRates () const
Size numberOfFactors () const
Size numberOfSteps () const
const Matrix & pseudoRoot (Size i) const
Private Attributes
boost::shared_ptr< MarketModel > coterminalModel_
Size numberOfFactors_
Size numberOfRates_
Size numberOfSteps_
std::vector< Rate > initialRates_
std::vector< Matrix > pseudoRoots_
Detailed Description
Definition at line 31 of file cotswaptofwdadapter.hpp.
Constructor & Destructor Documentation
QuantLib::CotSwapToFwdAdapter::CotSwapToFwdAdapter (const boost::shared_ptr< MarketModel > & coterminalModel)
Definition at line 30 of file cotswaptofwdadapter.cpp.
References coterminalModel_, QuantLib::SwapForwardMappings::coterminalSwapZedMatrix(), displacements(), QuantLib::CoterminalSwapCurveState::forwardRates(), initialRates_, QuantLib::inverse(), numberOfSteps_, QuantLib::io::ordinal(), pseudoRoots_, QL_REQUIRE, anonymous_namespace{marketmodel.cpp}::rateTimes, and QuantLib::CoterminalSwapCurveState::setOnCoterminalSwapRates().
    : coterminalModel_(ctModel),
      numberOfFactors_(ctModel->numberOfFactors()),
      numberOfRates_(ctModel->numberOfRates()),
      numberOfSteps_(ctModel->numberOfSteps()),
      pseudoRoots_(numberOfSteps_, Matrix(numberOfRates_, numberOfFactors_))
    {
        const std::vector<Spread>& displacements =
            coterminalModel_->displacements();
        for (Size i = 1; i<displacements.size(); ++i) {
            QL_REQUIRE(displacements[i]==displacements[0],
                       io::ordinal(i+1) << " displacement (" <<
                       displacements[i] << ") not equal to the previous ones"
                       " (" << displacements[0] << ")");
        }
        const std::vector<Time>& rateTimes =
            coterminalModel_->evolution().rateTimes();
        // we must ensure we step through all rateTimes
        const std::vector<Time>& evolutionTimes =
            coterminalModel_->evolution().evolutionTimes();
        for (Size i = 0;
             i<rateTimes.size() && rateTimes[i]<=evolutionTimes.back(); ++i) {
            QL_REQUIRE(std::find(evolutionTimes.begin(), evolutionTimes.end(),
                                 rateTimes[i])!=evolutionTimes.end(),
                                 "skipping " << io::ordinal(i+1) << " rate time");
        }
        CoterminalSwapCurveState cs(rateTimes);
        const std::vector<Rate>& initialCoterminalSwapRates =
            coterminalModel_->initialRates();
        cs.setOnCoterminalSwapRates(initialCoterminalSwapRates);
        initialRates_ = cs.forwardRates();
        Matrix zedMatrix = SwapForwardMappings::coterminalSwapZedMatrix(
            cs, displacements[0]);
        Matrix invertedZedMatrix = inverse(zedMatrix);
        const std::vector<Size>& alive =
            coterminalModel_->evolution().firstAliveRate();
        for (Size k = 0; k<numberOfSteps_; ++k) {
            pseudoRoots_[k]=invertedZedMatrix*coterminalModel_->pseudoRoot(k);
            for (Size i=0; i<alive[k]; ++i)
                std::fill(pseudoRoots_[k].row_begin(i),
                          pseudoRoots_[k].row_end(i),
                          0.0);
        }
    }
Member Function Documentation
const std::vector< Spread > & QuantLib::CotSwapToFwdAdapter::displacements () const [inline, virtual]
Implements QuantLib::MarketModel.
Definition at line 74 of file cotswaptofwdadapter.hpp.
References coterminalModel_.
Referenced by CotSwapToFwdAdapter().
{
        return coterminalModel_->displacements();
    }
const EvolutionDescription & QuantLib::CotSwapToFwdAdapter::evolution () const [inline, virtual]
Implements QuantLib::MarketModel.
Definition at line 79 of file cotswaptofwdadapter.hpp.
References coterminalModel_.
{
        return coterminalModel_->evolution();
    }
const std::vector< Rate > & QuantLib::CotSwapToFwdAdapter::initialRates () const [inline, virtual]
Implements QuantLib::MarketModel.
Definition at line 69 of file cotswaptofwdadapter.hpp.
References initialRates_.
{
        return initialRates_;
    }
Size QuantLib::CotSwapToFwdAdapter::numberOfFactors () const [inline, virtual]
Implements QuantLib::MarketModel.
Definition at line 87 of file cotswaptofwdadapter.hpp.
References coterminalModel_.
{
        return coterminalModel_->numberOfFactors();
    }
Size QuantLib::CotSwapToFwdAdapter::numberOfRates () const [inline, virtual]
Implements QuantLib::MarketModel.
Definition at line 83 of file cotswaptofwdadapter.hpp.
References coterminalModel_.
{
        return coterminalModel_->numberOfRates();
    }
Size QuantLib::CotSwapToFwdAdapter::numberOfSteps () const [inline, virtual]
Implements QuantLib::MarketModel.
Definition at line 91 of file cotswaptofwdadapter.hpp.
References coterminalModel_.
{
        return coterminalModel_->numberOfSteps();
    }
const Matrix & QuantLib::CotSwapToFwdAdapter::pseudoRoot (Size i) const [inline, virtual]
Implements QuantLib::MarketModel.
Definition at line 95 of file cotswaptofwdadapter.hpp.
References pseudoRoots_.
{
        return pseudoRoots_[i];
    }
Member Data Documentation
boost::shared_ptr<MarketModel> QuantLib::CotSwapToFwdAdapter::coterminalModel_ [private]
Definition at line 46 of file cotswaptofwdadapter.hpp.
Referenced by CotSwapToFwdAdapter(), displacements(), evolution(), numberOfFactors(), numberOfRates(), and numberOfSteps().
std::vector<Rate> QuantLib::CotSwapToFwdAdapter::initialRates_ [private]
Definition at line 48 of file cotswaptofwdadapter.hpp.
Referenced by CotSwapToFwdAdapter(), and initialRates().
Size QuantLib::CotSwapToFwdAdapter::numberOfFactors_ [private]
Definition at line 47 of file cotswaptofwdadapter.hpp.
Size QuantLib::CotSwapToFwdAdapter::numberOfRates_ [private]
Definition at line 47 of file cotswaptofwdadapter.hpp.
Size QuantLib::CotSwapToFwdAdapter::numberOfSteps_ [private]
Definition at line 47 of file cotswaptofwdadapter.hpp.
Referenced by CotSwapToFwdAdapter().
std::vector<Matrix> QuantLib::CotSwapToFwdAdapter::pseudoRoots_ [private]
Definition at line 49 of file cotswaptofwdadapter.hpp.
Referenced by CotSwapToFwdAdapter(), and pseudoRoot().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/models/cotswaptofwdadapter.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/models/cotswaptofwdadapter.cpp