QuantLib: QuantLib::CalibratedModel Class Reference
QuantLib::CalibratedModel Class Reference
Calibrated model class.
#include <model.hpp>
Classes
class CalibrationFunction
class PrivateConstraint
Public Member Functions
CalibratedModel (Size nArguments)
void update ()
void calibrate (const std::vector< boost::shared_ptr< CalibrationHelper > > &, OptimizationMethod &method, const EndCriteria &endCriteria, const Constraint &constraint=Constraint(), const std::vector< Real > &weights=std::vector< Real >())
Calibrate to a set of market instruments (caps/swaptions)
Real value (const Array &params, const std::vector< boost::shared_ptr< CalibrationHelper > > &)
const boost::shared_ptr
< Constraint > & constraint () const
EndCriteria::Type endCriteria ()
returns end criteria result
Disposable< Array > params () const
Returns array of arguments on which calibration is done.
virtual void setParams (const Array &params)
Protected Member Functions
virtual void generateArguments ()
Protected Attributes
std::vector< Parameter > arguments_
boost::shared_ptr< Constraint > constraint_
EndCriteria::Type shortRateEndCriteria_
Friends
class CalibrationFunction
Detailed Description
Calibrated model class.
Definition at line 79 of file model.hpp.
Constructor & Destructor Documentation
QuantLib::CalibratedModel::CalibratedModel (Size nArguments)
Definition at line 29 of file model.cpp.
    : arguments_(nArguments),
      constraint_(new PrivateConstraint(arguments_)),
      shortRateEndCriteria_(EndCriteria::None) {}
Member Function Documentation
void QuantLib::CalibratedModel::calibrate (const std::vector< boost::shared_ptr< CalibrationHelper > > & instruments, OptimizationMethod & method, const EndCriteria & endCriteria, const Constraint & constraint = Constraint(), const std::vector< Real > & weights = std::vector<Real>())
Calibrate to a set of market instruments (caps/swaptions)
An additional constraint can be passed which must be satisfied in addition to the constraints of the model.
Definition at line 77 of file model.cpp.
References anonymous_namespace{marketmodel.cpp}::c, constraint_, QuantLib::Problem::currentValue(), QuantLib::Constraint::empty(), anonymous_namespace{interpolations.cpp}::f(), QuantLib::OptimizationMethod::minimize(), QuantLib::Observable::notifyObservers(), params(), QL_REQUIRE, setParams(), shortRateEndCriteria_, QuantLib::Problem::values(), and anonymous_namespace{stats.cpp}::weights.
{
        QL_REQUIRE(weights.empty() ||
                   weights.size() == instruments.size(),
                   "mismatch between number of instruments and weights");
        Constraint c;
        if (additionalConstraint.empty())
            c = *constraint_;
        else
            c = CompositeConstraint(*constraint_,additionalConstraint);
        std::vector<Real> w = weights.empty() ?
                              std::vector<Real>(instruments.size(), 1.0):
                              weights;
        CalibrationFunction f(this, instruments, w);
        Problem prob(f, c, params());
        shortRateEndCriteria_ = method.minimize(prob, endCriteria);
        Array result(prob.currentValue());
        setParams(result);
        Array shortRateProblemValues_ = prob.values(result);
        notifyObservers();
    }
const boost::shared_ptr< Constraint > & QuantLib::CalibratedModel::constraint () const [inline]
Definition at line 135 of file model.hpp.
References constraint_.
{
        return constraint_;
    }
EndCriteria::Type QuantLib::CalibratedModel::endCriteria ()
returns end criteria result
Definition at line 107 of file model.cpp.
References shortRateEndCriteria_.
{
        return shortRateEndCriteria_;
    }
virtual void QuantLib::CalibratedModel::generateArguments () [inline, protected, virtual]
Reimplemented in QuantLib::G2, QuantLib::HullWhite, QuantLib::GJRGARCHModel, QuantLib::ExtendedCoxIngersollRoss, QuantLib::HestonModel, QuantLib::VarianceGammaModel, and QuantLib::BatesModel.
Definition at line 111 of file model.hpp.
Referenced by update().
{}
Disposable< Array > QuantLib::CalibratedModel::params () const
Returns array of arguments on which calibration is done.
Definition at line 118 of file model.cpp.
References arguments_.
Referenced by calibrate().
{
        Size size = 0, i;
        for (i=0; i<arguments_.size(); i++)
            size += arguments_[i].size();
        Array params(size);
        Size k = 0;
        for (i=0; i<arguments_.size(); i++) {
            for (Size j=0; j<arguments_[i].size(); j++, k++) {
                params[k] = arguments_[i].params()[j];
            }
        }
        return params;
    }
void QuantLib::CalibratedModel::setParams (const Array & params) [virtual]
Reimplemented in QuantLib::LiborForwardModel.
Definition at line 132 of file model.cpp.
References arguments_, QuantLib::Array::begin(), QuantLib::Array::end(), QL_REQUIRE, and update().
Referenced by calibrate().
{
        Array::const_iterator p = params.begin();
        for (Size i=0; i<arguments_.size(); ++i) {
            for (Size j=0; j<arguments_[i].size(); ++j, ++p) {
                QL_REQUIRE(p!=params.end(),"parameter array too small");
                arguments_[i].setParam(j, *p);
            }
        }
        QL_REQUIRE(p==params.end(),"parameter array too big!");
        update();
    }
void QuantLib::CalibratedModel::update () [inline, virtual]
This method must be implemented in derived classes. An instance of Observer does not call this method directly: instead, it will be called by the observables the instance registered with when they need to notify any changes.
Implements QuantLib::Observer.
Definition at line 83 of file model.hpp.
References generateArguments(), and QuantLib::Observable::notifyObservers().
Referenced by setParams().
                      {
            generateArguments();
            notifyObservers();
        }
Real QuantLib::CalibratedModel::value (const Array & params, const std::vector< boost::shared_ptr< CalibrationHelper > > & instruments)
Definition at line 111 of file model.cpp.
References anonymous_namespace{interpolations.cpp}::f(), and QuantLib::CalibratedModel::CalibrationFunction::value().
Referenced by QuantLib::CoxIngersollRoss::A(), QuantLib::ExtendedCoxIngersollRoss::A(), QuantLib::HullWhite::A(), QuantLib::CoxIngersollRoss::B(), QuantLib::BlackKarasinski::Helper::operator()(), QuantLib::OneFactorModel::ShortRateTree::Helper::operator()(), QuantLib::GeneralizedHullWhite::Helper::operator()(), QuantLib::G2::SwaptionPricingFunction::operator()(), QuantLib::G2::SwaptionPricingFunction::SolvingFunction::operator()(), QuantLib::OneFactorModel::ShortRateTree::ShortRateTree(), QuantLib::G2::sigmaP(), QuantLib::BlackKarasinski::tree(), QuantLib::HullWhite::tree(), QuantLib::GeneralizedHullWhite::tree(), and QuantLib::G2::V().
{
        std::vector<Real> w = std::vector<Real>(instruments.size(), 1.0);
        CalibrationFunction f(this, instruments, w);
        return f.value(params);
    }
Friends And Related Function Documentation
friend class CalibrationFunction [friend]
Definition at line 120 of file model.hpp.
Member Data Documentation
std::vector<Parameter> QuantLib::CalibratedModel::arguments_ [protected]
Definition at line 112 of file model.hpp.
Referenced by QuantLib::GJRGARCHModel::alpha(), QuantLib::BatesDetJumpModel::BatesDetJumpModel(), QuantLib::BatesDoubleExpDetJumpModel::BatesDoubleExpDetJumpModel(), QuantLib::BatesDoubleExpModel::BatesDoubleExpModel(), QuantLib::BatesModel::BatesModel(), QuantLib::GJRGARCHModel::beta(), QuantLib::BatesModel::delta(), QuantLib::GJRGARCHModel::gamma(), QuantLib::GJRGARCHModel::GJRGARCHModel(), QuantLib::HestonModel::HestonModel(), QuantLib::HestonModel::kappa(), QuantLib::PiecewiseTimeDependentHestonModel::kappa(), QuantLib::BatesDetJumpModel::kappaLambda(), QuantLib::BatesDoubleExpDetJumpModel::kappaLambda(), QuantLib::BatesModel::lambda(), QuantLib::GJRGARCHModel::lambda(), QuantLib::BatesDoubleExpModel::lambda(), QuantLib::LiborForwardModel::LiborForwardModel(), QuantLib::BatesModel::nu(), QuantLib::VarianceGammaModel::nu(), QuantLib::BatesDoubleExpModel::nuDown(), QuantLib::BatesDoubleExpModel::nuUp(), QuantLib::GJRGARCHModel::omega(), QuantLib::BatesDoubleExpModel::p(), params(), QuantLib::PiecewiseTimeDependentHestonModel::PiecewiseTimeDependentHestonModel(), QuantLib::HestonModel::rho(), QuantLib::PiecewiseTimeDependentHestonModel::rho(), QuantLib::LiborForwardModel::setParams(), setParams(), QuantLib::VarianceGammaModel::sigma(), QuantLib::HestonModel::sigma(), QuantLib::PiecewiseTimeDependentHestonModel::sigma(), QuantLib::HestonModel::theta(), QuantLib::VarianceGammaModel::theta(), QuantLib::PiecewiseTimeDependentHestonModel::theta(), QuantLib::BatesDetJumpModel::thetaLambda(), QuantLib::BatesDoubleExpDetJumpModel::thetaLambda(), QuantLib::HestonModel::v0(), QuantLib::GJRGARCHModel::v0(), QuantLib::PiecewiseTimeDependentHestonModel::v0(), and QuantLib::VarianceGammaModel::VarianceGammaModel().
boost::shared_ptr<Constraint> QuantLib::CalibratedModel::constraint_ [protected]
Definition at line 113 of file model.hpp.
Referenced by calibrate(), constraint(), and QuantLib::GJRGARCHModel::GJRGARCHModel().
EndCriteria::Type QuantLib::CalibratedModel::shortRateEndCriteria_ [protected]
Definition at line 114 of file model.hpp.
Referenced by calibrate(), and endCriteria().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/model.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/model.cpp