QuantLib: QuantLib::DiscretizedSwaption Class Reference
QuantLib::DiscretizedSwaption Class Reference
#include <discretizedswaption.hpp>
Public Member Functions
DiscretizedSwaption (const Swaption::arguments &, const Date &referenceDate, const DayCounter &dayCounter)
void reset (Size size)
Private Attributes
Swaption::arguments arguments_
Time lastPayment_
Detailed Description
Definition at line 33 of file discretizedswaption.hpp.
Constructor & Destructor Documentation
QuantLib::DiscretizedSwaption::DiscretizedSwaption (const Swaption::arguments & args, const Date & referenceDate, const DayCounter & dayCounter)
Definition at line 38 of file discretizedswaption.cpp.
References arguments_, QuantLib::Option::arguments::exercise, QuantLib::DiscretizedOption::exerciseTimes_, QuantLib::VanillaSwap::arguments::fixedPayDates, QuantLib::VanillaSwap::arguments::fixedResetDates, QuantLib::VanillaSwap::arguments::floatingPayDates, QuantLib::VanillaSwap::arguments::floatingResetDates, lastPayment_, QuantLib::DiscretizedOption::underlying_, QuantLib::anonymous_namespace{discretizedcallablefixedratebond.cpp}::withinNextWeek(), QuantLib::anonymous_namespace{discretizedcallablefixedratebond.cpp}::withinPreviousWeek(), and QuantLib::DayCounter::yearFraction().
    : DiscretizedOption(boost::shared_ptr<DiscretizedAsset>(),
                        args.exercise->type(),
                        std::vector<Time>()),
      arguments_(args) {
        exerciseTimes_.resize(arguments_.exercise->dates().size());
        for (Size i=0; i<exerciseTimes_.size(); ++i)
            exerciseTimes_[i] =
                dayCounter.yearFraction(referenceDate,
                                        arguments_.exercise->date(i));
        // Date adjustments can get time vectors out of synch.
        // Here, we try and collapse similar dates which could cause
        // a mispricing.
        for (Size i=0; i<arguments_.exercise->dates().size(); i++) {
            Date exerciseDate = arguments_.exercise->date(i);
            for (Size j=0; j<arguments_.fixedPayDates.size(); j++) {
                if (withinNextWeek(exerciseDate,
                                   arguments_.fixedPayDates[j])
                    // coupons in the future are dealt with below
                    && arguments_.fixedResetDates[j] < referenceDate)
                    arguments_.fixedPayDates[j] = exerciseDate;
            }
            for (Size j=0; j<arguments_.fixedResetDates.size(); j++) {
                if (withinPreviousWeek(exerciseDate,
                                       arguments_.fixedResetDates[j]))
                    arguments_.fixedResetDates[j] = exerciseDate;
            }
            for (Size j=0; j<arguments_.floatingResetDates.size(); j++) {
                if (withinPreviousWeek(exerciseDate,
                                       arguments_.floatingResetDates[j]))
                    arguments_.floatingResetDates[j] = exerciseDate;
            }
        }
        Time lastFixedPayment =
            dayCounter.yearFraction(referenceDate,
                                    arguments_.fixedPayDates.back());
        Time lastFloatingPayment =
            dayCounter.yearFraction(referenceDate,
                                    arguments_.floatingPayDates.back());
        lastPayment_ = std::max(lastFixedPayment,lastFloatingPayment);
        underlying_ = boost::shared_ptr<DiscretizedAsset>(
                                            new DiscretizedSwap(arguments_,
                                                                referenceDate,
                                                                dayCounter));
    }
Member Function Documentation
void QuantLib::DiscretizedSwaption::reset (Size size) [virtual]
This method should initialize the asset values to an Array of the given size and with values depending on the particular asset.
Reimplemented from QuantLib::DiscretizedOption.
Definition at line 90 of file discretizedswaption.cpp.
References lastPayment_, QuantLib::DiscretizedAsset::method(), and QuantLib::DiscretizedOption::underlying_.
{
        underlying_->initialize(method(), lastPayment_);
        DiscretizedOption::reset(size);
    }
Member Data Documentation
Swaption::arguments QuantLib::DiscretizedSwaption::arguments_ [private]
Definition at line 40 of file discretizedswaption.hpp.
Referenced by DiscretizedSwaption().
Time QuantLib::DiscretizedSwaption::lastPayment_ [private]
Definition at line 41 of file discretizedswaption.hpp.
Referenced by DiscretizedSwaption(), and reset().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/swaption/discretizedswaption.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/swaption/discretizedswaption.cpp