QuantLib: QuantLib::anonymous_namespace{cashflows.cpp}::ZSpreadFinder Class Reference
QuantLib::anonymous_namespace{cashflows.cpp}::ZSpreadFinder Class Reference
Public Member Functions
ZSpreadFinder (const Leg &leg, const shared_ptr< YieldTermStructure > &discountCurve, Real npv, const DayCounter &dc, Compounding comp, Frequency freq, bool includeSettlementDateFlows, Date settlementDate, Date npvDate)
Real operator() (Rate zSpread) const
Private Attributes
const Leg & leg_
Real npv_
shared_ptr< SimpleQuote > zSpread_
ZeroSpreadedTermStructure curve_
bool includeSettlementDateFlows_
Date settlementDate_
Date npvDate_
Detailed Description
Definition at line 1076 of file cashflows.cpp.
Constructor & Destructor Documentation
QuantLib::anonymous_namespace{cashflows.cpp}::ZSpreadFinder::ZSpreadFinder (const Leg & leg, const shared_ptr< YieldTermStructure > & discountCurve, Real npv, const DayCounter & dc, Compounding comp, Frequency freq, bool includeSettlementDateFlows, Date settlementDate, Date npvDate) [inline]
Definition at line 1078 of file cashflows.cpp.
References QuantLib::Settings::evaluationDate(), QuantLib::Singleton< Settings >::instance(), and QL_REQUIRE.
            : leg_(leg), npv_(npv), zSpread_(new SimpleQuote(0.0)),
              curve_(Handle<YieldTermStructure>(discountCurve),
                     Handle<Quote>(zSpread_), comp, freq, dc),
              includeSettlementDateFlows_(includeSettlementDateFlows),
              settlementDate_(settlementDate),
              npvDate_(npvDate) {
                QL_REQUIRE(!leg.empty(), "empty leg");
                if (settlementDate == Date())
                    settlementDate = Settings::instance().evaluationDate();
                if (npvDate == Date())
                    npvDate = settlementDate;
                // if the discount curve allows extrapolation, let's
                // the spreaded curve do too.
                curve_.enableExtrapolation(
                                  discountCurve->allowsExtrapolation());
            }
Member Function Documentation
Real QuantLib::anonymous_namespace{cashflows.cpp}::ZSpreadFinder::operator() (Rate zSpread) const [inline]
Definition at line 1106 of file cashflows.cpp.
References QuantLib::CashFlows::npv().
{
                zSpread_->setValue(zSpread);
                Real NPV = CashFlows::npv(leg_, curve_,
                                          includeSettlementDateFlows_,
                                          settlementDate_, npvDate_);
                return npv_ - NPV;
            }
Member Data Documentation
ZeroSpreadedTermStructure QuantLib::anonymous_namespace{cashflows.cpp}::ZSpreadFinder::curve_ [private]
Definition at line 1117 of file cashflows.cpp.
bool QuantLib::anonymous_namespace{cashflows.cpp}::ZSpreadFinder::includeSettlementDateFlows_ [private]
Definition at line 1118 of file cashflows.cpp.
const Leg& QuantLib::anonymous_namespace{cashflows.cpp}::ZSpreadFinder::leg_ [private]
Definition at line 1114 of file cashflows.cpp.
Real QuantLib::anonymous_namespace{cashflows.cpp}::ZSpreadFinder::npv_ [private]
Definition at line 1115 of file cashflows.cpp.
Date QuantLib::anonymous_namespace{cashflows.cpp}::ZSpreadFinder::npvDate_ [private]
Definition at line 1119 of file cashflows.cpp.
Date QuantLib::anonymous_namespace{cashflows.cpp}::ZSpreadFinder::settlementDate_ [private]
Definition at line 1119 of file cashflows.cpp.
shared_ptr<SimpleQuote> QuantLib::anonymous_namespace{cashflows.cpp}::ZSpreadFinder::zSpread_ [private]
Definition at line 1116 of file cashflows.cpp.
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/cashflows.cpp