QuantLib: QuantLib::AnalyticContinuousGeometricAveragePriceAsianEngine Class Reference
QuantLib::AnalyticContinuousGeometricAveragePriceAsianEngine Class Reference
Pricing engine for European continuous geometric average price Asian.
#include <analytic_cont_geom_av_price.hpp>
Public Member Functions
AnalyticContinuousGeometricAveragePriceAsianEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > &process)
void calculate () const
Private Attributes
boost::shared_ptr
< GeneralizedBlackScholesProcess > process_
Detailed Description
Pricing engine for European continuous geometric average price Asian.
This class implements a continuous geometric average price Asian option with European exercise. The formula is from "Option Pricing Formulas", E. G. Haug (1997) pag 96-97.
Test:
the correctness of the returned value is tested by reproducing results available in literature, and results obtained using a discrete average approximation.
the correctness of the returned greeks is tested by reproducing numerical derivatives.
Todo:
handle seasoned options
Definition at line 49 of file analytic_cont_geom_av_price.hpp.
Constructor & Destructor Documentation
QuantLib::AnalyticContinuousGeometricAveragePriceAsianEngine::AnalyticContinuousGeometricAveragePriceAsianEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > & process)
Definition at line 29 of file analytic_cont_geom_av_price.cpp.
References process_, and QuantLib::Observer::registerWith().
    : process_(process) {
        registerWith(process_);
    }
Member Function Documentation
void QuantLib::AnalyticContinuousGeometricAveragePriceAsianEngine::calculate () const [virtual]
Implements QuantLib::PricingEngine.
Definition at line 35 of file analytic_cont_geom_av_price.cpp.
References QuantLib::GenericEngine< ContinuousAveragingAsianOption::arguments, ContinuousAveragingAsianOption::results >::arguments_, QuantLib::ContinuousAveragingAsianOption::arguments::averageType, QuantLib::Continuous, QuantLib::BlackCalculator::delta(), QuantLib::BlackCalculator::dividendRho(), QuantLib::Exercise::European, QuantLib::BlackCalculator::gamma(), QuantLib::Average::Geometric, QuantLib::NoFrequency, process_, QL_REQUIRE, QuantLib::GenericEngine< ContinuousAveragingAsianOption::arguments, ContinuousAveragingAsianOption::results >::results_, QuantLib::BlackCalculator::rho(), QuantLib::BlackCalculator::theta(), QuantLib::BlackCalculator::value(), QuantLib::Instrument::results::value, QuantLib::BlackCalculator::vega(), QuantLib::io::volatility(), and QuantLib::DayCounter::yearFraction().
{
        QL_REQUIRE(arguments_.averageType == Average::Geometric,
                   "not a geometric average option");
        QL_REQUIRE(arguments_.exercise->type() == Exercise::European,
                   "not an European Option");
        Date exercise = arguments_.exercise->lastDate();
        boost::shared_ptr<PlainVanillaPayoff> payoff =
            boost::dynamic_pointer_cast<PlainVanillaPayoff>(arguments_.payoff);
        QL_REQUIRE(payoff, "non-plain payoff given");
        Volatility volatility =
            process_->blackVolatility()->blackVol(exercise, payoff->strike());
        Real variance =
            process_->blackVolatility()->blackVariance(exercise,
                                                       payoff->strike());
        DiscountFactor riskFreeDiscount =
            process_->riskFreeRate()->discount(exercise);
        DayCounter rfdc  = process_->riskFreeRate()->dayCounter();
        DayCounter divdc = process_->dividendYield()->dayCounter();
        DayCounter voldc = process_->blackVolatility()->dayCounter();
        Spread dividendYield = 0.5 * (
            process_->riskFreeRate()->zeroRate(exercise, rfdc,
                                               Continuous, NoFrequency) +
            process_->dividendYield()->zeroRate(exercise, divdc,
                                                Continuous, NoFrequency) +
            volatility*volatility/6.0);
        Time t_q = divdc.yearFraction(
            process_->dividendYield()->referenceDate(), exercise);
        DiscountFactor dividendDiscount = std::exp(-dividendYield*t_q);
        Real spot = process_->stateVariable()->value();
        QL_REQUIRE(spot > 0.0, "negative or null underlying");
        Real forward = spot * dividendDiscount / riskFreeDiscount;
        BlackCalculator black(payoff, forward, std::sqrt(variance/3.0),
                              riskFreeDiscount);
        results_.value = black.value();
        results_.delta = black.delta(spot);
        results_.gamma = black.gamma(spot);
        results_.dividendRho = black.dividendRho(t_q)/2.0;
        Time t_r = rfdc.yearFraction(process_->riskFreeRate()->referenceDate(),
                                     arguments_.exercise->lastDate());
        results_.rho = black.rho(t_r) + 0.5 * black.dividendRho(t_q);
        Time t_v = voldc.yearFraction(
            process_->blackVolatility()->referenceDate(),
            arguments_.exercise->lastDate());
        results_.vega = black.vega(t_v)/std::sqrt(3.0) +
                        black.dividendRho(t_q)*volatility/6.0;
        try {
            results_.theta = black.theta(spot, t_v);
        } catch (Error&) {
            results_.theta = Null<Real>();
        }
    }
Member Data Documentation
boost::shared_ptr<GeneralizedBlackScholesProcess> QuantLib::AnalyticContinuousGeometricAveragePriceAsianEngine::process_ [private]
Definition at line 56 of file analytic_cont_geom_av_price.hpp.
Referenced by AnalyticContinuousGeometricAveragePriceAsianEngine(), and calculate().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/asian/analytic_cont_geom_av_price.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/asian/analytic_cont_geom_av_price.cpp