QuantLib: QuantLib::DefaultProbabilityTermStructure Class Reference
QuantLib::DefaultProbabilityTermStructure Class Reference
Default probability term structure.
#include <defaulttermstructure.hpp>
Public Member Functions
Constructors
See the TermStructure documentation for issues regarding constructors.
DefaultProbabilityTermStructure (const DayCounter &dc=DayCounter(), const std::vector< Handle< Quote > > &jumps=std::vector< Handle< Quote > >(), const std::vector< Date > &jumpDates=std::vector< Date >())
DefaultProbabilityTermStructure (const Date &referenceDate, const Calendar &cal=Calendar(), const DayCounter &dc=DayCounter(), const std::vector< Handle< Quote > > &jumps=std::vector< Handle< Quote > >(), const std::vector< Date > &jumpDates=std::vector< Date >())
DefaultProbabilityTermStructure (Natural settlementDays, const Calendar &cal, const DayCounter &dc=DayCounter(), const std::vector< Handle< Quote > > &jumps=std::vector< Handle< Quote > >(), const std::vector< Date > &jumpDates=std::vector< Date >())
Survival probabilities
These methods return the survival probability from the reference date until a given date or time. In the latter case, the time is calculated as a fraction of year from the reference date.
Probability survivalProbability (const Date &d, bool extrapolate=false) const
Probability survivalProbability (Time t, bool extrapolate=false) const
Default probabilities
These methods return the default probability from the reference date until a given date or time. In the latter case, the time is calculated as a fraction of year from the reference date.
Probability defaultProbability (const Date &d, bool extrapolate=false) const
Probability defaultProbability (Time t, bool extrapolate=false) const
Probability defaultProbability (const Date &, const Date &, bool extrapolate=false) const
probability of default between two given dates
Probability defaultProbability (Time, Time, bool extrapo=false) const
probability of default between two given times
Default densities
These methods return the default density at a given date or time. In the latter case, the time is calculated as a fraction of year from the reference date.
Real defaultDensity (const Date &d, bool extrapolate=false) const
Real defaultDensity (Time t, bool extrapolate=false) const
Hazard rates
These methods returns the hazard rate at a given date or time. In the latter case, the time is calculated as a fraction of year from the reference date.
Hazard rates are defined with annual frequency and continuous compounding.
Rate hazardRate (const Date &d, bool extrapolate=false) const
Rate hazardRate (Time t, bool extrapolate=false) const
Jump inspectors
const std::vector< Date > & jumpDates () const
const std::vector< Time > & jumpTimes () const
Observer interface
void update ()
Protected Member Functions
Calculations
These methods must be implemented in derived classes to perform the actual calculations. When they are called, range check has already been performed; therefore, they must assume that extrapolation is required.
virtual Probability survivalProbabilityImpl (Time) const =0
survival probability calculation
virtual Real defaultDensityImpl (Time) const =0
default density calculation
Private Member Functions
void setJumps ()
Private Attributes
std::vector< Handle< Quote > > jumps_
std::vector< Date > jumpDates_
std::vector< Time > jumpTimes_
Size nJumps_
Date latestReference_
Detailed Description
Default probability term structure.
This abstract class defines the interface of concrete credit structures which will be derived from this one.
Definition at line 46 of file defaulttermstructure.hpp.
Constructor & Destructor Documentation
QuantLib::DefaultProbabilityTermStructure::DefaultProbabilityTermStructure (const DayCounter & dc = DayCounter(), const std::vector< Handle< Quote > > & jumps = std::vector<Handle<Quote> >(), const std::vector< Date > & jumpDates = std::vector<Date>())
Definition at line 28 of file defaulttermstructure.cpp.
References jumps_, nJumps_, QuantLib::Observer::registerWith(), and setJumps().
    : TermStructure(dc), jumps_(jumps),
      jumpDates_(jumpDates), jumpTimes_(jumpDates.size()),
      nJumps_(jumps_.size()) {
        setJumps();
        for (Size i=0; i<nJumps_; ++i)
            registerWith(jumps_[i]);
    }
QuantLib::DefaultProbabilityTermStructure::DefaultProbabilityTermStructure (const Date & referenceDate, const Calendar & cal = Calendar(), const DayCounter & dc = DayCounter(), const std::vector< Handle< Quote > > & jumps = std::vector<Handle<Quote> >(), const std::vector< Date > & jumpDates = std::vector<Date>())
Definition at line 40 of file defaulttermstructure.cpp.
References jumps_, nJumps_, QuantLib::Observer::registerWith(), and setJumps().
    : TermStructure(referenceDate, cal, dc), jumps_(jumps),
      jumpDates_(jumpDates), jumpTimes_(jumpDates.size()),
      nJumps_(jumps_.size()) {
        setJumps();
        for (Size i=0; i<nJumps_; ++i)
            registerWith(jumps_[i]);
    }
QuantLib::DefaultProbabilityTermStructure::DefaultProbabilityTermStructure (Natural settlementDays, const Calendar & cal, const DayCounter & dc = DayCounter(), const std::vector< Handle< Quote > > & jumps = std::vector<Handle<Quote> >(), const std::vector< Date > & jumpDates = std::vector<Date>())
Definition at line 54 of file defaulttermstructure.cpp.
References jumps_, nJumps_, QuantLib::Observer::registerWith(), and setJumps().
    : TermStructure(settlementDays, cal, dc), jumps_(jumps),
      jumpDates_(jumpDates), jumpTimes_(jumpDates.size()),
      nJumps_(jumps_.size()) {
        setJumps();
        for (Size i=0; i<nJumps_; ++i)
            registerWith(jumps_[i]);
    }
Member Function Documentation
Real QuantLib::DefaultProbabilityTermStructure::defaultDensity (const Date & d, bool extrapolate = false) const [inline]
Definition at line 199 of file defaulttermstructure.hpp.
References QuantLib::TermStructure::timeFromReference().
Referenced by hazardRate().
{
        return defaultDensity(timeFromReference(d), extrapolate);
    }
Real QuantLib::DefaultProbabilityTermStructure::defaultDensity (Time t, bool extrapolate = false) const [inline]
Definition at line 206 of file defaulttermstructure.hpp.
References QuantLib::TermStructure::checkRange(), and defaultDensityImpl().
{
        checkRange(t, extrapolate);
        return defaultDensityImpl(t);
    }
virtual Real QuantLib::DefaultProbabilityTermStructure::defaultDensityImpl (Time) const [protected, pure virtual]
default density calculation
Implemented in QuantLib::HazardRateStructure, QuantLib::InterpolatedDefaultDensityCurve< Interpolator >, QuantLib::InterpolatedSurvivalProbabilityCurve< Interpolator >, and QuantLib::SurvivalProbabilityStructure.
Referenced by defaultDensity(), and QuantLib::DefaultDensityStructure::survivalProbabilityImpl().
Probability QuantLib::DefaultProbabilityTermStructure::defaultProbability (const Date & d, bool extrapolate = false) const [inline]
Definition at line 185 of file defaulttermstructure.hpp.
References survivalProbability().
Referenced by defaultProbability(), DefaultProbabilityCurveTest::testDefaultProbability(), and DefaultProbabilityCurveTest::testFlatHazardRate().
{
        return 1.0 - survivalProbability(d, extrapolate);
    }
Probability QuantLib::DefaultProbabilityTermStructure::defaultProbability (Time t, bool extrapolate = false) const [inline]
The same day-counting rule used by the term structure should be used for calculating the passed time t.
Definition at line 192 of file defaulttermstructure.hpp.
References survivalProbability().
{
        return 1.0 - survivalProbability(t, extrapolate);
    }
Probability QuantLib::DefaultProbabilityTermStructure::defaultProbability (const Date & d1, const Date & d2, bool extrapolate = false) const
probability of default between two given dates
Definition at line 107 of file defaulttermstructure.cpp.
References defaultProbability(), and QL_REQUIRE.
{
        QL_REQUIRE(d1 <= d2,
                   "initial date (" << d1 << ") "
                   "later than final date (" << d2 << ")");
        Probability p1 = defaultProbability(d1,extrapolate),
                    p2 = defaultProbability(d2,extrapolate);
        return p2 - p1;
    }
Probability QuantLib::DefaultProbabilityTermStructure::defaultProbability (Time t1, Time t2, bool extrapo = false) const
probability of default between two given times
Definition at line 119 of file defaulttermstructure.cpp.
References defaultProbability(), and QL_REQUIRE.
{
        QL_REQUIRE(t1 <= t2,
                   "initial time (" << t1 << ") "
                   "later than final time (" << t2 << ")");
        Probability p1 = defaultProbability(t1,extrapolate),
                    p2 = defaultProbability(t2,extrapolate);
        return p2 - p1;
    }
Rate QuantLib::DefaultProbabilityTermStructure::hazardRate (const Date & d, bool extrapolate = false) const [inline]
Definition at line 214 of file defaulttermstructure.hpp.
References QuantLib::TermStructure::timeFromReference().
{
        return hazardRate(timeFromReference(d), extrapolate);
    }
Rate QuantLib::DefaultProbabilityTermStructure::hazardRate (Time t, bool extrapolate = false) const [inline]
Definition at line 220 of file defaulttermstructure.hpp.
References defaultDensity(), and survivalProbability().
{
        Probability S = survivalProbability(t, extrapolate);
        return S == 0.0 ? 0.0 : defaultDensity(t, extrapolate)/S;
    }
const std::vector< Date > & QuantLib::DefaultProbabilityTermStructure::jumpDates () const [inline]
Definition at line 228 of file defaulttermstructure.hpp.
References jumpDates_.
{
        return this->jumpDates_;
    }
const std::vector< Time > & QuantLib::DefaultProbabilityTermStructure::jumpTimes () const [inline]
Definition at line 234 of file defaulttermstructure.hpp.
References jumpTimes_.
{
        return this->jumpTimes_;
    }
void QuantLib::DefaultProbabilityTermStructure::setJumps () [private]
Definition at line 68 of file defaulttermstructure.cpp.
References QuantLib::December, jumpDates_, jumps_, jumpTimes_, latestReference_, nJumps_, QL_REQUIRE, QuantLib::TermStructure::referenceDate(), QuantLib::TermStructure::timeFromReference(), and QuantLib::Date::year().
Referenced by DefaultProbabilityTermStructure(), and update().
{
        if (jumpDates_.empty() && !jumps_.empty()) { // turn of year dates
            jumpDates_.resize(nJumps_);
            jumpTimes_.resize(nJumps_);
            Year y = referenceDate().year();
            for (Size i=0; i<nJumps_; ++i)
                jumpDates_[i] = Date(31, December, y+i);
        } else { // fixed dats
            QL_REQUIRE(jumpDates_.size()==nJumps_,
                       "mismatch between number of jumps (" << nJumps_ <<
                       ") and jump dates (" << jumpDates_.size() << ")");
        }
        for (Size i=0; i<nJumps_; ++i)
            jumpTimes_[i] = timeFromReference(jumpDates_[i]);
        latestReference_ = referenceDate();
    }
Probability QuantLib::DefaultProbabilityTermStructure::survivalProbability (const Date & d, bool extrapolate = false) const [inline]
Definition at line 178 of file defaulttermstructure.hpp.
References QuantLib::TermStructure::timeFromReference().
Referenced by defaultProbability(), and hazardRate().
{
        return survivalProbability(timeFromReference(d), extrapolate);
    }
Probability QuantLib::DefaultProbabilityTermStructure::survivalProbability (Time t, bool extrapolate = false) const
The same day-counting rule used by the term structure should be used for calculating the passed time t.
Definition at line 85 of file defaulttermstructure.cpp.
References QuantLib::TermStructure::checkRange(), jumps_, jumpTimes_, nJumps_, QuantLib::io::ordinal(), QL_REQUIRE, survivalProbabilityImpl(), and anonymous_namespace{quantlibbenchmark.cpp}::t.
{
        checkRange(t, extrapolate);
        if (!jumps_.empty()) {
            Probability jumpEffect = 1.0;
            for (Size i=0; i<nJumps_ && jumpTimes_[i]<t; ++i) {
                QL_REQUIRE(jumps_[i]->isValid(),
                           "invalid " << io::ordinal(i+1) << " jump quote");
                DiscountFactor thisJump = jumps_[i]->value();
                QL_REQUIRE(thisJump > 0.0 && thisJump <= 1.0,
                           "invalid " << io::ordinal(i+1) << " jump value: " <<
                           thisJump);
                jumpEffect *= thisJump;
            }
            return jumpEffect * survivalProbabilityImpl(t);
        }
        return survivalProbabilityImpl(t);
    }
virtual Probability QuantLib::DefaultProbabilityTermStructure::survivalProbabilityImpl (Time) const [protected, pure virtual]
survival probability calculation
Implemented in QuantLib::HazardRateStructure, QuantLib::InterpolatedHazardRateCurve< Interpolator >, QuantLib::InterpolatedDefaultDensityCurve< Interpolator >, QuantLib::DefaultDensityStructure, QuantLib::InterpolatedSurvivalProbabilityCurve< Interpolator >, and QuantLib::FlatHazardRate.
Referenced by QuantLib::SurvivalProbabilityStructure::defaultDensityImpl(), and survivalProbability().
void QuantLib::DefaultProbabilityTermStructure::update () [inline, virtual]
This method must be implemented in derived classes. An instance of Observer does not call this method directly: instead, it will be called by the observables the instance registered with when they need to notify any changes.
Reimplemented from QuantLib::TermStructure.
Definition at line 238 of file defaulttermstructure.hpp.
References latestReference_, QuantLib::TermStructure::referenceDate(), and setJumps().
{
        TermStructure::update();
        if (referenceDate() != latestReference_)
            setJumps();
    }
Member Data Documentation
std::vector<Date> QuantLib::DefaultProbabilityTermStructure::jumpDates_ [private]
Definition at line 169 of file defaulttermstructure.hpp.
Referenced by jumpDates(), and setJumps().
std::vector<Handle<Quote> > QuantLib::DefaultProbabilityTermStructure::jumps_ [private]
Definition at line 168 of file defaulttermstructure.hpp.
Referenced by DefaultProbabilityTermStructure(), setJumps(), and survivalProbability().
std::vector<Time> QuantLib::DefaultProbabilityTermStructure::jumpTimes_ [private]
Definition at line 170 of file defaulttermstructure.hpp.
Referenced by jumpTimes(), setJumps(), and survivalProbability().
Date QuantLib::DefaultProbabilityTermStructure::latestReference_ [private]
Definition at line 172 of file defaulttermstructure.hpp.
Referenced by setJumps(), and update().
Size QuantLib::DefaultProbabilityTermStructure::nJumps_ [private]
Definition at line 171 of file defaulttermstructure.hpp.
Referenced by DefaultProbabilityTermStructure(), setJumps(), and survivalProbability().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/defaulttermstructure.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/defaulttermstructure.cpp