QuantLib: QuantLib::MakeCms Class Reference
QuantLib::MakeCms Class Reference
helper class for instantiating CMS
#include <makecms.hpp>
Public Member Functions
MakeCms (const Period &swapTenor, const boost::shared_ptr< SwapIndex > &swapIndex, const boost::shared_ptr< IborIndex > &iborIndex, Spread iborSpread=0.0, const Period &forwardStart=0 *Days)
MakeCms (const Period &swapTenor, const boost::shared_ptr< SwapIndex > &swapIndex, Spread iborSpread=0.0, const Period &forwardStart=0 *Days)
operator Swap () const
operator boost::shared_ptr< Swap > () const
MakeCms & receiveCms (bool flag=true)
MakeCms & withNominal (Real n)
MakeCms & withEffectiveDate (const Date &)
MakeCms & withCmsLegTenor (const Period &t)
MakeCms & withCmsLegCalendar (const Calendar &cal)
MakeCms & withCmsLegConvention (BusinessDayConvention bdc)
MakeCms & withCmsLegTerminationDateConvention (BusinessDayConvention)
MakeCms & withCmsLegRule (DateGeneration::Rule r)
MakeCms & withCmsLegEndOfMonth (bool flag=true)
MakeCms & withCmsLegFirstDate (const Date &d)
MakeCms & withCmsLegNextToLastDate (const Date &d)
MakeCms & withCmsLegDayCount (const DayCounter &dc)
MakeCms & withFloatingLegTenor (const Period &t)
MakeCms & withFloatingLegCalendar (const Calendar &cal)
MakeCms & withFloatingLegConvention (BusinessDayConvention bdc)
MakeCms & withFloatingLegTerminationDateConvention (BusinessDayConvention bdc)
MakeCms & withFloatingLegRule (DateGeneration::Rule r)
MakeCms & withFloatingLegEndOfMonth (bool flag=true)
MakeCms & withFloatingLegFirstDate (const Date &d)
MakeCms & withFloatingLegNextToLastDate (const Date &d)
MakeCms & withFloatingLegDayCount (const DayCounter &dc)
MakeCms & withAtmSpread (bool flag=true)
MakeCms & withDiscountingTermStructure (const Handle< YieldTermStructure > &discountingTermStructure)
MakeCms & withCmsCouponPricer (const boost::shared_ptr< CmsCouponPricer > &couponPricer)
Private Attributes
Period swapTenor_
boost::shared_ptr< SwapIndex > swapIndex_
boost::shared_ptr< IborIndex > iborIndex_
Spread iborSpread_
bool useAtmSpread_
Period forwardStart_
Spread cmsSpread_
Real cmsGearing_
Rate cmsCap_
Rate cmsFloor_
Date effectiveDate_
Calendar cmsCalendar_
Calendar floatCalendar_
bool payCms_
Real nominal_
Period cmsTenor_
Period floatTenor_
BusinessDayConvention cmsConvention_
BusinessDayConvention cmsTerminationDateConvention_
BusinessDayConvention floatConvention_
BusinessDayConvention floatTerminationDateConvention_
DateGeneration::Rule cmsRule_
DateGeneration::Rule floatRule_
bool cmsEndOfMonth_
bool floatEndOfMonth_
Date cmsFirstDate_
Date cmsNextToLastDate_
Date floatFirstDate_
Date floatNextToLastDate_
DayCounter cmsDayCount_
DayCounter floatDayCount_
boost::shared_ptr< PricingEngine > engine_
boost::shared_ptr
< CmsCouponPricer > couponPricer_
Detailed Description
helper class for instantiating CMS
This class provides a more comfortable way to instantiate standard market constant maturity swap.
Definition at line 40 of file makecms.hpp.
Constructor & Destructor Documentation
QuantLib::MakeCms::MakeCms (const Period & swapTenor, const boost::shared_ptr< SwapIndex > & swapIndex, const boost::shared_ptr< IborIndex > & iborIndex, Spread iborSpread = 0.0, const Period & forwardStart = 0*Days)
Definition at line 33 of file makecms.cpp.
    : swapTenor_(swapTenor), swapIndex_(swapIndex),
      iborIndex_(iborIndex), iborSpread_(iborSpread),
      useAtmSpread_(false), forwardStart_(forwardStart),
      cmsSpread_(0.0), cmsGearing_(1.0),
      cmsCap_(2.0), cmsFloor_(Null<Real>()),
      effectiveDate_(Date()),
      cmsCalendar_(swapIndex->fixingCalendar()),
      floatCalendar_(iborIndex->fixingCalendar()),
      payCms_(true), nominal_(1.0),
      cmsTenor_(3*Months), floatTenor_(iborIndex->tenor()),
      cmsConvention_(ModifiedFollowing),
      cmsTerminationDateConvention_(ModifiedFollowing),
      floatConvention_(iborIndex->businessDayConvention()),
      floatTerminationDateConvention_(iborIndex->businessDayConvention()),
      cmsRule_(DateGeneration::Backward), floatRule_(DateGeneration::Backward),
      cmsEndOfMonth_(false), floatEndOfMonth_(false),
      cmsFirstDate_(Date()), cmsNextToLastDate_(Date()),
      floatFirstDate_(Date()), floatNextToLastDate_(Date()),
      cmsDayCount_(Actual360()),
      floatDayCount_(iborIndex->dayCounter()),
      // arbitrary choice:
      //engine_(new DiscountingSwapEngine(iborIndex->termStructure())),
      engine_(new DiscountingSwapEngine(swapIndex->forwardingTermStructure())) {}
QuantLib::MakeCms::MakeCms (const Period & swapTenor, const boost::shared_ptr< SwapIndex > & swapIndex, Spread iborSpread = 0.0, const Period & forwardStart = 0*Days)
Definition at line 65 of file makecms.cpp.
    : swapTenor_(swapTenor), swapIndex_(swapIndex),
      iborIndex_(swapIndex->iborIndex()), iborSpread_(iborSpread),
      useAtmSpread_(false), forwardStart_(forwardStart),
      cmsSpread_(0.0), cmsGearing_(1.0),
      cmsCap_(2.0), cmsFloor_(Null<Real>()),
      effectiveDate_(Date()),
      cmsCalendar_(swapIndex->fixingCalendar()),
      floatCalendar_(iborIndex_->fixingCalendar()),
      payCms_(true), nominal_(1.0),
      cmsTenor_(3*Months), floatTenor_(iborIndex_->tenor()),
      cmsConvention_(ModifiedFollowing),
      cmsTerminationDateConvention_(ModifiedFollowing),
      floatConvention_(iborIndex_->businessDayConvention()),
      floatTerminationDateConvention_(iborIndex_->businessDayConvention()),
      cmsRule_(DateGeneration::Backward), floatRule_(DateGeneration::Backward),
      cmsEndOfMonth_(false), floatEndOfMonth_(false),
      cmsFirstDate_(Date()), cmsNextToLastDate_(Date()),
      floatFirstDate_(Date()), floatNextToLastDate_(Date()),
      cmsDayCount_(Actual360()),
      floatDayCount_(iborIndex_->dayCounter()),
      engine_(new DiscountingSwapEngine(swapIndex->forwardingTermStructure())) {}
Member Function Documentation
QuantLib::MakeCms::operator boost::shared_ptr< Swap > () const
Definition at line 99 of file makecms.cpp.
References QuantLib::Date::advance(), QuantLib::Days, QuantLib::Settings::evaluationDate(), QuantLib::Singleton< Settings >::instance(), QuantLib::Swap::legBPS(), QuantLib::Swap::legNPV(), QL_REQUIRE, QuantLib::setCouponPricer(), QuantLib::Instrument::setPricingEngine(), anonymous_namespace{marketmodel.cpp}::startDate, QuantLib::swap(), QuantLib::CmsLeg::withCaps(), QuantLib::CmsLeg::withFixingDays(), QuantLib::IborLeg::withFixingDays(), QuantLib::CmsLeg::withFloors(), QuantLib::CmsLeg::withNotionals(), QuantLib::IborLeg::withNotionals(), QuantLib::CmsLeg::withPaymentAdjustment(), QuantLib::IborLeg::withPaymentAdjustment(), QuantLib::CmsLeg::withPaymentDayCounter(), QuantLib::IborLeg::withPaymentDayCounter(), and QuantLib::CmsLeg::withSpreads().
{
        Date startDate;
        if (effectiveDate_ != Date())
            startDate = effectiveDate_;
        else {
            Natural fixingDays = iborIndex_->fixingDays();
            Date referenceDate = Settings::instance().evaluationDate();
            Date spotDate = floatCalendar_.advance(referenceDate,
                                                   fixingDays*Days);
            startDate = spotDate+forwardStart_;
        }
        Date terminationDate = startDate+swapTenor_;
        Schedule cmsSchedule(startDate, terminationDate,
                             cmsTenor_, cmsCalendar_,
                             cmsConvention_,
                             cmsTerminationDateConvention_,
                             cmsRule_, cmsEndOfMonth_,
                             cmsFirstDate_, cmsNextToLastDate_);
        Schedule floatSchedule(startDate, terminationDate,
                               floatTenor_, floatCalendar_,
                               floatConvention_,
                               floatTerminationDateConvention_,
                               floatRule_ , floatEndOfMonth_,
                               floatFirstDate_, floatNextToLastDate_);
        Leg cmsLeg = CmsLeg(cmsSchedule, swapIndex_)
            .withNotionals(nominal_)
            .withPaymentDayCounter(cmsDayCount_)
            .withPaymentAdjustment(cmsConvention_)
            .withFixingDays(swapIndex_->fixingDays())
            .withGearings(cmsGearing_)
            .withSpreads(cmsSpread_)
            .withCaps(cmsCap_)
            .withFloors(cmsFloor_);
        if (couponPricer_)
            setCouponPricer(cmsLeg, couponPricer_);
        Rate usedSpread = iborSpread_;
        if (useAtmSpread_) {
            QL_REQUIRE(!iborIndex_->forwardingTermStructure().empty(),
                       "null term structure set to this instance of " <<
                       iborIndex_->name());
            QL_REQUIRE(!swapIndex_->forwardingTermStructure().empty(),
                       "null term structure set to this instance of " <<
                       swapIndex_->name());
            QL_REQUIRE(couponPricer_,
                       "no CmsCouponPricer set (yet)");
            Leg floatLeg = IborLeg(floatSchedule, iborIndex_)
                .withNotionals(nominal_)
                .withPaymentDayCounter(floatDayCount_)
                .withPaymentAdjustment(floatConvention_)
                .withFixingDays(iborIndex_->fixingDays());
            Swap temp(cmsLeg, floatLeg);
            temp.setPricingEngine(engine_);
            Real npv = temp.legNPV(0)+temp.legNPV(1);
            usedSpread = -npv/temp.legBPS(1)*1e-4;
        } else {
            QL_REQUIRE(usedSpread != Null<Spread>(),
                       "null spread set");
        }
        Leg floatLeg = IborLeg(floatSchedule, iborIndex_)
            .withNotionals(nominal_)
            .withPaymentDayCounter(floatDayCount_)
            .withPaymentAdjustment(floatConvention_)
            .withFixingDays(iborIndex_->fixingDays())
            .withSpreads(usedSpread);
        boost::shared_ptr<Swap> swap;
        if (payCms_)
            swap = boost::shared_ptr<Swap>(new Swap(cmsLeg, floatLeg));
        else
            swap = boost::shared_ptr<Swap>(new Swap(floatLeg, cmsLeg));
        swap->setPricingEngine(engine_);
        return swap;
    }
QuantLib::MakeCms::operator Swap () const
Definition at line 94 of file makecms.cpp.
References QuantLib::swap().
{
        boost::shared_ptr<Swap> swap = *this;
        return *swap;
    }
MakeCms & QuantLib::MakeCms::receiveCms (bool flag = true)
Definition at line 183 of file makecms.cpp.
References payCms_.
{
        payCms_ = !flag;
        return *this;
    }
MakeCms & QuantLib::MakeCms::withAtmSpread (bool flag = true)
Definition at line 313 of file makecms.cpp.
References useAtmSpread_.
{
        useAtmSpread_ = flag;
        return *this;
    }
MakeCms & QuantLib::MakeCms::withCmsCouponPricer (const boost::shared_ptr< CmsCouponPricer > & couponPricer)
Definition at line 206 of file makecms.cpp.
References couponPricer_.
Referenced by QuantLib::CmsMarket::CmsMarket().
{
        couponPricer_ = couponPricer;
        return *this;
    }
MakeCms & QuantLib::MakeCms::withCmsLegCalendar (const Calendar & cal)
Definition at line 218 of file makecms.cpp.
References cmsCalendar_.
{
        cmsCalendar_ = cal;
        return *this;
    }
MakeCms & QuantLib::MakeCms::withCmsLegConvention (BusinessDayConvention bdc)
Definition at line 224 of file makecms.cpp.
References cmsConvention_.
{
        cmsConvention_ = bdc;
        return *this;
    }
MakeCms & QuantLib::MakeCms::withCmsLegDayCount (const DayCounter & dc)
Definition at line 257 of file makecms.cpp.
References cmsDayCount_.
{
        cmsDayCount_ = dc;
        return *this;
    }
MakeCms & QuantLib::MakeCms::withCmsLegEndOfMonth (bool flag = true)
Definition at line 240 of file makecms.cpp.
References cmsEndOfMonth_.
{
        cmsEndOfMonth_ = flag;
        return *this;
    }
MakeCms & QuantLib::MakeCms::withCmsLegFirstDate (const Date & d)
Definition at line 245 of file makecms.cpp.
References cmsFirstDate_, and anonymous_namespace{marketmodel.cpp}::d.
{
        cmsFirstDate_ = d;
        return *this;
    }
MakeCms & QuantLib::MakeCms::withCmsLegNextToLastDate (const Date & d)
Definition at line 251 of file makecms.cpp.
References cmsNextToLastDate_, and anonymous_namespace{marketmodel.cpp}::d.
{
        cmsNextToLastDate_ = d;
        return *this;
    }
MakeCms & QuantLib::MakeCms::withCmsLegRule (DateGeneration::Rule r)
Definition at line 235 of file makecms.cpp.
References cmsRule_.
{
        cmsRule_ = r;
        return *this;
    }
MakeCms & QuantLib::MakeCms::withCmsLegTenor (const Period & t)
Definition at line 212 of file makecms.cpp.
References cmsTenor_, and anonymous_namespace{quantlibbenchmark.cpp}::t.
{
        cmsTenor_ = t;
        return *this;
    }
MakeCms & QuantLib::MakeCms::withCmsLegTerminationDateConvention (BusinessDayConvention bdc)
Definition at line 230 of file makecms.cpp.
References cmsTerminationDateConvention_.
{
        cmsTerminationDateConvention_ = bdc;
        return *this;
    }
MakeCms & QuantLib::MakeCms::withDiscountingTermStructure (const Handle< YieldTermStructure > & discountingTermStructure)
Definition at line 199 of file makecms.cpp.
References engine_.
Referenced by QuantLib::CmsMarket::CmsMarket().
{
        engine_ = boost::shared_ptr<PricingEngine>(new
                            DiscountingSwapEngine(discountingTermStructure));
        return *this;
    }
MakeCms & QuantLib::MakeCms::withEffectiveDate (const Date & effectiveDate)
Definition at line 194 of file makecms.cpp.
References effectiveDate_.
{
        effectiveDate_ = effectiveDate;
        return *this;
    }
MakeCms & QuantLib::MakeCms::withFloatingLegCalendar (const Calendar & cal)
Definition at line 268 of file makecms.cpp.
References floatCalendar_.
{
        floatCalendar_ = cal;
        return *this;
    }
MakeCms & QuantLib::MakeCms::withFloatingLegConvention (BusinessDayConvention bdc)
Definition at line 274 of file makecms.cpp.
References floatConvention_.
{
        floatConvention_ = bdc;
        return *this;
    }
MakeCms & QuantLib::MakeCms::withFloatingLegDayCount (const DayCounter & dc)
Definition at line 308 of file makecms.cpp.
References floatDayCount_.
{
        floatDayCount_ = dc;
        return *this;
    }
MakeCms & QuantLib::MakeCms::withFloatingLegEndOfMonth (bool flag = true)
Definition at line 290 of file makecms.cpp.
References floatEndOfMonth_.
{
        floatEndOfMonth_ = flag;
        return *this;
    }
MakeCms & QuantLib::MakeCms::withFloatingLegFirstDate (const Date & d)
Definition at line 296 of file makecms.cpp.
References anonymous_namespace{marketmodel.cpp}::d, and floatFirstDate_.
{
        floatFirstDate_ = d;
        return *this;
    }
MakeCms & QuantLib::MakeCms::withFloatingLegNextToLastDate (const Date & d)
Definition at line 302 of file makecms.cpp.
References anonymous_namespace{marketmodel.cpp}::d, and floatNextToLastDate_.
{
        floatNextToLastDate_ = d;
        return *this;
    }
MakeCms & QuantLib::MakeCms::withFloatingLegRule (DateGeneration::Rule r)
Definition at line 285 of file makecms.cpp.
References floatRule_.
{
        floatRule_ = r;
        return *this;
    }
MakeCms & QuantLib::MakeCms::withFloatingLegTenor (const Period & t)
Definition at line 262 of file makecms.cpp.
References floatTenor_, and anonymous_namespace{quantlibbenchmark.cpp}::t.
{
        floatTenor_ = t;
        return *this;
    }
MakeCms & QuantLib::MakeCms::withFloatingLegTerminationDateConvention (BusinessDayConvention bdc)
Definition at line 280 of file makecms.cpp.
References floatTerminationDateConvention_.
{
        floatTerminationDateConvention_ = bdc;
        return *this;
    }
MakeCms & QuantLib::MakeCms::withNominal (Real n)
Definition at line 188 of file makecms.cpp.
References nominal_.
{
        nominal_ = n;
        return *this;
    }
Member Data Documentation
Calendar QuantLib::MakeCms::cmsCalendar_ [private]
Definition at line 101 of file makecms.hpp.
Referenced by withCmsLegCalendar().
Rate QuantLib::MakeCms::cmsCap_ [private]
Definition at line 98 of file makecms.hpp.
BusinessDayConvention QuantLib::MakeCms::cmsConvention_ [private]
Definition at line 106 of file makecms.hpp.
Referenced by withCmsLegConvention().
DayCounter QuantLib::MakeCms::cmsDayCount_ [private]
Definition at line 112 of file makecms.hpp.
Referenced by withCmsLegDayCount().
bool QuantLib::MakeCms::cmsEndOfMonth_ [private]
Definition at line 109 of file makecms.hpp.
Referenced by withCmsLegEndOfMonth().
Date QuantLib::MakeCms::cmsFirstDate_ [private]
Definition at line 110 of file makecms.hpp.
Referenced by withCmsLegFirstDate().
Rate QuantLib::MakeCms::cmsFloor_ [private]
Definition at line 98 of file makecms.hpp.
Real QuantLib::MakeCms::cmsGearing_ [private]
Definition at line 97 of file makecms.hpp.
Date QuantLib::MakeCms::cmsNextToLastDate_ [private]
Definition at line 110 of file makecms.hpp.
Referenced by withCmsLegNextToLastDate().
DateGeneration::Rule QuantLib::MakeCms::cmsRule_ [private]
Definition at line 108 of file makecms.hpp.
Referenced by withCmsLegRule().
Spread QuantLib::MakeCms::cmsSpread_ [private]
Definition at line 96 of file makecms.hpp.
Period QuantLib::MakeCms::cmsTenor_ [private]
Definition at line 105 of file makecms.hpp.
Referenced by withCmsLegTenor().
BusinessDayConvention QuantLib::MakeCms::cmsTerminationDateConvention_ [private]
Definition at line 106 of file makecms.hpp.
Referenced by withCmsLegTerminationDateConvention().
boost::shared_ptr<CmsCouponPricer> QuantLib::MakeCms::couponPricer_ [private]
Definition at line 115 of file makecms.hpp.
Referenced by withCmsCouponPricer().
Date QuantLib::MakeCms::effectiveDate_ [private]
Definition at line 100 of file makecms.hpp.
Referenced by withEffectiveDate().
boost::shared_ptr<PricingEngine> QuantLib::MakeCms::engine_ [private]
Definition at line 114 of file makecms.hpp.
Referenced by withDiscountingTermStructure().
Calendar QuantLib::MakeCms::floatCalendar_ [private]
Definition at line 101 of file makecms.hpp.
Referenced by withFloatingLegCalendar().
BusinessDayConvention QuantLib::MakeCms::floatConvention_ [private]
Definition at line 107 of file makecms.hpp.
Referenced by withFloatingLegConvention().
DayCounter QuantLib::MakeCms::floatDayCount_ [private]
Definition at line 112 of file makecms.hpp.
Referenced by withFloatingLegDayCount().
bool QuantLib::MakeCms::floatEndOfMonth_ [private]
Definition at line 109 of file makecms.hpp.
Referenced by withFloatingLegEndOfMonth().
Date QuantLib::MakeCms::floatFirstDate_ [private]
Definition at line 111 of file makecms.hpp.
Referenced by withFloatingLegFirstDate().
Date QuantLib::MakeCms::floatNextToLastDate_ [private]
Definition at line 111 of file makecms.hpp.
Referenced by withFloatingLegNextToLastDate().
DateGeneration::Rule QuantLib::MakeCms::floatRule_ [private]
Definition at line 108 of file makecms.hpp.
Referenced by withFloatingLegRule().
Period QuantLib::MakeCms::floatTenor_ [private]
Definition at line 105 of file makecms.hpp.
Referenced by withFloatingLegTenor().
BusinessDayConvention QuantLib::MakeCms::floatTerminationDateConvention_ [private]
Definition at line 107 of file makecms.hpp.
Referenced by withFloatingLegTerminationDateConvention().
Period QuantLib::MakeCms::forwardStart_ [private]
Definition at line 94 of file makecms.hpp.
boost::shared_ptr<IborIndex> QuantLib::MakeCms::iborIndex_ [private]
Definition at line 91 of file makecms.hpp.
Spread QuantLib::MakeCms::iborSpread_ [private]
Definition at line 92 of file makecms.hpp.
Real QuantLib::MakeCms::nominal_ [private]
Definition at line 104 of file makecms.hpp.
Referenced by withNominal().
bool QuantLib::MakeCms::payCms_ [private]
Definition at line 103 of file makecms.hpp.
Referenced by receiveCms().
boost::shared_ptr<SwapIndex> QuantLib::MakeCms::swapIndex_ [private]
Definition at line 90 of file makecms.hpp.
Period QuantLib::MakeCms::swapTenor_ [private]
Definition at line 89 of file makecms.hpp.
bool QuantLib::MakeCms::useAtmSpread_ [private]
Definition at line 93 of file makecms.hpp.
Referenced by withAtmSpread().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/makecms.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/makecms.cpp