QuantLib: QuantLib::LongstaffSchwartzExerciseStrategy Class Reference
QuantLib::LongstaffSchwartzExerciseStrategy Class Reference
#include <lsstrategy.hpp>
Public Member Functions
LongstaffSchwartzExerciseStrategy (const Clone< MarketModelBasisSystem > &basisSystem, const std::vector< std::vector< Real > > &basisCoefficients, const EvolutionDescription &evolution, const std::vector< Size > &numeraires, const Clone< MarketModelExerciseValue > &exercise, const Clone< MarketModelExerciseValue > &control)
std::vector< Time > exerciseTimes () const
std::vector< Time > relevantTimes () const
void reset ()
bool exercise (const CurveState &currentState) const
void nextStep (const CurveState &currentState)
std::auto_ptr
< ExerciseStrategy< CurveState > > clone () const
Private Attributes
Clone< MarketModelBasisSystem > basisSystem_
std::vector< std::vector< Real > > basisCoefficients_
Clone< MarketModelExerciseValue > exercise_
Clone< MarketModelExerciseValue > control_
std::vector< Size > numeraires_
Size currentIndex_
Real principalInNumerairePortfolio_
Real newPrincipal_
std::vector< Time > exerciseTimes_
std::vector< Time > relevantTimes_
std::valarray< bool > isBasisTime_
std::valarray< bool > isRebateTime_
std::valarray< bool > isControlTime_
std::valarray< bool > isExerciseTime_
std::vector
< MarketModelDiscounter > rebateDiscounters_
std::vector
< MarketModelDiscounter > controlDiscounters_
std::vector< std::vector< Real > > basisValues_
std::vector< Size > exerciseIndex_
Detailed Description
Definition at line 32 of file lsstrategy.hpp.
Constructor & Destructor Documentation
QuantLib::LongstaffSchwartzExerciseStrategy::LongstaffSchwartzExerciseStrategy (const Clone< MarketModelBasisSystem > & basisSystem, const std::vector< std::vector< Real > > & basisCoefficients, const EvolutionDescription & evolution, const std::vector< Size > & numeraires, const Clone< MarketModelExerciseValue > & exercise, const Clone< MarketModelExerciseValue > & control)
Definition at line 30 of file lsstrategy.cpp.
References basisSystem_, basisValues_, QuantLib::checkCompatibility(), control_, controlDiscounters_, QuantLib::MarketModelExerciseValue::evolution(), QuantLib::MarketModelNodeDataProvider::evolution(), QuantLib::EvolutionDescription::evolutionTimes(), exercise_, exerciseIndex_, anonymous_namespace{swaption.cpp}::exercises, exerciseTimes_, isBasisTime_, isControlTime_, QuantLib::MarketModelExerciseValue::isExerciseTime(), isExerciseTime_, QuantLib::isInSubset(), isRebateTime_, QuantLib::MarketModelNodeDataProvider::numberOfExercises(), QuantLib::MarketModelBasisSystem::numberOfFunctions(), QuantLib::MarketModelExerciseValue::possibleCashFlowTimes(), QuantLib::EvolutionDescription::rateTimes(), anonymous_namespace{marketmodel.cpp}::rateTimes, rebateDiscounters_, relevantTimes_, and anonymous_namespace{perturbativebarrieroptionengine.cpp}::v().
Referenced by clone().
    : basisSystem_(basisSystem), basisCoefficients_(basisCoefficients),
      exercise_(exercise), control_(control),
      numeraires_(numeraires) {
        checkCompatibility(evolution, numeraires);
        relevantTimes_ = evolution.evolutionTimes();
        isBasisTime_.resize(relevantTimes_.size());
        isBasisTime_ = isInSubset(relevantTimes_,
                                  basisSystem_->evolution().evolutionTimes());
        isRebateTime_.resize(relevantTimes_.size());
        isRebateTime_ = isInSubset(relevantTimes_,
                                   exercise_->evolution().evolutionTimes());
        isControlTime_.resize(relevantTimes_.size());
        isControlTime_ = isInSubset(relevantTimes_,
                                    control_->evolution().evolutionTimes());
        exerciseIndex_ = std::vector<Size>(relevantTimes_.size());
        isExerciseTime_.resize(relevantTimes_.size(), false);
        std::valarray<bool> v = exercise_->isExerciseTime();
        Size exercises = 0;
        Size i;
        for (i=0; i<relevantTimes_.size(); ++i) {
            exerciseIndex_[i] = exercises;
            if (isRebateTime_[i]) {
                isExerciseTime_[i] = v[exercises];
                if (isExerciseTime_[i]) {
                    exerciseTimes_.push_back(relevantTimes_[i]);
                    ++exercises;
                }
            }
        }
        std::vector<Time> rateTimes = evolution.rateTimes();
        std::vector<Time> rebateTimes = exercise_->possibleCashFlowTimes();
        rebateDiscounters_.reserve(rebateTimes.size());
        for (i=0; i<rebateTimes.size(); ++i)
            rebateDiscounters_.push_back(
                         MarketModelDiscounter(rebateTimes[i], rateTimes));
        std::vector<Time> controlTimes = control_->possibleCashFlowTimes();
        controlDiscounters_.reserve(controlTimes.size());
        for (i=0; i<controlTimes.size(); ++i)
            controlDiscounters_.push_back(
                         MarketModelDiscounter(controlTimes[i], rateTimes));
        std::vector<Size> basisSizes = basisSystem_->numberOfFunctions();
        basisValues_.resize(basisSystem_->numberOfExercises());
        for (i=0; i<basisValues_.size(); ++i)
            basisValues_[i].resize(basisSizes[i]);
    }
Member Function Documentation
std::auto_ptr< ExerciseStrategy< CurveState > > QuantLib::LongstaffSchwartzExerciseStrategy::clone () const [virtual]
Implements QuantLib::ExerciseStrategy< CurveState >.
Definition at line 160 of file lsstrategy.cpp.
References LongstaffSchwartzExerciseStrategy().
{
        return std::auto_ptr<ExerciseStrategy<CurveState> >(
                                new LongstaffSchwartzExerciseStrategy(*this));
    }
bool QuantLib::LongstaffSchwartzExerciseStrategy::exercise (const CurveState & currentState) const [virtual]
Implements QuantLib::ExerciseStrategy< CurveState >.
Definition at line 107 of file lsstrategy.cpp.
References QuantLib::CashFlow::amount(), basisCoefficients_, basisSystem_, basisValues_, control_, controlDiscounters_, currentIndex_, exercise_, exerciseIndex_, QuantLib::dsd::inner_product(), numeraires_, principalInNumerairePortfolio_, rebateDiscounters_, QuantLib::MarketModelExerciseValue::value(), and QuantLib::MarketModelNodeDataProvider::values().
{
        Size exerciseIndex = exerciseIndex_[currentIndex_-1];
        CashFlow exerciseCF = exercise_->value(currentState);
        Real exerciseValue = exerciseCF.amount *
            rebateDiscounters_[exerciseCF.timeIndex]
                .numeraireBonds(currentState,
                                numeraires_[currentIndex_-1]) /
            principalInNumerairePortfolio_;
        CashFlow controlCF = control_->value(currentState);
        Real controlValue = controlCF.amount *
            controlDiscounters_[controlCF.timeIndex]
                .numeraireBonds(currentState,
                                numeraires_[currentIndex_-1]) /
            principalInNumerairePortfolio_;
        basisSystem_->values(currentState,
                             basisValues_[exerciseIndex]);
        const std::vector<Real>& alphas = basisCoefficients_[exerciseIndex];
        Real continuationValue =
            std::inner_product(alphas.begin(), alphas.end(),
                               basisValues_[exerciseIndex].begin(),
                               controlValue);
        return exerciseValue >= continuationValue;
    }
std::vector< Time > QuantLib::LongstaffSchwartzExerciseStrategy::exerciseTimes () const [virtual]
Implements QuantLib::ExerciseStrategy< CurveState >.
Definition at line 90 of file lsstrategy.cpp.
References exerciseTimes_.
Referenced by MarketModelTest::testCallableSwapLS().
{
        return exerciseTimes_;
    }
void QuantLib::LongstaffSchwartzExerciseStrategy::nextStep (const CurveState & currentState) [virtual]
Implements QuantLib::ExerciseStrategy< CurveState >.
Definition at line 138 of file lsstrategy.cpp.
References basisSystem_, control_, currentIndex_, QuantLib::CurveState::discountRatio(), exercise_, isBasisTime_, isControlTime_, isRebateTime_, newPrincipal_, QuantLib::MarketModelNodeDataProvider::nextStep(), QuantLib::MarketModelExerciseValue::nextStep(), numeraires_, and principalInNumerairePortfolio_.
{
        principalInNumerairePortfolio_ = newPrincipal_;
        if (isRebateTime_[currentIndex_])
            exercise_->nextStep(currentState);
        if (isControlTime_[currentIndex_])
            control_->nextStep(currentState);
        if (isBasisTime_[currentIndex_])
            basisSystem_->nextStep(currentState);
        if (currentIndex_ < numeraires_.size()-1) {
            Size numeraire = numeraires_[currentIndex_];
            Size nextNumeraire = numeraires_[currentIndex_+1];
            newPrincipal_ *=
                currentState.discountRatio(numeraire, nextNumeraire);
        }
        ++currentIndex_;
    }
std::vector< Time > QuantLib::LongstaffSchwartzExerciseStrategy::relevantTimes () const [virtual]
Implements QuantLib::ExerciseStrategy< CurveState >.
Definition at line 95 of file lsstrategy.cpp.
References relevantTimes_.
{
        return relevantTimes_;
    }
void QuantLib::LongstaffSchwartzExerciseStrategy::reset () [virtual]
Implements QuantLib::ExerciseStrategy< CurveState >.
Definition at line 99 of file lsstrategy.cpp.
References basisSystem_, control_, currentIndex_, exercise_, newPrincipal_, principalInNumerairePortfolio_, QuantLib::MarketModelNodeDataProvider::reset(), and QuantLib::MarketModelExerciseValue::reset().
{
        exercise_->reset();
        control_->reset();
        basisSystem_->reset();
        currentIndex_ = 0;
        principalInNumerairePortfolio_ = newPrincipal_ = 1.0;
    }
Member Data Documentation
std::vector<std::vector<Real> > QuantLib::LongstaffSchwartzExerciseStrategy::basisCoefficients_ [private]
Definition at line 50 of file lsstrategy.hpp.
Referenced by exercise().
Clone<MarketModelBasisSystem> QuantLib::LongstaffSchwartzExerciseStrategy::basisSystem_ [private]
Definition at line 49 of file lsstrategy.hpp.
Referenced by exercise(), LongstaffSchwartzExerciseStrategy(), nextStep(), and reset().
std::vector<std::vector<Real> > QuantLib::LongstaffSchwartzExerciseStrategy::basisValues_ [mutable, private]
Definition at line 62 of file lsstrategy.hpp.
Referenced by exercise(), and LongstaffSchwartzExerciseStrategy().
Clone<MarketModelExerciseValue> QuantLib::LongstaffSchwartzExerciseStrategy::control_ [private]
Definition at line 52 of file lsstrategy.hpp.
Referenced by exercise(), LongstaffSchwartzExerciseStrategy(), nextStep(), and reset().
std::vector<MarketModelDiscounter> QuantLib::LongstaffSchwartzExerciseStrategy::controlDiscounters_ [private]
Definition at line 61 of file lsstrategy.hpp.
Referenced by exercise(), and LongstaffSchwartzExerciseStrategy().
Size QuantLib::LongstaffSchwartzExerciseStrategy::currentIndex_ [private]
Definition at line 55 of file lsstrategy.hpp.
Referenced by exercise(), nextStep(), and reset().
Clone<MarketModelExerciseValue> QuantLib::LongstaffSchwartzExerciseStrategy::exercise_ [private]
Definition at line 51 of file lsstrategy.hpp.
Referenced by exercise(), LongstaffSchwartzExerciseStrategy(), nextStep(), and reset().
std::vector<Size> QuantLib::LongstaffSchwartzExerciseStrategy::exerciseIndex_ [private]
Definition at line 63 of file lsstrategy.hpp.
Referenced by exercise(), and LongstaffSchwartzExerciseStrategy().
std::vector<Time> QuantLib::LongstaffSchwartzExerciseStrategy::exerciseTimes_ [private]
Definition at line 57 of file lsstrategy.hpp.
Referenced by exerciseTimes(), and LongstaffSchwartzExerciseStrategy().
std::valarray<bool> QuantLib::LongstaffSchwartzExerciseStrategy::isBasisTime_ [private]
Definition at line 58 of file lsstrategy.hpp.
Referenced by LongstaffSchwartzExerciseStrategy(), and nextStep().
std::valarray<bool> QuantLib::LongstaffSchwartzExerciseStrategy::isControlTime_ [private]
Definition at line 58 of file lsstrategy.hpp.
Referenced by LongstaffSchwartzExerciseStrategy(), and nextStep().
std::valarray<bool> QuantLib::LongstaffSchwartzExerciseStrategy::isExerciseTime_ [private]
Definition at line 59 of file lsstrategy.hpp.
Referenced by LongstaffSchwartzExerciseStrategy().
std::valarray<bool> QuantLib::LongstaffSchwartzExerciseStrategy::isRebateTime_ [private]
Definition at line 58 of file lsstrategy.hpp.
Referenced by LongstaffSchwartzExerciseStrategy(), and nextStep().
Real QuantLib::LongstaffSchwartzExerciseStrategy::newPrincipal_ [private]
Definition at line 56 of file lsstrategy.hpp.
Referenced by nextStep(), and reset().
std::vector<Size> QuantLib::LongstaffSchwartzExerciseStrategy::numeraires_ [private]
Definition at line 53 of file lsstrategy.hpp.
Referenced by exercise(), and nextStep().
Real QuantLib::LongstaffSchwartzExerciseStrategy::principalInNumerairePortfolio_ [private]
Definition at line 56 of file lsstrategy.hpp.
Referenced by exercise(), nextStep(), and reset().
std::vector<MarketModelDiscounter> QuantLib::LongstaffSchwartzExerciseStrategy::rebateDiscounters_ [private]
Definition at line 60 of file lsstrategy.hpp.
Referenced by exercise(), and LongstaffSchwartzExerciseStrategy().
std::vector<Time> QuantLib::LongstaffSchwartzExerciseStrategy::relevantTimes_ [private]
Definition at line 57 of file lsstrategy.hpp.
Referenced by LongstaffSchwartzExerciseStrategy(), and relevantTimes().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/callability/lsstrategy.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/callability/lsstrategy.cpp