QuantLib: QuantLib::LossDistBucketing Class Reference
QuantLib::LossDistBucketing Class Reference
Loss distribution with Hull-White bucketing.
#include <lossdistribution.hpp>
Public Member Functions
LossDistBucketing (Size nBuckets, Real maximum, Real epsilon=1e-6)
Distribution operator() (const std::vector< Real > &volumes, const std::vector< Real > &probabilities) const
Size buckets () const
Real maximum () const
Private Member Functions
int locateTargetBucket (Real loss, Size i0=0) const
Private Attributes
Size nBuckets_
Real maximum_
Real epsilon_
Detailed Description
Loss distribution with Hull-White bucketing.
Loss distribution with Hull-White bucketing
Loss distribution for varying volumes and probabilities of default, independence assumed.
The implementation of the loss distribution follows
John Hull and Alan White, "Valuation of a CDO and nth to default CDS without Monte Carlo simulation", Journal of Derivatives 12, 2, 2004.
Definition at line 184 of file lossdistribution.hpp.
Constructor & Destructor Documentation
QuantLib::LossDistBucketing::LossDistBucketing (Size nBuckets, Real maximum, Real epsilon = 1e-6) [inline]
Definition at line 186 of file lossdistribution.hpp.
            : nBuckets_(nBuckets), maximum_(maximum), epsilon_(epsilon) {}
Member Function Documentation
Size QuantLib::LossDistBucketing::buckets () const [inline, virtual]
Implements QuantLib::LossDist.
Definition at line 191 of file lossdistribution.hpp.
References nBuckets_.
{ return nBuckets_; }
int QuantLib::LossDistBucketing::locateTargetBucket (Real loss, Size i0 = 0) const [private]
Definition at line 292 of file lossdistribution.cpp.
References QL_REQUIRE.
{
    //--------------------------------------------------------------------------
        QL_REQUIRE (loss >= 0, "loss " << loss << " must be >= 0");
        Real dx = maximum_ / nBuckets_;
        for (Size i = i0; i < nBuckets_; i++)
            if (dx * i > loss + epsilon_) return i - 1;
        return nBuckets_;
    }
Real QuantLib::LossDistBucketing::maximum () const [inline, virtual]
Implements QuantLib::LossDist.
Definition at line 192 of file lossdistribution.hpp.
References maximum_.
{ return maximum_; }
Distribution QuantLib::LossDistBucketing::operator() (const std::vector< Real > & volumes, const std::vector< Real > & probabilities) const [virtual]
Implements QuantLib::LossDist.
Definition at line 227 of file lossdistribution.cpp.
References anonymous_namespace{marketmodel.cpp}::a, QuantLib::Distribution::addAverage(), QuantLib::Distribution::addDensity(), anonymous_namespace{interpolations.cpp}::f(), and QL_REQUIRE.
{
    //--------------------------------------------------------------------------
        QL_REQUIRE (nominals.size() == probabilities.size(), "sizes differ: "
                    << nominals.size() << " vs " << probabilities.size());
        vector<Real> p (nBuckets_, 0.0);
        vector<Real> a (nBuckets_, 0.0);
        vector<Real> ap (nBuckets_, 0.0);
        p[0] = 1.0;
        a[0] = 0.0;
        Real dx = maximum_ / nBuckets_;
        for (Size k = 1; k < nBuckets_; k++)
            a[k] = dx * k + dx/2;
        for (Size i = 0; i < nominals.size(); i++) {
            Real L = nominals[i];
            Real P = probabilities[i];
            for (int k = a.size()-1; k >= 0; k--) {
                if (p[k] > 0) {
                    int u = locateTargetBucket (a[k] + L, k);
                    QL_REQUIRE (u >= 0, "u=" << u << " at i=" << i << " k=" << k);
                    QL_REQUIRE (u >= k, "u=" << u << "<k=" << k << " at i=" << i);
                    Real dp = p[k] * P;
                    if (u == k)
                        a[k] += P * L;
                    else {
                        // no update of a[u] and p[u] if u is beyond grid end
                        if (u < int(nBuckets_)) {
                            // a[u] remains unchanged, if dp = 0
                            if (dp > 0.0) {
                                // on Windows, p[u]/dp could cause a NaN for
                                // some very small values of p[k].
                                // Writing the above as (p[u]/p[k])/P prevents
                                // the NaN. What can I say?
                                Real f = 1.0 / (1.0 + (p[u]/p[k]) / P);
                                a[u] = (1.0 - f) * a[u] + f * (a[k] + L);
                            }
                            /* formulation of Hull-White:
                               if (p[u] + dp > 0)
                                  a[u] = (p[u] * a[u] + dp * (a[k] + L))
                                         / (p[u] + dp);
                            */
                            p[u] += dp;
                        }
                        p[k] -= dp;
                    }
                }
                QL_REQUIRE(a[k] + epsilon_ >= dx * k && a[k] < dx * (k+1),
                           "a out of range at k=" << k << ", contract " << i);
            }
        }
        Distribution dist (nBuckets_, 0.0, maximum_);
        for (Size i = 0; i < nBuckets_; i++) {
            dist.addDensity (i, p[i] / dx);
            dist.addAverage (i, a[i]);
        }
        return dist;
    }
Member Data Documentation
Real QuantLib::LossDistBucketing::epsilon_ [private]
Definition at line 198 of file lossdistribution.hpp.
Real QuantLib::LossDistBucketing::maximum_ [private]
Definition at line 197 of file lossdistribution.hpp.
Referenced by maximum().
Size QuantLib::LossDistBucketing::nBuckets_ [private]
Definition at line 196 of file lossdistribution.hpp.
Referenced by buckets().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/lossdistribution.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/lossdistribution.cpp