QuantLib: QuantLib::GeometricAPOPathPricer Class Reference
QuantLib::GeometricAPOPathPricer Class Reference
#include <mc_discr_geom_av_price.hpp>
Public Member Functions
GeometricAPOPathPricer (Option::Type type, Real strike, DiscountFactor discount, Real runningProduct=1.0, Size pastFixings=0)
Real operator() (const Path &path) const
Private Attributes
PlainVanillaPayoff payoff_
DiscountFactor discount_
Real runningProduct_
Size pastFixings_
Detailed Description
Definition at line 68 of file mc_discr_geom_av_price.hpp.
Constructor & Destructor Documentation
QuantLib::GeometricAPOPathPricer::GeometricAPOPathPricer (Option::Type type, Real strike, DiscountFactor discount, Real runningProduct = 1.0, Size pastFixings = 0)
Definition at line 25 of file mc_discr_geom_av_price.cpp.
References QL_REQUIRE.
    : payoff_(type, strike), discount_(discount),
      runningProduct_(runningProduct), pastFixings_(pastFixings) {
        QL_REQUIRE(strike>=0.0, "negative strike given");
    }
Member Function Documentation
Real QuantLib::GeometricAPOPathPricer::operator() (const Path & path) const [virtual]
Implements QuantLib::PathPricer< Path >.
Definition at line 34 of file mc_discr_geom_av_price.cpp.
References discount_, QuantLib::Path::front(), QuantLib::Path::length(), QuantLib::TimeGrid::mandatoryTimes(), pastFixings_, payoff_, QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow(), QL_MAX_REAL, QL_REQUIRE, runningProduct_, and QuantLib::Path::timeGrid().
{
        Size n = path.length() - 1;
        QL_REQUIRE(n>0, "the path cannot be empty");
        Real averagePrice;
        Real product = runningProduct_;
        Size fixings = n+pastFixings_;
        if (path.timeGrid().mandatoryTimes()[0]==0.0) {
            fixings += 1;
            product *= path.front();
        }
        // care must be taken not to overflow product
        Real maxValue = QL_MAX_REAL;
        averagePrice = 1.0;
        for (Size i=1; i<n+1; i++) {
            Real price = path[i];
            if (product < maxValue/price) {
                product *= price;
            } else {
                averagePrice *= std::pow(product, 1.0/fixings);
                product = price;
            }
        }
        averagePrice *= std::pow(product, 1.0/fixings);
        return discount_ * payoff_(averagePrice);
    }
Member Data Documentation
DiscountFactor QuantLib::GeometricAPOPathPricer::discount_ [private]
Definition at line 78 of file mc_discr_geom_av_price.hpp.
Referenced by operator()().
Size QuantLib::GeometricAPOPathPricer::pastFixings_ [private]
Definition at line 80 of file mc_discr_geom_av_price.hpp.
Referenced by operator()().
PlainVanillaPayoff QuantLib::GeometricAPOPathPricer::payoff_ [private]
Definition at line 77 of file mc_discr_geom_av_price.hpp.
Referenced by operator()().
Real QuantLib::GeometricAPOPathPricer::runningProduct_ [private]
Definition at line 79 of file mc_discr_geom_av_price.hpp.
Referenced by operator()().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/asian/mc_discr_geom_av_price.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/asian/mc_discr_geom_av_price.cpp