QuantLib: QuantLib::FdmHestonOp Class Reference
QuantLib::FdmHestonOp Class Reference
#include <fdmhestonop.hpp>
Public Member Functions
FdmHestonOp (const boost::shared_ptr< FdmMesher > &mesher, const boost::shared_ptr< HestonProcess > &hestonProcess, const boost::shared_ptr< FdmQuantoHelper > &quantoHelper=boost::shared_ptr< FdmQuantoHelper >())
Size size () const
void setTime (Time t1, Time t2)
Time \(t1 <= t2\) is required.
Disposable< Array > apply (const Array &r) const
Disposable< Array > apply_mixed (const Array &r) const
Disposable< Array > apply_direction (Size direction, const Array &r) const
Disposable< Array > solve_splitting (Size direction, const Array &r, Real s) const
Disposable< Array > preconditioner (const Array &r, Real s) const
Disposable< SparseMatrix > toMatrix () const
Private Attributes
NinePointLinearOp correlationMap_
FdmHestonVariancePart dyMap_
FdmHestonEquityPart dxMap_
Detailed Description
Definition at line 78 of file fdmhestonop.hpp.
Constructor & Destructor Documentation
QuantLib::FdmHestonOp::FdmHestonOp (const boost::shared_ptr< FdmMesher > & mesher, const boost::shared_ptr< HestonProcess > & hestonProcess, const boost::shared_ptr< FdmQuantoHelper > & quantoHelper = boost::shared_ptr<FdmQuantoHelper>())
Definition at line 99 of file fdmhestonop.cpp.
    : correlationMap_(SecondOrderMixedDerivativeOp(0, 1, mesher)
                        .mult(hestonProcess->rho()*hestonProcess->sigma()
                                *mesher->locations(1))),
      dyMap_(mesher, hestonProcess->riskFreeRate().currentLink(),
              hestonProcess->sigma(),
              hestonProcess->kappa(),
              hestonProcess->theta()),
      dxMap_(mesher,
             hestonProcess->riskFreeRate().currentLink(),
             hestonProcess->dividendYield().currentLink(),
             quantoHelper) {
    }
Member Function Documentation
Disposable< Array > QuantLib::FdmHestonOp::apply (const Array & r) const [virtual]
Implements QuantLib::FdmLinearOp.
Definition at line 126 of file fdmhestonop.cpp.
References QuantLib::NinePointLinearOp::apply(), QuantLib::TripleBandLinearOp::apply(), correlationMap_, dxMap_, dyMap_, QuantLib::FdmHestonEquityPart::getMap(), and QuantLib::FdmHestonVariancePart::getMap().
{
        return dyMap_.getMap().apply(u) + dxMap_.getMap().apply(u)
              + correlationMap_.apply(u);
    }
Disposable< Array > QuantLib::FdmHestonOp::apply_direction (Size direction, const Array & r) const [virtual]
Implements QuantLib::FdmLinearOpComposite.
Definition at line 131 of file fdmhestonop.cpp.
References QuantLib::TripleBandLinearOp::apply(), dxMap_, dyMap_, QuantLib::FdmHestonEquityPart::getMap(), QuantLib::FdmHestonVariancePart::getMap(), and QL_FAIL.
{
        if (direction == 0)
            return dxMap_.getMap().apply(r);
        else if (direction == 1)
            return dyMap_.getMap().apply(r);
        else
            QL_FAIL("direction too large");
    }
Disposable< Array > QuantLib::FdmHestonOp::apply_mixed (const Array & r) const [virtual]
Implements QuantLib::FdmLinearOpComposite.
Definition at line 141 of file fdmhestonop.cpp.
References QuantLib::NinePointLinearOp::apply(), and correlationMap_.
{
        return correlationMap_.apply(r);
    }
Disposable< Array > QuantLib::FdmHestonOp::preconditioner (const Array & r, Real s) const [virtual]
Implements QuantLib::FdmLinearOpComposite.
Definition at line 160 of file fdmhestonop.cpp.
References solve_splitting().
{
        return solve_splitting(0, r, dt);
    }
void QuantLib::FdmHestonOp::setTime (Time t1, Time t2) [virtual]
Time \(t1 <= t2\) is required.
Implements QuantLib::FdmLinearOpComposite.
Definition at line 117 of file fdmhestonop.cpp.
References dxMap_, dyMap_, QuantLib::FdmHestonEquityPart::setTime(), and QuantLib::FdmHestonVariancePart::setTime().
{
        dxMap_.setTime(t1, t2);
        dyMap_.setTime(t1, t2);
    }
Size QuantLib::FdmHestonOp::size () const [virtual]
Implements QuantLib::FdmLinearOpComposite.
Definition at line 122 of file fdmhestonop.cpp.
{
        return 2;
    }
Disposable< Array > QuantLib::FdmHestonOp::solve_splitting (Size direction, const Array & r, Real s) const [virtual]
Implements QuantLib::FdmLinearOpComposite.
Definition at line 146 of file fdmhestonop.cpp.
References dxMap_, dyMap_, QuantLib::FdmHestonEquityPart::getMap(), QuantLib::FdmHestonVariancePart::getMap(), QL_FAIL, and QuantLib::TripleBandLinearOp::solve_splitting().
Referenced by preconditioner().
{
        if (direction == 0) {
            return dxMap_.getMap().solve_splitting(r, a, 1.0);
        }
        else if (direction == 1) {
            return dyMap_.getMap().solve_splitting(r, a, 1.0);
        }
        else
            QL_FAIL("direction too large");
    }
Disposable< SparseMatrix > QuantLib::FdmHestonOp::toMatrix () const [virtual]
Reimplemented from QuantLib::FdmLinearOp.
Definition at line 166 of file fdmhestonop.cpp.
References correlationMap_, dxMap_, dyMap_, QuantLib::FdmHestonEquityPart::getMap(), QuantLib::FdmHestonVariancePart::getMap(), QuantLib::NinePointLinearOp::toMatrix(), and QuantLib::TripleBandLinearOp::toMatrix().
{
        SparseMatrix retVal =
              dyMap_.getMap().toMatrix() + dxMap_.getMap().toMatrix()
            + correlationMap_.toMatrix();
        return retVal;
    }
Member Data Documentation
NinePointLinearOp QuantLib::FdmHestonOp::correlationMap_ [private]
Definition at line 102 of file fdmhestonop.hpp.
Referenced by apply(), apply_mixed(), and toMatrix().
FdmHestonEquityPart QuantLib::FdmHestonOp::dxMap_ [private]
Definition at line 104 of file fdmhestonop.hpp.
Referenced by apply(), apply_direction(), setTime(), solve_splitting(), and toMatrix().
FdmHestonVariancePart QuantLib::FdmHestonOp::dyMap_ [private]
Definition at line 103 of file fdmhestonop.hpp.
Referenced by apply(), apply_direction(), setTime(), solve_splitting(), and toMatrix().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/operators/fdmhestonop.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/operators/fdmhestonop.cpp