QuantLib: QuantLib::LiborForwardModelProcess Class Reference
QuantLib::LiborForwardModelProcess Class Reference
libor-forward-model process
#include <lfmprocess.hpp>
Public Member Functions
LiborForwardModelProcess (Size size, const boost::shared_ptr< IborIndex > &index)
Disposable< Array > initialValues () const
returns the initial values of the state variables
Disposable< Array > drift (Time t, const Array &x) const
returns the drift part of the equation, i.e., \(\mu(t, \mathrm{x}_t) \)
Disposable< Matrix > diffusion (Time t, const Array &x) const
returns the diffusion part of the equation, i.e. \(\sigma(t, \mathrm{x}_t) \)
Disposable< Matrix > covariance (Time t0, const Array &x0, Time dt) const
Disposable< Array > apply (const Array &x0, const Array &dx) const
Disposable< Array > evolve (Time t0, const Array &x0, Time dt, const Array &dw) const
Size size () const
returns the number of dimensions of the stochastic process
Size factors () const
returns the number of independent factors of the process
boost::shared_ptr< IborIndex > index () const
Leg cashFlows (Real amount=1.0) const
void setCovarParam (const boost::shared_ptr< LfmCovarianceParameterization > &param)
boost::shared_ptr
< LfmCovarianceParameterization > covarParam () const
Size nextIndexReset (Time t) const
const std::vector< Time > & fixingTimes () const
const std::vector< Date > & fixingDates () const
const std::vector< Time > & accrualStartTimes () const
const std::vector< Time > & accrualEndTimes () const
std::vector< DiscountFactor > discountBond (const std::vector< Rate > &rates) const
Private Attributes
Size size_
const boost::shared_ptr
< IborIndex > index_
boost::shared_ptr
< LfmCovarianceParameterization > lfmParam_
Array initialValues_
std::vector< Time > fixingTimes_
std::vector< Date > fixingDates_
std::vector< Time > accrualStartTimes_
std::vector< Time > accrualEndTimes_
std::vector< Time > accrualPeriod_
Array m1
Array m2
Detailed Description
libor-forward-model process
stochastic process of a libor forward model using the rolling forward measure incl. predictor-corrector step
References:
Glasserman, Paul, 2004, Monte Carlo Methods in Financial Engineering, Springer, Section 3.7
Antoon Pelsser, 2000, Efficient Methods for Valuing Interest Rate Derivatives, Springer, 8
Hull, John, White, Alan, 1999, Forward Rate Volatilities, Swap Rate Volatilities and the Implementation of the Libor Market Model (<http://www.rotman.utoronto.ca/~amackay/fin/libormktmodel2.pdf>)
Test:
the correctness is tested by Monte-Carlo reproduction of caplet & ratchet NPVs and comparison with Black pricing.
Warning:
this class does not work correctly with Visual C++ 6.
Definition at line 58 of file lfmprocess.hpp.
Constructor & Destructor Documentation
QuantLib::LiborForwardModelProcess::LiborForwardModelProcess (Size size, const boost::shared_ptr< IborIndex > & index)
Definition at line 33 of file lfmprocess.cpp.
References accrualEndTimes_, accrualPeriod_, accrualStartTimes_, cashFlows(), anonymous_namespace{marketmodel.cpp}::dayCounter, fixingDates_, fixingTimes_, index_, initialValues_, QL_REQUIRE, size_, anonymous_namespace{marketmodel.cpp}::startDate, and QuantLib::DayCounter::yearFraction().
    : StochasticProcess(boost::shared_ptr<discretization>(
                                                    new EulerDiscretization)),
      size_             (size),
      index_            (index),
      initialValues_    (size_),
      fixingTimes_      (size_),
      fixingDates_      (size_),
      accrualStartTimes_(size),
      accrualEndTimes_  (size),
      accrualPeriod_    (size_),
      m1(size_), m2(size_) {
        const DayCounter dayCounter = index_->dayCounter();
        const Leg flows = cashFlows();
        QL_REQUIRE(size_ == flows.size(), "wrong number of cashflows");
        Date settlement = index_->forwardingTermStructure()->referenceDate();
        const Date startDate =
            boost::dynamic_pointer_cast<IborCoupon>(flows[0])->fixingDate();
        for (Size i = 0; i < size_; ++i) {
            const boost::shared_ptr<IborCoupon> coupon =
               boost::dynamic_pointer_cast<IborCoupon>(flows[i]);
            QL_REQUIRE(coupon->date() == coupon->accrualEndDate(),
                       "irregular coupon types are not suppported");
            initialValues_[i] = coupon->rate();
            accrualPeriod_[i] = coupon->accrualPeriod();
            fixingDates_[i] = coupon->fixingDate();
            fixingTimes_[i] =
                dayCounter.yearFraction(startDate, coupon->fixingDate());
            accrualStartTimes_[i] =
                dayCounter.yearFraction(settlement,coupon->accrualStartDate());
            accrualEndTimes_[i]   =
                dayCounter.yearFraction(settlement,coupon->accrualEndDate());
        }
    }
Member Function Documentation
const std::vector< Time > & QuantLib::LiborForwardModelProcess::accrualEndTimes () const
Definition at line 219 of file lfmprocess.cpp.
References accrualEndTimes_.
{
        return accrualEndTimes_;
    }
const std::vector< Time > & QuantLib::LiborForwardModelProcess::accrualStartTimes () const
Definition at line 214 of file lfmprocess.cpp.
References accrualStartTimes_.
{
        return accrualStartTimes_;
    }
Disposable< Array > QuantLib::LiborForwardModelProcess::apply (const Array & x0, const Array & dx) const [virtual]
applies a change to the asset value. By default, it returns \(\mathrm{x} + \Delta \mathrm{x} \).
Reimplemented from QuantLib::StochasticProcess.
Definition at line 104 of file lfmprocess.cpp.
References size_.
{
        Array tmp(size_);
        for (Size k=0; k<size_; ++k) {
            tmp[k] = x0[k] * std::exp(dx[k]);
        }
        return tmp;
    }
Leg QuantLib::LiborForwardModelProcess::cashFlows (Real amount = 1.0) const
Definition at line 181 of file lfmprocess.cpp.
References QuantLib::DateGeneration::Forward, index_, size_, QuantLib::IborLeg::withNotionals(), and QuantLib::IborLeg::withPaymentDayCounter().
Referenced by LiborForwardModelProcess().
{
        Date refDate = index_->forwardingTermStructure()->referenceDate();
        Schedule schedule(refDate,
                          refDate + Period(index_->tenor().length()*size_,
                                           index_->tenor().units()),
                          index_->tenor(), index_->fixingCalendar(),
                          index_->businessDayConvention(),
                          index_->businessDayConvention(),
                          DateGeneration::Forward, false);
        return IborLeg(schedule,index_)
            .withNotionals(amount)
            .withPaymentDayCounter(index_->dayCounter())
            .withPaymentAdjustment(index_->businessDayConvention())
            .withFixingDays(index_->fixingDays());
    }
Disposable< Matrix > QuantLib::LiborForwardModelProcess::covariance (Time t0, const Array & x0, Time dt) const [virtual]
returns the covariance \(V(\mathrm{x}_{t_0 + \Delta t} | \mathrm{x}_{t_0} = \mathrm{x}_0) \) of the process after a time interval \(\Delta t \) according to the given discretization. This method can be overridden in derived classes which want to hard-code a particular discretization.
Reimplemented from QuantLib::StochasticProcess.
Definition at line 99 of file lfmprocess.cpp.
References QuantLib::anonymous_namespace{yieldtermstructure.cpp}::dt, and lfmParam_.
Referenced by drift(), and evolve().
{
        return lfmParam_->covariance(t, x)*dt;
    }
boost::shared_ptr< LfmCovarianceParameterization > QuantLib::LiborForwardModelProcess::covarParam () const
Definition at line 171 of file lfmprocess.cpp.
References lfmParam_.
{
        return lfmParam_;
    }
Disposable< Matrix > QuantLib::LiborForwardModelProcess::diffusion (Time t, const Array & x) const [virtual]
returns the diffusion part of the equation, i.e. \(\sigma(t, \mathrm{x}_t) \)
Implements QuantLib::StochasticProcess.
Definition at line 95 of file lfmprocess.cpp.
References lfmParam_.
{
        return lfmParam_->diffusion(t, x);
    }
std::vector< DiscountFactor > QuantLib::LiborForwardModelProcess::discountBond (const std::vector< Rate > & rates) const
Definition at line 228 of file lfmprocess.cpp.
References accrualPeriod_, and size_.
{
        std::vector<DiscountFactor> discountFactors(size_);
        discountFactors[0] = 1.0/(1.0 + rates[0]*accrualPeriod_[0]);
        for (Size i = 1; i < size_; ++i) {
            discountFactors[i] =
                discountFactors[i-1]/(1.0 + rates[i]*accrualPeriod_[i]);
        }
        return discountFactors;
    }
Disposable< Array > QuantLib::LiborForwardModelProcess::drift (Time t, const Array & x) const [virtual]
returns the drift part of the equation, i.e., \(\mu(t, \mathrm{x}_t) \)
Implements QuantLib::StochasticProcess.
Definition at line 77 of file lfmprocess.cpp.
References accrualPeriod_, QuantLib::Array::begin(), QuantLib::Matrix::column_begin(), covariance(), anonymous_namespace{interpolations.cpp}::f(), QuantLib::dsd::inner_product(), lfmParam_, m1, nextIndexReset(), and size_.
{
        Array f(size_, 0.0);
        Matrix covariance(lfmParam_->covariance(t, x));
        const Size m = nextIndexReset(t);
        for (Size k=m; k<size_; ++k) {
            m1[k] = accrualPeriod_[k]*x[k]/(1+accrualPeriod_[k]*x[k]);
            f[k]  = std::inner_product(m1.begin()+m, m1.begin()+k+1,
                                       covariance.column_begin(k)+m,0.0)
                    - 0.5*covariance[k][k];
        }
        return f;
    }
Disposable< Array > QuantLib::LiborForwardModelProcess::evolve (Time t0, const Array & x0, Time dt, const Array & dw) const [virtual]
returns the asset value after a time interval \(\Delta t \) according to the given discretization. By default, it returns
\[ E(\mathrm{x}_0,t_0,\Delta t) + S(\mathrm{x}_0,t_0,\Delta t) \cdot \Delta \mathrm{w} \]
where \(E \) is the expectation and \(S \) the standard deviation.
Reimplemented from QuantLib::StochasticProcess.
Definition at line 115 of file lfmprocess.cpp.
References accrualPeriod_, QuantLib::Array::begin(), QuantLib::Matrix::column_begin(), covariance(), anonymous_namespace{marketmodel.cpp}::d, anonymous_namespace{interpolations.cpp}::f(), QuantLib::dsd::inner_product(), lfmParam_, m1, m2, nextIndexReset(), QuantLib::Matrix::row_begin(), QuantLib::Matrix::row_end(), and size_.
{
        /* predictor-corrector step to reduce discretization errors.
           Short - but slow - solution would be
           Array rnd_0     = stdDeviation(t0, x0, dt)*dw;
           Array drift_0   = discretization_->drift(*this, t0, x0, dt);
           return apply(x0, ( drift_0 + discretization_
                ->drift(*this,t0,apply(x0, drift_0 + rnd_0),dt) )*0.5 + rnd_0);
           The following implementation does the same but is faster.
        */
        const Size m   = nextIndexReset(t0);
        const Real sdt = std::sqrt(dt);
        Array f(x0);
        Matrix diff       = lfmParam_->diffusion(t0, x0);
        Matrix covariance = lfmParam_->covariance(t0, x0);
        for (Size k=m; k<size_; ++k) {
            const Real y = accrualPeriod_[k]*x0[k];
            m1[k] = y/(1+y);
            const Real d = (
                std::inner_product(m1.begin()+m, m1.begin()+k+1,
                                   covariance.column_begin(k)+m,0.0)
                -0.5*covariance[k][k]) * dt;
            const Real r = std::inner_product(
                diff.row_begin(k), diff.row_end(k), dw.begin(), 0.0)*sdt;
            const Real x = y*std::exp(d + r);
            m2[k] = x/(1+x);
            f[k] = x0[k] * std::exp(0.5*(d+
                 (std::inner_product(m2.begin()+m, m2.begin()+k+1,
                                     covariance.column_begin(k)+m,0.0)
                  -0.5*covariance[k][k])*dt)+ r);
        }
        return f;
    }
Size QuantLib::LiborForwardModelProcess::factors () const [virtual]
returns the number of independent factors of the process
Reimplemented from QuantLib::StochasticProcess.
Definition at line 201 of file lfmprocess.cpp.
References lfmParam_.
{
        return lfmParam_->factors();
    }
const std::vector< Date > & QuantLib::LiborForwardModelProcess::fixingDates () const
Definition at line 209 of file lfmprocess.cpp.
References fixingDates_.
{
        return fixingDates_;
    }
const std::vector< Time > & QuantLib::LiborForwardModelProcess::fixingTimes () const
Definition at line 205 of file lfmprocess.cpp.
References fixingTimes_.
Referenced by LiborMarketModelProcessTest::testInitialisation().
{
        return fixingTimes_;
    }
boost::shared_ptr< IborIndex > QuantLib::LiborForwardModelProcess::index () const
Definition at line 176 of file lfmprocess.cpp.
References index_.
{
        return index_;
    }
Disposable< Array > QuantLib::LiborForwardModelProcess::initialValues () const [virtual]
returns the initial values of the state variables
Implements QuantLib::StochasticProcess.
Definition at line 160 of file lfmprocess.cpp.
References initialValues_.
{
        Array tmp = initialValues_;
        return tmp;
    }
Size QuantLib::LiborForwardModelProcess::nextIndexReset (Time t) const
Definition at line 223 of file lfmprocess.cpp.
References fixingTimes_, and anonymous_namespace{quantlibbenchmark.cpp}::t.
Referenced by drift(), evolve(), and LiborMarketModelProcessTest::testInitialisation().
{
        return std::upper_bound(fixingTimes_.begin(), fixingTimes_.end(), t)
                 - fixingTimes_.begin();
    }
void QuantLib::LiborForwardModelProcess::setCovarParam (const boost::shared_ptr< LfmCovarianceParameterization > & param)
Definition at line 165 of file lfmprocess.cpp.
References lfmParam_.
{
        lfmParam_ = param;
    }
Size QuantLib::LiborForwardModelProcess::size () const [virtual]
returns the number of dimensions of the stochastic process
Implements QuantLib::StochasticProcess.
Definition at line 197 of file lfmprocess.cpp.
References size_.
{
        return size_;
    }
Member Data Documentation
std::vector<Time> QuantLib::LiborForwardModelProcess::accrualEndTimes_ [private]
Definition at line 106 of file lfmprocess.hpp.
Referenced by accrualEndTimes(), and LiborForwardModelProcess().
std::vector<Time> QuantLib::LiborForwardModelProcess::accrualPeriod_ [private]
Definition at line 107 of file lfmprocess.hpp.
Referenced by discountBond(), drift(), evolve(), and LiborForwardModelProcess().
std::vector<Time> QuantLib::LiborForwardModelProcess::accrualStartTimes_ [private]
Definition at line 105 of file lfmprocess.hpp.
Referenced by accrualStartTimes(), and LiborForwardModelProcess().
std::vector<Date> QuantLib::LiborForwardModelProcess::fixingDates_ [private]
Definition at line 104 of file lfmprocess.hpp.
Referenced by fixingDates(), and LiborForwardModelProcess().
std::vector<Time> QuantLib::LiborForwardModelProcess::fixingTimes_ [private]
Definition at line 103 of file lfmprocess.hpp.
Referenced by fixingTimes(), LiborForwardModelProcess(), and nextIndexReset().
const boost::shared_ptr<IborIndex> QuantLib::LiborForwardModelProcess::index_ [private]
Definition at line 98 of file lfmprocess.hpp.
Referenced by cashFlows(), index(), and LiborForwardModelProcess().
Array QuantLib::LiborForwardModelProcess::initialValues_ [private]
Definition at line 101 of file lfmprocess.hpp.
Referenced by initialValues(), and LiborForwardModelProcess().
boost::shared_ptr<LfmCovarianceParameterization> QuantLib::LiborForwardModelProcess::lfmParam_ [private]
Definition at line 99 of file lfmprocess.hpp.
Referenced by covariance(), covarParam(), diffusion(), drift(), evolve(), factors(), and setCovarParam().
Array QuantLib::LiborForwardModelProcess::m1 [mutable, private]
Definition at line 109 of file lfmprocess.hpp.
Referenced by drift(), and evolve().
Array QuantLib::LiborForwardModelProcess::m2 [mutable, private]
Definition at line 109 of file lfmprocess.hpp.
Referenced by evolve().
Size QuantLib::LiborForwardModelProcess::size_ [private]
Definition at line 96 of file lfmprocess.hpp.
Referenced by apply(), cashFlows(), discountBond(), drift(), evolve(), LiborForwardModelProcess(), and size().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/legacy/libormarketmodels/lfmprocess.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/legacy/libormarketmodels/lfmprocess.cpp