QuantLib: QuantLib::Observable Class Reference
QuantLib::Observable Class Reference
Object that notifies its changes to a set of observers.
#include <observable.hpp>
Public Member Functions
Observable ()
Observable (const Observable &)
Observable & operator= (const Observable &)
virtual ~Observable ()
void notifyObservers ()
Private Types
typedef std::set< Observer * >
::iterator iterator
Private Member Functions
std::pair< iterator, bool > registerObserver (Observer *)
Size unregisterObserver (Observer *)
Private Attributes
std::set< Observer * > observers_
Friends
class Observer
Detailed Description
Object that notifies its changes to a set of observers.
Definition at line 42 of file observable.hpp.
Member Typedef Documentation
typedef std::set<Observer*>::iterator QuantLib::Observable::iterator [private]
Reimplemented in QuantLib::JointStochasticProcess, and QuantLib::CompositeInstrument.
Definition at line 55 of file observable.hpp.
Constructor & Destructor Documentation
QuantLib::Observable::Observable () [inline]
Definition at line 46 of file observable.hpp.
{}
QuantLib::Observable::Observable (const Observable &) [inline]
Definition at line 88 of file observable.hpp.
{
        // the observer set is not copied; no observer asked to
        // register with this object
    }
virtual QuantLib::Observable::~Observable () [inline, virtual]
Definition at line 49 of file observable.hpp.
{}
Member Function Documentation
void QuantLib::Observable::notifyObservers () [inline]
This method should be called at the end of non-const methods or when the programmer desires to notify any changes.
Definition at line 118 of file observable.hpp.
References observers_, and QL_ENSURE.
Referenced by QuantLib::CalibratedModel::calibrate(), operator=(), QuantLib::LazyObject::recalculate(), QuantLib::ForwardMeasureProcess::setForwardMeasureTime(), QuantLib::ForwardMeasureProcess1D::setForwardMeasureTime(), QuantLib::ExtendedBlackVarianceCurve::setInterpolation(), QuantLib::ExtendedBlackVarianceSurface::setInterpolation(), QuantLib::BlackVarianceCurve::setInterpolation(), QuantLib::BlackVarianceSurface::setInterpolation(), QuantLib::InflationTermStructure::setSeasonality(), QuantLib::SimpleQuote::setValue(), QuantLib::RecoveryRateQuote::setValue(), QuantLib::FdmAffineModelTermStructure::setVariable(), QuantLib::LazyObject::unfreeze(), QuantLib::Claim::update(), QuantLib::LazyObject::update(), QuantLib::ForwardValueQuote::update(), QuantLib::LastFixingQuote::update(), QuantLib::SpreadedSmileSection::update(), QuantLib::CalibrationHelper::update(), QuantLib::Handle< T >::Link::update(), QuantLib::CommodityIndex::update(), QuantLib::FuturesConvAdjustmentQuote::update(), QuantLib::FloatingRateCouponPricer::update(), QuantLib::InterestRateIndex::update(), QuantLib::CotSwapToFwdAdapterFactory::update(), QuantLib::FwdToCotSwapAdapterFactory::update(), QuantLib::ExtendedBlackVarianceCurve::update(), QuantLib::ConstantRecoveryModel::update(), QuantLib::DeltaVolQuote::update(), QuantLib::ExtendedBlackVarianceSurface::update(), QuantLib::GenericEngine< SimpleChooserOption::arguments, SimpleChooserOption::results >::update(), QuantLib::InflationCouponPricer::update(), QuantLib::IndexedCashFlow::update(), QuantLib::CappedFlooredCoupon::update(), QuantLib::SabrVolSurface::update(), QuantLib::FlatVolFactory::update(), QuantLib::CalibratedModel::update(), QuantLib::InflationCoupon::update(), QuantLib::InflationIndex::update(), QuantLib::FloatingRateCoupon::update(), QuantLib::TermStructure::update(), QuantLib::RendistatoBasket::update(), QuantLib::CappedFlooredYoYInflationCoupon::update(), QuantLib::DigitalCoupon::update(), and QuantLib::StochasticProcess::update().
{
        bool successful = true;
        std::string errMsg;
        for (iterator i=observers_.begin(); i!=observers_.end(); ++i) {
            try {
                (*i)->update();
            } catch (std::exception& e) {
                // quite a dilemma. If we don't catch the exception,
                // other observers will not receive the notification
                // and might be left in an incorrect state. If we do
                // catch it and continue the loop (as we do here) we
                // lose the exception. The least evil might be to try
                // and notify all observers, while raising an
                // exception if something bad happened.
                successful = false;
                errMsg = e.what();
            } catch (...) {
                successful = false;
            }
        }
        QL_ENSURE(successful,
                  "could not notify one or more observers: " << errMsg);
    }
Observable & QuantLib::Observable::operator= (const Observable & o) [inline]
Warning:
notification is sent before the copy constructor has a chance of actually change the data members. Therefore, observers whose update() method tries to use their observables will not see the updated values. It is suggested that the update() method just raise a flag in order to trigger a later recalculation.
Definition at line 101 of file observable.hpp.
References notifyObservers().
{
        // as above, the observer set is not copied. Moreover,
        // observers of this object must be notified of the change
        if (&o != this)
            notifyObservers();
        return *this;
    }
std::pair< std::set< Observer * >::iterator, bool > QuantLib::Observable::registerObserver (Observer * o) [inline, private]
Definition at line 110 of file observable.hpp.
References observers_.
{
        return observers_.insert(o);
    }
Size QuantLib::Observable::unregisterObserver (Observer * o) [inline, private]
Definition at line 114 of file observable.hpp.
References observers_.
{
        return observers_.erase(o);
    }
Friends And Related Function Documentation
friend class Observer [friend]
Definition at line 43 of file observable.hpp.
Member Data Documentation
std::set<Observer*> QuantLib::Observable::observers_ [private]
Definition at line 58 of file observable.hpp.
Referenced by notifyObservers(), registerObserver(), and unregisterObserver().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/patterns/observable.hpp