QuantLib: QuantLib::AnalyticContinuousFixedLookbackEngine Class Reference
QuantLib::AnalyticContinuousFixedLookbackEngine Class Reference
Pricing engine for European continuous fixed-strike lookback.
#include <analyticcontinuousfixedlookback.hpp>
Public Member Functions
AnalyticContinuousFixedLookbackEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > &process)
void calculate () const
Private Member Functions
Real underlying () const
Real strike () const
Time residualTime () const
Volatility volatility () const
Real minmax () const
Real stdDeviation () const
Rate riskFreeRate () const
DiscountFactor riskFreeDiscount () const
Rate dividendYield () const
DiscountFactor dividendDiscount () const
Real A (Real eta) const
Real B (Real eta) const
Real C (Real eta) const
Private Attributes
boost::shared_ptr
< GeneralizedBlackScholesProcess > process_
CumulativeNormalDistribution f_
Detailed Description
Pricing engine for European continuous fixed-strike lookback.
Formula from "Option Pricing Formulas", E.G. Haug, McGraw-Hill, 1998, p.63-64
Test:
returned values are verified against results from literature
Definition at line 42 of file analyticcontinuousfixedlookback.hpp.
Constructor & Destructor Documentation
QuantLib::AnalyticContinuousFixedLookbackEngine::AnalyticContinuousFixedLookbackEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > & process)
Definition at line 27 of file analyticcontinuousfixedlookback.cpp.
References process_, and QuantLib::Observer::registerWith().
    : process_(process) {
        registerWith(process_);
    }
Member Function Documentation
Real QuantLib::AnalyticContinuousFixedLookbackEngine::A (Real eta) const [private]
Definition at line 113 of file analyticcontinuousfixedlookback.cpp.
References dividendDiscount(), dividendYield(), f_, minmax(), QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow(), riskFreeDiscount(), riskFreeRate(), stdDeviation(), underlying(), and volatility().
Referenced by calculate().
{
        Volatility vol = volatility();
        Real lambda = 2.0*(riskFreeRate() - dividendYield())/(vol*vol);
        Real ss = underlying()/minmax();
        Real d1 =
            std::log(ss)/stdDeviation() + 0.5*(lambda+1.0)*stdDeviation();
        Real N1 = f_(eta*d1);
        Real N2 = f_(eta*(d1-stdDeviation()));
        Real N3 = f_(eta*(d1-lambda*stdDeviation()));
        Real N4 = f_(eta*d1);
        Real powss = std::pow(ss, -lambda);
        return eta*(underlying() * dividendDiscount() * N1 -
                    minmax() * riskFreeDiscount() * N2 -
                    underlying() * riskFreeDiscount() *
                    (powss * N3 - dividendDiscount()* N4/riskFreeDiscount())/
            lambda);
    }
Real QuantLib::AnalyticContinuousFixedLookbackEngine::B (Real eta) const [private]
Definition at line 131 of file analyticcontinuousfixedlookback.cpp.
References dividendDiscount(), dividendYield(), f_, QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow(), riskFreeDiscount(), riskFreeRate(), stdDeviation(), strike(), underlying(), and volatility().
Referenced by calculate().
{
        Volatility vol = volatility();
        Real lambda = 2.0*(riskFreeRate() - dividendYield())/(vol*vol);
        Real ss = underlying()/strike();
        Real d1 =
            std::log(ss)/stdDeviation() + 0.5*(lambda+1.0)*stdDeviation();
        Real N1 = f_(eta*d1);
        Real N2 = f_(eta*(d1-stdDeviation()));
        Real N3 = f_(eta*(d1-lambda*stdDeviation()));
        Real N4 = f_(eta*d1);
        Real powss = std::pow(ss, -lambda);
        return eta*(underlying() * dividendDiscount() * N1 -
                    strike() * riskFreeDiscount() * N2 -
                    underlying() * riskFreeDiscount() *
                    (powss * N3 - dividendDiscount()* N4/riskFreeDiscount())/
            lambda);
    }
Real QuantLib::AnalyticContinuousFixedLookbackEngine::C (Real eta) const [private]
Definition at line 149 of file analyticcontinuousfixedlookback.cpp.
References minmax(), riskFreeDiscount(), and strike().
Referenced by calculate().
{
        return eta*(riskFreeDiscount()*(minmax() - strike()));
    }
void QuantLib::AnalyticContinuousFixedLookbackEngine::calculate () const [virtual]
Implements QuantLib::PricingEngine.
Definition at line 33 of file analyticcontinuousfixedlookback.cpp.
References A(), QuantLib::GenericEngine< ContinuousFixedLookbackOption::arguments, ContinuousFixedLookbackOption::results >::arguments_, B(), C(), QuantLib::Option::Call, minmax(), process_, QuantLib::Option::Put, QL_FAIL, QL_REQUIRE, QuantLib::GenericEngine< ContinuousFixedLookbackOption::arguments, ContinuousFixedLookbackOption::results >::results_, strike(), and QuantLib::Instrument::results::value.
{
        boost::shared_ptr<PlainVanillaPayoff> payoff =
            boost::dynamic_pointer_cast<PlainVanillaPayoff>(arguments_.payoff);
        QL_REQUIRE(payoff, "Non-plain payoff given");
        QL_REQUIRE(process_->x0() > 0.0, "negative or null underlying");
        Real strike = payoff->strike();
        switch (payoff->optionType()) {
          case Option::Call:
            QL_REQUIRE(payoff->strike()>=0.0,
                       "Strike must be positive or null");
            if (strike <= minmax())
                results_.value = A(1) + C(1);
            else
                results_.value = B(1);
            break;
          case Option::Put:
            QL_REQUIRE(payoff->strike()>0.0,
                       "Strike must be positive");
            if (strike >= minmax())
                results_.value = A(-1) + C(-1);
            else
                results_.value = B(-1);
            break;
          default:
            QL_FAIL("Unknown type");
        }
    }
DiscountFactor QuantLib::AnalyticContinuousFixedLookbackEngine::dividendDiscount () const [private]
Definition at line 104 of file analyticcontinuousfixedlookback.cpp.
References process_, and residualTime().
Referenced by A(), and B().
{
        return process_->dividendYield()->discount(residualTime());
    }
Rate QuantLib::AnalyticContinuousFixedLookbackEngine::dividendYield () const [private]
Definition at line 99 of file analyticcontinuousfixedlookback.cpp.
References QuantLib::Continuous, QuantLib::NoFrequency, process_, and residualTime().
Referenced by A(), and B().
{
        return process_->dividendYield()->zeroRate(residualTime(),
                                                   Continuous, NoFrequency);
    }
Real QuantLib::AnalyticContinuousFixedLookbackEngine::minmax () const [private]
Definition at line 109 of file analyticcontinuousfixedlookback.cpp.
References QuantLib::GenericEngine< ContinuousFixedLookbackOption::arguments, ContinuousFixedLookbackOption::results >::arguments_, and QuantLib::ContinuousFixedLookbackOption::arguments::minmax.
Referenced by A(), C(), and calculate().
{
        return arguments_.minmax;
    }
Time QuantLib::AnalyticContinuousFixedLookbackEngine::residualTime () const [private]
Definition at line 77 of file analyticcontinuousfixedlookback.cpp.
References QuantLib::GenericEngine< ContinuousFixedLookbackOption::arguments, ContinuousFixedLookbackOption::results >::arguments_, and process_.
Referenced by dividendDiscount(), dividendYield(), riskFreeDiscount(), riskFreeRate(), stdDeviation(), and volatility().
{
        return process_->time(arguments_.exercise->lastDate());
    }
DiscountFactor QuantLib::AnalyticContinuousFixedLookbackEngine::riskFreeDiscount () const [private]
Definition at line 94 of file analyticcontinuousfixedlookback.cpp.
References process_, and residualTime().
Referenced by A(), B(), and C().
{
        return process_->riskFreeRate()->discount(residualTime());
    }
Rate QuantLib::AnalyticContinuousFixedLookbackEngine::riskFreeRate () const [private]
Definition at line 89 of file analyticcontinuousfixedlookback.cpp.
References QuantLib::Continuous, QuantLib::NoFrequency, process_, and residualTime().
Referenced by A(), and B().
{
        return process_->riskFreeRate()->zeroRate(residualTime(), Continuous,
                                                  NoFrequency);
    }
Real QuantLib::AnalyticContinuousFixedLookbackEngine::stdDeviation () const [private]
Definition at line 85 of file analyticcontinuousfixedlookback.cpp.
References residualTime(), and volatility().
Referenced by A(), and B().
{
        return volatility() * std::sqrt(residualTime());
    }
Real QuantLib::AnalyticContinuousFixedLookbackEngine::strike () const [private]
Definition at line 70 of file analyticcontinuousfixedlookback.cpp.
References QuantLib::GenericEngine< ContinuousFixedLookbackOption::arguments, ContinuousFixedLookbackOption::results >::arguments_, and QL_REQUIRE.
Referenced by B(), C(), calculate(), and volatility().
{
        boost::shared_ptr<PlainVanillaPayoff> payoff =
            boost::dynamic_pointer_cast<PlainVanillaPayoff>(arguments_.payoff);
        QL_REQUIRE(payoff, "Non-plain payoff given");
        return payoff->strike();
    }
Real QuantLib::AnalyticContinuousFixedLookbackEngine::underlying () const [private]
Definition at line 66 of file analyticcontinuousfixedlookback.cpp.
References process_.
Referenced by A(), and B().
{
        return process_->x0();
    }
Volatility QuantLib::AnalyticContinuousFixedLookbackEngine::volatility () const [private]
Definition at line 81 of file analyticcontinuousfixedlookback.cpp.
References process_, residualTime(), and strike().
Referenced by A(), B(), and stdDeviation().
{
        return process_->blackVolatility()->blackVol(residualTime(), strike());
    }
Member Data Documentation
CumulativeNormalDistribution QuantLib::AnalyticContinuousFixedLookbackEngine::f_ [private]
Definition at line 50 of file analyticcontinuousfixedlookback.hpp.
Referenced by A(), and B().
boost::shared_ptr<GeneralizedBlackScholesProcess> QuantLib::AnalyticContinuousFixedLookbackEngine::process_ [private]
Definition at line 49 of file analyticcontinuousfixedlookback.hpp.
Referenced by AnalyticContinuousFixedLookbackEngine(), calculate(), dividendDiscount(), dividendYield(), residualTime(), riskFreeDiscount(), riskFreeRate(), underlying(), and volatility().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/lookback/analyticcontinuousfixedlookback.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/lookback/analyticcontinuousfixedlookback.cpp