QuantLib: QuantLib::FdmSimple2dBSSolver Class Reference
QuantLib::FdmSimple2dBSSolver Class Reference
#include <fdmsimple2dbssolver.hpp>
Public Member Functions
FdmSimple2dBSSolver (const Handle< GeneralizedBlackScholesProcess > &process, Real strike, const FdmSolverDesc &desc, const FdmSchemeDesc &schemeDesc=FdmSchemeDesc::Douglas())
Real valueAt (Real s, Real a) const
Real deltaAt (Real s, Real a, Real eps) const
Real gammaAt (Real s, Real a, Real eps) const
Real thetaAt (Real s, Real a) const
Protected Member Functions
void performCalculations () const
Private Attributes
Handle
< GeneralizedBlackScholesProcess > process_
const Real strike_
const FdmSolverDesc solverDesc_
const FdmSchemeDesc schemeDesc_
boost::shared_ptr< Fdm2DimSolver > solver_
Detailed Description
Definition at line 38 of file fdmsimple2dbssolver.hpp.
Constructor & Destructor Documentation
QuantLib::FdmSimple2dBSSolver::FdmSimple2dBSSolver (const Handle< GeneralizedBlackScholesProcess > & process, Real strike, const FdmSolverDesc & desc, const FdmSchemeDesc & schemeDesc = FdmSchemeDesc::Douglas())
Definition at line 30 of file fdmsimple2dbssolver.cpp.
References process_, and QuantLib::Observer::registerWith().
    : process_(process),
      strike_(strike),
      solverDesc_(solverDesc),
      schemeDesc_(schemeDesc) {
        registerWith(process_);
    }
Member Function Documentation
Real QuantLib::FdmSimple2dBSSolver::deltaAt (Real s, Real a, Real eps) const
Definition at line 56 of file fdmsimple2dbssolver.cpp.
References valueAt().
{
        return (valueAt(s+eps, a) - valueAt(s-eps, a))/(2*eps);
    }
Real QuantLib::FdmSimple2dBSSolver::gammaAt (Real s, Real a, Real eps) const
Definition at line 60 of file fdmsimple2dbssolver.cpp.
References valueAt().
{
        return (valueAt(s+eps, a)+valueAt(s-eps, a)-2*valueAt(s,a))/(eps*eps);
    }
void QuantLib::FdmSimple2dBSSolver::performCalculations () const [protected, virtual]
This method must implement any calculations which must be (re)done in order to calculate the desired results.
Implements QuantLib::LazyObject.
Definition at line 43 of file fdmsimple2dbssolver.cpp.
References QuantLib::Handle< T >::currentLink(), QuantLib::FdmSolverDesc::mesher, process_, schemeDesc_, solver_, solverDesc_, and strike_.
{
        boost::shared_ptr<FdmBlackScholesOp> op(new FdmBlackScholesOp(
                solverDesc_.mesher, process_.currentLink(), strike_));
        solver_ = boost::shared_ptr<Fdm2DimSolver>(
                            new Fdm2DimSolver(solverDesc_, schemeDesc_, op));
    }
Real QuantLib::FdmSimple2dBSSolver::thetaAt (Real s, Real a) const
Definition at line 64 of file fdmsimple2dbssolver.cpp.
References QuantLib::LazyObject::calculate(), and solver_.
{
        calculate();
        return solver_->thetaAt(std::log(s), std::log(a));
    }
Real QuantLib::FdmSimple2dBSSolver::valueAt (Real s, Real a) const
Definition at line 51 of file fdmsimple2dbssolver.cpp.
References QuantLib::LazyObject::calculate(), and solver_.
Referenced by deltaAt(), and gammaAt().
{
        calculate();
        return solver_->interpolateAt(std::log(s), std::log(a));
    }
Member Data Documentation
Handle<GeneralizedBlackScholesProcess> QuantLib::FdmSimple2dBSSolver::process_ [private]
Definition at line 55 of file fdmsimple2dbssolver.hpp.
Referenced by FdmSimple2dBSSolver(), and performCalculations().
const FdmSchemeDesc QuantLib::FdmSimple2dBSSolver::schemeDesc_ [private]
Definition at line 58 of file fdmsimple2dbssolver.hpp.
Referenced by performCalculations().
boost::shared_ptr<Fdm2DimSolver> QuantLib::FdmSimple2dBSSolver::solver_ [mutable, private]
Definition at line 60 of file fdmsimple2dbssolver.hpp.
Referenced by performCalculations(), thetaAt(), and valueAt().
const FdmSolverDesc QuantLib::FdmSimple2dBSSolver::solverDesc_ [private]
Definition at line 57 of file fdmsimple2dbssolver.hpp.
Referenced by performCalculations().
const Real QuantLib::FdmSimple2dBSSolver::strike_ [private]
Definition at line 56 of file fdmsimple2dbssolver.hpp.
Referenced by performCalculations().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/solvers/fdmsimple2dbssolver.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/solvers/fdmsimple2dbssolver.cpp