QuantLib: InflationVolTest Class Reference
InflationVolTest Class Reference
#include <inflationvolatility.hpp>
Static Public Member Functions
static void testYoYPriceSurfaceToATM ()
static void testYoYPriceSurfaceToVol ()
static
boost::unit_test_framework::test_suite * suite ()
Detailed Description
Definition at line 29 of file inflationvolatility.hpp.
Member Function Documentation
boost::unit_test_framework::test_suite * InflationVolTest::suite () [static]
Definition at line 419 of file inflationvolatility.cpp.
References QUANTLIB_TEST_CASE, testYoYPriceSurfaceToATM(), and testYoYPriceSurfaceToVol().
Referenced by init_unit_test_suite().
{
    boost::unit_test_framework::test_suite* suite
        = BOOST_TEST_SUITE("yoyOptionletStripper (yoy inflation vol) tests");
    suite->add(QUANTLIB_TEST_CASE(&InflationVolTest::testYoYPriceSurfaceToATM));
    suite->add(QUANTLIB_TEST_CASE(&InflationVolTest::testYoYPriceSurfaceToVol));
    return suite;
}
void InflationVolTest::testYoYPriceSurfaceToATM () [static]
Definition at line 377 of file inflationvolatility.cpp.
References anonymous_namespace{inflationvolatility.cpp}::priceSurfEU, QL_REQUIRE, anonymous_namespace{inflationvolatility.cpp}::reset(), anonymous_namespace{inflationvolatility.cpp}::setup(), and anonymous_namespace{inflationvolatility.cpp}::setupPriceSurface().
Referenced by suite().
{
    BOOST_MESSAGE("Testing conversion from YoY cap-floor surface "
                  "to YoY inflation term structure...");
    SavedSettings backup;
    setup();
    setupPriceSurface();
    pair<vector<Time>, vector<Rate> > yyATMt = priceSurfEU->atmYoYSwapTimeRates();
    pair<vector<Date>, vector<Rate> > yyATMd = priceSurfEU->atmYoYSwapDateRates();
    // Real dy = (Real)lag / 12.0;
    const Real crv[] = {0.024586, 0.0247575, 0.0249396, 0.0252596,
                          0.0258498, 0.0262883, 0.0267915};
    const Real swaps[] = {0.024586, 0.0247575, 0.0249396, 0.0252596,
                          0.0258498, 0.0262883, 0.0267915};
    const Real ayoy[] = {0.0247659, 0.0251437, 0.0255945, 0.0265234,
                           0.0280457, 0.0285534, 0.0295884};
    Real eps = 2e-5;
    for(Size i = 0; i < yyATMt.first.size(); i++) {
        QL_REQUIRE(fabs( yyATMt.second[i] - crv[i] ) < eps,
                   "could not recover cached yoy swap curve "
                   << yyATMt.second[i]<< " vs " << crv[i]);
    }
    for(Size i = 0; i < yyATMd.first.size(); i++) {
        QL_REQUIRE(fabs( priceSurfEU->atmYoYSwapRate(yyATMd.first[i])  - swaps[i] ) < eps,
                   "could not recover yoy swap curve "
                   << priceSurfEU->atmYoYSwapRate(yyATMd.first[i]) << " vs " << swaps[i]);
    }
    for(Size i = 0; i < yyATMd.first.size(); i++) {
        QL_REQUIRE(fabs( priceSurfEU->atmYoYRate(yyATMd.first[i])  - ayoy[i] ) < eps,
                   " could not recover cached yoy curve "
                   << priceSurfEU->atmYoYRate(yyATMd.first[i]) << " vs " << ayoy[i]
                   <<" at "<<yyATMd.first[i]);
    }
    reset();
}
void InflationVolTest::testYoYPriceSurfaceToVol () [static]
Definition at line 287 of file inflationvolatility.cpp.
References anonymous_namespace{marketmodel.cpp}::d, QuantLib::ModifiedFollowing, anonymous_namespace{inflationvolatility.cpp}::priceSurfEU, QL_REQUIRE, anonymous_namespace{inflationvolatility.cpp}::reset(), anonymous_namespace{inflationvolatility.cpp}::setup(), anonymous_namespace{inflationvolatility.cpp}::setupPriceSurface(), QuantLib::Years, and anonymous_namespace{inflationvolatility.cpp}::yoyIndexEU.
Referenced by suite().
{
    BOOST_MESSAGE("Testing conversion from YoY price surface "
                  "to YoY volatility surface...");
    SavedSettings backup;
    setup();
    // first get the price surface set up
    setupPriceSurface();
    // caplet pricer, recall that setCapletVolatility(Handle<YoYOptionletVolatilitySurface>)
    // exists ... we'll use it with the -Curve variant of the surface
    // test UNIT DISPLACED pricer
    boost::shared_ptr<YoYOptionletVolatilitySurface> pVS;
    Handle<YoYOptionletVolatilitySurface> hVS(pVS, false); // pVS does NOT own whatever it points to later, hence the handle does not either
    boost::shared_ptr<YoYInflationUnitDisplacedBlackCapFloorEngine>
        yoyPricerUD(new YoYInflationUnitDisplacedBlackCapFloorEngine(yoyIndexEU,hVS)); //hVS
    // N.B. the vol gets set in the stripper ... else no point!
    // cap stripper
    boost::shared_ptr<YoYOptionletStripper> yoyOptionletStripper(
                             new InterpolatedYoYOptionletStripper<Linear>() );
    // now set up all the variables for the stripping
    Natural settlementDays = 0;
    TARGET cal;
    BusinessDayConvention bdc = ModifiedFollowing;
    DayCounter dc = Actual365Fixed();
    boost::shared_ptr<YoYCapFloorTermPriceSurface> capFloorPrices = priceSurfEU;
    Period lag = priceSurfEU->observationLag();
    Real slope = -0.5; //when you have bad data, i.e. very low/constant
    //prices for short dated extreem strikes
    //then you cannot assume constant caplet vol
    //(else arbitrage)
    // N.B. if this is too extreme then can't
    // get a no-arbitrage solution anyway
    // the way the slope is used means that the slope is
    // proportional to the level so higher slopes at
    // the edges when things are more volatile
    // Actually is doesn't matter what the interpolation is because we only
    // intend to use the K values that correspond to quotes ... for model fitting.
    boost::shared_ptr<KInterpolatedYoYOptionletVolatilitySurface<Linear> > yoySurf(new
                    KInterpolatedYoYOptionletVolatilitySurface<Linear>(settlementDays,
                cal, bdc, dc, lag, capFloorPrices, yoyPricerUD, yoyOptionletStripper,
                                                              slope) );
    // now use it for something ... like stating what the T=const lines look like
    const Real volATyear1[] = {
          0.0128, 0.0093, 0.0083, 0.0073, 0.0064,
          0.0058, 0.0042, 0.0046, 0.0053, 0.0064,
          0.0098
    };
    const Real volATyear3[] = {
          0.0079, 0.0058, 0.0051, 0.0045, 0.0039,
          0.0035, 0.0026, 0.0028, 0.0033, 0.0039,
          0.0060
    };
    Date d = yoySurf->baseDate() + Period(1,Years);
    pair<vector<Rate>, vector<Volatility> > someSlice;
    someSlice = yoySurf->Dslice(d);
    Size n = someSlice.first.size();
    Real eps = 0.0001;
    for(Size i = 0; i < n; i++){
        QL_REQUIRE( fabs(someSlice.second[i] - volATyear1[i]) < eps,
                   " could not recover 1yr vol: " << someSlice.second[i]
                   << " vs " << volATyear1[i] );
    }
    d = yoySurf->baseDate() + Period(3,Years);
    pair<vector<Rate>, vector<Volatility> >
        someOtherSlice = yoySurf->Dslice(d);
    n = someOtherSlice.first.size();
    for(Size i = 0; i < n; i++){
        QL_REQUIRE(fabs(someOtherSlice.second[i]-volATyear3[i]) < eps,
                        "could not recover 3yr vol: "
                        << someOtherSlice.second[i]<< " vs " << volATyear3[i] );
    }
    reset();
}
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/inflationvolatility.hpp
/home/deriversatile/QuantLib/QuantLibQt/test-suite/inflationvolatility.cpp