QuantLib: QuantLib::VarianceGammaModel Class Reference
QuantLib::VarianceGammaModel Class Reference
Variance Gamma model.
#include <variancegammamodel.hpp>
Public Member Functions
VarianceGammaModel (const boost::shared_ptr< VarianceGammaProcess > &process)
Real sigma () const
Real nu () const
Real theta () const
boost::shared_ptr
< VarianceGammaProcess > process () const
Protected Member Functions
void generateArguments ()
Protected Attributes
boost::shared_ptr
< VarianceGammaProcess > process_
Detailed Description
Variance Gamma model.
References:
Dilip B. Madan, Peter Carr, Eric C. Chang (1998) "The variance gamma process and option pricing," European Finance Review, 2, 79-105
Warning:
calibration is not implemented for VG
Definition at line 41 of file variancegammamodel.hpp.
Constructor & Destructor Documentation
QuantLib::VarianceGammaModel::VarianceGammaModel (const boost::shared_ptr< VarianceGammaProcess > & process)
Definition at line 25 of file variancegammamodel.cpp.
References QuantLib::CalibratedModel::arguments_, generateArguments(), process_, and QuantLib::Observer::registerWith().
        : CalibratedModel(3), process_(process) {
            arguments_[0] = ConstantParameter(process->sigma(),
                PositiveConstraint());
            arguments_[1] = ConstantParameter(process->nu(),
                PositiveConstraint());
            arguments_[2] = ConstantParameter(process->theta(),
                NoConstraint());
            generateArguments();
            registerWith(process_->riskFreeRate());
            registerWith(process_->dividendYield());
            registerWith(process_->s0());
    }
Member Function Documentation
void QuantLib::VarianceGammaModel::generateArguments () [protected, virtual]
Reimplemented from QuantLib::CalibratedModel.
Definition at line 42 of file variancegammamodel.cpp.
References nu(), process_, sigma(), and theta().
Referenced by VarianceGammaModel().
{
        process_.reset(new VarianceGammaProcess(process_->s0(),
            process_->dividendYield(),
            process_->riskFreeRate(),
            sigma(), nu(), theta()));
    }
Real QuantLib::VarianceGammaModel::nu () const [inline]
Definition at line 48 of file variancegammamodel.hpp.
References QuantLib::CalibratedModel::arguments_.
Referenced by generateArguments().
{ return arguments_[1](0.0); }
boost::shared_ptr<VarianceGammaProcess> QuantLib::VarianceGammaModel::process () const [inline]
Definition at line 53 of file variancegammamodel.hpp.
References process_.
{ return process_; }
Real QuantLib::VarianceGammaModel::sigma () const [inline]
Definition at line 46 of file variancegammamodel.hpp.
References QuantLib::CalibratedModel::arguments_.
Referenced by generateArguments().
{ return arguments_[0](0.0); }
Real QuantLib::VarianceGammaModel::theta () const [inline]
Definition at line 50 of file variancegammamodel.hpp.
References QuantLib::CalibratedModel::arguments_.
Referenced by generateArguments().
{ return arguments_[2](0.0); }
Member Data Documentation
boost::shared_ptr<VarianceGammaProcess> QuantLib::VarianceGammaModel::process_ [protected]
Definition at line 57 of file variancegammamodel.hpp.
Referenced by generateArguments(), process(), and VarianceGammaModel().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/variancegamma/variancegammamodel.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/variancegamma/variancegammamodel.cpp