QuantLib: QuantLib::AssetSwap Class Reference
QuantLib::AssetSwap Class Reference
Bullet bond vs Libor swap.
#include <assetswap.hpp>
Classes
class arguments
Arguments for asset swap calculation
class results
Results from simple swap calculation
Public Member Functions
AssetSwap (bool payBondCoupon, const boost::shared_ptr< Bond > &bond, Real bondCleanPrice, const boost::shared_ptr< IborIndex > &iborIndex, Spread spread, const Schedule &floatSchedule=Schedule(), const DayCounter &floatingDayCount=DayCounter(), bool parAssetSwap=true)
AssetSwap (bool parAssetSwap, const boost::shared_ptr< Bond > &bond, Real bondCleanPrice, Real nonParRepayment, Real gearing, const boost::shared_ptr< IborIndex > &iborIndex, Spread spread=0.0, const DayCounter &floatingDayCount=DayCounter(), Date dealMaturity=Date(), bool payBondCoupon=false)
Spread fairSpread () const
Real floatingLegBPS () const
Real floatingLegNPV () const
Real fairCleanPrice () const
Real fairNonParRepayment () const
bool parSwap () const
Spread spread () const
Real cleanPrice () const
Real nonParRepayment () const
const boost::shared_ptr< Bond > & bond () const
bool payBondCoupon () const
const Leg & bondLeg () const
const Leg & floatingLeg () const
void setupArguments (PricingEngine::arguments *args) const
void fetchResults (const PricingEngine::results *) const
Private Member Functions
void setupExpired () const
Private Attributes
boost::shared_ptr< Bond > bond_
Real bondCleanPrice_
Real nonParRepayment_
Spread spread_
bool parSwap_
Date upfrontDate_
Spread fairSpread_
Real fairCleanPrice_
Real fairNonParRepayment_
Detailed Description
Bullet bond vs Libor swap.
for mechanics of par asset swap and market asset swap, refer to "Introduction to Asset Swap", Lehman Brothers European Fixed Income Research - January 2000, D. O'Kane
Warning:
bondCleanPrice must be the (forward) price at the floatSchedule start date
Bug:
fair prices are not calculated correctly when using indexed coupons.
Definition at line 51 of file assetswap.hpp.
Constructor & Destructor Documentation
QuantLib::AssetSwap::AssetSwap (bool payBondCoupon, const boost::shared_ptr< Bond > & bond, Real bondCleanPrice, const boost::shared_ptr< IborIndex > & iborIndex, Spread spread, const Schedule & floatSchedule = Schedule(), const DayCounter & floatingDayCount = DayCounter(), bool parAssetSwap = true)
QuantLib::AssetSwap::AssetSwap (bool parAssetSwap, const boost::shared_ptr< Bond > & bond, Real bondCleanPrice, Real nonParRepayment, Real gearing, const boost::shared_ptr< IborIndex > & iborIndex, Spread spread = 0.0, const DayCounter & floatingDayCount = DayCounter(), Date dealMaturity = Date(), bool payBondCoupon = false)
Definition at line 37 of file assetswap.cpp.
References QuantLib::DateGeneration::Backward, bond_, bondCleanPrice_, bondLeg(), anonymous_namespace{marketmodel.cpp}::c, QuantLib::Following, QuantLib::Swap::legs_, nonParRepayment_, parSwap_, QuantLib::Swap::payer_, QL_REQUIRE, QuantLib::Observer::registerWith(), QuantLib::Schedule::startDate(), QuantLib::Schedule::until(), upfrontDate_, QuantLib::IborLeg::withGearings(), QuantLib::IborLeg::withNotionals(), QuantLib::IborLeg::withPaymentAdjustment(), QuantLib::IborLeg::withPaymentDayCounter(), and QuantLib::IborLeg::withSpreads().
    : Swap(2), bond_(bond), bondCleanPrice_(bondCleanPrice),
      nonParRepayment_(nonParRepayment), spread_(spread), parSwap_(parSwap)
    {
        Schedule tempSch(bond_->settlementDate(),
                         bond_->maturityDate(),
                         iborIndex->tenor(),
                         iborIndex->fixingCalendar(),
                         iborIndex->businessDayConvention(),
                         iborIndex->businessDayConvention(),
                         DateGeneration::Backward,
                         false); // endOfMonth
        if (dealMaturity==Date())
            dealMaturity = bond_->maturityDate();
        QL_REQUIRE(dealMaturity <= tempSch.dates().back(),
                   "deal maturity " << dealMaturity <<
                   " cannot be later than (adjusted) bond maturity " <<
                   tempSch.dates().back());
        // the following might become an input parameter
        BusinessDayConvention paymentAdjustment = Following;
        Date finalDate = tempSch.calendar().adjust(
            dealMaturity, paymentAdjustment);
        Schedule schedule = tempSch.until(finalDate);
        // bondCleanPrice must be the (forward) clean price
        // at the floating schedule start date
        upfrontDate_ = schedule.startDate();
        Real dirtyPrice = bondCleanPrice_ +
                          bond_->accruedAmount(upfrontDate_);
        Real notional = bond_->notional(upfrontDate_);
        /* In the market asset swap, the bond is purchased in return for
           payment of the full price. The notional of the floating leg is
           then scaled by the full price. */
        if (!parSwap_)
            notional *= dirtyPrice/100.0;
        if (floatingDayCounter==DayCounter())
            legs_[1] = IborLeg(schedule, iborIndex)
                .withNotionals(notional)
                .withPaymentAdjustment(paymentAdjustment)
                .withGearings(gearing)
                .withSpreads(spread);
        else
            legs_[1] = IborLeg(schedule, iborIndex)
                .withNotionals(notional)
                .withPaymentDayCounter(floatingDayCounter)
                .withPaymentAdjustment(paymentAdjustment)
                .withGearings(gearing)
                .withSpreads(spread);
        for (Leg::const_iterator i=legs_[1].begin(); i<legs_[1].end(); ++i)
            registerWith(*i);
        const Leg& bondLeg = bond_->cashflows();
        Leg::const_iterator i = bondLeg.begin();
        // skip bond redemption
        for (; i<bondLeg.end()-1 && (*i)->date()<=dealMaturity; ++i) {
            // whatever might be the choice for the discounting engine
            // bond flows on upfrontDate_ must be discarded
            bool upfrontDateBondFlows = false;
            if (!(*i)->hasOccurred(upfrontDate_, upfrontDateBondFlows))
                legs_[0].push_back(*i);
        }
        // if the first skipped cashflow is not the redemption
        // and it is a coupon then add the accrued coupon
        if (i<bondLeg.end()-1) {
            shared_ptr<Coupon> c = boost::dynamic_pointer_cast<Coupon>(*i);
            if (c) {
                shared_ptr<CashFlow> accruedCoupon(new
                    SimpleCashFlow(c->accruedAmount(dealMaturity), finalDate));
                legs_[0].push_back(accruedCoupon);
            }
        }
        // add the nonParRepayment_
        shared_ptr<CashFlow> nonParRepaymentFlow(new
            SimpleCashFlow(nonParRepayment_, finalDate));
        legs_[0].push_back(nonParRepaymentFlow);
        QL_REQUIRE(!legs_[0].empty(),
                   "empty bond leg to start with");
        // special flows
        if (parSwap_) {
            // upfront on the floating leg
            Real upfront = (dirtyPrice-100.0)/100.0*notional;
            shared_ptr<CashFlow> upfrontCashFlow(new
                SimpleCashFlow(upfront, upfrontDate_));
            legs_[1].insert(legs_[1].begin(), upfrontCashFlow);
            // backpayment on the floating leg
            // (accounts for non-par redemption, if any)
            Real backPayment = notional;
            shared_ptr<CashFlow> backPaymentCashFlow(new
                SimpleCashFlow(backPayment, finalDate));
            legs_[1].push_back(backPaymentCashFlow);
        } else {
            // final notional exchange
            shared_ptr<CashFlow> finalCashFlow (new
                SimpleCashFlow(notional, finalDate));
            legs_[1].push_back(finalCashFlow);
        }
        QL_REQUIRE(!legs_[0].empty(), "empty bond leg");
        for (Leg::const_iterator i=legs_[0].begin(); i<legs_[0].end(); ++i)
            registerWith(*i);
        if (payBondCoupon) {
            payer_[0]=-1.0;
            payer_[1]=+1.0;
        } else {
            payer_[0]=+1.0;
            payer_[1]=-1.0;
        }
    }
Member Function Documentation
const boost::shared_ptr<Bond>& QuantLib::AssetSwap::bond () const [inline]
Definition at line 86 of file assetswap.hpp.
References bond_.
{ return bond_; }
const Leg& QuantLib::AssetSwap::bondLeg () const [inline]
Definition at line 88 of file assetswap.hpp.
References QuantLib::Swap::legs_.
Referenced by AssetSwap(), and setupArguments().
{ return legs_[0]; }
Real QuantLib::AssetSwap::cleanPrice () const [inline]
Definition at line 84 of file assetswap.hpp.
References bondCleanPrice_.
{ return bondCleanPrice_; }
Real QuantLib::AssetSwap::fairCleanPrice () const
Definition at line 346 of file assetswap.cpp.
References bond_, bondCleanPrice_, QuantLib::Instrument::calculate(), fairCleanPrice_, QuantLib::Swap::legNPV_, QuantLib::Instrument::NPV_, QuantLib::Swap::npvDateDiscount_, parSwap_, QuantLib::Swap::payer_, QL_REQUIRE, QuantLib::Swap::startDiscounts_, and upfrontDate_.
Referenced by QuantLib::AssetSwap::results::reset().
{
        calculate();
        if (fairCleanPrice_ != Null<Real>()) {
            return fairCleanPrice_;
        } else {
            QL_REQUIRE(startDiscounts_[1]!=Null<DiscountFactor>(),
                       "fair clean price not available for seasoned deal");
            Real notional = bond_->notional(upfrontDate_);
            if (parSwap_) {
                fairCleanPrice_ = bondCleanPrice_ - payer_[1] *
                    NPV_*npvDateDiscount_/startDiscounts_[1]/(notional/100.0);
            } else {
                Real accruedAmount = bond_->accruedAmount(upfrontDate_);
                Real dirtyPrice = bondCleanPrice_ + accruedAmount;
                Real fairDirtyPrice = - legNPV_[0]/legNPV_[1] * dirtyPrice;
                fairCleanPrice_ = fairDirtyPrice - accruedAmount;
            }
            return fairCleanPrice_;
        }
    }
Real QuantLib::AssetSwap::fairNonParRepayment () const
Definition at line 368 of file assetswap.cpp.
References bond_, QuantLib::Instrument::calculate(), QuantLib::Swap::endDiscounts_, fairNonParRepayment_, nonParRepayment_, QuantLib::Instrument::NPV_, QuantLib::Swap::npvDateDiscount_, QuantLib::Swap::payer_, QL_REQUIRE, and upfrontDate_.
Referenced by QuantLib::AssetSwap::results::reset().
{
        calculate();
        if (fairNonParRepayment_ != Null<Real>()) {
            return fairNonParRepayment_;
        } else {
            QL_REQUIRE(endDiscounts_[1]!=Null<DiscountFactor>(),
                       "fair non par repayment not available for expired leg");
            Real notional = bond_->notional(upfrontDate_);
            fairNonParRepayment_ = nonParRepayment_ - payer_[0] *
                NPV_*npvDateDiscount_/endDiscounts_[1]/(notional/100.0);
            return fairNonParRepayment_;
        }
    }
Spread QuantLib::AssetSwap::fairSpread () const
Definition at line 319 of file assetswap.cpp.
References QuantLib::Instrument::calculate(), fairSpread_, QuantLib::Swap::legBPS_, QuantLib::Instrument::NPV_, QL_FAIL, and spread_.
Referenced by QuantLib::AssetSwap::results::reset().
{
        static const Spread basisPoint = 1.0e-4;
        calculate();
        if (fairSpread_ != Null<Spread>()) {
            return fairSpread_;
        } else if (legBPS_.size() > 1 && legBPS_[1] != Null<Spread>()) {
            fairSpread_ = spread_ - NPV_/legBPS_[1]*basisPoint;
            return fairSpread_;
        } else {
            QL_FAIL("fair spread not available");
        }
    }
void QuantLib::AssetSwap::fetchResults (const PricingEngine::results * r) const [virtual]
When a derived result structure is defined for an instrument, this method should be overridden to read from it. This is mandatory in case a pricing engine is used.
Reimplemented from QuantLib::Swap.
Definition at line 389 of file assetswap.cpp.
References QuantLib::AssetSwap::results::fairCleanPrice, fairCleanPrice_, QuantLib::AssetSwap::results::fairNonParRepayment, fairNonParRepayment_, QuantLib::AssetSwap::results::fairSpread, and fairSpread_.
{
        Swap::fetchResults(r);
        const AssetSwap::results* results =
            dynamic_cast<const AssetSwap::results*>(r);
        if (results) {
            fairSpread_ = results->fairSpread;
            fairCleanPrice_= results->fairCleanPrice;
            fairNonParRepayment_= results->fairNonParRepayment;
        } else {
            fairSpread_ = Null<Spread>();
            fairCleanPrice_ = Null<Real>();
            fairNonParRepayment_ = Null<Real>();
        }
    }
const Leg& QuantLib::AssetSwap::floatingLeg () const [inline]
Definition at line 89 of file assetswap.hpp.
References QuantLib::Swap::legs_.
Referenced by setupArguments().
{ return legs_[1]; }
Real QuantLib::AssetSwap::floatingLegBPS () const
Definition at line 332 of file assetswap.cpp.
References QuantLib::Instrument::calculate(), QuantLib::Swap::legBPS_, and QL_REQUIRE.
{
        calculate();
        QL_REQUIRE(legBPS_.size() > 1 && legBPS_[1] != Null<Real>(),
                   "floating-leg BPS not available");
        return legBPS_[1];
    }
Real QuantLib::AssetSwap::floatingLegNPV () const
Definition at line 339 of file assetswap.cpp.
References QuantLib::Instrument::calculate(), QuantLib::Swap::legNPV_, and QL_REQUIRE.
{
        calculate();
        QL_REQUIRE(legNPV_.size() > 1 && legNPV_[1] != Null<Real>(),
                   "floating-leg NPV not available");
        return legNPV_[1];
    }
Real QuantLib::AssetSwap::nonParRepayment () const [inline]
Definition at line 85 of file assetswap.hpp.
References nonParRepayment_.
{ return nonParRepayment_; }
bool QuantLib::AssetSwap::parSwap () const [inline]
Definition at line 82 of file assetswap.hpp.
References parSwap_.
{ return parSwap_; }
bool QuantLib::AssetSwap::payBondCoupon () const [inline]
Definition at line 87 of file assetswap.hpp.
References QuantLib::Swap::payer_.
{ return (payer_[0] == -1.0); }
void QuantLib::AssetSwap::setupArguments (PricingEngine::arguments *) const [virtual]
When a derived argument structure is defined for an instrument, this method should be overridden to fill it. This is mandatory in case a pricing engine is used.
Reimplemented from QuantLib::Swap.
Definition at line 272 of file assetswap.cpp.
References bondLeg(), QuantLib::AssetSwap::arguments::fixedCoupons, QuantLib::AssetSwap::arguments::fixedPayDates, QuantLib::AssetSwap::arguments::fixedResetDates, QuantLib::AssetSwap::arguments::floatingAccrualTimes, QuantLib::AssetSwap::arguments::floatingFixingDates, floatingLeg(), QuantLib::AssetSwap::arguments::floatingPayDates, QuantLib::AssetSwap::arguments::floatingResetDates, and QuantLib::AssetSwap::arguments::floatingSpreads.
{
        Swap::setupArguments(args);
        AssetSwap::arguments* arguments =
            dynamic_cast<AssetSwap::arguments*>(args);
        if (!arguments)  // it's a swap engine...
            return;
        const Leg& fixedCoupons = bondLeg();
        arguments->fixedResetDates = arguments->fixedPayDates =
            vector<Date>(fixedCoupons.size());
        arguments->fixedCoupons = vector<Real>(fixedCoupons.size());
        for (Size i=0; i<fixedCoupons.size(); ++i) {
            shared_ptr<FixedRateCoupon> coupon =
                dynamic_pointer_cast<FixedRateCoupon>(fixedCoupons[i]);
            arguments->fixedPayDates[i] = coupon->date();
            arguments->fixedResetDates[i] = coupon->accrualStartDate();
            arguments->fixedCoupons[i] = coupon->amount();
        }
        const Leg& floatingCoupons = floatingLeg();
        arguments->floatingResetDates = arguments->floatingPayDates =
            arguments->floatingFixingDates =
            vector<Date>(floatingCoupons.size());
        arguments->floatingAccrualTimes =
            vector<Time>(floatingCoupons.size());
        arguments->floatingSpreads =
            vector<Spread>(floatingCoupons.size());
        for (Size i=0; i<floatingCoupons.size(); ++i) {
            shared_ptr<FloatingRateCoupon> coupon =
                dynamic_pointer_cast<FloatingRateCoupon>(floatingCoupons[i]);
            arguments->floatingResetDates[i] = coupon->accrualStartDate();
            arguments->floatingPayDates[i] = coupon->date();
            arguments->floatingFixingDates[i] = coupon->fixingDate();
            arguments->floatingAccrualTimes[i] = coupon->accrualPeriod();
            arguments->floatingSpreads[i] = coupon->spread();
        }
    }
void QuantLib::AssetSwap::setupExpired () const [private, virtual]
This method must leave the instrument in a consistent state when the expiration condition is met.
Reimplemented from QuantLib::Swap.
Definition at line 382 of file assetswap.cpp.
References fairCleanPrice_, fairNonParRepayment_, and fairSpread_.
{
        Swap::setupExpired();
        fairSpread_ = Null<Spread>();
        fairCleanPrice_ = Null<Real>();
        fairNonParRepayment_ = Null<Real>();
    }
Spread QuantLib::AssetSwap::spread () const [inline]
Definition at line 83 of file assetswap.hpp.
References spread_.
{ return spread_; }
Member Data Documentation
boost::shared_ptr<Bond> QuantLib::AssetSwap::bond_ [private]
Definition at line 95 of file assetswap.hpp.
Referenced by AssetSwap(), bond(), fairCleanPrice(), and fairNonParRepayment().
Real QuantLib::AssetSwap::bondCleanPrice_ [private]
Definition at line 96 of file assetswap.hpp.
Referenced by AssetSwap(), cleanPrice(), and fairCleanPrice().
Real QuantLib::AssetSwap::fairCleanPrice_ [mutable, private]
Definition at line 102 of file assetswap.hpp.
Referenced by fairCleanPrice(), fetchResults(), and setupExpired().
Real QuantLib::AssetSwap::fairNonParRepayment_ [mutable, private]
Definition at line 102 of file assetswap.hpp.
Referenced by fairNonParRepayment(), fetchResults(), and setupExpired().
Spread QuantLib::AssetSwap::fairSpread_ [mutable, private]
Definition at line 101 of file assetswap.hpp.
Referenced by fairSpread(), fetchResults(), and setupExpired().
Real QuantLib::AssetSwap::nonParRepayment_ [private]
Definition at line 96 of file assetswap.hpp.
Referenced by AssetSwap(), fairNonParRepayment(), and nonParRepayment().
bool QuantLib::AssetSwap::parSwap_ [private]
Definition at line 98 of file assetswap.hpp.
Referenced by AssetSwap(), fairCleanPrice(), and parSwap().
Spread QuantLib::AssetSwap::spread_ [private]
Definition at line 97 of file assetswap.hpp.
Referenced by fairSpread(), and spread().
Date QuantLib::AssetSwap::upfrontDate_ [private]
Definition at line 99 of file assetswap.hpp.
Referenced by AssetSwap(), fairCleanPrice(), and fairNonParRepayment().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/assetswap.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/assetswap.cpp