QuantLib: QuantLib::FdmBatesSolver Class Reference
QuantLib::FdmBatesSolver Class Reference
#include <fdmbatessolver.hpp>
Public Member Functions
FdmBatesSolver (const Handle< BatesProcess > &process, const FdmSolverDesc &solverDesc, const FdmSchemeDesc &schemeDesc=FdmSchemeDesc::Hundsdorfer(), Size integroIntegrationOrder=12, const Handle< FdmQuantoHelper > &quantoHelper=Handle< FdmQuantoHelper >())
Real valueAt (Real s, Real v) const
Real thetaAt (Real s, Real v) const
Real deltaAt (Real s, Real v) const
Real gammaAt (Real s, Real v) const
Protected Member Functions
void performCalculations () const
Private Attributes
const Handle< BatesProcess > process_
const FdmSolverDesc solverDesc_
const FdmSchemeDesc schemeDesc_
const Size integroIntegrationOrder_
const Handle< FdmQuantoHelper > quantoHelper_
boost::shared_ptr< Fdm2DimSolver > solver_
Detailed Description
Definition at line 37 of file fdmbatessolver.hpp.
Constructor & Destructor Documentation
QuantLib::FdmBatesSolver::FdmBatesSolver (const Handle< BatesProcess > & process, const FdmSolverDesc & solverDesc, const FdmSchemeDesc & schemeDesc = FdmSchemeDesc::Hundsdorfer(), Size integroIntegrationOrder = 12, const Handle< FdmQuantoHelper > & quantoHelper = Handle<FdmQuantoHelper>())
Definition at line 31 of file fdmbatessolver.cpp.
References process_, quantoHelper_, and QuantLib::Observer::registerWith().
    : process_(process),
      solverDesc_(solverDesc),
      schemeDesc_(schemeDesc),
      integroIntegrationOrder_(integroIntegrationOrder),
      quantoHelper_(quantoHelper) {
        registerWith(process_);
        registerWith(quantoHelper_);
    }
Member Function Documentation
Real QuantLib::FdmBatesSolver::deltaAt (Real s, Real v) const
Definition at line 63 of file fdmbatessolver.cpp.
References QuantLib::LazyObject::calculate(), and solver_.
{
        calculate();
        return solver_->derivativeX(std::log(s), v)/s;
    }
Real QuantLib::FdmBatesSolver::gammaAt (Real s, Real v) const
Definition at line 68 of file fdmbatessolver.cpp.
References QuantLib::LazyObject::calculate(), and solver_.
{
        calculate();
        const Real x = std::log(s);
        return (solver_->derivativeXX(x, v)-solver_->derivativeX(x, v))/(s*s);
    }
void QuantLib::FdmBatesSolver::performCalculations () const [protected, virtual]
This method must implement any calculations which must be (re)done in order to calculate the desired results.
Implements QuantLib::LazyObject.
Definition at line 46 of file fdmbatessolver.cpp.
References QuantLib::FdmSolverDesc::bcSet, QuantLib::Handle< T >::currentLink(), QuantLib::Handle< T >::empty(), integroIntegrationOrder_, QuantLib::FdmSolverDesc::mesher, process_, quantoHelper_, schemeDesc_, solver_, and solverDesc_.
{
        boost::shared_ptr<FdmLinearOpComposite> op(
            new FdmBatesOp(solverDesc_.mesher, process_.currentLink(),
                           solverDesc_.bcSet, integroIntegrationOrder_,
                           (!quantoHelper_.empty())
                                   ? quantoHelper_.currentLink()
                                   : boost::shared_ptr<FdmQuantoHelper>()));
        solver_ = boost::shared_ptr<Fdm2DimSolver>(
                               new Fdm2DimSolver(solverDesc_, schemeDesc_, op));
    }
Real QuantLib::FdmBatesSolver::thetaAt (Real s, Real v) const
Definition at line 74 of file fdmbatessolver.cpp.
References QuantLib::LazyObject::calculate(), and solver_.
{
        calculate();
        return solver_->thetaAt(std::log(s), v);
    }
Real QuantLib::FdmBatesSolver::valueAt (Real s, Real v) const
Definition at line 58 of file fdmbatessolver.cpp.
References QuantLib::LazyObject::calculate(), and solver_.
{
        calculate();
        return solver_->interpolateAt(std::log(s), v);
    }
Member Data Documentation
const Size QuantLib::FdmBatesSolver::integroIntegrationOrder_ [private]
Definition at line 65 of file fdmbatessolver.hpp.
Referenced by performCalculations().
const Handle<BatesProcess> QuantLib::FdmBatesSolver::process_ [private]
Definition at line 62 of file fdmbatessolver.hpp.
Referenced by FdmBatesSolver(), and performCalculations().
const Handle<FdmQuantoHelper> QuantLib::FdmBatesSolver::quantoHelper_ [private]
Definition at line 66 of file fdmbatessolver.hpp.
Referenced by FdmBatesSolver(), and performCalculations().
const FdmSchemeDesc QuantLib::FdmBatesSolver::schemeDesc_ [private]
Definition at line 64 of file fdmbatessolver.hpp.
Referenced by performCalculations().
boost::shared_ptr<Fdm2DimSolver> QuantLib::FdmBatesSolver::solver_ [mutable, private]
Definition at line 68 of file fdmbatessolver.hpp.
Referenced by deltaAt(), gammaAt(), performCalculations(), thetaAt(), and valueAt().
const FdmSolverDesc QuantLib::FdmBatesSolver::solverDesc_ [private]
Definition at line 63 of file fdmbatessolver.hpp.
Referenced by performCalculations().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/solvers/fdmbatessolver.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/solvers/fdmbatessolver.cpp