QuantLib: QuantLib::BMASwap Class Reference
QuantLib::BMASwap Class Reference
swap paying Libor against BMA coupons
#include <bmaswap.hpp>
Public Types
enum Type { Receiver = -1, Payer = 1 }
Public Member Functions
BMASwap (Type type, Real nominal, const Schedule &liborSchedule, Rate liborFraction, Rate liborSpread, const boost::shared_ptr< IborIndex > &liborIndex, const DayCounter &liborDayCount, const Schedule &bmaSchedule, const boost::shared_ptr< BMAIndex > &bmaIndex, const DayCounter &bmaDayCount)
Inspectors
Real liborFraction () const
Spread liborSpread () const
Real nominal () const
Type type () const
"payer" or "receiver" refer to the BMA leg
const Leg & bmaLeg () const
const Leg & liborLeg () const
Results
Real liborLegBPS () const
Real liborLegNPV () const
Rate fairLiborFraction () const
Spread fairLiborSpread () const
Real bmaLegBPS () const
Real bmaLegNPV () const
Private Attributes
Type type_
Real nominal_
Rate liborFraction_
Rate liborSpread_
Detailed Description
swap paying Libor against BMA coupons
Definition at line 35 of file bmaswap.hpp.
Member Enumeration Documentation
enum QuantLib::BMASwap::Type
Enumerator:
Receiver
Payer
Definition at line 37 of file bmaswap.hpp.
{ Receiver = -1, Payer = 1 };
Constructor & Destructor Documentation
QuantLib::BMASwap::BMASwap (Type type, Real nominal, const Schedule & liborSchedule, Rate liborFraction, Rate liborSpread, const boost::shared_ptr< IborIndex > & liborIndex, const DayCounter & liborDayCount, const Schedule & bmaSchedule, const boost::shared_ptr< BMAIndex > & bmaIndex, const DayCounter & bmaDayCount)
Definition at line 27 of file bmaswap.cpp.
References QuantLib::Schedule::businessDayConvention(), QuantLib::Swap::legs_, Payer, QuantLib::Swap::payer_, QL_FAIL, Receiver, QuantLib::Observer::registerWith(), type_, QuantLib::IborLeg::withFixingDays(), QuantLib::IborLeg::withNotionals(), QuantLib::AverageBMALeg::withNotionals(), QuantLib::IborLeg::withPaymentAdjustment(), QuantLib::AverageBMALeg::withPaymentAdjustment(), QuantLib::IborLeg::withPaymentDayCounter(), QuantLib::AverageBMALeg::withPaymentDayCounter(), and QuantLib::IborLeg::withSpreads().
    : Swap(2), type_(type), nominal_(nominal),
      liborFraction_(liborFraction), liborSpread_(liborSpread)  {
        BusinessDayConvention convention =
            liborSchedule.businessDayConvention();
        legs_[0] = IborLeg(liborSchedule, liborIndex)
            .withNotionals(nominal)
            .withPaymentDayCounter(liborDayCount)
            .withPaymentAdjustment(convention)
            .withFixingDays(liborIndex->fixingDays())
            .withGearings(liborFraction)
            .withSpreads(liborSpread);
        legs_[1] = AverageBMALeg(bmaSchedule, bmaIndex)
            .withNotionals(nominal)
            .withPaymentDayCounter(bmaDayCount)
            .withPaymentAdjustment(bmaSchedule.businessDayConvention());
        for (Size j=0; j<2; ++j) {
            for (Leg::iterator i = legs_[j].begin(); i!= legs_[j].end(); ++i)
                registerWith(*i);
        }
        switch (type_) {
          case Payer:
            payer_[0] = +1.0;
            payer_[1] = -1.0;
            break;
          case Receiver:
            payer_[0] = -1.0;
            payer_[1] = +1.0;
            break;
          default:
            QL_FAIL("Unknown BMA-swap type");
        }
    }
Member Function Documentation
const Leg & QuantLib::BMASwap::bmaLeg () const
Definition at line 97 of file bmaswap.cpp.
References QuantLib::Swap::legs_.
{
        return legs_[1];
    }
Real QuantLib::BMASwap::bmaLegBPS () const
Definition at line 130 of file bmaswap.cpp.
References QuantLib::Instrument::calculate(), QuantLib::Swap::legBPS_, and QL_REQUIRE.
{
        calculate();
        QL_REQUIRE(legBPS_[1] != Null<Real>(), "result not available");
        return legBPS_[1];
    }
Real QuantLib::BMASwap::bmaLegNPV () const
Definition at line 136 of file bmaswap.cpp.
References QuantLib::Instrument::calculate(), QuantLib::Swap::legNPV_, and QL_REQUIRE.
Referenced by fairLiborFraction().
{
        calculate();
        QL_REQUIRE(legNPV_[1] != Null<Real>(), "result not available");
        return legNPV_[1];
    }
Real QuantLib::BMASwap::fairLiborFraction () const
Definition at line 114 of file bmaswap.cpp.
References bmaLegNPV(), liborFraction_, liborLegBPS(), liborLegNPV(), liborSpread_, and QL_REQUIRE.
{
        static Spread basisPoint = 1.0e-4;
        Real spreadNPV = (liborSpread_/basisPoint)*liborLegBPS();
        Real pureLiborNPV = liborLegNPV() - spreadNPV;
        QL_REQUIRE(pureLiborNPV != 0.0,
                   "result not available (null libor NPV)");
        return -liborFraction_ * (bmaLegNPV() + spreadNPV) / pureLiborNPV;
    }
Spread QuantLib::BMASwap::fairLiborSpread () const
Definition at line 124 of file bmaswap.cpp.
References liborLegBPS(), liborSpread_, and QuantLib::Instrument::NPV().
{
        static Spread basisPoint = 1.0e-4;
        return liborSpread_ - NPV()/(liborLegBPS()/basisPoint);
    }
Real QuantLib::BMASwap::liborFraction () const
Definition at line 77 of file bmaswap.cpp.
References liborFraction_.
{
        return liborFraction_;
    }
const Leg & QuantLib::BMASwap::liborLeg () const
Definition at line 93 of file bmaswap.cpp.
References QuantLib::Swap::legs_.
{
        return legs_[0];
    }
Real QuantLib::BMASwap::liborLegBPS () const
Definition at line 102 of file bmaswap.cpp.
References QuantLib::Instrument::calculate(), QuantLib::Swap::legBPS_, and QL_REQUIRE.
Referenced by fairLiborFraction(), and fairLiborSpread().
{
        calculate();
        QL_REQUIRE(legBPS_[0] != Null<Real>(), "result not available");
        return legBPS_[0];
    }
Real QuantLib::BMASwap::liborLegNPV () const
Definition at line 108 of file bmaswap.cpp.
References QuantLib::Instrument::calculate(), QuantLib::Swap::legNPV_, and QL_REQUIRE.
Referenced by fairLiborFraction().
{
        calculate();
        QL_REQUIRE(legNPV_[0] != Null<Real>(), "result not available");
        return legNPV_[0];
    }
Spread QuantLib::BMASwap::liborSpread () const
Definition at line 81 of file bmaswap.cpp.
References liborSpread_.
{
        return liborSpread_;
    }
Real QuantLib::BMASwap::nominal () const
Definition at line 85 of file bmaswap.cpp.
References nominal_.
{
        return nominal_;
    }
BMASwap::Type QuantLib::BMASwap::type () const
"payer" or "receiver" refer to the BMA leg
Definition at line 89 of file bmaswap.cpp.
References type_.
{
        return type_;
    }
Member Data Documentation
Rate QuantLib::BMASwap::liborFraction_ [private]
Definition at line 76 of file bmaswap.hpp.
Referenced by fairLiborFraction(), and liborFraction().
Rate QuantLib::BMASwap::liborSpread_ [private]
Definition at line 77 of file bmaswap.hpp.
Referenced by fairLiborFraction(), fairLiborSpread(), and liborSpread().
Real QuantLib::BMASwap::nominal_ [private]
Definition at line 75 of file bmaswap.hpp.
Referenced by nominal().
Type QuantLib::BMASwap::type_ [private]
Definition at line 74 of file bmaswap.hpp.
Referenced by BMASwap(), and type().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/bmaswap.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/bmaswap.cpp