QuantLib: QuantLib::MarketModelPathwiseMultiProduct Class Reference
QuantLib::MarketModelPathwiseMultiProduct Class Reference
market-model pathwise product
#include <pathwisemultiproduct.hpp>
Classes
struct CashFlow
Public Member Functions
virtual ~MarketModelPathwiseMultiProduct ()
virtual std::vector< Size > suggestedNumeraires () const =0
virtual const
EvolutionDescription & evolution () const =0
virtual std::vector< Time > possibleCashFlowTimes () const =0
virtual Size numberOfProducts () const =0
virtual Size maxNumberOfCashFlowsPerProductPerStep () const =0
virtual bool alreadyDeflated () const =0
virtual void reset ()=0
during simulation put product at start of path
virtual bool nextTimeStep (const CurveState &currentState, std::vector< Size > &numberCashFlowsThisStep, std::vector< std::vector< MarketModelPathwiseMultiProduct::CashFlow > > &cashFlowsGenerated)=0
return value indicates whether path is finished, TRUE means done
virtual std::auto_ptr
< MarketModelPathwiseMultiProduct > clone () const =0
returns a newly-allocated copy of itself
Detailed Description
market-model pathwise product
This is the abstract base class that encapsulates the notion of a product: it contains the information that would be in the termsheet of the product.
It's useful to have it be able to do several products simultaneously. The products would have to have the same underlying rate times of course. The class is therefore really encapsulating the notion of a multi-product.
For each time evolved to, it generates the cash flows associated to that time for the state of the yield curve. If one was doing a callable product then this would encompass the product and its exercise strategy.
This class differs from market-model multi-product in that it also returns the derivative of the pay-off with respect to each forward rate
Definition at line 53 of file pathwisemultiproduct.hpp.
Constructor & Destructor Documentation
virtual QuantLib::MarketModelPathwiseMultiProduct::~MarketModelPathwiseMultiProduct () [inline, virtual]
Definition at line 60 of file pathwisemultiproduct.hpp.
{}
Member Function Documentation
virtual bool QuantLib::MarketModelPathwiseMultiProduct::alreadyDeflated () const [pure virtual]
Implemented in QuantLib::MarketModelPathwiseMultiDeflatedCap, QuantLib::MarketModelPathwiseMultiDeflatedCaplet, QuantLib::MarketModelPathwiseCoterminalSwaptionsNumericalDeflated, QuantLib::MarketModelPathwiseInverseFloater, QuantLib::CallSpecifiedPathwiseMultiProduct, QuantLib::MarketModelPathwiseMultiCaplet, QuantLib::MarketModelPathwiseSwap, QuantLib::MarketModelPathwiseCashRebate, and QuantLib::MarketModelPathwiseCoterminalSwaptionsDeflated.
Referenced by QuantLib::CallSpecifiedPathwiseMultiProduct::alreadyDeflated(), and QuantLib::CallSpecifiedPathwiseMultiProduct::CallSpecifiedPathwiseMultiProduct().
virtual std::auto_ptr<MarketModelPathwiseMultiProduct> QuantLib::MarketModelPathwiseMultiProduct::clone () const [pure virtual]
returns a newly-allocated copy of itself
Implemented in QuantLib::MarketModelPathwiseMultiDeflatedCap, QuantLib::MarketModelPathwiseMultiDeflatedCaplet, QuantLib::MarketModelPathwiseCoterminalSwaptionsNumericalDeflated, QuantLib::MarketModelPathwiseInverseFloater, QuantLib::MarketModelPathwiseMultiCaplet, QuantLib::MarketModelPathwiseSwap, QuantLib::MarketModelPathwiseCoterminalSwaptionsDeflated, QuantLib::MarketModelPathwiseCashRebate, and QuantLib::CallSpecifiedPathwiseMultiProduct.
virtual const EvolutionDescription& QuantLib::MarketModelPathwiseMultiProduct::evolution () const [pure virtual]
Implemented in QuantLib::MarketModelPathwiseMultiDeflatedCap, QuantLib::MarketModelPathwiseMultiDeflatedCaplet, QuantLib::MarketModelPathwiseCoterminalSwaptionsNumericalDeflated, QuantLib::MarketModelPathwiseInverseFloater, QuantLib::MarketModelPathwiseMultiCaplet, QuantLib::MarketModelPathwiseSwap, QuantLib::MarketModelPathwiseCashRebate, QuantLib::CallSpecifiedPathwiseMultiProduct, and QuantLib::MarketModelPathwiseCoterminalSwaptionsDeflated.
Referenced by QuantLib::CallSpecifiedPathwiseMultiProduct::CallSpecifiedPathwiseMultiProduct(), QuantLib::MultiProductPathwiseWrapper::evolution(), QuantLib::MultiProductPathwiseWrapper::MultiProductPathwiseWrapper(), QuantLib::PathwiseAccountingEngine::PathwiseAccountingEngine(), QuantLib::PathwiseVegasAccountingEngine::PathwiseVegasAccountingEngine(), QuantLib::PathwiseVegasOuterAccountingEngine::PathwiseVegasOuterAccountingEngine(), and MarketModelTest::testPathwiseGreeks().
virtual Size QuantLib::MarketModelPathwiseMultiProduct::maxNumberOfCashFlowsPerProductPerStep () const [pure virtual]
Implemented in QuantLib::MarketModelPathwiseMultiDeflatedCap, QuantLib::MarketModelPathwiseMultiDeflatedCaplet, QuantLib::MarketModelPathwiseCoterminalSwaptionsNumericalDeflated, QuantLib::MarketModelPathwiseInverseFloater, QuantLib::MarketModelPathwiseMultiCaplet, QuantLib::MarketModelPathwiseSwap, QuantLib::MarketModelPathwiseCashRebate, QuantLib::CallSpecifiedPathwiseMultiProduct, and QuantLib::MarketModelPathwiseCoterminalSwaptionsDeflated.
Referenced by QuantLib::CallSpecifiedPathwiseMultiProduct::CallSpecifiedPathwiseMultiProduct(), QuantLib::MultiProductPathwiseWrapper::maxNumberOfCashFlowsPerProductPerStep(), QuantLib::CallSpecifiedPathwiseMultiProduct::maxNumberOfCashFlowsPerProductPerStep(), QuantLib::PathwiseAccountingEngine::PathwiseAccountingEngine(), QuantLib::PathwiseVegasAccountingEngine::PathwiseVegasAccountingEngine(), and QuantLib::PathwiseVegasOuterAccountingEngine::PathwiseVegasOuterAccountingEngine().
virtual bool QuantLib::MarketModelPathwiseMultiProduct::nextTimeStep (const CurveState & currentState, std::vector< Size > & numberCashFlowsThisStep, std::vector< std::vector< MarketModelPathwiseMultiProduct::CashFlow > > & cashFlowsGenerated) [pure virtual]
return value indicates whether path is finished, TRUE means done
Implemented in QuantLib::MarketModelPathwiseMultiDeflatedCap, QuantLib::MarketModelPathwiseMultiDeflatedCaplet, QuantLib::MarketModelPathwiseCoterminalSwaptionsNumericalDeflated, QuantLib::MarketModelPathwiseInverseFloater, QuantLib::MarketModelPathwiseMultiCaplet, QuantLib::MarketModelPathwiseSwap, QuantLib::MarketModelPathwiseCoterminalSwaptionsDeflated, QuantLib::MarketModelPathwiseCashRebate, and QuantLib::CallSpecifiedPathwiseMultiProduct.
Referenced by QuantLib::MultiProductPathwiseWrapper::nextTimeStep(), QuantLib::CallSpecifiedPathwiseMultiProduct::nextTimeStep(), QuantLib::PathwiseAccountingEngine::singlePathValues(), QuantLib::PathwiseVegasAccountingEngine::singlePathValues(), and QuantLib::PathwiseVegasOuterAccountingEngine::singlePathValues().
virtual Size QuantLib::MarketModelPathwiseMultiProduct::numberOfProducts () const [pure virtual]
Implemented in QuantLib::MarketModelPathwiseMultiDeflatedCap, QuantLib::MarketModelPathwiseMultiDeflatedCaplet, QuantLib::MarketModelPathwiseCoterminalSwaptionsNumericalDeflated, QuantLib::MarketModelPathwiseInverseFloater, QuantLib::MarketModelPathwiseMultiCaplet, QuantLib::MarketModelPathwiseSwap, QuantLib::MarketModelPathwiseCashRebate, QuantLib::CallSpecifiedPathwiseMultiProduct, and QuantLib::MarketModelPathwiseCoterminalSwaptionsDeflated.
Referenced by QuantLib::CallSpecifiedPathwiseMultiProduct::CallSpecifiedPathwiseMultiProduct(), QuantLib::PathwiseAccountingEngine::multiplePathValues(), QuantLib::PathwiseVegasAccountingEngine::multiplePathValues(), QuantLib::PathwiseVegasOuterAccountingEngine::multiplePathValuesElementary(), QuantLib::MultiProductPathwiseWrapper::numberOfProducts(), QuantLib::CallSpecifiedPathwiseMultiProduct::numberOfProducts(), MarketModelTest::testPathwiseGreeks(), and MarketModelTest::testPathwiseVegas().
virtual std::vector<Time> QuantLib::MarketModelPathwiseMultiProduct::possibleCashFlowTimes () const [pure virtual]
Implemented in QuantLib::MarketModelPathwiseMultiDeflatedCap, QuantLib::MarketModelPathwiseMultiDeflatedCaplet, QuantLib::MarketModelPathwiseCoterminalSwaptionsNumericalDeflated, QuantLib::MarketModelPathwiseInverseFloater, QuantLib::MarketModelPathwiseMultiCaplet, QuantLib::MarketModelPathwiseSwap, QuantLib::MarketModelPathwiseCashRebate, QuantLib::CallSpecifiedPathwiseMultiProduct, and QuantLib::MarketModelPathwiseCoterminalSwaptionsDeflated.
Referenced by QuantLib::CallSpecifiedPathwiseMultiProduct::CallSpecifiedPathwiseMultiProduct(), QuantLib::PathwiseAccountingEngine::PathwiseAccountingEngine(), QuantLib::PathwiseVegasAccountingEngine::PathwiseVegasAccountingEngine(), QuantLib::PathwiseVegasOuterAccountingEngine::PathwiseVegasOuterAccountingEngine(), and QuantLib::MultiProductPathwiseWrapper::possibleCashFlowTimes().
virtual void QuantLib::MarketModelPathwiseMultiProduct::reset () [pure virtual]
during simulation put product at start of path
Implemented in QuantLib::MarketModelPathwiseMultiDeflatedCap, QuantLib::MarketModelPathwiseMultiDeflatedCaplet, QuantLib::MarketModelPathwiseCoterminalSwaptionsNumericalDeflated, QuantLib::MarketModelPathwiseInverseFloater, QuantLib::MarketModelPathwiseMultiCaplet, QuantLib::MarketModelPathwiseSwap, QuantLib::MarketModelPathwiseCoterminalSwaptionsDeflated, QuantLib::MarketModelPathwiseCashRebate, and QuantLib::CallSpecifiedPathwiseMultiProduct.
Referenced by QuantLib::MultiProductPathwiseWrapper::reset(), QuantLib::CallSpecifiedPathwiseMultiProduct::reset(), QuantLib::PathwiseAccountingEngine::singlePathValues(), QuantLib::PathwiseVegasAccountingEngine::singlePathValues(), and QuantLib::PathwiseVegasOuterAccountingEngine::singlePathValues().
virtual std::vector<Size> QuantLib::MarketModelPathwiseMultiProduct::suggestedNumeraires () const [pure virtual]
Implemented in QuantLib::MarketModelPathwiseMultiDeflatedCap, QuantLib::MarketModelPathwiseMultiDeflatedCaplet, QuantLib::MarketModelPathwiseCoterminalSwaptionsNumericalDeflated, QuantLib::MarketModelPathwiseInverseFloater, QuantLib::MarketModelPathwiseMultiCaplet, QuantLib::MarketModelPathwiseSwap, QuantLib::MarketModelPathwiseCashRebate, QuantLib::CallSpecifiedPathwiseMultiProduct, and QuantLib::MarketModelPathwiseCoterminalSwaptionsDeflated.
Referenced by QuantLib::CallSpecifiedPathwiseMultiProduct::suggestedNumeraires(), and QuantLib::MultiProductPathwiseWrapper::suggestedNumeraires().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/pathwisemultiproduct.hpp