QuantLib: QuantLib::NumericHaganPricer Class Reference
QuantLib::NumericHaganPricer Class Reference
CMS-coupon pricer.
#include <conundrumpricer.hpp>
Classes
class ConundrumIntegrand
class Function
Public Member Functions
NumericHaganPricer (const Handle< SwaptionVolatilityStructure > &swaptionVol, GFunctionFactory::YieldCurveModel modelOfYieldCurve, const Handle< Quote > &meanReversion, Rate lowerLimit=0.0, Rate upperLimit=1.0, Real precision=1.0e-6)
Real upperLimit ()
Real stdDeviations ()
Real integrate (Real a, Real b, const ConundrumIntegrand &Integrand) const
virtual Real optionletPrice (Option::Type optionType, Rate strike) const
virtual Real swapletPrice () const
Real resetUpperLimit (Real stdDeviationsForUpperLimit) const
Real refineIntegration (Real integralValue, const ConundrumIntegrand &integrand) const
Public Attributes
Real upperLimit_
Real stdDeviationsForUpperLimit_
const Real lowerLimit_
const Real requiredStdDeviations_
const Real precision_
const Real refiningIntegrationTolerance_
Detailed Description
CMS-coupon pricer.
Prices a cms coupon via static replication as in Hagan's "Conundrums..." article via numerical integration based on prices of vanilla swaptions
Definition at line 249 of file conundrumpricer.hpp.
Constructor & Destructor Documentation
QuantLib::NumericHaganPricer::NumericHaganPricer (const Handle< SwaptionVolatilityStructure > & swaptionVol, GFunctionFactory::YieldCurveModel modelOfYieldCurve, const Handle< Quote > & meanReversion, Rate lowerLimit = 0.0, Rate upperLimit = 1.0, Real precision = 1.0e-6)
Definition at line 240 of file conundrumpricer.cpp.
    : HaganPricer(swaptionVol, modelOfYieldCurve, meanReversion),
       upperLimit_(upperLimit),
       lowerLimit_(lowerLimit),
       requiredStdDeviations_(8),
       precision_(precision),
       refiningIntegrationTolerance_(.0001){
    }
Member Function Documentation
Real QuantLib::NumericHaganPricer::integrate (Real a, Real b, const ConundrumIntegrand & Integrand) const
Definition at line 256 of file conundrumpricer.cpp.
References anonymous_namespace{marketmodel.cpp}::a, anonymous_namespace{interpolations.cpp}::f(), QuantLib::Integrator::integrationSuccess(), and precision_.
Referenced by optionletPrice(), and refineIntegration().
{
            double result =.0;
            //double abserr =.0;
            //double alpha = 1.0;
            //double epsabs = precision_;
            //double epsrel = 1.0; // we are interested only in absolute precision
            //size_t neval =0;
            // we use the non adaptive algorithm only for semi infinite interval
            if (a>0){
                // we estimate the actual boudary by testing integrand values
                Real upperBoundary = 2*a;
                while(integrand(upperBoundary)>precision_)
                    upperBoundary *=2.0;
                // sometimes b < a because of a wrong estimation of b based on stdev
                if (b > a)
                    upperBoundary = std::min(upperBoundary, b);
                boost::function<Real (Real)> f;
                GaussKronrodNonAdaptive
                    gaussKronrodNonAdaptive(precision_, 1000000, 1.0);
                // if the integration intervall is wide enough we use the
                // following change variable x -> a + (b-a)*(t/(a-b))^3
                if (upperBoundary > 2*a){
                    Size k = 3;
                    boost::function<Real (Real)> temp = boost::ref(integrand);
                    VariableChange variableChange(temp, a, upperBoundary, k);
                    f = boost::bind(&VariableChange::value, &variableChange, _1);
                    result = gaussKronrodNonAdaptive(f, .0, 1.0);
                } else {
                    f = boost::ref(integrand);
                    result = gaussKronrodNonAdaptive(f, a, upperBoundary);
                }
                // if the expected precision has not been reached we use the old algorithm
                if (!gaussKronrodNonAdaptive.integrationSuccess()){
                    const GaussKronrodAdaptive integrator(precision_, 1000000);
                    result = integrator(integrand,a , b);
                }
            } else {   // if a < b we use the old algorithm
                const GaussKronrodAdaptive integrator(precision_, 1000000);
                result = integrator(integrand,a , b);
            }
            return result;
    }
Real QuantLib::NumericHaganPricer::optionletPrice (Option::Type optionType, Rate strike) const [virtual]
Implements QuantLib::HaganPricer.
Definition at line 308 of file conundrumpricer.cpp.
References anonymous_namespace{marketmodel.cpp}::a, QuantLib::Coupon::accrualPeriod(), QuantLib::HaganPricer::annuity_, anonymous_namespace{marketmodel.cpp}::b, QuantLib::Option::Call, QuantLib::HaganPricer::coupon_, QuantLib::HaganPricer::discount_, QuantLib::HaganPricer::fixingDate_, QuantLib::HaganPricer::gFunction_, integrate(), lowerLimit_, QuantLib::HaganPricer::paymentDate_, QuantLib::HaganPricer::rateCurve_, requiredStdDeviations_, resetUpperLimit(), stdDeviationsForUpperLimit_, QuantLib::HaganPricer::swapRateValue_, upperLimit_, and QuantLib::HaganPricer::vanillaOptionPricer_.
Referenced by swapletPrice().
{
        boost::shared_ptr<ConundrumIntegrand> integrand(new
            ConundrumIntegrand(vanillaOptionPricer_, rateCurve_, gFunction_,
                               fixingDate_, paymentDate_, annuity_,
                               swapRateValue_, strike, optionType));
        stdDeviationsForUpperLimit_= requiredStdDeviations_;
        Real a, b, integralValue;
        if (optionType==Option::Call) {
            upperLimit_ = resetUpperLimit(stdDeviationsForUpperLimit_);
        //    while(upperLimit_ <= strike){
        //        stdDeviationsForUpperLimit_ += 1.;
        //        upperLimit_ = resetUpperLimit(stdDeviationsForUpperLimit_);
        //    }
            integralValue = integrate(strike, upperLimit_, *integrand);
            //refineIntegration(integralValue, *integrand);
        } else {
            a = std::min(strike, lowerLimit_);
            b = strike;
            integralValue = integrate(a, b, *integrand);
        }
        Real dFdK = integrand->firstDerivativeOfF(strike);
        Real swaptionPrice =
            (*vanillaOptionPricer_)(strike, optionType, annuity_);
        // v. HAGAN, Conundrums..., formule 2.17a, 2.18a
        return coupon_->accrualPeriod() * (discount_/annuity_) *
            ((1 + dFdK) * swaptionPrice + optionType*integralValue);
    }
Real QuantLib::NumericHaganPricer::refineIntegration (Real integralValue, const ConundrumIntegrand & integrand) const
Definition at line 357 of file conundrumpricer.cpp.
References integrate(), refiningIntegrationTolerance_, resetUpperLimit(), stdDeviationsForUpperLimit_, and upperLimit_.
{
        Real percDiff = 1000.;
        while(std::fabs(percDiff) < refiningIntegrationTolerance_){
            stdDeviationsForUpperLimit_ += 1.;
            Real lowerLimit = upperLimit_;
            upperLimit_ = resetUpperLimit(stdDeviationsForUpperLimit_);
            Real diff = integrate(lowerLimit, upperLimit_,integrand);
            percDiff = diff/integralValue;
            integralValue += diff;
        }
        return integralValue;
    }
Real QuantLib::NumericHaganPricer::resetUpperLimit (Real stdDeviationsForUpperLimit) const
Definition at line 371 of file conundrumpricer.cpp.
References QuantLib::HaganPricer::fixingDate_, QuantLib::HaganPricer::swapRateValue_, QuantLib::HaganPricer::swapTenor_, and QuantLib::CmsCouponPricer::swaptionVolatility().
Referenced by optionletPrice(), and refineIntegration().
{
        //return 1.0;
        Real variance =
            swaptionVolatility()->blackVariance(fixingDate_,swapTenor_,swapRateValue_);
        return swapRateValue_ *
            std::exp(stdDeviationsForUpperLimit*std::sqrt(variance));
    }
Real QuantLib::NumericHaganPricer::stdDeviations () [inline]
Definition at line 260 of file conundrumpricer.hpp.
References stdDeviationsForUpperLimit_.
{ return stdDeviationsForUpperLimit_; }
Real QuantLib::NumericHaganPricer::swapletPrice () const [virtual]
Implements QuantLib::HaganPricer.
Definition at line 340 of file conundrumpricer.cpp.
References QuantLib::Coupon::accrualPeriod(), QuantLib::Option::Call, QuantLib::HaganPricer::coupon_, QuantLib::HaganPricer::discount_, QuantLib::Settings::evaluationDate(), QuantLib::HaganPricer::fixingDate_, QuantLib::HaganPricer::gearing_, QuantLib::Singleton< Settings >::instance(), optionletPrice(), QuantLib::Option::Put, QuantLib::HaganPricer::spread_, QuantLib::HaganPricer::spreadLegValue_, QuantLib::CmsCoupon::swapIndex(), and QuantLib::HaganPricer::swapRateValue_.
{
        Date today = Settings::instance().evaluationDate();
        if (fixingDate_ <= today) {
            // the fixing is determined
            const Rate Rs = coupon_->swapIndex()->fixing(fixingDate_);
            Rate price = (gearing_*Rs + spread_)*(coupon_->accrualPeriod()*discount_);
            return price;
        } else {
            Real atmCapletPrice = optionletPrice(Option::Call, swapRateValue_);
            Real atmFloorletPrice = optionletPrice(Option::Put, swapRateValue_);
            return gearing_ *(coupon_->accrualPeriod()* discount_ * swapRateValue_
                             + atmCapletPrice - atmFloorletPrice)
                   + spreadLegValue_;
        }
    }
Real QuantLib::NumericHaganPricer::upperLimit () [inline]
Definition at line 259 of file conundrumpricer.hpp.
References upperLimit_.
{ return upperLimit_; }
Member Data Documentation
const Real QuantLib::NumericHaganPricer::lowerLimit_
Definition at line 311 of file conundrumpricer.hpp.
Referenced by optionletPrice().
const Real QuantLib::NumericHaganPricer::precision_
Definition at line 311 of file conundrumpricer.hpp.
Referenced by integrate().
const Real QuantLib::NumericHaganPricer::refiningIntegrationTolerance_
Definition at line 311 of file conundrumpricer.hpp.
Referenced by refineIntegration().
const Real QuantLib::NumericHaganPricer::requiredStdDeviations_
Definition at line 311 of file conundrumpricer.hpp.
Referenced by optionletPrice().
Real QuantLib::NumericHaganPricer::stdDeviationsForUpperLimit_ [mutable]
Definition at line 310 of file conundrumpricer.hpp.
Referenced by optionletPrice(), refineIntegration(), and stdDeviations().
Real QuantLib::NumericHaganPricer::upperLimit_ [mutable]
Definition at line 310 of file conundrumpricer.hpp.
Referenced by optionletPrice(), refineIntegration(), and upperLimit().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/conundrumpricer.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/conundrumpricer.cpp