QuantLib: QuantLib::Schedule Class Reference
QuantLib::Schedule Class Reference
Payment schedule.
#include <schedule.hpp>
Public Member Functions
Schedule (const std::vector< Date > &, const Calendar &calendar=NullCalendar(), BusinessDayConvention convention=Unadjusted)
Schedule (Date effectiveDate, const Date &terminationDate, const Period &tenor, const Calendar &calendar, BusinessDayConvention convention, BusinessDayConvention terminationDateConvention, DateGeneration::Rule rule, bool endOfMonth, const Date &firstDate=Date(), const Date &nextToLastDate=Date())
Schedule ()
Date access
Size size () const
const Date & operator[] (Size i) const
const Date & at (Size i) const
const Date & date (Size i) const
Date previousDate (const Date &refDate) const
Date nextDate (const Date &refDate) const
const std::vector< Date > & dates () const
bool isRegular (Size i) const
Other inspectors
bool empty () const
const Calendar & calendar () const
const Date & startDate () const
const Date & endDate () const
const Period & tenor () const
BusinessDayConvention businessDayConvention () const
BusinessDayConvention terminationDateBusinessDayConvention () const
DateGeneration::Rule rule () const
bool endOfMonth () const
Utilities
Schedule until (const Date &truncationDate) const
truncated schedule
Private Attributes
bool fullInterface_
Period tenor_
Calendar calendar_
BusinessDayConvention convention_
BusinessDayConvention terminationDateConvention_
DateGeneration::Rule rule_
bool endOfMonth_
Date firstDate_
Date nextToLastDate_
std::vector< Date > dates_
std::vector< bool > isRegular_
Iterators
typedef std::vector< Date >
::const_iterator const_iterator
const_iterator begin () const
const_iterator end () const
const_iterator lower_bound (const Date &d=Date()) const
Detailed Description
Payment schedule.
Definition at line 40 of file schedule.hpp.
Member Typedef Documentation
typedef std::vector<Date>::const_iterator QuantLib::Schedule::const_iterator
Definition at line 81 of file schedule.hpp.
Constructor & Destructor Documentation
QuantLib::Schedule::Schedule (const std::vector< Date > & dates, const Calendar & calendar = NullCalendar(), BusinessDayConvention convention = Unadjusted)
Definition at line 64 of file schedule.cpp.
    : fullInterface_(false),
      tenor_(Period()), calendar_(calendar),
      convention_(convention),
      terminationDateConvention_(convention),
      rule_(DateGeneration::Forward), endOfMonth_(false),
      dates_(dates) {}
QuantLib::Schedule::Schedule (Date effectiveDate, const Date & terminationDate, const Period & tenor, const Calendar & calendar, BusinessDayConvention convention, BusinessDayConvention terminationDateConvention, DateGeneration::Rule rule, bool endOfMonth, const Date & firstDate = Date(), const Date & nextToLastDate = Date())
Definition at line 74 of file schedule.cpp.
References QuantLib::Calendar::adjust(), QuantLib::Calendar::advance(), QuantLib::DateGeneration::Backward, calendar_, QuantLib::DateGeneration::CDS, dates_, QuantLib::Calendar::endOfMonth(), QuantLib::Date::endOfMonth(), QuantLib::Settings::evaluationDate(), firstDate_, QuantLib::DateGeneration::Forward, QuantLib::Singleton< Settings >::instance(), QuantLib::Calendar::isEndOfMonth(), QuantLib::IMM::isIMMdate(), isRegular_, QuantLib::Period::length(), nextToLastDate_, QuantLib::anonymous_namespace{schedule.cpp}::nextTwentieth(), QuantLib::Date::nthWeekday(), QuantLib::DateGeneration::OldCDS, QuantLib::anonymous_namespace{schedule.cpp}::previousTwentieth(), QL_FAIL, QL_REQUIRE, rule_, tenor_, QuantLib::DateGeneration::ThirdWednesday, QuantLib::DateGeneration::Twentieth, QuantLib::DateGeneration::TwentiethIMM, QuantLib::Unadjusted, QuantLib::Wednesday, QuantLib::Years, and QuantLib::DateGeneration::Zero.
    : fullInterface_(true),
      tenor_(tenor), calendar_(cal),
      convention_(convention),
      terminationDateConvention_(terminationDateConvention),
      rule_(rule), endOfMonth_(endOfMonth),
      firstDate_(first==effectiveDate ? Date() : first),
      nextToLastDate_(nextToLast==terminationDate ? Date() : nextToLast)
    {
        // sanity checks
        QL_REQUIRE(terminationDate != Date(), "null termination date");
        // in many cases (e.g. non-expired bonds) the effective date is not
        // really necessary. In these cases a decent placeholder is enough
        if (effectiveDate==Date() && first==Date()
                                  && rule==DateGeneration::Backward) {
            Date evalDate = Settings::instance().evaluationDate();
            QL_REQUIRE(evalDate < terminationDate, "null effective date");
            Natural y;
            if (nextToLast != Date()) {
                y = (nextToLast - evalDate)/366 + 1;
                effectiveDate = nextToLast - y*Years;
            } else {
                y = (terminationDate - evalDate)/366 + 1;
                effectiveDate = terminationDate - y*Years;
            }
        } else
            QL_REQUIRE(effectiveDate != Date(), "null effective date");
        QL_REQUIRE(effectiveDate < terminationDate,
                   "effective date (" << effectiveDate
                   << ") later than or equal to termination date ("
                   << terminationDate << ")");
        if (tenor.length()==0)
            rule_ = DateGeneration::Zero;
        else
            QL_REQUIRE(tenor.length()>0,
                       "non positive tenor (" << tenor << ") not allowed");
        if (firstDate_ != Date()) {
            switch (rule_) {
              case DateGeneration::Backward:
              case DateGeneration::Forward:
                QL_REQUIRE(firstDate_ > effectiveDate &&
                           firstDate_ < terminationDate,
                           "first date (" << firstDate_ <<
                           ") out of effective-termination date range [" <<
                           effectiveDate << ", " << terminationDate << ")");
                // we should ensure that the above condition is still
                // verified after adjustment
                break;
              case DateGeneration::ThirdWednesday:
                  QL_REQUIRE(IMM::isIMMdate(firstDate_, false),
                             "first date (" << firstDate_ <<
                             ") is not an IMM date");
                break;
              case DateGeneration::Zero:
              case DateGeneration::Twentieth:
              case DateGeneration::TwentiethIMM:
              case DateGeneration::OldCDS:
              case DateGeneration::CDS:
                QL_FAIL("first date incompatible with " << rule_ <<
                        " date generation rule");
              default:
                QL_FAIL("unknown rule (" << Integer(rule_) << ")");
            }
        }
        if (nextToLastDate_ != Date()) {
            switch (rule_) {
              case DateGeneration::Backward:
              case DateGeneration::Forward:
                QL_REQUIRE(nextToLastDate_ > effectiveDate &&
                           nextToLastDate_ < terminationDate,
                           "next to last date (" << nextToLastDate_ <<
                           ") out of effective-termination date range (" <<
                           effectiveDate << ", " << terminationDate << "]");
                // we should ensure that the above condition is still
                // verified after adjustment
                break;
              case DateGeneration::ThirdWednesday:
                QL_REQUIRE(IMM::isIMMdate(nextToLastDate_, false),
                           "next-to-last date (" << nextToLastDate_ <<
                           ") is not an IMM date");
                break;
              case DateGeneration::Zero:
              case DateGeneration::Twentieth:
              case DateGeneration::TwentiethIMM:
              case DateGeneration::OldCDS:
              case DateGeneration::CDS:
                QL_FAIL("next to last date incompatible with " << rule_ <<
                        " date generation rule");
              default:
                QL_FAIL("unknown rule (" << Integer(rule_) << ")");
            }
        }
        // calendar needed for endOfMonth adjustment
        Calendar nullCalendar = NullCalendar();
        Integer periods = 1;
        Date seed, exitDate;
        switch (rule_) {
          case DateGeneration::Zero:
            tenor_ = 0*Years;
            dates_.push_back(effectiveDate);
            dates_.push_back(terminationDate);
            isRegular_.push_back(true);
            break;
          case DateGeneration::Backward:
            dates_.push_back(terminationDate);
            seed = terminationDate;
            if (nextToLastDate_ != Date()) {
                dates_.insert(dates_.begin(), nextToLastDate_);
                Date temp = nullCalendar.advance(seed,
                    -periods*tenor_, convention, endOfMonth);
                if (temp!=nextToLastDate_)
                    isRegular_.insert(isRegular_.begin(), false);
                else
                    isRegular_.insert(isRegular_.begin(), true);
                seed = nextToLastDate_;
            }
            exitDate = effectiveDate;
            if (firstDate_ != Date())
                exitDate = firstDate_;
            for (;;) {
                Date temp = nullCalendar.advance(seed,
                    -periods*tenor_, convention, endOfMonth);
                if (temp < exitDate) {
                    if (firstDate_ != Date() &&
                        (calendar_.adjust(dates_.front(),convention)!=
                         calendar_.adjust(firstDate_,convention))) {
                        dates_.insert(dates_.begin(), firstDate_);
                        isRegular_.insert(isRegular_.begin(), false);
                    }
                    break;
                } else {
                    // skip dates that would result in duplicates
                    // after adjustment
                    if (calendar_.adjust(dates_.front(),convention)!=
                        calendar_.adjust(temp,convention)) {
                        dates_.insert(dates_.begin(), temp);
                        isRegular_.insert(isRegular_.begin(), true);
                    }
                    ++periods;
                }
            }
            if (calendar_.adjust(dates_.front(),convention)!=
                calendar_.adjust(effectiveDate,convention)) {
                dates_.insert(dates_.begin(), effectiveDate);
                isRegular_.insert(isRegular_.begin(), false);
            }
            break;
          case DateGeneration::Twentieth:
          case DateGeneration::TwentiethIMM:
          case DateGeneration::ThirdWednesday:
          case DateGeneration::OldCDS:
          case DateGeneration::CDS:
            QL_REQUIRE(!endOfMonth,
                       "endOfMonth convention incompatible with " << rule_ <<
                       " date generation rule");
          // fall through
          case DateGeneration::Forward:
            if (rule_ == DateGeneration::CDS) {
                dates_.push_back(previousTwentieth(effectiveDate,
                                                   DateGeneration::CDS));
            } else {
                dates_.push_back(effectiveDate);
            }
            seed = dates_.back();
            if (firstDate_!=Date()) {
                dates_.push_back(firstDate_);
                Date temp = nullCalendar.advance(seed, periods*tenor_,
                                                 convention, endOfMonth);
                if (temp!=firstDate_)
                    isRegular_.push_back(false);
                else
                    isRegular_.push_back(true);
                seed = firstDate_;
            } else if (rule_ == DateGeneration::Twentieth ||
                       rule_ == DateGeneration::TwentiethIMM ||
                       rule_ == DateGeneration::OldCDS ||
                       rule_ == DateGeneration::CDS) {
                Date next20th = nextTwentieth(effectiveDate, rule_);
                if (rule_ == DateGeneration::OldCDS) {
                    // distance rule inforced in natural days
                    static const BigInteger stubDays = 30;
                    if (next20th - effectiveDate < stubDays) {
                        // +1 will skip this one and get the next
                        next20th = nextTwentieth(next20th + 1, rule_);
                    }
                }
                if (next20th != effectiveDate) {
                    dates_.push_back(next20th);
                    isRegular_.push_back(false);
                    seed = next20th;
                }
            }
            exitDate = terminationDate;
            if (nextToLastDate_ != Date())
                exitDate = nextToLastDate_;
            for (;;) {
                Date temp = nullCalendar.advance(seed, periods*tenor_,
                                                 convention, endOfMonth);
                if (temp > exitDate) {
                    if (nextToLastDate_ != Date() &&
                        (calendar_.adjust(dates_.back(),convention)!=
                         calendar_.adjust(nextToLastDate_,convention))) {
                        dates_.push_back(nextToLastDate_);
                        isRegular_.push_back(false);
                    }
                    break;
                } else {
                    // skip dates that would result in duplicates
                    // after adjustment
                    if (calendar_.adjust(dates_.back(),convention)!=
                        calendar_.adjust(temp,convention)) {
                        dates_.push_back(temp);
                        isRegular_.push_back(true);
                    }
                    ++periods;
                }
            }
            if (calendar_.adjust(dates_.back(),terminationDateConvention)!=
                calendar_.adjust(terminationDate,terminationDateConvention)) {
                if (rule_ == DateGeneration::Twentieth ||
                    rule_ == DateGeneration::TwentiethIMM ||
                    rule_ == DateGeneration::OldCDS ||
                    rule_ == DateGeneration::CDS) {
                    dates_.push_back(nextTwentieth(terminationDate, rule_));
                    isRegular_.push_back(true);
                } else {
                    dates_.push_back(terminationDate);
                    isRegular_.push_back(false);
                }
            }
            break;
          default:
            QL_FAIL("unknown rule (" << Integer(rule_) << ")");
        }
        // adjustments
        if (rule_==DateGeneration::ThirdWednesday)
            for (Size i=1; i<dates_.size()-1; ++i)
                dates_[i] = Date::nthWeekday(3, Wednesday,
                                             dates_[i].month(),
                                             dates_[i].year());
        if (endOfMonth && calendar_.isEndOfMonth(seed)) {
            // adjust to end of month
            if (convention == Unadjusted) {
                for (Size i=0; i<dates_.size()-1; ++i)
                    dates_[i] = Date::endOfMonth(dates_[i]);
            } else {
                for (Size i=0; i<dates_.size()-1; ++i)
                    dates_[i] = calendar_.endOfMonth(dates_[i]);
            }
            if (terminationDateConvention != Unadjusted)
                dates_.back() = calendar_.endOfMonth(dates_.back());
        } else {
            // first date not adjusted for CDS schedules
            if (rule_ != DateGeneration::OldCDS)
                dates_[0] = calendar_.adjust(dates_[0], convention);
            for (Size i=1; i<dates_.size()-1; ++i)
                dates_[i] = calendar_.adjust(dates_[i], convention);
            // termination date is NOT adjusted as per ISDA
            // specifications, unless otherwise specified in the
            // confirmation of the deal or unless we're creating a CDS
            // schedule
            if (terminationDateConvention != Unadjusted
                || rule_ == DateGeneration::Twentieth
                || rule_ == DateGeneration::TwentiethIMM
                || rule_ == DateGeneration::OldCDS
                || rule_ == DateGeneration::CDS) {
                dates_.back() = calendar_.adjust(dates_.back(),
                                                terminationDateConvention);
            }
        }
        // final safety check to remove duplicated last dates, if any
        // it can happen if EOM is applied to two near dates
        if (dates_.back() == dates_[dates_.size()-2]) {
            dates_.pop_back();
            isRegular_.pop_back();
        }
    }
QuantLib::Schedule::Schedule () [inline]
Definition at line 55 of file schedule.hpp.
{}
Member Function Documentation
const Date & QuantLib::Schedule::at (Size i) const [inline]
Definition at line 152 of file schedule.hpp.
References dates_.
{
        return dates_.at(i);
    }
const_iterator QuantLib::Schedule::begin () const [inline]
Definition at line 82 of file schedule.hpp.
References dates_.
Referenced by HybridHestonHullWhiteProcessTest::testCallableEquityPricing().
{ return dates_.begin(); }
BusinessDayConvention QuantLib::Schedule::businessDayConvention () const [inline]
Definition at line 173 of file schedule.hpp.
References convention_.
Referenced by QuantLib::BMASwap::BMASwap(), QuantLib::ConvertibleFixedCouponBond::ConvertibleFixedCouponBond(), QuantLib::ConvertibleFloatingRateBond::ConvertibleFloatingRateBond(), QuantLib::FloatingDigitalLeg(), QuantLib::FloatingLeg(), QuantLib::FixedRateLeg::operator Leg(), QuantLib::yoyInflationLeg::operator Leg(), QuantLib::CPILeg::operator Leg(), and QuantLib::VanillaSwap::VanillaSwap().
{
        return convention_;
    }
const Calendar & QuantLib::Schedule::calendar () const [inline]
Definition at line 156 of file schedule.hpp.
References calendar_.
Referenced by QuantLib::CPISwap::CPISwap(), QuantLib::FloatingDigitalLeg(), QuantLib::FloatingLeg(), QuantLib::OvernightLeg::operator Leg(), QuantLib::AverageBMALeg::operator Leg(), QuantLib::FixedRateLeg::operator Leg(), QuantLib::yoyInflationLeg::operator Leg(), and QuantLib::CPILeg::operator Leg().
{
        return calendar_;
    }
const Date & QuantLib::Schedule::date (Size i) const [inline]
Definition at line 140 of file schedule.hpp.
References dates_.
Referenced by QuantLib::FloatingDigitalLeg(), QuantLib::FloatingLeg(), QuantLib::GFunctionFactory::GFunctionExactYield::GFunctionExactYield(), QuantLib::AverageBMACoupon::indexFixings(), QuantLib::HaganPricer::initialize(), QuantLib::OvernightLeg::operator Leg(), QuantLib::AverageBMALeg::operator Leg(), QuantLib::FixedRateLeg::operator Leg(), QuantLib::yoyInflationLeg::operator Leg(), and QuantLib::CPILeg::operator Leg().
{
        return dates_.at(i);
    }
const std::vector<Date>& QuantLib::Schedule::dates () const [inline]
Definition at line 64 of file schedule.hpp.
References dates_.
Referenced by QuantLib::CallableBond::CallableBond(), QuantLib::RiskyFixedBond::effectiveDate(), QuantLib::RiskyFloatingBond::effectiveDate(), QuantLib::MonteCarloCDOEngine1::expectedTrancheLoss(), QuantLib::RiskyAssetSwap::fairSpread(), QuantLib::AverageBMACoupon::fixingDates(), QuantLib::SyntheticCDO::engine::initialize(), QuantLib::RecursiveCdoEngine< CDOEngine, copulaT >::initialize(), QuantLib::CdsHelper::initializeDates(), QuantLib::RiskyAssetSwap::isExpired(), QuantLib::SyntheticCDO::isExpired(), QuantLib::CDO::isExpired(), QuantLib::RiskyFixedBond::maturityDate(), QuantLib::RiskyFloatingBond::maturityDate(), QuantLib::OvernightIndexedCoupon::OvernightIndexedCoupon(), QuantLib::RiskyAssetSwap::parCoupon(), QuantLib::RiskyAssetSwap::performCalculations(), QuantLib::RiskyAssetSwap::riskyBondPrice(), QuantLib::RiskyFixedBond::RiskyFixedBond(), QuantLib::RiskyFloatingBond::RiskyFloatingBond(), and QuantLib::SyntheticCDO::SyntheticCDO().
{ return dates_; }
bool QuantLib::Schedule::empty () const [inline]
Definition at line 69 of file schedule.hpp.
References dates_.
{ return dates_.empty(); }
const_iterator QuantLib::Schedule::end () const [inline]
Definition at line 83 of file schedule.hpp.
References dates_.
Referenced by HybridHestonHullWhiteProcessTest::testCallableEquityPricing().
{ return dates_.end(); }
const Date & QuantLib::Schedule::endDate () const [inline]
Definition at line 164 of file schedule.hpp.
References dates_.
Referenced by QuantLib::AmortizingCmsRateBond::AmortizingCmsRateBond(), QuantLib::AmortizingFixedRateBond::AmortizingFixedRateBond(), QuantLib::AmortizingFloatingRateBond::AmortizingFloatingRateBond(), QuantLib::CmsRateBond::CmsRateBond(), QuantLib::ConvertibleBond::ConvertibleBond(), QuantLib::CPIBond::CPIBond(), QuantLib::FixedRateBond::FixedRateBond(), and QuantLib::FloatingRateBond::FloatingRateBond().
{
        return dates_.back();
    }
bool QuantLib::Schedule::endOfMonth () const [inline]
Definition at line 188 of file schedule.hpp.
References endOfMonth_, fullInterface_, and QL_REQUIRE.
{
        QL_REQUIRE(fullInterface_, "full interface not available");
        return endOfMonth_;
    }
bool QuantLib::Schedule::isRegular (Size i) const
Definition at line 441 of file schedule.cpp.
References fullInterface_, isRegular_, and QL_REQUIRE.
Referenced by QuantLib::FloatingDigitalLeg(), QuantLib::FloatingLeg(), QuantLib::OvernightLeg::operator Leg(), QuantLib::AverageBMALeg::operator Leg(), QuantLib::FixedRateLeg::operator Leg(), QuantLib::yoyInflationLeg::operator Leg(), and QuantLib::CPILeg::operator Leg().
{
        QL_REQUIRE(fullInterface_, "full interface not available");
        QL_REQUIRE(i<=isRegular_.size() && i>0,
                   "index (" << i << ") must be in [1, " <<
                   isRegular_.size() <<"]");
        return isRegular_[i-1];
    }
std::vector< Date >::const_iterator QuantLib::Schedule::lower_bound (const Date & d = Date()) const
Definition at line 418 of file schedule.cpp.
References anonymous_namespace{marketmodel.cpp}::d, dates_, QuantLib::Settings::evaluationDate(), and QuantLib::Singleton< Settings >::instance().
Referenced by nextDate(), and previousDate().
{
        Date d = (refDate==Date() ?
                  Settings::instance().evaluationDate() :
                  refDate);
        return std::lower_bound(dates_.begin(), dates_.end(), d);
    }
Date QuantLib::Schedule::nextDate (const Date & refDate) const
Definition at line 425 of file schedule.cpp.
References dates_, and lower_bound().
{
        std::vector<Date>::const_iterator res = lower_bound(refDate);
        if (res!=dates_.end())
            return *res;
        else
            return Date();
    }
const Date & QuantLib::Schedule::operator[] (Size i) const [inline]
Definition at line 144 of file schedule.hpp.
References dates_.
{
        #if defined(QL_EXTRA_SAFETY_CHECKS)
        return dates_.at(i);
        #else
        return dates_[i];
        #endif
    }
Date QuantLib::Schedule::previousDate (const Date & refDate) const
Definition at line 433 of file schedule.cpp.
References dates_, and lower_bound().
{
        std::vector<Date>::const_iterator res = lower_bound(refDate);
        if (res!=dates_.begin())
            return *(--res);
        else
            return Date();
    }
DateGeneration::Rule QuantLib::Schedule::rule () const [inline]
Definition at line 183 of file schedule.hpp.
References fullInterface_, QL_REQUIRE, and rule_.
{
        QL_REQUIRE(fullInterface_, "full interface not available");
        return rule_;
    }
Size QuantLib::Schedule::size () const [inline]
Definition at line 58 of file schedule.hpp.
References dates_.
Referenced by anonymous_namespace{schedule.cpp}::check_dates(), anonymous_namespace{curvestates.cpp}::CommonVars::CommonVars(), anonymous_namespace{inflationcapfloor.cpp}::CommonVars::CommonVars(), anonymous_namespace{inflationcpiswap.cpp}::CommonVars::CommonVars(), anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::CommonVars(), anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::CommonVars(), CPISwapTest::consistency(), CPISwapTest::cpibondconsistency(), QuantLib::CPISwap::CPISwap(), QuantLib::RiskyAssetSwap::fairSpread(), QuantLib::RiskyAssetSwap::fixedAnnuity(), QuantLib::RiskyAssetSwap::floatAnnuity(), QuantLib::FloatingDigitalLeg(), QuantLib::FloatingLeg(), QuantLib::AverageBMACoupon::indexFixings(), anonymous_namespace{swapforwardmappings.cpp}::MarketModelData::MarketModelData(), QuantLib::RiskyFixedBond::notional(), QuantLib::RiskyFloatingBond::notional(), QuantLib::OvernightLeg::operator Leg(), QuantLib::AverageBMALeg::operator Leg(), QuantLib::FixedRateLeg::operator Leg(), QuantLib::yoyInflationLeg::operator Leg(), QuantLib::CPILeg::operator Leg(), QuantLib::CDO::performCalculations(), QuantLib::RiskyAssetSwap::recoveryValue(), QuantLib::RiskyAssetSwap::riskyBondPrice(), anonymous_namespace{marketmodel_cms.cpp}::setup(), anonymous_namespace{marketmodel_smm.cpp}::setup(), anonymous_namespace{marketmodel_smmcapletcalibration.cpp}::setup(), anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::setup(), anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::setup(), anonymous_namespace{marketmodel.cpp}::setup(), InflationTest::testYYIndex(), InflationTest::testZeroIndex(), and InflationTest::testZeroTermStructure().
{ return dates_.size(); }
const Date & QuantLib::Schedule::startDate () const [inline]
Definition at line 160 of file schedule.hpp.
References dates_.
Referenced by QuantLib::AssetSwap::AssetSwap(), QuantLib::GFunctionFactory::GFunctionExactYield::GFunctionExactYield(), QuantLib::SyntheticCDO::engine::initialize(), and QuantLib::MonteCarloCDOEngine1::initialize().
{
        return dates_.front();
    }
const Period & QuantLib::Schedule::tenor () const [inline]
Definition at line 168 of file schedule.hpp.
References fullInterface_, QL_REQUIRE, and tenor_.
Referenced by QuantLib::CallableFixedRateBond::CallableFixedRateBond(), QuantLib::FloatingDigitalLeg(), QuantLib::FloatingLeg(), QuantLib::OvernightLeg::operator Leg(), QuantLib::AverageBMALeg::operator Leg(), QuantLib::FixedRateLeg::operator Leg(), QuantLib::yoyInflationLeg::operator Leg(), and QuantLib::CPILeg::operator Leg().
{
        QL_REQUIRE(fullInterface_, "full interface not available");
        return tenor_;
    }
BusinessDayConvention QuantLib::Schedule::terminationDateBusinessDayConvention () const [inline]
Definition at line 178 of file schedule.hpp.
References fullInterface_, QL_REQUIRE, and terminationDateConvention_.
{
        QL_REQUIRE(fullInterface_, "full interface not available");
        return terminationDateConvention_;
    }
Schedule QuantLib::Schedule::until (const Date & truncationDate) const
truncated schedule
Definition at line 389 of file schedule.cpp.
References convention_, dates_, firstDate_, isRegular_, nextToLastDate_, terminationDateConvention_, and QuantLib::Unadjusted.
Referenced by QuantLib::AssetSwap::AssetSwap().
{
        Schedule result = *this;
        if (truncationDate<result.dates_.back()) {
            // remove later dates
            while (result.dates_.back()>truncationDate) {
                result.dates_.pop_back();
                result.isRegular_.pop_back();
            }
            // add truncationDate if missing
            if (truncationDate!=result.dates_.back()) {
                result.dates_.push_back(truncationDate);
                result.isRegular_.push_back(false);
                result.terminationDateConvention_ = Unadjusted;
            } else {
                result.terminationDateConvention_ = convention_;
            }
            if (result.nextToLastDate_>=truncationDate)
                result.nextToLastDate_ = Date();
            if (result.firstDate_>=truncationDate)
                result.firstDate_ = Date();
        }
        return result;
    }
Member Data Documentation
Calendar QuantLib::Schedule::calendar_ [private]
Definition at line 94 of file schedule.hpp.
Referenced by calendar(), and Schedule().
BusinessDayConvention QuantLib::Schedule::convention_ [private]
Definition at line 95 of file schedule.hpp.
Referenced by businessDayConvention(), and until().
std::vector<Date> QuantLib::Schedule::dates_ [private]
Definition at line 99 of file schedule.hpp.
Referenced by at(), begin(), date(), dates(), empty(), end(), endDate(), QuantLib::IterativeBootstrap< Curve >::initialize(), lower_bound(), nextDate(), operator[](), previousDate(), Schedule(), size(), startDate(), and until().
bool QuantLib::Schedule::endOfMonth_ [private]
Definition at line 97 of file schedule.hpp.
Referenced by endOfMonth().
Date QuantLib::Schedule::firstDate_ [private]
Definition at line 98 of file schedule.hpp.
Referenced by Schedule(), and until().
bool QuantLib::Schedule::fullInterface_ [private]
Definition at line 92 of file schedule.hpp.
Referenced by endOfMonth(), isRegular(), rule(), tenor(), and terminationDateBusinessDayConvention().
std::vector<bool> QuantLib::Schedule::isRegular_ [private]
Definition at line 100 of file schedule.hpp.
Referenced by isRegular(), Schedule(), and until().
Date QuantLib::Schedule::nextToLastDate_ [private]
Definition at line 98 of file schedule.hpp.
Referenced by Schedule(), and until().
DateGeneration::Rule QuantLib::Schedule::rule_ [private]
Definition at line 96 of file schedule.hpp.
Referenced by rule(), and Schedule().
Period QuantLib::Schedule::tenor_ [private]
Definition at line 93 of file schedule.hpp.
Referenced by Schedule(), and tenor().
BusinessDayConvention QuantLib::Schedule::terminationDateConvention_ [private]
Definition at line 95 of file schedule.hpp.
Referenced by terminationDateBusinessDayConvention(), and until().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/time/schedule.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/time/schedule.cpp