QuantLib: QuantLib::ZeroCouponBond Class Reference
QuantLib::ZeroCouponBond Class Reference
zero-coupon bond
#include <zerocouponbond.hpp>
Public Member Functions
ZeroCouponBond (Natural settlementDays, const Calendar &calendar, Real faceAmount, const Date &maturityDate, BusinessDayConvention paymentConvention=Following, Real redemption=100.0, const Date &issueDate=Date())
Detailed Description
zero-coupon bond
Test:
calculations are tested by checking results against cached values.
Definition at line 38 of file zerocouponbond.hpp.
Constructor & Destructor Documentation
QuantLib::ZeroCouponBond::ZeroCouponBond (Natural settlementDays, const Calendar & calendar, Real faceAmount, const Date & maturityDate, BusinessDayConvention paymentConvention = Following, Real redemption = 100.0, const Date & issueDate = Date())
Definition at line 26 of file zerocouponbond.cpp.
References QuantLib::Calendar::adjust(), QuantLib::Bond::calendar_, QuantLib::Bond::maturityDate(), QuantLib::Bond::maturityDate_, and QuantLib::Bond::setSingleRedemption().
    : Bond(settlementDays, calendar, issueDate) {
        maturityDate_ = maturityDate;
        Date redemptionDate = calendar_.adjust(maturityDate,
                                               paymentConvention);
        setSingleRedemption(faceAmount, redemption, redemptionDate);
    }
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/bonds/zerocouponbond.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/bonds/zerocouponbond.cpp