QuantLib: QuantLib::anonymous_namespace{cashflows.cpp}::IrrFinder Class Reference
QuantLib::anonymous_namespace{cashflows.cpp}::IrrFinder Class Reference
Public Member Functions
IrrFinder (const Leg &leg, Real npv, const DayCounter &dayCounter, Compounding comp, Frequency freq, bool includeSettlementDateFlows, Date settlementDate, Date npvDate)
Real operator() (Rate y) const
Real derivative (Rate y) const
Private Member Functions
void checkSign () const
Private Attributes
const Leg & leg_
Real npv_
DayCounter dayCounter_
Compounding compounding_
Frequency frequency_
bool includeSettlementDateFlows_
Date settlementDate_
Date npvDate_
Detailed Description
Definition at line 651 of file cashflows.cpp.
Constructor & Destructor Documentation
QuantLib::anonymous_namespace{cashflows.cpp}::IrrFinder::IrrFinder (const Leg & leg, Real npv, const DayCounter & dayCounter, Compounding comp, Frequency freq, bool includeSettlementDateFlows, Date settlementDate, Date npvDate) [inline]
Definition at line 653 of file cashflows.cpp.
References QuantLib::Settings::evaluationDate(), QuantLib::Singleton< Settings >::instance(), and QL_REQUIRE.
            : leg_(leg), npv_(npv),
              dayCounter_(dayCounter), compounding_(comp), frequency_(freq),
              includeSettlementDateFlows_(includeSettlementDateFlows),
              settlementDate_(settlementDate),
              npvDate_(npvDate) {
                QL_REQUIRE(!leg.empty(), "empty leg");
            if (settlementDate == Date())
                settlementDate = Settings::instance().evaluationDate();
                if (npvDate == Date())
                    npvDate = settlementDate;
                checkSign();
            }
Member Function Documentation
void QuantLib::anonymous_namespace{cashflows.cpp}::IrrFinder::checkSign () const [inline, private]
Definition at line 691 of file cashflows.cpp.
References QL_REQUIRE, and QuantLib::anonymous_namespace{cashflows.cpp}::sign().
{
                // depending on the sign of the market price, check that cash
                // flows of the opposite sign have been specified (otherwise
                // IRR is nonsensical.)
                Integer lastSign = sign(-npv_),
                        signChanges = 0;
                for (Size i = 0; i < leg_.size(); ++i) {
                    if (!leg_[i]->hasOccurred(settlementDate_,
                                              includeSettlementDateFlows_)) {
                        Integer thisSign = sign(leg_[i]->amount());
                        if (lastSign * thisSign < 0) // sign change
                            signChanges++;
                        if (thisSign != 0)
                            lastSign = thisSign;
                    }
                }
                QL_REQUIRE(signChanges > 0,
                           "the given cash flows cannot result in the given market "
                           "price due to their sign");
                /* The following is commented out due to the lack of a QL_WARN macro
                if (signChanges > 1) {    // Danger of non-unique solution
                                          // Check the aggregate cash flows (Norstrom)
                    Real aggregateCashFlow = npv;
                    signChanges = 0;
                    for (Size i = 0; i < leg.size(); ++i) {
                        Real nextAggregateCashFlow =
                            aggregateCashFlow + leg[i]->amount();
                        if (aggregateCashFlow * nextAggregateCashFlow < 0.0)
                            signChanges++;
                        aggregateCashFlow = nextAggregateCashFlow;
                    }
                    if (signChanges > 1)
                        QL_WARN( "danger of non-unique solution");
                };
                */
            }
Real QuantLib::anonymous_namespace{cashflows.cpp}::IrrFinder::derivative (Rate y) const [inline]
Definition at line 684 of file cashflows.cpp.
References anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::dayCounter_, and QuantLib::anonymous_namespace{cashflows.cpp}::modifiedDuration().
{
                InterestRate yield(y, dayCounter_, compounding_, frequency_);
                return modifiedDuration(leg_, yield,
                                        includeSettlementDateFlows_,
                                        settlementDate_, npvDate_);
            }
Real QuantLib::anonymous_namespace{cashflows.cpp}::IrrFinder::operator() (Rate y) const [inline]
Definition at line 677 of file cashflows.cpp.
References anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::dayCounter_, and QuantLib::CashFlows::npv().
{
                InterestRate yield(y, dayCounter_, compounding_, frequency_);
                Real NPV = CashFlows::npv(leg_, yield,
                                          includeSettlementDateFlows_,
                                          settlementDate_, npvDate_);
                return npv_ - NPV;
            }
Member Data Documentation
Compounding QuantLib::anonymous_namespace{cashflows.cpp}::IrrFinder::compounding_ [private]
Definition at line 735 of file cashflows.cpp.
DayCounter QuantLib::anonymous_namespace{cashflows.cpp}::IrrFinder::dayCounter_ [private]
Definition at line 734 of file cashflows.cpp.
Frequency QuantLib::anonymous_namespace{cashflows.cpp}::IrrFinder::frequency_ [private]
Definition at line 736 of file cashflows.cpp.
bool QuantLib::anonymous_namespace{cashflows.cpp}::IrrFinder::includeSettlementDateFlows_ [private]
Definition at line 737 of file cashflows.cpp.
const Leg& QuantLib::anonymous_namespace{cashflows.cpp}::IrrFinder::leg_ [private]
Definition at line 732 of file cashflows.cpp.
Real QuantLib::anonymous_namespace{cashflows.cpp}::IrrFinder::npv_ [private]
Definition at line 733 of file cashflows.cpp.
Date QuantLib::anonymous_namespace{cashflows.cpp}::IrrFinder::npvDate_ [private]
Definition at line 738 of file cashflows.cpp.
Date QuantLib::anonymous_namespace{cashflows.cpp}::IrrFinder::settlementDate_ [private]
Definition at line 738 of file cashflows.cpp.
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/cashflows.cpp