QuantLib: QuantLib::AssetSwapHelper Class Reference
QuantLib::AssetSwapHelper Class Reference
#include <riskyassetswap.hpp>
Public Member Functions
AssetSwapHelper (const Handle< Quote > &spread, const Period &tenor, Natural settlementDays, const Calendar &calendar, const Period &fixedPeriod, BusinessDayConvention fixedConvention, const DayCounter &fixedDayCount, const Period &floatPeriod, BusinessDayConvention floatConvention, const DayCounter &floatDayCount, Real recoveryRate, const RelinkableHandle< YieldTermStructure > &yieldTS, const Period &integrationStepSize=Period())
Real impliedQuote () const
void setTermStructure (DefaultProbabilityTermStructure *)
Private Member Functions
void update ()
void initializeDates ()
Private Attributes
Period tenor_
Natural settlementDays_
Calendar calendar_
BusinessDayConvention fixedConvention_
Period fixedPeriod_
DayCounter fixedDayCount_
BusinessDayConvention floatConvention_
Period floatPeriod_
DayCounter floatDayCount_
Real recoveryRate_
RelinkableHandle
< YieldTermStructure > yieldTS_
Period integrationStepSize_
Date evaluationDate_
boost::shared_ptr< RiskyAssetSwap > asw_
RelinkableHandle
< DefaultProbabilityTermStructure > probability_
Detailed Description
Definition at line 89 of file riskyassetswap.hpp.
Constructor & Destructor Documentation
QuantLib::AssetSwapHelper::AssetSwapHelper (const Handle< Quote > & spread, const Period & tenor, Natural settlementDays, const Calendar & calendar, const Period & fixedPeriod, BusinessDayConvention fixedConvention, const DayCounter & fixedDayCount, const Period & floatPeriod, BusinessDayConvention floatConvention, const DayCounter & floatDayCount, Real recoveryRate, const RelinkableHandle< YieldTermStructure > & yieldTS, const Period & integrationStepSize = Period())
Definition at line 182 of file riskyassetswap.cpp.
References initializeDates(), QuantLib::Singleton< Settings >::instance(), and QuantLib::Observer::registerWith().
    : DefaultProbabilityHelper(spread),
      tenor_(tenor), settlementDays_(settlementDays), calendar_(calendar),
      fixedConvention_(fixedConvention),
      fixedPeriod_(fixedPeriod), fixedDayCount_(fixedDayCount),
      floatConvention_(floatConvention),
      floatPeriod_(floatPeriod), floatDayCount_(floatDayCount),
      recoveryRate_(recoveryRate), yieldTS_(yieldTS),
      integrationStepSize_(integrationStepSize) {
        initializeDates();
        registerWith(Settings::instance().evaluationDate());
        registerWith(yieldTS);
    }
Member Function Documentation
Real QuantLib::AssetSwapHelper::impliedQuote () const [virtual]
Implements QuantLib::BootstrapHelper< TS >.
Definition at line 211 of file riskyassetswap.cpp.
References asw_, QuantLib::Handle< T >::empty(), probability_, and QL_REQUIRE.
{
        QL_REQUIRE(!probability_.empty(),
                   "default term structure not set");
        // we didn't register as observers - force calculation
        asw_->recalculate();
        return asw_->fairSpread();
    }
void QuantLib::AssetSwapHelper::initializeDates () [private]
Definition at line 241 of file riskyassetswap.cpp.
References QuantLib::Calendar::adjust(), QuantLib::Calendar::advance(), asw_, calendar_, QuantLib::Days, QuantLib::BootstrapHelper< TS >::earliestDate_, QuantLib::Settings::evaluationDate(), evaluationDate_, fixedConvention_, fixedDayCount_, fixedPeriod_, floatConvention_, floatDayCount_, floatPeriod_, QuantLib::DateGeneration::Forward, QuantLib::Singleton< Settings >::instance(), QuantLib::BootstrapHelper< TS >::latestDate_, probability_, recoveryRate_, settlementDays_, tenor_, and yieldTS_.
Referenced by AssetSwapHelper(), setTermStructure(), and update().
{
        evaluationDate_ = Settings::instance().evaluationDate();
        earliestDate_ = calendar_.advance (evaluationDate_,
                                           settlementDays_, Days);
        Date maturity = earliestDate_ + tenor_;
        latestDate_ = calendar_.adjust (maturity, fixedConvention_);
        Schedule fixedSchedule(earliestDate_, maturity,
                               fixedPeriod_, calendar_,
                               fixedConvention_, fixedConvention_,
                               DateGeneration::Forward, false);
        Schedule floatSchedule(earliestDate_, maturity,
                               floatPeriod_, calendar_,
                               floatConvention_, floatConvention_,
                               DateGeneration::Forward, false);
        asw_ = boost::shared_ptr<RiskyAssetSwap>(
                                      new RiskyAssetSwap(true,
                                                         100.0,
                                                         fixedSchedule,
                                                         floatSchedule,
                                                         fixedDayCount_,
                                                         floatDayCount_,
                                                         0.01,
                                                         recoveryRate_,
                                                         yieldTS_,
                                                         probability_));
    }
void QuantLib::AssetSwapHelper::setTermStructure (DefaultProbabilityTermStructure * ts)
Definition at line 223 of file riskyassetswap.cpp.
References initializeDates(), QuantLib::RelinkableHandle< T >::linkTo(), QuantLib::anonymous_namespace{riskyassetswap.cpp}::no_deletion(), and probability_.
{
        DefaultProbabilityHelper::setTermStructure(ts);
        probability_.linkTo(
            boost::shared_ptr<DefaultProbabilityTermStructure>(ts, no_deletion),
            false);
        initializeDates();
    }
void QuantLib::AssetSwapHelper::update () [private, virtual]
This method must be implemented in derived classes. An instance of Observer does not call this method directly: instead, it will be called by the observables the instance registered with when they need to notify any changes.
Reimplemented from QuantLib::BootstrapHelper< TS >.
Definition at line 234 of file riskyassetswap.cpp.
References evaluationDate_, initializeDates(), and QuantLib::Singleton< Settings >::instance().
{
        if (evaluationDate_ != Settings::instance().evaluationDate())
            initializeDates();
        DefaultProbabilityHelper::update();
    }
Member Data Documentation
boost::shared_ptr<RiskyAssetSwap> QuantLib::AssetSwapHelper::asw_ [private]
Definition at line 125 of file riskyassetswap.hpp.
Referenced by impliedQuote(), and initializeDates().
Calendar QuantLib::AssetSwapHelper::calendar_ [private]
Definition at line 113 of file riskyassetswap.hpp.
Referenced by initializeDates().
Date QuantLib::AssetSwapHelper::evaluationDate_ [private]
Definition at line 124 of file riskyassetswap.hpp.
Referenced by initializeDates(), and update().
BusinessDayConvention QuantLib::AssetSwapHelper::fixedConvention_ [private]
Definition at line 114 of file riskyassetswap.hpp.
Referenced by initializeDates().
DayCounter QuantLib::AssetSwapHelper::fixedDayCount_ [private]
Definition at line 116 of file riskyassetswap.hpp.
Referenced by initializeDates().
Period QuantLib::AssetSwapHelper::fixedPeriod_ [private]
Definition at line 115 of file riskyassetswap.hpp.
Referenced by initializeDates().
BusinessDayConvention QuantLib::AssetSwapHelper::floatConvention_ [private]
Definition at line 117 of file riskyassetswap.hpp.
Referenced by initializeDates().
DayCounter QuantLib::AssetSwapHelper::floatDayCount_ [private]
Definition at line 119 of file riskyassetswap.hpp.
Referenced by initializeDates().
Period QuantLib::AssetSwapHelper::floatPeriod_ [private]
Definition at line 118 of file riskyassetswap.hpp.
Referenced by initializeDates().
Period QuantLib::AssetSwapHelper::integrationStepSize_ [private]
Definition at line 122 of file riskyassetswap.hpp.
RelinkableHandle<DefaultProbabilityTermStructure> QuantLib::AssetSwapHelper::probability_ [private]
Definition at line 126 of file riskyassetswap.hpp.
Referenced by impliedQuote(), initializeDates(), and setTermStructure().
Real QuantLib::AssetSwapHelper::recoveryRate_ [private]
Definition at line 120 of file riskyassetswap.hpp.
Referenced by initializeDates().
Natural QuantLib::AssetSwapHelper::settlementDays_ [private]
Definition at line 112 of file riskyassetswap.hpp.
Referenced by initializeDates().
Period QuantLib::AssetSwapHelper::tenor_ [private]
Definition at line 111 of file riskyassetswap.hpp.
Referenced by initializeDates().
RelinkableHandle<YieldTermStructure> QuantLib::AssetSwapHelper::yieldTS_ [private]
Definition at line 121 of file riskyassetswap.hpp.
Referenced by initializeDates().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/riskyassetswap.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/riskyassetswap.cpp