QuantLib: QuantLib::IborCoupon Class Reference
QuantLib::IborCoupon Class Reference
Coupon paying a Libor-type index
#include <iborcoupon.hpp>
Public Member Functions
IborCoupon (const Date &paymentDate, Real nominal, const Date &startDate, const Date &endDate, Natural fixingDays, const boost::shared_ptr< IborIndex > &index, Real gearing=1.0, Spread spread=0.0, const Date &refPeriodStart=Date(), const Date &refPeriodEnd=Date(), const DayCounter &dayCounter=DayCounter(), bool isInArrears=false)
Inspectors
const boost::shared_ptr
< IborIndex > & iborIndex () const
FloatingRateCoupon interface
Rate indexFixing () const
Implemented in order to manage the case of par coupon.
Visitability
virtual void accept (AcyclicVisitor &)
Private Attributes
boost::shared_ptr< IborIndex > iborIndex_
Date fixingDate_
Date fixingValueDate_
Date fixingEndDate_
Time spanningTime_
Detailed Description
Coupon paying a Libor-type index
Definition at line 37 of file iborcoupon.hpp.
Constructor & Destructor Documentation
QuantLib::IborCoupon::IborCoupon (const Date & paymentDate, Real nominal, const Date & startDate, const Date & endDate, Natural fixingDays, const boost::shared_ptr< IborIndex > & index, Real gearing = 1.0, Spread spread = 0.0, const Date & refPeriodStart = Date(), const Date & refPeriodEnd = Date(), const DayCounter & dayCounter = DayCounter(), bool isInArrears = false)
Definition at line 33 of file iborcoupon.cpp.
References QuantLib::Coupon::accrualEndDate_, QuantLib::Calendar::advance(), QuantLib::Days, QuantLib::FloatingRateCoupon::fixingDate(), fixingDate_, fixingEndDate_, fixingValueDate_, QuantLib::FloatingRateCoupon::index_, QuantLib::FloatingRateCoupon::isInArrears_, QuantLib::DayCounter::name(), QL_REQUIRE, spanningTime_, and QuantLib::DayCounter::yearFraction().
    : FloatingRateCoupon(paymentDate, nominal, startDate, endDate,
                         fixingDays, iborIndex, gearing, spread,
                         refPeriodStart, refPeriodEnd,
                         dayCounter, isInArrears),
      iborIndex_(iborIndex) {
        fixingDate_ = fixingDate();
        const Calendar& fixingCalendar = index_->fixingCalendar();
        Natural indexFixingDays = index_->fixingDays();
        fixingValueDate_ = fixingCalendar.advance(
            fixingDate_, indexFixingDays, Days);
        #ifdef QL_USE_INDEXED_COUPON
        fixingEndDate_ = index_->maturityDate(fixingValueDate_);
        #else
        if (isInArrears_)
            fixingEndDate_ = index_->maturityDate(fixingValueDate_);
        else { // par coupon approximation
            Date nextFixingDate = fixingCalendar.advance(
                accrualEndDate_, -static_cast<Integer>(fixingDays), Days);
            fixingEndDate_ = fixingCalendar.advance(
                nextFixingDate, indexFixingDays, Days);
        }
        #endif
        const DayCounter& dc = index_->dayCounter();
        spanningTime_ = dc.yearFraction(fixingValueDate_,
                                        fixingEndDate_);
        QL_REQUIRE(spanningTime_>0.0,
                   "\n cannot calculate forward rate between " <<
                   fixingValueDate_ << " and " << fixingEndDate_ <<
                   ":\n non positive time (" << spanningTime_ <<
                   ") using " << dc.name() << " daycounter");
    }
Member Function Documentation
void QuantLib::IborCoupon::accept (AcyclicVisitor & v) [virtual]
Reimplemented from QuantLib::FloatingRateCoupon.
Definition at line 120 of file iborcoupon.cpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Visitor< T >::visit().
{
        Visitor<IborCoupon>* v1 =
            dynamic_cast<Visitor<IborCoupon>*>(&v);
        if (v1 != 0)
            v1->visit(*this);
        else
            FloatingRateCoupon::accept(v);
    }
const boost::shared_ptr<IborIndex>& QuantLib::IborCoupon::iborIndex () const [inline]
Definition at line 53 of file iborcoupon.hpp.
References iborIndex_.
{
            return iborIndex_;
        }
Rate QuantLib::IborCoupon::indexFixing () const [virtual]
Implemented in order to manage the case of par coupon.
Reimplemented from QuantLib::FloatingRateCoupon.
Definition at line 82 of file iborcoupon.cpp.
References QuantLib::Settings::evaluationDate(), fixingDate_, fixingEndDate_, fixingValueDate_, iborIndex_, QuantLib::FloatingRateCoupon::index_, QuantLib::Singleton< Settings >::instance(), QL_REQUIRE, and spanningTime_.
{
        /* instead of just returning index_->fixing(fixingValueDate_)
           its logic is duplicated here using a specialized iborIndex
           forecastFixing overload which
           1) allows to save date/time recalculations, and
           2) takes into account par coupon needs
        */
        Date today = Settings::instance().evaluationDate();
        if (fixingDate_>today)
            return iborIndex_->forecastFixing(fixingValueDate_,
                                              fixingEndDate_,
                                              spanningTime_);
        if (fixingDate_<today ||
            Settings::instance().enforcesTodaysHistoricFixings()) {
            // do not catch exceptions
            Rate result = index_->pastFixing(fixingDate_);
            QL_REQUIRE(result != Null<Real>(),
                       "Missing " << index_->name() << " fixing for " << fixingDate_);
            return result;
        }
        try {
            Rate result = index_->pastFixing(fixingDate_);
            if (result!=Null<Real>())
                return result;
            else
                ;   // fall through and forecast
        } catch (Error&) {
                ;   // fall through and forecast
        }
        return iborIndex_->forecastFixing(fixingValueDate_,
                                          fixingEndDate_,
                                          spanningTime_);
    }
Member Data Documentation
Date QuantLib::IborCoupon::fixingDate_ [private]
Definition at line 68 of file iborcoupon.hpp.
Referenced by IborCoupon(), and indexFixing().
Date QuantLib::IborCoupon::fixingEndDate_ [private]
Definition at line 68 of file iborcoupon.hpp.
Referenced by IborCoupon(), and indexFixing().
Date QuantLib::IborCoupon::fixingValueDate_ [private]
Definition at line 68 of file iborcoupon.hpp.
Referenced by IborCoupon(), and indexFixing().
boost::shared_ptr<IborIndex> QuantLib::IborCoupon::iborIndex_ [private]
Definition at line 67 of file iborcoupon.hpp.
Referenced by iborIndex(), and indexFixing().
Time QuantLib::IborCoupon::spanningTime_ [private]
Definition at line 69 of file iborcoupon.hpp.
Referenced by IborCoupon(), and indexFixing().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/iborcoupon.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/iborcoupon.cpp