QuantLib: QuantLib::BlackSwaptionEngine Class Reference
QuantLib::BlackSwaptionEngine Class Reference
Black-formula swaption engine.
#include <blackswaptionengine.hpp>
Public Member Functions
BlackSwaptionEngine (const Handle< YieldTermStructure > &discountCurve, Volatility vol, const DayCounter &dc=Actual365Fixed())
BlackSwaptionEngine (const Handle< YieldTermStructure > &discountCurve, const Handle< Quote > &vol, const DayCounter &dc=Actual365Fixed())
BlackSwaptionEngine (const Handle< YieldTermStructure > &discountCurve, const Handle< SwaptionVolatilityStructure > &vol)
void calculate () const
Handle< YieldTermStructure > termStructure ()
Handle
< SwaptionVolatilityStructure > volatility ()
Private Attributes
Handle< YieldTermStructure > discountCurve_
Handle
< SwaptionVolatilityStructure > vol_
Detailed Description
Black-formula swaption engine.
Warning:
The engine assumes that the exercise date equals the start date of the passed swap.
Definition at line 42 of file blackswaptionengine.hpp.
Constructor & Destructor Documentation
QuantLib::BlackSwaptionEngine::BlackSwaptionEngine (const Handle< YieldTermStructure > & discountCurve, Volatility vol, const DayCounter & dc = Actual365Fixed())
Definition at line 36 of file blackswaptionengine.cpp.
References discountCurve_, and QuantLib::Observer::registerWith().
    : discountCurve_(discountCurve),
      vol_(boost::shared_ptr<SwaptionVolatilityStructure>(new
          ConstantSwaptionVolatility(0, NullCalendar(), Following, vol, dc))) {
        registerWith(discountCurve_);
    }
QuantLib::BlackSwaptionEngine::BlackSwaptionEngine (const Handle< YieldTermStructure > & discountCurve, const Handle< Quote > & vol, const DayCounter & dc = Actual365Fixed())
Definition at line 46 of file blackswaptionengine.cpp.
References discountCurve_, QuantLib::Observer::registerWith(), and vol_.
    : discountCurve_(discountCurve),
      vol_(boost::shared_ptr<SwaptionVolatilityStructure>(new
          ConstantSwaptionVolatility(0, NullCalendar(), Following, vol, dc))) {
        registerWith(discountCurve_);
        registerWith(vol_);
    }
QuantLib::BlackSwaptionEngine::BlackSwaptionEngine (const Handle< YieldTermStructure > & discountCurve, const Handle< SwaptionVolatilityStructure > & vol)
Definition at line 57 of file blackswaptionengine.cpp.
References discountCurve_, QuantLib::Observer::registerWith(), and vol_.
    : discountCurve_(discountCurve),
      vol_(volatility) {
        registerWith(discountCurve_);
        registerWith(vol_);
    }
Member Function Documentation
void QuantLib::BlackSwaptionEngine::calculate () const [virtual]
Implements QuantLib::PricingEngine.
Definition at line 66 of file blackswaptionengine.cpp.
References QuantLib::Instrument::results::additionalResults, QuantLib::Annual, QuantLib::GenericEngine< Swaption::arguments, Swaption::results >::arguments_, QuantLib::blackFormula(), QuantLib::blackFormulaStdDevDerivative(), QuantLib::CashFlows::bps(), QuantLib::Option::Call, QuantLib::Settlement::Cash, QuantLib::Compounded, discountCurve_, QuantLib::Option::arguments::exercise, QuantLib::VanillaSwap::fairRate(), QuantLib::VanillaSwap::fixedLeg(), QuantLib::VanillaSwap::fixedLegBPS(), QuantLib::VanillaSwap::fixedRate(), QuantLib::VanillaSwap::floatingLegBPS(), QuantLib::VanillaSwap::arguments::floatingPayDates, QuantLib::VanillaSwap::Payer, QuantLib::Settlement::Physical, QuantLib::Option::Put, QL_FAIL, QuantLib::GenericEngine< Swaption::arguments, Swaption::results >::results_, QuantLib::Instrument::setPricingEngine(), QuantLib::Swaption::arguments::settlementType, QuantLib::VanillaSwap::spread(), QuantLib::Swaption::arguments::swap, QuantLib::swap(), QuantLib::VanillaSwap::arguments::type, QuantLib::Instrument::results::value, and vol_.
{
        static const Spread basisPoint = 1.0e-4;
        Date exerciseDate = arguments_.exercise->date(0);
        // the part of the swap preceding exerciseDate should be truncated
        // to avoid taking into account unwanted cashflows
        VanillaSwap swap = *arguments_.swap;
        Rate strike = swap.fixedRate();
        // using the discounting curve
        // swap.iborIndex() might be using a different forwarding curve
        swap.setPricingEngine(boost::shared_ptr<PricingEngine>(new
            DiscountingSwapEngine(discountCurve_, false)));
        Rate atmForward = swap.fairRate();
        // Volatilities are quoted for zero-spreaded swaps.
        // Therefore, any spread on the floating leg must be removed
        // with a corresponding correction on the fixed leg.
        if (swap.spread()!=0.0) {
            Spread correction = swap.spread() *
                std::fabs(swap.floatingLegBPS()/swap.fixedLegBPS());
            strike -= correction;
            atmForward -= correction;
            results_.additionalResults["spreadCorrection"] = correction;
        } else {
            results_.additionalResults["spreadCorrection"] = 0.0;
        }
        results_.additionalResults["strike"] = strike;
        results_.additionalResults["atmForward"] = atmForward;
        // using the discounting curve
        swap.setPricingEngine(boost::shared_ptr<PricingEngine>(
                           new DiscountingSwapEngine(discountCurve_, false)));
        Real annuity;
        switch(arguments_.settlementType) {
          case Settlement::Physical: {
              annuity = std::fabs(swap.fixedLegBPS())/basisPoint;
              break;
          }
          case Settlement::Cash: {
              const Leg& fixedLeg = swap.fixedLeg();
              boost::shared_ptr<FixedRateCoupon> firstCoupon =
                  boost::dynamic_pointer_cast<FixedRateCoupon>(fixedLeg[0]);
              DayCounter dayCount = firstCoupon->dayCounter();
              Real fixedLegCashBPS =
                  CashFlows::bps(fixedLeg,
                                 InterestRate(atmForward, dayCount, Compounded, Annual),
                                 false, discountCurve_->referenceDate()) ;
              annuity = std::fabs(fixedLegCashBPS/basisPoint);
              break;
          }
          default:
            QL_FAIL("unknown settlement type");
        }
        results_.additionalResults["annuity"] = annuity;
        // the swap length calculation might be improved using the value date
        // of the exercise date
        Time swapLength =  vol_->swapLength(exerciseDate,
                                                   arguments_.floatingPayDates.back());
        results_.additionalResults["swapLength"] = swapLength;
        Real variance = vol_->blackVariance(exerciseDate,
                                                   swapLength,
                                                   strike);
        Real stdDev = std::sqrt(variance);
        results_.additionalResults["stdDev"] = stdDev;
        Option::Type w = (arguments_.type==VanillaSwap::Payer) ?
                                                Option::Call : Option::Put;
        results_.value = blackFormula(w, strike, atmForward, stdDev, annuity);
        Time exerciseTime = vol_->timeFromReference(exerciseDate);
        results_.additionalResults["vega"] = std::sqrt(exerciseTime) *
            blackFormulaStdDevDerivative(strike, atmForward, stdDev, annuity);
    }
Handle<YieldTermStructure> QuantLib::BlackSwaptionEngine::termStructure () [inline]
Definition at line 53 of file blackswaptionengine.hpp.
References discountCurve_.
{ return discountCurve_; }
Handle<SwaptionVolatilityStructure> QuantLib::BlackSwaptionEngine::volatility () [inline]
Definition at line 54 of file blackswaptionengine.hpp.
References vol_.
{ return vol_; }
Member Data Documentation
Handle<YieldTermStructure> QuantLib::BlackSwaptionEngine::discountCurve_ [private]
Definition at line 56 of file blackswaptionengine.hpp.
Referenced by BlackSwaptionEngine(), calculate(), and termStructure().
Handle<SwaptionVolatilityStructure> QuantLib::BlackSwaptionEngine::vol_ [private]
Definition at line 57 of file blackswaptionengine.hpp.
Referenced by BlackSwaptionEngine(), calculate(), and volatility().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/swaption/blackswaptionengine.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/swaption/blackswaptionengine.cpp