QuantLib: QuantLib::InterpolatedYoYInflationCurve< Interpolator > Class Template Reference
QuantLib::InterpolatedYoYInflationCurve< Interpolator > Class Template Reference
Inflation term structure based on interpolated year-on-year rates.
#include <interpolatedyoyinflationcurve.hpp>
Public Member Functions
InterpolatedYoYInflationCurve (const Date &referenceDate, const Calendar &calendar, const DayCounter &dayCounter, const Period &lag, Frequency frequency, bool indexIsInterpolated, const Handle< YieldTermStructure > &yTS, const std::vector< Date > &dates, const std::vector< Rate > &rates, const Interpolator &interpolator=Interpolator())
InflationTermStructure interface
Date baseDate () const
minimum (base) date
Date maxDate () const
the latest date for which the curve can return values
Inspectors
const std::vector< Date > & dates () const
const std::vector< Time > & times () const
const std::vector< Real > & data () const
const std::vector< Rate > & rates () const
std::vector< std::pair< Date,
Rate > > nodes () const
Protected Member Functions
InterpolatedYoYInflationCurve (const Date &referenceDate, const Calendar &calendar, const DayCounter &dayCounter, Rate baseYoYRate, const Period &lag, Frequency frequency, bool indexIsInterpolated, const Handle< YieldTermStructure > &yTS, const Interpolator &interpolator=Interpolator())
YoYInflationTermStructure interface
Rate yoyRateImpl (Time t) const
to be defined in derived classes
Protected Attributes
std::vector< Date > dates_
Detailed Description
template<class Interpolator>
class QuantLib::InterpolatedYoYInflationCurve< Interpolator >
Inflation term structure based on interpolated year-on-year rates.
Note:
The provided rates are not YY inflation-swap quotes.
Definition at line 43 of file interpolatedyoyinflationcurve.hpp.
Constructor & Destructor Documentation
template<class Interpolator > QuantLib::InterpolatedYoYInflationCurve< Interpolator >::InterpolatedYoYInflationCurve (const Date & referenceDate, const Calendar & calendar, const DayCounter & dayCounter, const Period & lag, Frequency frequency, bool indexIsInterpolated, const Handle< YieldTermStructure > & yTS, const std::vector< Date > & dates, const std::vector< Rate > & rates, const Interpolator & interpolator = Interpolator())
Definition at line 105 of file interpolatedyoyinflationcurve.hpp.
References QuantLib::close(), QuantLib::InterpolatedCurve< Interpolator >::data_, QuantLib::InterpolatedYoYInflationCurve< Interpolator >::dates_, QuantLib::InflationTermStructure::frequency(), QuantLib::inflationPeriod(), QuantLib::InterpolatedCurve< Interpolator >::interpolation_, QuantLib::InterpolatedCurve< Interpolator >::interpolator_, QuantLib::InflationTermStructure::observationLag(), QL_REQUIRE, QuantLib::TermStructure::timeFromReference(), QuantLib::InterpolatedCurve< Interpolator >::times_, and QuantLib::Interpolation::update().
    : YoYInflationTermStructure(referenceDate, calendar, dayCounter, rates[0],
                                lag, frequency, indexIsInterpolated,  yTS),
      InterpolatedCurve<Interpolator>(std::vector<Time>(), rates, interpolator),
      dates_(dates) {
        QL_REQUIRE(dates_.size()>1, "too few dates: " << dates_.size());
        // check that the data starts from the beginning,
        // i.e. referenceDate - lag, at least must be in the relevant
        // period
        std::pair<Date,Date> lim =
            inflationPeriod(yTS->referenceDate() - this->observationLag(), frequency);
        QL_REQUIRE(lim.first <= dates_[0] && dates_[0] <= lim.second,
                   "first data date is not in base period, date: " << dates_[0]
                   << " not within [" << lim.first << "," << lim.second << "]");
        QL_REQUIRE(this->data_.size() == dates_.size(),
                   "indices/dates count mismatch: "
                   << this->data_.size() << " vs " << dates_.size());
        this->times_.resize(dates_.size());
        this->times_[0] = timeFromReference(dates_[0]);
        for (Size i = 1; i < dates_.size(); i++) {
            QL_REQUIRE(dates_[i] > dates_[i-1],
                       "dates not sorted");
            // YoY inflation data may be positive or negative
            // but must be greater than -1
            QL_REQUIRE(this->data_[i] > -1.0,
                       "year-on-year inflation data < -100 %");
            // this can be negative
            this->times_[i] = timeFromReference(dates_[i]);
            QL_REQUIRE(!close(this->times_[i],this->times_[i-1]),
                       "two dates correspond to the same time "
                       "under this curve's day count convention");
        }
        this->interpolation_ =
            this->interpolator_.interpolate(this->times_.begin(),
                                            this->times_.end(),
                                            this->data_.begin());
        this->interpolation_.update();
    }
template<class Interpolator > QuantLib::InterpolatedYoYInflationCurve< Interpolator >::InterpolatedYoYInflationCurve (const Date & referenceDate, const Calendar & calendar, const DayCounter & dayCounter, Rate baseYoYRate, const Period & lag, Frequency frequency, bool indexIsInterpolated, const Handle< YieldTermStructure > & yTS, const Interpolator & interpolator = Interpolator()) [protected]
Protected version for use when descendents don't want to (or can't) provide the points for interpolation on construction.
Definition at line 163 of file interpolatedyoyinflationcurve.hpp.
    : YoYInflationTermStructure(referenceDate, calendar, dayCounter, baseYoYRate,
                                lag, frequency, indexIsInterpolated, yTS),
      InterpolatedCurve<Interpolator>(interpolator) {}
Member Function Documentation
template<class T > Date QuantLib::InterpolatedYoYInflationCurve< T >::baseDate () const [virtual]
minimum (base) date
Important in inflation since it starts before nominal reference date. Changes depending whether index is interpolated or not. When interpolated the base date is just observation lag before nominal. When not interpolated it is the beginning of the relevant period (hence it is easy to create interpolated fixings from a not-interpolated curve because interpolation, usually, of fixings is forward looking).
Implements QuantLib::InflationTermStructure.
Reimplemented in QuantLib::PiecewiseYoYInflationCurve< Interpolator, Bootstrap, Traits >.
Definition at line 178 of file interpolatedyoyinflationcurve.hpp.
{
        return dates_.front();
    }
template<class T > const std::vector< Real > & QuantLib::InterpolatedYoYInflationCurve< T >::data () const [inline]
Reimplemented in QuantLib::PiecewiseYoYInflationCurve< Interpolator, Bootstrap, Traits >.
Definition at line 213 of file interpolatedyoyinflationcurve.hpp.
{
        return this->data_;
    }
template<class T > const std::vector< Date > & QuantLib::InterpolatedYoYInflationCurve< T >::dates () const [inline]
Reimplemented in QuantLib::PiecewiseYoYInflationCurve< Interpolator, Bootstrap, Traits >.
Definition at line 201 of file interpolatedyoyinflationcurve.hpp.
{
        return dates_;
    }
template<class T > Date QuantLib::InterpolatedYoYInflationCurve< T >::maxDate () const [virtual]
the latest date for which the curve can return values
Implements QuantLib::TermStructure.
Reimplemented in QuantLib::PiecewiseYoYInflationCurve< Interpolator, Bootstrap, Traits >.
Definition at line 183 of file interpolatedyoyinflationcurve.hpp.
{
        return dates_.back();
    }
template<class T > std::vector< std::pair< Date, Rate > > QuantLib::InterpolatedYoYInflationCurve< T >::nodes () const [inline]
Reimplemented in QuantLib::PiecewiseYoYInflationCurve< Interpolator, Bootstrap, Traits >.
Definition at line 219 of file interpolatedyoyinflationcurve.hpp.
{
        std::vector<std::pair<Date,Rate> > results(dates_.size());
        for (Size i=0; i<dates_.size(); ++i)
            results[i] = std::make_pair(dates_[i],this->data_[i]);
        return results;
    }
template<class T > const std::vector< Rate > & QuantLib::InterpolatedYoYInflationCurve< T >::rates () const [inline]
Definition at line 207 of file interpolatedyoyinflationcurve.hpp.
{
        return this->data_;
    }
template<class T > const std::vector< Time > & QuantLib::InterpolatedYoYInflationCurve< T >::times () const [inline]
Reimplemented in QuantLib::PiecewiseYoYInflationCurve< Interpolator, Bootstrap, Traits >.
Definition at line 195 of file interpolatedyoyinflationcurve.hpp.
{
        return this->times_;
    }
template<class T > Rate QuantLib::InterpolatedYoYInflationCurve< T >::yoyRateImpl (Time time) const [inline, protected, virtual]
to be defined in derived classes
Implements QuantLib::YoYInflationTermStructure.
Definition at line 189 of file interpolatedyoyinflationcurve.hpp.
{
        return this->interpolation_(t, true);
    }
Member Data Documentation
template<class Interpolator > std::vector<Date> QuantLib::InterpolatedYoYInflationCurve< Interpolator >::dates_ [mutable, protected]
Definition at line 79 of file interpolatedyoyinflationcurve.hpp.
Referenced by QuantLib::InterpolatedYoYInflationCurve< Interpolator >::InterpolatedYoYInflationCurve().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/inflation/interpolatedyoyinflationcurve.hpp