QuantLib: QuantLib::EuropeanPathMultiPathPricer Class Reference
QuantLib::EuropeanPathMultiPathPricer Class Reference
#include <mcpathbasketengine.hpp>
Public Member Functions
EuropeanPathMultiPathPricer (boost::shared_ptr< PathPayoff > &payoff, const std::vector< Size > &timePositions, const std::vector< Handle< YieldTermStructure > > &forwardTermStructures, const Array &discounts)
Real operator() (const MultiPath &multiPath) const
Private Attributes
boost::shared_ptr< PathPayoff > payoff_
std::vector< Size > timePositions_
std::vector< Handle
< YieldTermStructure > > forwardTermStructures_
Array discounts_
Detailed Description
Definition at line 90 of file mcpathbasketengine.hpp.
Constructor & Destructor Documentation
QuantLib::EuropeanPathMultiPathPricer::EuropeanPathMultiPathPricer (boost::shared_ptr< PathPayoff > & payoff, const std::vector< Size > & timePositions, const std::vector< Handle< YieldTermStructure > > & forwardTermStructures, const Array & discounts)
Definition at line 24 of file mcpathbasketengine.cpp.
    :  payoff_(payoff), timePositions_(timePositions), forwardTermStructures_(forwardTermStructures), discounts_(discounts) {}
Member Function Documentation
Real QuantLib::EuropeanPathMultiPathPricer::operator() (const MultiPath & multiPath) const [virtual]
Implements QuantLib::PathPricer< MultiPath >.
Definition at line 31 of file mcpathbasketengine.cpp.
References QuantLib::MultiPath::assetNumber(), discounts_, QuantLib::DotProduct(), anonymous_namespace{swaption.cpp}::exercises, forwardTermStructures_, QuantLib::MultiPath::pathSize(), payoff_, QL_REQUIRE, and timePositions_.
{
        Size n = multiPath.pathSize();
        QL_REQUIRE(n > 0, "the path cannot be empty");
        Size numberOfAssets = multiPath.assetNumber();
        QL_REQUIRE(numberOfAssets > 0, "there must be some paths");
        const Size numberOfTimes = timePositions_.size();
        Matrix path(numberOfAssets, numberOfTimes, Null<Real>());
        for (Size i = 0; i < numberOfTimes; ++i) {
            const Size pos = timePositions_[i];
            for (Size j = 0; j < numberOfAssets; ++j)
                path[j][i] = multiPath[j][pos];
        }
        Array values(numberOfTimes, 0.0);
        // ignored
        Array exercises;
        std::vector<Array> states;
        payoff_->value(path, forwardTermStructures_, values, exercises, states);
        // in this engine we ignore early exercise
        Real discountedPayoff = DotProduct(values, discounts_);
        return discountedPayoff;
    }
Member Data Documentation
Array QuantLib::EuropeanPathMultiPathPricer::discounts_ [private]
Definition at line 101 of file mcpathbasketengine.hpp.
Referenced by operator()().
std::vector<Handle<YieldTermStructure> > QuantLib::EuropeanPathMultiPathPricer::forwardTermStructures_ [private]
Definition at line 100 of file mcpathbasketengine.hpp.
Referenced by operator()().
boost::shared_ptr<PathPayoff> QuantLib::EuropeanPathMultiPathPricer::payoff_ [private]
Definition at line 98 of file mcpathbasketengine.hpp.
Referenced by operator()().
std::vector<Size> QuantLib::EuropeanPathMultiPathPricer::timePositions_ [private]
Definition at line 99 of file mcpathbasketengine.hpp.
Referenced by operator()().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/mcbasket/mcpathbasketengine.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/mcbasket/mcpathbasketengine.cpp