QuantLib: VPPTest Class Reference
VPPTest Class Reference
#include <vpp.hpp>
Static Public Member Functions
static void testGemanRoncoroniProcess ()
static void testSimpleExtOUStorageEngine ()
static void testKlugeExtOUSpreadOption ()
static void testVPPIntrinsicValue ()
static void testVPPPricing ()
static
boost::unit_test_framework::test_suite * suite ()
Detailed Description
Definition at line 28 of file vpp.hpp.
Member Function Documentation
test_suite * VPPTest::suite () [static]
Definition at line 891 of file vpp.cpp.
References QUANTLIB_TEST_CASE, testGemanRoncoroniProcess(), testKlugeExtOUSpreadOption(), testSimpleExtOUStorageEngine(), testVPPIntrinsicValue(), and testVPPPricing().
Referenced by init_unit_test_suite().
{
    test_suite* suite = BOOST_TEST_SUITE("VPP Test");
    suite->add(QUANTLIB_TEST_CASE(&VPPTest::testGemanRoncoroniProcess));
    suite->add(QUANTLIB_TEST_CASE(&VPPTest::testSimpleExtOUStorageEngine));
    suite->add(QUANTLIB_TEST_CASE(&VPPTest::testKlugeExtOUSpreadOption));
    suite->add(QUANTLIB_TEST_CASE(&VPPTest::testVPPIntrinsicValue));
    suite->add(QUANTLIB_TEST_CASE(&VPPTest::testVPPPricing));
    return suite;
}
void VPPTest::testGemanRoncoroniProcess () [static]
Definition at line 80 of file vpp.cpp.
References anonymous_namespace{marketmodel.cpp}::a, anonymous_namespace{marketmodel.cpp}::b, anonymous_namespace{marketmodel.cpp}::beta, anonymous_namespace{marketmodel.cpp}::d, QuantLib::December, QuantLib::Settings::evaluationDate(), anonymous_namespace{interpolations.cpp}::f(), QuantLib::flatRate(), QuantLib::Singleton< Settings >::instance(), QuantLib::GenericPseudoRandom< URNG, IC >::make_sequence_generator(), QuantLib::MultiPathGenerator< GSG >::next(), QuantLib::TimeGrid::size(), anonymous_namespace{quantlibbenchmark.cpp}::t, and QuantLib::ExtendedOrnsteinUhlenbeckProcess::Trapezodial.
Referenced by suite().
{
    BOOST_MESSAGE("Testing Geman Roncoroni process...");
    /* Example induced by H. Geman, A. Roncoroni,
       "Understanding the Fine Structure of Electricity Prices",
       http://papers.ssrn.com/sol3/papers.cfm?abstract_id=638322
       Results are verified against the authors MatLab-Code.
       http://semeq.unipmn.it/files/Ch19_spark_spread.zip
    */
    SavedSettings backup;
    const Date today = Date(18, December, 2011);
    Settings::instance().evaluationDate() = today;
    const DayCounter dc = ActualActual();
    boost::shared_ptr<YieldTermStructure> rTS = flatRate(today, 0.03, dc);
    const Real x0     = 3.3;
    const Real beta   = 0.05;
    const Real alpha  = 3.1;
    const Real gamma  = -0.09;
    const Real delta  = 0.07;
    const Real eps    = -0.40;
    const Real zeta   = -0.40;
    const Real d      = 1.6;
    const Real k      = 1.0;
    const Real tau    = 0.5;
    const Real sig2   = 10.0;
    const Real a      =-7.0;
    const Real b      =-0.3;
    const Real theta1 = 35.0;
    const Real theta2 = 9.0;
    const Real theta3 = 0.10;
    const Real psi    = 1.9;
    boost::shared_ptr<GemanRoncoroniProcess> grProcess(
                new GemanRoncoroniProcess(x0, alpha, beta, gamma, delta,
                                          eps, zeta, d, k, tau, sig2, a, b,
                                          theta1, theta2, theta3, psi));
    const Real speed     = 5.0;
    const Volatility vol = std::sqrt(1.4);
    const Real betaG     = 0.08;
    const Real alphaG    = 1.0;
    const Real x0G       = 1.1;
    boost::function<Real (Real)> f = alphaG + betaG*boost::lambda::_1;
    boost::shared_ptr<StochasticProcess1D> eouProcess(
        new ExtendedOrnsteinUhlenbeckProcess(speed, vol, x0G, f,
                           ExtendedOrnsteinUhlenbeckProcess::Trapezodial));
    std::vector<boost::shared_ptr<StochasticProcess1D> > processes;
    processes.push_back(grProcess);
    processes.push_back(eouProcess);
    Matrix correlation(2, 2, 1.0);
    correlation[0][1] = correlation[1][0] = 0.25;
    boost::shared_ptr<StochasticProcess> pArray(
                           new StochasticProcessArray(processes, correlation));
    const Time T = 10.0;
    const Size stepsPerYear = 250;
    const Size steps = Size(T*Real(stepsPerYear));
    TimeGrid grid(T, steps);
    typedef PseudoRandom::rsg_type rsg_type;
    typedef MultiPathGenerator<rsg_type>::sample_type sample_type;
    rsg_type rsg = PseudoRandom::make_sequence_generator(
                               pArray->size()*(grid.size()-1), BigNatural(421));
    GeneralStatistics npv, onTime;
    MultiPathGenerator<rsg_type> generator(pArray, grid, rsg, false);
    const Real heatRate = 8.0;
    const Size nrTrails = 250;
    for (Size n=0; n < nrTrails; ++n) {
        Real plantValue = 0.0;
        sample_type path = generator.next();
        for (Size i=1; i <= steps; ++i) {
            const Time t = Real(i)/stepsPerYear;
            const DiscountFactor df = rTS->discount(t);
            const Real gasPrice         = std::exp(path.value[1][i]);
            const Real electricityPrice = std::exp(path.value[0][i]);
            const Real sparkSpread = electricityPrice - heatRate*gasPrice;
            plantValue += std::max(0.0, sparkSpread)*df;
            onTime.add((sparkSpread > 0.0) ? 1.0 : 0.0);
        }
        npv.add(plantValue);
    }
    const Real expectedNPV = 12500;
    const Real calculatedNPV = npv.mean();
    const Real errorEstimateNPV = npv.errorEstimate();
    if (std::fabs(calculatedNPV - expectedNPV) > 3.0*errorEstimateNPV) {
        BOOST_ERROR("Failed to reproduce cached price with MC engine"
                    << "\n    calculated: " << calculatedNPV
                    << "\n    expected:   " << expectedNPV
                    << " +/- " << errorEstimateNPV);
    }
    const Real expectedOnTime = 0.43;
    const Real calculatedOnTime = onTime.mean();
    const Real errorEstimateOnTime
        = std::sqrt(calculatedOnTime*(1-calculatedOnTime))/nrTrails;
    if (std::fabs(calculatedOnTime - expectedOnTime)>3.0*errorEstimateOnTime) {
        BOOST_ERROR("Failed to reproduce cached price with MC engine"
                    << "\n    calculated: " << calculatedNPV
                    << "\n    expected:   " << expectedNPV
                    << " +/- " << errorEstimateNPV);
    }
}
void VPPTest::testKlugeExtOUSpreadOption () [static]
Definition at line 253 of file vpp.cpp.
References QuantLib::GeneralStatistics::add(), QuantLib::Array::back(), QuantLib::Option::Call, anonymous_namespace{swingoption.cpp}::createKlugeProcess(), anonymous_namespace{marketmodel.cpp}::dayCounter, QuantLib::December, QuantLib::GeneralStatistics::errorEstimate(), QuantLib::Settings::evaluationDate(), QuantLib::Exp(), anonymous_namespace{interpolations.cpp}::f(), QuantLib::flatRate(), QuantLib::Singleton< Settings >::instance(), QuantLib::GenericPseudoRandom< URNG, IC >::make_sequence_generator(), QuantLib::GeneralStatistics::mean(), QuantLib::MultiPathGenerator< GSG >::next(), QuantLib::Instrument::NPV(), QuantLib::Instrument::setPricingEngine(), QuantLib::TimeGrid::size(), QuantLib::ExtendedOrnsteinUhlenbeckProcess::Trapezodial, QuantLib::DayCounter::yearFraction(), and QuantLib::Years.
Referenced by suite().
{
    BOOST_MESSAGE("Testing Simple Kluge ext-Ornstein-Uhlenbeck spread option...");
    SavedSettings backup;
    Date settlementDate = Date(18, December, 2011);
    Settings::instance().evaluationDate() = settlementDate;
    DayCounter dayCounter = ActualActual();
    Date maturityDate = settlementDate + Period(1, Years);
    Time maturity = dayCounter.yearFraction(settlementDate, maturityDate);
    const Real speed     = 1.0;
    const Volatility vol = std::sqrt(1.4);
    const Real betaG     = 0.0;
    const Real alphaG    = 3.0;
    const Real x0G       = 3.0;
    const Rate irRate      = 0.0;
    const Real heatRate    = 2.0;
    const Real rho         = 0.5;
    boost::shared_ptr<ExtOUWithJumpsProcess>
                                           klugeProcess = createKlugeProcess();
    boost::function<Real (Real)> f = alphaG + betaG*boost::lambda::_1;
    boost::shared_ptr<ExtendedOrnsteinUhlenbeckProcess> extOUProcess(
        new ExtendedOrnsteinUhlenbeckProcess(speed, vol, x0G, f,
                           ExtendedOrnsteinUhlenbeckProcess::Trapezodial));
    boost::shared_ptr<YieldTermStructure> rTS(
                                flatRate(settlementDate, irRate, dayCounter));
    boost::shared_ptr<KlugeExtOUProcess> klugeOUProcess(
                    new KlugeExtOUProcess(rho, klugeProcess, extOUProcess));
    boost::shared_ptr<Payoff> payoff(new PlainVanillaPayoff(Option::Call, 0.0));
    Array spreadFactors(2);
    spreadFactors[0] = 1.0; spreadFactors[1] = -heatRate;
    boost::shared_ptr<BasketPayoff> basketPayoff(
                               new AverageBasketPayoff(payoff, spreadFactors));
    boost::shared_ptr<Exercise> exercise(new EuropeanExercise(maturityDate));
    BasketOption option(basketPayoff, exercise);
    option.setPricingEngine(boost::shared_ptr<PricingEngine>(
        new FdKlugeExtOUSpreadEngine(klugeOUProcess, rTS,
                                     5, 200, 50, 20)));
    TimeGrid grid(maturity, 50);
    typedef PseudoRandom::rsg_type rsg_type;
    typedef MultiPathGenerator<rsg_type>::sample_type sample_type;
    rsg_type rsg = PseudoRandom::make_sequence_generator(
                           klugeOUProcess->factors()*(grid.size()-1), 1234ul);
    MultiPathGenerator<rsg_type> generator(klugeOUProcess, grid, rsg, false);
    GeneralStatistics npv;
    const Size nTrails = 20000;
    for (Size i=0; i < nTrails; ++i) {
        const sample_type path = generator.next();
        Array p(2);
        p[0] = path.value[0].back() + path.value[1].back();
        p[1] = path.value[2].back();
        npv.add((*basketPayoff)(Exp(p)));
    }
    const Real calculated = option.NPV();
    const Real expectedMC = npv.mean();
    const Real mcError = npv.errorEstimate();
    if (std::fabs(expectedMC - calculated) > 3*mcError) {
            BOOST_ERROR("Failed to reproduce referenc values"
                       << "\n    calculated:   " << calculated
                       << "\n    expected(MC): " << expectedMC
                       << "\n    mc error    : " << mcError);
    }
}
void VPPTest::testSimpleExtOUStorageEngine () [static]
Definition at line 205 of file vpp.cpp.
References anonymous_namespace{marketmodel.cpp}::dayCounter, QuantLib::Days, QuantLib::December, QuantLib::Settings::evaluationDate(), QuantLib::flatRate(), QuantLib::Singleton< Settings >::instance(), QuantLib::Months, QuantLib::Instrument::NPV(), QuantLib::Instrument::setPricingEngine(), and QuantLib::io::volatility().
Referenced by suite().
{
    BOOST_MESSAGE("Testing Simple Storage option based on ext. OU model...");
    SavedSettings backup;
    Date settlementDate = Date(18, December, 2011);
    Settings::instance().evaluationDate() = settlementDate;
    DayCounter dayCounter = ActualActual();
    Date maturityDate = settlementDate + Period(12, Months);
    std::vector<Date> exerciseDates(1, settlementDate+Period(1, Days));
    while (exerciseDates.back() < maturityDate) {
        exerciseDates.push_back(exerciseDates.back()+Period(1, Days));
    }
    boost::shared_ptr<BermudanExercise> bermudanExercise(
                                        new BermudanExercise(exerciseDates));
    const Real x0 = 3.0;
    const Real speed = 1.0;
    const Real volatility = 0.5;
    const Rate irRate = 0.1;
    boost::shared_ptr<ExtendedOrnsteinUhlenbeckProcess> ouProcess(
        new ExtendedOrnsteinUhlenbeckProcess(speed, volatility, x0,
                                             constant<Real, Real>(x0)));
    boost::shared_ptr<YieldTermStructure> rTS(
                                flatRate(settlementDate, irRate, dayCounter));
    boost::shared_ptr<PricingEngine> storageEngine(
               new FdSimpleExtOUStorageEngine(ouProcess, rTS, 1, 25));
    VanillaStorageOption storageOption(bermudanExercise, 50, 0, 1);
    storageOption.setPricingEngine(storageEngine);
    const Real expected = 69.5755;
    const Real calculated = storageOption.NPV();
    if (std::fabs(expected - calculated) > 5e-2) {
        BOOST_ERROR("Failed to reproduce cached values" <<
                    "\n calculated: " << calculated <<
                    "\n   expected: " << expected);
    }
}
void VPPTest::testVPPIntrinsicValue () [static]
Definition at line 411 of file vpp.cpp.
References QuantLib::Array::begin(), QuantLib::Array::end(), anonymous_namespace{vpp.cpp}::gasPrices, and LENGTH.
Referenced by suite().
{
    BOOST_MESSAGE("Testing VPP step condition...");
    SavedSettings backup;
    // vpp parameters
    const Real pMin           = 8;
    const Real pMax           = 40;
    const Size tMinUp         = 2;
    const Size tMinDown       = 2;
    const Real startUpFuel    = 20;
    const Real startUpFixCost = 100;
    const Real carbonPrice    = 3.0;
    const Size nStarts        = Null<Size>();
    const Size stateDirection = 0;
    const Size nStates = ((nStarts == Null<Size>()) ? 1 : nStarts)*
                         (2*tMinUp + tMinDown);
    const std::vector<Size> dim(1, nStates);
    const boost::shared_ptr<FdmLinearOpLayout> layout(
                                                   new FdmLinearOpLayout(dim));
    const boost::shared_ptr<FdmMesher> mesher(
        new FdmMesherComposite(layout,
             std::vector<boost::shared_ptr<Fdm1dMesher> >(1,
                                boost::shared_ptr<Fdm1dMesher>(
                                    new Uniform1dMesher(0.0, 1.0, nStates)))));
    const boost::shared_ptr<FdmInnerValueCalculator> gasPrice(new GasPrice());
    const Real efficiency[] = { 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.9 };
    // Expected values are calculated using mixed integer programming
    // based on the gnu linear programming toolkit. For details please see:
    // http://spanderen.de/
    //        2011/06/23/vpp-pricing-ii-mixed-integer-linear-programming/
    const Real expected[] = { 0.0, 2056.04, 11145.577778, 26452.04,
                              44512.461818, 62000.626667, 137591.911111};
    for (Size i=0; i < LENGTH(efficiency); ++i) {
        const Real heatRate = 1.0/efficiency[i];
        const boost::shared_ptr<FdmInnerValueCalculator> sparkSpreadPrice(
                                              new SparkSpreadPrice(heatRate));
        boost::shared_ptr<StepCondition<Array> > stepCondition(
            new FdmVPPStepCondition(heatRate,
                                    pMin, pMax,
                                    tMinUp, tMinDown,
                                    nStarts,
                                    startUpFuel, startUpFixCost,
                                    carbonPrice, stateDirection,
                                    mesher, gasPrice, sparkSpreadPrice));
        Array state(nStates, 0.0);
        for (Size j=LENGTH(gasPrices); j > 0; --j) {
            stepCondition->applyTo(state, (Time) j-1);
        }
        const Real calculated = *std::max_element(state.begin(), state.end());
        if (std::fabs(expected[i] - calculated) > 1e-2) {
            BOOST_ERROR("Failed to reproduce reference values"
                       << "\n    calculated: " << calculated
                       << "\n    expected:   " << expected[i]);
        }
    }
}
void VPPTest::testVPPPricing () [static]
Definition at line 549 of file vpp.cpp.
References QuantLib::GeneralStatistics::add(), QuantLib::MultiPathGenerator< GSG >::antithetic(), QuantLib::FdmVPPStepCondition::applyTo(), QuantLib::Array::at(), QuantLib::Array::back(), anonymous_namespace{marketmodel.cpp}::beta, QuantLib::GeneralLinearLeastSquares::coefficients(), QuantLib::December, QuantLib::GeneralStatistics::errorEstimate(), QuantLib::Settings::evaluationDate(), QuantLib::flatRate(), QuantLib::Array::front(), anonymous_namespace{vpp.cpp}::gasPrices, QuantLib::Singleton< Settings >::instance(), LENGTH, QuantLib::GenericPseudoRandom< URNG, IC >::make_sequence_generator(), QuantLib::GeneralStatistics::mean(), QuantLib::LsmBasisSystem::Monomial, QuantLib::LsmBasisSystem::multiPathBasisSystem(), QuantLib::MultiPathGenerator< GSG >::next(), QuantLib::Instrument::NPV(), anonymous_namespace{vpp.cpp}::powerPrices, QuantLib::GeneralStatistics::reset(), QuantLib::Instrument::setPricingEngine(), anonymous_namespace{quantlibbenchmark.cpp}::t, anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::DayCounter::yearFraction().
Referenced by suite().
{
    BOOST_MESSAGE("Testing VPP pricing using perfect foresight or FDM...");
    SavedSettings backup;
    const Date today = Date(18, December, 2011);
    const DayCounter dc = ActualActual();
    Settings::instance().evaluationDate() = today;
    // vpp paramter
    const Real heatRate       = 2.5;
    const Real pMin           = 8;
    const Real pMax           = 40;
    const Size tMinUp         = 6;
    const Size tMinDown       = 2;
    const Real startUpFuel    = 20;
    const Real startUpFixCost = 100;
    const Size nStates        = 2u*tMinUp + tMinDown;
    boost::shared_ptr<SwingExercise> exercise(
                                new SwingExercise(today, today+6, 3600u));
    VanillaVPPOption vppOption(heatRate, pMin, pMax,
                               tMinUp, tMinDown,
                               Null<Size>(),
                               startUpFuel, startUpFixCost,
                               exercise);
    // model definition
    const Real beta         = 200;
    const Real eta          = 1.0/0.2;
    const Real lambda       = 4.0;
    const Real alpha        = 7.0;
    const Real volatility_x = 1.4;
    const Real kappa        = 4.45;
    const Real volatility_u = std::sqrt(1.3);
    const Real rho          = 0.7;
    const Rate irRate       = 0.00;
    const Real carbonPrice  = 3.0;
    Array x0(2);
    x0[0] = 0.0; x0[1] = 0.0;
    const boost::shared_ptr<ExtendedOrnsteinUhlenbeckProcess> ouProcess(
        new ExtendedOrnsteinUhlenbeckProcess(alpha, volatility_x, x0[0],
                                             constant<Real, Real>(x0[0])));
    const boost::shared_ptr<ExtOUWithJumpsProcess> lnPowerProcess(
        new ExtOUWithJumpsProcess(ouProcess, x0[1], beta, lambda, eta));
    const Real u=0.0;
    const boost::shared_ptr<ExtendedOrnsteinUhlenbeckProcess> lnGasProcess(
        new ExtendedOrnsteinUhlenbeckProcess(kappa, volatility_u, u,
                                             constant<Real, Real>(u)));
    const boost::shared_ptr<KlugeExtOUProcess> klugeOUProcess(
        new KlugeExtOUProcess(rho, lnPowerProcess, lnGasProcess));
    const boost::shared_ptr<YieldTermStructure> rTS
        = flatRate(today, irRate, dc);
    const Size nHours = LENGTH(powerPrices);
    typedef FdSimpleKlugeExtOUVPPEngine::Shape Shape;
    boost::shared_ptr<Shape> gasShape(new Shape(nHours));
    boost::shared_ptr<Shape> powerShape(new Shape(nHours));
    for (Size i=0; i < nHours; ++i) {
        const Time t = (i+1)/(365*24.);
        const Real gasPrice = gasPrices[i];
        const Real gs = std::log(gasPrice)-square<Real>()(volatility_u)
                               /(4*kappa)*(1-std::exp(-2*kappa*t));
        (*gasShape)[i] = Shape::value_type(t, gs);
        const Real powerPrice = powerPrices[i];
        const Real ps = std::log(powerPrice)-square<Real>()(volatility_x)
                 /(4*alpha)*(1-std::exp(-2*alpha*t))
                -lambda/beta*std::log((eta-std::exp(-beta*t))/(eta-1.0));
        (*powerShape)[i] = Shape::value_type(t, ps);
    }
    // Test: intrinsic value
    const boost::shared_ptr<FdmMesher> oneDimMesher(
        new FdmMesherComposite(boost::shared_ptr<FdmLinearOpLayout>(
            new FdmLinearOpLayout(std::vector<Size>(1, nStates))),
            std::vector<boost::shared_ptr<Fdm1dMesher> >(1,
                boost::shared_ptr<Fdm1dMesher>(
                    new Uniform1dMesher(0.0, 1.0, nStates)))));
    const FdmVPPStepCondition stepCondition(
            heatRate, pMin, pMax, tMinUp, tMinDown, Null<Size>(),
            startUpFuel, startUpFixCost, carbonPrice, 0u, oneDimMesher,
            boost::shared_ptr<FdmInnerValueCalculator>(new GasPrice()),
            boost::shared_ptr<FdmInnerValueCalculator>(
               new SparkSpreadPrice(heatRate)));
    Array state(nStates, 0.0);
    for (Size j=exercise->dates().size(); j > 0; --j) {
        stepCondition.applyTo(state, (Time) j-1);
    }
    const Real intrinsic = state.back();
    const Real expectedIntrinsic = 2056.04;
    if (std::fabs(intrinsic - expectedIntrinsic) > 0.1) {
        BOOST_ERROR("Failed to reproduce intrinsic value"
                   << "\n    calculated: " << intrinsic
                   << "\n    expected  : " << expectedIntrinsic);
    }
    // Test: finite difference price
    const boost::shared_ptr<PricingEngine> engine(
        new FdSimpleKlugeExtOUVPPEngine(klugeOUProcess, rTS, carbonPrice,
                                        1, 25, 11, 10,
                                        gasShape, powerShape));
    vppOption.setPricingEngine(engine);
    const Real fdmPrice = vppOption.NPV();
    const Real expectedFdmPrice = 5217.68;
    if (std::fabs(fdmPrice - expectedFdmPrice) > 0.1) {
       BOOST_ERROR("Failed to reproduce finite difference price"
                   << "\n    calculated: " << fdmPrice
                   << "\n    expected  : " << expectedFdmPrice);
    }
    // Test: Monte-Carlo perfect foresight price
    const TimeGrid grid(dc.yearFraction(today, exercise->lastDate()+1),
                        exercise->dates().size());
    typedef PseudoRandom::rsg_type rsg_type;
    typedef MultiPathGenerator<rsg_type>::sample_type sample_type;
    rsg_type rsg = PseudoRandom::make_sequence_generator(
                           klugeOUProcess->factors()*(grid.size()-1), 1234ul);
    MultiPathGenerator<rsg_type> generator(klugeOUProcess, grid, rsg, false);
    GeneralStatistics npv;
    const Size nTrails = 2500;
    for (Size i=0; i < nTrails; ++i) {
        const sample_type& path = generator.next();
        FdmVPPStepCondition stepCondition(
            heatRate, pMin, pMax, tMinUp, tMinDown, Null<Size>(),
            startUpFuel, startUpFixCost, carbonPrice, 0u, oneDimMesher,
            boost::shared_ptr<FdmInnerValueCalculator>(
                new PathGasPrice(path.value, gasShape)),
            boost::shared_ptr<FdmInnerValueCalculator>(
                new PathSparkSpreadPrice(heatRate, path.value,
                                         gasShape, powerShape)));
        Array state(nStates, 0.0);
        for (Size j=exercise->dates().size(); j > 0; --j) {
            stepCondition.applyTo(state, grid.at(j));
            state*=rTS->discount(grid.at(j))/rTS->discount(grid.at(j-1));
        }
        npv.add(state.back());
    }
    Real npvMC = npv.mean();
    Real errorMC = npv.errorEstimate();
    const Real expectedMC = 5250.0;
    if (std::fabs(npvMC-expectedMC) > 3*errorMC) {
        BOOST_ERROR("Failed to reproduce Monte-Carlo price"
                   << "\n    calculated: " << npvMC
                   << "\n    error     ; " << errorMC
                   << "\n    expected  : " << expectedMC);
    }
    npv.reset();
    // Test: Longstaff Schwartz least square Monte-Carlo
    const Size nCalibrationTrails = 1000u;
    std::vector<sample_type> calibrationPaths;
    std::vector<boost::shared_ptr<FdmVPPStepCondition> > stepConditions;
    std::vector<boost::shared_ptr<FdmInnerValueCalculator> > sparkSpreads;
    sparkSpreads.reserve(nCalibrationTrails);
    stepConditions.reserve(nCalibrationTrails);
    calibrationPaths.reserve(nCalibrationTrails);
    for (Size i=0; i < nCalibrationTrails; ++i) {
        calibrationPaths.push_back(generator.next());
        sparkSpreads.push_back(boost::shared_ptr<FdmInnerValueCalculator>(
            new PathSparkSpreadPrice(heatRate, calibrationPaths.back().value,
                                     gasShape, powerShape)));
        stepConditions.push_back(boost::shared_ptr<FdmVPPStepCondition>(
            new FdmVPPStepCondition(
                heatRate, pMin, pMax, tMinUp, tMinDown,Null<Size>(),
                startUpFuel, startUpFixCost, carbonPrice, 0u, oneDimMesher,
                boost::shared_ptr<FdmInnerValueCalculator>(
                    new PathGasPrice(calibrationPaths.back().value, gasShape)),
                sparkSpreads.back())));
    }
    const FdmLinearOpIterator iter = oneDimMesher->layout()->begin();
    // prices of all calibration paths for all states
    std::vector<Array> prices(nCalibrationTrails, Array(nStates, 0.0));
    // regression coefficients for all states and all exercise dates
    std::vector<std::vector<Array> > coeff(
        nStates, std::vector<Array>(exercise->dates().size(), Array()));
    // regression functions
    const Size dim = 1u;
    std::vector<boost::function1<Real, Array> > v(
        LsmBasisSystem::multiPathBasisSystem(dim,5u, LsmBasisSystem::Monomial));
    for (Size i=exercise->dates().size(); i > 0u; --i) {
        const Time t = grid.at(i);
        std::vector<Array> x(nCalibrationTrails, Array(dim));
        for (Size j=0; j < nCalibrationTrails; ++j) {
            x[j][0] = sparkSpreads[j]->innerValue(iter, t);
        }
        for (Size k=0; k < nStates; ++k) {
            std::vector<Real> y(nCalibrationTrails);
            for (Size j=0; j < nCalibrationTrails; ++j) {
                y[j] = prices[j][k];
            }
            coeff[k][i-1] = GeneralLinearLeastSquares(x, y, v).coefficients();
            for (Size j=0; j < nCalibrationTrails; ++j) {
                prices[j][k] = 0.0;
                for (Size l=0; l < v.size(); ++l) {
                    prices[j][k] += coeff[k][i-1][l]*v[l](x[j]);
                }
            }
        }
        for (Size j=0; j < nCalibrationTrails; ++j) {
            stepConditions[j]->applyTo(prices[j], grid.at(i));
        }
    }
    Real tmpValue = 0.0;
    for (Size i=0; i < nTrails; ++i) {
        Array x(dim), state(nStates, 0.0), contState(nStates, 0.0);
        const sample_type& path = (i % 2) ? generator.antithetic()
                                          : generator.next();
        const boost::shared_ptr<FdmInnerValueCalculator> gasPrices(
            new PathGasPrice(path.value, gasShape));
        const boost::shared_ptr<FdmInnerValueCalculator> sparkSpreads(
            new PathSparkSpreadPrice(heatRate, path.value,
                                     gasShape, powerShape));
        FdmVPPStepCondition stepCondition(
            heatRate, pMin, pMax, tMinUp, tMinDown,Null<Size>(),
            startUpFuel, startUpFixCost, carbonPrice, 0u, oneDimMesher,
            gasPrices, sparkSpreads);
        for (Size j=exercise->dates().size(); j > 0u; --j) {
            const Time t = grid.at(j);
            const Real gasPrice = gasPrices->innerValue(iter, t);
            const Real sparkSpread = sparkSpreads->innerValue(iter, t);
            const Real startUpCost
                    = startUpFixCost + (gasPrice + carbonPrice)*startUpFuel;
            x[0] = sparkSpread;
            for (Size k=0; k < nStates; ++k) {
                contState[k] = 0.0;
                for (Size l=0; l < v.size(); ++l) {
                    contState[k] += coeff[k][j-1][l]*v[l](x);
                }
            }
            const Real pMinFlow = pMin*(sparkSpread - heatRate*carbonPrice);
            const Real pMaxFlow = pMax*(sparkSpread - heatRate*carbonPrice);
            // rollback continuation states and the path states
            for (Size i=0; i < 2*tMinUp; ++i) {
                if (i < tMinUp) {
                    state[i]    += pMinFlow;
                    contState[i]+= pMinFlow;
                }
                else {
                    state[i]    += pMaxFlow;
                    contState[i]+= pMaxFlow;
                }
            }
            // dynamic programming using the continuation values
            Array retVal(nStates);
            for (Size i=0; i < tMinUp-1; ++i) {
                retVal[i] = retVal[tMinUp + i]
                          = (contState[i+1] > contState[tMinUp + i+1])?
                                          state[i+1] : state[tMinUp + i+1];
            }
            if (contState[2*tMinUp] >=
                std::max(contState[tMinUp-1], contState[2*tMinUp-1])) {
                retVal[tMinUp-1] = retVal[2*tMinUp-1] = state[2*tMinUp];
            }
            else if (contState[tMinUp-1] >= contState[2*tMinUp-1]) {
                retVal[tMinUp-1] = retVal[2*tMinUp-1] = state[tMinUp-1];
            }
            else {
                retVal[tMinUp-1] = retVal[2*tMinUp-1] = state[2*tMinUp-1];
            }
            for (Size i=0; i < tMinDown-1; ++i) {
                retVal[2*tMinUp + i] = state[2*tMinUp + i+1];
            }
            if (contState.back() >=
                std::max(contState.front(), contState[tMinUp]) - startUpCost) {
                retVal.back() = state.back();
            }
            else if (contState.front() >  contState[tMinUp]) {
                retVal.back() = state.front()-startUpCost;
            }
            else {
                retVal.back() = state[tMinUp]-startUpCost;
            }
            state = retVal;
        }
        tmpValue+=0.5*state.back();
        if ((i%2)) {
            npv.add(tmpValue, 1.0);
            tmpValue = 0.0;
        }
    }
    npvMC = npv.mean();
    errorMC = npv.errorEstimate();
    if (std::fabs(npvMC-fdmPrice) > 3*errorMC) {
        BOOST_ERROR("Failed to reproduce Least Square Monte-Carlo price"
                   << "\n    calculated   : " << npvMC
                   << "\n    error        : " << errorMC
                   << "\n    expected FDM : " << fdmPrice);
    }
}
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/vpp.hpp
/home/deriversatile/QuantLib/QuantLibQt/test-suite/vpp.cpp