QuantLib: QuantLib::detail::ImpliedVolatilityHelper Class Reference
QuantLib::detail::ImpliedVolatilityHelper Class Reference
helper class for one-asset implied-volatility calculation
#include <impliedvolatility.hpp>
Static Public Member Functions
static Volatility calculate (const Instrument &instrument, const PricingEngine &engine, SimpleQuote &volQuote, Real targetValue, Real accuracy, Natural maxEvaluations, Volatility minVol, Volatility maxVol)
static boost::shared_ptr
< GeneralizedBlackScholesProcess > clone (const boost::shared_ptr< GeneralizedBlackScholesProcess > &, const boost::shared_ptr< SimpleQuote > &)
Detailed Description
helper class for one-asset implied-volatility calculation
The passed engine must be linked to the passed quote (see, e.g., VanillaOption to see how this can be achieved.)
Note:
this function is meant for developers of option classes so that they can implement an impliedVolatility() method.
Definition at line 43 of file impliedvolatility.hpp.
Member Function Documentation
Volatility QuantLib::detail::ImpliedVolatilityHelper::calculate (const Instrument & instrument, const PricingEngine & engine, SimpleQuote & volQuote, Real targetValue, Real accuracy, Natural maxEvaluations, Volatility minVol, Volatility maxVol) [static]
Definition at line 62 of file impliedvolatility.cpp.
References anonymous_namespace{interpolations.cpp}::f(), QuantLib::PricingEngine::getArguments(), QuantLib::Solver1D< Impl >::setMaxEvaluations(), QuantLib::Instrument::setupArguments(), QuantLib::Solver1D< Impl >::solve(), and QuantLib::PricingEngine::arguments::validate().
Referenced by HybridHestonHullWhiteProcessTest::testHestonHullWhiteCalibration().
{
            instrument.setupArguments(engine.getArguments());
            engine.getArguments()->validate();
            PriceError f(engine, volQuote, targetValue);
            Brent solver;
            solver.setMaxEvaluations(maxEvaluations);
            Volatility guess = (minVol+maxVol)/2.0;
            Volatility result = solver.solve(f, accuracy, guess,
                                             minVol, maxVol);
            return result;
        }
boost::shared_ptr< GeneralizedBlackScholesProcess > QuantLib::detail::ImpliedVolatilityHelper::clone (const boost::shared_ptr< GeneralizedBlackScholesProcess > & process, const boost::shared_ptr< SimpleQuote > & volQuote) [static]
The returned process is equal to the passed one, except for the volatility which is flat and whose value is driven by the passed quote.
Definition at line 85 of file impliedvolatility.cpp.
References QuantLib::io::volatility().
Referenced by QuantLib::DividendVanillaOption::impliedVolatility(), QuantLib::BarrierOption::impliedVolatility(), QuantLib::VanillaOption::impliedVolatility(), and HybridHestonHullWhiteProcessTest::testHestonHullWhiteCalibration().
{
            Handle<Quote> stateVariable = process->stateVariable();
            Handle<YieldTermStructure> dividendYield = process->dividendYield();
            Handle<YieldTermStructure> riskFreeRate = process->riskFreeRate();
            Handle<BlackVolTermStructure> blackVol = process->blackVolatility();
            Handle<BlackVolTermStructure> volatility(
                boost::shared_ptr<BlackVolTermStructure>(
                               new BlackConstantVol(blackVol->referenceDate(),
                                                    blackVol->calendar(),
                                                    Handle<Quote>(volQuote),
                                                    blackVol->dayCounter())));
            return boost::shared_ptr<GeneralizedBlackScholesProcess>(
                new GeneralizedBlackScholesProcess(stateVariable, dividendYield,
                                                   riskFreeRate, volatility));
        }
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/impliedvolatility.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/impliedvolatility.cpp