QuantLib: QuantLib::BlackIborCouponPricer Class Reference
QuantLib::BlackIborCouponPricer Class Reference
Black-formula pricer for capped/floored Ibor coupons.
#include <couponpricer.hpp>
Public Member Functions
BlackIborCouponPricer (const Handle< OptionletVolatilityStructure > &v=Handle< OptionletVolatilityStructure >())
virtual void initialize (const FloatingRateCoupon &coupon)
Real swapletPrice () const
Rate swapletRate () const
Real capletPrice (Rate effectiveCap) const
Rate capletRate (Rate effectiveCap) const
Real floorletPrice (Rate effectiveFloor) const
Rate floorletRate (Rate effectiveFloor) const
Protected Member Functions
Real optionletPrice (Option::Type optionType, Real effStrike) const
virtual Rate adjustedFixing (Rate fixing=Null< Rate >()) const
Protected Attributes
Real gearing_
Spread spread_
Time accrualPeriod_
boost::shared_ptr< IborIndex > index_
Real discount_
Real spreadLegValue_
const FloatingRateCoupon * coupon_
Detailed Description
Black-formula pricer for capped/floored Ibor coupons.
Definition at line 84 of file couponpricer.hpp.
Constructor & Destructor Documentation
QuantLib::BlackIborCouponPricer::BlackIborCouponPricer (const Handle< OptionletVolatilityStructure > & v = Handle<OptionletVolatilityStructure>()) [inline]
Definition at line 86 of file couponpricer.hpp.
        : IborCouponPricer(v) {};
Member Function Documentation
Rate QuantLib::BlackIborCouponPricer::adjustedFixing (Rate fixing = Null<Rate>()) const [protected, virtual]
Reimplemented in QuantLib::BlackIborQuantoCouponPricer.
Definition at line 97 of file couponpricer.cpp.
References QuantLib::IborCouponPricer::capletVolatility(), coupon_, QuantLib::FloatingRateCoupon::fixingDate(), index_, QuantLib::FloatingRateCoupon::indexFixing(), QuantLib::FloatingRateCoupon::isInArrears(), and QL_REQUIRE.
Referenced by optionletPrice(), and swapletPrice().
{
        if (fixing == Null<Rate>())
            fixing = coupon_->indexFixing();
        if (!coupon_->isInArrears())
            return fixing;
        QL_REQUIRE(!capletVolatility().empty(),
                   "missing optionlet volatility");
        Date d1 = coupon_->fixingDate();
        Date referenceDate = capletVolatility()->referenceDate();
        if (d1 <= referenceDate)
            return fixing;
        // see Hull, 4th ed., page 550
        Date d2 = index_->maturityDate(d1);
        Time tau = index_->dayCounter().yearFraction(d1, d2);
        Real variance = capletVolatility()->blackVariance(d1, fixing);
        Spread adjustement = fixing*fixing*variance*tau/(1.0+fixing*tau);
        return fixing + adjustement;
    }
Real QuantLib::BlackIborCouponPricer::capletPrice (Rate effectiveCap) const [inline, virtual]
Implements QuantLib::FloatingRateCouponPricer.
Definition at line 156 of file couponpricer.hpp.
References QuantLib::Option::Call, gearing_, and optionletPrice().
Referenced by capletRate().
{
        Real capletPrice = optionletPrice(Option::Call, effectiveCap);
        return gearing_ * capletPrice;
    }
Rate QuantLib::BlackIborCouponPricer::capletRate (Rate effectiveCap) const [inline, virtual]
Implements QuantLib::FloatingRateCouponPricer.
Definition at line 161 of file couponpricer.hpp.
References accrualPeriod_, capletPrice(), and discount_.
{
        return capletPrice(effectiveCap) / (accrualPeriod_*discount_);
    }
Real QuantLib::BlackIborCouponPricer::floorletPrice (Rate effectiveFloor) const [inline, virtual]
Implements QuantLib::FloatingRateCouponPricer.
Definition at line 166 of file couponpricer.hpp.
References gearing_, optionletPrice(), and QuantLib::Option::Put.
Referenced by floorletRate().
{
        Real floorletPrice = optionletPrice(Option::Put, effectiveFloor);
        return gearing_ * floorletPrice;
    }
Rate QuantLib::BlackIborCouponPricer::floorletRate (Rate effectiveFloor) const [inline, virtual]
Implements QuantLib::FloatingRateCouponPricer.
Definition at line 172 of file couponpricer.hpp.
References accrualPeriod_, discount_, and floorletPrice().
{
        return floorletPrice(effectiveFloor) / (accrualPeriod_*discount_);
    }
void QuantLib::BlackIborCouponPricer::initialize (const FloatingRateCoupon & coupon) [virtual]
Implements QuantLib::FloatingRateCouponPricer.
Definition at line 40 of file couponpricer.cpp.
References QuantLib::Coupon::accrualPeriod(), accrualPeriod_, anonymous_namespace{marketmodel.cpp}::c, coupon_, QuantLib::Coupon::date(), discount_, QuantLib::FloatingRateCoupon::gearing(), gearing_, QuantLib::FloatingRateCoupon::index(), index_, QL_FAIL, QL_REQUIRE, QuantLib::FloatingRateCoupon::spread(), spread_, and spreadLegValue_.
{
        gearing_ = coupon.gearing();
        spread_ = coupon.spread();
        accrualPeriod_ = coupon.accrualPeriod();
        index_ = dynamic_pointer_cast<IborIndex>(coupon.index());
        if (!index_) {
            // check if the coupon was right
            const IborCoupon* c = dynamic_cast<const IborCoupon*>(&coupon);
            QL_REQUIRE(c, "IborCoupon required");
            // coupon was right, index is not
            QL_FAIL("IborIndex required");
        }
        Handle<YieldTermStructure> rateCurve =
                                            index_->forwardingTermStructure();
        Date paymentDate = coupon.date();
        if (paymentDate > rateCurve->referenceDate())
            discount_ = rateCurve->discount(paymentDate);
        else
            discount_ = 1.0;
        spreadLegValue_ = spread_ * accrualPeriod_ * discount_;
        coupon_ = &coupon;
    }
Real QuantLib::BlackIborCouponPricer::optionletPrice (Option::Type optionType, Real effStrike) const [protected]
Definition at line 68 of file couponpricer.cpp.
References anonymous_namespace{marketmodel.cpp}::a, accrualPeriod_, adjustedFixing(), anonymous_namespace{marketmodel.cpp}::b, QuantLib::blackFormula(), QuantLib::Option::Call, QuantLib::IborCouponPricer::capletVolatility(), coupon_, discount_, QuantLib::FloatingRateCoupon::fixingDate(), QuantLib::FloatingRateCoupon::indexFixing(), QuantLib::Singleton< Settings >::instance(), and QL_REQUIRE.
Referenced by capletPrice(), and floorletPrice().
{
        Date fixingDate = coupon_->fixingDate();
        if (fixingDate <= Settings::instance().evaluationDate()) {
            // the amount is determined
            Real a, b;
            if (optionType==Option::Call) {
                a = coupon_->indexFixing();
                b = effStrike;
            } else {
                a = effStrike;
                b = coupon_->indexFixing();
            }
            return std::max(a - b, 0.0)* accrualPeriod_*discount_;
        } else {
            // not yet determined, use Black model
            QL_REQUIRE(!capletVolatility().empty(),
                       "missing optionlet volatility");
            Real stdDev =
                std::sqrt(capletVolatility()->blackVariance(fixingDate,
                                                            effStrike));
            Rate fixing = blackFormula(optionType,
                                       effStrike,
                                       adjustedFixing(),
                                       stdDev);
            return fixing * accrualPeriod_ * discount_;
        }
    }
Real QuantLib::BlackIborCouponPricer::swapletPrice () const [inline, virtual]
Implements QuantLib::FloatingRateCouponPricer.
Definition at line 145 of file couponpricer.hpp.
References accrualPeriod_, adjustedFixing(), discount_, gearing_, and spreadLegValue_.
Referenced by swapletRate().
{
        // past or future fixing is managed in InterestRateIndex::fixing()
        Real swapletPrice = adjustedFixing() * accrualPeriod_ * discount_;
        return gearing_ * swapletPrice + spreadLegValue_;
    }
Rate QuantLib::BlackIborCouponPricer::swapletRate () const [inline, virtual]
Implements QuantLib::FloatingRateCouponPricer.
Definition at line 152 of file couponpricer.hpp.
References accrualPeriod_, discount_, and swapletPrice().
{
        return swapletPrice()/(accrualPeriod_*discount_);
    }
Member Data Documentation
Time QuantLib::BlackIborCouponPricer::accrualPeriod_ [protected]
Definition at line 106 of file couponpricer.hpp.
Referenced by capletRate(), floorletRate(), initialize(), optionletPrice(), swapletPrice(), and swapletRate().
const FloatingRateCoupon* QuantLib::BlackIborCouponPricer::coupon_ [protected]
Definition at line 111 of file couponpricer.hpp.
Referenced by QuantLib::BlackIborQuantoCouponPricer::adjustedFixing(), adjustedFixing(), initialize(), and optionletPrice().
Real QuantLib::BlackIborCouponPricer::discount_ [protected]
Definition at line 108 of file couponpricer.hpp.
Referenced by capletRate(), floorletRate(), initialize(), optionletPrice(), swapletPrice(), and swapletRate().
Real QuantLib::BlackIborCouponPricer::gearing_ [protected]
Definition at line 104 of file couponpricer.hpp.
Referenced by capletPrice(), floorletPrice(), initialize(), and swapletPrice().
boost::shared_ptr<IborIndex> QuantLib::BlackIborCouponPricer::index_ [protected]
Definition at line 107 of file couponpricer.hpp.
Referenced by adjustedFixing(), and initialize().
Spread QuantLib::BlackIborCouponPricer::spread_ [protected]
Definition at line 105 of file couponpricer.hpp.
Referenced by initialize().
Real QuantLib::BlackIborCouponPricer::spreadLegValue_ [protected]
Definition at line 109 of file couponpricer.hpp.
Referenced by initialize(), and swapletPrice().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/couponpricer.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/couponpricer.cpp