QuantLib: QuantLib::CapFloorTermVolatilityStructure Class Reference
QuantLib::CapFloorTermVolatilityStructure Class Reference
Cap/floor term-volatility structure.
#include <capfloortermvolatilitystructure.hpp>
Public Member Functions
virtual ~CapFloorTermVolatilityStructure ()
Constructors
See the TermStructure documentation for issues regarding constructors.
CapFloorTermVolatilityStructure (const Calendar &cal, BusinessDayConvention bdc, const DayCounter &dc=DayCounter())
CapFloorTermVolatilityStructure (BusinessDayConvention bdc, const DayCounter &dc=DayCounter())
CapFloorTermVolatilityStructure (const Date &referenceDate, const Calendar &cal, BusinessDayConvention bdc, const DayCounter &dc=DayCounter())
initialize with a fixed reference date
CapFloorTermVolatilityStructure (Natural settlementDays, const Calendar &, BusinessDayConvention bdc, const DayCounter &dc=DayCounter())
calculate the reference date based on the global evaluation date
Volatility
Volatility volatility (const Period &length, Rate strike, bool extrapolate=false) const
returns the volatility for a given cap/floor length and strike rate
Volatility volatility (const Date &end, Rate strike, bool extrapolate=false) const
Volatility volatility (Time t, Rate strike, bool extrapolate=false) const
returns the volatility for a given end time and strike rate
Protected Member Functions
virtual Volatility volatilityImpl (Time length, Rate strike) const =0
implements the actual volatility calculation in derived classes
Detailed Description
Cap/floor term-volatility structure.
This class is purely abstract and defines the interface of concrete structures which will be derived from this one.
Definition at line 36 of file capfloortermvolatilitystructure.hpp.
Constructor & Destructor Documentation
QuantLib::CapFloorTermVolatilityStructure::CapFloorTermVolatilityStructure (const Calendar & cal, BusinessDayConvention bdc, const DayCounter & dc = DayCounter())
Warning:
term structures initialized by means of this constructor must manage their own reference date by overriding the referenceDate() method.
Definition at line 26 of file capfloortermvolatilitystructure.cpp.
    : VolatilityTermStructure(cal, bdc, dc) {}
QuantLib::CapFloorTermVolatilityStructure::CapFloorTermVolatilityStructure (BusinessDayConvention bdc, const DayCounter & dc = DayCounter())
Warning:
term structures initialized by means of this constructor must manage their own reference date by overriding the referenceDate() method.
Definition at line 33 of file capfloortermvolatilitystructure.cpp.
    : VolatilityTermStructure(bdc, dc) {}
QuantLib::CapFloorTermVolatilityStructure::CapFloorTermVolatilityStructure (const Date & referenceDate, const Calendar & cal, BusinessDayConvention bdc, const DayCounter & dc = DayCounter())
initialize with a fixed reference date
Definition at line 38 of file capfloortermvolatilitystructure.cpp.
    : VolatilityTermStructure(refDate, cal, bdc, dc) {}
QuantLib::CapFloorTermVolatilityStructure::CapFloorTermVolatilityStructure (Natural settlementDays, const Calendar & cal, BusinessDayConvention bdc, const DayCounter & dc = DayCounter())
calculate the reference date based on the global evaluation date
Definition at line 45 of file capfloortermvolatilitystructure.cpp.
    : VolatilityTermStructure(settlementDays, cal, bdc, dc) {}
virtual QuantLib::CapFloorTermVolatilityStructure::~CapFloorTermVolatilityStructure () [inline, virtual]
Definition at line 69 of file capfloortermvolatilitystructure.hpp.
{}
Member Function Documentation
Volatility QuantLib::CapFloorTermVolatilityStructure::volatility (const Period & length, Rate strike, bool extrapolate = false) const [inline]
returns the volatility for a given cap/floor length and strike rate
Definition at line 93 of file capfloortermvolatilitystructure.hpp.
References anonymous_namespace{marketmodel.cpp}::d, and QuantLib::VolatilityTermStructure::optionDateFromTenor().
Referenced by volatility().
{
        Date d = optionDateFromTenor(optT);
        return volatility(d, strike, extrap);
    }
Volatility QuantLib::CapFloorTermVolatilityStructure::volatility (const Date & end, Rate strike, bool extrapolate = false) const [inline]
Definition at line 101 of file capfloortermvolatilitystructure.hpp.
References QuantLib::TermStructure::checkRange(), anonymous_namespace{quantlibbenchmark.cpp}::t, QuantLib::TermStructure::timeFromReference(), and volatility().
{
        checkRange(d, extrap);
        Time t = timeFromReference(d);
        return volatility(t, strike, extrap);
    }
Volatility QuantLib::CapFloorTermVolatilityStructure::volatility (Time t, Rate strike, bool extrapolate = false) const [inline]
returns the volatility for a given end time and strike rate
Definition at line 110 of file capfloortermvolatilitystructure.hpp.
References QuantLib::TermStructure::checkRange(), QuantLib::VolatilityTermStructure::checkStrike(), and volatilityImpl().
{
        checkRange(t, extrap);
        checkStrike(strike, extrap);
        return volatilityImpl(t, strike);
    }
virtual Volatility QuantLib::CapFloorTermVolatilityStructure::volatilityImpl (Time length, Rate strike) const [protected, pure virtual]
implements the actual volatility calculation in derived classes
Implemented in QuantLib::CapFloorTermVolSurface, QuantLib::CapFloorTermVolCurve, and QuantLib::ConstantCapFloorTermVolatility.
Referenced by volatility().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/capfloor/capfloortermvolatilitystructure.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/capfloor/capfloortermvolatilitystructure.cpp