QuantLib: QuantLib::FdmBlackScholesOp Class Reference
QuantLib::FdmBlackScholesOp Class Reference
#include <fdmblackscholesop.hpp>
Public Member Functions
FdmBlackScholesOp (const boost::shared_ptr< FdmMesher > &mesher, const boost::shared_ptr< GeneralizedBlackScholesProcess > &process, Real strike, bool localVol=false, Real illegalLocalVolOverwrite=-Null< Real >(), Size direction=0)
Size size () const
void setTime (Time t1, Time t2)
Time \(t1 <= t2\) is required.
Disposable< Array > apply (const Array &r) const
Disposable< Array > apply_mixed (const Array &r) const
Disposable< Array > apply_direction (Size direction, const Array &r) const
Disposable< Array > solve_splitting (Size direction, const Array &r, Real s) const
Disposable< Array > preconditioner (const Array &r, Real s) const
Disposable< SparseMatrix > toMatrix () const
Private Attributes
const boost::shared_ptr
< FdmMesher > mesher_
const boost::shared_ptr
< YieldTermStructure > rTS_
const boost::shared_ptr
< YieldTermStructure > qTS_
const boost::shared_ptr
< BlackVolTermStructure > volTS_
const boost::shared_ptr
< LocalVolTermStructure > localVol_
const Array x_
const FirstDerivativeOp dxMap_
const TripleBandLinearOp dxxMap_
TripleBandLinearOp mapT_
const Real strike_
const Real illegalLocalVolOverwrite_
const Size direction_
Detailed Description
Definition at line 37 of file fdmblackscholesop.hpp.
Constructor & Destructor Documentation
QuantLib::FdmBlackScholesOp::FdmBlackScholesOp (const boost::shared_ptr< FdmMesher > & mesher, const boost::shared_ptr< GeneralizedBlackScholesProcess > & process, Real strike, bool localVol = false, Real illegalLocalVolOverwrite = -Null<Real>(), Size direction = 0)
Definition at line 31 of file fdmblackscholesop.cpp.
    : mesher_(mesher),
      rTS_   (bsProcess->riskFreeRate().currentLink()),
      qTS_   (bsProcess->dividendYield().currentLink()),
      volTS_ (bsProcess->blackVolatility().currentLink()),
      localVol_((localVol) ? bsProcess->localVolatility().currentLink()
                           : boost::shared_ptr<LocalVolTermStructure>()),
      x_     ((localVol) ? Array(Exp(mesher->locations(direction))) : Array()),
      dxMap_ (FirstDerivativeOp(direction, mesher)),
      dxxMap_(SecondDerivativeOp(direction, mesher)),
      mapT_  (direction, mesher),
      strike_(strike),
      illegalLocalVolOverwrite_(illegalLocalVolOverwrite),
      direction_(direction) {
    }
Member Function Documentation
Disposable< Array > QuantLib::FdmBlackScholesOp::apply (const Array & r) const [virtual]
Implements QuantLib::FdmLinearOp.
Definition at line 96 of file fdmblackscholesop.cpp.
References QuantLib::TripleBandLinearOp::apply(), and mapT_.
Referenced by QuantLib::Fdm2dBlackScholesOp::apply(), and QuantLib::Fdm2dBlackScholesOp::apply_direction().
{
        return mapT_.apply(u);
    }
Disposable< Array > QuantLib::FdmBlackScholesOp::apply_direction (Size direction, const Array & r) const [virtual]
Implements QuantLib::FdmLinearOpComposite.
Definition at line 100 of file fdmblackscholesop.cpp.
References QuantLib::TripleBandLinearOp::apply(), direction_, mapT_, and QuantLib::Array::size().
{
        if (direction == direction_)
            return mapT_.apply(r);
        else {
            Array retVal(r.size(), 0.0);
            return retVal;
        }
    }
Disposable< Array > QuantLib::FdmBlackScholesOp::apply_mixed (const Array & r) const [virtual]
Implements QuantLib::FdmLinearOpComposite.
Definition at line 110 of file fdmblackscholesop.cpp.
References QuantLib::Array::size().
{
        Array retVal(r.size(), 0.0);
        return retVal;
    }
Disposable< Array > QuantLib::FdmBlackScholesOp::preconditioner (const Array & r, Real s) const [virtual]
Implements QuantLib::FdmLinearOpComposite.
Definition at line 125 of file fdmblackscholesop.cpp.
References direction_, and solve_splitting().
{
        return solve_splitting(direction_, r, dt);
    }
void QuantLib::FdmBlackScholesOp::setTime (Time t1, Time t2) [virtual]
Time \(t1 <= t2\) is required.
Implements QuantLib::FdmLinearOpComposite.
Definition at line 53 of file fdmblackscholesop.cpp.
References QuantLib::TripleBandLinearOp::axpyb(), QuantLib::Continuous, dxMap_, dxxMap_, illegalLocalVolOverwrite_, localVol_, mapT_, mesher_, QuantLib::TripleBandLinearOp::mult(), qTS_, rTS_, strike_, anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), volTS_, and x_.
Referenced by QuantLib::Fdm2dBlackScholesOp::setTime().
{
        const Rate r = rTS_->forwardRate(t1, t2, Continuous).rate();
        const Rate q = qTS_->forwardRate(t1, t2, Continuous).rate();
        if (localVol_) {
            const boost::shared_ptr<FdmLinearOpLayout> layout=mesher_->layout();
            const FdmLinearOpIterator endIter = layout->end();
            Array v(layout->size());
            for (FdmLinearOpIterator iter = layout->begin();
                 iter!=endIter; ++iter) {
                const Size i = iter.index();
                if (illegalLocalVolOverwrite_ < 0.0) {
                    v[i] = square<Real>()(
                                localVol_->localVol(0.5*(t1+t2), x_[i], true));
                }
                else {
                    try {
                        v[i] = square<Real>()(
                                localVol_->localVol(0.5*(t1+t2), x_[i], true));
                    } catch (Error&) {
                        v[i] = square<Real>()(illegalLocalVolOverwrite_);
                    }
                }
            }
            mapT_.axpyb(r - q - 0.5*v, dxMap_,
                        dxxMap_.mult(0.5*v), Array(1, -r));
        }
        else {
            const Real v
                = volTS_->blackForwardVariance(t1, t2, strike_)/(t2-t1);
            mapT_.axpyb(Array(1, r - q - 0.5*v), dxMap_,
                        dxxMap_.mult(0.5*Array(mesher_->layout()->size(), v)),
                        Array(1, -r));
        }
    }
Size QuantLib::FdmBlackScholesOp::size () const [virtual]
Implements QuantLib::FdmLinearOpComposite.
Definition at line 92 of file fdmblackscholesop.cpp.
{
        return 1u;
    }
Disposable< Array > QuantLib::FdmBlackScholesOp::solve_splitting (Size direction, const Array & r, Real s) const [virtual]
Implements QuantLib::FdmLinearOpComposite.
Definition at line 115 of file fdmblackscholesop.cpp.
References direction_, mapT_, and QuantLib::TripleBandLinearOp::solve_splitting().
Referenced by preconditioner(), and QuantLib::Fdm2dBlackScholesOp::solve_splitting().
{
        if (direction == direction_)
            return mapT_.solve_splitting(r, dt, 1.0);
        else {
            Array retVal(r);
            return retVal;
        }
    }
Disposable< SparseMatrix > QuantLib::FdmBlackScholesOp::toMatrix () const [virtual]
Reimplemented from QuantLib::FdmLinearOp.
Definition at line 131 of file fdmblackscholesop.cpp.
References mapT_, and QuantLib::TripleBandLinearOp::toMatrix().
Referenced by QuantLib::Fdm2dBlackScholesOp::toMatrix().
{
        return mapT_.toMatrix();
    }
Member Data Documentation
const Size QuantLib::FdmBlackScholesOp::direction_ [private]
Definition at line 72 of file fdmblackscholesop.hpp.
Referenced by apply_direction(), preconditioner(), and solve_splitting().
const FirstDerivativeOp QuantLib::FdmBlackScholesOp::dxMap_ [private]
Definition at line 67 of file fdmblackscholesop.hpp.
Referenced by setTime().
const TripleBandLinearOp QuantLib::FdmBlackScholesOp::dxxMap_ [private]
Definition at line 68 of file fdmblackscholesop.hpp.
Referenced by setTime().
const Real QuantLib::FdmBlackScholesOp::illegalLocalVolOverwrite_ [private]
Definition at line 71 of file fdmblackscholesop.hpp.
Referenced by setTime().
const boost::shared_ptr<LocalVolTermStructure> QuantLib::FdmBlackScholesOp::localVol_ [private]
Definition at line 65 of file fdmblackscholesop.hpp.
Referenced by setTime().
TripleBandLinearOp QuantLib::FdmBlackScholesOp::mapT_ [private]
Definition at line 69 of file fdmblackscholesop.hpp.
Referenced by apply(), apply_direction(), setTime(), solve_splitting(), and toMatrix().
const boost::shared_ptr<FdmMesher> QuantLib::FdmBlackScholesOp::mesher_ [private]
Definition at line 62 of file fdmblackscholesop.hpp.
Referenced by setTime().
const boost::shared_ptr<YieldTermStructure> QuantLib::FdmBlackScholesOp::qTS_ [private]
Definition at line 63 of file fdmblackscholesop.hpp.
Referenced by setTime().
const boost::shared_ptr<YieldTermStructure> QuantLib::FdmBlackScholesOp::rTS_ [private]
Definition at line 63 of file fdmblackscholesop.hpp.
Referenced by setTime().
const Real QuantLib::FdmBlackScholesOp::strike_ [private]
Definition at line 70 of file fdmblackscholesop.hpp.
Referenced by setTime().
const boost::shared_ptr<BlackVolTermStructure> QuantLib::FdmBlackScholesOp::volTS_ [private]
Definition at line 64 of file fdmblackscholesop.hpp.
Referenced by setTime().
const Array QuantLib::FdmBlackScholesOp::x_ [private]
Definition at line 66 of file fdmblackscholesop.hpp.
Referenced by setTime().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/operators/fdmblackscholesop.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/operators/fdmblackscholesop.cpp