QuantLib: QuantLib::BlackVarianceCurve Class Reference
QuantLib::BlackVarianceCurve Class Reference
Black volatility curve modelled as variance curve.
#include <blackvariancecurve.hpp>
Public Member Functions
BlackVarianceCurve (const Date &referenceDate, const std::vector< Date > &dates, const std::vector< Volatility > &blackVolCurve, const DayCounter &dayCounter, bool forceMonotoneVariance=true)
TermStructure interface
DayCounter dayCounter () const
the day counter used for date/time conversion
Date maxDate () const
the latest date for which the curve can return values
VolatilityTermStructure interface
Real minStrike () const
the minimum strike for which the term structure can return vols
Real maxStrike () const
the maximum strike for which the term structure can return vols
Modifiers
template<class Interpolator >
void setInterpolation (const Interpolator &i=Interpolator())
Visitability
virtual void accept (AcyclicVisitor &)
Protected Member Functions
virtual Real blackVarianceImpl (Time t, Real) const
Black variance calculation.
Private Attributes
DayCounter dayCounter_
Date maxDate_
std::vector< Time > times_
std::vector< Real > variances_
Interpolation varianceCurve_
Detailed Description
Black volatility curve modelled as variance curve.
This class calculates time-dependent Black volatilities using as input a vector of (ATM) Black volatilities observed in the market.
The calculation is performed interpolating on the variance curve. Linear interpolation is used as default; this can be changed by the setInterpolation() method.
For strike dependence, see BlackVarianceSurface.
Todo:
check time extrapolation
Definition at line 47 of file blackvariancecurve.hpp.
Constructor & Destructor Documentation
QuantLib::BlackVarianceCurve::BlackVarianceCurve (const Date & referenceDate, const std::vector< Date > & dates, const std::vector< Volatility > & blackVolCurve, const DayCounter & dayCounter, bool forceMonotoneVariance = true)
Definition at line 26 of file blackvariancecurve.cpp.
References QL_REQUIRE, QuantLib::TermStructure::timeFromReference(), times_, and variances_.
    : BlackVarianceTermStructure(referenceDate),
      dayCounter_(dayCounter), maxDate_(dates.back()) {
        QL_REQUIRE(dates.size()==blackVolCurve.size(),
                   "mismatch between date vector and black vol vector");
        // cannot have dates[0]==referenceDate, since the
        // value of the vol at dates[0] would be lost
        // (variance at referenceDate must be zero)
        QL_REQUIRE(dates[0]>referenceDate,
                   "cannot have dates[0] <= referenceDate");
        variances_ = std::vector<Real>(dates.size()+1);
        times_ = std::vector<Time>(dates.size()+1);
        variances_[0] = 0.0;
        times_[0] = 0.0;
        Size j;
        for (j=1; j<=blackVolCurve.size(); j++) {
            times_[j] = timeFromReference(dates[j-1]);
            QL_REQUIRE(times_[j]>times_[j-1],
                       "dates must be sorted unique!");
            variances_[j] = times_[j] *
                blackVolCurve[j-1]*blackVolCurve[j-1];
            QL_REQUIRE(variances_[j]>=variances_[j-1]
                       || !forceMonotoneVariance,
                       "variance must be non-decreasing");
        }
        // default: linear interpolation
        setInterpolation<Linear>();
    }
Member Function Documentation
void QuantLib::BlackVarianceCurve::accept (AcyclicVisitor & v) [inline, virtual]
Reimplemented from QuantLib::BlackVarianceTermStructure.
Definition at line 103 of file blackvariancecurve.hpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Visitor< T >::visit().
{
        Visitor<BlackVarianceCurve>* v1 =
            dynamic_cast<Visitor<BlackVarianceCurve>*>(&v);
        if (v1 != 0)
            v1->visit(*this);
        else
            BlackVarianceTermStructure::accept(v);
    }
Real QuantLib::BlackVarianceCurve::blackVarianceImpl (Time t, Real strike) const [protected, virtual]
Black variance calculation.
Implements QuantLib::BlackVolTermStructure.
Definition at line 64 of file blackvariancecurve.cpp.
References times_, and varianceCurve_.
{
        if (t<=times_.back()) {
            return varianceCurve_(t, true);
        } else {
            // extrapolate with flat vol
            return varianceCurve_(times_.back(), true)*t/times_.back();
        }
    }
DayCounter QuantLib::BlackVarianceCurve::dayCounter () const [inline, virtual]
the day counter used for date/time conversion
Reimplemented from QuantLib::TermStructure.
Definition at line 56 of file blackvariancecurve.hpp.
References dayCounter_.
Referenced by QuantLib::CapletVarianceCurve::dayCounter().
{ return dayCounter_; }
Date QuantLib::BlackVarianceCurve::maxDate () const [inline, virtual]
the latest date for which the curve can return values
Implements QuantLib::TermStructure.
Definition at line 91 of file blackvariancecurve.hpp.
References maxDate_.
Referenced by QuantLib::CapletVarianceCurve::maxDate().
{
        return maxDate_;
    }
Real QuantLib::BlackVarianceCurve::maxStrike () const [inline, virtual]
the maximum strike for which the term structure can return vols
Implements QuantLib::VolatilityTermStructure.
Definition at line 99 of file blackvariancecurve.hpp.
References QL_MAX_REAL.
Referenced by QuantLib::CapletVarianceCurve::maxStrike().
{
        return QL_MAX_REAL;
    }
Real QuantLib::BlackVarianceCurve::minStrike () const [inline, virtual]
the minimum strike for which the term structure can return vols
Implements QuantLib::VolatilityTermStructure.
Definition at line 95 of file blackvariancecurve.hpp.
References QL_MIN_REAL.
Referenced by QuantLib::CapletVarianceCurve::minStrike().
{
        return QL_MIN_REAL;
    }
template<class Interpolator > void QuantLib::BlackVarianceCurve::setInterpolation (const Interpolator & i = Interpolator()) [inline]
Definition at line 67 of file blackvariancecurve.hpp.
References QuantLib::Observable::notifyObservers(), times_, QuantLib::Interpolation::update(), varianceCurve_, and variances_.
{
            varianceCurve_ = i.interpolate(times_.begin(), times_.end(),
                                           variances_.begin());
            varianceCurve_.update();
            notifyObservers();
        }
Member Data Documentation
DayCounter QuantLib::BlackVarianceCurve::dayCounter_ [private]
Reimplemented from QuantLib::TermStructure.
Definition at line 81 of file blackvariancecurve.hpp.
Referenced by dayCounter().
Date QuantLib::BlackVarianceCurve::maxDate_ [private]
Definition at line 82 of file blackvariancecurve.hpp.
Referenced by maxDate().
std::vector<Time> QuantLib::BlackVarianceCurve::times_ [private]
Definition at line 83 of file blackvariancecurve.hpp.
Referenced by BlackVarianceCurve(), blackVarianceImpl(), and setInterpolation().
Interpolation QuantLib::BlackVarianceCurve::varianceCurve_ [private]
Definition at line 85 of file blackvariancecurve.hpp.
Referenced by blackVarianceImpl(), and setInterpolation().
std::vector<Real> QuantLib::BlackVarianceCurve::variances_ [private]
Definition at line 84 of file blackvariancecurve.hpp.
Referenced by BlackVarianceCurve(), and setInterpolation().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/equityfx/blackvariancecurve.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/equityfx/blackvariancecurve.cpp