QuantLib: QuantLib::AnalyticBarrierEngine Class Reference
QuantLib::AnalyticBarrierEngine Class Reference
Pricing engine for barrier options using analytical formulae.
#include <analyticbarrierengine.hpp>
Public Member Functions
AnalyticBarrierEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > &process)
void calculate () const
Private Member Functions
Real underlying () const
Real strike () const
Time residualTime () const
Volatility volatility () const
Real barrier () const
Real rebate () const
Real stdDeviation () const
Rate riskFreeRate () const
DiscountFactor riskFreeDiscount () const
Rate dividendYield () const
DiscountFactor dividendDiscount () const
Rate mu () const
Real muSigma () const
Real A (Real phi) const
Real B (Real phi) const
Real C (Real eta, Real phi) const
Real D (Real eta, Real phi) const
Real E (Real eta) const
Real F (Real eta) const
Private Attributes
boost::shared_ptr
< GeneralizedBlackScholesProcess > process_
CumulativeNormalDistribution f_
Detailed Description
Pricing engine for barrier options using analytical formulae.
The formulas are taken from "Option pricing formulas", E.G. Haug, McGraw-Hill, p.69 and following.
Test:
the correctness of the returned value is tested by reproducing results available in literature.
Definition at line 46 of file analyticbarrierengine.hpp.
Constructor & Destructor Documentation
QuantLib::AnalyticBarrierEngine::AnalyticBarrierEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > & process)
Definition at line 29 of file analyticbarrierengine.cpp.
References process_, and QuantLib::Observer::registerWith().
    : process_(process) {
        registerWith(process_);
    }
Member Function Documentation
Real QuantLib::AnalyticBarrierEngine::A (Real phi) const [private]
Definition at line 171 of file analyticbarrierengine.cpp.
References dividendDiscount(), f_, muSigma(), riskFreeDiscount(), stdDeviation(), strike(), underlying(), and QuantLib::x1.
Referenced by calculate().
{
        Real x1 =
            std::log(underlying()/strike())/stdDeviation() + muSigma();
        Real N1 = f_(phi*x1);
        Real N2 = f_(phi*(x1-stdDeviation()));
        return phi*(underlying() * dividendDiscount() * N1
                    - strike() * riskFreeDiscount() * N2);
    }
Real QuantLib::AnalyticBarrierEngine::B (Real phi) const [private]
Definition at line 180 of file analyticbarrierengine.cpp.
References barrier(), dividendDiscount(), f_, muSigma(), riskFreeDiscount(), stdDeviation(), strike(), underlying(), and QuantLib::x2.
Referenced by calculate().
{
        Real x2 =
            std::log(underlying()/barrier())/stdDeviation() + muSigma();
        Real N1 = f_(phi*x2);
        Real N2 = f_(phi*(x2-stdDeviation()));
        return phi*(underlying() * dividendDiscount() * N1
                    - strike() * riskFreeDiscount() * N2);
    }
Real QuantLib::AnalyticBarrierEngine::barrier () const [private]
Definition at line 136 of file analyticbarrierengine.cpp.
References QuantLib::GenericEngine< BarrierOption::arguments, BarrierOption::results >::arguments_, and QuantLib::BarrierOption::arguments::barrier.
Referenced by B(), C(), calculate(), D(), E(), and F().
{
        return arguments_.barrier;
    }
Real QuantLib::AnalyticBarrierEngine::C (Real eta, Real phi) const [private]
Definition at line 189 of file analyticbarrierengine.cpp.
References barrier(), dividendDiscount(), f_, mu(), muSigma(), QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow(), riskFreeDiscount(), stdDeviation(), strike(), and underlying().
Referenced by calculate().
{
        Real HS = barrier()/underlying();
        Real powHS0 = std::pow(HS, 2 * mu());
        Real powHS1 = powHS0 * HS * HS;
        Real y1 = std::log(barrier()*HS/strike())/stdDeviation() + muSigma();
        Real N1 = f_(eta*y1);
        Real N2 = f_(eta*(y1-stdDeviation()));
        return phi*(underlying() * dividendDiscount() * powHS1 * N1
                    - strike() * riskFreeDiscount() * powHS0 * N2);
    }
void QuantLib::AnalyticBarrierEngine::calculate () const [virtual]
Implements QuantLib::PricingEngine.
Definition at line 35 of file analyticbarrierengine.cpp.
References A(), QuantLib::GenericEngine< BarrierOption::arguments, BarrierOption::results >::arguments_, B(), barrier(), QuantLib::BarrierOption::arguments::barrierType, C(), QuantLib::Option::Call, D(), QuantLib::Barrier::DownIn, QuantLib::Barrier::DownOut, E(), F(), process_, QuantLib::Option::Put, QL_FAIL, QL_REQUIRE, QuantLib::GenericEngine< BarrierOption::arguments, BarrierOption::results >::results_, strike(), QuantLib::BarrierOption::engine::triggered(), QuantLib::Barrier::UpIn, QuantLib::Barrier::UpOut, and QuantLib::Instrument::results::value.
{
        boost::shared_ptr<PlainVanillaPayoff> payoff =
            boost::dynamic_pointer_cast<PlainVanillaPayoff>(arguments_.payoff);
        QL_REQUIRE(payoff, "non-plain payoff given");
        QL_REQUIRE(payoff->strike()>0.0,
                   "strike must be positive");
        Real strike = payoff->strike();
        Real spot = process_->x0();
        QL_REQUIRE(spot >= 0.0, "negative or null underlying given");
        QL_REQUIRE(!triggered(spot), "barrier touched");
        Barrier::Type barrierType = arguments_.barrierType;
        switch (payoff->optionType()) {
          case Option::Call:
            switch (barrierType) {
              case Barrier::DownIn:
                if (strike >= barrier())
                    results_.value = C(1,1) + E(1);
                else
                    results_.value = A(1) - B(1) + D(1,1) + E(1);
                break;
              case Barrier::UpIn:
                if (strike >= barrier())
                    results_.value = A(1) + E(-1);
                else
                    results_.value = B(1) - C(-1,1) + D(-1,1) + E(-1);
                break;
              case Barrier::DownOut:
                if (strike >= barrier())
                    results_.value = A(1) - C(1,1) + F(1);
                else
                    results_.value = B(1) - D(1,1) + F(1);
                break;
              case Barrier::UpOut:
                if (strike >= barrier())
                    results_.value = F(-1);
                else
                    results_.value = A(1) - B(1) + C(-1,1) - D(-1,1) + F(-1);
                break;
            }
            break;
          case Option::Put:
            switch (barrierType) {
              case Barrier::DownIn:
                if (strike >= barrier())
                    results_.value = B(-1) - C(1,-1) + D(1,-1) + E(1);
                else
                    results_.value = A(-1) + E(1);
                break;
              case Barrier::UpIn:
                if (strike >= barrier())
                    results_.value = A(-1) - B(-1) + D(-1,-1) + E(-1);
                else
                    results_.value = C(-1,-1) + E(-1);
                break;
              case Barrier::DownOut:
                if (strike >= barrier())
                    results_.value = A(-1) - B(-1) + C(1,-1) - D(1,-1) + F(1);
                else
                    results_.value = F(1);
                break;
              case Barrier::UpOut:
                if (strike >= barrier())
                    results_.value = B(-1) - D(-1,-1) + F(-1);
                else
                    results_.value = A(-1) - C(-1,-1) + F(-1);
                break;
            }
            break;
          default:
            QL_FAIL("unknown type");
        }
    }
Real QuantLib::AnalyticBarrierEngine::D (Real eta, Real phi) const [private]
Definition at line 200 of file analyticbarrierengine.cpp.
References barrier(), dividendDiscount(), f_, mu(), muSigma(), QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow(), riskFreeDiscount(), stdDeviation(), strike(), and underlying().
Referenced by calculate().
{
        Real HS = barrier()/underlying();
        Real powHS0 = std::pow(HS, 2 * mu());
        Real powHS1 = powHS0 * HS * HS;
        Real y2 = std::log(barrier()/underlying())/stdDeviation() + muSigma();
        Real N1 = f_(eta*y2);
        Real N2 = f_(eta*(y2-stdDeviation()));
        return phi*(underlying() * dividendDiscount() * powHS1 * N1
                    - strike() * riskFreeDiscount() * powHS0 * N2);
    }
DiscountFactor QuantLib::AnalyticBarrierEngine::dividendDiscount () const [private]
Definition at line 158 of file analyticbarrierengine.cpp.
References process_, and residualTime().
Referenced by A(), B(), C(), and D().
{
        return process_->dividendYield()->discount(residualTime());
    }
Rate QuantLib::AnalyticBarrierEngine::dividendYield () const [private]
Definition at line 153 of file analyticbarrierengine.cpp.
References QuantLib::Continuous, QuantLib::NoFrequency, process_, and residualTime().
Referenced by mu().
{
        return process_->dividendYield()->zeroRate(residualTime(),
                                                   Continuous, NoFrequency);
    }
Real QuantLib::AnalyticBarrierEngine::E (Real eta) const [private]
Definition at line 211 of file analyticbarrierengine.cpp.
References barrier(), f_, mu(), muSigma(), QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow(), rebate(), riskFreeDiscount(), stdDeviation(), underlying(), and QuantLib::x2.
Referenced by calculate().
{
        if (rebate() > 0) {
            Real powHS0 = std::pow(barrier()/underlying(), 2 * mu());
            Real x2 =
                std::log(underlying()/barrier())/stdDeviation() + muSigma();
            Real y2 =
                std::log(barrier()/underlying())/stdDeviation() + muSigma();
            Real N1 = f_(eta*(x2 - stdDeviation()));
            Real N2 = f_(eta*(y2 - stdDeviation()));
            return rebate() * riskFreeDiscount() * (N1 - powHS0 * N2);
        } else {
            return 0.0;
        }
    }
Real QuantLib::AnalyticBarrierEngine::F (Real eta) const [private]
Definition at line 226 of file analyticbarrierengine.cpp.
References barrier(), f_, mu(), QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow(), rebate(), riskFreeRate(), stdDeviation(), underlying(), and volatility().
Referenced by calculate().
{
        if (rebate() > 0) {
            Rate m = mu();
            Volatility vol = volatility();
            Real lambda = std::sqrt(m*m + 2.0*riskFreeRate()/(vol * vol));
            Real HS = barrier()/underlying();
            Real powHSplus = std::pow(HS, m + lambda);
            Real powHSminus = std::pow(HS, m - lambda);
            Real sigmaSqrtT = stdDeviation();
            Real z = std::log(barrier()/underlying())/sigmaSqrtT
                + lambda * sigmaSqrtT;
            Real N1 = f_(eta * z);
            Real N2 = f_(eta * (z - 2.0 * lambda * sigmaSqrtT));
            return rebate() * (powHSplus * N1 + powHSminus * N2);
        } else {
            return 0.0;
        }
    }
Rate QuantLib::AnalyticBarrierEngine::mu () const [private]
Definition at line 162 of file analyticbarrierengine.cpp.
References dividendYield(), riskFreeRate(), and volatility().
Referenced by C(), D(), E(), F(), and muSigma().
{
        Volatility vol = volatility();
        return (riskFreeRate() - dividendYield())/(vol * vol) - 0.5;
    }
Real QuantLib::AnalyticBarrierEngine::muSigma () const [private]
Definition at line 167 of file analyticbarrierengine.cpp.
References mu(), and stdDeviation().
Referenced by A(), B(), C(), D(), and E().
{
        return (1 + mu()) * stdDeviation();
    }
Real QuantLib::AnalyticBarrierEngine::rebate () const [private]
Definition at line 140 of file analyticbarrierengine.cpp.
References QuantLib::GenericEngine< BarrierOption::arguments, BarrierOption::results >::arguments_, and QuantLib::BarrierOption::arguments::rebate.
Referenced by E(), and F().
{
        return arguments_.rebate;
    }
Time QuantLib::AnalyticBarrierEngine::residualTime () const [private]
Definition at line 124 of file analyticbarrierengine.cpp.
References QuantLib::GenericEngine< BarrierOption::arguments, BarrierOption::results >::arguments_, and process_.
Referenced by dividendDiscount(), dividendYield(), riskFreeDiscount(), riskFreeRate(), stdDeviation(), and volatility().
{
        return process_->time(arguments_.exercise->lastDate());
    }
DiscountFactor QuantLib::AnalyticBarrierEngine::riskFreeDiscount () const [private]
Definition at line 149 of file analyticbarrierengine.cpp.
References process_, and residualTime().
Referenced by A(), B(), C(), D(), and E().
{
        return process_->riskFreeRate()->discount(residualTime());
    }
Rate QuantLib::AnalyticBarrierEngine::riskFreeRate () const [private]
Definition at line 144 of file analyticbarrierengine.cpp.
References QuantLib::Continuous, QuantLib::NoFrequency, process_, and residualTime().
Referenced by F(), and mu().
{
        return process_->riskFreeRate()->zeroRate(residualTime(), Continuous,
                                                  NoFrequency);
    }
Real QuantLib::AnalyticBarrierEngine::stdDeviation () const [private]
Definition at line 132 of file analyticbarrierengine.cpp.
References residualTime(), and volatility().
Referenced by A(), B(), C(), D(), E(), F(), and muSigma().
{
        return volatility() * std::sqrt(residualTime());
    }
Real QuantLib::AnalyticBarrierEngine::strike () const [private]
Definition at line 117 of file analyticbarrierengine.cpp.
References QuantLib::GenericEngine< BarrierOption::arguments, BarrierOption::results >::arguments_, and QL_REQUIRE.
Referenced by A(), B(), C(), calculate(), D(), and volatility().
{
        boost::shared_ptr<PlainVanillaPayoff> payoff =
            boost::dynamic_pointer_cast<PlainVanillaPayoff>(arguments_.payoff);
        QL_REQUIRE(payoff, "non-plain payoff given");
        return payoff->strike();
    }
Real QuantLib::AnalyticBarrierEngine::underlying () const [private]
Definition at line 113 of file analyticbarrierengine.cpp.
References process_.
Referenced by A(), B(), C(), D(), E(), and F().
{
        return process_->x0();
    }
Volatility QuantLib::AnalyticBarrierEngine::volatility () const [private]
Definition at line 128 of file analyticbarrierengine.cpp.
References process_, residualTime(), and strike().
Referenced by F(), mu(), and stdDeviation().
{
        return process_->blackVolatility()->blackVol(residualTime(), strike());
    }
Member Data Documentation
CumulativeNormalDistribution QuantLib::AnalyticBarrierEngine::f_ [private]
Definition at line 53 of file analyticbarrierengine.hpp.
Referenced by A(), B(), C(), D(), E(), and F().
boost::shared_ptr<GeneralizedBlackScholesProcess> QuantLib::AnalyticBarrierEngine::process_ [private]
Definition at line 52 of file analyticbarrierengine.hpp.
Referenced by AnalyticBarrierEngine(), calculate(), dividendDiscount(), dividendYield(), residualTime(), riskFreeDiscount(), riskFreeRate(), underlying(), and volatility().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/barrier/analyticbarrierengine.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/barrier/analyticbarrierengine.cpp