QuantLib: QuantLib::ReplicatingVarianceSwapEngine Class Reference
QuantLib::ReplicatingVarianceSwapEngine Class Reference
Variance-swap pricing engine using replicating cost,.
#include <replicatingvarianceswapengine.hpp>
Public Types
typedef std::vector< std::pair
< boost::shared_ptr
< StrikedTypePayoff >, Real > > weights_type
Public Member Functions
ReplicatingVarianceSwapEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > &process, Real dk=5.0, const std::vector< Real > &callStrikes=std::vector< Real >(), const std::vector< Real > &putStrikes=std::vector< Real >())
void calculate () const
Protected Member Functions
void computeOptionWeights (const std::vector< Real > &, const Option::Type, weights_type &optionWeights) const
Real computeLogPayoff (const Real, const Real) const
Real computeReplicatingPortfolio (const weights_type &optionWeights) const
Rate riskFreeRate () const
DiscountFactor riskFreeDiscount () const
Real underlying () const
Time residualTime () const
Private Attributes
boost::shared_ptr
< GeneralizedBlackScholesProcess > process_
Real dk_
std::vector< Real > callStrikes_
std::vector< Real > putStrikes_
Detailed Description
Variance-swap pricing engine using replicating cost,.
as described in Demeterfi, Derman, Kamal & Zou, "A Guide to Volatility and Variance Swaps", 1999
Test:
returned variances verified against results from literature
Definition at line 43 of file replicatingvarianceswapengine.hpp.
Member Typedef Documentation
typedef std::vector<std::pair< boost::shared_ptr<StrikedTypePayoff>, Real> > QuantLib::ReplicatingVarianceSwapEngine::weights_type
Definition at line 46 of file replicatingvarianceswapengine.hpp.
Constructor & Destructor Documentation
QuantLib::ReplicatingVarianceSwapEngine::ReplicatingVarianceSwapEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > & process, Real dk = 5.0, const std::vector< Real > & callStrikes = std::vector<Real>(), const std::vector< Real > & putStrikes = std::vector<Real>()) [inline]
Definition at line 75 of file replicatingvarianceswapengine.hpp.
References process_, and QL_REQUIRE.
    : process_(process), dk_(dk),
      callStrikes_(callStrikes), putStrikes_(putStrikes) {
        QL_REQUIRE(process_, "no process given");
        QL_REQUIRE(!callStrikes.empty() && !putStrikes.empty(),
                   "no strike(s) given");
        QL_REQUIRE(*std::min_element(putStrikes.begin(),putStrikes.end())>0.0,
                   "min put strike must be positive");
        QL_REQUIRE(*std::min_element(callStrikes.begin(), callStrikes.end())==
                   *std::max_element(putStrikes.begin(), putStrikes.end()),
                   "min call and max put strikes differ");
    }
Member Function Documentation
void QuantLib::ReplicatingVarianceSwapEngine::calculate () const [inline, virtual]
Implements QuantLib::PricingEngine.
Definition at line 185 of file replicatingvarianceswapengine.hpp.
References QuantLib::Instrument::results::additionalResults, QuantLib::GenericEngine< VarianceSwap::arguments, VarianceSwap::results >::arguments_, QuantLib::Option::Call, callStrikes_, computeOptionWeights(), computeReplicatingPortfolio(), QuantLib::Position::Long, QuantLib::VarianceSwap::arguments::maturityDate, QuantLib::VarianceSwap::arguments::notional, QuantLib::VarianceSwap::arguments::position, process_, QuantLib::Option::Put, putStrikes_, QL_FAIL, QuantLib::GenericEngine< VarianceSwap::arguments, VarianceSwap::results >::results_, riskFreeDiscount(), QuantLib::Position::Short, QuantLib::VarianceSwap::arguments::strike, QuantLib::Instrument::results::value, and QuantLib::VarianceSwap::results::variance.
{
        weights_type optionWeigths;
        computeOptionWeights(callStrikes_, Option::Call, optionWeigths);
        computeOptionWeights(putStrikes_, Option::Put, optionWeigths);
        results_.variance = computeReplicatingPortfolio(optionWeigths);
        DiscountFactor riskFreeDiscount =
            process_->riskFreeRate()->discount(arguments_.maturityDate);
        Real multiplier;
        switch (arguments_.position) {
          case Position::Long:
            multiplier = 1.0;
            break;
          case Position::Short:
            multiplier = -1.0;
            break;
          default:
            QL_FAIL("Unknown position");
        }
        results_.value = multiplier * riskFreeDiscount * arguments_.notional *
            (results_.variance - arguments_.strike);
        results_.additionalResults["optionWeights"] = optionWeigths;
    }
Real QuantLib::ReplicatingVarianceSwapEngine::computeLogPayoff (const Real strike, const Real callPutStrikeBoundary) const [inline, protected]
Definition at line 148 of file replicatingvarianceswapengine.hpp.
References anonymous_namespace{interpolations.cpp}::f(), and residualTime().
Referenced by computeOptionWeights().
{
        Real f = callPutStrikeBoundary;
        return (2.0/residualTime()) * (((strike - f)/f) - std::log(strike/f));
    }
void QuantLib::ReplicatingVarianceSwapEngine::computeOptionWeights (const std::vector< Real > & availStrikes, const Option::Type type, weights_type & optionWeights) const [inline, protected]
Definition at line 94 of file replicatingvarianceswapengine.hpp.
References QuantLib::Option::Call, computeLogPayoff(), dk_, anonymous_namespace{interpolations.cpp}::f(), QuantLib::Option::Put, and QL_FAIL.
Referenced by calculate().
{
        if (availStrikes.empty())
            return;
        std::vector<Real> strikes = availStrikes;
        // add end-strike for piecewise approximation
        switch (type) {
          case Option::Call:
            std::sort(strikes.begin(), strikes.end());
            strikes.push_back(strikes.back() + dk_);
            break;
          case Option::Put:
            std::sort(strikes.begin(), strikes.end(), std::greater<Real>());
            strikes.push_back(std::max(strikes.back() - dk_, 0.0));
            break;
          default:
            QL_FAIL("invalid option type");
        }
        // remove duplicate strikes
        std::vector<Real>::iterator last =
            std::unique(strikes.begin(), strikes.end());
        strikes.erase(last, strikes.end());
        // compute weights
        Real f = strikes.front();
        Real slope, prevSlope = 0.0;
        for (std::vector<Real>::const_iterator k=strikes.begin();
             // added end-strike discarded
             k<strikes.end()-1;
             k++) {
            slope = std::fabs((computeLogPayoff(*(k+1), f) -
                               computeLogPayoff(*k, f))/
                              (*(k+1) - *k));
            boost::shared_ptr<StrikedTypePayoff> payoff(
                                            new PlainVanillaPayoff(type, *k));
            if ( k == strikes.begin() )
                optionWeights.push_back(std::make_pair(payoff,slope));
            else
                optionWeights.push_back(
                                   std::make_pair(payoff, slope - prevSlope));
            prevSlope = slope;
        }
    }
Real QuantLib::ReplicatingVarianceSwapEngine::computeReplicatingPortfolio (const weights_type & optionWeights) const [inline, protected]
Definition at line 157 of file replicatingvarianceswapengine.hpp.
References QuantLib::GenericEngine< VarianceSwap::arguments, VarianceSwap::results >::arguments_, anonymous_namespace{interpolations.cpp}::f(), QuantLib::VarianceSwap::arguments::maturityDate, QuantLib::Instrument::NPV(), process_, residualTime(), riskFreeDiscount(), riskFreeRate(), QuantLib::Instrument::setPricingEngine(), and underlying().
Referenced by calculate().
{
        boost::shared_ptr<Exercise> exercise(
                               new EuropeanExercise(arguments_.maturityDate));
        boost::shared_ptr<PricingEngine> optionEngine(
                                        new AnalyticEuropeanEngine(process_));
        Real optionsValue = 0.0;
        for (weights_type::const_iterator i = optionWeights.begin();
             i < optionWeights.end(); ++i) {
            boost::shared_ptr<StrikedTypePayoff> payoff = i->first;
            EuropeanOption option(payoff, exercise);
            option.setPricingEngine(optionEngine);
            Real weight = i->second;
            optionsValue += option.NPV() * weight;
        }
        Real f = optionWeights.front().first->strike();
        return 2.0 * riskFreeRate() -
            2.0/residualTime() *
            (((underlying()/riskFreeDiscount() - f)/f) +
             std::log(f/underlying())) +
            optionsValue/riskFreeDiscount();
    }
Time QuantLib::ReplicatingVarianceSwapEngine::residualTime () const [inline, protected]
Definition at line 217 of file replicatingvarianceswapengine.hpp.
References QuantLib::GenericEngine< VarianceSwap::arguments, VarianceSwap::results >::arguments_, QuantLib::VarianceSwap::arguments::maturityDate, and process_.
Referenced by computeLogPayoff(), computeReplicatingPortfolio(), riskFreeDiscount(), and riskFreeRate().
{
        return process_->time(arguments_.maturityDate);
    }
DiscountFactor QuantLib::ReplicatingVarianceSwapEngine::riskFreeDiscount () const [inline, protected]
Definition at line 229 of file replicatingvarianceswapengine.hpp.
References process_, and residualTime().
Referenced by calculate(), and computeReplicatingPortfolio().
{
        return process_->riskFreeRate()->discount(residualTime());
    }
Rate QuantLib::ReplicatingVarianceSwapEngine::riskFreeRate () const [inline, protected]
Definition at line 222 of file replicatingvarianceswapengine.hpp.
References QuantLib::Continuous, QuantLib::NoFrequency, process_, and residualTime().
Referenced by computeReplicatingPortfolio().
{
        return process_->riskFreeRate()->zeroRate(residualTime(), Continuous,
                                                  NoFrequency, true);
    }
Real QuantLib::ReplicatingVarianceSwapEngine::underlying () const [inline, protected]
Definition at line 212 of file replicatingvarianceswapengine.hpp.
References process_.
Referenced by computeReplicatingPortfolio().
{
        return process_->x0();
    }
Member Data Documentation
std::vector<Real> QuantLib::ReplicatingVarianceSwapEngine::callStrikes_ [private]
Definition at line 69 of file replicatingvarianceswapengine.hpp.
Referenced by calculate().
Real QuantLib::ReplicatingVarianceSwapEngine::dk_ [private]
Definition at line 68 of file replicatingvarianceswapengine.hpp.
Referenced by computeOptionWeights().
boost::shared_ptr<GeneralizedBlackScholesProcess> QuantLib::ReplicatingVarianceSwapEngine::process_ [private]
Definition at line 67 of file replicatingvarianceswapengine.hpp.
Referenced by calculate(), computeReplicatingPortfolio(), ReplicatingVarianceSwapEngine(), residualTime(), riskFreeDiscount(), riskFreeRate(), and underlying().
std::vector<Real> QuantLib::ReplicatingVarianceSwapEngine::putStrikes_ [private]
Definition at line 69 of file replicatingvarianceswapengine.hpp.
Referenced by calculate().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/forward/replicatingvarianceswapengine.hpp