QuantLib: QuantLib::quadratic Class Reference
QuantLib::quadratic Class Reference
#include <quadratic.hpp>
Public Member Functions
quadratic (Real a, Real b, Real c)
Real turningPoint () const
Real valueAtTurningPoint () const
Real operator() (Real x) const
Real discriminant () const
bool roots (Real &x, Real &y) const
Private Attributes
Real a_
Real b_
Real c_
Detailed Description
Definition at line 32 of file quadratic.hpp.
Constructor & Destructor Documentation
QuantLib::quadratic::quadratic (Real a, Real b, Real c)
Definition at line 25 of file quadratic.cpp.
: a_(a), b_(b), c_(c) {}
Member Function Documentation
Real QuantLib::quadratic::discriminant () const
Definition at line 39 of file quadratic.cpp.
References a_, b_, and c_.
Referenced by roots().
{
        return b_*b_-4*a_*c_;
    }
Real QuantLib::quadratic::operator() (Real x) const
Definition at line 35 of file quadratic.cpp.
References a_, b_, and c_.
{
        return x*(x*a_+b_)+c_;
    }
bool QuantLib::quadratic::roots (Real & x, Real & y) const
Definition at line 44 of file quadratic.cpp.
References a_, b_, anonymous_namespace{marketmodel.cpp}::d, discriminant(), and turningPoint().
Referenced by QuantLib::AlphaFinder::finalPart(), and QuantLib::anonymous_namespace{capletcoterminalmaxhomogeneity.cpp}::singleRateClosestPointFinder().
{
        Real d = discriminant();
        if (d<0) {
            x = y = turningPoint();
            return false;
        }
        d = std::sqrt(d);
        x = (-b_ -  d)/(2*a_);
        y = (-b_ + d)/(2*a_);
        return true;
    }
Real QuantLib::quadratic::turningPoint () const
Definition at line 27 of file quadratic.cpp.
References a_, and b_.
Referenced by roots(), and valueAtTurningPoint().
{
        return -b_/(2.0*a_);
    }
Real QuantLib::quadratic::valueAtTurningPoint () const
Definition at line 31 of file quadratic.cpp.
References turningPoint().
Referenced by QuantLib::AlphaFinder::valueAtTurningPoint().
{
        return (*this)(turningPoint());
    }
Member Data Documentation
Real QuantLib::quadratic::a_ [private]
Definition at line 43 of file quadratic.hpp.
Referenced by discriminant(), operator()(), roots(), and turningPoint().
Real QuantLib::quadratic::b_ [private]
Definition at line 43 of file quadratic.hpp.
Referenced by discriminant(), operator()(), roots(), and turningPoint().
Real QuantLib::quadratic::c_ [private]
Definition at line 43 of file quadratic.hpp.
Referenced by discriminant(), and operator()().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/quadratic.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/math/quadratic.cpp