QuantLib: QuantLib::QuantoForwardVanillaOption Class Reference
QuantLib::QuantoForwardVanillaOption Class Reference
Quanto version of a forward vanilla option.
#include <quantoforwardvanillaoption.hpp>
Public Types
typedef
ForwardVanillaOption::arguments arguments
typedef QuantoOptionResults
< ForwardVanillaOption::results > results
Public Member Functions
QuantoForwardVanillaOption (Real moneyness, const Date &resetDate, const boost::shared_ptr< StrikedTypePayoff > &, const boost::shared_ptr< Exercise > &)
void fetchResults (const PricingEngine::results *) const
greeks
Real qvega () const
Real qrho () const
Real qlambda () const
Private Member Functions
void setupExpired () const
Private Attributes
Real qvega_
Real qrho_
Real qlambda_
Detailed Description
Quanto version of a forward vanilla option.
Definition at line 35 of file quantoforwardvanillaoption.hpp.
Member Typedef Documentation
typedef ForwardVanillaOption::arguments QuantLib::QuantoForwardVanillaOption::arguments
Reimplemented from QuantLib::ForwardVanillaOption.
Definition at line 37 of file quantoforwardvanillaoption.hpp.
typedef QuantoOptionResults<ForwardVanillaOption::results> QuantLib::QuantoForwardVanillaOption::results
Reimplemented from QuantLib::ForwardVanillaOption.
Definition at line 38 of file quantoforwardvanillaoption.hpp.
Constructor & Destructor Documentation
QuantLib::QuantoForwardVanillaOption::QuantoForwardVanillaOption (Real moneyness, const Date & resetDate, const boost::shared_ptr< StrikedTypePayoff > & payoff, const boost::shared_ptr< Exercise > & exercise)
Definition at line 25 of file quantoforwardvanillaoption.cpp.
    : ForwardVanillaOption(moneyness, resetDate, payoff, exercise) {}
Member Function Documentation
void QuantLib::QuantoForwardVanillaOption::fetchResults (const PricingEngine::results * r) const [virtual]
When a derived result structure is defined for an instrument, this method should be overridden to read from it. This is mandatory in case a pricing engine is used.
Reimplemented from QuantLib::ForwardVanillaOption.
Definition at line 58 of file quantoforwardvanillaoption.cpp.
References QL_ENSURE, QuantLib::QuantoOptionResults< ResultsType >::qlambda, qlambda_, QuantLib::QuantoOptionResults< ResultsType >::qrho, qrho_, QuantLib::QuantoOptionResults< ResultsType >::qvega, and qvega_.
{
        ForwardVanillaOption::fetchResults(r);
        const QuantoForwardVanillaOption::results* quantoResults =
            dynamic_cast<const QuantoForwardVanillaOption::results*>(r);
        QL_ENSURE(quantoResults != 0,
                  "no quanto results returned from pricing engine");
        qrho_    = quantoResults->qrho;
        qvega_   = quantoResults->qvega;
        qlambda_ = quantoResults->qlambda;
    }
Real QuantLib::QuantoForwardVanillaOption::qlambda () const
Definition at line 46 of file quantoforwardvanillaoption.cpp.
References QuantLib::Instrument::calculate(), QL_REQUIRE, and qlambda_.
Referenced by QuantoOptionTest::testForwardGreeks().
{
        calculate();
        QL_REQUIRE(qlambda_ != Null<Real>(),
                   "quanto correlation sensitivity calculation failed");
        return qlambda_;
    }
Real QuantLib::QuantoForwardVanillaOption::qrho () const
Definition at line 39 of file quantoforwardvanillaoption.cpp.
References QuantLib::Instrument::calculate(), QL_REQUIRE, and qrho_.
Referenced by QuantoOptionTest::testForwardGreeks().
{
        calculate();
        QL_REQUIRE(qrho_ != Null<Real>(),
                   "foreign interest rate rho calculation failed");
        return qrho_;
    }
Real QuantLib::QuantoForwardVanillaOption::qvega () const
Definition at line 32 of file quantoforwardvanillaoption.cpp.
References QuantLib::Instrument::calculate(), QL_REQUIRE, and qvega_.
Referenced by QuantoOptionTest::testForwardGreeks().
{
        calculate();
        QL_REQUIRE(qvega_ != Null<Real>(),
                   "exchange rate vega calculation failed");
        return qvega_;
    }
void QuantLib::QuantoForwardVanillaOption::setupExpired () const [private, virtual]
This method must leave the instrument in a consistent state when the expiration condition is met.
Reimplemented from QuantLib::OneAssetOption.
Definition at line 53 of file quantoforwardvanillaoption.cpp.
References qlambda_, qrho_, and qvega_.
{
        ForwardVanillaOption::setupExpired();
        qvega_ = qrho_ = qlambda_ = 0.0;
    }
Member Data Documentation
Real QuantLib::QuantoForwardVanillaOption::qlambda_ [mutable, private]
Definition at line 53 of file quantoforwardvanillaoption.hpp.
Referenced by fetchResults(), qlambda(), and setupExpired().
Real QuantLib::QuantoForwardVanillaOption::qrho_ [mutable, private]
Definition at line 53 of file quantoforwardvanillaoption.hpp.
Referenced by fetchResults(), qrho(), and setupExpired().
Real QuantLib::QuantoForwardVanillaOption::qvega_ [mutable, private]
Definition at line 53 of file quantoforwardvanillaoption.hpp.
Referenced by fetchResults(), qvega(), and setupExpired().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/quantoforwardvanillaoption.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/quantoforwardvanillaoption.cpp