QuantLib: QuantLib::LeastSquareFunction Class Reference
QuantLib::LeastSquareFunction Class Reference
Cost function for least-square problems.
#include <leastsquare.hpp>
Public Member Functions
LeastSquareFunction (LeastSquareProblem &lsp)
Default constructor.
virtual ~LeastSquareFunction ()
Destructor.
virtual Real value (const Array &x) const
compute value of the least square function
virtual Disposable< Array > values (const Array &) const
method to overload to compute the cost function values in x
virtual void gradient (Array &grad_f, const Array &x) const
compute vector of derivatives of the least square function
virtual Real valueAndGradient (Array &grad_f, const Array &x) const
compute value and gradient of the least square function
Protected Attributes
LeastSquareProblem & lsp_
least square problem
Detailed Description
Cost function for least-square problems.
Implements a cost function using the interface provided by the LeastSquareProblem class.
Definition at line 60 of file leastsquare.hpp.
Constructor & Destructor Documentation
QuantLib::LeastSquareFunction::LeastSquareFunction (LeastSquareProblem & lsp) [inline]
Default constructor.
Definition at line 63 of file leastsquare.hpp.
: lsp_(lsp) {}
virtual QuantLib::LeastSquareFunction::~LeastSquareFunction () [inline, virtual]
Destructor.
Definition at line 65 of file leastsquare.hpp.
{}
Member Function Documentation
void QuantLib::LeastSquareFunction::gradient (Array & grad_f, const Array & x) const [virtual]
compute vector of derivatives of the least square function
Reimplemented from QuantLib::CostFunction.
Definition at line 48 of file leastsquare.cpp.
References lsp_, QuantLib::LeastSquareProblem::size(), QuantLib::Array::size(), QuantLib::LeastSquareProblem::targetValueAndGradient(), and QuantLib::transpose().
{
        // size of target and function to fit vectors
        Array target (lsp_.size ()), fct2fit (lsp_.size ());
        // size of gradient matrix
        Matrix grad_fct2fit (lsp_.size (), x.size ());
        // compute its values
        lsp_.targetValueAndGradient(x, grad_fct2fit, target, fct2fit);
        // do the difference
        Array diff = target - fct2fit;
        // compute derivative
        grad_f = -2.0*(transpose(grad_fct2fit)*diff);
    }
Real QuantLib::LeastSquareFunction::value (const Array & x) const [virtual]
compute value of the least square function
Implements QuantLib::CostFunction.
Definition at line 27 of file leastsquare.cpp.
References QuantLib::DotProduct(), lsp_, QuantLib::LeastSquareProblem::size(), and QuantLib::LeastSquareProblem::targetAndValue().
{
        // size of target and function to fit vectors
        Array target(lsp_.size()), fct2fit(lsp_.size());
        // compute its values
        lsp_.targetAndValue(x, target, fct2fit);
        // do the difference
        Array diff = target - fct2fit;
        // and compute the scalar product (square of the norm)
        return DotProduct(diff, diff);
    }
Real QuantLib::LeastSquareFunction::valueAndGradient (Array & grad_f, const Array & x) const [virtual]
compute value and gradient of the least square function
Reimplemented from QuantLib::CostFunction.
Definition at line 62 of file leastsquare.cpp.
References QuantLib::DotProduct(), lsp_, QuantLib::LeastSquareProblem::size(), QuantLib::Array::size(), QuantLib::LeastSquareProblem::targetValueAndGradient(), and QuantLib::transpose().
{
        // size of target and function to fit vectors
        Array target(lsp_.size()), fct2fit(lsp_.size());
        // size of gradient matrix
        Matrix grad_fct2fit(lsp_.size(), x.size());
        // compute its values
        lsp_.targetValueAndGradient(x, grad_fct2fit, target, fct2fit);
        // do the difference
        Array diff = target - fct2fit;
        // compute derivative
        grad_f = -2.0*(transpose(grad_fct2fit)*diff);
        // and compute the scalar product (square of the norm)
        return DotProduct(diff, diff);
    }
Disposable< Array > QuantLib::LeastSquareFunction::values (const Array & x) const [virtual]
method to overload to compute the cost function values in x
Implements QuantLib::CostFunction.
Definition at line 38 of file leastsquare.cpp.
References lsp_, QuantLib::LeastSquareProblem::size(), and QuantLib::LeastSquareProblem::targetAndValue().
{
        // size of target and function to fit vectors
        Array target(lsp_.size()), fct2fit(lsp_.size());
        // compute its values
        lsp_.targetAndValue(x, target, fct2fit);
        // do the difference
        Array diff = target - fct2fit;
        return diff*diff;
    }
Member Data Documentation
LeastSquareProblem& QuantLib::LeastSquareFunction::lsp_ [protected]
least square problem
Definition at line 77 of file leastsquare.hpp.
Referenced by gradient(), value(), valueAndGradient(), and values().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/optimization/leastsquare.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/math/optimization/leastsquare.cpp