QuantLib: QuantLib::CallSpecifiedPathwiseMultiProduct Class Reference
QuantLib::CallSpecifiedPathwiseMultiProduct Class Reference
#include <pathwiseproductcallspecified.hpp>
Public Member Functions
CallSpecifiedPathwiseMultiProduct (const Clone< MarketModelPathwiseMultiProduct > &underlying, const Clone< ExerciseStrategy< CurveState > > &, const Clone< MarketModelPathwiseMultiProduct > &rebate=Clone< MarketModelPathwiseMultiProduct >())
const
MarketModelPathwiseMultiProduct & underlying () const
const ExerciseStrategy
< CurveState > & strategy () const
const
MarketModelPathwiseMultiProduct & rebate () const
void enableCallability ()
void disableCallability ()
MarketModelPathwiseMultiProduct interface
virtual std::vector< Size > suggestedNumeraires () const
virtual const
EvolutionDescription & evolution () const
virtual std::vector< Time > possibleCashFlowTimes () const
virtual Size numberOfProducts () const
virtual Size maxNumberOfCashFlowsPerProductPerStep () const
virtual void reset ()
during simulation put product at start of path
virtual bool nextTimeStep (const CurveState &currentState, std::vector< Size > &numberCashFlowsThisStep, std::vector< std::vector< MarketModelPathwiseMultiProduct::CashFlow > > &cashFlowsGenerated)
return value indicates whether path is finished, TRUE means done
virtual std::auto_ptr
< MarketModelPathwiseMultiProduct > clone () const
returns a newly-allocated copy of itself
virtual bool alreadyDeflated () const
Private Attributes
Clone
< MarketModelPathwiseMultiProduct > underlying_
Clone< ExerciseStrategy
< CurveState > > strategy_
Clone
< MarketModelPathwiseMultiProduct > rebate_
EvolutionDescription evolution_
std::vector< std::valarray
< bool > > isPresent_
std::vector< Time > cashFlowTimes_
Size rebateOffset_
bool wasCalled_
std::vector< Size > dummyCashFlowsThisStep_
std::vector< std::vector
< CashFlow > > dummyCashFlowsGenerated_
Size currentIndex_
bool callable_
Detailed Description
Definition at line 40 of file pathwiseproductcallspecified.hpp.
Constructor & Destructor Documentation
QuantLib::CallSpecifiedPathwiseMultiProduct::CallSpecifiedPathwiseMultiProduct (const Clone< MarketModelPathwiseMultiProduct > & underlying, const Clone< ExerciseStrategy< CurveState > > & strategy, const Clone< MarketModelPathwiseMultiProduct > & rebate = Clone<MarketModelPathwiseMultiProduct>())
Definition at line 29 of file pathwiseproductcallspecified.cpp.
References QuantLib::MarketModelPathwiseMultiProduct::alreadyDeflated(), QuantLib::MarketModelPathwiseMultiProduct::CashFlow::amount, cashFlowTimes_, dummyCashFlowsGenerated_, dummyCashFlowsThisStep_, QuantLib::Clone< T >::empty(), QuantLib::MarketModelPathwiseMultiProduct::evolution(), evolution_, QuantLib::EvolutionDescription::evolutionTimes(), QuantLib::ExerciseStrategy< State >::exerciseTimes(), isPresent_, QuantLib::MarketModelPathwiseMultiProduct::maxNumberOfCashFlowsPerProductPerStep(), QuantLib::mergeTimes(), QuantLib::MarketModelPathwiseMultiProduct::numberOfProducts(), QuantLib::EvolutionDescription::numberOfRates(), QuantLib::MarketModelPathwiseMultiProduct::possibleCashFlowTimes(), QL_REQUIRE, QuantLib::EvolutionDescription::rateTimes(), rebate_, rebateOffset_, QuantLib::ExerciseStrategy< State >::relevantTimes(), strategy(), and underlying_.
Referenced by clone().
            : underlying_(underlying),
            strategy_(strategy),
            rebate_(rebate),
            callable_(true)
        {
            Size products = underlying_->numberOfProducts();
            EvolutionDescription d1 = underlying->evolution();
            const std::vector<Time>& rateTimes1 = d1.rateTimes();
            const std::vector<Time>& evolutionTimes1 = d1.evolutionTimes();
            const std::vector<Time>& exerciseTimes = strategy->exerciseTimes();
            if (!rebate_.empty())
            {
                EvolutionDescription d2 = rebate_->evolution();
                const std::vector<Time>& rateTimes2 = d2.rateTimes();
                QL_REQUIRE(rateTimes1.size() == rateTimes2.size() &&
                    std::equal(rateTimes1.begin(), rateTimes1.end(),
                    rateTimes2.begin()),
                    "incompatible rate times");
                QL_REQUIRE(underlying_->alreadyDeflated() == rebate_->alreadyDeflated(), "incompatible deflations");
            }
            else
            {
                EvolutionDescription description(rateTimes1, exerciseTimes);
                Matrix amounts(products, exerciseTimes.size(), 0.0);
                rebate_ = MarketModelPathwiseCashRebate(description,
                                                        exerciseTimes,
                                                        amounts,
                                                        products);
            }
            std::vector<Time> mergedEvolutionTimes;
            std::vector<std::vector<Time> > allEvolutionTimes(4);
            allEvolutionTimes[0] = evolutionTimes1;
            allEvolutionTimes[1] = exerciseTimes;
            allEvolutionTimes[2] = rebate_->evolution().evolutionTimes();
            allEvolutionTimes[3] = strategy->relevantTimes();
            mergeTimes(allEvolutionTimes,
                mergedEvolutionTimes,
                isPresent_);
            // TODO: add relevant rates
            evolution_ = EvolutionDescription(rateTimes1, mergedEvolutionTimes);
            cashFlowTimes_ = underlying_->possibleCashFlowTimes();
            rebateOffset_ = cashFlowTimes_.size();
            const std::vector<Time> rebateTimes = rebate_->possibleCashFlowTimes();
            cashFlowTimes_.insert(cashFlowTimes_.end(),
                rebateTimes.begin(), rebateTimes.end());
            dummyCashFlowsThisStep_ = std::vector<Size>(products, 0);
            Size n = rebate_->maxNumberOfCashFlowsPerProductPerStep();
            CashFlow modelCashFlow;
            modelCashFlow.amount.resize(d1.numberOfRates()+1);
            dummyCashFlowsGenerated_ =
                std::vector<std::vector<CashFlow> >(products,
                std::vector<CashFlow>(n, modelCashFlow));
        }
Member Function Documentation
bool QuantLib::CallSpecifiedPathwiseMultiProduct::alreadyDeflated () const [virtual]
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 98 of file pathwiseproductcallspecified.cpp.
References QuantLib::MarketModelPathwiseMultiProduct::alreadyDeflated(), and underlying_.
        {
            return underlying_->alreadyDeflated();
        }
std::auto_ptr< MarketModelPathwiseMultiProduct > QuantLib::CallSpecifiedPathwiseMultiProduct::clone () const [virtual]
returns a newly-allocated copy of itself
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 191 of file pathwiseproductcallspecified.cpp.
References CallSpecifiedPathwiseMultiProduct().
        {
            return std::auto_ptr<MarketModelPathwiseMultiProduct>(
                new CallSpecifiedPathwiseMultiProduct(*this));
        }
void QuantLib::CallSpecifiedPathwiseMultiProduct::disableCallability ()
Definition at line 220 of file pathwiseproductcallspecified.cpp.
References callable_.
        {
            callable_ = false;
        }
void QuantLib::CallSpecifiedPathwiseMultiProduct::enableCallability ()
Definition at line 215 of file pathwiseproductcallspecified.cpp.
References callable_.
        {
            callable_ = true;
        }
const EvolutionDescription & QuantLib::CallSpecifiedPathwiseMultiProduct::evolution () const [virtual]
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 109 of file pathwiseproductcallspecified.cpp.
References evolution_.
        {
            return evolution_;
        }
Size QuantLib::CallSpecifiedPathwiseMultiProduct::maxNumberOfCashFlowsPerProductPerStep () const [virtual]
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 126 of file pathwiseproductcallspecified.cpp.
References QuantLib::MarketModelPathwiseMultiProduct::maxNumberOfCashFlowsPerProductPerStep(), rebate_, and underlying_.
        {
            return std::max(underlying_->maxNumberOfCashFlowsPerProductPerStep(),
                rebate_->maxNumberOfCashFlowsPerProductPerStep());
        }
bool QuantLib::CallSpecifiedPathwiseMultiProduct::nextTimeStep (const CurveState & currentState, std::vector< Size > & numberCashFlowsThisStep, std::vector< std::vector< MarketModelPathwiseMultiProduct::CashFlow > > & cashFlowsGenerated) [virtual]
return value indicates whether path is finished, TRUE means done
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 142 of file pathwiseproductcallspecified.cpp.
References callable_, currentIndex_, dummyCashFlowsGenerated_, dummyCashFlowsThisStep_, evolution_, QuantLib::EvolutionDescription::evolutionTimes(), QuantLib::ExerciseStrategy< State >::exercise(), isPresent_, QuantLib::ExerciseStrategy< State >::nextStep(), QuantLib::MarketModelPathwiseMultiProduct::nextTimeStep(), rebate_, rebateOffset_, strategy_, underlying_, and wasCalled_.
        {
            bool isUnderlyingTime = isPresent_[0][currentIndex_];
            bool isExerciseTime = isPresent_[1][currentIndex_];
            bool isRebateTime = isPresent_[2][currentIndex_];
            bool isStrategyRelevantTime = isPresent_[3][currentIndex_];
            bool done = false;
            if (!wasCalled_ && isStrategyRelevantTime)
                strategy_->nextStep(currentState);
            if (!wasCalled_ && isExerciseTime && callable_)
                wasCalled_ = strategy_->exercise(currentState);
            if (wasCalled_)
            {
                if (isRebateTime)
                {
                    done = rebate_->nextTimeStep(currentState,
                        numberCashFlowsThisStep,
                        cashFlowsGenerated);
                    for (Size i=0; i<numberCashFlowsThisStep.size(); ++i)
                        for (Size j=0; j<numberCashFlowsThisStep[i]; ++j)
                            cashFlowsGenerated[i][j].timeIndex += rebateOffset_;
                }
            }
            else
            {
                if (isRebateTime)
                    rebate_->nextTimeStep(currentState,
                    dummyCashFlowsThisStep_,
                    dummyCashFlowsGenerated_);
                if (isUnderlyingTime)
                    done = underlying_->nextTimeStep(currentState,
                    numberCashFlowsThisStep,
                    cashFlowsGenerated);
            }
            ++currentIndex_;
            return done || currentIndex_ == evolution_.evolutionTimes().size();
        }
Size QuantLib::CallSpecifiedPathwiseMultiProduct::numberOfProducts () const [virtual]
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 120 of file pathwiseproductcallspecified.cpp.
References QuantLib::MarketModelPathwiseMultiProduct::numberOfProducts(), and underlying_.
        {
            return underlying_->numberOfProducts();
        }
std::vector< Time > QuantLib::CallSpecifiedPathwiseMultiProduct::possibleCashFlowTimes () const [virtual]
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 115 of file pathwiseproductcallspecified.cpp.
References cashFlowTimes_.
        {
            return cashFlowTimes_;
        }
const MarketModelPathwiseMultiProduct & QuantLib::CallSpecifiedPathwiseMultiProduct::rebate () const
Definition at line 210 of file pathwiseproductcallspecified.cpp.
References rebate_.
        {
            return *rebate_;
        }
void QuantLib::CallSpecifiedPathwiseMultiProduct::reset () [virtual]
during simulation put product at start of path
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 132 of file pathwiseproductcallspecified.cpp.
References currentIndex_, rebate_, QuantLib::ExerciseStrategy< State >::reset(), QuantLib::MarketModelPathwiseMultiProduct::reset(), strategy_, underlying_, and wasCalled_.
        {
            underlying_->reset();
            rebate_->reset();
            strategy_->reset();
            currentIndex_ = 0;
            wasCalled_ = false;
        }
const ExerciseStrategy< CurveState > & QuantLib::CallSpecifiedPathwiseMultiProduct::strategy () const
Definition at line 204 of file pathwiseproductcallspecified.cpp.
References strategy_.
Referenced by CallSpecifiedPathwiseMultiProduct().
        {
            return *strategy_;
        }
std::vector< Size > QuantLib::CallSpecifiedPathwiseMultiProduct::suggestedNumeraires () const [virtual]
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 104 of file pathwiseproductcallspecified.cpp.
References QuantLib::MarketModelPathwiseMultiProduct::suggestedNumeraires(), and underlying_.
        {
            return underlying_->suggestedNumeraires();
        }
const MarketModelPathwiseMultiProduct & QuantLib::CallSpecifiedPathwiseMultiProduct::underlying () const
Definition at line 198 of file pathwiseproductcallspecified.cpp.
References underlying_.
        {
            return *underlying_;
        }
Member Data Documentation
bool QuantLib::CallSpecifiedPathwiseMultiProduct::callable_ [private]
Definition at line 84 of file pathwiseproductcallspecified.hpp.
Referenced by disableCallability(), enableCallability(), and nextTimeStep().
std::vector<Time> QuantLib::CallSpecifiedPathwiseMultiProduct::cashFlowTimes_ [private]
Definition at line 78 of file pathwiseproductcallspecified.hpp.
Referenced by CallSpecifiedPathwiseMultiProduct(), and possibleCashFlowTimes().
Size QuantLib::CallSpecifiedPathwiseMultiProduct::currentIndex_ [private]
Definition at line 83 of file pathwiseproductcallspecified.hpp.
Referenced by nextTimeStep(), and reset().
std::vector<std::vector<CashFlow> > QuantLib::CallSpecifiedPathwiseMultiProduct::dummyCashFlowsGenerated_ [private]
Definition at line 82 of file pathwiseproductcallspecified.hpp.
Referenced by CallSpecifiedPathwiseMultiProduct(), and nextTimeStep().
std::vector<Size> QuantLib::CallSpecifiedPathwiseMultiProduct::dummyCashFlowsThisStep_ [private]
Definition at line 81 of file pathwiseproductcallspecified.hpp.
Referenced by CallSpecifiedPathwiseMultiProduct(), and nextTimeStep().
EvolutionDescription QuantLib::CallSpecifiedPathwiseMultiProduct::evolution_ [private]
Definition at line 76 of file pathwiseproductcallspecified.hpp.
Referenced by CallSpecifiedPathwiseMultiProduct(), evolution(), and nextTimeStep().
std::vector<std::valarray<bool> > QuantLib::CallSpecifiedPathwiseMultiProduct::isPresent_ [private]
Definition at line 77 of file pathwiseproductcallspecified.hpp.
Referenced by CallSpecifiedPathwiseMultiProduct(), and nextTimeStep().
Clone<MarketModelPathwiseMultiProduct> QuantLib::CallSpecifiedPathwiseMultiProduct::rebate_ [private]
Definition at line 75 of file pathwiseproductcallspecified.hpp.
Referenced by CallSpecifiedPathwiseMultiProduct(), maxNumberOfCashFlowsPerProductPerStep(), nextTimeStep(), rebate(), and reset().
Size QuantLib::CallSpecifiedPathwiseMultiProduct::rebateOffset_ [private]
Definition at line 79 of file pathwiseproductcallspecified.hpp.
Referenced by CallSpecifiedPathwiseMultiProduct(), and nextTimeStep().
Clone<ExerciseStrategy<CurveState> > QuantLib::CallSpecifiedPathwiseMultiProduct::strategy_ [private]
Definition at line 74 of file pathwiseproductcallspecified.hpp.
Referenced by nextTimeStep(), reset(), and strategy().
Clone<MarketModelPathwiseMultiProduct> QuantLib::CallSpecifiedPathwiseMultiProduct::underlying_ [private]
Definition at line 73 of file pathwiseproductcallspecified.hpp.
Referenced by alreadyDeflated(), CallSpecifiedPathwiseMultiProduct(), maxNumberOfCashFlowsPerProductPerStep(), nextTimeStep(), numberOfProducts(), reset(), suggestedNumeraires(), and underlying().
bool QuantLib::CallSpecifiedPathwiseMultiProduct::wasCalled_ [private]
Definition at line 80 of file pathwiseproductcallspecified.hpp.
Referenced by nextTimeStep(), and reset().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/products/pathwise/pathwiseproductcallspecified.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/products/pathwise/pathwiseproductcallspecified.cpp