QuantLib: QuantLib::DiscretizedCapFloor Class Reference
QuantLib::DiscretizedCapFloor Class Reference
#include <discretizedcapfloor.hpp>
Public Member Functions
DiscretizedCapFloor (const CapFloor::arguments &args, const Date &referenceDate, const DayCounter &dayCounter)
void reset (Size size)
std::vector< Time > mandatoryTimes () const
Protected Member Functions
void preAdjustValuesImpl ()
void postAdjustValuesImpl ()
Private Attributes
CapFloor::arguments arguments_
std::vector< Time > startTimes_
std::vector< Time > endTimes_
Detailed Description
Definition at line 33 of file discretizedcapfloor.hpp.
Constructor & Destructor Documentation
QuantLib::DiscretizedCapFloor::DiscretizedCapFloor (const CapFloor::arguments & args, const Date & referenceDate, const DayCounter & dayCounter)
Definition at line 25 of file discretizedcapfloor.cpp.
References QuantLib::CapFloor::arguments::endDates, endTimes_, QuantLib::CapFloor::arguments::startDates, startTimes_, and QuantLib::DayCounter::yearFraction().
    : arguments_(args) {
        startTimes_.resize(args.startDates.size());
        for (Size i=0; i<startTimes_.size(); ++i)
            startTimes_[i] = dayCounter.yearFraction(referenceDate,
                                                     args.startDates[i]);
        endTimes_.resize(args.endDates.size());
        for (Size i=0; i<endTimes_.size(); ++i)
            endTimes_[i] = dayCounter.yearFraction(referenceDate,
                                                   args.endDates[i]);
    }
Member Function Documentation
std::vector< Time > QuantLib::DiscretizedCapFloor::mandatoryTimes () const [virtual]
This method returns the times at which the numerical method should stop while rolling back the asset. Typical examples include payment times, exercise times and such.
Note:
The returned values are not guaranteed to be sorted.
Implements QuantLib::DiscretizedAsset.
Definition at line 46 of file discretizedcapfloor.cpp.
References endTimes_, and startTimes_.
Referenced by QuantLib::TreeCapFloorEngine::calculate().
{
        std::vector<Time> times = startTimes_;
        std::copy(endTimes_.begin(), endTimes_.end(),
                  std::back_inserter(times));
        return times;
    }
void QuantLib::DiscretizedCapFloor::postAdjustValuesImpl () [protected, virtual]
This method performs the actual post-adjustment
Reimplemented from QuantLib::DiscretizedAsset.
Definition at line 88 of file discretizedcapfloor.cpp.
References QuantLib::CapFloor::arguments::accrualTimes, arguments_, QuantLib::CapFloor::Cap, QuantLib::CapFloor::arguments::capRates, QuantLib::CapFloor::Collar, endTimes_, QuantLib::CapFloor::Floor, QuantLib::CapFloor::arguments::floorRates, QuantLib::CapFloor::arguments::forwards, QuantLib::CapFloor::arguments::gearings, QuantLib::DiscretizedAsset::isOnTime(), QuantLib::CapFloor::arguments::nominals, startTimes_, QuantLib::CapFloor::arguments::type, and QuantLib::DiscretizedAsset::values_.
{
        for (Size i=0; i<endTimes_.size(); i++) {
            if (isOnTime(endTimes_[i])) {
                if (startTimes_[i] < 0.0) {
                    Real nominal = arguments_.nominals[i];
                    Time accrual = arguments_.accrualTimes[i];
                    Rate fixing = arguments_.forwards[i];
                    Real gearing = arguments_.gearings[i];
                    CapFloor::Type type = arguments_.type;
                    if (type == CapFloor::Cap || type == CapFloor::Collar) {
                        Rate cap = arguments_.capRates[i];
                        Rate capletRate = std::max(fixing-cap, 0.0);
                        values_ += capletRate*accrual*nominal*gearing;
                    }
                    if (type == CapFloor::Floor || type == CapFloor::Collar) {
                        Rate floor = arguments_.floorRates[i];
                        Rate floorletRate = std::max(floor-fixing, 0.0);
                        if (type == CapFloor::Floor)
                            values_ += floorletRate*accrual*nominal*gearing;
                        else
                            values_ -= floorletRate*accrual*nominal*gearing;
                    }
                }
            }
        }
    }
void QuantLib::DiscretizedCapFloor::preAdjustValuesImpl () [protected, virtual]
This method performs the actual pre-adjustment
Reimplemented from QuantLib::DiscretizedAsset.
Definition at line 53 of file discretizedcapfloor.cpp.
References QuantLib::CapFloor::arguments::accrualTimes, arguments_, QuantLib::CapFloor::Cap, QuantLib::CapFloor::arguments::capRates, QuantLib::CapFloor::Collar, endTimes_, QuantLib::CapFloor::Floor, QuantLib::CapFloor::arguments::floorRates, QuantLib::CapFloor::arguments::gearings, QuantLib::DiscretizedAsset::initialize(), QuantLib::DiscretizedAsset::isOnTime(), QuantLib::DiscretizedAsset::method(), QuantLib::CapFloor::arguments::nominals, QuantLib::DiscretizedAsset::rollback(), QuantLib::Array::size(), startTimes_, QuantLib::DiscretizedAsset::time_, QuantLib::CapFloor::arguments::type, QuantLib::DiscretizedAsset::values(), and QuantLib::DiscretizedAsset::values_.
{
        for (Size i=0; i<startTimes_.size(); i++) {
            if (isOnTime(startTimes_[i])) {
                Time end = endTimes_[i];
                Time tenor = arguments_.accrualTimes[i];
                DiscretizedDiscountBond bond;
                bond.initialize(method(), end);
                bond.rollback(time_);
                CapFloor::Type type = arguments_.type;
                Real gearing = arguments_.gearings[i];
                Real nominal = arguments_.nominals[i];
                if ( (type == CapFloor::Cap) ||
                     (type == CapFloor::Collar)) {
                    Real accrual = 1.0 + arguments_.capRates[i]*tenor;
                    Real strike = 1.0/accrual;
                    for (Size j=0; j<values_.size(); j++)
                        values_[j] += nominal*accrual*gearing*
                            std::max<Real>(strike - bond.values()[j], 0.0);
                }
                if ( (type == CapFloor::Floor) ||
                     (type == CapFloor::Collar)) {
                    Real accrual = 1.0 + arguments_.floorRates[i]*tenor;
                    Real strike = 1.0/accrual;
                    Real mult = (type == CapFloor::Floor)?1.0:-1.0;
                    for (Size j=0; j<values_.size(); j++)
                        values_[j] += nominal*accrual*mult*gearing*
                            std::max<Real>(bond.values()[j] - strike, 0.0);
                }
            }
        }
    }
void QuantLib::DiscretizedCapFloor::reset (Size size) [virtual]
This method should initialize the asset values to an Array of the given size and with values depending on the particular asset.
Implements QuantLib::DiscretizedAsset.
Definition at line 41 of file discretizedcapfloor.cpp.
References QuantLib::DiscretizedAsset::adjustValues(), and QuantLib::DiscretizedAsset::values_.
{
        values_ = Array(size, 0.0);
        adjustValues();
    }
Member Data Documentation
CapFloor::arguments QuantLib::DiscretizedCapFloor::arguments_ [private]
Definition at line 44 of file discretizedcapfloor.hpp.
Referenced by postAdjustValuesImpl(), and preAdjustValuesImpl().
std::vector<Time> QuantLib::DiscretizedCapFloor::endTimes_ [private]
Definition at line 46 of file discretizedcapfloor.hpp.
Referenced by DiscretizedCapFloor(), mandatoryTimes(), postAdjustValuesImpl(), and preAdjustValuesImpl().
std::vector<Time> QuantLib::DiscretizedCapFloor::startTimes_ [private]
Definition at line 45 of file discretizedcapfloor.hpp.
Referenced by DiscretizedCapFloor(), mandatoryTimes(), postAdjustValuesImpl(), and preAdjustValuesImpl().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/capfloor/discretizedcapfloor.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/capfloor/discretizedcapfloor.cpp