QuantLib: QuantLib::SwaptionVolatilityDiscrete Class Reference
QuantLib::SwaptionVolatilityDiscrete Class Reference
#include <swaptionvoldiscrete.hpp>
Public Member Functions
SwaptionVolatilityDiscrete (const std::vector< Period > &optionTenors, const std::vector< Period > &swapTenors, Natural settlementDays, const Calendar &cal, BusinessDayConvention bdc, const DayCounter &dc)
SwaptionVolatilityDiscrete (const std::vector< Period > &optionTenors, const std::vector< Period > &swapTenors, const Date &referenceDate, const Calendar &cal, BusinessDayConvention bdc, const DayCounter &dc)
SwaptionVolatilityDiscrete (const std::vector< Date > &optionDates, const std::vector< Period > &swapTenors, const Date &referenceDate, const Calendar &cal, BusinessDayConvention bdc, const DayCounter &dc)
const std::vector< Period > & optionTenors () const
const std::vector< Date > & optionDates () const
const std::vector< Time > & optionTimes () const
const std::vector< Period > & swapTenors () const
const std::vector< Time > & swapLengths () const
Observer interface
void update ()
LazyObject interface
void performCalculations () const
Protected Attributes
Size nOptionTenors_
std::vector< Period > optionTenors_
std::vector< Date > optionDates_
std::vector< Time > optionTimes_
std::vector< Real > optionDatesAsReal_
Interpolation optionInterpolator_
Size nSwapTenors_
std::vector< Period > swapTenors_
std::vector< Time > swapLengths_
Date evaluationDate_
Private Member Functions
void checkOptionTenors () const
void checkOptionDates () const
void checkSwapTenors () const
void initializeOptionDatesAndTimes () const
void initializeOptionTimes () const
void initializeSwapLengths () const
Detailed Description
Definition at line 33 of file swaptionvoldiscrete.hpp.
Constructor & Destructor Documentation
QuantLib::SwaptionVolatilityDiscrete::SwaptionVolatilityDiscrete (const std::vector< Period > & optionTenors, const std::vector< Period > & swapTenors, Natural settlementDays, const Calendar & cal, BusinessDayConvention bdc, const DayCounter & dc)
Definition at line 27 of file swaptionvoldiscrete.cpp.
References checkOptionTenors(), checkSwapTenors(), QuantLib::Extrapolator::enableExtrapolation(), QuantLib::Settings::evaluationDate(), evaluationDate_, initializeOptionDatesAndTimes(), initializeSwapLengths(), QuantLib::Singleton< Settings >::instance(), optionDatesAsReal_, optionInterpolator_, optionTimes_, QuantLib::Observer::registerWith(), and QuantLib::Interpolation::update().
    : SwaptionVolatilityStructure(settlementDays, cal, bdc, dc),
      nOptionTenors_(optionTenors.size()),
      optionTenors_(optionTenors),
      optionDates_(nOptionTenors_),
      optionTimes_(nOptionTenors_),
      optionDatesAsReal_(nOptionTenors_),
      nSwapTenors_(swapTenors.size()),
      swapTenors_(swapTenors),
      swapLengths_(nSwapTenors_) {
        checkOptionTenors();
        initializeOptionDatesAndTimes();
        checkSwapTenors();
        initializeSwapLengths();
        optionInterpolator_= LinearInterpolation(optionTimes_.begin(),
                                                 optionTimes_.end(),
                                                 optionDatesAsReal_.begin());
        optionInterpolator_.update();
        optionInterpolator_.enableExtrapolation();
        registerWith(Settings::instance().evaluationDate());
        evaluationDate_ = Settings::instance().evaluationDate();
    }
QuantLib::SwaptionVolatilityDiscrete::SwaptionVolatilityDiscrete (const std::vector< Period > & optionTenors, const std::vector< Period > & swapTenors, const Date & referenceDate, const Calendar & cal, BusinessDayConvention bdc, const DayCounter & dc)
Definition at line 60 of file swaptionvoldiscrete.cpp.
References checkOptionTenors(), checkSwapTenors(), QuantLib::Extrapolator::enableExtrapolation(), initializeOptionDatesAndTimes(), initializeSwapLengths(), optionDatesAsReal_, optionInterpolator_, optionTimes_, and QuantLib::Interpolation::update().
    : SwaptionVolatilityStructure(referenceDate, cal, bdc, dc),
      nOptionTenors_(optionTenors.size()),
      optionTenors_(optionTenors),
      optionDates_(nOptionTenors_),
      optionTimes_(nOptionTenors_),
      optionDatesAsReal_(nOptionTenors_),
      nSwapTenors_(swapTenors.size()),
      swapTenors_(swapTenors),
      swapLengths_(nSwapTenors_) {
        checkOptionTenors();
        initializeOptionDatesAndTimes();
        checkSwapTenors();
        initializeSwapLengths();
        optionInterpolator_= LinearInterpolation(optionTimes_.begin(),
                                                 optionTimes_.end(),
                                                 optionDatesAsReal_.begin());
        optionInterpolator_.update();
        optionInterpolator_.enableExtrapolation();
    }
QuantLib::SwaptionVolatilityDiscrete::SwaptionVolatilityDiscrete (const std::vector< Date > & optionDates, const std::vector< Period > & swapTenors, const Date & referenceDate, const Calendar & cal, BusinessDayConvention bdc, const DayCounter & dc)
Definition at line 90 of file swaptionvoldiscrete.cpp.
References checkOptionDates(), checkSwapTenors(), QuantLib::Extrapolator::enableExtrapolation(), initializeOptionTimes(), initializeSwapLengths(), optionDatesAsReal_, optionInterpolator_, optionTimes_, and QuantLib::Interpolation::update().
    : SwaptionVolatilityStructure(referenceDate, cal, bdc, dc),
      nOptionTenors_(optionDates.size()),
      optionTenors_(nOptionTenors_),
      optionDates_(optionDates),
      optionTimes_(nOptionTenors_),
      optionDatesAsReal_(nOptionTenors_),
      nSwapTenors_(swapTenors.size()),
      swapTenors_(swapTenors),
      swapLengths_(nSwapTenors_) {
        checkOptionDates();
        initializeOptionTimes();
        checkSwapTenors();
        initializeSwapLengths();
        optionInterpolator_= LinearInterpolation(optionTimes_.begin(),
                                                 optionTimes_.end(),
                                                 optionDatesAsReal_.begin());
        optionInterpolator_.update();
        optionInterpolator_.enableExtrapolation();
    }
Member Function Documentation
void QuantLib::SwaptionVolatilityDiscrete::checkOptionDates () const [private]
Definition at line 120 of file swaptionvoldiscrete.cpp.
References nOptionTenors_, optionDates_, QuantLib::io::ordinal(), QL_REQUIRE, and QuantLib::TermStructure::referenceDate().
Referenced by SwaptionVolatilityDiscrete().
{
        QL_REQUIRE(optionDates_[0]>referenceDate(),
                   "first option date (" << optionDates_[0] <<
                   ") must be greater than reference date (" <<
                   referenceDate() << ")");
        for (Size i=1; i<nOptionTenors_; ++i) {
            QL_REQUIRE(optionDates_[i]>optionDates_[i-1],
                       "non increasing option dates: " << io::ordinal(i) <<
                       " is " << optionDates_[i-1] << ", " << io::ordinal(i+1) <<
                       " is " << optionDates_[i]);
        }
    }
void QuantLib::SwaptionVolatilityDiscrete::checkOptionTenors () const [private]
Definition at line 133 of file swaptionvoldiscrete.cpp.
References QuantLib::Days, nOptionTenors_, optionTenors_, QuantLib::io::ordinal(), and QL_REQUIRE.
Referenced by SwaptionVolatilityDiscrete().
{
        QL_REQUIRE(optionTenors_[0]>0*Days,
                   "first option tenor is negative (" <<
                   optionTenors_[0] << ")");
        for (Size i=1; i<nOptionTenors_; ++i)
            QL_REQUIRE(optionTenors_[i]>optionTenors_[i-1],
                       "non increasing option tenor: " << io::ordinal(i) <<
                       " is " << optionTenors_[i-1] << ", " << io::ordinal(i+1) <<
                       " is " << optionTenors_[i]);
    }
void QuantLib::SwaptionVolatilityDiscrete::checkSwapTenors () const [private]
Definition at line 144 of file swaptionvoldiscrete.cpp.
References QuantLib::Days, nSwapTenors_, QuantLib::io::ordinal(), QL_REQUIRE, and swapTenors_.
Referenced by SwaptionVolatilityDiscrete().
{
        QL_REQUIRE(swapTenors_[0]>0*Days,
                   "first swap tenor is negative (" <<
                   swapTenors_[0] << ")");
        for (Size i=1; i<nSwapTenors_; ++i)
            QL_REQUIRE(swapTenors_[i]>swapTenors_[i-1],
                       "non increasing swap tenor: " << io::ordinal(i) <<
                       " is " << swapTenors_[i-1] << ", " << io::ordinal(i+1) <<
                       " is " << swapTenors_[i]);
    }
void QuantLib::SwaptionVolatilityDiscrete::initializeOptionDatesAndTimes () const [private]
Definition at line 155 of file swaptionvoldiscrete.cpp.
References initializeOptionTimes(), nOptionTenors_, QuantLib::VolatilityTermStructure::optionDateFromTenor(), optionDates_, optionDatesAsReal_, and optionTenors_.
Referenced by performCalculations(), SwaptionVolatilityDiscrete(), and update().
{
        for (Size i=0; i<nOptionTenors_; ++i) {
            optionDates_[i] = optionDateFromTenor(optionTenors_[i]);
            optionDatesAsReal_[i] =
                static_cast<Real>(optionDates_[i].serialNumber());
        }
        initializeOptionTimes();
    }
void QuantLib::SwaptionVolatilityDiscrete::initializeOptionTimes () const [private]
Definition at line 164 of file swaptionvoldiscrete.cpp.
References nOptionTenors_, optionDates_, optionTimes_, and QuantLib::TermStructure::timeFromReference().
Referenced by initializeOptionDatesAndTimes(), and SwaptionVolatilityDiscrete().
{
        for (Size i=0; i<nOptionTenors_; ++i)
            optionTimes_[i] = timeFromReference(optionDates_[i]);
    }
void QuantLib::SwaptionVolatilityDiscrete::initializeSwapLengths () const [private]
Definition at line 169 of file swaptionvoldiscrete.cpp.
References nSwapTenors_, QuantLib::SwaptionVolatilityStructure::swapLength(), swapLengths_, and swapTenors_.
Referenced by performCalculations(), SwaptionVolatilityDiscrete(), and update().
{
        for (Size i=0; i<nSwapTenors_; ++i)
            swapLengths_[i] = swapLength(swapTenors_[i]);
    }
const std::vector< Date > & QuantLib::SwaptionVolatilityDiscrete::optionDates () const [inline]
Definition at line 97 of file swaptionvoldiscrete.hpp.
References optionDates_.
Referenced by QuantLib::SwaptionVolCube1::fillVolatilityCube(), QuantLib::SwaptionVolCube1::sabrCalibration(), QuantLib::SwaptionVolCube1::sabrCalibrationSection(), and QuantLib::SwaptionVolCube1::spreadVolInterpolation().
{
        return optionDates_;
    }
const std::vector< Period > & QuantLib::SwaptionVolatilityDiscrete::optionTenors () const [inline]
Definition at line 92 of file swaptionvoldiscrete.hpp.
References optionTenors_.
{
         return optionTenors_;
    }
const std::vector< Time > & QuantLib::SwaptionVolatilityDiscrete::optionTimes () const [inline]
Definition at line 102 of file swaptionvoldiscrete.hpp.
References optionTimes_.
Referenced by QuantLib::SwaptionVolCube1::createSparseSmiles(), QuantLib::SwaptionVolCube1::fillVolatilityCube(), QuantLib::SwaptionVolCube1::sabrCalibration(), QuantLib::SwaptionVolCube1::sabrCalibrationSection(), and QuantLib::SwaptionVolCube1::spreadVolInterpolation().
{
        return optionTimes_;
    }
void QuantLib::SwaptionVolatilityDiscrete::performCalculations () const [virtual]
This method must implement any calculations which must be (re)done in order to calculate the desired results.
Implements QuantLib::LazyObject.
Reimplemented in QuantLib::SwaptionVolCube1, QuantLib::SwaptionVolatilityMatrix, and QuantLib::SwaptionVolCube2.
Definition at line 174 of file swaptionvoldiscrete.cpp.
References initializeOptionDatesAndTimes(), initializeSwapLengths(), and QuantLib::TermStructure::moving_.
{
        // check if date recalculation could be avoided here
        if (moving_) {
            initializeOptionDatesAndTimes();
            initializeSwapLengths();
        }
    }
const std::vector< Time > & QuantLib::SwaptionVolatilityDiscrete::swapLengths () const [inline]
Definition at line 112 of file swaptionvoldiscrete.hpp.
References swapLengths_.
Referenced by QuantLib::SwaptionVolCube1::createSparseSmiles(), QuantLib::SwaptionVolCube1::fillVolatilityCube(), QuantLib::SwaptionVolCube1::sabrCalibration(), QuantLib::SwaptionVolCube1::sabrCalibrationSection(), and QuantLib::SwaptionVolCube1::spreadVolInterpolation().
{
        return swapLengths_;
    }
const std::vector< Period > & QuantLib::SwaptionVolatilityDiscrete::swapTenors () const [inline]
Definition at line 107 of file swaptionvoldiscrete.hpp.
References swapTenors_.
Referenced by QuantLib::SwaptionVolCube1::fillVolatilityCube(), QuantLib::SwaptionVolCube1::sabrCalibration(), QuantLib::SwaptionVolCube1::sabrCalibrationSection(), and QuantLib::SwaptionVolCube1::spreadVolInterpolation().
{
     return swapTenors_;
    }
void QuantLib::SwaptionVolatilityDiscrete::update () [virtual]
This method must be implemented in derived classes. An instance of Observer does not call this method directly: instead, it will be called by the observables the instance registered with when they need to notify any changes.
Reimplemented from QuantLib::LazyObject.
Definition at line 182 of file swaptionvoldiscrete.cpp.
References anonymous_namespace{marketmodel.cpp}::d, QuantLib::Settings::evaluationDate(), evaluationDate_, initializeOptionDatesAndTimes(), initializeSwapLengths(), QuantLib::Singleton< Settings >::instance(), and QuantLib::TermStructure::moving_.
{
        // recalculate dates if necessary...
        if (moving_) {
            Date d = Settings::instance().evaluationDate();
            if (evaluationDate_ != d) {
                evaluationDate_ = d;
                initializeOptionDatesAndTimes();
                initializeSwapLengths();
            }
        }
        TermStructure::update();
        LazyObject::update();
    }
Member Data Documentation
Date QuantLib::SwaptionVolatilityDiscrete::evaluationDate_ [protected]
Definition at line 79 of file swaptionvoldiscrete.hpp.
Referenced by QuantLib::SwaptionVolatilityCube::SwaptionVolatilityCube(), SwaptionVolatilityDiscrete(), and update().
Size QuantLib::SwaptionVolatilityDiscrete::nOptionTenors_ [protected]
Definition at line 69 of file swaptionvoldiscrete.hpp.
Referenced by QuantLib::SwaptionVolatilityMatrix::checkInputs(), checkOptionDates(), checkOptionTenors(), initializeOptionDatesAndTimes(), initializeOptionTimes(), QuantLib::SwaptionVolCube2::performCalculations(), QuantLib::SwaptionVolCube1::performCalculations(), QuantLib::SwaptionVolCube1::recalibration(), QuantLib::SwaptionVolCube1::registerWithParametersGuess(), QuantLib::SwaptionVolatilityCube::registerWithVolatilitySpread(), and QuantLib::SwaptionVolatilityCube::SwaptionVolatilityCube().
Size QuantLib::SwaptionVolatilityDiscrete::nSwapTenors_ [protected]
Definition at line 76 of file swaptionvoldiscrete.hpp.
Referenced by QuantLib::SwaptionVolatilityMatrix::checkInputs(), checkSwapTenors(), initializeSwapLengths(), QuantLib::SwaptionVolCube2::performCalculations(), QuantLib::SwaptionVolCube1::performCalculations(), QuantLib::SwaptionVolCube1::recalibration(), QuantLib::SwaptionVolCube1::registerWithParametersGuess(), QuantLib::SwaptionVolatilityCube::registerWithVolatilitySpread(), and QuantLib::SwaptionVolatilityCube::SwaptionVolatilityCube().
std::vector<Date> QuantLib::SwaptionVolatilityDiscrete::optionDates_ [mutable, protected]
Definition at line 71 of file swaptionvoldiscrete.hpp.
Referenced by checkOptionDates(), QuantLib::SwaptionVolCube1::Cube::Cube(), QuantLib::SwaptionVolCube1::Cube::expandLayers(), initializeOptionDatesAndTimes(), initializeOptionTimes(), QuantLib::SwaptionVolatilityMatrix::maxDate(), QuantLib::SwaptionVolCube1::Cube::operator=(), optionDates(), QuantLib::SwaptionVolCube1::performCalculations(), and QuantLib::SwaptionVolCube1::Cube::setPoint().
std::vector<Real> QuantLib::SwaptionVolatilityDiscrete::optionDatesAsReal_ [mutable, protected]
Definition at line 73 of file swaptionvoldiscrete.hpp.
Referenced by initializeOptionDatesAndTimes(), and SwaptionVolatilityDiscrete().
Interpolation QuantLib::SwaptionVolatilityDiscrete::optionInterpolator_ [protected]
Definition at line 74 of file swaptionvoldiscrete.hpp.
Referenced by QuantLib::SwaptionVolCube2::smileSectionImpl(), and SwaptionVolatilityDiscrete().
std::vector<Period> QuantLib::SwaptionVolatilityDiscrete::optionTenors_ [protected]
Definition at line 70 of file swaptionvoldiscrete.hpp.
Referenced by checkOptionTenors(), initializeOptionDatesAndTimes(), and optionTenors().
std::vector<Time> QuantLib::SwaptionVolatilityDiscrete::optionTimes_ [mutable, protected]
Definition at line 72 of file swaptionvoldiscrete.hpp.
Referenced by QuantLib::SwaptionVolCube1::Cube::browse(), QuantLib::SwaptionVolCube1::Cube::Cube(), QuantLib::SwaptionVolCube1::Cube::expandLayers(), initializeOptionTimes(), QuantLib::SwaptionVolCube1::Cube::operator=(), optionTimes(), QuantLib::SwaptionVolCube1::Cube::optionTimes(), QuantLib::SwaptionVolCube2::performCalculations(), QuantLib::SwaptionVolCube1::performCalculations(), QuantLib::SwaptionVolCube1::Cube::setElement(), QuantLib::SwaptionVolCube1::Cube::setLayer(), QuantLib::SwaptionVolCube1::Cube::setPoint(), QuantLib::SwaptionVolCube1::Cube::setPoints(), SwaptionVolatilityDiscrete(), QuantLib::SwaptionVolatilityMatrix::SwaptionVolatilityMatrix(), and QuantLib::SwaptionVolCube1::Cube::updateInterpolators().
std::vector<Time> QuantLib::SwaptionVolatilityDiscrete::swapLengths_ [mutable, protected]
Definition at line 78 of file swaptionvoldiscrete.hpp.
Referenced by QuantLib::SwaptionVolCube1::Cube::browse(), QuantLib::SwaptionVolCube1::Cube::Cube(), QuantLib::SwaptionVolCube1::Cube::expandLayers(), initializeSwapLengths(), QuantLib::SwaptionVolCube1::Cube::operator=(), QuantLib::SwaptionVolCube2::performCalculations(), QuantLib::SwaptionVolCube1::performCalculations(), QuantLib::SwaptionVolCube1::Cube::setElement(), QuantLib::SwaptionVolCube1::Cube::setLayer(), QuantLib::SwaptionVolCube1::Cube::setPoint(), QuantLib::SwaptionVolCube1::Cube::setPoints(), swapLengths(), QuantLib::SwaptionVolCube1::Cube::swapLengths(), QuantLib::SwaptionVolatilityMatrix::SwaptionVolatilityMatrix(), and QuantLib::SwaptionVolCube1::Cube::updateInterpolators().
std::vector<Period> QuantLib::SwaptionVolatilityDiscrete::swapTenors_ [protected]
Definition at line 77 of file swaptionvoldiscrete.hpp.
Referenced by checkSwapTenors(), QuantLib::SwaptionVolCube1::Cube::Cube(), QuantLib::SwaptionVolCube1::Cube::expandLayers(), initializeSwapLengths(), QuantLib::SwaptionVolatilityMatrix::maxSwapTenor(), QuantLib::SwaptionVolCube1::Cube::operator=(), QuantLib::SwaptionVolCube1::performCalculations(), QuantLib::SwaptionVolCube1::Cube::setPoint(), and swapTenors().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/swaption/swaptionvoldiscrete.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/swaption/swaptionvoldiscrete.cpp