QuantLib: QuantLib::SwapIndex Class Reference
QuantLib::SwapIndex Class Reference
base class for swap-rate indexes
#include <swapindex.hpp>
Public Member Functions
SwapIndex (const std::string &familyName, const Period &tenor, Natural settlementDays, Currency currency, const Calendar &calendar, const Period &fixedLegTenor, BusinessDayConvention fixedLegConvention, const DayCounter &fixedLegDayCounter, const boost::shared_ptr< IborIndex > &iborIndex)
SwapIndex (const std::string &familyName, const Period &tenor, Natural settlementDays, Currency currency, const Calendar &calendar, const Period &fixedLegTenor, BusinessDayConvention fixedLegConvention, const DayCounter &fixedLegDayCounter, const boost::shared_ptr< IborIndex > &iborIndex, const Handle< YieldTermStructure > &discountingTermStructure)
InterestRateIndex interface
Date maturityDate (const Date &valueDate) const
Inspectors
Period fixedLegTenor () const
BusinessDayConvention fixedLegConvention () const
boost::shared_ptr< IborIndex > iborIndex () const
Handle< YieldTermStructure > forwardingTermStructure () const
Handle< YieldTermStructure > discountingTermStructure () const
bool exogenousDiscount () const
boost::shared_ptr< VanillaSwap > underlyingSwap (const Date &fixingDate) const
Other methods
virtual boost::shared_ptr
< SwapIndex > clone (const Handle< YieldTermStructure > &forwarding) const
returns a copy of itself linked to a different forwarding curve
virtual boost::shared_ptr
< SwapIndex > clone (const Handle< YieldTermStructure > &forwarding, const Handle< YieldTermStructure > &discounting) const
returns a copy of itself linked to different curves
Protected Member Functions
Rate forecastFixing (const Date &fixingDate) const
It can be overridden to implement particular conventions.
Protected Attributes
Period tenor_
boost::shared_ptr< IborIndex > iborIndex_
Period fixedLegTenor_
BusinessDayConvention fixedLegConvention_
bool exogenousDiscount_
Handle< YieldTermStructure > discount_
boost::shared_ptr< VanillaSwap > lastSwap_
Date lastFixingDate_
Detailed Description
base class for swap-rate indexes
Definition at line 40 of file swapindex.hpp.
Constructor & Destructor Documentation
QuantLib::SwapIndex::SwapIndex (const std::string & familyName, const Period & tenor, Natural settlementDays, Currency currency, const Calendar & calendar, const Period & fixedLegTenor, BusinessDayConvention fixedLegConvention, const DayCounter & fixedLegDayCounter, const boost::shared_ptr< IborIndex > & iborIndex)
Referenced by clone().
QuantLib::SwapIndex::SwapIndex (const std::string & familyName, const Period & tenor, Natural settlementDays, Currency currency, const Calendar & calendar, const Period & fixedLegTenor, BusinessDayConvention fixedLegConvention, const DayCounter & fixedLegDayCounter, const boost::shared_ptr< IborIndex > & iborIndex, const Handle< YieldTermStructure > & discountingTermStructure)
Member Function Documentation
shared_ptr< SwapIndex > QuantLib::SwapIndex::clone (const Handle< YieldTermStructure > & forwarding) const [virtual]
returns a copy of itself linked to a different forwarding curve
Definition at line 118 of file swapindex.cpp.
References QuantLib::InterestRateIndex::currency(), QuantLib::InterestRateIndex::dayCounter(), discount_, exogenousDiscount_, QuantLib::InterestRateIndex::familyName(), fixedLegConvention(), fixedLegTenor(), QuantLib::InterestRateIndex::fixingCalendar(), QuantLib::InterestRateIndex::fixingDays(), iborIndex_, SwapIndex(), and QuantLib::InterestRateIndex::tenor().
{
        if (exogenousDiscount_)
            return shared_ptr<SwapIndex>(new
                SwapIndex(familyName(),
                          tenor(),
                          fixingDays(),
                          currency(),
                          fixingCalendar(),
                          fixedLegTenor(),
                          fixedLegConvention(),
                          dayCounter(),
                          iborIndex_->clone(forwarding),
                          discount_));
        else
            return shared_ptr<SwapIndex>(new
                SwapIndex(familyName(),
                          tenor(),
                          fixingDays(),
                          currency(),
                          fixingCalendar(),
                          fixedLegTenor(),
                          fixedLegConvention(),
                          dayCounter(),
                          iborIndex_->clone(forwarding)));
    }
shared_ptr< SwapIndex > QuantLib::SwapIndex::clone (const Handle< YieldTermStructure > & forwarding, const Handle< YieldTermStructure > & discounting) const [virtual]
returns a copy of itself linked to different curves
Definition at line 146 of file swapindex.cpp.
References QuantLib::InterestRateIndex::currency(), QuantLib::InterestRateIndex::dayCounter(), QuantLib::InterestRateIndex::familyName(), fixedLegConvention(), fixedLegTenor(), QuantLib::InterestRateIndex::fixingCalendar(), QuantLib::InterestRateIndex::fixingDays(), iborIndex_, SwapIndex(), and QuantLib::InterestRateIndex::tenor().
{
        return shared_ptr<SwapIndex>(new
             SwapIndex(familyName(),
                       tenor(),
                       fixingDays(),
                       currency(),
                       fixingCalendar(),
                       fixedLegTenor(),
                       fixedLegConvention(),
                       dayCounter(),
                       iborIndex_->clone(forwarding),
                       discounting));
    }
Handle< YieldTermStructure > QuantLib::SwapIndex::discountingTermStructure () const
Definition at line 74 of file swapindex.cpp.
References discount_.
{
        return discount_;  // empty if not exogenous
    }
bool QuantLib::SwapIndex::exogenousDiscount () const [inline]
Definition at line 136 of file swapindex.hpp.
References exogenousDiscount_.
{
        return exogenousDiscount_;
    }
BusinessDayConvention QuantLib::SwapIndex::fixedLegConvention () const [inline]
Definition at line 132 of file swapindex.hpp.
References fixedLegConvention_.
Referenced by clone().
{
        return fixedLegConvention_;
    }
Period QuantLib::SwapIndex::fixedLegTenor () const [inline]
Definition at line 67 of file swapindex.hpp.
References fixedLegTenor_.
Referenced by clone().
{ return fixedLegTenor_; }
Rate QuantLib::SwapIndex::forecastFixing (const Date & fixingDate) const [protected, virtual]
It can be overridden to implement particular conventions.
Implements QuantLib::InterestRateIndex.
Definition at line 78 of file swapindex.cpp.
References underlyingSwap().
{
        return underlyingSwap(fixingDate)->fairRate();
    }
Handle< YieldTermStructure > QuantLib::SwapIndex::forwardingTermStructure () const
Definition at line 70 of file swapindex.cpp.
References iborIndex_.
{
        return iborIndex_->forwardingTermStructure();
    }
boost::shared_ptr<IborIndex> QuantLib::SwapIndex::iborIndex () const [inline]
Definition at line 69 of file swapindex.hpp.
References iborIndex_.
{ return iborIndex_; }
Date QuantLib::SwapIndex::maturityDate (const Date & valueDate) const [virtual]
Implements QuantLib::InterestRateIndex.
Definition at line 112 of file swapindex.cpp.
References QuantLib::InterestRateIndex::fixingDate(), and underlyingSwap().
{
        Date fixDate = fixingDate(valueDate);
        return underlyingSwap(fixDate)->maturityDate();
    }
shared_ptr< VanillaSwap > QuantLib::SwapIndex::underlyingSwap (const Date & fixingDate) const
Warning:
Relinking the term structure underlying the index will not have effect on the returned swap.
Reimplemented in QuantLib::OvernightIndexedSwapIndex.
Definition at line 83 of file swapindex.cpp.
References QuantLib::InterestRateIndex::dayCounter_, discount_, exogenousDiscount_, fixedLegConvention_, fixedLegTenor_, QuantLib::InterestRateIndex::fixingCalendar(), QuantLib::InterestRateIndex::fixingDate(), iborIndex_, lastFixingDate_, lastSwap_, QL_REQUIRE, tenor_, QuantLib::InterestRateIndex::valueDate(), QuantLib::MakeVanillaSwap::withDiscountingTermStructure(), QuantLib::MakeVanillaSwap::withEffectiveDate(), QuantLib::MakeVanillaSwap::withFixedLegCalendar(), QuantLib::MakeVanillaSwap::withFixedLegConvention(), QuantLib::MakeVanillaSwap::withFixedLegDayCount(), QuantLib::MakeVanillaSwap::withFixedLegTenor(), and QuantLib::MakeVanillaSwap::withFixedLegTerminationDateConvention().
Referenced by forecastFixing(), and maturityDate().
{
        QL_REQUIRE(fixingDate!=Date(), "null fixing date");
        // caching mechanism
        if (lastFixingDate_!=fixingDate) {
            Rate fixedRate = 0.0;
            if (exogenousDiscount_)
                lastSwap_ = MakeVanillaSwap(tenor_, iborIndex_, fixedRate)
                    .withEffectiveDate(valueDate(fixingDate))
                    .withFixedLegCalendar(fixingCalendar())
                    .withFixedLegDayCount(dayCounter_)
                    .withFixedLegTenor(fixedLegTenor_)
                    .withFixedLegConvention(fixedLegConvention_)
                    .withFixedLegTerminationDateConvention(fixedLegConvention_)
                    .withDiscountingTermStructure(discount_);
            else
                lastSwap_ = MakeVanillaSwap(tenor_, iborIndex_, fixedRate)
                    .withEffectiveDate(valueDate(fixingDate))
                    .withFixedLegCalendar(fixingCalendar())
                    .withFixedLegDayCount(dayCounter_)
                    .withFixedLegTenor(fixedLegTenor_)
                    .withFixedLegConvention(fixedLegConvention_)
                    .withFixedLegTerminationDateConvention(fixedLegConvention_);
            lastFixingDate_ = fixingDate;
        }
        return lastSwap_;
    }
Member Data Documentation
Handle<YieldTermStructure> QuantLib::SwapIndex::discount_ [protected]
Definition at line 96 of file swapindex.hpp.
Referenced by clone(), discountingTermStructure(), and underlyingSwap().
bool QuantLib::SwapIndex::exogenousDiscount_ [protected]
Definition at line 95 of file swapindex.hpp.
Referenced by clone(), exogenousDiscount(), and underlyingSwap().
BusinessDayConvention QuantLib::SwapIndex::fixedLegConvention_ [protected]
Definition at line 94 of file swapindex.hpp.
Referenced by fixedLegConvention(), and underlyingSwap().
Period QuantLib::SwapIndex::fixedLegTenor_ [protected]
Definition at line 93 of file swapindex.hpp.
Referenced by fixedLegTenor(), and underlyingSwap().
boost::shared_ptr<IborIndex> QuantLib::SwapIndex::iborIndex_ [protected]
Definition at line 92 of file swapindex.hpp.
Referenced by clone(), forwardingTermStructure(), iborIndex(), and underlyingSwap().
Date QuantLib::SwapIndex::lastFixingDate_ [mutable, protected]
Reimplemented in QuantLib::OvernightIndexedSwapIndex.
Definition at line 100 of file swapindex.hpp.
Referenced by underlyingSwap().
boost::shared_ptr<VanillaSwap> QuantLib::SwapIndex::lastSwap_ [mutable, protected]
Reimplemented in QuantLib::OvernightIndexedSwapIndex.
Definition at line 99 of file swapindex.hpp.
Referenced by underlyingSwap().
Period QuantLib::SwapIndex::tenor_ [protected]
Reimplemented from QuantLib::InterestRateIndex.
Definition at line 91 of file swapindex.hpp.
Referenced by underlyingSwap(), and QuantLib::OvernightIndexedSwapIndex::underlyingSwap().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/indexes/swapindex.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/indexes/swapindex.cpp