QuantLib: QuantLib::SubPeriodsCoupon Class Reference
QuantLib::SubPeriodsCoupon Class Reference
#include <subperiodcoupons.hpp>
Public Member Functions
SubPeriodsCoupon (const Date &paymentDate, Real nominal, const boost::shared_ptr< IborIndex > &index, const Date &startDate, const Date &endDate, Natural fixingDays, const DayCounter &dayCounter, Real gearing, Rate couponSpread, Rate rateSpread, const Date &refPeriodStart, const Date &refPeriodEnd)
Spread rateSpread () const
Real startTime () const
Real endTime () const
Size observations () const
const std::vector< Date > & observationDates () const
const std::vector< Real > & observationTimes () const
const boost::shared_ptr< Schedule > observationsSchedule () const
Real priceWithoutOptionality (const Handle< YieldTermStructure > &discountCurve) const
Visitability
virtual void accept (AcyclicVisitor &)
Private Attributes
Real startTime_
Real endTime_
boost::shared_ptr< Schedule > observationsSchedule_
std::vector< Date > observationDates_
std::vector< Real > observationTimes_
Size observations_
Rate rateSpread_
Detailed Description
Definition at line 38 of file subperiodcoupons.hpp.
Constructor & Destructor Documentation
QuantLib::SubPeriodsCoupon::SubPeriodsCoupon (const Date & paymentDate, Real nominal, const boost::shared_ptr< IborIndex > & index, const Date & startDate, const Date & endDate, Natural fixingDays, const DayCounter & dayCounter, Real gearing, Rate couponSpread, Rate rateSpread, const Date & refPeriodStart, const Date & refPeriodEnd)
Definition at line 29 of file subperiodcoupons.cpp.
References endTime_, QuantLib::DateGeneration::Forward, observationDates_, observations_, observationsSchedule_, observationTimes_, startTime_, QuantLib::Unadjusted, and QuantLib::DayCounter::yearFraction().
    : FloatingRateCoupon(paymentDate, nominal, startDate, endDate,
                         fixingDays, index, gearing, couponSpread,
                         refPeriodStart, refPeriodEnd, dayCounter),
      rateSpread_(rateSpread) {
        const Handle<YieldTermStructure>& rateCurve =
            index->forwardingTermStructure();
        const Date& referenceDate = rateCurve->referenceDate();
        observationsSchedule_ = boost::shared_ptr<Schedule>(new
            Schedule(startDate, endDate,
                     index->tenor(),
                     NullCalendar(),
                     Unadjusted,
                     Unadjusted,
                     DateGeneration::Forward,
                     false));
        observationDates_ = observationsSchedule_->dates();
        observationDates_.pop_back();                       //remove end date
        observations_ = observationDates_.size();
        startTime_ = dayCounter.yearFraction(referenceDate, startDate);
        endTime_ = dayCounter.yearFraction(referenceDate, endDate);
        for (Size i=0; i<observations_; ++i) {
            observationTimes_.push_back(
                dayCounter.yearFraction(referenceDate, observationDates_[i]));
        }
     }
Member Function Documentation
void QuantLib::SubPeriodsCoupon::accept (AcyclicVisitor & v) [virtual]
Reimplemented from QuantLib::FloatingRateCoupon.
Definition at line 72 of file subperiodcoupons.cpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Visitor< T >::visit().
{
        Visitor<SubPeriodsCoupon>* v1 =
            dynamic_cast<Visitor<SubPeriodsCoupon>*>(&v);
        if (v1 != 0)
            v1->visit(*this);
        else
            FloatingRateCoupon::accept(v);
    }
Real QuantLib::SubPeriodsCoupon::endTime () const [inline]
Definition at line 66 of file subperiodcoupons.hpp.
References endTime_.
Referenced by QuantLib::SubPeriodsPricer::initialize().
{ return endTime_; }
const std::vector<Date>& QuantLib::SubPeriodsCoupon::observationDates () const [inline]
Definition at line 68 of file subperiodcoupons.hpp.
References observationDates_.
{
            return observationDates_;
        }
Size QuantLib::SubPeriodsCoupon::observations () const [inline]
Definition at line 67 of file subperiodcoupons.hpp.
References observations_.
Referenced by QuantLib::SubPeriodsPricer::initialize().
{ return observations_; }
const boost::shared_ptr<Schedule> QuantLib::SubPeriodsCoupon::observationsSchedule () const [inline]
Definition at line 75 of file subperiodcoupons.hpp.
References observationsSchedule_.
Referenced by QuantLib::SubPeriodsPricer::initialize().
{
            return observationsSchedule_;
        }
const std::vector<Real>& QuantLib::SubPeriodsCoupon::observationTimes () const [inline]
Definition at line 71 of file subperiodcoupons.hpp.
References observationTimes_.
Referenced by QuantLib::SubPeriodsPricer::initialize().
{
            return observationTimes_;
        }
Real QuantLib::SubPeriodsCoupon::priceWithoutOptionality (const Handle< YieldTermStructure > & discountCurve) const
Spread QuantLib::SubPeriodsCoupon::rateSpread () const [inline]
Definition at line 63 of file subperiodcoupons.hpp.
References rateSpread_.
Referenced by QuantLib::SubPeriodsPricer::initialize().
{ return rateSpread_; }
Real QuantLib::SubPeriodsCoupon::startTime () const [inline]
Definition at line 65 of file subperiodcoupons.hpp.
References startTime_.
Referenced by QuantLib::SubPeriodsPricer::initialize().
{ return startTime_; }
Member Data Documentation
Real QuantLib::SubPeriodsCoupon::endTime_ [private]
Definition at line 88 of file subperiodcoupons.hpp.
Referenced by endTime(), and SubPeriodsCoupon().
std::vector<Date> QuantLib::SubPeriodsCoupon::observationDates_ [private]
Definition at line 91 of file subperiodcoupons.hpp.
Referenced by observationDates(), and SubPeriodsCoupon().
Size QuantLib::SubPeriodsCoupon::observations_ [private]
Definition at line 94 of file subperiodcoupons.hpp.
Referenced by observations(), and SubPeriodsCoupon().
boost::shared_ptr<Schedule> QuantLib::SubPeriodsCoupon::observationsSchedule_ [private]
Definition at line 90 of file subperiodcoupons.hpp.
Referenced by observationsSchedule(), and SubPeriodsCoupon().
std::vector<Real> QuantLib::SubPeriodsCoupon::observationTimes_ [private]
Definition at line 92 of file subperiodcoupons.hpp.
Referenced by observationTimes(), and SubPeriodsCoupon().
Rate QuantLib::SubPeriodsCoupon::rateSpread_ [private]
Definition at line 95 of file subperiodcoupons.hpp.
Referenced by rateSpread().
Real QuantLib::SubPeriodsCoupon::startTime_ [private]
Definition at line 87 of file subperiodcoupons.hpp.
Referenced by startTime(), and SubPeriodsCoupon().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/coupons/subperiodcoupons.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/coupons/subperiodcoupons.cpp