QuantLib: QuantLib::OvernightIndex Class Reference
QuantLib::OvernightIndex Class Reference
#include <iborindex.hpp>
Public Member Functions
OvernightIndex (const std::string &familyName, Natural settlementDays, const Currency &currency, const Calendar &fixingCalendar, const DayCounter &dayCounter, const Handle< YieldTermStructure > &h=Handle< YieldTermStructure >())
boost::shared_ptr< IborIndex > clone (const Handle< YieldTermStructure > &h) const
returns a copy of itself linked to a different forwarding curve
Detailed Description
Definition at line 89 of file iborindex.hpp.
Constructor & Destructor Documentation
QuantLib::OvernightIndex::OvernightIndex (const std::string & familyName, Natural settlementDays, const Currency & currency, const Calendar & fixingCalendar, const DayCounter & dayCounter, const Handle< YieldTermStructure > & h = Handle<YieldTermStructure>())
Definition at line 84 of file iborindex.cpp.
Referenced by clone().
   : IborIndex(familyName, 1*Days, settlementDays, curr,
               fixCal, Following, false, dc, h) {}
Member Function Documentation
boost::shared_ptr< IborIndex > QuantLib::OvernightIndex::clone (const Handle< YieldTermStructure > & h) const [virtual]
returns a copy of itself linked to a different forwarding curve
Reimplemented from QuantLib::IborIndex.
Definition at line 93 of file iborindex.cpp.
References QuantLib::InterestRateIndex::currency(), QuantLib::InterestRateIndex::dayCounter(), QuantLib::InterestRateIndex::familyName(), QuantLib::InterestRateIndex::fixingCalendar(), QuantLib::InterestRateIndex::fixingDays(), and OvernightIndex().
{
        return boost::shared_ptr<IborIndex>(
                                        new OvernightIndex(familyName(),
                                                           fixingDays(),
                                                           currency(),
                                                           fixingCalendar(),
                                                           dayCounter(),
                                                           h));
    }
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/indexes/iborindex.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/indexes/iborindex.cpp