QuantLib: QuantLib::RiskyAssetSwapOption Class Reference
QuantLib::RiskyAssetSwapOption Class Reference
Option on risky asset swap
#include <riskyassetswapoption.hpp>
Public Member Functions
RiskyAssetSwapOption (bool payer, const boost::shared_ptr< RiskyAssetSwap > &asw, const Date &expiry, Rate marketSpread, Volatility spreadVolatility)
Private Member Functions
bool isExpired () const
returns whether the instrument might have value greater than zero.
void performCalculations () const
Private Attributes
bool payer_
boost::shared_ptr< RiskyAssetSwap > asw_
Date expiry_
Rate marketSpread_
Volatility spreadVolatility_
Detailed Description
Option on risky asset swap
Definition at line 33 of file riskyassetswapoption.hpp.
Constructor & Destructor Documentation
QuantLib::RiskyAssetSwapOption::RiskyAssetSwapOption (bool payer, const boost::shared_ptr< RiskyAssetSwap > & asw, const Date & expiry, Rate marketSpread, Volatility spreadVolatility)
Definition at line 26 of file riskyassetswapoption.cpp.
    : payer_(payer), asw_(asw), expiry_(expiry),
      marketSpread_(marketSpread),
      spreadVolatility_(spreadVolatility) {}
Member Function Documentation
bool QuantLib::RiskyAssetSwapOption::isExpired () const [private, virtual]
returns whether the instrument might have value greater than zero.
Implements QuantLib::Instrument.
Definition at line 37 of file riskyassetswapoption.cpp.
References expiry_, and QuantLib::Event::hasOccurred().
{
        return detail::simple_event(expiry_).hasOccurred();
    }
void QuantLib::RiskyAssetSwapOption::performCalculations () const [private, virtual]
In case a pricing engine is not used, this method must be overridden to perform the actual calculations and set any needed results. In case a pricing engine is used, the default implementation can be used.
Reimplemented from QuantLib::Instrument.
Definition at line 42 of file riskyassetswapoption.cpp.
References asw_, anonymous_namespace{marketmodel.cpp}::d, QuantLib::Settings::evaluationDate(), expiry_, QuantLib::Singleton< Settings >::instance(), marketSpread_, QuantLib::Instrument::NPV_, spreadVolatility_, and QuantLib::DayCounter::yearFraction().
{
        Real w;
        if (asw_->fixedPayer()) // strike receiver = asw call = spread put
            w = -1.0;
        else
            w = 1.0;
        Date today = Settings::instance().evaluationDate();
        Time expiryTime = Actual365Fixed().yearFraction(today, expiry_);
        Real stdDev = spreadVolatility_ * sqrt(expiryTime);
        Real d = (asw_->spread() - marketSpread_) / stdDev;
        Real A0 = asw_->nominal() * asw_->floatAnnuity();
        NPV_ = A0 * stdDev * (w*d * CumulativeNormalDistribution()(w*d)
                              + NormalDistribution()(d));
    }
Member Data Documentation
boost::shared_ptr<RiskyAssetSwap> QuantLib::RiskyAssetSwapOption::asw_ [private]
Definition at line 45 of file riskyassetswapoption.hpp.
Referenced by performCalculations().
Date QuantLib::RiskyAssetSwapOption::expiry_ [private]
Definition at line 46 of file riskyassetswapoption.hpp.
Referenced by isExpired(), and performCalculations().
Rate QuantLib::RiskyAssetSwapOption::marketSpread_ [private]
Definition at line 47 of file riskyassetswapoption.hpp.
Referenced by performCalculations().
bool QuantLib::RiskyAssetSwapOption::payer_ [private]
Definition at line 44 of file riskyassetswapoption.hpp.
Volatility QuantLib::RiskyAssetSwapOption::spreadVolatility_ [private]
Definition at line 48 of file riskyassetswapoption.hpp.
Referenced by performCalculations().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/riskyassetswapoption.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/riskyassetswapoption.cpp