QuantLib: QuantLib::DiscretizedAsset Class Reference
QuantLib::DiscretizedAsset Class Reference
Discretized asset class used by numerical methods.
#include <discretizedasset.hpp>
Public Member Functions
DiscretizedAsset ()
virtual ~DiscretizedAsset ()
inspectors
Time time () const
Time & time ()
const Array & values () const
Array & values ()
const boost::shared_ptr
< Lattice > & method () const
High-level interface
Users of discretized assets should use these methods in order to initialize, evolve and take the present value of the assets. They call the corresponding methods in the Lattice interface, to which we refer for documentation.
void initialize (const boost::shared_ptr< Lattice > &, Time t)
void rollback (Time to)
void partialRollback (Time to)
Real presentValue ()
Low-level interface
These methods (that developers should override when deriving from DiscretizedAsset) are to be used by numerical methods and not directly by users, with the exception of adjustValues(), preAdjustValues() and postAdjustValues() that can be used together with partialRollback().
virtual void reset (Size size)=0
void preAdjustValues ()
void postAdjustValues ()
void adjustValues ()
virtual std::vector< Time > mandatoryTimes () const =0
Protected Member Functions
bool isOnTime (Time t) const
virtual void preAdjustValuesImpl ()
virtual void postAdjustValuesImpl ()
Protected Attributes
Time time_
Time latestPreAdjustment_
Time latestPostAdjustment_
Array values_
Private Attributes
boost::shared_ptr< Lattice > method_
Detailed Description
Discretized asset class used by numerical methods.
Definition at line 35 of file discretizedasset.hpp.
Constructor & Destructor Documentation
QuantLib::DiscretizedAsset::DiscretizedAsset () [inline]
Definition at line 37 of file discretizedasset.hpp.
        : latestPreAdjustment_(QL_MAX_REAL),
          latestPostAdjustment_(QL_MAX_REAL) {}
virtual QuantLib::DiscretizedAsset::~DiscretizedAsset () [inline, virtual]
Definition at line 40 of file discretizedasset.hpp.
{}
Member Function Documentation
void QuantLib::DiscretizedAsset::adjustValues () [inline]
This method performs both pre- and post-adjustment
Definition at line 112 of file discretizedasset.hpp.
References postAdjustValues(), and preAdjustValues().
Referenced by QuantLib::TsiveriotisFernandesLattice< T >::partialRollback(), QuantLib::TreeLattice< Impl >::partialRollback(), QuantLib::DiscretizedCallableFixedRateBond::reset(), QuantLib::DiscretizedSwap::reset(), QuantLib::DiscretizedCapFloor::reset(), QuantLib::DiscretizedVanillaOption::reset(), QuantLib::DiscretizedConvertible::reset(), QuantLib::DiscretizedOption::reset(), QuantLib::TsiveriotisFernandesLattice< T >::rollback(), and QuantLib::TreeLattice< Impl >::rollback().
{
            preAdjustValues();
            postAdjustValues();
        }
void QuantLib::DiscretizedAsset::initialize (const boost::shared_ptr< Lattice > & method, Time t) [inline]
Definition at line 182 of file discretizedasset.hpp.
References method(), and method_.
Referenced by QuantLib::TreeCapFloorEngine::calculate(), QuantLib::TreeCallableFixedRateBondEngine::calculate(), QuantLib::TreeVanillaSwapEngine::calculate(), QuantLib::BinomialConvertibleEngine< T >::calculate(), QuantLib::BinomialVanillaEngine< T >::calculate(), QuantLib::TreeSwaptionEngine::calculate(), QuantLib::DiscretizedCapFloor::preAdjustValuesImpl(), and QuantLib::DiscretizedSwap::preAdjustValuesImpl().
{
        method_ = method;
        method_->initialize(*this, t);
    }
bool QuantLib::DiscretizedAsset::isOnTime (Time t) const [inline, protected]
This method checks whether the asset was rolled at the given time.
Definition at line 215 of file discretizedasset.hpp.
References QuantLib::close_enough(), QuantLib::TimeGrid::index(), method(), and time().
Referenced by QuantLib::DiscretizedCallableFixedRateBond::postAdjustValuesImpl(), QuantLib::DiscretizedCapFloor::postAdjustValuesImpl(), QuantLib::DiscretizedSwap::postAdjustValuesImpl(), QuantLib::DiscretizedVanillaOption::postAdjustValuesImpl(), QuantLib::DiscretizedConvertible::postAdjustValuesImpl(), QuantLib::DiscretizedOption::postAdjustValuesImpl(), QuantLib::DiscretizedSwap::preAdjustValuesImpl(), and QuantLib::DiscretizedCapFloor::preAdjustValuesImpl().
{
        const TimeGrid& grid = method()->timeGrid();
        return close_enough(grid[grid.index(t)],time());
    }
virtual std::vector<Time> QuantLib::DiscretizedAsset::mandatoryTimes () const [pure virtual]
This method returns the times at which the numerical method should stop while rolling back the asset. Typical examples include payment times, exercise times and such.
Note:
The returned values are not guaranteed to be sorted.
Implemented in QuantLib::DiscretizedOption, QuantLib::DiscretizedDiscountBond, QuantLib::DiscretizedConvertible, QuantLib::DiscretizedVanillaOption, QuantLib::DiscretizedCapFloor, QuantLib::DiscretizedSwap, and QuantLib::DiscretizedCallableFixedRateBond.
const boost::shared_ptr<Lattice>& QuantLib::DiscretizedAsset::method () const [inline]
Definition at line 50 of file discretizedasset.hpp.
References method_.
Referenced by QuantLib::DiscretizedConvertible::adjustedGrid(), QuantLib::DiscretizedVanillaOption::applySpecificCondition(), initialize(), isOnTime(), QuantLib::DiscretizedCapFloor::preAdjustValuesImpl(), QuantLib::DiscretizedSwap::preAdjustValuesImpl(), QuantLib::DiscretizedSwaption::reset(), and QuantLib::DiscretizedOption::reset().
{
            return method_;
        }
void QuantLib::DiscretizedAsset::partialRollback (Time to) [inline]
Definition at line 193 of file discretizedasset.hpp.
References method_.
{
        method_->partialRollback(*this, to);
    }
void QuantLib::DiscretizedAsset::postAdjustValues () [inline]
This method will be invoked after rollback and after any other asset had their chance to look at the values. For instance, payments happening at the present time (and therefore not included in an option to be exercised at this time) will be added here.
This method is not virtual; derived classes must override the protected postAdjustValuesImpl() method instead.
Definition at line 208 of file discretizedasset.hpp.
References QuantLib::close_enough(), latestPostAdjustment_, postAdjustValuesImpl(), and time().
Referenced by adjustValues().
{
        if (!close_enough(time(),latestPostAdjustment_)) {
            postAdjustValuesImpl();
            latestPostAdjustment_ = time();
        }
    }
virtual void QuantLib::DiscretizedAsset::postAdjustValuesImpl () [inline, protected, virtual]
This method performs the actual post-adjustment
Reimplemented in QuantLib::DiscretizedOption, QuantLib::DiscretizedConvertible, QuantLib::DiscretizedVanillaOption, QuantLib::DiscretizedCallableFixedRateBond, QuantLib::DiscretizedCapFloor, and QuantLib::DiscretizedSwap.
Definition at line 132 of file discretizedasset.hpp.
Referenced by postAdjustValues().
{}
void QuantLib::DiscretizedAsset::preAdjustValues () [inline]
This method will be invoked after rollback and before any other asset (i.e., an option on this one) has any chance to look at the values. For instance, payments happening at times already spanned by the rollback will be added here.
This method is not virtual; derived classes must override the protected preAdjustValuesImpl() method instead.
Definition at line 201 of file discretizedasset.hpp.
References QuantLib::close_enough(), latestPreAdjustment_, preAdjustValuesImpl(), and time().
Referenced by adjustValues().
{
        if (!close_enough(time(),latestPreAdjustment_)) {
            preAdjustValuesImpl();
            latestPreAdjustment_ = time();
        }
    }
virtual void QuantLib::DiscretizedAsset::preAdjustValuesImpl () [inline, protected, virtual]
This method performs the actual pre-adjustment
Reimplemented in QuantLib::DiscretizedCallableFixedRateBond, QuantLib::DiscretizedCapFloor, and QuantLib::DiscretizedSwap.
Definition at line 130 of file discretizedasset.hpp.
Referenced by preAdjustValues().
{}
Real QuantLib::DiscretizedAsset::presentValue () [inline]
Definition at line 197 of file discretizedasset.hpp.
References method_.
Referenced by QuantLib::TreeCapFloorEngine::calculate(), QuantLib::TreeVanillaSwapEngine::calculate(), QuantLib::TreeCallableFixedRateBondEngine::calculate(), QuantLib::BinomialConvertibleEngine< T >::calculate(), QuantLib::BinomialVanillaEngine< T >::calculate(), and QuantLib::TreeSwaptionEngine::calculate().
{
        return method_->presentValue(*this);
    }
virtual void QuantLib::DiscretizedAsset::reset (Size size) [pure virtual]
This method should initialize the asset values to an Array of the given size and with values depending on the particular asset.
Implemented in QuantLib::DiscretizedOption, QuantLib::DiscretizedDiscountBond, QuantLib::DiscretizedConvertible, QuantLib::DiscretizedVanillaOption, QuantLib::DiscretizedCapFloor, QuantLib::DiscretizedSwap, QuantLib::DiscretizedSwaption, and QuantLib::DiscretizedCallableFixedRateBond.
Referenced by QuantLib::TreeLattice< Impl >::initialize().
void QuantLib::DiscretizedAsset::rollback (Time to) [inline]
Definition at line 189 of file discretizedasset.hpp.
References method_.
Referenced by QuantLib::TreeCapFloorEngine::calculate(), QuantLib::TreeCallableFixedRateBondEngine::calculate(), QuantLib::TreeVanillaSwapEngine::calculate(), QuantLib::BinomialConvertibleEngine< T >::calculate(), QuantLib::BinomialVanillaEngine< T >::calculate(), QuantLib::TreeSwaptionEngine::calculate(), QuantLib::DiscretizedCapFloor::preAdjustValuesImpl(), and QuantLib::DiscretizedSwap::preAdjustValuesImpl().
{
        method_->rollback(*this, to);
    }
Time QuantLib::DiscretizedAsset::time () const [inline]
Definition at line 44 of file discretizedasset.hpp.
References time_.
Referenced by QuantLib::DiscretizedConvertible::adjustedGrid(), QuantLib::DiscretizedVanillaOption::applySpecificCondition(), QuantLib::TreeLattice< Impl >::initialize(), isOnTime(), QuantLib::TsiveriotisFernandesLattice< T >::partialRollback(), QuantLib::TreeLattice< Impl >::partialRollback(), postAdjustValues(), QuantLib::DiscretizedVanillaOption::postAdjustValuesImpl(), QuantLib::DiscretizedConvertible::postAdjustValuesImpl(), QuantLib::DiscretizedOption::postAdjustValuesImpl(), preAdjustValues(), and QuantLib::TreeLattice< Impl >::presentValue().
{ return time_; }
Time& QuantLib::DiscretizedAsset::time () [inline]
Definition at line 45 of file discretizedasset.hpp.
References time_.
{ return time_; }
const Array& QuantLib::DiscretizedAsset::values () const [inline]
Definition at line 47 of file discretizedasset.hpp.
References values_.
Referenced by QuantLib::BinomialVanillaEngine< T >::calculate(), QuantLib::TsiveriotisFernandesLattice< T >::partialRollback(), QuantLib::TreeLattice< Impl >::partialRollback(), QuantLib::DiscretizedCapFloor::preAdjustValuesImpl(), QuantLib::DiscretizedSwap::preAdjustValuesImpl(), and QuantLib::TreeLattice< Impl >::presentValue().
{ return values_; }
Array& QuantLib::DiscretizedAsset::values () [inline]
Definition at line 48 of file discretizedasset.hpp.
References values_.
{ return values_; }
Member Data Documentation
Time QuantLib::DiscretizedAsset::latestPostAdjustment_ [protected]
Definition at line 135 of file discretizedasset.hpp.
Referenced by postAdjustValues().
Time QuantLib::DiscretizedAsset::latestPreAdjustment_ [protected]
Definition at line 135 of file discretizedasset.hpp.
Referenced by preAdjustValues().
boost::shared_ptr<Lattice> QuantLib::DiscretizedAsset::method_ [private]
Definition at line 138 of file discretizedasset.hpp.
Referenced by initialize(), method(), partialRollback(), presentValue(), and rollback().
Time QuantLib::DiscretizedAsset::time_ [protected]
Definition at line 134 of file discretizedasset.hpp.
Referenced by QuantLib::DiscretizedOption::postAdjustValuesImpl(), QuantLib::DiscretizedSwap::preAdjustValuesImpl(), QuantLib::DiscretizedCapFloor::preAdjustValuesImpl(), and time().
Array QuantLib::DiscretizedAsset::values_ [protected]
Definition at line 136 of file discretizedasset.hpp.
Referenced by QuantLib::DiscretizedCallableFixedRateBond::addCoupon(), QuantLib::DiscretizedConvertible::addCoupon(), QuantLib::DiscretizedCallableFixedRateBond::applyCallability(), QuantLib::DiscretizedConvertible::applyCallability(), QuantLib::DiscretizedConvertible::applyConvertibility(), QuantLib::DiscretizedOption::applyExerciseCondition(), QuantLib::DiscretizedVanillaOption::applySpecificCondition(), QuantLib::DiscretizedSwap::postAdjustValuesImpl(), QuantLib::DiscretizedCapFloor::postAdjustValuesImpl(), QuantLib::DiscretizedSwap::preAdjustValuesImpl(), QuantLib::DiscretizedCapFloor::preAdjustValuesImpl(), QuantLib::DiscretizedCallableFixedRateBond::reset(), QuantLib::DiscretizedCapFloor::reset(), QuantLib::DiscretizedSwap::reset(), QuantLib::DiscretizedVanillaOption::reset(), QuantLib::DiscretizedConvertible::reset(), QuantLib::DiscretizedDiscountBond::reset(), QuantLib::DiscretizedOption::reset(), and values().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/discretizedasset.hpp