QuantLib: QuantLib::BlackCallableFixedRateBondEngine Class Reference
QuantLib::BlackCallableFixedRateBondEngine Class Reference
Black-formula callable fixed rate bond engine.
#include <blackcallablebondengine.hpp>
Public Member Functions
BlackCallableFixedRateBondEngine (const Handle< Quote > &fwdYieldVol, const Handle< YieldTermStructure > &discountCurve)
volatility is the quoted fwd yield volatility, not price vol
BlackCallableFixedRateBondEngine (const Handle< CallableBondVolatilityStructure > &yieldVolStructure, const Handle< YieldTermStructure > &discountCurve)
volatility is the quoted fwd yield volatility, not price vol
void calculate () const
Private Member Functions
Real spotIncome () const
Volatility forwardPriceVolatility () const
Private Attributes
Handle
< CallableBondVolatilityStructure > volatility_
Handle< YieldTermStructure > discountCurve_
Detailed Description
Black-formula callable fixed rate bond engine.
Callable fixed rate bond Black engine. The embedded (European) option follows the Black "European bond option" treatment in Hull, Fourth Edition, Chapter 20.
Todo:
set additionalResults (e.g. vega, fairStrike, etc.)
Warning:
This class has yet to be tested
Definition at line 43 of file blackcallablebondengine.hpp.
Constructor & Destructor Documentation
QuantLib::BlackCallableFixedRateBondEngine::BlackCallableFixedRateBondEngine (const Handle< Quote > & fwdYieldVol, const Handle< YieldTermStructure > & discountCurve)
volatility is the quoted fwd yield volatility, not price vol
Definition at line 31 of file blackcallablebondengine.cpp.
References discountCurve_, QuantLib::Observer::registerWith(), and volatility_.
    : volatility_(boost::shared_ptr<CallableBondVolatilityStructure>(
                      new CallableBondConstantVolatility(0, NullCalendar(),
                                                         fwdYieldVol,
                                                         Actual365Fixed()))),
      discountCurve_(discountCurve) {
        registerWith(volatility_);
        registerWith(discountCurve_);
    }
QuantLib::BlackCallableFixedRateBondEngine::BlackCallableFixedRateBondEngine (const Handle< CallableBondVolatilityStructure > & yieldVolStructure, const Handle< YieldTermStructure > & discountCurve)
volatility is the quoted fwd yield volatility, not price vol
no vol structures implemented yet besides constant volatility
Definition at line 44 of file blackcallablebondengine.cpp.
References discountCurve_, QuantLib::Observer::registerWith(), and volatility_.
    : volatility_(yieldVolStructure), discountCurve_(discountCurve) {
        registerWith(volatility_);
        registerWith(discountCurve_);
    }
Member Function Documentation
void QuantLib::BlackCallableFixedRateBondEngine::calculate () const [virtual]
Implements QuantLib::PricingEngine.
Definition at line 127 of file blackcallablebondengine.cpp.
References QuantLib::GenericEngine< CallableBond::arguments, CallableBond::results >::arguments_, QuantLib::blackFormula(), QuantLib::Option::Call, QuantLib::Callability::Call, QuantLib::CallableBond::arguments::callabilityDates, QuantLib::CallableBond::arguments::callabilityPrices, QuantLib::Bond::arguments::cashflows, discountCurve_, forwardPriceVolatility(), QuantLib::CashFlows::npv(), QuantLib::Option::Put, QuantLib::CallableBond::arguments::putCallSchedule, QL_REQUIRE, QuantLib::GenericEngine< CallableBond::arguments, CallableBond::results >::results_, QuantLib::Bond::arguments::settlementDate, QuantLib::Bond::results::settlementValue, spotIncome(), QuantLib::Instrument::results::value, and volatility_.
{
        // validate args for Black engine
        QL_REQUIRE(arguments_.putCallSchedule.size() == 1,
                   "Must have exactly one call/put date to use Black Engine");
        Date settle = arguments_.settlementDate;
        Date exerciseDate = arguments_.callabilityDates[0];
        QL_REQUIRE(exerciseDate >= settle,
                   "must have exercise Date >= settlement Date");
        Leg fixedLeg = arguments_.cashflows;
        Real value = CashFlows::npv(fixedLeg,
                                    **discountCurve_,
                                    false, settle);
        Real npv = CashFlows::npv(fixedLeg,
                                  **discountCurve_,
                                  false, discountCurve_->referenceDate());
        Real fwdCashPrice = (value - spotIncome())/
                            discountCurve_->discount(exerciseDate);
        Real cashStrike = arguments_.callabilityPrices[0];
        Option::Type type = (arguments_.putCallSchedule[0]->type() ==
                             Callability::Call ? Option::Call : Option::Put);
        Volatility priceVol = forwardPriceVolatility();
        Time exerciseTime = volatility_->dayCounter().yearFraction(
                                                 volatility_->referenceDate(),
                                                 exerciseDate);
        Real embeddedOptionValue =
            blackFormula(type,
                         cashStrike,
                         fwdCashPrice,
                         priceVol*std::sqrt(exerciseTime));
        if (type == Option::Call) {
            results_.value = npv - embeddedOptionValue;
            results_.settlementValue = value - embeddedOptionValue;
        } else {
            results_.value = npv + embeddedOptionValue;
            results_.settlementValue = value + embeddedOptionValue;
        }
    }
Volatility QuantLib::BlackCallableFixedRateBondEngine::forwardPriceVolatility () const [private]
Definition at line 77 of file blackcallablebondengine.cpp.
References QuantLib::Annual, QuantLib::GenericEngine< CallableBond::arguments, CallableBond::results >::arguments_, QuantLib::CallableBond::arguments::callabilityDates, QuantLib::CallableBond::arguments::callabilityPrices, QuantLib::Bond::arguments::cashflows, QuantLib::Compounded, anonymous_namespace{marketmodel.cpp}::dayCounter, discountCurve_, QuantLib::CashFlows::duration(), QuantLib::CallableBond::arguments::frequency, QuantLib::Duration::Modified, QuantLib::NoFrequency, QuantLib::CashFlows::npv(), QuantLib::Once, QuantLib::CallableBond::arguments::paymentDayCounter, QuantLib::CallableBond::arguments::redemptionDate, volatility_, QuantLib::DayCounter::yearFraction(), and QuantLib::CashFlows::yield().
Referenced by calculate().
{
        Date bondMaturity = arguments_.redemptionDate;
        Date exerciseDate = arguments_.callabilityDates[0];
        Leg fixedLeg = arguments_.cashflows;
        // value of bond cash flows at option maturity
        Real fwdNpv = CashFlows::npv(fixedLeg,
                                     **discountCurve_,
                                     false, exerciseDate);
        DayCounter dayCounter = arguments_.paymentDayCounter;
        Frequency frequency = arguments_.frequency;
        // adjust if zero coupon bond (see also bond.cpp)
        if (frequency == NoFrequency || frequency == Once)
            frequency = Annual;
        Rate fwdYtm = CashFlows::yield(fixedLeg,
                                       fwdNpv,
                                       dayCounter,
                                       Compounded,
                                       frequency,
                                       false, exerciseDate);
        InterestRate fwdRate(fwdYtm,
                             dayCounter,
                             Compounded,
                             frequency);
        Time fwdDur = CashFlows::duration(fixedLeg,
                                          fwdRate,
                                          Duration::Modified,
                                          false, exerciseDate);
        Real cashStrike = arguments_.callabilityPrices[0];
        dayCounter = volatility_->dayCounter();
        Date referenceDate = volatility_->referenceDate();
        Time exerciseTime = dayCounter.yearFraction(referenceDate,
                                                    exerciseDate);
        Time maturityTime = dayCounter.yearFraction(referenceDate,
                                                    bondMaturity);
        Volatility yieldVol = volatility_->volatility(exerciseTime,
                                                      maturityTime-exerciseTime,
                                                      cashStrike);
        Volatility fwdPriceVol = yieldVol*fwdDur*fwdYtm;
        return fwdPriceVol;
    }
Real QuantLib::BlackCallableFixedRateBondEngine::spotIncome () const [private]
settle date of embedded option assumed same as that of bond
Definition at line 52 of file blackcallablebondengine.cpp.
References QuantLib::GenericEngine< CallableBond::arguments, CallableBond::results >::arguments_, QuantLib::Bond::arguments::cashflows, discountCurve_, QuantLib::CallableBond::arguments::putCallSchedule, and QuantLib::Bond::arguments::settlementDate.
Referenced by calculate().
{
        Date settlement = arguments_.settlementDate;
        Leg cf = arguments_.cashflows;
        Date optionMaturity = arguments_.putCallSchedule[0]->date();
        /* the following assumes
           1. cashflows are in ascending order !
           2. income = coupons paid between settlementDate() and put/call date
        */
        Real income = 0.0;
        for (Size i = 0; i < cf.size() - 1; ++i) {
            if (!cf[i]->hasOccurred(settlement, false)) {
                if (cf[i]->hasOccurred(optionMaturity, false)) {
                    income += cf[i]->amount() *
                              discountCurve_->discount(cf[i]->date());
                } else {
                    break;
                }
            }
        }
        return income/discountCurve_->discount(settlement);
    }
Member Data Documentation
Handle<YieldTermStructure> QuantLib::BlackCallableFixedRateBondEngine::discountCurve_ [private]
Definition at line 57 of file blackcallablebondengine.hpp.
Referenced by BlackCallableFixedRateBondEngine(), calculate(), forwardPriceVolatility(), and spotIncome().
Handle<CallableBondVolatilityStructure> QuantLib::BlackCallableFixedRateBondEngine::volatility_ [private]
Definition at line 56 of file blackcallablebondengine.hpp.
Referenced by BlackCallableFixedRateBondEngine(), calculate(), and forwardPriceVolatility().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/callablebonds/blackcallablebondengine.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/callablebonds/blackcallablebondengine.cpp