QuantLib: QuantLib::InverseCumulativePoisson Class Reference
QuantLib::InverseCumulativePoisson Class Reference
Inverse cumulative Poisson distribution function.
#include <poissondistribution.hpp>
Public Member Functions
InverseCumulativePoisson (Real lambda=1.0)
Real operator() (Real x) const
Private Member Functions
Real calcSummand (BigNatural index) const
Private Attributes
Real lambda_
Detailed Description
Inverse cumulative Poisson distribution function.
Test:
the correctness of the returned value is tested by checking it against known good results.
Definition at line 77 of file poissondistribution.hpp.
Constructor & Destructor Documentation
QuantLib::InverseCumulativePoisson::InverseCumulativePoisson (Real lambda = 1.0) [inline]
Definition at line 109 of file poissondistribution.hpp.
References lambda_, and QL_REQUIRE.
    : lambda_(lambda) {
        QL_REQUIRE(lambda_ > 0.0, "lambda must be positive");
    }
Member Function Documentation
Real QuantLib::InverseCumulativePoisson::calcSummand (BigNatural index) const [inline, private]
Definition at line 132 of file poissondistribution.hpp.
References QuantLib::detail::get(), lambda_, and QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow().
Referenced by operator()().
{
        return std::exp(-lambda_) * std::pow(lambda_, Integer(index)) /
            Factorial::get(index);
    }
Real QuantLib::InverseCumulativePoisson::operator() (Real x) const [inline]
Definition at line 114 of file poissondistribution.hpp.
References calcSummand(), QL_MAX_REAL, and QL_REQUIRE.
{
        QL_REQUIRE(x >= 0.0 && x <= 1.0,
                   "Inverse cumulative Poisson distribution is "
                   "only defined on the interval [0,1]");
        if (x == 1.0)
            return QL_MAX_REAL;
        Real sum = 0.0;
        BigNatural index = 0;
        while (x > sum) {
            sum += calcSummand(index);
            index++;
        }
        return Real(index-1);
    }
Member Data Documentation
Real QuantLib::InverseCumulativePoisson::lambda_ [private]
Definition at line 82 of file poissondistribution.hpp.
Referenced by calcSummand(), and InverseCumulativePoisson().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/distributions/poissondistribution.hpp