QuantLib: QuantLib::BarrierPathPricer Class Reference
QuantLib::BarrierPathPricer Class Reference
#include <mcbarrierengine.hpp>
Public Member Functions
BarrierPathPricer (Barrier::Type barrierType, Real barrier, Real rebate, Option::Type type, Real strike, const std::vector< DiscountFactor > &discounts, const boost::shared_ptr< StochasticProcess1D > &diffProcess, const PseudoRandom::ursg_type &sequenceGen)
Real operator() (const Path &path) const
Private Attributes
Barrier::Type barrierType_
Real barrier_
Real rebate_
boost::shared_ptr
< StochasticProcess1D > diffProcess_
PseudoRandom::ursg_type sequenceGen_
PlainVanillaPayoff payoff_
std::vector< DiscountFactor > discounts_
Detailed Description
Definition at line 140 of file mcbarrierengine.hpp.
Constructor & Destructor Documentation
QuantLib::BarrierPathPricer::BarrierPathPricer (Barrier::Type barrierType, Real barrier, Real rebate, Option::Type type, Real strike, const std::vector< DiscountFactor > & discounts, const boost::shared_ptr< StochasticProcess1D > & diffProcess, const PseudoRandom::ursg_type & sequenceGen)
Definition at line 26 of file mcbarrierengine.cpp.
References QL_REQUIRE.
    : barrierType_(barrierType), barrier_(barrier),
      rebate_(rebate), diffProcess_(diffProcess),
      sequenceGen_(sequenceGen), payoff_(type, strike),
      discounts_(discounts) {
        QL_REQUIRE(strike>=0.0,
                   "strike less than zero not allowed");
        QL_REQUIRE(barrier>0.0,
                   "barrier less/equal zero not allowed");
    }
Member Function Documentation
Real QuantLib::BarrierPathPricer::operator() (const Path & path) const [virtual]
Implements QuantLib::PathPricer< Path >.
Definition at line 46 of file mcbarrierengine.cpp.
References barrier_, barrierType_, diffProcess_, discounts_, QuantLib::Barrier::DownIn, QuantLib::Barrier::DownOut, QuantLib::anonymous_namespace{yieldtermstructure.cpp}::dt, QuantLib::TimeGrid::dt(), QuantLib::Path::front(), QuantLib::Path::length(), QuantLib::RandomSequenceGenerator< RNG >::nextSequence(), payoff_, QL_FAIL, QL_REQUIRE, rebate_, sequenceGen_, QuantLib::Path::timeGrid(), QuantLib::Barrier::UpIn, QuantLib::Barrier::UpOut, and QuantLib::Sample< T >::value.
{
        static Size null = Null<Size>();
        Size n = path.length();
        QL_REQUIRE(n>1, "the path cannot be empty");
        bool isOptionActive = false;
        Size knockNode = null;
        Real asset_price = path.front();
        Real new_asset_price;
        Real x, y;
        Volatility vol;
        TimeGrid timeGrid = path.timeGrid();
        Time dt;
        std::vector<Real> u = sequenceGen_.nextSequence().value;
        Size i;
        switch (barrierType_) {
          case Barrier::DownIn:
            isOptionActive = false;
            for (i = 0; i < n-1; i++) {
                new_asset_price = path[i+1];
                // terminal or initial vol?
                vol = diffProcess_->diffusion(timeGrid[i],asset_price);
                dt = timeGrid.dt(i);
                x = std::log(new_asset_price / asset_price);
                y = 0.5*(x - std::sqrt (x*x - 2*vol*vol*dt*std::log(u[i])));
                y = asset_price * std::exp(y);
                if (y <= barrier_) {
                    isOptionActive = true;
                    if (knockNode == null)
                        knockNode = i+1;
                }
                asset_price = new_asset_price;
            }
            break;
          case Barrier::UpIn:
            isOptionActive = false;
            for (i = 0; i < n-1; i++) {
                new_asset_price = path[i+1];
                // terminal or initial vol?
                vol = diffProcess_->diffusion(timeGrid[i],asset_price);
                dt = timeGrid.dt(i);
                x = std::log(new_asset_price / asset_price);
                y = 0.5*(x + std::sqrt(x*x - 2*vol*vol*dt*std::log((1-u[i]))));
                y = asset_price * std::exp(y);
                if (y >= barrier_) {
                    isOptionActive = true;
                    if (knockNode == null)
                        knockNode = i+1;
                }
                asset_price = new_asset_price;
            }
            break;
          case Barrier::DownOut:
            isOptionActive = true;
            for (i = 0; i < n-1; i++) {
                new_asset_price = path[i+1];
                // terminal or initial vol?
                vol = diffProcess_->diffusion(timeGrid[i],asset_price);
                dt = timeGrid.dt(i);
                x = std::log(new_asset_price / asset_price);
                y = 0.5*(x - std::sqrt(x*x - 2*vol*vol*dt*std::log(u[i])));
                y = asset_price * std::exp(y);
                if (y <= barrier_) {
                    isOptionActive = false;
                    if (knockNode == null)
                        knockNode = i+1;
                }
                asset_price = new_asset_price;
            }
            break;
          case Barrier::UpOut:
            isOptionActive = true;
            for (i = 0; i < n-1; i++) {
                new_asset_price = path[i+1];
                // terminal or initial vol?
                vol = diffProcess_->diffusion(timeGrid[i],asset_price);
                dt = timeGrid.dt(i);
                x = std::log(new_asset_price / asset_price);
                y = 0.5*(x + std::sqrt(x*x - 2*vol*vol*dt*std::log((1-u[i]))));
                y = asset_price * std::exp(y);
                if (y >= barrier_) {
                    isOptionActive = false;
                    if (knockNode == null)
                        knockNode = i+1;
                }
                asset_price = new_asset_price;
            }
            break;
          default:
            QL_FAIL("unknown barrier type");
        }
        if (isOptionActive) {
            return payoff_(asset_price) * discounts_.back();
        } else {
            switch (barrierType_) {
              case Barrier::UpIn:
              case Barrier::DownIn:
                return rebate_*discounts_.back();
              case Barrier::UpOut:
              case Barrier::DownOut:
                return rebate_*discounts_[knockNode];
              default:
                QL_FAIL("unknown barrier type");
            }
        }
    }
Member Data Documentation
Real QuantLib::BarrierPathPricer::barrier_ [private]
Definition at line 154 of file mcbarrierengine.hpp.
Referenced by operator()().
Barrier::Type QuantLib::BarrierPathPricer::barrierType_ [private]
Definition at line 153 of file mcbarrierengine.hpp.
Referenced by operator()().
boost::shared_ptr<StochasticProcess1D> QuantLib::BarrierPathPricer::diffProcess_ [private]
Definition at line 156 of file mcbarrierengine.hpp.
Referenced by operator()().
std::vector<DiscountFactor> QuantLib::BarrierPathPricer::discounts_ [private]
Definition at line 159 of file mcbarrierengine.hpp.
Referenced by operator()().
PlainVanillaPayoff QuantLib::BarrierPathPricer::payoff_ [private]
Definition at line 158 of file mcbarrierengine.hpp.
Referenced by operator()().
Real QuantLib::BarrierPathPricer::rebate_ [private]
Definition at line 155 of file mcbarrierengine.hpp.
Referenced by operator()().
PseudoRandom::ursg_type QuantLib::BarrierPathPricer::sequenceGen_ [private]
Definition at line 157 of file mcbarrierengine.hpp.
Referenced by operator()().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/barrier/mcbarrierengine.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/barrier/mcbarrierengine.cpp