QuantLib: QuantLib::MultiStepCoterminalSwaptions Class Reference
QuantLib::MultiStepCoterminalSwaptions Class Reference
#include <multistepcoterminalswaptions.hpp>
Public Member Functions
MultiStepCoterminalSwaptions (const std::vector< Time > &rateTimes, const std::vector< Time > &paymentTimes, const std::vector< boost::shared_ptr< StrikedTypePayoff > > &)
MarketModelMultiProduct interface
std::vector< Time > possibleCashFlowTimes () const
Size numberOfProducts () const
Size maxNumberOfCashFlowsPerProductPerStep () const
void reset ()
during simulation put product at start of path
bool nextTimeStep (const CurveState &currentState, std::vector< Size > &numberCashFlowsThisStep, std::vector< std::vector< CashFlow > > &cashFlowsGenerated)
return value indicates whether path is finished, TRUE means done
std::auto_ptr
< MarketModelMultiProduct > clone () const
returns a newly-allocated copy of itself
Private Attributes
std::vector< Time > paymentTimes_
std::vector< boost::shared_ptr
< StrikedTypePayoff > > payoffs_
Size lastIndex_
Size currentIndex_
Detailed Description
Definition at line 31 of file multistepcoterminalswaptions.hpp.
Constructor & Destructor Documentation
QuantLib::MultiStepCoterminalSwaptions::MultiStepCoterminalSwaptions (const std::vector< Time > & rateTimes, const std::vector< Time > & paymentTimes, const std::vector< boost::shared_ptr< StrikedTypePayoff > > & payoffs)
Definition at line 27 of file multistepcoterminalswaptions.cpp.
References QuantLib::checkIncreasingTimes(), and lastIndex_.
Referenced by clone().
    : MultiProductMultiStep(rateTimes),
      paymentTimes_(paymentTimes), payoffs_(payoffs) {
        checkIncreasingTimes(paymentTimes);
        lastIndex_ = rateTimes.size()-1;
    }
Member Function Documentation
std::auto_ptr< MarketModelMultiProduct > QuantLib::MultiStepCoterminalSwaptions::clone () const [virtual]
returns a newly-allocated copy of itself
Implements QuantLib::MarketModelMultiProduct.
Definition at line 58 of file multistepcoterminalswaptions.cpp.
References MultiStepCoterminalSwaptions().
{
        return std::auto_ptr<MarketModelMultiProduct>(
                                         new MultiStepCoterminalSwaptions(*this));
    }
Size QuantLib::MultiStepCoterminalSwaptions::maxNumberOfCashFlowsPerProductPerStep () const [inline, virtual]
Implements QuantLib::MarketModelMultiProduct.
Definition at line 69 of file multistepcoterminalswaptions.hpp.
{
        return 1;
    }
bool QuantLib::MultiStepCoterminalSwaptions::nextTimeStep (const CurveState & currentState, std::vector< Size > & numberCashFlowsThisStep, std::vector< std::vector< CashFlow > > & cashFlowsGenerated) [virtual]
return value indicates whether path is finished, TRUE means done
Implements QuantLib::MarketModelMultiProduct.
Definition at line 38 of file multistepcoterminalswaptions.cpp.
References QuantLib::CurveState::coterminalSwapAnnuity(), QuantLib::CurveState::coterminalSwapRate(), currentIndex_, lastIndex_, and payoffs_.
    {
        genCashFlows[currentIndex_][0].timeIndex = currentIndex_;
        Rate swapRate = currentState.coterminalSwapRate(currentIndex_);
        Real annuity = currentState.coterminalSwapAnnuity(currentIndex_, currentIndex_);
        genCashFlows[currentIndex_][0].amount =
            (*payoffs_[currentIndex_])(swapRate) * annuity;
        std::fill(numberCashFlowsThisStep.begin(),
                  numberCashFlowsThisStep.end(),0);
        numberCashFlowsThisStep[currentIndex_] = 1;
        ++currentIndex_;
        return (currentIndex_ == lastIndex_);
    }
Size QuantLib::MultiStepCoterminalSwaptions::numberOfProducts () const [inline, virtual]
Implements QuantLib::MarketModelMultiProduct.
Definition at line 64 of file multistepcoterminalswaptions.hpp.
References lastIndex_.
{
        return lastIndex_;
    }
std::vector< Time > QuantLib::MultiStepCoterminalSwaptions::possibleCashFlowTimes () const [inline, virtual]
Implements QuantLib::MarketModelMultiProduct.
Definition at line 60 of file multistepcoterminalswaptions.hpp.
References paymentTimes_.
{
        return paymentTimes_;
    }
void QuantLib::MultiStepCoterminalSwaptions::reset () [inline, virtual]
during simulation put product at start of path
Implements QuantLib::MarketModelMultiProduct.
Definition at line 73 of file multistepcoterminalswaptions.hpp.
References currentIndex_.
{
       currentIndex_=0;
    }
Member Data Documentation
Size QuantLib::MultiStepCoterminalSwaptions::currentIndex_ [private]
Definition at line 54 of file multistepcoterminalswaptions.hpp.
Referenced by nextTimeStep(), and reset().
Size QuantLib::MultiStepCoterminalSwaptions::lastIndex_ [private]
Definition at line 52 of file multistepcoterminalswaptions.hpp.
Referenced by MultiStepCoterminalSwaptions(), nextTimeStep(), and numberOfProducts().
std::vector<Time> QuantLib::MultiStepCoterminalSwaptions::paymentTimes_ [private]
Definition at line 50 of file multistepcoterminalswaptions.hpp.
Referenced by possibleCashFlowTimes().
std::vector<boost::shared_ptr<StrikedTypePayoff> > QuantLib::MultiStepCoterminalSwaptions::payoffs_ [private]
Definition at line 51 of file multistepcoterminalswaptions.hpp.
Referenced by nextTimeStep().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/products/multistep/multistepcoterminalswaptions.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/products/multistep/multistepcoterminalswaptions.cpp