QuantLib: QuantLib::InterpolatedZeroInflationCurve< Interpolator > Class Template Reference
QuantLib::InterpolatedZeroInflationCurve< Interpolator > Class Template Reference
Inflation term structure based on the interpolation of zero rates.
#include <interpolatedzeroinflationcurve.hpp>
Public Member Functions
InterpolatedZeroInflationCurve (const Date &referenceDate, const Calendar &calendar, const DayCounter &dayCounter, const Period &lag, Frequency frequency, bool indexIsInterpolated, const Handle< YieldTermStructure > &yTS, const std::vector< Date > &dates, const std::vector< Rate > &rates, const Interpolator &interpolator=Interpolator())
InflationTermStructure interface
Date baseDate () const
minimum (base) date
Date maxDate () const
the latest date for which the curve can return values
Inspectors
const std::vector< Date > & dates () const
const std::vector< Time > & times () const
const std::vector< Real > & data () const
const std::vector< Rate > & rates () const
std::vector< std::pair< Date,
Rate > > nodes () const
Protected Member Functions
InterpolatedZeroInflationCurve (const Date &referenceDate, const Calendar &calendar, const DayCounter &dayCounter, const Period &lag, Frequency frequency, bool indexIsInterpolated, Rate baseZeroRate, const Handle< YieldTermStructure > &yTS, const Interpolator &interpolator=Interpolator())
ZeroInflationTermStructure Interface
Rate zeroRateImpl (Time t) const
to be defined in derived classes
Protected Attributes
std::vector< Date > dates_
Detailed Description
template<class Interpolator>
class QuantLib::InterpolatedZeroInflationCurve< Interpolator >
Inflation term structure based on the interpolation of zero rates.
Definition at line 39 of file interpolatedzeroinflationcurve.hpp.
Constructor & Destructor Documentation
template<class Interpolator > QuantLib::InterpolatedZeroInflationCurve< Interpolator >::InterpolatedZeroInflationCurve (const Date & referenceDate, const Calendar & calendar, const DayCounter & dayCounter, const Period & lag, Frequency frequency, bool indexIsInterpolated, const Handle< YieldTermStructure > & yTS, const std::vector< Date > & dates, const std::vector< Rate > & rates, const Interpolator & interpolator = Interpolator())
Definition at line 101 of file interpolatedzeroinflationcurve.hpp.
References QuantLib::close(), QuantLib::InterpolatedCurve< Interpolator >::data_, QuantLib::InterpolatedZeroInflationCurve< Interpolator >::dates_, QuantLib::InflationTermStructure::frequency(), QuantLib::InflationTermStructure::indexIsInterpolated_, QuantLib::inflationPeriod(), QuantLib::InterpolatedCurve< Interpolator >::interpolation_, QuantLib::InterpolatedCurve< Interpolator >::interpolator_, QuantLib::InflationTermStructure::observationLag(), QL_REQUIRE, QuantLib::TermStructure::timeFromReference(), QuantLib::InterpolatedCurve< Interpolator >::times_, and QuantLib::Interpolation::update().
    : ZeroInflationTermStructure(referenceDate, calendar, dayCounter, rates[0],
                                 lag, frequency, indexIsInterpolated, yTS),
      InterpolatedCurve<Interpolator>(std::vector<Time>(), rates, interpolator),
      dates_(dates) {
          QL_REQUIRE(dates_.size() > 1, "too few dates: " << dates_.size());
          // check that the data starts from the beginning,
          // i.e. referenceDate - lag, at least must be in the relevant
          // period
          std::pair<Date,Date> lim =
                inflationPeriod(yTS->referenceDate() - this->observationLag(), frequency);
          QL_REQUIRE(lim.first <= dates_[0] && dates_[0] <= lim.second,
                   "first data date is not in base period, date: " << dates_[0]
                   << " not within [" << lim.first << "," << lim.second << "]");
          // by convention, if the index is not interpolated we pull all the dates
          // back to the start of their inflationPeriods
          // otherwise the time calculations will be inconsistent
          if (!indexIsInterpolated_) {
              for (Size i = 0; i < dates_.size(); i++) {
                  dates_[i] = inflationPeriod(dates_[i], frequency).first;
              }
          }
          QL_REQUIRE(this->data_.size() == dates_.size(),
                   "indices/dates count mismatch: "
                   << this->data_.size() << " vs " << dates_.size());
          this->times_.resize(dates_.size());
          this->times_[0] = timeFromReference(dates_[0]);
          for (Size i = 1; i < dates_.size(); i++) {
              QL_REQUIRE(dates_[i] > dates_[i-1],
                       "dates not sorted");
              // but must be greater than -1
              QL_REQUIRE(this->data_[i] > -1.0, "zero inflation data < -100 %");
              // this can be negative
              this->times_[i] = timeFromReference(dates_[i]);
              QL_REQUIRE(!close(this->times_[i],this->times_[i-1]),
                       "two dates correspond to the same time "
                       "under this curve's day count convention");
          }
          this->interpolation_ =
                this->interpolator_.interpolate(this->times_.begin(),
                                                this->times_.end(),
                                                this->data_.begin());
          this->interpolation_.update();
    }
template<class Interpolator > QuantLib::InterpolatedZeroInflationCurve< Interpolator >::InterpolatedZeroInflationCurve (const Date & referenceDate, const Calendar & calendar, const DayCounter & dayCounter, const Period & lag, Frequency frequency, bool indexIsInterpolated, Rate baseZeroRate, const Handle< YieldTermStructure > & yTS, const Interpolator & interpolator = Interpolator()) [protected]
Protected version for use when descendents don't want to (or can't) provide the points for interpolation on construction.
Definition at line 168 of file interpolatedzeroinflationcurve.hpp.
    :  ZeroInflationTermStructure(referenceDate, calendar, dayCounter, baseZeroRate,
                                  lag, frequency, indexIsInterpolated, yTS),
       InterpolatedCurve<Interpolator>(interpolator) {
    }
Member Function Documentation
template<class T > Date QuantLib::InterpolatedZeroInflationCurve< T >::baseDate () const [virtual]
minimum (base) date
Important in inflation since it starts before nominal reference date. Changes depending whether index is interpolated or not. When interpolated the base date is just observation lag before nominal. When not interpolated it is the beginning of the relevant period (hence it is easy to create interpolated fixings from a not-interpolated curve because interpolation, usually, of fixings is forward looking).
Implements QuantLib::InflationTermStructure.
Reimplemented in QuantLib::PiecewiseZeroInflationCurve< Interpolator, Bootstrap, Traits >.
Definition at line 184 of file interpolatedzeroinflationcurve.hpp.
{
        // if indexIsInterpolated we fixed the dates in the constructor
        return dates_.front();
    }
template<class T > const std::vector< Real > & QuantLib::InterpolatedZeroInflationCurve< T >::data () const [inline]
Reimplemented in QuantLib::PiecewiseZeroInflationCurve< Interpolator, Bootstrap, Traits >.
Definition at line 226 of file interpolatedzeroinflationcurve.hpp.
{
        return this->data_;
    }
template<class T > const std::vector< Date > & QuantLib::InterpolatedZeroInflationCurve< T >::dates () const [inline]
Reimplemented in QuantLib::PiecewiseZeroInflationCurve< Interpolator, Bootstrap, Traits >.
Definition at line 214 of file interpolatedzeroinflationcurve.hpp.
{
        return dates_;
    }
template<class T > Date QuantLib::InterpolatedZeroInflationCurve< T >::maxDate () const [virtual]
the latest date for which the curve can return values
Implements QuantLib::TermStructure.
Reimplemented in QuantLib::PiecewiseZeroInflationCurve< Interpolator, Bootstrap, Traits >.
Definition at line 190 of file interpolatedzeroinflationcurve.hpp.
References anonymous_namespace{marketmodel.cpp}::d, and QuantLib::inflationPeriod().
{
        Date d;
        if (indexIsInterpolated()) {
            d = dates_.back();
        } else {
            d = inflationPeriod(dates_.back(), frequency()).second;
        }
        return d;
    }
template<class T > std::vector< std::pair< Date, Rate > > QuantLib::InterpolatedZeroInflationCurve< T >::nodes () const [inline]
Reimplemented in QuantLib::PiecewiseZeroInflationCurve< Interpolator, Bootstrap, Traits >.
Definition at line 232 of file interpolatedzeroinflationcurve.hpp.
{
        std::vector<std::pair<Date,Rate> > results(dates_.size());
        for (Size i=0; i<dates_.size(); ++i)
            results[i] = std::make_pair(dates_[i],this->data_[i]);
        return results;
    }
template<class T > const std::vector< Rate > & QuantLib::InterpolatedZeroInflationCurve< T >::rates () const [inline]
Definition at line 220 of file interpolatedzeroinflationcurve.hpp.
{
        return this->data_;
    }
template<class T > const std::vector< Time > & QuantLib::InterpolatedZeroInflationCurve< T >::times () const [inline]
Reimplemented in QuantLib::PiecewiseZeroInflationCurve< Interpolator, Bootstrap, Traits >.
Definition at line 208 of file interpolatedzeroinflationcurve.hpp.
{
        return this->times_;
    }
template<class T > Rate QuantLib::InterpolatedZeroInflationCurve< T >::zeroRateImpl (Time t) const [inline, protected, virtual]
to be defined in derived classes
Implements QuantLib::ZeroInflationTermStructure.
Definition at line 202 of file interpolatedzeroinflationcurve.hpp.
{
        return this->interpolation_(t, true);
    }
Member Data Documentation
template<class Interpolator > std::vector<Date> QuantLib::InterpolatedZeroInflationCurve< Interpolator >::dates_ [mutable, protected]
Definition at line 75 of file interpolatedzeroinflationcurve.hpp.
Referenced by QuantLib::InterpolatedZeroInflationCurve< Interpolator >::InterpolatedZeroInflationCurve().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/inflation/interpolatedzeroinflationcurve.hpp