QuantLib: QuantLib::MarketModelMultiProduct Class Reference
QuantLib::MarketModelMultiProduct Class Reference
market-model product
#include <multiproduct.hpp>
Classes
struct CashFlow
Public Member Functions
virtual ~MarketModelMultiProduct ()
virtual std::vector< Size > suggestedNumeraires () const =0
virtual const
EvolutionDescription & evolution () const =0
virtual std::vector< Time > possibleCashFlowTimes () const =0
virtual Size numberOfProducts () const =0
virtual Size maxNumberOfCashFlowsPerProductPerStep () const =0
virtual void reset ()=0
during simulation put product at start of path
virtual bool nextTimeStep (const CurveState &currentState, std::vector< Size > &numberCashFlowsThisStep, std::vector< std::vector< CashFlow > > &cashFlowsGenerated)=0
return value indicates whether path is finished, TRUE means done
virtual std::auto_ptr
< MarketModelMultiProduct > clone () const =0
returns a newly-allocated copy of itself
Detailed Description
market-model product
This is the abstract base class that encapsulates the notion of a product: it contains the information that would be in the termsheet of the product.
It's useful to have it be able to do several products simultaneously. The products would have to have the same underlying rate times of course. The class is therefore really encapsulating the notion of a multi-product.
For each time evolved to, it generates the cash flows associated to that time for the state of the yield curve. If one was doing a callable product then this would encompass the product and its exercise strategy.
Definition at line 50 of file multiproduct.hpp.
Constructor & Destructor Documentation
virtual QuantLib::MarketModelMultiProduct::~MarketModelMultiProduct () [inline, virtual]
Definition at line 56 of file multiproduct.hpp.
{}
Member Function Documentation
virtual std::auto_ptr<MarketModelMultiProduct> QuantLib::MarketModelMultiProduct::clone () const [pure virtual]
returns a newly-allocated copy of itself
Implemented in QuantLib::anonymous_namespace{upperboundengine.cpp}::DecoratedHedge, QuantLib::MarketModelCashRebate, QuantLib::MultiStepInverseFloater, QuantLib::MultiStepPeriodCapletSwaptions, QuantLib::MultiStepSwaption, QuantLib::CallSpecifiedMultiProduct, QuantLib::MultiProductPathwiseWrapper, QuantLib::MultiStepOptionlets, QuantLib::MultiStepRatchet, QuantLib::MultiStepTarn, QuantLib::OneStepOptionlets, QuantLib::MultiStepSwap, QuantLib::MultiStepCoterminalSwaptions, QuantLib::MultiStepCoinitialSwaps, QuantLib::MultiStepCoterminalSwaps, QuantLib::OneStepCoterminalSwaps, QuantLib::ExerciseAdapter, QuantLib::MultiStepForwards, QuantLib::OneStepCoinitialSwaps, QuantLib::OneStepForwards, QuantLib::MultiProductComposite, QuantLib::SingleProductComposite, and QuantLib::MultiStepNothing.
virtual const EvolutionDescription& QuantLib::MarketModelMultiProduct::evolution () const [pure virtual]
Implemented in QuantLib::MultiProductPathwiseWrapper, QuantLib::MarketModelCashRebate, QuantLib::CallSpecifiedMultiProduct, QuantLib::MarketModelComposite, QuantLib::MultiProductMultiStep, QuantLib::MultiProductOneStep, and QuantLib::ExerciseAdapter.
Referenced by QuantLib::AccountingEngine::AccountingEngine(), QuantLib::MarketModelComposite::add(), QuantLib::CallSpecifiedMultiProduct::CallSpecifiedMultiProduct(), QuantLib::collectNodeData(), anonymous_namespace{marketmodel_smm.cpp}::makeMeasure(), anonymous_namespace{marketmodel_cms.cpp}::makeMeasure(), anonymous_namespace{marketmodel_smmcapletcalibration.cpp}::makeMeasure(), anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::makeMeasure(), anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::makeMeasure(), anonymous_namespace{marketmodel.cpp}::makeMeasure(), QuantLib::ProxyGreekEngine::ProxyGreekEngine(), and testMultiProductComposite().
virtual Size QuantLib::MarketModelMultiProduct::maxNumberOfCashFlowsPerProductPerStep () const [pure virtual]
Implemented in QuantLib::MarketModelCashRebate, QuantLib::MultiStepInverseFloater, QuantLib::MultiStepPeriodCapletSwaptions, QuantLib::MultiStepSwaption, QuantLib::CallSpecifiedMultiProduct, QuantLib::MultiProductPathwiseWrapper, QuantLib::MultiStepOptionlets, QuantLib::MultiStepRatchet, QuantLib::MultiStepTarn, QuantLib::OneStepOptionlets, QuantLib::MultiStepSwap, QuantLib::MultiStepCoterminalSwaptions, QuantLib::ExerciseAdapter, QuantLib::MultiStepCoinitialSwaps, QuantLib::MultiStepCoterminalSwaps, QuantLib::OneStepCoterminalSwaps, QuantLib::MultiProductComposite, QuantLib::MultiStepForwards, QuantLib::OneStepCoinitialSwaps, QuantLib::OneStepForwards, QuantLib::SingleProductComposite, and QuantLib::MultiStepNothing.
Referenced by QuantLib::AccountingEngine::AccountingEngine(), QuantLib::CallSpecifiedMultiProduct::CallSpecifiedMultiProduct(), QuantLib::collectNodeData(), QuantLib::CallSpecifiedMultiProduct::maxNumberOfCashFlowsPerProductPerStep(), and QuantLib::ProxyGreekEngine::ProxyGreekEngine().
virtual bool QuantLib::MarketModelMultiProduct::nextTimeStep (const CurveState & currentState, std::vector< Size > & numberCashFlowsThisStep, std::vector< std::vector< CashFlow > > & cashFlowsGenerated) [pure virtual]
return value indicates whether path is finished, TRUE means done
Implemented in QuantLib::anonymous_namespace{upperboundengine.cpp}::DecoratedHedge, QuantLib::MarketModelCashRebate, QuantLib::MultiStepInverseFloater, QuantLib::MultiStepPeriodCapletSwaptions, QuantLib::MultiStepSwaption, QuantLib::CallSpecifiedMultiProduct, QuantLib::MultiProductPathwiseWrapper, QuantLib::MultiStepOptionlets, QuantLib::MultiStepRatchet, QuantLib::MultiStepTarn, QuantLib::OneStepOptionlets, QuantLib::MultiStepSwap, QuantLib::MultiStepCoterminalSwaptions, QuantLib::MultiStepCoinitialSwaps, QuantLib::MultiStepCoterminalSwaps, QuantLib::OneStepCoterminalSwaps, QuantLib::ExerciseAdapter, QuantLib::MultiStepForwards, QuantLib::OneStepCoinitialSwaps, QuantLib::OneStepForwards, QuantLib::MultiProductComposite, QuantLib::SingleProductComposite, and QuantLib::MultiStepNothing.
Referenced by QuantLib::collectNodeData(), QuantLib::CallSpecifiedMultiProduct::nextTimeStep(), QuantLib::ProxyGreekEngine::singleEvolverValues(), and QuantLib::AccountingEngine::singlePathValues().
virtual Size QuantLib::MarketModelMultiProduct::numberOfProducts () const [pure virtual]
Implemented in QuantLib::MarketModelCashRebate, QuantLib::MultiStepInverseFloater, QuantLib::MultiStepPeriodCapletSwaptions, QuantLib::MultiStepSwaption, QuantLib::CallSpecifiedMultiProduct, QuantLib::MultiProductPathwiseWrapper, QuantLib::MultiStepOptionlets, QuantLib::MultiStepRatchet, QuantLib::MultiStepTarn, QuantLib::OneStepOptionlets, QuantLib::MultiStepSwap, QuantLib::MultiStepCoterminalSwaptions, QuantLib::MultiStepCoinitialSwaps, QuantLib::MultiStepCoterminalSwaps, QuantLib::OneStepCoterminalSwaps, QuantLib::MultiProductComposite, QuantLib::ExerciseAdapter, QuantLib::MultiStepForwards, QuantLib::OneStepCoinitialSwaps, QuantLib::OneStepForwards, QuantLib::SingleProductComposite, and QuantLib::MultiStepNothing.
Referenced by QuantLib::CallSpecifiedMultiProduct::CallSpecifiedMultiProduct(), QuantLib::collectNodeData(), QuantLib::AccountingEngine::multiplePathValues(), QuantLib::ProxyGreekEngine::multiplePathValues(), QuantLib::CallSpecifiedMultiProduct::numberOfProducts(), anonymous_namespace{swapforwardmappings.cpp}::simulate(), anonymous_namespace{marketmodel_smm.cpp}::simulate(), anonymous_namespace{marketmodel_cms.cpp}::simulate(), anonymous_namespace{marketmodel_smmcapletcalibration.cpp}::simulate(), anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::simulate(), anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::simulate(), anonymous_namespace{marketmodel.cpp}::simulate(), and QuantLib::UpperBoundEngine::UpperBoundEngine().
virtual std::vector<Time> QuantLib::MarketModelMultiProduct::possibleCashFlowTimes () const [pure virtual]
Implemented in QuantLib::MarketModelCashRebate, QuantLib::MultiStepInverseFloater, QuantLib::MultiStepPeriodCapletSwaptions, QuantLib::MultiStepSwaption, QuantLib::MarketModelComposite, QuantLib::CallSpecifiedMultiProduct, QuantLib::MultiProductPathwiseWrapper, QuantLib::MultiStepOptionlets, QuantLib::MultiStepRatchet, QuantLib::MultiStepTarn, QuantLib::OneStepOptionlets, QuantLib::MultiStepSwap, QuantLib::MultiStepCoterminalSwaptions, QuantLib::MultiStepCoinitialSwaps, QuantLib::MultiStepCoterminalSwaps, QuantLib::OneStepCoterminalSwaps, QuantLib::ExerciseAdapter, QuantLib::MultiStepForwards, QuantLib::OneStepCoinitialSwaps, QuantLib::OneStepForwards, and QuantLib::MultiStepNothing.
Referenced by QuantLib::AccountingEngine::AccountingEngine(), QuantLib::CallSpecifiedMultiProduct::CallSpecifiedMultiProduct(), QuantLib::collectNodeData(), and QuantLib::ProxyGreekEngine::ProxyGreekEngine().
virtual void QuantLib::MarketModelMultiProduct::reset () [pure virtual]
during simulation put product at start of path
Implemented in QuantLib::anonymous_namespace{upperboundengine.cpp}::DecoratedHedge, QuantLib::MarketModelCashRebate, QuantLib::MultiStepInverseFloater, QuantLib::MultiStepPeriodCapletSwaptions, QuantLib::MultiStepSwaption, QuantLib::CallSpecifiedMultiProduct, QuantLib::MultiProductPathwiseWrapper, QuantLib::MarketModelComposite, QuantLib::MultiStepOptionlets, QuantLib::MultiStepRatchet, QuantLib::MultiStepTarn, QuantLib::OneStepOptionlets, QuantLib::MultiStepSwap, QuantLib::MultiStepCoterminalSwaptions, QuantLib::ExerciseAdapter, QuantLib::MultiStepCoinitialSwaps, QuantLib::MultiStepCoterminalSwaps, QuantLib::OneStepCoterminalSwaps, QuantLib::MultiStepForwards, QuantLib::OneStepCoinitialSwaps, QuantLib::OneStepForwards, and QuantLib::MultiStepNothing.
Referenced by QuantLib::collectNodeData(), QuantLib::CallSpecifiedMultiProduct::reset(), QuantLib::ProxyGreekEngine::singleEvolverValues(), and QuantLib::AccountingEngine::singlePathValues().
virtual std::vector<Size> QuantLib::MarketModelMultiProduct::suggestedNumeraires () const [pure virtual]
Implemented in QuantLib::MultiProductPathwiseWrapper, QuantLib::MarketModelCashRebate, QuantLib::MarketModelComposite, QuantLib::CallSpecifiedMultiProduct, QuantLib::MultiProductOneStep, and QuantLib::MultiProductMultiStep.
Referenced by anonymous_namespace{marketmodel_smm.cpp}::makeMeasure(), anonymous_namespace{marketmodel_cms.cpp}::makeMeasure(), anonymous_namespace{marketmodel_smmcapletcalibration.cpp}::makeMeasure(), anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::makeMeasure(), anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::makeMeasure(), anonymous_namespace{marketmodel.cpp}::makeMeasure(), and QuantLib::CallSpecifiedMultiProduct::suggestedNumeraires().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/multiproduct.hpp