QuantLib: QuantLib::MultiStepOptionlets Class Reference
QuantLib::MultiStepOptionlets Class Reference
#include <multistepoptionlets.hpp>
Public Member Functions
MultiStepOptionlets (const std::vector< Time > &rateTimes, const std::vector< Real > &accruals, const std::vector< Time > &paymentTimes, const std::vector< boost::shared_ptr< Payoff > > &)
MarketModelMultiProduct interface
std::vector< Time > possibleCashFlowTimes () const
Size numberOfProducts () const
Size maxNumberOfCashFlowsPerProductPerStep () const
void reset ()
during simulation put product at start of path
bool nextTimeStep (const CurveState &currentState, std::vector< Size > &numberCashFlowsThisStep, std::vector< std::vector< CashFlow > > &cashFlowsGenerated)
return value indicates whether path is finished, TRUE means done
std::auto_ptr
< MarketModelMultiProduct > clone () const
returns a newly-allocated copy of itself
Private Attributes
std::vector< Real > accruals_
std::vector< Time > paymentTimes_
std::vector< boost::shared_ptr
< Payoff > > payoffs_
Size currentIndex_
Detailed Description
Definition at line 32 of file multistepoptionlets.hpp.
Constructor & Destructor Documentation
QuantLib::MultiStepOptionlets::MultiStepOptionlets (const std::vector< Time > & rateTimes, const std::vector< Real > & accruals, const std::vector< Time > & paymentTimes, const std::vector< boost::shared_ptr< Payoff > > & payoffs)
Definition at line 28 of file multistepoptionlets.cpp.
References QuantLib::checkIncreasingTimes().
Referenced by clone().
    : MultiProductMultiStep(rateTimes), accruals_(accruals),
      paymentTimes_(paymentTimes), payoffs_(payoffs) {
        checkIncreasingTimes(paymentTimes);
    }
Member Function Documentation
std::auto_ptr< MarketModelMultiProduct > QuantLib::MultiStepOptionlets::clone () const [virtual]
returns a newly-allocated copy of itself
Implements QuantLib::MarketModelMultiProduct.
Definition at line 55 of file multistepoptionlets.cpp.
References MultiStepOptionlets().
{
        return std::auto_ptr<MarketModelMultiProduct>(
                                                 new MultiStepOptionlets(*this));
    }
Size QuantLib::MultiStepOptionlets::maxNumberOfCashFlowsPerProductPerStep () const [inline, virtual]
Implements QuantLib::MarketModelMultiProduct.
Definition at line 70 of file multistepoptionlets.hpp.
Referenced by MarketModelTest::testPathwiseVegas().
{
        return 1;
    }
bool QuantLib::MultiStepOptionlets::nextTimeStep (const CurveState & currentState, std::vector< Size > & numberCashFlowsThisStep, std::vector< std::vector< CashFlow > > & cashFlowsGenerated) [virtual]
return value indicates whether path is finished, TRUE means done
Implements QuantLib::MarketModelMultiProduct.
Definition at line 38 of file multistepoptionlets.cpp.
References accruals_, currentIndex_, QuantLib::CurveState::forwardRate(), and payoffs_.
Referenced by MarketModelTest::testPathwiseVegas().
{
        Rate liborRate = currentState.forwardRate(currentIndex_);
        genCashFlows[currentIndex_][0].timeIndex = currentIndex_;
        genCashFlows[currentIndex_][0].amount =
            (*payoffs_[currentIndex_])(liborRate) *
            accruals_[currentIndex_];
        std::fill(numberCashFlowsThisStep.begin(),
                  numberCashFlowsThisStep.end(), 0);
        numberCashFlowsThisStep[currentIndex_] = 1;
        ++currentIndex_;
        return (currentIndex_ == payoffs_.size());
    }
Size QuantLib::MultiStepOptionlets::numberOfProducts () const [inline, virtual]
Implements QuantLib::MarketModelMultiProduct.
Definition at line 65 of file multistepoptionlets.hpp.
References payoffs_.
Referenced by MarketModelTest::testGreeks(), and MarketModelTest::testPathwiseVegas().
{
        return payoffs_.size();
    }
std::vector< Time > QuantLib::MultiStepOptionlets::possibleCashFlowTimes () const [inline, virtual]
Implements QuantLib::MarketModelMultiProduct.
Definition at line 61 of file multistepoptionlets.hpp.
References paymentTimes_.
{
      return paymentTimes_;
    }
void QuantLib::MultiStepOptionlets::reset () [inline, virtual]
during simulation put product at start of path
Implements QuantLib::MarketModelMultiProduct.
Definition at line 74 of file multistepoptionlets.hpp.
References currentIndex_.
Referenced by MarketModelTest::testPathwiseVegas().
{
       currentIndex_=0;
    }
Member Data Documentation
std::vector<Real> QuantLib::MultiStepOptionlets::accruals_ [private]
Definition at line 51 of file multistepoptionlets.hpp.
Referenced by nextTimeStep().
Size QuantLib::MultiStepOptionlets::currentIndex_ [private]
Definition at line 55 of file multistepoptionlets.hpp.
Referenced by nextTimeStep(), and reset().
std::vector<Time> QuantLib::MultiStepOptionlets::paymentTimes_ [private]
Definition at line 52 of file multistepoptionlets.hpp.
Referenced by possibleCashFlowTimes().
std::vector<boost::shared_ptr<Payoff> > QuantLib::MultiStepOptionlets::payoffs_ [private]
Definition at line 53 of file multistepoptionlets.hpp.
Referenced by nextTimeStep(), and numberOfProducts().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/products/multistep/multistepoptionlets.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/products/multistep/multistepoptionlets.cpp