QuantLib: FactorialTest Class Reference
FactorialTest Class Reference
#include <factorial.hpp>
Static Public Member Functions
static void testFactorial ()
static void testGammaFunction ()
static
boost::unit_test_framework::test_suite * suite ()
Detailed Description
Definition at line 28 of file factorial.hpp.
Member Function Documentation
test_suite * FactorialTest::suite () [static]
Definition at line 76 of file factorial.cpp.
References QUANTLIB_TEST_CASE, testFactorial(), and testGammaFunction().
Referenced by init_unit_test_suite().
{
    test_suite* suite = BOOST_TEST_SUITE("Factorial tests");
    suite->add(QUANTLIB_TEST_CASE(&FactorialTest::testFactorial));
    suite->add(QUANTLIB_TEST_CASE(&FactorialTest::testGammaFunction));
    return suite;
}
void FactorialTest::testFactorial () [static]
Definition at line 28 of file factorial.cpp.
References QuantLib::detail::get(), and QL_SCIENTIFIC.
Referenced by suite().
{
    BOOST_MESSAGE("Testing factorial numbers...");
    Real expected = 1.0;
    Real calculated = Factorial::get(0);
    if (calculated!=expected)
        BOOST_FAIL("Factorial(0) = " << calculated);
    for (Natural i=1; i<171; ++i) {
        expected *= i;
        calculated = Factorial::get(i);
        if (std::fabs(calculated-expected)/expected > 1.0e-9)
            BOOST_FAIL("Factorial(" << i << ")" <<
                       std::setprecision(16) << QL_SCIENTIFIC <<
                       "\n calculated: " << calculated <<
                       "\n   expected: " << expected <<
                       "\n rel. error: " <<
                       std::fabs(calculated-expected)/expected);
    }
}
void FactorialTest::testGammaFunction () [static]
Definition at line 50 of file factorial.cpp.
References QuantLib::GammaFunction::logValue(), and QL_SCIENTIFIC.
Referenced by suite().
{
    BOOST_MESSAGE("Testing Gamma function...");
    Real expected = 0.0;
    Real calculated = GammaFunction().logValue(1);
    if (std::fabs(calculated) > 1.0e-15)
        BOOST_ERROR("GammaFunction(1)\n"
                    << std::setprecision(16) << QL_SCIENTIFIC
                    << "    calculated: " << calculated << "\n"
                    << "    expected:   " << expected);
    for (Size i=2; i<9000; i++) {
        expected  += std::log(Real(i));
        calculated = GammaFunction().logValue(i+1);
        if (std::fabs(calculated-expected)/expected > 1.0e-9)
            BOOST_ERROR("GammaFunction(" << i << ")\n"
                        << std::setprecision(16) << QL_SCIENTIFIC
                        << "    calculated: " << calculated << "\n"
                        << "    expected:   " << expected << "\n"
                        << "    rel. error: "
                        << std::fabs(calculated-expected)/expected);
    }
}
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/factorial.hpp
/home/deriversatile/QuantLib/QuantLibQt/test-suite/factorial.cpp