QuantLib: anonymous_namespace{swapforwardmappings.cpp}::MarketModelData Class Reference
anonymous_namespace{swapforwardmappings.cpp}::MarketModelData Class Reference
Public Member Functions
MarketModelData ()
const std::vector< Time > & rateTimes ()
const std::vector< Rate > & forwards ()
const std::vector< Volatility > & volatilities ()
const std::vector< Rate > & displacements ()
const std::vector
< DiscountFactor > & discountFactors ()
Size nbRates ()
Private Attributes
std::vector< Time > rateTimes_
std::vector< Time > accruals_
std::vector< Rate > forwards_
std::vector< Spread > displacements_
std::vector< Volatility > volatilities_
std::vector< DiscountFactor > discountFactors_
Size nbRates_
Detailed Description
Definition at line 55 of file swapforwardmappings.cpp.
Constructor & Destructor Documentation
anonymous_namespace{swapforwardmappings.cpp}::MarketModelData::MarketModelData ()
Definition at line 73 of file swapforwardmappings.cpp.
References anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::accruals_, QuantLib::DateGeneration::Backward, anonymous_namespace{marketmodel.cpp}::calendar, anonymous_namespace{marketmodel.cpp}::dates, anonymous_namespace{marketmodel.cpp}::dayCounter, anonymous_namespace{marketmodel.cpp}::endDate, QuantLib::Settings::evaluationDate(), QuantLib::Following, QuantLib::Singleton< Settings >::instance(), anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::rateTimes_, QuantLib::Semiannual, QuantLib::Schedule::size(), anonymous_namespace{marketmodel.cpp}::todaysDate, and QuantLib::Years.
{
        // Times
        Calendar calendar = NullCalendar();
        Date todaysDate = Settings::instance().evaluationDate();
        Date endDate = todaysDate + 9*Years; // change back
        Schedule dates(todaysDate, endDate, Period(Semiannual),
            calendar, Following, Following, DateGeneration::Backward, false);
        nbRates_ = dates.size()-2;
        rateTimes_ = std::vector<Time>(nbRates_+1);
        //paymentTimes_ = std::vector<Time>(rateTimes_.size()-1);
        accruals_ = std::vector<Time>(nbRates_);
        DayCounter dayCounter = SimpleDayCounter();
        for (Size i=1; i<nbRates_+2; ++i)
            rateTimes_[i-1] = dayCounter.yearFraction(todaysDate, dates[i]);
        displacements_ = std::vector<Rate>(nbRates_, .0);
        forwards_ = std::vector<Rate>(nbRates_);
        discountFactors_ = std::vector<Rate>(nbRates_+1);
        discountFactors_[0] = 1.0; // .95; fdv1-> WHY ???????
        for (Size i=0; i<nbRates_; ++i){
            forwards_[i] = 0.03 + 0.0010*i;
            accruals_[i] = rateTimes_[i+1] - rateTimes_[i];
            discountFactors_[i+1] = discountFactors_[i]
            /(1+forwards_[i]*accruals_[i]);
        }
        Volatility mktVols[] = {0.15541283,
            0.18719678,
            0.20890740,
            0.22318179,
            0.23212717,
            0.23731450,
            0.23988649,
            0.24066384,
            0.24023111,
            0.23900189,
            0.23726699,
            0.23522952,
            0.23303022,
            0.23076564,
            0.22850101,
            0.22627951,
            0.22412881,
            0.22206569,
            0.22009939
            /*
            0.2,
            0.2,
            0.2,
            0.2,
            0.2,
            0.2,
            0.2,
            0.2,
            0.2,
            0.2,
            0.2,
            0.2,
            0.2,
            0.2,
            0.2,
            0.2,
            0.2,
            0.2,
            0.2,
            0.2
            */
        };
        volatilities_ = std::vector<Volatility>(nbRates_);
        for (Size i = 0; i < volatilities_.size(); ++i)
            volatilities_[i] =   mktVols[i];//.0;
    }
Member Function Documentation
const std::vector<DiscountFactor>& anonymous_namespace{swapforwardmappings.cpp}::MarketModelData::discountFactors () [inline]
Definition at line 62 of file swapforwardmappings.cpp.
{return discountFactors_;}
const std::vector<Rate>& anonymous_namespace{swapforwardmappings.cpp}::MarketModelData::displacements () [inline]
Definition at line 61 of file swapforwardmappings.cpp.
{return displacements_;}
const std::vector<Rate>& anonymous_namespace{swapforwardmappings.cpp}::MarketModelData::forwards () [inline]
Definition at line 59 of file swapforwardmappings.cpp.
{return forwards_;}
Size anonymous_namespace{swapforwardmappings.cpp}::MarketModelData::nbRates () [inline]
Definition at line 63 of file swapforwardmappings.cpp.
{return nbRates_;}
const std::vector<Time>& anonymous_namespace{swapforwardmappings.cpp}::MarketModelData::rateTimes () [inline]
Definition at line 58 of file swapforwardmappings.cpp.
References anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::rateTimes_.
{return rateTimes_;}
const std::vector<Volatility>& anonymous_namespace{swapforwardmappings.cpp}::MarketModelData::volatilities () [inline]
Definition at line 60 of file swapforwardmappings.cpp.
{return volatilities_;}
Member Data Documentation
std::vector<Time> anonymous_namespace{swapforwardmappings.cpp}::MarketModelData::accruals_ [private]
Definition at line 65 of file swapforwardmappings.cpp.
std::vector<DiscountFactor> anonymous_namespace{swapforwardmappings.cpp}::MarketModelData::discountFactors_ [private]
Definition at line 69 of file swapforwardmappings.cpp.
std::vector<Spread> anonymous_namespace{swapforwardmappings.cpp}::MarketModelData::displacements_ [private]
Definition at line 67 of file swapforwardmappings.cpp.
std::vector<Rate> anonymous_namespace{swapforwardmappings.cpp}::MarketModelData::forwards_ [private]
Definition at line 66 of file swapforwardmappings.cpp.
Size anonymous_namespace{swapforwardmappings.cpp}::MarketModelData::nbRates_ [private]
Definition at line 70 of file swapforwardmappings.cpp.
std::vector<Time> anonymous_namespace{swapforwardmappings.cpp}::MarketModelData::rateTimes_ [private]
Definition at line 65 of file swapforwardmappings.cpp.
std::vector<Volatility> anonymous_namespace{swapforwardmappings.cpp}::MarketModelData::volatilities_ [private]
Definition at line 68 of file swapforwardmappings.cpp.
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/swapforwardmappings.cpp