QuantLib: QuantLib::ConvertibleFixedCouponBond Class Reference
QuantLib::ConvertibleFixedCouponBond Class Reference
convertible fixed-coupon bond
#include <convertiblebond.hpp>
Public Member Functions
ConvertibleFixedCouponBond (const boost::shared_ptr< Exercise > &exercise, Real conversionRatio, const DividendSchedule &dividends, const CallabilitySchedule &callability, const Handle< Quote > &creditSpread, const Date &issueDate, Natural settlementDays, const std::vector< Rate > &coupons, const DayCounter &dayCounter, const Schedule &schedule, Real redemption=100)
Detailed Description
convertible fixed-coupon bond
Warning:
Most methods inherited from Bond (such as yield or the yield-based dirtyPrice and cleanPrice) refer to the underlying plain-vanilla bond and do not take convertibility and callability into account.
Definition at line 109 of file convertiblebond.hpp.
Constructor & Destructor Documentation
QuantLib::ConvertibleFixedCouponBond::ConvertibleFixedCouponBond (const boost::shared_ptr< Exercise > & exercise, Real conversionRatio, const DividendSchedule & dividends, const CallabilitySchedule & callability, const Handle< Quote > & creditSpread, const Date & issueDate, Natural settlementDays, const std::vector< Rate > & coupons, const DayCounter & dayCounter, const Schedule & schedule, Real redemption = 100)
Definition at line 93 of file convertiblebond.cpp.
References QuantLib::Bond::addRedemptionsToCashflows(), QuantLib::Schedule::businessDayConvention(), QuantLib::Bond::cashflows_, QuantLib::ConvertibleBond::option_, QL_ENSURE, QuantLib::Bond::redemptions_, QuantLib::FixedRateLeg::withCouponRates(), QuantLib::FixedRateLeg::withNotionals(), and QuantLib::FixedRateLeg::withPaymentAdjustment().
    : ConvertibleBond(exercise, conversionRatio, dividends, callability,
                      creditSpread, issueDate, settlementDays,
                      schedule, redemption) {
        // !!! notional forcibly set to 100
        cashflows_ = FixedRateLeg(schedule)
            .withNotionals(100.0)
            .withCouponRates(coupons, dayCounter)
            .withPaymentAdjustment(schedule.businessDayConvention());
        addRedemptionsToCashflows(std::vector<Real>(1, redemption));
        QL_ENSURE(redemptions_.size() == 1, "multiple redemptions created");
        option_ = boost::shared_ptr<option>(
                           new option(this, exercise, conversionRatio,
                                      dividends, callability, creditSpread,
                                      cashflows_, dayCounter, schedule,
                                      issueDate, settlementDays, redemption));
    }
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/convertiblebonds/convertiblebond.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/convertiblebonds/convertiblebond.cpp