QuantLib: QuantLib::FixedRateCoupon Class Reference
QuantLib::FixedRateCoupon Class Reference
Coupon paying a fixed interest rate
#include <fixedratecoupon.hpp>
Public Member Functions
constructors
FixedRateCoupon (const Date &paymentDate, Real nominal, Rate rate, const DayCounter &dayCounter, const Date &accrualStartDate, const Date &accrualEndDate, const Date &refPeriodStart=Date(), const Date &refPeriodEnd=Date())
FixedRateCoupon (const Date &paymentDate, Real nominal, const InterestRate &interestRate, const Date &accrualStartDate, const Date &accrualEndDate, const Date &refPeriodStart=Date(), const Date &refPeriodEnd=Date())
CashFlow interface
Real amount () const
returns the amount of the cash flow
Coupon interface
Rate rate () const
accrued rate
InterestRate interestRate () const
DayCounter dayCounter () const
day counter for accrual calculation
Real accruedAmount (const Date &) const
accrued amount at the given date
Visitability
virtual void accept (AcyclicVisitor &)
Private Attributes
InterestRate rate_
Detailed Description
Coupon paying a fixed interest rate
Definition at line 38 of file fixedratecoupon.hpp.
Constructor & Destructor Documentation
QuantLib::FixedRateCoupon::FixedRateCoupon (const Date & paymentDate, Real nominal, Rate rate, const DayCounter & dayCounter, const Date & accrualStartDate, const Date & accrualEndDate, const Date & refPeriodStart = Date(), const Date & refPeriodEnd = Date())
Definition at line 31 of file fixedratecoupon.cpp.
    : Coupon(paymentDate, nominal, accrualStartDate, accrualEndDate,
             refPeriodStart, refPeriodEnd),
      rate_(InterestRate(rate, dayCounter, Simple, Annual)) {}
QuantLib::FixedRateCoupon::FixedRateCoupon (const Date & paymentDate, Real nominal, const InterestRate & interestRate, const Date & accrualStartDate, const Date & accrualEndDate, const Date & refPeriodStart = Date(), const Date & refPeriodEnd = Date())
Definition at line 43 of file fixedratecoupon.cpp.
    : Coupon(paymentDate, nominal, accrualStartDate, accrualEndDate,
             refPeriodStart, refPeriodEnd),
      rate_(interestRate) {}
Member Function Documentation
void QuantLib::FixedRateCoupon::accept (AcyclicVisitor & v) [inline, virtual]
Reimplemented from QuantLib::Coupon.
Definition at line 108 of file fixedratecoupon.hpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Visitor< T >::visit().
{
        Visitor<FixedRateCoupon>* v1 =
            dynamic_cast<Visitor<FixedRateCoupon>*>(&v);
        if (v1 != 0)
            v1->visit(*this);
        else
            Coupon::accept(v);
    }
Real QuantLib::FixedRateCoupon::accruedAmount (const Date &) const [virtual]
accrued amount at the given date
Implements QuantLib::Coupon.
Definition at line 61 of file fixedratecoupon.cpp.
References QuantLib::Coupon::accrualEndDate_, QuantLib::Coupon::accrualStartDate_, QuantLib::InterestRate::compoundFactor(), QuantLib::Coupon::nominal(), QuantLib::Coupon::paymentDate_, rate_, QuantLib::Coupon::refPeriodEnd_, and QuantLib::Coupon::refPeriodStart_.
{
        if (d <= accrualStartDate_ || d > paymentDate_) {
            return 0.0;
        } else {
            return nominal()*(rate_.compoundFactor(accrualStartDate_,
                                                   std::min(d,accrualEndDate_),
                                                   refPeriodStart_,
                                                   refPeriodEnd_) - 1.0);
        }
    }
Real QuantLib::FixedRateCoupon::amount () const [virtual]
returns the amount of the cash flow
Note:
The amount is not discounted, i.e., it is the actual amount paid at the cash flow date.
Implements QuantLib::CashFlow.
Definition at line 54 of file fixedratecoupon.cpp.
References QuantLib::Coupon::accrualEndDate_, QuantLib::Coupon::accrualStartDate_, QuantLib::InterestRate::compoundFactor(), QuantLib::Coupon::nominal(), rate_, QuantLib::Coupon::refPeriodEnd_, and QuantLib::Coupon::refPeriodStart_.
{
        return nominal()*(rate_.compoundFactor(accrualStartDate_,
                                               accrualEndDate_,
                                               refPeriodStart_,
                                               refPeriodEnd_) - 1.0);
    }
DayCounter QuantLib::FixedRateCoupon::dayCounter () const [inline, virtual]
day counter for accrual calculation
Implements QuantLib::Coupon.
Definition at line 66 of file fixedratecoupon.hpp.
References QuantLib::InterestRate::dayCounter(), and rate_.
{ return rate_.dayCounter(); }
InterestRate QuantLib::FixedRateCoupon::interestRate () const [inline]
Definition at line 65 of file fixedratecoupon.hpp.
References rate_.
{ return rate_; }
Rate QuantLib::FixedRateCoupon::rate () const [inline, virtual]
accrued rate
Implements QuantLib::Coupon.
Definition at line 64 of file fixedratecoupon.hpp.
References rate_.
{ return rate_; }
Member Data Documentation
InterestRate QuantLib::FixedRateCoupon::rate_ [private]
Definition at line 74 of file fixedratecoupon.hpp.
Referenced by accruedAmount(), amount(), dayCounter(), interestRate(), and rate().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/fixedratecoupon.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/fixedratecoupon.cpp