QuantLib: QuantLib::DiscretizedSwap Class Reference
QuantLib::DiscretizedSwap Class Reference
#include <discretizedswap.hpp>
Public Member Functions
DiscretizedSwap (const VanillaSwap::arguments &, const Date &referenceDate, const DayCounter &dayCounter)
void reset (Size size)
std::vector< Time > mandatoryTimes () const
Protected Member Functions
void preAdjustValuesImpl ()
void postAdjustValuesImpl ()
Private Attributes
VanillaSwap::arguments arguments_
std::vector< Time > fixedResetTimes_
std::vector< Time > fixedPayTimes_
std::vector< Time > floatingResetTimes_
std::vector< Time > floatingPayTimes_
Detailed Description
Definition at line 33 of file discretizedswap.hpp.
Constructor & Destructor Documentation
QuantLib::DiscretizedSwap::DiscretizedSwap (const VanillaSwap::arguments & args, const Date & referenceDate, const DayCounter & dayCounter)
Definition at line 25 of file discretizedswap.cpp.
References QuantLib::VanillaSwap::arguments::fixedPayDates, fixedPayTimes_, QuantLib::VanillaSwap::arguments::fixedResetDates, fixedResetTimes_, QuantLib::VanillaSwap::arguments::floatingPayDates, floatingPayTimes_, QuantLib::VanillaSwap::arguments::floatingResetDates, floatingResetTimes_, and QuantLib::DayCounter::yearFraction().
    : arguments_(args) {
        fixedResetTimes_.resize(args.fixedResetDates.size());
        for (Size i=0; i<fixedResetTimes_.size(); ++i)
            fixedResetTimes_[i] =
                dayCounter.yearFraction(referenceDate,
                                        args.fixedResetDates[i]);
        fixedPayTimes_.resize(args.fixedPayDates.size());
        for (Size i=0; i<fixedPayTimes_.size(); ++i)
            fixedPayTimes_[i] =
                dayCounter.yearFraction(referenceDate,
                                        args.fixedPayDates[i]);
        floatingResetTimes_.resize(args.floatingResetDates.size());
        for (Size i=0; i<floatingResetTimes_.size(); ++i)
            floatingResetTimes_[i] =
                dayCounter.yearFraction(referenceDate,
                                        args.floatingResetDates[i]);
        floatingPayTimes_.resize(args.floatingPayDates.size());
        for (Size i=0; i<floatingPayTimes_.size(); ++i)
            floatingPayTimes_[i] =
                dayCounter.yearFraction(referenceDate,
                                        args.floatingPayDates[i]);
    }
Member Function Documentation
std::vector< Time > QuantLib::DiscretizedSwap::mandatoryTimes () const [virtual]
This method returns the times at which the numerical method should stop while rolling back the asset. Typical examples include payment times, exercise times and such.
Note:
The returned values are not guaranteed to be sorted.
Implements QuantLib::DiscretizedAsset.
Definition at line 60 of file discretizedswap.cpp.
References fixedPayTimes_, fixedResetTimes_, floatingPayTimes_, floatingResetTimes_, and anonymous_namespace{quantlibbenchmark.cpp}::t.
Referenced by QuantLib::TreeVanillaSwapEngine::calculate().
{
        std::vector<Time> times;
        for (Size i=0; i<fixedResetTimes_.size(); i++) {
            Time t = fixedResetTimes_[i];
            if (t >= 0.0)
                times.push_back(t);
        }
        for (Size i=0; i<fixedPayTimes_.size(); i++) {
            Time t = fixedPayTimes_[i];
            if (t >= 0.0)
                times.push_back(t);
        }
        for (Size i=0; i<floatingResetTimes_.size(); i++) {
            Time t = floatingResetTimes_[i];
            if (t >= 0.0)
                times.push_back(t);
        }
        for (Size i=0; i<floatingPayTimes_.size(); i++) {
            Time t = floatingPayTimes_[i];
            if (t >= 0.0)
                times.push_back(t);
        }
        return times;
    }
void QuantLib::DiscretizedSwap::postAdjustValuesImpl () [protected, virtual]
This method performs the actual post-adjustment
Reimplemented from QuantLib::DiscretizedAsset.
Definition at line 128 of file discretizedswap.cpp.
References arguments_, QuantLib::VanillaSwap::arguments::fixedCoupons, fixedPayTimes_, fixedResetTimes_, QuantLib::VanillaSwap::arguments::floatingCoupons, floatingPayTimes_, floatingResetTimes_, QuantLib::DiscretizedAsset::isOnTime(), QuantLib::VanillaSwap::Payer, QL_REQUIRE, reset(), anonymous_namespace{quantlibbenchmark.cpp}::t, QuantLib::VanillaSwap::arguments::type, and QuantLib::DiscretizedAsset::values_.
{
        // fixed coupons whose reset time is in the past won't be managed
        // in preAdjustValues()
        for (Size i=0; i<fixedPayTimes_.size(); i++) {
            Time t = fixedPayTimes_[i];
            Time reset = fixedResetTimes_[i];
            if (t >= 0.0 && isOnTime(t) && reset < 0.0) {
                Real fixedCoupon = arguments_.fixedCoupons[i];
                if (arguments_.type==VanillaSwap::Payer)
                    values_ -= fixedCoupon;
                else
                    values_ += fixedCoupon;
            }
        }
        // the same applies to floating payments whose rate is already fixed
        for (Size i=0; i<floatingPayTimes_.size(); i++) {
            Time t = floatingPayTimes_[i];
            Time reset = floatingResetTimes_[i];
            if (t >= 0.0 && isOnTime(t) && reset < 0.0) {
                Real currentFloatingCoupon = arguments_.floatingCoupons[i];
                QL_REQUIRE(currentFloatingCoupon != Null<Real>(),
                           "current floating coupon not given");
                if (arguments_.type == VanillaSwap::Payer)
                    values_ += currentFloatingCoupon;
                else
                    values_ -= currentFloatingCoupon;
            }
        }
    }
void QuantLib::DiscretizedSwap::preAdjustValuesImpl () [protected, virtual]
This method performs the actual pre-adjustment
Reimplemented from QuantLib::DiscretizedAsset.
Definition at line 85 of file discretizedswap.cpp.
References arguments_, QuantLib::VanillaSwap::arguments::fixedCoupons, fixedPayTimes_, fixedResetTimes_, QuantLib::VanillaSwap::arguments::floatingAccrualTimes, floatingPayTimes_, floatingResetTimes_, QuantLib::VanillaSwap::arguments::floatingSpreads, QuantLib::DiscretizedAsset::initialize(), QuantLib::DiscretizedAsset::isOnTime(), QuantLib::DiscretizedAsset::method(), QuantLib::VanillaSwap::arguments::nominal, QuantLib::VanillaSwap::Payer, QuantLib::DiscretizedAsset::rollback(), QuantLib::Array::size(), anonymous_namespace{quantlibbenchmark.cpp}::t, QuantLib::DiscretizedAsset::time_, QuantLib::VanillaSwap::arguments::type, QuantLib::DiscretizedAsset::values(), and QuantLib::DiscretizedAsset::values_.
{
        // floating payments
        for (Size i=0; i<floatingResetTimes_.size(); i++) {
            Time t = floatingResetTimes_[i];
            if (t >= 0.0 && isOnTime(t)) {
                DiscretizedDiscountBond bond;
                bond.initialize(method(), floatingPayTimes_[i]);
                bond.rollback(time_);
                Real nominal = arguments_.nominal;
                Time T = arguments_.floatingAccrualTimes[i];
                Spread spread = arguments_.floatingSpreads[i];
                Real accruedSpread = nominal*T*spread;
                for (Size j=0; j<values_.size(); j++) {
                    Real coupon = nominal * (1.0 - bond.values()[j])
                                + accruedSpread * bond.values()[j];
                    if (arguments_.type == VanillaSwap::Payer)
                        values_[j] += coupon;
                    else
                        values_[j] -= coupon;
                }
            }
        }
        // fixed payments
        for (Size i=0; i<fixedResetTimes_.size(); i++) {
            Time t = fixedResetTimes_[i];
            if (t >= 0.0 && isOnTime(t)) {
                DiscretizedDiscountBond bond;
                bond.initialize(method(), fixedPayTimes_[i]);
                bond.rollback(time_);
                Real fixedCoupon = arguments_.fixedCoupons[i];
                for (Size j=0; j<values_.size(); j++) {
                    Real coupon = fixedCoupon*bond.values()[j];
                    if (arguments_.type == VanillaSwap::Payer)
                        values_[j] -= coupon;
                    else
                        values_[j] += coupon;
                }
            }
        }
    }
void QuantLib::DiscretizedSwap::reset (Size size) [virtual]
This method should initialize the asset values to an Array of the given size and with values depending on the particular asset.
Implements QuantLib::DiscretizedAsset.
Definition at line 55 of file discretizedswap.cpp.
References QuantLib::DiscretizedAsset::adjustValues(), and QuantLib::DiscretizedAsset::values_.
Referenced by postAdjustValuesImpl().
{
        values_ = Array(size, 0.0);
        adjustValues();
    }
Member Data Documentation
VanillaSwap::arguments QuantLib::DiscretizedSwap::arguments_ [private]
Definition at line 44 of file discretizedswap.hpp.
Referenced by postAdjustValuesImpl(), and preAdjustValuesImpl().
std::vector<Time> QuantLib::DiscretizedSwap::fixedPayTimes_ [private]
Definition at line 46 of file discretizedswap.hpp.
Referenced by DiscretizedSwap(), mandatoryTimes(), postAdjustValuesImpl(), and preAdjustValuesImpl().
std::vector<Time> QuantLib::DiscretizedSwap::fixedResetTimes_ [private]
Definition at line 45 of file discretizedswap.hpp.
Referenced by DiscretizedSwap(), mandatoryTimes(), postAdjustValuesImpl(), and preAdjustValuesImpl().
std::vector<Time> QuantLib::DiscretizedSwap::floatingPayTimes_ [private]
Definition at line 48 of file discretizedswap.hpp.
Referenced by DiscretizedSwap(), mandatoryTimes(), postAdjustValuesImpl(), and preAdjustValuesImpl().
std::vector<Time> QuantLib::DiscretizedSwap::floatingResetTimes_ [private]
Definition at line 47 of file discretizedswap.hpp.
Referenced by DiscretizedSwap(), mandatoryTimes(), postAdjustValuesImpl(), and preAdjustValuesImpl().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/swap/discretizedswap.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/swap/discretizedswap.cpp