QuantLib: QuantLib::YieldTermStructure Class Reference
QuantLib::YieldTermStructure Class Reference
Interest-rate term structure.
#include <yieldtermstructure.hpp>
Public Member Functions
Constructors
See the TermStructure documentation for issues regarding constructors.
YieldTermStructure (const DayCounter &dc=DayCounter(), const std::vector< Handle< Quote > > &jumps=std::vector< Handle< Quote > >(), const std::vector< Date > &jumpDates=std::vector< Date >())
YieldTermStructure (const Date &referenceDate, const Calendar &cal=Calendar(), const DayCounter &dc=DayCounter(), const std::vector< Handle< Quote > > &jumps=std::vector< Handle< Quote > >(), const std::vector< Date > &jumpDates=std::vector< Date >())
YieldTermStructure (Natural settlementDays, const Calendar &cal, const DayCounter &dc=DayCounter(), const std::vector< Handle< Quote > > &jumps=std::vector< Handle< Quote > >(), const std::vector< Date > &jumpDates=std::vector< Date >())
Discount factors
These methods return the discount factor from a given date or time to the reference date. In the latter case, the time is calculated as a fraction of year from the reference date.
DiscountFactor discount (const Date &d, bool extrapolate=false) const
DiscountFactor discount (Time t, bool extrapolate=false) const
Zero-yield rates
These methods return the implied zero-yield rate for a given date or time. In the former case, the time is calculated as a fraction of year from the reference date.
InterestRate zeroRate (const Date &d, const DayCounter &resultDayCounter, Compounding comp, Frequency freq=Annual, bool extrapolate=false) const
InterestRate zeroRate (Time t, Compounding comp, Frequency freq=Annual, bool extrapolate=false) const
Forward rates
These methods returns the forward interest rate between two dates or times. In the former case, times are calculated as fractions of year from the reference date.
If both dates (times) are equal the instantaneous forward rate is returned.
InterestRate forwardRate (const Date &d1, const Date &d2, const DayCounter &resultDayCounter, Compounding comp, Frequency freq=Annual, bool extrapolate=false) const
InterestRate forwardRate (const Date &d, const Period &p, const DayCounter &resultDayCounter, Compounding comp, Frequency freq=Annual, bool extrapolate=false) const
InterestRate forwardRate (Time t1, Time t2, Compounding comp, Frequency freq=Annual, bool extrapolate=false) const
Jump inspectors
const std::vector< Date > & jumpDates () const
const std::vector< Time > & jumpTimes () const
Observer interface
void update ()
Protected Member Functions
Calculations
This method must be implemented in derived classes to perform the actual calculations. When it is called, range check has already been performed; therefore, it must assume that extrapolation is required.
virtual DiscountFactor discountImpl (Time) const =0
discount factor calculation
Private Member Functions
void setJumps ()
Private Attributes
std::vector< Handle< Quote > > jumps_
std::vector< Date > jumpDates_
std::vector< Time > jumpTimes_
Size nJumps_
Date latestReference_
Detailed Description
Interest-rate term structure.
This abstract class defines the interface of concrete interest rate structures which will be derived from this one.
Test:
observability against evaluation date changes is checked.
Definition at line 44 of file yieldtermstructure.hpp.
Constructor & Destructor Documentation
QuantLib::YieldTermStructure::YieldTermStructure (const DayCounter & dc = DayCounter(), const std::vector< Handle< Quote > > & jumps = std::vector<Handle<Quote> >(), const std::vector< Date > & jumpDates = std::vector<Date>())
Definition at line 32 of file yieldtermstructure.cpp.
References jumps_, nJumps_, QuantLib::Observer::registerWith(), and setJumps().
    : TermStructure(dc), jumps_(jumps),
      jumpDates_(jumpDates), jumpTimes_(jumpDates.size()),
      nJumps_(jumps_.size()) {
        setJumps();
        for (Size i=0; i<nJumps_; ++i)
            registerWith(jumps_[i]);
    }
QuantLib::YieldTermStructure::YieldTermStructure (const Date & referenceDate, const Calendar & cal = Calendar(), const DayCounter & dc = DayCounter(), const std::vector< Handle< Quote > > & jumps = std::vector<Handle<Quote> >(), const std::vector< Date > & jumpDates = std::vector<Date>())
Definition at line 44 of file yieldtermstructure.cpp.
References jumps_, nJumps_, QuantLib::Observer::registerWith(), and setJumps().
    : TermStructure(referenceDate, cal, dc), jumps_(jumps),
      jumpDates_(jumpDates), jumpTimes_(jumpDates.size()),
      nJumps_(jumps_.size()) {
        setJumps();
        for (Size i=0; i<nJumps_; ++i)
            registerWith(jumps_[i]);
    }
QuantLib::YieldTermStructure::YieldTermStructure (Natural settlementDays, const Calendar & cal, const DayCounter & dc = DayCounter(), const std::vector< Handle< Quote > > & jumps = std::vector<Handle<Quote> >(), const std::vector< Date > & jumpDates = std::vector<Date>())
Definition at line 58 of file yieldtermstructure.cpp.
References jumps_, nJumps_, QuantLib::Observer::registerWith(), and setJumps().
    : TermStructure(settlementDays, cal, dc), jumps_(jumps),
      jumpDates_(jumpDates), jumpTimes_(jumpDates.size()),
      nJumps_(jumps_.size()) {
        setJumps();
        for (Size i=0; i<nJumps_; ++i)
            registerWith(jumps_[i]);
    }
Member Function Documentation
DiscountFactor QuantLib::YieldTermStructure::discount (const Date & d, bool extrapolate = false) const [inline]
Definition at line 185 of file yieldtermstructure.hpp.
References QuantLib::TermStructure::timeFromReference().
Referenced by QuantLib::CashFlows::bps(), forwardRate(), QuantLib::CashFlows::npv(), QuantLib::CashFlows::npvbps(), and zeroRate().
{
        return discount(timeFromReference(d), extrapolate);
    }
DiscountFactor QuantLib::YieldTermStructure::discount (Time t, bool extrapolate = false) const
The same day-counting rule used by the term structure should be used for calculating the passed time t.
Definition at line 89 of file yieldtermstructure.cpp.
References QuantLib::TermStructure::checkRange(), discountImpl(), jumps_, jumpTimes_, nJumps_, QuantLib::io::ordinal(), and QL_REQUIRE.
{
        checkRange(t, extrapolate);
        if (jumps_.empty())
            return discountImpl(t);
        DiscountFactor jumpEffect = 1.0;
        for (Size i=0; i<nJumps_; ++i) {
            if (jumpTimes_[i]>0 && jumpTimes_[i]<t) {
                QL_REQUIRE(jumps_[i]->isValid(),
                           "invalid " << io::ordinal(i+1) << " jump quote");
                DiscountFactor thisJump = jumps_[i]->value();
                QL_REQUIRE(thisJump>0.0 && thisJump<=1.0,
                           "invalid " << io::ordinal(i+1) << " jump value: " <<
                           thisJump);
                jumpEffect *= thisJump;
            }
        }
        return jumpEffect * discountImpl(t);
    }
virtual DiscountFactor QuantLib::YieldTermStructure::discountImpl (Time) const [protected, pure virtual]
discount factor calculation
Implemented in QuantLib::FittedBondDiscountCurve, QuantLib::ForwardRateStructure, QuantLib::InterpolatedDiscountCurve< Interpolator >, QuantLib::FlatForward, QuantLib::ZeroYieldStructure, QuantLib::ImpliedTermStructure, and QuantLib::FdmAffineModelTermStructure.
Referenced by discount().
InterestRate QuantLib::YieldTermStructure::forwardRate (const Date & d1, const Date & d2, const DayCounter & resultDayCounter, Compounding comp, Frequency freq = Annual, bool extrapolate = false) const
The resulting interest rate has the required day-counting rule.
Definition at line 142 of file yieldtermstructure.cpp.
References QuantLib::TermStructure::checkRange(), discount(), QuantLib::anonymous_namespace{yieldtermstructure.cpp}::dt, QuantLib::InterestRate::impliedRate(), QL_REQUIRE, and QuantLib::TermStructure::timeFromReference().
Referenced by forwardRate().
{
        if (d1==d2) {
            checkRange(d1, extrapolate);
            Time t1 = std::max(timeFromReference(d1) - dt/2.0, 0.0);
            Time t2 = t1 + dt;
            Real compound =
                discount(t1, true)/discount(t2, true);
            // times have been calculated with a possibly different daycounter
            // but the difference should not matter for very small times
            return InterestRate::impliedRate(compound,
                                             dayCounter, comp, freq,
                                             dt);
        }
        QL_REQUIRE(d1 < d2,  d1 << " later than " << d2);
        Real compound = discount(d1, extrapolate)/discount(d2, extrapolate);
        return InterestRate::impliedRate(compound,
                                         dayCounter, comp, freq,
                                         d1, d2);
    }
InterestRate QuantLib::YieldTermStructure::forwardRate (const Date & d, const Period & p, const DayCounter & resultDayCounter, Compounding comp, Frequency freq = Annual, bool extrapolate = false) const [inline]
The resulting interest rate has the required day-counting rule.
Warning:
dates are not adjusted for holidays
Definition at line 191 of file yieldtermstructure.hpp.
References forwardRate().
{
        return forwardRate(d, d+p, dayCounter, comp, freq, extrapolate);
    }
InterestRate QuantLib::YieldTermStructure::forwardRate (Time t1, Time t2, Compounding comp, Frequency freq = Annual, bool extrapolate = false) const
The resulting interest rate has the same day-counting rule used by the term structure. The same rule should be used for calculating the passed times t1 and t2.
Definition at line 167 of file yieldtermstructure.cpp.
References QuantLib::TermStructure::checkRange(), QuantLib::TermStructure::dayCounter(), discount(), QuantLib::anonymous_namespace{yieldtermstructure.cpp}::dt, QuantLib::InterestRate::impliedRate(), and QL_REQUIRE.
{
        Real compound;
        if (t2==t1) {
            checkRange(t1, extrapolate);
            t1 = std::max(t1 - dt/2.0, 0.0);
            t2 = t1 + dt;
            compound = discount(t1, true)/discount(t2, true);
        } else {
            QL_REQUIRE(t2>t1, "t2 (" << t2 << ") < t1 (" << t2 << ")");
            compound = discount(t1, extrapolate)/discount(t2, extrapolate);
        }
        return InterestRate::impliedRate(compound,
                                         dayCounter(), comp, freq,
                                         t2-t1);
    }
const std::vector< Date > & QuantLib::YieldTermStructure::jumpDates () const [inline]
Definition at line 200 of file yieldtermstructure.hpp.
References jumpDates_.
{
        return this->jumpDates_;
    }
const std::vector< Time > & QuantLib::YieldTermStructure::jumpTimes () const [inline]
Definition at line 204 of file yieldtermstructure.hpp.
References jumpTimes_.
{
        return this->jumpTimes_;
    }
void QuantLib::YieldTermStructure::setJumps () [private]
Definition at line 72 of file yieldtermstructure.cpp.
References QuantLib::December, jumpDates_, jumps_, jumpTimes_, latestReference_, nJumps_, QL_REQUIRE, QuantLib::TermStructure::referenceDate(), QuantLib::TermStructure::timeFromReference(), and QuantLib::Date::year().
Referenced by update(), and YieldTermStructure().
{
        if (jumpDates_.empty() && !jumps_.empty()) { // turn of year dates
            jumpDates_.resize(nJumps_);
            jumpTimes_.resize(nJumps_);
            Year y = referenceDate().year();
            for (Size i=0; i<nJumps_; ++i)
                jumpDates_[i] = Date(31, December, y+i);
        } else { // fixed dats
            QL_REQUIRE(jumpDates_.size()==nJumps_,
                       "mismatch between number of jumps (" << nJumps_ <<
                       ") and jump dates (" << jumpDates_.size() << ")");
        }
        for (Size i=0; i<nJumps_; ++i)
            jumpTimes_[i] = timeFromReference(jumpDates_[i]);
        latestReference_ = referenceDate();
    }
void QuantLib::YieldTermStructure::update () [inline, virtual]
This method must be implemented in derived classes. An instance of Observer does not call this method directly: instead, it will be called by the observables the instance registered with when they need to notify any changes.
Reimplemented from QuantLib::TermStructure.
Reimplemented in QuantLib::FittedBondDiscountCurve, QuantLib::FlatForward, and QuantLib::PiecewiseZeroSpreadedTermStructure.
Definition at line 208 of file yieldtermstructure.hpp.
References latestReference_, QuantLib::TermStructure::referenceDate(), and setJumps().
{
        TermStructure::update();
        if (referenceDate() != latestReference_)
            setJumps();
    }
InterestRate QuantLib::YieldTermStructure::zeroRate (const Date & d, const DayCounter & resultDayCounter, Compounding comp, Frequency freq = Annual, bool extrapolate = false) const
The resulting interest rate has the required daycounting rule.
Definition at line 112 of file yieldtermstructure.cpp.
References discount(), QuantLib::anonymous_namespace{yieldtermstructure.cpp}::dt, QuantLib::InterestRate::impliedRate(), and QuantLib::TermStructure::referenceDate().
Referenced by QuantLib::PiecewiseZeroSpreadedTermStructure::zeroYieldImpl(), and QuantLib::ZeroSpreadedTermStructure::zeroYieldImpl().
{
        if (d==referenceDate()) {
            Real compound = 1.0/discount(dt, extrapolate);
            // t has been calculated with a possibly different daycounter
            // but the difference should not matter for very small times
            return InterestRate::impliedRate(compound,
                                             dayCounter, comp, freq,
                                             dt);
        }
        Real compound = 1.0/discount(d, extrapolate);
        return InterestRate::impliedRate(compound,
                                         dayCounter, comp, freq,
                                         referenceDate(), d);
    }
InterestRate QuantLib::YieldTermStructure::zeroRate (Time t, Compounding comp, Frequency freq = Annual, bool extrapolate = false) const
The resulting interest rate has the same day-counting rule used by the term structure. The same rule should be used for calculating the passed time t.
Definition at line 131 of file yieldtermstructure.cpp.
References QuantLib::TermStructure::dayCounter(), discount(), QuantLib::anonymous_namespace{yieldtermstructure.cpp}::dt, and QuantLib::InterestRate::impliedRate().
{
        if (t==0.0) t = dt;
        Real compound = 1.0/discount(t, extrapolate);
        return InterestRate::impliedRate(compound,
                                         dayCounter(), comp, freq,
                                         t);
    }
Member Data Documentation
std::vector<Date> QuantLib::YieldTermStructure::jumpDates_ [private]
Definition at line 176 of file yieldtermstructure.hpp.
Referenced by jumpDates(), and setJumps().
std::vector<Handle<Quote> > QuantLib::YieldTermStructure::jumps_ [private]
Definition at line 175 of file yieldtermstructure.hpp.
Referenced by discount(), setJumps(), and YieldTermStructure().
std::vector<Time> QuantLib::YieldTermStructure::jumpTimes_ [private]
Definition at line 177 of file yieldtermstructure.hpp.
Referenced by discount(), jumpTimes(), and setJumps().
Date QuantLib::YieldTermStructure::latestReference_ [private]
Definition at line 179 of file yieldtermstructure.hpp.
Referenced by setJumps(), and update().
Size QuantLib::YieldTermStructure::nJumps_ [private]
Definition at line 178 of file yieldtermstructure.hpp.
Referenced by discount(), setJumps(), and YieldTermStructure().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/yieldtermstructure.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/yieldtermstructure.cpp