QuantLib: QuantLib::Interpolation Class Reference
QuantLib::Interpolation Class Reference
base class for 1-D interpolations.
#include <interpolation.hpp>
Classes
class Impl
abstract base class for interpolation implementations
class templateImpl
basic template implementation
Public Types
typedef Real argument_type
typedef Real result_type
Public Member Functions
Interpolation ()
virtual ~Interpolation ()
bool empty () const
Real operator() (Real x, bool allowExtrapolation=false) const
Real primitive (Real x, bool allowExtrapolation=false) const
Real derivative (Real x, bool allowExtrapolation=false) const
Real secondDerivative (Real x, bool allowExtrapolation=false) const
Real xMin () const
Real xMax () const
bool isInRange (Real x) const
void update ()
Protected Member Functions
void checkRange (Real x, bool extrapolate) const
Protected Attributes
boost::shared_ptr< Impl > impl_
Detailed Description
base class for 1-D interpolations.
Classes derived from this class will provide interpolated values from two sequences of equal length, representing discretized values of a variable and a function of the former, respectively.
Definition at line 42 of file interpolation.hpp.
Member Typedef Documentation
typedef Real QuantLib::Interpolation::argument_type
Definition at line 61 of file interpolation.hpp.
typedef Real QuantLib::Interpolation::result_type
Definition at line 62 of file interpolation.hpp.
Constructor & Destructor Documentation
QuantLib::Interpolation::Interpolation () [inline]
Definition at line 110 of file interpolation.hpp.
{}
virtual QuantLib::Interpolation::~Interpolation () [inline, virtual]
Definition at line 111 of file interpolation.hpp.
{}
Member Function Documentation
void QuantLib::Interpolation::checkRange (Real x, bool extrapolate) const [inline, protected]
Definition at line 142 of file interpolation.hpp.
References QuantLib::Extrapolator::allowsExtrapolation(), impl_, and QL_REQUIRE.
Referenced by derivative(), operator()(), primitive(), and secondDerivative().
{
            QL_REQUIRE(extrapolate || allowsExtrapolation() ||
                       impl_->isInRange(x),
                       "interpolation range is ["
                       << impl_->xMin() << ", " << impl_->xMax()
                       << "]: extrapolation at " << x << " not allowed");
        }
Real QuantLib::Interpolation::derivative (Real x, bool allowExtrapolation = false) const [inline]
Definition at line 121 of file interpolation.hpp.
References checkRange(), and impl_.
Referenced by anonymous_namespace{interpolations.cpp}::check1stDerivativeValue(), QuantLib::detail::LogInterpolationImpl< I1, I2, Interpolator >::derivative(), QuantLib::detail::MixedInterpolationImpl< I1, I2, Interpolator1, Interpolator2 >::derivative(), QuantLib::detail::BicubicSplineImpl< I1, I2, M >::derivativeX(), QuantLib::detail::BicubicSplineImpl< I1, I2, M >::derivativeXY(), QuantLib::detail::BicubicSplineImpl< I1, I2, M >::derivativeY(), and QuantLib::detail::LogInterpolationImpl< I1, I2, Interpolator >::secondDerivative().
{
            checkRange(x,allowExtrapolation);
            return impl_->derivative(x);
        }
bool QuantLib::Interpolation::empty () const [inline]
Definition at line 112 of file interpolation.hpp.
References impl_.
{ return !impl_; }
bool QuantLib::Interpolation::isInRange (Real x) const [inline]
Definition at line 135 of file interpolation.hpp.
References impl_.
{
            return impl_->isInRange(x);
        }
Real QuantLib::Interpolation::operator() (Real x, bool allowExtrapolation = false) const [inline]
Definition at line 113 of file interpolation.hpp.
References checkRange(), and impl_.
{
            checkRange(x,allowExtrapolation);
            return impl_->value(x);
        }
Real QuantLib::Interpolation::primitive (Real x, bool allowExtrapolation = false) const [inline]
Definition at line 117 of file interpolation.hpp.
References checkRange(), and impl_.
Referenced by QuantLib::detail::MixedInterpolationImpl< I1, I2, Interpolator1, Interpolator2 >::primitive(), InterpolationTest::testBackwardFlat(), and InterpolationTest::testForwardFlat().
{
            checkRange(x,allowExtrapolation);
            return impl_->primitive(x);
        }
Real QuantLib::Interpolation::secondDerivative (Real x, bool allowExtrapolation = false) const [inline]
Definition at line 125 of file interpolation.hpp.
References checkRange(), and impl_.
Referenced by anonymous_namespace{interpolations.cpp}::check2ndDerivativeValue(), QuantLib::detail::LogInterpolationImpl< I1, I2, Interpolator >::secondDerivative(), QuantLib::detail::MixedInterpolationImpl< I1, I2, Interpolator1, Interpolator2 >::secondDerivative(), QuantLib::detail::BicubicSplineImpl< I1, I2, M >::secondDerivativeX(), QuantLib::detail::BicubicSplineImpl< I1, I2, M >::secondDerivativeY(), and InterpolationTest::testSplineOnGenericValues().
{
            checkRange(x,allowExtrapolation);
            return impl_->secondDerivative(x);
        }
void QuantLib::Interpolation::update () [inline]
Definition at line 138 of file interpolation.hpp.
References impl_.
Referenced by QuantLib::IterativeBootstrap< Curve >::calculate(), QuantLib::CommodityCurve::CommodityCurve(), QuantLib::FlatVolFactory::FlatVolFactory(), QuantLib::InterpolatedYoYInflationCurve< Interpolator >::InterpolatedYoYInflationCurve(), QuantLib::InterpolatedZeroInflationCurve< Interpolator >::InterpolatedZeroInflationCurve(), QuantLib::CapFloorTermVolCurve::performCalculations(), QuantLib::SampledCurve::regrid(), QuantLib::ExtendedBlackVarianceCurve::setInterpolation(), QuantLib::BlackVarianceCurve::setInterpolation(), QuantLib::CommodityCurve::setPrices(), QuantLib::SwaptionVolatilityDiscrete::SwaptionVolatilityDiscrete(), InterpolationTest::testAsFunctor(), InterpolationTest::testBackwardFlat(), InterpolationTest::testForwardFlat(), InterpolationTest::testSabrInterpolation(), InterpolationTest::testSplineOnGenericValues(), InterpolationTest::testSplineOnRPN15AValues(), QuantLib::detail::LogInterpolationImpl< I1, I2, Interpolator >::update(), QuantLib::detail::MixedInterpolationImpl< I1, I2, Interpolator1, Interpolator2 >::update(), and QuantLib::ExtendedBlackVarianceCurve::update().
                      {
            impl_->update();
        }
Real QuantLib::Interpolation::xMax () const [inline]
Definition at line 132 of file interpolation.hpp.
References impl_.
Referenced by QuantLib::InterpolatedYoYOptionletVolatilityCurve< Interpolator >::maxDate().
{
            return impl_->xMax();
        }
Real QuantLib::Interpolation::xMin () const [inline]
Definition at line 129 of file interpolation.hpp.
References impl_.
{
            return impl_->xMin();
        }
Member Data Documentation
boost::shared_ptr<Impl> QuantLib::Interpolation::impl_ [protected]
Definition at line 59 of file interpolation.hpp.
Referenced by QuantLib::AbcdInterpolation::AbcdInterpolation(), QuantLib::BackwardFlatInterpolation::BackwardFlatInterpolation(), checkRange(), QuantLib::ConvexMonotoneInterpolation< I1, I2 >::ConvexMonotoneInterpolation(), QuantLib::CubicInterpolation::CubicInterpolation(), derivative(), empty(), QuantLib::ForwardFlatInterpolation::ForwardFlatInterpolation(), QuantLib::ConvexMonotoneInterpolation< I1, I2 >::getExistingHelpers(), isInRange(), QuantLib::KernelInterpolation::KernelInterpolation(), QuantLib::LinearInterpolation::LinearInterpolation(), QuantLib::LogCubicInterpolation::LogCubicInterpolation(), QuantLib::LogLinearInterpolation::LogLinearInterpolation(), QuantLib::MixedLinearCubicInterpolation::MixedLinearCubicInterpolation(), operator()(), primitive(), QuantLib::SABRInterpolation::SABRInterpolation(), secondDerivative(), update(), xMax(), and xMin().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/interpolation.hpp