QuantLib: QuantLib::Flag Class Reference
QuantLib::Flag Class Reference
#include <utilities.hpp>
Public Member Functions
Flag ()
void raise ()
void lower ()
bool isUp () const
void update ()
Private Attributes
bool up_
Detailed Description
Definition at line 142 of file utilities.hpp.
Constructor & Destructor Documentation
QuantLib::Flag::Flag () [inline]
Definition at line 146 of file utilities.hpp.
: up_(false) {}
Member Function Documentation
bool QuantLib::Flag::isUp () const [inline]
Definition at line 149 of file utilities.hpp.
References up_.
Referenced by QuoteTest::testForwardValueQuoteAndImpliedStdevQuote(), TermStructureTest::testFSpreadedObs(), TermStructureTest::testImpliedObs(), EuropeanOptionTest::testImpliedVolContainment(), PiecewiseYieldCurveTest::testLiborFixing(), PiecewiseYieldCurveTest::testObservability(), InstrumentTest::testObservable(), QuoteTest::testObservable(), QuoteTest::testObservableHandle(), SwaptionVolatilityCubeTest::testSpreadedCube(), and TermStructureTest::testZSpreadedObs().
{ return up_; }
void QuantLib::Flag::lower () [inline]
Definition at line 148 of file utilities.hpp.
References up_.
Referenced by QuoteTest::testForwardValueQuoteAndImpliedStdevQuote(), TermStructureTest::testFSpreadedObs(), PiecewiseYieldCurveTest::testLiborFixing(), PiecewiseYieldCurveTest::testObservability(), InstrumentTest::testObservable(), QuoteTest::testObservableHandle(), SwaptionVolatilityCubeTest::testSpreadedCube(), and TermStructureTest::testZSpreadedObs().
{ up_ = false; }
void QuantLib::Flag::raise () [inline]
Definition at line 147 of file utilities.hpp.
References up_.
{ up_ = true; }
void QuantLib::Flag::update () [inline, virtual]
This method must be implemented in derived classes. An instance of Observer does not call this method directly: instead, it will be called by the observables the instance registered with when they need to notify any changes.
Implements QuantLib::Observer.
Definition at line 150 of file utilities.hpp.
{ raise(); }
Member Data Documentation
bool QuantLib::Flag::up_ [private]
Definition at line 144 of file utilities.hpp.
Referenced by isUp(), lower(), and raise().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/utilities.hpp