QuantLib: QuantLib::MultiStepSwaption Class Reference
QuantLib::MultiStepSwaption Class Reference
#include <multistepswaption.hpp>
Public Member Functions
MultiStepSwaption (const std::vector< Time > &rateTimes, Size startIndex, Size endIndex, boost::shared_ptr< StrikedTypePayoff > &)
MarketModelMultiProduct interface
std::vector< Time > possibleCashFlowTimes () const
Size numberOfProducts () const
Size maxNumberOfCashFlowsPerProductPerStep () const
void reset ()
during simulation put product at start of path
bool nextTimeStep (const CurveState &currentState, std::vector< Size > &numberCashFlowsThisStep, std::vector< std::vector< CashFlow > > &cashFlowsGenerated)
return value indicates whether path is finished, TRUE means done
std::auto_ptr
< MarketModelMultiProduct > clone () const
returns a newly-allocated copy of itself
Private Attributes
Size startIndex_
Size endIndex_
boost::shared_ptr
< StrikedTypePayoff > payoff_
std::vector< Time > paymentTimes_
Size currentIndex_
Detailed Description
Price a swaption associated to a contiguous subset of rates. Useful only for testing purposes. Steps through all rate times up to start of swap.
Definition at line 36 of file multistepswaption.hpp.
Constructor & Destructor Documentation
QuantLib::MultiStepSwaption::MultiStepSwaption (const std::vector< Time > & rateTimes, Size startIndex, Size endIndex, boost::shared_ptr< StrikedTypePayoff > & payOff)
Definition at line 28 of file multistepswaption.cpp.
References endIndex_, paymentTimes_, QL_REQUIRE, and startIndex_.
Referenced by clone().
                                     : MultiProductMultiStep(rateTimes),
     startIndex_(startIndex), endIndex_(endIndex), payoff_(payOff)
    {
        QL_REQUIRE(startIndex_ < endIndex_," start index must be before end index");
        QL_REQUIRE(endIndex_ < rateTimes.size(), "end index be before the end of the rates.");
        paymentTimes_.push_back(rateTimes[startIndex_]);
    }
Member Function Documentation
std::auto_ptr< MarketModelMultiProduct > QuantLib::MultiStepSwaption::clone () const [virtual]
returns a newly-allocated copy of itself
Implements QuantLib::MarketModelMultiProduct.
Definition at line 72 of file multistepswaption.cpp.
References MultiStepSwaption().
{
        return std::auto_ptr<MarketModelMultiProduct>(
                                         new MultiStepSwaption(*this));
    }
Size QuantLib::MultiStepSwaption::maxNumberOfCashFlowsPerProductPerStep () const [inline, virtual]
Implements QuantLib::MarketModelMultiProduct.
Definition at line 78 of file multistepswaption.hpp.
{
        return 1;
    }
bool QuantLib::MultiStepSwaption::nextTimeStep (const CurveState & currentState, std::vector< Size > & numberCashFlowsThisStep, std::vector< std::vector< CashFlow > > & cashFlowsGenerated) [virtual]
return value indicates whether path is finished, TRUE means done
Implements QuantLib::MarketModelMultiProduct.
Definition at line 42 of file multistepswaption.cpp.
References QuantLib::CurveState::cmSwapAnnuity(), QuantLib::CurveState::cmSwapRate(), currentIndex_, endIndex_, and startIndex_.
    {
        if (currentIndex_ == startIndex_)
        {
            genCashFlows[0][0].timeIndex = 0;
            Rate swapRate = currentState.cmSwapRate(startIndex_,endIndex_-startIndex_);
            Real annuity = currentState.cmSwapAnnuity(startIndex_,startIndex_,endIndex_-startIndex_);
            genCashFlows[0][0].amount =
                (*payoff_)(swapRate) * annuity;
            numberCashFlowsThisStep[0] =genCashFlows[0][0].amount != 0.0 ? 1 : 0 ;
            return true;
        }
        else
        {
            numberCashFlowsThisStep[0] =0;
            ++currentIndex_;
            return false;
        }
    }
Size QuantLib::MultiStepSwaption::numberOfProducts () const [inline, virtual]
Implements QuantLib::MarketModelMultiProduct.
Definition at line 73 of file multistepswaption.hpp.
{
        return 1UL;
    }
std::vector< Time > QuantLib::MultiStepSwaption::possibleCashFlowTimes () const [inline, virtual]
Implements QuantLib::MarketModelMultiProduct.
Definition at line 68 of file multistepswaption.hpp.
References paymentTimes_.
    {
        return paymentTimes_;
    }
void QuantLib::MultiStepSwaption::reset () [inline, virtual]
during simulation put product at start of path
Implements QuantLib::MarketModelMultiProduct.
Definition at line 82 of file multistepswaption.hpp.
References currentIndex_.
    {
       currentIndex_=0;
    }
Member Data Documentation
Size QuantLib::MultiStepSwaption::currentIndex_ [private]
Definition at line 62 of file multistepswaption.hpp.
Referenced by nextTimeStep(), and reset().
Size QuantLib::MultiStepSwaption::endIndex_ [private]
Definition at line 58 of file multistepswaption.hpp.
Referenced by MultiStepSwaption(), and nextTimeStep().
std::vector<Time> QuantLib::MultiStepSwaption::paymentTimes_ [private]
Definition at line 60 of file multistepswaption.hpp.
Referenced by MultiStepSwaption(), and possibleCashFlowTimes().
boost::shared_ptr<StrikedTypePayoff> QuantLib::MultiStepSwaption::payoff_ [private]
Definition at line 59 of file multistepswaption.hpp.
Size QuantLib::MultiStepSwaption::startIndex_ [private]
Definition at line 57 of file multistepswaption.hpp.
Referenced by MultiStepSwaption(), and nextTimeStep().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/products/multistep/multistepswaption.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/products/multistep/multistepswaption.cpp