QuantLib: QuantLib::CalibrationHelper Class Reference
QuantLib::CalibrationHelper Class Reference
liquid market instrument used during calibration
#include <calibrationhelper.hpp>
Classes
class ImpliedVolatilityHelper
Public Types
enum CalibrationErrorType { RelativePriceError, PriceError, ImpliedVolError }
Public Member Functions
CalibrationHelper (const Handle< Quote > &volatility, const Handle< YieldTermStructure > &termStructure, CalibrationErrorType calibrationErrorType=RelativePriceError)
void update ()
Real marketValue () const
returns the actual price of the instrument (from volatility)
virtual Real modelValue () const =0
returns the price of the instrument according to the model
virtual Real calibrationError ()
returns the error resulting from the model valuation
virtual void addTimesTo (std::list< Time > &times) const =0
Volatility impliedVolatility (Real targetValue, Real accuracy, Size maxEvaluations, Volatility minVol, Volatility maxVol) const
Black volatility implied by the model.
virtual Real blackPrice (Volatility volatility) const =0
Black price given a volatility.
void setPricingEngine (const boost::shared_ptr< PricingEngine > &engine)
Protected Attributes
Real marketValue_
Handle< Quote > volatility_
Handle< YieldTermStructure > termStructure_
boost::shared_ptr< PricingEngine > engine_
Private Attributes
const CalibrationErrorType calibrationErrorType_
Detailed Description
liquid market instrument used during calibration
Definition at line 36 of file calibrationhelper.hpp.
Member Enumeration Documentation
enum QuantLib::CalibrationHelper::CalibrationErrorType
Enumerator:
RelativePriceError
PriceError
ImpliedVolError
Definition at line 38 of file calibrationhelper.hpp.
{
                            RelativePriceError, PriceError, ImpliedVolError};
Constructor & Destructor Documentation
QuantLib::CalibrationHelper::CalibrationHelper (const Handle< Quote > & volatility, const Handle< YieldTermStructure > & termStructure, CalibrationErrorType calibrationErrorType = RelativePriceError) [inline]
Definition at line 41 of file calibrationhelper.hpp.
References QuantLib::Observer::registerWith(), termStructure_, and volatility_.
        : volatility_(volatility), termStructure_(termStructure),
          calibrationErrorType_(calibrationErrorType) {
            registerWith(volatility_);
            registerWith(termStructure_);
        }
Member Function Documentation
virtual void QuantLib::CalibrationHelper::addTimesTo (std::list< Time > & times) const [pure virtual]
Implemented in QuantLib::CapHelper, QuantLib::SwaptionHelper, and QuantLib::HestonModelHelper.
virtual Real QuantLib::CalibrationHelper::blackPrice (Volatility volatility) const [pure virtual]
Black price given a volatility.
Implemented in QuantLib::CapHelper, QuantLib::SwaptionHelper, and QuantLib::HestonModelHelper.
Referenced by calibrationError(), QuantLib::CalibrationHelper::ImpliedVolatilityHelper::operator()(), and update().
Real QuantLib::CalibrationHelper::calibrationError () [virtual]
returns the error resulting from the model valuation
Definition at line 51 of file calibrationhelper.cpp.
References blackPrice(), calibrationErrorType_, impliedVolatility(), ImpliedVolError, marketValue(), modelValue(), PriceError, QL_FAIL, RelativePriceError, and volatility_.
{
        double error;
        switch (calibrationErrorType_) {
          case RelativePriceError:
            error = std::fabs(marketValue() - modelValue())/marketValue();
            break;
          case PriceError:
            error = marketValue() - modelValue();
            break;
          case ImpliedVolError:
            {
              const Real lowerPrice = blackPrice(0.001);
              const Real upperPrice = blackPrice(10);
              const Real modelPrice = modelValue();
              Volatility implied;
              if (modelPrice <= lowerPrice)
                  implied = 0.001;
              else
                  if (modelPrice >= upperPrice)
                      implied = 10.0;
                  else
                      implied = this->impliedVolatility(
                                          modelPrice, 1e-12, 5000, 0.001, 10);
              error = implied - volatility_->value();
            }
            break;
          default:
            QL_FAIL("unknown Calibration Error Type");
        }
        return error;
    }
Volatility QuantLib::CalibrationHelper::impliedVolatility (Real targetValue, Real accuracy, Size maxEvaluations, Volatility minVol, Volatility maxVol) const
Black volatility implied by the model.
Definition at line 39 of file calibrationhelper.cpp.
References anonymous_namespace{interpolations.cpp}::f(), QuantLib::Solver1D< Impl >::setMaxEvaluations(), QuantLib::Solver1D< Impl >::solve(), and volatility_.
Referenced by calibrationError().
{
        ImpliedVolatilityHelper f(*this,targetValue);
        Brent solver;
        solver.setMaxEvaluations(maxEvaluations);
        return solver.solve(f,accuracy,volatility_->value(),minVol,maxVol);
    }
Real QuantLib::CalibrationHelper::marketValue () const [inline]
returns the actual price of the instrument (from volatility)
Definition at line 56 of file calibrationhelper.hpp.
References marketValue_.
Referenced by calibrationError().
{ return marketValue_; }
virtual Real QuantLib::CalibrationHelper::modelValue () const [pure virtual]
returns the price of the instrument according to the model
Implemented in QuantLib::CapHelper, QuantLib::SwaptionHelper, and QuantLib::HestonModelHelper.
Referenced by calibrationError().
void QuantLib::CalibrationHelper::setPricingEngine (const boost::shared_ptr< PricingEngine > & engine) [inline]
Definition at line 76 of file calibrationhelper.hpp.
References engine_.
{
            engine_ = engine;
        }
void QuantLib::CalibrationHelper::update () [inline, virtual]
This method must be implemented in derived classes. An instance of Observer does not call this method directly: instead, it will be called by the observables the instance registered with when they need to notify any changes.
Implements QuantLib::Observer.
Definition at line 50 of file calibrationhelper.hpp.
References blackPrice(), marketValue_, QuantLib::Observable::notifyObservers(), and volatility_.
                      {
            marketValue_ = blackPrice(volatility_->value());
            notifyObservers();
        }
Member Data Documentation
const CalibrationErrorType QuantLib::CalibrationHelper::calibrationErrorType_ [private]
Definition at line 87 of file calibrationhelper.hpp.
Referenced by calibrationError().
boost::shared_ptr<PricingEngine> QuantLib::CalibrationHelper::engine_ [protected]
Definition at line 84 of file calibrationhelper.hpp.
Referenced by QuantLib::CapHelper::blackPrice(), QuantLib::SwaptionHelper::blackPrice(), QuantLib::CapHelper::CapHelper(), QuantLib::HestonModelHelper::modelValue(), QuantLib::CapHelper::modelValue(), QuantLib::SwaptionHelper::modelValue(), setPricingEngine(), and QuantLib::SwaptionHelper::SwaptionHelper().
Real QuantLib::CalibrationHelper::marketValue_ [protected]
Definition at line 81 of file calibrationhelper.hpp.
Referenced by QuantLib::CapHelper::CapHelper(), QuantLib::HestonModelHelper::HestonModelHelper(), marketValue(), QuantLib::SwaptionHelper::SwaptionHelper(), and update().
Handle<YieldTermStructure> QuantLib::CalibrationHelper::termStructure_ [protected]
Definition at line 83 of file calibrationhelper.hpp.
Referenced by QuantLib::CapHelper::addTimesTo(), QuantLib::SwaptionHelper::addTimesTo(), QuantLib::HestonModelHelper::blackPrice(), QuantLib::SwaptionHelper::blackPrice(), QuantLib::CapHelper::blackPrice(), and CalibrationHelper().
Handle<Quote> QuantLib::CalibrationHelper::volatility_ [protected]
Definition at line 82 of file calibrationhelper.hpp.
Referenced by calibrationError(), CalibrationHelper(), QuantLib::CapHelper::CapHelper(), impliedVolatility(), QuantLib::SwaptionHelper::SwaptionHelper(), and update().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/calibrationhelper.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/calibrationhelper.cpp