QuantLib: QuantLib::DiscrepancyStatistics Class Reference
QuantLib::DiscrepancyStatistics Class Reference
Statistic tool for sequences with discrepancy calculation.
#include <discrepancystatistics.hpp>
Public Types
typedef
SequenceStatistics::value_type value_type
Public Member Functions
DiscrepancyStatistics (Size dimension)
template<class Sequence >
void add (const Sequence &sample, Real weight=1.0)
template<class Iterator >
void add (Iterator begin, Iterator end, Real weight=1.0)
void reset (Size dimension=0)
1-dimensional inspectors
Real discrepancy () const
Private Attributes
Real adiscr_
Real cdiscr_
Real bdiscr_
Real ddiscr_
Detailed Description
Statistic tool for sequences with discrepancy calculation.
It inherit from SequenceStatistics<Statistics> and adds \(L^2 \) discrepancy calculation
Definition at line 35 of file discrepancystatistics.hpp.
Member Typedef Documentation
typedef SequenceStatistics::value_type QuantLib::DiscrepancyStatistics::value_type
Reimplemented from QuantLib::GenericSequenceStatistics< StatisticsType >.
Definition at line 37 of file discrepancystatistics.hpp.
Constructor & Destructor Documentation
QuantLib::DiscrepancyStatistics::DiscrepancyStatistics (Size dimension) [inline]
Definition at line 103 of file discrepancystatistics.hpp.
References reset().
    : SequenceStatistics(dimension) {
        reset(dimension);
    }
Member Function Documentation
template<class Sequence > void QuantLib::DiscrepancyStatistics::add (const Sequence & sample, Real weight = 1.0) [inline]
Reimplemented from QuantLib::GenericSequenceStatistics< StatisticsType >.
Definition at line 45 of file discrepancystatistics.hpp.
Referenced by add(), and anonymous_namespace{lowdiscrepancysequences.cpp}::testGeneratorDiscrepancy().
{
            add(sample.begin(),sample.end(),weight);
        }
template<class Iterator > void QuantLib::DiscrepancyStatistics::add (Iterator begin, Iterator end, Real weight = 1.0) [inline]
Reimplemented from QuantLib::GenericSequenceStatistics< StatisticsType >.
Definition at line 50 of file discrepancystatistics.hpp.
References add(), adiscr_, cdiscr_, QuantLib::GenericSequenceStatistics< StatisticsType >::dimension_, QuantLib::GenericSequenceStatistics< StatisticsType >::max(), anonymous_namespace{matrices.cpp}::N, QuantLib::GenericSequenceStatistics< StatisticsType >::samples(), and QuantLib::GenericSequenceStatistics< StatisticsType >::stats_.
{
            SequenceStatistics::add(begin,end,weight);
            Size k, m, N = samples();
            Real r_ik, r_jk, temp = 1.0;
            Iterator it;
            for (k=0, it=begin; k<dimension_; ++it, ++k) {
                r_ik = *it; //i=N
                temp *= (1.0 - r_ik*r_ik);
            }
            cdiscr_ += temp;
            for (m=0; m<N-1; m++) {
                temp = 1.0;
                for (k=0, it=begin; k<dimension_; ++it, ++k) {
                    // running i=1..(N-1)
                    r_ik = stats_[k].data()[m].first;
                    // fixed j=N
                    r_jk = *it;
                    temp *= (1.0 - std::max(r_ik, r_jk));
                }
                adiscr_ += temp;
                temp = 1.0;
                for (k=0, it=begin; k<dimension_; ++it, ++k) {
                    // fixed i=N
                    r_ik = *it;
                    // running j=1..(N-1)
                    r_jk = stats_[k].data()[m].first;
                    temp *= (1.0 - std::max(r_ik, r_jk));
                }
                adiscr_ += temp;
            }
            temp = 1.0;
            for (k=0, it=begin; k<dimension_; ++it, ++k) {
                // fixed i=N, j=N
                r_ik = r_jk = *it;
                temp *= (1.0 - std::max(r_ik, r_jk));
            }
            adiscr_ += temp;
        }
Real QuantLib::DiscrepancyStatistics::discrepancy () const
Definition at line 24 of file discrepancystatistics.cpp.
References adiscr_, bdiscr_, cdiscr_, ddiscr_, anonymous_namespace{matrices.cpp}::N, and QuantLib::GenericSequenceStatistics< StatisticsType >::samples().
Referenced by anonymous_namespace{lowdiscrepancysequences.cpp}::testGeneratorDiscrepancy().
{
        Size N = samples();
        /*
        Size i;
        Real r_ik, r_jk, cdiscr = adiscr = 0.0, temp = 1.0;
        for (i=0; i<N; i++) {
            Real temp = 1.0;
            for (Size k=0; k<dimension_; k++) {
                r_ik = stats_[k].sampleData()[i].first;
                temp *= (1.0 - r_ik*r_ik);
            }
            cdiscr += temp;
        }
        for (i=0; i<N; i++) {
            for (Size j=0; j<N; j++) {
                Real temp = 1.0;
                for (Size k=0; k<dimension_; k++) {
                    r_jk = stats_[k].sampleData()[j].first;
                    r_ik = stats_[k].sampleData()[i].first;
                    temp *= (1.0 - std::max(r_ik, r_jk));
                }
                adiscr += temp;
            }
        }
        */
        return std::sqrt(adiscr_/(N*N)-bdiscr_/N*cdiscr_+ddiscr_);
    }
void QuantLib::DiscrepancyStatistics::reset (Size dimension = 0) [inline]
Reimplemented from QuantLib::GenericSequenceStatistics< StatisticsType >.
Definition at line 108 of file discrepancystatistics.hpp.
References adiscr_, bdiscr_, cdiscr_, ddiscr_, QuantLib::GenericSequenceStatistics< StatisticsType >::dimension_, QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow(), and QL_REQUIRE.
Referenced by DiscrepancyStatistics(), and anonymous_namespace{lowdiscrepancysequences.cpp}::testGeneratorDiscrepancy().
{
        if (dimension == 0)           // if no size given,
            dimension = dimension_;   // keep the current one
        QL_REQUIRE(dimension != 1,
                   "dimension==1 not allowed");
        SequenceStatistics::reset(dimension);
        adiscr_ = 0.0;
        bdiscr_ = 1.0/std::pow(2.0, Integer(dimension-1));
        cdiscr_ = 0.0;
        ddiscr_ = 1.0/std::pow(3.0, Integer(dimension));
    }
Member Data Documentation
Real QuantLib::DiscrepancyStatistics::adiscr_ [mutable, private]
Definition at line 96 of file discrepancystatistics.hpp.
Referenced by add(), discrepancy(), and reset().
Real QuantLib::DiscrepancyStatistics::bdiscr_ [private]
Definition at line 97 of file discrepancystatistics.hpp.
Referenced by discrepancy(), and reset().
Real QuantLib::DiscrepancyStatistics::cdiscr_ [mutable, private]
Definition at line 96 of file discrepancystatistics.hpp.
Referenced by add(), discrepancy(), and reset().
Real QuantLib::DiscrepancyStatistics::ddiscr_ [private]
Definition at line 97 of file discrepancystatistics.hpp.
Referenced by discrepancy(), and reset().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/statistics/discrepancystatistics.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/math/statistics/discrepancystatistics.cpp