QuantLib: QuantLib::GenericEngine< ArgumentsType, ResultsType > Class Template Reference
QuantLib::GenericEngine< ArgumentsType, ResultsType > Class Template Reference
template base class for option pricing engines
#include <pricingengine.hpp>
Inherits QuantLib::PricingEngine, and QuantLib::Observer.
Inherited by QuantLib::GenericModelEngine< ModelType, ArgumentsType, ResultsType >, QuantLib::MCLongstaffSchwartzEngine< GenericEngine, MC, RNG, S >, and QuantLib::MCLongstaffSchwartzPathEngine< GenericEngine, MC, RNG, S >.
Public Member Functions
PricingEngine::arguments * getArguments () const
const PricingEngine::results * getResults () const
void reset ()
void update ()
Protected Attributes
ArgumentsType arguments_
ResultsType results_
Detailed Description
template<class ArgumentsType, class ResultsType>
class QuantLib::GenericEngine< ArgumentsType, ResultsType >
template base class for option pricing engines
Derived engines only need to implement the calculate() method.
Definition at line 63 of file pricingengine.hpp.
Member Function Documentation
template<class ArgumentsType, class ResultsType> PricingEngine::arguments* QuantLib::GenericEngine< ArgumentsType, ResultsType >::getArguments () const [inline, virtual]
Implements QuantLib::PricingEngine.
Definition at line 66 of file pricingengine.hpp.
Referenced by QuantLib::CreditDefaultSwap::conventionalSpread(), and QuantLib::CreditDefaultSwap::impliedHazardRate().
{ return &arguments_; }
template<class ArgumentsType, class ResultsType> const PricingEngine::results* QuantLib::GenericEngine< ArgumentsType, ResultsType >::getResults () const [inline, virtual]
Implements QuantLib::PricingEngine.
Definition at line 67 of file pricingengine.hpp.
Referenced by QuantLib::CreditDefaultSwap::conventionalSpread(), and QuantLib::CreditDefaultSwap::impliedHazardRate().
{ return &results_; }
template<class ArgumentsType, class ResultsType> void QuantLib::GenericEngine< ArgumentsType, ResultsType >::reset () [inline, virtual]
Implements QuantLib::PricingEngine.
Definition at line 68 of file pricingengine.hpp.
{ results_.reset(); }
template<class ArgumentsType, class ResultsType> void QuantLib::GenericEngine< ArgumentsType, ResultsType >::update () [inline, virtual]
This method must be implemented in derived classes. An instance of Observer does not call this method directly: instead, it will be called by the observables the instance registered with when they need to notify any changes.
Implements QuantLib::Observer.
Reimplemented in QuantLib::AnalyticHestonHullWhiteEngine, QuantLib::FdHestonHullWhiteVanillaEngine, QuantLib::FdHestonVanillaEngine, QuantLib::LatticeShortRateModelEngine< Arguments, Results >, QuantLib::LatticeShortRateModelEngine< CapFloor::arguments, CapFloor::results >, QuantLib::LatticeShortRateModelEngine< VanillaSwap::arguments, VanillaSwap::results >, QuantLib::LatticeShortRateModelEngine< Swaption::arguments, Swaption::results >, and QuantLib::LatticeShortRateModelEngine< CallableBond::arguments, CallableBond::results >.
Definition at line 69 of file pricingengine.hpp.
Referenced by QuantLib::LatticeShortRateModelEngine< Arguments, Results >::update().
{ notifyObservers(); }
Member Data Documentation
template<class ArgumentsType, class ResultsType> ArgumentsType QuantLib::GenericEngine< ArgumentsType, ResultsType >::arguments_ [mutable, protected]
Definition at line 71 of file pricingengine.hpp.
Referenced by QuantLib::GenericEngine< SimpleChooserOption::arguments, SimpleChooserOption::results >::getArguments().
template<class ArgumentsType, class ResultsType> ResultsType QuantLib::GenericEngine< ArgumentsType, ResultsType >::results_ [mutable, protected]
Definition at line 72 of file pricingengine.hpp.
Referenced by QuantLib::GenericEngine< SimpleChooserOption::arguments, SimpleChooserOption::results >::getResults(), and QuantLib::GenericEngine< SimpleChooserOption::arguments, SimpleChooserOption::results >::reset().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengine.hpp