QuantLib: QuantLib::OneFactorStudentCopula Class Reference
QuantLib::OneFactorStudentCopula Class Reference
One-factor Double Student t-Copula.
#include <onefactorstudentcopula.hpp>
Public Member Functions
OneFactorStudentCopula (const Handle< Quote > &correlation, int nz, int nm, Real maximum=10, Size integrationSteps=200)
Real density (Real m) const
Density function of M.
Real cumulativeZ (Real z) const
Cumulative distribution of Z.
Private Member Functions
void performCalculations () const
Observer interface.
Real cumulativeYintegral (Real y) const
Private Attributes
StudentDistribution density_
CumulativeStudentDistribution cumulative_
int nz_
int nm_
Real scaleM_
Real scaleZ_
Detailed Description
One-factor Double Student t-Copula.
The copula model
\[ Y_i = a_i\,M+\sqrt{1-a_i^2}\:Z_i \]
is specified here by setting the probability density functions for \(Z_i \) (\(D_Z \)) and \(M \) (\(D_M \)) to Student t-distributions with \(N_z \) and \(N_m \) degrees of freedom, respectively.
The variance of the Student t-distribution with \(\nu \) degrees of freedom is \(\nu / (\nu - 2) \). Since the copula approach requires zero mean and unit variance distributions, variables \(Z \) and \(M \) are scaled by \(\sqrt{(N_z - 2) / N_z} \) and \(\sqrt{(N_m - 2) / N_m}, \) respectively.
Todo:
Improve performance/accuracy of the calculation of inverse cumulative Y. Tabulate and store it for selected correlations?
Definition at line 53 of file onefactorstudentcopula.hpp.
Constructor & Destructor Documentation
QuantLib::OneFactorStudentCopula::OneFactorStudentCopula (const Handle< Quote > & correlation, int nz, int nm, Real maximum = 10, Size integrationSteps = 200)
Definition at line 25 of file onefactorstudentcopula.cpp.
References QuantLib::LazyObject::calculate(), nm_, nz_, QL_REQUIRE, scaleM_, and scaleZ_.
    : OneFactorCopula (correlation, maximum, integrationSteps),
      density_ (nm), cumulative_ (nz), nz_(nz), nm_(nm) {
    //-------------------------------------------------------------------------
        QL_REQUIRE (nz > 2 && nm > 2, "degrees of freedom must be > 2");
        scaleM_ = std::sqrt (Real (nm_ - 2) / nm_);
        scaleZ_ = std::sqrt (Real (nz_ - 2) / nz_);
        calculate ();
    }
Member Function Documentation
Real QuantLib::OneFactorStudentCopula::cumulativeYintegral (Real y) const [private]
Definition at line 63 of file onefactorstudentcopula.cpp.
References anonymous_namespace{marketmodel.cpp}::c, QuantLib::OneFactorCopula::correlation_, QuantLib::OneFactorCopula::dm(), QuantLib::OneFactorCopula::m(), nm_, nz_, scaleM_, scaleZ_, and QuantLib::OneFactorCopula::steps().
Referenced by performCalculations().
{
    //-------------------------------------------------------------------------
        Real c = correlation_->value();
        if (c == 0)
            return CumulativeStudentDistribution(nz_)(y / scaleZ_);
        if (c == 1)
            return CumulativeStudentDistribution(nm_)(y / scaleM_);
        StudentDistribution dz (nz_);
        StudentDistribution dm (nm_);
        // FIXME:
        // Find a sensitive way of setting these parameters,
        // e.g. depending on nm and nz, and the desired table range
        Real minimum = -10; // -15
        Real maximum = +10; // +15
        int steps = 400;
        Real delta = (maximum - minimum) / steps;
        Real cumulated = 0;
        if (c < 0.5) {
            // outer integral -> 1 for c -> 0
            // inner integral -> cumulativeStudent(nz)(y) for c-> 0
            for (Real m = minimum + delta/2; m < maximum; m += delta)
                for (Real z = minimum + delta/2;
                     z < (y - std::sqrt(c) * m) / std::sqrt (1. - c); z += delta)
                    cumulated += dm (m / scaleM_) / scaleM_
                        * dz (z / scaleZ_) / scaleZ_;
        }
        else {
            // outer integral -> 1 for c -> 1
            // inner integral -> cumulativeStudent(nm)(y) for c-> 1
            for (Real z = minimum + delta/2; z < maximum; z += delta)
                for (Real m = minimum + delta/2;
                     m < (y - std::sqrt(1.0 - c) * z) / std::sqrt(c); m += delta)
                    cumulated += dm (m / scaleM_) / scaleM_
                        * dz (z / scaleZ_) / scaleZ_;
        }
        return cumulated * delta * delta;
    }
Real QuantLib::OneFactorStudentCopula::cumulativeZ (Real z) const [inline, virtual]
Cumulative distribution of Z.
Derived classes must override this method and ensure zero mean and unit variance.
Implements QuantLib::OneFactorCopula.
Definition at line 84 of file onefactorstudentcopula.hpp.
References cumulative_, and scaleZ_.
{
        return cumulative_(z / scaleZ_);
    }
Real QuantLib::OneFactorStudentCopula::density (Real m) const [inline, virtual]
Density function of M.
Derived classes must override this method and ensure zero mean and unit variance.
Implements QuantLib::OneFactorCopula.
Definition at line 80 of file onefactorstudentcopula.hpp.
References density_, and scaleM_.
{
        return density_(m / scaleM_) / scaleM_;
    }
void QuantLib::OneFactorStudentCopula::performCalculations () const [private, virtual]
Observer interface.
Implements QuantLib::LazyObject.
Definition at line 43 of file onefactorstudentcopula.cpp.
References anonymous_namespace{marketmodel.cpp}::c, QuantLib::OneFactorCopula::cumulativeY_, cumulativeYintegral(), QuantLib::OneFactorCopula::steps(), and QuantLib::OneFactorCopula::y_.
{
    //-------------------------------------------------------------------------
        y_.clear();
        cumulativeY_.clear();
        // FIXME:
        // compute F(ymin) and F(ymax) for the fattest case nm = nz = 2
        // set a desired confidence and work out ymin, ymax
        Real ymin = -10;
        Real ymax = +10;
        Size steps = 200;
        for (Size i = 0; i <= steps; i++) {
            Real y = ymin + (ymax - ymin) * i / steps;
            Real c = cumulativeYintegral (y);
            y_.push_back (y);
            cumulativeY_.push_back (c);
        }
    }
Member Data Documentation
CumulativeStudentDistribution QuantLib::OneFactorStudentCopula::cumulative_ [private]
Definition at line 67 of file onefactorstudentcopula.hpp.
Referenced by cumulativeZ().
StudentDistribution QuantLib::OneFactorStudentCopula::density_ [private]
Definition at line 66 of file onefactorstudentcopula.hpp.
Referenced by density().
int QuantLib::OneFactorStudentCopula::nm_ [private]
Definition at line 69 of file onefactorstudentcopula.hpp.
Referenced by cumulativeYintegral(), and OneFactorStudentCopula().
int QuantLib::OneFactorStudentCopula::nz_ [private]
Definition at line 68 of file onefactorstudentcopula.hpp.
Referenced by cumulativeYintegral(), and OneFactorStudentCopula().
Real QuantLib::OneFactorStudentCopula::scaleM_ [private]
Definition at line 71 of file onefactorstudentcopula.hpp.
Referenced by cumulativeYintegral(), density(), and OneFactorStudentCopula().
Real QuantLib::OneFactorStudentCopula::scaleZ_ [private]
Definition at line 72 of file onefactorstudentcopula.hpp.
Referenced by cumulativeYintegral(), cumulativeZ(), and OneFactorStudentCopula().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/onefactorstudentcopula.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/onefactorstudentcopula.cpp