QuantLib: QuantLib::FDDividendEngineBase< Scheme > Class Template Reference
QuantLib::FDDividendEngineBase< Scheme > Class Template Reference
Abstract base class for dividend engines.
#include <fddividendengine.hpp>
Public Member Functions
FDDividendEngineBase (const boost::shared_ptr< GeneralizedBlackScholesProcess > &process, Size timeSteps=100, Size gridPoints=100, bool timeDependent=false)
Protected Member Functions
virtual void setupArguments (const PricingEngine::arguments *) const
void setGridLimits () const =0
void executeIntermediateStep (Size step) const =0
Real getDividendAmount (Size i) const
Real getDiscountedDividend (Size i) const
Detailed Description
template<template< class > class Scheme = CrankNicolson>
class QuantLib::FDDividendEngineBase< Scheme >
Abstract base class for dividend engines.
Todo:
The dividend class really needs to be made more sophisticated to distinguish between fixed dividends and fractional dividends
Definition at line 39 of file fddividendengine.hpp.
Constructor & Destructor Documentation
template<template< class > class Scheme = CrankNicolson> QuantLib::FDDividendEngineBase< Scheme >::FDDividendEngineBase (const boost::shared_ptr< GeneralizedBlackScholesProcess > & process, Size timeSteps = 100, Size gridPoints = 100, bool timeDependent = false) [inline]
Definition at line 41 of file fddividendengine.hpp.
        : FDMultiPeriodEngine<Scheme>(process, timeSteps,
                                      gridPoints, timeDependent) {}
Member Function Documentation
template<template< class > class Scheme = CrankNicolson> void QuantLib::FDDividendEngineBase< Scheme >::executeIntermediateStep (Size step) const [protected, pure virtual]
Implements QuantLib::FDMultiPeriodEngine< Scheme >.
Implemented in QuantLib::FDDividendEngineShiftScale< Scheme >, and QuantLib::FDDividendEngineMerton73< Scheme >.
template<template< class > class Scheme = CrankNicolson> Real QuantLib::FDDividendEngineBase< Scheme >::getDiscountedDividend (Size i) const [inline, protected]
Definition at line 61 of file fddividendengine.hpp.
References QuantLib::FDMultiPeriodEngine< Scheme >::events_, QuantLib::FDDividendEngineBase< Scheme >::getDividendAmount(), and QuantLib::FDVanillaEngine::process_.
{
            Real dividend = getDividendAmount(i);
            Real discount =
                this->process_->riskFreeRate()->discount(
                                                   this->events_[i]->date()) /
                this->process_->dividendYield()->discount(
                                                    this->events_[i]->date());
            return dividend * discount;
        }
template<template< class > class Scheme = CrankNicolson> Real QuantLib::FDDividendEngineBase< Scheme >::getDividendAmount (Size i) const [inline, protected]
Definition at line 52 of file fddividendengine.hpp.
References QuantLib::Dividend::amount(), and QuantLib::FDMultiPeriodEngine< Scheme >::events_.
Referenced by QuantLib::FDDividendEngineBase< Scheme >::getDiscountedDividend().
{
            const Dividend *dividend =
                dynamic_cast<const Dividend *>(this->events_[i].get());
            if (dividend) {
                return dividend->amount();
            } else {
                return 0.0;
            }
        }
template<template< class > class Scheme = CrankNicolson> void QuantLib::FDDividendEngineBase< Scheme >::setGridLimits () const [protected, pure virtual]
Reimplemented from QuantLib::FDVanillaEngine.
Implemented in QuantLib::FDDividendEngineShiftScale< Scheme >, and QuantLib::FDDividendEngineMerton73< Scheme >.
template<template< class > class Scheme> void QuantLib::FDDividendEngineBase< Scheme >::setupArguments (const PricingEngine::arguments * a) const [protected, virtual]
Reimplemented from QuantLib::FDMultiPeriodEngine< Scheme >.
Definition at line 141 of file fddividendengine.hpp.
References anonymous_namespace{marketmodel.cpp}::a, QuantLib::DividendVanillaOption::arguments::cashFlow, QL_REQUIRE, and QuantLib::FDMultiPeriodEngine< Scheme >::setupArguments().
{
        const DividendVanillaOption::arguments *args =
            dynamic_cast<const DividendVanillaOption::arguments *>(a);
        QL_REQUIRE(args, "incorrect argument type");
        std::vector<boost::shared_ptr<Event> > events(args->cashFlow.size());
        std::copy(args->cashFlow.begin(), args->cashFlow.end(),
                  events.begin());
        FDMultiPeriodEngine<Scheme>::setupArguments(a, events);
    }
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/vanilla/fddividendengine.hpp