QuantLib: QuantLib::MakeMCDigitalEngine< RNG, S > Class Template Reference
QuantLib::MakeMCDigitalEngine< RNG, S > Class Template Reference
Monte Carlo digital engine factory.
#include <mcdigitalengine.hpp>
Public Member Functions
MakeMCDigitalEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > &)
MakeMCDigitalEngine & withSteps (Size steps)
MakeMCDigitalEngine & withStepsPerYear (Size steps)
MakeMCDigitalEngine & withBrownianBridge (bool b=true)
MakeMCDigitalEngine & withSamples (Size samples)
MakeMCDigitalEngine & withAbsoluteTolerance (Real tolerance)
MakeMCDigitalEngine & withMaxSamples (Size samples)
MakeMCDigitalEngine & withSeed (BigNatural seed)
MakeMCDigitalEngine & withAntitheticVariate (bool b=true)
operator boost::shared_ptr< PricingEngine > () const
Private Attributes
boost::shared_ptr
< GeneralizedBlackScholesProcess > process_
bool antithetic_
Size steps_
Size stepsPerYear_
Size samples_
Size maxSamples_
Real tolerance_
bool brownianBridge_
BigNatural seed_
Detailed Description
template<class RNG = PseudoRandom, class S = Statistics>
class QuantLib::MakeMCDigitalEngine< RNG, S >
Monte Carlo digital engine factory.
Definition at line 88 of file mcdigitalengine.hpp.
Constructor & Destructor Documentation
template<class RNG , class S > QuantLib::MakeMCDigitalEngine< RNG, S >::MakeMCDigitalEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > & process) [inline]
Definition at line 190 of file mcdigitalengine.hpp.
    : process_(process), antithetic_(false),
      steps_(Null<Size>()), stepsPerYear_(Null<Size>()),
      samples_(Null<Size>()), maxSamples_(Null<Size>()),
      tolerance_(Null<Real>()), brownianBridge_(false), seed_(0) {}
Member Function Documentation
template<class RNG , class S > QuantLib::MakeMCDigitalEngine< RNG, S >::operator boost::shared_ptr< PricingEngine > () const [inline]
Definition at line 262 of file mcdigitalengine.hpp.
References QL_REQUIRE, and anonymous_namespace{marketmodel.cpp}::seed_.
{
        QL_REQUIRE(steps_ != Null<Size>() || stepsPerYear_ != Null<Size>(),
                   "number of steps not given");
        QL_REQUIRE(steps_ == Null<Size>() || stepsPerYear_ == Null<Size>(),
                   "number of steps overspecified");
        return boost::shared_ptr<PricingEngine>(new
            MCDigitalEngine<RNG,S>(process_,
                                   steps_,
                                   stepsPerYear_,
                                   brownianBridge_,
                                   antithetic_,
                                   samples_, tolerance_,
                                   maxSamples_,
                                   seed_));
    }
template<class RNG , class S > MakeMCDigitalEngine< RNG, S > & QuantLib::MakeMCDigitalEngine< RNG, S >::withAbsoluteTolerance (Real tolerance) [inline]
Definition at line 222 of file mcdigitalengine.hpp.
References QL_REQUIRE, and anonymous_namespace{gaussianquadratures.cpp}::tolerance.
{
        QL_REQUIRE(samples_ == Null<Size>(),
                   "number of samples already set");
        QL_REQUIRE(RNG::allowsErrorEstimate,
                   "chosen random generator policy "
                   "does not allow an error estimate");
        tolerance_ = tolerance;
        return *this;
    }
template<class RNG , class S > MakeMCDigitalEngine< RNG, S > & QuantLib::MakeMCDigitalEngine< RNG, S >::withAntitheticVariate (bool b = true) [inline]
Definition at line 255 of file mcdigitalengine.hpp.
References anonymous_namespace{marketmodel.cpp}::b.
{
        antithetic_ = b;
        return *this;
    }
template<class RNG , class S > MakeMCDigitalEngine< RNG, S > & QuantLib::MakeMCDigitalEngine< RNG, S >::withBrownianBridge (bool b = true) [inline]
Definition at line 248 of file mcdigitalengine.hpp.
Referenced by DigitalOptionTest::testMCCashAtHit().
{
        brownianBridge_ = brownianBridge;
        return *this;
    }
template<class RNG , class S > MakeMCDigitalEngine< RNG, S > & QuantLib::MakeMCDigitalEngine< RNG, S >::withMaxSamples (Size samples) [inline]
Definition at line 234 of file mcdigitalengine.hpp.
Referenced by DigitalOptionTest::testMCCashAtHit().
{
        maxSamples_ = samples;
        return *this;
    }
template<class RNG , class S > MakeMCDigitalEngine< RNG, S > & QuantLib::MakeMCDigitalEngine< RNG, S >::withSamples (Size samples) [inline]
Definition at line 213 of file mcdigitalengine.hpp.
References QL_REQUIRE.
Referenced by DigitalOptionTest::testMCCashAtHit().
{
        QL_REQUIRE(tolerance_ == Null<Real>(),
                   "tolerance already set");
        samples_ = samples;
        return *this;
    }
template<class RNG , class S > MakeMCDigitalEngine< RNG, S > & QuantLib::MakeMCDigitalEngine< RNG, S >::withSeed (BigNatural seed) [inline]
Definition at line 241 of file mcdigitalengine.hpp.
References anonymous_namespace{marketmodel.cpp}::seed_.
Referenced by DigitalOptionTest::testMCCashAtHit().
{
        seed_ = seed;
        return *this;
    }
template<class RNG , class S > MakeMCDigitalEngine< RNG, S > & QuantLib::MakeMCDigitalEngine< RNG, S >::withSteps (Size steps) [inline]
Definition at line 199 of file mcdigitalengine.hpp.
{
        steps_ = steps;
        return *this;
    }
template<class RNG , class S > MakeMCDigitalEngine< RNG, S > & QuantLib::MakeMCDigitalEngine< RNG, S >::withStepsPerYear (Size steps) [inline]
Definition at line 206 of file mcdigitalengine.hpp.
{
        stepsPerYear_ = steps;
        return *this;
    }
Member Data Documentation
template<class RNG = PseudoRandom, class S = Statistics> bool QuantLib::MakeMCDigitalEngine< RNG, S >::antithetic_ [private]
Definition at line 105 of file mcdigitalengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> bool QuantLib::MakeMCDigitalEngine< RNG, S >::brownianBridge_ [private]
Definition at line 108 of file mcdigitalengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> Size QuantLib::MakeMCDigitalEngine< RNG, S >::maxSamples_ [private]
Definition at line 106 of file mcdigitalengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> boost::shared_ptr<GeneralizedBlackScholesProcess> QuantLib::MakeMCDigitalEngine< RNG, S >::process_ [private]
Definition at line 104 of file mcdigitalengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> Size QuantLib::MakeMCDigitalEngine< RNG, S >::samples_ [private]
Definition at line 106 of file mcdigitalengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> BigNatural QuantLib::MakeMCDigitalEngine< RNG, S >::seed_ [private]
Definition at line 109 of file mcdigitalengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> Size QuantLib::MakeMCDigitalEngine< RNG, S >::steps_ [private]
Definition at line 106 of file mcdigitalengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> Size QuantLib::MakeMCDigitalEngine< RNG, S >::stepsPerYear_ [private]
Definition at line 106 of file mcdigitalengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> Real QuantLib::MakeMCDigitalEngine< RNG, S >::tolerance_ [private]
Definition at line 107 of file mcdigitalengine.hpp.
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/vanilla/mcdigitalengine.hpp