QuantLib: QuantLib::DouglasScheme Class Reference
QuantLib::DouglasScheme Class Reference
#include <douglasscheme.hpp>
Public Types
typedef OperatorTraits
< FdmLinearOp > traits
typedef traits::operator_type operator_type
typedef traits::array_type array_type
typedef traits::bc_set bc_set
typedef traits::condition_type condition_type
Public Member Functions
DouglasScheme (Real theta, const boost::shared_ptr< FdmLinearOpComposite > &map, const bc_set &bcSet=bc_set())
void step (array_type &a, Time t)
void setStep (Time dt)
Protected Attributes
Time dt_
const Real theta_
const boost::shared_ptr
< FdmLinearOpComposite > & map_
const BoundaryConditionSchemeHelper bcSet_
Detailed Description
Definition at line 35 of file douglasscheme.hpp.
Member Typedef Documentation
typedef traits::array_type QuantLib::DouglasScheme::array_type
Definition at line 40 of file douglasscheme.hpp.
typedef traits::bc_set QuantLib::DouglasScheme::bc_set
Definition at line 41 of file douglasscheme.hpp.
typedef traits::condition_type QuantLib::DouglasScheme::condition_type
Definition at line 42 of file douglasscheme.hpp.
typedef traits::operator_type QuantLib::DouglasScheme::operator_type
Definition at line 39 of file douglasscheme.hpp.
typedef OperatorTraits<FdmLinearOp> QuantLib::DouglasScheme::traits
Definition at line 38 of file douglasscheme.hpp.
Constructor & Destructor Documentation
QuantLib::DouglasScheme::DouglasScheme (Real theta, const boost::shared_ptr< FdmLinearOpComposite > & map, const bc_set & bcSet = bc_set())
Definition at line 25 of file douglasscheme.cpp.
    : dt_(Null<Real>()),
      theta_(theta),
      map_(map),
      bcSet_(bcSet) {
    }
Member Function Documentation
void QuantLib::DouglasScheme::setStep (Time dt)
Definition at line 53 of file douglasscheme.cpp.
References QuantLib::anonymous_namespace{yieldtermstructure.cpp}::dt, and dt_.
{
        dt_=dt;
    }
void QuantLib::DouglasScheme::step (array_type & a, Time t)
Definition at line 35 of file douglasscheme.cpp.
References QuantLib::BoundaryConditionSchemeHelper::applyAfterApplying(), QuantLib::BoundaryConditionSchemeHelper::applyAfterSolving(), QuantLib::BoundaryConditionSchemeHelper::applyBeforeApplying(), bcSet_, dt_, map_, QL_REQUIRE, QuantLib::BoundaryConditionSchemeHelper::setTime(), and theta_.
{
        QL_REQUIRE(t-dt_ > -1e-8, "a step towards negative time given");
        map_->setTime(std::max(0.0, t-dt_), t);
        bcSet_.setTime(std::max(0.0, t-dt_));
        bcSet_.applyBeforeApplying(*map_);
        Array y = a + dt_*map_->apply(a);
        bcSet_.applyAfterApplying(y);
        for (Size i=0; i < map_->size(); ++i) {
            Array rhs = y - theta_*dt_*map_->apply_direction(i, a);
            y = map_->solve_splitting(i, rhs, -theta_*dt_);
        }
        bcSet_.applyAfterSolving(y);
        a = y;
    }
Member Data Documentation
const BoundaryConditionSchemeHelper QuantLib::DouglasScheme::bcSet_ [protected]
Definition at line 56 of file douglasscheme.hpp.
Referenced by step().
Time QuantLib::DouglasScheme::dt_ [protected]
Definition at line 53 of file douglasscheme.hpp.
Referenced by setStep(), and step().
const boost::shared_ptr<FdmLinearOpComposite>& QuantLib::DouglasScheme::map_ [protected]
Definition at line 55 of file douglasscheme.hpp.
Referenced by step().
const Real QuantLib::DouglasScheme::theta_ [protected]
Definition at line 54 of file douglasscheme.hpp.
Referenced by step().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/schemes/douglasscheme.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/schemes/douglasscheme.cpp