QuantLib: QuantLib::Swaption Class Reference
QuantLib::Swaption Class Reference
Swaption class
#include <swaption.hpp>
Classes
class arguments
Arguments for swaption calculation
class engine
base class for swaption engines
Public Member Functions
Swaption (const boost::shared_ptr< VanillaSwap > &swap, const boost::shared_ptr< Exercise > &exercise, Settlement::Type delivery=Settlement::Physical)
Volatility impliedVolatility (Real price, const Handle< YieldTermStructure > &discountCurve, Volatility guess, Real accuracy=1.0e-4, Natural maxEvaluations=100, Volatility minVol=1.0e-7, Volatility maxVol=4.0) const
implied volatility
Instrument interface
bool isExpired () const
returns whether the instrument might have value greater than zero.
void setupArguments (PricingEngine::arguments *) const
Inspectors
Settlement::Type settlementType () const
VanillaSwap::Type type () const
const boost::shared_ptr
< VanillaSwap > & underlyingSwap () const
Private Attributes
boost::shared_ptr< VanillaSwap > swap_
Settlement::Type settlementType_
Detailed Description
Swaption class
Test:
the correctness of the returned value is tested by checking that the price of a payer (resp. receiver) swaption decreases (resp. increases) with the strike.
the correctness of the returned value is tested by checking that the price of a payer (resp. receiver) swaption increases (resp. decreases) with the spread.
the correctness of the returned value is tested by checking it against that of a swaption on a swap with no spread and a correspondingly adjusted fixed rate.
the correctness of the returned value is tested by checking it against a known good value.
the correctness of the returned value of cash settled swaptions is tested by checking the modified annuity against a value calculated without using the Swaption class.
Todo:
add greeks and explicit exercise lag
Definition at line 66 of file swaption.hpp.
Constructor & Destructor Documentation
QuantLib::Swaption::Swaption (const boost::shared_ptr< VanillaSwap > & swap, const boost::shared_ptr< Exercise > & exercise, Settlement::Type delivery = Settlement::Physical)
Definition at line 100 of file swaption.cpp.
References QuantLib::Observer::registerWith(), and swap_.
    : Option(boost::shared_ptr<Payoff>(), exercise), swap_(swap),
      settlementType_(delivery) {
        registerWith(swap_);
    }
Member Function Documentation
Volatility QuantLib::Swaption::impliedVolatility (Real price, const Handle< YieldTermStructure > & discountCurve, Volatility guess, Real accuracy = 1.0e-4, Natural maxEvaluations = 100, Volatility minVol = 1.0e-7, Volatility maxVol = 4.0) const
implied volatility
Definition at line 132 of file swaption.cpp.
References anonymous_namespace{interpolations.cpp}::f(), isExpired(), QL_REQUIRE, QuantLib::Solver1D< Impl >::setMaxEvaluations(), and QuantLib::Solver1D< Impl >::solve().
Referenced by anonymous_namespace{swaptionvolatilitymatrix.cpp}::CommonVars::makeCoherenceTest().
{
        //calculate();
        QL_REQUIRE(!isExpired(), "instrument expired");
        ImpliedVolHelper f(*this, discountCurve, targetValue);
        //Brent solver;
        NewtonSafe solver;
        solver.setMaxEvaluations(maxEvaluations);
        return solver.solve(f, accuracy, guess, minVol, maxVol);
    }
bool QuantLib::Swaption::isExpired () const [virtual]
returns whether the instrument might have value greater than zero.
Implements QuantLib::Instrument.
Definition at line 108 of file swaption.cpp.
References QuantLib::Option::exercise_.
Referenced by impliedVolatility().
{
        return detail::simple_event(exercise_->dates().back()).hasOccurred();
    }
Settlement::Type QuantLib::Swaption::settlementType () const [inline]
Definition at line 80 of file swaption.hpp.
References settlementType_.
{ return settlementType_; }
void QuantLib::Swaption::setupArguments (PricingEngine::arguments *) const [virtual]
When a derived argument structure is defined for an instrument, this method should be overridden to fill it. This is mandatory in case a pricing engine is used.
Reimplemented from QuantLib::Option.
Definition at line 112 of file swaption.cpp.
References QuantLib::Option::arguments::exercise, QuantLib::Option::exercise_, QL_REQUIRE, QuantLib::Swaption::arguments::settlementType, settlementType_, QuantLib::Swaption::arguments::swap, and swap_.
Referenced by QuantLib::anonymous_namespace{swaption.cpp}::ImpliedVolHelper::ImpliedVolHelper().
{
        swap_->setupArguments(args);
        Swaption::arguments* arguments =
            dynamic_cast<Swaption::arguments*>(args);
        QL_REQUIRE(arguments != 0, "wrong argument type");
        arguments->swap = swap_;
        arguments->settlementType = settlementType_;
        arguments->exercise = exercise_;
    }
VanillaSwap::Type QuantLib::Swaption::type () const [inline]
Definition at line 81 of file swaption.hpp.
References swap_.
{ return swap_->type(); }
const boost::shared_ptr<VanillaSwap>& QuantLib::Swaption::underlyingSwap () const [inline]
Definition at line 82 of file swaption.hpp.
References swap_.
Referenced by anonymous_namespace{swaptionvolatilitymatrix.cpp}::CommonVars::makeCoherenceTest().
{
            return swap_;
        }
Member Data Documentation
Settlement::Type QuantLib::Swaption::settlementType_ [private]
Definition at line 99 of file swaption.hpp.
Referenced by settlementType(), and setupArguments().
boost::shared_ptr<VanillaSwap> QuantLib::Swaption::swap_ [private]
Definition at line 97 of file swaption.hpp.
Referenced by setupArguments(), Swaption(), type(), and underlyingSwap().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/swaption.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/swaption.cpp