QuantLib: QuantLib::FdmLinearOpLayout Class Reference
QuantLib::FdmLinearOpLayout Class Reference
#include <fdmlinearoplayout.hpp>
Public Member Functions
FdmLinearOpLayout (const std::vector< Size > &dim)
FdmLinearOpIterator begin () const
FdmLinearOpIterator end () const
const std::vector< Size > & dim () const
const std::vector< Size > & spacing () const
Size size () const
Size index (const std::vector< Size > &coordinates) const
Size neighbourhood (const FdmLinearOpIterator &iterator, Size i, Integer offset) const
Size neighbourhood (const FdmLinearOpIterator &iterator, Size i1, Integer offset1, Size i2, Integer offset2) const
Disposable< FdmLinearOpIterator > iter_neighbourhood (const FdmLinearOpIterator &iterator, Size i, Integer offset) const
Private Attributes
Size size_
std::vector< Size > dim_
std::vector< Size > spacing_
Detailed Description
Definition at line 34 of file fdmlinearoplayout.hpp.
Constructor & Destructor Documentation
QuantLib::FdmLinearOpLayout::FdmLinearOpLayout (const std::vector< Size > & dim) [inline]
Definition at line 36 of file fdmlinearoplayout.hpp.
References size_, and spacing_.
        : dim_(dim), spacing_(dim.size()) {
            spacing_[0] = 1;
            std::partial_sum(dim.begin(), dim.end()-1,
                spacing_.begin()+1, std::multiplies<Size>());
            size_ = spacing_.back()*dim.back();
        }
Member Function Documentation
FdmLinearOpIterator QuantLib::FdmLinearOpLayout::begin () const [inline]
Definition at line 45 of file fdmlinearoplayout.hpp.
References dim_.
Referenced by FdmLinearOpTest::testFdmLinearOpLayout().
{
            return FdmLinearOpIterator(dim_);
        }
const std::vector<Size>& QuantLib::FdmLinearOpLayout::dim () const [inline]
Definition at line 53 of file fdmlinearoplayout.hpp.
References dim_.
Referenced by FdmLinearOpTest::testFdmLinearOpLayout().
{
            return dim_;
        }
FdmLinearOpIterator QuantLib::FdmLinearOpLayout::end () const [inline]
Definition at line 49 of file fdmlinearoplayout.hpp.
References size_.
{
            return FdmLinearOpIterator(size_);
        }
Size QuantLib::FdmLinearOpLayout::index (const std::vector< Size > & coordinates) const [inline]
Definition at line 65 of file fdmlinearoplayout.hpp.
References QuantLib::dsd::inner_product(), and spacing_.
Referenced by iter_neighbourhood(), and FdmLinearOpTest::testFdmLinearOpLayout().
{
            return std::inner_product(coordinates.begin(),
                                      coordinates.end(),
                                      spacing_.begin(), Size(0));
        }
Disposable< FdmLinearOpIterator > QuantLib::FdmLinearOpLayout::iter_neighbourhood (const FdmLinearOpIterator & iterator, Size i, Integer offset) const
Definition at line 69 of file fdmlinearoplayout.cpp.
References QuantLib::FdmLinearOpIterator::coordinates(), dim_, and index().
{
        std::vector<Size> coordinates = iterator.coordinates();
        Integer coorOffset = Integer(coordinates[i])+offset;
        if (coorOffset < 0) {
            coorOffset=-coorOffset;
        }
        else if (Size(coorOffset) >= dim_[i]) {
            coorOffset = 2*(dim_[i]-1) - coorOffset;
        }
        coordinates[i] = Size(coorOffset);
        FdmLinearOpIterator retVal(dim_, coordinates,
                                   index(coordinates));
        return retVal;
    }
Size QuantLib::FdmLinearOpLayout::neighbourhood (const FdmLinearOpIterator & iterator, Size i, Integer offset) const
Definition at line 26 of file fdmlinearoplayout.cpp.
References QuantLib::FdmLinearOpIterator::coordinates(), dim_, QuantLib::FdmLinearOpIterator::index(), and spacing_.
Referenced by FdmLinearOpTest::testFdmLinearOpLayout().
{
        Size myIndex = iterator.index()
            - iterator.coordinates()[i]*spacing_[i];
        Integer coorOffset = Integer(iterator.coordinates()[i])+offset;
        if (coorOffset < 0) {
            coorOffset=-coorOffset;
        }
        else if (Size(coorOffset) >= dim_[i]) {
            coorOffset = 2*(dim_[i]-1) - coorOffset;
        }
        return myIndex + coorOffset*spacing_[i];
    }
Size QuantLib::FdmLinearOpLayout::neighbourhood (const FdmLinearOpIterator & iterator, Size i1, Integer offset1, Size i2, Integer offset2) const
Definition at line 41 of file fdmlinearoplayout.cpp.
References QuantLib::FdmLinearOpIterator::coordinates(), dim_, QuantLib::FdmLinearOpIterator::index(), and spacing_.
{
        Size myIndex = iterator.index()
            - iterator.coordinates()[i1]*spacing_[i1]
            - iterator.coordinates()[i2]*spacing_[i2];
        Integer coorOffset1 = Integer(iterator.coordinates()[i1])+offset1;
        if (coorOffset1 < 0) {
            coorOffset1=-coorOffset1;
        }
        else if (Size(coorOffset1) >= dim_[i1]) {
            coorOffset1 = 2*(dim_[i1]-1) - coorOffset1;
        }
        Integer coorOffset2 = Integer(iterator.coordinates()[i2])+offset2;
        if (coorOffset2 < 0) {
            coorOffset2=-coorOffset2;
        }
        else if (Size(coorOffset2) >= dim_[i2]) {
            coorOffset2 = 2*(dim_[i2]-1) - coorOffset2;
        }
        return myIndex + coorOffset1*spacing_[i1]+coorOffset2*spacing_[i2];
    }
Size QuantLib::FdmLinearOpLayout::size () const [inline]
Definition at line 61 of file fdmlinearoplayout.hpp.
References size_.
Referenced by FdmLinearOpTest::testFdmLinearOpLayout().
{
            return size_;
        }
const std::vector<Size>& QuantLib::FdmLinearOpLayout::spacing () const [inline]
Definition at line 57 of file fdmlinearoplayout.hpp.
References spacing_.
Referenced by QuantLib::TripleBandLinearOp::TripleBandLinearOp().
{
            return spacing_;
        }
Member Data Documentation
std::vector<Size> QuantLib::FdmLinearOpLayout::dim_ [private]
Definition at line 84 of file fdmlinearoplayout.hpp.
Referenced by begin(), dim(), iter_neighbourhood(), and neighbourhood().
Size QuantLib::FdmLinearOpLayout::size_ [private]
Definition at line 83 of file fdmlinearoplayout.hpp.
Referenced by end(), FdmLinearOpLayout(), and size().
std::vector<Size> QuantLib::FdmLinearOpLayout::spacing_ [private]
Definition at line 84 of file fdmlinearoplayout.hpp.
Referenced by FdmLinearOpLayout(), index(), neighbourhood(), and spacing().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/operators/fdmlinearoplayout.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/operators/fdmlinearoplayout.cpp