QuantLib: QuantLib::InterestRateIndex Class Reference
QuantLib::InterestRateIndex Class Reference
base class for interest rate indexes
#include <interestrateindex.hpp>
Public Member Functions
InterestRateIndex (const std::string &familyName, const Period &tenor, Natural settlementDays, const Currency &currency, const Calendar &fixingCalendar, const DayCounter &dayCounter)
Index interface
std::string name () const
Returns the name of the index.
Calendar fixingCalendar () const
returns the calendar defining valid fixing dates
bool isValidFixingDate (const Date &fixingDate) const
returns TRUE if the fixing date is a valid one
Rate fixing (const Date &fixingDate, bool forecastTodaysFixing=false) const
returns the fixing at the given date
Observer interface
void update ()
Inspectors
std::string familyName () const
Period tenor () const
Natural fixingDays () const
Date fixingDate (const Date &valueDate) const
const Currency & currency () const
const DayCounter & dayCounter () const
Date calculations
These method can be overridden to implement particular conventions (e.g. EurLibor)
virtual Date valueDate (const Date &fixingDate) const
virtual Date maturityDate (const Date &valueDate) const =0
Fixing calculations
virtual Rate forecastFixing (const Date &fixingDate) const =0
It can be overridden to implement particular conventions.
Rate pastFixing (const Date &fixingDate) const
Protected Attributes
std::string familyName_
Period tenor_
Natural fixingDays_
Currency currency_
DayCounter dayCounter_
Private Attributes
std::string name_
Calendar fixingCalendar_
Detailed Description
base class for interest rate indexes
Todo:
add methods returning InterestRate
Definition at line 39 of file interestrateindex.hpp.
Constructor & Destructor Documentation
QuantLib::InterestRateIndex::InterestRateIndex (const std::string & familyName, const Period & tenor, Natural settlementDays, const Currency & currency, const Calendar & fixingCalendar, const DayCounter & dayCounter)
Definition at line 29 of file interestrateindex.cpp.
References dayCounter_, QuantLib::Days, familyName_, fixingDays_, QuantLib::Singleton< Settings >::instance(), QuantLib::Singleton< IndexManager >::instance(), name(), QuantLib::DayCounter::name(), name_, QuantLib::Period::normalize(), QuantLib::Observer::registerWith(), QuantLib::io::short_period(), and tenor_.
    : familyName_(familyName), tenor_(tenor), fixingDays_(fixingDays),
      currency_(currency), dayCounter_(dayCounter),
      fixingCalendar_(fixingCalendar) {
        tenor_.normalize();
        std::ostringstream out;
        out << familyName_;
        if (tenor_ == 1*Days) {
            if (fixingDays_==0)
                out << "ON";
            else if (fixingDays_==1)
                out << "TN";
            else if (fixingDays_==2)
                out << "SN";
            else
                out << io::short_period(tenor_);
        } else {
            out << io::short_period(tenor_);
        }
        out << " " << dayCounter_.name();
        name_ = out.str();
        registerWith(Settings::instance().evaluationDate());
        registerWith(IndexManager::instance().notifier(name()));
    }
Member Function Documentation
const Currency& QuantLib::InterestRateIndex::currency () const [inline]
Definition at line 66 of file interestrateindex.hpp.
References currency_.
Referenced by QuantLib::Libor::clone(), QuantLib::IborIndex::clone(), QuantLib::SwapIndex::clone(), and QuantLib::OvernightIndex::clone().
{ return currency_; }
const DayCounter& QuantLib::InterestRateIndex::dayCounter () const [inline]
Definition at line 67 of file interestrateindex.hpp.
References dayCounter_.
Referenced by QuantLib::Libor::clone(), QuantLib::IborIndex::clone(), QuantLib::SwapIndex::clone(), QuantLib::OvernightIndex::clone(), and anonymous_namespace{piecewiseyieldcurve.cpp}::CommonVars::CommonVars().
{ return dayCounter_; }
std::string QuantLib::InterestRateIndex::familyName () const [inline]
Definition at line 62 of file interestrateindex.hpp.
References familyName_.
Referenced by QuantLib::Libor::clone(), QuantLib::IborIndex::clone(), QuantLib::SwapIndex::clone(), and QuantLib::OvernightIndex::clone().
{ return familyName_; }
Rate QuantLib::InterestRateIndex::fixing (const Date & fixingDate, bool forecastTodaysFixing = false) const [virtual]
returns the fixing at the given date
the date passed as arguments must be the actual calendar date of the fixing; no settlement days must be used.
Implements QuantLib::Index.
Definition at line 61 of file interestrateindex.cpp.
References QuantLib::Settings::evaluationDate(), forecastFixing(), QuantLib::Singleton< Settings >::instance(), isValidFixingDate(), name(), pastFixing(), and QL_REQUIRE.
Referenced by anonymous_namespace{piecewiseyieldcurve.cpp}::testCurveConsistency().
{
        QL_REQUIRE(isValidFixingDate(fixingDate),
                   "Fixing date " << fixingDate << " is not valid");
        Date today = Settings::instance().evaluationDate();
        if (fixingDate>today ||
            (fixingDate==today && forecastTodaysFixing))
            return forecastFixing(fixingDate);
        if (fixingDate<today ||
            Settings::instance().enforcesTodaysHistoricFixings()) {
            // must have been fixed
            // do not catch exceptions
            Rate result = pastFixing(fixingDate);
            QL_REQUIRE(result != Null<Real>(),
                       "Missing " << name() << " fixing for " << fixingDate);
            return result;
        }
        try {
            // might have been fixed
            Rate result = pastFixing(fixingDate);
            if (result!=Null<Real>())
                return result;
            else
                ;   // fall through and forecast
        } catch (Error&) {
                ;   // fall through and forecast
        }
        return forecastFixing(fixingDate);
    }
Calendar QuantLib::InterestRateIndex::fixingCalendar () const [inline, virtual]
returns the calendar defining valid fixing dates
Implements QuantLib::Index.
Definition at line 103 of file interestrateindex.hpp.
References fixingCalendar_.
Referenced by QuantLib::IborIndex::clone(), QuantLib::SwapIndex::clone(), QuantLib::OvernightIndex::clone(), anonymous_namespace{piecewiseyieldcurve.cpp}::CommonVars::CommonVars(), fixingDate(), QuantLib::BMAIndex::fixingSchedule(), QuantLib::BMAIndex::forecastFixing(), QuantLib::BMAIndex::isValidFixingDate(), isValidFixingDate(), QuantLib::IborIndex::maturityDate(), QuantLib::BMAIndex::maturityDate(), QuantLib::SwapIndex::underlyingSwap(), QuantLib::Libor::valueDate(), and valueDate().
{
        return fixingCalendar_;
    }
Date QuantLib::InterestRateIndex::fixingDate (const Date & valueDate) const [inline]
Definition at line 115 of file interestrateindex.hpp.
References QuantLib::Calendar::advance(), QuantLib::Days, fixingCalendar(), and fixingDays_.
Referenced by QuantLib::BMAIndex::maturityDate(), QuantLib::SwapIndex::maturityDate(), pastFixing(), QuantLib::SwapIndex::underlyingSwap(), and QuantLib::OvernightIndexedSwapIndex::underlyingSwap().
{
        Date fixingDate = fixingCalendar().advance(valueDate,
            -static_cast<Integer>(fixingDays_), Days);
        return fixingDate;
    }
Natural QuantLib::InterestRateIndex::fixingDays () const [inline]
Definition at line 64 of file interestrateindex.hpp.
References fixingDays_.
Referenced by QuantLib::Libor::clone(), QuantLib::IborIndex::clone(), QuantLib::SwapIndex::clone(), QuantLib::OvernightIndex::clone(), and anonymous_namespace{piecewiseyieldcurve.cpp}::CommonVars::CommonVars().
{ return fixingDays_; }
virtual Rate QuantLib::InterestRateIndex::forecastFixing (const Date & fixingDate) const [pure virtual]
It can be overridden to implement particular conventions.
Implemented in QuantLib::SwapIndex, QuantLib::BMAIndex, QuantLib::IborIndex, and QuantLib::ProxyIbor.
Referenced by fixing().
bool QuantLib::InterestRateIndex::isValidFixingDate (const Date & fixingDate) const [inline, virtual]
returns TRUE if the fixing date is a valid one
Implements QuantLib::Index.
Reimplemented in QuantLib::BMAIndex.
Definition at line 107 of file interestrateindex.hpp.
References fixingCalendar(), and QuantLib::Calendar::isBusinessDay().
Referenced by fixing(), pastFixing(), QuantLib::EURLibor::valueDate(), QuantLib::Libor::valueDate(), and valueDate().
{
        return fixingCalendar().isBusinessDay(d);
    }
virtual Date QuantLib::InterestRateIndex::maturityDate (const Date & valueDate) const [pure virtual]
Implemented in QuantLib::SwapIndex, QuantLib::BMAIndex, QuantLib::Libor, QuantLib::EURLibor, and QuantLib::IborIndex.
std::string QuantLib::InterestRateIndex::name () const [inline, virtual]
Returns the name of the index.
Warning:
This method is used for output and comparison between indexes. It is not meant to be used for writing switch-on-type code.
Implements QuantLib::Index.
Reimplemented in QuantLib::BMAIndex.
Definition at line 99 of file interestrateindex.hpp.
References name_.
Referenced by fixing(), QuantLib::IborIndex::forecastFixing(), and InterestRateIndex().
{
        return name_;
    }
Rate QuantLib::InterestRateIndex::pastFixing (const Date & fixingDate) const [inline]
Definition at line 127 of file interestrateindex.hpp.
References fixingDate(), isValidFixingDate(), QL_REQUIRE, and QuantLib::Index::timeSeries().
Referenced by fixing().
{
        QL_REQUIRE(isValidFixingDate(fixingDate),
                   fixingDate << " is not a valid fixing date");
        return timeSeries()[fixingDate];
    }
Period QuantLib::InterestRateIndex::tenor () const [inline]
Definition at line 63 of file interestrateindex.hpp.
References tenor_.
Referenced by QuantLib::Libor::clone(), QuantLib::IborIndex::clone(), QuantLib::SwapIndex::clone(), QuantLib::Euribor::Euribor(), QuantLib::Euribor365::Euribor365(), QuantLib::EURLibor::EURLibor(), and QuantLib::Libor::Libor().
{ return tenor_; }
void QuantLib::InterestRateIndex::update () [inline, virtual]
This method must be implemented in derived classes. An instance of Observer does not call this method directly: instead, it will be called by the observables the instance registered with when they need to notify any changes.
Implements QuantLib::Observer.
Definition at line 111 of file interestrateindex.hpp.
References QuantLib::Observable::notifyObservers().
{
        notifyObservers();
    }
Date QuantLib::InterestRateIndex::valueDate (const Date & fixingDate) const [inline, virtual]
Reimplemented in QuantLib::Libor, and QuantLib::EURLibor.
Definition at line 121 of file interestrateindex.hpp.
References QuantLib::Calendar::advance(), QuantLib::Days, fixingCalendar(), fixingDays_, isValidFixingDate(), and QL_REQUIRE.
Referenced by QuantLib::IborIndex::forecastFixing(), QuantLib::SwapIndex::underlyingSwap(), and QuantLib::OvernightIndexedSwapIndex::underlyingSwap().
{
        QL_REQUIRE(isValidFixingDate(fixingDate),
                   fixingDate << " is not a valid fixing date");
        return fixingCalendar().advance(fixingDate, fixingDays_, Days);
    }
Member Data Documentation
Currency QuantLib::InterestRateIndex::currency_ [protected]
Definition at line 89 of file interestrateindex.hpp.
Referenced by currency().
DayCounter QuantLib::InterestRateIndex::dayCounter_ [protected]
Definition at line 90 of file interestrateindex.hpp.
Referenced by dayCounter(), QuantLib::IborIndex::forecastFixing(), QuantLib::BMAIndex::forecastFixing(), InterestRateIndex(), QuantLib::SwapIndex::underlyingSwap(), and QuantLib::OvernightIndexedSwapIndex::underlyingSwap().
std::string QuantLib::InterestRateIndex::familyName_ [protected]
Definition at line 86 of file interestrateindex.hpp.
Referenced by familyName(), and InterestRateIndex().
Calendar QuantLib::InterestRateIndex::fixingCalendar_ [private]
Definition at line 93 of file interestrateindex.hpp.
Referenced by fixingCalendar().
Natural QuantLib::InterestRateIndex::fixingDays_ [protected]
Definition at line 88 of file interestrateindex.hpp.
Referenced by fixingDate(), fixingDays(), InterestRateIndex(), QuantLib::EURLibor::valueDate(), QuantLib::Libor::valueDate(), and valueDate().
std::string QuantLib::InterestRateIndex::name_ [private]
Definition at line 92 of file interestrateindex.hpp.
Referenced by InterestRateIndex(), and name().
Period QuantLib::InterestRateIndex::tenor_ [protected]
Reimplemented in QuantLib::SwapIndex.
Definition at line 87 of file interestrateindex.hpp.
Referenced by InterestRateIndex(), QuantLib::IborIndex::maturityDate(), QuantLib::EURLibor::maturityDate(), QuantLib::Libor::maturityDate(), and tenor().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/indexes/interestrateindex.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/indexes/interestrateindex.cpp