QuantLib: QuantLib::InterpolatedCPICapFloorTermPriceSurface< Interpolator2D > Class Template Reference
QuantLib::InterpolatedCPICapFloorTermPriceSurface< Interpolator2D > Class Template Reference
#include <cpicapfloortermpricesurface.hpp>
Public Member Functions
InterpolatedCPICapFloorTermPriceSurface (Real nominal, Rate startRate, const Period &observationLag, const Calendar &cal, const BusinessDayConvention &bdc, const DayCounter &dc, const Handle< ZeroInflationIndex > &zii, const Handle< YieldTermStructure > &yts, const std::vector< Rate > &cStrikes, const std::vector< Rate > &fStrikes, const std::vector< Period > &cfMaturities, const Matrix &cPrice, const Matrix &fPrice, const Interpolator2D &interpolator2d=Interpolator2D())
LazyObject interface
void update ()
void performCalculations () const
virtual Real price (const Date &d, Rate k) const
remember that the strikes use the quoting convention
virtual Real capPrice (const Date &d, Rate k) const
remember that the strike uses the quoting convention
virtual Real floorPrice (const Date &d, Rate k) const
remember that the strike uses the quoting convention
Protected Attributes
std::vector< Rate > allStrikes_
Matrix cPriceB_
Matrix fPriceB_
Interpolation2D capPrice_
Interpolation2D floorPrice_
Interpolator2D interpolator2d_
Detailed Description
template<class Interpolator2D>
class QuantLib::InterpolatedCPICapFloorTermPriceSurface< Interpolator2D >
Definition at line 160 of file cpicapfloortermpricesurface.hpp.
Constructor & Destructor Documentation
template<class Interpolator2D > QuantLib::InterpolatedCPICapFloorTermPriceSurface< Interpolator2D >::InterpolatedCPICapFloorTermPriceSurface (Real nominal, Rate startRate, const Period & observationLag, const Calendar & cal, const BusinessDayConvention & bdc, const DayCounter & dc, const Handle< ZeroInflationIndex > & zii, const Handle< YieldTermStructure > & yts, const std::vector< Rate > & cStrikes, const std::vector< Rate > & fStrikes, const std::vector< Period > & cfMaturities, const Matrix & cPrice, const Matrix & fPrice, const Interpolator2D & interpolator2d = Interpolator2D())
Definition at line 216 of file cpicapfloortermpricesurface.hpp.
References QuantLib::InterpolatedCPICapFloorTermPriceSurface< Interpolator2D >::performCalculations().
    : CPICapFloorTermPriceSurface(nominal, startRate, observationLag, cal, bdc, dc,
                                  zii, yts, cStrikes, fStrikes, cfMaturities, cPrice, fPrice),
      interpolator2d_(interpolator2d) {
        performCalculations();
    }
Member Function Documentation
template<class I2D > Real QuantLib::InterpolatedCPICapFloorTermPriceSurface< I2D >::capPrice (const Date & d, Rate k) const [virtual]
remember that the strike uses the quoting convention
Implements QuantLib::CPICapFloorTermPriceSurface.
Definition at line 349 of file cpicapfloortermpricesurface.hpp.
References anonymous_namespace{quantlibbenchmark.cpp}::t.
{
        Time t = timeFromReference(d);
        return capPrice_(t,k);
    }
template<class I2D > Real QuantLib::InterpolatedCPICapFloorTermPriceSurface< I2D >::floorPrice (const Date & d, Rate k) const [virtual]
remember that the strike uses the quoting convention
Implements QuantLib::CPICapFloorTermPriceSurface.
Definition at line 357 of file cpicapfloortermpricesurface.hpp.
References anonymous_namespace{quantlibbenchmark.cpp}::t.
{
        Time t = timeFromReference(d);
        return floorPrice_(t,k);
    }
template<class I2D > void QuantLib::InterpolatedCPICapFloorTermPriceSurface< I2D >::performCalculations () const
set up the interpolations for capPrice_ and floorPrice_ since we know ATM, and we have single flows, we can use put/call parity to extend the surfaces across all strikes
Definition at line 253 of file cpicapfloortermpricesurface.hpp.
References QuantLib::Handle< T >::empty(), QuantLib::Period::length(), anonymous_namespace{inflation.cpp}::nominalTermStructure(), QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow(), and QL_REQUIRE.
Referenced by QuantLib::InterpolatedCPICapFloorTermPriceSurface< Interpolator2D >::InterpolatedCPICapFloorTermPriceSurface().
{
        Size nMat = cfMaturities_.size(), ncK = cStrikes_.size(), nfK = fStrikes_.size(),
            nK = ncK + nfK;
        Matrix cP(nK, nMat), fP(nK, nMat);
        Handle<ZeroInflationTermStructure> zts = zii_->zeroInflationTermStructure();
        Handle<YieldTermStructure> yts = this->nominalTermStructure();
        QL_REQUIRE(!zts.empty(),"Zts is empty!!!");
        QL_REQUIRE(!yts.empty(),"Yts is empty!!!");
        for (Size i =0; i<nfK; i++){
            allStrikes_.push_back(fStrikes_[i]);
            for (Size j=0; j<nMat; j++) {
                Period mat = cfMaturities_[j];
                Real df = yts->discount(cpiOptionDateFromTenor(mat));
                Real atm_quote = zts->zeroRate(cpiOptionDateFromTenor(mat));
                Real atm = pow(1.0+atm_quote, mat.length());
                Real S = atm * df;
                Real K_quote = fStrikes_[i]/100.0;
                Real K = pow(1.0+K_quote, mat.length());
                cP[i][j] = fPrice_[i][j] + S - K * df;
                fP[i][j] = fPrice_[i][j];
            }
        }
        for (Size i =0; i<ncK; i++){
            allStrikes_.push_back(cStrikes_[i]);
            for (Size j=0; j<nMat; j++) {
                Period mat = cfMaturities_[j];
                Real df = yts->discount(cpiOptionDateFromTenor(mat));
                Real atm_quote = zts->zeroRate(cpiOptionDateFromTenor(mat));
                Real atm = pow(1.0+atm_quote, mat.length());
                Real S = atm * df;
                Real K_quote = cStrikes_[i]/100.0;
                Real K = pow(1.0+K_quote, mat.length());
                cP[i+nfK][j] = cPrice_[i][j];
                fP[i+nfK][j] = cPrice_[i][j] + K * df - S;
            }
        }
        // copy to store
        cPriceB_ = cP;
        fPriceB_ = fP;
        cfMaturityTimes_.clear();
        for (Size i=0; i<cfMaturities_.size();i++) {
            cfMaturityTimes_.push_back(timeFromReference(cpiOptionDateFromTenor(cfMaturities_[i])));
        }
        capPrice_ = interpolator2d_.interpolate(cfMaturityTimes_.begin(),cfMaturityTimes_.end(),
                                                allStrikes_.begin(), allStrikes_.end(),
                                                cPriceB_
                                                );
        capPrice_.enableExtrapolation();
        floorPrice_ = interpolator2d_.interpolate(cfMaturityTimes_.begin(),cfMaturityTimes_.end(),
                                                  allStrikes_.begin(), allStrikes_.end(),
                                                  fPriceB_
                                                  );
        floorPrice_.enableExtrapolation();
        /* test code - note order of indices
        for (Size i =0; i<nK; i++){
            std::cout << allStrikes_[i] << ":  ";
            Real qK = allStrikes_[i];
            for (Size j=0; j<nMat; j++) {
                Real t = cfMaturityTimes_[j];
                std::cout << fP[i][j] << "," << floorPrice_(t,qK) << " | " ;
            }
            std::cout << std::endl;
        }
        for (Size i =0; i<nK; i++){
            std::cout << allStrikes_[i] << ":  ";
            Real qK = allStrikes_[i];
            for (Size j=0; j<nMat; j++) {
                Real t = cfMaturityTimes_[j];
                std::cout << cP[i][j] << "," << capPrice_(t,qK) << " | " ;
            }
            std::cout << std::endl;
        }
        */
    }
template<class I2D > Real QuantLib::InterpolatedCPICapFloorTermPriceSurface< I2D >::price (const Date & d, Rate k) const [virtual]
remember that the strikes use the quoting convention
remember that the strike uses the quoting convention
Implements QuantLib::CPICapFloorTermPriceSurface.
Definition at line 340 of file cpicapfloortermpricesurface.hpp.
{
        Rate atm = zeroInflationIndex()->zeroInflationTermStructure()->zeroRate(d);
        return k > atm ? capPrice(d,k): floorPrice(d,k);
    }
template<class I2D > void QuantLib::InterpolatedCPICapFloorTermPriceSurface< I2D >::update () [virtual]
This method must be implemented in derived classes. An instance of Observer does not call this method directly: instead, it will be called by the observables the instance registered with when they need to notify any changes.
Reimplemented from QuantLib::TermStructure.
Definition at line 242 of file cpicapfloortermpricesurface.hpp.
             {
        notifyObservers();
    }
Member Data Documentation
template<class Interpolator2D > std::vector<Rate> QuantLib::InterpolatedCPICapFloorTermPriceSurface< Interpolator2D >::allStrikes_ [mutable, protected]
Definition at line 201 of file cpicapfloortermpricesurface.hpp.
template<class Interpolator2D > Interpolation2D QuantLib::InterpolatedCPICapFloorTermPriceSurface< Interpolator2D >::capPrice_ [mutable, protected]
Definition at line 204 of file cpicapfloortermpricesurface.hpp.
template<class Interpolator2D > Matrix QuantLib::InterpolatedCPICapFloorTermPriceSurface< Interpolator2D >::cPriceB_ [mutable, protected]
Definition at line 202 of file cpicapfloortermpricesurface.hpp.
template<class Interpolator2D > Interpolation2D QuantLib::InterpolatedCPICapFloorTermPriceSurface< Interpolator2D >::floorPrice_ [mutable, protected]
Definition at line 204 of file cpicapfloortermpricesurface.hpp.
template<class Interpolator2D > Matrix QuantLib::InterpolatedCPICapFloorTermPriceSurface< Interpolator2D >::fPriceB_ [mutable, protected]
Definition at line 203 of file cpicapfloortermpricesurface.hpp.
template<class Interpolator2D > Interpolator2D QuantLib::InterpolatedCPICapFloorTermPriceSurface< Interpolator2D >::interpolator2d_ [mutable, protected]
Definition at line 205 of file cpicapfloortermpricesurface.hpp.
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/inflation/cpicapfloortermpricesurface.hpp