QuantLib: QuantLib::LocalVolCurve Class Reference
QuantLib::LocalVolCurve Class Reference
Local volatility curve derived from a Black curve.
#include <localvolcurve.hpp>
Public Member Functions
LocalVolCurve (const Handle< BlackVarianceCurve > &curve)
TermStructure interface
const Date & referenceDate () const
the date at which discount = 1.0 and/or variance = 0.0
Calendar calendar () const
the calendar used for reference and/or option date calculation
DayCounter dayCounter () const
the day counter used for date/time conversion
Date maxDate () const
the latest date for which the curve can return values
VolatilityTermStructure interface
Real minStrike () const
the minimum strike for which the term structure can return vols
Real maxStrike () const
the maximum strike for which the term structure can return vols
Visitability
virtual void accept (AcyclicVisitor &)
Protected Member Functions
Volatility localVolImpl (Time, Real) const
Private Attributes
Handle< BlackVarianceCurve > blackVarianceCurve_
Detailed Description
Local volatility curve derived from a Black curve.
Definition at line 33 of file localvolcurve.hpp.
Constructor & Destructor Documentation
QuantLib::LocalVolCurve::LocalVolCurve (const Handle< BlackVarianceCurve > & curve) [inline]
Definition at line 35 of file localvolcurve.hpp.
References blackVarianceCurve_, and QuantLib::Observer::registerWith().
        : LocalVolTermStructure(curve->businessDayConvention(),
                                curve->dayCounter()),
          blackVarianceCurve_(curve) {
            registerWith(blackVarianceCurve_);
        }
Member Function Documentation
void QuantLib::LocalVolCurve::accept (AcyclicVisitor & v) [inline, virtual]
Reimplemented from QuantLib::LocalVolTermStructure.
Definition at line 79 of file localvolcurve.hpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Visitor< T >::visit().
{
        Visitor<LocalVolCurve>* v1 =
            dynamic_cast<Visitor<LocalVolCurve>*>(&v);
        if (v1 != 0)
            v1->visit(*this);
        else
            LocalVolTermStructure::accept(v);
    }
Calendar QuantLib::LocalVolCurve::calendar () const [inline, virtual]
the calendar used for reference and/or option date calculation
Reimplemented from QuantLib::TermStructure.
Definition at line 46 of file localvolcurve.hpp.
References blackVarianceCurve_.
{
            return blackVarianceCurve_->calendar();
        }
DayCounter QuantLib::LocalVolCurve::dayCounter () const [inline, virtual]
the day counter used for date/time conversion
Reimplemented from QuantLib::TermStructure.
Definition at line 49 of file localvolcurve.hpp.
References blackVarianceCurve_.
{
            return blackVarianceCurve_->dayCounter();
        }
Volatility QuantLib::LocalVolCurve::localVolImpl (Time t, Real dummy) const [inline, protected, virtual]
The relation
\[ \int_0^T \sigma_L^2(t)dt = \sigma_B^2 T \]
holds, where \(\sigma_L(t) \) is the local volatility at time \(t \) and \(\sigma_B(T) \) is the Black volatility for maturity \(T \). From the above, the formula
\[ \sigma_L(t) = \sqrt{\frac{\mathrm{d}}{\mathrm{d}t}\sigma_B^2(t)t} \]
can be deduced which is here implemented.
Implements QuantLib::LocalVolTermStructure.
Definition at line 100 of file localvolcurve.hpp.
References blackVarianceCurve_, and QuantLib::anonymous_namespace{yieldtermstructure.cpp}::dt.
{
        Time dt = (1.0/365.0);
        Real var1 = blackVarianceCurve_->blackVariance(t, dummy, true);
        Real var2 = blackVarianceCurve_->blackVariance(t+dt, dummy, true);
        Real derivative = (var2-var1)/dt;
        return std::sqrt(derivative);
    }
Date QuantLib::LocalVolCurve::maxDate () const [inline, virtual]
the latest date for which the curve can return values
Implements QuantLib::TermStructure.
Definition at line 52 of file localvolcurve.hpp.
References blackVarianceCurve_.
{
            return blackVarianceCurve_->maxDate();
        }
Real QuantLib::LocalVolCurve::maxStrike () const [inline, virtual]
the maximum strike for which the term structure can return vols
Implements QuantLib::VolatilityTermStructure.
Definition at line 61 of file localvolcurve.hpp.
References QL_MAX_REAL.
{
            return QL_MAX_REAL;
        }
Real QuantLib::LocalVolCurve::minStrike () const [inline, virtual]
the minimum strike for which the term structure can return vols
Implements QuantLib::VolatilityTermStructure.
Definition at line 58 of file localvolcurve.hpp.
References QL_MIN_REAL.
{
            return QL_MIN_REAL;
        }
const Date& QuantLib::LocalVolCurve::referenceDate () const [inline, virtual]
the date at which discount = 1.0 and/or variance = 0.0
Reimplemented from QuantLib::TermStructure.
Definition at line 43 of file localvolcurve.hpp.
References blackVarianceCurve_.
{
            return blackVarianceCurve_->referenceDate();
        }
Member Data Documentation
Handle<BlackVarianceCurve> QuantLib::LocalVolCurve::blackVarianceCurve_ [private]
Definition at line 72 of file localvolcurve.hpp.
Referenced by calendar(), dayCounter(), LocalVolCurve(), localVolImpl(), maxDate(), and referenceDate().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/equityfx/localvolcurve.hpp