QuantLib: QuantLib::AbcdFunction Class Reference
QuantLib::AbcdFunction Class Reference
Abcd functional form for instantaneous volatility
#include <abcd.hpp>
Public Member Functions
AbcdFunction (Real a=-0.06, Real b=0.17, Real c=0.54, Real d=0.17)
Real operator() (Time u) const
volatility function value at time u:
\[ f(u) \]
Real maximumLocation () const
time at which the volatility function reaches maximum (if any)
Real maximumVolatility () const
maximum value of the volatility function
Real shortTermVolatility () const
volatility function value at time 0:
\[ f(0) \]
Real longTermVolatility () const
volatility function value at time +inf:
\[ f(\inf) \]
Real covariance (Time t, Time T, Time S) const
Real covariance (Time t1, Time t2, Time T, Time S) const
Real volatility (Time tMin, Time tMax, Time T) const
Real variance (Time tMin, Time tMax, Time T) const
Real instantaneousVolatility (Time t, Time T) const
Real instantaneousVariance (Time t, Time T) const
Real instantaneousCovariance (Time u, Time T, Time S) const
Real primitive (Time t, Time T, Time S) const
Real a () const
Real b () const
Real c () const
Real d () const
Private Attributes
Real a_
Real b_
Real c_
Real d_
Detailed Description
Abcd functional form for instantaneous volatility
\[ f(T-t) = [ a + b(T-t) ] e^{-c(T-t)} + d \]
following Rebonato's notation.
Definition at line 45 of file abcd.hpp.
Constructor & Destructor Documentation
QuantLib::AbcdFunction::AbcdFunction (Real a = -0.06, Real b = 0.17, Real c = 0.54, Real d = 0.17)
Definition at line 27 of file abcd.cpp.
References QuantLib::validateAbcdParameters().
    : a_(a), b_(b), c_(c), d_(d) {
        validateAbcdParameters(a, b, c, d);
    }
Member Function Documentation
Real QuantLib::AbcdFunction::a () const [inline]
Inspectors
Definition at line 107 of file abcd.hpp.
References a_.
{ return a_; }
Real QuantLib::AbcdFunction::b () const [inline]
Definition at line 108 of file abcd.hpp.
References b_.
{ return b_; }
Real QuantLib::AbcdFunction::c () const [inline]
Definition at line 109 of file abcd.hpp.
References c_.
{ return c_; }
Real QuantLib::AbcdFunction::covariance (Time t, Time T, Time S) const
instantaneous covariance function at time t between T-fixing and S-fixing rates
\[ f(T-t)f(S-t) \]
Definition at line 69 of file abcd.cpp.
References anonymous_namespace{quantlibbenchmark.cpp}::t.
Referenced by QuantLib::AbcdVol::AbcdVol(), and variance().
{
        return (*this)(T-t) * (*this)(S-t);
    }
Real QuantLib::AbcdFunction::covariance (Time t1, Time t2, Time T, Time S) const
integral of the instantaneous covariance function between time t1 and t2 for T-fixing and S-fixing rates
\[ \int_{t1}^{t2} f(T-t)f(S-t)dt \]
Definition at line 73 of file abcd.cpp.
References primitive(), and QL_REQUIRE.
{
        QL_REQUIRE(t1<=t2,
                   "integrations bounds (" << t1 <<
                   "," << t2 << ") are in reverse order");
        Time cutOff = std::min(S,T);
        if (t1>=cutOff) {
            return 0.0;
        } else {
            cutOff = std::min(t2, cutOff);
            return primitive(cutOff, T, S) - primitive(t1, T, S);
        }
    }
Real QuantLib::AbcdFunction::d () const [inline]
Definition at line 110 of file abcd.hpp.
References d_.
{ return d_; }
Real QuantLib::AbcdFunction::instantaneousCovariance (Time u, Time T, Time S) const
instantaneous covariance at time t between T and S fixing rates:
\[ f(T-u)f(S-u) \]
Definition at line 94 of file abcd.cpp.
Referenced by instantaneousVariance().
{
        return (*this)(T-u)*(*this)(S-u);
    }
Real QuantLib::AbcdFunction::instantaneousVariance (Time t, Time T) const
instantaneous variance at time t of T-fixing rate:
\[ f(T-t)f(T-t) \]
Definition at line 91 of file abcd.cpp.
References instantaneousCovariance().
Referenced by instantaneousVolatility().
{
        return instantaneousCovariance(u, T, T);
    }
Real QuantLib::AbcdFunction::instantaneousVolatility (Time t, Time T) const
instantaneous volatility at time t of the T-fixing rate:
\[ f(T-t) \]
Definition at line 87 of file abcd.cpp.
References instantaneousVariance().
Referenced by volatility().
{
        return std::sqrt(instantaneousVariance(u, T));
    }
Real QuantLib::AbcdFunction::longTermVolatility () const [inline]
volatility function value at time +inf:
\[ f(\inf) \]
Definition at line 66 of file abcd.hpp.
References d_.
{ return d_; }
Real QuantLib::AbcdFunction::maximumLocation () const
time at which the volatility function reaches maximum (if any)
Definition at line 36 of file abcd.cpp.
References a_, b_, and c_.
{
        if (b_<=0) {
            return 0.0;
        } else {
            if((b_-c_*a_)/(c_*b_)>0) {
                return (b_-c_*a_)/(c_*b_);
            } else
                return 0.0;
        }
    }
Real QuantLib::AbcdFunction::maximumVolatility () const
maximum value of the volatility function
Definition at line 47 of file abcd.cpp.
References a_, b_, c_, d_, and shortTermVolatility().
{
        if (b_<=0) {
            return shortTermVolatility();
        } else {
            if ((b_-c_*a_)/(c_*b_) > 0.0) {
                return b_/c_*std::exp(-1.0 +c_*a_/b_) + d_;
            } else
                return shortTermVolatility();
        }
    }
Real QuantLib::AbcdFunction::operator() (Time u) const
volatility function value at time u:
\[ f(u) \]
Definition at line 32 of file abcd.cpp.
References a_, b_, c_, and d_.
{
        return u<0 ? 0.0 : (a_ + b_*u)*std::exp(-c_*u) + d_;
    }
Real QuantLib::AbcdFunction::primitive (Time t, Time T, Time S) const
indefinite integral of the instantaneous covariance function at time t between T-fixing and S-fixing rates
\[ \int f(T-t)f(S-t)dt \]
Definition at line 99 of file abcd.cpp.
References a_, b_, c_, and d_.
Referenced by covariance().
{
        if (T<t || S<t) return 0.0;
        Real k1=std::exp(c_*t), k2=std::exp(c_*S), k3=std::exp(c_*T);
        return (b_*b_*(-1 - 2*c_*c_*S*T - c_*(S + T)
                     + k1*k1*(1 + c_*(S + T - 2*t) + 2*c_*c_*(S - t)*(T - t)))
                + 2*c_*c_*(2*d_*a_*(k2 + k3)*(k1 - 1)
                         +a_*a_*(k1*k1 - 1)+2*c_*d_*d_*k2*k3*t)
                + 2*b_*c_*(a_*(-1 - c_*(S + T) + k1*k1*(1 + c_*(S + T - 2*t)))
                         -2*d_*(k3*(1 + c_*S) + k2*(1 + c_*T)
                               - k1*k3*(1 + c_*(S - t))
                               - k1*k2*(1 + c_*(T - t)))
                         )
                ) / (4*c_*c_*c_*k2*k3);
    }
Real QuantLib::AbcdFunction::shortTermVolatility () const [inline]
volatility function value at time 0:
\[ f(0) \]
Definition at line 63 of file abcd.hpp.
References a_, and d_.
Referenced by maximumVolatility().
{ return a_+d_; }
Real QuantLib::AbcdFunction::variance (Time tMin, Time tMax, Time T) const
variance between tMin and tMax of T-fixing rate:
\[ \frac{\int_{tMin}^{tMax} f^2(T-u)du}{tMax-tMin} \]
Definition at line 65 of file abcd.cpp.
References covariance().
Referenced by volatility().
{
        return covariance(tMin, tMax, T, T);
    }
Real QuantLib::AbcdFunction::volatility (Time tMin, Time tMax, Time T) const
average volatility in [tMin,tMax] of T-fixing rate:
\[ \sqrt{ \frac{\int_{tMin}^{tMax} f^2(T-u)du}{tMax-tMin} } \]
Definition at line 58 of file abcd.cpp.
References instantaneousVolatility(), QL_REQUIRE, and variance().
Referenced by QuantLib::abcdBlackVolatility(), and MarketModelTest::testAbcdVolatilityFit().
{
        if (tMax==tMin)
            return instantaneousVolatility(tMax, T);
        QL_REQUIRE(tMax>tMin, "tMax must be > tMin");
        return std::sqrt(variance(tMin, tMax, T)/(tMax-tMin));
    }
Member Data Documentation
Real QuantLib::AbcdFunction::a_ [private]
Definition at line 113 of file abcd.hpp.
Referenced by a(), maximumLocation(), maximumVolatility(), operator()(), primitive(), and shortTermVolatility().
Real QuantLib::AbcdFunction::b_ [private]
Definition at line 113 of file abcd.hpp.
Referenced by b(), maximumLocation(), maximumVolatility(), operator()(), and primitive().
Real QuantLib::AbcdFunction::c_ [private]
Definition at line 113 of file abcd.hpp.
Referenced by c(), maximumLocation(), maximumVolatility(), operator()(), and primitive().
Real QuantLib::AbcdFunction::d_ [private]
Definition at line 113 of file abcd.hpp.
Referenced by d(), longTermVolatility(), maximumVolatility(), operator()(), primitive(), and shortTermVolatility().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/abcd.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/abcd.cpp