QuantLib: QuantLib::InterpolatedSmileSection< Interpolator > Class Template Reference
QuantLib::InterpolatedSmileSection< Interpolator > Class Template Reference
#include <interpolatedsmilesection.hpp>
Public Member Functions
InterpolatedSmileSection (Time expiryTime, const std::vector< Rate > &strikes, const std::vector< Handle< Quote > > &stdDevHandles, const Handle< Quote > &atmLevel, const Interpolator &interpolator=Interpolator(), const DayCounter &dc=Actual365Fixed())
InterpolatedSmileSection (Time expiryTime, const std::vector< Rate > &strikes, const std::vector< Real > &stdDevs, Real atmLevel, const Interpolator &interpolator=Interpolator(), const DayCounter &dc=Actual365Fixed())
InterpolatedSmileSection (const Date &d, const std::vector< Rate > &strikes, const std::vector< Handle< Quote > > &stdDevHandles, const Handle< Quote > &atmLevel, const DayCounter &dc=Actual365Fixed(), const Interpolator &interpolator=Interpolator(), const Date &referenceDate=Date())
InterpolatedSmileSection (const Date &d, const std::vector< Rate > &strikes, const std::vector< Real > &stdDevs, Real atmLevel, const DayCounter &dc=Actual365Fixed(), const Interpolator &interpolator=Interpolator(), const Date &referenceDate=Date())
void performCalculations () const
Real varianceImpl (Rate strike) const
Volatility volatilityImpl (Rate strike) const
Real minStrike () const
Real maxStrike () const
virtual Real atmLevel () const
void update ()
Private Attributes
Real exerciseTimeSquareRoot_
std::vector< Rate > strikes_
std::vector< Handle< Quote > > stdDevHandles_
Handle< Quote > atmLevel_
std::vector< Volatility > vols_
Interpolation interpolation_
Detailed Description
template<class Interpolator>
class QuantLib::InterpolatedSmileSection< Interpolator >
Definition at line 37 of file interpolatedsmilesection.hpp.
Constructor & Destructor Documentation
template<class Interpolator > QuantLib::InterpolatedSmileSection< Interpolator >::InterpolatedSmileSection (Time expiryTime, const std::vector< Rate > & strikes, const std::vector< Handle< Quote > > & stdDevHandles, const Handle< Quote > & atmLevel, const Interpolator & interpolator = Interpolator(), const DayCounter & dc = Actual365Fixed())
Definition at line 89 of file interpolatedsmilesection.hpp.
References QuantLib::InterpolatedSmileSection< Interpolator >::atmLevel_, QuantLib::InterpolatedSmileSection< Interpolator >::interpolation_, QuantLib::Observer::registerWith(), QuantLib::InterpolatedSmileSection< Interpolator >::stdDevHandles_, QuantLib::InterpolatedSmileSection< Interpolator >::strikes_, and QuantLib::InterpolatedSmileSection< Interpolator >::vols_.
    : SmileSection(timeToExpiry, dc),
      exerciseTimeSquareRoot_(std::sqrt(exerciseTime())), strikes_(strikes),
      stdDevHandles_(stdDevHandles), atmLevel_(atmLevel),
      vols_(stdDevHandles.size())
    {
        for (Size i=0; i<stdDevHandles_.size(); ++i)
            LazyObject::registerWith(stdDevHandles_[i]);
        LazyObject::registerWith(atmLevel_);
        // check strikes!!!!!!!!!!!!!!!!!!!!
        interpolation_ = interpolator.interpolate(strikes_.begin(),
                                                  strikes_.end(),
                                                  vols_.begin());
    }
template<class Interpolator > QuantLib::InterpolatedSmileSection< Interpolator >::InterpolatedSmileSection (Time expiryTime, const std::vector< Rate > & strikes, const std::vector< Real > & stdDevs, Real atmLevel, const Interpolator & interpolator = Interpolator(), const DayCounter & dc = Actual365Fixed())
Definition at line 111 of file interpolatedsmilesection.hpp.
References QuantLib::InterpolatedSmileSection< Interpolator >::atmLevel_, QuantLib::InterpolatedSmileSection< Interpolator >::interpolation_, QuantLib::InterpolatedSmileSection< Interpolator >::stdDevHandles_, QuantLib::InterpolatedSmileSection< Interpolator >::strikes_, and QuantLib::InterpolatedSmileSection< Interpolator >::vols_.
    : SmileSection(timeToExpiry, dc),
      exerciseTimeSquareRoot_(std::sqrt(exerciseTime())), strikes_(strikes),
      stdDevHandles_(stdDevs.size()), vols_(stdDevs.size())
    {
        // fill dummy handles to allow generic handle-based
        // computations later on
        for (Size i=0; i<stdDevs.size(); ++i)
            stdDevHandles_[i] = Handle<Quote>(boost::shared_ptr<Quote>(new
                SimpleQuote(stdDevs[i])));
        atmLevel_ = Handle<Quote>
           (boost::shared_ptr<Quote>(new SimpleQuote(atmLevel)));
        // check strikes!!!!!!!!!!!!!!!!!!!!
        interpolation_ = interpolator.interpolate(strikes_.begin(),
                                                  strikes_.end(),
                                                  vols_.begin());
    }
template<class Interpolator > QuantLib::InterpolatedSmileSection< Interpolator >::InterpolatedSmileSection (const Date & d, const std::vector< Rate > & strikes, const std::vector< Handle< Quote > > & stdDevHandles, const Handle< Quote > & atmLevel, const DayCounter & dc = Actual365Fixed(), const Interpolator & interpolator = Interpolator(), const Date & referenceDate = Date())
Definition at line 136 of file interpolatedsmilesection.hpp.
References QuantLib::InterpolatedSmileSection< Interpolator >::atmLevel_, QuantLib::InterpolatedSmileSection< Interpolator >::interpolation_, QuantLib::Observer::registerWith(), QuantLib::InterpolatedSmileSection< Interpolator >::stdDevHandles_, QuantLib::InterpolatedSmileSection< Interpolator >::strikes_, and QuantLib::InterpolatedSmileSection< Interpolator >::vols_.
    : SmileSection(d, dc, referenceDate),
      exerciseTimeSquareRoot_(std::sqrt(exerciseTime())), strikes_(strikes),
      stdDevHandles_(stdDevHandles), atmLevel_(atmLevel), vols_(stdDevHandles.size())
    {
        for (Size i=0; i<stdDevHandles_.size(); ++i)
            LazyObject::registerWith(stdDevHandles_[i]);
        LazyObject::registerWith(atmLevel_);
        // check strikes!!!!!!!!!!!!!!!!!!!!
        interpolation_ = interpolator.interpolate(strikes_.begin(),
                                                  strikes_.end(),
                                                  vols_.begin());
    }
template<class Interpolator > QuantLib::InterpolatedSmileSection< Interpolator >::InterpolatedSmileSection (const Date & d, const std::vector< Rate > & strikes, const std::vector< Real > & stdDevs, Real atmLevel, const DayCounter & dc = Actual365Fixed(), const Interpolator & interpolator = Interpolator(), const Date & referenceDate = Date())
Definition at line 158 of file interpolatedsmilesection.hpp.
References QuantLib::InterpolatedSmileSection< Interpolator >::atmLevel_, QuantLib::InterpolatedSmileSection< Interpolator >::interpolation_, QuantLib::InterpolatedSmileSection< Interpolator >::stdDevHandles_, QuantLib::InterpolatedSmileSection< Interpolator >::strikes_, and QuantLib::InterpolatedSmileSection< Interpolator >::vols_.
    : SmileSection(d, dc, referenceDate),
      exerciseTimeSquareRoot_(std::sqrt(exerciseTime())), strikes_(strikes),
      stdDevHandles_(stdDevs.size()), vols_(stdDevs.size())
    {
        //fill dummy handles to allow generic handle-based
        // computations later on
        for (Size i=0; i<stdDevs.size(); ++i)
            stdDevHandles_[i] = Handle<Quote>(boost::shared_ptr<Quote>(new
                SimpleQuote(stdDevs[i])));
        atmLevel_ = Handle<Quote>
           (boost::shared_ptr<Quote>(new SimpleQuote(atmLevel)));
        // check strikes!!!!!!!!!!!!!!!!!!!!
        interpolation_ = interpolator.interpolate(strikes_.begin(),
                                                  strikes_.end(),
                                                  vols_.begin());
    }
Member Function Documentation
template<class Interpolator > virtual Real QuantLib::InterpolatedSmileSection< Interpolator >::atmLevel () const [inline, virtual]
Implements QuantLib::SmileSection.
Definition at line 76 of file interpolatedsmilesection.hpp.
References QuantLib::InterpolatedSmileSection< Interpolator >::atmLevel_.
{ return atmLevel_->value(); }
template<class Interpolator > Real QuantLib::InterpolatedSmileSection< Interpolator >::maxStrike () const [inline, virtual]
Implements QuantLib::SmileSection.
Definition at line 75 of file interpolatedsmilesection.hpp.
References QuantLib::InterpolatedSmileSection< Interpolator >::strikes_.
{ return strikes_.back(); }
template<class Interpolator > Real QuantLib::InterpolatedSmileSection< Interpolator >::minStrike () const [inline, virtual]
Implements QuantLib::SmileSection.
Definition at line 74 of file interpolatedsmilesection.hpp.
References QuantLib::InterpolatedSmileSection< Interpolator >::strikes_.
{ return strikes_.front(); }
template<class Interpolator > void QuantLib::InterpolatedSmileSection< Interpolator >::performCalculations () const [inline, virtual]
This method must implement any calculations which must be (re)done in order to calculate the desired results.
Implements QuantLib::LazyObject.
Definition at line 184 of file interpolatedsmilesection.hpp.
{
        for (Size i=0; i<stdDevHandles_.size(); ++i)
            vols_[i] = stdDevHandles_[i]->value()/exerciseTimeSquareRoot_;
        interpolation_.update();
    }
template<class Interpolator > void QuantLib::InterpolatedSmileSection< Interpolator >::update () [virtual]
This method must be implemented in derived classes. An instance of Observer does not call this method directly: instead, it will be called by the observables the instance registered with when they need to notify any changes.
Reimplemented from QuantLib::LazyObject.
Definition at line 206 of file interpolatedsmilesection.hpp.
References QuantLib::LazyObject::update(), and QuantLib::SmileSection::update().
{
        LazyObject::update();
        SmileSection::update();
    }
template<class Interpolator > Real QuantLib::InterpolatedSmileSection< Interpolator >::varianceImpl (Rate strike) const [virtual]
Reimplemented from QuantLib::SmileSection.
Definition at line 193 of file interpolatedsmilesection.hpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v().
{
        calculate();
        Real v = interpolation_(strike, true);
        return v*v*exerciseTime();
    }
template<class Interpolator > Real QuantLib::InterpolatedSmileSection< Interpolator >::volatilityImpl (Rate strike) const [virtual]
Implements QuantLib::SmileSection.
Definition at line 200 of file interpolatedsmilesection.hpp.
{
        calculate();
        return interpolation_(strike, true);
    }
Member Data Documentation
template<class Interpolator > Handle<Quote> QuantLib::InterpolatedSmileSection< Interpolator >::atmLevel_ [private]
Definition at line 82 of file interpolatedsmilesection.hpp.
Referenced by QuantLib::InterpolatedSmileSection< Interpolator >::atmLevel(), and QuantLib::InterpolatedSmileSection< Interpolator >::InterpolatedSmileSection().
template<class Interpolator > Real QuantLib::InterpolatedSmileSection< Interpolator >::exerciseTimeSquareRoot_ [private]
Definition at line 79 of file interpolatedsmilesection.hpp.
template<class Interpolator > Interpolation QuantLib::InterpolatedSmileSection< Interpolator >::interpolation_ [mutable, private]
Definition at line 84 of file interpolatedsmilesection.hpp.
Referenced by QuantLib::InterpolatedSmileSection< Interpolator >::InterpolatedSmileSection().
template<class Interpolator > std::vector<Handle<Quote> > QuantLib::InterpolatedSmileSection< Interpolator >::stdDevHandles_ [private]
Definition at line 81 of file interpolatedsmilesection.hpp.
Referenced by QuantLib::InterpolatedSmileSection< Interpolator >::InterpolatedSmileSection().
template<class Interpolator > std::vector<Rate> QuantLib::InterpolatedSmileSection< Interpolator >::strikes_ [private]
Definition at line 80 of file interpolatedsmilesection.hpp.
Referenced by QuantLib::InterpolatedSmileSection< Interpolator >::InterpolatedSmileSection(), QuantLib::InterpolatedSmileSection< Interpolator >::maxStrike(), and QuantLib::InterpolatedSmileSection< Interpolator >::minStrike().
template<class Interpolator > std::vector<Volatility> QuantLib::InterpolatedSmileSection< Interpolator >::vols_ [mutable, private]
Definition at line 83 of file interpolatedsmilesection.hpp.
Referenced by QuantLib::InterpolatedSmileSection< Interpolator >::InterpolatedSmileSection().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/interpolatedsmilesection.hpp