QuantLib: QuantLib::Fdm2DimSolver Class Reference
QuantLib::Fdm2DimSolver Class Reference
#include <fdm2dimsolver.hpp>
Public Member Functions
Fdm2DimSolver (const FdmSolverDesc &solverDesc, const FdmSchemeDesc &schemeDesc, const boost::shared_ptr< FdmLinearOpComposite > &op)
Real interpolateAt (Real x, Real y) const
Real thetaAt (Real x, Real y) const
Real derivativeX (Real x, Real y) const
Real derivativeY (Real x, Real y) const
Real derivativeXX (Real x, Real y) const
Real derivativeYY (Real x, Real y) const
Real derivativeXY (Real x, Real y) const
Protected Member Functions
void performCalculations () const
Private Attributes
const FdmSolverDesc solverDesc_
const FdmSchemeDesc schemeDesc_
const boost::shared_ptr
< FdmLinearOpComposite > op_
const boost::shared_ptr
< FdmSnapshotCondition > thetaCondition_
const boost::shared_ptr
< FdmStepConditionComposite > conditions_
std::vector< Real > x_
std::vector< Real > y_
std::vector< Real > initialValues_
Matrix resultValues_
boost::shared_ptr< BicubicSpline > interpolation_
Detailed Description
Definition at line 38 of file fdm2dimsolver.hpp.
Constructor & Destructor Documentation
QuantLib::Fdm2DimSolver::Fdm2DimSolver (const FdmSolverDesc & solverDesc, const FdmSchemeDesc & schemeDesc, const boost::shared_ptr< FdmLinearOpComposite > & op)
Definition at line 31 of file fdm2dimsolver.cpp.
References QuantLib::FdmSolverDesc::calculator, initialValues_, QuantLib::FdmSolverDesc::maturity, QuantLib::FdmSolverDesc::mesher, solverDesc_, x_, and y_.
    : solverDesc_(solverDesc),
      schemeDesc_(schemeDesc),
      op_(op),
      thetaCondition_(new FdmSnapshotCondition(
        0.99*std::min(1.0/365.0,
           solverDesc.condition->stoppingTimes().empty()
                    ? solverDesc.maturity
                    : solverDesc.condition->stoppingTimes().front()))),
      conditions_(FdmStepConditionComposite::joinConditions(thetaCondition_,
                                                         solverDesc.condition)),
      initialValues_(solverDesc.mesher->layout()->size()),
      resultValues_ (solverDesc.mesher->layout()->dim()[1],
                     solverDesc.mesher->layout()->dim()[0]) {
        const boost::shared_ptr<FdmMesher> mesher = solverDesc.mesher;
        const boost::shared_ptr<FdmLinearOpLayout> layout = mesher->layout();
        x_.reserve(layout->dim()[0]);
        y_.reserve(layout->dim()[1]);
        const FdmLinearOpIterator endIter = layout->end();
        for (FdmLinearOpIterator iter = layout->begin(); iter != endIter;
             ++iter) {
            initialValues_[iter.index()]
                 = solverDesc_.calculator->avgInnerValue(iter,
                                                         solverDesc.maturity);
            if (!iter.coordinates()[1]) {
                x_.push_back(mesher->location(iter, 0));
            }
            if (!iter.coordinates()[0]) {
                y_.push_back(mesher->location(iter, 1));
            }
        }
    }
Member Function Documentation
Real QuantLib::Fdm2DimSolver::derivativeX (Real x, Real y) const
Definition at line 108 of file fdm2dimsolver.cpp.
References QuantLib::LazyObject::calculate(), and interpolation_.
{
        calculate();
        return interpolation_->derivativeX(x, y);
    }
Real QuantLib::Fdm2DimSolver::derivativeXX (Real x, Real y) const
Definition at line 118 of file fdm2dimsolver.cpp.
References QuantLib::LazyObject::calculate(), and interpolation_.
{
        calculate();
        return interpolation_->secondDerivativeX(x, y);
    }
Real QuantLib::Fdm2DimSolver::derivativeXY (Real x, Real y) const
Definition at line 128 of file fdm2dimsolver.cpp.
References QuantLib::LazyObject::calculate(), and interpolation_.
{
        calculate();
        return interpolation_->derivativeXY(x, y);
    }
Real QuantLib::Fdm2DimSolver::derivativeY (Real x, Real y) const
Definition at line 113 of file fdm2dimsolver.cpp.
References QuantLib::LazyObject::calculate(), and interpolation_.
{
        calculate();
        return interpolation_->derivativeY(x, y);
    }
Real QuantLib::Fdm2DimSolver::derivativeYY (Real x, Real y) const
Definition at line 123 of file fdm2dimsolver.cpp.
References QuantLib::LazyObject::calculate(), and interpolation_.
{
        calculate();
        return interpolation_->secondDerivativeY(x, y);
    }
Real QuantLib::Fdm2DimSolver::interpolateAt (Real x, Real y) const
Definition at line 87 of file fdm2dimsolver.cpp.
References QuantLib::LazyObject::calculate(), and interpolation_.
Referenced by thetaAt().
{
        calculate();
        return interpolation_->operator()(x, y);
    }
void QuantLib::Fdm2DimSolver::performCalculations () const [protected, virtual]
This method must implement any calculations which must be (re)done in order to calculate the desired results.
Implements QuantLib::LazyObject.
Definition at line 72 of file fdm2dimsolver.cpp.
References QuantLib::FdmSolverDesc::bcSet, QuantLib::Matrix::begin(), conditions_, QuantLib::FdmSolverDesc::dampingSteps, initialValues_, interpolation_, QuantLib::FdmSolverDesc::maturity, op_, resultValues_, QuantLib::FdmBackwardSolver::rollback(), schemeDesc_, solverDesc_, QuantLib::FdmSolverDesc::timeSteps, x_, and y_.
{
        Array rhs(initialValues_.size());
        std::copy(initialValues_.begin(), initialValues_.end(), rhs.begin());
        FdmBackwardSolver(op_, solverDesc_.bcSet, conditions_, schemeDesc_)
            .rollback(rhs, solverDesc_.maturity, 0.0,
                      solverDesc_.timeSteps, solverDesc_.dampingSteps);
        std::copy(rhs.begin(), rhs.end(), resultValues_.begin());
        interpolation_ = boost::shared_ptr<BicubicSpline> (
            new BicubicSpline(x_.begin(), x_.end(),
                              y_.begin(), y_.end(),
                              resultValues_));
    }
Real QuantLib::Fdm2DimSolver::thetaAt (Real x, Real y) const
Definition at line 92 of file fdm2dimsolver.cpp.
References QuantLib::LazyObject::calculate(), QuantLib::Matrix::columns(), conditions_, interpolateAt(), QL_REQUIRE, resultValues_, QuantLib::Matrix::rows(), thetaCondition_, x_, and y_.
{
        QL_REQUIRE(conditions_->stoppingTimes().front() > 0.0,
                   "stopping time at zero-> can't calculate theta");
        calculate();
        Matrix thetaValues(resultValues_.rows(), resultValues_.columns());
        const Array& rhs = thetaCondition_->getValues();
        std::copy(rhs.begin(), rhs.end(), thetaValues.begin());
        return (BicubicSpline(x_.begin(), x_.end(), y_.begin(), y_.end(),
                              thetaValues)(x, y) - interpolateAt(x, y))
              / thetaCondition_->getTime();
    }
Member Data Documentation
const boost::shared_ptr<FdmStepConditionComposite> QuantLib::Fdm2DimSolver::conditions_ [private]
Definition at line 62 of file fdm2dimsolver.hpp.
Referenced by performCalculations(), and thetaAt().
std::vector<Real> QuantLib::Fdm2DimSolver::initialValues_ [private]
Definition at line 64 of file fdm2dimsolver.hpp.
Referenced by Fdm2DimSolver(), and performCalculations().
boost::shared_ptr<BicubicSpline> QuantLib::Fdm2DimSolver::interpolation_ [mutable, private]
Definition at line 66 of file fdm2dimsolver.hpp.
Referenced by derivativeX(), derivativeXX(), derivativeXY(), derivativeY(), derivativeYY(), interpolateAt(), and performCalculations().
const boost::shared_ptr<FdmLinearOpComposite> QuantLib::Fdm2DimSolver::op_ [private]
Definition at line 59 of file fdm2dimsolver.hpp.
Referenced by performCalculations().
Matrix QuantLib::Fdm2DimSolver::resultValues_ [mutable, private]
Definition at line 65 of file fdm2dimsolver.hpp.
Referenced by performCalculations(), and thetaAt().
const FdmSchemeDesc QuantLib::Fdm2DimSolver::schemeDesc_ [private]
Definition at line 58 of file fdm2dimsolver.hpp.
Referenced by performCalculations().
const FdmSolverDesc QuantLib::Fdm2DimSolver::solverDesc_ [private]
Definition at line 57 of file fdm2dimsolver.hpp.
Referenced by Fdm2DimSolver(), and performCalculations().
const boost::shared_ptr<FdmSnapshotCondition> QuantLib::Fdm2DimSolver::thetaCondition_ [private]
Definition at line 61 of file fdm2dimsolver.hpp.
Referenced by thetaAt().
std::vector<Real> QuantLib::Fdm2DimSolver::x_ [private]
Definition at line 64 of file fdm2dimsolver.hpp.
Referenced by Fdm2DimSolver(), performCalculations(), and thetaAt().
std::vector<Real> QuantLib::Fdm2DimSolver::y_ [private]
Definition at line 64 of file fdm2dimsolver.hpp.
Referenced by Fdm2DimSolver(), performCalculations(), and thetaAt().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/solvers/fdm2dimsolver.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/solvers/fdm2dimsolver.cpp