QuantLib: PiecewiseYieldCurveTest Class Reference
PiecewiseYieldCurveTest Class Reference
#include <piecewiseyieldcurve.hpp>
Static Public Member Functions
static void testLogCubicDiscountConsistency ()
static void testLogLinearDiscountConsistency ()
static void testLinearDiscountConsistency ()
static void testLogLinearZeroConsistency ()
static void testLinearZeroConsistency ()
static void testSplineZeroConsistency ()
static void testLinearForwardConsistency ()
static void testFlatForwardConsistency ()
static void testSplineForwardConsistency ()
static void testConvexMonotoneForwardConsistency ()
static void testLocalBootstrapConsistency ()
static void testObservability ()
static void testLiborFixing ()
static void testJpyLibor ()
static void testDiscountCopy ()
static void testForwardCopy ()
static void testZeroCopy ()
static
boost::unit_test_framework::test_suite * suite ()
Detailed Description
Definition at line 28 of file piecewiseyieldcurve.hpp.
Member Function Documentation
test_suite * PiecewiseYieldCurveTest::suite () [static]
Definition at line 911 of file piecewiseyieldcurve.cpp.
References QUANTLIB_TEST_CASE, testConvexMonotoneForwardConsistency(), testDiscountCopy(), testFlatForwardConsistency(), testForwardCopy(), testJpyLibor(), testLiborFixing(), testLinearDiscountConsistency(), testLinearForwardConsistency(), testLinearZeroConsistency(), testLocalBootstrapConsistency(), testLogLinearDiscountConsistency(), testLogLinearZeroConsistency(), testObservability(), testSplineZeroConsistency(), and testZeroCopy().
Referenced by init_unit_test_suite().
{
    test_suite* suite = BOOST_TEST_SUITE("Piecewise yield curve tests");
    //suite->add(QUANTLIB_TEST_CASE(
    //             &PiecewiseYieldCurveTest::testLogCubicDiscountConsistency));
    suite->add(QUANTLIB_TEST_CASE(
                 &PiecewiseYieldCurveTest::testLogLinearDiscountConsistency));
    suite->add(QUANTLIB_TEST_CASE(
                 &PiecewiseYieldCurveTest::testLinearDiscountConsistency));
    #if !defined(QL_USE_INDEXED_COUPON)
    suite->add(QUANTLIB_TEST_CASE(
                 &PiecewiseYieldCurveTest::testLogLinearZeroConsistency));
    #endif
    suite->add(QUANTLIB_TEST_CASE(
                 &PiecewiseYieldCurveTest::testLinearZeroConsistency));
    suite->add(QUANTLIB_TEST_CASE(
                 &PiecewiseYieldCurveTest::testSplineZeroConsistency));
    suite->add(QUANTLIB_TEST_CASE(
                 &PiecewiseYieldCurveTest::testLinearForwardConsistency));
    suite->add(QUANTLIB_TEST_CASE(
                 &PiecewiseYieldCurveTest::testFlatForwardConsistency));
    //suite->add(QUANTLIB_TEST_CASE(
    //             &PiecewiseYieldCurveTest::testSplineForwardConsistency));
    suite->add(QUANTLIB_TEST_CASE(
             &PiecewiseYieldCurveTest::testConvexMonotoneForwardConsistency));
    suite->add(QUANTLIB_TEST_CASE(
             &PiecewiseYieldCurveTest::testLocalBootstrapConsistency));
    suite->add(QUANTLIB_TEST_CASE(&PiecewiseYieldCurveTest::testObservability));
    suite->add(QUANTLIB_TEST_CASE(&PiecewiseYieldCurveTest::testLiborFixing));
    suite->add(QUANTLIB_TEST_CASE(&PiecewiseYieldCurveTest::testJpyLibor));
    suite->add(QUANTLIB_TEST_CASE(&PiecewiseYieldCurveTest::testDiscountCopy));
    suite->add(QUANTLIB_TEST_CASE(&PiecewiseYieldCurveTest::testForwardCopy));
    suite->add(QUANTLIB_TEST_CASE(&PiecewiseYieldCurveTest::testZeroCopy));
    return suite;
}
void PiecewiseYieldCurveTest::testConvexMonotoneForwardConsistency () [static]
Definition at line 617 of file piecewiseyieldcurve.cpp.
References anonymous_namespace{piecewiseyieldcurve.cpp}::testBMACurveConsistency().
Referenced by suite().
{
    BOOST_MESSAGE(
        "Testing consistency of convex monotone forward-rate curve...");
    CommonVars vars;
    testCurveConsistency<ForwardRate,ConvexMonotone,IterativeBootstrap>(vars);
    testBMACurveConsistency<ForwardRate,ConvexMonotone,
                            IterativeBootstrap>(vars);
}
void PiecewiseYieldCurveTest::testDiscountCopy () [static]
Definition at line 887 of file piecewiseyieldcurve.cpp.
Referenced by suite().
{
    BOOST_MESSAGE("Testing copying of discount curve...");
    CommonVars vars;
    testCurveCopy<Discount,LogLinear>(vars);
}
void PiecewiseYieldCurveTest::testFlatForwardConsistency () [static]
Definition at line 587 of file piecewiseyieldcurve.cpp.
Referenced by suite().
{
    BOOST_MESSAGE(
        "Testing consistency of piecewise-flat forward-rate curve...");
    CommonVars vars;
    testCurveConsistency<ForwardRate,BackwardFlat,IterativeBootstrap>(vars);
    testBMACurveConsistency<ForwardRate,BackwardFlat,IterativeBootstrap>(vars);
}
void PiecewiseYieldCurveTest::testForwardCopy () [static]
Definition at line 894 of file piecewiseyieldcurve.cpp.
Referenced by suite().
{
    BOOST_MESSAGE("Testing copying of forward-rate curve...");
    CommonVars vars;
    testCurveCopy<ForwardRate,BackwardFlat>(vars);
}
void PiecewiseYieldCurveTest::testJpyLibor () [static]
Definition at line 770 of file piecewiseyieldcurve.cpp.
References QuantLib::Days, QuantLib::Settings::evaluationDate(), QuantLib::VanillaSwap::fairRate(), QuantLib::Singleton< Settings >::instance(), QuantLib::RelinkableHandle< T >::linkTo(), QuantLib::Months, anonymous_namespace{piecewiseyieldcurve.cpp}::Datum::n, QuantLib::October, anonymous_namespace{piecewiseyieldcurve.cpp}::Datum::rate, QuantLib::io::rate(), QuantLib::swap(), anonymous_namespace{piecewiseyieldcurve.cpp}::CommonVars::today, anonymous_namespace{gaussianquadratures.cpp}::tolerance, anonymous_namespace{piecewiseyieldcurve.cpp}::Datum::units, QuantLib::MakeVanillaSwap::withEffectiveDate(), QuantLib::MakeVanillaSwap::withFixedLegCalendar(), QuantLib::MakeVanillaSwap::withFixedLegConvention(), QuantLib::MakeVanillaSwap::withFixedLegDayCount(), QuantLib::MakeVanillaSwap::withFixedLegTenor(), QuantLib::MakeVanillaSwap::withFixedLegTerminationDateConvention(), and QuantLib::MakeVanillaSwap::withFloatingLegCalendar().
Referenced by suite().
{
    BOOST_MESSAGE(
        "Testing bootstrap over JPY LIBOR swaps...");
    CommonVars vars;
    vars.today = Date(4, October, 2007);
    Settings::instance().evaluationDate() = vars.today;
    vars.calendar = Japan();
    vars.settlement =
        vars.calendar.advance(vars.today,vars.settlementDays,Days);
    // market elements
    vars.rates = std::vector<boost::shared_ptr<SimpleQuote> >(vars.swaps);
    for (Size i=0; i<vars.swaps; i++) {
        vars.rates[i] = boost::shared_ptr<SimpleQuote>(
                                       new SimpleQuote(swapData[i].rate/100));
    }
    // rate helpers
    vars.instruments = std::vector<boost::shared_ptr<RateHelper> >(vars.swaps);
    boost::shared_ptr<IborIndex> index(new JPYLibor(6*Months));
    for (Size i=0; i<vars.swaps; i++) {
        Handle<Quote> r(vars.rates[i]);
        vars.instruments[i] = boost::shared_ptr<RateHelper>(
           new SwapRateHelper(r, swapData[i].n*swapData[i].units,
                              vars.calendar,
                              vars.fixedLegFrequency, vars.fixedLegConvention,
                              vars.fixedLegDayCounter, index));
    }
    vars.termStructure = boost::shared_ptr<YieldTermStructure>(
        new PiecewiseYieldCurve<Discount,LogLinear>(
                                       vars.settlement, vars.instruments,
                                       Actual360(),
                                       1.0e-12));
    RelinkableHandle<YieldTermStructure> curveHandle;
    curveHandle.linkTo(vars.termStructure);
    // check swaps
    boost::shared_ptr<IborIndex> jpylibor6m(new JPYLibor(6*Months,curveHandle));
    for (Size i=0; i<vars.swaps; i++) {
        Period tenor = swapData[i].n*swapData[i].units;
        VanillaSwap swap = MakeVanillaSwap(tenor, jpylibor6m, 0.0)
            .withEffectiveDate(vars.settlement)
            .withFixedLegDayCount(vars.fixedLegDayCounter)
            .withFixedLegTenor(Period(vars.fixedLegFrequency))
            .withFixedLegConvention(vars.fixedLegConvention)
            .withFixedLegTerminationDateConvention(vars.fixedLegConvention)
            .withFixedLegCalendar(vars.calendar)
            .withFloatingLegCalendar(vars.calendar);
        Rate expectedRate = swapData[i].rate/100,
             estimatedRate = swap.fairRate();
        Spread error = std::fabs(expectedRate-estimatedRate);
        Real tolerance = 1.0e-9;
        if (error > tolerance) {
            BOOST_ERROR(swapData[i].n << " year(s) swap:\n"
                        << std::setprecision(8)
                        << "\n estimated rate: " << io::rate(estimatedRate)
                        << "\n expected rate:  " << io::rate(expectedRate)
                        << "\n error:          " << io::rate(error)
                        << "\n tolerance:      " << io::rate(tolerance));
        }
    }
}
void PiecewiseYieldCurveTest::testLiborFixing () [static]
Definition at line 684 of file piecewiseyieldcurve.cpp.
References anonymous_namespace{interpolations.cpp}::f(), QuantLib::VanillaSwap::fairRate(), QuantLib::Flag::isUp(), QuantLib::Flag::lower(), anonymous_namespace{piecewiseyieldcurve.cpp}::Datum::n, anonymous_namespace{piecewiseyieldcurve.cpp}::Datum::rate, QuantLib::io::rate(), QuantLib::Observer::registerWith(), QuantLib::swap(), anonymous_namespace{gaussianquadratures.cpp}::tolerance, anonymous_namespace{piecewiseyieldcurve.cpp}::Datum::units, QuantLib::MakeVanillaSwap::withEffectiveDate(), QuantLib::MakeVanillaSwap::withFixedLegConvention(), QuantLib::MakeVanillaSwap::withFixedLegDayCount(), QuantLib::MakeVanillaSwap::withFixedLegTenor(), and QuantLib::MakeVanillaSwap::withFixedLegTerminationDateConvention().
Referenced by suite().
{
    BOOST_MESSAGE(
        "Testing use of today's LIBOR fixings in swap curve...");
    CommonVars vars;
    std::vector<boost::shared_ptr<RateHelper> > swapHelpers(vars.swaps);
    boost::shared_ptr<IborIndex> euribor6m(new Euribor6M);
    for (Size i=0; i<vars.swaps; i++) {
        Handle<Quote> r(vars.rates[i+vars.deposits]);
        swapHelpers[i] = boost::shared_ptr<RateHelper>(new
            SwapRateHelper(r, Period(swapData[i].n, swapData[i].units),
                           vars.calendar,
                           vars.fixedLegFrequency, vars.fixedLegConvention,
                           vars.fixedLegDayCounter, euribor6m));
    }
    vars.termStructure = boost::shared_ptr<YieldTermStructure>(new
        PiecewiseYieldCurve<Discount,LogLinear>(vars.settlement,
                                                swapHelpers,
                                                Actual360()));
    Handle<YieldTermStructure> curveHandle =
        Handle<YieldTermStructure>(vars.termStructure);
    boost::shared_ptr<IborIndex> index(new Euribor6M(curveHandle));
    for (Size i=0; i<vars.swaps; i++) {
        Period tenor = swapData[i].n*swapData[i].units;
        VanillaSwap swap = MakeVanillaSwap(tenor, index, 0.0)
            .withEffectiveDate(vars.settlement)
            .withFixedLegDayCount(vars.fixedLegDayCounter)
            .withFixedLegTenor(Period(vars.fixedLegFrequency))
            .withFixedLegConvention(vars.fixedLegConvention)
            .withFixedLegTerminationDateConvention(vars.fixedLegConvention);
        Rate expectedRate = swapData[i].rate/100,
             estimatedRate = swap.fairRate();
        Real tolerance = 1.0e-9;
        if (std::fabs(expectedRate-estimatedRate) > tolerance) {
            BOOST_ERROR("before LIBOR fixing:\n"
                        << swapData[i].n << " year(s) swap:\n"
                        << std::setprecision(8)
                        << "    estimated rate: "
                        << io::rate(estimatedRate) << "\n"
                        << "    expected rate:  "
                        << io::rate(expectedRate));
        }
    }
    Flag f;
    f.registerWith(vars.termStructure);
    f.lower();
    index->addFixing(vars.today, 0.0425);
    if (!f.isUp())
        BOOST_ERROR("Observer was not notified of rate fixing");
    for (Size i=0; i<vars.swaps; i++) {
        Period tenor = swapData[i].n*swapData[i].units;
        VanillaSwap swap = MakeVanillaSwap(tenor, index, 0.0)
            .withEffectiveDate(vars.settlement)
            .withFixedLegDayCount(vars.fixedLegDayCounter)
            .withFixedLegTenor(Period(vars.fixedLegFrequency))
            .withFixedLegConvention(vars.fixedLegConvention)
            .withFixedLegTerminationDateConvention(vars.fixedLegConvention);
        Rate expectedRate = swapData[i].rate/100,
             estimatedRate = swap.fairRate();
        Real tolerance = 1.0e-9;
        if (std::fabs(expectedRate-estimatedRate) > tolerance) {
            BOOST_ERROR("after LIBOR fixing:\n"
                        << swapData[i].n << " year(s) swap:\n"
                        << std::setprecision(8)
                        << "    estimated rate: "
                        << io::rate(estimatedRate) << "\n"
                        << "    expected rate:  "
                        << io::rate(expectedRate));
        }
    }
}
void PiecewiseYieldCurveTest::testLinearDiscountConsistency () [static]
Definition at line 524 of file piecewiseyieldcurve.cpp.
Referenced by suite().
{
    BOOST_MESSAGE(
        "Testing consistency of piecewise-linear discount curve...");
    CommonVars vars;
    testCurveConsistency<Discount,Linear,IterativeBootstrap>(vars);
    testBMACurveConsistency<Discount,Linear,IterativeBootstrap>(vars);
}
void PiecewiseYieldCurveTest::testLinearForwardConsistency () [static]
Definition at line 576 of file piecewiseyieldcurve.cpp.
Referenced by suite().
{
    BOOST_MESSAGE(
        "Testing consistency of piecewise-linear forward-rate curve...");
    CommonVars vars;
    testCurveConsistency<ForwardRate,Linear,IterativeBootstrap>(vars);
    testBMACurveConsistency<ForwardRate,Linear,IterativeBootstrap>(vars);
}
void PiecewiseYieldCurveTest::testLinearZeroConsistency () [static]
Definition at line 546 of file piecewiseyieldcurve.cpp.
Referenced by suite().
{
    BOOST_MESSAGE(
        "Testing consistency of piecewise-linear zero-yield curve...");
    CommonVars vars;
    testCurveConsistency<ZeroYield,Linear,IterativeBootstrap>(vars);
    testBMACurveConsistency<ZeroYield,Linear,IterativeBootstrap>(vars);
}
void PiecewiseYieldCurveTest::testLocalBootstrapConsistency () [static]
Definition at line 629 of file piecewiseyieldcurve.cpp.
Referenced by suite().
{
    BOOST_MESSAGE(
        "Testing consistency of local-bootstrap algorithm...");
    CommonVars vars;
    testCurveConsistency<ForwardRate,ConvexMonotone,LocalBootstrap>(
                                              vars, ConvexMonotone(), 1.0e-7);
    testBMACurveConsistency<ForwardRate,ConvexMonotone,LocalBootstrap>(
                                              vars, ConvexMonotone(), 1.0e-7);
}
void PiecewiseYieldCurveTest::testLogCubicDiscountConsistency () [static]
Definition at line 494 of file piecewiseyieldcurve.cpp.
References QuantLib::CubicInterpolation::SecondDerivative, and QuantLib::CubicInterpolation::Spline.
{
    BOOST_MESSAGE(
        "Testing consistency of piecewise-log-cubic discount curve...");
    CommonVars vars;
    testCurveConsistency<Discount,LogCubic,IterativeBootstrap>(
        vars,
        LogCubic(CubicInterpolation::Spline, true,
                 CubicInterpolation::SecondDerivative, 0.0,
                 CubicInterpolation::SecondDerivative, 0.0));
    testBMACurveConsistency<Discount,LogCubic,IterativeBootstrap>(
        vars,
        LogCubic(CubicInterpolation::Spline, true,
                 CubicInterpolation::SecondDerivative, 0.0,
                 CubicInterpolation::SecondDerivative, 0.0));
}
void PiecewiseYieldCurveTest::testLogLinearDiscountConsistency () [static]
Definition at line 513 of file piecewiseyieldcurve.cpp.
Referenced by suite().
{
    BOOST_MESSAGE(
        "Testing consistency of piecewise-log-linear discount curve...");
    CommonVars vars;
    testCurveConsistency<Discount,LogLinear,IterativeBootstrap>(vars);
    testBMACurveConsistency<Discount,LogLinear,IterativeBootstrap>(vars);
}
void PiecewiseYieldCurveTest::testLogLinearZeroConsistency () [static]
Definition at line 535 of file piecewiseyieldcurve.cpp.
Referenced by suite().
{
    BOOST_MESSAGE(
        "Testing consistency of piecewise-log-linear zero-yield curve...");
    CommonVars vars;
    testCurveConsistency<ZeroYield,LogLinear,IterativeBootstrap>(vars);
    testBMACurveConsistency<ZeroYield,LogLinear,IterativeBootstrap>(vars);
}
void PiecewiseYieldCurveTest::testObservability () [static]
Definition at line 641 of file piecewiseyieldcurve.cpp.
References QuantLib::Days, QuantLib::Settings::evaluationDate(), anonymous_namespace{interpolations.cpp}::f(), QuantLib::Singleton< Settings >::instance(), QuantLib::Flag::isUp(), QuantLib::Flag::lower(), QuantLib::Observer::registerWith(), anonymous_namespace{piecewiseyieldcurve.cpp}::CommonVars::termStructure, and QuantLib::DayCounter::yearFraction().
Referenced by suite().
{
    BOOST_MESSAGE("Testing observability of piecewise yield curve...");
    CommonVars vars;
    vars.termStructure = boost::shared_ptr<YieldTermStructure>(
       new PiecewiseYieldCurve<Discount,LogLinear>(vars.settlementDays,
                                                   vars.calendar,
                                                   vars.instruments,
                                                   Actual360()));
    Flag f;
    f.registerWith(vars.termStructure);
    for (Size i=0; i<vars.deposits+vars.swaps; i++) {
        Time testTime =
            Actual360().yearFraction(vars.settlement,
                                     vars.instruments[i]->latestDate());
        DiscountFactor discount = vars.termStructure->discount(testTime);
        f.lower();
        vars.rates[i]->setValue(vars.rates[i]->value()*1.01);
        if (!f.isUp())
            BOOST_FAIL("Observer was not notified of underlying rate change");
        if (vars.termStructure->discount(testTime,true) == discount)
            BOOST_FAIL("rate change did not trigger recalculation");
        vars.rates[i]->setValue(vars.rates[i]->value()/1.01);
    }
    vars.termStructure->maxDate();
    f.lower();
    Settings::instance().evaluationDate() =
        vars.calendar.advance(vars.today,15,Days);
    if (!f.isUp())
        BOOST_FAIL("Observer was not notified of date change");
    f.lower();
    Settings::instance().evaluationDate() = vars.today;
    if (f.isUp())
        BOOST_FAIL("Observer was notified of date change"
                   " without an intervening recalculation");
}
void PiecewiseYieldCurveTest::testSplineForwardConsistency () [static]
Definition at line 598 of file piecewiseyieldcurve.cpp.
References QuantLib::CubicInterpolation::SecondDerivative, and QuantLib::CubicInterpolation::Spline.
{
    BOOST_MESSAGE(
        "Testing consistency of piecewise-cubic forward-rate curve...");
    CommonVars vars;
    testCurveConsistency<ForwardRate,Cubic,IterativeBootstrap>(
                   vars,
                   Cubic(CubicInterpolation::Spline, true,
                         CubicInterpolation::SecondDerivative, 0.0,
                         CubicInterpolation::SecondDerivative, 0.0));
    testBMACurveConsistency<ForwardRate,Cubic,IterativeBootstrap>(
                   vars,
                   Cubic(CubicInterpolation::Spline, true,
                         CubicInterpolation::SecondDerivative, 0.0,
                         CubicInterpolation::SecondDerivative, 0.0));
}
void PiecewiseYieldCurveTest::testSplineZeroConsistency () [static]
Definition at line 557 of file piecewiseyieldcurve.cpp.
References QuantLib::CubicInterpolation::SecondDerivative, and QuantLib::CubicInterpolation::Spline.
Referenced by suite().
{
    BOOST_MESSAGE(
        "Testing consistency of piecewise-cubic zero-yield curve...");
    CommonVars vars;
    testCurveConsistency<ZeroYield,Cubic,IterativeBootstrap>(
                   vars,
                   Cubic(CubicInterpolation::Spline, true,
                         CubicInterpolation::SecondDerivative, 0.0,
                         CubicInterpolation::SecondDerivative, 0.0));
    testBMACurveConsistency<ZeroYield,Cubic,IterativeBootstrap>(
                   vars,
                   Cubic(CubicInterpolation::Spline, true,
                         CubicInterpolation::SecondDerivative, 0.0,
                         CubicInterpolation::SecondDerivative, 0.0));
}
void PiecewiseYieldCurveTest::testZeroCopy () [static]
Definition at line 901 of file piecewiseyieldcurve.cpp.
Referenced by suite().
{
    BOOST_MESSAGE("Testing copying of zero-rate curve...");
    CommonVars vars;
    testCurveCopy<ZeroYield,Linear>(vars);
}
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/piecewiseyieldcurve.hpp
/home/deriversatile/QuantLib/QuantLibQt/test-suite/piecewiseyieldcurve.cpp