QuantLib: QuantLib::MarketModelEvolver Class Reference
QuantLib::MarketModelEvolver Class Reference
Market-model evolver.
#include <evolver.hpp>
Public Member Functions
virtual ~MarketModelEvolver ()
virtual const std::vector< Size > & numeraires () const =0
virtual Real startNewPath ()=0
virtual Real advanceStep ()=0
virtual Size currentStep () const =0
virtual const CurveState & currentState () const =0
virtual void setInitialState (const CurveState &)=0
Detailed Description
Market-model evolver.
Abstract base class. The evolver does the actual gritty work of evolving the forward rates from one time to the next.
Definition at line 35 of file evolver.hpp.
Constructor & Destructor Documentation
virtual QuantLib::MarketModelEvolver::~MarketModelEvolver () [inline, virtual]
Definition at line 37 of file evolver.hpp.
{}
Member Function Documentation
virtual Real QuantLib::MarketModelEvolver::advanceStep () [pure virtual]
Implemented in QuantLib::LogNormalFwdRateEulerConstrained, QuantLib::SVDDFwdRatePc, QuantLib::LogNormalCmSwapRatePc, QuantLib::LogNormalCotSwapRatePc, QuantLib::LogNormalFwdRateEuler, QuantLib::LogNormalFwdRateIpc, QuantLib::LogNormalFwdRatePc, QuantLib::NormalFwdRatePc, QuantLib::LogNormalFwdRateBalland, and QuantLib::LogNormalFwdRateiBalland.
Referenced by QuantLib::collectNodeData(), and QuantLib::ProxyGreekEngine::singleEvolverValues().
virtual const CurveState& QuantLib::MarketModelEvolver::currentState () const [pure virtual]
Implemented in QuantLib::LogNormalFwdRateEulerConstrained, QuantLib::SVDDFwdRatePc, QuantLib::LogNormalCmSwapRatePc, QuantLib::LogNormalCotSwapRatePc, QuantLib::LogNormalFwdRateEuler, QuantLib::LogNormalFwdRateIpc, QuantLib::LogNormalFwdRatePc, QuantLib::NormalFwdRatePc, QuantLib::LogNormalFwdRateBalland, and QuantLib::LogNormalFwdRateiBalland.
Referenced by QuantLib::collectNodeData(), and QuantLib::ProxyGreekEngine::singleEvolverValues().
virtual Size QuantLib::MarketModelEvolver::currentStep () const [pure virtual]
Implemented in QuantLib::LogNormalFwdRateEulerConstrained, QuantLib::SVDDFwdRatePc, QuantLib::LogNormalCmSwapRatePc, QuantLib::LogNormalCotSwapRatePc, QuantLib::LogNormalFwdRateEuler, QuantLib::LogNormalFwdRateIpc, QuantLib::LogNormalFwdRatePc, QuantLib::NormalFwdRatePc, QuantLib::LogNormalFwdRateBalland, and QuantLib::LogNormalFwdRateiBalland.
Referenced by QuantLib::collectNodeData(), and QuantLib::ProxyGreekEngine::singleEvolverValues().
virtual const std::vector<Size>& QuantLib::MarketModelEvolver::numeraires () const [pure virtual]
Implemented in QuantLib::LogNormalFwdRateEulerConstrained, QuantLib::SVDDFwdRatePc, QuantLib::LogNormalCmSwapRatePc, QuantLib::LogNormalCotSwapRatePc, QuantLib::LogNormalFwdRateEuler, QuantLib::LogNormalFwdRateIpc, QuantLib::LogNormalFwdRatePc, QuantLib::NormalFwdRatePc, QuantLib::LogNormalFwdRateBalland, and QuantLib::LogNormalFwdRateiBalland.
Referenced by QuantLib::collectNodeData(), and QuantLib::ProxyGreekEngine::singleEvolverValues().
virtual void QuantLib::MarketModelEvolver::setInitialState (const CurveState &) [pure virtual]
Implemented in QuantLib::LogNormalFwdRateEulerConstrained, QuantLib::SVDDFwdRatePc, QuantLib::LogNormalCmSwapRatePc, QuantLib::LogNormalCotSwapRatePc, QuantLib::LogNormalFwdRateEuler, QuantLib::LogNormalFwdRateIpc, QuantLib::LogNormalFwdRatePc, QuantLib::NormalFwdRatePc, QuantLib::LogNormalFwdRateBalland, and QuantLib::LogNormalFwdRateiBalland.
virtual Real QuantLib::MarketModelEvolver::startNewPath () [pure virtual]
Implemented in QuantLib::LogNormalFwdRateEulerConstrained, QuantLib::SVDDFwdRatePc, QuantLib::LogNormalCmSwapRatePc, QuantLib::LogNormalCotSwapRatePc, QuantLib::LogNormalFwdRateEuler, QuantLib::LogNormalFwdRateIpc, QuantLib::LogNormalFwdRatePc, QuantLib::NormalFwdRatePc, QuantLib::LogNormalFwdRateBalland, and QuantLib::LogNormalFwdRateiBalland.
Referenced by QuantLib::collectNodeData(), and QuantLib::ProxyGreekEngine::singleEvolverValues().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/evolver.hpp