QuantLib: QuantLib::FuturesRateHelper Class Reference
QuantLib::FuturesRateHelper Class Reference
Rate helper for bootstrapping over IborIndex futures prices.
#include <ratehelpers.hpp>
Public Member Functions
FuturesRateHelper (const Handle< Quote > &price, const Date &immDate, Natural lengthInMonths, const Calendar &calendar, BusinessDayConvention convention, bool endOfMonth, const DayCounter &dayCounter, const Handle< Quote > &convexityAdjustment=Handle< Quote >())
FuturesRateHelper (Real price, const Date &immDate, Natural lengthInMonths, const Calendar &calendar, BusinessDayConvention convention, bool endOfMonth, const DayCounter &dayCounter, Rate convexityAdjustment=0.0)
FuturesRateHelper (const Handle< Quote > &price, const Date &immStartDate, const Date &endDate, const DayCounter &dayCounter, const Handle< Quote > &convexityAdjustment=Handle< Quote >())
FuturesRateHelper (Real price, const Date &immStartDate, const Date &endDate, const DayCounter &dayCounter, Rate convexityAdjustment=0.0)
FuturesRateHelper (const Handle< Quote > &price, const Date &immDate, const boost::shared_ptr< IborIndex > &iborIndex, const Handle< Quote > &convexityAdjustment=Handle< Quote >())
FuturesRateHelper (Real price, const Date &immDate, const boost::shared_ptr< IborIndex > &iborIndex, Rate convexityAdjustment=0.0)
RateHelper interface
Real impliedQuote () const
FuturesRateHelper inspectors
Real convexityAdjustment () const
Visitability
void accept (AcyclicVisitor &)
Private Attributes
Time yearFraction_
Handle< Quote > convAdj_
Detailed Description
Rate helper for bootstrapping over IborIndex futures prices.
Definition at line 46 of file ratehelpers.hpp.
Constructor & Destructor Documentation
QuantLib::FuturesRateHelper::FuturesRateHelper (const Handle< Quote > & price, const Date & immDate, Natural lengthInMonths, const Calendar & calendar, BusinessDayConvention convention, bool endOfMonth, const DayCounter & dayCounter, const Handle< Quote > & convexityAdjustment = Handle<Quote>())
Definition at line 42 of file ratehelpers.cpp.
References QuantLib::Calendar::advance(), convAdj_, QuantLib::BootstrapHelper< TS >::earliestDate_, QuantLib::IMM::isIMMdate(), QuantLib::BootstrapHelper< TS >::latestDate_, QuantLib::Months, QL_REQUIRE, QuantLib::Observer::registerWith(), QuantLib::DayCounter::yearFraction(), and yearFraction_.
    : RateHelper(price), convAdj_(convAdj) {
        QL_REQUIRE(IMM::isIMMdate(immDate, false),
                   immDate << " is not a valid IMM date");
        earliestDate_ = immDate;
        latestDate_ = calendar.advance(immDate, lengthInMonths*Months,
                                       convention, endOfMonth);
        yearFraction_ = dayCounter.yearFraction(earliestDate_, latestDate_);
        registerWith(convAdj_);
    }
QuantLib::FuturesRateHelper::FuturesRateHelper (Real price, const Date & immDate, Natural lengthInMonths, const Calendar & calendar, BusinessDayConvention convention, bool endOfMonth, const DayCounter & dayCounter, Rate convexityAdjustment = 0.0)
Definition at line 61 of file ratehelpers.cpp.
References QuantLib::Calendar::advance(), QuantLib::BootstrapHelper< TS >::earliestDate_, QuantLib::IMM::isIMMdate(), QuantLib::BootstrapHelper< TS >::latestDate_, QuantLib::Months, QL_REQUIRE, QuantLib::DayCounter::yearFraction(), and yearFraction_.
    : RateHelper(price),
      convAdj_(Handle<Quote>(shared_ptr<Quote>(new SimpleQuote(convAdj))))
    {
        QL_REQUIRE(IMM::isIMMdate(immDate, false),
                   immDate << "is not a valid IMM date");
        earliestDate_ = immDate;
        latestDate_ = calendar.advance(immDate, lengthInMonths*Months,
                                       convention, endOfMonth);
        yearFraction_ = dayCounter.yearFraction(earliestDate_, latestDate_);
    }
QuantLib::FuturesRateHelper::FuturesRateHelper (const Handle< Quote > & price, const Date & immStartDate, const Date & endDate, const DayCounter & dayCounter, const Handle< Quote > & convexityAdjustment = Handle<Quote>())
Definition at line 80 of file ratehelpers.cpp.
References convAdj_, QuantLib::BootstrapHelper< TS >::earliestDate_, anonymous_namespace{marketmodel.cpp}::endDate, QuantLib::IMM::isIMMdate(), QuantLib::BootstrapHelper< TS >::latestDate_, QuantLib::IMM::nextDate(), QL_REQUIRE, QuantLib::Observer::registerWith(), QuantLib::DayCounter::yearFraction(), and yearFraction_.
    : RateHelper(price), convAdj_(convAdj) {
        QL_REQUIRE(IMM::isIMMdate(immDate, false),
                   immDate << " is not a valid IMM date");
        earliestDate_ = immDate;
        if (endDate==Date()) {
            latestDate_ = IMM::nextDate(immDate, false);
            latestDate_ = IMM::nextDate(latestDate_, false);
            latestDate_ = IMM::nextDate(latestDate_, false);
        } else {
            QL_REQUIRE(endDate>immDate,
                       "end date (" << endDate <<
                       ") must be greater than IMM start date (" <<
                       immDate << ")");
            latestDate_ = endDate;
        }
        yearFraction_ = dayCounter.yearFraction(earliestDate_, latestDate_);
        registerWith(convAdj_);
    }
QuantLib::FuturesRateHelper::FuturesRateHelper (Real price, const Date & immStartDate, const Date & endDate, const DayCounter & dayCounter, Rate convexityAdjustment = 0.0)
Definition at line 107 of file ratehelpers.cpp.
References QuantLib::BootstrapHelper< TS >::earliestDate_, anonymous_namespace{marketmodel.cpp}::endDate, QuantLib::IMM::isIMMdate(), QuantLib::BootstrapHelper< TS >::latestDate_, QuantLib::IMM::nextDate(), QL_REQUIRE, QuantLib::DayCounter::yearFraction(), and yearFraction_.
    : RateHelper(price),
      convAdj_(Handle<Quote>(shared_ptr<Quote>(new SimpleQuote(convAdj))))
    {
        QL_REQUIRE(IMM::isIMMdate(immDate, false),
                   immDate << "is not a valid IMM date");
        earliestDate_ = immDate;
        if (endDate==Date()) {
            latestDate_ = IMM::nextDate(immDate, false);
            latestDate_ = IMM::nextDate(latestDate_, false);
            latestDate_ = IMM::nextDate(latestDate_, false);
        } else {
            QL_REQUIRE(endDate>immDate,
                       "end date (" << endDate <<
                       ") must be greater than IMM start date (" <<
                       immDate << ")");
            latestDate_ = endDate;
        }
        yearFraction_ = dayCounter.yearFraction(earliestDate_, latestDate_);
    }
QuantLib::FuturesRateHelper::FuturesRateHelper (const Handle< Quote > & price, const Date & immDate, const boost::shared_ptr< IborIndex > & iborIndex, const Handle< Quote > & convexityAdjustment = Handle< Quote >())
QuantLib::FuturesRateHelper::FuturesRateHelper (Real price, const Date & immDate, const boost::shared_ptr< IborIndex > & iborIndex, Rate convexityAdjustment = 0.0)
Member Function Documentation
void QuantLib::FuturesRateHelper::accept (AcyclicVisitor & v) [virtual]
Reimplemented from QuantLib::BootstrapHelper< TS >.
Definition at line 180 of file ratehelpers.cpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Visitor< T >::visit().
{
        Visitor<FuturesRateHelper>* v1 =
            dynamic_cast<Visitor<FuturesRateHelper>*>(&v);
        if (v1 != 0)
            v1->visit(*this);
        else
            RateHelper::accept(v);
    }
Real QuantLib::FuturesRateHelper::convexityAdjustment () const
Definition at line 176 of file ratehelpers.cpp.
References convAdj_, and QuantLib::Handle< T >::empty().
{
        return convAdj_.empty() ? 0.0 : convAdj_->value();
    }
Real QuantLib::FuturesRateHelper::impliedQuote () const [virtual]
Implements QuantLib::BootstrapHelper< TS >.
Definition at line 164 of file ratehelpers.cpp.
References convAdj_, QuantLib::BootstrapHelper< TS >::earliestDate_, QuantLib::Handle< T >::empty(), QuantLib::BootstrapHelper< TS >::latestDate_, QL_ENSURE, QL_REQUIRE, QuantLib::BootstrapHelper< TS >::termStructure_, and yearFraction_.
{
        QL_REQUIRE(termStructure_ != 0, "term structure not set");
        Rate forwardRate = (termStructure_->discount(earliestDate_) /
            termStructure_->discount(latestDate_)-1.0)/yearFraction_;
        Rate convAdj = convAdj_.empty() ? 0.0 : convAdj_->value();
        QL_ENSURE(convAdj >= 0.0,
                  "Negative (" << convAdj <<
                  ") futures convexity adjustment");
        Rate futureRate = forwardRate + convAdj;
        return 100.0 * (1.0 - futureRate);
    }
Member Data Documentation
Handle<Quote> QuantLib::FuturesRateHelper::convAdj_ [private]
Definition at line 96 of file ratehelpers.hpp.
Referenced by convexityAdjustment(), FuturesRateHelper(), and impliedQuote().
Time QuantLib::FuturesRateHelper::yearFraction_ [private]
Definition at line 95 of file ratehelpers.hpp.
Referenced by FuturesRateHelper(), and impliedQuote().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/yield/ratehelpers.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/yield/ratehelpers.cpp