QuantLib: QuantLib::CurveState Class Reference
QuantLib::CurveState Class Reference
Curve state for market-model simulations
#include <curvestate.hpp>
Public Member Functions
CurveState (const std::vector< Time > &rateTimes)
virtual ~CurveState ()
Inspectors
Size numberOfRates () const
const std::vector< Time > & rateTimes () const
const std::vector< Time > & rateTaus () const
virtual Real discountRatio (Size i, Size j) const =0
virtual Rate forwardRate (Size i) const =0
virtual Rate coterminalSwapAnnuity (Size numeraire, Size i) const =0
virtual Rate coterminalSwapRate (Size i) const =0
virtual Rate cmSwapAnnuity (Size numeraire, Size i, Size spanningForwards) const =0
virtual Rate cmSwapRate (Size i, Size spanningForwards) const =0
virtual const std::vector< Rate > & forwardRates () const =0
virtual const std::vector< Rate > & coterminalSwapRates () const =0
virtual const std::vector< Rate > & cmSwapRates (Size spanningForwards) const =0
Rate swapRate (Size begin, Size end) const
virtual std::auto_ptr< CurveState > clone () const =0
Protected Attributes
Size numberOfRates_
std::vector< Time > rateTimes_
std::vector< Time > rateTaus_
Detailed Description
Curve state for market-model simulations
This class stores the state of the yield curve associated to the fixed calendar times within the simulation. This is the workhorse discounting object associated to the rate times of the simulation. It's important to pass the rates via an object like this to the product rather than directly to make it easier to switch to other engines such as a coterminal swap rate engine. Many products will not need expired rates and others will only require the first rate.
Definition at line 41 of file curvestate.hpp.
Constructor & Destructor Documentation
QuantLib::CurveState::CurveState (const std::vector< Time > & rateTimes)
Definition at line 26 of file curvestate.cpp.
References QuantLib::checkIncreasingTimesAndCalculateTaus(), rateTaus_, and rateTimes_.
    : numberOfRates_(rateTimes.empty() ? 0 : rateTimes.size()-1),
      rateTimes_(rateTimes), rateTaus_(numberOfRates_) {
        checkIncreasingTimesAndCalculateTaus(rateTimes_, rateTaus_);
    }
virtual QuantLib::CurveState::~CurveState () [inline, virtual]
Definition at line 54 of file curvestate.hpp.
{}
Member Function Documentation
virtual std::auto_ptr<CurveState> QuantLib::CurveState::clone () const [pure virtual]
Implemented in QuantLib::LMMCurveState, QuantLib::CoterminalSwapCurveState, and QuantLib::CMSwapCurveState.
virtual Rate QuantLib::CurveState::cmSwapAnnuity (Size numeraire, Size i, Size spanningForwards) const [pure virtual]
Implemented in QuantLib::LMMCurveState, QuantLib::CoterminalSwapCurveState, and QuantLib::CMSwapCurveState.
Referenced by QuantLib::MultiStepSwaption::nextTimeStep().
virtual Rate QuantLib::CurveState::cmSwapRate (Size i, Size spanningForwards) const [pure virtual]
Implemented in QuantLib::LMMCurveState, QuantLib::CoterminalSwapCurveState, and QuantLib::CMSwapCurveState.
Referenced by QuantLib::SwapForwardMappings::cmSwapZedMatrix(), QuantLib::SwapForwardMappings::coinitialSwapZedMatrix(), and QuantLib::MultiStepSwaption::nextTimeStep().
virtual const std::vector<Rate>& QuantLib::CurveState::cmSwapRates (Size spanningForwards) const [pure virtual]
Implemented in QuantLib::LMMCurveState, QuantLib::CoterminalSwapCurveState, and QuantLib::CMSwapCurveState.
virtual Rate QuantLib::CurveState::coterminalSwapAnnuity (Size numeraire, Size i) const [pure virtual]
Implemented in QuantLib::LMMCurveState, QuantLib::CoterminalSwapCurveState, and QuantLib::CMSwapCurveState.
Referenced by QuantLib::SwapForwardMappings::coterminalSwapForwardJacobian(), QuantLib::BermudanSwaptionExerciseValue::nextStep(), QuantLib::MultiStepCoterminalSwaptions::nextTimeStep(), QuantLib::MarketModelPathwiseCoterminalSwaptionsDeflated::nextTimeStep(), and QuantLib::MarketModelPathwiseCoterminalSwaptionsNumericalDeflated::nextTimeStep().
virtual Rate QuantLib::CurveState::coterminalSwapRate (Size i) const [pure virtual]
Implemented in QuantLib::LMMCurveState, QuantLib::CoterminalSwapCurveState, and QuantLib::CMSwapCurveState.
Referenced by QuantLib::SwapRateTrigger::exercise(), QuantLib::BermudanSwaptionExerciseValue::nextStep(), QuantLib::MultiStepCoterminalSwaptions::nextTimeStep(), QuantLib::MarketModelPathwiseCoterminalSwaptionsDeflated::nextTimeStep(), QuantLib::MarketModelPathwiseCoterminalSwaptionsNumericalDeflated::nextTimeStep(), QuantLib::SwapBasisSystem::values(), QuantLib::TriggeredSwapExercise::values(), and QuantLib::SwapForwardBasisSystem::values().
virtual const std::vector<Rate>& QuantLib::CurveState::coterminalSwapRates () const [pure virtual]
Implemented in QuantLib::LMMCurveState, QuantLib::CoterminalSwapCurveState, and QuantLib::CMSwapCurveState.
Referenced by QuantLib::SwapForwardMappings::coterminalSwapZedMatrix().
virtual Real QuantLib::CurveState::discountRatio (Size i, Size j) const [pure virtual]
Implemented in QuantLib::LMMCurveState, QuantLib::CoterminalSwapCurveState, and QuantLib::CMSwapCurveState.
Referenced by QuantLib::SwapForwardMappings::annuity(), QuantLib::collectNodeData(), QuantLib::SwapForwardMappings::coterminalSwapForwardJacobian(), QuantLib::ForwardForwardMappings::ForwardForwardJacobian(), QuantLib::LongstaffSchwartzExerciseStrategy::nextStep(), QuantLib::MultiStepPeriodCapletSwaptions::nextTimeStep(), QuantLib::MarketModelPathwiseCoterminalSwaptionsDeflated::nextTimeStep(), QuantLib::MarketModelPathwiseMultiDeflatedCaplet::nextTimeStep(), QuantLib::MarketModelDiscounter::numeraireBonds(), QuantLib::ForwardForwardMappings::RestrictCurveState(), QuantLib::ProxyGreekEngine::singleEvolverValues(), QuantLib::SwapForwardMappings::swapDerivative(), swapRate(), QuantLib::SwapForwardBasisSystem::values(), and QuantLib::ForwardForwardMappings::YMatrix().
virtual Rate QuantLib::CurveState::forwardRate (Size i) const [pure virtual]
Implemented in QuantLib::LMMCurveState, QuantLib::CoterminalSwapCurveState, and QuantLib::CMSwapCurveState.
Referenced by QuantLib::MultiStepForwards::nextTimeStep(), QuantLib::OneStepCoinitialSwaps::nextTimeStep(), QuantLib::OneStepForwards::nextTimeStep(), QuantLib::MultiStepCoterminalSwaps::nextTimeStep(), QuantLib::MultiStepCoinitialSwaps::nextTimeStep(), QuantLib::OneStepCoterminalSwaps::nextTimeStep(), QuantLib::MultiStepSwap::nextTimeStep(), QuantLib::MultiStepOptionlets::nextTimeStep(), QuantLib::MultiStepRatchet::nextTimeStep(), QuantLib::MultiStepTarn::nextTimeStep(), QuantLib::OneStepOptionlets::nextTimeStep(), QuantLib::MultiStepInverseFloater::nextTimeStep(), QuantLib::MarketModelPathwiseCoterminalSwaptionsDeflated::nextTimeStep(), QuantLib::MarketModelPathwiseSwap::nextTimeStep(), QuantLib::MarketModelPathwiseMultiCaplet::nextTimeStep(), QuantLib::MarketModelPathwiseInverseFloater::nextTimeStep(), QuantLib::MarketModelPathwiseMultiDeflatedCaplet::nextTimeStep(), QuantLib::SwapForwardMappings::swapDerivative(), QuantLib::SwapBasisSystem::values(), QuantLib::SwapForwardBasisSystem::values(), and QuantLib::ForwardForwardMappings::YMatrix().
virtual const std::vector<Rate>& QuantLib::CurveState::forwardRates () const [pure virtual]
Implemented in QuantLib::LMMCurveState, QuantLib::CoterminalSwapCurveState, and QuantLib::CMSwapCurveState.
Referenced by QuantLib::SwapForwardMappings::cmSwapZedMatrix(), QuantLib::SwapForwardMappings::coinitialSwapZedMatrix(), QuantLib::SwapForwardMappings::coterminalSwapForwardJacobian(), QuantLib::SwapForwardMappings::coterminalSwapZedMatrix(), QuantLib::MarketModelPathwiseCoterminalSwaptionsNumericalDeflated::nextTimeStep(), QuantLib::LogNormalFwdRateiBalland::setInitialState(), QuantLib::LogNormalFwdRateBalland::setInitialState(), QuantLib::NormalFwdRatePc::setInitialState(), QuantLib::LogNormalFwdRateIpc::setInitialState(), QuantLib::LogNormalFwdRateEuler::setInitialState(), QuantLib::LogNormalFwdRatePc::setInitialState(), QuantLib::SVDDFwdRatePc::setInitialState(), and QuantLib::LogNormalFwdRateEulerConstrained::setInitialState().
Size QuantLib::CurveState::numberOfRates () const [inline]
Definition at line 58 of file curvestate.hpp.
References numberOfRates_.
Referenced by QuantLib::SwapForwardMappings::cmSwapForwardJacobian(), QuantLib::SwapForwardMappings::cmSwapZedMatrix(), QuantLib::SwapForwardMappings::coinitialSwapForwardJacobian(), QuantLib::SwapForwardMappings::coinitialSwapZedMatrix(), QuantLib::SMMDriftCalculator::compute(), QuantLib::CMSMMDriftCalculator::compute(), QuantLib::SwapForwardMappings::coterminalSwapForwardJacobian(), QuantLib::SwapForwardMappings::coterminalSwapZedMatrix(), QuantLib::CotSwapFromFwdCorrelation::CotSwapFromFwdCorrelation(), QuantLib::ForwardForwardMappings::ForwardForwardJacobian(), QuantLib::FwdPeriodAdapter::FwdPeriodAdapter(), QuantLib::CTSMMCapletCalibration::performChecks(), QuantLib::ForwardForwardMappings::RestrictCurveState(), MarketModelTest::testPeriodAdapter(), and QuantLib::ForwardForwardMappings::YMatrix().
{ return numberOfRates_; }
const std::vector<Time>& QuantLib::CurveState::rateTaus () const [inline]
Definition at line 61 of file curvestate.hpp.
References rateTaus_.
Referenced by QuantLib::SwapForwardMappings::annuity(), QuantLib::SMMDriftCalculator::compute(), QuantLib::CMSMMDriftCalculator::compute(), QuantLib::SwapForwardMappings::coterminalSwapForwardJacobian(), QuantLib::ForwardForwardMappings::ForwardForwardJacobian(), QuantLib::SwapForwardMappings::swapDerivative(), and MarketModelTest::testPeriodAdapter().
{ return rateTaus_; }
const std::vector<Time>& QuantLib::CurveState::rateTimes () const [inline]
Definition at line 60 of file curvestate.hpp.
References rateTimes_.
Referenced by QuantLib::CotSwapFromFwdCorrelation::CotSwapFromFwdCorrelation(), QuantLib::ForwardForwardMappings::ForwardForwardJacobian(), QuantLib::FwdPeriodAdapter::FwdPeriodAdapter(), QuantLib::CTSMMCapletCalibration::performChecks(), QuantLib::ForwardForwardMappings::RestrictCurveState(), MarketModelTest::testPeriodAdapter(), and QuantLib::ForwardForwardMappings::YMatrix().
{ return rateTimes_; }
Rate QuantLib::CurveState::swapRate (Size begin, Size end) const
Definition at line 32 of file curvestate.cpp.
References discountRatio(), numberOfRates_, QL_REQUIRE, and rateTaus_.
Referenced by QuantLib::ProxyGreekEngine::singleEvolverValues().
{
        QL_REQUIRE(end > begin, "empty range specified");
        QL_REQUIRE(end <= numberOfRates_, "taus/end mismatch");
        Real sum = 0.0;
        for (Size i=begin; i<end; ++i)
            sum += rateTaus_[i]*discountRatio(i+1, numberOfRates_);
        return (discountRatio(begin, numberOfRates_)-discountRatio(end, numberOfRates_))/sum;
    }
Member Data Documentation
Size QuantLib::CurveState::numberOfRates_ [protected]
Definition at line 84 of file curvestate.hpp.
Referenced by QuantLib::CMSwapCurveState::cmSwapAnnuity(), QuantLib::CoterminalSwapCurveState::cmSwapAnnuity(), QuantLib::LMMCurveState::cmSwapAnnuity(), QuantLib::CMSwapCurveState::cmSwapRate(), QuantLib::CoterminalSwapCurveState::cmSwapRate(), QuantLib::LMMCurveState::cmSwapRate(), QuantLib::CMSwapCurveState::cmSwapRates(), QuantLib::CoterminalSwapCurveState::cmSwapRates(), QuantLib::LMMCurveState::cmSwapRates(), QuantLib::CMSwapCurveState::coterminalSwapAnnuity(), QuantLib::CoterminalSwapCurveState::coterminalSwapAnnuity(), QuantLib::LMMCurveState::coterminalSwapAnnuity(), QuantLib::CMSwapCurveState::coterminalSwapRate(), QuantLib::CoterminalSwapCurveState::coterminalSwapRate(), QuantLib::LMMCurveState::coterminalSwapRate(), QuantLib::CMSwapCurveState::coterminalSwapRates(), QuantLib::CoterminalSwapCurveState::coterminalSwapRates(), QuantLib::LMMCurveState::coterminalSwapRates(), QuantLib::CMSwapCurveState::discountRatio(), QuantLib::CoterminalSwapCurveState::discountRatio(), QuantLib::LMMCurveState::discountRatio(), QuantLib::CMSwapCurveState::forwardRate(), QuantLib::CoterminalSwapCurveState::forwardRate(), QuantLib::LMMCurveState::forwardRate(), QuantLib::CMSwapCurveState::forwardRates(), QuantLib::CoterminalSwapCurveState::forwardRates(), QuantLib::LMMCurveState::forwardRates(), numberOfRates(), QuantLib::CMSwapCurveState::setOnCMSwapRates(), QuantLib::CoterminalSwapCurveState::setOnCoterminalSwapRates(), QuantLib::LMMCurveState::setOnDiscountRatios(), QuantLib::LMMCurveState::setOnForwardRates(), and swapRate().
std::vector<Time> QuantLib::CurveState::rateTaus_ [protected]
Definition at line 85 of file curvestate.hpp.
Referenced by QuantLib::CMSwapCurveState::cmSwapAnnuity(), QuantLib::CoterminalSwapCurveState::cmSwapAnnuity(), QuantLib::LMMCurveState::cmSwapAnnuity(), QuantLib::CMSwapCurveState::cmSwapRate(), QuantLib::CoterminalSwapCurveState::cmSwapRate(), QuantLib::LMMCurveState::cmSwapRate(), QuantLib::CMSwapCurveState::cmSwapRates(), QuantLib::CoterminalSwapCurveState::cmSwapRates(), QuantLib::LMMCurveState::cmSwapRates(), QuantLib::CMSwapCurveState::coterminalSwapAnnuity(), QuantLib::LMMCurveState::coterminalSwapAnnuity(), QuantLib::CMSwapCurveState::coterminalSwapRate(), QuantLib::CMSwapCurveState::coterminalSwapRates(), QuantLib::LMMCurveState::coterminalSwapRates(), CurveState(), QuantLib::CMSwapCurveState::forwardRate(), QuantLib::CoterminalSwapCurveState::forwardRate(), QuantLib::CMSwapCurveState::forwardRates(), QuantLib::CoterminalSwapCurveState::forwardRates(), rateTaus(), QuantLib::CMSwapCurveState::setOnCMSwapRates(), QuantLib::CoterminalSwapCurveState::setOnCoterminalSwapRates(), QuantLib::LMMCurveState::setOnDiscountRatios(), QuantLib::LMMCurveState::setOnForwardRates(), and swapRate().
std::vector<Time> QuantLib::CurveState::rateTimes_ [protected]
Definition at line 85 of file curvestate.hpp.
Referenced by CurveState(), and rateTimes().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/curvestate.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/curvestate.cpp