QuantLib: QuantLib::Money Class Reference
QuantLib::Money Class Reference
amount of cash
#include <money.hpp>
Public Member Functions
Constructors
Money ()
Money (const Currency &currency, Decimal value)
Money (Decimal value, const Currency &currency)
Inspectors
const Currency & currency () const
Decimal value () const
Money rounded () const
Money arithmetics
See below for non-member functions and for settings which determine the behavior of the operators.
Money operator+ () const
Money operator- () const
Money & operator+= (const Money &)
Money & operator-= (const Money &)
Money & operator*= (Decimal)
Money & operator/= (Decimal)
Private Attributes
Decimal value_
Currency currency_
Related Functions
(Note that these are not member functions.)
Money operator+ (const Money &, const Money &)
Money operator- (const Money &, const Money &)
Money operator* (const Money &, Decimal)
Money operator* (Decimal, const Money &)
Money operator/ (const Money &, Decimal)
Decimal operator/ (const Money &, const Money &)
bool operator== (const Money &, const Money &)
bool operator!= (const Money &, const Money &)
bool operator< (const Money &, const Money &)
bool operator<= (const Money &, const Money &)
bool operator> (const Money &, const Money &)
bool operator>= (const Money &, const Money &)
bool close (const Money &, const Money &, Size n=42)
bool close_enough (const Money &, const Money &, Size n=42)
Money operator* (Decimal, const Currency &)
Money operator* (const Currency &, Decimal)
std::ostream & operator<< (std::ostream &, const Money &)
Conversion settings
These parameters are used for combining money amounts in different currencies
enum ConversionType { NoConversion, BaseCurrencyConversion, AutomatedConversion }
static ConversionType conversionType = Money::NoConversion
static Currency baseCurrency = Currency()
Detailed Description
amount of cash
Test:
money arithmetic is tested with and without currency conversions.
Definition at line 36 of file money.hpp.
Member Enumeration Documentation
enum QuantLib::Money::ConversionType
Enumerator:
NoConversion
do not perform conversions
BaseCurrencyConversion
convert both operands to the base currency before converting
AutomatedConversion
return the result in the currency of the first operand
Definition at line 69 of file money.hpp.
{
            NoConversion,
            BaseCurrencyConversion,
            AutomatedConversion
        };
Constructor & Destructor Documentation
QuantLib::Money::Money () [inline]
Definition at line 135 of file money.hpp.
Referenced by operator-(), and rounded().
    : value_(0.0) {}
QuantLib::Money::Money (const Currency & currency, Decimal value) [inline]
Definition at line 138 of file money.hpp.
    : value_(value), currency_(currency) {}
QuantLib::Money::Money (Decimal value, const Currency & currency) [inline]
Definition at line 141 of file money.hpp.
    : value_(value), currency_(currency) {}
Member Function Documentation
const Currency & QuantLib::Money::currency () const [inline]
Definition at line 144 of file money.hpp.
References currency_.
Referenced by QuantLib::EnergyCommodity::calculateSecondaryCostAmounts(), QuantLib::CommodityPricingHelper::calculateUnitCost(), QuantLib::EnergyCommodity::calculateUnitCost(), QuantLib::close(), QuantLib::close_enough(), QuantLib::anonymous_namespace{money.cpp}::convertTo(), QuantLib::CommodityCashFlow::currency(), QuantLib::ExchangeRate::exchange(), QuantLib::operator/(), QuantLib::operator<(), QuantLib::operator<<(), QuantLib::operator<=(), QuantLib::operator==(), QuantLib::EnergyFuture::performCalculations(), QuantLib::EnergyBasisSwap::performCalculations(), QuantLib::EnergyVanillaSwap::performCalculations(), and MoneyTest::testAutomated().
{
        return currency_;
    }
Money & QuantLib::Money::operator*= (Decimal x) [inline]
Definition at line 164 of file money.hpp.
References value_.
{
        value_ *= x;
        return *this;
    }
Money QuantLib::Money::operator+ () const [inline]
Definition at line 156 of file money.hpp.
{
        return *this;
    }
Money & QuantLib::Money::operator+= (const Money & m)
Definition at line 50 of file money.cpp.
References AutomatedConversion, BaseCurrencyConversion, conversionType, QuantLib::anonymous_namespace{quantity.cpp}::convertTo(), QuantLib::anonymous_namespace{quantity.cpp}::convertToBase(), currency_, QL_FAIL, and value_.
{
        if (currency_ == m.currency_) {
            value_ += m.value_;
        } else if (Money::conversionType == Money::BaseCurrencyConversion) {
            convertToBase(*this);
            Money tmp = m;
            convertToBase(tmp);
            *this += tmp;
        } else if (Money::conversionType == Money::AutomatedConversion) {
            Money tmp = m;
            convertTo(tmp, currency_);
            *this += tmp;
        } else {
            QL_FAIL("currency mismatch and no conversion specified");
        }
        return *this;
    }
Money QuantLib::Money::operator- () const [inline]
Definition at line 160 of file money.hpp.
References currency_, Money(), and value_.
{
        return Money(-value_, currency_);
    }
Money & QuantLib::Money::operator-= (const Money & m)
Definition at line 68 of file money.cpp.
References AutomatedConversion, BaseCurrencyConversion, conversionType, QuantLib::anonymous_namespace{quantity.cpp}::convertTo(), QuantLib::anonymous_namespace{quantity.cpp}::convertToBase(), currency_, QL_FAIL, and value_.
{
        if (currency_ == m.currency_) {
            value_ -= m.value_;
        } else if (Money::conversionType == Money::BaseCurrencyConversion) {
            convertToBase(*this);
            Money tmp = m;
            convertToBase(tmp);
            *this -= tmp;
        } else if (Money::conversionType == Money::AutomatedConversion) {
            Money tmp = m;
            convertTo(tmp, currency_);
            *this -= tmp;
        } else {
            QL_FAIL("currency mismatch and no conversion specified");
        }
        return *this;
    }
Money & QuantLib::Money::operator/= (Decimal x) [inline]
Definition at line 169 of file money.hpp.
References value_.
{
        value_ /= x;
        return *this;
    }
Money QuantLib::Money::rounded () const [inline]
Definition at line 152 of file money.hpp.
References currency_, Money(), QuantLib::Currency::rounding(), and value_.
Referenced by QuantLib::anonymous_namespace{money.cpp}::convertTo(), and QuantLib::operator<<().
{
        return Money(currency_.rounding()(value_), currency_);
    }
Decimal QuantLib::Money::value () const [inline]
Definition at line 148 of file money.hpp.
References value_.
Referenced by QuantLib::CommodityCashFlow::amount(), QuantLib::EnergyCommodity::calculateSecondaryCostAmounts(), QuantLib::CommodityPricingHelper::calculateUnitCost(), QuantLib::EnergyCommodity::calculateUnitCost(), QuantLib::close(), QuantLib::close_enough(), QuantLib::ExchangeRate::exchange(), QuantLib::operator/(), QuantLib::operator<(), QuantLib::operator<<(), QuantLib::operator<=(), QuantLib::operator==(), QuantLib::EnergyFuture::performCalculations(), QuantLib::EnergyBasisSwap::performCalculations(), QuantLib::EnergyVanillaSwap::performCalculations(), MoneyTest::testAutomated(), MoneyTest::testBaseCurrency(), ExchangeRateTest::testDerived(), ExchangeRateTest::testDirect(), ExchangeRateTest::testDirectLookup(), MoneyTest::testNone(), ExchangeRateTest::testSmartLookup(), and ExchangeRateTest::testTriangulatedLookup().
{
        return value_;
    }
Friends And Related Function Documentation
bool close (const Money & , const Money & , Size n = 42) [related]
Definition at line 158 of file money.cpp.
{
        if (m1.currency() == m2.currency()) {
            return close(m1.value(),m2.value(),n);
        } else if (Money::conversionType == Money::BaseCurrencyConversion) {
            Money tmp1 = m1;
            convertToBase(tmp1);
            Money tmp2 = m2;
            convertToBase(tmp2);
            return close(tmp1,tmp2,n);
        } else if (Money::conversionType == Money::AutomatedConversion) {
            Money tmp = m2;
            convertTo(tmp, m1.currency());
            return close(m1,tmp,n);
        } else {
            QL_FAIL("currency mismatch and no conversion specified");
        }
    }
bool close_enough (const Money & , const Money & , Size n = 42) [related]
Definition at line 176 of file money.cpp.
{
        if (m1.currency() == m2.currency()) {
            return close_enough(m1.value(),m2.value(),n);
        } else if (Money::conversionType == Money::BaseCurrencyConversion) {
            Money tmp1 = m1;
            convertToBase(tmp1);
            Money tmp2 = m2;
            convertToBase(tmp2);
            return close_enough(tmp1,tmp2,n);
        } else if (Money::conversionType == Money::AutomatedConversion) {
            Money tmp = m2;
            convertTo(tmp, m1.currency());
            return close_enough(m1,tmp,n);
        } else {
            QL_FAIL("currency mismatch and no conversion specified");
        }
    }
bool operator!= (const Money & , const Money &) [related]
Definition at line 203 of file money.hpp.
{
        return !(m1 == m2);
    }
Money operator* (const Money & , Decimal) [related]
Definition at line 187 of file money.hpp.
{
        Money tmp = m;
        tmp *= x;
        return tmp;
    }
Money operator* (Decimal , const Money &) [related]
Definition at line 193 of file money.hpp.
{
        return m*x;
    }
Money operator* (Decimal , const Currency &) [related]
Definition at line 215 of file money.hpp.
{
        return Money(value,c);
    }
Money operator* (const Currency & , Decimal) [related]
Definition at line 219 of file money.hpp.
{
        return Money(value,c);
    }
Money operator+ (const Money & , const Money &) [related]
Definition at line 175 of file money.hpp.
{
        Money tmp = m1;
        tmp += m2;
        return tmp;
    }
Money operator- (const Money & , const Money &) [related]
Definition at line 181 of file money.hpp.
{
        Money tmp = m1;
        tmp -= m2;
        return tmp;
    }
Money operator/ (const Money & , Decimal) [related]
Definition at line 197 of file money.hpp.
{
        Money tmp = m;
        tmp /= x;
        return tmp;
    }
Decimal operator/ (const Money & , const Money &) [related]
Definition at line 86 of file money.cpp.
{
        if (m1.currency() == m2.currency()) {
            return m1.value()/m2.value();
        } else if (Money::conversionType == Money::BaseCurrencyConversion) {
            Money tmp1 = m1;
            convertToBase(tmp1);
            Money tmp2 = m2;
            convertToBase(tmp2);
            return tmp1/tmp2;
        } else if (Money::conversionType == Money::AutomatedConversion) {
            Money tmp = m2;
            convertTo(tmp, m1.currency());
            return m1/tmp;
        } else {
            QL_FAIL("currency mismatch and no conversion specified");
        }
    }
bool operator< (const Money & , const Money &) [related]
Definition at line 122 of file money.cpp.
{
        if (m1.currency() == m2.currency()) {
            return m1.value() < m2.value();
        } else if (Money::conversionType == Money::BaseCurrencyConversion) {
            Money tmp1 = m1;
            convertToBase(tmp1);
            Money tmp2 = m2;
            convertToBase(tmp2);
            return tmp1 < tmp2;
        } else if (Money::conversionType == Money::AutomatedConversion) {
            Money tmp = m2;
            convertTo(tmp, m1.currency());
            return m1 < tmp;
        } else {
            QL_FAIL("currency mismatch and no conversion specified");
        }
    }
std::ostream & operator<< (std::ostream & , const Money &) [related]
Definition at line 195 of file money.cpp.
{
        #if defined(QL_PATCH_MSVC71) && BOOST_VERSION > 103600
        // boost::format doesn't work with VC7 - simplified output
        return out << m.currency().code() << " "
                   << m.rounded().value();
        #else
        boost::format fmt(m.currency().format());
        fmt.exceptions(boost::io::all_error_bits ^
                       boost::io::too_many_args_bit);
        return out << fmt % m.rounded().value()
                          % m.currency().code()
                          % m.currency().symbol();
        #endif
    }
bool operator<= (const Money & , const Money &) [related]
Definition at line 140 of file money.cpp.
{
        if (m1.currency() == m2.currency()) {
            return m1.value() <= m2.value();
        } else if (Money::conversionType == Money::BaseCurrencyConversion) {
            Money tmp1 = m1;
            convertToBase(tmp1);
            Money tmp2 = m2;
            convertToBase(tmp2);
            return tmp1 <= tmp2;
        } else if (Money::conversionType == Money::AutomatedConversion) {
            Money tmp = m2;
            convertTo(tmp, m1.currency());
            return m1 <= tmp;
        } else {
            QL_FAIL("currency mismatch and no conversion specified");
        }
    }
bool operator== (const Money & , const Money &) [related]
Definition at line 104 of file money.cpp.
{
        if (m1.currency() == m2.currency()) {
            return m1.value() == m2.value();
        } else if (Money::conversionType == Money::BaseCurrencyConversion) {
            Money tmp1 = m1;
            convertToBase(tmp1);
            Money tmp2 = m2;
            convertToBase(tmp2);
            return tmp1 == tmp2;
        } else if (Money::conversionType == Money::AutomatedConversion) {
            Money tmp = m2;
            convertTo(tmp, m1.currency());
            return m1 == tmp;
        } else {
            QL_FAIL("currency mismatch and no conversion specified");
        }
    }
bool operator> (const Money & , const Money &) [related]
Definition at line 207 of file money.hpp.
{
        return m2 < m1;
    }
bool operator>= (const Money & , const Money &) [related]
Definition at line 211 of file money.hpp.
{
        return m2 <= m1;
    }
Member Data Documentation
Currency QuantLib::Money::baseCurrency = Currency() [static]
Definition at line 79 of file money.hpp.
Referenced by QuantLib::anonymous_namespace{money.cpp}::convertToBase(), and MoneyTest::testBaseCurrency().
Money::ConversionType QuantLib::Money::conversionType = Money::NoConversion [static]
Definition at line 78 of file money.hpp.
Referenced by QuantLib::close(), QuantLib::close_enough(), operator+=(), operator-=(), QuantLib::operator/(), QuantLib::operator<(), QuantLib::operator<=(), QuantLib::operator==(), MoneyTest::testAutomated(), MoneyTest::testBaseCurrency(), ExchangeRateTest::testDerived(), ExchangeRateTest::testDirect(), ExchangeRateTest::testDirectLookup(), MoneyTest::testNone(), ExchangeRateTest::testSmartLookup(), and ExchangeRateTest::testTriangulatedLookup().
Currency QuantLib::Money::currency_ [private]
Definition at line 83 of file money.hpp.
Referenced by currency(), operator+=(), operator-(), operator-=(), and rounded().
Decimal QuantLib::Money::value_ [private]
Definition at line 82 of file money.hpp.
Referenced by operator*=(), operator+=(), operator-(), operator-=(), operator/=(), rounded(), and value().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/money.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/money.cpp