QuantLib: MarketModelSmmCapletAlphaCalibrationTest Class Reference
MarketModelSmmCapletAlphaCalibrationTest Class Reference
#include <marketmodel_smmcapletalphacalibration.hpp>
Static Public Member Functions
static void testFunction ()
static
boost::unit_test_framework::test_suite * suite ()
Detailed Description
Definition at line 28 of file marketmodel_smmcapletalphacalibration.hpp.
Member Function Documentation
test_suite * MarketModelSmmCapletAlphaCalibrationTest::suite () [static]
Definition at line 539 of file marketmodel_smmcapletalphacalibration.cpp.
References QUANTLIB_TEST_CASE, and testFunction().
Referenced by init_unit_test_suite().
{
    test_suite* suite = BOOST_TEST_SUITE("SMM Caplet alpha calibration test");
    #if !defined(QL_NO_UBLAS_SUPPORT)
    suite->add(QUANTLIB_TEST_CASE(
                    &MarketModelSmmCapletAlphaCalibrationTest::testFunction));
    #endif
    return suite;
}
void MarketModelSmmCapletAlphaCalibrationTest::testFunction () [static]
Definition at line 408 of file marketmodel_smmcapletalphacalibration.cpp.
References anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::a_, anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::alpha_, anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::alphaMax_, anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::alphaMin_, anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::b_, anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::beta_, anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::c_, QuantLib::CTSMMCapletCalibration::calibrate(), QuantLib::CTSMMCapletCalibration::capletMaxError(), QuantLib::CTSMMCapletCalibration::capletRmsError(), anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::capletVols_, anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::d_, QuantLib::CTSMMCapletCalibration::deformationSize(), anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::displacement_, QuantLib::CTSMMCapletCalibration::failures(), anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::longTermCorrelation_, anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::numberOfFactors_, QuantLib::io::ordinal(), anonymous_namespace{marketmodel.cpp}::printReport_, QL_FIXED, QuantLib::io::rate(), anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::rateTimes_, QuantLib::io::sequence(), anonymous_namespace{inflationvolatility.cpp}::setup(), QuantLib::CTSMMCapletCalibration::swapPseudoRoots(), QuantLib::CTSMMCapletCalibration::swaptionMaxError(), QuantLib::CTSMMCapletCalibration::swaptionRmsError(), anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::todaysForwards_, and QuantLib::transpose().
Referenced by suite().
{
    BOOST_MESSAGE("Testing alpha caplet calibration "
                  "in a lognormal coterminal swap market model...");
    setup();
    Size numberOfRates = todaysForwards_.size();
    EvolutionDescription evolution(rateTimes_);
    // Size numberOfSteps = evolution.numberOfSteps();
    boost::shared_ptr<PiecewiseConstantCorrelation> fwdCorr(new
        ExponentialForwardCorrelation(rateTimes_,
                                      longTermCorrelation_,
                                      beta_));
    boost::shared_ptr<LMMCurveState> cs(new LMMCurveState(rateTimes_));
    cs->setOnForwardRates(todaysForwards_);
    boost::shared_ptr<PiecewiseConstantCorrelation> corr(new
        CotSwapFromFwdCorrelation(fwdCorr, *cs, displacement_));
    std::vector<boost::shared_ptr<PiecewiseConstantVariance> >
                                    swapVariances(numberOfRates);
    for (Size i=0; i<numberOfRates; ++i) {
        swapVariances[i] = boost::shared_ptr<PiecewiseConstantVariance>(new
            PiecewiseConstantAbcdVariance(a_, b_, c_, d_,
                                          i, rateTimes_));
    }
    // create calibrator
    std::vector<Real> alphaInitial(numberOfRates, alpha_);
    std::vector<Real> alphaMax(numberOfRates,  1.0);
    std::vector<Real> alphaMin(numberOfRates, -1.0);
    bool maximizeHomogeneity = false; //?
    if (printReport_) {
        BOOST_MESSAGE("caplet market vols: " << QL_FIXED <<
                      std::setprecision(4) << io::sequence(capletVols_));
        BOOST_MESSAGE("alphaMin:           " << alphaMin_);
        BOOST_MESSAGE("alphaInitial:       " << alpha_);
        BOOST_MESSAGE("alphaMax:           " << alphaMax_);
        BOOST_MESSAGE("maximizeHomogeneity:" << maximizeHomogeneity);
    }
    CTSMMCapletAlphaFormCalibration calibrator(evolution,
                                               corr,
                                               swapVariances,
                                               capletVols_,
                                               cs,
                                               displacement_,
                                               alphaInitial,
                                               alphaMax,
                                               alphaMin,
                                               maximizeHomogeneity);
    // calibrate
    Natural maxIterations = 10;
    Real capletTolerance = 1e-4; // i.e. 1 bp
    Natural innerMaxIterations = 100;
    Real innerTolerance = 1e-8;
    if (printReport_) {
        BOOST_MESSAGE("numberOfFactors:    " << numberOfFactors_);
        BOOST_MESSAGE("maxIterations:      " << maxIterations);
        BOOST_MESSAGE("capletTolerance:    " << io::rate(capletTolerance));
        BOOST_MESSAGE("innerMaxIterations: " << innerMaxIterations);
        BOOST_MESSAGE("innerTolerance:     " << io::rate(innerTolerance));
    }
    bool result = calibrator.calibrate(numberOfFactors_,
                                       maxIterations,
                                       capletTolerance,
                                       innerMaxIterations,
                                       innerTolerance);
    if (!result)
        BOOST_ERROR("calibration failed");
    const std::vector<Matrix>& swapPseudoRoots = calibrator.swapPseudoRoots();
    boost::shared_ptr<MarketModel> smm(new
        PseudoRootFacade(swapPseudoRoots,
                         rateTimes_,
                         cs->coterminalSwapRates(),
                         std::vector<Spread>(numberOfRates, displacement_)));
    CotSwapToFwdAdapter flmm(smm);
    Matrix capletTotCovariance = flmm.totalCovariance(numberOfRates-1);
    std::vector<Volatility> capletVols(numberOfRates);
    for (Size i=0; i<numberOfRates; ++i) {
        capletVols[i] = std::sqrt(capletTotCovariance[i][i]/rateTimes_[i]);
    }
    if (printReport_) {
        BOOST_MESSAGE("caplet smm implied vols: " << QL_FIXED <<
                      std::setprecision(4) << io::sequence(capletVols));
        BOOST_MESSAGE("failures: " << calibrator.failures());
        BOOST_MESSAGE("deformationSize: " << calibrator.deformationSize());
        BOOST_MESSAGE("capletRmsError: " << calibrator.capletRmsError());
        BOOST_MESSAGE("capletMaxError: " << calibrator.capletMaxError());
        BOOST_MESSAGE("swaptionRmsError: " << calibrator.swaptionRmsError());
        BOOST_MESSAGE("swaptionMaxError: " << calibrator.swaptionMaxError());
    }
    // check perfect swaption fit
    Real error, swapTolerance = 1e-14;
    Matrix swapTerminalCovariance(numberOfRates, numberOfRates, 0.0);
    for (Size i=0; i<numberOfRates; ++i) {
        Volatility expSwaptionVol = swapVariances[i]->totalVolatility(i);
        swapTerminalCovariance += swapPseudoRoots[i] * transpose(swapPseudoRoots[i]);
        Volatility swaptionVol = std::sqrt(swapTerminalCovariance[i][i]/rateTimes_[i]);
        error = std::fabs(swaptionVol-expSwaptionVol);
        if (error>swapTolerance)
            BOOST_ERROR("failed to reproduce " << io::ordinal(i+1) << " swaption vol:"
                        "\n expected:  " << io::rate(expSwaptionVol) <<
                        "\n realized:  " << io::rate(swaptionVol) <<
                        "\n error:     " << error <<
                        "\n tolerance: " << swapTolerance);
    }
    // check caplet fit
    for (Size i=0; i<numberOfRates; ++i) {
        error = std::fabs(capletVols[i]-capletVols_[i]);
        if (error>capletTolerance)
            BOOST_ERROR("failed to reproduce " << io::ordinal(i+1) << " caplet vol:"
                        "\n expected:         " << io::rate(capletVols_[i]) <<
                        "\n realized:         " << io::rate(capletVols[i]) <<
                        "\n percentage error: " << error/capletVols_[i] <<
                        "\n error:            " << error <<
                        "\n tolerance:        " << capletTolerance);
    }
}
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/marketmodel_smmcapletalphacalibration.hpp
/home/deriversatile/QuantLib/QuantLibQt/test-suite/marketmodel_smmcapletalphacalibration.cpp