QuantLib: QuantLib::MarketModelPathwiseMultiDeflatedCaplet Class Reference
QuantLib::MarketModelPathwiseMultiDeflatedCaplet Class Reference
#include <pathwiseproductcaplet.hpp>
Public Member Functions
MarketModelPathwiseMultiDeflatedCaplet (const std::vector< Time > &rateTimes, const std::vector< Real > &accruals, const std::vector< Time > &paymentTimes, const std::vector< Rate > &strikes)
MarketModelPathwiseMultiDeflatedCaplet (const std::vector< Time > &rateTimes, const std::vector< Real > &accruals, const std::vector< Time > &paymentTimes, Rate strike)
virtual ~MarketModelPathwiseMultiDeflatedCaplet ()
virtual std::vector< Size > suggestedNumeraires () const
virtual const
EvolutionDescription & evolution () const
virtual std::vector< Time > possibleCashFlowTimes () const
virtual Size numberOfProducts () const
virtual Size maxNumberOfCashFlowsPerProductPerStep () const
virtual bool alreadyDeflated () const
virtual void reset ()
during simulation put product at start of path
virtual bool nextTimeStep (const CurveState &currentState, std::vector< Size > &numberCashFlowsThisStep, std::vector< std::vector< MarketModelPathwiseMultiProduct::CashFlow > > &cashFlowsGenerated)
return value indicates whether path is finished, TRUE means done
virtual std::auto_ptr
< MarketModelPathwiseMultiProduct > clone () const
returns a newly-allocated copy of itself
Private Attributes
std::vector< Real > rateTimes_
std::vector< Real > accruals_
std::vector< Time > paymentTimes_
std::vector< Rate > strikes_
Size numberRates_
Size currentIndex_
EvolutionDescription evolution_
Detailed Description
Definition at line 91 of file pathwiseproductcaplet.hpp.
Constructor & Destructor Documentation
QuantLib::MarketModelPathwiseMultiDeflatedCaplet::MarketModelPathwiseMultiDeflatedCaplet (const std::vector< Time > & rateTimes, const std::vector< Real > & accruals, const std::vector< Time > & paymentTimes, const std::vector< Rate > & strikes)
Definition at line 145 of file pathwiseproductcaplet.cpp.
References QuantLib::checkIncreasingTimes(), evolution_, numberRates_, QL_REQUIRE, and rateTimes_.
Referenced by clone().
        : rateTimes_(rateTimes),
        accruals_(accruals),
        paymentTimes_(paymentTimes),
        strikes_(strikes) ,
        numberRates_(accruals_.size())
    {
        checkIncreasingTimes(rateTimes);
        checkIncreasingTimes(paymentTimes);
        std::vector<Time> evolTimes(rateTimes_);
        evolTimes.pop_back();
        QL_REQUIRE(evolTimes.size()==numberRates_,
            "rateTimes.size()<> numberOfRates+1");
        QL_REQUIRE(paymentTimes.size()==numberRates_,
            "paymentTimes.size()<> numberOfRates");
        QL_REQUIRE(accruals.size()==numberRates_,
            "accruals.size()<> numberOfRates");
        QL_REQUIRE(strikes.size()==numberRates_,
            "strikes.size()<> numberOfRates");
        evolution_ = EvolutionDescription(rateTimes,evolTimes);
    }
QuantLib::MarketModelPathwiseMultiDeflatedCaplet::MarketModelPathwiseMultiDeflatedCaplet (const std::vector< Time > & rateTimes, const std::vector< Real > & accruals, const std::vector< Time > & paymentTimes, Rate strike)
Definition at line 177 of file pathwiseproductcaplet.cpp.
References QuantLib::checkIncreasingTimes(), evolution_, numberRates_, QL_REQUIRE, rateTimes_, and strikes_.
        : rateTimes_(rateTimes),
        accruals_(accruals),
        paymentTimes_(paymentTimes),
        strikes_(accruals.size()) ,
        numberRates_(accruals_.size())
    {
        checkIncreasingTimes(rateTimes);
        checkIncreasingTimes(paymentTimes);
        std::vector<Time> evolTimes(rateTimes_);
        evolTimes.pop_back();
        QL_REQUIRE(evolTimes.size()==numberRates_,
            "rateTimes.size()<> numberOfRates+1");
        QL_REQUIRE(paymentTimes.size()==numberRates_,
            "paymentTimes.size()<> numberOfRates");
        QL_REQUIRE(accruals.size()==numberRates_,
            "accruals.size()<> numberOfRates");
        std::fill(strikes_.begin(), strikes_.end(),strike);
        evolution_ = EvolutionDescription(rateTimes,evolTimes);
    }
virtual QuantLib::MarketModelPathwiseMultiDeflatedCaplet::~MarketModelPathwiseMultiDeflatedCaplet () [inline, virtual]
Definition at line 106 of file pathwiseproductcaplet.hpp.
{}
Member Function Documentation
bool QuantLib::MarketModelPathwiseMultiDeflatedCaplet::alreadyDeflated () const [virtual]
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 139 of file pathwiseproductcaplet.cpp.
Referenced by QuantLib::MarketModelPathwiseMultiDeflatedCap::alreadyDeflated().
    {
        return true;
    }
std::auto_ptr< MarketModelPathwiseMultiProduct > QuantLib::MarketModelPathwiseMultiDeflatedCaplet::clone () const [virtual]
returns a newly-allocated copy of itself
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 242 of file pathwiseproductcaplet.cpp.
References MarketModelPathwiseMultiDeflatedCaplet().
Referenced by MarketModelTest::testPathwiseGreeks(), and MarketModelTest::testPathwiseVegas().
    {
        return std::auto_ptr<MarketModelPathwiseMultiProduct>(
            new MarketModelPathwiseMultiDeflatedCaplet(*this));
    }
const EvolutionDescription & QuantLib::MarketModelPathwiseMultiDeflatedCaplet::evolution () const [virtual]
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 257 of file pathwiseproductcaplet.cpp.
References evolution_.
Referenced by QuantLib::MarketModelPathwiseMultiDeflatedCap::evolution().
    {
        return evolution_;
    }
Size QuantLib::MarketModelPathwiseMultiDeflatedCaplet::maxNumberOfCashFlowsPerProductPerStep () const [virtual]
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 272 of file pathwiseproductcaplet.cpp.
Referenced by QuantLib::MarketModelPathwiseMultiDeflatedCap::MarketModelPathwiseMultiDeflatedCap(), and QuantLib::MarketModelPathwiseMultiDeflatedCap::maxNumberOfCashFlowsPerProductPerStep().
    {
        return 1;
    }
bool QuantLib::MarketModelPathwiseMultiDeflatedCaplet::nextTimeStep (const CurveState & currentState, std::vector< Size > & numberCashFlowsThisStep, std::vector< std::vector< MarketModelPathwiseMultiProduct::CashFlow > > & cashFlowsGenerated) [virtual]
return value indicates whether path is finished, TRUE means done
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 210 of file pathwiseproductcaplet.cpp.
References accruals_, currentIndex_, QuantLib::CurveState::discountRatio(), QuantLib::CurveState::forwardRate(), numberRates_, and strikes_.
Referenced by QuantLib::MarketModelPathwiseMultiDeflatedCap::nextTimeStep().
    {
        Rate liborRate = currentState.forwardRate(currentIndex_);
        cashFlowsGenerated[currentIndex_][0].timeIndex = currentIndex_;
        cashFlowsGenerated[currentIndex_][0].amount[0] =
            (liborRate-strikes_[currentIndex_])*accruals_[currentIndex_]*currentState.discountRatio(currentIndex_+1,0);
        std::fill(numberCashFlowsThisStep.begin(),
            numberCashFlowsThisStep.end(),0);
        if (  cashFlowsGenerated[currentIndex_][0].amount[0]  >0)
        {
            numberCashFlowsThisStep[currentIndex_] = 1;
            for (Size i=1; i <= numberRates_; ++i)
                cashFlowsGenerated[currentIndex_][0].amount[i] =0;
            cashFlowsGenerated[currentIndex_][0].amount[currentIndex_+1]  = accruals_[currentIndex_]*currentState.discountRatio(currentIndex_+1,0);
            for (Size i=0; i <= currentIndex_; ++i)
            {
                Real stepDF = currentState.discountRatio(i+1,i);
                cashFlowsGenerated[currentIndex_][0].amount[i+1] -=   accruals_[i]*stepDF
                    *cashFlowsGenerated[currentIndex_][0].amount[0];
            }
        }
        ++currentIndex_;
        return (currentIndex_ == strikes_.size());
    }
Size QuantLib::MarketModelPathwiseMultiDeflatedCaplet::numberOfProducts () const [virtual]
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 267 of file pathwiseproductcaplet.cpp.
References numberRates_.
    {
        return numberRates_;
    }
std::vector< Time > QuantLib::MarketModelPathwiseMultiDeflatedCaplet::possibleCashFlowTimes () const [virtual]
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 262 of file pathwiseproductcaplet.cpp.
References paymentTimes_.
Referenced by QuantLib::MarketModelPathwiseMultiDeflatedCap::possibleCashFlowTimes().
    {
        return paymentTimes_;
    }
void QuantLib::MarketModelPathwiseMultiDeflatedCaplet::reset () [virtual]
during simulation put product at start of path
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 278 of file pathwiseproductcaplet.cpp.
References currentIndex_.
Referenced by QuantLib::MarketModelPathwiseMultiDeflatedCap::reset().
    {
        currentIndex_=0;
    }
std::vector< Size > QuantLib::MarketModelPathwiseMultiDeflatedCaplet::suggestedNumeraires () const [virtual]
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 248 of file pathwiseproductcaplet.cpp.
References numberRates_.
Referenced by QuantLib::MarketModelPathwiseMultiDeflatedCap::suggestedNumeraires().
    {
        std::vector<Size> numeraires(numberRates_);
        for (Size i=0; i < numberRates_; ++i)
            numeraires[i] = i;
        return numeraires;
    }
Member Data Documentation
std::vector<Real> QuantLib::MarketModelPathwiseMultiDeflatedCaplet::accruals_ [private]
Definition at line 133 of file pathwiseproductcaplet.hpp.
Referenced by nextTimeStep().
Size QuantLib::MarketModelPathwiseMultiDeflatedCaplet::currentIndex_ [private]
Definition at line 138 of file pathwiseproductcaplet.hpp.
Referenced by nextTimeStep(), and reset().
EvolutionDescription QuantLib::MarketModelPathwiseMultiDeflatedCaplet::evolution_ [private]
Definition at line 140 of file pathwiseproductcaplet.hpp.
Referenced by evolution(), and MarketModelPathwiseMultiDeflatedCaplet().
Size QuantLib::MarketModelPathwiseMultiDeflatedCaplet::numberRates_ [private]
Definition at line 136 of file pathwiseproductcaplet.hpp.
Referenced by MarketModelPathwiseMultiDeflatedCaplet(), nextTimeStep(), numberOfProducts(), and suggestedNumeraires().
std::vector<Time> QuantLib::MarketModelPathwiseMultiDeflatedCaplet::paymentTimes_ [private]
Definition at line 134 of file pathwiseproductcaplet.hpp.
Referenced by possibleCashFlowTimes().
std::vector<Real> QuantLib::MarketModelPathwiseMultiDeflatedCaplet::rateTimes_ [private]
Definition at line 132 of file pathwiseproductcaplet.hpp.
Referenced by MarketModelPathwiseMultiDeflatedCaplet().
std::vector<Rate> QuantLib::MarketModelPathwiseMultiDeflatedCaplet::strikes_ [private]
Definition at line 135 of file pathwiseproductcaplet.hpp.
Referenced by MarketModelPathwiseMultiDeflatedCaplet(), and nextTimeStep().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/products/pathwise/pathwiseproductcaplet.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/products/pathwise/pathwiseproductcaplet.cpp