QuantLib: QuantLib::DividendVanillaOption Class Reference
QuantLib::DividendVanillaOption Class Reference
Single-asset vanilla option (no barriers) with discrete dividends.
#include <dividendvanillaoption.hpp>
Classes
class arguments
Arguments for dividend vanilla option calculation
class engine
Dividend-vanilla-option engine base class
Public Member Functions
DividendVanillaOption (const boost::shared_ptr< StrikedTypePayoff > &payoff, const boost::shared_ptr< Exercise > &exercise, const std::vector< Date > &dividendDates, const std::vector< Real > &dividends)
Volatility impliedVolatility (Real price, const boost::shared_ptr< GeneralizedBlackScholesProcess > &process, Real accuracy=1.0e-4, Size maxEvaluations=100, Volatility minVol=1.0e-7, Volatility maxVol=4.0) const
Protected Member Functions
void setupArguments (PricingEngine::arguments *) const
Private Attributes
DividendSchedule cashFlow_
Detailed Description
Single-asset vanilla option (no barriers) with discrete dividends.
Definition at line 37 of file dividendvanillaoption.hpp.
Constructor & Destructor Documentation
QuantLib::DividendVanillaOption::DividendVanillaOption (const boost::shared_ptr< StrikedTypePayoff > & payoff, const boost::shared_ptr< Exercise > & exercise, const std::vector< Date > & dividendDates, const std::vector< Real > & dividends)
Definition at line 31 of file dividendvanillaoption.cpp.
    : OneAssetOption(payoff, exercise),
      cashFlow_(DividendVector(dividendDates, dividends)) {}
Member Function Documentation
Volatility QuantLib::DividendVanillaOption::impliedVolatility (Real price, const boost::shared_ptr< GeneralizedBlackScholesProcess > & process, Real accuracy = 1.0e-4, Size maxEvaluations = 100, Volatility minVol = 1.0e-7, Volatility maxVol = 4.0) const
Warning:
see VanillaOption for notes on implied-volatility calculation.
Definition at line 40 of file dividendvanillaoption.cpp.
References QuantLib::Exercise::American, QuantLib::Exercise::Bermudan, QuantLib::Instrument::calculate(), QuantLib::detail::ImpliedVolatilityHelper::clone(), QuantLib::Exercise::European, QuantLib::Option::exercise_, QuantLib::OneAssetOption::isExpired(), QL_FAIL, and QL_REQUIRE.
{
        QL_REQUIRE(!isExpired(), "option expired");
        boost::shared_ptr<SimpleQuote> volQuote(new SimpleQuote);
        boost::shared_ptr<GeneralizedBlackScholesProcess> newProcess =
            detail::ImpliedVolatilityHelper::clone(process, volQuote);
        // engines are built-in for the time being
        boost::scoped_ptr<PricingEngine> engine;
        switch (exercise_->type()) {
          case Exercise::European:
            engine.reset(new AnalyticDividendEuropeanEngine(newProcess));
            break;
          case Exercise::American:
            engine.reset(new FDDividendAmericanEngine<CrankNicolson>(
                                                                 newProcess));
            break;
          case Exercise::Bermudan:
            QL_FAIL("engine not available for Bermudan option with dividends");
            break;
          default:
            QL_FAIL("unknown exercise type");
        }
        return detail::ImpliedVolatilityHelper::calculate(*this,
                                                          *engine,
                                                          *volQuote,
                                                          targetValue,
                                                          accuracy,
                                                          maxEvaluations,
                                                          minVol, maxVol);
    }
void QuantLib::DividendVanillaOption::setupArguments (PricingEngine::arguments *) const [protected, virtual]
When a derived argument structure is defined for an instrument, this method should be overridden to fill it. This is mandatory in case a pricing engine is used.
Reimplemented from QuantLib::Option.
Definition at line 82 of file dividendvanillaoption.cpp.
References QuantLib::DividendVanillaOption::arguments::cashFlow, cashFlow_, and QL_REQUIRE.
{
        OneAssetOption::setupArguments(args);
        DividendVanillaOption::arguments* arguments =
            dynamic_cast<DividendVanillaOption::arguments*>(args);
        QL_REQUIRE(arguments != 0, "wrong engine type");
        arguments->cashFlow = cashFlow_;
    }
Member Data Documentation
DividendSchedule QuantLib::DividendVanillaOption::cashFlow_ [private]
Definition at line 59 of file dividendvanillaoption.hpp.
Referenced by setupArguments().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/dividendvanillaoption.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/dividendvanillaoption.cpp