QuantLib: SwapForwardMappingsTest Class Reference
SwapForwardMappingsTest Class Reference
#include <swapforwardmappings.hpp>
Static Public Member Functions
static void testSwaptionImpliedVolatility ()
static void testForwardSwapJacobians ()
static void testForwardCoterminalMappings ()
static
boost::unit_test_framework::test_suite * suite ()
Detailed Description
Definition at line 28 of file swapforwardmappings.hpp.
Member Function Documentation
test_suite * SwapForwardMappingsTest::suite () [static]
Definition at line 454 of file swapforwardmappings.cpp.
References QUANTLIB_TEST_CASE, testForwardCoterminalMappings(), testForwardSwapJacobians(), and testSwaptionImpliedVolatility().
Referenced by init_unit_test_suite().
{
    test_suite* suite = BOOST_TEST_SUITE("swap-forward mappings tests");
    suite->add(QUANTLIB_TEST_CASE(
        &SwapForwardMappingsTest::testSwaptionImpliedVolatility));
    suite->add(QUANTLIB_TEST_CASE(
        &SwapForwardMappingsTest::testForwardSwapJacobians));
#if !defined(QL_NO_UBLAS_SUPPORT)
    suite->add(QUANTLIB_TEST_CASE(
        &SwapForwardMappingsTest::testForwardCoterminalMappings));
#endif
    return suite;
}
void SwapForwardMappingsTest::testForwardCoterminalMappings () [static]
Definition at line 297 of file swapforwardmappings.cpp.
References anonymous_namespace{marketmodel.cpp}::beta, QuantLib::Option::Call, QuantLib::LMMCurveState::coterminalSwapAnnuity(), QuantLib::LMMCurveState::coterminalSwapRates(), QuantLib::SwapForwardMappings::coterminalSwapZedMatrix(), QuantLib::SobolBrownianGenerator::Diagonal, anonymous_namespace{marketmodel.cpp}::displacement, QuantLib::MultiProductMultiStep::evolution(), QuantLib::exponentialCorrelations(), anonymous_namespace{swapforwardmappings.cpp}::makeMultiStepCoterminalSwaptions(), QuantLib::EvolutionDescription::rateTimes(), anonymous_namespace{marketmodel.cpp}::rateTimes, QuantLib::LMMCurveState::setOnForwardRates(), anonymous_namespace{marketmodel.cpp}::simulate(), anonymous_namespace{marketmodel.cpp}::todaysCoterminalSwapRates, and anonymous_namespace{marketmodel.cpp}::todaysDiscounts.
Referenced by suite().
{
    BOOST_MESSAGE("Testing forward-rate coterminal-swap mappings...");
    MarketModelData marketData;
    const std::vector<Time>& rateTimes = marketData.rateTimes();
    const std::vector<Rate>& forwards = marketData.forwards();
    const Size nbRates = marketData.nbRates();
    LMMCurveState lmmCurveState(rateTimes);
    lmmCurveState.setOnForwardRates(forwards);
    const Real longTermCorr=0.5;
    const Real beta = .2;
    Real strike = .03;
    MultiStepCoterminalSwaptions product
        = makeMultiStepCoterminalSwaptions(rateTimes, strike);
    const EvolutionDescription evolution = product.evolution();
    const Size numberOfFactors = nbRates;
    Spread displacement = marketData.displacements().front();
    Matrix jacobian =
        SwapForwardMappings::coterminalSwapZedMatrix(
        lmmCurveState, displacement);
    Matrix correlations = exponentialCorrelations(evolution.rateTimes(),
        longTermCorr,
        beta);
    boost::shared_ptr<PiecewiseConstantCorrelation> corr(new
        TimeHomogeneousForwardCorrelation(correlations,
        rateTimes));
    boost::shared_ptr<MarketModel> smmMarketModel(new
        FlatVol(marketData.volatilities(),
        corr,
        evolution,
        numberOfFactors,
        lmmCurveState.coterminalSwapRates(),
        marketData.displacements()));
    boost::shared_ptr<MarketModel>
        lmmMarketModel(new CotSwapToFwdAdapter(smmMarketModel));
    SobolBrownianGeneratorFactory generatorFactory(SobolBrownianGenerator::Diagonal);
    std::vector<Size> numeraires(nbRates,
        nbRates);
    boost::shared_ptr<MarketModelEvolver> evolver(new LogNormalFwdRatePc
        (lmmMarketModel, generatorFactory, numeraires));
    boost::shared_ptr<SequenceStatisticsInc> stats =
        simulate(marketData.discountFactors(), evolver, product);
    std::vector<Real> results = stats->mean();
    std::vector<Real> errors = stats->errorEstimate();
    const std::vector<DiscountFactor>& todaysDiscounts = marketData.discountFactors();
    const std::vector<Rate>& todaysCoterminalSwapRates = lmmCurveState.coterminalSwapRates();
    for (Size i=0; i<nbRates; ++i) {
        const Matrix& cotSwapsCovariance = smmMarketModel->totalCovariance(i);
        //Matrix cotSwapsCovariance= jacobian * forwardsCovariance * transpose(jacobian);
        //Time expiry = rateTimes[i];
        boost::shared_ptr<PlainVanillaPayoff> payoff(
            new PlainVanillaPayoff(Option::Call, strike+displacement));
        //const std::vector<Time>&  taus = lmmCurveState.rateTaus();
        Real expectedSwaption = BlackCalculator(payoff,
            todaysCoterminalSwapRates[i]+displacement,
            std::sqrt(cotSwapsCovariance[i][i]),
            lmmCurveState.coterminalSwapAnnuity(i,i) *
            todaysDiscounts[i]).value();
        if (false)
            BOOST_MESSAGE(
            "expected\t" << expectedSwaption <<
            "\tLMM\t" << results[i]
        << "\tstdev:\t" << errors[i] <<
            "\t" <<std::fabs(results[i]- expectedSwaption)/errors[i]);
    }
}
void SwapForwardMappingsTest::testForwardSwapJacobians () [static]
Definition at line 185 of file swapforwardmappings.cpp.
References QuantLib::SwapForwardMappings::cmSwapForwardJacobian(), QuantLib::LMMCurveState::cmSwapRate(), QuantLib::SwapForwardMappings::coinitialSwapForwardJacobian(), anonymous_namespace{marketmodel.cpp}::rateTimes, QuantLib::LMMCurveState::setOnForwardRates(), and anonymous_namespace{marketmodel_cms.cpp}::spanningForwards.
Referenced by suite().
{
    {
        BOOST_MESSAGE("Testing forward-rate coinitial-swap Jacobian...");
        MarketModelData marketData;
        const std::vector<Time>& rateTimes = marketData.rateTimes();
        const std::vector<Rate>& forwards = marketData.forwards();
        const Size nbRates = marketData.nbRates();
        LMMCurveState lmmCurveState(rateTimes);
        lmmCurveState.setOnForwardRates(forwards);
        Real bumpSize = 1e-8;
        std::vector<Rate> bumpedForwards(forwards);
        Matrix coinitialJacobian(nbRates,nbRates);
        for (Size i=0; i < nbRates; ++i)
            for (Size j=0; j < nbRates; ++j)
            {
                bumpedForwards = forwards;
                bumpedForwards[j]+= bumpSize;
                lmmCurveState.setOnForwardRates(bumpedForwards);
                Real upRate = lmmCurveState.cmSwapRate(0,i+1);
                bumpedForwards[j]-= 2.0*bumpSize;
                lmmCurveState.setOnForwardRates(bumpedForwards);
                Real downRate = lmmCurveState.cmSwapRate(0,i+1);
                Real deriv = (upRate-downRate)/(2.0*bumpSize);
                coinitialJacobian[i][j] = deriv;
            }
            Matrix modelJacobian(SwapForwardMappings::coinitialSwapForwardJacobian(lmmCurveState));
            Real errorTolerance = 1e-5;
            for (Size i=0; i < nbRates; ++i)
                for (Size j=0; j < nbRates; ++j)
                    if( fabs(modelJacobian[i][j]-coinitialJacobian[i][j]) > errorTolerance)
                    {
                        BOOST_MESSAGE(
                            "rate " << i
                            << ", sensitivity "  <<  j
                            << ", formula value " << modelJacobian[i][j]
                        << " bumping value " << coinitialJacobian[i][j]
                        <<  "\n");
                        BOOST_ERROR("test failed");
                    }
    }
    {
        BOOST_MESSAGE("Testing forward-rate constant-maturity swap Jacobian...");
        MarketModelData marketData;
        const std::vector<Time>& rateTimes = marketData.rateTimes();
        const std::vector<Rate>& forwards = marketData.forwards();
        const Size nbRates = marketData.nbRates();
        LMMCurveState lmmCurveState(rateTimes);
        lmmCurveState.setOnForwardRates(forwards);
        Real bumpSize = 1e-8;
        for( Size spanningForwards = 1; spanningForwards < nbRates; ++spanningForwards)
        {
            std::vector<Rate> bumpedForwards(forwards);
            Matrix cmsJacobian(nbRates,nbRates);
            for (Size i=0; i < nbRates; ++i)
                for (Size j=0; j < nbRates; ++j)
                {
                    bumpedForwards = forwards;
                    bumpedForwards[j]+= bumpSize;
                    lmmCurveState.setOnForwardRates(bumpedForwards);
                    Real upRate = lmmCurveState.cmSwapRate(i,spanningForwards);
                    bumpedForwards[j]-= 2.0*bumpSize;
                    lmmCurveState.setOnForwardRates(bumpedForwards);
                    Real downRate = lmmCurveState.cmSwapRate(i,spanningForwards);
                    Real deriv = (upRate-downRate)/(2.0*bumpSize);
                    cmsJacobian[i][j] = deriv;
                }
                Matrix modelJacobian(SwapForwardMappings::cmSwapForwardJacobian(lmmCurveState, spanningForwards));
                Real errorTolerance = 1e-5;
                for (Size i=0; i < nbRates; ++i)
                    for (Size j=0; j < nbRates; ++j)
                        if( fabs(modelJacobian[i][j]-cmsJacobian[i][j]) > errorTolerance)
{
                            BOOST_MESSAGE(
                                "rate " << i
                                << ", sensitivity "  <<  j
                                << ", formula value " << modelJacobian[i][j]
                            << " bumping value " << cmsJacobian[i][j]
                            <<  "\n");
                            BOOST_ERROR("test failed");
                        }
        }
    }
}
void SwapForwardMappingsTest::testSwaptionImpliedVolatility () [static]
Definition at line 371 of file swapforwardmappings.cpp.
References anonymous_namespace{marketmodel.cpp}::beta, QuantLib::Option::Call, QuantLib::LMMCurveState::cmSwapAnnuity(), QuantLib::LMMCurveState::cmSwapRate(), QuantLib::SwapForwardMappings::coterminalSwapZedMatrix(), QuantLib::SobolBrownianGenerator::Diagonal, anonymous_namespace{marketmodel.cpp}::displacement, QuantLib::MultiProductMultiStep::evolution(), QuantLib::exponentialCorrelations(), QuantLib::LMMCurveState::forwardRates(), QuantLib::EvolutionDescription::rateTimes(), anonymous_namespace{marketmodel.cpp}::rateTimes, QuantLib::LMMCurveState::setOnForwardRates(), anonymous_namespace{marketmodel.cpp}::simulate(), QuantLib::SwapForwardMappings::swaptionImpliedVolatility(), and QuantLib::BlackCalculator::value().
Referenced by suite().
{
    BOOST_MESSAGE("Testing implied swaption vol in LMM using HW approximation...");
    MarketModelData marketData;
    const std::vector<Time>& rateTimes = marketData.rateTimes();
    const std::vector<Rate>& forwards = marketData.forwards();
    const Size nbRates = marketData.nbRates();
    LMMCurveState lmmCurveState(rateTimes);
    lmmCurveState.setOnForwardRates(forwards);
    const Real longTermCorr=0.5;
    const Real beta = .2;
    Real strike = .03;
    for (Size startIndex = 1; startIndex+2 < nbRates; startIndex = startIndex+5)
    {
        Size endIndex = nbRates-2;
        boost::shared_ptr<StrikedTypePayoff> payoff(new
            PlainVanillaPayoff(Option::Call, strike));
        MultiStepSwaption product(rateTimes, startIndex, endIndex,payoff );
        const EvolutionDescription evolution = product.evolution();
        const Size numberOfFactors = nbRates;
        Spread displacement = marketData.displacements().front();
        Matrix jacobian =
            SwapForwardMappings::coterminalSwapZedMatrix(
            lmmCurveState, displacement);
        Matrix correlations = exponentialCorrelations(evolution.rateTimes(),
            longTermCorr,
            beta);
        boost::shared_ptr<PiecewiseConstantCorrelation> corr(new
            TimeHomogeneousForwardCorrelation(correlations,
            rateTimes));
        boost::shared_ptr<MarketModel> lmmMarketModel(new
            FlatVol(marketData.volatilities(),
            corr,
            evolution,
            numberOfFactors,
            lmmCurveState.forwardRates(),
            marketData.displacements()));
        SobolBrownianGeneratorFactory generatorFactory(SobolBrownianGenerator::Diagonal);
        std::vector<Size> numeraires(nbRates,
            nbRates);
        boost::shared_ptr<MarketModelEvolver> evolver(new LogNormalFwdRatePc
            (lmmMarketModel, generatorFactory, numeraires));
        boost::shared_ptr<SequenceStatisticsInc> stats =
            simulate(marketData.discountFactors(), evolver, product);
        std::vector<Real> results = stats->mean();
        std::vector<Real> errors = stats->errorEstimate();
        Real estimatedImpliedVol = SwapForwardMappings::swaptionImpliedVolatility(*lmmMarketModel,startIndex,endIndex);
        Real swapRate = lmmCurveState.cmSwapRate(startIndex,endIndex-startIndex);
        Real swapAnnuity = lmmCurveState.cmSwapAnnuity(startIndex,startIndex,endIndex-startIndex)*marketData.discountFactors()[startIndex];
        boost::shared_ptr<PlainVanillaPayoff> payoffDis( new PlainVanillaPayoff(Option::Call, strike+displacement));
        Real expectedSwaption = BlackCalculator(payoffDis,
            swapRate+displacement, estimatedImpliedVol *sqrt(rateTimes[startIndex]),
            swapAnnuity).value();
        Real error = expectedSwaption - results[0];
        Real errorInSds = error/errors[0];
        if (fabs(errorInSds) > 3.5 )
            BOOST_ERROR(
            "expected\t" << expectedSwaption <<
            "\tLMM\t" << results[0]
        << "\tstdev:\t" << errors[0] <<
            "\t" <<errorInSds);
    }
}
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/swapforwardmappings.hpp
/home/deriversatile/QuantLib/QuantLibQt/test-suite/swapforwardmappings.cpp