QuantLib: QuantLib::MarketModel Class Reference
QuantLib::MarketModel Class Reference
base class for market models
#include <marketmodel.hpp>
Public Member Functions
virtual ~MarketModel ()
virtual const std::vector< Rate > & initialRates () const =0
virtual const std::vector
< Spread > & displacements () const =0
virtual const
EvolutionDescription & evolution () const =0
virtual Size numberOfRates () const =0
virtual Size numberOfFactors () const =0
virtual Size numberOfSteps () const =0
virtual const Matrix & pseudoRoot (Size i) const =0
virtual const Matrix & covariance (Size i) const
virtual const Matrix & totalCovariance (Size endIndex) const
std::vector< Volatility > timeDependentVolatility (Size i) const
Private Attributes
std::vector< Matrix > covariance_
std::vector< Matrix > totalCovariance_
Detailed Description
base class for market models
For each time step, generates the pseudo-square root of the covariance matrix for that time step.
Definition at line 39 of file marketmodel.hpp.
Constructor & Destructor Documentation
virtual QuantLib::MarketModel::~MarketModel () [inline, virtual]
Definition at line 41 of file marketmodel.hpp.
{}
Member Function Documentation
const Matrix & QuantLib::MarketModel::covariance (Size i) const [virtual]
Definition at line 28 of file marketmodel.cpp.
References covariance_, numberOfSteps(), pseudoRoot(), QL_REQUIRE, and QuantLib::transpose().
Referenced by QuantLib::AbcdVol::AbcdVol(), QuantLib::FlatVol::FlatVol(), QuantLib::rateInstVolDifferences(), timeDependentVolatility(), and totalCovariance().
{
        if (covariance_.empty()) {
            covariance_.resize(numberOfSteps());
            for (Size j=0; j<numberOfSteps(); ++j)
                covariance_[j] = pseudoRoot(j) * transpose(pseudoRoot(j));
        }
        QL_REQUIRE(i<covariance_.size(),
                   "i (" << i <<
                   ") must be less than covariance_.size() (" << covariance_.size() << ")")
        return covariance_[i];
    }
virtual const std::vector<Spread>& QuantLib::MarketModel::displacements () const [pure virtual]
Implemented in QuantLib::AbcdVol, QuantLib::FlatVol, QuantLib::PseudoRootFacade, QuantLib::FwdPeriodAdapter, QuantLib::CotSwapToFwdAdapter, and QuantLib::FwdToCotSwapAdapter.
Referenced by QuantLib::SwapForwardMappings::swaptionImpliedVolatility().
virtual const EvolutionDescription& QuantLib::MarketModel::evolution () const [pure virtual]
Implemented in QuantLib::AbcdVol, QuantLib::FlatVol, QuantLib::PseudoRootFacade, QuantLib::FwdPeriodAdapter, QuantLib::CotSwapToFwdAdapter, and QuantLib::FwdToCotSwapAdapter.
Referenced by QuantLib::rateInstVolDifferences(), QuantLib::rateVolDifferences(), QuantLib::SwapForwardMappings::swaptionImpliedVolatility(), and timeDependentVolatility().
virtual const std::vector<Rate>& QuantLib::MarketModel::initialRates () const [pure virtual]
Implemented in QuantLib::AbcdVol, QuantLib::FlatVol, QuantLib::PseudoRootFacade, QuantLib::FwdPeriodAdapter, QuantLib::CotSwapToFwdAdapter, and QuantLib::FwdToCotSwapAdapter.
Referenced by QuantLib::rateInstVolDifferences(), QuantLib::rateVolDifferences(), and QuantLib::SwapForwardMappings::swaptionImpliedVolatility().
virtual Size QuantLib::MarketModel::numberOfFactors () const [pure virtual]
Implemented in QuantLib::AbcdVol, QuantLib::FlatVol, QuantLib::PseudoRootFacade, QuantLib::FwdPeriodAdapter, QuantLib::CotSwapToFwdAdapter, and QuantLib::FwdToCotSwapAdapter.
Referenced by QuantLib::SwapForwardMappings::swaptionImpliedVolatility().
virtual Size QuantLib::MarketModel::numberOfRates () const [pure virtual]
Implemented in QuantLib::AbcdVol, QuantLib::FlatVol, QuantLib::PseudoRootFacade, QuantLib::FwdPeriodAdapter, QuantLib::CotSwapToFwdAdapter, and QuantLib::FwdToCotSwapAdapter.
Referenced by timeDependentVolatility().
virtual Size QuantLib::MarketModel::numberOfSteps () const [pure virtual]
Implemented in QuantLib::AbcdVol, QuantLib::FlatVol, QuantLib::PseudoRootFacade, QuantLib::FwdPeriodAdapter, QuantLib::CotSwapToFwdAdapter, and QuantLib::FwdToCotSwapAdapter.
Referenced by covariance(), QuantLib::rateVolDifferences(), timeDependentVolatility(), and totalCovariance().
virtual const Matrix& QuantLib::MarketModel::pseudoRoot (Size i) const [pure virtual]
Implemented in QuantLib::AbcdVol, QuantLib::FlatVol, QuantLib::PseudoRootFacade, QuantLib::FwdPeriodAdapter, QuantLib::CotSwapToFwdAdapter, and QuantLib::FwdToCotSwapAdapter.
Referenced by covariance(), and QuantLib::SwapForwardMappings::swaptionImpliedVolatility().
std::vector< Volatility > QuantLib::MarketModel::timeDependentVolatility (Size i) const
Definition at line 55 of file marketmodel.cpp.
References covariance(), evolution(), QuantLib::EvolutionDescription::evolutionTimes(), numberOfRates(), numberOfSteps(), and QL_REQUIRE.
   {
        QL_REQUIRE(i<numberOfRates(),
                   "index (" << i << ") must less than number of rates (" <<
                   numberOfRates() << ")");
        std::vector<Volatility> result(numberOfSteps());
        const std::vector<Time>& evolutionTime = evolution().evolutionTimes();
        Time lastTime=0.0;
        for (Size j=0; j<numberOfSteps(); ++j) {
            Time tau = evolutionTime[j]-lastTime;
            Real thisVariance = covariance(j)[i][i];
            Real thisVol = std::sqrt(thisVariance/tau);
            result[j] = thisVol;
            lastTime =  evolutionTime[j];
        }
        return result;
   }
const Matrix & QuantLib::MarketModel::totalCovariance (Size endIndex) const [virtual]
Definition at line 40 of file marketmodel.cpp.
References covariance(), covariance_, numberOfSteps(), QL_REQUIRE, and totalCovariance_.
Referenced by QuantLib::CTSMMCapletCalibration::calibrate(), and QuantLib::rateVolDifferences().
{
        if (totalCovariance_.empty()) {
            totalCovariance_.resize(numberOfSteps());
            // call to covariance(0) triggers calculation, if necessary
            // while covariance_[0] would not
            totalCovariance_[0] = covariance(0);
            for (Size j=1; j<numberOfSteps(); ++j)
                totalCovariance_[j] = totalCovariance_[j-1] + covariance_[j];
        }
        QL_REQUIRE(endIndex<covariance_.size(),
                   "endIndex (" << endIndex <<
                   ") must be less than covariance_.size() (" << covariance_.size() << ")")
        return totalCovariance_[endIndex];
    }
Member Data Documentation
std::vector<Matrix> QuantLib::MarketModel::covariance_ [mutable, private]
Definition at line 53 of file marketmodel.hpp.
Referenced by covariance(), and totalCovariance().
std::vector<Matrix> QuantLib::MarketModel::totalCovariance_ [mutable, private]
Definition at line 53 of file marketmodel.hpp.
Referenced by totalCovariance().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/marketmodel.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/marketmodel.cpp