QuantLib: QuantLib::BarrierOption Class Reference
QuantLib::BarrierOption Class Reference
Barrier option on a single asset.
#include <barrieroption.hpp>
Classes
class arguments
Arguments for barrier option calculation
class engine
Barrier-option engine base class
Public Member Functions
BarrierOption (Barrier::Type barrierType, Real barrier, Real rebate, const boost::shared_ptr< StrikedTypePayoff > &payoff, const boost::shared_ptr< Exercise > &exercise)
void setupArguments (PricingEngine::arguments *) const
Volatility impliedVolatility (Real price, const boost::shared_ptr< GeneralizedBlackScholesProcess > &process, Real accuracy=1.0e-4, Size maxEvaluations=100, Volatility minVol=1.0e-7, Volatility maxVol=4.0) const
Protected Attributes
Barrier::Type barrierType_
Real barrier_
Real rebate_
Detailed Description
Barrier option on a single asset.
The analytic pricing engine will be used if none if passed.
Definition at line 42 of file barrieroption.hpp.
Constructor & Destructor Documentation
QuantLib::BarrierOption::BarrierOption (Barrier::Type barrierType, Real barrier, Real rebate, const boost::shared_ptr< StrikedTypePayoff > & payoff, const boost::shared_ptr< Exercise > & exercise)
Definition at line 30 of file barrieroption.cpp.
    : OneAssetOption(payoff, exercise),
      barrierType_(barrierType), barrier_(barrier), rebate_(rebate) {}
Member Function Documentation
Volatility QuantLib::BarrierOption::impliedVolatility (Real price, const boost::shared_ptr< GeneralizedBlackScholesProcess > & process, Real accuracy = 1.0e-4, Size maxEvaluations = 100, Volatility minVol = 1.0e-7, Volatility maxVol = 4.0) const
Warning:
see VanillaOption for notes on implied-volatility calculation.
Definition at line 52 of file barrieroption.cpp.
References QuantLib::Exercise::American, QuantLib::Exercise::Bermudan, QuantLib::Instrument::calculate(), QuantLib::detail::ImpliedVolatilityHelper::clone(), QuantLib::Exercise::European, QuantLib::Option::exercise_, QuantLib::OneAssetOption::isExpired(), QL_FAIL, and QL_REQUIRE.
{
        QL_REQUIRE(!isExpired(), "option expired");
        boost::shared_ptr<SimpleQuote> volQuote(new SimpleQuote);
        boost::shared_ptr<GeneralizedBlackScholesProcess> newProcess =
            detail::ImpliedVolatilityHelper::clone(process, volQuote);
        // engines are built-in for the time being
        boost::scoped_ptr<PricingEngine> engine;
        switch (exercise_->type()) {
          case Exercise::European:
            engine.reset(new AnalyticBarrierEngine(newProcess));
            break;
          case Exercise::American:
          case Exercise::Bermudan:
            QL_FAIL("engine not available for non-European barrier option");
            break;
          default:
            QL_FAIL("unknown exercise type");
        }
        return detail::ImpliedVolatilityHelper::calculate(*this,
                                                          *engine,
                                                          *volQuote,
                                                          targetValue,
                                                          accuracy,
                                                          maxEvaluations,
                                                          minVol, maxVol);
    }
void QuantLib::BarrierOption::setupArguments (PricingEngine::arguments *) const [virtual]
When a derived argument structure is defined for an instrument, this method should be overridden to fill it. This is mandatory in case a pricing engine is used.
Reimplemented from QuantLib::Option.
Reimplemented in QuantLib::DividendBarrierOption.
Definition at line 39 of file barrieroption.cpp.
References QuantLib::BarrierOption::arguments::barrier, barrier_, QuantLib::BarrierOption::arguments::barrierType, barrierType_, QL_REQUIRE, QuantLib::BarrierOption::arguments::rebate, and rebate_.
{
        OneAssetOption::setupArguments(args);
        BarrierOption::arguments* moreArgs =
            dynamic_cast<BarrierOption::arguments*>(args);
        QL_REQUIRE(moreArgs != 0, "wrong argument type");
        moreArgs->barrierType = barrierType_;
        moreArgs->barrier = barrier_;
        moreArgs->rebate = rebate_;
    }
Member Data Documentation
Real QuantLib::BarrierOption::barrier_ [protected]
Definition at line 65 of file barrieroption.hpp.
Referenced by setupArguments().
Barrier::Type QuantLib::BarrierOption::barrierType_ [protected]
Definition at line 64 of file barrieroption.hpp.
Referenced by setupArguments().
Real QuantLib::BarrierOption::rebate_ [protected]
Definition at line 66 of file barrieroption.hpp.
Referenced by setupArguments().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/barrieroption.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/barrieroption.cpp