QuantLib: QuantLib::LsmBasisSystem Class Reference
QuantLib::LsmBasisSystem Class Reference
#include <lsmbasissystem.hpp>
Public Types
enum PolynomType {
Monomial, Laguerre, Hermite, Hyperbolic,
Legendre, Chebyshev, Chebyshev2nd
}
Static Public Member Functions
static std::vector
< boost::function1< Real, Real > > pathBasisSystem (Size order, PolynomType polyType)
static std::vector
< boost::function1< Real,
Array > > multiPathBasisSystem (Size dim, Size order, PolynomType polyType)
Detailed Description
Definition at line 37 of file lsmbasissystem.hpp.
Member Enumeration Documentation
enum QuantLib::LsmBasisSystem::PolynomType
Enumerator:
Monomial
Laguerre
Hermite
Hyperbolic
Legendre
Chebyshev
Chebyshev2nd
Definition at line 39 of file lsmbasissystem.hpp.
                         { Monomial, Laguerre, Hermite, Hyperbolic,
                           Legendre, Chebyshev, Chebyshev2nd };
Member Function Documentation
VF_A QuantLib::LsmBasisSystem::multiPathBasisSystem (Size dim, Size order, PolynomType polyType) [static]
Definition at line 144 of file lsmbasissystem.cpp.
References QuantLib::anonymous_namespace{lsmbasissystem.cpp}::next_order_tuples(), pathBasisSystem(), and QL_REQUIRE.
Referenced by anonymous_namespace{mclongstaffschwartzengine.cpp}::AmericanMaxPathPricer::basisSystem(), and VPPTest::testVPPPricing().
{
        QL_REQUIRE(dim>0, "zero dimension");
        // get single factor basis
        VF_R pathBasis = pathBasisSystem(order, polyType);
        VF_A ret;
        // 0-th order term
        VF_R term(dim, pathBasis[0]);
        ret.push_back(MultiDimFct(term));
        // start with all 0 tuple
        VV tuples(1, std::vector<Size>(dim));
        // add multi-factor terms
        for(Size i=1; i<=order; ++i) {
            tuples = next_order_tuples(tuples);
            // now we have all tuples of order i
            // for each tuple add the corresponding term
            for(Size j=0; j<tuples.size(); ++j) {
                for(Size k=0; k<dim; ++k)
                    term[k] = pathBasis[tuples[j][k]];
                ret.push_back(MultiDimFct(term));
            }
        }
        return ret;
    }
VF_R QuantLib::LsmBasisSystem::pathBasisSystem (Size order, PolynomType polyType) [static]
Definition at line 112 of file lsmbasissystem.cpp.
References Chebyshev, Chebyshev2nd, Hermite, Hyperbolic, Laguerre, Legendre, Monomial, QuantLib::anonymous_namespace{lsmbasissystem.cpp}::ptr_w, and QL_FAIL.
Referenced by multiPathBasisSystem().
{
        VF_R ret(order+1);
        for (Size i=0; i<=order; ++i) {
            switch (polyType) {
              case Monomial:
                ret[i] = MonomialFct(i);
                break;
              case Laguerre:
                ret[i] = boost::bind(ptr_w, GaussLaguerrePolynomial(), i, _1);
                break;
              case Hermite:
                ret[i] = boost::bind(ptr_w, GaussHermitePolynomial(), i, _1);
                break;
              case Hyperbolic:
                ret[i] = boost::bind(ptr_w, GaussHyperbolicPolynomial(), i, _1);
                break;
              case Legendre:
                ret[i] = boost::bind(ptr_w, GaussLegendrePolynomial(), i, _1);
                break;
              case Chebyshev:
                ret[i] = boost::bind(ptr_w, GaussChebyshevPolynomial(), i, _1);
                break;
              case Chebyshev2nd:
                ret[i] = boost::bind(ptr_w,GaussChebyshev2ndPolynomial(),i, _1);
                break;
              default:
                QL_FAIL("unknown regression type");
            }
        }
        return ret;
    }
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/montecarlo/lsmbasissystem.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/montecarlo/lsmbasissystem.cpp