QuantLib: StatisticsTest Class Reference
StatisticsTest Class Reference
#include <stats.hpp>
Static Public Member Functions
static void testStatistics ()
static void testSequenceStatistics ()
static void testConvergenceStatistics ()
static
boost::unit_test_framework::test_suite * suite ()
Detailed Description
Definition at line 29 of file stats.hpp.
Member Function Documentation
test_suite * StatisticsTest::suite () [static]
Definition at line 326 of file stats.cpp.
References QUANTLIB_TEST_CASE, testConvergenceStatistics(), testSequenceStatistics(), and testStatistics().
Referenced by init_unit_test_suite().
{
    test_suite* suite = BOOST_TEST_SUITE("Statistics tests");
    suite->add(QUANTLIB_TEST_CASE(&StatisticsTest::testStatistics));
    suite->add(QUANTLIB_TEST_CASE(&StatisticsTest::testSequenceStatistics));
    suite->add(QUANTLIB_TEST_CASE(&StatisticsTest::testConvergenceStatistics));
    return suite;
}
void StatisticsTest::testConvergenceStatistics () [static]
Definition at line 315 of file stats.cpp.
Referenced by suite().
{
    BOOST_MESSAGE("Testing convergence statistics...");
    checkConvergence<IncrementalStatistics>(
                              std::string("IncrementalStatistics"));
    checkConvergence<Statistics>(std::string("Statistics"));
}
void StatisticsTest::testSequenceStatistics () [static]
Definition at line 235 of file stats.cpp.
Referenced by suite().
{
    BOOST_MESSAGE("Testing sequence statistics...");
    checkSequence<IncrementalStatistics>(
        std::string("IncrementalStatistics"),5);
    checkSequence<Statistics>(std::string("Statistics"),5);
}
void StatisticsTest::testStatistics () [static]
Definition at line 115 of file stats.cpp.
Referenced by suite().
{
    BOOST_MESSAGE("Testing statistics...");
    check<IncrementalStatistics>(
        std::string("IncrementalStatistics"));
    check<Statistics>(std::string("Statistics"));
}
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/stats.hpp
/home/deriversatile/QuantLib/QuantLibQt/test-suite/stats.cpp