QuantLib: CliquetOptionTest Class Reference
CliquetOptionTest Class Reference
#include <cliquetoption.hpp>
Static Public Member Functions
static void testValues ()
static void testGreeks ()
static void testPerformanceGreeks ()
static void testMcPerformance ()
static
boost::unit_test_framework::test_suite * suite ()
Detailed Description
Definition at line 28 of file cliquetoption.hpp.
Member Function Documentation
test_suite * CliquetOptionTest::suite () [static]
Definition at line 373 of file cliquetoption.cpp.
References QUANTLIB_TEST_CASE, testGreeks(), testMcPerformance(), testPerformanceGreeks(), and testValues().
Referenced by init_unit_test_suite().
{
    test_suite* suite = BOOST_TEST_SUITE("Cliquet option tests");
    suite->add(QUANTLIB_TEST_CASE(&CliquetOptionTest::testValues));
    suite->add(QUANTLIB_TEST_CASE(&CliquetOptionTest::testGreeks));
    suite->add(QUANTLIB_TEST_CASE(&CliquetOptionTest::testPerformanceGreeks));
    suite->add(QUANTLIB_TEST_CASE(&CliquetOptionTest::testMcPerformance));
    return suite;
}
void CliquetOptionTest::testGreeks () [static]
Definition at line 264 of file cliquetoption.cpp.
Referenced by suite().
{
    BOOST_MESSAGE("Testing Cliquet option greeks...");
    testOptionGreeks<AnalyticCliquetEngine>();
}
void CliquetOptionTest::testMcPerformance () [static]
Definition at line 276 of file cliquetoption.cpp.
References QuantLib::Option::Call, anonymous_namespace{marketmodel.cpp}::d, QuantLib::Settings::evaluationDate(), QuantLib::flatRate(), QuantLib::flatVol(), QuantLib::Singleton< Settings >::instance(), LENGTH, anonymous_namespace{swaption.cpp}::lengths, QuantLib::Instrument::NPV(), QuantLib::Option::Put, QuantLib::Quarterly, REPORT_FAILURE, anonymous_namespace{inflationvolatility.cpp}::reset(), QuantLib::Semiannual, QuantLib::Instrument::setPricingEngine(), anonymous_namespace{marketmodel.cpp}::todaysDate, anonymous_namespace{gaussianquadratures.cpp}::tolerance, anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), QuantLib::MakeMCPerformanceEngine< RNG, S >::withAbsoluteTolerance(), and QuantLib::MakeMCPerformanceEngine< RNG, S >::withSeed().
Referenced by suite().
{
    BOOST_MESSAGE(
        "Testing Monte Carlo performance engine against analytic results...");
    SavedSettings backup;
    Option::Type types[] = { Option::Call, Option::Put };
    Real moneyness[] = { 0.9, 1.1 };
    Real underlyings[] = { 100.0 };
    Rate qRates[] = { 0.04, 0.06 };
    Rate rRates[] = { 0.01, 0.10 };
    Integer lengths[] = { 2, 4 };
    Frequency frequencies[] = { Semiannual, Quarterly };
    Volatility vols[] = { 0.10, 0.90 };
    DayCounter dc = Actual360();
    Date today = Date::todaysDate();
    Settings::instance().evaluationDate() = today;
    boost::shared_ptr<SimpleQuote> spot(new SimpleQuote(0.0));
    boost::shared_ptr<SimpleQuote> qRate(new SimpleQuote(0.0));
    Handle<YieldTermStructure> qTS(flatRate(qRate, dc));
    boost::shared_ptr<SimpleQuote> rRate(new SimpleQuote(0.0));
    Handle<YieldTermStructure> rTS(flatRate(rRate, dc));
    boost::shared_ptr<SimpleQuote> vol(new SimpleQuote(0.0));
    Handle<BlackVolTermStructure> volTS(flatVol(vol, dc));
    boost::shared_ptr<BlackScholesMertonProcess> process(
                            new BlackScholesMertonProcess(Handle<Quote>(spot),
                                                          qTS, rTS, volTS));
    for (Size i=0; i<LENGTH(types); i++) {
      for (Size j=0; j<LENGTH(moneyness); j++) {
        for (Size k=0; k<LENGTH(lengths); k++) {
          for (Size kk=0; kk<LENGTH(frequencies); kk++) {
              Period tenor = Period(frequencies[kk]);
              boost::shared_ptr<EuropeanExercise> maturity(
                              new EuropeanExercise(today + lengths[k]*tenor));
              boost::shared_ptr<PercentageStrikePayoff> payoff(
                          new PercentageStrikePayoff(types[i], moneyness[j]));
              std::vector<Date> reset;
              for (Date d = today + tenor; d < maturity->lastDate(); d += tenor)
                  reset.push_back(d);
              CliquetOption option(payoff, maturity, reset);
              boost::shared_ptr<PricingEngine> refEngine(
                                      new AnalyticPerformanceEngine(process));
              boost::shared_ptr<PricingEngine> mcEngine =
                  MakeMCPerformanceEngine<PseudoRandom>(process)
                  .withBrownianBridge()
                  .withAbsoluteTolerance(5.0e-3)
                  .withSeed(42);
              for (Size l=0; l<LENGTH(underlyings); l++) {
                for (Size m=0; m<LENGTH(qRates); m++) {
                  for (Size n=0; n<LENGTH(rRates); n++) {
                    for (Size p=0; p<LENGTH(vols); p++) {
                      Real u = underlyings[l];
                      Rate q = qRates[m],
                           r = rRates[n];
                      Volatility v = vols[p];
                      spot->setValue(u);
                      qRate->setValue(q);
                      rRate->setValue(r);
                      vol->setValue(v);
                      option.setPricingEngine(refEngine);
                      Real refValue = option.NPV();
                      option.setPricingEngine(mcEngine);
                      Real value = option.NPV();
                      Real error = std::fabs(refValue-value);
                      Real tolerance = 1.5e-2;
                      if (error > tolerance) {
                          REPORT_FAILURE("value", payoff, maturity,
                                         u, q, r, today, v,
                                         refValue, value,
                                         error, tolerance);
                      }
                    }
                  }
                }
              }
          }
        }
      }
    }
}
void CliquetOptionTest::testPerformanceGreeks () [static]
Definition at line 270 of file cliquetoption.cpp.
Referenced by suite().
{
    BOOST_MESSAGE("Testing performance option greeks...");
    testOptionGreeks<AnalyticPerformanceEngine>();
}
void CliquetOptionTest::testValues () [static]
Definition at line 54 of file cliquetoption.cpp.
References QuantLib::Option::Call, QuantLib::flatRate(), QuantLib::flatVol(), QuantLib::Instrument::NPV(), REPORT_FAILURE, anonymous_namespace{inflationvolatility.cpp}::reset(), QuantLib::Instrument::setPricingEngine(), anonymous_namespace{marketmodel.cpp}::todaysDate, and anonymous_namespace{gaussianquadratures.cpp}::tolerance.
Referenced by suite().
{
    BOOST_MESSAGE("Testing Cliquet option values...");
    Date today = Date::todaysDate();
    DayCounter dc = Actual360();
    boost::shared_ptr<SimpleQuote> spot(new SimpleQuote(60.0));
    boost::shared_ptr<SimpleQuote> qRate(new SimpleQuote(0.04));
    boost::shared_ptr<YieldTermStructure> qTS = flatRate(today, qRate, dc);
    boost::shared_ptr<SimpleQuote> rRate(new SimpleQuote(0.08));
    boost::shared_ptr<YieldTermStructure> rTS = flatRate(today, rRate, dc);
    boost::shared_ptr<SimpleQuote> vol(new SimpleQuote(0.30));
    boost::shared_ptr<BlackVolTermStructure> volTS = flatVol(today, vol, dc);
    boost::shared_ptr<BlackScholesMertonProcess> process(
         new BlackScholesMertonProcess(Handle<Quote>(spot),
                                       Handle<YieldTermStructure>(qTS),
                                       Handle<YieldTermStructure>(rTS),
                                       Handle<BlackVolTermStructure>(volTS)));
    boost::shared_ptr<PricingEngine> engine(new AnalyticCliquetEngine(process));
    std::vector<Date> reset;
    reset.push_back(today + 90);
    Date maturity = today + 360;
    Option::Type type = Option::Call;
    Real moneyness = 1.1;
    boost::shared_ptr<PercentageStrikePayoff> payoff(
                                 new PercentageStrikePayoff(type, moneyness));
    boost::shared_ptr<EuropeanExercise> exercise(
                                              new EuropeanExercise(maturity));
    CliquetOption option(payoff, exercise, reset);
    option.setPricingEngine(engine);
    Real calculated = option.NPV();
    Real expected = 4.4064; // Haug, p.37
    Real error = std::fabs(calculated-expected);
    Real tolerance = 1e-4;
    if (error > tolerance) {
        REPORT_FAILURE("value", payoff, exercise, spot->value(),
                       qRate->value(), rRate->value(), today,
                       vol->value(), expected, calculated,
                       error, tolerance);
    }
}
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/cliquetoption.hpp
/home/deriversatile/QuantLib/QuantLibQt/test-suite/cliquetoption.cpp