QuantLib: QuantLib::PenaltyFunction< Curve > Class Template Reference
QuantLib::PenaltyFunction< Curve > Class Template Reference
#include <localbootstrap.hpp>
Public Member Functions
PenaltyFunction (Curve *curve, Size initialIndex, helper_iterator rateHelpersStart, helper_iterator rateHelpersEnd)
Real value (const Array &x) const
method to overload to compute the cost function value in x
Disposable< Array > values (const Array &x) const
method to overload to compute the cost function values in x
Private Types
typedef Curve::traits_type Traits
typedef Traits::helper helper
typedef std::vector
< boost::shared_ptr< helper >
>::const_iterator helper_iterator
Private Attributes
Curve * curve_
Size initialIndex_
Size localisation_
helper_iterator rateHelpersStart_
helper_iterator rateHelpersEnd_
Detailed Description
template<class Curve>
class QuantLib::PenaltyFunction< Curve >
Definition at line 40 of file localbootstrap.hpp.
Member Typedef Documentation
template<class Curve> typedef Traits::helper QuantLib::PenaltyFunction< Curve >::helper [private]
Definition at line 42 of file localbootstrap.hpp.
template<class Curve> typedef std::vector< boost::shared_ptr<helper> >::const_iterator QuantLib::PenaltyFunction< Curve >::helper_iterator [private]
Definition at line 45 of file localbootstrap.hpp.
template<class Curve> typedef Curve::traits_type QuantLib::PenaltyFunction< Curve >::Traits [private]
Definition at line 41 of file localbootstrap.hpp.
Constructor & Destructor Documentation
template<class Curve> QuantLib::PenaltyFunction< Curve >::PenaltyFunction (Curve * curve, Size initialIndex, helper_iterator rateHelpersStart, helper_iterator rateHelpersEnd) [inline]
Definition at line 47 of file localbootstrap.hpp.
References QuantLib::PenaltyFunction< Curve >::localisation_.
        : curve_(curve), initialIndex_(initialIndex),
          rateHelpersStart_(rateHelpersStart), rateHelpersEnd_(rateHelpersEnd) {
            localisation_ = std::distance(rateHelpersStart, rateHelpersEnd);
        }
Member Function Documentation
template<class Curve > Real QuantLib::PenaltyFunction< Curve >::value (const Array & x) const [virtual]
method to overload to compute the cost function value in x
Implements QuantLib::CostFunction.
Definition at line 251 of file localbootstrap.hpp.
References QuantLib::Array::begin(), and QuantLib::Array::end().
{
        Size i = initialIndex_;
        Array::const_iterator guessIt = x.begin();
        while (guessIt != x.end()) {
            Traits::updateGuess(curve_->data_, *guessIt, i);
            ++guessIt;
            ++i;
        }
        curve_->interpolation_.update();
        Real penalty = 0.0;
        helper_iterator instIt = rateHelpersStart_;
        while (instIt != rateHelpersEnd_) {
            Real quoteError = (*instIt)->quoteError();
            penalty += std::fabs(quoteError);
            ++instIt;
        }
        return penalty;
    }
template<class Curve > Disposable< Array > QuantLib::PenaltyFunction< Curve >::values (const Array & x) const [virtual]
method to overload to compute the cost function values in x
Implements QuantLib::CostFunction.
Definition at line 273 of file localbootstrap.hpp.
References QuantLib::Array::begin(), and QuantLib::Array::end().
{
        Array::const_iterator guessIt = x.begin();
        Size i = initialIndex_;
        while (guessIt != x.end()) {
            Traits::updateGuess(curve_->data_, *guessIt, i);
            ++guessIt;
            ++i;
        }
        curve_->interpolation_.update();
        Array penalties(localisation_);
        helper_iterator instIt = rateHelpersStart_;
        Array::iterator penIt = penalties.begin();
        while (instIt != rateHelpersEnd_) {
            Real quoteError = (*instIt)->quoteError();
            *penIt = std::fabs(quoteError);
            ++instIt;
            ++penIt;
        }
        return penalties;
    }
Member Data Documentation
template<class Curve> Curve* QuantLib::PenaltyFunction< Curve >::curve_ [private]
Definition at line 60 of file localbootstrap.hpp.
template<class Curve> Size QuantLib::PenaltyFunction< Curve >::initialIndex_ [private]
Definition at line 61 of file localbootstrap.hpp.
template<class Curve> Size QuantLib::PenaltyFunction< Curve >::localisation_ [private]
Definition at line 62 of file localbootstrap.hpp.
Referenced by QuantLib::PenaltyFunction< Curve >::PenaltyFunction().
template<class Curve> helper_iterator QuantLib::PenaltyFunction< Curve >::rateHelpersEnd_ [private]
Definition at line 64 of file localbootstrap.hpp.
template<class Curve> helper_iterator QuantLib::PenaltyFunction< Curve >::rateHelpersStart_ [private]
Definition at line 63 of file localbootstrap.hpp.
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/localbootstrap.hpp