QuantLib: QuantLib::AnalyticContinuousFloatingLookbackEngine Class Reference
QuantLib::AnalyticContinuousFloatingLookbackEngine Class Reference
Pricing engine for European continuous floating-strike lookback.
#include <analyticcontinuousfloatinglookback.hpp>
Public Member Functions
AnalyticContinuousFloatingLookbackEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > &process)
void calculate () const
Private Member Functions
Real underlying () const
Time residualTime () const
Volatility volatility () const
Real minmax () const
Real stdDeviation () const
Rate riskFreeRate () const
DiscountFactor riskFreeDiscount () const
Rate dividendYield () const
DiscountFactor dividendDiscount () const
Real A (Real eta) const
Private Attributes
boost::shared_ptr
< GeneralizedBlackScholesProcess > process_
CumulativeNormalDistribution f_
Detailed Description
Pricing engine for European continuous floating-strike lookback.
Formula from "Option Pricing Formulas", E.G. Haug, McGraw-Hill, 1998, p.61-62
Test:
returned values verified against results from literature
Definition at line 42 of file analyticcontinuousfloatinglookback.hpp.
Constructor & Destructor Documentation
QuantLib::AnalyticContinuousFloatingLookbackEngine::AnalyticContinuousFloatingLookbackEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > & process)
Definition at line 27 of file analyticcontinuousfloatinglookback.cpp.
References process_, and QuantLib::Observer::registerWith().
    : process_(process) {
        registerWith(process_);
    }
Member Function Documentation
Real QuantLib::AnalyticContinuousFloatingLookbackEngine::A (Real eta) const [private]
Definition at line 93 of file analyticcontinuousfloatinglookback.cpp.
References dividendDiscount(), dividendYield(), f_, minmax(), QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow(), riskFreeDiscount(), riskFreeRate(), stdDeviation(), underlying(), and volatility().
Referenced by calculate().
{
        Volatility vol = volatility();
        Real lambda = 2.0*(riskFreeRate() - dividendYield())/(vol*vol);
        Real s = underlying()/minmax();
        Real d1 = std::log(s)/stdDeviation() + 0.5*(lambda+1.0)*stdDeviation();
        Real n1 = f_(eta*d1);
        Real n2 = f_(eta*(d1-stdDeviation()));
        Real n3 = f_(eta*(-d1+lambda*stdDeviation()));
        Real n4 = f_(eta*-d1);
        Real pow_s = std::pow(s, -lambda);
        return eta*((underlying() * dividendDiscount() * n1 -
                    minmax() * riskFreeDiscount() * n2) +
                    (underlying() * riskFreeDiscount() *
                    (pow_s * n3 - dividendDiscount()* n4/riskFreeDiscount())/
            lambda));
    }
void QuantLib::AnalyticContinuousFloatingLookbackEngine::calculate () const [virtual]
Implements QuantLib::PricingEngine.
Definition at line 33 of file analyticcontinuousfloatinglookback.cpp.
References A(), QuantLib::GenericEngine< ContinuousFloatingLookbackOption::arguments, ContinuousFloatingLookbackOption::results >::arguments_, QuantLib::Option::Call, process_, QuantLib::Option::Put, QL_FAIL, QL_REQUIRE, QuantLib::GenericEngine< ContinuousFloatingLookbackOption::arguments, ContinuousFloatingLookbackOption::results >::results_, and QuantLib::Instrument::results::value.
{
        boost::shared_ptr<FloatingTypePayoff> payoff =
            boost::dynamic_pointer_cast<FloatingTypePayoff>(arguments_.payoff);
        QL_REQUIRE(payoff, "Non-floating payoff given");
        QL_REQUIRE(process_->x0() > 0.0, "negative or null underlying");
        switch (payoff->optionType()) {
          case Option::Call:
            results_.value = A(1);
            break;
          case Option::Put:
            results_.value = A(-1);
            break;
          default:
            QL_FAIL("Unknown type");
        }
    }
DiscountFactor QuantLib::AnalyticContinuousFloatingLookbackEngine::dividendDiscount () const [private]
Definition at line 84 of file analyticcontinuousfloatinglookback.cpp.
References process_, and residualTime().
Referenced by A().
{
        return process_->dividendYield()->discount(residualTime());
    }
Rate QuantLib::AnalyticContinuousFloatingLookbackEngine::dividendYield () const [private]
Definition at line 79 of file analyticcontinuousfloatinglookback.cpp.
References QuantLib::Continuous, QuantLib::NoFrequency, process_, and residualTime().
Referenced by A().
{
        return process_->dividendYield()->zeroRate(residualTime(),
                                                   Continuous, NoFrequency);
    }
Real QuantLib::AnalyticContinuousFloatingLookbackEngine::minmax () const [private]
Definition at line 89 of file analyticcontinuousfloatinglookback.cpp.
References QuantLib::GenericEngine< ContinuousFloatingLookbackOption::arguments, ContinuousFloatingLookbackOption::results >::arguments_, and QuantLib::ContinuousFloatingLookbackOption::arguments::minmax.
Referenced by A(), and volatility().
{
        return arguments_.minmax;
    }
Time QuantLib::AnalyticContinuousFloatingLookbackEngine::residualTime () const [private]
Definition at line 57 of file analyticcontinuousfloatinglookback.cpp.
References QuantLib::GenericEngine< ContinuousFloatingLookbackOption::arguments, ContinuousFloatingLookbackOption::results >::arguments_, and process_.
Referenced by dividendDiscount(), dividendYield(), riskFreeDiscount(), riskFreeRate(), stdDeviation(), and volatility().
{
        return process_->time(arguments_.exercise->lastDate());
    }
DiscountFactor QuantLib::AnalyticContinuousFloatingLookbackEngine::riskFreeDiscount () const [private]
Definition at line 74 of file analyticcontinuousfloatinglookback.cpp.
References process_, and residualTime().
Referenced by A().
{
        return process_->riskFreeRate()->discount(residualTime());
    }
Rate QuantLib::AnalyticContinuousFloatingLookbackEngine::riskFreeRate () const [private]
Definition at line 69 of file analyticcontinuousfloatinglookback.cpp.
References QuantLib::Continuous, QuantLib::NoFrequency, process_, and residualTime().
Referenced by A().
{
        return process_->riskFreeRate()->zeroRate(residualTime(), Continuous,
                                                  NoFrequency);
    }
Real QuantLib::AnalyticContinuousFloatingLookbackEngine::stdDeviation () const [private]
Definition at line 65 of file analyticcontinuousfloatinglookback.cpp.
References residualTime(), and volatility().
Referenced by A().
{
        return volatility() * std::sqrt(residualTime());
    }
Real QuantLib::AnalyticContinuousFloatingLookbackEngine::underlying () const [private]
Definition at line 53 of file analyticcontinuousfloatinglookback.cpp.
References process_.
Referenced by A().
{
        return process_->x0();
    }
Volatility QuantLib::AnalyticContinuousFloatingLookbackEngine::volatility () const [private]
Definition at line 61 of file analyticcontinuousfloatinglookback.cpp.
References minmax(), process_, and residualTime().
Referenced by A(), and stdDeviation().
{
        return process_->blackVolatility()->blackVol(residualTime(), minmax());
    }
Member Data Documentation
CumulativeNormalDistribution QuantLib::AnalyticContinuousFloatingLookbackEngine::f_ [private]
Definition at line 50 of file analyticcontinuousfloatinglookback.hpp.
Referenced by A().
boost::shared_ptr<GeneralizedBlackScholesProcess> QuantLib::AnalyticContinuousFloatingLookbackEngine::process_ [private]
Definition at line 49 of file analyticcontinuousfloatinglookback.hpp.
Referenced by AnalyticContinuousFloatingLookbackEngine(), calculate(), dividendDiscount(), dividendYield(), residualTime(), riskFreeDiscount(), riskFreeRate(), underlying(), and volatility().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/lookback/analyticcontinuousfloatinglookback.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/lookback/analyticcontinuousfloatinglookback.cpp