QuantLib: QuantLib::Libor Class Reference
QuantLib::Libor Class Reference
base class for all BBA LIBOR indexes but the EUR, O/N, and S/N ones
#include <libor.hpp>
Public Member Functions
Libor (const std::string &familyName, const Period &tenor, Natural settlementDays, const Currency &currency, const Calendar &financialCenterCalendar, const DayCounter &dayCounter, const Handle< YieldTermStructure > &h=Handle< YieldTermStructure >())
Date calculations
see http://www.bba.org.uk/bba/jsp/polopoly.jsp?d=225&a=1412
Date valueDate (const Date &fixingDate) const
Date maturityDate (const Date &valueDate) const
Other methods
boost::shared_ptr< IborIndex > clone (const Handle< YieldTermStructure > &h) const
returns a copy of itself linked to a different forwarding curve
Other inspectors
Calendar jointCalendar () const
Private Attributes
Calendar financialCenterCalendar_
Calendar jointCalendar_
Detailed Description
base class for all BBA LIBOR indexes but the EUR, O/N, and S/N ones
LIBOR fixed by BBA.
See <http://www.bba.org.uk/bba/jsp/polopoly.jsp?d=225&a=1414>.
Definition at line 38 of file libor.hpp.
Constructor & Destructor Documentation
QuantLib::Libor::Libor (const std::string & familyName, const Period & tenor, Natural settlementDays, const Currency & currency, const Calendar & financialCenterCalendar, const DayCounter & dayCounter, const Handle< YieldTermStructure > & h = Handle<YieldTermStructure>())
Definition at line 60 of file libor.cpp.
References QuantLib::Days, QL_REQUIRE, and QuantLib::InterestRateIndex::tenor().
Referenced by clone().
    : IborIndex(familyName, tenor, settlementDays, currency,
                // http://www.bba.org.uk/bba/jsp/polopoly.jsp?d=225&a=1412 :
                // UnitedKingdom::Exchange is the fixing calendar for
                // a) all currencies but EUR
                // b) all indexes but o/n and s/n
                UnitedKingdom(UnitedKingdom::Exchange),
                liborConvention(tenor), liborEOM(tenor),
                dayCounter, h),
      financialCenterCalendar_(financialCenterCalendar),
      jointCalendar_(JointCalendar(UnitedKingdom(UnitedKingdom::Exchange),
                                   financialCenterCalendar,
                                   JoinHolidays)) {
        QL_REQUIRE(this->tenor().units()!=Days,
                   "for daily tenors (" << this->tenor() <<
                   ") dedicated DailyTenor constructor must be used");
        QL_REQUIRE(currency!=EURCurrency(),
                   "for EUR Libor dedicated EurLibor constructor must be used");
    }
Member Function Documentation
boost::shared_ptr< IborIndex > QuantLib::Libor::clone (const Handle< YieldTermStructure > & forwarding) const [virtual]
returns a copy of itself linked to a different forwarding curve
Reimplemented from QuantLib::IborIndex.
Definition at line 119 of file libor.cpp.
References QuantLib::InterestRateIndex::currency(), QuantLib::InterestRateIndex::dayCounter(), QuantLib::InterestRateIndex::familyName(), financialCenterCalendar_, QuantLib::InterestRateIndex::fixingDays(), Libor(), and QuantLib::InterestRateIndex::tenor().
{
        return boost::shared_ptr<IborIndex>(new Libor(familyName(),
                                                      tenor(),
                                                      fixingDays(),
                                                      currency(),
                                                      financialCenterCalendar_,
                                                      dayCounter(),
                                                      h));
    }
Calendar QuantLib::Libor::jointCalendar () const
Definition at line 115 of file libor.cpp.
References jointCalendar_.
{
        return jointCalendar_;
    }
Date QuantLib::Libor::maturityDate (const Date & valueDate) const [virtual]
Reimplemented from QuantLib::IborIndex.
Definition at line 102 of file libor.cpp.
References QuantLib::Calendar::advance(), QuantLib::IborIndex::convention_, QuantLib::IborIndex::endOfMonth(), jointCalendar_, and QuantLib::InterestRateIndex::tenor_.
{
        // Where a deposit is made on the final business day of a
        // particular calendar month, the maturity of the deposit shall
        // be on the final business day of the month in which it matures
        // (not the corresponding date in the month of maturity). Or in
        // other words, in line with market convention, BBA LIBOR rates
        // are dealt on an end-end basis. For instance a one month
        // deposit for value 28th February would mature on 31st March,
        // not the 28th of March.
        return jointCalendar_.advance(valueDate, tenor_, convention_,
                                                         endOfMonth());
    }
Date QuantLib::Libor::valueDate (const Date & fixingDate) const [virtual]
Reimplemented from QuantLib::InterestRateIndex.
Definition at line 86 of file libor.cpp.
References QuantLib::Calendar::adjust(), QuantLib::Calendar::advance(), anonymous_namespace{marketmodel.cpp}::d, QuantLib::Days, QuantLib::InterestRateIndex::fixingCalendar(), QuantLib::InterestRateIndex::fixingDays_, QuantLib::InterestRateIndex::isValidFixingDate(), jointCalendar_, and QL_REQUIRE.
{
        QL_REQUIRE(isValidFixingDate(fixingDate),
                   "Fixing date " << fixingDate << " is not valid");
        // http://www.bba.org.uk/bba/jsp/polopoly.jsp?d=225&a=1412 :
        // For all currencies other than EUR and GBP the period between
        // Fixing Date and Value Date will be two London business days
        // after the Fixing Date, or if that day is not both a London
        // business day and a business day in the principal financial centre
        // of the currency concerned, the next following day which is a
        // business day in both centres shall be the Value Date.
        Date d = fixingCalendar().advance(fixingDate, fixingDays_, Days);
        return jointCalendar_.adjust(d);
    }
Member Data Documentation
Calendar QuantLib::Libor::financialCenterCalendar_ [private]
Definition at line 66 of file libor.hpp.
Referenced by clone().
Calendar QuantLib::Libor::jointCalendar_ [private]
Definition at line 67 of file libor.hpp.
Referenced by jointCalendar(), maturityDate(), and valueDate().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/indexes/ibor/libor.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/indexes/ibor/libor.cpp