QuantLib: QuantLib::BlackCalculator Class Reference
QuantLib::BlackCalculator Class Reference
Black 1976 calculator class.
#include <blackcalculator.hpp>
Classes
class Calculator
Public Member Functions
BlackCalculator (const boost::shared_ptr< StrikedTypePayoff > &payoff, Real forward, Real stdDev, Real discount=1.0)
BlackCalculator (Option::Type optionType, Real strike, Real forward, Real stdDev, Real discount=1.0)
virtual ~BlackCalculator ()
Real value () const
Real deltaForward () const
virtual Real delta (Real spot) const
Real elasticityForward () const
virtual Real elasticity (Real spot) const
Real gammaForward () const
virtual Real gamma (Real spot) const
virtual Real theta (Real spot, Time maturity) const
virtual Real thetaPerDay (Real spot, Time maturity) const
Real vega (Time maturity) const
Real rho (Time maturity) const
Real dividendRho (Time maturity) const
Real itmCashProbability () const
Real itmAssetProbability () const
Real strikeSensitivity () const
Real alpha () const
Real beta () const
Protected Member Functions
void initialize (const boost::shared_ptr< StrikedTypePayoff > &p)
Protected Attributes
Real strike_
Real forward_
Real stdDev_
Real discount_
Real variance_
Real d1_
Real d2_
Real alpha_
Real beta_
Real DalphaDd1_
Real DbetaDd2_
Real n_d1_
Real cum_d1_
Real n_d2_
Real cum_d2_
Real x_
Real DxDs_
Real DxDstrike_
Friends
class Calculator
Detailed Description
Black 1976 calculator class.
Bug:
When the variance is null, division by zero occur during the calculation of delta, delta forward, gamma, gamma forward, rho, dividend rho, vega, and strike sensitivity.
Definition at line 37 of file blackcalculator.hpp.
Constructor & Destructor Documentation
QuantLib::BlackCalculator::BlackCalculator (const boost::shared_ptr< StrikedTypePayoff > & payoff, Real forward, Real stdDev, Real discount = 1.0)
QuantLib::BlackCalculator::BlackCalculator (Option::Type optionType, Real strike, Real forward, Real stdDev, Real discount = 1.0)
Definition at line 56 of file blackcalculator.cpp.
References initialize().
    : strike_(strike), forward_(forward), stdDev_(stdDev),
      discount_(discount), variance_(stdDev*stdDev) {
        initialize(shared_ptr<StrikedTypePayoff>(new
            PlainVanillaPayoff(optionType, strike)));
    }
virtual QuantLib::BlackCalculator::~BlackCalculator () [inline, virtual]
Definition at line 51 of file blackcalculator.hpp.
{}
Member Function Documentation
Real QuantLib::BlackCalculator::alpha () const [inline]
Definition at line 131 of file blackcalculator.hpp.
References alpha_.
{
        return alpha_;
    }
Real QuantLib::BlackCalculator::beta () const [inline]
Definition at line 135 of file blackcalculator.hpp.
References beta_.
Referenced by QuantLib::AnalyticCliquetEngine::calculate().
{
        return beta_;
    }
Real QuantLib::BlackCalculator::delta (Real spot) const [virtual]
Sensitivity to change in the underlying spot price.
Definition at line 204 of file blackcalculator.cpp.
References alpha_, beta_, DalphaDd1_, DbetaDd2_, discount_, DxDs_, forward_, QL_REQUIRE, stdDev_, and x_.
Referenced by QuantLib::AnalyticDividendEuropeanEngine::calculate(), QuantLib::BjerksundStenslandApproximationEngine::calculate(), QuantLib::AnalyticCliquetEngine::calculate(), QuantLib::BaroneAdesiWhaleyApproximationEngine::calculate(), QuantLib::AnalyticContinuousGeometricAveragePriceAsianEngine::calculate(), QuantLib::AnalyticDiscreteGeometricAveragePriceAsianEngine::calculate(), QuantLib::FDStepConditionEngine< Scheme >::calculate(), QuantLib::JuQuadraticApproximationEngine::calculate(), QuantLib::AnalyticEuropeanEngine::calculate(), elasticity(), and theta().
{
        QL_REQUIRE(spot > 0.0, "positive spot value required: " <<
                   spot << " not allowed");
        Real DforwardDs = forward_ / spot;
        Real temp = stdDev_*spot;
        Real DalphaDs = DalphaDd1_/temp;
        Real DbetaDs  = DbetaDd2_/temp;
        Real temp2 = DalphaDs * forward_ + alpha_ * DforwardDs
                      +DbetaDs  * x_       + beta_  * DxDs_;
        return discount_ * temp2;
    }
Real QuantLib::BlackCalculator::deltaForward () const
Sensitivity to change in the underlying forward price.
Definition at line 220 of file blackcalculator.cpp.
References alpha_, DalphaDd1_, DbetaDd2_, discount_, forward_, stdDev_, and x_.
Referenced by QuantLib::BjerksundStenslandApproximationEngine::calculate(), QuantLib::BaroneAdesiWhaleyApproximationEngine::calculate(), QuantLib::JuQuadraticApproximationEngine::calculate(), QuantLib::AnalyticEuropeanEngine::calculate(), and elasticityForward().
{
        Real temp = stdDev_*forward_;
        Real DalphaDforward = DalphaDd1_/temp;
        Real DbetaDforward  = DbetaDd2_/temp;
        Real temp2 = DalphaDforward * forward_ + alpha_
                      +DbetaDforward  * x_; // DXDforward = 0.0
        return discount_ * temp2;
    }
Real QuantLib::BlackCalculator::dividendRho (Time maturity) const
Sensitivity to dividend/growth rate.
Definition at line 330 of file blackcalculator.cpp.
References alpha_, DalphaDd1_, DbetaDd2_, discount_, forward_, QL_REQUIRE, stdDev_, and x_.
Referenced by QuantLib::AnalyticPerformanceEngine::calculate(), QuantLib::BjerksundStenslandApproximationEngine::calculate(), QuantLib::AnalyticCliquetEngine::calculate(), QuantLib::BaroneAdesiWhaleyApproximationEngine::calculate(), QuantLib::AnalyticDiscreteGeometricAveragePriceAsianEngine::calculate(), QuantLib::AnalyticContinuousGeometricAveragePriceAsianEngine::calculate(), QuantLib::JuQuadraticApproximationEngine::calculate(), and QuantLib::AnalyticEuropeanEngine::calculate().
{
        QL_REQUIRE(maturity>=0.0,
                   "negative maturity not allowed");
        // actually DalphaDq / T
        Real DalphaDq = -DalphaDd1_/stdDev_;
        Real DbetaDq  = -DbetaDd2_/stdDev_;
        Real temp = DalphaDq * forward_ - alpha_ * forward_ + DbetaDq * x_;
        return maturity * discount_ * temp;
    }
Real QuantLib::BlackCalculator::elasticity (Real spot) const [virtual]
Sensitivity in percent to a percent change in the underlying spot price.
Definition at line 231 of file blackcalculator.cpp.
References delta(), QL_EPSILON, QL_MAX_REAL, QL_MIN_REAL, and value().
Referenced by QuantLib::BjerksundStenslandApproximationEngine::calculate(), QuantLib::BaroneAdesiWhaleyApproximationEngine::calculate(), QuantLib::JuQuadraticApproximationEngine::calculate(), and QuantLib::AnalyticEuropeanEngine::calculate().
{
        Real val = value();
        Real del = delta(spot);
        if (val>QL_EPSILON)
            return del/val*spot;
        else if (std::fabs(del)<QL_EPSILON)
            return 0.0;
        else if (del>0.0)
            return QL_MAX_REAL;
        else
            return QL_MIN_REAL;
    }
Real QuantLib::BlackCalculator::elasticityForward () const
Sensitivity in percent to a percent change in the underlying forward price.
Definition at line 244 of file blackcalculator.cpp.
References deltaForward(), forward_, QL_EPSILON, QL_MAX_REAL, QL_MIN_REAL, and value().
{
        Real val = value();
        Real del = deltaForward();
        if (val>QL_EPSILON)
            return del/val*forward_;
        else if (std::fabs(del)<QL_EPSILON)
            return 0.0;
        else if (del>0.0)
            return QL_MAX_REAL;
        else
            return QL_MIN_REAL;
    }
Real QuantLib::BlackCalculator::gamma (Real spot) const [virtual]
Second order derivative with respect to change in the underlying spot price.
Definition at line 257 of file blackcalculator.cpp.
References d1_, d2_, DalphaDd1_, DbetaDd2_, discount_, DxDs_, forward_, QL_REQUIRE, stdDev_, and x_.
Referenced by QuantLib::AnalyticDividendEuropeanEngine::calculate(), QuantLib::BjerksundStenslandApproximationEngine::calculate(), QuantLib::BaroneAdesiWhaleyApproximationEngine::calculate(), QuantLib::AnalyticContinuousGeometricAveragePriceAsianEngine::calculate(), QuantLib::AnalyticDiscreteGeometricAveragePriceAsianEngine::calculate(), QuantLib::FDStepConditionEngine< Scheme >::calculate(), QuantLib::JuQuadraticApproximationEngine::calculate(), QuantLib::AnalyticEuropeanEngine::calculate(), and theta().
{
        QL_REQUIRE(spot > 0.0, "positive spot value required: " <<
                   spot << " not allowed");
        Real DforwardDs = forward_ / spot;
        Real temp = stdDev_*spot;
        Real DalphaDs = DalphaDd1_/temp;
        Real DbetaDs  = DbetaDd2_/temp;
        Real D2alphaDs2 = - DalphaDs/spot*(1+d1_/stdDev_);
        Real D2betaDs2  = - DbetaDs /spot*(1+d2_/stdDev_);
        Real temp2 = D2alphaDs2 * forward_ + 2.0 * DalphaDs * DforwardDs
                      +D2betaDs2  * x_       + 2.0 * DbetaDs  * DxDs_;
        return  discount_ * temp2;
    }
Real QuantLib::BlackCalculator::gammaForward () const
Second order derivative with respect to change in the underlying forward price.
Definition at line 277 of file blackcalculator.cpp.
References d1_, d2_, DalphaDd1_, DbetaDd2_, discount_, forward_, stdDev_, and x_.
{
        Real temp = stdDev_*forward_;
        Real DalphaDforward = DalphaDd1_/temp;
        Real DbetaDforward  = DbetaDd2_/temp;
        Real D2alphaDforward2 = - DalphaDforward/forward_*(1+d1_/stdDev_);
        Real D2betaDforward2  = - DbetaDforward /forward_*(1+d2_/stdDev_);
        Real temp2 = D2alphaDforward2 * forward_ + 2.0 * DalphaDforward
                      +D2betaDforward2  * x_; // DXDforward = 0.0
        return discount_ * temp2;
    }
void QuantLib::BlackCalculator::initialize (const boost::shared_ptr< StrikedTypePayoff > & p) [protected]
Definition at line 67 of file blackcalculator.cpp.
References alpha_, beta_, QuantLib::Option::Call, QuantLib::close(), cum_d1_, cum_d2_, d1_, d2_, DalphaDd1_, DbetaDd2_, QuantLib::CumulativeNormalDistribution::derivative(), discount_, DxDs_, DxDstrike_, anonymous_namespace{interpolations.cpp}::f(), forward_, M_1_SQRTPI, M_SQRT_2, n_d1_, n_d2_, QuantLib::Option::Put, QL_EPSILON, QL_FAIL, QL_MAX_REAL, QL_MIN_REAL, QL_REQUIRE, stdDev_, strike_, and x_.
Referenced by BlackCalculator().
{
        QL_REQUIRE(strike_>=0.0,
                   "strike (" << strike_ << ") must be non-negative");
        QL_REQUIRE(forward_>0.0,
                   "forward (" << forward_ << ") must be positive");
        //QL_REQUIRE(displacement_>=0.0,
        //           "displacement (" << displacement_ << ") must be non-negative");
        QL_REQUIRE(stdDev_>=0.0,
                   "stdDev (" << stdDev_ << ") must be non-negative");
        QL_REQUIRE(discount_>0.0,
                   "discount (" << discount_ << ") must be positive");
        if (stdDev_>=QL_EPSILON) {
            if (close(strike_, 0.0)) {
                d1_ = QL_MAX_REAL;
                d2_ = QL_MAX_REAL;
                cum_d1_ = 1.0;
                cum_d2_ = 1.0;
                n_d1_ = 0.0;
                n_d2_ = 0.0;
            } else {
                d1_ = std::log(forward_/strike_)/stdDev_ + 0.5*stdDev_;
                d2_ = d1_-stdDev_;
                CumulativeNormalDistribution f;
                cum_d1_ = f(d1_);
                cum_d2_ = f(d2_);
                n_d1_ = f.derivative(d1_);
                n_d2_ = f.derivative(d2_);
            }
        } else {
            if (close(forward_, strike_)) {
                d1_ = 0;
                d2_ = 0;
                cum_d1_ = 0.5;
                cum_d2_ = 0.5;
                n_d1_ = M_SQRT_2 * M_1_SQRTPI;
                n_d2_ = M_SQRT_2 * M_1_SQRTPI;
            } else if (forward_>strike_) {
                d1_ = QL_MAX_REAL;
                d2_ = QL_MAX_REAL;
                cum_d1_ = 1.0;
                cum_d2_ = 1.0;
                n_d1_ = 0.0;
                n_d2_ = 0.0;
            } else {
                d1_ = QL_MIN_REAL;
                d2_ = QL_MIN_REAL;
                cum_d1_ = 0.0;
                cum_d2_ = 0.0;
                n_d1_ = 0.0;
                n_d2_ = 0.0;
            }
        }
        x_ = strike_;
        DxDstrike_ = 1.0;
        // the following one will probably disappear as soon as
        // super-share will be properly handled
        DxDs_ = 0.0;
        // this part is always executed.
        // in case of plain-vanilla payoffs, it is also the only part
        // which is executed.
        switch (p->optionType()) {
          case Option::Call:
            alpha_     =  cum_d1_;//  N(d1)
            DalphaDd1_ =    n_d1_;//  n(d1)
            beta_      = -cum_d2_;// -N(d2)
            DbetaDd2_  = -  n_d2_;// -n(d2)
            break;
          case Option::Put:
            alpha_     = -1.0+cum_d1_;// -N(-d1)
            DalphaDd1_ =        n_d1_;//  n( d1)
            beta_      =  1.0-cum_d2_;//  N(-d2)
            DbetaDd2_  =     -  n_d2_;// -n( d2)
            break;
          default:
            QL_FAIL("invalid option type");
        }
        // now dispatch on type.
        Calculator calc(*this);
        p->accept(calc);
    }
Real QuantLib::BlackCalculator::itmAssetProbability () const [inline]
Probability of being in the money in the asset martingale measure, i.e. N(d1). It is a risk-neutral probability, not the real world one.
Definition at line 127 of file blackcalculator.hpp.
References cum_d1_.
{
        return cum_d1_;
    }
Real QuantLib::BlackCalculator::itmCashProbability () const [inline]
Probability of being in the money in the bond martingale measure, i.e. N(d2). It is a risk-neutral probability, not the real world one.
Definition at line 123 of file blackcalculator.hpp.
References cum_d2_.
Referenced by QuantLib::BjerksundStenslandApproximationEngine::calculate(), QuantLib::BaroneAdesiWhaleyApproximationEngine::calculate(), QuantLib::JuQuadraticApproximationEngine::calculate(), and QuantLib::AnalyticEuropeanEngine::calculate().
{
        return cum_d2_;
    }
Real QuantLib::BlackCalculator::rho (Time maturity) const
Sensitivity to discounting rate.
Definition at line 318 of file blackcalculator.cpp.
References alpha_, DalphaDd1_, DbetaDd2_, discount_, forward_, QL_REQUIRE, stdDev_, value(), and x_.
Referenced by QuantLib::AnalyticPerformanceEngine::calculate(), QuantLib::AnalyticDividendEuropeanEngine::calculate(), QuantLib::BjerksundStenslandApproximationEngine::calculate(), QuantLib::AnalyticCliquetEngine::calculate(), QuantLib::BaroneAdesiWhaleyApproximationEngine::calculate(), QuantLib::AnalyticContinuousGeometricAveragePriceAsianEngine::calculate(), QuantLib::AnalyticDiscreteGeometricAveragePriceAsianEngine::calculate(), QuantLib::JuQuadraticApproximationEngine::calculate(), and QuantLib::AnalyticEuropeanEngine::calculate().
{
        QL_REQUIRE(maturity>=0.0,
                   "negative maturity not allowed");
        // actually DalphaDr / T
        Real DalphaDr = DalphaDd1_/stdDev_;
        Real DbetaDr  = DbetaDd2_/stdDev_;
        Real temp = DalphaDr * forward_ + alpha_ * forward_ + DbetaDr * x_;
        return maturity * (discount_ * temp - value());
    }
Real QuantLib::BlackCalculator::strikeSensitivity () const
Sensitivity to strike.
Definition at line 343 of file blackcalculator.cpp.
References beta_, DalphaDd1_, DbetaDd2_, discount_, DxDstrike_, forward_, stdDev_, strike_, and x_.
Referenced by QuantLib::BjerksundStenslandApproximationEngine::calculate(), QuantLib::BaroneAdesiWhaleyApproximationEngine::calculate(), QuantLib::AnalyticDiscreteGeometricAveragePriceAsianEngine::calculate(), QuantLib::JuQuadraticApproximationEngine::calculate(), and QuantLib::AnalyticEuropeanEngine::calculate().
{
        Real temp = stdDev_*strike_;
        Real DalphaDstrike = -DalphaDd1_/temp;
        Real DbetaDstrike  = -DbetaDd2_/temp;
        Real temp2 =
            DalphaDstrike * forward_ + DbetaDstrike * x_ + beta_ * DxDstrike_;
        return discount_ * temp2;
    }
Real QuantLib::BlackCalculator::theta (Real spot, Time maturity) const [virtual]
Sensitivity to time to maturity.
Definition at line 292 of file blackcalculator.cpp.
References QuantLib::close(), delta(), discount_, forward_, gamma(), QL_REQUIRE, value(), and variance_.
Referenced by QuantLib::AnalyticDividendEuropeanEngine::calculate(), QuantLib::BjerksundStenslandApproximationEngine::calculate(), QuantLib::BaroneAdesiWhaleyApproximationEngine::calculate(), QuantLib::AnalyticContinuousGeometricAveragePriceAsianEngine::calculate(), QuantLib::JuQuadraticApproximationEngine::calculate(), QuantLib::AnalyticEuropeanEngine::calculate(), and thetaPerDay().
{
        QL_REQUIRE(maturity>=0.0,
                   "maturity (" << maturity << ") must be non-negative");
        if (close(maturity, 0.0)) return 0.0;
        return -( std::log(discount_)            * value()
                 +std::log(forward_/spot) * spot * delta(spot)
                 +0.5*variance_ * spot  * spot * gamma(spot))/maturity;
    }
Real QuantLib::BlackCalculator::thetaPerDay (Real spot, Time maturity) const [inline, virtual]
Sensitivity to time to maturity per day, assuming 365 day per year.
Definition at line 118 of file blackcalculator.hpp.
References theta().
Referenced by QuantLib::BjerksundStenslandApproximationEngine::calculate(), QuantLib::BaroneAdesiWhaleyApproximationEngine::calculate(), QuantLib::JuQuadraticApproximationEngine::calculate(), and QuantLib::AnalyticEuropeanEngine::calculate().
{
        return theta(spot, maturity)/365.0;
    }
Real QuantLib::BlackCalculator::value () const
Definition at line 199 of file blackcalculator.cpp.
References alpha_, beta_, discount_, forward_, and x_.
Referenced by QuantLib::AnalyticPerformanceEngine::calculate(), QuantLib::AnalyticDividendEuropeanEngine::calculate(), QuantLib::BjerksundStenslandApproximationEngine::calculate(), QuantLib::AnalyticCliquetEngine::calculate(), QuantLib::KirkEngine::calculate(), QuantLib::BaroneAdesiWhaleyApproximationEngine::calculate(), QuantLib::AnalyticDiscreteGeometricAveragePriceAsianEngine::calculate(), QuantLib::AnalyticContinuousGeometricAveragePriceAsianEngine::calculate(), QuantLib::FDStepConditionEngine< Scheme >::calculate(), QuantLib::JuQuadraticApproximationEngine::calculate(), QuantLib::AnalyticEuropeanEngine::calculate(), anonymous_namespace{marketmodel.cpp}::checkForwardsAndOptionlets(), elasticity(), elasticityForward(), QuantLib::anonymous_namespace{analyticvariancegammaengine.cpp}::Integrand::operator()(), rho(), MarketModelTest::testGreeks(), MarketModelTest::testPathwiseGreeks(), MarketModelTest::testPathwiseVegas(), SwapForwardMappingsTest::testSwaptionImpliedVolatility(), and theta().
{
        Real result = discount_ * (forward_ * alpha_ + x_ * beta_);
        return result;
    }
Real QuantLib::BlackCalculator::vega (Time maturity) const
Sensitivity to volatility.
Definition at line 303 of file blackcalculator.cpp.
References DalphaDd1_, DbetaDd2_, discount_, forward_, QL_REQUIRE, strike_, variance_, and x_.
Referenced by QuantLib::AnalyticPerformanceEngine::calculate(), QuantLib::AnalyticDividendEuropeanEngine::calculate(), QuantLib::BjerksundStenslandApproximationEngine::calculate(), QuantLib::AnalyticCliquetEngine::calculate(), QuantLib::BaroneAdesiWhaleyApproximationEngine::calculate(), QuantLib::AnalyticContinuousGeometricAveragePriceAsianEngine::calculate(), QuantLib::JuQuadraticApproximationEngine::calculate(), and QuantLib::AnalyticEuropeanEngine::calculate().
{
        QL_REQUIRE(maturity>=0.0,
                   "negative maturity not allowed");
        Real temp = std::log(strike_/forward_)/variance_;
        // actually DalphaDsigma / SQRT(T)
        Real DalphaDsigma = DalphaDd1_*(temp+0.5);
        Real DbetaDsigma  = DbetaDd2_ *(temp-0.5);
        Real temp2 = DalphaDsigma * forward_ + DbetaDsigma * x_;
        return discount_ * std::sqrt(maturity) * temp2;
    }
Friends And Related Function Documentation
friend class Calculator [friend]
Definition at line 39 of file blackcalculator.hpp.
Member Data Documentation
Real QuantLib::BlackCalculator::alpha_ [protected]
Definition at line 112 of file blackcalculator.hpp.
Referenced by alpha(), delta(), deltaForward(), dividendRho(), initialize(), rho(), and value().
Real QuantLib::BlackCalculator::beta_ [protected]
Definition at line 112 of file blackcalculator.hpp.
Referenced by beta(), delta(), initialize(), strikeSensitivity(), and value().
Real QuantLib::BlackCalculator::cum_d1_ [protected]
Definition at line 113 of file blackcalculator.hpp.
Referenced by initialize(), and itmAssetProbability().
Real QuantLib::BlackCalculator::cum_d2_ [protected]
Definition at line 113 of file blackcalculator.hpp.
Referenced by initialize(), and itmCashProbability().
Real QuantLib::BlackCalculator::d1_ [protected]
Definition at line 111 of file blackcalculator.hpp.
Referenced by gamma(), gammaForward(), and initialize().
Real QuantLib::BlackCalculator::d2_ [protected]
Definition at line 111 of file blackcalculator.hpp.
Referenced by gamma(), gammaForward(), and initialize().
Real QuantLib::BlackCalculator::DalphaDd1_ [protected]
Definition at line 112 of file blackcalculator.hpp.
Referenced by delta(), deltaForward(), dividendRho(), gamma(), gammaForward(), initialize(), rho(), strikeSensitivity(), and vega().
Real QuantLib::BlackCalculator::DbetaDd2_ [protected]
Definition at line 112 of file blackcalculator.hpp.
Referenced by delta(), deltaForward(), dividendRho(), gamma(), gammaForward(), initialize(), rho(), strikeSensitivity(), and vega().
Real QuantLib::BlackCalculator::discount_ [protected]
Definition at line 110 of file blackcalculator.hpp.
Referenced by delta(), deltaForward(), dividendRho(), gamma(), gammaForward(), initialize(), rho(), strikeSensitivity(), theta(), value(), and vega().
Real QuantLib::BlackCalculator::DxDs_ [protected]
Definition at line 114 of file blackcalculator.hpp.
Referenced by delta(), gamma(), and initialize().
Real QuantLib::BlackCalculator::DxDstrike_ [protected]
Definition at line 114 of file blackcalculator.hpp.
Referenced by initialize(), and strikeSensitivity().
Real QuantLib::BlackCalculator::forward_ [protected]
Definition at line 110 of file blackcalculator.hpp.
Referenced by delta(), deltaForward(), dividendRho(), elasticityForward(), gamma(), gammaForward(), initialize(), rho(), strikeSensitivity(), theta(), value(), and vega().
Real QuantLib::BlackCalculator::n_d1_ [protected]
Definition at line 113 of file blackcalculator.hpp.
Referenced by initialize().
Real QuantLib::BlackCalculator::n_d2_ [protected]
Definition at line 113 of file blackcalculator.hpp.
Referenced by initialize().
Real QuantLib::BlackCalculator::stdDev_ [protected]
Definition at line 110 of file blackcalculator.hpp.
Referenced by delta(), deltaForward(), dividendRho(), gamma(), gammaForward(), initialize(), rho(), and strikeSensitivity().
Real QuantLib::BlackCalculator::strike_ [protected]
Definition at line 110 of file blackcalculator.hpp.
Referenced by initialize(), strikeSensitivity(), and vega().
Real QuantLib::BlackCalculator::variance_ [protected]
Definition at line 110 of file blackcalculator.hpp.
Referenced by theta(), and vega().
Real QuantLib::BlackCalculator::x_ [protected]
Definition at line 114 of file blackcalculator.hpp.
Referenced by delta(), deltaForward(), dividendRho(), gamma(), gammaForward(), initialize(), rho(), strikeSensitivity(), value(), and vega().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/blackcalculator.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/blackcalculator.cpp