QuantLib: LiborMarketModelProcessTest Class Reference
LiborMarketModelProcessTest Class Reference
#include <libormarketmodelprocess.hpp>
Static Public Member Functions
static void testInitialisation ()
static void testLambdaBootstrapping ()
static void testMonteCarloCapletPricing ()
static
boost::unit_test_framework::test_suite * suite ()
Detailed Description
Definition at line 28 of file libormarketmodelprocess.hpp.
Member Function Documentation
test_suite * LiborMarketModelProcessTest::suite () [static]
Definition at line 335 of file libormarketmodelprocess.cpp.
References QUANTLIB_TEST_CASE, testInitialisation(), testLambdaBootstrapping(), and testMonteCarloCapletPricing().
Referenced by init_unit_test_suite().
{
    test_suite* suite = BOOST_TEST_SUITE("Libor market model process tests");
    suite->add(QUANTLIB_TEST_CASE(
         &LiborMarketModelProcessTest::testInitialisation));
    suite->add(QUANTLIB_TEST_CASE(
         &LiborMarketModelProcessTest::testLambdaBootstrapping));
    suite->add(QUANTLIB_TEST_CASE(
          &LiborMarketModelProcessTest::testMonteCarloCapletPricing));
    return suite;
}
void LiborMarketModelProcessTest::testInitialisation () [static]
Definition at line 111 of file libormarketmodelprocess.cpp.
References QuantLib::Calendar::adjust(), QuantLib::Calendar::advance(), anonymous_namespace{marketmodel.cpp}::calendar, anonymous_namespace{marketmodel.cpp}::dayCounter, QuantLib::Days, QuantLib::Settings::evaluationDate(), QuantLib::LiborForwardModelProcess::fixingTimes(), QuantLib::flatRate(), QuantLib::Following, QuantLib::Singleton< Settings >::instance(), QuantLib::RelinkableHandle< T >::linkTo(), QuantLib::LiborForwardModelProcess::nextIndexReset(), anonymous_namespace{marketmodel.cpp}::todaysDate, and QuantLib::Date::todaysDate().
Referenced by suite().
{
    BOOST_MESSAGE("Testing caplet LMM process initialisation...");
    SavedSettings backup;
    DayCounter dayCounter = Actual360();
    RelinkableHandle<YieldTermStructure> termStructure(
        flatRate(Date::todaysDate(), 0.04, dayCounter));
    boost::shared_ptr<IborIndex> index(new Euribor6M(termStructure));
    boost::shared_ptr<OptionletVolatilityStructure> capletVol(new
        ConstantOptionletVolatility(termStructure->referenceDate(),
                                    termStructure->calendar(),
                                    Following,
                                    0.2,
                                    termStructure->dayCounter()));
    Calendar calendar = index->fixingCalendar();
    for (Integer daysOffset=0; daysOffset < 1825 /* 5 year*/; daysOffset+=8) {
        Date todaysDate = calendar.adjust(Date::todaysDate()+daysOffset);
        Settings::instance().evaluationDate() = todaysDate;
        Date settlementDate =
            calendar.advance(todaysDate, index->fixingDays(), Days);
        termStructure.linkTo(flatRate(settlementDate, 0.04, dayCounter));
        LiborForwardModelProcess process(60, index);
        std::vector<Time> fixings = process.fixingTimes();
        for (Size i=1; i < fixings.size()-1; ++i) {
            Size ileft  = process.nextIndexReset(fixings[i]-0.000001);
            Size iright = process.nextIndexReset(fixings[i]+0.000001);
            Size ii     = process.nextIndexReset(fixings[i]);
            if ((ileft != i) || (iright != i+1) || (ii != i+1)) {
                BOOST_ERROR("Failed to next index resets");
            }
        }
    }
}
void LiborMarketModelProcessTest::testLambdaBootstrapping () [static]
Definition at line 154 of file libormarketmodelprocess.cpp.
References QuantLib::Matrix::columns(), anonymous_namespace{europeanoption.cpp}::makeProcess(), QuantLib::Matrix::rows(), anonymous_namespace{quantlibbenchmark.cpp}::t, and anonymous_namespace{gaussianquadratures.cpp}::tolerance.
Referenced by suite().
{
    BOOST_MESSAGE("Testing caplet LMM lambda bootstrapping...");
    SavedSettings backup;
    Real tolerance = 1e-10;
    Volatility lambdaExpected[]= {14.3010297550, 19.3821411939, 15.9816590141,
                                  15.9953118303, 14.0570815635, 13.5687599894,
                                  12.7477197786, 13.7056638165, 11.6191989567};
    boost::shared_ptr<LiborForwardModelProcess> process = makeProcess();
    Matrix covar = process->covariance(0.0, Null<Array>(), 1.0);
    for (Size i=0; i<9; ++i) {
        const Real calculated = std::sqrt(covar[i+1][i+1]);
        const Real expected   = lambdaExpected[i]/100;
        if (std::fabs(calculated - expected) > tolerance)
            BOOST_ERROR("Failed to reproduce expected lambda values"
                        << "\n    calculated: " << calculated
                        << "\n    expected:   " << expected);
    }
    boost::shared_ptr<LfmCovarianceParameterization> param =
        process->covarParam();
    std::vector<Time> tmp = process->fixingTimes();
    TimeGrid grid(tmp.begin(), tmp.end(), 14);
    for (Size t=0; t<grid.size(); ++t) {
        Matrix diff = (param->integratedCovariance(grid[t])
        - param->LfmCovarianceParameterization::integratedCovariance(grid[t]));
        for (Size i=0; i<diff.rows(); ++i) {
            for (Size j=0; j<diff.columns(); ++j) {
                if (std::fabs(diff[i][j]) > tolerance) {
                     BOOST_FAIL("Failed to reproduce integrated covariance" <<
                        "\n    i: " << i <<
                        "\n    j: " << j <<
                        "\nerror: " << diff[i][j]);
                }
            }
        }
    }
}
void LiborMarketModelProcessTest::testMonteCarloCapletPricing () [static]
Definition at line 201 of file libormarketmodelprocess.cpp.
References QuantLib::Matrix::begin(), QuantLib::GenericLowDiscrepancy< URSG, IC >::make_sequence_generator(), anonymous_namespace{europeanoption.cpp}::makeProcess(), and QuantLib::MultiPathGenerator< GSG >::next().
Referenced by suite().
{
    BOOST_MESSAGE("Testing caplet LMM Monte-Carlo caplet pricing...");
    SavedSettings backup;
    /* factor loadings are taken from Hull & White article
       plus extra normalisation to get orthogonal eigenvectors
       http://www.rotman.utoronto.ca/~amackay/fin/libormktmodel2.pdf */
    Real compValues[] = {0.85549771, 0.46707264, 0.22353259,
                         0.91915359, 0.37716089, 0.11360610,
                         0.96438280, 0.26413316,-0.01412414,
                         0.97939148, 0.13492952,-0.15028753,
                         0.95970595,-0.00000000,-0.28100621,
                         0.97939148,-0.13492952,-0.15028753,
                         0.96438280,-0.26413316,-0.01412414,
                         0.91915359,-0.37716089, 0.11360610,
                         0.85549771,-0.46707264, 0.22353259};
    Matrix volaComp(9,3);
    std::copy(compValues, compValues+9*3, volaComp.begin());
    boost::shared_ptr<LiborForwardModelProcess> process1 = makeProcess();
    boost::shared_ptr<LiborForwardModelProcess> process2 = makeProcess(
                                                                    volaComp);
    std::vector<Time> tmp = process1->fixingTimes();
    TimeGrid grid(tmp.begin(), tmp.end(),12);
    Size i;
    std::vector<Size> location;
    for (i=0; i < tmp.size(); ++i) {
        location.push_back(
                      std::find(grid.begin(),grid.end(),tmp[i])-grid.begin());
    }
    // set-up a small Monte-Carlo simulation to price caplets
    // and ratchet caps using a one- and a three factor libor market model
    typedef LowDiscrepancy::rsg_type rsg_type;
    typedef MultiPathGenerator<rsg_type>::sample_type sample_type;
    BigNatural seed = 42;
    rsg_type rsg1 = LowDiscrepancy::make_sequence_generator(
                            process1->factors()*(grid.size()-1), seed);
    rsg_type rsg2 = LowDiscrepancy::make_sequence_generator(
                            process2->factors()*(grid.size()-1), seed);
    MultiPathGenerator<rsg_type> generator1(process1, grid, rsg1, false);
    MultiPathGenerator<rsg_type> generator2(process2, grid, rsg2, false);
    const Size nrTrails = 250000;
    std::vector<GeneralStatistics> stat1(process1->size());
    std::vector<GeneralStatistics> stat2(process2->size());
    std::vector<GeneralStatistics> stat3(process2->size()-1);
    for (i=0; i<nrTrails; ++i) {
        sample_type path1 = generator1.next();
        sample_type path2 = generator2.next();
        std::vector<Rate> rates1(len);
        std::vector<Rate> rates2(len);
        for (Size j=0; j<process1->size(); ++j) {
            rates1[j] = path1.value[j][location[j]];
            rates2[j] = path2.value[j][location[j]];
        }
        std::vector<DiscountFactor> dis1 = process1->discountBond(rates1);
        std::vector<DiscountFactor> dis2 = process2->discountBond(rates2);
        for (Size k=0; k<process1->size(); ++k) {
            Real accrualPeriod =  process1->accrualEndTimes()[k]
                                - process1->accrualStartTimes()[k];
            // caplet payoff function, cap rate at 4%
            Real payoff1 = std::max(rates1[k] - 0.04, 0.0) * accrualPeriod;
            Real payoff2 = std::max(rates2[k] - 0.04, 0.0) * accrualPeriod;
            stat1[k].add(dis1[k] * payoff1);
            stat2[k].add(dis2[k] * payoff2);
            if (k != 0) {
                // ratchet cap payoff function
                Real payoff3 =  std::max(rates2[k] - (rates2[k-1]+0.0025), 0.0)
                              * accrualPeriod;
                stat3[k-1].add(dis2[k] * payoff3);
            }
        }
    }
    Real capletNpv[] = {0.000000000000, 0.000002841629, 0.002533279333,
                        0.009577143571, 0.017746502618, 0.025216116835,
                        0.031608230268, 0.036645683881, 0.039792254012,
                        0.041829864365};
    Real ratchetNpv[] = {0.0082644895, 0.0082754754, 0.0082159966,
                         0.0082982822, 0.0083803357, 0.0084366961,
                         0.0084173270, 0.0081803406, 0.0079533814};
    for (Size k=0; k < process1->size(); ++k) {
        Real calculated1 = stat1[k].mean();
        Real tolerance1  = stat1[k].errorEstimate();
        Real expected    = capletNpv[k];
        if (std::fabs(calculated1 - expected) > tolerance1) {
            BOOST_ERROR("Failed to reproduce expected caplet NPV"
                        << "\n    calculated: " << calculated1
                        << "\n    error int:  " << tolerance1
                        << "\n    expected:   " << expected);
        }
        Real calculated2 = stat2[k].mean();
        Real tolerance2  = stat2[k].errorEstimate();
        if (std::fabs(calculated2 - expected) > tolerance2) {
            BOOST_ERROR("Failed to reproduce expected caplet NPV"
                        << "\n    calculated: " << calculated2
                        << "\n    error int:  " << tolerance2
                        << "\n    expected:   " << expected);
        }
        if (k != 0) {
            Real calculated3 = stat3[k-1].mean();
            Real tolerance3  = stat3[k-1].errorEstimate();
            expected    = ratchetNpv[k-1];
            Real refError = 1e-5; // 1e-5. error bars of the reference values
            if (std::fabs(calculated3 - expected) > tolerance3 + refError) {
                BOOST_ERROR("Failed to reproduce expected caplet NPV"
                            << "\n    calculated: " << calculated3
                            << "\n    error int:  " << tolerance3 + refError
                            << "\n    expected:   " << expected);
            }
        }
    }
}
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/libormarketmodelprocess.hpp
/home/deriversatile/QuantLib/QuantLibQt/test-suite/libormarketmodelprocess.cpp