QuantLib: QuantLib::OneStepForwards Class Reference
QuantLib::OneStepForwards Class Reference
#include <onestepforwards.hpp>
Public Member Functions
OneStepForwards (const std::vector< Time > &rateTimes, const std::vector< Real > &accruals, const std::vector< Time > &paymentTimes, const std::vector< Rate > &strikes)
MarketModelMultiProduct interface
std::vector< Time > possibleCashFlowTimes () const
Size numberOfProducts () const
Size maxNumberOfCashFlowsPerProductPerStep () const
void reset ()
during simulation put product at start of path
bool nextTimeStep (const CurveState &currentState, std::vector< Size > &numberCashFlowsThisStep, std::vector< std::vector< CashFlow > > &cashFlowsGenerated)
return value indicates whether path is finished, TRUE means done
std::auto_ptr
< MarketModelMultiProduct > clone () const
returns a newly-allocated copy of itself
Private Attributes
std::vector< Real > accruals_
std::vector< Time > paymentTimes_
std::vector< Rate > strikes_
Detailed Description
Definition at line 28 of file onestepforwards.hpp.
Constructor & Destructor Documentation
QuantLib::OneStepForwards::OneStepForwards (const std::vector< Time > & rateTimes, const std::vector< Real > & accruals, const std::vector< Time > & paymentTimes, const std::vector< Rate > & strikes)
Definition at line 26 of file onestepforwards.cpp.
References QuantLib::checkIncreasingTimes().
Referenced by clone().
    : MultiProductOneStep(rateTimes), accruals_(accruals),
      paymentTimes_(paymentTimes), strikes_(strikes) {
        checkIncreasingTimes(paymentTimes);
    }
Member Function Documentation
std::auto_ptr< MarketModelMultiProduct > QuantLib::OneStepForwards::clone () const [virtual]
returns a newly-allocated copy of itself
Implements QuantLib::MarketModelMultiProduct.
Definition at line 52 of file onestepforwards.cpp.
References OneStepForwards().
{
        return std::auto_ptr<MarketModelMultiProduct>(
                                                  new OneStepForwards(*this));
    }
Size QuantLib::OneStepForwards::maxNumberOfCashFlowsPerProductPerStep () const [inline, virtual]
Implements QuantLib::MarketModelMultiProduct.
Definition at line 65 of file onestepforwards.hpp.
{
        return 1;
    }
bool QuantLib::OneStepForwards::nextTimeStep (const CurveState & currentState, std::vector< Size > & numberCashFlowsThisStep, std::vector< std::vector< CashFlow > > & cashFlowsGenerated) [virtual]
return value indicates whether path is finished, TRUE means done
Implements QuantLib::MarketModelMultiProduct.
Definition at line 35 of file onestepforwards.cpp.
References accruals_, QuantLib::CurveState::forwardRate(), and strikes_.
{
        for (Size i=0; i<strikes_.size(); ++i) {
            Rate liborRate = currentState.forwardRate(i);
            genCashFlows[i][0].timeIndex = i;
            genCashFlows[i][0].amount =
                (liborRate-strikes_[i])*accruals_[i];
        }
        std::fill(numberCashFlowsThisStep.begin(),
                  numberCashFlowsThisStep.end(), 1);
        return true;
    }
Size QuantLib::OneStepForwards::numberOfProducts () const [inline, virtual]
Implements QuantLib::MarketModelMultiProduct.
Definition at line 60 of file onestepforwards.hpp.
References strikes_.
{
        return strikes_.size();
    }
std::vector< Time > QuantLib::OneStepForwards::possibleCashFlowTimes () const [inline, virtual]
Implements QuantLib::MarketModelMultiProduct.
Definition at line 55 of file onestepforwards.hpp.
References paymentTimes_.
{
      return paymentTimes_;
    }
void QuantLib::OneStepForwards::reset () [inline, virtual]
during simulation put product at start of path
Implements QuantLib::MarketModelMultiProduct.
Definition at line 70 of file onestepforwards.hpp.
{
        // nothing to do
    }
Member Data Documentation
std::vector<Real> QuantLib::OneStepForwards::accruals_ [private]
Definition at line 47 of file onestepforwards.hpp.
Referenced by nextTimeStep().
std::vector<Time> QuantLib::OneStepForwards::paymentTimes_ [private]
Definition at line 48 of file onestepforwards.hpp.
Referenced by possibleCashFlowTimes().
std::vector<Rate> QuantLib::OneStepForwards::strikes_ [private]
Definition at line 49 of file onestepforwards.hpp.
Referenced by nextTimeStep(), and numberOfProducts().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/products/onestep/onestepforwards.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/products/onestep/onestepforwards.cpp