QuantLib: QuantLib::RandomSequenceGenerator< RNG > Class Template Reference
QuantLib::RandomSequenceGenerator< RNG > Class Template Reference
Random sequence generator based on a pseudo-random number generator.
#include <randomsequencegenerator.hpp>
Public Types
typedef Sample< std::vector
< Real > > sample_type
Public Member Functions
RandomSequenceGenerator (Size dimensionality, const RNG &rng)
RandomSequenceGenerator (Size dimensionality, BigNatural seed=0)
const sample_type & nextSequence () const
std::vector< BigNatural > nextInt32Sequence () const
const sample_type & lastSequence () const
Size dimension () const
Private Attributes
Size dimensionality_
RNG rng_
sample_type sequence_
std::vector< BigNatural > int32Sequence_
Detailed Description
template<class RNG>
class QuantLib::RandomSequenceGenerator< RNG >
Random sequence generator based on a pseudo-random number generator.
Random sequence generator based on a pseudo-random number generator RNG.
Class RNG must implement the following interface:
            RNG::sample_type RNG::next() const;
If a client of this class wants to use the nextInt32Sequence method, class RNG must also implement
            unsigned long RNG::nextInt32() const;
Warning:
do not use with low-discrepancy sequence generator.
Definition at line 50 of file randomsequencegenerator.hpp.
Member Typedef Documentation
template<class RNG> typedef Sample<std::vector<Real> > QuantLib::RandomSequenceGenerator< RNG >::sample_type
Definition at line 52 of file randomsequencegenerator.hpp.
Constructor & Destructor Documentation
template<class RNG> QuantLib::RandomSequenceGenerator< RNG >::RandomSequenceGenerator (Size dimensionality, const RNG & rng) [inline]
Definition at line 53 of file randomsequencegenerator.hpp.
        : dimensionality_(dimensionality), rng_(rng),
          sequence_(std::vector<Real> (dimensionality), 1.0),
          int32Sequence_(dimensionality) {
          QL_REQUIRE(dimensionality>0,
                     "dimensionality must be greater than 0");
        }
template<class RNG> QuantLib::RandomSequenceGenerator< RNG >::RandomSequenceGenerator (Size dimensionality, BigNatural seed = 0) [inline]
Definition at line 62 of file randomsequencegenerator.hpp.
        : dimensionality_(dimensionality), rng_(seed),
          sequence_(std::vector<Real> (dimensionality), 1.0),
          int32Sequence_(dimensionality) {}
Member Function Documentation
template<class RNG> Size QuantLib::RandomSequenceGenerator< RNG >::dimension () const [inline]
Definition at line 86 of file randomsequencegenerator.hpp.
{return dimensionality_;}
template<class RNG> const sample_type& QuantLib::RandomSequenceGenerator< RNG >::lastSequence () const [inline]
Definition at line 83 of file randomsequencegenerator.hpp.
Referenced by QuantLib::MTBrownianGenerator::nextStep().
{
            return sequence_;
        }
template<class RNG> std::vector<BigNatural> QuantLib::RandomSequenceGenerator< RNG >::nextInt32Sequence () const [inline]
Definition at line 77 of file randomsequencegenerator.hpp.
Referenced by QuantLib::HaltonRsg::HaltonRsg().
{
            for (Size i=0; i<dimensionality_; i++) {
                int32Sequence_[i] = rng_.nextInt32();
            }
            return int32Sequence_;
        }
template<class RNG> const sample_type& QuantLib::RandomSequenceGenerator< RNG >::nextSequence () const [inline]
Definition at line 68 of file randomsequencegenerator.hpp.
Referenced by QuantLib::HaltonRsg::HaltonRsg(), QuantLib::MTBrownianGenerator::nextPath(), QuantLib::DigitalPathPricer::operator()(), and QuantLib::BarrierPathPricer::operator()().
{
            sequence_.weight = 1.0;
            for (Size i=0; i<dimensionality_; i++) {
                typename RNG::sample_type x(rng_.next());
                sequence_.value[i] = x.value;
                sequence_.weight  *= x.weight;
            }
            return sequence_;
        }
Member Data Documentation
template<class RNG> Size QuantLib::RandomSequenceGenerator< RNG >::dimensionality_ [private]
Definition at line 88 of file randomsequencegenerator.hpp.
Referenced by QuantLib::RandomSequenceGenerator< MersenneTwisterUniformRng >::dimension(), QuantLib::RandomSequenceGenerator< MersenneTwisterUniformRng >::nextInt32Sequence(), and QuantLib::RandomSequenceGenerator< MersenneTwisterUniformRng >::nextSequence().
template<class RNG> std::vector<BigNatural> QuantLib::RandomSequenceGenerator< RNG >::int32Sequence_ [mutable, private]
Definition at line 91 of file randomsequencegenerator.hpp.
Referenced by QuantLib::RandomSequenceGenerator< MersenneTwisterUniformRng >::nextInt32Sequence().
template<class RNG> RNG QuantLib::RandomSequenceGenerator< RNG >::rng_ [private]
Definition at line 89 of file randomsequencegenerator.hpp.
Referenced by QuantLib::RandomSequenceGenerator< MersenneTwisterUniformRng >::nextInt32Sequence(), and QuantLib::RandomSequenceGenerator< MersenneTwisterUniformRng >::nextSequence().
template<class RNG> sample_type QuantLib::RandomSequenceGenerator< RNG >::sequence_ [mutable, private]
Definition at line 90 of file randomsequencegenerator.hpp.
Referenced by QuantLib::RandomSequenceGenerator< MersenneTwisterUniformRng >::lastSequence(), and QuantLib::RandomSequenceGenerator< MersenneTwisterUniformRng >::nextSequence().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/randomnumbers/randomsequencegenerator.hpp