QuantLib: QuantLib::MultiAssetOption Class Reference
QuantLib::MultiAssetOption Class Reference
Base class for options on multiple assets.
#include <multiassetoption.hpp>
Classes
class engine
class results
Results from multi-asset option calculation
Public Member Functions
MultiAssetOption (const boost::shared_ptr< Payoff > &, const boost::shared_ptr< Exercise > &)
void setupArguments (PricingEngine::arguments *) const
void fetchResults (const PricingEngine::results *) const
Instrument interface
bool isExpired () const
returns whether the instrument might have value greater than zero.
greeks
Real delta () const
Real gamma () const
Real theta () const
Real vega () const
Real rho () const
Real dividendRho () const
Protected Member Functions
void setupExpired () const
Protected Attributes
Real delta_
Real gamma_
Real theta_
Real vega_
Real rho_
Real dividendRho_
Detailed Description
Base class for options on multiple assets.
Definition at line 34 of file multiassetoption.hpp.
Constructor & Destructor Documentation
QuantLib::MultiAssetOption::MultiAssetOption (const boost::shared_ptr< Payoff > & payoff, const boost::shared_ptr< Exercise > & exercise)
Definition at line 29 of file multiassetoption.cpp.
    : Option(payoff, exercise) {}
Member Function Documentation
Real QuantLib::MultiAssetOption::delta () const
Definition at line 38 of file multiassetoption.cpp.
References QuantLib::Instrument::calculate(), delta_, and QL_REQUIRE.
{
        calculate();
        QL_REQUIRE(delta_ != Null<Real>(), "delta not provided");
        return delta_;
    }
Real QuantLib::MultiAssetOption::dividendRho () const
Definition at line 68 of file multiassetoption.cpp.
References QuantLib::Instrument::calculate(), dividendRho_, and QL_REQUIRE.
{
        calculate();
        QL_REQUIRE(dividendRho_ != Null<Real>(), "dividend rho not provided");
        return dividendRho_;
    }
void QuantLib::MultiAssetOption::fetchResults (const PricingEngine::results * r) const [virtual]
When a derived result structure is defined for an instrument, this method should be overridden to read from it. This is mandatory in case a pricing engine is used.
Reimplemented from QuantLib::Instrument.
Reimplemented in QuantLib::MargrabeOption, and QuantLib::EverestOption.
Definition at line 89 of file multiassetoption.cpp.
References QuantLib::Greeks::delta, delta_, QuantLib::Greeks::dividendRho, dividendRho_, QuantLib::Greeks::gamma, gamma_, QL_ENSURE, QuantLib::Greeks::rho, rho_, QuantLib::Greeks::theta, theta_, QuantLib::Greeks::vega, and vega_.
{
        Option::fetchResults(r);
        const Greeks* results = dynamic_cast<const Greeks*>(r);
        QL_ENSURE(results != 0,
                  "no greeks returned from pricing engine");
        delta_          = results->delta;
        gamma_          = results->gamma;
        theta_          = results->theta;
        vega_           = results->vega;
        rho_            = results->rho;
        dividendRho_    = results->dividendRho;
    }
Real QuantLib::MultiAssetOption::gamma () const
Definition at line 44 of file multiassetoption.cpp.
References QuantLib::Instrument::calculate(), gamma_, and QL_REQUIRE.
{
        calculate();
        QL_REQUIRE(gamma_ != Null<Real>(), "gamma not provided");
        return gamma_;
    }
bool QuantLib::MultiAssetOption::isExpired () const [virtual]
returns whether the instrument might have value greater than zero.
Implements QuantLib::Instrument.
Reimplemented in QuantLib::VanillaVPPOption.
Definition at line 34 of file multiassetoption.cpp.
References QuantLib::Option::exercise_.
{
        return detail::simple_event(exercise_->lastDate()).hasOccurred();
    }
Real QuantLib::MultiAssetOption::rho () const
Definition at line 62 of file multiassetoption.cpp.
References QuantLib::Instrument::calculate(), QL_REQUIRE, and rho_.
Referenced by MargrabeOptionTest::testEuroExchangeTwoAssets(), and MargrabeOptionTest::testGreeks().
{
        calculate();
        QL_REQUIRE(rho_ != Null<Real>(), "rho not provided");
        return rho_;
    }
void QuantLib::MultiAssetOption::setupArguments (PricingEngine::arguments *) const [virtual]
When a derived argument structure is defined for an instrument, this method should be overridden to fill it. This is mandatory in case a pricing engine is used.
Reimplemented from QuantLib::Option.
Reimplemented in QuantLib::HimalayaOption, QuantLib::PagodaOption, QuantLib::MargrabeOption, QuantLib::VanillaVPPOption, and QuantLib::EverestOption.
Definition at line 79 of file multiassetoption.cpp.
References QuantLib::Option::arguments::exercise, QuantLib::Option::exercise_, QuantLib::Option::arguments::payoff, QuantLib::Option::payoff_, and QL_REQUIRE.
{
        MultiAssetOption::arguments* arguments =
            dynamic_cast<MultiAssetOption::arguments*>(args);
        QL_REQUIRE(arguments != 0, "wrong argument type");
        arguments->payoff = payoff_;
        arguments->exercise = exercise_;
    }
void QuantLib::MultiAssetOption::setupExpired () const [protected, virtual]
This method must leave the instrument in a consistent state when the expiration condition is met.
Reimplemented from QuantLib::Instrument.
Definition at line 74 of file multiassetoption.cpp.
References delta_, dividendRho_, gamma_, QuantLib::Instrument::NPV_, rho_, theta_, and vega_.
{
        NPV_ = delta_ = gamma_ = theta_ =
            vega_ = rho_ = dividendRho_ =  0.0;
    }
Real QuantLib::MultiAssetOption::theta () const
Definition at line 50 of file multiassetoption.cpp.
References QuantLib::Instrument::calculate(), QL_REQUIRE, and theta_.
Referenced by MargrabeOptionTest::testEuroExchangeTwoAssets(), and MargrabeOptionTest::testGreeks().
{
        calculate();
        QL_REQUIRE(theta_ != Null<Real>(), "theta not provided");
        return theta_;
    }
Real QuantLib::MultiAssetOption::vega () const
Definition at line 56 of file multiassetoption.cpp.
References QuantLib::Instrument::calculate(), QL_REQUIRE, and vega_.
{
        calculate();
        QL_REQUIRE(vega_ != Null<Real>(), "vega not provided");
        return vega_;
    }
Member Data Documentation
Real QuantLib::MultiAssetOption::delta_ [mutable, protected]
Definition at line 59 of file multiassetoption.hpp.
Referenced by delta(), fetchResults(), and setupExpired().
Real QuantLib::MultiAssetOption::dividendRho_ [mutable, protected]
Definition at line 59 of file multiassetoption.hpp.
Referenced by dividendRho(), fetchResults(), and setupExpired().
Real QuantLib::MultiAssetOption::gamma_ [mutable, protected]
Definition at line 59 of file multiassetoption.hpp.
Referenced by fetchResults(), gamma(), and setupExpired().
Real QuantLib::MultiAssetOption::rho_ [mutable, protected]
Definition at line 59 of file multiassetoption.hpp.
Referenced by fetchResults(), rho(), and setupExpired().
Real QuantLib::MultiAssetOption::theta_ [mutable, protected]
Definition at line 59 of file multiassetoption.hpp.
Referenced by fetchResults(), setupExpired(), and theta().
Real QuantLib::MultiAssetOption::vega_ [mutable, protected]
Definition at line 59 of file multiassetoption.hpp.
Referenced by fetchResults(), setupExpired(), and vega().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/multiassetoption.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/multiassetoption.cpp