QuantLib: QuantLib::NullPayoff Class Reference
QuantLib::NullPayoff Class Reference
Dummy payoff class.
#include <payoffs.hpp>
Public Member Functions
Payoff interface
std::string name () const
std::string description () const
Real operator() (Real price) const
virtual void accept (AcyclicVisitor &)
Detailed Description
Dummy payoff class.
Definition at line 36 of file payoffs.hpp.
Member Function Documentation
void QuantLib::NullPayoff::accept (AcyclicVisitor & v) [virtual]
Reimplemented from QuantLib::Payoff.
Definition at line 39 of file payoffs.cpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Visitor< T >::visit().
{
        Visitor<NullPayoff>* v1 =
            dynamic_cast<Visitor<NullPayoff>*>(&v);
        if (v1 != 0)
            v1->visit(*this);
        else
            Payoff::accept(v);
    }
std::string QuantLib::NullPayoff::description () const [virtual]
Implements QuantLib::Payoff.
Definition at line 31 of file payoffs.cpp.
References name().
{
        return name();
    }
std::string QuantLib::NullPayoff::name () const [virtual]
Warning:
This method is used for output and comparison between payoffs. It is not meant to be used for writing switch-on-type code.
Implements QuantLib::Payoff.
Definition at line 27 of file payoffs.cpp.
Referenced by description().
{
        return "Null";
    }
Real QuantLib::NullPayoff::operator() (Real price) const [virtual]
Implements QuantLib::Payoff.
Definition at line 35 of file payoffs.cpp.
References QL_FAIL.
{
        QL_FAIL("dummy payoff given");
    }
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/payoffs.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/payoffs.cpp