QuantLib: QuantLib::GaussianOrthogonalPolynomial Class Reference
QuantLib::GaussianOrthogonalPolynomial Class Reference
orthogonal polynomial for Gaussian quadratures
#include <gaussianorthogonalpolynomial.hpp>
Public Member Functions
virtual ~GaussianOrthogonalPolynomial ()
virtual Real mu_0 () const =0
virtual Real alpha (Size i) const =0
virtual Real beta (Size i) const =0
virtual Real w (Real x) const =0
Real value (Size i, Real x) const
Real weightedValue (Size i, Real x) const
Detailed Description
orthogonal polynomial for Gaussian quadratures
References: Gauss quadratures and orthogonal polynomials
G.H. Gloub and J.H. Welsch: Calculation of Gauss quadrature rule. Math. Comput. 23 (1986), 221-230
"Numerical Recipes in C", 2nd edition, Press, Teukolsky, Vetterling, Flannery,
The polynomials are defined by the three-term recurrence relation
\[ P_{k+1}(x)=(x-\alpha_k) P_k(x) - \beta_k P_{k-1}(x) \]
and
\[ \mu_0 = \int{w(x)dx} \]
Definition at line 50 of file gaussianorthogonalpolynomial.hpp.
Constructor & Destructor Documentation
virtual QuantLib::GaussianOrthogonalPolynomial::~GaussianOrthogonalPolynomial () [inline, virtual]
Definition at line 52 of file gaussianorthogonalpolynomial.hpp.
{}
Member Function Documentation
virtual Real QuantLib::GaussianOrthogonalPolynomial::alpha (Size i) const [pure virtual]
Implemented in QuantLib::GaussHyperbolicPolynomial, QuantLib::GaussJacobiPolynomial, QuantLib::GaussHermitePolynomial, and QuantLib::GaussLaguerrePolynomial.
Referenced by QuantLib::GaussianQuadrature::GaussianQuadrature(), and value().
virtual Real QuantLib::GaussianOrthogonalPolynomial::beta (Size i) const [pure virtual]
Implemented in QuantLib::GaussHyperbolicPolynomial, QuantLib::GaussJacobiPolynomial, QuantLib::GaussHermitePolynomial, and QuantLib::GaussLaguerrePolynomial.
Referenced by QuantLib::GaussianQuadrature::GaussianQuadrature(), and value().
virtual Real QuantLib::GaussianOrthogonalPolynomial::mu_0 () const [pure virtual]
Implemented in QuantLib::GaussHyperbolicPolynomial, QuantLib::GaussJacobiPolynomial, QuantLib::GaussHermitePolynomial, and QuantLib::GaussLaguerrePolynomial.
Referenced by QuantLib::GaussianQuadrature::GaussianQuadrature().
Real QuantLib::GaussianOrthogonalPolynomial::value (Size i, Real x) const
Definition at line 31 of file gaussianorthogonalpolynomial.cpp.
References alpha(), and beta().
Referenced by weightedValue().
{
        if (n > 1) {
            return  (x-alpha(n-1)) * value(n-1, x)
                       - beta(n-1) * value(n-2, x);
        }
        else if (n == 1) {
            return x-alpha(0);
        }
        return 1;
    }
virtual Real QuantLib::GaussianOrthogonalPolynomial::w (Real x) const [pure virtual]
Implemented in QuantLib::GaussHyperbolicPolynomial, QuantLib::GaussJacobiPolynomial, QuantLib::GaussHermitePolynomial, and QuantLib::GaussLaguerrePolynomial.
Referenced by QuantLib::GaussianQuadrature::GaussianQuadrature(), and weightedValue().
Real QuantLib::GaussianOrthogonalPolynomial::weightedValue (Size i, Real x) const
Definition at line 43 of file gaussianorthogonalpolynomial.cpp.
References value(), and w().
{
        return std::sqrt(w(x))*value(n, x);
    }
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/integrals/gaussianorthogonalpolynomial.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/math/integrals/gaussianorthogonalpolynomial.cpp