QuantLib: GaussianQuadraturesTest Class Reference
GaussianQuadraturesTest Class Reference
#include <gaussianquadratures.hpp>
Static Public Member Functions
static void testJacobi ()
static void testLaguerre ()
static void testHermite ()
static void testHyperbolic ()
static void testTabulated ()
static
boost::unit_test_framework::test_suite * suite ()
Detailed Description
Definition at line 28 of file gaussianquadratures.hpp.
Member Function Documentation
test_suite * GaussianQuadraturesTest::suite () [static]
Definition at line 177 of file gaussianquadratures.cpp.
References QUANTLIB_TEST_CASE, testHermite(), testHyperbolic(), testJacobi(), testLaguerre(), and testTabulated().
Referenced by init_unit_test_suite().
{
    test_suite* suite = BOOST_TEST_SUITE("Gaussian quadratures tests");
    suite->add(QUANTLIB_TEST_CASE(&GaussianQuadraturesTest::testJacobi));
    suite->add(QUANTLIB_TEST_CASE(&GaussianQuadraturesTest::testLaguerre));
    suite->add(QUANTLIB_TEST_CASE(&GaussianQuadraturesTest::testHermite));
    suite->add(QUANTLIB_TEST_CASE(&GaussianQuadraturesTest::testHyperbolic));
    suite->add(QUANTLIB_TEST_CASE(&GaussianQuadraturesTest::testTabulated));
    return suite;
}
void GaussianQuadraturesTest::testHermite () [static]
Definition at line 141 of file gaussianquadratures.cpp.
References anonymous_namespace{gaussianquadratures.cpp}::testSingle(), anonymous_namespace{gaussianquadratures.cpp}::x_normaldistribution(), and anonymous_namespace{gaussianquadratures.cpp}::x_x_normaldistribution().
Referenced by suite().
{
     BOOST_MESSAGE("Testing Gauss-Hermite integration...");
     testSingle(GaussHermiteIntegration(16), "f(x) = Gaussian(x)",
                NormalDistribution(), 1.0);
     testSingle(GaussHermiteIntegration(16,0.5), "f(x) = x*Gaussian(x)",
                std::ptr_fun<Real,Real>(x_normaldistribution), 0.0);
     testSingle(GaussHermiteIntegration(64,0.9), "f(x) = x*x*Gaussian(x)",
                std::ptr_fun<Real,Real>(x_x_normaldistribution), 1.0);
}
void GaussianQuadraturesTest::testHyperbolic () [static]
Definition at line 152 of file gaussianquadratures.cpp.
References anonymous_namespace{gaussianquadratures.cpp}::inv_cosh(), M_PI, anonymous_namespace{gaussianquadratures.cpp}::testSingle(), and anonymous_namespace{gaussianquadratures.cpp}::x_inv_cosh().
Referenced by suite().
{
     BOOST_MESSAGE("Testing Gauss hyperbolic integration...");
     testSingle(GaussHyperbolicIntegration(16), "f(x) = 1/cosh(x)",
                std::ptr_fun<Real,Real>(inv_cosh), M_PI);
     testSingle(GaussHyperbolicIntegration(16), "f(x) = x/cosh(x)",
                std::ptr_fun<Real,Real>(x_inv_cosh), 0.0);
}
void GaussianQuadraturesTest::testJacobi () [static]
Definition at line 120 of file gaussianquadratures.cpp.
References anonymous_namespace{gaussianquadratures.cpp}::testSingleJacobi().
Referenced by suite().
{
    BOOST_MESSAGE("Testing Gauss-Jacobi integration...");
    testSingleJacobi(GaussLegendreIntegration(16));
    testSingleJacobi(GaussChebyshevIntegration(130));
    testSingleJacobi(GaussChebyshev2ndIntegration(130));
    testSingleJacobi(GaussGegenbauerIntegration(50,0.55));
}
void GaussianQuadraturesTest::testLaguerre () [static]
Definition at line 129 of file gaussianquadratures.cpp.
References anonymous_namespace{gaussianquadratures.cpp}::testSingle(), anonymous_namespace{gaussianquadratures.cpp}::testSingleLaguerre(), and anonymous_namespace{gaussianquadratures.cpp}::x_inv_exp().
Referenced by suite().
{
     BOOST_MESSAGE("Testing Gauss-Laguerre integration...");
     testSingleLaguerre(GaussLaguerreIntegration(16));
     testSingleLaguerre(GaussLaguerreIntegration(150,0.01));
     testSingle(GaussLaguerreIntegration(16, 1.0), "f(x) = x*exp(-x)",
                std::ptr_fun<Real,Real>(x_inv_exp), 1.0);
     testSingle(GaussLaguerreIntegration(32, 0.9), "f(x) = x*exp(-x)",
                std::ptr_fun<Real,Real>(x_inv_exp), 1.0);
}
void GaussianQuadraturesTest::testTabulated () [static]
Definition at line 161 of file gaussianquadratures.cpp.
References anonymous_namespace{gaussianquadratures.cpp}::testSingleTabulated().
Referenced by suite().
{
     BOOST_MESSAGE("Testing tabulated Gauss-Laguerre integration...");
     testSingleTabulated(constant<Real,Real>(1.0), "f(x) = 1",
                         2.0,       1.0e-13);
     testSingleTabulated(identity<Real>(), "f(x) = x",
                         0.0,       1.0e-13);
     testSingleTabulated(square<Real>(), "f(x) = x^2",
                         (2.0/3.0), 1.0e-13);
     testSingleTabulated(cube<Real>(), "f(x) = x^3",
                         0.0,       1.0e-13);
     testSingleTabulated(fourth_power<Real>(), "f(x) = x^4",
                         (2.0/5.0), 1.0e-13);
}
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/gaussianquadratures.hpp
/home/deriversatile/QuantLib/QuantLibQt/test-suite/gaussianquadratures.cpp