QuantLib: QuantLib::ImplicitEulerScheme Class Reference
QuantLib::ImplicitEulerScheme Class Reference
#include <impliciteulerscheme.hpp>
Public Types
typedef OperatorTraits
< FdmLinearOp > traits
typedef traits::operator_type operator_type
typedef traits::array_type array_type
typedef traits::bc_set bc_set
typedef traits::condition_type condition_type
Public Member Functions
ImplicitEulerScheme (const boost::shared_ptr< FdmLinearOpComposite > &map, const bc_set &bcSet=bc_set(), Real relTol=1e-8)
void step (array_type &a, Time t)
void setStep (Time dt)
Protected Member Functions
Disposable< Array > apply (const Array &r) const
Protected Attributes
Time dt_
const Real relTol_
const boost::shared_ptr
< FdmLinearOpComposite > map_
const BoundaryConditionSchemeHelper bcSet_
Detailed Description
Definition at line 35 of file impliciteulerscheme.hpp.
Member Typedef Documentation
typedef traits::array_type QuantLib::ImplicitEulerScheme::array_type
Definition at line 40 of file impliciteulerscheme.hpp.
typedef traits::bc_set QuantLib::ImplicitEulerScheme::bc_set
Definition at line 41 of file impliciteulerscheme.hpp.
typedef traits::condition_type QuantLib::ImplicitEulerScheme::condition_type
Definition at line 42 of file impliciteulerscheme.hpp.
typedef traits::operator_type QuantLib::ImplicitEulerScheme::operator_type
Definition at line 39 of file impliciteulerscheme.hpp.
typedef OperatorTraits<FdmLinearOp> QuantLib::ImplicitEulerScheme::traits
Definition at line 38 of file impliciteulerscheme.hpp.
Constructor & Destructor Documentation
QuantLib::ImplicitEulerScheme::ImplicitEulerScheme (const boost::shared_ptr< FdmLinearOpComposite > & map, const bc_set & bcSet = bc_set(), Real relTol = 1e-8)
Definition at line 30 of file impliciteulerscheme.cpp.
    : dt_    (Null<Real>()),
      relTol_(relTol),
      map_   (map),
      bcSet_ (bcSet) {
    }
Member Function Documentation
Disposable< Array > QuantLib::ImplicitEulerScheme::apply (const Array & r) const [protected]
Definition at line 40 of file impliciteulerscheme.cpp.
References dt_, and map_.
Referenced by step().
{
        return r - dt_*map_->apply(r);
    }
void QuantLib::ImplicitEulerScheme::setStep (Time dt)
Definition at line 63 of file impliciteulerscheme.cpp.
References QuantLib::anonymous_namespace{yieldtermstructure.cpp}::dt, and dt_.
{
        dt_=dt;
    }
void QuantLib::ImplicitEulerScheme::step (array_type & a, Time t)
Definition at line 44 of file impliciteulerscheme.cpp.
References apply(), QuantLib::BoundaryConditionSchemeHelper::applyAfterSolving(), QuantLib::BoundaryConditionSchemeHelper::applyBeforeSolving(), bcSet_, dt_, map_, QuantLib::FdmLinearOpComposite::preconditioner(), QL_REQUIRE, relTol_, QuantLib::BoundaryConditionSchemeHelper::setTime(), QuantLib::Array::size(), QuantLib::BiCGstab::solve(), and QuantLib::BiCGStabResult::x.
{
        QL_REQUIRE(t-dt_ > -1e-8, "a step towards negative time given");
        map_->setTime(std::max(0.0, t-dt_), t);
        bcSet_.setTime(std::max(0.0, t-dt_));
        bcSet_.applyBeforeSolving(*map_, a);
        a = BiCGstab(
                boost::function<Disposable<Array>(const Array&)>(
                    boost::bind(&ImplicitEulerScheme::apply, this, _1)),
                10*a.size(), relTol_,
                boost::function<Disposable<Array>(const Array&)>(
                    boost::bind(&FdmLinearOpComposite::preconditioner,
                                map_, _1, -dt_))
            ).solve(a).x;
        bcSet_.applyAfterSolving(a);
    }
Member Data Documentation
const BoundaryConditionSchemeHelper QuantLib::ImplicitEulerScheme::bcSet_ [protected]
Definition at line 59 of file impliciteulerscheme.hpp.
Referenced by step().
Time QuantLib::ImplicitEulerScheme::dt_ [protected]
Definition at line 56 of file impliciteulerscheme.hpp.
Referenced by apply(), setStep(), and step().
const boost::shared_ptr<FdmLinearOpComposite> QuantLib::ImplicitEulerScheme::map_ [protected]
Definition at line 58 of file impliciteulerscheme.hpp.
Referenced by apply(), and step().
const Real QuantLib::ImplicitEulerScheme::relTol_ [protected]
Definition at line 57 of file impliciteulerscheme.hpp.
Referenced by step().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/schemes/impliciteulerscheme.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/schemes/impliciteulerscheme.cpp