QuantLib: QuantLib::MakeMCHestonHullWhiteEngine< RNG, S > Class Template Reference
QuantLib::MakeMCHestonHullWhiteEngine< RNG, S > Class Template Reference
Monte Carlo Heston/Hull-White engine factory.
#include <mchestonhullwhiteengine.hpp>
Public Member Functions
MakeMCHestonHullWhiteEngine (const boost::shared_ptr< HybridHestonHullWhiteProcess > &)
MakeMCHestonHullWhiteEngine & withSteps (Size steps)
MakeMCHestonHullWhiteEngine & withStepsPerYear (Size steps)
MakeMCHestonHullWhiteEngine & withAntitheticVariate (bool b=true)
MakeMCHestonHullWhiteEngine & withControlVariate (bool b=true)
MakeMCHestonHullWhiteEngine & withSamples (Size samples)
MakeMCHestonHullWhiteEngine & withAbsoluteTolerance (Real tolerance)
MakeMCHestonHullWhiteEngine & withMaxSamples (Size samples)
MakeMCHestonHullWhiteEngine & withSeed (BigNatural seed)
operator boost::shared_ptr< PricingEngine > () const
Private Attributes
boost::shared_ptr
< HybridHestonHullWhiteProcess > process_
Size steps_
Size stepsPerYear_
Size samples_
Size maxSamples_
bool antithetic_
bool controlVariate_
Real tolerance_
BigNatural seed_
Detailed Description
template<class RNG = PseudoRandom, class S = Statistics>
class QuantLib::MakeMCHestonHullWhiteEngine< RNG, S >
Monte Carlo Heston/Hull-White engine factory.
Definition at line 71 of file mchestonhullwhiteengine.hpp.
Constructor & Destructor Documentation
template<class RNG , class S > QuantLib::MakeMCHestonHullWhiteEngine< RNG, S >::MakeMCHestonHullWhiteEngine (const boost::shared_ptr< HybridHestonHullWhiteProcess > & process) [inline]
Definition at line 225 of file mchestonhullwhiteengine.hpp.
    : process_(process),
      steps_(Null<Size>()), stepsPerYear_(Null<Size>()),
      samples_(Null<Size>()), maxSamples_(Null<Size>()),
      antithetic_(false), controlVariate_(false),
      tolerance_(Null<Real>()), seed_(0) {}
Member Function Documentation
template<class RNG , class S > QuantLib::MakeMCHestonHullWhiteEngine< RNG, S >::operator boost::shared_ptr< PricingEngine > () const [inline]
Definition at line 299 of file mchestonhullwhiteengine.hpp.
References QL_REQUIRE, and anonymous_namespace{marketmodel.cpp}::seed_.
{
        QL_REQUIRE(steps_ != Null<Size>() || stepsPerYear_ != Null<Size>(),
                   "number of steps not given");
        QL_REQUIRE(steps_ == Null<Size>() || stepsPerYear_ == Null<Size>(),
                   "number of steps overspecified");
        return boost::shared_ptr<PricingEngine>(new
            MCHestonHullWhiteEngine<RNG,S>(process_,
                                           steps_,
                                           stepsPerYear_,
                                           antithetic_,
                                           controlVariate_,
                                           samples_,
                                           tolerance_,
                                           maxSamples_,
                                           seed_));
    }
template<class RNG , class S > MakeMCHestonHullWhiteEngine< RNG, S > & QuantLib::MakeMCHestonHullWhiteEngine< RNG, S >::withAbsoluteTolerance (Real tolerance) [inline]
Definition at line 272 of file mchestonhullwhiteengine.hpp.
References QL_REQUIRE, and anonymous_namespace{gaussianquadratures.cpp}::tolerance.
Referenced by HybridHestonHullWhiteProcessTest::testMcVanillaPricing().
{
        QL_REQUIRE(samples_ == Null<Size>(),
                   "number of samples already set");
        QL_REQUIRE(RNG::allowsErrorEstimate,
                   "chosen random generator policy "
                   "does not allow an error estimate");
        tolerance_ = tolerance;
        return *this;
    }
template<class RNG , class S > MakeMCHestonHullWhiteEngine< RNG, S > & QuantLib::MakeMCHestonHullWhiteEngine< RNG, S >::withAntitheticVariate (bool b = true) [inline]
Definition at line 249 of file mchestonhullwhiteengine.hpp.
References anonymous_namespace{marketmodel.cpp}::b.
Referenced by HybridHestonHullWhiteProcessTest::testMcVanillaPricing().
{
        antithetic_ = b;
        return *this;
    }
template<class RNG , class S > MakeMCHestonHullWhiteEngine< RNG, S > & QuantLib::MakeMCHestonHullWhiteEngine< RNG, S >::withControlVariate (bool b = true) [inline]
Definition at line 256 of file mchestonhullwhiteengine.hpp.
References anonymous_namespace{marketmodel.cpp}::b.
Referenced by HybridHestonHullWhiteProcessTest::testMcVanillaPricing().
{
        controlVariate_ = b;
        return *this;
    }
template<class RNG , class S > MakeMCHestonHullWhiteEngine< RNG, S > & QuantLib::MakeMCHestonHullWhiteEngine< RNG, S >::withMaxSamples (Size samples) [inline]
Definition at line 284 of file mchestonhullwhiteengine.hpp.
{
        maxSamples_ = samples;
        return *this;
    }
template<class RNG , class S > MakeMCHestonHullWhiteEngine< RNG, S > & QuantLib::MakeMCHestonHullWhiteEngine< RNG, S >::withSamples (Size samples) [inline]
Definition at line 263 of file mchestonhullwhiteengine.hpp.
References QL_REQUIRE.
{
        QL_REQUIRE(tolerance_ == Null<Real>(),
                   "tolerance already set");
        samples_ = samples;
        return *this;
    }
template<class RNG , class S > MakeMCHestonHullWhiteEngine< RNG, S > & QuantLib::MakeMCHestonHullWhiteEngine< RNG, S >::withSeed (BigNatural seed) [inline]
Definition at line 291 of file mchestonhullwhiteengine.hpp.
References anonymous_namespace{marketmodel.cpp}::seed_.
Referenced by HybridHestonHullWhiteProcessTest::testMcVanillaPricing().
{
        seed_ = seed;
        return *this;
    }
template<class RNG , class S > MakeMCHestonHullWhiteEngine< RNG, S > & QuantLib::MakeMCHestonHullWhiteEngine< RNG, S >::withSteps (Size steps) [inline]
Definition at line 235 of file mchestonhullwhiteengine.hpp.
{
        steps_ = steps;
        return *this;
    }
template<class RNG , class S > MakeMCHestonHullWhiteEngine< RNG, S > & QuantLib::MakeMCHestonHullWhiteEngine< RNG, S >::withStepsPerYear (Size steps) [inline]
Definition at line 242 of file mchestonhullwhiteengine.hpp.
{
        stepsPerYear_ = steps;
        return *this;
    }
Member Data Documentation
template<class RNG = PseudoRandom, class S = Statistics> bool QuantLib::MakeMCHestonHullWhiteEngine< RNG, S >::antithetic_ [private]
Definition at line 89 of file mchestonhullwhiteengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> bool QuantLib::MakeMCHestonHullWhiteEngine< RNG, S >::controlVariate_ [private]
Definition at line 89 of file mchestonhullwhiteengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> Size QuantLib::MakeMCHestonHullWhiteEngine< RNG, S >::maxSamples_ [private]
Definition at line 88 of file mchestonhullwhiteengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> boost::shared_ptr<HybridHestonHullWhiteProcess> QuantLib::MakeMCHestonHullWhiteEngine< RNG, S >::process_ [private]
Definition at line 87 of file mchestonhullwhiteengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> Size QuantLib::MakeMCHestonHullWhiteEngine< RNG, S >::samples_ [private]
Definition at line 88 of file mchestonhullwhiteengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> BigNatural QuantLib::MakeMCHestonHullWhiteEngine< RNG, S >::seed_ [private]
Definition at line 91 of file mchestonhullwhiteengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> Size QuantLib::MakeMCHestonHullWhiteEngine< RNG, S >::steps_ [private]
Definition at line 88 of file mchestonhullwhiteengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> Size QuantLib::MakeMCHestonHullWhiteEngine< RNG, S >::stepsPerYear_ [private]
Definition at line 88 of file mchestonhullwhiteengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> Real QuantLib::MakeMCHestonHullWhiteEngine< RNG, S >::tolerance_ [private]
Definition at line 90 of file mchestonhullwhiteengine.hpp.
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/vanilla/mchestonhullwhiteengine.hpp