QuantLib: QuantLib::StochasticProcessArray Class Reference
QuantLib::StochasticProcessArray Class Reference
Array of correlated 1-D stochastic processes
#include <stochasticprocessarray.hpp>
Public Member Functions
StochasticProcessArray (const std::vector< boost::shared_ptr< StochasticProcess1D > > &, const Matrix &correlation)
Size size () const
returns the number of dimensions of the stochastic process
Disposable< Array > initialValues () const
returns the initial values of the state variables
Disposable< Array > drift (Time t, const Array &x) const
returns the drift part of the equation, i.e., \(\mu(t, \mathrm{x}_t) \)
Disposable< Array > expectation (Time t0, const Array &x0, Time dt) const
Disposable< Matrix > diffusion (Time t, const Array &x) const
returns the diffusion part of the equation, i.e. \(\sigma(t, \mathrm{x}_t) \)
Disposable< Matrix > covariance (Time t0, const Array &x0, Time dt) const
Disposable< Matrix > stdDeviation (Time t0, const Array &x0, Time dt) const
Disposable< Array > apply (const Array &x0, const Array &dx) const
Disposable< Array > evolve (Time t0, const Array &x0, Time dt, const Array &dw) const
Time time (const Date &) const
const boost::shared_ptr
< StochasticProcess1D > & process (Size i) const
Disposable< Matrix > correlation () const
Protected Attributes
std::vector< boost::shared_ptr
< StochasticProcess1D > > processes_
Matrix sqrtCorrelation_
Detailed Description
Array of correlated 1-D stochastic processes
Definition at line 35 of file stochasticprocessarray.hpp.
Constructor & Destructor Documentation
QuantLib::StochasticProcessArray::StochasticProcessArray (const std::vector< boost::shared_ptr< StochasticProcess1D > > & processes, const Matrix & correlation)
Definition at line 26 of file stochasticprocessarray.cpp.
References processes_, QL_REQUIRE, QuantLib::Observer::registerWith(), and QuantLib::Matrix::rows().
    : processes_(processes),
      sqrtCorrelation_(pseudoSqrt(correlation,SalvagingAlgorithm::Spectral)) {
        QL_REQUIRE(!processes.empty(), "no processes given");
        QL_REQUIRE(correlation.rows() == processes.size(),
                   "mismatch between number of processes "
                   "and size of correlation matrix");
        for (Size i=0; i<processes_.size(); i++)
            registerWith(processes_[i]);
    }
Member Function Documentation
Disposable< Array > QuantLib::StochasticProcessArray::apply (const Array & x0, const Array & dx) const [virtual]
applies a change to the asset value. By default, it returns \(\mathrm{x} + \Delta \mathrm{x} \).
Reimplemented from QuantLib::StochasticProcess.
Definition at line 110 of file stochasticprocessarray.cpp.
References processes_, and size().
{
        Array tmp(size());
        for (Size i=0; i<size(); ++i)
            tmp[i] = processes_[i]->apply(x0[i],dx[i]);
        return tmp;
    }
Disposable< Matrix > QuantLib::StochasticProcessArray::correlation () const
Definition at line 127 of file stochasticprocessarray.cpp.
References sqrtCorrelation_, and QuantLib::transpose().
{
        return sqrtCorrelation_ * transpose(sqrtCorrelation_);
    }
Disposable< Matrix > QuantLib::StochasticProcessArray::covariance (Time t0, const Array & x0, Time dt) const [virtual]
returns the covariance \(V(\mathrm{x}_{t_0 + \Delta t} | \mathrm{x}_{t_0} = \mathrm{x}_0) \) of the process after a time interval \(\Delta t \) according to the given discretization. This method can be overridden in derived classes which want to hard-code a particular discretization.
Reimplemented from QuantLib::StochasticProcess.
Definition at line 93 of file stochasticprocessarray.cpp.
References stdDeviation(), and QuantLib::transpose().
{
        Matrix tmp = stdDeviation(t0, x0, dt);
        return tmp*transpose(tmp);
    }
Disposable< Matrix > QuantLib::StochasticProcessArray::diffusion (Time t, const Array & x) const [virtual]
returns the diffusion part of the equation, i.e. \(\sigma(t, \mathrm{x}_t) \)
Implements QuantLib::StochasticProcess.
Definition at line 59 of file stochasticprocessarray.cpp.
References processes_, QuantLib::Matrix::row_begin(), QuantLib::Matrix::row_end(), anonymous_namespace{distributions.cpp}::sigma, size(), and sqrtCorrelation_.
{
        Matrix tmp = sqrtCorrelation_;
        for (Size i=0; i<size(); ++i) {
            Real sigma = processes_[i]->diffusion(t, x[i]);
            std::transform(tmp.row_begin(i), tmp.row_end(i),
                           tmp.row_begin(i),
                           std::bind2nd(std::multiplies<Real>(),sigma));
        }
        return tmp;
    }
Disposable< Array > QuantLib::StochasticProcessArray::drift (Time t, const Array & x) const [virtual]
returns the drift part of the equation, i.e., \(\mu(t, \mathrm{x}_t) \)
Implements QuantLib::StochasticProcess.
Definition at line 51 of file stochasticprocessarray.cpp.
References processes_, and size().
{
        Array tmp(size());
        for (Size i=0; i<size(); ++i)
            tmp[i] = processes_[i]->drift(t, x[i]);
        return tmp;
    }
Disposable< Array > QuantLib::StochasticProcessArray::evolve (Time t0, const Array & x0, Time dt, const Array & dw) const [virtual]
returns the asset value after a time interval \(\Delta t \) according to the given discretization. By default, it returns
\[ E(\mathrm{x}_0,t_0,\Delta t) + S(\mathrm{x}_0,t_0,\Delta t) \cdot \Delta \mathrm{w} \]
where \(E \) is the expectation and \(S \) the standard deviation.
Reimplemented from QuantLib::StochasticProcess.
Definition at line 100 of file stochasticprocessarray.cpp.
References processes_, size(), and sqrtCorrelation_.
{
        const Array dz = sqrtCorrelation_ * dw;
        Array tmp(size());
        for (Size i=0; i<size(); ++i)
            tmp[i] = processes_[i]->evolve(t0, x0[i], dt, dz[i]);
        return tmp;
    }
Disposable< Array > QuantLib::StochasticProcessArray::expectation (Time t0, const Array & x0, Time dt) const [virtual]
returns the expectation \(E(\mathrm{x}_{t_0 + \Delta t} | \mathrm{x}_{t_0} = \mathrm{x}_0) \) of the process after a time interval \(\Delta t \) according to the given discretization. This method can be overridden in derived classes which want to hard-code a particular discretization.
Reimplemented from QuantLib::StochasticProcess.
Definition at line 71 of file stochasticprocessarray.cpp.
References processes_, and size().
{
        Array tmp(size());
        for (Size i=0; i<size(); ++i)
            tmp[i] = processes_[i]->expectation(t0, x0[i], dt);
        return tmp;
    }
Disposable< Array > QuantLib::StochasticProcessArray::initialValues () const [virtual]
returns the initial values of the state variables
Implements QuantLib::StochasticProcess.
Definition at line 44 of file stochasticprocessarray.cpp.
References processes_, and size().
{
        Array tmp(size());
        for (Size i=0; i<size(); ++i)
            tmp[i] = processes_[i]->x0();
        return tmp;
    }
const boost::shared_ptr< StochasticProcess1D > & QuantLib::StochasticProcessArray::process (Size i) const
Definition at line 123 of file stochasticprocessarray.cpp.
References processes_.
{
        return processes_[i];
    }
Size QuantLib::StochasticProcessArray::size () const [virtual]
returns the number of dimensions of the stochastic process
Implements QuantLib::StochasticProcess.
Definition at line 40 of file stochasticprocessarray.cpp.
References processes_.
Referenced by apply(), diffusion(), drift(), evolve(), expectation(), initialValues(), and stdDeviation().
{
        return processes_.size();
    }
Disposable< Matrix > QuantLib::StochasticProcessArray::stdDeviation (Time t0, const Array & x0, Time dt) const [virtual]
returns the standard deviation \(S(\mathrm{x}_{t_0 + \Delta t} | \mathrm{x}_{t_0} = \mathrm{x}_0) \) of the process after a time interval \(\Delta t \) according to the given discretization. This method can be overridden in derived classes which want to hard-code a particular discretization.
Reimplemented from QuantLib::StochasticProcess.
Definition at line 80 of file stochasticprocessarray.cpp.
References processes_, QuantLib::Matrix::row_begin(), QuantLib::Matrix::row_end(), anonymous_namespace{distributions.cpp}::sigma, size(), and sqrtCorrelation_.
Referenced by covariance().
{
        Matrix tmp = sqrtCorrelation_;
        for (Size i=0; i<size(); ++i) {
            Real sigma = processes_[i]->stdDeviation(t0, x0[i], dt);
            std::transform(tmp.row_begin(i), tmp.row_end(i),
                           tmp.row_begin(i),
                           std::bind2nd(std::multiplies<Real>(),sigma));
        }
        return tmp;
    }
Time QuantLib::StochasticProcessArray::time (const Date &) const [virtual]
returns the time value corresponding to the given date in the reference system of the stochastic process.
Note:
As a number of processes might not need this functionality, a default implementation is given which raises an exception.
Reimplemented from QuantLib::StochasticProcess.
Definition at line 118 of file stochasticprocessarray.cpp.
References processes_.
{
        return processes_[0]->time(d);
    }
Member Data Documentation
std::vector<boost::shared_ptr<StochasticProcess1D> > QuantLib::StochasticProcessArray::processes_ [protected]
Definition at line 60 of file stochasticprocessarray.hpp.
Referenced by apply(), diffusion(), drift(), evolve(), expectation(), initialValues(), process(), size(), stdDeviation(), StochasticProcessArray(), and time().
Matrix QuantLib::StochasticProcessArray::sqrtCorrelation_ [protected]
Definition at line 61 of file stochasticprocessarray.hpp.
Referenced by correlation(), diffusion(), evolve(), and stdDeviation().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/processes/stochasticprocessarray.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/processes/stochasticprocessarray.cpp