QuantLib: QuantLib::Garch11 Class Reference
QuantLib::Garch11 Class Reference
GARCH volatility model.
#include <garch.hpp>
Public Member Functions
Garch11 (Real a, Real b, Real vl)
Garch11 (const TimeSeries< Volatility > &qs)
TimeSeries< Volatility > calculate (const TimeSeries< Volatility > &quoteSeries)
TimeSeries< Volatility > calculate (const TimeSeries< Volatility > &quoteSeries, Real, Real, Real)
void calibrate (const TimeSeries< Volatility > &quoteSeries)
Private Member Functions
Real costFunction (const TimeSeries< Volatility > &qs, Real alpha, Real beta, Real omega)
Private Attributes
Real alpha_
Real beta_
Real gamma_
Real vl_
Detailed Description
GARCH volatility model.
Volatilities are assumed to be expressed on an annual basis.
Definition at line 35 of file garch.hpp.
Constructor & Destructor Documentation
QuantLib::Garch11::Garch11 (Real a, Real b, Real vl) [inline]
Definition at line 39 of file garch.hpp.
References anonymous_namespace{marketmodel.cpp}::b, and gamma_.
                                         :
            alpha_(a), beta_(b), vl_(vl) {gamma_ = 1 - a - b;};
QuantLib::Garch11::Garch11 (const TimeSeries< Volatility > & qs) [inline]
Definition at line 41 of file garch.hpp.
References calibrate().
{
            calibrate(qs);
        };
Member Function Documentation
TimeSeries< Volatility > QuantLib::Garch11::calculate (const TimeSeries< Volatility > & quoteSeries) [virtual]
Implements QuantLib::VolatilityCompositor.
Definition at line 25 of file garch.cpp.
References alpha_, beta_, gamma_, and vl_.
Referenced by costFunction().
{
    return calculate(qs, alpha_, beta_, gamma_* vl_);
  }
TimeSeries< Volatility > QuantLib::Garch11::calculate (const TimeSeries< Volatility > & quoteSeries, Real alpha, Real beta, Real omega)
Definition at line 30 of file garch.cpp.
References QuantLib::TimeSeries< T, Container >::begin(), and QuantLib::TimeSeries< T, Container >::end().
{
    TimeSeries<Volatility> retval;
    TimeSeries<Volatility>::const_iterator cur = qs.begin();
    retval[cur->first] = cur->second;
    Real sigma2 = cur->second * cur->second;
    ++cur;
    while (cur != qs.end()) {
      Real u = cur->second;
      sigma2 = omega + alpha * u * u +
          beta * sigma2;
      retval[cur->first] = std::sqrt(sigma2);
      ++cur;
    }
    return retval;
  }
void QuantLib::Garch11::calibrate (const TimeSeries< Volatility > & quoteSeries) [virtual]
Implements QuantLib::VolatilityCompositor.
Definition at line 47 of file garch.cpp.
Referenced by Garch11().
{}
Real QuantLib::Garch11::costFunction (const TimeSeries< Volatility > & qs, Real alpha, Real beta, Real omega) [private]
Definition at line 49 of file garch.cpp.
References calculate(), QL_REQUIRE, anonymous_namespace{solvers.cpp}::test(), anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::TimeSeries< T, Container >::values().
{
      Real retval(0.0);
      TimeSeries<Volatility> test =
          calculate(qs, alpha, beta, omega);
      std::vector<Volatility> testValues = test.values();
      std::vector<Volatility> quoteValues = qs.values();
      QL_REQUIRE(testValues.size() == quoteValues.size(),
                 "quote and test values do not match");
      std::vector<Volatility>::const_iterator i_t, i_q;
      i_t = testValues.begin();
      i_q = quoteValues.begin();
      while (i_t != testValues.end()) {
          Real v = (*i_q) * (*i_q);
          Real u2 = (*i_t) * (*i_t);
          retval += 2.0 * std::log(v) + u2/ (v*v);
          i_t++;
          i_q++;
      }
      return retval;
  }
Member Data Documentation
Real QuantLib::Garch11::alpha_ [private]
Definition at line 37 of file garch.hpp.
Referenced by calculate().
Real QuantLib::Garch11::beta_ [private]
Definition at line 37 of file garch.hpp.
Referenced by calculate().
Real QuantLib::Garch11::gamma_ [private]
Definition at line 37 of file garch.hpp.
Referenced by calculate(), and Garch11().
Real QuantLib::Garch11::vl_ [private]
Definition at line 37 of file garch.hpp.
Referenced by calculate().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/volatility/garch.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/volatility/garch.cpp