QuantLib: QuantLib::HundsdorferScheme Class Reference
QuantLib::HundsdorferScheme Class Reference
#include <hundsdorferscheme.hpp>
Public Types
typedef OperatorTraits
< FdmLinearOp > traits
typedef traits::operator_type operator_type
typedef traits::array_type array_type
typedef traits::bc_set bc_set
typedef traits::condition_type condition_type
Public Member Functions
HundsdorferScheme (Real theta, Real mu, const boost::shared_ptr< FdmLinearOpComposite > &map, const bc_set &bcSet=bc_set())
void step (array_type &a, Time t)
void setStep (Time dt)
Protected Attributes
Time dt_
const Real theta_
const Real mu_
const boost::shared_ptr
< FdmLinearOpComposite > & map_
const BoundaryConditionSchemeHelper bcSet_
Detailed Description
Definition at line 38 of file hundsdorferscheme.hpp.
Member Typedef Documentation
typedef traits::array_type QuantLib::HundsdorferScheme::array_type
Definition at line 43 of file hundsdorferscheme.hpp.
typedef traits::bc_set QuantLib::HundsdorferScheme::bc_set
Definition at line 44 of file hundsdorferscheme.hpp.
typedef traits::condition_type QuantLib::HundsdorferScheme::condition_type
Definition at line 45 of file hundsdorferscheme.hpp.
typedef traits::operator_type QuantLib::HundsdorferScheme::operator_type
Definition at line 42 of file hundsdorferscheme.hpp.
typedef OperatorTraits<FdmLinearOp> QuantLib::HundsdorferScheme::traits
Definition at line 41 of file hundsdorferscheme.hpp.
Constructor & Destructor Documentation
QuantLib::HundsdorferScheme::HundsdorferScheme (Real theta, Real mu, const boost::shared_ptr< FdmLinearOpComposite > & map, const bc_set & bcSet = bc_set())
Definition at line 26 of file hundsdorferscheme.cpp.
    : dt_(Null<Real>()),
      theta_(theta),
      mu_   (mu),
      map_  (map),
      bcSet_(bcSet) {
    }
Member Function Documentation
void QuantLib::HundsdorferScheme::setStep (Time dt)
Definition at line 67 of file hundsdorferscheme.cpp.
References QuantLib::anonymous_namespace{yieldtermstructure.cpp}::dt, and dt_.
{
        dt_=dt;
    }
void QuantLib::HundsdorferScheme::step (array_type & a, Time t)
Definition at line 37 of file hundsdorferscheme.cpp.
References QuantLib::BoundaryConditionSchemeHelper::applyAfterApplying(), QuantLib::BoundaryConditionSchemeHelper::applyAfterSolving(), QuantLib::BoundaryConditionSchemeHelper::applyBeforeApplying(), bcSet_, dt_, map_, mu_, QL_REQUIRE, QuantLib::BoundaryConditionSchemeHelper::setTime(), and theta_.
{
        QL_REQUIRE(t-dt_ > -1e-8, "a step towards negative time given");
        map_->setTime(std::max(0.0, t-dt_), t);
        bcSet_.setTime(std::max(0.0, t-dt_));
        bcSet_.applyBeforeApplying(*map_);
        Array y = a + dt_*map_->apply(a);
        bcSet_.applyAfterApplying(y);
        Array y0 = y;
        for (Size i=0; i < map_->size(); ++i) {
            Array rhs = y - theta_*dt_*map_->apply_direction(i, a);
            y = map_->solve_splitting(i, rhs, -theta_*dt_);
        }
        bcSet_.applyBeforeApplying(*map_);
        Array yt = y0 + mu_*dt_*map_->apply(y-a);
        bcSet_.applyAfterApplying(yt);
        for (Size i=0; i < map_->size(); ++i) {
            Array rhs = yt - theta_*dt_*map_->apply_direction(i, y);
            yt = map_->solve_splitting(i, rhs, -theta_*dt_);
        }
        bcSet_.applyAfterSolving(yt);
        a = yt;
    }
Member Data Documentation
const BoundaryConditionSchemeHelper QuantLib::HundsdorferScheme::bcSet_ [protected]
Definition at line 61 of file hundsdorferscheme.hpp.
Referenced by step().
Time QuantLib::HundsdorferScheme::dt_ [protected]
Definition at line 56 of file hundsdorferscheme.hpp.
Referenced by setStep(), and step().
const boost::shared_ptr<FdmLinearOpComposite>& QuantLib::HundsdorferScheme::map_ [protected]
Definition at line 60 of file hundsdorferscheme.hpp.
Referenced by step().
const Real QuantLib::HundsdorferScheme::mu_ [protected]
Definition at line 58 of file hundsdorferscheme.hpp.
Referenced by step().
const Real QuantLib::HundsdorferScheme::theta_ [protected]
Definition at line 57 of file hundsdorferscheme.hpp.
Referenced by step().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/schemes/hundsdorferscheme.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/schemes/hundsdorferscheme.cpp