QuantLib: QuantLib::CapletVarianceCurve Class Reference
QuantLib::CapletVarianceCurve Class Reference
#include <capletvariancecurve.hpp>
Public Member Functions
CapletVarianceCurve (const Date &referenceDate, const std::vector< Date > &dates, const std::vector< Volatility > &capletVolCurve, const DayCounter &dayCounter)
Real minStrike () const
the minimum strike for which the term structure can return vols
Real maxStrike () const
the maximum strike for which the term structure can return vols
TermStructure interface
DayCounter dayCounter () const
the day counter used for date/time conversion
Date maxDate () const
the latest date for which the curve can return values
Protected Member Functions
boost::shared_ptr< SmileSection > smileSectionImpl (Time t) const
implements the actual smile calculation in derived classes
Volatility volatilityImpl (Time t, Rate) const
implements the actual volatility calculation in derived classes
Private Attributes
BlackVarianceCurve blackCurve_
Detailed Description
Deprecated:
use the StrippedOptionletAdapter of a StrippedOptionlet instance
Definition at line 36 of file capletvariancecurve.hpp.
Constructor & Destructor Documentation
QuantLib::CapletVarianceCurve::CapletVarianceCurve (const Date & referenceDate, const std::vector< Date > & dates, const std::vector< Volatility > & capletVolCurve, const DayCounter & dayCounter) [inline]
Definition at line 57 of file capletvariancecurve.hpp.
    : OptionletVolatilityStructure(referenceDate, Calendar(), Following),
      blackCurve_(referenceDate, dates, capletVolCurve, dayCounter, false) {}
Member Function Documentation
DayCounter QuantLib::CapletVarianceCurve::dayCounter () const [inline, virtual]
the day counter used for date/time conversion
Reimplemented from QuantLib::TermStructure.
Definition at line 65 of file capletvariancecurve.hpp.
References blackCurve_, and QuantLib::BlackVarianceCurve::dayCounter().
Referenced by smileSectionImpl().
{
        return blackCurve_.dayCounter();
    }
Date QuantLib::CapletVarianceCurve::maxDate () const [inline, virtual]
the latest date for which the curve can return values
Implements QuantLib::TermStructure.
Definition at line 69 of file capletvariancecurve.hpp.
References blackCurve_, and QuantLib::BlackVarianceCurve::maxDate().
{
        return blackCurve_.maxDate();
    }
Real QuantLib::CapletVarianceCurve::maxStrike () const [inline, virtual]
the maximum strike for which the term structure can return vols
Implements QuantLib::VolatilityTermStructure.
Definition at line 77 of file capletvariancecurve.hpp.
References blackCurve_, and QuantLib::BlackVarianceCurve::maxStrike().
{
        return blackCurve_.maxStrike();
    }
Real QuantLib::CapletVarianceCurve::minStrike () const [inline, virtual]
the minimum strike for which the term structure can return vols
Implements QuantLib::VolatilityTermStructure.
Definition at line 73 of file capletvariancecurve.hpp.
References blackCurve_, and QuantLib::BlackVarianceCurve::minStrike().
{
        return blackCurve_.minStrike();
    }
boost::shared_ptr< SmileSection > QuantLib::CapletVarianceCurve::smileSectionImpl (Time optionTime) const [inline, protected, virtual]
implements the actual smile calculation in derived classes
Implements QuantLib::OptionletVolatilityStructure.
Definition at line 82 of file capletvariancecurve.hpp.
References blackCurve_, QuantLib::BlackVolTermStructure::blackVol(), and dayCounter().
{
        // dummy strike
        Volatility atmVol = blackCurve_.blackVol(t, 0.05, true);
        return boost::shared_ptr<SmileSection>(new
            FlatSmileSection(t,
                             atmVol,
                             dayCounter()));
    }
Volatility QuantLib::CapletVarianceCurve::volatilityImpl (Time optionTime, Rate strike) const [inline, protected, virtual]
implements the actual volatility calculation in derived classes
Implements QuantLib::OptionletVolatilityStructure.
Definition at line 92 of file capletvariancecurve.hpp.
References blackCurve_, and QuantLib::BlackVolTermStructure::blackVol().
{
        return blackCurve_.blackVol(t, r, true);
    }
Member Data Documentation
BlackVarianceCurve QuantLib::CapletVarianceCurve::blackCurve_ [private]
Definition at line 54 of file capletvariancecurve.hpp.
Referenced by dayCounter(), maxDate(), maxStrike(), minStrike(), smileSectionImpl(), and volatilityImpl().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/optionlet/capletvariancecurve.hpp