QuantLib: QuantLib::AverageBMACoupon Class Reference
QuantLib::AverageBMACoupon Class Reference
Average BMA coupon.
#include <averagebmacoupon.hpp>
Public Member Functions
AverageBMACoupon (const Date &paymentDate, Real nominal, const Date &startDate, const Date &endDate, const boost::shared_ptr< BMAIndex > &index, Real gearing=1.0, Spread spread=0.0, const Date &refPeriodStart=Date(), const Date &refPeriodEnd=Date(), const DayCounter &dayCounter=DayCounter())
FloatingRateCoupon interface
Date fixingDate () const
not applicable here; use fixingDates() instead
std::vector< Date > fixingDates () const
fixing dates of the rates to be averaged
Rate indexFixing () const
not applicable here; use indexFixings() instead
std::vector< Rate > indexFixings () const
fixings of the underlying index to be averaged
Rate convexityAdjustment () const
not applicable here
Visitability
void accept (AcyclicVisitor &)
Private Attributes
Schedule fixingSchedule_
Detailed Description
Average BMA coupon.
Coupon paying a BMA index, where the coupon rate is a weighted average of relevant fixings.
The weighted average is computed based on the actual calendar days for which a given fixing is valid and contributing to the given interest period.
Before weights are computed, the fixing schedule is adjusted for the index's fixing day gap. See rate() method for details.
Definition at line 44 of file averagebmacoupon.hpp.
Constructor & Destructor Documentation
QuantLib::AverageBMACoupon::AverageBMACoupon (const Date & paymentDate, Real nominal, const Date & startDate, const Date & endDate, const boost::shared_ptr< BMAIndex > & index, Real gearing = 1.0, Spread spread = 0.0, const Date & refPeriodStart = Date(), const Date & refPeriodEnd = Date(), const DayCounter & dayCounter = DayCounter())
Definition at line 104 of file averagebmacoupon.cpp.
References QuantLib::Calendar::advance(), QuantLib::anonymous_namespace{averagebmacoupon.cpp}::bmaCutoffDays, QuantLib::Days, QuantLib::FloatingRateCoupon::fixingDays(), fixingSchedule_, QuantLib::Preceding, and QuantLib::FloatingRateCoupon::setPricer().
    : FloatingRateCoupon(paymentDate, nominal, startDate, endDate,
                         index->fixingDays(), index, gearing, spread,
                         refPeriodStart, refPeriodEnd, dayCounter, false)
    {
        Calendar cal = index->fixingCalendar();
        Integer fixingDays = Integer(index->fixingDays());
        fixingDays += bmaCutoffDays;
        Date fixingStart = cal.advance(startDate, -fixingDays*Days, Preceding);
        fixingSchedule_ = index->fixingSchedule(fixingStart, endDate);
        setPricer(boost::shared_ptr<FloatingRateCouponPricer>(
                                                 new AverageBMACouponPricer));
    }
Member Function Documentation
void QuantLib::AverageBMACoupon::accept (AcyclicVisitor & v) [virtual]
Reimplemented from QuantLib::FloatingRateCoupon.
Definition at line 150 of file averagebmacoupon.cpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Visitor< T >::visit().
{
        Visitor<AverageBMACoupon>* v1 =
            dynamic_cast<Visitor<AverageBMACoupon>*>(&v);
        if (v1 != 0) {
            v1->visit(*this);
        } else {
            FloatingRateCoupon::accept(v);
        }
    }
Rate QuantLib::AverageBMACoupon::convexityAdjustment () const [virtual]
not applicable here
Reimplemented from QuantLib::FloatingRateCoupon.
Definition at line 146 of file averagebmacoupon.cpp.
References QL_FAIL.
{
        QL_FAIL("not defined for average-BMA coupon");
    }
Date QuantLib::AverageBMACoupon::fixingDate () const [virtual]
not applicable here; use fixingDates() instead
Reimplemented from QuantLib::FloatingRateCoupon.
Definition at line 127 of file averagebmacoupon.cpp.
References QL_FAIL.
{
        QL_FAIL("no single fixing date for average-BMA coupon");
    }
std::vector< Date > QuantLib::AverageBMACoupon::fixingDates () const
fixing dates of the rates to be averaged
Definition at line 131 of file averagebmacoupon.cpp.
References QuantLib::Schedule::dates(), and fixingSchedule_.
{
        return fixingSchedule_.dates();
    }
Rate QuantLib::AverageBMACoupon::indexFixing () const [virtual]
not applicable here; use indexFixings() instead
Reimplemented from QuantLib::FloatingRateCoupon.
Definition at line 135 of file averagebmacoupon.cpp.
References QL_FAIL.
{
        QL_FAIL("no single fixing for average-BMA coupon");
    }
std::vector< Rate > QuantLib::AverageBMACoupon::indexFixings () const
fixings of the underlying index to be averaged
Definition at line 139 of file averagebmacoupon.cpp.
References QuantLib::Schedule::date(), fixingSchedule_, QuantLib::FloatingRateCoupon::index_, and QuantLib::Schedule::size().
{
        std::vector<Rate> fixings(fixingSchedule_.size());
        for (Size i=0; i<fixings.size(); ++i)
            fixings[i] = index_->fixing(fixingSchedule_.date(i));
        return fixings;
    }
Member Data Documentation
Schedule QuantLib::AverageBMACoupon::fixingSchedule_ [private]
Definition at line 78 of file averagebmacoupon.hpp.
Referenced by AverageBMACoupon(), fixingDates(), and indexFixings().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/averagebmacoupon.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/averagebmacoupon.cpp