QuantLib: QuantLib::CommodityPricingHelper Class Reference
QuantLib::CommodityPricingHelper Class Reference
commodity index helper
#include <commoditypricinghelpers.hpp>
Public Member Functions
CommodityPricingHelper ()
Static Public Member Functions
static Real calculateFxConversionFactor (const Currency &fromCurrency, const Currency &toCurrency, const Date &evaluationDate)
static Real calculateUomConversionFactor (const CommodityType &commodityType, const UnitOfMeasure &fromUnitOfMeasure, const UnitOfMeasure &toUnitOfMeasure)
static Real calculateUnitCost (const CommodityType &commodityType, const CommodityUnitCost &unitCost, const Currency &baseCurrency, const UnitOfMeasure &baseUnitOfMeasure, const Date &evaluationDate)
static void createPricingPeriods (Date startDate, Date endDate, const Quantity &quantity, EnergyCommodity::DeliverySchedule deliverySchedule, EnergyCommodity::QuantityPeriodicity qtyPeriodicity, const PaymentTerm &paymentTerm, PricingPeriods &pricingPeriods)
Detailed Description
commodity index helper
Definition at line 36 of file commoditypricinghelpers.hpp.
Constructor & Destructor Documentation
QuantLib::CommodityPricingHelper::CommodityPricingHelper ()
Member Function Documentation
Real QuantLib::CommodityPricingHelper::calculateFxConversionFactor (const Currency & fromCurrency, const Currency & toCurrency, const Date & evaluationDate) [inline, static]
Definition at line 79 of file commoditypricinghelpers.hpp.
References QuantLib::ExchangeRate::Direct, QuantLib::Singleton< ExchangeRateManager >::instance(), QuantLib::ExchangeRateManager::lookup(), QuantLib::ExchangeRate::rate(), and QuantLib::ExchangeRate::source().
Referenced by calculateUnitCost().
{
        if (fromCurrency != toCurrency) {
            ExchangeRate exchRate =
                ExchangeRateManager::instance().lookup(fromCurrency,
                                                       toCurrency,
                                                       evaluationDate,
                                                       ExchangeRate::Direct);
            if (fromCurrency != exchRate.source())
                return (Real)1 / exchRate.rate();
            return exchRate.rate();
        }
        return 1;
    }
Real QuantLib::CommodityPricingHelper::calculateUnitCost (const CommodityType & commodityType, const CommodityUnitCost & unitCost, const Currency & baseCurrency, const UnitOfMeasure & baseUnitOfMeasure, const Date & evaluationDate) [inline, static]
Definition at line 96 of file commoditypricinghelpers.hpp.
References QuantLib::CommodityUnitCost::amount(), calculateFxConversionFactor(), calculateUomConversionFactor(), QuantLib::Money::currency(), QuantLib::CommodityUnitCost::unitOfMeasure(), and QuantLib::Money::value().
{
        if (unitCost.amount().value() != 0) {
            Real unitCostUomConversionFactor =
                calculateUomConversionFactor(commodityType,
                                             unitCost.unitOfMeasure(),
                                             baseUnitOfMeasure);
            Real unitCostFxConversionFactor =
                calculateFxConversionFactor(unitCost.amount().currency(),
                                            baseCurrency, evaluationDate);
            return unitCost.amount().value() * unitCostUomConversionFactor
                 * unitCostFxConversionFactor;
        }
        return 0;
    }
Real QuantLib::CommodityPricingHelper::calculateUomConversionFactor (const CommodityType & commodityType, const UnitOfMeasure & fromUnitOfMeasure, const UnitOfMeasure & toUnitOfMeasure) [inline, static]
Definition at line 65 of file commoditypricinghelpers.hpp.
References QuantLib::UnitOfMeasureConversion::conversionFactor(), QuantLib::Singleton< UnitOfMeasureConversionManager >::instance(), and QuantLib::UnitOfMeasureConversionManager::lookup().
Referenced by calculateUnitCost(), QuantLib::CommodityIndex::CommodityIndex(), and QuantLib::CommodityCurve::setBasisOfCurve().
{
        if (toUnitOfMeasure != fromUnitOfMeasure) {
            UnitOfMeasureConversion uomConv =
                UnitOfMeasureConversionManager::instance().lookup(
                           commodityType, fromUnitOfMeasure, toUnitOfMeasure);
            return uomConv.conversionFactor();
        }
        return 1;
    }
void QuantLib::CommodityPricingHelper::createPricingPeriods (Date startDate, Date endDate, const Quantity & quantity, EnergyCommodity::DeliverySchedule deliverySchedule, EnergyCommodity::QuantityPeriodicity qtyPeriodicity, const PaymentTerm & paymentTerm, PricingPeriods & pricingPeriods) [static]
Definition at line 24 of file commoditypricinghelpers.cpp.
References QuantLib::EnergyCommodity::Daily, anonymous_namespace{marketmodel.cpp}::endDate, QuantLib::PaymentTerm::getPaymentDate(), QuantLib::EnergyCommodity::Monthly, QuantLib::Months, QuantLib::EnergyCommodity::PerDay, QuantLib::EnergyCommodity::PerMonth, QL_FAIL, and QL_REQUIRE.
{
        if (deliverySchedule == EnergyCommodity::Monthly) {
            Quantity periodQuantity;
            if (qtyPeriodicity == EnergyCommodity::PerMonth) {
                periodQuantity = quantity;
            } else {
                QL_FAIL("Invalid period quantity/pricing period combination.");
            }
            for (Date periodStartDate=startDate; periodStartDate<endDate; ) {
                Date periodEndDate = (periodStartDate + (1 * Months)) - 1;
                Date paymentDate = paymentTerm.getPaymentDate(periodEndDate);
                pricingPeriods.push_back(boost::shared_ptr<PricingPeriod>(
                             new PricingPeriod(periodStartDate, periodEndDate,
                                               paymentDate, periodQuantity)));
                periodStartDate = periodEndDate + 1;
            }
        } else if (deliverySchedule == EnergyCommodity::Daily) {
            QL_REQUIRE(qtyPeriodicity == EnergyCommodity::PerDay,
                       "Invalid period quantity/pricing period combination.");
            for (Date periodStartDate=startDate; periodStartDate<endDate; ) {
                Date periodEndDate = (periodStartDate + (1 * Months)) - 1;
                Quantity periodQuantity =
                    quantity * (periodEndDate - periodStartDate);
                Date paymentDate = paymentTerm.getPaymentDate(periodEndDate);
                pricingPeriods.push_back(boost::shared_ptr<PricingPeriod>(
                             new PricingPeriod(periodStartDate, periodEndDate,
                                               paymentDate, periodQuantity)));
                periodStartDate = periodEndDate + 1;
            }
        }
    }
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/commodities/commoditypricinghelpers.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/commodities/commoditypricinghelpers.cpp