QuantLib: QuantLib::CallableFixedRateBond Class Reference
QuantLib::CallableFixedRateBond Class Reference
callable/puttable fixed rate bond
#include <callablebond.hpp>
Public Member Functions
CallableFixedRateBond (Natural settlementDays, Real faceAmount, const Schedule &schedule, const std::vector< Rate > &coupons, const DayCounter &accrualDayCounter, BusinessDayConvention paymentConvention=Following, Real redemption=100.0, const Date &issueDate=Date(), const CallabilitySchedule &putCallSchedule=CallabilitySchedule())
virtual void setupArguments (PricingEngine::arguments *args) const
Private Member Functions
Real accrued (Date settlement) const
accrued interest used internally, where includeToday = false
Detailed Description
callable/puttable fixed rate bond
Callable fixed rate bond class.
Example: CallableBonds.cpp
Definition at line 152 of file callablebond.hpp.
Constructor & Destructor Documentation
QuantLib::CallableFixedRateBond::CallableFixedRateBond (Natural settlementDays, Real faceAmount, const Schedule & schedule, const std::vector< Rate > & coupons, const DayCounter & accrualDayCounter, BusinessDayConvention paymentConvention = Following, Real redemption = 100.0, const Date & issueDate = Date(), const CallabilitySchedule & putCallSchedule = CallabilitySchedule())
Definition at line 111 of file callablebond.cpp.
References QuantLib::Bond::addRedemptionsToCashflows(), QuantLib::Calendar::adjust(), QuantLib::CallableBond::blackDiscountCurve_, QuantLib::CallableBond::blackEngine_, QuantLib::CallableBond::blackVolQuote_, QuantLib::Bond::calendar_, QuantLib::Bond::cashflows_, QuantLib::close(), QuantLib::Period::frequency(), QuantLib::CallableBond::frequency_, QuantLib::RelinkableHandle< T >::linkTo(), QuantLib::Bond::maturityDate_, QuantLib::Bond::setSingleRedemption(), QuantLib::Schedule::tenor(), QuantLib::FixedRateLeg::withCouponRates(), QuantLib::FixedRateLeg::withNotionals(), and QuantLib::FixedRateLeg::withPaymentAdjustment().
    : CallableBond(settlementDays, schedule, accrualDayCounter,
                   issueDate, putCallSchedule) {
        frequency_ = schedule.tenor().frequency();
        bool isZeroCouponBond = (coupons.size() == 1 && close(coupons[0], 0.0));
        if (!isZeroCouponBond) {
            cashflows_ =
                FixedRateLeg(schedule)
                .withNotionals(faceAmount)
                .withCouponRates(coupons, accrualDayCounter)
                .withPaymentAdjustment(paymentConvention);
            addRedemptionsToCashflows(std::vector<Real>(1, redemption));
        } else {
            Date redemptionDate = calendar_.adjust(maturityDate_,
                                                   paymentConvention);
            setSingleRedemption(faceAmount, redemption, redemptionDate);
        }
        // used for impliedVolatility() calculation
        boost::shared_ptr<SimpleQuote> dummyVolQuote(new SimpleQuote(0.));
        blackVolQuote_.linkTo(dummyVolQuote);
        blackEngine_ = boost::shared_ptr<PricingEngine>(
                   new BlackCallableFixedRateBondEngine(blackVolQuote_,
                                                        blackDiscountCurve_));
    }
Member Function Documentation
Real QuantLib::CallableFixedRateBond::accrued (Date settlement) const [private]
accrued interest used internally, where includeToday = false
same as Bond::accruedAmount() but with enable early payments true. Forces accrued to be calculated in a consistent way for future put/ call dates, which can be problematic in lattice engines when option dates are also coupon dates.
Definition at line 151 of file callablebond.cpp.
References QuantLib::Coupon::accruedAmount(), QuantLib::Bond::cashflows_, QuantLib::Bond::notional(), and QuantLib::Bond::settlementDate().
Referenced by setupArguments().
{
        if (settlement == Date()) settlement = settlementDate();
        const bool IncludeToday = false;
        for (Size i = 0; i<cashflows_.size(); ++i) {
            // the first coupon paying after d is the one we're after
            if (!cashflows_[i]->hasOccurred(settlement,IncludeToday)) {
                boost::shared_ptr<Coupon> coupon =
                    boost::dynamic_pointer_cast<Coupon>(cashflows_[i]);
                if (coupon)
                    // !!!
                    return coupon->accruedAmount(settlement) /
                           notional(settlement) * 100.0;
                else
                    return 0.0;
            }
        }
        return 0.0;
    }
void QuantLib::CallableFixedRateBond::setupArguments (PricingEngine::arguments *) const [virtual]
When a derived argument structure is defined for an instrument, this method should be overridden to fill it. This is mandatory in case a pricing engine is used.
Reimplemented from QuantLib::CallableBond.
Definition at line 173 of file callablebond.cpp.
References accrued(), QuantLib::CallableBond::arguments::callabilityDates, QuantLib::CallableBond::arguments::callabilityPrices, QuantLib::Bond::cashflows(), QuantLib::Callability::Price::Clean, QuantLib::CallableBond::arguments::couponAmounts, QuantLib::CallableBond::arguments::couponDates, QuantLib::CallableBond::arguments::frequency, QuantLib::CallableBond::frequency_, QuantLib::CallableBond::arguments::paymentDayCounter, QuantLib::CallableBond::paymentDayCounter_, QuantLib::CallableBond::arguments::putCallSchedule, QuantLib::CallableBond::putCallSchedule_, QL_REQUIRE, QuantLib::Bond::redemption(), QuantLib::CallableBond::arguments::redemption, QuantLib::CallableBond::arguments::redemptionDate, QuantLib::Bond::arguments::settlementDate, and anonymous_namespace{swaption.cpp}::type.
{
        Bond::setupArguments(args);
        CallableBond::arguments* arguments =
            dynamic_cast<CallableBond::arguments*>(args);
        QL_REQUIRE(arguments != 0, "no arguments given");
        Date settlement = arguments->settlementDate;
        arguments->redemption = redemption()->amount();
        arguments->redemptionDate = redemption()->date();
        const Leg& cfs = cashflows();
        arguments->couponDates.clear();
        arguments->couponDates.reserve(cfs.size()-1);
        arguments->couponAmounts.clear();
        arguments->couponAmounts.reserve(cfs.size()-1);
        for (Size i=0; i<cfs.size()-1; i++) {
            if (!cfs[i]->hasOccurred(settlement, false)) {
                arguments->couponDates.push_back(cfs[i]->date());
                arguments->couponAmounts.push_back(cfs[i]->amount());
            }
        }
        arguments->callabilityPrices.clear();
        arguments->callabilityDates.clear();
        arguments->callabilityPrices.reserve(putCallSchedule_.size());
        arguments->callabilityDates.reserve(putCallSchedule_.size());
        arguments->paymentDayCounter = paymentDayCounter_;
        arguments->frequency = frequency_;
        arguments->putCallSchedule = putCallSchedule_;
        for (Size i=0; i<putCallSchedule_.size(); i++) {
            if (!putCallSchedule_[i]->hasOccurred(settlement, false)) {
                arguments->callabilityDates.push_back(
                                                 putCallSchedule_[i]->date());
                arguments->callabilityPrices.push_back(
                                       putCallSchedule_[i]->price().amount());
                if (putCallSchedule_[i]->price().type()==
                    Callability::Price::Clean) {
                    /* calling accrued() forces accrued interest to be zero
                       if future option date is also coupon date, so that dirty
                       price = clean price. Use here because callability is
                       always applied before coupon in the tree engine.
                    */
                    arguments->callabilityPrices.back() +=
                        this->accrued(putCallSchedule_[i]->date());
                }
            }
        }
    }
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/callablebonds/callablebond.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/callablebonds/callablebond.cpp