QuantLib: QuantLib::SabrVolSurface Class Reference
QuantLib::SabrVolSurface Class Reference
SABR volatility (smile) surface.
#include <sabrvolsurface.hpp>
Public Member Functions
SabrVolSurface (const boost::shared_ptr< InterestRateIndex > &, const Handle< BlackAtmVolCurve > &, const std::vector< Period > &optionTenors, const std::vector< Spread > &atmRateSpreads, const std::vector< std::vector< Handle< Quote > > > &volSpreads)
const Handle< BlackAtmVolCurve > & atmCurve () const
std::vector< Volatility > volatilitySpreads (const Period &) const
std::vector< Volatility > volatilitySpreads (const Date &) const
TermStructure interface
DayCounter dayCounter () const
the day counter used for date/time conversion
Date maxDate () const
the latest date for which the curve can return values
Time maxTime () const
the latest time for which the curve can return values
const Date & referenceDate () const
the date at which discount = 1.0 and/or variance = 0.0
Calendar calendar () const
the calendar used for reference and/or option date calculation
Natural settlementDays () const
the settlementDays used for reference date calculation
VolatilityTermStructure interface
Real minStrike () const
the minimum strike for which the term structure can return vols
Real maxStrike () const
the maximum strike for which the term structure can return vols
Visitability
virtual void accept (AcyclicVisitor &)
BlackVolSurface interface
boost::shared_ptr< SmileSection > smileSectionImpl (Time) const
Protected Member Functions
boost::array< Real, 4 > sabrGuesses (const Date &) const
LazyObject interface
void performCalculations () const
virtual void update ()
Private Member Functions
void registerWithMarketData ()
void checkInputs () const
void updateSabrGuesses (const Date &d, boost::array< Real, 4 > newGuesses) const
Private Attributes
Handle< BlackAtmVolCurve > atmCurve_
std::vector< Period > optionTenors_
std::vector< Time > optionTimes_
std::vector< Date > optionDates_
std::vector< Spread > atmRateSpreads_
std::vector< std::vector
< Handle< Quote > > > volSpreads_
bool isAlphaFixed_
bool isBetaFixed_
bool isNuFixed_
bool isRhoFixed_
bool vegaWeighted_
std::vector< boost::array
< Real, 4 > > sabrGuesses_
Detailed Description
SABR volatility (smile) surface.
blah blah
Definition at line 39 of file sabrvolsurface.hpp.
Constructor & Destructor Documentation
QuantLib::SabrVolSurface::SabrVolSurface (const boost::shared_ptr< InterestRateIndex > & index, const Handle< BlackAtmVolCurve > & atmCurve, const std::vector< Period > & optionTenors, const std::vector< Spread > & atmRateSpreads, const std::vector< std::vector< Handle< Quote > > > & volSpreads)
Definition at line 29 of file sabrvolsurface.cpp.
References checkInputs(), isAlphaFixed_, isBetaFixed_, isNuFixed_, isRhoFixed_, QuantLib::InterestRateVolSurface::optionDateFromTenor(), optionDates_, optionTenors_, optionTimes_, registerWithMarketData(), sabrGuesses_, QuantLib::TermStructure::timeFromReference(), and vegaWeighted_.
    : InterestRateVolSurface(index),
      atmCurve_(atmCurve),
      optionTenors_(optionTenors),
      optionTimes_(optionTenors.size()),
      optionDates_(optionTenors.size()),
      atmRateSpreads_(atmRateSpreads),
      volSpreads_(volSpreads) {
        checkInputs();
        // Creation of reference smile sections
        // Hard coded
        isAlphaFixed_ = false;
        isBetaFixed_ = false;
        isNuFixed_ = false;
        isRhoFixed_ = false;
        vegaWeighted_ = true;
        sabrGuesses_.resize(optionTenors_.size());
        for (Size i=0; i<optionTenors_.size(); ++i) {
            optionDates_[i] = optionDateFromTenor(optionTenors_[i]);
            optionTimes_[i] = timeFromReference(optionDates_[i]);
            // Hard coded
            sabrGuesses_[i][0] = 0.025; // alpha
            sabrGuesses_[i][1] = 0.5;   // beta
            sabrGuesses_[i][2] = 0.3;   // rho
            sabrGuesses_[i][3] = 0.0;   // nu
        }
        registerWithMarketData();
    }
Member Function Documentation
void QuantLib::SabrVolSurface::accept (AcyclicVisitor & v) [virtual]
Reimplemented from QuantLib::InterestRateVolSurface.
Definition at line 176 of file sabrvolsurface.cpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Visitor< T >::visit().
{
        Visitor<SabrVolSurface>* v1 =
            dynamic_cast<Visitor<SabrVolSurface>*>(&v);
        if (v1 != 0)
            v1->visit(*this);
        else
            InterestRateVolSurface::accept(v);
    }
const Handle< BlackAtmVolCurve > & QuantLib::SabrVolSurface::atmCurve () const [inline]
Definition at line 139 of file sabrvolsurface.hpp.
References atmCurve_.
{
        return atmCurve_;
    }
Calendar QuantLib::SabrVolSurface::calendar () const [inline, virtual]
the calendar used for reference and/or option date calculation
Reimplemented from QuantLib::TermStructure.
Definition at line 123 of file sabrvolsurface.hpp.
References atmCurve_.
{
        return atmCurve_->calendar();
    }
void QuantLib::SabrVolSurface::checkInputs () const [private]
Definition at line 160 of file sabrvolsurface.cpp.
References atmRateSpreads_, QuantLib::io::ordinal(), QL_REQUIRE, and volSpreads_.
Referenced by SabrVolSurface().
{
        Size nStrikes = atmRateSpreads_.size();
        QL_REQUIRE(nStrikes>1, "too few strikes (" << nStrikes << ")");
        for (Size i=1; i<nStrikes; ++i)
            QL_REQUIRE(atmRateSpreads_[i-1]<atmRateSpreads_[i],
                       "non increasing strike spreads: " <<
                       io::ordinal(i) << " is " << atmRateSpreads_[i-1] << ", " <<
                       io::ordinal(i+1) << " is " << atmRateSpreads_[i]);
        for (Size i=0; i<volSpreads_.size(); i++)
            QL_REQUIRE(atmRateSpreads_.size()==volSpreads_[i].size(),
                       "mismatch between number of strikes (" << atmRateSpreads_.size() <<
                       ") and number of columns (" << volSpreads_[i].size() <<
                       ") in the " << io::ordinal(i+1) << " row");
    }
DayCounter QuantLib::SabrVolSurface::dayCounter () const [inline, virtual]
the day counter used for date/time conversion
Reimplemented from QuantLib::TermStructure.
Definition at line 107 of file sabrvolsurface.hpp.
References atmCurve_.
{
        return atmCurve_->dayCounter();
    }
Date QuantLib::SabrVolSurface::maxDate () const [inline, virtual]
the latest date for which the curve can return values
Implements QuantLib::TermStructure.
Definition at line 111 of file sabrvolsurface.hpp.
References atmCurve_.
{
        return atmCurve_->maxDate();
    }
Real QuantLib::SabrVolSurface::maxStrike () const [inline, virtual]
the maximum strike for which the term structure can return vols
Implements QuantLib::VolatilityTermStructure.
Definition at line 135 of file sabrvolsurface.hpp.
References QL_MAX_REAL.
{
        return QL_MAX_REAL;
    }
Time QuantLib::SabrVolSurface::maxTime () const [inline, virtual]
the latest time for which the curve can return values
Reimplemented from QuantLib::TermStructure.
Definition at line 115 of file sabrvolsurface.hpp.
References atmCurve_.
{
        return atmCurve_->maxTime();
    }
Real QuantLib::SabrVolSurface::minStrike () const [inline, virtual]
the minimum strike for which the term structure can return vols
Implements QuantLib::VolatilityTermStructure.
Definition at line 131 of file sabrvolsurface.hpp.
References QL_MIN_REAL.
{
        return QL_MIN_REAL;
    }
void QuantLib::SabrVolSurface::performCalculations () const [protected]
const Date & QuantLib::SabrVolSurface::referenceDate () const [inline, virtual]
the date at which discount = 1.0 and/or variance = 0.0
Reimplemented from QuantLib::TermStructure.
Definition at line 119 of file sabrvolsurface.hpp.
References atmCurve_.
Referenced by smileSectionImpl().
{
        return atmCurve_->referenceDate();
    }
void QuantLib::SabrVolSurface::registerWithMarketData () [private]
Definition at line 151 of file sabrvolsurface.cpp.
References atmRateSpreads_, optionTenors_, QuantLib::Observer::registerWith(), and volSpreads_.
Referenced by SabrVolSurface().
{
        for (Size i=0; i<optionTenors_.size(); ++i) {
            for (Size j=0; j<atmRateSpreads_.size(); ++j) {
                registerWith(volSpreads_[i][j]);
            }
        }
    }
boost::array< Real, 4 > QuantLib::SabrVolSurface::sabrGuesses (const Date & d) const [protected]
Definition at line 70 of file sabrvolsurface.cpp.
References optionDates_, and sabrGuesses_.
Referenced by smileSectionImpl().
{
        // the guesses for sabr parameters are assumed to be piecewise constant
        if (d<=optionDates_[0]) return sabrGuesses_[0];
        Size i=0;
        while( d<optionDates_[i] && i<optionDates_.size()-1)
            ++i;
        return sabrGuesses_[i];
    }
Natural QuantLib::SabrVolSurface::settlementDays () const [inline, virtual]
the settlementDays used for reference date calculation
Reimplemented from QuantLib::TermStructure.
Definition at line 127 of file sabrvolsurface.hpp.
References atmCurve_.
{
        return atmCurve_->settlementDays();
    }
boost::shared_ptr< SmileSection > QuantLib::SabrVolSurface::smileSectionImpl (Time t) const [virtual]
Implements QuantLib::BlackVolSurface.
Definition at line 122 of file sabrvolsurface.cpp.
References atmCurve_, atmRateSpreads_, anonymous_namespace{marketmodel.cpp}::d, QuantLib::Days, QuantLib::InterestRateVolSurface::index_, isAlphaFixed_, isBetaFixed_, isNuFixed_, isRhoFixed_, referenceDate(), sabrGuesses(), vegaWeighted_, and volatilitySpreads().
{
        BigInteger n = BigInteger(t*365.0);
        Date d = referenceDate()+n*Days;
        // interpolating on ref smile sections
        std::vector<Volatility> volSpreads = volatilitySpreads(d);
        // calculate sabr fit
        boost::array<Real, 4> sabrParameters1 = sabrGuesses(d);
        boost::shared_ptr<SabrInterpolatedSmileSection> tmp(new
            SabrInterpolatedSmileSection(d,
                                         index_->fixing(d,true), atmRateSpreads_, true,
                                            atmCurve_->atmVol(d), volSpreads,
                                            sabrParameters1[0], sabrParameters1[1],
                                            sabrParameters1[2], sabrParameters1[3],
                                            isAlphaFixed_, isBetaFixed_,
                                            isNuFixed_, isRhoFixed_,
                                            vegaWeighted_/*,
                                            const boost::shared_ptr<EndCriteria>& endCriteria,
                                            const boost::shared_ptr<OptimizationMethod>& method,
                                            const DayCounter& dc*/));
        // update guess
        return tmp;
    }
void QuantLib::SabrVolSurface::update () [protected, virtual]
This method must be implemented in derived classes. An instance of Observer does not call this method directly: instead, it will be called by the observables the instance registered with when they need to notify any changes.
Reimplemented from QuantLib::TermStructure.
Definition at line 111 of file sabrvolsurface.cpp.
References QuantLib::Observable::notifyObservers(), QuantLib::InterestRateVolSurface::optionDateFromTenor(), optionDates_, optionTenors_, optionTimes_, and QuantLib::TermStructure::timeFromReference().
{
        TermStructure::update();
        for (Size i=0; i<optionTenors_.size(); ++i) {
            optionDates_[i] = optionDateFromTenor(optionTenors_[i]);
            optionTimes_[i] = timeFromReference(optionDates_[i]);
        }
        notifyObservers();
    }
void QuantLib::SabrVolSurface::updateSabrGuesses (const Date & d, boost::array< Real, 4 > newGuesses) const [private]
Definition at line 80 of file sabrvolsurface.cpp.
References optionDates_, and sabrGuesses_.
{
        Size i=0;
        while( d<=optionDates_[i] && i<optionDates_.size())
            ++i;
        sabrGuesses_[i][0] = newGuesses[0];
        sabrGuesses_[i][1] = newGuesses[1];
        sabrGuesses_[i][2] = newGuesses[2];
        sabrGuesses_[i][3] = newGuesses[3];
    }
std::vector< Volatility > QuantLib::SabrVolSurface::volatilitySpreads (const Period & p) const [inline]
Definition at line 144 of file sabrvolsurface.hpp.
References QuantLib::InterestRateVolSurface::optionDateFromTenor().
Referenced by smileSectionImpl().
{
        return volatilitySpreads(optionDateFromTenor(p));
    }
std::vector< Volatility > QuantLib::SabrVolSurface::volatilitySpreads (const Date & d) const
Definition at line 92 of file sabrvolsurface.cpp.
References atmRateSpreads_, optionTimes_, QuantLib::TermStructure::timeFromReference(), and volSpreads_.
{
        Size nOptionsTimes = optionTimes_.size();
        Size nAtmRateSpreads = atmRateSpreads_.size();
        std::vector<Volatility> interpolatedVols(nAtmRateSpreads);
        std::vector<Volatility> vols(nOptionsTimes); // the volspread at a given strike
        for (Size i=0; i<nAtmRateSpreads; ++i) {
            for (Size j=0; j<nOptionsTimes; ++j) {
                vols[j] = (**volSpreads_[j][i]).value();
            }
            LinearInterpolation interpolator(optionTimes_.begin(), optionTimes_.end(),
                                             vols.begin());
            interpolatedVols[i] = interpolator(timeFromReference(d),true);
        }
        return interpolatedVols;
    }
Member Data Documentation
Handle<BlackAtmVolCurve> QuantLib::SabrVolSurface::atmCurve_ [private]
Definition at line 89 of file sabrvolsurface.hpp.
Referenced by atmCurve(), calendar(), dayCounter(), maxDate(), maxTime(), referenceDate(), settlementDays(), and smileSectionImpl().
std::vector<Spread> QuantLib::SabrVolSurface::atmRateSpreads_ [private]
Definition at line 93 of file sabrvolsurface.hpp.
Referenced by checkInputs(), registerWithMarketData(), smileSectionImpl(), and volatilitySpreads().
bool QuantLib::SabrVolSurface::isAlphaFixed_ [private]
Definition at line 96 of file sabrvolsurface.hpp.
Referenced by SabrVolSurface(), and smileSectionImpl().
bool QuantLib::SabrVolSurface::isBetaFixed_ [private]
Definition at line 97 of file sabrvolsurface.hpp.
Referenced by SabrVolSurface(), and smileSectionImpl().
bool QuantLib::SabrVolSurface::isNuFixed_ [private]
Definition at line 98 of file sabrvolsurface.hpp.
Referenced by SabrVolSurface(), and smileSectionImpl().
bool QuantLib::SabrVolSurface::isRhoFixed_ [private]
Definition at line 99 of file sabrvolsurface.hpp.
Referenced by SabrVolSurface(), and smileSectionImpl().
std::vector<Date> QuantLib::SabrVolSurface::optionDates_ [private]
Definition at line 92 of file sabrvolsurface.hpp.
Referenced by sabrGuesses(), SabrVolSurface(), update(), and updateSabrGuesses().
std::vector<Period> QuantLib::SabrVolSurface::optionTenors_ [private]
Definition at line 90 of file sabrvolsurface.hpp.
Referenced by registerWithMarketData(), SabrVolSurface(), and update().
std::vector<Time> QuantLib::SabrVolSurface::optionTimes_ [private]
Definition at line 91 of file sabrvolsurface.hpp.
Referenced by SabrVolSurface(), update(), and volatilitySpreads().
std::vector<boost::array<Real,4> > QuantLib::SabrVolSurface::sabrGuesses_ [mutable, private]
Definition at line 102 of file sabrvolsurface.hpp.
Referenced by sabrGuesses(), SabrVolSurface(), and updateSabrGuesses().
bool QuantLib::SabrVolSurface::vegaWeighted_ [private]
Definition at line 100 of file sabrvolsurface.hpp.
Referenced by SabrVolSurface(), and smileSectionImpl().
std::vector<std::vector<Handle<Quote> > > QuantLib::SabrVolSurface::volSpreads_ [private]
Definition at line 94 of file sabrvolsurface.hpp.
Referenced by checkInputs(), registerWithMarketData(), and volatilitySpreads().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/volatility/sabrvolsurface.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/volatility/sabrvolsurface.cpp