QuantLib: QuantLib::TransformedGrid Class Reference
QuantLib::TransformedGrid Class Reference
transformed grid
#include <transformedgrid.hpp>
Public Member Functions
TransformedGrid (const Array &grid)
template<class T >
TransformedGrid (const Array &grid, T func)
const Array & gridArray () const
const Array & transformedGridArray () const
const Array & dxmArray () const
const Array & dxpArray () const
const Array & dxArray () const
Real grid (Size i) const
Real transformedGrid (Size i) const
Real dxm (Size i) const
Real dxp (Size i) const
Real dx (Size i) const
Size size () const
Protected Attributes
Array grid_
Array transformedGrid_
Array dxm_
Array dxp_
Array dx_
Detailed Description
transformed grid
This package encapuslates an array of grid points. It is used primarily in PDE calculations.
Definition at line 37 of file transformedgrid.hpp.
Constructor & Destructor Documentation
QuantLib::TransformedGrid::TransformedGrid (const Array & grid) [inline]
Definition at line 39 of file transformedgrid.hpp.
References dx_, dxm_, dxp_, QuantLib::Array::size(), and transformedGrid_.
                                            :
            grid_(grid), transformedGrid_(grid),
            dxm_(grid.size()), dxp_(grid.size()),
            dx_(grid.size()){
            for (Size i=1; i < transformedGrid_.size() -1 ; i++) {
                dxm_[i] = transformedGrid_[i] - transformedGrid_[i-1];
                dxp_[i] = transformedGrid_[i+1] - transformedGrid_[i];
                dx_[i] = dxm_[i] + dxp_[i];
            }
        }
template<class T > QuantLib::TransformedGrid::TransformedGrid (const Array & grid, T func) [inline]
Definition at line 50 of file transformedgrid.hpp.
References QuantLib::Array::begin(), dx_, dxm_, dxp_, QuantLib::Array::end(), grid_, QuantLib::Array::size(), and transformedGrid_.
                                                    :
            grid_(grid), transformedGrid_(grid.size()),
            dxm_(grid.size()), dxp_(grid.size()),
            dx_(grid.size()){
            std::transform(grid_.begin(),
                           grid_.end(),
                           transformedGrid_.begin(),
                           func);
            for (Size i=1; i < transformedGrid_.size() -1 ; i++) {
                dxm_[i] = transformedGrid_[i] - transformedGrid_[i-1];
                dxp_[i] = transformedGrid_[i+1] - transformedGrid_[i];
                dx_[i] = dxm_[i] + dxp_[i];
            }
        }
Member Function Documentation
Real QuantLib::TransformedGrid::dx (Size i) const [inline]
Definition at line 74 of file transformedgrid.hpp.
References dx_.
Referenced by QuantLib::PdeSecondOrderParabolic::generateOperator().
{ return dx_[i];}
const Array& QuantLib::TransformedGrid::dxArray () const [inline]
Definition at line 68 of file transformedgrid.hpp.
References dx_.
{ return dx_;}
Real QuantLib::TransformedGrid::dxm (Size i) const [inline]
Definition at line 72 of file transformedgrid.hpp.
References dxm_.
Referenced by QuantLib::PdeSecondOrderParabolic::generateOperator().
{ return dxm_[i];}
const Array& QuantLib::TransformedGrid::dxmArray () const [inline]
Definition at line 66 of file transformedgrid.hpp.
References dxm_.
{ return dxm_;}
Real QuantLib::TransformedGrid::dxp (Size i) const [inline]
Definition at line 73 of file transformedgrid.hpp.
References dxp_.
Referenced by QuantLib::PdeSecondOrderParabolic::generateOperator().
{ return dxp_[i];}
const Array& QuantLib::TransformedGrid::dxpArray () const [inline]
Definition at line 67 of file transformedgrid.hpp.
References dxp_.
{ return dxp_;}
Real QuantLib::TransformedGrid::grid (Size i) const [inline]
Definition at line 70 of file transformedgrid.hpp.
References grid_.
Referenced by QuantLib::PdeSecondOrderParabolic::generateOperator(), and TransformedGridTest::testConstruction().
{ return grid_[i];}
const Array& QuantLib::TransformedGrid::gridArray () const [inline]
Definition at line 64 of file transformedgrid.hpp.
References grid_.
{ return grid_;}
Size QuantLib::TransformedGrid::size () const [inline]
Definition at line 75 of file transformedgrid.hpp.
References grid_, and QuantLib::Array::size().
Referenced by QuantLib::PdeSecondOrderParabolic::generateOperator().
{return grid_.size();}
Real QuantLib::TransformedGrid::transformedGrid (Size i) const [inline]
Definition at line 71 of file transformedgrid.hpp.
References transformedGrid_.
Referenced by QuantLib::LogGrid::logGrid(), and TransformedGridTest::testConstruction().
{ return transformedGrid_[i];}
const Array& QuantLib::TransformedGrid::transformedGridArray () const [inline]
Definition at line 65 of file transformedgrid.hpp.
References transformedGrid_.
Referenced by QuantLib::LogGrid::logGridArray().
{ return transformedGrid_;}
Member Data Documentation
Array QuantLib::TransformedGrid::dx_ [protected]
Definition at line 82 of file transformedgrid.hpp.
Referenced by dx(), dxArray(), and TransformedGrid().
Array QuantLib::TransformedGrid::dxm_ [protected]
Definition at line 80 of file transformedgrid.hpp.
Referenced by dxm(), dxmArray(), and TransformedGrid().
Array QuantLib::TransformedGrid::dxp_ [protected]
Definition at line 81 of file transformedgrid.hpp.
Referenced by dxp(), dxpArray(), and TransformedGrid().
Array QuantLib::TransformedGrid::grid_ [protected]
Definition at line 78 of file transformedgrid.hpp.
Referenced by grid(), gridArray(), size(), and TransformedGrid().
Array QuantLib::TransformedGrid::transformedGrid_ [protected]
Definition at line 79 of file transformedgrid.hpp.
Referenced by TransformedGrid(), transformedGrid(), and transformedGridArray().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/transformedgrid.hpp