QuantLib: QuantLib::MakeYoYInflationCapFloor Class Reference
QuantLib::MakeYoYInflationCapFloor Class Reference
helper class
#include <makeyoyinflationcapfloor.hpp>
Public Member Functions
MakeYoYInflationCapFloor (YoYInflationCapFloor::Type capFloorType, const Size &length, const Calendar &cal, const boost::shared_ptr< YoYInflationIndex > &index, const Period &observationLag, Rate strike=Null< Rate >(), const Period &forwardStart=0 *Days)
MakeYoYInflationCapFloor & withNominal (Real n)
MakeYoYInflationCapFloor & withEffectiveDate (const Date &effectiveDate)
MakeYoYInflationCapFloor & withFirstCapletExcluded ()
MakeYoYInflationCapFloor & withPaymentDayCounter (const DayCounter &)
MakeYoYInflationCapFloor & withPaymentAdjustment (BusinessDayConvention)
MakeYoYInflationCapFloor & withFixingDays (Natural fixingDays)
operator YoYInflationCapFloor () const
operator boost::shared_ptr< YoYInflationCapFloor > () const
MakeYoYInflationCapFloor & asOptionlet (bool b=true)
only get last coupon
MakeYoYInflationCapFloor & withPricingEngine (const boost::shared_ptr< PricingEngine > &engine)
Private Attributes
YoYInflationCapFloor::Type capFloorType_
Size length_
Calendar calendar_
boost::shared_ptr
< YoYInflationIndex > index_
Period observationLag_
Rate strike_
bool firstCapletExcluded_
bool asOptionlet_
Date effectiveDate_
Period forwardStart_
DayCounter dayCounter_
BusinessDayConvention roll_
Natural fixingDays_
Real nominal_
boost::shared_ptr< PricingEngine > engine_
Detailed Description
helper class
This class provides a more comfortable way to instantiate standard yoy inflation cap and floor.
Definition at line 38 of file makeyoyinflationcapfloor.hpp.
Constructor & Destructor Documentation
QuantLib::MakeYoYInflationCapFloor::MakeYoYInflationCapFloor (YoYInflationCapFloor::Type capFloorType, const Size & length, const Calendar & cal, const boost::shared_ptr< YoYInflationIndex > & index, const Period & observationLag, Rate strike = Null<Rate>(), const Period & forwardStart = 0*Days)
Definition at line 28 of file makeyoyinflationcapfloor.cpp.
    : capFloorType_(capFloorType), length_(length),
      calendar_(cal), index_(index), observationLag_(observationLag),
      strike_(strike), firstCapletExcluded_(false),
      asOptionlet_(false), effectiveDate_(Date()), forwardStart_(forwardStart),
      dayCounter_(Thirty360()), roll_(ModifiedFollowing), fixingDays_(0),
      nominal_(1000000.0)
     {}
Member Function Documentation
MakeYoYInflationCapFloor & QuantLib::MakeYoYInflationCapFloor::asOptionlet (bool b = true)
only get last coupon
Definition at line 125 of file makeyoyinflationcapfloor.cpp.
References asOptionlet_, and anonymous_namespace{marketmodel.cpp}::b.
{
        asOptionlet_ = b;
        return *this;
    }
QuantLib::MakeYoYInflationCapFloor::operator boost::shared_ptr< YoYInflationCapFloor > () const
Definition at line 46 of file makeyoyinflationcapfloor.cpp.
References QuantLib::Calendar::advance(), QuantLib::Annual, QuantLib::CashFlows::atmRate(), anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::calendar_, anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::dayCounter_, QuantLib::Days, anonymous_namespace{marketmodel.cpp}::endDate, QuantLib::Settings::evaluationDate(), QuantLib::DateGeneration::Forward, QuantLib::Singleton< Settings >::instance(), QL_REQUIRE, anonymous_namespace{marketmodel.cpp}::startDate, QuantLib::Unadjusted, QuantLib::yoyInflationLeg::withNotionals(), QuantLib::yoyInflationLeg::withPaymentAdjustment(), QuantLib::yoyInflationLeg::withPaymentDayCounter(), and QuantLib::Years.
{
        Date startDate;
        if (effectiveDate_ != Date()) {
            startDate = effectiveDate_;
        } else {
            Date referenceDate = Settings::instance().evaluationDate();
            Date spotDate = calendar_.advance(referenceDate,
                                              fixingDays_*Days);
            startDate = spotDate+forwardStart_;
        }
        Date endDate = calendar_.advance(startDate,length_*Years,Unadjusted);
        Schedule schedule(startDate, endDate, Period(Annual), calendar_,
                          Unadjusted, Unadjusted, // ref periods & acc periods
                          DateGeneration::Forward, false);
        Leg leg = yoyInflationLeg(schedule, calendar_, index_,
                                  observationLag_)
        .withPaymentAdjustment(roll_)
        .withPaymentDayCounter(dayCounter_)
        .withNotionals(nominal_)
        ;
        if (firstCapletExcluded_)
            leg.erase(leg.begin());
        // only leaves the last coupon
        if (asOptionlet_ && leg.size() > 1) {
            Leg::iterator end = leg.end();  // Sun Studio needs an lvalue
            leg.erase(leg.begin(), --end);
        }
        std::vector<Rate> strikeVector(1, strike_);
        if (strike_ == Null<Rate>()) {
            // ATM on the forecasting curve
            QL_REQUIRE(!index_->yoyInflationTermStructure().empty(),
                       "no forecasting yoy term structure set for " <<
                       index_->name());
            Handle<YieldTermStructure> fc
            = index_->yoyInflationTermStructure()->nominalTermStructure();
            strikeVector[0] = CashFlows::atmRate(leg,**fc,
                                                 false, fc->referenceDate());
        }
        boost::shared_ptr<YoYInflationCapFloor> capFloor(new
                    YoYInflationCapFloor(capFloorType_, leg, strikeVector));
        capFloor->setPricingEngine(engine_);
        return capFloor;
    }
QuantLib::MakeYoYInflationCapFloor::operator YoYInflationCapFloor () const
Definition at line 41 of file makeyoyinflationcapfloor.cpp.
{
        boost::shared_ptr<YoYInflationCapFloor> capfloor = *this;
        return *capfloor;
    }
MakeYoYInflationCapFloor & QuantLib::MakeYoYInflationCapFloor::withEffectiveDate (const Date & effectiveDate)
Definition at line 101 of file makeyoyinflationcapfloor.cpp.
References effectiveDate_.
{
        effectiveDate_ = effectiveDate;
        return *this;
    }
MakeYoYInflationCapFloor& QuantLib::MakeYoYInflationCapFloor::withFirstCapletExcluded ()
MakeYoYInflationCapFloor & QuantLib::MakeYoYInflationCapFloor::withFixingDays (Natural fixingDays)
Definition at line 120 of file makeyoyinflationcapfloor.cpp.
References fixingDays_.
{
        fixingDays_ = n;
        return *this;
    }
MakeYoYInflationCapFloor & QuantLib::MakeYoYInflationCapFloor::withNominal (Real n)
Definition at line 96 of file makeyoyinflationcapfloor.cpp.
References nominal_.
{
        nominal_ = n;
        return *this;
    }
MakeYoYInflationCapFloor & QuantLib::MakeYoYInflationCapFloor::withPaymentAdjustment (BusinessDayConvention bdc)
Definition at line 108 of file makeyoyinflationcapfloor.cpp.
References roll_.
{
        roll_ = bdc;
        return *this;
    }
MakeYoYInflationCapFloor & QuantLib::MakeYoYInflationCapFloor::withPaymentDayCounter (const DayCounter & dc)
Definition at line 114 of file makeyoyinflationcapfloor.cpp.
References dayCounter_.
{
        dayCounter_ = dc;
        return *this;
    }
MakeYoYInflationCapFloor & QuantLib::MakeYoYInflationCapFloor::withPricingEngine (const boost::shared_ptr< PricingEngine > & engine)
Definition at line 130 of file makeyoyinflationcapfloor.cpp.
References engine_.
{
        engine_ = engine;
        return *this;
    }
Member Data Documentation
bool QuantLib::MakeYoYInflationCapFloor::asOptionlet_ [private]
Definition at line 68 of file makeyoyinflationcapfloor.hpp.
Referenced by asOptionlet().
Calendar QuantLib::MakeYoYInflationCapFloor::calendar_ [private]
Definition at line 64 of file makeyoyinflationcapfloor.hpp.
YoYInflationCapFloor::Type QuantLib::MakeYoYInflationCapFloor::capFloorType_ [private]
Definition at line 62 of file makeyoyinflationcapfloor.hpp.
DayCounter QuantLib::MakeYoYInflationCapFloor::dayCounter_ [private]
Definition at line 71 of file makeyoyinflationcapfloor.hpp.
Referenced by withPaymentDayCounter().
Date QuantLib::MakeYoYInflationCapFloor::effectiveDate_ [private]
Definition at line 69 of file makeyoyinflationcapfloor.hpp.
Referenced by withEffectiveDate().
boost::shared_ptr<PricingEngine> QuantLib::MakeYoYInflationCapFloor::engine_ [private]
Definition at line 77 of file makeyoyinflationcapfloor.hpp.
Referenced by withPricingEngine().
bool QuantLib::MakeYoYInflationCapFloor::firstCapletExcluded_ [private]
Definition at line 68 of file makeyoyinflationcapfloor.hpp.
Natural QuantLib::MakeYoYInflationCapFloor::fixingDays_ [private]
Definition at line 73 of file makeyoyinflationcapfloor.hpp.
Referenced by withFixingDays().
Period QuantLib::MakeYoYInflationCapFloor::forwardStart_ [private]
Definition at line 70 of file makeyoyinflationcapfloor.hpp.
boost::shared_ptr<YoYInflationIndex> QuantLib::MakeYoYInflationCapFloor::index_ [private]
Definition at line 65 of file makeyoyinflationcapfloor.hpp.
Size QuantLib::MakeYoYInflationCapFloor::length_ [private]
Definition at line 63 of file makeyoyinflationcapfloor.hpp.
Real QuantLib::MakeYoYInflationCapFloor::nominal_ [private]
Definition at line 74 of file makeyoyinflationcapfloor.hpp.
Referenced by withNominal().
Period QuantLib::MakeYoYInflationCapFloor::observationLag_ [private]
Definition at line 66 of file makeyoyinflationcapfloor.hpp.
BusinessDayConvention QuantLib::MakeYoYInflationCapFloor::roll_ [private]
Definition at line 72 of file makeyoyinflationcapfloor.hpp.
Referenced by withPaymentAdjustment().
Rate QuantLib::MakeYoYInflationCapFloor::strike_ [private]
Definition at line 67 of file makeyoyinflationcapfloor.hpp.
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/makeyoyinflationcapfloor.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/makeyoyinflationcapfloor.cpp