QuantLib: QuantLib::Swap::results Class Reference
QuantLib::Swap::results Class Reference
#include <swap.hpp>
Public Member Functions
void reset ()
Public Attributes
std::vector< Real > legNPV
std::vector< Real > legBPS
std::vector< DiscountFactor > startDiscounts
std::vector< DiscountFactor > endDiscounts
DiscountFactor npvDateDiscount
Detailed Description
Definition at line 124 of file swap.hpp.
Member Function Documentation
void QuantLib::Swap::results::reset () [virtual]
Reimplemented from QuantLib::Instrument::results.
Reimplemented in QuantLib::CPISwap::results, QuantLib::VanillaSwap::results, QuantLib::YearOnYearInflationSwap::results, and QuantLib::AssetSwap::results.
Definition at line 165 of file swap.cpp.
References QuantLib::Swap::endDiscounts(), QuantLib::Swap::legBPS(), QuantLib::Swap::legNPV(), QuantLib::Swap::npvDateDiscount(), anonymous_namespace{inflationvolatility.cpp}::reset(), and QuantLib::Swap::startDiscounts().
{
        Instrument::results::reset();
        legNPV.clear();
        legBPS.clear();
        startDiscounts.clear();
        endDiscounts.clear();
        npvDateDiscount = Null<DiscountFactor>();
    }
Member Data Documentation
std::vector<DiscountFactor> QuantLib::Swap::results::endDiscounts
Definition at line 128 of file swap.hpp.
Referenced by QuantLib::DiscountingSwapEngine::calculate(), and QuantLib::Swap::fetchResults().
std::vector<Real> QuantLib::Swap::results::legBPS
Definition at line 127 of file swap.hpp.
Referenced by QuantLib::DiscountingSwapEngine::calculate(), and QuantLib::Swap::fetchResults().
std::vector<Real> QuantLib::Swap::results::legNPV
Definition at line 126 of file swap.hpp.
Referenced by QuantLib::DiscountingSwapEngine::calculate(), and QuantLib::Swap::fetchResults().
DiscountFactor QuantLib::Swap::results::npvDateDiscount
Definition at line 129 of file swap.hpp.
Referenced by QuantLib::DiscountingSwapEngine::calculate(), and QuantLib::Swap::fetchResults().
std::vector<DiscountFactor> QuantLib::Swap::results::startDiscounts
Definition at line 128 of file swap.hpp.
Referenced by QuantLib::DiscountingSwapEngine::calculate(), and QuantLib::Swap::fetchResults().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/swap.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/swap.cpp