QuantLib: QuantLib::MakeCapFloor Class Reference
QuantLib::MakeCapFloor Class Reference
helper class
#include <makecapfloor.hpp>
Public Member Functions
MakeCapFloor (CapFloor::Type capFloorType, const Period &capFloorTenor, const boost::shared_ptr< IborIndex > &iborIndex, Rate strike=Null< Rate >(), const Period &forwardStart=0 *Days)
operator CapFloor () const
operator boost::shared_ptr< CapFloor > () const
MakeCapFloor & withNominal (Real n)
MakeCapFloor & withEffectiveDate (const Date &effectiveDate, bool firstCapletExcluded)
MakeCapFloor & withTenor (const Period &t)
MakeCapFloor & withCalendar (const Calendar &cal)
MakeCapFloor & withConvention (BusinessDayConvention bdc)
MakeCapFloor & withTerminationDateConvention (BusinessDayConvention bdc)
MakeCapFloor & withRule (DateGeneration::Rule r)
MakeCapFloor & withEndOfMonth (bool flag=true)
MakeCapFloor & withFirstDate (const Date &d)
MakeCapFloor & withNextToLastDate (const Date &d)
MakeCapFloor & withDayCount (const DayCounter &dc)
MakeCapFloor & asOptionlet (bool b=true)
only get last coupon
MakeCapFloor & withPricingEngine (const boost::shared_ptr< PricingEngine > &engine)
Private Attributes
CapFloor::Type capFloorType_
Rate strike_
bool firstCapletExcluded_
bool asOptionlet_
MakeVanillaSwap makeVanillaSwap_
boost::shared_ptr< PricingEngine > engine_
Detailed Description
helper class
This class provides a more comfortable way to instantiate standard market cap and floor.
Definition at line 37 of file makecapfloor.hpp.
Constructor & Destructor Documentation
QuantLib::MakeCapFloor::MakeCapFloor (CapFloor::Type capFloorType, const Period & capFloorTenor, const boost::shared_ptr< IborIndex > & iborIndex, Rate strike = Null<Rate>(), const Period & forwardStart = 0*Days)
Definition at line 30 of file makecapfloor.cpp.
    : capFloorType_(capFloorType), strike_(strike),
      firstCapletExcluded_(forwardStart==0*Days), asOptionlet_(false),
      makeVanillaSwap_(MakeVanillaSwap(tenor, iborIndex, 0.0, forwardStart)) {}
Member Function Documentation
MakeCapFloor & QuantLib::MakeCapFloor::asOptionlet (bool b = true)
only get last coupon
Definition at line 152 of file makecapfloor.cpp.
References asOptionlet_, and anonymous_namespace{marketmodel.cpp}::b.
{
        asOptionlet_ = b;
        return *this;
    }
QuantLib::MakeCapFloor::operator boost::shared_ptr< CapFloor > () const
QuantLib::MakeCapFloor::operator CapFloor () const
Definition at line 39 of file makecapfloor.cpp.
{
        shared_ptr<CapFloor> capfloor = *this;
        return *capfloor;
    }
MakeCapFloor & QuantLib::MakeCapFloor::withCalendar (const Calendar & cal)
Definition at line 99 of file makecapfloor.cpp.
References makeVanillaSwap_, QuantLib::MakeVanillaSwap::withFixedLegCalendar(), and QuantLib::MakeVanillaSwap::withFloatingLegCalendar().
{
        makeVanillaSwap_.withFixedLegCalendar(cal);
        makeVanillaSwap_.withFloatingLegCalendar(cal);
        return *this;
    }
MakeCapFloor & QuantLib::MakeCapFloor::withConvention (BusinessDayConvention bdc)
Definition at line 106 of file makecapfloor.cpp.
References makeVanillaSwap_, QuantLib::MakeVanillaSwap::withFixedLegConvention(), and QuantLib::MakeVanillaSwap::withFloatingLegConvention().
{
        makeVanillaSwap_.withFixedLegConvention(bdc);
        makeVanillaSwap_.withFloatingLegConvention(bdc);
        return *this;
    }
MakeCapFloor & QuantLib::MakeCapFloor::withDayCount (const DayCounter & dc)
Definition at line 146 of file makecapfloor.cpp.
References makeVanillaSwap_, QuantLib::MakeVanillaSwap::withFixedLegDayCount(), and QuantLib::MakeVanillaSwap::withFloatingLegDayCount().
{
        makeVanillaSwap_.withFixedLegDayCount(dc);
        makeVanillaSwap_.withFloatingLegDayCount(dc);
        return *this;
    }
MakeCapFloor & QuantLib::MakeCapFloor::withEffectiveDate (const Date & effectiveDate, bool firstCapletExcluded)
Definition at line 85 of file makecapfloor.cpp.
References firstCapletExcluded_, makeVanillaSwap_, and QuantLib::MakeVanillaSwap::withEffectiveDate().
{
        makeVanillaSwap_.withEffectiveDate(effectiveDate);
        firstCapletExcluded_ = firstCapletExcluded;
        return *this;
    }
MakeCapFloor & QuantLib::MakeCapFloor::withEndOfMonth (bool flag = true)
Definition at line 127 of file makecapfloor.cpp.
References makeVanillaSwap_, QuantLib::MakeVanillaSwap::withFixedLegEndOfMonth(), and QuantLib::MakeVanillaSwap::withFloatingLegEndOfMonth().
{
        makeVanillaSwap_.withFixedLegEndOfMonth(flag);
        makeVanillaSwap_.withFloatingLegEndOfMonth(flag);
        return *this;
    }
MakeCapFloor & QuantLib::MakeCapFloor::withFirstDate (const Date & d)
Definition at line 134 of file makecapfloor.cpp.
References makeVanillaSwap_, QuantLib::MakeVanillaSwap::withFixedLegFirstDate(), and QuantLib::MakeVanillaSwap::withFloatingLegFirstDate().
{
        makeVanillaSwap_.withFixedLegFirstDate(d);
        makeVanillaSwap_.withFloatingLegFirstDate(d);
        return *this;
    }
MakeCapFloor & QuantLib::MakeCapFloor::withNextToLastDate (const Date & d)
Definition at line 140 of file makecapfloor.cpp.
References makeVanillaSwap_, QuantLib::MakeVanillaSwap::withFixedLegNextToLastDate(), and QuantLib::MakeVanillaSwap::withFloatingLegNextToLastDate().
{
        makeVanillaSwap_.withFixedLegNextToLastDate(d);
        makeVanillaSwap_.withFloatingLegNextToLastDate(d);
        return *this;
    }
MakeCapFloor & QuantLib::MakeCapFloor::withNominal (Real n)
Definition at line 80 of file makecapfloor.cpp.
References makeVanillaSwap_, and QuantLib::MakeVanillaSwap::withNominal().
{
        makeVanillaSwap_.withNominal(n);
        return *this;
    }
MakeCapFloor & QuantLib::MakeCapFloor::withPricingEngine (const boost::shared_ptr< PricingEngine > & engine)
Definition at line 157 of file makecapfloor.cpp.
References engine_.
Referenced by QuantLib::OptionletStripper2::performCalculations(), QuantLib::OptionletStripper1::performCalculations(), OptionletStripperTest::testFlatTermVolatilityStripping1(), and OptionletStripperTest::testTermVolatilityStripping1().
{
        engine_ = engine;
        return *this;
    }
MakeCapFloor & QuantLib::MakeCapFloor::withRule (DateGeneration::Rule r)
Definition at line 121 of file makecapfloor.cpp.
References makeVanillaSwap_, QuantLib::MakeVanillaSwap::withFixedLegRule(), and QuantLib::MakeVanillaSwap::withFloatingLegRule().
{
        makeVanillaSwap_.withFixedLegRule(r);
        makeVanillaSwap_.withFloatingLegRule(r);
        return *this;
    }
MakeCapFloor & QuantLib::MakeCapFloor::withTenor (const Period & t)
Definition at line 92 of file makecapfloor.cpp.
References makeVanillaSwap_, QuantLib::MakeVanillaSwap::withFixedLegTenor(), and QuantLib::MakeVanillaSwap::withFloatingLegTenor().
{
        makeVanillaSwap_.withFixedLegTenor(t);
        makeVanillaSwap_.withFloatingLegTenor(t);
        return *this;
    }
MakeCapFloor & QuantLib::MakeCapFloor::withTerminationDateConvention (BusinessDayConvention bdc)
Definition at line 114 of file makecapfloor.cpp.
References makeVanillaSwap_, QuantLib::MakeVanillaSwap::withFixedLegTerminationDateConvention(), and QuantLib::MakeVanillaSwap::withFloatingLegTerminationDateConvention().
{
        makeVanillaSwap_.withFixedLegTerminationDateConvention(bdc);
        makeVanillaSwap_.withFloatingLegTerminationDateConvention(bdc);
        return *this;
    }
Member Data Documentation
bool QuantLib::MakeCapFloor::asOptionlet_ [private]
Definition at line 69 of file makecapfloor.hpp.
Referenced by asOptionlet().
CapFloor::Type QuantLib::MakeCapFloor::capFloorType_ [private]
Definition at line 67 of file makecapfloor.hpp.
boost::shared_ptr<PricingEngine> QuantLib::MakeCapFloor::engine_ [private]
Definition at line 73 of file makecapfloor.hpp.
Referenced by withPricingEngine().
bool QuantLib::MakeCapFloor::firstCapletExcluded_ [private]
Definition at line 69 of file makecapfloor.hpp.
Referenced by withEffectiveDate().
MakeVanillaSwap QuantLib::MakeCapFloor::makeVanillaSwap_ [private]
Definition at line 71 of file makecapfloor.hpp.
Referenced by withCalendar(), withConvention(), withDayCount(), withEffectiveDate(), withEndOfMonth(), withFirstDate(), withNextToLastDate(), withNominal(), withRule(), withTenor(), and withTerminationDateConvention().
Rate QuantLib::MakeCapFloor::strike_ [private]
Definition at line 68 of file makecapfloor.hpp.
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/makecapfloor.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/makecapfloor.cpp