QuantLib: QuantLib::CoxIngersollRoss Class Reference
QuantLib::CoxIngersollRoss Class Reference
Cox-Ingersoll-Ross model class.
#include <coxingersollross.hpp>
Classes
class Dynamics
Dynamics of the short-rate under the Cox-Ingersoll-Ross model
class HelperProcess
class VolatilityConstraint
Public Member Functions
CoxIngersollRoss (Rate r0=0.05, Real theta=0.1, Real k=0.1, Real sigma=0.1)
virtual Real discountBondOption (Option::Type type, Real strike, Time maturity, Time bondMaturity) const
virtual boost::shared_ptr
< ShortRateDynamics > dynamics () const
returns the short-rate dynamics
boost::shared_ptr< Lattice > tree (const TimeGrid &grid) const
Return by default a trinomial recombining tree.
Protected Member Functions
Real A (Time t, Time T) const
Real B (Time t, Time T) const
Real theta () const
Real k () const
Real sigma () const
Real x0 () const
Private Attributes
Parameter & theta_
Parameter & k_
Parameter & sigma_
Parameter & r0_
Detailed Description
Cox-Ingersoll-Ross model class.
This class implements the Cox-Ingersoll-Ross model defined by
\[ dr_t = k(\theta - r_t)dt + \sqrt{r_t}\sigma dW_t . \]
Bug:
this class was not tested enough to guarantee its functionality.
Definition at line 43 of file coxingersollross.hpp.
Constructor & Destructor Documentation
QuantLib::CoxIngersollRoss::CoxIngersollRoss (Rate r0 = 0.05, Real theta = 0.1, Real k = 0.1, Real sigma = 0.1)
Definition at line 47 of file coxingersollross.cpp.
References k_, r0_, sigma_, and theta_.
    : OneFactorAffineModel(4),
      theta_(arguments_[0]), k_(arguments_[1]),
      sigma_(arguments_[2]), r0_(arguments_[3]) {
        theta_ = ConstantParameter(theta, PositiveConstraint());
        k_ = ConstantParameter(k, PositiveConstraint());
        sigma_ = ConstantParameter(sigma, VolatilityConstraint(k,theta));
        r0_ = ConstantParameter(r0, PositiveConstraint());
    }
Member Function Documentation
Real QuantLib::CoxIngersollRoss::A (Time t, Time T) const [protected, virtual]
Implements QuantLib::OneFactorAffineModel.
Reimplemented in QuantLib::ExtendedCoxIngersollRoss.
Definition at line 64 of file coxingersollross.cpp.
References k(), sigma(), theta(), and QuantLib::CalibratedModel::value().
Referenced by QuantLib::ExtendedCoxIngersollRoss::A(), discountBondOption(), and QuantLib::ExtendedCoxIngersollRoss::discountBondOption().
{
        Real sigma2 = sigma()*sigma();
        Real h = std::sqrt(k()*k() + 2.0*sigma2);
        Real numerator = 2.0*h*std::exp(0.5*(k()+h)*(T-t));
        Real denominator = 2.0*h + (k()+h)*(std::exp((T-t)*h) - 1.0);
        Real value = std::log(numerator/denominator)*
            2.0*k()*theta()/sigma2;
        return std::exp(value);
    }
Real QuantLib::CoxIngersollRoss::B (Time t, Time T) const [protected, virtual]
Implements QuantLib::OneFactorAffineModel.
Definition at line 74 of file coxingersollross.cpp.
References k(), sigma(), and QuantLib::CalibratedModel::value().
Referenced by QuantLib::ExtendedCoxIngersollRoss::A(), discountBondOption(), and QuantLib::ExtendedCoxIngersollRoss::discountBondOption().
{
        Real h = std::sqrt(k()*k() + 2.0*sigma()*sigma());
        Real temp = std::exp((T-t)*h) - 1.0;
        Real numerator = 2.0*temp;
        Real denominator = 2.0*h + (k()+h)*temp;
        Real value = numerator/denominator;
        return value;
    }
Real QuantLib::CoxIngersollRoss::discountBondOption (Option::Type type, Real strike, Time maturity, Time bondMaturity) const [virtual]
Implements QuantLib::AffineModel.
Reimplemented in QuantLib::ExtendedCoxIngersollRoss.
Definition at line 83 of file coxingersollross.cpp.
References A(), B(), anonymous_namespace{marketmodel.cpp}::b, QuantLib::Option::Call, QuantLib::OneFactorAffineModel::discountBond(), k(), QuantLib::Option::Put, QL_EPSILON, QL_FAIL, QL_REQUIRE, sigma(), theta(), and x0().
{
        QL_REQUIRE(strike>0.0, "strike must be positive");
        DiscountFactor discountT = discountBond(0.0, t, x0());
        DiscountFactor discountS = discountBond(0.0, s, x0());
        if (t < QL_EPSILON) {
            switch(type) {
              case Option::Call:
                return std::max<Real>(discountS - strike, 0.0);
              case Option::Put:
                return std::max<Real>(strike - discountS, 0.0);
              default: QL_FAIL("unsupported option type");
            }
        }
        Real sigma2 = sigma()*sigma();
        Real h = std::sqrt(k()*k() + 2.0*sigma2);
        Real b = B(t,s);
        Real rho = 2.0*h/(sigma2*(std::exp(h*t) - 1.0));
        Real psi = (k() + h)/sigma2;
        Real df = 4.0*k()*theta()/sigma2;
        Real ncps = 2.0*rho*rho*x0()*std::exp(h*t)/(rho+psi+b);
        Real ncpt = 2.0*rho*rho*x0()*std::exp(h*t)/(rho+psi);
        NonCentralChiSquareDistribution chis(df, ncps);
        NonCentralChiSquareDistribution chit(df, ncpt);
        Real z = std::log(A(t,s)/strike)/b;
        Real call = discountS*chis(2.0*z*(rho+psi+b)) -
            strike*discountT*chit(2.0*z*(rho+psi));
        if (type == Option::Call)
            return call;
        else
            return call - discountS + strike*discountT;
    }
boost::shared_ptr< OneFactorModel::ShortRateDynamics > QuantLib::CoxIngersollRoss::dynamics () const [virtual]
returns the short-rate dynamics
Implements QuantLib::OneFactorModel.
Reimplemented in QuantLib::ExtendedCoxIngersollRoss.
Definition at line 59 of file coxingersollross.cpp.
References k(), sigma(), theta(), and x0().
Referenced by tree().
{
        return boost::shared_ptr<ShortRateDynamics>(
                                  new Dynamics(theta(), k() , sigma(), x0()));
    }
Real QuantLib::CoxIngersollRoss::k () const [inline, protected]
Definition at line 65 of file coxingersollross.hpp.
References k_.
Referenced by A(), B(), discountBondOption(), QuantLib::ExtendedCoxIngersollRoss::discountBondOption(), QuantLib::ExtendedCoxIngersollRoss::dynamics(), dynamics(), QuantLib::ExtendedCoxIngersollRoss::generateArguments(), and QuantLib::ExtendedCoxIngersollRoss::tree().
{ return k_(0.0); }
Real QuantLib::CoxIngersollRoss::sigma () const [inline, protected]
Definition at line 66 of file coxingersollross.hpp.
References sigma_.
Referenced by A(), B(), discountBondOption(), QuantLib::ExtendedCoxIngersollRoss::discountBondOption(), QuantLib::ExtendedCoxIngersollRoss::dynamics(), dynamics(), QuantLib::ExtendedCoxIngersollRoss::generateArguments(), QuantLib::CoxIngersollRoss::VolatilityConstraint::Impl::test(), and QuantLib::ExtendedCoxIngersollRoss::tree().
{ return sigma_(0.0); }
Real QuantLib::CoxIngersollRoss::theta () const [inline, protected]
Definition at line 64 of file coxingersollross.hpp.
References theta_.
Referenced by A(), discountBondOption(), QuantLib::ExtendedCoxIngersollRoss::discountBondOption(), dynamics(), QuantLib::ExtendedCoxIngersollRoss::dynamics(), QuantLib::ExtendedCoxIngersollRoss::generateArguments(), and QuantLib::ExtendedCoxIngersollRoss::tree().
{ return theta_(0.0); }
boost::shared_ptr< Lattice > QuantLib::CoxIngersollRoss::tree (const TimeGrid & grid) const [virtual]
Return by default a trinomial recombining tree.
Reimplemented from QuantLib::OneFactorModel.
Reimplemented in QuantLib::ExtendedCoxIngersollRoss.
Definition at line 126 of file coxingersollross.cpp.
References dynamics().
{
        boost::shared_ptr<TrinomialTree> trinomial(
                        new TrinomialTree(dynamics()->process(), grid, true));
        return boost::shared_ptr<Lattice>(
                              new ShortRateTree(trinomial, dynamics(), grid));
    }
Real QuantLib::CoxIngersollRoss::x0 () const [inline, protected]
Definition at line 67 of file coxingersollross.hpp.
References r0_.
Referenced by QuantLib::ExtendedCoxIngersollRoss::A(), discountBondOption(), QuantLib::ExtendedCoxIngersollRoss::dynamics(), dynamics(), QuantLib::ExtendedCoxIngersollRoss::generateArguments(), and QuantLib::ExtendedCoxIngersollRoss::tree().
{ return r0_(0.0); }
Member Data Documentation
Parameter& QuantLib::CoxIngersollRoss::k_ [private]
Definition at line 74 of file coxingersollross.hpp.
Referenced by CoxIngersollRoss(), and k().
Parameter& QuantLib::CoxIngersollRoss::r0_ [private]
Definition at line 76 of file coxingersollross.hpp.
Referenced by CoxIngersollRoss(), and x0().
Parameter& QuantLib::CoxIngersollRoss::sigma_ [private]
Definition at line 75 of file coxingersollross.hpp.
Referenced by CoxIngersollRoss(), and sigma().
Parameter& QuantLib::CoxIngersollRoss::theta_ [private]
Definition at line 71 of file coxingersollross.hpp.
Referenced by CoxIngersollRoss(), and theta().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/shortrate/onefactormodels/coxingersollross.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/shortrate/onefactormodels/coxingersollross.cpp