QuantLib: QuantLib::FdmLinearOpIterator Class Reference
QuantLib::FdmLinearOpIterator Class Reference
#include <fdmlinearopiterator.hpp>
Public Member Functions
FdmLinearOpIterator (Size index=0)
FdmLinearOpIterator (const std::vector< Size > &dim)
FdmLinearOpIterator (const std::vector< Size > &dim, const std::vector< Size > &coordinates, Size index)
FdmLinearOpIterator (const Disposable< FdmLinearOpIterator > &from)
void operator++ ()
bool operator!= (const FdmLinearOpIterator &iterator)
Size index () const
const std::vector< Size > & coordinates () const
void swap (FdmLinearOpIterator &iter)
Private Attributes
Size index_
std::vector< Size > dim_
std::vector< Size > coordinates_
Detailed Description
Definition at line 36 of file fdmlinearopiterator.hpp.
Constructor & Destructor Documentation
QuantLib::FdmLinearOpIterator::FdmLinearOpIterator (Size index = 0) [inline, explicit]
Definition at line 38 of file fdmlinearopiterator.hpp.
        : index_(index) {}
QuantLib::FdmLinearOpIterator::FdmLinearOpIterator (const std::vector< Size > & dim) [inline, explicit]
Definition at line 41 of file fdmlinearopiterator.hpp.
        : index_(0),
          dim_(dim),
          coordinates_(dim.size(), 0) {}
QuantLib::FdmLinearOpIterator::FdmLinearOpIterator (const std::vector< Size > & dim, const std::vector< Size > & coordinates, Size index) [inline]
Definition at line 46 of file fdmlinearopiterator.hpp.
        : index_(index),
          dim_(dim),
          coordinates_(coordinates) {}
QuantLib::FdmLinearOpIterator::FdmLinearOpIterator (const Disposable< FdmLinearOpIterator > & from) [inline]
Definition at line 52 of file fdmlinearopiterator.hpp.
References swap().
{
            swap(const_cast<Disposable<FdmLinearOpIterator> & >(from));
        }
Member Function Documentation
const std::vector<Size>& QuantLib::FdmLinearOpIterator::coordinates () const [inline]
Definition at line 76 of file fdmlinearopiterator.hpp.
References coordinates_.
Referenced by QuantLib::FdmLogInnerValue::avgInnerValue(), QuantLib::FdmLogInnerValue::avgInnerValueCalc(), QuantLib::FdmMesherComposite::dminus(), QuantLib::FdmMesherComposite::dplus(), QuantLib::FdmVPPStepCondition::evolve(), QuantLib::FdmBatesOp::integro(), QuantLib::FdmLinearOpLayout::iter_neighbourhood(), QuantLib::FdmMesherComposite::location(), QuantLib::UniformGridMesher::location(), and QuantLib::FdmLinearOpLayout::neighbourhood().
{
            return coordinates_;
        }
Size QuantLib::FdmLinearOpIterator::index () const [inline]
Definition at line 72 of file fdmlinearopiterator.hpp.
References index_.
Referenced by QuantLib::FirstDerivativeOp::FirstDerivativeOp(), QuantLib::FdmLinearOpLayout::neighbourhood(), QuantLib::NinePointLinearOp::NinePointLinearOp(), QuantLib::SecondDerivativeOp::SecondDerivativeOp(), and QuantLib::SecondOrderMixedDerivativeOp::SecondOrderMixedDerivativeOp().
{
            return index_;
        }
bool QuantLib::FdmLinearOpIterator::operator!= (const FdmLinearOpIterator & iterator) [inline]
Definition at line 68 of file fdmlinearopiterator.hpp.
References index_.
{
            return index_ != iterator.index_;
        }
void QuantLib::FdmLinearOpIterator::operator++ () [inline]
Definition at line 56 of file fdmlinearopiterator.hpp.
References coordinates_, dim_, and index_.
{
            ++index_;
            for (Size i=0; i < dim_.size(); ++i) {
                if (++coordinates_[i] == dim_[i]) {
                    coordinates_[i] = 0;
                }
                else {
                    break;
                }
            }
        }
void QuantLib::FdmLinearOpIterator::swap (FdmLinearOpIterator & iter) [inline]
Definition at line 80 of file fdmlinearopiterator.hpp.
References coordinates_, dim_, and index_.
Referenced by FdmLinearOpIterator().
{
            std::swap(iter.index_, index_);
            dim_.swap(iter.dim_);
            coordinates_.swap(iter.coordinates_);
        }
Member Data Documentation
std::vector<Size> QuantLib::FdmLinearOpIterator::coordinates_ [private]
Definition at line 89 of file fdmlinearopiterator.hpp.
Referenced by coordinates(), operator++(), and swap().
std::vector<Size> QuantLib::FdmLinearOpIterator::dim_ [private]
Definition at line 88 of file fdmlinearopiterator.hpp.
Referenced by operator++(), and swap().
Size QuantLib::FdmLinearOpIterator::index_ [private]
Definition at line 87 of file fdmlinearopiterator.hpp.
Referenced by index(), operator!=(), operator++(), and swap().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/operators/fdmlinearopiterator.hpp