QuantLib: QuantLib::LfmCovarianceParameterization::Var_Helper Class Reference
QuantLib::LfmCovarianceParameterization::Var_Helper Class Reference
Public Member Functions
Var_Helper (const LfmCovarianceParameterization *param, Size i, Size j)
Real operator() (Real t) const
Private Attributes
const Size i_
const Size j_
const
LfmCovarianceParameterization * param_
Detailed Description
Definition at line 25 of file lfmcovarparam.cpp.
Constructor & Destructor Documentation
QuantLib::LfmCovarianceParameterization::Var_Helper::Var_Helper (const LfmCovarianceParameterization * param, Size i, Size j)
Definition at line 35 of file lfmcovarparam.cpp.
    : i_(i), j_(j), param_(param) {}
Member Function Documentation
Real QuantLib::LfmCovarianceParameterization::Var_Helper::operator() (Real t) const
Definition at line 40 of file lfmcovarparam.cpp.
References QuantLib::dsd::inner_product(), QuantLib::Matrix::row_begin(), and QuantLib::Matrix::row_end().
{
        const Matrix m = param_->diffusion(t);
        return std::inner_product(m.row_begin(i_), m.row_end(i_),
                                  m.row_begin(j_), 0.0);
    }
Member Data Documentation
const Size QuantLib::LfmCovarianceParameterization::Var_Helper::i_ [private]
Definition at line 31 of file lfmcovarparam.cpp.
const Size QuantLib::LfmCovarianceParameterization::Var_Helper::j_ [private]
Definition at line 31 of file lfmcovarparam.cpp.
const LfmCovarianceParameterization* QuantLib::LfmCovarianceParameterization::Var_Helper::param_ [private]
Definition at line 32 of file lfmcovarparam.cpp.
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/legacy/libormarketmodels/lfmcovarparam.cpp