QuantLib: QuantLib::GaussianQuadrature Class Reference
QuantLib::GaussianQuadrature Class Reference
Integral of a 1-dimensional function using the Gauss quadratures method.
#include <gaussianquadratures.hpp>
Public Member Functions
GaussianQuadrature (Size n, const GaussianOrthogonalPolynomial &p)
template<class F >
Real operator() (const F &f) const
Size order () const
const Array & weights ()
const Array & x ()
Private Attributes
Array x_
Array w_
Detailed Description
Integral of a 1-dimensional function using the Gauss quadratures method.
References: Gauss quadratures and orthogonal polynomials
G.H. Gloub and J.H. Welsch: Calculation of Gauss quadrature rule. Math. Comput. 23 (1986), 221-230
"Numerical Recipes in C", 2nd edition, Press, Teukolsky, Vetterling, Flannery,
Test:
the correctness of the result is tested by checking it against known good values.
Definition at line 47 of file gaussianquadratures.hpp.
Constructor & Destructor Documentation
QuantLib::GaussianQuadrature::GaussianQuadrature (Size n, const GaussianOrthogonalPolynomial & p)
Definition at line 31 of file gaussianquadratures.cpp.
References QuantLib::GaussianOrthogonalPolynomial::alpha(), QuantLib::GaussianOrthogonalPolynomial::beta(), QuantLib::TqrEigenDecomposition::eigenvalues(), QuantLib::TqrEigenDecomposition::eigenvectors(), QuantLib::GaussianOrthogonalPolynomial::mu_0(), QuantLib::TqrEigenDecomposition::OnlyFirstRowEigenVector, QuantLib::TqrEigenDecomposition::Overrelaxation, QuantLib::GaussianOrthogonalPolynomial::w(), w_, and x_.
    : x_(n), w_(n) {
        // set-up matrix to compute the roots and the weights
        Array e(n-1);
        Size i;
        for (i=1; i < n; ++i) {
            x_[i] = orthPoly.alpha(i);
            e[i-1] = std::sqrt(orthPoly.beta(i));
        }
        x_[0] = orthPoly.alpha(0);
        TqrEigenDecomposition tqr(
                               x_, e,
                               TqrEigenDecomposition::OnlyFirstRowEigenVector,
                               TqrEigenDecomposition::Overrelaxation);
        x_ = tqr.eigenvalues();
        const Matrix& ev = tqr.eigenvectors();
        Real mu_0 = orthPoly.mu_0();
        for (i=0; i<n; ++i) {
            w_[i] = mu_0*ev[0][i]*ev[0][i] / orthPoly.w(x_[i]);
        }
    }
Member Function Documentation
template<class F > Real QuantLib::GaussianQuadrature::operator() (const F & f) const [inline]
Definition at line 53 of file gaussianquadratures.hpp.
References anonymous_namespace{interpolations.cpp}::f(), order(), w_, and x_.
{
            Real sum = 0.0;
            for (Integer i = order()-1; i >= 0; --i) {
                sum += w_[i] * f(x_[i]);
            }
            return sum;
        }
Size QuantLib::GaussianQuadrature::order () const [inline]
Definition at line 61 of file gaussianquadratures.hpp.
References QuantLib::Array::size(), and x_.
Referenced by operator()().
{ return x_.size(); }
const Array& QuantLib::GaussianQuadrature::weights () [inline]
Definition at line 62 of file gaussianquadratures.hpp.
References w_.
Referenced by QuantLib::FdmExtOUJumpOp::FdmExtOUJumpOp().
{ return w_; }
const Array& QuantLib::GaussianQuadrature::x () [inline]
Definition at line 63 of file gaussianquadratures.hpp.
References x_.
Referenced by QuantLib::FdmExtOUJumpOp::FdmExtOUJumpOp().
{ return x_; }
Member Data Documentation
Array QuantLib::GaussianQuadrature::w_ [private]
Definition at line 66 of file gaussianquadratures.hpp.
Referenced by GaussianQuadrature(), operator()(), and weights().
Array QuantLib::GaussianQuadrature::x_ [private]
Definition at line 66 of file gaussianquadratures.hpp.
Referenced by GaussianQuadrature(), operator()(), order(), and x().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/integrals/gaussianquadratures.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/math/integrals/gaussianquadratures.cpp