QuantLib: QuantLib::CreditDefaultSwap Class Reference
QuantLib::CreditDefaultSwap Class Reference
Credit default swap.
#include <creditdefaultswap.hpp>
Classes
class arguments
class engine
class results
Public Member Functions
Constructors
CreditDefaultSwap (Protection::Side side, Real notional, Rate spread, const Schedule &schedule, BusinessDayConvention paymentConvention, const DayCounter &dayCounter, bool settlesAccrual=true, bool paysAtDefaultTime=true, const Date &protectionStart=Date(), const boost::shared_ptr< Claim > &=boost::shared_ptr< Claim >())
CDS quoted as running-spread only.
CreditDefaultSwap (Protection::Side side, Real notional, Rate upfront, Rate spread, const Schedule &schedule, BusinessDayConvention paymentConvention, const DayCounter &dayCounter, bool settlesAccrual=true, bool paysAtDefaultTime=true, const Date &protectionStart=Date(), const Date &upfrontDate=Date(), const boost::shared_ptr< Claim > &=boost::shared_ptr< Claim >())
CDS quoted as upfront and running spread.
Inspectors
Protection::Side side () const
Real notional () const
Rate runningSpread () const
boost::optional< Rate > upfront () const
bool settlesAccrual () const
bool paysAtDefaultTime () const
const Leg & coupons () const
const Date & protectionStartDate () const
The first date for which defaults will trigger the contract.
const Date & protectionEndDate () const
The last date for which defaults will trigger the contract.
Results
Rate fairUpfront () const
Rate fairSpread () const
Real couponLegBPS () const
Real upfrontBPS () const
Real couponLegNPV () const
Real defaultLegNPV () const
Real upfrontNPV () const
Rate impliedHazardRate (Real targetNPV, const Handle< YieldTermStructure > &discountCurve, const DayCounter &dayCounter, Real recoveryRate=0.4, Real accuracy=1.0e-6) const
Implied hazard rate calculation.
Rate conventionalSpread (Real conventionalRecovery, const Handle< YieldTermStructure > &discountCurve, const DayCounter &dayCounter) const
Conventional/standard upfront-to-spread conversion.
Protected Attributes
Protection::Side side_
Real notional_
boost::optional< Rate > upfront_
Rate runningSpread_
bool settlesAccrual_
bool paysAtDefaultTime_
boost::shared_ptr< Claim > claim_
Leg leg_
boost::shared_ptr< CashFlow > upfrontPayment_
Date protectionStart_
Rate fairUpfront_
Rate fairSpread_
Real couponLegBPS_
Real couponLegNPV_
Real upfrontBPS_
Real upfrontNPV_
Real defaultLegNPV_
Instrument interface
bool isExpired () const
returns whether the instrument might have value greater than zero.
void setupArguments (PricingEngine::arguments *) const
void fetchResults (const PricingEngine::results *) const
void setupExpired () const
Detailed Description
Credit default swap.
Note:
This instrument currently assumes that the issuer did not default until today's date.
Warning:
if Settings::includeReferenceDateCashFlows() is set to true, payments occurring at the settlement date of the swap might be included in the NPV and therefore affect the fair-spread calculation. This might not be what you want.
Definition at line 52 of file creditdefaultswap.hpp.
Constructor & Destructor Documentation
QuantLib::CreditDefaultSwap::CreditDefaultSwap (Protection::Side side, Real notional, Rate spread, const Schedule & schedule, BusinessDayConvention paymentConvention, const DayCounter & dayCounter, bool settlesAccrual = true, bool paysAtDefaultTime = true, const Date & protectionStart = Date(), const boost::shared_ptr< Claim > & claim = boost::shared_ptr<Claim>())
CDS quoted as running-spread only.
Parameters:
side Whether the protection is bought or sold.
notional Notional value
spread Running spread in fractional units.
schedule Coupon schedule.
paymentConvention Business-day convention for payment-date adjustment.
dayCounter Day-count convention for accrual.
settlesAccrual Whether or not the accrued coupon is due in the event of a default.
paysAtDefaultTime If set to true, any payments triggered by a default event are due at default time. If set to false, they are due at the end of the accrual period.
protectionStart The first date where a default event will trigger the contract.
Definition at line 35 of file creditdefaultswap.cpp.
References claim_, leg_, protectionStart_, QL_REQUIRE, QuantLib::Observer::registerWith(), upfrontPayment_, QuantLib::FixedRateLeg::withCouponRates(), QuantLib::FixedRateLeg::withNotionals(), and QuantLib::FixedRateLeg::withPaymentAdjustment().
    : side_(side), notional_(notional), upfront_(boost::none),
      runningSpread_(spread), settlesAccrual_(settlesAccrual),
      paysAtDefaultTime_(paysAtDefaultTime), claim_(claim),
      protectionStart_(protectionStart == Null<Date>() ? schedule[0] :
                                                         protectionStart) {
        QL_REQUIRE(protectionStart_ <= schedule[0],
                   "protection can not start after accrual");
        leg_ = FixedRateLeg(schedule)
            .withNotionals(notional)
            .withCouponRates(spread, dayCounter)
            .withPaymentAdjustment(convention);
        upfrontPayment_.reset(new SimpleCashFlow(0.0, schedule[0]));
        if (!claim_)
            claim_ = boost::shared_ptr<Claim>(new FaceValueClaim);
        registerWith(claim_);
    }
QuantLib::CreditDefaultSwap::CreditDefaultSwap (Protection::Side side, Real notional, Rate upfront, Rate spread, const Schedule & schedule, BusinessDayConvention paymentConvention, const DayCounter & dayCounter, bool settlesAccrual = true, bool paysAtDefaultTime = true, const Date & protectionStart = Date(), const Date & upfrontDate = Date(), const boost::shared_ptr< Claim > & claim = boost::shared_ptr<Claim>())
CDS quoted as upfront and running spread.
Parameters:
side Whether the protection is bought or sold.
notional Notional value
upfront Upfront in fractional units.
spread Running spread in fractional units.
schedule Coupon schedule.
paymentConvention Business-day convention for payment-date adjustment.
dayCounter Day-count convention for accrual.
settlesAccrual Whether or not the accrued coupon is due in the event of a default.
paysAtDefaultTime If set to true, any payments triggered by a default event are due at default time. If set to false, they are due at the end of the accrual period.
protectionStart The first date where a default event will trigger the contract.
upfrontDate Settlement date for the upfront payment.
Definition at line 63 of file creditdefaultswap.cpp.
References claim_, anonymous_namespace{marketmodel.cpp}::d, leg_, protectionStart_, QL_REQUIRE, QuantLib::Observer::registerWith(), upfrontPayment_, QuantLib::FixedRateLeg::withCouponRates(), QuantLib::FixedRateLeg::withNotionals(), and QuantLib::FixedRateLeg::withPaymentAdjustment().
    : side_(side), notional_(notional), upfront_(upfront),
      runningSpread_(runningSpread), settlesAccrual_(settlesAccrual),
      paysAtDefaultTime_(paysAtDefaultTime), claim_(claim),
      protectionStart_(protectionStart == Null<Date>() ? schedule[0] :
                                                         protectionStart) {
        QL_REQUIRE(protectionStart_ <= schedule[0],
                   "protection can not start after accrual");
        leg_ = FixedRateLeg(schedule)
            .withNotionals(notional)
            .withCouponRates(runningSpread, dayCounter)
            .withPaymentAdjustment(convention);
        Date d = upfrontDate == Null<Date>() ? schedule[0] : upfrontDate;
        upfrontPayment_.reset(new SimpleCashFlow(notional*upfront, d));
        QL_REQUIRE(upfrontPayment_->date() >= protectionStart_,
                   "upfront can not be due before contract start");
        if (!claim_)
            claim_ = boost::shared_ptr<Claim>(new FaceValueClaim);
        registerWith(claim_);
    }
Member Function Documentation
Rate QuantLib::CreditDefaultSwap::conventionalSpread (Real conventionalRecovery, const Handle< YieldTermStructure > & discountCurve, const DayCounter & dayCounter) const
Conventional/standard upfront-to-spread conversion.
Under a standard ISDA model and a set of standardised instrument characteristics, it is the running only quoted spread that will make a CDS contract have an NPV of 0 when quoted for that running only spread. Refer to: "ISDA Standard CDS converter specification." May 2009.
The conventional recovery rate to apply in the calculation is as specified by ISDA, not necessarily equal to the market-quoted one. It is typically 0.4 for SeniorSec and 0.2 for subordinate.
Note:
The conversion employs a flat hazard rate. As a result, you will not recover the market quotes.
This method performs the calculation with the instrument characteristics. It will coincide with the ISDA calculation if your object has the standard characteristics. Notably:
The calendar should have no bank holidays, just weekends.
The yield curve should be LIBOR piecewise constant in fwd rates, with a discount factor of 1 on the calculation date, which coincides with the trade date.
Convention should be Following for yield curve and contract cashflows.
The CDS should pay accrued and mature on standard IMM dates, settle on trade date +1 and upfront settle on trade date +3.
Definition at line 280 of file creditdefaultswap.cpp.
References QuantLib::MidPointCdsEngine::calculate(), QuantLib::CreditDefaultSwap::results::fairSpread, QuantLib::GenericEngine< ArgumentsType, ResultsType >::getArguments(), QuantLib::GenericEngine< ArgumentsType, ResultsType >::getResults(), impliedHazardRate(), and setupArguments().
{
        Rate flatHazardRate = impliedHazardRate(0.0,
                                                discountCurve,
                                                dayCounter,
                                                conventionalRecovery);
        Handle<DefaultProbabilityTermStructure> probability(
            boost::shared_ptr<DefaultProbabilityTermStructure>(
                             new FlatHazardRate(0, WeekendsOnly(),
                                                flatHazardRate, dayCounter)));
        MidPointCdsEngine engine(probability, conventionalRecovery,
                                 discountCurve, true);
        setupArguments(engine.getArguments());
        engine.calculate();
        const CreditDefaultSwap::results* results =
            dynamic_cast<const CreditDefaultSwap::results*>(
                                                       engine.getResults());
        return results->fairSpread;
    }
Real QuantLib::CreditDefaultSwap::couponLegBPS () const
Returns the variation of the fixed-leg value given a one-basis-point change in the running spread.
Definition at line 191 of file creditdefaultswap.cpp.
References QuantLib::Instrument::calculate(), couponLegBPS_, and QL_REQUIRE.
Referenced by QuantLib::CreditDefaultSwap::results::reset().
{
        calculate();
        QL_REQUIRE(couponLegBPS_ != Null<Rate>(),
                   "coupon-leg BPS not available");
        return couponLegBPS_;
    }
Real QuantLib::CreditDefaultSwap::couponLegNPV () const
Definition at line 198 of file creditdefaultswap.cpp.
References QuantLib::Instrument::calculate(), couponLegNPV_, and QL_REQUIRE.
Referenced by QuantLib::CreditDefaultSwap::results::reset().
{
        calculate();
        QL_REQUIRE(couponLegNPV_ != Null<Rate>(),
                   "coupon-leg NPV not available");
        return couponLegNPV_;
    }
const Leg & QuantLib::CreditDefaultSwap::coupons () const
Definition at line 120 of file creditdefaultswap.cpp.
References leg_.
{
        return leg_;
    }
Real QuantLib::CreditDefaultSwap::defaultLegNPV () const
Definition at line 205 of file creditdefaultswap.cpp.
References QuantLib::Instrument::calculate(), defaultLegNPV_, and QL_REQUIRE.
Referenced by QuantLib::CreditDefaultSwap::results::reset().
{
        calculate();
        QL_REQUIRE(defaultLegNPV_ != Null<Rate>(),
                   "default-leg NPV not available");
        return defaultLegNPV_;
    }
Rate QuantLib::CreditDefaultSwap::fairSpread () const
Returns the running spread that, given the quoted recovery rate, will make the running-only CDS have an NPV of 0.
Note:
This calculation does not take any upfront into account, even if one was given.
Definition at line 184 of file creditdefaultswap.cpp.
References QuantLib::Instrument::calculate(), fairSpread_, and QL_REQUIRE.
Referenced by QuantLib::CreditDefaultSwap::results::reset(), anonymous_namespace{defaultprobabilitycurves.cpp}::testBootstrapFromSpread(), CdsOptionTest::testCached(), CreditDefaultSwapTest::testCachedMarketValue(), CreditDefaultSwapTest::testCachedValue(), CreditDefaultSwapTest::testFairSpread(), and NthToDefaultTest::testGauss().
{
        calculate();
        QL_REQUIRE(fairSpread_ != Null<Rate>(),
                   "fair spread not available");
        return fairSpread_;
    }
Rate QuantLib::CreditDefaultSwap::fairUpfront () const
Returns the upfront spread that, given the running spread and the quoted recovery rate, will make the instrument have an NPV of 0.
Definition at line 177 of file creditdefaultswap.cpp.
References QuantLib::Instrument::calculate(), fairUpfront_, and QL_REQUIRE.
Referenced by QuantLib::CreditDefaultSwap::results::reset(), anonymous_namespace{defaultprobabilitycurves.cpp}::testBootstrapFromUpfront(), and CreditDefaultSwapTest::testFairUpfront().
{
        calculate();
        QL_REQUIRE(fairUpfront_ != Null<Rate>(),
                   "fair upfront not available");
        return fairUpfront_;
    }
void QuantLib::CreditDefaultSwap::fetchResults (const PricingEngine::results * r) const [virtual]
When a derived result structure is defined for an instrument, this method should be overridden to read from it. This is mandatory in case a pricing engine is used.
Reimplemented from QuantLib::Instrument.
Definition at line 160 of file creditdefaultswap.cpp.
References QuantLib::CreditDefaultSwap::results::couponLegBPS, couponLegBPS_, QuantLib::CreditDefaultSwap::results::couponLegNPV, couponLegNPV_, QuantLib::CreditDefaultSwap::results::defaultLegNPV, defaultLegNPV_, QuantLib::CreditDefaultSwap::results::fairSpread, fairSpread_, QuantLib::CreditDefaultSwap::results::fairUpfront, fairUpfront_, QL_REQUIRE, QuantLib::CreditDefaultSwap::results::upfrontBPS, upfrontBPS_, QuantLib::CreditDefaultSwap::results::upfrontNPV, and upfrontNPV_.
{
        Instrument::fetchResults(r);
        const CreditDefaultSwap::results* results =
            dynamic_cast<const CreditDefaultSwap::results*>(r);
        QL_REQUIRE(results != 0, "wrong result type");
        fairSpread_ = results->fairSpread;
        fairUpfront_ = results->fairUpfront;
        couponLegBPS_ = results->couponLegBPS;
        couponLegNPV_ = results->couponLegNPV;
        defaultLegNPV_ = results->defaultLegNPV;
        upfrontNPV_ = results->upfrontNPV;
        upfrontBPS_ = results->upfrontBPS;
    }
Rate QuantLib::CreditDefaultSwap::impliedHazardRate (Real targetNPV, const Handle< YieldTermStructure > & discountCurve, const DayCounter & dayCounter, Real recoveryRate = 0.4, Real accuracy = 1.0e-6) const
Implied hazard rate calculation.
Note:
This method performs the calculation with the instrument characteristics. It will coincide with the ISDA calculation if your object has the standard characteristics. Notably:
The calendar should have no bank holidays, just weekends.
The yield curve should be LIBOR piecewise constant in fwd rates, with a discount factor of 1 on the calculation date, which coincides with the trade date.
Convention should be Following for yield curve and contract cashflows.
The CDS should pay accrued and mature on standard IMM dates, settle on trade date +1 and upfront settle on trade date +3.
Definition at line 252 of file creditdefaultswap.cpp.
References anonymous_namespace{interpolations.cpp}::f(), QuantLib::flatRate(), QuantLib::GenericEngine< ArgumentsType, ResultsType >::getArguments(), QuantLib::GenericEngine< ArgumentsType, ResultsType >::getResults(), setupArguments(), and QuantLib::Solver1D< Impl >::solve().
Referenced by conventionalSpread(), and CreditDefaultSwapTest::testImpliedHazardRate().
{
        boost::shared_ptr<SimpleQuote> flatRate(new SimpleQuote(0.0));
        Handle<DefaultProbabilityTermStructure> probability(
            boost::shared_ptr<DefaultProbabilityTermStructure>(new
                FlatHazardRate(0, WeekendsOnly(),
                               Handle<Quote>(flatRate), dayCounter)));
        MidPointCdsEngine engine(probability, recoveryRate, discountCurve);
        setupArguments(engine.getArguments());
        const CreditDefaultSwap::results* results =
            dynamic_cast<const CreditDefaultSwap::results*>(
                                                       engine.getResults());
        ObjectiveFunction f(targetNPV, *flatRate, engine, results);
        Rate guess = 0.001;
        Rate step = guess*0.1;
        return Brent().solve(f, accuracy, guess, step);
    }
bool QuantLib::CreditDefaultSwap::isExpired () const [virtual]
returns whether the instrument might have value greater than zero.
Implements QuantLib::Instrument.
Definition at line 125 of file creditdefaultswap.cpp.
References leg_.
{
        for (Leg::const_reverse_iterator i = leg_.rbegin();
                                         i != leg_.rend(); ++i) {
            if (!(*i)->hasOccurred())
                return false;
        }
        return true;
    }
Real QuantLib::CreditDefaultSwap::notional () const
Definition at line 100 of file creditdefaultswap.cpp.
References notional_.
Referenced by QuantLib::CreditDefaultSwap::arguments::validate().
{
        return notional_;
    }
bool QuantLib::CreditDefaultSwap::paysAtDefaultTime () const
Definition at line 116 of file creditdefaultswap.cpp.
References paysAtDefaultTime_.
{
        return paysAtDefaultTime_;
    }
const Date & QuantLib::CreditDefaultSwap::protectionEndDate () const
The last date for which defaults will trigger the contract.
Definition at line 309 of file creditdefaultswap.cpp.
References leg_.
{
        return boost::dynamic_pointer_cast<Coupon>(leg_.back())
            ->accrualEndDate();
    }
const Date & QuantLib::CreditDefaultSwap::protectionStartDate () const
The first date for which defaults will trigger the contract.
Definition at line 305 of file creditdefaultswap.cpp.
References protectionStart_.
{
        return protectionStart_;
    }
Rate QuantLib::CreditDefaultSwap::runningSpread () const
Definition at line 104 of file creditdefaultswap.cpp.
References runningSpread_.
{
        return runningSpread_;
    }
bool QuantLib::CreditDefaultSwap::settlesAccrual () const
Definition at line 112 of file creditdefaultswap.cpp.
References settlesAccrual_.
{
        return settlesAccrual_;
    }
void QuantLib::CreditDefaultSwap::setupArguments (PricingEngine::arguments *) const [virtual]
When a derived argument structure is defined for an instrument, this method should be overridden to fill it. This is mandatory in case a pricing engine is used.
Reimplemented from QuantLib::Instrument.
Definition at line 141 of file creditdefaultswap.cpp.
References QuantLib::CreditDefaultSwap::arguments::claim, claim_, QuantLib::CreditDefaultSwap::arguments::leg, leg_, QuantLib::CreditDefaultSwap::arguments::notional, notional_, QuantLib::CreditDefaultSwap::arguments::paysAtDefaultTime, paysAtDefaultTime_, QuantLib::CreditDefaultSwap::arguments::protectionStart, protectionStart_, QL_REQUIRE, runningSpread_, QuantLib::CreditDefaultSwap::arguments::settlesAccrual, settlesAccrual_, QuantLib::CreditDefaultSwap::arguments::side, side_, QuantLib::CreditDefaultSwap::arguments::spread, QuantLib::CreditDefaultSwap::arguments::upfront, upfront_, QuantLib::CreditDefaultSwap::arguments::upfrontPayment, and upfrontPayment_.
Referenced by conventionalSpread(), and impliedHazardRate().
{
        CreditDefaultSwap::arguments* arguments =
            dynamic_cast<CreditDefaultSwap::arguments*>(args);
        QL_REQUIRE(arguments != 0, "wrong argument type");
        arguments->side = side_;
        arguments->notional = notional_;
        arguments->leg = leg_;
        arguments->upfrontPayment = upfrontPayment_;
        arguments->settlesAccrual = settlesAccrual_;
        arguments->paysAtDefaultTime = paysAtDefaultTime_;
        arguments->claim = claim_;
        arguments->upfront = upfront_;
        arguments->spread = runningSpread_;
        arguments->protectionStart = protectionStart_;
    }
void QuantLib::CreditDefaultSwap::setupExpired () const [protected, virtual]
This method must leave the instrument in a consistent state when the expiration condition is met.
Reimplemented from QuantLib::Instrument.
Definition at line 134 of file creditdefaultswap.cpp.
References couponLegBPS_, couponLegNPV_, defaultLegNPV_, fairSpread_, fairUpfront_, upfrontBPS_, and upfrontNPV_.
{
        Instrument::setupExpired();
        fairSpread_ = fairUpfront_ = 0.0;
        couponLegBPS_ = upfrontBPS_ = 0.0;
        couponLegNPV_ = defaultLegNPV_ = upfrontNPV_ = 0.0;
    }
Protection::Side QuantLib::CreditDefaultSwap::side () const
Definition at line 96 of file creditdefaultswap.cpp.
References side_.
Referenced by QuantLib::CreditDefaultSwap::arguments::validate().
{
        return side_;
    }
boost::optional< Rate > QuantLib::CreditDefaultSwap::upfront () const
Definition at line 108 of file creditdefaultswap.cpp.
References upfront_.
{
        return upfront_;
    }
Real QuantLib::CreditDefaultSwap::upfrontBPS () const
Definition at line 219 of file creditdefaultswap.cpp.
References QuantLib::Instrument::calculate(), QL_REQUIRE, and upfrontBPS_.
Referenced by QuantLib::CreditDefaultSwap::results::reset().
{
        calculate();
        QL_REQUIRE(upfrontBPS_ != Null<Real>(),
                   "upfront BPS not available");
        return upfrontBPS_;
    }
Real QuantLib::CreditDefaultSwap::upfrontNPV () const
Definition at line 212 of file creditdefaultswap.cpp.
References QuantLib::Instrument::calculate(), QL_REQUIRE, and upfrontNPV_.
Referenced by QuantLib::CreditDefaultSwap::results::reset().
{
        calculate();
        QL_REQUIRE(upfrontNPV_ != Null<Real>(),
                   "upfront NPV not available");
        return upfrontNPV_;
    }
Member Data Documentation
boost::shared_ptr<Claim> QuantLib::CreditDefaultSwap::claim_ [protected]
Definition at line 235 of file creditdefaultswap.hpp.
Referenced by CreditDefaultSwap(), and setupArguments().
Real QuantLib::CreditDefaultSwap::couponLegBPS_ [mutable, protected]
Definition at line 242 of file creditdefaultswap.hpp.
Referenced by couponLegBPS(), fetchResults(), and setupExpired().
Real QuantLib::CreditDefaultSwap::couponLegNPV_ [mutable, protected]
Definition at line 242 of file creditdefaultswap.hpp.
Referenced by couponLegNPV(), fetchResults(), and setupExpired().
Real QuantLib::CreditDefaultSwap::defaultLegNPV_ [mutable, protected]
Definition at line 244 of file creditdefaultswap.hpp.
Referenced by defaultLegNPV(), fetchResults(), and setupExpired().
Rate QuantLib::CreditDefaultSwap::fairSpread_ [mutable, protected]
Definition at line 241 of file creditdefaultswap.hpp.
Referenced by fairSpread(), fetchResults(), and setupExpired().
Rate QuantLib::CreditDefaultSwap::fairUpfront_ [mutable, protected]
Definition at line 240 of file creditdefaultswap.hpp.
Referenced by fairUpfront(), fetchResults(), and setupExpired().
Leg QuantLib::CreditDefaultSwap::leg_ [protected]
Definition at line 236 of file creditdefaultswap.hpp.
Referenced by coupons(), CreditDefaultSwap(), isExpired(), protectionEndDate(), and setupArguments().
Real QuantLib::CreditDefaultSwap::notional_ [protected]
Definition at line 231 of file creditdefaultswap.hpp.
Referenced by notional(), and setupArguments().
bool QuantLib::CreditDefaultSwap::paysAtDefaultTime_ [protected]
Definition at line 234 of file creditdefaultswap.hpp.
Referenced by paysAtDefaultTime(), and setupArguments().
Date QuantLib::CreditDefaultSwap::protectionStart_ [protected]
Definition at line 238 of file creditdefaultswap.hpp.
Referenced by CreditDefaultSwap(), protectionStartDate(), and setupArguments().
Rate QuantLib::CreditDefaultSwap::runningSpread_ [protected]
Definition at line 233 of file creditdefaultswap.hpp.
Referenced by runningSpread(), and setupArguments().
bool QuantLib::CreditDefaultSwap::settlesAccrual_ [protected]
Definition at line 234 of file creditdefaultswap.hpp.
Referenced by settlesAccrual(), and setupArguments().
Protection::Side QuantLib::CreditDefaultSwap::side_ [protected]
Definition at line 230 of file creditdefaultswap.hpp.
Referenced by setupArguments(), and side().
boost::optional<Rate> QuantLib::CreditDefaultSwap::upfront_ [protected]
Definition at line 232 of file creditdefaultswap.hpp.
Referenced by setupArguments(), and upfront().
Real QuantLib::CreditDefaultSwap::upfrontBPS_ [mutable, protected]
Definition at line 243 of file creditdefaultswap.hpp.
Referenced by fetchResults(), setupExpired(), and upfrontBPS().
Real QuantLib::CreditDefaultSwap::upfrontNPV_ [mutable, protected]
Definition at line 243 of file creditdefaultswap.hpp.
Referenced by fetchResults(), setupExpired(), and upfrontNPV().
boost::shared_ptr<CashFlow> QuantLib::CreditDefaultSwap::upfrontPayment_ [protected]
Definition at line 237 of file creditdefaultswap.hpp.
Referenced by CreditDefaultSwap(), and setupArguments().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/creditdefaultswap.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/creditdefaultswap.cpp