QuantLib: QuantLib::GaussKronrodAdaptive Class Reference
QuantLib::GaussKronrodAdaptive Class Reference
Integral of a 1-dimensional function using the Gauss-Kronrod methods.
#include <kronrodintegral.hpp>
Public Member Functions
GaussKronrodAdaptive (Real tolerance, Size maxFunctionEvaluations=Null< Size >())
Protected Member Functions
Real integrate (const boost::function< Real(Real)> &f, Real a, Real b) const
Private Member Functions
Real integrateRecursively (const boost::function< Real(Real)> &f, Real a, Real b, Real tolerance) const
Detailed Description
Integral of a 1-dimensional function using the Gauss-Kronrod methods.
This class provide an adaptive integration procedure using 15 points Gauss-Kronrod integration rule. This is more robust in that it allows to integrate less smooth functions (though singular functions should be integrated using dedicated algorithms) but less efficient beacuse it does not reuse precedently computed points during computation steps.
References:
Gauss-Kronrod Integration <http://mathcssun1.emporia.edu/~oneilcat/ExperimentApplet3/ExperimentApplet3.html>
NMS - Numerical Analysis Library <http://www.math.iastate.edu/burkardt/f_src/nms/nms.html>
Test:
the correctness of the result is tested by checking it against known good values.
Definition at line 86 of file kronrodintegral.hpp.
Constructor & Destructor Documentation
QuantLib::GaussKronrodAdaptive::GaussKronrodAdaptive (Real tolerance, Size maxFunctionEvaluations = Null<Size>())
Definition at line 437 of file kronrodintegral.cpp.
References QL_REQUIRE.
    : Integrator(absoluteAccuracy, maxEvaluations) {
        QL_REQUIRE(maxEvaluations >= 15,
                   "required maxEvaluations (" << maxEvaluations <<
                   ") not allowed. It must be >= 15");
    }
Member Function Documentation
Real QuantLib::GaussKronrodAdaptive::integrate (const boost::function< Real(Real)> & f, Real a, Real b) const [protected, virtual]
Implements QuantLib::Integrator.
Definition at line 349 of file kronrodintegral.cpp.
References QuantLib::Integrator::absoluteAccuracy(), anonymous_namespace{interpolations.cpp}::f(), and integrateRecursively().
{
        return integrateRecursively(f, a, b, absoluteAccuracy());
    }
Real QuantLib::GaussKronrodAdaptive::integrateRecursively (const boost::function< Real(Real)> & f, Real a, Real b, Real tolerance) const [private]
Definition at line 381 of file kronrodintegral.cpp.
References anonymous_namespace{marketmodel.cpp}::a, anonymous_namespace{marketmodel.cpp}::b, anonymous_namespace{interpolations.cpp}::f(), QuantLib::g7w, QuantLib::Integrator::increaseNumberOfEvaluations(), QuantLib::k15t, QuantLib::k15w, QuantLib::Integrator::maxEvaluations(), QuantLib::Integrator::numberOfEvaluations(), QL_REQUIRE, and anonymous_namespace{quantlibbenchmark.cpp}::t.
Referenced by integrate().
{
            Real halflength = (b - a) / 2;
            Real center = (a + b) / 2;
            Real g7; // will be result of G7 integral
            Real k15; // will be result of K15 integral
            Real t, fsum; // t (abscissa) and f(t)
            Real fc = f(center);
            g7 = fc * g7w[0];
            k15 = fc * k15w[0];
            // calculate g7 and half of k15
            Integer j, j2;
            for (j = 1, j2 = 2; j < 4; j++, j2 += 2) {
                t = halflength * k15t[j2];
                fsum = f(center - t) + f(center + t);
                g7  += fsum * g7w[j];
                k15 += fsum * k15w[j2];
            }
            // calculate other half of k15
            for (j2 = 1; j2 < 8; j2 += 2) {
                t = halflength * k15t[j2];
                fsum = f(center - t) + f(center + t);
                k15 += fsum * k15w[j2];
            }
            // multiply by (a - b) / 2
            g7 = halflength * g7;
            k15 = halflength * k15;
            // 15 more function evaluations have been used
            increaseNumberOfEvaluations(15);
            // error is <= k15 - g7
            // if error is larger than tolerance then split the interval
            // in two and integrate recursively
            if (std::fabs(k15 - g7) < tolerance) {
                return k15;
            } else {
                QL_REQUIRE(numberOfEvaluations()+30 <=
                           maxEvaluations(),
                           "maximum number of function evaluations "
                           "exceeded");
                return integrateRecursively(f, a, center, tolerance/2)
                    + integrateRecursively(f, center, b, tolerance/2);
            }
        }
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/integrals/kronrodintegral.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/math/integrals/kronrodintegral.cpp