QuantLib: QuantLib::BinomialConvertibleEngine< T > Class Template Reference
QuantLib::BinomialConvertibleEngine< T > Class Template Reference
Binomial Tsiveriotis-Fernandes engine for convertible bonds.
#include <binomialconvertibleengine.hpp>
Public Member Functions
BinomialConvertibleEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > &process, Size timeSteps)
void calculate () const
Private Attributes
boost::shared_ptr
< GeneralizedBlackScholesProcess > process_
Size timeSteps_
Detailed Description
template<class T>
class QuantLib::BinomialConvertibleEngine< T >
Binomial Tsiveriotis-Fernandes engine for convertible bonds.
Definition at line 45 of file binomialconvertibleengine.hpp.
Constructor & Destructor Documentation
template<class T > QuantLib::BinomialConvertibleEngine< T >::BinomialConvertibleEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > & process, Size timeSteps) [inline]
Definition at line 47 of file binomialconvertibleengine.hpp.
References QuantLib::BinomialConvertibleEngine< T >::process_, QL_REQUIRE, and QuantLib::Observer::registerWith().
        : process_(process), timeSteps_(timeSteps) {
            QL_REQUIRE(timeSteps>0,
                       "timeSteps must be positive, " << timeSteps <<
                       " not allowed");
            registerWith(process_);
        }
Member Function Documentation
template<class T > void QuantLib::BinomialConvertibleEngine< T >::calculate () const [virtual]
Implements QuantLib::PricingEngine.
Definition at line 64 of file binomialconvertibleengine.hpp.
References QuantLib::Continuous, QuantLib::flatVol(), QuantLib::DiscretizedAsset::initialize(), QuantLib::NoFrequency, QuantLib::DiscretizedAsset::presentValue(), QL_ENSURE, QL_REQUIRE, QuantLib::DiscretizedAsset::rollback(), anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::DayCounter::yearFraction().
{
        DayCounter rfdc  = process_->riskFreeRate()->dayCounter();
        DayCounter divdc = process_->dividendYield()->dayCounter();
        DayCounter voldc = process_->blackVolatility()->dayCounter();
        Calendar volcal = process_->blackVolatility()->calendar();
        Real s0 = process_->x0();
        QL_REQUIRE(s0 > 0.0, "negative or null underlying");
        Volatility v = process_->blackVolatility()->blackVol(
                                         arguments_.exercise->lastDate(), s0);
        Date maturityDate = arguments_.exercise->lastDate();
        Rate riskFreeRate = process_->riskFreeRate()->zeroRate(
                                 maturityDate, rfdc, Continuous, NoFrequency);
        Rate q = process_->dividendYield()->zeroRate(
                                maturityDate, divdc, Continuous, NoFrequency);
        Date referenceDate = process_->riskFreeRate()->referenceDate();
        // subtract dividends
        Size i;
        for (i=0; i<arguments_.dividends.size(); i++) {
            if (arguments_.dividends[i]->date() >= referenceDate)
                s0 -= arguments_.dividends[i]->amount() *
                      process_->riskFreeRate()->discount(
                                             arguments_.dividends[i]->date());
        }
        QL_REQUIRE(s0 > 0.0,
                   "negative value after subtracting dividends");
        // binomial trees with constant coefficient
        Handle<Quote> underlying(boost::shared_ptr<Quote>(new SimpleQuote(s0)));
        Handle<YieldTermStructure> flatRiskFree(
            boost::shared_ptr<YieldTermStructure>(
                new FlatForward(referenceDate, riskFreeRate, rfdc)));
        Handle<YieldTermStructure> flatDividends(
            boost::shared_ptr<YieldTermStructure>(
                new FlatForward(referenceDate, q, divdc)));
        Handle<BlackVolTermStructure> flatVol(
            boost::shared_ptr<BlackVolTermStructure>(
                new BlackConstantVol(referenceDate, volcal, v, voldc)));
        boost::shared_ptr<PlainVanillaPayoff> payoff =
            boost::dynamic_pointer_cast<PlainVanillaPayoff>(arguments_.payoff);
        QL_REQUIRE(payoff, "non-plain payoff given");
        Time maturity = rfdc.yearFraction(arguments_.settlementDate,
                                          maturityDate);
        boost::shared_ptr<GeneralizedBlackScholesProcess> bs(
                 new GeneralizedBlackScholesProcess(underlying, flatDividends,
                                                    flatRiskFree, flatVol));
        boost::shared_ptr<T> tree(new T(bs, maturity, timeSteps_,
                                        payoff->strike()));
        Real creditSpread = arguments_.creditSpread->value();
        boost::shared_ptr<Lattice> lattice(
              new TsiveriotisFernandesLattice<T>(tree,riskFreeRate,maturity,
                                                 timeSteps_,creditSpread,v,q));
        DiscretizedConvertible convertible(arguments_, bs,
                                           TimeGrid(maturity, timeSteps_));
        convertible.initialize(lattice, maturity);
        convertible.rollback(0.0);
        results_.value = convertible.presentValue();
        QL_ENSURE(results_.value < std::numeric_limits<Real>::max(),
                  "floating-point overflow on tree grid");
    }
Member Data Documentation
template<class T > boost::shared_ptr<GeneralizedBlackScholesProcess> QuantLib::BinomialConvertibleEngine< T >::process_ [private]
Definition at line 58 of file binomialconvertibleengine.hpp.
Referenced by QuantLib::BinomialConvertibleEngine< T >::BinomialConvertibleEngine().
template<class T > Size QuantLib::BinomialConvertibleEngine< T >::timeSteps_ [private]
Definition at line 59 of file binomialconvertibleengine.hpp.
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/convertiblebonds/binomialconvertibleengine.hpp