QuantLib: QuantLib::StochasticProcess Class Reference
QuantLib::StochasticProcess Class Reference
multi-dimensional stochastic process class.
#include <stochasticprocess.hpp>
Classes
class discretization
discretization of a stochastic process over a given time interval
Public Member Functions
virtual ~StochasticProcess ()
Stochastic process interface
virtual Size size () const =0
returns the number of dimensions of the stochastic process
virtual Size factors () const
returns the number of independent factors of the process
virtual Disposable< Array > initialValues () const =0
returns the initial values of the state variables
virtual Disposable< Array > drift (Time t, const Array &x) const =0
returns the drift part of the equation, i.e., \(\mu(t, \mathrm{x}_t) \)
virtual Disposable< Matrix > diffusion (Time t, const Array &x) const =0
returns the diffusion part of the equation, i.e. \(\sigma(t, \mathrm{x}_t) \)
virtual Disposable< Array > expectation (Time t0, const Array &x0, Time dt) const
virtual Disposable< Matrix > stdDeviation (Time t0, const Array &x0, Time dt) const
virtual Disposable< Matrix > covariance (Time t0, const Array &x0, Time dt) const
virtual Disposable< Array > evolve (Time t0, const Array &x0, Time dt, const Array &dw) const
virtual Disposable< Array > apply (const Array &x0, const Array &dx) const
utilities
virtual Time time (const Date &) const
Observer interface
void update ()
Protected Member Functions
StochasticProcess ()
StochasticProcess (const boost::shared_ptr< discretization > &)
Protected Attributes
boost::shared_ptr< discretization > discretization_
Detailed Description
multi-dimensional stochastic process class.
This class describes a stochastic process governed by
\[ d\mathrm{x}_t = \mu(t, x_t)\mathrm{d}t + \sigma(t, \mathrm{x}_t) \cdot d\mathrm{W}_t. \]
Definition at line 42 of file stochasticprocess.hpp.
Constructor & Destructor Documentation
virtual QuantLib::StochasticProcess::~StochasticProcess () [inline, virtual]
Definition at line 60 of file stochasticprocess.hpp.
{}
QuantLib::StochasticProcess::StochasticProcess () [protected]
Definition at line 28 of file stochasticprocess.cpp.
{}
QuantLib::StochasticProcess::StochasticProcess (const boost::shared_ptr< discretization > & disc) [protected]
Definition at line 30 of file stochasticprocess.cpp.
    : discretization_(disc) {}
Member Function Documentation
Disposable< Array > QuantLib::StochasticProcess::apply (const Array & x0, const Array & dx) const [virtual]
applies a change to the asset value. By default, it returns \(\mathrm{x} + \Delta \mathrm{x} \).
Reimplemented in QuantLib::StochasticProcess1D, QuantLib::GJRGARCHProcess, QuantLib::LiborForwardModelProcess, QuantLib::HestonProcess, QuantLib::HybridHestonHullWhiteProcess, QuantLib::JointStochasticProcess, and QuantLib::StochasticProcessArray.
Definition at line 62 of file stochasticprocess.cpp.
Referenced by evolve(), and expectation().
{
        return x0 + dx;
    }
Disposable< Matrix > QuantLib::StochasticProcess::covariance (Time t0, const Array & x0, Time dt) const [virtual]
returns the covariance \(V(\mathrm{x}_{t_0 + \Delta t} | \mathrm{x}_{t_0} = \mathrm{x}_0) \) of the process after a time interval \(\Delta t \) according to the given discretization. This method can be overridden in derived classes which want to hard-code a particular discretization.
Reimplemented in QuantLib::StochasticProcess1D, QuantLib::G2ForwardProcess, QuantLib::LiborForwardModelProcess, QuantLib::JointStochasticProcess, QuantLib::StochasticProcessArray, and QuantLib::G2Process.
Definition at line 50 of file stochasticprocess.cpp.
References discretization_.
{
        return discretization_->covariance(*this, t0, x0, dt);
    }
virtual Disposable<Matrix> QuantLib::StochasticProcess::diffusion (Time t, const Array & x) const [pure virtual]
returns the diffusion part of the equation, i.e. \(\sigma(t, \mathrm{x}_t) \)
Implemented in QuantLib::StochasticProcess1D, QuantLib::GJRGARCHProcess, QuantLib::G2ForwardProcess, QuantLib::ExtOUWithJumpsProcess, QuantLib::KlugeExtOUProcess, QuantLib::LiborForwardModelProcess, QuantLib::HestonProcess, QuantLib::HybridHestonHullWhiteProcess, QuantLib::JointStochasticProcess, QuantLib::StochasticProcessArray, and QuantLib::G2Process.
Referenced by QuantLib::EndEulerDiscretization::covariance(), QuantLib::EulerDiscretization::covariance(), QuantLib::EulerDiscretization::diffusion(), and QuantLib::EndEulerDiscretization::diffusion().
virtual Disposable<Array> QuantLib::StochasticProcess::drift (Time t, const Array & x) const [pure virtual]
returns the drift part of the equation, i.e., \(\mu(t, \mathrm{x}_t) \)
Implemented in QuantLib::StochasticProcess1D, QuantLib::GJRGARCHProcess, QuantLib::G2ForwardProcess, QuantLib::ExtOUWithJumpsProcess, QuantLib::KlugeExtOUProcess, QuantLib::LiborForwardModelProcess, QuantLib::HestonProcess, QuantLib::BatesProcess, QuantLib::HybridHestonHullWhiteProcess, QuantLib::JointStochasticProcess, QuantLib::StochasticProcessArray, and QuantLib::G2Process.
Referenced by QuantLib::EndEulerDiscretization::drift(), and QuantLib::EulerDiscretization::drift().
Disposable< Array > QuantLib::StochasticProcess::evolve (Time t0, const Array & x0, Time dt, const Array & dw) const [virtual]
returns the asset value after a time interval \(\Delta t \) according to the given discretization. By default, it returns
\[ E(\mathrm{x}_0,t_0,\Delta t) + S(\mathrm{x}_0,t_0,\Delta t) \cdot \Delta \mathrm{w} \]
where \(E \) is the expectation and \(S \) the standard deviation.
Reimplemented in QuantLib::StochasticProcess1D, QuantLib::GJRGARCHProcess, QuantLib::ExtOUWithJumpsProcess, QuantLib::LiborForwardModelProcess, QuantLib::KlugeExtOUProcess, QuantLib::HestonProcess, QuantLib::BatesProcess, QuantLib::HybridHestonHullWhiteProcess, QuantLib::JointStochasticProcess, and QuantLib::StochasticProcessArray.
Definition at line 56 of file stochasticprocess.cpp.
References apply(), expectation(), and stdDeviation().
{
        return apply(expectation(t0,x0,dt), stdDeviation(t0,x0,dt)*dw);
    }
Disposable< Array > QuantLib::StochasticProcess::expectation (Time t0, const Array & x0, Time dt) const [virtual]
returns the expectation \(E(\mathrm{x}_{t_0 + \Delta t} | \mathrm{x}_{t_0} = \mathrm{x}_0) \) of the process after a time interval \(\Delta t \) according to the given discretization. This method can be overridden in derived classes which want to hard-code a particular discretization.
Reimplemented in QuantLib::StochasticProcess1D, QuantLib::G2ForwardProcess, QuantLib::JointStochasticProcess, QuantLib::StochasticProcessArray, and QuantLib::G2Process.
Definition at line 38 of file stochasticprocess.cpp.
References apply(), and discretization_.
Referenced by evolve().
{
        return apply(x0, discretization_->drift(*this, t0, x0, dt));
    }
Size QuantLib::StochasticProcess::factors () const [virtual]
returns the number of independent factors of the process
Reimplemented in QuantLib::LiborForwardModelProcess, QuantLib::ExtOUWithJumpsProcess, QuantLib::KlugeExtOUProcess, QuantLib::BatesProcess, and QuantLib::JointStochasticProcess.
Definition at line 34 of file stochasticprocess.cpp.
References size().
{
        return size();
    }
virtual Disposable<Array> QuantLib::StochasticProcess::initialValues () const [pure virtual]
returns the initial values of the state variables
Implemented in QuantLib::StochasticProcess1D, QuantLib::GJRGARCHProcess, QuantLib::G2ForwardProcess, QuantLib::ExtOUWithJumpsProcess, QuantLib::KlugeExtOUProcess, QuantLib::LiborForwardModelProcess, QuantLib::HestonProcess, QuantLib::HybridHestonHullWhiteProcess, QuantLib::JointStochasticProcess, QuantLib::StochasticProcessArray, and QuantLib::G2Process.
virtual Size QuantLib::StochasticProcess::size () const [pure virtual]
returns the number of dimensions of the stochastic process
Implemented in QuantLib::StochasticProcess1D, QuantLib::GJRGARCHProcess, QuantLib::LiborForwardModelProcess, QuantLib::G2ForwardProcess, QuantLib::ExtOUWithJumpsProcess, QuantLib::KlugeExtOUProcess, QuantLib::HestonProcess, QuantLib::HybridHestonHullWhiteProcess, QuantLib::StochasticProcessArray, QuantLib::JointStochasticProcess, and QuantLib::G2Process.
Referenced by factors().
Disposable< Matrix > QuantLib::StochasticProcess::stdDeviation (Time t0, const Array & x0, Time dt) const [virtual]
returns the standard deviation \(S(\mathrm{x}_{t_0 + \Delta t} | \mathrm{x}_{t_0} = \mathrm{x}_0) \) of the process after a time interval \(\Delta t \) according to the given discretization. This method can be overridden in derived classes which want to hard-code a particular discretization.
Reimplemented in QuantLib::StochasticProcess1D, QuantLib::G2ForwardProcess, QuantLib::JointStochasticProcess, QuantLib::StochasticProcessArray, and QuantLib::G2Process.
Definition at line 44 of file stochasticprocess.cpp.
References discretization_.
Referenced by evolve().
{
        return discretization_->diffusion(*this, t0, x0, dt);
    }
Time QuantLib::StochasticProcess::time (const Date &) const [virtual]
returns the time value corresponding to the given date in the reference system of the stochastic process.
Note:
As a number of processes might not need this functionality, a default implementation is given which raises an exception.
Reimplemented in QuantLib::GJRGARCHProcess, QuantLib::HestonProcess, QuantLib::GeneralizedBlackScholesProcess, QuantLib::JointStochasticProcess, QuantLib::HybridHestonHullWhiteProcess, QuantLib::Merton76Process, and QuantLib::StochasticProcessArray.
Definition at line 67 of file stochasticprocess.cpp.
References QL_FAIL.
Referenced by QuantLib::DiscretizedVanillaOption::DiscretizedVanillaOption().
{
        QL_FAIL("date/time conversion not supported");
    }
void QuantLib::StochasticProcess::update () [virtual]
This method must be implemented in derived classes. An instance of Observer does not call this method directly: instead, it will be called by the observables the instance registered with when they need to notify any changes.
Implements QuantLib::Observer.
Reimplemented in QuantLib::GeneralizedBlackScholesProcess, QuantLib::HybridHestonHullWhiteProcess, and QuantLib::JointStochasticProcess.
Definition at line 71 of file stochasticprocess.cpp.
References QuantLib::Observable::notifyObservers().
{
        notifyObservers();
    }
Member Data Documentation
boost::shared_ptr<discretization> QuantLib::StochasticProcess::discretization_ [protected]
Reimplemented in QuantLib::StochasticProcess1D, QuantLib::GJRGARCHProcess, QuantLib::HestonProcess, QuantLib::HybridHestonHullWhiteProcess, QuantLib::ExtendedOrnsteinUhlenbeckProcess, and QuantLib::ExtendedBlackScholesMertonProcess.
Definition at line 152 of file stochasticprocess.hpp.
Referenced by covariance(), expectation(), and stdDeviation().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/stochasticprocess.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/stochasticprocess.cpp