QuantLib: QuantLib::SwaptionVolCube1 Class Reference
QuantLib::SwaptionVolCube1 Class Reference
#include <swaptionvolcube1.hpp>
Classes
class Cube
Public Member Functions
SwaptionVolCube1 (const Handle< SwaptionVolatilityStructure > &atmVolStructure, const std::vector< Period > &optionTenors, const std::vector< Period > &swapTenors, const std::vector< Spread > &strikeSpreads, const std::vector< std::vector< Handle< Quote > > > &volSpreads, const boost::shared_ptr< SwapIndex > &swapIndexBase, const boost::shared_ptr< SwapIndex > &shortSwapIndexBase, bool vegaWeightedSmileFit, const std::vector< std::vector< Handle< Quote > > > &parametersGuess, const std::vector< bool > &isParameterFixed, bool isAtmCalibrated, const boost::shared_ptr< EndCriteria > &endCriteria=boost::shared_ptr< EndCriteria >(), Real maxErrorTolerance=Null< Real >(), const boost::shared_ptr< OptimizationMethod > &optMethod=boost::shared_ptr< OptimizationMethod >())
void sabrCalibrationSection (const Cube &marketVolCube, Cube &parametersCube, const Period &swapTenor) const
void recalibration (Real beta, const Period &swapTenor)
LazyObject interface
void performCalculations () const
SwaptionVolatilityCube interface
boost::shared_ptr< SmileSection > smileSectionImpl (Time optionTime, Time swapLength) const
Other inspectors
const Matrix & marketVolCube (Size i) const
Matrix sparseSabrParameters () const
Matrix denseSabrParameters () const
Matrix marketVolCube () const
Matrix volCubeAtmCalibrated () const
Protected Member Functions
void registerWithParametersGuess ()
boost::shared_ptr< SmileSection > smileSection (Time optionTime, Time swapLength, const Cube &sabrParametersCube) const
Cube sabrCalibration (const Cube &marketVolCube) const
void fillVolatilityCube () const
void createSparseSmiles () const
std::vector< Real > spreadVolInterpolation (const Date &atmOptionDate, const Period &atmSwapTenor) const
Private Attributes
Cube marketVolCube_
Cube volCubeAtmCalibrated_
Cube sparseParameters_
Cube denseParameters_
std::vector< std::vector
< boost::shared_ptr
< SmileSection > > > sparseSmiles_
std::vector< std::vector
< Handle< Quote > > > parametersGuessQuotes_
Cube parametersGuess_
std::vector< bool > isParameterFixed_
bool isAtmCalibrated_
const boost::shared_ptr
< EndCriteria > endCriteria_
Real maxErrorTolerance_
const boost::shared_ptr
< OptimizationMethod > optMethod_
Detailed Description
Definition at line 36 of file swaptionvolcube1.hpp.
Constructor & Destructor Documentation
QuantLib::SwaptionVolCube1::SwaptionVolCube1 (const Handle< SwaptionVolatilityStructure > & atmVolStructure, const std::vector< Period > & optionTenors, const std::vector< Period > & swapTenors, const std::vector< Spread > & strikeSpreads, const std::vector< std::vector< Handle< Quote > > > & volSpreads, const boost::shared_ptr< SwapIndex > & swapIndexBase, const boost::shared_ptr< SwapIndex > & shortSwapIndexBase, bool vegaWeightedSmileFit, const std::vector< std::vector< Handle< Quote > > > & parametersGuess, const std::vector< bool > & isParameterFixed, bool isAtmCalibrated, const boost::shared_ptr< EndCriteria > & endCriteria = boost::shared_ptr<EndCriteria>(), Real maxErrorTolerance = Null<Real>(), const boost::shared_ptr< OptimizationMethod > & optMethod = boost::shared_ptr<OptimizationMethod>())
Definition at line 40 of file swaptionvolcube1.cpp.
References maxErrorTolerance_, registerWithParametersGuess(), SWAPTIONVOLCUBE_TOL, SWAPTIONVOLCUBE_VEGAWEIGHTED_TOL, and QuantLib::SwaptionVolatilityCube::vegaWeightedSmileFit_.
    : SwaptionVolatilityCube(atmVolStructure, optionTenors, swapTenors,
                             strikeSpreads, volSpreads, swapIndexBase,
                             shortSwapIndexBase,
                             vegaWeightedSmileFit),
      parametersGuessQuotes_(parametersGuess),
      isParameterFixed_(isParameterFixed), isAtmCalibrated_(isAtmCalibrated),
      endCriteria_(endCriteria), optMethod_(optMethod)
    {
        if (maxErrorTolerance != Null<Rate>()) {
            maxErrorTolerance_ = maxErrorTolerance;
        } else{
            maxErrorTolerance_ = SWAPTIONVOLCUBE_VEGAWEIGHTED_TOL;
            if (vegaWeightedSmileFit_) maxErrorTolerance_ = SWAPTIONVOLCUBE_TOL;
        }
       registerWithParametersGuess();
    }
Member Function Documentation
void QuantLib::SwaptionVolCube1::createSparseSmiles () const [protected]
Definition at line 393 of file swaptionvolcube1.cpp.
References QuantLib::SwaptionVolatilityDiscrete::optionTimes(), QuantLib::SwaptionVolCube1::Cube::optionTimes(), smileSection(), sparseParameters_, sparseSmiles_, QuantLib::SwaptionVolatilityDiscrete::swapLengths(), and QuantLib::SwaptionVolCube1::Cube::swapLengths().
Referenced by fillVolatilityCube().
{
        std::vector<Time> optionTimes(sparseParameters_.optionTimes());
        std::vector<Time> swapLengths(sparseParameters_.swapLengths());
        sparseSmiles_.clear();
        for (Size j=0; j<optionTimes.size(); j++) {
            std::vector<boost::shared_ptr<SmileSection> > tmp;
            Size n = swapLengths.size();
            tmp.reserve(n);
            for (Size k=0; k<n; ++k) {
                tmp.push_back(smileSection(optionTimes[j], swapLengths[k],
                                           sparseParameters_));
            }
            sparseSmiles_.push_back(tmp);
        }
    }
Matrix QuantLib::SwaptionVolCube1::denseSabrParameters () const
Definition at line 557 of file swaptionvolcube1.cpp.
References QuantLib::SwaptionVolCube1::Cube::browse(), QuantLib::LazyObject::calculate(), and denseParameters_.
{
        calculate();
        return denseParameters_.browse();
    }
void QuantLib::SwaptionVolCube1::fillVolatilityCube () const [protected]
Definition at line 317 of file swaptionvolcube1.cpp.
References QuantLib::SwaptionVolatilityCube::atmStrike(), createSparseSmiles(), QuantLib::SwaptionVolatilityCube::nStrikes_, QuantLib::SwaptionVolatilityDiscrete::optionDates(), QuantLib::SwaptionVolCube1::Cube::optionDates(), QuantLib::SwaptionVolatilityDiscrete::optionTimes(), QuantLib::SwaptionVolCube1::Cube::optionTimes(), QuantLib::SwaptionVolCube1::Cube::setPoint(), spreadVolInterpolation(), QuantLib::SwaptionVolatilityDiscrete::swapLengths(), QuantLib::SwaptionVolCube1::Cube::swapLengths(), QuantLib::SwaptionVolatilityDiscrete::swapTenors(), QuantLib::SwaptionVolCube1::Cube::swapTenors(), QuantLib::SwaptionVolCube1::Cube::updateInterpolators(), and volCubeAtmCalibrated_.
Referenced by performCalculations(), and recalibration().
{
        const boost::shared_ptr<SwaptionVolatilityDiscrete> atmVolStructure =
            boost::dynamic_pointer_cast<SwaptionVolatilityDiscrete>(*atmVol_);
        std::vector<Time> atmOptionTimes(atmVolStructure->optionTimes());
        std::vector<Time> optionTimes(volCubeAtmCalibrated_.optionTimes());
        atmOptionTimes.insert(atmOptionTimes.end(),
                              optionTimes.begin(), optionTimes.end());
        std::sort(atmOptionTimes.begin(),atmOptionTimes.end());
        std::vector<Time>::iterator new_end =
            std::unique(atmOptionTimes.begin(), atmOptionTimes.end());
        atmOptionTimes.erase(new_end, atmOptionTimes.end());
        std::vector<Time> atmSwapLengths(atmVolStructure->swapLengths());
        std::vector<Time> swapLengths(volCubeAtmCalibrated_.swapLengths());
        atmSwapLengths.insert(atmSwapLengths.end(),
                              swapLengths.begin(), swapLengths.end());
        std::sort(atmSwapLengths.begin(),atmSwapLengths.end());
        new_end = std::unique(atmSwapLengths.begin(), atmSwapLengths.end());
        atmSwapLengths.erase(new_end, atmSwapLengths.end());
        std::vector<Date> atmOptionDates = atmVolStructure->optionDates();
        std::vector<Date> optionDates(volCubeAtmCalibrated_.optionDates());
        atmOptionDates.insert(atmOptionDates.end(),
                                optionDates.begin(), optionDates.end());
        std::sort(atmOptionDates.begin(),atmOptionDates.end());
        std::vector<Date>::iterator new_end_1 =
            std::unique(atmOptionDates.begin(), atmOptionDates.end());
        atmOptionDates.erase(new_end_1, atmOptionDates.end());
        std::vector<Period> atmSwapTenors = atmVolStructure->swapTenors();
        std::vector<Period> swapTenors(volCubeAtmCalibrated_.swapTenors());
        atmSwapTenors.insert(atmSwapTenors.end(),
                             swapTenors.begin(), swapTenors.end());
        std::sort(atmSwapTenors.begin(),atmSwapTenors.end());
        std::vector<Period>::iterator new_end_2 =
            std::unique(atmSwapTenors.begin(), atmSwapTenors.end());
        atmSwapTenors.erase(new_end_2, atmSwapTenors.end());
        createSparseSmiles();
        for (Size j=0; j<atmOptionTimes.size(); j++) {
            for (Size k=0; k<atmSwapLengths.size(); k++) {
                bool expandOptionTimes =
                    !(std::binary_search(optionTimes.begin(),
                                         optionTimes.end(),
                                         atmOptionTimes[j]));
                bool expandSwapLengths =
                    !(std::binary_search(swapLengths.begin(),
                                         swapLengths.end(),
                                         atmSwapLengths[k]));
                if(expandOptionTimes || expandSwapLengths){
                    Rate atmForward = atmStrike(atmOptionDates[j],
                                                atmSwapTenors[k]);
                    Volatility atmVol = atmVol_->volatility(
                        atmOptionDates[j], atmSwapTenors[k], atmForward);
                    std::vector<Real> spreadVols =
                        spreadVolInterpolation(atmOptionDates[j],
                                               atmSwapTenors[k]);
                    std::vector<Real> volAtmCalibrated;
                    volAtmCalibrated.reserve(nStrikes_);
                    for (Size i=0; i<nStrikes_; i++)
                        volAtmCalibrated.push_back(atmVol + spreadVols[i]);
                    volCubeAtmCalibrated_.setPoint(
                                    atmOptionDates[j], atmSwapTenors[k],
                                    atmOptionTimes[j], atmSwapLengths[k],
                                    volAtmCalibrated);
                }
            }
        }
        volCubeAtmCalibrated_.updateInterpolators();
    }
const Matrix& QuantLib::SwaptionVolCube1::marketVolCube (Size i) const [inline]
Definition at line 118 of file swaptionvolcube1.hpp.
References marketVolCube_, and QuantLib::SwaptionVolCube1::Cube::points().
{
            return marketVolCube_.points()[i];
        }
Matrix QuantLib::SwaptionVolCube1::marketVolCube () const
Definition at line 562 of file swaptionvolcube1.cpp.
References QuantLib::SwaptionVolCube1::Cube::browse(), QuantLib::LazyObject::calculate(), and marketVolCube_.
{
        calculate();
        return marketVolCube_.browse();
    }
void QuantLib::SwaptionVolCube1::performCalculations () const [virtual]
This method must implement any calculations which must be (re)done in order to calculate the desired results.
set parametersGuess_ by parametersGuessQuotes_
set marketVolCube_ by volSpreads_ quotes
Reimplemented from QuantLib::SwaptionVolatilityDiscrete.
Definition at line 80 of file swaptionvolcube1.cpp.
References QuantLib::SwaptionVolatilityCube::atmStrike(), QuantLib::SwaptionVolatilityCube::atmVol_, denseParameters_, fillVolatilityCube(), isAtmCalibrated_, marketVolCube_, QuantLib::SwaptionVolatilityDiscrete::nOptionTenors_, QuantLib::SwaptionVolatilityCube::nStrikes_, QuantLib::SwaptionVolatilityDiscrete::nSwapTenors_, QuantLib::SwaptionVolatilityDiscrete::optionDates_, QuantLib::SwaptionVolatilityDiscrete::optionTimes_, parametersGuess_, parametersGuessQuotes_, sabrCalibration(), QuantLib::SwaptionVolCube1::Cube::setElement(), sparseParameters_, QuantLib::SwaptionVolatilityDiscrete::swapLengths_, QuantLib::SwaptionVolatilityDiscrete::swapTenors_, QuantLib::SwaptionVolCube1::Cube::updateInterpolators(), volCubeAtmCalibrated_, and QuantLib::SwaptionVolatilityCube::volSpreads_.
{
        SwaptionVolatilityDiscrete::performCalculations();
        parametersGuess_ = Cube(optionDates_, swapTenors_,
                                optionTimes_, swapLengths_, 4);
        Size i;
        for (i=0; i<4; i++)
            for (Size j=0; j<nOptionTenors_ ; j++)
                for (Size k=0; k<nSwapTenors_; k++) {
                    parametersGuess_.setElement(i, j, k,
                        parametersGuessQuotes_[j+k*nOptionTenors_][i]->value());
                }
        parametersGuess_.updateInterpolators();
        marketVolCube_ = Cube(optionDates_, swapTenors_,
                              optionTimes_, swapLengths_, nStrikes_);
        Rate atmForward;
        Volatility atmVol, vol;
        for (Size j=0; j<nOptionTenors_; ++j) {
            for (Size k=0; k<nSwapTenors_; ++k) {
                atmForward = atmStrike(optionDates_[j], swapTenors_[k]);
                atmVol = atmVol_->volatility(optionDates_[j], swapTenors_[k],
                                                              atmForward);
                for (Size i=0; i<nStrikes_; ++i) {
                    vol = atmVol + volSpreads_[j*nSwapTenors_+k][i]->value();
                    marketVolCube_.setElement(i, j, k, vol);
                }
            }
        }
        marketVolCube_.updateInterpolators();
        sparseParameters_ = sabrCalibration(marketVolCube_);
        //parametersGuess_ = sparseParameters_;
        sparseParameters_.updateInterpolators();
        //parametersGuess_.updateInterpolators();
        volCubeAtmCalibrated_= marketVolCube_;
        if(isAtmCalibrated_){
            fillVolatilityCube();
            denseParameters_ = sabrCalibration(volCubeAtmCalibrated_);
            denseParameters_.updateInterpolators();
        }
    }
void QuantLib::SwaptionVolCube1::recalibration (Real beta, const Period & swapTenor)
Definition at line 571 of file swaptionvolcube1.cpp.
References denseParameters_, fillVolatilityCube(), isAtmCalibrated_, marketVolCube_, QuantLib::SwaptionVolatilityDiscrete::nOptionTenors_, QuantLib::SwaptionVolatilityDiscrete::nSwapTenors_, parametersGuess_, sabrCalibrationSection(), QuantLib::SwaptionVolCube1::Cube::setLayer(), sparseParameters_, QuantLib::SwaptionVolCube1::Cube::updateInterpolators(), and volCubeAtmCalibrated_.
Referenced by anonymous_namespace{cmsmarketcalibration.cpp}::ObjectiveFunction::updateVolatilityCubeAndCmsMarket(), and anonymous_namespace{cmsmarketcalibration.cpp}::ObjectiveFunction2::updateVolatilityCubeAndCmsMarket().
{
        Matrix newBetaGuess(nOptionTenors_, nSwapTenors_, beta);
        parametersGuess_.setLayer(1, newBetaGuess);
        parametersGuess_.updateInterpolators();
        sabrCalibrationSection(marketVolCube_,sparseParameters_,swapTenor);
        if(isAtmCalibrated_){
            fillVolatilityCube();
            sabrCalibrationSection(volCubeAtmCalibrated_,denseParameters_,swapTenor);
        }
    }
void QuantLib::SwaptionVolCube1::registerWithParametersGuess () [protected]
Definition at line 72 of file swaptionvolcube1.cpp.
References QuantLib::SwaptionVolatilityDiscrete::nOptionTenors_, QuantLib::SwaptionVolatilityDiscrete::nSwapTenors_, parametersGuessQuotes_, and QuantLib::Observer::registerWith().
Referenced by SwaptionVolCube1().
    {
        for (Size i=0; i<4; i++)
            for (Size j=0; j<nOptionTenors_; j++)
                for (Size k=0; k<nSwapTenors_; k++)
                    registerWith(parametersGuessQuotes_[j+k*nOptionTenors_][i]);
    }
SwaptionVolCube1::Cube QuantLib::SwaptionVolCube1::sabrCalibration (const Cube & marketVolCube) const [protected]
Definition at line 128 of file swaptionvolcube1.cpp.
References QuantLib::SwaptionVolatilityCube::atmStrike(), endCriteria_, isParameterFixed_, maxErrorTolerance_, QuantLib::EndCriteria::MaxIterations, QuantLib::SwaptionVolatilityCube::nStrikes_, QuantLib::SwaptionVolatilityDiscrete::optionDates(), QuantLib::SwaptionVolCube1::Cube::optionDates(), QuantLib::SwaptionVolatilityDiscrete::optionTimes(), QuantLib::SwaptionVolCube1::Cube::optionTimes(), optMethod_, parametersGuess_, QuantLib::SwaptionVolCube1::Cube::points(), QL_ENSURE, QuantLib::io::rate(), QuantLib::SwaptionVolCube1::Cube::setLayer(), QuantLib::SwaptionVolatilityCube::strikeSpreads_, QuantLib::SwaptionVolatilityDiscrete::swapLengths(), QuantLib::SwaptionVolCube1::Cube::swapLengths(), QuantLib::SwaptionVolatilityDiscrete::swapTenors(), QuantLib::SwaptionVolCube1::Cube::swapTenors(), QuantLib::SwaptionVolatilityCube::vegaWeightedSmileFit_, and anonymous_namespace{marketmodel.cpp}::volatilities.
Referenced by performCalculations().
{
        const std::vector<Time>& optionTimes = marketVolCube.optionTimes();
        const std::vector<Time>& swapLengths = marketVolCube.swapLengths();
        const std::vector<Date>& optionDates = marketVolCube.optionDates();
        const std::vector<Period>& swapTenors = marketVolCube.swapTenors();
        Matrix alphas(optionTimes.size(), swapLengths.size(),0.);
        Matrix betas(alphas);
        Matrix nus(alphas);
        Matrix rhos(alphas);
        Matrix forwards(alphas);
        Matrix errors(alphas);
        Matrix maxErrors(alphas);
        Matrix endCriteria(alphas);
        const std::vector<Matrix>& tmpMarketVolCube = marketVolCube.points();
        std::vector<Real> strikes(strikeSpreads_.size());
        std::vector<Real> volatilities(strikeSpreads_.size());
        for (Size j=0; j<optionTimes.size(); j++) {
            for (Size k=0; k<swapLengths.size(); k++) {
                Rate atmForward = atmStrike(optionDates[j], swapTenors[k]);
                for (Size i=0; i<nStrikes_; i++){
                    strikes[i] = atmForward+strikeSpreads_[i];
                    volatilities[i] = tmpMarketVolCube[i][j][k];
                }
                const std::vector<Real>& guess = parametersGuess_.operator()(
                    optionTimes[j], swapLengths[k]);
                const boost::shared_ptr<SABRInterpolation> sabrInterpolation =
                    boost::shared_ptr<SABRInterpolation>(new
                        SABRInterpolation(strikes.begin(), strikes.end(),
                                          volatilities.begin(),
                                          optionTimes[j], atmForward,
                                          guess[0], guess[1],
                                          guess[2], guess[3],
                                          isParameterFixed_[0],
                                          isParameterFixed_[1],
                                          isParameterFixed_[2],
                                          isParameterFixed_[3],
                                          vegaWeightedSmileFit_,
                                          endCriteria_,
                                          optMethod_));
                sabrInterpolation->update();
                Real rmsError = sabrInterpolation->rmsError();
                Real maxError = sabrInterpolation->maxError();
                alphas     [j][k] = sabrInterpolation->alpha();
                betas      [j][k] = sabrInterpolation->beta();
                nus        [j][k] = sabrInterpolation->nu();
                rhos       [j][k] = sabrInterpolation->rho();
                forwards   [j][k] = atmForward;
                errors     [j][k] = rmsError;
                maxErrors  [j][k] = maxError;
                endCriteria[j][k] = sabrInterpolation->endCriteria();
                QL_ENSURE(endCriteria[j][k]!=EndCriteria::MaxIterations,
                          "global swaptions calibration failed: "
                          "MaxIterations reached: " << "\n" <<
                          "option maturity = " << optionDates[j] << ", \n" <<
                          "swap tenor = " << swapTenors[k] << ", \n" <<
                          "error = " << io::rate(errors[j][k])  << ", \n" <<
                          "max error = " << io::rate(maxErrors[j][k]) << ", \n" <<
                          "   alpha = " <<  alphas[j][k] << "n" <<
                          "   beta = " <<  betas[j][k] << "\n" <<
                          "   nu = " <<  nus[j][k]   << "\n" <<
                          "   rho = " <<  rhos[j][k]  << "\n"
                          );
                QL_ENSURE(maxErrors[j][k]<maxErrorTolerance_,
                          "global swaptions calibration failed: "
                          "maxErrorTolerance = " << io::rate(maxErrorTolerance_)
                          << " exceeded " << "\n" <<
                          "option maturity = " << optionDates[j] << ", \n" <<
                          "swap tenor = " << swapTenors[k] << "\n" <<
                          "error = " << io::rate(errors[j][k])  << ", \n" <<
                          "max error = " << io::rate(maxErrors[j][k]) << ", \n" <<
                          "   alpha = " << alphas[j][k]<< "\n" <<
                          "   beta = " << betas[j][k] << "\n" <<
                          "   nu = " << nus[j][k]   << "\n" <<
                          "   rho = " << rhos[j][k]
                          );
            }
        }
        Cube sabrParametersCube(optionDates, swapTenors,
                                optionTimes, swapLengths, 8);
        sabrParametersCube.setLayer(0, alphas);
        sabrParametersCube.setLayer(1, betas);
        sabrParametersCube.setLayer(2, nus);
        sabrParametersCube.setLayer(3, rhos);
        sabrParametersCube.setLayer(4, forwards);
        sabrParametersCube.setLayer(5, errors);
        sabrParametersCube.setLayer(6, maxErrors);
        sabrParametersCube.setLayer(7, endCriteria);
        return sabrParametersCube;
    }
void QuantLib::SwaptionVolCube1::sabrCalibrationSection (const Cube & marketVolCube, Cube & parametersCube, const Period & swapTenor) const
Definition at line 228 of file swaptionvolcube1.cpp.
References QuantLib::SwaptionVolatilityCube::atmStrike(), endCriteria_, isParameterFixed_, maxErrorTolerance_, QuantLib::EndCriteria::MaxIterations, QuantLib::SwaptionVolatilityCube::nStrikes_, QuantLib::SwaptionVolatilityDiscrete::optionDates(), QuantLib::SwaptionVolCube1::Cube::optionDates(), QuantLib::SwaptionVolatilityDiscrete::optionTimes(), QuantLib::SwaptionVolCube1::Cube::optionTimes(), optMethod_, parametersGuess_, QuantLib::SwaptionVolCube1::Cube::points(), QL_ENSURE, QL_REQUIRE, QuantLib::SwaptionVolCube1::Cube::setPoint(), QuantLib::SwaptionVolatilityCube::strikeSpreads_, QuantLib::SwaptionVolatilityDiscrete::swapLengths(), QuantLib::SwaptionVolCube1::Cube::swapLengths(), QuantLib::SwaptionVolatilityDiscrete::swapTenors(), QuantLib::SwaptionVolCube1::Cube::swapTenors(), QuantLib::SwaptionVolCube1::Cube::updateInterpolators(), QuantLib::SwaptionVolatilityCube::vegaWeightedSmileFit_, and anonymous_namespace{marketmodel.cpp}::volatilities.
Referenced by recalibration().
{
        const std::vector<Time>& optionTimes = marketVolCube.optionTimes();
        const std::vector<Time>& swapLengths = marketVolCube.swapLengths();
        const std::vector<Date>& optionDates = marketVolCube.optionDates();
        const std::vector<Period>& swapTenors = marketVolCube.swapTenors();
        Size k = std::find(swapTenors.begin(), swapTenors.end(),
                           swapTenor) - swapTenors.begin();
        QL_REQUIRE(k != swapTenors.size(), "swap tenor not found");
        std::vector<Real> calibrationResult(8,0.);
        const std::vector<Matrix>& tmpMarketVolCube = marketVolCube.points();
        std::vector<Real> strikes(strikeSpreads_.size());
        std::vector<Real> volatilities(strikeSpreads_.size());
        for (Size j=0; j<optionTimes.size(); j++) {
            Rate atmForward = atmStrike(optionDates[j], swapTenors[k]);
            for (Size i=0; i<nStrikes_; i++){
                strikes[i] = atmForward+strikeSpreads_[i];
                volatilities[i] = tmpMarketVolCube[i][j][k];
            }
            const std::vector<Real>& guess = parametersGuess_.operator()(
                optionTimes[j], swapLengths[k]);
            const boost::shared_ptr<SABRInterpolation> sabrInterpolation =
                boost::shared_ptr<SABRInterpolation>(new
                    SABRInterpolation(strikes.begin(), strikes.end(),
                                      volatilities.begin(),
                                      optionTimes[j], atmForward,
                                      guess[0], guess[1],
                                      guess[2], guess[3],
                                      isParameterFixed_[0],
                                      isParameterFixed_[1],
                                      isParameterFixed_[2],
                                      isParameterFixed_[3],
                                      vegaWeightedSmileFit_,
                                      endCriteria_,
                                      optMethod_));
            sabrInterpolation->update();
            Real interpolationError = sabrInterpolation->rmsError();
            calibrationResult[0]=sabrInterpolation->alpha();
            calibrationResult[1]=sabrInterpolation->beta();
            calibrationResult[2]=sabrInterpolation->nu();
            calibrationResult[3]=sabrInterpolation->rho();
            calibrationResult[4]=atmForward;
            calibrationResult[5]=interpolationError;
            calibrationResult[6]=sabrInterpolation->maxError();
            calibrationResult[7]=sabrInterpolation->endCriteria();
            QL_ENSURE(calibrationResult[7]!=EndCriteria::MaxIterations,
                      "section calibration failed: "
                      "option tenor " << optionDates[j] <<
                      ", swap tenor " << swapTenors[k] <<
                      ": max iteration (" <<
                      endCriteria_->maxIterations() << ")" <<
                          ", alpha " <<  calibrationResult[0]<<
                          ", beta "  <<  calibrationResult[1] <<
                          ", nu "    <<  calibrationResult[2]   <<
                          ", rho "   <<  calibrationResult[3]  <<
                          ", error " <<  calibrationResult[5]
                          );
            QL_ENSURE(calibrationResult[6]< maxErrorTolerance_,
                      "section calibration failed: "
                      "option tenor " << optionDates[j] <<
                      ", swap tenor " << swapTenors[k] <<
                      ": max error " << calibrationResult[6]  <<
                          ", alpha " <<  calibrationResult[0] <<
                          ", beta "  <<  calibrationResult[1] <<
                          ", nu "    <<  calibrationResult[2] <<
                          ", rho "   <<  calibrationResult[3] <<
                          ", error " <<  calibrationResult[5]
                          );
            parametersCube.setPoint(optionDates[j], swapTenors[k],
                                    optionTimes[j], swapLengths[k],
                                    calibrationResult);
            parametersCube.updateInterpolators();
        }
    }
boost::shared_ptr< SmileSection > QuantLib::SwaptionVolCube1::smileSection (Time optionTime, Time swapLength, const Cube & sabrParametersCube) const [protected]
Definition at line 533 of file swaptionvolcube1.cpp.
References QuantLib::LazyObject::calculate().
Referenced by createSparseSmiles(), and smileSectionImpl().
{
        calculate();
        const std::vector<Real> sabrParameters =
            sabrParametersCube(optionTime, swapLength);
        return boost::shared_ptr<SmileSection>(new
            SabrSmileSection(optionTime, sabrParameters[4], sabrParameters));
    }
boost::shared_ptr< SmileSection > QuantLib::SwaptionVolCube1::smileSectionImpl (Time optionTime, Time swapLength) const [virtual]
Implements QuantLib::SwaptionVolatilityStructure.
Definition at line 544 of file swaptionvolcube1.cpp.
References denseParameters_, isAtmCalibrated_, smileSection(), and sparseParameters_.
{
        if (isAtmCalibrated_)
            return smileSection(optionTime, swapLength, denseParameters_);
        else
            return smileSection(optionTime, swapLength, sparseParameters_);
    }
Matrix QuantLib::SwaptionVolCube1::sparseSabrParameters () const
Definition at line 552 of file swaptionvolcube1.cpp.
References QuantLib::SwaptionVolCube1::Cube::browse(), QuantLib::LazyObject::calculate(), and sparseParameters_.
{
        calculate();
        return sparseParameters_.browse();
    }
std::vector< Real > QuantLib::SwaptionVolCube1::spreadVolInterpolation (const Date & atmOptionDate, const Period & atmSwapTenor) const [protected]
Definition at line 412 of file swaptionvolcube1.cpp.
References QuantLib::SwaptionVolatilityCube::atmStrike(), QuantLib::SwaptionVolatilityCube::atmVol_, QuantLib::SwaptionVolatilityCube::nStrikes_, QuantLib::SwaptionVolatilityDiscrete::optionDates(), QuantLib::SwaptionVolCube1::Cube::optionDates(), QuantLib::SwaptionVolatilityDiscrete::optionTimes(), QuantLib::SwaptionVolCube1::Cube::optionTimes(), QL_REQUIRE, QuantLib::SwaptionVolCube1::Cube::setLayer(), sparseParameters_, sparseSmiles_, QuantLib::SwaptionVolatilityCube::strikeSpreads_, QuantLib::SwaptionVolatilityStructure::swapLength(), QuantLib::SwaptionVolatilityDiscrete::swapLengths(), QuantLib::SwaptionVolCube1::Cube::swapLengths(), QuantLib::SwaptionVolatilityDiscrete::swapTenors(), QuantLib::SwaptionVolCube1::Cube::swapTenors(), QuantLib::TermStructure::timeFromReference(), and QuantLib::SwaptionVolCube1::Cube::updateInterpolators().
Referenced by fillVolatilityCube().
{
        Time atmOptionTime = timeFromReference(atmOptionDate);
        Time atmTimeLength = swapLength(atmSwapTenor);
        std::vector<Real> result;
        const std::vector<Time>& optionTimes(sparseParameters_.optionTimes());
        const std::vector<Time>& swapLengths(sparseParameters_.swapLengths());
        const std::vector<Date>& optionDates =
            sparseParameters_.optionDates();
        const std::vector<Period>& swapTenors = sparseParameters_.swapTenors();
        std::vector<Real>::const_iterator optionTimesPreviousNode,
                                          swapLengthsPreviousNode;
        optionTimesPreviousNode = std::lower_bound(optionTimes.begin(),
                                                   optionTimes.end(),
                                                   atmOptionTime);
        Size optionTimesPreviousIndex =
            optionTimesPreviousNode - optionTimes.begin();
        if (optionTimesPreviousIndex >0)
            optionTimesPreviousIndex --;
        swapLengthsPreviousNode = std::lower_bound(swapLengths.begin(),
                                                   swapLengths.end(),
                                                   atmTimeLength);
        Size swapLengthsPreviousIndex = swapLengthsPreviousNode - swapLengths.begin();
        if (swapLengthsPreviousIndex >0)
            swapLengthsPreviousIndex --;
        std::vector< std::vector<boost::shared_ptr<SmileSection> > > smiles;
        std::vector<boost::shared_ptr<SmileSection> >  smilesOnPreviousExpiry;
        std::vector<boost::shared_ptr<SmileSection> >  smilesOnNextExpiry;
        QL_REQUIRE(optionTimesPreviousIndex+1 < sparseSmiles_.size(),
                   "optionTimesPreviousIndex+1 >= sparseSmiles_.size()");
        QL_REQUIRE(swapLengthsPreviousIndex+1 < sparseSmiles_[0].size(),
                   "swapLengthsPreviousIndex+1 >= sparseSmiles_[0].size()");
        smilesOnPreviousExpiry.push_back(
              sparseSmiles_[optionTimesPreviousIndex][swapLengthsPreviousIndex]);
        smilesOnPreviousExpiry.push_back(
              sparseSmiles_[optionTimesPreviousIndex][swapLengthsPreviousIndex+1]);
        smilesOnNextExpiry.push_back(
              sparseSmiles_[optionTimesPreviousIndex+1][swapLengthsPreviousIndex]);
        smilesOnNextExpiry.push_back(
              sparseSmiles_[optionTimesPreviousIndex+1][swapLengthsPreviousIndex+1]);
        smiles.push_back(smilesOnPreviousExpiry);
        smiles.push_back(smilesOnNextExpiry);
        std::vector<Real> optionsNodes(2);
        optionsNodes[0] = optionTimes[optionTimesPreviousIndex];
        optionsNodes[1] = optionTimes[optionTimesPreviousIndex+1];
        std::vector<Date> optionsDateNodes(2);
        optionsDateNodes[0] = optionDates[optionTimesPreviousIndex];
        optionsDateNodes[1] = optionDates[optionTimesPreviousIndex+1];
        std::vector<Real> swapLengthsNodes(2);
        swapLengthsNodes[0] = swapLengths[swapLengthsPreviousIndex];
        swapLengthsNodes[1] = swapLengths[swapLengthsPreviousIndex+1];
        std::vector<Period> swapTenorNodes(2);
        swapTenorNodes[0] = swapTenors[swapLengthsPreviousIndex];
        swapTenorNodes[1] = swapTenors[swapLengthsPreviousIndex+1];
        Rate atmForward = atmStrike(atmOptionDate, atmSwapTenor);
        Matrix atmForwards(2, 2, 0.0);
        Matrix atmVols(2, 2, 0.0);
        for (Size i=0; i<2; i++) {
            for (Size j=0; j<2; j++) {
                atmForwards[i][j] = atmStrike(optionsDateNodes[i],
                                              swapTenorNodes[j]);
                // atmVols[i][j] = smiles[i][j]->volatility(atmForwards[i][j]);
                atmVols[i][j] = atmVol_->volatility(
                    optionsDateNodes[i], swapTenorNodes[j], atmForwards[i][j]);
                /* With the old implementation the interpolated spreads on ATM
                   volatilities were null even if the spreads on ATM volatilities to be
                   interpolated were non-zero. The new implementation removes
                   this behaviour, but introduces a small ERROR in the cube:
                   even if no spreads are applied on any cube ATM volatility corresponding
                   to quoted smile sections (that is ATM volatilities in sparse cube), the
                   cube ATM volatilities corresponding to not quoted smile sections (that
                   is ATM volatilities in dense cube) are no more exactly the quoted values,
                   but that ones PLUS the linear interpolation of the fit errors on the ATM
                   volatilities in sparse cube whose spreads are used in the calculation.
                   A similar imprecision is introduced to the volatilities in dense cube
                   whith moneyness near to 1.
                   (See below how spreadVols are calculated).
                   The extent of this error depends on the quality of the fit: in case of
                   good fits it is negligibile.
                */
            }
        }
        for (Size k=0; k<nStrikes_; k++){
            const Real strike = atmForward + strikeSpreads_[k];
            const Real moneyness = atmForward/strike;
            Matrix strikes(2,2,0.);
            Matrix spreadVols(2,2,0.);
            for (Size i=0; i<2; i++){
                for (Size j=0; j<2; j++){
                    strikes[i][j] = atmForwards[i][j]/moneyness;
                    spreadVols[i][j] =
                        smiles[i][j]->volatility(strikes[i][j]) - atmVols[i][j];
                }
            }
           Cube localInterpolator(optionsDateNodes, swapTenorNodes,
                                  optionsNodes, swapLengthsNodes, 1);
           localInterpolator.setLayer(0, spreadVols);
           localInterpolator.updateInterpolators();
           result.push_back(localInterpolator(atmOptionTime, atmTimeLength)[0]);
        }
        return result;
    }
Matrix QuantLib::SwaptionVolCube1::volCubeAtmCalibrated () const
Definition at line 566 of file swaptionvolcube1.cpp.
References QuantLib::SwaptionVolCube1::Cube::browse(), QuantLib::LazyObject::calculate(), and volCubeAtmCalibrated_.
{
        calculate();
        return volCubeAtmCalibrated_.browse();
    }
Member Data Documentation
Cube QuantLib::SwaptionVolCube1::denseParameters_ [mutable, private]
Definition at line 146 of file swaptionvolcube1.hpp.
Referenced by denseSabrParameters(), performCalculations(), recalibration(), and smileSectionImpl().
const boost::shared_ptr<EndCriteria> QuantLib::SwaptionVolCube1::endCriteria_ [private]
Definition at line 153 of file swaptionvolcube1.hpp.
Referenced by sabrCalibration(), and sabrCalibrationSection().
bool QuantLib::SwaptionVolCube1::isAtmCalibrated_ [private]
Definition at line 152 of file swaptionvolcube1.hpp.
Referenced by performCalculations(), recalibration(), and smileSectionImpl().
std::vector<bool> QuantLib::SwaptionVolCube1::isParameterFixed_ [private]
Definition at line 151 of file swaptionvolcube1.hpp.
Referenced by sabrCalibration(), and sabrCalibrationSection().
Cube QuantLib::SwaptionVolCube1::marketVolCube_ [mutable, private]
Definition at line 143 of file swaptionvolcube1.hpp.
Referenced by marketVolCube(), performCalculations(), and recalibration().
Real QuantLib::SwaptionVolCube1::maxErrorTolerance_ [private]
Definition at line 154 of file swaptionvolcube1.hpp.
Referenced by sabrCalibration(), sabrCalibrationSection(), and SwaptionVolCube1().
const boost::shared_ptr<OptimizationMethod> QuantLib::SwaptionVolCube1::optMethod_ [private]
Definition at line 155 of file swaptionvolcube1.hpp.
Referenced by sabrCalibration(), and sabrCalibrationSection().
Cube QuantLib::SwaptionVolCube1::parametersGuess_ [mutable, private]
Definition at line 150 of file swaptionvolcube1.hpp.
Referenced by performCalculations(), recalibration(), sabrCalibration(), and sabrCalibrationSection().
std::vector<std::vector<Handle<Quote> > > QuantLib::SwaptionVolCube1::parametersGuessQuotes_ [private]
Definition at line 149 of file swaptionvolcube1.hpp.
Referenced by performCalculations(), and registerWithParametersGuess().
Cube QuantLib::SwaptionVolCube1::sparseParameters_ [mutable, private]
Definition at line 145 of file swaptionvolcube1.hpp.
Referenced by createSparseSmiles(), performCalculations(), recalibration(), smileSectionImpl(), sparseSabrParameters(), and spreadVolInterpolation().
std::vector< std::vector<boost::shared_ptr<SmileSection> > > QuantLib::SwaptionVolCube1::sparseSmiles_ [mutable, private]
Definition at line 148 of file swaptionvolcube1.hpp.
Referenced by createSparseSmiles(), and spreadVolInterpolation().
Cube QuantLib::SwaptionVolCube1::volCubeAtmCalibrated_ [mutable, private]
Definition at line 144 of file swaptionvolcube1.hpp.
Referenced by fillVolatilityCube(), performCalculations(), recalibration(), and volCubeAtmCalibrated().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/swaption/swaptionvolcube1.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/swaption/swaptionvolcube1.cpp