QuantLib: QuantLib::CotSwapFromFwdCorrelation Class Reference
QuantLib::CotSwapFromFwdCorrelation Class Reference
#include <cotswapfromfwdcorrelation.hpp>
Public Member Functions
CotSwapFromFwdCorrelation (const boost::shared_ptr< PiecewiseConstantCorrelation > &fwdCorr, const CurveState &curveState, Spread displacement)
const std::vector< Time > & times () const
const std::vector< Time > & rateTimes () const
const std::vector< Matrix > & correlations () const
Size numberOfRates () const
Private Attributes
boost::shared_ptr
< PiecewiseConstantCorrelation > fwdCorr_
Size numberOfRates_
std::vector< Matrix > swapCorrMatrices_
Detailed Description
Definition at line 31 of file cotswapfromfwdcorrelation.hpp.
Constructor & Destructor Documentation
QuantLib::CotSwapFromFwdCorrelation::CotSwapFromFwdCorrelation (const boost::shared_ptr< PiecewiseConstantCorrelation > & fwdCorr, const CurveState & curveState, Spread displacement)
Definition at line 30 of file cotswapfromfwdcorrelation.cpp.
References QuantLib::CovarianceDecomposition::correlationMatrix(), QuantLib::SwapForwardMappings::coterminalSwapZedMatrix(), fwdCorr_, QuantLib::CurveState::numberOfRates(), numberOfRates_, QL_REQUIRE, rateTimes(), QuantLib::CurveState::rateTimes(), swapCorrMatrices_, and QuantLib::transpose().
    : fwdCorr_(fwdCorr),
      numberOfRates_(fwdCorr->numberOfRates()),
      swapCorrMatrices_(fwdCorr->correlations().size())
    {
        QL_REQUIRE(numberOfRates_==curveState.numberOfRates(),
                   "mismatch between number of rates in fwdCorr (" <<
                   numberOfRates_ << ") and curveState (" <<
                   curveState.numberOfRates() << ")");
        Matrix zed = SwapForwardMappings::coterminalSwapZedMatrix(
                                                curveState, displacement);
        Matrix zedT = transpose(zed);
        const std::vector<Matrix>& fwdCorrMatrices = fwdCorr->correlations();
        for (Size k = 0; k<fwdCorrMatrices.size(); ++k) {
            swapCorrMatrices_[k] = CovarianceDecomposition(
                zed * fwdCorrMatrices[k] * zedT).correlationMatrix();
            // zero expired rates' correlation coefficients
            const std::vector<Time>& rateTimes = curveState.rateTimes();
            const std::vector<Time>& corrTimes = fwdCorr_->times();
            for (Size i=0; i<numberOfRates_; ++i)
                for (Size j=0; j<=i; ++j)
                    if (corrTimes[k]>rateTimes[j])
                        swapCorrMatrices_[k][i][j] =
                            swapCorrMatrices_[k][j][i] = 0.0;
        }
    }
Member Function Documentation
const std::vector< Matrix > & QuantLib::CotSwapFromFwdCorrelation::correlations () const [virtual]
Implements QuantLib::PiecewiseConstantCorrelation.
Definition at line 74 of file cotswapfromfwdcorrelation.cpp.
References swapCorrMatrices_.
{
        return swapCorrMatrices_;
    }
Size QuantLib::CotSwapFromFwdCorrelation::numberOfRates () const [virtual]
Implements QuantLib::PiecewiseConstantCorrelation.
Definition at line 69 of file cotswapfromfwdcorrelation.cpp.
References numberOfRates_.
{
        return numberOfRates_;
    }
const std::vector< Time > & QuantLib::CotSwapFromFwdCorrelation::rateTimes () const [virtual]
Implements QuantLib::PiecewiseConstantCorrelation.
Definition at line 65 of file cotswapfromfwdcorrelation.cpp.
References fwdCorr_.
Referenced by CotSwapFromFwdCorrelation().
{
        return fwdCorr_->rateTimes();
    }
const std::vector< Time > & QuantLib::CotSwapFromFwdCorrelation::times () const [virtual]
Implements QuantLib::PiecewiseConstantCorrelation.
Definition at line 61 of file cotswapfromfwdcorrelation.cpp.
References fwdCorr_.
{
        return fwdCorr_->times();
    }
Member Data Documentation
boost::shared_ptr<PiecewiseConstantCorrelation> QuantLib::CotSwapFromFwdCorrelation::fwdCorr_ [private]
Definition at line 42 of file cotswapfromfwdcorrelation.hpp.
Referenced by CotSwapFromFwdCorrelation(), rateTimes(), and times().
Size QuantLib::CotSwapFromFwdCorrelation::numberOfRates_ [private]
Definition at line 43 of file cotswapfromfwdcorrelation.hpp.
Referenced by CotSwapFromFwdCorrelation(), and numberOfRates().
std::vector<Matrix> QuantLib::CotSwapFromFwdCorrelation::swapCorrMatrices_ [private]
Definition at line 44 of file cotswapfromfwdcorrelation.hpp.
Referenced by correlations(), and CotSwapFromFwdCorrelation().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/correlations/cotswapfromfwdcorrelation.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/correlations/cotswapfromfwdcorrelation.cpp