QuantLib: FastFourierTransformTest Class Reference
FastFourierTransformTest Class Reference
#include <fastfouriertransform.hpp>
Static Public Member Functions
static void testSimple ()
static void testInverse ()
static
boost::unit_test_framework::test_suite * suite ()
Detailed Description
Definition at line 29 of file fastfouriertransform.hpp.
Member Function Documentation
test_suite * FastFourierTransformTest::suite () [static]
Definition at line 103 of file fastfouriertransform.cpp.
References QUANTLIB_TEST_CASE, testInverse(), and testSimple().
Referenced by init_unit_test_suite().
{
    test_suite* suite = BOOST_TEST_SUITE("fast fourier transform tests");
    suite->add(QUANTLIB_TEST_CASE(&FastFourierTransformTest::testSimple));
    suite->add(QUANTLIB_TEST_CASE(&FastFourierTransformTest::testInverse));
    return suite;
}
void FastFourierTransformTest::testInverse () [static]
Definition at line 54 of file fastfouriertransform.cpp.
References QuantLib::Array::begin(), QuantLib::Array::end(), QuantLib::FastFourierTransform::min_order(), QL_SCIENTIFIC, and QuantLib::Array::size().
Referenced by suite().
{
    BOOST_MESSAGE("Testing convolution via inverse FFT...");
    Array x(3);
    x[0] = 1;
    x[1] = 2;
    x[2] = 3;
    size_t order = FastFourierTransform::min_order(x.size())+1;
    FastFourierTransform fft(order);
    size_t nFrq = fft.output_size();
    std::vector< std::complex<Real> > ft (nFrq);
    std::vector< Real > tmp (nFrq);
    fft.inverse_transform(x.begin(), x.end(), ft.begin());
    std::transform (ft.begin(), ft.end(), tmp.begin(), std::norm<Real>);
    std::fill (ft.begin(), ft.end(), std::complex<Real>());
    fft.inverse_transform(tmp.begin(), tmp.end(), ft.begin());
    // 0
    Real calculated = ft[0].real() / nFrq;
    Real expected = x[0]*x[0] + x[1]*x[1] + x[2]*x[2];
    if (fabs (calculated - expected) > 1.0e-10)
        BOOST_ERROR("Convolution(0)\n"
                    << std::setprecision(16) << QL_SCIENTIFIC
                    << "    calculated: " << calculated << "\n"
                    << "    expected:   " << expected);
    // 1
    calculated = ft[1].real() / nFrq;
    expected = x[0]*x[1] + x[1]*x[2];
    if (fabs (calculated - expected) > 1.0e-10)
        BOOST_ERROR("Convolution(1)\n"
                    << std::setprecision(16) << QL_SCIENTIFIC
                    << "    calculated: " << calculated << "\n"
                    << "    expected:   " << expected);
    // 2
    calculated = ft[2].real() / nFrq;
    expected = x[0]*x[2];
    if (fabs (calculated - expected) > 1.0e-10)
        BOOST_ERROR("Convolution(1)\n"
                    << std::setprecision(16) << QL_SCIENTIFIC
                    << "    calculated: " << calculated << "\n"
                    << "    expected:   " << expected);
}
void FastFourierTransformTest::testSimple () [static]
Definition at line 32 of file fastfouriertransform.cpp.
References anonymous_namespace{marketmodel.cpp}::a, anonymous_namespace{marketmodel.cpp}::b, QL_SCIENTIFIC, and QuantLib::FastFourierTransform::transform().
Referenced by suite().
{
    BOOST_MESSAGE("Testing complex direct FFT...");
    typedef std::complex<Real> cx;
    cx a[] = { cx(0,0), cx(1,1), cx(3,3), cx(4,4),
               cx(4,4), cx(3,3), cx(1,1), cx(0,0) };
    cx b[8];
    FastFourierTransform fft(3);
    fft.transform(a, a+8, b);
    cx expected[] = { cx(16,16), cx(-4.8284,-11.6569),
                      cx(0,0),   cx(-0.3431,0.8284),
                      cx(0,0),   cx(0.8284, -0.3431),
                      cx(0,0),   cx(-11.6569,-4.8284) };
    for (size_t i = 0; i<8; i++) {
        if ((std::fabs(b[i].real() - expected[i].real()) > 1.0e-2) ||
            (std::fabs(b[i].imag() - expected[i].imag()) > 1.0e-2))
            BOOST_ERROR("Convolution(" << i << ")\n"
                        << std::setprecision(4) << QL_SCIENTIFIC
                        << "    calculated: " << b[i] << "\n"
                        << "    expected:   " << expected[i]);
    }
}
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/fastfouriertransform.hpp
/home/deriversatile/QuantLib/QuantLibQt/test-suite/fastfouriertransform.cpp