QuantLib: RangeAccrualTest Class Reference
RangeAccrualTest Class Reference
#include <rangeaccrual.hpp>
Static Public Member Functions
static void testInfiniteRange ()
static void testPriceMonotonicityWithRespectToLowerStrike ()
static void testPriceMonotonicityWithRespectToUpperStrike ()
static
boost::unit_test_framework::test_suite * suite ()
Detailed Description
Definition at line 28 of file rangeaccrual.hpp.
Member Function Documentation
test_suite * RangeAccrualTest::suite () [static]
Definition at line 1649 of file rangeaccrual.cpp.
References QUANTLIB_TEST_CASE, testInfiniteRange(), testPriceMonotonicityWithRespectToLowerStrike(), and testPriceMonotonicityWithRespectToUpperStrike().
{
    test_suite* suite = BOOST_TEST_SUITE("Range Accrual tests");
    suite->add(QUANTLIB_TEST_CASE(&RangeAccrualTest::testInfiniteRange));
    suite->add(QUANTLIB_TEST_CASE(
           &RangeAccrualTest::testPriceMonotonicityWithRespectToLowerStrike));
    suite->add(QUANTLIB_TEST_CASE(
           &RangeAccrualTest::testPriceMonotonicityWithRespectToUpperStrike));
    return suite;
}
void RangeAccrualTest::testInfiniteRange () [static]
Definition at line 1487 of file rangeaccrual.cpp.
References QuantLib::FloatingRateCoupon::fixingDate(), QuantLib::FloatingRateCoupon::rate(), QuantLib::io::rate(), and QuantLib::FloatingRateCoupon::setPricer().
Referenced by suite().
{
    BOOST_MESSAGE("Testing infinite range accrual floaters...");
    CommonVars vars;
    //Coupon
    RangeAccrualFloatersCoupon coupon(vars.paymentDate,
                                      1.0,
                                      vars.iborIndex,
                                      vars.startDate,
                                      vars.endDate,
                                      vars.fixingDays,
                                      vars.rangeCouponDayCount,
                                      vars.gearing, vars.spread,
                                      vars.startDate, vars.endDate,
                                      vars.observationSchedule,
                                      vars.infiniteLowerStrike,
                                      vars.infiniteUpperStrike);
    Date fixingDate = coupon.fixingDate();
    for (Size z = 0; z < vars.smilesOnPayment.size(); z++) {
        for (Size i = 0; i < vars.byCallSpread.size(); i++){
            boost::shared_ptr<RangeAccrualPricer> bgmPricer(new
                RangeAccrualPricerByBgm(vars.correlation,
                                        vars.smilesOnExpiry[z],
                                        vars.smilesOnPayment[z],
                                        true,
                                        vars.byCallSpread[i]));
                coupon.setPricer(bgmPricer);
                //Computation
                const Rate rate = coupon.rate();
                const Rate indexfixing = vars.iborIndex->fixing(fixingDate);
                const Rate difference =  rate-indexfixing;
                if (std::fabs(difference) > vars.rateTolerance) {
                    BOOST_ERROR("\n" <<
                                "i:\t" << i << "\n"
                                "fixingDate:\t" << fixingDate << "\n"
                                "startDate:\t" << vars.startDate << "\n"
                                "range accrual rate:\t" << io::rate(rate) << "\n"
                                "index fixing:\t" << io::rate(indexfixing) << "\n"
                                "difference:\t" << io::rate(difference) << "\n"
                                "tolerance: \t" << io::rate(vars.rateTolerance));
                }
        }
    }
}
void RangeAccrualTest::testPriceMonotonicityWithRespectToLowerStrike () [static]
Definition at line 1539 of file rangeaccrual.cpp.
References QuantLib::FloatingRateCoupon::price(), and QuantLib::FloatingRateCoupon::setPricer().
Referenced by suite().
{
    BOOST_MESSAGE("Testing price monotonicity with respect to the lower strike...");
    CommonVars vars;
    for (Size z = 0; z < vars.smilesOnPayment.size(); z++) {
        for (Size i = 0; i < vars.byCallSpread.size(); i++){
            boost::shared_ptr<RangeAccrualPricer> bgmPricer(new
                RangeAccrualPricerByBgm(vars.correlation,
                                        vars.smilesOnExpiry[z],
                                        vars.smilesOnPayment[z],
                                        true,
                                        vars.byCallSpread[i]));
            Real effectiveLowerStrike;
            Real previousPrice = 100.;
            for (Size k = 1; k < 100; k++){
                effectiveLowerStrike = 0.005 + k*0.001;
                RangeAccrualFloatersCoupon coupon(
                                            vars.paymentDate,
                                            1.,
                                            vars.iborIndex,
                                            vars.startDate,
                                            vars.endDate,
                                            vars.fixingDays,
                                            vars.rangeCouponDayCount,
                                            vars.gearing, vars.spread,
                                            vars.startDate, vars.endDate,
                                            vars.observationSchedule,
                                            effectiveLowerStrike,
                                            vars.infiniteUpperStrike);
                coupon.setPricer(bgmPricer);
                //Computation
                const Rate price = coupon.price(vars.termStructure);
                if (previousPrice <= price) {
                    BOOST_ERROR("\n" <<
                                "i:\t" << i << "\n"
                                "k:\t" << k << "\n"
                                "Price at lower strike\t" << effectiveLowerStrike-0.001 <<
                                ": \t" << previousPrice << "\n"
                                "Price at lower strike\t" << effectiveLowerStrike <<
                                ": \t" << price << "\n");
                }
                previousPrice = price;
            }
        }
    }
}
void RangeAccrualTest::testPriceMonotonicityWithRespectToUpperStrike () [static]
Definition at line 1594 of file rangeaccrual.cpp.
References QuantLib::FloatingRateCoupon::price(), and QuantLib::FloatingRateCoupon::setPricer().
Referenced by suite().
{
    BOOST_MESSAGE("Testing price monotonicity with respect to the upper strike...");
    CommonVars vars;
    for (Size z = 0; z < vars.smilesOnPayment.size(); z++) {
        for (Size i = 0; i < vars.byCallSpread.size(); i++){
            boost::shared_ptr<RangeAccrualPricer> bgmPricer(new
                RangeAccrualPricerByBgm(vars.correlation,
                                        vars.smilesOnExpiry[z],
                                        vars.smilesOnPayment[z],
                                        true,
                                        vars.byCallSpread[i]));
            Real effectiveUpperStrike;
            Real previousPrice = 0.;
            for (Size k = 1; k < 95; k++){
                effectiveUpperStrike = 0.006 + k*0.001;
                RangeAccrualFloatersCoupon coupon(
                                            vars.paymentDate,
                                            1.,
                                            vars.iborIndex,
                                            vars.startDate,
                                            vars.endDate,
                                            vars.fixingDays,
                                            vars.rangeCouponDayCount,
                                            vars.gearing, vars.spread,
                                            vars.startDate, vars.endDate,
                                            vars.observationSchedule,
                                            .004,
                                            effectiveUpperStrike);
                coupon.setPricer(bgmPricer);
                //Computation
                const Rate price = coupon.price(vars.termStructure);
                if (previousPrice > price) {
                    BOOST_ERROR("\n" <<
                                "i:\t" << i << "\n"
                                "k:\t" << k << "\n"
                                "Price at upper strike\t" << effectiveUpperStrike-0.001 <<
                                ": \t" << previousPrice << "\n"
                                "Price at upper strike\t" << effectiveUpperStrike <<
                                ": \t" << price << "\n");
                }
                previousPrice = price;
            }
        }
    }
}
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/rangeaccrual.hpp
/home/deriversatile/QuantLib/QuantLibQt/test-suite/rangeaccrual.cpp