QuantLib: QuantLib::GenericSequenceStatistics< StatisticsType > Class Template Reference
QuantLib::GenericSequenceStatistics< StatisticsType > Class Template Reference
Statistics analysis of N-dimensional (sequence) data.
#include <sequencestatistics.hpp>
Public Types
typedef StatisticsType statistics_type
typedef std::vector< typename
StatisticsType::value_type > value_type
Public Member Functions
GenericSequenceStatistics (Size dimension=0)
inspectors
Size size () const
covariance and correlation
Disposable< Matrix > covariance () const
returns the covariance Matrix
Disposable< Matrix > correlation () const
returns the correlation Matrix
1-D inspectors lifted from underlying statistics class
Size samples () const
Real weightSum () const
N-D inspectors lifted from underlying statistics class
std::vector< Real > mean () const
std::vector< Real > variance () const
std::vector< Real > standardDeviation () const
std::vector< Real > downsideVariance () const
std::vector< Real > downsideDeviation () const
std::vector< Real > semiVariance () const
std::vector< Real > semiDeviation () const
std::vector< Real > errorEstimate () const
std::vector< Real > skewness () const
std::vector< Real > kurtosis () const
std::vector< Real > min () const
std::vector< Real > max () const
std::vector< Real > gaussianPercentile (Real y) const
std::vector< Real > percentile (Real y) const
std::vector< Real > gaussianPotentialUpside (Real percentile) const
std::vector< Real > potentialUpside (Real percentile) const
std::vector< Real > gaussianValueAtRisk (Real percentile) const
std::vector< Real > valueAtRisk (Real percentile) const
std::vector< Real > gaussianExpectedShortfall (Real percentile) const
std::vector< Real > expectedShortfall (Real percentile) const
std::vector< Real > regret (Real target) const
std::vector< Real > gaussianShortfall (Real target) const
std::vector< Real > shortfall (Real target) const
std::vector< Real > gaussianAverageShortfall (Real target) const
std::vector< Real > averageShortfall (Real target) const
Modifiers
void reset (Size dimension=0)
template<class Sequence >
void add (const Sequence &sample, Real weight=1.0)
template<class Iterator >
void add (Iterator begin, Iterator end, Real weight=1.0)
Protected Attributes
Size dimension_
std::vector< statistics_type > stats_
std::vector< Real > results_
Matrix quadraticSum_
Detailed Description
template<class StatisticsType>
class QuantLib::GenericSequenceStatistics< StatisticsType >
Statistics analysis of N-dimensional (sequence) data.
It provides 1-dimensional statistics as discrepancy plus N-dimensional (sequence) statistics (e.g. mean, variance, skewness, kurtosis, etc.) with one component for each dimension of the sample space.
For most of the statistics this class relies on the StatisticsType underlying class to provide 1-D methods that will be iterated for all the components of the N-D data. These lifted methods are the union of all the methods that might be requested to the 1-D underlying StatisticsType class, with the usual compile-time checks provided by the template approach.
Test:
the correctness of the returned values is tested by checking them against numerical calculations.
Definition at line 50 of file sequencestatistics.hpp.
Member Typedef Documentation
template<class StatisticsType> typedef StatisticsType QuantLib::GenericSequenceStatistics< StatisticsType >::statistics_type
Definition at line 53 of file sequencestatistics.hpp.
template<class StatisticsType> typedef std::vector<typename StatisticsType::value_type> QuantLib::GenericSequenceStatistics< StatisticsType >::value_type
Reimplemented in QuantLib::DiscrepancyStatistics.
Definition at line 54 of file sequencestatistics.hpp.
Constructor & Destructor Documentation
template<class Stat > QuantLib::GenericSequenceStatistics< Stat >::GenericSequenceStatistics (Size dimension = 0) [inline]
Definition at line 160 of file sequencestatistics.hpp.
References QuantLib::GenericSequenceStatistics< StatisticsType >::reset().
    : dimension_(0) {
        reset(dimension);
    }
Member Function Documentation
template<class StatisticsType> template<class Sequence > void QuantLib::GenericSequenceStatistics< StatisticsType >::add (const Sequence & sample, Real weight = 1.0) [inline]
Reimplemented in QuantLib::DiscrepancyStatistics.
Definition at line 115 of file sequencestatistics.hpp.
Referenced by QuantLib::GenericSequenceStatistics< StatisticsType >::add(), anonymous_namespace{stats.cpp}::checkSequence(), QuantLib::genericLongstaffSchwartzRegression(), QuantLib::historicalForwardRatesAnalysis(), QuantLib::historicalRatesAnalysis(), QuantLib::AccountingEngine::multiplePathValues(), QuantLib::ProxyGreekEngine::multiplePathValues(), QuantLib::PathwiseAccountingEngine::multiplePathValues(), CovarianceTest::testCovariance(), LowDiscrepancyTest::testHalton(), BrownianBridgeTest::testPathGeneration(), anonymous_namespace{lowdiscrepancysequences.cpp}::testRandomizedLatticeRule(), LowDiscrepancyTest::testSobol(), and BrownianBridgeTest::testVariates().
{
            add(sample.begin(), sample.end(), weight);
        }
template<class StatisticsType> template<class Iterator > void QuantLib::GenericSequenceStatistics< StatisticsType >::add (Iterator begin, Iterator end, Real weight = 1.0) [inline]
Reimplemented in QuantLib::DiscrepancyStatistics.
Definition at line 120 of file sequencestatistics.hpp.
References QuantLib::GenericSequenceStatistics< StatisticsType >::add(), QuantLib::GenericSequenceStatistics< StatisticsType >::dimension_, QuantLib::outerProduct(), QL_REQUIRE, QuantLib::GenericSequenceStatistics< StatisticsType >::quadraticSum_, QuantLib::GenericSequenceStatistics< StatisticsType >::reset(), and QuantLib::GenericSequenceStatistics< StatisticsType >::stats_.
{
            if (dimension_ == 0) {
                // stat wasn't initialized yet
                QL_REQUIRE(end>begin, "sample error: end<=begin");
                Size dimension = std::distance(begin, end);
                reset(dimension);
            }
            QL_REQUIRE(std::distance(begin, end) == Integer(dimension_),
                       "sample size mismatch: " << dimension_ <<
                       " required, " << std::distance(begin, end) <<
                       " provided");
            quadraticSum_ += weight * outerProduct(begin, end,
                                                   begin, end);
            for (Size i=0; i<dimension_; ++begin, ++i)
                stats_[i].add(*begin, weight);
        }
template<class StatisticsType> std::vector<Real> QuantLib::GenericSequenceStatistics< StatisticsType >::averageShortfall (Real target) const
template<class Stat > Disposable< Matrix > QuantLib::GenericSequenceStatistics< Stat >::correlation () const
returns the correlation Matrix
Definition at line 270 of file sequencestatistics.hpp.
References QuantLib::Matrix::diagonal().
Referenced by CovarianceTest::testCovariance().
{
        Matrix correlation = covariance();
        Array variances = correlation.diagonal();
        for (Size i=0; i<dimension_; i++){
            for (Size j=0; j<dimension_; j++){
                if (i==j) {
                    if (variances[i]==0.0) {
                        correlation[i][j] = 1.0;
                    } else {
                        correlation[i][j] *=
                            1.0/std::sqrt(variances[i]*variances[j]);
                    }
                } else {
                    if (variances[i]==0.0 && variances[j]==0) {
                        correlation[i][j] = 1.0;
                    } else if (variances[i]==0.0 || variances[j]==0.0) {
                        correlation[i][j] = 0.0;
                    } else {
                        correlation[i][j] *=
                            1.0/std::sqrt(variances[i]*variances[j]);
                    }
                }
            } // j for
        } // i for
        return correlation;
    }
template<class Stat > Disposable< Matrix > QuantLib::GenericSequenceStatistics< Stat >::covariance () const
returns the covariance Matrix
Definition at line 248 of file sequencestatistics.hpp.
References QuantLib::outerProduct(), and QL_REQUIRE.
Referenced by QuantLib::genericLongstaffSchwartzRegression(), CovarianceTest::testCovariance(), BrownianBridgeTest::testPathGeneration(), and BrownianBridgeTest::testVariates().
{
        Real sampleWeight = weightSum();
        QL_REQUIRE(sampleWeight > 0.0,
                   "sampleWeight=0, unsufficient");
        Real sampleNumber = static_cast<Real>(samples());
        QL_REQUIRE(sampleNumber > 1.0,
                   "sample number <=1, unsufficient");
        std::vector<Real> m = mean();
        Real inv = 1.0/sampleWeight;
        Matrix result = inv*quadraticSum_;
        result -= outerProduct(m.begin(), m.end(),
                               m.begin(), m.end());
        result *= (sampleNumber/(sampleNumber-1.0));
        return result;
    }
template<class StatisticsType> std::vector<Real> QuantLib::GenericSequenceStatistics< StatisticsType >::downsideDeviation () const
template<class StatisticsType> std::vector<Real> QuantLib::GenericSequenceStatistics< StatisticsType >::downsideVariance () const
template<class StatisticsType> std::vector<Real> QuantLib::GenericSequenceStatistics< StatisticsType >::errorEstimate () const
Referenced by anonymous_namespace{marketmodel.cpp}::checkCallableSwap(), anonymous_namespace{marketmodel_cms.cpp}::checkCMSAndSwaptions(), anonymous_namespace{marketmodel_smm.cpp}::checkCoterminalSwapsAndSwaptions(), anonymous_namespace{marketmodel.cpp}::checkForwardsAndOptionlets(), anonymous_namespace{marketmodel.cpp}::checkMultiProductCompositeResults(), anonymous_namespace{marketmodel.cpp}::checkNormalForwardsAndOptionlets(), MarketModelTest::testPathwiseGreeks(), MarketModelTest::testPathwiseVegas(), and anonymous_namespace{lowdiscrepancysequences.cpp}::testRandomizedLatticeRule().
template<class StatisticsType> std::vector<Real> QuantLib::GenericSequenceStatistics< StatisticsType >::expectedShortfall (Real percentile) const
template<class StatisticsType> std::vector<Real> QuantLib::GenericSequenceStatistics< StatisticsType >::gaussianAverageShortfall (Real target) const
template<class StatisticsType> std::vector<Real> QuantLib::GenericSequenceStatistics< StatisticsType >::gaussianExpectedShortfall (Real percentile) const
template<class StatisticsType> std::vector<Real> QuantLib::GenericSequenceStatistics< StatisticsType >::gaussianPercentile (Real y) const
template<class StatisticsType> std::vector<Real> QuantLib::GenericSequenceStatistics< StatisticsType >::gaussianPotentialUpside (Real percentile) const
template<class StatisticsType> std::vector<Real> QuantLib::GenericSequenceStatistics< StatisticsType >::gaussianShortfall (Real target) const
template<class StatisticsType> std::vector<Real> QuantLib::GenericSequenceStatistics< StatisticsType >::gaussianValueAtRisk (Real percentile) const
template<class StatisticsType> std::vector<Real> QuantLib::GenericSequenceStatistics< StatisticsType >::kurtosis () const
Referenced by anonymous_namespace{stats.cpp}::checkSequence().
template<class StatisticsType> std::vector<Real> QuantLib::GenericSequenceStatistics< StatisticsType >::max () const
Referenced by QuantLib::DiscrepancyStatistics::add(), and anonymous_namespace{stats.cpp}::checkSequence().
template<class StatisticsType> std::vector<Real> QuantLib::GenericSequenceStatistics< StatisticsType >::mean () const
Referenced by anonymous_namespace{marketmodel.cpp}::checkCallableSwap(), anonymous_namespace{marketmodel_cms.cpp}::checkCMSAndSwaptions(), anonymous_namespace{marketmodel_smm.cpp}::checkCoterminalSwapsAndSwaptions(), anonymous_namespace{marketmodel.cpp}::checkForwardsAndOptionlets(), anonymous_namespace{marketmodel.cpp}::checkMultiProductCompositeResults(), anonymous_namespace{marketmodel.cpp}::checkNormalForwardsAndOptionlets(), anonymous_namespace{stats.cpp}::checkSequence(), QuantLib::genericLongstaffSchwartzRegression(), CovarianceTest::testCovariance(), LowDiscrepancyTest::testHalton(), BrownianBridgeTest::testPathGeneration(), MarketModelTest::testPathwiseGreeks(), MarketModelTest::testPathwiseVegas(), anonymous_namespace{lowdiscrepancysequences.cpp}::testRandomizedLatticeRule(), LowDiscrepancyTest::testSobol(), and BrownianBridgeTest::testVariates().
template<class StatisticsType> std::vector<Real> QuantLib::GenericSequenceStatistics< StatisticsType >::min () const
Referenced by anonymous_namespace{stats.cpp}::checkSequence().
template<class StatisticsType> std::vector<Real> QuantLib::GenericSequenceStatistics< StatisticsType >::percentile (Real y) const
template<class StatisticsType> std::vector<Real> QuantLib::GenericSequenceStatistics< StatisticsType >::potentialUpside (Real percentile) const
template<class StatisticsType> std::vector<Real> QuantLib::GenericSequenceStatistics< StatisticsType >::regret (Real target) const
template<class Stat > void QuantLib::GenericSequenceStatistics< Stat >::reset (Size dimension = 0)
Reimplemented in QuantLib::DiscrepancyStatistics.
Definition at line 230 of file sequencestatistics.hpp.
References anonymous_namespace{inflationvolatility.cpp}::reset().
Referenced by QuantLib::GenericSequenceStatistics< StatisticsType >::add(), QuantLib::GenericSequenceStatistics< StatisticsType >::GenericSequenceStatistics(), QuantLib::historicalForwardRatesAnalysis(), QuantLib::historicalRatesAnalysis(), and LowDiscrepancyTest::testHalton().
{
        // (re-)initialize
        if (dimension > 0) {
            if (dimension == dimension_) {
                for (Size i=0; i<dimension_; ++i)
                    stats_[i].reset();
            } else {
                dimension_ = dimension;
                stats_ = std::vector<Stat>(dimension);
                results_ = std::vector<Real>(dimension);
            }
            quadraticSum_ = Matrix(dimension_, dimension_, 0.0);
        } else {
            dimension_ = dimension;
        }
    }
template<class Stat > Size QuantLib::GenericSequenceStatistics< Stat >::samples () const [inline]
Definition at line 166 of file sequencestatistics.hpp.
Referenced by QuantLib::DiscrepancyStatistics::add(), anonymous_namespace{stats.cpp}::checkSequence(), and QuantLib::DiscrepancyStatistics::discrepancy().
{
        return (stats_.size() == 0) ? 0 : stats_[0].samples();
    }
template<class StatisticsType> std::vector<Real> QuantLib::GenericSequenceStatistics< StatisticsType >::semiDeviation () const
template<class StatisticsType> std::vector<Real> QuantLib::GenericSequenceStatistics< StatisticsType >::semiVariance () const
template<class StatisticsType> std::vector<Real> QuantLib::GenericSequenceStatistics< StatisticsType >::shortfall (Real target) const
template<class StatisticsType> Size QuantLib::GenericSequenceStatistics< StatisticsType >::size () const [inline]
Definition at line 59 of file sequencestatistics.hpp.
References QuantLib::GenericSequenceStatistics< StatisticsType >::dimension_.
{ return dimension_; }
template<class StatisticsType> std::vector<Real> QuantLib::GenericSequenceStatistics< StatisticsType >::skewness () const
Referenced by anonymous_namespace{stats.cpp}::checkSequence().
template<class StatisticsType> std::vector<Real> QuantLib::GenericSequenceStatistics< StatisticsType >::standardDeviation () const
Referenced by anonymous_namespace{stats.cpp}::checkSequence(), and CovarianceTest::testCovariance().
template<class StatisticsType> std::vector<Real> QuantLib::GenericSequenceStatistics< StatisticsType >::valueAtRisk (Real percentile) const
template<class StatisticsType> std::vector<Real> QuantLib::GenericSequenceStatistics< StatisticsType >::variance () const
Referenced by anonymous_namespace{stats.cpp}::checkSequence().
template<class Stat > Real QuantLib::GenericSequenceStatistics< Stat >::weightSum () const [inline]
Definition at line 171 of file sequencestatistics.hpp.
Referenced by anonymous_namespace{stats.cpp}::checkSequence().
{
        return (stats_.size() == 0) ? 0.0 : stats_[0].weightSum();
    }
Member Data Documentation
template<class StatisticsType> Size QuantLib::GenericSequenceStatistics< StatisticsType >::dimension_ [protected]
Definition at line 144 of file sequencestatistics.hpp.
Referenced by QuantLib::DiscrepancyStatistics::add(), QuantLib::GenericSequenceStatistics< StatisticsType >::add(), QuantLib::DiscrepancyStatistics::reset(), and QuantLib::GenericSequenceStatistics< StatisticsType >::size().
template<class StatisticsType> Matrix QuantLib::GenericSequenceStatistics< StatisticsType >::quadraticSum_ [protected]
Definition at line 147 of file sequencestatistics.hpp.
Referenced by QuantLib::GenericSequenceStatistics< StatisticsType >::add().
template<class StatisticsType> std::vector<Real> QuantLib::GenericSequenceStatistics< StatisticsType >::results_ [mutable, protected]
Definition at line 146 of file sequencestatistics.hpp.
template<class StatisticsType> std::vector<statistics_type> QuantLib::GenericSequenceStatistics< StatisticsType >::stats_ [protected]
Definition at line 145 of file sequencestatistics.hpp.
Referenced by QuantLib::DiscrepancyStatistics::add(), and QuantLib::GenericSequenceStatistics< StatisticsType >::add().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/statistics/sequencestatistics.hpp