QuantLib: QuantLib::IncrementalStatistics Class Reference
QuantLib::IncrementalStatistics Class Reference
Statistics tool based on incremental accumulation.
#include <incrementalstatistics.hpp>
Public Types
typedef Real value_type
Public Member Functions
IncrementalStatistics ()
Inspectors
Size samples () const
number of samples collected
Real weightSum () const
sum of data weights
Real mean () const
Real variance () const
Real standardDeviation () const
Real errorEstimate () const
Real skewness () const
Real kurtosis () const
Real min () const
Real max () const
Real downsideVariance () const
Real downsideDeviation () const
Modifiers
void add (Real value, Real weight=1.0)
adds a datum to the set, possibly with a weight
template<class DataIterator >
void addSequence (DataIterator begin, DataIterator end)
adds a sequence of data to the set, with default weight
template<class DataIterator , class WeightIterator >
void addSequence (DataIterator begin, DataIterator end, WeightIterator wbegin)
adds a sequence of data to the set, each with its weight
void reset ()
resets the data to a null set
Protected Attributes
Size sampleNumber_
Size downsideSampleNumber_
Real sampleWeight_
Real downsideSampleWeight_
Real sum_
Real quadraticSum_
Real downsideQuadraticSum_
Real cubicSum_
Real fourthPowerSum_
Real min_
Real max_
Detailed Description
Statistics tool based on incremental accumulation.
It can accumulate a set of data and return statistics (e.g: mean, variance, skewness, kurtosis, error estimation, etc.)
Warning:
high moments are numerically unstable for high average/standardDeviation ratios.
Definition at line 40 of file incrementalstatistics.hpp.
Member Typedef Documentation
typedef Real QuantLib::IncrementalStatistics::value_type
Definition at line 42 of file incrementalstatistics.hpp.
Constructor & Destructor Documentation
QuantLib::IncrementalStatistics::IncrementalStatistics ()
Definition at line 26 of file incrementalstatistics.cpp.
References reset().
{
        reset();
    }
Member Function Documentation
void QuantLib::IncrementalStatistics::add (Real value, Real weight = 1.0)
adds a datum to the set, possibly with a weight
Precondition:
weight must be positive or null
Definition at line 143 of file incrementalstatistics.cpp.
References cubicSum_, downsideQuadraticSum_, downsideSampleNumber_, downsideSampleWeight_, fourthPowerSum_, max(), max_, min(), min_, QL_ENSURE, QL_REQUIRE, quadraticSum_, sampleNumber_, sampleWeight_, and sum_.
Referenced by addSequence().
{
        QL_REQUIRE(weight>=0.0,
                   "negative weight (" << weight << ") not allowed");
        Size oldSamples = sampleNumber_;
        sampleNumber_++;
        QL_ENSURE(sampleNumber_ > oldSamples,
                  "maximum number of samples reached");
        sampleWeight_ += weight;
        Real temp = weight*value;
        sum_ += temp;
        temp *= value;
        quadraticSum_ += temp;
        if (value<0.0) {
            downsideQuadraticSum_ += temp;
            downsideSampleNumber_++;
            downsideSampleWeight_ += weight;
        }
        temp *= value;
        cubicSum_ += temp;
        temp *= value;
        fourthPowerSum_ += temp;
        if (oldSamples == 0) {
            min_ = max_ = value;
        } else {
            min_ = std::min(value, min_);
            max_ = std::max(value, max_);
        }
    }
template<class DataIterator > void QuantLib::IncrementalStatistics::addSequence (DataIterator begin, DataIterator end) [inline]
adds a sequence of data to the set, with default weight
Definition at line 117 of file incrementalstatistics.hpp.
References add().
Referenced by QuantLib::Histogram::calculate().
{
            for (;begin!=end;++begin)
                add(*begin);
        }
template<class DataIterator , class WeightIterator > void QuantLib::IncrementalStatistics::addSequence (DataIterator begin, DataIterator end, WeightIterator wbegin) [inline]
adds a sequence of data to the set, each with its weight
Precondition:
weights must be positive or null
Definition at line 124 of file incrementalstatistics.hpp.
References add().
{
            for (;begin!=end;++begin,++wbegin)
                add(*begin, *wbegin);
        }
Real QuantLib::IncrementalStatistics::downsideDeviation () const
returns the downside deviation, defined as the square root of the downside variance.
Definition at line 80 of file incrementalstatistics.cpp.
References downsideVariance().
{
        return std::sqrt(downsideVariance());
    }
Real QuantLib::IncrementalStatistics::downsideVariance () const
returns the downside variance, defined as
\[ \frac{N}{N-1} \times \frac{ \sum_{i=1}^{N} \theta \times x_i^{2}}{ \sum_{i=1}^{N} w_i} \]
, where \(\theta \) = 0 if x > 0 and \(\theta \) =1 if x <0
Definition at line 66 of file incrementalstatistics.cpp.
References downsideQuadraticSum_, downsideSampleNumber_, downsideSampleWeight_, QL_REQUIRE, and sampleWeight_.
Referenced by downsideDeviation().
{
        if (downsideSampleWeight_==0.0) {
            QL_REQUIRE(sampleWeight_>0.0,
                       "sampleWeight_=0, unsufficient");
            return 0.0;
        }
        QL_REQUIRE(downsideSampleNumber_>1,
                   "sample number below zero <=1, unsufficient");
        return (downsideSampleNumber_/(downsideSampleNumber_-1.0))*
            (downsideQuadraticSum_ /downsideSampleWeight_);
    }
Real QuantLib::IncrementalStatistics::errorEstimate () const
returns the error estimate \(\epsilon \), defined as the square root of the ratio of the variance to the number of samples.
Definition at line 84 of file incrementalstatistics.cpp.
References QL_REQUIRE, samples(), and variance().
{
        Real var = variance();
        QL_REQUIRE(samples() > 0, "empty sample set");
        return std::sqrt(var/samples());
    }
Real QuantLib::IncrementalStatistics::kurtosis () const
returns the excess kurtosis, defined as
\[ \frac{N^2(N+1)}{(N-1)(N-2)(N-3)} \frac{\left\langle \left(x-\langle x \rangle \right)^4 \right\rangle}{\sigma^4} - \frac{3(N-1)^2}{(N-2)(N-3)}. \]
The above evaluates to 0 for a Gaussian distribution.
Definition at line 107 of file incrementalstatistics.cpp.
References anonymous_namespace{marketmodel.cpp}::c, cubicSum_, fourthPowerSum_, mean(), QL_REQUIRE, quadraticSum_, sampleNumber_, sampleWeight_, anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and variance().
{
        QL_REQUIRE(sampleNumber_>3,
                   "sample number <=3, unsufficient");
        Real m = mean();
        Real v = variance();
        Real c = (sampleNumber_-1.0)/(sampleNumber_-2.0);
        c *= (sampleNumber_-1.0)/(sampleNumber_-3.0);
        c *= 3.0;
        if (v==0) return c;
        Real result = fourthPowerSum_/sampleWeight_;
        result -= 4.0*m*(cubicSum_/sampleWeight_);
        result += 6.0*m*m*(quadraticSum_/sampleWeight_);
        result -= 3.0*m*m*m*m;
        result /= v*v;
        result *= sampleNumber_/(sampleNumber_-1.0);
        result *= sampleNumber_/(sampleNumber_-2.0);
        result *= (sampleNumber_+1.0)/(sampleNumber_-3.0);
        return result-c;
    }
Real QuantLib::IncrementalStatistics::max () const
returns the maximum sample value
Definition at line 138 of file incrementalstatistics.cpp.
References max_, QL_REQUIRE, and samples().
Referenced by add().
{
        QL_REQUIRE(samples() > 0, "empty sample set");
        return max_;
    }
Real QuantLib::IncrementalStatistics::mean () const
returns the mean, defined as
\[ \langle x \rangle = \frac{\sum w_i x_i}{\sum w_i}. \]
Definition at line 38 of file incrementalstatistics.cpp.
References QL_REQUIRE, sampleWeight_, and sum_.
Referenced by kurtosis(), skewness(), and variance().
{
        QL_REQUIRE(sampleWeight_>0.0,
                   "sampleWeight_=0, unsufficient");
        return sum_/sampleWeight_;
    }
Real QuantLib::IncrementalStatistics::min () const
returns the minimum sample value
Definition at line 133 of file incrementalstatistics.cpp.
References min_, QL_REQUIRE, and samples().
Referenced by add().
{
        QL_REQUIRE(samples() > 0, "empty sample set");
        return min_;
    }
void QuantLib::IncrementalStatistics::reset ()
resets the data to a null set
Definition at line 175 of file incrementalstatistics.cpp.
References cubicSum_, downsideQuadraticSum_, downsideSampleNumber_, downsideSampleWeight_, fourthPowerSum_, max_, min_, QL_MAX_REAL, QL_MIN_REAL, quadraticSum_, sampleNumber_, sampleWeight_, and sum_.
Referenced by IncrementalStatistics().
{
        min_ = QL_MAX_REAL;
        max_ = QL_MIN_REAL;
        sampleNumber_ = 0;
        downsideSampleNumber_ = 0;
        sampleWeight_ = 0.0;
        downsideSampleWeight_ = 0.0;
        sum_ = 0.0;
        quadraticSum_ = 0.0;
        downsideQuadraticSum_ = 0.0;
        cubicSum_ = 0.0;
        fourthPowerSum_ = 0.0;
    }
Size QuantLib::IncrementalStatistics::samples () const
number of samples collected
Definition at line 30 of file incrementalstatistics.cpp.
References sampleNumber_.
Referenced by errorEstimate(), max(), and min().
{
        return sampleNumber_;
    }
Real QuantLib::IncrementalStatistics::skewness () const
returns the skewness, defined as
\[ \frac{N^2}{(N-1)(N-2)} \frac{\left\langle \left(x-\langle x \rangle \right)^3 \right\rangle}{\sigma^3}. \]
The above evaluates to 0 for a Gaussian distribution.
Definition at line 90 of file incrementalstatistics.cpp.
References cubicSum_, mean(), QL_REQUIRE, quadraticSum_, sampleNumber_, sampleWeight_, and standardDeviation().
{
        QL_REQUIRE(sampleNumber_>2,
                   "sample number <=2, unsufficient");
        Real s = standardDeviation();
        if (s==0.0) return 0.0;
        Real m = mean();
        Real result = cubicSum_/sampleWeight_;
        result -= 3.0*m*(quadraticSum_/sampleWeight_);
        result += 2.0*m*m*m;
        result /= s*s*s;
        result *= sampleNumber_/(sampleNumber_-1.0);
        result *= sampleNumber_/(sampleNumber_-2.0);
        return result;
    }
Real QuantLib::IncrementalStatistics::standardDeviation () const
returns the standard deviation \(\sigma \), defined as the square root of the variance.
Definition at line 62 of file incrementalstatistics.cpp.
References variance().
Referenced by skewness().
{
        return std::sqrt(variance());
    }
Real QuantLib::IncrementalStatistics::variance () const
returns the variance, defined as
\[ \frac{N}{N-1} \left\langle \left(x-\langle x \rangle \right)^2 \right\rangle. \]
Definition at line 44 of file incrementalstatistics.cpp.
References mean(), QL_ENSURE, QL_REQUIRE, quadraticSum_, sampleNumber_, sampleWeight_, and anonymous_namespace{perturbativebarrieroptionengine.cpp}::v().
Referenced by QuantLib::Histogram::calculate(), errorEstimate(), kurtosis(), and standardDeviation().
{
        QL_REQUIRE(sampleWeight_>0.0,
                   "sampleWeight_=0, unsufficient");
        QL_REQUIRE(sampleNumber_>1,
                   "sample number <=1, unsufficient");
        Real m = mean();
        Real v = quadraticSum_/sampleWeight_;
        v -= m*m;
        v *= sampleNumber_/(sampleNumber_-1.0);
        QL_ENSURE(v >= 0.0,
                  "negative variance (" << std::scientific << v << ")");
        return v;
    }
Real QuantLib::IncrementalStatistics::weightSum () const
sum of data weights
Definition at line 34 of file incrementalstatistics.cpp.
References sampleWeight_.
{
        return sampleWeight_;
    }
Member Data Documentation
Real QuantLib::IncrementalStatistics::cubicSum_ [protected]
Definition at line 135 of file incrementalstatistics.hpp.
Referenced by add(), kurtosis(), reset(), and skewness().
Real QuantLib::IncrementalStatistics::downsideQuadraticSum_ [protected]
Definition at line 135 of file incrementalstatistics.hpp.
Referenced by add(), downsideVariance(), and reset().
Size QuantLib::IncrementalStatistics::downsideSampleNumber_ [protected]
Definition at line 133 of file incrementalstatistics.hpp.
Referenced by add(), downsideVariance(), and reset().
Real QuantLib::IncrementalStatistics::downsideSampleWeight_ [protected]
Definition at line 134 of file incrementalstatistics.hpp.
Referenced by add(), downsideVariance(), and reset().
Real QuantLib::IncrementalStatistics::fourthPowerSum_ [protected]
Definition at line 135 of file incrementalstatistics.hpp.
Referenced by add(), kurtosis(), and reset().
Real QuantLib::IncrementalStatistics::max_ [protected]
Definition at line 137 of file incrementalstatistics.hpp.
Referenced by add(), max(), and reset().
Real QuantLib::IncrementalStatistics::min_ [protected]
Definition at line 137 of file incrementalstatistics.hpp.
Referenced by add(), min(), and reset().
Real QuantLib::IncrementalStatistics::quadraticSum_ [protected]
Definition at line 135 of file incrementalstatistics.hpp.
Referenced by add(), kurtosis(), reset(), skewness(), and variance().
Size QuantLib::IncrementalStatistics::sampleNumber_ [protected]
Definition at line 133 of file incrementalstatistics.hpp.
Referenced by add(), kurtosis(), reset(), samples(), skewness(), and variance().
Real QuantLib::IncrementalStatistics::sampleWeight_ [protected]
Definition at line 134 of file incrementalstatistics.hpp.
Referenced by add(), downsideVariance(), kurtosis(), mean(), reset(), skewness(), variance(), and weightSum().
Real QuantLib::IncrementalStatistics::sum_ [protected]
Definition at line 135 of file incrementalstatistics.hpp.
Referenced by add(), mean(), and reset().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/statistics/incrementalstatistics.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/math/statistics/incrementalstatistics.cpp