QuantLib: QuantLib::YoYInflationCouponPricer Class Reference
QuantLib::YoYInflationCouponPricer Class Reference
base pricer for capped/floored YoY inflation coupons
#include <inflationcouponpricer.hpp>
Public Member Functions
YoYInflationCouponPricer (const Handle< YoYOptionletVolatilitySurface > &capletVol=Handle< YoYOptionletVolatilitySurface >())
virtual Handle
< YoYOptionletVolatilitySurface > capletVolatility () const
virtual void setCapletVolatility (const Handle< YoYOptionletVolatilitySurface > &capletVol)
InflationCouponPricer interface
virtual Real swapletPrice () const
virtual Rate swapletRate () const
virtual Real capletPrice (Rate effectiveCap) const
virtual Rate capletRate (Rate effectiveCap) const
virtual Real floorletPrice (Rate effectiveFloor) const
virtual Rate floorletRate (Rate effectiveFloor) const
virtual void initialize (const InflationCoupon &)
Protected Member Functions
virtual Real optionletPrice (Option::Type optionType, Real effStrike) const
car replace this if really required
virtual Real optionletPriceImp (Option::Type, Real strike, Real forward, Real stdDev) const
virtual Rate adjustedFixing (Rate fixing=Null< Rate >()) const
Protected Attributes
Handle
< YoYOptionletVolatilitySurface > capletVol_
data
const YoYInflationCoupon * coupon_
Real gearing_
Spread spread_
Real discount_
Real spreadLegValue_
Detailed Description
base pricer for capped/floored YoY inflation coupons
Note:
this pricer can already do swaplets but to get volatility-dependent coupons you need the descendents.
Definition at line 82 of file inflationcouponpricer.hpp.
Constructor & Destructor Documentation
QuantLib::YoYInflationCouponPricer::YoYInflationCouponPricer (const Handle< YoYOptionletVolatilitySurface > & capletVol = Handle<YoYOptionletVolatilitySurface>())
Definition at line 27 of file inflationcouponpricer.cpp.
References capletVol_, QuantLib::Handle< T >::empty(), and QuantLib::Observer::registerWith().
    : capletVol_(capletVol) {
        if( !capletVol_.empty() ) registerWith(capletVol_);
    }
Member Function Documentation
Rate QuantLib::YoYInflationCouponPricer::adjustedFixing (Rate fixing = Null<Rate>()) const [protected, virtual]
Definition at line 107 of file inflationcouponpricer.cpp.
References coupon_, and QuantLib::InflationCoupon::indexFixing().
Referenced by optionletPrice(), swapletPrice(), and swapletRate().
{
        if (fixing == Null<Rate>())
            fixing = coupon_->indexFixing();
        // no adjustment
        return fixing;
    }
Real QuantLib::YoYInflationCouponPricer::capletPrice (Rate effectiveCap) const [virtual]
Implements QuantLib::InflationCouponPricer.
Definition at line 47 of file inflationcouponpricer.cpp.
References QuantLib::Option::Call, gearing_, and optionletPrice().
Referenced by capletRate().
{
        Real capletPrice = optionletPrice(Option::Call, effectiveCap);
        return gearing_ * capletPrice;
    }
Rate QuantLib::YoYInflationCouponPricer::capletRate (Rate effectiveCap) const [virtual]
Implements QuantLib::InflationCouponPricer.
Definition at line 58 of file inflationcouponpricer.cpp.
References QuantLib::Coupon::accrualPeriod(), capletPrice(), coupon_, and discount_.
{
        return capletPrice(effectiveCap)/(coupon_->accrualPeriod()*discount_);
    }
virtual Handle<YoYOptionletVolatilitySurface> QuantLib::YoYInflationCouponPricer::capletVolatility () const [inline, virtual]
Definition at line 87 of file inflationcouponpricer.hpp.
References capletVol_.
Referenced by optionletPrice().
{
            return capletVol_;
        }
Real QuantLib::YoYInflationCouponPricer::floorletPrice (Rate effectiveFloor) const [virtual]
Implements QuantLib::InflationCouponPricer.
Definition at line 42 of file inflationcouponpricer.cpp.
References gearing_, optionletPrice(), and QuantLib::Option::Put.
Referenced by floorletRate().
{
        Real floorletPrice = optionletPrice(Option::Put, effectiveFloor);
        return gearing_ * floorletPrice;
    }
Rate QuantLib::YoYInflationCouponPricer::floorletRate (Rate effectiveFloor) const [virtual]
Implements QuantLib::InflationCouponPricer.
Definition at line 53 of file inflationcouponpricer.cpp.
References QuantLib::Coupon::accrualPeriod(), coupon_, discount_, and floorletPrice().
{
        return floorletPrice(effectiveFloor)/
        (coupon_->accrualPeriod()*discount_);
    }
void QuantLib::YoYInflationCouponPricer::initialize (const InflationCoupon & coupon) [virtual]
Implements QuantLib::InflationCouponPricer.
Definition at line 117 of file inflationcouponpricer.cpp.
References QuantLib::Coupon::accrualPeriod(), coupon_, QuantLib::Coupon::date(), discount_, QuantLib::YoYInflationCoupon::gearing(), gearing_, QuantLib::InflationCoupon::index(), QuantLib::InflationCouponPricer::paymentDate_, QL_REQUIRE, QuantLib::InflationCouponPricer::rateCurve_, QuantLib::YoYInflationCoupon::spread(), spread_, and spreadLegValue_.
{
        coupon_ = dynamic_cast<const YoYInflationCoupon*>(&coupon);
        QL_REQUIRE(coupon_, "year-on-year inflation coupon needed");
        gearing_ = coupon_->gearing();
        spread_ = coupon_->spread();
        paymentDate_ = coupon_->date();
        rateCurve_ = boost::dynamic_pointer_cast<YoYInflationIndex>(coupon.index())
            ->yoyInflationTermStructure()
            ->nominalTermStructure();
        // past or future fixing is managed in YoYInflationIndex::fixing()
        // use yield curve from index (which sets discount)
        discount_ = 1.0;
        if (paymentDate_ > rateCurve_->referenceDate())
            discount_ = rateCurve_->discount(paymentDate_);
        spreadLegValue_ = spread_ * coupon_->accrualPeriod()* discount_;
    }
Real QuantLib::YoYInflationCouponPricer::optionletPrice (Option::Type optionType, Real effStrike) const [protected, virtual]
car replace this if really required
Definition at line 77 of file inflationcouponpricer.cpp.
References anonymous_namespace{marketmodel.cpp}::a, QuantLib::Coupon::accrualPeriod(), adjustedFixing(), anonymous_namespace{marketmodel.cpp}::b, QuantLib::Option::Call, capletVolatility(), coupon_, discount_, QuantLib::InflationCoupon::fixingDate(), QuantLib::InflationCoupon::indexFixing(), QuantLib::Singleton< Settings >::instance(), optionletPriceImp(), and QL_REQUIRE.
Referenced by capletPrice(), and floorletPrice().
{
        Date fixingDate = coupon_->fixingDate();
        if (fixingDate <= Settings::instance().evaluationDate()) {
            // the amount is determined
            Real a, b;
            if (optionType==Option::Call) {
                a = coupon_->indexFixing();
                b = effStrike;
            } else {
                a = effStrike;
                b = coupon_->indexFixing();
            }
            return std::max(a - b, 0.0)* coupon_->accrualPeriod()*discount_;
        } else {
            // not yet determined, use Black/DD1/Bachelier/whatever from Impl
            QL_REQUIRE(!capletVolatility().empty(),
                       "missing optionlet volatility");
            Real stdDev =
            std::sqrt(capletVolatility()->totalVariance(fixingDate,
                                                        effStrike));
            Rate fixing = optionletPriceImp(optionType,
                                            effStrike,
                                            adjustedFixing(),
                                            stdDev);
            return fixing * coupon_->accrualPeriod() * discount_;
        }
    }
Real QuantLib::YoYInflationCouponPricer::optionletPriceImp (Option::Type , Real strike, Real forward, Real stdDev) const [protected, virtual]
usually only need implement this (of course they may need to re-implement initialize too ...)
Reimplemented in QuantLib::BachelierYoYInflationCouponPricer, QuantLib::UnitDisplacedBlackYoYInflationCouponPricer, and QuantLib::BlackYoYInflationCouponPricer.
Definition at line 63 of file inflationcouponpricer.cpp.
References QL_FAIL.
Referenced by optionletPrice().
{
        QL_FAIL("you must implement this to get a vol-dependent price");
        //return effStrike*forward*stdDev*optionType;
    }
void QuantLib::YoYInflationCouponPricer::setCapletVolatility (const Handle< YoYOptionletVolatilitySurface > & capletVol) [virtual]
Definition at line 34 of file inflationcouponpricer.cpp.
References capletVol_, QuantLib::Handle< T >::empty(), QL_REQUIRE, and QuantLib::Observer::registerWith().
{
        QL_REQUIRE(!capletVol.empty(),"empty capletVol handle")
        capletVol_ = capletVol;
        registerWith(capletVol_);
    }
Real QuantLib::YoYInflationCouponPricer::swapletPrice () const [virtual]
Implements QuantLib::InflationCouponPricer.
Definition at line 139 of file inflationcouponpricer.cpp.
References QuantLib::Coupon::accrualPeriod(), adjustedFixing(), coupon_, discount_, gearing_, and spreadLegValue_.
{
        Real swapletPrice = adjustedFixing() * coupon_->accrualPeriod() * discount_;
        return gearing_ * swapletPrice + spreadLegValue_;
    }
Rate QuantLib::YoYInflationCouponPricer::swapletRate () const [virtual]
Implements QuantLib::InflationCouponPricer.
Definition at line 146 of file inflationcouponpricer.cpp.
References adjustedFixing(), gearing_, and spread_.
{
        // This way we do not require the index to have
        // a yield curve, i.e. we do not get the problem
        // that a discounting-instrument-pricer is used
        // with a different yield curve
        return gearing_ * adjustedFixing() + spread_;
    }
Member Data Documentation
Handle<YoYOptionletVolatilitySurface> QuantLib::YoYInflationCouponPricer::capletVol_ [protected]
data
Definition at line 119 of file inflationcouponpricer.hpp.
Referenced by capletVolatility(), setCapletVolatility(), and YoYInflationCouponPricer().
const YoYInflationCoupon* QuantLib::YoYInflationCouponPricer::coupon_ [protected]
Definition at line 120 of file inflationcouponpricer.hpp.
Referenced by adjustedFixing(), capletRate(), floorletRate(), initialize(), optionletPrice(), and swapletPrice().
Real QuantLib::YoYInflationCouponPricer::discount_ [protected]
Definition at line 123 of file inflationcouponpricer.hpp.
Referenced by capletRate(), floorletRate(), initialize(), optionletPrice(), and swapletPrice().
Real QuantLib::YoYInflationCouponPricer::gearing_ [protected]
Definition at line 121 of file inflationcouponpricer.hpp.
Referenced by capletPrice(), floorletPrice(), initialize(), swapletPrice(), and swapletRate().
Spread QuantLib::YoYInflationCouponPricer::spread_ [protected]
Definition at line 122 of file inflationcouponpricer.hpp.
Referenced by initialize(), and swapletRate().
Real QuantLib::YoYInflationCouponPricer::spreadLegValue_ [protected]
Definition at line 124 of file inflationcouponpricer.hpp.
Referenced by initialize(), and swapletPrice().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/inflationcouponpricer.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/inflationcouponpricer.cpp