QuantLib: QuantLib::HaltonRsg Class Reference
QuantLib::HaltonRsg Class Reference
Halton low-discrepancy sequence generator.
#include <haltonrsg.hpp>
Public Types
typedef Sample< std::vector
< Real > > sample_type
Public Member Functions
HaltonRsg (Size dimensionality, unsigned long seed=0, bool randomStart=true, bool randomShift=false)
const sample_type & nextSequence () const
const sample_type & lastSequence () const
Size dimension () const
Private Attributes
Size dimensionality_
unsigned long sequenceCounter_
sample_type sequence_
std::vector< unsigned long > randomStart_
std::vector< Real > randomShift_
Detailed Description
Halton low-discrepancy sequence generator.
Halton algorithm for low-discrepancy sequence. For more details see chapter 8, paragraph 2 of "Monte Carlo Methods in Finance", by Peter Jäckel
Test:
the correctness of the returned values is tested by reproducing known good values.
the correctness of the returned values is tested by checking their discrepancy against known good values.
Definition at line 43 of file haltonrsg.hpp.
Member Typedef Documentation
typedef Sample<std::vector<Real> > QuantLib::HaltonRsg::sample_type
Definition at line 45 of file haltonrsg.hpp.
Constructor & Destructor Documentation
QuantLib::HaltonRsg::HaltonRsg (Size dimensionality, unsigned long seed = 0, bool randomStart = true, bool randomShift = false)
Definition at line 36 of file haltonrsg.cpp.
References dimensionality_, QuantLib::RandomSequenceGenerator< RNG >::nextInt32Sequence(), QuantLib::RandomSequenceGenerator< RNG >::nextSequence(), QL_REQUIRE, randomShift_, randomStart_, and QuantLib::Sample< T >::value.
    : dimensionality_(dimensionality), sequenceCounter_(0),
      sequence_(std::vector<Real> (dimensionality), 1.0),
      randomStart_(dimensionality, 0UL),
      randomShift_(dimensionality, 0.0) {
        QL_REQUIRE(dimensionality>0,
                   "dimensionality must be greater than 0");
        if (randomStart || randomShift) {
            RandomSequenceGenerator<MersenneTwisterUniformRng>
                uniformRsg(dimensionality_, seed);
            if (randomStart)
                randomStart_ = uniformRsg.nextInt32Sequence();
            if (randomShift)
                randomShift_ = uniformRsg.nextSequence().value;
        }
    }
Member Function Documentation
Size QuantLib::HaltonRsg::dimension () const [inline]
Definition at line 54 of file haltonrsg.hpp.
References dimensionality_.
{return dimensionality_;}
const sample_type& QuantLib::HaltonRsg::lastSequence () const [inline]
Definition at line 51 of file haltonrsg.hpp.
References sequence_.
{
            return sequence_;
        }
const HaltonRsg::sample_type & QuantLib::HaltonRsg::nextSequence () const
Definition at line 57 of file haltonrsg.cpp.
References anonymous_namespace{marketmodel.cpp}::b, dimensionality_, anonymous_namespace{interpolations.cpp}::f(), QuantLib::detail::get(), randomShift_, randomStart_, sequence_, sequenceCounter_, and QuantLib::Sample< T >::value.
Referenced by LowDiscrepancyTest::testHalton().
{
        ++sequenceCounter_;
        unsigned long b, k;
        double f, h;
        for (Size i=0; i<dimensionality_; ++i) {
            h = 0.0;
            b = PrimeNumbers::get(i);
            f = 1.0;
            k = sequenceCounter_+randomStart_[i];
            while (k) {
                f /= b;
                h += (k%b)*f;
                k /= b;
            }
            sequence_.value[i] = h+randomShift_[i];
            sequence_.value[i] -= long(sequence_.value[i]);
        }
        return sequence_;
    }
Member Data Documentation
Size QuantLib::HaltonRsg::dimensionality_ [private]
Definition at line 56 of file haltonrsg.hpp.
Referenced by dimension(), HaltonRsg(), and nextSequence().
std::vector<Real> QuantLib::HaltonRsg::randomShift_ [private]
Definition at line 60 of file haltonrsg.hpp.
Referenced by HaltonRsg(), and nextSequence().
std::vector<unsigned long> QuantLib::HaltonRsg::randomStart_ [private]
Definition at line 59 of file haltonrsg.hpp.
Referenced by HaltonRsg(), and nextSequence().
sample_type QuantLib::HaltonRsg::sequence_ [mutable, private]
Definition at line 58 of file haltonrsg.hpp.
Referenced by lastSequence(), and nextSequence().
unsigned long QuantLib::HaltonRsg::sequenceCounter_ [mutable, private]
Definition at line 57 of file haltonrsg.hpp.
Referenced by nextSequence().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/randomnumbers/haltonrsg.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/math/randomnumbers/haltonrsg.cpp