QuantLib: QuantLib::BMASwapRateHelper Class Reference
QuantLib::BMASwapRateHelper Class Reference
Rate helper for bootstrapping over BMA swap rates.
#include <ratehelpers.hpp>
Public Member Functions
BMASwapRateHelper (const Handle< Quote > &liborFraction, const Period &tenor, Natural settlementDays, const Calendar &calendar, const Period &bmaPeriod, BusinessDayConvention bmaConvention, const DayCounter &bmaDayCount, const boost::shared_ptr< BMAIndex > &bmaIndex, const boost::shared_ptr< IborIndex > &index)
RateHelper interface
Real impliedQuote () const
void setTermStructure (YieldTermStructure *)
Visitability
void accept (AcyclicVisitor &)
Protected Member Functions
void initializeDates ()
Protected Attributes
Period tenor_
Natural settlementDays_
Calendar calendar_
Period bmaPeriod_
BusinessDayConvention bmaConvention_
DayCounter bmaDayCount_
boost::shared_ptr< BMAIndex > bmaIndex_
boost::shared_ptr< IborIndex > iborIndex_
boost::shared_ptr< BMASwap > swap_
RelinkableHandle
< YieldTermStructure > termStructureHandle_
Detailed Description
Rate helper for bootstrapping over BMA swap rates.
Definition at line 280 of file ratehelpers.hpp.
Constructor & Destructor Documentation
QuantLib::BMASwapRateHelper::BMASwapRateHelper (const Handle< Quote > & liborFraction, const Period & tenor, Natural settlementDays, const Calendar & calendar, const Period & bmaPeriod, BusinessDayConvention bmaConvention, const DayCounter & bmaDayCount, const boost::shared_ptr< BMAIndex > & bmaIndex, const boost::shared_ptr< IborIndex > & index)
Definition at line 629 of file ratehelpers.cpp.
References bmaIndex_, iborIndex_, initializeDates(), and QuantLib::Observer::registerWith().
    : RelativeDateRateHelper(liborFraction),
      tenor_(tenor), settlementDays_(settlementDays),
      calendar_(calendar),
      bmaPeriod_(bmaPeriod),
      bmaConvention_(bmaConvention),
      bmaDayCount_(bmaDayCount),
      bmaIndex_(bmaIndex),
      iborIndex_(iborIndex) {
        registerWith(iborIndex_);
        registerWith(bmaIndex_);
        initializeDates();
    }
Member Function Documentation
void QuantLib::BMASwapRateHelper::accept (AcyclicVisitor & v) [virtual]
Reimplemented from QuantLib::BootstrapHelper< TS >.
Definition at line 716 of file ratehelpers.cpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Visitor< T >::visit().
{
        Visitor<BMASwapRateHelper>* v1 =
            dynamic_cast<Visitor<BMASwapRateHelper>*>(&v);
        if (v1 != 0)
            v1->visit(*this);
        else
            RateHelper::accept(v);
    }
Real QuantLib::BMASwapRateHelper::impliedQuote () const [virtual]
Implements QuantLib::BootstrapHelper< TS >.
Definition at line 709 of file ratehelpers.cpp.
References QL_REQUIRE, swap_, and QuantLib::BootstrapHelper< TS >::termStructure_.
{
        QL_REQUIRE(termStructure_ != 0, "term structure not set");
        // we didn't register as observers - force calculation
        swap_->recalculate();
        return swap_->fairLiborFraction();
    }
void QuantLib::BMASwapRateHelper::initializeDates () [protected, virtual]
Implements QuantLib::RelativeDateBootstrapHelper< TS >.
Definition at line 654 of file ratehelpers.cpp.
References QuantLib::Calendar::adjust(), QuantLib::Calendar::advance(), QuantLib::MakeSchedule::backwards(), bmaConvention_, bmaDayCount_, bmaIndex_, bmaPeriod_, calendar_, anonymous_namespace{marketmodel.cpp}::d, QuantLib::Days, QuantLib::BootstrapHelper< TS >::earliestDate_, QuantLib::RelativeDateBootstrapHelper< TS >::evaluationDate_, QuantLib::Following, QuantLib::MakeSchedule::from(), iborIndex_, QuantLib::BootstrapHelper< TS >::latestDate_, QuantLib::anonymous_namespace{bmaindex.cpp}::nextWednesday(), QuantLib::BMASwap::Payer, settlementDays_, swap_, tenor_, termStructureHandle_, QuantLib::MakeSchedule::to(), QuantLib::Date::weekday(), QuantLib::MakeSchedule::withCalendar(), and QuantLib::MakeSchedule::withTenor().
Referenced by BMASwapRateHelper().
{
        earliestDate_ = calendar_.advance(evaluationDate_,
                                          settlementDays_*Days,
                                          Following);
        Date maturity = earliestDate_ + tenor_;
        // dummy BMA index with curve/swap arguments
        shared_ptr<BMAIndex> clonedIndex(new BMAIndex(termStructureHandle_));
        Schedule bmaSchedule =
            MakeSchedule().from(earliestDate_).to(maturity)
                          .withTenor(bmaPeriod_)
                          .withCalendar(bmaIndex_->fixingCalendar())
                          .withConvention(bmaConvention_)
                          .backwards();
        Schedule liborSchedule =
            MakeSchedule().from(earliestDate_).to(maturity)
                          .withTenor(iborIndex_->tenor())
                          .withCalendar(iborIndex_->fixingCalendar())
                          .withConvention(iborIndex_->businessDayConvention())
                          .endOfMonth(iborIndex_->endOfMonth())
                          .backwards();
        swap_ = shared_ptr<BMASwap>(new BMASwap(BMASwap::Payer, 100.0,
                                                liborSchedule,
                                                0.75, // arbitrary
                                                0.0,
                                                iborIndex_,
                                                iborIndex_->dayCounter(),
                                                bmaSchedule,
                                                clonedIndex,
                                                bmaDayCount_));
        swap_->setPricingEngine(shared_ptr<PricingEngine>(new
            DiscountingSwapEngine(iborIndex_->forwardingTermStructure())));
        Date d = calendar_.adjust(swap_->maturityDate(), Following);
        Weekday w = d.weekday();
        Date nextWednesday = (w >= 4) ?
            d + (11 - w) * Days :
            d + (4 - w) * Days;
        latestDate_ = clonedIndex->valueDate(
                         clonedIndex->fixingCalendar().adjust(nextWednesday));
    }
void QuantLib::BMASwapRateHelper::setTermStructure (YieldTermStructure * t)
Definition at line 700 of file ratehelpers.cpp.
References QuantLib::RelinkableHandle< T >::linkTo(), QuantLib::anonymous_namespace{riskyassetswap.cpp}::no_deletion(), and termStructureHandle_.
{
        // do not set the relinkable handle as an observer -
        // force recalculation when needed
        termStructureHandle_.linkTo(
                         shared_ptr<YieldTermStructure>(t,no_deletion),
                         false);
        RelativeDateRateHelper::setTermStructure(t);
    }
Member Data Documentation
BusinessDayConvention QuantLib::BMASwapRateHelper::bmaConvention_ [protected]
Definition at line 308 of file ratehelpers.hpp.
Referenced by initializeDates().
DayCounter QuantLib::BMASwapRateHelper::bmaDayCount_ [protected]
Definition at line 309 of file ratehelpers.hpp.
Referenced by initializeDates().
boost::shared_ptr<BMAIndex> QuantLib::BMASwapRateHelper::bmaIndex_ [protected]
Definition at line 310 of file ratehelpers.hpp.
Referenced by BMASwapRateHelper(), and initializeDates().
Period QuantLib::BMASwapRateHelper::bmaPeriod_ [protected]
Definition at line 307 of file ratehelpers.hpp.
Referenced by initializeDates().
Calendar QuantLib::BMASwapRateHelper::calendar_ [protected]
Definition at line 306 of file ratehelpers.hpp.
Referenced by initializeDates().
boost::shared_ptr<IborIndex> QuantLib::BMASwapRateHelper::iborIndex_ [protected]
Definition at line 311 of file ratehelpers.hpp.
Referenced by BMASwapRateHelper(), and initializeDates().
Natural QuantLib::BMASwapRateHelper::settlementDays_ [protected]
Definition at line 305 of file ratehelpers.hpp.
Referenced by initializeDates().
boost::shared_ptr<BMASwap> QuantLib::BMASwapRateHelper::swap_ [protected]
Definition at line 313 of file ratehelpers.hpp.
Referenced by impliedQuote(), and initializeDates().
Period QuantLib::BMASwapRateHelper::tenor_ [protected]
Definition at line 304 of file ratehelpers.hpp.
Referenced by initializeDates().
RelinkableHandle<YieldTermStructure> QuantLib::BMASwapRateHelper::termStructureHandle_ [protected]
Definition at line 314 of file ratehelpers.hpp.
Referenced by initializeDates(), and setTermStructure().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/yield/ratehelpers.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/yield/ratehelpers.cpp