QuantLib: QuantLib::MarketModelComposite Class Reference
QuantLib::MarketModelComposite Class Reference
Composition of two or more market-model products.
#include <compositeproduct.hpp>
Classes
struct SubProduct
Public Member Functions
MarketModelComposite ()
MarketModelMultiProduct interface
const EvolutionDescription & evolution () const
std::vector< Size > suggestedNumeraires () const
std::vector< Time > possibleCashFlowTimes () const
void reset ()
during simulation put product at start of path
Composite facilities
void add (const Clone< MarketModelMultiProduct > &, Real multiplier=1.0)
void subtract (const Clone< MarketModelMultiProduct > &, Real multiplier=1.0)
void finalize ()
Size size () const
const MarketModelMultiProduct & item (Size i) const
MarketModelMultiProduct & item (Size i)
Real multiplier (Size i) const
Protected Types
typedef std::vector
< SubProduct >::iterator iterator
typedef std::vector
< SubProduct >::const_iterator const_iterator
Protected Attributes
std::vector< SubProduct > components_
std::vector< Time > rateTimes_
std::vector< Time > evolutionTimes_
EvolutionDescription evolution_
bool finalized_
Size currentIndex_
std::vector< Time > cashflowTimes_
std::vector< std::vector< Time > > allEvolutionTimes_
std::vector< std::valarray
< bool > > isInSubset_
Detailed Description
Composition of two or more market-model products.
Instances of this class build a market-model product by composing one or more subproducts.
Precondition:
All subproducts must have the same rate times.
Definition at line 36 of file compositeproduct.hpp.
Member Typedef Documentation
typedef std::vector<SubProduct>::const_iterator QuantLib::MarketModelComposite::const_iterator [protected]
Definition at line 70 of file compositeproduct.hpp.
typedef std::vector<SubProduct>::iterator QuantLib::MarketModelComposite::iterator [protected]
Definition at line 69 of file compositeproduct.hpp.
Constructor & Destructor Documentation
QuantLib::MarketModelComposite::MarketModelComposite ()
Definition at line 25 of file compositeproduct.cpp.
    : finalized_(false) {}
Member Function Documentation
void QuantLib::MarketModelComposite::add (const Clone< MarketModelMultiProduct > & product, Real multiplier = 1.0)
Definition at line 53 of file compositeproduct.cpp.
References allEvolutionTimes_, components_, anonymous_namespace{marketmodel.cpp}::d, QuantLib::MarketModelMultiProduct::evolution(), QuantLib::EvolutionDescription::evolutionTimes(), finalized_, multiplier(), QL_REQUIRE, and QuantLib::EvolutionDescription::rateTimes().
Referenced by addCoinitialSwaps(), addCoterminalSwapsAndSwaptions(), addForwards(), addOptionLets(), subtract(), MarketModelTest::testCallableSwapAnderson(), MarketModelTest::testCallableSwapLS(), MarketModelTest::testCallableSwapNaif(), MarketModelTest::testInverseFloater(), MarketModelCmsTest::testMultiStepCmSwapsAndSwaptions(), MarketModelSmmTest::testMultiStepCoterminalSwapsAndSwaptions(), MarketModelTest::testOneStepForwardsAndOptionlets(), MarketModelTest::testOneStepNormalForwardsAndOptionlets(), MarketModelTest::testStochVolForwardsAndOptionlets(), and QuantLib::UpperBoundEngine::UpperBoundEngine().
{
        QL_REQUIRE(!finalized_, "product already finalized");
        EvolutionDescription d = product->evolution();
        if (!components_.empty()) {
            // enforce preconditions
            EvolutionDescription d1 =
                components_.front().product->evolution();
            const std::vector<Time>& rateTimes1 = d1.rateTimes();
            const std::vector<Time>& rateTimes2 = d.rateTimes();
            QL_REQUIRE(rateTimes1.size() == rateTimes2.size() &&
                       std::equal(rateTimes1.begin(), rateTimes1.end(),
                                  rateTimes2.begin()),
                       "incompatible rate times");
        }
        components_.push_back(SubProduct());
        components_.back().product = product;
        components_.back().multiplier = multiplier;
        components_.back().done = false;
        allEvolutionTimes_.push_back(d.evolutionTimes());
    }
const EvolutionDescription & QuantLib::MarketModelComposite::evolution () const [virtual]
Implements QuantLib::MarketModelMultiProduct.
Definition at line 28 of file compositeproduct.cpp.
References evolution_, finalized_, and QL_REQUIRE.
Referenced by addCoterminalSwapsAndSwaptions(), MarketModelTest::testInverseFloater(), MarketModelCmsTest::testMultiStepCmSwapsAndSwaptions(), MarketModelSmmTest::testMultiStepCoterminalSwapsAndSwaptions(), MarketModelTest::testOneStepForwardsAndOptionlets(), MarketModelTest::testOneStepNormalForwardsAndOptionlets(), MarketModelTest::testStochVolForwardsAndOptionlets(), and QuantLib::UpperBoundEngine::UpperBoundEngine().
{
        QL_REQUIRE(finalized_, "composite not finalized");
        return evolution_;
    }
void QuantLib::MarketModelComposite::finalize ()
Definition at line 82 of file compositeproduct.cpp.
References allEvolutionTimes_, cashflowTimes_, components_, anonymous_namespace{marketmodel.cpp}::d, evolution_, evolutionTimes_, finalized_, isInSubset_, QuantLib::mergeTimes(), QL_REQUIRE, and rateTimes_.
Referenced by addCoterminalSwapsAndSwaptions(), MarketModelTest::testAllMultiStepProducts(), MarketModelTest::testCallableSwapAnderson(), MarketModelTest::testCallableSwapLS(), MarketModelTest::testCallableSwapNaif(), MarketModelTest::testInverseFloater(), MarketModelCmsTest::testMultiStepCmSwapsAndSwaptions(), MarketModelSmmTest::testMultiStepCoterminalSwapsAndSwaptions(), MarketModelTest::testOneStepForwardsAndOptionlets(), MarketModelTest::testOneStepNormalForwardsAndOptionlets(), MarketModelTest::testStochVolForwardsAndOptionlets(), and QuantLib::UpperBoundEngine::UpperBoundEngine().
{
        QL_REQUIRE(!finalized_, "product already finalized");
        QL_REQUIRE(!components_.empty(), "no sub-product provided");
        // fetch the rate times from the first subproduct (we checked
        // they're all the same)
        EvolutionDescription description =
            components_.front().product->evolution();
        rateTimes_ = description.rateTimes();
        mergeTimes(allEvolutionTimes_, evolutionTimes_, isInSubset_);
        std::vector<Time> allCashflowTimes;
        // now, for each subproduct...
        iterator i;
        for (i=components_.begin(); i!=components_.end(); ++i) {
            EvolutionDescription d = i->product->evolution();
            // ...collect all possible cash-flow times...
            const std::vector<Time>& cashflowTimes =
                i->product->possibleCashFlowTimes();
            allCashflowTimes.insert(allCashflowTimes.end(),
                                    cashflowTimes.begin(),
                                    cashflowTimes.end());
            // ...allocate working vectors...
            i->numberOfCashflows =
                std::vector<Size>(i->product->numberOfProducts());
            i->cashflows =
                std::vector<std::vector<CashFlow> >(
                     i->product->numberOfProducts(),
                     std::vector<CashFlow>(i->product
                                  ->maxNumberOfCashFlowsPerProductPerStep()));
        }
        // all information having been collected, we can sort and
        // compact the vector of all cash-flow times...
        std::sort(allCashflowTimes.begin(), allCashflowTimes.end());
        std::vector<Time>::iterator end = std::unique(allCashflowTimes.begin(),
                                                      allCashflowTimes.end());
        //std::copy(allCashflowTimes.begin(), end,
        //          std::back_inserter(cashflowTimes_));
        cashflowTimes_.insert(cashflowTimes_.end(),
                              allCashflowTimes.begin(), end);
        // ...and map each product's cash-flow time into the total vector.
        for (i=components_.begin(); i!=components_.end(); ++i) {
            const std::vector<Time>& productTimes =
                i->product->possibleCashFlowTimes();
            i->timeIndices = std::vector<Size>(productTimes.size());
            for (Size j=0; j<productTimes.size(); ++j) {
                i->timeIndices[j] =
                    std::find(cashflowTimes_.begin(), cashflowTimes_.end(),
                              productTimes[j]) - cashflowTimes_.begin();
            }
        }
        evolution_ = EvolutionDescription(rateTimes_, evolutionTimes_);
        // all done.
        finalized_ = true;
    }
const MarketModelMultiProduct & QuantLib::MarketModelComposite::item (Size i) const
Definition at line 147 of file compositeproduct.cpp.
References components_.
Referenced by QuantLib::UpperBoundEngine::singlePathValue().
{
        return *(components_.at(i).product);
    }
MarketModelMultiProduct & QuantLib::MarketModelComposite::item (Size i)
Definition at line 151 of file compositeproduct.cpp.
References components_.
{
        return *(components_.at(i).product);
    }
Real QuantLib::MarketModelComposite::multiplier (Size i) const
Definition at line 155 of file compositeproduct.cpp.
References components_.
Referenced by add().
{
        return components_.at(i).multiplier;
    }
std::vector< Time > QuantLib::MarketModelComposite::possibleCashFlowTimes () const [virtual]
Implements QuantLib::MarketModelMultiProduct.
Definition at line 38 of file compositeproduct.cpp.
References cashflowTimes_, finalized_, and QL_REQUIRE.
Referenced by QuantLib::UpperBoundEngine::UpperBoundEngine().
{
        QL_REQUIRE(finalized_, "composite not finalized");
        return cashflowTimes_;
    }
void QuantLib::MarketModelComposite::reset () [virtual]
during simulation put product at start of path
Implements QuantLib::MarketModelMultiProduct.
Definition at line 43 of file compositeproduct.cpp.
References components_, and currentIndex_.
Referenced by QuantLib::UpperBoundEngine::singlePathValue().
{
        for (iterator i=components_.begin(); i!=components_.end(); ++i) {
            i->product->reset();
            i->done = false;
        }
        currentIndex_ = 0;
    }
Size QuantLib::MarketModelComposite::size () const
Definition at line 143 of file compositeproduct.cpp.
References components_.
{
        return components_.size();
    }
void QuantLib::MarketModelComposite::subtract (const Clone< MarketModelMultiProduct > & product, Real multiplier = 1.0)
Definition at line 76 of file compositeproduct.cpp.
References add().
{
        add(product, -multiplier);
    }
std::vector< Size > QuantLib::MarketModelComposite::suggestedNumeraires () const [virtual]
Implements QuantLib::MarketModelMultiProduct.
Definition at line 33 of file compositeproduct.cpp.
References evolution_, finalized_, QL_REQUIRE, and QuantLib::terminalMeasure().
{
        QL_REQUIRE(finalized_, "composite not finalized");
        return terminalMeasure(evolution_);
    }
Member Data Documentation
std::vector<std::vector<Time> > QuantLib::MarketModelComposite::allEvolutionTimes_ [protected]
Definition at line 79 of file compositeproduct.hpp.
Referenced by add(), and finalize().
std::vector<Time> QuantLib::MarketModelComposite::cashflowTimes_ [protected]
Definition at line 78 of file compositeproduct.hpp.
Referenced by finalize(), and possibleCashFlowTimes().
std::vector<SubProduct> QuantLib::MarketModelComposite::components_ [protected]
Definition at line 68 of file compositeproduct.hpp.
Referenced by add(), finalize(), item(), QuantLib::MultiProductComposite::maxNumberOfCashFlowsPerProductPerStep(), QuantLib::SingleProductComposite::maxNumberOfCashFlowsPerProductPerStep(), multiplier(), QuantLib::MultiProductComposite::nextTimeStep(), QuantLib::SingleProductComposite::nextTimeStep(), QuantLib::MultiProductComposite::numberOfProducts(), reset(), and size().
Size QuantLib::MarketModelComposite::currentIndex_ [protected]
Definition at line 77 of file compositeproduct.hpp.
Referenced by QuantLib::MultiProductComposite::nextTimeStep(), QuantLib::SingleProductComposite::nextTimeStep(), and reset().
EvolutionDescription QuantLib::MarketModelComposite::evolution_ [protected]
Definition at line 74 of file compositeproduct.hpp.
Referenced by evolution(), finalize(), and suggestedNumeraires().
std::vector<Time> QuantLib::MarketModelComposite::evolutionTimes_ [protected]
Definition at line 73 of file compositeproduct.hpp.
Referenced by finalize().
bool QuantLib::MarketModelComposite::finalized_ [protected]
Definition at line 76 of file compositeproduct.hpp.
Referenced by add(), evolution(), finalize(), QuantLib::SingleProductComposite::nextTimeStep(), QuantLib::MultiProductComposite::nextTimeStep(), possibleCashFlowTimes(), and suggestedNumeraires().
std::vector<std::valarray<bool> > QuantLib::MarketModelComposite::isInSubset_ [protected]
Definition at line 80 of file compositeproduct.hpp.
Referenced by finalize(), QuantLib::SingleProductComposite::nextTimeStep(), and QuantLib::MultiProductComposite::nextTimeStep().
std::vector<Time> QuantLib::MarketModelComposite::rateTimes_ [protected]
Definition at line 72 of file compositeproduct.hpp.
Referenced by finalize().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/products/compositeproduct.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/products/compositeproduct.cpp