QuantLib: QuantLib::FdmExtOUJumpModelInnerValue Class Reference
QuantLib::FdmExtOUJumpModelInnerValue Class Reference
#include <fdmextoujumpmodelinnervalue.hpp>
Public Types
typedef std::vector< std::pair
< Time, Real > > Shape
Public Member Functions
FdmExtOUJumpModelInnerValue (const boost::shared_ptr< Payoff > &payoff, const boost::shared_ptr< FdmMesher > &mesher, const boost::shared_ptr< Shape > &shape=boost::shared_ptr< Shape >())
Real innerValue (const FdmLinearOpIterator &iter, Time t)
Real avgInnerValue (const FdmLinearOpIterator &iter, Time t)
Private Attributes
const boost::shared_ptr< Payoff > payoff_
const boost::shared_ptr
< FdmMesher > mesher_
const boost::shared_ptr< Shape > shape_
Detailed Description
Definition at line 35 of file fdmextoujumpmodelinnervalue.hpp.
Member Typedef Documentation
typedef std::vector<std::pair<Time, Real> > QuantLib::FdmExtOUJumpModelInnerValue::Shape
Definition at line 37 of file fdmextoujumpmodelinnervalue.hpp.
Constructor & Destructor Documentation
QuantLib::FdmExtOUJumpModelInnerValue::FdmExtOUJumpModelInnerValue (const boost::shared_ptr< Payoff > & payoff, const boost::shared_ptr< FdmMesher > & mesher, const boost::shared_ptr< Shape > & shape = boost::shared_ptr<Shape>()) [inline]
Definition at line 39 of file fdmextoujumpmodelinnervalue.hpp.
        : payoff_(payoff),
          mesher_(mesher),
          shape_ (shape) { }
Member Function Documentation
Real QuantLib::FdmExtOUJumpModelInnerValue::avgInnerValue (const FdmLinearOpIterator & iter, Time t) [inline, virtual]
Implements QuantLib::FdmInnerValueCalculator.
Definition at line 58 of file fdmextoujumpmodelinnervalue.hpp.
References innerValue().
{
            return innerValue(iter, t);
        }
Real QuantLib::FdmExtOUJumpModelInnerValue::innerValue (const FdmLinearOpIterator & iter, Time t) [inline, virtual]
Implements QuantLib::FdmInnerValueCalculator.
Definition at line 47 of file fdmextoujumpmodelinnervalue.hpp.
References anonymous_namespace{interpolations.cpp}::f(), mesher_, payoff_, QL_EPSILON, and shape_.
Referenced by avgInnerValue().
{
            const Real x = mesher_->location(iter, 0);
            const Real y = mesher_->location(iter, 1);
            Real f = 0;
            if (shape_) {
                f = std::lower_bound(shape_->begin(), shape_->end(),
                   std::pair<Time, Real>(t-std::sqrt(QL_EPSILON), 0.0))->second;
            }
            return payoff_->operator()(std::exp(f + x + y));
        }
Member Data Documentation
const boost::shared_ptr<FdmMesher> QuantLib::FdmExtOUJumpModelInnerValue::mesher_ [private]
Definition at line 64 of file fdmextoujumpmodelinnervalue.hpp.
Referenced by innerValue().
const boost::shared_ptr<Payoff> QuantLib::FdmExtOUJumpModelInnerValue::payoff_ [private]
Definition at line 63 of file fdmextoujumpmodelinnervalue.hpp.
Referenced by innerValue().
const boost::shared_ptr<Shape> QuantLib::FdmExtOUJumpModelInnerValue::shape_ [private]
Definition at line 65 of file fdmextoujumpmodelinnervalue.hpp.
Referenced by innerValue().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/finitedifferences/fdmextoujumpmodelinnervalue.hpp