QuantLib: QuantLib::ZeroCouponInflationSwapHelper Class Reference
QuantLib::ZeroCouponInflationSwapHelper Class Reference
Zero-coupon inflation-swap bootstrap helper.
#include <inflationhelpers.hpp>
Public Member Functions
ZeroCouponInflationSwapHelper (const Handle< Quote > &quote, const Period &swapObsLag, const Date &maturity, const Calendar &calendar, BusinessDayConvention paymentConvention, const DayCounter &dayCounter, const boost::shared_ptr< ZeroInflationIndex > &zii)
void setTermStructure (ZeroInflationTermStructure *)
sets the term structure to be used for pricing
Real impliedQuote () const
Protected Attributes
Period swapObsLag_
Date maturity_
Calendar calendar_
BusinessDayConvention paymentConvention_
DayCounter dayCounter_
boost::shared_ptr
< ZeroInflationIndex > zii_
boost::shared_ptr
< ZeroCouponInflationSwap > zciis_
Detailed Description
Zero-coupon inflation-swap bootstrap helper.
Definition at line 36 of file inflationhelpers.hpp.
Constructor & Destructor Documentation
QuantLib::ZeroCouponInflationSwapHelper::ZeroCouponInflationSwapHelper (const Handle< Quote > & quote, const Period & swapObsLag, const Date & maturity, const Calendar & calendar, BusinessDayConvention paymentConvention, const DayCounter & dayCounter, const boost::shared_ptr< ZeroInflationIndex > & zii)
Definition at line 32 of file inflationhelpers.cpp.
References QuantLib::BootstrapHelper< ZeroInflationTermStructure >::earliestDate_, QuantLib::inflationPeriod(), QuantLib::Singleton< Settings >::instance(), QuantLib::BootstrapHelper< ZeroInflationTermStructure >::latestDate_, maturity_, QL_REQUIRE, QuantLib::Observer::registerWith(), swapObsLag_, and zii_.
    : BootstrapHelper<ZeroInflationTermStructure>(quote),
    swapObsLag_(swapObsLag), maturity_(maturity), calendar_(calendar),
    paymentConvention_(paymentConvention), dayCounter_(dayCounter),
    zii_(zii) {
        if (zii_->interpolated()) {
            // if interpolated then simple
            earliestDate_ = maturity_ - swapObsLag_;
            latestDate_ = maturity_ - swapObsLag_;
        } else {
            // but if NOT interpolated then the value is valid
            // for every day in an inflation period so you actually
            // get an extended validity, however for curve building
            // just put the first date because using that convention
            // for the base date throughout
            std::pair<Date,Date> limStart = inflationPeriod(maturity_ - swapObsLag_,
                                                            zii_->frequency());
            earliestDate_ = limStart.first;
            latestDate_ = limStart.first;
        }
        // check that the observation lag of the swap
        // is compatible with the availability lag of the index AND
        // it's interpolation (assuming the start day is spot)
        if (zii_->interpolated()) {
            Period pShift(zii_->frequency());
            QL_REQUIRE(swapObsLag_ - pShift > zii_->availabilityLag(),
                       "inconsistency between swap observation of index "
                       << swapObsLag_ <<
                       " index availability " << zii_->availabilityLag() <<
                       " index period " << pShift <<
                       " and index availability " << zii_->availabilityLag() <<
                       " need (obsLag-index period) > availLag");
        }
        registerWith(Settings::instance().evaluationDate());
    }
Member Function Documentation
Real QuantLib::ZeroCouponInflationSwapHelper::impliedQuote () const [virtual]
Implements QuantLib::BootstrapHelper< ZeroInflationTermStructure >.
Definition at line 78 of file inflationhelpers.cpp.
References zciis_.
{
        // what does the term structure imply?
        // in this case just the same value ... trivial case
        // (would not be so for an inflation-linked bond)
        zciis_->recalculate();
        return zciis_->fairRate();
    }
void QuantLib::ZeroCouponInflationSwapHelper::setTermStructure (ZeroInflationTermStructure *) [virtual]
sets the term structure to be used for pricing
Warning:
Being a pointer and not a shared_ptr, the term structure is not guaranteed to remain allocated for the whole life of the rate helper. It is responsibility of the programmer to ensure that the pointer remains valid. It is advised that this method is called only inside the term structure being bootstrapped, setting the pointer to this, i.e., the term structure itself.
Reimplemented from QuantLib::BootstrapHelper< ZeroInflationTermStructure >.
Definition at line 86 of file inflationhelpers.cpp.
References calendar_, dayCounter_, maturity_, QuantLib::anonymous_namespace{riskyassetswap.cpp}::no_deletion(), QuantLib::InflationTermStructure::nominalTermStructure(), QuantLib::ZeroCouponInflationSwap::Payer, paymentConvention_, QuantLib::BootstrapHelper< ZeroInflationTermStructure >::quote(), swapObsLag_, zciis_, and zii_.
{
        BootstrapHelper<ZeroInflationTermStructure>::setTermStructure(z);
        // set up a new ZCIIS
        // but this one does NOT own its inflation term structure
        const bool own = false;
        Rate K = quote()->value();
        // The effect of the new inflation term structure is
        // felt via the effect on the inflation index
        Handle<ZeroInflationTermStructure> zits(
            boost::shared_ptr<ZeroInflationTermStructure>(z,no_deletion), own);
        boost::shared_ptr<ZeroInflationIndex> new_zii = zii_->clone(zits);
        Real nominal = 1000000.0;   // has to be something but doesn't matter what
        Date start = z->nominalTermStructure()->referenceDate();
        zciis_.reset(new ZeroCouponInflationSwap(
                                ZeroCouponInflationSwap::Payer,
                                nominal, start, maturity_,
                                calendar_, paymentConvention_, dayCounter_, K, // fixed side & fixed rate
                                new_zii, swapObsLag_));
        // Because very simple instrument only takes
        // standard discounting swap engine.
        zciis_->setPricingEngine(boost::shared_ptr<PricingEngine>(
                new DiscountingSwapEngine(z->nominalTermStructure())));
    }
Member Data Documentation
Calendar QuantLib::ZeroCouponInflationSwapHelper::calendar_ [protected]
Definition at line 53 of file inflationhelpers.hpp.
Referenced by setTermStructure().
DayCounter QuantLib::ZeroCouponInflationSwapHelper::dayCounter_ [protected]
Definition at line 55 of file inflationhelpers.hpp.
Referenced by setTermStructure().
Date QuantLib::ZeroCouponInflationSwapHelper::maturity_ [protected]
Definition at line 52 of file inflationhelpers.hpp.
Referenced by setTermStructure(), and ZeroCouponInflationSwapHelper().
BusinessDayConvention QuantLib::ZeroCouponInflationSwapHelper::paymentConvention_ [protected]
Definition at line 54 of file inflationhelpers.hpp.
Referenced by setTermStructure().
Period QuantLib::ZeroCouponInflationSwapHelper::swapObsLag_ [protected]
Definition at line 51 of file inflationhelpers.hpp.
Referenced by setTermStructure(), and ZeroCouponInflationSwapHelper().
boost::shared_ptr<ZeroCouponInflationSwap> QuantLib::ZeroCouponInflationSwapHelper::zciis_ [protected]
Definition at line 57 of file inflationhelpers.hpp.
Referenced by impliedQuote(), and setTermStructure().
boost::shared_ptr<ZeroInflationIndex> QuantLib::ZeroCouponInflationSwapHelper::zii_ [protected]
Definition at line 56 of file inflationhelpers.hpp.
Referenced by setTermStructure(), and ZeroCouponInflationSwapHelper().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/inflation/inflationhelpers.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/inflation/inflationhelpers.cpp