QuantLib: QuantLib::StochasticProcess1D Class Reference
QuantLib::StochasticProcess1D Class Reference
1-dimensional stochastic process
#include <stochasticprocess.hpp>
Classes
class discretization
discretization of a 1-D stochastic process
Public Member Functions
1-D stochastic process interface
virtual Real x0 () const =0
returns the initial value of the state variable
virtual Real drift (Time t, Real x) const =0
returns the drift part of the equation, i.e. \(\mu(t, x_t) \)
virtual Real diffusion (Time t, Real x) const =0
returns the diffusion part of the equation, i.e. \(\sigma(t, x_t) \)
virtual Real expectation (Time t0, Real x0, Time dt) const
virtual Real stdDeviation (Time t0, Real x0, Time dt) const
virtual Real variance (Time t0, Real x0, Time dt) const
virtual Real evolve (Time t0, Real x0, Time dt, Real dw) const
virtual Real apply (Real x0, Real dx) const
Protected Member Functions
StochasticProcess1D ()
StochasticProcess1D (const boost::shared_ptr< discretization > &)
Protected Attributes
boost::shared_ptr< discretization > discretization_
Private Member Functions
Size size () const
returns the number of dimensions of the stochastic process
Disposable< Array > initialValues () const
returns the initial values of the state variables
Disposable< Array > drift (Time t, const Array &x) const
returns the drift part of the equation, i.e., \(\mu(t, \mathrm{x}_t) \)
Disposable< Matrix > diffusion (Time t, const Array &x) const
returns the diffusion part of the equation, i.e. \(\sigma(t, \mathrm{x}_t) \)
Disposable< Array > expectation (Time t0, const Array &x0, Time dt) const
Disposable< Matrix > stdDeviation (Time t0, const Array &x0, Time dt) const
Disposable< Matrix > covariance (Time t0, const Array &x0, Time dt) const
Disposable< Array > evolve (Time t0, const Array &x0, Time dt, const Array &dw) const
Disposable< Array > apply (const Array &x0, const Array &dx) const
Detailed Description
1-dimensional stochastic process
This class describes a stochastic process governed by
\[ dx_t = \mu(t, x_t)dt + \sigma(t, x_t)dW_t. \]
Definition at line 162 of file stochasticprocess.hpp.
Constructor & Destructor Documentation
QuantLib::StochasticProcess1D::StochasticProcess1D () [protected]
Definition at line 78 of file stochasticprocess.cpp.
{}
QuantLib::StochasticProcess1D::StochasticProcess1D (const boost::shared_ptr< discretization > & disc) [protected]
Definition at line 80 of file stochasticprocess.cpp.
    : discretization_(disc) {}
Member Function Documentation
Real QuantLib::StochasticProcess1D::apply (Real x0, Real dx) const [virtual]
applies a change to the asset value. By default, it returns \(x + \Delta x \).
Reimplemented in QuantLib::GeneralizedBlackScholesProcess, and QuantLib::Merton76Process.
Definition at line 101 of file stochasticprocess.cpp.
Referenced by apply(), evolve(), and expectation().
{
        return x0 + dx;
    }
Disposable< Array > QuantLib::StochasticProcess1D::apply (const Array & x0, const Array & dx) const [inline, private, virtual]
applies a change to the asset value. By default, it returns \(\mathrm{x} + \Delta \mathrm{x} \).
Reimplemented from QuantLib::StochasticProcess.
Definition at line 313 of file stochasticprocess.hpp.
References anonymous_namespace{marketmodel.cpp}::a, apply(), QL_REQUIRE, and QuantLib::Array::size().
{
        #if defined(QL_EXTRA_SAFETY_CHECKS)
        QL_REQUIRE(x0.size() == 1, "1-D array required");
        QL_REQUIRE(dx.size() == 1, "1-D array required");
        #endif
        Array a(1, apply(x0[0],dx[0]));
        return a;
    }
Disposable< Matrix > QuantLib::StochasticProcess1D::covariance (Time t0, const Array & x0, Time dt) const [inline, private, virtual]
returns the covariance \(V(\mathrm{x}_{t_0 + \Delta t} | \mathrm{x}_{t_0} = \mathrm{x}_0) \) of the process after a time interval \(\Delta t \) according to the given discretization. This method can be overridden in derived classes which want to hard-code a particular discretization.
Reimplemented from QuantLib::StochasticProcess.
Definition at line 293 of file stochasticprocess.hpp.
References QL_REQUIRE, QuantLib::Array::size(), and variance().
{
        #if defined(QL_EXTRA_SAFETY_CHECKS)
        QL_REQUIRE(x0.size() == 1, "1-D array required");
        #endif
        Matrix m(1, 1, variance(t0, x0[0], dt));
        return m;
    }
virtual Real QuantLib::StochasticProcess1D::diffusion (Time t, Real x) const [pure virtual]
returns the diffusion part of the equation, i.e. \(\sigma(t, x_t) \)
Implemented in QuantLib::CoxIngersollRoss::HelperProcess, QuantLib::HullWhiteForwardProcess, QuantLib::GeneralizedBlackScholesProcess, QuantLib::VarianceGammaProcess, QuantLib::ExtendedOrnsteinUhlenbeckProcess, QuantLib::GemanRoncoroniProcess, QuantLib::GeneralizedOrnsteinUhlenbeckProcess, QuantLib::Merton76Process, QuantLib::OrnsteinUhlenbeckProcess, QuantLib::SquareRootProcess, QuantLib::ExtendedBlackScholesMertonProcess, QuantLib::VegaStressedBlackScholesProcess, QuantLib::GeometricBrownianMotionProcess, and QuantLib::HullWhiteProcess.
Referenced by QuantLib::EndEulerDiscretization::diffusion(), QuantLib::EulerDiscretization::diffusion(), diffusion(), QuantLib::EndEulerDiscretization::variance(), and QuantLib::EulerDiscretization::variance().
Disposable< Matrix > QuantLib::StochasticProcess1D::diffusion (Time t, const Array & x) const [inline, private, virtual]
returns the diffusion part of the equation, i.e. \(\sigma(t, \mathrm{x}_t) \)
Implements QuantLib::StochasticProcess.
Definition at line 266 of file stochasticprocess.hpp.
References diffusion(), QL_REQUIRE, and QuantLib::Array::size().
{
        #if defined(QL_EXTRA_SAFETY_CHECKS)
        QL_REQUIRE(x.size() == 1, "1-D array required");
        #endif
        Matrix m(1, 1, diffusion(t, x[0]));
        return m;
    }
virtual Real QuantLib::StochasticProcess1D::drift (Time t, Real x) const [pure virtual]
returns the drift part of the equation, i.e. \(\mu(t, x_t) \)
Implemented in QuantLib::CoxIngersollRoss::HelperProcess, QuantLib::HullWhiteForwardProcess, QuantLib::GeneralizedBlackScholesProcess, QuantLib::VarianceGammaProcess, QuantLib::ExtendedOrnsteinUhlenbeckProcess, QuantLib::GemanRoncoroniProcess, QuantLib::GeneralizedOrnsteinUhlenbeckProcess, QuantLib::Merton76Process, QuantLib::SquareRootProcess, QuantLib::OrnsteinUhlenbeckProcess, QuantLib::ExtendedBlackScholesMertonProcess, QuantLib::GeometricBrownianMotionProcess, and QuantLib::HullWhiteProcess.
Referenced by QuantLib::EndEulerDiscretization::drift(), QuantLib::EulerDiscretization::drift(), and drift().
Disposable< Array > QuantLib::StochasticProcess1D::drift (Time t, const Array & x) const [inline, private, virtual]
returns the drift part of the equation, i.e., \(\mu(t, \mathrm{x}_t) \)
Implements QuantLib::StochasticProcess.
Definition at line 257 of file stochasticprocess.hpp.
References anonymous_namespace{marketmodel.cpp}::a, drift(), QL_REQUIRE, and QuantLib::Array::size().
{
        #if defined(QL_EXTRA_SAFETY_CHECKS)
        QL_REQUIRE(x.size() == 1, "1-D array required");
        #endif
        Array a(1, drift(t, x[0]));
        return a;
    }
Real QuantLib::StochasticProcess1D::evolve (Time t0, Real x0, Time dt, Real dw) const [virtual]
returns the asset value after a time interval \(\Delta t \) according to the given discretization. By default, it returns
\[ E(x_0,t_0,\Delta t) + S(x_0,t_0,\Delta t) \cdot \Delta w \]
where \(E \) is the expectation and \(S \) the standard deviation.
Reimplemented in QuantLib::GeneralizedBlackScholesProcess, QuantLib::GemanRoncoroniProcess, and QuantLib::ExtendedBlackScholesMertonProcess.
Definition at line 96 of file stochasticprocess.cpp.
References apply(), expectation(), and stdDeviation().
Referenced by evolve(), and SwingOptionTest::testExtendedOrnsteinUhlenbeckProcess().
{
        return apply(expectation(t0,x0,dt), stdDeviation(t0,x0,dt)*dw);
    }
Disposable< Array > QuantLib::StochasticProcess1D::evolve (Time t0, const Array & x0, Time dt, const Array & dw) const [inline, private, virtual]
returns the asset value after a time interval \(\Delta t \) according to the given discretization. By default, it returns
\[ E(\mathrm{x}_0,t_0,\Delta t) + S(\mathrm{x}_0,t_0,\Delta t) \cdot \Delta \mathrm{w} \]
where \(E \) is the expectation and \(S \) the standard deviation.
Reimplemented from QuantLib::StochasticProcess.
Definition at line 302 of file stochasticprocess.hpp.
References anonymous_namespace{marketmodel.cpp}::a, evolve(), QL_REQUIRE, and QuantLib::Array::size().
{
        #if defined(QL_EXTRA_SAFETY_CHECKS)
        QL_REQUIRE(x0.size() == 1, "1-D array required");
        QL_REQUIRE(dw.size() == 1, "1-D array required");
        #endif
        Array a(1, evolve(t0,x0[0],dt,dw[0]));
        return a;
    }
Real QuantLib::StochasticProcess1D::expectation (Time t0, Real x0, Time dt) const [virtual]
returns the expectation \(E(x_{t_0 + \Delta t} | x_{t_0} = x_0) \) of the process after a time interval \(\Delta t \) according to the given discretization. This method can be overridden in derived classes which want to hard-code a particular discretization.
Reimplemented in QuantLib::HullWhiteForwardProcess, QuantLib::GeneralizedBlackScholesProcess, QuantLib::ExtendedOrnsteinUhlenbeckProcess, QuantLib::GeneralizedOrnsteinUhlenbeckProcess, QuantLib::OrnsteinUhlenbeckProcess, and QuantLib::HullWhiteProcess.
Definition at line 84 of file stochasticprocess.cpp.
References apply(), and discretization_.
Referenced by evolve(), and expectation().
{
        return apply(x0, discretization_->drift(*this, t0, x0, dt));
    }
Disposable< Array > QuantLib::StochasticProcess1D::expectation (Time t0, const Array & x0, Time dt) const [inline, private, virtual]
returns the expectation \(E(\mathrm{x}_{t_0 + \Delta t} | \mathrm{x}_{t_0} = \mathrm{x}_0) \) of the process after a time interval \(\Delta t \) according to the given discretization. This method can be overridden in derived classes which want to hard-code a particular discretization.
Reimplemented from QuantLib::StochasticProcess.
Definition at line 275 of file stochasticprocess.hpp.
References anonymous_namespace{marketmodel.cpp}::a, expectation(), QL_REQUIRE, and QuantLib::Array::size().
{
        #if defined(QL_EXTRA_SAFETY_CHECKS)
        QL_REQUIRE(x0.size() == 1, "1-D array required");
        #endif
        Array a(1, expectation(t0, x0[0], dt));
        return a;
    }
Disposable< Array > QuantLib::StochasticProcess1D::initialValues () const [inline, private, virtual]
returns the initial values of the state variables
Implements QuantLib::StochasticProcess.
Definition at line 252 of file stochasticprocess.hpp.
References anonymous_namespace{marketmodel.cpp}::a, and x0().
{
        Array a(1, x0());
        return a;
    }
Size QuantLib::StochasticProcess1D::size () const [inline, private, virtual]
returns the number of dimensions of the stochastic process
Implements QuantLib::StochasticProcess.
Definition at line 248 of file stochasticprocess.hpp.
{
        return 1;
    }
Real QuantLib::StochasticProcess1D::stdDeviation (Time t0, Real x0, Time dt) const [virtual]
returns the standard deviation \(S(x_{t_0 + \Delta t} | x_{t_0} = x_0) \) of the process after a time interval \(\Delta t \) according to the given discretization. This method can be overridden in derived classes which want to hard-code a particular discretization.
Reimplemented in QuantLib::HullWhiteForwardProcess, QuantLib::ExtendedOrnsteinUhlenbeckProcess, QuantLib::GemanRoncoroniProcess, QuantLib::GeneralizedOrnsteinUhlenbeckProcess, QuantLib::OrnsteinUhlenbeckProcess, and QuantLib::HullWhiteProcess.
Definition at line 88 of file stochasticprocess.cpp.
References discretization_.
Referenced by QuantLib::ExtendedBlackScholesMertonProcess::evolve(), QuantLib::GeneralizedBlackScholesProcess::evolve(), evolve(), and stdDeviation().
{
        return discretization_->diffusion(*this, t0, x0, dt);
    }
Disposable< Matrix > QuantLib::StochasticProcess1D::stdDeviation (Time t0, const Array & x0, Time dt) const [inline, private, virtual]
returns the standard deviation \(S(\mathrm{x}_{t_0 + \Delta t} | \mathrm{x}_{t_0} = \mathrm{x}_0) \) of the process after a time interval \(\Delta t \) according to the given discretization. This method can be overridden in derived classes which want to hard-code a particular discretization.
Reimplemented from QuantLib::StochasticProcess.
Definition at line 284 of file stochasticprocess.hpp.
References QL_REQUIRE, QuantLib::Array::size(), and stdDeviation().
{
        #if defined(QL_EXTRA_SAFETY_CHECKS)
        QL_REQUIRE(x0.size() == 1, "1-D array required");
        #endif
        Matrix m(1, 1, stdDeviation(t0, x0[0], dt));
        return m;
    }
Real QuantLib::StochasticProcess1D::variance (Time t0, Real x0, Time dt) const [virtual]
returns the variance \(V(x_{t_0 + \Delta t} | x_{t_0} = x_0) \) of the process after a time interval \(\Delta t \) according to the given discretization. This method can be overridden in derived classes which want to hard-code a particular discretization.
Reimplemented in QuantLib::HullWhiteForwardProcess, QuantLib::OrnsteinUhlenbeckProcess, QuantLib::ExtendedOrnsteinUhlenbeckProcess, QuantLib::GeneralizedOrnsteinUhlenbeckProcess, and QuantLib::HullWhiteProcess.
Definition at line 92 of file stochasticprocess.cpp.
References discretization_.
Referenced by covariance().
{
        return discretization_->variance(*this, t0, x0, dt);
    }
virtual Real QuantLib::StochasticProcess1D::x0 () const [pure virtual]
returns the initial value of the state variable
Implemented in QuantLib::CoxIngersollRoss::HelperProcess, QuantLib::HullWhiteForwardProcess, QuantLib::OrnsteinUhlenbeckProcess, QuantLib::VarianceGammaProcess, QuantLib::GeneralizedBlackScholesProcess, QuantLib::GemanRoncoroniProcess, QuantLib::ExtendedOrnsteinUhlenbeckProcess, QuantLib::GeneralizedOrnsteinUhlenbeckProcess, QuantLib::Merton76Process, QuantLib::SquareRootProcess, QuantLib::GeometricBrownianMotionProcess, and QuantLib::HullWhiteProcess.
Referenced by initialValues().
Member Data Documentation
boost::shared_ptr<discretization> QuantLib::StochasticProcess1D::discretization_ [protected]
Reimplemented from QuantLib::StochasticProcess.
Reimplemented in QuantLib::ExtendedOrnsteinUhlenbeckProcess, and QuantLib::ExtendedBlackScholesMertonProcess.
Definition at line 227 of file stochasticprocess.hpp.
Referenced by QuantLib::GeneralizedBlackScholesProcess::evolve(), expectation(), stdDeviation(), and variance().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/stochasticprocess.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/stochasticprocess.cpp