QuantLib: QuantLib::AnalyticDividendEuropeanEngine Class Reference
QuantLib::AnalyticDividendEuropeanEngine Class Reference
Analytic pricing engine for European options with discrete dividends.
#include <analyticdividendeuropeanengine.hpp>
Public Member Functions
AnalyticDividendEuropeanEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > &)
void calculate () const
Private Attributes
boost::shared_ptr
< GeneralizedBlackScholesProcess > process_
Detailed Description
Analytic pricing engine for European options with discrete dividends.
Test:
the correctness of the returned greeks is tested by reproducing numerical derivatives.
Definition at line 38 of file analyticdividendeuropeanengine.hpp.
Constructor & Destructor Documentation
QuantLib::AnalyticDividendEuropeanEngine::AnalyticDividendEuropeanEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > & process)
Definition at line 26 of file analyticdividendeuropeanengine.cpp.
References process_, and QuantLib::Observer::registerWith().
    : process_(process) {
        registerWith(process_);
    }
Member Function Documentation
void QuantLib::AnalyticDividendEuropeanEngine::calculate () const [virtual]
Implements QuantLib::PricingEngine.
Definition at line 32 of file analyticdividendeuropeanengine.cpp.
References QuantLib::Annual, QuantLib::GenericEngine< DividendVanillaOption::arguments, DividendVanillaOption::results >::arguments_, QuantLib::DividendVanillaOption::arguments::cashFlow, QuantLib::Continuous, anonymous_namespace{marketmodel.cpp}::d, QuantLib::BlackCalculator::delta(), QuantLib::Exercise::European, QuantLib::BlackCalculator::gamma(), process_, QL_REQUIRE, QuantLib::GenericEngine< DividendVanillaOption::arguments, DividendVanillaOption::results >::results_, QuantLib::BlackCalculator::rho(), anonymous_namespace{quantlibbenchmark.cpp}::t, QuantLib::BlackCalculator::theta(), QuantLib::BlackCalculator::value(), QuantLib::Instrument::results::value, QuantLib::BlackCalculator::vega(), and QuantLib::DayCounter::yearFraction().
{
        QL_REQUIRE(arguments_.exercise->type() == Exercise::European,
                   "not an European option");
        boost::shared_ptr<StrikedTypePayoff> payoff =
            boost::dynamic_pointer_cast<StrikedTypePayoff>(arguments_.payoff);
        QL_REQUIRE(payoff, "non-striked payoff given");
        Date settlementDate = process_->riskFreeRate()->referenceDate();
        Real riskless = 0.0;
        Size i;
        for (i=0; i<arguments_.cashFlow.size(); i++)
            if (arguments_.cashFlow[i]->date() >= settlementDate)
                riskless += arguments_.cashFlow[i]->amount() *
                    process_->riskFreeRate()->discount(
                                              arguments_.cashFlow[i]->date());
        Real spot = process_->stateVariable()->value() - riskless;
        QL_REQUIRE(spot > 0.0,
                   "negative or null underlying after subtracting dividends");
        DiscountFactor dividendDiscount =
            process_->dividendYield()->discount(
                                             arguments_.exercise->lastDate());
        DiscountFactor riskFreeDiscount =
            process_->riskFreeRate()->discount(arguments_.exercise->lastDate());
        Real forwardPrice = spot * dividendDiscount / riskFreeDiscount;
        Real variance =
            process_->blackVolatility()->blackVariance(
                                              arguments_.exercise->lastDate(),
                                              payoff->strike());
        BlackCalculator black(payoff, forwardPrice, std::sqrt(variance),
                              riskFreeDiscount);
        results_.value = black.value();
        results_.delta = black.delta(spot);
        results_.gamma = black.gamma(spot);
        DayCounter rfdc  = process_->riskFreeRate()->dayCounter();
        DayCounter voldc = process_->blackVolatility()->dayCounter();
        Time t = voldc.yearFraction(
                                 process_->blackVolatility()->referenceDate(),
                                 arguments_.exercise->lastDate());
        results_.vega = black.vega(t);
        Real delta_theta = 0.0, delta_rho = 0.0;
        for (i = 0; i < arguments_.cashFlow.size(); i++) {
            Date d = arguments_.cashFlow[i]->date();
            if (d >= settlementDate) {
                delta_theta -= arguments_.cashFlow[i]->amount() *
                  process_->riskFreeRate()->zeroRate(d,rfdc,Continuous,Annual)*
                  process_->riskFreeRate()->discount(d);
                Time t = process_->time(d);
                delta_rho += arguments_.cashFlow[i]->amount() * t *
                             process_->riskFreeRate()->discount(t);
            }
        }
        t = process_->time(arguments_.exercise->lastDate());
        try {
            results_.theta = black.theta(spot, t) +
                             delta_theta * black.delta(spot);
        } catch (Error&) {
            results_.theta = Null<Real>();
        }
        results_.rho = black.rho(t) +
                       delta_rho * black.delta(spot);
    }
Member Data Documentation
boost::shared_ptr<GeneralizedBlackScholesProcess> QuantLib::AnalyticDividendEuropeanEngine::process_ [private]
Definition at line 45 of file analyticdividendeuropeanengine.hpp.
Referenced by AnalyticDividendEuropeanEngine(), and calculate().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/vanilla/analyticdividendeuropeanengine.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/vanilla/analyticdividendeuropeanengine.cpp