QuantLib: QuantLib::SeedGenerator Class Reference
QuantLib::SeedGenerator Class Reference
Random seed generator.
#include <seedgenerator.hpp>
Public Member Functions
unsigned long get ()
Private Member Functions
SeedGenerator ()
void initialize ()
Private Attributes
MersenneTwisterUniformRng rng_
Friends
class Singleton< SeedGenerator >
Detailed Description
Random seed generator.
Random number generator used for automatic generation of initialization seeds.
Test:
correct initialization of the single instance is tested.
Definition at line 38 of file seedgenerator.hpp.
Constructor & Destructor Documentation
QuantLib::SeedGenerator::SeedGenerator () [private]
Definition at line 29 of file seedgenerator.cpp.
References initialize().
                                 : rng_(42UL) {
        initialize();
    }
Member Function Documentation
unsigned long QuantLib::SeedGenerator::get ()
Definition at line 59 of file seedgenerator.cpp.
References QuantLib::MersenneTwisterUniformRng::nextInt32(), and rng_.
Referenced by QuantLib::LecuyerUniformRng::LecuyerUniformRng(), QuantLib::MersenneTwisterUniformRng::seedInitialization(), and LowDiscrepancyTest::testSeedGenerator().
{
        return rng_.nextInt32();
    }
void QuantLib::SeedGenerator::initialize () [private]
Definition at line 33 of file seedgenerator.cpp.
References QuantLib::MersenneTwisterUniformRng::nextInt32(), and rng_.
Referenced by SeedGenerator().
{
        // firstSeed is chosen based on clock() and used for the first rng
        unsigned long firstSeed = (unsigned long)(std::time(0));
        MersenneTwisterUniformRng first(firstSeed);
        // secondSeed is as random as it could be
        // feel free to suggest improvements
        unsigned long secondSeed = first.nextInt32();
        MersenneTwisterUniformRng second(secondSeed);
        // use the second rng to initialize the final one
        unsigned long skip = second.nextInt32() % 1000;
        std::vector<unsigned long> init(4);
        init[0]=second.nextInt32();
        init[1]=second.nextInt32();
        init[2]=second.nextInt32();
        init[3]=second.nextInt32();
        rng_ = MersenneTwisterUniformRng(init);
        for (unsigned long i=0; i<skip ; i++)
            rng_.nextInt32();
    }
Friends And Related Function Documentation
friend class Singleton< SeedGenerator > [friend]
Definition at line 39 of file seedgenerator.hpp.
Member Data Documentation
MersenneTwisterUniformRng QuantLib::SeedGenerator::rng_ [private]
Definition at line 45 of file seedgenerator.hpp.
Referenced by get(), and initialize().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/randomnumbers/seedgenerator.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/math/randomnumbers/seedgenerator.cpp