QuantLib: SurfaceTest Class Reference
SurfaceTest Class Reference
#include <surface.hpp>
Static Public Member Functions
static void testOutput ()
static
boost::unit_test_framework::test_suite * suite ()
Detailed Description
Definition at line 28 of file surface.hpp.
Member Function Documentation
test_suite * SurfaceTest::suite () [static]
Definition at line 47 of file surface.cpp.
References QUANTLIB_TEST_CASE, and testOutput().
Referenced by init_unit_test_suite().
{
    test_suite* suite = BOOST_TEST_SUITE("Surface tests");
    suite->add(QUANTLIB_TEST_CASE(&SurfaceTest::testOutput));
    return suite;
}
void SurfaceTest::testOutput () [static]
Definition at line 28 of file surface.cpp.
References QuantLib::RectangularDomain::includes(), and anonymous_namespace{gaussianquadratures.cpp}::tolerance.
Referenced by suite().
{
    BOOST_MESSAGE("Testing surface...");
    Real tolerance = 1e-5;
    TestSurface st;
    Real out = st(0, 0);
    Real expected = 0.0;
    if (std::fabs(out - expected) > tolerance)
        BOOST_FAIL("test surface incorrect value");
    RectangularDomain rect(0.0, 0.0, 1.0, 1.0);
    if (!rect.includes(0.5, 0.5))
        BOOST_FAIL("RectangularDomain fails 0.5 0.5");
    if (rect.includes(1.5, 0.5))
        BOOST_FAIL("RectangularDomain fails 1.5 0.5");
}
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/surface.hpp
/home/deriversatile/QuantLib/QuantLibQt/test-suite/surface.cpp