QuantLib: QuantLib::MarketModelPathwiseCashRebate Class Reference
QuantLib::MarketModelPathwiseCashRebate Class Reference
#include <pathwiseproductcashrebate.hpp>
Public Member Functions
MarketModelPathwiseCashRebate (const EvolutionDescription &evolution, const std::vector< Time > &paymentTimes, const Matrix &amounts, Size numberOfProducts)
virtual std::vector< Size > suggestedNumeraires () const
virtual const
EvolutionDescription & evolution () const
virtual std::vector< Time > possibleCashFlowTimes () const
virtual Size numberOfProducts () const
virtual Size maxNumberOfCashFlowsPerProductPerStep () const
virtual void reset ()
during simulation put product at start of path
virtual bool alreadyDeflated () const
virtual bool nextTimeStep (const CurveState &currentState, std::vector< Size > &numberCashFlowsThisStep, std::vector< std::vector< MarketModelPathwiseMultiProduct::CashFlow > > &cashFlowsGenerated)
return value indicates whether path is finished, TRUE means done
virtual std::auto_ptr
< MarketModelPathwiseMultiProduct > clone () const
returns a newly-allocated copy of itself
Private Attributes
EvolutionDescription evolution_
std::vector< Time > paymentTimes_
Matrix amounts_
Size numberOfProducts_
Size currentIndex_
Detailed Description
Swap for doing simple cash rebate. Fairly useless when used directly, but if we want to look a breakable swap it becomes useful.
Definition at line 42 of file pathwiseproductcashrebate.hpp.
Constructor & Destructor Documentation
QuantLib::MarketModelPathwiseCashRebate::MarketModelPathwiseCashRebate (const EvolutionDescription & evolution, const std::vector< Time > & paymentTimes, const Matrix & amounts, Size numberOfProducts)
Definition at line 33 of file pathwiseproductcashrebate.cpp.
References amounts_, QuantLib::checkIncreasingTimes(), QuantLib::Matrix::columns(), evolution_, QuantLib::EvolutionDescription::evolutionTimes(), numberOfProducts_, paymentTimes_, QL_REQUIRE, and QuantLib::Matrix::rows().
Referenced by clone().
    : evolution_(evolution), paymentTimes_(paymentTimes),
      amounts_(amounts), numberOfProducts_(numberOfProducts)
    {
        checkIncreasingTimes(paymentTimes);
        QL_REQUIRE(amounts_.rows() == numberOfProducts_,
                   "the number of rows in the matrix must equal "
                   "the number of products");
        QL_REQUIRE(amounts_.columns() == paymentTimes_.size(),
                   "the number of columns in the matrix must equal "
                   "the number of payment times");
        QL_REQUIRE(evolution_.evolutionTimes().size() == paymentTimes_.size(),
                   "the number of evolution times must equal "
                   "the number of payment times");
    }
Member Function Documentation
bool QuantLib::MarketModelPathwiseCashRebate::alreadyDeflated () const [virtual]
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 28 of file pathwiseproductcashrebate.cpp.
    {
        return false;
    }
std::auto_ptr< MarketModelPathwiseMultiProduct > QuantLib::MarketModelPathwiseCashRebate::clone () const [virtual]
returns a newly-allocated copy of itself
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 109 of file pathwiseproductcashrebate.cpp.
References MarketModelPathwiseCashRebate().
    {
        return std::auto_ptr<MarketModelPathwiseMultiProduct>(
                                            new MarketModelPathwiseCashRebate(*this));
    }
const EvolutionDescription & QuantLib::MarketModelPathwiseCashRebate::evolution () const [virtual]
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 83 of file pathwiseproductcashrebate.cpp.
References evolution_.
    {
        return evolution_;
    }
Size QuantLib::MarketModelPathwiseCashRebate::maxNumberOfCashFlowsPerProductPerStep () const [virtual]
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 67 of file pathwiseproductcashrebate.cpp.
    {
        return 1;
    }
bool QuantLib::MarketModelPathwiseCashRebate::nextTimeStep (const CurveState & currentState, std::vector< Size > & numberCashFlowsThisStep, std::vector< std::vector< MarketModelPathwiseMultiProduct::CashFlow > > & cashFlowsGenerated) [virtual]
return value indicates whether path is finished, TRUE means done
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 89 of file pathwiseproductcashrebate.cpp.
References amounts_, currentIndex_, evolution_, numberOfProducts_, and QuantLib::EvolutionDescription::numberOfRates().
    {
        for (Size i=0; i<numberOfProducts_; ++i)
        {
            numberCashFlowsThisStep[i] = 1;
            cashFlowsGenerated[i][0].timeIndex = currentIndex_;
            cashFlowsGenerated[i][0].amount[0] = amounts_[i][currentIndex_];
            for (Size k=1; k <= evolution_.numberOfRates(); ++k)
                 cashFlowsGenerated[i][0].amount[k] = 0.0;
        }
        ++currentIndex_;
        return true;
    }
Size QuantLib::MarketModelPathwiseCashRebate::numberOfProducts () const [virtual]
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 62 of file pathwiseproductcashrebate.cpp.
References numberOfProducts_.
    {
        return numberOfProducts_;
    }
std::vector< Time > QuantLib::MarketModelPathwiseCashRebate::possibleCashFlowTimes () const [virtual]
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 57 of file pathwiseproductcashrebate.cpp.
References paymentTimes_.
    {
        return paymentTimes_;
    }
void QuantLib::MarketModelPathwiseCashRebate::reset () [virtual]
during simulation put product at start of path
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 72 of file pathwiseproductcashrebate.cpp.
References currentIndex_.
    {
       currentIndex_=0;
    }
std::vector< Size > QuantLib::MarketModelPathwiseCashRebate::suggestedNumeraires () const [virtual]
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 78 of file pathwiseproductcashrebate.cpp.
References QL_FAIL.
    {
        QL_FAIL("not implemented (yet?)");
    }
Member Data Documentation
Matrix QuantLib::MarketModelPathwiseCashRebate::amounts_ [private]
Definition at line 70 of file pathwiseproductcashrebate.hpp.
Referenced by MarketModelPathwiseCashRebate(), and nextTimeStep().
Size QuantLib::MarketModelPathwiseCashRebate::currentIndex_ [private]
Definition at line 73 of file pathwiseproductcashrebate.hpp.
Referenced by nextTimeStep(), and reset().
EvolutionDescription QuantLib::MarketModelPathwiseCashRebate::evolution_ [private]
Definition at line 68 of file pathwiseproductcashrebate.hpp.
Referenced by evolution(), MarketModelPathwiseCashRebate(), and nextTimeStep().
Size QuantLib::MarketModelPathwiseCashRebate::numberOfProducts_ [private]
Definition at line 71 of file pathwiseproductcashrebate.hpp.
Referenced by MarketModelPathwiseCashRebate(), nextTimeStep(), and numberOfProducts().
std::vector<Time> QuantLib::MarketModelPathwiseCashRebate::paymentTimes_ [private]
Definition at line 69 of file pathwiseproductcashrebate.hpp.
Referenced by MarketModelPathwiseCashRebate(), and possibleCashFlowTimes().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/products/pathwise/pathwiseproductcashrebate.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/products/pathwise/pathwiseproductcashrebate.cpp