QuantLib: QuantLib::ZeroInflationTraits Class Reference
QuantLib::ZeroInflationTraits Class Reference
Bootstrap traits to use for PiecewiseZeroInflationCurve.
#include <inflationtraits.hpp>
Public Types
typedef BootstrapHelper
< ZeroInflationTermStructure > helper
Static Public Member Functions
static Date initialDate (const ZeroInflationTermStructure *t)
static Rate initialValue (const ZeroInflationTermStructure *t)
template<class C >
static Rate guess (Size i, const C *c, bool validData, Size)
template<class C >
static Rate minValueAfter (Size i, const C *c, bool validData, Size)
template<class C >
static Rate maxValueAfter (Size i, const C *c, bool validData, Size)
static void updateGuess (std::vector< Rate > &data, Rate level, Size i)
static Size maxIterations ()
Detailed Description
Bootstrap traits to use for PiecewiseZeroInflationCurve.
Definition at line 41 of file inflationtraits.hpp.
Member Typedef Documentation
typedef BootstrapHelper<ZeroInflationTermStructure> QuantLib::ZeroInflationTraits::helper
Definition at line 43 of file inflationtraits.hpp.
Member Function Documentation
template<class C > static Rate QuantLib::ZeroInflationTraits::guess (Size i, const C * c, bool validData, Size) [inline, static]
Definition at line 61 of file inflationtraits.hpp.
References QuantLib::detail::avgInflation.
        {
            if (validData) // previous iteration value
                return c->data()[i];
            if (i==1) // first pillar
                return detail::avgInflation;
            // could/should extrapolate
            return detail::avgInflation;
        }
static Date QuantLib::ZeroInflationTraits::initialDate (const ZeroInflationTermStructure * t) [inline, static]
Definition at line 46 of file inflationtraits.hpp.
References QuantLib::InflationTermStructure::frequency(), QuantLib::InflationTermStructure::indexIsInterpolated(), QuantLib::inflationPeriod(), QuantLib::InflationTermStructure::observationLag(), and QuantLib::TermStructure::referenceDate().
{
            if (t->indexIsInterpolated()) {
                return t->referenceDate() - t->observationLag();
            } else {
                return inflationPeriod(t->referenceDate() - t->observationLag(),
                                       t->frequency()).first;
            }
        }
static Rate QuantLib::ZeroInflationTraits::initialValue (const ZeroInflationTermStructure * t) [inline, static]
Definition at line 55 of file inflationtraits.hpp.
References QuantLib::InflationTermStructure::baseRate().
{
            return t->baseRate();
        }
static Size QuantLib::ZeroInflationTraits::maxIterations () [inline, static]
Definition at line 112 of file inflationtraits.hpp.
{ return 5; }
template<class C > static Rate QuantLib::ZeroInflationTraits::maxValueAfter (Size i, const C * c, bool validData, Size) [inline, static]
Definition at line 90 of file inflationtraits.hpp.
References QuantLib::detail::maxInflation.
        {
            if (validData) {
                Rate r = *(std::max_element(c->data().begin(), c->data().end()));
                return r<0.0 ? r/2.0 : r*2.0;
            }
            // no constraints.
            // We choose as max a value very unlikely to be exceeded.
            return detail::maxInflation;
        }
template<class C > static Rate QuantLib::ZeroInflationTraits::minValueAfter (Size i, const C * c, bool validData, Size) [inline, static]
Definition at line 78 of file inflationtraits.hpp.
References QuantLib::detail::maxInflation.
        {
            if (validData) {
                Rate r = *(std::min_element(c->data().begin(), c->data().end()));
                return r<0.0 ? r*2.0 : r/2.0;
            }
            return -detail::maxInflation;
        }
static void QuantLib::ZeroInflationTraits::updateGuess (std::vector< Rate > & data, Rate level, Size i) [inline, static]
Definition at line 105 of file inflationtraits.hpp.
{
            data[i] = level;
        }
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/inflation/inflationtraits.hpp