QuantLib: QuantLib::EulerDiscretization Class Reference
QuantLib::EulerDiscretization Class Reference
Euler discretization for stochastic processes.
#include <eulerdiscretization.hpp>
Public Member Functions
Disposable< Array > drift (const StochasticProcess &, Time t0, const Array &x0, Time dt) const
Real drift (const StochasticProcess1D &, Time t0, Real x0, Time dt) const
Disposable< Matrix > diffusion (const StochasticProcess &, Time t0, const Array &x0, Time dt) const
Real diffusion (const StochasticProcess1D &, Time t0, Real x0, Time dt) const
Disposable< Matrix > covariance (const StochasticProcess &, Time t0, const Array &x0, Time dt) const
Real variance (const StochasticProcess1D &, Time t0, Real x0, Time dt) const
Detailed Description
Euler discretization for stochastic processes.
Definition at line 33 of file eulerdiscretization.hpp.
Member Function Documentation
Disposable< Matrix > QuantLib::EulerDiscretization::covariance (const StochasticProcess & process, Time t0, const Array & x0, Time dt) const [virtual]
Returns an approximation of the covariance defined as \(\sigma(t_0, \mathbf{x}_0)^2 \Delta t \).
Implements QuantLib::StochasticProcess::discretization.
Definition at line 48 of file eulerdiscretization.cpp.
References QuantLib::StochasticProcess::diffusion(), QuantLib::anonymous_namespace{yieldtermstructure.cpp}::dt, anonymous_namespace{distributions.cpp}::sigma, and QuantLib::transpose().
{
        Matrix sigma = process.diffusion(t0, x0);
        Matrix result = sigma*transpose(sigma)*dt;
        return result;
    }
Disposable< Matrix > QuantLib::EulerDiscretization::diffusion (const StochasticProcess & process, Time t0, const Array & x0, Time dt) const [virtual]
Returns an approximation of the diffusion defined as \(\sigma(t_0, \mathbf{x}_0) \sqrt{\Delta t} \).
Implements QuantLib::StochasticProcess::discretization.
Definition at line 36 of file eulerdiscretization.cpp.
References QuantLib::StochasticProcess::diffusion().
{
        return process.diffusion(t0, x0) * std::sqrt(dt);
    }
Real QuantLib::EulerDiscretization::diffusion (const StochasticProcess1D & process, Time t0, Real x0, Time dt) const [virtual]
Returns an approximation of the diffusion defined as \(\sigma(t_0, x_0) \sqrt{\Delta t} \).
Implements QuantLib::StochasticProcess1D::discretization.
Definition at line 43 of file eulerdiscretization.cpp.
References QuantLib::StochasticProcess1D::diffusion().
{
        return process.diffusion(t0, x0) * std::sqrt(dt);
    }
Disposable< Array > QuantLib::EulerDiscretization::drift (const StochasticProcess & process, Time t0, const Array & x0, Time dt) const [virtual]
Returns an approximation of the drift defined as \(\mu(t_0, \mathbf{x}_0) \Delta t \).
Implements QuantLib::StochasticProcess::discretization.
Definition at line 24 of file eulerdiscretization.cpp.
References QuantLib::StochasticProcess::drift(), and QuantLib::anonymous_namespace{yieldtermstructure.cpp}::dt.
{
        return process.drift(t0, x0)*dt;
    }
Real QuantLib::EulerDiscretization::drift (const StochasticProcess1D & process, Time t0, Real x0, Time dt) const [virtual]
Returns an approximation of the drift defined as \(\mu(t_0, x_0) \Delta t \).
Implements QuantLib::StochasticProcess1D::discretization.
Definition at line 31 of file eulerdiscretization.cpp.
References QuantLib::StochasticProcess1D::drift(), and QuantLib::anonymous_namespace{yieldtermstructure.cpp}::dt.
{
        return process.drift(t0, x0)*dt;
    }
Real QuantLib::EulerDiscretization::variance (const StochasticProcess1D & process, Time t0, Real x0, Time dt) const [virtual]
Returns an approximation of the variance defined as \(\sigma(t_0, x_0)^2 \Delta t \).
Implements QuantLib::StochasticProcess1D::discretization.
Definition at line 57 of file eulerdiscretization.cpp.
References QuantLib::StochasticProcess1D::diffusion(), QuantLib::anonymous_namespace{yieldtermstructure.cpp}::dt, and anonymous_namespace{distributions.cpp}::sigma.
{
        Real sigma = process.diffusion(t0, x0);
        return sigma*sigma*dt;
    }
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/processes/eulerdiscretization.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/processes/eulerdiscretization.cpp