QuantLib: QuantLib::RandomizedLDS< LDS, PRS > Class Template Reference
QuantLib::RandomizedLDS< LDS, PRS > Class Template Reference
Randomized (random shift) low-discrepancy sequence.
#include <randomizedlds.hpp>
Public Types
typedef Sample< std::vector
< Real > > sample_type
Public Member Functions
RandomizedLDS (const LDS &ldsg, const PRS &prsg)
RandomizedLDS (const LDS &ldsg)
RandomizedLDS (Size dimensionality, BigNatural ldsSeed=0, BigNatural prsSeed=0)
const sample_type & nextSequence () const
returns next sample using a given randomizing vector
const sample_type & lastSequence () const
void nextRandomizer ()
Size dimension () const
Private Attributes
LDS ldsg_
LDS pristineldsg_
PRS prsg_
Size dimension_
sample_type x
sample_type randomizer_
Detailed Description
template<class LDS, class PRS = RandomSequenceGenerator<MersenneTwisterUniformRng>>
class QuantLib::RandomizedLDS< LDS, PRS >
Randomized (random shift) low-discrepancy sequence.
Random-shifts a uniform low-discrepancy sequence of dimension \(N \) by adding (modulo 1 for each coordinate) a pseudo-random uniform deviate in \((0, 1)^N. \) It is used for implementing Randomized Quasi Monte Carlo.
The uniform low discrepancy sequence is supplied by LDS; the uniform pseudo-random sequence is supplied by PRS.
Both class LDS and PRS must implement the following interface:
            LDS::sample_type LDS::nextSequence() const;
            Size LDS::dimension() const;
Precondition:
LDS and PRS must have the same dimension \(N \)
Warning:
Inverting LDS and PRS is possible, but it doesn't make sense.
Todo:
implement the other randomization algorithms
Test:
correct initialization is tested.
Definition at line 58 of file randomizedlds.hpp.
Member Typedef Documentation
template<class LDS, class PRS = RandomSequenceGenerator<MersenneTwisterUniformRng>> typedef Sample<std::vector<Real> > QuantLib::RandomizedLDS< LDS, PRS >::sample_type
Definition at line 60 of file randomizedlds.hpp.
Constructor & Destructor Documentation
template<class LDS , class PRS > QuantLib::RandomizedLDS< LDS, PRS >::RandomizedLDS (const LDS & ldsg, const PRS & prsg)
Definition at line 87 of file randomizedlds.hpp.
References QuantLib::RandomizedLDS< LDS, PRS >::dimension_, QuantLib::RandomizedLDS< LDS, PRS >::prsg_, QL_REQUIRE, and QuantLib::RandomizedLDS< LDS, PRS >::randomizer_.
    : ldsg_(ldsg), pristineldsg_(ldsg),
      prsg_(prsg), dimension_(ldsg_.dimension()),
      x(std::vector<Real> (dimension_), 1.0), randomizer_(std::vector<Real> (dimension_), 1.0) {
        QL_REQUIRE(prsg_.dimension()==dimension_,
                   "generator mismatch: "
                   << dimension_ << "-dim low discrepancy "
                   << "and " << prsg_.dimension() << "-dim pseudo random")
        randomizer_ = prsg_.nextSequence();
    }
template<class LDS , class PRS > QuantLib::RandomizedLDS< LDS, PRS >::RandomizedLDS (const LDS & ldsg)
Definition at line 102 of file randomizedlds.hpp.
References QuantLib::RandomizedLDS< LDS, PRS >::prsg_, and QuantLib::RandomizedLDS< LDS, PRS >::randomizer_.
    : ldsg_(ldsg), pristineldsg_(ldsg),
      prsg_(ldsg_.dimension()), dimension_(ldsg_.dimension()),
      x(std::vector<Real> (dimension_), 1.0), randomizer_(std::vector<Real> (dimension_), 1.0) {
        randomizer_ = prsg_.nextSequence();
    }
template<class LDS , class PRS > QuantLib::RandomizedLDS< LDS, PRS >::RandomizedLDS (Size dimensionality, BigNatural ldsSeed = 0, BigNatural prsSeed = 0)
Definition at line 112 of file randomizedlds.hpp.
References QuantLib::RandomizedLDS< LDS, PRS >::prsg_, and QuantLib::RandomizedLDS< LDS, PRS >::randomizer_.
    : ldsg_(dimensionality, ldsSeed), pristineldsg_(dimensionality, ldsSeed),
      prsg_(dimensionality, prsSeed), dimension_(dimensionality),
      x(std::vector<Real> (dimensionality), 1.0), randomizer_(std::vector<Real> (dimensionality), 1.0) {
        randomizer_ = prsg_.nextSequence();
    }
Member Function Documentation
template<class LDS, class PRS = RandomSequenceGenerator<MersenneTwisterUniformRng>> Size QuantLib::RandomizedLDS< LDS, PRS >::dimension () const [inline]
Definition at line 78 of file randomizedlds.hpp.
References QuantLib::RandomizedLDS< LDS, PRS >::dimension_.
{return dimension_;}
template<class LDS, class PRS = RandomSequenceGenerator<MersenneTwisterUniformRng>> const sample_type& QuantLib::RandomizedLDS< LDS, PRS >::lastSequence () const [inline]
Definition at line 69 of file randomizedlds.hpp.
References QuantLib::RandomizedLDS< LDS, PRS >::x.
Referenced by LowDiscrepancyTest::testRandomizedLowDiscrepancySequence().
{
            return x;
        }
template<class LDS, class PRS = RandomSequenceGenerator<MersenneTwisterUniformRng>> void QuantLib::RandomizedLDS< LDS, PRS >::nextRandomizer () [inline]
update the randomizing vector and re-initialize the low discrepancy generator
Definition at line 74 of file randomizedlds.hpp.
References QuantLib::RandomizedLDS< LDS, PRS >::ldsg_, QuantLib::RandomizedLDS< LDS, PRS >::pristineldsg_, QuantLib::RandomizedLDS< LDS, PRS >::prsg_, and QuantLib::RandomizedLDS< LDS, PRS >::randomizer_.
Referenced by anonymous_namespace{lowdiscrepancysequences.cpp}::testRandomizedLatticeRule(), and LowDiscrepancyTest::testRandomizedLowDiscrepancySequence().
{
            randomizer_ = prsg_.nextSequence();
            ldsg_ = pristineldsg_;
        }
template<class LDS , class PRS > const RandomizedLDS< LDS, PRS >::sample_type & QuantLib::RandomizedLDS< LDS, PRS >::nextSequence () const [inline]
returns next sample using a given randomizing vector
Definition at line 124 of file randomizedlds.hpp.
References QuantLib::Sample< T >::weight.
Referenced by anonymous_namespace{lowdiscrepancysequences.cpp}::testRandomizedLatticeRule(), and LowDiscrepancyTest::testRandomizedLowDiscrepancySequence().
{
    typename LDS::sample_type sample =
        ldsg_.nextSequence();
    x.weight = randomizer_.weight * sample.weight;
    for (Size i = 0; i < dimension_; i++) {
        x.value[i] =  randomizer_.value[i] + sample.value[i];
        if (x.value[i]>1.0)
            x.value[i] -= 1.0;
    }
    return x;
    }
Member Data Documentation
template<class LDS, class PRS = RandomSequenceGenerator<MersenneTwisterUniformRng>> Size QuantLib::RandomizedLDS< LDS, PRS >::dimension_ [private]
Definition at line 82 of file randomizedlds.hpp.
Referenced by QuantLib::RandomizedLDS< LDS, PRS >::dimension(), and QuantLib::RandomizedLDS< LDS, PRS >::RandomizedLDS().
template<class LDS, class PRS = RandomSequenceGenerator<MersenneTwisterUniformRng>> LDS QuantLib::RandomizedLDS< LDS, PRS >::ldsg_ [mutable, private]
Definition at line 80 of file randomizedlds.hpp.
Referenced by QuantLib::RandomizedLDS< LDS, PRS >::nextRandomizer().
template<class LDS, class PRS = RandomSequenceGenerator<MersenneTwisterUniformRng>> LDS QuantLib::RandomizedLDS< LDS, PRS >::pristineldsg_ [mutable, private]
Definition at line 80 of file randomizedlds.hpp.
Referenced by QuantLib::RandomizedLDS< LDS, PRS >::nextRandomizer().
template<class LDS, class PRS = RandomSequenceGenerator<MersenneTwisterUniformRng>> PRS QuantLib::RandomizedLDS< LDS, PRS >::prsg_ [private]
Definition at line 81 of file randomizedlds.hpp.
Referenced by QuantLib::RandomizedLDS< LDS, PRS >::nextRandomizer(), and QuantLib::RandomizedLDS< LDS, PRS >::RandomizedLDS().
template<class LDS, class PRS = RandomSequenceGenerator<MersenneTwisterUniformRng>> sample_type QuantLib::RandomizedLDS< LDS, PRS >::randomizer_ [mutable, private]
Definition at line 83 of file randomizedlds.hpp.
Referenced by QuantLib::RandomizedLDS< LDS, PRS >::nextRandomizer(), and QuantLib::RandomizedLDS< LDS, PRS >::RandomizedLDS().
template<class LDS, class PRS = RandomSequenceGenerator<MersenneTwisterUniformRng>> sample_type QuantLib::RandomizedLDS< LDS, PRS >::x [mutable, private]
Definition at line 83 of file randomizedlds.hpp.
Referenced by QuantLib::RandomizedLDS< LDS, PRS >::lastSequence().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/randomnumbers/randomizedlds.hpp