QuantLib: QuantLib::HaganPricer Class Reference
QuantLib::HaganPricer Class Reference
CMS-coupon pricer.
#include <conundrumpricer.hpp>
Public Member Functions
virtual Real swapletPrice () const =0
virtual Rate swapletRate () const
virtual Real capletPrice (Rate effectiveCap) const
virtual Rate capletRate (Rate effectiveCap) const
virtual Real floorletPrice (Rate effectiveFloor) const
virtual Rate floorletRate (Rate effectiveFloor) const
Real meanReversion () const
void setMeanReversion (const Handle< Quote > &meanReversion)
Protected Member Functions
HaganPricer (const Handle< SwaptionVolatilityStructure > &swaptionVol, GFunctionFactory::YieldCurveModel modelOfYieldCurve, const Handle< Quote > &meanReversion)
void initialize (const FloatingRateCoupon &coupon)
virtual Real optionletPrice (Option::Type optionType, Real strike) const =0
Protected Attributes
boost::shared_ptr
< YieldTermStructure > rateCurve_
GFunctionFactory::YieldCurveModel modelOfYieldCurve_
boost::shared_ptr< GFunction > gFunction_
const CmsCoupon * coupon_
Date paymentDate_
Date fixingDate_
Rate swapRateValue_
DiscountFactor discount_
Real annuity_
Real gearing_
Spread spread_
Real spreadLegValue_
Rate cutoffForCaplet_
Rate cutoffForFloorlet_
Handle< Quote > meanReversion_
Period swapTenor_
boost::shared_ptr
< VanillaOptionPricer > vanillaOptionPricer_
Detailed Description
CMS-coupon pricer.
Base class for the pricing of a CMS coupon via static replication as in Hagan's "Conundrums..." article
Definition at line 199 of file conundrumpricer.hpp.
Constructor & Destructor Documentation
QuantLib::HaganPricer::HaganPricer (const Handle< SwaptionVolatilityStructure > & swaptionVol, GFunctionFactory::YieldCurveModel modelOfYieldCurve, const Handle< Quote > & meanReversion) [protected]
Definition at line 68 of file conundrumpricer.cpp.
References meanReversion_, and QuantLib::Observer::registerWith().
    : CmsCouponPricer(swaptionVol),
      modelOfYieldCurve_(modelOfYieldCurve),
      cutoffForCaplet_(2), cutoffForFloorlet_(0),
      meanReversion_(meanReversion) {
          registerWith(meanReversion_);
    }
Member Function Documentation
Real QuantLib::HaganPricer::capletPrice (Rate effectiveCap) const [virtual]
Implements QuantLib::FloatingRateCouponPricer.
Definition at line 149 of file conundrumpricer.cpp.
References QuantLib::Coupon::accrualPeriod(), QuantLib::Option::Call, coupon_, cutoffForCaplet_, discount_, QuantLib::Settings::evaluationDate(), fixingDate_, gearing_, QuantLib::Singleton< Settings >::instance(), optionletPrice(), and QuantLib::CmsCoupon::swapIndex().
Referenced by capletRate().
{
        // caplet is equivalent to call option on fixing
        Date today = Settings::instance().evaluationDate();
        if (fixingDate_ <= today) {
            // the fixing is determined
            const Rate Rs =
                std::max(coupon_->swapIndex()->fixing(fixingDate_)-effectiveCap, 0.);
            Rate price = (gearing_*Rs)*(coupon_->accrualPeriod()*discount_);
            return price;
        } else {
            Real cutoffNearZero = 1e-10;
            Real capletPrice = 0;
            if (effectiveCap < cutoffForCaplet_) {
                Rate effectiveStrikeForMax = std::max(effectiveCap,cutoffNearZero);
                capletPrice = optionletPrice(Option::Call, effectiveStrikeForMax);
            }
            return gearing_ * capletPrice;
        }
    }
Rate QuantLib::HaganPricer::capletRate (Rate effectiveCap) const [virtual]
Implements QuantLib::FloatingRateCouponPricer.
Definition at line 169 of file conundrumpricer.cpp.
References QuantLib::Coupon::accrualPeriod(), capletPrice(), coupon_, and discount_.
{
        return capletPrice(effectiveCap)/(coupon_->accrualPeriod()*discount_);
    }
Real QuantLib::HaganPricer::floorletPrice (Rate effectiveFloor) const [virtual]
Implements QuantLib::FloatingRateCouponPricer.
Definition at line 173 of file conundrumpricer.cpp.
References QuantLib::Coupon::accrualPeriod(), coupon_, cutoffForFloorlet_, discount_, QuantLib::Settings::evaluationDate(), fixingDate_, gearing_, QuantLib::Singleton< Settings >::instance(), optionletPrice(), QuantLib::Option::Put, and QuantLib::CmsCoupon::swapIndex().
Referenced by floorletRate().
{
        // floorlet is equivalent to put option on fixing
        Date today = Settings::instance().evaluationDate();
        if (fixingDate_ <= today) {
            // the fixing is determined
            const Rate Rs =
                std::max(effectiveFloor-coupon_->swapIndex()->fixing(fixingDate_),0.);
            Rate price = (gearing_*Rs)*(coupon_->accrualPeriod()*discount_);
            return price;
        } else {
            Real cutoffNearZero = 1e-10;
            Real floorletPrice = 0;
            if (effectiveFloor > cutoffForFloorlet_){
                Rate effectiveStrikeForMin = std::max(effectiveFloor,cutoffNearZero);
                floorletPrice=optionletPrice(Option::Put, effectiveStrikeForMin);
            }
            return gearing_ * floorletPrice;
        }
    }
Rate QuantLib::HaganPricer::floorletRate (Rate effectiveFloor) const [virtual]
Implements QuantLib::FloatingRateCouponPricer.
Definition at line 193 of file conundrumpricer.cpp.
References QuantLib::Coupon::accrualPeriod(), coupon_, discount_, and floorletPrice().
{
        return floorletPrice(effectiveFloor)/(coupon_->accrualPeriod()*discount_);
    }
void QuantLib::HaganPricer::initialize (const FloatingRateCoupon & coupon) [protected, virtual]
Implements QuantLib::FloatingRateCouponPricer.
Definition at line 79 of file conundrumpricer.cpp.
References QuantLib::Coupon::accrualPeriod(), annuity_, coupon_, QuantLib::Coupon::date(), QuantLib::Schedule::date(), discount_, QuantLib::Settings::evaluationDate(), QuantLib::GFunctionFactory::ExactYield, QuantLib::FloatingRateCoupon::fixingDate(), fixingDate_, QuantLib::FloatingRateCoupon::gearing(), gearing_, gFunction_, QuantLib::Singleton< Settings >::instance(), QuantLib::Period::length(), meanReversion_, modelOfYieldCurve_, QuantLib::GFunctionFactory::newGFunctionExactYield(), QuantLib::GFunctionFactory::newGFunctionStandard(), QuantLib::GFunctionFactory::newGFunctionWithShifts(), QuantLib::GFunctionFactory::NonParallelShifts, QuantLib::GFunctionFactory::ParallelShifts, paymentDate_, QL_FAIL, QL_REQUIRE, rateCurve_, QuantLib::FloatingRateCoupon::spread(), spread_, spreadLegValue_, QuantLib::GFunctionFactory::Standard, QuantLib::swap(), QuantLib::CmsCoupon::swapIndex(), swapRateValue_, swapTenor_, QuantLib::CmsCouponPricer::swaptionVolatility(), vanillaOptionPricer_, and QuantLib::DayCounter::yearFraction().
{
        coupon_ =  dynamic_cast<const CmsCoupon*>(&coupon);
        QL_REQUIRE(coupon_, "CMS coupon needed");
        gearing_ = coupon_->gearing();
        spread_ = coupon_->spread();
        fixingDate_ = coupon_->fixingDate();
        paymentDate_ = coupon_->date();
        const boost::shared_ptr<SwapIndex>& swapIndex = coupon_->swapIndex();
        rateCurve_ = *(swapIndex->forwardingTermStructure());
        Date today = Settings::instance().evaluationDate();
        if(paymentDate_ > today)
            discount_ = rateCurve_->discount(paymentDate_);
        else discount_= 1.;
        spreadLegValue_ = spread_ * coupon_->accrualPeriod()* discount_;
        if (fixingDate_ > today){
            swapTenor_ = swapIndex->tenor();
            boost::shared_ptr<VanillaSwap> swap = swapIndex->underlyingSwap(fixingDate_);
            swapRateValue_ = swap->fairRate();
            static const Spread bp = 1.0e-4;
            annuity_ = (swap->floatingLegBPS()/bp);
            Size q = swapIndex->fixedLegTenor().frequency();
            const Schedule& schedule = swap->fixedSchedule();
            const DayCounter& dc = swapIndex->dayCounter();
            //const DayCounter dc = coupon.dayCounter();
            Time startTime = dc.yearFraction(rateCurve_->referenceDate(),
                                             swap->startDate());
            Time swapFirstPaymentTime =
                dc.yearFraction(rateCurve_->referenceDate(), schedule.date(1));
            Time paymentTime = dc.yearFraction(rateCurve_->referenceDate(),
                                               paymentDate_);
            Real delta = (paymentTime-startTime) / (swapFirstPaymentTime-startTime);
            switch (modelOfYieldCurve_) {
                case GFunctionFactory::Standard:
                    gFunction_ = GFunctionFactory::newGFunctionStandard(q, delta, swapTenor_.length());
                    break;
                case GFunctionFactory::ExactYield:
                    gFunction_ = GFunctionFactory::newGFunctionExactYield(*coupon_);
                    break;
                case GFunctionFactory::ParallelShifts: {
                    Handle<Quote> nullMeanReversionQuote(boost::shared_ptr<Quote>(new SimpleQuote(0.0)));
                    gFunction_ = GFunctionFactory::newGFunctionWithShifts(*coupon_, nullMeanReversionQuote);
                    }
                    break;
                case GFunctionFactory::NonParallelShifts:
                    gFunction_ = GFunctionFactory::newGFunctionWithShifts(*coupon_, meanReversion_);
                    break;
                default:
                    QL_FAIL("unknown/illegal gFunction type");
            }
            vanillaOptionPricer_= boost::shared_ptr<VanillaOptionPricer>(new
                BlackVanillaOptionPricer(swapRateValue_, fixingDate_, swapTenor_,
                                        *swaptionVolatility()));
         }
    }
Real QuantLib::HaganPricer::meanReversion () const
Definition at line 143 of file conundrumpricer.cpp.
References meanReversion_.
Referenced by setMeanReversion().
{ return meanReversion_->value();}
virtual Real QuantLib::HaganPricer::optionletPrice (Option::Type optionType, Real strike) const [protected, pure virtual]
Implemented in QuantLib::AnalyticHaganPricer, and QuantLib::NumericHaganPricer.
Referenced by capletPrice(), and floorletPrice().
void QuantLib::HaganPricer::setMeanReversion (const Handle< Quote > & meanReversion) [inline]
Definition at line 210 of file conundrumpricer.hpp.
References meanReversion(), meanReversion_, QuantLib::Observer::registerWith(), QuantLib::Observer::unregisterWith(), and QuantLib::FloatingRateCouponPricer::update().
{
            unregisterWith(meanReversion_);
            meanReversion_ = meanReversion;
            registerWith(meanReversion_);
            update();
        };
virtual Real QuantLib::HaganPricer::swapletPrice () const [pure virtual]
Implements QuantLib::FloatingRateCouponPricer.
Implemented in QuantLib::AnalyticHaganPricer, and QuantLib::NumericHaganPricer.
Referenced by swapletRate().
Rate QuantLib::HaganPricer::swapletRate () const [virtual]
Implements QuantLib::FloatingRateCouponPricer.
Definition at line 145 of file conundrumpricer.cpp.
References QuantLib::Coupon::accrualPeriod(), coupon_, discount_, and swapletPrice().
{
        return swapletPrice()/(coupon_->accrualPeriod()*discount_);
    }
Member Data Documentation
Real QuantLib::HaganPricer::annuity_ [protected]
Definition at line 233 of file conundrumpricer.hpp.
Referenced by QuantLib::NumericHaganPricer::ConundrumIntegrand::annuity(), initialize(), QuantLib::NumericHaganPricer::ConundrumIntegrand::operator()(), QuantLib::NumericHaganPricer::optionletPrice(), QuantLib::AnalyticHaganPricer::optionletPrice(), and QuantLib::AnalyticHaganPricer::swapletPrice().
const CmsCoupon* QuantLib::HaganPricer::coupon_ [protected]
Definition at line 229 of file conundrumpricer.hpp.
Referenced by capletPrice(), capletRate(), floorletPrice(), floorletRate(), initialize(), QuantLib::NumericHaganPricer::optionletPrice(), QuantLib::AnalyticHaganPricer::optionletPrice(), QuantLib::NumericHaganPricer::swapletPrice(), QuantLib::AnalyticHaganPricer::swapletPrice(), and swapletRate().
Rate QuantLib::HaganPricer::cutoffForCaplet_ [protected]
Definition at line 237 of file conundrumpricer.hpp.
Referenced by capletPrice().
Rate QuantLib::HaganPricer::cutoffForFloorlet_ [protected]
Definition at line 237 of file conundrumpricer.hpp.
Referenced by floorletPrice().
DiscountFactor QuantLib::HaganPricer::discount_ [protected]
Definition at line 232 of file conundrumpricer.hpp.
Referenced by capletPrice(), capletRate(), floorletPrice(), floorletRate(), initialize(), QuantLib::NumericHaganPricer::optionletPrice(), QuantLib::AnalyticHaganPricer::optionletPrice(), QuantLib::NumericHaganPricer::swapletPrice(), QuantLib::AnalyticHaganPricer::swapletPrice(), and swapletRate().
Date QuantLib::HaganPricer::fixingDate_ [protected]
Definition at line 230 of file conundrumpricer.hpp.
Referenced by capletPrice(), QuantLib::NumericHaganPricer::ConundrumIntegrand::fixingDate(), floorletPrice(), initialize(), QuantLib::NumericHaganPricer::optionletPrice(), QuantLib::AnalyticHaganPricer::optionletPrice(), QuantLib::NumericHaganPricer::resetUpperLimit(), QuantLib::NumericHaganPricer::swapletPrice(), and QuantLib::AnalyticHaganPricer::swapletPrice().
Real QuantLib::HaganPricer::gearing_ [protected]
Definition at line 234 of file conundrumpricer.hpp.
Referenced by capletPrice(), floorletPrice(), initialize(), QuantLib::NumericHaganPricer::swapletPrice(), and QuantLib::AnalyticHaganPricer::swapletPrice().
boost::shared_ptr<GFunction> QuantLib::HaganPricer::gFunction_ [protected]
Definition at line 228 of file conundrumpricer.hpp.
Referenced by QuantLib::NumericHaganPricer::ConundrumIntegrand::firstDerivativeOfF(), QuantLib::NumericHaganPricer::ConundrumIntegrand::functionF(), initialize(), QuantLib::NumericHaganPricer::optionletPrice(), QuantLib::AnalyticHaganPricer::optionletPrice(), QuantLib::NumericHaganPricer::ConundrumIntegrand::secondDerivativeOfF(), and QuantLib::AnalyticHaganPricer::swapletPrice().
Handle<Quote> QuantLib::HaganPricer::meanReversion_ [protected]
Definition at line 238 of file conundrumpricer.hpp.
Referenced by HaganPricer(), initialize(), meanReversion(), and setMeanReversion().
GFunctionFactory::YieldCurveModel QuantLib::HaganPricer::modelOfYieldCurve_ [protected]
Definition at line 227 of file conundrumpricer.hpp.
Referenced by initialize().
Date QuantLib::HaganPricer::paymentDate_ [protected]
Definition at line 230 of file conundrumpricer.hpp.
Referenced by initialize(), and QuantLib::NumericHaganPricer::optionletPrice().
boost::shared_ptr<YieldTermStructure> QuantLib::HaganPricer::rateCurve_ [protected]
Definition at line 226 of file conundrumpricer.hpp.
Referenced by initialize(), and QuantLib::NumericHaganPricer::optionletPrice().
Spread QuantLib::HaganPricer::spread_ [protected]
Definition at line 235 of file conundrumpricer.hpp.
Referenced by initialize(), QuantLib::NumericHaganPricer::swapletPrice(), and QuantLib::AnalyticHaganPricer::swapletPrice().
Real QuantLib::HaganPricer::spreadLegValue_ [protected]
Definition at line 236 of file conundrumpricer.hpp.
Referenced by initialize(), QuantLib::NumericHaganPricer::swapletPrice(), and QuantLib::AnalyticHaganPricer::swapletPrice().
Rate QuantLib::HaganPricer::swapRateValue_ [protected]
Definition at line 231 of file conundrumpricer.hpp.
Referenced by initialize(), QuantLib::NumericHaganPricer::optionletPrice(), QuantLib::AnalyticHaganPricer::optionletPrice(), QuantLib::NumericHaganPricer::resetUpperLimit(), QuantLib::NumericHaganPricer::swapletPrice(), and QuantLib::AnalyticHaganPricer::swapletPrice().
Period QuantLib::HaganPricer::swapTenor_ [protected]
Definition at line 239 of file conundrumpricer.hpp.
Referenced by initialize(), QuantLib::AnalyticHaganPricer::optionletPrice(), QuantLib::NumericHaganPricer::resetUpperLimit(), and QuantLib::AnalyticHaganPricer::swapletPrice().
boost::shared_ptr<VanillaOptionPricer> QuantLib::HaganPricer::vanillaOptionPricer_ [protected]
Definition at line 240 of file conundrumpricer.hpp.
Referenced by initialize(), and QuantLib::NumericHaganPricer::optionletPrice().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/conundrumpricer.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/conundrumpricer.cpp