QuantLib: QuantLib::ImpliedTermStructure Class Reference
QuantLib::ImpliedTermStructure Class Reference
Implied term structure at a given date in the future.
#include <impliedtermstructure.hpp>
Public Member Functions
ImpliedTermStructure (const Handle< YieldTermStructure > &, const Date &referenceDate)
Private Attributes
Handle< YieldTermStructure > originalCurve_
YieldTermStructure interface
DayCounter dayCounter () const
the day counter used for date/time conversion
Calendar calendar () const
the calendar used for reference and/or option date calculation
Natural settlementDays () const
the settlementDays used for reference date calculation
Date maxDate () const
the latest date for which the curve can return values
DiscountFactor discountImpl (Time) const
discount factor calculation
Detailed Description
Implied term structure at a given date in the future.
The given date will be the implied reference date.
Note:
This term structure will remain linked to the original structure, i.e., any changes in the latter will be reflected in this structure as well.
Test:
the correctness of the returned values is tested by checking them against numerical calculations.
observability against changes in the underlying term structure is checked.
Definition at line 47 of file impliedtermstructure.hpp.
Constructor & Destructor Documentation
QuantLib::ImpliedTermStructure::ImpliedTermStructure (const Handle< YieldTermStructure > & h, const Date & referenceDate) [inline]
Definition at line 67 of file impliedtermstructure.hpp.
References originalCurve_, and QuantLib::Observer::registerWith().
    : YieldTermStructure(referenceDate), originalCurve_(h) {
        registerWith(originalCurve_);
    }
Member Function Documentation
Calendar QuantLib::ImpliedTermStructure::calendar () const [inline, virtual]
the calendar used for reference and/or option date calculation
Reimplemented from QuantLib::TermStructure.
Definition at line 78 of file impliedtermstructure.hpp.
References originalCurve_.
{
        return originalCurve_->calendar();
    }
DayCounter QuantLib::ImpliedTermStructure::dayCounter () const [inline, virtual]
the day counter used for date/time conversion
Reimplemented from QuantLib::TermStructure.
Definition at line 74 of file impliedtermstructure.hpp.
References originalCurve_.
Referenced by discountImpl().
{
        return originalCurve_->dayCounter();
    }
DiscountFactor QuantLib::ImpliedTermStructure::discountImpl (Time) const [inline, protected, virtual]
discount factor calculation
Implements QuantLib::YieldTermStructure.
Definition at line 90 of file impliedtermstructure.hpp.
References dayCounter(), originalCurve_, QuantLib::TermStructure::referenceDate(), and QuantLib::DayCounter::yearFraction().
{
        /* t is relative to the current reference date
           and needs to be converted to the time relative
           to the reference date of the original curve */
        Date ref = referenceDate();
        Time originalTime = t + dayCounter().yearFraction(
                                        originalCurve_->referenceDate(), ref);
        /* discount at evaluation date cannot be cached
           since the original curve could change between
           invocations of this method */
        return originalCurve_->discount(originalTime, true) /
               originalCurve_->discount(ref, true);
    }
Date QuantLib::ImpliedTermStructure::maxDate () const [inline, virtual]
the latest date for which the curve can return values
Implements QuantLib::TermStructure.
Definition at line 86 of file impliedtermstructure.hpp.
References originalCurve_.
{
        return originalCurve_->maxDate();
    }
Natural QuantLib::ImpliedTermStructure::settlementDays () const [inline, virtual]
the settlementDays used for reference date calculation
Reimplemented from QuantLib::TermStructure.
Definition at line 82 of file impliedtermstructure.hpp.
References originalCurve_.
{
        return originalCurve_->settlementDays();
    }
Member Data Documentation
Handle<YieldTermStructure> QuantLib::ImpliedTermStructure::originalCurve_ [private]
Definition at line 61 of file impliedtermstructure.hpp.
Referenced by calendar(), dayCounter(), discountImpl(), ImpliedTermStructure(), maxDate(), and settlementDays().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/yield/impliedtermstructure.hpp