QuantLib: QuantLib::ForwardSwapQuote Class Reference
QuantLib::ForwardSwapQuote Class Reference
Quote for a forward starting swap.
#include <forwardswapquote.hpp>
Public Member Functions
ForwardSwapQuote (const boost::shared_ptr< SwapIndex > &swapIndex, const Handle< Quote > &spread, const Period &fwdStart)
const Date & valueDate () const
const Date & startDate () const
const Date & fixingDate () const
Quote interface
Real value () const
returns the current value
bool isValid () const
returns true if the Quote holds a valid value
Observer interface
void update ()
Protected Member Functions
void initializeDates ()
void performCalculations () const
Protected Attributes
boost::shared_ptr< SwapIndex > swapIndex_
Handle< Quote > spread_
Period fwdStart_
Date evaluationDate_
Date valueDate_
Date startDate_
Date fixingDate_
boost::shared_ptr< VanillaSwap > swap_
Rate result_
Detailed Description
Quote for a forward starting swap.
Definition at line 35 of file forwardswapquote.hpp.
Constructor & Destructor Documentation
QuantLib::ForwardSwapQuote::ForwardSwapQuote (const boost::shared_ptr< SwapIndex > & swapIndex, const Handle< Quote > & spread, const Period & fwdStart)
Definition at line 25 of file forwardswapquote.cpp.
References QuantLib::Settings::evaluationDate(), evaluationDate_, initializeDates(), QuantLib::Singleton< Settings >::instance(), QuantLib::Observer::registerWith(), spread_, and swapIndex_.
    : swapIndex_(swapIndex), spread_(spread), fwdStart_(fwdStart) {
        registerWith(swapIndex_);
        registerWith(spread_);
        registerWith(Settings::instance().evaluationDate());
        evaluationDate_ = Settings::instance().evaluationDate();
        initializeDates();
    }
Member Function Documentation
const Date & QuantLib::ForwardSwapQuote::fixingDate () const
Definition at line 67 of file forwardswapquote.cpp.
References QuantLib::LazyObject::calculate(), and fixingDate_.
{
        calculate();
        return fixingDate_;
    }
void QuantLib::ForwardSwapQuote::initializeDates () [protected]
Definition at line 37 of file forwardswapquote.cpp.
References QuantLib::Days, evaluationDate_, fixingDate_, QuantLib::Following, fwdStart_, startDate_, swap_, swapIndex_, and valueDate_.
Referenced by ForwardSwapQuote(), and update().
{
        valueDate_ = swapIndex_->fixingCalendar().advance(
                                                evaluationDate_,
                                                swapIndex_->fixingDays()*Days,
                                                Following);
        startDate_ = swapIndex_->fixingCalendar().advance(valueDate_,
                                                          fwdStart_,
                                                          Following);
        fixingDate_ = swapIndex_->fixingDate(startDate_);
        swap_ = swapIndex_->underlyingSwap(fixingDate_);
    }
bool QuantLib::ForwardSwapQuote::isValid () const [virtual]
returns true if the Quote holds a valid value
Implements QuantLib::Quote.
Definition at line 77 of file forwardswapquote.cpp.
References QuantLib::Handle< T >::empty(), spread_, and swap_.
{
        bool swapIndexIsValid = true;
        try {
            swap_->recalculate();
        } catch (...) {
            swapIndexIsValid = false;
        }
        bool spreadIsValid = spread_.empty() ? true : spread_->isValid();
        return swapIndexIsValid && spreadIsValid;
    }
void QuantLib::ForwardSwapQuote::performCalculations () const [protected, virtual]
This method must implement any calculations which must be (re)done in order to calculate the desired results.
Implements QuantLib::LazyObject.
Definition at line 88 of file forwardswapquote.cpp.
References QuantLib::Handle< T >::empty(), result_, spread_, and swap_.
{
        // we didn't register as observers - force calculation
        swap_->recalculate();
        // weak implementation... to be improved
        static const Spread basisPoint = 1.0e-4;
        Real floatingLegNPV = swap_->floatingLegNPV();
        Spread spread = spread_.empty() ? 0.0 : spread_->value();
        Real spreadNPV = swap_->floatingLegBPS()/basisPoint*spread;
        Real totNPV = - (floatingLegNPV+spreadNPV);
        result_ = totNPV/(swap_->fixedLegBPS()/basisPoint);
    }
const Date & QuantLib::ForwardSwapQuote::startDate () const
Definition at line 62 of file forwardswapquote.cpp.
References QuantLib::LazyObject::calculate(), and startDate_.
{
        calculate();
        return startDate_;
    }
void QuantLib::ForwardSwapQuote::update () [virtual]
This method must be implemented in derived classes. An instance of Observer does not call this method directly: instead, it will be called by the observables the instance registered with when they need to notify any changes.
Reimplemented from QuantLib::LazyObject.
Definition at line 49 of file forwardswapquote.cpp.
References QuantLib::Settings::evaluationDate(), evaluationDate_, initializeDates(), and QuantLib::Singleton< Settings >::instance().
{
        if (evaluationDate_ != Settings::instance().evaluationDate()) {
            evaluationDate_ = Settings::instance().evaluationDate();
            initializeDates();
        }
        LazyObject::update();
    }
Real QuantLib::ForwardSwapQuote::value () const [virtual]
returns the current value
Implements QuantLib::Quote.
Definition at line 72 of file forwardswapquote.cpp.
References QuantLib::LazyObject::calculate(), and result_.
{
        calculate();
        return result_;
    }
const Date & QuantLib::ForwardSwapQuote::valueDate () const
Definition at line 57 of file forwardswapquote.cpp.
References QuantLib::LazyObject::calculate(), and valueDate_.
{
        calculate();
        return valueDate_;
    }
Member Data Documentation
Date QuantLib::ForwardSwapQuote::evaluationDate_ [protected]
Definition at line 61 of file forwardswapquote.hpp.
Referenced by ForwardSwapQuote(), initializeDates(), and update().
Date QuantLib::ForwardSwapQuote::fixingDate_ [protected]
Definition at line 61 of file forwardswapquote.hpp.
Referenced by fixingDate(), and initializeDates().
Period QuantLib::ForwardSwapQuote::fwdStart_ [protected]
Definition at line 59 of file forwardswapquote.hpp.
Referenced by initializeDates().
Rate QuantLib::ForwardSwapQuote::result_ [mutable, protected]
Definition at line 64 of file forwardswapquote.hpp.
Referenced by performCalculations(), and value().
Handle<Quote> QuantLib::ForwardSwapQuote::spread_ [protected]
Definition at line 58 of file forwardswapquote.hpp.
Referenced by ForwardSwapQuote(), isValid(), and performCalculations().
Date QuantLib::ForwardSwapQuote::startDate_ [protected]
Definition at line 61 of file forwardswapquote.hpp.
Referenced by initializeDates(), and startDate().
boost::shared_ptr<VanillaSwap> QuantLib::ForwardSwapQuote::swap_ [protected]
Definition at line 62 of file forwardswapquote.hpp.
Referenced by initializeDates(), isValid(), and performCalculations().
boost::shared_ptr<SwapIndex> QuantLib::ForwardSwapQuote::swapIndex_ [protected]
Definition at line 57 of file forwardswapquote.hpp.
Referenced by ForwardSwapQuote(), and initializeDates().
Date QuantLib::ForwardSwapQuote::valueDate_ [protected]
Definition at line 61 of file forwardswapquote.hpp.
Referenced by initializeDates(), and valueDate().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/quotes/forwardswapquote.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/quotes/forwardswapquote.cpp