QuantLib: ScheduleTest Class Reference
ScheduleTest Class Reference
#include <schedule.hpp>
Static Public Member Functions
static void testDailySchedule ()
static void testEndDateWithEomAdjustment ()
static
boost::unit_test_framework::test_suite * suite ()
Detailed Description
Definition at line 28 of file schedule.hpp.
Member Function Documentation
test_suite * ScheduleTest::suite () [static]
Definition at line 117 of file schedule.cpp.
References QUANTLIB_TEST_CASE, testDailySchedule(), and testEndDateWithEomAdjustment().
Referenced by init_unit_test_suite().
{
    test_suite* suite = BOOST_TEST_SUITE("Schedule tests");
    suite->add(QUANTLIB_TEST_CASE(&ScheduleTest::testDailySchedule));
    suite->add(QUANTLIB_TEST_CASE(&ScheduleTest::testEndDateWithEomAdjustment));
    return suite;
}
void ScheduleTest::testDailySchedule () [static]
Definition at line 49 of file schedule.cpp.
References anonymous_namespace{schedule.cpp}::check_dates(), QuantLib::Daily, QuantLib::MakeSchedule::from(), QuantLib::January, QuantLib::Preceding, anonymous_namespace{marketmodel.cpp}::startDate, QuantLib::MakeSchedule::to(), QuantLib::MakeSchedule::withCalendar(), QuantLib::MakeSchedule::withConvention(), and QuantLib::MakeSchedule::withFrequency().
Referenced by suite().
{
    BOOST_MESSAGE("Testing schedule with daily frequency...");
    Date startDate = Date(17,January,2012);
    Schedule s =
        MakeSchedule().from(startDate).to(startDate+7)
                      .withCalendar(TARGET())
                      .withFrequency(Daily)
                      .withConvention(Preceding);
    std::vector<Date> expected(6);
    // The schedule should skip Saturday 21st and Sunday 22rd.
    // Previously, it would adjust them to Friday 20th, resulting
    // in three copies of the same date.
    expected[0] = Date(17,January,2012);
    expected[1] = Date(18,January,2012);
    expected[2] = Date(19,January,2012);
    expected[3] = Date(20,January,2012);
    expected[4] = Date(23,January,2012);
    expected[5] = Date(24,January,2012);
    check_dates(s, expected);
}
void ScheduleTest::testEndDateWithEomAdjustment () [static]
Definition at line 74 of file schedule.cpp.
References anonymous_namespace{schedule.cpp}::check_dates(), QuantLib::MakeSchedule::endOfMonth(), QuantLib::Following, QuantLib::MakeSchedule::forwards(), QuantLib::MakeSchedule::from(), QuantLib::June, QuantLib::March, QuantLib::Months, QuantLib::September, QuantLib::MakeSchedule::to(), QuantLib::Unadjusted, QuantLib::MakeSchedule::withCalendar(), QuantLib::MakeSchedule::withConvention(), QuantLib::MakeSchedule::withTenor(), and QuantLib::MakeSchedule::withTerminationDateConvention().
Referenced by suite().
{
    BOOST_MESSAGE(
        "Testing end date for schedule with end-of-month adjustment...");
    Schedule s =
        MakeSchedule().from(Date(30,September,2009))
                      .to(Date(15,June,2012))
                      .withCalendar(Japan())
                      .withTenor(6*Months)
                      .withConvention(Following)
                      .withTerminationDateConvention(Following)
                      .forwards()
                      .endOfMonth();
    std::vector<Date> expected(7);
    // The end date is adjusted, so it should also be moved to the end
    // of the month.
    expected[0] = Date(30,September,2009);
    expected[1] = Date(31,March,2010);
    expected[2] = Date(30,September,2010);
    expected[3] = Date(31,March,2011);
    expected[4] = Date(30,September,2011);
    expected[5] = Date(30,March,2012);
    expected[6] = Date(29,June,2012);
    check_dates(s, expected);
    // now with unadjusted termination date...
    s = MakeSchedule().from(Date(30,September,2009))
                      .to(Date(15,June,2012))
                      .withCalendar(Japan())
                      .withTenor(6*Months)
                      .withConvention(Following)
                      .withTerminationDateConvention(Unadjusted)
                      .forwards()
                      .endOfMonth();
    // ...which should leave it alone.
    expected[6] = Date(15,June,2012);
    check_dates(s, expected);
}
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/schedule.hpp
/home/deriversatile/QuantLib/QuantLibQt/test-suite/schedule.cpp