QuantLib: QuantLib::FdmSimple3dExtOUJumpSolver Class Reference
QuantLib::FdmSimple3dExtOUJumpSolver Class Reference
#include <fdmsimple3dextoujumpsolver.hpp>
Public Member Functions
FdmSimple3dExtOUJumpSolver (const Handle< ExtOUWithJumpsProcess > &process, const boost::shared_ptr< YieldTermStructure > &rTS, const FdmSolverDesc &solverDesc, const FdmSchemeDesc &schemeDesc=FdmSchemeDesc::Hundsdorfer())
Real valueAt (Real x, Real y, Real z) const
Protected Member Functions
void performCalculations () const
Private Attributes
const Handle
< ExtOUWithJumpsProcess > process_
const boost::shared_ptr
< YieldTermStructure > rTS_
const FdmSolverDesc solverDesc_
const FdmSchemeDesc schemeDesc_
boost::shared_ptr< Fdm3DimSolver > solver_
Detailed Description
Definition at line 39 of file fdmsimple3dextoujumpsolver.hpp.
Constructor & Destructor Documentation
QuantLib::FdmSimple3dExtOUJumpSolver::FdmSimple3dExtOUJumpSolver (const Handle< ExtOUWithJumpsProcess > & process, const boost::shared_ptr< YieldTermStructure > & rTS, const FdmSolverDesc & solverDesc, const FdmSchemeDesc & schemeDesc = FdmSchemeDesc::Hundsdorfer()) [inline]
Definition at line 41 of file fdmsimple3dextoujumpsolver.hpp.
References QuantLib::Observer::registerWith().
        : process_(process), rTS_(rTS),
          solverDesc_(solverDesc), schemeDesc_(schemeDesc) {
            registerWith(process);
        }
Member Function Documentation
void QuantLib::FdmSimple3dExtOUJumpSolver::performCalculations () const [inline, protected, virtual]
This method must implement any calculations which must be (re)done in order to calculate the desired results.
Implements QuantLib::LazyObject.
Definition at line 57 of file fdmsimple3dextoujumpsolver.hpp.
References QuantLib::FdmSolverDesc::bcSet, QuantLib::Handle< T >::currentLink(), QuantLib::FdmSolverDesc::mesher, process_, rTS_, schemeDesc_, solver_, and solverDesc_.
{
            boost::shared_ptr<FdmLinearOpComposite>op(
                new FdmExtOUJumpOp(solverDesc_.mesher,
                                   process_.currentLink(),
                                   rTS_, solverDesc_.bcSet, 32));
            solver_ = boost::shared_ptr<Fdm3DimSolver>(
                          new Fdm3DimSolver(solverDesc_, schemeDesc_, op));
        }
Real QuantLib::FdmSimple3dExtOUJumpSolver::valueAt (Real x, Real y, Real z) const [inline]
Definition at line 51 of file fdmsimple3dextoujumpsolver.hpp.
References QuantLib::LazyObject::calculate(), and solver_.
{
            calculate();
            return solver_->interpolateAt(x, y, z);
        }
Member Data Documentation
const Handle<ExtOUWithJumpsProcess> QuantLib::FdmSimple3dExtOUJumpSolver::process_ [private]
Definition at line 68 of file fdmsimple3dextoujumpsolver.hpp.
Referenced by performCalculations().
const boost::shared_ptr<YieldTermStructure> QuantLib::FdmSimple3dExtOUJumpSolver::rTS_ [private]
Definition at line 69 of file fdmsimple3dextoujumpsolver.hpp.
Referenced by performCalculations().
const FdmSchemeDesc QuantLib::FdmSimple3dExtOUJumpSolver::schemeDesc_ [private]
Definition at line 71 of file fdmsimple3dextoujumpsolver.hpp.
Referenced by performCalculations().
boost::shared_ptr<Fdm3DimSolver> QuantLib::FdmSimple3dExtOUJumpSolver::solver_ [mutable, private]
Definition at line 73 of file fdmsimple3dextoujumpsolver.hpp.
Referenced by performCalculations(), and valueAt().
const FdmSolverDesc QuantLib::FdmSimple3dExtOUJumpSolver::solverDesc_ [private]
Definition at line 70 of file fdmsimple3dextoujumpsolver.hpp.
Referenced by performCalculations().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/finitedifferences/fdmsimple3dextoujumpsolver.hpp