QuantLib: QuantLib::Payoff Class Reference
QuantLib::Payoff Class Reference
Abstract base class for option payoffs.
#include <payoff.hpp>
Public Member Functions
virtual ~Payoff ()
Payoff interface
virtual std::string name () const =0
virtual std::string description () const =0
virtual Real operator() (Real price) const =0
Visitability
virtual void accept (AcyclicVisitor &)
Detailed Description
Abstract base class for option payoffs.
Definition at line 36 of file payoff.hpp.
Constructor & Destructor Documentation
virtual QuantLib::Payoff::~Payoff () [inline, virtual]
Definition at line 38 of file payoff.hpp.
{}
Member Function Documentation
void QuantLib::Payoff::accept (AcyclicVisitor & v) [inline, virtual]
Reimplemented in QuantLib::SuperSharePayoff, QuantLib::SuperFundPayoff, QuantLib::GapPayoff, QuantLib::CashOrNothingPayoff, QuantLib::AssetOrNothingPayoff, QuantLib::PercentageStrikePayoff, QuantLib::PlainVanillaPayoff, QuantLib::FloatingTypePayoff, QuantLib::DoubleStickyRatchetPayoff, and QuantLib::NullPayoff.
Definition at line 58 of file payoff.hpp.
References QL_FAIL, anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Visitor< T >::visit().
{
        Visitor<Payoff>* v1 = dynamic_cast<Visitor<Payoff>*>(&v);
        if (v1 != 0)
            v1->visit(*this);
        else
            QL_FAIL("not a payoff visitor");
    }
virtual std::string QuantLib::Payoff::description () const [pure virtual]
Implemented in QuantLib::SuperSharePayoff, QuantLib::GapPayoff, QuantLib::CashOrNothingPayoff, QuantLib::ForwardTypePayoff, anonymous_namespace{fdmlinearop.cpp}::ExpressPayoff, QuantLib::StrikedTypePayoff, QuantLib::TypePayoff, QuantLib::DoubleStickyRatchetPayoff, QuantLib::BasketPayoff, QuantLib::NullPayoff, and QuantLib::anonymous_namespace{vanillavppoption.cpp}::IdenticalPayoff.
virtual std::string QuantLib::Payoff::name () const [pure virtual]
Warning:
This method is used for output and comparison between payoffs. It is not meant to be used for writing switch-on-type code.
Implemented in QuantLib::SuperSharePayoff, QuantLib::SuperFundPayoff, QuantLib::GapPayoff, QuantLib::StickyMinPayoff, QuantLib::CashOrNothingPayoff, QuantLib::ForwardTypePayoff, QuantLib::StickyMaxPayoff, QuantLib::AssetOrNothingPayoff, QuantLib::RatchetMinPayoff, QuantLib::PercentageStrikePayoff, anonymous_namespace{fdmlinearop.cpp}::ExpressPayoff, QuantLib::PlainVanillaPayoff, QuantLib::RatchetMaxPayoff, QuantLib::StickyPayoff, QuantLib::FloatingTypePayoff, QuantLib::RatchetPayoff, QuantLib::DoubleStickyRatchetPayoff, QuantLib::BasketPayoff, QuantLib::NullPayoff, and QuantLib::anonymous_namespace{vanillavppoption.cpp}::IdenticalPayoff.
Referenced by QuantLib::TypePayoff::description(), and QuantLib::BlackCalculator::Calculator::visit().
virtual Real QuantLib::Payoff::operator() (Real price) const [pure virtual]
Implemented in QuantLib::SuperSharePayoff, QuantLib::SuperFundPayoff, QuantLib::GapPayoff, QuantLib::CashOrNothingPayoff, QuantLib::ForwardTypePayoff, QuantLib::AssetOrNothingPayoff, QuantLib::PercentageStrikePayoff, QuantLib::PlainVanillaPayoff, QuantLib::FloatingTypePayoff, QuantLib::DoubleStickyRatchetPayoff, QuantLib::BasketPayoff, QuantLib::NullPayoff, and QuantLib::anonymous_namespace{vanillavppoption.cpp}::IdenticalPayoff.
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/payoff.hpp