QuantLib: QuantLib::YearOnYearInflationSwap Class Reference
QuantLib::YearOnYearInflationSwap Class Reference
Year-on-year inflation-indexed swap.
#include <yearonyearinflationswap.hpp>
Classes
class arguments
Arguments for YoY swap calculation
class engine
class results
Results from YoY swap calculation
Public Types
enum Type { Receiver = -1, Payer = 1 }
Public Member Functions
YearOnYearInflationSwap (Type type, Real nominal, const Schedule &fixedSchedule, Rate fixedRate, const DayCounter &fixedDayCount, const Schedule &yoySchedule, const boost::shared_ptr< YoYInflationIndex > &yoyIndex, const Period &observationLag, Spread spread, const DayCounter &yoyDayCount, const Calendar &paymentCalendar, BusinessDayConvention paymentConvention=ModifiedFollowing)
virtual Real fixedLegNPV () const
virtual Rate fairRate () const
virtual Real yoyLegNPV () const
virtual Spread fairSpread () const
virtual Type type () const
virtual Real nominal () const
virtual const Schedule & fixedSchedule () const
virtual Rate fixedRate () const
virtual const DayCounter & fixedDayCount () const
virtual const Schedule & yoySchedule () const
virtual const
boost::shared_ptr
< YoYInflationIndex > & yoyInflationIndex () const
virtual Period observationLag () const
virtual Spread spread () const
virtual const DayCounter & yoyDayCount () const
virtual Calendar paymentCalendar () const
virtual BusinessDayConvention paymentConvention () const
virtual const Leg & fixedLeg () const
virtual const Leg & yoyLeg () const
void setupArguments (PricingEngine::arguments *args) const
void fetchResults (const PricingEngine::results *) const
virtual ~YearOnYearInflationSwap ()
Private Member Functions
void setupExpired () const
Private Attributes
Type type_
Real nominal_
Schedule fixedSchedule_
Rate fixedRate_
DayCounter fixedDayCount_
Schedule yoySchedule_
boost::shared_ptr
< YoYInflationIndex > yoyIndex_
Period observationLag_
Spread spread_
DayCounter yoyDayCount_
Calendar paymentCalendar_
BusinessDayConvention paymentConvention_
Rate fairRate_
Spread fairSpread_
Detailed Description
Year-on-year inflation-indexed swap.
Quoted as a fixed rate \(K \). At start:
\[ \sum_{i=1}^{M} P_n(0,t_i) N K = \sum_{i=1}^{M} P_n(0,t_i) N \left[ \frac{I(t_i)}{I(t_i-1)} - 1 \right] \]
where \(t_M \) is the maturity time, \(P_n(0,t) \) is the nominal discount factor at time \(t \), \(N \) is the notional, and \(I(t) \) is the inflation index value at time \(t \).
Note:
These instruments have now been changed to follow typical VanillaSwap type design conventions w.r.t. Schedules etc.
Definition at line 51 of file yearonyearinflationswap.hpp.
Member Enumeration Documentation
enum QuantLib::YearOnYearInflationSwap::Type
Enumerator:
Receiver
Payer
Definition at line 53 of file yearonyearinflationswap.hpp.
{ Receiver = -1, Payer = 1 };
Constructor & Destructor Documentation
QuantLib::YearOnYearInflationSwap::YearOnYearInflationSwap (Type type, Real nominal, const Schedule & fixedSchedule, Rate fixedRate, const DayCounter & fixedDayCount, const Schedule & yoySchedule, const boost::shared_ptr< YoYInflationIndex > & yoyIndex, const Period & observationLag, Spread spread, const DayCounter & yoyDayCount, const Calendar & paymentCalendar, BusinessDayConvention paymentConvention = ModifiedFollowing)
Definition at line 34 of file yearonyearinflationswap.cpp.
References fixedDayCount_, fixedLeg(), fixedRate_, fixedSchedule_, QuantLib::Swap::legs_, nominal_, observationLag_, Payer, QuantLib::Swap::payer_, paymentCalendar_, paymentConvention_, QuantLib::Observer::registerWith(), spread_, type_, QuantLib::FixedRateLeg::withCouponRates(), QuantLib::FixedRateLeg::withNotionals(), QuantLib::yoyInflationLeg::withNotionals(), QuantLib::FixedRateLeg::withPaymentAdjustment(), QuantLib::yoyInflationLeg::withPaymentAdjustment(), QuantLib::yoyInflationLeg::withPaymentDayCounter(), QuantLib::yoyInflationLeg::withSpreads(), yoyDayCount_, yoyIndex_, yoyLeg(), and yoySchedule_.
    : Swap(2), type_(type), nominal_(nominal),
    fixedSchedule_(fixedSchedule), fixedRate_(fixedRate),
    fixedDayCount_(fixedDayCount),
    yoySchedule_(yoySchedule), yoyIndex_(yoyIndex),
    observationLag_(observationLag),
    spread_(spread),
    yoyDayCount_(yoyDayCount), paymentCalendar_(paymentCalendar),
    paymentConvention_(paymentConvention)
    {
        // N.B. fixed leg gets its calendar from the schedule!
        Leg fixedLeg = FixedRateLeg(fixedSchedule_)
        .withNotionals(nominal_)
        .withCouponRates(fixedRate_, fixedDayCount_) // Simple compounding by default
        .withPaymentAdjustment(paymentConvention_);
        Leg yoyLeg = yoyInflationLeg(yoySchedule_, paymentCalendar_, yoyIndex_, observationLag_)
        .withNotionals(nominal_)
        .withPaymentDayCounter(yoyDayCount_)
        .withPaymentAdjustment(paymentConvention_)
        .withSpreads(spread_);
        Leg::const_iterator i;
        for (i = yoyLeg.begin(); i < yoyLeg.end(); ++i)
            registerWith(*i);
        legs_[0] = fixedLeg;
        legs_[1] = yoyLeg;
        if (type_==Payer) {
            payer_[0] = -1.0;
            payer_[1] = +1.0;
        } else {
            payer_[0] = +1.0;
            payer_[1] = -1.0;
        }
    }
virtual QuantLib::YearOnYearInflationSwap::~YearOnYearInflationSwap () [inline, virtual]
Definition at line 101 of file yearonyearinflationswap.hpp.
{}
Member Function Documentation
Rate QuantLib::YearOnYearInflationSwap::fairRate () const [virtual]
Definition at line 141 of file yearonyearinflationswap.cpp.
References QuantLib::Instrument::calculate(), fairRate_, and QL_REQUIRE.
Referenced by QuantLib::YearOnYearInflationSwap::results::reset(), and InflationTest::testYYTermStructure().
{
        calculate();
        QL_REQUIRE(fairRate_ != Null<Rate>(), "result not available");
        return fairRate_;
    }
Spread QuantLib::YearOnYearInflationSwap::fairSpread () const [virtual]
Definition at line 147 of file yearonyearinflationswap.cpp.
References QuantLib::Instrument::calculate(), fairSpread_, and QL_REQUIRE.
Referenced by QuantLib::YearOnYearInflationSwap::results::reset().
{
        calculate();
        QL_REQUIRE(fairSpread_ != Null<Spread>(), "result not available");
        return fairSpread_;
    }
void QuantLib::YearOnYearInflationSwap::fetchResults (const PricingEngine::results * r) const [virtual]
When a derived result structure is defined for an instrument, this method should be overridden to read from it. This is mandatory in case a pricing engine is used.
Reimplemented from QuantLib::Swap.
Definition at line 173 of file yearonyearinflationswap.cpp.
References QuantLib::YearOnYearInflationSwap::results::fairRate, fairRate_, QuantLib::YearOnYearInflationSwap::results::fairSpread, fairSpread_, fixedRate_, QuantLib::Swap::legBPS_, QuantLib::Instrument::NPV_, and spread_.
{
        static const Spread basisPoint = 1.0e-4;
        // copy from VanillaSwap
        // works because similarly simple instrument
        // that we always expect to be priced with a swap engine
        Swap::fetchResults(r);
        const YearOnYearInflationSwap::results* results =
        dynamic_cast<const YearOnYearInflationSwap::results*>(r);
        if (results) { // might be a swap engine, so no error is thrown
            fairRate_ = results->fairRate;
            fairSpread_ = results->fairSpread;
        } else {
            fairRate_ = Null<Rate>();
            fairSpread_ = Null<Spread>();
        }
        if (fairRate_ == Null<Rate>()) {
            // calculate it from other results
            if (legBPS_[0] != Null<Real>())
                fairRate_ = fixedRate_ - NPV_/(legBPS_[0]/basisPoint);
        }
        if (fairSpread_ == Null<Spread>()) {
            // ditto
            if (legBPS_[1] != Null<Real>())
                fairSpread_ = spread_ - NPV_/(legBPS_[1]/basisPoint);
        }
    }
const DayCounter & QuantLib::YearOnYearInflationSwap::fixedDayCount () const [inline, virtual]
Definition at line 174 of file yearonyearinflationswap.hpp.
References fixedDayCount_.
{
        return fixedDayCount_;
    }
const Leg & QuantLib::YearOnYearInflationSwap::fixedLeg () const [inline, virtual]
Definition at line 198 of file yearonyearinflationswap.hpp.
References QuantLib::Swap::legs_.
Referenced by setupArguments(), and YearOnYearInflationSwap().
{
        return legs_[0];
    }
Real QuantLib::YearOnYearInflationSwap::fixedLegNPV () const [virtual]
Definition at line 154 of file yearonyearinflationswap.cpp.
References QuantLib::Instrument::calculate(), QuantLib::Swap::legNPV_, and QL_REQUIRE.
{
        calculate();
        QL_REQUIRE(legNPV_[0] != Null<Real>(), "result not available");
        return legNPV_[0];
    }
Rate QuantLib::YearOnYearInflationSwap::fixedRate () const [inline, virtual]
Definition at line 170 of file yearonyearinflationswap.hpp.
References fixedRate_.
{
        return fixedRate_;
    }
const Schedule & QuantLib::YearOnYearInflationSwap::fixedSchedule () const [inline, virtual]
Definition at line 166 of file yearonyearinflationswap.hpp.
References fixedSchedule_.
{
        return fixedSchedule_;
    }
Real QuantLib::YearOnYearInflationSwap::nominal () const [inline, virtual]
Definition at line 162 of file yearonyearinflationswap.hpp.
References nominal_.
{
        return nominal_;
    }
virtual Period QuantLib::YearOnYearInflationSwap::observationLag () const [inline, virtual]
Definition at line 88 of file yearonyearinflationswap.hpp.
References observationLag_.
{ return observationLag_; }
virtual Calendar QuantLib::YearOnYearInflationSwap::paymentCalendar () const [inline, virtual]
Definition at line 92 of file yearonyearinflationswap.hpp.
References paymentCalendar_.
{ return paymentCalendar_; }
BusinessDayConvention QuantLib::YearOnYearInflationSwap::paymentConvention () const [inline, virtual]
Definition at line 194 of file yearonyearinflationswap.hpp.
References paymentConvention_.
Referenced by InflationTest::testYYTermStructure().
{
        return paymentConvention_;
    }
void QuantLib::YearOnYearInflationSwap::setupArguments (PricingEngine::arguments *) const [virtual]
When a derived argument structure is defined for an instrument, this method should be overridden to fill it. This is mandatory in case a pricing engine is used.
Reimplemented from QuantLib::Swap.
Definition at line 84 of file yearonyearinflationswap.cpp.
References QuantLib::YearOnYearInflationSwap::arguments::fixedCoupons, fixedLeg(), QuantLib::YearOnYearInflationSwap::arguments::fixedPayDates, QuantLib::YearOnYearInflationSwap::arguments::fixedResetDates, QuantLib::YearOnYearInflationSwap::arguments::nominal, nominal_, QuantLib::YearOnYearInflationSwap::arguments::type, type_, QuantLib::YearOnYearInflationSwap::arguments::yoyAccrualTimes, QuantLib::YearOnYearInflationSwap::arguments::yoyCoupons, QuantLib::YearOnYearInflationSwap::arguments::yoyFixingDates, yoyLeg(), QuantLib::YearOnYearInflationSwap::arguments::yoyPayDates, QuantLib::YearOnYearInflationSwap::arguments::yoyResetDates, and QuantLib::YearOnYearInflationSwap::arguments::yoySpreads.
{
        Swap::setupArguments(args);
        YearOnYearInflationSwap::arguments* arguments =
        dynamic_cast<YearOnYearInflationSwap::arguments*>(args);
        if (!arguments)  // it's a swap engine...
            return;
        arguments->type = type_;
        arguments->nominal = nominal_;
        const Leg& fixedCoupons = fixedLeg();
        arguments->fixedResetDates = arguments->fixedPayDates =
        std::vector<Date>(fixedCoupons.size());
        arguments->fixedCoupons = std::vector<Real>(fixedCoupons.size());
        for (Size i=0; i<fixedCoupons.size(); ++i) {
            boost::shared_ptr<FixedRateCoupon> coupon =
            boost::dynamic_pointer_cast<FixedRateCoupon>(fixedCoupons[i]);
            arguments->fixedPayDates[i] = coupon->date();
            arguments->fixedResetDates[i] = coupon->accrualStartDate();
            arguments->fixedCoupons[i] = coupon->amount();
        }
        const Leg& yoyCoupons = yoyLeg();
        arguments->yoyResetDates = arguments->yoyPayDates =
        arguments->yoyFixingDates =
        std::vector<Date>(yoyCoupons.size());
        arguments->yoyAccrualTimes =
        std::vector<Time>(yoyCoupons.size());
        arguments->yoySpreads =
        std::vector<Spread>(yoyCoupons.size());
        arguments->yoyCoupons = std::vector<Real>(yoyCoupons.size());
        for (Size i=0; i<yoyCoupons.size(); ++i) {
            boost::shared_ptr<YoYInflationCoupon> coupon =
            boost::dynamic_pointer_cast<YoYInflationCoupon>(yoyCoupons[i]);
            arguments->yoyResetDates[i] = coupon->accrualStartDate();
            arguments->yoyPayDates[i] = coupon->date();
            arguments->yoyFixingDates[i] = coupon->fixingDate();
            arguments->yoyAccrualTimes[i] = coupon->accrualPeriod();
            arguments->yoySpreads[i] = coupon->spread();
            try {
                arguments->yoyCoupons[i] = coupon->amount();
            } catch (Error&) {
                arguments->yoyCoupons[i] = Null<Real>();
            }
        }
    }
void QuantLib::YearOnYearInflationSwap::setupExpired () const [private, virtual]
This method must leave the instrument in a consistent state when the expiration condition is met.
Reimplemented from QuantLib::Swap.
Definition at line 166 of file yearonyearinflationswap.cpp.
References fairRate_, fairSpread_, and QuantLib::Swap::legBPS_.
{
        Swap::setupExpired();
        legBPS_[0] = legBPS_[1] = 0.0;
        fairRate_ = Null<Rate>();
        fairSpread_ = Null<Spread>();
    }
Spread QuantLib::YearOnYearInflationSwap::spread () const [inline, virtual]
Definition at line 186 of file yearonyearinflationswap.hpp.
References spread_.
{
        return spread_;
    }
YearOnYearInflationSwap::Type QuantLib::YearOnYearInflationSwap::type () const [inline, virtual]
Definition at line 158 of file yearonyearinflationswap.hpp.
References type_.
{
        return type_;
    }
const DayCounter & QuantLib::YearOnYearInflationSwap::yoyDayCount () const [inline, virtual]
Definition at line 190 of file yearonyearinflationswap.hpp.
References yoyDayCount_.
{
        return yoyDayCount_;
    }
const boost::shared_ptr< YoYInflationIndex > & QuantLib::YearOnYearInflationSwap::yoyInflationIndex () const [inline, virtual]
Definition at line 182 of file yearonyearinflationswap.hpp.
References yoyIndex_.
{
        return yoyIndex_;
    }
const Leg & QuantLib::YearOnYearInflationSwap::yoyLeg () const [inline, virtual]
Definition at line 202 of file yearonyearinflationswap.hpp.
References QuantLib::Swap::legs_.
Referenced by setupArguments(), and YearOnYearInflationSwap().
{
        return legs_[1];
    }
Real QuantLib::YearOnYearInflationSwap::yoyLegNPV () const [virtual]
Definition at line 160 of file yearonyearinflationswap.cpp.
References QuantLib::Instrument::calculate(), QuantLib::Swap::legNPV_, and QL_REQUIRE.
{
        calculate();
        QL_REQUIRE(legNPV_[1] != Null<Real>(), "result not available");
        return legNPV_[1];
    }
const Schedule & QuantLib::YearOnYearInflationSwap::yoySchedule () const [inline, virtual]
Definition at line 178 of file yearonyearinflationswap.hpp.
References yoySchedule_.
{
        return yoySchedule_;
    }
Member Data Documentation
Rate QuantLib::YearOnYearInflationSwap::fairRate_ [mutable, private]
Definition at line 118 of file yearonyearinflationswap.hpp.
Referenced by fairRate(), fetchResults(), and setupExpired().
Spread QuantLib::YearOnYearInflationSwap::fairSpread_ [mutable, private]
Definition at line 119 of file yearonyearinflationswap.hpp.
Referenced by fairSpread(), fetchResults(), and setupExpired().
DayCounter QuantLib::YearOnYearInflationSwap::fixedDayCount_ [private]
Definition at line 109 of file yearonyearinflationswap.hpp.
Referenced by fixedDayCount(), and YearOnYearInflationSwap().
Rate QuantLib::YearOnYearInflationSwap::fixedRate_ [private]
Definition at line 108 of file yearonyearinflationswap.hpp.
Referenced by fetchResults(), fixedRate(), and YearOnYearInflationSwap().
Schedule QuantLib::YearOnYearInflationSwap::fixedSchedule_ [private]
Definition at line 107 of file yearonyearinflationswap.hpp.
Referenced by fixedSchedule(), and YearOnYearInflationSwap().
Real QuantLib::YearOnYearInflationSwap::nominal_ [private]
Definition at line 106 of file yearonyearinflationswap.hpp.
Referenced by nominal(), setupArguments(), and YearOnYearInflationSwap().
Period QuantLib::YearOnYearInflationSwap::observationLag_ [private]
Definition at line 112 of file yearonyearinflationswap.hpp.
Referenced by observationLag(), and YearOnYearInflationSwap().
Calendar QuantLib::YearOnYearInflationSwap::paymentCalendar_ [private]
Definition at line 115 of file yearonyearinflationswap.hpp.
Referenced by paymentCalendar(), and YearOnYearInflationSwap().
BusinessDayConvention QuantLib::YearOnYearInflationSwap::paymentConvention_ [private]
Definition at line 116 of file yearonyearinflationswap.hpp.
Referenced by paymentConvention(), and YearOnYearInflationSwap().
Spread QuantLib::YearOnYearInflationSwap::spread_ [private]
Definition at line 113 of file yearonyearinflationswap.hpp.
Referenced by fetchResults(), spread(), and YearOnYearInflationSwap().
Type QuantLib::YearOnYearInflationSwap::type_ [private]
Definition at line 105 of file yearonyearinflationswap.hpp.
Referenced by setupArguments(), type(), and YearOnYearInflationSwap().
DayCounter QuantLib::YearOnYearInflationSwap::yoyDayCount_ [private]
Definition at line 114 of file yearonyearinflationswap.hpp.
Referenced by YearOnYearInflationSwap(), and yoyDayCount().
boost::shared_ptr<YoYInflationIndex> QuantLib::YearOnYearInflationSwap::yoyIndex_ [private]
Definition at line 111 of file yearonyearinflationswap.hpp.
Referenced by YearOnYearInflationSwap(), and yoyInflationIndex().
Schedule QuantLib::YearOnYearInflationSwap::yoySchedule_ [private]
Definition at line 110 of file yearonyearinflationswap.hpp.
Referenced by YearOnYearInflationSwap(), and yoySchedule().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/yearonyearinflationswap.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/yearonyearinflationswap.cpp