QuantLib: QuantLib::VanillaSwap Class Reference
QuantLib::VanillaSwap Class Reference
Plain-vanilla swap: fix vs floating leg.
#include <vanillaswap.hpp>
Classes
class arguments
Arguments for simple swap calculation
class engine
class results
Results from simple swap calculation
Public Types
enum Type { Receiver = -1, Payer = 1 }
Public Member Functions
VanillaSwap (Type type, Real nominal, const Schedule &fixedSchedule, Rate fixedRate, const DayCounter &fixedDayCount, const Schedule &floatSchedule, const boost::shared_ptr< IborIndex > &iborIndex, Spread spread, const DayCounter &floatingDayCount, boost::optional< BusinessDayConvention > paymentConvention=boost::none)
void setupArguments (PricingEngine::arguments *args) const
void fetchResults (const PricingEngine::results *) const
Inspectors
Type type () const
Real nominal () const
const Schedule & fixedSchedule () const
Rate fixedRate () const
const DayCounter & fixedDayCount () const
const Schedule & floatingSchedule () const
const boost::shared_ptr
< IborIndex > & iborIndex () const
Spread spread () const
const DayCounter & floatingDayCount () const
BusinessDayConvention paymentConvention () const
const Leg & fixedLeg () const
const Leg & floatingLeg () const
Results
Real fixedLegBPS () const
Real fixedLegNPV () const
Rate fairRate () const
Real floatingLegBPS () const
Real floatingLegNPV () const
Spread fairSpread () const
Private Member Functions
void setupExpired () const
Private Attributes
Type type_
Real nominal_
Schedule fixedSchedule_
Rate fixedRate_
DayCounter fixedDayCount_
Schedule floatingSchedule_
boost::shared_ptr< IborIndex > iborIndex_
Spread spread_
DayCounter floatingDayCount_
BusinessDayConvention paymentConvention_
Rate fairRate_
Spread fairSpread_
Detailed Description
Plain-vanilla swap: fix vs floating leg.
If no payment convention is passed, the convention of the floating-rate schedule is used.
Warning:
if Settings::includeReferenceDateCashFlows() is set to true, payments occurring at the settlement date of the swap might be included in the NPV and therefore affect the fair-rate and fair-spread calculation. This might not be what you want.
Test:
the correctness of the returned value is tested by checking that the price of a swap paying the fair fixed rate is null.
the correctness of the returned value is tested by checking that the price of a swap receiving the fair floating-rate spread is null.
the correctness of the returned value is tested by checking that the price of a swap decreases with the paid fixed rate.
the correctness of the returned value is tested by checking that the price of a swap increases with the received floating-rate spread.
the correctness of the returned value is tested by checking it against a known good value.
Definition at line 65 of file vanillaswap.hpp.
Member Enumeration Documentation
enum QuantLib::VanillaSwap::Type
Enumerator:
Receiver
Payer
Definition at line 67 of file vanillaswap.hpp.
{ Receiver = -1, Payer = 1 };
Constructor & Destructor Documentation
QuantLib::VanillaSwap::VanillaSwap (Type type, Real nominal, const Schedule & fixedSchedule, Rate fixedRate, const DayCounter & fixedDayCount, const Schedule & floatSchedule, const boost::shared_ptr< IborIndex > & iborIndex, Spread spread, const DayCounter & floatingDayCount, boost::optional< BusinessDayConvention > paymentConvention = boost::none)
Definition at line 33 of file vanillaswap.cpp.
References QuantLib::Schedule::businessDayConvention(), fixedDayCount_, fixedRate_, fixedSchedule_, floatingDayCount_, floatingSchedule_, iborIndex_, QuantLib::Swap::legs_, nominal_, Payer, QuantLib::Swap::payer_, paymentConvention(), paymentConvention_, QL_FAIL, Receiver, QuantLib::Observer::registerWith(), spread_, type_, QuantLib::FixedRateLeg::withCouponRates(), QuantLib::IborLeg::withNotionals(), QuantLib::FixedRateLeg::withNotionals(), QuantLib::IborLeg::withPaymentAdjustment(), QuantLib::FixedRateLeg::withPaymentAdjustment(), QuantLib::IborLeg::withPaymentDayCounter(), and QuantLib::IborLeg::withSpreads().
    : Swap(2), type_(type), nominal_(nominal),
      fixedSchedule_(fixedSchedule), fixedRate_(fixedRate),
      fixedDayCount_(fixedDayCount),
      floatingSchedule_(floatSchedule), iborIndex_(iborIndex), spread_(spread),
      floatingDayCount_(floatingDayCount) {
        if (paymentConvention)
            paymentConvention_ = *paymentConvention;
        else
            paymentConvention_ = floatingSchedule_.businessDayConvention();
        legs_[0] = FixedRateLeg(fixedSchedule_)
            .withNotionals(nominal_)
            .withCouponRates(fixedRate_, fixedDayCount_)
            .withPaymentAdjustment(paymentConvention_);
        legs_[1] = IborLeg(floatingSchedule_, iborIndex_)
            .withNotionals(nominal_)
            .withPaymentDayCounter(floatingDayCount_)
            .withPaymentAdjustment(paymentConvention_)
            .withSpreads(spread_);
        for (Leg::const_iterator i = legs_[1].begin(); i < legs_[1].end(); ++i)
            registerWith(*i);
        switch (type_) {
          case Payer:
            payer_[0] = -1.0;
            payer_[1] = +1.0;
            break;
          case Receiver:
            payer_[0] = +1.0;
            payer_[1] = -1.0;
            break;
          default:
            QL_FAIL("Unknown vanilla-swap type");
        }
    }
Member Function Documentation
Rate QuantLib::VanillaSwap::fairRate () const
Definition at line 138 of file vanillaswap.cpp.
References QuantLib::Instrument::calculate(), fairRate_, and QL_REQUIRE.
Referenced by QuantLib::LfmSwaptionEngine::calculate(), QuantLib::BlackSwaptionEngine::calculate(), QuantLib::VanillaSwap::results::reset(), QuantLib::SwaptionHelper::SwaptionHelper(), anonymous_namespace{piecewiseyieldcurve.cpp}::testCurveConsistency(), PiecewiseYieldCurveTest::testJpyLibor(), and PiecewiseYieldCurveTest::testLiborFixing().
{
        calculate();
        QL_REQUIRE(fairRate_ != Null<Rate>(), "result not available");
        return fairRate_;
    }
Spread QuantLib::VanillaSwap::fairSpread () const
Definition at line 144 of file vanillaswap.cpp.
References QuantLib::Instrument::calculate(), fairSpread_, and QL_REQUIRE.
Referenced by QuantLib::VanillaSwap::results::reset().
{
        calculate();
        QL_REQUIRE(fairSpread_ != Null<Spread>(), "result not available");
        return fairSpread_;
    }
void QuantLib::VanillaSwap::fetchResults (const PricingEngine::results * r) const [virtual]
When a derived result structure is defined for an instrument, this method should be overridden to read from it. This is mandatory in case a pricing engine is used.
Reimplemented from QuantLib::Swap.
Definition at line 181 of file vanillaswap.cpp.
References QuantLib::VanillaSwap::results::fairRate, fairRate_, QuantLib::VanillaSwap::results::fairSpread, fairSpread_, fixedRate_, QuantLib::Swap::legBPS_, QuantLib::Instrument::NPV_, and spread_.
{
        static const Spread basisPoint = 1.0e-4;
        Swap::fetchResults(r);
        const VanillaSwap::results* results =
            dynamic_cast<const VanillaSwap::results*>(r);
        if (results) { // might be a swap engine, so no error is thrown
            fairRate_ = results->fairRate;
            fairSpread_ = results->fairSpread;
        } else {
            fairRate_ = Null<Rate>();
            fairSpread_ = Null<Spread>();
        }
        if (fairRate_ == Null<Rate>()) {
            // calculate it from other results
            if (legBPS_[0] != Null<Real>())
                fairRate_ = fixedRate_ - NPV_/(legBPS_[0]/basisPoint);
        }
        if (fairSpread_ == Null<Spread>()) {
            // ditto
            if (legBPS_[1] != Null<Real>())
                fairSpread_ = spread_ - NPV_/(legBPS_[1]/basisPoint);
        }
    }
const DayCounter & QuantLib::VanillaSwap::fixedDayCount () const [inline]
Definition at line 185 of file vanillaswap.hpp.
References fixedDayCount_.
{
        return fixedDayCount_;
    }
const Leg & QuantLib::VanillaSwap::fixedLeg () const [inline]
Definition at line 209 of file vanillaswap.hpp.
References QuantLib::Swap::legs_.
Referenced by QuantLib::BlackSwaptionEngine::calculate(), and setupArguments().
{
        return legs_[0];
    }
Real QuantLib::VanillaSwap::fixedLegBPS () const
Definition at line 150 of file vanillaswap.cpp.
References QuantLib::Instrument::calculate(), QuantLib::Swap::legBPS_, and QL_REQUIRE.
Referenced by QuantLib::LfmSwaptionEngine::calculate(), QuantLib::G2SwaptionEngine::calculate(), and QuantLib::BlackSwaptionEngine::calculate().
{
        calculate();
        QL_REQUIRE(legBPS_[0] != Null<Real>(), "result not available");
        return legBPS_[0];
    }
Real QuantLib::VanillaSwap::fixedLegNPV () const
Definition at line 162 of file vanillaswap.cpp.
References QuantLib::Instrument::calculate(), QuantLib::Swap::legNPV_, and QL_REQUIRE.
{
        calculate();
        QL_REQUIRE(legNPV_[0] != Null<Real>(), "result not available");
        return legNPV_[0];
    }
Rate QuantLib::VanillaSwap::fixedRate () const [inline]
Definition at line 181 of file vanillaswap.hpp.
References fixedRate_.
Referenced by QuantLib::LfmSwaptionEngine::calculate(), QuantLib::G2SwaptionEngine::calculate(), and QuantLib::BlackSwaptionEngine::calculate().
{
        return fixedRate_;
    }
const Schedule & QuantLib::VanillaSwap::fixedSchedule () const [inline]
Definition at line 177 of file vanillaswap.hpp.
References fixedSchedule_.
{
        return fixedSchedule_;
    }
const DayCounter & QuantLib::VanillaSwap::floatingDayCount () const [inline]
Definition at line 201 of file vanillaswap.hpp.
References floatingDayCount_.
{
        return floatingDayCount_;
    }
const Leg & QuantLib::VanillaSwap::floatingLeg () const [inline]
Definition at line 213 of file vanillaswap.hpp.
References QuantLib::Swap::legs_.
Referenced by setupArguments().
{
        return legs_[1];
    }
Real QuantLib::VanillaSwap::floatingLegBPS () const
Definition at line 156 of file vanillaswap.cpp.
References QuantLib::Instrument::calculate(), QuantLib::Swap::legBPS_, and QL_REQUIRE.
Referenced by QuantLib::LfmSwaptionEngine::calculate(), QuantLib::G2SwaptionEngine::calculate(), and QuantLib::BlackSwaptionEngine::calculate().
{
        calculate();
        QL_REQUIRE(legBPS_[1] != Null<Real>(), "result not available");
        return legBPS_[1];
    }
Real QuantLib::VanillaSwap::floatingLegNPV () const
Definition at line 168 of file vanillaswap.cpp.
References QuantLib::Instrument::calculate(), QuantLib::Swap::legNPV_, and QL_REQUIRE.
{
        calculate();
        QL_REQUIRE(legNPV_[1] != Null<Real>(), "result not available");
        return legNPV_[1];
    }
const Schedule & QuantLib::VanillaSwap::floatingSchedule () const [inline]
Definition at line 189 of file vanillaswap.hpp.
References floatingSchedule_.
{
        return floatingSchedule_;
    }
const boost::shared_ptr< IborIndex > & QuantLib::VanillaSwap::iborIndex () const [inline]
Definition at line 193 of file vanillaswap.hpp.
References iborIndex_.
{
        return iborIndex_;
    }
Real QuantLib::VanillaSwap::nominal () const [inline]
Definition at line 173 of file vanillaswap.hpp.
References nominal_.
{
        return nominal_;
    }
BusinessDayConvention QuantLib::VanillaSwap::paymentConvention () const [inline]
Definition at line 205 of file vanillaswap.hpp.
References paymentConvention_.
Referenced by VanillaSwap().
{
        return paymentConvention_;
    }
void QuantLib::VanillaSwap::setupArguments (PricingEngine::arguments *) const [virtual]
When a derived argument structure is defined for an instrument, this method should be overridden to fill it. This is mandatory in case a pricing engine is used.
Reimplemented from QuantLib::Swap.
Definition at line 82 of file vanillaswap.cpp.
References QuantLib::VanillaSwap::arguments::fixedCoupons, fixedLeg(), QuantLib::VanillaSwap::arguments::fixedPayDates, QuantLib::VanillaSwap::arguments::fixedResetDates, QuantLib::VanillaSwap::arguments::floatingAccrualTimes, QuantLib::VanillaSwap::arguments::floatingCoupons, QuantLib::VanillaSwap::arguments::floatingFixingDates, floatingLeg(), QuantLib::VanillaSwap::arguments::floatingPayDates, QuantLib::VanillaSwap::arguments::floatingResetDates, QuantLib::VanillaSwap::arguments::floatingSpreads, QuantLib::VanillaSwap::arguments::nominal, nominal_, QuantLib::VanillaSwap::arguments::type, and type_.
{
        Swap::setupArguments(args);
        VanillaSwap::arguments* arguments =
            dynamic_cast<VanillaSwap::arguments*>(args);
        if (!arguments)  // it's a swap engine...
            return;
        arguments->type = type_;
        arguments->nominal = nominal_;
        const Leg& fixedCoupons = fixedLeg();
        arguments->fixedResetDates = arguments->fixedPayDates =
            std::vector<Date>(fixedCoupons.size());
        arguments->fixedCoupons = std::vector<Real>(fixedCoupons.size());
        for (Size i=0; i<fixedCoupons.size(); ++i) {
            boost::shared_ptr<FixedRateCoupon> coupon =
                boost::dynamic_pointer_cast<FixedRateCoupon>(fixedCoupons[i]);
            arguments->fixedPayDates[i] = coupon->date();
            arguments->fixedResetDates[i] = coupon->accrualStartDate();
            arguments->fixedCoupons[i] = coupon->amount();
        }
        const Leg& floatingCoupons = floatingLeg();
        arguments->floatingResetDates = arguments->floatingPayDates =
            arguments->floatingFixingDates =
            std::vector<Date>(floatingCoupons.size());
        arguments->floatingAccrualTimes =
            std::vector<Time>(floatingCoupons.size());
        arguments->floatingSpreads =
            std::vector<Spread>(floatingCoupons.size());
        arguments->floatingCoupons = std::vector<Real>(floatingCoupons.size());
        for (Size i=0; i<floatingCoupons.size(); ++i) {
            boost::shared_ptr<IborCoupon> coupon =
                boost::dynamic_pointer_cast<IborCoupon>(floatingCoupons[i]);
            arguments->floatingResetDates[i] = coupon->accrualStartDate();
            arguments->floatingPayDates[i] = coupon->date();
            arguments->floatingFixingDates[i] = coupon->fixingDate();
            arguments->floatingAccrualTimes[i] = coupon->accrualPeriod();
            arguments->floatingSpreads[i] = coupon->spread();
            try {
                arguments->floatingCoupons[i] = coupon->amount();
            } catch (Error&) {
                arguments->floatingCoupons[i] = Null<Real>();
            }
        }
    }
void QuantLib::VanillaSwap::setupExpired () const [private, virtual]
This method must leave the instrument in a consistent state when the expiration condition is met.
Reimplemented from QuantLib::Swap.
Definition at line 174 of file vanillaswap.cpp.
References fairRate_, fairSpread_, and QuantLib::Swap::legBPS_.
{
        Swap::setupExpired();
        legBPS_[0] = legBPS_[1] = 0.0;
        fairRate_ = Null<Rate>();
        fairSpread_ = Null<Spread>();
    }
Spread QuantLib::VanillaSwap::spread () const [inline]
Definition at line 197 of file vanillaswap.hpp.
References spread_.
Referenced by QuantLib::LfmSwaptionEngine::calculate(), QuantLib::G2SwaptionEngine::calculate(), and QuantLib::BlackSwaptionEngine::calculate().
{
        return spread_;
    }
VanillaSwap::Type QuantLib::VanillaSwap::type () const [inline]
Definition at line 169 of file vanillaswap.hpp.
References type_.
{
        return type_;
    }
Member Data Documentation
Rate QuantLib::VanillaSwap::fairRate_ [mutable, private]
Definition at line 129 of file vanillaswap.hpp.
Referenced by fairRate(), fetchResults(), and setupExpired().
Spread QuantLib::VanillaSwap::fairSpread_ [mutable, private]
Definition at line 130 of file vanillaswap.hpp.
Referenced by fairSpread(), fetchResults(), and setupExpired().
DayCounter QuantLib::VanillaSwap::fixedDayCount_ [private]
Definition at line 122 of file vanillaswap.hpp.
Referenced by fixedDayCount(), and VanillaSwap().
Rate QuantLib::VanillaSwap::fixedRate_ [private]
Definition at line 121 of file vanillaswap.hpp.
Referenced by fetchResults(), fixedRate(), and VanillaSwap().
Schedule QuantLib::VanillaSwap::fixedSchedule_ [private]
Definition at line 120 of file vanillaswap.hpp.
Referenced by fixedSchedule(), and VanillaSwap().
DayCounter QuantLib::VanillaSwap::floatingDayCount_ [private]
Definition at line 126 of file vanillaswap.hpp.
Referenced by floatingDayCount(), and VanillaSwap().
Schedule QuantLib::VanillaSwap::floatingSchedule_ [private]
Definition at line 123 of file vanillaswap.hpp.
Referenced by floatingSchedule(), and VanillaSwap().
boost::shared_ptr<IborIndex> QuantLib::VanillaSwap::iborIndex_ [private]
Definition at line 124 of file vanillaswap.hpp.
Referenced by iborIndex(), and VanillaSwap().
Real QuantLib::VanillaSwap::nominal_ [private]
Definition at line 119 of file vanillaswap.hpp.
Referenced by nominal(), setupArguments(), and VanillaSwap().
BusinessDayConvention QuantLib::VanillaSwap::paymentConvention_ [private]
Definition at line 127 of file vanillaswap.hpp.
Referenced by paymentConvention(), and VanillaSwap().
Spread QuantLib::VanillaSwap::spread_ [private]
Definition at line 125 of file vanillaswap.hpp.
Referenced by fetchResults(), spread(), and VanillaSwap().
Type QuantLib::VanillaSwap::type_ [private]
Definition at line 118 of file vanillaswap.hpp.
Referenced by setupArguments(), type(), and VanillaSwap().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/vanillaswap.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/vanillaswap.cpp