QuantLib: QuantLib::ImpliedVolTermStructure Class Reference
QuantLib::ImpliedVolTermStructure Class Reference
Implied vol term structure at a given date in the future.
#include <impliedvoltermstructure.hpp>
Public Member Functions
ImpliedVolTermStructure (const Handle< BlackVolTermStructure > &origTS, const Date &referenceDate)
TermStructure interface
DayCounter dayCounter () const
the day counter used for date/time conversion
Date maxDate () const
the latest date for which the curve can return values
VolatilityTermStructure interface
Real minStrike () const
the minimum strike for which the term structure can return vols
Real maxStrike () const
the maximum strike for which the term structure can return vols
Visitability
virtual void accept (AcyclicVisitor &)
Protected Member Functions
virtual Real blackVarianceImpl (Time t, Real strike) const
Black variance calculation.
Private Attributes
Handle< BlackVolTermStructure > originalTS_
Detailed Description
Implied vol term structure at a given date in the future.
The given date will be the implied reference date.
Note:
This term structure will remain linked to the original structure, i.e., any changes in the latter will be reflected in this structure as well.
Warning:
It doesn't make financial sense to have an asset-dependant implied Vol Term Structure. This class should be used with term structures that are time dependant only.
Definition at line 42 of file impliedvoltermstructure.hpp.
Constructor & Destructor Documentation
QuantLib::ImpliedVolTermStructure::ImpliedVolTermStructure (const Handle< BlackVolTermStructure > & origTS, const Date & referenceDate) [inline]
Definition at line 69 of file impliedvoltermstructure.hpp.
References originalTS_, and QuantLib::Observer::registerWith().
    : BlackVarianceTermStructure(referenceDate), originalTS_(originalTS) {
        registerWith(originalTS_);
    }
Member Function Documentation
void QuantLib::ImpliedVolTermStructure::accept (AcyclicVisitor & v) [inline, virtual]
Reimplemented from QuantLib::BlackVarianceTermStructure.
Definition at line 88 of file impliedvoltermstructure.hpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Visitor< T >::visit().
{
        Visitor<ImpliedVolTermStructure>* v1 =
            dynamic_cast<Visitor<ImpliedVolTermStructure>*>(&v);
        if (v1 != 0)
            v1->visit(*this);
        else
            BlackVarianceTermStructure::accept(v);
    }
Real QuantLib::ImpliedVolTermStructure::blackVarianceImpl (Time t, Real strike) const [inline, protected, virtual]
Black variance calculation.
Implements QuantLib::BlackVolTermStructure.
Definition at line 97 of file impliedvoltermstructure.hpp.
References dayCounter(), originalTS_, QuantLib::TermStructure::referenceDate(), and QuantLib::DayCounter::yearFraction().
{
        /* timeShift (and/or variance) variance at evaluation date
           cannot be cached since the original curve could change
           between invocations of this method */
        Time timeShift =
            dayCounter().yearFraction(originalTS_->referenceDate(),
                                      referenceDate());
        /* t is relative to the current reference date
           and needs to be converted to the time relative
           to the reference date of the original curve */
        return originalTS_->blackForwardVariance(timeShift,
                                                 timeShift+t,
                                                 strike,
                                                 true);
    }
DayCounter QuantLib::ImpliedVolTermStructure::dayCounter () const [inline, virtual]
the day counter used for date/time conversion
Reimplemented from QuantLib::TermStructure.
Definition at line 48 of file impliedvoltermstructure.hpp.
References originalTS_.
Referenced by blackVarianceImpl().
{ return originalTS_->dayCounter(); }
Date QuantLib::ImpliedVolTermStructure::maxDate () const [inline, virtual]
the latest date for which the curve can return values
Implements QuantLib::TermStructure.
Definition at line 76 of file impliedvoltermstructure.hpp.
References originalTS_.
{
        return originalTS_->maxDate();
    }
Real QuantLib::ImpliedVolTermStructure::maxStrike () const [inline, virtual]
the maximum strike for which the term structure can return vols
Implements QuantLib::VolatilityTermStructure.
Definition at line 84 of file impliedvoltermstructure.hpp.
References originalTS_.
{
        return originalTS_->maxStrike();
    }
Real QuantLib::ImpliedVolTermStructure::minStrike () const [inline, virtual]
the minimum strike for which the term structure can return vols
Implements QuantLib::VolatilityTermStructure.
Definition at line 80 of file impliedvoltermstructure.hpp.
References originalTS_.
{
        return originalTS_->minStrike();
    }
Member Data Documentation
Handle<BlackVolTermStructure> QuantLib::ImpliedVolTermStructure::originalTS_ [private]
Definition at line 63 of file impliedvoltermstructure.hpp.
Referenced by blackVarianceImpl(), dayCounter(), ImpliedVolTermStructure(), maxDate(), maxStrike(), and minStrike().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/equityfx/impliedvoltermstructure.hpp