QuantLib: QuantLib::LmCorrelationModel Class Reference
QuantLib::LmCorrelationModel Class Reference
libor forward correlation model
#include <lmcorrmodel.hpp>
Public Member Functions
LmCorrelationModel (Size size, Size nArguments)
virtual ~LmCorrelationModel ()
virtual Size size () const
virtual Size factors () const
std::vector< Parameter > & params ()
void setParams (const std::vector< Parameter > &arguments)
virtual Disposable< Matrix > correlation (Time t, const Array &x=Null< Array >()) const =0
virtual Disposable< Matrix > pseudoSqrt (Time t, const Array &x=Null< Array >()) const
virtual Real correlation (Size i, Size j, Time t, const Array &x=Null< Array >()) const
virtual bool isTimeIndependent () const
Protected Member Functions
virtual void generateArguments ()=0
Protected Attributes
const Size size_
std::vector< Parameter > arguments_
Detailed Description
libor forward correlation model
Definition at line 35 of file lmcorrmodel.hpp.
Constructor & Destructor Documentation
QuantLib::LmCorrelationModel::LmCorrelationModel (Size size, Size nArguments)
Definition at line 25 of file lmcorrmodel.cpp.
    : size_(size), arguments_(nArguments) {}
virtual QuantLib::LmCorrelationModel::~LmCorrelationModel () [inline, virtual]
Definition at line 38 of file lmcorrmodel.hpp.
{}
Member Function Documentation
virtual Disposable<Matrix> QuantLib::LmCorrelationModel::correlation (Time t, const Array & x = Null< Array >()) const [pure virtual]
Implemented in QuantLib::LmLinearExponentialCorrelationModel, QuantLib::LmExponentialCorrelationModel, and QuantLib::LmConstWrapperCorrelationModel.
Referenced by correlation(), and pseudoSqrt().
Real QuantLib::LmCorrelationModel::correlation (Size i, Size j, Time t, const Array & x = Null<Array>()) const [virtual]
Reimplemented in QuantLib::LmLinearExponentialCorrelationModel, QuantLib::LmExponentialCorrelationModel, and QuantLib::LmConstWrapperCorrelationModel.
Definition at line 46 of file lmcorrmodel.cpp.
References correlation().
{
        // inefficient implementation, please overload in derived classes
        return correlation(t, x)[i][j];
    }
Size QuantLib::LmCorrelationModel::factors () const [virtual]
Reimplemented in QuantLib::LmLinearExponentialCorrelationModel, and QuantLib::LmConstWrapperCorrelationModel.
Definition at line 32 of file lmcorrmodel.cpp.
References size_.
{
        return size_;
    }
virtual void QuantLib::LmCorrelationModel::generateArguments () [protected, pure virtual]
Implemented in QuantLib::LmConstWrapperCorrelationModel, QuantLib::LmLinearExponentialCorrelationModel, and QuantLib::LmExponentialCorrelationModel.
Referenced by setParams().
bool QuantLib::LmCorrelationModel::isTimeIndependent () const [virtual]
Reimplemented in QuantLib::LmLinearExponentialCorrelationModel, QuantLib::LmConstWrapperCorrelationModel, and QuantLib::LmExponentialCorrelationModel.
Definition at line 36 of file lmcorrmodel.cpp.
{
        return false;
    }
std::vector< Parameter > & QuantLib::LmCorrelationModel::params ()
Definition at line 53 of file lmcorrmodel.cpp.
References arguments_.
{
        return arguments_;
    }
Disposable< Matrix > QuantLib::LmCorrelationModel::pseudoSqrt (Time t, const Array & x = Null<Array>()) const [virtual]
Reimplemented in QuantLib::LmLinearExponentialCorrelationModel, QuantLib::LmExponentialCorrelationModel, and QuantLib::LmConstWrapperCorrelationModel.
Definition at line 40 of file lmcorrmodel.cpp.
References correlation(), and QuantLib::SalvagingAlgorithm::Spectral.
{
        return QuantLib::pseudoSqrt(this->correlation(t, x),
                                    SalvagingAlgorithm::Spectral);
    }
void QuantLib::LmCorrelationModel::setParams (const std::vector< Parameter > & arguments)
Definition at line 57 of file lmcorrmodel.cpp.
References arguments_, and generateArguments().
{
        arguments_ = arguments;
        generateArguments();
    }
Size QuantLib::LmCorrelationModel::size () const [virtual]
Definition at line 28 of file lmcorrmodel.cpp.
References size_.
{
        return size_;
    }
Member Data Documentation
std::vector<Parameter> QuantLib::LmCorrelationModel::arguments_ [protected]
Definition at line 60 of file lmcorrmodel.hpp.
Referenced by QuantLib::LmExponentialCorrelationModel::generateArguments(), QuantLib::LmLinearExponentialCorrelationModel::generateArguments(), QuantLib::LmExponentialCorrelationModel::LmExponentialCorrelationModel(), QuantLib::LmLinearExponentialCorrelationModel::LmLinearExponentialCorrelationModel(), params(), and setParams().
const Size QuantLib::LmCorrelationModel::size_ [protected]
Definition at line 58 of file lmcorrmodel.hpp.
Referenced by factors(), QuantLib::LmExponentialCorrelationModel::generateArguments(), QuantLib::LmLinearExponentialCorrelationModel::generateArguments(), and size().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/legacy/libormarketmodels/lmcorrmodel.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/legacy/libormarketmodels/lmcorrmodel.cpp