QuantLib: QuantLib::GFunctionFactory::GFunctionWithShifts Class Reference
QuantLib::GFunctionFactory::GFunctionWithShifts Class Reference
Classes
class ObjectiveFunction
Public Member Functions
GFunctionWithShifts (const CmsCoupon &coupon, const Handle< Quote > &meanReversion)
Real operator() (Real x)
Real firstDerivative (Real x)
Real secondDerivative (Real x)
Private Member Functions
Real shapeOfShift (Real s) const
Real calibrationOfShift (Real Rs)
Real functionZ (Real x)
Real derRs_derX (Real x)
Real derZ_derX (Real x)
Real der2Rs_derX2 (Real x)
Real der2Z_derX2 (Real x)
Private Attributes
Time swapStartTime_
Time shapedPaymentTime_
std::vector< Time > shapedSwapPaymentTimes_
std::vector< Time > accruals_
std::vector< Real > swapPaymentDiscounts_
Real discountAtStart_
Real discountRatio_
Real swapRateValue_
Handle< Quote > meanReversion_
Real calibratedShift_
Real tmpRs_
const Real accuracy_
boost::shared_ptr
< ObjectiveFunction > objectiveFunction_
Friends
class ObjectiveFunction
Detailed Description
Definition at line 123 of file conundrumpricer.hpp.
Constructor & Destructor Documentation
QuantLib::GFunctionFactory::GFunctionWithShifts::GFunctionWithShifts (const CmsCoupon & coupon, const Handle< Quote > & meanReversion)
Definition at line 660 of file conundrumpricer.cpp.
References accruals_, QuantLib::Coupon::date(), discountAtStart_, discountRatio_, QuantLib::FloatingRateCoupon::fixingDate(), ObjectiveFunction, objectiveFunction_, shapedPaymentTime_, shapedSwapPaymentTimes_, shapeOfShift(), QuantLib::swap(), QuantLib::CmsCoupon::swapIndex(), swapPaymentDiscounts_, swapRateValue_, swapStartTime_, and QuantLib::DayCounter::yearFraction().
    : meanReversion_(meanReversion), calibratedShift_(0.03),
      tmpRs_(10000000.0), accuracy_( 1.0e-14) {
        const boost::shared_ptr<SwapIndex>& swapIndex = coupon.swapIndex();
        const boost::shared_ptr<VanillaSwap>& swap = swapIndex->underlyingSwap(coupon.fixingDate());
        swapRateValue_ = swap->fairRate();
        objectiveFunction_ = boost::shared_ptr<ObjectiveFunction>(new ObjectiveFunction(*this, swapRateValue_));
        const Schedule& schedule = swap->fixedSchedule();
        Handle<YieldTermStructure> rateCurve =
            swapIndex->forwardingTermStructure();
        const DayCounter& dc = swapIndex->dayCounter();
        swapStartTime_ = dc.yearFraction(rateCurve->referenceDate(),
                                         schedule.startDate());
        discountAtStart_ = rateCurve->discount(schedule.startDate());
        Real paymentTime = dc.yearFraction(rateCurve->referenceDate(),
                                                 coupon.date());
        shapedPaymentTime_ = shapeOfShift(paymentTime);
        const Leg& fixedLeg(swap->fixedLeg());
        Size n = fixedLeg.size();
        accruals_.reserve(n);
        shapedSwapPaymentTimes_.reserve(n);
        swapPaymentDiscounts_.reserve(n);
        for(Size i=0; i<n; ++i) {
            boost::shared_ptr<Coupon> coupon =
                boost::dynamic_pointer_cast<Coupon>(fixedLeg[i]);
            accruals_.push_back(coupon->accrualPeriod());
            const Date paymentDate(coupon->date());
            const double swapPaymentTime(dc.yearFraction(rateCurve->referenceDate(), paymentDate));
            shapedSwapPaymentTimes_.push_back(shapeOfShift(swapPaymentTime));
            swapPaymentDiscounts_.push_back(rateCurve->discount(paymentDate));
        }
        discountRatio_ = swapPaymentDiscounts_.back()/discountAtStart_;
    }
Member Function Documentation
Real QuantLib::GFunctionFactory::GFunctionWithShifts::calibrationOfShift (Real Rs) [private]
Definition at line 866 of file conundrumpricer.cpp.
References anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::accruals_, anonymous_namespace{matrices.cpp}::N, QL_FAIL, QuantLib::Solver1D< Impl >::setMaxEvaluations(), and QuantLib::Solver1D< Impl >::solve().
{
        if(Rs!=tmpRs_){
            Real initialGuess, N=0, D=0;
            for(Size i=0; i<accruals_.size(); i++) {
                N+=accruals_[i]*swapPaymentDiscounts_[i];
                D+=accruals_[i]*swapPaymentDiscounts_[i]*shapedSwapPaymentTimes_[i];
            }
            N *= Rs;
            D *= Rs;
            N += accruals_.back() * swapPaymentDiscounts_.back()
                - objectiveFunction_->gFunctionWithShifts().discountAtStart_;
            D += accruals_.back() * swapPaymentDiscounts_.back()*
                            shapedSwapPaymentTimes_.back();
            initialGuess = N/D;
            objectiveFunction_->setSwapRateValue(Rs);
            Newton solver;
            solver.setMaxEvaluations(1000);
            // these boundaries migth not be big enough if the volatility
            // of big swap rate values is too high . In this case the G function
            // is not even integrable, so better to fix the vol than increasing
            // these values
            const Real lower = -20, upper = 20.;
            try {
                calibratedShift_ = solver.solve(*objectiveFunction_, accuracy_,
                    std::max( std::min(initialGuess, upper*.99), lower*.99),
                    lower, upper);
            } catch (std::exception& e) {
                QL_FAIL("meanReversion: " << meanReversion_->value() <<
                        ", swapRateValue: " << swapRateValue_ <<
                        ", swapStartTime: " << swapStartTime_ <<
                        ", shapedPaymentTime: " << shapedPaymentTime_ <<
                        "\n error message: " << e.what());
            }
            tmpRs_=Rs;
        }
        return calibratedShift_;
    }
Real QuantLib::GFunctionFactory::GFunctionWithShifts::der2Rs_derX2 (Real x) [private]
Definition at line 734 of file conundrumpricer.cpp.
References anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::accruals_, QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow(), and QL_REQUIRE.
{
        Real denOfRfunztion = 0.;
        Real derDenOfRfunztion = 0.;
        Real der2DenOfRfunztion = 0.;
        for(Size i=0; i<accruals_.size(); i++) {
            denOfRfunztion += accruals_[i]*swapPaymentDiscounts_[i]
                *std::exp(-shapedSwapPaymentTimes_[i]*x);
            derDenOfRfunztion -= shapedSwapPaymentTimes_[i]* accruals_[i]*swapPaymentDiscounts_[i]
                *std::exp(-shapedSwapPaymentTimes_[i]*x);
            der2DenOfRfunztion+= shapedSwapPaymentTimes_[i]*shapedSwapPaymentTimes_[i]* accruals_[i]*
                swapPaymentDiscounts_[i]*std::exp(-shapedSwapPaymentTimes_[i]*x);
        }
        const Real denominator = std::pow(denOfRfunztion, 4);
        Real numOfDerR = 0;
        numOfDerR += shapedSwapPaymentTimes_.back()* swapPaymentDiscounts_.back()*
                     std::exp(-shapedSwapPaymentTimes_.back()*x)*denOfRfunztion;
        numOfDerR -= (discountAtStart_ - swapPaymentDiscounts_.back()* std::exp(-shapedSwapPaymentTimes_.back()*x))*
                     derDenOfRfunztion;
        const Real denOfDerR = std::pow(denOfRfunztion,2);
        Real derNumOfDerR = 0.;
        derNumOfDerR -= shapedSwapPaymentTimes_.back()*shapedSwapPaymentTimes_.back()* swapPaymentDiscounts_.back()*
                     std::exp(-shapedSwapPaymentTimes_.back()*x)*denOfRfunztion;
        derNumOfDerR += shapedSwapPaymentTimes_.back()* swapPaymentDiscounts_.back()*
                     std::exp(-shapedSwapPaymentTimes_.back()*x)*derDenOfRfunztion;
        derNumOfDerR -= (shapedSwapPaymentTimes_.back()*swapPaymentDiscounts_.back()*
                        std::exp(-shapedSwapPaymentTimes_.back()*x))* derDenOfRfunztion;
        derNumOfDerR -= (discountAtStart_ - swapPaymentDiscounts_.back()* std::exp(-shapedSwapPaymentTimes_.back()*x))*
                     der2DenOfRfunztion;
        const Real derDenOfDerR = 2*denOfRfunztion*derDenOfRfunztion;
        const Real numerator = derNumOfDerR*denOfDerR -numOfDerR*derDenOfDerR;
        QL_REQUIRE(denominator!=0, "GFunctionWithShifts::der2Rs_derX2: denominator == 0");
        return numerator/denominator;
    }
Real QuantLib::GFunctionFactory::GFunctionWithShifts::der2Z_derX2 (Real x) [private]
Definition at line 787 of file conundrumpricer.cpp.
References QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow(), and QL_REQUIRE.
{
        const Real denOfZfunction = (1.-discountRatio_*std::exp(-shapedSwapPaymentTimes_.back()*x));
        const Real derDenOfZfunction = shapedSwapPaymentTimes_.back()*discountRatio_*std::exp(-shapedSwapPaymentTimes_.back()*x);
        const Real denominator = std::pow(denOfZfunction, 4);
        QL_REQUIRE(denominator!=0, "GFunctionWithShifts::der2Z_derX2: denominator == 0");
        Real numOfDerZ = 0;
        numOfDerZ -= shapedPaymentTime_* std::exp(-shapedPaymentTime_*x)* denOfZfunction;
        numOfDerZ -= shapedSwapPaymentTimes_.back()* std::exp(-shapedPaymentTime_*x)* (1.-denOfZfunction);
        const Real denOfDerZ = std::pow(denOfZfunction,2);
        const Real derNumOfDerZ = (-shapedPaymentTime_* std::exp(-shapedPaymentTime_*x)*
                             (-shapedPaymentTime_+(shapedPaymentTime_*discountRatio_-
                               shapedSwapPaymentTimes_.back()*discountRatio_)* std::exp(-shapedSwapPaymentTimes_.back()*x))
                              -shapedSwapPaymentTimes_.back()*std::exp(-shapedPaymentTime_*x)*
                              (shapedPaymentTime_*discountRatio_- shapedSwapPaymentTimes_.back()*discountRatio_)*
                              std::exp(-shapedSwapPaymentTimes_.back()*x));
        const Real derDenOfDerZ = 2*denOfZfunction*derDenOfZfunction;
        const Real numerator = derNumOfDerZ*denOfDerZ -numOfDerZ*derDenOfDerZ;
        return numerator/denominator;
    }
Real QuantLib::GFunctionFactory::GFunctionWithShifts::derRs_derX (Real x) [private]
Definition at line 714 of file conundrumpricer.cpp.
References anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::accruals_, and QL_REQUIRE.
{
        Real sqrtDenominator = 0;
        Real derSqrtDenominator = 0;
        for(Size i=0; i<accruals_.size(); i++) {
            sqrtDenominator += accruals_[i]*swapPaymentDiscounts_[i]
                *std::exp(-shapedSwapPaymentTimes_[i]*x);
            derSqrtDenominator -= shapedSwapPaymentTimes_[i]* accruals_[i]*swapPaymentDiscounts_[i]
                *std::exp(-shapedSwapPaymentTimes_[i]*x);
        }
        const Real denominator = sqrtDenominator* sqrtDenominator;
        Real numerator = 0;
        numerator += shapedSwapPaymentTimes_.back()* swapPaymentDiscounts_.back()*
                     std::exp(-shapedSwapPaymentTimes_.back()*x)*sqrtDenominator;
        numerator -= (discountAtStart_ - swapPaymentDiscounts_.back()* std::exp(-shapedSwapPaymentTimes_.back()*x))*
                     derSqrtDenominator;
        QL_REQUIRE(denominator!=0, "GFunctionWithShifts::derRs_derX: denominator == 0");
        return numerator/denominator;
    }
Real QuantLib::GFunctionFactory::GFunctionWithShifts::derZ_derX (Real x) [private]
Definition at line 775 of file conundrumpricer.cpp.
References QL_REQUIRE.
{
        const Real sqrtDenominator = (1.-discountRatio_*std::exp(-shapedSwapPaymentTimes_.back()*x));
        const Real denominator = sqrtDenominator* sqrtDenominator;
        QL_REQUIRE(denominator!=0, "GFunctionWithShifts::derZ_derX: denominator == 0");
        Real numerator = 0;
        numerator -= shapedPaymentTime_* std::exp(-shapedPaymentTime_*x)* sqrtDenominator;
        numerator -= shapedSwapPaymentTimes_.back()* std::exp(-shapedPaymentTime_*x)* (1.-sqrtDenominator);
        return numerator/denominator;
    }
Real QuantLib::GFunctionFactory::GFunctionWithShifts::firstDerivative (Real x) [virtual]
Implements QuantLib::GFunction.
Definition at line 811 of file conundrumpricer.cpp.
{
        //Real dRs = 1.0e-8;
        //return (operator()(Rs+dRs)-operator()(Rs-dRs))/(2.0*dRs);
        const Real calibratedShift = calibrationOfShift(Rs);
        return functionZ(calibratedShift) + Rs * derZ_derX(calibratedShift)/derRs_derX(calibratedShift);
    }
Real QuantLib::GFunctionFactory::GFunctionWithShifts::functionZ (Real x) [private]
Definition at line 709 of file conundrumpricer.cpp.
{
        return std::exp(-shapedPaymentTime_*x)
            / (1.-discountRatio_*std::exp(-shapedSwapPaymentTimes_.back()*x));
    }
Real QuantLib::GFunctionFactory::GFunctionWithShifts::operator() (Real x) [virtual]
Implements QuantLib::GFunction.
Definition at line 704 of file conundrumpricer.cpp.
{
        const Real calibratedShift = calibrationOfShift(Rs);
        return Rs* functionZ(calibratedShift);
    }
Real QuantLib::GFunctionFactory::GFunctionWithShifts::secondDerivative (Real x) [virtual]
Implements QuantLib::GFunction.
Definition at line 818 of file conundrumpricer.cpp.
References QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow().
{
        //Real dRs = 1.0e-8;
        //return (firstDerivative(Rs+dRs)-firstDerivative(Rs-dRs))/(2.0*dRs);
        const Real calibratedShift = calibrationOfShift(Rs);
        return 2.*derZ_derX(calibratedShift)/derRs_derX(calibratedShift) +
            Rs * der2Z_derX2(calibratedShift)/std::pow(derRs_derX(calibratedShift),2.)-
            Rs * derZ_derX(calibratedShift)*der2Rs_derX2(calibratedShift)/
            std::pow(derRs_derX(calibratedShift),3.);
    }
Real QuantLib::GFunctionFactory::GFunctionWithShifts::shapeOfShift (Real s) const [private]
Definition at line 855 of file conundrumpricer.cpp.
Referenced by GFunctionWithShifts().
{
        const Real x(s-swapStartTime_);
        Real meanReversion = meanReversion_->value();
        if(meanReversion>0) {
            return (1.-std::exp(-meanReversion*x))/meanReversion;
        }
        else {
            return x;
        }
    }
Friends And Related Function Documentation
friend class ObjectiveFunction [friend]
Definition at line 150 of file conundrumpricer.hpp.
Referenced by GFunctionWithShifts().
Member Data Documentation
std::vector<Time> QuantLib::GFunctionFactory::GFunctionWithShifts::accruals_ [private]
Definition at line 130 of file conundrumpricer.hpp.
Referenced by GFunctionWithShifts().
const Real QuantLib::GFunctionFactory::GFunctionWithShifts::accuracy_ [private]
Definition at line 138 of file conundrumpricer.hpp.
Real QuantLib::GFunctionFactory::GFunctionWithShifts::calibratedShift_ [private]
Definition at line 137 of file conundrumpricer.hpp.
Real QuantLib::GFunctionFactory::GFunctionWithShifts::discountAtStart_ [private]
Definition at line 132 of file conundrumpricer.hpp.
Referenced by GFunctionWithShifts().
Real QuantLib::GFunctionFactory::GFunctionWithShifts::discountRatio_ [private]
Definition at line 132 of file conundrumpricer.hpp.
Referenced by GFunctionWithShifts().
Handle<Quote> QuantLib::GFunctionFactory::GFunctionWithShifts::meanReversion_ [private]
Definition at line 135 of file conundrumpricer.hpp.
boost::shared_ptr<ObjectiveFunction> QuantLib::GFunctionFactory::GFunctionWithShifts::objectiveFunction_ [private]
Definition at line 168 of file conundrumpricer.hpp.
Referenced by GFunctionWithShifts().
Time QuantLib::GFunctionFactory::GFunctionWithShifts::shapedPaymentTime_ [private]
Definition at line 127 of file conundrumpricer.hpp.
Referenced by GFunctionWithShifts().
std::vector<Time> QuantLib::GFunctionFactory::GFunctionWithShifts::shapedSwapPaymentTimes_ [private]
Definition at line 128 of file conundrumpricer.hpp.
Referenced by GFunctionWithShifts().
std::vector<Real> QuantLib::GFunctionFactory::GFunctionWithShifts::swapPaymentDiscounts_ [private]
Definition at line 131 of file conundrumpricer.hpp.
Referenced by GFunctionWithShifts().
Real QuantLib::GFunctionFactory::GFunctionWithShifts::swapRateValue_ [private]
Definition at line 134 of file conundrumpricer.hpp.
Referenced by GFunctionWithShifts().
Time QuantLib::GFunctionFactory::GFunctionWithShifts::swapStartTime_ [private]
Definition at line 125 of file conundrumpricer.hpp.
Referenced by GFunctionWithShifts().
Real QuantLib::GFunctionFactory::GFunctionWithShifts::tmpRs_ [private]
Definition at line 137 of file conundrumpricer.hpp.
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/conundrumpricer.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/conundrumpricer.cpp