QuantLib: QuantLib::IndexManager Class Reference
QuantLib::IndexManager Class Reference
global repository for past index fixings
#include <indexmanager.hpp>
Public Member Functions
bool hasHistory (const std::string &name) const
returns whether historical fixings were stored for the index
const TimeSeries< Real > & getHistory (const std::string &name) const
returns the (possibly empty) history of the index fixings
void setHistory (const std::string &name, const TimeSeries< Real > &)
stores the historical fixings of the index
boost::shared_ptr< Observable > notifier (const std::string &name) const
observer notifying of changes in the index fixings
std::vector< std::string > histories () const
returns all names of the indexes for which fixings were stored
void clearHistory (const std::string &name)
clears the historical fixings of the index
void clearHistories ()
clears all stored fixings
Private Types
typedef std::map< std::string,
ObservableValue< TimeSeries
< Real > > > history_map
Private Member Functions
IndexManager ()
Private Attributes
history_map data_
Friends
class Singleton< IndexManager >
Detailed Description
global repository for past index fixings
Note:
index names are case insensitive
Definition at line 36 of file indexmanager.hpp.
Member Typedef Documentation
typedef std::map<std::string, ObservableValue<TimeSeries<Real> > > QuantLib::IndexManager::history_map [private]
Definition at line 57 of file indexmanager.hpp.
Constructor & Destructor Documentation
QuantLib::IndexManager::IndexManager () [inline, private]
Definition at line 39 of file indexmanager.hpp.
{}
Member Function Documentation
void QuantLib::IndexManager::clearHistories ()
clears all stored fixings
Definition at line 60 of file indexmanager.cpp.
References data_.
Referenced by QuantLib::IndexHistoryCleaner::~IndexHistoryCleaner().
{
        data_.clear();
    }
void QuantLib::IndexManager::clearHistory (const std::string & name)
clears the historical fixings of the index
Definition at line 56 of file indexmanager.cpp.
References data_.
Referenced by QuantLib::Index::clearFixings(), and QuantLib::CommodityIndex::clearQuotes().
{
        data_.erase(to_upper_copy(name));
    }
const TimeSeries< Real > & QuantLib::IndexManager::getHistory (const std::string & name) const
returns the (possibly empty) history of the index fixings
Definition at line 33 of file indexmanager.cpp.
References data_.
Referenced by QuantLib::Index::addFixings(), QuantLib::CommodityIndex::addQuote(), QuantLib::CommodityIndex::addQuotes(), QuantLib::CommodityIndex::CommodityIndex(), QuantLib::YoYInflationIndex::fixing(), QuantLib::DigitalCoupon::rate(), QuantLib::anonymous_namespace{overnightindexedcoupon.cpp}::OvernightIndexedCouponPricer::swapletRate(), and QuantLib::Index::timeSeries().
{
        return data_[to_upper_copy(name)].value();
    }
bool QuantLib::IndexManager::hasHistory (const std::string & name) const
returns whether historical fixings were stored for the index
Definition at line 28 of file indexmanager.cpp.
References data_.
{
        return data_.find(to_upper_copy(name)) != data_.end();
    }
std::vector< string > QuantLib::IndexManager::histories () const
returns all names of the indexes for which fixings were stored
Definition at line 47 of file indexmanager.cpp.
References data_.
{
        std::vector<string> temp;
        temp.reserve(data_.size());
        for (history_map::const_iterator i=data_.begin();
             i!=data_.end(); ++i)
            temp.push_back(i->first);
        return temp;
    }
boost::shared_ptr< Observable > QuantLib::IndexManager::notifier (const std::string & name) const
observer notifying of changes in the index fixings
Definition at line 43 of file indexmanager.cpp.
References data_.
{
        return data_[to_upper_copy(name)];
    }
void QuantLib::IndexManager::setHistory (const std::string & name, const TimeSeries< Real > & history)
stores the historical fixings of the index
Definition at line 37 of file indexmanager.cpp.
References data_.
Referenced by QuantLib::Index::addFixings(), QuantLib::CommodityIndex::addQuote(), QuantLib::CommodityIndex::addQuotes(), QuantLib::CommodityIndex::CommodityIndex(), and ShortRateModelTest::testSwaps().
{
        data_[to_upper_copy(name)] = history;
    }
Friends And Related Function Documentation
friend class Singleton< IndexManager > [friend]
Definition at line 37 of file indexmanager.hpp.
Member Data Documentation
history_map QuantLib::IndexManager::data_ [mutable, private]
Definition at line 58 of file indexmanager.hpp.
Referenced by clearHistories(), clearHistory(), getHistory(), hasHistory(), histories(), notifier(), and setHistory().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/indexes/indexmanager.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/indexes/indexmanager.cpp