QuantLib: QuantLib::FraRateHelper Class Reference
QuantLib::FraRateHelper Class Reference
Rate helper for bootstrapping over FRA rates.
#include <ratehelpers.hpp>
Public Member Functions
FraRateHelper (const Handle< Quote > &rate, Natural monthsToStart, Natural monthsToEnd, Natural fixingDays, const Calendar &calendar, BusinessDayConvention convention, bool endOfMonth, const DayCounter &dayCounter)
FraRateHelper (Rate rate, Natural monthsToStart, Natural monthsToEnd, Natural fixingDays, const Calendar &calendar, BusinessDayConvention convention, bool endOfMonth, const DayCounter &dayCounter)
FraRateHelper (const Handle< Quote > &rate, Natural monthsToStart, const boost::shared_ptr< IborIndex > &iborIndex)
FraRateHelper (Rate rate, Natural monthsToStart, const boost::shared_ptr< IborIndex > &iborIndex)
FraRateHelper (const Handle< Quote > &rate, Period periodToStart, Natural lengthInMonths, Natural fixingDays, const Calendar &calendar, BusinessDayConvention convention, bool endOfMonth, const DayCounter &dayCounter)
FraRateHelper (Rate rate, Period periodToStart, Natural lengthInMonths, Natural fixingDays, const Calendar &calendar, BusinessDayConvention convention, bool endOfMonth, const DayCounter &dayCounter)
FraRateHelper (const Handle< Quote > &rate, Period periodToStart, const boost::shared_ptr< IborIndex > &iborIndex)
FraRateHelper (Rate rate, Period periodToStart, const boost::shared_ptr< IborIndex > &iborIndex)
RateHelper interface
Real impliedQuote () const
void setTermStructure (YieldTermStructure *)
Visitability
void accept (AcyclicVisitor &)
Private Member Functions
void initializeDates ()
Private Attributes
Date fixingDate_
Period periodToStart_
boost::shared_ptr< IborIndex > iborIndex_
RelinkableHandle
< YieldTermStructure > termStructureHandle_
Detailed Description
Rate helper for bootstrapping over FRA rates.
Definition at line 139 of file ratehelpers.hpp.
Constructor & Destructor Documentation
QuantLib::FraRateHelper::FraRateHelper (const Handle< Quote > & rate, Natural monthsToStart, Natural monthsToEnd, Natural fixingDays, const Calendar & calendar, BusinessDayConvention convention, bool endOfMonth, const DayCounter & dayCounter)
Definition at line 275 of file ratehelpers.cpp.
References iborIndex_, initializeDates(), QuantLib::Months, QL_REQUIRE, and termStructureHandle_.
    : RelativeDateRateHelper(rate), periodToStart_(monthsToStart*Months) {
        QL_REQUIRE(monthsToEnd>monthsToStart,
                   "monthsToEnd (" << monthsToEnd <<
                   ") must be grater than monthsToStart (" << monthsToStart <<
                   ")");
        // no way to take fixing into account,
        // even if we would like to for FRA over today
        iborIndex_ = shared_ptr<IborIndex>(new
            IborIndex("no-fix", // correct family name would be needed
                      (monthsToEnd-monthsToStart)*Months,
                      fixingDays,
                      Currency(), calendar, convention,
                      endOfMonth, dayCounter, termStructureHandle_));
        initializeDates();
    }
QuantLib::FraRateHelper::FraRateHelper (Rate rate, Natural monthsToStart, Natural monthsToEnd, Natural fixingDays, const Calendar & calendar, BusinessDayConvention convention, bool endOfMonth, const DayCounter & dayCounter)
Definition at line 299 of file ratehelpers.cpp.
References iborIndex_, initializeDates(), QuantLib::Months, QL_REQUIRE, and termStructureHandle_.
    : RelativeDateRateHelper(rate),periodToStart_(monthsToStart*Months) {
        QL_REQUIRE(monthsToEnd>monthsToStart,
                   "monthsToEnd (" << monthsToEnd <<
                   ") must be grater than monthsToStart (" << monthsToStart <<
                   ")");
        // no way to take fixing into account,
        // even if we would like to for FRA over today
        iborIndex_ = shared_ptr<IborIndex>(new
            IborIndex("no-fix", // correct family name would be needed
                      (monthsToEnd-monthsToStart)*Months,
                      fixingDays,
                      Currency(), calendar, convention,
                      endOfMonth, dayCounter, termStructureHandle_));
        initializeDates();
    }
QuantLib::FraRateHelper::FraRateHelper (const Handle< Quote > & rate, Natural monthsToStart, const boost::shared_ptr< IborIndex > & iborIndex)
QuantLib::FraRateHelper::FraRateHelper (Rate rate, Natural monthsToStart, const boost::shared_ptr< IborIndex > & iborIndex)
QuantLib::FraRateHelper::FraRateHelper (const Handle< Quote > & rate, Period periodToStart, Natural lengthInMonths, Natural fixingDays, const Calendar & calendar, BusinessDayConvention convention, bool endOfMonth, const DayCounter & dayCounter)
Definition at line 349 of file ratehelpers.cpp.
References iborIndex_, initializeDates(), QuantLib::Months, and termStructureHandle_.
    : RelativeDateRateHelper(rate), periodToStart_(periodToStart) {
        // no way to take fixing into account,
        // even if we would like to for FRA over today
        iborIndex_ = shared_ptr<IborIndex>(new
            IborIndex("no-fix", // correct family name would be needed
                      lengthInMonths*Months,
                      fixingDays,
                      Currency(), calendar, convention,
                      endOfMonth, dayCounter, termStructureHandle_));
        initializeDates();
    }
QuantLib::FraRateHelper::FraRateHelper (Rate rate, Period periodToStart, Natural lengthInMonths, Natural fixingDays, const Calendar & calendar, BusinessDayConvention convention, bool endOfMonth, const DayCounter & dayCounter)
Definition at line 369 of file ratehelpers.cpp.
References iborIndex_, initializeDates(), QuantLib::Months, and termStructureHandle_.
    : RelativeDateRateHelper(rate),periodToStart_(periodToStart) {
        // no way to take fixing into account,
        // even if we would like to for FRA over today
        iborIndex_ = shared_ptr<IborIndex>(new
            IborIndex("no-fix", // correct family name would be needed
                      lengthInMonths*Months,
                      fixingDays,
                      Currency(), calendar, convention,
                      endOfMonth, dayCounter, termStructureHandle_));
        initializeDates();
    }
QuantLib::FraRateHelper::FraRateHelper (const Handle< Quote > & rate, Period periodToStart, const boost::shared_ptr< IborIndex > & iborIndex)
QuantLib::FraRateHelper::FraRateHelper (Rate rate, Period periodToStart, const boost::shared_ptr< IborIndex > & iborIndex)
Member Function Documentation
void QuantLib::FraRateHelper::accept (AcyclicVisitor & v) [virtual]
Reimplemented from QuantLib::BootstrapHelper< TS >.
Definition at line 438 of file ratehelpers.cpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Visitor< T >::visit().
{
        Visitor<FraRateHelper>* v1 =
            dynamic_cast<Visitor<FraRateHelper>*>(&v);
        if (v1 != 0)
            v1->visit(*this);
        else
            RateHelper::accept(v);
    }
Real QuantLib::FraRateHelper::impliedQuote () const [virtual]
Implements QuantLib::BootstrapHelper< TS >.
Definition at line 413 of file ratehelpers.cpp.
References fixingDate_, iborIndex_, QL_REQUIRE, and QuantLib::BootstrapHelper< TS >::termStructure_.
{
        QL_REQUIRE(termStructure_ != 0, "term structure not set");
        return iborIndex_->fixing(fixingDate_, true);
    }
void QuantLib::FraRateHelper::initializeDates () [private, virtual]
Implements QuantLib::RelativeDateBootstrapHelper< TS >.
Definition at line 426 of file ratehelpers.cpp.
References QuantLib::Days, QuantLib::BootstrapHelper< TS >::earliestDate_, QuantLib::RelativeDateBootstrapHelper< TS >::evaluationDate_, fixingDate_, iborIndex_, QuantLib::BootstrapHelper< TS >::latestDate_, and periodToStart_.
Referenced by FraRateHelper().
{
        Date settlement = iborIndex_->fixingCalendar().advance(
            evaluationDate_, iborIndex_->fixingDays()*Days);
        earliestDate_ = iborIndex_->fixingCalendar().advance(
                               settlement,
                               periodToStart_,
                               iborIndex_->businessDayConvention(),
                               iborIndex_->endOfMonth());
        latestDate_ = iborIndex_->maturityDate(earliestDate_);
        fixingDate_ = iborIndex_->fixingDate(earliestDate_);
    }
void QuantLib::FraRateHelper::setTermStructure (YieldTermStructure * t)
Definition at line 418 of file ratehelpers.cpp.
References QuantLib::RelinkableHandle< T >::linkTo(), QuantLib::anonymous_namespace{riskyassetswap.cpp}::no_deletion(), and termStructureHandle_.
{
        // no need to register---the index is not lazy
        termStructureHandle_.linkTo(
                         shared_ptr<YieldTermStructure>(t,no_deletion),
                         false);
        RelativeDateRateHelper::setTermStructure(t);
    }
Member Data Documentation
Date QuantLib::FraRateHelper::fixingDate_ [private]
Definition at line 196 of file ratehelpers.hpp.
Referenced by impliedQuote(), and initializeDates().
boost::shared_ptr<IborIndex> QuantLib::FraRateHelper::iborIndex_ [private]
Definition at line 198 of file ratehelpers.hpp.
Referenced by FraRateHelper(), impliedQuote(), and initializeDates().
Period QuantLib::FraRateHelper::periodToStart_ [private]
Definition at line 197 of file ratehelpers.hpp.
Referenced by initializeDates().
RelinkableHandle<YieldTermStructure> QuantLib::FraRateHelper::termStructureHandle_ [private]
Definition at line 199 of file ratehelpers.hpp.
Referenced by FraRateHelper(), and setTermStructure().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/yield/ratehelpers.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/yield/ratehelpers.cpp