QuantLib: TimeSeriesTest Class Reference
TimeSeriesTest Class Reference
#include <timeseries.hpp>
Static Public Member Functions
static void testConstruction ()
static void testIntervalPrice ()
static void testIterators ()
static
boost::unit_test_framework::test_suite * suite ()
Detailed Description
Definition at line 28 of file timeseries.hpp.
Member Function Documentation
test_suite * TimeSeriesTest::suite () [static]
Definition at line 192 of file timeseries.cpp.
References QUANTLIB_TEST_CASE, testConstruction(), testIntervalPrice(), and testIterators().
Referenced by init_unit_test_suite().
{
    test_suite* suite = BOOST_TEST_SUITE("time series tests");
    suite->add(QUANTLIB_TEST_CASE(&TimeSeriesTest::testConstruction));
    suite->add(QUANTLIB_TEST_CASE(&TimeSeriesTest::testIntervalPrice));
    suite->add(QUANTLIB_TEST_CASE(&TimeSeriesTest::testIterators));
    return suite;
}
void TimeSeriesTest::testConstruction () [static]
Definition at line 33 of file timeseries.cpp.
References QuantLib::TimeSeries< T, Container >::begin(), and QuantLib::March.
Referenced by suite().
{
    BOOST_MESSAGE("Testing time series construction...");
    TimeSeries<Real> ts;
    ts[Date(25, March, 2005)] = 1.2;
    ts[Date(29, March, 2005)] = 2.3;
    ts[Date(15, March, 2005)] = 0.3;
    TimeSeries<Real>::const_iterator cur = ts.begin();
    if (cur->first != Date(15, March, 2005)) {
        BOOST_ERROR("date does not match");
    }
    if (cur->second != 0.3) {
        BOOST_ERROR("value does not match");
    }
    ts[Date(15, March, 2005)] = 4.0;
    cur = ts.begin();
    if (cur->second != 4.0) {
        BOOST_ERROR("replaced value does not match" << cur->second << "\n");
    }
    ts[Date(15, March, 2005)] = 3.5;
    if (cur->second != 3.5) {
        BOOST_ERROR("set value operator not match" << cur->second << "\n");
    }
}
void TimeSeriesTest::testIntervalPrice () [static]
Definition at line 63 of file timeseries.cpp.
References QuantLib::close(), QuantLib::IntervalPrice::makeSeries(), and QuantLib::March.
Referenced by suite().
{
    BOOST_MESSAGE("Testing time series interval price...");
    std::vector<Date> date;
    std::vector<Real> open, close, high, low;
    date.push_back(Date(25, March, 2005));
    date.push_back(Date(29, March, 2005));
    open.push_back(1.3);
    open.push_back(2.3);
    close.push_back(2.3);
    close.push_back(3.4);
    high.push_back(3.4);
    high.push_back(3.5);
    low.push_back(3.4);
    low.push_back(3.2);
    TimeSeries<IntervalPrice> tsiq = IntervalPrice::makeSeries(date,
                                                               open,
                                                               close,
                                                               high,
                                                               low);
}
void TimeSeriesTest::testIterators () [static]
Definition at line 103 of file timeseries.cpp.
References QuantLib::Calendar::advance(), QuantLib::April, anonymous_namespace{marketmodel.cpp}::calendar, anonymous_namespace{marketmodel.cpp}::d, anonymous_namespace{stats.cpp}::data, anonymous_namespace{marketmodel.cpp}::dates, QuantLib::Days, QuantLib::March, and QuantLib::UnitedStates::NYSE.
Referenced by suite().
{
    BOOST_MESSAGE("Testing time series iterators...");
    std::vector<Date> dates;
    std::vector<Real> prices;
    dates.push_back(Date(25, March, 2005));
    dates.push_back(Date(29, March, 2005));
    dates.push_back(Date(15, March, 2005));
    prices.push_back(25);
    prices.push_back(23);
    prices.push_back(20);
    TimeSeries<Real> ts(dates.begin(), dates.end(), prices.begin());
    // projection iterators
    std::copy(ts.cbegin_time(), ts.cend_time(), dates.begin());
    if (dates[0] != Date(15, March, 2005)) {
        BOOST_ERROR("date does not match");
    }
    std::copy(ts.cbegin_values(), ts.cend_values(), prices.begin());
    if (prices[0] != 20) {
        BOOST_ERROR("value does not match");
    }
    dates = ts.dates();
    if (dates[0] != Date(15, March, 2005)) {
        BOOST_ERROR("date does not match");
    }
    prices = ts.values();
    if (prices[0] != 20) {
        BOOST_ERROR("value does not match");
    }
    #if BOOST_VERSION >= 103600
    // unordered container
    typedef TimeSeries<int, boost::unordered_map<Date, int> >
                                                          TimeSeriesUnordered;
    TimeSeriesUnordered ts1;
    Date d0(25, March, 2005), d1(25, April, 2005), d = d0;
    UnitedStates calendar(UnitedStates::NYSE);
    for (int i = 0; d < d1; ++i, d = calendar.advance(d, 1, Days)) {
        ts1[d] = i;
    }
    d = d0;
    for (int i = 0; d < d1; ++i, d = calendar.advance(d, 1, Days)) {
        if (ts1[d] != int(i)) {
            BOOST_ERROR("value does not match");
        }
    }
    #endif
    // reverse iterators
    std::vector<std::pair<Date,Real> > data(prices.size());
    std::copy(ts.crbegin(), ts.crend(), data.begin());
    if (data[2].second != 20) {
        BOOST_ERROR("value does not match");
    }
    if (data[2].first != Date(15, March, 2005)) {
        BOOST_ERROR("date does not match");
    }
    std::copy(ts.crbegin_time(), ts.crend_time(), dates.begin());
    if (dates[0] != Date(29, March, 2005)) {
        BOOST_ERROR("date does not match");
    }
    std::copy(ts.crbegin_values(), ts.crend_values(), prices.begin());
    if (prices[0] != 23) {
        BOOST_ERROR("value does not match");
    }
    // The following should not compile:
    // std::transform(ts1.crbegin(), ts1.crend(), prices.begin(),
    //                TimeSeriesUnordered::get_value);
    // std::copy(ts1.crbegin_values(), ts1.crend_values(), prices.begin());
    // ts1.lastDate();
    // last date
    if (ts.lastDate() != Date(29, March, 2005)) {
        BOOST_ERROR("lastDate does not match");
    }
}
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/timeseries.hpp
/home/deriversatile/QuantLib/QuantLibQt/test-suite/timeseries.cpp