QuantLib: QuantLib::FDStepConditionEngine< Scheme > Class Template Reference
QuantLib::FDStepConditionEngine< Scheme > Class Template Reference
Finite-differences pricing engine for American-style vanilla options.
#include <fdstepconditionengine.hpp>
Public Member Functions
FDStepConditionEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > &process, Size timeSteps, Size gridPoints, bool timeDependent=false)
Protected Member Functions
virtual void initializeStepCondition () const =0
virtual void calculate (PricingEngine::results *) const
Protected Attributes
boost::shared_ptr
< StandardStepCondition > stepCondition_
SampledCurve prices_
TridiagonalOperator controlOperator_
std::vector< boost::shared_ptr
< bc_type > > controlBCs_
SampledCurve controlPrices_
Detailed Description
template<template< class > class Scheme = CrankNicolson>
class QuantLib::FDStepConditionEngine< Scheme >
Finite-differences pricing engine for American-style vanilla options.
Definition at line 39 of file fdstepconditionengine.hpp.
Constructor & Destructor Documentation
template<template< class > class Scheme = CrankNicolson> QuantLib::FDStepConditionEngine< Scheme >::FDStepConditionEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > & process, Size timeSteps, Size gridPoints, bool timeDependent = false) [inline]
Definition at line 41 of file fdstepconditionengine.hpp.
        : FDVanillaEngine(process, timeSteps, gridPoints, timeDependent),
          controlBCs_(2), controlPrices_(gridPoints) {}
Member Function Documentation
template<template< class > class Scheme> void QuantLib::FDStepConditionEngine< Scheme >::calculate (PricingEngine::results * r) const [protected, virtual]
Definition at line 61 of file fdstepconditionengine.hpp.
References QuantLib::Instrument::results::additionalResults, QuantLib::BlackCalculator::delta(), QuantLib::Greeks::delta, QuantLib::BlackCalculator::gamma(), QuantLib::Greeks::gamma, QL_REQUIRE, QuantLib::BlackCalculator::value(), and QuantLib::Instrument::results::value.
{
        OneAssetOption::results * results =
            dynamic_cast<OneAssetOption::results *>(r);
        setGridLimits();
        initializeInitialCondition();
        initializeOperator();
        initializeBoundaryConditions();
        initializeStepCondition();
        typedef FiniteDifferenceModel<ParallelEvolver<
                    Scheme<TridiagonalOperator> > > model_type;
        typename model_type::operator_type operatorSet;
        typename model_type::array_type arraySet;
        typename model_type::bc_set bcSet;
        typename model_type::condition_type conditionSet;
        prices_ = intrinsicValues_;
        controlPrices_ = intrinsicValues_;
        controlOperator_ = finiteDifferenceOperator_;
        controlBCs_[0] = BCs_[0];
        controlBCs_[1] = BCs_[1];
        operatorSet.push_back(finiteDifferenceOperator_);
        operatorSet.push_back(controlOperator_);
        arraySet.push_back(prices_.values());
        arraySet.push_back(controlPrices_.values());
        bcSet.push_back(BCs_);
        bcSet.push_back(controlBCs_);
        conditionSet.push_back(stepCondition_);
        conditionSet.push_back(boost::shared_ptr<StandardStepCondition>(
                                                   new NullCondition<Array>));
        model_type model(operatorSet, bcSet);
        model.rollback(arraySet, getResidualTime(),
                       0.0, timeSteps_, conditionSet);
        prices_.values() = arraySet[0];
        controlPrices_.values() = arraySet[1];
        boost::shared_ptr<StrikedTypePayoff> striked_payoff =
            boost::dynamic_pointer_cast<StrikedTypePayoff>(payoff_);
        QL_REQUIRE(striked_payoff, "non-striked payoff given");
        Real variance =
            process_->blackVolatility()->blackVariance(
                                     exerciseDate_, striked_payoff->strike());
        DiscountFactor dividendDiscount =
            process_->dividendYield()->discount(exerciseDate_);
        DiscountFactor riskFreeDiscount =
            process_->riskFreeRate()->discount(exerciseDate_);
        Real spot = process_->stateVariable()->value();
        Real forwardPrice = spot * dividendDiscount / riskFreeDiscount;
        BlackCalculator black(striked_payoff, forwardPrice,
                              std::sqrt(variance), riskFreeDiscount);
        results->value = prices_.valueAtCenter()
            - controlPrices_.valueAtCenter()
            + black.value();
        results->delta = prices_.firstDerivativeAtCenter()
            - controlPrices_.firstDerivativeAtCenter()
            + black.delta(spot);
        results->gamma = prices_.secondDerivativeAtCenter()
            - controlPrices_.secondDerivativeAtCenter()
            + black.gamma(spot);
        results->additionalResults["priceCurve"] = prices_;
    }
template<template< class > class Scheme = CrankNicolson> virtual void QuantLib::FDStepConditionEngine< Scheme >::initializeStepCondition () const [protected, pure virtual]
Implemented in QuantLib::FDShoutCondition< FDStepConditionEngine< Scheme > >, and QuantLib::FDAmericanCondition< FDStepConditionEngine< Scheme > >.
Member Data Documentation
template<template< class > class Scheme = CrankNicolson> std::vector<boost::shared_ptr<bc_type> > QuantLib::FDStepConditionEngine< Scheme >::controlBCs_ [mutable, protected]
Definition at line 51 of file fdstepconditionengine.hpp.
template<template< class > class Scheme = CrankNicolson> TridiagonalOperator QuantLib::FDStepConditionEngine< Scheme >::controlOperator_ [mutable, protected]
Definition at line 50 of file fdstepconditionengine.hpp.
template<template< class > class Scheme = CrankNicolson> SampledCurve QuantLib::FDStepConditionEngine< Scheme >::controlPrices_ [mutable, protected]
Definition at line 52 of file fdstepconditionengine.hpp.
template<template< class > class Scheme = CrankNicolson> SampledCurve QuantLib::FDStepConditionEngine< Scheme >::prices_ [mutable, protected]
Definition at line 49 of file fdstepconditionengine.hpp.
template<template< class > class Scheme = CrankNicolson> boost::shared_ptr<StandardStepCondition> QuantLib::FDStepConditionEngine< Scheme >::stepCondition_ [mutable, protected]
Definition at line 48 of file fdstepconditionengine.hpp.
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/vanilla/fdstepconditionengine.hpp