QuantLib: QuantLib::LineSearchBasedMethod Class Reference
QuantLib::LineSearchBasedMethod Class Reference
#include <linesearchbasedmethod.hpp>
Public Member Functions
LineSearchBasedMethod (const boost::shared_ptr< LineSearch > &lSearch=boost::shared_ptr< LineSearch >())
virtual ~LineSearchBasedMethod ()
virtual EndCriteria::Type minimize (Problem &P, const EndCriteria &endCriteria)
minimize the optimization problem P
Protected Member Functions
virtual Disposable< Array > getUpdatedDirection (const Problem &P, Real gold2, const Array &gradient)=0
computes the new search direction
Protected Attributes
boost::shared_ptr< LineSearch > lineSearch_
line search
Detailed Description
Definition at line 36 of file linesearchbasedmethod.hpp.
Constructor & Destructor Documentation
QuantLib::LineSearchBasedMethod::LineSearchBasedMethod (const boost::shared_ptr< LineSearch > & lSearch = boost::shared_ptr<LineSearch>())
Definition at line 28 of file linesearchbasedmethod.cpp.
References lineSearch_.
    : lineSearch_(lineSearch) {
        if (!lineSearch_)
           lineSearch_ = boost::shared_ptr<LineSearch>(new ArmijoLineSearch);
    }
virtual QuantLib::LineSearchBasedMethod::~LineSearchBasedMethod () [inline, virtual]
Definition at line 40 of file linesearchbasedmethod.hpp.
{}
Member Function Documentation
virtual Disposable<Array> QuantLib::LineSearchBasedMethod::getUpdatedDirection (const Problem & P, Real gold2, const Array & gradient) [protected, pure virtual]
computes the new search direction
Implemented in QuantLib::ConjugateGradient, QuantLib::BFGS, and QuantLib::SteepestDescent.
Referenced by minimize().
EndCriteria::Type QuantLib::LineSearchBasedMethod::minimize (Problem & P, const EndCriteria & endCriteria) [virtual]
minimize the optimization problem P
Implements QuantLib::OptimizationMethod.
Definition at line 36 of file linesearchbasedmethod.cpp.
References QuantLib::Problem::currentValue(), anonymous_namespace{marketmodel.cpp}::d, QuantLib::DotProduct(), QuantLib::EndCriteria::functionEpsilon(), getUpdatedDirection(), lineSearch_, QuantLib::EndCriteria::maxStationaryStateIterations(), anonymous_namespace{optimizers.cpp}::maxStationaryStateIterations_, QuantLib::EndCriteria::None, QL_EPSILON, QuantLib::Problem::reset(), QuantLib::Problem::setCurrentValue(), QuantLib::Problem::setFunctionValue(), QuantLib::Problem::setGradientNormValue(), QuantLib::Array::size(), anonymous_namespace{quantlibbenchmark.cpp}::t, and QuantLib::Problem::valueAndGradient().
Referenced by QuantLib::anonymous_namespace{pseudosqrt.cpp}::hypersphereOptimize().
{
        // Initializations
        Real ftol = endCriteria.functionEpsilon();
        Size maxStationaryStateIterations_
            = endCriteria.maxStationaryStateIterations();
        EndCriteria::Type ecType = EndCriteria::None;   // reset end criteria
        P.reset();                                      // reset problem
        Array x_ = P.currentValue();              // store the starting point
        Size iterationNumber_ = 0;
        // dimension line search
        lineSearch_->searchDirection() = Array(x_.size());
        bool done = false;
        // function and squared norm of gradient values;
        Real fnew, fold, gold2;
        Real fdiff;
        // classical initial value for line-search step
        Real t = 1.0;
        // Set gradient g at the size of the optimization problem
        // search direction
        Size sz = lineSearch_->searchDirection().size();
        Array prevGradient(sz), d(sz), sddiff(sz), direction(sz);
        // Initialize cost function, gradient prevGradient and search direction
        P.setFunctionValue(P.valueAndGradient(prevGradient, x_));
        P.setGradientNormValue(DotProduct(prevGradient, prevGradient));
        lineSearch_->searchDirection() = -prevGradient;
        bool first_time = true;
        // Loop over iterations
        do {
            // Linesearch
            if (!first_time)
                prevGradient = lineSearch_->lastGradient();
            t = (*lineSearch_)(P, ecType, endCriteria, t);
            // don't throw: it can fail just because maxIterations exceeded
            //QL_REQUIRE(lineSearch_->succeed(), "line-search failed!");
            if (lineSearch_->succeed())
            {
                // Updates
                // New point
                x_ = lineSearch_->lastX();
                // New function value
                fold = P.functionValue();
                P.setFunctionValue(lineSearch_->lastFunctionValue());
                // New gradient and search direction vectors
                // orthogonalization coef
                gold2 = P.gradientNormValue();
                P.setGradientNormValue(lineSearch_->lastGradientNorm2());
                // conjugate gradient search direction
                direction = getUpdatedDirection(P, gold2, prevGradient);
                sddiff = direction - lineSearch_->searchDirection();
                lineSearch_->searchDirection() = direction;
                // Now compute accuracy and check end criteria
                // Numerical Recipes exit strategy on fx (see NR in C++, p.423)
                fnew = P.functionValue();
                fdiff = 2.0*std::fabs(fnew-fold) /
                        (std::fabs(fnew) + std::fabs(fold) + QL_EPSILON);
                if (fdiff < ftol ||
                    endCriteria.checkMaxIterations(iterationNumber_, ecType)) {
                    endCriteria.checkStationaryFunctionValue(0.0, 0.0,
                        maxStationaryStateIterations_, ecType);
                    endCriteria.checkMaxIterations(iterationNumber_, ecType);
                    return ecType;
                }
                P.setCurrentValue(x_);      // update problem current value
                ++iterationNumber_;         // Increase iteration number
                first_time = false;
            } else {
                done = true;
            }
        } while (!done);
        P.setCurrentValue(x_);
        return ecType;
    }
Member Data Documentation
boost::shared_ptr<LineSearch> QuantLib::LineSearchBasedMethod::lineSearch_ [protected]
line search
Definition at line 51 of file linesearchbasedmethod.hpp.
Referenced by QuantLib::SteepestDescent::getUpdatedDirection(), QuantLib::BFGS::getUpdatedDirection(), QuantLib::ConjugateGradient::getUpdatedDirection(), LineSearchBasedMethod(), and minimize().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/optimization/linesearchbasedmethod.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/math/optimization/linesearchbasedmethod.cpp