QuantLib: QuantLib::BiCGstab Class Reference
QuantLib::BiCGstab Class Reference
#include <bicgstab.hpp>
Public Types
typedef boost::function1
< Disposable< Array >, const
Array & > MatrixMult
Public Member Functions
BiCGstab (const MatrixMult &A, Size maxIter, Real relTol, const MatrixMult &preConditioner=MatrixMult())
BiCGStabResult solve (const Array &b, const Array &x0=Array()) const
Protected Member Functions
Real norm2 (const Array &a) const
Protected Attributes
const MatrixMult A_
const MatrixMult M_
const Size maxIter_
const Real relTol_
Detailed Description
Definition at line 39 of file bicgstab.hpp.
Member Typedef Documentation
typedef boost::function1<Disposable<Array> , const Array& > QuantLib::BiCGstab::MatrixMult
Definition at line 41 of file bicgstab.hpp.
Constructor & Destructor Documentation
QuantLib::BiCGstab::BiCGstab (const MatrixMult & A, Size maxIter, Real relTol, const MatrixMult & preConditioner = MatrixMult())
Definition at line 30 of file bicgstab.cpp.
    : A_(A), M_(preConditioner),
      maxIter_(maxIter), relTol_(relTol) {
    }
Member Function Documentation
Real QuantLib::BiCGstab::norm2 (const Array & a) const [protected]
Definition at line 95 of file bicgstab.cpp.
References QuantLib::DotProduct().
Referenced by solve().
{
        return std::sqrt(DotProduct(a, a));
    }
BiCGStabResult QuantLib::BiCGstab::solve (const Array & b, const Array & x0 = Array()) const
Definition at line 37 of file bicgstab.cpp.
References A_, anonymous_namespace{marketmodel.cpp}::beta, QuantLib::DotProduct(), QuantLib::Array::empty(), M_, maxIter_, norm2(), QL_REQUIRE, relTol_, QuantLib::Array::size(), anonymous_namespace{quantlibbenchmark.cpp}::t, and anonymous_namespace{perturbativebarrieroptionengine.cpp}::v().
Referenced by QuantLib::ImplicitEulerScheme::step(), and FdmLinearOpTest::testBiCGstab().
{
        Real bnorm2 = norm2(b);
        if (bnorm2 == 0.0) {
            BiCGStabResult result = { 0, 0.0, b};
            return result;
        }
        Array x = ((!x0.empty()) ? x0 : Array(b.size(), 0.0));
        Array r = b - A_(x);
        Array rTld = r;
        Array p, pTld, v, s, sTld, t;
        Real omega = 1.0;
        Real rho, rhoTld=1.0;
        Real alpha=0.0, beta;
        Real error=Null<Real>();
        Size i;
        for (i=0; i < maxIter_ && error >= relTol_; ++i) {
           rho = DotProduct(rTld, r);
           if  (rho == 0.0 || omega == 0.0)
               break;
           if (i) {
              beta = (rho/rhoTld)*(alpha/omega);
              p = r + beta*(p - omega*v);
           }
           else {
              p = r;
           }
           pTld = ((M_)? M_(p) : p);
           v     = A_(pTld);
           alpha = rho/DotProduct(rTld, v);
           s     = r-alpha*v;
           if (norm2(s) < relTol_*bnorm2) {
              x += alpha*pTld;
              error = norm2(s)/bnorm2;
              break;
           }
           sTld = ((M_) ? M_(s) : s);
           t = A_(sTld);
           omega = DotProduct(t,s)/DotProduct(t,t);
           x += alpha*pTld + omega*sTld;
           r = s - omega*t;
           error = norm2(r)/bnorm2;
           rhoTld = rho;
        }
        QL_REQUIRE(i < maxIter_, "max number of iterations exceeded");
        QL_REQUIRE(error < relTol_, "could not converge");
        BiCGStabResult result = { i, error, x};
        return result;
    }
Member Data Documentation
const MatrixMult QuantLib::BiCGstab::A_ [protected]
Definition at line 51 of file bicgstab.hpp.
Referenced by solve().
const MatrixMult QuantLib::BiCGstab::M_ [protected]
Definition at line 51 of file bicgstab.hpp.
Referenced by solve().
const Size QuantLib::BiCGstab::maxIter_ [protected]
Definition at line 52 of file bicgstab.hpp.
Referenced by solve().
const Real QuantLib::BiCGstab::relTol_ [protected]
Definition at line 53 of file bicgstab.hpp.
Referenced by solve().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/matrixutilities/bicgstab.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/math/matrixutilities/bicgstab.cpp