QuantLib: QuantLib::OneFactorGaussianStudentCopula Class Reference
QuantLib::OneFactorGaussianStudentCopula Class Reference
One-factor Gaussian-Student t-Copula.
#include <onefactorstudentcopula.hpp>
Public Member Functions
OneFactorGaussianStudentCopula (const Handle< Quote > &correlation, int nz, Real maximum=10, Size integrationSteps=200)
Real density (Real m) const
Density function of M.
Real cumulativeZ (Real z) const
Cumulative distribution of Z.
Private Member Functions
void performCalculations () const
Observer interface.
Real cumulativeYintegral (Real y) const
Private Attributes
NormalDistribution density_
CumulativeStudentDistribution cumulative_
int nz_
Real scaleZ_
Detailed Description
One-factor Gaussian-Student t-Copula.
The copula model
\[ Y_i = a_i\,M+\sqrt{1-a_i^2}\:Z_i \]
is specified here by setting the probability density functions for \(Z_i \) (\(D_Z \)) to a Student t-distributions with \(N_z \) degrees of freedom, and for \(M \) (\(D_M \)) to a Gaussian.
The variance of the Student t-distribution with \(\nu \) degrees of freedom is \(\nu / (\nu - 2) \). Since the copula approach requires zero mean and unit variance distributions, \(Z \) is scaled by \(\sqrt{(N_z - 2) / N_z}.\)
Todo:
Improve performance/accuracy of the calculation of inverse cumulative Y. Tabulate and store it for selected correlations?
Definition at line 108 of file onefactorstudentcopula.hpp.
Constructor & Destructor Documentation
QuantLib::OneFactorGaussianStudentCopula::OneFactorGaussianStudentCopula (const Handle< Quote > & correlation, int nz, Real maximum = 10, Size integrationSteps = 200)
Definition at line 109 of file onefactorstudentcopula.cpp.
References QuantLib::LazyObject::calculate(), nz_, QL_REQUIRE, and scaleZ_.
    : OneFactorCopula (correlation, maximum, integrationSteps),
      cumulative_(nz), nz_(nz) {
    //-------------------------------------------------------------------------
        QL_REQUIRE (nz > 2, "degrees of freedom must be > 2");
        scaleZ_ = std::sqrt (Real (nz_ - 2) / nz_);
        calculate ();
    }
Member Function Documentation
Real QuantLib::OneFactorGaussianStudentCopula::cumulativeYintegral (Real y) const [private]
Definition at line 145 of file onefactorstudentcopula.cpp.
References anonymous_namespace{marketmodel.cpp}::c, QuantLib::OneFactorCopula::correlation_, QuantLib::OneFactorCopula::dm(), QuantLib::OneFactorCopula::m(), nz_, scaleZ_, and QuantLib::OneFactorCopula::steps().
Referenced by performCalculations().
{
    //-------------------------------------------------------------------------
        Real c = correlation_->value();
        if (c == 0)
            return CumulativeStudentDistribution(nz_)(y / scaleZ_);
        if (c == 1)
            return CumulativeNormalDistribution()(y);
        StudentDistribution dz (nz_);
        NormalDistribution dm;
        // FIXME:
        // Find a sensitive way of setting these parameters,
        // e.g. depending on nm and nz, and the desired table range
        Real minimum = -10;
        Real maximum = +10;
        int steps = 400;
        Real delta = (maximum - minimum) / steps;
        Real cumulated = 0;
        if (c < 0.5) {
            // outer integral -> 1 for c -> 0
            // inner integral -> cumulativeStudent(nz)(y) for c-> 0
            for (Real m = minimum + delta/2; m < maximum; m += delta)
                for (Real z = minimum + delta/2;
                     z < (y - std::sqrt(c) * m) / std::sqrt (1. - c);
                     z += delta)
                    cumulated += dm (m) * dz (z / scaleZ_) / scaleZ_;
        }
        else {
            // outer integral -> 1 for c -> 1
            // inner integral -> cumulativeNormal(y) for c-> 1
            for (Real z = minimum + delta/2; z < maximum; z += delta)
                for (Real m = minimum + delta/2;
                     m < (y - std::sqrt(1.0 - c) * z) / std::sqrt(c);
                     m += delta)
                    cumulated += dm (m) * dz (z / scaleZ_) / scaleZ_;
        }
        return cumulated * delta * delta;
    }
Real QuantLib::OneFactorGaussianStudentCopula::cumulativeZ (Real z) const [inline, virtual]
Cumulative distribution of Z.
Derived classes must override this method and ensure zero mean and unit variance.
Implements QuantLib::OneFactorCopula.
Definition at line 138 of file onefactorstudentcopula.hpp.
References cumulative_, and scaleZ_.
{
        return cumulative_(z / scaleZ_);
    }
Real QuantLib::OneFactorGaussianStudentCopula::density (Real m) const [inline, virtual]
Density function of M.
Derived classes must override this method and ensure zero mean and unit variance.
Implements QuantLib::OneFactorCopula.
Definition at line 134 of file onefactorstudentcopula.hpp.
References density_.
{
        return density_(m);
    }
void QuantLib::OneFactorGaussianStudentCopula::performCalculations () const [private, virtual]
Observer interface.
Implements QuantLib::LazyObject.
Definition at line 125 of file onefactorstudentcopula.cpp.
References anonymous_namespace{marketmodel.cpp}::c, QuantLib::OneFactorCopula::cumulativeY_, cumulativeYintegral(), QuantLib::OneFactorCopula::steps(), and QuantLib::OneFactorCopula::y_.
{
    //-------------------------------------------------------------------------
        y_.clear();
        cumulativeY_.clear();
        // FIXME:
        // compute F(ymin) and F(ymax) for the fattest case nm = nz = 2
        // set a desired confidence and work out ymin, ymax
        Real ymin = -10;
        Real ymax = +10;
        Size steps = 200;
        for (Size i = 0; i <= steps; i++) {
            Real y = ymin + (ymax - ymin) * i / steps;
            Real c = cumulativeYintegral (y);
            y_.push_back (y);
            cumulativeY_.push_back (c);
        }
    }
Member Data Documentation
CumulativeStudentDistribution QuantLib::OneFactorGaussianStudentCopula::cumulative_ [private]
Definition at line 123 of file onefactorstudentcopula.hpp.
Referenced by cumulativeZ().
NormalDistribution QuantLib::OneFactorGaussianStudentCopula::density_ [private]
Definition at line 122 of file onefactorstudentcopula.hpp.
Referenced by density().
int QuantLib::OneFactorGaussianStudentCopula::nz_ [private]
Definition at line 124 of file onefactorstudentcopula.hpp.
Referenced by cumulativeYintegral(), and OneFactorGaussianStudentCopula().
Real QuantLib::OneFactorGaussianStudentCopula::scaleZ_ [private]
Definition at line 126 of file onefactorstudentcopula.hpp.
Referenced by cumulativeYintegral(), cumulativeZ(), and OneFactorGaussianStudentCopula().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/onefactorstudentcopula.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/onefactorstudentcopula.cpp