QuantLib: QuantLib::anonymous_namespace{parametricexercise.cpp}::ValueEstimate Class Reference
QuantLib::anonymous_namespace{parametricexercise.cpp}::ValueEstimate Class Reference
Public Member Functions
ValueEstimate (const std::vector< NodeData > &simulationData, const ParametricExercise &exercise, Size exerciseIndex)
Real value (const Array &parameters) const
method to overload to compute the cost function value in x
Disposable< Array > values (const Array &) const
method to overload to compute the cost function values in x
Private Attributes
const std::vector< NodeData > & simulationData_
const ParametricExercise & exercise_
Size exerciseIndex_
std::vector< Real > parameters_
Detailed Description
Definition at line 28 of file parametricexercise.cpp.
Constructor & Destructor Documentation
QuantLib::anonymous_namespace{parametricexercise.cpp}::ValueEstimate::ValueEstimate (const std::vector< NodeData > & simulationData, const ParametricExercise & exercise, Size exerciseIndex)
Definition at line 44 of file parametricexercise.cpp.
References QL_FAIL, and simulationData_.
        : simulationData_(simulationData), exercise_(exercise),
          exerciseIndex_(exerciseIndex),
          parameters_(exercise.numberOfParameters()[exerciseIndex]) {
            for (Size i=0; i<simulationData_.size(); ++i) {
                if (simulationData_[i].isValid)
                    return;
            }
            QL_FAIL("no valid paths");
        }
Member Function Documentation
Real QuantLib::anonymous_namespace{parametricexercise.cpp}::ValueEstimate::value (const Array & x) const [virtual]
method to overload to compute the cost function value in x
Implements QuantLib::CostFunction.
Definition at line 58 of file parametricexercise.cpp.
References QuantLib::Array::begin(), QuantLib::Array::end(), QuantLib::ParametricExercise::exercise(), exercise_, exerciseIndex_, parameters_, and simulationData_.
{
            std::copy(parameters.begin(), parameters.end(),
                      parameters_.begin());
            Real sum = 0.0;
            Size n = 0;
            for (Size i=0; i<simulationData_.size(); ++i) {
                if (simulationData_[i].isValid) {
                    ++n;
                    if (exercise_.exercise(exerciseIndex_,
                                           parameters_,
                                           simulationData_[i].values))
                        sum += simulationData_[i].exerciseValue;
                    else
                        sum += simulationData_[i].cumulatedCashFlows;
                }
            }
            return -sum/n;
        }
Disposable<Array> QuantLib::anonymous_namespace{parametricexercise.cpp}::ValueEstimate::values (const Array & x) const [inline, virtual]
method to overload to compute the cost function values in x
Implements QuantLib::CostFunction.
Definition at line 34 of file parametricexercise.cpp.
References QL_FAIL.
{
                QL_FAIL("values method not implemented");
            }
Member Data Documentation
const ParametricExercise& QuantLib::anonymous_namespace{parametricexercise.cpp}::ValueEstimate::exercise_ [private]
Definition at line 39 of file parametricexercise.cpp.
Referenced by value().
Size QuantLib::anonymous_namespace{parametricexercise.cpp}::ValueEstimate::exerciseIndex_ [private]
Definition at line 40 of file parametricexercise.cpp.
Referenced by value().
std::vector<Real> QuantLib::anonymous_namespace{parametricexercise.cpp}::ValueEstimate::parameters_ [mutable, private]
Definition at line 41 of file parametricexercise.cpp.
Referenced by value().
const std::vector<NodeData>& QuantLib::anonymous_namespace{parametricexercise.cpp}::ValueEstimate::simulationData_ [private]
Definition at line 38 of file parametricexercise.cpp.
Referenced by value(), and ValueEstimate().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/montecarlo/parametricexercise.cpp