QuantLib: QuantLib::MCLongstaffSchwartzPathEngine< GenericEngine, MC, RNG, S > Class Template Reference
QuantLib::MCLongstaffSchwartzPathEngine< GenericEngine, MC, RNG, S > Class Template Reference
Longstaff-Schwarz Monte Carlo engine for early exercise options.
#include <mclongstaffschwartzpathengine.hpp>
Public Types
typedef MC< RNG >::path_type path_type
typedef McSimulation< MC, RNG,
S >::stats_type stats_type
typedef McSimulation< MC, RNG,
S >::path_pricer_type path_pricer_type
typedef McSimulation< MC, RNG,
S >::path_generator_type path_generator_type
Public Member Functions
MCLongstaffSchwartzPathEngine (const boost::shared_ptr< StochasticProcess > &process, Size timeSteps, Size timeStepsPerYear, bool brownianBridge, bool antitheticVariate, bool controlVariate, Size requiredSamples, Real requiredTolerance, Size maxSamples, BigNatural seed, Size nCalibrationSamples=Null< Size >())
void calculate () const
Protected Member Functions
virtual boost::shared_ptr
< LongstaffSchwartzMultiPathPricer > lsmPathPricer () const =0
TimeGrid timeGrid () const
boost::shared_ptr
< path_pricer_type > pathPricer () const
boost::shared_ptr
< path_generator_type > pathGenerator () const
Protected Attributes
boost::shared_ptr
< StochasticProcess > process_
const Size timeSteps_
const Size timeStepsPerYear_
const bool brownianBridge_
const Size requiredSamples_
const Real requiredTolerance_
const Size maxSamples_
const Size seed_
const Size nCalibrationSamples_
boost::shared_ptr
< LongstaffSchwartzMultiPathPricer > pathPricer_
Detailed Description
template<class GenericEngine, template< class > class MC, class RNG, class S = Statistics>
class QuantLib::MCLongstaffSchwartzPathEngine< GenericEngine, MC, RNG, S >
Longstaff-Schwarz Monte Carlo engine for early exercise options.
References:
Francis Longstaff, Eduardo Schwartz, 2001. Valuing American Options by Simulation: A Simple Least-Squares Approach, The Review of Financial Studies, Volume 14, No. 1, 113-147
Test:
the correctness of the returned value is tested by reproducing results available in web/literature
Definition at line 40 of file mclongstaffschwartzpathengine.hpp.
Member Typedef Documentation
template<class GenericEngine, template< class > class MC, class RNG, class S = Statistics> typedef McSimulation<MC,RNG,S>::path_generator_type QuantLib::MCLongstaffSchwartzPathEngine< GenericEngine, MC, RNG, S >::path_generator_type
Reimplemented from QuantLib::McSimulation< MC, RNG, S >.
Definition at line 49 of file mclongstaffschwartzpathengine.hpp.
template<class GenericEngine, template< class > class MC, class RNG, class S = Statistics> typedef McSimulation<MC,RNG,S>::path_pricer_type QuantLib::MCLongstaffSchwartzPathEngine< GenericEngine, MC, RNG, S >::path_pricer_type
Reimplemented from QuantLib::McSimulation< MC, RNG, S >.
Definition at line 47 of file mclongstaffschwartzpathengine.hpp.
template<class GenericEngine, template< class > class MC, class RNG, class S = Statistics> typedef MC<RNG>::path_type QuantLib::MCLongstaffSchwartzPathEngine< GenericEngine, MC, RNG, S >::path_type
Definition at line 43 of file mclongstaffschwartzpathengine.hpp.
template<class GenericEngine, template< class > class MC, class RNG, class S = Statistics> typedef McSimulation<MC,RNG,S>::stats_type QuantLib::MCLongstaffSchwartzPathEngine< GenericEngine, MC, RNG, S >::stats_type
Reimplemented from QuantLib::McSimulation< MC, RNG, S >.
Definition at line 45 of file mclongstaffschwartzpathengine.hpp.
Constructor & Destructor Documentation
template<class GenericEngine , template< class > class MC, class RNG , class S > QuantLib::MCLongstaffSchwartzPathEngine< GenericEngine, MC, RNG, S >::MCLongstaffSchwartzPathEngine (const boost::shared_ptr< StochasticProcess > & process, Size timeSteps, Size timeStepsPerYear, bool brownianBridge, bool antitheticVariate, bool controlVariate, Size requiredSamples, Real requiredTolerance, Size maxSamples, BigNatural seed, Size nCalibrationSamples = Null<Size>()) [inline]
Definition at line 90 of file mclongstaffschwartzpathengine.hpp.
References QuantLib::MCLongstaffSchwartzPathEngine< GenericEngine, MC, RNG, S >::process_, QL_REQUIRE, and QuantLib::Observer::registerWith().
    : McSimulation<MC,RNG,S> (antitheticVariate, controlVariate),
      process_            (process),
      timeSteps_          (timeSteps),
      timeStepsPerYear_   (timeStepsPerYear),
      brownianBridge_     (brownianBridge),
      requiredSamples_    (requiredSamples),
      requiredTolerance_  (requiredTolerance),
      maxSamples_         (maxSamples),
      seed_               (seed),
      nCalibrationSamples_( (nCalibrationSamples == Null<Size>())
                            ? 2048 : nCalibrationSamples) {
        QL_REQUIRE(timeSteps != Null<Size>() ||
                   timeStepsPerYear != Null<Size>(),
                   "no time steps provided");
        QL_REQUIRE(timeSteps == Null<Size>() ||
                   timeStepsPerYear == Null<Size>(),
                   "both time steps and time steps per year were provided");
        QL_REQUIRE(timeSteps != 0,
                   "timeSteps must be positive, " << timeSteps <<
                   " not allowed");
        QL_REQUIRE(timeStepsPerYear != 0,
                   "timeStepsPerYear must be positive, "
                    << timeStepsPerYear << " not allowed");
        this->registerWith(process_);
    }
Member Function Documentation
template<class GenericEngine , template< class > class MC, class RNG , class S > void QuantLib::MCLongstaffSchwartzPathEngine< GenericEngine, MC, RNG, S >::calculate () const [inline, virtual]
Implements QuantLib::PricingEngine.
Definition at line 143 of file mclongstaffschwartzpathengine.hpp.
References QuantLib::McSimulation< MC, RNG, S >::calculate().
          {
        pathPricer_ = this->lsmPathPricer();
        this->mcModel_ = boost::shared_ptr<MonteCarloModel<MC,RNG,S> >(
                          new MonteCarloModel<MC,RNG,S>
                              (pathGenerator(), pathPricer_,
                               stats_type(), this->antitheticVariate_));
        this->mcModel_->addSamples(nCalibrationSamples_);
        this->pathPricer_->calibrate();
        McSimulation<MC,RNG,S>::calculate(requiredTolerance_,
                                          requiredSamples_,
                                          maxSamples_);
        this->results_.value = this->mcModel_->sampleAccumulator().mean();
        if (RNG::allowsErrorEstimate) {
            this->results_.errorEstimate =
                this->mcModel_->sampleAccumulator().errorEstimate();
        }
    }
template<class GenericEngine, template< class > class MC, class RNG, class S = Statistics> virtual boost::shared_ptr<LongstaffSchwartzMultiPathPricer> QuantLib::MCLongstaffSchwartzPathEngine< GenericEngine, MC, RNG, S >::lsmPathPricer () const [protected, pure virtual]
Implemented in QuantLib::MCAmericanPathEngine< RNG >.
template<class GenericEngine , template< class > class MC, class RNG , class S > boost::shared_ptr< typename MCLongstaffSchwartzPathEngine< GenericEngine, MC, RNG, S >::path_generator_type > QuantLib::MCLongstaffSchwartzPathEngine< GenericEngine, MC, RNG, S >::pathGenerator () const [inline, protected, virtual]
Implements QuantLib::McSimulation< MC, RNG, S >.
Definition at line 188 of file mclongstaffschwartzpathengine.hpp.
References anonymous_namespace{marketmodel.cpp}::seed_, and QuantLib::TimeGrid::size().
          {
        Size dimensions = process_->factors();
        TimeGrid grid = this->timeGrid();
        typename RNG::rsg_type generator =
            RNG::make_sequence_generator(dimensions*(grid.size()-1),seed_);
        return boost::shared_ptr<path_generator_type>(
                   new path_generator_type(process_,
                                           grid, generator, brownianBridge_));
    }
template<class GenericEngine , template< class > class MC, class RNG , class S > boost::shared_ptr< typename MCLongstaffSchwartzPathEngine< GenericEngine, MC, RNG, S >::path_pricer_type > QuantLib::MCLongstaffSchwartzPathEngine< GenericEngine, MC, RNG, S >::pathPricer () const [inline, protected, virtual]
Implements QuantLib::McSimulation< MC, RNG, S >.
Definition at line 133 of file mclongstaffschwartzpathengine.hpp.
References QL_REQUIRE.
              {
        QL_REQUIRE(pathPricer_, "path pricer unknown");
        return pathPricer_;
    }
template<class GenericEngine , template< class > class MC, class RNG , class S > TimeGrid QuantLib::MCLongstaffSchwartzPathEngine< GenericEngine, MC, RNG, S >::timeGrid () const [inline, protected, virtual]
Implements QuantLib::McSimulation< MC, RNG, S >.
Definition at line 167 of file mclongstaffschwartzpathengine.hpp.
              {
        const std::vector<Date> & fixings = this->arguments_.fixingDates;
        const Size numberOfFixings = fixings.size();
        std::vector<Time> fixingTimes(numberOfFixings);
        for (Size i = 0; i < numberOfFixings; ++i) {
            fixingTimes[i] =
                this->process_->time(fixings[i]);
        }
        const Size numberOfTimeSteps = timeSteps_ != Null<Size>() ? timeSteps_ : timeStepsPerYear_ * fixingTimes.back();
        return TimeGrid(fixingTimes.begin(), fixingTimes.end(), numberOfTimeSteps);
     }
Member Data Documentation
template<class GenericEngine, template< class > class MC, class RNG, class S = Statistics> const bool QuantLib::MCLongstaffSchwartzPathEngine< GenericEngine, MC, RNG, S >::brownianBridge_ [protected]
Definition at line 77 of file mclongstaffschwartzpathengine.hpp.
template<class GenericEngine, template< class > class MC, class RNG, class S = Statistics> const Size QuantLib::MCLongstaffSchwartzPathEngine< GenericEngine, MC, RNG, S >::maxSamples_ [protected]
Definition at line 80 of file mclongstaffschwartzpathengine.hpp.
template<class GenericEngine, template< class > class MC, class RNG, class S = Statistics> const Size QuantLib::MCLongstaffSchwartzPathEngine< GenericEngine, MC, RNG, S >::nCalibrationSamples_ [protected]
Definition at line 82 of file mclongstaffschwartzpathengine.hpp.
template<class GenericEngine, template< class > class MC, class RNG, class S = Statistics> boost::shared_ptr<LongstaffSchwartzMultiPathPricer> QuantLib::MCLongstaffSchwartzPathEngine< GenericEngine, MC, RNG, S >::pathPricer_ [mutable, protected]
Definition at line 84 of file mclongstaffschwartzpathengine.hpp.
template<class GenericEngine, template< class > class MC, class RNG, class S = Statistics> boost::shared_ptr<StochasticProcess> QuantLib::MCLongstaffSchwartzPathEngine< GenericEngine, MC, RNG, S >::process_ [protected]
Definition at line 74 of file mclongstaffschwartzpathengine.hpp.
Referenced by QuantLib::MCLongstaffSchwartzPathEngine< GenericEngine, MC, RNG, S >::MCLongstaffSchwartzPathEngine().
template<class GenericEngine, template< class > class MC, class RNG, class S = Statistics> const Size QuantLib::MCLongstaffSchwartzPathEngine< GenericEngine, MC, RNG, S >::requiredSamples_ [protected]
Definition at line 78 of file mclongstaffschwartzpathengine.hpp.
template<class GenericEngine, template< class > class MC, class RNG, class S = Statistics> const Real QuantLib::MCLongstaffSchwartzPathEngine< GenericEngine, MC, RNG, S >::requiredTolerance_ [protected]
Definition at line 79 of file mclongstaffschwartzpathengine.hpp.
template<class GenericEngine, template< class > class MC, class RNG, class S = Statistics> const Size QuantLib::MCLongstaffSchwartzPathEngine< GenericEngine, MC, RNG, S >::seed_ [protected]
Definition at line 81 of file mclongstaffschwartzpathengine.hpp.
template<class GenericEngine, template< class > class MC, class RNG, class S = Statistics> const Size QuantLib::MCLongstaffSchwartzPathEngine< GenericEngine, MC, RNG, S >::timeSteps_ [protected]
Definition at line 75 of file mclongstaffschwartzpathengine.hpp.
template<class GenericEngine, template< class > class MC, class RNG, class S = Statistics> const Size QuantLib::MCLongstaffSchwartzPathEngine< GenericEngine, MC, RNG, S >::timeStepsPerYear_ [protected]
Definition at line 76 of file mclongstaffschwartzpathengine.hpp.
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/mcbasket/mclongstaffschwartzpathengine.hpp