QuantLib: QuantLib::OneAssetOption Class Reference
QuantLib::OneAssetOption Class Reference
Base class for options on a single asset.
#include <oneassetoption.hpp>
Classes
class engine
class results
Results from single-asset option calculation
Public Member Functions
OneAssetOption (const boost::shared_ptr< Payoff > &, const boost::shared_ptr< Exercise > &)
void fetchResults (const PricingEngine::results *) const
Instrument interface
bool isExpired () const
returns whether the instrument might have value greater than zero.
greeks
Real delta () const
Real deltaForward () const
Real elasticity () const
Real gamma () const
Real theta () const
Real thetaPerDay () const
Real vega () const
Real rho () const
Real dividendRho () const
Real strikeSensitivity () const
Real itmCashProbability () const
Protected Member Functions
void setupExpired () const
Protected Attributes
Real delta_
Real deltaForward_
Real elasticity_
Real gamma_
Real theta_
Real thetaPerDay_
Real vega_
Real rho_
Real dividendRho_
Real strikeSensitivity_
Real itmCashProbability_
Detailed Description
Base class for options on a single asset.
Definition at line 34 of file oneassetoption.hpp.
Constructor & Destructor Documentation
QuantLib::OneAssetOption::OneAssetOption (const boost::shared_ptr< Payoff > & payoff, const boost::shared_ptr< Exercise > & exercise)
Definition at line 28 of file oneassetoption.cpp.
    : Option(payoff, exercise) {}
Member Function Documentation
Real QuantLib::OneAssetOption::delta () const
Definition at line 37 of file oneassetoption.cpp.
References QuantLib::Instrument::calculate(), delta_, and QL_REQUIRE.
Referenced by AsianOptionTest::testAnalyticContinuousGeometricAveragePriceGreeks(), AsianOptionTest::testAnalyticDiscreteGeometricAveragePriceGreeks(), HybridHestonHullWhiteProcessTest::testBsmHullWhiteEngine(), DigitalOptionTest::testCashAtHitOrNothingAmericanGreeks(), DividendOptionTest::testEuropeanGreeks(), anonymous_namespace{americanoption.cpp}::testFdGreeks(), anonymous_namespace{dividendoption.cpp}::testFdGreeks(), FdHestonTest::testFdmHestonAmerican(), FdHestonTest::testFdmHestonBarrier(), FdHestonTest::testFdmHestonEuropeanWithDividends(), HybridHestonHullWhiteProcessTest::testFdmHestonHullWhiteEngine(), QuantoOptionTest::testForwardGreeks(), anonymous_namespace{forwardoption.cpp}::testForwardGreeks(), JumpDiffusionTest::testGreeks(), QuantoOptionTest::testGreeks(), EuropeanOptionTest::testGreeks(), EuropeanOptionTest::testLocalVolatility(), HestonModelTest::testMultipleStrikesEngine(), anonymous_namespace{cliquetoption.cpp}::testOptionGreeks(), and CompoundOptionTest::testValues().
{
        calculate();
        QL_REQUIRE(delta_ != Null<Real>(), "delta not provided");
        return delta_;
    }
Real QuantLib::OneAssetOption::deltaForward () const
Definition at line 43 of file oneassetoption.cpp.
References QuantLib::Instrument::calculate(), deltaForward_, and QL_REQUIRE.
{
        calculate();
        QL_REQUIRE(deltaForward_ != Null<Real>(),
                   "forward delta not provided");
        return deltaForward_;
    }
Real QuantLib::OneAssetOption::dividendRho () const
Definition at line 86 of file oneassetoption.cpp.
References QuantLib::Instrument::calculate(), dividendRho_, and QL_REQUIRE.
Referenced by AsianOptionTest::testAnalyticContinuousGeometricAveragePriceGreeks(), AsianOptionTest::testAnalyticDiscreteGeometricAveragePriceGreeks(), QuantoOptionTest::testForwardGreeks(), anonymous_namespace{forwardoption.cpp}::testForwardGreeks(), JumpDiffusionTest::testGreeks(), EuropeanOptionTest::testGreeks(), QuantoOptionTest::testGreeks(), and anonymous_namespace{cliquetoption.cpp}::testOptionGreeks().
{
        calculate();
        QL_REQUIRE(dividendRho_ != Null<Real>(), "dividend rho not provided");
        return dividendRho_;
    }
Real QuantLib::OneAssetOption::elasticity () const
Definition at line 50 of file oneassetoption.cpp.
References QuantLib::Instrument::calculate(), elasticity_, and QL_REQUIRE.
{
        calculate();
        QL_REQUIRE(elasticity_ != Null<Real>(), "elasticity not provided");
        return elasticity_;
    }
void QuantLib::OneAssetOption::fetchResults (const PricingEngine::results * r) const [virtual]
When a derived result structure is defined for an instrument, this method should be overridden to read from it. This is mandatory in case a pricing engine is used.
Reimplemented from QuantLib::Instrument.
Reimplemented in QuantLib::QuantoVanillaOption, QuantLib::ForwardVanillaOption, QuantLib::QuantoBarrierOption, and QuantLib::QuantoForwardVanillaOption.
Definition at line 113 of file oneassetoption.cpp.
References QuantLib::Greeks::delta, delta_, QuantLib::MoreGreeks::deltaForward, deltaForward_, QuantLib::Greeks::dividendRho, dividendRho_, QuantLib::MoreGreeks::elasticity, elasticity_, QuantLib::Greeks::gamma, gamma_, QuantLib::MoreGreeks::itmCashProbability, itmCashProbability_, QL_ENSURE, QuantLib::Greeks::rho, rho_, QuantLib::MoreGreeks::strikeSensitivity, strikeSensitivity_, QuantLib::Greeks::theta, theta_, QuantLib::MoreGreeks::thetaPerDay, thetaPerDay_, QuantLib::Greeks::vega, and vega_.
{
        Option::fetchResults(r);
        const Greeks* results = dynamic_cast<const Greeks*>(r);
        QL_ENSURE(results != 0,
                  "no greeks returned from pricing engine");
        /* no check on null values - just copy.
           this allows:
           a) to decide in derived options what to do when null
           results are returned (throw? numerical calculation?)
           b) to implement slim engines which only calculate the
           value---of course care must be taken not to call
           the greeks methods when using these.
        */
        delta_          = results->delta;
        gamma_          = results->gamma;
        theta_          = results->theta;
        vega_           = results->vega;
        rho_            = results->rho;
        dividendRho_    = results->dividendRho;
        const MoreGreeks* moreResults = dynamic_cast<const MoreGreeks*>(r);
        QL_ENSURE(moreResults != 0,
                  "no more greeks returned from pricing engine");
        /* no check on null values - just copy.
           this allows:
           a) to decide in derived options what to do when null
           results are returned (throw? numerical calculation?)
           b) to implement slim engines which only calculate the
           value---of course care must be taken not to call
           the greeks methods when using these.
        */
        deltaForward_       = moreResults->deltaForward;
        elasticity_         = moreResults->elasticity;
        thetaPerDay_        = moreResults->thetaPerDay;
        strikeSensitivity_  = moreResults->strikeSensitivity;
        itmCashProbability_ = moreResults->itmCashProbability;
    }
Real QuantLib::OneAssetOption::gamma () const
Definition at line 56 of file oneassetoption.cpp.
References QuantLib::Instrument::calculate(), gamma_, and QL_REQUIRE.
Referenced by AsianOptionTest::testAnalyticContinuousGeometricAveragePriceGreeks(), AsianOptionTest::testAnalyticDiscreteGeometricAveragePriceGreeks(), HybridHestonHullWhiteProcessTest::testBsmHullWhiteEngine(), DigitalOptionTest::testCashAtHitOrNothingAmericanGreeks(), FdmLinearOpTest::testCrankNicolsonWithDamping(), DividendOptionTest::testEuropeanGreeks(), anonymous_namespace{americanoption.cpp}::testFdGreeks(), anonymous_namespace{dividendoption.cpp}::testFdGreeks(), FdHestonTest::testFdmHestonAmerican(), FdHestonTest::testFdmHestonBarrier(), FdHestonTest::testFdmHestonEuropeanWithDividends(), HybridHestonHullWhiteProcessTest::testFdmHestonHullWhiteEngine(), QuantoOptionTest::testForwardGreeks(), anonymous_namespace{forwardoption.cpp}::testForwardGreeks(), JumpDiffusionTest::testGreeks(), QuantoOptionTest::testGreeks(), EuropeanOptionTest::testGreeks(), EuropeanOptionTest::testLocalVolatility(), HestonModelTest::testMultipleStrikesEngine(), anonymous_namespace{cliquetoption.cpp}::testOptionGreeks(), and CompoundOptionTest::testValues().
{
        calculate();
        QL_REQUIRE(gamma_ != Null<Real>(), "gamma not provided");
        return gamma_;
    }
bool QuantLib::OneAssetOption::isExpired () const [virtual]
returns whether the instrument might have value greater than zero.
Implements QuantLib::Instrument.
Reimplemented in QuantLib::VanillaSwingOption, QuantLib::WriterExtensibleOption, and QuantLib::VanillaStorageOption.
Definition at line 33 of file oneassetoption.cpp.
References QuantLib::Option::exercise_.
Referenced by QuantLib::DividendVanillaOption::impliedVolatility(), QuantLib::BarrierOption::impliedVolatility(), and QuantLib::VanillaOption::impliedVolatility().
{
        return detail::simple_event(exercise_->lastDate()).hasOccurred();
    }
Real QuantLib::OneAssetOption::itmCashProbability () const
Definition at line 99 of file oneassetoption.cpp.
References QuantLib::Instrument::calculate(), itmCashProbability_, and QL_REQUIRE.
{
        calculate();
        QL_REQUIRE(itmCashProbability_ != Null<Real>(),
                   "in-the-money cash probability not provided");
        return itmCashProbability_;
    }
Real QuantLib::OneAssetOption::rho () const
Definition at line 80 of file oneassetoption.cpp.
References QuantLib::Instrument::calculate(), QL_REQUIRE, and rho_.
Referenced by AsianOptionTest::testAnalyticContinuousGeometricAveragePriceGreeks(), AsianOptionTest::testAnalyticDiscreteGeometricAveragePriceGreeks(), DigitalOptionTest::testCashAtHitOrNothingAmericanGreeks(), DividendOptionTest::testEuropeanGreeks(), QuantoOptionTest::testForwardGreeks(), anonymous_namespace{forwardoption.cpp}::testForwardGreeks(), JumpDiffusionTest::testGreeks(), QuantoOptionTest::testGreeks(), EuropeanOptionTest::testGreeks(), and anonymous_namespace{cliquetoption.cpp}::testOptionGreeks().
{
        calculate();
        QL_REQUIRE(rho_ != Null<Real>(), "rho not provided");
        return rho_;
    }
void QuantLib::OneAssetOption::setupExpired () const [protected, virtual]
This method must leave the instrument in a consistent state when the expiration condition is met.
Reimplemented from QuantLib::Instrument.
Reimplemented in QuantLib::QuantoVanillaOption, QuantLib::QuantoBarrierOption, and QuantLib::QuantoForwardVanillaOption.
Definition at line 106 of file oneassetoption.cpp.
References delta_, deltaForward_, dividendRho_, elasticity_, gamma_, itmCashProbability_, rho_, strikeSensitivity_, theta_, thetaPerDay_, and vega_.
{
        Option::setupExpired();
        delta_ = deltaForward_ = elasticity_ = gamma_ = theta_ =
            thetaPerDay_ = vega_ = rho_ = dividendRho_ =
            strikeSensitivity_ = itmCashProbability_ = 0.0;
    }
Real QuantLib::OneAssetOption::strikeSensitivity () const
Definition at line 92 of file oneassetoption.cpp.
References QuantLib::Instrument::calculate(), QL_REQUIRE, and strikeSensitivity_.
{
        calculate();
        QL_REQUIRE(strikeSensitivity_ != Null<Real>(),
                   "strike sensitivity not provided");
        return strikeSensitivity_;
    }
Real QuantLib::OneAssetOption::theta () const
Definition at line 62 of file oneassetoption.cpp.
References QuantLib::Instrument::calculate(), QL_REQUIRE, and theta_.
Referenced by AsianOptionTest::testAnalyticContinuousGeometricAveragePriceGreeks(), AsianOptionTest::testAnalyticDiscreteGeometricAveragePriceGreeks(), HybridHestonHullWhiteProcessTest::testBsmHullWhiteEngine(), DividendOptionTest::testEuropeanGreeks(), QuantoOptionTest::testForwardGreeks(), anonymous_namespace{forwardoption.cpp}::testForwardGreeks(), JumpDiffusionTest::testGreeks(), EuropeanOptionTest::testGreeks(), QuantoOptionTest::testGreeks(), HestonModelTest::testMultipleStrikesEngine(), anonymous_namespace{cliquetoption.cpp}::testOptionGreeks(), and CompoundOptionTest::testValues().
{
        calculate();
        QL_REQUIRE(theta_ != Null<Real>(), "theta not provided");
        return theta_;
    }
Real QuantLib::OneAssetOption::thetaPerDay () const
Definition at line 68 of file oneassetoption.cpp.
References QuantLib::Instrument::calculate(), QL_REQUIRE, and thetaPerDay_.
{
        calculate();
        QL_REQUIRE(thetaPerDay_ != Null<Real>(), "theta per-day not provided");
        return thetaPerDay_;
    }
Real QuantLib::OneAssetOption::vega () const
Definition at line 74 of file oneassetoption.cpp.
References QuantLib::Instrument::calculate(), QL_REQUIRE, and vega_.
Referenced by AsianOptionTest::testAnalyticContinuousGeometricAveragePriceGreeks(), AsianOptionTest::testAnalyticDiscreteGeometricAveragePriceGreeks(), HybridHestonHullWhiteProcessTest::testBsmHullWhiteEngine(), DividendOptionTest::testEuropeanGreeks(), QuantoOptionTest::testForwardGreeks(), anonymous_namespace{forwardoption.cpp}::testForwardGreeks(), JumpDiffusionTest::testGreeks(), QuantoOptionTest::testGreeks(), EuropeanOptionTest::testGreeks(), anonymous_namespace{cliquetoption.cpp}::testOptionGreeks(), and CompoundOptionTest::testValues().
{
        calculate();
        QL_REQUIRE(vega_ != Null<Real>(), "vega not provided");
        return vega_;
    }
Member Data Documentation
Real QuantLib::OneAssetOption::delta_ [mutable, protected]
Definition at line 62 of file oneassetoption.hpp.
Referenced by delta(), QuantLib::ForwardVanillaOption::fetchResults(), fetchResults(), and setupExpired().
Real QuantLib::OneAssetOption::deltaForward_ [mutable, protected]
Definition at line 62 of file oneassetoption.hpp.
Referenced by deltaForward(), fetchResults(), and setupExpired().
Real QuantLib::OneAssetOption::dividendRho_ [mutable, protected]
Definition at line 62 of file oneassetoption.hpp.
Referenced by dividendRho(), QuantLib::ForwardVanillaOption::fetchResults(), fetchResults(), and setupExpired().
Real QuantLib::OneAssetOption::elasticity_ [mutable, protected]
Definition at line 62 of file oneassetoption.hpp.
Referenced by elasticity(), fetchResults(), and setupExpired().
Real QuantLib::OneAssetOption::gamma_ [mutable, protected]
Definition at line 62 of file oneassetoption.hpp.
Referenced by QuantLib::ForwardVanillaOption::fetchResults(), fetchResults(), gamma(), and setupExpired().
Real QuantLib::OneAssetOption::itmCashProbability_ [mutable, protected]
Definition at line 62 of file oneassetoption.hpp.
Referenced by fetchResults(), itmCashProbability(), and setupExpired().
Real QuantLib::OneAssetOption::rho_ [mutable, protected]
Definition at line 62 of file oneassetoption.hpp.
Referenced by QuantLib::ForwardVanillaOption::fetchResults(), fetchResults(), rho(), and setupExpired().
Real QuantLib::OneAssetOption::strikeSensitivity_ [mutable, protected]
Definition at line 62 of file oneassetoption.hpp.
Referenced by fetchResults(), setupExpired(), and strikeSensitivity().
Real QuantLib::OneAssetOption::theta_ [mutable, protected]
Definition at line 62 of file oneassetoption.hpp.
Referenced by QuantLib::ForwardVanillaOption::fetchResults(), fetchResults(), setupExpired(), and theta().
Real QuantLib::OneAssetOption::thetaPerDay_ [mutable, protected]
Definition at line 62 of file oneassetoption.hpp.
Referenced by fetchResults(), setupExpired(), and thetaPerDay().
Real QuantLib::OneAssetOption::vega_ [mutable, protected]
Definition at line 62 of file oneassetoption.hpp.
Referenced by QuantLib::ForwardVanillaOption::fetchResults(), fetchResults(), setupExpired(), and vega().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/oneassetoption.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/oneassetoption.cpp