QuantLib: MCLongstaffSchwartzEngineTest Class Reference
MCLongstaffSchwartzEngineTest Class Reference
#include <mclongstaffschwartzengine.hpp>
Static Public Member Functions
static void testAmericanOption ()
static void testAmericanMaxOption ()
static
boost::unit_test_framework::test_suite * suite ()
Detailed Description
Definition at line 28 of file mclongstaffschwartzengine.hpp.
Member Function Documentation
test_suite * MCLongstaffSchwartzEngineTest::suite () [static]
Definition at line 297 of file mclongstaffschwartzengine.cpp.
References QUANTLIB_TEST_CASE, testAmericanMaxOption(), and testAmericanOption().
Referenced by init_unit_test_suite().
{
    test_suite* suite = BOOST_TEST_SUITE("Longstaff Schwartz MC engine tests");
    // FLOATING_POINT_EXCEPTION
    suite->add(QUANTLIB_TEST_CASE(
         &MCLongstaffSchwartzEngineTest::testAmericanOption));
    suite->add(QUANTLIB_TEST_CASE(
         &MCLongstaffSchwartzEngineTest::testAmericanMaxOption));
    return suite;
}
void MCLongstaffSchwartzEngineTest::testAmericanMaxOption () [static]
Definition at line 210 of file mclongstaffschwartzengine.cpp.
References QuantLib::Option::Call, anonymous_namespace{marketmodel.cpp}::dayCounter, QuantLib::Instrument::errorEstimate(), QuantLib::Settings::evaluationDate(), QuantLib::Singleton< Settings >::instance(), QuantLib::RelinkableHandle< T >::linkTo(), QuantLib::May, QuantLib::Instrument::NPV(), QuantLib::Instrument::setPricingEngine(), anonymous_namespace{marketmodel.cpp}::todaysDate, anonymous_namespace{swaption.cpp}::type, anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::io::volatility().
Referenced by suite().
{
    // reference values taken from
    // "Monte Carlo Methods in Financial Engineering",
    // by Paul Glasserman, 2004 Springer Verlag, p. 462
    BOOST_MESSAGE("Testing Monte-Carlo pricing of American max options...");
    SavedSettings backup;
    // most of the example taken from the EquityOption.cpp
    const Option::Type type(Option::Call);
    const Real strike = 100;
    const Spread dividendYield = 0.10;
    const Rate riskFreeRate = 0.05;
    const Volatility volatility = 0.20;
    const Date todaysDate(15, May, 1998);
    const Date settlementDate(17, May, 1998);
    Settings::instance().evaluationDate() = todaysDate;
    const Date maturity(16, May, 2001);
    const DayCounter dayCounter = Actual365Fixed();
    boost::shared_ptr<Exercise> americanExercise(
        new AmericanExercise(settlementDate, maturity));
    // bootstrap the yield/dividend/vol curves
    Handle<YieldTermStructure> flatTermStructure(
        boost::shared_ptr<YieldTermStructure>(
            new FlatForward(settlementDate, riskFreeRate, dayCounter)));
    Handle<YieldTermStructure> flatDividendTS(
        boost::shared_ptr<YieldTermStructure>(
            new FlatForward(settlementDate, dividendYield, dayCounter)));
    Handle<BlackVolTermStructure> flatVolTS(
        boost::shared_ptr<BlackVolTermStructure>(new
            BlackConstantVol(settlementDate, NullCalendar(),
                             volatility, dayCounter)));
    boost::shared_ptr<StrikedTypePayoff> payoff(
        new PlainVanillaPayoff(type, strike));
    RelinkableHandle<Quote> underlyingH;
    boost::shared_ptr<GeneralizedBlackScholesProcess> stochasticProcess(new
        GeneralizedBlackScholesProcess(
            underlyingH, flatDividendTS, flatTermStructure, flatVolTS));
    const Size numberAssets = 2;
    Matrix corr(numberAssets, numberAssets, 0.0);
    std::vector<boost::shared_ptr<StochasticProcess1D> > v;
    for (Size i=0; i<numberAssets; ++i) {
        v.push_back(stochasticProcess);
        corr[i][i] = 1.0;
    }
    boost::shared_ptr<StochasticProcessArray> process(
        new StochasticProcessArray(v, corr));
    VanillaOption americanMaxOption(payoff, americanExercise);
    boost::shared_ptr<PricingEngine> mcengine(
        new MCAmericanMaxEngine<PseudoRandom>(process, 25, Null<Size>(), false,
                                              true, false, 4096,
                                              Null<Real>(), Null<Size>(),
                                              42, 1024));
    americanMaxOption.setPricingEngine(mcengine);
    const Real expected[] = {8.08, 13.90, 21.34};
    for (Size i = 0; i < 3; ++i) {
        const Real underlying = 90.0 + i*10.0;
        underlyingH.linkTo(
            boost::shared_ptr<Quote>(new SimpleQuote(underlying)));
        const Real calculated  = americanMaxOption.NPV();
        const Real errorEstimate = americanMaxOption.errorEstimate();
        if (std::fabs(calculated - expected[i]) > 2.34*errorEstimate) {
                BOOST_ERROR("Failed to reproduce american option prices"
                            << "\n    expected: " << expected[i]
                            << "\n    calculated:   " << calculated
                            << " +/- " << errorEstimate);
        }
    }
}
void MCLongstaffSchwartzEngineTest::testAmericanOption () [static]
Definition at line 124 of file mclongstaffschwartzengine.cpp.
References QuantLib::LsmBasisSystem::Chebyshev2nd, anonymous_namespace{marketmodel.cpp}::dayCounter, QuantLib::Instrument::errorEstimate(), QuantLib::Settings::evaluationDate(), QuantLib::LsmBasisSystem::Hermite, QuantLib::LsmBasisSystem::Hyperbolic, QuantLib::Singleton< Settings >::instance(), QuantLib::LsmBasisSystem::Laguerre, LENGTH, QuantLib::May, QuantLib::LsmBasisSystem::Monomial, QuantLib::Instrument::NPV(), QuantLib::Option::Put, QuantLib::Instrument::setPricingEngine(), anonymous_namespace{marketmodel.cpp}::todaysDate, anonymous_namespace{swaption.cpp}::type, QuantLib::io::volatility(), QuantLib::MakeMCAmericanEngine< RNG, S >::withAbsoluteTolerance(), QuantLib::MakeMCAmericanEngine< RNG, S >::withAntitheticVariate(), QuantLib::MakeMCAmericanEngine< RNG, S >::withBasisSystem(), QuantLib::MakeMCAmericanEngine< RNG, S >::withPolynomOrder(), and QuantLib::MakeMCAmericanEngine< RNG, S >::withSeed().
Referenced by suite().
{
    BOOST_MESSAGE("Testing Monte-Carlo pricing of American options...");
    SavedSettings backup;
    // most of the example taken from the EquityOption.cpp
    const Option::Type type(Option::Put);
    const Real underlying = 36;
    const Spread dividendYield = 0.00;
    const Rate riskFreeRate = 0.06;
    const Volatility volatility = 0.20;
    const Date todaysDate(15, May, 1998);
    const Date settlementDate(17, May, 1998);
    Settings::instance().evaluationDate() = todaysDate;
    const Date maturity(17, May, 1999);
    const DayCounter dayCounter = Actual365Fixed();
    boost::shared_ptr<Exercise> americanExercise(
        new AmericanExercise(settlementDate, maturity));
    // bootstrap the yield/dividend/vol curves
    Handle<YieldTermStructure> flatTermStructure(
            boost::shared_ptr<YieldTermStructure>(
                new FlatForward(settlementDate, riskFreeRate, dayCounter)));
    Handle<YieldTermStructure> flatDividendTS(
            boost::shared_ptr<YieldTermStructure>(
                new FlatForward(settlementDate, dividendYield, dayCounter)));
    LsmBasisSystem::PolynomType polynomTypes[]
        = { LsmBasisSystem::Monomial, LsmBasisSystem::Laguerre,
            LsmBasisSystem::Hermite, LsmBasisSystem::Hyperbolic,
            LsmBasisSystem::Chebyshev2nd };
    for (Integer i=0; i<2; ++i) {
        for (Integer j=0; j<3; ++j) {
            Handle<BlackVolTermStructure> flatVolTS(
                boost::shared_ptr<BlackVolTermStructure>(
                    new BlackConstantVol(settlementDate, NullCalendar(),
                                         volatility+0.1*j, dayCounter)));
            boost::shared_ptr<StrikedTypePayoff> payoff(
                new PlainVanillaPayoff(type, underlying+4*i));
            Handle<Quote> underlyingH(
                boost::shared_ptr<Quote>(new SimpleQuote(underlying)));
            boost::shared_ptr<GeneralizedBlackScholesProcess>
                stochasticProcess(new GeneralizedBlackScholesProcess(
                                      underlyingH, flatDividendTS,
                                      flatTermStructure, flatVolTS));
            VanillaOption americanOption(payoff, americanExercise);
            boost::shared_ptr<PricingEngine> mcengine =
                MakeMCAmericanEngine<PseudoRandom>(stochasticProcess)
                  .withSteps(75)
                  .withAntitheticVariate()
                  .withAbsoluteTolerance(0.02)
                  .withSeed(42)
                  .withPolynomOrder(3)
                  .withBasisSystem(
                       polynomTypes[0*(i*3+j)%LENGTH(polynomTypes)]);
            americanOption.setPricingEngine(mcengine);
            // FLOATING_POINT_EXCEPTION
            const Real calculated = americanOption.NPV();
            const Real errorEstimate = americanOption.errorEstimate();
            americanOption.setPricingEngine(boost::shared_ptr<PricingEngine>(
                        new FDAmericanEngine<CrankNicolson>(stochasticProcess,
                                                            401, 200)));
            const Real expected = americanOption.NPV();
            if (std::fabs(calculated - expected) > 2.34*errorEstimate) {
                BOOST_ERROR("Failed to reproduce american option prices"
                            << "\n    expected: " << expected
                            << "\n    calculated:   " << calculated
                            << " +/- " << errorEstimate);
            }
        }
    }
}
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/mclongstaffschwartzengine.hpp
/home/deriversatile/QuantLib/QuantLibQt/test-suite/mclongstaffschwartzengine.cpp