QuantLib: QuantLib::MultiplicativePriceSeasonality Class Reference
QuantLib::MultiplicativePriceSeasonality Class Reference
Multiplicative seasonality in the price index (CPI/RPI/HICP/etc).
#include <seasonality.hpp>
Public Member Functions
MultiplicativePriceSeasonality ()
MultiplicativePriceSeasonality (const Date &seasonalityBaseDate, const Frequency frequency, const std::vector< Rate > seasonalityFactors)
virtual void set (const Date &seasonalityBaseDate, const Frequency frequency, const std::vector< Rate > seasonalityFactors)
virtual ~MultiplicativePriceSeasonality ()
virtual Date seasonalityBaseDate () const
inspectors
virtual Frequency frequency () const
virtual std::vector< Rate > seasonalityFactors () const
virtual Rate seasonalityFactor (const Date &d) const
The factor returned is NOT normalized relative to ANYTHING.
Seasonality interface
virtual Rate correctZeroRate (const Date &d, const Rate r, const InflationTermStructure &iTS) const
virtual Rate correctYoYRate (const Date &d, const Rate r, const InflationTermStructure &iTS) const
virtual bool isConsistent (const InflationTermStructure &iTS) const
Protected Member Functions
virtual void validate () const
virtual Rate seasonalityCorrection (Rate r, const Date &d, const DayCounter &dc, const Date &curveBaseDate, bool isZeroRate) const
Private Attributes
Date seasonalityBaseDate_
Frequency frequency_
std::vector< Rate > seasonalityFactors_
Detailed Description
Multiplicative seasonality in the price index (CPI/RPI/HICP/etc).
Stationary multiplicative seasonality in CPI/RPI/HICP (i.e. in price) implies that zero inflation swap rates are affected, but that year-on-year inflation swap rates show no effect. Of course, if the seasonality in CPI/RPI/HICP is non-stationary then both swap rates will be affected.
Factors must be in multiples of the minimum required for one year, e.g. 12 for monthly, and these factors are reused for as long as is required, i.e. they wrap around. So, for example, if 24 factors are given this repeats every two years. True stationary seasonality can be obtained by giving the same number of factors as the frequency dictates e.g. 12 for monthly seasonality.
Warning:
Multi-year seasonality (i.e. non-stationary) is fragile: the user must ensure that corrections at whole years before and after the inflation term structure base date are the same. Otherwise there can be an inconsistency with quoted rates. This is enforced if the frequency is lower than daily. This is not enforced for daily seasonality because this will always be inconsistent due to weekends, holidays, leap years, etc. If you use multi-year daily seasonality it is up to you to check.
Note:
Factors are normalized relative to their appropriate reference dates. For zero inflation this is the inflation curve true base date: since you have a fixing for that date the seasonality factor must be one. For YoY inflation the reference is always one year earlier.
Seasonality is treated as piecewise constant, hence it works correctly with uninterpolated indices if the seasonality correction factor frequency is the same as the index frequency (or less).
Definition at line 118 of file seasonality.hpp.
Constructor & Destructor Documentation
QuantLib::MultiplicativePriceSeasonality::MultiplicativePriceSeasonality ()
Definition at line 35 of file seasonality.cpp.
{
    }
QuantLib::MultiplicativePriceSeasonality::MultiplicativePriceSeasonality (const Date & seasonalityBaseDate, const Frequency frequency, const std::vector< Rate > seasonalityFactors)
Definition at line 91 of file seasonality.cpp.
References frequency(), seasonalityBaseDate(), and seasonalityFactors().
    {
        set(seasonalityBaseDate, frequency, seasonalityFactors);
    }
virtual QuantLib::MultiplicativePriceSeasonality::~MultiplicativePriceSeasonality () [inline, virtual]
Definition at line 156 of file seasonality.hpp.
{};
Member Function Documentation
Rate QuantLib::MultiplicativePriceSeasonality::correctYoYRate (const Date & d, const Rate r, const InflationTermStructure & iTS) const [virtual]
Implements QuantLib::Seasonality.
Definition at line 131 of file seasonality.cpp.
References QuantLib::InflationTermStructure::baseDate(), QuantLib::TermStructure::dayCounter(), QuantLib::InflationTermStructure::frequency(), QuantLib::inflationPeriod(), and seasonalityCorrection().
{
        std::pair<Date,Date> lim = inflationPeriod(iTS.baseDate(), iTS.frequency());
        Date curveBaseDate = lim.second;
        return seasonalityCorrection(r, d, iTS.dayCounter(), curveBaseDate, false);
    }
Rate QuantLib::MultiplicativePriceSeasonality::correctZeroRate (const Date & d, const Rate r, const InflationTermStructure & iTS) const [virtual]
Implements QuantLib::Seasonality.
Definition at line 122 of file seasonality.cpp.
References QuantLib::InflationTermStructure::baseDate(), QuantLib::TermStructure::dayCounter(), QuantLib::InflationTermStructure::frequency(), QuantLib::inflationPeriod(), and seasonalityCorrection().
{
        std::pair<Date,Date> lim = inflationPeriod(iTS.baseDate(), iTS.frequency());
        Date curveBaseDate = lim.second;
        return seasonalityCorrection(r, d, iTS.dayCounter(), curveBaseDate, true);
    }
Frequency QuantLib::MultiplicativePriceSeasonality::frequency () const [virtual]
Definition at line 113 of file seasonality.cpp.
References frequency_.
Referenced by isConsistent(), MultiplicativePriceSeasonality(), seasonalityFactor(), set(), and validate().
{
        return frequency_;
    }
bool QuantLib::MultiplicativePriceSeasonality::isConsistent (const InflationTermStructure & iTS) const [virtual]
It is possible for multi-year seasonalities to be inconsistent with the inflation term structure they are given to. This method enables testing - but programmers are not required to implement it. E.g. for price seasonality the corrections at whole years after the inflation curve base date should be the same or else there can be an inconsistency with quoted instruments. Alternatively, the seasonality can be set _before_ the inflation curve is bootstrapped.
Reimplemented from QuantLib::Seasonality.
Definition at line 64 of file seasonality.cpp.
References QuantLib::InflationTermStructure::baseDate(), QuantLib::Daily, QuantLib::InflationTermStructure::frequency(), frequency(), QuantLib::inflationPeriod(), QL_REQUIRE, seasonalityFactor(), seasonalityFactors(), and QuantLib::Years.
    {
        // If multi-year is the specification consistent with the term structure start date?
        // We do NOT test daily seasonality because this will, in general, never be consistent
        // given weekends, holidays, leap years, etc.
        if(this->frequency() == Daily) return true;
        if(Size(this->frequency()) == seasonalityFactors().size()) return true;
        // how many years do you need to test?
        Size nTest = seasonalityFactors().size() / this->frequency();
        // ... relative to the start of the inflation curve
        std::pair<Date,Date> lim = inflationPeriod(iTS.baseDate(), iTS.frequency());
        Date curveBaseDate = lim.second;
        Real factorBase = this->seasonalityFactor(curveBaseDate);
        Real eps = 0.00001;
        for (Size i = 1; i < nTest; i++) {
            Real factorAt = this->seasonalityFactor(curveBaseDate+Period(i,Years));
            QL_REQUIRE(fabs(factorAt-factorBase)<eps,"seasonality is inconsistent with inflation term structure, factors "
                       << factorBase << " and later factor " << factorAt << ", " << i << " years later from inflation curve "
                       <<" with base date at " << curveBaseDate);
        }
        return true;
    }
Date QuantLib::MultiplicativePriceSeasonality::seasonalityBaseDate () const [virtual]
inspectors
Definition at line 109 of file seasonality.cpp.
References seasonalityBaseDate_.
Referenced by MultiplicativePriceSeasonality(), seasonalityFactor(), and set().
{
        return seasonalityBaseDate_;
    }
Rate QuantLib::MultiplicativePriceSeasonality::seasonalityCorrection (Rate r, const Date & d, const DayCounter & dc, const Date & curveBaseDate, bool isZeroRate) const [protected, virtual]
Definition at line 186 of file seasonality.cpp.
References anonymous_namespace{interpolations.cpp}::f(), QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow(), seasonalityFactor(), QuantLib::DayCounter::yearFraction(), and QuantLib::Years.
Referenced by correctYoYRate(), and correctZeroRate().
{
        // need _two_ corrections in order to get: seasonality = factor[atDate-seasonalityBase] / factor[reference-seasonalityBase]
        // i.e. for ZERO inflation rates you have the true fixing at the curve base so this factor must be normalized to one
        //      for YoY inflation rates your reference point is the year before
        Real factorAt = this->seasonalityFactor(atDate);
        //Getting seasonality correction for either ZC or YoY
        Rate f;
        if (isZeroRate) {
            Rate factorBase = this->seasonalityFactor(curveBaseDate);
            Real seasonalityAt = factorAt / factorBase;
            Time timeFromCurveBase = dc.yearFraction(curveBaseDate, atDate);
            f = pow(seasonalityAt, 1/timeFromCurveBase);
        }
        else {
            Rate factor1Ybefore = this->seasonalityFactor(atDate - Period(1,Years));
            f = factorAt / factor1Ybefore;
        }
        return (rate + 1)*f - 1;
    }
Real QuantLib::MultiplicativePriceSeasonality::seasonalityFactor (const Date & d) const [virtual]
The factor returned is NOT normalized relative to ANYTHING.
Definition at line 140 of file seasonality.cpp.
References QuantLib::Days, frequency(), QuantLib::inflationPeriod(), QuantLib::Period::length(), QuantLib::Months, QL_FAIL, seasonalityBaseDate(), seasonalityFactors(), QuantLib::Period::units(), QuantLib::Weeks, and QuantLib::Years.
Referenced by isConsistent(), and seasonalityCorrection().
{
        Date from = seasonalityBaseDate();
        Frequency factorFrequency = frequency();
        Size nFactors = seasonalityFactors().size();
        Period factorPeriod(factorFrequency);
        Size which = 0;
        if (from==to) {
            which = 0;
        } else {
            // days, weeks, months, years are the only time unit possibilities
            Integer diffDays = std::abs(to - from);  // in days
            Integer dir = 1;
            if(from > to)dir = -1;
            Integer diff;
            if (factorPeriod.units() == Days) {
                diff = dir*diffDays;
            } else if (factorPeriod.units() == Weeks) {
                diff = dir * (diffDays / 7);
            } else if (factorPeriod.units() == Months) {
                std::pair<Date,Date> lim = inflationPeriod(to, factorFrequency);
                diff = diffDays / (31*factorPeriod.length());
                Date go = from + dir*diff*factorPeriod;
                while ( !(lim.first <= go && go <= lim.second) ) {
                    go += dir*factorPeriod;
                    diff++;
                }
                diff=dir*diff;
            } else if (factorPeriod.units() == Years) {
                QL_FAIL("seasonality period time unit is not allowed to be : " << factorPeriod.units());
            } else {
                QL_FAIL("Unknown time unit: " << factorPeriod.units());
            }
            // now adjust to the available number of factors, direction dependent
            if (dir==1) {
                which = diff % nFactors;
            } else {
                which = (nFactors - (-diff % nFactors)) % nFactors;
            }
        }
        return seasonalityFactors()[which];
    }
std::vector< Rate > QuantLib::MultiplicativePriceSeasonality::seasonalityFactors () const [virtual]
Definition at line 117 of file seasonality.cpp.
References seasonalityFactors_.
Referenced by isConsistent(), MultiplicativePriceSeasonality(), seasonalityFactor(), and validate().
{
        return seasonalityFactors_;
    }
void QuantLib::MultiplicativePriceSeasonality::set (const Date & seasonalityBaseDate, const Frequency frequency, const std::vector< Rate > seasonalityFactors) [virtual]
Definition at line 97 of file seasonality.cpp.
References frequency(), frequency_, seasonalityBaseDate(), seasonalityBaseDate_, seasonalityFactors_, and validate().
    {
        frequency_ = frequency;
        seasonalityFactors_ = std::vector<Rate>(seasonalityFactors.size());
        for(Size i=0; i<seasonalityFactors.size(); i++) {
            seasonalityFactors_[i] = seasonalityFactors[i];
        }
        seasonalityBaseDate_ = seasonalityBaseDate;
        validate();
    }
void QuantLib::MultiplicativePriceSeasonality::validate () const [protected, virtual]
Definition at line 39 of file seasonality.cpp.
References QuantLib::Bimonthly, QuantLib::Biweekly, QuantLib::Daily, QuantLib::EveryFourthMonth, frequency(), QuantLib::Monthly, QL_FAIL, QL_REQUIRE, QuantLib::Quarterly, seasonalityFactors(), QuantLib::Semiannual, and QuantLib::Weekly.
Referenced by set().
    {
        switch (this->frequency()) {
            case Semiannual:        //2
            case EveryFourthMonth:  //3
            case Quarterly:         //4
            case Bimonthly:         //6
            case Monthly:           //12
            case Biweekly:          // etc.
            case Weekly:
            case Daily:
                QL_REQUIRE( (this->seasonalityFactors().size() %
                             this->frequency()) == 0,
                           "For frequency " << this->frequency()
                           << " require multiple of " << ((int)this->frequency()) << " factors "
                           << this->seasonalityFactors().size() << " were given.");
            break;
            default:
                QL_FAIL("bad frequency specified: " << this->frequency()
                        << ", only semi-annual through daily permitted.");
            break;
        }
    }
Member Data Documentation
Frequency QuantLib::MultiplicativePriceSeasonality::frequency_ [private]
Definition at line 122 of file seasonality.hpp.
Referenced by frequency(), and set().
Date QuantLib::MultiplicativePriceSeasonality::seasonalityBaseDate_ [private]
Definition at line 121 of file seasonality.hpp.
Referenced by seasonalityBaseDate(), and set().
std::vector<Rate> QuantLib::MultiplicativePriceSeasonality::seasonalityFactors_ [private]
Definition at line 123 of file seasonality.hpp.
Referenced by seasonalityFactors(), and set().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/inflation/seasonality.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/inflation/seasonality.cpp