QuantLib: QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D > Class Template Reference
QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D > Class Template Reference
#include <yoycapfloortermpricesurface.hpp>
Classes
class ObjectiveFunction
Public Member Functions
InterpolatedYoYCapFloorTermPriceSurface (Natural fixingDays, const Period &yyLag, const boost::shared_ptr< YoYInflationIndex > &yii, Rate baseRate, const Handle< YieldTermStructure > &nominal, const DayCounter &dc, const Calendar &cal, const BusinessDayConvention &bdc, const std::vector< Rate > &cStrikes, const std::vector< Rate > &fStrikes, const std::vector< Period > &cfMaturities, const Matrix &cPrice, const Matrix &fPrice, const Interpolator2D &interpolator2d=Interpolator2D(), const Interpolator1D &interpolator1d=Interpolator1D())
virtual Natural fixingDays () const
virtual Date maxDate () const
inflation term structure interface
virtual Date baseDate () const
minimum (base) date
YoYCapFloorTermPriceSurface interface
virtual std::pair< std::vector
< Time >, std::vector< Rate > > atmYoYSwapTimeRates () const
atm yoy swaps from put-call parity on cap/floor data
virtual std::pair< std::vector
< Date >, std::vector< Rate > > atmYoYSwapDateRates () const
virtual boost::shared_ptr
< YoYInflationTermStructure > YoYTS () const
derived from yoy swap rates
virtual Rate price (const Date &d, const Rate k) const
virtual Real floorPrice (const Date &d, const Rate k) const
virtual Real capPrice (const Date &d, const Rate k) const
virtual Rate atmYoYSwapRate (const Date &d, bool extrapolate=true) const
virtual Rate atmYoYRate (const Date &d, const Period &obsLag=Period(-1, Days), bool extrapolate=true) const
LazyObject interface
void update ()
void performCalculations () const
Protected Member Functions
void intersect () const
intersection of cap and floor price surfaces at given strikes
void calculateYoYTermStructure () const
mess of making it, i.e. create instruments from quotes and bootstrap
Protected Attributes
std::vector< Rate > cStrikesB_
std::vector< Rate > fStrikesB_
Matrix cPriceB_
Matrix fPriceB_
Interpolation2D capPrice_
Interpolation2D floorPrice_
Interpolation2D floorPrice2_
Interpolator2D interpolator2d_
Interpolation atmYoYSwapRateCurve_
Interpolator1D interpolator1d_
Detailed Description
template<class Interpolator2D, class Interpolator1D>
class QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >
Definition at line 146 of file yoycapfloortermpricesurface.hpp.
Constructor & Destructor Documentation
template<class Interpolator2D , class Interpolator1D > QuantLib::InterpolatedYoYCapFloorTermPriceSurface< I2D, I1D >::InterpolatedYoYCapFloorTermPriceSurface (Natural fixingDays, const Period & yyLag, const boost::shared_ptr< YoYInflationIndex > & yii, Rate baseRate, const Handle< YieldTermStructure > & nominal, const DayCounter & dc, const Calendar & cal, const BusinessDayConvention & bdc, const std::vector< Rate > & cStrikes, const std::vector< Rate > & fStrikes, const std::vector< Period > & cfMaturities, const Matrix & cPrice, const Matrix & fPrice, const Interpolator2D & interpolator2d = Interpolator2D(), const Interpolator1D & interpolator1d = Interpolator1D())
Definition at line 241 of file yoycapfloortermpricesurface.hpp.
References QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::performCalculations().
    : YoYCapFloorTermPriceSurface(fixingDays, yyLag, yii,
                                  baseRate, nominal, dc, cal, bdc,
                                  cStrikes, fStrikes, cfMaturities,
                                  cPrice, fPrice),
      interpolator2d_(interpolator2d), interpolator1d_(interpolator1d) {
        performCalculations();
    }
Member Function Documentation
template<class Interpolator2D , class Interpolator1D > virtual Rate QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::atmYoYRate (const Date & d, const Period & obsLag = Period(-1,Days), bool extrapolate = true) const [inline, virtual]
Implements QuantLib::YoYCapFloorTermPriceSurface.
Definition at line 188 of file yoycapfloortermpricesurface.hpp.
References QuantLib::YoYCapFloorTermPriceSurface::yoy_.
{
            // work in terms of maturity-of-instruments
            // so ask for rate with observation lag
            // Third parameter = force linear interpolation of yoy
            return yoy_->yoyRate(d, obsLag, false, extrapolate);
        }
template<class Interpolator2D , class Interpolator1D > virtual std::pair<std::vector<Date>, std::vector<Rate> > QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::atmYoYSwapDateRates () const [inline, virtual]
Implements QuantLib::YoYCapFloorTermPriceSurface.
Definition at line 178 of file yoycapfloortermpricesurface.hpp.
References QuantLib::YoYCapFloorTermPriceSurface::atmYoYSwapDateRates_.
{ return atmYoYSwapDateRates_; }
template<class Interpolator2D , class Interpolator1D > virtual Rate QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::atmYoYSwapRate (const Date & d, bool extrapolate = true) const [inline, virtual]
Implements QuantLib::YoYCapFloorTermPriceSurface.
Definition at line 184 of file yoycapfloortermpricesurface.hpp.
References QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::atmYoYSwapRateCurve_, and QuantLib::TermStructure::timeFromReference().
Referenced by QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::calculateYoYTermStructure(), and QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::price().
{
            return atmYoYSwapRateCurve_(timeFromReference(d),extrapolate);
        }
template<class Interpolator2D , class Interpolator1D > virtual std::pair<std::vector<Time>, std::vector<Rate> > QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::atmYoYSwapTimeRates () const [inline, virtual]
atm yoy swaps from put-call parity on cap/floor data
uses interpolation (on surface price data), yearly maturities.
Implements QuantLib::YoYCapFloorTermPriceSurface.
Definition at line 176 of file yoycapfloortermpricesurface.hpp.
References QuantLib::YoYCapFloorTermPriceSurface::atmYoYSwapTimeRates_.
{ return atmYoYSwapTimeRates_; }
template<class Interpolator2D , class Interpolator1D > virtual Date QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::baseDate () const [inline, virtual]
minimum (base) date
Important in inflation since it starts before nominal reference date. Changes depending whether index is interpolated or not. When interpolated the base date is just observation lag before nominal. When not interpolated it is the beginning of the relevant period (hence it is easy to create interpolated fixings from a not-interpolated curve because interpolation, usually, of fixings is forward looking).
Implements QuantLib::InflationTermStructure.
Definition at line 169 of file yoycapfloortermpricesurface.hpp.
References QuantLib::YoYCapFloorTermPriceSurface::yoy_.
{return yoy_->baseDate();}
template<class I2D , class I1D > void QuantLib::InterpolatedYoYCapFloorTermPriceSurface< I2D, I1D >::calculateYoYTermStructure () const [protected]
mess of making it, i.e. create instruments from quotes and bootstrap
Definition at line 507 of file yoycapfloortermpricesurface.hpp.
References QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::atmYoYSwapRate(), QuantLib::YoYCapFloorTermPriceSurface::bdc_, QuantLib::TermStructure::calendar(), QuantLib::YoYCapFloorTermPriceSurface::cfMaturities_, QuantLib::TermStructure::dayCounter(), QuantLib::InflationTermStructure::frequency(), QuantLib::InflationTermStructure::nominalTermStructure(), QuantLib::InflationTermStructure::observationLag(), QL_REQUIRE, QuantLib::TermStructure::referenceDate(), QuantLib::TermStructure::timeFromReference(), QuantLib::Years, QuantLib::YoYCapFloorTermPriceSurface::yoy_, QuantLib::YoYCapFloorTermPriceSurface::yoyIndex(), and QuantLib::YoYCapFloorTermPriceSurface::yoyOptionDateFromTenor().
{
        // which yoy-swap points to use in building the yoy-fwd curve?
        // for now pick every year
        Size nYears = (Size)(0.5+timeFromReference(referenceDate()+cfMaturities_.back()));
        std::vector<boost::shared_ptr<BootstrapHelper<YoYInflationTermStructure> > > YYhelpers;
        for (Size i=1; i<=nYears; i++) {
            Date maturity = nominalTermStructure()->referenceDate() + Period(i,Years);
            Handle<Quote> quote(boost::shared_ptr<Quote>(
                               new SimpleQuote( atmYoYSwapRate( maturity ) )));
            boost::shared_ptr<BootstrapHelper<YoYInflationTermStructure> >
            anInstrument(
                new YearOnYearInflationSwapHelper(
                                quote, observationLag(), maturity,
                                calendar(), bdc_, dayCounter(),
                                yoyIndex()));
            YYhelpers.push_back (anInstrument);
        }
        // usually this base rate is known
        // however for the data to be self-consistent
        // we pick this as the end of the curve
        Rate baseYoYRate = atmYoYSwapRate( referenceDate() );
        Handle<YieldTermStructure> nominalH( nominalTermStructure() );
        // Linear is OK because we have every year
        boost::shared_ptr<PiecewiseYoYInflationCurve<Linear> >   pYITS(
              new PiecewiseYoYInflationCurve<Linear>(
                      nominalTermStructure()->referenceDate(),
                      calendar(), dayCounter(), observationLag(), yoyIndex()->frequency(),
                      yoyIndex()->interpolated(), baseYoYRate,
                      nominalH, YYhelpers));
        pYITS->recalculate();
        yoy_ = pYITS;   // store
        // check that helpers are repriced
        const Real eps = 1e-5;
        for (Size i=0; i<YYhelpers.size(); i++) {
            Rate original = atmYoYSwapRate( yoyOptionDateFromTenor(Period(i+1,Years)) );
            QL_REQUIRE(fabs(YYhelpers[i]->impliedQuote() - original) <eps,
                       "could not reprice helper "<< i
                       << ", data " << original
                       << ", implied quote " << YYhelpers[i]->impliedQuote()
            );
        }
    }
template<class I2D , class I1D > Rate QuantLib::InterpolatedYoYCapFloorTermPriceSurface< I2D, I1D >::capPrice (const Date & d, const Rate k) const [virtual]
Implements QuantLib::YoYCapFloorTermPriceSurface.
Definition at line 307 of file yoycapfloortermpricesurface.hpp.
References QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::capPrice_, anonymous_namespace{quantlibbenchmark.cpp}::t, and QuantLib::TermStructure::timeFromReference().
Referenced by QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::price().
{
        Time t = timeFromReference(d);
        return capPrice_(t,k);
    }
template<class Interpolator2D , class Interpolator1D > virtual Natural QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::fixingDays () const [inline, virtual]
Reimplemented from QuantLib::YoYCapFloorTermPriceSurface.
Definition at line 171 of file yoycapfloortermpricesurface.hpp.
References QuantLib::YoYCapFloorTermPriceSurface::fixingDays_.
{return fixingDays_;}
template<class I2D , class I1D > Rate QuantLib::InterpolatedYoYCapFloorTermPriceSurface< I2D, I1D >::floorPrice (const Date & d, const Rate k) const [virtual]
Implements QuantLib::YoYCapFloorTermPriceSurface.
Definition at line 315 of file yoycapfloortermpricesurface.hpp.
References QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::floorPrice_, anonymous_namespace{quantlibbenchmark.cpp}::t, and QuantLib::TermStructure::timeFromReference().
Referenced by QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::price().
{
        Time t = timeFromReference(d);
        return floorPrice_(t,k);
    }
template<class I2D , class I1D > void QuantLib::InterpolatedYoYCapFloorTermPriceSurface< I2D, I1D >::intersect () const [protected]
intersection of cap and floor price surfaces at given strikes
Definition at line 332 of file yoycapfloortermpricesurface.hpp.
References QuantLib::YoYCapFloorTermPriceSurface::atmYoYSwapDateRates_, QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::atmYoYSwapRateCurve_, QuantLib::YoYCapFloorTermPriceSurface::atmYoYSwapTimeRates_, QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::capPrice_, QuantLib::YoYCapFloorTermPriceSurface::cfMaturities_, QuantLib::YoYCapFloorTermPriceSurface::cfMaturityTimes_, QuantLib::YoYCapFloorTermPriceSurface::cPrice_, QuantLib::YoYCapFloorTermPriceSurface::cStrikes_, QuantLib::Extrapolator::enableExtrapolation(), QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::floorPrice_, QuantLib::YoYCapFloorTermPriceSurface::fPrice_, QuantLib::YoYCapFloorTermPriceSurface::fStrikes_, QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::interpolator1d_, QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::interpolator2d_, QuantLib::InflationTermStructure::nominalTermStructure(), QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::price(), QL_FAIL, QuantLib::TermStructure::referenceDate(), QuantLib::Solver1D< Impl >::solve(), anonymous_namespace{quantlibbenchmark.cpp}::t, QuantLib::TermStructure::timeFromReference(), and QuantLib::YoYCapFloorTermPriceSurface::yoyOptionDateFromTenor().
                      {
        // TODO: define the constants outside the code
        const Real maxSearchRange = 0.0201;
        const Real maxExtrapolationMaturity = 5.01;
        const Real searchStep = 0.0050;
        const Real intrinsicValueAddOn = 0.001;
        cfMaturityTimes_.clear();
        for (Size i=0; i<cfMaturities_.size();i++) {
            cfMaturityTimes_.push_back(timeFromReference(
                    yoyOptionDateFromTenor(cfMaturities_[i])));
        }
        capPrice_ = interpolator2d_.interpolate(
                            cfMaturityTimes_.begin(),cfMaturityTimes_.end(),
                            cStrikes_.begin(), cStrikes_.end(),
                            cPrice_
                            );
        capPrice_.enableExtrapolation();
        floorPrice_ = interpolator2d_.interpolate(
                            cfMaturityTimes_.begin(),cfMaturityTimes_.end(),
                            fStrikes_.begin(), fStrikes_.end(),
                            fPrice_
                            );
        floorPrice_.enableExtrapolation();
        atmYoYSwapDateRates_.first.clear();
        atmYoYSwapDateRates_.second.clear();
        atmYoYSwapTimeRates_.first.clear();
        atmYoYSwapTimeRates_.second.clear();
        Brent solver;
        Real solverTolerance_ = 1e-7;
        Real lo,hi,guess;
        std::vector<Real> minSwapRateIntersection(cfMaturityTimes_.size());
        std::vector<Real> maxSwapRateIntersection(cfMaturityTimes_.size());
        std::vector<Time> tmpSwapMaturities;
        std::vector<Rate> tmpSwapRates;
        for (Size i = 0; i < cfMaturities_.size(); i++) {
            Time t = cfMaturityTimes_[i];
            // determine the sum of discount factors
            Size numYears = (Size)(t + 0.5);
            Real sumDiscount = 0.0;
            for (Size j=0; j<numYears; ++j)
                sumDiscount += nominalTermStructure()->discount(j + 1.0);
            // determine the minimum value of the ATM swap point
            Real tmpMinSwapRateIntersection = -1.e10;
            Real tmpMaxSwapRateIntersection = 1.e10;
            for (Size j=0; j<fStrikes_.size(); ++j) {
                Real price = floorPrice_(t,fStrikes_[j]);
                Real minSwapRate = fStrikes_[j] - price / (sumDiscount * 10000);
                if (minSwapRate > tmpMinSwapRateIntersection)
                    tmpMinSwapRateIntersection = minSwapRate;
            }
            for (Size j=0; j<cStrikes_.size(); ++j) {
                Real price = capPrice_(t,cStrikes_[j]);
                Real maxSwapRate = cStrikes_[j] + price / (sumDiscount * 10000);
                if (maxSwapRate < tmpMaxSwapRateIntersection)
                    tmpMaxSwapRateIntersection = maxSwapRate;
            }
            maxSwapRateIntersection[i] = tmpMaxSwapRateIntersection;
            minSwapRateIntersection[i] = tmpMinSwapRateIntersection;
            // find the interval where the intersection lies
            bool trialsExceeded = false;
            int numTrials = (int)(maxSearchRange / searchStep);
            if ( floorPrice_(t,fStrikes_.back()) > capPrice_(t,fStrikes_.back()) ) {
                int counter = 1;
                bool stop = false;
                Real strike = 0.0;
                while (stop == false) {
                    strike = fStrikes_.back() - counter * searchStep;
                    if (floorPrice_(t, strike) < capPrice_(t, strike))
                        stop = true;
                    counter++;
                    if (counter == numTrials + 1) {
                        if (stop == false) {
                            stop = true;
                            trialsExceeded = true;
                        }
                    }
                }
                lo = strike;
                hi = strike + searchStep;
            } else {
                int counter = 1;
                bool stop = false;
                Real strike = 0.0;
                while (stop == false) {
                    strike = fStrikes_.back() + counter * searchStep;
                    if (floorPrice_(t, strike) > capPrice_(t, strike))
                        stop = true;
                    counter++;
                    if (counter == numTrials + 1) {
                        if (stop == false) {
                            stop = true;
                            trialsExceeded = true;
                        }
                    }
                }
                lo = strike - searchStep;
                hi = strike;
            }
            guess = (hi+lo)/2.0;
            Rate kI = -999.999;
            if (trialsExceeded == false) {
                try{
                    kI = solver.solve(  ObjectiveFunction(t, capPrice_, floorPrice_), solverTolerance_, guess, lo, hi );
                } catch( std::exception &e) {
                    QL_FAIL("cap/floor intersection finding failed at t = " << t << ", error msg: "<< e.what());
                }
                // error message if kI is economically nonsensical (only if t is large)
                if (kI <= minSwapRateIntersection[i]) {
                    if (t > maxExtrapolationMaturity)
                        QL_FAIL("cap/floor intersection finding failed at t = " << t <<
                                ", error msg: intersection value is below the arbitrage free lower bound "
                                << minSwapRateIntersection[i]);
                }
                else
                {
                    tmpSwapMaturities.push_back(t);
                    tmpSwapRates.push_back(kI);
                }
            }
            else
            {
                // error message if t is too large
                if (t > maxExtrapolationMaturity)
                    QL_FAIL("cap/floor intersection finding failed at t = " << t <<
                            ", error msg: no interection found inside the admissible range");
            }
        }
        // extrapolation of swap rates if necessary
        //Polynomial2D tmpInterpol;
        //Interpolation interpol = tmpInterpol.interpolate(tmpSwapMaturities.begin(), tmpSwapMaturities.end(), tmpSwapRates.begin());
        //interpol.enableExtrapolation();
        Time startMaturity = tmpSwapMaturities.front();
        int counter = 0;
        for (Size i=0; i<cfMaturities_.size(); ++i) {
            if (cfMaturityTimes_[i] < startMaturity) {
                atmYoYSwapDateRates_.first.push_back(referenceDate()+cfMaturities_[i]);
                atmYoYSwapTimeRates_.first.push_back(timeFromReference(referenceDate()+cfMaturities_[i]));
                // atmYoYSwapRates_->second.push_back(interpol((*cfMaturities_)[i]));
                // Heuristic: overwrite the the swap rate with a value that guarantees that the
                // intrinsic value of all options is lower than the price
                Real newSwapRate = minSwapRateIntersection[i] + intrinsicValueAddOn;
                if (newSwapRate > maxSwapRateIntersection[i])
                    newSwapRate = 0.5 * (minSwapRateIntersection[i] + maxSwapRateIntersection[i]);
                atmYoYSwapTimeRates_.second.push_back(newSwapRate);
                atmYoYSwapDateRates_.second.push_back(newSwapRate);
            } else {
                atmYoYSwapTimeRates_.first.push_back(tmpSwapMaturities[counter]);
                atmYoYSwapTimeRates_.second.push_back(tmpSwapRates[counter]);
                atmYoYSwapDateRates_.first.push_back(
                    yoyOptionDateFromTenor(cfMaturities_.at(counter)));
                atmYoYSwapDateRates_.second.push_back(tmpSwapRates[counter]);
                counter++;
            }
        }
        // create the swap curve using the factory
        atmYoYSwapRateCurve_ =
            interpolator1d_.interpolate(atmYoYSwapTimeRates_.first.begin(),
                                        atmYoYSwapTimeRates_.first.end(),
                                        atmYoYSwapTimeRates_.second.begin());
    }
template<class Interpolator2D , class Interpolator1D > virtual Date QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::maxDate () const [inline, virtual]
inflation term structure interface
Implements QuantLib::TermStructure.
Definition at line 168 of file yoycapfloortermpricesurface.hpp.
References QuantLib::YoYCapFloorTermPriceSurface::yoy_.
{return yoy_->maxDate();}
template<class I2D , class I1D > void QuantLib::InterpolatedYoYCapFloorTermPriceSurface< I2D, I1D >::performCalculations () const
Definition at line 276 of file yoycapfloortermpricesurface.hpp.
Referenced by QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::InterpolatedYoYCapFloorTermPriceSurface().
{
        // calculate all the useful things
        // ... first the intersection of the cap and floor surfs
        intersect();
        // ... then the yoy term structure, which requires instruments
        // and a bootstrap
        calculateYoYTermStructure();
    }
template<class I2D , class I1D > Rate QuantLib::InterpolatedYoYCapFloorTermPriceSurface< I2D, I1D >::price (const Date & d, const Rate k) const [virtual]
Implements QuantLib::YoYCapFloorTermPriceSurface.
Definition at line 299 of file yoycapfloortermpricesurface.hpp.
References QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::atmYoYSwapRate(), QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::capPrice(), and QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::floorPrice().
Referenced by QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::intersect().
{
        Rate atm = atmYoYSwapRate(d);
        return k > atm ? capPrice(d,k): floorPrice(d,k);
    }
template<class I2D , class I1D > void QuantLib::InterpolatedYoYCapFloorTermPriceSurface< I2D, I1D >::update () [virtual]
This method must be implemented in derived classes. An instance of Observer does not call this method directly: instead, it will be called by the observables the instance registered with when they need to notify any changes.
Reimplemented from QuantLib::TermStructure.
Definition at line 269 of file yoycapfloortermpricesurface.hpp.
             {
        notifyObservers();
    }
template<class Interpolator2D , class Interpolator1D > virtual boost::shared_ptr<YoYInflationTermStructure> QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::YoYTS () const [inline, virtual]
derived from yoy swap rates
Implements QuantLib::YoYCapFloorTermPriceSurface.
Definition at line 180 of file yoycapfloortermpricesurface.hpp.
References QuantLib::YoYCapFloorTermPriceSurface::yoy_.
{ return yoy_; }
Member Data Documentation
template<class Interpolator2D , class Interpolator1D > Interpolation QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::atmYoYSwapRateCurve_ [mutable, protected]
Definition at line 229 of file yoycapfloortermpricesurface.hpp.
Referenced by QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::atmYoYSwapRate(), and QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::intersect().
template<class Interpolator2D , class Interpolator1D > Interpolation2D QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::capPrice_ [mutable, protected]
Definition at line 226 of file yoycapfloortermpricesurface.hpp.
Referenced by QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::capPrice(), and QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::intersect().
template<class Interpolator2D , class Interpolator1D > Matrix QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::cPriceB_ [mutable, protected]
Definition at line 224 of file yoycapfloortermpricesurface.hpp.
template<class Interpolator2D , class Interpolator1D > std::vector<Rate> QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::cStrikesB_ [mutable, protected]
Definition at line 222 of file yoycapfloortermpricesurface.hpp.
template<class Interpolator2D , class Interpolator1D > Interpolation2D QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::floorPrice2_ [mutable, protected]
Definition at line 227 of file yoycapfloortermpricesurface.hpp.
template<class Interpolator2D , class Interpolator1D > Interpolation2D QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::floorPrice_ [mutable, protected]
Definition at line 226 of file yoycapfloortermpricesurface.hpp.
Referenced by QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::floorPrice(), and QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::intersect().
template<class Interpolator2D , class Interpolator1D > Matrix QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::fPriceB_ [mutable, protected]
Definition at line 225 of file yoycapfloortermpricesurface.hpp.
template<class Interpolator2D , class Interpolator1D > std::vector<Rate> QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::fStrikesB_ [mutable, protected]
Definition at line 223 of file yoycapfloortermpricesurface.hpp.
template<class Interpolator2D , class Interpolator1D > Interpolator1D QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::interpolator1d_ [mutable, protected]
Definition at line 230 of file yoycapfloortermpricesurface.hpp.
Referenced by QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::intersect().
template<class Interpolator2D , class Interpolator1D > Interpolator2D QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::interpolator2d_ [mutable, protected]
Definition at line 228 of file yoycapfloortermpricesurface.hpp.
Referenced by QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::intersect().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/inflation/yoycapfloortermpricesurface.hpp