QuantLib: QuantLib::ExtendedBlackVarianceSurface Class Reference
QuantLib::ExtendedBlackVarianceSurface Class Reference
Black volatility surface modelled as variance surface.
#include <extendedblackvariancesurface.hpp>
Public Types
enum Extrapolation { ConstantExtrapolation, InterpolatorDefaultExtrapolation }
Public Member Functions
ExtendedBlackVarianceSurface (const Date &referenceDate, const Calendar &calendar, const std::vector< Date > &dates, const std::vector< Real > &strikes, const std::vector< Handle< Quote > > &volatilities, const DayCounter &dayCounter, Extrapolation lowerExtrapolation=InterpolatorDefaultExtrapolation, Extrapolation upperExtrapolation=InterpolatorDefaultExtrapolation)
DayCounter dayCounter () const
the day counter used for date/time conversion
Date maxDate () const
the latest date for which the curve can return values
Real minStrike () const
the minimum strike for which the term structure can return vols
Real maxStrike () const
the maximum strike for which the term structure can return vols
template<class Interpolator >
void setInterpolation (const Interpolator &i=Interpolator())
void accept (AcyclicVisitor &)
void update ()
Private Member Functions
Real blackVarianceImpl (Time t, Real strike) const
Black variance calculation.
void setVariances ()
Private Attributes
DayCounter dayCounter_
Date maxDate_
const std::vector< Handle
< Quote > > & volatilities_
std::vector< Real > strikes_
std::vector< Time > times_
Matrix variances_
Interpolation2D varianceSurface_
Extrapolation lowerExtrapolation_
Extrapolation upperExtrapolation_
Detailed Description
Black volatility surface modelled as variance surface.
This class is similar to BlackVarianceSurface, but extends it to use quotes for the input volatilities.
Definition at line 39 of file extendedblackvariancesurface.hpp.
Member Enumeration Documentation
enum QuantLib::ExtendedBlackVarianceSurface::Extrapolation
Enumerator:
ConstantExtrapolation
InterpolatorDefaultExtrapolation
Definition at line 41 of file extendedblackvariancesurface.hpp.
                           { ConstantExtrapolation,
                             InterpolatorDefaultExtrapolation };
Constructor & Destructor Documentation
QuantLib::ExtendedBlackVarianceSurface::ExtendedBlackVarianceSurface (const Date & referenceDate, const Calendar & calendar, const std::vector< Date > & dates, const std::vector< Real > & strikes, const std::vector< Handle< Quote > > & volatilities, const DayCounter & dayCounter, ExtendedBlackVarianceSurface::Extrapolation lowerEx = InterpolatorDefaultExtrapolation, ExtendedBlackVarianceSurface::Extrapolation upperEx = InterpolatorDefaultExtrapolation)
Definition at line 25 of file extendedblackvariancesurface.cpp.
References QL_REQUIRE, QuantLib::Observer::registerWith(), setVariances(), strikes_, QuantLib::TermStructure::timeFromReference(), times_, variances_, and volatilities_.
    : BlackVarianceTermStructure(referenceDate, calendar),
      dayCounter_(dayCounter), maxDate_(dates.back()),
      volatilities_(volatilities), strikes_(strikes),
      lowerExtrapolation_(lowerEx), upperExtrapolation_(upperEx) {
        QL_REQUIRE(dates.size()*strikes_.size()==volatilities_.size(),
                   "size mismatch between date vector and vol matrix columns "
                   "and/or between money-strike vector and vol matrix rows");
        QL_REQUIRE(dates[0] > referenceDate,
                   "cannot have dates_[0] <= referenceDate_");
        times_ = std::vector<Time>(dates.size()+1);
        times_[0] = 0.0;
        for (Size j=1; j<=dates.size(); j++) {
            times_[j] = timeFromReference(dates[j-1]);
            QL_REQUIRE(times_[j]>times_[j-1],
                       "dates must be sorted unique");
        }
        variances_ = Matrix(strikes_.size(), dates.size()+1);
        setVariances();
        setInterpolation<Bilinear>();
        for (Size j = 0; j < volatilities_.size(); j++)
            registerWith(volatilities_[j]);
    }
Member Function Documentation
void QuantLib::ExtendedBlackVarianceSurface::accept (AcyclicVisitor & v) [inline, virtual]
Reimplemented from QuantLib::BlackVarianceTermStructure.
Definition at line 82 of file extendedblackvariancesurface.hpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Visitor< T >::visit().
{
        Visitor<ExtendedBlackVarianceSurface>* v1 =
            dynamic_cast<Visitor<ExtendedBlackVarianceSurface>*>(&v);
        if (v1 != 0)
            v1->visit(*this);
        else
            BlackVarianceTermStructure::accept(v);
    }
Real QuantLib::ExtendedBlackVarianceSurface::blackVarianceImpl (Time t, Real strike) const [private, virtual]
Black variance calculation.
Implements QuantLib::BlackVolTermStructure.
Definition at line 87 of file extendedblackvariancesurface.cpp.
References ConstantExtrapolation, lowerExtrapolation_, strikes_, times_, upperExtrapolation_, and varianceSurface_.
{
        if (t==0.0) return 0.0;
        // enforce constant extrapolation when required
        if (strike < strikes_.front()
            && lowerExtrapolation_ == ConstantExtrapolation)
            strike = strikes_.front();
        if (strike > strikes_.back()
            && upperExtrapolation_ == ConstantExtrapolation)
            strike = strikes_.back();
        if (t<=times_.back())
            return varianceSurface_(t, strike, true);
        else // t>times_.back() || extrapolate
            return varianceSurface_(times_.back(), strike, true) *
                t/times_.back();
    }
DayCounter QuantLib::ExtendedBlackVarianceSurface::dayCounter () const [inline, virtual]
the day counter used for date/time conversion
Reimplemented from QuantLib::TermStructure.
Definition at line 54 of file extendedblackvariancesurface.hpp.
References dayCounter_.
{ return dayCounter_; }
Date QuantLib::ExtendedBlackVarianceSurface::maxDate () const [inline, virtual]
the latest date for which the curve can return values
Implements QuantLib::TermStructure.
Definition at line 55 of file extendedblackvariancesurface.hpp.
References maxDate_.
{ return maxDate_; }
Real QuantLib::ExtendedBlackVarianceSurface::maxStrike () const [inline, virtual]
the maximum strike for which the term structure can return vols
Implements QuantLib::VolatilityTermStructure.
Definition at line 57 of file extendedblackvariancesurface.hpp.
References strikes_.
{ return strikes_.back(); }
Real QuantLib::ExtendedBlackVarianceSurface::minStrike () const [inline, virtual]
the minimum strike for which the term structure can return vols
Implements QuantLib::VolatilityTermStructure.
Definition at line 56 of file extendedblackvariancesurface.hpp.
References strikes_.
{ return strikes_.front(); }
template<class Interpolator > void QuantLib::ExtendedBlackVarianceSurface::setInterpolation (const Interpolator & i = Interpolator()) [inline]
Definition at line 59 of file extendedblackvariancesurface.hpp.
References QuantLib::Observable::notifyObservers(), strikes_, times_, QuantLib::Interpolation2D::update(), variances_, and varianceSurface_.
{
            varianceSurface_ =
                i.interpolate(times_.begin(), times_.end(),
                              strikes_.begin(), strikes_.end(),
                              variances_);
            varianceSurface_.update();
            notifyObservers();
        }
void QuantLib::ExtendedBlackVarianceSurface::setVariances () [private]
Definition at line 66 of file extendedblackvariancesurface.cpp.
References QL_REQUIRE, anonymous_namespace{distributions.cpp}::sigma, strikes_, times_, variances_, and volatilities_.
Referenced by ExtendedBlackVarianceSurface(), and update().
{
        for (Size i=0; i<times_.size()+1; i++) {
            variances_[0][i] = 0.0;
        }
        for (Size j=1; j<=times_.size(); j++) {
            for (Size i=0; i<strikes_.size(); i++) {
                Volatility sigma = volatilities_[i*times_.size()+j-1]->value();
                variances_[i][j] = times_[j] * sigma * sigma;
                QL_REQUIRE(variances_[i][j]>=variances_[i][j-1],
                           "variance must be non-decreasing");
            }
        }
    }
void QuantLib::ExtendedBlackVarianceSurface::update () [virtual]
This method must be implemented in derived classes. An instance of Observer does not call this method directly: instead, it will be called by the observables the instance registered with when they need to notify any changes.
Reimplemented from QuantLib::TermStructure.
Definition at line 81 of file extendedblackvariancesurface.cpp.
References QuantLib::Observable::notifyObservers(), setVariances(), QuantLib::Interpolation2D::update(), and varianceSurface_.
{
        setVariances();
        varianceSurface_.update();
        notifyObservers();
    }
Member Data Documentation
DayCounter QuantLib::ExtendedBlackVarianceSurface::dayCounter_ [private]
Reimplemented from QuantLib::TermStructure.
Definition at line 72 of file extendedblackvariancesurface.hpp.
Referenced by dayCounter().
Extrapolation QuantLib::ExtendedBlackVarianceSurface::lowerExtrapolation_ [private]
Definition at line 79 of file extendedblackvariancesurface.hpp.
Referenced by blackVarianceImpl().
Date QuantLib::ExtendedBlackVarianceSurface::maxDate_ [private]
Definition at line 73 of file extendedblackvariancesurface.hpp.
Referenced by maxDate().
std::vector<Real> QuantLib::ExtendedBlackVarianceSurface::strikes_ [private]
Definition at line 75 of file extendedblackvariancesurface.hpp.
Referenced by blackVarianceImpl(), ExtendedBlackVarianceSurface(), maxStrike(), minStrike(), setInterpolation(), and setVariances().
std::vector<Time> QuantLib::ExtendedBlackVarianceSurface::times_ [private]
Definition at line 76 of file extendedblackvariancesurface.hpp.
Referenced by blackVarianceImpl(), ExtendedBlackVarianceSurface(), setInterpolation(), and setVariances().
Extrapolation QuantLib::ExtendedBlackVarianceSurface::upperExtrapolation_ [private]
Definition at line 79 of file extendedblackvariancesurface.hpp.
Referenced by blackVarianceImpl().
Matrix QuantLib::ExtendedBlackVarianceSurface::variances_ [private]
Definition at line 77 of file extendedblackvariancesurface.hpp.
Referenced by ExtendedBlackVarianceSurface(), setInterpolation(), and setVariances().
Interpolation2D QuantLib::ExtendedBlackVarianceSurface::varianceSurface_ [private]
Definition at line 78 of file extendedblackvariancesurface.hpp.
Referenced by blackVarianceImpl(), setInterpolation(), and update().
const std::vector<Handle<Quote> >& QuantLib::ExtendedBlackVarianceSurface::volatilities_ [private]
Definition at line 74 of file extendedblackvariancesurface.hpp.
Referenced by ExtendedBlackVarianceSurface(), and setVariances().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/volatility/extendedblackvariancesurface.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/volatility/extendedblackvariancesurface.cpp