QuantLib: QuantLib::FdmG2Solver Class Reference
QuantLib::FdmG2Solver Class Reference
#include <fdmg2solver.hpp>
Public Member Functions
FdmG2Solver (const Handle< G2 > &model, const FdmSolverDesc &solverDesc, const FdmSchemeDesc &schemeDesc=FdmSchemeDesc::Hundsdorfer())
Real valueAt (Real x, Real y) const
Protected Member Functions
void performCalculations () const
Private Attributes
const Handle< G2 > model_
const FdmSolverDesc solverDesc_
const FdmSchemeDesc schemeDesc_
boost::shared_ptr< Fdm2DimSolver > solver_
Detailed Description
Definition at line 36 of file fdmg2solver.hpp.
Constructor & Destructor Documentation
QuantLib::FdmG2Solver::FdmG2Solver (const Handle< G2 > & model, const FdmSolverDesc & solverDesc, const FdmSchemeDesc & schemeDesc = FdmSchemeDesc::Hundsdorfer())
Definition at line 31 of file fdmg2solver.cpp.
References model_, and QuantLib::Observer::registerWith().
    : model_(model),
      solverDesc_(solverDesc),
      schemeDesc_(schemeDesc) {
        registerWith(model_);
    }
Member Function Documentation
void QuantLib::FdmG2Solver::performCalculations () const [protected, virtual]
This method must implement any calculations which must be (re)done in order to calculate the desired results.
Implements QuantLib::LazyObject.
Definition at line 42 of file fdmg2solver.cpp.
References QuantLib::Handle< T >::currentLink(), QuantLib::FdmSolverDesc::mesher, model_, schemeDesc_, solver_, and solverDesc_.
{
        const boost::shared_ptr<FdmG2Op> op(
            new FdmG2Op(solverDesc_.mesher, model_.currentLink(), 0, 1));
        solver_ = boost::shared_ptr<Fdm2DimSolver>(
            new Fdm2DimSolver(solverDesc_, schemeDesc_, op));
    }
Real QuantLib::FdmG2Solver::valueAt (Real x, Real y) const
Definition at line 50 of file fdmg2solver.cpp.
References QuantLib::LazyObject::calculate(), and solver_.
{
        calculate();
        return solver_->interpolateAt(x, y);
    }
Member Data Documentation
const Handle<G2> QuantLib::FdmG2Solver::model_ [private]
Definition at line 49 of file fdmg2solver.hpp.
Referenced by FdmG2Solver(), and performCalculations().
const FdmSchemeDesc QuantLib::FdmG2Solver::schemeDesc_ [private]
Definition at line 51 of file fdmg2solver.hpp.
Referenced by performCalculations().
boost::shared_ptr<Fdm2DimSolver> QuantLib::FdmG2Solver::solver_ [mutable, private]
Definition at line 53 of file fdmg2solver.hpp.
Referenced by performCalculations(), and valueAt().
const FdmSolverDesc QuantLib::FdmG2Solver::solverDesc_ [private]
Definition at line 50 of file fdmg2solver.hpp.
Referenced by performCalculations().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/solvers/fdmg2solver.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/solvers/fdmg2solver.cpp