QuantLib: QuantLib::EndCriteria Class Reference
QuantLib::EndCriteria Class Reference
Criteria to end optimization process:
#include <endcriteria.hpp>
Public Types
enum Type {
None, MaxIterations, StationaryPoint, StationaryFunctionValue,
StationaryFunctionAccuracy, ZeroGradientNorm, Unknown
}
Public Member Functions
EndCriteria (Size maxIterations, Size maxStationaryStateIterations, Real rootEpsilon, Real functionEpsilon, Real gradientNormEpsilon)
Initialization constructor.
Size maxIterations () const
Size maxStationaryStateIterations () const
Real rootEpsilon () const
Real functionEpsilon () const
Real gradientNormEpsilon () const
bool operator() (const Size iteration, Size &statState, const bool positiveOptimization, const Real fold, const Real normgold, const Real fnew, const Real normgnew, EndCriteria::Type &ecType) const
bool checkMaxIterations (const Size iteration, EndCriteria::Type &ecType) const
bool checkStationaryPoint (const Real xOld, const Real xNew, Size &statStateIterations, EndCriteria::Type &ecType) const
bool checkStationaryFunctionValue (const Real fxOld, const Real fxNew, Size &statStateIterations, EndCriteria::Type &ecType) const
bool checkStationaryFunctionAccuracy (const Real f, const bool positiveOptimization, EndCriteria::Type &ecType) const
bool checkZeroGradientNorm (const Real gNorm, EndCriteria::Type &ecType) const
Protected Attributes
Size maxIterations_
Maximum number of iterations.
Size maxStationaryStateIterations_
Maximun number of iterations in stationary state.
Real rootEpsilon_
root, function and gradient epsilons
Real functionEpsilon_
Real gradientNormEpsilon_
Detailed Description
Criteria to end optimization process:
maximum number of iterations AND minimum number of iterations around stationary point
x (independent variable) stationary point
y=f(x) (dependent variable) stationary point
stationary gradient
Definition at line 40 of file endcriteria.hpp.
Member Enumeration Documentation
enum QuantLib::EndCriteria::Type
Enumerator:
None
MaxIterations
StationaryPoint
StationaryFunctionValue
StationaryFunctionAccuracy
ZeroGradientNorm
Unknown
Definition at line 42 of file endcriteria.hpp.
                  {None,
                   MaxIterations,
                   StationaryPoint,
                   StationaryFunctionValue,
                   StationaryFunctionAccuracy,
                   ZeroGradientNorm,
                   Unknown};
Constructor & Destructor Documentation
QuantLib::EndCriteria::EndCriteria (Size maxIterations, Size maxStationaryStateIterations, Real rootEpsilon, Real functionEpsilon, Real gradientNormEpsilon)
Initialization constructor.
Definition at line 28 of file endcriteria.cpp.
References functionEpsilon_, gradientNormEpsilon_, maxIterations_, maxStationaryStateIterations_, and QL_REQUIRE.
    : maxIterations_(maxIterations),
      maxStationaryStateIterations_(maxStationaryStateIterations),
      rootEpsilon_(rootEpsilon),
      functionEpsilon_(functionEpsilon),
      gradientNormEpsilon_(gradientNormEpsilon) {
        if (maxStationaryStateIterations_ == Null<Size>())
            maxStationaryStateIterations_ = std::min(static_cast<Size>(maxIterations/2),
                                                     static_cast<Size>(100));
        QL_REQUIRE(maxStationaryStateIterations_>1,
                   "maxStationaryStateIterations_ (" <<
                   maxStationaryStateIterations_ <<
                   ") must be greater than one");
        QL_REQUIRE(maxStationaryStateIterations_<maxIterations_,
                   "maxStationaryStateIterations_ (" <<
                   maxStationaryStateIterations_ <<
                   ") must be less than maxIterations_ (" <<
                   maxIterations_ << ")");
        if (gradientNormEpsilon_ == Null<Real>())
            gradientNormEpsilon_ = functionEpsilon_;
    }
Member Function Documentation
bool QuantLib::EndCriteria::checkMaxIterations (const Size iteration, EndCriteria::Type & ecType) const
Test if the number of iteration is below MaxIterations
Definition at line 55 of file endcriteria.cpp.
References MaxIterations, and maxIterations_.
Referenced by QuantLib::LevenbergMarquardt::minimize(), QuantLib::Simplex::minimize(), QuantLib::ArmijoLineSearch::operator()(), and operator()().
{
        if (iteration < maxIterations_)
            return false;
        ecType = MaxIterations;
        return true;
    }
bool QuantLib::EndCriteria::checkStationaryFunctionAccuracy (const Real f, const bool positiveOptimization, EndCriteria::Type & ecType) const
Test if the function value is below functionEpsilon
Definition at line 94 of file endcriteria.cpp.
References functionEpsilon_, and StationaryFunctionAccuracy.
Referenced by operator()().
{
        if (!positiveOptimization)
            return false;
        if (f >= functionEpsilon_)
            return false;
        ecType = StationaryFunctionAccuracy;
        return true;
    }
bool QuantLib::EndCriteria::checkStationaryFunctionValue (const Real fxOld, const Real fxNew, Size & statStateIterations, EndCriteria::Type & ecType) const
Test if the function variation is below functionEpsilon
Definition at line 78 of file endcriteria.cpp.
References functionEpsilon_, maxStationaryStateIterations_, and StationaryFunctionValue.
Referenced by operator()().
{
        if (std::fabs(fxNew-fxOld) >= functionEpsilon_) {
            statStateIterations = 0;
            return false;
        }
        ++statStateIterations;
        if (statStateIterations <= maxStationaryStateIterations_)
            return false;
        ecType = StationaryFunctionValue;
        return true;
    }
bool QuantLib::EndCriteria::checkStationaryPoint (const Real xOld, const Real xNew, Size & statStateIterations, EndCriteria::Type & ecType) const
Test if the root variation is below rootEpsilon
Definition at line 63 of file endcriteria.cpp.
References maxStationaryStateIterations_, rootEpsilon_, and StationaryPoint.
Referenced by QuantLib::Simplex::minimize().
{
        if (std::fabs(xNew-xOld) >= rootEpsilon_) {
            statStateIterations = 0;
            return false;
        }
        ++statStateIterations;
        if (statStateIterations <= maxStationaryStateIterations_)
            return false;
        ecType = StationaryPoint;
        return true;
    }
bool QuantLib::EndCriteria::checkZeroGradientNorm (const Real gNorm, EndCriteria::Type & ecType) const
Test if the gradient norm variation is below gradientNormEpsilon
Test if the gradient norm value is below gradientNormEpsilon
Definition at line 116 of file endcriteria.cpp.
References gradientNormEpsilon_, and ZeroGradientNorm.
Referenced by operator()().
{
        if (gradientNorm >= gradientNormEpsilon_)
            return false;
        ecType = ZeroGradientNorm;
        return true;
    }
Real QuantLib::EndCriteria::functionEpsilon () const
Definition at line 152 of file endcriteria.cpp.
References functionEpsilon_.
Referenced by QuantLib::LevenbergMarquardt::minimize(), QuantLib::LineSearchBasedMethod::minimize(), and OptimizersTest::test().
{
        return functionEpsilon_;
    }
Real QuantLib::EndCriteria::gradientNormEpsilon () const
Definition at line 156 of file endcriteria.cpp.
References gradientNormEpsilon_.
{
        return gradientNormEpsilon_;
    }
Size QuantLib::EndCriteria::maxIterations () const
Definition at line 140 of file endcriteria.cpp.
References maxIterations_.
Referenced by QuantLib::LevenbergMarquardt::minimize().
{
        return maxIterations_;
    }
Size QuantLib::EndCriteria::maxStationaryStateIterations () const
Definition at line 144 of file endcriteria.cpp.
References maxStationaryStateIterations_.
Referenced by QuantLib::LineSearchBasedMethod::minimize(), and QuantLib::Simplex::minimize().
{
        return maxStationaryStateIterations_;
    }
bool QuantLib::EndCriteria::operator() (const Size iteration, Size & statState, const bool positiveOptimization, const Real fold, const Real normgold, const Real fnew, const Real normgnew, EndCriteria::Type & ecType) const
Test if the number of iterations is not too big and if a minimum point is not reached
Definition at line 124 of file endcriteria.cpp.
References checkMaxIterations(), checkStationaryFunctionAccuracy(), checkStationaryFunctionValue(), and checkZeroGradientNorm().
{
        return
            checkMaxIterations(iteration, ecType) ||
            checkStationaryFunctionValue(fold, fnew, statStateIterations, ecType) ||
            checkStationaryFunctionAccuracy(fnew, positiveOptimization, ecType) ||
            checkZeroGradientNorm(normgnew, ecType);
    }
Real QuantLib::EndCriteria::rootEpsilon () const
Definition at line 148 of file endcriteria.cpp.
References rootEpsilon_.
Referenced by QuantLib::Simplex::minimize(), and OptimizersTest::test().
{
        return rootEpsilon_;
    }
Member Data Documentation
Real QuantLib::EndCriteria::functionEpsilon_ [protected]
Definition at line 106 of file endcriteria.hpp.
Referenced by checkStationaryFunctionAccuracy(), checkStationaryFunctionValue(), EndCriteria(), and functionEpsilon().
Real QuantLib::EndCriteria::gradientNormEpsilon_ [protected]
Definition at line 106 of file endcriteria.hpp.
Referenced by checkZeroGradientNorm(), EndCriteria(), and gradientNormEpsilon().
Size QuantLib::EndCriteria::maxIterations_ [protected]
Maximum number of iterations.
Definition at line 102 of file endcriteria.hpp.
Referenced by checkMaxIterations(), EndCriteria(), and maxIterations().
Size QuantLib::EndCriteria::maxStationaryStateIterations_ [mutable, protected]
Maximun number of iterations in stationary state.
Definition at line 104 of file endcriteria.hpp.
Referenced by checkStationaryFunctionValue(), checkStationaryPoint(), EndCriteria(), and maxStationaryStateIterations().
Real QuantLib::EndCriteria::rootEpsilon_ [protected]
root, function and gradient epsilons
Definition at line 106 of file endcriteria.hpp.
Referenced by checkStationaryPoint(), and rootEpsilon().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/optimization/endcriteria.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/math/optimization/endcriteria.cpp