QuantLib: QuantLib::FdmHestonSolver Class Reference
QuantLib::FdmHestonSolver Class Reference
#include <fdmhestonsolver.hpp>
Public Member Functions
FdmHestonSolver (const Handle< HestonProcess > &process, const FdmSolverDesc &solverDesc, const FdmSchemeDesc &schemeDesc=FdmSchemeDesc::Hundsdorfer(), const Handle< FdmQuantoHelper > &quantoHelper=Handle< FdmQuantoHelper >())
Real valueAt (Real s, Real v) const
Real thetaAt (Real s, Real v) const
Real deltaAt (Real s, Real v) const
Real gammaAt (Real s, Real v) const
Real meanVarianceDeltaAt (Real s, Real v) const
Real meanVarianceGammaAt (Real s, Real v) const
Protected Member Functions
void performCalculations () const
Private Attributes
const Handle< HestonProcess > process_
const FdmSolverDesc solverDesc_
const FdmSchemeDesc schemeDesc_
const Handle< FdmQuantoHelper > quantoHelper_
boost::shared_ptr< Fdm2DimSolver > solver_
Detailed Description
Definition at line 40 of file fdmhestonsolver.hpp.
Constructor & Destructor Documentation
QuantLib::FdmHestonSolver::FdmHestonSolver (const Handle< HestonProcess > & process, const FdmSolverDesc & solverDesc, const FdmSchemeDesc & schemeDesc = FdmSchemeDesc::Hundsdorfer(), const Handle< FdmQuantoHelper > & quantoHelper = Handle<FdmQuantoHelper>())
Definition at line 29 of file fdmhestonsolver.cpp.
References process_, quantoHelper_, and QuantLib::Observer::registerWith().
    : process_(process),
      solverDesc_(solverDesc),
      schemeDesc_(schemeDesc),
      quantoHelper_(quantoHelper) {
        registerWith(process_);
        registerWith(quantoHelper_);
    }
Member Function Documentation
Real QuantLib::FdmHestonSolver::deltaAt (Real s, Real v) const
Definition at line 59 of file fdmhestonsolver.cpp.
References QuantLib::LazyObject::calculate(), and solver_.
Referenced by meanVarianceDeltaAt(), and FdmLinearOpTest::testFdmHestonExpress().
{
        calculate();
        return solver_->derivativeX(std::log(s), v)/s;
    }
Real QuantLib::FdmHestonSolver::gammaAt (Real s, Real v) const
Definition at line 64 of file fdmhestonsolver.cpp.
References QuantLib::LazyObject::calculate(), and solver_.
Referenced by meanVarianceGammaAt(), and FdmLinearOpTest::testFdmHestonExpress().
{
        calculate();
        const Real x = std::log(s);
        return (solver_->derivativeXX(x, v)-solver_->derivativeX(x, v))/(s*s);
    }
Real QuantLib::FdmHestonSolver::meanVarianceDeltaAt (Real s, Real v) const
Definition at line 70 of file fdmhestonsolver.cpp.
References QuantLib::LazyObject::calculate(), deltaAt(), process_, and solver_.
Referenced by FdmLinearOpTest::testFdmHestonExpress().
{
        calculate();
        const Real alpha = process_->rho()*process_->sigma()/s;
        return deltaAt(s, v) + alpha*solver_->derivativeY(std::log(s), v);
    }
Real QuantLib::FdmHestonSolver::meanVarianceGammaAt (Real s, Real v) const
Definition at line 77 of file fdmhestonsolver.cpp.
References QuantLib::LazyObject::calculate(), gammaAt(), process_, and solver_.
Referenced by FdmLinearOpTest::testFdmHestonExpress().
{
        calculate();
        const Real x = std::log(s);
        const Real alpha = process_->rho()*process_->sigma()/s;
        return gammaAt(s, v)
                +  solver_->derivativeYY(x, v)*alpha*alpha
                +2*solver_->derivativeXY(x, v)*alpha/s;
    }
void QuantLib::FdmHestonSolver::performCalculations () const [protected, virtual]
This method must implement any calculations which must be (re)done in order to calculate the desired results.
Implements QuantLib::LazyObject.
Definition at line 43 of file fdmhestonsolver.cpp.
References QuantLib::Handle< T >::currentLink(), QuantLib::Handle< T >::empty(), QuantLib::FdmSolverDesc::mesher, process_, quantoHelper_, schemeDesc_, solver_, and solverDesc_.
{
        boost::shared_ptr<FdmLinearOpComposite> op(
                new FdmHestonOp(
                        solverDesc_.mesher, process_.currentLink(),
                        (!quantoHelper_.empty()) ? quantoHelper_.currentLink()
                                     : boost::shared_ptr<FdmQuantoHelper>()));
        solver_ = boost::shared_ptr<Fdm2DimSolver>(
                               new Fdm2DimSolver(solverDesc_, schemeDesc_, op));
    }
Real QuantLib::FdmHestonSolver::thetaAt (Real s, Real v) const
Definition at line 87 of file fdmhestonsolver.cpp.
References QuantLib::LazyObject::calculate(), and solver_.
{
        calculate();
        return solver_->thetaAt(std::log(s), v);
    }
Real QuantLib::FdmHestonSolver::valueAt (Real s, Real v) const
Definition at line 54 of file fdmhestonsolver.cpp.
References QuantLib::LazyObject::calculate(), and solver_.
Referenced by FdmLinearOpTest::testFdmHestonExpress().
{
        calculate();
        return solver_->interpolateAt(std::log(s), v);
    }
Member Data Documentation
const Handle<HestonProcess> QuantLib::FdmHestonSolver::process_ [private]
Definition at line 67 of file fdmhestonsolver.hpp.
Referenced by FdmHestonSolver(), meanVarianceDeltaAt(), meanVarianceGammaAt(), and performCalculations().
const Handle<FdmQuantoHelper> QuantLib::FdmHestonSolver::quantoHelper_ [private]
Definition at line 70 of file fdmhestonsolver.hpp.
Referenced by FdmHestonSolver(), and performCalculations().
const FdmSchemeDesc QuantLib::FdmHestonSolver::schemeDesc_ [private]
Definition at line 69 of file fdmhestonsolver.hpp.
Referenced by performCalculations().
boost::shared_ptr<Fdm2DimSolver> QuantLib::FdmHestonSolver::solver_ [mutable, private]
Definition at line 72 of file fdmhestonsolver.hpp.
Referenced by deltaAt(), gammaAt(), meanVarianceDeltaAt(), meanVarianceGammaAt(), performCalculations(), thetaAt(), and valueAt().
const FdmSolverDesc QuantLib::FdmHestonSolver::solverDesc_ [private]
Definition at line 68 of file fdmhestonsolver.hpp.
Referenced by performCalculations().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/solvers/fdmhestonsolver.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/solvers/fdmhestonsolver.cpp