QuantLib: QuantLib::FdmHestonVariancePart Class Reference
QuantLib::FdmHestonVariancePart Class Reference
#include <fdmhestonop.hpp>
Public Member Functions
FdmHestonVariancePart (const boost::shared_ptr< FdmMesher > &mesher, const boost::shared_ptr< YieldTermStructure > &rTS, Real sigma, Real kappa, Real theta)
void setTime (Time t1, Time t2)
const TripleBandLinearOp & getMap () const
Protected Attributes
const TripleBandLinearOp dyMap_
TripleBandLinearOp mapT_
const boost::shared_ptr
< YieldTermStructure > rTS_
Detailed Description
Definition at line 60 of file fdmhestonop.hpp.
Constructor & Destructor Documentation
QuantLib::FdmHestonVariancePart::FdmHestonVariancePart (const boost::shared_ptr< FdmMesher > & mesher, const boost::shared_ptr< YieldTermStructure > & rTS, Real sigma, Real kappa, Real theta)
Definition at line 78 of file fdmhestonop.cpp.
    : dyMap_(SecondDerivativeOp(1, mesher)
                .mult(0.5*sigma*sigma*mesher->locations(1))
             .add(FirstDerivativeOp(1, mesher)
                  .mult(kappa*(theta - mesher->locations(1))))),
      mapT_(1, mesher),
      rTS_(rTS) {
    }
Member Function Documentation
const TripleBandLinearOp & QuantLib::FdmHestonVariancePart::getMap () const
Definition at line 95 of file fdmhestonop.cpp.
References mapT_.
Referenced by QuantLib::FdmHestonOp::apply(), QuantLib::FdmHestonOp::apply_direction(), QuantLib::FdmHestonOp::solve_splitting(), and QuantLib::FdmHestonOp::toMatrix().
{
        return mapT_;
    }
void QuantLib::FdmHestonVariancePart::setTime (Time t1, Time t2)
Definition at line 90 of file fdmhestonop.cpp.
References QuantLib::TripleBandLinearOp::axpyb(), QuantLib::Continuous, dyMap_, mapT_, and rTS_.
Referenced by QuantLib::FdmHestonOp::setTime().
{
        const Rate r = rTS_->forwardRate(t1, t2, Continuous).rate();
        mapT_.axpyb(Array(), dyMap_, dyMap_, Array(1,-0.5*r));
    }
Member Data Documentation
const TripleBandLinearOp QuantLib::FdmHestonVariancePart::dyMap_ [protected]
Definition at line 71 of file fdmhestonop.hpp.
Referenced by setTime().
TripleBandLinearOp QuantLib::FdmHestonVariancePart::mapT_ [protected]
Definition at line 72 of file fdmhestonop.hpp.
Referenced by getMap(), and setTime().
const boost::shared_ptr<YieldTermStructure> QuantLib::FdmHestonVariancePart::rTS_ [protected]
Definition at line 74 of file fdmhestonop.hpp.
Referenced by setTime().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/operators/fdmhestonop.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/operators/fdmhestonop.cpp