QuantLib: QuantLib::SwaptionVolatilityCube Class Reference
QuantLib::SwaptionVolatilityCube Class Reference
swaption-volatility cube
#include <swaptionvolcube.hpp>
Public Member Functions
SwaptionVolatilityCube (const Handle< SwaptionVolatilityStructure > &atmVolStructure, const std::vector< Period > &optionTenors, const std::vector< Period > &swapTenors, const std::vector< Spread > &strikeSpreads, const std::vector< std::vector< Handle< Quote > > > &volSpreads, const boost::shared_ptr< SwapIndex > &swapIndexBase, const boost::shared_ptr< SwapIndex > &shortSwapIndexBase, bool vegaWeightedSmileFit)
TermStructure interface
DayCounter dayCounter () const
the day counter used for date/time conversion
Date maxDate () const
the latest date for which the curve can return values
Time maxTime () const
the latest time for which the curve can return values
const Date & referenceDate () const
the date at which discount = 1.0 and/or variance = 0.0
Calendar calendar () const
the calendar used for reference and/or option date calculation
Natural settlementDays () const
the settlementDays used for reference date calculation
VolatilityTermStructure interface
Rate minStrike () const
the minimum strike for which the term structure can return vols
Rate maxStrike () const
the maximum strike for which the term structure can return vols
SwaptionVolatilityStructure interface
const Period & maxSwapTenor () const
the largest length for which the term structure can return vols
Other inspectors
Rate atmStrike (const Date &optionDate, const Period &swapTenor) const
Rate atmStrike (const Period &optionTenor, const Period &swapTenor) const
Protected Member Functions
void registerWithVolatilitySpread ()
Volatility volatilityImpl (Time optionTime, Time swapLength, Rate strike) const
Volatility volatilityImpl (const Date &optionDate, const Period &swapTenor, Rate strike) const
Protected Attributes
Handle
< SwaptionVolatilityStructure > atmVol_
Size nStrikes_
std::vector< Spread > strikeSpreads_
std::vector< Rate > localStrikes_
std::vector< Volatility > localSmile_
std::vector< std::vector
< Handle< Quote > > > volSpreads_
boost::shared_ptr< SwapIndex > swapIndexBase_
boost::shared_ptr< SwapIndex > shortSwapIndexBase_
bool vegaWeightedSmileFit_
Detailed Description
swaption-volatility cube
Warning:
this class is not finalized and its interface might change in subsequent releases.
Definition at line 39 of file swaptionvolcube.hpp.
Constructor & Destructor Documentation
QuantLib::SwaptionVolatilityCube::SwaptionVolatilityCube (const Handle< SwaptionVolatilityStructure > & atmVolStructure, const std::vector< Period > & optionTenors, const std::vector< Period > & swapTenors, const std::vector< Spread > & strikeSpreads, const std::vector< std::vector< Handle< Quote > > > & volSpreads, const boost::shared_ptr< SwapIndex > & swapIndexBase, const boost::shared_ptr< SwapIndex > & shortSwapIndexBase, bool vegaWeightedSmileFit)
Definition at line 27 of file swaptionvolcube.cpp.
References atmVol_, QuantLib::Handle< T >::empty(), QuantLib::Settings::evaluationDate(), QuantLib::SwaptionVolatilityDiscrete::evaluationDate_, QuantLib::Singleton< Settings >::instance(), QuantLib::SwaptionVolatilityDiscrete::nOptionTenors_, nStrikes_, QuantLib::SwaptionVolatilityDiscrete::nSwapTenors_, QuantLib::io::ordinal(), QL_REQUIRE, QuantLib::Observer::registerWith(), registerWithVolatilitySpread(), shortSwapIndexBase_, strikeSpreads_, swapIndexBase_, and volSpreads_.
    : SwaptionVolatilityDiscrete(optionTenors, swapTenors, 0,
                                 atmVol->calendar(),
                                 atmVol->businessDayConvention(),
                                 atmVol->dayCounter()),
      atmVol_(atmVol),
      nStrikes_(strikeSpreads.size()),
      strikeSpreads_(strikeSpreads),
      localStrikes_(nStrikes_),
      localSmile_(nStrikes_),
      volSpreads_(volSpreads),
      swapIndexBase_(swapIndexBase),
      shortSwapIndexBase_(shortSwapIndexBase),
      vegaWeightedSmileFit_(vegaWeightedSmileFit)
    {
        QL_REQUIRE(!atmVol.empty(), "atm vol handle not linked to anything");
        QL_REQUIRE(nStrikes_>1, "too few strikes (" << nStrikes_ << ")");
        for (Size i=1; i<nStrikes_; ++i)
            QL_REQUIRE(strikeSpreads_[i-1]<strikeSpreads_[i],
                       "non increasing strike spreads: " <<
                       io::ordinal(i) << " is " << strikeSpreads_[i-1] << ", " <<
                       io::ordinal(i+1) << " is " << strikeSpreads_[i]);
        QL_REQUIRE(!volSpreads_.empty(), "empty vol spreads matrix");
        QL_REQUIRE(nOptionTenors_*nSwapTenors_==volSpreads_.size(),
            "mismatch between number of option tenors * swap tenors (" <<
            nOptionTenors_*nSwapTenors_ << ") and number of rows (" <<
            volSpreads_.size() << ")");
        for (Size i=0; i<volSpreads_.size(); i++)
            QL_REQUIRE(nStrikes_==volSpreads_[i].size(),
                       "mismatch between number of strikes (" << nStrikes_ <<
                       ") and number of columns (" << volSpreads_[i].size() <<
                       ") in the " << io::ordinal(i+1) << " row");
        registerWith(atmVol_);
        atmVol_->enableExtrapolation();
        registerWith(swapIndexBase_);
        registerWith(shortSwapIndexBase_);
        QL_REQUIRE(shortSwapIndexBase_->tenor()<swapIndexBase_->tenor(),
                   "short index tenor (" << shortSwapIndexBase_->tenor() <<
                   ") is not less than index tenor (" <<
                   swapIndexBase_->tenor() << ")");
        registerWithVolatilitySpread();
        registerWith(Settings::instance().evaluationDate());
        evaluationDate_ = Settings::instance().evaluationDate();
    }
Member Function Documentation
Rate QuantLib::SwaptionVolatilityCube::atmStrike (const Date & optionDate, const Period & swapTenor) const
Definition at line 96 of file swaptionvolcube.cpp.
References shortSwapIndexBase_, and swapIndexBase_.
Referenced by atmStrike(), QuantLib::SwaptionVolCube1::fillVolatilityCube(), anonymous_namespace{swaptionvolatilitycube.cpp}::CommonVars::makeAtmVolTest(), anonymous_namespace{swaptionvolatilitycube.cpp}::CommonVars::makeVolSpreadsTest(), QuantLib::SwaptionVolCube1::performCalculations(), QuantLib::SwaptionVolCube1::sabrCalibration(), QuantLib::SwaptionVolCube1::sabrCalibrationSection(), QuantLib::SwaptionVolCube2::smileSectionImpl(), and QuantLib::SwaptionVolCube1::spreadVolInterpolation().
{
        // FIXME use a familyName-based index factory
        if (swapTenor > shortSwapIndexBase_->tenor()) {
            if (swapIndexBase_->exogenousDiscount()) {
                return SwapIndex(swapIndexBase_->familyName(),
                                 swapTenor,
                                 swapIndexBase_->fixingDays(),
                                 swapIndexBase_->currency(),
                                 swapIndexBase_->fixingCalendar(),
                                 swapIndexBase_->fixedLegTenor(),
                                 swapIndexBase_->fixedLegConvention(),
                                 swapIndexBase_->dayCounter(),
                                 swapIndexBase_->iborIndex(),
                                 swapIndexBase_->discountingTermStructure())
                    .fixing(optionD);
            } else {
                return SwapIndex(swapIndexBase_->familyName(),
                                 swapTenor,
                                 swapIndexBase_->fixingDays(),
                                 swapIndexBase_->currency(),
                                 swapIndexBase_->fixingCalendar(),
                                 swapIndexBase_->fixedLegTenor(),
                                 swapIndexBase_->fixedLegConvention(),
                                 swapIndexBase_->dayCounter(),
                                 swapIndexBase_->iborIndex())
                    .fixing(optionD);
            }
        } else {
            if (shortSwapIndexBase_->exogenousDiscount()) {
                return SwapIndex(shortSwapIndexBase_->familyName(),
                                 swapTenor,
                                 shortSwapIndexBase_->fixingDays(),
                                 shortSwapIndexBase_->currency(),
                                 shortSwapIndexBase_->fixingCalendar(),
                                 shortSwapIndexBase_->fixedLegTenor(),
                                 shortSwapIndexBase_->fixedLegConvention(),
                                 shortSwapIndexBase_->dayCounter(),
                                 shortSwapIndexBase_->iborIndex(),
                                 shortSwapIndexBase_->discountingTermStructure())
                    .fixing(optionD);
            } else {
                return SwapIndex(shortSwapIndexBase_->familyName(),
                                 swapTenor,
                                 shortSwapIndexBase_->fixingDays(),
                                 shortSwapIndexBase_->currency(),
                                 shortSwapIndexBase_->fixingCalendar(),
                                 shortSwapIndexBase_->fixedLegTenor(),
                                 shortSwapIndexBase_->fixedLegConvention(),
                                 shortSwapIndexBase_->dayCounter(),
                                 shortSwapIndexBase_->iborIndex())
                    .fixing(optionD);
            }
        }
    }
Rate QuantLib::SwaptionVolatilityCube::atmStrike (const Period & optionTenor, const Period & swapTenor) const [inline]
Definition at line 71 of file swaptionvolcube.hpp.
References atmStrike(), and QuantLib::VolatilityTermStructure::optionDateFromTenor().
{
            Date optionDate = optionDateFromTenor(optionTenor);
            return atmStrike(optionDate, swapTenor);
        }
Calendar QuantLib::SwaptionVolatilityCube::calendar () const [inline, virtual]
the calendar used for reference and/or option date calculation
Reimplemented from QuantLib::TermStructure.
Definition at line 56 of file swaptionvolcube.hpp.
References atmVol_.
{ return atmVol_->calendar(); }
DayCounter QuantLib::SwaptionVolatilityCube::dayCounter () const [inline, virtual]
the day counter used for date/time conversion
Reimplemented from QuantLib::TermStructure.
Definition at line 52 of file swaptionvolcube.hpp.
References atmVol_.
{ return atmVol_->dayCounter(); }
Date QuantLib::SwaptionVolatilityCube::maxDate () const [inline, virtual]
the latest date for which the curve can return values
Implements QuantLib::TermStructure.
Definition at line 53 of file swaptionvolcube.hpp.
References atmVol_.
{ return atmVol_->maxDate(); }
Rate QuantLib::SwaptionVolatilityCube::maxStrike () const [inline, virtual]
the maximum strike for which the term structure can return vols
Implements QuantLib::VolatilityTermStructure.
Definition at line 61 of file swaptionvolcube.hpp.
{ return 1.0; }
const Period& QuantLib::SwaptionVolatilityCube::maxSwapTenor () const [inline, virtual]
the largest length for which the term structure can return vols
Implements QuantLib::SwaptionVolatilityStructure.
Definition at line 65 of file swaptionvolcube.hpp.
References atmVol_.
{ return atmVol_->maxSwapTenor(); }
Time QuantLib::SwaptionVolatilityCube::maxTime () const [inline, virtual]
the latest time for which the curve can return values
Reimplemented from QuantLib::TermStructure.
Definition at line 54 of file swaptionvolcube.hpp.
References atmVol_.
{ return atmVol_->maxTime(); }
Rate QuantLib::SwaptionVolatilityCube::minStrike () const [inline, virtual]
the minimum strike for which the term structure can return vols
Implements QuantLib::VolatilityTermStructure.
Definition at line 60 of file swaptionvolcube.hpp.
{ return 0.0; }
const Date& QuantLib::SwaptionVolatilityCube::referenceDate () const [inline, virtual]
the date at which discount = 1.0 and/or variance = 0.0
Reimplemented from QuantLib::TermStructure.
Definition at line 55 of file swaptionvolcube.hpp.
References atmVol_.
{ return atmVol_->referenceDate();}
void QuantLib::SwaptionVolatilityCube::registerWithVolatilitySpread () [protected]
Definition at line 88 of file swaptionvolcube.cpp.
References QuantLib::SwaptionVolatilityDiscrete::nOptionTenors_, nStrikes_, QuantLib::SwaptionVolatilityDiscrete::nSwapTenors_, QuantLib::Observer::registerWith(), and volSpreads_.
Referenced by SwaptionVolatilityCube().
    {
        for (Size i=0; i<nStrikes_; i++)
            for (Size j=0; j<nOptionTenors_; j++)
                for (Size k=0; k<nSwapTenors_; k++)
                    registerWith(volSpreads_[j*nSwapTenors_+k][i]);
    }
Natural QuantLib::SwaptionVolatilityCube::settlementDays () const [inline, virtual]
the settlementDays used for reference date calculation
Reimplemented from QuantLib::TermStructure.
Definition at line 57 of file swaptionvolcube.hpp.
References atmVol_.
{ return atmVol_->settlementDays(); }
Volatility QuantLib::SwaptionVolatilityCube::volatilityImpl (Time optionTime, Time swapLength, Rate strike) const [inline, protected, virtual]
Implements QuantLib::SwaptionVolatilityStructure.
Definition at line 97 of file swaptionvolcube.hpp.
References QuantLib::SwaptionVolatilityStructure::smileSectionImpl().
{
        return smileSectionImpl(optionTime, swapLength)->volatility(strike);
    }
Volatility QuantLib::SwaptionVolatilityCube::volatilityImpl (const Date & optionDate, const Period & swapTenor, Rate strike) const [inline, protected, virtual]
Reimplemented from QuantLib::SwaptionVolatilityStructure.
Definition at line 104 of file swaptionvolcube.hpp.
References QuantLib::SwaptionVolatilityStructure::smileSectionImpl().
{
        return smileSectionImpl(optionDate, swapTenor)->volatility(strike);
    }
Member Data Documentation
Handle<SwaptionVolatilityStructure> QuantLib::SwaptionVolatilityCube::atmVol_ [protected]
Definition at line 85 of file swaptionvolcube.hpp.
Referenced by calendar(), dayCounter(), maxDate(), maxSwapTenor(), maxTime(), QuantLib::SwaptionVolCube1::performCalculations(), referenceDate(), settlementDays(), QuantLib::SwaptionVolCube2::smileSectionImpl(), QuantLib::SwaptionVolCube1::spreadVolInterpolation(), and SwaptionVolatilityCube().
std::vector<Volatility> QuantLib::SwaptionVolatilityCube::localSmile_ [mutable, protected]
Definition at line 89 of file swaptionvolcube.hpp.
std::vector<Rate> QuantLib::SwaptionVolatilityCube::localStrikes_ [mutable, protected]
Definition at line 88 of file swaptionvolcube.hpp.
Size QuantLib::SwaptionVolatilityCube::nStrikes_ [protected]
Definition at line 86 of file swaptionvolcube.hpp.
Referenced by QuantLib::SwaptionVolCube1::fillVolatilityCube(), QuantLib::SwaptionVolCube2::performCalculations(), QuantLib::SwaptionVolCube1::performCalculations(), registerWithVolatilitySpread(), QuantLib::SwaptionVolCube1::sabrCalibration(), QuantLib::SwaptionVolCube1::sabrCalibrationSection(), QuantLib::SwaptionVolCube2::smileSectionImpl(), QuantLib::SwaptionVolCube1::spreadVolInterpolation(), and SwaptionVolatilityCube().
boost::shared_ptr<SwapIndex> QuantLib::SwaptionVolatilityCube::shortSwapIndexBase_ [protected]
Definition at line 91 of file swaptionvolcube.hpp.
Referenced by atmStrike(), and SwaptionVolatilityCube().
std::vector<Spread> QuantLib::SwaptionVolatilityCube::strikeSpreads_ [protected]
Definition at line 87 of file swaptionvolcube.hpp.
Referenced by QuantLib::SwaptionVolCube1::sabrCalibration(), QuantLib::SwaptionVolCube1::sabrCalibrationSection(), QuantLib::SwaptionVolCube2::smileSectionImpl(), QuantLib::SwaptionVolCube1::spreadVolInterpolation(), and SwaptionVolatilityCube().
boost::shared_ptr<SwapIndex> QuantLib::SwaptionVolatilityCube::swapIndexBase_ [protected]
Definition at line 91 of file swaptionvolcube.hpp.
Referenced by atmStrike(), and SwaptionVolatilityCube().
bool QuantLib::SwaptionVolatilityCube::vegaWeightedSmileFit_ [protected]
Definition at line 92 of file swaptionvolcube.hpp.
Referenced by QuantLib::SwaptionVolCube1::sabrCalibration(), QuantLib::SwaptionVolCube1::sabrCalibrationSection(), and QuantLib::SwaptionVolCube1::SwaptionVolCube1().
std::vector<std::vector<Handle<Quote> > > QuantLib::SwaptionVolatilityCube::volSpreads_ [protected]
Definition at line 90 of file swaptionvolcube.hpp.
Referenced by QuantLib::SwaptionVolCube2::performCalculations(), QuantLib::SwaptionVolCube1::performCalculations(), registerWithVolatilitySpread(), and SwaptionVolatilityCube().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/swaption/swaptionvolcube.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/swaption/swaptionvolcube.cpp