QuantLib: QuantLib::PeriodParser Class Reference
QuantLib::PeriodParser Class Reference
#include <dataparsers.hpp>
Static Public Member Functions
static Period parse (const std::string &str)
Static Private Member Functions
static Period parseOnePeriod (const std::string &str)
Detailed Description
Definition at line 41 of file dataparsers.hpp.
Member Function Documentation
Period QuantLib::PeriodParser::parse (const std::string & str) [static]
Definition at line 50 of file dataparsers.cpp.
References parseOnePeriod(), and QL_REQUIRE.
{
        QL_REQUIRE(str.length()>1, "period string length must be at least 2");
        std::vector<std::string > subStrings;
        std::string reducedString = str;
        Size iPos, reducedStringDim = 100000, max_iter = 0;
        while (reducedStringDim>0) {
            iPos = reducedString.find_first_of("DdWwMmYy");
            Size subStringDim = iPos+1;
            reducedStringDim = reducedString.length()-subStringDim;
            subStrings.push_back(reducedString.substr(0, subStringDim));
            reducedString = reducedString.substr(iPos+1, reducedStringDim);
            ++max_iter;
            QL_REQUIRE(max_iter<str.length(), "unknown '" << str << "' unit");
        }
        Period result = parseOnePeriod(subStrings[0]);
        for (Size i=1; i<subStrings.size(); ++i)
            result += parseOnePeriod(subStrings[i]);
        return result;
    }
Period QuantLib::PeriodParser::parseOnePeriod (const std::string & str) [static, private]
Definition at line 73 of file dataparsers.cpp.
References QuantLib::Days, QuantLib::Months, QL_FAIL, QL_REQUIRE, QuantLib::io::to_integer(), QuantLib::Weeks, and QuantLib::Years.
Referenced by parse().
{
        QL_REQUIRE(str.length()>1, "single period require a string of at "
                   "least 2 characters");
        Size iPos = str.find_first_of("DdWwMmYy");
        QL_REQUIRE(iPos==str.length()-1, "unknown '" <<
                   str.substr(str.length()-1, str.length()) << "' unit");
        TimeUnit units = Days;
        char abbr = std::toupper(str[iPos]);
        if      (abbr == 'D') units = Days;
        else if (abbr == 'W') units = Weeks;
        else if (abbr == 'M') units = Months;
        else if (abbr == 'Y') units = Years;
        Size nPos = str.find_first_of("-+0123456789");
        QL_REQUIRE(nPos<iPos, "no numbers of " << units << " provided");
        Integer n;
        try {
            n = io::to_integer(str.substr(nPos,iPos));
                //boost::lexical_cast<Integer>(str.substr(nPos,iPos));
        } catch (std::exception& e) {
            QL_FAIL("unable to parse the number of units of " << units <<
                    " in '" << str << "'. Error:" << e.what());
        }
        return Period(n, units);
    }
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/utilities/dataparsers.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/utilities/dataparsers.cpp