QuantLib: QuantLib::DiscretizedOption Class Reference
QuantLib::DiscretizedOption Class Reference
Discretized option on a given asset.
#include <discretizedasset.hpp>
Public Member Functions
DiscretizedOption (const boost::shared_ptr< DiscretizedAsset > &underlying, Exercise::Type exerciseType, const std::vector< Time > &exerciseTimes)
void reset (Size size)
std::vector< Time > mandatoryTimes () const
Protected Member Functions
void postAdjustValuesImpl ()
void applyExerciseCondition ()
Protected Attributes
boost::shared_ptr
< DiscretizedAsset > underlying_
Exercise::Type exerciseType_
std::vector< Time > exerciseTimes_
Detailed Description
Discretized option on a given asset.
Warning:
it is advised that derived classes take care of creating and initializing themselves an instance of the underlying.
Definition at line 160 of file discretizedasset.hpp.
Constructor & Destructor Documentation
QuantLib::DiscretizedOption::DiscretizedOption (const boost::shared_ptr< DiscretizedAsset > & underlying, Exercise::Type exerciseType, const std::vector< Time > & exerciseTimes) [inline]
Definition at line 162 of file discretizedasset.hpp.
        : underlying_(underlying), exerciseType_(exerciseType),
          exerciseTimes_(exerciseTimes) {}
Member Function Documentation
void QuantLib::DiscretizedOption::applyExerciseCondition () [inline, protected]
Definition at line 240 of file discretizedasset.hpp.
References QuantLib::Array::size(), underlying_, and QuantLib::DiscretizedAsset::values_.
Referenced by postAdjustValuesImpl().
{
        for (Size i=0; i<values_.size(); i++)
            values_[i] = std::max(underlying_->values()[i], values_[i]);
    }
std::vector< Time > QuantLib::DiscretizedOption::mandatoryTimes () const [inline, virtual]
This method returns the times at which the numerical method should stop while rolling back the asset. Typical examples include payment times, exercise times and such.
Note:
The returned values are not guaranteed to be sorted.
Implements QuantLib::DiscretizedAsset.
Definition at line 229 of file discretizedasset.hpp.
References exerciseTimes_, and underlying_.
Referenced by QuantLib::TreeSwaptionEngine::calculate().
{
        std::vector<Time> times = underlying_->mandatoryTimes();
        // discard negative times...
        std::vector<Time>::const_iterator i =
            std::find_if(exerciseTimes_.begin(),exerciseTimes_.end(),
                         std::bind2nd(std::greater_equal<Time>(),0.0));
        // and add the positive ones
        times.insert(times.end(), i, exerciseTimes_.end());
        return times;
    }
void QuantLib::DiscretizedOption::postAdjustValuesImpl () [protected, virtual]
This method performs the actual post-adjustment
Reimplemented from QuantLib::DiscretizedAsset.
Definition at line 25 of file discretizedasset.cpp.
References QuantLib::Exercise::American, applyExerciseCondition(), QuantLib::Exercise::Bermudan, QuantLib::Exercise::European, exerciseTimes_, exerciseType_, QuantLib::DiscretizedAsset::isOnTime(), QL_FAIL, anonymous_namespace{quantlibbenchmark.cpp}::t, QuantLib::DiscretizedAsset::time(), QuantLib::DiscretizedAsset::time_, and underlying_.
{
        /* In the real world, with time flowing forward, first
           any payment is settled and only after options can be
           exercised. Here, with time flowing backward, options
           must be exercised before performing the adjustment.
        */
        underlying_->partialRollback(time());
        underlying_->preAdjustValues();
        Size i;
        switch (exerciseType_) {
          case Exercise::American:
            if (time_ >= exerciseTimes_[0] && time_ <= exerciseTimes_[1])
                applyExerciseCondition();
            break;
          case Exercise::Bermudan:
          case Exercise::European:
            for (i=0; i<exerciseTimes_.size(); i++) {
                Time t = exerciseTimes_[i];
                if (t >= 0.0 && isOnTime(t))
                    applyExerciseCondition();
            }
            break;
          default:
            QL_FAIL("invalid exercise type");
        }
        underlying_->postAdjustValues();
    }
void QuantLib::DiscretizedOption::reset (Size size) [inline, virtual]
This method should initialize the asset values to an Array of the given size and with values depending on the particular asset.
Implements QuantLib::DiscretizedAsset.
Reimplemented in QuantLib::DiscretizedSwaption.
Definition at line 221 of file discretizedasset.hpp.
References QuantLib::DiscretizedAsset::adjustValues(), QuantLib::DiscretizedAsset::method(), QL_REQUIRE, underlying_, and QuantLib::DiscretizedAsset::values_.
{
        QL_REQUIRE(method() == underlying_->method(),
                   "option and underlying were initialized on "
                   "different methods");
        values_ = Array(size, 0.0);
        adjustValues();
    }
Member Data Documentation
std::vector<Time> QuantLib::DiscretizedOption::exerciseTimes_ [protected]
Definition at line 175 of file discretizedasset.hpp.
Referenced by QuantLib::DiscretizedSwaption::DiscretizedSwaption(), mandatoryTimes(), and postAdjustValuesImpl().
Exercise::Type QuantLib::DiscretizedOption::exerciseType_ [protected]
Definition at line 174 of file discretizedasset.hpp.
Referenced by postAdjustValuesImpl().
boost::shared_ptr<DiscretizedAsset> QuantLib::DiscretizedOption::underlying_ [protected]
Definition at line 173 of file discretizedasset.hpp.
Referenced by applyExerciseCondition(), QuantLib::DiscretizedSwaption::DiscretizedSwaption(), mandatoryTimes(), postAdjustValuesImpl(), QuantLib::DiscretizedSwaption::reset(), and reset().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/discretizedasset.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/discretizedasset.cpp