QuantLib: QuantLib::IterativeBootstrap< Curve > Class Template Reference
QuantLib::IterativeBootstrap< Curve > Class Template Reference
Universal piecewise-term-structure boostrapper.
#include <iterativebootstrap.hpp>
Public Member Functions
IterativeBootstrap ()
void setup (Curve *ts)
void calculate () const
Private Types
typedef Curve::traits_type Traits
typedef Curve::interpolator_type Interpolator
Private Member Functions
void initialize () const
Private Attributes
Curve * ts_
Size n_
Brent firstSolver_
FiniteDifferenceNewtonSafe solver_
bool initialized_
bool validCurve_
Size firstAliveHelper_
Size alive_
std::vector< Real > previousData_
std::vector< boost::shared_ptr
< BootstrapError< Curve > > > errors_
Detailed Description
template<class Curve>
class QuantLib::IterativeBootstrap< Curve >
Universal piecewise-term-structure boostrapper.
Definition at line 40 of file iterativebootstrap.hpp.
Member Typedef Documentation
template<class Curve > typedef Curve::interpolator_type QuantLib::IterativeBootstrap< Curve >::Interpolator [private]
Definition at line 42 of file iterativebootstrap.hpp.
template<class Curve > typedef Curve::traits_type QuantLib::IterativeBootstrap< Curve >::Traits [private]
Definition at line 41 of file iterativebootstrap.hpp.
Constructor & Destructor Documentation
template<class Curve > QuantLib::IterativeBootstrap< Curve >::IterativeBootstrap ()
Definition at line 63 of file iterativebootstrap.hpp.
        : ts_(0), initialized_(false), validCurve_(false) {}
Member Function Documentation
template<class Curve > void QuantLib::IterativeBootstrap< Curve >::calculate () const
Definition at line 131 of file iterativebootstrap.hpp.
References anonymous_namespace{stats.cpp}::data, QuantLib::Linear::interpolate(), QuantLib::io::ordinal(), QL_FAIL, QL_REQUIRE, and QuantLib::Interpolation::update().
{
        // we might have to call initialize even if the curve is initialized
        // and not moving, just because helpers might be date relative and change
        // with evaluation date change.
        // anyway it makes little sense to use date relative helpers with a
        // non-moving curve if the evaluation date changes
        if (!initialized_ || ts_->moving_)
            initialize();
        // setup helpers
        for (Size j=firstAliveHelper_; j<n_; ++j) {
            const boost::shared_ptr<typename Traits::helper>& helper =
                                                        ts_->instruments_[j];
            // check for valid quote
            QL_REQUIRE(helper->quote()->isValid(),
                       io::ordinal(j+1) << " instrument (maturity: " <<
                       helper->latestDate() << ") has an invalid quote");
            // don't try this at home!
            // This call creates helpers, and removes "const".
            // There is a significant interaction with observability.
            helper->setTermStructure(const_cast<Curve*>(ts_));
        }
        const std::vector<Time>& times = ts_->times_;
        const std::vector<Real>& data = ts_->data_;
        Real accuracy = ts_->accuracy_;
        Size maxIterations = Traits::maxIterations()-1;
        for (Size iteration=0; ; ++iteration) {
            previousData_ = ts_->data_;
            for (Size i=1; i<=alive_; ++i) { // pillar loop
                bool validData = validCurve_ || iteration>0;
                // bracket root and calculate guess
                Real min = Traits::minValueAfter(i, ts_, validData,
                                                            firstAliveHelper_);
                Real max = Traits::maxValueAfter(i, ts_, validData,
                                                            firstAliveHelper_);
                Real guess = Traits::guess(i, ts_, validData,
                                                            firstAliveHelper_);
                // adjust guess if needed
                if (guess>=max)
                    guess = max - (max-min)/5.0;
                else if (guess<=min)
                    guess = min + (max-min)/5.0;
                // extend interpolation if needed
                if (!validData) {
                    try { // extend interpolation a point at a time
                          // including the pillar to be boostrapped
                        ts_->interpolation_ = ts_->interpolator_.interpolate(
                            times.begin(), times.begin()+i+1, data.begin());
                    } catch (...) {
                        if (!Interpolator::global)
                            throw; // no chance to fix it in a later iteration
                        // otherwise use Linear while the target
                        // interpolation is not usable yet
                        ts_->interpolation_ = Linear().interpolate(
                            times.begin(), times.begin()+i+1, data.begin());
                    }
                    ts_->interpolation_.update();
                }
                try {
                    if (validData)
                        solver_.solve(*errors_[i], accuracy, guess, min, max);
                    else
                        firstSolver_.solve(*errors_[i], accuracy,guess,min,max);
                } catch (std::exception &e) {
                    validCurve_ = false;
                    QL_FAIL(io::ordinal(iteration+1) << " iteration: failed "
                            "at " << io::ordinal(i) << " alive instrument, "
                            "maturity " << errors_[i]->helper()->latestDate()<<
                            ", reference date " << ts_->dates_[0] <<
                            ": " << e.what());
                }
            }
            if (!Interpolator::global)
                break;     // no need for convergence loop
            else if (iteration==0)
                continue; // at least one more iteration to convergence check
            // exit condition
            Real change = std::fabs(data[1]-previousData_[1]);
            for (Size i=2; i<=alive_; ++i)
                change = std::max(change, std::fabs(data[i]-previousData_[i]));
            if (change<=accuracy)  // convergence reached
                break;
            QL_REQUIRE(iteration<maxIterations,
                       "convergence not reached after " << iteration <<
                       " iterations; last improvement " << change <<
                       ", required accuracy " << accuracy);
        }
        validCurve_ = true;
    }
template<class Curve > void QuantLib::IterativeBootstrap< Curve >::initialize () const [private]
Definition at line 79 of file iterativebootstrap.hpp.
References anonymous_namespace{marketmodel.cpp}::dates, QuantLib::Schedule::dates_, and QL_REQUIRE.
{
        // ensure helpers are sorted
        std::sort(ts_->instruments_.begin(), ts_->instruments_.end(),
                  detail::BootstrapHelperSorter());
        // skip expired helpers
        Date firstDate = Traits::initialDate(ts_);
        QL_REQUIRE(ts_->instruments_[n_-1]->latestDate()>firstDate,
                   "all instruments expired");
        firstAliveHelper_ = 0;
        while (ts_->instruments_[firstAliveHelper_]->latestDate() <= firstDate)
            ++firstAliveHelper_;
        alive_ = n_-firstAliveHelper_;
        QL_REQUIRE(alive_>=Interpolator::requiredPoints-1,
                   "not enough alive instruments: " << alive_ <<
                   " provided, " << Interpolator::requiredPoints-1 <<
                   " required");
        // calculate dates and times, create errors_
        std::vector<Date>& dates = ts_->dates_;
        std::vector<Time>& times = ts_->times_;
        dates.resize(alive_+1);
        times.resize(alive_+1);
        errors_.resize(alive_+1);
        dates[0] = firstDate;
        times[0] = ts_->timeFromReference(dates[0]);
        // pillar counter: i
        // helper counter: j
        for (Size i=1, j=firstAliveHelper_; j<n_; ++i, ++j) {
            const boost::shared_ptr<typename Traits::helper>& helper =
                                                        ts_->instruments_[j];
            dates[i] = helper->latestDate();
            times[i] = ts_->timeFromReference(dates[i]);
            // check for duplicated maturity
            QL_REQUIRE(dates[i-1]!=dates[i],
                       "more than one instrument with maturity " << dates[i]);
            errors_[i] = boost::shared_ptr<BootstrapError<Curve> >(new
                BootstrapError<Curve>(ts_, helper, i));
        }
        // set initial guess only if the current curve cannot be used as guess
        if (!validCurve_ || ts_->data_.size()!=alive_+1) {
            // ts_->data_[0] is the only relevant item,
            // but reasonable numbers might be needed for the whole data vector
            // because, e.g., of interpolation's early checks
            ts_->data_ = std::vector<Real>(alive_+1, Traits::initialValue(ts_));
            previousData_.resize(alive_+1);
        }
        initialized_ = true;
    }
template<class Curve > void QuantLib::IterativeBootstrap< Curve >::setup (Curve * ts)
Definition at line 67 of file iterativebootstrap.hpp.
{
        ts_ = ts;
        n_ = ts_->instruments_.size();
        for (Size j=0; j<n_; ++j)
            ts_->registerWith(ts_->instruments_[j]);
        // do not initialize yet: instruments could be invalid here
        // but valid later when bootstrapping is actually required
    }
Member Data Documentation
template<class Curve > Size QuantLib::IterativeBootstrap< Curve >::alive_ [mutable, private]
Definition at line 54 of file iterativebootstrap.hpp.
template<class Curve > std::vector<boost::shared_ptr<BootstrapError<Curve> > > QuantLib::IterativeBootstrap< Curve >::errors_ [mutable, private]
Definition at line 56 of file iterativebootstrap.hpp.
template<class Curve > Size QuantLib::IterativeBootstrap< Curve >::firstAliveHelper_ [mutable, private]
Definition at line 54 of file iterativebootstrap.hpp.
template<class Curve > Brent QuantLib::IterativeBootstrap< Curve >::firstSolver_ [private]
Definition at line 51 of file iterativebootstrap.hpp.
template<class Curve > bool QuantLib::IterativeBootstrap< Curve >::initialized_ [mutable, private]
Definition at line 53 of file iterativebootstrap.hpp.
template<class Curve > Size QuantLib::IterativeBootstrap< Curve >::n_ [private]
Definition at line 50 of file iterativebootstrap.hpp.
template<class Curve > std::vector<Real> QuantLib::IterativeBootstrap< Curve >::previousData_ [mutable, private]
Definition at line 55 of file iterativebootstrap.hpp.
template<class Curve > FiniteDifferenceNewtonSafe QuantLib::IterativeBootstrap< Curve >::solver_ [private]
Definition at line 52 of file iterativebootstrap.hpp.
template<class Curve > Curve* QuantLib::IterativeBootstrap< Curve >::ts_ [private]
Definition at line 49 of file iterativebootstrap.hpp.
template<class Curve > bool QuantLib::IterativeBootstrap< Curve >::validCurve_ [mutable, private]
Definition at line 53 of file iterativebootstrap.hpp.
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/iterativebootstrap.hpp