QuantLib: QuantLib::HestonModelHelper Class Reference
QuantLib::HestonModelHelper Class Reference
calibration helper for Heston model
#include <hestonmodelhelper.hpp>
Public Member Functions
HestonModelHelper (const Period &maturity, const Calendar &calendar, const Real s0, const Real strikePrice, const Handle< Quote > &volatility, const Handle< YieldTermStructure > &riskFreeRate, const Handle< YieldTermStructure > &dividendYield, CalibrationHelper::CalibrationErrorType errorType=CalibrationHelper::RelativePriceError)
void addTimesTo (std::list< Time > &) const
Real modelValue () const
returns the price of the instrument according to the model
Real blackPrice (Real volatility) const
Black price given a volatility.
Time maturity () const
Private Attributes
Handle< YieldTermStructure > dividendYield_
boost::shared_ptr< VanillaOption > option_
const Date exerciseDate_
const Time tau_
const Real s0_
const Real strikePrice_
Detailed Description
calibration helper for Heston model
Definition at line 33 of file hestonmodelhelper.hpp.
Constructor & Destructor Documentation
QuantLib::HestonModelHelper::HestonModelHelper (const Period & maturity, const Calendar & calendar, const Real s0, const Real strikePrice, const Handle< Quote > & volatility, const Handle< YieldTermStructure > & riskFreeRate, const Handle< YieldTermStructure > & dividendYield, CalibrationHelper::CalibrationErrorType errorType = CalibrationHelper::RelativePriceError)
Definition at line 30 of file hestonmodelhelper.cpp.
References blackPrice(), QuantLib::Option::Call, exerciseDate_, QuantLib::CalibrationHelper::marketValue_, option_, and strikePrice_.
    : CalibrationHelper(volatility, riskFreeRate, errorType),
      dividendYield_(dividendYield),
      exerciseDate_(calendar.advance(riskFreeRate->referenceDate(),
                                     maturity)),
      tau_(riskFreeRate->dayCounter().yearFraction(
                               riskFreeRate->referenceDate(), exerciseDate_)),
      s0_(s0), strikePrice_(strikePrice) {
        boost::shared_ptr<StrikedTypePayoff> payoff(
                          new PlainVanillaPayoff(Option::Call, strikePrice_));
        boost::shared_ptr<Exercise> exercise(
                                         new EuropeanExercise(exerciseDate_));
        option_ = boost::shared_ptr<VanillaOption>(
                           new VanillaOption(payoff, exercise));
        marketValue_ = blackPrice(volatility->value());
    }
Member Function Documentation
void QuantLib::HestonModelHelper::addTimesTo (std::list< Time > &) const [inline, virtual]
Implements QuantLib::CalibrationHelper.
Definition at line 46 of file hestonmodelhelper.hpp.
{}
Real QuantLib::HestonModelHelper::blackPrice (Real volatility) const [virtual]
Black price given a volatility.
Implements QuantLib::CalibrationHelper.
Definition at line 64 of file hestonmodelhelper.cpp.
References QuantLib::blackFormula(), QuantLib::Option::Call, dividendYield_, maturity(), s0_, strikePrice_, tau_, QuantLib::CalibrationHelper::termStructure_, and QuantLib::io::volatility().
Referenced by HestonModelHelper().
{
        const Real volatility = sigma*std::sqrt(maturity());
        return blackFormula(Option::Call,
            strikePrice_*termStructure_->discount(tau_),
            s0_*dividendYield_->discount(tau_),
            volatility);
    }
Time QuantLib::HestonModelHelper::maturity () const [inline]
Definition at line 49 of file hestonmodelhelper.hpp.
References tau_.
Referenced by blackPrice().
{ return tau_; }
Real QuantLib::HestonModelHelper::modelValue () const [virtual]
returns the price of the instrument according to the model
Implements QuantLib::CalibrationHelper.
Definition at line 59 of file hestonmodelhelper.cpp.
References QuantLib::CalibrationHelper::engine_, and option_.
{
        option_->setPricingEngine(engine_);
        return option_->NPV();
    }
Member Data Documentation
Handle<YieldTermStructure> QuantLib::HestonModelHelper::dividendYield_ [private]
Definition at line 51 of file hestonmodelhelper.hpp.
Referenced by blackPrice().
const Date QuantLib::HestonModelHelper::exerciseDate_ [private]
Definition at line 53 of file hestonmodelhelper.hpp.
Referenced by HestonModelHelper().
boost::shared_ptr<VanillaOption> QuantLib::HestonModelHelper::option_ [private]
Definition at line 52 of file hestonmodelhelper.hpp.
Referenced by HestonModelHelper(), and modelValue().
const Real QuantLib::HestonModelHelper::s0_ [private]
Definition at line 55 of file hestonmodelhelper.hpp.
Referenced by blackPrice().
const Real QuantLib::HestonModelHelper::strikePrice_ [private]
Definition at line 56 of file hestonmodelhelper.hpp.
Referenced by blackPrice(), and HestonModelHelper().
const Time QuantLib::HestonModelHelper::tau_ [private]
Definition at line 54 of file hestonmodelhelper.hpp.
Referenced by blackPrice(), and maturity().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/equity/hestonmodelhelper.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/equity/hestonmodelhelper.cpp