QuantLib: QuantLib::ForwardTypePayoff Class Reference
QuantLib::ForwardTypePayoff Class Reference
Class for forward type payoffs.
#include <forward.hpp>
Public Member Functions
ForwardTypePayoff (Position::Type type, Real strike)
Position::Type forwardType () const
Real strike () const
Payoff interface
std::string name () const
std::string description () const
Real operator() (Real price) const
Protected Attributes
Position::Type type_
Real strike_
Detailed Description
Class for forward type payoffs.
Definition at line 146 of file forward.hpp.
Constructor & Destructor Documentation
QuantLib::ForwardTypePayoff::ForwardTypePayoff (Position::Type type, Real strike) [inline]
Definition at line 148 of file forward.hpp.
References QL_REQUIRE.
        : type_(type),strike_(strike) {
            QL_REQUIRE(strike >= 0.0,"negative strike given");
        }
Member Function Documentation
std::string QuantLib::ForwardTypePayoff::description () const [inline, virtual]
Implements QuantLib::Payoff.
Definition at line 190 of file forward.hpp.
References name(), and strike().
{
        std::ostringstream result;
        result << name() << ", " << strike() << " strike";
        return result.str();
    }
Position::Type QuantLib::ForwardTypePayoff::forwardType () const [inline]
Definition at line 152 of file forward.hpp.
References type_.
{ return type_; };
std::string QuantLib::ForwardTypePayoff::name () const [inline, virtual]
Warning:
This method is used for output and comparison between payoffs. It is not meant to be used for writing switch-on-type code.
Implements QuantLib::Payoff.
Definition at line 156 of file forward.hpp.
Referenced by description().
{ return "Forward";}
Real QuantLib::ForwardTypePayoff::operator() (Real price) const [inline, virtual]
Implements QuantLib::Payoff.
Definition at line 196 of file forward.hpp.
References QuantLib::Position::Long, QL_FAIL, QuantLib::Position::Short, strike_, and type_.
{
        switch (type_) {
          case Position::Long:
            return (price-strike_);
          case Position::Short:
            return (strike_-price);
          default:
            QL_FAIL("unknown/illegal position type");
        }
    }
Real QuantLib::ForwardTypePayoff::strike () const [inline]
Definition at line 153 of file forward.hpp.
References strike_.
Referenced by description().
{ return strike_; };
Member Data Documentation
Real QuantLib::ForwardTypePayoff::strike_ [protected]
Definition at line 162 of file forward.hpp.
Referenced by operator()(), and strike().
Position::Type QuantLib::ForwardTypePayoff::type_ [protected]
Definition at line 161 of file forward.hpp.
Referenced by forwardType(), and operator()().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/forward.hpp