QuantLib: QuantLib::EnergyVanillaSwap Class Reference
QuantLib::EnergyVanillaSwap Class Reference
Vanilla energy swap.
#include <energyvanillaswap.hpp>
Public Member Functions
EnergyVanillaSwap (bool payer, const Calendar &calendar, const Money &fixedPrice, const UnitOfMeasure &fixedPriceUnitOfMeasure, const boost::shared_ptr< CommodityIndex > &index, const Currency &payCurrency, const Currency &receiveCurrency, const PricingPeriods &pricingPeriods, const CommodityType &commodityType, const boost::shared_ptr< SecondaryCosts > &secondaryCosts, const Handle< YieldTermStructure > &payLegTermStructure, const Handle< YieldTermStructure > &receiveLegTermStructure, const Handle< YieldTermStructure > &discountTermStructure)
bool isExpired () const
returns whether the instrument might have value greater than zero.
Integer payReceive () const
const Money & fixedPrice () const
const UnitOfMeasure & fixedPriceUnitOfMeasure () const
const boost::shared_ptr
< CommodityIndex > & index () const
Protected Member Functions
void performCalculations () const
Protected Attributes
Integer payReceive_
Money fixedPrice_
UnitOfMeasure fixedPriceUnitOfMeasure_
boost::shared_ptr< CommodityIndex > index_
Handle< YieldTermStructure > payLegTermStructure_
Handle< YieldTermStructure > receiveLegTermStructure_
Handle< YieldTermStructure > discountTermStructure_
Detailed Description
Vanilla energy swap.
Definition at line 34 of file energyvanillaswap.hpp.
Constructor & Destructor Documentation
QuantLib::EnergyVanillaSwap::EnergyVanillaSwap (bool payer, const Calendar & calendar, const Money & fixedPrice, const UnitOfMeasure & fixedPriceUnitOfMeasure, const boost::shared_ptr< CommodityIndex > & index, const Currency & payCurrency, const Currency & receiveCurrency, const PricingPeriods & pricingPeriods, const CommodityType & commodityType, const boost::shared_ptr< SecondaryCosts > & secondaryCosts, const Handle< YieldTermStructure > & payLegTermStructure, const Handle< YieldTermStructure > & receiveLegTermStructure, const Handle< YieldTermStructure > & discountTermStructure)
Definition at line 25 of file energyvanillaswap.cpp.
References index_, QuantLib::EnergySwap::pricingPeriods_, QL_REQUIRE, and QuantLib::Observer::registerWith().
    : EnergySwap(calendar, payCurrency, receiveCurrency, pricingPeriods,
                 commodityType, secondaryCosts),
      payReceive_(payer ? 1 : 0), fixedPrice_(fixedPrice),
      fixedPriceUnitOfMeasure_(fixedPriceUnitOfMeasure),
      index_(index), payLegTermStructure_(payLegTermStructure),
      receiveLegTermStructure_(receiveLegTermStructure),
      discountTermStructure_(discountTermStructure) {
        QL_REQUIRE(pricingPeriods_.size() > 0, "no pricing periods");
        registerWith(index_);
    }
Member Function Documentation
const Money& QuantLib::EnergyVanillaSwap::fixedPrice () const [inline]
Definition at line 53 of file energyvanillaswap.hpp.
References fixedPrice_.
{ return fixedPrice_; }
const UnitOfMeasure& QuantLib::EnergyVanillaSwap::fixedPriceUnitOfMeasure () const [inline]
Definition at line 54 of file energyvanillaswap.hpp.
References fixedPriceUnitOfMeasure_.
{
            return fixedPriceUnitOfMeasure_;
        }
const boost::shared_ptr<CommodityIndex>& QuantLib::EnergyVanillaSwap::index () const [inline]
Definition at line 57 of file energyvanillaswap.hpp.
References index_.
{
            return index_;
        }
bool QuantLib::EnergyVanillaSwap::isExpired () const [virtual]
returns whether the instrument might have value greater than zero.
Reimplemented from QuantLib::EnergySwap.
Definition at line 50 of file energyvanillaswap.cpp.
References QuantLib::EnergySwap::pricingPeriods_.
{
        return detail::simple_event(pricingPeriods_.back()->endDate())
               .hasOccurred();
    }
Integer QuantLib::EnergyVanillaSwap::payReceive () const [inline]
Definition at line 52 of file energyvanillaswap.hpp.
References payReceive_.
{ return payReceive_; }
void QuantLib::EnergyVanillaSwap::performCalculations () const [protected, virtual]
In case a pricing engine is not used, this method must be overridden to perform the actual calculations and set any needed results. In case a pricing engine is used, the default implementation can be used.
Reimplemented from QuantLib::Instrument.
Definition at line 55 of file energyvanillaswap.cpp.
References QuantLib::Instrument::additionalResults_, QuantLib::Commodity::addPricingError(), QuantLib::Calendar::adjust(), QuantLib::Calendar::advance(), QuantLib::EnergyCommodity::calculateFxConversionFactor(), QuantLib::EnergyCommodity::calculateSecondaryCostAmounts(), QuantLib::EnergyCommodity::calculateUomConversionFactor(), QuantLib::EnergySwap::calendar_, QuantLib::EnergySwap::commodityType(), QuantLib::CommoditySettings::currency(), QuantLib::Money::currency(), QuantLib::EnergySwap::dailyPositions_, QuantLib::Days, discountTermStructure_, QuantLib::PricingError::Error, QuantLib::Settings::evaluationDate(), fixedPrice_, fixedPriceUnitOfMeasure_, index_, QuantLib::Singleton< Settings >::instance(), QuantLib::Singleton< CommoditySettings >::instance(), QuantLib::io::iso_date(), QuantLib::Instrument::NPV_, QuantLib::EnergySwap::payCurrency_, QuantLib::EnergyDailyPosition::payLegPrice, payLegTermStructure_, QuantLib::EnergySwap::paymentCashFlows_, payReceive_, QuantLib::EnergySwap::pricingPeriods_, QL_FAIL, QL_REQUIRE, QuantLib::EnergySwap::quantity(), QuantLib::EnergyDailyPosition::quantityAmount, QuantLib::EnergySwap::receiveCurrency_, QuantLib::EnergyDailyPosition::receiveLegPrice, receiveLegTermStructure_, QuantLib::EnergyDailyPosition::riskDelta, QuantLib::Commodity::secondaryCostAmounts_, QuantLib::CommoditySettings::unitOfMeasure(), QuantLib::Money::value(), QuantLib::PricingError::Warning, and QuantLib::Error::what().
{
        try {
            if (index_->empty()) {
                if (index_->forwardCurveEmpty()) {
                    QL_FAIL("index [" << index_->name()
                            << "] does not have any quotes");
                } else {
                    addPricingError(PricingError::Warning,
                                    "index [" + index_->name() +
                                    "] does not have any quotes; "
                                    "using forward prices from ["
                                    + index_->forwardCurve()->name() + "]");
                }
            }
            NPV_ = 0.0;
            additionalResults_.clear();
            dailyPositions_.clear();
            paymentCashFlows_.clear();
            Date evaluationDate = Settings::instance().evaluationDate();
            const Currency& baseCurrency =
                CommoditySettings::instance().currency();
            const UnitOfMeasure baseUnitOfMeasure =
                CommoditySettings::instance().unitOfMeasure();
            Real quantityUomConversionFactor =
                calculateUomConversionFactor(
                               pricingPeriods_[0]->quantity().commodityType(),
                               baseUnitOfMeasure,
                               pricingPeriods_[0]->quantity().unitOfMeasure());
            Real fixedPriceUomConversionFactor =
                calculateUomConversionFactor(
                               pricingPeriods_[0]->quantity().commodityType(),
                               fixedPriceUnitOfMeasure_, baseUnitOfMeasure);
            Real indexUomConversionFactor =
                calculateUomConversionFactor(index_->commodityType(),
                                             index_->unitOfMeasure(),
                                             baseUnitOfMeasure);
            Real fixedPriceFxConversionFactor =
                calculateFxConversionFactor(fixedPrice_.currency(),
                                            baseCurrency, evaluationDate);
            Real indexPriceFxConversionFactor =
                calculateFxConversionFactor(index_->currency(),
                                            baseCurrency, evaluationDate);
            Real payLegFxConversionFactor =
                calculateFxConversionFactor(
                            baseCurrency,
                            payReceive_ > 0 ? payCurrency_ : receiveCurrency_,
                            evaluationDate);
            Real receiveLegFxConversionFactor =
                calculateFxConversionFactor(
                            baseCurrency,
                            payReceive_ > 0 ? receiveCurrency_ : payCurrency_,
                            evaluationDate);
            Date lastQuoteDate = index_->lastQuoteDate();
            if (lastQuoteDate < evaluationDate - 1) {
                std::ostringstream message;
                message << "index [" << index_->name()
                        << "] has last quote date of "
                        << io::iso_date(lastQuoteDate);
                addPricingError(PricingError::Warning, message.str());
            }
            Real totalQuantityAmount = 0;
            // price each period
            for (PricingPeriods::const_iterator pi = pricingPeriods_.begin();
                 pi != pricingPeriods_.end(); pi++) {
                const boost::shared_ptr<PricingPeriod>& pricingPeriod = *pi;
                QL_REQUIRE(pricingPeriod->quantity().amount() != 0,
                           "quantity is zero");
                Integer periodDayCount = 0;
                // get the futures quotes or everything after
                Date periodStartDate =
                    calendar_.adjust(pricingPeriod->startDate());
                for (Date stepDate = periodStartDate;
                     stepDate <= pricingPeriod->endDate();
                     stepDate = calendar_.advance(stepDate, 1*Days)) {
                    bool unrealized = stepDate > evaluationDate;
                    Real quoteValue = 0;
                    if (stepDate <= lastQuoteDate) {
                        quoteValue = index_->price(stepDate);
                    } else {
                        quoteValue = index_->forwardPrice(stepDate);
                    }
                    if (quoteValue == 0) {
                        std::ostringstream message;
                        message << "pay quote value for curve ["
                                << index_->name() << "] is 0 for date "
                                << io::iso_date(stepDate);
                        addPricingError(PricingError::Warning, message.str());
                    }
                    QL_REQUIRE(quoteValue != Null<Real>(),
                               "curve [" << index_->name() <<
                               "] missing value for pricing date: "
                               << stepDate);
                    Real fixedLegPriceValue =
                        fixedPrice_.value() * fixedPriceUomConversionFactor *
                        fixedPriceFxConversionFactor;
                    Real floatingLegPriceValue =
                        quoteValue * indexUomConversionFactor *
                        indexPriceFxConversionFactor;
                    Real payLegPriceValue =
                        payReceive_ > 0 ? fixedLegPriceValue :
                                          floatingLegPriceValue;
                    Real receiveLegPriceValue =
                        payReceive_ > 0 ? floatingLegPriceValue :
                                          fixedLegPriceValue;
                    dailyPositions_[stepDate] =
                        EnergyDailyPosition(stepDate, payLegPriceValue,
                                            receiveLegPriceValue, unrealized);
                    periodDayCount++;
                }
                Real periodQuantityAmount =
                    pricingPeriod->quantity().amount() *
                    quantityUomConversionFactor;
                totalQuantityAmount += periodQuantityAmount;
                Real avgDailyQuantityAmount =
                    periodDayCount == 0 ? 0 :
                                          periodQuantityAmount / periodDayCount;
                Real payLegValue = 0;
                Real receiveLegValue = 0;
                for (std::map<Date, EnergyDailyPosition>::iterator dpi =
                         dailyPositions_.find(periodStartDate);
                     dpi != dailyPositions_.end() &&
                         dpi->first <= pricingPeriod->endDate(); dpi++) {
                    EnergyDailyPosition& dailyPosition = dpi->second;
                    dailyPosition.quantityAmount = avgDailyQuantityAmount;
                    dailyPosition.riskDelta =
                        (-dailyPosition.payLegPrice + dailyPosition.receiveLegPrice) * avgDailyQuantityAmount;
                    payLegValue += -dailyPosition.payLegPrice * avgDailyQuantityAmount;
                    receiveLegValue += dailyPosition.receiveLegPrice * avgDailyQuantityAmount;
                }
                Real discountFactor = 1;
                Real payLegDiscountFactor = 1;
                Real receiveLegDiscountFactor = 1;
                if (pricingPeriod->paymentDate() >= evaluationDate + 2) {
                    discountFactor =
                        discountTermStructure_->discount(
                                                pricingPeriod->paymentDate());
                    payLegDiscountFactor =
                        payLegTermStructure_->discount(
                                                pricingPeriod->paymentDate());
                    receiveLegDiscountFactor =
                        receiveLegTermStructure_->discount(
                                                pricingPeriod->paymentDate());
                }
                Real uDelta = receiveLegValue + payLegValue;
                Real dDelta = (receiveLegValue * receiveLegDiscountFactor) +
                    (payLegValue * payLegDiscountFactor);
                Real pmtFxConversionFactor =
                    ((dDelta * payReceive_) > 0) ? payLegFxConversionFactor :
                                                   receiveLegFxConversionFactor;
                Currency pmtCurrency =
                    ((dDelta * payReceive_) > 0) ? receiveCurrency_ :
                                                   payCurrency_;
                Real pmtDiscountFactor =
                    (dDelta  > 0) ? receiveLegDiscountFactor :
                                    payLegDiscountFactor;
                paymentCashFlows_[pricingPeriod->paymentDate()] =
                    boost::shared_ptr<CommodityCashFlow>(
                           new CommodityCashFlow(pricingPeriod->paymentDate(),
                                                 Money(baseCurrency,
                                                       uDelta * discountFactor),
                                                 Money(baseCurrency, uDelta),
                                                 Money(pmtCurrency,
                                                       dDelta * pmtFxConversionFactor),
                                                 Money(pmtCurrency,
                                                       uDelta * pmtFxConversionFactor),
                                                 discountFactor,
                                                 pmtDiscountFactor,
                                                 pricingPeriod->paymentDate() <= evaluationDate));
                calculateSecondaryCostAmounts(
                               pricingPeriods_[0]->quantity().commodityType(),
                               totalQuantityAmount, evaluationDate);
                NPV_ += dDelta;
            }
            QL_REQUIRE(!paymentCashFlows_.empty(), "no cashflows");
            for (SecondaryCostAmounts::const_iterator i =
                     secondaryCostAmounts_.begin();
                 i != secondaryCostAmounts_.end(); i++) {
                Real amount = i->second.value();
                NPV_ -= amount;
            }
            additionalResults_["dailyPositions"] = dailyPositions_;
        } catch (const QuantLib::Error& e) {
            addPricingError(PricingError::Error, e.what());
            throw;
        } catch (const std::exception& e) {
            addPricingError(PricingError::Error, e.what());
            throw;
        }
    }
Member Data Documentation
Handle<YieldTermStructure> QuantLib::EnergyVanillaSwap::discountTermStructure_ [protected]
Definition at line 70 of file energyvanillaswap.hpp.
Referenced by performCalculations().
Money QuantLib::EnergyVanillaSwap::fixedPrice_ [protected]
Definition at line 65 of file energyvanillaswap.hpp.
Referenced by fixedPrice(), and performCalculations().
UnitOfMeasure QuantLib::EnergyVanillaSwap::fixedPriceUnitOfMeasure_ [protected]
Definition at line 66 of file energyvanillaswap.hpp.
Referenced by fixedPriceUnitOfMeasure(), and performCalculations().
boost::shared_ptr<CommodityIndex> QuantLib::EnergyVanillaSwap::index_ [protected]
Definition at line 67 of file energyvanillaswap.hpp.
Referenced by EnergyVanillaSwap(), index(), and performCalculations().
Handle<YieldTermStructure> QuantLib::EnergyVanillaSwap::payLegTermStructure_ [protected]
Definition at line 68 of file energyvanillaswap.hpp.
Referenced by performCalculations().
Integer QuantLib::EnergyVanillaSwap::payReceive_ [protected]
Definition at line 64 of file energyvanillaswap.hpp.
Referenced by payReceive(), and performCalculations().
Handle<YieldTermStructure> QuantLib::EnergyVanillaSwap::receiveLegTermStructure_ [protected]
Definition at line 69 of file energyvanillaswap.hpp.
Referenced by performCalculations().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/commodities/energyvanillaswap.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/commodities/energyvanillaswap.cpp