QuantLib: QuantLib::VolatilityTermStructure Class Reference
QuantLib::VolatilityTermStructure Class Reference
Volatility term structure.
#include <voltermstructure.hpp>
Public Member Functions
virtual BusinessDayConvention businessDayConvention () const
the business day convention used in tenor to date conversion
Date optionDateFromTenor (const Period &) const
period/date conversion
virtual Rate minStrike () const =0
the minimum strike for which the term structure can return vols
virtual Rate maxStrike () const =0
the maximum strike for which the term structure can return vols
Constructors
See the TermStructure documentation for issues regarding constructors.
VolatilityTermStructure (const Calendar &cal, BusinessDayConvention bdc, const DayCounter &dc=DayCounter())
VolatilityTermStructure (BusinessDayConvention bdc, const DayCounter &dc=DayCounter())
VolatilityTermStructure (const Date &referenceDate, const Calendar &cal, BusinessDayConvention bdc, const DayCounter &dc=DayCounter())
initialize with a fixed reference date
VolatilityTermStructure (Natural settlementDays, const Calendar &cal, BusinessDayConvention bdc, const DayCounter &dc=DayCounter())
calculate the reference date based on the global evaluation date
Protected Member Functions
void checkStrike (Rate strike, bool extrapolate) const
strike-range check
Private Attributes
BusinessDayConvention bdc_
Detailed Description
Volatility term structure.
This abstract class defines the interface of concrete volatility structures which will be derived from this one.
Definition at line 36 of file voltermstructure.hpp.
Constructor & Destructor Documentation
QuantLib::VolatilityTermStructure::VolatilityTermStructure (const Calendar & cal, BusinessDayConvention bdc, const DayCounter & dc = DayCounter())
Warning:
term structures initialized by means of this constructor must manage their own reference date by overriding the referenceDate() method.
Definition at line 25 of file voltermstructure.cpp.
References QuantLib::TermStructure::calendar_.
    : TermStructure(dc), bdc_(bdc) {
        calendar_ = cal;
    }
QuantLib::VolatilityTermStructure::VolatilityTermStructure (BusinessDayConvention bdc, const DayCounter & dc = DayCounter())
Warning:
term structures initialized by means of this constructor must manage their own reference date by overriding the referenceDate() method.
Definition at line 33 of file voltermstructure.cpp.
    : TermStructure(dc), bdc_(bdc) {}
QuantLib::VolatilityTermStructure::VolatilityTermStructure (const Date & referenceDate, const Calendar & cal, BusinessDayConvention bdc, const DayCounter & dc = DayCounter())
initialize with a fixed reference date
Definition at line 37 of file voltermstructure.cpp.
    : TermStructure(referenceDate, cal, dc), bdc_(bdc) {}
QuantLib::VolatilityTermStructure::VolatilityTermStructure (Natural settlementDays, const Calendar & cal, BusinessDayConvention bdc, const DayCounter & dc = DayCounter())
calculate the reference date based on the global evaluation date
Definition at line 43 of file voltermstructure.cpp.
    : TermStructure(settlementDays, cal, dc), bdc_(bdc) {}
Member Function Documentation
BusinessDayConvention QuantLib::VolatilityTermStructure::businessDayConvention () const [inline, virtual]
the business day convention used in tenor to date conversion
Reimplemented in QuantLib::SpreadedOptionletVolatility.
Definition at line 88 of file voltermstructure.hpp.
References bdc_.
Referenced by optionDateFromTenor().
{
        return bdc_;
    }
void QuantLib::VolatilityTermStructure::checkStrike (Rate strike, bool extrapolate) const [protected]
strike-range check
Definition at line 49 of file voltermstructure.cpp.
References QuantLib::Extrapolator::allowsExtrapolation(), maxStrike(), minStrike(), and QL_REQUIRE.
Referenced by QuantLib::BlackVolTermStructure::blackForwardVariance(), QuantLib::BlackVolTermStructure::blackForwardVol(), QuantLib::BlackVolTermStructure::blackVariance(), QuantLib::BlackVolTermStructure::blackVol(), QuantLib::LocalVolTermStructure::localVol(), QuantLib::CapFloorTermVolatilityStructure::volatility(), QuantLib::OptionletVolatilityStructure::volatility(), and QuantLib::SwaptionVolatilityStructure::volatility().
{
        QL_REQUIRE(extrapolate || allowsExtrapolation() ||
                   (k >= minStrike() && k <= maxStrike()),
                   "strike (" << k << ") is outside the curve domain ["
                   << minStrike() << "," << maxStrike()<< "]");
    }
virtual Rate QuantLib::VolatilityTermStructure::maxStrike () const [pure virtual]
the maximum strike for which the term structure can return vols
Implemented in QuantLib::ConstantYoYOptionletVolatility, QuantLib::CPIVolatilitySurface, QuantLib::YoYOptionletVolatilitySurface, QuantLib::SwaptionVolatilityMatrix, QuantLib::CapFloorTermVolCurve, QuantLib::CapFloorTermVolSurface, QuantLib::BlackVarianceSurface, QuantLib::InterpolatedYoYOptionletVolatilityCurve< Interpolator1D >, QuantLib::InterpolatedYoYOptionletVolatilityCurve< Interpolator >, QuantLib::AbcdAtmVolCurve, QuantLib::ConstantSwaptionVolatility, QuantLib::ConstantOptionletVolatility, QuantLib::ConstantCapFloorTermVolatility, QuantLib::BlackConstantVol, QuantLib::LocalVolSurface, QuantLib::KInterpolatedYoYOptionletVolatilitySurface< Interpolator1D >, QuantLib::LocalConstantVol, QuantLib::BlackVarianceCurve, QuantLib::SabrVolSurface, QuantLib::LocalVolCurve, QuantLib::SwaptionVolatilityCube, QuantLib::ExtendedBlackVarianceSurface, QuantLib::ImpliedVolTermStructure, QuantLib::ConstantCPIVolatility, QuantLib::StrippedOptionletAdapter, QuantLib::SpreadedSwaptionVolatility, QuantLib::ExtendedBlackVarianceCurve, QuantLib::CapletVarianceCurve, QuantLib::anonymous_namespace{analyticbsmhullwhiteengine.cpp}::ShiftedBlackVolTermStructure, and QuantLib::SpreadedOptionletVolatility.
Referenced by checkStrike().
virtual Rate QuantLib::VolatilityTermStructure::minStrike () const [pure virtual]
the minimum strike for which the term structure can return vols
Implemented in QuantLib::ConstantYoYOptionletVolatility, QuantLib::CPIVolatilitySurface, QuantLib::YoYOptionletVolatilitySurface, QuantLib::SwaptionVolatilityMatrix, QuantLib::CapFloorTermVolCurve, QuantLib::CapFloorTermVolSurface, QuantLib::BlackVarianceSurface, QuantLib::InterpolatedYoYOptionletVolatilityCurve< Interpolator1D >, QuantLib::AbcdAtmVolCurve, QuantLib::ConstantSwaptionVolatility, QuantLib::InterpolatedYoYOptionletVolatilityCurve< Interpolator >, QuantLib::ConstantOptionletVolatility, QuantLib::ConstantCapFloorTermVolatility, QuantLib::BlackConstantVol, QuantLib::LocalVolSurface, QuantLib::KInterpolatedYoYOptionletVolatilitySurface< Interpolator1D >, QuantLib::LocalConstantVol, QuantLib::BlackVarianceCurve, QuantLib::SabrVolSurface, QuantLib::SwaptionVolatilityCube, QuantLib::LocalVolCurve, QuantLib::ExtendedBlackVarianceSurface, QuantLib::ImpliedVolTermStructure, QuantLib::ConstantCPIVolatility, QuantLib::StrippedOptionletAdapter, QuantLib::SpreadedSwaptionVolatility, QuantLib::ExtendedBlackVarianceCurve, QuantLib::CapletVarianceCurve, QuantLib::anonymous_namespace{analyticbsmhullwhiteengine.cpp}::ShiftedBlackVolTermStructure, and QuantLib::SpreadedOptionletVolatility.
Referenced by checkStrike().
Date QuantLib::VolatilityTermStructure::optionDateFromTenor (const Period & p) const [inline]
period/date conversion
Reimplemented in QuantLib::InterestRateVolSurface.
Definition at line 93 of file voltermstructure.hpp.
References QuantLib::Calendar::advance(), businessDayConvention(), QuantLib::TermStructure::calendar(), and QuantLib::TermStructure::referenceDate().
Referenced by QuantLib::SwaptionVolatilityCube::atmStrike(), QuantLib::BlackAtmVolCurve::atmVariance(), QuantLib::BlackAtmVolCurve::atmVol(), QuantLib::OptionletVolatilityStructure::blackVariance(), QuantLib::SwaptionVolatilityStructure::blackVariance(), QuantLib::SwaptionVolatilityDiscrete::initializeOptionDatesAndTimes(), QuantLib::AbcdAtmVolCurve::initializeOptionDatesAndTimes(), QuantLib::CapFloorTermVolCurve::initializeOptionDatesAndTimes(), QuantLib::CapFloorTermVolSurface::initializeOptionDatesAndTimes(), QuantLib::AbcdAtmVolCurve::maxDate(), QuantLib::InterpolatedYoYOptionletVolatilityCurve< Interpolator >::maxDate(), QuantLib::CapFloorTermVolSurface::maxDate(), QuantLib::CapFloorTermVolCurve::maxDate(), QuantLib::BlackVolSurface::smileSection(), QuantLib::OptionletVolatilityStructure::smileSection(), QuantLib::SwaptionVolatilityStructure::smileSection(), QuantLib::CPIVolatilitySurface::totalVariance(), QuantLib::YoYOptionletVolatilitySurface::totalVariance(), QuantLib::CPIVolatilitySurface::volatility(), QuantLib::YoYOptionletVolatilitySurface::volatility(), QuantLib::CapFloorTermVolatilityStructure::volatility(), QuantLib::OptionletVolatilityStructure::volatility(), and QuantLib::SwaptionVolatilityStructure::volatility().
{
        // swaption style
        return calendar().advance(referenceDate(),
                                  p,
                                  businessDayConvention());
    }
Member Data Documentation
BusinessDayConvention QuantLib::VolatilityTermStructure::bdc_ [private]
Definition at line 82 of file voltermstructure.hpp.
Referenced by businessDayConvention().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/voltermstructure.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/voltermstructure.cpp