QuantLib: QuantLib::InverseNonCentralChiSquareDistribution Class Reference
QuantLib::InverseNonCentralChiSquareDistribution Class Reference
#include <chisquaredistribution.hpp>
Public Member Functions
InverseNonCentralChiSquareDistribution (Real df, Real ncp, Size maxEvaluations=10, Real accuracy=1e-8)
Real operator() (Real x) const
Private Attributes
NonCentralChiSquareDistribution nonCentralDist_
const Real guess_
const Size maxEvaluations_
const Real accuracy_
Detailed Description
Definition at line 51 of file chisquaredistribution.hpp.
Constructor & Destructor Documentation
QuantLib::InverseNonCentralChiSquareDistribution::InverseNonCentralChiSquareDistribution (Real df, Real ncp, Size maxEvaluations = 10, Real accuracy = 1e-8)
Definition at line 94 of file chisquaredistribution.cpp.
    : nonCentralDist_(df, ncp),
      guess_(df+ncp),
      maxEvaluations_(maxEvaluations),
      accuracy_(accuracy) {
    }
Member Function Documentation
Real QuantLib::InverseNonCentralChiSquareDistribution::operator() (Real x) const
Definition at line 103 of file chisquaredistribution.cpp.
References accuracy_, QuantLib::compose(), guess_, maxEvaluations_, nonCentralDist_, QuantLib::Solver1D< Impl >::setMaxEvaluations(), and QuantLib::Solver1D< Impl >::solve().
{
        // first find the right side of the interval
        Real upper = guess_;
        Size evaluations = maxEvaluations_;
        while (nonCentralDist_(upper) < x && evaluations > 0) {
            upper*=2.0;
            --evaluations;
        }
        // use a brent solver for the rest
        Brent solver;
        solver.setMaxEvaluations(evaluations);
        return solver.solve(compose(std::bind2nd(std::minus<Real>(),x),
                                    nonCentralDist_),
                            accuracy_, 0.75*upper,
                            (evaluations == maxEvaluations_)? 0.0: 0.5*upper,
                            upper);
    }
Member Data Documentation
const Real QuantLib::InverseNonCentralChiSquareDistribution::accuracy_ [private]
Definition at line 63 of file chisquaredistribution.hpp.
Referenced by operator()().
const Real QuantLib::InverseNonCentralChiSquareDistribution::guess_ [private]
Definition at line 61 of file chisquaredistribution.hpp.
Referenced by operator()().
const Size QuantLib::InverseNonCentralChiSquareDistribution::maxEvaluations_ [private]
Definition at line 62 of file chisquaredistribution.hpp.
Referenced by operator()().
NonCentralChiSquareDistribution QuantLib::InverseNonCentralChiSquareDistribution::nonCentralDist_ [private]
Definition at line 60 of file chisquaredistribution.hpp.
Referenced by operator()().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/distributions/chisquaredistribution.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/math/distributions/chisquaredistribution.cpp