QuantLib: QuantLib::CashFlow Class Reference
QuantLib::CashFlow Class Reference
Base class for cash flows.
#include <cashflow.hpp>
Public Member Functions
virtual ~CashFlow ()
Event interface
virtual Date date () const =0
bool hasOccurred (const Date &refDate=Date(), boost::optional< bool > includeRefDate=boost::none) const
returns true if an event has already occurred before a date
CashFlow interface
virtual Real amount () const =0
returns the amount of the cash flow
Visitability
virtual void accept (AcyclicVisitor &)
Detailed Description
Base class for cash flows.
This class is purely virtual and acts as a base class for the actual cash flow implementations.
Definition at line 39 of file cashflow.hpp.
Constructor & Destructor Documentation
virtual QuantLib::CashFlow::~CashFlow () [inline, virtual]
Definition at line 41 of file cashflow.hpp.
{}
Member Function Documentation
void QuantLib::CashFlow::accept (AcyclicVisitor & v) [virtual]
Reimplemented from QuantLib::Event.
Reimplemented in QuantLib::CappedFlooredCmsCoupon, QuantLib::DigitalCoupon, QuantLib::CappedFlooredIborCoupon, QuantLib::CappedFlooredYoYInflationCoupon, QuantLib::CPICoupon, QuantLib::FloatingRateCoupon, QuantLib::InflationCoupon, QuantLib::CappedFlooredCoupon, QuantLib::SubPeriodsCoupon, QuantLib::Coupon, QuantLib::AmortizingPayment, QuantLib::RangeAccrualFloatersCoupon, QuantLib::CommodityCashFlow, QuantLib::AverageBMACoupon, QuantLib::IndexedCashFlow, QuantLib::FixedRateCoupon, QuantLib::OvernightIndexedCoupon, QuantLib::Redemption, QuantLib::YoYInflationCoupon, QuantLib::IborCoupon, QuantLib::CmsCoupon, QuantLib::DigitalCmsCoupon, QuantLib::DigitalIborCoupon, QuantLib::Dividend, and QuantLib::SimpleCashFlow.
Definition at line 49 of file cashflow.cpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Visitor< T >::visit().
Referenced by QuantLib::CashFlows::npvbps().
{
        Visitor<CashFlow>* v1 = dynamic_cast<Visitor<CashFlow>*>(&v);
        if (v1 != 0)
            v1->visit(*this);
        else
            Event::accept(v);
    }
virtual Real QuantLib::CashFlow::amount () const [pure virtual]
returns the amount of the cash flow
Note:
The amount is not discounted, i.e., it is the actual amount paid at the cash flow date.
Implemented in QuantLib::CPICashFlow, QuantLib::FractionalDividend, QuantLib::IndexedCashFlow, QuantLib::FixedDividend, QuantLib::InflationCoupon, QuantLib::FloatingRateCoupon, QuantLib::FixedRateCoupon, QuantLib::CommodityCashFlow, QuantLib::Dividend, and QuantLib::SimpleCashFlow.
Referenced by QuantLib::collectNodeData(), QuantLib::LongstaffSchwartzExerciseStrategy::exercise(), and QuantLib::CashFlows::npvbps().
virtual Date QuantLib::CashFlow::date () const [pure virtual]
Note:
This is inherited from the event class
Implements QuantLib::Event.
Implemented in QuantLib::IndexedCashFlow, QuantLib::Coupon, QuantLib::CommodityCashFlow, QuantLib::Dividend, and QuantLib::SimpleCashFlow.
Referenced by hasOccurred(), QuantLib::CashFlows::npvbps(), and QuantLib::earlier_than< CashFlow >::operator()().
bool QuantLib::CashFlow::hasOccurred (const Date & refDate = Date(), boost::optional< bool > includeRefDate = boost::none) const [virtual]
returns true if an event has already occurred before a date
overloads Event::hasOccurred in order to take QL_TODAYS_PAYMENTS in account
Reimplemented from QuantLib::Event.
Definition at line 25 of file cashflow.cpp.
References date(), QuantLib::Settings::includeTodaysCashFlows(), and QuantLib::Singleton< Settings >::instance().
Referenced by QuantLib::CashFlows::npvbps().
{
        // easy and quick handling of most cases
        if (refDate != Date()) {
            Date cf = date();
            if (refDate < cf)
                return false;
            if (cf < refDate)
                return true;
        }
        if (refDate == Date() ||
            refDate == Settings::instance().evaluationDate()) {
            // today's date; we override the bool with the one
            // specified in the settings (if any)
            boost::optional<bool> includeToday =
                Settings::instance().includeTodaysCashFlows();
            if (includeToday)
                includeRefDate = *includeToday;
        }
        return Event::hasOccurred(refDate, includeRefDate);
    }
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflow.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflow.cpp