QuantLib: PeriodTest Class Reference
PeriodTest Class Reference
#include <period.hpp>
Static Public Member Functions
static void testYearsMonthsAlgebra ()
static void testWeeksDaysAlgebra ()
static
boost::unit_test_framework::test_suite * suite ()
Detailed Description
Definition at line 28 of file period.hpp.
Member Function Documentation
test_suite * PeriodTest::suite () [static]
Definition at line 135 of file period.cpp.
References QUANTLIB_TEST_CASE, testWeeksDaysAlgebra(), and testYearsMonthsAlgebra().
Referenced by init_unit_test_suite().
{
    test_suite* suite = BOOST_TEST_SUITE("Period tests");
    suite->add(QUANTLIB_TEST_CASE(&PeriodTest::testYearsMonthsAlgebra));
    suite->add(QUANTLIB_TEST_CASE(&PeriodTest::testWeeksDaysAlgebra));
    return suite;
}
void PeriodTest::testWeeksDaysAlgebra () [static]
Definition at line 80 of file period.cpp.
References QuantLib::Days, QuantLib::Period::length(), QuantLib::Period::normalize(), QuantLib::Period::units(), and QuantLib::Weeks.
Referenced by suite().
{
    BOOST_MESSAGE("Testing period algebra on weeks/days...");
    Period TwoWeeks(2, Weeks);
    Period OneWeek(1, Weeks);
    Period ThreeDays(3, Days);
    Period OneDay(1, Days);
    Integer n = 2;
    if (TwoWeeks/n!=OneWeek)
        BOOST_ERROR("division error: " << TwoWeeks << "/" << n <<
                    " not equal to " << OneWeek);
    n = 7;
    if (OneWeek/n!=OneDay)
        BOOST_ERROR("division error: " << OneWeek << "/" << n <<
                    " not equal to " << OneDay);
    Period sum=ThreeDays;
    sum+=OneDay;
    if (sum!=Period(4, Days))
        BOOST_ERROR("sum error: " << ThreeDays <<
                    " + " << OneDay <<
                    " != " << Period(4, Days));
    sum+=OneWeek;
    if (sum!=Period(11, Days))
        BOOST_ERROR("sum error: " << ThreeDays <<
                    " + " << OneDay <<
                    " + " << OneWeek <<
                    " != " << Period(11, Days));
    Period SevenDays(7, Days);
    if (SevenDays.length()!=7)
        BOOST_ERROR("normalization error: SevenDays.length()" <<
                    " is " << SevenDays.length() <<
                    " instead of 7");
    if (SevenDays.units()!=Days)
        BOOST_ERROR("normalization error: SevenDays.units()" <<
                    " is " << SevenDays.units() <<
                    " instead of " << Days);
    Period NormalizedSevenDays(7, Days);
    NormalizedSevenDays.normalize();
    if (NormalizedSevenDays.length()!=1)
        BOOST_ERROR("normalization error: NormalizedSevenDays.length()" <<
                    " is " << NormalizedSevenDays.length() <<
                    " instead of 1");
    if (NormalizedSevenDays.units()!=Weeks)
        BOOST_ERROR("normalization error: NormalizedSevenDays.units()" <<
                    " is " << NormalizedSevenDays.units() <<
                    " instead of " << Weeks);
}
void PeriodTest::testYearsMonthsAlgebra () [static]
Definition at line 27 of file period.cpp.
References QuantLib::Period::length(), QuantLib::Months, QuantLib::Period::normalize(), QuantLib::Period::units(), and QuantLib::Years.
Referenced by suite().
{
    BOOST_MESSAGE("Testing period algebra on years/months...");
    Period OneYear(1, Years);
    Period SixMonths(6, Months);
    Period ThreeMonths(3, Months);
    Integer n = 4;
    if (OneYear/n!=ThreeMonths)
        BOOST_ERROR("division error: " << OneYear << "/" << n <<
                    " not equal to " << ThreeMonths);
    n = 2;
    if (OneYear/n!=SixMonths)
        BOOST_ERROR("division error: " << OneYear << "/" << n <<
                    " not equal to " << SixMonths);
    Period sum=ThreeMonths;
    sum+=SixMonths;
    if (sum!=Period(9, Months))
        BOOST_ERROR("sum error: " << ThreeMonths <<
                    " + " << SixMonths <<
                    " != " << Period(9, Months));
    sum+=OneYear;
    if (sum!=Period(21, Months))
        BOOST_ERROR("sum error: " << ThreeMonths <<
                    " + " << SixMonths <<
                    " + " << OneYear <<
                    " != " << Period(21, Months));
    Period TwelveMonths(12, Months);
    if (TwelveMonths.length()!=12)
        BOOST_ERROR("normalization error: TwelveMonths.length()" <<
                    " is " << TwelveMonths.length() <<
                    " instead of 12");
    if (TwelveMonths.units()!=Months)
        BOOST_ERROR("normalization error: TwelveMonths.units()" <<
                    " is " << TwelveMonths.units() <<
                    " instead of " << Months);
    Period NormalizedTwelveMonths(12, Months);
    NormalizedTwelveMonths.normalize();
    if (NormalizedTwelveMonths.length()!=1)
        BOOST_ERROR("normalization error: NormalizedTwelveMonths.length()" <<
                    " is " << NormalizedTwelveMonths.length() <<
                    " instead of 1");
    if (NormalizedTwelveMonths.units()!=Years)
        BOOST_ERROR("normalization error: NormalizedTwelveMonths.units()" <<
                    " is " << NormalizedTwelveMonths.units() <<
                    " instead of " << Years);
}
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/period.hpp
/home/deriversatile/QuantLib/QuantLibQt/test-suite/period.cpp