QuantLib: QuantLib::FdmExtendedOrnsteinUhlenbackOp Class Reference
QuantLib::FdmExtendedOrnsteinUhlenbackOp Class Reference
#include <fdmextendedornsteinuhlenbeckop.hpp>
Public Member Functions
FdmExtendedOrnsteinUhlenbackOp (const boost::shared_ptr< FdmMesher > &mesher, const boost::shared_ptr< ExtendedOrnsteinUhlenbeckProcess > &p, const boost::shared_ptr< YieldTermStructure > &rTS, const FdmBoundaryConditionSet &bcSet, Size direction=0)
Size size () const
void setTime (Time t1, Time t2)
Time \(t1 <= t2\) is required.
Disposable< Array > apply (const Array &r) const
Disposable< Array > apply_mixed (const Array &r) const
Disposable< Array > apply_direction (Size direction, const Array &r) const
Disposable< Array > solve_splitting (Size direction, const Array &r, Real s) const
Disposable< Array > preconditioner (const Array &r, Real s) const
Disposable< SparseMatrix > toMatrix () const
Private Attributes
const boost::shared_ptr
< FdmMesher > mesher_
const boost::shared_ptr
< ExtendedOrnsteinUhlenbeckProcess > process_
const boost::shared_ptr
< YieldTermStructure > rTS_
const FdmBoundaryConditionSet bcSet_
const Size direction_
const Array x_
const FirstDerivativeOp dxMap_
const TripleBandLinearOp dxxMap_
TripleBandLinearOp mapX_
Detailed Description
Definition at line 39 of file fdmextendedornsteinuhlenbeckop.hpp.
Constructor & Destructor Documentation
QuantLib::FdmExtendedOrnsteinUhlenbackOp::FdmExtendedOrnsteinUhlenbackOp (const boost::shared_ptr< FdmMesher > & mesher, const boost::shared_ptr< ExtendedOrnsteinUhlenbeckProcess > & p, const boost::shared_ptr< YieldTermStructure > & rTS, const FdmBoundaryConditionSet & bcSet, Size direction = 0)
Definition at line 34 of file fdmextendedornsteinuhlenbeckop.cpp.
    : mesher_   (mesher),
      process_  (process),
      rTS_      (rTS),
      bcSet_    (bcSet),
      direction_(direction),
      x_        (mesher->locations(direction)),
      dxMap_    (direction, mesher),
      dxxMap_   (SecondDerivativeOp(direction, mesher)
                .mult(0.5*square<Real>()(process_->volatility())
                  *Array(mesher->layout()->size(), 1.))),
      mapX_     (direction, mesher) {
    }
Member Function Documentation
Disposable< Array > QuantLib::FdmExtendedOrnsteinUhlenbackOp::apply (const Array & r) const [virtual]
Implements QuantLib::FdmLinearOp.
Definition at line 72 of file fdmextendedornsteinuhlenbeckop.cpp.
References QuantLib::TripleBandLinearOp::apply(), and mapX_.
{
        return mapX_.apply(r);
    }
Disposable< Array > QuantLib::FdmExtendedOrnsteinUhlenbackOp::apply_direction (Size direction, const Array & r) const [virtual]
Implements QuantLib::FdmLinearOpComposite.
Definition at line 83 of file fdmextendedornsteinuhlenbeckop.cpp.
References QuantLib::TripleBandLinearOp::apply(), direction_, mapX_, and QuantLib::Array::size().
{
        if (direction == direction_) {
            return mapX_.apply(r);
        }
        else {
            Array retVal(r.size(), 0.0);
            return retVal;
        }
    }
Disposable< Array > QuantLib::FdmExtendedOrnsteinUhlenbackOp::apply_mixed (const Array & r) const [virtual]
Implements QuantLib::FdmLinearOpComposite.
Definition at line 77 of file fdmextendedornsteinuhlenbeckop.cpp.
References QuantLib::Array::size().
{
        Array retVal(r.size(), 0.0);
        return retVal;
    }
Disposable< Array > QuantLib::FdmExtendedOrnsteinUhlenbackOp::preconditioner (const Array & r, Real s) const [virtual]
Implements QuantLib::FdmLinearOpComposite.
Definition at line 105 of file fdmextendedornsteinuhlenbeckop.cpp.
References direction_, and solve_splitting().
{
        return solve_splitting(direction_, r, dt);
    }
void QuantLib::FdmExtendedOrnsteinUhlenbackOp::setTime (Time t1, Time t2) [virtual]
Time \(t1 <= t2\) is required.
Implements QuantLib::FdmLinearOpComposite.
Definition at line 57 of file fdmextendedornsteinuhlenbeckop.cpp.
References QuantLib::TripleBandLinearOp::axpyb(), QuantLib::Continuous, dxMap_, dxxMap_, mapX_, mesher_, process_, rTS_, and x_.
{
        const Rate r = rTS_->forwardRate(t1, t2, Continuous).rate();
        const boost::shared_ptr<FdmLinearOpLayout> layout=mesher_->layout();
        const FdmLinearOpIterator endIter = layout->end();
        Array drift(layout->size());
        for (FdmLinearOpIterator iter = layout->begin();
             iter!=endIter; ++iter) {
            const Size i = iter.index();
            drift[i] = process_->drift(0.5*(t1+t2), x_[i]);
        }
        mapX_.axpyb(drift, dxMap_, dxxMap_, Array(1, -r));
    }
Size QuantLib::FdmExtendedOrnsteinUhlenbackOp::size () const [virtual]
Implements QuantLib::FdmLinearOpComposite.
Definition at line 53 of file fdmextendedornsteinuhlenbeckop.cpp.
References mesher_.
{
        return mesher_->layout()->dim().size();;
    }
Disposable< Array > QuantLib::FdmExtendedOrnsteinUhlenbackOp::solve_splitting (Size direction, const Array & r, Real s) const [virtual]
Implements QuantLib::FdmLinearOpComposite.
Definition at line 94 of file fdmextendedornsteinuhlenbeckop.cpp.
References direction_, mapX_, and QuantLib::TripleBandLinearOp::solve_splitting().
Referenced by preconditioner().
{
        if (direction == direction_) {
            return mapX_.solve_splitting(r, a, 1.0);
        }
        else {
            Array retVal(r);
            return retVal;
        }
    }
Disposable< SparseMatrix > QuantLib::FdmExtendedOrnsteinUhlenbackOp::toMatrix () const [virtual]
Reimplemented from QuantLib::FdmLinearOp.
Definition at line 111 of file fdmextendedornsteinuhlenbeckop.cpp.
References mapX_, and QuantLib::TripleBandLinearOp::toMatrix().
{
        return mapX_.toMatrix();
    }
Member Data Documentation
const FdmBoundaryConditionSet QuantLib::FdmExtendedOrnsteinUhlenbackOp::bcSet_ [private]
Definition at line 67 of file fdmextendedornsteinuhlenbeckop.hpp.
const Size QuantLib::FdmExtendedOrnsteinUhlenbackOp::direction_ [private]
Definition at line 68 of file fdmextendedornsteinuhlenbeckop.hpp.
Referenced by apply_direction(), preconditioner(), and solve_splitting().
const FirstDerivativeOp QuantLib::FdmExtendedOrnsteinUhlenbackOp::dxMap_ [private]
Definition at line 71 of file fdmextendedornsteinuhlenbeckop.hpp.
Referenced by setTime().
const TripleBandLinearOp QuantLib::FdmExtendedOrnsteinUhlenbackOp::dxxMap_ [private]
Definition at line 72 of file fdmextendedornsteinuhlenbeckop.hpp.
Referenced by setTime().
TripleBandLinearOp QuantLib::FdmExtendedOrnsteinUhlenbackOp::mapX_ [private]
Definition at line 73 of file fdmextendedornsteinuhlenbeckop.hpp.
Referenced by apply(), apply_direction(), setTime(), solve_splitting(), and toMatrix().
const boost::shared_ptr<FdmMesher> QuantLib::FdmExtendedOrnsteinUhlenbackOp::mesher_ [private]
Definition at line 64 of file fdmextendedornsteinuhlenbeckop.hpp.
Referenced by setTime(), and size().
const boost::shared_ptr<ExtendedOrnsteinUhlenbeckProcess> QuantLib::FdmExtendedOrnsteinUhlenbackOp::process_ [private]
Definition at line 65 of file fdmextendedornsteinuhlenbeckop.hpp.
Referenced by setTime().
const boost::shared_ptr<YieldTermStructure> QuantLib::FdmExtendedOrnsteinUhlenbackOp::rTS_ [private]
Definition at line 66 of file fdmextendedornsteinuhlenbeckop.hpp.
Referenced by setTime().
const Array QuantLib::FdmExtendedOrnsteinUhlenbackOp::x_ [private]
Definition at line 70 of file fdmextendedornsteinuhlenbeckop.hpp.
Referenced by setTime().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/finitedifferences/fdmextendedornsteinuhlenbeckop.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/finitedifferences/fdmextendedornsteinuhlenbeckop.cpp