QuantLib: QuantLib::MarketModelCashRebate Class Reference
QuantLib::MarketModelCashRebate Class Reference
#include <cashrebate.hpp>
Public Member Functions
MarketModelCashRebate (const EvolutionDescription &evolution, const std::vector< Time > &paymentTimes, const Matrix &amounts, Size numberOfProducts)
MarketModelMultiProduct interface
std::vector< Size > suggestedNumeraires () const
const EvolutionDescription & evolution () const
std::vector< Time > possibleCashFlowTimes () const
Size numberOfProducts () const
Size maxNumberOfCashFlowsPerProductPerStep () const
void reset ()
during simulation put product at start of path
bool nextTimeStep (const CurveState &currentState, std::vector< Size > &numberCashFlowsThisStep, std::vector< std::vector< CashFlow > > &cashFlowsGenerated)
return value indicates whether path is finished, TRUE means done
std::auto_ptr
< MarketModelMultiProduct > clone () const
returns a newly-allocated copy of itself
Private Attributes
EvolutionDescription evolution_
std::vector< Time > paymentTimes_
Matrix amounts_
Size numberOfProducts_
Size currentIndex_
Detailed Description
Class to model receipt of a fixed cash amount once. Product terminates immediately. Mainly useful as rebate received when another product is cancelled.
Definition at line 36 of file cashrebate.hpp.
Constructor & Destructor Documentation
QuantLib::MarketModelCashRebate::MarketModelCashRebate (const EvolutionDescription & evolution, const std::vector< Time > & paymentTimes, const Matrix & amounts, Size numberOfProducts)
Definition at line 25 of file cashrebate.cpp.
References amounts_, QuantLib::checkIncreasingTimes(), QuantLib::Matrix::columns(), evolution_, QuantLib::EvolutionDescription::evolutionTimes(), numberOfProducts_, paymentTimes_, QL_REQUIRE, and QuantLib::Matrix::rows().
Referenced by clone().
    : evolution_(evolution), paymentTimes_(paymentTimes),
      amounts_(amounts), numberOfProducts_(numberOfProducts)
    {
        checkIncreasingTimes(paymentTimes);
        QL_REQUIRE(amounts_.rows() == numberOfProducts_,
                   "the number of rows in the matrix must equal "
                   "the number of products");
        QL_REQUIRE(amounts_.columns() == paymentTimes_.size(),
                   "the number of columns in the matrix must equal "
                   "the number of payment times");
        QL_REQUIRE(evolution_.evolutionTimes().size() == paymentTimes_.size(),
                   "the number of evolution times must equal "
                   "the number of payment times");
    }
Member Function Documentation
std::auto_ptr< MarketModelMultiProduct > QuantLib::MarketModelCashRebate::clone () const [virtual]
returns a newly-allocated copy of itself
Implements QuantLib::MarketModelMultiProduct.
Definition at line 98 of file cashrebate.cpp.
References MarketModelCashRebate().
    {
        return std::auto_ptr<MarketModelMultiProduct>(
                                            new MarketModelCashRebate(*this));
    }
const EvolutionDescription & QuantLib::MarketModelCashRebate::evolution () const [virtual]
Implements QuantLib::MarketModelMultiProduct.
Definition at line 75 of file cashrebate.cpp.
References evolution_.
    {
        return evolution_;
    }
Size QuantLib::MarketModelCashRebate::maxNumberOfCashFlowsPerProductPerStep () const [virtual]
Implements QuantLib::MarketModelMultiProduct.
Definition at line 59 of file cashrebate.cpp.
    {
        return 1;
    }
bool QuantLib::MarketModelCashRebate::nextTimeStep (const CurveState & currentState, std::vector< Size > & numberCashFlowsThisStep, std::vector< std::vector< CashFlow > > & cashFlowsGenerated) [virtual]
return value indicates whether path is finished, TRUE means done
Implements QuantLib::MarketModelMultiProduct.
Definition at line 81 of file cashrebate.cpp.
References amounts_, currentIndex_, and numberOfProducts_.
    {
        for (Size i=0; i<numberOfProducts_; ++i)
        {
            numberCashFlowsThisStep[i] = 1;
            genCashFlows[i][0].timeIndex = currentIndex_;
            genCashFlows[i][0].amount = amounts_[i][currentIndex_];
        }
        ++currentIndex_;
        return true;
    }
Size QuantLib::MarketModelCashRebate::numberOfProducts () const [virtual]
Implements QuantLib::MarketModelMultiProduct.
Definition at line 54 of file cashrebate.cpp.
References numberOfProducts_.
    {
        return numberOfProducts_;
    }
std::vector< Time > QuantLib::MarketModelCashRebate::possibleCashFlowTimes () const [virtual]
Implements QuantLib::MarketModelMultiProduct.
Definition at line 49 of file cashrebate.cpp.
References paymentTimes_.
    {
        return paymentTimes_;
    }
void QuantLib::MarketModelCashRebate::reset () [virtual]
during simulation put product at start of path
Implements QuantLib::MarketModelMultiProduct.
Definition at line 64 of file cashrebate.cpp.
References currentIndex_.
    {
       currentIndex_=0;
    }
std::vector< Size > QuantLib::MarketModelCashRebate::suggestedNumeraires () const [virtual]
Implements QuantLib::MarketModelMultiProduct.
Definition at line 70 of file cashrebate.cpp.
References QL_FAIL.
    {
        QL_FAIL("not implemented (yet?)");
    }
Member Data Documentation
Matrix QuantLib::MarketModelCashRebate::amounts_ [private]
Definition at line 60 of file cashrebate.hpp.
Referenced by MarketModelCashRebate(), and nextTimeStep().
Size QuantLib::MarketModelCashRebate::currentIndex_ [private]
Definition at line 63 of file cashrebate.hpp.
Referenced by nextTimeStep(), and reset().
EvolutionDescription QuantLib::MarketModelCashRebate::evolution_ [private]
Definition at line 58 of file cashrebate.hpp.
Referenced by evolution(), and MarketModelCashRebate().
Size QuantLib::MarketModelCashRebate::numberOfProducts_ [private]
Definition at line 61 of file cashrebate.hpp.
Referenced by MarketModelCashRebate(), nextTimeStep(), and numberOfProducts().
std::vector<Time> QuantLib::MarketModelCashRebate::paymentTimes_ [private]
Definition at line 59 of file cashrebate.hpp.
Referenced by MarketModelCashRebate(), and possibleCashFlowTimes().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/products/multistep/cashrebate.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/products/multistep/cashrebate.cpp