QuantLib: QuantLib::Histogram Class Reference
QuantLib::Histogram Class Reference
Histogram class.
#include <histogram.hpp>
Public Types
enum Algorithm { None, Sturges, FD, Scott }
Public Member Functions
constructors
Histogram ()
template<class T >
Histogram (T data_begin, T data_end, Size breaks)
template<class T >
Histogram (T data_begin, T data_end, Algorithm algorithm)
template<class T , class U >
Histogram (T data_begin, T data_end, U breaks_begin, U breaks_end)
inspectors
Size bins () const
const std::vector< Real > & breaks () const
Algorithm algorithm () const
bool empty () const
results
Size counts (Size i) const
Real frequency (Size i) const
Private Member Functions
void calculate ()
Private Attributes
std::vector< Real > data_
Size bins_
Algorithm algorithm_
std::vector< Real > breaks_
std::vector< Size > counts_
std::vector< Real > frequency_
Detailed Description
Histogram class.
This class computes the histogram of a given data set. The caller can specify the number of bins, the breaks, or the algorithm for determining these quantities in computing the histogram.
Definition at line 38 of file histogram.hpp.
Member Enumeration Documentation
enum QuantLib::Histogram::Algorithm
Enumerator:
None
Sturges
FD
Scott
Definition at line 40 of file histogram.hpp.
{ None, Sturges, FD, Scott };
Constructor & Destructor Documentation
QuantLib::Histogram::Histogram () [inline]
Definition at line 44 of file histogram.hpp.
        : bins_(0), algorithm_(Algorithm(-1)) {}
template<class T > QuantLib::Histogram::Histogram (T data_begin, T data_end, Size breaks) [inline]
Definition at line 48 of file histogram.hpp.
References calculate().
        : data_(data_begin,data_end), bins_(breaks+1),
          algorithm_(None) {
            calculate();
        }
template<class T > QuantLib::Histogram::Histogram (T data_begin, T data_end, Algorithm algorithm) [inline]
Definition at line 55 of file histogram.hpp.
References calculate().
        : data_(data_begin,data_end), bins_(Null<Size>()),
          algorithm_(algorithm) {
            calculate();
        }
template<class T , class U > QuantLib::Histogram::Histogram (T data_begin, T data_end, U breaks_begin, U breaks_end) [inline]
Definition at line 62 of file histogram.hpp.
References bins_, breaks_, and calculate().
        : data_(data_begin,data_end), bins_(Null<Size>()),
          algorithm_(None), breaks_(breaks_begin,breaks_end) {
            bins_ = breaks_.size()+1;
            calculate();
        }
Member Function Documentation
Histogram::Algorithm QuantLib::Histogram::algorithm () const
Definition at line 75 of file histogram.cpp.
References algorithm_.
{
        return algorithm_;
    }
Size QuantLib::Histogram::bins () const
Definition at line 67 of file histogram.cpp.
References bins_.
{
        return bins_;
    }
const std::vector< Real > & QuantLib::Histogram::breaks () const
Definition at line 71 of file histogram.cpp.
References breaks_.
{
        return breaks_;
    }
void QuantLib::Histogram::calculate () [private]
Definition at line 99 of file histogram.cpp.
References QuantLib::IncrementalStatistics::addSequence(), algorithm_, bins_, breaks_, QuantLib::close_enough(), counts_, data_, FD, frequency_, None, QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow(), QL_FAIL, QL_REQUIRE, QuantLib::anonymous_namespace{histogram.cpp}::quantile(), Scott, Sturges, and QuantLib::IncrementalStatistics::variance().
Referenced by Histogram().
{
        QL_REQUIRE(!data_.empty(), "no data given");
        Real min = *std::min_element(data_.begin(), data_.end());
        Real max = *std::max_element(data_.begin(), data_.end());
        // calculate number of bins if necessary
        if (bins_ == Null<Size>()) {
            switch (algorithm_) {
              case Sturges: {
                  bins_ = static_cast<Size>(
                           std::ceil(std::log(static_cast<Real>(data_.size()))
                                     /std::log(2.0) + 1));
                  break;
              }
              case FD: {
                  Real r1 = quantile(data_, 0.25);
                  Real r2 = quantile(data_, 0.75);
                  Real h = 2.0 * (r2-r1) * std::pow(static_cast<Real>(data_.size()), -1.0/3.0);
                  bins_ = static_cast<Size>(std::ceil((max-min)/h));
                  break;
              }
              case Scott: {
                  IncrementalStatistics summary;
                  summary.addSequence(data_.begin(), data_.end());
                  Real variance = summary.variance();
                  Real h = 3.5 * std::sqrt(variance)
                         * std::pow(static_cast<Real>(data_.size()), -1.0/3.0);
                  bins_ = static_cast<Size>(std::ceil((max-min)/h));
                  break;
              }
              case None:
                QL_FAIL("a bin-partition algorithm is required");
              default:
                QL_FAIL("unknown bin-partition algorithm");
            };
            bins_ = std::max<Size>(bins_,1);
        }
        if (breaks_.empty()) {
            // set breaks if not provided
            breaks_.resize(bins_-1);
            // ensure breaks_ evenly span over the range of data_
            // TODO: borrow the idea of pretty in R.
            Real h = (max-min)/bins_;
            for (Size i=0; i<breaks_.size(); ++i) {
                breaks_[i] = min + (i+1)*h;
            }
        } else {
            // or ensure they're sorted if given
            std::sort(breaks_.begin(), breaks_.end());
            std::vector<Real>::iterator end =
                std::unique(breaks_.begin(),breaks_.end(),
                            std::ptr_fun(close_enough));
            breaks_.resize(end - breaks_.begin());
        }
        // finally, calculate counts and frequencies
        counts_.resize(bins_);
        std::fill(counts_.begin(), counts_.end(), 0);
        for (std::vector<Real>::const_iterator p = data_.begin();
             p != data_.end(); ++p) {
            bool processed = false;
            for (Size i=0; i<breaks_.size(); ++i) {
                if (*p < breaks_[i]) {
                    ++counts_[i];
                    processed = true;
                    break;
                }
            }
            if (!processed)
                ++counts_[bins_-1];
        }
        frequency_.resize(bins_);
        Size totalCounts = data_.size();
        for (Size i=0; i<bins_; ++i)
            frequency_[i] = static_cast<Real>(counts_[i])/totalCounts;
    }
Size QuantLib::Histogram::counts (Size i) const
Definition at line 83 of file histogram.cpp.
References counts_.
{
        #if defined(QL_EXTRA_SAFETY_CHECKS)
        return counts_.at(i);
        #else
        return counts_[i];
        #endif
    }
bool QuantLib::Histogram::empty () const
Definition at line 79 of file histogram.cpp.
References bins_.
{
        return bins_ == 0;
    }
Real QuantLib::Histogram::frequency (Size i) const
Definition at line 91 of file histogram.cpp.
References frequency_.
{
        #if defined(QL_EXTRA_SAFETY_CHECKS)
        return frequency_.at(i);
        #else
        return frequency_[i];
        #endif
    }
Member Data Documentation
Algorithm QuantLib::Histogram::algorithm_ [private]
Definition at line 87 of file histogram.hpp.
Referenced by algorithm(), and calculate().
Size QuantLib::Histogram::bins_ [private]
Definition at line 86 of file histogram.hpp.
Referenced by bins(), calculate(), empty(), and Histogram().
std::vector<Real> QuantLib::Histogram::breaks_ [private]
Definition at line 88 of file histogram.hpp.
Referenced by breaks(), calculate(), and Histogram().
std::vector<Size> QuantLib::Histogram::counts_ [private]
Definition at line 89 of file histogram.hpp.
Referenced by calculate(), and counts().
std::vector<Real> QuantLib::Histogram::data_ [private]
Definition at line 85 of file histogram.hpp.
Referenced by calculate().
std::vector<Real> QuantLib::Histogram::frequency_ [private]
Definition at line 90 of file histogram.hpp.
Referenced by calculate(), and frequency().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/statistics/histogram.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/math/statistics/histogram.cpp