QuantLib: QuantLib::BlackVolatilityTermStructure Class Reference
QuantLib::BlackVolatilityTermStructure Class Reference
Black-volatility term structure.
#include <blackvoltermstructure.hpp>
Public Member Functions
Constructors
See the TermStructure documentation for issues regarding constructors.
BlackVolatilityTermStructure (const Calendar &cal, BusinessDayConvention bdc=Following, const DayCounter &dc=DayCounter())
BlackVolatilityTermStructure (BusinessDayConvention bdc=Following, const DayCounter &dc=DayCounter())
default constructor
BlackVolatilityTermStructure (const Date &referenceDate, const Calendar &cal=Calendar(), BusinessDayConvention bdc=Following, const DayCounter &dc=DayCounter())
initialize with a fixed reference date
BlackVolatilityTermStructure (Natural settlementDays, const Calendar &cal, BusinessDayConvention bdc=Following, const DayCounter &dc=DayCounter())
calculate the reference date based on the global evaluation date
Visitability
virtual void accept (AcyclicVisitor &)
Protected Member Functions
Real blackVarianceImpl (Time maturity, Real strike) const
Detailed Description
Black-volatility term structure.
This abstract class acts as an adapter to BlackVolTermStructure allowing the programmer to implement only the blackVolImpl(Time, Real, bool) method in derived classes.
Volatility are assumed to be expressed on an annual basis.
Definition at line 143 of file blackvoltermstructure.hpp.
Constructor & Destructor Documentation
QuantLib::BlackVolatilityTermStructure::BlackVolatilityTermStructure (const Calendar & cal, BusinessDayConvention bdc = Following, const DayCounter & dc = DayCounter())
Warning:
term structures initialized by means of this constructor must manage their own reference date by overriding the referenceDate() method.
Definition at line 126 of file blackvoltermstructure.cpp.
    : BlackVolTermStructure(cal, bdc, dc) {}
QuantLib::BlackVolatilityTermStructure::BlackVolatilityTermStructure (BusinessDayConvention bdc = Following, const DayCounter & dc = DayCounter())
default constructor
Warning:
term structures initialized by means of this constructor must manage their own reference date by overriding the referenceDate() method.
Definition at line 133 of file blackvoltermstructure.cpp.
    : BlackVolTermStructure(bdc, dc) {}
QuantLib::BlackVolatilityTermStructure::BlackVolatilityTermStructure (const Date & referenceDate, const Calendar & cal = Calendar(), BusinessDayConvention bdc = Following, const DayCounter & dc = DayCounter())
initialize with a fixed reference date
Definition at line 138 of file blackvoltermstructure.cpp.
    : BlackVolTermStructure(refDate, cal, bdc, dc) {}
QuantLib::BlackVolatilityTermStructure::BlackVolatilityTermStructure (Natural settlementDays, const Calendar & cal, BusinessDayConvention bdc = Following, const DayCounter & dc = DayCounter())
calculate the reference date based on the global evaluation date
Definition at line 145 of file blackvoltermstructure.cpp.
    : BlackVolTermStructure(settlementDays, cal, bdc, dc) {}
Member Function Documentation
void QuantLib::BlackVolatilityTermStructure::accept (AcyclicVisitor & v) [inline, virtual]
Reimplemented from QuantLib::BlackVolTermStructure.
Reimplemented in QuantLib::BlackConstantVol.
Definition at line 297 of file blackvoltermstructure.hpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Visitor< T >::visit().
{
        Visitor<BlackVolatilityTermStructure>* v1 =
            dynamic_cast<Visitor<BlackVolatilityTermStructure>*>(&v);
        if (v1 != 0)
            v1->visit(*this);
        else
            BlackVolTermStructure::accept(v);
    }
Real QuantLib::BlackVolatilityTermStructure::blackVarianceImpl (Time maturity, Real strike) const [inline, protected, virtual]
Returns the variance for the given strike and date calculating it from the volatility.
Implements QuantLib::BlackVolTermStructure.
Definition at line 291 of file blackvoltermstructure.hpp.
References QuantLib::BlackVolTermStructure::blackVolImpl(), and anonymous_namespace{quantlibbenchmark.cpp}::t.
{
        Volatility vol = blackVolImpl(t, strike);
        return vol*vol*t;
    }
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/equityfx/blackvoltermstructure.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/equityfx/blackvoltermstructure.cpp