QuantLib: QuantLib::ContinuousArithmeticAsianLevyEngine Class Reference
QuantLib::ContinuousArithmeticAsianLevyEngine Class Reference
#include <continuousarithmeticasianlevyengine.hpp>
Public Member Functions
ContinuousArithmeticAsianLevyEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > &process, const Handle< Quote > &currentAverage, Date startDate)
void calculate () const
Private Attributes
boost::shared_ptr
< GeneralizedBlackScholesProcess > process_
Handle< Quote > currentAverage_
Date startDate_
Detailed Description
Definition at line 32 of file continuousarithmeticasianlevyengine.hpp.
Constructor & Destructor Documentation
QuantLib::ContinuousArithmeticAsianLevyEngine::ContinuousArithmeticAsianLevyEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > & process, const Handle< Quote > & currentAverage, Date startDate)
Definition at line 29 of file continuousarithmeticasianlevyengine.cpp.
References currentAverage_, process_, and QuantLib::Observer::registerWith().
    : process_(process), currentAverage_(currentAverage),
      startDate_(startDate) {
        registerWith(process_);
        registerWith(currentAverage_);
    }
Member Function Documentation
void QuantLib::ContinuousArithmeticAsianLevyEngine::calculate () const [virtual]
Implements QuantLib::PricingEngine.
Definition at line 39 of file continuousarithmeticasianlevyengine.cpp.
References QuantLib::GenericEngine< ContinuousAveragingAsianOption::arguments, ContinuousAveragingAsianOption::results >::arguments_, QuantLib::Average::Arithmetic, QuantLib::ContinuousAveragingAsianOption::arguments::averageType, anonymous_namespace{marketmodel.cpp}::b, QuantLib::Option::Call, QuantLib::Continuous, currentAverage_, QuantLib::Handle< T >::empty(), QuantLib::Exercise::European, anonymous_namespace{matrices.cpp}::N, QuantLib::NoFrequency, process_, QL_REQUIRE, QuantLib::GenericEngine< ContinuousAveragingAsianOption::arguments, ContinuousAveragingAsianOption::results >::results_, startDate_, QuantLib::Instrument::results::value, and QuantLib::io::volatility().
{
        QL_REQUIRE(arguments_.averageType == Average::Arithmetic,
                   "not an Arithmetic average option");
        QL_REQUIRE(arguments_.exercise->type() == Exercise::European,
                   "not an European Option");
        DayCounter rfdc  = process_->riskFreeRate()->dayCounter();
        DayCounter divdc = process_->dividendYield()->dayCounter();
        DayCounter voldc = process_->blackVolatility()->dayCounter();
        Real spot = process_->stateVariable()->value();
        // payoff
        boost::shared_ptr<StrikedTypePayoff> payoff =
            boost::dynamic_pointer_cast<StrikedTypePayoff>(arguments_.payoff);
        QL_REQUIRE(payoff, "non-plain payoff given");
        // original time to maturity
        Date maturity = arguments_.exercise->lastDate();
        Time T = rfdc.yearFraction(startDate_,
                                   arguments_.exercise->lastDate());
        // remaining time to maturity
        Time T2 = rfdc.yearFraction(process_->riskFreeRate()->referenceDate(),
                                    arguments_.exercise->lastDate());
        Real strike = payoff->strike();
        Volatility volatility =
            process_->blackVolatility()->blackVol(maturity, strike);
        CumulativeNormalDistribution N;
        Rate riskFreeRate = process_->riskFreeRate()->
            zeroRate(maturity, rfdc, Continuous, NoFrequency);
        Rate dividendYield = process_->dividendYield()->
            zeroRate(maturity, divdc, Continuous, NoFrequency);
        Real b = riskFreeRate - dividendYield;
        QL_REQUIRE(b != 0.0, "null cost of carry not allowed by Levy engine");
        Real Se = (spot/(T*b))*(exp((b-riskFreeRate)*T2)-exp(-riskFreeRate*T2));
        Real X;
        if (T2 < T) {
            QL_REQUIRE(!currentAverage_.empty() && currentAverage_->isValid(),
                       "current average required");
            X = strike - ((T-T2)/T)*currentAverage_->value();
        } else {
            X = strike;
        }
        Real M = (2*spot*spot/(b+volatility*volatility)) *
            (((exp((2*b+volatility*volatility)*T2)-1)
              / (2*b+volatility*volatility))-((exp(b*T2)-1)/b));
        Real D = M/(T*T);
        Real V = log(D)-2*(riskFreeRate*T2+log(Se));
        Real d1 = (1/sqrt(V))*((log(D)/2)-log(X));
        Real d2 = d1-sqrt(V);
        if(payoff->optionType()==Option::Call)
            results_.value = Se*N(d1) - X*exp(-riskFreeRate*T2)*N(d2);
        else
            results_.value = Se*N(d1) - X*exp(-riskFreeRate*T2)*N(d2)
                             - Se + X*exp(-riskFreeRate*T2);
    }
Member Data Documentation
Handle<Quote> QuantLib::ContinuousArithmeticAsianLevyEngine::currentAverage_ [private]
Definition at line 42 of file continuousarithmeticasianlevyengine.hpp.
Referenced by calculate(), and ContinuousArithmeticAsianLevyEngine().
boost::shared_ptr<GeneralizedBlackScholesProcess> QuantLib::ContinuousArithmeticAsianLevyEngine::process_ [private]
Definition at line 41 of file continuousarithmeticasianlevyengine.hpp.
Referenced by calculate(), and ContinuousArithmeticAsianLevyEngine().
Date QuantLib::ContinuousArithmeticAsianLevyEngine::startDate_ [private]
Definition at line 43 of file continuousarithmeticasianlevyengine.hpp.
Referenced by calculate().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/exoticoptions/continuousarithmeticasianlevyengine.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/exoticoptions/continuousarithmeticasianlevyengine.cpp