QuantLib: QuantLib::MakeMCAmericanBasketEngine< RNG > Class Template Reference
QuantLib::MakeMCAmericanBasketEngine< RNG > Class Template Reference
Monte Carlo American basket-option engine factory.
#include <mcamericanbasketengine.hpp>
Public Member Functions
MakeMCAmericanBasketEngine (const boost::shared_ptr< StochasticProcessArray > &)
MakeMCAmericanBasketEngine & withSteps (Size steps)
MakeMCAmericanBasketEngine & withStepsPerYear (Size steps)
MakeMCAmericanBasketEngine & withBrownianBridge (bool b=true)
MakeMCAmericanBasketEngine & withAntitheticVariate (bool b=true)
MakeMCAmericanBasketEngine & withSamples (Size samples)
MakeMCAmericanBasketEngine & withAbsoluteTolerance (Real tolerance)
MakeMCAmericanBasketEngine & withMaxSamples (Size samples)
MakeMCAmericanBasketEngine & withSeed (BigNatural seed)
MakeMCAmericanBasketEngine & withCalibrationSamples (Size samples)
operator boost::shared_ptr< PricingEngine > () const
Private Attributes
boost::shared_ptr
< StochasticProcessArray > process_
bool brownianBridge_
bool antithetic_
Size steps_
Size stepsPerYear_
Size samples_
Size maxSamples_
Size calibrationSamples_
Real tolerance_
BigNatural seed_
Detailed Description
template<class RNG = PseudoRandom>
class QuantLib::MakeMCAmericanBasketEngine< RNG >
Monte Carlo American basket-option engine factory.
Definition at line 69 of file mcamericanbasketengine.hpp.
Constructor & Destructor Documentation
template<class RNG > QuantLib::MakeMCAmericanBasketEngine< RNG >::MakeMCAmericanBasketEngine (const boost::shared_ptr< StochasticProcessArray > & process) [inline]
Definition at line 178 of file mcamericanbasketengine.hpp.
    : process_(process), brownianBridge_(false), antithetic_(false),
      steps_(Null<Size>()), stepsPerYear_(Null<Size>()),
      samples_(Null<Size>()), maxSamples_(Null<Size>()),
      calibrationSamples_(Null<Size>()),
      tolerance_(Null<Real>()), seed_(0) {}
Member Function Documentation
template<class RNG > QuantLib::MakeMCAmericanBasketEngine< RNG >::operator boost::shared_ptr< PricingEngine > () const [inline]
Definition at line 259 of file mcamericanbasketengine.hpp.
References QL_REQUIRE, and anonymous_namespace{marketmodel.cpp}::seed_.
{
        QL_REQUIRE(steps_ != Null<Size>() || stepsPerYear_ != Null<Size>(),
                   "number of steps not given");
        QL_REQUIRE(steps_ == Null<Size>() || stepsPerYear_ == Null<Size>(),
                   "number of steps overspecified");
        return boost::shared_ptr<PricingEngine>(new
            MCAmericanBasketEngine<RNG>(process_,
                                        steps_,
                                        stepsPerYear_,
                                        brownianBridge_,
                                        antithetic_,
                                        samples_,
                                        tolerance_,
                                        maxSamples_,
                                        seed_,
                                        calibrationSamples_));
    }
template<class RNG > MakeMCAmericanBasketEngine< RNG > & QuantLib::MakeMCAmericanBasketEngine< RNG >::withAbsoluteTolerance (Real tolerance) [inline]
Definition at line 225 of file mcamericanbasketengine.hpp.
References QL_REQUIRE, and anonymous_namespace{gaussianquadratures.cpp}::tolerance.
{
        QL_REQUIRE(samples_ == Null<Size>(),
                   "number of samples already set");
        QL_REQUIRE(RNG::allowsErrorEstimate,
                   "chosen random generator policy "
                   "does not allow an error estimate");
        tolerance_ = tolerance;
        return *this;
    }
template<class RNG > MakeMCAmericanBasketEngine< RNG > & QuantLib::MakeMCAmericanBasketEngine< RNG >::withAntitheticVariate (bool b = true) [inline]
Definition at line 209 of file mcamericanbasketengine.hpp.
References anonymous_namespace{marketmodel.cpp}::b.
Referenced by BasketOptionTest::testBarraquandThreeValues(), BasketOptionTest::testOddSamples(), BasketOptionTest::testOneDAmericanValues(), and BasketOptionTest::testTavellaValues().
{
        antithetic_ = b;
        return *this;
    }
template<class RNG > MakeMCAmericanBasketEngine< RNG > & QuantLib::MakeMCAmericanBasketEngine< RNG >::withBrownianBridge (bool b = true) [inline]
Definition at line 202 of file mcamericanbasketengine.hpp.
{
        brownianBridge_ = brownianBridge;
        return *this;
    }
template<class RNG > MakeMCAmericanBasketEngine< RNG > & QuantLib::MakeMCAmericanBasketEngine< RNG >::withCalibrationSamples (Size samples) [inline]
Definition at line 251 of file mcamericanbasketengine.hpp.
Referenced by BasketOptionTest::testBarraquandThreeValues(), BasketOptionTest::testOddSamples(), BasketOptionTest::testOneDAmericanValues(), and BasketOptionTest::testTavellaValues().
{
        calibrationSamples_ = samples;
        return *this;
    }
template<class RNG > MakeMCAmericanBasketEngine< RNG > & QuantLib::MakeMCAmericanBasketEngine< RNG >::withMaxSamples (Size samples) [inline]
Definition at line 237 of file mcamericanbasketengine.hpp.
{
        maxSamples_ = samples;
        return *this;
    }
template<class RNG > MakeMCAmericanBasketEngine< RNG > & QuantLib::MakeMCAmericanBasketEngine< RNG >::withSamples (Size samples) [inline]
Definition at line 216 of file mcamericanbasketengine.hpp.
References QL_REQUIRE.
Referenced by BasketOptionTest::testBarraquandThreeValues(), BasketOptionTest::testOddSamples(), BasketOptionTest::testOneDAmericanValues(), and BasketOptionTest::testTavellaValues().
{
        QL_REQUIRE(tolerance_ == Null<Real>(),
                   "tolerance already set");
        samples_ = samples;
        return *this;
    }
template<class RNG > MakeMCAmericanBasketEngine< RNG > & QuantLib::MakeMCAmericanBasketEngine< RNG >::withSeed (BigNatural seed) [inline]
Definition at line 244 of file mcamericanbasketengine.hpp.
References anonymous_namespace{marketmodel.cpp}::seed_.
Referenced by BasketOptionTest::testBarraquandThreeValues(), BasketOptionTest::testOddSamples(), BasketOptionTest::testOneDAmericanValues(), and BasketOptionTest::testTavellaValues().
{
        seed_ = seed;
        return *this;
    }
template<class RNG > MakeMCAmericanBasketEngine< RNG > & QuantLib::MakeMCAmericanBasketEngine< RNG >::withSteps (Size steps) [inline]
Definition at line 188 of file mcamericanbasketengine.hpp.
{
        steps_ = steps;
        return *this;
    }
template<class RNG > MakeMCAmericanBasketEngine< RNG > & QuantLib::MakeMCAmericanBasketEngine< RNG >::withStepsPerYear (Size steps) [inline]
Definition at line 195 of file mcamericanbasketengine.hpp.
{
        stepsPerYear_ = steps;
        return *this;
    }
Member Data Documentation
template<class RNG = PseudoRandom> bool QuantLib::MakeMCAmericanBasketEngine< RNG >::antithetic_ [private]
Definition at line 87 of file mcamericanbasketengine.hpp.
template<class RNG = PseudoRandom> bool QuantLib::MakeMCAmericanBasketEngine< RNG >::brownianBridge_ [private]
Definition at line 87 of file mcamericanbasketengine.hpp.
template<class RNG = PseudoRandom> Size QuantLib::MakeMCAmericanBasketEngine< RNG >::calibrationSamples_ [private]
Definition at line 88 of file mcamericanbasketengine.hpp.
template<class RNG = PseudoRandom> Size QuantLib::MakeMCAmericanBasketEngine< RNG >::maxSamples_ [private]
Definition at line 88 of file mcamericanbasketengine.hpp.
template<class RNG = PseudoRandom> boost::shared_ptr<StochasticProcessArray> QuantLib::MakeMCAmericanBasketEngine< RNG >::process_ [private]
Definition at line 86 of file mcamericanbasketengine.hpp.
template<class RNG = PseudoRandom> Size QuantLib::MakeMCAmericanBasketEngine< RNG >::samples_ [private]
Definition at line 88 of file mcamericanbasketengine.hpp.
template<class RNG = PseudoRandom> BigNatural QuantLib::MakeMCAmericanBasketEngine< RNG >::seed_ [private]
Definition at line 90 of file mcamericanbasketengine.hpp.
template<class RNG = PseudoRandom> Size QuantLib::MakeMCAmericanBasketEngine< RNG >::steps_ [private]
Definition at line 88 of file mcamericanbasketengine.hpp.
template<class RNG = PseudoRandom> Size QuantLib::MakeMCAmericanBasketEngine< RNG >::stepsPerYear_ [private]
Definition at line 88 of file mcamericanbasketengine.hpp.
template<class RNG = PseudoRandom> Real QuantLib::MakeMCAmericanBasketEngine< RNG >::tolerance_ [private]
Definition at line 89 of file mcamericanbasketengine.hpp.
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/basket/mcamericanbasketengine.hpp