QuantLib: QuantLib::PathMultiAssetOption Class Reference
QuantLib::PathMultiAssetOption Class Reference
Base class for path-dependent options on multiple assets.
#include <pathmultiassetoption.hpp>
Classes
class arguments
Arguments for multi-asset option calculation
class engine
class results
Results from multi-asset option calculation
Public Member Functions
PathMultiAssetOption (const boost::shared_ptr< PricingEngine > &engine=boost::shared_ptr< PricingEngine >())
virtual ~PathMultiAssetOption ()
Instrument interface
bool isExpired () const
returns whether the instrument might have value greater than zero.
void setupArguments (PricingEngine::arguments *) const
virtual boost::shared_ptr
< PathPayoff > pathPayoff () const =0
virtual std::vector< Date > fixingDates () const =0
void setupExpired () const
Detailed Description
Base class for path-dependent options on multiple assets.
Definition at line 35 of file pathmultiassetoption.hpp.
Constructor & Destructor Documentation
QuantLib::PathMultiAssetOption::PathMultiAssetOption (const boost::shared_ptr< PricingEngine > & engine = boost::shared_ptr<PricingEngine>())
Definition at line 28 of file pathmultiassetoption.cpp.
References QuantLib::Instrument::setPricingEngine().
{
        if (engine)
            setPricingEngine(engine);
    }
virtual QuantLib::PathMultiAssetOption::~PathMultiAssetOption () [inline, virtual]
Definition at line 40 of file pathmultiassetoption.hpp.
{}
Member Function Documentation
virtual std::vector<Date> QuantLib::PathMultiAssetOption::fixingDates () const [pure virtual]
Referenced by isExpired(), and setupArguments().
bool QuantLib::PathMultiAssetOption::isExpired () const [virtual]
returns whether the instrument might have value greater than zero.
Implements QuantLib::Instrument.
Definition at line 34 of file pathmultiassetoption.cpp.
References fixingDates(), and QuantLib::Event::hasOccurred().
{
        return detail::simple_event(fixingDates().back()).hasOccurred();
    }
virtual boost::shared_ptr<PathPayoff> QuantLib::PathMultiAssetOption::pathPayoff () const [pure virtual]
Referenced by setupArguments().
void QuantLib::PathMultiAssetOption::setupArguments (PricingEngine::arguments *) const [virtual]
When a derived argument structure is defined for an instrument, this method should be overridden to fill it. This is mandatory in case a pricing engine is used.
Reimplemented from QuantLib::Instrument.
Definition at line 42 of file pathmultiassetoption.cpp.
References fixingDates(), QuantLib::PathMultiAssetOption::arguments::fixingDates, pathPayoff(), QuantLib::PathMultiAssetOption::arguments::payoff, and QL_REQUIRE.
{
        PathMultiAssetOption::arguments* arguments =
            dynamic_cast<PathMultiAssetOption::arguments*>(args);
        QL_REQUIRE(arguments != 0, "wrong argument type");
        arguments->payoff            = pathPayoff();
        arguments->fixingDates       = fixingDates();
    }
void QuantLib::PathMultiAssetOption::setupExpired () const [protected, virtual]
This method must leave the instrument in a consistent state when the expiration condition is met.
Reimplemented from QuantLib::Instrument.
Definition at line 38 of file pathmultiassetoption.cpp.
References QuantLib::Instrument::NPV_.
{
        NPV_ = 0.0;
    }
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/mcbasket/pathmultiassetoption.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/mcbasket/pathmultiassetoption.cpp