QuantLib: QuantLib::FdG2SwaptionEngine Class Reference
QuantLib::FdG2SwaptionEngine Class Reference
#include <fdg2swaptionengine.hpp>
Public Member Functions
FdG2SwaptionEngine (const boost::shared_ptr< G2 > &model, Size tGrid=100, Size xGrid=50, Size yGrid=50, Size dampingSteps=0, Real invEps=1e-5, const FdmSchemeDesc &schemeDesc=FdmSchemeDesc::Hundsdorfer())
void calculate () const
Private Attributes
const Size tGrid_
const Size xGrid_
const Size yGrid_
const Size dampingSteps_
const Real invEps_
const FdmSchemeDesc schemeDesc_
Detailed Description
Definition at line 34 of file fdg2swaptionengine.hpp.
Constructor & Destructor Documentation
QuantLib::FdG2SwaptionEngine::FdG2SwaptionEngine (const boost::shared_ptr< G2 > & model, Size tGrid = 100, Size xGrid = 50, Size yGrid = 50, Size dampingSteps = 0, Real invEps = 1e-5, const FdmSchemeDesc & schemeDesc = FdmSchemeDesc::Hundsdorfer())
Definition at line 39 of file fdg2swaptionengine.cpp.
    : GenericModelEngine<G2, Swaption::arguments, Swaption::results>(model),
      tGrid_(tGrid),
      xGrid_(xGrid),
      yGrid_(yGrid),
      dampingSteps_(dampingSteps),
      invEps_(invEps),
      schemeDesc_(schemeDesc) {
    }
Member Function Documentation
void QuantLib::FdG2SwaptionEngine::calculate () const [virtual]
Implements QuantLib::PricingEngine.
Definition at line 53 of file fdg2swaptionengine.cpp.
References QuantLib::GenericEngine< Swaption::arguments, Swaption::results >::arguments_, QuantLib::Handle< T >::currentLink(), dampingSteps_, QuantLib::Option::arguments::exercise, invEps_, QuantLib::GenericModelEngine< G2, Swaption::arguments, Swaption::results >::model_, QL_REQUIRE, QuantLib::GenericEngine< Swaption::arguments, Swaption::results >::results_, schemeDesc_, QuantLib::Swaption::arguments::swap, anonymous_namespace{quantlibbenchmark.cpp}::t, tGrid_, QuantLib::Instrument::results::value, QuantLib::FdmStepConditionComposite::vanillaComposite(), xGrid_, QuantLib::DayCounter::yearFraction(), and yGrid_.
{
        const Handle<YieldTermStructure> ts = model_->termStructure();
        // 1. Layout
        std::vector<Size> dims;
        dims.push_back(xGrid_); dims.push_back(yGrid_);
        const boost::shared_ptr<FdmLinearOpLayout> layout(
            new FdmLinearOpLayout(dims));
        // 2. Mesher
        const DayCounter dc = ts->dayCounter();
        const Date referenceDate = ts->referenceDate();
        const Time maturity = dc.yearFraction(referenceDate,
                                              arguments_.exercise->lastDate());
        const boost::shared_ptr<OrnsteinUhlenbeckProcess> process1(
            new OrnsteinUhlenbeckProcess(model_->a(), model_->sigma()));
        const boost::shared_ptr<OrnsteinUhlenbeckProcess> process2(
            new OrnsteinUhlenbeckProcess(model_->b(), model_->eta()));
        const boost::shared_ptr<Fdm1dMesher> xMesher(
            new FdmSimpleProcess1dMesher(xGrid_,process1,maturity,1,invEps_));
        const boost::shared_ptr<Fdm1dMesher> yMesher(
            new FdmSimpleProcess1dMesher(yGrid_,process2,maturity,1,invEps_));
        std::vector<boost::shared_ptr<Fdm1dMesher> > meshers;
        meshers.push_back(xMesher);
        meshers.push_back(yMesher);
        const boost::shared_ptr<FdmMesher> mesher(
            new FdmMesherComposite(layout, meshers));
        // 3. Inner Value Calculator
        const std::vector<Date>& exerciseDates = arguments_.exercise->dates();
        std::map<Time, Date> t2d;
        for (Size i=0; i < exerciseDates.size(); ++i) {
            const Time t = dc.yearFraction(referenceDate, exerciseDates[i]);
            QL_REQUIRE(t >= 0, "exercise dates must not contain past date");
            t2d[t] = exerciseDates[i];
        }
        const Handle<YieldTermStructure> disTs = model_->termStructure();
        const Handle<YieldTermStructure> fwdTs
            = arguments_.swap->iborIndex()->forwardingTermStructure();
        QL_REQUIRE(fwdTs->dayCounter() == disTs->dayCounter(),
                "day counter of forward and discount curve must match");
        QL_REQUIRE(fwdTs->referenceDate() == disTs->referenceDate(),
                "reference date of forward and discount curve must match");
        const boost::shared_ptr<G2> fwdModel(
            new G2(fwdTs, model_->a(), model_->sigma(),
                   model_->b(), model_->eta(), model_->rho()));
        const boost::shared_ptr<FdmInnerValueCalculator> calculator(
             new FdmAffineModelSwapInnerValue<G2>(
                 model_.currentLink(), fwdModel,
                 arguments_.swap, t2d, mesher, 0));
        // 4. Step conditions
        const boost::shared_ptr<FdmStepConditionComposite> conditions =
             FdmStepConditionComposite::vanillaComposite(
                 DividendSchedule(), arguments_.exercise,
                 mesher, calculator, referenceDate, dc);
        // 5. Boundary conditions
        const FdmBoundaryConditionSet boundaries;
        // 6. Solver
        FdmSolverDesc solverDesc = { mesher, boundaries, conditions,
                                     calculator, maturity,
                                     tGrid_, dampingSteps_ };
        const boost::scoped_ptr<FdmG2Solver> solver(
            new FdmG2Solver(model_, solverDesc, schemeDesc_));
        results_.value = solver->valueAt(0.0, 0.0);
    }
Member Data Documentation
const Size QuantLib::FdG2SwaptionEngine::dampingSteps_ [private]
Definition at line 46 of file fdg2swaptionengine.hpp.
Referenced by calculate().
const Real QuantLib::FdG2SwaptionEngine::invEps_ [private]
Definition at line 47 of file fdg2swaptionengine.hpp.
Referenced by calculate().
const FdmSchemeDesc QuantLib::FdG2SwaptionEngine::schemeDesc_ [private]
Definition at line 48 of file fdg2swaptionengine.hpp.
Referenced by calculate().
const Size QuantLib::FdG2SwaptionEngine::tGrid_ [private]
Definition at line 46 of file fdg2swaptionengine.hpp.
Referenced by calculate().
const Size QuantLib::FdG2SwaptionEngine::xGrid_ [private]
Definition at line 46 of file fdg2swaptionengine.hpp.
Referenced by calculate().
const Size QuantLib::FdG2SwaptionEngine::yGrid_ [private]
Definition at line 46 of file fdg2swaptionengine.hpp.
Referenced by calculate().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/swaption/fdg2swaptionengine.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/swaption/fdg2swaptionengine.cpp