QuantLib: QuantLib::DiscountingBondEngine Class Reference
QuantLib::DiscountingBondEngine Class Reference
#include <discountingbondengine.hpp>
Public Member Functions
DiscountingBondEngine (const Handle< YieldTermStructure > &discountCurve=Handle< YieldTermStructure >(), boost::optional< bool > includeSettlementDateFlows=boost::none)
void calculate () const
Handle< YieldTermStructure > discountCurve () const
Private Attributes
Handle< YieldTermStructure > discountCurve_
boost::optional< bool > includeSettlementDateFlows_
Detailed Description
Definition at line 34 of file discountingbondengine.hpp.
Constructor & Destructor Documentation
QuantLib::DiscountingBondEngine::DiscountingBondEngine (const Handle< YieldTermStructure > & discountCurve = Handle<YieldTermStructure>(), boost::optional< bool > includeSettlementDateFlows = boost::none)
Definition at line 26 of file discountingbondengine.cpp.
References discountCurve_, and QuantLib::Observer::registerWith().
    : discountCurve_(discountCurve),
      includeSettlementDateFlows_(includeSettlementDateFlows) {
        registerWith(discountCurve_);
    }
Member Function Documentation
void QuantLib::DiscountingBondEngine::calculate () const [virtual]
Implements QuantLib::PricingEngine.
Definition at line 34 of file discountingbondengine.cpp.
References QuantLib::GenericEngine< Bond::arguments, Bond::results >::arguments_, QuantLib::Bond::arguments::cashflows, discountCurve_, QuantLib::Handle< T >::empty(), QuantLib::Settings::includeReferenceDateEvents(), includeSettlementDateFlows_, QuantLib::Singleton< Settings >::instance(), QuantLib::CashFlows::npv(), QL_REQUIRE, QuantLib::GenericEngine< Bond::arguments, Bond::results >::results_, QuantLib::Bond::arguments::settlementDate, QuantLib::Bond::results::settlementValue, QuantLib::Instrument::results::valuationDate, and QuantLib::Instrument::results::value.
{
        QL_REQUIRE(!discountCurve_.empty(),
                   "discounting term structure handle is empty");
        results_.valuationDate = (*discountCurve_)->referenceDate();
        bool includeRefDateFlows =
            includeSettlementDateFlows_ ?
            *includeSettlementDateFlows_ :
            Settings::instance().includeReferenceDateEvents();
        results_.value = CashFlows::npv(arguments_.cashflows,
                                        **discountCurve_,
                                        includeRefDateFlows,
                                        results_.valuationDate,
                                        results_.valuationDate);
        // a bond's cashflow on settlement date is never taken into
        // account, so we might have to play it safe and recalculate
        if (!includeRefDateFlows
                     && results_.valuationDate == arguments_.settlementDate) {
            // same parameters as above, we can avoid another call
            results_.settlementValue = results_.value;
        } else {
            // no such luck
            results_.settlementValue =
                CashFlows::npv(arguments_.cashflows,
                               **discountCurve_,
                               false,
                               arguments_.settlementDate,
                               arguments_.settlementDate);
        }
    }
Handle<YieldTermStructure> QuantLib::DiscountingBondEngine::discountCurve () const [inline]
Definition at line 41 of file discountingbondengine.hpp.
References discountCurve_.
{
            return discountCurve_;
        }
Member Data Documentation
Handle<YieldTermStructure> QuantLib::DiscountingBondEngine::discountCurve_ [private]
Definition at line 45 of file discountingbondengine.hpp.
Referenced by calculate(), discountCurve(), and DiscountingBondEngine().
boost::optional<bool> QuantLib::DiscountingBondEngine::includeSettlementDateFlows_ [private]
Definition at line 46 of file discountingbondengine.hpp.
Referenced by calculate().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/bond/discountingbondengine.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/bond/discountingbondengine.cpp