QuantLib: QuantLib::GeneralizedHullWhite Class Reference
QuantLib::GeneralizedHullWhite Class Reference
Generalized Hull-White model class.
#include <generalizedhullwhite.hpp>
Classes
class Dynamics
Short-rate dynamics in the generalized Hull-White model.
class Helper
Public Member Functions
GeneralizedHullWhite (const Handle< YieldTermStructure > &yieldtermStructure, const std::vector< Date > &speedstructure, const std::vector< Date > &volstructure)
GeneralizedHullWhite (const Handle< YieldTermStructure > &yieldtermStructure, const std::vector< Date > &speedstructure, const std::vector< Date > &volstructure, const std::vector< Real > &speed, const std::vector< Real > &vol)
boost::shared_ptr
< ShortRateDynamics > dynamics () const
returns the short-rate dynamics
boost::shared_ptr< Lattice > tree (const TimeGrid &grid) const
Return by default a trinomial recombining tree.
Private Member Functions
boost::function< Real(Time)> speed () const
boost::function< Real(Time)> vol () const
Private Attributes
std::vector< Date > speedstructure_
std::vector< Date > volstructure_
std::vector< Time > speedperiods_
std::vector< Time > volperiods_
Parameter & a_
Parameter & sigma_
Parameter phi_
Detailed Description
Generalized Hull-White model class.
This class implements the standard Black-Karasinski model defined by
\[ d f(r_t) = (\theta(t) - \alpha f(r_t))dt + \sigma dW_t, \]
where \(alpha \) and \(sigma \) are piecewise linear functions.
Definition at line 42 of file generalizedhullwhite.hpp.
Constructor & Destructor Documentation
QuantLib::GeneralizedHullWhite::GeneralizedHullWhite (const Handle< YieldTermStructure > & yieldtermStructure, const std::vector< Date > & speedstructure, const std::vector< Date > & volstructure)
Definition at line 91 of file generalizedhullwhite.cpp.
References a_, QuantLib::Observer::registerWith(), QuantLib::Parameter::setParam(), sigma_, QuantLib::Parameter::size(), speedperiods_, volperiods_, and QuantLib::DayCounter::yearFraction().
    : OneFactorModel(2), TermStructureConsistentModel(yieldtermStructure),
      speedstructure_(speedstructure), volstructure_(volstructure),
      a_(arguments_[0]), sigma_(arguments_[1]) {
        DayCounter dc = yieldtermStructure->dayCounter();
        speedperiods_.push_back(0.0);
        for (Size i=0;i<speedstructure.size()-1;i++)
            speedperiods_.push_back(dc.yearFraction(speedstructure[0],
                                                    speedstructure[i+1]));
        a_ = PiecewiseConstantParameter(speedperiods_, PositiveConstraint());
        volperiods_.push_back(0.0);
        for (Size i=0;i<volstructure.size()-1;i++)
            volperiods_.push_back(dc.yearFraction(volstructure[0],
                                                  volstructure[i+1]));
        sigma_ = PiecewiseConstantParameter(volperiods_, PositiveConstraint());
        a_.setParam(0,0.1);
        sigma_.setParam(0,0.1);
        for (Size i=1; i< a_.size();i++){
            a_.setParam(i,0.1*i+0.01);
        }
        for (Size i=1; i< sigma_.size();i++){
            sigma_.setParam(i,0.1*i+0.01);
        }
        registerWith(yieldtermStructure);
    }
QuantLib::GeneralizedHullWhite::GeneralizedHullWhite (const Handle< YieldTermStructure > & yieldtermStructure, const std::vector< Date > & speedstructure, const std::vector< Date > & volstructure, const std::vector< Real > & speed, const std::vector< Real > & vol)
Definition at line 129 of file generalizedhullwhite.cpp.
References a_, QuantLib::Observer::registerWith(), QuantLib::Parameter::setParam(), sigma_, QuantLib::Parameter::size(), speedperiods_, volperiods_, and QuantLib::DayCounter::yearFraction().
  : OneFactorModel(2), TermStructureConsistentModel(yieldtermStructure),
    speedstructure_(speedstructure),
    volstructure_(volstructure),
    a_(arguments_[0]), sigma_(arguments_[1]) {
        DayCounter dc = yieldtermStructure->dayCounter();
        speedperiods_.push_back(0.0);
        for (Size i=0;i<speedstructure.size()-1;i++)
            speedperiods_.push_back(dc.yearFraction(speedstructure[0],
                                                    speedstructure[i+1]));
        a_ = PiecewiseConstantParameter(speedperiods_, PositiveConstraint());
        volperiods_.push_back(0.0);
        for (Size i=0;i<volstructure.size()-1;i++)
            volperiods_.push_back(dc.yearFraction(volstructure[0],
                                                  volstructure[i+1]));
        sigma_ = PiecewiseConstantParameter(volperiods_, PositiveConstraint());
        a_.setParam(0,speed[0]);
        sigma_.setParam(0,vol[0]);
        for (Size i=1; i< sigma_.size();i++) {
            sigma_.setParam(i,vol[i-1]);
        }
        for (Size i=1; i< a_.size();i++) {
            a_.setParam(i,speed[i-1]);
        }
        registerWith(yieldtermStructure);
    }
Member Function Documentation
boost::shared_ptr<ShortRateDynamics> QuantLib::GeneralizedHullWhite::dynamics () const [inline, virtual]
returns the short-rate dynamics
Implements QuantLib::OneFactorModel.
Definition at line 63 of file generalizedhullwhite.hpp.
References QL_FAIL.
{
            QL_FAIL("no defined process for generalized Hull-White model");
        }
boost::function< Real(Time)> QuantLib::GeneralizedHullWhite::speed () const [private]
Definition at line 202 of file generalizedhullwhite.cpp.
References a_, QuantLib::Parameter::size(), speedperiods_, and speedstructure_.
Referenced by tree().
{
        std::vector<Real> speedvals;
        speedvals.push_back(a_(0.0001));
        for (Size i=0;i<a_.size()-1;i++)
            speedvals.push_back(
            a_(
            (speedstructure_[i+1]-speedstructure_[0])/365.0
            - 0.00001));
        return PiecewiseLinearCurve(speedperiods_, speedvals);
    }
boost::shared_ptr< Lattice > QuantLib::GeneralizedHullWhite::tree (const TimeGrid & grid) const [virtual]
Return by default a trinomial recombining tree.
Reimplemented from QuantLib::OneFactorModel.
Definition at line 169 of file generalizedhullwhite.cpp.
References QuantLib::Parameter::implementation(), QuantLib::anonymous_namespace{bjerksundstenslandengine.cpp}::phi(), QuantLib::TermStructureFittingParameter::NumericalImpl::reset(), QuantLib::Solver1D< Impl >::setMaxEvaluations(), QuantLib::TimeGrid::size(), QuantLib::Solver1D< Impl >::solve(), speed(), QuantLib::TermStructureConsistentModel::termStructure(), QuantLib::CalibratedModel::value(), and vol().
{
        TermStructureFittingParameter phi(termStructure());
        boost::shared_ptr<ShortRateDynamics> numericDynamics(
            new Dynamics(phi, speed(), vol()));
        boost::shared_ptr<TrinomialTree> trinomial(
            new TrinomialTree(numericDynamics->process(), grid));
        boost::shared_ptr<ShortRateTree> numericTree(
            new ShortRateTree(trinomial, numericDynamics, grid));
        typedef TermStructureFittingParameter::NumericalImpl NumericalImpl;
        boost::shared_ptr<NumericalImpl> impl =
            boost::dynamic_pointer_cast<NumericalImpl>(phi.implementation());
        impl->reset();
        Real value = 1.0;
        Real vMin = -50.0;
        Real vMax = 50.0;
        for (Size i=0; i<(grid.size() - 1); i++) {
            Real discountBond = termStructure()->discount(grid[i+1]);
            Real xMin = trinomial->underlying(i, 0);
            Real dx = trinomial->dx(i);
            Helper finder(i, xMin, dx, discountBond, numericTree);
            Brent s1d;
            s1d.setMaxEvaluations(1000);
            value = s1d.solve(finder, 1e-7, value, vMin, vMax);
            impl->set(grid[i], value);
        }
        return numericTree;
    }
boost::function< Real(Time)> QuantLib::GeneralizedHullWhite::vol () const [private]
Definition at line 215 of file generalizedhullwhite.cpp.
References sigma_, QuantLib::Parameter::size(), speedstructure_, and volperiods_.
Referenced by tree().
{
        std::vector<Real> volvals;
        volvals.push_back(sigma_(0.0001));
        for (Size i=0;i<sigma_.size()-1;i++)
            volvals.push_back(
            sigma_(
            (speedstructure_[i+1]-speedstructure_[0])/365.0
            - 0.00001));
        return PiecewiseLinearCurve(volperiods_, volvals);
    }
Member Data Documentation
Parameter& QuantLib::GeneralizedHullWhite::a_ [private]
Definition at line 82 of file generalizedhullwhite.hpp.
Referenced by GeneralizedHullWhite(), and speed().
Parameter QuantLib::GeneralizedHullWhite::phi_ [private]
Definition at line 84 of file generalizedhullwhite.hpp.
Parameter& QuantLib::GeneralizedHullWhite::sigma_ [private]
Definition at line 83 of file generalizedhullwhite.hpp.
Referenced by GeneralizedHullWhite(), and vol().
std::vector<Time> QuantLib::GeneralizedHullWhite::speedperiods_ [private]
Definition at line 76 of file generalizedhullwhite.hpp.
Referenced by GeneralizedHullWhite(), and speed().
std::vector<Date> QuantLib::GeneralizedHullWhite::speedstructure_ [private]
Definition at line 72 of file generalizedhullwhite.hpp.
Referenced by speed(), and vol().
std::vector<Time> QuantLib::GeneralizedHullWhite::volperiods_ [private]
Definition at line 77 of file generalizedhullwhite.hpp.
Referenced by GeneralizedHullWhite(), and vol().
std::vector<Date> QuantLib::GeneralizedHullWhite::volstructure_ [private]
Definition at line 75 of file generalizedhullwhite.hpp.
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/shortrate/generalizedhullwhite.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/shortrate/generalizedhullwhite.cpp