QuantLib: QuantLib::IntegralCdsEngine Class Reference
QuantLib::IntegralCdsEngine Class Reference
#include <integralcdsengine.hpp>
Public Member Functions
IntegralCdsEngine (const Period &integrationStep, const Handle< DefaultProbabilityTermStructure > &, Real recoveryRate, const Handle< YieldTermStructure > &discountCurve, boost::optional< bool > includeSettlementDateFlows=boost::none)
void calculate () const
Private Attributes
Period integrationStep_
Handle
< DefaultProbabilityTermStructure > probability_
Real recoveryRate_
Handle< YieldTermStructure > discountCurve_
boost::optional< bool > includeSettlementDateFlows_
Detailed Description
Definition at line 32 of file integralcdsengine.hpp.
Constructor & Destructor Documentation
QuantLib::IntegralCdsEngine::IntegralCdsEngine (const Period & integrationStep, const Handle< DefaultProbabilityTermStructure > & probability, Real recoveryRate, const Handle< YieldTermStructure > & discountCurve, boost::optional< bool > includeSettlementDateFlows = boost::none)
Definition at line 29 of file integralcdsengine.cpp.
References discountCurve_, probability_, and QuantLib::Observer::registerWith().
    : integrationStep_(step), probability_(probability),
      recoveryRate_(recoveryRate), discountCurve_(discountCurve),
      includeSettlementDateFlows_(includeSettlementDateFlows) {
        registerWith(probability_);
        registerWith(discountCurve_);
    }
Member Function Documentation
void QuantLib::IntegralCdsEngine::calculate () const [virtual]
Implements QuantLib::PricingEngine.
Definition at line 42 of file integralcdsengine.cpp.
References QuantLib::GenericEngine< CreditDefaultSwap::arguments, CreditDefaultSwap::results >::arguments_, QuantLib::Protection::Buyer, QuantLib::CreditDefaultSwap::arguments::claim, QuantLib::CreditDefaultSwap::results::couponLegBPS, QuantLib::CreditDefaultSwap::results::couponLegNPV, QuantLib::CreditDefaultSwap::results::defaultLegNPV, discountCurve_, QuantLib::Handle< T >::empty(), anonymous_namespace{marketmodel.cpp}::endDate, QuantLib::Instrument::results::errorEstimate, QuantLib::Settings::evaluationDate(), QuantLib::CreditDefaultSwap::results::fairSpread, QuantLib::CreditDefaultSwap::results::fairUpfront, includeSettlementDateFlows_, QuantLib::Singleton< Settings >::instance(), integrationStep_, QuantLib::CreditDefaultSwap::arguments::leg, QuantLib::CreditDefaultSwap::arguments::notional, QuantLib::CreditDefaultSwap::arguments::paysAtDefaultTime, probability_, QuantLib::CreditDefaultSwap::arguments::protectionStart, QL_FAIL, QL_REQUIRE, recoveryRate_, QuantLib::GenericEngine< CreditDefaultSwap::arguments, CreditDefaultSwap::results >::results_, QuantLib::Protection::Seller, QuantLib::CreditDefaultSwap::arguments::settlesAccrual, QuantLib::CreditDefaultSwap::arguments::side, QuantLib::CreditDefaultSwap::arguments::spread, anonymous_namespace{marketmodel.cpp}::startDate, QuantLib::CreditDefaultSwap::arguments::upfront, QuantLib::CreditDefaultSwap::results::upfrontBPS, QuantLib::CreditDefaultSwap::results::upfrontNPV, QuantLib::CreditDefaultSwap::arguments::upfrontPayment, and QuantLib::Instrument::results::value.
{
        QL_REQUIRE(integrationStep_ != Period(),
                   "null period set");
        QL_REQUIRE(!discountCurve_.empty(),
                   "no discount term structure set");
        QL_REQUIRE(!probability_.empty(),
                   "no probability term structure set");
        Date today = Settings::instance().evaluationDate();
        Date settlementDate = discountCurve_->referenceDate();
        // Upfront Flow NPV. Either we are on-the-run (no flow)
        // or we are forward start
        Real upfPVO1 = 0.0;
        if(!arguments_.upfrontPayment->hasOccurred(
                                               settlementDate,
                                               includeSettlementDateFlows_)) {
            // date determining the probability survival so we have to pay
            // the upfront (did not knock out)
            Date effectiveUpfrontDate =
                arguments_.protectionStart > probability_->referenceDate() ?
                    arguments_.protectionStart : probability_->referenceDate();
            upfPVO1 =
                probability_->survivalProbability(effectiveUpfrontDate) *
                discountCurve_->discount(arguments_.upfrontPayment->date());
        }
        results_.upfrontNPV = upfPVO1 * arguments_.upfrontPayment->amount();
        results_.couponLegNPV = 0.0;
        results_.defaultLegNPV = 0.0;
        for (Size i=0; i<arguments_.leg.size(); ++i) {
            if (arguments_.leg[i]->hasOccurred(settlementDate,
                                               includeSettlementDateFlows_))
                continue;
            boost::shared_ptr<FixedRateCoupon> coupon =
                boost::dynamic_pointer_cast<FixedRateCoupon>(arguments_.leg[i]);
            // In order to avoid a few switches, we calculate the NPV
            // of both legs as a positive quantity. We'll give them
            // the right sign at the end.
            Date paymentDate = coupon->date(),
                 startDate = (i == 0 ? arguments_.protectionStart :
                                       coupon->accrualStartDate()),
                 endDate = coupon->accrualEndDate();
            Date effectiveStartDate =
                (startDate <= today && today <= endDate) ? today : startDate;
            Real couponAmount = coupon->amount();
            Probability S = probability_->survivalProbability(paymentDate);
            // On one side, we add the fixed rate payments in case of
            // survival.
            results_.couponLegNPV +=
                S * couponAmount * discountCurve_->discount(paymentDate);
            // On the other side, we add the payment (and possibly the
            // accrual) in case of default.
            Period step = integrationStep_;
            Date d0 = effectiveStartDate;
            Date d1 = std::min(d0 + step, endDate);
            Probability P0 = probability_->defaultProbability(d0);
            DiscountFactor endDiscount = discountCurve_->discount(paymentDate);
            do {
                DiscountFactor B =
                    arguments_.paysAtDefaultTime ?
                    discountCurve_->discount(d1) :
                    endDiscount;
                Probability P1 = probability_->defaultProbability(d1);
                Probability dP = P1 - P0;
                // accrual...
                if (arguments_.settlesAccrual) {
                    if (arguments_.paysAtDefaultTime)
                        results_.couponLegNPV +=
                            coupon->accruedAmount(d1) * B * dP;
                    else
                        results_.couponLegNPV +=
                            couponAmount * B * dP;
                }
                // ...and claim.
                Real claim = arguments_.claim->amount(d1,
                                                      arguments_.notional,
                                                      recoveryRate_);
                results_.defaultLegNPV += claim * B * dP;
                // setup for next time around the loop
                P0 = P1;
                d0 = d1;
                d1 = std::min(d0 + step, endDate);
            } while (d0 < endDate);
        }
        Real upfrontSign = 1.0;
        switch (arguments_.side) {
          case Protection::Seller:
            results_.defaultLegNPV *= -1.0;
            break;
          case Protection::Buyer:
            results_.couponLegNPV *= -1.0;
            results_.upfrontNPV   *= -1.0;
            upfrontSign = -1.0;
            break;
          default:
            QL_FAIL("unknown protection side");
        }
        results_.value =
            results_.defaultLegNPV+results_.couponLegNPV+results_.upfrontNPV;
        results_.errorEstimate = Null<Real>();
        if (results_.couponLegNPV != 0.0) {
            results_.fairSpread =
                -results_.defaultLegNPV*arguments_.spread/results_.couponLegNPV;
        } else {
            results_.fairSpread = Null<Rate>();
        }
        Real upfrontSensitivity = upfPVO1 * arguments_.notional;
        if (upfrontSensitivity != 0.0) {
            results_.fairUpfront =
                -upfrontSign*(results_.defaultLegNPV + results_.couponLegNPV)
                / upfrontSensitivity;
        } else {
            results_.fairUpfront = Null<Rate>();
        }
        static const Rate basisPoint = 1.0e-4;
        if (arguments_.spread != 0.0) {
            results_.couponLegBPS =
                results_.couponLegNPV*basisPoint/arguments_.spread;
        } else {
            results_.couponLegBPS = Null<Rate>();
        }
        if (arguments_.upfront && *arguments_.upfront != 0.0) {
            results_.upfrontBPS =
                results_.upfrontNPV*basisPoint/(*arguments_.upfront);
        } else {
            results_.upfrontBPS = Null<Rate>();
        }
    }
Member Data Documentation
Handle<YieldTermStructure> QuantLib::IntegralCdsEngine::discountCurve_ [private]
Definition at line 45 of file integralcdsengine.hpp.
Referenced by calculate(), and IntegralCdsEngine().
boost::optional<bool> QuantLib::IntegralCdsEngine::includeSettlementDateFlows_ [private]
Definition at line 46 of file integralcdsengine.hpp.
Referenced by calculate().
Period QuantLib::IntegralCdsEngine::integrationStep_ [private]
Definition at line 42 of file integralcdsengine.hpp.
Referenced by calculate().
Handle<DefaultProbabilityTermStructure> QuantLib::IntegralCdsEngine::probability_ [private]
Definition at line 43 of file integralcdsengine.hpp.
Referenced by calculate(), and IntegralCdsEngine().
Real QuantLib::IntegralCdsEngine::recoveryRate_ [private]
Definition at line 44 of file integralcdsengine.hpp.
Referenced by calculate().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/credit/integralcdsengine.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/credit/integralcdsengine.cpp