QuantLib: QuantLib::SimpleLocalEstimator Class Reference
QuantLib::SimpleLocalEstimator Class Reference
Local-estimator volatility model.
#include <simplelocalestimator.hpp>
Public Member Functions
SimpleLocalEstimator (Real y)
TimeSeries< Volatility > calculate (const TimeSeries< Real > &quoteSeries)
Private Attributes
Real yearFraction_
Detailed Description
Local-estimator volatility model.
Volatilities are assumed to be expressed on an annual basis.
Definition at line 35 of file simplelocalestimator.hpp.
Constructor & Destructor Documentation
QuantLib::SimpleLocalEstimator::SimpleLocalEstimator (Real y) [inline]
Definition at line 40 of file simplelocalestimator.hpp.
                                     :
        yearFraction_(y) {}
Member Function Documentation
TimeSeries<Volatility> QuantLib::SimpleLocalEstimator::calculate (const TimeSeries< Real > & quoteSeries) [inline, virtual]
Implements QuantLib::LocalVolatilityEstimator< Real >.
Definition at line 43 of file simplelocalestimator.hpp.
References QuantLib::TimeSeries< T, Container >::begin(), QuantLib::TimeSeries< T, Container >::end(), and yearFraction_.
Referenced by VolatilityModelsTest::testConstruction().
{
            TimeSeries<Volatility> retval;
            TimeSeries<Real>::const_iterator prev, next, cur, start;
            start = quoteSeries.begin();
            ++start;
            for (cur = start; cur != quoteSeries.end(); ++cur) {
                prev = cur; --prev;
                retval[cur->first] =
                    std::fabs(std::log(cur->second/prev->second))/
                    std::sqrt(yearFraction_);
            }
            return retval;
        }
Member Data Documentation
Real QuantLib::SimpleLocalEstimator::yearFraction_ [private]
Definition at line 38 of file simplelocalestimator.hpp.
Referenced by calculate().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/volatility/simplelocalestimator.hpp