QuantLib: QuantLib::FlatForward Class Reference
QuantLib::FlatForward Class Reference
Flat interest-rate curve.
#include <flatforward.hpp>
Public Member Functions
Compounding compounding () const
Frequency compoundingFrequency () const
Constructors
FlatForward (const Date &referenceDate, const Handle< Quote > &forward, const DayCounter &dayCounter, Compounding compounding=Continuous, Frequency frequency=Annual)
FlatForward (const Date &referenceDate, Rate forward, const DayCounter &dayCounter, Compounding compounding=Continuous, Frequency frequency=Annual)
FlatForward (Natural settlementDays, const Calendar &calendar, const Handle< Quote > &forward, const DayCounter &dayCounter, Compounding compounding=Continuous, Frequency frequency=Annual)
FlatForward (Natural settlementDays, const Calendar &calendar, Rate forward, const DayCounter &dayCounter, Compounding compounding=Continuous, Frequency frequency=Annual)
TermStructure interface
Date maxDate () const
the latest date for which the curve can return values
Observer interface
void update ()
Private Member Functions
LazyObject interface
void performCalculations () const
YieldTermStructure implementation
DiscountFactor discountImpl (Time) const
discount factor calculation
Private Attributes
Handle< Quote > forward_
Compounding compounding_
Frequency frequency_
InterestRate rate_
Detailed Description
Flat interest-rate curve.
Definition at line 36 of file flatforward.hpp.
Constructor & Destructor Documentation
QuantLib::FlatForward::FlatForward (const Date & referenceDate, const Handle< Quote > & forward, const DayCounter & dayCounter, Compounding compounding = Continuous, Frequency frequency = Annual)
Definition at line 26 of file flatforward.cpp.
References forward_, and QuantLib::Observer::registerWith().
    : YieldTermStructure(referenceDate, Calendar(), dayCounter),
      forward_(forward), compounding_(compounding), frequency_(frequency) {
        registerWith(forward_);
    }
QuantLib::FlatForward::FlatForward (const Date & referenceDate, Rate forward, const DayCounter & dayCounter, Compounding compounding = Continuous, Frequency frequency = Annual)
Definition at line 36 of file flatforward.cpp.
    : YieldTermStructure(referenceDate, Calendar(), dayCounter),
      forward_(boost::shared_ptr<Quote>(new SimpleQuote(forward))),
      compounding_(compounding), frequency_(frequency) {}
QuantLib::FlatForward::FlatForward (Natural settlementDays, const Calendar & calendar, const Handle< Quote > & forward, const DayCounter & dayCounter, Compounding compounding = Continuous, Frequency frequency = Annual)
Definition at line 45 of file flatforward.cpp.
References forward_, and QuantLib::Observer::registerWith().
    : YieldTermStructure(settlementDays, calendar, dayCounter),
      forward_(forward), compounding_(compounding), frequency_(frequency) {
        registerWith(forward_);
    }
QuantLib::FlatForward::FlatForward (Natural settlementDays, const Calendar & calendar, Rate forward, const DayCounter & dayCounter, Compounding compounding = Continuous, Frequency frequency = Annual)
Definition at line 56 of file flatforward.cpp.
    : YieldTermStructure(settlementDays, calendar, dayCounter),
      forward_(boost::shared_ptr<Quote>(new SimpleQuote(forward))),
      compounding_(compounding), frequency_(frequency) {}
Member Function Documentation
Compounding QuantLib::FlatForward::compounding () const [inline]
Definition at line 66 of file flatforward.hpp.
References compounding_.
{ return compounding_; }
Frequency QuantLib::FlatForward::compoundingFrequency () const [inline]
Definition at line 67 of file flatforward.hpp.
References frequency_.
{ return frequency_; }
DiscountFactor QuantLib::FlatForward::discountImpl (Time) const [inline, private, virtual]
discount factor calculation
Implements QuantLib::YieldTermStructure.
Definition at line 102 of file flatforward.hpp.
References QuantLib::LazyObject::calculate(), QuantLib::InterestRate::discountFactor(), and rate_.
{
        calculate();
        return rate_.discountFactor(t);
    }
Date QuantLib::FlatForward::maxDate () const [inline, virtual]
the latest date for which the curve can return values
Implements QuantLib::TermStructure.
Definition at line 71 of file flatforward.hpp.
{ return Date::maxDate(); }
void QuantLib::FlatForward::performCalculations () const [inline, private, virtual]
This method must implement any calculations which must be (re)done in order to calculate the desired results.
Implements QuantLib::LazyObject.
Definition at line 107 of file flatforward.hpp.
References compounding_, QuantLib::TermStructure::dayCounter(), forward_, frequency_, and rate_.
{
        rate_ = InterestRate(forward_->value(), dayCounter(),
                             compounding_, frequency_);
    }
void QuantLib::FlatForward::update () [inline, virtual]
This method must be implemented in derived classes. An instance of Observer does not call this method directly: instead, it will be called by the observables the instance registered with when they need to notify any changes.
Reimplemented from QuantLib::LazyObject.
Definition at line 97 of file flatforward.hpp.
{
        LazyObject::update();
        YieldTermStructure::update();
    }
Member Data Documentation
Compounding QuantLib::FlatForward::compounding_ [private]
Definition at line 90 of file flatforward.hpp.
Referenced by compounding(), and performCalculations().
Handle<Quote> QuantLib::FlatForward::forward_ [private]
Definition at line 89 of file flatforward.hpp.
Referenced by FlatForward(), and performCalculations().
Frequency QuantLib::FlatForward::frequency_ [private]
Definition at line 91 of file flatforward.hpp.
Referenced by compoundingFrequency(), and performCalculations().
InterestRate QuantLib::FlatForward::rate_ [mutable, private]
Definition at line 92 of file flatforward.hpp.
Referenced by discountImpl(), and performCalculations().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/yield/flatforward.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/yield/flatforward.cpp