QuantLib: QuantLib::CPIBond Class Reference
QuantLib::CPIBond Class Reference
#include <cpibond.hpp>
Public Member Functions
CPIBond (Natural settlementDays, Real faceAmount, bool growthOnly, Real baseCPI, const Period &observationLag, const boost::shared_ptr< ZeroInflationIndex > &cpiIndex, CPI::InterpolationType observationInterpolation, const Schedule &schedule, const std::vector< Rate > &coupons, const DayCounter &accrualDayCounter, BusinessDayConvention paymentConvention=ModifiedFollowing, const Date &issueDate=Date())
Frequency frequency () const
const DayCounter & dayCounter () const
bool growthOnly () const
Real baseCPI () const
Period observationLag () const
const boost::shared_ptr
< ZeroInflationIndex > & cpiIndex () const
CPI::InterpolationType observationInterpolation () const
Protected Attributes
Frequency frequency_
DayCounter dayCounter_
bool growthOnly_
Real baseCPI_
Period observationLag_
boost::shared_ptr
< ZeroInflationIndex > cpiIndex_
CPI::InterpolationType observationInterpolation_
Detailed Description
cpi bond; if there is only one date in the schedule it is a zero bond returning an inflated notional.
Definition at line 43 of file cpibond.hpp.
Constructor & Destructor Documentation
QuantLib::CPIBond::CPIBond (Natural settlementDays, Real faceAmount, bool growthOnly, Real baseCPI, const Period & observationLag, const boost::shared_ptr< ZeroInflationIndex > & cpiIndex, CPI::InterpolationType observationInterpolation, const Schedule & schedule, const std::vector< Rate > & coupons, const DayCounter & accrualDayCounter, BusinessDayConvention paymentConvention = ModifiedFollowing, const Date & issueDate = Date())
Definition at line 36 of file cpibond.cpp.
References baseCPI_, QuantLib::Bond::cashflows_, cpiIndex_, QuantLib::Schedule::endDate(), growthOnly_, QuantLib::Bond::maturityDate_, observationInterpolation_, observationLag_, QuantLib::Observer::registerWith(), QuantLib::CPILeg::withFixedRates(), QuantLib::CPILeg::withNotionals(), QuantLib::CPILeg::withObservationInterpolation(), QuantLib::CPILeg::withPaymentAdjustment(), QuantLib::CPILeg::withPaymentDayCounter(), and QuantLib::CPILeg::withSubtractInflationNominal().
    : Bond(settlementDays, schedule.calendar(), issueDate),
    frequency_(schedule.tenor().frequency()),
    dayCounter_(accrualDayCounter),
    growthOnly_(growthOnly),
    baseCPI_(baseCPI),
    observationLag_(observationLag),
    cpiIndex_(cpiIndex),
    observationInterpolation_(observationInterpolation)
    {
        maturityDate_ = schedule.endDate();
        // a CPIleg know about zero legs and inclusion of base inflation notional
        cashflows_ = CPILeg(schedule, cpiIndex_,
                            baseCPI_, observationLag_)
        .withNotionals(faceAmount)
        .withFixedRates(fixedRate)
        .withPaymentDayCounter(accrualDayCounter)
        .withPaymentAdjustment(paymentConvention)
        .withObservationInterpolation(observationInterpolation_)
        .withSubtractInflationNominal(growthOnly_);
        registerWith(cpiIndex_);
        Leg::const_iterator i;
        for (i = cashflows_.begin(); i < cashflows_.end(); ++i) {
            registerWith(*i);
        }
    };
Member Function Documentation
Real QuantLib::CPIBond::baseCPI () const [inline]
Definition at line 61 of file cpibond.hpp.
References baseCPI_.
{ return baseCPI_; }
const boost::shared_ptr<ZeroInflationIndex>& QuantLib::CPIBond::cpiIndex () const [inline]
Definition at line 63 of file cpibond.hpp.
References cpiIndex_.
{ return cpiIndex_; }
const DayCounter& QuantLib::CPIBond::dayCounter () const [inline]
Definition at line 59 of file cpibond.hpp.
References dayCounter_.
{ return dayCounter_; }
Frequency QuantLib::CPIBond::frequency () const [inline]
Definition at line 58 of file cpibond.hpp.
References frequency_.
{ return frequency_; }
bool QuantLib::CPIBond::growthOnly () const [inline]
Definition at line 60 of file cpibond.hpp.
References growthOnly_.
{ return growthOnly_; }
CPI::InterpolationType QuantLib::CPIBond::observationInterpolation () const [inline]
Definition at line 64 of file cpibond.hpp.
References observationInterpolation_.
{ return observationInterpolation_; }
Period QuantLib::CPIBond::observationLag () const [inline]
Definition at line 62 of file cpibond.hpp.
References observationLag_.
{ return observationLag_; }
Member Data Documentation
Real QuantLib::CPIBond::baseCPI_ [protected]
Definition at line 70 of file cpibond.hpp.
Referenced by baseCPI(), and CPIBond().
boost::shared_ptr<ZeroInflationIndex> QuantLib::CPIBond::cpiIndex_ [protected]
Definition at line 72 of file cpibond.hpp.
Referenced by CPIBond(), and cpiIndex().
DayCounter QuantLib::CPIBond::dayCounter_ [protected]
Definition at line 68 of file cpibond.hpp.
Referenced by dayCounter().
Frequency QuantLib::CPIBond::frequency_ [protected]
Definition at line 67 of file cpibond.hpp.
Referenced by frequency().
bool QuantLib::CPIBond::growthOnly_ [protected]
Definition at line 69 of file cpibond.hpp.
Referenced by CPIBond(), and growthOnly().
CPI::InterpolationType QuantLib::CPIBond::observationInterpolation_ [protected]
Definition at line 73 of file cpibond.hpp.
Referenced by CPIBond(), and observationInterpolation().
Period QuantLib::CPIBond::observationLag_ [protected]
Definition at line 71 of file cpibond.hpp.
Referenced by CPIBond(), and observationLag().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/bonds/cpibond.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/bonds/cpibond.cpp