QuantLib: QuantLib::YoYInflationTermStructure Class Reference
QuantLib::YoYInflationTermStructure Class Reference
Base class for year-on-year inflation term structures.
#include <inflationtermstructure.hpp>
Public Member Functions
Constructors
YoYInflationTermStructure (const DayCounter &dayCounter, Rate baseYoYRate, const Period &lag, Frequency frequency, bool indexIsInterpolated, const Handle< YieldTermStructure > &yieldTS, const boost::shared_ptr< Seasonality > &seasonality=boost::shared_ptr< Seasonality >())
YoYInflationTermStructure (const Date &referenceDate, const Calendar &calendar, const DayCounter &dayCounter, Rate baseYoYRate, const Period &lag, Frequency frequency, bool indexIsInterpolated, const Handle< YieldTermStructure > &yieldTS, const boost::shared_ptr< Seasonality > &seasonality=boost::shared_ptr< Seasonality >())
YoYInflationTermStructure (Natural settlementDays, const Calendar &calendar, const DayCounter &dayCounter, Rate baseYoYRate, const Period &lag, Frequency frequency, bool indexIsInterpolated, const Handle< YieldTermStructure > &yieldTS, const boost::shared_ptr< Seasonality > &seasonality=boost::shared_ptr< Seasonality >())
Inspectors
Rate yoyRate (const Date &d, const Period &instObsLag=Period(-1, Days), bool forceLinearInterpolation=false, bool extrapolate=false) const
year-on-year inflation rate.
Rate yoyRate (Time t, bool extrapolate=false) const
year-on-year inflation rate.
Protected Member Functions
virtual Rate yoyRateImpl (Time time) const =0
to be defined in derived classes
Detailed Description
Base class for year-on-year inflation term structures.
Definition at line 195 of file inflationtermstructure.hpp.
Constructor & Destructor Documentation
QuantLib::YoYInflationTermStructure::YoYInflationTermStructure (const DayCounter & dayCounter, Rate baseYoYRate, const Period & lag, Frequency frequency, bool indexIsInterpolated, const Handle< YieldTermStructure > & yieldTS, const boost::shared_ptr< Seasonality > & seasonality = boost::shared_ptr<Seasonality>())
Definition at line 195 of file inflationtermstructure.cpp.
    : InflationTermStructure(baseYoYRate, observationLag, frequency, indexIsInterpolated,
                             yTS, dayCounter, seasonality) {}
QuantLib::YoYInflationTermStructure::YoYInflationTermStructure (const Date & referenceDate, const Calendar & calendar, const DayCounter & dayCounter, Rate baseYoYRate, const Period & lag, Frequency frequency, bool indexIsInterpolated, const Handle< YieldTermStructure > & yieldTS, const boost::shared_ptr< Seasonality > & seasonality = boost::shared_ptr<Seasonality>())
Definition at line 206 of file inflationtermstructure.cpp.
    : InflationTermStructure(referenceDate, baseYoYRate, observationLag, frequency, indexIsInterpolated,
                             yTS, calendar, dayCounter, seasonality) {}
QuantLib::YoYInflationTermStructure::YoYInflationTermStructure (Natural settlementDays, const Calendar & calendar, const DayCounter & dayCounter, Rate baseYoYRate, const Period & lag, Frequency frequency, bool indexIsInterpolated, const Handle< YieldTermStructure > & yieldTS, const boost::shared_ptr< Seasonality > & seasonality = boost::shared_ptr<Seasonality>())
Definition at line 219 of file inflationtermstructure.cpp.
    : InflationTermStructure(settlementDays, calendar, baseYoYRate, observationLag,
                             frequency, indexIsInterpolated,
                             yTS, dayCounter, seasonality) {}
Member Function Documentation
Rate QuantLib::YoYInflationTermStructure::yoyRate (const Date & d, const Period & instObsLag = Period(-1,Days), bool forceLinearInterpolation = false, bool extrapolate = false) const
year-on-year inflation rate.
The forceLinearInterpolation parameter is relative to the frequency of the TS.
Note:
this is not the year-on-year swap (YYIIS) rate.
Definition at line 234 of file inflationtermstructure.cpp.
References QuantLib::InflationTermStructure::checkRange(), QuantLib::Days, QuantLib::anonymous_namespace{yieldtermstructure.cpp}::dt, QuantLib::InflationTermStructure::frequency(), QuantLib::InflationTermStructure::hasSeasonality(), QuantLib::InflationTermStructure::indexIsInterpolated(), QuantLib::inflationPeriod(), QuantLib::InflationTermStructure::observationLag(), QuantLib::InflationTermStructure::seasonality(), anonymous_namespace{quantlibbenchmark.cpp}::t, QuantLib::TermStructure::timeFromReference(), and yoyRateImpl().
{
        Period useLag = instObsLag;
        if (instObsLag == Period(-1,Days)) {
            useLag = observationLag();
        }
        Rate yoyRate;
        if (forceLinearInterpolation) {
            std::pair<Date,Date> dd = inflationPeriod(d-useLag, frequency());
            dd.second = dd.second + Period(1,Days);
            Real dp = dd.second - dd.first;
            Real dt = (d-useLag) - dd.first;
            // if we are interpolating we only check the exact point
            // this prevents falling off the end at curve maturity
            InflationTermStructure::checkRange(d, extrapolate);
            Time t1 = timeFromReference(dd.first);
            Time t2 = timeFromReference(dd.second);
            yoyRate = yoyRateImpl(t1) + (yoyRateImpl(t2)-yoyRateImpl(t1)) * (dt/dp);
        } else {
            if (indexIsInterpolated()) {
                InflationTermStructure::checkRange(d-useLag, extrapolate);
                Time t = timeFromReference(d-useLag);
                yoyRate = yoyRateImpl(t);
            } else {
                std::pair<Date,Date> dd = inflationPeriod(d-useLag, frequency());
                InflationTermStructure::checkRange(dd.first, extrapolate);
                Time t = timeFromReference(dd.first);
                yoyRate = yoyRateImpl(t);
            }
        }
        if (hasSeasonality()) {
            yoyRate = seasonality()->correctYoYRate(d-useLag, yoyRate, *this);
        }
        return yoyRate;
    }
Rate QuantLib::YoYInflationTermStructure::yoyRate (Time t, bool extrapolate = false) const
year-on-year inflation rate.
Warning:
Since inflation is highly linked to dates (lags, interpolation, months for seasonality, etc) this method cannot account for all effects. If you call it, You'll have to manage lag, seasonality etc. yourself.
Definition at line 274 of file inflationtermstructure.cpp.
References QuantLib::InflationTermStructure::checkRange(), and yoyRateImpl().
{
        checkRange(t, extrapolate);
        return yoyRateImpl(t);
    }
virtual Rate QuantLib::YoYInflationTermStructure::yoyRateImpl (Time time) const [protected, pure virtual]
to be defined in derived classes
Implemented in QuantLib::InterpolatedYoYInflationCurve< Interpolator >.
Referenced by yoyRate().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/inflationtermstructure.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/inflationtermstructure.cpp