QuantLib: QuantLib::CTSMMCapletMaxHomogeneityCalibration Class Reference
QuantLib::CTSMMCapletMaxHomogeneityCalibration Class Reference
#include <capletcoterminalmaxhomogeneity.hpp>
Public Member Functions
CTSMMCapletMaxHomogeneityCalibration (const EvolutionDescription &evolution, const boost::shared_ptr< PiecewiseConstantCorrelation > &corr, const std::vector< boost::shared_ptr< PiecewiseConstantVariance > > &displacedSwapVariances, const std::vector< Volatility > &capletVols, const boost::shared_ptr< CurveState > &cs, Spread displacement, Real caplet0Swaption1Priority=1.0)
Static Public Member Functions
static Natural capletMaxHomogeneityCalibration (const EvolutionDescription &evolution, const PiecewiseConstantCorrelation &corr, const std::vector< boost::shared_ptr< PiecewiseConstantVariance > > &displacedSwapVariances, const std::vector< Volatility > &capletVols, const CurveState &cs, const Spread displacement, Real caplet0Swaption1Priority, Size numberOfFactors, Size maxIterations, Real tolerance, Real &deformationSize, Real &totalSwaptionError, std::vector< Matrix > &swapCovariancePseudoRoots)
Private Member Functions
Natural calibrationImpl_ (Natural numberOfFactors, Natural maxIterations, Real tolerance)
Private Attributes
Real caplet0Swaption1Priority_
Real totalSwaptionError_
Detailed Description
Definition at line 28 of file capletcoterminalmaxhomogeneity.hpp.
Constructor & Destructor Documentation
QuantLib::CTSMMCapletMaxHomogeneityCalibration::CTSMMCapletMaxHomogeneityCalibration (const EvolutionDescription & evolution, const boost::shared_ptr< PiecewiseConstantCorrelation > & corr, const std::vector< boost::shared_ptr< PiecewiseConstantVariance > > & displacedSwapVariances, const std::vector< Volatility > & capletVols, const boost::shared_ptr< CurveState > & cs, Spread displacement, Real caplet0Swaption1Priority = 1.0)
Definition at line 246 of file capletcoterminalmaxhomogeneity.cpp.
References QL_REQUIRE.
        : CTSMMCapletCalibration(evolution, corr, displacedSwapVariances,
        mktCapletVols, cs, displacement),
        caplet0Swaption1Priority_(caplet0Swaption1Priority) {
            QL_REQUIRE(caplet0Swaption1Priority>=0.0 &&
                caplet0Swaption1Priority<=1.0,
                "caplet0Swaption1Priority (" << caplet0Swaption1Priority <<
                ") must be in [0.0, 1.0]");
    }
Member Function Documentation
Natural QuantLib::CTSMMCapletMaxHomogeneityCalibration::calibrationImpl_ (Natural numberOfFactors, Natural maxIterations, Real tolerance) [private, virtual]
Implements QuantLib::CTSMMCapletCalibration.
Definition at line 398 of file capletcoterminalmaxhomogeneity.cpp.
References caplet0Swaption1Priority_, capletMaxHomogeneityCalibration(), QuantLib::CTSMMCapletCalibration::corr_, QuantLib::CTSMMCapletCalibration::cs_, QuantLib::CTSMMCapletCalibration::deformationSize_, QuantLib::CTSMMCapletCalibration::displacedSwapVariances_, QuantLib::CTSMMCapletCalibration::displacement_, QuantLib::CTSMMCapletCalibration::evolution_, QuantLib::CTSMMCapletCalibration::swapCovariancePseudoRoots_, totalSwaptionError_, and QuantLib::CTSMMCapletCalibration::usedCapletVols_.
{
            return capletMaxHomogeneityCalibration(evolution_,
                *corr_,
                displacedSwapVariances_,
                // not mktCapletVols_ but...
                usedCapletVols_,
                *cs_,
                displacement_,
                caplet0Swaption1Priority_,
                numberOfFactors,
                maxIterations,
                tolerance,
                deformationSize_,
                totalSwaptionError_,
                swapCovariancePseudoRoots_);
    }
Natural QuantLib::CTSMMCapletMaxHomogeneityCalibration::capletMaxHomogeneityCalibration (const EvolutionDescription & evolution, const PiecewiseConstantCorrelation & corr, const std::vector< boost::shared_ptr< PiecewiseConstantVariance > > & displacedSwapVariances, const std::vector< Volatility > & capletVols, const CurveState & cs, const Spread displacement, Real caplet0Swaption1Priority, Size numberOfFactors, Size maxIterations, Real tolerance, Real & deformationSize, Real & totalSwaptionError, std::vector< Matrix > & swapCovariancePseudoRoots) [static]
Definition at line 267 of file capletcoterminalmaxhomogeneity.cpp.
References QuantLib::Matrix::columns(), QuantLib::PiecewiseConstantCorrelation::correlation(), QuantLib::SwapForwardMappings::coterminalSwapZedMatrix(), QuantLib::CTSMMCapletCalibration::failures(), QuantLib::inverse(), QuantLib::SalvagingAlgorithm::None, QuantLib::EvolutionDescription::numberOfRates(), QuantLib::EvolutionDescription::numberOfSteps(), QuantLib::CTSMMCapletCalibration::performChecks(), QL_ENSURE, QL_REQUIRE, QuantLib::rankReducedSqrt(), QuantLib::EvolutionDescription::rateTimes(), anonymous_namespace{marketmodel.cpp}::rateTimes, QuantLib::anonymous_namespace{capletcoterminalmaxhomogeneity.cpp}::singleRateClosestPointFinder(), and QuantLib::PiecewiseConstantCorrelation::times().
Referenced by calibrationImpl_().
    {
            CTSMMCapletCalibration::performChecks(evolution, corr,
                displacedSwapVariances, capletVols, cs);
            Size numberOfSteps = evolution.numberOfSteps();
            Size numberOfRates = evolution.numberOfRates();
            const std::vector<Time>& rateTimes = evolution.rateTimes();
            QL_REQUIRE(numberOfFactors<=numberOfRates,
                "number of factors (" << numberOfFactors <<
                ") cannot be greater than numberOfRates (" <<
                numberOfRates << ")");
            QL_REQUIRE(numberOfFactors>0,
                "number of factors (" << numberOfFactors <<
                ") must be greater than zero");
            Natural failures=0;
            totalSwaptionError = 0.0;
            deformationSize = 0.0;
            // factor reduction
            std::vector<Matrix> corrPseudo(corr.times().size());
            for (Size i=0; i<corrPseudo.size(); ++i)
                corrPseudo[i] = rankReducedSqrt(corr.correlation(i),
                numberOfFactors, 1.0,
                SalvagingAlgorithm::None);
            // get Zinverse, we can get wj later
            Matrix zedMatrix =
                SwapForwardMappings::coterminalSwapZedMatrix(cs, displacement);
            Matrix invertedZedMatrix = inverse(zedMatrix);
            // vectors for the new vol of all swap rates
            std::vector<std::vector<Volatility> > newVols;
            std::vector<Volatility> theseNewVols(numberOfRates);
            std::vector<Volatility> firstRateVols(numberOfRates);
            firstRateVols[0] = std::sqrt(displacedSwapVariances[0]->variances()[0]);
            std::vector<Volatility> secondRateVols(numberOfRates);
            std::vector<Real> correlations(numberOfRates);
            newVols.push_back(firstRateVols);
            // final caplet and swaption are the same, so we skip that case
            for (Size i=0; i<numberOfRates-1; ++i)
            {
                // final weight dont do anything when i < 2
                Real thisFinalWeight = i  > 1 ? (i-1)/2.0 : 1.0;
                // we will calibrate caplet on forward rate i,
                // we will do this by modifying the vol of swap rate i+1
                const std::vector<Real>& var =
                    displacedSwapVariances[i+1]->variances();
                for (Size j =0; j < i+2; ++j)
                    secondRateVols[j] = std::sqrt(var[j]);
                for (Size k=0; k < i+1; k++) {
                    Real correlation=0.0;
                    for (Size l=0; l < numberOfFactors; ++l) {
                        Real term1 = corrPseudo[k][i][l];
                        Real term2 = corrPseudo[k][i+1][l];
                        correlation += term1*term2;
                    }
                    correlations[k] = correlation;
                }
                Real w0 = invertedZedMatrix[i][i];
                Real w1 = invertedZedMatrix[i][i+1];
                // w0 adjustment
                for (Size k = i+2; k <invertedZedMatrix.columns(); ++k)
                    w0+= invertedZedMatrix[i][k];
                Real targetCapletVariance= capletVols[i]*capletVols[i]*rateTimes[i];
                Real thisCapletError;
                Real thisSwaptionError;
                bool success = singleRateClosestPointFinder(
                    i, secondRateVols, firstRateVols, targetCapletVariance, correlations,
                    w0, w1, caplet0Swaption1Priority,maxIterations, tolerance,
                    theseNewVols, thisFinalWeight ,thisSwaptionError, thisCapletError);
                totalSwaptionError+= thisSwaptionError*thisSwaptionError;
                if (!success)
                    ++failures;
                for (Size j=0; j < i+2; ++j)
                    deformationSize += (theseNewVols[i]-secondRateVols[i])*(theseNewVols[i]-secondRateVols[i]);
                newVols.push_back(theseNewVols);
                firstRateVols = theseNewVols;
            }
            swapCovariancePseudoRoots.resize(numberOfSteps);
            for (Size k=0; k<numberOfSteps; ++k) {
                swapCovariancePseudoRoots[k] = corrPseudo[k];
                for (Size j=0; j<numberOfRates; ++j) {
                    Real coeff =newVols[j][k];
                    for (Size i=0; i<numberOfFactors; ++i)
                        swapCovariancePseudoRoots[k][j][i]*=coeff;
                }
                QL_ENSURE(swapCovariancePseudoRoots[k].rows()==numberOfRates,
                    "step " << k << " abcd vol wrong number of rows: " <<
                    swapCovariancePseudoRoots[k].rows() <<
                    " instead of " << numberOfRates);
                QL_ENSURE(swapCovariancePseudoRoots[k].columns()==numberOfFactors,
                    "step " << k << " abcd vol wrong number of columns: " <<
                    swapCovariancePseudoRoots[k].columns() <<
                    " instead of " << numberOfFactors);
            }
            return failures;
    }
Member Data Documentation
Real QuantLib::CTSMMCapletMaxHomogeneityCalibration::caplet0Swaption1Priority_ [private]
Definition at line 64 of file capletcoterminalmaxhomogeneity.hpp.
Referenced by calibrationImpl_().
Real QuantLib::CTSMMCapletMaxHomogeneityCalibration::totalSwaptionError_ [private]
Definition at line 66 of file capletcoterminalmaxhomogeneity.hpp.
Referenced by calibrationImpl_().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/models/capletcoterminalmaxhomogeneity.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/models/capletcoterminalmaxhomogeneity.cpp