QuantLib: QuantLib::Index Class Reference
QuantLib::Index Class Reference
purely virtual base class for indexes
#include <index.hpp>
Public Member Functions
virtual ~Index ()
virtual std::string name () const =0
Returns the name of the index.
virtual Calendar fixingCalendar () const =0
returns the calendar defining valid fixing dates
virtual bool isValidFixingDate (const Date &fixingDate) const =0
returns TRUE if the fixing date is a valid one
virtual Real fixing (const Date &fixingDate, bool forecastTodaysFixing=false) const =0
returns the fixing at the given date
const TimeSeries< Real > & timeSeries () const
returns the fixing TimeSeries
virtual void addFixing (const Date &fixingDate, Real fixing, bool forceOverwrite=false)
stores the historical fixing at the given date
void addFixings (const TimeSeries< Real > &t, bool forceOverwrite=false)
stores historical fixings from a TimeSeries
template<class DateIterator , class ValueIterator >
void addFixings (DateIterator dBegin, DateIterator dEnd, ValueIterator vBegin, bool forceOverwrite=false)
stores historical fixings at the given dates
void clearFixings ()
clears all stored historical fixings
Detailed Description
purely virtual base class for indexes
Warning:
this class performs no check that the provided/requested fixings are for dates in the past, i.e. for dates less than or equal to the evaluation date. It is up to the client code to take care of possible inconsistencies due to "seeing in the future"
Definition at line 44 of file index.hpp.
Constructor & Destructor Documentation
virtual QuantLib::Index::~Index () [inline, virtual]
Definition at line 46 of file index.hpp.
{}
Member Function Documentation
void QuantLib::Index::addFixing (const Date & fixingDate, Real fixing, bool forceOverwrite = false) [virtual]
stores the historical fixing at the given date
the date passed as arguments must be the actual calendar date of the fixing; no settlement days must be used.
Reimplemented in QuantLib::InflationIndex.
Definition at line 24 of file index.cpp.
References addFixings().
{
        addFixings(&fixingDate, (&fixingDate)+1,
                   &fixing,
                   forceOverwrite);
    }
void QuantLib::Index::addFixings (const TimeSeries< Real > & t, bool forceOverwrite = false)
stores historical fixings from a TimeSeries
the dates in the TimeSeries must be the actual calendar dates of the fixings; no settlement days must be used.
Definition at line 32 of file index.cpp.
References anonymous_namespace{marketmodel.cpp}::dates, QuantLib::TimeSeries< T, Container >::dates(), and QuantLib::TimeSeries< T, Container >::values().
Referenced by addFixing(), and QuantLib::InflationIndex::addFixing().
{
        // is there a way of iterating over dates and values
        // without having to make a copy?
        std::vector<Date> dates = t.dates();
        std::vector<Real> values = t.values();
        addFixings(dates.begin(), dates.end(),
                   values.begin(),
                   forceOverwrite);
    }
template<class DateIterator , class ValueIterator > void QuantLib::Index::addFixings (DateIterator dBegin, DateIterator dEnd, ValueIterator vBegin, bool forceOverwrite = false) [inline]
stores historical fixings at the given dates
the dates passed as arguments must be the actual calendar dates of the fixings; no settlement days must be used.
Definition at line 85 of file index.hpp.
References QuantLib::close(), QuantLib::IndexManager::getHistory(), QuantLib::Singleton< IndexManager >::instance(), isValidFixingDate(), name(), QL_REQUIRE, QuantLib::IndexManager::setHistory(), and QuantLib::Date::weekday().
{
            std::string tag = name();
            TimeSeries<Real> h = IndexManager::instance().getHistory(tag);
            bool missingFixing, validFixing;
            bool noInvalidFixing = true, noDuplicatedFixing = true;
            Date invalidDate, duplicatedDate;
            Real nullValue = Null<Real>();
            Real invalidValue = Null<Real>();
            Real duplicatedValue = Null<Real>();
            while (dBegin != dEnd) {
                validFixing = isValidFixingDate(*dBegin);
                Real currentValue = h[*dBegin];
                missingFixing= forceOverwrite || close(currentValue,nullValue);
                if (validFixing) {
                    if (missingFixing)
                        h[*(dBegin++)] = *(vBegin++);
                    else if (close(currentValue,*(vBegin))) {
                        ++dBegin;
                        ++vBegin;
                    } else {
                        noDuplicatedFixing = false;
                        duplicatedDate = *(dBegin++);
                        duplicatedValue = *(vBegin++);
                    }
                } else {
                    noInvalidFixing = false;
                    invalidDate = *(dBegin++);
                    invalidValue = *(vBegin++);
                }
            }
            IndexManager::instance().setHistory(tag, h);
            QL_REQUIRE(noInvalidFixing,
                       "At least one invalid fixing provided: " <<
                       invalidDate.weekday() << " " << invalidDate <<
                       ", " << invalidValue);
            QL_REQUIRE(noDuplicatedFixing,
                       "At least one duplicated fixing provided: " <<
                       duplicatedDate << ", " << duplicatedValue <<
                       " while " << h[duplicatedDate] <<
                       " value is already present");
        }
void QuantLib::Index::clearFixings ()
clears all stored historical fixings
Definition at line 43 of file index.cpp.
References QuantLib::IndexManager::clearHistory(), QuantLib::Singleton< IndexManager >::instance(), and name().
{
        IndexManager::instance().clearHistory(name());
    }
virtual Real QuantLib::Index::fixing (const Date & fixingDate, bool forecastTodaysFixing = false) const [pure virtual]
returns the fixing at the given date
the date passed as arguments must be the actual calendar date of the fixing; no settlement days must be used.
Implemented in QuantLib::YoYInflationIndex, QuantLib::ZeroInflationIndex, QuantLib::InflationIndex, and QuantLib::InterestRateIndex.
virtual Calendar QuantLib::Index::fixingCalendar () const [pure virtual]
returns the calendar defining valid fixing dates
Implemented in QuantLib::InflationIndex, and QuantLib::InterestRateIndex.
virtual bool QuantLib::Index::isValidFixingDate (const Date & fixingDate) const [pure virtual]
returns TRUE if the fixing date is a valid one
Implemented in QuantLib::InflationIndex, QuantLib::InterestRateIndex, and QuantLib::BMAIndex.
Referenced by addFixings().
virtual std::string QuantLib::Index::name () const [pure virtual]
Returns the name of the index.
Warning:
This method is used for output and comparison between indexes. It is not meant to be used for writing switch-on-type code.
Implemented in QuantLib::InflationIndex, QuantLib::InterestRateIndex, and QuantLib::BMAIndex.
Referenced by addFixings(), clearFixings(), and timeSeries().
const TimeSeries<Real>& QuantLib::Index::timeSeries () const [inline]
returns the fixing TimeSeries
Definition at line 64 of file index.hpp.
References QuantLib::IndexManager::getHistory(), QuantLib::Singleton< IndexManager >::instance(), and name().
Referenced by QuantLib::ZeroInflationIndex::fixing(), QuantLib::YoYInflationIndex::fixing(), QuantLib::ZeroInflationIndex::needsForecast(), and QuantLib::InterestRateIndex::pastFixing().
{
            return IndexManager::instance().getHistory(name());
        }
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/index.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/index.cpp