QuantLib: QuantLib::FixedRateBondForward Class Reference
QuantLib::FixedRateBondForward Class Reference
Forward contract on a fixed-rate bond
#include <fixedratebondforward.hpp>
Public Member Functions
Constructors
FixedRateBondForward (const Date &valueDate, const Date &maturityDate, Position::Type type, Real strike, Natural settlementDays, const DayCounter &dayCounter, const Calendar &calendar, BusinessDayConvention businessDayConvention, const boost::shared_ptr< FixedRateBond > &fixedCouponBond, const Handle< YieldTermStructure > &discountCurve=Handle< YieldTermStructure >(), const Handle< YieldTermStructure > &incomeDiscountCurve=Handle< YieldTermStructure >())
Calculations
Real forwardPrice () const
(dirty) forward bond price
Real cleanForwardPrice () const
(dirty) forward bond price minus accrued on bond at delivery
Real spotIncome (const Handle< YieldTermStructure > &incomeDiscountCurve) const
NPV of bond coupons discounted using incomeDiscountCurve.
Real spotValue () const
NPV of underlying bond.
Protected Member Functions
void performCalculations () const
Protected Attributes
boost::shared_ptr< FixedRateBond > fixedCouponBond_
Detailed Description
Forward contract on a fixed-rate bond
1. valueDate refers to the settlement date of the bond forward contract. maturityDate is the delivery (or repurchase) date for the underlying bond (not the bond's maturity date).
2. Relevant formulas used in the calculations (\(P\) refers to a price):
a. \(P_{CleanFwd}(t) = P_{DirtyFwd}(t) - AI(t=deliveryDate) \) where \(AI \) refers to the accrued interest on the underlying bond.
b. \(P_{DirtyFwd}(t) = \frac{P_{DirtySpot}(t) - SpotIncome(t)} {discountCurve->discount(t=deliveryDate)} \)
c. \(SpotIncome(t) = \sum_i \left(CF_i \times incomeDiscountCurve->discount(t_i) \right) \) where \(CF_i \) represents the ith bond cash flow (coupon payment) associated with the underlying bond falling between the settlementDate and the deliveryDate. (Note the two different discount curves used in b. and c.)
Example: valuation of a repo on a fixed-rate bond
Todo:
Add preconditions and tests
Todo:
Create switch- if coupon goes to seller is toggled on, don't consider income in the \(P_{DirtyFwd}(t) \) calculation.
Todo:
Verify this works when the underlying is paper (in which case ignore all AI.)
Warning:
This class still needs to be rigorously tested
Definition at line 73 of file fixedratebondforward.hpp.
Constructor & Destructor Documentation
QuantLib::FixedRateBondForward::FixedRateBondForward (const Date & valueDate, const Date & maturityDate, Position::Type type, Real strike, Natural settlementDays, const DayCounter & dayCounter, const Calendar & calendar, BusinessDayConvention businessDayConvention, const boost::shared_ptr< FixedRateBond > & fixedCouponBond, const Handle< YieldTermStructure > & discountCurve = Handle<YieldTermStructure>(), const Handle< YieldTermStructure > & incomeDiscountCurve = Handle<YieldTermStructure>())
If strike is given in the constructor, can calculate the NPV of the contract via NPV().
If strike/forward price is desired, it can be obtained via forwardPrice(). In this case, the strike variable in the constructor is irrelevant and will be ignored.
Definition at line 26 of file fixedratebondforward.cpp.
References QuantLib::Forward::incomeDiscountCurve(), QuantLib::Forward::incomeDiscountCurve_, and QuantLib::Observer::registerWith().
    : Forward(dayCounter, calendar, businessDayConvention, settlementDays,
              boost::shared_ptr<Payoff>(new ForwardTypePayoff(type,strike)),
              valueDate, maturityDate, discountCurve),
      fixedCouponBond_(fixedCouponBond) {
        incomeDiscountCurve_ = incomeDiscountCurve;
        registerWith(incomeDiscountCurve_);
    }
Member Function Documentation
Real QuantLib::FixedRateBondForward::cleanForwardPrice () const
(dirty) forward bond price minus accrued on bond at delivery
Definition at line 48 of file fixedratebondforward.cpp.
References fixedCouponBond_, QuantLib::Forward::forwardValue(), and QuantLib::Forward::maturityDate_.
{
        return forwardValue() -
               fixedCouponBond_->accruedAmount(maturityDate_);
    }
Real QuantLib::FixedRateBondForward::forwardPrice () const
(dirty) forward bond price
Definition at line 54 of file fixedratebondforward.cpp.
References QuantLib::Forward::forwardValue().
{
        return forwardValue();
    }
void QuantLib::FixedRateBondForward::performCalculations () const [protected, virtual]
In case a pricing engine is not used, this method must be overridden to perform the actual calculations and set any needed results. In case a pricing engine is used, the default implementation can be used.
Reimplemented from QuantLib::Forward.
Definition at line 93 of file fixedratebondforward.cpp.
References QuantLib::Forward::incomeDiscountCurve_, spotIncome(), spotValue(), QuantLib::Forward::underlyingIncome_, and QuantLib::Forward::underlyingSpotValue_.
{
        underlyingSpotValue_ = spotValue();
        underlyingIncome_    = spotIncome(incomeDiscountCurve_);
        Forward::performCalculations();
    }
Real QuantLib::FixedRateBondForward::spotIncome (const Handle< YieldTermStructure > & incomeDiscountCurve) const [virtual]
NPV of bond coupons discounted using incomeDiscountCurve.
Here only coupons between max(evaluation date,settlement date) and maturity date of bond forward contract are considered income.
Implements QuantLib::Forward.
Definition at line 59 of file fixedratebondforward.cpp.
References fixedCouponBond_, QuantLib::Forward::maturityDate_, and QuantLib::Forward::settlementDate().
Referenced by performCalculations().
{
        Real income = 0.0;
        Date settlement = settlementDate();
        Leg cf =
            fixedCouponBond_->cashflows();
        /*
          the following assumes
          1. cashflows are in ascending order !
          2. considers as income: all coupons paid between settlementDate()
          and contract delivery/maturity date
        */
        for (Size i = 0; i < cf.size(); ++i) {
            if (!cf[i]->hasOccurred(settlement, false)) {
                if (cf[i]->hasOccurred(maturityDate_, false)) {
                    income += cf[i]->amount() *
                              incomeDiscountCurve->discount(cf[i]->date()) ;
                } else {
                    break;
                }
            }
        }
        return income;
    }
Real QuantLib::FixedRateBondForward::spotValue () const [virtual]
NPV of underlying bond.
Implements QuantLib::Forward.
Definition at line 88 of file fixedratebondforward.cpp.
References fixedCouponBond_.
Referenced by performCalculations().
{
        return fixedCouponBond_->dirtyPrice();
    }
Member Data Documentation
boost::shared_ptr<FixedRateBond> QuantLib::FixedRateBondForward::fixedCouponBond_ [protected]
Definition at line 123 of file fixedratebondforward.hpp.
Referenced by cleanForwardPrice(), spotIncome(), and spotValue().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/fixedratebondforward.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/fixedratebondforward.cpp