QuantLib: QuantLib::BlackIborQuantoCouponPricer Class Reference
QuantLib::BlackIborQuantoCouponPricer Class Reference
#include <quantocouponpricer.hpp>
Public Member Functions
BlackIborQuantoCouponPricer (const Handle< BlackVolTermStructure > &fxRateBlackVolatility, const Handle< Quote > &underlyingFxCorrelation, const Handle< OptionletVolatilityStructure > &capletVolatility)
Protected Member Functions
Rate adjustedFixing (Rate fixing=Null< Rate >()) const
Private Attributes
Handle< BlackVolTermStructure > fxRateBlackVolatility_
Handle< Quote > underlyingFxCorrelation_
Detailed Description
Definition at line 33 of file quantocouponpricer.hpp.
Constructor & Destructor Documentation
QuantLib::BlackIborQuantoCouponPricer::BlackIborQuantoCouponPricer (const Handle< BlackVolTermStructure > & fxRateBlackVolatility, const Handle< Quote > & underlyingFxCorrelation, const Handle< OptionletVolatilityStructure > & capletVolatility) [inline]
Definition at line 35 of file quantocouponpricer.hpp.
References fxRateBlackVolatility_, QuantLib::Observer::registerWith(), and underlyingFxCorrelation_.
        : BlackIborCouponPricer(capletVolatility),
          fxRateBlackVolatility_(fxRateBlackVolatility),
          underlyingFxCorrelation_(underlyingFxCorrelation) {
            registerWith(fxRateBlackVolatility_);
            registerWith(underlyingFxCorrelation_);
        }
Member Function Documentation
Rate QuantLib::BlackIborQuantoCouponPricer::adjustedFixing (Rate fixing = Null<Rate>()) const [protected, virtual]
Reimplemented from QuantLib::BlackIborCouponPricer.
Definition at line 31 of file quantocouponpricer.cpp.
References QuantLib::IborCouponPricer::capletVolatility(), QuantLib::BlackIborCouponPricer::coupon_, QuantLib::FloatingRateCoupon::fixingDate(), fxRateBlackVolatility_, QuantLib::FloatingRateCoupon::index(), QuantLib::FloatingRateCoupon::indexFixing(), anonymous_namespace{distributions.cpp}::sigma, and underlyingFxCorrelation_.
{
        if (fixing == Null<Rate>())
            fixing = coupon_->indexFixing();
        // Here we apply the quanto adjustment first, then delegate to
        // the parent class
        Date d1 = coupon_->fixingDate(),
             referenceDate = capletVolatility()->referenceDate();
        if (d1 > referenceDate) {
            Time t1 =
                coupon_->index()->dayCounter().yearFraction(referenceDate, d1);
            Volatility fxsigma =
                fxRateBlackVolatility_->blackVol(t1, fixing, true);
            Volatility sigma = capletVolatility()->volatility(d1, fixing);
            Real rho = underlyingFxCorrelation_->value();
            // Apply Quanto Adjustment.
            // Hull 6th Edition, page 642.
            Real dQuantoAdj = std::exp(sigma*fxsigma*rho*t1);
            fixing *= dQuantoAdj;
        }
        return BlackIborCouponPricer::adjustedFixing(fixing);
    }
Member Data Documentation
Handle<BlackVolTermStructure> QuantLib::BlackIborQuantoCouponPricer::fxRateBlackVolatility_ [private]
Definition at line 50 of file quantocouponpricer.hpp.
Referenced by adjustedFixing(), and BlackIborQuantoCouponPricer().
Handle<Quote> QuantLib::BlackIborQuantoCouponPricer::underlyingFxCorrelation_ [private]
Definition at line 51 of file quantocouponpricer.hpp.
Referenced by adjustedFixing(), and BlackIborQuantoCouponPricer().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/coupons/quantocouponpricer.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/coupons/quantocouponpricer.cpp