QuantLib: QuantLib::FuturesConvAdjustmentQuote Class Reference
QuantLib::FuturesConvAdjustmentQuote Class Reference
quote for the futures-convexity adjustment of an index
#include <futuresconvadjustmentquote.hpp>
Public Member Functions
FuturesConvAdjustmentQuote (const boost::shared_ptr< IborIndex > &index, const Date &futuresDate, const Handle< Quote > &futuresQuote, const Handle< Quote > &volatility, const Handle< Quote > &meanReversion)
FuturesConvAdjustmentQuote (const boost::shared_ptr< IborIndex > &index, const std::string &immCode, const Handle< Quote > &futuresQuote, const Handle< Quote > &volatility, const Handle< Quote > &meanReversion)
void update ()
Quote interface
Real value () const
returns the current value
bool isValid () const
returns true if the Quote holds a valid value
Inspectors
Real futuresValue () const
Real volatility () const
Real meanReversion () const
Date immDate () const
Protected Attributes
DayCounter dc_
const Date futuresDate_
const Date indexMaturityDate_
Handle< Quote > futuresQuote_
Handle< Quote > volatility_
Handle< Quote > meanReversion_
Detailed Description
quote for the futures-convexity adjustment of an index
Definition at line 36 of file futuresconvadjustmentquote.hpp.
Constructor & Destructor Documentation
QuantLib::FuturesConvAdjustmentQuote::FuturesConvAdjustmentQuote (const boost::shared_ptr< IborIndex > & index, const Date & futuresDate, const Handle< Quote > & futuresQuote, const Handle< Quote > & volatility, const Handle< Quote > & meanReversion)
Definition at line 26 of file futuresconvadjustmentquote.cpp.
References futuresQuote_, meanReversion_, QuantLib::Observer::registerWith(), and volatility_.
    : dc_(index->dayCounter()),
      futuresDate_(futuresDate),
      indexMaturityDate_(index->maturityDate(futuresDate_)),
      futuresQuote_(futuresQuote),
      volatility_(volatility), meanReversion_(meanReversion) {
        registerWith(futuresQuote_);
        registerWith(volatility_);
        registerWith(meanReversion_);
    }
QuantLib::FuturesConvAdjustmentQuote::FuturesConvAdjustmentQuote (const boost::shared_ptr< IborIndex > & index, const std::string & immCode, const Handle< Quote > & futuresQuote, const Handle< Quote > & volatility, const Handle< Quote > & meanReversion)
Definition at line 43 of file futuresconvadjustmentquote.cpp.
References futuresQuote_, meanReversion_, QuantLib::Observer::registerWith(), and volatility_.
    : dc_(index->dayCounter()),
      futuresDate_(IMM::date(immCode)),
      indexMaturityDate_(index->maturityDate(futuresDate_)),
      futuresQuote_(futuresQuote),
      volatility_(volatility), meanReversion_(meanReversion) {
        registerWith(futuresQuote_);
        registerWith(volatility_);
        registerWith(meanReversion_);
    }
Member Function Documentation
Real QuantLib::FuturesConvAdjustmentQuote::futuresValue () const [inline]
Definition at line 57 of file futuresconvadjustmentquote.hpp.
References futuresQuote_.
{ return futuresQuote_->value(); }
Date QuantLib::FuturesConvAdjustmentQuote::immDate () const [inline]
Definition at line 60 of file futuresconvadjustmentquote.hpp.
References futuresDate_.
{ return futuresDate_; }
bool QuantLib::FuturesConvAdjustmentQuote::isValid () const [virtual]
returns true if the Quote holds a valid value
Implements QuantLib::Quote.
Definition at line 73 of file futuresconvadjustmentquote.cpp.
References QuantLib::Handle< T >::empty(), futuresQuote_, meanReversion_, and volatility_.
{
        return !futuresQuote_.empty() && !volatility_.empty() &&
               !meanReversion_.empty() && futuresQuote_->isValid() &&
               volatility_->isValid() && meanReversion_->isValid();
    }
Real QuantLib::FuturesConvAdjustmentQuote::meanReversion () const [inline]
Definition at line 59 of file futuresconvadjustmentquote.hpp.
References meanReversion_.
{ return meanReversion_->value(); }
void QuantLib::FuturesConvAdjustmentQuote::update () [inline, virtual]
This method must be implemented in derived classes. An instance of Observer does not call this method directly: instead, it will be called by the observables the instance registered with when they need to notify any changes.
Implements QuantLib::Observer.
Definition at line 72 of file futuresconvadjustmentquote.hpp.
References QuantLib::Observable::notifyObservers().
{
        notifyObservers();
    }
Real QuantLib::FuturesConvAdjustmentQuote::value () const [virtual]
returns the current value
Implements QuantLib::Quote.
Definition at line 60 of file futuresconvadjustmentquote.cpp.
References QuantLib::HullWhite::convexityBias(), dc_, QuantLib::Settings::evaluationDate(), futuresDate_, futuresQuote_, indexMaturityDate_, QuantLib::Singleton< Settings >::instance(), meanReversion_, volatility_, and QuantLib::DayCounter::yearFraction().
{
        Date settlementDate = Settings::instance().evaluationDate();
        Time startTime = dc_.yearFraction(settlementDate, futuresDate_);
        Time indexMaturity = dc_.yearFraction(settlementDate,
                                              indexMaturityDate_);
        return HullWhite::convexityBias(futuresQuote_->value(),
                                        startTime,
                                        indexMaturity,
                                        volatility_->value(),
                                        meanReversion_->value());
    }
Real QuantLib::FuturesConvAdjustmentQuote::volatility () const [inline]
Definition at line 58 of file futuresconvadjustmentquote.hpp.
References volatility_.
{ return volatility_->value(); }
Member Data Documentation
DayCounter QuantLib::FuturesConvAdjustmentQuote::dc_ [protected]
Definition at line 63 of file futuresconvadjustmentquote.hpp.
Referenced by value().
const Date QuantLib::FuturesConvAdjustmentQuote::futuresDate_ [protected]
Definition at line 64 of file futuresconvadjustmentquote.hpp.
Referenced by immDate(), and value().
Handle<Quote> QuantLib::FuturesConvAdjustmentQuote::futuresQuote_ [protected]
Definition at line 65 of file futuresconvadjustmentquote.hpp.
Referenced by FuturesConvAdjustmentQuote(), futuresValue(), isValid(), and value().
const Date QuantLib::FuturesConvAdjustmentQuote::indexMaturityDate_ [protected]
Definition at line 64 of file futuresconvadjustmentquote.hpp.
Referenced by value().
Handle<Quote> QuantLib::FuturesConvAdjustmentQuote::meanReversion_ [protected]
Definition at line 67 of file futuresconvadjustmentquote.hpp.
Referenced by FuturesConvAdjustmentQuote(), isValid(), meanReversion(), and value().
Handle<Quote> QuantLib::FuturesConvAdjustmentQuote::volatility_ [protected]
Definition at line 66 of file futuresconvadjustmentquote.hpp.
Referenced by FuturesConvAdjustmentQuote(), isValid(), value(), and volatility().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/quotes/futuresconvadjustmentquote.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/quotes/futuresconvadjustmentquote.cpp