QuantLib: QuantLib::SwaptionHelper Class Reference
QuantLib::SwaptionHelper Class Reference
calibration helper for ATM swaption
#include <swaptionhelper.hpp>
Public Member Functions
SwaptionHelper (const Period &maturity, const Period &length, const Handle< Quote > &volatility, const boost::shared_ptr< IborIndex > &index, const Period &fixedLegTenor, const DayCounter &fixedLegDayCounter, const DayCounter &floatingLegDayCounter, const Handle< YieldTermStructure > &termStructure, CalibrationHelper::CalibrationErrorType errorType=CalibrationHelper::RelativePriceError)
virtual void addTimesTo (std::list< Time > &times) const
virtual Real modelValue () const
returns the price of the instrument according to the model
virtual Real blackPrice (Volatility volatility) const
Black price given a volatility.
Private Attributes
Rate exerciseRate_
boost::shared_ptr< VanillaSwap > swap_
boost::shared_ptr< Swaption > swaption_
Detailed Description
calibration helper for ATM swaption
Bug:
This helper does not register with the passed IBOR index and with the evaluation date. Furthermore, the ATM exercise rate is not recalculated when any of its observables change.
Definition at line 38 of file swaptionhelper.hpp.
Constructor & Destructor Documentation
QuantLib::SwaptionHelper::SwaptionHelper (const Period & maturity, const Period & length, const Handle< Quote > & volatility, const boost::shared_ptr< IborIndex > & index, const Period & fixedLegTenor, const DayCounter & fixedLegDayCounter, const DayCounter & floatingLegDayCounter, const Handle< YieldTermStructure > & termStructure, CalibrationHelper::CalibrationErrorType errorType = CalibrationHelper::RelativePriceError)
Definition at line 31 of file swaptionhelper.cpp.
References QuantLib::Calendar::advance(), blackPrice(), anonymous_namespace{marketmodel.cpp}::calendar, QuantLib::Days, anonymous_namespace{marketmodel.cpp}::endDate, QuantLib::CalibrationHelper::engine_, exerciseRate_, QuantLib::VanillaSwap::fairRate(), QuantLib::DateGeneration::Forward, QuantLib::CalibrationHelper::marketValue_, QuantLib::VanillaSwap::Receiver, QuantLib::Instrument::setPricingEngine(), anonymous_namespace{marketmodel.cpp}::startDate, swap_, swaption_, and QuantLib::CalibrationHelper::volatility_.
    : CalibrationHelper(volatility,termStructure, errorType) {
        Calendar calendar = index->fixingCalendar();
        Natural fixingDays = index->fixingDays();
        Date exerciseDate = calendar.advance(termStructure->referenceDate(),
                                             maturity,
                                             index->businessDayConvention());
        Date startDate = calendar.advance(exerciseDate,
                                          fixingDays, Days,
                                          index->businessDayConvention());
        Date endDate = calendar.advance(startDate, length,
                                        index->businessDayConvention());
        Schedule fixedSchedule(startDate, endDate, fixedLegTenor, calendar,
                               index->businessDayConvention(),
                               index->businessDayConvention(),
                               DateGeneration::Forward, false);
        Schedule floatSchedule(startDate, endDate, index->tenor(), calendar,
                               index->businessDayConvention(),
                               index->businessDayConvention(),
                               DateGeneration::Forward, false);
        boost::shared_ptr<PricingEngine> swapEngine(
                             new DiscountingSwapEngine(termStructure, false));
        VanillaSwap temp(VanillaSwap::Receiver, 1.0,
                         fixedSchedule, 0.0, fixedLegDayCounter,
                         floatSchedule, index, 0.0, floatingLegDayCounter);
        temp.setPricingEngine(swapEngine);
        exerciseRate_ = temp.fairRate();
        swap_ = boost::shared_ptr<VanillaSwap>(
            new VanillaSwap(VanillaSwap::Receiver, 1.0,
                            fixedSchedule, exerciseRate_, fixedLegDayCounter,
                            floatSchedule, index, 0.0, floatingLegDayCounter));
        swap_->setPricingEngine(swapEngine);
        engine_  = boost::shared_ptr<PricingEngine>();
        boost::shared_ptr<Exercise> exercise(
                                          new EuropeanExercise(exerciseDate));
        swaption_ = boost::shared_ptr<Swaption>(new Swaption(swap_, exercise));
        marketValue_ = blackPrice(volatility_->value());
    }
Member Function Documentation
void QuantLib::SwaptionHelper::addTimesTo (std::list< Time > & times) const [virtual]
Implements QuantLib::CalibrationHelper.
Definition at line 84 of file swaptionhelper.cpp.
References swaption_, and QuantLib::CalibrationHelper::termStructure_.
{
        Swaption::arguments args;
        swaption_->setupArguments(&args);
        std::vector<Time> swaptionTimes =
            DiscretizedSwaption(args,
                                termStructure_->referenceDate(),
                                termStructure_->dayCounter()).mandatoryTimes();
        times.insert(times.end(),
                     swaptionTimes.begin(), swaptionTimes.end());
    }
Real QuantLib::SwaptionHelper::blackPrice (Volatility volatility) const [virtual]
Black price given a volatility.
Implements QuantLib::CalibrationHelper.
Definition at line 100 of file swaptionhelper.cpp.
References QuantLib::CalibrationHelper::engine_, swaption_, and QuantLib::CalibrationHelper::termStructure_.
Referenced by SwaptionHelper().
{
        Handle<Quote> vol(boost::shared_ptr<Quote>(new SimpleQuote(sigma)));
        boost::shared_ptr<PricingEngine> black(new
                                    BlackSwaptionEngine(termStructure_, vol));
        swaption_->setPricingEngine(black);
        Real value = swaption_->NPV();
        swaption_->setPricingEngine(engine_);
        return value;
    }
Real QuantLib::SwaptionHelper::modelValue () const [virtual]
returns the price of the instrument according to the model
Implements QuantLib::CalibrationHelper.
Definition at line 95 of file swaptionhelper.cpp.
References QuantLib::CalibrationHelper::engine_, and swaption_.
{
        swaption_->setPricingEngine(engine_);
        return swaption_->NPV();
    }
Member Data Documentation
Rate QuantLib::SwaptionHelper::exerciseRate_ [private]
Definition at line 54 of file swaptionhelper.hpp.
Referenced by SwaptionHelper().
boost::shared_ptr<VanillaSwap> QuantLib::SwaptionHelper::swap_ [private]
Definition at line 55 of file swaptionhelper.hpp.
Referenced by SwaptionHelper().
boost::shared_ptr<Swaption> QuantLib::SwaptionHelper::swaption_ [private]
Definition at line 56 of file swaptionhelper.hpp.
Referenced by addTimesTo(), blackPrice(), modelValue(), and SwaptionHelper().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/shortrate/calibrationhelpers/swaptionhelper.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/shortrate/calibrationhelpers/swaptionhelper.cpp