QuantLib: QuantLib::AnalyticCapFloorEngine Class Reference
QuantLib::AnalyticCapFloorEngine Class Reference
Analytic engine for cap/floor.
#include <analyticcapfloorengine.hpp>
Public Member Functions
AnalyticCapFloorEngine (const boost::shared_ptr< AffineModel > &model, const Handle< YieldTermStructure > &termStructure=Handle< YieldTermStructure >())
void calculate () const
Private Attributes
Handle< YieldTermStructure > termStructure_
Detailed Description
Analytic engine for cap/floor.
Definition at line 35 of file analyticcapfloorengine.hpp.
Constructor & Destructor Documentation
QuantLib::AnalyticCapFloorEngine::AnalyticCapFloorEngine (const boost::shared_ptr< AffineModel > & model, const Handle< YieldTermStructure > & termStructure = Handle<YieldTermStructure>())
Note:
the term structure is only needed when the short-rate model cannot provide one itself.
Definition at line 24 of file analyticcapfloorengine.cpp.
References QuantLib::Observer::registerWith(), and termStructure_.
    : GenericModelEngine<AffineModel,
                         CapFloor::arguments,
                         CapFloor::results >(model),
      termStructure_(termStructure) {
        registerWith(termStructure_);
    }
Member Function Documentation
void QuantLib::AnalyticCapFloorEngine::calculate () const [virtual]
Implements QuantLib::PricingEngine.
Definition at line 35 of file analyticcapfloorengine.cpp.
References QuantLib::CapFloor::arguments::accrualTimes, QuantLib::GenericEngine< CapFloor::arguments, CapFloor::results >::arguments_, QuantLib::Option::Call, QuantLib::CapFloor::Cap, QuantLib::CapFloor::arguments::capRates, QuantLib::CapFloor::Collar, anonymous_namespace{marketmodel.cpp}::dayCounter, QuantLib::Handle< T >::empty(), QuantLib::CapFloor::arguments::endDates, QuantLib::CapFloor::arguments::fixingDates, QuantLib::CapFloor::Floor, QuantLib::CapFloor::arguments::floorRates, QuantLib::CapFloor::arguments::forwards, QuantLib::CapFloor::arguments::gearings, QuantLib::Settings::includeReferenceDateEvents(), QuantLib::Settings::includeTodaysCashFlows(), QuantLib::Singleton< Settings >::instance(), QuantLib::GenericModelEngine< AffineModel, CapFloor::arguments, CapFloor::results >::model_, QuantLib::CapFloor::arguments::nominals, QuantLib::Option::Put, QL_REQUIRE, QuantLib::GenericEngine< CapFloor::arguments, CapFloor::results >::results_, QuantLib::CapFloor::arguments::startDates, QuantLib::TermStructureConsistentModel::termStructure(), termStructure_, QuantLib::CapFloor::arguments::type, and QuantLib::DayCounter::yearFraction().
{
        QL_REQUIRE(!model_.empty(), "null model");
        Date referenceDate;
        DayCounter dayCounter;
        boost::shared_ptr<TermStructureConsistentModel> tsmodel =
            boost::dynamic_pointer_cast<TermStructureConsistentModel>(*model_);
        if (tsmodel) {
            referenceDate = tsmodel->termStructure()->referenceDate();
            dayCounter = tsmodel->termStructure()->dayCounter();
        } else {
            referenceDate = termStructure_->referenceDate();
            dayCounter = termStructure_->dayCounter();
        }
        Real value = 0.0;
        CapFloor::Type type = arguments_.type;
        Size nPeriods = arguments_.endDates.size();
        bool includeRefDatePayments =
            Settings::instance().includeReferenceDateEvents();
        if (referenceDate == Settings::instance().evaluationDate()) {
            boost::optional<bool> includeTodaysPayments =
                Settings::instance().includeTodaysCashFlows();
            if (includeTodaysPayments)
                includeRefDatePayments = *includeTodaysPayments;
        }
        for (Size i=0; i<nPeriods; i++) {
            Time fixingTime =
                dayCounter.yearFraction(referenceDate,
                                        arguments_.fixingDates[i]);
            Time paymentTime =
                dayCounter.yearFraction(referenceDate,
                                        arguments_.endDates[i]);
            bool not_expired =
                includeRefDatePayments ? paymentTime >= 0.0 : paymentTime > 0.0;
            if (not_expired) {
                Time tenor = arguments_.accrualTimes[i];
                Rate fixing = arguments_.forwards[i];
                if (fixingTime <= 0.0) {
                    if (type == CapFloor::Cap || type == CapFloor::Collar) {
                        DiscountFactor discount = model_->discount(paymentTime);
                        Rate strike = arguments_.capRates[i];
                        value += discount * arguments_.nominals[i] * tenor
                               * arguments_.gearings[i]
                               * std::max(0.0, fixing - strike);
                    }
                    if (type == CapFloor::Floor || type == CapFloor::Collar) {
                        DiscountFactor discount = model_->discount(paymentTime);
                        Rate strike = arguments_.floorRates[i];
                        Real mult = (type == CapFloor::Floor) ? 1.0 : -1.0;
                        value += discount * arguments_.nominals[i] * tenor
                               * mult * arguments_.gearings[i]
                               * std::max(0.0, strike - fixing);
                    }
                } else {
                    Time maturity =
                        dayCounter.yearFraction(referenceDate,
                                                arguments_.startDates[i]);
                    if (type == CapFloor::Cap || type == CapFloor::Collar) {
                        Real temp = 1.0+arguments_.capRates[i]*tenor;
                        value += arguments_.nominals[i] *
                            arguments_.gearings[i] * temp *
                            model_->discountBondOption(Option::Put, 1.0/temp,
                                                       maturity, paymentTime);
                    }
                    if (type == CapFloor::Floor || type == CapFloor::Collar) {
                        Real temp = 1.0+arguments_.floorRates[i]*tenor;
                        Real mult = (type == CapFloor::Floor) ? 1.0 : -1.0;
                        value += arguments_.nominals[i] *
                            arguments_.gearings[i] * temp * mult *
                            model_->discountBondOption(Option::Call, 1.0/temp,
                                                       maturity, paymentTime);
                    }
                }
            }
        }
        results_.value = value;
    }
Member Data Documentation
Handle<YieldTermStructure> QuantLib::AnalyticCapFloorEngine::termStructure_ [private]
Definition at line 49 of file analyticcapfloorengine.hpp.
Referenced by AnalyticCapFloorEngine(), and calculate().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/capfloor/analyticcapfloorengine.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/capfloor/analyticcapfloorengine.cpp