QuantLib: QuantLib::AccountingEngine Class Reference
QuantLib::AccountingEngine Class Reference
Engine collecting cash flows along a market-model simulation.
#include <accountingengine.hpp>
Public Member Functions
AccountingEngine (const boost::shared_ptr< MarketModelEvolver > &evolver, const Clone< MarketModelMultiProduct > &product, Real initialNumeraireValue)
void multiplePathValues (SequenceStatisticsInc &stats, Size numberOfPaths)
Private Member Functions
Real singlePathValues (std::vector< Real > &values)
Private Attributes
boost::shared_ptr
< MarketModelEvolver > evolver_
Clone< MarketModelMultiProduct > product_
Real initialNumeraireValue_
Size numberProducts_
std::vector< Real > numerairesHeld_
std::vector< Size > numberCashFlowsThisStep_
std::vector< std::vector
< MarketModelMultiProduct::CashFlow > > cashFlowsGenerated_
std::vector
< MarketModelDiscounter > discounters_
Detailed Description
Engine collecting cash flows along a market-model simulation.
Definition at line 44 of file accountingengine.hpp.
Constructor & Destructor Documentation
QuantLib::AccountingEngine::AccountingEngine (const boost::shared_ptr< MarketModelEvolver > & evolver, const Clone< MarketModelMultiProduct > & product, Real initialNumeraireValue)
Definition at line 29 of file accountingengine.cpp.
References cashFlowsGenerated_, discounters_, QuantLib::MarketModelMultiProduct::evolution(), QuantLib::MarketModelMultiProduct::maxNumberOfCashFlowsPerProductPerStep(), numberProducts_, QuantLib::MarketModelMultiProduct::possibleCashFlowTimes(), product_, QuantLib::EvolutionDescription::rateTimes(), and anonymous_namespace{marketmodel.cpp}::rateTimes.
    : evolver_(evolver), product_(product),
      initialNumeraireValue_(initialNumeraireValue),
      numberProducts_(product->numberOfProducts()),
      numerairesHeld_(product->numberOfProducts()),
      numberCashFlowsThisStep_(product->numberOfProducts()),
      cashFlowsGenerated_(product->numberOfProducts()) {
        for (Size i=0; i<numberProducts_; ++i)
            cashFlowsGenerated_[i].resize(
                       product_->maxNumberOfCashFlowsPerProductPerStep());
        const std::vector<Time>& cashFlowTimes =
            product_->possibleCashFlowTimes();
        const std::vector<Rate>& rateTimes = product_->evolution().rateTimes();
        discounters_.reserve(cashFlowTimes.size());
        for (Size j=0; j<cashFlowTimes.size(); ++j)
            discounters_.push_back(MarketModelDiscounter(cashFlowTimes[j],
                                                         rateTimes));
    }
Member Function Documentation
void QuantLib::AccountingEngine::multiplePathValues (SequenceStatisticsInc & stats, Size numberOfPaths)
Definition at line 115 of file accountingengine.cpp.
References QuantLib::GenericSequenceStatistics< StatisticsType >::add(), QuantLib::MarketModelMultiProduct::numberOfProducts(), product_, and singlePathValues().
Referenced by anonymous_namespace{swapforwardmappings.cpp}::simulate(), anonymous_namespace{marketmodel_smm.cpp}::simulate(), anonymous_namespace{marketmodel_cms.cpp}::simulate(), anonymous_namespace{marketmodel_smmcapletcalibration.cpp}::simulate(), anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::simulate(), anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::simulate(), anonymous_namespace{marketmodel.cpp}::simulate(), and QuantLib::UpperBoundEngine::singlePathValue().
    {
        std::vector<Real> values(product_->numberOfProducts());
        for (Size i=0; i<numberOfPaths; ++i) {
            Real weight = singlePathValues(values);
            stats.add(values,weight);
        }
    }
Real QuantLib::AccountingEngine::singlePathValues (std::vector< Real > & values) [private]
Definition at line 53 of file accountingengine.cpp.
References cashFlowsGenerated_, discounters_, evolver_, initialNumeraireValue_, QuantLib::MarketModelMultiProduct::nextTimeStep(), numberCashFlowsThisStep_, numberProducts_, QuantLib::MarketModelDiscounter::numeraireBonds(), numerairesHeld_, product_, and QuantLib::MarketModelMultiProduct::reset().
Referenced by multiplePathValues().
{
        std::fill(numerairesHeld_.begin(), numerairesHeld_.end(), 0.0);
        Real weight = evolver_->startNewPath();
        product_->reset();
        Real principalInNumerairePortfolio = 1.0;
        bool done = false;
        do {
            Size thisStep = evolver_->currentStep();
            weight *= evolver_->advanceStep();
            done = product_->nextTimeStep(evolver_->currentState(),
                                          numberCashFlowsThisStep_,
                                          cashFlowsGenerated_);
            Size numeraire =
                evolver_->numeraires()[thisStep];
            // for each product...
            for (Size i=0; i<numberProducts_; ++i) {
                // ...and each cash flow...
                const std::vector<MarketModelMultiProduct::CashFlow>& cashflows =
                    cashFlowsGenerated_[i];
                for (Size j=0; j<numberCashFlowsThisStep_[i]; ++j) {
                    // ...convert the cash flow to numeraires.
                    // This is done by calculating the number of
                    // numeraire bonds corresponding to such cash flow...
                    const MarketModelDiscounter& discounter =
                        discounters_[cashflows[j].timeIndex];
                    Real bonds = cashflows[j].amount *
                        discounter.numeraireBonds(evolver_->currentState(),
                                                  numeraire);
                    // ...and adding the newly bought bonds to the number
                    // of numeraires held.
                    numerairesHeld_[i] += bonds/principalInNumerairePortfolio;
                }
            }
            if (!done) {
                // The numeraire might change between steps. This implies
                // that we might have to convert the numeraire bonds for
                // this step into a corresponding amount of numeraire
                // bonds for the next step. This can be done by changing
                // the principal of the numeraire and updating the number
                // of bonds in the numeraire portfolio accordingly.
                Size nextNumeraire = evolver_->numeraires()[thisStep+1];
                principalInNumerairePortfolio *=
                    evolver_->currentState().discountRatio(numeraire,
                                                           nextNumeraire);
            }
        } while (!done);
        for (Size i=0; i<numerairesHeld_.size(); ++i)
            values[i] = numerairesHeld_[i] * initialNumeraireValue_;
        return weight;
    }
Member Data Documentation
std::vector<std::vector<MarketModelMultiProduct::CashFlow> > QuantLib::AccountingEngine::cashFlowsGenerated_ [private]
Definition at line 64 of file accountingengine.hpp.
Referenced by AccountingEngine(), and singlePathValues().
std::vector<MarketModelDiscounter> QuantLib::AccountingEngine::discounters_ [private]
Definition at line 65 of file accountingengine.hpp.
Referenced by AccountingEngine(), and singlePathValues().
boost::shared_ptr<MarketModelEvolver> QuantLib::AccountingEngine::evolver_ [private]
Definition at line 54 of file accountingengine.hpp.
Referenced by singlePathValues().
Real QuantLib::AccountingEngine::initialNumeraireValue_ [private]
Definition at line 57 of file accountingengine.hpp.
Referenced by singlePathValues().
std::vector<Size> QuantLib::AccountingEngine::numberCashFlowsThisStep_ [private]
Definition at line 62 of file accountingengine.hpp.
Referenced by singlePathValues().
Size QuantLib::AccountingEngine::numberProducts_ [private]
Definition at line 58 of file accountingengine.hpp.
Referenced by AccountingEngine(), and singlePathValues().
std::vector<Real> QuantLib::AccountingEngine::numerairesHeld_ [private]
Definition at line 61 of file accountingengine.hpp.
Referenced by singlePathValues().
Clone<MarketModelMultiProduct> QuantLib::AccountingEngine::product_ [private]
Definition at line 55 of file accountingengine.hpp.
Referenced by AccountingEngine(), multiplePathValues(), and singlePathValues().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/accountingengine.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/accountingengine.cpp