QuantLib: QuantLib::GenericGaussianStatistics< Stat > Class Template Reference
QuantLib::GenericGaussianStatistics< Stat > Class Template Reference
Statistics tool for gaussian-assumption risk measures.
#include <gaussianstatistics.hpp>
Public Types
typedef Stat::value_type value_type
Public Member Functions
GenericGaussianStatistics ()
GenericGaussianStatistics (const Stat &s)
Gaussian risk measures
Real gaussianDownsideVariance () const
Real gaussianDownsideDeviation () const
Real gaussianRegret (Real target) const
Real gaussianPercentile (Real percentile) const
Real gaussianTopPercentile (Real percentile) const
Real gaussianPotentialUpside (Real percentile) const
gaussian-assumption Potential-Upside at a given percentile
Real gaussianValueAtRisk (Real percentile) const
gaussian-assumption Value-At-Risk at a given percentile
Real gaussianExpectedShortfall (Real percentile) const
gaussian-assumption Expected Shortfall at a given percentile
Real gaussianShortfall (Real target) const
gaussian-assumption Shortfall (observations below target)
Real gaussianAverageShortfall (Real target) const
gaussian-assumption Average Shortfall (averaged shortfallness)
Detailed Description
template<class Stat>
class QuantLib::GenericGaussianStatistics< Stat >
Statistics tool for gaussian-assumption risk measures.
This class wraps a somewhat generic statistic tool and adds a number of gaussian risk measures (e.g.: value-at-risk, expected shortfall, etc.) based on the mean and variance provided by the underlying statistic tool.
Definition at line 40 of file gaussianstatistics.hpp.
Member Typedef Documentation
template<class Stat > typedef Stat::value_type QuantLib::GenericGaussianStatistics< Stat >::value_type
Definition at line 42 of file gaussianstatistics.hpp.
Constructor & Destructor Documentation
template<class Stat > QuantLib::GenericGaussianStatistics< Stat >::GenericGaussianStatistics () [inline]
Definition at line 43 of file gaussianstatistics.hpp.
{}
template<class Stat > QuantLib::GenericGaussianStatistics< Stat >::GenericGaussianStatistics (const Stat & s) [inline]
Definition at line 44 of file gaussianstatistics.hpp.
: Stat(s) {}
Member Function Documentation
template<class Stat > Real QuantLib::GenericGaussianStatistics< Stat >::gaussianAverageShortfall (Real target) const [inline]
gaussian-assumption Average Shortfall (averaged shortfallness)
Definition at line 229 of file gaussianstatistics.hpp.
Referenced by RiskStatisticsTest::testResults().
{
        Real m = this->mean();
        Real std = this->standardDeviation();
        CumulativeNormalDistribution gIntegral(m, std);
        NormalDistribution g(m, std);
        return ( (target-m) + std*std*g(target)/gIntegral(target) );
    }
template<class Stat > Real QuantLib::GenericGaussianStatistics< Stat >::gaussianDownsideDeviation () const [inline]
returns the downside deviation, defined as the square root of the downside variance.
Definition at line 60 of file gaussianstatistics.hpp.
References QuantLib::GenericGaussianStatistics< Stat >::gaussianDownsideVariance().
{
            return std::sqrt(gaussianDownsideVariance());
        }
template<class Stat > Real QuantLib::GenericGaussianStatistics< Stat >::gaussianDownsideVariance () const [inline]
returns the downside variance, defined as
\[ \frac{N}{N-1} \times \frac{ \sum_{i=1}^{N} \theta \times x_i^{2}}{ \sum_{i=1}^{N} w_i} \]
, where \(\theta \) = 0 if x > 0 and \(\theta \) =1 if x <0
Definition at line 53 of file gaussianstatistics.hpp.
References QuantLib::GenericGaussianStatistics< Stat >::gaussianRegret().
Referenced by QuantLib::GenericGaussianStatistics< Stat >::gaussianDownsideDeviation(), and RiskStatisticsTest::testResults().
{
            return gaussianRegret(0.0);
        }
template<class Stat > Real QuantLib::GenericGaussianStatistics< Stat >::gaussianExpectedShortfall (Real percentile) const [inline]
gaussian-assumption Expected Shortfall at a given percentile
Assuming a gaussian distribution it returns the expected loss in case that the loss exceeded a VaR threshold,
\[ \mathrm{E}\left[ x \;|\; x < \mathrm{VaR}(p) \right], \]
that is the average of observations below the given percentile \(p \). Also know as conditional value-at-risk.
See Artzner, Delbaen, Eber and Heath, "Coherent measures of risk", Mathematical Finance 9 (1999)
Precondition:
percentile must be in range [90%-100%)
Definition at line 201 of file gaussianstatistics.hpp.
References QL_REQUIRE.
Referenced by RiskStatisticsTest::testResults().
{
        QL_REQUIRE(percentile<1.0 && percentile>=0.9,
                   "percentile (" << percentile << ") out of range [0.9, 1)");
        Real m = this->mean();
        Real std = this->standardDeviation();
        InverseCumulativeNormal gInverse(m, std);
        Real var = gInverse(1.0-percentile);
        NormalDistribution g(m, std);
        Real result = m - std*std*g(var)/(1.0-percentile);
        // expectedShortfall must be a loss
        // this means that it has to be MIN(result, 0.0)
        // expectedShortfall must also be a positive quantity, so -MIN(*)
        return -std::min<Real>(result, 0.0);
    }
template<class Stat > Real QuantLib::GenericGaussianStatistics< Stat >::gaussianPercentile (Real percentile) const [inline]
gaussian-assumption y-th percentile, defined as the value x such that
\[ y = \frac{1}{\sqrt{2 \pi}} \int_{-\infty}^{x} \exp (-u^2/2) du \]
Precondition:
percentile must be in range (0%-100%) extremes excluded
Definition at line 148 of file gaussianstatistics.hpp.
References QL_REQUIRE.
Referenced by RiskStatisticsTest::testResults().
{
        QL_REQUIRE(percentile>0.0,
                   "percentile (" << percentile << ") must be > 0.0");
        QL_REQUIRE(percentile<1.0,
                   "percentile (" << percentile << ") must be < 1.0");
        InverseCumulativeNormal gInverse(Stat::mean(),
                                         Stat::standardDeviation());
        return gInverse(percentile);
    }
template<class Stat > Real QuantLib::GenericGaussianStatistics< Stat >::gaussianPotentialUpside (Real percentile) const [inline]
gaussian-assumption Potential-Upside at a given percentile
Precondition:
percentile must be in range [90%-100%)
Definition at line 171 of file gaussianstatistics.hpp.
References QL_REQUIRE.
Referenced by RiskStatisticsTest::testResults().
{
        QL_REQUIRE(percentile<1.0 && percentile>=0.9,
                   "percentile (" << percentile << ") out of range [0.9, 1)");
        Real result = gaussianPercentile(percentile);
        // potential upside must be a gain, i.e., floored at 0.0
        return std::max<Real>(result, 0.0);
    }
template<class Stat > Real QuantLib::GenericGaussianStatistics< Stat >::gaussianRegret (Real target) const [inline]
returns the variance of observations below target
\[ \frac{\sum w_i (min(0, x_i-target))^2 }{\sum w_i}. \]
See Dembo, Freeman "The Rules Of Risk", Wiley (2001)
Definition at line 132 of file gaussianstatistics.hpp.
References anonymous_namespace{marketmodel.cpp}::beta.
Referenced by QuantLib::GenericGaussianStatistics< Stat >::gaussianDownsideVariance(), and RiskStatisticsTest::testResults().
{
        Real m = this->mean();
        Real std = this->standardDeviation();
        Real variance = std*std;
        CumulativeNormalDistribution gIntegral(m, std);
        NormalDistribution g(m, std);
        Real firstTerm = variance + m*m - 2.0*target*m + target*target;
        Real alfa = gIntegral(target);
        Real secondTerm = m - target;
        Real beta = variance*g(target);
        Real result = alfa*firstTerm - beta*secondTerm;
        return result/alfa;
    }
template<class Stat > Real QuantLib::GenericGaussianStatistics< Stat >::gaussianShortfall (Real target) const [inline]
gaussian-assumption Shortfall (observations below target)
Definition at line 220 of file gaussianstatistics.hpp.
Referenced by RiskStatisticsTest::testResults().
{
        CumulativeNormalDistribution gIntegral(this->mean(),
                                               this->standardDeviation());
        return gIntegral(target);
    }
template<class Stat > Real QuantLib::GenericGaussianStatistics< Stat >::gaussianTopPercentile (Real percentile) const [inline]
Precondition:
percentile must be in range (0%-100%) extremes excluded
Definition at line 163 of file gaussianstatistics.hpp.
{
        return gaussianPercentile(1.0-percentile);
    }
template<class Stat > Real QuantLib::GenericGaussianStatistics< Stat >::gaussianValueAtRisk (Real percentile) const [inline]
gaussian-assumption Value-At-Risk at a given percentile
Precondition:
percentile must be in range [90%-100%)
Definition at line 185 of file gaussianstatistics.hpp.
References QL_REQUIRE.
Referenced by RiskStatisticsTest::testResults().
{
        QL_REQUIRE(percentile<1.0 && percentile>=0.9,
                   "percentile (" << percentile << ") out of range [0.9, 1)");
        Real result = gaussianPercentile(1.0-percentile);
        // VAR must be a loss
        // this means that it has to be MIN(dist(1.0-percentile), 0.0)
        // VAR must also be a positive quantity, so -MIN(*)
        return -std::min<Real>(result, 0.0);
    }
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/statistics/gaussianstatistics.hpp