QuantLib: QuantLib::GJRGARCHModel Class Reference
QuantLib::GJRGARCHModel Class Reference
GJR-GARCH model for the stochastic volatility of an asset.
#include <gjrgarchmodel.hpp>
Classes
class VolatilityConstraint
Public Member Functions
GJRGARCHModel (const boost::shared_ptr< GJRGARCHProcess > &process)
Real omega () const
Real alpha () const
Real beta () const
Real gamma () const
Real lambda () const
Real v0 () const
boost::shared_ptr
< GJRGARCHProcess > process () const
Protected Member Functions
void generateArguments ()
Protected Attributes
boost::shared_ptr
< GJRGARCHProcess > process_
Detailed Description
GJR-GARCH model for the stochastic volatility of an asset.
References:
Glosten, L., Jagannathan, R., Runkle, D., 1993. Relationship between the expected value and the volatility of the nominal excess return on stocks. Journal of Finance 48, 1779-1801
Test:
calibration is not implemented for GJR-GARCH
Definition at line 42 of file gjrgarchmodel.hpp.
Constructor & Destructor Documentation
QuantLib::GJRGARCHModel::GJRGARCHModel (const boost::shared_ptr< GJRGARCHProcess > & process)
Definition at line 42 of file gjrgarchmodel.cpp.
References QuantLib::CalibratedModel::arguments_, QuantLib::CalibratedModel::constraint_, generateArguments(), process_, and QuantLib::Observer::registerWith().
    : CalibratedModel(6), process_(process) {
        arguments_[0] = ConstantParameter(process->omega(),
                                          PositiveConstraint());
        arguments_[1] = ConstantParameter(process->alpha(),
                                          BoundaryConstraint( 0.0, 1.0));
        arguments_[2] = ConstantParameter(process->beta(),
                                          BoundaryConstraint( 0.0, 1.0));
        arguments_[3] = ConstantParameter(process->gamma(),
                                          BoundaryConstraint(-1.0, 1.0));
        arguments_[4] = ConstantParameter(process->lambda(), NoConstraint());
        arguments_[5] = ConstantParameter(process->v0(),
                                          PositiveConstraint());
        constraint_ = boost::shared_ptr<Constraint>(
            new CompositeConstraint(*constraint_, VolatilityConstraint()));
        generateArguments();
        registerWith(process_->riskFreeRate());
        registerWith(process_->dividendYield());
        registerWith(process_->s0());
    }
Member Function Documentation
Real QuantLib::GJRGARCHModel::alpha () const [inline]
Definition at line 50 of file gjrgarchmodel.hpp.
References QuantLib::CalibratedModel::arguments_.
Referenced by generateArguments().
{ return arguments_[1](0.0); }
Real QuantLib::GJRGARCHModel::beta () const [inline]
Definition at line 52 of file gjrgarchmodel.hpp.
References QuantLib::CalibratedModel::arguments_.
Referenced by generateArguments(), and QuantLib::GJRGARCHModel::VolatilityConstraint::Impl::test().
{ return arguments_[2](0.0); }
Real QuantLib::GJRGARCHModel::gamma () const [inline]
Definition at line 54 of file gjrgarchmodel.hpp.
References QuantLib::CalibratedModel::arguments_.
Referenced by generateArguments(), and QuantLib::GJRGARCHModel::VolatilityConstraint::Impl::test().
{ return arguments_[3](0.0); }
void QuantLib::GJRGARCHModel::generateArguments () [protected, virtual]
Reimplemented from QuantLib::CalibratedModel.
Definition at line 67 of file gjrgarchmodel.cpp.
References alpha(), beta(), gamma(), lambda(), omega(), process_, and v0().
Referenced by GJRGARCHModel().
{
        process_.reset(new GJRGARCHProcess(process_->riskFreeRate(),
                                           process_->dividendYield(),
                                           process_->s0(),
                                           v0(), omega(),
                                           alpha(), beta(),
                                           gamma(), lambda(),
                                           process_->daysPerYear()));
    }
Real QuantLib::GJRGARCHModel::lambda () const [inline]
Definition at line 56 of file gjrgarchmodel.hpp.
References QuantLib::CalibratedModel::arguments_.
Referenced by generateArguments().
{ return arguments_[4](0.0); }
Real QuantLib::GJRGARCHModel::omega () const [inline]
Definition at line 48 of file gjrgarchmodel.hpp.
References QuantLib::CalibratedModel::arguments_.
Referenced by generateArguments().
{ return arguments_[0](0.0); }
boost::shared_ptr<GJRGARCHProcess> QuantLib::GJRGARCHModel::process () const [inline]
Definition at line 61 of file gjrgarchmodel.hpp.
References process_.
{ return process_; }
Real QuantLib::GJRGARCHModel::v0 () const [inline]
Definition at line 58 of file gjrgarchmodel.hpp.
References QuantLib::CalibratedModel::arguments_.
Referenced by generateArguments().
{ return arguments_[5](0.0); }
Member Data Documentation
boost::shared_ptr<GJRGARCHProcess> QuantLib::GJRGARCHModel::process_ [protected]
Definition at line 66 of file gjrgarchmodel.hpp.
Referenced by generateArguments(), GJRGARCHModel(), and process().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/equity/gjrgarchmodel.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/equity/gjrgarchmodel.cpp