QuantLib: QuantLib::DepositRateHelper Class Reference
QuantLib::DepositRateHelper Class Reference
Rate helper for bootstrapping over deposit rates.
#include <ratehelpers.hpp>
Public Member Functions
DepositRateHelper (const Handle< Quote > &rate, const Period &tenor, Natural fixingDays, const Calendar &calendar, BusinessDayConvention convention, bool endOfMonth, const DayCounter &dayCounter)
DepositRateHelper (Rate rate, const Period &tenor, Natural fixingDays, const Calendar &calendar, BusinessDayConvention convention, bool endOfMonth, const DayCounter &dayCounter)
DepositRateHelper (const Handle< Quote > &rate, const boost::shared_ptr< IborIndex > &iborIndex)
DepositRateHelper (Rate rate, const boost::shared_ptr< IborIndex > &iborIndex)
RateHelper interface
Real impliedQuote () const
void setTermStructure (YieldTermStructure *)
Visitability
void accept (AcyclicVisitor &)
Private Member Functions
void initializeDates ()
Private Attributes
Date fixingDate_
boost::shared_ptr< IborIndex > iborIndex_
RelinkableHandle
< YieldTermStructure > termStructureHandle_
Detailed Description
Rate helper for bootstrapping over deposit rates.
Definition at line 101 of file ratehelpers.hpp.
Constructor & Destructor Documentation
QuantLib::DepositRateHelper::DepositRateHelper (const Handle< Quote > & rate, const Period & tenor, Natural fixingDays, const Calendar & calendar, BusinessDayConvention convention, bool endOfMonth, const DayCounter & dayCounter)
Definition at line 189 of file ratehelpers.cpp.
References iborIndex_, initializeDates(), and termStructureHandle_.
    : RelativeDateRateHelper(rate) {
        iborIndex_ = shared_ptr<IborIndex>(new
            IborIndex("no-fix", // never take fixing into account
                      tenor, fixingDays,
                      Currency(), calendar, convention,
                      endOfMonth, dayCounter, termStructureHandle_));
        initializeDates();
    }
QuantLib::DepositRateHelper::DepositRateHelper (Rate rate, const Period & tenor, Natural fixingDays, const Calendar & calendar, BusinessDayConvention convention, bool endOfMonth, const DayCounter & dayCounter)
Definition at line 205 of file ratehelpers.cpp.
References iborIndex_, initializeDates(), and termStructureHandle_.
    : RelativeDateRateHelper(rate) {
        iborIndex_ = shared_ptr<IborIndex>(new
            IborIndex("no-fix", // never take fixing into account
                      tenor, fixingDays,
                      Currency(), calendar, convention,
                      endOfMonth, dayCounter, termStructureHandle_));
        initializeDates();
    }
QuantLib::DepositRateHelper::DepositRateHelper (const Handle< Quote > & rate, const boost::shared_ptr< IborIndex > & iborIndex)
QuantLib::DepositRateHelper::DepositRateHelper (Rate rate, const boost::shared_ptr< IborIndex > & iborIndex)
Member Function Documentation
void QuantLib::DepositRateHelper::accept (AcyclicVisitor & v) [virtual]
Reimplemented from QuantLib::BootstrapHelper< TS >.
Definition at line 265 of file ratehelpers.cpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Visitor< T >::visit().
{
        Visitor<DepositRateHelper>* v1 =
            dynamic_cast<Visitor<DepositRateHelper>*>(&v);
        if (v1 != 0)
            v1->visit(*this);
        else
            RateHelper::accept(v);
    }
Real QuantLib::DepositRateHelper::impliedQuote () const [virtual]
Implements QuantLib::BootstrapHelper< TS >.
Definition at line 245 of file ratehelpers.cpp.
References fixingDate_, iborIndex_, QL_REQUIRE, and QuantLib::BootstrapHelper< TS >::termStructure_.
{
        QL_REQUIRE(termStructure_ != 0, "term structure not set");
        return iborIndex_->fixing(fixingDate_, true);
    }
void QuantLib::DepositRateHelper::initializeDates () [private, virtual]
Implements QuantLib::RelativeDateBootstrapHelper< TS >.
Definition at line 258 of file ratehelpers.cpp.
References QuantLib::Days, QuantLib::BootstrapHelper< TS >::earliestDate_, QuantLib::RelativeDateBootstrapHelper< TS >::evaluationDate_, fixingDate_, iborIndex_, and QuantLib::BootstrapHelper< TS >::latestDate_.
Referenced by DepositRateHelper().
{
        earliestDate_ = iborIndex_->fixingCalendar().advance(
            evaluationDate_, iborIndex_->fixingDays()*Days);
        latestDate_ = iborIndex_->maturityDate(earliestDate_);
        fixingDate_ = iborIndex_->fixingDate(earliestDate_);
    }
void QuantLib::DepositRateHelper::setTermStructure (YieldTermStructure * t)
Definition at line 250 of file ratehelpers.cpp.
References QuantLib::RelinkableHandle< T >::linkTo(), QuantLib::anonymous_namespace{riskyassetswap.cpp}::no_deletion(), and termStructureHandle_.
{
        // no need to register---the index is not lazy
        termStructureHandle_.linkTo(
                         shared_ptr<YieldTermStructure>(t,no_deletion),
                         false);
        RelativeDateRateHelper::setTermStructure(t);
    }
Member Data Documentation
Date QuantLib::DepositRateHelper::fixingDate_ [private]
Definition at line 132 of file ratehelpers.hpp.
Referenced by impliedQuote(), and initializeDates().
boost::shared_ptr<IborIndex> QuantLib::DepositRateHelper::iborIndex_ [private]
Definition at line 133 of file ratehelpers.hpp.
Referenced by DepositRateHelper(), impliedQuote(), and initializeDates().
RelinkableHandle<YieldTermStructure> QuantLib::DepositRateHelper::termStructureHandle_ [private]
Definition at line 134 of file ratehelpers.hpp.
Referenced by DepositRateHelper(), and setTermStructure().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/yield/ratehelpers.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/yield/ratehelpers.cpp