QuantLib: QuantLib::MarketModelNodeDataProvider Class Reference
QuantLib::MarketModelNodeDataProvider Class Reference
#include <nodedataprovider.hpp>
Public Member Functions
virtual ~MarketModelNodeDataProvider ()
virtual Size numberOfExercises () const =0
virtual std::vector< Size > numberOfData () const =0
virtual const
EvolutionDescription & evolution () const =0
virtual void nextStep (const CurveState &)=0
virtual void reset ()=0
virtual std::valarray< bool > isExerciseTime () const =0
virtual void values (const CurveState &, std::vector< Real > &results) const =0
Detailed Description
Definition at line 33 of file nodedataprovider.hpp.
Constructor & Destructor Documentation
virtual QuantLib::MarketModelNodeDataProvider::~MarketModelNodeDataProvider () [inline, virtual]
Definition at line 35 of file nodedataprovider.hpp.
{}
Member Function Documentation
virtual const EvolutionDescription& QuantLib::MarketModelNodeDataProvider::evolution () const [pure virtual]
Implemented in QuantLib::SwapForwardBasisSystem, QuantLib::TriggeredSwapExercise, and QuantLib::SwapBasisSystem.
Referenced by QuantLib::collectNodeData(), QuantLib::LongstaffSchwartzExerciseStrategy::LongstaffSchwartzExerciseStrategy(), QuantLib::ParametricExerciseAdapter::ParametricExerciseAdapter(), and QuantLib::ParametricExerciseAdapter::relevantTimes().
virtual std::valarray<bool> QuantLib::MarketModelNodeDataProvider::isExerciseTime () const [pure virtual]
Implemented in QuantLib::SwapForwardBasisSystem, QuantLib::TriggeredSwapExercise, and QuantLib::SwapBasisSystem.
virtual void QuantLib::MarketModelNodeDataProvider::nextStep (const CurveState &) [pure virtual]
Implemented in QuantLib::SwapForwardBasisSystem, QuantLib::TriggeredSwapExercise, and QuantLib::SwapBasisSystem.
Referenced by QuantLib::collectNodeData(), QuantLib::ParametricExerciseAdapter::nextStep(), and QuantLib::LongstaffSchwartzExerciseStrategy::nextStep().
virtual std::vector<Size> QuantLib::MarketModelNodeDataProvider::numberOfData () const [pure virtual]
Implemented in QuantLib::MarketModelBasisSystem, and QuantLib::MarketModelParametricExercise.
virtual Size QuantLib::MarketModelNodeDataProvider::numberOfExercises () const [pure virtual]
Implemented in QuantLib::SwapForwardBasisSystem, QuantLib::TriggeredSwapExercise, and QuantLib::SwapBasisSystem.
Referenced by QuantLib::LongstaffSchwartzExerciseStrategy::LongstaffSchwartzExerciseStrategy().
virtual void QuantLib::MarketModelNodeDataProvider::reset () [pure virtual]
Implemented in QuantLib::SwapForwardBasisSystem, QuantLib::TriggeredSwapExercise, and QuantLib::SwapBasisSystem.
Referenced by QuantLib::collectNodeData(), QuantLib::ParametricExerciseAdapter::reset(), and QuantLib::LongstaffSchwartzExerciseStrategy::reset().
virtual void QuantLib::MarketModelNodeDataProvider::values (const CurveState & , std::vector< Real > & results) const [pure virtual]
Implemented in QuantLib::SwapForwardBasisSystem, QuantLib::TriggeredSwapExercise, and QuantLib::SwapBasisSystem.
Referenced by QuantLib::collectNodeData(), QuantLib::ParametricExerciseAdapter::exercise(), and QuantLib::LongstaffSchwartzExerciseStrategy::exercise().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/callability/nodedataprovider.hpp