QuantLib: QuantLib::anonymous_namespace{upperboundengine.cpp}::DecoratedHedge Class Reference
QuantLib::anonymous_namespace{upperboundengine.cpp}::DecoratedHedge Class Reference
Public Member Functions
DecoratedHedge (const CallSpecifiedMultiProduct &product)
void reset ()
during simulation put product at start of path
bool nextTimeStep (const CurveState &currentState, std::vector< Size > &numberCashFlowsThisStep, std::vector< std::vector< CashFlow > > &cashFlowsGenerated)
return value indicates whether path is finished, TRUE means done
std::auto_ptr
< MarketModelMultiProduct > clone () const
returns a newly-allocated copy of itself
void save ()
void clear ()
void startRecording ()
void stopRecording ()
Private Attributes
std::vector< Clone< CurveState > > savedStates_
Size lastSavedStep_
bool recording_
std::vector< Size > numberCashFlowsThisStep_
std::vector< std::vector
< CashFlow > > cashFlowsGenerated_
Detailed Description
Definition at line 37 of file upperboundengine.cpp.
Constructor & Destructor Documentation
QuantLib::anonymous_namespace{upperboundengine.cpp}::DecoratedHedge::DecoratedHedge (const CallSpecifiedMultiProduct & product) [inline]
Definition at line 39 of file upperboundengine.cpp.
References QuantLib::CallSpecifiedMultiProduct::evolution(), QuantLib::CallSpecifiedMultiProduct::maxNumberOfCashFlowsPerProductPerStep(), anonymous_namespace{matrices.cpp}::N, QuantLib::CallSpecifiedMultiProduct::numberOfProducts(), and QuantLib::EvolutionDescription::numberOfSteps().
            : CallSpecifiedMultiProduct(product) {
                savedStates_.reserve(product.evolution().numberOfSteps());
                Size N = product.numberOfProducts();
                numberCashFlowsThisStep_.resize(N);
                cashFlowsGenerated_.resize(N);
                for (Size i=0; i<N; ++i)
                    cashFlowsGenerated_[i].resize(
                            product.maxNumberOfCashFlowsPerProductPerStep());
                clear();
            }
Member Function Documentation
void QuantLib::anonymous_namespace{upperboundengine.cpp}::DecoratedHedge::clear () [inline]
Definition at line 85 of file upperboundengine.cpp.
{
                lastSavedStep_ = 0;
                savedStates_.clear();
                recording_ = true;
            }
std::auto_ptr<MarketModelMultiProduct> QuantLib::anonymous_namespace{upperboundengine.cpp}::DecoratedHedge::clone () const [inline, virtual]
returns a newly-allocated copy of itself
Reimplemented from QuantLib::CallSpecifiedMultiProduct.
Definition at line 76 of file upperboundengine.cpp.
{
                return std::auto_ptr<MarketModelMultiProduct>(
                                                   new DecoratedHedge(*this));
            }
bool QuantLib::anonymous_namespace{upperboundengine.cpp}::DecoratedHedge::nextTimeStep (const CurveState & currentState, std::vector< Size > & numberCashFlowsThisStep, std::vector< std::vector< CashFlow > > & cashFlowsGenerated) [inline, virtual]
return value indicates whether path is finished, TRUE means done
Reimplemented from QuantLib::CallSpecifiedMultiProduct.
Definition at line 64 of file upperboundengine.cpp.
References QuantLib::CallSpecifiedMultiProduct::nextTimeStep().
{
                if (recording_)
                    savedStates_.push_back(currentState);
                return CallSpecifiedMultiProduct::nextTimeStep(
                                                     currentState,
                                                     numberCashFlowsThisStep,
                                                     cashFlowsGenerated);
            }
void QuantLib::anonymous_namespace{upperboundengine.cpp}::DecoratedHedge::reset () [inline, virtual]
during simulation put product at start of path
Reimplemented from QuantLib::CallSpecifiedMultiProduct.
Definition at line 53 of file upperboundengine.cpp.
References QuantLib::CallSpecifiedMultiProduct::nextTimeStep(), and anonymous_namespace{inflationvolatility.cpp}::reset().
{
                CallSpecifiedMultiProduct::reset();
                disableCallability();
                for (Size i=0; i<lastSavedStep_; ++i)
                    CallSpecifiedMultiProduct::nextTimeStep(
                                                     *savedStates_[i],
                                                     numberCashFlowsThisStep_,
                                                     cashFlowsGenerated_);
                enableCallability();
            }
void QuantLib::anonymous_namespace{upperboundengine.cpp}::DecoratedHedge::save () [inline]
Definition at line 81 of file upperboundengine.cpp.
{
                lastSavedStep_ = savedStates_.size();
            }
void QuantLib::anonymous_namespace{upperboundengine.cpp}::DecoratedHedge::startRecording () [inline]
Definition at line 91 of file upperboundengine.cpp.
{
                recording_ = true;
            }
void QuantLib::anonymous_namespace{upperboundengine.cpp}::DecoratedHedge::stopRecording () [inline]
Definition at line 95 of file upperboundengine.cpp.
{
                recording_ = false;
            }
Member Data Documentation
std::vector<std::vector<CashFlow> > QuantLib::anonymous_namespace{upperboundengine.cpp}::DecoratedHedge::cashFlowsGenerated_ [private]
Definition at line 103 of file upperboundengine.cpp.
Size QuantLib::anonymous_namespace{upperboundengine.cpp}::DecoratedHedge::lastSavedStep_ [private]
Definition at line 100 of file upperboundengine.cpp.
std::vector<Size> QuantLib::anonymous_namespace{upperboundengine.cpp}::DecoratedHedge::numberCashFlowsThisStep_ [private]
Definition at line 102 of file upperboundengine.cpp.
bool QuantLib::anonymous_namespace{upperboundengine.cpp}::DecoratedHedge::recording_ [private]
Definition at line 101 of file upperboundengine.cpp.
std::vector<Clone<CurveState> > QuantLib::anonymous_namespace{upperboundengine.cpp}::DecoratedHedge::savedStates_ [private]
Definition at line 99 of file upperboundengine.cpp.
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/callability/upperboundengine.cpp