QuantLib: QuantLib::BlackConstantVol Class Reference
QuantLib::BlackConstantVol Class Reference
Constant Black volatility, no time-strike dependence.
#include <blackconstantvol.hpp>
Public Member Functions
BlackConstantVol (const Date &referenceDate, const Calendar &, Volatility volatility, const DayCounter &dayCounter)
BlackConstantVol (const Date &referenceDate, const Calendar &, const Handle< Quote > &volatility, const DayCounter &dayCounter)
BlackConstantVol (Natural settlementDays, const Calendar &, Volatility volatility, const DayCounter &dayCounter)
BlackConstantVol (Natural settlementDays, const Calendar &, const Handle< Quote > &volatility, const DayCounter &dayCounter)
TermStructure interface
Date maxDate () const
the latest date for which the curve can return values
VolatilityTermStructure interface
Real minStrike () const
the minimum strike for which the term structure can return vols
Real maxStrike () const
the maximum strike for which the term structure can return vols
Visitability
virtual void accept (AcyclicVisitor &)
Protected Member Functions
virtual Volatility blackVolImpl (Time t, Real) const
Black volatility calculation.
Private Attributes
Handle< Quote > volatility_
Detailed Description
Constant Black volatility, no time-strike dependence.
This class implements the BlackVolatilityTermStructure interface for a constant Black volatility (no time/strike dependence).
Definition at line 39 of file blackconstantvol.hpp.
Constructor & Destructor Documentation
QuantLib::BlackConstantVol::BlackConstantVol (const Date & referenceDate, const Calendar & cal, Volatility volatility, const DayCounter & dayCounter) [inline]
Definition at line 79 of file blackconstantvol.hpp.
    : BlackVolatilityTermStructure(referenceDate, cal, Following, dc),
      volatility_(boost::shared_ptr<Quote>(new SimpleQuote(volatility))) {}
QuantLib::BlackConstantVol::BlackConstantVol (const Date & referenceDate, const Calendar & cal, const Handle< Quote > & volatility, const DayCounter & dayCounter) [inline]
Definition at line 86 of file blackconstantvol.hpp.
References QuantLib::Observer::registerWith(), and volatility_.
    : BlackVolatilityTermStructure(referenceDate, cal, Following, dc),
      volatility_(volatility) {
        registerWith(volatility_);
    }
QuantLib::BlackConstantVol::BlackConstantVol (Natural settlementDays, const Calendar & cal, Volatility volatility, const DayCounter & dayCounter) [inline]
Definition at line 95 of file blackconstantvol.hpp.
    : BlackVolatilityTermStructure(settlementDays, cal, Following, dc),
      volatility_(boost::shared_ptr<Quote>(new SimpleQuote(volatility))) {}
QuantLib::BlackConstantVol::BlackConstantVol (Natural settlementDays, const Calendar & cal, const Handle< Quote > & volatility, const DayCounter & dayCounter) [inline]
Definition at line 102 of file blackconstantvol.hpp.
References QuantLib::Observer::registerWith(), and volatility_.
    : BlackVolatilityTermStructure(settlementDays, cal, Following, dc),
      volatility_(volatility) {
        registerWith(volatility_);
    }
Member Function Documentation
void QuantLib::BlackConstantVol::accept (AcyclicVisitor & v) [inline, virtual]
Reimplemented from QuantLib::BlackVolatilityTermStructure.
Definition at line 123 of file blackconstantvol.hpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Visitor< T >::visit().
{
        Visitor<BlackConstantVol>* v1 =
            dynamic_cast<Visitor<BlackConstantVol>*>(&v);
        if (v1 != 0)
            v1->visit(*this);
        else
            BlackVolatilityTermStructure::accept(v);
    }
Volatility QuantLib::BlackConstantVol::blackVolImpl (Time t, Real strike) const [inline, protected, virtual]
Black volatility calculation.
Implements QuantLib::BlackVolTermStructure.
Definition at line 132 of file blackconstantvol.hpp.
References volatility_.
{
        return volatility_->value();
    }
Date QuantLib::BlackConstantVol::maxDate () const [inline, virtual]
the latest date for which the curve can return values
Implements QuantLib::TermStructure.
Definition at line 111 of file blackconstantvol.hpp.
{
        return Date::maxDate();
    }
Real QuantLib::BlackConstantVol::maxStrike () const [inline, virtual]
the maximum strike for which the term structure can return vols
Implements QuantLib::VolatilityTermStructure.
Definition at line 119 of file blackconstantvol.hpp.
References QL_MAX_REAL.
{
        return QL_MAX_REAL;
    }
Real QuantLib::BlackConstantVol::minStrike () const [inline, virtual]
the minimum strike for which the term structure can return vols
Implements QuantLib::VolatilityTermStructure.
Definition at line 115 of file blackconstantvol.hpp.
References QL_MIN_REAL.
{
        return QL_MIN_REAL;
    }
Member Data Documentation
Handle<Quote> QuantLib::BlackConstantVol::volatility_ [private]
Definition at line 73 of file blackconstantvol.hpp.
Referenced by BlackConstantVol(), and blackVolImpl().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/equityfx/blackconstantvol.hpp