QuantLib: QuantLib::RelinkableHandle< T > Class Template Reference
QuantLib::RelinkableHandle< T > Class Template Reference
Relinkable handle to an observable.
#include <handle.hpp>
Public Member Functions
RelinkableHandle (const boost::shared_ptr< T > &p=boost::shared_ptr< T >(), bool registerAsObserver=true)
RelinkableHandle (T *p, bool registerAsObserver=true)
void linkTo (const boost::shared_ptr< T > &, bool registerAsObserver=true)
Detailed Description
template<class T>
class QuantLib::RelinkableHandle< T >
Relinkable handle to an observable.
An instance of this class can be relinked so that it points to another observable. The change will be propagated to all handles that were created as copies of such instance.
Precondition:
Class T must inherit from Observable
Warning:
see the Handle documentation for issues relatives to registerAsObserver.
Definition at line 114 of file handle.hpp.
Constructor & Destructor Documentation
template<class T> QuantLib::RelinkableHandle< T >::RelinkableHandle (const boost::shared_ptr< T > & p = boost::shared_ptr<T>(), bool registerAsObserver = true) [inline, explicit]
Definition at line 181 of file handle.hpp.
    : Handle<T>(p,registerAsObserver) {}
template<class T> QuantLib::RelinkableHandle< T >::RelinkableHandle (T * p, bool registerAsObserver = true) [inline, explicit]
Definition at line 186 of file handle.hpp.
    : Handle<T>(p,registerAsObserver) {}
Member Function Documentation
template<class T> void QuantLib::RelinkableHandle< T >::linkTo (const boost::shared_ptr< T > & h, bool registerAsObserver = true) [inline]
Definition at line 191 of file handle.hpp.
Referenced by QuantLib::CallableFixedRateBond::CallableFixedRateBond(), QuantLib::GaussianRecursiveCdoEngine< CDOEngine >::GaussianRecursiveCdoEngine(), QuantLib::CallableBond::impliedVolatility(), QuantLib::CallableBond::ImpliedVolHelper::ImpliedVolHelper(), QuantLib::GeneralizedBlackScholesProcess::localVolatility(), anonymous_namespace{libormarketmodelprocess.cpp}::makeIndex(), anonymous_namespace{libormarketmodel.cpp}::makeIndex(), anonymous_namespace{inflationvolatility.cpp}::reset(), QuantLib::OISRateHelper::setTermStructure(), QuantLib::BondHelper::setTermStructure(), QuantLib::DatedOISRateHelper::setTermStructure(), QuantLib::CdsHelper::setTermStructure(), QuantLib::AssetSwapHelper::setTermStructure(), QuantLib::DepositRateHelper::setTermStructure(), QuantLib::FraRateHelper::setTermStructure(), QuantLib::SwapRateHelper::setTermStructure(), QuantLib::BMASwapRateHelper::setTermStructure(), anonymous_namespace{inflationvolatility.cpp}::setup(), QuantLib::StudentRecursiveCdoEngine< CDOEngine >::StudentRecursiveCdoEngine(), MCLongstaffSchwartzEngineTest::testAmericanMaxOption(), DigitalCouponTest::testAssetOrNothing(), DigitalCouponTest::testAssetOrNothingDeepInTheMoney(), DigitalCouponTest::testAssetOrNothingDeepOutTheMoney(), anonymous_namespace{piecewiseyieldcurve.cpp}::testBMACurveConsistency(), anonymous_namespace{defaultprobabilitycurves.cpp}::testBootstrapFromSpread(), anonymous_namespace{defaultprobabilitycurves.cpp}::testBootstrapFromUpfront(), CdsOptionTest::testCached(), CreditDefaultSwapTest::testCachedMarketValue(), CreditDefaultSwapTest::testCachedValue(), DigitalCouponTest::testCallPutParity(), DigitalCouponTest::testCashOrNothing(), DigitalCouponTest::testCashOrNothingDeepInTheMoney(), DigitalCouponTest::testCashOrNothingDeepOutTheMoney(), anonymous_namespace{piecewiseyieldcurve.cpp}::testCurveConsistency(), CreditDefaultSwapTest::testFairSpread(), CreditDefaultSwapTest::testFairUpfront(), TermStructureTest::testFSpreadedObs(), NthToDefaultTest::testGaussStudent(), CdoTest::testHW(), CreditDefaultSwapTest::testImpliedHazardRate(), TermStructureTest::testImpliedObs(), LiborMarketModelProcessTest::testInitialisation(), PiecewiseYieldCurveTest::testJpyLibor(), InstrumentTest::testObservable(), QuoteTest::testObservableHandle(), DigitalCouponTest::testReplicationType(), DefaultProbabilityCurveTest::testSingleInstrumentBootstrap(), InflationTest::testYYTermStructure(), InflationTest::testZeroTermStructure(), and TermStructureTest::testZSpreadedObs().
{
        this->link_->linkTo(h,registerAsObserver);
    }
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/handle.hpp