QuantLib: QuantLib::detail::CubicInterpolationImpl< I1, I2 > Class Template Reference
QuantLib::detail::CubicInterpolationImpl< I1, I2 > Class Template Reference
#include <cubicinterpolation.hpp>
Public Member Functions
CubicInterpolationImpl (const I1 &xBegin, const I1 &xEnd, const I2 &yBegin, CubicInterpolation::DerivativeApprox da, bool monotonic, CubicInterpolation::BoundaryCondition leftCondition, Real leftConditionValue, CubicInterpolation::BoundaryCondition rightCondition, Real rightConditionValue)
void update ()
Real value (Real x) const
Real primitive (Real x) const
Real derivative (Real x) const
Real secondDerivative (Real x) const
Private Attributes
CubicInterpolation::DerivativeApprox da_
bool monotonic_
CubicInterpolation::BoundaryCondition leftType_
CubicInterpolation::BoundaryCondition rightType_
Real leftValue_
Real rightValue_
Array tmp_
std::vector< Real > dx_
std::vector< Real > S_
TridiagonalOperator L_
Detailed Description
template<class I1, class I2>
class QuantLib::detail::CubicInterpolationImpl< I1, I2 >
Definition at line 341 of file cubicinterpolation.hpp.
Constructor & Destructor Documentation
template<class I1 , class I2 > QuantLib::detail::CubicInterpolationImpl< I1, I2 >::CubicInterpolationImpl (const I1 & xBegin, const I1 & xEnd, const I2 & yBegin, CubicInterpolation::DerivativeApprox da, bool monotonic, CubicInterpolation::BoundaryCondition leftCondition, Real leftConditionValue, CubicInterpolation::BoundaryCondition rightCondition, Real rightConditionValue) [inline]
Definition at line 344 of file cubicinterpolation.hpp.
            : CoefficientHolder(xEnd-xBegin),
              Interpolation::templateImpl<I1,I2>(xBegin, xEnd, yBegin),
              da_(da),
              monotonic_(monotonic),
              leftType_(leftCondition), rightType_(rightCondition),
              leftValue_(leftConditionValue),
              rightValue_(rightConditionValue),
              tmp_(n_), dx_(n_-1), S_(n_-1), L_(n_) {}
Member Function Documentation
template<class I1 , class I2 > Real QuantLib::detail::CubicInterpolationImpl< I1, I2 >::derivative (Real x) const [inline, virtual]
Implements QuantLib::Interpolation::Impl.
Definition at line 683 of file cubicinterpolation.hpp.
References QuantLib::detail::CoefficientHolder::a_, QuantLib::detail::CoefficientHolder::b_, QuantLib::detail::CoefficientHolder::c_, QuantLib::detail::CubicInterpolationImpl< I1, I2 >::dx_, QuantLib::Interpolation::templateImpl< I1, I2 >::locate(), and QuantLib::Interpolation::templateImpl< I1, I2 >::xBegin_.
{
                Size j = this->locate(x);
                Real dx_ = x-this->xBegin_[j];
                return a_[j] + (2.0*b_[j] + 3.0*c_[j]*dx_)*dx_;
            }
template<class I1 , class I2 > Real QuantLib::detail::CubicInterpolationImpl< I1, I2 >::primitive (Real x) const [inline, virtual]
Implements QuantLib::Interpolation::Impl.
Definition at line 676 of file cubicinterpolation.hpp.
References QuantLib::detail::CoefficientHolder::a_, QuantLib::detail::CoefficientHolder::b_, QuantLib::detail::CoefficientHolder::c_, QuantLib::detail::CubicInterpolationImpl< I1, I2 >::dx_, QuantLib::Interpolation::templateImpl< I1, I2 >::locate(), QuantLib::detail::CoefficientHolder::primitiveConst_, QuantLib::Interpolation::templateImpl< I1, I2 >::xBegin_, and QuantLib::Interpolation::templateImpl< I1, I2 >::yBegin_.
{
                Size j = this->locate(x);
                Real dx_ = x-this->xBegin_[j];
                return primitiveConst_[j]
                    + dx_*(this->yBegin_[j] + dx_*(a_[j]/2.0
                    + dx_*(b_[j]/3.0 + dx_*c_[j]/4.0)));
            }
template<class I1 , class I2 > Real QuantLib::detail::CubicInterpolationImpl< I1, I2 >::secondDerivative (Real x) const [inline, virtual]
Implements QuantLib::Interpolation::Impl.
Definition at line 688 of file cubicinterpolation.hpp.
References QuantLib::detail::CoefficientHolder::b_, QuantLib::detail::CoefficientHolder::c_, QuantLib::detail::CubicInterpolationImpl< I1, I2 >::dx_, QuantLib::Interpolation::templateImpl< I1, I2 >::locate(), and QuantLib::Interpolation::templateImpl< I1, I2 >::xBegin_.
{
                Size j = this->locate(x);
                Real dx_ = x-this->xBegin_[j];
                return 2.0*b_[j] + 6.0*c_[j]*dx_;
            }
template<class I1 , class I2 > void QuantLib::detail::CubicInterpolationImpl< I1, I2 >::update () [inline, virtual]
Implements QuantLib::Interpolation::Impl.
Definition at line 362 of file cubicinterpolation.hpp.
References QuantLib::detail::CoefficientHolder::a_, QuantLib::CubicInterpolation::Akima, QuantLib::detail::CoefficientHolder::b_, QuantLib::detail::CoefficientHolder::c_, QuantLib::detail::CubicInterpolationImpl< I1, I2 >::da_, QuantLib::detail::CubicInterpolationImpl< I1, I2 >::dx_, QuantLib::CubicInterpolation::FirstDerivative, QuantLib::CubicInterpolation::FourthOrder, QuantLib::CubicInterpolation::FritschButland, QuantLib::inverse(), QuantLib::CubicInterpolation::Kruger, QuantLib::detail::CubicInterpolationImpl< I1, I2 >::L_, QuantLib::CubicInterpolation::Lagrange, QuantLib::detail::CubicInterpolationImpl< I1, I2 >::leftType_, QuantLib::detail::CubicInterpolationImpl< I1, I2 >::leftValue_, QuantLib::detail::CubicInterpolationImpl< I1, I2 >::monotonic_, QuantLib::detail::CoefficientHolder::monotonicityAdjustments_, QuantLib::detail::CoefficientHolder::n_, QuantLib::CubicInterpolation::NotAKnot, QuantLib::CubicInterpolation::Parabolic, QuantLib::CubicInterpolation::Periodic, QuantLib::detail::CoefficientHolder::primitiveConst_, QL_FAIL, QuantLib::detail::CubicInterpolationImpl< I1, I2 >::rightType_, QuantLib::detail::CubicInterpolationImpl< I1, I2 >::rightValue_, QuantLib::detail::CubicInterpolationImpl< I1, I2 >::S_, QuantLib::CubicInterpolation::SecondDerivative, QuantLib::TridiagonalOperator::setFirstRow(), QuantLib::TridiagonalOperator::setLastRow(), QuantLib::TridiagonalOperator::setMidRow(), QuantLib::TridiagonalOperator::solveFor(), QuantLib::CubicInterpolation::Spline, QuantLib::CubicInterpolation::SplineOM1, QuantLib::CubicInterpolation::SplineOM2, QuantLib::detail::CubicInterpolationImpl< I1, I2 >::tmp_, QuantLib::transpose(), QuantLib::Interpolation::templateImpl< I1, I2 >::xBegin_, and QuantLib::Interpolation::templateImpl< I1, I2 >::yBegin_.
{
                for (Size i=0; i<n_-1; ++i) {
                    dx_[i] = this->xBegin_[i+1] - this->xBegin_[i];
                    S_[i] = (this->yBegin_[i+1] - this->yBegin_[i])/dx_[i];
                }
                // first derivative approximation
                if (da_==CubicInterpolation::Spline) {
                    for (Size i=1; i<n_-1; ++i) {
                        L_.setMidRow(i, dx_[i], 2.0*(dx_[i]+dx_[i-1]), dx_[i-1]);
                        tmp_[i] = 3.0*(dx_[i]*S_[i-1] + dx_[i-1]*S_[i]);
                    }
                    // left boundary condition
                    switch (leftType_) {
                      case CubicInterpolation::NotAKnot:
                        // ignoring end condition value
                        L_.setFirstRow(dx_[1]*(dx_[1]+dx_[0]),
                                      (dx_[0]+dx_[1])*(dx_[0]+dx_[1]));
                        tmp_[0] = S_[0]*dx_[1]*(2.0*dx_[1]+3.0*dx_[0]) +
                                 S_[1]*dx_[0]*dx_[0];
                        break;
                      case CubicInterpolation::FirstDerivative:
                        L_.setFirstRow(1.0, 0.0);
                        tmp_[0] = leftValue_;
                        break;
                      case CubicInterpolation::SecondDerivative:
                        L_.setFirstRow(2.0, 1.0);
                        tmp_[0] = 3.0*S_[0] - leftValue_*dx_[0]/2.0;
                        break;
                      case CubicInterpolation::Periodic:
                      case CubicInterpolation::Lagrange:
                        // ignoring end condition value
                        QL_FAIL("this end condition is not implemented yet");
                      default:
                        QL_FAIL("unknown end condition");
                    }
                    // right boundary condition
                    switch (rightType_) {
                      case CubicInterpolation::NotAKnot:
                        // ignoring end condition value
                        L_.setLastRow(-(dx_[n_-2]+dx_[n_-3])*(dx_[n_-2]+dx_[n_-3]),
                                     -dx_[n_-3]*(dx_[n_-3]+dx_[n_-2]));
                        tmp_[n_-1] = -S_[n_-3]*dx_[n_-2]*dx_[n_-2] -
                                     S_[n_-2]*dx_[n_-3]*(3.0*dx_[n_-2]+2.0*dx_[n_-3]);
                        break;
                      case CubicInterpolation::FirstDerivative:
                        L_.setLastRow(0.0, 1.0);
                        tmp_[n_-1] = rightValue_;
                        break;
                      case CubicInterpolation::SecondDerivative:
                        L_.setLastRow(1.0, 2.0);
                        tmp_[n_-1] = 3.0*S_[n_-2] + rightValue_*dx_[n_-2]/2.0;
                        break;
                      case CubicInterpolation::Periodic:
                      case CubicInterpolation::Lagrange:
                        // ignoring end condition value
                        QL_FAIL("this end condition is not implemented yet");
                      default:
                        QL_FAIL("unknown end condition");
                    }
                    // solve the system
                    L_.solveFor(tmp_, tmp_);
                } else if (da_==CubicInterpolation::SplineOM1) {
                    Matrix T_(n_-2, n_, 0.0);
                    for (Size i=0; i<n_-2; ++i) {
                        T_[i][i]=dx_[i]/6.0;
                        T_[i][i+1]=(dx_[i+1]+dx_[i])/3.0;
                        T_[i][i+2]=dx_[i+1]/6.0;
                    }
                    Matrix S_(n_-2, n_, 0.0);
                    for (Size i=0; i<n_-2; ++i) {
                        S_[i][i]=1.0/dx_[i];
                        S_[i][i+1]=-(1.0/dx_[i+1]+1.0/dx_[i]);
                        S_[i][i+2]=1.0/dx_[i+1];
                    }
                    Matrix Up_(n_, 2, 0.0);
                    Up_[0][0]=1;
                    Up_[n_-1][1]=1;
                    Matrix Us_(n_, n_-2, 0.0);
                    for (Size i=0; i<n_-2; ++i)
                        Us_[i+1][i]=1;
                    Matrix Z_ = Us_*inverse(T_*Us_);
                    Matrix I_(n_, n_, 0.0);
                    for (Size i=0; i<n_; ++i)
                        I_[i][i]=1;
                    Matrix V_ = (I_-Z_*T_)*Up_;
                    Matrix W_ = Z_*S_;
                    Matrix Q_(n_, n_, 0.0);
                    Q_[0][0]=1.0/(n_-1)*dx_[0]*dx_[0]*dx_[0];
                    Q_[0][1]=7.0/8*1.0/(n_-1)*dx_[0]*dx_[0]*dx_[0];
                    for (Size i=1; i<n_-1; ++i) {
                        Q_[i][i-1]=7.0/8*1.0/(n_-1)*dx_[i-1]*dx_[i-1]*dx_[i-1];
                        Q_[i][i]=1.0/(n_-1)*dx_[i]*dx_[i]*dx_[i]+1.0/(n_-1)*dx_[i-1]*dx_[i-1]*dx_[i-1];
                        Q_[i][i+1]=7.0/8*1.0/(n_-1)*dx_[i]*dx_[i]*dx_[i];
                    }
                    Q_[n_-1][n_-2]=7.0/8*1.0/(n_-1)*dx_[n_-2]*dx_[n_-2]*dx_[n_-2];
                    Q_[n_-1][n_-1]=1.0/(n_-1)*dx_[n_-2]*dx_[n_-2]*dx_[n_-2];
                    Matrix J_ = (I_-V_*inverse(transpose(V_)*Q_*V_)*transpose(V_)*Q_)*W_;
                    Array Y_(n_);
                    for (Size i=0; i<n_; ++i)
                        Y_[i]=this->yBegin_[i];
                    Array D_ = J_*Y_;
                    for (Size i=0; i<n_-1; ++i)
                        tmp_[i]=(Y_[i+1]-Y_[i])/dx_[i]-(2.0*D_[i]+D_[i+1])*dx_[i]/6.0;
                    tmp_[n_-1]=tmp_[n_-2]+D_[n_-2]*dx_[n_-2]+(D_[n_-1]-D_[n_-2])*dx_[n_-2]/2.0;
                } else if (da_==CubicInterpolation::SplineOM2) {
                    Matrix T_(n_-2, n_, 0.0);
                    for (Size i=0; i<n_-2; ++i) {
                        T_[i][i]=dx_[i]/6.0;
                        T_[i][i+1]=(dx_[i]+dx_[i+1])/3.0;
                        T_[i][i+2]=dx_[i+1]/6.0;
                    }
                    Matrix S_(n_-2, n_, 0.0);
                    for (Size i=0; i<n_-2; ++i) {
                        S_[i][i]=1.0/dx_[i];
                        S_[i][i+1]=-(1.0/dx_[i+1]+1.0/dx_[i]);
                        S_[i][i+2]=1.0/dx_[i+1];
                    }
                    Matrix Up_(n_, 2, 0.0);
                    Up_[0][0]=1;
                    Up_[n_-1][1]=1;
                    Matrix Us_(n_, n_-2, 0.0);
                    for (Size i=0; i<n_-2; ++i)
                        Us_[i+1][i]=1;
                    Matrix Z_ = Us_*inverse(T_*Us_);
                    Matrix I_(n_, n_, 0.0);
                    for (Size i=0; i<n_; ++i)
                        I_[i][i]=1;
                    Matrix V_ = (I_-Z_*T_)*Up_;
                    Matrix W_ = Z_*S_;
                    Matrix Q_(n_, n_, 0.0);
                    Q_[0][0]=1.0/(n_-1)*dx_[0];
                    Q_[0][1]=1.0/2*1.0/(n_-1)*dx_[0];
                    for (Size i=1; i<n_-1; ++i) {
                        Q_[i][i-1]=1.0/2*1.0/(n_-1)*dx_[i-1];
                        Q_[i][i]=1.0/(n_-1)*dx_[i]+1.0/(n_-1)*dx_[i-1];
                        Q_[i][i+1]=1.0/2*1.0/(n_-1)*dx_[i];
                    }
                    Q_[n_-1][n_-2]=1.0/2*1.0/(n_-1)*dx_[n_-2];
                    Q_[n_-1][n_-1]=1.0/(n_-1)*dx_[n_-2];
                    Matrix J_ = (I_-V_*inverse(transpose(V_)*Q_*V_)*transpose(V_)*Q_)*W_;
                    Array Y_(n_);
                    for (Size i=0; i<n_; ++i)
                        Y_[i]=this->yBegin_[i];
                    Array D_ = J_*Y_;
                    for (Size i=0; i<n_-1; ++i)
                        tmp_[i]=(Y_[i+1]-Y_[i])/dx_[i]-(2.0*D_[i]+D_[i+1])*dx_[i]/6.0;
                    tmp_[n_-1]=tmp_[n_-2]+D_[n_-2]*dx_[n_-2]+(D_[n_-1]-D_[n_-2])*dx_[n_-2]/2.0;
                } else { // local schemes
                    if (n_==2)
                        tmp_[0] = tmp_[1] = S_[0];
                    else {
                        switch (da_) {
                            case CubicInterpolation::FourthOrder:
                                QL_FAIL("FourthOrder not implemented yet");
                                break;
                            case CubicInterpolation::Parabolic:
                                // intermediate points
                                for (Size i=1; i<n_-1; ++i)
                                    tmp_[i] = (dx_[i-1]*S_[i]+dx_[i]*S_[i-1])/(dx_[i]+dx_[i-1]);
                                // end points
                                tmp_[0]    = ((2.0*dx_[   0]+dx_[   1])*S_[   0] - dx_[   0]*S_[   1]) / (dx_[   0]+dx_[   1]);
                                tmp_[n_-1] = ((2.0*dx_[n_-2]+dx_[n_-3])*S_[n_-2] - dx_[n_-2]*S_[n_-3]) / (dx_[n_-2]+dx_[n_-3]);
                                break;
                            case CubicInterpolation::FritschButland:
                                // intermediate points
                                for (Size i=1; i<n_-1; ++i) {
                                    Real Smin = std::min(S_[i-1], S_[i]);
                                    Real Smax = std::max(S_[i-1], S_[i]);
                                    tmp_[i] = 3.0*Smin*Smax/(Smax+2.0*Smin);
                                }
                                // end points
                                tmp_[0]    = ((2.0*dx_[   0]+dx_[   1])*S_[   0] - dx_[   0]*S_[   1]) / (dx_[   0]+dx_[   1]);
                                tmp_[n_-1] = ((2.0*dx_[n_-2]+dx_[n_-3])*S_[n_-2] - dx_[n_-2]*S_[n_-3]) / (dx_[n_-2]+dx_[n_-3]);
                                break;
                            case CubicInterpolation::Akima:
                                tmp_[0] = (std::abs(S_[1]-S_[0])*2*S_[0]*S_[1]+std::abs(2*S_[0]*S_[1]-4*S_[0]*S_[0]*S_[1])*S_[0])/(std::abs(S_[1]-S_[0])+std::abs(2*S_[0]*S_[1]-4*S_[0]*S_[0]*S_[1]));
                                tmp_[1] = (std::abs(S_[2]-S_[1])*S_[0]+std::abs(S_[0]-2*S_[0]*S_[1])*S_[1])/(std::abs(S_[2]-S_[1])+std::abs(S_[0]-2*S_[0]*S_[1]));
                                for (Size i=2; i<n_-2; ++i) {
                                    if ((S_[i-2]==S_[i-1]) && (S_[i]!=S_[i+1]))
                                        tmp_[i] = S_[i-1];
                                    else if ((S_[i-2]!=S_[i-1]) && (S_[i]==S_[i+1]))
                                        tmp_[i] = S_[i];
                                    else if (S_[i]==S_[i-1])
                                        tmp_[i] = S_[i];
                                    else if ((S_[i-2]==S_[i-1]) && (S_[i-1]!=S_[i]) && (S_[i]==S_[i+1]))
                                        tmp_[i] = (S_[i-1]+S_[i])/2.0;
                                    else
                                        tmp_[i] = (std::abs(S_[i+1]-S_[i])*S_[i-1]+std::abs(S_[i-1]-S_[i-2])*S_[i])/(std::abs(S_[i+1]-S_[i])+std::abs(S_[i-1]-S_[i-2]));
                                 }
                                 tmp_[n_-2] = (std::abs(2*S_[n_-2]*S_[n_-3]-S_[n_-2])*S_[n_-3]+std::abs(S_[n_-3]-S_[n_-4])*S_[n_-2])/(std::abs(2*S_[n_-2]*S_[n_-3]-S_[n_-2])+std::abs(S_[n_-3]-S_[n_-4]));
                                 tmp_[n_-1] = (std::abs(4*S_[n_-2]*S_[n_-2]*S_[n_-3]-2*S_[n_-2]*S_[n_-3])*S_[n_-2]+std::abs(S_[n_-2]-S_[n_-3])*2*S_[n_-2]*S_[n_-3])/(std::abs(4*S_[n_-2]*S_[n_-2]*S_[n_-3]-2*S_[n_-2]*S_[n_-3])+std::abs(S_[n_-2]-S_[n_-3]));
                                 break;
                            case CubicInterpolation::Kruger:
                                // intermediate points
                                for (Size i=1; i<n_-1; ++i) {
                                    if (S_[i-1]*S_[i]<0.0)
                                        // slope changes sign at point
                                        tmp_[i] = 0.0;
                                    else
                                        // slope will be between the slopes of the adjacent
                                        // straight lines and should approach zero if the
                                        // slope of either line approaches zero
                                        tmp_[i] = 2.0/(1.0/S_[i-1]+1.0/S_[i]);
                                }
                                // end points
                                tmp_[0] = (3.0*S_[0]-tmp_[1])/2.0;
                                tmp_[n_-1] = (3.0*S_[n_-2]-tmp_[n_-2])/2.0;
                                break;
                            default:
                                QL_FAIL("unknown scheme");
                        }
                    }
                }
                std::fill(monotonicityAdjustments_.begin(),
                          monotonicityAdjustments_.end(), false);
                // Hyman monotonicity constrained filter
                if (monotonic_) {
                    Real correction;
                    Real pm, pu, pd, M;
                    for (Size i=0; i<n_; ++i) {
                        if (i==0) {
                            if (tmp_[i]*S_[0]>0.0) {
                                correction = tmp_[i]/std::fabs(tmp_[i]) *
                                    std::min<Real>(std::fabs(tmp_[i]),
                                                   std::fabs(3.0*S_[0]));
                            } else {
                                correction = 0.0;
                            }
                            if (correction!=tmp_[i]) {
                                tmp_[i] = correction;
                                monotonicityAdjustments_[i] = true;
                            }
                        } else if (i==n_-1) {
                            if (tmp_[i]*S_[n_-2]>0.0) {
                                correction = tmp_[i]/std::fabs(tmp_[i]) *
                                    std::min<Real>(std::fabs(tmp_[i]),
                                                   std::fabs(3.0*S_[n_-2]));
                            } else {
                                correction = 0.0;
                            }
                            if (correction!=tmp_[i]) {
                                tmp_[i] = correction;
                                monotonicityAdjustments_[i] = true;
                            }
                        } else {
                            pm=(S_[i-1]*dx_[i]+S_[i]*dx_[i-1])/
                                (dx_[i-1]+dx_[i]);
                            M = 3.0 * std::min(std::min(std::fabs(S_[i-1]),
                                                        std::fabs(S_[i])),
                                               std::fabs(pm));
                            if (i>1) {
                                if ((S_[i-1]-S_[i-2])*(S_[i]-S_[i-1])>0.0) {
                                    pd=(S_[i-1]*(2.0*dx_[i-1]+dx_[i-2])
                                        -S_[i-2]*dx_[i-1])/
                                        (dx_[i-2]+dx_[i-1]);
                                    if (pm*pd>0.0 && pm*(S_[i-1]-S_[i-2])>0.0) {
                                        M = std::max<Real>(M, 1.5*std::min(
                                                std::fabs(pm),std::fabs(pd)));
                                    }
                                }
                            }
                            if (i<n_-2) {
                                if ((S_[i]-S_[i-1])*(S_[i+1]-S_[i])>0.0) {
                                    pu=(S_[i]*(2.0*dx_[i]+dx_[i+1])-S_[i+1]*dx_[i])/
                                        (dx_[i]+dx_[i+1]);
                                    if (pm*pu>0.0 && -pm*(S_[i]-S_[i-1])>0.0) {
                                        M = std::max<Real>(M, 1.5*std::min(
                                                std::fabs(pm),std::fabs(pu)));
                                    }
                                }
                            }
                            if (tmp_[i]*pm>0.0) {
                                correction = tmp_[i]/std::fabs(tmp_[i]) *
                                    std::min(std::fabs(tmp_[i]), M);
                            } else {
                                correction = 0.0;
                            }
                            if (correction!=tmp_[i]) {
                                tmp_[i] = correction;
                                monotonicityAdjustments_[i] = true;
                            }
                        }
                    }
                }
                // cubic coefficients
                for (Size i=0; i<n_-1; ++i) {
                    a_[i] = tmp_[i];
                    b_[i] = (3.0*S_[i] - tmp_[i+1] - 2.0*tmp_[i])/dx_[i];
                    c_[i] = (tmp_[i+1] + tmp_[i] - 2.0*S_[i])/(dx_[i]*dx_[i]);
                }
                primitiveConst_[0] = 0.0;
                for (Size i=1; i<n_-1; ++i) {
                    primitiveConst_[i] = primitiveConst_[i-1]
                        + dx_[i-1] *
                        (this->yBegin_[i-1] + dx_[i-1] *
                         (a_[i-1]/2.0 + dx_[i-1] *
                          (b_[i-1]/3.0 + dx_[i-1] * c_[i-1]/4.0)));
                }
            }
template<class I1 , class I2 > Real QuantLib::detail::CubicInterpolationImpl< I1, I2 >::value (Real x) const [inline, virtual]
Implements QuantLib::Interpolation::Impl.
Definition at line 671 of file cubicinterpolation.hpp.
References QuantLib::detail::CoefficientHolder::a_, QuantLib::detail::CoefficientHolder::b_, QuantLib::detail::CoefficientHolder::c_, QuantLib::detail::CubicInterpolationImpl< I1, I2 >::dx_, QuantLib::Interpolation::templateImpl< I1, I2 >::locate(), QuantLib::Interpolation::templateImpl< I1, I2 >::xBegin_, and QuantLib::Interpolation::templateImpl< I1, I2 >::yBegin_.
{
                Size j = this->locate(x);
                Real dx_ = x-this->xBegin_[j];
                return this->yBegin_[j] + dx_*(a_[j] + dx_*(b_[j] + dx_*c_[j]));
            }
Member Data Documentation
template<class I1 , class I2 > CubicInterpolation::DerivativeApprox QuantLib::detail::CubicInterpolationImpl< I1, I2 >::da_ [private]
Definition at line 694 of file cubicinterpolation.hpp.
Referenced by QuantLib::detail::CubicInterpolationImpl< I1, I2 >::update().
template<class I1 , class I2 > std::vector<Real> QuantLib::detail::CubicInterpolationImpl< I1, I2 >::dx_ [mutable, private]
Definition at line 699 of file cubicinterpolation.hpp.
Referenced by QuantLib::detail::CubicInterpolationImpl< I1, I2 >::derivative(), QuantLib::detail::CubicInterpolationImpl< I1, I2 >::primitive(), QuantLib::detail::CubicInterpolationImpl< I1, I2 >::secondDerivative(), QuantLib::detail::CubicInterpolationImpl< I1, I2 >::update(), and QuantLib::detail::CubicInterpolationImpl< I1, I2 >::value().
template<class I1 , class I2 > TridiagonalOperator QuantLib::detail::CubicInterpolationImpl< I1, I2 >::L_ [mutable, private]
Definition at line 700 of file cubicinterpolation.hpp.
Referenced by QuantLib::detail::CubicInterpolationImpl< I1, I2 >::update().
template<class I1 , class I2 > CubicInterpolation::BoundaryCondition QuantLib::detail::CubicInterpolationImpl< I1, I2 >::leftType_ [private]
Definition at line 696 of file cubicinterpolation.hpp.
Referenced by QuantLib::detail::CubicInterpolationImpl< I1, I2 >::update().
template<class I1 , class I2 > Real QuantLib::detail::CubicInterpolationImpl< I1, I2 >::leftValue_ [private]
Definition at line 697 of file cubicinterpolation.hpp.
Referenced by QuantLib::detail::CubicInterpolationImpl< I1, I2 >::update().
template<class I1 , class I2 > bool QuantLib::detail::CubicInterpolationImpl< I1, I2 >::monotonic_ [private]
Definition at line 695 of file cubicinterpolation.hpp.
Referenced by QuantLib::detail::CubicInterpolationImpl< I1, I2 >::update().
template<class I1 , class I2 > CubicInterpolation::BoundaryCondition QuantLib::detail::CubicInterpolationImpl< I1, I2 >::rightType_ [private]
Definition at line 696 of file cubicinterpolation.hpp.
Referenced by QuantLib::detail::CubicInterpolationImpl< I1, I2 >::update().
template<class I1 , class I2 > Real QuantLib::detail::CubicInterpolationImpl< I1, I2 >::rightValue_ [private]
Definition at line 697 of file cubicinterpolation.hpp.
Referenced by QuantLib::detail::CubicInterpolationImpl< I1, I2 >::update().
template<class I1 , class I2 > std::vector<Real> QuantLib::detail::CubicInterpolationImpl< I1, I2 >::S_ [mutable, private]
Definition at line 699 of file cubicinterpolation.hpp.
Referenced by QuantLib::detail::CubicInterpolationImpl< I1, I2 >::update().
template<class I1 , class I2 > Array QuantLib::detail::CubicInterpolationImpl< I1, I2 >::tmp_ [mutable, private]
Definition at line 698 of file cubicinterpolation.hpp.
Referenced by QuantLib::detail::CubicInterpolationImpl< I1, I2 >::update().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/interpolations/cubicinterpolation.hpp