QuantLib: InflationCPICapFloorTest Class Reference
InflationCPICapFloorTest Class Reference
#include <inflationcpicapfloor.hpp>
Static Public Member Functions
static void cpicapfloorpricesurface ()
tests CPI price surface reproduction
static void cpicapfloorpricer ()
tests interpolation pricer
static
boost::unit_test_framework::test_suite * suite ()
Detailed Description
Tests cpi cap/floor price data N.B. a cpi cap produces ONE flow only - because inflation is cumulative.
Definition at line 31 of file inflationcpicapfloor.hpp.
Member Function Documentation
void InflationCPICapFloorTest::cpicapfloorpricer () [static]
tests interpolation pricer
Definition at line 392 of file inflationcpicapfloor.cpp.
References QuantLib::Calendar::adjust(), QuantLib::CPI::AsIndex, QuantLib::Option::Call, anonymous_namespace{marketmodel.cpp}::d, QuantLib::Settings::evaluationDate(), QuantLib::Singleton< Settings >::instance(), QuantLib::ModifiedFollowing, QuantLib::Instrument::NPV(), QL_REQUIRE, QuantLib::Instrument::setPricingEngine(), anonymous_namespace{marketmodel.cpp}::startDate, QuantLib::Unadjusted, and QuantLib::Years.
Referenced by suite().
{
    CommonVars common;
    Real nominal = 1.0;
    boost::shared_ptr<CPICapFloorTermPriceSurface> cpiCFpriceSurf(new InterpolatedCPICapFloorTermPriceSurface
                                                    <Bilinear>(nominal,
                                                               common.baseZeroRate,
                                                               common.observationLag,
                                                               common.calendar,
                                                               common.convention,
                                                               common.dcZCIIS,
                                                               common.hii,
                                                               common.nominalUK,
                                                               common.cStrikesUK,
                                                               common.fStrikesUK,
                                                               common.cfMaturitiesUK,
                                                               *(common.cPriceUK),
                                                               *(common.fPriceUK)));
    common.cpiCFsurfUK = cpiCFpriceSurf;
    // interpolation pricer first
    // N.B. no new instrument required but we do need a new pricer
    Date startDate = Settings::instance().evaluationDate();
    Date maturity(startDate + Period(3,Years));
    Calendar fixCalendar = UnitedKingdom(), payCalendar = UnitedKingdom();
    BusinessDayConvention fixConvention(Unadjusted), payConvention(ModifiedFollowing);
    Rate strike(0.03);
    Real baseCPI = common.hii->fixing(fixCalendar.adjust(startDate-common.observationLag,fixConvention));
    CPI::InterpolationType observationInterpolation = CPI::AsIndex;
    CPICapFloor aCap(Option::Call,
                     nominal,
                     startDate,   // start date of contract (only)
                     baseCPI,
                     maturity,    // this is pre-adjustment!
                     fixCalendar,
                     fixConvention,
                     payCalendar,
                     payConvention,
                     strike,
                     common.hii,
                     common.observationLag,
                     observationInterpolation);
    Handle<CPICapFloorTermPriceSurface> cpiCFsurfUKh(common.cpiCFsurfUK);
    boost::shared_ptr<PricingEngine>engine(new InterpolatingCPICapFloorEngine(cpiCFsurfUKh));
    aCap.setPricingEngine(engine);
    Date d = common.cpiCFsurfUK->cpiOptionDateFromTenor(Period(3,Years));
    Real cached = cpiCFsurfUKh->capPrice(d, strike);
    QL_REQUIRE(fabs(cached - aCap.NPV())<1e-10,"InterpolatingCPICapFloorEngine does not reproduce cached price: "
               << cached << " vs " << aCap.NPV());
    // remove circular refernce
    common.hcpi.linkTo(boost::shared_ptr<ZeroInflationTermStructure>());
}
void InflationCPICapFloorTest::cpicapfloorpricesurface () [static]
tests CPI price surface reproduction
Definition at line 335 of file inflationcpicapfloor.cpp.
References anonymous_namespace{marketmodel.cpp}::a, anonymous_namespace{marketmodel.cpp}::b, QL_REQUIRE, and anonymous_namespace{quantlibbenchmark.cpp}::t.
Referenced by suite().
{
    // check inflation leg vs calculation directly from inflation TS
    CommonVars common;
    Real nominal = 1.0;
    InterpolatedCPICapFloorTermPriceSurface
    <Bilinear> cpiSurf(nominal,
                       common.baseZeroRate,
                       common.observationLag,
                       common.calendar,
                       common.convention,
                       common.dcZCIIS,
                       common.hii,
                       common.nominalUK,
                       common.cStrikesUK,
                       common.fStrikesUK,
                       common.cfMaturitiesUK,
                       *(common.cPriceUK),
                       *(common.fPriceUK));
    // test code - note order of indices
     for (Size i =0; i<common.fStrikesUK.size(); i++){
         Real qK = common.fStrikesUK[i];
         Size nMat = common.cfMaturitiesUK.size();
         for (Size j=0; j<nMat; j++) {
             Period t = common.cfMaturitiesUK[j];
             Real a = (*(common.fPriceUK))[i][j];
             Real b = cpiSurf.floorPrice(t,qK);
             QL_REQUIRE(fabs(a-b)<1e-7,"cannot reproduce cpi floor data from surface: "
                        << a << " vs constructed = " << b);
         }
     }
    for (Size i =0; i<common.cStrikesUK.size(); i++){
        Real qK = common.cStrikesUK[i];
        Size nMat = common.cfMaturitiesUK.size();
        for (Size j=0; j<nMat; j++) {
            Period t = common.cfMaturitiesUK[j];
            Real a = (*(common.cPriceUK))[i][j];
            Real b = cpiSurf.capPrice(t,qK);
            QL_REQUIRE(fabs(a-b)<1e-7,"cannot reproduce cpi cap data from surface: "
                       << a << " vs constructed = " << b);
        }
    }
    // remove circular refernce
    common.hcpi.linkTo(boost::shared_ptr<ZeroInflationTermStructure>());
}
test_suite * InflationCPICapFloorTest::suite () [static]
Definition at line 456 of file inflationcpicapfloor.cpp.
References cpicapfloorpricer(), cpicapfloorpricesurface(), and QUANTLIB_TEST_CASE.
Referenced by init_unit_test_suite().
{
    test_suite* suite = BOOST_TEST_SUITE("CPIswaption tests");
    suite->add(QUANTLIB_TEST_CASE(&InflationCPICapFloorTest::cpicapfloorpricesurface));
    suite->add(QUANTLIB_TEST_CASE(&InflationCPICapFloorTest::cpicapfloorpricer));
    return suite;
}
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/inflationcpicapfloor.hpp
/home/deriversatile/QuantLib/QuantLibQt/test-suite/inflationcpicapfloor.cpp