QuantLib: QuantLib::LocalConstantVol Class Reference
QuantLib::LocalConstantVol Class Reference
Constant local volatility, no time-strike dependence.
#include <localconstantvol.hpp>
Public Member Functions
LocalConstantVol (const Date &referenceDate, Volatility volatility, const DayCounter &dayCounter)
LocalConstantVol (const Date &referenceDate, const Handle< Quote > &volatility, const DayCounter &dayCounter)
LocalConstantVol (Natural settlementDays, const Calendar &, Volatility volatility, const DayCounter &dayCounter)
LocalConstantVol (Natural settlementDays, const Calendar &, const Handle< Quote > &volatility, const DayCounter &dayCounter)
TermStructure interface
DayCounter dayCounter () const
the day counter used for date/time conversion
Date maxDate () const
the latest date for which the curve can return values
VolatilityTermStructure interface
Real minStrike () const
the minimum strike for which the term structure can return vols
Real maxStrike () const
the maximum strike for which the term structure can return vols
Visitability
virtual void accept (AcyclicVisitor &)
Private Member Functions
Volatility localVolImpl (Time, Real) const
local vol calculation
Private Attributes
Handle< Quote > volatility_
DayCounter dayCounter_
Detailed Description
Constant local volatility, no time-strike dependence.
This class implements the LocalVolatilityTermStructure interface for a constant local volatility (no time/asset dependence). Local volatility and Black volatility are the same when volatility is at most time dependent, so this class is basically a proxy for BlackVolatilityTermStructure.
Definition at line 39 of file localconstantvol.hpp.
Constructor & Destructor Documentation
QuantLib::LocalConstantVol::LocalConstantVol (const Date & referenceDate, Volatility volatility, const DayCounter & dayCounter) [inline]
Definition at line 77 of file localconstantvol.hpp.
    : LocalVolTermStructure(referenceDate),
      volatility_(boost::shared_ptr<Quote>(new SimpleQuote(volatility))),
      dayCounter_(dayCounter) {}
QuantLib::LocalConstantVol::LocalConstantVol (const Date & referenceDate, const Handle< Quote > & volatility, const DayCounter & dayCounter) [inline]
Definition at line 84 of file localconstantvol.hpp.
References QuantLib::Observer::registerWith(), and volatility_.
    : LocalVolTermStructure(referenceDate), volatility_(volatility),
      dayCounter_(dayCounter) {
        registerWith(volatility_);
    }
QuantLib::LocalConstantVol::LocalConstantVol (Natural settlementDays, const Calendar & calendar, Volatility volatility, const DayCounter & dayCounter) [inline]
Definition at line 92 of file localconstantvol.hpp.
    : LocalVolTermStructure(settlementDays,calendar),
      volatility_(boost::shared_ptr<Quote>(new SimpleQuote(volatility))),
      dayCounter_(dayCounter) {}
QuantLib::LocalConstantVol::LocalConstantVol (Natural settlementDays, const Calendar & calendar, const Handle< Quote > & volatility, const DayCounter & dayCounter) [inline]
Definition at line 100 of file localconstantvol.hpp.
References QuantLib::Observer::registerWith(), and volatility_.
    : LocalVolTermStructure(settlementDays,calendar), volatility_(volatility),
      dayCounter_(dayCounter) {
        registerWith(volatility_);
    }
Member Function Documentation
void QuantLib::LocalConstantVol::accept (AcyclicVisitor & v) [inline, virtual]
Reimplemented from QuantLib::LocalVolTermStructure.
Definition at line 109 of file localconstantvol.hpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Visitor< T >::visit().
{
        Visitor<LocalConstantVol>* v1 =
            dynamic_cast<Visitor<LocalConstantVol>*>(&v);
        if (v1 != 0)
            v1->visit(*this);
        else
            LocalVolTermStructure::accept(v);
    }
DayCounter QuantLib::LocalConstantVol::dayCounter () const [inline, virtual]
the day counter used for date/time conversion
Reimplemented from QuantLib::TermStructure.
Definition at line 57 of file localconstantvol.hpp.
References dayCounter_.
{ return dayCounter_; }
Volatility QuantLib::LocalConstantVol::localVolImpl (Time t, Real strike) const [inline, private, virtual]
local vol calculation
Implements QuantLib::LocalVolTermStructure.
Definition at line 118 of file localconstantvol.hpp.
References volatility_.
{
        return volatility_->value();
    }
Date QuantLib::LocalConstantVol::maxDate () const [inline, virtual]
the latest date for which the curve can return values
Implements QuantLib::TermStructure.
Definition at line 58 of file localconstantvol.hpp.
{ return Date::maxDate(); }
Real QuantLib::LocalConstantVol::maxStrike () const [inline, virtual]
the maximum strike for which the term structure can return vols
Implements QuantLib::VolatilityTermStructure.
Definition at line 63 of file localconstantvol.hpp.
References QL_MAX_REAL.
{ return QL_MAX_REAL; }
Real QuantLib::LocalConstantVol::minStrike () const [inline, virtual]
the minimum strike for which the term structure can return vols
Implements QuantLib::VolatilityTermStructure.
Definition at line 62 of file localconstantvol.hpp.
References QL_MIN_REAL.
{ return QL_MIN_REAL; }
Member Data Documentation
DayCounter QuantLib::LocalConstantVol::dayCounter_ [private]
Reimplemented from QuantLib::TermStructure.
Definition at line 72 of file localconstantvol.hpp.
Referenced by dayCounter().
Handle<Quote> QuantLib::LocalConstantVol::volatility_ [private]
Definition at line 71 of file localconstantvol.hpp.
Referenced by LocalConstantVol(), and localVolImpl().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/equityfx/localconstantvol.hpp