QuantLib: QuantLib::YoYInflationCapFloorEngine Class Reference
QuantLib::YoYInflationCapFloorEngine Class Reference
Base YoY inflation cap/floor engine.
#include <inflationcapfloorengines.hpp>
Public Member Functions
YoYInflationCapFloorEngine (const boost::shared_ptr< YoYInflationIndex > &, const Handle< YoYOptionletVolatilitySurface > &vol)
boost::shared_ptr
< YoYInflationIndex > index () const
Handle
< YoYOptionletVolatilitySurface > volatility () const
void setVolatility (const Handle< YoYOptionletVolatilitySurface > &vol)
void calculate () const
Protected Member Functions
virtual Real optionletImpl (Option::Type type, Rate strike, Rate forward, Real stdDev, Real d) const =0
descendents only need to implement this
Protected Attributes
boost::shared_ptr
< YoYInflationIndex > index_
Handle
< YoYOptionletVolatilitySurface > volatility_
Detailed Description
Base YoY inflation cap/floor engine.
This class doesn't know yet what sort of vol it is. The inflation index must be linked to a yoy inflation term structure. This provides the curves, hence the call uses a shared_ptr<> not a handle<> to the index.
Definition at line 45 of file inflationcapfloorengines.hpp.
Constructor & Destructor Documentation
QuantLib::YoYInflationCapFloorEngine::YoYInflationCapFloorEngine (const boost::shared_ptr< YoYInflationIndex > & index, const Handle< YoYOptionletVolatilitySurface > & vol)
Definition at line 28 of file inflationcapfloorengines.cpp.
References index_, QuantLib::Observer::registerWith(), and volatility_.
    : index_(index), volatility_(volatility) {
        registerWith(index_);
        registerWith(volatility_);
    }
Member Function Documentation
void QuantLib::YoYInflationCapFloorEngine::calculate () const [virtual]
Implements QuantLib::PricingEngine.
Definition at line 47 of file inflationcapfloorengines.cpp.
References QuantLib::YoYInflationCapFloor::arguments::accrualTimes, QuantLib::GenericEngine< YoYInflationCapFloor::arguments, YoYInflationCapFloor::results >::arguments_, QuantLib::Option::Call, QuantLib::YoYInflationCapFloor::Cap, QuantLib::YoYInflationCapFloor::arguments::capRates, QuantLib::YoYInflationCapFloor::Collar, anonymous_namespace{marketmodel.cpp}::d, QuantLib::Days, QuantLib::YoYInflationCapFloor::arguments::fixingDates, QuantLib::YoYInflationCapFloor::Floor, QuantLib::YoYInflationCapFloor::arguments::floorRates, QuantLib::YoYInflationCapFloor::arguments::gearings, index(), QuantLib::YoYInflationCapFloor::arguments::nominals, optionletImpl(), QuantLib::YoYInflationCapFloor::arguments::payDates, QuantLib::Option::Put, QuantLib::GenericEngine< YoYInflationCapFloor::arguments, YoYInflationCapFloor::results >::results_, QuantLib::YoYInflationCapFloor::arguments::startDates, QuantLib::YoYInflationCapFloor::arguments::type, and volatility_.
{
        // copy black version then adapt to others
        Real value = 0.0;
        Size optionlets = arguments_.startDates.size();
        std::vector<Real> values(optionlets, 0.0);
        std::vector<Real> stdDevs(optionlets, 0.0);
        std::vector<Real> forwards(optionlets, 0.0);
        YoYInflationCapFloor::Type type = arguments_.type;
        Handle<YoYInflationTermStructure> yoyTS
        = index()->yoyInflationTermStructure();
        Handle<YieldTermStructure> nominalTS
        = yoyTS->nominalTermStructure();
        Date settlement = nominalTS->referenceDate();
        for (Size i=0; i<optionlets; ++i) {
            Date paymentDate = arguments_.payDates[i];
            if (paymentDate > settlement) { // discard expired caplets
                DiscountFactor d = arguments_.nominals[i] *
                    arguments_.gearings[i] *
                    nominalTS->discount(paymentDate) *
                arguments_.accrualTimes[i];
                // We explicitly have the index and assume that
                // the fixing is natural, i.e. no convexity adjustment.
                // If that was required then we would also need
                // nominal vols in the pricing engine, i.e. a different engine.
                // This also means that we do not need the coupon to have
                // a pricing engine to return the swaplet rate and then
                // the adjusted fixing in the instrument.
                forwards[i] = yoyTS->yoyRate(arguments_.fixingDates[i],Period(0,Days));
                Rate forward = forwards[i];
                Date fixingDate = arguments_.fixingDates[i];
                Time sqrtTime = 0.0;
                if (fixingDate > volatility_->baseDate()){
                    sqrtTime = std::sqrt(
                        volatility_->timeFromBase(fixingDate));
                }
                if (type == YoYInflationCapFloor::Cap || type == YoYInflationCapFloor::Collar) {
                    Rate strike = arguments_.capRates[i];
                    if (sqrtTime>0.0) {
                        stdDevs[i] = std::sqrt(
                            volatility_->totalVariance(fixingDate, strike, Period(0,Days)));
                    }
                    // sttDev=0 for already-fixed dates so everything on forward
                    values[i] = optionletImpl(Option::Call, strike,
                                              forward, stdDevs[i], d);
                }
                if (type == YoYInflationCapFloor::Floor || type == YoYInflationCapFloor::Collar) {
                    Rate strike = arguments_.floorRates[i];
                    if (sqrtTime>0.0) {
                        stdDevs[i] = std::sqrt(
                            volatility_->totalVariance(fixingDate, strike, Period(0,Days)));
                    }
                    Real floorlet = optionletImpl(Option::Put, strike,
                                                  forward, stdDevs[i], d);
                    if (type == YoYInflationCapFloor::Floor) {
                        values[i] = floorlet;
                    } else {
                        // a collar is long a cap and short a floor
                        values[i] -= floorlet;
                    }
                }
                value += values[i];
            }
        }
        results_.value = value;
        results_.additionalResults["optionletsPrice"] = values;
        results_.additionalResults["optionletsAtmForward"] = forwards;
        if (type != YoYInflationCapFloor::Collar)
            results_.additionalResults["optionletsStdDev"] = stdDevs;
    }
boost::shared_ptr<YoYInflationIndex> QuantLib::YoYInflationCapFloorEngine::index () const [inline]
Definition at line 50 of file inflationcapfloorengines.hpp.
References index_.
Referenced by calculate().
{ return index_;}
virtual Real QuantLib::YoYInflationCapFloorEngine::optionletImpl (Option::Type type, Rate strike, Rate forward, Real stdDev, Real d) const [protected, pure virtual]
descendents only need to implement this
Implemented in QuantLib::YoYInflationBachelierCapFloorEngine, QuantLib::YoYInflationUnitDisplacedBlackCapFloorEngine, and QuantLib::YoYInflationBlackCapFloorEngine.
Referenced by calculate().
void QuantLib::YoYInflationCapFloorEngine::setVolatility (const Handle< YoYOptionletVolatilitySurface > & vol)
Definition at line 37 of file inflationcapfloorengines.cpp.
References QuantLib::Handle< T >::empty(), QuantLib::Observer::registerWith(), QuantLib::Observer::unregisterWith(), QuantLib::GenericEngine< YoYInflationCapFloor::arguments, YoYInflationCapFloor::results >::update(), anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and volatility_.
{
        if (!volatility_.empty())
            unregisterWith(volatility_);
        volatility_ = v;
        registerWith(volatility_);
        update();
    }
Handle<YoYOptionletVolatilitySurface> QuantLib::YoYInflationCapFloorEngine::volatility () const [inline]
Definition at line 51 of file inflationcapfloorengines.hpp.
References volatility_.
{ return volatility_; }
Member Data Documentation
boost::shared_ptr<YoYInflationIndex> QuantLib::YoYInflationCapFloorEngine::index_ [protected]
Definition at line 63 of file inflationcapfloorengines.hpp.
Referenced by index(), and YoYInflationCapFloorEngine().
Handle<YoYOptionletVolatilitySurface> QuantLib::YoYInflationCapFloorEngine::volatility_ [protected]
Definition at line 64 of file inflationcapfloorengines.hpp.
Referenced by calculate(), setVolatility(), volatility(), and YoYInflationCapFloorEngine().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/inflation/inflationcapfloorengines.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/inflation/inflationcapfloorengines.cpp