QuantLib: OvernightIndexedSwapTest Class Reference
OvernightIndexedSwapTest Class Reference
#include <overnightindexedswap.hpp>
Static Public Member Functions
static void testFairRate ()
static void testFairSpread ()
static void testCachedValue ()
static void testBootstrap ()
static
boost::unit_test_framework::test_suite * suite ()
Detailed Description
Definition at line 28 of file overnightindexedswap.hpp.
Member Function Documentation
test_suite * OvernightIndexedSwapTest::suite () [static]
Definition at line 428 of file overnightindexedswap.cpp.
References QUANTLIB_TEST_CASE, testBootstrap(), testCachedValue(), testFairRate(), and testFairSpread().
Referenced by init_unit_test_suite().
{
    test_suite* suite = BOOST_TEST_SUITE("Overnight-indexed swap tests");
    suite->add(QUANTLIB_TEST_CASE(&OvernightIndexedSwapTest::testFairRate));
    suite->add(QUANTLIB_TEST_CASE(&OvernightIndexedSwapTest::testFairSpread));
    suite->add(QUANTLIB_TEST_CASE(&OvernightIndexedSwapTest::testCachedValue));
    suite->add(QUANTLIB_TEST_CASE(&OvernightIndexedSwapTest::testBootstrap));
    return suite;
}
void OvernightIndexedSwapTest::testBootstrap () [static]
Definition at line 298 of file overnightindexedswap.cpp.
References QuantLib::Days, anonymous_namespace{overnightindexedswap.cpp}::depositData, anonymous_namespace{overnightindexedswap.cpp}::eoniaSwapData, anonymous_namespace{overnightindexedswap.cpp}::fraData, anonymous_namespace{overnightindexedswap.cpp}::SwapDatum::indexUnit, LENGTH, QuantLib::Months, anonymous_namespace{overnightindexedswap.cpp}::Datum::n, anonymous_namespace{overnightindexedswap.cpp}::SwapDatum::nIndexUnits, anonymous_namespace{overnightindexedswap.cpp}::SwapDatum::nTermUnits, anonymous_namespace{overnightindexedswap.cpp}::Datum::rate, anonymous_namespace{overnightindexedswap.cpp}::FraDatum::rate, anonymous_namespace{overnightindexedswap.cpp}::SwapDatum::rate, QuantLib::io::rate(), QuantLib::swap(), anonymous_namespace{overnightindexedswap.cpp}::swapData, anonymous_namespace{overnightindexedswap.cpp}::SwapDatum::termUnit, anonymous_namespace{gaussianquadratures.cpp}::tolerance, and anonymous_namespace{overnightindexedswap.cpp}::Datum::unit.
Referenced by suite().
{
    BOOST_MESSAGE("Testing Eonia-swap curve building...");
    CommonVars vars;
    std::vector<shared_ptr<RateHelper> > eoniaHelpers;
    std::vector<shared_ptr<RateHelper> > swap3mHelpers;
    shared_ptr<IborIndex> euribor3m(new Euribor3M);
    shared_ptr<Eonia> eonia(new Eonia);
    for (Size i = 0; i < LENGTH(depositData); i++) {
        Real rate = 0.01 * depositData[i].rate;
        shared_ptr<SimpleQuote> simple = shared_ptr<SimpleQuote>(new SimpleQuote(rate));
        shared_ptr<Quote> quote (simple);
        Period term = depositData[i].n * depositData[i].unit;
        shared_ptr<RateHelper> helper(new
                    DepositRateHelper(Handle<Quote>(quote),
                                      term,
                                      depositData[i].settlementDays,
                                      euribor3m->fixingCalendar(),
                                      euribor3m->businessDayConvention(),
                                      euribor3m->endOfMonth(),
                                      euribor3m->dayCounter()));
        if (term <= 2*Days)
            eoniaHelpers.push_back(helper);
        if (term <= 3*Months)
            swap3mHelpers.push_back(helper);
    }
    for (Size i = 0; i < LENGTH(fraData); i++) {
        Real rate = 0.01 * fraData[i].rate;
        shared_ptr<SimpleQuote> simple = shared_ptr<SimpleQuote>(new SimpleQuote(rate));
        shared_ptr<Quote> quote (simple);
        shared_ptr<RateHelper> helper(new
                               FraRateHelper(Handle<Quote>(quote),
                                             fraData[i].nExpiry,
                                             fraData[i].nMaturity,
                                             fraData[i].settlementDays,
                                             euribor3m->fixingCalendar(),
                                             euribor3m->businessDayConvention(),
                                             euribor3m->endOfMonth(),
                                             euribor3m->dayCounter()));
        swap3mHelpers.push_back(helper);
    }
    for (Size i = 0; i < LENGTH(eoniaSwapData); i++) {
        Real rate = 0.01 * eoniaSwapData[i].rate;
        shared_ptr<SimpleQuote> simple = shared_ptr<SimpleQuote>(new SimpleQuote(rate));
        shared_ptr<Quote> quote (simple);
        Period term = eoniaSwapData[i].n * eoniaSwapData[i].unit;
        shared_ptr<RateHelper> helper(new
                     OISRateHelper(eoniaSwapData[i].settlementDays,
                                   term,
                                   Handle<Quote>(quote),
                                   eonia));
        eoniaHelpers.push_back(helper);
    }
    for (Size i = 0; i < LENGTH(swapData); i++) {
        Real rate = 0.01 * swapData[i].rate;
        shared_ptr<SimpleQuote> simple = shared_ptr<SimpleQuote>(new SimpleQuote(rate));
        shared_ptr<Quote> quote (simple);
        Period tenor = swapData[i].nIndexUnits * swapData[i].indexUnit;
        Period term = swapData[i].nTermUnits * swapData[i].termUnit;
        shared_ptr<RateHelper> helper(new SwapRateHelper(
                               Handle<Quote>(quote),
                               term,
                               vars.calendar,
                               vars.fixedSwapFrequency,
                               vars.fixedSwapConvention,
                               vars.fixedSwapDayCount,
                               euribor3m));
        if (tenor == 3*Months)
            swap3mHelpers.push_back(helper);
    }
    shared_ptr<PiecewiseFlatForward> eoniaTS(new
        PiecewiseFlatForward (vars.today, eoniaHelpers, Actual365Fixed()));
    shared_ptr<PiecewiseFlatForward> swapTS(new
        PiecewiseFlatForward (vars.today, swap3mHelpers, Actual365Fixed()));
    vars.eoniaTermStructure.linkTo(eoniaTS);
    /*
    std::cout.setf (std::ios::fixed, std::ios::floatfield);
    std::cout.setf (std::ios::showpoint);
    */
    // test curve consistency
    Real tolerance = 1.0e-8;
    for (Size i = 0; i < LENGTH(eoniaSwapData); i++) {
        Rate expected = eoniaSwapData[i].rate;
        Period term = eoniaSwapData[i].n * eoniaSwapData[i].unit;
        shared_ptr<OvernightIndexedSwap> swap = vars.makeSwap(term, 0.0, 0.0);
        Rate calculated = 100.0 * swap->fairRate();
        Rate error = std::fabs(expected-calculated);
        if (error>tolerance)
            BOOST_FAIL("curve inconsistency:" << std::setprecision(10) <<
                        "\n swap length:     " << term <<
                        "\n quoted rate:     " << expected <<
                        "\n calculated rate: " << calculated <<
                        "\n error:           " << error <<
                        "\n tolerance:       " << tolerance);
    }
    // zero spread
    /*
    std::cout << "zero spread:" << std::endl;
    std::cout << "years date zero3m/% zero1d/% spread/bp" << std::endl;
    DayCounter dc = Actual365Fixed();
    for (Size i = 1; i <= 10; i++) {
        Date d = vars.today + i*Years;
        Rate zero1d = eoniaTS->zeroRate(d, dc, Continuous, Annual,false).rate();
        Rate zero3m = swapTS->zeroRate(d, dc, Continuous, Annual,false).rate();
        std::cout << std::setw(2) << i << "y  " << io::iso_date(d) << "  "
                  << std::setprecision(3)
                  << zero3m * 100.0 << " "
                  << zero1d * 100.0 << " "
                  << std::setprecision(1)
                  << (zero3m - zero1d) * 10000.0 << std::endl;
    }
    */
}
void OvernightIndexedSwapTest::testCachedValue () [static]
Definition at line 274 of file overnightindexedswap.cpp.
References QuantLib::Days, QuantLib::Settings::evaluationDate(), QuantLib::flatRate(), QuantLib::Singleton< Settings >::instance(), QL_FIXED, QuantLib::swap(), anonymous_namespace{gaussianquadratures.cpp}::tolerance, and QuantLib::Years.
Referenced by suite().
{
    BOOST_MESSAGE("Testing Eonia-swap calculation against cached value...");
    CommonVars vars;
    Settings::instance().evaluationDate() = vars.today;
    vars.settlement =
        vars.calendar.advance(vars.today,vars.settlementDays,Days);
    Real flat = 0.05;
    vars.eoniaTermStructure.linkTo(flatRate(vars.settlement,flat,Actual360()));
    Real fixedRate = exp(flat) - 1;
    shared_ptr<OvernightIndexedSwap> swap = vars.makeSwap(1*Years, fixedRate, 0.0);
    Real cachedNPV   = 0.001730450147;
    Real tolerance = 1.0e-11;
    if (std::fabs(swap->NPV()-cachedNPV) > tolerance)
        BOOST_ERROR("\nfailed to reproduce cached swap value:" <<
                    QL_FIXED << std::setprecision(12) <<
                    "\ncalculated: " << swap->NPV() <<
                    "\n  expected: " << cachedNPV <<
                    "\n tolerance:" << tolerance);
}
void OvernightIndexedSwapTest::testFairRate () [static]
Definition at line 215 of file overnightindexedswap.cpp.
References LENGTH, anonymous_namespace{swaption.cpp}::lengths, QuantLib::io::rate(), QuantLib::swap(), and QuantLib::Years.
Referenced by suite().
{
    BOOST_MESSAGE("Testing Eonia-swap calculation of fair fixed rate...");
    CommonVars vars;
    Period lengths[] = { 1*Years, 2*Years, 5*Years, 10*Years, 20*Years };
    Spread spreads[] = { -0.001, -0.01, 0.0, 0.01, 0.001 };
    for (Size i=0; i<LENGTH(lengths); i++) {
        for (Size j=0; j<LENGTH(spreads); j++) {
            shared_ptr<OvernightIndexedSwap> swap =
                vars.makeSwap(lengths[i],0.0,spreads[j]);
            swap = vars.makeSwap(lengths[i],swap->fairRate(),spreads[j]);
            if (std::fabs(swap->NPV()) > 1.0e-10) {
                BOOST_ERROR("recalculating with implied rate:\n"
                            << std::setprecision(2)
                            << "    length: " << lengths[i] << " \n"
                            << "    floating spread: "
                            << io::rate(spreads[j]) << "\n"
                            << "    swap value: " << swap->NPV());
            }
        }
    }
}
void OvernightIndexedSwapTest::testFairSpread () [static]
Definition at line 243 of file overnightindexedswap.cpp.
References LENGTH, anonymous_namespace{swaption.cpp}::lengths, QuantLib::io::rate(), QuantLib::swap(), and QuantLib::Years.
Referenced by suite().
{
    BOOST_MESSAGE("Testing Eonia-swap calculation of "
                  "fair floating spread...");
    CommonVars vars;
    Period lengths[] = { 1*Years, 2*Years, 5*Years, 10*Years, 20*Years };
    Rate rates[] = { 0.04, 0.05, 0.06, 0.07 };
    for (Size i=0; i<LENGTH(lengths); i++) {
        for (Size j=0; j<LENGTH(rates); j++) {
            shared_ptr<OvernightIndexedSwap> swap =
                vars.makeSwap(lengths[i], rates[j], 0.0);
            Spread fairSpread = swap->fairSpread();
            swap = vars.makeSwap(lengths[i], rates[j], fairSpread);
            if (std::fabs(swap->NPV()) > 1.0e-10) {
                BOOST_ERROR("\nrecalculating with implied spread:" <<
                            std::setprecision(2) <<
                            "\n     length: " << lengths[i] <<
                            "\n fixed rate: " << io::rate(rates[j]) <<
                            "\nfair spread: " << io::rate(fairSpread) <<
                            "\n swap value: " << swap->NPV());
            }
        }
    }
}
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/overnightindexedswap.hpp
/home/deriversatile/QuantLib/QuantLibQt/test-suite/overnightindexedswap.cpp