QuantLib: QuantLib::MakeMCEuropeanHestonEngine< RNG, S > Class Template Reference
QuantLib::MakeMCEuropeanHestonEngine< RNG, S > Class Template Reference
Monte Carlo Heston European engine factory.
#include <mceuropeanhestonengine.hpp>
Public Member Functions
MakeMCEuropeanHestonEngine (const boost::shared_ptr< HestonProcess > &)
MakeMCEuropeanHestonEngine & withSteps (Size steps)
MakeMCEuropeanHestonEngine & withStepsPerYear (Size steps)
MakeMCEuropeanHestonEngine & withSamples (Size samples)
MakeMCEuropeanHestonEngine & withAbsoluteTolerance (Real tolerance)
MakeMCEuropeanHestonEngine & withMaxSamples (Size samples)
MakeMCEuropeanHestonEngine & withSeed (BigNatural seed)
MakeMCEuropeanHestonEngine & withAntitheticVariate (bool b=true)
operator boost::shared_ptr< PricingEngine > () const
Private Attributes
boost::shared_ptr< HestonProcess > process_
bool antithetic_
Size steps_
Size stepsPerYear_
Size samples_
Size maxSamples_
Real tolerance_
BigNatural seed_
Detailed Description
template<class RNG = PseudoRandom, class S = Statistics>
class QuantLib::MakeMCEuropeanHestonEngine< RNG, S >
Monte Carlo Heston European engine factory.
Definition at line 59 of file mceuropeanhestonengine.hpp.
Constructor & Destructor Documentation
template<class RNG , class S > QuantLib::MakeMCEuropeanHestonEngine< RNG, S >::MakeMCEuropeanHestonEngine (const boost::shared_ptr< HestonProcess > & process) [inline]
Definition at line 133 of file mceuropeanhestonengine.hpp.
    : process_(process), antithetic_(false),
      steps_(Null<Size>()), stepsPerYear_(Null<Size>()),
      samples_(Null<Size>()), maxSamples_(Null<Size>()),
      tolerance_(Null<Real>()), seed_(0) {}
Member Function Documentation
template<class RNG , class S > QuantLib::MakeMCEuropeanHestonEngine< RNG, S >::operator boost::shared_ptr< PricingEngine > () const [inline]
Definition at line 203 of file mceuropeanhestonengine.hpp.
References QL_REQUIRE, and anonymous_namespace{marketmodel.cpp}::seed_.
{
        QL_REQUIRE(steps_ != Null<Size>() || stepsPerYear_ != Null<Size>(),
                   "number of steps not given");
        return boost::shared_ptr<PricingEngine>(
                 new MCEuropeanHestonEngine<RNG,S>(process_,
                                                   steps_,
                                                   stepsPerYear_,
                                                   antithetic_,
                                                   samples_, tolerance_,
                                                   maxSamples_,
                                                   seed_));
    }
template<class RNG , class S > MakeMCEuropeanHestonEngine< RNG, S > & QuantLib::MakeMCEuropeanHestonEngine< RNG, S >::withAbsoluteTolerance (Real tolerance) [inline]
Definition at line 169 of file mceuropeanhestonengine.hpp.
References QL_REQUIRE, and anonymous_namespace{gaussianquadratures.cpp}::tolerance.
Referenced by BatesModelTest::testAnalyticAndMcVsJumpDiffusion(), BatesModelTest::testAnalyticVsMCPricing(), and HestonModelTest::testKahlJaeckelCase().
{
        QL_REQUIRE(samples_ == Null<Size>(),
                   "number of samples already set");
        QL_REQUIRE(RNG::allowsErrorEstimate,
                   "chosen random generator policy "
                   "does not allow an error estimate");
        tolerance_ = tolerance;
        return *this;
    }
template<class RNG , class S > MakeMCEuropeanHestonEngine< RNG, S > & QuantLib::MakeMCEuropeanHestonEngine< RNG, S >::withAntitheticVariate (bool b = true) [inline]
Definition at line 195 of file mceuropeanhestonengine.hpp.
References anonymous_namespace{marketmodel.cpp}::b.
Referenced by BatesModelTest::testAnalyticAndMcVsJumpDiffusion(), BatesModelTest::testAnalyticVsMCPricing(), HestonModelTest::testKahlJaeckelCase(), and HestonModelTest::testMcVsCached().
{
        antithetic_ = b;
        return *this;
    }
template<class RNG , class S > MakeMCEuropeanHestonEngine< RNG, S > & QuantLib::MakeMCEuropeanHestonEngine< RNG, S >::withMaxSamples (Size samples) [inline]
Definition at line 181 of file mceuropeanhestonengine.hpp.
{
        maxSamples_ = samples;
        return *this;
    }
template<class RNG , class S > MakeMCEuropeanHestonEngine< RNG, S > & QuantLib::MakeMCEuropeanHestonEngine< RNG, S >::withSamples (Size samples) [inline]
Definition at line 160 of file mceuropeanhestonengine.hpp.
References QL_REQUIRE.
Referenced by HestonModelTest::testMcVsCached().
{
        QL_REQUIRE(tolerance_ == Null<Real>(),
                   "tolerance already set");
        samples_ = samples;
        return *this;
    }
template<class RNG , class S > MakeMCEuropeanHestonEngine< RNG, S > & QuantLib::MakeMCEuropeanHestonEngine< RNG, S >::withSeed (BigNatural seed) [inline]
Definition at line 188 of file mceuropeanhestonengine.hpp.
References anonymous_namespace{marketmodel.cpp}::seed_.
Referenced by BatesModelTest::testAnalyticAndMcVsJumpDiffusion(), BatesModelTest::testAnalyticVsMCPricing(), HestonModelTest::testKahlJaeckelCase(), and HestonModelTest::testMcVsCached().
{
        seed_ = seed;
        return *this;
    }
template<class RNG , class S > MakeMCEuropeanHestonEngine< RNG, S > & QuantLib::MakeMCEuropeanHestonEngine< RNG, S >::withSteps (Size steps) [inline]
Definition at line 142 of file mceuropeanhestonengine.hpp.
References QL_REQUIRE.
{
        QL_REQUIRE(stepsPerYear_ == Null<Size>(),
                   "number of steps per year already set");
        steps_ = steps;
        return *this;
    }
template<class RNG , class S > MakeMCEuropeanHestonEngine< RNG, S > & QuantLib::MakeMCEuropeanHestonEngine< RNG, S >::withStepsPerYear (Size steps) [inline]
Definition at line 151 of file mceuropeanhestonengine.hpp.
References QL_REQUIRE.
{
        QL_REQUIRE(steps_ == Null<Size>(),
                   "number of steps already set");
        stepsPerYear_ = steps;
        return *this;
    }
Member Data Documentation
template<class RNG = PseudoRandom, class S = Statistics> bool QuantLib::MakeMCEuropeanHestonEngine< RNG, S >::antithetic_ [private]
Definition at line 74 of file mceuropeanhestonengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> Size QuantLib::MakeMCEuropeanHestonEngine< RNG, S >::maxSamples_ [private]
Definition at line 75 of file mceuropeanhestonengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> boost::shared_ptr<HestonProcess> QuantLib::MakeMCEuropeanHestonEngine< RNG, S >::process_ [private]
Definition at line 73 of file mceuropeanhestonengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> Size QuantLib::MakeMCEuropeanHestonEngine< RNG, S >::samples_ [private]
Definition at line 75 of file mceuropeanhestonengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> BigNatural QuantLib::MakeMCEuropeanHestonEngine< RNG, S >::seed_ [private]
Definition at line 77 of file mceuropeanhestonengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> Size QuantLib::MakeMCEuropeanHestonEngine< RNG, S >::steps_ [private]
Definition at line 75 of file mceuropeanhestonengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> Size QuantLib::MakeMCEuropeanHestonEngine< RNG, S >::stepsPerYear_ [private]
Definition at line 75 of file mceuropeanhestonengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> Real QuantLib::MakeMCEuropeanHestonEngine< RNG, S >::tolerance_ [private]
Definition at line 76 of file mceuropeanhestonengine.hpp.
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/vanilla/mceuropeanhestonengine.hpp