QuantLib: QuantLib::CumulativeNormalDistribution Class Reference
QuantLib::CumulativeNormalDistribution Class Reference
Cumulative normal distribution function.
#include <normaldistribution.hpp>
Public Member Functions
CumulativeNormalDistribution (Real average=0.0, Real sigma=1.0)
Real operator() (Real x) const
Real derivative (Real x) const
Private Attributes
Real average_
Real sigma_
NormalDistribution gaussian_
ErrorFunction errorFunction_
Detailed Description
Cumulative normal distribution function.
Given x it provides an approximation to the integral of the gaussian normal distribution: formula here ...
For this implementation see M. Abramowitz and I. Stegun, Handbook of Mathematical Functions, Dover Publications, New York (1972)
Definition at line 68 of file normaldistribution.hpp.
Constructor & Destructor Documentation
QuantLib::CumulativeNormalDistribution::CumulativeNormalDistribution (Real average = 0.0, Real sigma = 1.0) [inline]
Definition at line 256 of file normaldistribution.hpp.
References QL_REQUIRE, and sigma_.
    : average_(average), sigma_(sigma) {
        QL_REQUIRE(sigma_>0.0,
                   "sigma must be greater than 0.0 ("
                   << sigma_ << " not allowed)");
    }
Member Function Documentation
Real QuantLib::CumulativeNormalDistribution::derivative (Real x) const [inline]
Definition at line 265 of file normaldistribution.hpp.
References average_, gaussian_, and sigma_.
Referenced by QuantLib::LogNormalFwdRateEulerConstrained::advanceStep(), QuantLib::AmericanPayoffAtExpiry::AmericanPayoffAtExpiry(), QuantLib::AmericanPayoffAtHit::AmericanPayoffAtHit(), QuantLib::bachelierBlackFormula(), QuantLib::blackFormulaStdDevDerivative(), QuantLib::AbcdCalibration::compute(), QuantLib::BaroneAdesiWhaleyApproximationEngine::criticalPrice(), QuantLib::BlackImpliedStdDevHelper::derivative(), QuantLib::BlackCalculator::initialize(), QuantLib::BlackDeltaCalculator::nD1(), QuantLib::BlackDeltaCalculator::nD2(), and DistributionTest::testNormal().
{
        Real xn = (x - average_) / sigma_;
        return gaussian_(xn) / sigma_;
    }
Real QuantLib::CumulativeNormalDistribution::operator() (Real x) const
Definition at line 28 of file normaldistribution.cpp.
References anonymous_namespace{marketmodel.cpp}::a, average_, errorFunction_, gaussian_, M_SQRT_2, QL_EPSILON, QL_MAX_REAL, and sigma_.
{
        //QL_REQUIRE(!(z >= average_ && 2.0*average_-z > average_),
        //           "not a real number. ");
        z = (z - average_) / sigma_;
        Real result = 0.5 * ( 1.0 + errorFunction_( z*M_SQRT_2 ) );
        if (result<=1e-8) { //todo: investigate the threshold level
            // Asymptotic expansion for very negative z following (26.2.12)
            // on page 408 in M. Abramowitz and A. Stegun,
            // Pocketbook of Mathematical Functions, ISBN 3-87144818-4.
            Real sum=1.0, zsqr=z*z, i=1.0, g=1.0, x, y,
                 a=QL_MAX_REAL, lasta;
            do {
                lasta=a;
                x = (4.0*i-3.0)/zsqr;
                y = x*((4.0*i-1)/zsqr);
                a = g*(x-y);
                sum -= a;
                g *= y;
                ++i;
                a = std::fabs(a);
            } while (lasta>a && a>=std::fabs(sum*QL_EPSILON));
            result = -gaussian_(z)/z*sum;
        }
        return result;
    }
Member Data Documentation
Real QuantLib::CumulativeNormalDistribution::average_ [private]
Definition at line 77 of file normaldistribution.hpp.
Referenced by derivative(), and operator()().
ErrorFunction QuantLib::CumulativeNormalDistribution::errorFunction_ [private]
Definition at line 79 of file normaldistribution.hpp.
Referenced by operator()().
NormalDistribution QuantLib::CumulativeNormalDistribution::gaussian_ [private]
Definition at line 78 of file normaldistribution.hpp.
Referenced by derivative(), and operator()().
Real QuantLib::CumulativeNormalDistribution::sigma_ [private]
Definition at line 77 of file normaldistribution.hpp.
Referenced by CumulativeNormalDistribution(), derivative(), and operator()().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/distributions/normaldistribution.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/math/distributions/normaldistribution.cpp