QuantLib: QuantLib::FwdPeriodAdapter Class Reference
QuantLib::FwdPeriodAdapter Class Reference
#include <fwdperiodadapter.hpp>
Public Member Functions
FwdPeriodAdapter (const boost::shared_ptr< MarketModel > &largeModel, Size period, Size offset, const std::vector< Spread > &newDisplacements_)
MarketModel interface
const std::vector< Rate > & initialRates () const
const std::vector< Spread > & displacements () const
const EvolutionDescription & evolution () const
Size numberOfRates () const
Size numberOfFactors () const
Size numberOfSteps () const
const Matrix & pseudoRoot (Size i) const
Private Attributes
EvolutionDescription evolution_
Size numberOfFactors_
Size numberOfRates_
Size numberOfSteps_
std::vector< Rate > initialRates_
std::vector< Matrix > pseudoRoots_
std::vector< Spread > displacements_
Detailed Description
Definition at line 31 of file fwdperiodadapter.hpp.
Constructor & Destructor Documentation
QuantLib::FwdPeriodAdapter::FwdPeriodAdapter (const boost::shared_ptr< MarketModel > & largeModel, Size period, Size offset, const std::vector< Spread > & newDisplacements_)
Definition at line 31 of file fwdperiodadapter.cpp.
References displacements_, evolution_, QuantLib::EvolutionDescription::evolutionTimes(), QuantLib::EvolutionDescription::firstAliveRate(), QuantLib::LMMCurveState::forwardRates(), initialRates_, QuantLib::CurveState::numberOfRates(), numberOfRates_, numberOfSteps_, pseudoRoots_, QL_REQUIRE, QuantLib::CurveState::rateTimes(), anonymous_namespace{marketmodel.cpp}::rateTimes, QuantLib::ForwardForwardMappings::RestrictCurveState(), QuantLib::LMMCurveState::setOnForwardRates(), and QuantLib::ForwardForwardMappings::YMatrix().
    :
      numberOfFactors_(largeModel->numberOfFactors()),
          numberOfRates_((largeModel->numberOfRates()-offset) / (period > 0 ? period : 1) ),
      numberOfSteps_(largeModel->numberOfSteps()),
      pseudoRoots_(numberOfSteps_, Matrix(numberOfRates_,
                                          numberOfFactors_)),
                                          displacements_(newDisplacements)
    {
        QL_REQUIRE( period >0, "period must  be greater than zero in fwdperiodadapter");
        QL_REQUIRE(period > offset, "period must be greater than offset in fwdperiodadapter");
        const std::vector<Spread>& largeDisplacements_ =
            largeModel->displacements();
        if (displacements_.size() == 1)
        {
            Real dis = displacements_[0];
            displacements_.resize(numberOfRates_);
            std::fill(displacements_.begin(), displacements_.end(), dis);
        }
        if (displacements_.size() ==0) // if not specified use average across rate
        {
            displacements_.reserve(numberOfRates_);
            Size m=0;
            Real sum=0.0;
            for (Size k=0; k < numberOfRates_; ++k)
            {
                for (Size l=0; l < period; ++l, ++m)
                    sum+= largeDisplacements_[m];
                displacements_.push_back(sum/period);
            }
        }
        QL_REQUIRE( displacements_.size() == numberOfRates_,"newDisplacements should be empty,1, or number of new rates in fwdperiodadapter");
        LMMCurveState largeCS(largeModel->evolution().rateTimes());
        largeCS.setOnForwardRates(largeModel->initialRates());
        LMMCurveState smallCS(
                ForwardForwardMappings::RestrictCurveState(largeCS,
                                    period, offset
                                        ));
        initialRates_ =smallCS.forwardRates();
        Real finalReset = smallCS.rateTimes()[smallCS.numberOfRates()-1];
        std::vector<Time> oldEvolutionTimes(largeModel->evolution().evolutionTimes());
        std::vector<Time> newEvolutionTimes;
        for (Size i =0; i < oldEvolutionTimes.size() && oldEvolutionTimes[i]<= finalReset; ++i)
            newEvolutionTimes.push_back(oldEvolutionTimes[i]);
        evolution_=EvolutionDescription(smallCS.rateTimes(),
                                        newEvolutionTimes);
        numberOfSteps_ = newEvolutionTimes.size();
        const std::vector<Time>& rateTimes =
            smallCS.rateTimes();
        // we must ensure we step through all rateTimes
        const std::vector<Time>& evolutionTimes =
            evolution_.evolutionTimes();
        std::set<Time> setTimes(evolutionTimes.begin(),evolutionTimes.end());
        for (Size i=0; i < rateTimes.size()-1; ++i)
            QL_REQUIRE(setTimes.find(rateTimes[i]) != setTimes.end(),
                        "every new rate time except last must be an evolution time in fwdperiod adapter");
        Matrix YMatrix =
            ForwardForwardMappings::YMatrix( largeCS,
                                                 largeDisplacements_,
                                                  displacements_,
                                                 period,
                                                 offset
                                                 );
        const std::vector<Size>& alive =
            evolution_.firstAliveRate();
        for (Size k = 0; k<numberOfSteps_; ++k) {
            pseudoRoots_[k]=YMatrix*largeModel->pseudoRoot(k);
            for (Size i=0; i<alive[k]; ++i)
                std::fill(pseudoRoots_[k].row_begin(i),
                          pseudoRoots_[k].row_end(i),
                          0.0);
        }
    }
Member Function Documentation
const std::vector< Spread > & QuantLib::FwdPeriodAdapter::displacements () const [inline, virtual]
Implements QuantLib::MarketModel.
Definition at line 67 of file fwdperiodadapter.hpp.
References displacements_.
{
        return displacements_;
    }
const EvolutionDescription & QuantLib::FwdPeriodAdapter::evolution () const [inline, virtual]
Implements QuantLib::MarketModel.
Definition at line 72 of file fwdperiodadapter.hpp.
References evolution_.
{
        return evolution_;
    }
const std::vector< Rate > & QuantLib::FwdPeriodAdapter::initialRates () const [inline, virtual]
Implements QuantLib::MarketModel.
Definition at line 62 of file fwdperiodadapter.hpp.
References initialRates_.
{
        return initialRates_;
    }
Size QuantLib::FwdPeriodAdapter::numberOfFactors () const [inline, virtual]
Implements QuantLib::MarketModel.
Definition at line 80 of file fwdperiodadapter.hpp.
References numberOfFactors_.
{
        return numberOfFactors_;
    }
Size QuantLib::FwdPeriodAdapter::numberOfRates () const [inline, virtual]
Implements QuantLib::MarketModel.
Definition at line 76 of file fwdperiodadapter.hpp.
References numberOfRates_.
{
        return numberOfRates_;
    }
Size QuantLib::FwdPeriodAdapter::numberOfSteps () const [inline, virtual]
Implements QuantLib::MarketModel.
Definition at line 84 of file fwdperiodadapter.hpp.
References numberOfSteps_.
{
        return numberOfSteps_;
    }
const Matrix & QuantLib::FwdPeriodAdapter::pseudoRoot (Size i) const [inline, virtual]
Implements QuantLib::MarketModel.
Definition at line 88 of file fwdperiodadapter.hpp.
References pseudoRoots_.
{
        return pseudoRoots_[i];
    }
Member Data Documentation
std::vector<Spread> QuantLib::FwdPeriodAdapter::displacements_ [private]
Definition at line 53 of file fwdperiodadapter.hpp.
Referenced by displacements(), and FwdPeriodAdapter().
EvolutionDescription QuantLib::FwdPeriodAdapter::evolution_ [private]
Definition at line 49 of file fwdperiodadapter.hpp.
Referenced by evolution(), and FwdPeriodAdapter().
std::vector<Rate> QuantLib::FwdPeriodAdapter::initialRates_ [private]
Definition at line 51 of file fwdperiodadapter.hpp.
Referenced by FwdPeriodAdapter(), and initialRates().
Size QuantLib::FwdPeriodAdapter::numberOfFactors_ [private]
Definition at line 50 of file fwdperiodadapter.hpp.
Referenced by numberOfFactors().
Size QuantLib::FwdPeriodAdapter::numberOfRates_ [private]
Definition at line 50 of file fwdperiodadapter.hpp.
Referenced by FwdPeriodAdapter(), and numberOfRates().
Size QuantLib::FwdPeriodAdapter::numberOfSteps_ [private]
Definition at line 50 of file fwdperiodadapter.hpp.
Referenced by FwdPeriodAdapter(), and numberOfSteps().
std::vector<Matrix> QuantLib::FwdPeriodAdapter::pseudoRoots_ [private]
Definition at line 52 of file fwdperiodadapter.hpp.
Referenced by FwdPeriodAdapter(), and pseudoRoot().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/models/fwdperiodadapter.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/models/fwdperiodadapter.cpp