QuantLib: MatricesTest Class Reference
MatricesTest Class Reference
#include <matrices.hpp>
Static Public Member Functions
static void testEigenvectors ()
static void testSqrt ()
static void testHighamSqrt ()
static void testSVD ()
static void testQRDecomposition ()
static void testQRSolve ()
static void testInverse ()
static void testDeterminant ()
static void testOrthogonalProjection ()
static
boost::unit_test_framework::test_suite * suite ()
Detailed Description
Definition at line 29 of file matrices.hpp.
Member Function Documentation
test_suite * MatricesTest::suite () [static]
Definition at line 473 of file matrices.cpp.
References QUANTLIB_TEST_CASE, testDeterminant(), testEigenvectors(), testHighamSqrt(), testInverse(), testOrthogonalProjection(), testQRDecomposition(), testQRSolve(), testSqrt(), and testSVD().
Referenced by init_unit_test_suite().
{
    test_suite* suite = BOOST_TEST_SUITE("Matrix tests");
    suite->add(QUANTLIB_TEST_CASE(&MatricesTest::testOrthogonalProjection));
    suite->add(QUANTLIB_TEST_CASE(&MatricesTest::testEigenvectors));
    suite->add(QUANTLIB_TEST_CASE(&MatricesTest::testSqrt));
    suite->add(QUANTLIB_TEST_CASE(&MatricesTest::testSVD));
    suite->add(QUANTLIB_TEST_CASE(&MatricesTest::testHighamSqrt));
    suite->add(QUANTLIB_TEST_CASE(&MatricesTest::testQRDecomposition));
    suite->add(QUANTLIB_TEST_CASE(&MatricesTest::testQRSolve));
    #if !defined(QL_NO_UBLAS_SUPPORT)
    suite->add(QUANTLIB_TEST_CASE(&MatricesTest::testInverse));
    suite->add(QUANTLIB_TEST_CASE(&MatricesTest::testDeterminant));
    #endif
    return suite;
}
void MatricesTest::testDeterminant () [static]
Definition at line 352 of file matrices.cpp.
References anonymous_namespace{marketmodel.cpp}::a, anonymous_namespace{marketmodel.cpp}::b, QuantLib::Matrix::begin(), anonymous_namespace{marketmodel.cpp}::c, anonymous_namespace{marketmodel.cpp}::d, QuantLib::determinant(), QuantLib::Matrix::end(), anonymous_namespace{interpolations.cpp}::f(), anonymous_namespace{matrices.cpp}::I, LENGTH, anonymous_namespace{matrices.cpp}::M1, anonymous_namespace{matrices.cpp}::M2, anonymous_namespace{matrices.cpp}::M5, anonymous_namespace{matrices.cpp}::M6, QuantLib::MersenneTwisterUniformRng::next(), QuantLib::Matrix::row_begin(), QuantLib::Matrix::row_end(), anonymous_namespace{inflationvolatility.cpp}::setup(), and QuantLib::Sample< T >::value.
Referenced by suite().
{
    BOOST_MESSAGE("Testing LU determinant calculation...");
    setup();
    Real tol = 1e-10;
    Matrix testMatrices[] = {M1, M2, M5, M6, I};
    // expected results calculated with octave
    Real expected[] = { 0.044, -0.012, 5.0, 5.7621e-11, 1.0};
    for (Size j=0; j<LENGTH(testMatrices); ++j) {
        const Real calculated = determinant(testMatrices[j]);
        if (std::fabs(expected[j] - calculated) > tol)
            BOOST_FAIL("determinant calculation failed "
                       << "\n matrix     :\n" << testMatrices[j]
                       << "\n calculated : " << calculated
                       << "\n expected   : " << expected[j]);
    }
    MersenneTwisterUniformRng rng(1234);
    for (Size j=0; j<100; ++j) {
        Matrix m(3, 3, 0.0);
        for (Matrix::iterator iter = m.begin(); iter != m.end(); ++iter)
            *iter = rng.next().value;
        if (!(j%3)) {
            // every third matrix is a singular matrix
            Size row = Size(3*rng.next().value);
            std::fill(m.row_begin(row), m.row_end(row), 0.0);
        }
        Real a=m[0][0];
        Real b=m[0][1];
        Real c=m[0][2];
        Real d=m[1][0];
        Real e=m[1][1];
        Real f=m[1][2];
        Real g=m[2][0];
        Real h=m[2][1];
        Real i=m[2][2];
        const Real expected = a*e*i+b*f*g+c*d*h-(g*e*c+h*f*a+i*d*b);
        const Real calculated = determinant(m);
        if (std::fabs(expected-calculated) > tol)
            BOOST_FAIL("determinant calculation failed "
                       << "\n matrix     :\n" << m
                       << "\n calculated : " << calculated
                       << "\n expected   : " << expected);
    }
}
void MatricesTest::testEigenvectors () [static]
Definition at line 101 of file matrices.cpp.
References anonymous_namespace{marketmodel.cpp}::a, anonymous_namespace{marketmodel.cpp}::b, QuantLib::SymmetricSchurDecomposition::eigenvalues(), QuantLib::SymmetricSchurDecomposition::eigenvectors(), anonymous_namespace{matrices.cpp}::I, LENGTH, anonymous_namespace{matrices.cpp}::M1, anonymous_namespace{matrices.cpp}::M2, anonymous_namespace{matrices.cpp}::N, QuantLib::norm(), QL_MAX_REAL, anonymous_namespace{inflationvolatility.cpp}::setup(), QuantLib::transpose(), and anonymous_namespace{perturbativebarrieroptionengine.cpp}::v().
Referenced by suite().
{
    BOOST_MESSAGE("Testing eigenvalues and eigenvectors calculation...");
    setup();
    Matrix testMatrices[] = { M1, M2 };
    for (Size k=0; k<LENGTH(testMatrices); k++) {
        Matrix& M = testMatrices[k];
        SymmetricSchurDecomposition dec(M);
        Array eigenValues = dec.eigenvalues();
        Matrix eigenVectors = dec.eigenvectors();
        Real minHolder = QL_MAX_REAL;
        for (Size i=0; i<N; i++) {
            Array v(N);
            for (Size j=0; j<N; j++)
                v[j] = eigenVectors[j][i];
            // check definition
            Array a = M*v;
            Array b = eigenValues[i]*v;
            if (norm(a-b) > 1.0e-15)
                BOOST_FAIL("Eigenvector definition not satisfied");
            // check decreasing ordering
            if (eigenValues[i] >= minHolder) {
                BOOST_FAIL("Eigenvalues not ordered: " << eigenValues);
            } else
                minHolder = eigenValues[i];
        }
        // check normalization
        Matrix m = eigenVectors * transpose(eigenVectors);
        if (norm(m-I) > 1.0e-15)
            BOOST_FAIL("Eigenvector not normalized");
    }
}
void MatricesTest::testHighamSqrt () [static]
Definition at line 160 of file matrices.cpp.
References QuantLib::SalvagingAlgorithm::Higham, anonymous_namespace{matrices.cpp}::M5, anonymous_namespace{matrices.cpp}::M6, QuantLib::SalvagingAlgorithm::None, QuantLib::norm(), QuantLib::pseudoSqrt(), anonymous_namespace{inflationvolatility.cpp}::setup(), and anonymous_namespace{gaussianquadratures.cpp}::tolerance.
Referenced by suite().
{
    BOOST_MESSAGE("Testing Higham matricial square root...");
    setup();
    Matrix tempSqrt = pseudoSqrt(M5, SalvagingAlgorithm::Higham);
    Matrix ansSqrt = pseudoSqrt(M6, SalvagingAlgorithm::None);
    Real error = norm(ansSqrt - tempSqrt);
    Real tolerance = 1.0e-4;
    if (error>tolerance) {
        BOOST_FAIL("Higham matrix correction failed\n"
                   << "original matrix:\n" << M5
                   << "pseudoSqrt:\n" << tempSqrt
                   << "should be:\n" << ansSqrt
                   << "\nerror:     " << error
                   << "\ntolerance: " << tolerance);
    }
}
void MatricesTest::testInverse () [static]
Definition at line 323 of file matrices.cpp.
References anonymous_namespace{matrices.cpp}::I, QuantLib::inverse(), LENGTH, anonymous_namespace{matrices.cpp}::M1, anonymous_namespace{matrices.cpp}::M2, anonymous_namespace{matrices.cpp}::M5, QuantLib::norm(), and anonymous_namespace{inflationvolatility.cpp}::setup().
Referenced by suite().
{
    BOOST_MESSAGE("Testing LU inverse calculation...");
    setup();
    Real tol = 1.0e-12;
    Matrix testMatrices[] = { M1, M2, I, M5 };
    for (Size j = 0; j < LENGTH(testMatrices); j++) {
        const Matrix& A = testMatrices[j];
        const Matrix invA = inverse(A);
        const Matrix I1 = invA*A;
        const Matrix I2 = A*invA;
        Matrix eins(A.rows(), A.rows(), 0.0);
        for (Size i=0; i < A.rows(); ++i) eins[i][i] = 1.0;
        if (norm(I1 - eins) > tol)
            BOOST_FAIL("inverse(A)*A does not recover unit matrix (norm = "
                       << norm(I1-eins) << ")");
        if (norm(I2 - eins) > tol)
            BOOST_FAIL("A*inverse(A) does not recover unit matrix (norm = "
                       << norm(I1-eins) << ")");
    }
}
void MatricesTest::testOrthogonalProjection () [static]
Definition at line 405 of file matrices.cpp.
References QuantLib::OrthogonalProjections::GetVector(), QuantLib::MersenneTwisterUniformRng::next(), anonymous_namespace{solvers.cpp}::test(), anonymous_namespace{gaussianquadratures.cpp}::tolerance, QuantLib::OrthogonalProjections::validVectors(), and QuantLib::Sample< T >::value.
Referenced by suite().
{
    BOOST_MESSAGE("Testing orthogonal projections...");
    Size dimension = 1000;
    Size numberVectors = 50;
    Real multiplier = 100;
    Real tolerance = 1e-6;
    unsigned long seed = 1;
    Real errorAcceptable = 1E-11;
    Matrix test(numberVectors,dimension);
    MersenneTwisterUniformRng rng(seed);
    for (Size i=0; i < numberVectors; ++i)
        for (Size j=0; j < dimension; ++j)
            test[i][j] = rng.next().value;
    OrthogonalProjections projector(test,
                                    multiplier,
                                    tolerance  );
    Size numberFailures =0;
    Size failuresTwo=0;
    for (Size i=0; i < numberVectors; ++i)
    {
        // check output vector i is orthogonal to all other vectors
        if (projector.validVectors()[i])
        {
            for (Size j=0; j < numberVectors; ++j)
                  if (projector.validVectors()[j] && i != j)
                  {
                      Real dotProduct=0.0;
                      for (Size k=0; k < dimension; ++k)
                          dotProduct += test[j][k]*projector.GetVector(i)[k];
                      if (fabs(dotProduct) > errorAcceptable)
                          ++numberFailures;
                  }
           Real innerProductWithOriginal =0.0;
           Real normSq =0.0;
           for (Size j=0; j < dimension; ++j)
           {
                innerProductWithOriginal +=   projector.GetVector(i)[j]*test[i][j];
                normSq += test[i][j]*test[i][j];
           }
           if (fabs(innerProductWithOriginal-normSq) > errorAcceptable)
               ++failuresTwo;
        }
    }
    if (numberFailures > 0 || failuresTwo >0)
        BOOST_FAIL("OrthogonalProjections test failed with " << numberFailures << " failures  of orthogonality and "
                    << failuresTwo << " failures of projection size.");
}
void MatricesTest::testQRDecomposition () [static]
Definition at line 224 of file matrices.cpp.
References QuantLib::Matrix::columns(), anonymous_namespace{matrices.cpp}::I, LENGTH, anonymous_namespace{matrices.cpp}::M1, anonymous_namespace{matrices.cpp}::M2, anonymous_namespace{matrices.cpp}::M3, anonymous_namespace{matrices.cpp}::M4, anonymous_namespace{matrices.cpp}::M5, QuantLib::norm(), QuantLib::qrDecomposition(), anonymous_namespace{inflationvolatility.cpp}::setup(), and QuantLib::transpose().
Referenced by suite().
{
    BOOST_MESSAGE("Testing QR decomposition...");
    setup();
    Real tol = 1.0e-12;
    Matrix testMatrices[] = { M1, M2, I,
                              M3, transpose(M3), M4, transpose(M4), M5 };
    for (Size j = 0; j < LENGTH(testMatrices); j++) {
        Matrix Q, R;
        bool pivot = true;
        const Matrix& A = testMatrices[j];
        const std::vector<Size> ipvt = qrDecomposition(A, Q, R, pivot);
        Matrix P(A.columns(), A.columns(), 0.0);
        // reverse column pivoting
        for (Size i=0; i < P.columns(); ++i) {
            P[ipvt[i]][i] = 1.0;
        }
        if (norm(Q*R - A*P) > tol)
            BOOST_FAIL("Q*R does not match matrix A*P (norm = "
                       << norm(Q*R-A*P) << ")");
        pivot = false;
        qrDecomposition(A, Q, R, pivot);
        if (norm(Q*R - A) > tol)
            BOOST_FAIL("Q*R does not match matrix A (norm = "
                       << norm(Q*R-A) << ")");
    }
}
void MatricesTest::testQRSolve () [static]
Definition at line 260 of file matrices.cpp.
References anonymous_namespace{marketmodel.cpp}::b, QuantLib::Matrix::column_begin(), QuantLib::Matrix::column_end(), QuantLib::Matrix::columns(), anonymous_namespace{matrices.cpp}::I, QuantLib::dsd::inner_product(), LENGTH, anonymous_namespace{matrices.cpp}::M1, anonymous_namespace{matrices.cpp}::M2, anonymous_namespace{matrices.cpp}::M3, anonymous_namespace{matrices.cpp}::M4, anonymous_namespace{matrices.cpp}::M5, anonymous_namespace{matrices.cpp}::M7, QuantLib::MersenneTwisterUniformRng::next(), QuantLib::norm(), QL_EPSILON, QuantLib::qrSolve(), QuantLib::Matrix::rows(), anonymous_namespace{inflationvolatility.cpp}::setup(), QuantLib::SVD::singularValues(), QuantLib::transpose(), QuantLib::SVD::U(), QuantLib::SVD::V(), and QuantLib::Sample< T >::value.
Referenced by suite().
{
    BOOST_MESSAGE("Testing QR solve...");
    setup();
    Real tol = 1.0e-12;
    MersenneTwisterUniformRng rng(1234);
    Matrix bigM(50, 100, 0.0);
    for (Size i=0; i < std::min(bigM.rows(), bigM.columns()); ++i) {
        bigM[i][i] = i+1.0;
    }
    Matrix testMatrices[] = { M1, M2, M3, transpose(M3),
                              M4, transpose(M4), M5, I, M7, bigM, transpose(bigM) };
    for (Size j = 0; j < LENGTH(testMatrices); j++) {
        const Matrix& A = testMatrices[j];
        Array b(A.rows());
        for (Size k=0; k < 10; ++k) {
            for (Array::iterator iter = b.begin(); iter != b.end(); ++iter) {
                *iter = rng.next().value;
            }
            const Array x = qrSolve(A, b, true);
            if (A.columns() >= A.rows()) {
                if (norm(A*x - b) > tol)
                    BOOST_FAIL("A*x does not match vector b (norm = "
                               << norm(A*x - b) << ")");
            }
            else {
                // use the SVD to calculate the reference values
                const Size n = A.columns();
                Array xr(n, 0.0);
                SVD svd(A);
                const Matrix& V = svd.V();
                const Matrix& U = svd.U();
                const Array&  w = svd.singularValues();
                const Real threshold = n*QL_EPSILON;
                for (Size i=0; i<n; ++i) {
                    if (w[i] > threshold) {
                        const Real u = std::inner_product(U.column_begin(i),
                                                          U.column_end(i),
                                                          b.begin(), 0.0)/w[i];
                        for (Size j=0; j<n; ++j) {
                            xr[j]  +=u*V[j][i];
                        }
                    }
                }
                if (norm(xr-x) > tol) {
                    BOOST_FAIL("least square solution does not match (norm = "
                               << norm(x - xr) << ")");
                }
            }
        }
    }
}
void MatricesTest::testSqrt () [static]
Definition at line 140 of file matrices.cpp.
References anonymous_namespace{matrices.cpp}::M1, QuantLib::SalvagingAlgorithm::None, QuantLib::norm(), QuantLib::pseudoSqrt(), anonymous_namespace{inflationvolatility.cpp}::setup(), anonymous_namespace{gaussianquadratures.cpp}::tolerance, and QuantLib::transpose().
Referenced by suite().
{
    BOOST_MESSAGE("Testing matricial square root...");
    setup();
    Matrix m = pseudoSqrt(M1, SalvagingAlgorithm::None);
    Matrix temp = m*transpose(m);
    Real error = norm(temp - M1);
    Real tolerance = 1.0e-12;
    if (error>tolerance) {
        BOOST_FAIL("Matrix square root calculation failed\n"
                   << "original matrix:\n" << M1
                   << "pseudoSqrt:\n" << m
                   << "pseudoSqrt*pseudoSqrt:\n" << temp
                   << "\nerror:     " << error
                   << "\ntolerance: " << tolerance);
    }
}
void MatricesTest::testSVD () [static]
Definition at line 179 of file matrices.cpp.
References anonymous_namespace{matrices.cpp}::I, LENGTH, anonymous_namespace{matrices.cpp}::M1, anonymous_namespace{matrices.cpp}::M2, anonymous_namespace{matrices.cpp}::M3, anonymous_namespace{matrices.cpp}::M4, QuantLib::norm(), QuantLib::Matrix::rows(), QuantLib::SVD::S(), anonymous_namespace{inflationvolatility.cpp}::setup(), QuantLib::SVD::singularValues(), QuantLib::transpose(), QuantLib::SVD::U(), and QuantLib::SVD::V().
Referenced by suite().
{
    BOOST_MESSAGE("Testing singular value decomposition...");
    setup();
    Real tol = 1.0e-12;
    Matrix testMatrices[] = { M1, M2, M3, M4 };
    for (Size j = 0; j < LENGTH(testMatrices); j++) {
        // m >= n required (rows >= columns)
        Matrix& A = testMatrices[j];
        SVD svd(A);
        // U is m x n
        Matrix U = svd.U();
        // s is n long
        Array s = svd.singularValues();
        // S is n x n
        Matrix S = svd.S();
        // V is n x n
        Matrix V = svd.V();
        for (Size i=0; i < S.rows(); i++) {
            if (S[i][i] != s[i])
                BOOST_FAIL("S not consistent with s");
        }
        // tests
        Matrix U_Utranspose = transpose(U)*U;
        if (norm(U_Utranspose-I) > tol)
            BOOST_FAIL("U not orthogonal (norm of U^T*U-I = "
                       << norm(U_Utranspose-I) << ")");
        Matrix V_Vtranspose = transpose(V)*V;
        if (norm(V_Vtranspose-I) > tol)
            BOOST_FAIL("V not orthogonal (norm of V^T*V-I = "
                       << norm(V_Vtranspose-I) << ")");
        Matrix A_reconstructed = U * S * transpose(V);
        if (norm(A_reconstructed-A) > tol)
            BOOST_FAIL("Product does not recover A: (norm of U*S*V^T-A = "
                       << norm(A_reconstructed-A) << ")");
    }
}
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/matrices.hpp
/home/deriversatile/QuantLib/QuantLibQt/test-suite/matrices.cpp