QuantLib: QuantLib::AnalyticSimpleChooserEngine Class Reference
QuantLib::AnalyticSimpleChooserEngine Class Reference
Pricing engine for European Simple Chooser option.
#include <analyticsimplechooserengine.hpp>
Public Member Functions
AnalyticSimpleChooserEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > &process)
void calculate () const
Private Attributes
boost::shared_ptr
< GeneralizedBlackScholesProcess > process_
Detailed Description
Pricing engine for European Simple Chooser option.
This class implements a Simple Chooser Option option, with European exercise.
Definition at line 36 of file analyticsimplechooserengine.hpp.
Constructor & Destructor Documentation
QuantLib::AnalyticSimpleChooserEngine::AnalyticSimpleChooserEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > & process)
Definition at line 27 of file analyticsimplechooserengine.cpp.
References process_, and QuantLib::Observer::registerWith().
    : process_(process) {
        registerWith(process_);
    }
Member Function Documentation
void QuantLib::AnalyticSimpleChooserEngine::calculate () const [virtual]
Implements QuantLib::PricingEngine.
Definition at line 33 of file analyticsimplechooserengine.cpp.
References QuantLib::GenericEngine< SimpleChooserOption::arguments, SimpleChooserOption::results >::arguments_, QuantLib::SimpleChooserOption::arguments::choosingDate, QuantLib::Continuous, anonymous_namespace{marketmodel.cpp}::d, QuantLib::Settings::evaluationDate(), anonymous_namespace{interpolations.cpp}::f(), QuantLib::Singleton< Settings >::instance(), QuantLib::NoFrequency, process_, QL_REQUIRE, QuantLib::GenericEngine< SimpleChooserOption::arguments, SimpleChooserOption::results >::results_, QuantLib::Instrument::results::value, QuantLib::io::volatility(), and QuantLib::DayCounter::yearFraction().
{
        Date today = Settings::instance().evaluationDate();
        DayCounter rfdc  = process_->riskFreeRate()->dayCounter();
        DayCounter divdc = process_->dividendYield()->dayCounter();
        DayCounter voldc = process_->blackVolatility()->dayCounter();
        QL_REQUIRE(rfdc==divdc,
                   "Risk-free rate and dividend yield must"
                   "have the same day counter");
        QL_REQUIRE(rfdc==voldc,
                   "Risk-free rate and volatility must"
                   "have the same day counter");
        Real spot = process_->stateVariable()->value();
        boost::shared_ptr<StrikedTypePayoff> payoff =
            boost::dynamic_pointer_cast<StrikedTypePayoff>(arguments_.payoff);
        QL_REQUIRE(payoff, "non-plain payoff given");
        Real strike = payoff->strike();
        Volatility volatility = process_->blackVolatility()->blackVol(
                                                arguments_.exercise->lastDate(),
                                                strike);
        Date maturity = arguments_.exercise->lastDate();
        Real timeToMaturity = rfdc.yearFraction(today,maturity);
        Real timeToChoosing = rfdc.yearFraction(today,arguments_.choosingDate);
        Rate dividendRate =
            process_->dividendYield()->zeroRate(maturity, divdc,
                                                Continuous, NoFrequency);
        Rate riskFreeRate =
            process_->riskFreeRate()->zeroRate(maturity, rfdc,
                                               Continuous, NoFrequency);
        QL_REQUIRE(spot > 0.0, "negative or null spot value");
        QL_REQUIRE(strike > 0.0, "negative or null strike value");
        QL_REQUIRE(volatility > 0.0,
                   "negative or null volatility");
        QL_REQUIRE(timeToChoosing > 0.0,
                   "choosing date earlier than or equal to evaluation date");
        Real d = (std::log(spot/strike)
            + ((riskFreeRate-dividendRate) + volatility*volatility*0.5)*timeToMaturity)
            /(volatility*std::sqrt(timeToMaturity));
        Real y = (std::log(spot/strike) + (riskFreeRate-dividendRate)*timeToMaturity
            + (volatility*volatility*timeToChoosing/2))
            /(volatility*std::sqrt(timeToChoosing));
        CumulativeNormalDistribution f;
        results_.value = spot*std::exp(-dividendRate*timeToMaturity)*f(d)
            - strike*std::exp(-riskFreeRate*timeToMaturity)
            *f(d-volatility*std::sqrt(timeToMaturity))
            -spot*std::exp(-dividendRate*timeToMaturity)*f(-y)
            +strike*std::exp(-riskFreeRate*timeToMaturity)
            *f(-y+volatility*std::sqrt(timeToChoosing));
     }
Member Data Documentation
boost::shared_ptr<GeneralizedBlackScholesProcess> QuantLib::AnalyticSimpleChooserEngine::process_ [private]
Definition at line 42 of file analyticsimplechooserengine.hpp.
Referenced by AnalyticSimpleChooserEngine(), and calculate().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/exoticoptions/analyticsimplechooserengine.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/exoticoptions/analyticsimplechooserengine.cpp