QuantLib: QuantLib::InterestRate Class Reference
QuantLib::InterestRate Class Reference
Concrete interest rate class.
#include <interestrate.hpp>
Public Member Functions
constructors
InterestRate ()
Default constructor returning a null interest rate.
InterestRate (Rate r, const DayCounter &dc, Compounding comp, Frequency freq)
Standard constructor.
conversions
operator Rate () const
inspectors
Rate rate () const
const DayCounter & dayCounter () const
Compounding compounding () const
Frequency frequency () const
discount/compound factor calculations
DiscountFactor discountFactor (Time t) const
discount factor implied by the rate compounded at time t.
DiscountFactor discountFactor (const Date &d1, const Date &d2, const Date &refStart=Date(), const Date &refEnd=Date()) const
discount factor implied by the rate compounded between two dates
Real compoundFactor (Time t) const
compound factor implied by the rate compounded at time t.
Real compoundFactor (const Date &d1, const Date &d2, const Date &refStart=Date(), const Date &refEnd=Date()) const
compound factor implied by the rate compounded between two dates
equivalent rate calculations
InterestRate equivalentRate (Compounding comp, Frequency freq, Time t) const
equivalent interest rate for a compounding period t.
InterestRate equivalentRate (const DayCounter &resultDC, Compounding comp, Frequency freq, Date d1, Date d2, const Date &refStart=Date(), const Date &refEnd=Date()) const
equivalent rate for a compounding period between two dates
Static Public Member Functions
implied rate calculations
static InterestRate impliedRate (Real compound, const DayCounter &resultDC, Compounding comp, Frequency freq, Time t)
implied interest rate for a given compound factor at a given time.
static InterestRate impliedRate (Real compound, const DayCounter &resultDC, Compounding comp, Frequency freq, const Date &d1, const Date &d2, const Date &refStart=Date(), const Date &refEnd=Date())
implied rate for a given compound factor between two dates.
Private Attributes
Rate r_
DayCounter dc_
Compounding comp_
bool freqMakesSense_
Real freq_
Related Functions
(Note that these are not member functions.)
std::ostream & operator<< (std::ostream &, const InterestRate &)
Detailed Description
Concrete interest rate class.
This class encapsulate the interest rate compounding algebra. It manages day-counting conventions, compounding conventions, conversion between different conventions, discount/compound factor calculations, and implied/equivalent rate calculations.
Test:
Converted rates are checked against known good results
Definition at line 40 of file interestrate.hpp.
Constructor & Destructor Documentation
QuantLib::InterestRate::InterestRate ()
Default constructor returning a null interest rate.
Definition at line 29 of file interestrate.cpp.
Referenced by impliedRate().
    : r_(Null<Real>()) {}
QuantLib::InterestRate::InterestRate (Rate r, const DayCounter & dc, Compounding comp, Frequency freq)
Standard constructor.
Definition at line 32 of file interestrate.cpp.
References comp_, QuantLib::Compounded, freq_, freqMakesSense_, QuantLib::NoFrequency, QuantLib::Once, QL_REQUIRE, and QuantLib::SimpleThenCompounded.
    : r_(r), dc_(dc), comp_(comp), freqMakesSense_(false) {
        if (comp_==Compounded || comp_==SimpleThenCompounded) {
            freqMakesSense_ = true;
            QL_REQUIRE(freq!=Once && freq!=NoFrequency,
                       "frequency not allowed for this interest rate");
            freq_ = Real(freq);
        }
    }
Member Function Documentation
Real QuantLib::InterestRate::compoundFactor (Time t) const
compound factor implied by the rate compounded at time t.
returns the compound (a.k.a capitalization) factor implied by the rate compounded at time t.
Warning:
Time must be measured using InterestRate's own day counter.
Definition at line 46 of file interestrate.cpp.
References comp_, QuantLib::Compounded, QuantLib::Continuous, freq_, QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow(), QL_FAIL, QL_REQUIRE, r_, QuantLib::Simple, QuantLib::SimpleThenCompounded, and anonymous_namespace{quantlibbenchmark.cpp}::t.
Referenced by QuantLib::FixedRateCoupon::accruedAmount(), QuantLib::FixedRateCoupon::amount(), compoundFactor(), discountFactor(), equivalentRate(), QuantLib::ForwardRateAgreement::ForwardRateAgreement(), QuantLib::ForwardRateAgreement::spotValue(), and InterestRateTest::testConversions().
{
        QL_REQUIRE(t>=0.0, "negative time not allowed");
        QL_REQUIRE(r_ != Null<Rate>(), "null interest rate");
        switch (comp_) {
          case Simple:
            return 1.0 + r_*t;
          case Compounded:
            return std::pow(1.0+r_/freq_, freq_*t);
          case Continuous:
            return std::exp(r_*t);
          case SimpleThenCompounded:
            if (t<=1.0/Real(freq_))
                return 1.0 + r_*t;
            else
                return std::pow(1.0+r_/freq_, freq_*t);
          default:
            QL_FAIL("unknown compounding convention");
        }
    }
Real QuantLib::InterestRate::compoundFactor (const Date & d1, const Date & d2, const Date & refStart = Date(), const Date & refEnd = Date()) const [inline]
compound factor implied by the rate compounded between two dates
returns the compound (a.k.a capitalization) factor implied by the rate compounded between two dates.
Definition at line 101 of file interestrate.hpp.
References compoundFactor(), dc_, QL_REQUIRE, anonymous_namespace{quantlibbenchmark.cpp}::t, and QuantLib::DayCounter::yearFraction().
{
            QL_REQUIRE(d2>=d1,
                       "d1 (" << d1 << ") "
                       "later than d2 (" << d2 << ")");
            Time t = dc_.yearFraction(d1, d2, refStart, refEnd);
            return compoundFactor(t);
        }
Compounding QuantLib::InterestRate::compounding () const [inline]
Definition at line 60 of file interestrate.hpp.
References comp_.
Referenced by QuantLib::CashFlows::bps(), QuantLib::CashFlows::convexity(), QuantLib::anonymous_namespace{cashflows.cpp}::macaulayDuration(), QuantLib::anonymous_namespace{cashflows.cpp}::modifiedDuration(), QuantLib::FixedRateLeg::operator Leg(), QuantLib::operator<<(), BondTest::testBrazilianCached(), InterestRateTest::testConversions(), QuantLib::PiecewiseZeroSpreadedTermStructure::zeroYieldImpl(), and QuantLib::ZeroSpreadedTermStructure::zeroYieldImpl().
{ return comp_; }
const DayCounter& QuantLib::InterestRate::dayCounter () const [inline]
Definition at line 59 of file interestrate.hpp.
References dc_.
Referenced by QuantLib::CashFlows::bps(), QuantLib::CashFlows::convexity(), QuantLib::FixedRateCoupon::dayCounter(), QuantLib::anonymous_namespace{cashflows.cpp}::modifiedDuration(), QuantLib::FixedRateLeg::operator Leg(), QuantLib::operator<<(), QuantLib::anonymous_namespace{cashflows.cpp}::simpleDuration(), BondTest::testBrazilianCached(), InterestRateTest::testConversions(), QuantLib::PiecewiseZeroSpreadedTermStructure::zeroYieldImpl(), and QuantLib::ZeroSpreadedTermStructure::zeroYieldImpl().
{ return dc_; }
DiscountFactor QuantLib::InterestRate::discountFactor (Time t) const [inline]
discount factor implied by the rate compounded at time t.
Warning:
Time must be measured using InterestRate's own day counter.
Definition at line 72 of file interestrate.hpp.
References compoundFactor().
Referenced by QuantLib::CashFlows::convexity(), discountFactor(), QuantLib::FlatForward::discountImpl(), QuantLib::anonymous_namespace{cashflows.cpp}::modifiedDuration(), QuantLib::CashFlows::npv(), QuantLib::anonymous_namespace{cashflows.cpp}::simpleDuration(), and InterestRateTest::testConversions().
{
            return 1.0/compoundFactor(t);
        }
DiscountFactor QuantLib::InterestRate::discountFactor (const Date & d1, const Date & d2, const Date & refStart = Date(), const Date & refEnd = Date()) const [inline]
discount factor implied by the rate compounded between two dates
Definition at line 77 of file interestrate.hpp.
References dc_, discountFactor(), QL_REQUIRE, anonymous_namespace{quantlibbenchmark.cpp}::t, and QuantLib::DayCounter::yearFraction().
{
            QL_REQUIRE(d2>=d1,
                       "d1 (" << d1 << ") "
                       "later than d2 (" << d2 << ")");
            Time t = dc_.yearFraction(d1, d2, refStart, refEnd);
            return discountFactor(t);
        }
InterestRate QuantLib::InterestRate::equivalentRate (Compounding comp, Frequency freq, Time t) const [inline]
equivalent interest rate for a compounding period t.
The resulting InterestRate shares the same implicit day-counting rule of the original InterestRate instance.
Warning:
Time must be measured using the InterestRate's own day counter.
Definition at line 158 of file interestrate.hpp.
References compoundFactor(), dc_, and impliedRate().
Referenced by InterestRateTest::testConversions(), QuantLib::PiecewiseZeroSpreadedTermStructure::zeroYieldImpl(), and QuantLib::ZeroSpreadedTermStructure::zeroYieldImpl().
{
            return impliedRate(compoundFactor(t), dc_, comp, freq, t);
        }
InterestRate QuantLib::InterestRate::equivalentRate (const DayCounter & resultDC, Compounding comp, Frequency freq, Date d1, Date d2, const Date & refStart = Date(), const Date & refEnd = Date()) const [inline]
equivalent rate for a compounding period between two dates
The resulting rate is calculated taking the required day-counting rule into account.
Definition at line 168 of file interestrate.hpp.
References compoundFactor(), dc_, impliedRate(), QL_REQUIRE, and QuantLib::DayCounter::yearFraction().
{
            QL_REQUIRE(d2>=d1,
                       "d1 (" << d1 << ") "
                       "later than d2 (" << d2 << ")");
            Time t1 = dc_.yearFraction(d1, d2, refStart, refEnd);
            Time t2 = resultDC.yearFraction(d1, d2, refStart, refEnd);
            return impliedRate(compoundFactor(t1), resultDC, comp, freq, t2);
        }
Frequency QuantLib::InterestRate::frequency () const [inline]
Definition at line 61 of file interestrate.hpp.
References freq_, freqMakesSense_, and QuantLib::NoFrequency.
Referenced by QuantLib::CashFlows::bps(), QuantLib::CashFlows::convexity(), QuantLib::anonymous_namespace{cashflows.cpp}::macaulayDuration(), QuantLib::anonymous_namespace{cashflows.cpp}::modifiedDuration(), QuantLib::FixedRateLeg::operator Leg(), QuantLib::operator<<(), BondTest::testBrazilianCached(), InterestRateTest::testConversions(), QuantLib::PiecewiseZeroSpreadedTermStructure::zeroYieldImpl(), and QuantLib::ZeroSpreadedTermStructure::zeroYieldImpl().
{
            return freqMakesSense_ ? Frequency(Integer(freq_)) : NoFrequency;
        }
InterestRate QuantLib::InterestRate::impliedRate (Real compound, const DayCounter & resultDC, Compounding comp, Frequency freq, Time t) [static]
implied interest rate for a given compound factor at a given time.
The resulting InterestRate has the day-counter provided as input.
Warning:
Time must be measured using the day-counter provided as input.
Definition at line 67 of file interestrate.cpp.
References QuantLib::Compounded, QuantLib::Continuous, InterestRate(), QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow(), QL_FAIL, QL_REQUIRE, QuantLib::Simple, QuantLib::SimpleThenCompounded, and anonymous_namespace{quantlibbenchmark.cpp}::t.
Referenced by equivalentRate(), QuantLib::YieldTermStructure::forwardRate(), impliedRate(), QuantLib::Forward::impliedYield(), and QuantLib::YieldTermStructure::zeroRate().
{
        QL_REQUIRE(compound>0.0, "positive compound factor required");
        Rate r;
        if (compound==1.0) {
            QL_REQUIRE(t>=0.0, "non negative time (" << t << ") required");
            r = 0.0;
        } else {
            QL_REQUIRE(t>0.0, "positive time (" << t << ") required");
            switch (comp) {
              case Simple:
                r = (compound - 1.0)/t;
                break;
              case Compounded:
                r = (std::pow(compound, 1.0/(Real(freq)*t))-1.0)*Real(freq);
                break;
              case Continuous:
                r = std::log(compound)/t;
                break;
              case SimpleThenCompounded:
                if (t<=1.0/Real(freq))
                    r = (compound - 1.0)/t;
                else
                    r = (std::pow(compound, 1.0/(Real(freq)*t))-1.0)*Real(freq);
                break;
              default:
                QL_FAIL("unknown compounding convention ("
                        << Integer(comp) << ")");
            }
        }
        return InterestRate(r, resultDC, comp, freq);
    }
static InterestRate QuantLib::InterestRate::impliedRate (Real compound, const DayCounter & resultDC, Compounding comp, Frequency freq, const Date & d1, const Date & d2, const Date & refStart = Date(), const Date & refEnd = Date()) [inline, static]
implied rate for a given compound factor between two dates.
The resulting rate is calculated taking the required day-counting rule into account.
Definition at line 132 of file interestrate.hpp.
References impliedRate(), QL_REQUIRE, anonymous_namespace{quantlibbenchmark.cpp}::t, and QuantLib::DayCounter::yearFraction().
{
            QL_REQUIRE(d2>=d1,
                       "d1 (" << d1 << ") "
                       "later than d2 (" << d2 << ")");
            Time t = resultDC.yearFraction(d1, d2, refStart, refEnd);
            return impliedRate(compound, resultDC, comp, freq, t);
        }
QuantLib::InterestRate::operator Rate () const [inline]
Definition at line 54 of file interestrate.hpp.
References r_.
{ return r_; }
Rate QuantLib::InterestRate::rate () const [inline]
Definition at line 58 of file interestrate.hpp.
References r_.
Referenced by QuantLib::CashFlows::bps(), QuantLib::CashFlows::convexity(), QuantLib::anonymous_namespace{cashflows.cpp}::macaulayDuration(), QuantLib::anonymous_namespace{cashflows.cpp}::modifiedDuration(), QuantLib::FixedRateLeg::operator Leg(), QuantLib::operator<<(), BondTest::testBrazilianCached(), and InterestRateTest::testConversions().
{ return r_; }
Friends And Related Function Documentation
std::ostream & operator<< (std::ostream & , const InterestRate &) [related]
Definition at line 106 of file interestrate.cpp.
{
        if (ir.rate() == Null<Rate>())
            return out << "null interest rate";
        out << io::rate(ir.rate()) << " " << ir.dayCounter().name() << " ";
        switch (ir.compounding()) {
          case Simple:
            out << "simple compounding";
            break;
          case Compounded:
            switch (ir.frequency()) {
              case NoFrequency:
              case Once:
                QL_FAIL(ir.frequency() << " frequency not allowed "
                        "for this interest rate");
              default:
                out << ir.frequency() <<" compounding";
            }
            break;
          case Continuous:
            out << "continuous compounding";
            break;
          case SimpleThenCompounded:
            switch (ir.frequency()) {
              case NoFrequency:
              case Once:
                QL_FAIL(ir.frequency() << " frequency not allowed "
                        "for this interest rate");
              default:
                out << "simple compounding up to "
                    << Integer(12/ir.frequency()) << " months, then "
                    << ir.frequency() << " compounding";
            }
            break;
          default:
            QL_FAIL("unknown compounding convention ("
                    << Integer(ir.compounding()) << ")");
        }
        return out;
    }
Member Data Documentation
Compounding QuantLib::InterestRate::comp_ [private]
Definition at line 186 of file interestrate.hpp.
Referenced by compoundFactor(), compounding(), and InterestRate().
DayCounter QuantLib::InterestRate::dc_ [private]
Definition at line 185 of file interestrate.hpp.
Referenced by compoundFactor(), dayCounter(), discountFactor(), and equivalentRate().
Real QuantLib::InterestRate::freq_ [private]
Definition at line 188 of file interestrate.hpp.
Referenced by compoundFactor(), frequency(), and InterestRate().
bool QuantLib::InterestRate::freqMakesSense_ [private]
Definition at line 187 of file interestrate.hpp.
Referenced by frequency(), and InterestRate().
Rate QuantLib::InterestRate::r_ [private]
Definition at line 184 of file interestrate.hpp.
Referenced by compoundFactor(), operator Rate(), and rate().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/interestrate.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/interestrate.cpp