QuantLib: QuantLib::Event Class Reference
QuantLib::Event Class Reference
Base class for event.
#include <event.hpp>
Public Member Functions
virtual ~Event ()
Event interface
virtual Date date () const =0
returns the date at which the event occurs
virtual bool hasOccurred (const Date &refDate=Date(), boost::optional< bool > includeRefDate=boost::none) const
returns true if an event has already occurred before a date
Visitability
virtual void accept (AcyclicVisitor &)
Detailed Description
Base class for event.
This class acts as a base class for the actual event implementations.
Definition at line 39 of file event.hpp.
Constructor & Destructor Documentation
virtual QuantLib::Event::~Event () [inline, virtual]
Definition at line 41 of file event.hpp.
{}
Member Function Documentation
void QuantLib::Event::accept (AcyclicVisitor & v) [virtual]
Reimplemented in QuantLib::DefaultEvent, QuantLib::CappedFlooredCmsCoupon, QuantLib::DigitalCoupon, QuantLib::CappedFlooredIborCoupon, QuantLib::CappedFlooredYoYInflationCoupon, QuantLib::CPICoupon, QuantLib::FloatingRateCoupon, QuantLib::InflationCoupon, QuantLib::CappedFlooredCoupon, QuantLib::SubPeriodsCoupon, QuantLib::Coupon, QuantLib::AmortizingPayment, QuantLib::RangeAccrualFloatersCoupon, QuantLib::CommodityCashFlow, QuantLib::DefaultEvent::DefaultSettlement, QuantLib::AverageBMACoupon, QuantLib::IndexedCashFlow, QuantLib::FixedRateCoupon, QuantLib::Callability, QuantLib::OvernightIndexedCoupon, QuantLib::Redemption, QuantLib::YoYInflationCoupon, QuantLib::CashFlow, QuantLib::IborCoupon, QuantLib::CmsCoupon, QuantLib::DigitalCmsCoupon, QuantLib::DigitalIborCoupon, QuantLib::Dividend, and QuantLib::SimpleCashFlow.
Definition at line 39 of file event.cpp.
References QL_FAIL, anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Visitor< T >::visit().
{
        Visitor<Event>* v1 = dynamic_cast<Visitor<Event>*>(&v);
        if (v1 != 0)
            v1->visit(*this);
        else
            QL_FAIL("not an event visitor");
    }
virtual Date QuantLib::Event::date () const [pure virtual]
returns the date at which the event occurs
Implemented in QuantLib::DefaultEvent, QuantLib::detail::simple_event, QuantLib::DefaultEvent::DefaultSettlement, QuantLib::Callability, QuantLib::IndexedCashFlow, QuantLib::Coupon, QuantLib::CommodityCashFlow, QuantLib::CashFlow, QuantLib::Dividend, and QuantLib::SimpleCashFlow.
Referenced by hasOccurred().
bool QuantLib::Event::hasOccurred (const Date & refDate = Date(), boost::optional< bool > includeRefDate = boost::none) const [virtual]
returns true if an event has already occurred before a date
If includeRefDate is true, then an event has not occurred if its date is the same as the refDate, i.e. this method returns false if the event date is the same as the refDate.
Reimplemented in QuantLib::CashFlow.
Definition at line 26 of file event.cpp.
References date(), QuantLib::Settings::evaluationDate(), QuantLib::Settings::includeReferenceDateEvents(), and QuantLib::Singleton< Settings >::instance().
Referenced by QuantLib::RiskyAssetSwapOption::isExpired(), QuantLib::PathMultiAssetOption::isExpired(), QuantLib::VarianceOption::isExpired(), QuantLib::VarianceSwap::isExpired(), QuantLib::RiskyBond::isExpired(), QuantLib::Forward::isExpired(), QuantLib::ForwardRateAgreement::isExpired(), and QuantLib::FailureToPayEvent::matchesEventType().
{
        Date refDate =
            d != Date() ? d : Settings::instance().evaluationDate();
        bool includeRefDateEvent =
            includeRefDate ? *includeRefDate :
                           Settings::instance().includeReferenceDateEvents();
        if (includeRefDateEvent)
            return date() < refDate;
        else
            return date() <= refDate;
    }
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/event.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/event.cpp