QuantLib: QuantLib::CallableBondVolatilityStructure Class Reference
QuantLib::CallableBondVolatilityStructure Class Reference
Callable-bond volatility structure.
#include <callablebondvolstructure.hpp>
Public Member Functions
virtual ~CallableBondVolatilityStructure ()
virtual std::pair< Time, Time > convertDates (const Date &optionDate, const Period &bondTenor) const
implements the conversion between dates and times
virtual BusinessDayConvention businessDayConvention () const
the business day convention used for option date calculation
Date optionDateFromTenor (const Period &optionTenor) const
implements the conversion between optionTenors and optionDates
Constructors
See the TermStructure documentation for issues regarding constructors.
CallableBondVolatilityStructure (const DayCounter &dc=DayCounter(), BusinessDayConvention bdc=Following)
default constructor
CallableBondVolatilityStructure (const Date &referenceDate, const Calendar &calendar=Calendar(), const DayCounter &dc=DayCounter(), BusinessDayConvention bdc=Following)
initialize with a fixed reference date
CallableBondVolatilityStructure (Natural settlementDays, const Calendar &, const DayCounter &dc=DayCounter(), BusinessDayConvention bdc=Following)
calculate the reference date based on the global evaluation date
Volatility, variance and smile
Volatility volatility (Time optionTime, Time bondLength, Rate strike, bool extrapolate=false) const
returns the volatility for a given option time and bondLength
Real blackVariance (Time optionTime, Time bondLength, Rate strike, bool extrapolate=false) const
returns the Black variance for a given option time and bondLength
Volatility volatility (const Date &optionDate, const Period &bondTenor, Rate strike, bool extrapolate=false) const
returns the volatility for a given option date and bond tenor
Real blackVariance (const Date &optionDate, const Period &bondTenor, Rate strike, bool extrapolate=false) const
returns the Black variance for a given option date and bond tenor
virtual boost::shared_ptr
< SmileSection > smileSection (const Date &optionDate, const Period &bondTenor) const
Volatility volatility (const Period &optionTenor, const Period &bondTenor, Rate strike, bool extrapolate=false) const
returns the volatility for a given option tenor and bond tenor
Real blackVariance (const Period &optionTenor, const Period &bondTenor, Rate strike, bool extrapolate=false) const
returns the Black variance for a given option tenor and bond tenor
boost::shared_ptr< SmileSection > smileSection (const Period &optionTenor, const Period &bondTenor) const
Limits
virtual const Period & maxBondTenor () const =0
the largest length for which the term structure can return vols
virtual Time maxBondLength () const
the largest bondLength for which the term structure can return vols
virtual Rate minStrike () const =0
the minimum strike for which the term structure can return vols
virtual Rate maxStrike () const =0
the maximum strike for which the term structure can return vols
Protected Member Functions
virtual boost::shared_ptr
< SmileSection > smileSectionImpl (Time optionTime, Time bondLength) const =0
return smile section
virtual Volatility volatilityImpl (Time optionTime, Time bondLength, Rate strike) const =0
implements the actual volatility calculation in derived classes
virtual Volatility volatilityImpl (const Date &optionDate, const Period &bondTenor, Rate strike) const
void checkRange (Time, Time, Rate strike, bool extrapolate) const
void checkRange (const Date &optionDate, const Period &bondTenor, Rate strike, bool extrapolate) const
Private Attributes
BusinessDayConvention bdc_
Detailed Description
Callable-bond volatility structure.
This class is purely abstract and defines the interface of concrete callable-bond volatility structures which will be derived from this one.
Definition at line 38 of file callablebondvolstructure.hpp.
Constructor & Destructor Documentation
QuantLib::CallableBondVolatilityStructure::CallableBondVolatilityStructure (const DayCounter & dc = DayCounter(), BusinessDayConvention bdc = Following)
default constructor
Warning:
term structures initialized by means of this constructor must manage their own reference date by overriding the referenceDate() method.
Definition at line 25 of file callablebondvolstructure.cpp.
    : TermStructure(dc), bdc_(bdc) {}
QuantLib::CallableBondVolatilityStructure::CallableBondVolatilityStructure (const Date & referenceDate, const Calendar & calendar = Calendar(), const DayCounter & dc = DayCounter(), BusinessDayConvention bdc = Following)
initialize with a fixed reference date
Definition at line 30 of file callablebondvolstructure.cpp.
    : TermStructure(referenceDate, calendar, dc), bdc_(bdc) {}
QuantLib::CallableBondVolatilityStructure::CallableBondVolatilityStructure (Natural settlementDays, const Calendar & calendar, const DayCounter & dc = DayCounter(), BusinessDayConvention bdc = Following)
calculate the reference date based on the global evaluation date
Definition at line 37 of file callablebondvolstructure.cpp.
    : TermStructure(settlementDays, calendar, dc), bdc_(bdc) {}
virtual QuantLib::CallableBondVolatilityStructure::~CallableBondVolatilityStructure () [inline, virtual]
Definition at line 63 of file callablebondvolstructure.hpp.
{}
Member Function Documentation
Real QuantLib::CallableBondVolatilityStructure::blackVariance (Time optionTime, Time bondLength, Rate strike, bool extrapolate = false) const [inline]
returns the Black variance for a given option time and bondLength
Definition at line 177 of file callablebondvolstructure.hpp.
References checkRange(), and volatilityImpl().
{
        checkRange(optionTime, bondLength, strike, extrapolate);
        Volatility vol = volatilityImpl(optionTime, bondLength, strike);
        return vol*vol*optionTime;
    }
Real QuantLib::CallableBondVolatilityStructure::blackVariance (const Date & optionDate, const Period & bondTenor, Rate strike, bool extrapolate = false) const [inline]
returns the Black variance for a given option date and bond tenor
Definition at line 197 of file callablebondvolstructure.hpp.
References convertDates(), and volatility().
{
        Volatility vol =
            volatility(optionDate, bondTenor, strike, extrapolate);
        const std::pair<Time, Time> p = convertDates(optionDate, bondTenor);
        return vol*vol*p.first;
    }
Real QuantLib::CallableBondVolatilityStructure::blackVariance (const Period & optionTenor, const Period & bondTenor, Rate strike, bool extrapolate = false) const [inline]
returns the Black variance for a given option tenor and bond tenor
Definition at line 217 of file callablebondvolstructure.hpp.
References convertDates(), optionDateFromTenor(), and volatility().
{
        Date optionDate = optionDateFromTenor(optionTenor);
        Volatility vol =
            volatility(optionDate, bondTenor, strike, extrapolate);
        const std::pair<Time, Time> p = convertDates(optionDate, bondTenor);
        return vol*vol*p.first;
    }
BusinessDayConvention QuantLib::CallableBondVolatilityStructure::businessDayConvention () const [inline, virtual]
the business day convention used for option date calculation
Definition at line 156 of file callablebondvolstructure.hpp.
References bdc_.
Referenced by optionDateFromTenor().
{
        return bdc_;
    }
void QuantLib::CallableBondVolatilityStructure::checkRange (Time optionTime, Time bondLength, Rate strike, bool extrapolate) const [inline, protected]
Definition at line 239 of file callablebondvolstructure.hpp.
References QuantLib::Extrapolator::allowsExtrapolation(), maxBondLength(), maxStrike(), minStrike(), and QL_REQUIRE.
Referenced by blackVariance(), checkRange(), and volatility().
{
        TermStructure::checkRange(optionTime, extrapolate);
        QL_REQUIRE(bondLength >= 0.0,
                   "negative bondLength (" << bondLength << ") given");
        QL_REQUIRE(extrapolate || allowsExtrapolation() ||
                   bondLength <= maxBondLength(),
                   "bondLength (" << bondLength << ") is past max curve bondLength ("
                   << maxBondLength() << ")");
        QL_REQUIRE(extrapolate || allowsExtrapolation() ||
                   (k >= minStrike() && k <= maxStrike()),
                   "strike (" << k << ") is outside the curve domain ["
                   << minStrike() << "," << maxStrike()<< "]");
    }
void QuantLib::CallableBondVolatilityStructure::checkRange (const Date & optionDate, const Period & bondTenor, Rate strike, bool extrapolate) const [protected]
Definition at line 60 of file callablebondvolstructure.cpp.
References QuantLib::Extrapolator::allowsExtrapolation(), checkRange(), QuantLib::Period::length(), maxBondTenor(), maxStrike(), minStrike(), QL_REQUIRE, and QuantLib::TermStructure::timeFromReference().
{
        TermStructure::checkRange(timeFromReference(optionDate),
                                  extrapolate);
        QL_REQUIRE(bondTenor.length() > 0,
                   "negative bond tenor (" << bondTenor << ") given");
        QL_REQUIRE(extrapolate || allowsExtrapolation() ||
                   bondTenor <= maxBondTenor(),
                   "bond tenor (" << bondTenor << ") is past max tenor ("
                   << maxBondTenor() << ")");
        QL_REQUIRE(extrapolate || allowsExtrapolation() ||
                   (k >= minStrike() && k <= maxStrike()),
                   "strike (" << k << ") is outside the curve domain ["
                   << minStrike() << "," << maxStrike()<< "]");
    }
std::pair< Time, Time > QuantLib::CallableBondVolatilityStructure::convertDates (const Date & optionDate, const Period & bondTenor) const [virtual]
implements the conversion between dates and times
Definition at line 49 of file callablebondvolstructure.cpp.
References QuantLib::TermStructure::dayCounter(), QL_REQUIRE, QuantLib::TermStructure::timeFromReference(), and QuantLib::DayCounter::yearFraction().
Referenced by blackVariance(), smileSection(), and volatilityImpl().
{
        Date end = optionDate + bondTenor;
        QL_REQUIRE(end>optionDate,
                   "negative bond tenor (" << bondTenor << ") given");
        Time optionTime = timeFromReference(optionDate);
        Time timeLength = dayCounter().yearFraction(optionDate, end);
        return std::make_pair(optionTime, timeLength);
    }
Time QuantLib::CallableBondVolatilityStructure::maxBondLength () const [virtual]
the largest bondLength for which the term structure can return vols
Reimplemented in QuantLib::CallableBondConstantVolatility.
Definition at line 44 of file callablebondvolstructure.cpp.
References maxBondTenor(), QuantLib::TermStructure::referenceDate(), and QuantLib::TermStructure::timeFromReference().
Referenced by checkRange().
{
        return timeFromReference(referenceDate()+maxBondTenor());
    }
virtual const Period& QuantLib::CallableBondVolatilityStructure::maxBondTenor () const [pure virtual]
the largest length for which the term structure can return vols
Implemented in QuantLib::CallableBondConstantVolatility.
Referenced by checkRange(), and maxBondLength().
virtual Rate QuantLib::CallableBondVolatilityStructure::maxStrike () const [pure virtual]
the maximum strike for which the term structure can return vols
Implemented in QuantLib::CallableBondConstantVolatility.
Referenced by checkRange().
virtual Rate QuantLib::CallableBondVolatilityStructure::minStrike () const [pure virtual]
the minimum strike for which the term structure can return vols
Implemented in QuantLib::CallableBondConstantVolatility.
Referenced by checkRange().
Date QuantLib::CallableBondVolatilityStructure::optionDateFromTenor (const Period & optionTenor) const [inline]
implements the conversion between optionTenors and optionDates
Definition at line 160 of file callablebondvolstructure.hpp.
References QuantLib::Calendar::advance(), businessDayConvention(), QuantLib::TermStructure::calendar(), and QuantLib::TermStructure::referenceDate().
Referenced by blackVariance(), smileSection(), and volatility().
{
        return calendar().advance(referenceDate(),
                                  optionTenor,
                                  businessDayConvention());
    }
virtual boost::shared_ptr<SmileSection> QuantLib::CallableBondVolatilityStructure::smileSection (const Date & optionDate, const Period & bondTenor) const [inline, virtual]
Definition at line 87 of file callablebondvolstructure.hpp.
References convertDates(), and smileSectionImpl().
Referenced by smileSection().
{
            const std::pair<Time, Time> p = convertDates(optionDate, bondTenor);
            return smileSectionImpl(p.first, p.second);
        }
boost::shared_ptr< SmileSection > QuantLib::CallableBondVolatilityStructure::smileSection (const Period & optionTenor, const Period & bondTenor) const [inline]
Definition at line 231 of file callablebondvolstructure.hpp.
References optionDateFromTenor(), and smileSection().
{
        Date optionDate = optionDateFromTenor(optionTenor);
        return smileSection(optionDate, bondTenor);
    }
virtual boost::shared_ptr<SmileSection> QuantLib::CallableBondVolatilityStructure::smileSectionImpl (Time optionTime, Time bondLength) const [protected, pure virtual]
return smile section
Implemented in QuantLib::CallableBondConstantVolatility.
Referenced by smileSection().
Volatility QuantLib::CallableBondVolatilityStructure::volatility (Time optionTime, Time bondLength, Rate strike, bool extrapolate = false) const [inline]
returns the volatility for a given option time and bondLength
Definition at line 167 of file callablebondvolstructure.hpp.
References checkRange(), and volatilityImpl().
Referenced by blackVariance(), and volatility().
{
        checkRange(optionTime, bondLength, strike, extrapolate);
        return volatilityImpl(optionTime, bondLength, strike);
    }
Volatility QuantLib::CallableBondVolatilityStructure::volatility (const Date & optionDate, const Period & bondTenor, Rate strike, bool extrapolate = false) const [inline]
returns the volatility for a given option date and bond tenor
Definition at line 188 of file callablebondvolstructure.hpp.
References checkRange(), and volatilityImpl().
{
        checkRange(optionDate, bondTenor, strike, extrapolate);
        return volatilityImpl(optionDate, bondTenor, strike);
    }
Volatility QuantLib::CallableBondVolatilityStructure::volatility (const Period & optionTenor, const Period & bondTenor, Rate strike, bool extrapolate = false) const [inline]
returns the volatility for a given option tenor and bond tenor
Definition at line 208 of file callablebondvolstructure.hpp.
References optionDateFromTenor(), and volatility().
{
        Date optionDate = optionDateFromTenor(optionTenor);
        return volatility(optionDate, bondTenor, strike, extrapolate);
    }
virtual Volatility QuantLib::CallableBondVolatilityStructure::volatilityImpl (Time optionTime, Time bondLength, Rate strike) const [protected, pure virtual]
implements the actual volatility calculation in derived classes
Implemented in QuantLib::CallableBondConstantVolatility.
Referenced by blackVariance(), volatility(), and volatilityImpl().
virtual Volatility QuantLib::CallableBondVolatilityStructure::volatilityImpl (const Date & optionDate, const Period & bondTenor, Rate strike) const [inline, protected, virtual]
Reimplemented in QuantLib::CallableBondConstantVolatility.
Definition at line 138 of file callablebondvolstructure.hpp.
References convertDates(), and volatilityImpl().
{
            const std::pair<Time, Time> p = convertDates(optionDate, bondTenor);
            return volatilityImpl(p.first, p.second, strike);
        }
Member Data Documentation
BusinessDayConvention QuantLib::CallableBondVolatilityStructure::bdc_ [private]
Definition at line 149 of file callablebondvolstructure.hpp.
Referenced by businessDayConvention().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/callablebonds/callablebondvolstructure.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/callablebonds/callablebondvolstructure.cpp