QuantLib: QuantLib::CdsHelper Class Reference
QuantLib::CdsHelper Class Reference
#include <defaultprobabilityhelpers.hpp>
Public Member Functions
CdsHelper (const Handle< Quote > &quote, const Period &tenor, Integer settlementDays, const Calendar &calendar, Frequency frequency, BusinessDayConvention paymentConvention, DateGeneration::Rule rule, const DayCounter &dayCounter, Real recoveryRate, const Handle< YieldTermStructure > &discountCurve, bool settlesAccrual=true, bool paysAtDefaultTime=true)
CdsHelper (Rate quote, const Period &tenor, Integer settlementDays, const Calendar &calendar, Frequency frequency, BusinessDayConvention paymentConvention, DateGeneration::Rule rule, const DayCounter &dayCounter, Real recoveryRate, const Handle< YieldTermStructure > &discountCurve, bool settlesAccrual=true, bool paysAtDefaultTime=true)
void setTermStructure (DefaultProbabilityTermStructure *)
Protected Member Functions
void update ()
void initializeDates ()
virtual void resetEngine ()=0
Protected Attributes
Period tenor_
Integer settlementDays_
Calendar calendar_
Frequency frequency_
BusinessDayConvention paymentConvention_
DateGeneration::Rule rule_
DayCounter dayCounter_
Real recoveryRate_
Handle< YieldTermStructure > discountCurve_
bool settlesAccrual_
bool paysAtDefaultTime_
Schedule schedule_
boost::shared_ptr
< CreditDefaultSwap > swap_
RelinkableHandle
< DefaultProbabilityTermStructure > probability_
Date protectionStart_
protection effective date.
Detailed Description
Base default-probability bootstrap helper
Parameters:
tenor CDS tenor.
frequency Coupon frequency.
settlementDays The number of days from today's date to the start of the protection period.
paymentConvention The payment convention applied to coupons schedules, settlement dates and protection period calculations.
Definition at line 54 of file defaultprobabilityhelpers.hpp.
Constructor & Destructor Documentation
QuantLib::CdsHelper::CdsHelper (const Handle< Quote > & quote, const Period & tenor, Integer settlementDays, const Calendar & calendar, Frequency frequency, BusinessDayConvention paymentConvention, DateGeneration::Rule rule, const DayCounter & dayCounter, Real recoveryRate, const Handle< YieldTermStructure > & discountCurve, bool settlesAccrual = true, bool paysAtDefaultTime = true)
Definition at line 33 of file defaultprobabilityhelpers.cpp.
References initializeDates(), and QuantLib::Observer::registerWith().
    : RelativeDateDefaultProbabilityHelper(quote),
      tenor_(tenor), settlementDays_(settlementDays), calendar_(calendar),
      frequency_(frequency), paymentConvention_(paymentConvention),
      rule_(rule), dayCounter_(dayCounter), recoveryRate_(recoveryRate),
      discountCurve_(discountCurve),
      settlesAccrual_(settlesAccrual), paysAtDefaultTime_(paysAtDefaultTime) {
        initializeDates();
        registerWith(discountCurve);
    }
QuantLib::CdsHelper::CdsHelper (Rate quote, const Period & tenor, Integer settlementDays, const Calendar & calendar, Frequency frequency, BusinessDayConvention paymentConvention, DateGeneration::Rule rule, const DayCounter & dayCounter, Real recoveryRate, const Handle< YieldTermStructure > & discountCurve, bool settlesAccrual = true, bool paysAtDefaultTime = true)
Definition at line 57 of file defaultprobabilityhelpers.cpp.
References initializeDates(), and QuantLib::Observer::registerWith().
    : RelativeDateDefaultProbabilityHelper(quote),
      tenor_(tenor), settlementDays_(settlementDays), calendar_(calendar),
      frequency_(frequency), paymentConvention_(paymentConvention),
      rule_(rule), dayCounter_(dayCounter), recoveryRate_(recoveryRate),
      discountCurve_(discountCurve),
      settlesAccrual_(settlesAccrual), paysAtDefaultTime_(paysAtDefaultTime) {
        initializeDates();
        registerWith(discountCurve);
    }
Member Function Documentation
void QuantLib::CdsHelper::initializeDates () [protected, virtual]
Implements QuantLib::RelativeDateBootstrapHelper< TS >.
Reimplemented in QuantLib::UpfrontCdsHelper.
Definition at line 96 of file defaultprobabilityhelpers.cpp.
References QuantLib::Calendar::adjust(), calendar_, QuantLib::Schedule::dates(), QuantLib::BootstrapHelper< TS >::earliestDate_, anonymous_namespace{marketmodel.cpp}::endDate, QuantLib::RelativeDateBootstrapHelper< TS >::evaluationDate_, frequency_, QuantLib::MakeSchedule::from(), QuantLib::BootstrapHelper< TS >::latestDate_, paymentConvention_, protectionStart_, rule_, schedule_, settlementDays_, anonymous_namespace{marketmodel.cpp}::startDate, tenor_, QuantLib::MakeSchedule::to(), QuantLib::Unadjusted, QuantLib::MakeSchedule::withCalendar(), QuantLib::MakeSchedule::withConvention(), QuantLib::MakeSchedule::withFrequency(), QuantLib::MakeSchedule::withRule(), and QuantLib::MakeSchedule::withTerminationDateConvention().
Referenced by CdsHelper().
{
        protectionStart_ = evaluationDate_ + settlementDays_;
        Date startDate = calendar_.adjust(protectionStart_,
                                          paymentConvention_);
        Date endDate = evaluationDate_ + tenor_;
        schedule_ =
            MakeSchedule().from(startDate)
                          .to(endDate)
                          .withFrequency(frequency_)
                          .withCalendar(calendar_)
                          .withConvention(paymentConvention_)
                          .withTerminationDateConvention(Unadjusted)
                          .withRule(rule_);
        earliestDate_ = schedule_.dates().front();
        latestDate_   = calendar_.adjust(schedule_.dates().back(),
                                         paymentConvention_);
    }
virtual void QuantLib::CdsHelper::resetEngine () [protected, pure virtual]
Implemented in QuantLib::UpfrontCdsHelper, and QuantLib::SpreadCdsHelper.
Referenced by setTermStructure(), and update().
void QuantLib::CdsHelper::setTermStructure (DefaultProbabilityTermStructure * ts)
Definition at line 81 of file defaultprobabilityhelpers.cpp.
References QuantLib::RelinkableHandle< T >::linkTo(), QuantLib::anonymous_namespace{riskyassetswap.cpp}::no_deletion(), probability_, and resetEngine().
{
        RelativeDateDefaultProbabilityHelper::setTermStructure(ts);
        probability_.linkTo(
            boost::shared_ptr<DefaultProbabilityTermStructure>(ts, no_deletion),
            false);
        resetEngine();
    }
void QuantLib::CdsHelper::update () [protected, virtual]
This method must be implemented in derived classes. An instance of Observer does not call this method directly: instead, it will be called by the observables the instance registered with when they need to notify any changes.
Reimplemented from QuantLib::RelativeDateBootstrapHelper< TS >.
Definition at line 91 of file defaultprobabilityhelpers.cpp.
References resetEngine().
{
        RelativeDateDefaultProbabilityHelper::update();
        resetEngine();
    }
Member Data Documentation
Calendar QuantLib::CdsHelper::calendar_ [protected]
Definition at line 87 of file defaultprobabilityhelpers.hpp.
Referenced by initializeDates(), and QuantLib::UpfrontCdsHelper::initializeDates().
DayCounter QuantLib::CdsHelper::dayCounter_ [protected]
Definition at line 91 of file defaultprobabilityhelpers.hpp.
Referenced by QuantLib::SpreadCdsHelper::resetEngine(), and QuantLib::UpfrontCdsHelper::resetEngine().
Handle<YieldTermStructure> QuantLib::CdsHelper::discountCurve_ [protected]
Definition at line 93 of file defaultprobabilityhelpers.hpp.
Referenced by QuantLib::SpreadCdsHelper::resetEngine(), and QuantLib::UpfrontCdsHelper::resetEngine().
Frequency QuantLib::CdsHelper::frequency_ [protected]
Definition at line 88 of file defaultprobabilityhelpers.hpp.
Referenced by initializeDates().
BusinessDayConvention QuantLib::CdsHelper::paymentConvention_ [protected]
Definition at line 89 of file defaultprobabilityhelpers.hpp.
Referenced by initializeDates(), QuantLib::UpfrontCdsHelper::initializeDates(), QuantLib::SpreadCdsHelper::resetEngine(), and QuantLib::UpfrontCdsHelper::resetEngine().
bool QuantLib::CdsHelper::paysAtDefaultTime_ [protected]
Definition at line 95 of file defaultprobabilityhelpers.hpp.
Referenced by QuantLib::SpreadCdsHelper::resetEngine(), and QuantLib::UpfrontCdsHelper::resetEngine().
RelinkableHandle<DefaultProbabilityTermStructure> QuantLib::CdsHelper::probability_ [protected]
Definition at line 99 of file defaultprobabilityhelpers.hpp.
Referenced by QuantLib::SpreadCdsHelper::resetEngine(), QuantLib::UpfrontCdsHelper::resetEngine(), and setTermStructure().
Date QuantLib::CdsHelper::protectionStart_ [protected]
protection effective date.
Definition at line 101 of file defaultprobabilityhelpers.hpp.
Referenced by initializeDates(), QuantLib::SpreadCdsHelper::resetEngine(), and QuantLib::UpfrontCdsHelper::resetEngine().
Real QuantLib::CdsHelper::recoveryRate_ [protected]
Definition at line 92 of file defaultprobabilityhelpers.hpp.
Referenced by QuantLib::SpreadCdsHelper::resetEngine(), and QuantLib::UpfrontCdsHelper::resetEngine().
DateGeneration::Rule QuantLib::CdsHelper::rule_ [protected]
Definition at line 90 of file defaultprobabilityhelpers.hpp.
Referenced by initializeDates().
Schedule QuantLib::CdsHelper::schedule_ [protected]
Definition at line 97 of file defaultprobabilityhelpers.hpp.
Referenced by initializeDates(), QuantLib::SpreadCdsHelper::resetEngine(), and QuantLib::UpfrontCdsHelper::resetEngine().
Integer QuantLib::CdsHelper::settlementDays_ [protected]
Definition at line 86 of file defaultprobabilityhelpers.hpp.
Referenced by initializeDates().
bool QuantLib::CdsHelper::settlesAccrual_ [protected]
Definition at line 94 of file defaultprobabilityhelpers.hpp.
Referenced by QuantLib::SpreadCdsHelper::resetEngine(), and QuantLib::UpfrontCdsHelper::resetEngine().
boost::shared_ptr<CreditDefaultSwap> QuantLib::CdsHelper::swap_ [protected]
Definition at line 98 of file defaultprobabilityhelpers.hpp.
Referenced by QuantLib::SpreadCdsHelper::impliedQuote(), QuantLib::UpfrontCdsHelper::impliedQuote(), QuantLib::SpreadCdsHelper::resetEngine(), and QuantLib::UpfrontCdsHelper::resetEngine().
Period QuantLib::CdsHelper::tenor_ [protected]
Definition at line 85 of file defaultprobabilityhelpers.hpp.
Referenced by initializeDates().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/credit/defaultprobabilityhelpers.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/credit/defaultprobabilityhelpers.cpp