QuantLib: QuantLib::CmsCoupon Class Reference
QuantLib::CmsCoupon Class Reference
CMS coupon class.
#include <cmscoupon.hpp>
Public Member Functions
CmsCoupon (const Date &paymentDate, Real nominal, const Date &startDate, const Date &endDate, Natural fixingDays, const boost::shared_ptr< SwapIndex > &index, Real gearing=1.0, Spread spread=0.0, const Date &refPeriodStart=Date(), const Date &refPeriodEnd=Date(), const DayCounter &dayCounter=DayCounter(), bool isInArrears=false)
Inspectors
const boost::shared_ptr
< SwapIndex > & swapIndex () const
Visitability
virtual void accept (AcyclicVisitor &)
Private Attributes
boost::shared_ptr< SwapIndex > swapIndex_
Detailed Description
CMS coupon class.
Warning:
This class does not perform any date adjustment, i.e., the start and end date passed upon construction should be already rolled to a business day.
Definition at line 39 of file cmscoupon.hpp.
Constructor & Destructor Documentation
QuantLib::CmsCoupon::CmsCoupon (const Date & paymentDate, Real nominal, const Date & startDate, const Date & endDate, Natural fixingDays, const boost::shared_ptr< SwapIndex > & index, Real gearing = 1.0, Spread spread = 0.0, const Date & refPeriodStart = Date(), const Date & refPeriodEnd = Date(), const DayCounter & dayCounter = DayCounter(), bool isInArrears = false)
Definition at line 28 of file cmscoupon.cpp.
    : FloatingRateCoupon(paymentDate, nominal, startDate, endDate,
                         fixingDays, swapIndex, gearing, spread,
                         refPeriodStart, refPeriodEnd,
                         dayCounter, isInArrears),
      swapIndex_(swapIndex) {}
Member Function Documentation
void QuantLib::CmsCoupon::accept (AcyclicVisitor & v) [virtual]
Reimplemented from QuantLib::FloatingRateCoupon.
Definition at line 46 of file cmscoupon.cpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Visitor< T >::visit().
{
        Visitor<CmsCoupon>* v1 = dynamic_cast<Visitor<CmsCoupon>*>(&v);
        if (v1 != 0)
            v1->visit(*this);
        else
            FloatingRateCoupon::accept(v);
    }
const boost::shared_ptr<SwapIndex>& QuantLib::CmsCoupon::swapIndex () const [inline]
Definition at line 55 of file cmscoupon.hpp.
References swapIndex_.
Referenced by QuantLib::HaganPricer::capletPrice(), QuantLib::HaganPricer::floorletPrice(), QuantLib::GFunctionFactory::GFunctionExactYield::GFunctionExactYield(), QuantLib::GFunctionFactory::GFunctionWithShifts::GFunctionWithShifts(), QuantLib::HaganPricer::initialize(), QuantLib::NumericHaganPricer::swapletPrice(), and QuantLib::AnalyticHaganPricer::swapletPrice().
{
            return swapIndex_;
        }
Member Data Documentation
boost::shared_ptr<SwapIndex> QuantLib::CmsCoupon::swapIndex_ [private]
Definition at line 64 of file cmscoupon.hpp.
Referenced by swapIndex().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/cmscoupon.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/cmscoupon.cpp