QuantLib: QuantLib::VegaBumpCollection Class Reference
QuantLib::VegaBumpCollection Class Reference
#include <vegabumpcluster.hpp>
Public Member Functions
VegaBumpCollection (const boost::shared_ptr< MarketModel > &volStructure, bool allowFactorwiseBumping=true)
VegaBumpCollection (const std::vector< VegaBumpCluster > &allBumps, const boost::shared_ptr< MarketModel > &volStructure)
Size numberBumps () const
const boost::shared_ptr
< MarketModel > & associatedModel () const
const std::vector
< VegaBumpCluster > & allBumps () const
bool isFull () const
bool isNonOverlapping () const
bool isSensible () const
Private Attributes
std::vector< VegaBumpCluster > allBumps_
boost::shared_ptr< MarketModel > associatedVolStructure_
bool checked_
bool nonOverlapped_
bool full_
Detailed Description
There are too many pseudo-root elements to allow bumping them all independently so we cluster them together and then divide all elements into a collection of such clusters.
Definition at line 99 of file vegabumpcluster.hpp.
Constructor & Destructor Documentation
QuantLib::VegaBumpCollection::VegaBumpCollection (const boost::shared_ptr< MarketModel > & volStructure, bool allowFactorwiseBumping = true)
Definition at line 99 of file vegabumpcluster.cpp.
References allBumps_, checked_, anonymous_namespace{interpolations.cpp}::f(), full_, and nonOverlapped_.
                            : associatedVolStructure_(volStructure)
    {
        Size steps = volStructure->numberOfSteps();
        Size rates = volStructure->numberOfRates();
        Size factors = volStructure->numberOfFactors();
        for (Size s=0; s < steps; ++s)
            for (Size r=volStructure->evolution().firstAliveRate()[s]; r < rates; ++r)
            {
                if (factorwiseBumping)
                {
                    for (Size f=0; f < factors; ++f)
                    {
                        VegaBumpCluster thisCluster(f,f+1,r,r+1,s,s+1);
                        allBumps_.push_back(thisCluster);
                    }
                }
                else
                {
                     VegaBumpCluster thisCluster(0,factors,r,r+1,s,s+1);
                     allBumps_.push_back(thisCluster);
                }
            }
        checked_=true;
        full_=true;
        nonOverlapped_=true;
    }
QuantLib::VegaBumpCollection::VegaBumpCollection (const std::vector< VegaBumpCluster > & allBumps, const boost::shared_ptr< MarketModel > & volStructure)
Definition at line 135 of file vegabumpcluster.cpp.
References allBumps_, associatedVolStructure_, and QL_REQUIRE.
        : allBumps_(allBumps), associatedVolStructure_(volStructure), checked_(false)
    {
        for (Size j=0; j < allBumps_.size(); ++j)
            QL_REQUIRE(allBumps_[j].isCompatible(associatedVolStructure_),"incompatible bumps passed to VegaBumpCollection");
    }
Member Function Documentation
const std::vector< VegaBumpCluster > & QuantLib::VegaBumpCollection::allBumps () const
Definition at line 144 of file vegabumpcluster.cpp.
References allBumps_.
Referenced by QuantLib::VolatilityBumpInstrumentJacobian::derivativesVolatility(), and QuantLib::OrthogonalizedBumpFinder::GetVegaBumps().
    {
        return allBumps_;
    }
const boost::shared_ptr<MarketModel>& QuantLib::VegaBumpCollection::associatedModel () const [inline]
Definition at line 110 of file vegabumpcluster.hpp.
References associatedVolStructure_.
Referenced by QuantLib::VolatilityBumpInstrumentJacobian::derivativesVolatility(), and QuantLib::OrthogonalizedBumpFinder::GetVegaBumps().
        {
            return associatedVolStructure_;
        }
bool QuantLib::VegaBumpCollection::isFull () const
Definition at line 149 of file vegabumpcluster.cpp.
References allBumps_, associatedVolStructure_, checked_, anonymous_namespace{interpolations.cpp}::f(), full_, and anonymous_namespace{perturbativebarrieroptionengine.cpp}::v().
Referenced by isSensible().
    {
        if (checked_)
            return full_;
        std::vector<std::vector<std::valarray<bool> > > v;
        Size factors = associatedVolStructure_->numberOfFactors();
        std::valarray<bool> model(false,factors);
    //    std::fill(model.begin(), model.end(), false);
        std::vector<std::valarray<bool> > modelTwo;
        for (Size i=0; i < associatedVolStructure_->numberOfRates(); ++i)
            modelTwo.push_back(model);
        for (Size j=0; j < associatedVolStructure_->numberOfSteps(); ++j)
            v.push_back(modelTwo);
        for (Size k=0; k < allBumps_.size(); ++k)
        {
            for (Size f=allBumps_[k].factorBegin(); f <  allBumps_[k].factorEnd(); ++f)
                for (Size r=allBumps_[k].rateBegin(); r <  allBumps_[k].rateEnd(); ++r)
                    for (Size s= allBumps_[k].stepBegin(); s <  allBumps_[k].stepEnd(); ++s)
                        v[s][r][f] = true;
        }
        Size numberFailures =0;
        for (Size s =0; s < associatedVolStructure_->numberOfSteps(); ++s)
            for (Size f=0; f < associatedVolStructure_->numberOfFactors(); ++f)
                for (Size r=associatedVolStructure_->evolution().firstAliveRate()[s]; r <  associatedVolStructure_->numberOfRates(); ++r)
                    if (!v[s][r][f])
                        ++numberFailures;
        return numberFailures>0;
    }
bool QuantLib::VegaBumpCollection::isNonOverlapping () const
Definition at line 187 of file vegabumpcluster.cpp.
References allBumps_, associatedVolStructure_, checked_, anonymous_namespace{interpolations.cpp}::f(), nonOverlapped_, and anonymous_namespace{perturbativebarrieroptionengine.cpp}::v().
Referenced by isSensible().
    {
        if (checked_)
            return nonOverlapped_;
        std::vector<std::vector<std::valarray<bool> > > v;
        Size factors = associatedVolStructure_->numberOfFactors();
        std::valarray<bool> model(false,factors);
        //std::fill(model.begin(), model.end(), false);
        std::vector<std::valarray<bool> > modelTwo;
        for (Size i=0; i < associatedVolStructure_->numberOfRates(); ++i)
            modelTwo.push_back(model);
        for (Size j=0; j < associatedVolStructure_->numberOfSteps(); ++j)
            v.push_back(modelTwo);
        Size numberFailures=0;
        for (Size k=0; k < allBumps_.size(); ++k)
        {
            for (Size f=allBumps_[k].factorBegin(); f <  allBumps_[k].factorEnd(); ++f)
                for (Size r=allBumps_[k].rateBegin(); r <  allBumps_[k].rateEnd(); ++r)
                    for (Size s= allBumps_[k].stepBegin(); s <  allBumps_[k].stepEnd(); ++s)
                    {
                        if (v[s][r][f])
                            ++numberFailures;
                        v[s][r][f] = true;
                    }
        }
        return numberFailures>0;
    }
bool QuantLib::VegaBumpCollection::isSensible () const
Definition at line 227 of file vegabumpcluster.cpp.
References checked_, isFull(), and isNonOverlapping().
    {
        if (checked_)
            return true;
        return isNonOverlapping() && isFull();
    }
Size QuantLib::VegaBumpCollection::numberBumps () const
Definition at line 236 of file vegabumpcluster.cpp.
References allBumps_.
Referenced by QuantLib::VolatilityBumpInstrumentJacobian::derivativesVolatility().
    {
        return allBumps_.size();
    }
Member Data Documentation
std::vector<VegaBumpCluster> QuantLib::VegaBumpCollection::allBumps_ [private]
Definition at line 125 of file vegabumpcluster.hpp.
Referenced by allBumps(), isFull(), isNonOverlapping(), numberBumps(), and VegaBumpCollection().
boost::shared_ptr<MarketModel> QuantLib::VegaBumpCollection::associatedVolStructure_ [private]
Definition at line 126 of file vegabumpcluster.hpp.
Referenced by associatedModel(), isFull(), isNonOverlapping(), and VegaBumpCollection().
bool QuantLib::VegaBumpCollection::checked_ [mutable, private]
Definition at line 127 of file vegabumpcluster.hpp.
Referenced by isFull(), isNonOverlapping(), isSensible(), and VegaBumpCollection().
bool QuantLib::VegaBumpCollection::full_ [mutable, private]
Definition at line 129 of file vegabumpcluster.hpp.
Referenced by isFull(), and VegaBumpCollection().
bool QuantLib::VegaBumpCollection::nonOverlapped_ [mutable, private]
Definition at line 128 of file vegabumpcluster.hpp.
Referenced by isNonOverlapping(), and VegaBumpCollection().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/pathwisegreeks/vegabumpcluster.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/pathwisegreeks/vegabumpcluster.cpp