QuantLib: QuantLib::OneFactorModel::ShortRateTree Class Reference
QuantLib::OneFactorModel::ShortRateTree Class Reference
Recombining trinomial tree discretizing the state variable.
#include <onefactormodel.hpp>
Classes
class Helper
Public Member Functions
ShortRateTree (const boost::shared_ptr< TrinomialTree > &tree, const boost::shared_ptr< ShortRateDynamics > &dynamics, const TimeGrid &timeGrid)
Plain tree build-up from short-rate dynamics.
ShortRateTree (const boost::shared_ptr< TrinomialTree > &tree, const boost::shared_ptr< ShortRateDynamics > &dynamics, const boost::shared_ptr< TermStructureFittingParameter::NumericalImpl > &phi, const TimeGrid &timeGrid)
Tree build-up + numerical fitting to term-structure.
Size size (Size i) const
DiscountFactor discount (Size i, Size index) const
Real underlying (Size i, Size index) const
Size descendant (Size i, Size index, Size branch) const
Real probability (Size i, Size index, Size branch) const
Private Attributes
boost::shared_ptr< TrinomialTree > tree_
boost::shared_ptr
< ShortRateDynamics > dynamics_
Detailed Description
Recombining trinomial tree discretizing the state variable.
Definition at line 75 of file onefactormodel.hpp.
Constructor & Destructor Documentation
QuantLib::OneFactorModel::ShortRateTree::ShortRateTree (const boost::shared_ptr< TrinomialTree > & tree, const boost::shared_ptr< ShortRateDynamics > & dynamics, const TimeGrid & timeGrid)
Plain tree build-up from short-rate dynamics.
Definition at line 85 of file onefactormodel.cpp.
    : TreeLattice1D<OneFactorModel::ShortRateTree>(timeGrid, tree->size(1)),
      tree_(tree), dynamics_(dynamics) {}
QuantLib::OneFactorModel::ShortRateTree::ShortRateTree (const boost::shared_ptr< TrinomialTree > & tree, const boost::shared_ptr< ShortRateDynamics > & dynamics, const boost::shared_ptr< TermStructureFittingParameter::NumericalImpl > & phi, const TimeGrid & timeGrid)
Tree build-up + numerical fitting to term-structure.
Definition at line 60 of file onefactormodel.cpp.
References QuantLib::Solver1D< Impl >::setMaxEvaluations(), QuantLib::TimeGrid::size(), QuantLib::Solver1D< Impl >::solve(), QuantLib::Lattice::t_, and QuantLib::CalibratedModel::value().
    : TreeLattice1D<OneFactorModel::ShortRateTree>(timeGrid, tree->size(1)),
      tree_(tree), dynamics_(dynamics) {
        theta->reset();
        Real value = 1.0;
        Real vMin = -100.0;
        Real vMax = 100.0;
        for (Size i=0; i<(timeGrid.size() - 1); i++) {
            Real discountBond = theta->termStructure()->discount(t_[i+1]);
            Helper finder(i, discountBond, theta, *this);
            Brent s1d;
            s1d.setMaxEvaluations(1000);
            value = s1d.solve(finder, 1e-7, value, vMin, vMax);
            // vMin = value - 1.0;
            // vMax = value + 1.0;
            theta->change(value);
        }
    }
Member Function Documentation
Size QuantLib::OneFactorModel::ShortRateTree::descendant (Size i, Size index, Size branch) const [inline]
Definition at line 100 of file onefactormodel.hpp.
References tree_.
{
            return tree_->descendant(i, index, branch);
        }
DiscountFactor QuantLib::OneFactorModel::ShortRateTree::discount (Size i, Size index) const [inline]
Definition at line 92 of file onefactormodel.hpp.
References QuantLib::anonymous_namespace{yieldtermstructure.cpp}::dt, dynamics_, QuantLib::Lattice::timeGrid(), and tree_.
Referenced by QuantLib::OneFactorModel::ShortRateTree::Helper::operator()().
{
            Real x = tree_->underlying(i, index);
            Rate r = dynamics_->shortRate(timeGrid()[i], x);
            return std::exp(-r*timeGrid().dt(i));
        }
Real QuantLib::OneFactorModel::ShortRateTree::probability (Size i, Size index, Size branch) const [inline]
Definition at line 103 of file onefactormodel.hpp.
References tree_.
{
            return tree_->probability(i, index, branch);
        }
Size QuantLib::OneFactorModel::ShortRateTree::size (Size i) const [inline]
Definition at line 89 of file onefactormodel.hpp.
References tree_.
{
            return tree_->size(i);
        }
Real QuantLib::OneFactorModel::ShortRateTree::underlying (Size i, Size index) const [inline]
Reimplemented from QuantLib::TreeLattice1D< OneFactorModel::ShortRateTree >.
Definition at line 97 of file onefactormodel.hpp.
References tree_.
{
            return tree_->underlying(i, index);
        }
Member Data Documentation
boost::shared_ptr<ShortRateDynamics> QuantLib::OneFactorModel::ShortRateTree::dynamics_ [private]
Definition at line 108 of file onefactormodel.hpp.
Referenced by discount().
boost::shared_ptr<TrinomialTree> QuantLib::OneFactorModel::ShortRateTree::tree_ [private]
Definition at line 107 of file onefactormodel.hpp.
Referenced by descendant(), discount(), probability(), size(), and underlying().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/shortrate/onefactormodel.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/shortrate/onefactormodel.cpp