QuantLib: QuantLib::PricingEngine Class Reference
QuantLib::PricingEngine Class Reference
interface for pricing engines
#include <pricingengine.hpp>
Classes
class arguments
class results
Public Member Functions
virtual ~PricingEngine ()
virtual arguments * getArguments () const =0
virtual const results * getResults () const =0
virtual void reset ()=0
virtual void calculate () const =0
Detailed Description
interface for pricing engines
Definition at line 34 of file pricingengine.hpp.
Constructor & Destructor Documentation
virtual QuantLib::PricingEngine::~PricingEngine () [inline, virtual]
Definition at line 38 of file pricingengine.hpp.
{}
Member Function Documentation
virtual void QuantLib::PricingEngine::calculate () const [pure virtual]
Implemented in QuantLib::MonteCarloCDOEngine2, QuantLib::AnalyticHestonEngine, QuantLib::FDEngineAdapter< FDDividendEngineShiftScale< Scheme >, DividendVanillaOption::engine >, QuantLib::FDEngineAdapter< FDShoutCondition< FDDividendEngine< Scheme > >, DividendVanillaOption::engine >, QuantLib::FDEngineAdapter< FDDividendEngine< Scheme >, DividendVanillaOption::engine >, QuantLib::FDEngineAdapter< FDAmericanCondition< FDStepConditionEngine< Scheme > >, OneAssetOption::engine >, QuantLib::FDEngineAdapter< FDAmericanCondition< FDDividendEngineMerton73< Scheme > >, DividendVanillaOption::engine >, QuantLib::FDEngineAdapter< FDShoutCondition< FDStepConditionEngine< Scheme > >, OneAssetOption::engine >, QuantLib::FDEngineAdapter< FDAmericanCondition< FDDividendEngine< Scheme > >, DividendVanillaOption::engine >, QuantLib::FDEngineAdapter< FDDividendEngineMerton73< Scheme >, DividendVanillaOption::engine >, QuantLib::FDEngineAdapter< FDAmericanCondition< FDDividendEngineShiftScale< Scheme > >, DividendVanillaOption::engine >, QuantLib::FDEngineAdapter< FDShoutCondition< FDDividendEngineMerton73< Scheme > >, DividendVanillaOption::engine >, QuantLib::FDEngineAdapter< FDShoutCondition< FDDividendEngineShiftScale< Scheme > >, DividendVanillaOption::engine >, QuantLib::IntegralCDOEngine, QuantLib::MCHullWhiteCapFloorEngine< RNG, S >, QuantLib::MidPointCDOEngine, QuantLib::AnalyticHestonHullWhiteEngine, QuantLib::MCBarrierEngine< RNG, S >, QuantLib::AnalyticPTDHestonEngine, QuantLib::MCVarianceSwapEngine< RNG, S >, QuantLib::MCLongstaffSchwartzEngine< GenericEngine, MC, RNG, S >, QuantLib::MCLongstaffSchwartzEngine< BasketOption::engine, MultiVariate, RNG >, QuantLib::TreeSwaptionEngine, QuantLib::BinomialVanillaEngine< T >, QuantLib::MCLongstaffSchwartzPathEngine< GenericEngine, MC, RNG, S >, QuantLib::MCLongstaffSchwartzPathEngine< PathMultiAssetOption::engine, MultiVariate, RNG >, QuantLib::MCDiscreteAveragingAsianEngine< RNG, S >, QuantLib::MCEuropeanBasketEngine< RNG, S >, QuantLib::MCPathBasketEngine< RNG, S >, QuantLib::FdHestonHullWhiteVanillaEngine, QuantLib::FdHestonBarrierEngine, QuantLib::AnalyticDigitalAmericanEngine, QuantLib::FdKlugeExtOUSpreadEngine, QuantLib::FdSimpleKlugeExtOUVPPEngine, QuantLib::QuantoEngine< Instr, Engine >, QuantLib::JamshidianSwaptionEngine, QuantLib::AnalyticGJRGARCHEngine, QuantLib::FdBlackScholesVanillaEngine, QuantLib::FdHestonVanillaEngine, QuantLib::BinomialConvertibleEngine< T >, QuantLib::FdBlackScholesBarrierEngine, QuantLib::FDEuropeanEngine< Scheme >, QuantLib::YoYInflationCapFloorEngine, QuantLib::BlackCallableFixedRateBondEngine, QuantLib::TreeCallableFixedRateBondEngine, QuantLib::MCEverestEngine< RNG, S >, QuantLib::MCPagodaEngine< RNG, S >, QuantLib::AnalyticContinuousGeometricAveragePriceAsianEngine, QuantLib::AnalyticDiscreteGeometricAveragePriceAsianEngine, QuantLib::FdHestonRebateEngine, QuantLib::ForwardVanillaEngine< Engine >, QuantLib::TreeVanillaSwapEngine, QuantLib::AnalyticBSMHullWhiteEngine, QuantLib::MCHimalayaEngine< RNG, S >, QuantLib::ReplicatingVarianceSwapEngine, QuantLib::FdSimpleExtOUJumpSwingEngine, QuantLib::FdBlackScholesRebateEngine, QuantLib::Fd2dBlackScholesVanillaEngine, QuantLib::TreeCapFloorEngine, QuantLib::BlackSwaptionEngine, QuantLib::MCPerformanceEngine< RNG, S >, QuantLib::FdBatesVanillaEngine, QuantLib::AnalyticDiscreteGeometricAverageStrikeAsianEngine, QuantLib::FdBlackScholesAsianEngine, QuantLib::AnalyticBarrierEngine, QuantLib::StulzEngine, QuantLib::G2SwaptionEngine, QuantLib::AnalyticCompoundOptionEngine, QuantLib::KirkEngine, QuantLib::BlackCapFloorEngine, QuantLib::AnalyticAmericanMargrabeEngine, QuantLib::AnalyticEuropeanMargrabeEngine, QuantLib::FdExtOUJumpVanillaEngine, QuantLib::AnalyticCapFloorEngine, QuantLib::ForwardPerformanceVanillaEngine< Engine >, QuantLib::AnalyticContinuousFixedLookbackEngine, QuantLib::AnalyticContinuousFloatingLookbackEngine, QuantLib::FdSimpleExtOUStorageEngine, QuantLib::InterpolatingCPICapFloorEngine, QuantLib::FdSimpleBSSwingEngine, QuantLib::AnalyticCliquetEngine, QuantLib::PerturbativeBarrierOptionEngine, QuantLib::FdHullWhiteSwaptionEngine, QuantLib::FdG2SwaptionEngine, QuantLib::AnalyticDividendEuropeanEngine, QuantLib::BlackCdsOptionEngine, QuantLib::IntegralHestonVarianceOptionEngine, QuantLib::AnalyticPerformanceEngine, QuantLib::DiscountingSwapEngine, QuantLib::LfmSwaptionEngine, QuantLib::AnalyticSimpleChooserEngine, QuantLib::DiscountingBondEngine, QuantLib::IntegralCdsEngine, QuantLib::MidPointCdsEngine, QuantLib::ContinuousArithmeticAsianLevyEngine, QuantLib::KirkSpreadOptionEngine, and QuantLib::AnalyticWriterExtensibleOptionEngine.
Referenced by QuantLib::anonymous_namespace{impliedvolatility.cpp}::PriceError::operator()().
virtual arguments* QuantLib::PricingEngine::getArguments () const [pure virtual]
Implemented in QuantLib::GenericEngine< ArgumentsType, ResultsType >, QuantLib::GenericEngine< EnergyCommodity::arguments, EnergyCommodity::results >, QuantLib::GenericEngine< ForwardOptionArguments< VanillaOption::arguments >, VanillaOption::results >, QuantLib::GenericEngine< YearOnYearInflationSwap::arguments, YearOnYearInflationSwap::results >, QuantLib::GenericEngine< CPISwap::arguments, CPISwap::results >, QuantLib::GenericEngine< VanillaSwingOption::arguments, VanillaSwingOption::results >, QuantLib::GenericEngine< VarianceSwap::arguments, VarianceSwap::results >, QuantLib::GenericEngine< PagodaOption::arguments, PagodaOption::results >, QuantLib::GenericEngine< MargrabeOption::arguments, MargrabeOption::results >, QuantLib::GenericEngine< Arguments, Results >, QuantLib::GenericEngine< ContinuousFixedLookbackOption::arguments, ContinuousFixedLookbackOption::results >, QuantLib::GenericEngine< CreditDefaultSwap::arguments, CreditDefaultSwap::results >, QuantLib::GenericEngine< CapFloor::arguments, CapFloor::results >, QuantLib::GenericEngine< VanillaStorageOption::arguments, VanillaStorageOption::results >, QuantLib::GenericEngine< SpreadOption::arguments, SpreadOption::results >, QuantLib::GenericEngine< HimalayaOption::arguments, HimalayaOption::results >, QuantLib::GenericEngine< EverestOption::arguments, EverestOption::results >, QuantLib::GenericEngine< MultiAssetOption::arguments, MultiAssetOption::results >, QuantLib::GenericEngine< CompoundOption::arguments, CompoundOption::results >, QuantLib::GenericEngine< CdsOption::arguments, CdsOption::results >, QuantLib::GenericEngine< SyntheticCDO::arguments, SyntheticCDO::results >, QuantLib::GenericEngine< ContinuousFloatingLookbackOption::arguments, ContinuousFloatingLookbackOption::results >, QuantLib::GenericEngine< CliquetOption::arguments, CliquetOption::results >, QuantLib::GenericEngine< OneAssetOption::arguments, OneAssetOption::results >, QuantLib::GenericEngine< DividendBarrierOption::arguments, DividendBarrierOption::results >, QuantLib::GenericEngine< ContinuousAveragingAsianOption::arguments, ContinuousAveragingAsianOption::results >, QuantLib::GenericEngine< PathMultiAssetOption::arguments, PathMultiAssetOption::results >, QuantLib::GenericEngine< VanillaSwap::arguments, VanillaSwap::results >, QuantLib::GenericEngine< ConvertibleBond::option::arguments, ConvertibleBond::option::results >, QuantLib::GenericEngine< VarianceOption::arguments, VarianceOption::results >, QuantLib::GenericEngine< BarrierOption::arguments, BarrierOption::results >, QuantLib::GenericEngine< VanillaVPPOption::arguments, VanillaVPPOption::results >, QuantLib::GenericEngine< Swaption::arguments, Swaption::results >, QuantLib::GenericEngine< WriterExtensibleOption::arguments, WriterExtensibleOption::results >, QuantLib::GenericEngine< YoYInflationCapFloor::arguments, YoYInflationCapFloor::results >, QuantLib::GenericEngine< CallableBond::arguments, CallableBond::results >, QuantLib::GenericEngine< DiscreteAveragingAsianOption::arguments, DiscreteAveragingAsianOption::results >, QuantLib::GenericEngine< VanillaOption::arguments, VanillaOption::results >, QuantLib::GenericEngine< Swap::arguments, Swap::results >, QuantLib::GenericEngine< Instr::arguments, QuantoOptionResults< Instr::results > >, QuantLib::GenericEngine< Bond::arguments, Bond::results >, QuantLib::GenericEngine< ZeroCouponInflationSwap::arguments, ZeroCouponInflationSwap::results >, QuantLib::GenericEngine< DividendVanillaOption::arguments, DividendVanillaOption::results >, QuantLib::GenericEngine< BasketOption::arguments, BasketOption::results >, QuantLib::GenericEngine< CPICapFloor::arguments, CPICapFloor::results >, and QuantLib::GenericEngine< SimpleChooserOption::arguments, SimpleChooserOption::results >.
Referenced by QuantLib::detail::ImpliedVolatilityHelper::calculate().
virtual const results* QuantLib::PricingEngine::getResults () const [pure virtual]
Implemented in QuantLib::GenericEngine< ArgumentsType, ResultsType >, QuantLib::GenericEngine< EnergyCommodity::arguments, EnergyCommodity::results >, QuantLib::GenericEngine< ForwardOptionArguments< VanillaOption::arguments >, VanillaOption::results >, QuantLib::GenericEngine< YearOnYearInflationSwap::arguments, YearOnYearInflationSwap::results >, QuantLib::GenericEngine< CPISwap::arguments, CPISwap::results >, QuantLib::GenericEngine< VanillaSwingOption::arguments, VanillaSwingOption::results >, QuantLib::GenericEngine< VarianceSwap::arguments, VarianceSwap::results >, QuantLib::GenericEngine< PagodaOption::arguments, PagodaOption::results >, QuantLib::GenericEngine< MargrabeOption::arguments, MargrabeOption::results >, QuantLib::GenericEngine< Arguments, Results >, QuantLib::GenericEngine< ContinuousFixedLookbackOption::arguments, ContinuousFixedLookbackOption::results >, QuantLib::GenericEngine< CreditDefaultSwap::arguments, CreditDefaultSwap::results >, QuantLib::GenericEngine< CapFloor::arguments, CapFloor::results >, QuantLib::GenericEngine< VanillaStorageOption::arguments, VanillaStorageOption::results >, QuantLib::GenericEngine< SpreadOption::arguments, SpreadOption::results >, QuantLib::GenericEngine< HimalayaOption::arguments, HimalayaOption::results >, QuantLib::GenericEngine< EverestOption::arguments, EverestOption::results >, QuantLib::GenericEngine< MultiAssetOption::arguments, MultiAssetOption::results >, QuantLib::GenericEngine< CompoundOption::arguments, CompoundOption::results >, QuantLib::GenericEngine< CdsOption::arguments, CdsOption::results >, QuantLib::GenericEngine< SyntheticCDO::arguments, SyntheticCDO::results >, QuantLib::GenericEngine< ContinuousFloatingLookbackOption::arguments, ContinuousFloatingLookbackOption::results >, QuantLib::GenericEngine< CliquetOption::arguments, CliquetOption::results >, QuantLib::GenericEngine< OneAssetOption::arguments, OneAssetOption::results >, QuantLib::GenericEngine< DividendBarrierOption::arguments, DividendBarrierOption::results >, QuantLib::GenericEngine< ContinuousAveragingAsianOption::arguments, ContinuousAveragingAsianOption::results >, QuantLib::GenericEngine< PathMultiAssetOption::arguments, PathMultiAssetOption::results >, QuantLib::GenericEngine< VanillaSwap::arguments, VanillaSwap::results >, QuantLib::GenericEngine< ConvertibleBond::option::arguments, ConvertibleBond::option::results >, QuantLib::GenericEngine< VarianceOption::arguments, VarianceOption::results >, QuantLib::GenericEngine< BarrierOption::arguments, BarrierOption::results >, QuantLib::GenericEngine< VanillaVPPOption::arguments, VanillaVPPOption::results >, QuantLib::GenericEngine< Swaption::arguments, Swaption::results >, QuantLib::GenericEngine< WriterExtensibleOption::arguments, WriterExtensibleOption::results >, QuantLib::GenericEngine< YoYInflationCapFloor::arguments, YoYInflationCapFloor::results >, QuantLib::GenericEngine< CallableBond::arguments, CallableBond::results >, QuantLib::GenericEngine< DiscreteAveragingAsianOption::arguments, DiscreteAveragingAsianOption::results >, QuantLib::GenericEngine< VanillaOption::arguments, VanillaOption::results >, QuantLib::GenericEngine< Swap::arguments, Swap::results >, QuantLib::GenericEngine< Instr::arguments, QuantoOptionResults< Instr::results > >, QuantLib::GenericEngine< Bond::arguments, Bond::results >, QuantLib::GenericEngine< ZeroCouponInflationSwap::arguments, ZeroCouponInflationSwap::results >, QuantLib::GenericEngine< DividendVanillaOption::arguments, DividendVanillaOption::results >, QuantLib::GenericEngine< BasketOption::arguments, BasketOption::results >, QuantLib::GenericEngine< CPICapFloor::arguments, CPICapFloor::results >, and QuantLib::GenericEngine< SimpleChooserOption::arguments, SimpleChooserOption::results >.
Referenced by QuantLib::anonymous_namespace{impliedvolatility.cpp}::PriceError::PriceError().
virtual void QuantLib::PricingEngine::reset () [pure virtual]
Implemented in QuantLib::GenericEngine< ArgumentsType, ResultsType >, QuantLib::GenericEngine< EnergyCommodity::arguments, EnergyCommodity::results >, QuantLib::GenericEngine< ForwardOptionArguments< VanillaOption::arguments >, VanillaOption::results >, QuantLib::GenericEngine< YearOnYearInflationSwap::arguments, YearOnYearInflationSwap::results >, QuantLib::GenericEngine< CPISwap::arguments, CPISwap::results >, QuantLib::GenericEngine< VanillaSwingOption::arguments, VanillaSwingOption::results >, QuantLib::GenericEngine< VarianceSwap::arguments, VarianceSwap::results >, QuantLib::GenericEngine< PagodaOption::arguments, PagodaOption::results >, QuantLib::GenericEngine< MargrabeOption::arguments, MargrabeOption::results >, QuantLib::GenericEngine< Arguments, Results >, QuantLib::GenericEngine< ContinuousFixedLookbackOption::arguments, ContinuousFixedLookbackOption::results >, QuantLib::GenericEngine< CreditDefaultSwap::arguments, CreditDefaultSwap::results >, QuantLib::GenericEngine< CapFloor::arguments, CapFloor::results >, QuantLib::GenericEngine< VanillaStorageOption::arguments, VanillaStorageOption::results >, QuantLib::GenericEngine< SpreadOption::arguments, SpreadOption::results >, QuantLib::GenericEngine< HimalayaOption::arguments, HimalayaOption::results >, QuantLib::GenericEngine< EverestOption::arguments, EverestOption::results >, QuantLib::GenericEngine< MultiAssetOption::arguments, MultiAssetOption::results >, QuantLib::GenericEngine< CompoundOption::arguments, CompoundOption::results >, QuantLib::GenericEngine< CdsOption::arguments, CdsOption::results >, QuantLib::GenericEngine< SyntheticCDO::arguments, SyntheticCDO::results >, QuantLib::GenericEngine< ContinuousFloatingLookbackOption::arguments, ContinuousFloatingLookbackOption::results >, QuantLib::GenericEngine< CliquetOption::arguments, CliquetOption::results >, QuantLib::GenericEngine< OneAssetOption::arguments, OneAssetOption::results >, QuantLib::GenericEngine< DividendBarrierOption::arguments, DividendBarrierOption::results >, QuantLib::GenericEngine< ContinuousAveragingAsianOption::arguments, ContinuousAveragingAsianOption::results >, QuantLib::GenericEngine< PathMultiAssetOption::arguments, PathMultiAssetOption::results >, QuantLib::GenericEngine< VanillaSwap::arguments, VanillaSwap::results >, QuantLib::GenericEngine< ConvertibleBond::option::arguments, ConvertibleBond::option::results >, QuantLib::GenericEngine< VarianceOption::arguments, VarianceOption::results >, QuantLib::GenericEngine< BarrierOption::arguments, BarrierOption::results >, QuantLib::GenericEngine< VanillaVPPOption::arguments, VanillaVPPOption::results >, QuantLib::GenericEngine< Swaption::arguments, Swaption::results >, QuantLib::GenericEngine< WriterExtensibleOption::arguments, WriterExtensibleOption::results >, QuantLib::GenericEngine< YoYInflationCapFloor::arguments, YoYInflationCapFloor::results >, QuantLib::GenericEngine< CallableBond::arguments, CallableBond::results >, QuantLib::GenericEngine< DiscreteAveragingAsianOption::arguments, DiscreteAveragingAsianOption::results >, QuantLib::GenericEngine< VanillaOption::arguments, VanillaOption::results >, QuantLib::GenericEngine< Swap::arguments, Swap::results >, QuantLib::GenericEngine< Instr::arguments, QuantoOptionResults< Instr::results > >, QuantLib::GenericEngine< Bond::arguments, Bond::results >, QuantLib::GenericEngine< ZeroCouponInflationSwap::arguments, ZeroCouponInflationSwap::results >, QuantLib::GenericEngine< DividendVanillaOption::arguments, DividendVanillaOption::results >, QuantLib::GenericEngine< BasketOption::arguments, BasketOption::results >, QuantLib::GenericEngine< CPICapFloor::arguments, CPICapFloor::results >, and QuantLib::GenericEngine< SimpleChooserOption::arguments, SimpleChooserOption::results >.
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengine.hpp