QuantLib: QuantLib::ConvergenceStatistics< T, U > Class Template Reference
QuantLib::ConvergenceStatistics< T, U > Class Template Reference
statistics class with convergence table
#include <convergencestatistics.hpp>
Public Types
typedef T::value_type value_type
typedef std::vector< std::pair
< Size, value_type > > table_type
Public Member Functions
ConvergenceStatistics (const T &stats, const U &rule=U())
ConvergenceStatistics (const U &rule=U())
void add (const value_type &value, Real weight=1.0)
template<class DataIterator >
void addSequence (DataIterator begin, DataIterator end)
template<class DataIterator , class WeightIterator >
void addSequence (DataIterator begin, DataIterator end, WeightIterator wbegin)
void reset ()
const std::vector< std::pair
< Size, value_type > > & convergenceTable () const
Private Attributes
table_type table_
U samplingRule_
Size nextSampleSize_
Detailed Description
template<class T, class U = DoublingConvergenceSteps>
class QuantLib::ConvergenceStatistics< T, U >
statistics class with convergence table
This class decorates another statistics class adding a convergence table calculation. The table tracks the convergence of the mean.
It is possible to specify the number of samples at which the mean should be stored by mean of the second template parameter; the default is to store \(2^{n-1} \) samples at the \(n \)-th step. Any passed class must implement the following interface:
        Size initialSamples() const;
        Size nextSamples(Size currentSamples) const;
as well as a copy constructor.
Test:
results are tested against known good values.
Definition at line 58 of file convergencestatistics.hpp.
Member Typedef Documentation
template<class T, class U = DoublingConvergenceSteps> typedef std::vector<std::pair<Size,value_type> > QuantLib::ConvergenceStatistics< T, U >::table_type
Definition at line 61 of file convergencestatistics.hpp.
template<class T, class U = DoublingConvergenceSteps> typedef T::value_type QuantLib::ConvergenceStatistics< T, U >::value_type
Definition at line 60 of file convergencestatistics.hpp.
Constructor & Destructor Documentation
template<class T , class U > QuantLib::ConvergenceStatistics< T, U >::ConvergenceStatistics (const T & stats, const U & rule = U())
Definition at line 90 of file convergencestatistics.hpp.
References QuantLib::ConvergenceStatistics< T, U >::reset().
    : T(stats), samplingRule_(rule) {
        reset();
    }
template<class T , class U > QuantLib::ConvergenceStatistics< T, U >::ConvergenceStatistics (const U & rule = U())
Definition at line 97 of file convergencestatistics.hpp.
References QuantLib::ConvergenceStatistics< T, U >::reset().
    : samplingRule_(rule) {
        reset();
    }
Member Function Documentation
template<class T, class U = DoublingConvergenceSteps> void QuantLib::ConvergenceStatistics< T, U >::add (const value_type & value, Real weight = 1.0)
Definition at line 104 of file convergencestatistics.hpp.
References anonymous_namespace{quotes.cpp}::add().
Referenced by QuantLib::ConvergenceStatistics< T, U >::addSequence(), and anonymous_namespace{stats.cpp}::checkConvergence().
{
        T::add(value,weight);
        if (this->samples() == nextSampleSize_) {
            table_.push_back(std::make_pair(this->samples(),this->mean()));
            nextSampleSize_ = samplingRule_.nextSamples(nextSampleSize_);
        }
    }
template<class T, class U = DoublingConvergenceSteps> template<class DataIterator > void QuantLib::ConvergenceStatistics< T, U >::addSequence (DataIterator begin, DataIterator end) [inline]
Definition at line 67 of file convergencestatistics.hpp.
References QuantLib::ConvergenceStatistics< T, U >::add().
{
            for (; begin != end; ++begin)
                add(*begin);
        }
template<class T, class U = DoublingConvergenceSteps> template<class DataIterator , class WeightIterator > void QuantLib::ConvergenceStatistics< T, U >::addSequence (DataIterator begin, DataIterator end, WeightIterator wbegin) [inline]
Definition at line 72 of file convergencestatistics.hpp.
References QuantLib::ConvergenceStatistics< T, U >::add().
{
            for (; begin != end; ++begin, ++wbegin)
                add(*begin,*wbegin);
        }
template<class T , class U > const ConvergenceStatistics< T, U >::table_type & QuantLib::ConvergenceStatistics< T, U >::convergenceTable () const
Definition at line 124 of file convergencestatistics.hpp.
Referenced by anonymous_namespace{stats.cpp}::checkConvergence().
{
        return table_;
    }
template<class T , class U > void QuantLib::ConvergenceStatistics< T, U >::reset ()
Definition at line 116 of file convergencestatistics.hpp.
References anonymous_namespace{inflationvolatility.cpp}::reset().
Referenced by anonymous_namespace{stats.cpp}::checkConvergence(), and QuantLib::ConvergenceStatistics< T, U >::ConvergenceStatistics().
{
        T::reset();
        nextSampleSize_ = samplingRule_.initialSamples();
        table_.clear();
    }
Member Data Documentation
template<class T, class U = DoublingConvergenceSteps> Size QuantLib::ConvergenceStatistics< T, U >::nextSampleSize_ [private]
Definition at line 83 of file convergencestatistics.hpp.
template<class T, class U = DoublingConvergenceSteps> U QuantLib::ConvergenceStatistics< T, U >::samplingRule_ [private]
Definition at line 82 of file convergencestatistics.hpp.
template<class T, class U = DoublingConvergenceSteps> table_type QuantLib::ConvergenceStatistics< T, U >::table_ [private]
Definition at line 81 of file convergencestatistics.hpp.
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/statistics/convergencestatistics.hpp