QuantLib: QuantLib::DigitalCoupon Class Reference
QuantLib::DigitalCoupon Class Reference
Digital-payoff coupon.
#include <digitalcoupon.hpp>
Public Member Functions
Constructors
DigitalCoupon (const boost::shared_ptr< FloatingRateCoupon > &underlying, Rate callStrike=Null< Rate >(), Position::Type callPosition=Position::Long, bool isCallITMIncluded=false, Rate callDigitalPayoff=Null< Rate >(), Rate putStrike=Null< Rate >(), Position::Type putPosition=Position::Long, bool isPutITMIncluded=false, Rate putDigitalPayoff=Null< Rate >(), const boost::shared_ptr< DigitalReplication > &replication=boost::shared_ptr< DigitalReplication >())
general constructor
Coupon interface
Rate rate () const
accrued rate
Rate convexityAdjustment () const
convexity adjustment
Digital inspectors
Rate callStrike () const
Rate putStrike () const
Rate callDigitalPayoff () const
Rate putDigitalPayoff () const
bool hasPut () const
bool hasCall () const
bool hasCollar () const
bool isLongPut () const
bool isLongCall () const
boost::shared_ptr
< FloatingRateCoupon > underlying () const
Rate callOptionRate () const
Rate putOptionRate () const
Observer interface
void update ()
Visitability
virtual void accept (AcyclicVisitor &)
void setPricer (const boost::shared_ptr< FloatingRateCouponPricer > &pricer)
Protected Attributes
Data members
boost::shared_ptr
< FloatingRateCoupon > underlying_
Rate callStrike_
strike rate for the the call option
Rate putStrike_
strike rate for the the put option
Real callCsi_
multiplicative factor of call payoff
Real putCsi_
multiplicative factor of put payoff
bool isCallATMIncluded_
inclusion flag og the call payoff if the call option ends at-the-money
bool isPutATMIncluded_
inclusion flag og the put payoff if the put option ends at-the-money
bool isCallCashOrNothing_
digital call option type: if true, cash-or-nothing, if false asset-or-nothing
bool isPutCashOrNothing_
digital put option type: if true, cash-or-nothing, if false asset-or-nothing
Rate callDigitalPayoff_
digital call option payoff rate, if any
Rate putDigitalPayoff_
digital put option payoff rate, if any
Real callLeftEps_
the left and right gaps applied in payoff replication for call
Real callRightEps_
Real putLeftEps_
the left and right gaps applied in payoff replication for puf
Real putRightEps_
bool hasPutStrike_
bool hasCallStrike_
Replication::Type replicationType_
Type of replication.
Private Member Functions
Rate callPayoff () const
Rate putPayoff () const
Detailed Description
Digital-payoff coupon.
Implementation of a floating-rate coupon with digital call/put option. Payoffs:
Coupon with cash-or-nothing Digital Call rate + csi * payoffRate * Heaviside(rate-strike)
Coupon with cash-or-nothing Digital Put rate + csi * payoffRate * Heaviside(strike-rate) where csi=+1 or csi=-1.
Coupon with asset-or-nothing Digital Call rate + csi * rate * Heaviside(rate-strike)
Coupon with asset-or-nothing Digital Put rate + csi * rate * Heaviside(strike-rate) where csi=+1 or csi=-1. The evaluation of the coupon is made using the call/put spread replication method.
Test:
the correctness of the returned value in case of Asset-or-nothing embedded option is tested by pricing the digital option with Cox-Rubinstein formula.
the correctness of the returned value in case of deep-in-the-money Asset-or-nothing embedded option is tested vs the expected values of coupon and option.
the correctness of the returned value in case of deep-out-of-the-money Asset-or-nothing embedded option is tested vs the expected values of coupon and option.
the correctness of the returned value in case of Cash-or-nothing embedded option is tested by pricing the digital option with Reiner-Rubinstein formula.
the correctness of the returned value in case of deep-in-the-money Cash-or-nothing embedded option is tested vs the expected values of coupon and option.
the correctness of the returned value in case of deep-out-of-the-money Cash-or-nothing embedded option is tested vs the expected values of coupon and option.
the correctness of the returned value is tested checking the correctness of the call-put parity relation.
the correctness of the returned value is tested by the relationship between prices in case of different replication types.
Definition at line 78 of file digitalcoupon.hpp.
Constructor & Destructor Documentation
QuantLib::DigitalCoupon::DigitalCoupon (const boost::shared_ptr< FloatingRateCoupon > & underlying, Rate callStrike = Null<Rate>(), Position::Type callPosition = Position::Long, bool isCallITMIncluded = false, Rate callDigitalPayoff = Null<Rate>(), Rate putStrike = Null<Rate>(), Position::Type putPosition = Position::Long, bool isPutITMIncluded = false, Rate putDigitalPayoff = Null<Rate>(), const boost::shared_ptr< DigitalReplication > & replication = boost::shared_ptr<DigitalReplication>())
general constructor
Definition at line 28 of file digitalcoupon.cpp.
References callCsi_, callDigitalPayoff(), callDigitalPayoff_, callLeftEps_, callRightEps_, callStrike(), callStrike_, QuantLib::Replication::Central, hasCallStrike_, hasPutStrike_, isCallCashOrNothing_, isPutCashOrNothing_, QuantLib::Position::Long, putCsi_, putDigitalPayoff(), putDigitalPayoff_, putLeftEps_, putRightEps_, putStrike(), putStrike_, QL_FAIL, QL_REQUIRE, QuantLib::Observer::registerWith(), replicationType_, QuantLib::Position::Short, QuantLib::Replication::Sub, and QuantLib::Replication::Super.
    : FloatingRateCoupon(underlying->date(),
                         underlying->nominal(),
                         underlying->accrualStartDate(),
                         underlying->accrualEndDate(),
                         underlying->fixingDays(),
                         underlying->index(),
                         underlying->gearing(),
                         underlying->spread(),
                         underlying->referencePeriodStart(),
                         underlying->referencePeriodEnd(),
                         underlying->dayCounter(),
                         underlying->isInArrears()),
      underlying_(underlying), callCsi_(0.), putCsi_(0.),
      isCallATMIncluded_(isCallATMIncluded), isPutATMIncluded_(isPutATMIncluded),
      isCallCashOrNothing_(false), isPutCashOrNothing_(false),
      callLeftEps_(replication->gap()/2.), callRightEps_(replication->gap()/2.),
      putLeftEps_(replication->gap()/2.), putRightEps_(replication->gap()/2.),
      hasPutStrike_(false), hasCallStrike_(false),
      replicationType_(replication->replicationType()) {
        QL_REQUIRE(replication->gap()>0.0, "Non positive epsilon not allowed");
        if (putStrike == Null<Rate>()) {
            QL_REQUIRE(putDigitalPayoff == Null<Rate>(),
            "Put Cash rate non allowed if put strike is null");
        }
        if (callStrike == Null<Rate>()) {
            QL_REQUIRE(callDigitalPayoff == Null<Rate>(),
            "Call Cash rate non allowed if call strike is null");
        }
        if (callStrike != Null<Rate>()) {
            QL_REQUIRE(callStrike >= 0., "negative call strike not allowed");
            hasCallStrike_ = true;
            callStrike_ = callStrike;
            QL_REQUIRE(callStrike_>=replication->gap()/2., "call strike < eps/2");
            switch (callPosition) {
                case Position::Long :
                    callCsi_ = 1.0;
                    break;
                case Position::Short :
                    callCsi_ = -1.0;
                    break;
                default:
                    QL_FAIL("unsupported position type");
            }
            if (callDigitalPayoff != Null<Rate>()){
                callDigitalPayoff_ = callDigitalPayoff;
                isCallCashOrNothing_ = true;
            }
        }
        if (putStrike != Null<Rate>()){
            QL_REQUIRE(putStrike >= 0., "negative put strike not allowed");
            hasPutStrike_ = true;
            putStrike_ = putStrike;
            switch (putPosition) {
                case Position::Long :
                    putCsi_ = 1.0;
                    break;
                case Position::Short :
                    putCsi_ = -1.0;
                    break;
                default:
                    QL_FAIL("unsupported position type");
            }
            if (putDigitalPayoff != Null<Rate>()){
                putDigitalPayoff_ = putDigitalPayoff;
                isPutCashOrNothing_ = true;
            }
        }
        switch (replicationType_) {
          case Replication::Central :
            // do nothing
            break;
          case Replication::Sub :
            if (hasCallStrike_) {
                switch (callPosition) {
                    case Position::Long :
                        callLeftEps_ = 0.;
                        callRightEps_ = replication->gap();
                        break;
                    case Position::Short :
                        callLeftEps_ = replication->gap();
                        callRightEps_ = 0.;
                        break;
                    default:
                        QL_FAIL("unsupported position type");
                }
            }
            if (hasPutStrike_) {
                switch (putPosition) {
                    case Position::Long :
                        putLeftEps_ = replication->gap();
                        putRightEps_ = 0.;
                        break;
                    case Position::Short :
                        putLeftEps_ = 0.;
                        putRightEps_ = replication->gap();
                        break;
                    default:
                        QL_FAIL("unsupported position type");
                }
            }
            break;
          case Replication::Super :
            if (hasCallStrike_) {
                switch (callPosition) {
                    case Position::Long :
                        callLeftEps_ = replication->gap();
                        callRightEps_ = 0.;
                        break;
                    case Position::Short :
                        callLeftEps_ = 0.;
                        callRightEps_ = replication->gap();
                        break;
                    default:
                        QL_FAIL("unsupported position type");
                }
            }
            if (hasPutStrike_) {
                switch (putPosition) {
                    case Position::Long :
                        putLeftEps_ = 0.;
                        putRightEps_ = replication->gap();
                        break;
                    case Position::Short :
                        putLeftEps_ = replication->gap();
                        putRightEps_ = 0.;
                        break;
                    default:
                        QL_FAIL("unsupported position type");
                }
            }
            break;
          default:
            QL_FAIL("unsupported replication type");
        }
        registerWith(underlying);
    }
Member Function Documentation
void QuantLib::DigitalCoupon::accept (AcyclicVisitor & v) [virtual]
Reimplemented from QuantLib::FloatingRateCoupon.
Reimplemented in QuantLib::DigitalCmsCoupon, and QuantLib::DigitalIborCoupon.
Definition at line 284 of file digitalcoupon.cpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Visitor< T >::visit().
{
        typedef FloatingRateCoupon super;
        Visitor<DigitalCoupon>* v1 =
            dynamic_cast<Visitor<DigitalCoupon>*>(&v);
        if (v1 != 0)
            v1->visit(*this);
        else
            super::accept(v);
    }
Rate QuantLib::DigitalCoupon::callDigitalPayoff () const
Definition at line 266 of file digitalcoupon.cpp.
References callDigitalPayoff_, and isCallCashOrNothing_.
Referenced by DigitalCoupon().
{
        if (isCallCashOrNothing_)
            return callDigitalPayoff_;
        else
            return Null<Rate>();
    }
Rate QuantLib::DigitalCoupon::callOptionRate () const
Returns the call option rate (multiplied by: nominal*accrualperiod*discount is the NPV of the option)
Definition at line 180 of file digitalcoupon.cpp.
References callDigitalPayoff_, callLeftEps_, callRightEps_, callStrike_, hasCallStrike_, isCallCashOrNothing_, QuantLib::CappedFlooredCoupon::rate(), and underlying_.
Referenced by rate(), DigitalCouponTest::testAssetOrNothing(), DigitalCouponTest::testAssetOrNothingDeepInTheMoney(), DigitalCouponTest::testAssetOrNothingDeepOutTheMoney(), DigitalCouponTest::testCashOrNothing(), DigitalCouponTest::testCashOrNothingDeepInTheMoney(), and DigitalCouponTest::testCashOrNothingDeepOutTheMoney().
{
        Rate callOptionRate = Rate(0.);
        if(hasCallStrike_) {
            // Step function
            callOptionRate = isCallCashOrNothing_ ? callDigitalPayoff_ : callStrike_;
            CappedFlooredCoupon next(underlying_, callStrike_ + callRightEps_);
            CappedFlooredCoupon previous(underlying_, callStrike_ - callLeftEps_);
            callOptionRate *= (next.rate() - previous.rate())
                            / (callLeftEps_ + callRightEps_);
            if (!isCallCashOrNothing_) {
                // Call
                CappedFlooredCoupon atStrike(underlying_, callStrike_);
                Rate call = underlying_->rate() - atStrike.rate();
                // Sum up
                callOptionRate += call;
            }
        }
        return callOptionRate;
    }
Rate QuantLib::DigitalCoupon::callPayoff () const [private]
Definition at line 294 of file digitalcoupon.cpp.
References callDigitalPayoff_, callStrike_, hasCallStrike_, isCallATMIncluded_, isCallCashOrNothing_, and underlying_.
Referenced by rate().
{
        // to use only if index has fixed
        Rate payoff(0.);
        if(hasCallStrike_) {
            Rate underlyingRate = underlying_->rate();
            if ( (underlyingRate - callStrike_) > 1.e-16 ) {
                payoff = isCallCashOrNothing_ ? callDigitalPayoff_ : underlyingRate;
            } else {
                if (isCallATMIncluded_) {
                    if ( std::abs(callStrike_ - underlyingRate) <= 1.e-16 )
                        payoff = isCallCashOrNothing_ ? callDigitalPayoff_ : underlyingRate;
                }
            }
        }
        return payoff;
    }
Rate QuantLib::DigitalCoupon::callStrike () const
Definition at line 252 of file digitalcoupon.cpp.
References callStrike_, and hasCall().
Referenced by DigitalCoupon().
{
        if (hasCall())
            return callStrike_;
        else
            return Null<Rate>();
   }
Rate QuantLib::DigitalCoupon::convexityAdjustment () const [virtual]
convexity adjustment
Reimplemented from QuantLib::FloatingRateCoupon.
Definition at line 248 of file digitalcoupon.cpp.
References underlying_.
{
        return underlying_->convexityAdjustment();
    }
bool QuantLib::DigitalCoupon::hasCall () const [inline]
Definition at line 109 of file digitalcoupon.hpp.
References hasCallStrike_.
Referenced by callStrike().
{return hasCallStrike_; }
bool QuantLib::DigitalCoupon::hasCollar () const [inline]
Definition at line 110 of file digitalcoupon.hpp.
References hasCallStrike_, and hasPutStrike_.
{return (hasCallStrike_ && hasPutStrike_); }
bool QuantLib::DigitalCoupon::hasPut () const [inline]
Definition at line 108 of file digitalcoupon.hpp.
References hasPutStrike_.
Referenced by putStrike().
{ return hasPutStrike_; }
bool QuantLib::DigitalCoupon::isLongCall () const [inline]
Definition at line 112 of file digitalcoupon.hpp.
References callCsi_.
{ return (callCsi_==1.); }
bool QuantLib::DigitalCoupon::isLongPut () const [inline]
Definition at line 111 of file digitalcoupon.hpp.
References putCsi_.
{ return (putCsi_==1.); }
Rate QuantLib::DigitalCoupon::putDigitalPayoff () const
Definition at line 273 of file digitalcoupon.cpp.
References isPutCashOrNothing_, and putDigitalPayoff_.
Referenced by DigitalCoupon().
{
        if (isPutCashOrNothing_)
            return putDigitalPayoff_;
        else
            return Null<Rate>();
    }
Rate QuantLib::DigitalCoupon::putOptionRate () const
Returns the put option rate (multiplied by: nominal*accrualperiod*discount is the NPV of the option)
Definition at line 201 of file digitalcoupon.cpp.
References hasPutStrike_, isPutCashOrNothing_, putDigitalPayoff_, putLeftEps_, putRightEps_, putStrike_, QuantLib::CappedFlooredCoupon::rate(), and underlying_.
Referenced by rate(), DigitalCouponTest::testAssetOrNothing(), DigitalCouponTest::testAssetOrNothingDeepInTheMoney(), DigitalCouponTest::testAssetOrNothingDeepOutTheMoney(), DigitalCouponTest::testCashOrNothing(), DigitalCouponTest::testCashOrNothingDeepInTheMoney(), and DigitalCouponTest::testCashOrNothingDeepOutTheMoney().
{
        Rate putOptionRate = Rate(0.);
        if(hasPutStrike_) {
            // Step function
            putOptionRate = isPutCashOrNothing_ ? putDigitalPayoff_ : putStrike_;
            CappedFlooredCoupon next(underlying_, Null<Rate>(), putStrike_ + putRightEps_);
            CappedFlooredCoupon previous(underlying_, Null<Rate>(), putStrike_ - putLeftEps_);
            putOptionRate *= (next.rate() - previous.rate())
                           / (putLeftEps_ + putRightEps_);
            if (!isPutCashOrNothing_) {
                // Put
                CappedFlooredCoupon atStrike(underlying_, Null<Rate>(), putStrike_);
                Rate put = - underlying_->rate() + atStrike.rate();
                // Sum up
                putOptionRate -= put;
            }
        }
        return putOptionRate;
    }
Rate QuantLib::DigitalCoupon::putPayoff () const [private]
Definition at line 311 of file digitalcoupon.cpp.
References hasPutStrike_, isPutATMIncluded_, isPutCashOrNothing_, putDigitalPayoff_, putStrike_, and underlying_.
Referenced by rate().
{
        // to use only if index has fixed
        Rate payoff(0.);
        if(hasPutStrike_) {
            Rate underlyingRate = underlying_->rate();
            if ( (putStrike_ - underlyingRate) > 1.e-16 ) {
                payoff = isPutCashOrNothing_ ? putDigitalPayoff_ : underlyingRate;
            } else {
                // putStrike_ <= underlyingRate
                if (isPutATMIncluded_) {
                    if ( std::abs(putStrike_ - underlyingRate) <= 1.e-16 )
                        payoff = isPutCashOrNothing_ ? putDigitalPayoff_ : underlyingRate;
                }
            }
        }
        return payoff;
    }
Rate QuantLib::DigitalCoupon::putStrike () const
Definition at line 259 of file digitalcoupon.cpp.
References hasPut(), and putStrike_.
Referenced by DigitalCoupon().
{
        if (hasPut())
            return putStrike_;
        else
            return Null<Rate>();
    }
Rate QuantLib::DigitalCoupon::rate () const [virtual]
accrued rate
Reimplemented from QuantLib::FloatingRateCoupon.
Definition at line 222 of file digitalcoupon.cpp.
References callCsi_, callOptionRate(), callPayoff(), QuantLib::Settings::enforcesTodaysHistoricFixings(), QuantLib::Settings::evaluationDate(), QuantLib::FloatingRateCoupon::fixingDate(), QuantLib::IndexManager::getHistory(), QuantLib::Singleton< Settings >::instance(), QuantLib::Singleton< IndexManager >::instance(), putCsi_, putOptionRate(), putPayoff(), QL_REQUIRE, and underlying_.
{
        QL_REQUIRE(underlying_->pricer(), "pricer not set");
        Date fixingDate = underlying_->fixingDate();
        Date today = Settings::instance().evaluationDate();
        bool enforceTodaysHistoricFixings =
            Settings::instance().enforcesTodaysHistoricFixings();
        Rate underlyingRate = underlying_->rate();
        if (fixingDate < today ||
            ((fixingDate == today) && enforceTodaysHistoricFixings)) {
            // must have been fixed
            return underlyingRate + callCsi_ * callPayoff() + putCsi_  * putPayoff();
        }
        if (fixingDate == today) {
            // might have been fixed
            Rate pastFixing =
                IndexManager::instance().getHistory((underlying_->index())->name())[fixingDate];
            if (pastFixing != Null<Real>()) {
                return underlyingRate + callCsi_ * callPayoff() + putCsi_  * putPayoff();
            } else
                return underlyingRate + callCsi_ * callOptionRate() + putCsi_ * putOptionRate();
        }
        return underlyingRate + callCsi_ * callOptionRate() + putCsi_ * putOptionRate();
    }
void QuantLib::DigitalCoupon::setPricer (const boost::shared_ptr< FloatingRateCouponPricer > & pricer) [inline]
Reimplemented from QuantLib::FloatingRateCoupon.
Definition at line 131 of file digitalcoupon.hpp.
References QuantLib::FloatingRateCoupon::pricer(), QuantLib::FloatingRateCoupon::pricer_, QuantLib::Observer::registerWith(), underlying_, QuantLib::Observer::unregisterWith(), and update().
Referenced by DigitalCouponTest::testAssetOrNothing(), DigitalCouponTest::testAssetOrNothingDeepInTheMoney(), DigitalCouponTest::testAssetOrNothingDeepOutTheMoney(), DigitalCouponTest::testCallPutParity(), DigitalCouponTest::testCashOrNothing(), DigitalCouponTest::testCashOrNothingDeepInTheMoney(), DigitalCouponTest::testCashOrNothingDeepOutTheMoney(), DigitalCouponTest::testReplicationType(), and QuantLib::anonymous_namespace{couponpricer.cpp}::PricerSetter::visit().
{
            if (pricer_)
                unregisterWith(pricer_);
            pricer_ = pricer;
            if (pricer_)
                registerWith(pricer_);
            update();
            underlying_->setPricer(pricer);
        }
boost::shared_ptr<FloatingRateCoupon> QuantLib::DigitalCoupon::underlying () const [inline]
Definition at line 113 of file digitalcoupon.hpp.
References underlying_.
{ return underlying_; }
void QuantLib::DigitalCoupon::update () [virtual]
This method must be implemented in derived classes. An instance of Observer does not call this method directly: instead, it will be called by the observables the instance registered with when they need to notify any changes.
Reimplemented from QuantLib::FloatingRateCoupon.
Definition at line 280 of file digitalcoupon.cpp.
References QuantLib::Observable::notifyObservers().
Referenced by setPricer().
{
        notifyObservers();
    }
Member Data Documentation
Real QuantLib::DigitalCoupon::callCsi_ [protected]
multiplicative factor of call payoff
Definition at line 152 of file digitalcoupon.hpp.
Referenced by DigitalCoupon(), isLongCall(), and rate().
Rate QuantLib::DigitalCoupon::callDigitalPayoff_ [protected]
digital call option payoff rate, if any
Definition at line 164 of file digitalcoupon.hpp.
Referenced by callDigitalPayoff(), callOptionRate(), callPayoff(), and DigitalCoupon().
Real QuantLib::DigitalCoupon::callLeftEps_ [protected]
the left and right gaps applied in payoff replication for call
Definition at line 168 of file digitalcoupon.hpp.
Referenced by callOptionRate(), and DigitalCoupon().
Real QuantLib::DigitalCoupon::callRightEps_ [protected]
Definition at line 168 of file digitalcoupon.hpp.
Referenced by callOptionRate(), and DigitalCoupon().
Rate QuantLib::DigitalCoupon::callStrike_ [protected]
strike rate for the the call option
Definition at line 148 of file digitalcoupon.hpp.
Referenced by callOptionRate(), callPayoff(), callStrike(), and DigitalCoupon().
bool QuantLib::DigitalCoupon::hasCallStrike_ [protected]
Definition at line 172 of file digitalcoupon.hpp.
Referenced by callOptionRate(), callPayoff(), DigitalCoupon(), hasCall(), and hasCollar().
bool QuantLib::DigitalCoupon::hasPutStrike_ [protected]
Definition at line 172 of file digitalcoupon.hpp.
Referenced by DigitalCoupon(), hasCollar(), hasPut(), putOptionRate(), and putPayoff().
bool QuantLib::DigitalCoupon::isCallATMIncluded_ [protected]
inclusion flag og the call payoff if the call option ends at-the-money
Definition at line 156 of file digitalcoupon.hpp.
Referenced by callPayoff().
bool QuantLib::DigitalCoupon::isCallCashOrNothing_ [protected]
digital call option type: if true, cash-or-nothing, if false asset-or-nothing
Definition at line 160 of file digitalcoupon.hpp.
Referenced by callDigitalPayoff(), callOptionRate(), callPayoff(), and DigitalCoupon().
bool QuantLib::DigitalCoupon::isPutATMIncluded_ [protected]
inclusion flag og the put payoff if the put option ends at-the-money
Definition at line 158 of file digitalcoupon.hpp.
Referenced by putPayoff().
bool QuantLib::DigitalCoupon::isPutCashOrNothing_ [protected]
digital put option type: if true, cash-or-nothing, if false asset-or-nothing
Definition at line 162 of file digitalcoupon.hpp.
Referenced by DigitalCoupon(), putDigitalPayoff(), putOptionRate(), and putPayoff().
Real QuantLib::DigitalCoupon::putCsi_ [protected]
multiplicative factor of put payoff
Definition at line 154 of file digitalcoupon.hpp.
Referenced by DigitalCoupon(), isLongPut(), and rate().
Rate QuantLib::DigitalCoupon::putDigitalPayoff_ [protected]
digital put option payoff rate, if any
Definition at line 166 of file digitalcoupon.hpp.
Referenced by DigitalCoupon(), putDigitalPayoff(), putOptionRate(), and putPayoff().
Real QuantLib::DigitalCoupon::putLeftEps_ [protected]
the left and right gaps applied in payoff replication for puf
Definition at line 170 of file digitalcoupon.hpp.
Referenced by DigitalCoupon(), and putOptionRate().
Real QuantLib::DigitalCoupon::putRightEps_ [protected]
Definition at line 170 of file digitalcoupon.hpp.
Referenced by DigitalCoupon(), and putOptionRate().
Rate QuantLib::DigitalCoupon::putStrike_ [protected]
strike rate for the the put option
Definition at line 150 of file digitalcoupon.hpp.
Referenced by DigitalCoupon(), putOptionRate(), putPayoff(), and putStrike().
Replication::Type QuantLib::DigitalCoupon::replicationType_ [protected]
Type of replication.
Definition at line 174 of file digitalcoupon.hpp.
Referenced by DigitalCoupon().
boost::shared_ptr<FloatingRateCoupon> QuantLib::DigitalCoupon::underlying_ [protected]
Definition at line 146 of file digitalcoupon.hpp.
Referenced by callOptionRate(), callPayoff(), convexityAdjustment(), putOptionRate(), putPayoff(), rate(), setPricer(), and underlying().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/digitalcoupon.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/digitalcoupon.cpp