QuantLib: QuantLib::TqrEigenDecomposition Class Reference
QuantLib::TqrEigenDecomposition Class Reference
tridiag. QR eigen decomposition with explicite shift aka Wilkinson
#include <tqreigendecomposition.hpp>
Public Types
enum EigenVectorCalculation { WithEigenVector, WithoutEigenVector, OnlyFirstRowEigenVector }
enum ShiftStrategy { NoShift, Overrelaxation, CloseEigenValue }
Public Member Functions
TqrEigenDecomposition (const Array &diag, const Array &sub, EigenVectorCalculation calc=WithEigenVector, ShiftStrategy strategy=CloseEigenValue)
const Array & eigenvalues () const
const Matrix & eigenvectors () const
Size iterations () const
Private Member Functions
bool offDiagIsZero (Size k, Array &e)
Private Attributes
Size iter_
Array d_
Matrix ev_
Detailed Description
tridiag. QR eigen decomposition with explicite shift aka Wilkinson
References:
Wilkinson, J.H. and Reinsch, C. 1971, Linear Algebra, vol. II of Handbook for Automatic Computation (New York: Springer-Verlag)
"Numerical Recipes in C", 2nd edition, Press, Teukolsky, Vetterling, Flannery,
Test:
the correctness of the result is tested by checking it against known good values.
Definition at line 44 of file tqreigendecomposition.hpp.
Member Enumeration Documentation
enum QuantLib::TqrEigenDecomposition::EigenVectorCalculation
Enumerator:
WithEigenVector
WithoutEigenVector
OnlyFirstRowEigenVector
Definition at line 46 of file tqreigendecomposition.hpp.
                                    { WithEigenVector,
                                      WithoutEigenVector,
                                      OnlyFirstRowEigenVector };
enum QuantLib::TqrEigenDecomposition::ShiftStrategy
Enumerator:
NoShift
Overrelaxation
CloseEigenValue
Definition at line 50 of file tqreigendecomposition.hpp.
                           { NoShift,
                             Overrelaxation,
                             CloseEigenValue };
Constructor & Destructor Documentation
QuantLib::TqrEigenDecomposition::TqrEigenDecomposition (const Array & diag, const Array & sub, EigenVectorCalculation calc = WithEigenVector, ShiftStrategy strategy = CloseEigenValue)
Definition at line 29 of file tqreigendecomposition.cpp.
References QuantLib::Array::begin(), CloseEigenValue, QuantLib::Matrix::column_begin(), QuantLib::Matrix::column_end(), d_, QuantLib::Array::end(), ev_, iter_, NoShift, offDiagIsZero(), QL_REQUIRE, QuantLib::Matrix::rows(), QuantLib::anonymous_namespace{cashflows.cpp}::sign(), QuantLib::Array::size(), and anonymous_namespace{quantlibbenchmark.cpp}::t.
    : iter_(0), d_(diag),
      ev_((calc == WithEigenVector)? d_.size() :
          (calc == WithoutEigenVector)? 0 : 1, d_.size(), 0)
    {
        Size n = diag.size();
        QL_REQUIRE(n == sub.size()+1, "Wrong dimensions");
        Array e(n, 0.0);
        std::copy(sub.begin(),sub.end(),e.begin()+1);
        Size i;
        for (i=0; i < ev_.rows(); ++i) {
            ev_[i][i] = 1.0;
        }
        for (Size k=n-1; k >=1; --k) {
            while (!offDiagIsZero(k, e)) {
                Size l = k;
                while (--l > 0 && !offDiagIsZero(l,e));
                iter_++;
                Real q = d_[l];
                if (strategy != NoShift) {
                    // calculated eigenvalue of 2x2 sub matrix of
                    // [ d_[k-1] e_[k] ]
                    // [  e_[k]  d_[k] ]
                    // which is closer to d_[k+1].
                    // FLOATING_POINT_EXCEPTION
                    const Real t1 = std::sqrt(
                                          0.25*(d_[k]*d_[k] + d_[k-1]*d_[k-1])
                                          - 0.5*d_[k-1]*d_[k] + e[k]*e[k]);
                    const Real t2 = 0.5*(d_[k]+d_[k-1]);
                    const Real lambda =
                        (std::fabs(t2+t1 - d_[k]) < std::fabs(t2-t1 - d_[k]))?
                        t2+t1 : t2-t1;
                    if (strategy == CloseEigenValue) {
                        q-=lambda;
                    } else {
                        q-=((k==n-1)? 1.25 : 1.0)*lambda;
                    }
                }
                // the QR transformation
                Real sine = 1.0;
                Real cosine = 1.0;
                Real u = 0.0;
                bool recoverUnderflow = false;
                for (Size i=l+1; i <= k && !recoverUnderflow; ++i) {
                    const Real h = cosine*e[i];
                    const Real p = sine*e[i];
                    e[i-1] = std::sqrt(p*p+q*q);
                    if (e[i-1] != 0.0) {
                        sine = p/e[i-1];
                        cosine = q/e[i-1];
                        const Real g = d_[i-1]-u;
                        const Real t = (d_[i]-g)*sine+2*cosine*h;
                        u = sine*t;
                        d_[i-1] = g + u;
                        q = cosine*t - h;
                        for (Size j=0; j < ev_.rows(); ++j) {
                            const Real tmp = ev_[j][i-1];
                            ev_[j][i-1] = sine*ev_[j][i] + cosine*tmp;
                            ev_[j][i] = cosine*ev_[j][i] - sine*tmp;
                        }
                    } else {
                        // recover from underflow
                        d_[i-1] -= u;
                        e[l] = 0.0;
                        recoverUnderflow = true;
                    }
                }
                if (!recoverUnderflow) {
                    d_[k] -= u;
                    e[k] = q;
                    e[l] = 0.0;
                }
            }
        }
        // sort (eigenvalues, eigenvectors),
        // code taken from symmetricSchureDecomposition.cpp
        std::vector<std::pair<Real, std::vector<Real> > > temp(n);
        std::vector<Real> eigenVector(ev_.rows());
        for (i=0; i<n; i++) {
            if (ev_.rows() > 0)
                std::copy(ev_.column_begin(i),
                          ev_.column_end(i), eigenVector.begin());
            temp[i] = std::make_pair(d_[i], eigenVector);
        }
        std::sort(temp.begin(), temp.end(),
                  std::greater<std::pair<Real, std::vector<Real> > >());
        // first element is positive
        for (i=0; i<n; i++) {
            d_[i] = temp[i].first;
            Real sign = 1.0;
            if (ev_.rows() > 0 && temp[i].second[0]<0.0)
                sign = -1.0;
            for (Size j=0; j<ev_.rows(); ++j) {
                ev_[j][i] = sign * temp[i].second[j];
            }
        }
    }
Member Function Documentation
const Array& QuantLib::TqrEigenDecomposition::eigenvalues () const [inline]
Definition at line 59 of file tqreigendecomposition.hpp.
References d_.
Referenced by QuantLib::GaussianQuadrature::GaussianQuadrature(), TqrEigenDecompositionTest::testEigenValueDecomposition(), and TqrEigenDecompositionTest::testZeroOffDiagEigenValues().
{ return d_; }
const Matrix& QuantLib::TqrEigenDecomposition::eigenvectors () const [inline]
Definition at line 60 of file tqreigendecomposition.hpp.
References ev_.
Referenced by QuantLib::GaussianQuadrature::GaussianQuadrature(), and TqrEigenDecompositionTest::testEigenVectorDecomposition().
{ return ev_; }
Size QuantLib::TqrEigenDecomposition::iterations () const [inline]
Definition at line 62 of file tqreigendecomposition.hpp.
References iter_.
{ return iter_; }
bool QuantLib::TqrEigenDecomposition::offDiagIsZero (Size k, Array & e) [private]
Definition at line 146 of file tqreigendecomposition.cpp.
References d_.
Referenced by TqrEigenDecomposition().
{
        return std::fabs(d_[k-1])+std::fabs(d_[k])
            == std::fabs(d_[k-1])+std::fabs(d_[k])+std::fabs(e[k]);
    }
Member Data Documentation
Array QuantLib::TqrEigenDecomposition::d_ [private]
Definition at line 68 of file tqreigendecomposition.hpp.
Referenced by eigenvalues(), offDiagIsZero(), and TqrEigenDecomposition().
Matrix QuantLib::TqrEigenDecomposition::ev_ [private]
Definition at line 69 of file tqreigendecomposition.hpp.
Referenced by eigenvectors(), and TqrEigenDecomposition().
Size QuantLib::TqrEigenDecomposition::iter_ [private]
Definition at line 67 of file tqreigendecomposition.hpp.
Referenced by iterations(), and TqrEigenDecomposition().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/matrixutilities/tqreigendecomposition.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/math/matrixutilities/tqreigendecomposition.cpp