QuantLib: QuantLib::DefaultEvent Class Reference
QuantLib::DefaultEvent Class Reference
Credit event on a bond of a certain seniority(ies)/currency.
#include <defaultevent.hpp>
Classes
class DefaultSettlement
Public Member Functions
DefaultEvent (const Date &creditEventDate, const DefaultType &atomicEvType, const Currency &curr, Seniority bondsSen, const Date &settleDate=Null< Date >(), const std::map< Seniority, Real > &recoveryRates=rate_map())
DefaultEvent (const Date &creditEventDate, const DefaultType &atomicEvType, const Currency &curr, Seniority bondsSen, const Date &settleDate=Null< Date >(), Real recoveryRate=0.4)
Date date () const
returns the date at which the event occurs
bool isRestructuring () const
bool isDefault () const
bool hasSettled () const
const DefaultSettlement & settlement () const
const DefaultType & defaultType () const
const Currency & currency () const
returns the currency of the bond this event refers to.
Seniority eventSeniority () const
returns the seniority of the bond that triggered the event.
virtual Real recoveryRate (Seniority seniority) const
virtual bool matchesEventType (const boost::shared_ptr< DefaultType > &contractEvType) const
virtual bool matchesDefaultKey (const DefaultProbKey &contractKey) const
void accept (AcyclicVisitor &)
Protected Attributes
Currency bondsCurrency_
Date defaultDate_
DefaultType eventType_
Seniority bondsSeniority_
DefaultSettlement defSettlement_
Private Types
typedef std::map< Seniority, Real > rate_map
Detailed Description
Credit event on a bond of a certain seniority(ies)/currency.
Represents a credit event affecting all bonds with a given \ seniority and currency. It assumes that all such bonds suffer \ the event simultaneously. Some events affect all seniorities and this has to be encoded through a different set of events of the same event type. The event is an actual realization, not a contractual reference, as such it contains only an atomic type.
Definition at line 49 of file defaultevent.hpp.
Member Typedef Documentation
typedef std::map<Seniority, Real> QuantLib::DefaultEvent::rate_map [private]
Definition at line 85 of file defaultevent.hpp.
Constructor & Destructor Documentation
QuantLib::DefaultEvent::DefaultEvent (const Date & creditEventDate, const DefaultType & atomicEvType, const Currency & curr, Seniority bondsSen, const Date & settleDate = Null<Date>(), const std::map< Seniority, Real > & recoveryRates = rate_map())
Credit event with optional settlement information. Represents a credit event that has taken place. Realized events are of an atomic type. If the settlement information is given seniorities present are the seniorities/bonds affected by the event.
Definition at line 92 of file defaultevent.cpp.
References QL_REQUIRE.
    : bondsCurrency_(curr),
      defaultDate_(creditEventDate),
      eventType_(atomicEvType),
      bondsSeniority_(bondsSen),
      defSettlement_(settleDate,
                     recoveryRates.empty() ? makeIsdaConvMap()
                                           : recoveryRates) {
        if(settleDate != Null<Date>()) {// has settled
            QL_REQUIRE(settleDate >= creditEventDate,
              "Settlement date should be after default date.");
            QL_REQUIRE(recoveryRates.find(bondsSen) != recoveryRates.end(),
              "Settled events must contain the seniority of the default");
        }
    }
QuantLib::DefaultEvent::DefaultEvent (const Date & creditEventDate, const DefaultType & atomicEvType, const Currency & curr, Seniority bondsSen, const Date & settleDate = Null<Date>(), Real recoveryRate = 0.4)
Use NoSeniority to settle to all seniorities with that recovery. In that case the event is assumed to have affected all seniorities.
Definition at line 114 of file defaultevent.cpp.
References QL_REQUIRE.
    : bondsCurrency_(curr),
      defaultDate_(creditEventDate),
      eventType_(atomicEvType),
      bondsSeniority_(bondsSen),
      defSettlement_(settleDate, bondsSen, recoveryRate) {
        if(settleDate != Null<Date>()) {
            QL_REQUIRE(settleDate >= creditEventDate,
            "Settlement date should be after default date.");
        }
    }
Member Function Documentation
void QuantLib::DefaultEvent::accept (AcyclicVisitor & v) [virtual]
Reimplemented from QuantLib::Event.
Definition at line 31 of file defaultevent.cpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Visitor< T >::visit().
Referenced by QuantLib::DefaultEvent::DefaultSettlement::accept().
{
        Visitor<DefaultEvent>* v1 =
            dynamic_cast<Visitor<DefaultEvent>*>(&v);
        if (v1 != 0)
            v1->visit(*this);
        else
            Event::accept(v);
    }
const Currency& QuantLib::DefaultEvent::currency () const [inline]
returns the currency of the bond this event refers to.
Definition at line 126 of file defaultevent.hpp.
References bondsCurrency_.
Referenced by QuantLib::operator==().
{
            return bondsCurrency_;
        }
Date QuantLib::DefaultEvent::date () const [virtual]
returns the date at which the event occurs
Implements QuantLib::Event.
Definition at line 27 of file defaultevent.cpp.
References defaultDate_.
Referenced by QuantLib::earlier_than< DefaultEvent >::operator()(), and QuantLib::operator==().
{
        return defaultDate_;
    }
const DefaultType& QuantLib::DefaultEvent::defaultType () const [inline]
Definition at line 122 of file defaultevent.hpp.
References eventType_.
Referenced by QuantLib::operator==().
{
            return eventType_;
        }
Seniority QuantLib::DefaultEvent::eventSeniority () const [inline]
returns the seniority of the bond that triggered the event.
Definition at line 130 of file defaultevent.hpp.
References bondsSeniority_.
Referenced by QuantLib::operator==().
{
            return bondsSeniority_;
        }
bool QuantLib::DefaultEvent::hasSettled () const [inline]
Definition at line 116 of file defaultevent.hpp.
References QuantLib::DefaultEvent::DefaultSettlement::date(), and defSettlement_.
Referenced by QuantLib::BankruptcyEvent::BankruptcyEvent(), and recoveryRate().
{
            return defSettlement_.date() != Null<Date>();
        }
bool QuantLib::DefaultEvent::isDefault () const [inline]
Definition at line 115 of file defaultevent.hpp.
References isRestructuring().
{ return !isRestructuring();}
bool QuantLib::DefaultEvent::isRestructuring () const [inline]
Definition at line 114 of file defaultevent.hpp.
References eventType_, and QuantLib::DefaultType::isRestructuring().
Referenced by isDefault().
{ return eventType_.isRestructuring(); }
bool QuantLib::DefaultEvent::matchesDefaultKey (const DefaultProbKey & contractKey) const [virtual]
Returns true if this event would trigger a contract with the arguments characteristics.
Definition at line 132 of file defaultevent.cpp.
References bondsCurrency_, bondsSeniority_, QuantLib::DefaultProbKey::currency(), QuantLib::DefaultProbKey::eventTypes(), matchesEventType(), QuantLib::NoSeniority, QuantLib::DefaultProbKey::seniority(), and QuantLib::DefaultProbKey::size().
{
        if(bondsCurrency_ != contractKey.currency()) return false;
        // a contract with NoSeniority matches all events
        if((bondsSeniority_ != contractKey.seniority())
            && (contractKey.seniority() != NoSeniority))
            return false;
        // loop on all event types in the contract and chek if we match any,
        //   calls derived types
        for(Size i=0; i<contractKey.size(); i++) {
            if(this->matchesEventType(contractKey.eventTypes()[i])) return true;
        }
        return false;
    }
virtual bool QuantLib::DefaultEvent::matchesEventType (const boost::shared_ptr< DefaultType > & contractEvType) const [inline, virtual]
matches the event if this event would trigger a contract related to the requested event type. Notice the contractual event types are not neccesarily atomic. Notice it does not check seniority or currency only event type. typically used from Issuer
Reimplemented in QuantLib::BankruptcyEvent, and QuantLib::FailureToPayEvent.
Definition at line 150 of file defaultevent.hpp.
References QuantLib::DefaultType::defaultType(), eventType_, and QuantLib::DefaultType::restructuringType().
Referenced by matchesDefaultKey().
{
            // remember we are made of an atomic type.
            // behaviour by default...
            return
                contractEvType->containsRestructuringType(
                    eventType_.restructuringType()) &&
                contractEvType->containsDefaultType(
                    eventType_.defaultType());
        }
virtual Real QuantLib::DefaultEvent::recoveryRate (Seniority seniority) const [inline, virtual]
returns a value if the event lead to a settlement for the requested seniority. Specializations on the default atomics and recoveries could change the default policy.
Definition at line 137 of file defaultevent.hpp.
References defSettlement_, hasSettled(), and QuantLib::DefaultEvent::DefaultSettlement::recoveryRate().
{
            if(hasSettled()) {
                return defSettlement_.recoveryRate(seniority);
            }
            return Null<Real>();
        }
const DefaultSettlement& QuantLib::DefaultEvent::settlement () const [inline]
Definition at line 119 of file defaultevent.hpp.
References defSettlement_.
{
            return defSettlement_;
        }
Member Data Documentation
Currency QuantLib::DefaultEvent::bondsCurrency_ [protected]
Definition at line 167 of file defaultevent.hpp.
Referenced by currency(), and matchesDefaultKey().
Seniority QuantLib::DefaultEvent::bondsSeniority_ [protected]
Definition at line 170 of file defaultevent.hpp.
Referenced by eventSeniority(), and matchesDefaultKey().
Date QuantLib::DefaultEvent::defaultDate_ [protected]
Definition at line 168 of file defaultevent.hpp.
Referenced by date().
DefaultSettlement QuantLib::DefaultEvent::defSettlement_ [protected]
Definition at line 171 of file defaultevent.hpp.
Referenced by hasSettled(), recoveryRate(), and settlement().
DefaultType QuantLib::DefaultEvent::eventType_ [protected]
Definition at line 169 of file defaultevent.hpp.
Referenced by defaultType(), isRestructuring(), and matchesEventType().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/defaultevent.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/defaultevent.cpp