QuantLib: QuantLib::FiniteDifferenceModel< Evolver > Class Template Reference
QuantLib::FiniteDifferenceModel< Evolver > Class Template Reference
Generic finite difference model.
#include <finitedifferencemodel.hpp>
Public Types
typedef Evolver::traits traits
typedef traits::operator_type operator_type
typedef traits::array_type array_type
typedef traits::bc_set bc_set
typedef traits::condition_type condition_type
Public Member Functions
FiniteDifferenceModel (const operator_type &L, const bc_set &bcs, const std::vector< Time > &stoppingTimes=std::vector< Time >())
FiniteDifferenceModel (const Evolver &evolver, const std::vector< Time > &stoppingTimes=std::vector< Time >())
const Evolver & evolver () const
void rollback (array_type &a, Time from, Time to, Size steps)
void rollback (array_type &a, Time from, Time to, Size steps, const condition_type &condition)
Private Member Functions
void rollbackImpl (array_type &a, Time from, Time to, Size steps, const condition_type *condition)
Private Attributes
Evolver evolver_
std::vector< Time > stoppingTimes_
Detailed Description
template<class Evolver>
class QuantLib::FiniteDifferenceModel< Evolver >
Generic finite difference model.
Definition at line 36 of file finitedifferencemodel.hpp.
Member Typedef Documentation
template<class Evolver> typedef traits::array_type QuantLib::FiniteDifferenceModel< Evolver >::array_type
Definition at line 40 of file finitedifferencemodel.hpp.
template<class Evolver> typedef traits::bc_set QuantLib::FiniteDifferenceModel< Evolver >::bc_set
Definition at line 41 of file finitedifferencemodel.hpp.
template<class Evolver> typedef traits::condition_type QuantLib::FiniteDifferenceModel< Evolver >::condition_type
Definition at line 42 of file finitedifferencemodel.hpp.
template<class Evolver> typedef traits::operator_type QuantLib::FiniteDifferenceModel< Evolver >::operator_type
Definition at line 39 of file finitedifferencemodel.hpp.
template<class Evolver> typedef Evolver::traits QuantLib::FiniteDifferenceModel< Evolver >::traits
Definition at line 38 of file finitedifferencemodel.hpp.
Constructor & Destructor Documentation
template<class Evolver> QuantLib::FiniteDifferenceModel< Evolver >::FiniteDifferenceModel (const operator_type & L, const bc_set & bcs, const std::vector< Time > & stoppingTimes = std::vector<Time>()) [inline]
Definition at line 44 of file finitedifferencemodel.hpp.
References QuantLib::FiniteDifferenceModel< Evolver >::stoppingTimes_.
        : evolver_(L,bcs), stoppingTimes_(stoppingTimes) {
            std::sort(stoppingTimes_.begin(), stoppingTimes_.end());
            std::vector<Time>::iterator last =
                std::unique(stoppingTimes_.begin(), stoppingTimes_.end());
            stoppingTimes_.erase(last, stoppingTimes_.end());
        }
template<class Evolver> QuantLib::FiniteDifferenceModel< Evolver >::FiniteDifferenceModel (const Evolver & evolver, const std::vector< Time > & stoppingTimes = std::vector<Time>()) [inline]
Definition at line 54 of file finitedifferencemodel.hpp.
References QuantLib::FiniteDifferenceModel< Evolver >::stoppingTimes_.
        : evolver_(evolver), stoppingTimes_(stoppingTimes) {
            std::sort(stoppingTimes_.begin(), stoppingTimes_.end());
            std::vector<Time>::iterator last =
                std::unique(stoppingTimes_.begin(), stoppingTimes_.end());
            stoppingTimes_.erase(last, stoppingTimes_.end());
        }
Member Function Documentation
template<class Evolver> const Evolver& QuantLib::FiniteDifferenceModel< Evolver >::evolver () const [inline]
Definition at line 65 of file finitedifferencemodel.hpp.
References QuantLib::FiniteDifferenceModel< Evolver >::evolver_.
{ return evolver_; }
template<class Evolver> void QuantLib::FiniteDifferenceModel< Evolver >::rollback (array_type & a, Time from, Time to, Size steps) [inline]
solves the problem between the given times.
Warning:
being this a rollback, from must be a later time than to.
Definition at line 70 of file finitedifferencemodel.hpp.
References QuantLib::FiniteDifferenceModel< Evolver >::rollbackImpl().
Referenced by QuantLib::FDEuropeanEngine< Scheme >::calculate(), QuantLib::FdmBackwardSolver::rollback(), FdmLinearOpTest::testFdmHestonAmerican(), FdmLinearOpTest::testFdmHestonBarrier(), and FdmLinearOpTest::testFdmHestonHullWhiteOp().
{
            rollbackImpl(a,from,to,steps,(const condition_type*) 0);
        }
template<class Evolver> void QuantLib::FiniteDifferenceModel< Evolver >::rollback (array_type & a, Time from, Time to, Size steps, const condition_type & condition) [inline]
solves the problem between the given times, applying a condition at every step.
Warning:
being this a rollback, from must be a later time than to.
Definition at line 81 of file finitedifferencemodel.hpp.
References QuantLib::FiniteDifferenceModel< Evolver >::rollbackImpl().
{
            rollbackImpl(a,from,to,steps,&condition);
        }
template<class Evolver> void QuantLib::FiniteDifferenceModel< Evolver >::rollbackImpl (array_type & a, Time from, Time to, Size steps, const condition_type * condition) [inline, private]
Definition at line 89 of file finitedifferencemodel.hpp.
References QuantLib::anonymous_namespace{yieldtermstructure.cpp}::dt, QuantLib::FiniteDifferenceModel< Evolver >::evolver_, QL_EPSILON, QL_REQUIRE, QuantLib::FiniteDifferenceModel< Evolver >::stoppingTimes_, and anonymous_namespace{quantlibbenchmark.cpp}::t.
Referenced by QuantLib::FiniteDifferenceModel< Evolver >::rollback().
{
            QL_REQUIRE(from >= to,
                       "trying to roll back from " << from << " to " << to);
            Time dt = (from-to)/steps, t = from;
            evolver_.setStep(dt);
            if(!stoppingTimes_.empty() && stoppingTimes_.back() == from) {
                if (condition)
                    condition->applyTo(a,from);
            }
            for (Size i=0; i<steps; ++i, t -= dt) {
                Time now = t, next = t-dt;
                if (std::fabs(to-next) < std::sqrt(QL_EPSILON)) next = to;
                bool hit = false;
                for (Integer j = stoppingTimes_.size()-1; j >= 0 ; --j) {
                    if (next <= stoppingTimes_[j] && stoppingTimes_[j] < now) {
                        // a stopping time was hit
                        hit = true;
                        // perform a small step to stoppingTimes_[j]...
                        evolver_.setStep(now-stoppingTimes_[j]);
                        evolver_.step(a,now);
                        if (condition)
                            condition->applyTo(a,stoppingTimes_[j]);
                        // ...and continue the cycle
                        now = stoppingTimes_[j];
                    }
                }
                // if we did hit...
                if (hit) {
                    // ...we might have to make a small step to
                    // complete the big one...
                    if (now > next) {
                        evolver_.setStep(now - next);
                        evolver_.step(a,now);
                        if (condition)
                            condition->applyTo(a,next);
                    }
                    // ...and in any case, we have to reset the
                    // evolver to the default step.
                    evolver_.setStep(dt);
                } else {
                    // if we didn't, the evolver is already set to the
                    // default step, which is ok for us.
                    evolver_.step(a,now);
                    if (condition)
                        condition->applyTo(a, next);
                }
            }
        }
Member Data Documentation
template<class Evolver> Evolver QuantLib::FiniteDifferenceModel< Evolver >::evolver_ [private]
Definition at line 145 of file finitedifferencemodel.hpp.
Referenced by QuantLib::FiniteDifferenceModel< Evolver >::evolver(), and QuantLib::FiniteDifferenceModel< Evolver >::rollbackImpl().
template<class Evolver> std::vector<Time> QuantLib::FiniteDifferenceModel< Evolver >::stoppingTimes_ [private]
Definition at line 146 of file finitedifferencemodel.hpp.
Referenced by QuantLib::FiniteDifferenceModel< Evolver >::FiniteDifferenceModel(), and QuantLib::FiniteDifferenceModel< Evolver >::rollbackImpl().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/finitedifferencemodel.hpp