QuantLib: QuantLib::OneFactorModel Class Reference
QuantLib::OneFactorModel Class Reference
Single-factor short-rate model abstract class.
#include <onefactormodel.hpp>
Classes
class ShortRateDynamics
Base class describing the short-rate dynamics.
class ShortRateTree
Recombining trinomial tree discretizing the state variable.
Public Member Functions
OneFactorModel (Size nArguments)
virtual ~OneFactorModel ()
virtual boost::shared_ptr
< ShortRateDynamics > dynamics () const =0
returns the short-rate dynamics
boost::shared_ptr< Lattice > tree (const TimeGrid &grid) const
Return by default a trinomial recombining tree.
Detailed Description
Single-factor short-rate model abstract class.
Definition at line 37 of file onefactormodel.hpp.
Constructor & Destructor Documentation
QuantLib::OneFactorModel::OneFactorModel (Size nArguments)
Definition at line 92 of file onefactormodel.cpp.
    : ShortRateModel(nArguments) {}
virtual QuantLib::OneFactorModel::~OneFactorModel () [inline, virtual]
Definition at line 40 of file onefactormodel.hpp.
{}
Member Function Documentation
virtual boost::shared_ptr<ShortRateDynamics> QuantLib::OneFactorModel::dynamics () const [pure virtual]
returns the short-rate dynamics
Implemented in QuantLib::GeneralizedHullWhite, QuantLib::CoxIngersollRoss, QuantLib::ExtendedCoxIngersollRoss, QuantLib::HullWhite, QuantLib::Vasicek, and QuantLib::BlackKarasinski.
Referenced by QuantLib::OneFactorAffineModel::discount(), and tree().
boost::shared_ptr< Lattice > QuantLib::OneFactorModel::tree (const TimeGrid & grid) const [virtual]
Return by default a trinomial recombining tree.
Implements QuantLib::ShortRateModel.
Reimplemented in QuantLib::GeneralizedHullWhite, QuantLib::CoxIngersollRoss, QuantLib::ExtendedCoxIngersollRoss, QuantLib::HullWhite, and QuantLib::BlackKarasinski.
Definition at line 96 of file onefactormodel.cpp.
References dynamics().
{
        boost::shared_ptr<TrinomialTree> trinomial(
                              new TrinomialTree(dynamics()->process(), grid));
        return boost::shared_ptr<Lattice>(
                              new ShortRateTree(trinomial, dynamics(), grid));
    }
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/shortrate/onefactormodel.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/shortrate/onefactormodel.cpp