QuantLib: QuantLib::EURLibor Class Reference
QuantLib::EURLibor Class Reference
base class for all BBA EUR LIBOR indexes but the O/N
#include <eurlibor.hpp>
Public Member Functions
EURLibor (const Period &tenor, const Handle< YieldTermStructure > &h=Handle< YieldTermStructure >())
Date calculations
see http://www.bba.org.uk/bba/jsp/polopoly.jsp?d=225&a=1412
Date valueDate (const Date &fixingDate) const
Date maturityDate (const Date &valueDate) const
Private Attributes
Calendar target_
Detailed Description
base class for all BBA EUR LIBOR indexes but the O/N
Euro LIBOR fixed by BBA.
See <http://www.bba.org.uk/bba/jsp/polopoly.jsp?d=225&a=1414>.
Warning:
This is the rate fixed in London by BBA. Use Euribor if you're interested in the fixing by the ECB.
Definition at line 42 of file eurlibor.hpp.
Constructor & Destructor Documentation
QuantLib::EURLibor::EURLibor (const Period & tenor, const Handle< YieldTermStructure > & h = Handle<YieldTermStructure>())
Definition at line 60 of file eurlibor.cpp.
References QuantLib::Days, QL_REQUIRE, and QuantLib::InterestRateIndex::tenor().
    : IborIndex("EURLibor", tenor,
                2,
                EURCurrency(),
                // http://www.bba.org.uk/bba/jsp/polopoly.jsp?d=225&a=1412 :
                // JoinBusinessDays is the fixing calendar for
                // all indexes but o/n
                JointCalendar(UnitedKingdom(UnitedKingdom::Exchange),
                              TARGET(),
                              JoinBusinessDays),
                eurliborConvention(tenor), eurliborEOM(tenor),
                Actual360(), h),
      target_(TARGET()) {
        QL_REQUIRE(this->tenor().units()!=Days,
                   "for daily tenors (" << this->tenor() <<
                   ") dedicated DailyTenor constructor must be used");
    }
Member Function Documentation
Date QuantLib::EURLibor::maturityDate (const Date & valueDate) const [virtual]
Reimplemented from QuantLib::IborIndex.
Definition at line 90 of file eurlibor.cpp.
References QuantLib::Calendar::advance(), QuantLib::IborIndex::convention_, QuantLib::IborIndex::endOfMonth(), target_, and QuantLib::InterestRateIndex::tenor_.
{
        // http://www.bba.org.uk/bba/jsp/polopoly.jsp?d=225&a=1412 :
        // In the case of EUR only, maturity dates will be based on days in
        // which the Target system is open.
        return target_.advance(valueDate, tenor_, convention_, endOfMonth());
    }
Date QuantLib::EURLibor::valueDate (const Date & fixingDate) const [virtual]
Reimplemented from QuantLib::InterestRateIndex.
Definition at line 79 of file eurlibor.cpp.
References QuantLib::Calendar::advance(), QuantLib::Days, QuantLib::InterestRateIndex::fixingDays_, QuantLib::InterestRateIndex::isValidFixingDate(), QL_REQUIRE, and target_.
{
        QL_REQUIRE(isValidFixingDate(fixingDate),
                   "Fixing date " << fixingDate << " is not valid");
        // http://www.bba.org.uk/bba/jsp/polopoly.jsp?d=225&a=1412 :
        // In the case of EUR the Value Date shall be two TARGET
        // business days after the Fixing Date.
        return target_.advance(fixingDate, fixingDays_, Days);
    }
Member Data Documentation
Calendar QuantLib::EURLibor::target_ [private]
Definition at line 56 of file eurlibor.hpp.
Referenced by maturityDate(), and valueDate().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/indexes/ibor/eurlibor.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/indexes/ibor/eurlibor.cpp