QuantLib: QuantLib::detail::SABRInterpolationImpl< I1, I2 > Class Template Reference
QuantLib::detail::SABRInterpolationImpl< I1, I2 > Class Template Reference
#include <sabrinterpolation.hpp>
Classes
class SABRError
class SabrParametersTransformation
Public Member Functions
SABRInterpolationImpl (const I1 &xBegin, const I1 &xEnd, const I2 &yBegin, Time t, const Real &forward, Real alpha, Real beta, Real nu, Real rho, bool alphaIsFixed, bool betaIsFixed, bool nuIsFixed, bool rhoIsFixed, bool vegaWeighted, const boost::shared_ptr< EndCriteria > &endCriteria, const boost::shared_ptr< OptimizationMethod > &optMethod)
void update ()
Real value (Real x) const
Real primitive (Real) const
Real derivative (Real) const
Real secondDerivative (Real) const
Real interpolationSquaredError () const
Disposable< Array > interpolationErrors (const Array &) const
Real interpolationError () const
Real interpolationMaxError () const
Private Attributes
boost::shared_ptr< EndCriteria > endCriteria_
boost::shared_ptr
< OptimizationMethod > optMethod_
const Real & forward_
bool vegaWeighted_
boost::shared_ptr
< ParametersTransformation > transformation_
NoConstraint constraint_
Detailed Description
template<class I1, class I2>
class QuantLib::detail::SABRInterpolationImpl< I1, I2 >
Definition at line 102 of file sabrinterpolation.hpp.
Constructor & Destructor Documentation
template<class I1 , class I2 > QuantLib::detail::SABRInterpolationImpl< I1, I2 >::SABRInterpolationImpl (const I1 & xBegin, const I1 & xEnd, const I2 & yBegin, Time t, const Real & forward, Real alpha, Real beta, Real nu, Real rho, bool alphaIsFixed, bool betaIsFixed, bool nuIsFixed, bool rhoIsFixed, bool vegaWeighted, const boost::shared_ptr< EndCriteria > & endCriteria, const boost::shared_ptr< OptimizationMethod > & optMethod) [inline]
Definition at line 105 of file sabrinterpolation.hpp.
References QuantLib::detail::SABRInterpolationImpl< I1, I2 >::endCriteria_, QuantLib::detail::SABRInterpolationImpl< I1, I2 >::optMethod_, and QuantLib::detail::SABRCoeffHolder::weights_.
            : Interpolation::templateImpl<I1,I2>(xBegin, xEnd, yBegin),
              SABRCoeffHolder(t, forward, alpha, beta, nu, rho,
                              alphaIsFixed,betaIsFixed,nuIsFixed,rhoIsFixed),
              endCriteria_(endCriteria), optMethod_(optMethod),
              forward_(forward),
              vegaWeighted_(vegaWeighted)
            {
                // if no optimization method or endCriteria is provided, we provide one
                if (!optMethod_)
                    //optMethod_ = boost::shared_ptr<OptimizationMethod>(new
                    //    LevenbergMarquardt(1e-8, 1e-8, 1e-8));
                    optMethod_ = boost::shared_ptr<OptimizationMethod>(new
                        Simplex(0.01));
                if (!endCriteria_) {
                    endCriteria_ = boost::shared_ptr<EndCriteria>(new
                        EndCriteria(60000, 100, 1e-8, 1e-8, 1e-8));
                }
                weights_ = std::vector<Real>(xEnd-xBegin, 1.0/(xEnd-xBegin));
            }
Member Function Documentation
template<class I1 , class I2 > Real QuantLib::detail::SABRInterpolationImpl< I1, I2 >::derivative (Real) const [inline, virtual]
Implements QuantLib::Interpolation::Impl.
Definition at line 224 of file sabrinterpolation.hpp.
References QL_FAIL.
{
                QL_FAIL("SABR derivative not implemented");
            }
template<class I1 , class I2 > Real QuantLib::detail::SABRInterpolationImpl< I1, I2 >::interpolationError () const [inline]
Definition at line 255 of file sabrinterpolation.hpp.
References QuantLib::detail::SABRInterpolationImpl< I1, I2 >::interpolationSquaredError(), QuantLib::Interpolation::templateImpl< I1, I2 >::xBegin_, and QuantLib::Interpolation::templateImpl< I1, I2 >::xEnd_.
Referenced by QuantLib::detail::SABRInterpolationImpl< I1, I2 >::update().
{
                Size n = this->xEnd_-this->xBegin_;
                Real squaredError = interpolationSquaredError();
                return std::sqrt(n*squaredError/(n-1));
            }
template<class I1 , class I2 > Disposable<Array> QuantLib::detail::SABRInterpolationImpl< I1, I2 >::interpolationErrors (const Array &) const [inline]
Definition at line 243 of file sabrinterpolation.hpp.
References QuantLib::Array::begin(), QuantLib::detail::SABRInterpolationImpl< I1, I2 >::value(), QuantLib::detail::SABRCoeffHolder::weights_, QuantLib::Interpolation::templateImpl< I1, I2 >::xBegin_, QuantLib::Interpolation::templateImpl< I1, I2 >::xEnd_, and QuantLib::Interpolation::templateImpl< I1, I2 >::yBegin_.
Referenced by QuantLib::detail::SABRInterpolationImpl< I1, I2 >::SABRError::values().
{
                Array results(this->xEnd_ - this->xBegin_);
                std::vector<Real>::const_iterator x = this->xBegin_;
                Array::iterator r = results.begin();
                std::vector<Real>::const_iterator y = this->yBegin_;
                std::vector<Real>::const_iterator w = weights_.begin();
                for (; x != this->xEnd_; ++x, ++r, ++w, ++y) {
                    *r = (value(*x) - *y)* std::sqrt(*w);
                }
                return results;
            }
template<class I1 , class I2 > Real QuantLib::detail::SABRInterpolationImpl< I1, I2 >::interpolationMaxError () const [inline]
Definition at line 261 of file sabrinterpolation.hpp.
References QL_MIN_REAL, QuantLib::detail::SABRInterpolationImpl< I1, I2 >::value(), QuantLib::Interpolation::templateImpl< I1, I2 >::xBegin_, QuantLib::Interpolation::templateImpl< I1, I2 >::xEnd_, and QuantLib::Interpolation::templateImpl< I1, I2 >::yBegin_.
Referenced by QuantLib::detail::SABRInterpolationImpl< I1, I2 >::update().
{
                Real error, maxError = QL_MIN_REAL;
                I1 i = this->xBegin_;
                I2 j = this->yBegin_;
                for (; i != this->xEnd_; ++i, ++j) {
                    error = std::fabs(value(*i) - *j);
                    maxError = std::max(maxError, error);
                }
                return maxError;
            }
template<class I1 , class I2 > Real QuantLib::detail::SABRInterpolationImpl< I1, I2 >::interpolationSquaredError () const [inline]
Definition at line 231 of file sabrinterpolation.hpp.
References QuantLib::detail::SABRInterpolationImpl< I1, I2 >::value(), QuantLib::detail::SABRCoeffHolder::weights_, QuantLib::Interpolation::templateImpl< I1, I2 >::xBegin_, QuantLib::Interpolation::templateImpl< I1, I2 >::xEnd_, and QuantLib::Interpolation::templateImpl< I1, I2 >::yBegin_.
Referenced by QuantLib::detail::SABRInterpolationImpl< I1, I2 >::interpolationError(), and QuantLib::detail::SABRInterpolationImpl< I1, I2 >::SABRError::value().
{
                Real error, totalError = 0.0;
                std::vector<Real>::const_iterator x = this->xBegin_;
                std::vector<Real>::const_iterator y = this->yBegin_;
                std::vector<Real>::const_iterator w = weights_.begin();
                for (; x != this->xEnd_; ++x, ++y, ++w) {
                    error = (value(*x) - *y);
                    totalError += error*error * (*w);
                }
                return totalError;
            }
template<class I1 , class I2 > Real QuantLib::detail::SABRInterpolationImpl< I1, I2 >::primitive (Real) const [inline, virtual]
Implements QuantLib::Interpolation::Impl.
Definition at line 221 of file sabrinterpolation.hpp.
References QL_FAIL.
{
                QL_FAIL("SABR primitive not implemented");
            }
template<class I1 , class I2 > Real QuantLib::detail::SABRInterpolationImpl< I1, I2 >::secondDerivative (Real) const [inline, virtual]
Implements QuantLib::Interpolation::Impl.
Definition at line 227 of file sabrinterpolation.hpp.
References QL_FAIL.
{
                QL_FAIL("SABR secondDerivative not implemented");
            }
template<class I1 , class I2 > void QuantLib::detail::SABRInterpolationImpl< I1, I2 >::update () [inline, virtual]
Implements QuantLib::Interpolation::Impl.
Definition at line 138 of file sabrinterpolation.hpp.
References QuantLib::detail::SABRCoeffHolder::alpha_, QuantLib::detail::SABRCoeffHolder::alphaIsFixed_, QuantLib::detail::SABRCoeffHolder::beta_, QuantLib::detail::SABRCoeffHolder::betaIsFixed_, QuantLib::blackFormulaStdDevDerivative(), QuantLib::Problem::currentValue(), QuantLib::detail::SABRInterpolationImpl< I1, I2 >::endCriteria_, QuantLib::detail::SABRCoeffHolder::error_, QuantLib::detail::SABRInterpolationImpl< I1, I2 >::forward_, QuantLib::detail::SABRInterpolationImpl< I1, I2 >::interpolationError(), QuantLib::detail::SABRInterpolationImpl< I1, I2 >::interpolationMaxError(), QuantLib::detail::SABRCoeffHolder::maxError_, QuantLib::EndCriteria::None, QuantLib::detail::SABRCoeffHolder::nu_, QuantLib::detail::SABRCoeffHolder::nuIsFixed_, QuantLib::detail::SABRInterpolationImpl< I1, I2 >::optMethod_, QL_REQUIRE, QuantLib::io::rate(), QuantLib::detail::SABRCoeffHolder::rho_, QuantLib::detail::SABRCoeffHolder::rhoIsFixed_, QuantLib::detail::SABRCoeffHolder::SABREndCriteria_, QuantLib::detail::SABRCoeffHolder::t_, QuantLib::detail::SABRInterpolationImpl< I1, I2 >::transformation_, QuantLib::detail::SABRInterpolationImpl< I1, I2 >::vegaWeighted_, QuantLib::detail::SABRCoeffHolder::weights_, QuantLib::Interpolation::templateImpl< I1, I2 >::xBegin_, QuantLib::Interpolation::templateImpl< I1, I2 >::xEnd_, and QuantLib::Interpolation::templateImpl< I1, I2 >::yBegin_.
{
                // forward_ might have changed
                QL_REQUIRE(forward_>0.0, "at the money forward rate must be "
                           "positive: " << io::rate(forward_) << " not allowed");
                // we should also check that y contains positive values only
                // we must update weights if it is vegaWeighted
                if (vegaWeighted_) {
                    std::vector<Real>::const_iterator x = this->xBegin_;
                    std::vector<Real>::const_iterator y = this->yBegin_;
                    //std::vector<Real>::iterator w = weights_.begin();
                    weights_.clear();
                    Real weightsSum = 0.0;
                    for ( ; x!=this->xEnd_; ++x, ++y) {
                        Real stdDev = std::sqrt((*y)*(*y)*t_);
                        weights_.push_back(
                            blackFormulaStdDevDerivative(*x, forward_, stdDev));
                        weightsSum += weights_.back();
                    }
                    // weight normalization
                    std::vector<Real>::iterator w = weights_.begin();
                    for ( ; w!=weights_.end(); ++w)
                        *w /= weightsSum;
                }
                // there is nothing to optimize
                if (alphaIsFixed_ && betaIsFixed_ && nuIsFixed_ && rhoIsFixed_) {
                    error_ = interpolationError();
                    maxError_ = interpolationMaxError();
                    SABREndCriteria_ = EndCriteria::None;
                    return;
                } else {
                    SABRError costFunction(this);
                    transformation_ = boost::shared_ptr<ParametersTransformation>(new
                        SabrParametersTransformation);
                    Array guess(4);
                    guess[0] = alpha_;
                    guess[1] = beta_;
                    guess[2] = nu_;
                    guess[3] = rho_;
                    std::vector<bool> parameterAreFixed(4);
                    parameterAreFixed[0] = alphaIsFixed_;
                    parameterAreFixed[1] = betaIsFixed_;
                    parameterAreFixed[2] = nuIsFixed_;
                    parameterAreFixed[3] = rhoIsFixed_;
                    Array inversedTransformatedGuess(transformation_->inverse(guess));
                    ProjectedCostFunction constrainedSABRError(costFunction,
                                    inversedTransformatedGuess, parameterAreFixed);
                    Array projectedGuess
                        (constrainedSABRError.project(inversedTransformatedGuess));
                    NoConstraint constraint;
                    Problem problem(constrainedSABRError, constraint, projectedGuess);
                    SABREndCriteria_ = optMethod_->minimize(problem, *endCriteria_);
                    Array projectedResult(problem.currentValue());
                    Array transfResult(constrainedSABRError.include(projectedResult));
                    Array result = transformation_->direct(transfResult);
                    alpha_ = result[0];
                    beta_  = result[1];
                    nu_    = result[2];
                    rho_   = result[3];
                }
                error_ = interpolationError();
                maxError_ = interpolationMaxError();
            }
template<class I1 , class I2 > Real QuantLib::detail::SABRInterpolationImpl< I1, I2 >::value (Real x) const [inline, virtual]
Implements QuantLib::Interpolation::Impl.
Definition at line 215 of file sabrinterpolation.hpp.
References QuantLib::detail::SABRCoeffHolder::alpha_, QuantLib::detail::SABRCoeffHolder::beta_, QuantLib::detail::SABRInterpolationImpl< I1, I2 >::forward_, QuantLib::detail::SABRCoeffHolder::nu_, QL_REQUIRE, QuantLib::io::rate(), QuantLib::detail::SABRCoeffHolder::rho_, QuantLib::sabrVolatility(), and QuantLib::detail::SABRCoeffHolder::t_.
Referenced by QuantLib::detail::SABRInterpolationImpl< I1, I2 >::interpolationErrors(), QuantLib::detail::SABRInterpolationImpl< I1, I2 >::interpolationMaxError(), and QuantLib::detail::SABRInterpolationImpl< I1, I2 >::interpolationSquaredError().
{
                QL_REQUIRE(x>0.0, "strike must be positive: " <<
                                  io::rate(x) << " not allowed");
                return sabrVolatility(x, forward_, t_,
                                      alpha_, beta_, nu_, rho_);
            }
Member Data Documentation
template<class I1 , class I2 > NoConstraint QuantLib::detail::SABRInterpolationImpl< I1, I2 >::constraint_ [private]
Definition at line 334 of file sabrinterpolation.hpp.
template<class I1 , class I2 > boost::shared_ptr<EndCriteria> QuantLib::detail::SABRInterpolationImpl< I1, I2 >::endCriteria_ [private]
Definition at line 329 of file sabrinterpolation.hpp.
Referenced by QuantLib::detail::SABRInterpolationImpl< I1, I2 >::SABRInterpolationImpl(), and QuantLib::detail::SABRInterpolationImpl< I1, I2 >::update().
template<class I1 , class I2 > const Real& QuantLib::detail::SABRInterpolationImpl< I1, I2 >::forward_ [private]
Reimplemented from QuantLib::detail::SABRCoeffHolder.
Definition at line 331 of file sabrinterpolation.hpp.
Referenced by QuantLib::detail::SABRInterpolationImpl< I1, I2 >::update(), and QuantLib::detail::SABRInterpolationImpl< I1, I2 >::value().
template<class I1 , class I2 > boost::shared_ptr<OptimizationMethod> QuantLib::detail::SABRInterpolationImpl< I1, I2 >::optMethod_ [private]
Definition at line 330 of file sabrinterpolation.hpp.
Referenced by QuantLib::detail::SABRInterpolationImpl< I1, I2 >::SABRInterpolationImpl(), and QuantLib::detail::SABRInterpolationImpl< I1, I2 >::update().
template<class I1 , class I2 > boost::shared_ptr<ParametersTransformation> QuantLib::detail::SABRInterpolationImpl< I1, I2 >::transformation_ [private]
Definition at line 333 of file sabrinterpolation.hpp.
Referenced by QuantLib::detail::SABRInterpolationImpl< I1, I2 >::update(), QuantLib::detail::SABRInterpolationImpl< I1, I2 >::SABRError::value(), and QuantLib::detail::SABRInterpolationImpl< I1, I2 >::SABRError::values().
template<class I1 , class I2 > bool QuantLib::detail::SABRInterpolationImpl< I1, I2 >::vegaWeighted_ [private]
Definition at line 332 of file sabrinterpolation.hpp.
Referenced by QuantLib::detail::SABRInterpolationImpl< I1, I2 >::update().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/interpolations/sabrinterpolation.hpp