QuantLib: QuantLib::TreeLattice< Impl > Class Template Reference
QuantLib::TreeLattice< Impl > Class Template Reference
Tree-based lattice-method base class.
#include <lattice.hpp>
Public Member Functions
TreeLattice (const TimeGrid &timeGrid, Size n)
const Array & statePrices (Size i) const
void stepback (Size i, const Array &values, Array &newValues) const
Lattice interface
void initialize (DiscretizedAsset &, Time t) const
initialize an asset at the given time.
void rollback (DiscretizedAsset &, Time to) const
void partialRollback (DiscretizedAsset &, Time to) const
Real presentValue (DiscretizedAsset &) const
Computes the present value of an asset using Arrow-Debrew prices.
Protected Member Functions
void computeStatePrices (Size until) const
Protected Attributes
std::vector< Array > statePrices_
Private Attributes
Size n_
Size statePricesLimit_
Detailed Description
template<class Impl>
class QuantLib::TreeLattice< Impl >
Tree-based lattice-method base class.
This class defines a lattice method that is able to rollback (with discount) a discretized asset object. It will be based on one or more trees.
Derived classes must implement the following interface:
        public:
          DiscountFactor discount(Size i, Size index) const;
          Size descendant(Size i, Size index, Size branch) const;
          Real probability(Size i, Size index, Size branch) const;
and may implement the following:
        public:
          void stepback(Size i,
                        const Array& values,
                        Array& newValues) const;
Definition at line 57 of file lattice.hpp.
Constructor & Destructor Documentation
template<class Impl> QuantLib::TreeLattice< Impl >::TreeLattice (const TimeGrid & timeGrid, Size n) [inline]
Definition at line 60 of file lattice.hpp.
        : Lattice(timeGrid), n_(n) {
            QL_REQUIRE(n>0, "there is no zeronomial lattice!");
            statePrices_ = std::vector<Array>(1, Array(1, 1.0));
            statePricesLimit_ = 0;
        }
Member Function Documentation
template<class Impl > void QuantLib::TreeLattice< Impl >::computeStatePrices (Size until) const [protected]
Definition at line 98 of file lattice.hpp.
{
        for (Size i=statePricesLimit_; i<until; i++) {
            statePrices_.push_back(Array(this->impl().size(i+1), 0.0));
            for (Size j=0; j<this->impl().size(i); j++) {
                DiscountFactor disc = this->impl().discount(i,j);
                Real statePrice = statePrices_[i][j];
                for (Size l=0; l<n_; l++) {
                    statePrices_[i+1][this->impl().descendant(i,j,l)] +=
                        statePrice*disc*this->impl().probability(i,j,l);
                }
            }
        }
        statePricesLimit_ = until;
    }
template<class Impl > void QuantLib::TreeLattice< Impl >::initialize (DiscretizedAsset & , Time time) const [virtual]
initialize an asset at the given time.
Implements QuantLib::Lattice.
Definition at line 127 of file lattice.hpp.
References QuantLib::DiscretizedAsset::reset(), anonymous_namespace{quantlibbenchmark.cpp}::t, and QuantLib::DiscretizedAsset::time().
{
        Size i = t_.index(t);
        asset.time() = t;
        asset.reset(this->impl().size(i));
    }
template<class Impl > void QuantLib::TreeLattice< Impl >::partialRollback (DiscretizedAsset & , Time to) const [virtual]
Roll back an asset until the given time, but do not perform the final adjustment.
Warning:
In version 0.3.7 and earlier, this method was called rollAlmostBack method and performed pre-adjustment. This is no longer true; when migrating your code, you'll have to replace calls such as:
                     method->rollAlmostBack(asset,t);
with the two statements:
                     method->partialRollback(asset,t);
                     asset->preAdjustValues();
Implements QuantLib::Lattice.
Reimplemented in QuantLib::TsiveriotisFernandesLattice< T >.
Definition at line 140 of file lattice.hpp.
References QuantLib::DiscretizedAsset::adjustValues(), QuantLib::close(), QL_REQUIRE, QuantLib::DiscretizedAsset::time(), and QuantLib::DiscretizedAsset::values().
{
        Time from = asset.time();
        if (close(from,to))
            return;
        QL_REQUIRE(from > to,
                   "cannot roll the asset back to" << to
                   << " (it is already at t = " << from << ")");
        Integer iFrom = Integer(t_.index(from));
        Integer iTo = Integer(t_.index(to));
        for (Integer i=iFrom-1; i>=iTo; --i) {
            Array newValues(this->impl().size(i));
            this->impl().stepback(i, asset.values(), newValues);
            asset.time() = t_[i];
            asset.values() = newValues;
            // skip the very last adjustment
            if (i != iTo)
                asset.adjustValues();
        }
    }
template<class Impl > Real QuantLib::TreeLattice< Impl >::presentValue (DiscretizedAsset & asset) const [virtual]
Computes the present value of an asset using Arrow-Debrew prices.
Implements QuantLib::Lattice.
Definition at line 121 of file lattice.hpp.
References QuantLib::DotProduct(), QuantLib::DiscretizedAsset::time(), and QuantLib::DiscretizedAsset::values().
{
        Size i = t_.index(asset.time());
        return DotProduct(asset.values(), statePrices(i));
    }
template<class Impl > void QuantLib::TreeLattice< Impl >::rollback (DiscretizedAsset & , Time to) const [virtual]
Roll back an asset until the given time, performing any needed adjustment.
Implements QuantLib::Lattice.
Reimplemented in QuantLib::TsiveriotisFernandesLattice< T >.
Definition at line 134 of file lattice.hpp.
References QuantLib::DiscretizedAsset::adjustValues().
{
        partialRollback(asset,to);
        asset.adjustValues();
    }
template<class Impl > const Array & QuantLib::TreeLattice< Impl >::statePrices (Size i) const
Definition at line 114 of file lattice.hpp.
{
        if (i>statePricesLimit_)
            computeStatePrices(i);
        return statePrices_[i];
    }
template<class Impl > void QuantLib::TreeLattice< Impl >::stepback (Size i, const Array & values, Array & newValues) const
Reimplemented in QuantLib::BlackScholesLattice< T >.
Definition at line 167 of file lattice.hpp.
{
        for (Size j=0; j<this->impl().size(i); j++) {
            Real value = 0.0;
            for (Size l=0; l<n_; l++) {
                value += this->impl().probability(i,j,l) *
                         values[this->impl().descendant(i,j,l)];
            }
            value *= this->impl().discount(i,j);
            newValues[j] = value;
        }
    }
Member Data Documentation
template<class Impl> Size QuantLib::TreeLattice< Impl >::n_ [private]
Definition at line 90 of file lattice.hpp.
template<class Impl> std::vector<Array> QuantLib::TreeLattice< Impl >::statePrices_ [mutable, protected]
Definition at line 87 of file lattice.hpp.
Referenced by QuantLib::TreeLattice< BlackScholesLattice< T > >::TreeLattice().
template<class Impl> Size QuantLib::TreeLattice< Impl >::statePricesLimit_ [mutable, private]
Definition at line 91 of file lattice.hpp.
Referenced by QuantLib::TreeLattice< BlackScholesLattice< T > >::TreeLattice().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/lattices/lattice.hpp