QuantLib: QuantLib::MarketModelPathwiseMultiDeflatedCap Class Reference
QuantLib::MarketModelPathwiseMultiDeflatedCap Class Reference
#include <pathwiseproductcaplet.hpp>
Public Member Functions
MarketModelPathwiseMultiDeflatedCap (const std::vector< Time > &rateTimes, const std::vector< Real > &accruals, const std::vector< Time > &paymentTimes, Rate strike, const std::vector< std::pair< Size, Size > > &startsAndEnds)
virtual ~MarketModelPathwiseMultiDeflatedCap ()
virtual std::vector< Size > suggestedNumeraires () const
virtual const
EvolutionDescription & evolution () const
virtual std::vector< Time > possibleCashFlowTimes () const
virtual Size numberOfProducts () const
virtual Size maxNumberOfCashFlowsPerProductPerStep () const
virtual bool alreadyDeflated () const
virtual void reset ()
during simulation put product at start of path
virtual bool nextTimeStep (const CurveState &currentState, std::vector< Size > &numberCashFlowsThisStep, std::vector< std::vector< MarketModelPathwiseMultiProduct::CashFlow > > &cashFlowsGenerated)
return value indicates whether path is finished, TRUE means done
virtual std::auto_ptr
< MarketModelPathwiseMultiProduct > clone () const
returns a newly-allocated copy of itself
Private Attributes
MarketModelPathwiseMultiDeflatedCaplet underlyingCaplets_
Size numberRates_
std::vector< std::pair< Size,
Size > > startsAndEnds_
Size currentIndex_
std::vector< Size > innerCashFlowSizes_
std::vector< std::vector
< MarketModelPathwiseMultiProduct::CashFlow > > innerCashFlowsGenerated_
Detailed Description
MarketModelPathwiseMultiDeflatedCap to price several caps and get their derivatives simultaneously. Mainly useful for testing pathwise market vegas code.
Definition at line 148 of file pathwiseproductcaplet.hpp.
Constructor & Destructor Documentation
QuantLib::MarketModelPathwiseMultiDeflatedCap::MarketModelPathwiseMultiDeflatedCap (const std::vector< Time > & rateTimes, const std::vector< Real > & accruals, const std::vector< Time > & paymentTimes, Rate strike, const std::vector< std::pair< Size, Size > > & startsAndEnds)
Definition at line 283 of file pathwiseproductcaplet.cpp.
References innerCashFlowsGenerated_, innerCashFlowSizes_, QuantLib::MarketModelPathwiseMultiDeflatedCaplet::maxNumberOfCashFlowsPerProductPerStep(), QL_REQUIRE, startsAndEnds_, and underlyingCaplets_.
Referenced by clone().
        : underlyingCaplets_(rateTimes, accruals, paymentTimes, strike),numberRates_(accruals.size()),
        startsAndEnds_(startsAndEnds)
    {
        for (Size j=0; j < startsAndEnds_.size(); ++j)
        {
            QL_REQUIRE(startsAndEnds_[j].first < startsAndEnds_[j].second,"a cap must start before it ends: " << j << startsAndEnds_[j].first << startsAndEnds_[j].second );
            QL_REQUIRE(startsAndEnds_[j].second <= accruals.size() ,"a cap must end when the underlying caplets: " << j << startsAndEnds_[j].first << startsAndEnds_[j].second );
        }
        innerCashFlowSizes_.resize(accruals.size());
        innerCashFlowsGenerated_.resize(accruals.size());
        for (Size i=0; i <  innerCashFlowsGenerated_.size(); ++i)
        {
            innerCashFlowsGenerated_[i].resize(underlyingCaplets_.maxNumberOfCashFlowsPerProductPerStep());
            for (Size j=0; j < underlyingCaplets_.maxNumberOfCashFlowsPerProductPerStep(); ++j)
                innerCashFlowsGenerated_[i][j].amount.resize(accruals.size()+1);
        }
    }
virtual QuantLib::MarketModelPathwiseMultiDeflatedCap::~MarketModelPathwiseMultiDeflatedCap () [inline, virtual]
Definition at line 161 of file pathwiseproductcaplet.hpp.
{}
Member Function Documentation
bool QuantLib::MarketModelPathwiseMultiDeflatedCap::alreadyDeflated () const [virtual]
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 339 of file pathwiseproductcaplet.cpp.
References QuantLib::MarketModelPathwiseMultiDeflatedCaplet::alreadyDeflated(), and underlyingCaplets_.
    {
        return underlyingCaplets_.alreadyDeflated();
    }
std::auto_ptr< MarketModelPathwiseMultiProduct > QuantLib::MarketModelPathwiseMultiDeflatedCap::clone () const [virtual]
returns a newly-allocated copy of itself
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 381 of file pathwiseproductcaplet.cpp.
References MarketModelPathwiseMultiDeflatedCap().
    {
        return std::auto_ptr<MarketModelPathwiseMultiProduct>(
                              new MarketModelPathwiseMultiDeflatedCap(*this));
    }
const EvolutionDescription & QuantLib::MarketModelPathwiseMultiDeflatedCap::evolution () const [virtual]
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 319 of file pathwiseproductcaplet.cpp.
References QuantLib::MarketModelPathwiseMultiDeflatedCaplet::evolution(), and underlyingCaplets_.
    {
        return underlyingCaplets_.evolution();
    }
Size QuantLib::MarketModelPathwiseMultiDeflatedCap::maxNumberOfCashFlowsPerProductPerStep () const [virtual]
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 333 of file pathwiseproductcaplet.cpp.
References QuantLib::MarketModelPathwiseMultiDeflatedCaplet::maxNumberOfCashFlowsPerProductPerStep(), and underlyingCaplets_.
    {
        return underlyingCaplets_.maxNumberOfCashFlowsPerProductPerStep();
    }
bool QuantLib::MarketModelPathwiseMultiDeflatedCap::nextTimeStep (const CurveState & currentState, std::vector< Size > & numberCashFlowsThisStep, std::vector< std::vector< MarketModelPathwiseMultiProduct::CashFlow > > & cashFlowsGenerated) [virtual]
return value indicates whether path is finished, TRUE means done
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 352 of file pathwiseproductcaplet.cpp.
References innerCashFlowsGenerated_, innerCashFlowSizes_, QuantLib::MarketModelPathwiseMultiDeflatedCaplet::nextTimeStep(), numberRates_, startsAndEnds_, and underlyingCaplets_.
    {
        bool done = underlyingCaplets_.nextTimeStep(currentState, innerCashFlowSizes_, innerCashFlowsGenerated_);
        for (Size k=0; k < startsAndEnds_.size(); ++k)
            numberCashFlowsThisStep[k]=0;
        for (Size j=0; j < numberRates_; ++j)
        {
            if (innerCashFlowSizes_[j]>0)
            {
                for (Size k=0; k < startsAndEnds_.size(); ++k)
                {
                    if (startsAndEnds_[k].first <= j && j < startsAndEnds_[k].second)
                    {
                        for (Size l=0; l < innerCashFlowSizes_[j]; ++l)
                            cashFlowsGenerated[k][numberCashFlowsThisStep[k]++] = innerCashFlowsGenerated_[j][l];
                    }
                }
            }
        }
        return done;
    }
Size QuantLib::MarketModelPathwiseMultiDeflatedCap::numberOfProducts () const [virtual]
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 329 of file pathwiseproductcaplet.cpp.
References startsAndEnds_.
Referenced by MarketModelTest::testPathwiseMarketVegas(), and MarketModelTest::testPathwiseVegas().
    {
        return startsAndEnds_.size();
    }
std::vector< Time > QuantLib::MarketModelPathwiseMultiDeflatedCap::possibleCashFlowTimes () const [virtual]
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 324 of file pathwiseproductcaplet.cpp.
References QuantLib::MarketModelPathwiseMultiDeflatedCaplet::possibleCashFlowTimes(), and underlyingCaplets_.
    {
        return underlyingCaplets_.possibleCashFlowTimes();
    }
void QuantLib::MarketModelPathwiseMultiDeflatedCap::reset () [virtual]
during simulation put product at start of path
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 345 of file pathwiseproductcaplet.cpp.
References currentIndex_, QuantLib::MarketModelPathwiseMultiDeflatedCaplet::reset(), and underlyingCaplets_.
    {
        underlyingCaplets_.reset();
        currentIndex_=0;
    }
std::vector< Size > QuantLib::MarketModelPathwiseMultiDeflatedCap::suggestedNumeraires () const [virtual]
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 313 of file pathwiseproductcaplet.cpp.
References QuantLib::MarketModelPathwiseMultiDeflatedCaplet::suggestedNumeraires(), and underlyingCaplets_.
Referenced by MarketModelTest::testPathwiseMarketVegas().
    {
        return underlyingCaplets_.suggestedNumeraires();
    }
Member Data Documentation
Size QuantLib::MarketModelPathwiseMultiDeflatedCap::currentIndex_ [private]
Definition at line 194 of file pathwiseproductcaplet.hpp.
Referenced by reset().
std::vector<std::vector<MarketModelPathwiseMultiProduct::CashFlow> > QuantLib::MarketModelPathwiseMultiDeflatedCap::innerCashFlowsGenerated_ [private]
Definition at line 196 of file pathwiseproductcaplet.hpp.
Referenced by MarketModelPathwiseMultiDeflatedCap(), and nextTimeStep().
std::vector<Size> QuantLib::MarketModelPathwiseMultiDeflatedCap::innerCashFlowSizes_ [private]
Definition at line 195 of file pathwiseproductcaplet.hpp.
Referenced by MarketModelPathwiseMultiDeflatedCap(), and nextTimeStep().
Size QuantLib::MarketModelPathwiseMultiDeflatedCap::numberRates_ [private]
Definition at line 189 of file pathwiseproductcaplet.hpp.
Referenced by nextTimeStep().
std::vector<std::pair<Size,Size> > QuantLib::MarketModelPathwiseMultiDeflatedCap::startsAndEnds_ [private]
Definition at line 191 of file pathwiseproductcaplet.hpp.
Referenced by MarketModelPathwiseMultiDeflatedCap(), nextTimeStep(), and numberOfProducts().
MarketModelPathwiseMultiDeflatedCaplet QuantLib::MarketModelPathwiseMultiDeflatedCap::underlyingCaplets_ [private]
Definition at line 187 of file pathwiseproductcaplet.hpp.
Referenced by alreadyDeflated(), evolution(), MarketModelPathwiseMultiDeflatedCap(), maxNumberOfCashFlowsPerProductPerStep(), nextTimeStep(), possibleCashFlowTimes(), reset(), and suggestedNumeraires().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/products/pathwise/pathwiseproductcaplet.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/products/pathwise/pathwiseproductcaplet.cpp