QuantLib: QuantLib::IntervalPrice Class Reference
QuantLib::IntervalPrice Class Reference
interval price
#include <prices.hpp>
Public Types
enum Type { Open, Close, High, Low }
Public Member Functions
IntervalPrice ()
IntervalPrice (Real open, Real close, Real high, Real low)
Inspectors
Real open () const
Real close () const
Real high () const
Real low () const
Real value (IntervalPrice::Type) const
Modifiers
void setValue (Real value, IntervalPrice::Type)
void setValues (Real open, Real close, Real high, Real low)
Static Public Member Functions
Helper functions
static TimeSeries< IntervalPrice > makeSeries (const std::vector< Date > &d, const std::vector< Real > &open, const std::vector< Real > &close, const std::vector< Real > &high, const std::vector< Real > &low)
static std::vector< Real > extractValues (const TimeSeries< IntervalPrice > &, IntervalPrice::Type)
static TimeSeries< Real > extractComponent (const TimeSeries< IntervalPrice > &, enum IntervalPrice::Type)
Private Attributes
Real open_
Real close_
Real high_
Real low_
Detailed Description
interval price
Definition at line 66 of file prices.hpp.
Member Enumeration Documentation
enum QuantLib::IntervalPrice::Type
Enumerator:
Open
Close
High
Low
Definition at line 68 of file prices.hpp.
{ Open, Close, High, Low };
Constructor & Destructor Documentation
QuantLib::IntervalPrice::IntervalPrice ()
Definition at line 57 of file prices.cpp.
Referenced by makeSeries().
    : open_(Null<Real>()), close_(Null<Real>()),
      high_(Null<Real>()), low_(Null<Real>()) {}
QuantLib::IntervalPrice::IntervalPrice (Real open, Real close, Real high, Real low)
Definition at line 61 of file prices.cpp.
    : open_(open), close_(close), high_(high), low_(low) {}
Member Function Documentation
Real QuantLib::IntervalPrice::close () const [inline]
Definition at line 76 of file prices.hpp.
References close_.
Referenced by QuantLib::GarmanKlassSimpleSigma::calculatePoint(), QuantLib::GarmanKlassSigma4::calculatePoint(), QuantLib::GarmanKlassSigma5::calculatePoint(), and setValues().
{ return close_; }
TimeSeries< Real > QuantLib::IntervalPrice::extractComponent (const TimeSeries< IntervalPrice > & ts, enum IntervalPrice::Type t) [static]
Definition at line 140 of file prices.cpp.
References anonymous_namespace{marketmodel.cpp}::dates, QuantLib::TimeSeries< T, Container >::dates(), and extractValues().
{
        std::vector<Date> dates = ts.dates();
        std::vector<Real> values = extractValues(ts, t);
        return TimeSeries<Real>(dates.begin(), dates.end(), values.begin());
    }
std::vector< Real > QuantLib::IntervalPrice::extractValues (const TimeSeries< IntervalPrice > & ts, IntervalPrice::Type t) [static]
Definition at line 128 of file prices.cpp.
References QuantLib::TimeSeries< T, Container >::begin(), QuantLib::TimeSeries< T, Container >::end(), and QuantLib::TimeSeries< T, Container >::size().
Referenced by extractComponent().
{
        std::vector<Real> returnval;
        returnval.reserve(ts.size());
        for (TimeSeries<IntervalPrice>::const_iterator i = ts.begin();
             i != ts.end(); i++) {
            returnval.push_back(i->second.value(t));
        }
        return returnval;
    }
Real QuantLib::IntervalPrice::high () const [inline]
Definition at line 77 of file prices.hpp.
References high_.
Referenced by QuantLib::ParkinsonSigma::calculatePoint(), QuantLib::GarmanKlassSigma4::calculatePoint(), QuantLib::GarmanKlassSigma5::calculatePoint(), and setValues().
{ return high_; }
Real QuantLib::IntervalPrice::low () const [inline]
Definition at line 78 of file prices.hpp.
References low_.
Referenced by QuantLib::ParkinsonSigma::calculatePoint(), QuantLib::GarmanKlassSigma4::calculatePoint(), QuantLib::GarmanKlassSigma5::calculatePoint(), and setValues().
{ return low_; }
TimeSeries< IntervalPrice > QuantLib::IntervalPrice::makeSeries (const std::vector< Date > & d, const std::vector< Real > & open, const std::vector< Real > & close, const std::vector< Real > & high, const std::vector< Real > & low) [static]
Definition at line 100 of file prices.cpp.
References IntervalPrice(), and QL_REQUIRE.
Referenced by TimeSeriesTest::testIntervalPrice().
{
        Size dsize = d.size();
        QL_REQUIRE((open.size() == dsize && close.size() == dsize &&
                    high.size() == dsize && low.size() == dsize),
                   "size mismatch (" << dsize << ", "
                                     << open.size() << ", "
                                     << close.size() << ", "
                                     << high.size() << ", "
                                     << low.size() << ")");
        TimeSeries<IntervalPrice> retval;
        std::vector<Date>::const_iterator i;
        std::vector<Real>::const_iterator openi, closei, highi, lowi;
        openi = open.begin();
        closei = close.begin();
        highi = high.begin();
        lowi = low.begin();
        for (i = d.begin(); i != d.end(); i++) {
            retval[*i] = IntervalPrice(*openi, *closei, *highi, *lowi);
            ++openi; ++closei; ++highi; ++lowi;
        }
        return retval;
    }
Real QuantLib::IntervalPrice::open () const [inline]
Definition at line 75 of file prices.hpp.
References open_.
Referenced by QuantLib::GarmanKlassSimpleSigma::calculatePoint(), QuantLib::ParkinsonSigma::calculatePoint(), QuantLib::GarmanKlassSigma4::calculatePoint(), QuantLib::GarmanKlassSigma5::calculatePoint(), and setValues().
{ return open_; }
void QuantLib::IntervalPrice::setValue (Real value, IntervalPrice::Type t)
Definition at line 79 of file prices.cpp.
References Close, close_, High, high_, Low, low_, Open, open_, QL_FAIL, and value().
{
        switch(t) {
          case Open:
            open_ = value;
          case Close:
            close_ = value;
          case High:
            high_ = value;
          case Low:
            low_ = value;
          default:
            QL_FAIL("Unknown price type");
        }
    }
void QuantLib::IntervalPrice::setValues (Real open, Real close, Real high, Real low)
Definition at line 95 of file prices.cpp.
References close(), close_, high(), high_, low(), low_, open(), and open_.
{
        open_ = open; close_ = close; high_ = high; low_ = low;
    }
Real QuantLib::IntervalPrice::value (IntervalPrice::Type t) const
Definition at line 64 of file prices.cpp.
References Close, close_, High, high_, Low, low_, Open, open_, and QL_FAIL.
Referenced by setValue().
{
        switch(t) {
          case Open:
            return open_;
          case Close:
            return close_;
          case High:
            return high_;
          case Low:
            return low_;
          default:
            QL_FAIL("Unknown price type");
        }
    }
Member Data Documentation
Real QuantLib::IntervalPrice::close_ [private]
Definition at line 104 of file prices.hpp.
Referenced by close(), setValue(), setValues(), and value().
Real QuantLib::IntervalPrice::high_ [private]
Definition at line 104 of file prices.hpp.
Referenced by high(), setValue(), setValues(), and value().
Real QuantLib::IntervalPrice::low_ [private]
Definition at line 104 of file prices.hpp.
Referenced by low(), setValue(), setValues(), and value().
Real QuantLib::IntervalPrice::open_ [private]
Definition at line 104 of file prices.hpp.
Referenced by open(), setValue(), setValues(), and value().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/prices.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/prices.cpp