QuantLib: QuantLib::KnuthUniformRng Class Reference
QuantLib::KnuthUniformRng Class Reference
Uniform random number generator.
#include <knuthuniformrng.hpp>
Public Types
typedef Sample< Real > sample_type
Public Member Functions
KnuthUniformRng (long seed=0)
sample_type next () const
Private Member Functions
double mod_sum (double x, double y) const
bool is_odd (int s) const
void ranf_start (long seed)
void ranf_array (std::vector< double > &aa, int n) const
double ranf_arr_cycle () const
Private Attributes
std::vector< double > ranf_arr_buf
size_t ranf_arr_ptr
size_t ranf_arr_sentinel
std::vector< double > ran_u
Static Private Attributes
static const int KK = 100
static const int LL = 37
static const int TT = 70
static const int QUALITY = 1009
Detailed Description
Uniform random number generator.
Random number generator by Knuth. For more details see Knuth, Seminumerical Algorithms, 3rd edition, Section 3.6.
Note:
This is not Knuth's original implementation which is available at http://www-cs-faculty.stanford.edu/~knuth/programs.html, but rather a slightly modified version wrapped in a C++ class. Such modifications did not affect the code but only the data structures used, which were converted to their standard C++ equivalents.
Definition at line 44 of file knuthuniformrng.hpp.
Member Typedef Documentation
typedef Sample<Real> QuantLib::KnuthUniformRng::sample_type
Definition at line 46 of file knuthuniformrng.hpp.
Constructor & Destructor Documentation
QuantLib::KnuthUniformRng::KnuthUniformRng (long seed = 0) [explicit]
if the given seed is 0, a random seed will be chosen based on clock()
Definition at line 30 of file knuthuniformrng.cpp.
References QuantLib::Singleton< SeedGenerator >::instance(), ranf_arr_buf, ranf_arr_ptr, ranf_arr_sentinel, and ranf_start().
    : ranf_arr_buf(QUALITY), ran_u(QUALITY) {
        ranf_arr_ptr = ranf_arr_sentinel = ranf_arr_buf.size();
        ranf_start(seed != 0 ? seed : SeedGenerator::instance().get());
    }
Member Function Documentation
bool QuantLib::KnuthUniformRng::is_odd (int s) const [inline, private]
Definition at line 79 of file knuthuniformrng.hpp.
Referenced by ranf_start().
{
        return (s&1) != 0;
    }
double QuantLib::KnuthUniformRng::mod_sum (double x, double y) const [inline, private]
Definition at line 75 of file knuthuniformrng.hpp.
Referenced by ranf_array(), and ranf_start().
{
        return (x+y)-int(x+y);
    }
KnuthUniformRng::sample_type QuantLib::KnuthUniformRng::next () const [inline]
returns a sample with weight 1.0 containing a random number uniformly chosen from (0.0,1.0)
Definition at line 68 of file knuthuniformrng.hpp.
References ranf_arr_buf, ranf_arr_cycle(), ranf_arr_ptr, and ranf_arr_sentinel.
{
        double result = (ranf_arr_ptr != ranf_arr_sentinel ?
                         ranf_arr_buf[ranf_arr_ptr++] :
                         ranf_arr_cycle());
        return sample_type(result,1.0);
    }
double QuantLib::KnuthUniformRng::ranf_arr_cycle () const [private]
Definition at line 78 of file knuthuniformrng.cpp.
References QUALITY, ranf_arr_buf, ranf_arr_ptr, ranf_arr_sentinel, and ranf_array().
Referenced by next().
{
        ranf_array(ranf_arr_buf,QUALITY);
        ranf_arr_ptr = 1;
        ranf_arr_sentinel = 100;
        return ranf_arr_buf[0];
    }
void QuantLib::KnuthUniformRng::ranf_array (std::vector< double > & aa, int n) const [private]
Definition at line 69 of file knuthuniformrng.cpp.
References KK, LL, mod_sum(), and ran_u.
Referenced by ranf_arr_cycle().
{
        int i,j;
        for (j=0;j<KK;j++) aa[j]=ran_u[j];
        for (;j<n;j++) aa[j]=mod_sum(aa[j-KK],aa[j-LL]);
        for (i=0;i<LL;i++,j++) ran_u[i]=mod_sum(aa[j-KK],aa[j-LL]);
        for (;i<KK;i++,j++) ran_u[i]=mod_sum(aa[j-KK],ran_u[i-LL]);
    }
void QuantLib::KnuthUniformRng::ranf_start (long seed) [private]
Definition at line 36 of file knuthuniformrng.cpp.
References is_odd(), KK, LL, mod_sum(), ran_u, anonymous_namespace{quantlibbenchmark.cpp}::t, and TT.
Referenced by KnuthUniformRng().
{
        int t,s,j;
        std::vector<double> u(KK+KK-1),ul(KK+KK-1);
        double ulp=(1.0/(1L<<30))/(1L<<22);                // 2 to the -52
        double ss=2.0*ulp*((seed&0x3fffffff)+2);
        for (j=0;j<KK;j++) {
            u[j]=ss; ul[j]=0.0;                    // bootstrap the buffer
            ss+=ss; if (ss>=1.0) ss-=1.0-2*ulp; // cyclic shift of 51 bits
        }
        for (;j<KK+KK-1;j++) u[j]=ul[j]=0.0;
        u[1]+=ulp;ul[1]=ulp;            // make u[1] (and only u[1]) "odd"
        s=seed&0x3fffffff;
        t=TT-1; while (t) {
            for (j=KK-1;j>0;--j) ul[j+j]=ul[j],u[j+j]=u[j];    // "square"
            for (j=KK+KK-2;j>KK-LL;j-=2)
                ul[KK+KK-1-j]=0.0,u[KK+KK-1-j]=u[j]-ul[j];
            for (j=KK+KK-2;j>=KK;--j) if(ul[j]) {
                ul[j-(KK-LL)]=ulp-ul[j-(KK-LL)],
                    u[j-(KK-LL)]=mod_sum(u[j-(KK-LL)],u[j]);
                ul[j-KK]=ulp-ul[j-KK],u[j-KK]=mod_sum(u[j-KK],u[j]);
            }
            if (is_odd(s)) {                            // "multiply by z"
                for (j=KK;j>0;--j)  ul[j]=ul[j-1],u[j]=u[j-1];
                ul[0]=ul[KK],u[0]=u[KK];    // shift the buffer cyclically
                if (ul[KK]) ul[LL]=ulp-ul[LL],u[LL]=mod_sum(u[LL],u[KK]);
            }
            if (s) s>>=1; else t--;
        }
        for (j=0;j<LL;j++) ran_u[j+KK-LL]=u[j];
        for (;j<KK;j++) ran_u[j-LL]=u[j];
    }
Member Data Documentation
const int QuantLib::KnuthUniformRng::KK = 100 [static, private]
Definition at line 54 of file knuthuniformrng.hpp.
Referenced by ranf_array(), and ranf_start().
const int QuantLib::KnuthUniformRng::LL = 37 [static, private]
Definition at line 54 of file knuthuniformrng.hpp.
Referenced by ranf_array(), and ranf_start().
const int QuantLib::KnuthUniformRng::QUALITY = 1009 [static, private]
Definition at line 54 of file knuthuniformrng.hpp.
Referenced by ranf_arr_cycle().
std::vector<double> QuantLib::KnuthUniformRng::ran_u [mutable, private]
Definition at line 57 of file knuthuniformrng.hpp.
Referenced by ranf_array(), and ranf_start().
std::vector<double> QuantLib::KnuthUniformRng::ranf_arr_buf [mutable, private]
Definition at line 55 of file knuthuniformrng.hpp.
Referenced by KnuthUniformRng(), next(), and ranf_arr_cycle().
size_t QuantLib::KnuthUniformRng::ranf_arr_ptr [mutable, private]
Definition at line 56 of file knuthuniformrng.hpp.
Referenced by KnuthUniformRng(), next(), and ranf_arr_cycle().
size_t QuantLib::KnuthUniformRng::ranf_arr_sentinel [mutable, private]
Definition at line 56 of file knuthuniformrng.hpp.
Referenced by KnuthUniformRng(), next(), and ranf_arr_cycle().
const int QuantLib::KnuthUniformRng::TT = 70 [static, private]
Definition at line 54 of file knuthuniformrng.hpp.
Referenced by ranf_start().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/randomnumbers/knuthuniformrng.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/math/randomnumbers/knuthuniformrng.cpp