QuantLib: QuantLib::FlatVolFactory Class Reference
QuantLib::FlatVolFactory Class Reference
#include <flatvol.hpp>
Public Member Functions
FlatVolFactory (Real longTermCorrelation, Real beta, const std::vector< Time > &times, const std::vector< Volatility > &vols, const Handle< YieldTermStructure > &yieldCurve, Spread displacement)
boost::shared_ptr< MarketModel > create (const EvolutionDescription &, Size numberOfFactors) const
void update ()
Private Attributes
Real longTermCorrelation_
Real beta_
std::vector< Time > times_
std::vector< Volatility > vols_
Interpolation volatility_
Handle< YieldTermStructure > yieldCurve_
Spread displacement_
Detailed Description
Definition at line 66 of file flatvol.hpp.
Constructor & Destructor Documentation
QuantLib::FlatVolFactory::FlatVolFactory (Real longTermCorrelation, Real beta, const std::vector< Time > & times, const std::vector< Volatility > & vols, const Handle< YieldTermStructure > & yieldCurve, Spread displacement)
Definition at line 154 of file flatvol.cpp.
References QuantLib::Observer::registerWith(), times_, QuantLib::Interpolation::update(), volatility_, vols_, and yieldCurve_.
    : longTermCorrelation_(longTermCorrelation), beta_(beta),
      times_(times), vols_(vols), yieldCurve_(yieldCurve),
      displacement_(displacement) {
        volatility_ = LinearInterpolation(times_.begin(), times_.end(),
                                          vols_.begin());
        volatility_.update();
        registerWith(yieldCurve_);
    }
Member Function Documentation
boost::shared_ptr< MarketModel > QuantLib::FlatVolFactory::create (const EvolutionDescription & evolution, Size numberOfFactors) const [virtual]
Implements QuantLib::MarketModelFactory.
Definition at line 171 of file flatvol.cpp.
References beta_, displacement_, QuantLib::exponentialCorrelations(), longTermCorrelation_, QuantLib::EvolutionDescription::rateTimes(), anonymous_namespace{marketmodel.cpp}::rateTimes, QuantLib::Simple, volatility_, and yieldCurve_.
{
        const std::vector<Time>& rateTimes = evolution.rateTimes();
        Size numberOfRates = rateTimes.size()-1;
        std::vector<Rate> initialRates(numberOfRates);
        for (Size i=0; i<numberOfRates; ++i)
            initialRates[i] = yieldCurve_->forwardRate(rateTimes[i],
                                                       rateTimes[i+1],
                                                       Simple);
        std::vector<Volatility> displacedVolatilities(numberOfRates);
        for (Size i=0; i<numberOfRates; ++i) {
            Volatility vol = // to be changes
                volatility_(rateTimes[i]);
            displacedVolatilities[i] =
                initialRates[i]*vol/(initialRates[i]+displacement_);
        }
        std::vector<Spread> displacements(numberOfRates, displacement_);
        Matrix correlations = exponentialCorrelations(evolution.rateTimes(),
                                                      longTermCorrelation_,
                                                      beta_);
        boost::shared_ptr<PiecewiseConstantCorrelation> corr(new
            TimeHomogeneousForwardCorrelation(correlations,
                                              rateTimes));
        return boost::shared_ptr<MarketModel>(new
            FlatVol(displacedVolatilities,
                           corr,
                           evolution,
                           numberOfFactors,
                           initialRates,
                           displacements));
    }
void QuantLib::FlatVolFactory::update () [virtual]
This method must be implemented in derived classes. An instance of Observer does not call this method directly: instead, it will be called by the observables the instance registered with when they need to notify any changes.
Implements QuantLib::Observer.
Definition at line 207 of file flatvol.cpp.
References QuantLib::Observable::notifyObservers().
{
        notifyObservers();
    }
Member Data Documentation
Real QuantLib::FlatVolFactory::beta_ [private]
Definition at line 85 of file flatvol.hpp.
Referenced by create().
Spread QuantLib::FlatVolFactory::displacement_ [private]
Definition at line 92 of file flatvol.hpp.
Referenced by create().
Real QuantLib::FlatVolFactory::longTermCorrelation_ [private]
Definition at line 85 of file flatvol.hpp.
Referenced by create().
std::vector<Time> QuantLib::FlatVolFactory::times_ [private]
Definition at line 87 of file flatvol.hpp.
Referenced by FlatVolFactory().
Interpolation QuantLib::FlatVolFactory::volatility_ [private]
Definition at line 89 of file flatvol.hpp.
Referenced by create(), and FlatVolFactory().
std::vector<Volatility> QuantLib::FlatVolFactory::vols_ [private]
Definition at line 88 of file flatvol.hpp.
Referenced by FlatVolFactory().
Handle<YieldTermStructure> QuantLib::FlatVolFactory::yieldCurve_ [private]
Definition at line 91 of file flatvol.hpp.
Referenced by create(), and FlatVolFactory().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/models/flatvol.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/models/flatvol.cpp