QuantLib: QuantLib::SwaptionVolatilityMatrix Class Reference
QuantLib::SwaptionVolatilityMatrix Class Reference
At-the-money swaption-volatility matrix.
#include <swaptionvolmatrix.hpp>
Public Member Functions
SwaptionVolatilityMatrix (const Calendar &calendar, BusinessDayConvention bdc, const std::vector< Period > &optionTenors, const std::vector< Period > &swapTenors, const std::vector< std::vector< Handle< Quote > > > &vols, const DayCounter &dayCounter)
floating reference date, floating market data
SwaptionVolatilityMatrix (const Date &referenceDate, const Calendar &calendar, BusinessDayConvention bdc, const std::vector< Period > &optionTenors, const std::vector< Period > &swapTenors, const std::vector< std::vector< Handle< Quote > > > &vols, const DayCounter &dayCounter)
fixed reference date, floating market data
SwaptionVolatilityMatrix (const Calendar &calendar, BusinessDayConvention bdc, const std::vector< Period > &optionTenors, const std::vector< Period > &swapTenors, const Matrix &volatilities, const DayCounter &dayCounter)
floating reference date, fixed market data
SwaptionVolatilityMatrix (const Date &referenceDate, const Calendar &calendar, BusinessDayConvention bdc, const std::vector< Period > &optionTenors, const std::vector< Period > &swapTenors, const Matrix &volatilities, const DayCounter &dayCounter)
fixed reference date, fixed market data
SwaptionVolatilityMatrix (const Date &referenceDate, const std::vector< Date > &optionDates, const std::vector< Period > &swapTenors, const Matrix &volatilities, const DayCounter &dayCounter)
LazyObject interface
void performCalculations () const
TermStructure interface
Date maxDate () const
the latest date for which the curve can return values
VolatilityTermStructure interface
Rate minStrike () const
the minimum strike for which the term structure can return vols
Rate maxStrike () const
the maximum strike for which the term structure can return vols
SwaptionVolatilityStructure interface
const Period & maxSwapTenor () const
the largest length for which the term structure can return vols
Other inspectors
std::pair< Size, Size > locate (const Date &optionDate, const Period &swapTenor) const
returns the lower indexes of surrounding volatility matrix corners
std::pair< Size, Size > locate (Time optionTime, Time swapLength) const
returns the lower indexes of surrounding volatility matrix corners
Protected Member Functions
boost::shared_ptr< SmileSection > smileSectionImpl (Time, Time) const
Volatility volatilityImpl (Time optionTime, Time swapLength, Rate strike) const
Private Member Functions
void checkInputs (Size volRows, Size volsColumns) const
void registerWithMarketData ()
Private Attributes
std::vector< std::vector
< Handle< Quote > > > volHandles_
Matrix volatilities_
Interpolation2D interpolation_
Detailed Description
At-the-money swaption-volatility matrix.
This class provides the at-the-money volatility for a given swaption by interpolating a volatility matrix whose elements are the market volatilities of a set of swaption with given option date and swapLength.
The volatility matrix M must be defined so that:
the number of rows equals the number of option dates;
the number of columns equals the number of swap tenors;
M[i][j] contains the volatility corresponding to the i-th option and j-th tenor.
Definition at line 51 of file swaptionvolmatrix.hpp.
Constructor & Destructor Documentation
QuantLib::SwaptionVolatilityMatrix::SwaptionVolatilityMatrix (const Calendar & calendar, BusinessDayConvention bdc, const std::vector< Period > & optionTenors, const std::vector< Period > & swapTenors, const std::vector< std::vector< Handle< Quote > > > & vols, const DayCounter & dayCounter)
floating reference date, floating market data
Definition at line 33 of file swaptionvolmatrix.cpp.
References checkInputs(), QuantLib::Matrix::columns(), interpolation_, QuantLib::SwaptionVolatilityDiscrete::optionTimes_, registerWithMarketData(), QuantLib::Matrix::rows(), QuantLib::SwaptionVolatilityDiscrete::swapLengths_, and volatilities_.
    : SwaptionVolatilityDiscrete(optionT, swapT, 0, cal, bdc, dc),
      volHandles_(vols),
      volatilities_(vols.size(), vols.front().size()) {
        checkInputs(volatilities_.rows(), volatilities_.columns());
        registerWithMarketData();
        interpolation_ =
            BilinearInterpolation(swapLengths_.begin(), swapLengths_.end(),
                                  optionTimes_.begin(), optionTimes_.end(),
                                  volatilities_);
   }
QuantLib::SwaptionVolatilityMatrix::SwaptionVolatilityMatrix (const Date & referenceDate, const Calendar & calendar, BusinessDayConvention bdc, const std::vector< Period > & optionTenors, const std::vector< Period > & swapTenors, const std::vector< std::vector< Handle< Quote > > > & vols, const DayCounter & dayCounter)
fixed reference date, floating market data
Definition at line 52 of file swaptionvolmatrix.cpp.
References checkInputs(), QuantLib::Matrix::columns(), interpolation_, QuantLib::SwaptionVolatilityDiscrete::optionTimes_, registerWithMarketData(), QuantLib::Matrix::rows(), QuantLib::SwaptionVolatilityDiscrete::swapLengths_, and volatilities_.
    : SwaptionVolatilityDiscrete(optionT, swapT, refDate, cal, bdc, dc),
      volHandles_(vols),
      volatilities_(vols.size(), vols.front().size()) {
        checkInputs(volatilities_.rows(), volatilities_.columns());
        registerWithMarketData();
        interpolation_ =
            BilinearInterpolation(swapLengths_.begin(), swapLengths_.end(),
                                  optionTimes_.begin(), optionTimes_.end(),
                                  volatilities_);
    }
QuantLib::SwaptionVolatilityMatrix::SwaptionVolatilityMatrix (const Calendar & calendar, BusinessDayConvention bdc, const std::vector< Period > & optionTenors, const std::vector< Period > & swapTenors, const Matrix & volatilities, const DayCounter & dayCounter)
floating reference date, fixed market data
Definition at line 72 of file swaptionvolmatrix.cpp.
References checkInputs(), QuantLib::Matrix::columns(), interpolation_, QuantLib::SwaptionVolatilityDiscrete::optionTimes_, QuantLib::Matrix::rows(), QuantLib::SwaptionVolatilityDiscrete::swapLengths_, volatilities_, and volHandles_.
    : SwaptionVolatilityDiscrete(optionT, swapT, 0, cal, bdc, dc),
      volHandles_(vols.rows()),
      volatilities_(vols.rows(), vols.columns()) {
        checkInputs(vols.rows(), vols.columns());
        // fill dummy handles to allow generic handle-based
        // computations later on
        for (Size i=0; i<vols.rows(); ++i) {
            volHandles_[i].resize(vols.columns());
            for (Size j=0; j<vols.columns(); ++j)
                volHandles_[i][j] = Handle<Quote>(boost::shared_ptr<Quote>(new
                    SimpleQuote(vols[i][j])));
        }
        interpolation_ =
            BilinearInterpolation(swapLengths_.begin(), swapLengths_.end(),
                                  optionTimes_.begin(), optionTimes_.end(),
                                  volatilities_);
    }
QuantLib::SwaptionVolatilityMatrix::SwaptionVolatilityMatrix (const Date & referenceDate, const Calendar & calendar, BusinessDayConvention bdc, const std::vector< Period > & optionTenors, const std::vector< Period > & swapTenors, const Matrix & volatilities, const DayCounter & dayCounter)
fixed reference date, fixed market data
Definition at line 100 of file swaptionvolmatrix.cpp.
References checkInputs(), QuantLib::Matrix::columns(), interpolation_, QuantLib::SwaptionVolatilityDiscrete::optionTimes_, QuantLib::Matrix::rows(), QuantLib::SwaptionVolatilityDiscrete::swapLengths_, volatilities_, and volHandles_.
    : SwaptionVolatilityDiscrete(optionT, swapT, refDate, cal, bdc, dc),
      volHandles_(vols.rows()),
      volatilities_(vols.rows(), vols.columns()) {
        checkInputs(vols.rows(), vols.columns());
        // fill dummy handles to allow generic handle-based
        // computations later on
        for (Size i=0; i<vols.rows(); ++i) {
            volHandles_[i].resize(vols.columns());
            for (Size j=0; j<vols.columns(); ++j)
                volHandles_[i][j] = Handle<Quote>(boost::shared_ptr<Quote>(new
                    SimpleQuote(vols[i][j])));
        }
        interpolation_ =
            BilinearInterpolation(swapLengths_.begin(), swapLengths_.end(),
                                  optionTimes_.begin(), optionTimes_.end(),
                                  volatilities_);
    }
QuantLib::SwaptionVolatilityMatrix::SwaptionVolatilityMatrix (const Date & referenceDate, const std::vector< Date > & optionDates, const std::vector< Period > & swapTenors, const Matrix & volatilities, const DayCounter & dayCounter)
Definition at line 129 of file swaptionvolmatrix.cpp.
References checkInputs(), QuantLib::Matrix::columns(), interpolation_, QuantLib::SwaptionVolatilityDiscrete::optionTimes_, QuantLib::Matrix::rows(), QuantLib::SwaptionVolatilityDiscrete::swapLengths_, volatilities_, and volHandles_.
    : SwaptionVolatilityDiscrete(optionDates, swapT, today, Calendar(), Following, dc),
      volHandles_(vols.rows()),
      volatilities_(vols.rows(), vols.columns()) {
        checkInputs(vols.rows(), vols.columns());
        // fill dummy handles to allow generic handle-based
        // computations later on
        for (Size i=0; i<vols.rows(); ++i) {
            volHandles_[i].resize(vols.columns());
            for (Size j=0; j<vols.columns(); ++j)
                volHandles_[i][j] = Handle<Quote>(boost::shared_ptr<Quote>(new
                    SimpleQuote(vols[i][j])));
        }
        interpolation_ =
            BilinearInterpolation(swapLengths_.begin(), swapLengths_.end(),
                                  optionTimes_.begin(), optionTimes_.end(),
                                  volatilities_);
    }
Member Function Documentation
void QuantLib::SwaptionVolatilityMatrix::checkInputs (Size volRows, Size volsColumns) const [private]
Definition at line 155 of file swaptionvolmatrix.cpp.
References QuantLib::SwaptionVolatilityDiscrete::nOptionTenors_, QuantLib::SwaptionVolatilityDiscrete::nSwapTenors_, and QL_REQUIRE.
Referenced by SwaptionVolatilityMatrix().
{
        QL_REQUIRE(nOptionTenors_==volRows,
                   "mismatch between number of option dates (" <<
                   nOptionTenors_ << ") and number of rows (" << volRows <<
                   ") in the vol matrix");
        QL_REQUIRE(nSwapTenors_==volsColumns,
                   "mismatch between number of swap tenors (" <<
                   nSwapTenors_ << ") and number of rows (" << volsColumns <<
                   ") in the vol matrix");
    }
std::pair<Size,Size> QuantLib::SwaptionVolatilityMatrix::locate (const Date & optionDate, const Period & swapTenor) const [inline]
returns the lower indexes of surrounding volatility matrix corners
Definition at line 114 of file swaptionvolmatrix.hpp.
References QuantLib::SwaptionVolatilityStructure::swapLength(), and QuantLib::TermStructure::timeFromReference().
{
            return locate(timeFromReference(optionDate),
                          swapLength(swapTenor));
        }
std::pair<Size,Size> QuantLib::SwaptionVolatilityMatrix::locate (Time optionTime, Time swapLength) const [inline]
returns the lower indexes of surrounding volatility matrix corners
Definition at line 120 of file swaptionvolmatrix.hpp.
References interpolation_, QuantLib::Interpolation2D::locateX(), and QuantLib::Interpolation2D::locateY().
{
            return std::make_pair(interpolation_.locateY(optionTime),
                                  interpolation_.locateX(swapLength));
        }
Date QuantLib::SwaptionVolatilityMatrix::maxDate () const [inline, virtual]
the latest date for which the curve can return values
Implements QuantLib::TermStructure.
Definition at line 147 of file swaptionvolmatrix.hpp.
References QuantLib::SwaptionVolatilityDiscrete::optionDates_.
{
        return optionDates_.back();
    }
Rate QuantLib::SwaptionVolatilityMatrix::maxStrike () const [inline, virtual]
the maximum strike for which the term structure can return vols
Implements QuantLib::VolatilityTermStructure.
Definition at line 155 of file swaptionvolmatrix.hpp.
References QL_MAX_REAL.
{
        return QL_MAX_REAL;
    }
const Period & QuantLib::SwaptionVolatilityMatrix::maxSwapTenor () const [inline, virtual]
the largest length for which the term structure can return vols
Implements QuantLib::SwaptionVolatilityStructure.
Definition at line 159 of file swaptionvolmatrix.hpp.
References QuantLib::SwaptionVolatilityDiscrete::swapTenors_.
{
        return swapTenors_.back();
    }
Rate QuantLib::SwaptionVolatilityMatrix::minStrike () const [inline, virtual]
the minimum strike for which the term structure can return vols
Implements QuantLib::VolatilityTermStructure.
Definition at line 151 of file swaptionvolmatrix.hpp.
References QL_MIN_REAL.
{
        return QL_MIN_REAL;
    }
void QuantLib::SwaptionVolatilityMatrix::performCalculations () const [virtual]
This method must implement any calculations which must be (re)done in order to calculate the desired results.
Reimplemented from QuantLib::SwaptionVolatilityDiscrete.
Definition at line 174 of file swaptionvolmatrix.cpp.
References QuantLib::Matrix::columns(), QuantLib::Matrix::rows(), volatilities_, and volHandles_.
{
        SwaptionVolatilityDiscrete::performCalculations();
        // we might use iterators here...
        for (Size i=0; i<volatilities_.rows(); ++i)
            for (Size j=0; j<volatilities_.columns(); ++j)
                volatilities_[i][j] = volHandles_[i][j]->value();
    }
void QuantLib::SwaptionVolatilityMatrix::registerWithMarketData () [private]
Definition at line 167 of file swaptionvolmatrix.cpp.
References QuantLib::Observer::registerWith(), and volHandles_.
Referenced by SwaptionVolatilityMatrix().
    {
        for (Size i=0; i<volHandles_.size(); ++i)
            for (Size j=0; j<volHandles_.front().size(); ++j)
                registerWith(volHandles_[i][j]);
    }
boost::shared_ptr< SmileSection > QuantLib::SwaptionVolatilityMatrix::smileSectionImpl (Time optionTime, Time swapLength) const [protected, virtual]
Implements QuantLib::SwaptionVolatilityStructure.
Definition at line 196 of file swaptionvolmatrix.cpp.
References QuantLib::TermStructure::dayCounter(), and volatilityImpl().
{
        // dummy strike
        Volatility atmVol = volatilityImpl(optionTime, swapLength, 0.05);
        return boost::shared_ptr<SmileSection>(new
            FlatSmileSection(optionTime, atmVol, dayCounter()));
    }
Volatility QuantLib::SwaptionVolatilityMatrix::volatilityImpl (Time optionTime, Time swapLength, Rate strike) const [inline, protected, virtual]
Implements QuantLib::SwaptionVolatilityStructure.
Definition at line 163 of file swaptionvolmatrix.hpp.
References QuantLib::LazyObject::calculate(), and interpolation_.
Referenced by smileSectionImpl().
{
        calculate();
        return interpolation_(swapLength, optionTime, true);
    }
Member Data Documentation
Interpolation2D QuantLib::SwaptionVolatilityMatrix::interpolation_ [private]
Definition at line 142 of file swaptionvolmatrix.hpp.
Referenced by locate(), SwaptionVolatilityMatrix(), and volatilityImpl().
Matrix QuantLib::SwaptionVolatilityMatrix::volatilities_ [mutable, private]
Definition at line 141 of file swaptionvolmatrix.hpp.
Referenced by performCalculations(), and SwaptionVolatilityMatrix().
std::vector<std::vector<Handle<Quote> > > QuantLib::SwaptionVolatilityMatrix::volHandles_ [private]
Definition at line 140 of file swaptionvolmatrix.hpp.
Referenced by performCalculations(), registerWithMarketData(), and SwaptionVolatilityMatrix().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/swaption/swaptionvolmatrix.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/swaption/swaptionvolmatrix.cpp