QuantLib: QuantLib::CPIVolatilitySurface Class Reference
QuantLib::CPIVolatilitySurface Class Reference
zero inflation (i.e. CPI/RPI/HICP/etc.) volatility structures
#include <cpivolatilitystructure.hpp>
Public Member Functions
CPIVolatilitySurface (Natural settlementDays, const Calendar &, BusinessDayConvention bdc, const DayCounter &dc, const Period &observationLag, Frequency frequency, bool indexIsInterpolated)
Volatility
Volatility volatility (const Date &maturityDate, Rate strike, const Period &obsLag=Period(-1, Days), bool extrapolate=false) const
Returns the volatility for a given maturity date and strike rate.
Volatility volatility (const Period &optionTenor, Rate strike, const Period &obsLag=Period(-1, Days), bool extrapolate=false) const
returns the volatility for a given option tenor and strike rate
virtual Volatility totalVariance (const Date &exerciseDate, Rate strike, const Period &obsLag=Period(-1, Days), bool extrapolate=false) const
virtual Volatility totalVariance (const Period &optionTenor, Rate strike, const Period &obsLag=Period(-1, Days), bool extrapolate=false) const
Inspectors
virtual Period observationLag () const
virtual Frequency frequency () const
virtual bool indexIsInterpolated () const
virtual Date baseDate () const
virtual Time timeFromBase (const Date &date, const Period &obsLag=Period(-1, Days)) const
base date will be in the past because of observation lag
virtual Volatility baseLevel () const
Limits
virtual Real minStrike () const =0
the minimum strike for which the term structure can return vols
virtual Real maxStrike () const =0
the maximum strike for which the term structure can return vols
Protected Member Functions
virtual void checkRange (const Date &, Rate strike, bool extrapolate) const
virtual void checkRange (Time, Rate strike, bool extrapolate) const
virtual Volatility volatilityImpl (Time length, Rate strike) const =0
Protected Attributes
Volatility baseLevel_
Period observationLag_
Frequency frequency_
bool indexIsInterpolated_
Detailed Description
zero inflation (i.e. CPI/RPI/HICP/etc.) volatility structures
Abstract interface. CPI volatility is always with respect to some base date. Also deal with lagged observations of an index with a (usually different) availability lag.
Definition at line 36 of file cpivolatilitystructure.hpp.
Constructor & Destructor Documentation
QuantLib::CPIVolatilitySurface::CPIVolatilitySurface (Natural settlementDays, const Calendar & cal, BusinessDayConvention bdc, const DayCounter & dc, const Period & observationLag, Frequency frequency, bool indexIsInterpolated)
calculates the reference date based on the global evaluation date.
Definition at line 25 of file cpivolatilitystructure.cpp.
    : VolatilityTermStructure(settlementDays, cal, bdc, dc),
      baseLevel_(Null<Volatility>()), observationLag_(observationLag),
      frequency_(frequency), indexIsInterpolated_(indexIsInterpolated)
    {}
Member Function Documentation
Date QuantLib::CPIVolatilitySurface::baseDate () const [virtual]
Definition at line 38 of file cpivolatilitystructure.cpp.
References frequency(), indexIsInterpolated(), QuantLib::inflationPeriod(), observationLag(), and QuantLib::TermStructure::referenceDate().
Referenced by checkRange(), and timeFromBase().
{
        // Depends on interpolation, or not, of observed index
        // and observation lag with which it was built.
        // We want this to work even if the index does not
        // have a term structure.
        if (indexIsInterpolated()) {
            return referenceDate() - observationLag();
        } else {
            return inflationPeriod(referenceDate() - observationLag(),
                                   frequency()).first;
        }
    }
virtual Volatility QuantLib::CPIVolatilitySurface::baseLevel () const [inline, virtual]
Definition at line 107 of file cpivolatilitystructure.hpp.
References baseLevel_, and QL_REQUIRE.
{
            QL_REQUIRE(baseLevel_ != Null<Volatility>(),
                       "Base volatility, for baseDate(), not set.");
            return baseLevel_;
        }
void QuantLib::CPIVolatilitySurface::checkRange (const Date & d, Rate strike, bool extrapolate) const [protected, virtual]
Definition at line 52 of file cpivolatilitystructure.cpp.
References QuantLib::Extrapolator::allowsExtrapolation(), baseDate(), QuantLib::TermStructure::maxDate(), maxStrike(), minStrike(), and QL_REQUIRE.
Referenced by volatility().
{
        QL_REQUIRE(d >= baseDate(),
                   "date (" << d << ") is before base date");
        QL_REQUIRE(extrapolate || allowsExtrapolation() || d <= maxDate(),
                   "date (" << d << ") is past max curve date ("
                   << maxDate() << ")");
        QL_REQUIRE(extrapolate || allowsExtrapolation() ||
                   (strike >= minStrike() && strike <= maxStrike()),
                   "strike (" << strike << ") is outside the curve domain ["
                   << minStrike() << "," << maxStrike()<< "]] at date = " << d);
    }
void QuantLib::CPIVolatilitySurface::checkRange (Time t, Rate strike, bool extrapolate) const [protected, virtual]
Definition at line 66 of file cpivolatilitystructure.cpp.
References QuantLib::Extrapolator::allowsExtrapolation(), baseDate(), maxStrike(), QuantLib::TermStructure::maxTime(), minStrike(), QL_REQUIRE, and QuantLib::TermStructure::timeFromReference().
{
        QL_REQUIRE(t >= timeFromReference(baseDate()),
                   "time (" << t << ") is before base date");
        QL_REQUIRE(extrapolate || allowsExtrapolation() || t <= maxTime(),
                   "time (" << t << ") is past max curve time ("
                   << maxTime() << ")");
        QL_REQUIRE(extrapolate || allowsExtrapolation() ||
                   (strike >= minStrike() && strike <= maxStrike()),
                   "strike (" << strike << ") is outside the curve domain ["
                   << minStrike() << "," << maxStrike()<< "] at time = " << t);
    }
virtual Frequency QuantLib::CPIVolatilitySurface::frequency () const [inline, virtual]
Definition at line 98 of file cpivolatilitystructure.hpp.
References frequency_.
Referenced by baseDate(), timeFromBase(), and volatility().
{ return frequency_; }
virtual bool QuantLib::CPIVolatilitySurface::indexIsInterpolated () const [inline, virtual]
Definition at line 99 of file cpivolatilitystructure.hpp.
References indexIsInterpolated_.
Referenced by baseDate(), timeFromBase(), and volatility().
{
            return indexIsInterpolated_;
        }
virtual Real QuantLib::CPIVolatilitySurface::maxStrike () const [pure virtual]
the maximum strike for which the term structure can return vols
Implements QuantLib::VolatilityTermStructure.
Implemented in QuantLib::ConstantCPIVolatility.
Referenced by checkRange().
virtual Real QuantLib::CPIVolatilitySurface::minStrike () const [pure virtual]
the minimum strike for which the term structure can return vols
Implements QuantLib::VolatilityTermStructure.
Implemented in QuantLib::ConstantCPIVolatility.
Referenced by checkRange().
virtual Period QuantLib::CPIVolatilitySurface::observationLag () const [inline, virtual]
The term structure observes with a lag that is usually different from the availability lag of the index. An inflation rate is given, by default, for the maturity requested assuming this lag.
Definition at line 97 of file cpivolatilitystructure.hpp.
References observationLag_.
Referenced by baseDate(), timeFromBase(), and volatility().
{ return observationLag_; }
Time QuantLib::CPIVolatilitySurface::timeFromBase (const Date & date, const Period & obsLag = Period(-1,Days)) const [virtual]
base date will be in the past because of observation lag
needed for total variance calculations
Definition at line 114 of file cpivolatilitystructure.cpp.
References baseDate(), QuantLib::TermStructure::dayCounter(), QuantLib::Days, frequency(), indexIsInterpolated(), QuantLib::inflationPeriod(), observationLag(), and QuantLib::DayCounter::yearFraction().
Referenced by totalVariance().
{
        Period useLag = obsLag;
        if (obsLag==Period(-1,Days)) {
            useLag = observationLag();
        }
        Date useDate;
        if (indexIsInterpolated()) {
            useDate = maturityDate - useLag;
        } else {
            useDate = inflationPeriod(maturityDate - useLag,
                                      frequency()).first;
        }
        // This assumes that the inflation term structure starts
        // as late as possible given the inflation index definition,
        // which is the usual case.
        return dayCounter().yearFraction(baseDate(), useDate);
    }
Volatility QuantLib::CPIVolatilitySurface::totalVariance (const Date & exerciseDate, Rate strike, const Period & obsLag = Period(-1,Days), bool extrapolate = false) const [virtual]
Returns the total integrated variance for a given exercise date and strike rate.
Total integrated variance is useful because it scales out t for the optionlet pricing formulae. Note that it is called "total" because the surface does not know whether it represents Black, Bachelier or Displaced Diffusion variance. These are virtual so alternate connections between const vol and total var are possible.
Definition at line 136 of file cpivolatilitystructure.cpp.
References anonymous_namespace{quantlibbenchmark.cpp}::t, timeFromBase(), and volatility().
Referenced by totalVariance().
{
        Volatility vol = volatility(maturityDate, strike, obsLag, extrapolate);
        Time t = timeFromBase(maturityDate, obsLag);
        return vol*vol*t;
    }
Volatility QuantLib::CPIVolatilitySurface::totalVariance (const Period & optionTenor, Rate strike, const Period & obsLag = Period(-1,Days), bool extrapolate = false) const [virtual]
returns the total integrated variance for a given option tenor and strike rate.
Definition at line 146 of file cpivolatilitystructure.cpp.
References QuantLib::VolatilityTermStructure::optionDateFromTenor(), and totalVariance().
{
        Date maturityDate = optionDateFromTenor(tenor);
        return totalVariance(maturityDate, strike, obsLag, extrap);
    }
Volatility QuantLib::CPIVolatilitySurface::volatility (const Date & maturityDate, Rate strike, const Period & obsLag = Period(-1,Days), bool extrapolate = false) const
Returns the volatility for a given maturity date and strike rate.
by default, inflation is observed with the lag of the term structure.
Because inflation is highly linked to dates (for interpolation, periods, etc) time-based overload of the methods are not provided.
Definition at line 80 of file cpivolatilitystructure.cpp.
References checkRange(), QuantLib::Days, frequency(), indexIsInterpolated(), QuantLib::inflationPeriod(), observationLag(), anonymous_namespace{quantlibbenchmark.cpp}::t, QuantLib::TermStructure::timeFromReference(), and volatilityImpl().
Referenced by totalVariance(), and volatility().
{
        Period useLag = obsLag;
        if (obsLag==Period(-1,Days)) {
            useLag = observationLag();
        }
        if (indexIsInterpolated()) {
            checkRange(maturityDate-useLag, strike, extrapolate);
            Time t = timeFromReference(maturityDate-useLag);
            return volatilityImpl(t,strike);
        } else {
            std::pair<Date,Date> dd =
                inflationPeriod(maturityDate-useLag, frequency());
            checkRange(dd.first, strike, extrapolate);
            Time t = timeFromReference(dd.first);
            return volatilityImpl(t,strike);
        }
    }
Volatility QuantLib::CPIVolatilitySurface::volatility (const Period & optionTenor, Rate strike, const Period & obsLag = Period(-1,Days), bool extrapolate = false) const
returns the volatility for a given option tenor and strike rate
Definition at line 104 of file cpivolatilitystructure.cpp.
References QuantLib::VolatilityTermStructure::optionDateFromTenor(), and volatility().
{
        Date maturityDate = optionDateFromTenor(optionTenor);
        return volatility(maturityDate, strike, obsLag, extrapolate);
    }
virtual Volatility QuantLib::CPIVolatilitySurface::volatilityImpl (Time length, Rate strike) const [protected, pure virtual]
Implements the actual volatility surface calculation in derived classes e.g. bilinear interpolation. N.B. does not derive the surface.
Implemented in QuantLib::ConstantCPIVolatility.
Referenced by volatility().
Member Data Documentation
Volatility QuantLib::CPIVolatilitySurface::baseLevel_ [mutable, protected]
Definition at line 132 of file cpivolatilitystructure.hpp.
Referenced by baseLevel().
Frequency QuantLib::CPIVolatilitySurface::frequency_ [protected]
Definition at line 135 of file cpivolatilitystructure.hpp.
Referenced by frequency().
bool QuantLib::CPIVolatilitySurface::indexIsInterpolated_ [protected]
Definition at line 136 of file cpivolatilitystructure.hpp.
Referenced by indexIsInterpolated().
Period QuantLib::CPIVolatilitySurface::observationLag_ [protected]
Definition at line 134 of file cpivolatilitystructure.hpp.
Referenced by observationLag().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/inflation/cpivolatilitystructure.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/inflation/cpivolatilitystructure.cpp