QuantLib: QuantLib::FlatExtrapolator2D::FlatExtrapolator2DImpl Class Reference
QuantLib::FlatExtrapolator2D::FlatExtrapolator2DImpl Class Reference
#include <flatextrapolation2d.hpp>
Public Member Functions
FlatExtrapolator2DImpl (boost::shared_ptr< Interpolation2D > decoratedInterpolation)
Real xMin () const
Real xMax () const
std::vector< Real > xValues () const
Size locateX (Real x) const
Real yMin () const
Real yMax () const
std::vector< Real > yValues () const
Size locateY (Real y) const
const Matrix & zData () const
bool isInRange (Real x, Real y) const
void update ()
void calculate ()
Real value (Real x, Real y) const
Private Member Functions
Real bindX (Real x) const
Real bindY (Real y) const
Private Attributes
boost::shared_ptr
< Interpolation2D > decoratedInterp_
Detailed Description
Definition at line 39 of file flatextrapolation2d.hpp.
Constructor & Destructor Documentation
QuantLib::FlatExtrapolator2D::FlatExtrapolator2DImpl::FlatExtrapolator2DImpl (boost::shared_ptr< Interpolation2D > decoratedInterpolation) [inline]
Definition at line 41 of file flatextrapolation2d.hpp.
References calculate().
            :decoratedInterp_(decoratedInterpolation){
                calculate();
            }
Member Function Documentation
Real QuantLib::FlatExtrapolator2D::FlatExtrapolator2DImpl::bindX (Real x) const [inline, private]
Definition at line 88 of file flatextrapolation2d.hpp.
References xMax(), and xMin().
Referenced by value().
{
                if(x < xMin())
                    return xMin();
                if (x > xMax())
                    return xMax();
                return x;
            }
Real QuantLib::FlatExtrapolator2D::FlatExtrapolator2DImpl::bindY (Real y) const [inline, private]
Definition at line 95 of file flatextrapolation2d.hpp.
References yMax(), and yMin().
Referenced by value().
{
                if(y < yMin())
                    return yMin();
                if (y > yMax())
                    return yMax();
                return y;
            }
void QuantLib::FlatExtrapolator2D::FlatExtrapolator2DImpl::calculate () [inline, virtual]
Implements QuantLib::Interpolation2D::Impl.
Definition at line 78 of file flatextrapolation2d.hpp.
Referenced by FlatExtrapolator2DImpl().
{}
bool QuantLib::FlatExtrapolator2D::FlatExtrapolator2DImpl::isInRange (Real x, Real y) const [inline, virtual]
Implements QuantLib::Interpolation2D::Impl.
Definition at line 72 of file flatextrapolation2d.hpp.
References decoratedInterp_.
{
                return decoratedInterp_->isInRange(x,y);
            }
Size QuantLib::FlatExtrapolator2D::FlatExtrapolator2DImpl::locateX (Real x) const [inline, virtual]
Implements QuantLib::Interpolation2D::Impl.
Definition at line 54 of file flatextrapolation2d.hpp.
References decoratedInterp_.
{
                return decoratedInterp_->locateX(x);
            }
Size QuantLib::FlatExtrapolator2D::FlatExtrapolator2DImpl::locateY (Real y) const [inline, virtual]
Implements QuantLib::Interpolation2D::Impl.
Definition at line 66 of file flatextrapolation2d.hpp.
References decoratedInterp_.
{
                return decoratedInterp_->locateY(y);
            }
void QuantLib::FlatExtrapolator2D::FlatExtrapolator2DImpl::update () [inline]
Definition at line 75 of file flatextrapolation2d.hpp.
References decoratedInterp_.
{
                decoratedInterp_->update();
            }
Real QuantLib::FlatExtrapolator2D::FlatExtrapolator2DImpl::value (Real x, Real y) const [inline, virtual]
Implements QuantLib::Interpolation2D::Impl.
Definition at line 79 of file flatextrapolation2d.hpp.
References bindX(), bindY(), and decoratedInterp_.
{
                x = bindX(x);
                y = bindY(y);
                return decoratedInterp_->operator()(x,y);
            }
Real QuantLib::FlatExtrapolator2D::FlatExtrapolator2DImpl::xMax () const [inline, virtual]
Implements QuantLib::Interpolation2D::Impl.
Definition at line 48 of file flatextrapolation2d.hpp.
References decoratedInterp_.
Referenced by bindX().
{
                return decoratedInterp_->xMax();
            }
Real QuantLib::FlatExtrapolator2D::FlatExtrapolator2DImpl::xMin () const [inline, virtual]
Implements QuantLib::Interpolation2D::Impl.
Definition at line 45 of file flatextrapolation2d.hpp.
References decoratedInterp_.
Referenced by bindX().
{
                return decoratedInterp_->xMin();
            }
std::vector<Real> QuantLib::FlatExtrapolator2D::FlatExtrapolator2DImpl::xValues () const [inline, virtual]
Implements QuantLib::Interpolation2D::Impl.
Definition at line 51 of file flatextrapolation2d.hpp.
References decoratedInterp_.
{
                return decoratedInterp_->xValues();
            }
Real QuantLib::FlatExtrapolator2D::FlatExtrapolator2DImpl::yMax () const [inline, virtual]
Implements QuantLib::Interpolation2D::Impl.
Definition at line 60 of file flatextrapolation2d.hpp.
References decoratedInterp_.
Referenced by bindY().
{
                return decoratedInterp_->yMax();
            }
Real QuantLib::FlatExtrapolator2D::FlatExtrapolator2DImpl::yMin () const [inline, virtual]
Implements QuantLib::Interpolation2D::Impl.
Definition at line 57 of file flatextrapolation2d.hpp.
References decoratedInterp_.
Referenced by bindY().
{
                return decoratedInterp_->yMin();
            }
std::vector<Real> QuantLib::FlatExtrapolator2D::FlatExtrapolator2DImpl::yValues () const [inline, virtual]
Implements QuantLib::Interpolation2D::Impl.
Definition at line 63 of file flatextrapolation2d.hpp.
References decoratedInterp_.
{
                return decoratedInterp_->yValues();
            }
const Matrix& QuantLib::FlatExtrapolator2D::FlatExtrapolator2DImpl::zData () const [inline, virtual]
Implements QuantLib::Interpolation2D::Impl.
Definition at line 69 of file flatextrapolation2d.hpp.
References decoratedInterp_.
{
                return decoratedInterp_->zData();
            }
Member Data Documentation
boost::shared_ptr<Interpolation2D> QuantLib::FlatExtrapolator2D::FlatExtrapolator2DImpl::decoratedInterp_ [private]
Definition at line 86 of file flatextrapolation2d.hpp.
Referenced by isInRange(), locateX(), locateY(), update(), value(), xMax(), xMin(), xValues(), yMax(), yMin(), yValues(), and zData().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/interpolations/flatextrapolation2d.hpp