QuantLib: QuantLib::Singapore::SgxImpl Class Reference
QuantLib::Singapore::SgxImpl Class Reference
Public Member Functions
std::string name () const
bool isBusinessDay (const Date &) const
Detailed Description
Definition at line 60 of file singapore.hpp.
Member Function Documentation
bool QuantLib::Singapore::SgxImpl::isBusinessDay (const Date & date) const [virtual]
Implements QuantLib::Calendar::Impl.
Definition at line 31 of file singapore.cpp.
References QuantLib::August, anonymous_namespace{marketmodel.cpp}::d, QuantLib::Date::dayOfMonth(), QuantLib::Date::dayOfYear(), QuantLib::December, QuantLib::Calendar::WesternImpl::easterMonday(), QuantLib::February, QuantLib::Calendar::WesternImpl::isWeekend(), QuantLib::January, QuantLib::June, QuantLib::May, QuantLib::Date::month(), QuantLib::November, QuantLib::October, QuantLib::September, QuantLib::Date::weekday(), and QuantLib::Date::year().
{
        Weekday w = date.weekday();
        Day d = date.dayOfMonth(), dd = date.dayOfYear();
        Month m = date.month();
        Year y = date.year();
        Day em = easterMonday(y);
        if (isWeekend(w)
            // New Year's Day
            || (d == 1 && m == January)
            // Good Friday
            || (dd == em-3)
            // Labor Day
            || (d == 1 && m == May)
            // National Day
            || (d == 9 && m == August)
            || (d == 10 && m == August && y == 2009)
            // Christmas Day
            || (d == 25 && m == December)
            // Chinese New Year
            || ((d == 22 || d == 23) && m == January && y == 2004)
            || ((d == 9 || d == 10) && m == February && y == 2005)
            || ((d == 30 || d == 31) && m == January && y == 2006)
            || ((d == 19 || d == 20) && m == February && y == 2007)
            || ((d == 7 || d == 8) && m == February && y == 2008)
            || ((d == 26 || d == 27) && m == January && y == 2009)
            || ((d == 15 || d == 16) && m == January && y == 2010)
            // Hari Raya Haji
            || ((d == 1 || d == 2) && m == February && y == 2004)
            || (d == 21 && m == January && y == 2005)
            || (d == 10 && m == January && y == 2006)
            || (d == 2 && m == January && y == 2007)
            || (d == 20 && m == December && y == 2007)
            || (d == 8 && m == December && y == 2008)
            || (d == 27 && m == November && y == 2009)
            || (d == 17 && m == November && y == 2010)
            // Vesak Poya Day
            || (d == 2 && m == June && y == 2004)
            || (d == 22 && m == May && y == 2005)
            || (d == 12 && m == May && y == 2006)
            || (d == 31 && m == May && y == 2007)
            || (d == 18 && m == May && y == 2008)
            || (d == 9 && m == May && y == 2009)
            || (d == 28 && m == May && y == 2010)
            // Deepavali
            || (d == 11 && m == November && y == 2004)
            || (d == 8 && m == November && y == 2007)
            || (d == 28 && m == October && y == 2008)
            || (d == 16 && m == November && y == 2009)
            || (d == 5 && m == November && y == 2010)
            // Diwali
            || (d == 1 && m == November && y == 2005)
            // Hari Raya Puasa
            || ((d == 14 || d == 15) && m == November && y == 2004)
            || (d == 3 && m == November && y == 2005)
            || (d == 24 && m == October && y == 2006)
            || (d == 13 && m == October && y == 2007)
            || (d == 1 && m == October && y == 2008)
            || (d == 21 && m == September && y == 2009)
            || (d == 10 && m == September && y == 2010)
            )
            return false;
        return true;
    }
std::string QuantLib::Singapore::SgxImpl::name () const [inline, virtual]
Implements QuantLib::Calendar::Impl.
Definition at line 62 of file singapore.hpp.
{ return "Singapore exchange"; }
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/time/calendars/singapore.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/time/calendars/singapore.cpp