QuantLib: CPISwapTest Class Reference
CPISwapTest Class Reference
Classic inflation index ratio-from-base products. Always have some "notional" flow.
#include <inflationcpiswap.hpp>
Static Public Member Functions
static void consistency ()
consistency test w.r.t. manual build-up of calculatons
static void zciisconsistency ()
a CPI swap can look like a Zero Coupon Inflation Inedex Swap, check it gies same prices
static void cpibondconsistency ()
one leg of a CPI swap looks like a CPI bond with growthOnly=true
static
boost::unit_test_framework::test_suite * suite ()
Detailed Description
Classic inflation index ratio-from-base products. Always have some "notional" flow.
Definition at line 26 of file inflationcpiswap.hpp.
Member Function Documentation
void CPISwapTest::consistency () [static]
consistency test w.r.t. manual build-up of calculatons
Definition at line 266 of file inflationcpiswap.cpp.
References QuantLib::MakeSchedule::backwards(), QuantLib::CPISwap::cpiLeg(), anonymous_namespace{marketmodel.cpp}::endDate, QuantLib::Settings::evaluationDate(), QuantLib::MakeSchedule::from(), QuantLib::Singleton< Settings >::instance(), QuantLib::Swap::leg(), QuantLib::Swap::legNPV(), QuantLib::ModifiedFollowing, QuantLib::Months, QuantLib::Instrument::NPV(), QuantLib::October, QuantLib::CPISwap::Payer, QL_REQUIRE, QuantLib::Instrument::setPricingEngine(), QuantLib::Schedule::size(), anonymous_namespace{marketmodel.cpp}::startDate, QuantLib::MakeSchedule::to(), QuantLib::Unadjusted, QuantLib::MakeSchedule::withCalendar(), QuantLib::MakeSchedule::withConvention(), and QuantLib::MakeSchedule::withTenor().
Referenced by suite().
{
    // check inflation leg vs calculation directly from inflation TS
    CommonVars common;
    // ZeroInflationSwap aka CPISwap
    CPISwap::Type type = CPISwap::Payer;
    Real nominal = 1000000.0;
    bool subtractInflationNominal = true;
    // float+spread leg
    Spread spread = 0.0;
    DayCounter floatDayCount = Actual365Fixed();
    BusinessDayConvention floatPaymentConvention = ModifiedFollowing;
    Natural fixingDays = 0;
    boost::shared_ptr<IborIndex> floatIndex(new GBPLibor(Period(6,Months),
                                                         common.nominalTS));
    // fixed x inflation leg
    Rate fixedRate = 0.1;//1% would be 0.01
    Real baseCPI = 206.1; // would be 206.13871 if we were interpolating
    DayCounter fixedDayCount = Actual365Fixed();
    BusinessDayConvention fixedPaymentConvention = ModifiedFollowing;
    Calendar fixedPaymentCalendar = UnitedKingdom();
    boost::shared_ptr<ZeroInflationIndex> fixedIndex = common.ii;
    Period contractObservationLag = common.contractObservationLag;
    CPI::InterpolationType observationInterpolation = common.contractObservationInterpolation;
    // set the schedules
    Date startDate(2, October, 2007);
    Date endDate(2, October, 2052);
    Schedule floatSchedule = MakeSchedule().from(startDate).to(endDate)
    .withTenor(Period(6,Months))
    .withCalendar(UnitedKingdom())
    .withConvention(floatPaymentConvention)
    .backwards()
    ;
    Schedule fixedSchedule = MakeSchedule().from(startDate).to(endDate)
    .withTenor(Period(6,Months))
    .withCalendar(UnitedKingdom())
    .withConvention(Unadjusted)
    .backwards()
    ;
    CPISwap zisV(type, nominal, subtractInflationNominal,
                 spread, floatDayCount, floatSchedule,
                 floatPaymentConvention, fixingDays, floatIndex,
                 fixedRate, baseCPI, fixedDayCount, fixedSchedule,
                 fixedPaymentConvention, contractObservationLag,
                 fixedIndex, observationInterpolation);
    Date asofDate = Settings::instance().evaluationDate();
    Real floatFix[] = {0.06255,0.05975,0.0637,0.018425,0.0073438,-1,-1};
    Real cpiFix[] = {211.4,217.2,211.4,213.4,-2,-2};
    for(Size i=0;i<floatSchedule.size(); i++){
        if (floatSchedule[i] < common.evaluationDate) {
            floatIndex->addFixing(floatSchedule[i], floatFix[i],true);//true=overwrite
        }
        boost::shared_ptr<CPICoupon>
        zic = boost::dynamic_pointer_cast<CPICoupon>(zisV.cpiLeg()[i]);
        if (zic) {
            if (zic->fixingDate() < (common.evaluationDate - Period(1,Months))) {
                fixedIndex->addFixing(zic->fixingDate(), cpiFix[i],true);
            }
        }
    }
    // simple structure so simple pricing engine - most work done by index
    boost::shared_ptr<DiscountingSwapEngine>
        dse(new DiscountingSwapEngine(common.nominalTS));
    zisV.setPricingEngine(dse);
    // get float+spread & fixed*inflation leg prices separately
    Real testInfLegNPV = 0.0;
    for(Size i=0;i<zisV.leg(0).size(); i++){
        Date zicPayDate = (zisV.leg(0))[i]->date();
        if(zicPayDate > asofDate) {
            testInfLegNPV += (zisV.leg(0))[i]->amount()*common.nominalTS->discount(zicPayDate);
        }
        boost::shared_ptr<CPICoupon>
            zicV = boost::dynamic_pointer_cast<CPICoupon>(zisV.cpiLeg()[i]);
        if (zicV) {
            Real diff = fabs( zicV->rate() - (fixedRate*(zicV->indexFixing()/baseCPI)) );
            QL_REQUIRE(diff<1e-8,"failed "<<i<<"th coupon reconstruction as "
                       << (fixedRate*(zicV->indexFixing()/baseCPI)) << " vs rate = "
                       <<zicV->rate() << ", with difference: " << diff);
        }
    }
    Real error = fabs(testInfLegNPV - zisV.legNPV(0));
    QL_REQUIRE(error<1e-5,
               "failed manual inf leg NPV calc vs pricing engine: " <<
               testInfLegNPV << " vs " << zisV.legNPV(0));
    Real diff = fabs(1-zisV.NPV()/4191660.0);
    QL_REQUIRE(diff<1e-5,
               "failed stored consistency value test, ratio = " << diff);
    // remove circular refernce
    common.hcpi.linkTo(boost::shared_ptr<ZeroInflationTermStructure>());
}
void CPISwapTest::cpibondconsistency () [static]
one leg of a CPI swap looks like a CPI bond with growthOnly=true
Definition at line 430 of file inflationcpiswap.cpp.
References QuantLib::MakeSchedule::backwards(), QuantLib::CPISwap::cpiLeg(), anonymous_namespace{marketmodel.cpp}::endDate, QuantLib::MakeSchedule::from(), QuantLib::Swap::legNPV(), QuantLib::ModifiedFollowing, QuantLib::Months, QuantLib::Instrument::NPV(), QuantLib::October, QuantLib::CPISwap::Payer, QL_REQUIRE, QuantLib::Instrument::setPricingEngine(), QuantLib::Schedule::size(), anonymous_namespace{marketmodel.cpp}::startDate, QuantLib::MakeSchedule::to(), QuantLib::Unadjusted, QuantLib::MakeSchedule::withCalendar(), QuantLib::MakeSchedule::withConvention(), and QuantLib::MakeSchedule::withTenor().
Referenced by suite().
{
    CommonVars common;
    // ZeroInflationSwap aka CPISwap
    CPISwap::Type type = CPISwap::Payer;
    Real nominal = 1000000.0;
    bool subtractInflationNominal = true;
    // float+spread leg
    Spread spread = 0.0;
    DayCounter floatDayCount = Actual365Fixed();
    BusinessDayConvention floatPaymentConvention = ModifiedFollowing;
    Natural fixingDays = 0;
    boost::shared_ptr<IborIndex> floatIndex(new GBPLibor(Period(6,Months),
                                                         common.nominalTS));
    // fixed x inflation leg
    Rate fixedRate = 0.1;//1% would be 0.01
    Real baseCPI = 206.1; // would be 206.13871 if we were interpolating
    DayCounter fixedDayCount = Actual365Fixed();
    BusinessDayConvention fixedPaymentConvention = ModifiedFollowing;
    Calendar fixedPaymentCalendar = UnitedKingdom();
    boost::shared_ptr<ZeroInflationIndex> fixedIndex = common.ii;
    Period contractObservationLag = common.contractObservationLag;
    CPI::InterpolationType observationInterpolation = common.contractObservationInterpolation;
    // set the schedules
    Date startDate(2, October, 2007);
    Date endDate(2, October, 2052);
    Schedule floatSchedule = MakeSchedule().from(startDate).to(endDate)
    .withTenor(Period(6,Months))
    .withCalendar(UnitedKingdom())
    .withConvention(floatPaymentConvention)
    .backwards()
    ;
    Schedule fixedSchedule = MakeSchedule().from(startDate).to(endDate)
    .withTenor(Period(6,Months))
    .withCalendar(UnitedKingdom())
    .withConvention(Unadjusted)
    .backwards()
    ;
    CPISwap zisV(type, nominal, subtractInflationNominal,
                 spread, floatDayCount, floatSchedule,
                 floatPaymentConvention, fixingDays, floatIndex,
                 fixedRate, baseCPI, fixedDayCount, fixedSchedule,
                 fixedPaymentConvention, contractObservationLag,
                 fixedIndex, observationInterpolation);
    Real floatFix[] = {0.06255,0.05975,0.0637,0.018425,0.0073438,-1,-1};
    Real cpiFix[] = {211.4,217.2,211.4,213.4,-2,-2};
    for(Size i=0;i<floatSchedule.size(); i++){
        if (floatSchedule[i] < common.evaluationDate) {
            floatIndex->addFixing(floatSchedule[i], floatFix[i],true);//true=overwrite
        }
        boost::shared_ptr<CPICoupon>
        zic = boost::dynamic_pointer_cast<CPICoupon>(zisV.cpiLeg()[i]);
        if (zic) {
            if (zic->fixingDate() < (common.evaluationDate - Period(1,Months))) {
                fixedIndex->addFixing(zic->fixingDate(), cpiFix[i],true);
            }
        }
    }
    // simple structure so simple pricing engine - most work done by index
    boost::shared_ptr<DiscountingSwapEngine>
    dse(new DiscountingSwapEngine(common.nominalTS));
    zisV.setPricingEngine(dse);
    // now do the bond equivalent
    std::vector<Rate> fixedRates(1,fixedRate);
    Natural settlementDays = 1;// cannot be zero!
    bool growthOnly = true;
    CPIBond cpiB(settlementDays, nominal, growthOnly,
                 baseCPI, contractObservationLag, fixedIndex,
                 observationInterpolation, fixedSchedule,
                 fixedRates, fixedDayCount, fixedPaymentConvention);
    boost::shared_ptr<DiscountingBondEngine>
    dbe(new DiscountingBondEngine(common.nominalTS));
    cpiB.setPricingEngine(dbe);
    QL_REQUIRE(fabs(cpiB.NPV() - zisV.legNPV(0))<1e-5,"cpi bond does not equal equivalent cpi swap leg");
    // remove circular refernce
    common.hcpi.linkTo(boost::shared_ptr<ZeroInflationTermStructure>());
}
test_suite * CPISwapTest::suite () [static]
Definition at line 522 of file inflationcpiswap.cpp.
References consistency(), cpibondconsistency(), QUANTLIB_TEST_CASE, and zciisconsistency().
Referenced by init_unit_test_suite().
{
    test_suite* suite = BOOST_TEST_SUITE("CPISwap tests");
    suite->add(QUANTLIB_TEST_CASE(&CPISwapTest::consistency));
    suite->add(QUANTLIB_TEST_CASE(&CPISwapTest::zciisconsistency));
    suite->add(QUANTLIB_TEST_CASE(&CPISwapTest::cpibondconsistency));
    return suite;
}
void CPISwapTest::zciisconsistency () [static]
a CPI swap can look like a Zero Coupon Inflation Inedex Swap, check it gies same prices
Definition at line 375 of file inflationcpiswap.cpp.
References QuantLib::CPI::AsIndex, anonymous_namespace{marketmodel.cpp}::endDate, QuantLib::Swap::legNPV(), QuantLib::ModifiedFollowing, QuantLib::Months, QuantLib::November, QuantLib::Instrument::NPV(), QuantLib::CPISwap::Payer, QuantLib::ZeroCouponInflationSwap::Payer, QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow(), QL_REQUIRE, QuantLib::Instrument::setPricingEngine(), and anonymous_namespace{marketmodel.cpp}::startDate.
Referenced by suite().
{
    CommonVars common;
    ZeroCouponInflationSwap::Type ztype = ZeroCouponInflationSwap::Payer;
    Real  nominal = 1000000.0;
    Date startDate(common.evaluationDate);
    Date endDate(25, November, 2059);
    Calendar cal = UnitedKingdom();
    BusinessDayConvention paymentConvention = ModifiedFollowing;
    DayCounter dummyDC, dc = ActualActual();
    Period observationLag(2,Months);
    Rate quote = 0.03714;
    ZeroCouponInflationSwap zciis(ztype, nominal, startDate, endDate, cal,
                                  paymentConvention, dc, quote, common.ii,
                                  observationLag);
    // simple structure so simple pricing engine - most work done by index
    boost::shared_ptr<DiscountingSwapEngine>
    dse(new DiscountingSwapEngine(common.nominalTS));
    zciis.setPricingEngine(dse);
    QL_REQUIRE(fabs(zciis.NPV())<1e-3,"zciis does not reprice to zero");
    std::vector<Date> oneDate;
    oneDate.push_back(endDate);
    Schedule schOneDate(oneDate, cal, paymentConvention);
    CPISwap::Type stype = CPISwap::Payer;
    Real inflationNominal = nominal;
    Real floatNominal = inflationNominal * std::pow(1.0+quote,50);
    bool subtractInflationNominal = true;
    Real dummySpread=0.0, dummyFixedRate=0.0;
    Natural fixingDays = 0;
    Date baseDate = startDate - observationLag;
    Real baseCPI = common.ii->fixing(baseDate);
    boost::shared_ptr<IborIndex> dummyFloatIndex;
    CPISwap cS(stype, floatNominal, subtractInflationNominal, dummySpread, dummyDC, schOneDate,
               paymentConvention, fixingDays, dummyFloatIndex,
               dummyFixedRate, baseCPI, dummyDC, schOneDate, paymentConvention, observationLag,
               common.ii, CPI::AsIndex, inflationNominal);
    cS.setPricingEngine(dse);
    QL_REQUIRE(fabs(cS.NPV())<1e-3,"CPISwap as ZCIIS does not reprice to zero");
    for (Size i=0; i<2; i++) {
        QL_REQUIRE(fabs(cS.legNPV(i)-zciis.legNPV(i))<1e-3,"zciis leg does not equal CPISwap leg");
    }
    // remove circular refernce
    common.hcpi.linkTo(boost::shared_ptr<ZeroInflationTermStructure>());
}
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/inflationcpiswap.hpp
/home/deriversatile/QuantLib/QuantLibQt/test-suite/inflationcpiswap.cpp