QuantLib: QuantLib::Date Class Reference
QuantLib::Date Class Reference
Concrete date class.
#include <date.hpp>
Public Member Functions
constructors
Date ()
Default constructor returning a null date.
Date (BigInteger serialNumber)
Constructor taking a serial number as given by Applix or Excel.
Date (Day d, Month m, Year y)
More traditional constructor.
inspectors
Weekday weekday () const
Day dayOfMonth () const
Day dayOfYear () const
One-based (Jan 1st = 1)
Month month () const
Year year () const
BigInteger serialNumber () const
date algebra
Date & operator+= (BigInteger days)
increments date by the given number of days
Date & operator+= (const Period &)
increments date by the given period
Date & operator-= (BigInteger days)
decrement date by the given number of days
Date & operator-= (const Period &)
decrements date by the given period
Date & operator++ ()
1-day pre-increment
Date operator++ (int)
1-day post-increment
Date & operator-- ()
1-day pre-decrement
Date operator-- (int)
1-day post-decrement
Date operator+ (BigInteger days) const
returns a new date incremented by the given number of days
Date operator+ (const Period &) const
returns a new date incremented by the given period
Date operator- (BigInteger days) const
returns a new date decremented by the given number of days
Date operator- (const Period &) const
returns a new date decremented by the given period
Static Public Member Functions
static methods
static Date todaysDate ()
today's date.
static Date minDate ()
earliest allowed date
static Date maxDate ()
latest allowed date
static bool isLeap (Year y)
whether the given year is a leap one
static Date endOfMonth (const Date &d)
last day of the month to which the given date belongs
static bool isEndOfMonth (const Date &d)
whether a date is the last day of its month
static Date nextWeekday (const Date &d, Weekday w)
next given weekday following or equal to the given date
static Date nthWeekday (Size n, Weekday w, Month m, Year y)
n-th given weekday in the given month and year
Static Private Member Functions
static Date advance (const Date &d, Integer units, TimeUnit)
static Integer monthLength (Month m, bool leapYear)
static Integer monthOffset (Month m, bool leapYear)
static BigInteger yearOffset (Year y)
static BigInteger minimumSerialNumber ()
static BigInteger maximumSerialNumber ()
static void checkSerialNumber (BigInteger serialNumber)
Private Attributes
BigInteger serialNumber_
Related Functions
(Note that these are not member functions.)
BigInteger operator- (const Date &, const Date &)
Difference in days between dates.
bool operator== (const Date &, const Date &)
bool operator!= (const Date &, const Date &)
bool operator< (const Date &, const Date &)
bool operator<= (const Date &, const Date &)
bool operator> (const Date &, const Date &)
bool operator>= (const Date &, const Date &)
std::ostream & operator<< (std::ostream &, const Date &)
Detailed Description
Concrete date class.
This class provides methods to inspect dates as well as methods and operators which implement a limited date algebra (increasing and decreasing dates, and calculating their difference).
Test:
self-consistency of dates, serial numbers, days of month, months, and weekdays is checked over the whole date range.
Definition at line 89 of file date.hpp.
Constructor & Destructor Documentation
QuantLib::Date::Date ()
Default constructor returning a null date.
Definition at line 37 of file date.cpp.
Referenced by advance(), endOfMonth(), nthWeekday(), operator+(), operator-(), and todaysDate().
    : serialNumber_(BigInteger(0)) {}
QuantLib::Date::Date (BigInteger serialNumber) [explicit]
Constructor taking a serial number as given by Applix or Excel.
Definition at line 40 of file date.cpp.
References checkSerialNumber().
    : serialNumber_(serialNumber) {
        checkSerialNumber(serialNumber);
    }
QuantLib::Date::Date (Day d, Month m, Year y)
More traditional constructor.
Definition at line 45 of file date.cpp.
References isLeap(), anonymous_namespace{libormarketmodelprocess.cpp}::len, monthLength(), monthOffset(), QL_REQUIRE, serialNumber_, and yearOffset().
{
        QL_REQUIRE(y > 1900 && y < 2200,
                   "year " << y << " out of bound. It must be in [1901,2199]");
        QL_REQUIRE(Integer(m) > 0 && Integer(m) < 13,
                   "month " << Integer(m)
                   << " outside January-December range [1,12]");
        bool leap = isLeap(y);
        Day len = monthLength(m,leap), offset = monthOffset(m,leap);
        QL_REQUIRE(d <= len && d > 0,
                   "day outside month (" << Integer(m) << ") day-range "
                   << "[1," << len << "]");
        serialNumber_ = d + offset + yearOffset(y);
    }
Member Function Documentation
Date QuantLib::Date::advance (const Date & d, Integer units, TimeUnit units) [static, private]
Definition at line 151 of file date.cpp.
References anonymous_namespace{marketmodel.cpp}::d, Date(), dayOfMonth(), QuantLib::Days, QuantLib::February, isLeap(), month(), monthLength(), QuantLib::Months, QL_ENSURE, QL_FAIL, QuantLib::Weeks, year(), and QuantLib::Years.
Referenced by anonymous_namespace{bermudanswaption.cpp}::CommonVars::CommonVars(), QuantLib::MakeCms::operator boost::shared_ptr< Swap >(), QuantLib::MakeVanillaSwap::operator boost::shared_ptr< VanillaSwap >(), operator+(), operator+=(), operator-(), operator-=(), DigitalCouponTest::testAssetOrNothing(), DigitalCouponTest::testAssetOrNothingDeepInTheMoney(), DigitalCouponTest::testAssetOrNothingDeepOutTheMoney(), CapFloorTest::testATMRate(), SwaptionTest::testCachedValue(), DigitalCouponTest::testCallPutParity(), DigitalCouponTest::testCashOrNothing(), DigitalCouponTest::testCashOrNothingDeepInTheMoney(), DigitalCouponTest::testCashOrNothingDeepOutTheMoney(), SwaptionTest::testCashSettledSwaptions(), TermStructureTest::testImplied(), TermStructureTest::testImpliedObs(), SwaptionTest::testImpliedVolatility(), CapFloorTest::testParity(), DigitalCouponTest::testReplicationType(), SwaptionTest::testSpreadDependency(), SwaptionTest::testSpreadTreatment(), SwaptionTest::testStrikeDependency(), BondTest::testTheoretical(), SwaptionTest::testVega(), BondTest::testYield(), and BondTest::testZspread().
{
        switch (units) {
          case Days:
            return date + n;
          case Weeks:
            return date + 7*n;
          case Months: {
            Day d = date.dayOfMonth();
            Integer m = Integer(date.month())+n;
            Year y = date.year();
            while (m > 12) {
                m -= 12;
                y += 1;
            }
            while (m < 1) {
                m += 12;
                y -= 1;
            }
            QL_ENSURE(y >= 1900 && y <= 2199,
                      "year " << y << " out of bounds. "
                      << "It must be in [1901,2199]");
            Integer length = monthLength(Month(m), isLeap(y));
            if (d > length)
                d = length;
            return Date(d, Month(m), y);
          }
          case Years: {
              Day d = date.dayOfMonth();
              Month m = date.month();
              Year y = date.year()+n;
              QL_ENSURE(y >= 1900 && y <= 2199,
                        "year " << y << " out of bounds. "
                        << "It must be in [1901,2199]");
              if (d == 29 && m == February && !isLeap(y))
                  d = 28;
              return Date(d,m,y);
          }
          default:
            QL_FAIL("undefined time units");
        }
    }
void QuantLib::Date::checkSerialNumber (BigInteger serialNumber) [static, private]
Definition at line 389 of file date.cpp.
References maxDate(), maximumSerialNumber(), minDate(), minimumSerialNumber(), and QL_REQUIRE.
Referenced by Date(), operator++(), operator+=(), operator--(), and operator-=().
{
        QL_REQUIRE(serialNumber >= minimumSerialNumber() &&
                   serialNumber <= maximumSerialNumber(),
                   "Date's serial number (" << serialNumber << ") outside "
                   "allowed range [" << minimumSerialNumber() <<
                   "-" << maximumSerialNumber() << "], i.e. [" <<
                   minDate() << "-" << maxDate() << "]");
    }
Day QuantLib::Date::dayOfMonth () const [inline]
Definition at line 258 of file date.hpp.
References dayOfYear(), isLeap(), month(), monthOffset(), and year().
Referenced by advance(), QuantLib::Thirty360::US_Impl::dayCount(), QuantLib::Thirty360::EU_Impl::dayCount(), QuantLib::Thirty360::IT_Impl::dayCount(), QuantLib::Turkey::Impl::isBusinessDay(), QuantLib::Russia::SettlementImpl::isBusinessDay(), QuantLib::Hungary::Impl::isBusinessDay(), QuantLib::Switzerland::Impl::isBusinessDay(), QuantLib::TARGET::Impl::isBusinessDay(), QuantLib::Norway::Impl::isBusinessDay(), QuantLib::Denmark::Impl::isBusinessDay(), QuantLib::Poland::Impl::isBusinessDay(), QuantLib::Mexico::BmvImpl::isBusinessDay(), QuantLib::Australia::Impl::isBusinessDay(), QuantLib::Finland::Impl::isBusinessDay(), QuantLib::SaudiArabia::TadawulImpl::isBusinessDay(), QuantLib::CzechRepublic::PseImpl::isBusinessDay(), QuantLib::Ukraine::UseImpl::isBusinessDay(), QuantLib::Sweden::Impl::isBusinessDay(), QuantLib::Iceland::IcexImpl::isBusinessDay(), QuantLib::SouthAfrica::Impl::isBusinessDay(), QuantLib::Argentina::MervalImpl::isBusinessDay(), QuantLib::Taiwan::TsecImpl::isBusinessDay(), QuantLib::NewZealand::Impl::isBusinessDay(), QuantLib::Slovakia::BsseImpl::isBusinessDay(), QuantLib::China::SseImpl::isBusinessDay(), QuantLib::Singapore::SgxImpl::isBusinessDay(), QuantLib::Indonesia::BejImpl::isBusinessDay(), QuantLib::Japan::Impl::isBusinessDay(), QuantLib::HongKong::HkexImpl::isBusinessDay(), QuantLib::India::NseImpl::isBusinessDay(), QuantLib::Italy::SettlementImpl::isBusinessDay(), QuantLib::Canada::SettlementImpl::isBusinessDay(), QuantLib::SouthKorea::SettlementImpl::isBusinessDay(), QuantLib::Italy::ExchangeImpl::isBusinessDay(), QuantLib::Brazil::SettlementImpl::isBusinessDay(), QuantLib::Canada::TsxImpl::isBusinessDay(), QuantLib::SouthKorea::KrxImpl::isBusinessDay(), QuantLib::Brazil::ExchangeImpl::isBusinessDay(), QuantLib::UnitedKingdom::SettlementImpl::isBusinessDay(), QuantLib::UnitedKingdom::ExchangeImpl::isBusinessDay(), QuantLib::UnitedKingdom::MetalsImpl::isBusinessDay(), QuantLib::Germany::SettlementImpl::isBusinessDay(), QuantLib::UnitedStates::SettlementImpl::isBusinessDay(), QuantLib::Germany::FrankfurtStockExchangeImpl::isBusinessDay(), QuantLib::Germany::XetraImpl::isBusinessDay(), QuantLib::UnitedStates::NyseImpl::isBusinessDay(), QuantLib::Germany::EurexImpl::isBusinessDay(), QuantLib::UnitedStates::GovernmentBondImpl::isBusinessDay(), QuantLib::Germany::EuwaxImpl::isBusinessDay(), QuantLib::UnitedStates::NercImpl::isBusinessDay(), isEndOfMonth(), QuantLib::IMM::isIMMdate(), DateTest::isoDates(), QuantLib::IMM::nextDate(), QuantLib::detail::operator<<(), DateTest::testConsistency(), and QuantLib::SimpleDayCounter::Impl::yearFraction().
{
        return dayOfYear() - monthOffset(month(),isLeap(year()));
    }
Day QuantLib::Date::dayOfYear () const [inline]
One-based (Jan 1st = 1)
Definition at line 262 of file date.hpp.
References serialNumber_, year(), and yearOffset().
Referenced by dayOfMonth(), QuantLib::Denmark::Impl::isBusinessDay(), QuantLib::Hungary::Impl::isBusinessDay(), QuantLib::Mexico::BmvImpl::isBusinessDay(), QuantLib::Norway::Impl::isBusinessDay(), QuantLib::Poland::Impl::isBusinessDay(), QuantLib::Switzerland::Impl::isBusinessDay(), QuantLib::TARGET::Impl::isBusinessDay(), QuantLib::Finland::Impl::isBusinessDay(), QuantLib::Australia::Impl::isBusinessDay(), QuantLib::Ukraine::UseImpl::isBusinessDay(), QuantLib::CzechRepublic::PseImpl::isBusinessDay(), QuantLib::Iceland::IcexImpl::isBusinessDay(), QuantLib::Sweden::Impl::isBusinessDay(), QuantLib::Argentina::MervalImpl::isBusinessDay(), QuantLib::SouthAfrica::Impl::isBusinessDay(), QuantLib::NewZealand::Impl::isBusinessDay(), QuantLib::Slovakia::BsseImpl::isBusinessDay(), QuantLib::Singapore::SgxImpl::isBusinessDay(), QuantLib::Indonesia::BejImpl::isBusinessDay(), QuantLib::HongKong::HkexImpl::isBusinessDay(), QuantLib::India::NseImpl::isBusinessDay(), QuantLib::Italy::SettlementImpl::isBusinessDay(), QuantLib::Canada::SettlementImpl::isBusinessDay(), QuantLib::Italy::ExchangeImpl::isBusinessDay(), QuantLib::Brazil::SettlementImpl::isBusinessDay(), QuantLib::Canada::TsxImpl::isBusinessDay(), QuantLib::Brazil::ExchangeImpl::isBusinessDay(), QuantLib::UnitedKingdom::SettlementImpl::isBusinessDay(), QuantLib::UnitedKingdom::ExchangeImpl::isBusinessDay(), QuantLib::UnitedKingdom::MetalsImpl::isBusinessDay(), QuantLib::Germany::SettlementImpl::isBusinessDay(), QuantLib::Germany::FrankfurtStockExchangeImpl::isBusinessDay(), QuantLib::Germany::XetraImpl::isBusinessDay(), QuantLib::UnitedStates::NyseImpl::isBusinessDay(), QuantLib::Germany::EurexImpl::isBusinessDay(), QuantLib::UnitedStates::GovernmentBondImpl::isBusinessDay(), QuantLib::Germany::EuwaxImpl::isBusinessDay(), month(), and DateTest::testConsistency().
{
        return serialNumber_ - yearOffset(year());
    }
Date QuantLib::Date::endOfMonth (const Date & d) [inline, static]
last day of the month to which the given date belongs
Definition at line 286 of file date.hpp.
References Date(), isLeap(), month(), monthLength(), and year().
Referenced by QuantLib::Calendar::endOfMonth(), QuantLib::inflationPeriod(), and QuantLib::Schedule::Schedule().
{
        Month m = d.month();
        Year y = d.year();
        return Date(monthLength(m, isLeap(y)), m, y);
    }
bool QuantLib::Date::isEndOfMonth (const Date & d) [inline, static]
whether a date is the last day of its month
Definition at line 292 of file date.hpp.
References dayOfMonth(), isLeap(), month(), monthLength(), and year().
Referenced by QuantLib::SimpleDayCounter::Impl::yearFraction().
{
       return (d.dayOfMonth() == monthLength(d.month(), isLeap(d.year())));
    }
bool QuantLib::Date::isLeap (Year y) [static]
whether the given year is a leap one
Definition at line 199 of file date.cpp.
References QL_REQUIRE.
Referenced by advance(), Date(), dayOfMonth(), endOfMonth(), isEndOfMonth(), month(), DateTest::testConsistency(), QuantLib::ActualActual::ISDA_Impl::yearFraction(), and QuantLib::ActualActual::AFB_Impl::yearFraction().
{
        static const bool YearIsLeap[] = {
            // 1900 is leap in agreement with Excel's bug
            // 1900 is out of valid date range anyway
            // 1900-1909
             true,false,false,false, true,false,false,false, true,false,
            // 1910-1919
            false,false, true,false,false,false, true,false,false,false,
            // 1920-1929
             true,false,false,false, true,false,false,false, true,false,
            // 1930-1939
            false,false, true,false,false,false, true,false,false,false,
            // 1940-1949
             true,false,false,false, true,false,false,false, true,false,
            // 1950-1959
            false,false, true,false,false,false, true,false,false,false,
            // 1960-1969
             true,false,false,false, true,false,false,false, true,false,
            // 1970-1979
            false,false, true,false,false,false, true,false,false,false,
            // 1980-1989
             true,false,false,false, true,false,false,false, true,false,
            // 1990-1999
            false,false, true,false,false,false, true,false,false,false,
            // 2000-2009
             true,false,false,false, true,false,false,false, true,false,
            // 2010-2019
            false,false, true,false,false,false, true,false,false,false,
            // 2020-2029
             true,false,false,false, true,false,false,false, true,false,
            // 2030-2039
            false,false, true,false,false,false, true,false,false,false,
            // 2040-2049
             true,false,false,false, true,false,false,false, true,false,
            // 2050-2059
            false,false, true,false,false,false, true,false,false,false,
            // 2060-2069
             true,false,false,false, true,false,false,false, true,false,
            // 2070-2079
            false,false, true,false,false,false, true,false,false,false,
            // 2080-2089
             true,false,false,false, true,false,false,false, true,false,
            // 2090-2099
            false,false, true,false,false,false, true,false,false,false,
            // 2100-2109
            false,false,false,false, true,false,false,false, true,false,
            // 2110-2119
            false,false, true,false,false,false, true,false,false,false,
            // 2120-2129
             true,false,false,false, true,false,false,false, true,false,
            // 2130-2139
            false,false, true,false,false,false, true,false,false,false,
            // 2140-2149
             true,false,false,false, true,false,false,false, true,false,
            // 2150-2159
            false,false, true,false,false,false, true,false,false,false,
            // 2160-2169
             true,false,false,false, true,false,false,false, true,false,
            // 2170-2179
            false,false, true,false,false,false, true,false,false,false,
            // 2180-2189
             true,false,false,false, true,false,false,false, true,false,
            // 2190-2199
            false,false, true,false,false,false, true,false,false,false,
            // 2200
            false
        };
        QL_REQUIRE(y>=1900 && y<=2200, "year outside valid range");
        return YearIsLeap[y-1900];
    }
Date QuantLib::Date::maxDate () [static]
latest allowed date
Definition at line 146 of file date.cpp.
References maximumSerialNumber().
Referenced by QuantLib::ExchangeRateManager::addKnownRates(), checkSerialNumber(), DateTest::immDates(), QuantLib::anonymous_namespace{analyticbsmhullwhiteengine.cpp}::ShiftedBlackVolTermStructure::maxDate(), QuantLib::Basket::scenarioIncrementalTrancheLosses(), QuantLib::CashFlows::startDate(), DateTest::testConsistency(), and CalendarTest::testEndOfMonth().
                       {
        static const Date maximumDate(maximumSerialNumber());
        return maximumDate;
    }
BigInteger QuantLib::Date::maximumSerialNumber () [static, private]
Definition at line 385 of file date.cpp.
Referenced by checkSerialNumber(), and maxDate().
{
        return 109574;    // Dec 31st, 2199
    }
Date QuantLib::Date::minDate () [static]
earliest allowed date
Definition at line 141 of file date.cpp.
References minimumSerialNumber().
Referenced by QuantLib::AmericanExercise::AmericanExercise(), QuantLib::CallableBond::CallableBond(), checkSerialNumber(), QuantLib::ECB::date(), DateTest::ecbDates(), DateTest::immDates(), QuantLib::CommodityIndex::lastQuoteDate(), QuantLib::CashFlows::maturityDate(), QuantLib::FittedBondDiscountCurve::performCalculations(), QuantLib::Basket::scenarioIncrementalTrancheLosses(), DateTest::testConsistency(), and CalendarTest::testEndOfMonth().
                       {
        static const Date minimumDate(minimumSerialNumber());
        return minimumDate;
    }
BigInteger QuantLib::Date::minimumSerialNumber () [static, private]
Definition at line 381 of file date.cpp.
Referenced by checkSerialNumber(), and minDate().
{
        return 367;       // Jan 1st, 1901
    }
Month QuantLib::Date::month () const
Definition at line 61 of file date.cpp.
References anonymous_namespace{marketmodel.cpp}::d, dayOfYear(), isLeap(), monthOffset(), and year().
Referenced by QuantLib::Calendar::adjust(), advance(), QuantLib::IMM::code(), QuantLib::ECB::code(), QuantLib::Business252::Impl::dayCount(), QuantLib::Thirty360::US_Impl::dayCount(), QuantLib::Thirty360::EU_Impl::dayCount(), QuantLib::Thirty360::IT_Impl::dayCount(), dayOfMonth(), endOfMonth(), QuantLib::inflationPeriod(), QuantLib::Turkey::Impl::isBusinessDay(), QuantLib::Russia::SettlementImpl::isBusinessDay(), QuantLib::Switzerland::Impl::isBusinessDay(), QuantLib::Hungary::Impl::isBusinessDay(), QuantLib::TARGET::Impl::isBusinessDay(), QuantLib::Mexico::BmvImpl::isBusinessDay(), QuantLib::Denmark::Impl::isBusinessDay(), QuantLib::Norway::Impl::isBusinessDay(), QuantLib::Poland::Impl::isBusinessDay(), QuantLib::SaudiArabia::TadawulImpl::isBusinessDay(), QuantLib::Australia::Impl::isBusinessDay(), QuantLib::Finland::Impl::isBusinessDay(), QuantLib::Ukraine::UseImpl::isBusinessDay(), QuantLib::CzechRepublic::PseImpl::isBusinessDay(), QuantLib::Sweden::Impl::isBusinessDay(), QuantLib::Iceland::IcexImpl::isBusinessDay(), QuantLib::Argentina::MervalImpl::isBusinessDay(), QuantLib::SouthAfrica::Impl::isBusinessDay(), QuantLib::Slovakia::BsseImpl::isBusinessDay(), QuantLib::Taiwan::TsecImpl::isBusinessDay(), QuantLib::NewZealand::Impl::isBusinessDay(), QuantLib::China::SseImpl::isBusinessDay(), QuantLib::Singapore::SgxImpl::isBusinessDay(), QuantLib::Indonesia::BejImpl::isBusinessDay(), QuantLib::Japan::Impl::isBusinessDay(), QuantLib::HongKong::HkexImpl::isBusinessDay(), QuantLib::India::NseImpl::isBusinessDay(), QuantLib::Italy::SettlementImpl::isBusinessDay(), QuantLib::Canada::SettlementImpl::isBusinessDay(), QuantLib::SouthKorea::SettlementImpl::isBusinessDay(), QuantLib::Italy::ExchangeImpl::isBusinessDay(), QuantLib::Brazil::SettlementImpl::isBusinessDay(), QuantLib::Canada::TsxImpl::isBusinessDay(), QuantLib::SouthKorea::KrxImpl::isBusinessDay(), QuantLib::Brazil::ExchangeImpl::isBusinessDay(), QuantLib::UnitedKingdom::SettlementImpl::isBusinessDay(), QuantLib::UnitedKingdom::ExchangeImpl::isBusinessDay(), QuantLib::UnitedKingdom::MetalsImpl::isBusinessDay(), QuantLib::Germany::SettlementImpl::isBusinessDay(), QuantLib::UnitedStates::SettlementImpl::isBusinessDay(), QuantLib::Germany::FrankfurtStockExchangeImpl::isBusinessDay(), QuantLib::Germany::XetraImpl::isBusinessDay(), QuantLib::UnitedStates::NyseImpl::isBusinessDay(), QuantLib::Germany::EurexImpl::isBusinessDay(), QuantLib::UnitedStates::GovernmentBondImpl::isBusinessDay(), QuantLib::Germany::EuwaxImpl::isBusinessDay(), QuantLib::UnitedStates::NercImpl::isBusinessDay(), QuantLib::Calendar::isEndOfMonth(), isEndOfMonth(), QuantLib::IMM::isIMMdate(), DateTest::isoDates(), QuantLib::IMM::nextDate(), QuantLib::anonymous_namespace{schedule.cpp}::nextTwentieth(), QuantLib::detail::operator<<(), QuantLib::anonymous_namespace{schedule.cpp}::previousTwentieth(), QuantLib::anonymous_namespace{business252.cpp}::sameMonth(), DateTest::testConsistency(), CalendarTest::testEndOfMonth(), and QuantLib::SimpleDayCounter::Impl::yearFraction().
{
        Day d = dayOfYear(); // dayOfYear is 1 based
        Integer m = d/30 + 1;
        bool leap = isLeap(year());
        while (d <= monthOffset(Month(m),leap))
            --m;
        while (d > monthOffset(Month(m+1),leap))
            ++m;
        return Month(m);
    }
Integer QuantLib::Date::monthLength (Month m, bool leapYear) [static, private]
Definition at line 287 of file date.cpp.
Referenced by advance(), Date(), endOfMonth(), and isEndOfMonth().
{
        static const Integer MonthLength[] = {
            31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31
        };
        static const Integer MonthLeapLength[] = {
            31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31
        };
        return (leapYear? MonthLeapLength[m-1] : MonthLength[m-1]);
    }
Integer QuantLib::Date::monthOffset (Month m, bool leapYear) [static, private]
Definition at line 297 of file date.cpp.
Referenced by Date(), dayOfMonth(), and month().
{
        static const Integer MonthOffset[] = {
              0,  31,  59,  90, 120, 151,   // Jan - Jun
            181, 212, 243, 273, 304, 334,   // Jun - Dec
            365     // used in dayOfMonth to bracket day
        };
        static const Integer MonthLeapOffset[] = {
              0,  31,  60,  91, 121, 152,   // Jan - Jun
            182, 213, 244, 274, 305, 335,   // Jun - Dec
            366     // used in dayOfMonth to bracket day
        };
        return (leapYear? MonthLeapOffset[m-1] : MonthOffset[m-1]);
    }
Date QuantLib::Date::nextWeekday (const Date & d, Weekday w) [static]
next given weekday following or equal to the given date
E.g., the Friday following Tuesday, January 15th, 2002 was January 18th, 2002.
see http://www.cpearson.com/excel/DateTimeWS.htm
Definition at line 271 of file date.cpp.
References weekday().
{
        Weekday wd = d.weekday();
        return d + ((wd>dayOfWeek ? 7 : 0) - wd + dayOfWeek);
    }
Date QuantLib::Date::nthWeekday (Size n, Weekday w, Month m, Year y) [static]
n-th given weekday in the given month and year
E.g., the 4th Thursday of March, 1998 was March 26th, 1998.
see http://www.cpearson.com/excel/DateTimeWS.htm
Definition at line 276 of file date.cpp.
References Date(), and QL_REQUIRE.
Referenced by QuantLib::IMM::nextDate(), and QuantLib::Schedule::Schedule().
{
        QL_REQUIRE(nth>0,
                   "zeroth day of week in a given (month, year) is undefined");
        QL_REQUIRE(nth<6,
                   "no more than 5 weekday in a given (month, year)");
        Weekday first = Date(1, m, y).weekday();
        Size skip = nth - (dayOfWeek>=first ? 1 : 0);
        return Date(1 + dayOfWeek-first + skip*7, m, y);
    }
Date QuantLib::Date::operator+ (BigInteger days) const [inline]
returns a new date incremented by the given number of days
Definition at line 270 of file date.hpp.
References Date(), and serialNumber_.
{
        return Date(serialNumber_+days);
    }
Date QuantLib::Date::operator+ (const Period & p) const [inline]
returns a new date incremented by the given period
Definition at line 278 of file date.hpp.
References advance(), QuantLib::Period::length(), and QuantLib::Period::units().
{
        return advance(*this,p.length(),p.units());
    }
Date & QuantLib::Date::operator++ ()
1-day pre-increment
Definition at line 104 of file date.cpp.
References checkSerialNumber(), and serialNumber_.
{
        BigInteger serial = serialNumber_ + 1;
        checkSerialNumber(serial);
        serialNumber_ = serial;
        return *this;
    }
Date QuantLib::Date::operator++ (int)
1-day post-increment
Definition at line 111 of file date.cpp.
{
        Date old(*this);
        ++*this; // use the pre-increment
        return old;
    }
Date & QuantLib::Date::operator+= (BigInteger days)
increments date by the given number of days
Definition at line 80 of file date.cpp.
References checkSerialNumber(), QuantLib::days(), and serialNumber_.
{
        BigInteger serial = serialNumber_ + days;
        checkSerialNumber(serial);
        serialNumber_ = serial;
        return *this;
    }
Date & QuantLib::Date::operator+= (const Period & p)
increments date by the given period
Definition at line 87 of file date.cpp.
References advance(), QuantLib::Period::length(), serialNumber(), serialNumber_, and QuantLib::Period::units().
{
        serialNumber_ = advance(*this,p.length(),p.units()).serialNumber();
        return *this;
    }
Date QuantLib::Date::operator- (BigInteger days) const [inline]
returns a new date decremented by the given number of days
Definition at line 274 of file date.hpp.
References Date(), and serialNumber_.
{
        return Date(serialNumber_-days);
    }
Date QuantLib::Date::operator- (const Period & p) const [inline]
returns a new date decremented by the given period
Definition at line 282 of file date.hpp.
References advance(), QuantLib::Period::length(), and QuantLib::Period::units().
{
        return advance(*this,-p.length(),p.units());
    }
Date & QuantLib::Date::operator-- ()
1-day pre-decrement
Definition at line 117 of file date.cpp.
References checkSerialNumber(), and serialNumber_.
{
        BigInteger serial = serialNumber_ - 1;
        checkSerialNumber(serial);
        serialNumber_ = serial;
        return *this;
    }
Date QuantLib::Date::operator-- (int)
1-day post-decrement
Definition at line 124 of file date.cpp.
{
        Date old(*this);
        --*this; // use the pre-decrement
        return old;
    }
Date & QuantLib::Date::operator-= (BigInteger days)
decrement date by the given number of days
Definition at line 92 of file date.cpp.
References checkSerialNumber(), QuantLib::days(), and serialNumber_.
{
        BigInteger serial = serialNumber_ - days;
        checkSerialNumber(serial);
        serialNumber_ = serial;
        return *this;
    }
Date & QuantLib::Date::operator-= (const Period & p)
decrements date by the given period
Definition at line 99 of file date.cpp.
References advance(), QuantLib::Period::length(), serialNumber(), serialNumber_, and QuantLib::Period::units().
{
        serialNumber_ = advance(*this,-p.length(),p.units()).serialNumber();
        return *this;
    }
BigInteger QuantLib::Date::serialNumber () const [inline]
Definition at line 266 of file date.hpp.
References serialNumber_.
Referenced by QuantLib::operator!=(), operator+=(), QuantLib::operator-(), operator-=(), QuantLib::operator<(), QuantLib::operator<=(), QuantLib::operator==(), QuantLib::operator>(), QuantLib::operator>=(), and DateTest::testConsistency().
{
        return serialNumber_;
    }
Date QuantLib::Date::todaysDate () [static]
today's date.
Definition at line 130 of file date.cpp.
References Date(), and anonymous_namespace{quantlibbenchmark.cpp}::t.
Referenced by QuantLib::Settings::anchorEvaluationDate(), anonymous_namespace{swaptionvolatilitymatrix.cpp}::CommonVars::CommonVars(), anonymous_namespace{digitalcoupon.cpp}::CommonVars::CommonVars(), anonymous_namespace{bermudanswaption.cpp}::CommonVars::CommonVars(), anonymous_namespace{termstructures.cpp}::CommonVars::CommonVars(), anonymous_namespace{bonds.cpp}::CommonVars::CommonVars(), anonymous_namespace{capfloor.cpp}::CommonVars::CommonVars(), anonymous_namespace{capflooredcoupon.cpp}::CommonVars::CommonVars(), anonymous_namespace{cms.cpp}::CommonVars::CommonVars(), anonymous_namespace{convertiblebonds.cpp}::CommonVars::CommonVars(), anonymous_namespace{swap.cpp}::CommonVars::CommonVars(), anonymous_namespace{swaption.cpp}::CommonVars::CommonVars(), anonymous_namespace{piecewiseyieldcurve.cpp}::CommonVars::CommonVars(), anonymous_namespace{optionletstripper.cpp}::CommonVars::setTermStructure(), anonymous_namespace{piecewiseyieldcurve.cpp}::testBMACurveConsistency(), CreditDefaultSwapTest::testFairSpread(), CreditDefaultSwapTest::testFairUpfront(), CreditDefaultSwapTest::testImpliedHazardRate(), and LiborMarketModelProcessTest::testInitialisation().
{
        std::time_t t;
        if (std::time(&t) == std::time_t(-1)) // -1 means time() didn't work
            return Date();
        std::tm *lt = std::localtime(&t);
        return Date(Day(lt->tm_mday),
                    Month(lt->tm_mon+1),
                    Year(lt->tm_year+1900));
    }
Weekday QuantLib::Date::weekday () const [inline]
Definition at line 253 of file date.hpp.
References serialNumber_.
Referenced by QuantLib::Index::addFixings(), DateTest::immDates(), QuantLib::BMASwapRateHelper::initializeDates(), QuantLib::WeekendsOnly::Impl::isBusinessDay(), QuantLib::BespokeCalendar::Impl::isBusinessDay(), QuantLib::Russia::SettlementImpl::isBusinessDay(), QuantLib::Turkey::Impl::isBusinessDay(), QuantLib::Hungary::Impl::isBusinessDay(), QuantLib::Switzerland::Impl::isBusinessDay(), QuantLib::TARGET::Impl::isBusinessDay(), QuantLib::Denmark::Impl::isBusinessDay(), QuantLib::Mexico::BmvImpl::isBusinessDay(), QuantLib::Norway::Impl::isBusinessDay(), QuantLib::Poland::Impl::isBusinessDay(), QuantLib::SaudiArabia::TadawulImpl::isBusinessDay(), QuantLib::Australia::Impl::isBusinessDay(), QuantLib::Finland::Impl::isBusinessDay(), QuantLib::Ukraine::UseImpl::isBusinessDay(), QuantLib::CzechRepublic::PseImpl::isBusinessDay(), QuantLib::Sweden::Impl::isBusinessDay(), QuantLib::Iceland::IcexImpl::isBusinessDay(), QuantLib::SouthAfrica::Impl::isBusinessDay(), QuantLib::Argentina::MervalImpl::isBusinessDay(), QuantLib::Slovakia::BsseImpl::isBusinessDay(), QuantLib::Taiwan::TsecImpl::isBusinessDay(), QuantLib::NewZealand::Impl::isBusinessDay(), QuantLib::China::SseImpl::isBusinessDay(), QuantLib::Singapore::SgxImpl::isBusinessDay(), QuantLib::Indonesia::BejImpl::isBusinessDay(), QuantLib::Japan::Impl::isBusinessDay(), QuantLib::HongKong::HkexImpl::isBusinessDay(), QuantLib::India::NseImpl::isBusinessDay(), QuantLib::Italy::SettlementImpl::isBusinessDay(), QuantLib::Canada::SettlementImpl::isBusinessDay(), QuantLib::SouthKorea::SettlementImpl::isBusinessDay(), QuantLib::Italy::ExchangeImpl::isBusinessDay(), QuantLib::Brazil::SettlementImpl::isBusinessDay(), QuantLib::Canada::TsxImpl::isBusinessDay(), QuantLib::Brazil::ExchangeImpl::isBusinessDay(), QuantLib::UnitedKingdom::SettlementImpl::isBusinessDay(), QuantLib::UnitedKingdom::ExchangeImpl::isBusinessDay(), QuantLib::UnitedKingdom::MetalsImpl::isBusinessDay(), QuantLib::Germany::SettlementImpl::isBusinessDay(), QuantLib::Germany::FrankfurtStockExchangeImpl::isBusinessDay(), QuantLib::UnitedStates::SettlementImpl::isBusinessDay(), QuantLib::UnitedStates::NyseImpl::isBusinessDay(), QuantLib::Germany::XetraImpl::isBusinessDay(), QuantLib::UnitedStates::GovernmentBondImpl::isBusinessDay(), QuantLib::Germany::EurexImpl::isBusinessDay(), QuantLib::Germany::EuwaxImpl::isBusinessDay(), QuantLib::UnitedStates::NercImpl::isBusinessDay(), QuantLib::IMM::isIMMdate(), nextWeekday(), QuantLib::anonymous_namespace{bmaindex.cpp}::previousWednesday(), anonymous_namespace{piecewiseyieldcurve.cpp}::testBMACurveConsistency(), DateTest::testConsistency(), and CalendarTest::testEndOfMonth().
{
        Integer w = serialNumber_ % 7;
        return Weekday(w == 0 ? 7 : w);
    }
Year QuantLib::Date::year () const
Definition at line 72 of file date.cpp.
References serialNumber_, and yearOffset().
Referenced by advance(), QuantLib::IMM::code(), QuantLib::ECB::code(), QuantLib::ECB::date(), QuantLib::IMM::date(), QuantLib::Business252::Impl::dayCount(), QuantLib::Thirty360::US_Impl::dayCount(), QuantLib::Thirty360::EU_Impl::dayCount(), QuantLib::Thirty360::IT_Impl::dayCount(), dayOfMonth(), dayOfYear(), endOfMonth(), QuantLib::inflationPeriod(), QuantLib::Turkey::Impl::isBusinessDay(), QuantLib::Switzerland::Impl::isBusinessDay(), QuantLib::Hungary::Impl::isBusinessDay(), QuantLib::TARGET::Impl::isBusinessDay(), QuantLib::Denmark::Impl::isBusinessDay(), QuantLib::Mexico::BmvImpl::isBusinessDay(), QuantLib::Norway::Impl::isBusinessDay(), QuantLib::Poland::Impl::isBusinessDay(), QuantLib::Australia::Impl::isBusinessDay(), QuantLib::Finland::Impl::isBusinessDay(), QuantLib::SaudiArabia::TadawulImpl::isBusinessDay(), QuantLib::CzechRepublic::PseImpl::isBusinessDay(), QuantLib::Ukraine::UseImpl::isBusinessDay(), QuantLib::Sweden::Impl::isBusinessDay(), QuantLib::Iceland::IcexImpl::isBusinessDay(), QuantLib::SouthAfrica::Impl::isBusinessDay(), QuantLib::Argentina::MervalImpl::isBusinessDay(), QuantLib::Slovakia::BsseImpl::isBusinessDay(), QuantLib::Taiwan::TsecImpl::isBusinessDay(), QuantLib::NewZealand::Impl::isBusinessDay(), QuantLib::China::SseImpl::isBusinessDay(), QuantLib::Singapore::SgxImpl::isBusinessDay(), QuantLib::Indonesia::BejImpl::isBusinessDay(), QuantLib::Japan::Impl::isBusinessDay(), QuantLib::HongKong::HkexImpl::isBusinessDay(), QuantLib::India::NseImpl::isBusinessDay(), QuantLib::Italy::SettlementImpl::isBusinessDay(), QuantLib::Canada::SettlementImpl::isBusinessDay(), QuantLib::SouthKorea::SettlementImpl::isBusinessDay(), QuantLib::Italy::ExchangeImpl::isBusinessDay(), QuantLib::Brazil::SettlementImpl::isBusinessDay(), QuantLib::Canada::TsxImpl::isBusinessDay(), QuantLib::SouthKorea::KrxImpl::isBusinessDay(), QuantLib::Brazil::ExchangeImpl::isBusinessDay(), QuantLib::UnitedKingdom::SettlementImpl::isBusinessDay(), QuantLib::UnitedKingdom::ExchangeImpl::isBusinessDay(), QuantLib::UnitedKingdom::MetalsImpl::isBusinessDay(), QuantLib::Germany::SettlementImpl::isBusinessDay(), QuantLib::Germany::FrankfurtStockExchangeImpl::isBusinessDay(), QuantLib::Germany::XetraImpl::isBusinessDay(), QuantLib::UnitedStates::NyseImpl::isBusinessDay(), QuantLib::Germany::EurexImpl::isBusinessDay(), QuantLib::UnitedStates::GovernmentBondImpl::isBusinessDay(), QuantLib::Germany::EuwaxImpl::isBusinessDay(), isEndOfMonth(), DateTest::isoDates(), month(), QuantLib::IMM::nextDate(), QuantLib::anonymous_namespace{schedule.cpp}::nextTwentieth(), QuantLib::detail::operator<<(), QuantLib::anonymous_namespace{schedule.cpp}::previousTwentieth(), QuantLib::anonymous_namespace{business252.cpp}::sameMonth(), QuantLib::anonymous_namespace{business252.cpp}::sameYear(), QuantLib::DefaultProbabilityTermStructure::setJumps(), QuantLib::YieldTermStructure::setJumps(), DateTest::testConsistency(), CalendarTest::testEndOfMonth(), InflationTest::testZeroTermStructure(), QuantLib::SimpleDayCounter::Impl::yearFraction(), QuantLib::ActualActual::ISDA_Impl::yearFraction(), and QuantLib::ActualActual::AFB_Impl::yearFraction().
{
        Year y = (serialNumber_ / 365)+1900;
        // yearOffset(y) is December 31st of the preceding year
        if (serialNumber_ <= yearOffset(y))
            --y;
        return y;
    }
BigInteger QuantLib::Date::yearOffset (Year y) [static, private]
Definition at line 311 of file date.cpp.
Referenced by Date(), dayOfYear(), and year().
{
        // the list of all December 31st in the preceding year
        // e.g. for 1901 yearOffset[1] is 366, that is, December 31 1900
        static const BigInteger YearOffset[] = {
            // 1900-1909
                0,  366,  731, 1096, 1461, 1827, 2192, 2557, 2922, 3288,
            // 1910-1919
             3653, 4018, 4383, 4749, 5114, 5479, 5844, 6210, 6575, 6940,
            // 1920-1929
             7305, 7671, 8036, 8401, 8766, 9132, 9497, 9862,10227,10593,
            // 1930-1939
            10958,11323,11688,12054,12419,12784,13149,13515,13880,14245,
            // 1940-1949
            14610,14976,15341,15706,16071,16437,16802,17167,17532,17898,
            // 1950-1959
            18263,18628,18993,19359,19724,20089,20454,20820,21185,21550,
            // 1960-1969
            21915,22281,22646,23011,23376,23742,24107,24472,24837,25203,
            // 1970-1979
            25568,25933,26298,26664,27029,27394,27759,28125,28490,28855,
            // 1980-1989
            29220,29586,29951,30316,30681,31047,31412,31777,32142,32508,
            // 1990-1999
            32873,33238,33603,33969,34334,34699,35064,35430,35795,36160,
            // 2000-2009
            36525,36891,37256,37621,37986,38352,38717,39082,39447,39813,
            // 2010-2019
            40178,40543,40908,41274,41639,42004,42369,42735,43100,43465,
            // 2020-2029
            43830,44196,44561,44926,45291,45657,46022,46387,46752,47118,
            // 2030-2039
            47483,47848,48213,48579,48944,49309,49674,50040,50405,50770,
            // 2040-2049
            51135,51501,51866,52231,52596,52962,53327,53692,54057,54423,
            // 2050-2059
            54788,55153,55518,55884,56249,56614,56979,57345,57710,58075,
            // 2060-2069
            58440,58806,59171,59536,59901,60267,60632,60997,61362,61728,
            // 2070-2079
            62093,62458,62823,63189,63554,63919,64284,64650,65015,65380,
            // 2080-2089
            65745,66111,66476,66841,67206,67572,67937,68302,68667,69033,
            // 2090-2099
            69398,69763,70128,70494,70859,71224,71589,71955,72320,72685,
            // 2100-2109
            73050,73415,73780,74145,74510,74876,75241,75606,75971,76337,
            // 2110-2119
            76702,77067,77432,77798,78163,78528,78893,79259,79624,79989,
            // 2120-2129
            80354,80720,81085,81450,81815,82181,82546,82911,83276,83642,
            // 2130-2139
            84007,84372,84737,85103,85468,85833,86198,86564,86929,87294,
            // 2140-2149
            87659,88025,88390,88755,89120,89486,89851,90216,90581,90947,
            // 2150-2159
            91312,91677,92042,92408,92773,93138,93503,93869,94234,94599,
            // 2160-2169
            94964,95330,95695,96060,96425,96791,97156,97521,97886,98252,
            // 2170-2179
            98617,98982,99347,99713,100078,100443,100808,101174,101539,101904,
            // 2180-2189
            102269,102635,103000,103365,103730,104096,104461,104826,105191,105557,
            // 2190-2199
            105922,106287,106652,107018,107383,107748,108113,108479,108844,109209,
            // 2200
            109574
        };
        return YearOffset[y-1900];
    }
Friends And Related Function Documentation
bool operator!= (const Date & , const Date &) [related]
Definition at line 304 of file date.hpp.
{
        return (d1.serialNumber() != d2.serialNumber());
    }
BigInteger operator- (const Date & , const Date &) [related]
Difference in days between dates.
Definition at line 296 of file date.hpp.
{
        return d1.serialNumber()-d2.serialNumber();
    }
bool operator< (const Date & , const Date &) [related]
Definition at line 308 of file date.hpp.
{
        return (d1.serialNumber() < d2.serialNumber());
    }
std::ostream & operator<< (std::ostream & , const Date &) [related]
Definition at line 434 of file date.cpp.
{
        return out << io::long_date(d);
    }
bool operator<= (const Date & , const Date &) [related]
Definition at line 312 of file date.hpp.
{
        return (d1.serialNumber() <= d2.serialNumber());
    }
bool operator== (const Date & , const Date &) [related]
Definition at line 300 of file date.hpp.
{
        return (d1.serialNumber() == d2.serialNumber());
    }
bool operator> (const Date & , const Date &) [related]
Definition at line 316 of file date.hpp.
{
        return (d1.serialNumber() > d2.serialNumber());
    }
bool operator>= (const Date & , const Date &) [related]
Definition at line 320 of file date.hpp.
{
        return (d1.serialNumber() >= d2.serialNumber());
    }
Member Data Documentation
BigInteger QuantLib::Date::serialNumber_ [private]
Definition at line 173 of file date.hpp.
Referenced by Date(), dayOfYear(), operator+(), operator++(), operator+=(), operator-(), operator--(), operator-=(), serialNumber(), weekday(), and year().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/time/date.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/time/date.cpp