QuantLib: SwapTest Class Reference
SwapTest Class Reference
#include <swap.hpp>
Static Public Member Functions
static void testFairRate ()
static void testFairSpread ()
static void testRateDependency ()
static void testSpreadDependency ()
static void testInArrears ()
static void testCachedValue ()
static
boost::unit_test_framework::test_suite * suite ()
Detailed Description
Definition at line 28 of file swap.hpp.
Member Function Documentation
test_suite * SwapTest::suite () [static]
Definition at line 326 of file swap.cpp.
References QUANTLIB_TEST_CASE, testCachedValue(), testFairRate(), testFairSpread(), testInArrears(), testRateDependency(), and testSpreadDependency().
Referenced by init_unit_test_suite().
{
    test_suite* suite = BOOST_TEST_SUITE("Swap tests");
    suite->add(QUANTLIB_TEST_CASE(&SwapTest::testFairRate));
    suite->add(QUANTLIB_TEST_CASE(&SwapTest::testFairSpread));
    suite->add(QUANTLIB_TEST_CASE(&SwapTest::testRateDependency));
    suite->add(QUANTLIB_TEST_CASE(&SwapTest::testSpreadDependency));
    suite->add(QUANTLIB_TEST_CASE(&SwapTest::testInArrears));
    suite->add(QUANTLIB_TEST_CASE(&SwapTest::testCachedValue));
    return suite;
}
void SwapTest::testCachedValue () [static]
Definition at line 299 of file swap.cpp.
References QuantLib::Days, QuantLib::Settings::evaluationDate(), QuantLib::flatRate(), QuantLib::Singleton< Settings >::instance(), QuantLib::June, QL_FIXED, and QuantLib::swap().
Referenced by suite().
{
    BOOST_MESSAGE("Testing vanilla-swap calculation against cached value...");
    CommonVars vars;
    vars.today = Date(17,June,2002);
    Settings::instance().evaluationDate() = vars.today;
    vars.settlement =
        vars.calendar.advance(vars.today,vars.settlementDays,Days);
    vars.termStructure.linkTo(flatRate(vars.settlement,0.05,Actual365Fixed()));
    boost::shared_ptr<VanillaSwap> swap = vars.makeSwap(10, 0.06, 0.001);
    #ifndef QL_USE_INDEXED_COUPON
    Real cachedNPV   = -5.872863313209;
    #else
    Real cachedNPV   = -5.872342992212;
    #endif
    if (std::fabs(swap->NPV()-cachedNPV) > 1.0e-11)
        BOOST_ERROR("failed to reproduce cached swap value:\n"
                    << QL_FIXED << std::setprecision(12)
                    << "    calculated: " << swap->NPV() << "\n"
                    << "    expected:   " << cachedNPV);
}
void SwapTest::testFairRate () [static]
Definition at line 105 of file swap.cpp.
References LENGTH, anonymous_namespace{swaption.cpp}::lengths, QuantLib::io::rate(), and QuantLib::swap().
Referenced by suite().
{
    BOOST_MESSAGE("Testing vanilla-swap calculation of fair fixed rate...");
    CommonVars vars;
    Integer lengths[] = { 1, 2, 5, 10, 20 };
    Spread spreads[] = { -0.001, -0.01, 0.0, 0.01, 0.001 };
    for (Size i=0; i<LENGTH(lengths); i++) {
        for (Size j=0; j<LENGTH(spreads); j++) {
            boost::shared_ptr<VanillaSwap> swap =
                vars.makeSwap(lengths[i],0.0,spreads[j]);
            swap = vars.makeSwap(lengths[i],swap->fairRate(),spreads[j]);
            if (std::fabs(swap->NPV()) > 1.0e-10) {
                BOOST_ERROR("recalculating with implied rate:\n"
                            << std::setprecision(2)
                            << "    length: " << lengths[i] << " years\n"
                            << "    floating spread: "
                            << io::rate(spreads[j]) << "\n"
                            << "    swap value: " << swap->NPV());
            }
        }
    }
}
void SwapTest::testFairSpread () [static]
Definition at line 132 of file swap.cpp.
References LENGTH, anonymous_namespace{swaption.cpp}::lengths, QuantLib::io::rate(), and QuantLib::swap().
Referenced by suite().
{
    BOOST_MESSAGE("Testing vanilla-swap calculation of "
                  "fair floating spread...");
    CommonVars vars;
    Integer lengths[] = { 1, 2, 5, 10, 20 };
    Rate rates[] = { 0.04, 0.05, 0.06, 0.07 };
    for (Size i=0; i<LENGTH(lengths); i++) {
        for (Size j=0; j<LENGTH(rates); j++) {
            boost::shared_ptr<VanillaSwap> swap =
                vars.makeSwap(lengths[i],rates[j],0.0);
            swap = vars.makeSwap(lengths[i],rates[j],swap->fairSpread());
            if (std::fabs(swap->NPV()) > 1.0e-10) {
                BOOST_ERROR("recalculating with implied spread:\n"
                            << std::setprecision(2)
                            << "    length: " << lengths[i] << " years\n"
                            << "    fixed rate: " << io::rate(rates[j]) << "\n"
                            << "    swap value: " << swap->NPV());
            }
        }
    }
}
void SwapTest::testInArrears () [static]
Definition at line 233 of file swap.cpp.
References QuantLib::Annual, anonymous_namespace{marketmodel.cpp}::calendar, anonymous_namespace{marketmodel.cpp}::dayCounter, QuantLib::flatRate(), QuantLib::Following, QuantLib::DateGeneration::Forward, QuantLib::IborLeg::inArrears(), QuantLib::Instrument::NPV(), QuantLib::setCouponPricer(), QuantLib::Instrument::setPricingEngine(), QuantLib::swap(), anonymous_namespace{gaussianquadratures.cpp}::tolerance, QuantLib::FixedRateLeg::withCouponRates(), QuantLib::IborLeg::withFixingDays(), QuantLib::IborLeg::withGearings(), QuantLib::IborLeg::withNotionals(), QuantLib::FixedRateLeg::withNotionals(), QuantLib::IborLeg::withPaymentDayCounter(), QuantLib::IborLeg::withSpreads(), and QuantLib::Years.
Referenced by suite().
{
    BOOST_MESSAGE("Testing in-arrears swap calculation...");
    CommonVars vars;
    /* See Hull, 4th ed., page 550
       Note: the calculation in the book is wrong (work out the
       adjustment and you'll get 0.05 + 0.000115 T1)
    */
    Date maturity = vars.today + 5*Years;
    Calendar calendar = NullCalendar();
    Schedule schedule(vars.today, maturity,Period(Annual),calendar,
                      Following,Following,
                      DateGeneration::Forward,false);
    DayCounter dayCounter = SimpleDayCounter();
    std::vector<Real> nominals(1, 100000000.0);
    boost::shared_ptr<IborIndex> index(new IborIndex("dummy", 1*Years, 0,
                                             EURCurrency(), calendar,
                                             Following, false, dayCounter,
                                             vars.termStructure));
    Rate oneYear = 0.05;
    Rate r = std::log(1.0+oneYear);
    vars.termStructure.linkTo(flatRate(vars.today,r,dayCounter));
    std::vector<Rate> coupons(1, oneYear);
    Leg fixedLeg = FixedRateLeg(schedule)
        .withNotionals(nominals)
        .withCouponRates(coupons, dayCounter);
    std::vector<Real> gearings;
    std::vector<Rate> spreads;
    Natural fixingDays = 0;
    Volatility capletVolatility = 0.22;
    Handle<OptionletVolatilityStructure> vol(
        boost::shared_ptr<OptionletVolatilityStructure>(new
            ConstantOptionletVolatility(vars.today, NullCalendar(), Following,
                                        capletVolatility, dayCounter)));
    boost::shared_ptr<IborCouponPricer> pricer(new
        BlackIborCouponPricer(vol));
    Leg floatingLeg = IborLeg(schedule, index)
        .withNotionals(nominals)
        .withPaymentDayCounter(dayCounter)
        .withFixingDays(fixingDays)
        .withGearings(gearings)
        .withSpreads(spreads)
        .inArrears();
    setCouponPricer(floatingLeg, pricer);
    Swap swap(floatingLeg,fixedLeg);
    swap.setPricingEngine(boost::shared_ptr<PricingEngine>(
                              new DiscountingSwapEngine(vars.termStructure)));
    Decimal storedValue = -144813.0;
    Real tolerance = 1.0;
    if (std::fabs(swap.NPV()-storedValue) > tolerance)
        BOOST_ERROR("Wrong NPV calculation:\n"
                    << "    expected:   " << storedValue << "\n"
                    << "    calculated: " << swap.NPV());
}
void SwapTest::testRateDependency () [static]
Definition at line 159 of file swap.cpp.
References LENGTH, anonymous_namespace{swaption.cpp}::lengths, QuantLib::io::rate(), and QuantLib::swap().
Referenced by suite().
{
    BOOST_MESSAGE("Testing vanilla-swap dependency on fixed rate...");
    CommonVars vars;
    Integer lengths[] = { 1, 2, 5, 10, 20 };
    Spread spreads[] = { -0.001, -0.01, 0.0, 0.01, 0.001 };
    Rate rates[] = { 0.03, 0.04, 0.05, 0.06, 0.07 };
    for (Size i=0; i<LENGTH(lengths); i++) {
        for (Size j=0; j<LENGTH(spreads); j++) {
            // store the results for different rates...
            std::vector<Real> swap_values;
            for (Size k=0; k<LENGTH(rates); k++) {
                boost::shared_ptr<VanillaSwap> swap =
                    vars.makeSwap(lengths[i],rates[k],spreads[j]);
                swap_values.push_back(swap->NPV());
            }
            // and check that they go the right way
            std::vector<Real>::iterator it =
                std::adjacent_find(swap_values.begin(),swap_values.end(),
                                   std::less<Real>());
            if (it != swap_values.end()) {
                Size n = it - swap_values.begin();
                BOOST_ERROR(
                    "NPV is increasing with the fixed rate in a swap: \n"
                    << "    length: " << lengths[i] << " years\n"
                    << "    value:  " << swap_values[n]
                    << " paying fixed rate: " << io::rate(rates[n]) << "\n"
                    << "    value:  " << swap_values[n+1]
                    << " paying fixed rate: " << io::rate(rates[n+1]));
            }
        }
    }
}
void SwapTest::testSpreadDependency () [static]
Definition at line 196 of file swap.cpp.
References LENGTH, anonymous_namespace{swaption.cpp}::lengths, QuantLib::io::rate(), and QuantLib::swap().
Referenced by suite().
{
    BOOST_MESSAGE("Testing vanilla-swap dependency on floating spread...");
    CommonVars vars;
    Integer lengths[] = { 1, 2, 5, 10, 20 };
    Rate rates[] = { 0.04, 0.05, 0.06, 0.07 };
    Spread spreads[] = { -0.01, -0.002, -0.001, 0.0, 0.001, 0.002, 0.01 };
    for (Size i=0; i<LENGTH(lengths); i++) {
        for (Size j=0; j<LENGTH(rates); j++) {
            // store the results for different spreads...
            std::vector<Real> swap_values;
            for (Size k=0; k<LENGTH(spreads); k++) {
                boost::shared_ptr<VanillaSwap> swap =
                    vars.makeSwap(lengths[i],rates[j],spreads[k]);
                swap_values.push_back(swap->NPV());
            }
            // and check that they go the right way
            std::vector<Real>::iterator it =
                std::adjacent_find(swap_values.begin(),swap_values.end(),
                                   std::greater<Real>());
            if (it != swap_values.end()) {
                Size n = it - swap_values.begin();
                BOOST_ERROR(
                    "NPV is decreasing with the floating spread in a swap: \n"
                    << "    length: " << lengths[i] << " years\n"
                    << "    value:  " << swap_values[n]
                    << " receiving spread: " << io::rate(spreads[n]) << "\n"
                    << "    value:  " << swap_values[n+1]
                    << " receiving spread: " << io::rate(spreads[n+1]));
            }
        }
    }
}
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/swap.hpp
/home/deriversatile/QuantLib/QuantLibQt/test-suite/swap.cpp