QuantLib: QuantLib::InterpolatedZeroCurve< Interpolator > Class Template Reference
QuantLib::InterpolatedZeroCurve< Interpolator > Class Template Reference
YieldTermStructure based on interpolation of zero rates.
#include <zerocurve.hpp>
Public Member Functions
InterpolatedZeroCurve (const std::vector< Date > &dates, const std::vector< Rate > &yields, const DayCounter &dayCounter, const Calendar &calendar=Calendar(), const std::vector< Handle< Quote > > &jumps=std::vector< Handle< Quote > >(), const std::vector< Date > &jumpDates=std::vector< Date >(), const Interpolator &interpolator=Interpolator())
InterpolatedZeroCurve (const std::vector< Date > &dates, const std::vector< Rate > &yields, const DayCounter &dayCounter, const Calendar &calendar, const Interpolator &interpolator)
InterpolatedZeroCurve (const std::vector< Date > &dates, const std::vector< Rate > &yields, const DayCounter &dayCounter, const Interpolator &interpolator)
TermStructure interface
Date maxDate () const
the latest date for which the curve can return values
other inspectors
const std::vector< Time > & times () const
const std::vector< Date > & dates () const
const std::vector< Real > & data () const
const std::vector< Rate > & zeroRates () const
std::vector< std::pair< Date,
Real > > nodes () const
Protected Member Functions
InterpolatedZeroCurve (const DayCounter &, const std::vector< Handle< Quote > > &jumps=std::vector< Handle< Quote > >(), const std::vector< Date > &jumpDates=std::vector< Date >(), const Interpolator &interpolator=Interpolator())
InterpolatedZeroCurve (const Date &referenceDate, const DayCounter &, const std::vector< Handle< Quote > > &jumps=std::vector< Handle< Quote > >(), const std::vector< Date > &jumpDates=std::vector< Date >(), const Interpolator &interpolator=Interpolator())
InterpolatedZeroCurve (Natural settlementDays, const Calendar &, const DayCounter &, const std::vector< Handle< Quote > > &jumps=std::vector< Handle< Quote > >(), const std::vector< Date > &jumpDates=std::vector< Date >(), const Interpolator &interpolator=Interpolator())
ZeroYieldStructure implementation
Rate zeroYieldImpl (Time t) const
zero-yield calculation
Protected Attributes
std::vector< Date > dates_
Private Member Functions
void initialize ()
Detailed Description
template<class Interpolator>
class QuantLib::InterpolatedZeroCurve< Interpolator >
YieldTermStructure based on interpolation of zero rates.
Definition at line 40 of file zerocurve.hpp.
Constructor & Destructor Documentation
template<class Interpolator > QuantLib::InterpolatedZeroCurve< Interpolator >::InterpolatedZeroCurve (const std::vector< Date > & dates, const std::vector< Rate > & yields, const DayCounter & dayCounter, const Calendar & calendar = Calendar(), const std::vector< Handle< Quote > > & jumps = std::vector< Handle< Quote > >(), const std::vector< Date > & jumpDates = std::vector< Date >(), const Interpolator & interpolator = Interpolator())
template<class Interpolator > QuantLib::InterpolatedZeroCurve< Interpolator >::InterpolatedZeroCurve (const std::vector< Date > & dates, const std::vector< Rate > & yields, const DayCounter & dayCounter, const Calendar & calendar, const Interpolator & interpolator)
template<class Interpolator > QuantLib::InterpolatedZeroCurve< Interpolator >::InterpolatedZeroCurve (const std::vector< Date > & dates, const std::vector< Rate > & yields, const DayCounter & dayCounter, const Interpolator & interpolator)
template<class Interpolator > QuantLib::InterpolatedZeroCurve< Interpolator >::InterpolatedZeroCurve (const DayCounter & , const std::vector< Handle< Quote > > & jumps = std::vector< Handle< Quote > >(), const std::vector< Date > & jumpDates = std::vector< Date >(), const Interpolator & interpolator = Interpolator()) [protected]
template<class Interpolator > QuantLib::InterpolatedZeroCurve< Interpolator >::InterpolatedZeroCurve (const Date & referenceDate, const DayCounter & , const std::vector< Handle< Quote > > & jumps = std::vector< Handle< Quote > >(), const std::vector< Date > & jumpDates = std::vector< Date >(), const Interpolator & interpolator = Interpolator()) [protected]
template<class Interpolator > QuantLib::InterpolatedZeroCurve< Interpolator >::InterpolatedZeroCurve (Natural settlementDays, const Calendar & , const DayCounter & , const std::vector< Handle< Quote > > & jumps = std::vector< Handle< Quote > >(), const std::vector< Date > & jumpDates = std::vector< Date >(), const Interpolator & interpolator = Interpolator()) [protected]
Member Function Documentation
template<class T > const std::vector< Real > & QuantLib::InterpolatedZeroCurve< T >::data () const [inline]
Definition at line 128 of file zerocurve.hpp.
{
        return this->data_;
    }
template<class T > const std::vector< Date > & QuantLib::InterpolatedZeroCurve< T >::dates () const [inline]
Definition at line 122 of file zerocurve.hpp.
{
        return dates_;
    }
template<class T > void QuantLib::InterpolatedZeroCurve< T >::initialize () [private]
Definition at line 239 of file zerocurve.hpp.
References QuantLib::close(), anonymous_namespace{marketmodel.cpp}::dayCounter, QL_REQUIRE, QuantLib::io::rate(), and QuantLib::DayCounter::yearFraction().
    {
        QL_REQUIRE(dates_.size() >= T::requiredPoints,
                   "not enough input dates given");
        QL_REQUIRE(this->data_.size() == dates_.size(),
                   "dates/data count mismatch");
        this->times_.resize(dates_.size());
        this->times_[0] = 0.0;
        for (Size i=1; i<dates_.size(); ++i) {
            QL_REQUIRE(dates_[i] > dates_[i-1],
                       "invalid date (" << dates_[i] << ", vs "
                       << dates_[i-1] << ")");
            this->times_[i] = dayCounter().yearFraction(dates_[0], dates_[i]);
            QL_REQUIRE(!close(this->times_[i],this->times_[i-1]),
                       "two dates correspond to the same time "
                       "under this curve's day count convention");
            #if !defined(QL_NEGATIVE_RATES)
            QL_REQUIRE(this->data_[i] > 0.0, "non-positive yield");
            // positive yields are not enough to ensure non-negative fwd rates
            // so here's a stronger requirement
            QL_REQUIRE(this->data_[i]   * this->times_[i] -
                       this->data_[i-1] * this->times_[i-1] >= 0.0,
                       "negative forward rate implied by the zero yield " <<
                       io::rate(this->data_[i]) << " at " << dates_[i] <<
                       " (t=" << this->times_[i] << ") after the zero yield " <<
                       io::rate(this->data_[i-1]) << " at " << dates_[i-1] <<
                       " (t=" << this->times_[i-1] << ")");
            #endif
        }
        this->interpolation_ =
            this->interpolator_.interpolate(this->times_.begin(),
                                            this->times_.end(),
                                            this->data_.begin());
        this->interpolation_.update();
    }
template<class T > Date QuantLib::InterpolatedZeroCurve< T >::maxDate () const [inline, virtual]
the latest date for which the curve can return values
Implements QuantLib::TermStructure.
Definition at line 112 of file zerocurve.hpp.
{
        return dates_.back();
    }
template<class T > std::vector< std::pair< Date, Real > > QuantLib::InterpolatedZeroCurve< T >::nodes () const [inline]
Definition at line 140 of file zerocurve.hpp.
{
        std::vector<std::pair<Date, Real> > results(dates_.size());
        for (Size i=0; i<dates_.size(); ++i)
            results[i] = std::make_pair(dates_[i], this->data_[i]);
        return results;
    }
template<class T > const std::vector< Time > & QuantLib::InterpolatedZeroCurve< T >::times () const [inline]
Definition at line 117 of file zerocurve.hpp.
{
        return this->times_;
    }
template<class T > const std::vector< Rate > & QuantLib::InterpolatedZeroCurve< T >::zeroRates () const [inline]
Definition at line 134 of file zerocurve.hpp.
{
        return this->data_;
    }
template<class T > Rate QuantLib::InterpolatedZeroCurve< T >::zeroYieldImpl (Time) const [protected, virtual]
zero-yield calculation
Implements QuantLib::ZeroYieldStructure.
Definition at line 152 of file zerocurve.hpp.
References anonymous_namespace{quantlibbenchmark.cpp}::t.
{
        if (t <= this->times_.back())
            return this->interpolation_(t, true);
        // flat fwd extrapolation
        Time tMax = this->times_.back();
        Rate zMax = this->data_.back();
        Rate instFwdMax = zMax + tMax * this->interpolation_.derivative(tMax);
        return (zMax * tMax + instFwdMax * (t-tMax)) / t;
    }
Member Data Documentation
template<class Interpolator > std::vector<Date> QuantLib::InterpolatedZeroCurve< Interpolator >::dates_ [mutable, protected]
Definition at line 99 of file zerocurve.hpp.
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/yield/zerocurve.hpp