QuantLib: QuantLib::OneStepCoinitialSwaps Class Reference
QuantLib::OneStepCoinitialSwaps Class Reference
#include <onestepcoinitialswaps.hpp>
Public Member Functions
OneStepCoinitialSwaps (const std::vector< Time > &rateTimes, const std::vector< Real > &fixedAccruals, const std::vector< Real > &floatingAccruals, const std::vector< Time > &paymentTimes, double fixedRate)
MarketModelMultiProduct interface
std::vector< Time > possibleCashFlowTimes () const
Size numberOfProducts () const
Size maxNumberOfCashFlowsPerProductPerStep () const
void reset ()
during simulation put product at start of path
bool nextTimeStep (const CurveState &currentState, std::vector< Size > &numberCashFlowsThisStep, std::vector< std::vector< CashFlow > > &cashFlowsGenerated)
return value indicates whether path is finished, TRUE means done
std::auto_ptr
< MarketModelMultiProduct > clone () const
returns a newly-allocated copy of itself
Private Attributes
std::vector< Real > fixedAccruals_
std::vector< Real > floatingAccruals_
std::vector< Time > paymentTimes_
double fixedRate_
Size lastIndex_
Detailed Description
Definition at line 27 of file onestepcoinitialswaps.hpp.
Constructor & Destructor Documentation
QuantLib::OneStepCoinitialSwaps::OneStepCoinitialSwaps (const std::vector< Time > & rateTimes, const std::vector< Real > & fixedAccruals, const std::vector< Real > & floatingAccruals, const std::vector< Time > & paymentTimes, double fixedRate)
Definition at line 26 of file onestepcoinitialswaps.cpp.
References QuantLib::checkIncreasingTimes(), and lastIndex_.
Referenced by clone().
    : MultiProductOneStep(rateTimes),
      fixedAccruals_(fixedAccruals), floatingAccruals_(floatingAccruals),
      paymentTimes_(paymentTimes), fixedRate_(fixedRate) {
        checkIncreasingTimes(paymentTimes);
        lastIndex_ = rateTimes.size()-1;
    }
Member Function Documentation
std::auto_ptr< MarketModelMultiProduct > QuantLib::OneStepCoinitialSwaps::clone () const [virtual]
returns a newly-allocated copy of itself
Implements QuantLib::MarketModelMultiProduct.
Definition at line 67 of file onestepcoinitialswaps.cpp.
References OneStepCoinitialSwaps().
{
        return std::auto_ptr<MarketModelMultiProduct>(
                                            new OneStepCoinitialSwaps(*this));
    }
Size QuantLib::OneStepCoinitialSwaps::maxNumberOfCashFlowsPerProductPerStep () const [inline, virtual]
Implements QuantLib::MarketModelMultiProduct.
Definition at line 66 of file onestepcoinitialswaps.hpp.
References lastIndex_.
{
        return 2*lastIndex_;
    }
bool QuantLib::OneStepCoinitialSwaps::nextTimeStep (const CurveState & currentState, std::vector< Size > & numberCashFlowsThisStep, std::vector< std::vector< CashFlow > > & cashFlowsGenerated) [virtual]
return value indicates whether path is finished, TRUE means done
Implements QuantLib::MarketModelMultiProduct.
Definition at line 41 of file onestepcoinitialswaps.cpp.
References fixedAccruals_, fixedRate_, floatingAccruals_, QuantLib::CurveState::forwardRate(), and lastIndex_.
{
        std::fill(numberCashFlowsThisStep.begin(),
                  numberCashFlowsThisStep.end(),0);
        for (Size indexOfTime=0;indexOfTime<lastIndex_;indexOfTime++) {
            Rate liborRate = currentState.forwardRate(indexOfTime);
            for (Size i=indexOfTime;i<lastIndex_;i++) {
                genCashFlows[i][(indexOfTime)*2].timeIndex = indexOfTime;
                genCashFlows[i][(indexOfTime)*2].amount =
                    -fixedRate_*fixedAccruals_[indexOfTime];
                genCashFlows[i][(indexOfTime)*2+1].timeIndex = indexOfTime;
                genCashFlows[i][(indexOfTime)*2+1].amount =
                    liborRate*floatingAccruals_[indexOfTime];
                numberCashFlowsThisStep[i] += 2;
            }
        }
        return true ;
    }
Size QuantLib::OneStepCoinitialSwaps::numberOfProducts () const [inline, virtual]
Implements QuantLib::MarketModelMultiProduct.
Definition at line 61 of file onestepcoinitialswaps.hpp.
References lastIndex_.
{
        return lastIndex_;
    }
std::vector< Time > QuantLib::OneStepCoinitialSwaps::possibleCashFlowTimes () const [inline, virtual]
Implements QuantLib::MarketModelMultiProduct.
Definition at line 57 of file onestepcoinitialswaps.hpp.
References paymentTimes_.
{
        return paymentTimes_;
    }
void QuantLib::OneStepCoinitialSwaps::reset () [inline, virtual]
during simulation put product at start of path
Implements QuantLib::MarketModelMultiProduct.
Definition at line 70 of file onestepcoinitialswaps.hpp.
{
        // nothing to do
    }
Member Data Documentation
std::vector<Real> QuantLib::OneStepCoinitialSwaps::fixedAccruals_ [private]
Definition at line 47 of file onestepcoinitialswaps.hpp.
Referenced by nextTimeStep().
double QuantLib::OneStepCoinitialSwaps::fixedRate_ [private]
Definition at line 49 of file onestepcoinitialswaps.hpp.
Referenced by nextTimeStep().
std::vector<Real> QuantLib::OneStepCoinitialSwaps::floatingAccruals_ [private]
Definition at line 47 of file onestepcoinitialswaps.hpp.
Referenced by nextTimeStep().
Size QuantLib::OneStepCoinitialSwaps::lastIndex_ [private]
Definition at line 50 of file onestepcoinitialswaps.hpp.
Referenced by maxNumberOfCashFlowsPerProductPerStep(), nextTimeStep(), numberOfProducts(), and OneStepCoinitialSwaps().
std::vector<Time> QuantLib::OneStepCoinitialSwaps::paymentTimes_ [private]
Definition at line 48 of file onestepcoinitialswaps.hpp.
Referenced by possibleCashFlowTimes().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/products/onestep/onestepcoinitialswaps.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/products/onestep/onestepcoinitialswaps.cpp