QuantLib: QuantLib::InverseCumulativeRng< RNG, IC > Class Template Reference
QuantLib::InverseCumulativeRng< RNG, IC > Class Template Reference
Inverse cumulative random number generator.
#include <inversecumulativerng.hpp>
Public Types
typedef Sample< Real > sample_type
typedef RNG urng_type
Public Member Functions
InverseCumulativeRng (const RNG &uniformGenerator)
sample_type next () const
returns a sample from a Gaussian distribution
Private Attributes
RNG uniformGenerator_
IC ICND_
Detailed Description
template<class RNG, class IC>
class QuantLib::InverseCumulativeRng< RNG, IC >
Inverse cumulative random number generator.
It uses a uniform deviate in (0, 1) as the source of cumulative distribution values. Then an inverse cumulative distribution is used to calculate the distribution deviate.
The uniform deviate is supplied by RNG.
Class RNG must implement the following interface:
            RNG::sample_type RNG::next() const;
The inverse cumulative distribution is supplied by IC.
Class IC must implement the following interface:
            IC::IC();
            Real IC::operator() const;
Definition at line 54 of file inversecumulativerng.hpp.
Member Typedef Documentation
template<class RNG, class IC> typedef Sample<Real> QuantLib::InverseCumulativeRng< RNG, IC >::sample_type
Definition at line 56 of file inversecumulativerng.hpp.
template<class RNG, class IC> typedef RNG QuantLib::InverseCumulativeRng< RNG, IC >::urng_type
Definition at line 57 of file inversecumulativerng.hpp.
Constructor & Destructor Documentation
template<class RNG, class IC > QuantLib::InverseCumulativeRng< RNG, IC >::InverseCumulativeRng (const RNG & uniformGenerator) [explicit]
Definition at line 67 of file inversecumulativerng.hpp.
    : uniformGenerator_(ug) {}
Member Function Documentation
template<class RNG , class IC > InverseCumulativeRng< RNG, IC >::sample_type QuantLib::InverseCumulativeRng< RNG, IC >::next () const [inline]
returns a sample from a Gaussian distribution
Definition at line 72 of file inversecumulativerng.hpp.
Referenced by SwingOptionTest::testExtendedOrnsteinUhlenbeckProcess(), SwingOptionTest::testFdmExponentialJump1dMesher(), LinearLeastSquaresRegressionTest::testMultiDimRegression(), and LinearLeastSquaresRegressionTest::testRegression().
{
        typename RNG::sample_type sample = uniformGenerator_.next();
        return sample_type(ICND_(sample.value),sample.weight);
    }
Member Data Documentation
template<class RNG, class IC> IC QuantLib::InverseCumulativeRng< RNG, IC >::ICND_ [private]
Definition at line 63 of file inversecumulativerng.hpp.
template<class RNG, class IC> RNG QuantLib::InverseCumulativeRng< RNG, IC >::uniformGenerator_ [private]
Definition at line 62 of file inversecumulativerng.hpp.
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/randomnumbers/inversecumulativerng.hpp