QuantLib: QuantLib::MCHullWhiteCapFloorEngine< RNG, S > Class Template Reference
QuantLib::MCHullWhiteCapFloorEngine< RNG, S > Class Template Reference
Monte Carlo Hull-White engine for cap/floors.
#include <mchullwhiteengine.hpp>
Public Types
typedef
simulation::path_generator_type path_generator_type
typedef
simulation::path_pricer_type path_pricer_type
typedef simulation::stats_type stats_type
Public Member Functions
MCHullWhiteCapFloorEngine (const boost::shared_ptr< HullWhite > &model, bool brownianBridge, bool antitheticVariate, Size requiredSamples, Real requiredTolerance, Size maxSamples, BigNatural seed)
void calculate () const
Protected Member Functions
boost::shared_ptr
< path_pricer_type > pathPricer () const
TimeGrid timeGrid () const
boost::shared_ptr
< path_generator_type > pathGenerator () const
Private Types
typedef McSimulation
< SingleVariate, RNG, S > simulation
Private Attributes
boost::shared_ptr< HullWhite > model_
Size requiredSamples_
Size maxSamples_
Real requiredTolerance_
bool brownianBridge_
BigNatural seed_
Detailed Description
template<class RNG = PseudoRandom, class S = Statistics>
class QuantLib::MCHullWhiteCapFloorEngine< RNG, S >
Monte Carlo Hull-White engine for cap/floors.
Definition at line 57 of file mchullwhiteengine.hpp.
Member Typedef Documentation
template<class RNG = PseudoRandom, class S = Statistics> typedef simulation::path_generator_type QuantLib::MCHullWhiteCapFloorEngine< RNG, S >::path_generator_type
Reimplemented from QuantLib::McSimulation< SingleVariate, RNG, S >.
Definition at line 68 of file mchullwhiteengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> typedef simulation::path_pricer_type QuantLib::MCHullWhiteCapFloorEngine< RNG, S >::path_pricer_type
Reimplemented from QuantLib::McSimulation< SingleVariate, RNG, S >.
Definition at line 69 of file mchullwhiteengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> typedef McSimulation<SingleVariate,RNG,S> QuantLib::MCHullWhiteCapFloorEngine< RNG, S >::simulation [private]
Definition at line 61 of file mchullwhiteengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> typedef simulation::stats_type QuantLib::MCHullWhiteCapFloorEngine< RNG, S >::stats_type
Reimplemented from QuantLib::McSimulation< SingleVariate, RNG, S >.
Definition at line 70 of file mchullwhiteengine.hpp.
Constructor & Destructor Documentation
template<class RNG = PseudoRandom, class S = Statistics> QuantLib::MCHullWhiteCapFloorEngine< RNG, S >::MCHullWhiteCapFloorEngine (const boost::shared_ptr< HullWhite > & model, bool brownianBridge, bool antitheticVariate, Size requiredSamples, Real requiredTolerance, Size maxSamples, BigNatural seed) [inline]
Definition at line 72 of file mchullwhiteengine.hpp.
References QuantLib::MCHullWhiteCapFloorEngine< RNG, S >::model_, and QuantLib::Observer::registerWith().
        : McSimulation<SingleVariate,RNG,S>(antitheticVariate, false),
          model_(model), requiredSamples_(requiredSamples),
          maxSamples_(maxSamples), requiredTolerance_(requiredTolerance),
          brownianBridge_(brownianBridge), seed_(seed) {
            registerWith(model_);
        }
Member Function Documentation
template<class RNG = PseudoRandom, class S = Statistics> void QuantLib::MCHullWhiteCapFloorEngine< RNG, S >::calculate () const [inline, virtual]
Implements QuantLib::PricingEngine.
Definition at line 86 of file mchullwhiteengine.hpp.
References QuantLib::McSimulation< SingleVariate, RNG, S >::calculate(), QuantLib::MCHullWhiteCapFloorEngine< RNG, S >::maxSamples_, QuantLib::McSimulation< SingleVariate, RNG, S >::mcModel_, QuantLib::MCHullWhiteCapFloorEngine< RNG, S >::requiredSamples_, QuantLib::MCHullWhiteCapFloorEngine< RNG, S >::requiredTolerance_, and QuantLib::GenericEngine< CapFloor::arguments, CapFloor::results >::results_.
{
            simulation::calculate(requiredTolerance_,
                                  requiredSamples_,
                                  maxSamples_);
            results_.value = this->mcModel_->sampleAccumulator().mean();
            if (RNG::allowsErrorEstimate)
                results_.errorEstimate =
                    this->mcModel_->sampleAccumulator().errorEstimate();
        }
template<class RNG = PseudoRandom, class S = Statistics> boost::shared_ptr<path_generator_type> QuantLib::MCHullWhiteCapFloorEngine< RNG, S >::pathGenerator () const [inline, protected, virtual]
Implements QuantLib::McSimulation< SingleVariate, RNG, S >.
Definition at line 128 of file mchullwhiteengine.hpp.
References anonymous_namespace{marketmodel.cpp}::a, QuantLib::GenericEngine< CapFloor::arguments, CapFloor::results >::arguments_, QuantLib::MCHullWhiteCapFloorEngine< RNG, S >::brownianBridge_, anonymous_namespace{marketmodel.cpp}::dayCounter, QuantLib::CapFloor::arguments::endDates, QuantLib::MCHullWhiteCapFloorEngine< RNG, S >::model_, QuantLib::MCHullWhiteCapFloorEngine< RNG, S >::seed_, anonymous_namespace{distributions.cpp}::sigma, QuantLib::TimeGrid::size(), QuantLib::MCHullWhiteCapFloorEngine< RNG, S >::timeGrid(), and QuantLib::DayCounter::yearFraction().
{
            Handle<YieldTermStructure> curve = model_->termStructure();
            Date referenceDate = curve->referenceDate();
            DayCounter dayCounter = curve->dayCounter();
            Time forwardMeasureTime =
                dayCounter.yearFraction(referenceDate,
                                        arguments_.endDates.back());
            Array parameters = model_->params();
            Real a = parameters[0], sigma = parameters[1];
            boost::shared_ptr<HullWhiteForwardProcess> process(
                                new HullWhiteForwardProcess(curve, a, sigma));
            process->setForwardMeasureTime(forwardMeasureTime);
            TimeGrid grid = this->timeGrid();
            typename RNG::rsg_type generator =
                RNG::make_sequence_generator(grid.size()-1,seed_);
            return boost::shared_ptr<path_generator_type>(
                             new path_generator_type(process, grid, generator,
                                                     brownianBridge_));
        }
template<class RNG = PseudoRandom, class S = Statistics> boost::shared_ptr<path_pricer_type> QuantLib::MCHullWhiteCapFloorEngine< RNG, S >::pathPricer () const [inline, protected, virtual]
Implements QuantLib::McSimulation< SingleVariate, RNG, S >.
Definition at line 97 of file mchullwhiteengine.hpp.
References QuantLib::GenericEngine< CapFloor::arguments, CapFloor::results >::arguments_, anonymous_namespace{marketmodel.cpp}::dayCounter, QuantLib::CapFloor::arguments::endDates, QuantLib::MCHullWhiteCapFloorEngine< RNG, S >::model_, and QuantLib::DayCounter::yearFraction().
{
            Date referenceDate = model_->termStructure()->referenceDate();
            DayCounter dayCounter = model_->termStructure()->dayCounter();
            Time forwardMeasureTime =
                dayCounter.yearFraction(referenceDate,
                                        arguments_.endDates.back());
            return boost::shared_ptr<path_pricer_type>(
                     new detail::HullWhiteCapFloorPricer(arguments_, model_,
                                                         forwardMeasureTime));
        }
template<class RNG = PseudoRandom, class S = Statistics> TimeGrid QuantLib::MCHullWhiteCapFloorEngine< RNG, S >::timeGrid () const [inline, protected, virtual]
Implements QuantLib::McSimulation< SingleVariate, RNG, S >.
Definition at line 108 of file mchullwhiteengine.hpp.
References QuantLib::GenericEngine< CapFloor::arguments, CapFloor::results >::arguments_, anonymous_namespace{marketmodel.cpp}::dayCounter, QuantLib::CapFloor::arguments::endDates, QuantLib::CapFloor::arguments::fixingDates, QuantLib::MCHullWhiteCapFloorEngine< RNG, S >::model_, and QuantLib::DayCounter::yearFraction().
Referenced by QuantLib::MCHullWhiteCapFloorEngine< RNG, S >::pathGenerator().
{
            Date referenceDate = model_->termStructure()->referenceDate();
            DayCounter dayCounter = model_->termStructure()->dayCounter();
            // only add future fixing times...
            std::vector<Time> times;
            for (Size i=0; i<arguments_.fixingDates.size(); i++) {
                if (arguments_.fixingDates[i] > referenceDate)
                    times.push_back(
                          dayCounter.yearFraction(referenceDate,
                                                  arguments_.fixingDates[i]));
            }
            // ...and maturity.
            times.push_back(
                        dayCounter.yearFraction(referenceDate,
                                                arguments_.endDates.back()));
            return TimeGrid(times.begin(), times.end());
        }
Member Data Documentation
template<class RNG = PseudoRandom, class S = Statistics> bool QuantLib::MCHullWhiteCapFloorEngine< RNG, S >::brownianBridge_ [private]
Definition at line 65 of file mchullwhiteengine.hpp.
Referenced by QuantLib::MCHullWhiteCapFloorEngine< RNG, S >::pathGenerator().
template<class RNG = PseudoRandom, class S = Statistics> Size QuantLib::MCHullWhiteCapFloorEngine< RNG, S >::maxSamples_ [private]
Definition at line 63 of file mchullwhiteengine.hpp.
Referenced by QuantLib::MCHullWhiteCapFloorEngine< RNG, S >::calculate().
template<class RNG = PseudoRandom, class S = Statistics> boost::shared_ptr<HullWhite> QuantLib::MCHullWhiteCapFloorEngine< RNG, S >::model_ [private]
Definition at line 62 of file mchullwhiteengine.hpp.
Referenced by QuantLib::MCHullWhiteCapFloorEngine< RNG, S >::MCHullWhiteCapFloorEngine(), QuantLib::MCHullWhiteCapFloorEngine< RNG, S >::pathGenerator(), QuantLib::MCHullWhiteCapFloorEngine< RNG, S >::pathPricer(), and QuantLib::MCHullWhiteCapFloorEngine< RNG, S >::timeGrid().
template<class RNG = PseudoRandom, class S = Statistics> Size QuantLib::MCHullWhiteCapFloorEngine< RNG, S >::requiredSamples_ [private]
Definition at line 63 of file mchullwhiteengine.hpp.
Referenced by QuantLib::MCHullWhiteCapFloorEngine< RNG, S >::calculate().
template<class RNG = PseudoRandom, class S = Statistics> Real QuantLib::MCHullWhiteCapFloorEngine< RNG, S >::requiredTolerance_ [private]
Definition at line 64 of file mchullwhiteengine.hpp.
Referenced by QuantLib::MCHullWhiteCapFloorEngine< RNG, S >::calculate().
template<class RNG = PseudoRandom, class S = Statistics> BigNatural QuantLib::MCHullWhiteCapFloorEngine< RNG, S >::seed_ [private]
Definition at line 66 of file mchullwhiteengine.hpp.
Referenced by QuantLib::MCHullWhiteCapFloorEngine< RNG, S >::pathGenerator().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/capfloor/mchullwhiteengine.hpp