QuantLib: QuantLib::MarketModelExerciseValue Class Reference
QuantLib::MarketModelExerciseValue Class Reference
#include <exercisevalue.hpp>
Public Member Functions
virtual ~MarketModelExerciseValue ()
virtual Size numberOfExercises () const =0
virtual const
EvolutionDescription & evolution () const =0
virtual std::vector< Time > possibleCashFlowTimes () const =0
virtual void nextStep (const CurveState &)=0
virtual void reset ()=0
virtual std::valarray< bool > isExerciseTime () const =0
virtual
MarketModelMultiProduct::CashFlow value (const CurveState &) const =0
virtual std::auto_ptr
< MarketModelExerciseValue > clone () const =0
Detailed Description
Definition at line 35 of file exercisevalue.hpp.
Constructor & Destructor Documentation
virtual QuantLib::MarketModelExerciseValue::~MarketModelExerciseValue () [inline, virtual]
Definition at line 37 of file exercisevalue.hpp.
{}
Member Function Documentation
virtual std::auto_ptr<MarketModelExerciseValue> QuantLib::MarketModelExerciseValue::clone () const [pure virtual]
Implemented in QuantLib::BermudanSwaptionExerciseValue, and QuantLib::NothingExerciseValue.
virtual const EvolutionDescription& QuantLib::MarketModelExerciseValue::evolution () const [pure virtual]
Implemented in QuantLib::BermudanSwaptionExerciseValue, and QuantLib::NothingExerciseValue.
Referenced by QuantLib::collectNodeData(), QuantLib::ExerciseAdapter::evolution(), and QuantLib::LongstaffSchwartzExerciseStrategy::LongstaffSchwartzExerciseStrategy().
virtual std::valarray<bool> QuantLib::MarketModelExerciseValue::isExerciseTime () const [pure virtual]
Implemented in QuantLib::BermudanSwaptionExerciseValue, and QuantLib::NothingExerciseValue.
Referenced by QuantLib::collectNodeData(), and QuantLib::LongstaffSchwartzExerciseStrategy::LongstaffSchwartzExerciseStrategy().
virtual void QuantLib::MarketModelExerciseValue::nextStep (const CurveState &) [pure virtual]
Implemented in QuantLib::BermudanSwaptionExerciseValue, and QuantLib::NothingExerciseValue.
Referenced by QuantLib::collectNodeData(), QuantLib::LongstaffSchwartzExerciseStrategy::nextStep(), and QuantLib::ExerciseAdapter::nextTimeStep().
virtual Size QuantLib::MarketModelExerciseValue::numberOfExercises () const [pure virtual]
Implemented in QuantLib::BermudanSwaptionExerciseValue, and QuantLib::NothingExerciseValue.
virtual std::vector<Time> QuantLib::MarketModelExerciseValue::possibleCashFlowTimes () const [pure virtual]
Implemented in QuantLib::BermudanSwaptionExerciseValue, and QuantLib::NothingExerciseValue.
Referenced by QuantLib::collectNodeData(), QuantLib::LongstaffSchwartzExerciseStrategy::LongstaffSchwartzExerciseStrategy(), and QuantLib::ExerciseAdapter::possibleCashFlowTimes().
virtual void QuantLib::MarketModelExerciseValue::reset () [pure virtual]
Implemented in QuantLib::BermudanSwaptionExerciseValue, and QuantLib::NothingExerciseValue.
Referenced by QuantLib::collectNodeData(), QuantLib::ExerciseAdapter::reset(), and QuantLib::LongstaffSchwartzExerciseStrategy::reset().
virtual MarketModelMultiProduct::CashFlow QuantLib::MarketModelExerciseValue::value (const CurveState &) const [pure virtual]
Implemented in QuantLib::BermudanSwaptionExerciseValue, and QuantLib::NothingExerciseValue.
Referenced by QuantLib::collectNodeData(), QuantLib::LongstaffSchwartzExerciseStrategy::exercise(), and QuantLib::ExerciseAdapter::nextTimeStep().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/callability/exercisevalue.hpp