QuantLib: QuantLib::InflationTermStructure Class Reference
QuantLib::InflationTermStructure Class Reference
Interface for inflation term structures.
#include <inflationtermstructure.hpp>
Public Member Functions
void setSeasonality (const boost::shared_ptr< Seasonality > &seasonality=boost::shared_ptr< Seasonality >())
Functions to set and get seasonality.
boost::shared_ptr< Seasonality > seasonality () const
bool hasSeasonality () const
Constructors
InflationTermStructure (Rate baseRate, const Period &observationLag, Frequency frequency, bool indexIsInterpolated, const Handle< YieldTermStructure > &yTS, const DayCounter &dayCounter=DayCounter(), const boost::shared_ptr< Seasonality > &seasonality=boost::shared_ptr< Seasonality >())
InflationTermStructure (const Date &referenceDate, Rate baseRate, const Period &observationLag, Frequency frequency, bool indexIsInterpolated, const Handle< YieldTermStructure > &yTS, const Calendar &calendar=Calendar(), const DayCounter &dayCounter=DayCounter(), const boost::shared_ptr< Seasonality > &seasonality=boost::shared_ptr< Seasonality >())
InflationTermStructure (Natural settlementDays, const Calendar &calendar, Rate baseRate, const Period &observationLag, Frequency frequency, bool indexIsInterpolated, const Handle< YieldTermStructure > &yTS, const DayCounter &dayCounter=DayCounter(), const boost::shared_ptr< Seasonality > &seasonality=boost::shared_ptr< Seasonality >())
Inflation interface
virtual Period observationLag () const
virtual Frequency frequency () const
virtual bool indexIsInterpolated () const
virtual Rate baseRate () const
virtual Handle
< YieldTermStructure > nominalTermStructure () const
virtual Date baseDate () const =0
minimum (base) date
Protected Member Functions
virtual void setBaseRate (const Rate &r)
void checkRange (const Date &, bool extrapolate) const
date-range check
void checkRange (Time t, bool extrapolate) const
time-range check
Protected Attributes
boost::shared_ptr< Seasonality > seasonality_
Period observationLag_
Frequency frequency_
bool indexIsInterpolated_
Rate baseRate_
Handle< YieldTermStructure > nominalTermStructure_
Detailed Description
Interface for inflation term structures.
Definition at line 35 of file inflationtermstructure.hpp.
Constructor & Destructor Documentation
QuantLib::InflationTermStructure::InflationTermStructure (Rate baseRate, const Period & observationLag, Frequency frequency, bool indexIsInterpolated, const Handle< YieldTermStructure > & yTS, const DayCounter & dayCounter = DayCounter(), const boost::shared_ptr< Seasonality > & seasonality = boost::shared_ptr<Seasonality>())
Definition at line 25 of file inflationtermstructure.cpp.
References nominalTermStructure_, QuantLib::Observer::registerWith(), and setSeasonality().
    : TermStructure(dayCounter),
      observationLag_(observationLag), frequency_(frequency), indexIsInterpolated_(indexIsInterpolated),
      baseRate_(baseRate), nominalTermStructure_(yTS) {
        registerWith(nominalTermStructure_);
        setSeasonality(seasonality);
    }
QuantLib::InflationTermStructure::InflationTermStructure (const Date & referenceDate, Rate baseRate, const Period & observationLag, Frequency frequency, bool indexIsInterpolated, const Handle< YieldTermStructure > & yTS, const Calendar & calendar = Calendar(), const DayCounter & dayCounter = DayCounter(), const boost::shared_ptr< Seasonality > & seasonality = boost::shared_ptr<Seasonality>())
Definition at line 40 of file inflationtermstructure.cpp.
References nominalTermStructure_, QuantLib::Observer::registerWith(), and setSeasonality().
    : TermStructure(referenceDate, calendar, dayCounter),
      observationLag_(observationLag),
      frequency_(frequency), indexIsInterpolated_(indexIsInterpolated),
      baseRate_(baseRate), nominalTermStructure_(yTS) {
        registerWith(nominalTermStructure_);
        setSeasonality(seasonality);
    }
QuantLib::InflationTermStructure::InflationTermStructure (Natural settlementDays, const Calendar & calendar, Rate baseRate, const Period & observationLag, Frequency frequency, bool indexIsInterpolated, const Handle< YieldTermStructure > & yTS, const DayCounter & dayCounter = DayCounter(), const boost::shared_ptr< Seasonality > & seasonality = boost::shared_ptr<Seasonality>())
Definition at line 58 of file inflationtermstructure.cpp.
References nominalTermStructure_, QuantLib::Observer::registerWith(), and setSeasonality().
    : TermStructure(settlementDays, calendar, dayCounter),
      observationLag_(observationLag),
      frequency_(frequency), indexIsInterpolated_(indexIsInterpolated),
      baseRate_(baseRate), nominalTermStructure_(yTS) {
        registerWith(nominalTermStructure_);
        setSeasonality(seasonality);
    }
Member Function Documentation
virtual Date QuantLib::InflationTermStructure::baseDate () const [pure virtual]
minimum (base) date
Important in inflation since it starts before nominal reference date. Changes depending whether index is interpolated or not. When interpolated the base date is just observation lag before nominal. When not interpolated it is the beginning of the relevant period (hence it is easy to create interpolated fixings from a not-interpolated curve because interpolation, usually, of fixings is forward looking).
Implemented in QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >, QuantLib::CPICapFloorTermPriceSurface, QuantLib::PiecewiseYoYInflationCurve< Interpolator, Bootstrap, Traits >, QuantLib::PiecewiseZeroInflationCurve< Interpolator, Bootstrap, Traits >, QuantLib::InterpolatedYoYInflationCurve< Interpolator >, and QuantLib::InterpolatedZeroInflationCurve< Interpolator >.
Referenced by checkRange(), QuantLib::MultiplicativePriceSeasonality::correctYoYRate(), QuantLib::MultiplicativePriceSeasonality::correctZeroRate(), and QuantLib::MultiplicativePriceSeasonality::isConsistent().
Rate QuantLib::InflationTermStructure::baseRate () const [inline, virtual]
Definition at line 281 of file inflationtermstructure.hpp.
References baseRate_.
Referenced by QuantLib::ZeroInflationTraits::initialValue(), and QuantLib::YoYInflationTraits::initialValue().
{
        return baseRate_;
    }
void QuantLib::InflationTermStructure::checkRange (const Date & d, bool extrapolate) const [protected]
date-range check
Reimplemented from QuantLib::TermStructure.
Definition at line 90 of file inflationtermstructure.cpp.
References QuantLib::Extrapolator::allowsExtrapolation(), baseDate(), QuantLib::TermStructure::maxDate(), and QL_REQUIRE.
Referenced by QuantLib::YoYInflationTermStructure::yoyRate(), and QuantLib::ZeroInflationTermStructure::zeroRate().
{
        QL_REQUIRE(d >= baseDate(),
                   "date (" << d << ") is before base date");
        QL_REQUIRE(extrapolate || allowsExtrapolation() || d <= maxDate(),
                   "date (" << d << ") is past max curve date ("
                   << maxDate() << ")");
    }
void QuantLib::InflationTermStructure::checkRange (Time t, bool extrapolate) const [protected]
time-range check
Reimplemented from QuantLib::TermStructure.
Definition at line 99 of file inflationtermstructure.cpp.
References QuantLib::Extrapolator::allowsExtrapolation(), baseDate(), QuantLib::TermStructure::maxTime(), QL_REQUIRE, and QuantLib::TermStructure::timeFromReference().
{
        QL_REQUIRE(t >= timeFromReference(baseDate()),
                   "time (" << t << ") is before base date");
        QL_REQUIRE(extrapolate || allowsExtrapolation() || t <= maxTime(),
                   "time (" << t << ") is past max curve time ("
                   << maxTime() << ")");
    }
Frequency QuantLib::InflationTermStructure::frequency () const [inline, virtual]
Definition at line 273 of file inflationtermstructure.hpp.
References frequency_.
Referenced by QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::calculateYoYTermStructure(), QuantLib::MultiplicativePriceSeasonality::correctYoYRate(), QuantLib::MultiplicativePriceSeasonality::correctZeroRate(), QuantLib::ZeroInflationTraits::initialDate(), QuantLib::YoYInflationTraits::initialDate(), QuantLib::InterpolatedYoYInflationCurve< Interpolator >::InterpolatedYoYInflationCurve(), QuantLib::InterpolatedZeroInflationCurve< Interpolator >::InterpolatedZeroInflationCurve(), QuantLib::MultiplicativePriceSeasonality::isConsistent(), QuantLib::YoYInflationTermStructure::yoyRate(), and QuantLib::ZeroInflationTermStructure::zeroRate().
{
        return frequency_;
    }
bool QuantLib::InflationTermStructure::hasSeasonality () const [inline]
Definition at line 294 of file inflationtermstructure.hpp.
References seasonality_.
Referenced by QuantLib::YoYInflationTermStructure::yoyRate(), and QuantLib::ZeroInflationTermStructure::zeroRate().
{
        return seasonality_;
    }
bool QuantLib::InflationTermStructure::indexIsInterpolated () const [inline, virtual]
Definition at line 277 of file inflationtermstructure.hpp.
References indexIsInterpolated_.
Referenced by QuantLib::ZeroInflationTraits::initialDate(), QuantLib::YoYInflationTraits::initialDate(), QuantLib::YoYInflationTermStructure::yoyRate(), and QuantLib::ZeroInflationTermStructure::zeroRate().
{
        return indexIsInterpolated_;
    }
Handle< YieldTermStructure > QuantLib::InflationTermStructure::nominalTermStructure () const [inline, virtual]
Definition at line 286 of file inflationtermstructure.hpp.
References nominalTermStructure_.
Referenced by QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::calculateYoYTermStructure(), QuantLib::CPICapFloorTermPriceSurface::CPICapFloorTermPriceSurface(), QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::intersect(), QuantLib::ZeroCouponInflationSwapHelper::setTermStructure(), and QuantLib::YearOnYearInflationSwapHelper::setTermStructure().
{
        return nominalTermStructure_;
    }
Period QuantLib::InflationTermStructure::observationLag () const [inline, virtual]
The TS observes with a lag that is usually different from the availability lag of the index. An inflation rate is given, by default, for the maturity requested assuming this lag.
Reimplemented in QuantLib::CPICapFloorTermPriceSurface.
Definition at line 269 of file inflationtermstructure.hpp.
References observationLag_.
Referenced by QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::calculateYoYTermStructure(), QuantLib::ZeroInflationTraits::initialDate(), QuantLib::YoYInflationTraits::initialDate(), QuantLib::InterpolatedYoYInflationCurve< Interpolator >::InterpolatedYoYInflationCurve(), QuantLib::InterpolatedZeroInflationCurve< Interpolator >::InterpolatedZeroInflationCurve(), QuantLib::YoYInflationTermStructure::yoyRate(), and QuantLib::ZeroInflationTermStructure::zeroRate().
{
        return observationLag_;
    }
boost::shared_ptr< Seasonality > QuantLib::InflationTermStructure::seasonality () const [inline]
Definition at line 290 of file inflationtermstructure.hpp.
References seasonality_.
Referenced by setSeasonality(), QuantLib::YoYInflationTermStructure::yoyRate(), and QuantLib::ZeroInflationTermStructure::zeroRate().
{
        return seasonality_;
    }
virtual void QuantLib::InflationTermStructure::setBaseRate (const Rate & r) [inline, protected, virtual]
Definition at line 106 of file inflationtermstructure.hpp.
References baseRate_.
{baseRate_=r;}
void QuantLib::InflationTermStructure::setSeasonality (const boost::shared_ptr< Seasonality > & seasonality = boost::shared_ptr<Seasonality>())
Functions to set and get seasonality.
Calling setSeasonality with no arguments means unsetting as the default is used to choose unsetting.
Definition at line 77 of file inflationtermstructure.cpp.
References QuantLib::Observable::notifyObservers(), QL_REQUIRE, seasonality(), and seasonality_.
Referenced by InflationTermStructure().
{
        // always reset, whether with null or new pointer
        seasonality_ = seasonality;
        if (seasonality_) {
            QL_REQUIRE(seasonality_->isConsistent(*this),
                       "Seasonality inconsistent with "
                       "inflation term structure");
        }
        notifyObservers();
    }
Member Data Documentation
Rate QuantLib::InflationTermStructure::baseRate_ [mutable, protected]
Definition at line 122 of file inflationtermstructure.hpp.
Referenced by baseRate(), and setBaseRate().
Frequency QuantLib::InflationTermStructure::frequency_ [protected]
Definition at line 120 of file inflationtermstructure.hpp.
Referenced by frequency().
bool QuantLib::InflationTermStructure::indexIsInterpolated_ [protected]
Definition at line 121 of file inflationtermstructure.hpp.
Referenced by indexIsInterpolated(), and QuantLib::InterpolatedZeroInflationCurve< Interpolator >::InterpolatedZeroInflationCurve().
Handle<YieldTermStructure> QuantLib::InflationTermStructure::nominalTermStructure_ [protected]
Definition at line 123 of file inflationtermstructure.hpp.
Referenced by InflationTermStructure(), and nominalTermStructure().
Period QuantLib::InflationTermStructure::observationLag_ [protected]
Definition at line 119 of file inflationtermstructure.hpp.
Referenced by observationLag().
boost::shared_ptr<Seasonality> QuantLib::InflationTermStructure::seasonality_ [protected]
Definition at line 115 of file inflationtermstructure.hpp.
Referenced by hasSeasonality(), seasonality(), and setSeasonality().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/inflationtermstructure.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/inflationtermstructure.cpp