QuantLib: QuantLib::LocalBootstrap< Curve > Class Template Reference
QuantLib::LocalBootstrap< Curve > Class Template Reference
Localised-term-structure bootstrapper for most curve types.
#include <localbootstrap.hpp>
Public Member Functions
LocalBootstrap (Size localisation=2, bool forcePositive=true)
void setup (Curve *ts)
void calculate () const
Private Types
typedef Curve::traits_type Traits
typedef Curve::interpolator_type Interpolator
Private Attributes
bool validCurve_
Curve * ts_
Size localisation_
bool forcePositive_
Detailed Description
template<class Curve>
class QuantLib::LocalBootstrap< Curve >
Localised-term-structure bootstrapper for most curve types.
This algorithm enables a localised fitting for non-local interpolation methods.
As in the similar class (IterativeBootstrap) the input term structure is solved on a number of market instruments which are passed as a vector of handles to BootstrapHelper instances. Their maturities mark the boundaries of the interpolated segments.
Unlike the IterativeBootstrap class, the solution for each interpolated segment is derived using a local approximation. This restricts the risk profile s.t. the risk is localised. Therefore, we obtain a local IR risk profile whilst using a smoother interpolation method. Particularly good for the convex-monotone spline method.
Definition at line 86 of file localbootstrap.hpp.
Member Typedef Documentation
template<class Curve > typedef Curve::interpolator_type QuantLib::LocalBootstrap< Curve >::Interpolator [private]
Definition at line 88 of file localbootstrap.hpp.
template<class Curve > typedef Curve::traits_type QuantLib::LocalBootstrap< Curve >::Traits [private]
Definition at line 87 of file localbootstrap.hpp.
Constructor & Destructor Documentation
template<class Curve > QuantLib::LocalBootstrap< Curve >::LocalBootstrap (Size localisation = 2, bool forcePositive = true)
Definition at line 107 of file localbootstrap.hpp.
    : validCurve_(false), ts_(0), localisation_(localisation),
      forcePositive_(forcePositive)
    {}
Member Function Documentation
template<class Curve > void QuantLib::LocalBootstrap< Curve >::calculate () const
Definition at line 133 of file localbootstrap.hpp.
References QuantLib::Array::data_, QuantLib::LevenbergMarquardt::minimize(), QuantLib::io::ordinal(), QL_ENSURE, QL_REQUIRE, QuantLib::Array::size(), QuantLib::EndCriteria::StationaryFunctionAccuracy, and QuantLib::EndCriteria::StationaryFunctionValue.
{
        validCurve_ = false;
        Size nInsts = ts_->instruments_.size();
        // ensure rate helpers are sorted
        std::sort(ts_->instruments_.begin(), ts_->instruments_.end(),
                  detail::BootstrapHelperSorter());
        // check that there is no instruments with the same maturity
        for (Size i=1; i<nInsts; ++i) {
            Date m1 = ts_->instruments_[i-1]->latestDate(),
                 m2 = ts_->instruments_[i]->latestDate();
            QL_REQUIRE(m1 != m2,
                       "two instruments have the same maturity ("<< m1 <<")");
        }
        // check that there is no instruments with invalid quote
        for (Size i=0; i<nInsts; ++i)
            QL_REQUIRE(ts_->instruments_[i]->quote()->isValid(),
                       io::ordinal(i+1) << " instrument (maturity: " <<
                       ts_->instruments_[i]->latestDate() <<
                       ") has an invalid quote");
        // setup instruments
        for (Size i=0; i<nInsts; ++i) {
            // don't try this at home!
            // This call creates instruments, and removes "const".
            // There is a significant interaction with observability.
            ts_->instruments_[i]->setTermStructure(const_cast<Curve*>(ts_));
        }
        // set initial guess only if the current curve cannot be used as guess
        if (validCurve_)
            QL_ENSURE(ts_->data_.size() == nInsts+1,
                      "dimension mismatch: expected " << nInsts+1 <<
                      ", actual " << ts_->data_.size());
        else {
            ts_->data_ = std::vector<Rate>(nInsts+1);
            ts_->data_[0] = Traits::initialValue(ts_);
        }
        // calculate dates and times
        ts_->dates_ = std::vector<Date>(nInsts+1);
        ts_->times_ = std::vector<Time>(nInsts+1);
        ts_->dates_[0] = Traits::initialDate(ts_);
        ts_->times_[0] = ts_->timeFromReference(ts_->dates_[0]);
        for (Size i=0; i<nInsts; ++i) {
            ts_->dates_[i+1] = ts_->instruments_[i]->latestDate();
            ts_->times_[i+1] = ts_->timeFromReference(ts_->dates_[i+1]);
            if (!validCurve_)
                ts_->data_[i+1] = ts_->data_[i];
        }
        LevenbergMarquardt solver(ts_->accuracy_,
                                  ts_->accuracy_,
                                  ts_->accuracy_);
        EndCriteria endCriteria(100, 10, 0.00, ts_->accuracy_, 0.00);
        PositiveConstraint posConstraint;
        NoConstraint noConstraint;
        Constraint& solverConstraint = forcePositive_ ?
            static_cast<Constraint&>(posConstraint) :
            static_cast<Constraint&>(noConstraint);
        // now start the bootstrapping.
        Size iInst = localisation_-1;
        Size dataAdjust = Curve::interpolator_type::dataSizeAdjustment;
        do {
            Size initialDataPt = iInst+1-localisation_+dataAdjust;
            Array startArray(localisation_+1-dataAdjust);
            for (Size j = 0; j < startArray.size()-1; ++j)
                startArray[j] = ts_->data_[initialDataPt+j];
            // here we are extending the interpolation a point at a
            // time... but the local interpolator can make an
            // approximation for the final localisation period.
            // e.g. if the localisation is 2, then the first section
            // of the curve will be solved using the first 2
            // instruments... with the local interpolator making
            // suitable boundary conditions.
            ts_->interpolation_ =
                ts_->interpolator_.localInterpolate(
                                              ts_->times_.begin(),
                                              ts_->times_.begin()+(iInst + 2),
                                              ts_->data_.begin(),
                                              localisation_,
                                              ts_->interpolation_,
                                              nInsts+1);
            if (iInst >= localisation_) {
                startArray[localisation_-dataAdjust] =
                    Traits::guess(iInst, ts_, false, 0); // ?
            } else {
                startArray[localisation_-dataAdjust] = ts_->data_[0];
            }
            PenaltyFunction<Curve> currentCost(
                        ts_,
                        initialDataPt,
                        ts_->instruments_.begin() + (iInst - localisation_+1),
                        ts_->instruments_.begin() + (iInst+1));
            Problem toSolve(currentCost, solverConstraint, startArray);
            EndCriteria::Type endType = solver.minimize(toSolve, endCriteria);
            // check the end criteria
            QL_REQUIRE(endType == EndCriteria::StationaryFunctionAccuracy ||
                       endType == EndCriteria::StationaryFunctionValue,
                       "Unable to strip yieldcurve to required accuracy " );
            ++iInst;
        } while ( iInst < nInsts );
        validCurve_ = true;
    }
template<class Curve > void QuantLib::LocalBootstrap< Curve >::setup (Curve * ts)
Definition at line 114 of file localbootstrap.hpp.
References QL_REQUIRE.
{
        ts_ = ts;
        Size n = ts_->instruments_.size();
        QL_REQUIRE(n >= Interpolator::requiredPoints,
                   "not enough instruments: " << n << " provided, " <<
                   Interpolator::requiredPoints << " required");
        QL_REQUIRE(n > localisation_,
                   "not enough instruments: " << n << " provided, " <<
                   localisation_ << " required.");
        for (Size i=0; i<n; ++i){
            ts_->registerWith(ts_->instruments_[i]);
        }
    }
Member Data Documentation
template<class Curve > bool QuantLib::LocalBootstrap< Curve >::forcePositive_ [private]
Definition at line 99 of file localbootstrap.hpp.
template<class Curve > Size QuantLib::LocalBootstrap< Curve >::localisation_ [private]
Definition at line 98 of file localbootstrap.hpp.
template<class Curve > Curve* QuantLib::LocalBootstrap< Curve >::ts_ [private]
Definition at line 97 of file localbootstrap.hpp.
template<class Curve > bool QuantLib::LocalBootstrap< Curve >::validCurve_ [mutable, private]
Definition at line 96 of file localbootstrap.hpp.
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/localbootstrap.hpp