QuantLib: QuantLib::MCEverestEngine< RNG, S > Class Template Reference
QuantLib::MCEverestEngine< RNG, S > Class Template Reference
#include <mceverestengine.hpp>
Public Types
typedef McSimulation
< MultiVariate, RNG, S >
::path_generator_type path_generator_type
typedef McSimulation
< MultiVariate, RNG, S >
::path_pricer_type path_pricer_type
typedef McSimulation
< MultiVariate, RNG, S >
::stats_type stats_type
Public Member Functions
MCEverestEngine (const boost::shared_ptr< StochasticProcessArray > &, Size timeSteps, Size timeStepsPerYear, bool brownianBridge, bool antitheticVariate, Size requiredSamples, Real requiredTolerance, Size maxSamples, BigNatural seed)
void calculate () const
Private Member Functions
DiscountFactor endDiscount () const
TimeGrid timeGrid () const
boost::shared_ptr
< path_generator_type > pathGenerator () const
boost::shared_ptr
< path_pricer_type > pathPricer () const
Private Attributes
boost::shared_ptr
< StochasticProcessArray > processes_
Size timeSteps_
Size timeStepsPerYear_
Size requiredSamples_
Size maxSamples_
Real requiredTolerance_
bool brownianBridge_
BigNatural seed_
Detailed Description
template<class RNG = PseudoRandom, class S = Statistics>
class QuantLib::MCEverestEngine< RNG, S >
Definition at line 36 of file mceverestengine.hpp.
Member Typedef Documentation
template<class RNG = PseudoRandom, class S = Statistics> typedef McSimulation<MultiVariate,RNG,S>::path_generator_type QuantLib::MCEverestEngine< RNG, S >::path_generator_type
Reimplemented from QuantLib::McSimulation< MultiVariate, RNG, S >.
Definition at line 40 of file mceverestengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> typedef McSimulation<MultiVariate,RNG,S>::path_pricer_type QuantLib::MCEverestEngine< RNG, S >::path_pricer_type
Reimplemented from QuantLib::McSimulation< MultiVariate, RNG, S >.
Definition at line 42 of file mceverestengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> typedef McSimulation<MultiVariate,RNG,S>::stats_type QuantLib::MCEverestEngine< RNG, S >::stats_type
Reimplemented from QuantLib::McSimulation< MultiVariate, RNG, S >.
Definition at line 44 of file mceverestengine.hpp.
Constructor & Destructor Documentation
template<class RNG , class S > QuantLib::MCEverestEngine< RNG, S >::MCEverestEngine (const boost::shared_ptr< StochasticProcessArray > & processes, Size timeSteps, Size timeStepsPerYear, bool brownianBridge, bool antitheticVariate, Size requiredSamples, Real requiredTolerance, Size maxSamples, BigNatural seed) [inline]
Definition at line 140 of file mceverestengine.hpp.
References QuantLib::MCEverestEngine< RNG, S >::processes_, QL_REQUIRE, and QuantLib::Observer::registerWith().
    : McSimulation<MultiVariate,RNG,S>(antitheticVariate, false),
      processes_(processes), timeSteps_(timeSteps),
      timeStepsPerYear_(timeStepsPerYear),
      requiredSamples_(requiredSamples), maxSamples_(maxSamples),
      requiredTolerance_(requiredTolerance),
      brownianBridge_(brownianBridge), seed_(seed) {
        QL_REQUIRE(timeSteps != Null<Size>() ||
                   timeStepsPerYear != Null<Size>(),
                   "no time steps provided");
        QL_REQUIRE(timeSteps == Null<Size>() ||
                   timeStepsPerYear == Null<Size>(),
                   "both time steps and time steps per year were provided");
        QL_REQUIRE(timeSteps != 0,
                   "timeSteps must be positive, " << timeSteps <<
                   " not allowed");
        QL_REQUIRE(timeStepsPerYear != 0,
                   "timeStepsPerYear must be positive, " << timeStepsPerYear <<
                   " not allowed");
        registerWith(processes_);
    }
Member Function Documentation
template<class RNG = PseudoRandom, class S = Statistics> void QuantLib::MCEverestEngine< RNG, S >::calculate () const [inline, virtual]
Implements QuantLib::PricingEngine.
Definition at line 54 of file mceverestengine.hpp.
References QuantLib::GenericEngine< EverestOption::arguments, EverestOption::results >::arguments_, QuantLib::MCEverestEngine< RNG, S >::endDiscount(), QuantLib::Instrument::results::errorEstimate, QuantLib::MCEverestEngine< RNG, S >::maxSamples_, QuantLib::McSimulation< MultiVariate, RNG, S >::mcModel_, QuantLib::EverestOption::arguments::notional, QuantLib::MCEverestEngine< RNG, S >::requiredSamples_, QuantLib::MCEverestEngine< RNG, S >::requiredTolerance_, QuantLib::GenericEngine< EverestOption::arguments, EverestOption::results >::results_, QuantLib::Instrument::results::value, and QuantLib::EverestOption::results::yield.
{
            McSimulation<MultiVariate,RNG,S>::calculate(requiredTolerance_,
                                                        requiredSamples_,
                                                        maxSamples_);
            results_.value = this->mcModel_->sampleAccumulator().mean();
            if (RNG::allowsErrorEstimate) {
                results_.errorEstimate =
                    this->mcModel_->sampleAccumulator().errorEstimate();
            }
            Real notional = arguments_.notional;
            DiscountFactor discount = endDiscount();
            results_.yield = results_.value/(notional * discount) - 1.0;
        }
template<class RNG , class S > DiscountFactor QuantLib::MCEverestEngine< RNG, S >::endDiscount () const [inline, private]
Definition at line 186 of file mceverestengine.hpp.
References QL_REQUIRE.
Referenced by QuantLib::MCEverestEngine< RNG, S >::calculate().
{
        boost::shared_ptr<GeneralizedBlackScholesProcess> process =
            boost::dynamic_pointer_cast<GeneralizedBlackScholesProcess>(
                                                      processes_->process(0));
        QL_REQUIRE(process, "Black-Scholes process required");
        return process->riskFreeRate()->discount(
                                             arguments_.exercise->lastDate());
    }
template<class RNG = PseudoRandom, class S = Statistics> boost::shared_ptr<path_generator_type> QuantLib::MCEverestEngine< RNG, S >::pathGenerator () const [inline, private, virtual]
Implements QuantLib::McSimulation< MultiVariate, RNG, S >.
Definition at line 74 of file mceverestengine.hpp.
References QuantLib::MCEverestEngine< RNG, S >::brownianBridge_, QuantLib::MCEverestEngine< RNG, S >::processes_, QuantLib::MCEverestEngine< RNG, S >::seed_, QuantLib::TimeGrid::size(), and QuantLib::MCEverestEngine< RNG, S >::timeGrid().
{
            Size numAssets = processes_->size();
            TimeGrid grid = timeGrid();
            typename RNG::rsg_type gen =
                RNG::make_sequence_generator(numAssets*(grid.size()-1),seed_);
            return boost::shared_ptr<path_generator_type>(
                         new path_generator_type(processes_,
                                                 grid, gen, brownianBridge_));
        }
template<class RNG , class S > boost::shared_ptr< typename MCEverestEngine< RNG, S >::path_pricer_type > QuantLib::MCEverestEngine< RNG, S >::pathPricer () const [inline, private, virtual]
Implements QuantLib::McSimulation< MultiVariate, RNG, S >.
Definition at line 198 of file mceverestengine.hpp.
{
        return boost::shared_ptr<
                         typename MCEverestEngine<RNG,S>::path_pricer_type>(
                              new EverestMultiPathPricer(arguments_.notional,
                                                         arguments_.guarantee,
                                                         endDiscount()));
    }
template<class RNG , class S > TimeGrid QuantLib::MCEverestEngine< RNG, S >::timeGrid () const [inline, private, virtual]
Implements QuantLib::McSimulation< MultiVariate, RNG, S >.
Definition at line 172 of file mceverestengine.hpp.
References QL_FAIL.
Referenced by QuantLib::MCEverestEngine< RNG, S >::pathGenerator().
{
        Time residualTime = processes_->time(
                                       this->arguments_.exercise->lastDate());
        if (timeSteps_ != Null<Size>()) {
            return TimeGrid(residualTime, timeSteps_);
        } else if (timeStepsPerYear_ != Null<Size>()) {
            Size steps = static_cast<Size>(timeStepsPerYear_*residualTime);
            return TimeGrid(residualTime, std::max<Size>(steps, 1));
        } else {
            QL_FAIL("time steps not specified");
        }
    }
Member Data Documentation
template<class RNG = PseudoRandom, class S = Statistics> bool QuantLib::MCEverestEngine< RNG, S >::brownianBridge_ [private]
Definition at line 94 of file mceverestengine.hpp.
Referenced by QuantLib::MCEverestEngine< RNG, S >::pathGenerator().
template<class RNG = PseudoRandom, class S = Statistics> Size QuantLib::MCEverestEngine< RNG, S >::maxSamples_ [private]
Definition at line 92 of file mceverestengine.hpp.
Referenced by QuantLib::MCEverestEngine< RNG, S >::calculate().
template<class RNG = PseudoRandom, class S = Statistics> boost::shared_ptr<StochasticProcessArray> QuantLib::MCEverestEngine< RNG, S >::processes_ [private]
Definition at line 89 of file mceverestengine.hpp.
Referenced by QuantLib::MCEverestEngine< RNG, S >::MCEverestEngine(), and QuantLib::MCEverestEngine< RNG, S >::pathGenerator().
template<class RNG = PseudoRandom, class S = Statistics> Size QuantLib::MCEverestEngine< RNG, S >::requiredSamples_ [private]
Definition at line 91 of file mceverestengine.hpp.
Referenced by QuantLib::MCEverestEngine< RNG, S >::calculate().
template<class RNG = PseudoRandom, class S = Statistics> Real QuantLib::MCEverestEngine< RNG, S >::requiredTolerance_ [private]
Definition at line 93 of file mceverestengine.hpp.
Referenced by QuantLib::MCEverestEngine< RNG, S >::calculate().
template<class RNG = PseudoRandom, class S = Statistics> BigNatural QuantLib::MCEverestEngine< RNG, S >::seed_ [private]
Definition at line 95 of file mceverestengine.hpp.
Referenced by QuantLib::MCEverestEngine< RNG, S >::pathGenerator().
template<class RNG = PseudoRandom, class S = Statistics> Size QuantLib::MCEverestEngine< RNG, S >::timeSteps_ [private]
Definition at line 90 of file mceverestengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> Size QuantLib::MCEverestEngine< RNG, S >::timeStepsPerYear_ [private]
Definition at line 90 of file mceverestengine.hpp.
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/exoticoptions/mceverestengine.hpp