QuantLib: QuantLib::TypePayoff Class Reference
QuantLib::TypePayoff Class Reference
Intermediate class for put/call payoffs.
#include <payoffs.hpp>
Public Member Functions
Option::Type optionType () const
Payoff interface
std::string description () const
Protected Member Functions
TypePayoff (Option::Type type)
Protected Attributes
Option::Type type_
Detailed Description
Intermediate class for put/call payoffs.
Definition at line 49 of file payoffs.hpp.
Constructor & Destructor Documentation
QuantLib::TypePayoff::TypePayoff (Option::Type type) [inline, protected]
Definition at line 57 of file payoffs.hpp.
: type_(type) {}
Member Function Documentation
std::string QuantLib::TypePayoff::description () const [virtual]
Implements QuantLib::Payoff.
Reimplemented in QuantLib::SuperSharePayoff, QuantLib::GapPayoff, QuantLib::CashOrNothingPayoff, and QuantLib::StrikedTypePayoff.
Definition at line 50 of file payoffs.cpp.
References QuantLib::Payoff::name(), and optionType().
{
        std::ostringstream result;
        result << name() << " " << optionType();
        return result.str();
    }
Option::Type QuantLib::TypePayoff::optionType () const [inline]
Definition at line 51 of file payoffs.hpp.
References type_.
Referenced by description(), QuantLib::AnalyticHestonEngine::doCalculation(), and QuantLib::BlackCalculator::Calculator::visit().
{ return type_; };
Member Data Documentation
Option::Type QuantLib::TypePayoff::type_ [protected]
Definition at line 58 of file payoffs.hpp.
Referenced by QuantLib::PlainVanillaPayoff::operator()(), QuantLib::PercentageStrikePayoff::operator()(), QuantLib::AssetOrNothingPayoff::operator()(), QuantLib::CashOrNothingPayoff::operator()(), QuantLib::GapPayoff::operator()(), and optionType().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/payoffs.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/payoffs.cpp