QuantLib: QuantLib::MCPerformanceEngine< RNG, S > Class Template Reference
QuantLib::MCPerformanceEngine< RNG, S > Class Template Reference
Pricing engine for performance options using Monte Carlo simulation.
#include <mcperformanceengine.hpp>
Public Types
typedef McSimulation
< SingleVariate, RNG, S >
::path_generator_type path_generator_type
typedef McSimulation
< SingleVariate, RNG, S >
::path_pricer_type path_pricer_type
typedef McSimulation
< SingleVariate, RNG, S >
::stats_type stats_type
Public Member Functions
MCPerformanceEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > &process, bool brownianBridge, bool antitheticVariate, Size requiredSamples, Real requiredTolerance, Size maxSamples, BigNatural seed)
void calculate () const
Protected Member Functions
TimeGrid timeGrid () const
boost::shared_ptr
< path_generator_type > pathGenerator () const
boost::shared_ptr
< path_pricer_type > pathPricer () const
Protected Attributes
boost::shared_ptr
< GeneralizedBlackScholesProcess > process_
Size requiredSamples_
Size maxSamples_
Real requiredTolerance_
bool brownianBridge_
BigNatural seed_
Detailed Description
template<class RNG = PseudoRandom, class S = Statistics>
class QuantLib::MCPerformanceEngine< RNG, S >
Pricing engine for performance options using Monte Carlo simulation.
Definition at line 32 of file mcperformanceengine.hpp.
Member Typedef Documentation
template<class RNG = PseudoRandom, class S = Statistics> typedef McSimulation<SingleVariate,RNG,S>::path_generator_type QuantLib::MCPerformanceEngine< RNG, S >::path_generator_type
Reimplemented from QuantLib::McSimulation< SingleVariate, RNG, S >.
Definition at line 37 of file mcperformanceengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> typedef McSimulation<SingleVariate,RNG,S>::path_pricer_type QuantLib::MCPerformanceEngine< RNG, S >::path_pricer_type
Reimplemented from QuantLib::McSimulation< SingleVariate, RNG, S >.
Definition at line 39 of file mcperformanceengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> typedef McSimulation<SingleVariate,RNG,S>::stats_type QuantLib::MCPerformanceEngine< RNG, S >::stats_type
Reimplemented from QuantLib::McSimulation< SingleVariate, RNG, S >.
Definition at line 41 of file mcperformanceengine.hpp.
Constructor & Destructor Documentation
template<class RNG , class S > QuantLib::MCPerformanceEngine< RNG, S >::MCPerformanceEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > & process, bool brownianBridge, bool antitheticVariate, Size requiredSamples, Real requiredTolerance, Size maxSamples, BigNatural seed) [inline]
Definition at line 124 of file mcperformanceengine.hpp.
References QuantLib::MCPerformanceEngine< RNG, S >::process_, and QuantLib::Observer::registerWith().
    : McSimulation<SingleVariate,RNG,S>(antitheticVariate, false),
      process_(process), requiredSamples_(requiredSamples),
      maxSamples_(maxSamples), requiredTolerance_(requiredTolerance),
      brownianBridge_(brownianBridge), seed_(seed) {
        registerWith(process_);
    }
Member Function Documentation
template<class RNG = PseudoRandom, class S = Statistics> void QuantLib::MCPerformanceEngine< RNG, S >::calculate () const [inline, virtual]
Implements QuantLib::PricingEngine.
Definition at line 51 of file mcperformanceengine.hpp.
References QuantLib::Instrument::results::errorEstimate, QuantLib::MCPerformanceEngine< RNG, S >::maxSamples_, QuantLib::McSimulation< SingleVariate, RNG, S >::mcModel_, QuantLib::MCPerformanceEngine< RNG, S >::requiredSamples_, QuantLib::MCPerformanceEngine< RNG, S >::requiredTolerance_, QuantLib::GenericEngine< CliquetOption::arguments, CliquetOption::results >::results_, and QuantLib::Instrument::results::value.
{
            McSimulation<SingleVariate,RNG,S>::calculate(requiredTolerance_,
                                                         requiredSamples_,
                                                         maxSamples_);
            results_.value = this->mcModel_->sampleAccumulator().mean();
            if (RNG::allowsErrorEstimate)
            results_.errorEstimate =
                this->mcModel_->sampleAccumulator().errorEstimate();
        }
template<class RNG = PseudoRandom, class S = Statistics> boost::shared_ptr<path_generator_type> QuantLib::MCPerformanceEngine< RNG, S >::pathGenerator () const [inline, protected, virtual]
Implements QuantLib::McSimulation< SingleVariate, RNG, S >.
Definition at line 63 of file mcperformanceengine.hpp.
References QuantLib::MCPerformanceEngine< RNG, S >::brownianBridge_, QuantLib::MCPerformanceEngine< RNG, S >::process_, QuantLib::MCPerformanceEngine< RNG, S >::seed_, QuantLib::TimeGrid::size(), and QuantLib::MCPerformanceEngine< RNG, S >::timeGrid().
{
            TimeGrid grid = this->timeGrid();
            typename RNG::rsg_type gen =
                RNG::make_sequence_generator(grid.size()-1,seed_);
            return boost::shared_ptr<path_generator_type>(
                         new path_generator_type(process_, grid,
                                                 gen, brownianBridge_));
        }
template<class RNG , class S > boost::shared_ptr< typename MCPerformanceEngine< RNG, S >::path_pricer_type > QuantLib::MCPerformanceEngine< RNG, S >::pathPricer () const [inline, protected, virtual]
Implements QuantLib::McSimulation< SingleVariate, RNG, S >.
Definition at line 155 of file mcperformanceengine.hpp.
References QL_REQUIRE.
{
        boost::shared_ptr<PercentageStrikePayoff> payoff =
            boost::dynamic_pointer_cast<PercentageStrikePayoff>(
                this->arguments_.payoff);
        QL_REQUIRE(payoff, "non-percentage payoff given");
        boost::shared_ptr<EuropeanExercise> exercise =
            boost::dynamic_pointer_cast<EuropeanExercise>(
                this->arguments_.exercise);
        QL_REQUIRE(exercise, "wrong exercise given");
        std::vector<DiscountFactor> discounts;
        for (Size k=0;k<arguments_.resetDates.size();k++) {
            discounts.push_back(this->process_->riskFreeRate()->discount(
                                                   arguments_.resetDates[k]));
        }
        discounts.push_back(this->process_->riskFreeRate()->discount(
                                            arguments_.exercise->lastDate()));
        return boost::shared_ptr<
            typename MCPerformanceEngine<RNG,S>::path_pricer_type>(
                         new PerformanceOptionPathPricer(payoff->optionType(),
                                                         payoff->strike(),
                                                         discounts));
    }
template<class RNG , class S > TimeGrid QuantLib::MCPerformanceEngine< RNG, S >::timeGrid () const [inline, protected, virtual]
Implements QuantLib::McSimulation< SingleVariate, RNG, S >.
Definition at line 141 of file mcperformanceengine.hpp.
Referenced by QuantLib::MCPerformanceEngine< RNG, S >::pathGenerator().
{
        std::vector<Time> fixingTimes;
        for (Size i=0; i<arguments_.resetDates.size(); i++)
            fixingTimes.push_back(process_->time(arguments_.resetDates[i]));
        fixingTimes.push_back(process_->time(arguments_.exercise->lastDate()));
        return TimeGrid(fixingTimes.begin(), fixingTimes.end());
    }
Member Data Documentation
template<class RNG = PseudoRandom, class S = Statistics> bool QuantLib::MCPerformanceEngine< RNG, S >::brownianBridge_ [protected]
Definition at line 77 of file mcperformanceengine.hpp.
Referenced by QuantLib::MCPerformanceEngine< RNG, S >::pathGenerator().
template<class RNG = PseudoRandom, class S = Statistics> Size QuantLib::MCPerformanceEngine< RNG, S >::maxSamples_ [protected]
Definition at line 75 of file mcperformanceengine.hpp.
Referenced by QuantLib::MCPerformanceEngine< RNG, S >::calculate().
template<class RNG = PseudoRandom, class S = Statistics> boost::shared_ptr<GeneralizedBlackScholesProcess> QuantLib::MCPerformanceEngine< RNG, S >::process_ [protected]
Definition at line 74 of file mcperformanceengine.hpp.
Referenced by QuantLib::MCPerformanceEngine< RNG, S >::MCPerformanceEngine(), and QuantLib::MCPerformanceEngine< RNG, S >::pathGenerator().
template<class RNG = PseudoRandom, class S = Statistics> Size QuantLib::MCPerformanceEngine< RNG, S >::requiredSamples_ [protected]
Definition at line 75 of file mcperformanceengine.hpp.
Referenced by QuantLib::MCPerformanceEngine< RNG, S >::calculate().
template<class RNG = PseudoRandom, class S = Statistics> Real QuantLib::MCPerformanceEngine< RNG, S >::requiredTolerance_ [protected]
Definition at line 76 of file mcperformanceengine.hpp.
Referenced by QuantLib::MCPerformanceEngine< RNG, S >::calculate().
template<class RNG = PseudoRandom, class S = Statistics> BigNatural QuantLib::MCPerformanceEngine< RNG, S >::seed_ [protected]
Definition at line 78 of file mcperformanceengine.hpp.
Referenced by QuantLib::MCPerformanceEngine< RNG, S >::pathGenerator().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/cliquet/mcperformanceengine.hpp