QuantLib: QuantLib::FittedBondDiscountCurve Class Reference
QuantLib::FittedBondDiscountCurve Class Reference
Discount curve fitted to a set of fixed-coupon bonds.
#include <fittedbonddiscountcurve.hpp>
Classes
class FittingMethod
Base fitting method used to construct a fitted bond discount curve.
Public Member Functions
Constructors
FittedBondDiscountCurve (Natural settlementDays, const Calendar &calendar, const std::vector< boost::shared_ptr< BondHelper > > &bonds, const DayCounter &dayCounter, const FittingMethod &fittingMethod, Real accuracy=1.0e-10, Size maxEvaluations=10000, const Array &guess=Array(), Real simplexLambda=1.0)
reference date based on current evaluation date
FittedBondDiscountCurve (const Date &referenceDate, const std::vector< boost::shared_ptr< BondHelper > > &bonds, const DayCounter &dayCounter, const FittingMethod &fittingMethod, Real accuracy=1.0e-10, Size maxEvaluations=10000, const Array &guess=Array(), Real simplexLambda=1.0)
curve reference date fixed for life of curve
FittedBondDiscountCurve (Natural settlementDays, const Calendar &calendar, const std::vector< boost::shared_ptr< FixedRateBondHelper > > &bonds, const DayCounter &dayCounter, const FittingMethod &fittingMethod, Real accuracy=1.0e-10, Size maxEvaluations=10000, const Array &guess=Array(), Real simplexLambda=1.0)
reference date based on current evaluation date
FittedBondDiscountCurve (const Date &referenceDate, const std::vector< boost::shared_ptr< FixedRateBondHelper > > &bonds, const DayCounter &dayCounter, const FittingMethod &fittingMethod, Real accuracy=1.0e-10, Size maxEvaluations=10000, const Array &guess=Array(), Real simplexLambda=1.0)
curve reference date fixed for life of curve
Inspectors
Size numberOfBonds () const
total number of bonds used to fit the yield curve
Date maxDate () const
the latest date for which the curve can return values
const FittingMethod & fitResults () const
class holding the results of the fit
Observer interface
void update ()
Private Member Functions
void setup ()
void performCalculations () const
DiscountFactor discountImpl (Time) const
discount factor calculation
Private Attributes
Real accuracy_
Size maxEvaluations_
Real simplexLambda_
Array guessSolution_
Date maxDate_
std::vector< boost::shared_ptr
< BondHelper > > bondHelpers_
Clone< FittingMethod > fittingMethod_
Friends
class FittingMethod
Detailed Description
Discount curve fitted to a set of fixed-coupon bonds.
This class fits a discount function \(d(t) \) over a set of bonds, using a user defined fitting method. The discount function is fit in such a way so that all cashflows of all input bonds, when discounted using \(d(t) \), will reproduce the set of input bond prices in an optimized sense. Minimized price errors are weighted by the inverse of their respective bond duration.
The FittedBondDiscountCurve class acts as a generic wrapper, while its inner class FittingMethod provides the implementation details. Developers thus need only derive new fitting methods from the latter.
Example: compares various bond discount curve fitting methodologies
Warning:
The method can be slow if there are many bonds to fit. Speed also depends on the particular choice of fitting method chosen and its convergence properties under optimization. See also todo list for BondDiscountCurveFittingMethod.
Todo:
refactor the bond helper class so that it is pure virtual and returns a generic bond or its cash flows. Derived classes would include helpers for fixed-rate and zero-coupon bonds. In this way, both bonds and bills can be used to fit a discount curve using the exact same machinery. At present, only fixed-coupon bonds are supported. An even better way to move forward might be to get rate helpers to return cashflows, in which case this class could be used to fit any set of cash flows, not just bonds.
Todo:
add more fitting diagnostics: smoothness, standard deviation, student-t test, etc. Generic smoothness method may be useful for smoothing splines fitting. See Fisher, M., D. Nychka and D. Zervos: "Fitting the term structure of interest rates with smoothing splines." Board of Governors of the Federal Reserve System, Federal Resere Board Working Paper, 95-1.
Todo:
add extrapolation routines
Definition at line 83 of file fittedbonddiscountcurve.hpp.
Constructor & Destructor Documentation
QuantLib::FittedBondDiscountCurve::FittedBondDiscountCurve (Natural settlementDays, const Calendar & calendar, const std::vector< boost::shared_ptr< BondHelper > > & bonds, const DayCounter & dayCounter, const FittingMethod & fittingMethod, Real accuracy = 1.0e-10, Size maxEvaluations = 10000, const Array & guess = Array(), Real simplexLambda = 1.0)
reference date based on current evaluation date
QuantLib::FittedBondDiscountCurve::FittedBondDiscountCurve (const Date & referenceDate, const std::vector< boost::shared_ptr< BondHelper > > & bonds, const DayCounter & dayCounter, const FittingMethod & fittingMethod, Real accuracy = 1.0e-10, Size maxEvaluations = 10000, const Array & guess = Array(), Real simplexLambda = 1.0)
curve reference date fixed for life of curve
QuantLib::FittedBondDiscountCurve::FittedBondDiscountCurve (Natural settlementDays, const Calendar & calendar, const std::vector< boost::shared_ptr< FixedRateBondHelper > > & bonds, const DayCounter & dayCounter, const FittingMethod & fittingMethod, Real accuracy = 1.0e-10, Size maxEvaluations = 10000, const Array & guess = Array(), Real simplexLambda = 1.0)
reference date based on current evaluation date
QuantLib::FittedBondDiscountCurve::FittedBondDiscountCurve (const Date & referenceDate, const std::vector< boost::shared_ptr< FixedRateBondHelper > > & bonds, const DayCounter & dayCounter, const FittingMethod & fittingMethod, Real accuracy = 1.0e-10, Size maxEvaluations = 10000, const Array & guess = Array(), Real simplexLambda = 1.0)
curve reference date fixed for life of curve
Member Function Documentation
DiscountFactor QuantLib::FittedBondDiscountCurve::discountImpl (Time) const [inline, private, virtual]
discount factor calculation
Implements QuantLib::YieldTermStructure.
Definition at line 277 of file fittedbonddiscountcurve.hpp.
References QuantLib::LazyObject::calculate(), QuantLib::FittedBondDiscountCurve::FittingMethod::discountFunction(), fittingMethod_, and QuantLib::FittedBondDiscountCurve::FittingMethod::solution_.
{
        calculate();
        return fittingMethod_->discountFunction(fittingMethod_->solution_, t);
    }
const FittedBondDiscountCurve::FittingMethod & QuantLib::FittedBondDiscountCurve::fitResults () const [inline]
class holding the results of the fit
Definition at line 262 of file fittedbonddiscountcurve.hpp.
References QuantLib::LazyObject::calculate(), and fittingMethod_.
{
        calculate();
        return *fittingMethod_;
    }
Date QuantLib::FittedBondDiscountCurve::maxDate () const [inline, virtual]
the latest date for which the curve can return values
Implements QuantLib::TermStructure.
Definition at line 256 of file fittedbonddiscountcurve.hpp.
References QuantLib::LazyObject::calculate(), and maxDate_.
{
        calculate();
        return maxDate_;
    }
Size QuantLib::FittedBondDiscountCurve::numberOfBonds () const [inline]
total number of bonds used to fit the yield curve
Definition at line 252 of file fittedbonddiscountcurve.hpp.
References bondHelpers_.
{
        return bondHelpers_.size();
    }
void QuantLib::FittedBondDiscountCurve::performCalculations () const [private, virtual]
This method must implement any calculations which must be (re)done in order to calculate the desired results.
Implements QuantLib::LazyObject.
Definition at line 146 of file fittedbonddiscountcurve.cpp.
References bondHelpers_, fittingMethod_, QuantLib::BondFunctions::isTradable(), maxDate_, QuantLib::Date::minDate(), QuantLib::io::ordinal(), QL_REQUIRE, and QuantLib::TermStructure::referenceDate().
{
        QL_REQUIRE(!bondHelpers_.empty(), "no bondHelpers given");
        maxDate_ = Date::minDate();
        Date refDate = referenceDate();
        // double check bond quotes still valid and/or instruments not expired
        for (Size i=0; i<bondHelpers_.size(); ++i) {
            shared_ptr<Bond> bond = bondHelpers_[i]->bond();
            QL_REQUIRE(bondHelpers_[i]->quote()->isValid(),
                       io::ordinal(i+1) << " bond (maturity: " <<
                       bond->maturityDate() << ") has an invalid price quote");
            Date bondSettlement = bond->settlementDate();
            QL_REQUIRE(bondSettlement>=refDate,
                       io::ordinal(i+1) << " bond settlemente date (" <<
                       bondSettlement << ") before curve reference date (" <<
                       refDate << ")");
            QL_REQUIRE(BondFunctions::isTradable(*bond, bondSettlement),
                       io::ordinal(i+1) << " bond non tradable at " <<
                       bondSettlement << " settlement date (maturity"
                       " being " << bond->maturityDate() << ")");
            maxDate_ = std::max(maxDate_, bondHelpers_[i]->latestDate());
            bondHelpers_[i]->setTermStructure(
                                  const_cast<FittedBondDiscountCurve*>(this));
        }
        fittingMethod_->init();
        fittingMethod_->calculate();
    }
void QuantLib::FittedBondDiscountCurve::setup () [inline, private]
Definition at line 272 of file fittedbonddiscountcurve.hpp.
References bondHelpers_, and QuantLib::Observer::registerWith().
{
        for (Size i=0; i<bondHelpers_.size(); ++i)
            registerWith(bondHelpers_[i]);
    }
void QuantLib::FittedBondDiscountCurve::update () [inline, virtual]
This method must be implemented in derived classes. An instance of Observer does not call this method directly: instead, it will be called by the observables the instance registered with when they need to notify any changes.
Reimplemented from QuantLib::LazyObject.
Definition at line 267 of file fittedbonddiscountcurve.hpp.
{
        TermStructure::update();
        LazyObject::update();
    }
Friends And Related Function Documentation
friend class FittingMethod [friend]
Definition at line 86 of file fittedbonddiscountcurve.hpp.
Member Data Documentation
Real QuantLib::FittedBondDiscountCurve::accuracy_ [private]
Definition at line 157 of file fittedbonddiscountcurve.hpp.
std::vector<boost::shared_ptr<BondHelper> > QuantLib::FittedBondDiscountCurve::bondHelpers_ [private]
Definition at line 165 of file fittedbonddiscountcurve.hpp.
Referenced by numberOfBonds(), performCalculations(), and setup().
Clone<FittingMethod> QuantLib::FittedBondDiscountCurve::fittingMethod_ [private]
Definition at line 166 of file fittedbonddiscountcurve.hpp.
Referenced by discountImpl(), fitResults(), performCalculations(), and QuantLib::FittedBondDiscountCurve::FittingMethod::FittingCost::value().
Array QuantLib::FittedBondDiscountCurve::guessSolution_ [private]
Definition at line 163 of file fittedbonddiscountcurve.hpp.
Date QuantLib::FittedBondDiscountCurve::maxDate_ [mutable, private]
Definition at line 164 of file fittedbonddiscountcurve.hpp.
Referenced by maxDate(), and performCalculations().
Size QuantLib::FittedBondDiscountCurve::maxEvaluations_ [private]
Definition at line 159 of file fittedbonddiscountcurve.hpp.
Real QuantLib::FittedBondDiscountCurve::simplexLambda_ [private]
Definition at line 161 of file fittedbonddiscountcurve.hpp.
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/yield/fittedbonddiscountcurve.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/yield/fittedbonddiscountcurve.cpp