QuantLib: QuantLib::CPICapFloorTermPriceSurface Class Reference
QuantLib::CPICapFloorTermPriceSurface Class Reference
Provides cpi cap/floor prices by interpolation and put/call parity (not cap/floor/swap* parity).
#include <cpicapfloortermpricesurface.hpp>
Public Member Functions
CPICapFloorTermPriceSurface (Real nominal, Real baseRate, const Period &observationLag, const Calendar &cal, const BusinessDayConvention &bdc, const DayCounter &dc, const Handle< ZeroInflationIndex > &zii, const Handle< YieldTermStructure > &yts, const std::vector< Rate > &cStrikes, const std::vector< Rate > &fStrikes, const std::vector< Period > &cfMaturities, const Matrix &cPrice, const Matrix &fPrice)
Handle< ZeroInflationIndex > zeroInflationIndex () const
is based on
virtual std::vector< Rate > strikes () const
virtual std::vector< Rate > capStrikes () const
virtual std::vector< Rate > floorStrikes () const
virtual std::vector< Period > maturities () const
virtual const Matrix & capPrices () const
virtual const Matrix & floorPrices () const
virtual Rate minStrike () const
virtual Rate maxStrike () const
virtual Date minDate () const
virtual Date maxDate () const
the latest date for which the curve can return values
virtual Date cpiOptionDateFromTenor (const Period &p) const
InflationTermStructure interface
Period observationLag () const
Date baseDate () const
minimum (base) date
virtual Real nominal () const
inspectors
virtual BusinessDayConvention businessDayConvention () const
virtual Real price (const Period &d, Rate k) const
virtual Real capPrice (const Period &d, Rate k) const
virtual Real floorPrice (const Period &d, Rate k) const
virtual Real price (const Date &d, Rate k) const =0
virtual Real capPrice (const Date &d, Rate k) const =0
virtual Real floorPrice (const Date &d, Rate k) const =0
Protected Member Functions
virtual bool checkStrike (Rate K)
virtual bool checkMaturity (const Date &d)
Protected Attributes
Handle< ZeroInflationIndex > zii_
std::vector< Rate > cStrikes_
std::vector< Rate > fStrikes_
std::vector< Period > cfMaturities_
std::vector< Real > cfMaturityTimes_
Matrix cPrice_
Matrix fPrice_
std::vector< Rate > cfStrikes_
Private Attributes
Real nominal_
BusinessDayConvention bdc_
Detailed Description
Provides cpi cap/floor prices by interpolation and put/call parity (not cap/floor/swap* parity).
The inflation index MUST contain a ZeroInflationTermStructure as this is used to create ATM. Unlike YoY price surfaces we assume that 1) an ATM ZeroInflationTermStructure is available and 2) that it is safe to use it. This is supported by the fact that no stripping is required for CPI cap/floors as they only give one flow.
cpi cap/floors have a single (one) flow (unlike nominal caps) because they observe cumulative inflation up to their maturity. Options are on CPI(T)/CPI(0) but strikes are quoted for yearly average inflation, so require transformation via (1+quote)^T to obtain actual strikes. These are consistent with ZCIIS quoting conventions.
The observationLag is that for the referenced instrument prices. Strikes are as-quoted not as-used.
Definition at line 68 of file cpicapfloortermpricesurface.hpp.
Constructor & Destructor Documentation
QuantLib::CPICapFloorTermPriceSurface::CPICapFloorTermPriceSurface (Real nominal, Real baseRate, const Period & observationLag, const Calendar & cal, const BusinessDayConvention & bdc, const DayCounter & dc, const Handle< ZeroInflationIndex > & zii, const Handle< YieldTermStructure > & yts, const std::vector< Rate > & cStrikes, const std::vector< Rate > & fStrikes, const std::vector< Period > & cfMaturities, const Matrix & cPrice, const Matrix & fPrice)
Definition at line 27 of file cpicapfloortermpricesurface.cpp.
References cfMaturities_, cfStrikes_, QuantLib::Matrix::columns(), cPrice_, cStrikes_, QuantLib::Days, QuantLib::Handle< T >::empty(), fPrice_, fStrikes_, QuantLib::InflationTermStructure::nominalTermStructure(), QL_REQUIRE, QuantLib::Matrix::rows(), and zii_.
    : InflationTermStructure(0, cal, baseRate, observationLag, zii->frequency(),
                             zii->interpolated(), yts, dc),
      zii_(zii), cStrikes_(cStrikes), fStrikes_(fStrikes),
      cfMaturities_(cfMaturities), cPrice_(cPrice), fPrice_(fPrice), bdc_(bdc) {
          // does the index have a TS?
          QL_REQUIRE(!zii_->zeroInflationTermStructure().empty(),"ZITS missing from index");
          QL_REQUIRE(!this->nominalTermStructure().empty(),"nominal TS missing");
        // data consistency checking, enough data?
        QL_REQUIRE(fStrikes_.size() > 1, "not enough floor strikes");
        QL_REQUIRE(cStrikes_.size() > 1, "not enough cap strikes");
        QL_REQUIRE(cfMaturities_.size() > 1, "not enough maturities");
        QL_REQUIRE(fStrikes_.size() == fPrice.rows(),
                   "floor strikes vs floor price rows not equal");
        QL_REQUIRE(cStrikes_.size() == cPrice.rows(),
                   "cap strikes vs cap price rows not equal");
        QL_REQUIRE(cfMaturities_.size() == fPrice.columns(),
                   "maturities vs floor price columns not equal");
        QL_REQUIRE(cfMaturities_.size() == cPrice.columns(),
                   "maturities vs cap price columns not equal");
        // data has correct properties (positive, monotonic)?
        for(Size j = 0; j <cfMaturities_.size(); j++) {
            QL_REQUIRE( cfMaturities[j] > Period(0,Days), "non-positive maturities");
            if(j>0) {
                QL_REQUIRE( cfMaturities[j] > cfMaturities[j-1],
                            "non-increasing maturities");
            }
            for(Size i = 0; i <fPrice_.rows(); i++) {
                QL_REQUIRE( fPrice_[i][j] > 0.0,
                            "non-positive floor price: " << fPrice_[i][j] );
                if(i>0) {
                    QL_REQUIRE( fPrice_[i][j] >= fPrice_[i-1][j],
                                "non-increasing floor prices");
                }
            }
            for(Size i = 0; i <cPrice_.rows(); i++) {
                QL_REQUIRE( cPrice_[i][j] > 0.0,
                            "non-positive cap price: " << cPrice_[i][j] );
                if(i>0) {
                    QL_REQUIRE( cPrice_[i][j] <= cPrice_[i-1][j],
                                "non-decreasing cap prices: "
                               << cPrice_[i][j] << " then " << cPrice_[i-1][j]);
                }
            }
        }
        // Get the set of strikes, noting that repeats, overlaps are
        // expected between caps and floors but that no overlap in the
        // output is allowed so no repeats or overlaps are used
        cfStrikes_ = std::vector<Rate>();
        for(Size i = 0; i <fStrikes_.size(); i++)
            cfStrikes_.push_back( fStrikes[i] );
        Real eps = 0.0000001;
        Rate maxFstrike = fStrikes_.back();
        for(Size i = 0; i < cStrikes_.size(); i++) {
            Rate k = cStrikes[i];
            if (k > maxFstrike + eps) cfStrikes_.push_back(k);
        }
        // final consistency checking
        QL_REQUIRE(cfStrikes_.size() > 2, "overall not enough strikes");
        for (Size i = 1; i < cfStrikes_.size(); i++)
            QL_REQUIRE( cfStrikes_[i] > cfStrikes_[i-1],
                        "cfStrikes not increasing");
    }
Member Function Documentation
Date QuantLib::CPICapFloorTermPriceSurface::baseDate () const [inline, virtual]
minimum (base) date
Important in inflation since it starts before nominal reference date. Changes depending whether index is interpolated or not. When interpolated the base date is just observation lag before nominal. When not interpolated it is the beginning of the relevant period (hence it is easy to create interpolated fixings from a not-interpolated curve because interpolation, usually, of fixings is forward looking).
Implements QuantLib::InflationTermStructure.
Definition at line 368 of file cpicapfloortermpricesurface.hpp.
References zeroInflationIndex().
{
        return zeroInflationIndex()->zeroInflationTermStructure()->baseDate();
    }
BusinessDayConvention QuantLib::CPICapFloorTermPriceSurface::businessDayConvention () const [inline, virtual]
Definition at line 377 of file cpicapfloortermpricesurface.hpp.
References bdc_.
Referenced by cpiOptionDateFromTenor().
{
        return bdc_;
    }
Real QuantLib::CPICapFloorTermPriceSurface::capPrice (const Period & d, Rate k) const [virtual]
Definition at line 121 of file cpicapfloortermpricesurface.cpp.
References cpiOptionDateFromTenor().
{
        return this->capPrice(cpiOptionDateFromTenor(d), k);
    }
virtual Real QuantLib::CPICapFloorTermPriceSurface::capPrice (const Date & d, Rate k) const [pure virtual]
Implemented in QuantLib::InterpolatedCPICapFloorTermPriceSurface< Interpolator2D >.
virtual const Matrix& QuantLib::CPICapFloorTermPriceSurface::capPrices () const [inline, virtual]
Definition at line 120 of file cpicapfloortermpricesurface.hpp.
References cPrice_.
{ return cPrice_; }
virtual std::vector<Rate> QuantLib::CPICapFloorTermPriceSurface::capStrikes () const [inline, virtual]
Definition at line 116 of file cpicapfloortermpricesurface.hpp.
References cStrikes_.
{return cStrikes_;}
virtual bool QuantLib::CPICapFloorTermPriceSurface::checkMaturity (const Date & d) [inline, protected, virtual]
Definition at line 136 of file cpicapfloortermpricesurface.hpp.
References maxDate(), and minDate().
{
            return ( minDate() <= d && d <= maxDate() );
        }
virtual bool QuantLib::CPICapFloorTermPriceSurface::checkStrike (Rate K) [inline, protected, virtual]
Definition at line 133 of file cpicapfloortermpricesurface.hpp.
References maxStrike(), and minStrike().
{
            return ( minStrike() <= K && K <= maxStrike() );
        }
Date QuantLib::CPICapFloorTermPriceSurface::cpiOptionDateFromTenor (const Period & p) const [virtual]
Definition at line 110 of file cpicapfloortermpricesurface.cpp.
References businessDayConvention(), QuantLib::TermStructure::calendar(), and QuantLib::TermStructure::referenceDate().
Referenced by capPrice(), floorPrice(), and price().
    {
        return Date(calendar().adjust(referenceDate() + p, businessDayConvention()));
    }
Real QuantLib::CPICapFloorTermPriceSurface::floorPrice (const Period & d, Rate k) const [virtual]
Definition at line 126 of file cpicapfloortermpricesurface.cpp.
References cpiOptionDateFromTenor().
{
        return this->floorPrice(cpiOptionDateFromTenor(d), k);
    }
virtual Real QuantLib::CPICapFloorTermPriceSurface::floorPrice (const Date & d, Rate k) const [pure virtual]
Implemented in QuantLib::InterpolatedCPICapFloorTermPriceSurface< Interpolator2D >.
virtual const Matrix& QuantLib::CPICapFloorTermPriceSurface::floorPrices () const [inline, virtual]
Definition at line 121 of file cpicapfloortermpricesurface.hpp.
References fPrice_.
{ return fPrice_; }
virtual std::vector<Rate> QuantLib::CPICapFloorTermPriceSurface::floorStrikes () const [inline, virtual]
Definition at line 117 of file cpicapfloortermpricesurface.hpp.
References fStrikes_.
{return fStrikes_;}
virtual std::vector<Period> QuantLib::CPICapFloorTermPriceSurface::maturities () const [inline, virtual]
Definition at line 118 of file cpicapfloortermpricesurface.hpp.
References cfMaturities_.
{return cfMaturities_;}
virtual Date QuantLib::CPICapFloorTermPriceSurface::maxDate () const [inline, virtual]
the latest date for which the curve can return values
Implements QuantLib::TermStructure.
Definition at line 126 of file cpicapfloortermpricesurface.hpp.
References cfMaturities_, and QuantLib::TermStructure::referenceDate().
Referenced by checkMaturity().
{return referenceDate()+cfMaturities_.back();}
virtual Rate QuantLib::CPICapFloorTermPriceSurface::maxStrike () const [inline, virtual]
Definition at line 124 of file cpicapfloortermpricesurface.hpp.
References cfStrikes_.
Referenced by checkStrike().
{return cfStrikes_.back();};
virtual Date QuantLib::CPICapFloorTermPriceSurface::minDate () const [inline, virtual]
Definition at line 125 of file cpicapfloortermpricesurface.hpp.
References cfMaturities_, and QuantLib::TermStructure::referenceDate().
Referenced by checkMaturity().
{return referenceDate()+cfMaturities_.front();}// \TODO deal with index interpolation
virtual Rate QuantLib::CPICapFloorTermPriceSurface::minStrike () const [inline, virtual]
Definition at line 123 of file cpicapfloortermpricesurface.hpp.
References cfStrikes_.
Referenced by checkStrike().
{return cfStrikes_.front();};
Real QuantLib::CPICapFloorTermPriceSurface::nominal () const [inline, virtual]
inspectors
Note:
you don't know if price() is a cap or a floor without checking the ZeroInflation ATM level.
Definition at line 372 of file cpicapfloortermpricesurface.hpp.
References nominal_.
{
        return nominal_;
    }
Period QuantLib::CPICapFloorTermPriceSurface::observationLag () const [inline, virtual]
The TS observes with a lag that is usually different from the availability lag of the index. An inflation rate is given, by default, for the maturity requested assuming this lag.
Reimplemented from QuantLib::InflationTermStructure.
Definition at line 364 of file cpicapfloortermpricesurface.hpp.
References zeroInflationIndex().
{
        return zeroInflationIndex()->zeroInflationTermStructure()->observationLag();
    }
Real QuantLib::CPICapFloorTermPriceSurface::price (const Period & d, Rate k) const [virtual]
Warning:
you MUST remind the compiler in any descendants with the using:: mechanism because you overload the names remember that the strikes use the quoting convention
Definition at line 116 of file cpicapfloortermpricesurface.cpp.
References cpiOptionDateFromTenor().
{
        return this->price(cpiOptionDateFromTenor(d), k);
    }
virtual Real QuantLib::CPICapFloorTermPriceSurface::price (const Date & d, Rate k) const [pure virtual]
Implemented in QuantLib::InterpolatedCPICapFloorTermPriceSurface< Interpolator2D >.
virtual std::vector<Rate> QuantLib::CPICapFloorTermPriceSurface::strikes () const [inline, virtual]
Definition at line 115 of file cpicapfloortermpricesurface.hpp.
References cfStrikes_.
{return cfStrikes_;}
Handle<ZeroInflationIndex> QuantLib::CPICapFloorTermPriceSurface::zeroInflationIndex () const [inline]
is based on
Definition at line 91 of file cpicapfloortermpricesurface.hpp.
References zii_.
Referenced by baseDate(), and observationLag().
{ return zii_; }
Member Data Documentation
BusinessDayConvention QuantLib::CPICapFloorTermPriceSurface::bdc_ [private]
Definition at line 154 of file cpicapfloortermpricesurface.hpp.
Referenced by businessDayConvention().
std::vector<Period> QuantLib::CPICapFloorTermPriceSurface::cfMaturities_ [protected]
Definition at line 146 of file cpicapfloortermpricesurface.hpp.
Referenced by CPICapFloorTermPriceSurface(), maturities(), maxDate(), and minDate().
std::vector<Real> QuantLib::CPICapFloorTermPriceSurface::cfMaturityTimes_ [mutable, protected]
Definition at line 147 of file cpicapfloortermpricesurface.hpp.
std::vector<Rate> QuantLib::CPICapFloorTermPriceSurface::cfStrikes_ [mutable, protected]
Definition at line 151 of file cpicapfloortermpricesurface.hpp.
Referenced by CPICapFloorTermPriceSurface(), maxStrike(), minStrike(), and strikes().
Matrix QuantLib::CPICapFloorTermPriceSurface::cPrice_ [protected]
Definition at line 148 of file cpicapfloortermpricesurface.hpp.
Referenced by capPrices(), and CPICapFloorTermPriceSurface().
std::vector<Rate> QuantLib::CPICapFloorTermPriceSurface::cStrikes_ [protected]
Definition at line 144 of file cpicapfloortermpricesurface.hpp.
Referenced by capStrikes(), and CPICapFloorTermPriceSurface().
Matrix QuantLib::CPICapFloorTermPriceSurface::fPrice_ [protected]
Definition at line 149 of file cpicapfloortermpricesurface.hpp.
Referenced by CPICapFloorTermPriceSurface(), and floorPrices().
std::vector<Rate> QuantLib::CPICapFloorTermPriceSurface::fStrikes_ [protected]
Definition at line 145 of file cpicapfloortermpricesurface.hpp.
Referenced by CPICapFloorTermPriceSurface(), and floorStrikes().
Real QuantLib::CPICapFloorTermPriceSurface::nominal_ [private]
Definition at line 153 of file cpicapfloortermpricesurface.hpp.
Referenced by nominal().
Handle<ZeroInflationIndex> QuantLib::CPICapFloorTermPriceSurface::zii_ [protected]
Definition at line 142 of file cpicapfloortermpricesurface.hpp.
Referenced by CPICapFloorTermPriceSurface(), and zeroInflationIndex().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/inflation/cpicapfloortermpricesurface.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/inflation/cpicapfloortermpricesurface.cpp