QuantLib: QuantLib::TermStructure Class Reference
QuantLib::TermStructure Class Reference
Basic term-structure functionality.
#include <termstructure.hpp>
Public Member Functions
virtual ~TermStructure ()
Constructors
There are three ways in which a term structure can keep track of its reference date. The first is that such date is fixed; the second is that it is determined by advancing the current date of a given number of business days; and the third is that it is based on the reference date of some other structure.
In the first case, the constructor taking a date is to be used; the default implementation of referenceDate() will then return such date. In the second case, the constructor taking a number of days and a calendar is to be used; referenceDate() will return a date calculated based on the current evaluation date, and the term structure and its observers will be notified when the evaluation date changes. In the last case, the referenceDate() method must be overridden in derived classes so that it fetches and return the appropriate date.
TermStructure (const DayCounter &dc=DayCounter())
default constructor
TermStructure (const Date &referenceDate, const Calendar &calendar=Calendar(), const DayCounter &dc=DayCounter())
initialize with a fixed reference date
TermStructure (Natural settlementDays, const Calendar &, const DayCounter &dc=DayCounter())
calculate the reference date based on the global evaluation date
Dates and Time
virtual DayCounter dayCounter () const
the day counter used for date/time conversion
Time timeFromReference (const Date &date) const
date/time conversion
virtual Date maxDate () const =0
the latest date for which the curve can return values
virtual Time maxTime () const
the latest time for which the curve can return values
virtual const Date & referenceDate () const
the date at which discount = 1.0 and/or variance = 0.0
virtual Calendar calendar () const
the calendar used for reference and/or option date calculation
virtual Natural settlementDays () const
the settlementDays used for reference date calculation
Observer interface
void update ()
Protected Member Functions
void checkRange (const Date &d, bool extrapolate) const
date-range check
void checkRange (Time t, bool extrapolate) const
time-range check
Protected Attributes
bool moving_
bool updated_
Calendar calendar_
Private Attributes
Date referenceDate_
Natural settlementDays_
DayCounter dayCounter_
Detailed Description
Basic term-structure functionality.
Definition at line 37 of file termstructure.hpp.
Constructor & Destructor Documentation
QuantLib::TermStructure::TermStructure (const DayCounter & dc = DayCounter())
default constructor
Warning:
term structures initialized by means of this constructor must manage their own reference date by overriding the referenceDate() method.
Definition at line 25 of file termstructure.cpp.
    : moving_(false),
      updated_(true),
      settlementDays_(Null<Natural>()),
      dayCounter_(dc) {}
QuantLib::TermStructure::TermStructure (const Date & referenceDate, const Calendar & calendar = Calendar(), const DayCounter & dc = DayCounter())
initialize with a fixed reference date
Definition at line 31 of file termstructure.cpp.
    : moving_(false), updated_(true), calendar_(cal),
      referenceDate_(referenceDate),
      settlementDays_(Null<Natural>()),
      dayCounter_(dc) {}
QuantLib::TermStructure::TermStructure (Natural settlementDays, const Calendar & cal, const DayCounter & dc = DayCounter())
calculate the reference date based on the global evaluation date
Definition at line 39 of file termstructure.cpp.
References QuantLib::Singleton< Settings >::instance(), and QuantLib::Observer::registerWith().
    : moving_(true), updated_(false), calendar_(cal),
      settlementDays_(settlementDays),
      dayCounter_(dc) {
        registerWith(Settings::instance().evaluationDate());
    }
virtual QuantLib::TermStructure::~TermStructure () [inline, virtual]
Definition at line 77 of file termstructure.hpp.
{}
Member Function Documentation
Calendar QuantLib::TermStructure::calendar () const [inline, virtual]
the calendar used for reference and/or option date calculation
Reimplemented in QuantLib::PiecewiseZeroSpreadedTermStructure, QuantLib::SwaptionVolatilityCube, QuantLib::ForwardSpreadedTermStructure, QuantLib::ZeroSpreadedTermStructure, QuantLib::SabrVolSurface, QuantLib::QuantoTermStructure, QuantLib::ImpliedTermStructure, QuantLib::SpreadedOptionletVolatility, QuantLib::DriftTermStructure, QuantLib::FactorSpreadedHazardRateCurve, QuantLib::SpreadedHazardRateCurve, QuantLib::LocalVolCurve, and QuantLib::SpreadedSwaptionVolatility.
Definition at line 130 of file termstructure.hpp.
References calendar_.
Referenced by QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::calculateYoYTermStructure(), QuantLib::CPICapFloorTermPriceSurface::cpiOptionDateFromTenor(), QuantLib::VolatilityTermStructure::optionDateFromTenor(), QuantLib::CallableBondVolatilityStructure::optionDateFromTenor(), and referenceDate().
{
        return calendar_;
    }
void QuantLib::TermStructure::checkRange (const Date & d, bool extrapolate) const [protected]
date-range check
Reimplemented in QuantLib::InflationTermStructure.
Definition at line 63 of file termstructure.cpp.
References QuantLib::Extrapolator::allowsExtrapolation(), maxDate(), QL_REQUIRE, and referenceDate().
Referenced by QuantLib::BlackAtmVolCurve::atmVariance(), QuantLib::BlackAtmVolCurve::atmVol(), QuantLib::BlackVolTermStructure::blackForwardVariance(), QuantLib::BlackVolTermStructure::blackForwardVol(), QuantLib::BlackVolTermStructure::blackVariance(), QuantLib::BlackVolTermStructure::blackVol(), QuantLib::DefaultProbabilityTermStructure::defaultDensity(), QuantLib::YieldTermStructure::discount(), QuantLib::YieldTermStructure::forwardRate(), QuantLib::LocalVolTermStructure::localVol(), QuantLib::BlackVolSurface::smileSection(), QuantLib::OptionletVolatilityStructure::smileSection(), QuantLib::SwaptionVolatilityStructure::smileSection(), QuantLib::DefaultProbabilityTermStructure::survivalProbability(), QuantLib::CapFloorTermVolatilityStructure::volatility(), QuantLib::OptionletVolatilityStructure::volatility(), and QuantLib::SwaptionVolatilityStructure::volatility().
{
        QL_REQUIRE(d >= referenceDate(),
                   "date (" << d << ") before reference date (" <<
                   referenceDate() << ")");
        QL_REQUIRE(extrapolate || allowsExtrapolation() || d <= maxDate(),
                   "date (" << d << ") is past max curve date ("
                            << maxDate() << ")");
    }
void QuantLib::TermStructure::checkRange (Time t, bool extrapolate) const [protected]
time-range check
Reimplemented in QuantLib::InflationTermStructure.
Definition at line 73 of file termstructure.cpp.
References QuantLib::Extrapolator::allowsExtrapolation(), QuantLib::close_enough(), maxTime(), and QL_REQUIRE.
{
        QL_REQUIRE(t >= 0.0,
                   "negative time (" << t << ") given");
        QL_REQUIRE(extrapolate || allowsExtrapolation()
                   || t <= maxTime() || close_enough(t, maxTime()),
                   "time (" << t << ") is past max curve time ("
                            << maxTime() << ")");
    }
DayCounter QuantLib::TermStructure::dayCounter () const [inline, virtual]
the day counter used for date/time conversion
Reimplemented in QuantLib::BlackVarianceSurface, QuantLib::LocalVolSurface, QuantLib::LocalConstantVol, QuantLib::BlackVarianceCurve, QuantLib::PiecewiseZeroSpreadedTermStructure, QuantLib::ZeroSpreadedTermStructure, QuantLib::CallableBondConstantVolatility, QuantLib::ExtendedBlackVarianceSurface, QuantLib::QuantoTermStructure, QuantLib::ImpliedTermStructure, QuantLib::SwaptionVolatilityCube, QuantLib::ForwardSpreadedTermStructure, QuantLib::SabrVolSurface, QuantLib::LocalVolCurve, QuantLib::ImpliedVolTermStructure, QuantLib::DriftTermStructure, QuantLib::ExtendedBlackVarianceCurve, QuantLib::SpreadedOptionletVolatility, QuantLib::FactorSpreadedHazardRateCurve, QuantLib::SpreadedHazardRateCurve, QuantLib::CapletVarianceCurve, and QuantLib::SpreadedSwaptionVolatility.
Definition at line 122 of file termstructure.hpp.
References dayCounter_.
Referenced by QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::calculateYoYTermStructure(), QuantLib::CallableBondVolatilityStructure::convertDates(), QuantLib::MultiplicativePriceSeasonality::correctYoYRate(), QuantLib::MultiplicativePriceSeasonality::correctZeroRate(), QuantLib::YieldTermStructure::forwardRate(), QuantLib::FlatForward::performCalculations(), QuantLib::CommodityCurve::setPrices(), QuantLib::ConstantOptionletVolatility::smileSectionImpl(), QuantLib::ConstantSwaptionVolatility::smileSectionImpl(), QuantLib::SwaptionVolatilityMatrix::smileSectionImpl(), QuantLib::YoYOptionletVolatilitySurface::timeFromBase(), QuantLib::CPIVolatilitySurface::timeFromBase(), timeFromReference(), and QuantLib::YieldTermStructure::zeroRate().
{
        return dayCounter_;
    }
virtual Date QuantLib::TermStructure::maxDate () const [pure virtual]
the latest date for which the curve can return values
Implemented in QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >, QuantLib::ConstantYoYOptionletVolatility, QuantLib::PiecewiseYoYOptionletVolatilityCurve< Interpolator, Bootstrap, Traits >, QuantLib::FittedBondDiscountCurve, QuantLib::CPICapFloorTermPriceSurface, QuantLib::SwaptionVolatilityMatrix, QuantLib::CapFloorTermVolCurve, QuantLib::CapFloorTermVolSurface, QuantLib::PiecewiseYoYInflationCurve< Interpolator, Bootstrap, Traits >, QuantLib::PiecewiseZeroInflationCurve< Interpolator, Bootstrap, Traits >, QuantLib::InterpolatedYoYOptionletVolatilityCurve< Interpolator1D >, QuantLib::FlatForward, QuantLib::InterpolatedYoYOptionletVolatilityCurve< Interpolator >, QuantLib::InterpolatedZeroCurve< Interpolator >, QuantLib::InterpolatedHazardRateCurve< Interpolator >, QuantLib::InterpolatedDiscountCurve< Interpolator >, QuantLib::InterpolatedForwardCurve< Interpolator >, QuantLib::KInterpolatedYoYOptionletVolatilitySurface< Interpolator1D >, QuantLib::AbcdAtmVolCurve, QuantLib::InterpolatedDefaultDensityCurve< Interpolator >, QuantLib::BlackVarianceSurface, QuantLib::ConstantSwaptionVolatility, QuantLib::CommodityCurve, QuantLib::ConstantOptionletVolatility, QuantLib::InterpolatedYoYInflationCurve< Interpolator >, QuantLib::ConstantCapFloorTermVolatility, QuantLib::PiecewiseZeroSpreadedTermStructure, QuantLib::BlackConstantVol, QuantLib::LocalVolSurface, QuantLib::ZeroSpreadedTermStructure, QuantLib::InterpolatedZeroInflationCurve< Interpolator >, QuantLib::LocalConstantVol, QuantLib::QuantoTermStructure, QuantLib::BlackVarianceCurve, QuantLib::FlatHazardRate, QuantLib::ImpliedTermStructure, QuantLib::CallableBondConstantVolatility, QuantLib::ExtendedBlackVarianceSurface, QuantLib::SwaptionVolatilityCube, QuantLib::ForwardSpreadedTermStructure, QuantLib::SabrVolSurface, QuantLib::LocalVolCurve, QuantLib::DriftTermStructure, QuantLib::InterpolatedSurvivalProbabilityCurve< Interpolator >, QuantLib::FactorSpreadedHazardRateCurve, QuantLib::SpreadedHazardRateCurve, QuantLib::ImpliedVolTermStructure, QuantLib::ConstantCPIVolatility, QuantLib::ExtendedBlackVarianceCurve, QuantLib::SpreadedOptionletVolatility, QuantLib::anonymous_namespace{analyticbsmhullwhiteengine.cpp}::ShiftedBlackVolTermStructure, QuantLib::StrippedOptionletAdapter, QuantLib::CapletVarianceCurve, QuantLib::FdmAffineModelTermStructure, and QuantLib::SpreadedSwaptionVolatility.
Referenced by checkRange(), QuantLib::InflationTermStructure::checkRange(), QuantLib::YoYOptionletVolatilitySurface::checkRange(), QuantLib::CPIVolatilitySurface::checkRange(), and maxTime().
Time QuantLib::TermStructure::maxTime () const [inline, virtual]
the latest time for which the curve can return values
Reimplemented in QuantLib::ZeroSpreadedTermStructure, QuantLib::SwaptionVolatilityCube, QuantLib::ForwardSpreadedTermStructure, QuantLib::SabrVolSurface, QuantLib::FactorSpreadedHazardRateCurve, QuantLib::SpreadedHazardRateCurve, QuantLib::SpreadedOptionletVolatility, and QuantLib::SpreadedSwaptionVolatility.
Definition at line 126 of file termstructure.hpp.
References maxDate(), and timeFromReference().
Referenced by checkRange(), QuantLib::InflationTermStructure::checkRange(), QuantLib::YoYOptionletVolatilitySurface::checkRange(), and QuantLib::CPIVolatilitySurface::checkRange().
{
        return timeFromReference(maxDate());
    }
const Date & QuantLib::TermStructure::referenceDate () const [virtual]
the date at which discount = 1.0 and/or variance = 0.0
Reimplemented in QuantLib::PiecewiseZeroSpreadedTermStructure, QuantLib::ZeroSpreadedTermStructure, QuantLib::LocalVolSurface, QuantLib::QuantoTermStructure, QuantLib::SwaptionVolatilityCube, QuantLib::ForwardSpreadedTermStructure, QuantLib::SabrVolSurface, QuantLib::DriftTermStructure, QuantLib::SpreadedOptionletVolatility, QuantLib::FactorSpreadedHazardRateCurve, QuantLib::SpreadedHazardRateCurve, QuantLib::SpreadedSwaptionVolatility, and QuantLib::LocalVolCurve.
Definition at line 48 of file termstructure.cpp.
References QuantLib::Calendar::advance(), calendar(), QuantLib::Days, QuantLib::Settings::evaluationDate(), QuantLib::Singleton< Settings >::instance(), referenceDate_, settlementDays(), and updated_.
Referenced by QuantLib::CapFloor::atmRate(), QuantLib::YoYInflationCapFloor::atmRate(), QuantLib::YoYOptionletVolatilitySurface::baseDate(), QuantLib::CPIVolatilitySurface::baseDate(), QuantLib::ImpliedVolTermStructure::blackVarianceImpl(), QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::calculateYoYTermStructure(), QuantLib::SwaptionVolatilityDiscrete::checkOptionDates(), checkRange(), QuantLib::CPICapFloorTermPriceSurface::cpiOptionDateFromTenor(), QuantLib::ImpliedTermStructure::discountImpl(), QuantLib::ZeroInflationTraits::initialDate(), QuantLib::Discount::initialDate(), QuantLib::SurvivalProbability::initialDate(), QuantLib::YoYInflationTraits::initialDate(), QuantLib::HazardRate::initialDate(), QuantLib::ZeroYield::initialDate(), QuantLib::DefaultDensity::initialDate(), QuantLib::ForwardRate::initialDate(), QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::intersect(), QuantLib::CallableBondVolatilityStructure::maxBondLength(), QuantLib::CPICapFloorTermPriceSurface::maxDate(), QuantLib::YoYCapFloorTermPriceSurface::maxMaturity(), QuantLib::CPICapFloorTermPriceSurface::minDate(), QuantLib::YoYCapFloorTermPriceSurface::minMaturity(), QuantLib::VolatilityTermStructure::optionDateFromTenor(), QuantLib::InterestRateVolSurface::optionDateFromTenor(), QuantLib::CallableBondVolatilityStructure::optionDateFromTenor(), QuantLib::FittedBondDiscountCurve::performCalculations(), QuantLib::DefaultProbabilityTermStructure::setJumps(), QuantLib::YieldTermStructure::setJumps(), QuantLib::ConstantOptionletVolatility::smileSectionImpl(), QuantLib::ConstantSwaptionVolatility::smileSectionImpl(), timeFromReference(), QuantLib::DefaultProbabilityTermStructure::update(), QuantLib::YieldTermStructure::update(), QuantLib::YoYCapFloorTermPriceSurface::yoyOptionDateFromTenor(), and QuantLib::YieldTermStructure::zeroRate().
{
        if (!updated_) {
            Date today = Settings::instance().evaluationDate();
            referenceDate_ = calendar().advance(today, settlementDays(), Days);
            updated_ = true;
        }
        return referenceDate_;
    }
Natural QuantLib::TermStructure::settlementDays () const [inline, virtual]
the settlementDays used for reference date calculation
Reimplemented in QuantLib::SwaptionVolatilityCube, QuantLib::ForwardSpreadedTermStructure, QuantLib::PiecewiseZeroSpreadedTermStructure, QuantLib::ZeroSpreadedTermStructure, QuantLib::SabrVolSurface, QuantLib::QuantoTermStructure, QuantLib::ImpliedTermStructure, QuantLib::SpreadedOptionletVolatility, QuantLib::DriftTermStructure, and QuantLib::SpreadedSwaptionVolatility.
Definition at line 134 of file termstructure.hpp.
References QL_REQUIRE, and settlementDays_.
Referenced by referenceDate().
{
        QL_REQUIRE(settlementDays_!=Null<Natural>(),
                   "settlement days not provided for this instance");
        return settlementDays_;
    }
Time QuantLib::TermStructure::timeFromReference (const Date & date) const [inline]
date/time conversion
Definition at line 140 of file termstructure.hpp.
References dayCounter(), referenceDate(), and QuantLib::DayCounter::yearFraction().
Referenced by QuantLib::EquityFXVolSurface::atmForwardVariance(), QuantLib::EquityFXVolSurface::atmForwardVol(), QuantLib::BlackAtmVolCurve::atmVariance(), QuantLib::BlackAtmVolCurve::atmVol(), QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::atmYoYSwapRate(), QuantLib::CommodityCurve::basisOfPrice(), QuantLib::BlackVolTermStructure::blackForwardVariance(), QuantLib::BlackVolTermStructure::blackForwardVol(), QuantLib::BlackVolTermStructure::blackVariance(), QuantLib::OptionletVolatilityStructure::blackVariance(), QuantLib::SwaptionVolatilityStructure::blackVariance(), QuantLib::BlackVarianceCurve::BlackVarianceCurve(), QuantLib::BlackVarianceSurface::BlackVarianceSurface(), QuantLib::BlackVolTermStructure::blackVol(), QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::calculateYoYTermStructure(), QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::capPrice(), QuantLib::InflationTermStructure::checkRange(), QuantLib::YoYOptionletVolatilitySurface::checkRange(), QuantLib::CPIVolatilitySurface::checkRange(), QuantLib::CallableBondVolatilityStructure::checkRange(), QuantLib::CallableBondVolatilityStructure::convertDates(), QuantLib::DefaultProbabilityTermStructure::defaultDensity(), QuantLib::YieldTermStructure::discount(), QuantLib::ExtendedBlackVarianceCurve::ExtendedBlackVarianceCurve(), QuantLib::ExtendedBlackVarianceSurface::ExtendedBlackVarianceSurface(), QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::floorPrice(), QuantLib::YieldTermStructure::forwardRate(), QuantLib::DefaultProbabilityTermStructure::hazardRate(), QuantLib::AbcdAtmVolCurve::initializeOptionDatesAndTimes(), QuantLib::CapFloorTermVolCurve::initializeOptionDatesAndTimes(), QuantLib::CapFloorTermVolSurface::initializeOptionDatesAndTimes(), QuantLib::SwaptionVolatilityDiscrete::initializeOptionTimes(), QuantLib::InterpolatedYoYInflationCurve< Interpolator >::InterpolatedYoYInflationCurve(), QuantLib::InterpolatedYoYOptionletVolatilityCurve< Interpolator1D >::InterpolatedYoYOptionletVolatilityCurve(), QuantLib::InterpolatedZeroInflationCurve< Interpolator >::InterpolatedZeroInflationCurve(), QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::intersect(), QuantLib::LocalVolTermStructure::localVol(), QuantLib::SwaptionVolatilityMatrix::locate(), QuantLib::CallableBondVolatilityStructure::maxBondLength(), maxTime(), QuantLib::CommodityCurve::price(), QuantLib::SabrVolSurface::SabrVolSurface(), QuantLib::DefaultProbabilityTermStructure::setJumps(), QuantLib::YieldTermStructure::setJumps(), QuantLib::BlackVolSurface::smileSection(), QuantLib::SwaptionVolCube2::smileSectionImpl(), QuantLib::OptionletVolatilityStructure::smileSectionImpl(), QuantLib::SwaptionVolatilityStructure::smileSectionImpl(), QuantLib::SwaptionVolCube1::spreadVolInterpolation(), QuantLib::DefaultProbabilityTermStructure::survivalProbability(), QuantLib::SabrVolSurface::update(), QuantLib::PiecewiseZeroSpreadedTermStructure::updateTimes(), QuantLib::CPIVolatilitySurface::volatility(), QuantLib::YoYOptionletVolatilitySurface::volatility(), QuantLib::CapFloorTermVolatilityStructure::volatility(), QuantLib::SwaptionVolatilityStructure::volatility(), QuantLib::OptionletVolatilityStructure::volatilityImpl(), QuantLib::SwaptionVolatilityStructure::volatilityImpl(), QuantLib::SabrVolSurface::volatilitySpreads(), QuantLib::YoYInflationTermStructure::yoyRate(), and QuantLib::ZeroInflationTermStructure::zeroRate().
{
        return dayCounter().yearFraction(referenceDate(), d);
    }
void QuantLib::TermStructure::update () [virtual]
This method must be implemented in derived classes. An instance of Observer does not call this method directly: instead, it will be called by the observables the instance registered with when they need to notify any changes.
Implements QuantLib::Observer.
Reimplemented in QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >, QuantLib::InterpolatedCPICapFloorTermPriceSurface< Interpolator2D >, QuantLib::PiecewiseYoYOptionletVolatilityCurve< Interpolator, Bootstrap, Traits >, QuantLib::YieldTermStructure, QuantLib::DefaultProbabilityTermStructure, QuantLib::FittedBondDiscountCurve, QuantLib::PiecewiseYoYInflationCurve< Interpolator, Bootstrap, Traits >, QuantLib::CapFloorTermVolCurve, QuantLib::CapFloorTermVolSurface, QuantLib::PiecewiseZeroInflationCurve< Interpolator, Bootstrap, Traits >, QuantLib::SabrVolSurface, QuantLib::FlatForward, QuantLib::AbcdAtmVolCurve, QuantLib::ExtendedBlackVarianceSurface, QuantLib::PiecewiseZeroSpreadedTermStructure, QuantLib::SwaptionVolatilityDiscrete, QuantLib::ExtendedBlackVarianceCurve, and QuantLib::StrippedOptionletAdapter.
Definition at line 57 of file termstructure.cpp.
References moving_, QuantLib::Observable::notifyObservers(), and updated_.
{
        if (moving_)
            updated_ = false;
        notifyObservers();
    }
Member Data Documentation
Calendar QuantLib::TermStructure::calendar_ [protected]
Definition at line 109 of file termstructure.hpp.
Referenced by calendar(), and QuantLib::VolatilityTermStructure::VolatilityTermStructure().
DayCounter QuantLib::TermStructure::dayCounter_ [private]
Reimplemented in QuantLib::BlackVarianceSurface, QuantLib::BlackVarianceCurve, QuantLib::ExtendedBlackVarianceSurface, QuantLib::LocalConstantVol, QuantLib::CallableBondConstantVolatility, and QuantLib::ExtendedBlackVarianceCurve.
Definition at line 117 of file termstructure.hpp.
Referenced by dayCounter().
bool QuantLib::TermStructure::moving_ [protected]
Definition at line 106 of file termstructure.hpp.
Referenced by QuantLib::SwaptionVolatilityDiscrete::performCalculations(), QuantLib::SwaptionVolatilityDiscrete::update(), QuantLib::AbcdAtmVolCurve::update(), QuantLib::CapFloorTermVolSurface::update(), QuantLib::CapFloorTermVolCurve::update(), and update().
Date QuantLib::TermStructure::referenceDate_ [mutable, private]
Definition at line 115 of file termstructure.hpp.
Referenced by referenceDate().
Natural QuantLib::TermStructure::settlementDays_ [private]
Definition at line 116 of file termstructure.hpp.
Referenced by settlementDays().
bool QuantLib::TermStructure::updated_ [mutable, protected]
Definition at line 107 of file termstructure.hpp.
Referenced by referenceDate(), and update().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructure.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructure.cpp