QuantLib: QuantLib::MCBarrierEngine< RNG, S > Class Template Reference
QuantLib::MCBarrierEngine< RNG, S > Class Template Reference
Pricing engine for barrier options using Monte Carlo simulation.
#include <mcbarrierengine.hpp>
Public Types
typedef McSimulation
< SingleVariate, RNG, S >
::path_generator_type path_generator_type
typedef McSimulation
< SingleVariate, RNG, S >
::path_pricer_type path_pricer_type
typedef McSimulation
< SingleVariate, RNG, S >
::stats_type stats_type
Public Member Functions
MCBarrierEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > &process, Size timeSteps, Size timeStepsPerYear, bool brownianBridge, bool antitheticVariate, Size requiredSamples, Real requiredTolerance, Size maxSamples, bool isBiased, BigNatural seed)
void calculate () const
Protected Member Functions
TimeGrid timeGrid () const
boost::shared_ptr
< path_generator_type > pathGenerator () const
boost::shared_ptr
< path_pricer_type > pathPricer () const
Protected Attributes
boost::shared_ptr
< GeneralizedBlackScholesProcess > process_
Size timeSteps_
Size timeStepsPerYear_
Size requiredSamples_
Size maxSamples_
Real requiredTolerance_
bool isBiased_
bool brownianBridge_
BigNatural seed_
Detailed Description
template<class RNG = PseudoRandom, class S = Statistics>
class QuantLib::MCBarrierEngine< RNG, S >
Pricing engine for barrier options using Monte Carlo simulation.
Uses the Brownian-bridge correction for the barrier found in Going to Extremes: Correcting Simulation Bias in Exotic Option Valuation - D.R. Beaglehole, P.H. Dybvig and G. Zhou Financial Analysts Journal; Jan/Feb 1997; 53, 1. pg. 62-68 and Simulating path-dependent options: A new approach - M. El Babsiri and G. Noel Journal of Derivatives; Winter 1998; 6, 2; pg. 65-83
Test:
the correctness of the returned value is tested by reproducing results available in literature.
Definition at line 56 of file mcbarrierengine.hpp.
Member Typedef Documentation
template<class RNG = PseudoRandom, class S = Statistics> typedef McSimulation<SingleVariate,RNG,S>::path_generator_type QuantLib::MCBarrierEngine< RNG, S >::path_generator_type
Reimplemented from QuantLib::McSimulation< SingleVariate, RNG, S >.
Definition at line 61 of file mcbarrierengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> typedef McSimulation<SingleVariate,RNG,S>::path_pricer_type QuantLib::MCBarrierEngine< RNG, S >::path_pricer_type
Reimplemented from QuantLib::McSimulation< SingleVariate, RNG, S >.
Definition at line 63 of file mcbarrierengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> typedef McSimulation<SingleVariate,RNG,S>::stats_type QuantLib::MCBarrierEngine< RNG, S >::stats_type
Reimplemented from QuantLib::McSimulation< SingleVariate, RNG, S >.
Definition at line 65 of file mcbarrierengine.hpp.
Constructor & Destructor Documentation
template<class RNG , class S > QuantLib::MCBarrierEngine< RNG, S >::MCBarrierEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > & process, Size timeSteps, Size timeStepsPerYear, bool brownianBridge, bool antitheticVariate, Size requiredSamples, Real requiredTolerance, Size maxSamples, bool isBiased, BigNatural seed) [inline]
Definition at line 185 of file mcbarrierengine.hpp.
References QuantLib::MCBarrierEngine< RNG, S >::process_, QL_REQUIRE, and QuantLib::Observer::registerWith().
    : McSimulation<SingleVariate,RNG,S>(antitheticVariate, false),
      process_(process), timeSteps_(timeSteps),
      timeStepsPerYear_(timeStepsPerYear),
      requiredSamples_(requiredSamples), maxSamples_(maxSamples),
      requiredTolerance_(requiredTolerance),
      isBiased_(isBiased),
      brownianBridge_(brownianBridge), seed_(seed) {
        QL_REQUIRE(timeSteps != Null<Size>() ||
                   timeStepsPerYear != Null<Size>(),
                   "no time steps provided");
        QL_REQUIRE(timeSteps == Null<Size>() ||
                   timeStepsPerYear == Null<Size>(),
                   "both time steps and time steps per year were provided");
        QL_REQUIRE(timeSteps != 0,
                   "timeSteps must be positive, " << timeSteps <<
                   " not allowed");
        QL_REQUIRE(timeStepsPerYear != 0,
                   "timeStepsPerYear must be positive, " << timeStepsPerYear <<
                   " not allowed");
        registerWith(process_);
    }
Member Function Documentation
template<class RNG = PseudoRandom, class S = Statistics> void QuantLib::MCBarrierEngine< RNG, S >::calculate () const [inline, virtual]
Implements QuantLib::PricingEngine.
Definition at line 78 of file mcbarrierengine.hpp.
References QuantLib::Instrument::results::errorEstimate, QuantLib::MCBarrierEngine< RNG, S >::maxSamples_, QuantLib::McSimulation< SingleVariate, RNG, S >::mcModel_, QuantLib::MCBarrierEngine< RNG, S >::process_, QL_REQUIRE, QuantLib::MCBarrierEngine< RNG, S >::requiredSamples_, QuantLib::MCBarrierEngine< RNG, S >::requiredTolerance_, QuantLib::GenericEngine< BarrierOption::arguments, BarrierOption::results >::results_, QuantLib::BarrierOption::engine::triggered(), and QuantLib::Instrument::results::value.
{
            Real spot = process_->x0();
            QL_REQUIRE(spot >= 0.0, "negative or null underlying given");
            QL_REQUIRE(!triggered(spot), "barrier touched");
            McSimulation<SingleVariate,RNG,S>::calculate(requiredTolerance_,
                                                         requiredSamples_,
                                                         maxSamples_);
            results_.value = this->mcModel_->sampleAccumulator().mean();
            if (RNG::allowsErrorEstimate)
            results_.errorEstimate =
                this->mcModel_->sampleAccumulator().errorEstimate();
        }
template<class RNG = PseudoRandom, class S = Statistics> boost::shared_ptr<path_generator_type> QuantLib::MCBarrierEngine< RNG, S >::pathGenerator () const [inline, protected, virtual]
Implements QuantLib::McSimulation< SingleVariate, RNG, S >.
Definition at line 93 of file mcbarrierengine.hpp.
References QuantLib::MCBarrierEngine< RNG, S >::brownianBridge_, QuantLib::MCBarrierEngine< RNG, S >::process_, QuantLib::MCBarrierEngine< RNG, S >::seed_, QuantLib::TimeGrid::size(), and QuantLib::MCBarrierEngine< RNG, S >::timeGrid().
{
            TimeGrid grid = timeGrid();
            typename RNG::rsg_type gen =
                RNG::make_sequence_generator(grid.size()-1,seed_);
            return boost::shared_ptr<path_generator_type>(
                         new path_generator_type(process_,
                                                 grid, gen, brownianBridge_));
        }
template<class RNG , class S > boost::shared_ptr< typename MCBarrierEngine< RNG, S >::path_pricer_type > QuantLib::MCBarrierEngine< RNG, S >::pathPricer () const [inline, protected, virtual]
Implements QuantLib::McSimulation< SingleVariate, RNG, S >.
Definition at line 236 of file mcbarrierengine.hpp.
References QL_REQUIRE, and QuantLib::TimeGrid::size().
{
        boost::shared_ptr<PlainVanillaPayoff> payoff =
            boost::dynamic_pointer_cast<PlainVanillaPayoff>(arguments_.payoff);
        QL_REQUIRE(payoff, "non-plain payoff given");
        TimeGrid grid = timeGrid();
        std::vector<DiscountFactor> discounts(grid.size());
        for (Size i=0; i<grid.size(); i++)
            discounts[i] = process_->riskFreeRate()->discount(grid[i]);
        // do this with template parameters?
        if (isBiased_) {
            return boost::shared_ptr<
                        typename MCBarrierEngine<RNG,S>::path_pricer_type>(
                new BiasedBarrierPathPricer(
                       arguments_.barrierType,
                       arguments_.barrier,
                       arguments_.rebate,
                       payoff->optionType(),
                       payoff->strike(),
                       discounts));
        } else {
            PseudoRandom::ursg_type sequenceGen(grid.size()-1,
                                                PseudoRandom::urng_type(5));
            return boost::shared_ptr<
                        typename MCBarrierEngine<RNG,S>::path_pricer_type>(
                new BarrierPathPricer(
                    arguments_.barrierType,
                    arguments_.barrier,
                    arguments_.rebate,
                    payoff->optionType(),
                    payoff->strike(),
                    discounts,
                    process_,
                    sequenceGen));
        }
    }
template<class RNG , class S > TimeGrid QuantLib::MCBarrierEngine< RNG, S >::timeGrid () const [inline, protected, virtual]
Implements QuantLib::McSimulation< SingleVariate, RNG, S >.
Definition at line 219 of file mcbarrierengine.hpp.
References QL_FAIL.
Referenced by QuantLib::MCBarrierEngine< RNG, S >::pathGenerator().
{
        Time residualTime = process_->time(arguments_.exercise->lastDate());
        if (timeSteps_ != Null<Size>()) {
            return TimeGrid(residualTime, timeSteps_);
        } else if (timeStepsPerYear_ != Null<Size>()) {
            Size steps = static_cast<Size>(timeStepsPerYear_*residualTime);
            return TimeGrid(residualTime, std::max<Size>(steps, 1));
        } else {
            QL_FAIL("time steps not specified");
        }
    }
Member Data Documentation
template<class RNG = PseudoRandom, class S = Statistics> bool QuantLib::MCBarrierEngine< RNG, S >::brownianBridge_ [protected]
Definition at line 108 of file mcbarrierengine.hpp.
Referenced by QuantLib::MCBarrierEngine< RNG, S >::pathGenerator().
template<class RNG = PseudoRandom, class S = Statistics> bool QuantLib::MCBarrierEngine< RNG, S >::isBiased_ [protected]
Definition at line 107 of file mcbarrierengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> Size QuantLib::MCBarrierEngine< RNG, S >::maxSamples_ [protected]
Definition at line 105 of file mcbarrierengine.hpp.
Referenced by QuantLib::MCBarrierEngine< RNG, S >::calculate().
template<class RNG = PseudoRandom, class S = Statistics> boost::shared_ptr<GeneralizedBlackScholesProcess> QuantLib::MCBarrierEngine< RNG, S >::process_ [protected]
Definition at line 103 of file mcbarrierengine.hpp.
Referenced by QuantLib::MCBarrierEngine< RNG, S >::calculate(), QuantLib::MCBarrierEngine< RNG, S >::MCBarrierEngine(), and QuantLib::MCBarrierEngine< RNG, S >::pathGenerator().
template<class RNG = PseudoRandom, class S = Statistics> Size QuantLib::MCBarrierEngine< RNG, S >::requiredSamples_ [protected]
Definition at line 105 of file mcbarrierengine.hpp.
Referenced by QuantLib::MCBarrierEngine< RNG, S >::calculate().
template<class RNG = PseudoRandom, class S = Statistics> Real QuantLib::MCBarrierEngine< RNG, S >::requiredTolerance_ [protected]
Definition at line 106 of file mcbarrierengine.hpp.
Referenced by QuantLib::MCBarrierEngine< RNG, S >::calculate().
template<class RNG = PseudoRandom, class S = Statistics> BigNatural QuantLib::MCBarrierEngine< RNG, S >::seed_ [protected]
Definition at line 109 of file mcbarrierengine.hpp.
Referenced by QuantLib::MCBarrierEngine< RNG, S >::pathGenerator().
template<class RNG = PseudoRandom, class S = Statistics> Size QuantLib::MCBarrierEngine< RNG, S >::timeSteps_ [protected]
Definition at line 104 of file mcbarrierengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> Size QuantLib::MCBarrierEngine< RNG, S >::timeStepsPerYear_ [protected]
Definition at line 104 of file mcbarrierengine.hpp.
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/barrier/mcbarrierengine.hpp