QuantLib: QuantLib::ExplicitEulerScheme Class Reference
QuantLib::ExplicitEulerScheme Class Reference
#include <expliciteulerscheme.hpp>
Public Types
typedef OperatorTraits
< FdmLinearOp > traits
typedef traits::operator_type operator_type
typedef traits::array_type array_type
typedef traits::bc_set bc_set
typedef traits::condition_type condition_type
Public Member Functions
ExplicitEulerScheme (const boost::shared_ptr< FdmLinearOpComposite > &map, const bc_set &bcSet=bc_set())
void step (array_type &a, Time t)
void setStep (Time dt)
Protected Attributes
Time dt_
const boost::shared_ptr
< FdmLinearOpComposite > & map_
const BoundaryConditionSchemeHelper bcSet_
Detailed Description
Definition at line 35 of file expliciteulerscheme.hpp.
Member Typedef Documentation
typedef traits::array_type QuantLib::ExplicitEulerScheme::array_type
Definition at line 40 of file expliciteulerscheme.hpp.
typedef traits::bc_set QuantLib::ExplicitEulerScheme::bc_set
Definition at line 41 of file expliciteulerscheme.hpp.
typedef traits::condition_type QuantLib::ExplicitEulerScheme::condition_type
Definition at line 42 of file expliciteulerscheme.hpp.
typedef traits::operator_type QuantLib::ExplicitEulerScheme::operator_type
Definition at line 39 of file expliciteulerscheme.hpp.
typedef OperatorTraits<FdmLinearOp> QuantLib::ExplicitEulerScheme::traits
Definition at line 38 of file expliciteulerscheme.hpp.
Constructor & Destructor Documentation
QuantLib::ExplicitEulerScheme::ExplicitEulerScheme (const boost::shared_ptr< FdmLinearOpComposite > & map, const bc_set & bcSet = bc_set())
Definition at line 25 of file expliciteulerscheme.cpp.
                                 :
            dt_(Null<Real>()), map_(map), bcSet_(bcSet) {
    }
Member Function Documentation
void QuantLib::ExplicitEulerScheme::setStep (Time dt)
Definition at line 41 of file expliciteulerscheme.cpp.
References QuantLib::anonymous_namespace{yieldtermstructure.cpp}::dt, and dt_.
{
        dt_ = dt;
    }
void QuantLib::ExplicitEulerScheme::step (array_type & a, Time t)
Definition at line 31 of file expliciteulerscheme.cpp.
References QuantLib::BoundaryConditionSchemeHelper::applyAfterApplying(), QuantLib::BoundaryConditionSchemeHelper::applyBeforeApplying(), bcSet_, dt_, map_, QL_REQUIRE, and QuantLib::BoundaryConditionSchemeHelper::setTime().
{
        QL_REQUIRE(t-dt_ > -1e-8, "a step towards negative time given");
        map_->setTime(std::max(0.0, t - dt_), t);
        bcSet_.setTime(std::max(0.0, t-dt_));
        bcSet_.applyBeforeApplying(*map_);
        a += dt_ * map_->apply(a);
        bcSet_.applyAfterApplying(a);
    }
Member Data Documentation
const BoundaryConditionSchemeHelper QuantLib::ExplicitEulerScheme::bcSet_ [protected]
Definition at line 55 of file expliciteulerscheme.hpp.
Referenced by step().
Time QuantLib::ExplicitEulerScheme::dt_ [protected]
Definition at line 53 of file expliciteulerscheme.hpp.
Referenced by setStep(), and step().
const boost::shared_ptr<FdmLinearOpComposite>& QuantLib::ExplicitEulerScheme::map_ [protected]
Definition at line 54 of file expliciteulerscheme.hpp.
Referenced by step().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/schemes/expliciteulerscheme.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/schemes/expliciteulerscheme.cpp