QuantLib: QuantLib::Vasicek Class Reference
QuantLib::Vasicek Class Reference
Vasicek model class
#include <vasicek.hpp>
Classes
class Dynamics
Short-rate dynamics in the Vasicek model.
Public Member Functions
Vasicek (Rate r0=0.05, Real a=0.1, Real b=0.05, Real sigma=0.01, Real lambda=0.0)
virtual Real discountBondOption (Option::Type type, Real strike, Time maturity, Time bondMaturity) const
virtual boost::shared_ptr
< ShortRateDynamics > dynamics () const
returns the short-rate dynamics
Real a () const
Real b () const
Real lambda () const
Real sigma () const
Protected Member Functions
virtual Real A (Time t, Time T) const
virtual Real B (Time t, Time T) const
Protected Attributes
Real r0_
Parameter & a_
Parameter & b_
Parameter & sigma_
Parameter & lambda_
Detailed Description
Vasicek model class
This class implements the Vasicek model defined by
\[ dr_t = a(b - r_t)dt + \sigma dW_t , \]
where \(a \), \(b \) and \(\sigma \) are constants; a risk premium \(\lambda \) can also be specified.
Definition at line 42 of file vasicek.hpp.
Constructor & Destructor Documentation
QuantLib::Vasicek::Vasicek (Rate r0 = 0.05, Real a = 0.1, Real b = 0.05, Real sigma = 0.01, Real lambda = 0.0)
Definition at line 26 of file vasicek.cpp.
References a_, b_, lambda_, and sigma_.
    : OneFactorAffineModel(4), r0_(r0),
      a_(arguments_[0]), b_(arguments_[1]), sigma_(arguments_[2]),
      lambda_(arguments_[3]) {
        a_ = ConstantParameter(a, PositiveConstraint());
        b_ = ConstantParameter(b, NoConstraint());
        sigma_ = ConstantParameter(sigma, PositiveConstraint());
        lambda_ = ConstantParameter(lambda, NoConstraint());
    }
Member Function Documentation
Real QuantLib::Vasicek::a () const [inline]
Definition at line 54 of file vasicek.hpp.
References a_.
Referenced by A(), B(), discountBondOption(), QuantLib::HullWhite::discountBondOption(), dynamics(), QuantLib::HullWhite::dynamics(), QuantLib::HullWhite::generateArguments(), and QuantLib::HullWhite::tree().
{ return a_(0.0); }
Real QuantLib::Vasicek::A (Time t, Time T) const [protected, virtual]
Implements QuantLib::OneFactorAffineModel.
Reimplemented in QuantLib::HullWhite.
Definition at line 36 of file vasicek.cpp.
References a(), b(), B(), lambda(), QL_EPSILON, and sigma().
{
        Real _a = a();
        if (_a < std::sqrt(QL_EPSILON)) {
            return 0.0;
        } else {
            Real sigma2 = sigma()*sigma();
            Real bt = B(t, T);
            return std::exp((b() + lambda()*sigma()/_a
                             - 0.5*sigma2/(_a*_a))*(bt - (T - t))
                             - 0.25*sigma2*bt*bt/_a);
        }
    }
Real QuantLib::Vasicek::b () const [inline]
Definition at line 55 of file vasicek.hpp.
References b_.
Referenced by A(), and dynamics().
{ return b_(0.0); }
Real QuantLib::Vasicek::B (Time t, Time T) const [protected, virtual]
Implements QuantLib::OneFactorAffineModel.
Definition at line 49 of file vasicek.cpp.
References a(), and QL_EPSILON.
Referenced by A(), QuantLib::HullWhite::A(), discountBondOption(), and QuantLib::HullWhite::discountBondOption().
{
        Real _a = a();
        if (_a < std::sqrt(QL_EPSILON))
            return (T - t);
        else
            return (1.0 - std::exp(-_a*(T - t)))/_a;
    }
Real QuantLib::Vasicek::discountBondOption (Option::Type type, Real strike, Time maturity, Time bondMaturity) const [virtual]
Implements QuantLib::AffineModel.
Reimplemented in QuantLib::HullWhite.
Definition at line 57 of file vasicek.cpp.
References a(), B(), QuantLib::blackFormula(), QuantLib::OneFactorAffineModel::discountBond(), anonymous_namespace{interpolations.cpp}::f(), QL_EPSILON, r0_, sigma(), and anonymous_namespace{perturbativebarrieroptionengine.cpp}::v().
{
        Real v;
        Real _a = a();
        if (std::fabs(maturity) < QL_EPSILON) {
            v = 0.0;
        } else if (_a < std::sqrt(QL_EPSILON)) {
            v = sigma()*B(maturity, bondMaturity)* std::sqrt(maturity);
        } else {
            v = sigma()*B(maturity, bondMaturity)*
                std::sqrt(0.5*(1.0 - std::exp(-2.0*_a*maturity))/_a);
        }
        Real f = discountBond(0.0, bondMaturity, r0_);
        Real k = discountBond(0.0, maturity, r0_)*strike;
        return blackFormula(type, k, f, v);
    }
boost::shared_ptr< OneFactorModel::ShortRateDynamics > QuantLib::Vasicek::dynamics () const [inline, virtual]
returns the short-rate dynamics
Implements QuantLib::OneFactorModel.
Reimplemented in QuantLib::HullWhite.
Definition at line 101 of file vasicek.hpp.
References a(), b(), r0_, and sigma().
{
        return boost::shared_ptr<ShortRateDynamics>(
                                     new Dynamics(a(), b() , sigma(), r0_));
    }
Real QuantLib::Vasicek::lambda () const [inline]
Definition at line 56 of file vasicek.hpp.
References lambda_.
Referenced by A(), and QuantLib::HullWhite::convexityBias().
{ return lambda_(0.0); }
Real QuantLib::Vasicek::sigma () const [inline]
Definition at line 57 of file vasicek.hpp.
References sigma_.
Referenced by A(), QuantLib::HullWhite::A(), discountBondOption(), QuantLib::HullWhite::discountBondOption(), dynamics(), QuantLib::HullWhite::dynamics(), QuantLib::HullWhite::generateArguments(), and QuantLib::HullWhite::tree().
{ return sigma_(0.0); }
Member Data Documentation
Parameter& QuantLib::Vasicek::a_ [protected]
Definition at line 64 of file vasicek.hpp.
Referenced by a(), and Vasicek().
Parameter& QuantLib::Vasicek::b_ [protected]
Definition at line 65 of file vasicek.hpp.
Referenced by b(), QuantLib::HullWhite::HullWhite(), and Vasicek().
Parameter& QuantLib::Vasicek::lambda_ [protected]
Definition at line 67 of file vasicek.hpp.
Referenced by QuantLib::HullWhite::HullWhite(), lambda(), and Vasicek().
Real QuantLib::Vasicek::r0_ [protected]
Definition at line 63 of file vasicek.hpp.
Referenced by discountBondOption(), and dynamics().
Parameter& QuantLib::Vasicek::sigma_ [protected]
Definition at line 66 of file vasicek.hpp.
Referenced by sigma(), and Vasicek().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/shortrate/onefactormodels/vasicek.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/shortrate/onefactormodels/vasicek.cpp