QuantLib: QuantLib::VolatilityInterpolationSpecifier Class Reference
QuantLib::VolatilityInterpolationSpecifier Class Reference
#include <volatilityinterpolationspecifier.hpp>
Public Member Functions
VolatilityInterpolationSpecifier ()
virtual ~VolatilityInterpolationSpecifier ()
virtual void setScalingFactors (const std::vector< Real > &scales)=0
virtual void setLastCapletVol (Real vol)=0
virtual const std::vector
< boost::shared_ptr
< PiecewiseConstantVariance > > & interpolatedVariances () const =0
virtual const std::vector
< boost::shared_ptr
< PiecewiseConstantVariance > > & originalVariances () const =0
virtual Size getPeriod () const =0
virtual Size getOffset () const =0
virtual Size getNoBigRates () const =0
virtual Size getNoSmallRates () const =0
Detailed Description
Definition at line 39 of file volatilityinterpolationspecifier.hpp.
Constructor & Destructor Documentation
QuantLib::VolatilityInterpolationSpecifier::VolatilityInterpolationSpecifier ()
Definition at line 26 of file volatilityinterpolationspecifier.cpp.
    {
    }
QuantLib::VolatilityInterpolationSpecifier::~VolatilityInterpolationSpecifier () [virtual]
Definition at line 30 of file volatilityinterpolationspecifier.cpp.
    {
    }
Member Function Documentation
virtual Size QuantLib::VolatilityInterpolationSpecifier::getNoBigRates () const [pure virtual]
Implemented in QuantLib::VolatilityInterpolationSpecifierabcd.
Referenced by QuantLib::capletSwaptionPeriodicCalibration().
virtual Size QuantLib::VolatilityInterpolationSpecifier::getNoSmallRates () const [pure virtual]
Implemented in QuantLib::VolatilityInterpolationSpecifierabcd.
virtual Size QuantLib::VolatilityInterpolationSpecifier::getOffset () const [pure virtual]
Implemented in QuantLib::VolatilityInterpolationSpecifierabcd.
virtual Size QuantLib::VolatilityInterpolationSpecifier::getPeriod () const [pure virtual]
Implemented in QuantLib::VolatilityInterpolationSpecifierabcd.
virtual const std::vector<boost::shared_ptr<PiecewiseConstantVariance> >& QuantLib::VolatilityInterpolationSpecifier::interpolatedVariances () const [pure virtual]
Implemented in QuantLib::VolatilityInterpolationSpecifierabcd.
Referenced by QuantLib::capletSwaptionPeriodicCalibration().
virtual const std::vector<boost::shared_ptr<PiecewiseConstantVariance> >& QuantLib::VolatilityInterpolationSpecifier::originalVariances () const [pure virtual]
Implemented in QuantLib::VolatilityInterpolationSpecifierabcd.
Referenced by QuantLib::capletSwaptionPeriodicCalibration().
virtual void QuantLib::VolatilityInterpolationSpecifier::setLastCapletVol (Real vol) [pure virtual]
Implemented in QuantLib::VolatilityInterpolationSpecifierabcd.
Referenced by QuantLib::capletSwaptionPeriodicCalibration().
virtual void QuantLib::VolatilityInterpolationSpecifier::setScalingFactors (const std::vector< Real > & scales) [pure virtual]
Implemented in QuantLib::VolatilityInterpolationSpecifierabcd.
Referenced by QuantLib::capletSwaptionPeriodicCalibration().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/models/volatilityinterpolationspecifier.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/models/volatilityinterpolationspecifier.cpp