QuantLib: QuantLib::StulzEngine Class Reference
QuantLib::StulzEngine Class Reference
Pricing engine for 2D European Baskets.
#include <stulzengine.hpp>
Public Member Functions
StulzEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > &process1, const boost::shared_ptr< GeneralizedBlackScholesProcess > &process2, Real correlation)
void calculate () const
Private Attributes
boost::shared_ptr
< GeneralizedBlackScholesProcess > process1_
boost::shared_ptr
< GeneralizedBlackScholesProcess > process2_
Real rho_
Detailed Description
Pricing engine for 2D European Baskets.
This class implements formulae from "Options on the Minimum or the Maximum of Two Risky Assets", Rene Stulz, Journal of Financial Ecomomics (1982) 10, 161-185.
Test:
the correctness of the returned value is tested by reproducing results available in literature.
Definition at line 44 of file stulzengine.hpp.
Constructor & Destructor Documentation
QuantLib::StulzEngine::StulzEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > & process1, const boost::shared_ptr< GeneralizedBlackScholesProcess > & process2, Real correlation)
Definition at line 102 of file stulzengine.cpp.
References process1_, process2_, and QuantLib::Observer::registerWith().
    : process1_(process1), process2_(process2), rho_(correlation) {
        registerWith(process1_);
        registerWith(process2_);
    }
Member Function Documentation
void QuantLib::StulzEngine::calculate () const [virtual]
Implements QuantLib::PricingEngine.
Definition at line 111 of file stulzengine.cpp.
References QuantLib::GenericEngine< BasketOption::arguments, BasketOption::results >::arguments_, QuantLib::Option::Call, QuantLib::Exercise::European, QuantLib::anonymous_namespace{stulzengine.cpp}::euroTwoAssetMaxBasketCall(), QuantLib::anonymous_namespace{stulzengine.cpp}::euroTwoAssetMinBasketCall(), process1_, process2_, QuantLib::Option::Put, QL_FAIL, QL_REQUIRE, QuantLib::GenericEngine< BasketOption::arguments, BasketOption::results >::results_, rho_, and QuantLib::Instrument::results::value.
{
        QL_REQUIRE(arguments_.exercise->type() == Exercise::European,
                   "not an European Option");
        boost::shared_ptr<EuropeanExercise> exercise =
            boost::dynamic_pointer_cast<EuropeanExercise>(arguments_.exercise);
        QL_REQUIRE(exercise, "not an European Option");
        boost::shared_ptr<BasketPayoff> basket_payoff =
            boost::dynamic_pointer_cast<BasketPayoff>(arguments_.payoff);
        boost::shared_ptr<MinBasketPayoff> min_basket =
            boost::dynamic_pointer_cast<MinBasketPayoff>(arguments_.payoff);
        boost::shared_ptr<MaxBasketPayoff> max_basket =
            boost::dynamic_pointer_cast<MaxBasketPayoff>(arguments_.payoff);
        QL_REQUIRE(min_basket || max_basket, "unknown basket type");
        boost::shared_ptr<PlainVanillaPayoff> payoff =
            boost::dynamic_pointer_cast<PlainVanillaPayoff>(basket_payoff->basePayoff());
        QL_REQUIRE(payoff, "non-plain payoff given");
        Real strike = payoff->strike();
        Real variance1 = process1_->blackVolatility()->blackVariance(
                                                exercise->lastDate(), strike);
        Real variance2 = process2_->blackVolatility()->blackVariance(
                                                exercise->lastDate(), strike);
        DiscountFactor riskFreeDiscount =
            process1_->riskFreeRate()->discount(exercise->lastDate());
        // cannot handle non zero dividends, so don't believe this...
        DiscountFactor dividendDiscount1 =
            process1_->dividendYield()->discount(exercise->lastDate());
        DiscountFactor dividendDiscount2 =
            process2_->dividendYield()->discount(exercise->lastDate());
        Real forward1 = process1_->stateVariable()->value() *
            dividendDiscount1 / riskFreeDiscount;
        Real forward2 = process2_->stateVariable()->value() *
            dividendDiscount2 / riskFreeDiscount;
        if (max_basket) {
            switch (payoff->optionType()) {
              // euro call on a two asset max basket
              case Option::Call:
                results_.value =
                    euroTwoAssetMaxBasketCall(forward1, forward2, strike,
                                              riskFreeDiscount,
                                              variance1, variance2,
                                              rho_);
                break;
              // euro put on a two asset max basket
              case Option::Put:
                results_.value = strike * riskFreeDiscount -
                    euroTwoAssetMaxBasketCall(forward1, forward2, 0.0,
                                              riskFreeDiscount,
                                              variance1, variance2, rho_) +
                    euroTwoAssetMaxBasketCall(forward1, forward2, strike,
                                              riskFreeDiscount,
                                              variance1, variance2, rho_);
                break;
              default:
                QL_FAIL("unknown option type");
            }
        } else if (min_basket) {
            switch (payoff->optionType()) {
              // euro call on a two asset min basket
              case Option::Call:
                results_.value =
                    euroTwoAssetMinBasketCall(forward1, forward2, strike,
                                              riskFreeDiscount,
                                              variance1, variance2,
                                              rho_);
                break;
              // euro put on a two asset min basket
              case Option::Put:
                results_.value = strike * riskFreeDiscount -
                    euroTwoAssetMinBasketCall(forward1, forward2, 0.0,
                                              riskFreeDiscount,
                                              variance1, variance2, rho_) +
                    euroTwoAssetMinBasketCall(forward1, forward2, strike,
                                              riskFreeDiscount,
                                              variance1, variance2, rho_);
                break;
              default:
                QL_FAIL("unknown option type");
            }
        } else {
            QL_FAIL("unknown type");
        }
    }
Member Data Documentation
boost::shared_ptr<GeneralizedBlackScholesProcess> QuantLib::StulzEngine::process1_ [private]
Definition at line 52 of file stulzengine.hpp.
Referenced by calculate(), and StulzEngine().
boost::shared_ptr<GeneralizedBlackScholesProcess> QuantLib::StulzEngine::process2_ [private]
Definition at line 53 of file stulzengine.hpp.
Referenced by calculate(), and StulzEngine().
Real QuantLib::StulzEngine::rho_ [private]
Definition at line 54 of file stulzengine.hpp.
Referenced by calculate().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/basket/stulzengine.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/basket/stulzengine.cpp