QuantLib: QuantLib::IndexedCashFlow Class Reference
QuantLib::IndexedCashFlow Class Reference
Cash flow dependent on an index ratio.
#include <indexedcashflow.hpp>
Public Member Functions
IndexedCashFlow (Real notional, const boost::shared_ptr< Index > &index, const Date &baseDate, const Date &fixingDate, const Date &paymentDate, bool growthOnly=false)
virtual Real notional () const
virtual Date baseDate () const
virtual Date fixingDate () const
virtual boost::shared_ptr< Index > index () const
virtual bool growthOnly () const
Event interface
Date date () const
CashFlow interface
Real amount () const
returns the amount of the cash flow
Visitability
virtual void accept (AcyclicVisitor &)
Observer interface
void update ()
Private Attributes
Real notional_
boost::shared_ptr< Index > index_
Date baseDate_
Date fixingDate_
Date paymentDate_
bool growthOnly_
Detailed Description
Cash flow dependent on an index ratio.
This cash flow is not a coupon, i.e., there's no accrual. The amount is either i(T)/i(0) or i(T)/i(0) - 1, depending on the growthOnly parameter.
We expect this to be used inside an instrument that does all the date adjustment etc., so this takes just dates and does not change them. growthOnly = false means i(T)/i(0), which is a bond-type setting. growthOnly = true means i(T)/i(0) - 1, which is a swap-type setting.
Definition at line 43 of file indexedcashflow.hpp.
Constructor & Destructor Documentation
QuantLib::IndexedCashFlow::IndexedCashFlow (Real notional, const boost::shared_ptr< Index > & index, const Date & baseDate, const Date & fixingDate, const Date & paymentDate, bool growthOnly = false) [inline]
Definition at line 46 of file indexedcashflow.hpp.
References QuantLib::Observer::registerWith().
        : notional_(notional), index_(index),
          baseDate_(baseDate), fixingDate_(fixingDate),
          paymentDate_(paymentDate), growthOnly_(growthOnly) {
            registerWith(index);
        }
Member Function Documentation
void QuantLib::IndexedCashFlow::accept (AcyclicVisitor & v) [inline, virtual]
Reimplemented from QuantLib::CashFlow.
Definition at line 88 of file indexedcashflow.hpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Visitor< T >::visit().
{
        Visitor<IndexedCashFlow>* v1 =
        dynamic_cast<Visitor<IndexedCashFlow>*>(&v);
        if (v1 != 0)
            v1->visit(*this);
        else
            CashFlow::accept(v);
    }
Real QuantLib::IndexedCashFlow::amount () const [virtual]
returns the amount of the cash flow
Note:
The amount is not discounted, i.e., it is the actual amount paid at the cash flow date.
Implements QuantLib::CashFlow.
Reimplemented in QuantLib::CPICashFlow.
Definition at line 25 of file indexedcashflow.cpp.
References baseDate_, fixingDate_, growthOnly_, index_, and notional_.
Referenced by InflationTest::testZeroTermStructure().
{
        Real I0 = index_->fixing(baseDate_);
        Real I1 = index_->fixing(fixingDate_);
        if (growthOnly_)
            return notional_ * (I1 / I0 - 1.0);
        else
            return notional_ * (I1 / I0);
    }
virtual Date QuantLib::IndexedCashFlow::baseDate () const [inline, virtual]
Reimplemented in QuantLib::CPICashFlow.
Definition at line 62 of file indexedcashflow.hpp.
References baseDate_.
Referenced by InflationTest::testZeroTermStructure().
{ return baseDate_; }
Date QuantLib::IndexedCashFlow::date () const [inline, virtual]
Note:
This is inherited from the event class
Implements QuantLib::CashFlow.
Definition at line 59 of file indexedcashflow.hpp.
References paymentDate_.
{ return paymentDate_; }
virtual Date QuantLib::IndexedCashFlow::fixingDate () const [inline, virtual]
Definition at line 63 of file indexedcashflow.hpp.
References fixingDate_.
Referenced by QuantLib::CPICashFlow::amount(), and InflationTest::testZeroTermStructure().
{ return fixingDate_; }
virtual bool QuantLib::IndexedCashFlow::growthOnly () const [inline, virtual]
Definition at line 65 of file indexedcashflow.hpp.
References growthOnly_.
Referenced by QuantLib::CPICashFlow::amount().
{ return growthOnly_; }
virtual boost::shared_ptr<Index> QuantLib::IndexedCashFlow::index () const [inline, virtual]
Definition at line 64 of file indexedcashflow.hpp.
References index_.
Referenced by QuantLib::CPICashFlow::amount().
{ return index_; }
virtual Real QuantLib::IndexedCashFlow::notional () const [inline, virtual]
Definition at line 61 of file indexedcashflow.hpp.
References notional_.
Referenced by QuantLib::CPICashFlow::amount(), and InflationTest::testZeroTermStructure().
{ return notional_; }
void QuantLib::IndexedCashFlow::update () [inline, virtual]
This method must be implemented in derived classes. An instance of Observer does not call this method directly: instead, it will be called by the observables the instance registered with when they need to notify any changes.
Implements QuantLib::Observer.
Definition at line 76 of file indexedcashflow.hpp.
References QuantLib::Observable::notifyObservers().
{ notifyObservers(); }
Member Data Documentation
Date QuantLib::IndexedCashFlow::baseDate_ [private]
Definition at line 81 of file indexedcashflow.hpp.
Referenced by amount(), and baseDate().
Date QuantLib::IndexedCashFlow::fixingDate_ [private]
Definition at line 81 of file indexedcashflow.hpp.
Referenced by amount(), and fixingDate().
bool QuantLib::IndexedCashFlow::growthOnly_ [private]
Definition at line 82 of file indexedcashflow.hpp.
Referenced by amount(), and growthOnly().
boost::shared_ptr<Index> QuantLib::IndexedCashFlow::index_ [private]
Definition at line 80 of file indexedcashflow.hpp.
Referenced by amount(), and index().
Real QuantLib::IndexedCashFlow::notional_ [private]
Definition at line 79 of file indexedcashflow.hpp.
Referenced by amount(), and notional().
Date QuantLib::IndexedCashFlow::paymentDate_ [private]
Definition at line 81 of file indexedcashflow.hpp.
Referenced by date().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/indexedcashflow.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/indexedcashflow.cpp