QuantLib: QuantLib::Issuer Class Reference
QuantLib::Issuer Class Reference
#include <issuer.hpp>
Public Types
typedef std::pair
< DefaultProbKey, Handle
< DefaultProbabilityTermStructure > > key_curve_pair
Public Member Functions
Issuer (const std::vector< key_curve_pair > &probabilities=std::vector< key_curve_pair >(), const DefaultEventSet &events=DefaultEventSet())
Issuer (const std::vector< std::vector< boost::shared_ptr< DefaultType > > > &eventTypes, const std::vector< Currency > &currencies, const std::vector< Seniority > &seniorities, const std::vector< Handle< DefaultProbabilityTermStructure > > &curves, const DefaultEventSet &events=DefaultEventSet())
std::vector< boost::shared_ptr
< DefaultEvent > > defaultsBetween (const Date &start, const Date &end, const DefaultProbKey &contractKey, bool includeRefDate) const
Inspectors
const Handle
< DefaultProbabilityTermStructure > & defaultProbability (const DefaultProbKey &key) const
Utilities
boost::shared_ptr< DefaultEvent > defaultedBetween (const Date &start, const Date &end, const DefaultProbKey &key, bool includeRefDate=false) const
If a default event with the required seniority and.
Private Attributes
std::vector< std::pair
< DefaultProbKey, Handle
< DefaultProbabilityTermStructure > > > probabilities_
probabilities of events for each bond collection
DefaultEventSet events_
History of past events affecting this issuer. Notice it is possible.
Detailed Description
Definition at line 40 of file issuer.hpp.
Member Typedef Documentation
typedef std::pair<DefaultProbKey, Handle<DefaultProbabilityTermStructure> > QuantLib::Issuer::key_curve_pair
Definition at line 44 of file issuer.hpp.
Constructor & Destructor Documentation
QuantLib::Issuer::Issuer (const std::vector< key_curve_pair > & probabilities = std::vector< key_curve_pair >(), const DefaultEventSet & events = DefaultEventSet())
The first argument represents the probability of an issuer of having any of its bonds with the given seniority, currency incurring in that particular event. The second argument represents the history of past events. Theres no check on wether the event list makes sense, events can occur several times and several of them can take place on the same date.
To do: add settlement event access
QuantLib::Issuer::Issuer (const std::vector< std::vector< boost::shared_ptr< DefaultType > > > & eventTypes, const std::vector< Currency > & currencies, const std::vector< Seniority > & seniorities, const std::vector< Handle< DefaultProbabilityTermStructure > > & curves, const DefaultEventSet & events = DefaultEventSet())
Definition at line 42 of file issuer.cpp.
References probabilities_, and QL_REQUIRE.
    : events_(events) {
        QL_REQUIRE((eventTypes.size() == curves.size()) &&
            (curves.size()== currencies.size()) &&
            (currencies.size() == seniorities.size()),
            "Incompatible size of Issuer parameters.");
        for(Size i=0; i <eventTypes.size(); i++) {
            DefaultProbKey keytmp(eventTypes[i], currencies[i],
                seniorities[i]);
            probabilities_.push_back(std::make_pair(keytmp, curves[i]));
        }
    }
Member Function Documentation
boost::shared_ptr< DefaultEvent > QuantLib::Issuer::defaultedBetween (const Date & start, const Date & end, const DefaultProbKey & key, bool includeRefDate = false) const
If a default event with the required seniority and.
Definition at line 71 of file issuer.cpp.
References QuantLib::anonymous_namespace{issuer.cpp}::between(), and events_.
    {
        // to do: the set is ordered, see how to use it to speed this up
        for(DefaultEventSet::const_iterator itev = events_.begin();
            // am i really speeding things up with the date comp?
            itev != events_.end(); // && (*itev)->date() > start;
            itev++) {
            if((*itev)->matchesDefaultKey(contractKey) &&
                between(*itev, start, end, includeRefDate))
                return *itev;
        }
        return boost::shared_ptr<DefaultEvent>();
    }
const Handle< DefaultProbabilityTermStructure > & QuantLib::Issuer::defaultProbability (const DefaultProbKey & key) const
Definition at line 63 of file issuer.cpp.
References probabilities_, and QL_FAIL.
Referenced by QuantLib::GaussianLHPCDOEngine< CDOEngine >::expectedTrancheLoss().
{
        for(Size i=0; i<probabilities_.size(); i++)
            if(key == probabilities_[i].first)
                return probabilities_[i].second;
        QL_FAIL("Probability curve not available.");
    }
std::vector< boost::shared_ptr< DefaultEvent > > QuantLib::Issuer::defaultsBetween (const Date & start, const Date & end, const DefaultProbKey & contractKey, bool includeRefDate) const
Definition at line 91 of file issuer.cpp.
References QuantLib::anonymous_namespace{issuer.cpp}::between(), and events_.
    {
        std::vector<boost::shared_ptr<DefaultEvent> > defaults;
        // to do: the set is ordered, see how to use it to speed this up
        for(DefaultEventSet::const_iterator itev = events_.begin();
            // am i really speeding things up with the date comp?
            itev != events_.end(); // && (*itev)->date() > start;
            itev++) {
            if((*itev)->matchesDefaultKey(contractKey) &&
                between(*itev, start, end, includeRefDate))
                defaults.push_back(*itev);
        }
        return defaults;
    }
Member Data Documentation
DefaultEventSet QuantLib::Issuer::events_ [private]
History of past events affecting this issuer. Notice it is possible.
Definition at line 101 of file issuer.hpp.
Referenced by defaultedBetween(), and defaultsBetween().
std::vector<std::pair<DefaultProbKey, Handle<DefaultProbabilityTermStructure> > > QuantLib::Issuer::probabilities_ [private]
probabilities of events for each bond collection
Definition at line 97 of file issuer.hpp.
Referenced by defaultProbability(), and Issuer().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/issuer.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/issuer.cpp