QuantLib: QuantLib::step_iterator< Iterator > Class Template Reference
QuantLib::step_iterator< Iterator > Class Template Reference
Iterator advancing in constant steps.
#include <steppingiterator.hpp>
Public Member Functions
step_iterator ()
step_iterator (const Iterator &base, Size step)
template<class OtherIterator >
step_iterator (const step_iterator< OtherIterator > &i, typename boost::enable_if_convertible< OtherIterator, Iterator >::type *=0)
Size step () const
void increment ()
void decrement ()
void advance (typename super_t::difference_type n)
super_t::difference_type distance_to (const step_iterator &i) const
Private Types
typedef
boost::iterator_adaptor
< step_iterator< Iterator >
, Iterator > super_t
Private Attributes
BigInteger step_
Related Functions
(Note that these are not member functions.)
template<class Iterator >
step_iterator< Iterator > make_step_iterator (Iterator it, Size step)
helper function to create step iterators
Detailed Description
template<class Iterator>
class QuantLib::step_iterator< Iterator >
Iterator advancing in constant steps.
This iterator advances an underlying random-access iterator in steps of \(n \) positions, where \(n \) is a positive integer given upon construction.
Definition at line 38 of file steppingiterator.hpp.
Member Typedef Documentation
template<class Iterator> typedef boost::iterator_adaptor<step_iterator<Iterator>, Iterator> QuantLib::step_iterator< Iterator >::super_t [private]
Definition at line 42 of file steppingiterator.hpp.
Constructor & Destructor Documentation
template<class Iterator> QuantLib::step_iterator< Iterator >::step_iterator () [inline]
Definition at line 46 of file steppingiterator.hpp.
{}
template<class Iterator> QuantLib::step_iterator< Iterator >::step_iterator (const Iterator & base, Size step) [inline, explicit]
Definition at line 47 of file steppingiterator.hpp.
        : super_t(base), step_(static_cast<BigInteger>(step)) {}
template<class Iterator> template<class OtherIterator > QuantLib::step_iterator< Iterator >::step_iterator (const step_iterator< OtherIterator > & i, typename boost::enable_if_convertible< OtherIterator, Iterator >::type * = 0) [inline]
Definition at line 50 of file steppingiterator.hpp.
        : super_t(i.base()), step_(static_cast<BigInteger>(i.step())) {}
Member Function Documentation
template<class Iterator> void QuantLib::step_iterator< Iterator >::advance (typename super_t::difference_type n) [inline]
Definition at line 63 of file steppingiterator.hpp.
References QuantLib::step_iterator< Iterator >::step_.
Referenced by QuantLib::step_iterator< Iterator >::decrement(), and QuantLib::step_iterator< Iterator >::increment().
{
            this->base_reference() += n*(this->step_);
        }
template<class Iterator> void QuantLib::step_iterator< Iterator >::decrement () [inline]
Definition at line 60 of file steppingiterator.hpp.
References QuantLib::step_iterator< Iterator >::advance(), and QuantLib::step_iterator< Iterator >::step_.
{
            std::advance(this->base_reference(), -step_);
        }
template<class Iterator> super_t::difference_type QuantLib::step_iterator< Iterator >::distance_to (const step_iterator< Iterator > & i) const [inline]
Definition at line 67 of file steppingiterator.hpp.
References QuantLib::step_iterator< Iterator >::step_.
{
            return (i.base()-this->base())/(this->step_);
        }
template<class Iterator> void QuantLib::step_iterator< Iterator >::increment () [inline]
Definition at line 57 of file steppingiterator.hpp.
References QuantLib::step_iterator< Iterator >::advance(), and QuantLib::step_iterator< Iterator >::step_.
{
            std::advance(this->base_reference(), step_);
        }
template<class Iterator> Size QuantLib::step_iterator< Iterator >::step () const [inline]
Definition at line 55 of file steppingiterator.hpp.
References QuantLib::step_iterator< Iterator >::step_.
{ return static_cast<Size>(this->step_); }
Friends And Related Function Documentation
template<class Iterator > step_iterator< Iterator > make_step_iterator (Iterator it, Size step) [related]
helper function to create step iterators
Definition at line 75 of file steppingiterator.hpp.
{
        return step_iterator<Iterator>(it,step);
    }
Member Data Documentation
template<class Iterator> BigInteger QuantLib::step_iterator< Iterator >::step_ [private]
Definition at line 44 of file steppingiterator.hpp.
Referenced by QuantLib::step_iterator< Iterator >::advance(), QuantLib::step_iterator< Iterator >::decrement(), QuantLib::step_iterator< Iterator >::distance_to(), QuantLib::step_iterator< Iterator >::increment(), and QuantLib::step_iterator< Iterator >::step().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/utilities/steppingiterator.hpp