QuantLib: QuantLib::AnalyticEuropeanEngine Class Reference
QuantLib::AnalyticEuropeanEngine Class Reference
Pricing engine for European vanilla options using analytical formulae.
#include <analyticeuropeanengine.hpp>
Public Member Functions
AnalyticEuropeanEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > &)
void calculate () const
Private Attributes
boost::shared_ptr
< GeneralizedBlackScholesProcess > process_
Detailed Description
Pricing engine for European vanilla options using analytical formulae.
Test:
the correctness of the returned value is tested by reproducing results available in literature.
the correctness of the returned greeks is tested by reproducing results available in literature.
the correctness of the returned greeks is tested by reproducing numerical derivatives.
the correctness of the returned implied volatility is tested by using it for reproducing the target value.
the implied-volatility calculation is tested by checking that it does not modify the option.
the correctness of the returned value in case of cash-or-nothing digital payoff is tested by reproducing results available in literature.
the correctness of the returned value in case of asset-or-nothing digital payoff is tested by reproducing results available in literature.
the correctness of the returned value in case of gap digital payoff is tested by reproducing results available in literature.
the correctness of the returned greeks in case of cash-or-nothing digital payoff is tested by reproducing numerical derivatives.
Definition at line 61 of file analyticeuropeanengine.hpp.
Constructor & Destructor Documentation
QuantLib::AnalyticEuropeanEngine::AnalyticEuropeanEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > & process)
Definition at line 27 of file analyticeuropeanengine.cpp.
References process_.
    : process_(process) {
        registerWith(process_);
    }
Member Function Documentation
void QuantLib::AnalyticEuropeanEngine::calculate () const
Definition at line 33 of file analyticeuropeanengine.cpp.
References QuantLib::BlackCalculator::delta(), QuantLib::BlackCalculator::deltaForward(), QuantLib::BlackCalculator::dividendRho(), QuantLib::BlackCalculator::elasticity(), QuantLib::Exercise::European, QuantLib::BlackCalculator::gamma(), QuantLib::BlackCalculator::itmCashProbability(), process_, QL_REQUIRE, QuantLib::BlackCalculator::rho(), QuantLib::BlackCalculator::strikeSensitivity(), anonymous_namespace{quantlibbenchmark.cpp}::t, QuantLib::BlackCalculator::theta(), QuantLib::BlackCalculator::thetaPerDay(), QuantLib::BlackCalculator::value(), QuantLib::BlackCalculator::vega(), and QuantLib::DayCounter::yearFraction().
Referenced by QuantLib::JumpDiffusionEngine::calculate().
{
        QL_REQUIRE(arguments_.exercise->type() == Exercise::European,
                   "not an European option");
        boost::shared_ptr<StrikedTypePayoff> payoff =
            boost::dynamic_pointer_cast<StrikedTypePayoff>(arguments_.payoff);
        QL_REQUIRE(payoff, "non-striked payoff given");
        Real variance =
            process_->blackVolatility()->blackVariance(
                                              arguments_.exercise->lastDate(),
                                              payoff->strike());
        DiscountFactor dividendDiscount =
            process_->dividendYield()->discount(
                                             arguments_.exercise->lastDate());
        DiscountFactor riskFreeDiscount =
            process_->riskFreeRate()->discount(arguments_.exercise->lastDate());
        Real spot = process_->stateVariable()->value();
        QL_REQUIRE(spot > 0.0, "negative or null underlying given");
        Real forwardPrice = spot * dividendDiscount / riskFreeDiscount;
        BlackCalculator black(payoff, forwardPrice, std::sqrt(variance),
                              riskFreeDiscount);
        results_.value = black.value();
        results_.delta = black.delta(spot);
        results_.deltaForward = black.deltaForward();
        results_.elasticity = black.elasticity(spot);
        results_.gamma = black.gamma(spot);
        DayCounter rfdc  = process_->riskFreeRate()->dayCounter();
        DayCounter divdc = process_->dividendYield()->dayCounter();
        DayCounter voldc = process_->blackVolatility()->dayCounter();
        Time t = rfdc.yearFraction(process_->riskFreeRate()->referenceDate(),
                                   arguments_.exercise->lastDate());
        results_.rho = black.rho(t);
        t = divdc.yearFraction(process_->dividendYield()->referenceDate(),
                               arguments_.exercise->lastDate());
        results_.dividendRho = black.dividendRho(t);
        t = voldc.yearFraction(process_->blackVolatility()->referenceDate(),
                               arguments_.exercise->lastDate());
        results_.vega = black.vega(t);
        try {
            results_.theta = black.theta(spot, t);
            results_.thetaPerDay =
                black.thetaPerDay(spot, t);
        } catch (Error&) {
            results_.theta = Null<Real>();
            results_.thetaPerDay = Null<Real>();
        }
        results_.strikeSensitivity  = black.strikeSensitivity();
        results_.itmCashProbability = black.itmCashProbability();
    }
Member Data Documentation
boost::shared_ptr<GeneralizedBlackScholesProcess> QuantLib::AnalyticEuropeanEngine::process_ [private]
Definition at line 67 of file analyticeuropeanengine.hpp.
Referenced by AnalyticEuropeanEngine(), and calculate().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/vanilla/analyticeuropeanengine.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/vanilla/analyticeuropeanengine.cpp