QuantLib: QuantLib::DatedOISRateHelper Class Reference
QuantLib::DatedOISRateHelper Class Reference
Rate helper for bootstrapping over Overnight Indexed Swap rates.
#include <oisratehelper.hpp>
Public Member Functions
DatedOISRateHelper (const Date &startDate, const Date &endDate, const Handle< Quote > &fixedRate, const boost::shared_ptr< OvernightIndex > &overnightIndex)
RateHelper interface
Real impliedQuote () const
void setTermStructure (YieldTermStructure *)
Visitability
void accept (AcyclicVisitor &)
Protected Attributes
boost::shared_ptr
< OvernightIndexedSwap > swap_
RelinkableHandle
< YieldTermStructure > termStructureHandle_
Detailed Description
Rate helper for bootstrapping over Overnight Indexed Swap rates.
Definition at line 65 of file oisratehelper.hpp.
Constructor & Destructor Documentation
QuantLib::DatedOISRateHelper::DatedOISRateHelper (const Date & startDate, const Date & endDate, const Handle< Quote > & fixedRate, const boost::shared_ptr< OvernightIndex > & overnightIndex)
Definition at line 87 of file oisratehelper.cpp.
References QuantLib::BootstrapHelper< TS >::earliestDate_, QuantLib::BootstrapHelper< TS >::latestDate_, QuantLib::Observer::registerWith(), swap_, termStructureHandle_, QuantLib::MakeOIS::withDiscountingTermStructure(), QuantLib::MakeOIS::withEffectiveDate(), and QuantLib::MakeOIS::withTerminationDate().
    : RateHelper(fixedRate) {
        registerWith(overnightIndex);
        // dummy OvernightIndex with curve/swap arguments
        // review here
        boost::shared_ptr<IborIndex> clonedIborIndex =
            overnightIndex->clone(termStructureHandle_);
        shared_ptr<OvernightIndex> clonedOvernightIndex =
            boost::dynamic_pointer_cast<OvernightIndex>(clonedIborIndex);
       swap_ = MakeOIS(Period(), clonedOvernightIndex, 0.0)
           .withEffectiveDate(startDate)
           .withTerminationDate(endDate)
           .withDiscountingTermStructure(termStructureHandle_);
        earliestDate_ = swap_->startDate();
        latestDate_ = swap_->maturityDate();
    }
Member Function Documentation
void QuantLib::DatedOISRateHelper::accept (AcyclicVisitor & v) [virtual]
Reimplemented from QuantLib::BootstrapHelper< TS >.
Definition at line 128 of file oisratehelper.cpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Visitor< T >::visit().
{
        Visitor<DatedOISRateHelper>* v1 =
            dynamic_cast<Visitor<DatedOISRateHelper>*>(&v);
        if (v1 != 0)
            v1->visit(*this);
        else
            RateHelper::accept(v);
    }
Real QuantLib::DatedOISRateHelper::impliedQuote () const [virtual]
Implements QuantLib::BootstrapHelper< TS >.
Definition at line 121 of file oisratehelper.cpp.
References QL_REQUIRE, swap_, and QuantLib::BootstrapHelper< TS >::termStructure_.
{
        QL_REQUIRE(termStructure_ != 0, "term structure not set");
        // we didn't register as observers - force calculation
        swap_->recalculate();
        return swap_->fairRate();
    }
void QuantLib::DatedOISRateHelper::setTermStructure (YieldTermStructure * t)
Definition at line 112 of file oisratehelper.cpp.
References QuantLib::RelinkableHandle< T >::linkTo(), QuantLib::anonymous_namespace{riskyassetswap.cpp}::no_deletion(), and termStructureHandle_.
{
        // do not set the relinkable handle as an observer -
        // force recalculation when needed
        termStructureHandle_.linkTo(
                         shared_ptr<YieldTermStructure>(t,no_deletion),
                         false);
        RateHelper::setTermStructure(t);
    }
Member Data Documentation
boost::shared_ptr<OvernightIndexedSwap> QuantLib::DatedOISRateHelper::swap_ [protected]
Definition at line 82 of file oisratehelper.hpp.
Referenced by DatedOISRateHelper(), and impliedQuote().
RelinkableHandle<YieldTermStructure> QuantLib::DatedOISRateHelper::termStructureHandle_ [protected]
Definition at line 83 of file oisratehelper.hpp.
Referenced by DatedOISRateHelper(), and setTermStructure().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/yield/oisratehelper.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/yield/oisratehelper.cpp