QuantLib: QuantLib::FFTEngine Class Reference
QuantLib::FFTEngine Class Reference
Base class for FFT pricing engines for European vanilla options.
#include <fftengine.hpp>
Public Member Functions
FFTEngine (const boost::shared_ptr< StochasticProcess1D > &process, Real logStrikeSpacing)
void calculate () const
void update ()
void precalculate (const std::vector< boost::shared_ptr< Instrument > > &optionList)
virtual std::auto_ptr< FFTEngine > clone () const =0
Protected Member Functions
virtual void precalculateExpiry (Date d)=0
virtual std::complex< Real > complexFourierTransform (std::complex< Real > u) const =0
virtual Real discountFactor (Date d) const =0
virtual Real dividendYield (Date d) const =0
void calculateUncached (boost::shared_ptr< StrikedTypePayoff > payoff, boost::shared_ptr< Exercise > exercise) const
Protected Attributes
boost::shared_ptr
< StochasticProcess1D > process_
Real lambda_
Private Types
typedef std::map
< boost::shared_ptr
< StrikedTypePayoff >, Real > PayoffResultMap
typedef std::map< Date,
PayoffResultMap > ResultMap
Private Attributes
ResultMap resultMap_
Detailed Description
Base class for FFT pricing engines for European vanilla options.
The FFT engine calculates the values of all options with the same expiry at the same time. For that reason it is very inefficient to price options individually. When using this engine you should collect all the options you wish to price in a list and call the engine's precalculate method before calling the NPV method of the option.
References: Carr, P. and D. B. Madan (1998), "Option Valuation using the fast Fourier transform," Journal of Computational Finance, 2, 61-73.
Definition at line 47 of file fftengine.hpp.
Member Typedef Documentation
typedef std::map<boost::shared_ptr<StrikedTypePayoff>, Real> QuantLib::FFTEngine::PayoffResultMap [private]
Definition at line 70 of file fftengine.hpp.
typedef std::map<Date, PayoffResultMap> QuantLib::FFTEngine::ResultMap [private]
Definition at line 71 of file fftengine.hpp.
Constructor & Destructor Documentation
QuantLib::FFTEngine::FFTEngine (const boost::shared_ptr< StochasticProcess1D > & process, Real logStrikeSpacing)
Definition at line 28 of file fftengine.cpp.
References process_.
        : process_(process), lambda_(logStrikeSpacing) {
            registerWith(process_);
    }
Member Function Documentation
void QuantLib::FFTEngine::calculate () const
Definition at line 34 of file fftengine.cpp.
References calculateUncached(), QuantLib::Exercise::European, QL_REQUIRE, and resultMap_.
    {
        QL_REQUIRE(arguments_.exercise->type() == Exercise::European,
            "not an European Option");
        boost::shared_ptr<StrikedTypePayoff> payoff =
            boost::dynamic_pointer_cast<StrikedTypePayoff>(arguments_.payoff);
        QL_REQUIRE(payoff, "non-striked payoff given");
        ResultMap::const_iterator r1 = resultMap_.find(arguments_.exercise->lastDate());
        if (r1 != resultMap_.end())
        {
            PayoffResultMap::const_iterator r2 = r1->second.find(payoff);
            if (r2 != r1->second.end())
            {
                results_.value = r2->second;
                return;
            }
        }
        // Option not precalculated - do entire FFT for one option.  Not very efficient - call precalculate!
        calculateUncached(payoff, arguments_.exercise);
    }
void QuantLib::FFTEngine::calculateUncached (boost::shared_ptr< StrikedTypePayoff > payoff, boost::shared_ptr< Exercise > exercise) const [protected]
Definition at line 67 of file fftengine.cpp.
References clone().
Referenced by calculate().
    {
        boost::shared_ptr<VanillaOption> option(new VanillaOption(payoff, exercise));
        std::vector<boost::shared_ptr<Instrument> > optionList;
        optionList.push_back(option);
        boost::shared_ptr<FFTEngine> tempEngine(clone().release());
        tempEngine->precalculate(optionList);
        option->setPricingEngine(tempEngine);
        results_.value = option->NPV();
    }
virtual std::auto_ptr<FFTEngine> QuantLib::FFTEngine::clone () const [pure virtual]
Implemented in QuantLib::FFTVanillaEngine, and QuantLib::FFTVarianceGammaEngine.
Referenced by calculateUncached().
virtual std::complex<Real> QuantLib::FFTEngine::complexFourierTransform (std::complex< Real > u) const [protected, pure virtual]
Implemented in QuantLib::FFTVanillaEngine, and QuantLib::FFTVarianceGammaEngine.
Referenced by precalculate().
virtual Real QuantLib::FFTEngine::discountFactor (Date d) const [protected, pure virtual]
Implemented in QuantLib::FFTVanillaEngine, and QuantLib::FFTVarianceGammaEngine.
Referenced by precalculate().
virtual Real QuantLib::FFTEngine::dividendYield (Date d) const [protected, pure virtual]
Implemented in QuantLib::FFTVanillaEngine, and QuantLib::FFTVarianceGammaEngine.
Referenced by precalculate().
void QuantLib::FFTEngine::precalculate (const std::vector< boost::shared_ptr< Instrument > > & optionList)
Definition at line 80 of file fftengine.cpp.
References anonymous_namespace{marketmodel.cpp}::b, QuantLib::Option::Call, complexFourierTransform(), discountFactor(), dividendYield(), QuantLib::Exercise::European, lambda_, M_PI, precalculateExpiry(), process_, QuantLib::Option::Put, QL_FAIL, QL_REQUIRE, resultMap_, and QuantLib::FastFourierTransform::transform().
{
        // Group payoffs by expiry date
        // as with FFT we can compute a bunch of these at once
        resultMap_.clear();
        typedef std::vector<boost::shared_ptr<StrikedTypePayoff> > PayoffList;
        typedef std::map<Date, PayoffList> PayoffMap;
        PayoffMap payoffMap;
        for (std::vector<boost::shared_ptr<Instrument> >::const_iterator optIt = optionList.begin();
            optIt != optionList.end(); optIt++)
        {
            boost::shared_ptr<VanillaOption> option = boost::dynamic_pointer_cast<VanillaOption>(*optIt);
            QL_REQUIRE(option, "instrument must be option");
            QL_REQUIRE(option->exercise()->type() == Exercise::European,
                "not an European Option");
            boost::shared_ptr<StrikedTypePayoff> payoff =
                boost::dynamic_pointer_cast<StrikedTypePayoff>(option->payoff());
            QL_REQUIRE(payoff, "non-striked payoff given");
            payoffMap[option->exercise()->lastDate()].push_back(payoff);
        }
        std::complex<Real> i1(0, 1);
        Real alpha = 1.25;
        for (PayoffMap::const_iterator payIt = payoffMap.begin(); payIt != payoffMap.end(); payIt++)
        {
            Date expiryDate = payIt->first;
            // Calculate n large enough for maximum strike, and round up to a power of 2
            Real maxStrike = 0.0;
            for (PayoffList::const_iterator it = payIt->second.begin();
                it != payIt->second.end(); it++)
            {
                boost::shared_ptr<StrikedTypePayoff> payoff = *it;
                if (payoff->strike() > maxStrike)
                    maxStrike = payoff->strike();
            }
            Real nR = 2.0 * (std::log(maxStrike) + lambda_) / lambda_;
      Size log2_n = (static_cast<Size>((std::log(nR) / std::log(2.0))) + 1);
            Size n = 1 << log2_n;
            // Strike range (equation 19,20)
            Real b = n * lambda_ / 2.0;
            // Grid spacing (equation 23)
            Real eta = 2.0 * M_PI / (lambda_ * n);
            // Discount factor
            Real df = discountFactor(expiryDate);
            Real div = dividendYield(expiryDate);
            // Input to fourier transform
            std::vector<std::complex<Real> > fti;
            fti.resize(n);
            // Precalculate any discount factors etc.
            precalculateExpiry(expiryDate);
            for (Size i=0; i<n; i++)
            {
                Real v_j = eta * i;
                Real sw = eta * (3.0 + ((i % 2) == 0 ? -1.0 : 1.0) - ((i == 0) ? 1.0 : 0.0)) / 3.0;
                std::complex<Real> psi = df * complexFourierTransform(v_j - (alpha + 1)* i1);
                psi = psi / (alpha*alpha + alpha - v_j*v_j + i1 * (2 * alpha + 1.0) * v_j);
                fti[i] = std::exp(i1 * b * v_j)  * sw * psi;
            }
            // Perform fft
            std::vector<std::complex<Real> > results(n);
            FastFourierTransform fft(log2_n);
            fft.transform(fti.begin(), fti.end(), results.begin());
            // Call prices
            std::vector<Real> prices, strikes;
            prices.resize(n);
            strikes.resize(n);
            for (Size i=0; i<n; i++)
            {
                Real k_u = -b + lambda_ * i;
                prices[i] = (std::exp(-alpha * k_u) / M_PI) * results[i].real();
                strikes[i] = std::exp(k_u);
            }
            for (PayoffList::const_iterator it = payIt->second.begin();
                it != payIt->second.end(); it++)
            {
                boost::shared_ptr<StrikedTypePayoff> payoff = *it;
                Real callPrice = LinearInterpolation(strikes.begin(), strikes.end(), prices.begin())(payoff->strike());
                switch (payoff->optionType())
                {
                case Option::Call:
                    resultMap_[expiryDate][payoff] = callPrice;
                    break;
                case Option::Put:
                    resultMap_[expiryDate][payoff] = callPrice - process_->x0() * div + payoff->strike() * df;
                    break;
                default:
                    QL_FAIL("Invalid option type");
                }
            }
        }
    }
virtual void QuantLib::FFTEngine::precalculateExpiry (Date d) [protected, pure virtual]
Implemented in QuantLib::FFTVanillaEngine, and QuantLib::FFTVarianceGammaEngine.
Referenced by precalculate().
void QuantLib::FFTEngine::update ()
Definition at line 58 of file fftengine.cpp.
References resultMap_.
    {
        // Process has changed so cached values may no longer be correct
        resultMap_.clear();
        // Call base class implementation
        VanillaOption::engine::update();
    }
Member Data Documentation
Real QuantLib::FFTEngine::lambda_ [protected]
Definition at line 67 of file fftengine.hpp.
Referenced by QuantLib::FFTVanillaEngine::clone(), QuantLib::FFTVarianceGammaEngine::clone(), and precalculate().
boost::shared_ptr<StochasticProcess1D> QuantLib::FFTEngine::process_ [protected]
Definition at line 66 of file fftengine.hpp.
Referenced by QuantLib::FFTVanillaEngine::clone(), QuantLib::FFTVarianceGammaEngine::clone(), QuantLib::FFTVanillaEngine::complexFourierTransform(), QuantLib::FFTVarianceGammaEngine::complexFourierTransform(), QuantLib::FFTVarianceGammaEngine::discountFactor(), QuantLib::FFTVanillaEngine::discountFactor(), QuantLib::FFTVanillaEngine::dividendYield(), QuantLib::FFTVarianceGammaEngine::dividendYield(), FFTEngine(), precalculate(), QuantLib::FFTVanillaEngine::precalculateExpiry(), and QuantLib::FFTVarianceGammaEngine::precalculateExpiry().
ResultMap QuantLib::FFTEngine::resultMap_ [private]
Definition at line 72 of file fftengine.hpp.
Referenced by calculate(), precalculate(), and update().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/variancegamma/fftengine.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/variancegamma/fftengine.cpp