QuantLib: QuantLib::DefaultType Class Reference
QuantLib::DefaultType Class Reference
Atomic credit-event type.
#include <defaulttype.hpp>
Public Member Functions
DefaultType (AtomicDefault::Type defType=AtomicDefault::Bankruptcy, Restructuring::Type restType=Restructuring::XR)
virtual ~DefaultType ()
AtomicDefault::Type defaultType () const
Restructuring::Type restructuringType () const
bool isRestructuring () const
bool containsDefaultType (AtomicDefault::Type defType) const
bool containsRestructuringType (Restructuring::Type resType) const
Protected Attributes
AtomicDefault::Type defTypes_
Restructuring::Type restrType_
Detailed Description
Atomic credit-event type.
This class encapsulates the ISDA default contractual types and their combinations. Non-atomicity works only at the atomic type level, obviating the specific event characteristics which it is accounted for only in derived classes.
Definition at line 106 of file defaulttype.hpp.
Constructor & Destructor Documentation
QuantLib::DefaultType::DefaultType (AtomicDefault::Type defType = AtomicDefault::Bankruptcy, Restructuring::Type restType = Restructuring::XR) [explicit]
Definition at line 26 of file defaulttype.cpp.
References QuantLib::Restructuring::NoRestructuring, QL_REQUIRE, restrType_, and QuantLib::AtomicDefault::Restructuring.
    : defTypes_(defType), restrType_(restType) {
        // checks restruct and norestruct are never together.
        QL_REQUIRE((defType == AtomicDefault::Restructuring) != // xor
                   (restrType_ == Restructuring::NoRestructuring),
                   "Incoherent credit event type definition.");
    }
virtual QuantLib::DefaultType::~DefaultType () [inline, virtual]
Definition at line 112 of file defaulttype.hpp.
{}
Member Function Documentation
bool QuantLib::DefaultType::containsDefaultType (AtomicDefault::Type defType) const [inline]
Returns true if one or a set of event types is within this one and as such will be recognised as a trigger. Not the same as equality.
Notice that these methods do not include any event logical hierarchy. The match is in a strict sense. If event B is contained in (implied by) event A this would not send a match. This policies should be implemented at the CreditEvent class, which is polymorphic.
Definition at line 134 of file defaulttype.hpp.
References defTypes_.
{
            return defTypes_ ==  defType;
        }
bool QuantLib::DefaultType::containsRestructuringType (Restructuring::Type resType) const [inline]
Definition at line 138 of file defaulttype.hpp.
References QuantLib::Restructuring::AnyRestructuring, and restrType_.
{
            return (restrType_ == resType) ||
                (Restructuring::AnyRestructuring == resType);
        }
AtomicDefault::Type QuantLib::DefaultType::defaultType () const [inline]
Definition at line 114 of file defaulttype.hpp.
References defTypes_.
Referenced by QuantLib::DefaultEvent::matchesEventType(), and QuantLib::operator==().
{
            return defTypes_;
        }
bool QuantLib::DefaultType::isRestructuring () const [inline]
Definition at line 118 of file defaulttype.hpp.
References QuantLib::Restructuring::NoRestructuring, and restrType_.
Referenced by QuantLib::DefaultEvent::isRestructuring().
{
            return restrType_ != Restructuring::NoRestructuring;
        }
Restructuring::Type QuantLib::DefaultType::restructuringType () const [inline]
Definition at line 117 of file defaulttype.hpp.
References restrType_.
Referenced by QuantLib::DefaultEvent::matchesEventType(), and QuantLib::operator==().
{return restrType_;}
Member Data Documentation
AtomicDefault::Type QuantLib::DefaultType::defTypes_ [protected]
Definition at line 144 of file defaulttype.hpp.
Referenced by containsDefaultType(), and defaultType().
Restructuring::Type QuantLib::DefaultType::restrType_ [protected]
Definition at line 145 of file defaulttype.hpp.
Referenced by containsRestructuringType(), DefaultType(), isRestructuring(), and restructuringType().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/defaulttype.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/defaulttype.cpp