QuantLib: QuantLib::SimpleDayCounter::Impl Class Reference
QuantLib::SimpleDayCounter::Impl Class Reference
Public Member Functions
std::string name () const
BigInteger dayCount (const Date &d1, const Date &d2) const
to be overloaded by more complex day counters
Time yearFraction (const Date &d1, const Date &d2, const Date &, const Date &) const
Detailed Description
Definition at line 48 of file simpledaycounter.hpp.
Member Function Documentation
BigInteger QuantLib::SimpleDayCounter::Impl::dayCount (const Date & d1, const Date & d2) const [virtual]
to be overloaded by more complex day counters
Reimplemented from QuantLib::DayCounter::Impl.
Definition at line 27 of file simpledaycounter.cpp.
References QuantLib::DayCounter::dayCount(), and QuantLib::anonymous_namespace{simpledaycounter.cpp}::fallback.
{
        return fallback.dayCount(d1,d2);
    }
std::string QuantLib::SimpleDayCounter::Impl::name () const [inline, virtual]
Implements QuantLib::DayCounter::Impl.
Definition at line 50 of file simpledaycounter.hpp.
{ return "Simple"; }
Time QuantLib::SimpleDayCounter::Impl::yearFraction (const Date & d1, const Date & d2, const Date & , const Date &) const [virtual]
Implements QuantLib::DayCounter::Impl.
Definition at line 32 of file simpledaycounter.cpp.
References QuantLib::Date::dayOfMonth(), QuantLib::anonymous_namespace{simpledaycounter.cpp}::fallback, QuantLib::Date::isEndOfMonth(), QuantLib::Date::month(), QuantLib::Date::year(), and QuantLib::DayCounter::yearFraction().
{
        Day dm1 = d1.dayOfMonth(),
            dm2 = d2.dayOfMonth();
        if (dm1 == dm2 ||
            // e.g., Aug 30 -> Feb 28 ?
            (dm1 > dm2 && Date::isEndOfMonth(d2)) ||
            // e.g., Feb 28 -> Aug 30 ?
            (dm1 < dm2 && Date::isEndOfMonth(d1))) {
            return (d2.year()-d1.year()) +
                (Integer(d2.month())-Integer(d1.month()))/12.0;
        } else {
            return fallback.yearFraction(d1,d2);
        }
    }
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/time/daycounters/simpledaycounter.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/time/daycounters/simpledaycounter.cpp