QuantLib: QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel > Class Template Reference
QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel > Class Template Reference
#include <kernelinterpolation.hpp>
Public Member Functions
KernelInterpolationImpl (const I1 &xBegin, const I1 &xEnd, const I2 &yBegin, const Kernel &kernel)
void update ()
Real value (Real x) const
Real primitive (Real) const
Real derivative (Real) const
Real secondDerivative (Real) const
void setInverseResultPrecision (Real invPrec)
Private Member Functions
Real kernelAbs (Real x1, Real x2) const
Real gammaFunc (Real x) const
void updateAlphaVec ()
Private Attributes
Size xSize_
Real invPrec_
Matrix M_
Array alphaVec_
Array yVec_
Kernel kernel_
Detailed Description
template<class I1, class I2, class Kernel>
class QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >
Definition at line 36 of file kernelinterpolation.hpp.
Constructor & Destructor Documentation
template<class I1 , class I2 , class Kernel > QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::KernelInterpolationImpl (const I1 & xBegin, const I1 & xEnd, const I2 & yBegin, const Kernel & kernel) [inline]
Definition at line 39 of file kernelinterpolation.hpp.
            : Interpolation::templateImpl<I1,I2>(xBegin, xEnd, yBegin),
              xSize_(Size(xEnd-xBegin)),invPrec_(1.0e-7),
              M_(xSize_,xSize_), alphaVec_(xSize_), yVec_(xSize_),
              kernel_(kernel) {}
Member Function Documentation
template<class I1 , class I2 , class Kernel > Real QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::derivative (Real) const [inline, virtual]
Implements QuantLib::Interpolation::Impl.
Definition at line 67 of file kernelinterpolation.hpp.
References QL_FAIL.
{
                QL_FAIL("First derivative calculation not implemented "
                        "for kernel interpolation");
            }
template<class I1 , class I2 , class Kernel > Real QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::gammaFunc (Real x) const [inline, private]
Definition at line 92 of file kernelinterpolation.hpp.
References QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::kernelAbs(), QuantLib::Interpolation::templateImpl< I1, I2 >::xBegin_, and QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::xSize_.
Referenced by QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::updateAlphaVec(), and QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::value().
{
                Real res=0.0;
                for(Size i=0; i< xSize_;++i){
                    res+=kernelAbs(x,this->xBegin_[i]);
                }
                return res;
            }
template<class I1 , class I2 , class Kernel > Real QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::kernelAbs (Real x1, Real x2) const [inline, private]
Definition at line 88 of file kernelinterpolation.hpp.
References QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::kernel_.
Referenced by QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::gammaFunc(), QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::updateAlphaVec(), and QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::value().
{
                return kernel_(std::fabs(x1-x2));
            }
template<class I1 , class I2 , class Kernel > Real QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::primitive (Real) const [inline, virtual]
Implements QuantLib::Interpolation::Impl.
Definition at line 62 of file kernelinterpolation.hpp.
References QL_FAIL.
{
                QL_FAIL("Primitive calculation not implemented "
                        "for kernel interpolation");
            }
template<class I1 , class I2 , class Kernel > Real QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::secondDerivative (Real) const [inline, virtual]
Implements QuantLib::Interpolation::Impl.
Definition at line 72 of file kernelinterpolation.hpp.
References QL_FAIL.
{
                QL_FAIL("Second derivative calculation not implemented "
                        "for kernel interpolation");
            }
template<class I1 , class I2 , class Kernel > void QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::setInverseResultPrecision (Real invPrec) [inline]
Definition at line 82 of file kernelinterpolation.hpp.
References QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::invPrec_.
{
                invPrec_=invPrec;
            }
template<class I1 , class I2 , class Kernel > void QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::update () [inline, virtual]
Implements QuantLib::Interpolation::Impl.
Definition at line 47 of file kernelinterpolation.hpp.
References QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::updateAlphaVec().
{
                updateAlphaVec();
            }
template<class I1 , class I2 , class Kernel > void QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::updateAlphaVec () [inline, private]
Definition at line 102 of file kernelinterpolation.hpp.
References QuantLib::Abs(), QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::alphaVec_, QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::gammaFunc(), QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::invPrec_, QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::kernelAbs(), QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::M_, QL_REQUIRE, QuantLib::qrSolve(), QuantLib::Array::size(), QuantLib::Interpolation::templateImpl< I1, I2 >::xBegin_, QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::xSize_, QuantLib::Interpolation::templateImpl< I1, I2 >::yBegin_, and QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::yVec_.
Referenced by QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::update().
{
                // Function calculates the alpha vector with given
                // fixed pillars+values
                // Write Matrix M
                Real tmp=0.0;
                for(Size rowIt=0; rowIt<xSize_;++rowIt){
                    yVec_[rowIt]=this->yBegin_[rowIt];
                    tmp=1.0/gammaFunc(this->xBegin_[rowIt]);
                    for(Size colIt=0; colIt<xSize_;++colIt){
                        M_[rowIt][colIt]=kernelAbs(this->xBegin_[rowIt],
                                                   this->xBegin_[colIt])*tmp;
                    }
                }
                // Solve y=M*\alpha for \alpha
                alphaVec_ = qrSolve(M_, yVec_);
                // check if inversion worked up to a reasonable precision.
                // I've chosen not to check determinant(M_)!=0 before solving
                Array diffVec=Abs(M_*alphaVec_ - yVec_);
                for (Size i=0; i<diffVec.size(); ++i) {
                    QL_REQUIRE(diffVec[i] < invPrec_,
                               "Inversion failed in 1d kernel interpolation");
                }
            }
template<class I1 , class I2 , class Kernel > Real QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::value (Real x) const [inline, virtual]
Implements QuantLib::Interpolation::Impl.
Definition at line 51 of file kernelinterpolation.hpp.
References QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::alphaVec_, QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::gammaFunc(), QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::kernelAbs(), QuantLib::Interpolation::templateImpl< I1, I2 >::xBegin_, and QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::xSize_.
{
                Real res=0.0;
                for( Size i=0; i< xSize_;++i){
                    res+=alphaVec_[i]*kernelAbs(x,this->xBegin_[i]);
                }
                return res/gammaFunc(x);
            }
Member Data Documentation
template<class I1 , class I2 , class Kernel > Array QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::alphaVec_ [private]
Definition at line 137 of file kernelinterpolation.hpp.
Referenced by QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::updateAlphaVec(), and QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::value().
template<class I1 , class I2 , class Kernel > Real QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::invPrec_ [private]
Definition at line 135 of file kernelinterpolation.hpp.
Referenced by QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::setInverseResultPrecision(), and QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::updateAlphaVec().
template<class I1 , class I2 , class Kernel > Kernel QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::kernel_ [private]
Definition at line 138 of file kernelinterpolation.hpp.
Referenced by QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::kernelAbs().
template<class I1 , class I2 , class Kernel > Matrix QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::M_ [private]
Definition at line 136 of file kernelinterpolation.hpp.
Referenced by QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::updateAlphaVec().
template<class I1 , class I2 , class Kernel > Size QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::xSize_ [private]
Definition at line 134 of file kernelinterpolation.hpp.
Referenced by QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::gammaFunc(), QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::updateAlphaVec(), and QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::value().
template<class I1 , class I2 , class Kernel > Array QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::yVec_ [private]
Definition at line 137 of file kernelinterpolation.hpp.
Referenced by QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::updateAlphaVec().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/interpolations/kernelinterpolation.hpp