QuantLib: QuantLib::OneStepOptionlets Class Reference
QuantLib::OneStepOptionlets Class Reference
#include <onestepoptionlets.hpp>
Public Member Functions
OneStepOptionlets (const std::vector< Time > &rateTimes, const std::vector< Real > &accruals, const std::vector< Time > &paymentTimes, const std::vector< boost::shared_ptr< Payoff > > &)
MarketModelMultiProduct interface
std::vector< Time > possibleCashFlowTimes () const
Size numberOfProducts () const
Size maxNumberOfCashFlowsPerProductPerStep () const
void reset ()
during simulation put product at start of path
bool nextTimeStep (const CurveState &currentState, std::vector< Size > &numberCashFlowsThisStep, std::vector< std::vector< CashFlow > > &cashFlowsGenerated)
return value indicates whether path is finished, TRUE means done
std::auto_ptr
< MarketModelMultiProduct > clone () const
returns a newly-allocated copy of itself
Private Attributes
std::vector< Real > accruals_
std::vector< Time > paymentTimes_
std::vector< boost::shared_ptr
< Payoff > > payoffs_
Detailed Description
Definition at line 32 of file onestepoptionlets.hpp.
Constructor & Destructor Documentation
QuantLib::OneStepOptionlets::OneStepOptionlets (const std::vector< Time > & rateTimes, const std::vector< Real > & accruals, const std::vector< Time > & paymentTimes, const std::vector< boost::shared_ptr< Payoff > > & payoffs)
Definition at line 28 of file onestepoptionlets.cpp.
References QuantLib::checkIncreasingTimes().
Referenced by clone().
    : MultiProductOneStep(rateTimes), accruals_(accruals),
      paymentTimes_(paymentTimes), payoffs_(payoffs) {
        checkIncreasingTimes(paymentTimes);
    }
Member Function Documentation
std::auto_ptr< MarketModelMultiProduct > QuantLib::OneStepOptionlets::clone () const [virtual]
returns a newly-allocated copy of itself
Implements QuantLib::MarketModelMultiProduct.
Definition at line 58 of file onestepoptionlets.cpp.
References OneStepOptionlets().
{
        return std::auto_ptr<MarketModelMultiProduct>(
                                                   new OneStepOptionlets(*this));
    }
Size QuantLib::OneStepOptionlets::maxNumberOfCashFlowsPerProductPerStep () const [inline, virtual]
Implements QuantLib::MarketModelMultiProduct.
Definition at line 68 of file onestepoptionlets.hpp.
{
        return 1;
    }
bool QuantLib::OneStepOptionlets::nextTimeStep (const CurveState & currentState, std::vector< Size > & numberCashFlowsThisStep, std::vector< std::vector< CashFlow > > & cashFlowsGenerated) [virtual]
return value indicates whether path is finished, TRUE means done
Implements QuantLib::MarketModelMultiProduct.
Definition at line 38 of file onestepoptionlets.cpp.
References accruals_, QuantLib::CurveState::forwardRate(), and payoffs_.
{
        std::fill(numberCashFlowsThisStep.begin(),
                  numberCashFlowsThisStep.end(), 0);
        for (Size i=0; i<payoffs_.size(); ++i) {
            Rate liborRate = currentState.forwardRate(i);
            Real payoff = (*payoffs_[i])(liborRate);
            if (payoff>0.0) {
                numberCashFlowsThisStep[i] = 1;
                genCashFlows[i][0].timeIndex = i;
                genCashFlows[i][0].amount = payoff*accruals_[i];
            }
        }
        return true;
    }
Size QuantLib::OneStepOptionlets::numberOfProducts () const [inline, virtual]
Implements QuantLib::MarketModelMultiProduct.
Definition at line 63 of file onestepoptionlets.hpp.
References payoffs_.
{
        return payoffs_.size();
    }
std::vector< Time > QuantLib::OneStepOptionlets::possibleCashFlowTimes () const [inline, virtual]
Implements QuantLib::MarketModelMultiProduct.
Definition at line 59 of file onestepoptionlets.hpp.
References paymentTimes_.
{
      return paymentTimes_;
    }
void QuantLib::OneStepOptionlets::reset () [inline, virtual]
during simulation put product at start of path
Implements QuantLib::MarketModelMultiProduct.
Definition at line 72 of file onestepoptionlets.hpp.
{
        // nothing to do
    }
Member Data Documentation
std::vector<Real> QuantLib::OneStepOptionlets::accruals_ [private]
Definition at line 51 of file onestepoptionlets.hpp.
Referenced by nextTimeStep().
std::vector<Time> QuantLib::OneStepOptionlets::paymentTimes_ [private]
Definition at line 52 of file onestepoptionlets.hpp.
Referenced by possibleCashFlowTimes().
std::vector<boost::shared_ptr<Payoff> > QuantLib::OneStepOptionlets::payoffs_ [private]
Definition at line 53 of file onestepoptionlets.hpp.
Referenced by nextTimeStep(), and numberOfProducts().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/products/onestep/onestepoptionlets.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/products/onestep/onestepoptionlets.cpp