QuantLib: QuantLib::anonymous_namespace{overnightindexedcoupon.cpp}::OvernightIndexedCouponPricer Class Reference
QuantLib::anonymous_namespace{overnightindexedcoupon.cpp}::OvernightIndexedCouponPricer Class Reference
Public Member Functions
void initialize (const FloatingRateCoupon &coupon)
Rate swapletRate () const
Real swapletPrice () const
Real capletPrice (Rate) const
Rate capletRate (Rate) const
Real floorletPrice (Rate) const
Rate floorletRate (Rate) const
Protected Attributes
const OvernightIndexedCoupon * coupon_
Detailed Description
Definition at line 35 of file overnightindexedcoupon.cpp.
Member Function Documentation
Real QuantLib::anonymous_namespace{overnightindexedcoupon.cpp}::OvernightIndexedCouponPricer::capletPrice (Rate) const [inline, virtual]
Implements QuantLib::FloatingRateCouponPricer.
Definition at line 105 of file overnightindexedcoupon.cpp.
References QL_FAIL.
{ QL_FAIL("capletPrice not available"); }
Rate QuantLib::anonymous_namespace{overnightindexedcoupon.cpp}::OvernightIndexedCouponPricer::capletRate (Rate) const [inline, virtual]
Implements QuantLib::FloatingRateCouponPricer.
Definition at line 106 of file overnightindexedcoupon.cpp.
References QL_FAIL.
{ QL_FAIL("capletRate not available"); }
Real QuantLib::anonymous_namespace{overnightindexedcoupon.cpp}::OvernightIndexedCouponPricer::floorletPrice (Rate) const [inline, virtual]
Implements QuantLib::FloatingRateCouponPricer.
Definition at line 107 of file overnightindexedcoupon.cpp.
References QL_FAIL.
{ QL_FAIL("floorletPrice not available"); }
Rate QuantLib::anonymous_namespace{overnightindexedcoupon.cpp}::OvernightIndexedCouponPricer::floorletRate (Rate) const [inline, virtual]
Implements QuantLib::FloatingRateCouponPricer.
Definition at line 108 of file overnightindexedcoupon.cpp.
References QL_FAIL.
{ QL_FAIL("floorletRate not available"); }
void QuantLib::anonymous_namespace{overnightindexedcoupon.cpp}::OvernightIndexedCouponPricer::initialize (const FloatingRateCoupon & coupon) [inline, virtual]
Implements QuantLib::FloatingRateCouponPricer.
Definition at line 37 of file overnightindexedcoupon.cpp.
References QL_ENSURE.
{
                coupon_ = dynamic_cast<const OvernightIndexedCoupon*>(&coupon);
                QL_ENSURE(coupon_, "wrong coupon type");
            }
Real QuantLib::anonymous_namespace{overnightindexedcoupon.cpp}::OvernightIndexedCouponPricer::swapletPrice () const [inline, virtual]
Implements QuantLib::FloatingRateCouponPricer.
Definition at line 104 of file overnightindexedcoupon.cpp.
References QL_FAIL.
{ QL_FAIL("swapletPrice not available");  }
Rate QuantLib::anonymous_namespace{overnightindexedcoupon.cpp}::OvernightIndexedCouponPricer::swapletRate () const [inline, virtual]
Implements QuantLib::FloatingRateCouponPricer.
Definition at line 41 of file overnightindexedcoupon.cpp.
References anonymous_namespace{marketmodel.cpp}::dates, QuantLib::anonymous_namespace{yieldtermstructure.cpp}::dt, QuantLib::Handle< T >::empty(), QuantLib::Settings::evaluationDate(), QuantLib::IndexManager::getHistory(), QuantLib::Singleton< Settings >::instance(), QuantLib::Singleton< IndexManager >::instance(), QL_REQUIRE, and QuantLib::io::rate().
{
                shared_ptr<OvernightIndex> index =
                    dynamic_pointer_cast<OvernightIndex>(coupon_->index());
                const vector<Date>& fixingDates = coupon_->fixingDates();
                const vector<Time>& dt = coupon_->dt();
                Size n = dt.size(),
                     i = 0;
                Real compoundFactor = 1.0;
                // already fixed part
                Date today = Settings::instance().evaluationDate();
                while (fixingDates[i]<today && i<n) {
                    // rate must have been fixed
                    Rate pastFixing = IndexManager::instance().getHistory(
                                                index->name())[fixingDates[i]];
                    QL_REQUIRE(pastFixing != Null<Real>(),
                               "Missing " << index->name() <<
                               " fixing for " << fixingDates[i]);
                    compoundFactor *= (1.0 + pastFixing*dt[i]);
                    ++i;
                }
                // today is a border case
                if (fixingDates[i] == today && i<n) {
                    // might have been fixed
                    try {
                        Rate pastFixing = IndexManager::instance().getHistory(
                                                index->name())[fixingDates[i]];
                        if (pastFixing != Null<Real>()) {
                            compoundFactor *= (1.0 + pastFixing*dt[i]);
                            ++i;
                        } else {
                            ;   // fall through and forecast
                        }
                    } catch (Error&) {
                        ;       // fall through and forecast
                    }
                }
                // forward part using telescopic property in order
                // to avoid the evaluation of multiple forward fixings
                if (i<n) {
                    Handle<YieldTermStructure> curve =
                        index->forwardingTermStructure();
                    QL_REQUIRE(!curve.empty(),
                               "null term structure set to this instance of "<<
                               index->name());
                    const vector<Date>& dates = coupon_->valueDates();
                    DiscountFactor startDiscount = curve->discount(dates[i]);
                    DiscountFactor endDiscount = curve->discount(dates[n]);
                    compoundFactor *= startDiscount/endDiscount;
                }
                Rate rate = (compoundFactor - 1.0) / coupon_->accrualPeriod();
                return coupon_->gearing() * rate + coupon_->spread();
            }
Member Data Documentation
const OvernightIndexedCoupon* QuantLib::anonymous_namespace{overnightindexedcoupon.cpp}::OvernightIndexedCouponPricer::coupon_ [protected]
Definition at line 110 of file overnightindexedcoupon.cpp.
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/overnightindexedcoupon.cpp