QuantLib: QuantLib::RiskyAssetSwap Class Reference
QuantLib::RiskyAssetSwap Class Reference
Risky asset-swap instrument.
#include <riskyassetswap.hpp>
Public Member Functions
RiskyAssetSwap (bool fixedPayer, Real nominal, const Schedule &fixedSchedule, const Schedule &floatSchedule, const DayCounter &fixedDayCounter, const DayCounter &floatDayCounter, Rate spread, Rate recoveryRate_, const Handle< YieldTermStructure > &yieldTS, const Handle< DefaultProbabilityTermStructure > &defaultTS, Rate coupon=Null< Rate >())
Real fairSpread ()
Real floatAnnuity () const
Real nominal ()
Rate spread ()
bool fixedPayer ()
Private Member Functions
void setupExpired () const
bool isExpired () const
returns whether the instrument might have value greater than zero.
void performCalculations () const
Real fixedAnnuity () const
Real parCoupon () const
Real recoveryValue () const
Real riskyBondPrice () const
Private Attributes
Real fixedAnnuity_
Real floatAnnuity_
Real parCoupon_
Real recoveryValue_
Real riskyBondPrice_
bool fixedPayer_
Real nominal_
Schedule fixedSchedule_
Schedule floatSchedule_
DayCounter fixedDayCounter_
DayCounter floatDayCounter_
Rate spread_
Rate recoveryRate_
Handle< YieldTermStructure > yieldTS_
Handle
< DefaultProbabilityTermStructure > defaultTS_
Real coupon_
Detailed Description
Risky asset-swap instrument.
Definition at line 36 of file riskyassetswap.hpp.
Constructor & Destructor Documentation
QuantLib::RiskyAssetSwap::RiskyAssetSwap (bool fixedPayer, Real nominal, const Schedule & fixedSchedule, const Schedule & floatSchedule, const DayCounter & fixedDayCounter, const DayCounter & floatDayCounter, Rate spread, Rate recoveryRate_, const Handle< YieldTermStructure > & yieldTS, const Handle< DefaultProbabilityTermStructure > & defaultTS, Rate coupon = Null<Rate>())
Definition at line 25 of file riskyassetswap.cpp.
References defaultTS_, QuantLib::Observer::registerWith(), and yieldTS_.
    : fixedPayer_(fixedPayer), nominal_(nominal),
      fixedSchedule_(fixedSchedule), floatSchedule_(floatSchedule),
      fixedDayCounter_(fixedDayCounter), floatDayCounter_(floatDayCounter),
      spread_(spread), recoveryRate_(recoveryRate),
      yieldTS_(yieldTS), defaultTS_(defaultTS), coupon_(coupon) {
        registerWith (yieldTS_);
        registerWith (defaultTS_);
    }
Member Function Documentation
Real QuantLib::RiskyAssetSwap::fairSpread ()
Definition at line 159 of file riskyassetswap.cpp.
References QuantLib::Instrument::calculate(), coupon_, QuantLib::Schedule::dates(), defaultTS_, fixedAnnuity_, fixedDayCounter_, fixedSchedule_, recoveryValue_, QuantLib::Schedule::size(), QuantLib::DayCounter::yearFraction(), and yieldTS_.
{
        calculate();
        Real value = 0;
        for (Size i = 1; i < fixedSchedule_.size(); i++) {
            Time dcf = fixedDayCounter_.yearFraction (fixedSchedule_[i-1],
                                                      fixedSchedule_[i]);
            value += dcf * yieldTS_->discount (fixedSchedule_[i])
                * defaultTS_->defaultProbability (fixedSchedule_[i], true);
        }
        value *= coupon_;
        value += yieldTS_->discount (fixedSchedule_.dates().back())
            * defaultTS_->defaultProbability (fixedSchedule_.dates().back(),
                                              true);
        Real initialDiscount = yieldTS_->discount(fixedSchedule_[0]);
        return (1.0 - initialDiscount + value - recoveryValue_) / fixedAnnuity_;
    }
Real QuantLib::RiskyAssetSwap::fixedAnnuity () const [private]
Definition at line 93 of file riskyassetswap.cpp.
References fixedDayCounter_, floatSchedule_, QuantLib::Schedule::size(), QuantLib::DayCounter::yearFraction(), and yieldTS_.
Referenced by performCalculations().
{
        Real annuity = 0;
        for (Size i = 1; i < floatSchedule_.size(); i++) {
            Time dcf = fixedDayCounter_.yearFraction (floatSchedule_[i-1],
                                                      floatSchedule_[i]);
            annuity += dcf * yieldTS_->discount (floatSchedule_[i]);
        }
        return annuity;
    }
bool QuantLib::RiskyAssetSwap::fixedPayer () [inline]
Definition at line 56 of file riskyassetswap.hpp.
References fixedPayer_.
{ return fixedPayer_; }
Real QuantLib::RiskyAssetSwap::floatAnnuity () const
Definition at line 82 of file riskyassetswap.cpp.
References floatDayCounter_, floatSchedule_, QuantLib::Schedule::size(), QuantLib::DayCounter::yearFraction(), and yieldTS_.
Referenced by performCalculations().
{
        Real annuity = 0;
        for (Size i = 1; i < floatSchedule_.size(); i++) {
            Time dcf = floatDayCounter_.yearFraction (floatSchedule_[i-1],
                                                      floatSchedule_[i]);
            annuity += dcf * yieldTS_->discount (floatSchedule_[i]);
        }
        return annuity;
    }
bool QuantLib::RiskyAssetSwap::isExpired () const [private, virtual]
returns whether the instrument might have value greater than zero.
Implements QuantLib::Instrument.
Definition at line 47 of file riskyassetswap.cpp.
References QuantLib::Schedule::dates(), fixedSchedule_, and yieldTS_.
{
        return detail::simple_event(fixedSchedule_.dates().back())
               .hasOccurred(yieldTS_->referenceDate());
    }
Real QuantLib::RiskyAssetSwap::nominal () [inline]
Definition at line 54 of file riskyassetswap.hpp.
References nominal_.
{ return nominal_; }
Real QuantLib::RiskyAssetSwap::parCoupon () const [private]
Definition at line 104 of file riskyassetswap.cpp.
References QuantLib::Schedule::dates(), fixedAnnuity_, fixedSchedule_, and yieldTS_.
Referenced by performCalculations().
{
        return (yieldTS_->discount(fixedSchedule_.dates().front())
                -yieldTS_->discount(fixedSchedule_.dates().back()))
            / fixedAnnuity_;
    }
void QuantLib::RiskyAssetSwap::performCalculations () const [private, virtual]
In case a pricing engine is not used, this method must be overridden to perform the actual calculations and set any needed results. In case a pricing engine is used, the default implementation can be used.
Reimplemented from QuantLib::Instrument.
Definition at line 58 of file riskyassetswap.cpp.
References coupon_, QuantLib::Schedule::dates(), fixedAnnuity(), fixedAnnuity_, fixedPayer_, fixedSchedule_, floatAnnuity(), floatAnnuity_, nominal_, QuantLib::Instrument::NPV_, parCoupon(), parCoupon_, recoveryValue(), recoveryValue_, riskyBondPrice(), riskyBondPrice_, spread_, and yieldTS_.
{
        // order of calls is essential
        floatAnnuity_   = floatAnnuity();
        fixedAnnuity_   = fixedAnnuity();
        parCoupon_      = parCoupon();
        if (coupon_ == Null<Rate>())  coupon_ = parCoupon_;
        recoveryValue_  = recoveryValue();
        riskyBondPrice_ = riskyBondPrice();
        NPV_ = riskyBondPrice_
            - coupon_ * fixedAnnuity_
            + yieldTS_->discount (fixedSchedule_.dates().front())
            - yieldTS_->discount (fixedSchedule_.dates().back())
            + spread_ * floatAnnuity_;
        NPV_ *= nominal_;
        if (fixedPayer_ == false)
            NPV_ *= -1;
    }
Real QuantLib::RiskyAssetSwap::recoveryValue () const [private]
Definition at line 111 of file riskyassetswap.cpp.
References QuantLib::Calendar::advance(), anonymous_namespace{marketmodel.cpp}::d, QuantLib::Days, defaultTS_, fixedSchedule_, recoveryRate_, QuantLib::Schedule::size(), QuantLib::Unadjusted, and yieldTS_.
Referenced by performCalculations().
{
        Real recoveryValue = 0;
        // simple Euler integral to evaluate the recovery value
        for (Size i = 1; i < fixedSchedule_.size(); i++) {
            TimeUnit stepSize = Days;
            Date d;
            if (fixedSchedule_[i-1] >= defaultTS_->referenceDate())
                d = fixedSchedule_[i-1];
            else
                d = defaultTS_->referenceDate();
            Date d0 = d;
            do {
                double disc = yieldTS_->discount (d);
                double dd   = defaultTS_->defaultDensity (d, true);
                double dcf  = defaultTS_->dayCounter().yearFraction (d0, d);
                recoveryValue  += disc * dd * dcf;
                d0 = d;
                d = NullCalendar().advance (d0, 1, stepSize, Unadjusted);
            }
            while (d < fixedSchedule_[i]);
        }
        recoveryValue *= recoveryRate_;
        return recoveryValue;
    }
Real QuantLib::RiskyAssetSwap::riskyBondPrice () const [private]
Definition at line 141 of file riskyassetswap.cpp.
References coupon_, QuantLib::Schedule::dates(), defaultTS_, fixedDayCounter_, fixedSchedule_, recoveryValue_, QuantLib::Schedule::size(), QuantLib::DayCounter::yearFraction(), and yieldTS_.
Referenced by performCalculations().
{
        Real value = 0;
        for (Size i = 1; i < fixedSchedule_.size(); i++) {
            Time dcf = fixedDayCounter_.yearFraction (fixedSchedule_[i-1],
                                                      fixedSchedule_[i]);
            value += dcf * yieldTS_->discount (fixedSchedule_[i])
                * defaultTS_->survivalProbability (fixedSchedule_[i], true);
        }
        value *= coupon_;
        value += yieldTS_->discount (fixedSchedule_.dates().back())
            * defaultTS_->survivalProbability (fixedSchedule_.dates().back(),
                                               true);
        return value + recoveryValue_;
    }
void QuantLib::RiskyAssetSwap::setupExpired () const [private, virtual]
This method must leave the instrument in a consistent state when the expiration condition is met.
Reimplemented from QuantLib::Instrument.
Definition at line 53 of file riskyassetswap.cpp.
{
        Instrument::setupExpired();
    }
Rate QuantLib::RiskyAssetSwap::spread () [inline]
Definition at line 55 of file riskyassetswap.hpp.
References spread_.
{ return spread_; }
Member Data Documentation
Real QuantLib::RiskyAssetSwap::coupon_ [mutable, private]
Definition at line 84 of file riskyassetswap.hpp.
Referenced by fairSpread(), performCalculations(), and riskyBondPrice().
Handle<DefaultProbabilityTermStructure> QuantLib::RiskyAssetSwap::defaultTS_ [private]
Definition at line 83 of file riskyassetswap.hpp.
Referenced by fairSpread(), recoveryValue(), RiskyAssetSwap(), and riskyBondPrice().
Real QuantLib::RiskyAssetSwap::fixedAnnuity_ [mutable, private]
Definition at line 69 of file riskyassetswap.hpp.
Referenced by fairSpread(), parCoupon(), and performCalculations().
DayCounter QuantLib::RiskyAssetSwap::fixedDayCounter_ [private]
Definition at line 79 of file riskyassetswap.hpp.
Referenced by fairSpread(), fixedAnnuity(), and riskyBondPrice().
bool QuantLib::RiskyAssetSwap::fixedPayer_ [private]
Definition at line 76 of file riskyassetswap.hpp.
Referenced by fixedPayer(), and performCalculations().
Schedule QuantLib::RiskyAssetSwap::fixedSchedule_ [private]
Definition at line 78 of file riskyassetswap.hpp.
Referenced by fairSpread(), isExpired(), parCoupon(), performCalculations(), recoveryValue(), and riskyBondPrice().
Real QuantLib::RiskyAssetSwap::floatAnnuity_ [mutable, private]
Definition at line 70 of file riskyassetswap.hpp.
Referenced by performCalculations().
DayCounter QuantLib::RiskyAssetSwap::floatDayCounter_ [private]
Definition at line 79 of file riskyassetswap.hpp.
Referenced by floatAnnuity().
Schedule QuantLib::RiskyAssetSwap::floatSchedule_ [private]
Definition at line 78 of file riskyassetswap.hpp.
Referenced by fixedAnnuity(), and floatAnnuity().
Real QuantLib::RiskyAssetSwap::nominal_ [private]
Definition at line 77 of file riskyassetswap.hpp.
Referenced by nominal(), and performCalculations().
Real QuantLib::RiskyAssetSwap::parCoupon_ [mutable, private]
Definition at line 71 of file riskyassetswap.hpp.
Referenced by performCalculations().
Rate QuantLib::RiskyAssetSwap::recoveryRate_ [private]
Definition at line 81 of file riskyassetswap.hpp.
Referenced by recoveryValue().
Real QuantLib::RiskyAssetSwap::recoveryValue_ [mutable, private]
Definition at line 72 of file riskyassetswap.hpp.
Referenced by fairSpread(), performCalculations(), and riskyBondPrice().
Real QuantLib::RiskyAssetSwap::riskyBondPrice_ [mutable, private]
Definition at line 73 of file riskyassetswap.hpp.
Referenced by performCalculations().
Rate QuantLib::RiskyAssetSwap::spread_ [private]
Definition at line 80 of file riskyassetswap.hpp.
Referenced by performCalculations(), and spread().
Handle<YieldTermStructure> QuantLib::RiskyAssetSwap::yieldTS_ [private]
Definition at line 82 of file riskyassetswap.hpp.
Referenced by fairSpread(), fixedAnnuity(), floatAnnuity(), isExpired(), parCoupon(), performCalculations(), recoveryValue(), RiskyAssetSwap(), and riskyBondPrice().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/riskyassetswap.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/riskyassetswap.cpp