QuantLib: QuantLib::Solver1D< Impl > Class Template Reference
QuantLib::Solver1D< Impl > Class Template Reference
Base class for 1-D solvers.
#include <solver1d.hpp>
Public Member Functions
Solver1D ()
Modifiers
template<class F >
Real solve (const F &f, Real accuracy, Real guess, Real step) const
template<class F >
Real solve (const F &f, Real accuracy, Real guess, Real xMin, Real xMax) const
void setMaxEvaluations (Size evaluations)
void setLowerBound (Real lowerBound)
sets the lower bound for the function domain
void setUpperBound (Real upperBound)
sets the upper bound for the function domain
Protected Attributes
Real root_
Real xMin_
Real xMax_
Real fxMin_
Real fxMax_
Size maxEvaluations_
Size evaluationNumber_
Private Member Functions
Real enforceBounds_ (Real x) const
Private Attributes
Real lowerBound_
Real upperBound_
bool lowerBoundEnforced_
bool upperBoundEnforced_
Detailed Description
template<class Impl>
class QuantLib::Solver1D< Impl >
Base class for 1-D solvers.
The implementation of this class uses the so-called "Barton-Nackman trick", also known as "the curiously recurring template pattern". Concrete solvers will be declared as:
        class Foo : public Solver1D<Foo> {
          public:
            ...
            template <class F>
            Real solveImpl(const F& f, Real accuracy) const {
                ...
            }
        };
Before calling solveImpl, the base class will set its protected data members so that:
xMin_ and xMax_ form a valid bracket;
fxMin_ and fxMax_ contain the values of the function in xMin_ and xMax_;
root_ is a valid initial guess. The implementation of solveImpl can safely assume all of the above.
Todo:
clean up the interface so that it is clear whether the accuracy is specified for \(x \) or \(f(x) \).
add target value (now the target value is 0.0)
Definition at line 66 of file solver1d.hpp.
Constructor & Destructor Documentation
template<class Impl> QuantLib::Solver1D< Impl >::Solver1D () [inline]
Definition at line 68 of file solver1d.hpp.
        : maxEvaluations_(MAX_FUNCTION_EVALUATIONS),
          lowerBoundEnforced_(false), upperBoundEnforced_(false) {}
Member Function Documentation
template<class T > Real QuantLib::Solver1D< T >::enforceBounds_ (Real x) const [inline, private]
Definition at line 256 of file solver1d.hpp.
Referenced by QuantLib::Solver1D< Ridder >::solve().
{
        if (lowerBoundEnforced_ && x < lowerBound_)
            return lowerBound_;
        if (upperBoundEnforced_ && x > upperBound_)
            return upperBound_;
        return x;
    }
template<class T > void QuantLib::Solver1D< T >::setLowerBound (Real lowerBound) [inline]
sets the lower bound for the function domain
Definition at line 244 of file solver1d.hpp.
Referenced by QuantLib::JamshidianSwaptionEngine::calculate().
{
        lowerBound_ = lowerBound;
        lowerBoundEnforced_ = true;
    }
template<class T > void QuantLib::Solver1D< T >::setMaxEvaluations (Size evaluations) [inline]
This method sets the maximum number of function evaluations for the bracketing routine. An error is thrown if a bracket is not found after this number of evaluations.
Definition at line 239 of file solver1d.hpp.
Referenced by QuantLib::blackFormulaImpliedStdDev(), QuantLib::AnalyticCompoundOptionEngine::calculate(), QuantLib::detail::ImpliedVolatilityHelper::calculate(), QuantLib::JamshidianSwaptionEngine::calculate(), QuantLib::GFunctionFactory::GFunctionWithShifts::calibrationOfShift(), QuantLib::CapPseudoDerivative::CapPseudoDerivative(), QuantLib::CalibrationHelper::impliedVolatility(), QuantLib::CdsOption::impliedVolatility(), QuantLib::CallableBond::impliedVolatility(), QuantLib::CapFloor::impliedVolatility(), QuantLib::Swaption::impliedVolatility(), QuantLib::InverseNonCentralChiSquareDistribution::operator()(), QuantLib::G2::SwaptionPricingFunction::operator()(), QuantLib::OneFactorModel::ShortRateTree::ShortRateTree(), QuantLib::Newton::solveImpl(), QuantLib::OptionletStripper2::spreadsVolImplied(), QuantLib::BlackDeltaCalculator::strikeFromDelta(), QuantLib::BlackKarasinski::tree(), QuantLib::GeneralizedHullWhite::tree(), and QuantLib::CashFlows::yield().
{
        maxEvaluations_ = evaluations;
    }
template<class T > void QuantLib::Solver1D< T >::setUpperBound (Real upperBound) [inline]
sets the upper bound for the function domain
Definition at line 250 of file solver1d.hpp.
Referenced by QuantLib::JamshidianSwaptionEngine::calculate().
{
        upperBound_ = upperBound;
        upperBoundEnforced_ = true;
    }
template<class Impl> template<class F > Real QuantLib::Solver1D< Impl >::solve (const F & f, Real accuracy, Real guess, Real step) const [inline]
This method returns the zero of the function \(f \), determined with the given accuracy \(\epsilon \); depending on the particular solver, this might mean that the returned \(x \) is such that \(|f(x)| < \epsilon \), or that \(|x-\xi| < \epsilon \) where \(\xi \) is the real zero.
This method contains a bracketing routine to which an initial guess must be supplied as well as a step used to scan the range of the possible bracketing values.
Definition at line 85 of file solver1d.hpp.
Referenced by QuantLib::blackFormulaImpliedStdDev(), QuantLib::AnalyticCompoundOptionEngine::calculate(), QuantLib::detail::ImpliedVolatilityHelper::calculate(), QuantLib::JamshidianSwaptionEngine::calculate(), QuantLib::GFunctionFactory::GFunctionWithShifts::calibrationOfShift(), QuantLib::CapPseudoDerivative::CapPseudoDerivative(), QuantLib::CreditDefaultSwap::impliedHazardRate(), QuantLib::CalibrationHelper::impliedVolatility(), QuantLib::CdsOption::impliedVolatility(), QuantLib::CallableBond::impliedVolatility(), QuantLib::CapFloor::impliedVolatility(), QuantLib::Swaption::impliedVolatility(), QuantLib::InterpolatedYoYOptionletStripper< Interpolator1D >::initialize(), QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::intersect(), QuantLib::InverseNonCentralChiSquareDistribution::operator()(), QuantLib::RichardsonExtrapolation::operator()(), QuantLib::OneFactorModel::ShortRateTree::ShortRateTree(), QuantLib::Newton::solveImpl(), QuantLib::OptionletStripper2::spreadsVolImplied(), QuantLib::BlackDeltaCalculator::strikeFromDelta(), QuantLib::BlackKarasinski::tree(), QuantLib::GeneralizedHullWhite::tree(), and QuantLib::CashFlows::yield().
{
            QL_REQUIRE(accuracy>0.0,
                       "accuracy (" << accuracy << ") must be positive");
            // check whether we really want to use epsilon
            accuracy = std::max(accuracy, QL_EPSILON);
            const Real growthFactor = 1.6;
            Integer flipflop = -1;
            root_ = guess;
            fxMax_ = f(root_);
            // monotonically crescent bias, as in optionValue(volatility)
            if (close(fxMax_,0.0))
                return root_;
            else if (close(fxMax_, 0.0)) {
                xMin_ = enforceBounds_(root_ - step);
                fxMin_ = f(xMin_);
                xMax_ = root_;
            } else {
                xMin_ = root_;
                fxMin_ = fxMax_;
                xMax_ = enforceBounds_(root_+step);
                fxMax_ = f(xMax_);
            }
            evaluationNumber_ = 2;
            while (evaluationNumber_ <= maxEvaluations_) {
                if (fxMin_*fxMax_ <= 0.0) {
                    if (close(fxMin_, 0.0))
                        return xMin_;
                    if (close(fxMax_, 0.0))
                        return xMax_;
                    root_ = (xMax_+xMin_)/2.0;
                    return this->impl().solveImpl(f, accuracy);
                }
                if (std::fabs(fxMin_) < std::fabs(fxMax_)) {
                    xMin_ = enforceBounds_(xMin_+growthFactor*(xMin_ - xMax_));
                    fxMin_= f(xMin_);
                } else if (std::fabs(fxMin_) > std::fabs(fxMax_)) {
                    xMax_ = enforceBounds_(xMax_+growthFactor*(xMax_ - xMin_));
                    fxMax_= f(xMax_);
                } else if (flipflop == -1) {
                    xMin_ = enforceBounds_(xMin_+growthFactor*(xMin_ - xMax_));
                    fxMin_= f(xMin_);
                    evaluationNumber_++;
                    flipflop = 1;
                } else if (flipflop == 1) {
                    xMax_ = enforceBounds_(xMax_+growthFactor*(xMax_ - xMin_));
                    fxMax_= f(xMax_);
                    flipflop = -1;
                }
                evaluationNumber_++;
            }
            QL_FAIL("unable to bracket root in " << maxEvaluations_
                    << " function evaluations (last bracket attempt: "
                    << "f[" << xMin_ << "," << xMax_ << "] "
                    << "-> [" << fxMin_ << "," << fxMax_ << "])");
        }
template<class Impl> template<class F > Real QuantLib::Solver1D< Impl >::solve (const F & f, Real accuracy, Real guess, Real xMin, Real xMax) const [inline]
This method returns the zero of the function \(f \), determined with the given accuracy \(\epsilon \); depending on the particular solver, this might mean that the returned \(x \) is such that \(|f(x)| < \epsilon \), or that \(|x-\xi| < \epsilon \) where \(\xi \) is the real zero.
An initial guess must be supplied, as well as two values \(x_\mathrm{min} \) and \(x_\mathrm{max} \) which must bracket the zero (i.e., either \(f(x_\mathrm{min}) \leq 0 \leq f(x_\mathrm{max}) \), or \(f(x_\mathrm{max}) \leq 0 \leq f(x_\mathrm{min}) \) must be true).
Definition at line 164 of file solver1d.hpp.
{
            QL_REQUIRE(accuracy>0.0,
                       "accuracy (" << accuracy << ") must be positive");
            // check whether we really want to use epsilon
            accuracy = std::max(accuracy, QL_EPSILON);
            xMin_ = xMin;
            xMax_ = xMax;
            QL_REQUIRE(xMin_ < xMax_,
                       "invalid range: xMin_ (" << xMin_
                       << ") >= xMax_ (" << xMax_ << ")");
            QL_REQUIRE(!lowerBoundEnforced_ || xMin_ >= lowerBound_,
                       "xMin_ (" << xMin_
                       << ") < enforced low bound (" << lowerBound_ << ")");
            QL_REQUIRE(!upperBoundEnforced_ || xMax_ <= upperBound_,
                       "xMax_ (" << xMax_
                       << ") > enforced hi bound (" << upperBound_ << ")");
            fxMin_ = f(xMin_);
            if (close(fxMin_, 0.0))
                return xMin_;
            fxMax_ = f(xMax_);
            if (close(fxMax_, 0.0))
                return xMax_;
            evaluationNumber_ = 2;
            QL_REQUIRE(fxMin_*fxMax_ < 0.0,
                       "root not bracketed: f["
                       << xMin_ << "," << xMax_ << "] -> ["
                       << std::scientific
                       << fxMin_ << "," << fxMax_ << "]");
            QL_REQUIRE(guess > xMin_,
                       "guess (" << guess << ") < xMin_ (" << xMin_ << ")");
            QL_REQUIRE(guess < xMax_,
                       "guess (" << guess << ") > xMax_ (" << xMax_ << ")");
            root_ = guess;
            return this->impl().solveImpl(f, accuracy);
        }
Member Data Documentation
template<class Impl> Size QuantLib::Solver1D< Impl >::evaluationNumber_ [mutable, protected]
Definition at line 228 of file solver1d.hpp.
Referenced by QuantLib::Solver1D< Ridder >::solve().
template<class Impl> Real QuantLib::Solver1D< Impl >::fxMax_ [mutable, protected]
Definition at line 226 of file solver1d.hpp.
Referenced by QuantLib::Solver1D< Ridder >::solve().
template<class Impl> Real QuantLib::Solver1D< Impl >::fxMin_ [mutable, protected]
Definition at line 226 of file solver1d.hpp.
Referenced by QuantLib::Solver1D< Ridder >::solve().
template<class Impl> Real QuantLib::Solver1D< Impl >::lowerBound_ [private]
Definition at line 231 of file solver1d.hpp.
Referenced by QuantLib::Solver1D< Ridder >::solve().
template<class Impl> bool QuantLib::Solver1D< Impl >::lowerBoundEnforced_ [private]
Definition at line 232 of file solver1d.hpp.
Referenced by QuantLib::Solver1D< Ridder >::solve().
template<class Impl> Size QuantLib::Solver1D< Impl >::maxEvaluations_ [protected]
Definition at line 227 of file solver1d.hpp.
Referenced by QuantLib::Solver1D< Ridder >::solve().
template<class Impl> Real QuantLib::Solver1D< Impl >::root_ [mutable, protected]
Definition at line 226 of file solver1d.hpp.
Referenced by QuantLib::Solver1D< Ridder >::solve().
template<class Impl> Real QuantLib::Solver1D< Impl >::upperBound_ [private]
Definition at line 231 of file solver1d.hpp.
Referenced by QuantLib::Solver1D< Ridder >::solve().
template<class Impl> bool QuantLib::Solver1D< Impl >::upperBoundEnforced_ [private]
Definition at line 232 of file solver1d.hpp.
Referenced by QuantLib::Solver1D< Ridder >::solve().
template<class Impl> Real QuantLib::Solver1D< Impl >::xMax_ [mutable, protected]
Definition at line 226 of file solver1d.hpp.
Referenced by QuantLib::Solver1D< Ridder >::solve().
template<class Impl> Real QuantLib::Solver1D< Impl >::xMin_ [mutable, protected]
Definition at line 226 of file solver1d.hpp.
Referenced by QuantLib::Solver1D< Ridder >::solve().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/solver1d.hpp