QuantLib: QuantLib::InverseCumulativeRsg< USG, IC > Class Template Reference
QuantLib::InverseCumulativeRsg< USG, IC > Class Template Reference
Inverse cumulative random sequence generator.
#include <inversecumulativersg.hpp>
Public Types
typedef Sample< std::vector
< Real > > sample_type
Public Member Functions
InverseCumulativeRsg (const USG &uniformSequenceGenerator)
InverseCumulativeRsg (const USG &uniformSequenceGenerator, const IC &inverseCumulative)
const sample_type & nextSequence () const
returns next sample from the inverse cumulative distribution
const sample_type & lastSequence () const
Size dimension () const
Private Attributes
USG uniformSequenceGenerator_
Size dimension_
sample_type x_
IC ICD_
Detailed Description
template<class USG, class IC>
class QuantLib::InverseCumulativeRsg< USG, IC >
Inverse cumulative random sequence generator.
It uses a sequence of uniform deviate in (0, 1) as the source of cumulative distribution values. Then an inverse cumulative distribution is used to calculate the distribution deviate.
The uniform deviate sequence is supplied by USG.
Class USG must implement the following interface:
            USG::sample_type USG::nextSequence() const;
            Size USG::dimension() const;
The inverse cumulative distribution is supplied by IC.
Class IC must implement the following interface:
            IC::IC();
            Real IC::operator() const;
Definition at line 56 of file inversecumulativersg.hpp.
Member Typedef Documentation
template<class USG, class IC> typedef Sample<std::vector<Real> > QuantLib::InverseCumulativeRsg< USG, IC >::sample_type
Definition at line 58 of file inversecumulativersg.hpp.
Constructor & Destructor Documentation
template<class USG, class IC > QuantLib::InverseCumulativeRsg< USG, IC >::InverseCumulativeRsg (const USG & uniformSequenceGenerator) [explicit]
Definition at line 74 of file inversecumulativersg.hpp.
    : uniformSequenceGenerator_(usg),
      dimension_(uniformSequenceGenerator_.dimension()),
      x_(std::vector<Real> (dimension_), 1.0) {}
template<class USG, class IC> QuantLib::InverseCumulativeRsg< USG, IC >::InverseCumulativeRsg (const USG & uniformSequenceGenerator, const IC & inverseCumulative)
Definition at line 80 of file inversecumulativersg.hpp.
    : uniformSequenceGenerator_(usg),
      dimension_(uniformSequenceGenerator_.dimension()),
      x_(std::vector<Real> (dimension_), 1.0),
      ICD_(inverseCum) {}
Member Function Documentation
template<class USG, class IC> Size QuantLib::InverseCumulativeRsg< USG, IC >::dimension () const [inline]
Definition at line 65 of file inversecumulativersg.hpp.
{ return dimension_; }
template<class USG, class IC> const sample_type& QuantLib::InverseCumulativeRsg< USG, IC >::lastSequence () const [inline]
Definition at line 64 of file inversecumulativersg.hpp.
{ return x_; }
template<class USG , class IC > const InverseCumulativeRsg< USG, IC >::sample_type & QuantLib::InverseCumulativeRsg< USG, IC >::nextSequence () const [inline]
returns next sample from the inverse cumulative distribution
Definition at line 89 of file inversecumulativersg.hpp.
References QuantLib::Sample< T >::weight.
Referenced by QuantLib::SobolBrownianGenerator::nextPath(), QuantLib::GaussianRandomDefaultModel::nextSequence(), RngTraitsTest::testGaussian(), and BrownianBridgeTest::testVariates().
{
        typename USG::sample_type sample =
            uniformSequenceGenerator_.nextSequence();
        x_.weight = sample.weight;
        for (Size i = 0; i < dimension_; i++) {
            x_.value[i] = ICD_(sample.value[i]);
        }
        return x_;
    }
Member Data Documentation
template<class USG, class IC> Size QuantLib::InverseCumulativeRsg< USG, IC >::dimension_ [private]
Definition at line 68 of file inversecumulativersg.hpp.
Referenced by QuantLib::InverseCumulativeRsg< SobolRsg, InverseCumulativeNormal >::dimension().
template<class USG, class IC> IC QuantLib::InverseCumulativeRsg< USG, IC >::ICD_ [private]
Definition at line 70 of file inversecumulativersg.hpp.
template<class USG, class IC> USG QuantLib::InverseCumulativeRsg< USG, IC >::uniformSequenceGenerator_ [private]
Definition at line 67 of file inversecumulativersg.hpp.
template<class USG, class IC> sample_type QuantLib::InverseCumulativeRsg< USG, IC >::x_ [mutable, private]
Definition at line 69 of file inversecumulativersg.hpp.
Referenced by QuantLib::InverseCumulativeRsg< SobolRsg, InverseCumulativeNormal >::lastSequence().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/randomnumbers/inversecumulativersg.hpp