QuantLib: QuantLib::AnalyticBSMHullWhiteEngine Class Reference
QuantLib::AnalyticBSMHullWhiteEngine Class Reference
analytic european option pricer including stochastic interest rates
#include <analyticbsmhullwhiteengine.hpp>
Public Member Functions
AnalyticBSMHullWhiteEngine (Real equityShortRateCorrelation, const boost::shared_ptr< GeneralizedBlackScholesProcess > &, const boost::shared_ptr< HullWhite > &)
void calculate () const
Private Attributes
Real rho_
boost::shared_ptr
< GeneralizedBlackScholesProcess > process_
Detailed Description
analytic european option pricer including stochastic interest rates
References:
Brigo, Mercurio, Interest Rate Models
Test:
the correctness of the returned value is tested by reproducing results available in web/literature
Definition at line 45 of file analyticbsmhullwhiteengine.hpp.
Constructor & Destructor Documentation
QuantLib::AnalyticBSMHullWhiteEngine::AnalyticBSMHullWhiteEngine (Real equityShortRateCorrelation, const boost::shared_ptr< GeneralizedBlackScholesProcess > & process, const boost::shared_ptr< HullWhite > & model)
Definition at line 63 of file analyticbsmhullwhiteengine.cpp.
References process_, and QuantLib::Observer::registerWith().
    : GenericModelEngine<HullWhite,
                         VanillaOption::arguments,
                         VanillaOption::results>(model),
      rho_(equityShortRateCorrelation), process_(process) {
        registerWith(process_);
    }
Member Function Documentation
void QuantLib::AnalyticBSMHullWhiteEngine::calculate () const [virtual]
Implements QuantLib::PricingEngine.
Definition at line 74 of file analyticbsmhullwhiteengine.cpp.
References anonymous_namespace{marketmodel.cpp}::a, QuantLib::GenericEngine< VanillaOption::arguments, VanillaOption::results >::arguments_, QuantLib::Option::arguments::exercise, QuantLib::GenericModelEngine< HullWhite, VanillaOption::arguments, VanillaOption::results >::model_, QuantLib::Option::arguments::payoff, QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow(), process_, QL_EPSILON, QL_REQUIRE, QuantLib::GenericEngine< VanillaOption::arguments, VanillaOption::results >::results_, rho_, QuantLib::Option::setupArguments(), anonymous_namespace{distributions.cpp}::sigma, anonymous_namespace{quantlibbenchmark.cpp}::t, and anonymous_namespace{perturbativebarrieroptionengine.cpp}::v().
{
        QL_REQUIRE(process_->x0() > 0.0, "negative or null underlying given");
        const boost::shared_ptr<StrikedTypePayoff> payoff =
            boost::dynamic_pointer_cast<StrikedTypePayoff>(arguments_.payoff);
        QL_REQUIRE(payoff, "non-striked payoff given");
        const boost::shared_ptr<Exercise> exercise = arguments_.exercise;
        Time t = process_->riskFreeRate()->dayCounter().yearFraction(
                                    process_->riskFreeRate()->referenceDate(),
                                    exercise->lastDate());
        const Real a = model_->params()[0];
        const Real sigma = model_->params()[1];
        const Real eta =
            process_->blackVolatility()->blackVol(exercise->lastDate(),
                                                  payoff->strike());
        Real varianceOffset;
        if (a*t > std::pow(QL_EPSILON, 0.25)) {
            const Real v = sigma*sigma/(a*a)
                *(t + 2/a*std::exp(-a*t) - 1/(2*a)*std::exp(-2*a*t) - 3/(2*a));
            const Real mu = 2*rho_*sigma*eta/a*(t-1/a*(1-std::exp(-a*t)));
            varianceOffset = v + mu;
        }
        else {
            // low-a algebraic limit
            const Real v = sigma*sigma*t*t*t*(1/3.0-0.25*a*t+7/60.0*a*a*t*t);
            const Real mu = rho_*sigma*eta*t*t*(1-a*t/3.0+a*a*t*t/12.0);
            varianceOffset = v + mu;
        }
        Handle<BlackVolTermStructure> volTS(
             boost::shared_ptr<BlackVolTermStructure>(
              new ShiftedBlackVolTermStructure(varianceOffset,
                                               process_->blackVolatility())));
        boost::shared_ptr<GeneralizedBlackScholesProcess> adjProcess(
                new GeneralizedBlackScholesProcess(process_->stateVariable(),
                                                   process_->dividendYield(),
                                                   process_->riskFreeRate(),
                                                   volTS));
        boost::shared_ptr<AnalyticEuropeanEngine> bsmEngine(
                                      new AnalyticEuropeanEngine(adjProcess));
        VanillaOption(payoff, exercise).setupArguments(
                                                   bsmEngine->getArguments());
        bsmEngine->calculate();
        results_ = *dynamic_cast<const OneAssetOption::results*>(
                                                    bsmEngine->getResults());
    }
Member Data Documentation
boost::shared_ptr<GeneralizedBlackScholesProcess> QuantLib::AnalyticBSMHullWhiteEngine::process_ [private]
Definition at line 57 of file analyticbsmhullwhiteengine.hpp.
Referenced by AnalyticBSMHullWhiteEngine(), and calculate().
Real QuantLib::AnalyticBSMHullWhiteEngine::rho_ [private]
Definition at line 56 of file analyticbsmhullwhiteengine.hpp.
Referenced by calculate().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/vanilla/analyticbsmhullwhiteengine.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/vanilla/analyticbsmhullwhiteengine.cpp