QuantLib: QuantLib::YoYOptionletVolatilitySurface Class Reference
QuantLib::YoYOptionletVolatilitySurface Class Reference
#include <yoyinflationoptionletvolatilitystructure.hpp>
Public Member Functions
virtual Volatility baseLevel () const
Constructor
calculate the reference date based on the global evaluation date
YoYOptionletVolatilitySurface (Natural settlementDays, const Calendar &, BusinessDayConvention bdc, const DayCounter &dc, const Period &observationLag, Frequency frequency, bool indexIsInterpolated)
virtual ~YoYOptionletVolatilitySurface ()
Volatility (only)
Volatility volatility (const Date &maturityDate, Rate strike, const Period &obsLag=Period(-1, Days), bool extrapolate=false) const
Volatility volatility (const Period &optionTenor, Rate strike, const Period &obsLag=Period(-1, Days), bool extrapolate=false) const
returns the volatility for a given option tenor and strike rate
virtual Volatility totalVariance (const Date &exerciseDate, Rate strike, const Period &obsLag=Period(-1, Days), bool extrapolate=false) const
Returns the total integrated variance for a given exercise date and strike rate.
virtual Volatility totalVariance (const Period &optionTenor, Rate strike, const Period &obsLag=Period(-1, Days), bool extrapolate=false) const
returns the total integrated variance for a given option tenor and strike rate
virtual Period observationLag () const
virtual Frequency frequency () const
virtual bool indexIsInterpolated () const
virtual Date baseDate () const
virtual Time timeFromBase (const Date &date, const Period &obsLag=Period(-1, Days)) const
base date will be in the past because of observation lag
Limits
virtual Real minStrike () const =0
the minimum strike for which the term structure can return vols
virtual Real maxStrike () const =0
the maximum strike for which the term structure can return vols
Protected Member Functions
virtual void checkRange (const Date &, Rate strike, bool extrapolate) const
virtual void checkRange (Time, Rate strike, bool extrapolate) const
virtual Volatility volatilityImpl (Time length, Rate strike) const =0
virtual void setBaseLevel (Volatility v)
Protected Attributes
Volatility baseLevel_
Period observationLag_
Frequency frequency_
bool indexIsInterpolated_
Detailed Description
Abstract interface ... no data, only results.
Basically used to change the BlackVariance() methods to totalVariance. Also deal with lagged observations of an index with a (usually different) availability lag.
Definition at line 39 of file yoyinflationoptionletvolatilitystructure.hpp.
Constructor & Destructor Documentation
QuantLib::YoYOptionletVolatilitySurface::YoYOptionletVolatilitySurface (Natural settlementDays, const Calendar & cal, BusinessDayConvention bdc, const DayCounter & dc, const Period & observationLag, Frequency frequency, bool indexIsInterpolated)
Definition at line 30 of file yoyinflationoptionletvolatilitystructure.cpp.
    : VolatilityTermStructure(settlementDays, cal, bdc, dc),
      baseLevel_(Null<Volatility>()), observationLag_(observationLag),
      frequency_(frequency), indexIsInterpolated_(indexIsInterpolated)
    {}
virtual QuantLib::YoYOptionletVolatilitySurface::~YoYOptionletVolatilitySurface () [inline, virtual]
Definition at line 51 of file yoyinflationoptionletvolatilitystructure.hpp.
{}
Member Function Documentation
Date QuantLib::YoYOptionletVolatilitySurface::baseDate () const [virtual]
Reimplemented in QuantLib::PiecewiseYoYOptionletVolatilityCurve< Interpolator, Bootstrap, Traits >.
Definition at line 44 of file yoyinflationoptionletvolatilitystructure.cpp.
References frequency(), indexIsInterpolated(), QuantLib::inflationPeriod(), observationLag(), and QuantLib::TermStructure::referenceDate().
Referenced by checkRange(), QuantLib::YoYInflationVolatilityTraits::initialDate(), QuantLib::InterpolatedYoYOptionletVolatilityCurve< Interpolator1D >::InterpolatedYoYOptionletVolatilityCurve(), and timeFromBase().
{
        // Depends on interpolation, or not, of observed index
        // and observation lag with which it was built.
        // We want this to work even if the index does not
        // have a yoy term structure.
        if (indexIsInterpolated()) {
            return referenceDate() - observationLag();
        } else {
            return inflationPeriod(referenceDate() - observationLag(),
                                   frequency()).first;
        }
    }
virtual Volatility QuantLib::YoYOptionletVolatilitySurface::baseLevel () const [inline, virtual]
Definition at line 112 of file yoyinflationoptionletvolatilitystructure.hpp.
References baseLevel_, and QL_REQUIRE.
Referenced by QuantLib::YoYInflationVolatilityTraits::initialValue().
{
            QL_REQUIRE(baseLevel_ != Null<Volatility>(),
                       "Base volatility, for baseDate(), not set.");
            return baseLevel_;
        }
void QuantLib::YoYOptionletVolatilitySurface::checkRange (const Date & d, Rate strike, bool extrapolate) const [protected, virtual]
Definition at line 59 of file yoyinflationoptionletvolatilitystructure.cpp.
References QuantLib::Extrapolator::allowsExtrapolation(), baseDate(), QuantLib::TermStructure::maxDate(), maxStrike(), minStrike(), and QL_REQUIRE.
Referenced by volatility().
{
        QL_REQUIRE(d >= baseDate(),
                   "date (" << d << ") is before base date");
        QL_REQUIRE(extrapolate || allowsExtrapolation() || d <= maxDate(),
                   "date (" << d << ") is past max curve date ("
                   << maxDate() << ")");
        QL_REQUIRE(extrapolate || allowsExtrapolation() ||
                   (strike >= minStrike() && strike <= maxStrike()),
                   "strike (" << strike << ") is outside the curve domain ["
                   << minStrike() << "," << maxStrike()<< "]] at date = " << d);
    }
void QuantLib::YoYOptionletVolatilitySurface::checkRange (Time t, Rate strike, bool extrapolate) const [protected, virtual]
Definition at line 73 of file yoyinflationoptionletvolatilitystructure.cpp.
References QuantLib::Extrapolator::allowsExtrapolation(), baseDate(), maxStrike(), QuantLib::TermStructure::maxTime(), minStrike(), QL_REQUIRE, and QuantLib::TermStructure::timeFromReference().
{
        QL_REQUIRE(t >= timeFromReference(baseDate()),
                   "time (" << t << ") is before base date");
        QL_REQUIRE(extrapolate || allowsExtrapolation() || t <= maxTime(),
                   "time (" << t << ") is past max curve time ("
                   << maxTime() << ")");
        QL_REQUIRE(extrapolate || allowsExtrapolation() ||
                   (strike >= minStrike() && strike <= maxStrike()),
                   "strike (" << strike << ") is outside the curve domain ["
                   << minStrike() << "," << maxStrike()<< "] at time = " << t);
    }
virtual Frequency QuantLib::YoYOptionletVolatilitySurface::frequency () const [inline, virtual]
Definition at line 95 of file yoyinflationoptionletvolatilitystructure.hpp.
References frequency_.
Referenced by baseDate(), timeFromBase(), and volatility().
{ return frequency_; }
virtual bool QuantLib::YoYOptionletVolatilitySurface::indexIsInterpolated () const [inline, virtual]
Definition at line 96 of file yoyinflationoptionletvolatilitystructure.hpp.
References indexIsInterpolated_.
Referenced by baseDate(), timeFromBase(), and volatility().
{ return indexIsInterpolated_; }
virtual Real QuantLib::YoYOptionletVolatilitySurface::maxStrike () const [pure virtual]
the maximum strike for which the term structure can return vols
Implements QuantLib::VolatilityTermStructure.
Implemented in QuantLib::ConstantYoYOptionletVolatility, QuantLib::InterpolatedYoYOptionletVolatilityCurve< Interpolator1D >, QuantLib::InterpolatedYoYOptionletVolatilityCurve< Interpolator >, and QuantLib::KInterpolatedYoYOptionletVolatilitySurface< Interpolator1D >.
Referenced by checkRange().
virtual Real QuantLib::YoYOptionletVolatilitySurface::minStrike () const [pure virtual]
the minimum strike for which the term structure can return vols
Implements QuantLib::VolatilityTermStructure.
Implemented in QuantLib::ConstantYoYOptionletVolatility, QuantLib::InterpolatedYoYOptionletVolatilityCurve< Interpolator1D >, QuantLib::InterpolatedYoYOptionletVolatilityCurve< Interpolator >, and QuantLib::KInterpolatedYoYOptionletVolatilitySurface< Interpolator1D >.
Referenced by checkRange().
virtual Period QuantLib::YoYOptionletVolatilitySurface::observationLag () const [inline, virtual]
The TS observes with a lag that is usually different from the availability lag of the index. An inflation rate is given, by default, for the maturity requested assuming this lag.
Definition at line 94 of file yoyinflationoptionletvolatilitystructure.hpp.
References observationLag_.
Referenced by baseDate(), timeFromBase(), and volatility().
{ return observationLag_; }
virtual void QuantLib::YoYOptionletVolatilitySurface::setBaseLevel (Volatility v) [inline, protected, virtual]
Definition at line 129 of file yoyinflationoptionletvolatilitystructure.hpp.
References baseLevel_, and anonymous_namespace{perturbativebarrieroptionengine.cpp}::v().
Referenced by QuantLib::InterpolatedYoYOptionletVolatilityCurve< Interpolator1D >::InterpolatedYoYOptionletVolatilityCurve().
{ baseLevel_ = v; }
Time QuantLib::YoYOptionletVolatilitySurface::timeFromBase (const Date & date, const Period & obsLag = Period(-1,Days)) const [virtual]
base date will be in the past because of observation lag
needed for total variance calculations
Definition at line 123 of file yoyinflationoptionletvolatilitystructure.cpp.
References baseDate(), QuantLib::TermStructure::dayCounter(), QuantLib::Days, frequency(), indexIsInterpolated(), QuantLib::inflationPeriod(), observationLag(), and QuantLib::DayCounter::yearFraction().
Referenced by totalVariance().
{
        Period useLag = obsLag;
        if (obsLag==Period(-1,Days)) {
            useLag = observationLag();
        }
        Date useDate;
        if (indexIsInterpolated()) {
            useDate = maturityDate - useLag;
        } else {
            useDate = inflationPeriod(maturityDate - useLag,
                                      frequency()).first;
        }
        // This assumes that the inflation term structure starts
        // as late as possible given the inflation index definition,
        // which is the usual case.
        return dayCounter().yearFraction(baseDate(), useDate);
    }
Volatility QuantLib::YoYOptionletVolatilitySurface::totalVariance (const Date & exerciseDate, Rate strike, const Period & obsLag = Period(-1,Days), bool extrapolate = false) const [virtual]
Returns the total integrated variance for a given exercise date and strike rate.
Total integrated variance is useful because it scales out t for the optionlet pricing formulae. Note that it is called "total" because the surface does not know whether it represents Black, Bachelier or Displaced Diffusion variance. These are virtual so alternate connections between const vol and total var are possible.
Because inflation is highly linked to dates (for interpolation, periods, etc) we do NOT provide a time version
Definition at line 147 of file yoyinflationoptionletvolatilitystructure.cpp.
References anonymous_namespace{quantlibbenchmark.cpp}::t, timeFromBase(), and volatility().
Referenced by totalVariance().
{
        Volatility vol = volatility(maturityDate, strike, obsLag, extrapolate);
        Time t = timeFromBase(maturityDate, obsLag);
        return vol*vol*t;
    }
Volatility QuantLib::YoYOptionletVolatilitySurface::totalVariance (const Period & optionTenor, Rate strike, const Period & obsLag = Period(-1,Days), bool extrapolate = false) const [virtual]
returns the total integrated variance for a given option tenor and strike rate
Definition at line 159 of file yoyinflationoptionletvolatilitystructure.cpp.
References QuantLib::VolatilityTermStructure::optionDateFromTenor(), and totalVariance().
{
        Date maturityDate = optionDateFromTenor(tenor);
        return totalVariance(maturityDate, strike, obsLag, extrap);
    }
Volatility QuantLib::YoYOptionletVolatilitySurface::volatility (const Date & maturityDate, Rate strike, const Period & obsLag = Period(-1,Days), bool extrapolate = false) const
Returns the volatility for a given maturity date and strike rate that observes inflation, by default, with the observation lag of the term structure. Because inflation is highly linked to dates (for interpolation, periods, etc) we do NOT provide a time version.
Definition at line 88 of file yoyinflationoptionletvolatilitystructure.cpp.
References checkRange(), QuantLib::Days, frequency(), indexIsInterpolated(), QuantLib::inflationPeriod(), observationLag(), anonymous_namespace{quantlibbenchmark.cpp}::t, QuantLib::TermStructure::timeFromReference(), and volatilityImpl().
Referenced by totalVariance(), and volatility().
{
        Period useLag = obsLag;
        if (obsLag==Period(-1,Days)) {
            useLag = observationLag();
        }
        if (indexIsInterpolated()) {
            YoYOptionletVolatilitySurface::checkRange(maturityDate-useLag, strike, extrapolate);
            Time t = timeFromReference(maturityDate-useLag);
            return volatilityImpl(t,strike);
        } else {
            std::pair<Date,Date> dd = inflationPeriod(maturityDate-useLag, frequency());
            YoYOptionletVolatilitySurface::checkRange(dd.first, strike, extrapolate);
            Time t = timeFromReference(dd.first);
            return volatilityImpl(t,strike);
        }
    }
Volatility QuantLib::YoYOptionletVolatilitySurface::volatility (const Period & optionTenor, Rate strike, const Period & obsLag = Period(-1,Days), bool extrapolate = false) const
returns the volatility for a given option tenor and strike rate
Definition at line 112 of file yoyinflationoptionletvolatilitystructure.cpp.
References QuantLib::VolatilityTermStructure::optionDateFromTenor(), and volatility().
{
        Date maturityDate = optionDateFromTenor(optionTenor);
        return volatility(maturityDate, strike, obsLag, extrapolate);
    }
virtual Volatility QuantLib::YoYOptionletVolatilitySurface::volatilityImpl (Time length, Rate strike) const [protected, pure virtual]
Implements the actual volatility surface calculation in derived classes e.g. bilinear interpolation. N.B. does not derive the surface.
Implemented in QuantLib::ConstantYoYOptionletVolatility, QuantLib::InterpolatedYoYOptionletVolatilityCurve< Interpolator1D >, QuantLib::InterpolatedYoYOptionletVolatilityCurve< Interpolator >, and QuantLib::KInterpolatedYoYOptionletVolatilitySurface< Interpolator1D >.
Referenced by volatility().
Member Data Documentation
Volatility QuantLib::YoYOptionletVolatilitySurface::baseLevel_ [mutable, protected]
Definition at line 130 of file yoyinflationoptionletvolatilitystructure.hpp.
Referenced by baseLevel(), and setBaseLevel().
Frequency QuantLib::YoYOptionletVolatilitySurface::frequency_ [protected]
Definition at line 134 of file yoyinflationoptionletvolatilitystructure.hpp.
Referenced by frequency().
bool QuantLib::YoYOptionletVolatilitySurface::indexIsInterpolated_ [protected]
Definition at line 135 of file yoyinflationoptionletvolatilitystructure.hpp.
Referenced by indexIsInterpolated().
Period QuantLib::YoYOptionletVolatilitySurface::observationLag_ [protected]
Definition at line 133 of file yoyinflationoptionletvolatilitystructure.hpp.
Referenced by observationLag().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/inflation/yoyinflationoptionletvolatilitystructure.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/inflation/yoyinflationoptionletvolatilitystructure.cpp