QuantLib: QuantLib::AnalyticHestonEngine Class Reference
QuantLib::AnalyticHestonEngine Class Reference
analytic Heston-model engine based on Fourier transform
#include <analytichestonengine.hpp>
Classes
class Fj_Helper
class Integration
Public Types
enum ComplexLogFormula { Gatheral, BranchCorrection }
Public Member Functions
AnalyticHestonEngine (const boost::shared_ptr< HestonModel > &model, Real relTolerance, Size maxEvaluations)
AnalyticHestonEngine (const boost::shared_ptr< HestonModel > &model, Size integrationOrder=144)
AnalyticHestonEngine (const boost::shared_ptr< HestonModel > &model, ComplexLogFormula cpxLog, const Integration &itg)
void calculate () const
Size numberOfEvaluations () const
Static Public Member Functions
static void doCalculation (Real riskFreeDiscount, Real dividendDiscount, Real spotPrice, Real strikePrice, Real term, Real kappa, Real theta, Real sigma, Real v0, Real rho, const TypePayoff &type, const Integration &integration, const ComplexLogFormula cpxLog, const AnalyticHestonEngine *const enginePtr, Real &value, Size &evaluations)
Protected Member Functions
virtual std::complex< Real > addOnTerm (Real phi, Time t, Size j) const
Private Attributes
Size evaluations_
const ComplexLogFormula cpxLog_
const boost::shared_ptr
< Integration > integration_
Detailed Description
analytic Heston-model engine based on Fourier transform
Integration detail: Two algebraically equivalent formulations of the complex logarithm of the Heston model exist. Gatherals [2005] (also Duffie, Pan and Singleton [2000], and Schoutens, Simons and Tistaert[2004]) version does not cause discoutinuities whereas the original version (e.g. Heston [1993]) needs some sort of "branch correction" to work properly. Gatheral's version does also work with adaptive integration routines and should be preferred over the original Heston version.
References:
Heston, Steven L., 1993. A Closed-Form Solution for Options with Stochastic Volatility with Applications to Bond and Currency Options. The review of Financial Studies, Volume 6, Issue 2, 327-343.
A. Sepp, Pricing European-Style Options under Jump Diffusion Processes with Stochastic Volatility: Applications of Fourier Transform (<http://math.ut.ee/~spartak/papers/stochjumpvols.pdf>)
R. Lord and C. Kahl, Why the rotation count algorithm works, http://papers.ssrn.com/sol3/papers.cfm?abstract_id=921335
H. Albrecher, P. Mayer, W.Schoutens and J. Tistaert, The Little Heston Trap, http://www.schoutens.be/HestonTrap.pdf
J. Gatheral, The Volatility Surface: A Practitioner's Guide, Wiley Finance
Test:
the correctness of the returned value is tested by reproducing results available in web/literature and comparison with Black pricing.
Definition at line 78 of file analytichestonengine.hpp.
Member Enumeration Documentation
enum QuantLib::AnalyticHestonEngine::ComplexLogFormula
Enumerator:
Gatheral
BranchCorrection
Definition at line 84 of file analytichestonengine.hpp.
{ Gatheral, BranchCorrection };
Constructor & Destructor Documentation
QuantLib::AnalyticHestonEngine::AnalyticHestonEngine (const boost::shared_ptr< HestonModel > & model, Real relTolerance, Size maxEvaluations)
Definition at line 299 of file analytichestonengine.cpp.
    : GenericModelEngine<HestonModel,
                         VanillaOption::arguments,
                         VanillaOption::results>(model),
      cpxLog_(Gatheral),
      integration_(new Integration(Integration::gaussLobatto(
                              relTolerance, Null<Real>(), maxEvaluations))) {
    }
QuantLib::AnalyticHestonEngine::AnalyticHestonEngine (const boost::shared_ptr< HestonModel > & model, Size integrationOrder = 144)
Definition at line 288 of file analytichestonengine.cpp.
    : GenericModelEngine<HestonModel,
                         VanillaOption::arguments,
                         VanillaOption::results>(model),
      cpxLog_     (Gatheral),
      integration_(new Integration(
                          Integration::gaussLaguerre(integrationOrder))) {
    }
QuantLib::AnalyticHestonEngine::AnalyticHestonEngine (const boost::shared_ptr< HestonModel > & model, ComplexLogFormula cpxLog, const Integration & itg)
Definition at line 310 of file analytichestonengine.cpp.
References BranchCorrection, cpxLog_, QuantLib::AnalyticHestonEngine::Integration::isAdaptiveIntegration(), and QL_REQUIRE.
    : GenericModelEngine<HestonModel,
                         VanillaOption::arguments,
                         VanillaOption::results>(model),
      cpxLog_(cpxLog),
      integration_(new Integration(integration)) {
        QL_REQUIRE(   cpxLog_ != BranchCorrection
                   || !integration.isAdaptiveIntegration(),
                   "Branch correction does not work in conjunction "
                   "with adaptive integration methods");
    }
Member Function Documentation
std::complex< Real > QuantLib::AnalyticHestonEngine::addOnTerm (Real phi, Time t, Size j) const [inline, protected, virtual]
Reimplemented in QuantLib::BatesDoubleExpDetJumpEngine, QuantLib::BatesDoubleExpEngine, QuantLib::BatesDetJumpEngine, QuantLib::BatesEngine, and QuantLib::AnalyticHestonHullWhiteEngine.
Definition at line 189 of file analytichestonengine.hpp.
Referenced by QuantLib::AnalyticHestonEngine::Fj_Helper::operator()().
{
        return std::complex<Real>(0,0);
    }
void QuantLib::AnalyticHestonEngine::calculate () const [virtual]
Implements QuantLib::PricingEngine.
Reimplemented in QuantLib::AnalyticHestonHullWhiteEngine.
Definition at line 379 of file analytichestonengine.cpp.
References QuantLib::GenericEngine< VanillaOption::arguments, VanillaOption::results >::arguments_, cpxLog_, doCalculation(), QuantLib::Exercise::European, evaluations_, QuantLib::Option::arguments::exercise, integration_, QuantLib::GenericModelEngine< HestonModel, VanillaOption::arguments, VanillaOption::results >::model_, QuantLib::Option::arguments::payoff, QL_REQUIRE, QuantLib::GenericEngine< VanillaOption::arguments, VanillaOption::results >::results_, and QuantLib::Instrument::results::value.
    {
        // this is a european option pricer
        QL_REQUIRE(arguments_.exercise->type() == Exercise::European,
                   "not an European option");
        // plain vanilla
        boost::shared_ptr<PlainVanillaPayoff> payoff =
            boost::dynamic_pointer_cast<PlainVanillaPayoff>(arguments_.payoff);
        QL_REQUIRE(payoff, "non-striked payoff given");
        const boost::shared_ptr<HestonProcess>& process = model_->process();
        const Real riskFreeDiscount = process->riskFreeRate()->discount(
                                            arguments_.exercise->lastDate());
        const Real dividendDiscount = process->dividendYield()->discount(
                                            arguments_.exercise->lastDate());
        const Real spotPrice = process->s0()->value();
        QL_REQUIRE(spotPrice > 0.0, "negative or null underlying given");
        const Real strikePrice = payoff->strike();
        const Real term = process->time(arguments_.exercise->lastDate());
        doCalculation(riskFreeDiscount,
                      dividendDiscount,
                      spotPrice,
                      strikePrice,
                      term,
                      model_->kappa(),
                      model_->theta(),
                      model_->sigma(),
                      model_->v0(),
                      model_->rho(),
                      *payoff,
                      *integration_,
                      cpxLog_,
                      this,
                      results_.value,
                      evaluations_);
    }
void QuantLib::AnalyticHestonEngine::doCalculation (Real riskFreeDiscount, Real dividendDiscount, Real spotPrice, Real strikePrice, Real term, Real kappa, Real theta, Real sigma, Real v0, Real rho, const TypePayoff & type, const Integration & integration, const ComplexLogFormula cpxLog, const AnalyticHestonEngine *const enginePtr, Real & value, Size & evaluations) [static]
Definition at line 329 of file analytichestonengine.cpp.
References QuantLib::AnalyticHestonEngine::Integration::calculate(), QuantLib::Option::Call, M_PI, QuantLib::AnalyticHestonEngine::Integration::numberOfEvaluations(), QuantLib::TypePayoff::optionType(), QuantLib::Option::Put, and QL_FAIL.
Referenced by calculate(), and MarketModelTest::testStochVolForwardsAndOptionlets().
    {
        const Real ratio = riskFreeDiscount/dividendDiscount;
        const Real c_inf = std::min(10.0, std::max(0.0001,
                std::sqrt(1.0-square<Real>()(rho))/sigma))
                *(v0 + kappa*theta*term);
        evaluations = 0;
        const Real p1 = integration.calculate(c_inf,
            Fj_Helper(kappa,theta,sigma,v0,spotPrice,rho, enginePtr, cpxLog, term, strikePrice, ratio, 1))
            //Fj_Helper(arguments_, model_, this, cpxLog_, term, ratio, 1))
            /M_PI;
        evaluations+= integration.numberOfEvaluations();
        const Real p2 = integration.calculate(c_inf,
                  Fj_Helper(kappa,theta,sigma,v0,spotPrice,rho, enginePtr, cpxLog, term, strikePrice, ratio, 2))
            //Fj_Helper(arguments_, model_, this, cpxLog_, term, ratio, 2))
            /M_PI;
        evaluations+= integration.numberOfEvaluations();
        switch (type.optionType())
        {
          case Option::Call:
            value = spotPrice*dividendDiscount*(p1+0.5)
                           - strikePrice*riskFreeDiscount*(p2+0.5);
            break;
          case Option::Put:
            value = spotPrice*dividendDiscount*(p1-0.5)
                           - strikePrice*riskFreeDiscount*(p2-0.5);
            break;
          default:
            QL_FAIL("unknown option type");
        }
    }
Size QuantLib::AnalyticHestonEngine::numberOfEvaluations () const
Definition at line 325 of file analytichestonengine.cpp.
References evaluations_.
{
        return evaluations_;
    }
Member Data Documentation
const ComplexLogFormula QuantLib::AnalyticHestonEngine::cpxLog_ [private]
Definition at line 132 of file analytichestonengine.hpp.
Referenced by AnalyticHestonEngine(), calculate(), and QuantLib::AnalyticHestonEngine::Fj_Helper::operator()().
Size QuantLib::AnalyticHestonEngine::evaluations_ [mutable, private]
Definition at line 129 of file analytichestonengine.hpp.
Referenced by calculate(), and numberOfEvaluations().
const boost::shared_ptr<Integration> QuantLib::AnalyticHestonEngine::integration_ [private]
Definition at line 133 of file analytichestonengine.hpp.
Referenced by calculate().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/vanilla/analytichestonengine.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/vanilla/analytichestonengine.cpp