QuantLib: QuantLib::EnergyCommodity Class Reference
QuantLib::EnergyCommodity Class Reference
Energy commodity class.
#include <energycommodity.hpp>
Classes
class arguments
class engine
class results
Public Types
enum DeliverySchedule {
Constant, Window, Hourly, Daily,
Weekly, Monthly, Quarterly, Yearly
}
enum QuantityPeriodicity {
Absolute, PerHour, PerDay, PerWeek,
PerMonth, PerQuarter, PerYear
}
enum PaymentSchedule { WindowSettlement, MonthlySettlement, QuarterlySettlement, YearlySettlement }
Public Member Functions
EnergyCommodity (const CommodityType &commodityType, const boost::shared_ptr< SecondaryCosts > &secondaryCosts)
virtual Quantity quantity () const =0
const CommodityType & commodityType () const
void setupArguments (PricingEngine::arguments *) const
void fetchResults (const PricingEngine::results *) const
Protected Member Functions
Real calculateUnitCost (const CommodityType &commodityType, const CommodityUnitCost &unitCost, const Date &evaluationDate) const
void calculateSecondaryCostAmounts (const CommodityType &commodityType, Real totalQuantityValue, const Date &evaluationDate) const
Static Protected Member Functions
static Real calculateFxConversionFactor (const Currency &fromCurrency, const Currency &toCurrency, const Date &evaluationDate)
static Real calculateUomConversionFactor (const CommodityType &commodityType, const UnitOfMeasure &fromUnitOfMeasure, const UnitOfMeasure &toUnitOfMeasure)
Protected Attributes
CommodityType commodityType_
Detailed Description
Energy commodity class.
Definition at line 63 of file energycommodity.hpp.
Member Enumeration Documentation
enum QuantLib::EnergyCommodity::DeliverySchedule
Enumerator:
Constant
Window
Hourly
Daily
Weekly
Monthly
Quarterly
Yearly
Definition at line 69 of file energycommodity.hpp.
                              { Constant,
                                Window,
                                Hourly,
                                Daily,
                                Weekly,
                                Monthly,
                                Quarterly,
                                Yearly };
enum QuantLib::EnergyCommodity::PaymentSchedule
Enumerator:
WindowSettlement
MonthlySettlement
QuarterlySettlement
YearlySettlement
Definition at line 84 of file energycommodity.hpp.
                             { WindowSettlement,
                               MonthlySettlement,
                               QuarterlySettlement,
                               YearlySettlement };
enum QuantLib::EnergyCommodity::QuantityPeriodicity
Enumerator:
Absolute
PerHour
PerDay
PerWeek
PerMonth
PerQuarter
PerYear
Definition at line 77 of file energycommodity.hpp.
                                 { Absolute,
                                   PerHour,
                                   PerDay,
                                   PerWeek,
                                   PerMonth,
                                   PerQuarter,
                                   PerYear };
Constructor & Destructor Documentation
QuantLib::EnergyCommodity::EnergyCommodity (const CommodityType & commodityType, const boost::shared_ptr< SecondaryCosts > & secondaryCosts)
Definition at line 88 of file energycommodity.cpp.
    : Commodity(secondaryCosts), commodityType_(commodityType) {}
Member Function Documentation
Real QuantLib::EnergyCommodity::calculateFxConversionFactor (const Currency & fromCurrency, const Currency & toCurrency, const Date & evaluationDate) [static, protected]
Definition at line 112 of file energycommodity.cpp.
References QuantLib::Singleton< ExchangeRateManager >::instance(), QuantLib::ExchangeRateManager::lookup(), QuantLib::ExchangeRate::rate(), and QuantLib::ExchangeRate::target().
Referenced by calculateSecondaryCostAmounts(), calculateUnitCost(), QuantLib::EnergyFuture::performCalculations(), QuantLib::EnergyBasisSwap::performCalculations(), and QuantLib::EnergyVanillaSwap::performCalculations().
{
        if (fromCurrency != toCurrency) {
            ExchangeRate exchRate = ExchangeRateManager::instance().lookup(
                                   fromCurrency, toCurrency,
                                   evaluationDate /*, ExchangeRate::Direct*/);
            if (fromCurrency == exchRate.target())
                return 1.0 / exchRate.rate();
            return exchRate.rate();
        }
        return 1;
    }
void QuantLib::EnergyCommodity::calculateSecondaryCostAmounts (const CommodityType & commodityType, Real totalQuantityValue, const Date & evaluationDate) const [protected]
Definition at line 148 of file energycommodity.cpp.
References calculateFxConversionFactor(), calculateUnitCost(), QuantLib::CommoditySettings::currency(), QuantLib::Money::currency(), QuantLib::Singleton< CommoditySettings >::instance(), QL_FAIL, QuantLib::Commodity::secondaryCostAmounts_, QuantLib::Commodity::secondaryCosts_, and QuantLib::Money::value().
Referenced by QuantLib::EnergyFuture::performCalculations(), QuantLib::EnergyBasisSwap::performCalculations(), and QuantLib::EnergyVanillaSwap::performCalculations().
{
        secondaryCostAmounts_.empty();
        if (secondaryCosts_ != 0) {
            const Currency& baseCurrency =
                CommoditySettings::instance().currency();
            try {
                for (SecondaryCosts::const_iterator i = secondaryCosts_->begin();
                     i != secondaryCosts_->end(); i++) {
                    if (boost::any_cast<CommodityUnitCost>(&i->second)) {
                        Real value =
                            calculateUnitCost(
                                commodityType,
                                boost::any_cast<CommodityUnitCost>(i->second),
                                evaluationDate) * totalQuantityValue;
                        secondaryCostAmounts_[i->first] =
                            Money(baseCurrency, value);
                    } else if (boost::any_cast<Money>(&i->second)) {
                        const Money& amount = boost::any_cast<Money>(i->second);
                        Real fxConversionFactor =
                            calculateFxConversionFactor(amount.currency(),
                                                        baseCurrency,
                                                        evaluationDate);
                        secondaryCostAmounts_[i->first] =
                            Money(baseCurrency,
                                  amount.value() * fxConversionFactor);
                    }
                }
            } catch (const std::exception& e) {
                QL_FAIL("error calculating secondary costs: " << e.what());
            }
        }
    }
Real QuantLib::EnergyCommodity::calculateUnitCost (const CommodityType & commodityType, const CommodityUnitCost & unitCost, const Date & evaluationDate) const [protected]
Definition at line 127 of file energycommodity.cpp.
References QuantLib::CommodityUnitCost::amount(), calculateFxConversionFactor(), calculateUomConversionFactor(), QuantLib::CommoditySettings::currency(), QuantLib::Money::currency(), QuantLib::Singleton< CommoditySettings >::instance(), QuantLib::CommodityUnitCost::unitOfMeasure(), QuantLib::CommoditySettings::unitOfMeasure(), and QuantLib::Money::value().
Referenced by calculateSecondaryCostAmounts().
{
        if (unitCost.amount().value() != 0) {
            const Currency& baseCurrency =
                CommoditySettings::instance().currency();
            const UnitOfMeasure baseUnitOfMeasure =
                CommoditySettings::instance().unitOfMeasure();
            Real unitCostUomConversionFactor =
                calculateUomConversionFactor(commodityType,
                                             unitCost.unitOfMeasure(),
                                             baseUnitOfMeasure);
            Real unitCostFxConversionFactor =
                calculateFxConversionFactor(unitCost.amount().currency(),
                                            baseCurrency, evaluationDate);
            return unitCost.amount().value() * unitCostUomConversionFactor
                 * unitCostFxConversionFactor;
        }
        return 0;
    }
Real QuantLib::EnergyCommodity::calculateUomConversionFactor (const CommodityType & commodityType, const UnitOfMeasure & fromUnitOfMeasure, const UnitOfMeasure & toUnitOfMeasure) [static, protected]
Definition at line 98 of file energycommodity.cpp.
References QuantLib::UnitOfMeasureConversion::conversionFactor(), QuantLib::Singleton< UnitOfMeasureConversionManager >::instance(), and QuantLib::UnitOfMeasureConversionManager::lookup().
Referenced by calculateUnitCost(), QuantLib::EnergyFuture::performCalculations(), QuantLib::EnergyBasisSwap::performCalculations(), and QuantLib::EnergyVanillaSwap::performCalculations().
{
        if (toUnitOfMeasure != fromUnitOfMeasure) {
            UnitOfMeasureConversion uomConv =
                UnitOfMeasureConversionManager::instance().lookup(
                           commodityType, fromUnitOfMeasure, toUnitOfMeasure);
            return uomConv.conversionFactor();
        }
        return 1;
    }
const CommodityType & QuantLib::EnergyCommodity::commodityType () const
Reimplemented in QuantLib::EnergySwap.
Definition at line 93 of file energycommodity.cpp.
References commodityType_.
{
        return commodityType_;
    }
void QuantLib::EnergyCommodity::fetchResults (const PricingEngine::results * r) const [virtual]
When a derived result structure is defined for an instrument, this method should be overridden to read from it. This is mandatory in case a pricing engine is used.
Reimplemented from QuantLib::Instrument.
Definition at line 81 of file energycommodity.cpp.
References QL_REQUIRE.
{
        Instrument::fetchResults(r);
        const EnergyCommodity::results* results =
            dynamic_cast<const EnergyCommodity::results*>(r);
        QL_REQUIRE(results != 0, "wrong result type");
    }
virtual Quantity QuantLib::EnergyCommodity::quantity () const [pure virtual]
Implemented in QuantLib::EnergySwap, and QuantLib::EnergyFuture.
void QuantLib::EnergyCommodity::setupArguments (PricingEngine::arguments *) const [virtual]
When a derived argument structure is defined for an instrument, this method should be overridden to fill it. This is mandatory in case a pricing engine is used.
Reimplemented from QuantLib::Instrument.
Definition at line 73 of file energycommodity.cpp.
References QL_REQUIRE.
{
        EnergyCommodity::arguments* arguments =
            dynamic_cast<EnergyCommodity::arguments*>(args);
        QL_REQUIRE(arguments != 0, "wrong argument type");
        //arguments->legs = legs_;
        //arguments->payer = payer_;
    }
Member Data Documentation
CommodityType QuantLib::EnergyCommodity::commodityType_ [protected]
Definition at line 114 of file energycommodity.hpp.
Referenced by commodityType().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/commodities/energycommodity.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/commodities/energycommodity.cpp