QuantLib: QuantLib::DefaultEvent::DefaultSettlement Class Reference
QuantLib::DefaultEvent::DefaultSettlement Class Reference
#include <defaultevent.hpp>
Public Member Functions
Date date () const
returns the date at which the event occurs
Real recoveryRate (Seniority sen) const
void accept (AcyclicVisitor &)
Protected Member Functions
DefaultSettlement (const Date &date, const std::map< Seniority, Real > &recoveryRates)
DefaultSettlement (const Date &date=Date(), Seniority seniority=NoSeniority, Real recoveryRate=0.4)
Private Attributes
Date settlementDate_
std::map< Seniority, Real > recoveryRates_
Realized recovery rates.
Friends
class DefaultEvent
Detailed Description
Definition at line 51 of file defaultevent.hpp.
Constructor & Destructor Documentation
QuantLib::DefaultEvent::DefaultSettlement::DefaultSettlement (const Date & date, const std::map< Seniority, Real > & recoveryRates) [protected]
Default settlement events encode the settlement date and the recovery rates for the affected seniorities. Specific events might require different sets of recoveries to be present. The way these objects are constructed is a prerogative of the particular event class.
Definition at line 54 of file defaultevent.cpp.
References QuantLib::NoSeniority, and QL_REQUIRE.
    : settlementDate_(date), recoveryRates_(recoveryRates) {
        QL_REQUIRE(recoveryRates.find(NoSeniority) ==
            recoveryRates.end(),
            "NoSeniority is not a valid realized seniority.");
    }
QuantLib::DefaultEvent::DefaultSettlement::DefaultSettlement (const Date & date = Date(), Seniority seniority = NoSeniority, Real recoveryRate = 0.4) [protected]
When NoSeniority is passed all seniorities are assumed to have settled to the recovery passed.
Definition at line 63 of file defaultevent.cpp.
References QuantLib::NoSeniority, recoveryRate(), and recoveryRates_.
    : settlementDate_(date), recoveryRates_(makeIsdaConvMap()) {
        if (seniority == NoSeniority) {
            for (std::map<Seniority, Real>::iterator i=recoveryRates_.begin();
                 i != recoveryRates_.end(); ++i) {
                i->second = recoveryRate;
            }
        } else {
            recoveryRates_[seniority] = recoveryRate;
        }
    }
Member Function Documentation
void QuantLib::DefaultEvent::DefaultSettlement::accept (AcyclicVisitor & v) [virtual]
Reimplemented from QuantLib::Event.
Definition at line 45 of file defaultevent.cpp.
References QuantLib::DefaultEvent::accept(), anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Visitor< T >::visit().
{
        Visitor<DefaultEvent::DefaultSettlement>* v1 =
            dynamic_cast<Visitor<DefaultEvent::DefaultSettlement>*>(&v);
        if (v1 != 0)
            v1->visit(*this);
        else
            Event::accept(v);
    }
Date QuantLib::DefaultEvent::DefaultSettlement::date () const [virtual]
returns the date at which the event occurs
Implements QuantLib::Event.
Definition at line 41 of file defaultevent.cpp.
References settlementDate_.
Referenced by QuantLib::DefaultEvent::hasSettled().
{
        return settlementDate_;
    }
Real QuantLib::DefaultEvent::DefaultSettlement::recoveryRate (Seniority sen) const
Returns the recovery rate of a default event which has already settled.
Definition at line 78 of file defaultevent.cpp.
References QuantLib::NoSeniority, and QL_REQUIRE.
Referenced by DefaultSettlement(), and QuantLib::DefaultEvent::recoveryRate().
{
        // expensive require cause called often...... fix me
        QL_REQUIRE(sen != NoSeniority,
            "NoSeniority is not valid for recovery rate request.");
        std::map<Seniority, Real>::const_iterator itmatch =
            recoveryRates_.find(sen);
        if(itmatch != recoveryRates_.end()) {
            return itmatch->second;
        }else{
            return Null<Real>();
        }
    }
Friends And Related Function Documentation
friend class DefaultEvent [friend]
Definition at line 53 of file defaultevent.hpp.
Member Data Documentation
std::map<Seniority, Real> QuantLib::DefaultEvent::DefaultSettlement::recoveryRates_ [private]
Realized recovery rates.
Definition at line 80 of file defaultevent.hpp.
Referenced by DefaultSettlement().
Date QuantLib::DefaultEvent::DefaultSettlement::settlementDate_ [private]
Definition at line 78 of file defaultevent.hpp.
Referenced by date().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/defaultevent.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/defaultevent.cpp