QuantLib: QuantLib::Period Class Reference
QuantLib::Period Class Reference
#include <period.hpp>
Public Member Functions
Period ()
Period (Integer n, TimeUnit units)
Period (Frequency f)
Integer length () const
TimeUnit units () const
Frequency frequency () const
Period & operator+= (const Period &)
Period & operator-= (const Period &)
Period & operator/= (Integer)
void normalize ()
Private Attributes
Integer length_
TimeUnit units_
Related Functions
(Note that these are not member functions.)
Real years (const Period &)
Real months (const Period &)
Real weeks (const Period &)
Real days (const Period &)
template<typename T >
Period operator* (T n, TimeUnit units)
template<typename T >
Period operator* (TimeUnit units, T n)
Period operator- (const Period &)
Period operator* (Integer n, const Period &)
Period operator* (const Period &, Integer n)
Period operator/ (const Period &, Integer n)
Period operator+ (const Period &, const Period &)
Period operator- (const Period &, const Period &)
bool operator< (const Period &, const Period &)
bool operator== (const Period &, const Period &)
bool operator!= (const Period &, const Period &)
bool operator> (const Period &, const Period &)
bool operator<= (const Period &, const Period &)
bool operator>= (const Period &, const Period &)
std::ostream & operator<< (std::ostream &, const Period &)
Detailed Description
This class provides a Period (length + TimeUnit) class and implements a limited algebra.
Test:
self-consistency of algebra is checked.
Definition at line 44 of file period.hpp.
Constructor & Destructor Documentation
QuantLib::Period::Period () [inline]
Definition at line 46 of file period.hpp.
        : length_(0), units_(Days) {}
QuantLib::Period::Period (Integer n, TimeUnit units) [inline]
Definition at line 48 of file period.hpp.
        : length_(n), units_(units) {}
QuantLib::Period::Period (Frequency f) [explicit]
Definition at line 28 of file period.cpp.
References QuantLib::Annual, QuantLib::Bimonthly, QuantLib::Biweekly, QuantLib::Daily, QuantLib::Days, QuantLib::EveryFourthMonth, QuantLib::EveryFourthWeek, anonymous_namespace{interpolations.cpp}::f(), length_, QuantLib::Monthly, QuantLib::Months, QuantLib::NoFrequency, QuantLib::Once, QuantLib::OtherFrequency, QL_FAIL, QuantLib::Quarterly, QuantLib::Semiannual, units_, QuantLib::Weekly, QuantLib::Weeks, and QuantLib::Years.
{
        switch (f) {
          case NoFrequency:
            // same as Period()
            units_ = Days;
            length_ = 0;
            break;
          case Once:
            units_ = Years;
            length_ = 0;
            break;
          case Annual:
            units_ = Years;
            length_ = 1;
            break;
          case Semiannual:
          case EveryFourthMonth:
          case Quarterly:
          case Bimonthly:
          case Monthly:
            units_ = Months;
            length_ = 12/f;
            break;
          case EveryFourthWeek:
          case Biweekly:
          case Weekly:
            units_ = Weeks;
            length_ = 52/f;
            break;
          case Daily:
            units_ = Days;
            length_ = 1;
            break;
          case OtherFrequency:
            QL_FAIL("unknown frequency");  // no point in showing 999...
          default:
            QL_FAIL("unknown frequency (" << Integer(f) << ")");
        }
    }
Member Function Documentation
Frequency QuantLib::Period::frequency () const
Definition at line 68 of file period.cpp.
References QuantLib::Annual, QuantLib::Biweekly, QuantLib::Daily, QuantLib::Days, QuantLib::EveryFourthWeek, length(), length_, QuantLib::Months, QuantLib::NoFrequency, QuantLib::Once, QuantLib::OtherFrequency, QL_FAIL, units_, QuantLib::Weekly, QuantLib::Weeks, and QuantLib::Years.
Referenced by QuantLib::CallableFixedRateBond::CallableFixedRateBond().
{
        // unsigned version
        Size length = std::abs(length_);
        if (length==0) {
            if (units_==Years) return Once;
            return NoFrequency;
        }
        switch (units_) {
          case Years:
            if (length == 1)
                return Annual;
            else
                return OtherFrequency;
          case Months:
            if (12%length == 0 && length <= 12)
                return Frequency(12/length);
            else
                return OtherFrequency;
          case Weeks:
            if (length==1)
                return Weekly;
            else if (length==2)
                return Biweekly;
            else if (length==4)
                return EveryFourthWeek;
            else
                return OtherFrequency;
          case Days:
            if (length==1)
                return Daily;
            else
                return OtherFrequency;
          default:
            QL_FAIL("unknown time unit (" << Integer(units_) << ")");
        }
    }
Integer QuantLib::Period::length () const [inline]
Definition at line 51 of file period.hpp.
References length_.
Referenced by QuantLib::Calendar::advance(), QuantLib::CallableBondVolatilityStructure::checkRange(), QuantLib::SwaptionVolatilityStructure::checkSwapTenor(), QuantLib::days(), QuantLib::anonymous_namespace{amortizingfixedratebond.cpp}::daysMinMax(), QuantLib::anonymous_namespace{period.cpp}::daysMinMax(), frequency(), QuantLib::HaganPricer::initialize(), QuantLib::months(), QuantLib::operator*(), QuantLib::Date::operator+(), operator+=(), QuantLib::Date::operator+=(), QuantLib::Date::operator-(), QuantLib::operator-(), QuantLib::Date::operator-=(), operator/=(), QuantLib::operator<(), QuantLib::detail::operator<<(), QuantLib::InterpolatedCPICapFloorTermPriceSurface< Interpolator2D >::performCalculations(), QuantLib::Schedule::Schedule(), QuantLib::MultiplicativePriceSeasonality::seasonalityFactor(), QuantLib::SwaptionVolatilityStructure::swapLength(), PeriodTest::testWeeksDaysAlgebra(), PeriodTest::testYearsMonthsAlgebra(), QuantLib::weeks(), and QuantLib::years().
{ return length_; }
void QuantLib::Period::normalize ()
Definition at line 107 of file period.cpp.
References QuantLib::Days, length_, QuantLib::Months, QL_FAIL, units_, QuantLib::Weeks, and QuantLib::Years.
Referenced by QuantLib::InterestRateIndex::InterestRateIndex(), PeriodTest::testWeeksDaysAlgebra(), and PeriodTest::testYearsMonthsAlgebra().
{
        if (length_!=0)
            switch (units_) {
              case Days:
                if (!(length_%7)) {
                    length_/=7;
                    units_ = Weeks;
                }
                break;
              case Months:
                if (!(length_%12)) {
                    length_/=12;
                    units_ = Years;
                }
                break;
              case Weeks:
              case Years:
                break;
              default:
                QL_FAIL("unknown time unit (" << Integer(units_) << ")");
            }
    }
Period & QuantLib::Period::operator+= (const Period & p)
Definition at line 130 of file period.cpp.
References QuantLib::Days, length(), length_, QuantLib::Months, QL_FAIL, QL_REQUIRE, units(), units_, QuantLib::Weeks, and QuantLib::Years.
Referenced by operator-=().
{
        if (length_==0) {
            length_ = p.length();
            units_ = p.units();
        } else if (units_==p.units()) {
            // no conversion needed
            length_ += p.length();
        } else {
            switch (units_) {
              case Years:
                switch (p.units()) {
                  case Months:
                    units_ = Months;
                    length_ = length_*12 + p.length();
                    break;
                  case Weeks:
                  case Days:
                    QL_REQUIRE(p.length()==0,
                               "impossible addition between " << *this <<
                               " and " << p);
                    break;
                  default:
                    QL_FAIL("unknown time unit (" << Integer(p.units()) << ")");
                }
                break;
              case Months:
                switch (p.units()) {
                  case Years:
                    length_ += p.length()*12;
                    break;
                  case Weeks:
                  case Days:
                    QL_REQUIRE(p.length()==0,
                               "impossible addition between " << *this <<
                               " and " << p);
                    break;
                  default:
                    QL_FAIL("unknown time unit (" << Integer(p.units()) << ")");
                }
                break;
              case Weeks:
                switch (p.units()) {
                  case Days:
                    units_ = Days;
                    length_ = length_*7 + p.length();
                    break;
                  case Years:
                  case Months:
                    QL_REQUIRE(p.length()==0,
                               "impossible addition between " << *this <<
                               " and " << p);
                    break;
                  default:
                    QL_FAIL("unknown time unit (" << Integer(p.units()) << ")");
                }
                break;
              case Days:
                switch (p.units()) {
                  case Weeks:
                    length_ += p.length()*7;
                    break;
                  case Years:
                  case Months:
                    QL_REQUIRE(p.length()==0,
                               "impossible addition between " << *this <<
                               " and " << p);
                    break;
                  default:
                    QL_FAIL("unknown time unit (" << Integer(p.units()) << ")");
                }
                break;
              default:
                QL_FAIL("unknown time unit (" << Integer(units_) << ")");
            }
        }
        //this->normalize();
        return *this;
    }
Period & QuantLib::Period::operator-= (const Period & p)
Definition at line 216 of file period.cpp.
References operator+=().
{
        return operator+=(-p);
    }
Period & QuantLib::Period::operator/= (Integer n)
Definition at line 220 of file period.cpp.
References QuantLib::Days, length(), length_, QuantLib::Months, QL_REQUIRE, units(), units_, QuantLib::Weeks, and QuantLib::Years.
{
        QL_REQUIRE(n != 0, "cannot be divided by zero");
        if (length_ % n == 0) {
            // keep the original units. If the user created a
            // 24-months period, he'll probably want a 12-months one
            // when he halves it.
            length_ /= n;
        } else {
            // try
            TimeUnit units = units_;
            Integer length = length_;
            switch (units) {
              case Years:
                length *= 12;
                units = Months;
                break;
              case Weeks:
                length *= 7;
                units = Days;
                break;
              default:
                ;
            }
            QL_REQUIRE(length % n == 0,
                       *this << " cannot be divided by " << n);
            length_ = length/n;
            units_ = units;
            // if normalization were possible, we wouldn't be
            // here---the "if" branch would have been executed
            // instead.
            // result.normalize();
        }
        return *this;
    }
TimeUnit QuantLib::Period::units () const [inline]
Definition at line 52 of file period.hpp.
References units_.
Referenced by QuantLib::Calendar::advance(), QuantLib::days(), QuantLib::anonymous_namespace{amortizingfixedratebond.cpp}::daysMinMax(), QuantLib::anonymous_namespace{period.cpp}::daysMinMax(), QuantLib::anonymous_namespace{euribor.cpp}::euriborConvention(), QuantLib::anonymous_namespace{euribor.cpp}::euriborEOM(), QuantLib::anonymous_namespace{eurlibor.cpp}::eurliborConvention(), QuantLib::anonymous_namespace{eurlibor.cpp}::eurliborEOM(), QuantLib::anonymous_namespace{libor.cpp}::liborConvention(), QuantLib::anonymous_namespace{libor.cpp}::liborEOM(), QuantLib::months(), QuantLib::operator*(), QuantLib::Date::operator+(), operator+=(), QuantLib::Date::operator+=(), QuantLib::Date::operator-(), QuantLib::operator-(), QuantLib::Date::operator-=(), operator/=(), QuantLib::operator<(), QuantLib::detail::operator<<(), QuantLib::MultiplicativePriceSeasonality::seasonalityFactor(), QuantLib::SwaptionVolatilityStructure::swapLength(), PeriodTest::testWeeksDaysAlgebra(), PeriodTest::testYearsMonthsAlgebra(), QuantLib::weeks(), and QuantLib::years().
{ return units_; }
Friends And Related Function Documentation
Real days (const Period &) [related]
Definition at line 326 of file period.cpp.
{
        if (p.length()==0) return 0.0;
        switch (p.units()) {
          case Days:
              return p.length();
          case Weeks:
              return p.length()*7.0;
          case Months:
            QL_FAIL("cannot convert Months into Days");
          case Years:
            QL_FAIL("cannot convert Years into Days");
          default:
            QL_FAIL("unknown time unit (" << Integer(p.units()) << ")");
        }
    }
Real months (const Period &) [related]
Definition at line 292 of file period.cpp.
{
        if (p.length()==0) return 0.0;
        switch (p.units()) {
          case Days:
            QL_FAIL("cannot convert Days into Months");
          case Weeks:
            QL_FAIL("cannot convert Weeks into Months");
          case Months:
              return p.length();
          case Years:
              return p.length()*12.0;
          default:
            QL_FAIL("unknown time unit (" << Integer(p.units()) << ")");
        }
    }
bool operator!= (const Period & , const Period &) [related]
Definition at line 165 of file period.hpp.
{
        return !(p1 == p2);
    }
template<typename T > Period operator* (T n, TimeUnit units) [related]
Definition at line 140 of file period.hpp.
{
        return Period(Integer(n),units);
    }
template<typename T > Period operator* (TimeUnit units, T n) [related]
Definition at line 145 of file period.hpp.
{
        return Period(Integer(n),units);
    }
Period operator* (Integer n, const Period &) [related]
Definition at line 153 of file period.hpp.
{
        return Period(n*p.length(),p.units());
    }
Period operator* (const Period & , Integer n) [related]
Definition at line 157 of file period.hpp.
{
        return Period(n*p.length(),p.units());
    }
Period operator+ (const Period & , const Period &) [related]
Definition at line 376 of file period.cpp.
{
        Period result = p1;
        result += p2;
        return result;
    }
Period operator- (const Period &) [related]
Definition at line 149 of file period.hpp.
{
        return Period(-p.length(),p.units());
    }
Period operator- (const Period & , const Period &) [related]
Definition at line 382 of file period.cpp.
{
        return p1+(-p2);
    }
Period operator/ (const Period & , Integer n) [related]
Definition at line 386 of file period.cpp.
{
        Period result = p;
        result /= n;
        return result;
    }
bool operator< (const Period & , const Period &) [related]
Definition at line 343 of file period.cpp.
{
        // special cases
        if (p1.length() == 0)
            return p2.length() > 0;
        if (p2.length() == 0)
            return p1.length() < 0;
        // exact comparisons
        if (p1.units() == p2.units())
            return p1.length() < p2.length();
        if (p1.units() == Months && p2.units() == Years)
            return p1.length() < 12*p2.length();
        if (p1.units() == Years && p2.units() == Months)
            return 12*p1.length() < p2.length();
        if (p1.units() == Days && p2.units() == Weeks)
            return p1.length() < 7*p2.length();
        if (p1.units() == Weeks && p2.units() == Days)
            return 7*p1.length() < p2.length();
        // inexact comparisons (handled by converting to days and using limits)
        std::pair<Integer, Integer> p1lim = daysMinMax(p1);
        std::pair<Integer, Integer> p2lim = daysMinMax(p2);
        if (p1lim.second < p2lim.first)
            return true;
        else if (p1lim.first > p2lim.second)
            return false;
        else
            QL_FAIL("undecidable comparison between " << p1 << " and " << p2);
    }
std::ostream & operator<< (std::ostream & , const Period &) [related]
Definition at line 394 of file period.cpp.
{
        return out << io::short_period(p);
    }
bool operator<= (const Period & , const Period &) [related]
Definition at line 173 of file period.hpp.
{
        return !(p1 > p2);
    }
bool operator== (const Period & , const Period &) [related]
Definition at line 161 of file period.hpp.
{
        return !(p1 < p2 || p2 < p1);
    }
bool operator> (const Period & , const Period &) [related]
Definition at line 169 of file period.hpp.
{
        return p2 < p1;
    }
bool operator>= (const Period & , const Period &) [related]
Definition at line 177 of file period.hpp.
{
        return !(p1 < p2);
    }
Real weeks (const Period &) [related]
Definition at line 309 of file period.cpp.
{
        if (p.length()==0) return 0.0;
        switch (p.units()) {
          case Days:
              return p.length()/7.0;
          case Weeks:
              return p.length();
          case Months:
            QL_FAIL("cannot convert Months into Weeks");
          case Years:
            QL_FAIL("cannot convert Years into Weeks");
          default:
            QL_FAIL("unknown time unit (" << Integer(p.units()) << ")");
        }
    }
Real years (const Period &) [related]
Definition at line 275 of file period.cpp.
{
        if (p.length()==0) return 0.0;
        switch (p.units()) {
          case Days:
            QL_FAIL("cannot convert Days into Years");
          case Weeks:
            QL_FAIL("cannot convert Weeks into Years");
          case Months:
              return p.length()/12.0;
          case Years:
              return p.length();
          default:
            QL_FAIL("unknown time unit (" << Integer(p.units()) << ")");
        }
    }
Member Data Documentation
Integer QuantLib::Period::length_ [private]
Definition at line 59 of file period.hpp.
Referenced by frequency(), length(), normalize(), operator+=(), operator/=(), and Period().
TimeUnit QuantLib::Period::units_ [private]
Definition at line 60 of file period.hpp.
Referenced by frequency(), normalize(), operator+=(), operator/=(), Period(), and units().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/time/period.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/time/period.cpp