QuantLib: QuantLib::AnalyticAmericanMargrabeEngine Class Reference
QuantLib::AnalyticAmericanMargrabeEngine Class Reference
Analytic engine for American Margrabe option.
#include <analyticamericanmargrabeengine.hpp>
Public Member Functions
AnalyticAmericanMargrabeEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > &process1, const boost::shared_ptr< GeneralizedBlackScholesProcess > &process2, Real correlation)
void calculate () const
Private Attributes
boost::shared_ptr
< GeneralizedBlackScholesProcess > process1_
boost::shared_ptr
< GeneralizedBlackScholesProcess > process2_
Real rho_
Detailed Description
Analytic engine for American Margrabe option.
This class implements formulae from "The Value of an American Option to Exchange One Asset for Another", W. Margrabe, Journal of Finance, 33, 177-86.
Test:
the correctness of the returned value is tested by reproducing results available in literature.
Definition at line 41 of file analyticamericanmargrabeengine.hpp.
Constructor & Destructor Documentation
QuantLib::AnalyticAmericanMargrabeEngine::AnalyticAmericanMargrabeEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > & process1, const boost::shared_ptr< GeneralizedBlackScholesProcess > & process2, Real correlation)
Definition at line 30 of file analyticamericanmargrabeengine.cpp.
References process1_, process2_, and QuantLib::Observer::registerWith().
    : process1_(process1), process2_(process2), rho_(correlation) {
        registerWith(process1_);
        registerWith(process2_);
    }
Member Function Documentation
void QuantLib::AnalyticAmericanMargrabeEngine::calculate () const [virtual]
Implements QuantLib::PricingEngine.
Definition at line 39 of file analyticamericanmargrabeengine.cpp.
References QuantLib::Exercise::American, QuantLib::GenericEngine< MargrabeOption::arguments, MargrabeOption::results >::arguments_, QuantLib::Option::Call, QuantLib::Settings::evaluationDate(), QuantLib::Option::arguments::exercise, QuantLib::Singleton< Settings >::instance(), QuantLib::Instrument::NPV(), QuantLib::Option::arguments::payoff, process1_, process2_, QuantLib::MargrabeOption::arguments::Q1, QuantLib::MargrabeOption::arguments::Q2, QL_REQUIRE, QuantLib::GenericEngine< MargrabeOption::arguments, MargrabeOption::results >::results_, rho_, QuantLib::Instrument::setPricingEngine(), anonymous_namespace{quantlibbenchmark.cpp}::t, QuantLib::Instrument::results::value, QuantLib::io::volatility(), and QuantLib::DayCounter::yearFraction().
{
        QL_REQUIRE(arguments_.exercise->type() == Exercise::American,
                   "not an American option");
        boost::shared_ptr<AmericanExercise> exercise =
            boost::dynamic_pointer_cast<AmericanExercise>(arguments_.exercise);
        QL_REQUIRE(exercise, "not an American option");
        boost::shared_ptr<NullPayoff> payoff0 =
            boost::dynamic_pointer_cast<NullPayoff>(arguments_.payoff);
        QL_REQUIRE(payoff0, "not a null payoff");
        // The option can be priced as an American single-asset option
        // with an adjusted process and payoff.
        Date today = Settings::instance().evaluationDate();
        DayCounter rfdc  = process1_->riskFreeRate()->dayCounter();
        Time t = rfdc.yearFraction(process1_->riskFreeRate()->referenceDate(),
                                   arguments_.exercise->lastDate());
        Real s1 = process1_->stateVariable()->value();
        Real s2 = process2_->stateVariable()->value();
        boost::shared_ptr<SimpleQuote> spot(new SimpleQuote(arguments_.Q1*s1));
        boost::shared_ptr<StrikedTypePayoff> payoff(
                      new PlainVanillaPayoff(Option::Call, arguments_.Q2*s2));
        DiscountFactor dividendDiscount1 =
            process1_->dividendYield()->discount(exercise->lastDate());
        Rate q1 = -std::log(dividendDiscount1)/t;
        DiscountFactor dividendDiscount2 =
            process2_->dividendYield()->discount(exercise->lastDate());
        Rate q2 = -std::log(dividendDiscount2)/t;
        boost::shared_ptr<YieldTermStructure> qTS(
                                            new FlatForward(today, q1, rfdc));
        boost::shared_ptr<YieldTermStructure> rTS(
                                            new FlatForward(today, q2, rfdc));
        Real variance1 = process1_->blackVolatility()->blackVariance(
                                                exercise->lastDate(), s1);
        Real variance2 = process2_->blackVolatility()->blackVariance(
                                                exercise->lastDate(), s2);
        Real variance = variance1 + variance2
                      - 2*rho_*std::sqrt(variance1)*std::sqrt(variance2);
        Volatility volatility = std::sqrt(variance/t);
        boost::shared_ptr<BlackVolTermStructure> volTS(
               new BlackConstantVol(today, NullCalendar(), volatility, rfdc));
        boost::shared_ptr<BlackScholesMertonProcess> stochProcess(new
            BlackScholesMertonProcess(Handle<Quote>(spot),
                                      Handle<YieldTermStructure>(qTS),
                                      Handle<YieldTermStructure>(rTS),
                                      Handle<BlackVolTermStructure>(volTS)));
        boost::shared_ptr<PricingEngine> engine(
                     new BjerksundStenslandApproximationEngine(stochProcess));
        VanillaOption option(payoff, exercise);
        option.setPricingEngine(engine);
        results_.value = option.NPV();
    }
Member Data Documentation
boost::shared_ptr<GeneralizedBlackScholesProcess> QuantLib::AnalyticAmericanMargrabeEngine::process1_ [private]
Definition at line 49 of file analyticamericanmargrabeengine.hpp.
Referenced by AnalyticAmericanMargrabeEngine(), and calculate().
boost::shared_ptr<GeneralizedBlackScholesProcess> QuantLib::AnalyticAmericanMargrabeEngine::process2_ [private]
Definition at line 50 of file analyticamericanmargrabeengine.hpp.
Referenced by AnalyticAmericanMargrabeEngine(), and calculate().
Real QuantLib::AnalyticAmericanMargrabeEngine::rho_ [private]
Definition at line 51 of file analyticamericanmargrabeengine.hpp.
Referenced by calculate().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/exoticoptions/analyticamericanmargrabeengine.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/exoticoptions/analyticamericanmargrabeengine.cpp