QuantLib: QuantLib::YoYCapFloorTermPriceSurface Class Reference
QuantLib::YoYCapFloorTermPriceSurface Class Reference
Abstract base class, inheriting from InflationTermStructure.
#include <yoycapfloortermpricesurface.hpp>
Public Member Functions
YoYCapFloorTermPriceSurface (Natural fixingDays, const Period &yyLag, const boost::shared_ptr< YoYInflationIndex > &yii, Rate baseRate, const Handle< YieldTermStructure > &nominal, const DayCounter &dc, const Calendar &cal, const BusinessDayConvention &bdc, const std::vector< Rate > &cStrikes, const std::vector< Rate > &fStrikes, const std::vector< Period > &cfMaturities, const Matrix &cPrice, const Matrix &fPrice)
virtual std::pair< std::vector
< Time >, std::vector< Rate > > atmYoYSwapTimeRates () const =0
atm yoy swaps from put-call parity on cap/floor data
virtual std::pair< std::vector
< Date >, std::vector< Rate > > atmYoYSwapDateRates () const =0
virtual boost::shared_ptr
< YoYInflationTermStructure > YoYTS () const =0
derived from yoy swap rates
boost::shared_ptr
< YoYInflationIndex > yoyIndex () const
index yoy is based on
virtual Date yoyOptionDateFromTenor (const Period &p) const
virtual BusinessDayConvention businessDayConvention () const
inspectors
virtual Natural fixingDays () const
virtual Real price (const Date &d, const Rate k) const =0
virtual Real capPrice (const Date &d, const Rate k) const =0
virtual Real floorPrice (const Date &d, const Rate k) const =0
virtual Rate atmYoYSwapRate (const Date &d, bool extrapolate=true) const =0
virtual Rate atmYoYRate (const Date &d, const Period &obsLag=Period(-1, Days), bool extrapolate=true) const =0
virtual Real price (const Period &d, const Rate k) const
virtual Real capPrice (const Period &d, const Rate k) const
virtual Real floorPrice (const Period &d, const Rate k) const
virtual Rate atmYoYSwapRate (const Period &d, bool extrapolate=true) const
virtual Rate atmYoYRate (const Period &d, const Period &obsLag=Period(-1, Days), bool extrapolate=true) const
virtual std::vector< Rate > strikes () const
virtual std::vector< Rate > capStrikes () const
virtual std::vector< Rate > floorStrikes () const
virtual std::vector< Period > maturities () const
virtual Rate minStrike () const
virtual Rate maxStrike () const
virtual Date minMaturity () const
virtual Date maxMaturity () const
Protected Member Functions
virtual bool checkStrike (Rate K)
virtual bool checkMaturity (const Date &d)
Protected Attributes
Natural fixingDays_
BusinessDayConvention bdc_
boost::shared_ptr
< YoYInflationIndex > yoyIndex_
std::vector< Rate > cStrikes_
std::vector< Rate > fStrikes_
std::vector< Period > cfMaturities_
std::vector< Real > cfMaturityTimes_
Matrix cPrice_
Matrix fPrice_
std::vector< Rate > cfStrikes_
boost::shared_ptr
< YoYInflationTermStructure > yoy_
std::pair< std::vector< Time >
, std::vector< Rate > > atmYoYSwapTimeRates_
std::pair< std::vector< Date >
, std::vector< Rate > > atmYoYSwapDateRates_
Detailed Description
Abstract base class, inheriting from InflationTermStructure.
Since this can create a yoy term structure it does take a YoY index.
Todo:
deal with index interpolation.
Definition at line 41 of file yoycapfloortermpricesurface.hpp.
Constructor & Destructor Documentation
QuantLib::YoYCapFloorTermPriceSurface::YoYCapFloorTermPriceSurface (Natural fixingDays, const Period & yyLag, const boost::shared_ptr< YoYInflationIndex > & yii, Rate baseRate, const Handle< YieldTermStructure > & nominal, const DayCounter & dc, const Calendar & cal, const BusinessDayConvention & bdc, const std::vector< Rate > & cStrikes, const std::vector< Rate > & fStrikes, const std::vector< Period > & cfMaturities, const Matrix & cPrice, const Matrix & fPrice)
Definition at line 25 of file yoycapfloortermpricesurface.cpp.
References cfMaturities_, cfStrikes_, QuantLib::Matrix::columns(), cPrice_, cStrikes_, QuantLib::Days, fPrice_, fStrikes_, QL_REQUIRE, and QuantLib::Matrix::rows().
    : InflationTermStructure(0, cal, baseRate, lag, yii->frequency(), yii->interpolated(), nominal, dc),
      fixingDays_(fixingDays), bdc_(bdc), yoyIndex_(yii),
      cStrikes_(cStrikes), fStrikes_(fStrikes),
      cfMaturities_(cfMaturities), cPrice_(cPrice), fPrice_(fPrice) {
        // data consistency checking, enough data?
        QL_REQUIRE(fStrikes_.size() > 1, "not enough floor strikes");
        QL_REQUIRE(cStrikes_.size() > 1, "not enough cap strikes");
        QL_REQUIRE(cfMaturities_.size() > 1, "not enough maturities");
        QL_REQUIRE(fStrikes_.size() == fPrice.rows(),
                   "floor strikes vs floor price rows not equal");
        QL_REQUIRE(cStrikes_.size() == cPrice.rows(),
                   "cap strikes vs cap price rows not equal");
        QL_REQUIRE(cfMaturities_.size() == fPrice.columns(),
                   "maturities vs floor price columns not equal");
        QL_REQUIRE(cfMaturities_.size() == cPrice.columns(),
                   "maturities vs cap price columns not equal");
        // data has correct properties (positive, monotonic)?
        for(Size j = 0; j <cfMaturities_.size(); j++) {
            QL_REQUIRE( cfMaturities[j] > Period(0,Days), "non-positive maturities");
            if(j>0) {
                QL_REQUIRE( cfMaturities[j] > cfMaturities[j-1],
                            "non-increasing maturities");
            }
            for(Size i = 0; i <fPrice_.rows(); i++) {
                QL_REQUIRE( fPrice_[i][j] > 0.0,
                            "non-positive floor price: " << fPrice_[i][j] );
                if(i>0) {
                    QL_REQUIRE( fPrice_[i][j] >= fPrice_[i-1][j],
                                "non-increasing floor prices");
                }
            }
            for(Size i = 0; i <cPrice_.rows(); i++) {
                QL_REQUIRE( cPrice_[i][j] > 0.0,
                            "non-positive cap price: " << cPrice_[i][j] );
                if(i>0) {
                    QL_REQUIRE( cPrice_[i][j] <= cPrice_[i-1][j],
                                "non-decreasing cap prices");
                }
            }
        }
        // Get the set of strikes, noting that repeats, overlaps are
        // expected between caps and floors but that no overlap in the
        // output is allowed so no repeats or overlaps are used
        cfStrikes_ = std::vector<Rate>();
        for(Size i = 0; i <fStrikes_.size(); i++)
            cfStrikes_.push_back( fStrikes[i] );
        Real eps = 0.0000001;
        Rate maxFstrike = fStrikes_.back();
        for(Size i = 0; i < cStrikes_.size(); i++) {
            Rate k = cStrikes[i];
            if (k > maxFstrike + eps) cfStrikes_.push_back(k);
        }
        // final consistency checking
        QL_REQUIRE(cfStrikes_.size() > 2, "overall not enough strikes");
        for (Size i = 1; i < cfStrikes_.size(); i++)
            QL_REQUIRE( cfStrikes_[i] > cfStrikes_[i-1],
                        "cfStrikes not increasing");
    }
Member Function Documentation
virtual Rate QuantLib::YoYCapFloorTermPriceSurface::atmYoYRate (const Date & d, const Period & obsLag = Period(-1, Days), bool extrapolate = true) const [pure virtual]
Implemented in QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >.
Referenced by atmYoYRate().
Rate QuantLib::YoYCapFloorTermPriceSurface::atmYoYRate (const Period & d, const Period & obsLag = Period(-1,Days), bool extrapolate = true) const [virtual]
Definition at line 124 of file yoycapfloortermpricesurface.cpp.
References atmYoYRate(), and yoyOptionDateFromTenor().
{
        return atmYoYRate(yoyOptionDateFromTenor(d), obsLag, extrapolate);
    }
virtual std::pair<std::vector<Date>, std::vector<Rate> > QuantLib::YoYCapFloorTermPriceSurface::atmYoYSwapDateRates () const [pure virtual]
Implemented in QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >.
virtual Rate QuantLib::YoYCapFloorTermPriceSurface::atmYoYSwapRate (const Date & d, bool extrapolate = true) const [pure virtual]
Implemented in QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >.
Referenced by atmYoYSwapRate().
Rate QuantLib::YoYCapFloorTermPriceSurface::atmYoYSwapRate (const Period & d, bool extrapolate = true) const [virtual]
Definition at line 119 of file yoycapfloortermpricesurface.cpp.
References atmYoYSwapRate(), and yoyOptionDateFromTenor().
{
        return atmYoYSwapRate(yoyOptionDateFromTenor(d), extrapolate);
    }
virtual std::pair<std::vector<Time>, std::vector<Rate> > QuantLib::YoYCapFloorTermPriceSurface::atmYoYSwapTimeRates () const [pure virtual]
atm yoy swaps from put-call parity on cap/floor data
uses interpolation (on surface price data), yearly maturities.
Implemented in QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >.
virtual BusinessDayConvention QuantLib::YoYCapFloorTermPriceSurface::businessDayConvention () const [inline, virtual]
inspectors
Note:
you don't know if price() is a cap or a floor without checking the YoYSwapATM level.
atm cap/floor prices are generally inaccurate because they are from extrapolation and intersection.
Definition at line 83 of file yoycapfloortermpricesurface.hpp.
References bdc_.
{return bdc_;}
virtual Real QuantLib::YoYCapFloorTermPriceSurface::capPrice (const Date & d, const Rate k) const [pure virtual]
Implemented in QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >.
Referenced by capPrice().
Real QuantLib::YoYCapFloorTermPriceSurface::capPrice (const Period & d, const Rate k) const [virtual]
Definition at line 111 of file yoycapfloortermpricesurface.cpp.
References capPrice(), and yoyOptionDateFromTenor().
{
        return capPrice(yoyOptionDateFromTenor(d), k);
    }
virtual std::vector<Rate> QuantLib::YoYCapFloorTermPriceSurface::capStrikes () const [inline, virtual]
Definition at line 104 of file yoycapfloortermpricesurface.hpp.
References cStrikes_.
{return cStrikes_;}
virtual bool QuantLib::YoYCapFloorTermPriceSurface::checkMaturity (const Date & d) [inline, protected, virtual]
Definition at line 119 of file yoycapfloortermpricesurface.hpp.
References maxMaturity(), and minMaturity().
{
            return ( minMaturity() <= d && d <= maxMaturity() );
        }
virtual bool QuantLib::YoYCapFloorTermPriceSurface::checkStrike (Rate K) [inline, protected, virtual]
Definition at line 116 of file yoycapfloortermpricesurface.hpp.
References maxStrike(), and minStrike().
{
            return ( minStrike() <= K && K <= maxStrike() );
        }
virtual Natural QuantLib::YoYCapFloorTermPriceSurface::fixingDays () const [inline, virtual]
Reimplemented in QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >.
Definition at line 84 of file yoycapfloortermpricesurface.hpp.
References fixingDays_.
{return fixingDays_;}
virtual Real QuantLib::YoYCapFloorTermPriceSurface::floorPrice (const Date & d, const Rate k) const [pure virtual]
Implemented in QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >.
Referenced by floorPrice().
Real QuantLib::YoYCapFloorTermPriceSurface::floorPrice (const Period & d, const Rate k) const [virtual]
Definition at line 115 of file yoycapfloortermpricesurface.cpp.
References floorPrice(), and yoyOptionDateFromTenor().
{
        return floorPrice(yoyOptionDateFromTenor(d), k);
    }
virtual std::vector<Rate> QuantLib::YoYCapFloorTermPriceSurface::floorStrikes () const [inline, virtual]
Definition at line 105 of file yoycapfloortermpricesurface.hpp.
References fStrikes_.
{return fStrikes_;}
virtual std::vector<Period> QuantLib::YoYCapFloorTermPriceSurface::maturities () const [inline, virtual]
Definition at line 106 of file yoycapfloortermpricesurface.hpp.
References cfMaturities_.
{return cfMaturities_;}
virtual Date QuantLib::YoYCapFloorTermPriceSurface::maxMaturity () const [inline, virtual]
Definition at line 110 of file yoycapfloortermpricesurface.hpp.
References cfMaturities_, and QuantLib::TermStructure::referenceDate().
Referenced by checkMaturity().
{return referenceDate()+cfMaturities_.back();}
virtual Rate QuantLib::YoYCapFloorTermPriceSurface::maxStrike () const [inline, virtual]
Definition at line 108 of file yoycapfloortermpricesurface.hpp.
References cfStrikes_.
Referenced by checkStrike().
{return cfStrikes_.back();};
virtual Date QuantLib::YoYCapFloorTermPriceSurface::minMaturity () const [inline, virtual]
Definition at line 109 of file yoycapfloortermpricesurface.hpp.
References cfMaturities_, and QuantLib::TermStructure::referenceDate().
Referenced by checkMaturity().
{return referenceDate()+cfMaturities_.front();}// \TODO deal with index interpolation
virtual Rate QuantLib::YoYCapFloorTermPriceSurface::minStrike () const [inline, virtual]
Definition at line 107 of file yoycapfloortermpricesurface.hpp.
References cfStrikes_.
Referenced by checkStrike().
{return cfStrikes_.front();};
virtual Real QuantLib::YoYCapFloorTermPriceSurface::price (const Date & d, const Rate k) const [pure virtual]
Implemented in QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >.
Referenced by price().
Real QuantLib::YoYCapFloorTermPriceSurface::price (const Period & d, const Rate k) const [virtual]
Definition at line 107 of file yoycapfloortermpricesurface.cpp.
References price(), and yoyOptionDateFromTenor().
{
        return price(yoyOptionDateFromTenor(d), k);
    }
virtual std::vector<Rate> QuantLib::YoYCapFloorTermPriceSurface::strikes () const [inline, virtual]
Definition at line 103 of file yoycapfloortermpricesurface.hpp.
References cfStrikes_.
{return cfStrikes_;}
boost::shared_ptr<YoYInflationIndex> QuantLib::YoYCapFloorTermPriceSurface::yoyIndex () const [inline]
index yoy is based on
Definition at line 73 of file yoycapfloortermpricesurface.hpp.
References yoyIndex_.
Referenced by QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::calculateYoYTermStructure().
{ return yoyIndex_; }
Date QuantLib::YoYCapFloorTermPriceSurface::yoyOptionDateFromTenor (const Period & p) const [virtual]
Definition at line 102 of file yoycapfloortermpricesurface.cpp.
References QuantLib::TermStructure::referenceDate().
Referenced by atmYoYRate(), atmYoYSwapRate(), QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::calculateYoYTermStructure(), capPrice(), floorPrice(), QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::intersect(), and price().
    {
        return Date(referenceDate()+p);
    }
virtual boost::shared_ptr<YoYInflationTermStructure> QuantLib::YoYCapFloorTermPriceSurface::YoYTS () const [pure virtual]
derived from yoy swap rates
Implemented in QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >.
Member Data Documentation
std::pair<std::vector<Date>, std::vector<Rate> > QuantLib::YoYCapFloorTermPriceSurface::atmYoYSwapDateRates_ [mutable, protected]
Definition at line 141 of file yoycapfloortermpricesurface.hpp.
Referenced by QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::atmYoYSwapDateRates(), and QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::intersect().
std::pair<std::vector<Time>, std::vector<Rate> > QuantLib::YoYCapFloorTermPriceSurface::atmYoYSwapTimeRates_ [mutable, protected]
Definition at line 140 of file yoycapfloortermpricesurface.hpp.
Referenced by QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::atmYoYSwapTimeRates(), and QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::intersect().
BusinessDayConvention QuantLib::YoYCapFloorTermPriceSurface::bdc_ [protected]
Definition at line 128 of file yoycapfloortermpricesurface.hpp.
Referenced by businessDayConvention(), and QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::calculateYoYTermStructure().
std::vector<Period> QuantLib::YoYCapFloorTermPriceSurface::cfMaturities_ [protected]
Definition at line 133 of file yoycapfloortermpricesurface.hpp.
Referenced by QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::calculateYoYTermStructure(), QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::intersect(), maturities(), maxMaturity(), minMaturity(), and YoYCapFloorTermPriceSurface().
std::vector<Real> QuantLib::YoYCapFloorTermPriceSurface::cfMaturityTimes_ [mutable, protected]
Definition at line 134 of file yoycapfloortermpricesurface.hpp.
Referenced by QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::intersect().
std::vector<Rate> QuantLib::YoYCapFloorTermPriceSurface::cfStrikes_ [mutable, protected]
Definition at line 138 of file yoycapfloortermpricesurface.hpp.
Referenced by maxStrike(), minStrike(), strikes(), and YoYCapFloorTermPriceSurface().
Matrix QuantLib::YoYCapFloorTermPriceSurface::cPrice_ [protected]
Definition at line 135 of file yoycapfloortermpricesurface.hpp.
Referenced by QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::intersect(), and YoYCapFloorTermPriceSurface().
std::vector<Rate> QuantLib::YoYCapFloorTermPriceSurface::cStrikes_ [protected]
Definition at line 131 of file yoycapfloortermpricesurface.hpp.
Referenced by capStrikes(), QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::intersect(), and YoYCapFloorTermPriceSurface().
Natural QuantLib::YoYCapFloorTermPriceSurface::fixingDays_ [protected]
Definition at line 127 of file yoycapfloortermpricesurface.hpp.
Referenced by fixingDays(), and QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::fixingDays().
Matrix QuantLib::YoYCapFloorTermPriceSurface::fPrice_ [protected]
Definition at line 136 of file yoycapfloortermpricesurface.hpp.
Referenced by QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::intersect(), and YoYCapFloorTermPriceSurface().
std::vector<Rate> QuantLib::YoYCapFloorTermPriceSurface::fStrikes_ [protected]
Definition at line 132 of file yoycapfloortermpricesurface.hpp.
Referenced by floorStrikes(), QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::intersect(), and YoYCapFloorTermPriceSurface().
boost::shared_ptr<YoYInflationTermStructure> QuantLib::YoYCapFloorTermPriceSurface::yoy_ [mutable, protected]
Definition at line 139 of file yoycapfloortermpricesurface.hpp.
Referenced by QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::atmYoYRate(), QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::baseDate(), QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::calculateYoYTermStructure(), QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::maxDate(), and QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::YoYTS().
boost::shared_ptr<YoYInflationIndex> QuantLib::YoYCapFloorTermPriceSurface::yoyIndex_ [protected]
Definition at line 129 of file yoycapfloortermpricesurface.hpp.
Referenced by yoyIndex().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/inflation/yoycapfloortermpricesurface.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/inflation/yoycapfloortermpricesurface.cpp