QuantLib: QuantLib::OvernightLeg Class Reference
QuantLib::OvernightLeg Class Reference
helper class building a sequence of overnight coupons
#include <overnightindexedcoupon.hpp>
Public Member Functions
OvernightLeg (const Schedule &schedule, const boost::shared_ptr< OvernightIndex > &overnightIndex)
OvernightLeg & withNotionals (Real notional)
OvernightLeg & withNotionals (const std::vector< Real > &notionals)
OvernightLeg & withPaymentDayCounter (const DayCounter &)
OvernightLeg & withPaymentAdjustment (BusinessDayConvention)
OvernightLeg & withGearings (Real gearing)
OvernightLeg & withGearings (const std::vector< Real > &gearings)
OvernightLeg & withSpreads (Spread spread)
OvernightLeg & withSpreads (const std::vector< Spread > &spreads)
operator Leg () const
Private Attributes
Schedule schedule_
boost::shared_ptr< OvernightIndex > overnightIndex_
std::vector< Real > notionals_
DayCounter paymentDayCounter_
BusinessDayConvention paymentAdjustment_
std::vector< Real > gearings_
std::vector< Spread > spreads_
Detailed Description
helper class building a sequence of overnight coupons
Definition at line 78 of file overnightindexedcoupon.hpp.
Constructor & Destructor Documentation
QuantLib::OvernightLeg::OvernightLeg (const Schedule & schedule, const boost::shared_ptr< OvernightIndex > & overnightIndex)
Definition at line 180 of file overnightindexedcoupon.cpp.
    : schedule_(schedule), overnightIndex_(i), paymentAdjustment_(Following) {}
Member Function Documentation
QuantLib::OvernightLeg::operator Leg () const
Definition at line 225 of file overnightindexedcoupon.cpp.
References QuantLib::Calendar::adjust(), QuantLib::Schedule::calendar(), anonymous_namespace{marketmodel.cpp}::calendar, QuantLib::Schedule::date(), gearings_, QuantLib::detail::get(), QuantLib::Schedule::isRegular(), notionals_, overnightIndex_, paymentAdjustment_, paymentDayCounter_, QL_REQUIRE, schedule_, QuantLib::Schedule::size(), spreads_, and QuantLib::Schedule::tenor().
{
        QL_REQUIRE(!notionals_.empty(), "no notional given");
        Leg cashflows;
        // the following is not always correct
        Calendar calendar = schedule_.calendar();
        Date refStart, start, refEnd, end;
        Date paymentDate;
        Size n = schedule_.size()-1;
        for (Size i=0; i<n; ++i) {
            refStart = start = schedule_.date(i);
            refEnd   =   end = schedule_.date(i+1);
            paymentDate = calendar.adjust(end, paymentAdjustment_);
            if (i == 0 && !schedule_.isRegular(i+1))
                refStart = calendar.adjust(end - schedule_.tenor(),
                                           paymentAdjustment_);
            if (i == n-1 && !schedule_.isRegular(i+1))
                refEnd = calendar.adjust(start + schedule_.tenor(),
                                         paymentAdjustment_);
            cashflows.push_back(shared_ptr<CashFlow>(new
                OvernightIndexedCoupon(paymentDate,
                                       detail::get(notionals_, i,
                                                   notionals_.back()),
                                       start, end,
                                       overnightIndex_,
                                       detail::get(gearings_, i, 1.0),
                                       detail::get(spreads_, i, 0.0),
                                       refStart, refEnd,
                                       paymentDayCounter_)));
        }
        return cashflows;
    }
OvernightLeg & QuantLib::OvernightLeg::withGearings (Real gearing)
Definition at line 205 of file overnightindexedcoupon.cpp.
References gearings_.
{
        gearings_ = vector<Real>(1,gearing);
        return *this;
    }
OvernightLeg & QuantLib::OvernightLeg::withGearings (const std::vector< Real > & gearings)
Definition at line 210 of file overnightindexedcoupon.cpp.
References gearings_.
{
        gearings_ = gearings;
        return *this;
    }
OvernightLeg & QuantLib::OvernightLeg::withNotionals (Real notional)
Definition at line 184 of file overnightindexedcoupon.cpp.
References notionals_.
Referenced by QuantLib::OvernightIndexedSwap::initialize().
{
        notionals_ = vector<Real>(1, notional);
        return *this;
    }
OvernightLeg & QuantLib::OvernightLeg::withNotionals (const std::vector< Real > & notionals)
Definition at line 189 of file overnightindexedcoupon.cpp.
References notionals_.
{
        notionals_ = notionals;
        return *this;
    }
OvernightLeg & QuantLib::OvernightLeg::withPaymentAdjustment (BusinessDayConvention convention)
Definition at line 200 of file overnightindexedcoupon.cpp.
References paymentAdjustment_.
{
        paymentAdjustment_ = convention;
        return *this;
    }
OvernightLeg & QuantLib::OvernightLeg::withPaymentDayCounter (const DayCounter & dc)
Definition at line 194 of file overnightindexedcoupon.cpp.
References paymentDayCounter_.
{
        paymentDayCounter_ = dc;
        return *this;
    }
OvernightLeg & QuantLib::OvernightLeg::withSpreads (Spread spread)
Definition at line 215 of file overnightindexedcoupon.cpp.
References spreads_.
Referenced by QuantLib::OvernightIndexedSwap::initialize().
{
        spreads_ = vector<Spread>(1,spread);
        return *this;
    }
OvernightLeg & QuantLib::OvernightLeg::withSpreads (const std::vector< Spread > & spreads)
Definition at line 220 of file overnightindexedcoupon.cpp.
References spreads_.
{
        spreads_ = spreads;
        return *this;
    }
Member Data Documentation
std::vector<Real> QuantLib::OvernightLeg::gearings_ [private]
Definition at line 97 of file overnightindexedcoupon.hpp.
Referenced by operator Leg(), and withGearings().
std::vector<Real> QuantLib::OvernightLeg::notionals_ [private]
Definition at line 94 of file overnightindexedcoupon.hpp.
Referenced by operator Leg(), and withNotionals().
boost::shared_ptr<OvernightIndex> QuantLib::OvernightLeg::overnightIndex_ [private]
Definition at line 93 of file overnightindexedcoupon.hpp.
Referenced by operator Leg().
BusinessDayConvention QuantLib::OvernightLeg::paymentAdjustment_ [private]
Definition at line 96 of file overnightindexedcoupon.hpp.
Referenced by operator Leg(), and withPaymentAdjustment().
DayCounter QuantLib::OvernightLeg::paymentDayCounter_ [private]
Definition at line 95 of file overnightindexedcoupon.hpp.
Referenced by operator Leg(), and withPaymentDayCounter().
Schedule QuantLib::OvernightLeg::schedule_ [private]
Definition at line 92 of file overnightindexedcoupon.hpp.
Referenced by operator Leg().
std::vector<Spread> QuantLib::OvernightLeg::spreads_ [private]
Definition at line 98 of file overnightindexedcoupon.hpp.
Referenced by operator Leg(), and withSpreads().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/overnightindexedcoupon.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/overnightindexedcoupon.cpp