QuantLib: QuantLib::ConstantEstimator Class Reference
QuantLib::ConstantEstimator Class Reference
Constant-estimator volatility model.
#include <constantestimator.hpp>
Public Member Functions
ConstantEstimator (Size size)
TimeSeries< Volatility > calculate (const TimeSeries< Volatility > &)
void calibrate (const TimeSeries< Volatility > &)
Private Attributes
Size size_
Detailed Description
Constant-estimator volatility model.
Volatilities are assumed to be expressed on an annual basis.
Definition at line 35 of file constantestimator.hpp.
Constructor & Destructor Documentation
QuantLib::ConstantEstimator::ConstantEstimator (Size size) [inline]
Definition at line 39 of file constantestimator.hpp.
        : size_(size) {}
Member Function Documentation
TimeSeries< Volatility > QuantLib::ConstantEstimator::calculate (const TimeSeries< Volatility > & volatilitySeries) [virtual]
Implements QuantLib::VolatilityCompositor.
Definition at line 24 of file constantestimator.cpp.
References QuantLib::TimeSeries< T, Container >::begin(), QuantLib::TimeSeries< T, Container >::size(), size_, and QuantLib::TimeSeries< T, Container >::values().
Referenced by VolatilityModelsTest::testConstruction().
{
        TimeSeries<Volatility> retval;
        const std::vector<Volatility> u = volatilitySeries.values();
        TimeSeries<Volatility>::const_iterator prev, next, cur, start;
        cur = volatilitySeries.begin();
        std::advance(cur, size_);
        // ICK.  This could probably be made a lot more efficient
        for (Size i=size_; i < volatilitySeries.size(); i++) {
            Size j;
            Real sumu2=0.0, sumu=0.0;
            for (j=i-size_; j <i; j++) {
                sumu += u[j];
                sumu2 += u[j]*u[j];
            }
            Real s = std::sqrt(sumu2/(Real)size_ - sumu*sumu / (Real) size_ /
                               (Real) (size_+1));
            retval[cur->first] = s;
            ++cur;
        }
        return retval;
    }
void QuantLib::ConstantEstimator::calibrate (const TimeSeries< Volatility > &) [inline, virtual]
Implements QuantLib::VolatilityCompositor.
Definition at line 42 of file constantestimator.hpp.
{}
Member Data Documentation
Size QuantLib::ConstantEstimator::size_ [private]
Definition at line 37 of file constantestimator.hpp.
Referenced by calculate().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/volatility/constantestimator.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/volatility/constantestimator.cpp