QuantLib: QuantLib::Thirty360::US_Impl Class Reference
QuantLib::Thirty360::US_Impl Class Reference
Public Member Functions
std::string name () const
BigInteger dayCount (const Date &d1, const Date &d2) const
to be overloaded by more complex day counters
Time yearFraction (const Date &d1, const Date &d2, const Date &, const Date &) const
Detailed Description
Definition at line 60 of file thirty360.hpp.
Member Function Documentation
BigInteger QuantLib::Thirty360::US_Impl::dayCount (const Date & d1, const Date & d2) const [virtual]
to be overloaded by more complex day counters
Reimplemented from QuantLib::DayCounter::Impl.
Definition at line 40 of file thirty360.cpp.
References QuantLib::Date::dayOfMonth(), QuantLib::Date::month(), and QuantLib::Date::year().
Referenced by yearFraction().
{
        Day dd1 = d1.dayOfMonth(), dd2 = d2.dayOfMonth();
        Integer mm1 = d1.month(), mm2 = d2.month();
        Year yy1 = d1.year(), yy2 = d2.year();
        if (dd2 == 31 && dd1 < 30) { dd2 = 1; mm2++; }
        return 360*(yy2-yy1) + 30*(mm2-mm1-1) +
            std::max(Integer(0),30-dd1) + std::min(Integer(30),dd2);
    }
std::string QuantLib::Thirty360::US_Impl::name () const [inline, virtual]
Implements QuantLib::DayCounter::Impl.
Definition at line 62 of file thirty360.hpp.
{ return std::string("30/360 (Bond Basis)");}
Time QuantLib::Thirty360::US_Impl::yearFraction (const Date & d1, const Date & d2, const Date & , const Date &) const [inline, virtual]
Implements QuantLib::DayCounter::Impl.
Definition at line 65 of file thirty360.hpp.
References dayCount().
{
                return dayCount(d1,d2)/360.0; }
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/time/daycounters/thirty360.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/time/daycounters/thirty360.cpp