QuantLib: QuantLib::OrthogonalizedBumpFinder Class Reference
QuantLib::OrthogonalizedBumpFinder Class Reference
#include <bumpinstrumentjacobian.hpp>
Public Member Functions
OrthogonalizedBumpFinder (const VegaBumpCollection &bumps, const std::vector< VolatilityBumpInstrumentJacobian::Swaption > &swaptions, const std::vector< VolatilityBumpInstrumentJacobian::Cap > &caps, Real multiplierCutOff, Real tolerance)
void GetVegaBumps (std::vector< std::vector< Matrix > > &theBumps) const
Private Attributes
VolatilityBumpInstrumentJacobian derivativesProducer_
Real multiplierCutOff_
Real tolerance_
Detailed Description
Pass in a market model, a list of instruments, and possible bumps.
Get out pseudo-root bumps that shift each implied vol by one percent, and leave the other instruments fixed.
If the contribution of an instrument is too correlated with other instruments used, discard it.
Definition at line 89 of file bumpinstrumentjacobian.hpp.
Constructor & Destructor Documentation
QuantLib::OrthogonalizedBumpFinder::OrthogonalizedBumpFinder (const VegaBumpCollection & bumps, const std::vector< VolatilityBumpInstrumentJacobian::Swaption > & swaptions, const std::vector< VolatilityBumpInstrumentJacobian::Cap > & caps, Real multiplierCutOff, Real tolerance)
Definition at line 142 of file bumpinstrumentjacobian.cpp.
                                                     :
                                                        derivativesProducer_(bumps,swaptions,caps),
                                                        multiplierCutOff_(multiplierCutOff),
                                                        tolerance_(tolerance)
    {
    }
Member Function Documentation
void QuantLib::OrthogonalizedBumpFinder::GetVegaBumps (std::vector< std::vector< Matrix > > & theBumps) const
Definition at line 156 of file bumpinstrumentjacobian.cpp.
References QuantLib::VegaBumpCollection::allBumps(), QuantLib::VegaBumpCollection::associatedModel(), derivativesProducer_, QuantLib::VolatilityBumpInstrumentJacobian::getAllOnePercentBumps(), QuantLib::VolatilityBumpInstrumentJacobian::getInputBumps(), multiplierCutOff_, QuantLib::EvolutionDescription::numberOfSteps(), QuantLib::io::rate(), and tolerance_.
Referenced by MarketModelTest::testPathwiseMarketVegas().
    {
        OrthogonalProjections projector(derivativesProducer_.getAllOnePercentBumps(),
                                                            multiplierCutOff_,
                                                             tolerance_  );
        Size numberRestrictedBumps(projector.numberValidVectors());
        boost::shared_ptr<MarketModel> marketmodel(derivativesProducer_.getInputBumps().associatedModel());
        const EvolutionDescription& evolution(marketmodel->evolution());
        Size numberSteps = evolution.numberOfSteps();
        Size numberRates = evolution.numberOfRates();
        Size factors = marketmodel->numberOfFactors();
        theBumps.resize(numberSteps);
       // recall that the bumps: We do the outermost vector by time step and inner one by which vega.
        for (Size i=0; i < theBumps.size(); ++i)
            theBumps[i].resize(numberRestrictedBumps);
        Matrix modelMatrix(numberRates, factors,0.0);
        for (Size i=0;  i< numberSteps; ++i)
            for (Size j=0; j < numberRestrictedBumps; ++j)
                theBumps[i][j] = modelMatrix;
        const std::vector<VegaBumpCluster>& bumpClusters(derivativesProducer_.getInputBumps().allBumps());
        Size bumpIndex =0;
        for (Size instrument=0; instrument < projector.validVectors().size(); ++instrument)
        {
            if (projector.validVectors()[instrument])
            {
                for (Size cluster =0; cluster< bumpClusters.size(); ++cluster)
                {
                    Real magnitude = projector.GetVector(instrument)[cluster];
                    for (Size step = bumpClusters[cluster].stepBegin(); step <  bumpClusters[cluster].stepEnd(); ++step)
                        for (Size rate = bumpClusters[cluster].rateBegin(); rate < bumpClusters[cluster].rateEnd(); ++rate)
                            for (Size factor = bumpClusters[cluster].factorBegin(); factor <  bumpClusters[cluster].factorEnd(); ++factor)
                                theBumps[step][bumpIndex][rate][factor] = magnitude;
                }
                ++bumpIndex;
            }
        }
    }
Member Data Documentation
VolatilityBumpInstrumentJacobian QuantLib::OrthogonalizedBumpFinder::derivativesProducer_ [private]
Definition at line 103 of file bumpinstrumentjacobian.hpp.
Referenced by GetVegaBumps().
Real QuantLib::OrthogonalizedBumpFinder::multiplierCutOff_ [private]
Definition at line 104 of file bumpinstrumentjacobian.hpp.
Referenced by GetVegaBumps().
Real QuantLib::OrthogonalizedBumpFinder::tolerance_ [private]
Definition at line 105 of file bumpinstrumentjacobian.hpp.
Referenced by GetVegaBumps().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/pathwisegreeks/bumpinstrumentjacobian.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/pathwisegreeks/bumpinstrumentjacobian.cpp