QuantLib: QuantLib::SyntheticCDO::engine Class Reference
QuantLib::SyntheticCDO::engine Class Reference
CDO base engine.
#include <syntheticcdoengines.hpp>
Protected Member Functions
virtual Real expectedTrancheLoss (const Date &) const =0
virtual void initialize () const
Protected Attributes
boost::shared_ptr< Basket > remainingBasket_
Detailed Description
CDO base engine.
Definition at line 40 of file syntheticcdoengines.hpp.
Member Function Documentation
virtual Real QuantLib::SyntheticCDO::engine::expectedTrancheLoss (const Date &) const [protected, pure virtual]
Implemented in QuantLib::MonteCarloCDOEngine2, QuantLib::MonteCarloCDOEngine1, QuantLib::IntegralCDOEngine, and QuantLib::MidPointCDOEngine.
Referenced by initialize().
virtual void QuantLib::SyntheticCDO::engine::initialize () const [inline, protected, virtual]
Reimplemented in QuantLib::MonteCarloCDOEngine1.
Definition at line 44 of file syntheticcdoengines.hpp.
References anonymous_namespace{marketmodel.cpp}::a, QuantLib::GenericEngine< SyntheticCDO::arguments, SyntheticCDO::results >::arguments_, QuantLib::SyntheticCDO::basket(), QuantLib::SyntheticCDO::arguments::basket, anonymous_namespace{marketmodel.cpp}::d, QuantLib::Schedule::dates(), anonymous_namespace{marketmodel.cpp}::dates, QuantLib::Settings::evaluationDate(), expectedTrancheLoss(), QuantLib::SyntheticCDO::results::expectedTrancheLoss, QuantLib::Singleton< Settings >::instance(), remainingBasket_, QuantLib::SyntheticCDO::results::remainingNotional, QuantLib::GenericEngine< SyntheticCDO::arguments, SyntheticCDO::results >::results_, QuantLib::SyntheticCDO::arguments::schedule, QuantLib::Schedule::startDate(), QuantLib::SyntheticCDO::results::xMax, and QuantLib::SyntheticCDO::results::xMin.
{
            Date today = Settings::instance().evaluationDate();
            Date start = this->arguments_.schedule.startDate();
            boost::shared_ptr<Basket>& basket = this->arguments_.basket;
            /*
              Remove defaulted names and adjust the subordination.
            */
            std::vector<std::string> names = basket->remainingNames(start, today);
            std::vector<Real> notionals
                = basket->remainingNotionals(start, today);
            Real a = basket->remainingAttachmentRatio(start, today);
            Real d = basket->remainingDetachmentRatio(start, today);
            const boost::shared_ptr<Pool> pool = basket->pool();
            remainingBasket_ =
                boost::shared_ptr<Basket>(new Basket(names, notionals, pool,
                                                    basket->remainingDefaultKeys(start, today),
                                                    basket->remainingRecModels(start, today),
                                                     a, d));
            this->results_.xMin = remainingBasket_->attachmentAmount();
            this->results_.xMax = remainingBasket_->detachmentAmount();
            this->results_.remainingNotional = results_.xMax - results_.xMin;
            const std::vector<Date>& dates = arguments_.schedule.dates();
            for (Size i = 0; i < dates.size(); i++) {
                if (dates[i] <= today)
                    results_.expectedTrancheLoss.push_back(0.0);
                else {
                    Real L = expectedTrancheLoss(dates[i]);
                    results_.expectedTrancheLoss.push_back(L);
                }
            }
        }
Member Data Documentation
boost::shared_ptr<Basket> QuantLib::SyntheticCDO::engine::remainingBasket_ [mutable, protected]
Definition at line 77 of file syntheticcdoengines.hpp.
Referenced by initialize(), and QuantLib::MonteCarloCDOEngine1::initialize().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/syntheticcdoengines.hpp