QuantLib: QuantLib::Settings Class Reference
QuantLib::Settings Class Reference
global repository for run-time library settings
#include <settings.hpp>
Classes
class DateProxy
Public Member Functions
DateProxy & evaluationDate ()
the date at which pricing is to be performed.
const DateProxy & evaluationDate () const
void anchorEvaluationDate ()
void resetEvaluationDate ()
bool & includeReferenceDateEvents ()
bool includeReferenceDateEvents () const
bool & includeReferenceDateCashFlows ()
bool includeReferenceDateCashFlows () const
boost::optional< bool > & includeTodaysCashFlows ()
boost::optional< bool > includeTodaysCashFlows () const
bool & enforcesTodaysHistoricFixings ()
bool enforcesTodaysHistoricFixings () const
Private Member Functions
Settings ()
Private Attributes
DateProxy evaluationDate_
bool includeReferenceDateEvents_
boost::optional< bool > includeTodaysCashFlows_
bool enforcesTodaysHistoricFixings_
Friends
class Singleton< Settings >
std::ostream & operator<< (std::ostream &, const DateProxy &)
Detailed Description
global repository for run-time library settings
Definition at line 37 of file settings.hpp.
Constructor & Destructor Documentation
QuantLib::Settings::Settings () [private]
Definition at line 34 of file settings.cpp.
    : includeReferenceDateEvents_(false),
      enforcesTodaysHistoricFixings_(false) {}
Member Function Documentation
void QuantLib::Settings::anchorEvaluationDate ()
Call this to prevent the evaluation date to change at midnight (and, incidentally, to gain quite a bit of performance.) If no evaluation date was previously set, it is equivalent to setting the evaluation date to Date::todaysDate(); if an evaluation date other than Date() was already set, it has no effect.
Definition at line 38 of file settings.cpp.
References evaluationDate_, QuantLib::Date::todaysDate(), and QuantLib::ObservableValue< T >::value().
{
        // set to today's date if not already set.
        if (evaluationDate_.value() == Date())
            evaluationDate_ = Date::todaysDate();
        // If set, no-op since the date is already anchored.
    }
bool & QuantLib::Settings::enforcesTodaysHistoricFixings () [inline]
Definition at line 177 of file settings.hpp.
References enforcesTodaysHistoricFixings_.
Referenced by QuantLib::historicalForwardRatesAnalysis(), QuantLib::DigitalCoupon::rate(), and QuantLib::SavedSettings::~SavedSettings().
{
        return enforcesTodaysHistoricFixings_;
    }
bool QuantLib::Settings::enforcesTodaysHistoricFixings () const [inline]
Definition at line 181 of file settings.hpp.
References enforcesTodaysHistoricFixings_.
{
        return enforcesTodaysHistoricFixings_;
    }
Settings::DateProxy & QuantLib::Settings::evaluationDate () [inline]
the date at which pricing is to be performed.
Client code can inspect the evaluation date, as in:
            Date d = Settings::instance().evaluationDate();
where today's date is returned if the evaluation date is set to the null date (its default value;) can set it to a new value, as in:
            Settings::instance().evaluationDate() = d;
and can register with it, as in:
            registerWith(Settings::instance().evaluationDate());
to be notified when it is set to a new value.
Warning:
a notification is not sent when the evaluation date changes for natural causes---i.e., a date was not explicitly set (which results in today's date being used for pricing) and the current date changes as the clock strikes midnight.
Definition at line 153 of file settings.hpp.
References evaluationDate_.
Referenced by QuantLib::CashFlows::atmRate(), QuantLib::CashFlows::basisPointValue(), QuantLib::CashFlows::bps(), QuantLib::AnalyticSimpleChooserEngine::calculate(), QuantLib::IntegralCdsEngine::calculate(), QuantLib::MidPointCdsEngine::calculate(), QuantLib::AnalyticAmericanMargrabeEngine::calculate(), QuantLib::HaganPricer::capletPrice(), anonymous_namespace{swaptionvolatilitymatrix.cpp}::CommonVars::CommonVars(), anonymous_namespace{digitalcoupon.cpp}::CommonVars::CommonVars(), anonymous_namespace{termstructures.cpp}::CommonVars::CommonVars(), anonymous_namespace{bonds.cpp}::CommonVars::CommonVars(), anonymous_namespace{capfloor.cpp}::CommonVars::CommonVars(), anonymous_namespace{cms.cpp}::CommonVars::CommonVars(), anonymous_namespace{capflooredcoupon.cpp}::CommonVars::CommonVars(), anonymous_namespace{curvestates.cpp}::CommonVars::CommonVars(), anonymous_namespace{convertiblebonds.cpp}::CommonVars::CommonVars(), anonymous_namespace{assetswap.cpp}::CommonVars::CommonVars(), anonymous_namespace{swap.cpp}::CommonVars::CommonVars(), anonymous_namespace{swaption.cpp}::CommonVars::CommonVars(), anonymous_namespace{inflationcapfloor.cpp}::CommonVars::CommonVars(), anonymous_namespace{inflationcpiswap.cpp}::CommonVars::CommonVars(), anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::CommonVars(), anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::CommonVars(), anonymous_namespace{piecewiseyieldcurve.cpp}::CommonVars::CommonVars(), anonymous_namespace{overnightindexedswap.cpp}::CommonVars::CommonVars(), anonymous_namespace{rangeaccrual.cpp}::CommonVars::CommonVars(), CPISwapTest::consistency(), QuantLib::CashFlows::convexity(), InflationCPICapFloorTest::cpicapfloorpricer(), anonymous_namespace{fdmlinearop.cpp}::createHestonHullWhite(), QuantLib::CashFlows::duration(), QuantLib::GaussianLHPCDOEngine< CDOEngine >::expectedTrancheLoss(), QuantLib::InterestRateIndex::fixing(), QuantLib::YoYInflationIndex::fixing(), QuantLib::HaganPricer::floorletPrice(), QuantLib::ForwardSwapQuote::ForwardSwapQuote(), QuantLib::Event::hasOccurred(), QuantLib::historicalForwardRatesAnalysis(), QuantLib::IborCoupon::indexFixing(), QuantLib::SyntheticCDO::engine::initialize(), QuantLib::RecursiveCdoEngine< CDOEngine, copulaT >::initialize(), QuantLib::MonteCarloCDOEngine1::initialize(), QuantLib::HaganPricer::initialize(), QuantLib::AssetSwapHelper::initializeDates(), QuantLib::anonymous_namespace{cashflows.cpp}::IrrFinder::IrrFinder(), QuantLib::CashFlows::isExpired(), QuantLib::Schedule::lower_bound(), anonymous_namespace{libormarketmodelprocess.cpp}::makeIndex(), anonymous_namespace{libormarketmodel.cpp}::makeIndex(), anonymous_namespace{swaptionvolatilitymatrix.cpp}::CommonVars::makeObservabilityTest(), anonymous_namespace{swapforwardmappings.cpp}::MarketModelData::MarketModelData(), QuantLib::FailureToPayEvent::matchesEventType(), QuantLib::anonymous_namespace{cashflows.cpp}::modifiedDuration(), QuantLib::ZeroInflationIndex::needsForecast(), QuantLib::CashFlows::nextCashFlow(), QuantLib::ECB::nextDate(), QuantLib::ECB::nextDates(), QuantLib::CashFlows::npv(), QuantLib::MakeOIS::operator boost::shared_ptr< OvernightIndexedSwap >(), QuantLib::MakeCms::operator boost::shared_ptr< Swap >(), QuantLib::MakeSwaption::operator boost::shared_ptr< Swaption >(), QuantLib::MakeVanillaSwap::operator boost::shared_ptr< VanillaSwap >(), QuantLib::MakeYoYInflationCapFloor::operator boost::shared_ptr< YoYInflationCapFloor >(), QuantLib::detail::quantlib_test_case::operator()(), QuantLib::RiskyAssetSwapOption::performCalculations(), QuantLib::EnergyFuture::performCalculations(), QuantLib::EnergyBasisSwap::performCalculations(), QuantLib::EnergyVanillaSwap::performCalculations(), QuantLib::Basket::performCalculations(), QuantLib::CashFlows::previousCashFlow(), QuantLib::DigitalCoupon::rate(), QuantLib::TermStructure::referenceDate(), QuantLib::RelativeDateBootstrapHelper< TS >::RelativeDateBootstrapHelper(), QuantLib::Basket::scenarioIncrementalTrancheLosses(), QuantLib::Basket::scenarioTrancheLoss(), QuantLib::Schedule::Schedule(), anonymous_namespace{optionletstripper.cpp}::CommonVars::setTermStructure(), QuantLib::YearOnYearInflationSwapHelper::setTermStructure(), QuantLib::Bond::settlementDate(), anonymous_namespace{marketmodel_cms.cpp}::setup(), anonymous_namespace{marketmodel_smm.cpp}::setup(), anonymous_namespace{marketmodel_smmcapletcalibration.cpp}::setup(), anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::setup(), anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::setup(), anonymous_namespace{marketmodel.cpp}::setup(), QuantLib::CapFloor::setupArguments(), QuantLib::anonymous_namespace{cashflows.cpp}::simpleDuration(), QuantLib::SmileSection::SmileSection(), QuantLib::NumericHaganPricer::swapletPrice(), QuantLib::AnalyticHaganPricer::swapletPrice(), QuantLib::anonymous_namespace{overnightindexedcoupon.cpp}::OvernightIndexedCouponPricer::swapletRate(), QuantLib::SwaptionVolatilityCube::SwaptionVolatilityCube(), QuantLib::SwaptionVolatilityDiscrete::SwaptionVolatilityDiscrete(), QuantLib::SyntheticCDO::SyntheticCDO(), CashFlowsTest::testAccessViolation(), HestonModelTest::testAlanLewisReferencePrices(), MargrabeOptionTest::testAmericanExchangeTwoAssets(), MCLongstaffSchwartzEngineTest::testAmericanMaxOption(), MCLongstaffSchwartzEngineTest::testAmericanOption(), BatesModelTest::testAnalyticAndMcVsJumpDiffusion(), AsianOptionTest::testAnalyticContinuousGeometricAveragePriceGreeks(), AsianOptionTest::testAnalyticDiscreteGeometricAveragePriceGreeks(), HybridHestonHullWhiteProcessTest::testAnalyticHestonHullWhitePricing(), HestonModelTest::testAnalyticPiecewiseTimeDependent(), BatesModelTest::testAnalyticVsBlack(), HestonModelTest::testAnalyticVsBlack(), HestonModelTest::testAnalyticVsCached(), BatesModelTest::testAnalyticVsMCPricing(), WriterExtensibleOptionTest::testAnalyticWriterExtensibleOptionEngine(), HestonModelTest::testBlackCalibration(), anonymous_namespace{piecewiseyieldcurve.cpp}::testBMACurveConsistency(), anonymous_namespace{defaultprobabilitycurves.cpp}::testBootstrapFromSpread(), anonymous_namespace{defaultprobabilitycurves.cpp}::testBootstrapFromUpfront(), BondTest::testBrazilianCached(), HybridHestonHullWhiteProcessTest::testBsmHullWhiteEngine(), HybridHestonHullWhiteProcessTest::testBsmHullWhitePricing(), EverestOptionTest::testCached(), HimalayaOptionTest::testCached(), PagodaOptionTest::testCached(), CdsOptionTest::testCached(), BondTest::testCached(), BondTest::testCachedFixed(), BondTest::testCachedFloating(), ShortRateModelTest::testCachedHullWhite(), CreditDefaultSwapTest::testCachedMarketValue(), CreditDefaultSwapTest::testCachedValue(), OvernightIndexedSwapTest::testCachedValue(), SwaptionTest::testCachedValue(), SwapTest::testCachedValue(), CapFloorTest::testCachedValue(), BermudanSwaptionTest::testCachedValues(), BondTest::testCachedZero(), HybridHestonHullWhiteProcessTest::testCallableEquityPricing(), DigitalOptionTest::testCashAtHitOrNothingAmericanGreeks(), HybridHestonHullWhiteProcessTest::testCompareBsmHWandHestonHW(), AssetSwapTest::testConsistency(), GJRGARCHModelTest::testDAXCalibration(), HestonModelTest::testDAXCalibration(), BatesModelTest::testDAXCalibration(), HestonModelTest::testDAXCalibrationOfTimeDependentModel(), DefaultProbabilityCurveTest::testDefaultProbability(), HestonModelTest::testDifferentIntegrals(), HybridHestonHullWhiteProcessTest::testDiscretizationError(), MargrabeOptionTest::testEuroExchangeTwoAssets(), DividendOptionTest::testEuropeanEndLimit(), DividendOptionTest::testEuropeanGreeks(), DividendOptionTest::testEuropeanKnownValue(), DividendOptionTest::testEuropeanStartLimit(), DividendOptionTest::testEuropeanValues(), SwingOptionTest::testExtOUJumpSwingOption(), SwingOptionTest::testExtOUJumpVanillaEngine(), CreditDefaultSwapTest::testFairSpread(), CreditDefaultSwapTest::testFairUpfront(), DividendOptionTest::testFdAmericanDegenerate(), DividendOptionTest::testFdAmericanGreeks(), SwingOptionTest::testFdBSSwingOption(), DividendOptionTest::testFdEuropeanDegenerate(), DividendOptionTest::testFdEuropeanGreeks(), DividendOptionTest::testFdEuropeanValues(), anonymous_namespace{americanoption.cpp}::testFdGreeks(), FdHestonTest::testFdmHestonAmerican(), FdmLinearOpTest::testFdmHestonAmerican(), FdHestonTest::testFdmHestonBarrier(), FdmLinearOpTest::testFdmHestonBarrier(), FdHestonTest::testFdmHestonBarrierVsBlackScholes(), FdHestonTest::testFdmHestonBlackScholes(), FdHestonTest::testFdmHestonConvergence(), FdHestonTest::testFdmHestonEuropeanWithDividends(), FdmLinearOpTest::testFdmHestonExpress(), HybridHestonHullWhiteProcessTest::testFdmHestonHullWhiteEngine(), FdmLinearOpTest::testFdmHestonHullWhiteOp(), FdHestonTest::testFdmHestonIkonenToivanen(), HestonModelTest::testFdVanillaVsCached(), DefaultProbabilityCurveTest::testFlatHazardRate(), QuantoOptionTest::testForwardGreeks(), anonymous_namespace{forwardoption.cpp}::testForwardGreeks(), QuoteTest::testForwardValueQuoteAndImpliedStdevQuote(), NthToDefaultTest::testGauss(), NthToDefaultTest::testGaussStudent(), VPPTest::testGemanRoncoroniProcess(), MargrabeOptionTest::testGreeks(), JumpDiffusionTest::testGreeks(), QuantoOptionTest::testGreeks(), EuropeanOptionTest::testGreeks(), HybridHestonHullWhiteProcessTest::testHestonHullWhiteCalibration(), CdoTest::testHW(), TermStructureTest::testImplied(), CreditDefaultSwapTest::testImpliedHazardRate(), TermStructureTest::testImpliedObs(), LiborMarketModelProcessTest::testInitialisation(), VarianceOptionTest::testIntegralHeston(), PiecewiseYieldCurveTest::testJpyLibor(), HestonModelTest::testKahlJaeckelCase(), VPPTest::testKlugeExtOUSpreadOption(), BarrierOptionTest::testLocalVolAndHestonComparison(), EuropeanOptionTest::testLocalVolatility(), CliquetOptionTest::testMcPerformance(), HybridHestonHullWhiteProcessTest::testMcPureHestonPricing(), HybridHestonHullWhiteProcessTest::testMcVanillaPricing(), HestonModelTest::testMcVsCached(), PathGeneratorTest::testMultiPathGenerator(), HestonModelTest::testMultipleStrikesEngine(), SwaptionVolatilityCubeTest::testObservability(), PiecewiseYieldCurveTest::testObservability(), anonymous_namespace{cliquetoption.cpp}::testOptionGreeks(), BrownianBridgeTest::testPathGeneration(), PathGeneratorTest::testPathGenerator(), TermStructureTest::testReferenceChange(), ConvertibleBondTest::testRegression(), CashFlowsTest::testSettings(), VPPTest::testSimpleExtOUStorageEngine(), DefaultProbabilityCurveTest::testSingleInstrumentBootstrap(), HybridHestonHullWhiteProcessTest::testSpatialDiscretizatinError(), ShortRateModelTest::testSwaps(), VPPTest::testVPPPricing(), InflationTest::testYYIndex(), InflationTest::testYYTermStructure(), HybridHestonHullWhiteProcessTest::testZeroBondPricing(), InflationTest::testZeroIndex(), InflationTest::testZeroTermStructure(), QuantLib::SmileSection::update(), QuantLib::ForwardSwapQuote::update(), QuantLib::SwaptionVolatilityDiscrete::update(), QuantLib::AbcdAtmVolCurve::update(), QuantLib::CapFloorTermVolSurface::update(), QuantLib::CapFloorTermVolCurve::update(), QuantLib::RelativeDateBootstrapHelper< TS >::update(), QuantLib::FuturesConvAdjustmentQuote::value(), QuantLib::CashFlows::yieldValueBasisPoint(), QuantLib::anonymous_namespace{cashflows.cpp}::ZSpreadFinder::ZSpreadFinder(), and QuantLib::SavedSettings::~SavedSettings().
{
        return evaluationDate_;
    }
const Settings::DateProxy & QuantLib::Settings::evaluationDate () const [inline]
Definition at line 157 of file settings.hpp.
References evaluationDate_.
{
        return evaluationDate_;
    }
bool& QuantLib::Settings::includeReferenceDateCashFlows () [inline]
Definition at line 98 of file settings.hpp.
References includeReferenceDateEvents().
{
            return includeReferenceDateEvents();
        }
bool QuantLib::Settings::includeReferenceDateCashFlows () const [inline]
Definition at line 101 of file settings.hpp.
References includeReferenceDateEvents().
{
            return includeReferenceDateEvents();
        }
bool & QuantLib::Settings::includeReferenceDateEvents () [inline]
This flag specifies whether or not Events occurring on the reference date should, by default, be taken into account as not happened yet. It can be overridden locally when calling the Event::hasOccurred method.
Definition at line 161 of file settings.hpp.
References includeReferenceDateEvents_.
Referenced by QuantLib::DiscountingBondEngine::calculate(), QuantLib::DiscountingSwapEngine::calculate(), QuantLib::AnalyticCapFloorEngine::calculate(), QuantLib::Event::hasOccurred(), includeReferenceDateCashFlows(), CashFlowsTest::testSettings(), and QuantLib::SavedSettings::~SavedSettings().
{
        return includeReferenceDateEvents_;
    }
bool QuantLib::Settings::includeReferenceDateEvents () const [inline]
Definition at line 165 of file settings.hpp.
References includeReferenceDateEvents_.
{
        return includeReferenceDateEvents_;
    }
boost::optional< bool > & QuantLib::Settings::includeTodaysCashFlows () [inline]
If set, this flag specifies whether or not CashFlows occurring on today's date should enter the NPV. When the NPV date (i.e., the date at which the cash flows are discounted) equals today's date, this flag overrides the behavior chosen for includeReferenceDate. It cannot be overridden locally when calling the CashFlow::hasOccurred method.
Definition at line 169 of file settings.hpp.
References includeTodaysCashFlows_.
Referenced by QuantLib::AnalyticCapFloorEngine::calculate(), QuantLib::CashFlow::hasOccurred(), QuantLib::UpfrontCdsHelper::impliedQuote(), anonymous_namespace{defaultprobabilitycurves.cpp}::testBootstrapFromSpread(), anonymous_namespace{defaultprobabilitycurves.cpp}::testBootstrapFromUpfront(), CashFlowsTest::testSettings(), DefaultProbabilityCurveTest::testUpfrontBootstrap(), and QuantLib::SavedSettings::~SavedSettings().
{
        return includeTodaysCashFlows_;
    }
boost::optional< bool > QuantLib::Settings::includeTodaysCashFlows () const [inline]
Definition at line 173 of file settings.hpp.
References includeTodaysCashFlows_.
{
        return includeTodaysCashFlows_;
    }
void QuantLib::Settings::resetEvaluationDate ()
Call this to reset the evaluation date to Date::todaysDate() and allow it to change at midnight. It is equivalent to setting the evaluation date to Date(). This comes at the price of losing some performance, since the evaluation date is re-evaluated each time it is read.
Definition at line 45 of file settings.cpp.
References evaluationDate_.
{
        evaluationDate_ = Date();
    }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const DateProxy & p) [friend]
Definition at line 29 of file settings.cpp.
{
        return out << Date(p);
    }
friend class Singleton< Settings > [friend]
Definition at line 38 of file settings.hpp.
Member Data Documentation
bool QuantLib::Settings::enforcesTodaysHistoricFixings_ [private]
Definition at line 122 of file settings.hpp.
Referenced by enforcesTodaysHistoricFixings().
DateProxy QuantLib::Settings::evaluationDate_ [private]
Definition at line 119 of file settings.hpp.
Referenced by anchorEvaluationDate(), evaluationDate(), and resetEvaluationDate().
bool QuantLib::Settings::includeReferenceDateEvents_ [private]
Definition at line 120 of file settings.hpp.
Referenced by includeReferenceDateEvents().
boost::optional<bool> QuantLib::Settings::includeTodaysCashFlows_ [private]
Definition at line 121 of file settings.hpp.
Referenced by includeTodaysCashFlows().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/settings.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/settings.cpp