QuantLib: QuantLib::FrobeniusCostFunction Class Reference
QuantLib::FrobeniusCostFunction Class Reference
#include <tapcorrelations.hpp>
Public Member Functions
FrobeniusCostFunction (const Matrix &target, const boost::function< Disposable< Matrix >(const Array &, Size, Size)> &f, Size matrixSize, Size rank)
Real value (const Array &x) const
method to overload to compute the cost function value in x
Disposable< Array > values (const Array &x) const
method to overload to compute the cost function values in x
Private Attributes
Matrix target_
boost::function< Disposable
< Matrix >const Array &, Size,
Size)> f_
Size matrixSize_
Size rank_
Detailed Description
Definition at line 94 of file tapcorrelations.hpp.
Constructor & Destructor Documentation
QuantLib::FrobeniusCostFunction::FrobeniusCostFunction (const Matrix & target, const boost::function< Disposable< Matrix >(const Array &, Size, Size)> & f, Size matrixSize, Size rank) [inline]
Definition at line 96 of file tapcorrelations.hpp.
        : target_(target), f_(f), matrixSize_(matrixSize), rank_(rank) {}
Member Function Documentation
Real QuantLib::FrobeniusCostFunction::value (const Array & x) const [virtual]
method to overload to compute the cost function value in x
Implements QuantLib::CostFunction.
Definition at line 130 of file tapcorrelations.cpp.
References QuantLib::DotProduct(), and values().
{
        Array temp = values(x);
        return DotProduct(temp, temp);
    }
Disposable< Array > QuantLib::FrobeniusCostFunction::values (const Array & x) const [virtual]
method to overload to compute the cost function values in x
Implements QuantLib::CostFunction.
Definition at line 135 of file tapcorrelations.cpp.
References QuantLib::Matrix::columns(), f_, matrixSize_, rank_, QuantLib::Matrix::rows(), target_, and QuantLib::transpose().
Referenced by value().
{
        Array result((target_.rows()*(target_.columns()-1))/2);
        Matrix pseudoRoot = f_(x, matrixSize_, rank_);
        Matrix differences = pseudoRoot * transpose(pseudoRoot) - target_;
        Size k = 0;
        // then we store the elementwise differences in a vector.
        for (Size i=0; i<target_.rows(); ++i) {
            for (Size j=0; j<i; ++j){
                result[k] = differences[i][j];
                ++k;
            }
        }
        return result;
    }
Member Data Documentation
boost::function<Disposable<Matrix>const Array&, Size, Size)> QuantLib::FrobeniusCostFunction::f_ [private]
Definition at line 108 of file tapcorrelations.hpp.
Referenced by values().
Size QuantLib::FrobeniusCostFunction::matrixSize_ [private]
Definition at line 109 of file tapcorrelations.hpp.
Referenced by values().
Size QuantLib::FrobeniusCostFunction::rank_ [private]
Definition at line 110 of file tapcorrelations.hpp.
Referenced by values().
Matrix QuantLib::FrobeniusCostFunction::target_ [private]
Definition at line 107 of file tapcorrelations.hpp.
Referenced by values().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/matrixutilities/tapcorrelations.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/math/matrixutilities/tapcorrelations.cpp