QuantLib: QuantLib::CallSpecifiedMultiProduct Class Reference
QuantLib::CallSpecifiedMultiProduct Class Reference
#include <callspecifiedmultiproduct.hpp>
Public Member Functions
CallSpecifiedMultiProduct (const Clone< MarketModelMultiProduct > &underlying, const Clone< ExerciseStrategy< CurveState > > &, const Clone< MarketModelMultiProduct > &rebate=Clone< MarketModelMultiProduct >())
const MarketModelMultiProduct & underlying () const
const ExerciseStrategy
< CurveState > & strategy () const
const MarketModelMultiProduct & rebate () const
void enableCallability ()
void disableCallability ()
MarketModelMultiProduct interface
std::vector< Size > suggestedNumeraires () const
const EvolutionDescription & evolution () const
std::vector< Time > possibleCashFlowTimes () const
Size numberOfProducts () const
Size maxNumberOfCashFlowsPerProductPerStep () const
void reset ()
during simulation put product at start of path
bool nextTimeStep (const CurveState &currentState, std::vector< Size > &numberCashFlowsThisStep, std::vector< std::vector< CashFlow > > &cashFlowsGenerated)
return value indicates whether path is finished, TRUE means done
std::auto_ptr
< MarketModelMultiProduct > clone () const
returns a newly-allocated copy of itself
Private Attributes
Clone< MarketModelMultiProduct > underlying_
Clone< ExerciseStrategy
< CurveState > > strategy_
Clone< MarketModelMultiProduct > rebate_
EvolutionDescription evolution_
std::vector< std::valarray
< bool > > isPresent_
std::vector< Time > cashFlowTimes_
Size rebateOffset_
bool wasCalled_
std::vector< Size > dummyCashFlowsThisStep_
std::vector< std::vector
< CashFlow > > dummyCashFlowsGenerated_
Size currentIndex_
bool callable_
Detailed Description
Definition at line 32 of file callspecifiedmultiproduct.hpp.
Constructor & Destructor Documentation
QuantLib::CallSpecifiedMultiProduct::CallSpecifiedMultiProduct (const Clone< MarketModelMultiProduct > & underlying, const Clone< ExerciseStrategy< CurveState > > & strategy, const Clone< MarketModelMultiProduct > & rebate = Clone<MarketModelMultiProduct>())
Definition at line 26 of file callspecifiedmultiproduct.cpp.
References cashFlowTimes_, dummyCashFlowsGenerated_, dummyCashFlowsThisStep_, QuantLib::Clone< T >::empty(), QuantLib::MarketModelMultiProduct::evolution(), evolution_, QuantLib::EvolutionDescription::evolutionTimes(), QuantLib::ExerciseStrategy< State >::exerciseTimes(), isPresent_, QuantLib::MarketModelMultiProduct::maxNumberOfCashFlowsPerProductPerStep(), QuantLib::mergeTimes(), QuantLib::MarketModelMultiProduct::numberOfProducts(), QuantLib::MarketModelMultiProduct::possibleCashFlowTimes(), QL_REQUIRE, QuantLib::EvolutionDescription::rateTimes(), rebate_, rebateOffset_, QuantLib::ExerciseStrategy< State >::relevantTimes(), strategy(), and underlying_.
Referenced by clone().
                    : underlying_(underlying),
                    strategy_(strategy),
                    rebate_(rebate),
                    callable_(true)
    {
        Size products = underlying_->numberOfProducts();
        EvolutionDescription d1 = underlying->evolution();
        const std::vector<Time>& rateTimes1 = d1.rateTimes();
        const std::vector<Time>& evolutionTimes1 = d1.evolutionTimes();
        const std::vector<Time>& exerciseTimes = strategy->exerciseTimes();
        if (!rebate_.empty())
        {
            EvolutionDescription d2 = rebate_->evolution();
            const std::vector<Time>& rateTimes2 = d2.rateTimes();
            QL_REQUIRE(rateTimes1.size() == rateTimes2.size() &&
                       std::equal(rateTimes1.begin(), rateTimes1.end(),
                                  rateTimes2.begin()),
                       "incompatible rate times");
        }
        else
        {
            EvolutionDescription description(rateTimes1, exerciseTimes);
            Matrix amounts(products, exerciseTimes.size(), 0.0);
            rebate_ = MarketModelCashRebate(description, exerciseTimes,
                                            amounts, products);
        }
        std::vector<Time> mergedEvolutionTimes;
        std::vector<std::vector<Time> > allEvolutionTimes(4);
        allEvolutionTimes[0] = evolutionTimes1;
        allEvolutionTimes[1] = exerciseTimes;
        allEvolutionTimes[2] = rebate_->evolution().evolutionTimes();
        allEvolutionTimes[3] = strategy->relevantTimes();
        mergeTimes(allEvolutionTimes,
                                    mergedEvolutionTimes,
                                    isPresent_);
        // TODO: add relevant rates
        evolution_ = EvolutionDescription(rateTimes1, mergedEvolutionTimes);
        cashFlowTimes_ = underlying_->possibleCashFlowTimes();
        rebateOffset_ = cashFlowTimes_.size();
        const std::vector<Time> rebateTimes = rebate_->possibleCashFlowTimes();
        cashFlowTimes_.insert(cashFlowTimes_.end(),
                                                           rebateTimes.begin(), rebateTimes.end());
        dummyCashFlowsThisStep_ = std::vector<Size>(products, 0);
        Size n = rebate_->maxNumberOfCashFlowsPerProductPerStep();
        dummyCashFlowsGenerated_ =
            std::vector<std::vector<CashFlow> >(products,
                                                std::vector<CashFlow>(n));
    }
Member Function Documentation
std::auto_ptr< MarketModelMultiProduct > QuantLib::CallSpecifiedMultiProduct::clone () const [virtual]
returns a newly-allocated copy of itself
Implements QuantLib::MarketModelMultiProduct.
Reimplemented in QuantLib::anonymous_namespace{upperboundengine.cpp}::DecoratedHedge.
Definition at line 175 of file callspecifiedmultiproduct.cpp.
References CallSpecifiedMultiProduct().
    {
        return std::auto_ptr<MarketModelMultiProduct>(
                                        new CallSpecifiedMultiProduct(*this));
    }
void QuantLib::CallSpecifiedMultiProduct::disableCallability ()
Definition at line 204 of file callspecifiedmultiproduct.cpp.
References callable_.
    {
        callable_ = false;
    }
void QuantLib::CallSpecifiedMultiProduct::enableCallability ()
Definition at line 199 of file callspecifiedmultiproduct.cpp.
References callable_.
    {
        callable_ = true;
    }
const EvolutionDescription & QuantLib::CallSpecifiedMultiProduct::evolution () const [virtual]
Implements QuantLib::MarketModelMultiProduct.
Definition at line 93 of file callspecifiedmultiproduct.cpp.
References evolution_.
Referenced by QuantLib::anonymous_namespace{upperboundengine.cpp}::DecoratedHedge::DecoratedHedge(), MarketModelTest::testCallableSwapAnderson(), MarketModelTest::testCallableSwapLS(), and MarketModelTest::testCallableSwapNaif().
    {
        return evolution_;
    }
Size QuantLib::CallSpecifiedMultiProduct::maxNumberOfCashFlowsPerProductPerStep () const [virtual]
Implements QuantLib::MarketModelMultiProduct.
Definition at line 110 of file callspecifiedmultiproduct.cpp.
References QuantLib::MarketModelMultiProduct::maxNumberOfCashFlowsPerProductPerStep(), rebate_, and underlying_.
Referenced by QuantLib::anonymous_namespace{upperboundengine.cpp}::DecoratedHedge::DecoratedHedge().
    {
        return std::max(underlying_->maxNumberOfCashFlowsPerProductPerStep(),
                        rebate_->maxNumberOfCashFlowsPerProductPerStep());
    }
bool QuantLib::CallSpecifiedMultiProduct::nextTimeStep (const CurveState & currentState, std::vector< Size > & numberCashFlowsThisStep, std::vector< std::vector< CashFlow > > & cashFlowsGenerated) [virtual]
return value indicates whether path is finished, TRUE means done
Implements QuantLib::MarketModelMultiProduct.
Reimplemented in QuantLib::anonymous_namespace{upperboundengine.cpp}::DecoratedHedge.
Definition at line 126 of file callspecifiedmultiproduct.cpp.
References callable_, currentIndex_, dummyCashFlowsGenerated_, dummyCashFlowsThisStep_, evolution_, QuantLib::EvolutionDescription::evolutionTimes(), QuantLib::ExerciseStrategy< State >::exercise(), isPresent_, QuantLib::ExerciseStrategy< State >::nextStep(), QuantLib::MarketModelMultiProduct::nextTimeStep(), rebate_, rebateOffset_, strategy_, underlying_, and wasCalled_.
Referenced by QuantLib::anonymous_namespace{upperboundengine.cpp}::DecoratedHedge::nextTimeStep(), and QuantLib::anonymous_namespace{upperboundengine.cpp}::DecoratedHedge::reset().
    {
        bool isUnderlyingTime = isPresent_[0][currentIndex_];
        bool isExerciseTime = isPresent_[1][currentIndex_];
        bool isRebateTime = isPresent_[2][currentIndex_];
        bool isStrategyRelevantTime = isPresent_[3][currentIndex_];
        bool done = false;
        if (!wasCalled_ && isStrategyRelevantTime)
            strategy_->nextStep(currentState);
        if (!wasCalled_ && isExerciseTime && callable_)
            wasCalled_ = strategy_->exercise(currentState);
        if (wasCalled_)
        {
            if (isRebateTime)
            {
                done = rebate_->nextTimeStep(currentState,
                                             numberCashFlowsThisStep,
                                             cashFlowsGenerated);
                for (Size i=0; i<numberCashFlowsThisStep.size(); ++i)
                    for (Size j=0; j<numberCashFlowsThisStep[i]; ++j)
                        cashFlowsGenerated[i][j].timeIndex += rebateOffset_;
            }
        }
        else
        {
            if (isRebateTime)
                rebate_->nextTimeStep(currentState,
                                      dummyCashFlowsThisStep_,
                                      dummyCashFlowsGenerated_);
            if (isUnderlyingTime)
                done = underlying_->nextTimeStep(currentState,
                                                 numberCashFlowsThisStep,
                                                 cashFlowsGenerated);
        }
        ++currentIndex_;
        return done || currentIndex_ == evolution_.evolutionTimes().size();
    }
Size QuantLib::CallSpecifiedMultiProduct::numberOfProducts () const [virtual]
Implements QuantLib::MarketModelMultiProduct.
Definition at line 104 of file callspecifiedmultiproduct.cpp.
References QuantLib::MarketModelMultiProduct::numberOfProducts(), and underlying_.
Referenced by QuantLib::anonymous_namespace{upperboundengine.cpp}::DecoratedHedge::DecoratedHedge().
    {
        return underlying_->numberOfProducts();
    }
std::vector< Time > QuantLib::CallSpecifiedMultiProduct::possibleCashFlowTimes () const [virtual]
Implements QuantLib::MarketModelMultiProduct.
Definition at line 99 of file callspecifiedmultiproduct.cpp.
References cashFlowTimes_.
    {
        return cashFlowTimes_;
    }
const MarketModelMultiProduct & QuantLib::CallSpecifiedMultiProduct::rebate () const
Definition at line 194 of file callspecifiedmultiproduct.cpp.
References rebate_.
    {
        return *rebate_;
    }
void QuantLib::CallSpecifiedMultiProduct::reset () [virtual]
during simulation put product at start of path
Implements QuantLib::MarketModelMultiProduct.
Reimplemented in QuantLib::anonymous_namespace{upperboundengine.cpp}::DecoratedHedge.
Definition at line 116 of file callspecifiedmultiproduct.cpp.
References currentIndex_, rebate_, QuantLib::ExerciseStrategy< State >::reset(), QuantLib::MarketModelMultiProduct::reset(), strategy_, underlying_, and wasCalled_.
    {
        underlying_->reset();
        rebate_->reset();
        strategy_->reset();
        currentIndex_ = 0;
        wasCalled_ = false;
    }
const ExerciseStrategy< CurveState > & QuantLib::CallSpecifiedMultiProduct::strategy () const
Definition at line 188 of file callspecifiedmultiproduct.cpp.
References strategy_.
Referenced by CallSpecifiedMultiProduct().
    {
        return *strategy_;
    }
std::vector< Size > QuantLib::CallSpecifiedMultiProduct::suggestedNumeraires () const [virtual]
Implements QuantLib::MarketModelMultiProduct.
Definition at line 88 of file callspecifiedmultiproduct.cpp.
References QuantLib::MarketModelMultiProduct::suggestedNumeraires(), and underlying_.
    {
        return underlying_->suggestedNumeraires();
    }
const MarketModelMultiProduct & QuantLib::CallSpecifiedMultiProduct::underlying () const
Definition at line 182 of file callspecifiedmultiproduct.cpp.
References underlying_.
    {
        return *underlying_;
    }
Member Data Documentation
bool QuantLib::CallSpecifiedMultiProduct::callable_ [private]
Definition at line 70 of file callspecifiedmultiproduct.hpp.
Referenced by disableCallability(), enableCallability(), and nextTimeStep().
std::vector<Time> QuantLib::CallSpecifiedMultiProduct::cashFlowTimes_ [private]
Definition at line 64 of file callspecifiedmultiproduct.hpp.
Referenced by CallSpecifiedMultiProduct(), and possibleCashFlowTimes().
Size QuantLib::CallSpecifiedMultiProduct::currentIndex_ [private]
Definition at line 69 of file callspecifiedmultiproduct.hpp.
Referenced by nextTimeStep(), and reset().
std::vector<std::vector<CashFlow> > QuantLib::CallSpecifiedMultiProduct::dummyCashFlowsGenerated_ [private]
Definition at line 68 of file callspecifiedmultiproduct.hpp.
Referenced by CallSpecifiedMultiProduct(), and nextTimeStep().
std::vector<Size> QuantLib::CallSpecifiedMultiProduct::dummyCashFlowsThisStep_ [private]
Definition at line 67 of file callspecifiedmultiproduct.hpp.
Referenced by CallSpecifiedMultiProduct(), and nextTimeStep().
EvolutionDescription QuantLib::CallSpecifiedMultiProduct::evolution_ [private]
Definition at line 62 of file callspecifiedmultiproduct.hpp.
Referenced by CallSpecifiedMultiProduct(), evolution(), and nextTimeStep().
std::vector<std::valarray<bool> > QuantLib::CallSpecifiedMultiProduct::isPresent_ [private]
Definition at line 63 of file callspecifiedmultiproduct.hpp.
Referenced by CallSpecifiedMultiProduct(), and nextTimeStep().
Clone<MarketModelMultiProduct> QuantLib::CallSpecifiedMultiProduct::rebate_ [private]
Definition at line 61 of file callspecifiedmultiproduct.hpp.
Referenced by CallSpecifiedMultiProduct(), maxNumberOfCashFlowsPerProductPerStep(), nextTimeStep(), rebate(), and reset().
Size QuantLib::CallSpecifiedMultiProduct::rebateOffset_ [private]
Definition at line 65 of file callspecifiedmultiproduct.hpp.
Referenced by CallSpecifiedMultiProduct(), and nextTimeStep().
Clone<ExerciseStrategy<CurveState> > QuantLib::CallSpecifiedMultiProduct::strategy_ [private]
Definition at line 60 of file callspecifiedmultiproduct.hpp.
Referenced by nextTimeStep(), reset(), and strategy().
Clone<MarketModelMultiProduct> QuantLib::CallSpecifiedMultiProduct::underlying_ [private]
Definition at line 59 of file callspecifiedmultiproduct.hpp.
Referenced by CallSpecifiedMultiProduct(), maxNumberOfCashFlowsPerProductPerStep(), nextTimeStep(), numberOfProducts(), reset(), suggestedNumeraires(), and underlying().
bool QuantLib::CallSpecifiedMultiProduct::wasCalled_ [private]
Definition at line 66 of file callspecifiedmultiproduct.hpp.
Referenced by nextTimeStep(), and reset().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/products/multistep/callspecifiedmultiproduct.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/products/multistep/callspecifiedmultiproduct.cpp