QuantLib: QuantLib::GeneralizedOrnsteinUhlenbeckProcess Class Reference
QuantLib::GeneralizedOrnsteinUhlenbeckProcess Class Reference
Piecewise linear Ornstein-Uhlenbeck process class.
#include <generalizedornsteinuhlenbeckprocess.hpp>
Public Member Functions
GeneralizedOrnsteinUhlenbeckProcess (const boost::function< Real(Time)> &speed, const boost::function< Real(Time)> &vol, Real x0=0.0, Real level=0.0)
Real speed (Time t) const
Real volatility (Time t) const
Real level () const
StochasticProcess1D interface
Real x0 () const
returns the initial value of the state variable
Real drift (Time t, Real x) const
returns the drift part of the equation, i.e. \(\mu(t, x_t) \)
Real diffusion (Time t, Real x) const
returns the diffusion part of the equation, i.e. \(\sigma(t, x_t) \)
Real expectation (Time t0, Real x0, Time dt) const
Real stdDeviation (Time t0, Real x0, Time dt) const
Real variance (Time t0, Real x0, Time dt) const
Private Attributes
Real x0_
Real level_
boost::function< Real(Time)> speed_
boost::function< Real(Time)> volatility_
Detailed Description
Piecewise linear Ornstein-Uhlenbeck process class.
This class describes the Ornstein-Uhlenbeck process governed by
\[ dx = a (level - x_t) dt + \sigma dW_t \]
where the coefficients a and sigma are piecewise linear.
Definition at line 43 of file generalizedornsteinuhlenbeckprocess.hpp.
Constructor & Destructor Documentation
QuantLib::GeneralizedOrnsteinUhlenbeckProcess::GeneralizedOrnsteinUhlenbeckProcess (const boost::function< Real(Time)> & speed, const boost::function< Real(Time)> & vol, Real x0 = 0.0, Real level = 0.0)
Definition at line 25 of file generalizedornsteinuhlenbeckprocess.cpp.
References QL_REQUIRE.
    : x0_(x0), level_(level), speed_(speed), volatility_(vol) {
        QL_REQUIRE(x0 >= 0.0, "negative initial data given");
        QL_REQUIRE(level >= 0.0, "negative level given");
    }
Member Function Documentation
Real QuantLib::GeneralizedOrnsteinUhlenbeckProcess::diffusion (Time t, Real x) const [virtual]
returns the diffusion part of the equation, i.e. \(\sigma(t, x_t) \)
Implements QuantLib::StochasticProcess1D.
Definition at line 44 of file generalizedornsteinuhlenbeckprocess.cpp.
References volatility_.
{
        return volatility_(t);
    }
Real QuantLib::GeneralizedOrnsteinUhlenbeckProcess::drift (Time t, Real x) const [virtual]
returns the drift part of the equation, i.e. \(\mu(t, x_t) \)
Implements QuantLib::StochasticProcess1D.
Definition at line 40 of file generalizedornsteinuhlenbeckprocess.cpp.
References level_, and speed_.
{
        return speed_(t) * (level_ - x);;
    }
Real QuantLib::GeneralizedOrnsteinUhlenbeckProcess::expectation (Time t0, Real x0, Time dt) const [virtual]
returns the expectation \(E(x_{t_0 + \Delta t} | x_{t_0} = x_0) \) of the process after a time interval \(\Delta t \) according to the given discretization. This method can be overridden in derived classes which want to hard-code a particular discretization.
Reimplemented from QuantLib::StochasticProcess1D.
Definition at line 48 of file generalizedornsteinuhlenbeckprocess.cpp.
References QuantLib::anonymous_namespace{yieldtermstructure.cpp}::dt, level_, and speed_.
{
        return level_ + (x0 - level_) * std::exp(-speed_(t)*dt);
    }
Real QuantLib::GeneralizedOrnsteinUhlenbeckProcess::level () const
Definition at line 80 of file generalizedornsteinuhlenbeckprocess.cpp.
References level_.
{
        return level_;
    }
Real QuantLib::GeneralizedOrnsteinUhlenbeckProcess::speed (Time t) const
Definition at line 72 of file generalizedornsteinuhlenbeckprocess.cpp.
References speed_.
Referenced by variance().
{
        return speed_(t);
    }
Real QuantLib::GeneralizedOrnsteinUhlenbeckProcess::stdDeviation (Time t0, Real x0, Time dt) const [virtual]
returns the standard deviation \(S(x_{t_0 + \Delta t} | x_{t_0} = x_0) \) of the process after a time interval \(\Delta t \) according to the given discretization. This method can be overridden in derived classes which want to hard-code a particular discretization.
Reimplemented from QuantLib::StochasticProcess1D.
Definition at line 53 of file generalizedornsteinuhlenbeckprocess.cpp.
References variance().
{
        return std::sqrt(variance(t,x0,dt));
    }
Real QuantLib::GeneralizedOrnsteinUhlenbeckProcess::variance (Time t0, Real x0, Time dt) const [virtual]
returns the variance \(V(x_{t_0 + \Delta t} | x_{t_0} = x_0) \) of the process after a time interval \(\Delta t \) according to the given discretization. This method can be overridden in derived classes which want to hard-code a particular discretization.
Reimplemented from QuantLib::StochasticProcess1D.
Definition at line 58 of file generalizedornsteinuhlenbeckprocess.cpp.
References QuantLib::anonymous_namespace{yieldtermstructure.cpp}::dt, QL_EPSILON, speed(), speed_, and volatility_.
Referenced by stdDeviation().
{
        Real speed = speed_(t);
        Volatility vol = volatility_(t);
        if (speed < std::sqrt(QL_EPSILON)) {
            // algebraic limit for small speed
            return vol*vol*dt;
        } else {
            return 0.5*vol*vol/speed*(1.0 - std::exp(-2.0*speed*dt));
        }
    }
Real QuantLib::GeneralizedOrnsteinUhlenbeckProcess::volatility (Time t) const
Definition at line 76 of file generalizedornsteinuhlenbeckprocess.cpp.
References volatility_.
{
        return volatility_(t);
    }
Real QuantLib::GeneralizedOrnsteinUhlenbeckProcess::x0 () const [virtual]
returns the initial value of the state variable
Implements QuantLib::StochasticProcess1D.
Definition at line 36 of file generalizedornsteinuhlenbeckprocess.cpp.
References x0_.
{
        return x0_;
    }
Member Data Documentation
Real QuantLib::GeneralizedOrnsteinUhlenbeckProcess::level_ [private]
Definition at line 67 of file generalizedornsteinuhlenbeckprocess.hpp.
Referenced by drift(), expectation(), and level().
boost::function<Real (Time)> QuantLib::GeneralizedOrnsteinUhlenbeckProcess::speed_ [private]
Definition at line 68 of file generalizedornsteinuhlenbeckprocess.hpp.
Referenced by drift(), expectation(), speed(), and variance().
boost::function<Real (Time)> QuantLib::GeneralizedOrnsteinUhlenbeckProcess::volatility_ [private]
Definition at line 69 of file generalizedornsteinuhlenbeckprocess.hpp.
Referenced by diffusion(), variance(), and volatility().
Real QuantLib::GeneralizedOrnsteinUhlenbeckProcess::x0_ [private]
Definition at line 67 of file generalizedornsteinuhlenbeckprocess.hpp.
Referenced by x0().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/shortrate/generalizedornsteinuhlenbeckprocess.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/shortrate/generalizedornsteinuhlenbeckprocess.cpp