QuantLib: QuantLib::FdmHestonEquityPart Class Reference
QuantLib::FdmHestonEquityPart Class Reference
#include <fdmhestonop.hpp>
Public Member Functions
FdmHestonEquityPart (const boost::shared_ptr< FdmMesher > &mesher, const boost::shared_ptr< YieldTermStructure > &rTS, const boost::shared_ptr< YieldTermStructure > &qTS, const boost::shared_ptr< FdmQuantoHelper > &quantoHelper)
void setTime (Time t1, Time t2)
const TripleBandLinearOp & getMap () const
Protected Attributes
Array varianceValues_
Array volatilityValues_
const FirstDerivativeOp dxMap_
const TripleBandLinearOp dxxMap_
TripleBandLinearOp mapT_
const boost::shared_ptr
< FdmMesher > mesher_
const boost::shared_ptr
< YieldTermStructure > rTS_
const boost::shared_ptr
< YieldTermStructure > qTS_
const boost::shared_ptr
< FdmQuantoHelper > quantoHelper_
Detailed Description
Definition at line 38 of file fdmhestonop.hpp.
Constructor & Destructor Documentation
QuantLib::FdmHestonEquityPart::FdmHestonEquityPart (const boost::shared_ptr< FdmMesher > & mesher, const boost::shared_ptr< YieldTermStructure > & rTS, const boost::shared_ptr< YieldTermStructure > & qTS, const boost::shared_ptr< FdmQuantoHelper > & quantoHelper)
Definition at line 30 of file fdmhestonop.cpp.
References mesher_, QuantLib::Sqrt(), varianceValues_, and volatilityValues_.
    : varianceValues_(0.5*mesher->locations(1)),
      dxMap_ (FirstDerivativeOp(0, mesher)),
      dxxMap_(SecondDerivativeOp(0, mesher).mult(0.5*mesher->locations(1))),
      mapT_  (0, mesher),
      mesher_(mesher),
      rTS_(rTS),
      qTS_(qTS),
      quantoHelper_(quantoHelper) {
        // on the boundary s_min and s_max the second derivative
        // d^2V/dS^2 is zero and due to Ito's Lemma the variance term
        // in the drift should vanish.
        boost::shared_ptr<FdmLinearOpLayout> layout = mesher_->layout();
        FdmLinearOpIterator endIter = layout->end();
        for (FdmLinearOpIterator iter = layout->begin(); iter != endIter;
            ++iter) {
            if (   iter.coordinates()[0] == 0
                || iter.coordinates()[0] == layout->dim()[0]-1) {
                varianceValues_[iter.index()] = 0.0;
            }
        }
        volatilityValues_ = Sqrt(2*varianceValues_);
    }
Member Function Documentation
const TripleBandLinearOp & QuantLib::FdmHestonEquityPart::getMap () const
Definition at line 74 of file fdmhestonop.cpp.
References mapT_.
Referenced by QuantLib::FdmHestonOp::apply(), QuantLib::FdmHestonOp::apply_direction(), QuantLib::FdmHestonOp::solve_splitting(), and QuantLib::FdmHestonOp::toMatrix().
{
        return mapT_;
    }
void QuantLib::FdmHestonEquityPart::setTime (Time t1, Time t2)
Definition at line 59 of file fdmhestonop.cpp.
References QuantLib::TripleBandLinearOp::axpyb(), QuantLib::Continuous, dxMap_, dxxMap_, mapT_, qTS_, quantoHelper_, rTS_, varianceValues_, and volatilityValues_.
Referenced by QuantLib::FdmHestonOp::setTime().
{
        const Rate r = rTS_->forwardRate(t1, t2, Continuous).rate();
        const Rate q = qTS_->forwardRate(t1, t2, Continuous).rate();
        if (quantoHelper_) {
            mapT_.axpyb(r - q - varianceValues_
                - quantoHelper_->quantoAdjustment(
                volatilityValues_, t1, t2),
                dxMap_, dxxMap_, Array(1, -0.5*r));
        }
        else {
            mapT_.axpyb(r - q - varianceValues_, dxMap_, dxxMap_, Array(1, -0.5*r));
        }
    }
Member Data Documentation
const FirstDerivativeOp QuantLib::FdmHestonEquityPart::dxMap_ [protected]
Definition at line 51 of file fdmhestonop.hpp.
Referenced by setTime().
const TripleBandLinearOp QuantLib::FdmHestonEquityPart::dxxMap_ [protected]
Definition at line 52 of file fdmhestonop.hpp.
Referenced by setTime().
TripleBandLinearOp QuantLib::FdmHestonEquityPart::mapT_ [protected]
Definition at line 53 of file fdmhestonop.hpp.
Referenced by getMap(), and setTime().
const boost::shared_ptr<FdmMesher> QuantLib::FdmHestonEquityPart::mesher_ [protected]
Definition at line 55 of file fdmhestonop.hpp.
Referenced by FdmHestonEquityPart().
const boost::shared_ptr<YieldTermStructure> QuantLib::FdmHestonEquityPart::qTS_ [protected]
Definition at line 56 of file fdmhestonop.hpp.
Referenced by setTime().
const boost::shared_ptr<FdmQuantoHelper> QuantLib::FdmHestonEquityPart::quantoHelper_ [protected]
Definition at line 57 of file fdmhestonop.hpp.
Referenced by setTime().
const boost::shared_ptr<YieldTermStructure> QuantLib::FdmHestonEquityPart::rTS_ [protected]
Definition at line 56 of file fdmhestonop.hpp.
Referenced by setTime().
Array QuantLib::FdmHestonEquityPart::varianceValues_ [protected]
Definition at line 50 of file fdmhestonop.hpp.
Referenced by FdmHestonEquityPart(), and setTime().
Array QuantLib::FdmHestonEquityPart::volatilityValues_ [protected]
Definition at line 50 of file fdmhestonop.hpp.
Referenced by FdmHestonEquityPart(), and setTime().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/operators/fdmhestonop.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/operators/fdmhestonop.cpp