QuantLib: QuantLib::AbcdInterpolation Class Reference
QuantLib::AbcdInterpolation Class Reference
Abcd interpolation between discrete points.
#include <abcdinterpolation.hpp>
Public Member Functions
template<class I1 , class I2 >
AbcdInterpolation (const I1 &xBegin, const I1 &xEnd, const I2 &yBegin, Real a=-0.06, Real b=0.17, Real c=0.54, Real d=0.17, bool aIsFixed=false, bool bIsFixed=false, bool cIsFixed=false, bool dIsFixed=false, bool vegaWeighted=false, const boost::shared_ptr< EndCriteria > &endCriteria=boost::shared_ptr< EndCriteria >(), const boost::shared_ptr< OptimizationMethod > &optMethod=boost::shared_ptr< OptimizationMethod >())
Inspectors
boost::shared_ptr
< detail::AbcdCoeffHolder > coeffs_
Real a () const
Real b () const
Real c () const
Real d () const
std::vector< Real > k () const
Real rmsError () const
Real maxError () const
EndCriteria::Type endCriteria ()
template<class I1 >
Real k (Time t, const I1 &xBegin, const I1 &xEnd) const
Detailed Description
Abcd interpolation between discrete points.
Definition at line 158 of file abcdinterpolation.hpp.
Constructor & Destructor Documentation
template<class I1 , class I2 > QuantLib::AbcdInterpolation::AbcdInterpolation (const I1 & xBegin, const I1 & xEnd, const I2 & yBegin, Real a = -0.06, Real b = 0.17, Real c = 0.54, Real d = 0.17, bool aIsFixed = false, bool bIsFixed = false, bool cIsFixed = false, bool dIsFixed = false, bool vegaWeighted = false, const boost::shared_ptr< EndCriteria > & endCriteria = boost::shared_ptr<EndCriteria>(), const boost::shared_ptr< OptimizationMethod > & optMethod = boost::shared_ptr<OptimizationMethod>()) [inline]
Constructor
Definition at line 162 of file abcdinterpolation.hpp.
References a(), b(), c(), coeffs_, d(), endCriteria(), and QuantLib::Interpolation::impl_.
{
            impl_ = boost::shared_ptr<Interpolation::Impl>(new
                detail::AbcdInterpolationImpl<I1,I2>(xBegin, xEnd, yBegin,
                                                     a, b, c, d,
                                                     aIsFixed, bIsFixed,
                                                     cIsFixed, dIsFixed,
                                                     vegaWeighted,
                                                     endCriteria,
                                                     optMethod));
            impl_->update();
            coeffs_ =
                boost::dynamic_pointer_cast<detail::AbcdCoeffHolder>(impl_);
        }
Member Function Documentation
Real QuantLib::AbcdInterpolation::a () const [inline]
Definition at line 193 of file abcdinterpolation.hpp.
References coeffs_.
Referenced by AbcdInterpolation().
{ return coeffs_->a_; }
Real QuantLib::AbcdInterpolation::b () const [inline]
Definition at line 194 of file abcdinterpolation.hpp.
References coeffs_.
Referenced by AbcdInterpolation().
{ return coeffs_->b_; }
Real QuantLib::AbcdInterpolation::c () const [inline]
Definition at line 195 of file abcdinterpolation.hpp.
References coeffs_.
Referenced by AbcdInterpolation().
{ return coeffs_->c_; }
Real QuantLib::AbcdInterpolation::d () const [inline]
Definition at line 196 of file abcdinterpolation.hpp.
References coeffs_.
Referenced by AbcdInterpolation().
{ return coeffs_->d_; }
EndCriteria::Type QuantLib::AbcdInterpolation::endCriteria () [inline]
Definition at line 200 of file abcdinterpolation.hpp.
References coeffs_.
Referenced by AbcdInterpolation().
{ return coeffs_->abcdEndCriteria_; }
std::vector<Real> QuantLib::AbcdInterpolation::k () const [inline]
Definition at line 197 of file abcdinterpolation.hpp.
References coeffs_.
{ return coeffs_->k_; }
template<class I1 > Real QuantLib::AbcdInterpolation::k (Time t, const I1 & xBegin, const I1 & xEnd) const [inline]
Definition at line 202 of file abcdinterpolation.hpp.
References coeffs_.
{
            LinearInterpolation li(xBegin, xEnd, (coeffs_->k_).begin());
            return li(t);
        }
Real QuantLib::AbcdInterpolation::maxError () const [inline]
Definition at line 199 of file abcdinterpolation.hpp.
References coeffs_.
{ return coeffs_->maxError_; }
Real QuantLib::AbcdInterpolation::rmsError () const [inline]
Definition at line 198 of file abcdinterpolation.hpp.
References coeffs_.
{ return coeffs_->error_; }
Member Data Documentation
boost::shared_ptr<detail::AbcdCoeffHolder> QuantLib::AbcdInterpolation::coeffs_ [private]
Definition at line 207 of file abcdinterpolation.hpp.
Referenced by a(), AbcdInterpolation(), b(), c(), d(), endCriteria(), k(), maxError(), and rmsError().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/interpolations/abcdinterpolation.hpp