QuantLib: QuantLib::Interpolation2D Class Reference
QuantLib::Interpolation2D Class Reference
base class for 2-D interpolations.
#include <interpolation2d.hpp>
Classes
class Impl
abstract base class for 2-D interpolation implementations
class templateImpl
basic template implementation
Public Types
typedef Real first_argument_type
typedef Real second_argument_type
typedef Real result_type
Public Member Functions
Interpolation2D ()
Real operator() (Real x, Real y, bool allowExtrapolation=false) const
Real xMin () const
Real xMax () const
std::vector< Real > xValues () const
Size locateX (Real x) const
Real yMin () const
Real yMax () const
std::vector< Real > yValues () const
Size locateY (Real y) const
const Matrix & zData () const
bool isInRange (Real x, Real y) const
void update ()
Protected Member Functions
void checkRange (Real x, Real y, bool extrapolate) const
Protected Attributes
boost::shared_ptr< Impl > impl_
Detailed Description
base class for 2-D interpolations.
Classes derived from this class will provide interpolated values from two sequences of length \(N \) and \(M \), representing the discretized values of the \(x \) and \(y \) variables, and a \(N \times M \) matrix representing the tabulated function values.
Definition at line 44 of file interpolation2d.hpp.
Member Typedef Documentation
typedef Real QuantLib::Interpolation2D::first_argument_type
Definition at line 65 of file interpolation2d.hpp.
typedef Real QuantLib::Interpolation2D::result_type
Definition at line 67 of file interpolation2d.hpp.
typedef Real QuantLib::Interpolation2D::second_argument_type
Definition at line 66 of file interpolation2d.hpp.
Constructor & Destructor Documentation
QuantLib::Interpolation2D::Interpolation2D () [inline]
Definition at line 153 of file interpolation2d.hpp.
{}
Member Function Documentation
void QuantLib::Interpolation2D::checkRange (Real x, Real y, bool extrapolate) const [inline, protected]
Definition at line 193 of file interpolation2d.hpp.
References QuantLib::Extrapolator::allowsExtrapolation(), impl_, and QL_REQUIRE.
Referenced by operator()().
{
            QL_REQUIRE(extrapolate || allowsExtrapolation() ||
                       impl_->isInRange(x,y),
                       "interpolation range is ["
                       << impl_->xMin() << ", " << impl_->xMax()
                       << "] x ["
                       << impl_->yMin() << ", " << impl_->yMax()
                       << "]: extrapolation at ("
                       << x << ", " << y << ") not allowed");
        }
bool QuantLib::Interpolation2D::isInRange (Real x, Real y) const [inline]
Definition at line 186 of file interpolation2d.hpp.
References impl_.
{
            return impl_->isInRange(x,y);
        }
Size QuantLib::Interpolation2D::locateX (Real x) const [inline]
Definition at line 168 of file interpolation2d.hpp.
References impl_.
Referenced by QuantLib::SwaptionVolatilityMatrix::locate().
{
            return impl_->locateX(x);
        }
Size QuantLib::Interpolation2D::locateY (Real y) const [inline]
Definition at line 180 of file interpolation2d.hpp.
References impl_.
Referenced by QuantLib::SwaptionVolatilityMatrix::locate().
{
            return impl_->locateY(y);
        }
Real QuantLib::Interpolation2D::operator() (Real x, Real y, bool allowExtrapolation = false) const [inline]
Definition at line 154 of file interpolation2d.hpp.
References checkRange(), and impl_.
{
            checkRange(x,y,allowExtrapolation);
            return impl_->value(x,y);
        }
void QuantLib::Interpolation2D::update () [inline]
Definition at line 189 of file interpolation2d.hpp.
References impl_.
Referenced by QuantLib::KernelInterpolation2D::KernelInterpolation2D(), QuantLib::CapFloorTermVolSurface::performCalculations(), QuantLib::ExtendedBlackVarianceSurface::setInterpolation(), and QuantLib::ExtendedBlackVarianceSurface::update().
                      {
            impl_->calculate();
        }
Real QuantLib::Interpolation2D::xMax () const [inline]
Definition at line 162 of file interpolation2d.hpp.
References impl_.
{
            return impl_->xMax();
        }
Real QuantLib::Interpolation2D::xMin () const [inline]
Definition at line 159 of file interpolation2d.hpp.
References impl_.
{
            return impl_->xMin();
        }
std::vector<Real> QuantLib::Interpolation2D::xValues () const [inline]
Definition at line 165 of file interpolation2d.hpp.
References impl_.
{
            return impl_->xValues();
        }
Real QuantLib::Interpolation2D::yMax () const [inline]
Definition at line 174 of file interpolation2d.hpp.
References impl_.
{
            return impl_->yMax();
        }
Real QuantLib::Interpolation2D::yMin () const [inline]
Definition at line 171 of file interpolation2d.hpp.
References impl_.
{
            return impl_->yMin();
        }
std::vector<Real> QuantLib::Interpolation2D::yValues () const [inline]
Definition at line 177 of file interpolation2d.hpp.
References impl_.
{
            return impl_->yValues();
        }
const Matrix& QuantLib::Interpolation2D::zData () const [inline]
Definition at line 183 of file interpolation2d.hpp.
References impl_.
Referenced by QuantLib::BicubicSpline::BicubicSpline(), QuantLib::BilinearInterpolation::BilinearInterpolation(), QuantLib::KernelInterpolation2D::KernelInterpolation2D(), and QuantLib::Polynomial2DSpline::Polynomial2DSpline().
{
            return impl_->zData();
        }
Member Data Documentation
boost::shared_ptr<Impl> QuantLib::Interpolation2D::impl_ [protected]
Definition at line 63 of file interpolation2d.hpp.
Referenced by QuantLib::BicubicSpline::BicubicSpline(), QuantLib::BilinearInterpolation::BilinearInterpolation(), checkRange(), QuantLib::BicubicSpline::derivativeX(), QuantLib::BicubicSpline::derivativeXY(), QuantLib::BicubicSpline::derivativeY(), QuantLib::FlatExtrapolator2D::FlatExtrapolator2D(), isInRange(), QuantLib::KernelInterpolation2D::KernelInterpolation2D(), locateX(), locateY(), operator()(), QuantLib::Polynomial2DSpline::Polynomial2DSpline(), QuantLib::BicubicSpline::secondDerivativeX(), QuantLib::BicubicSpline::secondDerivativeY(), update(), xMax(), xMin(), xValues(), yMax(), yMin(), yValues(), and zData().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/interpolations/interpolation2d.hpp