QuantLib: QuantLib::ParametricExerciseAdapter Class Reference
QuantLib::ParametricExerciseAdapter Class Reference
#include <parametricexerciseadapter.hpp>
Public Member Functions
ParametricExerciseAdapter (const MarketModelParametricExercise &exercise, const std::vector< std::vector< Real > > &parameters)
std::vector< Time > exerciseTimes () const
std::vector< Time > relevantTimes () const
void reset ()
void nextStep (const CurveState &currentState)
bool exercise (const CurveState &currentState) const
std::auto_ptr
< ExerciseStrategy< CurveState > > clone () const
Private Attributes
Clone
< MarketModelParametricExercise > exercise_
std::vector< std::vector< Real > > parameters_
std::vector< Time > exerciseTimes_
Size currentStep_
Size currentExercise_
std::valarray< bool > isExerciseTime_
std::vector< Size > numberOfVariables_
std::vector< Real > variables_
Detailed Description
Definition at line 33 of file parametricexerciseadapter.hpp.
Constructor & Destructor Documentation
QuantLib::ParametricExerciseAdapter::ParametricExerciseAdapter (const MarketModelParametricExercise & exercise, const std::vector< std::vector< Real > > & parameters)
Definition at line 26 of file parametricexerciseadapter.cpp.
References QuantLib::MarketModelNodeDataProvider::evolution(), QuantLib::EvolutionDescription::evolutionTimes(), exercise_, exerciseTimes_, and isExerciseTime_.
Referenced by clone().
    : exercise_(exercise), parameters_(parameters),
      currentStep_(0), currentExercise_(0),
      isExerciseTime_(exercise.isExerciseTime()),
      numberOfVariables_(exercise.numberOfVariables()) {
        std::vector<Time> evolutionTimes =
            exercise_->evolution().evolutionTimes();
        for (Size i=0; i<evolutionTimes.size(); ++i) {
            if (isExerciseTime_[i])
                exerciseTimes_.push_back(evolutionTimes[i]);
        }
    }
Member Function Documentation
std::auto_ptr< ExerciseStrategy< CurveState > > QuantLib::ParametricExerciseAdapter::clone () const [virtual]
Implements QuantLib::ExerciseStrategy< CurveState >.
Definition at line 70 of file parametricexerciseadapter.cpp.
References ParametricExerciseAdapter().
{
        return std::auto_ptr<ExerciseStrategy<CurveState> >(
                                        new ParametricExerciseAdapter(*this));
    }
bool QuantLib::ParametricExerciseAdapter::exercise (const CurveState & currentState) const [virtual]
Implements QuantLib::ExerciseStrategy< CurveState >.
Definition at line 61 of file parametricexerciseadapter.cpp.
References currentExercise_, QuantLib::ParametricExercise::exercise(), exercise_, numberOfVariables_, parameters_, QuantLib::MarketModelNodeDataProvider::values(), and variables_.
{
        variables_.resize(numberOfVariables_[currentExercise_-1]);
        exercise_->values(currentState, variables_);
        return exercise_->exercise(currentExercise_-1,
                                   parameters_[currentExercise_-1],
                                   variables_);
    }
std::vector< Time > QuantLib::ParametricExerciseAdapter::exerciseTimes () const [virtual]
Implements QuantLib::ExerciseStrategy< CurveState >.
Definition at line 41 of file parametricexerciseadapter.cpp.
References exerciseTimes_.
Referenced by MarketModelTest::testCallableSwapAnderson().
{
        return exerciseTimes_;
    }
void QuantLib::ParametricExerciseAdapter::nextStep (const CurveState & currentState) [virtual]
Implements QuantLib::ExerciseStrategy< CurveState >.
Definition at line 54 of file parametricexerciseadapter.cpp.
References currentExercise_, currentStep_, exercise_, isExerciseTime_, and QuantLib::MarketModelNodeDataProvider::nextStep().
{
        exercise_->nextStep(currentState);
        if (isExerciseTime_[currentStep_])
            ++currentExercise_;
        ++currentStep_;
    }
std::vector< Time > QuantLib::ParametricExerciseAdapter::relevantTimes () const [virtual]
Implements QuantLib::ExerciseStrategy< CurveState >.
Definition at line 45 of file parametricexerciseadapter.cpp.
References QuantLib::MarketModelNodeDataProvider::evolution(), QuantLib::EvolutionDescription::evolutionTimes(), and exercise_.
{
        return exercise_->evolution().evolutionTimes();
    }
void QuantLib::ParametricExerciseAdapter::reset () [virtual]
Implements QuantLib::ExerciseStrategy< CurveState >.
Definition at line 49 of file parametricexerciseadapter.cpp.
References currentExercise_, currentStep_, exercise_, and QuantLib::MarketModelNodeDataProvider::reset().
{
        exercise_->reset();
        currentStep_ = currentExercise_ = 0;
    }
Member Data Documentation
Size QuantLib::ParametricExerciseAdapter::currentExercise_ [private]
Definition at line 48 of file parametricexerciseadapter.hpp.
Referenced by exercise(), nextStep(), and reset().
Size QuantLib::ParametricExerciseAdapter::currentStep_ [private]
Definition at line 48 of file parametricexerciseadapter.hpp.
Referenced by nextStep(), and reset().
Clone<MarketModelParametricExercise> QuantLib::ParametricExerciseAdapter::exercise_ [private]
Definition at line 45 of file parametricexerciseadapter.hpp.
Referenced by exercise(), nextStep(), ParametricExerciseAdapter(), relevantTimes(), and reset().
std::vector<Time> QuantLib::ParametricExerciseAdapter::exerciseTimes_ [private]
Definition at line 47 of file parametricexerciseadapter.hpp.
Referenced by exerciseTimes(), and ParametricExerciseAdapter().
std::valarray<bool> QuantLib::ParametricExerciseAdapter::isExerciseTime_ [private]
Definition at line 49 of file parametricexerciseadapter.hpp.
Referenced by nextStep(), and ParametricExerciseAdapter().
std::vector<Size> QuantLib::ParametricExerciseAdapter::numberOfVariables_ [private]
Definition at line 50 of file parametricexerciseadapter.hpp.
Referenced by exercise().
std::vector<std::vector<Real> > QuantLib::ParametricExerciseAdapter::parameters_ [private]
Definition at line 46 of file parametricexerciseadapter.hpp.
Referenced by exercise().
std::vector<Real> QuantLib::ParametricExerciseAdapter::variables_ [mutable, private]
Definition at line 51 of file parametricexerciseadapter.hpp.
Referenced by exercise().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/callability/parametricexerciseadapter.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/callability/parametricexerciseadapter.cpp