QuantLib: QuantLib::FdmHullWhiteSolver Class Reference
QuantLib::FdmHullWhiteSolver Class Reference
#include <fdmhullwhitesolver.hpp>
Public Member Functions
FdmHullWhiteSolver (const Handle< HullWhite > &model, const FdmSolverDesc &solverDesc, const FdmSchemeDesc &schemeDesc=FdmSchemeDesc::Hundsdorfer())
Real valueAt (Real r) const
Protected Member Functions
void performCalculations () const
Private Attributes
const Handle< HullWhite > model_
const FdmSolverDesc solverDesc_
const FdmSchemeDesc schemeDesc_
boost::shared_ptr< Fdm1DimSolver > solver_
Detailed Description
Definition at line 36 of file fdmhullwhitesolver.hpp.
Constructor & Destructor Documentation
QuantLib::FdmHullWhiteSolver::FdmHullWhiteSolver (const Handle< HullWhite > & model, const FdmSolverDesc & solverDesc, const FdmSchemeDesc & schemeDesc = FdmSchemeDesc::Hundsdorfer())
Definition at line 31 of file fdmhullwhitesolver.cpp.
References model_, and QuantLib::Observer::registerWith().
    : model_(model),
      solverDesc_(solverDesc),
      schemeDesc_(schemeDesc) {
        registerWith(model_);
    }
Member Function Documentation
void QuantLib::FdmHullWhiteSolver::performCalculations () const [protected, virtual]
This method must implement any calculations which must be (re)done in order to calculate the desired results.
Implements QuantLib::LazyObject.
Definition at line 42 of file fdmhullwhitesolver.cpp.
References QuantLib::Handle< T >::currentLink(), QuantLib::FdmSolverDesc::mesher, model_, schemeDesc_, solver_, and solverDesc_.
{
        const boost::shared_ptr<FdmHullWhiteOp> op(
            new FdmHullWhiteOp(solverDesc_.mesher, model_.currentLink(), 0));
        solver_ = boost::shared_ptr<Fdm1DimSolver>(
            new Fdm1DimSolver(solverDesc_, schemeDesc_, op));
    }
Real QuantLib::FdmHullWhiteSolver::valueAt (Real r) const
Definition at line 50 of file fdmhullwhitesolver.cpp.
References QuantLib::LazyObject::calculate(), and solver_.
{
        calculate();
        return solver_->interpolateAt(r);
    }
Member Data Documentation
const Handle<HullWhite> QuantLib::FdmHullWhiteSolver::model_ [private]
Definition at line 49 of file fdmhullwhitesolver.hpp.
Referenced by FdmHullWhiteSolver(), and performCalculations().
const FdmSchemeDesc QuantLib::FdmHullWhiteSolver::schemeDesc_ [private]
Definition at line 51 of file fdmhullwhitesolver.hpp.
Referenced by performCalculations().
boost::shared_ptr<Fdm1DimSolver> QuantLib::FdmHullWhiteSolver::solver_ [mutable, private]
Definition at line 53 of file fdmhullwhitesolver.hpp.
Referenced by performCalculations(), and valueAt().
const FdmSolverDesc QuantLib::FdmHullWhiteSolver::solverDesc_ [private]
Definition at line 50 of file fdmhullwhitesolver.hpp.
Referenced by performCalculations().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/solvers/fdmhullwhitesolver.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/solvers/fdmhullwhitesolver.cpp