QuantLib: QuantLib::YoYInflationIndex Class Reference
QuantLib::YoYInflationIndex Class Reference
Base class for year-on-year inflation indices.
#include <inflationindex.hpp>
Public Member Functions
YoYInflationIndex (const std::string &familyName, const Region &region, bool revised, bool interpolated, bool ratio, Frequency frequency, const Period &availabilityLag, const Currency &currency, const Handle< YoYInflationTermStructure > &ts=Handle< YoYInflationTermStructure >())
Index interface
Rate fixing (const Date &fixingDate, bool forecastTodaysFixing=false) const
Other methods
bool ratio () const
Handle< YoYInflationTermStructure > yoyInflationTermStructure () const
boost::shared_ptr
< YoYInflationIndex > clone (const Handle< YoYInflationTermStructure > &h) const
Private Member Functions
Rate forecastFixing (const Date &fixingDate) const
Private Attributes
bool ratio_
Handle< YoYInflationTermStructure > yoyInflation_
Detailed Description
Base class for year-on-year inflation indices.
These may be genuine indices published on, say, Bloomberg, or "fake" indices that are defined as the ratio of an index at different time points.
Definition at line 175 of file inflationindex.hpp.
Constructor & Destructor Documentation
QuantLib::YoYInflationIndex::YoYInflationIndex (const std::string & familyName, const Region & region, bool revised, bool interpolated, bool ratio, Frequency frequency, const Period & availabilityLag, const Currency & currency, const Handle< YoYInflationTermStructure > & ts = Handle<YoYInflationTermStructure>())
Definition at line 187 of file inflationindex.cpp.
References QuantLib::Observer::registerWith(), and yoyInflation_.
Referenced by clone().
    : InflationIndex(familyName, region, revised, interpolated,
                     frequency, availabilityLag, currency),
      ratio_(ratio), yoyInflation_(yoyInflation) {
        registerWith(yoyInflation_);
    }
Member Function Documentation
boost::shared_ptr< YoYInflationIndex > QuantLib::YoYInflationIndex::clone (const Handle< YoYInflationTermStructure > & h) const
Definition at line 329 of file inflationindex.cpp.
References QuantLib::InflationIndex::availabilityLag_, QuantLib::InflationIndex::currency_, QuantLib::InflationIndex::familyName_, QuantLib::InflationIndex::frequency_, QuantLib::InflationIndex::interpolated_, ratio_, QuantLib::InflationIndex::region_, QuantLib::InflationIndex::revised_, and YoYInflationIndex().
{
        return boost::shared_ptr<YoYInflationIndex>(
                      new YoYInflationIndex(familyName_, region_, revised_,
                                            interpolated_, ratio_, frequency_,
                                            availabilityLag_, currency_, h));
    }
Rate QuantLib::YoYInflationIndex::fixing (const Date & fixingDate, bool forecastTodaysFixing = false) const [virtual]
Warning:
the forecastTodaysFixing parameter (required by the Index interface) is currently ignored.
Implements QuantLib::InflationIndex.
Definition at line 204 of file inflationindex.cpp.
References QuantLib::Calendar::advance(), QuantLib::InflationIndex::availabilityLag_, QuantLib::Settings::evaluationDate(), forecastFixing(), QuantLib::InflationIndex::frequency_, QuantLib::IndexManager::getHistory(), QuantLib::inflationPeriod(), QuantLib::Singleton< Settings >::instance(), QuantLib::Singleton< IndexManager >::instance(), QuantLib::InflationIndex::interpolated(), QuantLib::ModifiedFollowing, QuantLib::InflationIndex::name(), QL_REQUIRE, ratio(), QuantLib::Index::timeSeries(), and QuantLib::Years.
{
        Date today = Settings::instance().evaluationDate();
        Date todayMinusLag = today - availabilityLag_;
        std::pair<Date,Date> lim = inflationPeriod(todayMinusLag, frequency_);
        Date lastFix = lim.first-1;
        Date flatMustForecastOn = lastFix+1;
        Date interpMustForecastOn = lastFix+1 - Period(frequency_);
        if (interpolated() && fixingDate >= interpMustForecastOn) {
            return forecastFixing(fixingDate);
        }
        if (!interpolated() && fixingDate >= flatMustForecastOn) {
            return forecastFixing(fixingDate);
        }
        // four cases with ratio() and interpolated()
        const TimeSeries<Real>& ts = timeSeries();
        if (ratio()) {
            if(interpolated()){ // IS ratio, IS interpolated
                std::pair<Date,Date> lim = inflationPeriod(fixingDate, frequency_);
                Date fixMinus1Y=NullCalendar().advance(fixingDate, -1*Years, ModifiedFollowing);
                std::pair<Date,Date> limBef = inflationPeriod(fixMinus1Y, frequency_);
                Real dp= lim.second + 1 - lim.first;
                Real dpBef=limBef.second + 1 - limBef.first;
                Real dl = fixingDate-lim.first;
                // potentially does not work on 29th Feb
                Real dlBef = fixMinus1Y - limBef.first;
                // get the four relevant fixings
                // recall that they are stored flat for every day
                Rate limFirstFix = ts[lim.first];
                QL_REQUIRE(limFirstFix != Null<Rate>(),
                            "Missing " << name() << " fixing for "
                            << lim.first );
                Rate limSecondFix = ts[lim.second+1];
                QL_REQUIRE(limSecondFix != Null<Rate>(),
                            "Missing " << name() << " fixing for "
                            << lim.second+1 );
                Rate limBefFirstFix = ts[limBef.first];
                QL_REQUIRE(limBefFirstFix != Null<Rate>(),
                            "Missing " << name() << " fixing for "
                            << limBef.first );
                Rate limBefSecondFix =
                IndexManager::instance().getHistory(name())[limBef.second+1];
                QL_REQUIRE(limBefSecondFix != Null<Rate>(),
                            "Missing " << name() << " fixing for "
                            << limBef.second+1 );
                Real linearNow = limFirstFix + (limSecondFix-limFirstFix)*dl/dp;
                Real linearBef = limBefFirstFix + (limBefSecondFix-limBefFirstFix)*dlBef/dpBef;
                Rate wasYES = linearNow / linearBef - 1.0;
                return wasYES;
            } else {    // IS ratio, NOT interpolated
                Rate pastFixing = ts[fixingDate];
                QL_REQUIRE(pastFixing != Null<Rate>(),
                            "Missing " << name() << " fixing for "
                            << fixingDate);
                Date previousDate = fixingDate - 1*Years;
                Rate previousFixing = ts[previousDate];
                QL_REQUIRE(previousFixing != Null<Rate>(),
                           "Missing " << name() << " fixing for "
                           << previousDate );
                return pastFixing/previousFixing - 1.0;
            }
        } else {  // NOT ratio
            if (interpolated()) { // NOT ratio, IS interpolated
                std::pair<Date,Date> lim = inflationPeriod(fixingDate, frequency_);
                Real dp= lim.second + 1 - lim.first;
                Real dl = fixingDate-lim.first;
                Rate limFirstFix = ts[lim.first];
                QL_REQUIRE(limFirstFix != Null<Rate>(),
                            "Missing " << name() << " fixing for "
                            << lim.first );
                Rate limSecondFix = ts[lim.second+1];
                QL_REQUIRE(limSecondFix != Null<Rate>(),
                            "Missing " << name() << " fixing for "
                            << lim.second+1 );
                Real linearNow = limFirstFix + (limSecondFix-limFirstFix)*dl/dp;
                return linearNow;
            } else { // NOT ratio, NOT interpolated
                    // so just flat
                Rate pastFixing = ts[fixingDate];
                QL_REQUIRE(pastFixing != Null<Rate>(),
                           "Missing " << name() << " fixing for "
                           << fixingDate);
                return pastFixing;
            }
        }
        // QL_FAIL("YoYInflationIndex::fixing, should never get here");
    }
Real QuantLib::YoYInflationIndex::forecastFixing (const Date & fixingDate) const [private]
Definition at line 315 of file inflationindex.cpp.
References anonymous_namespace{marketmodel.cpp}::d, QuantLib::Days, QuantLib::InflationIndex::frequency_, QuantLib::inflationPeriod(), QuantLib::InflationIndex::interpolated(), and yoyInflation_.
Referenced by fixing().
{
        Date d;
        if (interpolated()) {
            d = fixingDate;
        } else {
            // if the value is not interpolated use the starting value
            // by internal convention this will be consistent
            std::pair<Date,Date> lim = inflationPeriod(fixingDate, frequency_);
            d = lim.first;
        }
        return yoyInflation_->yoyRate(d,0*Days);
    }
bool QuantLib::YoYInflationIndex::ratio () const [inline]
Definition at line 253 of file inflationindex.hpp.
References ratio_.
Referenced by fixing(), and InflationTest::testYYIndex().
{
        return ratio_;
    }
Handle< YoYInflationTermStructure > QuantLib::YoYInflationIndex::yoyInflationTermStructure () const [inline]
Definition at line 258 of file inflationindex.hpp.
References yoyInflation_.
{
        return yoyInflation_;
    }
Member Data Documentation
bool QuantLib::YoYInflationIndex::ratio_ [private]
Definition at line 206 of file inflationindex.hpp.
Referenced by clone(), and ratio().
Handle<YoYInflationTermStructure> QuantLib::YoYInflationIndex::yoyInflation_ [private]
Definition at line 207 of file inflationindex.hpp.
Referenced by forecastFixing(), YoYInflationIndex(), and yoyInflationTermStructure().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/indexes/inflationindex.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/indexes/inflationindex.cpp