QuantLib: QuantLib::HestonModel Class Reference
QuantLib::HestonModel Class Reference
Heston model for the stochastic volatility of an asset.
#include <hestonmodel.hpp>
Classes
class FellerConstraint
Public Member Functions
HestonModel (const boost::shared_ptr< HestonProcess > &process)
Real theta () const
Real kappa () const
Real sigma () const
Real rho () const
Real v0 () const
boost::shared_ptr< HestonProcess > process () const
Protected Member Functions
void generateArguments ()
Protected Attributes
boost::shared_ptr< HestonProcess > process_
Detailed Description
Heston model for the stochastic volatility of an asset.
References:
Heston, Steven L., 1993. A Closed-Form Solution for Options with Stochastic Volatility with Applications to Bond and Currency Options. The review of Financial Studies, Volume 6, Issue 2, 327-343.
Test:
calibration is tested against known good values.
Definition at line 42 of file hestonmodel.hpp.
Constructor & Destructor Documentation
QuantLib::HestonModel::HestonModel (const boost::shared_ptr< HestonProcess > & process)
Definition at line 25 of file hestonmodel.cpp.
References QuantLib::CalibratedModel::arguments_, generateArguments(), process_, and QuantLib::Observer::registerWith().
    : CalibratedModel(5), process_(process) {
        arguments_[0] = ConstantParameter(process->theta(),
                                          PositiveConstraint());
        arguments_[1] = ConstantParameter(process->kappa(),
                                          PositiveConstraint());
        arguments_[2] = ConstantParameter(process->sigma(),
                                          PositiveConstraint());
        arguments_[3] = ConstantParameter(process->rho(),
                                          BoundaryConstraint(-1.0, 1.0));
        arguments_[4] = ConstantParameter(process->v0(),
                                          PositiveConstraint());
        generateArguments();
        registerWith(process_->riskFreeRate());
        registerWith(process_->dividendYield());
        registerWith(process_->s0());
    }
Member Function Documentation
void QuantLib::HestonModel::generateArguments () [protected, virtual]
Reimplemented from QuantLib::CalibratedModel.
Reimplemented in QuantLib::BatesModel.
Definition at line 44 of file hestonmodel.cpp.
References kappa(), process_, rho(), sigma(), theta(), and v0().
Referenced by HestonModel().
{
        process_.reset(new HestonProcess(process_->riskFreeRate(),
                                         process_->dividendYield(),
                                         process_->s0(),
                                         v0(), kappa(), theta(),
                                         sigma(), rho()));
    }
Real QuantLib::HestonModel::kappa () const [inline]
Definition at line 49 of file hestonmodel.hpp.
References QuantLib::CalibratedModel::arguments_.
Referenced by QuantLib::BatesModel::generateArguments(), generateArguments(), and QuantLib::HestonModel::FellerConstraint::Impl::test().
{ return arguments_[1](0.0); }
boost::shared_ptr<HestonProcess> QuantLib::HestonModel::process () const [inline]
Definition at line 58 of file hestonmodel.hpp.
References process_.
{ return process_; }
Real QuantLib::HestonModel::rho () const [inline]
Definition at line 53 of file hestonmodel.hpp.
References QuantLib::CalibratedModel::arguments_.
Referenced by QuantLib::BatesModel::generateArguments(), and generateArguments().
{ return arguments_[3](0.0); }
Real QuantLib::HestonModel::sigma () const [inline]
Definition at line 51 of file hestonmodel.hpp.
References QuantLib::CalibratedModel::arguments_.
Referenced by QuantLib::BatesModel::generateArguments(), generateArguments(), and QuantLib::HestonModel::FellerConstraint::Impl::test().
{ return arguments_[2](0.0); }
Real QuantLib::HestonModel::theta () const [inline]
Definition at line 47 of file hestonmodel.hpp.
References QuantLib::CalibratedModel::arguments_.
Referenced by QuantLib::BatesModel::generateArguments(), generateArguments(), and QuantLib::HestonModel::FellerConstraint::Impl::test().
{ return arguments_[0](0.0); }
Real QuantLib::HestonModel::v0 () const [inline]
Definition at line 55 of file hestonmodel.hpp.
References QuantLib::CalibratedModel::arguments_.
Referenced by QuantLib::BatesModel::generateArguments(), and generateArguments().
{ return arguments_[4](0.0); }
Member Data Documentation
boost::shared_ptr<HestonProcess> QuantLib::HestonModel::process_ [protected]
Definition at line 63 of file hestonmodel.hpp.
Referenced by QuantLib::BatesModel::generateArguments(), generateArguments(), HestonModel(), and process().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/equity/hestonmodel.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/equity/hestonmodel.cpp