QuantLib: QuantLib::MarketModelPathwiseCoterminalSwaptionsNumericalDeflated Class Reference
QuantLib::MarketModelPathwiseCoterminalSwaptionsNumericalDeflated Class Reference
#include <pathwiseproductswaption.hpp>
Public Member Functions
MarketModelPathwiseCoterminalSwaptionsNumericalDeflated (const std::vector< Time > &rateTimes, const std::vector< Rate > &strikes, Real bumpSize_)
virtual ~MarketModelPathwiseCoterminalSwaptionsNumericalDeflated ()
virtual std::vector< Size > suggestedNumeraires () const
virtual const
EvolutionDescription & evolution () const
virtual std::vector< Time > possibleCashFlowTimes () const
virtual Size numberOfProducts () const
virtual Size maxNumberOfCashFlowsPerProductPerStep () const
virtual bool alreadyDeflated () const
virtual void reset ()
during simulation put product at start of path
virtual bool nextTimeStep (const CurveState &currentState, std::vector< Size > &numberCashFlowsThisStep, std::vector< std::vector< MarketModelPathwiseMultiProduct::CashFlow > > &cashFlowsGenerated)
return value indicates whether path is finished, TRUE means done
virtual std::auto_ptr
< MarketModelPathwiseMultiProduct > clone () const
returns a newly-allocated copy of itself
Private Attributes
std::vector< Real > rateTimes_
std::vector< Rate > strikes_
Size numberRates_
Size currentIndex_
EvolutionDescription evolution_
Real bumpSize_
LMMCurveState up_
LMMCurveState down_
std::vector< Rate > forwards_
Detailed Description
Easiest way to test MarketModelPathwiseCoterminalSwaptionsDeflated is by doing a numerical differentiation version.
Definition at line 86 of file pathwiseproductswaption.hpp.
Constructor & Destructor Documentation
QuantLib::MarketModelPathwiseCoterminalSwaptionsNumericalDeflated::MarketModelPathwiseCoterminalSwaptionsNumericalDeflated (const std::vector< Time > & rateTimes, const std::vector< Rate > & strikes, Real bumpSize_)
Definition at line 142 of file pathwiseproductswaption.cpp.
References QuantLib::checkIncreasingTimes(), evolution_, numberRates_, QL_REQUIRE, and rateTimes_.
Referenced by clone().
    : rateTimes_(rateTimes),
      strikes_(strikes) ,
      numberRates_(rateTimes.size()-1), bumpSize_(bumpSize), up_(rateTimes), down_(rateTimes), forwards_(numberRates_)
    {
        checkIncreasingTimes(rateTimes);
        std::vector<Time> evolTimes(rateTimes_);
        evolTimes.pop_back();
        QL_REQUIRE(evolTimes.size()==numberRates_,
                   "rateTimes.size()<> numberOfRates+1");
        QL_REQUIRE(strikes.size()==numberRates_,
                   "strikes.size()<> numberOfRates");
        evolution_ = EvolutionDescription(rateTimes,evolTimes);
    }
virtual QuantLib::MarketModelPathwiseCoterminalSwaptionsNumericalDeflated::~MarketModelPathwiseCoterminalSwaptionsNumericalDeflated () [inline, virtual]
Definition at line 95 of file pathwiseproductswaption.hpp.
{}
Member Function Documentation
bool QuantLib::MarketModelPathwiseCoterminalSwaptionsNumericalDeflated::alreadyDeflated () const [virtual]
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 137 of file pathwiseproductswaption.cpp.
    {
        return false;
    }
std::auto_ptr< MarketModelPathwiseMultiProduct > QuantLib::MarketModelPathwiseCoterminalSwaptionsNumericalDeflated::clone () const [virtual]
returns a newly-allocated copy of itself
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 213 of file pathwiseproductswaption.cpp.
References MarketModelPathwiseCoterminalSwaptionsNumericalDeflated().
    {
        return std::auto_ptr<MarketModelPathwiseMultiProduct>(
                                                new MarketModelPathwiseCoterminalSwaptionsNumericalDeflated(*this));
    }
const EvolutionDescription & QuantLib::MarketModelPathwiseCoterminalSwaptionsNumericalDeflated::evolution () const [virtual]
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 228 of file pathwiseproductswaption.cpp.
References evolution_.
    {
        return evolution_;
    }
Size QuantLib::MarketModelPathwiseCoterminalSwaptionsNumericalDeflated::maxNumberOfCashFlowsPerProductPerStep () const [virtual]
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 243 of file pathwiseproductswaption.cpp.
    {
        return 1;
    }
bool QuantLib::MarketModelPathwiseCoterminalSwaptionsNumericalDeflated::nextTimeStep (const CurveState & currentState, std::vector< Size > & numberCashFlowsThisStep, std::vector< std::vector< MarketModelPathwiseMultiProduct::CashFlow > > & cashFlowsGenerated) [virtual]
return value indicates whether path is finished, TRUE means done
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 164 of file pathwiseproductswaption.cpp.
References bumpSize_, QuantLib::CurveState::coterminalSwapAnnuity(), QuantLib::LMMCurveState::coterminalSwapAnnuity(), QuantLib::LMMCurveState::coterminalSwapRate(), QuantLib::CurveState::coterminalSwapRate(), currentIndex_, down_, QuantLib::CurveState::forwardRates(), forwards_, numberRates_, QuantLib::LMMCurveState::setOnForwardRates(), strikes_, and up_.
    {
        Rate swapRate = currentState.coterminalSwapRate(currentIndex_);
        cashFlowsGenerated[currentIndex_][0].timeIndex = currentIndex_;
        Real annuity = currentState.coterminalSwapAnnuity(currentIndex_,currentIndex_);
        cashFlowsGenerated[currentIndex_][0].amount[0] =
            (swapRate-strikes_[currentIndex_])*annuity;
        std::fill(numberCashFlowsThisStep.begin(),
                  numberCashFlowsThisStep.end(),0);
        if (  cashFlowsGenerated[currentIndex_][0].amount[0]  >0)
        {
            numberCashFlowsThisStep[currentIndex_] = 1;
            for (Size i=1; i <= numberRates_; ++i)
                cashFlowsGenerated[currentIndex_][0].amount[i] =0;
            for (Size k=currentIndex_; k < numberRates_; ++k)
            {
                forwards_ = currentState.forwardRates();
                forwards_[k] += bumpSize_;
                up_.setOnForwardRates(forwards_);
                forwards_[k] -= bumpSize_;
                forwards_[k] -= bumpSize_;
                down_.setOnForwardRates(forwards_);
                Real upSR = up_.coterminalSwapRate(currentIndex_);
                Real upAnnuity = up_.coterminalSwapAnnuity(currentIndex_,currentIndex_);
                Real upValue = (upSR -  strikes_[currentIndex_])*  upAnnuity;
                Real downSR = down_.coterminalSwapRate(currentIndex_);
                Real downAnnuity = down_.coterminalSwapAnnuity(currentIndex_,currentIndex_);
                Real downValue = (downSR -  strikes_[currentIndex_])*  downAnnuity;
                Real deriv = (upValue - downValue)/(2.0*bumpSize_);
                cashFlowsGenerated[currentIndex_][0].amount[k+1]  = deriv;
            }
        }
        ++currentIndex_;
        return (currentIndex_ == strikes_.size());
    }
Size QuantLib::MarketModelPathwiseCoterminalSwaptionsNumericalDeflated::numberOfProducts () const [virtual]
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 238 of file pathwiseproductswaption.cpp.
References numberRates_.
    {
           return numberRates_;
    }
std::vector< Time > QuantLib::MarketModelPathwiseCoterminalSwaptionsNumericalDeflated::possibleCashFlowTimes () const [virtual]
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 233 of file pathwiseproductswaption.cpp.
References rateTimes_.
    {
        return rateTimes_;
    }
void QuantLib::MarketModelPathwiseCoterminalSwaptionsNumericalDeflated::reset () [virtual]
during simulation put product at start of path
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 249 of file pathwiseproductswaption.cpp.
References currentIndex_.
    {
        currentIndex_=0;
    }
std::vector< Size > QuantLib::MarketModelPathwiseCoterminalSwaptionsNumericalDeflated::suggestedNumeraires () const [virtual]
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 219 of file pathwiseproductswaption.cpp.
References numberRates_.
    {
            std::vector<Size> numeraires(numberRates_);
            for (Size i=0; i < numberRates_; ++i)
                numeraires[i] = i;
            return numeraires;
    }
Member Data Documentation
Real QuantLib::MarketModelPathwiseCoterminalSwaptionsNumericalDeflated::bumpSize_ [private]
Definition at line 128 of file pathwiseproductswaption.hpp.
Referenced by nextTimeStep().
Size QuantLib::MarketModelPathwiseCoterminalSwaptionsNumericalDeflated::currentIndex_ [private]
Definition at line 124 of file pathwiseproductswaption.hpp.
Referenced by nextTimeStep(), and reset().
LMMCurveState QuantLib::MarketModelPathwiseCoterminalSwaptionsNumericalDeflated::down_ [private]
Definition at line 130 of file pathwiseproductswaption.hpp.
Referenced by nextTimeStep().
EvolutionDescription QuantLib::MarketModelPathwiseCoterminalSwaptionsNumericalDeflated::evolution_ [private]
Definition at line 126 of file pathwiseproductswaption.hpp.
Referenced by evolution(), and MarketModelPathwiseCoterminalSwaptionsNumericalDeflated().
std::vector<Rate> QuantLib::MarketModelPathwiseCoterminalSwaptionsNumericalDeflated::forwards_ [private]
Definition at line 131 of file pathwiseproductswaption.hpp.
Referenced by nextTimeStep().
Size QuantLib::MarketModelPathwiseCoterminalSwaptionsNumericalDeflated::numberRates_ [private]
Definition at line 122 of file pathwiseproductswaption.hpp.
Referenced by MarketModelPathwiseCoterminalSwaptionsNumericalDeflated(), nextTimeStep(), numberOfProducts(), and suggestedNumeraires().
std::vector<Real> QuantLib::MarketModelPathwiseCoterminalSwaptionsNumericalDeflated::rateTimes_ [private]
Definition at line 120 of file pathwiseproductswaption.hpp.
Referenced by MarketModelPathwiseCoterminalSwaptionsNumericalDeflated(), and possibleCashFlowTimes().
std::vector<Rate> QuantLib::MarketModelPathwiseCoterminalSwaptionsNumericalDeflated::strikes_ [private]
Definition at line 121 of file pathwiseproductswaption.hpp.
Referenced by nextTimeStep().
LMMCurveState QuantLib::MarketModelPathwiseCoterminalSwaptionsNumericalDeflated::up_ [private]
Definition at line 129 of file pathwiseproductswaption.hpp.
Referenced by nextTimeStep().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/products/pathwise/pathwiseproductswaption.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/products/pathwise/pathwiseproductswaption.cpp