QuantLib: QuantLib::Constraint Class Reference
QuantLib::Constraint Class Reference
Base constraint class.
#include <constraint.hpp>
Classes
class Impl
Base class for constraint implementations.
Public Member Functions
bool empty () const
bool test (const Array &p) const
Real update (Array &p, const Array &direction, Real beta)
Constraint (const boost::shared_ptr< Impl > &impl=boost::shared_ptr< Impl >())
Protected Attributes
boost::shared_ptr< Impl > impl_
Detailed Description
Base constraint class.
Definition at line 32 of file constraint.hpp.
Constructor & Destructor Documentation
QuantLib::Constraint::Constraint (const boost::shared_ptr< Impl > & impl = boost::shared_ptr<Impl>())
Definition at line 24 of file constraint.cpp.
    : impl_(impl) {}
Member Function Documentation
bool QuantLib::Constraint::empty () const [inline]
Definition at line 43 of file constraint.hpp.
References impl_.
Referenced by QuantLib::CalibratedModel::calibrate().
{ return !impl_; }
bool QuantLib::Constraint::test (const Array & p) const [inline]
Definition at line 44 of file constraint.hpp.
References impl_.
Referenced by QuantLib::Simplex::extrapolate(), QuantLib::LevenbergMarquardt::fcn(), QuantLib::CompositeConstraint::Impl::test(), QuantLib::Parameter::testParams(), update(), and QuantLib::LineSearch::update().
{ return impl_->test(p); }
Real QuantLib::Constraint::update (Array & p, const Array & direction, Real beta)
Definition at line 27 of file constraint.cpp.
References anonymous_namespace{marketmodel.cpp}::beta, QL_FAIL, and test().
Referenced by QuantLib::Simplex::minimize().
{
        Real diff=beta;
        Array newParams = params + diff*direction;
        bool valid = test(newParams);
        Integer icount = 0;
        while (!valid) {
            if (icount > 200)
                QL_FAIL("can't update parameter vector");
            diff *= 0.5;
            icount ++;
            newParams = params + diff*direction;
            valid = test(newParams);
        }
        params += diff*direction;
        return diff;
    }
Member Data Documentation
boost::shared_ptr<Impl> QuantLib::Constraint::impl_ [protected]
Definition at line 41 of file constraint.hpp.
Referenced by empty(), and test().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/optimization/constraint.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/math/optimization/constraint.cpp