QuantLib: QuantLib::CmsLeg Class Reference
QuantLib::CmsLeg Class Reference
helper class building a sequence of capped/floored cms-rate coupons
#include <cmscoupon.hpp>
Public Member Functions
CmsLeg (const Schedule &schedule, const boost::shared_ptr< SwapIndex > &swapIndex)
CmsLeg & withNotionals (Real notional)
CmsLeg & withNotionals (const std::vector< Real > &notionals)
CmsLeg & withPaymentDayCounter (const DayCounter &)
CmsLeg & withPaymentAdjustment (BusinessDayConvention)
CmsLeg & withFixingDays (Natural fixingDays)
CmsLeg & withFixingDays (const std::vector< Natural > &fixingDays)
CmsLeg & withGearings (Real gearing)
CmsLeg & withGearings (const std::vector< Real > &gearings)
CmsLeg & withSpreads (Spread spread)
CmsLeg & withSpreads (const std::vector< Spread > &spreads)
CmsLeg & withCaps (Rate cap)
CmsLeg & withCaps (const std::vector< Rate > &caps)
CmsLeg & withFloors (Rate floor)
CmsLeg & withFloors (const std::vector< Rate > &floors)
CmsLeg & inArrears (bool flag=true)
CmsLeg & withZeroPayments (bool flag=true)
operator Leg () const
Private Attributes
Schedule schedule_
boost::shared_ptr< SwapIndex > swapIndex_
std::vector< Real > notionals_
DayCounter paymentDayCounter_
BusinessDayConvention paymentAdjustment_
std::vector< Natural > fixingDays_
std::vector< Real > gearings_
std::vector< Spread > spreads_
std::vector< Rate > caps_
std::vector< Rate > floors_
bool inArrears_
bool zeroPayments_
Detailed Description
helper class building a sequence of capped/floored cms-rate coupons
Definition at line 69 of file cmscoupon.hpp.
Constructor & Destructor Documentation
QuantLib::CmsLeg::CmsLeg (const Schedule & schedule, const boost::shared_ptr< SwapIndex > & swapIndex)
Definition at line 56 of file cmscoupon.cpp.
    : schedule_(schedule), swapIndex_(swapIndex),
      paymentAdjustment_(Following),
      inArrears_(false), zeroPayments_(false) {}
Member Function Documentation
CmsLeg & QuantLib::CmsLeg::inArrears (bool flag = true)
Definition at line 132 of file cmscoupon.cpp.
References inArrears_.
Referenced by QuantLib::AmortizingCmsRateBond::AmortizingCmsRateBond(), QuantLib::CmsRateBond::CmsRateBond(), AssetSwapTest::testGenericBondImplied(), AssetSwapTest::testMASWWithGenericBond(), AssetSwapTest::testSpecializedBondVsGenericBond(), AssetSwapTest::testSpecializedBondVsGenericBondUsingAsw(), and AssetSwapTest::testZSpreadWithGenericBond().
{
        inArrears_ = flag;
        return *this;
    }
QuantLib::CmsLeg::operator Leg () const
Definition at line 142 of file cmscoupon.cpp.
References caps_, fixingDays_, floors_, gearings_, inArrears_, notionals_, paymentAdjustment_, paymentDayCounter_, schedule_, spreads_, swapIndex_, and zeroPayments_.
{
        return FloatingLeg<SwapIndex, CmsCoupon, CappedFlooredCmsCoupon>(
                         schedule_, notionals_, swapIndex_, paymentDayCounter_,
                         paymentAdjustment_, fixingDays_, gearings_, spreads_,
                         caps_, floors_, inArrears_, zeroPayments_);
   }
CmsLeg & QuantLib::CmsLeg::withCaps (Rate cap)
Definition at line 112 of file cmscoupon.cpp.
References caps_.
Referenced by QuantLib::AmortizingCmsRateBond::AmortizingCmsRateBond(), QuantLib::CmsRateBond::CmsRateBond(), QuantLib::MakeCms::operator boost::shared_ptr< Swap >(), AssetSwapTest::testGenericBondImplied(), AssetSwapTest::testMASWWithGenericBond(), AssetSwapTest::testSpecializedBondVsGenericBond(), AssetSwapTest::testSpecializedBondVsGenericBondUsingAsw(), and AssetSwapTest::testZSpreadWithGenericBond().
{
        caps_ = std::vector<Rate>(1, cap);
        return *this;
    }
CmsLeg & QuantLib::CmsLeg::withCaps (const std::vector< Rate > & caps)
Definition at line 117 of file cmscoupon.cpp.
References caps_.
{
        caps_ = caps;
        return *this;
    }
CmsLeg & QuantLib::CmsLeg::withFixingDays (Natural fixingDays)
Definition at line 82 of file cmscoupon.cpp.
References fixingDays_.
Referenced by QuantLib::AmortizingCmsRateBond::AmortizingCmsRateBond(), QuantLib::CmsRateBond::CmsRateBond(), QuantLib::MakeCms::operator boost::shared_ptr< Swap >(), AssetSwapTest::testGenericBondImplied(), AssetSwapTest::testMASWWithGenericBond(), AssetSwapTest::testSpecializedBondVsGenericBond(), AssetSwapTest::testSpecializedBondVsGenericBondUsingAsw(), and AssetSwapTest::testZSpreadWithGenericBond().
{
        fixingDays_ = std::vector<Natural>(1, fixingDays);
        return *this;
    }
CmsLeg & QuantLib::CmsLeg::withFixingDays (const std::vector< Natural > & fixingDays)
Definition at line 87 of file cmscoupon.cpp.
References fixingDays_.
{
        fixingDays_ = fixingDays;
        return *this;
    }
CmsLeg & QuantLib::CmsLeg::withFloors (Rate floor)
Definition at line 122 of file cmscoupon.cpp.
References floors_.
Referenced by QuantLib::AmortizingCmsRateBond::AmortizingCmsRateBond(), QuantLib::CmsRateBond::CmsRateBond(), QuantLib::MakeCms::operator boost::shared_ptr< Swap >(), AssetSwapTest::testGenericBondImplied(), AssetSwapTest::testMASWWithGenericBond(), AssetSwapTest::testSpecializedBondVsGenericBond(), AssetSwapTest::testSpecializedBondVsGenericBondUsingAsw(), and AssetSwapTest::testZSpreadWithGenericBond().
{
        floors_ = std::vector<Rate>(1, floor);
        return *this;
    }
CmsLeg & QuantLib::CmsLeg::withFloors (const std::vector< Rate > & floors)
Definition at line 127 of file cmscoupon.cpp.
References floors_.
{
        floors_ = floors;
        return *this;
    }
CmsLeg & QuantLib::CmsLeg::withGearings (Real gearing)
Definition at line 92 of file cmscoupon.cpp.
References gearings_.
Referenced by QuantLib::AmortizingCmsRateBond::AmortizingCmsRateBond(), QuantLib::CmsRateBond::CmsRateBond(), AssetSwapTest::testGenericBondImplied(), AssetSwapTest::testMASWWithGenericBond(), AssetSwapTest::testSpecializedBondVsGenericBond(), AssetSwapTest::testSpecializedBondVsGenericBondUsingAsw(), and AssetSwapTest::testZSpreadWithGenericBond().
{
        gearings_ = std::vector<Real>(1, gearing);
        return *this;
    }
CmsLeg & QuantLib::CmsLeg::withGearings (const std::vector< Real > & gearings)
Definition at line 97 of file cmscoupon.cpp.
References gearings_.
{
        gearings_ = gearings;
        return *this;
    }
CmsLeg & QuantLib::CmsLeg::withNotionals (Real notional)
Definition at line 62 of file cmscoupon.cpp.
References notionals_.
Referenced by QuantLib::AmortizingCmsRateBond::AmortizingCmsRateBond(), QuantLib::CmsRateBond::CmsRateBond(), QuantLib::MakeCms::operator boost::shared_ptr< Swap >(), AssetSwapTest::testGenericBondImplied(), AssetSwapTest::testMASWWithGenericBond(), AssetSwapTest::testSpecializedBondVsGenericBond(), AssetSwapTest::testSpecializedBondVsGenericBondUsingAsw(), and AssetSwapTest::testZSpreadWithGenericBond().
{
        notionals_ = std::vector<Real>(1, notional);
        return *this;
    }
CmsLeg & QuantLib::CmsLeg::withNotionals (const std::vector< Real > & notionals)
Definition at line 67 of file cmscoupon.cpp.
References notionals_.
{
        notionals_ = notionals;
        return *this;
    }
CmsLeg & QuantLib::CmsLeg::withPaymentAdjustment (BusinessDayConvention convention)
Definition at line 77 of file cmscoupon.cpp.
References paymentAdjustment_.
Referenced by QuantLib::AmortizingCmsRateBond::AmortizingCmsRateBond(), QuantLib::CmsRateBond::CmsRateBond(), and QuantLib::MakeCms::operator boost::shared_ptr< Swap >().
{
        paymentAdjustment_ = convention;
        return *this;
    }
CmsLeg & QuantLib::CmsLeg::withPaymentDayCounter (const DayCounter & dayCounter)
Definition at line 72 of file cmscoupon.cpp.
References anonymous_namespace{marketmodel.cpp}::dayCounter, and paymentDayCounter_.
Referenced by QuantLib::AmortizingCmsRateBond::AmortizingCmsRateBond(), QuantLib::CmsRateBond::CmsRateBond(), QuantLib::MakeCms::operator boost::shared_ptr< Swap >(), AssetSwapTest::testGenericBondImplied(), AssetSwapTest::testMASWWithGenericBond(), AssetSwapTest::testSpecializedBondVsGenericBond(), AssetSwapTest::testSpecializedBondVsGenericBondUsingAsw(), and AssetSwapTest::testZSpreadWithGenericBond().
{
        paymentDayCounter_ = dayCounter;
        return *this;
    }
CmsLeg & QuantLib::CmsLeg::withSpreads (Spread spread)
Definition at line 102 of file cmscoupon.cpp.
References spreads_.
Referenced by QuantLib::AmortizingCmsRateBond::AmortizingCmsRateBond(), QuantLib::CmsRateBond::CmsRateBond(), and QuantLib::MakeCms::operator boost::shared_ptr< Swap >().
{
        spreads_ = std::vector<Spread>(1, spread);
        return *this;
    }
CmsLeg & QuantLib::CmsLeg::withSpreads (const std::vector< Spread > & spreads)
Definition at line 107 of file cmscoupon.cpp.
References spreads_.
{
        spreads_ = spreads;
        return *this;
    }
CmsLeg & QuantLib::CmsLeg::withZeroPayments (bool flag = true)
Definition at line 137 of file cmscoupon.cpp.
References zeroPayments_.
{
        zeroPayments_ = flag;
        return *this;
    }
Member Data Documentation
std::vector<Rate> QuantLib::CmsLeg::caps_ [private]
Definition at line 99 of file cmscoupon.hpp.
Referenced by operator Leg(), and withCaps().
std::vector<Natural> QuantLib::CmsLeg::fixingDays_ [private]
Definition at line 96 of file cmscoupon.hpp.
Referenced by operator Leg(), and withFixingDays().
std::vector<Rate> QuantLib::CmsLeg::floors_ [private]
Definition at line 99 of file cmscoupon.hpp.
Referenced by operator Leg(), and withFloors().
std::vector<Real> QuantLib::CmsLeg::gearings_ [private]
Definition at line 97 of file cmscoupon.hpp.
Referenced by operator Leg(), and withGearings().
bool QuantLib::CmsLeg::inArrears_ [private]
Definition at line 100 of file cmscoupon.hpp.
Referenced by inArrears(), and operator Leg().
std::vector<Real> QuantLib::CmsLeg::notionals_ [private]
Definition at line 93 of file cmscoupon.hpp.
Referenced by operator Leg(), and withNotionals().
BusinessDayConvention QuantLib::CmsLeg::paymentAdjustment_ [private]
Definition at line 95 of file cmscoupon.hpp.
Referenced by operator Leg(), and withPaymentAdjustment().
DayCounter QuantLib::CmsLeg::paymentDayCounter_ [private]
Definition at line 94 of file cmscoupon.hpp.
Referenced by operator Leg(), and withPaymentDayCounter().
Schedule QuantLib::CmsLeg::schedule_ [private]
Definition at line 91 of file cmscoupon.hpp.
Referenced by operator Leg().
std::vector<Spread> QuantLib::CmsLeg::spreads_ [private]
Definition at line 98 of file cmscoupon.hpp.
Referenced by operator Leg(), and withSpreads().
boost::shared_ptr<SwapIndex> QuantLib::CmsLeg::swapIndex_ [private]
Definition at line 92 of file cmscoupon.hpp.
Referenced by operator Leg().
bool QuantLib::CmsLeg::zeroPayments_ [private]
Definition at line 100 of file cmscoupon.hpp.
Referenced by operator Leg(), and withZeroPayments().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/cmscoupon.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/cmscoupon.cpp