QuantLib: QuantLib::EnergyFuture Class Reference
QuantLib::EnergyFuture Class Reference
Energy future.
#include <energyfuture.hpp>
Public Member Functions
EnergyFuture (Integer buySell, const Quantity &quantity, const CommodityUnitCost &tradePrice, const boost::shared_ptr< CommodityIndex > &index, const CommodityType &commodityType, const boost::shared_ptr< SecondaryCosts > &secondaryCosts)
bool isExpired () const
returns whether the instrument might have value greater than zero.
Quantity quantity () const
const CommodityUnitCost & tradePrice () const
const boost::shared_ptr
< CommodityIndex > index () const
Protected Member Functions
void performCalculations () const
Protected Attributes
Integer buySell_
Quantity quantity_
CommodityUnitCost tradePrice_
boost::shared_ptr< CommodityIndex > index_
Detailed Description
Energy future.
Definition at line 34 of file energyfuture.hpp.
Constructor & Destructor Documentation
QuantLib::EnergyFuture::EnergyFuture (Integer buySell, const Quantity & quantity, const CommodityUnitCost & tradePrice, const boost::shared_ptr< CommodityIndex > & index, const CommodityType & commodityType, const boost::shared_ptr< SecondaryCosts > & secondaryCosts)
Definition at line 26 of file energyfuture.cpp.
References index_, QuantLib::Singleton< Settings >::instance(), and QuantLib::Observer::registerWith().
    : EnergyCommodity(commodityType, secondaryCosts),
      buySell_(buySell), quantity_(quantity), tradePrice_(tradePrice),
      index_(index) {
        registerWith(Settings::instance().evaluationDate());
        registerWith(index_);
    }
Member Function Documentation
const boost::shared_ptr<CommodityIndex> QuantLib::EnergyFuture::index () const [inline]
Definition at line 45 of file energyfuture.hpp.
References index_.
{ return index_; }
bool QuantLib::EnergyFuture::isExpired () const [virtual]
returns whether the instrument might have value greater than zero.
Implements QuantLib::Instrument.
Definition at line 39 of file energyfuture.cpp.
{
        return false;
    }
void QuantLib::EnergyFuture::performCalculations () const [protected, virtual]
In case a pricing engine is not used, this method must be overridden to perform the actual calculations and set any needed results. In case a pricing engine is used, the default implementation can be used.
Reimplemented from QuantLib::Instrument.
Definition at line 43 of file energyfuture.cpp.
References QuantLib::Instrument::additionalResults_, QuantLib::Commodity::addPricingError(), QuantLib::CommodityUnitCost::amount(), QuantLib::Quantity::amount(), buySell_, QuantLib::EnergyCommodity::calculateFxConversionFactor(), QuantLib::EnergyCommodity::calculateSecondaryCostAmounts(), QuantLib::EnergyCommodity::calculateUomConversionFactor(), QuantLib::Quantity::commodityType(), QuantLib::CommoditySettings::currency(), QuantLib::Money::currency(), QuantLib::Settings::evaluationDate(), index_, QuantLib::Singleton< Settings >::instance(), QuantLib::Singleton< CommoditySettings >::instance(), QuantLib::io::iso_date(), QuantLib::Instrument::NPV_, QL_REQUIRE, quantity_, QuantLib::Commodity::secondaryCostAmounts_, tradePrice_, QuantLib::CommodityUnitCost::unitOfMeasure(), QuantLib::CommoditySettings::unitOfMeasure(), QuantLib::Quantity::unitOfMeasure(), QuantLib::Money::value(), and QuantLib::PricingError::Warning.
{
        NPV_ = 0.0;
        additionalResults_.clear();
        Date evaluationDate = Settings::instance().evaluationDate();
        const Currency& baseCurrency =
            CommoditySettings::instance().currency();
        const UnitOfMeasure baseUnitOfMeasure =
            CommoditySettings::instance().unitOfMeasure();
        Real quantityUomConversionFactor =
            calculateUomConversionFactor(
                           quantity_.commodityType(),
                           baseUnitOfMeasure,
                           quantity_.unitOfMeasure()) * index_->lotQuantity();
        Real indexUomConversionFactor =
            calculateUomConversionFactor(index_->commodityType(),
                                         index_->unitOfMeasure(),
                                         baseUnitOfMeasure);
        Real tradePriceUomConversionFactor =
            calculateUomConversionFactor(quantity_.commodityType(),
                                         tradePrice_.unitOfMeasure(),
                                         baseUnitOfMeasure);
        Real tradePriceFxConversionFactor =
            calculateFxConversionFactor(tradePrice_.amount().currency(),
                                        baseCurrency, evaluationDate);
        Real indexPriceFxConversionFactor =
            calculateFxConversionFactor(index_->currency(), baseCurrency,
                                        evaluationDate);
        Real quoteValue = 0;
        Date lastQuoteDate = index_->lastQuoteDate();
        if (lastQuoteDate >= evaluationDate - 1) {
            quoteValue = index_->price(evaluationDate);
        } else {
            quoteValue = index_->forwardPrice(evaluationDate);
            std::ostringstream message;
            message << "curve [" << index_->name()
                    << "] has last quote date of "
                    << io::iso_date(lastQuoteDate)
                    << " using forward price from ["
                    << index_->forwardCurve()->name() << "]";
            addPricingError(PricingError::Warning, message.str());
        }
        QL_REQUIRE(quoteValue != Null<Real>(),
                   "missing quote for [" << index_->name() << "]");
        Real tradePriceValue =
            tradePrice_.amount().value() * tradePriceUomConversionFactor
            * tradePriceFxConversionFactor;
        Real quotePriceValue = quoteValue * indexUomConversionFactor
            * indexPriceFxConversionFactor;
        Real quantityAmount = quantity_.amount() * quantityUomConversionFactor;
        Real delta = (((quotePriceValue - tradePriceValue) * quantityAmount)
                      * index_->lotQuantity()) * buySell_;
        NPV_ = delta;
        calculateSecondaryCostAmounts(quantity_.commodityType(),
                                      quantity_.amount(), evaluationDate);
        for (SecondaryCostAmounts::const_iterator i = secondaryCostAmounts_.begin(); i != secondaryCostAmounts_.end(); i++) {
            Real amount = i->second.value();
            NPV_ -= amount;
        }
        // additionalResults_["brokerCommission"] =
        //     -(brokerCommissionValue * quantityAmount);
    }
Quantity QuantLib::EnergyFuture::quantity () const [inline, virtual]
Implements QuantLib::EnergyCommodity.
Definition at line 43 of file energyfuture.hpp.
References quantity_.
{ return quantity_; }
const CommodityUnitCost& QuantLib::EnergyFuture::tradePrice () const [inline]
Definition at line 44 of file energyfuture.hpp.
References tradePrice_.
{ return tradePrice_; }
Member Data Documentation
Integer QuantLib::EnergyFuture::buySell_ [protected]
Definition at line 48 of file energyfuture.hpp.
Referenced by performCalculations().
boost::shared_ptr<CommodityIndex> QuantLib::EnergyFuture::index_ [protected]
Definition at line 51 of file energyfuture.hpp.
Referenced by EnergyFuture(), index(), and performCalculations().
Quantity QuantLib::EnergyFuture::quantity_ [protected]
Definition at line 49 of file energyfuture.hpp.
Referenced by performCalculations(), and quantity().
CommodityUnitCost QuantLib::EnergyFuture::tradePrice_ [protected]
Definition at line 50 of file energyfuture.hpp.
Referenced by performCalculations(), and tradePrice().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/commodities/energyfuture.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/commodities/energyfuture.cpp