QuantLib: QuantLib::AnalyticCompoundOptionEngine Class Reference
QuantLib::AnalyticCompoundOptionEngine Class Reference
Pricing engine for compound options using analytical formulae.
#include <analyticcompoundoptionengine.hpp>
Public Member Functions
AnalyticCompoundOptionEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > &process)
void calculate () const
Private Member Functions
Time residualTimeMother () const
Time residualTimeDaughter () const
Time residualTimeMotherDaughter () const
Date maturityMother () const
Date maturityDaughter () const
Real dPlus () const
Real dMinus () const
Real dPlusTau12 (Real S) const
Real dMinusTau12 () const
Real strikeDaughter () const
Real strikeMother () const
Real spot () const
Real volatilityDaughter () const
Real volatilityMother () const
Real riskFreeRateDaughter () const
Real dividendRateDaughter () const
Real stdDeviationDaughter () const
Real stdDeviationMother () const
Real typeDaughter () const
Real typeMother () const
Real transformX (Real X) const
Real e (Real X) const
DiscountFactor riskFreeDiscountDaughter () const
DiscountFactor riskFreeDiscountMother () const
DiscountFactor riskFreeDiscountMotherDaughter () const
DiscountFactor dividendDiscountDaughter () const
DiscountFactor dividendDiscountMother () const
DiscountFactor dividendDiscountMotherDaughter () const
boost::shared_ptr
< PlainVanillaPayoff > payoffMother () const
boost::shared_ptr
< PlainVanillaPayoff > payoffDaughter () const
Private Attributes
CumulativeNormalDistribution N_
NormalDistribution n_
boost::shared_ptr
< GeneralizedBlackScholesProcess > process_
Detailed Description
Pricing engine for compound options using analytical formulae.
The formulas are taken from "Foreign Exchange Risk", Uwe Wystup, Risk 2002, where closed form Greeks are available. (not available in Haug 2007). Value: Page 84, Greeks: Pages 94-95.
Test:
the correctness of the returned value is tested by reproducing results available in literature.
Definition at line 45 of file analyticcompoundoptionengine.hpp.
Constructor & Destructor Documentation
QuantLib::AnalyticCompoundOptionEngine::AnalyticCompoundOptionEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > & process)
Definition at line 24 of file analyticcompoundoptionengine.cpp.
References process_, and QuantLib::Observer::registerWith().
    : process_(process){
        registerWith(process_);
    }
Member Function Documentation
void QuantLib::AnalyticCompoundOptionEngine::calculate () const [virtual]
Implements QuantLib::PricingEngine.
Definition at line 30 of file analyticcompoundoptionengine.cpp.
References QuantLib::Days, dividendDiscountDaughter(), dividendRateDaughter(), dMinus(), dPlus(), dPlusTau12(), e(), anonymous_namespace{interpolations.cpp}::f(), maturityDaughter(), maturityMother(), N_, n_, payoffDaughter(), QuantLib::anonymous_namespace{bjerksundstenslandengine.cpp}::phi(), process_, QL_REQUIRE, residualTimeDaughter(), residualTimeMother(), QuantLib::GenericEngine< CompoundOption::arguments, CompoundOption::results >::results_, riskFreeDiscountDaughter(), riskFreeDiscountMother(), riskFreeRateDaughter(), QuantLib::Solver1D< Impl >::setMaxEvaluations(), QuantLib::Solver1D< Impl >::solve(), spot(), stdDeviationMother(), strikeDaughter(), strikeMother(), transformX(), typeDaughter(), typeMother(), and volatilityDaughter().
{
        QL_REQUIRE(strikeDaughter()>0.0,
                   "Daughter strike must be positive");
        QL_REQUIRE(strikeMother()>0.0,
                   "Mother strike must be positive");
        QL_REQUIRE(spot() >= 0.0, "negative or null underlying given");
        /* Solver Setup ***************************************************/
        Date helpDate(process_->riskFreeRate()->referenceDate());
        Date helpMaturity=helpDate+(maturityDaughter()-maturityMother())*Days;
        Real vol =process_->blackVolatility()->blackVol(helpMaturity,
                                                        strikeDaughter());
        Time helpTimeToMat=process_->time(helpMaturity);
        vol=vol*std::sqrt(helpTimeToMat);
        DiscountFactor dividendDiscount =
            process_->dividendYield()->discount(helpMaturity);
        DiscountFactor riskFreeDiscount =
            process_->riskFreeRate()->discount(helpMaturity);
        boost::shared_ptr<ImpliedSpotHelper> f(
                new ImpliedSpotHelper(dividendDiscount, riskFreeDiscount,
                                      vol, payoffDaughter(), strikeMother()));
        Brent solver;
        solver.setMaxEvaluations(1000);
        Real accuracy = 1.0e-6;
        Real X=0.0;
        Real sSolved=0.0;
        sSolved=solver.solve(*f, accuracy, strikeDaughter(), 1.0e-6, strikeDaughter()*1000.0);
        X=transformX(sSolved); // transform stock to return as in Wystup's book
        /* Solver Setup Finished*****************************************/
        Real phi=typeDaughter(); // -1 or 1
        Real w=typeMother(); // -1 or 1
        Real rho=std::sqrt(residualTimeMother()/residualTimeDaughter());
        BivariateCumulativeNormalDistributionDr78 N2(w*rho) ;
        DiscountFactor ddD=dividendDiscountDaughter();
        DiscountFactor rdD=riskFreeDiscountDaughter();
        //DiscountFactor ddM=dividendDiscountMother();
        DiscountFactor rdM=riskFreeDiscountMother();
        Real XmSM=X-stdDeviationMother();
        Real S=spot();
        Real dP=dPlus();
        Real dPT12=dPlusTau12(sSolved);
        Real vD=volatilityDaughter();
        Real dM=dMinus();
        Real strD=strikeDaughter();
        Real strM=strikeMother();
        Real rTM=residualTimeMother();
        Real rTD=residualTimeDaughter();
        Real rD=riskFreeRateDaughter();
        Real dD=dividendRateDaughter();
        Real tempRes=0.0;
        Real tempDelta=0.0;
        Real tempGamma=0.0;
        Real tempVega=0.0;
        Real tempTheta=0.0;
        Real N2XmSM=N2(-phi*w*XmSM,phi*dP);
        Real N2X=N2(-phi*w*X,phi*dM);
        Real NeX=N_(-phi*w*e(X));
        Real NX=N_(-phi*w*X);
        Real NT12=N_(phi*dPT12);
        Real ndP=n_(dP);
        Real nXm=n_(XmSM);
        Real invMTime=1/std::sqrt(rTM);
        Real invDTime=1/std::sqrt(rTD);
        tempRes=phi*w*S*ddD*N2XmSM-phi*w*strD*rdD*N2X-w*strM*rdM*NX;
        tempDelta=phi*w*ddD*N2XmSM;
        tempGamma=(ddD/(vD*S))*(invMTime*nXm*NT12+w*invDTime*ndP*NeX);
        tempVega=ddD*S*((1/invMTime)*nXm*NT12+w*(1/invDTime)*ndP*NeX);
        tempTheta+=phi*w*dD*S*ddD*N2XmSM-phi*w*rD*strD*rdD*N2X-w*rD*strM*rdM*NX;
        tempTheta-=0.5*vD*S*ddD*(invMTime*nXm*NT12+w*invDTime*ndP*NeX);
        results_.value=tempRes;
        results_.delta=tempDelta;
        results_.gamma=tempGamma;
        results_.vega=tempVega;
        results_.theta=tempTheta;
    }
DiscountFactor QuantLib::AnalyticCompoundOptionEngine::dividendDiscountDaughter () const [private]
Definition at line 218 of file analyticcompoundoptionengine.cpp.
References process_, and residualTimeDaughter().
Referenced by calculate(), and dPlus().
{
        return process_->dividendYield()->discount(residualTimeDaughter());
    }
DiscountFactor QuantLib::AnalyticCompoundOptionEngine::dividendDiscountMother () const [private]
Definition at line 222 of file analyticcompoundoptionengine.cpp.
References process_, and residualTimeMother().
Referenced by transformX().
{
        return process_->dividendYield()->discount(residualTimeMother());
    }
DiscountFactor QuantLib::AnalyticCompoundOptionEngine::dividendDiscountMotherDaughter () const [private]
Definition at line 226 of file analyticcompoundoptionengine.cpp.
References process_, and residualTimeMotherDaughter().
Referenced by dPlusTau12().
{
        return process_->dividendYield()->discount(residualTimeMotherDaughter());
    }
Real QuantLib::AnalyticCompoundOptionEngine::dividendRateDaughter () const [private]
Definition at line 256 of file analyticcompoundoptionengine.cpp.
References QuantLib::Continuous, QuantLib::NoFrequency, process_, and residualTimeDaughter().
Referenced by calculate().
{
        return process_->dividendYield()->zeroRate(residualTimeDaughter(),
                                                   Continuous,
                                                   NoFrequency);
    }
Real QuantLib::AnalyticCompoundOptionEngine::dMinus () const [private]
Definition at line 236 of file analyticcompoundoptionengine.cpp.
References dPlus(), and stdDeviationDaughter().
Referenced by calculate(), and e().
{
        return dPlus()-stdDeviationDaughter();
    }
Real QuantLib::AnalyticCompoundOptionEngine::dMinusTau12 () const [private]
Real QuantLib::AnalyticCompoundOptionEngine::dPlus () const [private]
Definition at line 230 of file analyticcompoundoptionengine.cpp.
References dividendDiscountDaughter(), riskFreeDiscountDaughter(), spot(), stdDeviationDaughter(), and strikeDaughter().
Referenced by calculate(), and dMinus().
{
        Real forward = spot() * dividendDiscountDaughter() / riskFreeDiscountDaughter();
        Real sd=stdDeviationDaughter();
        return std::log(forward/strikeDaughter())/sd+0.5*sd;
    }
Real QuantLib::AnalyticCompoundOptionEngine::dPlusTau12 (Real S) const [private]
Definition at line 240 of file analyticcompoundoptionengine.cpp.
References dividendDiscountMotherDaughter(), residualTimeMotherDaughter(), riskFreeDiscountMotherDaughter(), strikeDaughter(), and volatilityDaughter().
Referenced by calculate().
{
        Real forward = S * dividendDiscountMotherDaughter() / riskFreeDiscountMotherDaughter();
        Real sd=volatilityDaughter()*std::sqrt(residualTimeMotherDaughter());
        return std::log(forward/strikeDaughter())/sd+0.5*sd;
    }
Real QuantLib::AnalyticCompoundOptionEngine::e (Real X) const [private]
Definition at line 272 of file analyticcompoundoptionengine.cpp.
References dMinus(), residualTimeDaughter(), and residualTimeMother().
Referenced by calculate().
{
        Real rtM=residualTimeMother();
        Real rtD=residualTimeDaughter();
        return (X*std::sqrt(rtD)+std::sqrt(rtM)*dMinus())/std::sqrt(rtD-rtM);
    }
Date QuantLib::AnalyticCompoundOptionEngine::maturityDaughter () const [private]
Definition at line 135 of file analyticcompoundoptionengine.cpp.
References QuantLib::GenericEngine< CompoundOption::arguments, CompoundOption::results >::arguments_.
Referenced by calculate(), residualTimeDaughter(), and volatilityDaughter().
{
        return arguments_.exercise->lastDate();
    }
Date QuantLib::AnalyticCompoundOptionEngine::maturityMother () const [private]
Definition at line 139 of file analyticcompoundoptionengine.cpp.
References QuantLib::GenericEngine< CompoundOption::arguments, CompoundOption::results >::arguments_, and QuantLib::CompoundOption::arguments::motherOption.
Referenced by calculate(), residualTimeMother(), and volatilityMother().
{
        return (arguments_.motherOption->exercise())->lastDate();
    }
boost::shared_ptr< PlainVanillaPayoff > QuantLib::AnalyticCompoundOptionEngine::payoffDaughter () const [private]
Definition at line 177 of file analyticcompoundoptionengine.cpp.
References QuantLib::GenericEngine< CompoundOption::arguments, CompoundOption::results >::arguments_, and QL_REQUIRE.
Referenced by calculate(), strikeDaughter(), and typeDaughter().
{
        boost::shared_ptr<PlainVanillaPayoff> dPayoff =
            boost::dynamic_pointer_cast<PlainVanillaPayoff>(arguments_.payoff);
        QL_REQUIRE(dPayoff, "non-plain payoff given");
        return dPayoff;
    }
boost::shared_ptr< PlainVanillaPayoff > QuantLib::AnalyticCompoundOptionEngine::payoffMother () const [private]
Definition at line 187 of file analyticcompoundoptionengine.cpp.
References QuantLib::GenericEngine< CompoundOption::arguments, CompoundOption::results >::arguments_, QuantLib::CompoundOption::arguments::motherOption, and QL_REQUIRE.
Referenced by strikeMother(), and typeMother().
{
        boost::shared_ptr<PlainVanillaPayoff> mPayoff =
            boost::dynamic_pointer_cast<PlainVanillaPayoff>(
                                         (arguments_.motherOption)->payoff());
        QL_REQUIRE(mPayoff, "non-plain payoff given");
        return mPayoff;
    }
Time QuantLib::AnalyticCompoundOptionEngine::residualTimeDaughter () const [private]
Definition at line 143 of file analyticcompoundoptionengine.cpp.
References maturityDaughter(), and process_.
Referenced by calculate(), dividendDiscountDaughter(), dividendRateDaughter(), e(), residualTimeMotherDaughter(), riskFreeDiscountDaughter(), riskFreeRateDaughter(), and stdDeviationDaughter().
{
        return process_->time(maturityDaughter());
    }
Time QuantLib::AnalyticCompoundOptionEngine::residualTimeMother () const [private]
Definition at line 147 of file analyticcompoundoptionengine.cpp.
References maturityMother(), and process_.
Referenced by calculate(), dividendDiscountMother(), e(), residualTimeMotherDaughter(), riskFreeDiscountMother(), and stdDeviationMother().
{
        return process_->time(maturityMother());
    }
Time QuantLib::AnalyticCompoundOptionEngine::residualTimeMotherDaughter () const [private]
Definition at line 151 of file analyticcompoundoptionengine.cpp.
References residualTimeDaughter(), and residualTimeMother().
Referenced by dividendDiscountMotherDaughter(), dPlusTau12(), and riskFreeDiscountMotherDaughter().
{
        return residualTimeDaughter()-residualTimeMother();
    }
DiscountFactor QuantLib::AnalyticCompoundOptionEngine::riskFreeDiscountDaughter () const [private]
Definition at line 206 of file analyticcompoundoptionengine.cpp.
References process_, and residualTimeDaughter().
Referenced by calculate(), and dPlus().
{
        return process_->riskFreeRate()->discount(residualTimeDaughter());
    }
DiscountFactor QuantLib::AnalyticCompoundOptionEngine::riskFreeDiscountMother () const [private]
Definition at line 210 of file analyticcompoundoptionengine.cpp.
References process_, and residualTimeMother().
Referenced by calculate(), and transformX().
{
        return process_->riskFreeRate()->discount(residualTimeMother());
    }
DiscountFactor QuantLib::AnalyticCompoundOptionEngine::riskFreeDiscountMotherDaughter () const [private]
Definition at line 214 of file analyticcompoundoptionengine.cpp.
References process_, and residualTimeMotherDaughter().
Referenced by dPlusTau12().
{
        return process_->riskFreeRate()->discount(residualTimeMotherDaughter());
    }
Real QuantLib::AnalyticCompoundOptionEngine::riskFreeRateDaughter () const [private]
Definition at line 250 of file analyticcompoundoptionengine.cpp.
References QuantLib::Continuous, QuantLib::NoFrequency, process_, and residualTimeDaughter().
Referenced by calculate().
{
        return process_->riskFreeRate()->zeroRate(residualTimeDaughter(),
                                                  Continuous,
                                                  NoFrequency);
    }
Real QuantLib::AnalyticCompoundOptionEngine::spot () const [private]
Definition at line 246 of file analyticcompoundoptionengine.cpp.
References process_.
Referenced by calculate(), dPlus(), and transformX().
{
        return process_->x0();
    }
Real QuantLib::AnalyticCompoundOptionEngine::stdDeviationDaughter () const [private]
Definition at line 167 of file analyticcompoundoptionengine.cpp.
References residualTimeDaughter(), and volatilityDaughter().
Referenced by dMinus(), and dPlus().
{
        return volatilityDaughter()*std::sqrt(residualTimeDaughter());
    }
Real QuantLib::AnalyticCompoundOptionEngine::stdDeviationMother () const [private]
Definition at line 171 of file analyticcompoundoptionengine.cpp.
References residualTimeMother(), and volatilityMother().
Referenced by calculate(), and transformX().
{
        return volatilityMother()*std::sqrt(residualTimeMother());
    }
Real QuantLib::AnalyticCompoundOptionEngine::strikeDaughter () const [private]
Definition at line 202 of file analyticcompoundoptionengine.cpp.
References payoffDaughter().
Referenced by calculate(), dPlus(), dPlusTau12(), and volatilityDaughter().
{
        return payoffDaughter()->strike();
    }
Real QuantLib::AnalyticCompoundOptionEngine::strikeMother () const [private]
Definition at line 198 of file analyticcompoundoptionengine.cpp.
References payoffMother().
Referenced by calculate(), and volatilityMother().
{
        return payoffMother()->strike();
    }
Real QuantLib::AnalyticCompoundOptionEngine::transformX (Real X) const [private]
Definition at line 262 of file analyticcompoundoptionengine.cpp.
References dividendDiscountMother(), riskFreeDiscountMother(), spot(), and stdDeviationMother().
Referenced by calculate().
{
        Real sd=stdDeviationMother();
        Real resX=riskFreeDiscountMother()*X/(spot()*dividendDiscountMother());
        resX=resX*std::exp(0.5*sd*sd);
        resX=std::log(resX);
        return resX/sd;
    }
Real QuantLib::AnalyticCompoundOptionEngine::typeDaughter () const [private]
Definition at line 126 of file analyticcompoundoptionengine.cpp.
References payoffDaughter().
Referenced by calculate().
{
        // returns -1 or 1 according to put or call
        return (Real) payoffDaughter()->optionType();
    }
Real QuantLib::AnalyticCompoundOptionEngine::typeMother () const [private]
Definition at line 131 of file analyticcompoundoptionengine.cpp.
References payoffMother().
Referenced by calculate().
{
        return (Real) payoffMother()->optionType();
    }
Real QuantLib::AnalyticCompoundOptionEngine::volatilityDaughter () const [private]
Definition at line 156 of file analyticcompoundoptionengine.cpp.
References maturityDaughter(), process_, and strikeDaughter().
Referenced by calculate(), dPlusTau12(), and stdDeviationDaughter().
{
        return process_->blackVolatility()->blackVol(maturityDaughter(),
                                                     strikeDaughter());
    }
Real QuantLib::AnalyticCompoundOptionEngine::volatilityMother () const [private]
Definition at line 162 of file analyticcompoundoptionengine.cpp.
References maturityMother(), process_, and strikeMother().
Referenced by stdDeviationMother().
{
        return process_->blackVolatility()->blackVol(maturityMother(),
                                                     strikeMother());
    }
Member Data Documentation
CumulativeNormalDistribution QuantLib::AnalyticCompoundOptionEngine::N_ [private]
Definition at line 52 of file analyticcompoundoptionengine.hpp.
Referenced by calculate().
NormalDistribution QuantLib::AnalyticCompoundOptionEngine::n_ [private]
Definition at line 53 of file analyticcompoundoptionengine.hpp.
Referenced by calculate().
boost::shared_ptr<GeneralizedBlackScholesProcess> QuantLib::AnalyticCompoundOptionEngine::process_ [private]
Definition at line 54 of file analyticcompoundoptionengine.hpp.
Referenced by AnalyticCompoundOptionEngine(), calculate(), dividendDiscountDaughter(), dividendDiscountMother(), dividendDiscountMotherDaughter(), dividendRateDaughter(), residualTimeDaughter(), residualTimeMother(), riskFreeDiscountDaughter(), riskFreeDiscountMother(), riskFreeDiscountMotherDaughter(), riskFreeRateDaughter(), spot(), volatilityDaughter(), and volatilityMother().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/compoundoption/analyticcompoundoptionengine.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/compoundoption/analyticcompoundoptionengine.cpp