QuantLib: QuantLib::MakeMCAmericanEngine< RNG, S > Class Template Reference
QuantLib::MakeMCAmericanEngine< RNG, S > Class Template Reference
Monte Carlo American engine factory.
#include <mcamericanengine.hpp>
Public Member Functions
MakeMCAmericanEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > &)
MakeMCAmericanEngine & withSteps (Size steps)
MakeMCAmericanEngine & withStepsPerYear (Size steps)
MakeMCAmericanEngine & withSamples (Size samples)
MakeMCAmericanEngine & withAbsoluteTolerance (Real tolerance)
MakeMCAmericanEngine & withMaxSamples (Size samples)
MakeMCAmericanEngine & withSeed (BigNatural seed)
MakeMCAmericanEngine & withAntitheticVariate (bool b=true)
MakeMCAmericanEngine & withControlVariate (bool b=true)
MakeMCAmericanEngine & withPolynomOrder (Size polynomOrer)
MakeMCAmericanEngine & withBasisSystem (LsmBasisSystem::PolynomType)
MakeMCAmericanEngine & withCalibrationSamples (Size calibrationSamples)
operator boost::shared_ptr< PricingEngine > () const
Private Attributes
boost::shared_ptr
< GeneralizedBlackScholesProcess > process_
bool antithetic_
bool controlVariate_
Size steps_
Size stepsPerYear_
Size samples_
Size maxSamples_
Size calibrationSamples_
Real tolerance_
BigNatural seed_
Size polynomOrder_
LsmBasisSystem::PolynomType polynomType_
Detailed Description
template<class RNG = PseudoRandom, class S = Statistics>
class QuantLib::MakeMCAmericanEngine< RNG, S >
Monte Carlo American engine factory.
Definition at line 103 of file mcamericanengine.hpp.
Constructor & Destructor Documentation
template<class RNG , class S > QuantLib::MakeMCAmericanEngine< RNG, S >::MakeMCAmericanEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > & process) [inline]
Definition at line 247 of file mcamericanengine.hpp.
    : process_(process), antithetic_(false), controlVariate_(false),
      steps_(Null<Size>()), stepsPerYear_(Null<Size>()),
      samples_(Null<Size>()), maxSamples_(Null<Size>()),
      calibrationSamples_(2048),
      tolerance_(Null<Real>()), seed_(0),
      polynomOrder_(2),
      polynomType_ (LsmBasisSystem::Monomial) {}
Member Function Documentation
template<class RNG , class S > QuantLib::MakeMCAmericanEngine< RNG, S >::operator boost::shared_ptr< PricingEngine > () const [inline]
Definition at line 345 of file mcamericanengine.hpp.
References QL_REQUIRE, and anonymous_namespace{marketmodel.cpp}::seed_.
{
        QL_REQUIRE(steps_ != Null<Size>() || stepsPerYear_ != Null<Size>(),
                   "number of steps not given");
        QL_REQUIRE(steps_ == Null<Size>() || stepsPerYear_ == Null<Size>(),
                   "number of steps overspecified");
        return boost::shared_ptr<PricingEngine>(new
            MCAmericanEngine<RNG, S>(process_,
                                     steps_,
                                     stepsPerYear_,
                                     antithetic_,
                                     controlVariate_,
                                     samples_, tolerance_,
                                     maxSamples_,
                                     seed_,
                                     polynomOrder_,
                                     polynomType_,
                                     calibrationSamples_));
    }
template<class RNG , class S > MakeMCAmericanEngine< RNG, S > & QuantLib::MakeMCAmericanEngine< RNG, S >::withAbsoluteTolerance (Real tolerance) [inline]
Definition at line 297 of file mcamericanengine.hpp.
References QL_REQUIRE, and anonymous_namespace{gaussianquadratures.cpp}::tolerance.
Referenced by MCLongstaffSchwartzEngineTest::testAmericanOption().
{
        QL_REQUIRE(samples_ == Null<Size>(),
                   "number of samples already set");
        QL_REQUIRE(RNG::allowsErrorEstimate,
                   "chosen random generator policy "
                   "does not allow an error estimate");
        tolerance_ = tolerance;
        return *this;
    }
template<class RNG , class S > MakeMCAmericanEngine< RNG, S > & QuantLib::MakeMCAmericanEngine< RNG, S >::withAntitheticVariate (bool b = true) [inline]
Definition at line 330 of file mcamericanengine.hpp.
References anonymous_namespace{marketmodel.cpp}::b.
Referenced by MCLongstaffSchwartzEngineTest::testAmericanOption().
{
        antithetic_ = b;
        return *this;
    }
template<class RNG , class S > MakeMCAmericanEngine< RNG, S > & QuantLib::MakeMCAmericanEngine< RNG, S >::withBasisSystem (LsmBasisSystem::PolynomType polynomType) [inline]
Definition at line 266 of file mcamericanengine.hpp.
Referenced by MCLongstaffSchwartzEngineTest::testAmericanOption().
{
        polynomType_ = polynomType;
        return *this;
    }
template<class RNG , class S > MakeMCAmericanEngine< RNG, S > & QuantLib::MakeMCAmericanEngine< RNG, S >::withCalibrationSamples (Size calibrationSamples) [inline]
Definition at line 316 of file mcamericanengine.hpp.
{
        calibrationSamples_ = samples;
        return *this;
    }
template<class RNG , class S > MakeMCAmericanEngine< RNG, S > & QuantLib::MakeMCAmericanEngine< RNG, S >::withControlVariate (bool b = true) [inline]
Definition at line 337 of file mcamericanengine.hpp.
References anonymous_namespace{marketmodel.cpp}::b.
{
        controlVariate_ = b;
        return *this;
    }
template<class RNG , class S > MakeMCAmericanEngine< RNG, S > & QuantLib::MakeMCAmericanEngine< RNG, S >::withMaxSamples (Size samples) [inline]
Definition at line 309 of file mcamericanengine.hpp.
{
        maxSamples_ = samples;
        return *this;
    }
template<class RNG , class S > MakeMCAmericanEngine< RNG, S > & QuantLib::MakeMCAmericanEngine< RNG, S >::withPolynomOrder (Size polynomOrer) [inline]
Definition at line 259 of file mcamericanengine.hpp.
Referenced by MCLongstaffSchwartzEngineTest::testAmericanOption().
{
        polynomOrder_ = polynomOrder;
        return *this;
    }
template<class RNG , class S > MakeMCAmericanEngine< RNG, S > & QuantLib::MakeMCAmericanEngine< RNG, S >::withSamples (Size samples) [inline]
Definition at line 288 of file mcamericanengine.hpp.
References QL_REQUIRE.
{
        QL_REQUIRE(tolerance_ == Null<Real>(),
                   "tolerance already set");
        samples_ = samples;
        return *this;
    }
template<class RNG , class S > MakeMCAmericanEngine< RNG, S > & QuantLib::MakeMCAmericanEngine< RNG, S >::withSeed (BigNatural seed) [inline]
Definition at line 323 of file mcamericanengine.hpp.
References anonymous_namespace{marketmodel.cpp}::seed_.
Referenced by MCLongstaffSchwartzEngineTest::testAmericanOption().
{
        seed_ = seed;
        return *this;
    }
template<class RNG , class S > MakeMCAmericanEngine< RNG, S > & QuantLib::MakeMCAmericanEngine< RNG, S >::withSteps (Size steps) [inline]
Definition at line 274 of file mcamericanengine.hpp.
{
        steps_ = steps;
        return *this;
    }
template<class RNG , class S > MakeMCAmericanEngine< RNG, S > & QuantLib::MakeMCAmericanEngine< RNG, S >::withStepsPerYear (Size steps) [inline]
Definition at line 281 of file mcamericanengine.hpp.
{
        stepsPerYear_ = steps;
        return *this;
    }
Member Data Documentation
template<class RNG = PseudoRandom, class S = Statistics> bool QuantLib::MakeMCAmericanEngine< RNG, S >::antithetic_ [private]
Definition at line 124 of file mcamericanengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> Size QuantLib::MakeMCAmericanEngine< RNG, S >::calibrationSamples_ [private]
Definition at line 126 of file mcamericanengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> bool QuantLib::MakeMCAmericanEngine< RNG, S >::controlVariate_ [private]
Definition at line 124 of file mcamericanengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> Size QuantLib::MakeMCAmericanEngine< RNG, S >::maxSamples_ [private]
Definition at line 126 of file mcamericanengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> Size QuantLib::MakeMCAmericanEngine< RNG, S >::polynomOrder_ [private]
Definition at line 129 of file mcamericanengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> LsmBasisSystem::PolynomType QuantLib::MakeMCAmericanEngine< RNG, S >::polynomType_ [private]
Definition at line 130 of file mcamericanengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> boost::shared_ptr<GeneralizedBlackScholesProcess> QuantLib::MakeMCAmericanEngine< RNG, S >::process_ [private]
Definition at line 123 of file mcamericanengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> Size QuantLib::MakeMCAmericanEngine< RNG, S >::samples_ [private]
Definition at line 126 of file mcamericanengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> BigNatural QuantLib::MakeMCAmericanEngine< RNG, S >::seed_ [private]
Definition at line 128 of file mcamericanengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> Size QuantLib::MakeMCAmericanEngine< RNG, S >::steps_ [private]
Definition at line 125 of file mcamericanengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> Size QuantLib::MakeMCAmericanEngine< RNG, S >::stepsPerYear_ [private]
Definition at line 125 of file mcamericanengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> Real QuantLib::MakeMCAmericanEngine< RNG, S >::tolerance_ [private]
Definition at line 127 of file mcamericanengine.hpp.
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/vanilla/mcamericanengine.hpp