QuantLib: QuantLib::Calendar Class Reference
QuantLib::Calendar Class Reference
calendar class
#include <calendar.hpp>
Classes
class Impl
abstract base class for calendar implementations
class OrthodoxImpl
partial calendar implementation
class WesternImpl
partial calendar implementation
Public Member Functions
Calendar ()
Protected Attributes
boost::shared_ptr< Impl > impl_
Related Functions
(Note that these are not member functions.)
bool operator== (const Calendar &, const Calendar &)
bool operator!= (const Calendar &, const Calendar &)
std::ostream & operator<< (std::ostream &, const Calendar &)
Calendar interface
bool empty () const
Returns whether or not the calendar is initialized.
std::string name () const
Returns the name of the calendar.
bool isBusinessDay (const Date &d) const
bool isHoliday (const Date &d) const
bool isWeekend (Weekday w) const
bool isEndOfMonth (const Date &d) const
Date endOfMonth (const Date &d) const
last business day of the month to which the given date belongs
void addHoliday (const Date &)
void removeHoliday (const Date &)
Date adjust (const Date &, BusinessDayConvention convention=Following) const
Date advance (const Date &, Integer n, TimeUnit unit, BusinessDayConvention convention=Following, bool endOfMonth=false) const
Date advance (const Date &date, const Period &period, BusinessDayConvention convention=Following, bool endOfMonth=false) const
BigInteger businessDaysBetween (const Date &from, const Date &to, bool includeFirst=true, bool includeLast=false) const
static std::vector< Date > holidayList (const Calendar &calendar, const Date &from, const Date &to, bool includeWeekEnds=false)
Returns the holidays between two dates.
Detailed Description
calendar class
This class provides methods for determining whether a date is a business day or a holiday for a given market, and for incrementing/decrementing a date of a given number of business days.
The Bridge pattern is used to provide the base behavior of the calendar, namely, to determine whether a date is a business day.
A calendar should be defined for specific exchange holiday schedule or for general country holiday schedule. Legacy city holiday schedule calendars will be moved to the exchange/country convention.
Test:
the methods for adding and removing holidays are tested by inspecting the calendar before and after their invocation.
Definition at line 58 of file calendar.hpp.
Constructor & Destructor Documentation
QuantLib::Calendar::Calendar () [inline]
The default constructor returns a calendar with a null implementation, which is therefore unusable except as a placeholder.
Definition at line 75 of file calendar.hpp.
{}
Member Function Documentation
void QuantLib::Calendar::addHoliday (const Date & d)
Adds a date to the set of holidays for the given calendar.
Definition at line 27 of file calendar.cpp.
References impl_.
Referenced by CalendarTest::testBespokeCalendars(), and CalendarTest::testModifiedCalendars().
{
        // if d was a genuine holiday previously removed, revert the change
        impl_->removedHolidays.erase(d);
        // if it's already a holiday, leave the calendar alone.
        // Otherwise, add it.
        if (impl_->isBusinessDay(d))
            impl_->addedHolidays.insert(d);
    }
Date QuantLib::Calendar::adjust (const Date & d, BusinessDayConvention convention = Following) const
Adjusts a non-business day to the appropriate near business day with respect to the given convention.
Definition at line 45 of file calendar.cpp.
References anonymous_namespace{marketmodel.cpp}::d, QuantLib::Following, isHoliday(), QuantLib::ModifiedFollowing, QuantLib::ModifiedPreceding, QuantLib::Date::month(), QuantLib::Preceding, QL_FAIL, QL_REQUIRE, and QuantLib::Unadjusted.
Referenced by advance(), QuantLib::CallableFixedRateBond::CallableFixedRateBond(), anonymous_namespace{digitalcoupon.cpp}::CommonVars::CommonVars(), anonymous_namespace{bermudanswaption.cpp}::CommonVars::CommonVars(), anonymous_namespace{termstructures.cpp}::CommonVars::CommonVars(), anonymous_namespace{bonds.cpp}::CommonVars::CommonVars(), anonymous_namespace{cms.cpp}::CommonVars::CommonVars(), anonymous_namespace{convertiblebonds.cpp}::CommonVars::CommonVars(), anonymous_namespace{swap.cpp}::CommonVars::CommonVars(), anonymous_namespace{swaption.cpp}::CommonVars::CommonVars(), anonymous_namespace{inflationcapfloor.cpp}::CommonVars::CommonVars(), anonymous_namespace{inflationcpiswap.cpp}::CommonVars::CommonVars(), anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::CommonVars(), anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::CommonVars(), anonymous_namespace{piecewiseyieldcurve.cpp}::CommonVars::CommonVars(), InflationCPICapFloorTest::cpicapfloorpricer(), QuantLib::CPISwap::CPISwap(), endOfMonth(), QuantLib::CPICapFloor::fixingDate(), QuantLib::FloatingDigitalLeg(), QuantLib::FloatingLeg(), QuantLib::Forward::Forward(), QuantLib::CdsHelper::initializeDates(), QuantLib::AssetSwapHelper::initializeDates(), QuantLib::BMASwapRateHelper::initializeDates(), isEndOfMonth(), QuantLib::OvernightLeg::operator Leg(), QuantLib::AverageBMALeg::operator Leg(), QuantLib::FixedRateLeg::operator Leg(), QuantLib::yoyInflationLeg::operator Leg(), QuantLib::CPILeg::operator Leg(), QuantLib::CPICapFloor::payDate(), QuantLib::EnergyBasisSwap::performCalculations(), QuantLib::EnergyVanillaSwap::performCalculations(), QuantLib::Schedule::Schedule(), anonymous_namespace{optionletstripper.cpp}::CommonVars::setTermStructure(), anonymous_namespace{piecewiseyieldcurve.cpp}::testBMACurveConsistency(), anonymous_namespace{defaultprobabilitycurves.cpp}::testBootstrapFromSpread(), anonymous_namespace{defaultprobabilitycurves.cpp}::testBootstrapFromUpfront(), CreditDefaultSwapTest::testFairSpread(), CreditDefaultSwapTest::testFairUpfront(), AssetSwapTest::testGenericBondImplied(), CreditDefaultSwapTest::testImpliedHazardRate(), LiborMarketModelProcessTest::testInitialisation(), AssetSwapTest::testMASWWithGenericBond(), AssetSwapTest::testSpecializedBondVsGenericBond(), AssetSwapTest::testSpecializedBondVsGenericBondUsingAsw(), ShortRateModelTest::testSwaps(), InflationTest::testYYIndex(), InflationTest::testYYTermStructure(), InflationTest::testZeroIndex(), InflationTest::testZeroTermStructure(), AssetSwapTest::testZSpreadWithGenericBond(), QuantLib::Libor::valueDate(), QuantLib::ZeroCouponBond::ZeroCouponBond(), and QuantLib::ZeroCouponInflationSwap::ZeroCouponInflationSwap().
{
        QL_REQUIRE(d != Date(), "null date");
        if (c == Unadjusted)
            return d;
        Date d1 = d;
        if (c == Following || c == ModifiedFollowing) {
            while (isHoliday(d1))
                d1++;
            if (c == ModifiedFollowing) {
                if (d1.month() != d.month()) {
                    return adjust(d,Preceding);
                }
            }
        } else if (c == Preceding || c == ModifiedPreceding) {
            while (isHoliday(d1))
                d1--;
            if (c == ModifiedPreceding && d1.month() != d.month()) {
                return adjust(d,Following);
            }
        } else {
            QL_FAIL("unknown business-day convention");
        }
        return d1;
    }
Date QuantLib::Calendar::advance (const Date & d, Integer n, TimeUnit unit, BusinessDayConvention convention = Following, bool endOfMonth = false) const
Advances the given date of the given number of business days and returns the result.
Note:
The input date is not modified.
Definition at line 73 of file calendar.cpp.
References adjust(), anonymous_namespace{marketmodel.cpp}::d, QuantLib::Days, endOfMonth(), isEndOfMonth(), isHoliday(), QL_REQUIRE, and QuantLib::Weeks.
Referenced by advance(), QuantLib::AverageBMACoupon::AverageBMACoupon(), QuantLib::IntegralCDOEngine::calculate(), anonymous_namespace{termstructures.cpp}::CommonVars::CommonVars(), anonymous_namespace{convertiblebonds.cpp}::CommonVars::CommonVars(), anonymous_namespace{swaption.cpp}::CommonVars::CommonVars(), anonymous_namespace{inflationcapfloor.cpp}::CommonVars::CommonVars(), anonymous_namespace{inflationcpiswap.cpp}::CommonVars::CommonVars(), anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::CommonVars(), anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::CommonVars(), anonymous_namespace{piecewiseyieldcurve.cpp}::CommonVars::CommonVars(), QuantLib::YoYInflationIndex::fixing(), QuantLib::InterestRateIndex::fixingDate(), QuantLib::BMAIndex::forecastFixing(), QuantLib::ForwardRateAgreement::ForwardRateAgreement(), QuantLib::FuturesRateHelper::FuturesRateHelper(), QuantLib::historicalForwardRatesAnalysis(), QuantLib::historicalRatesAnalysis(), QuantLib::IborCoupon::IborCoupon(), QuantLib::RangeAccrualPricer::initialize(), QuantLib::AssetSwapHelper::initializeDates(), QuantLib::UpfrontCdsHelper::initializeDates(), QuantLib::BMASwapRateHelper::initializeDates(), anonymous_namespace{capflooredcoupon.cpp}::CommonVars::makeCapFlooredLeg(), anonymous_namespace{capflooredcoupon.cpp}::CommonVars::makeFixedLeg(), anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::makeFixedLeg(), anonymous_namespace{capflooredcoupon.cpp}::CommonVars::makeFloatingLeg(), anonymous_namespace{capfloor.cpp}::CommonVars::makeLeg(), anonymous_namespace{swap.cpp}::CommonVars::makeSwap(), anonymous_namespace{bermudanswaption.cpp}::CommonVars::makeSwap(), anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::makeYoYCapFlooredLeg(), anonymous_namespace{inflationcapfloor.cpp}::CommonVars::makeYoYLeg(), anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::makeYoYLeg(), QuantLib::IborIndex::maturityDate(), QuantLib::EURLibor::maturityDate(), QuantLib::Libor::maturityDate(), QuantLib::BMAIndex::maturityDate(), QuantLib::MakeOIS::operator boost::shared_ptr< OvernightIndexedSwap >(), QuantLib::MakeSwaption::operator boost::shared_ptr< Swaption >(), QuantLib::MakeYoYInflationCapFloor::operator boost::shared_ptr< YoYInflationCapFloor >(), QuantLib::VolatilityTermStructure::optionDateFromTenor(), QuantLib::CallableBondVolatilityStructure::optionDateFromTenor(), QuantLib::EnergyBasisSwap::performCalculations(), QuantLib::EnergyVanillaSwap::performCalculations(), QuantLib::ForwardRateAgreement::performCalculations(), QuantLib::CDO::performCalculations(), QuantLib::RiskyAssetSwap::recoveryValue(), QuantLib::TermStructure::referenceDate(), QuantLib::Schedule::Schedule(), QuantLib::Forward::settlementDate(), QuantLib::ForwardRateAgreement::settlementDate(), QuantLib::Bond::settlementDate(), anonymous_namespace{inflationvolatility.cpp}::setup(), QuantLib::StrippedOptionlet::StrippedOptionlet(), QuantLib::SwaptionHelper::SwaptionHelper(), HestonModelTest::testBlackCalibration(), anonymous_namespace{piecewiseyieldcurve.cpp}::testBMACurveConsistency(), CdsOptionTest::testCached(), CreditDefaultSwapTest::testCachedMarketValue(), CreditDefaultSwapTest::testCachedValue(), anonymous_namespace{piecewiseyieldcurve.cpp}::testCurveConsistency(), DefaultProbabilityCurveTest::testDefaultProbability(), CreditDefaultSwapTest::testFairSpread(), CreditDefaultSwapTest::testFairUpfront(), DefaultProbabilityCurveTest::testFlatHazardRate(), QuoteTest::testForwardValueQuoteAndImpliedStdevQuote(), CreditDefaultSwapTest::testImpliedHazardRate(), LiborMarketModelProcessTest::testInitialisation(), TimeSeriesTest::testIterators(), ShortRateModelTest::testSwaps(), InflationTest::testYYIndex(), QuantLib::EURLibor::valueDate(), QuantLib::Libor::valueDate(), and QuantLib::InterestRateIndex::valueDate().
{
        QL_REQUIRE(d!=Date(), "null date");
        if (n == 0) {
            return adjust(d,c);
        } else if (unit == Days) {
            Date d1 = d;
            if (n > 0) {
                while (n > 0) {
                    d1++;
                    while (isHoliday(d1))
                        d1++;
                    n--;
                }
            } else {
                while (n < 0) {
                    d1--;
                    while(isHoliday(d1))
                        d1--;
                    n++;
                }
            }
            return d1;
        } else if (unit == Weeks) {
            Date d1 = d + n*unit;
            return adjust(d1,c);
        } else {
            Date d1 = d + n*unit;
            // we are sure the unit is Months or Years
            if (endOfMonth && isEndOfMonth(d))
                return Calendar::endOfMonth(d1);
            return adjust(d1, c);
        }
    }
Date QuantLib::Calendar::advance (const Date & date, const Period & period, BusinessDayConvention convention = Following, bool endOfMonth = false) const
Advances the given date as specified by the given period and returns the result.
Note:
The input date is not modified.
Definition at line 112 of file calendar.cpp.
References advance(), anonymous_namespace{marketmodel.cpp}::c, endOfMonth(), QuantLib::Period::length(), and QuantLib::Period::units().
{
        return advance(d, p.length(), p.units(), c, endOfMonth);
    }
BigInteger QuantLib::Calendar::businessDaysBetween (const Date & from, const Date & to, bool includeFirst = true, bool includeLast = false) const
Calculates the number of business days between two given dates and returns the result.
Definition at line 119 of file calendar.cpp.
References anonymous_namespace{marketmodel.cpp}::d, and isBusinessDay().
Referenced by QuantLib::anonymous_namespace{business252.cpp}::businessDays(), and CalendarTest::testBusinessDaysBetween().
{
        BigInteger wd = 0;
        if (from != to) {
            if (from < to) {
                // the last one is treated separately to avoid
                // incrementing Date::maxDate()
                for (Date d = from; d < to; ++d) {
                    if (isBusinessDay(d))
                        ++wd;
                }
                if (isBusinessDay(to))
                    ++wd;
            } else if (from > to) {
                for (Date d = to; d < from; ++d) {
                    if (isBusinessDay(d))
                        ++wd;
                }
                if (isBusinessDay(from))
                    ++wd;
            }
            if (isBusinessDay(from) && !includeFirst)
                wd--;
            if (isBusinessDay(to) && !includeLast)
                wd--;
            if (from > to)
                wd = -wd;
        }
        return wd;
    }
bool QuantLib::Calendar::empty () const [inline]
Returns whether or not the calendar is initialized.
Definition at line 187 of file calendar.hpp.
References impl_.
Referenced by QuantLib::MakeSchedule::operator Schedule(), and QuantLib::operator==().
{
        return !impl_;
    }
Date QuantLib::Calendar::endOfMonth (const Date & d) const [inline]
last business day of the month to which the given date belongs
Definition at line 207 of file calendar.hpp.
References adjust(), QuantLib::Date::endOfMonth(), and QuantLib::Preceding.
Referenced by advance(), QuantLib::Schedule::Schedule(), and CalendarTest::testEndOfMonth().
{
        return adjust(Date::endOfMonth(d), Preceding);
    }
std::vector< Date > QuantLib::Calendar::holidayList (const Calendar & calendar, const Date & from, const Date & to, bool includeWeekEnds = false) [static]
Returns the holidays between two dates.
Definition at line 242 of file calendar.cpp.
References anonymous_namespace{marketmodel.cpp}::d, isHoliday(), isWeekend(), and QL_REQUIRE.
Referenced by CalendarTest::testBrazil(), CalendarTest::testGermanyEurex(), CalendarTest::testGermanyFrankfurt(), CalendarTest::testGermanyXetra(), CalendarTest::testItalyExchange(), CalendarTest::testKoreaStockExchange(), CalendarTest::testSouthKoreanSettlement(), CalendarTest::testTARGET(), CalendarTest::testUKExchange(), CalendarTest::testUKMetals(), CalendarTest::testUKSettlement(), CalendarTest::testUSGovernmentBondMarket(), CalendarTest::testUSNewYorkStockExchange(), and CalendarTest::testUSSettlement().
{
        QL_REQUIRE(to>from, "'from' date ("
            << from << ") must be earlier than 'to' date ("
            << to << ")");
        std::vector<Date> result;
        for (Date d = from; d <= to; ++d) {
            if (calendar.isHoliday(d)
                && (includeWeekEnds || !calendar.isWeekend(d.weekday())))
                result.push_back(d);
       }
       return result;
    }
bool QuantLib::Calendar::isBusinessDay (const Date & d) const [inline]
Returns true iff the date is a business day for the given market.
Definition at line 195 of file calendar.hpp.
References impl_.
Referenced by businessDaysBetween(), isHoliday(), QuantLib::BMAIndex::isValidFixingDate(), QuantLib::InterestRateIndex::isValidFixingDate(), QuantLib::CommodityIndex::isValidQuoteDate(), CalendarTest::testBespokeCalendars(), CalendarTest::testJointCalendars(), and CalendarTest::testModifiedCalendars().
{
        if (impl_->addedHolidays.find(d) != impl_->addedHolidays.end())
            return false;
        if (impl_->removedHolidays.find(d) != impl_->removedHolidays.end())
            return true;
        return impl_->isBusinessDay(d);
    }
bool QuantLib::Calendar::isEndOfMonth (const Date & d) const [inline]
Returns true iff the date is last business day for the month in given market.
Definition at line 203 of file calendar.hpp.
References adjust(), and QuantLib::Date::month().
Referenced by advance(), QuantLib::Schedule::Schedule(), and CalendarTest::testEndOfMonth().
{
        return (d.month() != adjust(d+1).month());
    }
bool QuantLib::Calendar::isHoliday (const Date & d) const [inline]
Returns true iff the date is a holiday for the given market.
Definition at line 211 of file calendar.hpp.
References isBusinessDay().
Referenced by adjust(), advance(), holidayList(), CalendarTest::testModifiedCalendars(), and CalendarTest::testUSNewYorkStockExchange().
{
        return !isBusinessDay(d);
    }
bool QuantLib::Calendar::isWeekend (Weekday w) const [inline]
Returns true iff the weekday is part of the weekend for the given market.
Definition at line 215 of file calendar.hpp.
References impl_.
Referenced by holidayList(), QuantLib::BespokeCalendar::Impl::isBusinessDay(), QuantLib::Turkey::Impl::isBusinessDay(), QuantLib::SaudiArabia::TadawulImpl::isBusinessDay(), QuantLib::Taiwan::TsecImpl::isBusinessDay(), QuantLib::China::SseImpl::isBusinessDay(), QuantLib::Japan::Impl::isBusinessDay(), QuantLib::Italy::ExchangeImpl::isBusinessDay(), QuantLib::SouthKorea::SettlementImpl::isBusinessDay(), QuantLib::Canada::TsxImpl::isBusinessDay(), QuantLib::Brazil::ExchangeImpl::isBusinessDay(), QuantLib::UnitedKingdom::ExchangeImpl::isBusinessDay(), QuantLib::UnitedKingdom::MetalsImpl::isBusinessDay(), QuantLib::Germany::FrankfurtStockExchangeImpl::isBusinessDay(), QuantLib::Germany::XetraImpl::isBusinessDay(), QuantLib::UnitedStates::NyseImpl::isBusinessDay(), QuantLib::Germany::EurexImpl::isBusinessDay(), QuantLib::UnitedStates::GovernmentBondImpl::isBusinessDay(), and QuantLib::UnitedStates::NercImpl::isBusinessDay().
{
        return impl_->isWeekend(w);
    }
std::string QuantLib::Calendar::name () const [inline]
Returns the name of the calendar.
Warning:
This method is used for output and comparison between calendars. It is not meant to be used for writing switch-on-type code.
Definition at line 191 of file calendar.hpp.
References impl_.
Referenced by QuantLib::Business252::Impl::name(), QuantLib::operator<<(), QuantLib::operator==(), CalendarTest::testEndOfMonth(), and CalendarTest::testJointCalendars().
{
        return impl_->name();
    }
void QuantLib::Calendar::removeHoliday (const Date & d)
Removes a date from the set of holidays for the given calendar.
Definition at line 36 of file calendar.cpp.
References impl_.
Referenced by CalendarTest::testModifiedCalendars().
{
        // if d was an artificially-added holiday, revert the change
        impl_->addedHolidays.erase(d);
        // if it's already a business day, leave the calendar alone.
        // Otherwise, add it.
        if (!impl_->isBusinessDay(d))
            impl_->removedHolidays.insert(d);
    }
Friends And Related Function Documentation
bool operator!= (const Calendar & , const Calendar &) [related]
Definition at line 224 of file calendar.hpp.
{
        return !(c1 == c2);
    }
std::ostream & operator<< (std::ostream & , const Calendar &) [related]
Definition at line 228 of file calendar.hpp.
{
        return out << c.name();
    }
bool operator== (const Calendar & , const Calendar &) [related]
Returns true iff the two calendars belong to the same derived class.
Definition at line 219 of file calendar.hpp.
{
        return (c1.empty() && c2.empty())
            || (!c1.empty() && !c2.empty() && c1.name() == c2.name());
    }
Member Data Documentation
boost::shared_ptr<Impl> QuantLib::Calendar::impl_ [protected]
Definition at line 69 of file calendar.hpp.
Referenced by addHoliday(), QuantLib::Argentina::Argentina(), QuantLib::Australia::Australia(), QuantLib::BespokeCalendar::BespokeCalendar(), QuantLib::Brazil::Brazil(), QuantLib::Canada::Canada(), QuantLib::China::China(), QuantLib::CzechRepublic::CzechRepublic(), QuantLib::Denmark::Denmark(), empty(), QuantLib::Finland::Finland(), QuantLib::Germany::Germany(), QuantLib::HongKong::HongKong(), QuantLib::Hungary::Hungary(), QuantLib::Iceland::Iceland(), QuantLib::India::India(), QuantLib::Indonesia::Indonesia(), isBusinessDay(), isWeekend(), QuantLib::Italy::Italy(), QuantLib::Japan::Japan(), QuantLib::JointCalendar::JointCalendar(), QuantLib::Mexico::Mexico(), name(), QuantLib::NewZealand::NewZealand(), QuantLib::Norway::Norway(), QuantLib::NullCalendar::NullCalendar(), QuantLib::Poland::Poland(), removeHoliday(), QuantLib::Russia::Russia(), QuantLib::SaudiArabia::SaudiArabia(), QuantLib::Singapore::Singapore(), QuantLib::Slovakia::Slovakia(), QuantLib::SouthAfrica::SouthAfrica(), QuantLib::SouthKorea::SouthKorea(), QuantLib::Sweden::Sweden(), QuantLib::Switzerland::Switzerland(), QuantLib::Taiwan::Taiwan(), QuantLib::TARGET::TARGET(), QuantLib::Turkey::Turkey(), QuantLib::Ukraine::Ukraine(), QuantLib::UnitedKingdom::UnitedKingdom(), QuantLib::UnitedStates::UnitedStates(), and QuantLib::WeekendsOnly::WeekendsOnly().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/time/calendar.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/time/calendar.cpp