QuantLib: QuantLib::OvernightIndexedSwap Class Reference
QuantLib::OvernightIndexedSwap Class Reference
Overnight indexed swap: fix vs compounded overnight rate.
#include <overnightindexedswap.hpp>
Public Types
enum Type { Receiver = -1, Payer = 1 }
Public Member Functions
OvernightIndexedSwap (Type type, Real nominal, const Schedule &schedule, Rate fixedRate, const DayCounter &fixedDC, const boost::shared_ptr< OvernightIndex > &overnightIndex, Spread spread=0.0)
OvernightIndexedSwap (Type type, std::vector< Real > nominals, const Schedule &schedule, Rate fixedRate, const DayCounter &fixedDC, const boost::shared_ptr< OvernightIndex > &overnightIndex, Spread spread=0.0)
Inspectors
Type type () const
Real nominal () const
std::vector< Real > nominals () const
Frequency paymentFrequency ()
Rate fixedRate () const
const DayCounter & fixedDayCount ()
const boost::shared_ptr
< OvernightIndex > & overnightIndex ()
Spread spread ()
const Leg & fixedLeg () const
const Leg & overnightLeg () const
Results
Real fixedLegBPS () const
Real fixedLegNPV () const
Real fairRate () const
Real overnightLegBPS () const
Real overnightLegNPV () const
Spread fairSpread () const
Private Member Functions
void initialize (const Schedule &schedule)
Private Attributes
Type type_
std::vector< Real > nominals_
Frequency paymentFrequency_
Rate fixedRate_
DayCounter fixedDC_
boost::shared_ptr< OvernightIndex > overnightIndex_
Spread spread_
Detailed Description
Overnight indexed swap: fix vs compounded overnight rate.
Definition at line 37 of file overnightindexedswap.hpp.
Member Enumeration Documentation
enum QuantLib::OvernightIndexedSwap::Type
Enumerator:
Receiver
Payer
Definition at line 39 of file overnightindexedswap.hpp.
{ Receiver = -1, Payer = 1 };
Constructor & Destructor Documentation
QuantLib::OvernightIndexedSwap::OvernightIndexedSwap (Type type, Real nominal, const Schedule & schedule, Rate fixedRate, const DayCounter & fixedDC, const boost::shared_ptr< OvernightIndex > & overnightIndex, Spread spread = 0.0)
Definition at line 27 of file overnightindexedswap.cpp.
References initialize().
    : Swap(2), type_(type),
      nominals_(std::vector<Real>(1, nominal)),
      paymentFrequency_(schedule.tenor().frequency()),
      fixedRate_(fixedRate), fixedDC_(fixedDC),
      overnightIndex_(overnightIndex), spread_(spread) {
          initialize(schedule);
    }
QuantLib::OvernightIndexedSwap::OvernightIndexedSwap (Type type, std::vector< Real > nominals, const Schedule & schedule, Rate fixedRate, const DayCounter & fixedDC, const boost::shared_ptr< OvernightIndex > & overnightIndex, Spread spread = 0.0)
Definition at line 45 of file overnightindexedswap.cpp.
References initialize().
    : Swap(2), type_(type), nominals_(nominals),
      paymentFrequency_(schedule.tenor().frequency()),
      fixedRate_(fixedRate), fixedDC_(fixedDC),
      overnightIndex_(overnightIndex), spread_(spread) {
          initialize(schedule);
    }
Member Function Documentation
Real QuantLib::OvernightIndexedSwap::fairRate () const
Definition at line 92 of file overnightindexedswap.cpp.
References QuantLib::Instrument::calculate(), fixedLegBPS(), fixedRate_, and QuantLib::Instrument::NPV_.
{
        static Spread basisPoint = 1.0e-4;
        calculate();
        return fixedRate_ - NPV_/(fixedLegBPS()/basisPoint);
    }
Spread QuantLib::OvernightIndexedSwap::fairSpread () const
Definition at line 98 of file overnightindexedswap.cpp.
References QuantLib::Instrument::calculate(), QuantLib::Instrument::NPV_, overnightLegBPS(), and spread_.
{
        static Spread basisPoint = 1.0e-4;
        calculate();
        return spread_ - NPV_/(overnightLegBPS()/basisPoint);
    }
const DayCounter& QuantLib::OvernightIndexedSwap::fixedDayCount () [inline]
Definition at line 66 of file overnightindexedswap.hpp.
References fixedDC_.
{ return fixedDC_; }
const Leg& QuantLib::OvernightIndexedSwap::fixedLeg () const [inline]
Definition at line 71 of file overnightindexedswap.hpp.
References QuantLib::Swap::legs_.
{ return legs_[0]; }
Real QuantLib::OvernightIndexedSwap::fixedLegBPS () const
Definition at line 104 of file overnightindexedswap.cpp.
References QuantLib::Instrument::calculate(), QuantLib::Swap::legBPS_, and QL_REQUIRE.
Referenced by fairRate().
{
        calculate();
        QL_REQUIRE(legBPS_[0] != Null<Real>(), "result not available");
        return legBPS_[0];
    }
Real QuantLib::OvernightIndexedSwap::fixedLegNPV () const
Definition at line 116 of file overnightindexedswap.cpp.
References QuantLib::Instrument::calculate(), QuantLib::Swap::legNPV_, and QL_REQUIRE.
{
        calculate();
        QL_REQUIRE(legNPV_[0] != Null<Real>(), "result not available");
        return legNPV_[0];
    }
Rate QuantLib::OvernightIndexedSwap::fixedRate () const [inline]
Definition at line 65 of file overnightindexedswap.hpp.
References fixedRate_.
{ return fixedRate_; }
void QuantLib::OvernightIndexedSwap::initialize (const Schedule & schedule) [private]
Definition at line 62 of file overnightindexedswap.cpp.
References fixedDC_, fixedRate_, QuantLib::Swap::legs_, nominals_, overnightIndex_, Payer, QuantLib::Swap::payer_, QL_FAIL, Receiver, QuantLib::Observer::registerWith(), spread_, type_, QuantLib::FixedRateLeg::withCouponRates(), QuantLib::OvernightLeg::withNotionals(), QuantLib::FixedRateLeg::withNotionals(), and QuantLib::OvernightLeg::withSpreads().
Referenced by OvernightIndexedSwap().
{
        if (fixedDC_==DayCounter())
            fixedDC_ = overnightIndex_->dayCounter();
        legs_[0] = FixedRateLeg(schedule)
            .withNotionals(nominals_)
            .withCouponRates(fixedRate_, fixedDC_);
        legs_[1] = OvernightLeg(schedule, overnightIndex_)
            .withNotionals(nominals_)
            .withSpreads(spread_);
        for (Size j=0; j<2; ++j) {
            for (Leg::iterator i = legs_[j].begin(); i!= legs_[j].end(); ++i)
                registerWith(*i);
        }
        switch (type_) {
          case Payer:
            payer_[0] = -1.0;
            payer_[1] = +1.0;
            break;
          case Receiver:
            payer_[0] = +1.0;
            payer_[1] = -1.0;
            break;
          default:
            QL_FAIL("Unknown overnight-swap type");
        }
    }
Real QuantLib::OvernightIndexedSwap::nominal () const [inline]
Definition at line 103 of file overnightindexedswap.hpp.
References nominals_, and QL_REQUIRE.
{
        QL_REQUIRE(nominals_.size()==1, "varying nominals");
        return nominals_[0];
    }
std::vector<Real> QuantLib::OvernightIndexedSwap::nominals () const [inline]
Definition at line 60 of file overnightindexedswap.hpp.
References nominals_.
{ return nominals_; }
const boost::shared_ptr<OvernightIndex>& QuantLib::OvernightIndexedSwap::overnightIndex ()
const Leg& QuantLib::OvernightIndexedSwap::overnightLeg () const [inline]
Definition at line 72 of file overnightindexedswap.hpp.
References QuantLib::Swap::legs_.
{ return legs_[1]; }
Real QuantLib::OvernightIndexedSwap::overnightLegBPS () const
Definition at line 110 of file overnightindexedswap.cpp.
References QuantLib::Instrument::calculate(), QuantLib::Swap::legBPS_, and QL_REQUIRE.
Referenced by fairSpread().
{
        calculate();
        QL_REQUIRE(legBPS_[1] != Null<Real>(), "result not available");
        return legBPS_[1];
    }
Real QuantLib::OvernightIndexedSwap::overnightLegNPV () const
Definition at line 122 of file overnightindexedswap.cpp.
References QuantLib::Instrument::calculate(), QuantLib::Swap::legNPV_, and QL_REQUIRE.
{
        calculate();
        QL_REQUIRE(legNPV_[1] != Null<Real>(), "result not available");
        return legNPV_[1];
    }
Frequency QuantLib::OvernightIndexedSwap::paymentFrequency () [inline]
Definition at line 63 of file overnightindexedswap.hpp.
References paymentFrequency_.
{ return paymentFrequency_; }
Spread QuantLib::OvernightIndexedSwap::spread () [inline]
Definition at line 69 of file overnightindexedswap.hpp.
References spread_.
{ return spread_; }
Type QuantLib::OvernightIndexedSwap::type () const [inline]
Definition at line 58 of file overnightindexedswap.hpp.
References type_.
{ return type_; }
Member Data Documentation
DayCounter QuantLib::OvernightIndexedSwap::fixedDC_ [private]
Definition at line 94 of file overnightindexedswap.hpp.
Referenced by fixedDayCount(), and initialize().
Rate QuantLib::OvernightIndexedSwap::fixedRate_ [private]
Definition at line 93 of file overnightindexedswap.hpp.
Referenced by fairRate(), fixedRate(), and initialize().
std::vector<Real> QuantLib::OvernightIndexedSwap::nominals_ [private]
Definition at line 88 of file overnightindexedswap.hpp.
Referenced by initialize(), nominal(), and nominals().
boost::shared_ptr<OvernightIndex> QuantLib::OvernightIndexedSwap::overnightIndex_ [private]
Definition at line 96 of file overnightindexedswap.hpp.
Referenced by initialize().
Frequency QuantLib::OvernightIndexedSwap::paymentFrequency_ [private]
Definition at line 90 of file overnightindexedswap.hpp.
Referenced by paymentFrequency().
Spread QuantLib::OvernightIndexedSwap::spread_ [private]
Definition at line 97 of file overnightindexedswap.hpp.
Referenced by fairSpread(), initialize(), and spread().
Type QuantLib::OvernightIndexedSwap::type_ [private]
Definition at line 87 of file overnightindexedswap.hpp.
Referenced by initialize(), and type().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/overnightindexedswap.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/overnightindexedswap.cpp