QuantLib: QuantLib::ExtendedCoxIngersollRoss Class Reference
QuantLib::ExtendedCoxIngersollRoss Class Reference
Extended Cox-Ingersoll-Ross model class.
#include <extendedcoxingersollross.hpp>
Classes
class Dynamics
Short-rate dynamics in the extended Cox-Ingersoll-Ross model.
class FittingParameter
Analytical term-structure fitting parameter \(\varphi(t) \).
Public Member Functions
ExtendedCoxIngersollRoss (const Handle< YieldTermStructure > &termStructure, Real theta=0.1, Real k=0.1, Real sigma=0.1, Real x0=0.05)
boost::shared_ptr< Lattice > tree (const TimeGrid &grid) const
Return by default a trinomial recombining tree.
boost::shared_ptr
< ShortRateDynamics > dynamics () const
returns the short-rate dynamics
Real discountBondOption (Option::Type type, Real strike, Time maturity, Time bondMaturity) const
Protected Member Functions
void generateArguments ()
Real A (Time t, Time T) const
Private Attributes
Parameter phi_
Detailed Description
Extended Cox-Ingersoll-Ross model class.
This class implements the extended Cox-Ingersoll-Ross model defined by
\[ dr_t = (\theta(t) - \alpha r_t)dt + \sqrt{r_t}\sigma dW_t . \]
Bug:
this class was not tested enough to guarantee its functionality.
Definition at line 43 of file extendedcoxingersollross.hpp.
Constructor & Destructor Documentation
QuantLib::ExtendedCoxIngersollRoss::ExtendedCoxIngersollRoss (const Handle< YieldTermStructure > & termStructure, Real theta = 0.1, Real k = 0.1, Real sigma = 0.1, Real x0 = 0.05)
Definition at line 26 of file extendedcoxingersollross.cpp.
References generateArguments().
    : CoxIngersollRoss(x0, theta, k, sigma),
      TermStructureConsistentModel(termStructure) {
        generateArguments();
    }
Member Function Documentation
Real QuantLib::ExtendedCoxIngersollRoss::A (Time t, Time T) const [protected, virtual]
Reimplemented from QuantLib::CoxIngersollRoss.
Definition at line 51 of file extendedcoxingersollross.cpp.
References QuantLib::CoxIngersollRoss::A(), QuantLib::CoxIngersollRoss::B(), phi_, QuantLib::TermStructureConsistentModel::termStructure(), QuantLib::CalibratedModel::value(), and QuantLib::CoxIngersollRoss::x0().
{
        Real pt = termStructure()->discount(t);
        Real ps = termStructure()->discount(s);
        Real value = CoxIngersollRoss::A(t,s)*std::exp(B(t,s)*phi_(t))*
            (ps*CoxIngersollRoss::A(0.0,t)*std::exp(-B(0.0,t)*x0()))/
            (pt*CoxIngersollRoss::A(0.0,s)*std::exp(-B(0.0,s)*x0()));
        return value;
    }
Real QuantLib::ExtendedCoxIngersollRoss::discountBondOption (Option::Type type, Real strike, Time maturity, Time bondMaturity) const [virtual]
Reimplemented from QuantLib::CoxIngersollRoss.
Definition at line 60 of file extendedcoxingersollross.cpp.
References QuantLib::CoxIngersollRoss::A(), QuantLib::CoxIngersollRoss::B(), anonymous_namespace{marketmodel.cpp}::b, QuantLib::Option::Call, QuantLib::Continuous, QuantLib::CoxIngersollRoss::k(), QuantLib::NoFrequency, phi_, QuantLib::Option::Put, QL_EPSILON, QL_FAIL, QL_REQUIRE, QuantLib::CoxIngersollRoss::sigma(), QuantLib::TermStructureConsistentModel::termStructure(), and QuantLib::CoxIngersollRoss::theta().
{
        QL_REQUIRE(strike>0.0, "strike must be positive");
        DiscountFactor discountT = termStructure()->discount(t);
        DiscountFactor discountS = termStructure()->discount(s);
        if (t < QL_EPSILON) {
            switch(type) {
              case Option::Call:
                return std::max<Real>(discountS - strike, 0.0);
              case Option::Put:
                return std::max<Real>(strike - discountS, 0.0);
              default: QL_FAIL("unsupported option type");
            }
        }
        Real sigma2 = sigma()*sigma();
        Real h = std::sqrt(k()*k() + 2.0*sigma2);
        Real r0 = termStructure()->forwardRate(0.0, 0.0,
                                               Continuous, NoFrequency);
        Real b = B(t,s);
        Real rho = 2.0*h/(sigma2*(std::exp(h*t) - 1.0));
        Real psi = (k() + h)/sigma2;
        Real df = 4.0*k()*theta()/sigma2;
        Real ncps = 2.0*rho*rho*(r0-phi_(0.0))*std::exp(h*t)/(rho+psi+b);
        Real ncpt = 2.0*rho*rho*(r0-phi_(0.0))*std::exp(h*t)/(rho+psi);
        NonCentralChiSquareDistribution chis(df, ncps);
        NonCentralChiSquareDistribution chit(df, ncpt);
        Real z = std::log(CoxIngersollRoss::A(t,s)/strike)/b;
        Real call = discountS*chis(2.0*z*(rho+psi+b)) -
            strike*discountT*chit(2.0*z*(rho+psi));
        if (type == Option::Call)
            return call;
        else
            return call - discountS + strike*discountT;
    }
boost::shared_ptr< OneFactorModel::ShortRateDynamics > QuantLib::ExtendedCoxIngersollRoss::dynamics () const [inline, virtual]
returns the short-rate dynamics
Reimplemented from QuantLib::CoxIngersollRoss.
Definition at line 148 of file extendedcoxingersollross.hpp.
References QuantLib::CoxIngersollRoss::k(), phi_, QuantLib::CoxIngersollRoss::sigma(), QuantLib::CoxIngersollRoss::theta(), and QuantLib::CoxIngersollRoss::x0().
{
        return boost::shared_ptr<ShortRateDynamics>(
                            new Dynamics(phi_, theta(), k() , sigma(), x0()));
    }
void QuantLib::ExtendedCoxIngersollRoss::generateArguments () [inline, protected, virtual]
Reimplemented from QuantLib::CalibratedModel.
Definition at line 153 of file extendedcoxingersollross.hpp.
References QuantLib::CoxIngersollRoss::k(), phi_, QuantLib::CoxIngersollRoss::sigma(), QuantLib::TermStructureConsistentModel::termStructure(), QuantLib::CoxIngersollRoss::theta(), and QuantLib::CoxIngersollRoss::x0().
Referenced by ExtendedCoxIngersollRoss().
{
        phi_ = FittingParameter(termStructure(), theta(), k(), sigma(), x0());
    }
boost::shared_ptr< Lattice > QuantLib::ExtendedCoxIngersollRoss::tree (const TimeGrid & grid) const [virtual]
Return by default a trinomial recombining tree.
Reimplemented from QuantLib::CoxIngersollRoss.
Definition at line 34 of file extendedcoxingersollross.cpp.
References QuantLib::Parameter::implementation(), QuantLib::CoxIngersollRoss::k(), QuantLib::anonymous_namespace{bjerksundstenslandengine.cpp}::phi(), QuantLib::CoxIngersollRoss::sigma(), QuantLib::TermStructureConsistentModel::termStructure(), QuantLib::CoxIngersollRoss::theta(), and QuantLib::CoxIngersollRoss::x0().
{
        TermStructureFittingParameter phi(termStructure());
        boost::shared_ptr<Dynamics> numericDynamics(
                              new Dynamics(phi, theta(), k(), sigma(), x0()));
        boost::shared_ptr<TrinomialTree> trinomial(
                   new TrinomialTree(numericDynamics->process(), grid, true));
        typedef TermStructureFittingParameter::NumericalImpl NumericalImpl;
        boost::shared_ptr<NumericalImpl> impl =
            boost::dynamic_pointer_cast<NumericalImpl>(phi.implementation());
        return boost::shared_ptr<Lattice>(
                   new ShortRateTree(trinomial, numericDynamics, impl, grid));
    }
Member Data Documentation
Parameter QuantLib::ExtendedCoxIngersollRoss::phi_ [private]
Definition at line 68 of file extendedcoxingersollross.hpp.
Referenced by A(), discountBondOption(), dynamics(), and generateArguments().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/shortrate/onefactormodels/extendedcoxingersollross.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/shortrate/onefactormodels/extendedcoxingersollross.cpp