QuantLib: QuantLib::GeneralStatistics Class Reference
QuantLib::GeneralStatistics Class Reference
Statistics tool.
#include <generalstatistics.hpp>
Public Types
typedef Real value_type
Public Member Functions
GeneralStatistics ()
Inspectors
Size samples () const
number of samples collected
const std::vector< std::pair
< Real, Real > > & data () const
collected data
Real weightSum () const
sum of data weights
Real mean () const
Real variance () const
Real standardDeviation () const
Real errorEstimate () const
Real skewness () const
Real kurtosis () const
Real min () const
Real max () const
template<class Func , class Predicate >
std::pair< Real, Size > expectationValue (const Func &f, const Predicate &inRange) const
Real percentile (Real y) const
Real topPercentile (Real y) const
Modifiers
void add (Real value, Real weight=1.0)
adds a datum to the set, possibly with a weight
template<class DataIterator >
void addSequence (DataIterator begin, DataIterator end)
adds a sequence of data to the set, with default weight
template<class DataIterator , class WeightIterator >
void addSequence (DataIterator begin, DataIterator end, WeightIterator wbegin)
adds a sequence of data to the set, each with its weight
void reset ()
resets the data to a null set
void reserve (Size n) const
informs the internal storage of a planned increase in size
void sort () const
sort the data set in increasing order
Private Attributes
std::vector< std::pair< Real,
Real > > samples_
bool sorted_
Detailed Description
Statistics tool.
This class accumulates a set of data and returns their statistics (e.g: mean, variance, skewness, kurtosis, error estimation, percentile, etc.) based on the empirical distribution (no gaussian assumption)
It doesn't suffer the numerical instability problem of IncrementalStatistics. The downside is that it stores all samples, thus increasing the memory requirements.
Definition at line 45 of file generalstatistics.hpp.
Member Typedef Documentation
typedef Real QuantLib::GeneralStatistics::value_type
Definition at line 47 of file generalstatistics.hpp.
Constructor & Destructor Documentation
QuantLib::GeneralStatistics::GeneralStatistics () [inline]
Definition at line 188 of file generalstatistics.hpp.
References reset().
{
        reset();
    }
Member Function Documentation
void QuantLib::GeneralStatistics::add (Real value, Real weight = 1.0) [inline]
adds a datum to the set, possibly with a weight
Precondition:
weights must be positive or null
Definition at line 222 of file generalstatistics.hpp.
References QL_REQUIRE, samples_, and sorted_.
Referenced by addSequence(), HybridHestonHullWhiteProcessTest::testCallableEquityPricing(), SwingOptionTest::testExtOUJumpSwingOption(), VPPTest::testKlugeExtOUSpreadOption(), LiborMarketModelTest::testSwaptionPricing(), and VPPTest::testVPPPricing().
{
        QL_REQUIRE(weight>=0.0, "negative weight not allowed");
        samples_.push_back(std::make_pair(value,weight));
        sorted_ = false;
    }
template<class DataIterator > void QuantLib::GeneralStatistics::addSequence (DataIterator begin, DataIterator end) [inline]
adds a sequence of data to the set, with default weight
Definition at line 159 of file generalstatistics.hpp.
References add().
{
            for (;begin!=end;++begin)
                add(*begin);
        }
template<class DataIterator , class WeightIterator > void QuantLib::GeneralStatistics::addSequence (DataIterator begin, DataIterator end, WeightIterator wbegin) [inline]
adds a sequence of data to the set, each with its weight
Definition at line 165 of file generalstatistics.hpp.
References add().
{
            for (;begin!=end;++begin,++wbegin)
                add(*begin, *wbegin);
        }
const std::vector< std::pair< Real, Real > > & QuantLib::GeneralStatistics::data () const [inline]
collected data
Definition at line 197 of file generalstatistics.hpp.
References samples_.
{
        return samples_;
    }
Real QuantLib::GeneralStatistics::errorEstimate () const [inline]
returns the error estimate on the mean value, defined as \(\epsilon = \sigma/\sqrt{N}. \)
Definition at line 205 of file generalstatistics.hpp.
References samples(), and variance().
Referenced by HybridHestonHullWhiteProcessTest::testCallableEquityPricing(), SwingOptionTest::testExtOUJumpSwingOption(), VPPTest::testKlugeExtOUSpreadOption(), LiborMarketModelTest::testSwaptionPricing(), and VPPTest::testVPPPricing().
{
        return std::sqrt(variance()/samples());
    }
template<class Func , class Predicate > std::pair<Real,Size> QuantLib::GeneralStatistics::expectationValue (const Func & f, const Predicate & inRange) const [inline]
Expectation value of a function \(f \) on a given range \(\mathcal{R} \), i.e.,
\[ \mathrm{E}\left[f \;|\; \mathcal{R}\right] = \frac{\sum_{x_i \in \mathcal{R}} f(x_i) w_i}{ \sum_{x_i \in \mathcal{R}} w_i}. \]
The range is passed as a boolean function returning true if the argument belongs to the range or false otherwise.
The function returns a pair made of the result and the number of observations in the given range.
Definition at line 115 of file generalstatistics.hpp.
References anonymous_namespace{interpolations.cpp}::f(), anonymous_namespace{matrices.cpp}::N, and samples_.
Referenced by kurtosis(), mean(), skewness(), and variance().
{
            Real num = 0.0, den = 0.0;
            Size N = 0;
            std::vector<std::pair<Real,Real> >::const_iterator i;
            for (i=samples_.begin(); i!=samples_.end(); ++i) {
                Real x = i->first, w = i->second;
                if (inRange(x)) {
                    num += f(x)*w;
                    den += w;
                    N += 1;
                }
            }
            if (N == 0)
                return std::make_pair<Real,Size>(Null<Real>(),0);
            else
                return std::make_pair(num/den,N);
        }
Real QuantLib::GeneralStatistics::kurtosis () const
returns the excess kurtosis, defined as
\[ \frac{N^2(N+1)}{(N-1)(N-2)(N-3)} \frac{\left\langle \left(x-\langle x \rangle \right)^4 \right\rangle}{\sigma^4} - \frac{3(N-1)^2}{(N-2)(N-3)}. \]
The above evaluates to 0 for a Gaussian distribution.
Definition at line 70 of file generalstatistics.cpp.
References QuantLib::compose(), expectationValue(), mean(), anonymous_namespace{matrices.cpp}::N, QL_REQUIRE, samples(), and variance().
{
        Size N = samples();
        QL_REQUIRE(N > 3,
                   "sample number <=3, unsufficient");
        Real x = expectationValue(compose(fourth_power<Real>(),
                                          std::bind2nd(std::minus<Real>(),
                                                       mean())),
                                  everywhere()).first;
        Real sigma2 = variance();
        Real c1 = (N/(N-1.0)) * (N/(N-2.0)) * ((N+1.0)/(N-3.0));
        Real c2 = 3.0 * ((N-1.0)/(N-2.0)) * ((N-1.0)/(N-3.0));
        return c1*(x/(sigma2*sigma2))-c2;
    }
Real QuantLib::GeneralStatistics::max () const [inline]
returns the maximum sample value
Definition at line 215 of file generalstatistics.hpp.
References QL_REQUIRE, samples(), and samples_.
{
        QL_REQUIRE(samples() > 0, "empty sample set");
        return std::max_element(samples_.begin(),
                                samples_.end())->first;
    }
Real QuantLib::GeneralStatistics::mean () const
returns the mean, defined as
\[ \langle x \rangle = \frac{\sum w_i x_i}{\sum w_i}. \]
Definition at line 35 of file generalstatistics.cpp.
References expectationValue(), anonymous_namespace{matrices.cpp}::N, QL_REQUIRE, and samples().
Referenced by kurtosis(), skewness(), HybridHestonHullWhiteProcessTest::testCallableEquityPricing(), SwingOptionTest::testExtOUJumpSwingOption(), VPPTest::testKlugeExtOUSpreadOption(), LiborMarketModelTest::testSwaptionPricing(), VPPTest::testVPPPricing(), and variance().
{
        Size N = samples();
        QL_REQUIRE(N != 0, "empty sample set");
        // eat our own dog food
        return expectationValue(identity<Real>(),
                                everywhere()).first;
    }
Real QuantLib::GeneralStatistics::min () const [inline]
returns the minimum sample value
Definition at line 209 of file generalstatistics.hpp.
References QL_REQUIRE, samples(), and samples_.
{
        QL_REQUIRE(samples() > 0, "empty sample set");
        return std::min_element(samples_.begin(),
                                samples_.end())->first;
    }
Real QuantLib::GeneralStatistics::percentile (Real y) const
\(y \)-th percentile, defined as the value \(\bar{x} \) such that
\[ y = \frac{\sum_{x_i < \bar{x}} w_i}{ \sum_i w_i} \]
Precondition:
\(y \) must be in the range \((0-1]. \)
Definition at line 87 of file generalstatistics.cpp.
References QL_REQUIRE, samples_, sort(), and weightSum().
{
        QL_REQUIRE(percent > 0.0 && percent <= 1.0,
                   "percentile (" << percent << ") must be in (0.0, 1.0]");
        Real sampleWeight = weightSum();
        QL_REQUIRE(sampleWeight>0.0,
                   "empty sample set");
        sort();
        std::vector<std::pair<Real,Real> >::iterator k, l;
        k = samples_.begin();
        l = samples_.end()-1;
        /* the sum of weight is non null, therefore there's
           at least one sample */
        Real integral = k->second, target = percent*sampleWeight;
        while (integral < target && k != l) {
            k++;
            integral += k->second;
        }
        return k->first;
    }
void QuantLib::GeneralStatistics::reserve (Size n) const [inline]
informs the internal storage of a planned increase in size
Definition at line 233 of file generalstatistics.hpp.
References samples_.
{
        samples_.reserve(n);
    }
void QuantLib::GeneralStatistics::reset () [inline]
resets the data to a null set
Definition at line 228 of file generalstatistics.hpp.
References samples_, and sorted_.
Referenced by GeneralStatistics(), and VPPTest::testVPPPricing().
{
        samples_ = std::vector<std::pair<Real,Real> >();
        sorted_ = true;
    }
Size QuantLib::GeneralStatistics::samples () const [inline]
number of samples collected
Definition at line 192 of file generalstatistics.hpp.
References samples_.
Referenced by errorEstimate(), kurtosis(), max(), mean(), min(), skewness(), and variance().
{
        return samples_.size();
    }
Real QuantLib::GeneralStatistics::skewness () const
returns the skewness, defined as
\[ \frac{N^2}{(N-1)(N-2)} \frac{\left\langle \left(x-\langle x \rangle \right)^3 \right\rangle}{\sigma^3}. \]
The above evaluates to 0 for a Gaussian distribution.
Definition at line 56 of file generalstatistics.cpp.
References QuantLib::compose(), expectationValue(), mean(), anonymous_namespace{matrices.cpp}::N, QL_REQUIRE, samples(), anonymous_namespace{distributions.cpp}::sigma, and standardDeviation().
{
        Size N = samples();
        QL_REQUIRE(N > 2,
                   "sample number <=2, unsufficient");
        Real x = expectationValue(compose(cube<Real>(),
                                          std::bind2nd(std::minus<Real>(),
                                                       mean())),
                                  everywhere()).first;
        Real sigma = standardDeviation();
        return (x/(sigma*sigma*sigma))*(N/(N-1.0))*(N/(N-2.0));
    }
void QuantLib::GeneralStatistics::sort () const [inline]
sort the data set in increasing order
Definition at line 237 of file generalstatistics.hpp.
References samples_, and sorted_.
Referenced by percentile(), and topPercentile().
{
        if (!sorted_) {
            std::sort(samples_.begin(), samples_.end());
            sorted_ = true;
        }
    }
Real QuantLib::GeneralStatistics::standardDeviation () const [inline]
returns the standard deviation \(\sigma \), defined as the square root of the variance.
Definition at line 201 of file generalstatistics.hpp.
References variance().
Referenced by skewness().
{
        return std::sqrt(variance());
    }
Real QuantLib::GeneralStatistics::topPercentile (Real y) const
\(y \)-th top percentile, defined as the value \(\bar{x} \) such that
\[ y = \frac{\sum_{x_i > \bar{x}} w_i}{ \sum_i w_i} \]
Precondition:
\(y \) must be in the range \((0-1]. \)
Definition at line 111 of file generalstatistics.cpp.
References QL_REQUIRE, samples_, sort(), and weightSum().
{
        QL_REQUIRE(percent > 0.0 && percent <= 1.0,
                   "percentile (" << percent << ") must be in (0.0, 1.0]");
        Real sampleWeight = weightSum();
        QL_REQUIRE(sampleWeight > 0.0,
                   "empty sample set");
        sort();
        std::vector<std::pair<Real,Real> >::reverse_iterator k, l;
        k = samples_.rbegin();
        l = samples_.rend()-1;
        /* the sum of weight is non null, therefore there's
           at least one sample */
        Real integral = k->second, target = percent*sampleWeight;
        while (integral < target && k != l) {
            k++;
            integral += k->second;
        }
        return k->first;
    }
Real QuantLib::GeneralStatistics::variance () const
returns the variance, defined as
\[ \sigma^2 = \frac{N}{N-1} \left\langle \left(x-\langle x \rangle \right)^2 \right\rangle. \]
Definition at line 43 of file generalstatistics.cpp.
References QuantLib::compose(), expectationValue(), mean(), anonymous_namespace{matrices.cpp}::N, QL_REQUIRE, and samples().
Referenced by errorEstimate(), kurtosis(), and standardDeviation().
{
        Size N = samples();
        QL_REQUIRE(N > 1,
                   "sample number <=1, unsufficient");
        // Subtract the mean and square. Repeat on the whole range.
        // Hopefully, the whole thing will be inlined in a single loop.
        Real s2 = expectationValue(compose(square<Real>(),
                                           std::bind2nd(std::minus<Real>(),
                                                        mean())),
                                   everywhere()).first;
        return s2*N/(N-1.0);
    }
Real QuantLib::GeneralStatistics::weightSum () const
sum of data weights
Definition at line 26 of file generalstatistics.cpp.
References samples_.
Referenced by percentile(), and topPercentile().
{
        Real result = 0.0;
        std::vector<std::pair<Real,Real> >::const_iterator it;
        for (it=samples_.begin(); it!=samples_.end(); it++) {
            result += it->second;
        }
        return result;
    }
Member Data Documentation
std::vector<std::pair<Real,Real> > QuantLib::GeneralStatistics::samples_ [mutable, private]
Definition at line 181 of file generalstatistics.hpp.
Referenced by add(), data(), expectationValue(), max(), min(), percentile(), reserve(), reset(), samples(), sort(), topPercentile(), and weightSum().
bool QuantLib::GeneralStatistics::sorted_ [mutable, private]
Definition at line 182 of file generalstatistics.hpp.
Referenced by add(), reset(), and sort().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/statistics/generalstatistics.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/math/statistics/generalstatistics.cpp