QuantLib: anonymous_namespace{optimizers.cpp}::OneDimensionalPolynomialDegreeN Class Reference
anonymous_namespace{optimizers.cpp}::OneDimensionalPolynomialDegreeN Class Reference
Public Member Functions
OneDimensionalPolynomialDegreeN (const Array &coefficients)
Real value (const Array &x) const
method to overload to compute the cost function value in x
Disposable< Array > values (const Array &x) const
method to overload to compute the cost function values in x
Private Attributes
const Array coefficients_
const Size polynomialDegree_
bool odd
Detailed Description
Definition at line 47 of file optimizers.cpp.
Constructor & Destructor Documentation
anonymous_namespace{optimizers.cpp}::OneDimensionalPolynomialDegreeN::OneDimensionalPolynomialDegreeN (const Array & coefficients) [inline]
Definition at line 49 of file optimizers.cpp.
        : coefficients_(coefficients),
          polynomialDegree_(coefficients.size()-1),odd(true) {}
Member Function Documentation
Real anonymous_namespace{optimizers.cpp}::OneDimensionalPolynomialDegreeN::value (const Array & x) const [inline, virtual]
method to overload to compute the cost function value in x
Implements QuantLib::CostFunction.
Definition at line 53 of file optimizers.cpp.
References QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow(), QL_REQUIRE, and QuantLib::Array::size().
{
            QL_REQUIRE(x.size()==1,"independent variable must be 1 dimensional");
            Real y = 0;
            for (Size i=0; i<=polynomialDegree_; ++i)
                y += coefficients_[i]*std::pow(x[0],static_cast<int>(i));
            return y;
        }
Disposable<Array> anonymous_namespace{optimizers.cpp}::OneDimensionalPolynomialDegreeN::values (const Array & x) const [inline, virtual]
method to overload to compute the cost function values in x
Implements QuantLib::CostFunction.
Definition at line 61 of file optimizers.cpp.
References QL_REQUIRE, and QuantLib::Array::size().
{
            QL_REQUIRE(x.size()==1,"independent variable must be 1 dimensional");
            Array y(1);
            y[0] = value(x);
            return y;
        }
Member Data Documentation
const Array anonymous_namespace{optimizers.cpp}::OneDimensionalPolynomialDegreeN::coefficients_ [private]
Definition at line 69 of file optimizers.cpp.
bool anonymous_namespace{optimizers.cpp}::OneDimensionalPolynomialDegreeN::odd [mutable, private]
Definition at line 71 of file optimizers.cpp.
const Size anonymous_namespace{optimizers.cpp}::OneDimensionalPolynomialDegreeN::polynomialDegree_ [private]
Definition at line 70 of file optimizers.cpp.
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/optimizers.cpp