QuantLib: QuantLib::GarmanKlassAbstract Class Reference
QuantLib::GarmanKlassAbstract Class Reference
Garman-Klass volatility model.
#include <garmanklass.hpp>
Public Member Functions
GarmanKlassAbstract (Real y)
TimeSeries< Volatility > calculate (const TimeSeries< IntervalPrice > &quoteSeries)
Protected Member Functions
virtual Real calculatePoint (const IntervalPrice &p)=0
Protected Attributes
Real yearFraction_
Detailed Description
Garman-Klass volatility model.
This class implements a concrete volatility model based on high low formulas using the method of Garman and Klass in their paper "On the Estimation of the Security Price from Historical Data" at http://www.fea.com/resources/pdf/a_estimation_of_security_price.pdf
Volatilities are assumed to be expressed on an annual basis.
Definition at line 41 of file garmanklass.hpp.
Constructor & Destructor Documentation
QuantLib::GarmanKlassAbstract::GarmanKlassAbstract (Real y) [inline]
Definition at line 47 of file garmanklass.hpp.
                                    :
        yearFraction_(y) {}
Member Function Documentation
TimeSeries<Volatility> QuantLib::GarmanKlassAbstract::calculate (const TimeSeries< IntervalPrice > & quoteSeries) [inline, virtual]
Implements QuantLib::LocalVolatilityEstimator< IntervalPrice >.
Reimplemented in QuantLib::GarmanKlassOpenClose< GarmanKlassSimpleSigma >, QuantLib::GarmanKlassOpenClose< GarmanKlassSigma4 >, and QuantLib::GarmanKlassOpenClose< ParkinsonSigma >.
Definition at line 50 of file garmanklass.hpp.
References QuantLib::TimeSeries< T, Container >::begin(), calculatePoint(), QuantLib::TimeSeries< T, Container >::end(), and yearFraction_.
{
            TimeSeries<Volatility> retval;
            TimeSeries<IntervalPrice>::const_iterator prev, next, cur, start;
            start = quoteSeries.begin();
            for (cur = start; cur != quoteSeries.end(); ++cur) {
                retval[cur->first] =
                    std::sqrt(std::fabs(calculatePoint(cur->second))/
                              yearFraction_);
            }
            return retval;
        }
virtual Real QuantLib::GarmanKlassAbstract::calculatePoint (const IntervalPrice & p) [protected, pure virtual]
Implemented in QuantLib::GarmanKlassSigma5, QuantLib::GarmanKlassSigma4, QuantLib::ParkinsonSigma, and QuantLib::GarmanKlassSimpleSigma.
Referenced by calculate().
Member Data Documentation
Real QuantLib::GarmanKlassAbstract::yearFraction_ [protected]
Definition at line 44 of file garmanklass.hpp.
Referenced by calculate().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/volatility/garmanklass.hpp