QuantLib: QuantLib::SaudiArabia::TadawulImpl Class Reference
QuantLib::SaudiArabia::TadawulImpl Class Reference
Public Member Functions
std::string name () const
bool isWeekend (Weekday) const
bool isBusinessDay (const Date &) const
Detailed Description
Definition at line 52 of file saudiarabia.hpp.
Member Function Documentation
bool QuantLib::SaudiArabia::TadawulImpl::isBusinessDay (const Date & date) const [virtual]
Implements QuantLib::Calendar::Impl.
Definition at line 43 of file saudiarabia.cpp.
References QuantLib::August, anonymous_namespace{marketmodel.cpp}::d, QuantLib::Date::dayOfMonth(), QuantLib::December, QuantLib::February, QuantLib::Calendar::isWeekend(), QuantLib::January, QuantLib::March, QuantLib::Date::month(), QuantLib::November, QuantLib::September, QuantLib::Date::weekday(), and QuantLib::Date::year().
{
        Weekday w = date.weekday();
        Day d = date.dayOfMonth();
        Month m = date.month();
        Year y = date.year();
        if (isWeekend(w)
            // National Day
            || (d == 23 && m == September)
            // Eid Al-Adha
            || (d >= 1 && d <= 6 && m == February && y==2004)
            || (d >= 21 && d <= 25 && m == January && y==2005)
            || (d >= 26 && m == November && y==2009)
            || (d <= 4 && m == December && y==2009)
            || (d >= 11 && d <= 19 && m == November && y==2010)
            // Eid Al-Fitr
            || (d >= 25 && d <= 29 && m == November && y==2004)
            || (d >= 14 && d <= 18 && m == November && y==2005)
            || (d >= 25 && m == August && y==2011)
            || (d <= 2 && m == September && y==2011)
            // other one-shot holidays
            || (d == 26 && m == February && y==2011)
            || (d == 19 && m == March && y==2011)
            )
            return false;
        return true;
    }
bool QuantLib::SaudiArabia::TadawulImpl::isWeekend (Weekday w) const [virtual]
Implements QuantLib::Calendar::Impl.
Definition at line 39 of file saudiarabia.cpp.
References QuantLib::Friday, and QuantLib::Thursday.
{
        return w == Thursday || w == Friday;
    }
std::string QuantLib::SaudiArabia::TadawulImpl::name () const [inline, virtual]
Implements QuantLib::Calendar::Impl.
Definition at line 54 of file saudiarabia.hpp.
{ return "Tadawul"; }
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/time/calendars/saudiarabia.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/time/calendars/saudiarabia.cpp