QuantLib: QuantLib::OvernightIndexedSwapIndex Class Reference
QuantLib::OvernightIndexedSwapIndex Class Reference
base class for overnight indexed swap indexes
#include <swapindex.hpp>
Public Member Functions
OvernightIndexedSwapIndex (const std::string &familyName, const Period &tenor, Natural settlementDays, Currency currency, const boost::shared_ptr< OvernightIndex > &overnightIndex)
Inspectors
boost::shared_ptr< OvernightIndex > overnightIndex () const
boost::shared_ptr
< OvernightIndexedSwap > underlyingSwap (const Date &fixingDate) const
Protected Attributes
boost::shared_ptr< OvernightIndex > overnightIndex_
boost::shared_ptr
< OvernightIndexedSwap > lastSwap_
Date lastFixingDate_
Detailed Description
base class for overnight indexed swap indexes
Definition at line 105 of file swapindex.hpp.
Constructor & Destructor Documentation
QuantLib::OvernightIndexedSwapIndex::OvernightIndexedSwapIndex (const std::string & familyName, const Period & tenor, Natural settlementDays, Currency currency, const boost::shared_ptr< OvernightIndex > & overnightIndex)
Definition at line 162 of file swapindex.cpp.
    : SwapIndex(familyName, tenor, settlementDays,
                currency, overnightIndex->fixingCalendar(),
                1*Years, ModifiedFollowing, overnightIndex->dayCounter(),
                overnightIndex),
      overnightIndex_(overnightIndex) {}
Member Function Documentation
boost::shared_ptr< OvernightIndex > QuantLib::OvernightIndexedSwapIndex::overnightIndex () const [inline]
Definition at line 141 of file swapindex.hpp.
References overnightIndex_.
{
        return overnightIndex_;
    }
boost::shared_ptr< OvernightIndexedSwap > QuantLib::OvernightIndexedSwapIndex::underlyingSwap (const Date & fixingDate) const
Warning:
Relinking the term structure underlying the index will not have effect on the returned swap.
Reimplemented from QuantLib::SwapIndex.
Definition at line 176 of file swapindex.cpp.
References QuantLib::InterestRateIndex::dayCounter_, QuantLib::InterestRateIndex::fixingDate(), lastFixingDate_, lastSwap_, overnightIndex_, QL_REQUIRE, QuantLib::SwapIndex::tenor_, QuantLib::InterestRateIndex::valueDate(), QuantLib::MakeOIS::withEffectiveDate(), and QuantLib::MakeOIS::withFixedLegDayCount().
{
        QL_REQUIRE(fixingDate!=Date(), "null fixing date");
        // caching mechanism
        if (lastFixingDate_!=fixingDate) {
            Rate fixedRate = 0.0;
            lastSwap_ = MakeOIS(tenor_, overnightIndex_, fixedRate)
                .withEffectiveDate(valueDate(fixingDate))
                .withFixedLegDayCount(dayCounter_);
            lastFixingDate_ = fixingDate;
        }
        return lastSwap_;
    }
Member Data Documentation
Date QuantLib::OvernightIndexedSwapIndex::lastFixingDate_ [mutable, protected]
Reimplemented from QuantLib::SwapIndex.
Definition at line 127 of file swapindex.hpp.
Referenced by underlyingSwap().
boost::shared_ptr<OvernightIndexedSwap> QuantLib::OvernightIndexedSwapIndex::lastSwap_ [mutable, protected]
Reimplemented from QuantLib::SwapIndex.
Definition at line 126 of file swapindex.hpp.
Referenced by underlyingSwap().
boost::shared_ptr<OvernightIndex> QuantLib::OvernightIndexedSwapIndex::overnightIndex_ [protected]
Definition at line 123 of file swapindex.hpp.
Referenced by overnightIndex(), and underlyingSwap().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/indexes/swapindex.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/indexes/swapindex.cpp