QuantLib: QuantLib::FastFourierTransform Class Reference
QuantLib::FastFourierTransform Class Reference
FFT implementation.
#include <fastfouriertransform.hpp>
Public Member Functions
FastFourierTransform (std::size_t order)
std::size_t output_size () const
The required size for the output vector.
template<typename InputIterator , typename RandomAccessIterator >
void transform (InputIterator inBegin, InputIterator inEnd, RandomAccessIterator out) const
FFT transform.
template<typename InputIterator , typename RandomAccessIterator >
void inverse_transform (InputIterator inBegin, InputIterator inEnd, RandomAccessIterator out) const
Inverse FFT transform.
Static Public Member Functions
static std::size_t min_order (std::size_t inputSize)
the minimum order required for the given input size
Private Member Functions
template<typename InputIterator , typename RandomAccessIterator >
void transform_impl (InputIterator inBegin, InputIterator inEnd, RandomAccessIterator out, bool inverse) const
Static Private Member Functions
static std::size_t bit_reverse (std::size_t x, std::size_t order)
Private Attributes
std::vector< double > cs_
std::vector< double > sn_
Detailed Description
FFT implementation.
Definition at line 38 of file fastfouriertransform.hpp.
Constructor & Destructor Documentation
QuantLib::FastFourierTransform::FastFourierTransform (std::size_t order) [inline]
Definition at line 47 of file fastfouriertransform.hpp.
References cs_, M_PI, and sn_.
        : cs_(order), sn_(order) {
            std::size_t m = 1 << order;
            cs_[order - 1] = std::cos (2 * M_PI / m);
            sn_[order - 1] = std::sin (2 * M_PI / m);
            for (std::size_t i = order - 1; i > 0; --i) {
                cs_ [i - 1] = cs_[i]*cs_[i] - sn_[i]*sn_[i];
                sn_ [i - 1] = 2*sn_[i]*cs_[i];
            }
        }
Member Function Documentation
static std::size_t QuantLib::FastFourierTransform::bit_reverse (std::size_t x, std::size_t order) [inline, static, private]
Definition at line 112 of file fastfouriertransform.hpp.
Referenced by transform_impl().
{
            std::size_t n = 0;
            for (std::size_t i = 0; i < order; ++i) {
                n <<= 1;
                n |= (x & 1);
                x >>= 1;
            }
            return n;
        }
template<typename InputIterator , typename RandomAccessIterator > void QuantLib::FastFourierTransform::inverse_transform (InputIterator inBegin, InputIterator inEnd, RandomAccessIterator out) const [inline]
Inverse FFT transform.
The output sequence must be allocated by the user.
Definition at line 74 of file fastfouriertransform.hpp.
References transform_impl().
{
            transform_impl(inBegin, inEnd, out, true);
        }
static std::size_t QuantLib::FastFourierTransform::min_order (std::size_t inputSize) [inline, static]
the minimum order required for the given input size
Definition at line 42 of file fastfouriertransform.hpp.
References M_LN2.
Referenced by QuantLib::detail::double_ft(), and FastFourierTransformTest::testInverse().
{
            return static_cast<std::size_t>(
                std::ceil(std::log(static_cast<Real>(inputSize)) / M_LN2));
        }
std::size_t QuantLib::FastFourierTransform::output_size () const [inline]
The required size for the output vector.
Definition at line 59 of file fastfouriertransform.hpp.
References cs_.
Referenced by QuantLib::detail::double_ft().
{
            return (1 << cs_.size());
        }
template<typename InputIterator , typename RandomAccessIterator > void QuantLib::FastFourierTransform::transform (InputIterator inBegin, InputIterator inEnd, RandomAccessIterator out) const [inline]
FFT transform.
The output sequence must be allocated by the user
Definition at line 66 of file fastfouriertransform.hpp.
References transform_impl().
Referenced by QuantLib::detail::double_ft(), QuantLib::FFTEngine::precalculate(), and FastFourierTransformTest::testSimple().
{
            transform_impl(inBegin, inEnd, out, false);
        }
template<typename InputIterator , typename RandomAccessIterator > void QuantLib::FastFourierTransform::transform_impl (InputIterator inBegin, InputIterator inEnd, RandomAccessIterator out, bool inverse) const [inline, private]
Definition at line 83 of file fastfouriertransform.hpp.
References bit_reverse(), cs_, anonymous_namespace{matrices.cpp}::N, QL_REQUIRE, sn_, and anonymous_namespace{quantlibbenchmark.cpp}::t.
Referenced by inverse_transform(), and transform().
{
            typedef
                typename std::iterator_traits<RandomAccessIterator>::value_type
                                                                       complex;
            const std::size_t order = cs_.size();
            const std::size_t N = 1 << order;
            std::size_t i = 0;
            for (; inBegin != inEnd; ++i, ++inBegin) {
                *(out + bit_reverse(i, order)) = *inBegin;
            }
            QL_REQUIRE (i <= N, "FFT order is too small");
            for (std::size_t s = 1; s <= order; ++s) {
                std::size_t m = 1 << s;
                complex w(1.0);
                complex wm(cs_[s-1], inverse ? sn_[s-1] : -sn_[s-1]);
                for (std::size_t j = 0; j < m/2; ++j) {
                    for (std::size_t k = j; k < N; k += m) {
                        complex t = w * (*(out + k + m/2));
                        complex u = *(out + k);
                        *(out + k) = u + t;
                        *(out + k + m/2) = u - t;
                    }
                    w *= wm;
                }
            }
        }
Member Data Documentation
std::vector<double> QuantLib::FastFourierTransform::cs_ [private]
Definition at line 80 of file fastfouriertransform.hpp.
Referenced by FastFourierTransform(), output_size(), and transform_impl().
std::vector<double> QuantLib::FastFourierTransform::sn_ [private]
Definition at line 80 of file fastfouriertransform.hpp.
Referenced by FastFourierTransform(), and transform_impl().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/math/fastfouriertransform.hpp