QuantLib: QuantLib::AnalyticPerformanceEngine Class Reference
QuantLib::AnalyticPerformanceEngine Class Reference
Pricing engine for performance options using analytical formulae.
#include <analyticperformanceengine.hpp>
Public Member Functions
AnalyticPerformanceEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > &process)
void calculate () const
Private Attributes
boost::shared_ptr
< GeneralizedBlackScholesProcess > process_
Detailed Description
Pricing engine for performance options using analytical formulae.
Test:
the correctness of the returned greeks is tested by reproducing numerical derivatives.
Definition at line 38 of file analyticperformanceengine.hpp.
Constructor & Destructor Documentation
QuantLib::AnalyticPerformanceEngine::AnalyticPerformanceEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > & process)
Definition at line 26 of file analyticperformanceengine.cpp.
References process_, and QuantLib::Observer::registerWith().
    : process_(process) {
        registerWith(process_);
    }
Member Function Documentation
void QuantLib::AnalyticPerformanceEngine::calculate () const [virtual]
Implements QuantLib::PricingEngine.
Definition at line 32 of file analyticperformanceengine.cpp.
References QuantLib::CliquetOption::arguments::accruedCoupon, QuantLib::GenericEngine< CliquetOption::arguments, CliquetOption::results >::arguments_, QuantLib::Continuous, QuantLib::BlackCalculator::dividendRho(), QuantLib::anonymous_namespace{yieldtermstructure.cpp}::dt, QuantLib::Exercise::European, QuantLib::Option::arguments::exercise, QuantLib::CliquetOption::arguments::globalCap, QuantLib::CliquetOption::arguments::globalFloor, QuantLib::CliquetOption::arguments::lastFixing, QuantLib::CliquetOption::arguments::localCap, QuantLib::CliquetOption::arguments::localFloor, QuantLib::NoFrequency, QuantLib::Option::arguments::payoff, process_, QL_REQUIRE, QuantLib::CliquetOption::arguments::resetDates, QuantLib::GenericEngine< CliquetOption::arguments, CliquetOption::results >::results_, QuantLib::BlackCalculator::rho(), anonymous_namespace{quantlibbenchmark.cpp}::t, QuantLib::BlackCalculator::value(), QuantLib::Instrument::results::value, QuantLib::BlackCalculator::vega(), and QuantLib::DayCounter::yearFraction().
{
        QL_REQUIRE(arguments_.accruedCoupon == Null<Real>() &&
                   arguments_.lastFixing == Null<Real>(),
                   "this engine cannot price options already started");
        QL_REQUIRE(arguments_.localCap == Null<Real>() &&
                   arguments_.localFloor == Null<Real>() &&
                   arguments_.globalCap == Null<Real>() &&
                   arguments_.globalFloor == Null<Real>(),
                   "this engine cannot price capped/floored options");
        QL_REQUIRE(arguments_.exercise->type() == Exercise::European,
                   "not an European option");
        boost::shared_ptr<PercentageStrikePayoff> moneyness =
            boost::dynamic_pointer_cast<PercentageStrikePayoff>(
                                                           arguments_.payoff);
        QL_REQUIRE(moneyness, "wrong payoff given");
        std::vector<Date> resetDates = arguments_.resetDates;
        resetDates.push_back(arguments_.exercise->lastDate());
        Real underlying = process_->stateVariable()->value();
        QL_REQUIRE(underlying > 0.0, "negative or null underlying");
        boost::shared_ptr<StrikedTypePayoff> payoff(
                        new PlainVanillaPayoff(moneyness->optionType(), 1.0));
        results_.value = 0.0;
        results_.delta = results_.gamma = 0.0;
        results_.theta = 0.0;
        results_.rho = results_.dividendRho = 0.0;
        results_.vega = 0.0;
        for (Size i = 1; i < resetDates.size(); i++) {
            DiscountFactor discount =
                process_->riskFreeRate()->discount(resetDates[i-1]);
            DiscountFactor rDiscount =
                process_->riskFreeRate()->discount(resetDates[i]) /
                process_->riskFreeRate()->discount(resetDates[i-1]);
            DiscountFactor qDiscount =
                process_->dividendYield()->discount(resetDates[i]) /
                process_->dividendYield()->discount(resetDates[i-1]);
            Real forward = (1.0/moneyness->strike())*qDiscount/rDiscount;
            Real variance =
                process_->blackVolatility()->blackForwardVariance(
                                        resetDates[i-1],resetDates[i],
                                        underlying * moneyness->strike());
            BlackCalculator black(payoff, forward, std::sqrt(variance), rDiscount);
            DayCounter rfdc  = process_->riskFreeRate()->dayCounter();
            DayCounter divdc = process_->dividendYield()->dayCounter();
            DayCounter voldc = process_->blackVolatility()->dayCounter();
            results_.value += discount * moneyness->strike() * black.value();
            results_.delta += 0.0;
            results_.gamma += 0.0;
            results_.theta += process_->riskFreeRate()->forwardRate(
                resetDates[i-1], resetDates[i], rfdc, Continuous, NoFrequency) *
                discount * moneyness->strike() * black.value();
            Time dt = rfdc.yearFraction(resetDates[i-1],resetDates[i]);
            Time t = rfdc.yearFraction(
                                  process_->riskFreeRate()->referenceDate(),
                                  resetDates[i-1]);
            results_.rho += discount * moneyness->strike() *
                (black.rho(dt) - t * black.value());
            dt = divdc.yearFraction(resetDates[i-1],resetDates[i]);
            results_.dividendRho += discount * moneyness->strike() *
                black.dividendRho(dt);
            dt = voldc.yearFraction(resetDates[i-1], resetDates[i]);
            results_.vega += discount * moneyness->strike() * black.vega(dt);
        }
    }
Member Data Documentation
boost::shared_ptr<GeneralizedBlackScholesProcess> QuantLib::AnalyticPerformanceEngine::process_ [private]
Definition at line 44 of file analyticperformanceengine.hpp.
Referenced by AnalyticPerformanceEngine(), and calculate().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/cliquet/analyticperformanceengine.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/cliquet/analyticperformanceengine.cpp