QuantLib: MarketModelCmsTest Class Reference
MarketModelCmsTest Class Reference
#include <marketmodel_cms.hpp>
Static Public Member Functions
static void testMultiStepCmSwapsAndSwaptions ()
static
boost::unit_test_framework::test_suite * suite ()
Detailed Description
Definition at line 29 of file marketmodel_cms.hpp.
Member Function Documentation
test_suite * MarketModelCmsTest::suite () [static]
Definition at line 540 of file marketmodel_cms.cpp.
References QUANTLIB_TEST_CASE, and testMultiStepCmSwapsAndSwaptions().
Referenced by init_unit_test_suite().
{
    test_suite* suite = BOOST_TEST_SUITE("CMS Market-model tests");
    suite->add(QUANTLIB_TEST_CASE(
                      &MarketModelCmsTest::testMultiStepCmSwapsAndSwaptions));
    return suite;
}
void MarketModelCmsTest::testMultiStepCmSwapsAndSwaptions () [static]
Definition at line 443 of file marketmodel_cms.cpp.
References anonymous_namespace{marketmodel.cpp}::accruals, QuantLib::MarketModelComposite::add(), QuantLib::Option::Call, anonymous_namespace{marketmodel_cms.cpp}::checkCMSAndSwaptions(), QuantLib::SobolBrownianGenerator::Diagonal, anonymous_namespace{marketmodel.cpp}::displacement, QuantLib::MarketModelComposite::evolution(), anonymous_namespace{marketmodel.cpp}::evolverTypeToString(), anonymous_namespace{marketmodel.cpp}::ExponentialCorrelationAbcdVolatility, anonymous_namespace{marketmodel.cpp}::ExponentialCorrelationFlatVolatility, QuantLib::MarketModelComposite::finalize(), QuantLib::isInTerminalMeasure(), LENGTH, anonymous_namespace{marketmodel.cpp}::makeMarketModel(), anonymous_namespace{marketmodel.cpp}::makeMarketModelEvolver(), anonymous_namespace{marketmodel.cpp}::makeMeasure(), anonymous_namespace{marketmodel.cpp}::marketModelTypeToString(), anonymous_namespace{marketmodel.cpp}::measureTypeToString(), anonymous_namespace{marketmodel.cpp}::MoneyMarket, anonymous_namespace{marketmodel.cpp}::Pc, anonymous_namespace{marketmodel.cpp}::printReport_, anonymous_namespace{marketmodel.cpp}::rateTimes, anonymous_namespace{marketmodel.cpp}::seed_, anonymous_namespace{inflationvolatility.cpp}::setup(), anonymous_namespace{marketmodel.cpp}::simulate(), anonymous_namespace{marketmodel.cpp}::Terminal, and anonymous_namespace{marketmodel.cpp}::todaysForwards.
Referenced by init_unit_test_suite(), and suite().
{
    BOOST_MESSAGE("Testing exact repricing of "
                  "multi-step constant maturity swaps and swaptions "
                  "in a lognormal constant maturity swap market model...");
    setup();
    Real fixedRate = 0.04;
    // swaps
    std::vector<Time> swapPaymentTimes(rateTimes.begin()+1, rateTimes.end());
    // until ConstantMaturitySwap is ready
    MultiStepCoterminalSwaps swaps(rateTimes, accruals, accruals,
                                   swapPaymentTimes,
                                   fixedRate);
    // swaptions
    std::vector<Time> swaptionPaymentTimes(rateTimes.begin(), rateTimes.end()-1);
    std::vector<boost::shared_ptr<StrikedTypePayoff> >
        displacedPayoff(todaysForwards.size()), undisplacedPayoff(todaysForwards.size());
    for (Size i=0; i<undisplacedPayoff.size(); ++i) {
        displacedPayoff[i] = boost::shared_ptr<StrikedTypePayoff>(new
            PlainVanillaPayoff(Option::Call, fixedRate+displacement));
        undisplacedPayoff[i] = boost::shared_ptr<StrikedTypePayoff>(new
            PlainVanillaPayoff(Option::Call, fixedRate));
    }
    // until ConstantMaturitySwap is ready
    MultiStepCoterminalSwaptions swaptions(rateTimes,
                                           swaptionPaymentTimes,
                                           undisplacedPayoff);
    MultiProductComposite product;
    product.add(swaps);
    product.add(swaptions);
    product.finalize();
    EvolutionDescription evolution = product.evolution();
    MarketModelType marketModels[] = {// CalibratedMM,
                                    ExponentialCorrelationFlatVolatility,
                                    ExponentialCorrelationAbcdVolatility };
    for (Size j=0; j<LENGTH(marketModels); j++) {
        Size testedFactors[] = { /*4, 8,*/ todaysForwards.size()};
        for (Size m=0; m<LENGTH(testedFactors); ++m) {
            Size factors = testedFactors[m];
            // Composite's ProductSuggested is the Terminal one
            MeasureType measures[] = { // ProductSuggested,
                                       Terminal,
                                      // MoneyMarketPlus,
                                       MoneyMarket};
            for (Size k=0; k<LENGTH(measures); k++) {
                std::vector<Size> numeraires = makeMeasure(product, measures[k]);
                boost::shared_ptr<MarketModel> marketModel =
                    makeMarketModel(evolution, factors, marketModels[j]);
                EvolverType evolvers[] = { Pc/*, Ipc*/ };
                boost::shared_ptr<MarketModelEvolver> evolver;
                Size stop = isInTerminalMeasure(evolution, numeraires) ? 0 : 1;
                for (Size i=0; i<LENGTH(evolvers)-stop; i++) {
                    for (Size n=0; n<1; n++) {
                        //MTBrownianGeneratorFactory generatorFactory(seed_);
                        SobolBrownianGeneratorFactory generatorFactory(
                                     SobolBrownianGenerator::Diagonal, seed_);
                        evolver = makeMarketModelEvolver(marketModel,
                                                         numeraires,
                                                         generatorFactory,
                                                         evolvers[i]);
                        std::ostringstream config;
                        config <<
                            marketModelTypeToString(marketModels[j]) << ", " <<
                            factors << (factors>1 ? (factors==todaysForwards.size() ? " (full) factors, " : " factors, ") : " factor,") <<
                            measureTypeToString(measures[k]) << ", " <<
                            evolverTypeToString(evolvers[i]) << ", " <<
                            "MT BGF";
                        if (printReport_)
                            BOOST_MESSAGE("    " << config.str());
                        boost::shared_ptr<SequenceStatisticsInc> stats = simulate(evolver, product);
                        checkCMSAndSwaptions(*stats, fixedRate,
                                             displacedPayoff, marketModel,config.str());
                    }
                }
            }
        }
    }
}
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/marketmodel_cms.hpp
/home/deriversatile/QuantLib/QuantLibQt/test-suite/marketmodel_cms.cpp