QuantLib: QuantLib::InterpolatedYoYOptionletStripper< Interpolator1D > Class Template Reference
QuantLib::InterpolatedYoYOptionletStripper< Interpolator1D > Class Template Reference
#include <interpolatedyoyoptionletstripper.hpp>
Classes
class ObjectiveFunction
Public Member Functions
virtual void initialize (const boost::shared_ptr< YoYCapFloorTermPriceSurface > &, const boost::shared_ptr< YoYInflationCapFloorEngine > &, const Real slope) const
YoYOptionletStripper interface.
virtual Rate minStrike () const
virtual Rate maxStrike () const
virtual std::vector< Rate > strikes () const
virtual std::pair< std::vector
< Rate >, std::vector
< Volatility > > slice (const Date &d) const
Protected Attributes
std::vector< boost::shared_ptr
< YoYOptionletVolatilitySurface > > volCurves_
Detailed Description
template<class Interpolator1D>
class QuantLib::InterpolatedYoYOptionletStripper< Interpolator1D >
The interpolated version interpolates along each K (as opposed to fitting a model, say).
Bug:
Tests currently fail.
Definition at line 44 of file interpolatedyoyoptionletstripper.hpp.
Member Function Documentation
template<class Interpolator1D > void QuantLib::InterpolatedYoYOptionletStripper< Interpolator1D >::initialize (const boost::shared_ptr< YoYCapFloorTermPriceSurface > & s, const boost::shared_ptr< YoYInflationCapFloorEngine > & p, const Real slope) const [virtual]
YoYOptionletStripper interface.
Implements QuantLib::YoYOptionletStripper.
Definition at line 176 of file interpolatedyoyoptionletstripper.hpp.
References QuantLib::YoYInflationCapFloor::Cap, QuantLib::YoYInflationCapFloor::Floor, QuantLib::YoYOptionletStripper::frequency_, QuantLib::YoYOptionletStripper::indexIsInterpolated_, QuantLib::YoYOptionletStripper::lag_, QuantLib::InterpolatedYoYOptionletStripper< Interpolator1D >::maxStrike(), QuantLib::InterpolatedYoYOptionletStripper< Interpolator1D >::minStrike(), QuantLib::YoYOptionletStripper::p_, QL_FAIL, QuantLib::Solver1D< Impl >::solve(), QuantLib::InterpolatedYoYOptionletStripper< Interpolator1D >::volCurves_, and QuantLib::YoYOptionletStripper::YoYCapFloorTermPriceSurface_.
{
        YoYCapFloorTermPriceSurface_ = s;
        p_ = p;
        lag_ = YoYCapFloorTermPriceSurface_->observationLag();
        frequency_ = YoYCapFloorTermPriceSurface_->frequency();
        indexIsInterpolated_ = YoYCapFloorTermPriceSurface_->indexIsInterpolated();
        Natural fixingDays_ = YoYCapFloorTermPriceSurface_->fixingDays();
        Natural settlementDays = 0; // always
        Calendar cal = YoYCapFloorTermPriceSurface_->calendar();
        BusinessDayConvention bdc =
            YoYCapFloorTermPriceSurface_->businessDayConvention();
        DayCounter dc = YoYCapFloorTermPriceSurface_->dayCounter();
        // switch from caps to floors when out of floors
        Rate maxFloor = YoYCapFloorTermPriceSurface_->floorStrikes().back();
        YoYInflationCapFloor::Type useType = YoYInflationCapFloor::Floor;
        Period TPmin = YoYCapFloorTermPriceSurface_->maturities().front();
        // create a "fake index" based on Generic, this should work
        // provided that the lag and frequency are correct
        RelinkableHandle<YoYInflationTermStructure> hYoY(
                                       YoYCapFloorTermPriceSurface_->YoYTS());
        boost::shared_ptr<YoYInflationIndex> anIndex(
                                           new YYGenericCPI(frequency_, false,
                                                            false, lag_,
                                                            Currency(), hYoY));
        // strip each K separatly
        for (Size i=0; i<YoYCapFloorTermPriceSurface_->strikes().size(); i++) {
            Rate K = YoYCapFloorTermPriceSurface_->strikes()[i];
            if (K > maxFloor) useType = YoYInflationCapFloor::Cap;
            // solve for the initial point on the vol curve
            Brent solver;
            Real solverTolerance_ = 1e-7;
             // these are VOLATILITY guesses (always +)
            Real lo = 0.00001, hi = 0.08;
            Real guess = (hi+lo)/2.0;
            Real found;
            Real priceToMatch =
                (useType == YoYInflationCapFloor::Cap ?
                 YoYCapFloorTermPriceSurface_->capPrice(TPmin, K) :
                 YoYCapFloorTermPriceSurface_->floorPrice(TPmin, K));
            try{
                found = solver.solve(
                      ObjectiveFunction(useType, slope, K, lag_, fixingDays_,
                                        anIndex, YoYCapFloorTermPriceSurface_,
                                        p_, priceToMatch),
                      solverTolerance_, guess, lo, hi );
            } catch( std::exception &e) {
                QL_FAIL("failed to find solution here because: " << e.what());
            }
            // ***create helpers***
            Real notional = 10000; // work in bps
            std::vector<boost::shared_ptr<BootstrapHelper<YoYOptionletVolatilitySurface> > > helperInstruments;
            std::vector<boost::shared_ptr<YoYOptionletHelper> > helpers;
            for (Size j = 0; j < YoYCapFloorTermPriceSurface_->maturities().size(); j++){
                Period Tp = YoYCapFloorTermPriceSurface_->maturities()[j];
                Real nextPrice =
                    (useType == YoYInflationCapFloor::Cap ?
                     YoYCapFloorTermPriceSurface_->capPrice(Tp, K) :
                     YoYCapFloorTermPriceSurface_->floorPrice(Tp, K));
                Handle<Quote> quote1(boost::shared_ptr<Quote>(
                                               new SimpleQuote( nextPrice )));
                // helper should be an integer number of periods away,
                // this is enforced by rounding
                Size nT = (Size)floor(s->timeFromReference(s->yoyOptionDateFromTenor(Tp))+0.5);
                helpers.push_back(boost::shared_ptr<YoYOptionletHelper>(
                          new YoYOptionletHelper(quote1, notional, useType,
                                                 lag_,
                                                 dc, cal,
                                                 fixingDays_,
                                                 anIndex, K, nT, p_)));
                boost::shared_ptr<ConstantYoYOptionletVolatility> yoyVolBLACK(
                          new ConstantYoYOptionletVolatility(found, settlementDays,
                                                             cal, bdc, dc,
                                                             lag_, frequency_,
                                                             false,
                                                             // -100% to +300%
                                                             -1.0,3.0));
                helpers[j]->setTermStructure(
                       // gets underlying pointer & removes const
                       const_cast<ConstantYoYOptionletVolatility*>(
                                                          yoyVolBLACK.get()));
                helperInstruments.push_back(helpers[j]);
            }
            // ***bootstrap***
            // this is the artificial vol at zero so that first section works
            Real Tmin = s->timeFromReference(s->yoyOptionDateFromTenor(TPmin));
            Volatility baseYoYVolatility = found - slope * Tmin * found;
            Rate eps = std::max(K, 0.02) / 1000.0;
            Rate minStrike = K-eps;
            Rate maxStrike = K+eps;
            boost::shared_ptr<
                PiecewiseYoYOptionletVolatilityCurve<Interpolator1D> > testPW(
                new PiecewiseYoYOptionletVolatilityCurve<Interpolator1D>(
                                            settlementDays, cal, bdc, dc, lag_,
                                            frequency_, indexIsInterpolated_,
                                            minStrike, maxStrike,
                                            baseYoYVolatility,
                                            helperInstruments) );
            testPW->recalculate();
            volCurves_.push_back(testPW);
        }
    }
template<class Interpolator1D > virtual Rate QuantLib::InterpolatedYoYOptionletStripper< Interpolator1D >::maxStrike () const [inline, virtual]
Implements QuantLib::YoYOptionletStripper.
Definition at line 56 of file interpolatedyoyoptionletstripper.hpp.
References QuantLib::YoYOptionletStripper::YoYCapFloorTermPriceSurface_.
Referenced by QuantLib::InterpolatedYoYOptionletStripper< Interpolator1D >::initialize().
{
            return YoYCapFloorTermPriceSurface_->strikes().back();
        }
template<class Interpolator1D > virtual Rate QuantLib::InterpolatedYoYOptionletStripper< Interpolator1D >::minStrike () const [inline, virtual]
Implements QuantLib::YoYOptionletStripper.
Definition at line 53 of file interpolatedyoyoptionletstripper.hpp.
References QuantLib::YoYOptionletStripper::YoYCapFloorTermPriceSurface_.
Referenced by QuantLib::InterpolatedYoYOptionletStripper< Interpolator1D >::initialize().
{
            return YoYCapFloorTermPriceSurface_->strikes().front();
        }
template<class Interpolator1D > std::pair< std::vector< Rate >, std::vector< Volatility > > QuantLib::InterpolatedYoYOptionletStripper< Interpolator1D >::slice (const Date & d) const [virtual]
Implements QuantLib::YoYOptionletStripper.
Definition at line 292 of file interpolatedyoyoptionletstripper.hpp.
References QuantLib::InterpolatedYoYOptionletStripper< Interpolator1D >::strikes(), anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::InterpolatedYoYOptionletStripper< Interpolator1D >::volCurves_.
{
        const std::vector<Real>& Ks = strikes();
        const Size nK = Ks.size();
        std::pair<std::vector<Rate>, std::vector<Volatility> > result =
            std::make_pair(std::vector<Rate>(nK), std::vector<Volatility>(nK));
        for (Size i = 0; i < nK; i++) {
            Rate K = Ks[i];
            Volatility v = volCurves_[i]->volatility(d, K);
            result.first[i] = K;
            result.second[i] = v;
        }
        return result;
    }
template<class Interpolator1D > virtual std::vector<Rate> QuantLib::InterpolatedYoYOptionletStripper< Interpolator1D >::strikes () const [inline, virtual]
Implements QuantLib::YoYOptionletStripper.
Definition at line 59 of file interpolatedyoyoptionletstripper.hpp.
References QuantLib::YoYOptionletStripper::YoYCapFloorTermPriceSurface_.
Referenced by QuantLib::InterpolatedYoYOptionletStripper< Interpolator1D >::slice().
{
            return YoYCapFloorTermPriceSurface_->strikes();
        }
Member Data Documentation
template<class Interpolator1D > std::vector<boost::shared_ptr<YoYOptionletVolatilitySurface> > QuantLib::InterpolatedYoYOptionletStripper< Interpolator1D >::volCurves_ [mutable, protected]
Definition at line 68 of file interpolatedyoyoptionletstripper.hpp.
Referenced by QuantLib::InterpolatedYoYOptionletStripper< Interpolator1D >::initialize(), and QuantLib::InterpolatedYoYOptionletStripper< Interpolator1D >::slice().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/inflation/interpolatedyoyoptionletstripper.hpp