QuantLib: QuantLib::LossDistBinomial Class Reference
QuantLib::LossDistBinomial Class Reference
Binomial loss distribution.
#include <lossdistribution.hpp>
Public Member Functions
LossDistBinomial (Size nBuckets, Real maximum)
Distribution operator() (Size n, Real volume, Real probability) const
Distribution operator() (const std::vector< Real > &volumes, const std::vector< Real > &probabilities) const
Size buckets () const
Real maximum () const
Real volume () const
Size size () const
std::vector< Real > probability () const
std::vector< Real > excessProbability () const
Private Attributes
Size nBuckets_
Real maximum_
Real volume_
Size n_
std::vector< Real > probability_
std::vector< Real > excessProbability_
Detailed Description
Binomial loss distribution.
Binomial loss distribution
Definition at line 101 of file lossdistribution.hpp.
Constructor & Destructor Documentation
QuantLib::LossDistBinomial::LossDistBinomial (Size nBuckets, Real maximum) [inline]
Definition at line 103 of file lossdistribution.hpp.
            : nBuckets_(nBuckets), maximum_(maximum) {}
Member Function Documentation
Size QuantLib::LossDistBinomial::buckets () const [inline, virtual]
Implements QuantLib::LossDist.
Definition at line 108 of file lossdistribution.hpp.
References nBuckets_.
{ return nBuckets_; }
std::vector<Real> QuantLib::LossDistBinomial::excessProbability () const [inline]
Definition at line 113 of file lossdistribution.hpp.
References excessProbability_.
{ return excessProbability_; }
Real QuantLib::LossDistBinomial::maximum () const [inline, virtual]
Implements QuantLib::LossDist.
Definition at line 109 of file lossdistribution.hpp.
References maximum_.
{ return maximum_; }
Distribution QuantLib::LossDistBinomial::operator() (Size n, Real volume, Real probability) const
Definition at line 146 of file lossdistribution.cpp.
References QuantLib::Distribution::addAverage(), QuantLib::Distribution::addDensity(), QuantLib::Distribution::dx(), QuantLib::Distribution::locate(), and QuantLib::Distribution::normalize().
{
    //--------------------------------------------------------------------------
        n_ = n;
        probability_.clear();
        probability_.resize(n_+1, 0.0);
        Distribution dist (nBuckets_, 0.0, maximum_);
        BinomialDistribution binomial (probability, n);
        for (Size i = 0; i <= n; i++) {
            if (volume_ * i <= maximum_) {
                probability_[i] = binomial(i);
                Size bucket = dist.locate(volume * i);
                dist.addDensity (bucket, probability_[i] / dist.dx(bucket));
                dist.addAverage (bucket, volume * i);
            }
        }
        excessProbability_.clear();
        excessProbability_.resize(n_+1, 0.0);
        excessProbability_[n_] = probability_[n_];
        for (int k = n_-1; k >= 0; k--)
            excessProbability_[k] = excessProbability_[k+1] + probability_[k];
        dist.normalize();
        return dist;
    }
Distribution QuantLib::LossDistBinomial::operator() (const std::vector< Real > & volumes, const std::vector< Real > & probabilities) const [virtual]
Implements QuantLib::LossDist.
Definition at line 175 of file lossdistribution.cpp.
{
    //--------------------------------------------------------------------------
        return operator()(nominals.size(), nominals[0], probabilities[0]);
    }
std::vector<Real> QuantLib::LossDistBinomial::probability () const [inline]
Definition at line 112 of file lossdistribution.hpp.
References probability_.
{ return probability_; }
Size QuantLib::LossDistBinomial::size () const [inline]
Definition at line 111 of file lossdistribution.hpp.
References n_.
{ return n_; }
Real QuantLib::LossDistBinomial::volume () const [inline]
Definition at line 110 of file lossdistribution.hpp.
References volume_.
{ return volume_; }
Member Data Documentation
std::vector<Real> QuantLib::LossDistBinomial::excessProbability_ [mutable, private]
Definition at line 120 of file lossdistribution.hpp.
Referenced by excessProbability().
Real QuantLib::LossDistBinomial::maximum_ [private]
Definition at line 116 of file lossdistribution.hpp.
Referenced by maximum().
Size QuantLib::LossDistBinomial::n_ [mutable, private]
Definition at line 118 of file lossdistribution.hpp.
Referenced by size().
Size QuantLib::LossDistBinomial::nBuckets_ [private]
Definition at line 115 of file lossdistribution.hpp.
Referenced by buckets().
std::vector<Real> QuantLib::LossDistBinomial::probability_ [mutable, private]
Definition at line 119 of file lossdistribution.hpp.
Referenced by probability().
Real QuantLib::LossDistBinomial::volume_ [mutable, private]
Definition at line 117 of file lossdistribution.hpp.
Referenced by volume().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/lossdistribution.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/lossdistribution.cpp