QuantLib: LowDiscrepancyTest Class Reference
LowDiscrepancyTest Class Reference
#include <lowdiscrepancysequences.hpp>
Static Public Member Functions
static void testSeedGenerator ()
static void testPolynomialsModuloTwo ()
static void testSobol ()
static void testHalton ()
static void testFaure ()
static void testMersenneTwisterDiscrepancy ()
static void testPlainHaltonDiscrepancy ()
static void testRandomStartHaltonDiscrepancy ()
static void testRandomShiftHaltonDiscrepancy ()
static void testRandomStartRandomShiftHaltonDiscrepancy ()
static void testJackelSobolDiscrepancy ()
static void testSobolLevitanSobolDiscrepancy ()
static void testSobolLevitanLemieuxSobolDiscrepancy ()
static void testUnitSobolDiscrepancy ()
static void testRandomizedLowDiscrepancySequence ()
static void testSobolSkipping ()
static void testRandomizedLattices ()
static
boost::unit_test_framework::test_suite * suite ()
Detailed Description
Definition at line 28 of file lowdiscrepancysequences.hpp.
Member Function Documentation
test_suite * LowDiscrepancyTest::suite () [static]
Definition at line 1095 of file lowdiscrepancysequences.cpp.
References QUANTLIB_TEST_CASE, testFaure(), testHalton(), testJackelSobolDiscrepancy(), testMersenneTwisterDiscrepancy(), testPlainHaltonDiscrepancy(), testPolynomialsModuloTwo(), testRandomizedLattices(), testRandomizedLowDiscrepancySequence(), testRandomShiftHaltonDiscrepancy(), testRandomStartHaltonDiscrepancy(), testRandomStartRandomShiftHaltonDiscrepancy(), testSeedGenerator(), testSobol(), testSobolLevitanLemieuxSobolDiscrepancy(), testSobolLevitanSobolDiscrepancy(), testSobolSkipping(), and testUnitSobolDiscrepancy().
Referenced by init_unit_test_suite().
{
    test_suite* suite = BOOST_TEST_SUITE("Low-discrepancy sequence tests");
    suite->add(QUANTLIB_TEST_CASE(
           &LowDiscrepancyTest::testRandomizedLattices));
    suite->add(QUANTLIB_TEST_CASE(
           &LowDiscrepancyTest::testSeedGenerator));
    suite->add(QUANTLIB_TEST_CASE(
           &LowDiscrepancyTest::testPolynomialsModuloTwo));
    suite->add(QUANTLIB_TEST_CASE(&LowDiscrepancyTest::testSobol));
    suite->add(QUANTLIB_TEST_CASE(&LowDiscrepancyTest::testHalton));
    suite->add(QUANTLIB_TEST_CASE(&LowDiscrepancyTest::testFaure));
    suite->add(QUANTLIB_TEST_CASE(
           &LowDiscrepancyTest::testMersenneTwisterDiscrepancy));
    suite->add(QUANTLIB_TEST_CASE(
           &LowDiscrepancyTest::testPlainHaltonDiscrepancy));
    suite->add(QUANTLIB_TEST_CASE(
           &LowDiscrepancyTest::testRandomStartHaltonDiscrepancy));
    suite->add(QUANTLIB_TEST_CASE(
           &LowDiscrepancyTest::testRandomShiftHaltonDiscrepancy));
    suite->add(QUANTLIB_TEST_CASE(
           &LowDiscrepancyTest::testRandomStartRandomShiftHaltonDiscrepancy));
    suite->add(QUANTLIB_TEST_CASE(
        &LowDiscrepancyTest::testUnitSobolDiscrepancy));
    suite->add(QUANTLIB_TEST_CASE(
           &LowDiscrepancyTest::testJackelSobolDiscrepancy));
    suite->add(QUANTLIB_TEST_CASE(
           &LowDiscrepancyTest::testSobolLevitanSobolDiscrepancy));
    suite->add(QUANTLIB_TEST_CASE(
           &LowDiscrepancyTest::testSobolLevitanLemieuxSobolDiscrepancy));
    suite->add(QUANTLIB_TEST_CASE(&LowDiscrepancyTest::testSobolSkipping));
    suite->add(QUANTLIB_TEST_CASE(
           &LowDiscrepancyTest::testRandomizedLowDiscrepancySequence));
    return suite;
}
void LowDiscrepancyTest::testFaure () [static]
Definition at line 261 of file lowdiscrepancysequences.cpp.
References anonymous_namespace{lowdiscrepancysequences.cpp}::dimensionality, QuantLib::FaureRsg::nextSequence(), QuantLib::io::ordinal(), QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow(), PPMT_MAX_DIM, QL_FIXED, QL_SCIENTIFIC, anonymous_namespace{gaussianquadratures.cpp}::tolerance, and QuantLib::Sample< T >::value.
Referenced by suite().
{
    BOOST_MESSAGE("Testing Faure sequences...");
    std::vector<Real> point;
    Real tolerance = 1.0e-15;
    // testing "high" dimensionality
    Size dimensionality = PPMT_MAX_DIM;
    FaureRsg rsg(dimensionality);
    Size points = 100, i;
    for (i=0; i<points; i++) {
        point = rsg.nextSequence().value;
        if (point.size()!=dimensionality) {
            BOOST_ERROR("Faure sequence generator returns "
                        " a sequence of wrong dimensionality: " << point.size()
                        << " instead of  " << dimensionality);
        }
    }
    // 1-dimension Faure (van der Corput sequence base 2)
    const Real vanderCorputSequenceModuloTwo[] = {
        // first cycle (zero excluded)
        0.50000,
        // second cycle
        0.75000, 0.25000,
        // third cycle
        0.37500, 0.87500, 0.62500, 0.12500,
        // fourth cycle
        0.18750, 0.68750, 0.93750, 0.43750, 0.31250, 0.81250, 0.56250, 0.06250,
        // fifth cycle
        0.09375, 0.59375, 0.84375, 0.34375, 0.46875, 0.96875, 0.71875, 0.21875,
        0.15625, 0.65625, 0.90625, 0.40625, 0.28125, 0.78125, 0.53125, 0.03125
    };
    dimensionality = 1;
    rsg = FaureRsg(dimensionality);
    points = Size(std::pow(2.0, 5))-1; // five cycles
    for (i=0; i<points; i++) {
        point = rsg.nextSequence().value;
        Real error = std::fabs(point[0]-vanderCorputSequenceModuloTwo[i]);
        if (error > tolerance) {
            BOOST_ERROR(io::ordinal(i+1) << " draw, dimension 1 ("
                        << QL_FIXED << point[0]
                        << ") in 3-D Faure sequence should have been "
                        << vanderCorputSequenceModuloTwo[i]
                        << QL_SCIENTIFIC
                        << " (error = " << error << ")");
        }
    }
    // 2nd dimension of the 2-dimensional Faure sequence
    // (shuffled van der Corput sequence base 2)
    // checked with the code provided with "Economic generation of
    // low-discrepancy sequences with a b-ary gray code", by E. Thiemard
    const Real FaureDimensionTwoOfTwo[] = {
        // first cycle (zero excluded)
        0.50000,
        // second cycle
        0.25000, 0.75000,
        // third cycle
        0.37500, 0.87500, 0.12500, 0.62500,
        // fourth cycle
        0.31250, 0.81250, 0.06250, 0.56250, 0.18750, 0.68750, 0.43750, 0.93750,
        // fifth cycle
        0.46875, 0.96875, 0.21875, 0.71875, 0.09375, 0.59375, 0.34375, 0.84375,
        0.15625, 0.65625, 0.40625, 0.90625, 0.28125, 0.78125, 0.03125, 0.53125
    };
    dimensionality = 2;
    rsg = FaureRsg(dimensionality);
    points = Size(std::pow(2.0, 5))-1; // five cycles
    for (i=0; i<points; i++) {
        point = rsg.nextSequence().value;
        Real error = std::fabs(point[0]-vanderCorputSequenceModuloTwo[i]);
        if (error > tolerance) {
            BOOST_ERROR(io::ordinal(i+1) << " draw, dimension 1 ("
                        << QL_FIXED << point[0]
                        << ") in 3-D Faure sequence should have been "
                        << vanderCorputSequenceModuloTwo[i]
                        << QL_SCIENTIFIC
                        << " (error = " << error << ")");
        }
        error = std::fabs(point[1]-FaureDimensionTwoOfTwo[i]);
        if (error > tolerance) {
            BOOST_ERROR(io::ordinal(i+1) << " draw, dimension 2 ("
                        << QL_FIXED << point[1]
                        << ") in 3-D Faure sequence should have been "
                        << FaureDimensionTwoOfTwo[i]
                        << QL_SCIENTIFIC
                        << " (error = " << error << ")");
        }
    }
    // 3-dimension Faure sequence (shuffled van der Corput sequence base 3)
    // see "Monte Carlo Methods in Financial Engineering,"
    // by Paul Glasserman, 2004 Springer Verlag, pag. 299
    const Real FaureDimensionOneOfThree[] = {
        // first cycle (zero excluded)
        1.0/3,  2.0/3,
        // second cycle
        7.0/9,  1.0/9,  4.0/9,  5.0/9,  8.0/9,  2.0/9
    };
    const Real FaureDimensionTwoOfThree[] = {
        // first cycle (zero excluded)
        1.0/3,  2.0/3,
        // second cycle
        1.0/9,  4.0/9,  7.0/9,  2.0/9,  5.0/9,  8.0/9
    };
    const Real FaureDimensionThreeOfThree[] = {
        // first cycle (zero excluded)
        1.0/3,  2.0/3,
        // second cycle
        4.0/9,  7.0/9,  1.0/9,  8.0/9,  2.0/9,  5.0/9
    };
    dimensionality = 3;
    rsg = FaureRsg(dimensionality);
    points = Size(std::pow(3.0, 2))-1; // three cycles
    for (i=0; i<points; i++) {
        point = rsg.nextSequence().value;
        Real error = std::fabs(point[0]-FaureDimensionOneOfThree[i]);
        if (error > tolerance) {
            BOOST_ERROR(io::ordinal(i+1) << " draw, dimension 1 ("
                        << QL_FIXED << point[0]
                        << ") in 3-D Faure sequence should have been "
                        << FaureDimensionOneOfThree[i]
                        << QL_SCIENTIFIC
                        << " (error = " << error << ")");
        }
        error = std::fabs(point[1]-FaureDimensionTwoOfThree[i]);
        if (error > tolerance) {
            BOOST_ERROR(io::ordinal(i+1) << " draw, dimension 2 ("
                        << QL_FIXED << point[1]
                        << ") in 3-D Faure sequence should have been "
                        << FaureDimensionTwoOfThree[i]
                        << QL_SCIENTIFIC
                        << " (error = " << error << ")");
        }
        error = std::fabs(point[2]-FaureDimensionThreeOfThree[i]);
        if (error > tolerance) {
            BOOST_ERROR(io::ordinal(i+1) << " draw, dimension 3 ("
                        << QL_FIXED << point[2]
                        << ") in 3-D Faure sequence should have been "
                        << FaureDimensionThreeOfThree[i]
                        << QL_SCIENTIFIC
                        << " (error = " << error << ")");
        }
    }
}
void LowDiscrepancyTest::testHalton () [static]
Definition at line 410 of file lowdiscrepancysequences.cpp.
References QuantLib::GenericSequenceStatistics< StatisticsType >::add(), anonymous_namespace{lowdiscrepancysequences.cpp}::dimensionality, QuantLib::GenericSequenceStatistics< StatisticsType >::mean(), QuantLib::HaltonRsg::nextSequence(), QuantLib::io::ordinal(), QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow(), PPMT_MAX_DIM, QL_FIXED, QL_SCIENTIFIC, QuantLib::GenericSequenceStatistics< StatisticsType >::reset(), anonymous_namespace{gaussianquadratures.cpp}::tolerance, and QuantLib::Sample< T >::value.
Referenced by suite().
{
    BOOST_MESSAGE("Testing Halton sequences...");
    std::vector<Real> point;
    Real tolerance = 1.0e-15;
    // testing "high" dimensionality
    Size dimensionality = PPMT_MAX_DIM;
    HaltonRsg rsg(dimensionality, 0, false, false);
    Size points = 100, i, k;
    for (i=0; i<points; i++) {
        point = rsg.nextSequence().value;
        if (point.size()!=dimensionality) {
            BOOST_ERROR("Halton sequence generator returns "
                        " a sequence of wrong dimensionality: " << point.size()
                        << " instead of  " << dimensionality);
        }
    }
    // testing first and second dimension (van der Corput sequence)
    const Real vanderCorputSequenceModuloTwo[] = {
        // first cycle (zero excluded)
        0.50000,
        // second cycle
        0.25000, 0.75000,
        // third cycle
        0.12500, 0.62500, 0.37500, 0.87500,
        // fourth cycle
        0.06250, 0.56250, 0.31250, 0.81250, 0.18750, 0.68750, 0.43750, 0.93750,
        // fifth cycle
        0.03125, 0.53125, 0.28125, 0.78125, 0.15625, 0.65625, 0.40625, 0.90625,
        0.09375, 0.59375, 0.34375, 0.84375, 0.21875, 0.71875, 0.46875, 0.96875,
    };
    dimensionality = 1;
    rsg = HaltonRsg(dimensionality, 0, false, false);
    points = Size(std::pow(2.0, 5))-1;  // five cycles
    for (i=0; i<points; i++) {
        point = rsg.nextSequence().value;
        Real error = std::fabs(point[0]-vanderCorputSequenceModuloTwo[i]);
        if (error > tolerance) {
            BOOST_ERROR(io::ordinal(i+1) << " draw ("
                        << QL_FIXED << point[0]
                        << ") in 1-D Halton sequence is not in the "
                        << "van der Corput sequence modulo two: "
                        << "it should have been "
                        << vanderCorputSequenceModuloTwo[i]
                        << QL_SCIENTIFIC
                        << " (error = " << error << ")");
        }
    }
    const Real vanderCorputSequenceModuloThree[] = {
        // first cycle (zero excluded)
        1.0/3,  2.0/3,
        // second cycle
        1.0/9,  4.0/9,  7.0/9,  2.0/9,  5.0/9,  8.0/9,
        // third cycle
        1.0/27, 10.0/27, 19.0/27,  4.0/27, 13.0/27, 22.0/27,
        7.0/27, 16.0/27, 25.0/27,  2.0/27, 11.0/27, 20.0/27,
        5.0/27, 14.0/27, 23.0/27,  8.0/27, 17.0/27, 26.0/27
    };
    dimensionality = 2;
    rsg = HaltonRsg(dimensionality, 0, false, false);
    points = Size(std::pow(3.0, 3))-1;  // three cycles of the higher dimension
    for (i=0; i<points; i++) {
        point = rsg.nextSequence().value;
        Real error = std::fabs(point[0]-vanderCorputSequenceModuloTwo[i]);
        if (error > tolerance) {
            BOOST_ERROR("First component of " << io::ordinal(i+1)
                        << " draw (" << QL_FIXED << point[0]
                        << ") in 2-D Halton sequence is not in the "
                        << "van der Corput sequence modulo two: "
                        << "it should have been "
                        << vanderCorputSequenceModuloTwo[i]
                        << QL_SCIENTIFIC
                        << " (error = " << error << ")");
        }
        error = std::fabs(point[1]-vanderCorputSequenceModuloThree[i]);
        if (error > tolerance) {
            BOOST_ERROR("Second component of " << io::ordinal(i+1)
                        << " draw (" << QL_FIXED << point[1]
                        << ") in 2-D Halton sequence is not in the "
                        << "van der Corput sequence modulo three: "
                        << "it should have been "
                        << vanderCorputSequenceModuloThree[i]
                        << QL_SCIENTIFIC
                        << " (error = " << error << ")");
        }
    }
    // testing homogeneity properties
    dimensionality = 33;
    rsg = HaltonRsg(dimensionality, 0, false, false);
    SequenceStatistics stat(dimensionality);
    std::vector<Real> mean, stdev, variance, skewness, kurtosis;
    k = 0;
    Integer j;
    for (j=1; j<5; j++) { // five cycle
        points = Size(std::pow(2.0, j))-1; // base 2
        for (; k<points; k++) {
            point = rsg.nextSequence().value;
            stat.add(point);
        }
        mean = stat.mean();
        Real error = std::fabs(mean[0] - 0.5);
        if (error > tolerance) {
            BOOST_ERROR("First dimension mean (" << QL_FIXED << mean[0]
                        << ") at the end of the " << io::ordinal(j+1)
                        << " cycle in Halton sequence is not " << 0.5
                        << QL_SCIENTIFIC
                        << " (error = " << error << ")");
        }
    }
    // reset generator and gaussianstatistics
    rsg  = HaltonRsg(dimensionality, 0, false, false);
    stat.reset(dimensionality);
    k = 0;
    for (j=1; j<3; j++) { // three cycle
        points = Size(std::pow(3.0, j))-1; // base 3
        for (; k<points; k++) {
            point = rsg.nextSequence().value;
            stat.add(point);
        }
        mean = stat.mean();
        Real error = std::fabs(mean[1] - 0.5);
        if (error > tolerance) {
            BOOST_ERROR("Second dimension mean (" << QL_FIXED << mean[1]
                        << ") at the end of the " << io::ordinal(j+1)
                        << " cycle in Halton sequence is not " << 0.5
                        << QL_SCIENTIFIC
                        << " (error = " << error << ")");
        }
    }
}
void LowDiscrepancyTest::testJackelSobolDiscrepancy () [static]
Definition at line 983 of file lowdiscrepancysequences.cpp.
References anonymous_namespace{lowdiscrepancysequences.cpp}::dim002Discr_Sobol, anonymous_namespace{lowdiscrepancysequences.cpp}::dim003Discr_Sobol, anonymous_namespace{lowdiscrepancysequences.cpp}::dim005Discr_Sobol, anonymous_namespace{lowdiscrepancysequences.cpp}::dim010DiscrJackel_Sobol, anonymous_namespace{lowdiscrepancysequences.cpp}::dim015DiscrJackel_Sobol, anonymous_namespace{lowdiscrepancysequences.cpp}::dim030DiscrJackel_Sobol, anonymous_namespace{lowdiscrepancysequences.cpp}::dim050DiscrJackel_Sobol, anonymous_namespace{lowdiscrepancysequences.cpp}::dim100DiscrJackel_Sobol, QuantLib::SobolRsg::Jaeckel, and anonymous_namespace{lowdiscrepancysequences.cpp}::testGeneratorDiscrepancy().
Referenced by suite().
{
    BOOST_MESSAGE("Testing Jaeckel-Sobol discrepancy...");
    const Real * const discrepancy[8] = {
        dim002Discr_Sobol, dim003Discr_Sobol,
        dim005Discr_Sobol, dim010DiscrJackel_Sobol,
        dim015DiscrJackel_Sobol, dim030DiscrJackel_Sobol,
        dim050DiscrJackel_Sobol, dim100DiscrJackel_Sobol};
    testGeneratorDiscrepancy(SobolFactory(SobolRsg::Jaeckel),
                             discrepancy,
                             "JackelSobolDiscrepancy.txt",
                             "DiscrJackel_Sobol");
}
void LowDiscrepancyTest::testMersenneTwisterDiscrepancy () [static]
Definition at line 902 of file lowdiscrepancysequences.cpp.
References anonymous_namespace{lowdiscrepancysequences.cpp}::dim002DiscrMersenneTwis, anonymous_namespace{lowdiscrepancysequences.cpp}::dim003DiscrMersenneTwis, anonymous_namespace{lowdiscrepancysequences.cpp}::dim005DiscrMersenneTwis, anonymous_namespace{lowdiscrepancysequences.cpp}::dim010DiscrMersenneTwis, anonymous_namespace{lowdiscrepancysequences.cpp}::dim015DiscrMersenneTwis, anonymous_namespace{lowdiscrepancysequences.cpp}::dim030DiscrMersenneTwis, anonymous_namespace{lowdiscrepancysequences.cpp}::dim050DiscrMersenneTwis, anonymous_namespace{lowdiscrepancysequences.cpp}::dim100DiscrMersenneTwis, and anonymous_namespace{lowdiscrepancysequences.cpp}::testGeneratorDiscrepancy().
Referenced by init_unit_test_suite(), and suite().
{
    BOOST_MESSAGE("Testing Mersenne-twister discrepancy...");
    const Real * const discrepancy[8] = {
        dim002DiscrMersenneTwis, dim003DiscrMersenneTwis,
        dim005DiscrMersenneTwis, dim010DiscrMersenneTwis,
        dim015DiscrMersenneTwis, dim030DiscrMersenneTwis,
        dim050DiscrMersenneTwis, dim100DiscrMersenneTwis
    };
    testGeneratorDiscrepancy(MersenneFactory(),
                             discrepancy,
                             "MersenneDiscrepancy.txt",
                             "DiscrMersenneTwis");
}
void LowDiscrepancyTest::testPlainHaltonDiscrepancy () [static]
Definition at line 919 of file lowdiscrepancysequences.cpp.
References anonymous_namespace{lowdiscrepancysequences.cpp}::dim002DiscrPlain_Halton, anonymous_namespace{lowdiscrepancysequences.cpp}::dim003DiscrPlain_Halton, anonymous_namespace{lowdiscrepancysequences.cpp}::dim005DiscrPlain_Halton, anonymous_namespace{lowdiscrepancysequences.cpp}::dim010DiscrPlain_Halton, anonymous_namespace{lowdiscrepancysequences.cpp}::dim015DiscrPlain_Halton, anonymous_namespace{lowdiscrepancysequences.cpp}::dim030DiscrPlain_Halton, anonymous_namespace{lowdiscrepancysequences.cpp}::dim050DiscrPlain_Halton, anonymous_namespace{lowdiscrepancysequences.cpp}::dim100DiscrPlain_Halton, and anonymous_namespace{lowdiscrepancysequences.cpp}::testGeneratorDiscrepancy().
Referenced by suite().
{
    BOOST_MESSAGE("Testing plain Halton discrepancy...");
    const Real * const discrepancy[8] = {
        dim002DiscrPlain_Halton, dim003DiscrPlain_Halton,
        dim005DiscrPlain_Halton, dim010DiscrPlain_Halton,
        dim015DiscrPlain_Halton, dim030DiscrPlain_Halton,
        dim050DiscrPlain_Halton, dim100DiscrPlain_Halton};
    testGeneratorDiscrepancy(HaltonFactory(false,false),
                             discrepancy,
                             "PlainHaltonDiscrepancy.txt",
                             "DiscrPlain_Halton");
}
void LowDiscrepancyTest::testPolynomialsModuloTwo () [static]
Definition at line 51 of file lowdiscrepancysequences.cpp.
References PPMT_MAX_DIM, and PrimitivePolynomials.
Referenced by suite().
{
    BOOST_MESSAGE("Testing " << PPMT_MAX_DIM <<
                  " primitive polynomials modulo two...");
    const Size jj[] = {
                 1,       1,       2,       2,       6,       6,      18,
                16,      48,      60,     176,     144,     630,     756,
              1800,    2048,    7710,    7776,   27594,   24000,   84672,
            120032,  356960,  276480, 1296000, 1719900, 4202496
    };
    Size i=0,j=0,n=0;
    BigInteger polynomial=0;
    while (n<PPMT_MAX_DIM || polynomial!=-1) {
        if (polynomial==-1) {
            ++i; // Increase degree index
            j=0; // Reset index of polynomial in degree.
        }
        polynomial = PrimitivePolynomials[i][j];
        if (polynomial==-1) {
            --n;
            if (j!=jj[i]) {
                BOOST_ERROR("Only " << j << " polynomials in degree " << i+1
                            << " instead of " << jj[i]);
            }
        }
        ++j; // Increase index of polynomial in degree i+1
        ++n; // Increase overall polynomial counter
    }
}
void LowDiscrepancyTest::testRandomizedLattices () [static]
Definition at line 167 of file lowdiscrepancysequences.cpp.
References QuantLib::LatticeRule::A, QuantLib::LatticeRule::B, QuantLib::LatticeRule::C, QuantLib::LatticeRule::D, and anonymous_namespace{lowdiscrepancysequences.cpp}::testRandomizedLatticeRule().
Referenced by suite().
{
    testRandomizedLatticeRule(LatticeRule::A, "A");
    testRandomizedLatticeRule(LatticeRule::B, "B");
    testRandomizedLatticeRule(LatticeRule::C, "C");
    testRandomizedLatticeRule(LatticeRule::D, "D");
}
void LowDiscrepancyTest::testRandomizedLowDiscrepancySequence () [static]
Definition at line 84 of file lowdiscrepancysequences.cpp.
References QuantLib::RandomizedLDS< LDS, PRS >::lastSequence(), QuantLib::RandomizedLDS< LDS, PRS >::nextRandomizer(), QuantLib::RandomizedLDS< LDS, PRS >::nextSequence(), and PPMT_MAX_DIM.
Referenced by suite().
{
    BOOST_MESSAGE("Testing randomized low-discrepancy sequences up to "
                  "dimension " << PPMT_MAX_DIM << "...");
    RandomizedLDS<SobolRsg, RandomSequenceGenerator<MersenneTwisterUniformRng> > rldsg(PPMT_MAX_DIM);
    rldsg.nextSequence();
    rldsg.lastSequence();
    rldsg.nextRandomizer();
    MersenneTwisterUniformRng t0;
    SobolRsg t1(PPMT_MAX_DIM);
    RandomSequenceGenerator<MersenneTwisterUniformRng> t2(PPMT_MAX_DIM);
    RandomizedLDS<SobolRsg, RandomSequenceGenerator<MersenneTwisterUniformRng> > rldsg2(t1, t2);
    rldsg2.nextSequence();
    rldsg2.lastSequence();
    rldsg2.nextRandomizer();
    RandomizedLDS<SobolRsg, RandomSequenceGenerator<MersenneTwisterUniformRng> > rldsg3(t1);
    rldsg3.nextSequence();
    rldsg3.lastSequence();
    rldsg3.nextRandomizer();
}
void LowDiscrepancyTest::testRandomShiftHaltonDiscrepancy () [static]
Definition at line 951 of file lowdiscrepancysequences.cpp.
References anonymous_namespace{lowdiscrepancysequences.cpp}::dim002DiscrRShiftHalton, anonymous_namespace{lowdiscrepancysequences.cpp}::dim003DiscrRShiftHalton, anonymous_namespace{lowdiscrepancysequences.cpp}::dim005DiscrRShiftHalton, anonymous_namespace{lowdiscrepancysequences.cpp}::dim010DiscrRShiftHalton, anonymous_namespace{lowdiscrepancysequences.cpp}::dim015DiscrRShiftHalton, anonymous_namespace{lowdiscrepancysequences.cpp}::dim030DiscrRShiftHalton, anonymous_namespace{lowdiscrepancysequences.cpp}::dim050DiscrRShiftHalton, anonymous_namespace{lowdiscrepancysequences.cpp}::dim100DiscrRShiftHalton, and anonymous_namespace{lowdiscrepancysequences.cpp}::testGeneratorDiscrepancy().
Referenced by suite().
{
    BOOST_MESSAGE("Testing random-shift Halton discrepancy...");
    const Real * const discrepancy[8] = {
        dim002DiscrRShiftHalton, dim003DiscrRShiftHalton,
        dim005DiscrRShiftHalton, dim010DiscrRShiftHalton,
        dim015DiscrRShiftHalton, dim030DiscrRShiftHalton,
        dim050DiscrRShiftHalton, dim100DiscrRShiftHalton};
    testGeneratorDiscrepancy(HaltonFactory(false,true),
                             discrepancy,
                             "RandomShiftHaltonDiscrepancy.txt",
                             "DiscrRShiftHalton");
}
void LowDiscrepancyTest::testRandomStartHaltonDiscrepancy () [static]
Definition at line 935 of file lowdiscrepancysequences.cpp.
References anonymous_namespace{lowdiscrepancysequences.cpp}::dim002DiscrRStartHalton, anonymous_namespace{lowdiscrepancysequences.cpp}::dim003DiscrRStartHalton, anonymous_namespace{lowdiscrepancysequences.cpp}::dim005DiscrRStartHalton, anonymous_namespace{lowdiscrepancysequences.cpp}::dim010DiscrRStartHalton, anonymous_namespace{lowdiscrepancysequences.cpp}::dim015DiscrRStartHalton, anonymous_namespace{lowdiscrepancysequences.cpp}::dim030DiscrRStartHalton, anonymous_namespace{lowdiscrepancysequences.cpp}::dim050DiscrRStartHalton, anonymous_namespace{lowdiscrepancysequences.cpp}::dim100DiscrRStartHalton, and anonymous_namespace{lowdiscrepancysequences.cpp}::testGeneratorDiscrepancy().
Referenced by suite().
{
    BOOST_MESSAGE("Testing random-start Halton discrepancy...");
    const Real * const discrepancy[8] = {
        dim002DiscrRStartHalton, dim003DiscrRStartHalton,
        dim005DiscrRStartHalton, dim010DiscrRStartHalton,
        dim015DiscrRStartHalton, dim030DiscrRStartHalton,
        dim050DiscrRStartHalton, dim100DiscrRStartHalton};
    testGeneratorDiscrepancy(HaltonFactory(true,false),
                             discrepancy,
                             "RandomStartHaltonDiscrepancy.txt",
                             "DiscrRStartHalton");
}
void LowDiscrepancyTest::testRandomStartRandomShiftHaltonDiscrepancy () [static]
Definition at line 967 of file lowdiscrepancysequences.cpp.
References anonymous_namespace{lowdiscrepancysequences.cpp}::dim002DiscrRStRShHalton, anonymous_namespace{lowdiscrepancysequences.cpp}::dim003DiscrRStRShHalton, anonymous_namespace{lowdiscrepancysequences.cpp}::dim005DiscrRStRShHalton, anonymous_namespace{lowdiscrepancysequences.cpp}::dim010DiscrRStRShHalton, anonymous_namespace{lowdiscrepancysequences.cpp}::dim015DiscrRStRShHalton, anonymous_namespace{lowdiscrepancysequences.cpp}::dim030DiscrRStRShHalton, anonymous_namespace{lowdiscrepancysequences.cpp}::dim050DiscrRStRShHalton, anonymous_namespace{lowdiscrepancysequences.cpp}::dim100DiscrRStRShHalton, and anonymous_namespace{lowdiscrepancysequences.cpp}::testGeneratorDiscrepancy().
Referenced by suite().
{
    BOOST_MESSAGE("Testing random-start, random-shift Halton discrepancy...");
    const Real * const discrepancy[8] = {
        dim002DiscrRStRShHalton, dim003DiscrRStRShHalton,
        dim005DiscrRStRShHalton, dim010DiscrRStRShHalton,
        dim015DiscrRStRShHalton, dim030DiscrRStRShHalton,
        dim050DiscrRStRShHalton, dim100DiscrRStRShHalton};
    testGeneratorDiscrepancy(HaltonFactory(true,true),
                             discrepancy,
                             "RandomStartRandomShiftHaltonDiscrepancy.txt",
                             "DiscrRStRShHalton");
}
void LowDiscrepancyTest::testSeedGenerator () [static]
Definition at line 46 of file lowdiscrepancysequences.cpp.
References QuantLib::SeedGenerator::get(), and QuantLib::Singleton< SeedGenerator >::instance().
Referenced by suite().
{
    BOOST_MESSAGE("Testing random-seed generator...");
    SeedGenerator::instance().get();
}
void LowDiscrepancyTest::testSobol () [static]
Definition at line 177 of file lowdiscrepancysequences.cpp.
References QuantLib::GenericSequenceStatistics< StatisticsType >::add(), anonymous_namespace{lowdiscrepancysequences.cpp}::dimensionality, QuantLib::GenericSequenceStatistics< StatisticsType >::mean(), QuantLib::SobolRsg::nextSequence(), QuantLib::io::ordinal(), QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow(), PPMT_MAX_DIM, QL_FIXED, QL_SCIENTIFIC, anonymous_namespace{gaussianquadratures.cpp}::tolerance, and QuantLib::Sample< T >::value.
Referenced by suite().
{
    BOOST_MESSAGE("Testing Sobol sequences up to dimension "
                  << PPMT_MAX_DIM << "...");
    std::vector<Real> point;
    Real tolerance = 1.0e-15;
    // testing max dimensionality
    Size dimensionality = PPMT_MAX_DIM;
    BigNatural seed = 123456;
    SobolRsg rsg(dimensionality, seed);
    Size points = 100, i;
    for (i=0; i<points; i++) {
        point = rsg.nextSequence().value;
        if (point.size()!=dimensionality) {
            BOOST_ERROR("Sobol sequence generator returns "
                        " a sequence of wrong dimensionality: " << point.size()
                        << " instead of  " << dimensionality);
        }
    }
    // testing homogeneity properties
    dimensionality = 33;
    seed = 123456;
    rsg = SobolRsg(dimensionality, seed);
    SequenceStatistics stat(dimensionality);
    std::vector<Real> mean;
    Size k = 0;
    for (Integer j=1; j<5; j++) { // five cycle
        points = Size(std::pow(2.0, j))-1; // base 2
        for (; k<points; k++) {
            point = rsg.nextSequence().value;
            stat.add(point);
        }
        mean = stat.mean();
        for (i=0; i<dimensionality; i++) {
            Real error = std::fabs(mean[i]-0.5);
            if (error > tolerance) {
                BOOST_ERROR(io::ordinal(i+1) << " dimension: "
                            << QL_FIXED
                            << "mean (" << mean[i]
                            << ") at the end of the " << io::ordinal(j+1)
                            << " cycle in Sobol sequence is not " << 0.5
                            << QL_SCIENTIFIC
                            << " (error = " << error << ")");
            }
        }
    }
    // testing first dimension (van der Corput sequence)
    const Real vanderCorputSequenceModuloTwo[] = {
        // first cycle (zero excluded)
        0.50000,
        // second cycle
        0.75000, 0.25000,
        // third cycle
        0.37500, 0.87500, 0.62500, 0.12500,
        // fourth cycle
        0.18750, 0.68750, 0.93750, 0.43750, 0.31250, 0.81250, 0.56250, 0.06250,
        // fifth cycle
        0.09375, 0.59375, 0.84375, 0.34375, 0.46875, 0.96875, 0.71875, 0.21875,
        0.15625, 0.65625, 0.90625, 0.40625, 0.28125, 0.78125, 0.53125, 0.03125
    };
    dimensionality = 1;
    rsg = SobolRsg(dimensionality);
    points = Size(std::pow(2.0, 5))-1; // five cycles
    for (i=0; i<points; i++) {
        point = rsg.nextSequence().value;
        Real error = std::fabs(point[0]-vanderCorputSequenceModuloTwo[i]);
        if (error > tolerance) {
            BOOST_ERROR(io::ordinal(i+1) << " draw ("
                        << QL_FIXED << point[0]
                        << ") in 1-D Sobol sequence is not in the "
                        << "van der Corput sequence modulo two: "
                        << "it should have been "
                        << vanderCorputSequenceModuloTwo[i]
                        << QL_SCIENTIFIC
                        << " (error = " << error << ")");
        }
    }
}
void LowDiscrepancyTest::testSobolLevitanLemieuxSobolDiscrepancy () [static]
Definition at line 1015 of file lowdiscrepancysequences.cpp.
References anonymous_namespace{lowdiscrepancysequences.cpp}::dim002Discr_Sobol, anonymous_namespace{lowdiscrepancysequences.cpp}::dim003Discr_Sobol, anonymous_namespace{lowdiscrepancysequences.cpp}::dim005Discr_Sobol, anonymous_namespace{lowdiscrepancysequences.cpp}::dim010DiscrSobLev_Sobol, anonymous_namespace{lowdiscrepancysequences.cpp}::dim015DiscrSobLev_Sobol, anonymous_namespace{lowdiscrepancysequences.cpp}::dim030DiscrSobLev_Sobol, anonymous_namespace{lowdiscrepancysequences.cpp}::dim050DiscrSobLem_Sobol, anonymous_namespace{lowdiscrepancysequences.cpp}::dim100DiscrSobLem_Sobol, QuantLib::SobolRsg::SobolLevitanLemieux, and anonymous_namespace{lowdiscrepancysequences.cpp}::testGeneratorDiscrepancy().
Referenced by suite().
{
    BOOST_MESSAGE("Testing Levitan-Lemieux-Sobol discrepancy...");
    const Real * const discrepancy[8] = {
        dim002Discr_Sobol, dim003Discr_Sobol,
        dim005Discr_Sobol, dim010DiscrSobLev_Sobol,
        dim015DiscrSobLev_Sobol, dim030DiscrSobLev_Sobol,
        dim050DiscrSobLem_Sobol, dim100DiscrSobLem_Sobol};
    testGeneratorDiscrepancy(SobolFactory(SobolRsg::SobolLevitanLemieux),
                             discrepancy,
                             "SobolLevitanLemieuxSobolDiscrepancy.txt",
                             "DiscrSobLevLem_Sobol");
}
void LowDiscrepancyTest::testSobolLevitanSobolDiscrepancy () [static]
Definition at line 999 of file lowdiscrepancysequences.cpp.
References anonymous_namespace{lowdiscrepancysequences.cpp}::dim002Discr_Sobol, anonymous_namespace{lowdiscrepancysequences.cpp}::dim003Discr_Sobol, anonymous_namespace{lowdiscrepancysequences.cpp}::dim005Discr_Sobol, anonymous_namespace{lowdiscrepancysequences.cpp}::dim010DiscrSobLev_Sobol, anonymous_namespace{lowdiscrepancysequences.cpp}::dim015DiscrSobLev_Sobol, anonymous_namespace{lowdiscrepancysequences.cpp}::dim030DiscrSobLev_Sobol, anonymous_namespace{lowdiscrepancysequences.cpp}::dim050DiscrSobLev_Sobol, anonymous_namespace{lowdiscrepancysequences.cpp}::dim100DiscrSobLev_Sobol, QuantLib::SobolRsg::SobolLevitan, and anonymous_namespace{lowdiscrepancysequences.cpp}::testGeneratorDiscrepancy().
Referenced by suite().
{
    BOOST_MESSAGE("Testing Levitan-Sobol discrepancy...");
    const Real * const discrepancy[8] = {
        dim002Discr_Sobol, dim003Discr_Sobol,
        dim005Discr_Sobol, dim010DiscrSobLev_Sobol,
        dim015DiscrSobLev_Sobol, dim030DiscrSobLev_Sobol,
        dim050DiscrSobLev_Sobol, dim100DiscrSobLev_Sobol};
    testGeneratorDiscrepancy(SobolFactory(SobolRsg::SobolLevitan),
                             discrepancy,
                             "SobolLevitanSobolDiscrepancy.txt",
                             "DiscrSobLev_Sobol");
}
void LowDiscrepancyTest::testSobolSkipping () [static]
Definition at line 1048 of file lowdiscrepancysequences.cpp.
References anonymous_namespace{lowdiscrepancysequences.cpp}::dimensionality, QuantLib::SobolRsg::Jaeckel, LENGTH, QuantLib::SobolRsg::nextInt32Sequence(), QuantLib::SobolRsg::skipTo(), QuantLib::SobolRsg::SobolLevitan, QuantLib::SobolRsg::SobolLevitanLemieux, and QuantLib::SobolRsg::Unit.
Referenced by suite().
{
    BOOST_MESSAGE("Testing Sobol sequence skipping...");
    unsigned long seed = 42;
    Size dimensionality[] = { 1, 10, 100, 1000 };
    unsigned long skip[] = { 0, 1, 42, 512, 100000 };
    SobolRsg::DirectionIntegers integers[] = { SobolRsg::Unit,
                                               SobolRsg::Jaeckel,
                                               SobolRsg::SobolLevitan,
                                               SobolRsg::SobolLevitanLemieux };
    for (Size i=0; i<LENGTH(integers); i++) {
      for (Size j=0; j<LENGTH(dimensionality); j++) {
        for (Size k=0; k<LENGTH(skip); k++) {
            // extract n samples
            SobolRsg rsg1(dimensionality[j], seed, integers[i]);
            for (Size l=0; l<skip[k]; l++)
                rsg1.nextInt32Sequence();
            // skip n samples at once
            SobolRsg rsg2(dimensionality[j], seed, integers[i]);
            rsg2.skipTo(skip[k]);
            // compare next 100 samples
            for (Size m=0; m<100; m++) {
                std::vector<unsigned long> s1 = rsg1.nextInt32Sequence();
                std::vector<unsigned long> s2 = rsg2.nextInt32Sequence();
                for (Size n=0; n<s1.size(); n++) {
                    if (s1[n] != s2[n]) {
                        BOOST_ERROR("Mismatch after skipping:"
                                    << "\n  size:     " << dimensionality[j]
                                    << "\n  integers: " << integers[i]
                                    << "\n  skipped:  " << skip[k]
                                    << "\n  at index: " << n
                                    << "\n  expected: " << s1[n]
                                    << "\n  found:    " << s2[n]);
                    }
                }
            }
        }
      }
    }
}
void LowDiscrepancyTest::testUnitSobolDiscrepancy () [static]
Definition at line 1031 of file lowdiscrepancysequences.cpp.
References anonymous_namespace{lowdiscrepancysequences.cpp}::dim002Discr__Unit_Sobol, anonymous_namespace{lowdiscrepancysequences.cpp}::dim003Discr__Unit_Sobol, anonymous_namespace{lowdiscrepancysequences.cpp}::dim005Discr__Unit_Sobol, anonymous_namespace{lowdiscrepancysequences.cpp}::dim010Discr__Unit_Sobol, anonymous_namespace{lowdiscrepancysequences.cpp}::dim015Discr__Unit_Sobol, anonymous_namespace{lowdiscrepancysequences.cpp}::dim030Discr__Unit_Sobol, anonymous_namespace{lowdiscrepancysequences.cpp}::dim050Discr__Unit_Sobol, anonymous_namespace{lowdiscrepancysequences.cpp}::dim100Discr__Unit_Sobol, anonymous_namespace{lowdiscrepancysequences.cpp}::testGeneratorDiscrepancy(), and QuantLib::SobolRsg::Unit.
Referenced by suite().
{
    BOOST_MESSAGE("Testing unit Sobol discrepancy...");
    const Real * const discrepancy[8] = {
        dim002Discr__Unit_Sobol, dim003Discr__Unit_Sobol,
        dim005Discr__Unit_Sobol, dim010Discr__Unit_Sobol,
        dim015Discr__Unit_Sobol, dim030Discr__Unit_Sobol,
        dim050Discr__Unit_Sobol, dim100Discr__Unit_Sobol};
        testGeneratorDiscrepancy(SobolFactory(SobolRsg::Unit),
                             discrepancy,
                             "UnitSobolDiscrepancy.txt",
                             "Discr__Unit_Sobol");
}
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/lowdiscrepancysequences.hpp
/home/deriversatile/QuantLib/QuantLibQt/test-suite/lowdiscrepancysequences.cpp