QuantLib: QuantLib::Coupon Class Reference
QuantLib::Coupon Class Reference
coupon accruing over a fixed period
#include <coupon.hpp>
Public Member Functions
Coupon (const Date &paymentDate, Real nominal, const Date &accrualStartDate, const Date &accrualEndDate, const Date &refPeriodStart=Date(), const Date &refPeriodEnd=Date())
Event interface
Date date () const
Inspectors
Real nominal () const
const Date & accrualStartDate () const
start of the accrual period
const Date & accrualEndDate () const
end of the accrual period
const Date & referencePeriodStart () const
start date of the reference period
const Date & referencePeriodEnd () const
end date of the reference period
Time accrualPeriod () const
accrual period as fraction of year
BigInteger accrualDays () const
accrual period in days
virtual Rate rate () const =0
accrued rate
virtual DayCounter dayCounter () const =0
day counter for accrual calculation
Time accruedPeriod (const Date &) const
accrued period as fraction of year at the given date
BigInteger accruedDays (const Date &) const
accrued days at the given date
virtual Real accruedAmount (const Date &) const =0
accrued amount at the given date
Visitability
virtual void accept (AcyclicVisitor &)
Protected Attributes
Date paymentDate_
Real nominal_
Date accrualStartDate_
Date accrualEndDate_
Date refPeriodStart_
Date refPeriodEnd_
Detailed Description
coupon accruing over a fixed period
This class implements part of the CashFlow interface but it is still abstract and provides derived classes with methods for accrual period calculations.
Definition at line 39 of file coupon.hpp.
Constructor & Destructor Documentation
QuantLib::Coupon::Coupon (const Date & paymentDate, Real nominal, const Date & accrualStartDate, const Date & accrualEndDate, const Date & refPeriodStart = Date(), const Date & refPeriodEnd = Date())
Warning:
the coupon does not adjust the payment date which must already be a business day.
Definition at line 26 of file coupon.cpp.
References accrualEndDate_, accrualStartDate_, refPeriodEnd_, and refPeriodStart_.
    : paymentDate_(paymentDate), nominal_(nominal),
      accrualStartDate_(accrualStartDate), accrualEndDate_(accrualEndDate),
      refPeriodStart_(refPeriodStart), refPeriodEnd_(refPeriodEnd) {
        if (refPeriodStart_ == Date())
            refPeriodStart_ = accrualStartDate_;
        if (refPeriodEnd_ == Date())
            refPeriodEnd_ = accrualEndDate_;
    }
Member Function Documentation
void QuantLib::Coupon::accept (AcyclicVisitor & v) [virtual]
Reimplemented from QuantLib::CashFlow.
Reimplemented in QuantLib::CappedFlooredCmsCoupon, QuantLib::DigitalCoupon, QuantLib::CappedFlooredIborCoupon, QuantLib::CappedFlooredYoYInflationCoupon, QuantLib::CPICoupon, QuantLib::FloatingRateCoupon, QuantLib::InflationCoupon, QuantLib::CappedFlooredCoupon, QuantLib::SubPeriodsCoupon, QuantLib::RangeAccrualFloatersCoupon, QuantLib::AverageBMACoupon, QuantLib::FixedRateCoupon, QuantLib::OvernightIndexedCoupon, QuantLib::YoYInflationCoupon, QuantLib::IborCoupon, QuantLib::CmsCoupon, QuantLib::DigitalCmsCoupon, and QuantLib::DigitalIborCoupon.
Definition at line 73 of file coupon.cpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Visitor< T >::visit().
{
        Visitor<Coupon>* v1 = dynamic_cast<Visitor<Coupon>*>(&v);
        if (v1 != 0)
            v1->visit(*this);
        else
            CashFlow::accept(v);
    }
BigInteger QuantLib::Coupon::accrualDays () const
accrual period in days
Definition at line 48 of file coupon.cpp.
References accrualEndDate_, accrualStartDate_, QuantLib::DayCounter::dayCount(), and dayCounter().
Referenced by QuantLib::CashFlows::accrualDays().
{
        return dayCounter().dayCount(accrualStartDate_,
                                     accrualEndDate_);
    }
const Date & QuantLib::Coupon::accrualEndDate () const [inline]
end of the accrual period
Definition at line 101 of file coupon.hpp.
References accrualEndDate_.
Referenced by QuantLib::CashFlows::accrualEndDate().
{
        return accrualEndDate_;
    }
Time QuantLib::Coupon::accrualPeriod () const
accrual period as fraction of year
Definition at line 41 of file coupon.cpp.
References accrualEndDate_, accrualStartDate_, dayCounter(), refPeriodEnd_, refPeriodStart_, and QuantLib::DayCounter::yearFraction().
Referenced by QuantLib::CashFlows::accrualPeriod(), QuantLib::FloatingRateCoupon::amount(), QuantLib::InflationCoupon::amount(), QuantLib::HaganPricer::capletPrice(), QuantLib::CPICouponPricer::capletRate(), QuantLib::YoYInflationCouponPricer::capletRate(), QuantLib::HaganPricer::capletRate(), QuantLib::HaganPricer::floorletPrice(), QuantLib::CPICouponPricer::floorletRate(), QuantLib::YoYInflationCouponPricer::floorletRate(), QuantLib::HaganPricer::floorletRate(), QuantLib::CPICouponPricer::initialize(), QuantLib::BlackIborCouponPricer::initialize(), QuantLib::YoYInflationCouponPricer::initialize(), QuantLib::RangeAccrualPricer::initialize(), QuantLib::SubPeriodsPricer::initialize(), QuantLib::HaganPricer::initialize(), QuantLib::CPICouponPricer::optionletPrice(), QuantLib::YoYInflationCouponPricer::optionletPrice(), QuantLib::NumericHaganPricer::optionletPrice(), QuantLib::AnalyticHaganPricer::optionletPrice(), QuantLib::RangeAccrualFloatersCoupon::priceWithoutOptionality(), QuantLib::CPICouponPricer::swapletPrice(), QuantLib::YoYInflationCouponPricer::swapletPrice(), QuantLib::AveragingRatePricer::swapletPrice(), QuantLib::CompoundingRatePricer::swapletPrice(), QuantLib::NumericHaganPricer::swapletPrice(), QuantLib::AnalyticHaganPricer::swapletPrice(), QuantLib::HaganPricer::swapletRate(), and QuantLib::anonymous_namespace{cashflows.cpp}::BPSCalculator::visit().
{
        return dayCounter().yearFraction(accrualStartDate_,
                                         accrualEndDate_,
                                         refPeriodStart_,
                                         refPeriodEnd_);
    }
const Date & QuantLib::Coupon::accrualStartDate () const [inline]
start of the accrual period
Definition at line 97 of file coupon.hpp.
References accrualStartDate_.
Referenced by QuantLib::CashFlows::accrualStartDate().
{
        return accrualStartDate_;
    }
virtual Real QuantLib::Coupon::accruedAmount (const Date &) const [pure virtual]
accrued amount at the given date
Implemented in QuantLib::FloatingRateCoupon, QuantLib::InflationCoupon, and QuantLib::FixedRateCoupon.
Referenced by QuantLib::CallableFixedRateBond::accrued(), and QuantLib::CashFlows::accruedAmount().
BigInteger QuantLib::Coupon::accruedDays (const Date & d) const
accrued days at the given date
Definition at line 64 of file coupon.cpp.
References accrualEndDate_, accrualStartDate_, QuantLib::DayCounter::dayCount(), dayCounter(), and paymentDate_.
Referenced by QuantLib::CashFlows::accruedDays().
{
        if (d <= accrualStartDate_ || d > paymentDate_) {
            return 0;
        } else {
            return dayCounter().dayCount(accrualStartDate_,
                                         std::min(d, accrualEndDate_));
        }
    }
Time QuantLib::Coupon::accruedPeriod (const Date & d) const
accrued period as fraction of year at the given date
Definition at line 53 of file coupon.cpp.
References accrualEndDate_, accrualStartDate_, dayCounter(), paymentDate_, refPeriodEnd_, refPeriodStart_, and QuantLib::DayCounter::yearFraction().
Referenced by QuantLib::CashFlows::accruedPeriod().
{
        if (d <= accrualStartDate_ || d > paymentDate_) {
            return 0.0;
        } else {
            return dayCounter().yearFraction(accrualStartDate_,
                                             std::min(d, accrualEndDate_),
                                             refPeriodStart_,
                                             refPeriodEnd_);
        }
    }
Date QuantLib::Coupon::date () const [inline, virtual]
Note:
This is inherited from the event class
Implements QuantLib::CashFlow.
Definition at line 52 of file coupon.hpp.
References paymentDate_.
Referenced by QuantLib::GFunctionFactory::GFunctionExactYield::GFunctionExactYield(), QuantLib::GFunctionFactory::GFunctionWithShifts::GFunctionWithShifts(), QuantLib::CPICouponPricer::initialize(), QuantLib::BlackIborCouponPricer::initialize(), QuantLib::YoYInflationCouponPricer::initialize(), QuantLib::RangeAccrualPricer::initialize(), QuantLib::SubPeriodsPricer::initialize(), QuantLib::HaganPricer::initialize(), QuantLib::InflationCoupon::price(), QuantLib::FloatingRateCoupon::price(), QuantLib::RangeAccrualFloatersCoupon::priceWithoutOptionality(), and QuantLib::anonymous_namespace{cashflows.cpp}::BPSCalculator::visit().
{ return paymentDate_; }
virtual DayCounter QuantLib::Coupon::dayCounter () const [pure virtual]
day counter for accrual calculation
Implemented in QuantLib::FloatingRateCoupon, QuantLib::InflationCoupon, and QuantLib::FixedRateCoupon.
Referenced by accrualDays(), accrualPeriod(), accruedDays(), and accruedPeriod().
Real QuantLib::Coupon::nominal () const [inline]
Definition at line 93 of file coupon.hpp.
References nominal_.
Referenced by QuantLib::FixedRateCoupon::accruedAmount(), QuantLib::FloatingRateCoupon::accruedAmount(), QuantLib::InflationCoupon::accruedAmount(), QuantLib::FixedRateCoupon::amount(), QuantLib::FloatingRateCoupon::amount(), QuantLib::InflationCoupon::amount(), QuantLib::CashFlows::nominal(), QuantLib::RangeAccrualFloatersCoupon::priceWithoutOptionality(), and QuantLib::anonymous_namespace{cashflows.cpp}::BPSCalculator::visit().
{
        return nominal_;
    }
virtual Rate QuantLib::Coupon::rate () const [pure virtual]
accrued rate
Implemented in QuantLib::CappedFlooredYoYInflationCoupon, QuantLib::DigitalCoupon, QuantLib::InflationCoupon, QuantLib::FloatingRateCoupon, QuantLib::CappedFlooredCoupon, and QuantLib::FixedRateCoupon.
const Date & QuantLib::Coupon::referencePeriodEnd () const [inline]
end date of the reference period
Definition at line 109 of file coupon.hpp.
References refPeriodEnd_.
Referenced by QuantLib::CashFlows::referencePeriodEnd().
{
        return refPeriodEnd_;
    }
const Date & QuantLib::Coupon::referencePeriodStart () const [inline]
start date of the reference period
Definition at line 105 of file coupon.hpp.
References refPeriodStart_.
Referenced by QuantLib::CashFlows::referencePeriodStart().
{
        return refPeriodStart_;
    }
Member Data Documentation
Date QuantLib::Coupon::accrualEndDate_ [protected]
Definition at line 87 of file coupon.hpp.
Referenced by accrualDays(), accrualEndDate(), accrualPeriod(), QuantLib::FixedRateCoupon::accruedAmount(), QuantLib::FloatingRateCoupon::accruedAmount(), QuantLib::InflationCoupon::accruedAmount(), accruedDays(), accruedPeriod(), QuantLib::FixedRateCoupon::amount(), Coupon(), QuantLib::FloatingRateCoupon::fixingDate(), and QuantLib::IborCoupon::IborCoupon().
Date QuantLib::Coupon::accrualStartDate_ [protected]
Definition at line 87 of file coupon.hpp.
Referenced by accrualDays(), accrualPeriod(), accrualStartDate(), QuantLib::FixedRateCoupon::accruedAmount(), QuantLib::FloatingRateCoupon::accruedAmount(), QuantLib::InflationCoupon::accruedAmount(), accruedDays(), accruedPeriod(), QuantLib::FixedRateCoupon::amount(), Coupon(), and QuantLib::FloatingRateCoupon::fixingDate().
Real QuantLib::Coupon::nominal_ [protected]
Definition at line 86 of file coupon.hpp.
Referenced by nominal().
Date QuantLib::Coupon::paymentDate_ [protected]
Definition at line 85 of file coupon.hpp.
Referenced by QuantLib::FixedRateCoupon::accruedAmount(), QuantLib::FloatingRateCoupon::accruedAmount(), QuantLib::InflationCoupon::accruedAmount(), accruedDays(), accruedPeriod(), and date().
Date QuantLib::Coupon::refPeriodEnd_ [protected]
Definition at line 87 of file coupon.hpp.
Referenced by accrualPeriod(), QuantLib::FixedRateCoupon::accruedAmount(), QuantLib::InflationCoupon::accruedAmount(), QuantLib::FloatingRateCoupon::accruedAmount(), accruedPeriod(), QuantLib::FixedRateCoupon::amount(), Coupon(), QuantLib::InflationCoupon::fixingDate(), and referencePeriodEnd().
Date QuantLib::Coupon::refPeriodStart_ [protected]
Definition at line 87 of file coupon.hpp.
Referenced by accrualPeriod(), QuantLib::FixedRateCoupon::accruedAmount(), QuantLib::InflationCoupon::accruedAmount(), QuantLib::FloatingRateCoupon::accruedAmount(), accruedPeriod(), QuantLib::FixedRateCoupon::amount(), Coupon(), and referencePeriodStart().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/coupon.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/coupon.cpp