QuantLib: QuantLib::TsiveriotisFernandesLattice< T > Class Template Reference
QuantLib::TsiveriotisFernandesLattice< T > Class Template Reference
Binomial lattice approximating the Tsiveriotis-Fernandes model.
#include <tflattice.hpp>
Public Member Functions
TsiveriotisFernandesLattice (const boost::shared_ptr< T > &tree, Rate riskFreeRate, Time end, Size steps, Spread creditSpread, Volatility volatility, Spread divYield)
Spread creditSpread () const
Protected Member Functions
void stepback (Size i, const Array &values, const Array &conversionProbability, const Array &spreadAdjustedRate, Array &newValues, Array &newConversionProbability, Array &newSpreadAdjustedRate) const
void rollback (DiscretizedAsset &, Time to) const
void partialRollback (DiscretizedAsset &, Time to) const
Private Attributes
Spread creditSpread_
Detailed Description
template<class T>
class QuantLib::TsiveriotisFernandesLattice< T >
Binomial lattice approximating the Tsiveriotis-Fernandes model.
Definition at line 36 of file tflattice.hpp.
Constructor & Destructor Documentation
template<class T > QuantLib::TsiveriotisFernandesLattice< T >::TsiveriotisFernandesLattice (const boost::shared_ptr< T > & tree, Rate riskFreeRate, Time end, Size steps, Spread creditSpread, Volatility volatility, Spread divYield)
Definition at line 67 of file tflattice.hpp.
References QuantLib::BlackScholesLattice< T >::pu_, and QL_REQUIRE.
    : BlackScholesLattice<T>(tree, riskFreeRate, end, steps),
      creditSpread_(creditSpread) {
        QL_REQUIRE(this->pu_<=1.0,
                   "probability (" << this->pu_ << ") higher than one");
        QL_REQUIRE(this->pu_>=0.0,
                   "negative (" << this->pu_ << ") probability");
    }
Member Function Documentation
template<class T > Spread QuantLib::TsiveriotisFernandesLattice< T >::creditSpread () const [inline]
Definition at line 46 of file tflattice.hpp.
References QuantLib::TsiveriotisFernandesLattice< T >::creditSpread_.
{ return creditSpread_; };
template<class T > void QuantLib::TsiveriotisFernandesLattice< T >::partialRollback (DiscretizedAsset & , Time to) const [protected, virtual]
Roll back an asset until the given time, but do not perform the final adjustment.
Warning:
In version 0.3.7 and earlier, this method was called rollAlmostBack method and performed pre-adjustment. This is no longer true; when migrating your code, you'll have to replace calls such as:
                     method->rollAlmostBack(asset,t);
with the two statements:
                     method->partialRollback(asset,t);
                     asset->preAdjustValues();
Reimplemented from QuantLib::TreeLattice< BlackScholesLattice< T > >.
Definition at line 124 of file tflattice.hpp.
References QuantLib::DiscretizedAsset::adjustValues(), QuantLib::close(), QuantLib::DiscretizedConvertible::conversionProbability(), QL_REQUIRE, QuantLib::DiscretizedConvertible::spreadAdjustedRate(), QuantLib::DiscretizedAsset::time(), and QuantLib::DiscretizedAsset::values().
{
        Time from = asset.time();
        if (close(from,to))
            return;
        QL_REQUIRE(from > to,
                   "cannot roll the asset back to" << to
                   << " (it is already at t = " << from << ")");
        DiscretizedConvertible& convertible =
            dynamic_cast<DiscretizedConvertible&>(asset);
        Integer iFrom = Integer(this->t_.index(from));
        Integer iTo = Integer(this->t_.index(to));
        for (Integer i=iFrom-1; i>=iTo; --i) {
            Array newValues(this->size(i));
            Array newSpreadAdjustedRate(this->size(i));
            Array newConversionProbability(this->size(i));
            stepback(i, convertible.values(),
                     convertible.conversionProbability(),
                     convertible.spreadAdjustedRate(), newValues,
                     newConversionProbability,newSpreadAdjustedRate);
            convertible.time() = this->t_[i];
            convertible.values() = newValues;
            convertible.spreadAdjustedRate() = newSpreadAdjustedRate;
            convertible.conversionProbability() = newConversionProbability;
            // skip the very last adjustment
            if (i != iTo)
                convertible.adjustValues();
        }
    }
template<class T > void QuantLib::TsiveriotisFernandesLattice< T >::rollback (DiscretizedAsset & , Time to) const [protected, virtual]
Roll back an asset until the given time, performing any needed adjustment.
Reimplemented from QuantLib::TreeLattice< BlackScholesLattice< T > >.
Definition at line 116 of file tflattice.hpp.
References QuantLib::DiscretizedAsset::adjustValues().
{
        partialRollback(asset,to);
        asset.adjustValues();
    }
template<class T > void QuantLib::TsiveriotisFernandesLattice< T >::stepback (Size i, const Array & values, const Array & conversionProbability, const Array & spreadAdjustedRate, Array & newValues, Array & newConversionProbability, Array & newSpreadAdjustedRate) const [protected]
Definition at line 84 of file tflattice.hpp.
{
        for (Size j=0; j<this->size(i); j++) {
            // new conversion probability is calculated via backward
            // induction using up and down probabilities on tree on
            // previous conversion probabilities, ie weighted average
            // of previous probabilities.
            newConversionProbability[j] =
                this->pd_*conversionProbability[j] +
                this->pu_*conversionProbability[j+1];
            // Use blended discounting rate
            newSpreadAdjustedRate[j] =
                newConversionProbability[j] * this->riskFreeRate_ +
                (1-newConversionProbability[j])*(this->riskFreeRate_+creditSpread_);
            newValues[j] =
                (this->pd_*values[j]/(1+(spreadAdjustedRate[j]*this->dt_)))
              + (this->pu_*values[j+1]/(1+(spreadAdjustedRate[j+1]*this->dt_)));
        }
    }
Member Data Documentation
template<class T > Spread QuantLib::TsiveriotisFernandesLattice< T >::creditSpread_ [private]
Definition at line 60 of file tflattice.hpp.
Referenced by QuantLib::TsiveriotisFernandesLattice< T >::creditSpread().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/convertiblebonds/tflattice.hpp