QuantLib: ForwardOptionTest Class Reference
ForwardOptionTest Class Reference
#include <forwardoption.hpp>
Static Public Member Functions
static void testValues ()
static void testGreeks ()
static void testPerformanceValues ()
static void testPerformanceGreeks ()
static
boost::unit_test_framework::test_suite * suite ()
Detailed Description
Definition at line 28 of file forwardoption.hpp.
Member Function Documentation
test_suite * ForwardOptionTest::suite () [static]
Definition at line 385 of file forwardoption.cpp.
References QUANTLIB_TEST_CASE, testGreeks(), testPerformanceGreeks(), testPerformanceValues(), and testValues().
Referenced by init_unit_test_suite().
{
    test_suite* suite = BOOST_TEST_SUITE("Forward option tests");
    suite->add(QUANTLIB_TEST_CASE(&ForwardOptionTest::testValues));
    suite->add(QUANTLIB_TEST_CASE(&ForwardOptionTest::testGreeks));
    suite->add(QUANTLIB_TEST_CASE(&ForwardOptionTest::testPerformanceValues));
    suite->add(QUANTLIB_TEST_CASE(&ForwardOptionTest::testPerformanceGreeks));
    return suite;
}
void ForwardOptionTest::testGreeks () [static]
Definition at line 365 of file forwardoption.cpp.
Referenced by suite().
{
    BOOST_MESSAGE("Testing forward option greeks...");
    SavedSettings backup;
    testForwardGreeks<ForwardVanillaEngine>();
}
void ForwardOptionTest::testPerformanceGreeks () [static]
Definition at line 375 of file forwardoption.cpp.
Referenced by suite().
{
    BOOST_MESSAGE("Testing forward performance option greeks...");
    SavedSettings backup;
    testForwardGreeks<ForwardPerformanceVanillaEngine>();
}
void ForwardOptionTest::testPerformanceValues () [static]
Definition at line 140 of file forwardoption.cpp.
References QuantLib::Option::Call, QuantLib::flatRate(), QuantLib::flatVol(), LENGTH, QuantLib::Instrument::NPV(), QuantLib::Option::Put, REPORT_FAILURE, anonymous_namespace{inflationvolatility.cpp}::reset(), QuantLib::Instrument::setPricingEngine(), anonymous_namespace{quantlibbenchmark.cpp}::t, anonymous_namespace{marketmodel.cpp}::todaysDate, anonymous_namespace{gaussianquadratures.cpp}::tolerance, and anonymous_namespace{perturbativebarrieroptionengine.cpp}::v().
Referenced by suite().
{
    BOOST_MESSAGE("Testing forward performance option values...");
    /* The data below are the performance equivalent of the
       forward options tested above and taken from
       "Option pricing formulas", E.G. Haug, McGraw-Hill 1998
    */
    ForwardOptionData values[] = {
        //  type, moneyness, spot,  div, rate,start, maturity,  vol,                       result, tol
        { Option::Call, 1.1, 60.0, 0.04, 0.08, 0.25,      1.0, 0.30, 4.4064/60*std::exp(-0.04*0.25), 1.0e-4 },
        {  Option::Put, 1.1, 60.0, 0.04, 0.08, 0.25,      1.0, 0.30, 8.2971/60*std::exp(-0.04*0.25), 1.0e-4 }
    };
    DayCounter dc = Actual360();
    Date today = Date::todaysDate();
    boost::shared_ptr<SimpleQuote> spot(new SimpleQuote(0.0));
    boost::shared_ptr<SimpleQuote> qRate(new SimpleQuote(0.0));
    Handle<YieldTermStructure> qTS(flatRate(today, qRate, dc));
    boost::shared_ptr<SimpleQuote> rRate(new SimpleQuote(0.0));
    Handle<YieldTermStructure> rTS(flatRate(today, rRate, dc));
    boost::shared_ptr<SimpleQuote> vol(new SimpleQuote(0.0));
    Handle<BlackVolTermStructure> volTS(flatVol(today, vol, dc));
    boost::shared_ptr<BlackScholesMertonProcess> stochProcess(
         new BlackScholesMertonProcess(Handle<Quote>(spot),
                                       Handle<YieldTermStructure>(qTS),
                                       Handle<YieldTermStructure>(rTS),
                                       Handle<BlackVolTermStructure>(volTS)));
    boost::shared_ptr<PricingEngine> engine(
        new ForwardPerformanceVanillaEngine<AnalyticEuropeanEngine>(
                                                               stochProcess));
    for (Size i=0; i<LENGTH(values); i++) {
        boost::shared_ptr<StrikedTypePayoff> payoff(
                                 new PlainVanillaPayoff(values[i].type, 0.0));
        Date exDate = today + Integer(values[i].t*360+0.5);
        boost::shared_ptr<Exercise> exercise(new EuropeanExercise(exDate));
        Date reset = today + Integer(values[i].start*360+0.5);
        spot ->setValue(values[i].s);
        qRate->setValue(values[i].q);
        rRate->setValue(values[i].r);
        vol  ->setValue(values[i].v);
        ForwardVanillaOption option(values[i].moneyness, reset,
                                    payoff, exercise);
        option.setPricingEngine(engine);
        Real calculated = option.NPV();
        Real error = std::fabs(calculated-values[i].result);
        Real tolerance = 1e-4;
        if (error>tolerance) {
            REPORT_FAILURE("value", payoff, exercise, values[i].s,
                           values[i].q, values[i].r, today,
                           values[i].v, values[i].moneyness, reset,
                           values[i].result, calculated,
                           error, tolerance);
        }
    }
}
void ForwardOptionTest::testValues () [static]
Definition at line 73 of file forwardoption.cpp.
References QuantLib::Option::Call, QuantLib::flatRate(), QuantLib::flatVol(), LENGTH, QuantLib::Instrument::NPV(), QuantLib::Option::Put, REPORT_FAILURE, anonymous_namespace{inflationvolatility.cpp}::reset(), QuantLib::Instrument::setPricingEngine(), anonymous_namespace{quantlibbenchmark.cpp}::t, anonymous_namespace{marketmodel.cpp}::todaysDate, anonymous_namespace{gaussianquadratures.cpp}::tolerance, and anonymous_namespace{perturbativebarrieroptionengine.cpp}::v().
Referenced by suite().
{
    BOOST_MESSAGE("Testing forward option values...");
    /* The data below are from
       "Option pricing formulas", E.G. Haug, McGraw-Hill 1998
    */
    ForwardOptionData values[] = {
        //  type, moneyness, spot,  div, rate,start,   t,  vol, result, tol
        // "Option pricing formulas", pag. 37
        { Option::Call, 1.1, 60.0, 0.04, 0.08, 0.25, 1.0, 0.30, 4.4064, 1.0e-4 },
        // "Option pricing formulas", VBA code
        {  Option::Put, 1.1, 60.0, 0.04, 0.08, 0.25, 1.0, 0.30, 8.2971, 1.0e-4 }
    };
    DayCounter dc = Actual360();
    Date today = Date::todaysDate();
    boost::shared_ptr<SimpleQuote> spot(new SimpleQuote(0.0));
    boost::shared_ptr<SimpleQuote> qRate(new SimpleQuote(0.0));
    Handle<YieldTermStructure> qTS(flatRate(today, qRate, dc));
    boost::shared_ptr<SimpleQuote> rRate(new SimpleQuote(0.0));
    Handle<YieldTermStructure> rTS(flatRate(today, rRate, dc));
    boost::shared_ptr<SimpleQuote> vol(new SimpleQuote(0.0));
    Handle<BlackVolTermStructure> volTS(flatVol(today, vol, dc));
    boost::shared_ptr<BlackScholesMertonProcess> stochProcess(
         new BlackScholesMertonProcess(Handle<Quote>(spot),
                                       Handle<YieldTermStructure>(qTS),
                                       Handle<YieldTermStructure>(rTS),
                                       Handle<BlackVolTermStructure>(volTS)));
    boost::shared_ptr<PricingEngine> engine(
              new ForwardVanillaEngine<AnalyticEuropeanEngine>(stochProcess));
    for (Size i=0; i<LENGTH(values); i++) {
        boost::shared_ptr<StrikedTypePayoff> payoff(
                                 new PlainVanillaPayoff(values[i].type, 0.0));
        Date exDate = today + Integer(values[i].t*360+0.5);
        boost::shared_ptr<Exercise> exercise(new EuropeanExercise(exDate));
        Date reset = today + Integer(values[i].start*360+0.5);
        spot ->setValue(values[i].s);
        qRate->setValue(values[i].q);
        rRate->setValue(values[i].r);
        vol  ->setValue(values[i].v);
        ForwardVanillaOption option(values[i].moneyness, reset,
                                    payoff, exercise);
        option.setPricingEngine(engine);
        Real calculated = option.NPV();
        Real error = std::fabs(calculated-values[i].result);
        Real tolerance = 1e-4;
        if (error>tolerance) {
            REPORT_FAILURE("value", payoff, exercise, values[i].s,
                           values[i].q, values[i].r, today,
                           values[i].v, values[i].moneyness, reset,
                           values[i].result, calculated,
                           error, tolerance);
        }
    }
}
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/forwardoption.hpp
/home/deriversatile/QuantLib/QuantLibQt/test-suite/forwardoption.cpp