QuantLib: QuantLib::MCPagodaEngine< RNG, S > Class Template Reference
QuantLib::MCPagodaEngine< RNG, S > Class Template Reference
Pricing engine for pagoda options using Monte Carlo simulation.
#include <mcpagodaengine.hpp>
Public Types
typedef McSimulation
< MultiVariate, RNG, S >
::path_generator_type path_generator_type
typedef McSimulation
< MultiVariate, RNG, S >
::path_pricer_type path_pricer_type
typedef McSimulation
< MultiVariate, RNG, S >
::stats_type stats_type
Public Member Functions
MCPagodaEngine (const boost::shared_ptr< StochasticProcessArray > &, bool brownianBridge, bool antitheticVariate, Size requiredSamples, Real requiredTolerance, Size maxSamples, BigNatural seed)
void calculate () const
Private Member Functions
TimeGrid timeGrid () const
boost::shared_ptr
< path_generator_type > pathGenerator () const
boost::shared_ptr
< path_pricer_type > pathPricer () const
Private Attributes
boost::shared_ptr
< StochasticProcessArray > processes_
Size requiredSamples_
Size maxSamples_
Real requiredTolerance_
bool brownianBridge_
BigNatural seed_
Detailed Description
template<class RNG = PseudoRandom, class S = Statistics>
class QuantLib::MCPagodaEngine< RNG, S >
Pricing engine for pagoda options using Monte Carlo simulation.
Definition at line 37 of file mcpagodaengine.hpp.
Member Typedef Documentation
template<class RNG = PseudoRandom, class S = Statistics> typedef McSimulation<MultiVariate,RNG,S>::path_generator_type QuantLib::MCPagodaEngine< RNG, S >::path_generator_type
Reimplemented from QuantLib::McSimulation< MultiVariate, RNG, S >.
Definition at line 41 of file mcpagodaengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> typedef McSimulation<MultiVariate,RNG,S>::path_pricer_type QuantLib::MCPagodaEngine< RNG, S >::path_pricer_type
Reimplemented from QuantLib::McSimulation< MultiVariate, RNG, S >.
Definition at line 43 of file mcpagodaengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> typedef McSimulation<MultiVariate,RNG,S>::stats_type QuantLib::MCPagodaEngine< RNG, S >::stats_type
Reimplemented from QuantLib::McSimulation< MultiVariate, RNG, S >.
Definition at line 45 of file mcpagodaengine.hpp.
Constructor & Destructor Documentation
template<class RNG , class S > QuantLib::MCPagodaEngine< RNG, S >::MCPagodaEngine (const boost::shared_ptr< StochasticProcessArray > & processes, bool brownianBridge, bool antitheticVariate, Size requiredSamples, Real requiredTolerance, Size maxSamples, BigNatural seed) [inline]
Definition at line 127 of file mcpagodaengine.hpp.
References QuantLib::MCPagodaEngine< RNG, S >::processes_, and QuantLib::Observer::registerWith().
    : McSimulation<MultiVariate,RNG,S>(antitheticVariate, false),
      processes_(processes), requiredSamples_(requiredSamples),
      maxSamples_(maxSamples), requiredTolerance_(requiredTolerance),
      brownianBridge_(brownianBridge), seed_(seed) {
        registerWith(processes_);
    }
Member Function Documentation
template<class RNG = PseudoRandom, class S = Statistics> void QuantLib::MCPagodaEngine< RNG, S >::calculate () const [inline, virtual]
Implements QuantLib::PricingEngine.
Definition at line 54 of file mcpagodaengine.hpp.
References QuantLib::Instrument::results::errorEstimate, QuantLib::MCPagodaEngine< RNG, S >::maxSamples_, QuantLib::McSimulation< MultiVariate, RNG, S >::mcModel_, QuantLib::MCPagodaEngine< RNG, S >::requiredSamples_, QuantLib::MCPagodaEngine< RNG, S >::requiredTolerance_, QuantLib::GenericEngine< PagodaOption::arguments, PagodaOption::results >::results_, and QuantLib::Instrument::results::value.
{
            McSimulation<MultiVariate,RNG,S>::calculate(requiredTolerance_,
                                                        requiredSamples_,
                                                        maxSamples_);
            results_.value = this->mcModel_->sampleAccumulator().mean();
            if (RNG::allowsErrorEstimate)
                results_.errorEstimate =
                    this->mcModel_->sampleAccumulator().errorEstimate();
        }
template<class RNG = PseudoRandom, class S = Statistics> boost::shared_ptr<path_generator_type> QuantLib::MCPagodaEngine< RNG, S >::pathGenerator () const [inline, private, virtual]
Implements QuantLib::McSimulation< MultiVariate, RNG, S >.
Definition at line 66 of file mcpagodaengine.hpp.
References QuantLib::MCPagodaEngine< RNG, S >::brownianBridge_, QuantLib::MCPagodaEngine< RNG, S >::processes_, QuantLib::MCPagodaEngine< RNG, S >::seed_, QuantLib::TimeGrid::size(), and QuantLib::MCPagodaEngine< RNG, S >::timeGrid().
{
            Size numAssets = processes_->size();
            TimeGrid grid = timeGrid();
            typename RNG::rsg_type gen =
                RNG::make_sequence_generator(numAssets*(grid.size()-1),seed_);
            return boost::shared_ptr<path_generator_type>(
                         new path_generator_type(processes_,
                                                 grid, gen, brownianBridge_));
        }
template<class RNG , class S > boost::shared_ptr< typename MCPagodaEngine< RNG, S >::path_pricer_type > QuantLib::MCPagodaEngine< RNG, S >::pathPricer () const [inline, private, virtual]
Implements QuantLib::McSimulation< MultiVariate, RNG, S >.
Definition at line 162 of file mcpagodaengine.hpp.
References QL_REQUIRE.
{
        boost::shared_ptr<GeneralizedBlackScholesProcess> process =
            boost::dynamic_pointer_cast<GeneralizedBlackScholesProcess>(
                                                      processes_->process(0));
        QL_REQUIRE(process, "Black-Scholes process required");
        return boost::shared_ptr<
                         typename MCPagodaEngine<RNG,S>::path_pricer_type>(
            new PagodaMultiPathPricer(arguments_.roof, arguments_.fraction,
                                      process->riskFreeRate()->discount(
                                           arguments_.exercise->lastDate())));
    }
template<class RNG , class S > TimeGrid QuantLib::MCPagodaEngine< RNG, S >::timeGrid () const [inline, private, virtual]
Implements QuantLib::McSimulation< MultiVariate, RNG, S >.
Definition at line 143 of file mcpagodaengine.hpp.
References QL_REQUIRE, and anonymous_namespace{quantlibbenchmark.cpp}::t.
Referenced by QuantLib::MCPagodaEngine< RNG, S >::pathGenerator().
{
        std::vector<Time> fixingTimes;
        for (Size i=0; i<arguments_.fixingDates.size(); i++) {
            Time t = processes_->time(arguments_.fixingDates[i]);
            QL_REQUIRE(t >= 0.0, "seasoned options are not handled");
            if (i > 0) {
                QL_REQUIRE(t > fixingTimes.back(), "fixing dates not sorted");
            }
            fixingTimes.push_back(t);
        }
        return TimeGrid(fixingTimes.begin(), fixingTimes.end());
    }
Member Data Documentation
template<class RNG = PseudoRandom, class S = Statistics> bool QuantLib::MCPagodaEngine< RNG, S >::brownianBridge_ [private]
Definition at line 85 of file mcpagodaengine.hpp.
Referenced by QuantLib::MCPagodaEngine< RNG, S >::pathGenerator().
template<class RNG = PseudoRandom, class S = Statistics> Size QuantLib::MCPagodaEngine< RNG, S >::maxSamples_ [private]
Definition at line 83 of file mcpagodaengine.hpp.
Referenced by QuantLib::MCPagodaEngine< RNG, S >::calculate().
template<class RNG = PseudoRandom, class S = Statistics> boost::shared_ptr<StochasticProcessArray> QuantLib::MCPagodaEngine< RNG, S >::processes_ [private]
Definition at line 81 of file mcpagodaengine.hpp.
Referenced by QuantLib::MCPagodaEngine< RNG, S >::MCPagodaEngine(), and QuantLib::MCPagodaEngine< RNG, S >::pathGenerator().
template<class RNG = PseudoRandom, class S = Statistics> Size QuantLib::MCPagodaEngine< RNG, S >::requiredSamples_ [private]
Definition at line 82 of file mcpagodaengine.hpp.
Referenced by QuantLib::MCPagodaEngine< RNG, S >::calculate().
template<class RNG = PseudoRandom, class S = Statistics> Real QuantLib::MCPagodaEngine< RNG, S >::requiredTolerance_ [private]
Definition at line 84 of file mcpagodaengine.hpp.
Referenced by QuantLib::MCPagodaEngine< RNG, S >::calculate().
template<class RNG = PseudoRandom, class S = Statistics> BigNatural QuantLib::MCPagodaEngine< RNG, S >::seed_ [private]
Definition at line 86 of file mcpagodaengine.hpp.
Referenced by QuantLib::MCPagodaEngine< RNG, S >::pathGenerator().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/exoticoptions/mcpagodaengine.hpp