QuantLib: QuantLib::MidPointCDOEngine Class Reference
QuantLib::MidPointCDOEngine Class Reference
CDO base engine taking schedule steps.
#include <syntheticcdoengines.hpp>
Public Member Functions
MidPointCDOEngine ()
void calculate () const
Private Member Functions
virtual Real expectedTrancheLoss (const Date &) const =0
Detailed Description
CDO base engine taking schedule steps.
Definition at line 82 of file syntheticcdoengines.hpp.
Constructor & Destructor Documentation
QuantLib::MidPointCDOEngine::MidPointCDOEngine () [inline]
Definition at line 84 of file syntheticcdoengines.hpp.
{}
Member Function Documentation
void QuantLib::MidPointCDOEngine::calculate () const [virtual]
Implements QuantLib::PricingEngine.
Definition at line 99 of file syntheticcdoengines.cpp.
References anonymous_namespace{marketmodel.cpp}::dates, anonymous_namespace{marketmodel.cpp}::endDate, anonymous_namespace{marketmodel.cpp}::startDate, QuantLib::FixedRateLeg::withCouponRates(), QuantLib::FixedRateLeg::withNotionals(), and QuantLib::FixedRateLeg::withPaymentAdjustment().
{
        Date today = Settings::instance().evaluationDate();
        results_.premiumValue = 0.0;
        results_.upfrontPremiumValue = 0.0;
        results_.protectionValue = 0.0;
        results_.expectedTrancheLoss.clear();
        // set remainingBasket_, results_.remainingNotional,
        // vector results_.expectedTrancheLoss for all schedule dates
        initialize();
        const vector<Date>& dates = arguments_.schedule.dates();
        if (dates.front() > today)
            results_.upfrontPremiumValue =
                arguments_.upfrontRate * results_.remainingNotional;
        vector<boost::shared_ptr<CashFlow> > premiumLeg =
            FixedRateLeg(arguments_.schedule)
            .withCouponRates(arguments_.runningRate, arguments_.dayCounter)
            .withPaymentAdjustment(arguments_.paymentConvention)
            .withNotionals(1.0);
        Real e1 = 0;
        if (dates[0] > today)
            e1 = expectedTrancheLoss (dates[0]);
        for (Size i = 0; i < premiumLeg.size(); i++) {
            boost::shared_ptr<Coupon> coupon =
                boost::dynamic_pointer_cast<Coupon>(premiumLeg[i]);
            Date paymentDate = coupon->date();
            Date startDate = std::max(coupon->accrualStartDate(),
                                      arguments_.yieldTS->referenceDate());
            Date endDate = coupon->accrualEndDate();
            Date defaultDate = startDate + (endDate-startDate)/2;
            if (paymentDate <= today)
                continue;
            Real e2 = expectedTrancheLoss(paymentDate);
            results_.premiumValue += (results_.remainingNotional - e2)
                * coupon->amount()
                * arguments_.yieldTS->discount(paymentDate);
            Real discount = arguments_.yieldTS->discount(defaultDate);
            results_.premiumValue += coupon->accruedAmount(defaultDate)
                * discount * (e2 - e1);
            results_.protectionValue += discount * (e2 - e1);
            e1 = e2;
        }
        if (arguments_.side == Protection::Buyer) {
            results_.protectionValue *= -1;
            results_.premiumValue *= -1;
            results_.upfrontPremiumValue *= -1;
        }
        results_.value = results_.premiumValue - results_.protectionValue
            + results_.upfrontPremiumValue;
        results_.errorEstimate = Null<Real>();
    }
virtual Real QuantLib::MidPointCDOEngine::expectedTrancheLoss (const Date &) const [private, pure virtual]
Implements QuantLib::SyntheticCDO::engine.
Implemented in QuantLib::MonteCarloCDOEngine1.
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/syntheticcdoengines.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/syntheticcdoengines.cpp