QuantLib: QuantLib::ExchangeRate Class Reference
QuantLib::ExchangeRate Class Reference
exchange rate between two currencies
#include <exchangerate.hpp>
Public Types
enum Type { Direct, Derived }
Public Member Functions
Constructors
ExchangeRate ()
ExchangeRate (const Currency &source, const Currency &target, Decimal rate)
Inspectors
const Currency & source () const
the source currency.
const Currency & target () const
the target currency.
Type type () const
the type
Decimal rate () const
the exchange rate (when available)
Private Attributes
Currency source_
Currency target_
Decimal rate_
Type type_
std::pair< boost::shared_ptr
< ExchangeRate >
, boost::shared_ptr
< ExchangeRate > > rateChain_
Utility methods
Money exchange (const Money &amount) const
apply the exchange rate to a cash amount
static ExchangeRate chain (const ExchangeRate &r1, const ExchangeRate &r2)
chain two exchange rates
Detailed Description
exchange rate between two currencies
Test:
application of direct and derived exchange rate is tested against calculations.
Definition at line 38 of file exchangerate.hpp.
Member Enumeration Documentation
enum QuantLib::ExchangeRate::Type
Enumerator:
Direct
given directly by the user
Derived
derived from exchange rates between other currencies
Definition at line 40 of file exchangerate.hpp.
                  { Direct,
                    Derived
        };
Constructor & Destructor Documentation
QuantLib::ExchangeRate::ExchangeRate () [inline]
Definition at line 86 of file exchangerate.hpp.
Referenced by chain().
    : rate_(Null<Decimal>()) {}
QuantLib::ExchangeRate::ExchangeRate (const Currency & source, const Currency & target, Decimal rate) [inline]
the rate \(r \) is given with the convention that a unit of the source is worth \(r \) units of the target.
Definition at line 89 of file exchangerate.hpp.
    : source_(source), target_(target), rate_(rate), type_(Direct) {}
Member Function Documentation
ExchangeRate QuantLib::ExchangeRate::chain (const ExchangeRate & r1, const ExchangeRate & r2) [static]
chain two exchange rates
Definition at line 50 of file exchangerate.cpp.
References Derived, ExchangeRate(), QL_FAIL, rate_, rateChain_, source_, target_, and type_.
Referenced by QuantLib::ExchangeRateManager::lookup(), QuantLib::ExchangeRateManager::smartLookup(), and ExchangeRateTest::testDerived().
{
        ExchangeRate result;
        result.type_ = Derived;
        result.rateChain_ = std::make_pair(
                       boost::shared_ptr<ExchangeRate>(new ExchangeRate(r1)),
                       boost::shared_ptr<ExchangeRate>(new ExchangeRate(r2)));
        if (r1.source_ == r2.source_) {
            result.source_ = r1.target_;
            result.target_ = r2.target_;
            result.rate_ = r2.rate_/r1.rate_;
        } else if (r1.source_ == r2.target_) {
            result.source_ = r1.target_;
            result.target_ = r2.source_;
            result.rate_ = 1.0/(r1.rate_*r2.rate_);
        } else if (r1.target_ == r2.source_) {
            result.source_ = r1.source_;
            result.target_ = r2.target_;
            result.rate_ = r1.rate_*r2.rate_;
        } else if (r1.target_ == r2.target_) {
            result.source_ = r1.source_;
            result.target_ = r2.source_;
            result.rate_ = r1.rate_/r2.rate_;
        } else {
            QL_FAIL("exchange rates not chainable");
        }
        return result;
    }
Money QuantLib::ExchangeRate::exchange (const Money & amount) const
apply the exchange rate to a cash amount
Definition at line 25 of file exchangerate.cpp.
References QuantLib::Money::currency(), Derived, Direct, QL_FAIL, rate_, rateChain_, source_, target_, type_, and QuantLib::Money::value().
Referenced by QuantLib::anonymous_namespace{money.cpp}::convertTo(), ExchangeRateTest::testDerived(), ExchangeRateTest::testDirect(), ExchangeRateTest::testDirectLookup(), ExchangeRateTest::testSmartLookup(), and ExchangeRateTest::testTriangulatedLookup().
{
        switch (type_) {
          case Direct:
            if (amount.currency() == source_)
                return Money(amount.value()*rate_, target_);
            else if (amount.currency() == target_)
                return Money(amount.value()/rate_, source_);
            else
                QL_FAIL("exchange rate not applicable");
          case Derived:
            if (amount.currency() == rateChain_.first->source() ||
                amount.currency() == rateChain_.first->target())
                return rateChain_.second->exchange(
                                         rateChain_.first->exchange(amount));
            else if (amount.currency() == rateChain_.second->source() ||
                       amount.currency() == rateChain_.second->target())
                return rateChain_.first->exchange(
                                         rateChain_.second->exchange(amount));
            else
                QL_FAIL("exchange rate not applicable");
          default:
            QL_FAIL("unknown exchange-rate type");
        }
    }
Decimal QuantLib::ExchangeRate::rate () const [inline]
the exchange rate (when available)
Definition at line 106 of file exchangerate.hpp.
References rate_.
Referenced by QuantLib::CommodityPricingHelper::calculateFxConversionFactor(), QuantLib::EnergyCommodity::calculateFxConversionFactor(), MoneyTest::testAutomated(), MoneyTest::testBaseCurrency(), ExchangeRateTest::testDerived(), ExchangeRateTest::testDirect(), ExchangeRateTest::testDirectLookup(), ExchangeRateTest::testSmartLookup(), and ExchangeRateTest::testTriangulatedLookup().
{
        return rate_;
    }
const Currency & QuantLib::ExchangeRate::source () const [inline]
the source currency.
Definition at line 94 of file exchangerate.hpp.
References source_.
Referenced by QuantLib::ExchangeRateManager::add(), QuantLib::CommodityPricingHelper::calculateFxConversionFactor(), and QuantLib::ExchangeRateManager::smartLookup().
{
        return source_;
    }
const Currency & QuantLib::ExchangeRate::target () const [inline]
the target currency.
Definition at line 98 of file exchangerate.hpp.
References target_.
Referenced by QuantLib::ExchangeRateManager::add(), QuantLib::EnergyCommodity::calculateFxConversionFactor(), and QuantLib::ExchangeRateManager::smartLookup().
{
        return target_;
    }
ExchangeRate::Type QuantLib::ExchangeRate::type () const [inline]
the type
Definition at line 102 of file exchangerate.hpp.
References type_.
{
        return type_;
    }
Member Data Documentation
Decimal QuantLib::ExchangeRate::rate_ [private]
Definition at line 77 of file exchangerate.hpp.
Referenced by chain(), exchange(), and rate().
std::pair<boost::shared_ptr<ExchangeRate>, boost::shared_ptr<ExchangeRate> > QuantLib::ExchangeRate::rateChain_ [private]
Definition at line 80 of file exchangerate.hpp.
Referenced by chain(), and exchange().
Currency QuantLib::ExchangeRate::source_ [private]
Definition at line 76 of file exchangerate.hpp.
Referenced by chain(), exchange(), and source().
Currency QuantLib::ExchangeRate::target_ [private]
Definition at line 76 of file exchangerate.hpp.
Referenced by chain(), exchange(), and target().
Type QuantLib::ExchangeRate::type_ [private]
Definition at line 78 of file exchangerate.hpp.
Referenced by chain(), exchange(), and type().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/exchangerate.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/exchangerate.cpp