QuantLib: QuantLib::MarketModelPathwiseMultiCaplet Class Reference
QuantLib::MarketModelPathwiseMultiCaplet Class Reference
market-model pathwise caplet
#include <pathwiseproductcaplet.hpp>
Public Member Functions
MarketModelPathwiseMultiCaplet (const std::vector< Time > &rateTimes, const std::vector< Real > &accruals, const std::vector< Time > &paymentTimes, const std::vector< Rate > &strikes)
virtual ~MarketModelPathwiseMultiCaplet ()
virtual std::vector< Size > suggestedNumeraires () const
virtual const
EvolutionDescription & evolution () const
virtual std::vector< Time > possibleCashFlowTimes () const
virtual Size numberOfProducts () const
virtual Size maxNumberOfCashFlowsPerProductPerStep () const
virtual bool alreadyDeflated () const
virtual void reset ()
during simulation put product at start of path
virtual bool nextTimeStep (const CurveState &currentState, std::vector< Size > &numberCashFlowsThisStep, std::vector< std::vector< MarketModelPathwiseMultiProduct::CashFlow > > &cashFlowsGenerated)
return value indicates whether path is finished, TRUE means done
virtual std::auto_ptr
< MarketModelPathwiseMultiProduct > clone () const
returns a newly-allocated copy of itself
Private Attributes
std::vector< Real > rateTimes_
std::vector< Real > accruals_
std::vector< Time > paymentTimes_
std::vector< Rate > strikes_
Size numberRates_
Size currentIndex_
EvolutionDescription evolution_
Detailed Description
market-model pathwise caplet
implementation of path wise methodology for caplets, essentially a test class since we have better ways of computing Greeks of caplets
used in MarketModelTest::testPathwiseVegas and MarketModelTest::testPathwiseGreeks
Definition at line 44 of file pathwiseproductcaplet.hpp.
Constructor & Destructor Documentation
QuantLib::MarketModelPathwiseMultiCaplet::MarketModelPathwiseMultiCaplet (const std::vector< Time > & rateTimes, const std::vector< Real > & accruals, const std::vector< Time > & paymentTimes, const std::vector< Rate > & strikes)
Definition at line 35 of file pathwiseproductcaplet.cpp.
References QuantLib::checkIncreasingTimes(), evolution_, numberRates_, QL_REQUIRE, and rateTimes_.
Referenced by clone().
        : rateTimes_(rateTimes),
        accruals_(accruals),
        paymentTimes_(paymentTimes),
        strikes_(strikes) ,
        numberRates_(accruals_.size())
    {
        checkIncreasingTimes(rateTimes);
        checkIncreasingTimes(paymentTimes);
        std::vector<Time> evolTimes(rateTimes_);
        evolTimes.pop_back();
        QL_REQUIRE(evolTimes.size()==numberRates_,
            "rateTimes.size()<> numberOfRates+1");
        QL_REQUIRE(paymentTimes.size()==numberRates_,
            "paymentTimes.size()<> numberOfRates");
        QL_REQUIRE(accruals.size()==numberRates_,
            "accruals.size()<> numberOfRates");
        QL_REQUIRE(strikes.size()==numberRates_,
            "strikes.size()<> numberOfRates");
        evolution_ = EvolutionDescription(rateTimes,evolTimes);
    }
virtual QuantLib::MarketModelPathwiseMultiCaplet::~MarketModelPathwiseMultiCaplet () [inline, virtual]
Definition at line 54 of file pathwiseproductcaplet.hpp.
{}
Member Function Documentation
bool QuantLib::MarketModelPathwiseMultiCaplet::alreadyDeflated () const [virtual]
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 30 of file pathwiseproductcaplet.cpp.
    {
        return false;
    }
std::auto_ptr< MarketModelPathwiseMultiProduct > QuantLib::MarketModelPathwiseMultiCaplet::clone () const [virtual]
returns a newly-allocated copy of itself
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 95 of file pathwiseproductcaplet.cpp.
References MarketModelPathwiseMultiCaplet().
Referenced by MarketModelTest::testPathwiseGreeks(), and MarketModelTest::testPathwiseVegas().
    {
        return std::auto_ptr<MarketModelPathwiseMultiProduct>(
            new MarketModelPathwiseMultiCaplet(*this));
    }
const EvolutionDescription & QuantLib::MarketModelPathwiseMultiCaplet::evolution () const [virtual]
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 110 of file pathwiseproductcaplet.cpp.
References evolution_.
    {
        return evolution_;
    }
Size QuantLib::MarketModelPathwiseMultiCaplet::maxNumberOfCashFlowsPerProductPerStep () const [virtual]
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 125 of file pathwiseproductcaplet.cpp.
    {
        return 1;
    }
bool QuantLib::MarketModelPathwiseMultiCaplet::nextTimeStep (const CurveState & currentState, std::vector< Size > & numberCashFlowsThisStep, std::vector< std::vector< MarketModelPathwiseMultiProduct::CashFlow > > & cashFlowsGenerated) [virtual]
return value indicates whether path is finished, TRUE means done
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 70 of file pathwiseproductcaplet.cpp.
References accruals_, currentIndex_, QuantLib::CurveState::forwardRate(), numberRates_, and strikes_.
    {
        Rate liborRate = currentState.forwardRate(currentIndex_);
        cashFlowsGenerated[currentIndex_][0].timeIndex = currentIndex_;
        cashFlowsGenerated[currentIndex_][0].amount[0] =
            (liborRate-strikes_[currentIndex_])*accruals_[currentIndex_];
        std::fill(numberCashFlowsThisStep.begin(),
            numberCashFlowsThisStep.end(),0);
        if (  cashFlowsGenerated[currentIndex_][0].amount[0]  >0)
        {
            numberCashFlowsThisStep[currentIndex_] = 1;
            for (Size i=1; i <= numberRates_; ++i)
                cashFlowsGenerated[currentIndex_][0].amount[i] =0;
            cashFlowsGenerated[currentIndex_][0].amount[currentIndex_+1]  = accruals_[currentIndex_];
        }
        ++currentIndex_;
        return (currentIndex_ == strikes_.size());
    }
Size QuantLib::MarketModelPathwiseMultiCaplet::numberOfProducts () const [virtual]
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 120 of file pathwiseproductcaplet.cpp.
References numberRates_.
Referenced by MarketModelTest::testPathwiseVegas().
    {
        return numberRates_;
    }
std::vector< Time > QuantLib::MarketModelPathwiseMultiCaplet::possibleCashFlowTimes () const [virtual]
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 115 of file pathwiseproductcaplet.cpp.
References paymentTimes_.
    {
        return paymentTimes_;
    }
void QuantLib::MarketModelPathwiseMultiCaplet::reset () [virtual]
during simulation put product at start of path
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 131 of file pathwiseproductcaplet.cpp.
References currentIndex_.
    {
        currentIndex_=0;
    }
std::vector< Size > QuantLib::MarketModelPathwiseMultiCaplet::suggestedNumeraires () const [virtual]
Implements QuantLib::MarketModelPathwiseMultiProduct.
Definition at line 101 of file pathwiseproductcaplet.cpp.
References numberRates_.
    {
        std::vector<Size> numeraires(numberRates_);
        for (Size i=0; i < numberRates_; ++i)
            numeraires[i] = i+1;
        return numeraires;
    }
Member Data Documentation
std::vector<Real> QuantLib::MarketModelPathwiseMultiCaplet::accruals_ [private]
Definition at line 81 of file pathwiseproductcaplet.hpp.
Referenced by nextTimeStep().
Size QuantLib::MarketModelPathwiseMultiCaplet::currentIndex_ [private]
Definition at line 86 of file pathwiseproductcaplet.hpp.
Referenced by nextTimeStep(), and reset().
EvolutionDescription QuantLib::MarketModelPathwiseMultiCaplet::evolution_ [private]
Definition at line 88 of file pathwiseproductcaplet.hpp.
Referenced by evolution(), and MarketModelPathwiseMultiCaplet().
Size QuantLib::MarketModelPathwiseMultiCaplet::numberRates_ [private]
Definition at line 84 of file pathwiseproductcaplet.hpp.
Referenced by MarketModelPathwiseMultiCaplet(), nextTimeStep(), numberOfProducts(), and suggestedNumeraires().
std::vector<Time> QuantLib::MarketModelPathwiseMultiCaplet::paymentTimes_ [private]
Definition at line 82 of file pathwiseproductcaplet.hpp.
Referenced by possibleCashFlowTimes().
std::vector<Real> QuantLib::MarketModelPathwiseMultiCaplet::rateTimes_ [private]
Definition at line 80 of file pathwiseproductcaplet.hpp.
Referenced by MarketModelPathwiseMultiCaplet().
std::vector<Rate> QuantLib::MarketModelPathwiseMultiCaplet::strikes_ [private]
Definition at line 83 of file pathwiseproductcaplet.hpp.
Referenced by nextTimeStep().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/products/pathwise/pathwiseproductcaplet.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/products/pathwise/pathwiseproductcaplet.cpp