QuantLib: QuantLib::GeneralLinearLeastSquares Class Reference
QuantLib::GeneralLinearLeastSquares Class Reference
general linear least squares regression
#include <generallinearleastsquares.hpp>
Public Member Functions
template<class xContainer , class yContainer , class vContainer >
GeneralLinearLeastSquares (const xContainer &x, const yContainer &y, const vContainer &v)
template<class xIterator , class yIterator , class vIterator >
GeneralLinearLeastSquares (xIterator xBegin, xIterator xEnd, yIterator yBegin, yIterator yEnd, vIterator vBegin, vIterator vEnd)
const Array & coefficients () const
const Array & residuals () const
const Array & standardErrors () const
standard parameter errors as given by Excel, R etc.
const Array & error () const
modeling uncertainty as definied in Numerical Recipes
const Array & a () const
Size size () const
Size dim () const
Protected Member Functions
template<class xIterator , class yIterator , class vIterator >
void calculate (xIterator xBegin, xIterator xEnd, yIterator yBegin, yIterator yEnd, vIterator vBegin, vIterator vEnd)
Protected Attributes
Array a_
Array err_
Array residuals_
Array standardErrors_
Detailed Description
general linear least squares regression
References: "Numerical Recipes in C", 2nd edition, Press, Teukolsky, Vetterling, Flannery,
Test:
the correctness of the returned values is tested by checking their properties.
Definition at line 48 of file generallinearleastsquares.hpp.
Constructor & Destructor Documentation
template<class xContainer , class yContainer , class vContainer > QuantLib::GeneralLinearLeastSquares::GeneralLinearLeastSquares (const xContainer & x, const yContainer & y, const vContainer & v) [inline]
Definition at line 85 of file generallinearleastsquares.hpp.
References calculate().
    : a_(v.size(), 0.0),
      err_(v.size(), 0.0),
      residuals_(y.size()),
      standardErrors_(v.size()) {
        calculate(x.begin(), x.end(), y.begin(), y.end(), v.begin(), v.end());
    }
template<class xIterator , class yIterator , class vIterator > QuantLib::GeneralLinearLeastSquares::GeneralLinearLeastSquares (xIterator xBegin, xIterator xEnd, yIterator yBegin, yIterator yEnd, vIterator vBegin, vIterator vEnd) [inline]
Definition at line 96 of file generallinearleastsquares.hpp.
References calculate().
    : a_(std::distance(vBegin, vEnd), 0.0),
      err_(a_.size(), 0.0),
      residuals_(std::distance(yBegin, yEnd)),
      standardErrors_(a_.size()) {
        calculate(xBegin, xEnd, yBegin, yEnd, vBegin, vEnd);
    }
Member Function Documentation
const Array& QuantLib::GeneralLinearLeastSquares::a () const [inline]
Definition at line 68 of file generallinearleastsquares.hpp.
References a_.
{ return a_;  }
template<class xIterator , class yIterator , class vIterator > void QuantLib::GeneralLinearLeastSquares::calculate (xIterator xBegin, xIterator xEnd, yIterator yBegin, yIterator yEnd, vIterator vBegin, vIterator vEnd) [protected]
Definition at line 109 of file generallinearleastsquares.hpp.
References a_, QuantLib::Array::begin(), QuantLib::Matrix::column_begin(), QuantLib::Matrix::column_end(), QuantLib::Array::end(), err_, QuantLib::dsd::inner_product(), QL_EPSILON, QL_REQUIRE, residuals_, QuantLib::SVD::singularValues(), QuantLib::Array::size(), QuantLib::Sqrt(), standardErrors_, QuantLib::SVD::U(), and QuantLib::SVD::V().
Referenced by GeneralLinearLeastSquares().
{
        const Size n = residuals_.size();
        const Size m = err_.size();
        QL_REQUIRE( n == Size(std::distance(yBegin, yEnd)),
            "sample set need to be of the same size");
        QL_REQUIRE(n >= m, "sample set is too small");
        Size i;
        Matrix A(n, m);
        for (i=0; i<m; ++i)
            std::transform(xBegin, xEnd, A.column_begin(i), *vBegin++);
        const SVD svd(A);
        const Matrix& V = svd.V();
        const Matrix& U = svd.U();
        const Array& w = svd.singularValues();
        const Real threshold = n*QL_EPSILON;
        for (i=0; i<m; ++i) {
            if (w[i] > threshold) {
                const Real u = std::inner_product(U.column_begin(i),
                    U.column_end(i),
                    yBegin, 0.0)/w[i];
                for (Size j=0; j<m; ++j) {
                    a_[j]  +=u*V[j][i];
                    err_[j]+=V[j][i]*V[j][i]/(w[i]*w[i]);
                }
            }
        }
        err_      = Sqrt(err_);
        Array tmp = A*a_;
        std::transform(tmp.begin(), tmp.end(),
                       yBegin, residuals_.begin(), std::minus<Real>());
        const Real chiSq
            = std::inner_product(residuals_.begin(), residuals_.end(),
            residuals_.begin(), 0.0);
        std::transform(err_.begin(), err_.end(), standardErrors_.begin(),
            std::bind1st(std::multiplies<Real>(),
            std::sqrt(chiSq/(n-2))));
    }
const Array& QuantLib::GeneralLinearLeastSquares::coefficients () const [inline]
Definition at line 59 of file generallinearleastsquares.hpp.
References a_.
Referenced by QuantLib::LongstaffSchwartzMultiPathPricer::calibrate(), QuantLib::LongstaffSchwartzPathPricer< PathType >::calibrate(), LinearLeastSquaresRegressionTest::test1dLinearRegression(), LinearLeastSquaresRegressionTest::testMultiDimRegression(), LinearLeastSquaresRegressionTest::testRegression(), and VPPTest::testVPPPricing().
{ return a_; }
Size QuantLib::GeneralLinearLeastSquares::dim () const [inline]
Definition at line 72 of file generallinearleastsquares.hpp.
References a_, and QuantLib::Array::size().
Referenced by LinearLeastSquaresRegressionTest::testMultiDimRegression().
{ return a_.size(); }
const Array& QuantLib::GeneralLinearLeastSquares::error () const [inline]
modeling uncertainty as definied in Numerical Recipes
Definition at line 65 of file generallinearleastsquares.hpp.
References err_.
{ return err_;}
const Array& QuantLib::GeneralLinearLeastSquares::residuals () const [inline]
Definition at line 60 of file generallinearleastsquares.hpp.
References residuals_.
{ return residuals_; }
Size QuantLib::GeneralLinearLeastSquares::size () const [inline]
Definition at line 70 of file generallinearleastsquares.hpp.
References residuals_, and QuantLib::Array::size().
{ return residuals_.size(); }
const Array& QuantLib::GeneralLinearLeastSquares::standardErrors () const [inline]
standard parameter errors as given by Excel, R etc.
Definition at line 63 of file generallinearleastsquares.hpp.
References standardErrors_.
Referenced by LinearLeastSquaresRegressionTest::test1dLinearRegression(), LinearLeastSquaresRegressionTest::testMultiDimRegression(), and LinearLeastSquaresRegressionTest::testRegression().
{ return standardErrors_; }
Member Data Documentation
Array QuantLib::GeneralLinearLeastSquares::a_ [protected]
Definition at line 75 of file generallinearleastsquares.hpp.
Referenced by a(), calculate(), coefficients(), and dim().
Array QuantLib::GeneralLinearLeastSquares::err_ [protected]
Definition at line 75 of file generallinearleastsquares.hpp.
Referenced by calculate(), and error().
Array QuantLib::GeneralLinearLeastSquares::residuals_ [protected]
Definition at line 75 of file generallinearleastsquares.hpp.
Referenced by calculate(), residuals(), and size().
Array QuantLib::GeneralLinearLeastSquares::standardErrors_ [protected]
Definition at line 75 of file generallinearleastsquares.hpp.
Referenced by calculate(), and standardErrors().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/generallinearleastsquares.hpp