QuantLib: QuantLib::LMMDriftCalculator Class Reference
QuantLib::LMMDriftCalculator Class Reference
Drift computation for log-normal Libor market models.
#include <lmmdriftcalculator.hpp>
Public Member Functions
LMMDriftCalculator (const Matrix &pseudo, const std::vector< Spread > &displacements, const std::vector< Time > &taus, Size numeraire, Size alive)
void compute (const LMMCurveState &cs, std::vector< Real > &drifts) const
Computes the drifts.
void compute (const std::vector< Rate > &fwds, std::vector< Real > &drifts) const
void computePlain (const LMMCurveState &cs, std::vector< Real > &drifts) const
void computePlain (const std::vector< Rate > &fwds, std::vector< Real > &drifts) const
void computeReduced (const LMMCurveState &cs, std::vector< Real > &drifts) const
void computeReduced (const std::vector< Rate > &fwds, std::vector< Real > &drifts) const
Private Attributes
Size numberOfRates_
Size numberOfFactors_
bool isFullFactor_
Size numeraire_
Size alive_
std::vector< Spread > displacements_
std::vector< Real > oneOverTaus_
Matrix C_
Matrix pseudo_
std::vector< Real > tmp_
Matrix e_
std::vector< Size > downs_
std::vector< Size > ups_
Detailed Description
Drift computation for log-normal Libor market models.
Returns the drift \(\mu \Delta t \). See Mark Joshi, Rapid Computation of Drifts in a Reduced Factor Libor Market Model, Wilmott Magazine, May 2003.
Definition at line 40 of file lmmdriftcalculator.hpp.
Constructor & Destructor Documentation
QuantLib::LMMDriftCalculator::LMMDriftCalculator (const Matrix & pseudo, const std::vector< Spread > & displacements, const std::vector< Time > & taus, Size numeraire, Size alive)
Definition at line 29 of file lmmdriftcalculator.cpp.
References alive_, C_, QuantLib::Matrix::columns(), downs_, numberOfRates_, numeraire_, oneOverTaus_, pseudo_, QL_REQUIRE, QuantLib::Matrix::rows(), QuantLib::transpose(), and ups_.
    : numberOfRates_(taus.size()), numberOfFactors_(pseudo.columns()),
      isFullFactor_(numberOfFactors_==numberOfRates_ ? true : false),
      numeraire_(numeraire), alive_(alive),
      displacements_(displacements), oneOverTaus_(taus.size()),
      pseudo_(pseudo), tmp_(taus.size(), 0.0),
      e_(pseudo_.columns(), pseudo_.rows(), 0.0),
      downs_(taus.size()), ups_(taus.size()) {
        // Check requirements
        QL_REQUIRE(numberOfRates_>0, "Dim out of range");
        QL_REQUIRE(displacements.size() == numberOfRates_,
            "Displacements out of range");
        QL_REQUIRE(pseudo.rows()==numberOfRates_,
            "pseudo.rows() not consistent with dim");
        QL_REQUIRE(pseudo.columns()>0 && pseudo.columns()<=numberOfRates_,
            "pseudo.rows() not consistent with pseudo.columns()");
        QL_REQUIRE(alive<numberOfRates_, "Alive out of bounds");
        QL_REQUIRE(numeraire_<=numberOfRates_, "Numeraire larger than dim");
        QL_REQUIRE(numeraire_>=alive, "Numeraire smaller than alive");
        // Precompute 1/taus
        for (Size i=0; i<taus.size(); ++i)
            oneOverTaus_[i] = 1.0/taus[i];
        // Compute covariance matrix from pseudoroot
        const Disposable<Matrix> pT = transpose(pseudo_);
        C_ = pseudo_*pT;
        // Compute lower and upper extrema for (non reduced) drift calculation
        for (Size i=alive_; i<numberOfRates_; ++i) {
            downs_[i] = std::min(i+1, numeraire_);
            ups_[i]   = std::max(i+1, numeraire_);
        }
    }
Member Function Documentation
void QuantLib::LMMDriftCalculator::compute (const LMMCurveState & cs, std::vector< Real > & drifts) const
Computes the drifts.
Definition at line 70 of file lmmdriftcalculator.cpp.
References QuantLib::LMMCurveState::forwardRates().
{
        compute(cs.forwardRates(), drifts);
    }
void QuantLib::LMMDriftCalculator::compute (const std::vector< Rate > & fwds, std::vector< Real > & drifts) const
Definition at line 75 of file lmmdriftcalculator.cpp.
References computePlain(), computeReduced(), isFullFactor_, numberOfRates_, and QL_REQUIRE.
{
        #if defined(QL_EXTRA_SAFETY_CHECKS)
            QL_REQUIRE(fwds.size()==numberOfRates_, "numberOfRates <> dim");
            QL_REQUIRE(drifts.size()==numberOfRates_, "drifts.size() <> dim");
        #endif
        if (isFullFactor_)
            computePlain(fwds, drifts);
        else
            computeReduced(fwds, drifts);
    }
void QuantLib::LMMDriftCalculator::computePlain (const LMMCurveState & cs, std::vector< Real > & drifts) const
Computes the drifts without factor reduction as in eqs. 2, 4 of ref. [1] (uses the covariance matrix directly).
Definition at line 88 of file lmmdriftcalculator.cpp.
References QuantLib::LMMCurveState::forwardRates().
Referenced by compute(), and MarketModelTest::testDriftCalculator().
{
        computePlain(cs.forwardRates(), drifts);
    }
void QuantLib::LMMDriftCalculator::computePlain (const std::vector< Rate > & fwds, std::vector< Real > & drifts) const
Definition at line 93 of file lmmdriftcalculator.cpp.
References alive_, C_, displacements_, downs_, QuantLib::dsd::inner_product(), numberOfRates_, numeraire_, oneOverTaus_, QuantLib::Matrix::row_begin(), tmp_, and ups_.
{
        // Compute drifts without factor reduction,
        // using directly the covariance matrix.
        // Precompute forwards factor
        Size i;
        for(i=alive_; i<numberOfRates_; ++i)
            tmp_[i] = (forwards[i]+displacements_[i]) /
                      (oneOverTaus_[i]+forwards[i]);
        // Compute drifts
        for (i=alive_; i<numberOfRates_; ++i) {
            drifts[i] = std::inner_product(tmp_.begin()+downs_[i],
                                           tmp_.begin()+ups_[i],
                                           C_.row_begin(i)+downs_[i], 0.0);
            if (numeraire_>i+1)
                drifts[i] = -drifts[i];
        }
    }
void QuantLib::LMMDriftCalculator::computeReduced (const LMMCurveState & cs, std::vector< Real > & drifts) const
Computes the drifts with factor reduction as in eq. 7 of ref. [1] (uses pseudo square root of the covariance matrix).
Definition at line 115 of file lmmdriftcalculator.cpp.
References QuantLib::LMMCurveState::forwardRates().
Referenced by compute(), and MarketModelTest::testDriftCalculator().
{
        computeReduced(cs.forwardRates(), drifts);
    }
void QuantLib::LMMDriftCalculator::computeReduced (const std::vector< Rate > & fwds, std::vector< Real > & drifts) const
Definition at line 120 of file lmmdriftcalculator.cpp.
References alive_, displacements_, e_, numberOfFactors_, numberOfRates_, numeraire_, oneOverTaus_, pseudo_, and tmp_.
{
        // Compute drifts with factor reduction,
        // using the pseudo square root of the covariance matrix.
        // Precompute forwards factor
        for (Size i=alive_; i<numberOfRates_; ++i)
            tmp_[i] = (forwards[i]+displacements_[i]) /
                (oneOverTaus_[i]+forwards[i]);
        // Enforce initialization
        for (Size r=0; r<numberOfFactors_; ++r)
            e_[r][std::max(0,static_cast<Integer>(numeraire_)-1)] = 0.0;
        // Now compute drifts: take the numeraire P_N (numeraire_=N)
        // as the reference point, divide the summation into 3 steps,
        // et impera:
        // 1st step: the drift corresponding to the numeraire P_N is zero.
        // (if N=0 no drift is null, if N=numberOfRates_ the last drift is null).
        if (numeraire_>0) drifts[numeraire_-1] = 0.0;
        // 2nd step: then, move backward from N-2 (included) back to
        // alive (included) (if N=0 jumps to 3rd step, if N=numberOfRates_ the
        // e_[r][N-1] are correctly initialized):
        for (Integer i=static_cast<Integer>(numeraire_)-2;
             i>=static_cast<Integer>(alive_); --i) {
            drifts[i] = 0.0;
            for (Size r=0; r<numberOfFactors_; ++r) {
                e_[r][i] = e_[r][i+1] + tmp_[i+1] * pseudo_[i+1][r];
                drifts[i] -= e_[r][i]*pseudo_[i][r];
            }
            /*
            Matrix::column_iterator p1 = e_.column_begin(i);
            Matrix::column_iterator end = e_.column_end(i);
            Matrix::const_column_iterator p2 = e_.column_begin(i+1);
            Matrix::const_row_iterator q1 = pseudo_.row_begin(i);
            Matrix::const_row_iterator q2 = pseudo_.row_begin(i+1);
            Real x = tmp_[i+1];
            while (p1 != end) {
                *p1 = *p2 + x*(*q2);
                drifts[i] -= *p1*(*q1);
                ++p1; ++p2; ++q1; ++q2;
            }
            */
        }
        // 3rd step: now, move forward from N (included) up to n (excluded)
        // (if N=0 this is the only relevant computation):
        for (Size i=numeraire_; i<numberOfRates_; ++i) {
            drifts[i] = 0.0;
            for (Size r=0; r<numberOfFactors_; ++r) {
                if (i==0)
                    e_[r][i] = tmp_[i] * pseudo_[i][r];
                else
                    e_[r][i] = e_[r][i-1] + tmp_[i] * pseudo_[i][r];
                drifts[i] += e_[r][i]*pseudo_[i][r];
            }
        }
    }
Member Data Documentation
Size QuantLib::LMMDriftCalculator::alive_ [private]
Definition at line 70 of file lmmdriftcalculator.hpp.
Referenced by computePlain(), computeReduced(), and LMMDriftCalculator().
Matrix QuantLib::LMMDriftCalculator::C_ [private]
Definition at line 73 of file lmmdriftcalculator.hpp.
Referenced by computePlain(), and LMMDriftCalculator().
std::vector<Spread> QuantLib::LMMDriftCalculator::displacements_ [private]
Definition at line 71 of file lmmdriftcalculator.hpp.
Referenced by computePlain(), and computeReduced().
std::vector<Size> QuantLib::LMMDriftCalculator::downs_ [private]
Definition at line 77 of file lmmdriftcalculator.hpp.
Referenced by computePlain(), and LMMDriftCalculator().
Matrix QuantLib::LMMDriftCalculator::e_ [mutable, private]
Definition at line 76 of file lmmdriftcalculator.hpp.
Referenced by computeReduced().
bool QuantLib::LMMDriftCalculator::isFullFactor_ [private]
Definition at line 69 of file lmmdriftcalculator.hpp.
Referenced by compute().
Size QuantLib::LMMDriftCalculator::numberOfFactors_ [private]
Definition at line 68 of file lmmdriftcalculator.hpp.
Referenced by computeReduced().
Size QuantLib::LMMDriftCalculator::numberOfRates_ [private]
Definition at line 68 of file lmmdriftcalculator.hpp.
Referenced by compute(), computePlain(), computeReduced(), and LMMDriftCalculator().
Size QuantLib::LMMDriftCalculator::numeraire_ [private]
Definition at line 70 of file lmmdriftcalculator.hpp.
Referenced by computePlain(), computeReduced(), and LMMDriftCalculator().
std::vector<Real> QuantLib::LMMDriftCalculator::oneOverTaus_ [private]
Definition at line 72 of file lmmdriftcalculator.hpp.
Referenced by computePlain(), computeReduced(), and LMMDriftCalculator().
Matrix QuantLib::LMMDriftCalculator::pseudo_ [private]
Definition at line 73 of file lmmdriftcalculator.hpp.
Referenced by computeReduced(), and LMMDriftCalculator().
std::vector<Real> QuantLib::LMMDriftCalculator::tmp_ [mutable, private]
Definition at line 75 of file lmmdriftcalculator.hpp.
Referenced by computePlain(), and computeReduced().
std::vector<Size> QuantLib::LMMDriftCalculator::ups_ [private]
Definition at line 77 of file lmmdriftcalculator.hpp.
Referenced by computePlain(), and LMMDriftCalculator().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/driftcomputation/lmmdriftcalculator.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/driftcomputation/lmmdriftcalculator.cpp