QuantLib: QuantLib::BlackCalculator::Calculator Class Reference
QuantLib::BlackCalculator::Calculator Class Reference
Public Member Functions
Calculator (BlackCalculator &black)
void visit (Payoff &)
void visit (PlainVanillaPayoff &)
void visit (CashOrNothingPayoff &)
void visit (AssetOrNothingPayoff &)
void visit (GapPayoff &)
Private Attributes
BlackCalculator & black_
Detailed Description
Definition at line 29 of file blackcalculator.cpp.
Constructor & Destructor Documentation
QuantLib::BlackCalculator::Calculator::Calculator (BlackCalculator & black) [inline]
Definition at line 38 of file blackcalculator.cpp.
: black_(black) {}
Member Function Documentation
void QuantLib::BlackCalculator::Calculator::visit (Payoff & p) [virtual]
Implements QuantLib::Visitor< Payoff >.
Definition at line 154 of file blackcalculator.cpp.
References QuantLib::Payoff::name(), and QL_FAIL.
{
        QL_FAIL("unsupported payoff type: " << p.name());
    }
void QuantLib::BlackCalculator::Calculator::visit (PlainVanillaPayoff &) [virtual]
Implements QuantLib::Visitor< PlainVanillaPayoff >.
Definition at line 158 of file blackcalculator.cpp.
{}
void QuantLib::BlackCalculator::Calculator::visit (CashOrNothingPayoff & payoff) [virtual]
Implements QuantLib::Visitor< CashOrNothingPayoff >.
Definition at line 160 of file blackcalculator.cpp.
References QuantLib::Option::Call, QuantLib::CashOrNothingPayoff::cashPayoff(), QuantLib::TypePayoff::optionType(), QuantLib::Option::Put, and QL_FAIL.
{
        black_.alpha_ = black_.DalphaDd1_ = 0.0;
        black_.x_ = payoff.cashPayoff();
        black_.DxDstrike_ = 0.0;
        switch (payoff.optionType()) {
          case Option::Call:
            black_.beta_     = black_.cum_d2_;
            black_.DbetaDd2_ = black_.n_d2_;
            break;
          case Option::Put:
            black_.beta_     = 1.0-black_.cum_d2_;
            black_.DbetaDd2_ =    -black_.n_d2_;
            break;
          default:
            QL_FAIL("invalid option type");
        }
    }
void QuantLib::BlackCalculator::Calculator::visit (AssetOrNothingPayoff & payoff) [virtual]
Implements QuantLib::Visitor< AssetOrNothingPayoff >.
Definition at line 178 of file blackcalculator.cpp.
References QuantLib::Option::Call, QuantLib::TypePayoff::optionType(), QuantLib::Option::Put, and QL_FAIL.
{
        black_.beta_ = black_.DbetaDd2_ = 0.0;
        switch (payoff.optionType()) {
          case Option::Call:
            black_.alpha_     = black_.cum_d1_;
            black_.DalphaDd1_ = black_.n_d1_;
            break;
          case Option::Put:
            black_.alpha_     = 1.0-black_.cum_d1_;
            black_.DalphaDd1_ = -black_.n_d1_;
            break;
          default:
            QL_FAIL("invalid option type");
        }
    }
void QuantLib::BlackCalculator::Calculator::visit (GapPayoff & payoff) [virtual]
Implements QuantLib::Visitor< GapPayoff >.
Definition at line 194 of file blackcalculator.cpp.
References QuantLib::GapPayoff::secondStrike().
{
        black_.x_ = payoff.secondStrike();
        black_.DxDstrike_ = 0.0;
    }
Member Data Documentation
BlackCalculator& QuantLib::BlackCalculator::Calculator::black_ [private]
Definition at line 36 of file blackcalculator.cpp.
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/blackcalculator.cpp