QuantLib: QuantLib::SwingExercise Class Reference
QuantLib::SwingExercise Class Reference
Swing exercise.
#include <vanillaswingoption.hpp>
Public Member Functions
SwingExercise (const std::vector< Date > &dates, const std::vector< Size > &seconds=std::vector< Size >())
SwingExercise (const Date &from, const Date &to, Size stepSizeSecs)
const std::vector< Size > & seconds () const
std::vector< Time > exerciseTimes (const DayCounter &dc, const Date &refDate) const
Private Attributes
const std::vector< Size > seconds_
Detailed Description
Swing exercise.
A Swing option can only be exercised at a set of fixed date times
Definition at line 37 of file vanillaswingoption.hpp.
Constructor & Destructor Documentation
QuantLib::SwingExercise::SwingExercise (const std::vector< Date > & dates, const std::vector< Size > & seconds = std::vector<Size>())
Definition at line 57 of file vanillaswingoption.cpp.
References QuantLib::Exercise::dates_, QL_REQUIRE, seconds_, and QuantLib::anonymous_namespace{vanillaswingoption.cpp}::secPerDay.
    : BermudanExercise(dates),
      seconds_(seconds.empty() ? std::vector<Size>(dates.size(), 0u)
                               : seconds) {
        QL_REQUIRE(dates_.size() == seconds_.size(),
                   "dates and seconds must have the same size");
        for (Size i=0; i < dates_.size(); ++i) {
            QL_REQUIRE(seconds_[i] < secPerDay,
                       "a date can not have more than 24*3600 seconds");
            if (i > 0) {
                QL_REQUIRE(dates_[i-1] < dates_[i]
                           || (dates_[i-1] == dates_[i]
                               && seconds_[i-1] < seconds_[i]),
                           "date times must be sorted");
            }
        }
    }
QuantLib::SwingExercise::SwingExercise (const Date & from, const Date & to, Size stepSizeSecs)
Definition at line 77 of file vanillaswingoption.cpp.
    : BermudanExercise(createDateTimes(from, to, stepSizeSecs).first),
      seconds_(createDateTimes(from, to, stepSizeSecs).second) {
    }
Member Function Documentation
std::vector< Time > QuantLib::SwingExercise::exerciseTimes (const DayCounter & dc, const Date & refDate) const
Definition at line 85 of file vanillaswingoption.cpp.
References QuantLib::Exercise::dates(), QuantLib::Days, QuantLib::anonymous_namespace{yieldtermstructure.cpp}::dt, QL_REQUIRE, seconds(), anonymous_namespace{quantlibbenchmark.cpp}::t, and QuantLib::DayCounter::yearFraction().
{
        std::vector<Time> exerciseTimes;
        exerciseTimes.reserve(dates().size());
        for (Size i=0; i<dates().size(); ++i) {
            Time t = dc.yearFraction(refDate, dates()[i]);
            const Time dt
                = dc.yearFraction(refDate, dates()[i]+Period(1u, Days)) - t;
            t += dt*seconds()[i]/(24*3600.);
            QL_REQUIRE(t >= 0, "exercise dates must not contain past date");
            exerciseTimes.push_back(t);
        }
        return exerciseTimes;
    }
const std::vector< Size > & QuantLib::SwingExercise::seconds () const
Definition at line 83 of file vanillaswingoption.cpp.
References seconds_.
Referenced by exerciseTimes().
{ return seconds_; }
Member Data Documentation
const std::vector<Size> QuantLib::SwingExercise::seconds_ [private]
Definition at line 49 of file vanillaswingoption.hpp.
Referenced by seconds(), and SwingExercise().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/vanillaswingoption.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/vanillaswingoption.cpp