QuantLib: QuantLib::TrinomialTree Class Reference
QuantLib::TrinomialTree Class Reference
Recombining trinomial tree class.
#include <trinomialtree.hpp>
Classes
class Branching
Public Types
enum Branches { branches = 3 }
Public Member Functions
TrinomialTree (const boost::shared_ptr< StochasticProcess1D > &process, const TimeGrid &timeGrid, bool isPositive=false)
Real dx (Size i) const
const TimeGrid & timeGrid () const
Size size (Size i) const
Real underlying (Size i, Size index) const
Size descendant (Size i, Size index, Size branch) const
Real probability (Size i, Size index, Size branch) const
Protected Attributes
std::vector< Branching > branchings_
Real x0_
std::vector< Real > dx_
TimeGrid timeGrid_
Detailed Description
Recombining trinomial tree class.
This class defines a recombining trinomial tree approximating a 1-D stochastic process.
Warning:
The diffusion term of the SDE must be independent of the underlying process.
Definition at line 41 of file trinomialtree.hpp.
Member Enumeration Documentation
enum QuantLib::TrinomialTree::Branches
Enumerator:
branches
Definition at line 44 of file trinomialtree.hpp.
{ branches = 3 };
Constructor & Destructor Documentation
QuantLib::TrinomialTree::TrinomialTree (const boost::shared_ptr< StochasticProcess1D > & process, const TimeGrid & timeGrid, bool isPositive = false)
Definition at line 26 of file trinomialtree.cpp.
References QuantLib::TrinomialTree::Branching::add(), branchings_, QuantLib::anonymous_namespace{yieldtermstructure.cpp}::dt, QuantLib::TimeGrid::dt(), dx_, QuantLib::TrinomialTree::Branching::jMax(), QuantLib::TrinomialTree::Branching::jMin(), QuantLib::TimeGrid::size(), anonymous_namespace{quantlibbenchmark.cpp}::t, anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and x0_.
    : Tree<TrinomialTree>(timeGrid.size()), dx_(1, 0.0), timeGrid_(timeGrid) {
        x0_ = process->x0();
        Size nTimeSteps = timeGrid.size() - 1;
        Integer jMin = 0;
        Integer jMax = 0;
        for (Size i=0; i<nTimeSteps; i++) {
            Time t = timeGrid[i];
            Time dt = timeGrid.dt(i);
            //Variance must be independent of x
            Real v2 = process->variance(t, 0.0, dt);
            Volatility v = std::sqrt(v2);
            dx_.push_back(v*std::sqrt(3.0));
            Branching branching;
            for (Integer j=jMin; j<=jMax; j++) {
                Real x = x0_ + j*dx_[i];
                Real m = process->expectation(t, x, dt);
                Integer temp = Integer(std::floor((m-x0_)/dx_[i+1] + 0.5));
                if (isPositive) {
                    while (x0_+(temp-1)*dx_[i+1]<=0) {
                        temp++;
                    }
                }
                Real e = m - (x0_ + temp*dx_[i+1]);
                Real e2 = e*e;
                Real e3 = e*std::sqrt(3.0);
                Real p1 = (1.0 + e2/v2 - e3/v)/6.0;
                Real p2 = (2.0 - e2/v2)/3.0;
                Real p3 = (1.0 + e2/v2 + e3/v)/6.0;
                branching.add(temp, p1, p2, p3);
            }
            branchings_.push_back(branching);
            jMin = branching.jMin();
            jMax = branching.jMax();
        }
    }
Member Function Documentation
Size QuantLib::TrinomialTree::descendant (Size i, Size index, Size branch) const [inline]
Definition at line 96 of file trinomialtree.hpp.
References branchings_.
{
        return branchings_[i].descendant(index, branch);
    }
Real QuantLib::TrinomialTree::dx (Size i) const [inline]
Definition at line 48 of file trinomialtree.hpp.
References dx_.
Referenced by underlying().
{ return dx_[i]; }
Real QuantLib::TrinomialTree::probability (Size i, Size index, Size branch) const [inline]
Definition at line 101 of file trinomialtree.hpp.
References branchings_.
{
        return branchings_[i].probability(j, b);
    }
Size QuantLib::TrinomialTree::size (Size i) const [inline]
Definition at line 84 of file trinomialtree.hpp.
References branchings_.
{
        return i==0 ? 1 : branchings_[i-1].size();
    }
const TimeGrid& QuantLib::TrinomialTree::timeGrid () const [inline]
Definition at line 49 of file trinomialtree.hpp.
References timeGrid_.
{ return timeGrid_; }
Real QuantLib::TrinomialTree::underlying (Size i, Size index) const [inline]
Definition at line 88 of file trinomialtree.hpp.
References branchings_, dx(), and x0_.
{
        if (i==0)
            return x0_;
        else
            return x0_ + (branchings_[i-1].jMin() +
                          static_cast<Real>(index))*dx(i);
    }
Member Data Documentation
std::vector<Branching> QuantLib::TrinomialTree::branchings_ [protected]
Definition at line 57 of file trinomialtree.hpp.
Referenced by descendant(), probability(), size(), TrinomialTree(), and underlying().
std::vector<Real> QuantLib::TrinomialTree::dx_ [protected]
Definition at line 59 of file trinomialtree.hpp.
Referenced by dx(), and TrinomialTree().
TimeGrid QuantLib::TrinomialTree::timeGrid_ [protected]
Definition at line 60 of file trinomialtree.hpp.
Referenced by timeGrid().
Real QuantLib::TrinomialTree::x0_ [protected]
Definition at line 58 of file trinomialtree.hpp.
Referenced by TrinomialTree(), and underlying().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/lattices/trinomialtree.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/lattices/trinomialtree.cpp