QuantLib: QuantLib::FdmLogInnerValue Class Reference
QuantLib::FdmLogInnerValue Class Reference
#include <fdminnervaluecalculator.hpp>
Public Member Functions
FdmLogInnerValue (const boost::shared_ptr< Payoff > &payoff, const boost::shared_ptr< FdmMesher > &mesher, Size direction)
Real innerValue (const FdmLinearOpIterator &iter, Time)
Real avgInnerValue (const FdmLinearOpIterator &iter, Time)
Private Member Functions
Real avgInnerValueCalc (const FdmLinearOpIterator &iter, Time)
Private Attributes
const boost::shared_ptr< Payoff > payoff_
const boost::shared_ptr
< FdmMesher > mesher_
const Size direction_
std::vector< Real > avgInnerValues_
Detailed Description
Definition at line 49 of file fdminnervaluecalculator.hpp.
Constructor & Destructor Documentation
QuantLib::FdmLogInnerValue::FdmLogInnerValue (const boost::shared_ptr< Payoff > & payoff, const boost::shared_ptr< FdmMesher > & mesher, Size direction)
Definition at line 38 of file fdminnervaluecalculator.cpp.
    : payoff_(payoff),
      mesher_(mesher),
      direction_ (direction) {
    }
Member Function Documentation
Real QuantLib::FdmLogInnerValue::avgInnerValue (const FdmLinearOpIterator & iter, Time t) [virtual]
Implements QuantLib::FdmInnerValueCalculator.
Definition at line 52 of file fdminnervaluecalculator.cpp.
References avgInnerValueCalc(), avgInnerValues_, QuantLib::FdmLinearOpIterator::coordinates(), direction_, and mesher_.
{
        if (avgInnerValues_.empty()) {
            // calculate caching values
            avgInnerValues_.resize(mesher_->layout()->dim()[direction_]);
            std::deque<bool> initialized(avgInnerValues_.size(), false);
            const boost::shared_ptr<FdmLinearOpLayout> layout=mesher_->layout();
            const FdmLinearOpIterator endIter = layout->end();
            for (FdmLinearOpIterator iter = layout->begin(); iter != endIter;
                 ++iter) {
                const Size xn = iter.coordinates()[direction_];
                if (!initialized[xn]) {
                    initialized[xn]     = true;
                    avgInnerValues_[xn] = avgInnerValueCalc(iter, t);
                }
            }
        }
        return avgInnerValues_[iter.coordinates()[direction_]];
    }
Real QuantLib::FdmLogInnerValue::avgInnerValueCalc (const FdmLinearOpIterator & iter, Time t) [private]
Definition at line 74 of file fdminnervaluecalculator.cpp.
References anonymous_namespace{marketmodel.cpp}::a, anonymous_namespace{marketmodel.cpp}::b, QuantLib::compose(), QuantLib::FdmLinearOpIterator::coordinates(), direction_, anonymous_namespace{interpolations.cpp}::f(), innerValue(), mesher_, and payoff_.
Referenced by avgInnerValue().
{
        const Size dim = mesher_->layout()->dim()[direction_];
        const Size coord = iter.coordinates()[direction_];
        const Real loc = mesher_->location(iter,direction_);
        Real a = loc;
        Real b = loc;
        if (coord > 0) {
            a -= mesher_->dminus(iter, direction_)/2.0;
        }
        if (coord < dim-1) {
            b += mesher_->dplus(iter, direction_)/2.0;
        }
        boost::function1<Real, Real> f = compose(
            std::bind1st(std::mem_fun(&Payoff::operator()), payoff_.get()),
                         std::ptr_fun<Real,Real>(std::exp));
        Real retVal;
        try {
            const Real acc
                = ((f(a) != 0.0 || f(b) != 0.0) ? (f(a)+f(b))*5e-5 : 1e-4);
            retVal = SimpsonIntegral(acc, 8)(f, a, b)/(b-a);
        }
        catch (Error&) {
            // use default value
            retVal = innerValue(iter, t);
        }
        return retVal;
    }
Real QuantLib::FdmLogInnerValue::innerValue (const FdmLinearOpIterator & iter, Time) [virtual]
Implements QuantLib::FdmInnerValueCalculator.
Definition at line 47 of file fdminnervaluecalculator.cpp.
References direction_, mesher_, and payoff_.
Referenced by avgInnerValueCalc().
{
        const Real s = std::exp(mesher_->location(iter, direction_));
        return payoff_->operator()(s);
    }
Member Data Documentation
std::vector<Real> QuantLib::FdmLogInnerValue::avgInnerValues_ [private]
Definition at line 65 of file fdminnervaluecalculator.hpp.
Referenced by avgInnerValue().
const Size QuantLib::FdmLogInnerValue::direction_ [private]
Definition at line 64 of file fdminnervaluecalculator.hpp.
Referenced by avgInnerValue(), avgInnerValueCalc(), and innerValue().
const boost::shared_ptr<FdmMesher> QuantLib::FdmLogInnerValue::mesher_ [private]
Definition at line 63 of file fdminnervaluecalculator.hpp.
Referenced by avgInnerValue(), avgInnerValueCalc(), and innerValue().
const boost::shared_ptr<Payoff> QuantLib::FdmLogInnerValue::payoff_ [private]
Definition at line 62 of file fdminnervaluecalculator.hpp.
Referenced by avgInnerValueCalc(), and innerValue().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/utilities/fdminnervaluecalculator.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/utilities/fdminnervaluecalculator.cpp