QuantLib: QuantLib::GaussianLHPCDOEngine< CDOEngine > Class Template Reference
QuantLib::GaussianLHPCDOEngine< CDOEngine > Class Template Reference
#include <syntheticcdoengines.hpp>
Public Member Functions
GaussianLHPCDOEngine (const Handle< OneFactorCopula > &copula)
Private Member Functions
Real expectedTrancheLoss (const Date &d) const
Private Attributes
const Handle< OneFactorCopula > copula_
Detailed Description
template<class CDOEngine>
class QuantLib::GaussianLHPCDOEngine< CDOEngine >
CDO engine with analytical expected tranche loss for a large homogeneous pool with Gaussian one-factor copula. See for example "The Normal Inverse Gaussian Distribution for Synthetic CDO pricing.", Anna Kalemanova, Bernd Schmid, Ralf Werner, Journal of Derivatives, Vol. 14, No. 3, (Spring 2007), pp. 80-93. http://www.defaultrisk.com/pp_crdrv_91.htm
Definition at line 228 of file syntheticcdoengines.hpp.
Constructor & Destructor Documentation
template<class CDOEngine > QuantLib::GaussianLHPCDOEngine< CDOEngine >::GaussianLHPCDOEngine (const Handle< OneFactorCopula > & copula) [inline]
Definition at line 230 of file syntheticcdoengines.hpp.
References QuantLib::GaussianLHPCDOEngine< CDOEngine >::copula_.
            : copula_(copula) {
            this->registerWith(copula_);
        }
Member Function Documentation
template<class CDOEngine > Real QuantLib::GaussianLHPCDOEngine< CDOEngine >::expectedTrancheLoss (const Date & d) const [inline, private]
Definition at line 235 of file syntheticcdoengines.hpp.
References QuantLib::GaussianLHPCDOEngine< CDOEngine >::copula_, QuantLib::Issuer::defaultProbability(), QuantLib::Settings::evaluationDate(), QuantLib::Singleton< Settings >::instance(), QuantLib::inverse(), and QuantLib::anonymous_namespace{bjerksundstenslandengine.cpp}::phi().
{
            Date today = Settings::instance().evaluationDate();
            Date start = this->arguments_.schedule.startDate();
            boost::shared_ptr<Basket>& basket = this->arguments_.basket;
            std::vector<std::string> names =
                basket->remainingNames(start, today);
            const boost::shared_ptr<Pool> pool = basket->pool();
            Issuer name = pool->get(names[0]);
            Real prob = name.defaultProbability(basket->defaultKeys()[0])->defaultProbability(d);
            //what if the name has defualted? The homogeneity in the model concerns the default state too...
            Real rec = basket->recoveryModels()[0]->recoveryValue(d,
                basket->defaultKeys()[0]);
            Real ntl = this->results_.remainingNotional;
            Real attach = basket->remainingAttachmentRatio(start, today);
            Real detach = basket->remainingDetachmentRatio(start, today);
            Real one = 1.0 - 1.0e-12;  // FIXME
            Real k1 = std::min(one, attach / (1.0 - rec));
            Real k2 = std::min(one, detach / (1.0 - rec));
            Real y = sqrt(1.0 - copula_->correlation());
            BivariateCumulativeNormalDistribution biphi(-y);
            InverseCumulativeNormal inverse;
            CumulativeNormalDistribution phi;
            if (ntl == 0.) return 0.;
            if (prob > 0) {
                Real ip = inverse(prob);
                if (k1 > 0)
                    return ntl
                        * (biphi(-inverse(k1), ip) - biphi(-inverse(k2), ip))
                        / (k2 - k1);
                else return ntl * (prob - biphi(-inverse(k2), ip)) / (k2 - k1);
            }
            else return 0.0;
        };
Member Data Documentation
template<class CDOEngine > const Handle<OneFactorCopula> QuantLib::GaussianLHPCDOEngine< CDOEngine >::copula_ [private]
Definition at line 271 of file syntheticcdoengines.hpp.
Referenced by QuantLib::GaussianLHPCDOEngine< CDOEngine >::expectedTrancheLoss(), and QuantLib::GaussianLHPCDOEngine< CDOEngine >::GaussianLHPCDOEngine().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/syntheticcdoengines.hpp