QuantLib: DefaultProbabilityCurveTest Class Reference
DefaultProbabilityCurveTest Class Reference
#include <defaultprobabilitycurves.hpp>
Static Public Member Functions
static void testDefaultProbability ()
static void testFlatHazardRate ()
static void testFlatHazardConsistency ()
static void testFlatDensityConsistency ()
static void testLinearDensityConsistency ()
static void testLogLinearSurvivalConsistency ()
static void testSingleInstrumentBootstrap ()
static void testUpfrontBootstrap ()
static
boost::unit_test_framework::test_suite * suite ()
Detailed Description
Definition at line 29 of file defaultprobabilitycurves.hpp.
Member Function Documentation
test_suite * DefaultProbabilityCurveTest::suite () [static]
Definition at line 390 of file defaultprobabilitycurves.cpp.
References QUANTLIB_TEST_CASE, testDefaultProbability(), testFlatDensityConsistency(), testFlatHazardConsistency(), testFlatHazardRate(), testLinearDensityConsistency(), testLogLinearSurvivalConsistency(), testSingleInstrumentBootstrap(), and testUpfrontBootstrap().
Referenced by init_unit_test_suite().
{
    test_suite* suite = BOOST_TEST_SUITE("Default-probability curve tests");
    suite->add(QUANTLIB_TEST_CASE(
                       &DefaultProbabilityCurveTest::testDefaultProbability));
    suite->add(QUANTLIB_TEST_CASE(
                           &DefaultProbabilityCurveTest::testFlatHazardRate));
    suite->add(QUANTLIB_TEST_CASE(
                    &DefaultProbabilityCurveTest::testFlatHazardConsistency));
    suite->add(QUANTLIB_TEST_CASE(
                   &DefaultProbabilityCurveTest::testFlatDensityConsistency));
    suite->add(QUANTLIB_TEST_CASE(
                 &DefaultProbabilityCurveTest::testLinearDensityConsistency));
    suite->add(QUANTLIB_TEST_CASE(
             &DefaultProbabilityCurveTest::testLogLinearSurvivalConsistency));
    suite->add(QUANTLIB_TEST_CASE(
                &DefaultProbabilityCurveTest::testSingleInstrumentBootstrap));
    suite->add(QUANTLIB_TEST_CASE(
                         &DefaultProbabilityCurveTest::testUpfrontBootstrap));
    return suite;
}
void DefaultProbabilityCurveTest::testDefaultProbability () [static]
Definition at line 42 of file defaultprobabilitycurves.cpp.
References QuantLib::Calendar::advance(), anonymous_namespace{marketmodel.cpp}::calendar, anonymous_namespace{marketmodel.cpp}::dayCounter, QuantLib::DefaultProbabilityTermStructure::defaultProbability(), anonymous_namespace{marketmodel.cpp}::endDate, QuantLib::Settings::evaluationDate(), QuantLib::Singleton< Settings >::instance(), anonymous_namespace{marketmodel.cpp}::startDate, anonymous_namespace{gaussianquadratures.cpp}::tolerance, QuantLib::DayCounter::yearFraction(), and QuantLib::Years.
Referenced by suite().
{
    BOOST_MESSAGE("Testing default-probability structure...");
    Real hazardRate = 0.0100;
    Handle<Quote> hazardRateQuote = Handle<Quote>(
                boost::shared_ptr<Quote>(new SimpleQuote(hazardRate)));
    DayCounter dayCounter = Actual360();
    Calendar calendar = TARGET();
    Size n = 20;
    double tolerance = 1.0e-10;
    Date today = Settings::instance().evaluationDate();
    Date startDate = today;
    Date endDate = startDate;
    FlatHazardRate flatHazardRate(startDate, hazardRateQuote, dayCounter);
    for(Size i=0; i<n; i++){
        startDate = endDate;
        endDate = calendar.advance(endDate, 1, Years);
        Probability pStart = flatHazardRate.defaultProbability(startDate);
        Probability pEnd = flatHazardRate.defaultProbability(endDate);
        Probability pBetweenComputed =
            flatHazardRate.defaultProbability(startDate, endDate);
        Probability pBetween = pEnd - pStart;
        if (std::fabs(pBetween - pBetweenComputed) > tolerance)
            BOOST_ERROR(
                "Failed to reproduce probability(d1, d2) "
                << "for default probability structure\n"
                << std::setprecision(12)
                << "    calculated probability: " << pBetweenComputed << "\n"
                << "    expected probability:   " << pBetween);
        Time t2 = dayCounter.yearFraction(today, endDate);
        Probability timeProbability = flatHazardRate.defaultProbability(t2);
        Probability dateProbability =
            flatHazardRate.defaultProbability(endDate);
        if (std::fabs(timeProbability - dateProbability) > tolerance)
            BOOST_ERROR(
                "single-time probability and single-date probability do not match\n"
                << std::setprecision(10)
                << "    time probability: " << timeProbability << "\n"
                << "    date probability: " << dateProbability);
        Time t1 = dayCounter.yearFraction(today, startDate);
        timeProbability = flatHazardRate.defaultProbability(t1, t2);
        dateProbability = flatHazardRate.defaultProbability(startDate, endDate);
        if (std::fabs(timeProbability - dateProbability) > tolerance)
            BOOST_ERROR(
                "double-time probability and double-date probability do not match\n"
                << std::setprecision(10)
                << "    time probability: " << timeProbability << "\n"
                << "    date probability: " << dateProbability);
    }
}
void DefaultProbabilityCurveTest::testFlatDensityConsistency () [static]
Definition at line 320 of file defaultprobabilitycurves.cpp.
Referenced by suite().
{
    BOOST_MESSAGE("Testing piecewise-flat default-density consistency...");
    testBootstrapFromSpread<DefaultDensity,BackwardFlat>();
    testBootstrapFromUpfront<DefaultDensity,BackwardFlat>();
}
void DefaultProbabilityCurveTest::testFlatHazardConsistency () [static]
Definition at line 314 of file defaultprobabilitycurves.cpp.
Referenced by suite().
{
    BOOST_MESSAGE("Testing piecewise-flat hazard-rate consistency...");
    testBootstrapFromSpread<HazardRate,BackwardFlat>();
    testBootstrapFromUpfront<HazardRate,BackwardFlat>();
}
void DefaultProbabilityCurveTest::testFlatHazardRate () [static]
Definition at line 106 of file defaultprobabilitycurves.cpp.
References QuantLib::Calendar::advance(), anonymous_namespace{marketmodel.cpp}::calendar, anonymous_namespace{marketmodel.cpp}::dayCounter, QuantLib::DefaultProbabilityTermStructure::defaultProbability(), anonymous_namespace{marketmodel.cpp}::endDate, QuantLib::Settings::evaluationDate(), QuantLib::Singleton< Settings >::instance(), anonymous_namespace{marketmodel.cpp}::startDate, anonymous_namespace{quantlibbenchmark.cpp}::t, anonymous_namespace{gaussianquadratures.cpp}::tolerance, QuantLib::DayCounter::yearFraction(), and QuantLib::Years.
Referenced by suite().
{
    BOOST_MESSAGE("Testing flat hazard rate...");
    Real hazardRate = 0.0100;
    Handle<Quote> hazardRateQuote = Handle<Quote>(
                boost::shared_ptr<Quote>(new SimpleQuote(hazardRate)));
    DayCounter dayCounter = Actual360();
    Calendar calendar = TARGET();
    Size n = 20;
    double tolerance = 1.0e-10;
    Date today = Settings::instance().evaluationDate();
    Date startDate = today;
    Date endDate = startDate;
    FlatHazardRate flatHazardRate(today, hazardRateQuote, dayCounter);
    for(Size i=0; i<n; i++){
        endDate = calendar.advance(endDate, 1, Years);
        Time t = dayCounter.yearFraction(startDate, endDate);
        Probability probability = 1.0 - std::exp(-hazardRate * t);
        Probability computedProbability = flatHazardRate.defaultProbability(t);
        if (std::fabs(probability - computedProbability) > tolerance)
            BOOST_ERROR(
                "Failed to reproduce probability for flat hazard rate\n"
                << std::setprecision(10)
                << "    calculated probability: " << computedProbability << "\n"
                << "    expected probability:   " << probability);
    }
}
void DefaultProbabilityCurveTest::testLinearDensityConsistency () [static]
Definition at line 326 of file defaultprobabilitycurves.cpp.
Referenced by suite().
{
    BOOST_MESSAGE("Testing piecewise-linear default-density consistency...");
    testBootstrapFromSpread<DefaultDensity,Linear>();
    testBootstrapFromUpfront<DefaultDensity,Linear>();
}
void DefaultProbabilityCurveTest::testLogLinearSurvivalConsistency () [static]
Definition at line 332 of file defaultprobabilitycurves.cpp.
Referenced by suite().
{
    BOOST_MESSAGE("Testing log-linear survival-probability consistency...");
    testBootstrapFromSpread<SurvivalProbability,LogLinear>();
    testBootstrapFromUpfront<SurvivalProbability,LogLinear>();
}
void DefaultProbabilityCurveTest::testSingleInstrumentBootstrap () [static]
Definition at line 338 of file defaultprobabilitycurves.cpp.
References anonymous_namespace{marketmodel.cpp}::calendar, anonymous_namespace{marketmodel.cpp}::dayCounter, QuantLib::Settings::evaluationDate(), QuantLib::Following, QuantLib::Singleton< Settings >::instance(), QuantLib::RelinkableHandle< T >::linkTo(), QuantLib::Quarterly, QuantLib::DateGeneration::TwentiethIMM, and QuantLib::Years.
Referenced by suite().
{
    BOOST_MESSAGE("Testing single-instrument curve bootstrap...");
    Calendar calendar = TARGET();
    Date today = Settings::instance().evaluationDate();
    Integer settlementDays = 0;
    Real quote = 0.005;
    Period tenor = 2*Years;
    Frequency frequency = Quarterly;
    BusinessDayConvention convention = Following;
    DateGeneration::Rule rule = DateGeneration::TwentiethIMM;
    DayCounter dayCounter = Thirty360();
    Real recoveryRate = 0.4;
    RelinkableHandle<YieldTermStructure> discountCurve;
    discountCurve.linkTo(boost::shared_ptr<YieldTermStructure>(
                                    new FlatForward(today,0.06,Actual360())));
    std::vector<boost::shared_ptr<DefaultProbabilityHelper> > helpers(1);
    helpers[0] = boost::shared_ptr<DefaultProbabilityHelper>(
                        new SpreadCdsHelper(quote, tenor,
                                            settlementDays, calendar,
                                            frequency, convention, rule,
                                            dayCounter, recoveryRate,
                                            discountCurve));
    PiecewiseDefaultCurve<HazardRate,BackwardFlat> defaultCurve(today, helpers,
                                                                dayCounter);
    defaultCurve.recalculate();
}
void DefaultProbabilityCurveTest::testUpfrontBootstrap () [static]
Definition at line 374 of file defaultprobabilitycurves.cpp.
References QuantLib::Settings::includeTodaysCashFlows(), and QuantLib::Singleton< Settings >::instance().
Referenced by suite().
{
    BOOST_MESSAGE("Testing bootstrap on upfront quotes...");
    SavedSettings backup;
    // not taken into account, this would prevent the upfront from being used
    Settings::instance().includeTodaysCashFlows() = false;
    testBootstrapFromUpfront<HazardRate,BackwardFlat>();
    // also ensure that we didn't override the flag permanently
    boost::optional<bool> flag = Settings::instance().includeTodaysCashFlows();
    if (flag != false)
        BOOST_ERROR("Cash-flow settings improperly modified");
}
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/defaultprobabilitycurves.hpp
/home/deriversatile/QuantLib/QuantLibQt/test-suite/defaultprobabilitycurves.cpp