QuantLib: QuantLib::CuriouslyRecurringTemplate< Impl > Class Template Reference
QuantLib::CuriouslyRecurringTemplate< Impl > Class Template Reference
Support for the curiously recurring template pattern.
#include <curiouslyrecurring.hpp>
Protected Member Functions
CuriouslyRecurringTemplate ()
~CuriouslyRecurringTemplate ()
Impl & impl ()
const Impl & impl () const
Detailed Description
template<class Impl>
class QuantLib::CuriouslyRecurringTemplate< Impl >
Support for the curiously recurring template pattern.
See James O. Coplien. A Curiously Recurring Template Pattern. In Stanley B. Lippman, editor, C++ Gems, 135-144. Cambridge University Press, New York, New York, 1996.
Definition at line 39 of file curiouslyrecurring.hpp.
Constructor & Destructor Documentation
template<class Impl> QuantLib::CuriouslyRecurringTemplate< Impl >::CuriouslyRecurringTemplate () [inline, protected]
Definition at line 42 of file curiouslyrecurring.hpp.
{}
template<class Impl> QuantLib::CuriouslyRecurringTemplate< Impl >::~CuriouslyRecurringTemplate () [inline, protected]
Definition at line 43 of file curiouslyrecurring.hpp.
{}
Member Function Documentation
template<class Impl> Impl& QuantLib::CuriouslyRecurringTemplate< Impl >::impl () [inline, protected]
Definition at line 45 of file curiouslyrecurring.hpp.
Referenced by QuantLib::TreeLattice1D< BlackScholesLattice< T > >::grid(), QuantLib::Solver1D< Ridder >::solve(), and QuantLib::TreeLattice1D< BlackScholesLattice< T > >::underlying().
                     {
            return static_cast<Impl&>(*this);
        }
template<class Impl> const Impl& QuantLib::CuriouslyRecurringTemplate< Impl >::impl () const [inline, protected]
Definition at line 48 of file curiouslyrecurring.hpp.
{
            return static_cast<const Impl&>(*this);
        }
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/patterns/curiouslyrecurring.hpp