QuantLib: QuantLib::SabrInterpolatedSmileSection Class Reference
QuantLib::SabrInterpolatedSmileSection Class Reference
#include <sabrinterpolatedsmilesection.hpp>
Public Member Functions
Real varianceImpl (Rate strike) const
Volatility volatilityImpl (Rate strike) const
Constructors
SabrInterpolatedSmileSection (const Date &optionDate, const Handle< Quote > &forward, const std::vector< Rate > &strikes, bool hasFloatingStrikes, const Handle< Quote > &atmVolatility, const std::vector< Handle< Quote > > &volHandles, Real alpha, Real beta, Real nu, Real rho, bool isAlphaFixed=false, bool isBetaFixed=false, bool isNuFixed=false, bool isRhoFixed=false, bool vegaWeighted=true, const boost::shared_ptr< EndCriteria > &endCriteria=boost::shared_ptr< EndCriteria >(), const boost::shared_ptr< OptimizationMethod > &method=boost::shared_ptr< OptimizationMethod >(), const DayCounter &dc=Actual365Fixed())
all market data are quotes
SabrInterpolatedSmileSection (const Date &optionDate, const Rate &forward, const std::vector< Rate > &strikes, bool hasFloatingStrikes, const Volatility &atmVolatility, const std::vector< Volatility > &vols, Real alpha, Real beta, Real nu, Real rho, bool isAlphaFixed=false, bool isBetaFixed=false, bool isNuFixed=false, bool isRhoFixed=false, bool vegaWeighted=true, const boost::shared_ptr< EndCriteria > &endCriteria=boost::shared_ptr< EndCriteria >(), const boost::shared_ptr< OptimizationMethod > &method=boost::shared_ptr< OptimizationMethod >(), const DayCounter &dc=Actual365Fixed())
no quotes
LazyObject interface
virtual void performCalculations () const
virtual void update ()
SmileSection interface
Real minStrike () const
Real maxStrike () const
Real atmLevel () const
Inspectors
Real alpha () const
Real beta () const
Real nu () const
Real rho () const
Real rmsError () const
Real maxError () const
EndCriteria::Type endCriteria () const
Protected Member Functions
void createInterpolation () const
Creates the mutable SABRInterpolation.
Protected Attributes
boost::shared_ptr
< SABRInterpolation > sabrInterpolation_
const Handle< Quote > forward_
Market data.
const Handle< Quote > atmVolatility_
std::vector< Handle< Quote > > volHandles_
std::vector< Rate > strikes_
std::vector< Rate > actualStrikes_
Only strikes corresponding to valid market data.
bool hasFloatingStrikes_
Real forwardValue_
std::vector< Volatility > vols_
Real alpha_
Sabr parameters.
Real beta_
Real nu_
Real rho_
bool isAlphaFixed_
Sabr interpolation settings.
bool isBetaFixed_
bool isNuFixed_
bool isRhoFixed_
bool vegaWeighted_
const boost::shared_ptr
< EndCriteria > endCriteria_
const boost::shared_ptr
< OptimizationMethod > method_
Date evaluationDate_
Detailed Description
Definition at line 37 of file sabrinterpolatedsmilesection.hpp.
Constructor & Destructor Documentation
QuantLib::SabrInterpolatedSmileSection::SabrInterpolatedSmileSection (const Date & optionDate, const Handle< Quote > & forward, const std::vector< Rate > & strikes, bool hasFloatingStrikes, const Handle< Quote > & atmVolatility, const std::vector< Handle< Quote > > & volHandles, Real alpha, Real beta, Real nu, Real rho, bool isAlphaFixed = false, bool isBetaFixed = false, bool isNuFixed = false, bool isRhoFixed = false, bool vegaWeighted = true, const boost::shared_ptr< EndCriteria > & endCriteria = boost::shared_ptr<EndCriteria>(), const boost::shared_ptr< OptimizationMethod > & method = boost::shared_ptr<OptimizationMethod>(), const DayCounter & dc = Actual365Fixed())
all market data are quotes
Definition at line 27 of file sabrinterpolatedsmilesection.cpp.
References atmVolatility_, forward_, QuantLib::Observer::registerWith(), and volHandles_.
         : SmileSection(optionDate, dc),
           forward_(forward), atmVolatility_(atmVolatility),
           volHandles_(volHandles), strikes_(strikes), actualStrikes_(strikes),
           hasFloatingStrikes_(hasFloatingStrikes), vols_(volHandles.size()),
           alpha_(alpha), beta_(beta), nu_(nu), rho_(rho),
           isAlphaFixed_(isAlphaFixed), isBetaFixed_(isBetaFixed),
           isNuFixed_(isNuFixed), isRhoFixed_(isRhoFixed),
           vegaWeighted_(vegaWeighted),
           endCriteria_(endCriteria), method_(method),
           evaluationDate_(Settings::instance().evaluationDate()) {
            LazyObject::registerWith(forward_);
            LazyObject::registerWith(atmVolatility_);
            for (Size i=0; i<volHandles_.size(); ++i)
                LazyObject::registerWith(volHandles_[i]);
    }
QuantLib::SabrInterpolatedSmileSection::SabrInterpolatedSmileSection (const Date & optionDate, const Rate & forward, const std::vector< Rate > & strikes, bool hasFloatingStrikes, const Volatility & atmVolatility, const std::vector< Volatility > & vols, Real alpha, Real beta, Real nu, Real rho, bool isAlphaFixed = false, bool isBetaFixed = false, bool isNuFixed = false, bool isRhoFixed = false, bool vegaWeighted = true, const boost::shared_ptr< EndCriteria > & endCriteria = boost::shared_ptr<EndCriteria>(), const boost::shared_ptr< OptimizationMethod > & method = boost::shared_ptr<OptimizationMethod>(), const DayCounter & dc = Actual365Fixed())
no quotes
Definition at line 58 of file sabrinterpolatedsmilesection.cpp.
References volHandles_.
         : SmileSection(optionDate, dc),
           forward_(Handle<Quote>(boost::shared_ptr<Quote>(new SimpleQuote(forward)))),
           atmVolatility_(Handle<Quote>(boost::shared_ptr<Quote>(new SimpleQuote(atmVolatility)))),
           volHandles_(volHandles.size()), strikes_(strikes), actualStrikes_(strikes),
           hasFloatingStrikes_(hasFloatingStrikes), vols_(volHandles.size()),
           alpha_(alpha), beta_(beta), nu_(nu), rho_(rho),
           isAlphaFixed_(isAlphaFixed), isBetaFixed_(isBetaFixed),
           isNuFixed_(isNuFixed), isRhoFixed_(isRhoFixed),
           vegaWeighted_(vegaWeighted),
           endCriteria_(endCriteria), method_(method),
           evaluationDate_(Settings::instance().evaluationDate()) {
            for (Size i=0; i<volHandles_.size(); ++i)
                volHandles_[i] = Handle<Quote>(boost::shared_ptr<Quote>(new
                                        SimpleQuote(volHandles[i])));
    }
Member Function Documentation
Real QuantLib::SabrInterpolatedSmileSection::alpha () const [inline]
Definition at line 143 of file sabrinterpolatedsmilesection.hpp.
References QuantLib::LazyObject::calculate(), and sabrInterpolation_.
{
        calculate();
        return sabrInterpolation_->alpha();
    }
Real QuantLib::SabrInterpolatedSmileSection::atmLevel () const [inline, virtual]
Implements QuantLib::SmileSection.
Definition at line 189 of file sabrinterpolatedsmilesection.hpp.
References QuantLib::LazyObject::calculate(), and forwardValue_.
{
        calculate();
        return forwardValue_;
    }
Real QuantLib::SabrInterpolatedSmileSection::beta () const [inline]
Definition at line 148 of file sabrinterpolatedsmilesection.hpp.
References QuantLib::LazyObject::calculate(), and sabrInterpolation_.
{
        calculate();
        return sabrInterpolation_->beta();
    }
void QuantLib::SabrInterpolatedSmileSection::createInterpolation () const [protected]
Creates the mutable SABRInterpolation.
Definition at line 90 of file sabrinterpolatedsmilesection.cpp.
References actualStrikes_, alpha_, beta_, endCriteria_, QuantLib::SmileSection::exerciseTime(), forwardValue_, isAlphaFixed_, isBetaFixed_, isNuFixed_, isRhoFixed_, method_, nu_, rho_, sabrInterpolation_, QuantLib::swap(), vegaWeighted_, and vols_.
Referenced by performCalculations().
{
         boost::shared_ptr<SABRInterpolation> tmp(new SABRInterpolation(
                     actualStrikes_.begin(), actualStrikes_.end(), vols_.begin(),
                     exerciseTime(), forwardValue_,
                     alpha_, beta_, nu_, rho_,
                     isAlphaFixed_, isBetaFixed_, isNuFixed_, isRhoFixed_, vegaWeighted_,
                     endCriteria_, method_));
         swap(tmp, sabrInterpolation_);
    }
EndCriteria::Type QuantLib::SabrInterpolatedSmileSection::endCriteria () const [inline]
Definition at line 173 of file sabrinterpolatedsmilesection.hpp.
References QuantLib::LazyObject::calculate(), and sabrInterpolation_.
{
        calculate();
        return sabrInterpolation_->endCriteria();
    }
Real QuantLib::SabrInterpolatedSmileSection::maxError () const [inline]
Definition at line 168 of file sabrinterpolatedsmilesection.hpp.
References QuantLib::LazyObject::calculate(), and sabrInterpolation_.
{
        calculate();
        return sabrInterpolation_->maxError();
    }
Real QuantLib::SabrInterpolatedSmileSection::maxStrike () const [inline, virtual]
Implements QuantLib::SmileSection.
Definition at line 184 of file sabrinterpolatedsmilesection.hpp.
References actualStrikes_, and QuantLib::LazyObject::calculate().
{
        calculate();
        return actualStrikes_.back();
    }
Real QuantLib::SabrInterpolatedSmileSection::minStrike () const [inline, virtual]
Implements QuantLib::SmileSection.
Definition at line 178 of file sabrinterpolatedsmilesection.hpp.
References actualStrikes_, and QuantLib::LazyObject::calculate().
{
        calculate();
        return actualStrikes_.front();
    }
Real QuantLib::SabrInterpolatedSmileSection::nu () const [inline]
Definition at line 153 of file sabrinterpolatedsmilesection.hpp.
References QuantLib::LazyObject::calculate(), and sabrInterpolation_.
{
        calculate();
        return sabrInterpolation_->nu();
    }
void QuantLib::SabrInterpolatedSmileSection::performCalculations () const [virtual]
This method must implement any calculations which must be (re)done in order to calculate the desired results.
Implements QuantLib::LazyObject.
Definition at line 100 of file sabrinterpolatedsmilesection.cpp.
References actualStrikes_, atmVolatility_, createInterpolation(), forward_, forwardValue_, hasFloatingStrikes_, sabrInterpolation_, strikes_, volHandles_, and vols_.
{
        forwardValue_ = forward_->value();
        vols_.clear();
        actualStrikes_.clear();
        // we populate the volatilities, skipping the invalid ones
        for (Size i=0; i<volHandles_.size(); ++i) {
            if (volHandles_[i]->isValid()) {
                if (hasFloatingStrikes_) {
                    actualStrikes_.push_back(forwardValue_ + strikes_[i]);
                    vols_.push_back(atmVolatility_->value() + volHandles_[i]->value());
                } else {
                    actualStrikes_.push_back(strikes_[i]);
                    vols_.push_back(volHandles_[i]->value());
                }
            }
        }
        // we are recreating the sabrinterpolation object unconditionnaly to
        // avoid iterator invalidation
        createInterpolation();
        sabrInterpolation_->update();
    }
Real QuantLib::SabrInterpolatedSmileSection::rho () const [inline]
Definition at line 158 of file sabrinterpolatedsmilesection.hpp.
References QuantLib::LazyObject::calculate(), and sabrInterpolation_.
{
        calculate();
        return sabrInterpolation_->rho();
    }
Real QuantLib::SabrInterpolatedSmileSection::rmsError () const [inline]
Definition at line 163 of file sabrinterpolatedsmilesection.hpp.
References QuantLib::LazyObject::calculate(), and sabrInterpolation_.
{
        calculate();
        return sabrInterpolation_->rmsError();
    }
void QuantLib::SabrInterpolatedSmileSection::update () [inline, virtual]
This method must be implemented in derived classes. An instance of Observer does not call this method directly: instead, it will be called by the observables the instance registered with when they need to notify any changes.
Reimplemented from QuantLib::LazyObject.
Definition at line 133 of file sabrinterpolatedsmilesection.hpp.
{
        LazyObject::update();
        SmileSection::update();
    }
Real QuantLib::SabrInterpolatedSmileSection::varianceImpl (Rate strike) const [virtual]
Reimplemented from QuantLib::SmileSection.
Definition at line 122 of file sabrinterpolatedsmilesection.cpp.
References QuantLib::LazyObject::calculate(), QuantLib::SmileSection::exerciseTime(), and anonymous_namespace{perturbativebarrieroptionengine.cpp}::v().
{
        calculate();
        Real v = (*sabrInterpolation_)(strike, true);
        return v*v*exerciseTime();
    }
Real QuantLib::SabrInterpolatedSmileSection::volatilityImpl (Rate strike) const [inline, virtual]
Implements QuantLib::SmileSection.
Definition at line 138 of file sabrinterpolatedsmilesection.hpp.
References QuantLib::LazyObject::calculate(), and sabrInterpolation_.
{
        calculate();
        return (*sabrInterpolation_)(strike, true);
    }
Member Data Documentation
std::vector<Rate> QuantLib::SabrInterpolatedSmileSection::actualStrikes_ [mutable, protected]
Only strikes corresponding to valid market data.
Definition at line 115 of file sabrinterpolatedsmilesection.hpp.
Referenced by createInterpolation(), maxStrike(), minStrike(), and performCalculations().
Real QuantLib::SabrInterpolatedSmileSection::alpha_ [protected]
Sabr parameters.
Definition at line 121 of file sabrinterpolatedsmilesection.hpp.
Referenced by createInterpolation().
const Handle<Quote> QuantLib::SabrInterpolatedSmileSection::atmVolatility_ [protected]
Definition at line 111 of file sabrinterpolatedsmilesection.hpp.
Referenced by performCalculations(), and SabrInterpolatedSmileSection().
Real QuantLib::SabrInterpolatedSmileSection::beta_ [protected]
Definition at line 121 of file sabrinterpolatedsmilesection.hpp.
Referenced by createInterpolation().
const boost::shared_ptr<EndCriteria> QuantLib::SabrInterpolatedSmileSection::endCriteria_ [protected]
Definition at line 125 of file sabrinterpolatedsmilesection.hpp.
Referenced by createInterpolation().
Date QuantLib::SabrInterpolatedSmileSection::evaluationDate_ [mutable, protected]
Definition at line 129 of file sabrinterpolatedsmilesection.hpp.
const Handle<Quote> QuantLib::SabrInterpolatedSmileSection::forward_ [protected]
Market data.
Definition at line 110 of file sabrinterpolatedsmilesection.hpp.
Referenced by performCalculations(), and SabrInterpolatedSmileSection().
Real QuantLib::SabrInterpolatedSmileSection::forwardValue_ [mutable, protected]
Definition at line 118 of file sabrinterpolatedsmilesection.hpp.
Referenced by atmLevel(), createInterpolation(), and performCalculations().
bool QuantLib::SabrInterpolatedSmileSection::hasFloatingStrikes_ [protected]
Definition at line 116 of file sabrinterpolatedsmilesection.hpp.
Referenced by performCalculations().
bool QuantLib::SabrInterpolatedSmileSection::isAlphaFixed_ [protected]
Sabr interpolation settings.
Definition at line 123 of file sabrinterpolatedsmilesection.hpp.
Referenced by createInterpolation().
bool QuantLib::SabrInterpolatedSmileSection::isBetaFixed_ [protected]
Definition at line 123 of file sabrinterpolatedsmilesection.hpp.
Referenced by createInterpolation().
bool QuantLib::SabrInterpolatedSmileSection::isNuFixed_ [protected]
Definition at line 123 of file sabrinterpolatedsmilesection.hpp.
Referenced by createInterpolation().
bool QuantLib::SabrInterpolatedSmileSection::isRhoFixed_ [protected]
Definition at line 123 of file sabrinterpolatedsmilesection.hpp.
Referenced by createInterpolation().
const boost::shared_ptr<OptimizationMethod> QuantLib::SabrInterpolatedSmileSection::method_ [protected]
Definition at line 126 of file sabrinterpolatedsmilesection.hpp.
Referenced by createInterpolation().
Real QuantLib::SabrInterpolatedSmileSection::nu_ [protected]
Definition at line 121 of file sabrinterpolatedsmilesection.hpp.
Referenced by createInterpolation().
Real QuantLib::SabrInterpolatedSmileSection::rho_ [protected]
Definition at line 121 of file sabrinterpolatedsmilesection.hpp.
Referenced by createInterpolation().
boost::shared_ptr<SABRInterpolation> QuantLib::SabrInterpolatedSmileSection::sabrInterpolation_ [mutable, protected]
Definition at line 107 of file sabrinterpolatedsmilesection.hpp.
Referenced by alpha(), beta(), createInterpolation(), endCriteria(), maxError(), nu(), performCalculations(), rho(), rmsError(), and volatilityImpl().
std::vector<Rate> QuantLib::SabrInterpolatedSmileSection::strikes_ [mutable, protected]
Definition at line 113 of file sabrinterpolatedsmilesection.hpp.
Referenced by performCalculations().
bool QuantLib::SabrInterpolatedSmileSection::vegaWeighted_ [protected]
Definition at line 124 of file sabrinterpolatedsmilesection.hpp.
Referenced by createInterpolation().
std::vector<Handle<Quote> > QuantLib::SabrInterpolatedSmileSection::volHandles_ [protected]
Definition at line 112 of file sabrinterpolatedsmilesection.hpp.
Referenced by performCalculations(), and SabrInterpolatedSmileSection().
std::vector<Volatility> QuantLib::SabrInterpolatedSmileSection::vols_ [mutable, protected]
Definition at line 119 of file sabrinterpolatedsmilesection.hpp.
Referenced by createInterpolation(), and performCalculations().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/sabrinterpolatedsmilesection.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/sabrinterpolatedsmilesection.cpp