QuantLib: QuantLib::ExtendedBlackScholesMertonProcess Class Reference
QuantLib::ExtendedBlackScholesMertonProcess Class Reference
experimental Black-Scholes-Merton stochastic process
#include <extendedblackscholesprocess.hpp>
Public Types
enum Discretization { Euler, Milstein, PredictorCorrector }
Public Member Functions
ExtendedBlackScholesMertonProcess (const Handle< Quote > &x0, const Handle< YieldTermStructure > &dividendTS, const Handle< YieldTermStructure > &riskFreeTS, const Handle< BlackVolTermStructure > &blackVolTS, const boost::shared_ptr< discretization > &d=boost::shared_ptr< discretization >(new EulerDiscretization), Discretization evolDisc=Milstein)
Real drift (Time t, Real x) const
Real diffusion (Time t, Real x) const
Real evolve (Time t0, Real x0, Time dt, Real dw) const
Private Attributes
const Discretization discretization_
Detailed Description
experimental Black-Scholes-Merton stochastic process
This class allows to choose a built-in discretization scheme
Definition at line 36 of file extendedblackscholesprocess.hpp.
Member Enumeration Documentation
enum QuantLib::ExtendedBlackScholesMertonProcess::Discretization
Enumerator:
Euler
Milstein
PredictorCorrector
Definition at line 39 of file extendedblackscholesprocess.hpp.
{ Euler, Milstein, PredictorCorrector };
Constructor & Destructor Documentation
QuantLib::ExtendedBlackScholesMertonProcess::ExtendedBlackScholesMertonProcess (const Handle< Quote > & x0, const Handle< YieldTermStructure > & dividendTS, const Handle< YieldTermStructure > & riskFreeTS, const Handle< BlackVolTermStructure > & blackVolTS, const boost::shared_ptr< discretization > & d = boost::shared_ptr<discretization>(new EulerDiscretization), Discretization evolDisc = Milstein)
Definition at line 24 of file extendedblackscholesprocess.cpp.
    : GeneralizedBlackScholesProcess(x0,dividendTS,riskFreeTS,blackVolTS,d),
      discretization_(evolDisc) {}
Member Function Documentation
Real QuantLib::ExtendedBlackScholesMertonProcess::diffusion (Time t, Real x) const [virtual]
Todo:
revise extrapolation
Reimplemented from QuantLib::GeneralizedBlackScholesProcess.
Definition at line 44 of file extendedblackscholesprocess.cpp.
References QuantLib::GeneralizedBlackScholesProcess::blackVolatility().
Referenced by drift(), and evolve().
{
        return blackVolatility()->blackVol(t, x, true);
    }
Real QuantLib::ExtendedBlackScholesMertonProcess::drift (Time t, Real x) const [virtual]
Todo:
revise extrapolation
Reimplemented from QuantLib::GeneralizedBlackScholesProcess.
Definition at line 34 of file extendedblackscholesprocess.cpp.
References QuantLib::Continuous, diffusion(), QuantLib::GeneralizedBlackScholesProcess::dividendYield(), QuantLib::NoFrequency, QuantLib::GeneralizedBlackScholesProcess::riskFreeRate(), and anonymous_namespace{distributions.cpp}::sigma.
Referenced by evolve().
{
        Real sigma = diffusion(t,x);
        // we could be more anticipatory if we know the right dt
        // for which the drift will be used
        Time t1 = t + 0.0001;
        return riskFreeRate()->forwardRate(t,t1,Continuous,NoFrequency,true)
             - dividendYield()->forwardRate(t,t1,Continuous,NoFrequency,true)
             - 0.5 * sigma * sigma;
    }
Real QuantLib::ExtendedBlackScholesMertonProcess::evolve (Time t0, Real x0, Time dt, Real dw) const [virtual]
returns the asset value after a time interval \(\Delta t \) according to the given discretization. By default, it returns
\[ E(x_0,t_0,\Delta t) + S(x_0,t_0,\Delta t) \cdot \Delta w \]
where \(E \) is the expectation and \(S \) the standard deviation.
Reimplemented from QuantLib::GeneralizedBlackScholesProcess.
Definition at line 48 of file extendedblackscholesprocess.cpp.
References QuantLib::GeneralizedBlackScholesProcess::apply(), QuantLib::Continuous, diffusion(), discretization_, QuantLib::GeneralizedBlackScholesProcess::dividendYield(), drift(), Euler, QuantLib::GeneralizedBlackScholesProcess::expectation(), Milstein, QuantLib::NoFrequency, QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow(), PredictorCorrector, QL_FAIL, QuantLib::GeneralizedBlackScholesProcess::riskFreeRate(), and QuantLib::StochasticProcess1D::stdDeviation().
{
        Real predictor, sigma0, sigma1;
        Time t1;
        Rate rate0, rate1;
        Real driftterm, diffusionterm, corrector;
        switch (discretization_) {
          case Milstein:
            // Milstein scheme
            return apply(x0, drift(t0, x0)*dt
                           + 0.5*std::pow(diffusion(t0, x0),2)*(dw*dw-1)*dt
                           + diffusion(t0,x0)*std::sqrt(dt)*dw);
            break;
          case Euler:
            // Usual Euler scheme
            return apply(expectation(t0,x0,dt), stdDeviation(t0,x0,dt)*dw);
            break;
          case PredictorCorrector:
            // Predictor-Corrector scheme with equal weighting
            predictor =
                apply(expectation(t0,x0,dt), stdDeviation(t0,x0,dt)*dw);
            t1 = t0 + 0.0001;
            sigma0 = diffusion(t0,x0);
            sigma1 = diffusion(t0+dt,predictor);
            rate0 =
                riskFreeRate()->forwardRate(t0,t1,Continuous,NoFrequency,true)
              - dividendYield()->forwardRate(t0,t1,Continuous,NoFrequency,true)
              - 0.5*std::pow(sigma0,2);
            rate1 =
                riskFreeRate()->forwardRate(t0+dt,t1+dt,Continuous,
                                            NoFrequency,true)
              - dividendYield()->forwardRate(t0+dt,t1+dt,
                                             Continuous,NoFrequency,true)
              - 0.5*std::pow(sigma1,2);
            driftterm = 0.5*rate1+0.5*rate0;
            diffusionterm = 0.5*(sigma1+sigma0);
            corrector =
                apply(x0,driftterm*dt+diffusionterm*std::sqrt(dt)*dw);
            return corrector;
            break;
          default:
            QL_FAIL("unknown discretization scheme");
        }
    }
Member Data Documentation
const Discretization QuantLib::ExtendedBlackScholesMertonProcess::discretization_ [private]
Reimplemented from QuantLib::StochasticProcess1D.
Definition at line 52 of file extendedblackscholesprocess.hpp.
Referenced by evolve().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/processes/extendedblackscholesprocess.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/processes/extendedblackscholesprocess.cpp