QuantLib: QuantLib::OneFactorCopula Class Reference
QuantLib::OneFactorCopula Class Reference
Abstract base class for one-factor copula models.
#include <onefactorcopula.hpp>
Public Member Functions
OneFactorCopula (const Handle< Quote > &correlation, Real maximum=5.0, Size integrationSteps=50, Real minimum=-5.0)
virtual Real density (Real m) const =0
Density function of M.
virtual Real cumulativeZ (Real z) const =0
Cumulative distribution of Z.
virtual Real cumulativeY (Real y) const
Cumulative distribution of Y.
virtual Real inverseCumulativeY (Real p) const
Inverse cumulative distribution of Y.
Real correlation () const
Single correlation parameter.
Real conditionalProbability (Real prob, Real m) const
Conditional probability.
std::vector< Real > conditionalProbability (const std::vector< Real > &prob, Real m) const
Vector of conditional probabilities.
Real integral (Real p) const
template<class F >
Real integral (const F &f, std::vector< Real > &probabilities) const
template<class F >
Distribution integral (const F &f, const std::vector< Real > &nominals, const std::vector< Real > &probabilities) const
int checkMoments (Real tolerance) const
Protected Member Functions
Size steps () const
Real dm (Size i) const
Real m (Size i) const
Real densitydm (Size i) const
Protected Attributes
Handle< Quote > correlation_
Real max_
Size steps_
Real min_
std::vector< Real > y_
std::vector< Real > cumulativeY_
Detailed Description
Abstract base class for one-factor copula models.
Reference: John Hull and Alan White, The Perfect Copula, June 2006
Let \(Q_i(t)\) be the cumulative probability of default of counterparty i before time t.
In a one-factor model, consider random variables
\[ Y_i = a_i\,M+\sqrt{1-a_i^2}\:Z_i \]
where \(M\) and \(Z_i\) have independent zero-mean unit-variance distributions and \(-1\leq a_i \leq 1\). The correlation between \(Y_i\) and \(Y_j\) is then \(a_i a_j\).
Let \(F_Y(y)\) be the cumulative distribution function of \(Y_i\). \(y\) is mapped to \(t\) such that percentiles match, i.e. \(F_Y(y)=Q_i(t)\) or \(y=F_Y^{-1}(Q_i(t))\).
Now let \(F_Z(z)\) be the cumulated distribution function of \(Z_i\). For given realization of \(M\), this determines the distribution of \(y\):
\[ Prob \,(Y_i < y|M) = F_Z \left(\frac{y-a_i\,M}{\sqrt{1-a_i^2}}\right) \qquad \mbox{or} \qquad Prob \,(t_i < t|M) = F_Z \left(\frac{F_Y^{-1}(Q_i(t))-a_i\,M} {\sqrt{1-a_i^2}} \right) \]
The distribution functions of \(M, Z_i \) are specified in derived classes. The distribution function of \(Y \) is then given by the convolution
\[ F_Y(y) = Prob\,(Y<y) = \int_{-\infty}^\infty\,\int_{-\infty}^{\infty}\: D_Z(z)\,D_M(m) \quad \Theta \left(y - a\,m - \sqrt{1-a^2}\,z\right)\,dm\,dz, \qquad \Theta (x) = \left\{ \begin{array}{ll} 1 & x \geq 0 \\ 0 & x < 0 \end{array}\right. \]
where \(D_Z(z) \) and \(D_M(m) \) are the probability densities of \(Z\) and \(M, \) respectively.
This convolution can also be written
\[ F(y) = Prob \,(Y < y) = \int_{-\infty}^\infty D_M(m)\,dm\: \int_{-\infty}^{g(y,a,m)} D_Z(z)\,dz, \qquad g(y,a,m) = \frac{y - a\cdot m}{\sqrt{1-a^2}}, \qquad a < 1 \]
or
\[ F(y) = Prob \,(Y < y) = \int_{-\infty}^\infty D_Z(z)\,dz\: \int_{-\infty}^{h(y,a,z)} D_M(m)\,dm, \qquad h(y,a,z) = \frac{y - \sqrt{1 - a^2}\cdot z}{a}, \qquad a > 0. \]
In general, \(F_Y(y) \) needs to be computed numerically.
Todo:
Improve on simple Euler integration
Definition at line 101 of file onefactorcopula.hpp.
Constructor & Destructor Documentation
QuantLib::OneFactorCopula::OneFactorCopula (const Handle< Quote > & correlation, Real maximum = 5.0, Size integrationSteps = 50, Real minimum = -5.0) [inline]
Definition at line 103 of file onefactorcopula.hpp.
References correlation_, QL_REQUIRE, and QuantLib::Observer::registerWith().
        : correlation_(correlation),
          max_(maximum), steps_(integrationSteps), min_(minimum) {
            QL_REQUIRE(correlation_->value() >= -1
                       && correlation_->value() <= 1,
                       "correlation out of range [-1, +1]");
            registerWith(correlation_);
        }
Member Function Documentation
int QuantLib::OneFactorCopula::checkMoments (Real tolerance) const
Check moments (unit norm, zero mean and unit variance) of the distributions of M, Z, and Y by numerically integrating the respective density. Parameter tolerance is the maximum tolerable absolute error.
Definition at line 99 of file onefactorcopula.cpp.
References QuantLib::anonymous_namespace{basisincompleteordered.cpp}::norm(), QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow(), and QL_REQUIRE.
{
    //-------------------------------------------------------------------------
        calculate ();
        Real norm = 0, mean = 0, var = 0;
        for (Size i = 0; i < steps(); i++) {
            norm += densitydm (i);
            mean += m(i) * densitydm (i);
            var += pow (m(i), 2) * densitydm (i);
        }
        QL_REQUIRE (fabs (norm - 1.0) < tolerance, "norm out of tolerance range");
        QL_REQUIRE (fabs (mean) < tolerance, "mean out of tolerance range");
        QL_REQUIRE (fabs (var - 1.0) < tolerance, "variance out of tolerance range");
        // FIXME: define range for Y via cutoff quantil?
        Real zMin = -10;
        Real zMax = +10;
        Size zSteps = 200;
        norm = 0;
        mean = 0;
        var = 0;
        for (Size i = 1; i < zSteps; i++) {
            Real z1 = zMin + (zMax - zMin) / zSteps * (i - 1);
            Real z2 = zMin + (zMax - zMin) / zSteps * i;
            Real z  = (z1 + z2) / 2;
            Real densitydz = cumulativeZ (z2) - cumulativeZ (z1);
            norm += densitydz;
            mean += z * densitydz;
            var += pow (z, 2) * densitydz;
        }
        QL_REQUIRE (fabs (norm - 1.0) < tolerance, "norm out of tolerance range");
        QL_REQUIRE (fabs (mean) < tolerance, "mean out of tolerance range");
        QL_REQUIRE (fabs (var - 1.0) < tolerance, "variance out of tolerance range");
        // FIXME: define range for Y via cutoff quantil?
        Real yMin = -10;
        Real yMax = +10;
        Size ySteps = 200;
        norm = 0;
        mean = 0;
        var = 0;
        for (Size i = 1; i < ySteps; i++) {
            Real y1 = yMin + (yMax - yMin) / ySteps * (i - 1);
            Real y2 = yMin + (yMax - yMin) / ySteps * i;
            Real y  = (y1 + y2) / 2;
            Real densitydy = cumulativeY (y2) - cumulativeY (y1);
            norm += densitydy;
            mean += y * densitydy;
            var += y * y * densitydy;
        }
        QL_REQUIRE (fabs (norm - 1.0) < tolerance, "norm out of tolerance range");
        QL_REQUIRE (fabs (mean) < tolerance, "mean out of tolerance range");
        QL_REQUIRE (fabs (var - 1.0) < tolerance, "variance out of tolerance range");
        return 0;
    }
Real QuantLib::OneFactorCopula::conditionalProbability (Real prob, Real m) const
Conditional probability.
\[ \hat p(m) = F_Z \left(\frac{F_Y^{-1}(p)-a\,m}{\sqrt{1-a^2}}\right) \]
Definition at line 27 of file onefactorcopula.cpp.
References anonymous_namespace{marketmodel.cpp}::c, and QL_REQUIRE.
Referenced by integral().
{
    //-------------------------------------------------------------------------
        calculate ();
        // FIXME
        if (p < 1e-10) return 0;
        Real c = correlation_->value();
        Real res = cumulativeZ ((inverseCumulativeY (p) - sqrt(c) * m)
                                / sqrt (1. - c));
        QL_REQUIRE (res >= 0 && res <= 1,
                    "conditional probability " << res << "out of range");
        return res;
    }
vector< Real > QuantLib::OneFactorCopula::conditionalProbability (const std::vector< Real > & prob, Real m) const
Vector of conditional probabilities.
\[ \hat p_i(m) = F_Z \left(\frac{F_Y^{-1}(p_i)-a\,m}{\sqrt{1-a^2}} \right) \]
Definition at line 45 of file onefactorcopula.cpp.
{
    //-------------------------------------------------------------------------
        calculate ();
        vector<Real> p (prob.size(), 0);
        for (Size i = 0; i < p.size(); i++)
            p[i] = conditionalProbability (prob[i], m);
        return p;
    }
Real QuantLib::OneFactorCopula::correlation () const [inline]
Single correlation parameter.
Definition at line 261 of file onefactorcopula.hpp.
References correlation_.
{
        return correlation_->value();
    }
Real QuantLib::OneFactorCopula::cumulativeY (Real y) const [virtual]
Cumulative distribution of Y.
This is the default implementation based on tabulated data. The table needs to be filled by derived classes. If analytic calculation is feasible, this method can also be overridden.
Reimplemented in QuantLib::OneFactorGaussianCopula.
Definition at line 57 of file onefactorcopula.cpp.
References QL_REQUIRE.
{
    //-------------------------------------------------------------------------
        calculate ();
        QL_REQUIRE (y_.size() > 0, "cumulative Y not tabulated yet");
        // linear interpolation on the tabulated cumulative distribution of Y
        if (y < y_.front())
            return cumulativeY_.front();
        for (Size i = 0; i < y_.size(); i++) {
            if (y_[i] > y)
                return (   (y_[i] - y)   * cumulativeY_[i-1]
                           + (y - y_[i-1]) * cumulativeY_[i]   )
                    / (y_[i] - y_[i-1]);
        }
        return cumulativeY_.back();
    }
virtual Real QuantLib::OneFactorCopula::cumulativeZ (Real z) const [pure virtual]
Cumulative distribution of Z.
Derived classes must override this method and ensure zero mean and unit variance.
Implemented in QuantLib::OneFactorStudentGaussianCopula, QuantLib::OneFactorGaussianStudentCopula, QuantLib::OneFactorStudentCopula, and QuantLib::OneFactorGaussianCopula.
virtual Real QuantLib::OneFactorCopula::density (Real m) const [pure virtual]
Density function of M.
Derived classes must override this method and ensure zero mean and unit variance.
Implemented in QuantLib::OneFactorStudentGaussianCopula, QuantLib::OneFactorGaussianStudentCopula, QuantLib::OneFactorStudentCopula, and QuantLib::OneFactorGaussianCopula.
Referenced by densitydm().
Real QuantLib::OneFactorCopula::densitydm (Size i) const [inline, protected]
Definition at line 278 of file onefactorcopula.hpp.
References density(), dm(), m(), QL_REQUIRE, and steps_.
Referenced by integral().
{
        QL_REQUIRE(i < steps_, "index out of range");
        return density(m(i)) * dm(i);
    }
Real QuantLib::OneFactorCopula::dm (Size i) const [inline, protected]
Definition at line 269 of file onefactorcopula.hpp.
References max_, min_, and steps_.
Referenced by QuantLib::OneFactorStudentCopula::cumulativeYintegral(), QuantLib::OneFactorGaussianStudentCopula::cumulativeYintegral(), QuantLib::OneFactorStudentGaussianCopula::cumulativeYintegral(), densitydm(), m(), and QuantLib::OneFactorGaussianCopula::testCumulativeY().
{
        return (max_ - min_)/ steps_;
    }
Real QuantLib::OneFactorCopula::integral (Real p) const [inline]
Integral over the density \(\rho(m) \) of M and the conditional probability related to p:
\[ \int_{-\infty}^\infty\,dm\,\rho(m)\, F_Z \left(\frac{F_Y^{-1}(p)-a\,m}{\sqrt{1-a^2}}\right) \]
Definition at line 167 of file onefactorcopula.hpp.
References QuantLib::LazyObject::calculate(), conditionalProbability(), densitydm(), m(), QL_REQUIRE, and steps().
{
            QL_REQUIRE(p >= 0 && p <= 1, "probability p=" << p
                       << " out of range [0,1]");
            calculate();
            Real avg = 0;
            for (Size k = 0; k < steps(); k++) {
                Real pp = conditionalProbability(p, m(k));
                avg += pp * densitydm(k);
            }
            return avg;
        }
template<class F > Real QuantLib::OneFactorCopula::integral (const F & f, std::vector< Real > & probabilities) const [inline]
Integral over the density \(\rho(m) \) of M and a one-dimensional function \(f \) of conditional probabilities related to the input vector of probabilities p:
\[ \int_{-\infty}^\infty\,dm\,\rho(m)\, f (\hat p_1, \hat p_2, \dots, \hat p_N), \qquad \hat p_i (m) = F_Z \left(\frac{F_Y^{-1}(p_i)-a\,m}{\sqrt{1-a^2}} \right) \]
Definition at line 192 of file onefactorcopula.hpp.
References QuantLib::LazyObject::calculate(), conditionalProbability(), densitydm(), anonymous_namespace{interpolations.cpp}::f(), m(), and steps_.
{
            calculate();
            Real avg = 0.0;
            for (Size i = 0; i < steps_; i++) {
                std::vector<Real> conditional
                    = conditionalProbability(probabilities, m(i));
                Real prob = f(conditional);
                avg += prob * densitydm(i);
            }
            return avg;
        }
template<class F > Distribution QuantLib::OneFactorCopula::integral (const F & f, const std::vector< Real > & nominals, const std::vector< Real > & probabilities) const [inline]
Integral over the density \(\rho(m) \) of M and a multi-dimensional function \(f \) of conditional probabilities related to the input vector of probabilities p:
\[ \int_{-\infty}^\infty\,dm\,\rho(m)\, f (\hat p_1, \hat p_2, \dots, \hat p_N), \qquad \hat p_i = F_Z \left(\frac{F_Y^{-1}(p_i)-a\,m}{\sqrt{1-a^2}}\right) \]
Definition at line 216 of file onefactorcopula.hpp.
References QuantLib::LazyObject::calculate(), conditionalProbability(), anonymous_namespace{marketmodel.cpp}::d, QuantLib::Distribution::density(), densitydm(), anonymous_namespace{interpolations.cpp}::f(), m(), and steps().
{
            calculate();
            Distribution dist(f.buckets(), 0.0, f.maximum());
            for (Size i = 0; i < steps(); i++) {
                std::vector<Real> conditional
                    = conditionalProbability(probabilities, m(i));
                Distribution d = f(nominals, conditional);
                for (Size j = 0; j < dist.size(); j++)
                    dist.addDensity(j, d.density(j) * densitydm(i));
            }
            return dist;
        }
Real QuantLib::OneFactorCopula::inverseCumulativeY (Real p) const [virtual]
Inverse cumulative distribution of Y.
This is the default implementation based on tabulated data. The table needs to be filled by derived classes. If analytic calculation is feasible, this method can also be overridden.
Reimplemented in QuantLib::OneFactorGaussianCopula.
Definition at line 78 of file onefactorcopula.cpp.
References QL_REQUIRE.
{
    //-------------------------------------------------------------------------
        calculate ();
        QL_REQUIRE (y_.size() > 0, "cumulative Y not tabulated yet");
        // linear interpolation on the tabulated cumulative distribution of Y
        if (x < cumulativeY_.front())
            return y_.front();
        for (Size i = 0; i < cumulativeY_.size(); i++) {
            if (cumulativeY_[i] > x)
                return (   (cumulativeY_[i] - x)   * y_[i-1]
                           + (x - cumulativeY_[i-1]) * y_[i]   )
                    / (cumulativeY_[i] - cumulativeY_[i-1]);
        }
        return y_.back();
    }
Real QuantLib::OneFactorCopula::m (Size i) const [inline, protected]
Definition at line 273 of file onefactorcopula.hpp.
References dm(), min_, QL_REQUIRE, and steps_.
Referenced by QuantLib::OneFactorStudentCopula::cumulativeYintegral(), QuantLib::OneFactorGaussianStudentCopula::cumulativeYintegral(), QuantLib::OneFactorStudentGaussianCopula::cumulativeYintegral(), densitydm(), integral(), and QuantLib::OneFactorGaussianCopula::testCumulativeY().
{
        QL_REQUIRE(i < steps_, "index out of range");
        return min_ + dm(i) * i + dm(i) / 2;
    }
Size QuantLib::OneFactorCopula::steps () const [inline, protected]
Definition at line 265 of file onefactorcopula.hpp.
References steps_.
Referenced by QuantLib::OneFactorStudentCopula::cumulativeYintegral(), QuantLib::OneFactorGaussianStudentCopula::cumulativeYintegral(), QuantLib::OneFactorStudentGaussianCopula::cumulativeYintegral(), integral(), QuantLib::OneFactorStudentCopula::performCalculations(), QuantLib::OneFactorGaussianStudentCopula::performCalculations(), QuantLib::OneFactorStudentGaussianCopula::performCalculations(), and QuantLib::OneFactorGaussianCopula::testCumulativeY().
{
        return steps_;
    }
Member Data Documentation
Handle<Quote> QuantLib::OneFactorCopula::correlation_ [protected]
Definition at line 240 of file onefactorcopula.hpp.
Referenced by correlation(), QuantLib::OneFactorStudentCopula::cumulativeYintegral(), QuantLib::OneFactorGaussianStudentCopula::cumulativeYintegral(), QuantLib::OneFactorStudentGaussianCopula::cumulativeYintegral(), OneFactorCopula(), QuantLib::OneFactorGaussianCopula::OneFactorGaussianCopula(), and QuantLib::OneFactorGaussianCopula::testCumulativeY().
std::vector<Real> QuantLib::OneFactorCopula::cumulativeY_ [mutable, protected]
Definition at line 247 of file onefactorcopula.hpp.
Referenced by QuantLib::OneFactorStudentCopula::performCalculations(), QuantLib::OneFactorGaussianStudentCopula::performCalculations(), and QuantLib::OneFactorStudentGaussianCopula::performCalculations().
Real QuantLib::OneFactorCopula::max_ [mutable, protected]
Definition at line 241 of file onefactorcopula.hpp.
Referenced by dm().
Real QuantLib::OneFactorCopula::min_ [mutable, protected]
Definition at line 243 of file onefactorcopula.hpp.
Referenced by dm(), and m().
Size QuantLib::OneFactorCopula::steps_ [mutable, protected]
Definition at line 242 of file onefactorcopula.hpp.
Referenced by densitydm(), dm(), integral(), m(), and steps().
std::vector<Real> QuantLib::OneFactorCopula::y_ [mutable, protected]
Definition at line 246 of file onefactorcopula.hpp.
Referenced by QuantLib::OneFactorStudentCopula::performCalculations(), QuantLib::OneFactorGaussianStudentCopula::performCalculations(), and QuantLib::OneFactorStudentGaussianCopula::performCalculations().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/onefactorcopula.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/onefactorcopula.cpp