QuantLib: QuantLib::ExtendedLeisenReimer Class Reference
QuantLib::ExtendedLeisenReimer Class Reference
Leisen & Reimer tree: multiplicative approach.
#include <extendedbinomialtree.hpp>
Public Member Functions
ExtendedLeisenReimer (const boost::shared_ptr< StochasticProcess1D > &, Time end, Size steps, Real strike)
Real underlying (Size i, Size index) const
Real probability (Size, Size, Size branch) const
Protected Attributes
Time end_
Size oddSteps_
Real strike_
Real up_
Real down_
Real pu_
Real pd_
Detailed Description
Leisen & Reimer tree: multiplicative approach.
Definition at line 212 of file extendedbinomialtree.hpp.
Constructor & Destructor Documentation
QuantLib::ExtendedLeisenReimer::ExtendedLeisenReimer (const boost::shared_ptr< StochasticProcess1D > & process, Time end, Size steps, Real strike)
Definition at line 163 of file extendedbinomialtree.cpp.
References down_, QuantLib::ExtendedBinomialTree< ExtendedLeisenReimer >::driftStep(), oddSteps_, pd_, QuantLib::PeizerPrattMethod2Inversion(), pu_, QL_REQUIRE, up_, and QuantLib::ExtendedBinomialTree< ExtendedLeisenReimer >::x0_.
    : ExtendedBinomialTree<ExtendedLeisenReimer>(process, end,
                                                 (steps%2 ? steps : steps+1)),
      end_(end), oddSteps_(steps%2 ? steps : steps+1), strike_(strike) {
        QL_REQUIRE(strike>0.0, "strike " << strike << "must be positive");
        Real variance = process->variance(0.0, x0_, end);
        Real ermqdt = std::exp(this->driftStep(0.0) + 0.5*variance/oddSteps_);
        Real d2 = (std::log(x0_/strike) + this->driftStep(0.0)*oddSteps_ ) /
            std::sqrt(variance);
        pu_ = PeizerPrattMethod2Inversion(d2, oddSteps_);
        pd_ = 1.0 - pu_;
        Real pdash = PeizerPrattMethod2Inversion(d2+std::sqrt(variance),
                                                 oddSteps_);
        up_ = ermqdt * pdash / pu_;
        down_ = (ermqdt - pu_ * up_) / (1.0 - pu_);
    }
Member Function Documentation
Real QuantLib::ExtendedLeisenReimer::probability (Size i, Size , Size branch) const
Definition at line 203 of file extendedbinomialtree.cpp.
References QuantLib::ExtendedBinomialTree< ExtendedLeisenReimer >::driftStep(), QuantLib::ExtendedBinomialTree< ExtendedLeisenReimer >::dt_, end_, oddSteps_, QuantLib::PeizerPrattMethod2Inversion(), strike_, QuantLib::ExtendedBinomialTree< ExtendedLeisenReimer >::treeProcess_, and QuantLib::ExtendedBinomialTree< ExtendedLeisenReimer >::x0_.
{
        Time stepTime = i*this->dt_;
        Real variance = this->treeProcess_->variance(stepTime, x0_, end_);
        Real d2 = (std::log(x0_/strike_) + this->driftStep(stepTime)*oddSteps_ ) /
            std::sqrt(variance);
        Real pu = PeizerPrattMethod2Inversion(d2, oddSteps_);
        Real pd = 1.0 - pu;
        return (branch == 1 ? pu : pd);
    }
Real QuantLib::ExtendedLeisenReimer::underlying (Size i, Size index) const
Definition at line 186 of file extendedbinomialtree.cpp.
References QuantLib::ExtendedBinomialTree< ExtendedLeisenReimer >::driftStep(), QuantLib::ExtendedBinomialTree< ExtendedLeisenReimer >::dt_, end_, oddSteps_, QuantLib::PeizerPrattMethod2Inversion(), QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow(), strike_, QuantLib::ExtendedBinomialTree< ExtendedLeisenReimer >::treeProcess_, and QuantLib::ExtendedBinomialTree< ExtendedLeisenReimer >::x0_.
{
        Time stepTime = i*this->dt_;
        Real variance = this->treeProcess_->variance(stepTime, x0_, end_);
        Real ermqdt = std::exp(this->driftStep(stepTime) + 0.5*variance/oddSteps_);
        Real d2 = (std::log(x0_/strike_) + this->driftStep(stepTime)*oddSteps_ ) /
            std::sqrt(variance);
        Real pu = PeizerPrattMethod2Inversion(d2, oddSteps_);
        Real pdash = PeizerPrattMethod2Inversion(d2+std::sqrt(variance),
            oddSteps_);
        Real up = ermqdt * pdash / pu;
        Real down = (ermqdt - pu * up) / (1.0 - pu);
        return x0_ * std::pow(down, Real(BigInteger(i)-BigInteger(index)))
            * std::pow(up, Real(index));
    }
Member Data Documentation
Real QuantLib::ExtendedLeisenReimer::down_ [protected]
Definition at line 225 of file extendedbinomialtree.hpp.
Referenced by ExtendedLeisenReimer().
Time QuantLib::ExtendedLeisenReimer::end_ [protected]
Definition at line 223 of file extendedbinomialtree.hpp.
Referenced by probability(), and underlying().
Size QuantLib::ExtendedLeisenReimer::oddSteps_ [protected]
Definition at line 224 of file extendedbinomialtree.hpp.
Referenced by ExtendedLeisenReimer(), probability(), and underlying().
Real QuantLib::ExtendedLeisenReimer::pd_ [protected]
Definition at line 225 of file extendedbinomialtree.hpp.
Referenced by ExtendedLeisenReimer().
Real QuantLib::ExtendedLeisenReimer::pu_ [protected]
Definition at line 225 of file extendedbinomialtree.hpp.
Referenced by ExtendedLeisenReimer().
Real QuantLib::ExtendedLeisenReimer::strike_ [protected]
Definition at line 225 of file extendedbinomialtree.hpp.
Referenced by probability(), and underlying().
Real QuantLib::ExtendedLeisenReimer::up_ [protected]
Definition at line 225 of file extendedbinomialtree.hpp.
Referenced by ExtendedLeisenReimer().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/lattices/extendedbinomialtree.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/lattices/extendedbinomialtree.cpp