QuantLib: QuantLib::Instrument Class Reference
QuantLib::Instrument Class Reference
Abstract instrument class.
#include <instrument.hpp>
Classes
class results
Public Member Functions
Instrument ()
virtual void setupArguments (PricingEngine::arguments *) const
virtual void fetchResults (const PricingEngine::results *) const
Inspectors
Real NPV () const
returns the net present value of the instrument.
Real errorEstimate () const
returns the error estimate on the NPV when available.
const Date & valuationDate () const
returns the date the net present value refers to.
template<typename T >
T result (const std::string &tag) const
returns any additional result returned by the pricing engine.
const std::map< std::string,
boost::any > & additionalResults () const
returns all additional result returned by the pricing engine.
virtual bool isExpired () const =0
returns whether the instrument might have value greater than zero.
Modifiers
void setPricingEngine (const boost::shared_ptr< PricingEngine > &)
set the pricing engine to be used.
Protected Member Functions
Calculations
void calculate () const
virtual void setupExpired () const
virtual void performCalculations () const
Protected Attributes
boost::shared_ptr< PricingEngine > engine_
Results
The value of this attribute and any other that derived classes might declare must be set during calculation.
Real NPV_
Real errorEstimate_
Date valuationDate_
std::map< std::string, boost::any > additionalResults_
Detailed Description
Abstract instrument class.
This class is purely abstract and defines the interface of concrete instruments which will be derived from this one.
Test:
observability of class instances is checked.
Definition at line 44 of file instrument.hpp.
Constructor & Destructor Documentation
QuantLib::Instrument::Instrument () [inline]
Definition at line 129 of file instrument.hpp.
    : NPV_(Null<Real>()), errorEstimate_(Null<Real>()),
      valuationDate_(Date()) {}
Member Function Documentation
const std::map< std::string, boost::any > & QuantLib::Instrument::additionalResults () const [inline]
returns all additional result returned by the pricing engine.
Definition at line 217 of file instrument.hpp.
References additionalResults_.
{
        return additionalResults_;
    }
void QuantLib::Instrument::calculate () const [inline, protected, virtual]
This method performs all needed calculations by calling the performCalculations method.
Warning:
Objects cache the results of the previous calculation. Such results will be returned upon later invocations of calculate. When the results depend on arguments which could change between invocations, the lazy object must register itself as observer of such objects for the calculations to be performed again when they change.
Should this method be redefined in derived classes, LazyObject::calculate() should be called in the overriding method.
Reimplemented from QuantLib::LazyObject.
Definition at line 148 of file instrument.hpp.
References QuantLib::LazyObject::calculated_, isExpired(), and setupExpired().
Referenced by QuantLib::BMASwap::bmaLegBPS(), QuantLib::BMASwap::bmaLegNPV(), QuantLib::CreditDefaultSwap::couponLegBPS(), QuantLib::CreditDefaultSwap::couponLegNPV(), QuantLib::CreditDefaultSwap::defaultLegNPV(), QuantLib::OneAssetOption::delta(), QuantLib::MultiAssetOption::delta(), QuantLib::MargrabeOption::delta1(), QuantLib::MargrabeOption::delta2(), QuantLib::OneAssetOption::deltaForward(), QuantLib::MultiAssetOption::dividendRho(), QuantLib::OneAssetOption::dividendRho(), QuantLib::OneAssetOption::elasticity(), QuantLib::Swap::endDiscounts(), QuantLib::SyntheticCDO::error(), QuantLib::CDO::error(), errorEstimate(), QuantLib::SyntheticCDO::expectedTrancheLoss(), QuantLib::AssetSwap::fairCleanPrice(), QuantLib::AssetSwap::fairNonParRepayment(), QuantLib::NthToDefault::fairPremium(), QuantLib::SyntheticCDO::fairPremium(), QuantLib::CDO::fairPremium(), QuantLib::YearOnYearInflationSwap::fairRate(), QuantLib::OvernightIndexedSwap::fairRate(), QuantLib::CPISwap::fairRate(), QuantLib::VanillaSwap::fairRate(), QuantLib::RiskyAssetSwap::fairSpread(), QuantLib::AssetSwap::fairSpread(), QuantLib::YearOnYearInflationSwap::fairSpread(), QuantLib::OvernightIndexedSwap::fairSpread(), QuantLib::CPISwap::fairSpread(), QuantLib::VanillaSwap::fairSpread(), QuantLib::CreditDefaultSwap::fairSpread(), QuantLib::CreditDefaultSwap::fairUpfront(), QuantLib::SyntheticCDO::fairUpfrontPremium(), QuantLib::OvernightIndexedSwap::fixedLegBPS(), QuantLib::VanillaSwap::fixedLegBPS(), QuantLib::YearOnYearInflationSwap::fixedLegNPV(), QuantLib::OvernightIndexedSwap::fixedLegNPV(), QuantLib::CPISwap::fixedLegNPV(), QuantLib::VanillaSwap::fixedLegNPV(), QuantLib::ZeroCouponInflationSwap::fixedLegNPV(), QuantLib::AssetSwap::floatingLegBPS(), QuantLib::VanillaSwap::floatingLegBPS(), QuantLib::AssetSwap::floatingLegNPV(), QuantLib::VanillaSwap::floatingLegNPV(), QuantLib::CPISwap::floatLegNPV(), QuantLib::ForwardRateAgreement::forwardRate(), QuantLib::Forward::forwardValue(), QuantLib::MultiAssetOption::gamma(), QuantLib::OneAssetOption::gamma(), QuantLib::MargrabeOption::gamma1(), QuantLib::MargrabeOption::gamma2(), QuantLib::DividendVanillaOption::impliedVolatility(), QuantLib::BarrierOption::impliedVolatility(), QuantLib::VanillaOption::impliedVolatility(), QuantLib::CdsOption::impliedVolatility(), QuantLib::CallableBond::impliedVolatility(), QuantLib::ZeroCouponInflationSwap::inflationLegNPV(), QuantLib::OneAssetOption::itmCashProbability(), QuantLib::Swap::legBPS(), QuantLib::Swap::legNPV(), QuantLib::BMASwap::liborLegBPS(), QuantLib::BMASwap::liborLegNPV(), NPV(), QuantLib::Swap::npvDateDiscount(), QuantLib::OvernightIndexedSwap::overnightLegBPS(), QuantLib::OvernightIndexedSwap::overnightLegNPV(), QuantLib::SyntheticCDO::premiumLegNPV(), QuantLib::SyntheticCDO::premiumValue(), QuantLib::CDO::premiumValue(), QuantLib::SyntheticCDO::protectionLegNPV(), QuantLib::SyntheticCDO::protectionValue(), QuantLib::CDO::protectionValue(), QuantLib::QuantoForwardVanillaOption::qlambda(), QuantLib::QuantoBarrierOption::qlambda(), QuantLib::QuantoVanillaOption::qlambda(), QuantLib::QuantoForwardVanillaOption::qrho(), QuantLib::QuantoBarrierOption::qrho(), QuantLib::QuantoVanillaOption::qrho(), QuantLib::QuantoForwardVanillaOption::qvega(), QuantLib::QuantoBarrierOption::qvega(), QuantLib::QuantoVanillaOption::qvega(), QuantLib::SyntheticCDO::remainingNotional(), result(), QuantLib::MultiAssetOption::rho(), QuantLib::OneAssetOption::rho(), QuantLib::CdsOption::riskyAnnuity(), QuantLib::Bond::settlementValue(), QuantLib::ForwardRateAgreement::spotValue(), QuantLib::Swap::startDiscounts(), QuantLib::OneAssetOption::strikeSensitivity(), QuantLib::MultiAssetOption::theta(), QuantLib::OneAssetOption::theta(), QuantLib::OneAssetOption::thetaPerDay(), QuantLib::CreditDefaultSwap::upfrontBPS(), QuantLib::CreditDefaultSwap::upfrontNPV(), valuationDate(), QuantLib::VarianceSwap::variance(), QuantLib::MultiAssetOption::vega(), QuantLib::OneAssetOption::vega(), QuantLib::EverestOption::yield(), and QuantLib::YearOnYearInflationSwap::yoyLegNPV().
{
        if (isExpired()) {
            setupExpired();
            calculated_ = true;
        } else {
            LazyObject::calculate();
        }
    }
Real QuantLib::Instrument::errorEstimate () const [inline]
returns the error estimate on the NPV when available.
Definition at line 192 of file instrument.hpp.
References calculate(), errorEstimate_, and QL_REQUIRE.
Referenced by MCLongstaffSchwartzEngineTest::testAmericanMaxOption(), MCLongstaffSchwartzEngineTest::testAmericanOption(), HybridHestonHullWhiteProcessTest::testAnalyticHestonHullWhitePricing(), HimalayaOptionTest::testCached(), EverestOptionTest::testCached(), PagodaOptionTest::testCached(), HybridHestonHullWhiteProcessTest::testDiscretizationError(), HestonModelTest::testKahlJaeckelCase(), HybridHestonHullWhiteProcessTest::testMcPureHestonPricing(), HybridHestonHullWhiteProcessTest::testMcVanillaPricing(), HestonModelTest::testMcVsCached(), and BasketOptionTest::testTavellaValues().
{
        calculate();
        QL_REQUIRE(errorEstimate_ != Null<Real>(),
                   "error estimate not provided");
        return errorEstimate_;
    }
void QuantLib::Instrument::fetchResults (const PricingEngine::results * r) const [inline, virtual]
When a derived result structure is defined for an instrument, this method should be overridden to read from it. This is mandatory in case a pricing engine is used.
Reimplemented in QuantLib::Bond, QuantLib::SyntheticCDO, QuantLib::CPISwap, QuantLib::CreditDefaultSwap, QuantLib::ZeroCouponInflationSwap, QuantLib::VanillaSwap, QuantLib::YearOnYearInflationSwap, QuantLib::EnergyCommodity, QuantLib::CPICapFloor, QuantLib::AssetSwap, QuantLib::CdsOption, QuantLib::VarianceSwap, QuantLib::QuantoVanillaOption, QuantLib::Swap, QuantLib::OneAssetOption, QuantLib::ForwardVanillaOption, QuantLib::MultiAssetOption, QuantLib::QuantoBarrierOption, QuantLib::MargrabeOption, QuantLib::QuantoForwardVanillaOption, and QuantLib::EverestOption.
Definition at line 172 of file instrument.hpp.
References QuantLib::Instrument::results::additionalResults, additionalResults_, QuantLib::Instrument::results::errorEstimate, errorEstimate_, NPV_, QL_ENSURE, QuantLib::Instrument::results::valuationDate, valuationDate_, and QuantLib::Instrument::results::value.
Referenced by performCalculations().
{
        const Instrument::results* results =
            dynamic_cast<const Instrument::results*>(r);
        QL_ENSURE(results != 0,
                  "no results returned from pricing engine");
        NPV_ = results->value;
        errorEstimate_ = results->errorEstimate;
        valuationDate_ = results->valuationDate;
        additionalResults_ = results->additionalResults;
    }
virtual bool QuantLib::Instrument::isExpired () const [pure virtual]
returns whether the instrument might have value greater than zero.
Implemented in QuantLib::CDO, QuantLib::CreditDefaultSwap, QuantLib::SyntheticCDO, QuantLib::CPICapFloor, QuantLib::Bond, QuantLib::ForwardRateAgreement, QuantLib::NthToDefault, QuantLib::Forward, QuantLib::Swaption, QuantLib::RiskyBond, QuantLib::YoYInflationCapFloor, QuantLib::CapFloor, QuantLib::VanillaSwingOption, QuantLib::CompositeInstrument, QuantLib::RiskyAssetSwap, QuantLib::Swap, QuantLib::CdsOption, QuantLib::WriterExtensibleOption, QuantLib::VarianceSwap, QuantLib::EnergyVanillaSwap, QuantLib::VarianceOption, QuantLib::PathMultiAssetOption, QuantLib::VanillaStorageOption, QuantLib::EnergySwap, QuantLib::VanillaVPPOption, QuantLib::MultiAssetOption, QuantLib::OneAssetOption, QuantLib::EnergyFuture, QuantLib::RiskyAssetSwapOption, and QuantLib::Stock.
Referenced by calculate().
Real QuantLib::Instrument::NPV () const [inline]
returns the net present value of the instrument.
Definition at line 186 of file instrument.hpp.
References calculate(), NPV_, and QL_REQUIRE.
Referenced by QuantLib::AnalyticAmericanMargrabeEngine::calculate(), QuantLib::FdHestonHullWhiteVanillaEngine::calculate(), QuantLib::CapHelper::CapHelper(), QuantLib::ReplicatingVarianceSwapEngine::computeReplicatingPortfolio(), CPISwapTest::consistency(), CPISwapTest::cpibondconsistency(), InflationCPICapFloorTest::cpicapfloorpricer(), QuantLib::BMASwap::fairLiborSpread(), anonymous_namespace{swaptionvolatilitymatrix.cpp}::CommonVars::makeCoherenceTest(), HestonModelTest::testAlanLewisReferencePrices(), MargrabeOptionTest::testAmericanExchangeTwoAssets(), MCLongstaffSchwartzEngineTest::testAmericanMaxOption(), MCLongstaffSchwartzEngineTest::testAmericanOption(), BatesModelTest::testAnalyticAndMcVsJumpDiffusion(), LookbackOptionTest::testAnalyticContinuousFixedLookback(), LookbackOptionTest::testAnalyticContinuousFloatingLookback(), AsianOptionTest::testAnalyticContinuousGeometricAveragePrice(), AsianOptionTest::testAnalyticContinuousGeometricAveragePriceGreeks(), AsianOptionTest::testAnalyticDiscreteGeometricAveragePrice(), AsianOptionTest::testAnalyticDiscreteGeometricAveragePriceGreeks(), AsianOptionTest::testAnalyticDiscreteGeometricAverageStrike(), HybridHestonHullWhiteProcessTest::testAnalyticHestonHullWhitePricing(), HestonModelTest::testAnalyticPiecewiseTimeDependent(), ChooserOptionTest::testAnalyticSimpleChooserEngine(), BatesModelTest::testAnalyticVsBlack(), HestonModelTest::testAnalyticVsBlack(), HestonModelTest::testAnalyticVsCached(), BatesModelTest::testAnalyticVsMCPricing(), WriterExtensibleOptionTest::testAnalyticWriterExtensibleOptionEngine(), DigitalOptionTest::testAssetAtExpiryOrNothingAmericanValues(), DigitalOptionTest::testAssetAtHitOrNothingAmericanValues(), DigitalCouponTest::testAssetOrNothing(), DigitalOptionTest::testAssetOrNothingEuropeanValues(), BarrierOptionTest::testBabsiriValues(), AmericanOptionTest::testBaroneAdesiWhaleyValues(), BasketOptionTest::testBarraquandThreeValues(), QuantoOptionTest::testBarrierValues(), BarrierOptionTest::testBeagleholeValues(), AmericanOptionTest::testBjerksundStenslandValues(), ConvertibleBondTest::testBond(), HybridHestonHullWhiteProcessTest::testBsmHullWhiteEngine(), EverestOptionTest::testCached(), HimalayaOptionTest::testCached(), PagodaOptionTest::testCached(), CdsOptionTest::testCached(), CreditDefaultSwapTest::testCachedMarketValue(), CreditDefaultSwapTest::testCachedValue(), BermudanSwaptionTest::testCachedValues(), DigitalOptionTest::testCashAtExpiryOrNothingAmericanValues(), DigitalOptionTest::testCashAtHitOrNothingAmericanGreeks(), DigitalOptionTest::testCashAtHitOrNothingAmericanValues(), DigitalCouponTest::testCashOrNothing(), DigitalOptionTest::testCashOrNothingEuropeanValues(), HybridHestonHullWhiteProcessTest::testCompareBsmHWandHestonHW(), InflationCapFloorTest::testConsistency(), CapFloorTest::testConsistency(), FdmLinearOpTest::testCrankNicolsonWithDamping(), CapFlooredCouponTest::testDecomposition(), InflationCapFlooredCouponTest::testDecomposition(), HestonModelTest::testDifferentIntegrals(), HybridHestonHullWhiteProcessTest::testDiscretizationError(), GJRGARCHModelTest::testEngines(), MargrabeOptionTest::testEuroExchangeTwoAssets(), DividendOptionTest::testEuropeanEndLimit(), DividendOptionTest::testEuropeanGreeks(), DividendOptionTest::testEuropeanKnownValue(), DividendOptionTest::testEuropeanStartLimit(), DividendOptionTest::testEuropeanValues(), BasketOptionTest::testEuroTwoValues(), SwingOptionTest::testExtOUJumpSwingOption(), SwingOptionTest::testExtOUJumpVanillaEngine(), CreditDefaultSwapTest::testFairSpread(), CreditDefaultSwapTest::testFairUpfront(), SwingOptionTest::testFdBSSwingOption(), anonymous_namespace{dividendoption.cpp}::testFdDegenerate(), DividendOptionTest::testFdEuropeanValues(), anonymous_namespace{americanoption.cpp}::testFdGreeks(), anonymous_namespace{dividendoption.cpp}::testFdGreeks(), FdHestonTest::testFdmHestonAmerican(), FdHestonTest::testFdmHestonBarrier(), FdHestonTest::testFdmHestonBarrierVsBlackScholes(), FdHestonTest::testFdmHestonBlackScholes(), FdHestonTest::testFdmHestonConvergence(), FdHestonTest::testFdmHestonEuropeanWithDividends(), HybridHestonHullWhiteProcessTest::testFdmHestonHullWhiteEngine(), FdHestonTest::testFdmHestonIkonenToivanen(), AmericanOptionTest::testFdValues(), HestonModelTest::testFdVanillaVsCached(), QuantoOptionTest::testForwardGreeks(), anonymous_namespace{forwardoption.cpp}::testForwardGreeks(), QuantoOptionTest::testForwardPerformanceValues(), QuantoOptionTest::testForwardValues(), DigitalOptionTest::testGapEuropeanValues(), MargrabeOptionTest::testGreeks(), JumpDiffusionTest::testGreeks(), EuropeanOptionTest::testGreeks(), QuantoOptionTest::testGreeks(), BarrierOptionTest::testHaugValues(), CreditDefaultSwapTest::testImpliedHazardRate(), SwapTest::testInArrears(), InflationCapFlooredCouponTest::testInstrumentEquality(), VarianceOptionTest::testIntegralHeston(), AmericanOptionTest::testJuValues(), HestonModelTest::testKahlJaeckelCase(), SpreadOptionTest::testKirkEngine(), VPPTest::testKlugeExtOUSpreadOption(), CapFlooredCouponTest::testLargeRates(), AsianOptionTest::testLevyEngine(), BarrierOptionTest::testLocalVolAndHestonComparison(), EuropeanOptionTest::testLocalVolatility(), DigitalOptionTest::testMCCashAtHit(), AsianOptionTest::testMCDiscreteArithmeticAveragePrice(), AsianOptionTest::testMCDiscreteArithmeticAverageStrike(), AsianOptionTest::testMCDiscreteGeometricAveragePrice(), CliquetOptionTest::testMcPerformance(), HybridHestonHullWhiteProcessTest::testMcPureHestonPricing(), HybridHestonHullWhiteProcessTest::testMcVanillaPricing(), HestonModelTest::testMcVsCached(), JumpDiffusionTest::testMerton76(), HestonModelTest::testMultipleStrikesEngine(), BasketOptionTest::testOddSamples(), BasketOptionTest::testOneDAmericanValues(), ConvertibleBondTest::testOption(), anonymous_namespace{cliquetoption.cpp}::testOptionGreeks(), InflationCapFloorTest::testParity(), AsianOptionTest::testPastFixings(), ForwardOptionTest::testPerformanceValues(), BarrierOptionTest::testPerturbative(), EuropeanOptionTest::testPriceCurve(), CompoundOptionTest::testPutCallParity(), ConvertibleBondTest::testRegression(), VPPTest::testSimpleExtOUStorageEngine(), ShortRateModelTest::testSwaps(), BasketOptionTest::testTavellaValues(), ForwardOptionTest::testValues(), CompoundOptionTest::testValues(), CliquetOptionTest::testValues(), EuropeanOptionTest::testValues(), QuantoOptionTest::testValues(), VPPTest::testVPPPricing(), InflationTest::testYYTermStructure(), InflationTest::testZeroTermStructure(), and CPISwapTest::zciisconsistency().
{
        calculate();
        QL_REQUIRE(NPV_ != Null<Real>(), "NPV not provided");
        return NPV_;
    }
void QuantLib::Instrument::performCalculations () const [inline, protected, virtual]
In case a pricing engine is not used, this method must be overridden to perform the actual calculations and set any needed results. In case a pricing engine is used, the default implementation can be used.
Implements QuantLib::LazyObject.
Reimplemented in QuantLib::CDO, QuantLib::FixedRateBondForward, QuantLib::Forward, QuantLib::ForwardRateAgreement, QuantLib::NthToDefault, QuantLib::RiskyBond, QuantLib::ConvertibleBond, QuantLib::CompositeInstrument, QuantLib::EnergyVanillaSwap, QuantLib::EnergyBasisSwap, QuantLib::RiskyAssetSwap, QuantLib::EnergyFuture, QuantLib::RiskyAssetSwapOption, and QuantLib::Stock.
Definition at line 163 of file instrument.hpp.
References engine_, fetchResults(), QL_REQUIRE, and setupArguments().
{
        QL_REQUIRE(engine_, "null pricing engine");
        engine_->reset();
        setupArguments(engine_->getArguments());
        engine_->getArguments()->validate();
        engine_->calculate();
        fetchResults(engine_->getResults());
    }
template<class T > T QuantLib::Instrument::result (const std::string & tag) const [inline]
returns any additional result returned by the pricing engine.
Definition at line 207 of file instrument.hpp.
References additionalResults_, calculate(), and QL_REQUIRE.
Referenced by EuropeanOptionTest::testPriceCurve().
{
        calculate();
        std::map<std::string,boost::any>::const_iterator value =
            additionalResults_.find(tag);
        QL_REQUIRE(value != additionalResults_.end(),
                   tag << " not provided");
        return boost::any_cast<T>(value->second);
    }
void QuantLib::Instrument::setPricingEngine (const boost::shared_ptr< PricingEngine > & e) [inline]
set the pricing engine to be used.
Warning:
calling this method will have no effects in case the performCalculation method was overridden in a derived class.
Definition at line 133 of file instrument.hpp.
References engine_, QuantLib::Observer::registerWith(), QuantLib::Observer::unregisterWith(), and QuantLib::LazyObject::update().
Referenced by QuantLib::LfmSwaptionEngine::calculate(), QuantLib::AnalyticAmericanMargrabeEngine::calculate(), QuantLib::G2SwaptionEngine::calculate(), QuantLib::BlackSwaptionEngine::calculate(), QuantLib::FdHestonHullWhiteVanillaEngine::calculate(), QuantLib::CapHelper::CapHelper(), QuantLib::ReplicatingVarianceSwapEngine::computeReplicatingPortfolio(), CPISwapTest::consistency(), CPISwapTest::cpibondconsistency(), InflationCPICapFloorTest::cpicapfloorpricer(), QuantLib::InterpolatedYoYOptionletStripper< Interpolator1D >::ObjectiveFunction::ObjectiveFunction(), QuantLib::MakeCms::operator boost::shared_ptr< Swap >(), QuantLib::PathMultiAssetOption::PathMultiAssetOption(), QuantLib::SwaptionHelper::SwaptionHelper(), HestonModelTest::testAlanLewisReferencePrices(), MargrabeOptionTest::testAmericanExchangeTwoAssets(), MCLongstaffSchwartzEngineTest::testAmericanMaxOption(), MCLongstaffSchwartzEngineTest::testAmericanOption(), BatesModelTest::testAnalyticAndMcVsJumpDiffusion(), LookbackOptionTest::testAnalyticContinuousFixedLookback(), LookbackOptionTest::testAnalyticContinuousFloatingLookback(), AsianOptionTest::testAnalyticContinuousGeometricAveragePrice(), AsianOptionTest::testAnalyticContinuousGeometricAveragePriceGreeks(), AsianOptionTest::testAnalyticDiscreteGeometricAveragePrice(), AsianOptionTest::testAnalyticDiscreteGeometricAveragePriceGreeks(), AsianOptionTest::testAnalyticDiscreteGeometricAverageStrike(), HybridHestonHullWhiteProcessTest::testAnalyticHestonHullWhitePricing(), HestonModelTest::testAnalyticPiecewiseTimeDependent(), ChooserOptionTest::testAnalyticSimpleChooserEngine(), BatesModelTest::testAnalyticVsBlack(), HestonModelTest::testAnalyticVsBlack(), HestonModelTest::testAnalyticVsCached(), BatesModelTest::testAnalyticVsMCPricing(), WriterExtensibleOptionTest::testAnalyticWriterExtensibleOptionEngine(), DigitalOptionTest::testAssetAtExpiryOrNothingAmericanValues(), DigitalOptionTest::testAssetAtHitOrNothingAmericanValues(), DigitalCouponTest::testAssetOrNothing(), DigitalOptionTest::testAssetOrNothingEuropeanValues(), BarrierOptionTest::testBabsiriValues(), AmericanOptionTest::testBaroneAdesiWhaleyValues(), BasketOptionTest::testBarraquandThreeValues(), QuantoOptionTest::testBarrierValues(), BarrierOptionTest::testBeagleholeValues(), AmericanOptionTest::testBjerksundStenslandValues(), ConvertibleBondTest::testBond(), anonymous_namespace{defaultprobabilitycurves.cpp}::testBootstrapFromSpread(), anonymous_namespace{defaultprobabilitycurves.cpp}::testBootstrapFromUpfront(), HybridHestonHullWhiteProcessTest::testBsmHullWhiteEngine(), PagodaOptionTest::testCached(), EverestOptionTest::testCached(), HimalayaOptionTest::testCached(), CdsOptionTest::testCached(), BondTest::testCached(), BondTest::testCachedFixed(), BondTest::testCachedFloating(), CreditDefaultSwapTest::testCachedMarketValue(), CreditDefaultSwapTest::testCachedValue(), BermudanSwaptionTest::testCachedValues(), BondTest::testCachedZero(), DigitalOptionTest::testCashAtExpiryOrNothingAmericanValues(), DigitalOptionTest::testCashAtHitOrNothingAmericanGreeks(), DigitalOptionTest::testCashAtHitOrNothingAmericanValues(), DigitalCouponTest::testCashOrNothing(), DigitalOptionTest::testCashOrNothingEuropeanValues(), HybridHestonHullWhiteProcessTest::testCompareBsmHWandHestonHW(), AssetSwapTest::testConsistency(), InflationCapFloorTest::testConsistency(), CapFloorTest::testConsistency(), FdmLinearOpTest::testCrankNicolsonWithDamping(), anonymous_namespace{piecewiseyieldcurve.cpp}::testCurveConsistency(), CapFlooredCouponTest::testDecomposition(), InflationCapFlooredCouponTest::testDecomposition(), HestonModelTest::testDifferentIntegrals(), HybridHestonHullWhiteProcessTest::testDiscretizationError(), GJRGARCHModelTest::testEngines(), MargrabeOptionTest::testEuroExchangeTwoAssets(), DividendOptionTest::testEuropeanEndLimit(), DividendOptionTest::testEuropeanGreeks(), DividendOptionTest::testEuropeanKnownValue(), DividendOptionTest::testEuropeanStartLimit(), DividendOptionTest::testEuropeanValues(), BasketOptionTest::testEuroTwoValues(), SwingOptionTest::testExtOUJumpSwingOption(), SwingOptionTest::testExtOUJumpVanillaEngine(), CreditDefaultSwapTest::testFairSpread(), CreditDefaultSwapTest::testFairUpfront(), SwingOptionTest::testFdBSSwingOption(), anonymous_namespace{dividendoption.cpp}::testFdDegenerate(), DividendOptionTest::testFdEuropeanValues(), anonymous_namespace{americanoption.cpp}::testFdGreeks(), anonymous_namespace{dividendoption.cpp}::testFdGreeks(), FdHestonTest::testFdmHestonAmerican(), FdHestonTest::testFdmHestonBarrier(), FdHestonTest::testFdmHestonBarrierVsBlackScholes(), FdHestonTest::testFdmHestonBlackScholes(), FdHestonTest::testFdmHestonConvergence(), FdHestonTest::testFdmHestonEuropeanWithDividends(), HybridHestonHullWhiteProcessTest::testFdmHestonHullWhiteEngine(), FdmLinearOpTest::testFdmHestonHullWhiteOp(), FdHestonTest::testFdmHestonIkonenToivanen(), AmericanOptionTest::testFdValues(), HestonModelTest::testFdVanillaVsCached(), QuantoOptionTest::testForwardGreeks(), anonymous_namespace{forwardoption.cpp}::testForwardGreeks(), QuantoOptionTest::testForwardPerformanceValues(), QuantoOptionTest::testForwardValues(), DigitalOptionTest::testGapEuropeanValues(), NthToDefaultTest::testGauss(), AssetSwapTest::testGenericBondImplied(), MargrabeOptionTest::testGreeks(), JumpDiffusionTest::testGreeks(), QuantoOptionTest::testGreeks(), EuropeanOptionTest::testGreeks(), BarrierOptionTest::testHaugValues(), CdoTest::testHW(), CreditDefaultSwapTest::testImpliedHazardRate(), AssetSwapTest::testImpliedValue(), SwapTest::testInArrears(), InflationCapFlooredCouponTest::testInstrumentEquality(), VarianceOptionTest::testIntegralHeston(), AmericanOptionTest::testJuValues(), HestonModelTest::testKahlJaeckelCase(), SpreadOptionTest::testKirkEngine(), VPPTest::testKlugeExtOUSpreadOption(), CapFlooredCouponTest::testLargeRates(), AsianOptionTest::testLevyEngine(), BarrierOptionTest::testLocalVolAndHestonComparison(), EuropeanOptionTest::testLocalVolatility(), AssetSwapTest::testMarketASWSpread(), AssetSwapTest::testMASWWithGenericBond(), DigitalOptionTest::testMCCashAtHit(), AsianOptionTest::testMCDiscreteArithmeticAveragePrice(), AsianOptionTest::testMCDiscreteArithmeticAverageStrike(), AsianOptionTest::testMCDiscreteGeometricAveragePrice(), CliquetOptionTest::testMcPerformance(), HybridHestonHullWhiteProcessTest::testMcPureHestonPricing(), HybridHestonHullWhiteProcessTest::testMcVanillaPricing(), VarianceSwapTest::testMCVarianceSwap(), HestonModelTest::testMcVsCached(), JumpDiffusionTest::testMerton76(), HestonModelTest::testMultipleStrikesEngine(), BasketOptionTest::testOddSamples(), BasketOptionTest::testOneDAmericanValues(), ConvertibleBondTest::testOption(), anonymous_namespace{cliquetoption.cpp}::testOptionGreeks(), InflationCapFloorTest::testParity(), AsianOptionTest::testPastFixings(), ForwardOptionTest::testPerformanceValues(), BarrierOptionTest::testPerturbative(), EuropeanOptionTest::testPriceCurve(), CompoundOptionTest::testPutCallParity(), ConvertibleBondTest::testRegression(), VarianceSwapTest::testReplicatingVarianceSwap(), VPPTest::testSimpleExtOUStorageEngine(), AssetSwapTest::testSpecializedBondVsGenericBondUsingAsw(), ShortRateModelTest::testSwaps(), BasketOptionTest::testTavellaValues(), BondTest::testTheoretical(), ForwardOptionTest::testValues(), CliquetOptionTest::testValues(), CompoundOptionTest::testValues(), EuropeanOptionTest::testValues(), QuantoOptionTest::testValues(), VarianceGammaTest::testVarianceGamma(), VPPTest::testVPPPricing(), InflationTest::testYYTermStructure(), InflationTest::testZeroTermStructure(), and CPISwapTest::zciisconsistency().
{
        if (engine_)
            unregisterWith(engine_);
        engine_ = e;
        if (engine_)
            registerWith(engine_);
        // trigger (lazy) recalculation and notify observers
        update();
    }
void QuantLib::Instrument::setupArguments (PricingEngine::arguments *) const [inline, virtual]
When a derived argument structure is defined for an instrument, this method should be overridden to fill it. This is mandatory in case a pricing engine is used.
Reimplemented in QuantLib::Bond, QuantLib::ConvertibleBond::option, QuantLib::CallableFixedRateBond, QuantLib::SyntheticCDO, QuantLib::CPISwap, QuantLib::CreditDefaultSwap, QuantLib::ZeroCouponInflationSwap, QuantLib::VanillaSwap, QuantLib::YearOnYearInflationSwap, QuantLib::EnergyCommodity, QuantLib::CPICapFloor, QuantLib::AssetSwap, QuantLib::CallableBond, QuantLib::Swaption, QuantLib::YoYInflationCapFloor, QuantLib::CapFloor, QuantLib::DiscreteAveragingAsianOption, QuantLib::VarianceSwap, QuantLib::VanillaSwingOption, QuantLib::VarianceOption, QuantLib::ContinuousFixedLookbackOption, QuantLib::Swap, QuantLib::DividendVanillaOption, QuantLib::ForwardVanillaOption, QuantLib::CdsOption, QuantLib::CliquetOption, QuantLib::WriterExtensibleOption, QuantLib::MultiAssetOption, QuantLib::HimalayaOption, QuantLib::PagodaOption, QuantLib::BarrierOption, QuantLib::PathMultiAssetOption, QuantLib::DividendBarrierOption, QuantLib::ContinuousAveragingAsianOption, QuantLib::CompoundOption, QuantLib::VanillaStorageOption, QuantLib::MargrabeOption, QuantLib::SimpleChooserOption, QuantLib::VanillaVPPOption, QuantLib::Option, QuantLib::ContinuousFloatingLookbackOption, and QuantLib::EverestOption.
Definition at line 144 of file instrument.hpp.
References QL_FAIL.
Referenced by QuantLib::detail::ImpliedVolatilityHelper::calculate(), and performCalculations().
{
        QL_FAIL("Instrument::setupArguments() not implemented");
    }
void QuantLib::Instrument::setupExpired () const [inline, protected, virtual]
This method must leave the instrument in a consistent state when the expiration condition is met.
Reimplemented in QuantLib::CreditDefaultSwap, QuantLib::Bond, QuantLib::CDO, QuantLib::SyntheticCDO, QuantLib::CPISwap, QuantLib::VanillaSwap, QuantLib::Swap, QuantLib::YearOnYearInflationSwap, QuantLib::NthToDefault, QuantLib::AssetSwap, QuantLib::CdsOption, QuantLib::RiskyBond, QuantLib::VarianceSwap, QuantLib::QuantoVanillaOption, QuantLib::OneAssetOption, QuantLib::RiskyAssetSwap, QuantLib::MultiAssetOption, QuantLib::PathMultiAssetOption, QuantLib::QuantoBarrierOption, and QuantLib::QuantoForwardVanillaOption.
Definition at line 157 of file instrument.hpp.
References additionalResults_, errorEstimate_, NPV_, and valuationDate_.
Referenced by calculate().
{
        NPV_ = errorEstimate_ = 0.0;
        valuationDate_ = Date();
        additionalResults_.clear();
    }
const Date & QuantLib::Instrument::valuationDate () const [inline]
returns the date the net present value refers to.
Definition at line 199 of file instrument.hpp.
References calculate(), QL_REQUIRE, and valuationDate_.
{
        calculate();
        QL_REQUIRE(valuationDate_ != Date(),
                   "valuation date not provided");
        return valuationDate_;
    }
Member Data Documentation
std::map<std::string,boost::any> QuantLib::Instrument::additionalResults_ [mutable, protected]
Definition at line 108 of file instrument.hpp.
Referenced by additionalResults(), fetchResults(), QuantLib::EnergyFuture::performCalculations(), QuantLib::EnergyBasisSwap::performCalculations(), QuantLib::EnergyVanillaSwap::performCalculations(), result(), and setupExpired().
boost::shared_ptr<PricingEngine> QuantLib::Instrument::engine_ [protected]
Definition at line 110 of file instrument.hpp.
Referenced by QuantLib::CallableBond::ImpliedVolHelper::operator()(), QuantLib::ConvertibleBond::performCalculations(), performCalculations(), and setPricingEngine().
Real QuantLib::Instrument::errorEstimate_ [mutable, protected]
Definition at line 106 of file instrument.hpp.
Referenced by errorEstimate(), fetchResults(), QuantLib::ConvertibleBond::performCalculations(), QuantLib::NthToDefault::performCalculations(), QuantLib::CDO::performCalculations(), and setupExpired().
Real QuantLib::Instrument::NPV_ [mutable, protected]
Definition at line 106 of file instrument.hpp.
Referenced by QuantLib::AssetSwap::fairCleanPrice(), QuantLib::AssetSwap::fairNonParRepayment(), QuantLib::OvernightIndexedSwap::fairRate(), QuantLib::AssetSwap::fairSpread(), QuantLib::OvernightIndexedSwap::fairSpread(), fetchResults(), QuantLib::YearOnYearInflationSwap::fetchResults(), QuantLib::VanillaSwap::fetchResults(), QuantLib::CPISwap::fetchResults(), NPV(), QuantLib::Stock::performCalculations(), QuantLib::RiskyAssetSwapOption::performCalculations(), QuantLib::EnergyFuture::performCalculations(), QuantLib::EnergyBasisSwap::performCalculations(), QuantLib::RiskyAssetSwap::performCalculations(), QuantLib::EnergyVanillaSwap::performCalculations(), QuantLib::CompositeInstrument::performCalculations(), QuantLib::ConvertibleBond::performCalculations(), QuantLib::NthToDefault::performCalculations(), QuantLib::Forward::performCalculations(), QuantLib::CDO::performCalculations(), QuantLib::PathMultiAssetOption::setupExpired(), QuantLib::MultiAssetOption::setupExpired(), and setupExpired().
Date QuantLib::Instrument::valuationDate_ [mutable, protected]
Definition at line 107 of file instrument.hpp.
Referenced by fetchResults(), setupExpired(), and valuationDate().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/instrument.hpp