QuantLib: QuantLib::CapFloor Class Reference
QuantLib::CapFloor Class Reference
Base class for cap-like instruments.
#include <capfloor.hpp>
Classes
class arguments
Arguments for cap/floor calculation
class engine
base class for cap/floor engines
Public Types
enum Type { Cap, Floor, Collar }
Public Member Functions
CapFloor (Type type, const Leg &floatingLeg, const std::vector< Rate > &capRates, const std::vector< Rate > &floorRates)
CapFloor (Type type, const Leg &floatingLeg, const std::vector< Rate > &strikes)
Rate atmRate (const YieldTermStructure &discountCurve) const
Volatility impliedVolatility (Real price, const Handle< YieldTermStructure > &disc, Volatility guess, Real accuracy=1.0e-4, Natural maxEvaluations=100, Volatility minVol=1.0e-7, Volatility maxVol=4.0) const
implied term volatility
Instrument interface
bool isExpired () const
returns whether the instrument might have value greater than zero.
void setupArguments (PricingEngine::arguments *) const
Inspectors
Type type () const
const std::vector< Rate > & capRates () const
const std::vector< Rate > & floorRates () const
const Leg & floatingLeg () const
Date startDate () const
Date maturityDate () const
boost::shared_ptr
< FloatingRateCoupon > lastFloatingRateCoupon () const
boost::shared_ptr< CapFloor > optionlet (const Size n) const
Returns the n-th optionlet as a new CapFloor with only one cash flow.
Private Attributes
Type type_
Leg floatingLeg_
std::vector< Rate > capRates_
std::vector< Rate > floorRates_
Detailed Description
Base class for cap-like instruments.
Test:
the correctness of the returned value is tested by checking that the price of a cap (resp. floor) decreases (resp. increases) with the strike rate.
the relationship between the values of caps, floors and the resulting collars is checked.
the put-call parity between the values of caps, floors and swaps is checked.
the correctness of the returned implied volatility is tested by using it for reproducing the target value.
the correctness of the returned value is tested by checking it against a known good value.
Definition at line 54 of file capfloor.hpp.
Member Enumeration Documentation
enum QuantLib::CapFloor::Type
Enumerator:
Cap
Floor
Collar
Definition at line 56 of file capfloor.hpp.
{ Cap, Floor, Collar };
Constructor & Destructor Documentation
QuantLib::CapFloor::CapFloor (CapFloor::Type type, const Leg & floatingLeg, const std::vector< Rate > & capRates, const std::vector< Rate > & floorRates)
Definition at line 105 of file capfloor.cpp.
References capRates_, floatingLeg_, floorRates_, QuantLib::Singleton< Settings >::instance(), QL_REQUIRE, QuantLib::Observer::registerWith(), and type_.
Referenced by optionlet().
    : type_(type), floatingLeg_(floatingLeg),
      capRates_(capRates), floorRates_(floorRates) {
        if (type_ == Cap || type_ == Collar) {
            QL_REQUIRE(!capRates_.empty(), "no cap rates given");
            capRates_.reserve(floatingLeg_.size());
            while (capRates_.size() < floatingLeg_.size())
                capRates_.push_back(capRates_.back());
        }
        if (type_ == Floor || type_ == Collar) {
            QL_REQUIRE(!floorRates_.empty(), "no floor rates given");
            floorRates_.reserve(floatingLeg_.size());
            while (floorRates_.size() < floatingLeg_.size())
                floorRates_.push_back(floorRates_.back());
        }
        Leg::const_iterator i;
        for (i = floatingLeg_.begin(); i != floatingLeg_.end(); ++i)
            registerWith(*i);
        registerWith(Settings::instance().evaluationDate());
    }
QuantLib::CapFloor::CapFloor (CapFloor::Type type, const Leg & floatingLeg, const std::vector< Rate > & strikes)
Definition at line 130 of file capfloor.cpp.
References capRates_, floatingLeg_, floorRates_, QuantLib::Singleton< Settings >::instance(), QL_FAIL, QL_REQUIRE, QuantLib::Observer::registerWith(), and type_.
    : type_(type), floatingLeg_(floatingLeg) {
        QL_REQUIRE(!strikes.empty(), "no strikes given");
        if (type_ == Cap) {
            capRates_ = strikes;
            capRates_.reserve(floatingLeg_.size());
            while (capRates_.size() < floatingLeg_.size())
                capRates_.push_back(capRates_.back());
        } else if (type_ == Floor) {
            floorRates_ = strikes;
            floorRates_.reserve(floatingLeg_.size());
            while (floorRates_.size() < floatingLeg_.size())
                floorRates_.push_back(floorRates_.back());
        } else
            QL_FAIL("only Cap/Floor types allowed in this constructor");
        Leg::const_iterator i;
        for (i = floatingLeg_.begin(); i != floatingLeg_.end(); ++i)
            registerWith(*i);
        registerWith(Settings::instance().evaluationDate());
    }
Member Function Documentation
Rate QuantLib::CapFloor::atmRate (const YieldTermStructure & discountCurve) const
Definition at line 289 of file capfloor.cpp.
References floatingLeg_, and QuantLib::TermStructure::referenceDate().
{
        bool includeSettlementDateFlows = false;
        Date settlementDate = discountCurve.referenceDate();
        return CashFlows::atmRate(floatingLeg_, discountCurve,
                                  includeSettlementDateFlows,
                                  settlementDate);
    }
const std::vector<Rate>& QuantLib::CapFloor::capRates () const [inline]
Definition at line 74 of file capfloor.hpp.
References capRates_.
Referenced by optionlet().
{ return capRates_; }
const Leg& QuantLib::CapFloor::floatingLeg () const [inline]
Definition at line 76 of file capfloor.hpp.
References floatingLeg_.
Referenced by optionlet().
{ return floatingLeg_; }
const std::vector<Rate>& QuantLib::CapFloor::floorRates () const [inline]
Definition at line 75 of file capfloor.hpp.
References floorRates_.
Referenced by optionlet().
{ return floorRates_; }
Volatility QuantLib::CapFloor::impliedVolatility (Real price, const Handle< YieldTermStructure > & disc, Volatility guess, Real accuracy = 1.0e-4, Natural maxEvaluations = 100, Volatility minVol = 1.0e-7, Volatility maxVol = 4.0) const
implied term volatility
Definition at line 297 of file capfloor.cpp.
References anonymous_namespace{interpolations.cpp}::f(), isExpired(), QL_REQUIRE, QuantLib::Solver1D< Impl >::setMaxEvaluations(), and QuantLib::Solver1D< Impl >::solve().
{
        //calculate();
        QL_REQUIRE(!isExpired(), "instrument expired");
        ImpliedVolHelper f(*this, d, targetValue);
        //Brent solver;
        NewtonSafe solver;
        solver.setMaxEvaluations(maxEvaluations);
        return solver.solve(f, accuracy, guess, minVol, maxVol);
    }
bool QuantLib::CapFloor::isExpired () const [virtual]
returns whether the instrument might have value greater than zero.
Implements QuantLib::Instrument.
Definition at line 155 of file capfloor.cpp.
References floatingLeg_.
Referenced by impliedVolatility().
{
        for (Size i=floatingLeg_.size(); i>0; --i)
            if (!floatingLeg_[i-1]->hasOccurred())
                return false;
        return true;
    }
shared_ptr< FloatingRateCoupon > QuantLib::CapFloor::lastFloatingRateCoupon () const
Definition at line 171 of file capfloor.cpp.
References floatingLeg_.
Referenced by QuantLib::OptionletStripper1::performCalculations().
{
        shared_ptr<CashFlow> lastCF(floatingLeg_.back());
        shared_ptr<FloatingRateCoupon> lastFloatingCoupon =
            boost::dynamic_pointer_cast<FloatingRateCoupon>(lastCF);
        return lastFloatingCoupon;
    }
Date QuantLib::CapFloor::maturityDate () const
Definition at line 166 of file capfloor.cpp.
References floatingLeg_.
{
        return CashFlows::maturityDate(floatingLeg_);
    }
shared_ptr< CapFloor > QuantLib::CapFloor::optionlet (const Size n) const
Returns the n-th optionlet as a new CapFloor with only one cash flow.
Definition at line 178 of file capfloor.cpp.
References CapFloor(), capRates(), floatingLeg(), floorRates(), QuantLib::io::ordinal(), QL_REQUIRE, and type().
Referenced by CapFloorTest::testConsistency().
{
        QL_REQUIRE(i < floatingLeg().size(),
                   io::ordinal(i+1) << " optionlet does not exist, only " <<
                   floatingLeg().size());
        Leg cf(1, floatingLeg()[i]);
        std::vector<Rate> cap, floor;
        if (type() == Cap || type() == Collar)
            cap.push_back(capRates()[i]);
        if (type() == Floor || type() == Collar)
            floor.push_back(floorRates()[i]);
        return shared_ptr<CapFloor>(new CapFloor(type(), cf, cap, floor));
    }
void QuantLib::CapFloor::setupArguments (PricingEngine::arguments *) const [virtual]
When a derived argument structure is defined for an instrument, this method should be overridden to fill it. This is mandatory in case a pricing engine is used.
Reimplemented from QuantLib::Instrument.
Definition at line 193 of file capfloor.cpp.
References QuantLib::CapFloor::arguments::accrualTimes, QuantLib::CapFloor::arguments::capRates, capRates_, QuantLib::CapFloor::arguments::endDates, QuantLib::Settings::evaluationDate(), QuantLib::CapFloor::arguments::fixingDates, floatingLeg_, QuantLib::CapFloor::arguments::floorRates, floorRates_, QuantLib::CapFloor::arguments::forwards, QuantLib::CapFloor::arguments::gearings, QuantLib::Singleton< Settings >::instance(), QuantLib::CapFloor::arguments::nominals, QL_REQUIRE, QuantLib::CapFloor::arguments::spreads, QuantLib::CapFloor::arguments::startDates, QuantLib::CapFloor::arguments::type, and type_.
Referenced by QuantLib::anonymous_namespace{capfloor.cpp}::ImpliedVolHelper::ImpliedVolHelper().
{
        CapFloor::arguments* arguments =
            dynamic_cast<CapFloor::arguments*>(args);
        QL_REQUIRE(arguments != 0, "wrong argument type");
        Size n = floatingLeg_.size();
        arguments->startDates.resize(n);
        arguments->fixingDates.resize(n);
        arguments->endDates.resize(n);
        arguments->accrualTimes.resize(n);
        arguments->forwards.resize(n);
        arguments->nominals.resize(n);
        arguments->gearings.resize(n);
        arguments->capRates.resize(n);
        arguments->floorRates.resize(n);
        arguments->spreads.resize(n);
        arguments->type = type_;
        Date today = Settings::instance().evaluationDate();
        for (Size i=0; i<n; ++i) {
            shared_ptr<FloatingRateCoupon> coupon =
                boost::dynamic_pointer_cast<FloatingRateCoupon>(
                                                             floatingLeg_[i]);
            QL_REQUIRE(coupon, "non-FloatingRateCoupon given");
            arguments->startDates[i] = coupon->accrualStartDate();
            arguments->fixingDates[i] = coupon->fixingDate();
            arguments->endDates[i] = coupon->date();
            // this is passed explicitly for precision
            arguments->accrualTimes[i] = coupon->accrualPeriod();
            // this is passed explicitly for precision...
            if (arguments->endDates[i] >= today) { // ...but only if needed
                arguments->forwards[i] = coupon->adjustedFixing();
            } else {
                arguments->forwards[i] = Null<Rate>();
            }
            arguments->nominals[i] = coupon->nominal();
            Spread spread = coupon->spread();
            Real gearing = coupon->gearing();
            arguments->gearings[i] = gearing;
            arguments->spreads[i] = spread;
            if (type_ == Cap || type_ == Collar)
                arguments->capRates[i] = (capRates_[i]-spread)/gearing;
            else
                arguments->capRates[i] = Null<Rate>();
            if (type_ == Floor || type_ == Collar)
                arguments->floorRates[i] = (floorRates_[i]-spread)/gearing;
            else
                arguments->floorRates[i] = Null<Rate>();
        }
    }
Date QuantLib::CapFloor::startDate () const
Definition at line 162 of file capfloor.cpp.
References floatingLeg_.
{
        return CashFlows::startDate(floatingLeg_);
    }
Type QuantLib::CapFloor::type () const [inline]
Definition at line 73 of file capfloor.hpp.
References type_.
Referenced by optionlet().
{ return type_; }
Member Data Documentation
std::vector<Rate> QuantLib::CapFloor::capRates_ [private]
Definition at line 96 of file capfloor.hpp.
Referenced by CapFloor(), capRates(), and setupArguments().
Leg QuantLib::CapFloor::floatingLeg_ [private]
Definition at line 95 of file capfloor.hpp.
Referenced by atmRate(), CapFloor(), floatingLeg(), isExpired(), lastFloatingRateCoupon(), maturityDate(), setupArguments(), and startDate().
std::vector<Rate> QuantLib::CapFloor::floorRates_ [private]
Definition at line 97 of file capfloor.hpp.
Referenced by CapFloor(), floorRates(), and setupArguments().
Type QuantLib::CapFloor::type_ [private]
Definition at line 94 of file capfloor.hpp.
Referenced by CapFloor(), setupArguments(), and type().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/capfloor.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/capfloor.cpp