QuantLib: QuantLib::anonymous_namespace{impliedvolatility.cpp}::PriceError Class Reference
QuantLib::anonymous_namespace{impliedvolatility.cpp}::PriceError Class Reference
Public Member Functions
PriceError (const PricingEngine &engine, SimpleQuote &vol, Real targetValue)
Real operator() (Volatility x) const
Private Attributes
const PricingEngine & engine_
SimpleQuote & vol_
Real targetValue_
const Instrument::results * results_
Detailed Description
Definition at line 28 of file impliedvolatility.cpp.
Constructor & Destructor Documentation
QuantLib::anonymous_namespace{impliedvolatility.cpp}::PriceError::PriceError (const PricingEngine & engine, SimpleQuote & vol, Real targetValue)
Definition at line 41 of file impliedvolatility.cpp.
References engine_, QuantLib::PricingEngine::getResults(), QL_REQUIRE, and results_.
        : engine_(engine), vol_(vol), targetValue_(targetValue) {
            results_ =
                dynamic_cast<const Instrument::results*>(engine_.getResults());
            QL_REQUIRE(results_ != 0,
                       "pricing engine does not supply needed results");
        }
Member Function Documentation
Real QuantLib::anonymous_namespace{impliedvolatility.cpp}::PriceError::operator() (Volatility x) const
Definition at line 51 of file impliedvolatility.cpp.
References QuantLib::PricingEngine::calculate(), engine_, results_, QuantLib::SimpleQuote::setValue(), targetValue_, QuantLib::Instrument::results::value, and vol_.
{
            vol_.setValue(x);
            engine_.calculate();
            return results_->value-targetValue_;
        }
Member Data Documentation
const PricingEngine& QuantLib::anonymous_namespace{impliedvolatility.cpp}::PriceError::engine_ [private]
Definition at line 35 of file impliedvolatility.cpp.
Referenced by operator()(), and PriceError().
const Instrument::results* QuantLib::anonymous_namespace{impliedvolatility.cpp}::PriceError::results_ [private]
Definition at line 38 of file impliedvolatility.cpp.
Referenced by operator()(), and PriceError().
Real QuantLib::anonymous_namespace{impliedvolatility.cpp}::PriceError::targetValue_ [private]
Definition at line 37 of file impliedvolatility.cpp.
Referenced by operator()().
SimpleQuote& QuantLib::anonymous_namespace{impliedvolatility.cpp}::PriceError::vol_ [private]
Definition at line 36 of file impliedvolatility.cpp.
Referenced by operator()().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/impliedvolatility.cpp