QuantLib: QuantLib::AbcdCalibration Class Reference
QuantLib::AbcdCalibration Class Reference
#include <abcdcalibration.hpp>
Classes
class AbcdError
class AbcdParametersTransformation
Public Member Functions
AbcdCalibration ()
AbcdCalibration (const std::vector< Real > &t, const std::vector< Real > &blackVols, Real aGuess=-0.06, Real bGuess=0.17, Real cGuess=0.54, Real dGuess=0.17, bool aIsFixed=false, bool bIsFixed=false, bool cIsFixed=false, bool dIsFixed=false, bool vegaWeighted=false, const boost::shared_ptr< EndCriteria > &endCriteria=boost::shared_ptr< EndCriteria >(), const boost::shared_ptr< OptimizationMethod > &method=boost::shared_ptr< OptimizationMethod >())
std::vector< Real > k (const std::vector< Real > &t, const std::vector< Real > &blackVols) const
adjustment factors needed to match Black vols
void compute ()
Real value (Real x) const
Real error () const
Real maxError () const
Disposable< Array > errors () const
EndCriteria::Type endCriteria () const
Real a () const
Real b () const
Real c () const
Real d () const
Public Attributes
bool aIsFixed_
bool bIsFixed_
bool cIsFixed_
bool dIsFixed_
Real a_
Real b_
Real c_
Real d_
boost::shared_ptr
< ParametersTransformation > transformation_
Private Attributes
EndCriteria::Type abcdEndCriteria_
boost::shared_ptr< EndCriteria > endCriteria_
boost::shared_ptr
< OptimizationMethod > optMethod_
std::vector< Real > weights_
bool vegaWeighted_
std::vector< Real > times_
Parameters.
std::vector< Real > blackVols_
Detailed Description
Definition at line 39 of file abcdcalibration.hpp.
Constructor & Destructor Documentation
QuantLib::AbcdCalibration::AbcdCalibration () [inline]
Definition at line 96 of file abcdcalibration.hpp.
{};
QuantLib::AbcdCalibration::AbcdCalibration (const std::vector< Real > & t, const std::vector< Real > & blackVols, Real aGuess = -0.06, Real bGuess = 0.17, Real cGuess = 0.54, Real dGuess = 0.17, bool aIsFixed = false, bool bIsFixed = false, bool cIsFixed = false, bool dIsFixed = false, bool vegaWeighted = false, const boost::shared_ptr< EndCriteria > & endCriteria = boost::shared_ptr<EndCriteria>(), const boost::shared_ptr< OptimizationMethod > & method = boost::shared_ptr<OptimizationMethod>())
Definition at line 34 of file abcdcalibration.cpp.
References endCriteria_, optMethod_, and QL_REQUIRE.
    : aIsFixed_(aIsFixed), bIsFixed_(bIsFixed),
      cIsFixed_(cIsFixed), dIsFixed_(dIsFixed),
      a_(a), b_(b), c_(c), d_(d),
      abcdEndCriteria_(EndCriteria::None), endCriteria_(endCriteria),
      optMethod_(optMethod), weights_(blackVols.size(), 1.0/blackVols.size()),
      vegaWeighted_(vegaWeighted),
      times_(t), blackVols_(blackVols) {
        QL_REQUIRE(blackVols.size()==t.size(),
                       "mismatch between number of times (" << t.size() <<
                       ") and blackVols (" << blackVols.size() << ")");
        // if no optimization method or endCriteria is provided, we provide one
        if (!optMethod_)
            optMethod_ = boost::shared_ptr<OptimizationMethod>(new
                LevenbergMarquardt(1e-8, 1e-8, 1e-8));
            //method_ = boost::shared_ptr<OptimizationMethod>(new
            //    Simplex(0.01));
        if (!endCriteria_)
            //endCriteria_ = boost::shared_ptr<EndCriteria>(new
            //    EndCriteria(60000, 100, 1e-8, 1e-8, 1e-8));
            endCriteria_ = boost::shared_ptr<EndCriteria>(new
                EndCriteria(1000, 100, 1.0e-8, 0.3e-4, 0.3e-4));   // Why 0.3e-4 ?
    }
Member Function Documentation
Real QuantLib::AbcdCalibration::a () const
Definition at line 130 of file abcdcalibration.cpp.
References a_.
Referenced by MarketModelTest::testAbcdVolatilityFit().
{
        return a_;
    }
Real QuantLib::AbcdCalibration::b () const
Definition at line 134 of file abcdcalibration.cpp.
References b_.
Referenced by MarketModelTest::testAbcdVolatilityFit().
{
        return b_;
    }
Real QuantLib::AbcdCalibration::c () const
Definition at line 138 of file abcdcalibration.cpp.
References c_.
Referenced by MarketModelTest::testAbcdVolatilityFit().
{
        return c_;
    }
void QuantLib::AbcdCalibration::compute ()
Definition at line 67 of file abcdcalibration.cpp.
References a_, abcdEndCriteria_, aIsFixed_, b_, bIsFixed_, blackVols_, c_, cIsFixed_, QuantLib::Problem::currentValue(), d_, QuantLib::CumulativeNormalDistribution::derivative(), dIsFixed_, endCriteria_, QuantLib::EndCriteria::None, optMethod_, times_, transformation_, QuantLib::validateAbcdParameters(), vegaWeighted_, and weights_.
Referenced by MarketModelTest::testAbcdVolatilityFit().
{
        if (vegaWeighted_) {
            Real weightsSum = 0.0;
            for (Size i=0; i<times_.size() ; i++) {
                Real stdDev = std::sqrt(blackVols_[i]* blackVols_[i]* times_[i]);
                // when strike==forward, the blackFormulaStdDevDerivative becomes
                weights_[i] = CumulativeNormalDistribution().derivative(.5*stdDev);
                weightsSum += weights_[i];
            }
            // weight normalization
            for (Size i=0; i<times_.size() ; i++) {
                weights_[i] /= weightsSum;
            }
        }
        // there is nothing to optimize
        if (aIsFixed_ && bIsFixed_ && cIsFixed_ && dIsFixed_) {
            abcdEndCriteria_ = EndCriteria::None;
            //error_ = interpolationError();
            //maxError_ = interpolationMaxError();
            return;
        } else {
            AbcdError costFunction(this);
            transformation_ = boost::shared_ptr<ParametersTransformation>(new
                AbcdParametersTransformation);
            Array guess(4);
            guess[0] = a_;
            guess[1] = b_;
            guess[2] = c_;
            guess[3] = d_;
            std::vector<bool> parameterAreFixed(4);
            parameterAreFixed[0] = aIsFixed_;
            parameterAreFixed[1] = bIsFixed_;
            parameterAreFixed[2] = cIsFixed_;
            parameterAreFixed[3] = dIsFixed_;
            Array inversedTransformatedGuess(transformation_->inverse(guess));
            ProjectedCostFunction projectedAbcdCostFunction(costFunction,
                            inversedTransformatedGuess, parameterAreFixed);
            Array projectedGuess
                (projectedAbcdCostFunction.project(inversedTransformatedGuess));
            NoConstraint constraint;
            Problem problem(projectedAbcdCostFunction, constraint, projectedGuess);
            abcdEndCriteria_ = optMethod_->minimize(problem, *endCriteria_);
            Array projectedResult(problem.currentValue());
            Array transfResult(projectedAbcdCostFunction.include(projectedResult));
            Array result = transformation_->direct(transfResult);
            a_ = result[0];
            b_ = result[1];
            c_ = result[2];
            d_ = result[3];
            validateAbcdParameters(a_, b_, c_, d_);
        }
    }
Real QuantLib::AbcdCalibration::d () const
Definition at line 142 of file abcdcalibration.cpp.
References d_.
Referenced by MarketModelTest::testAbcdVolatilityFit().
{
        return d_;
    }
EndCriteria::Type QuantLib::AbcdCalibration::endCriteria () const
Definition at line 191 of file abcdcalibration.cpp.
References abcdEndCriteria_.
Referenced by MarketModelTest::testAbcdVolatilityFit().
{
        return abcdEndCriteria_;
    }
Real QuantLib::AbcdCalibration::error () const
Definition at line 163 of file abcdcalibration.cpp.
References blackVols_, times_, value(), and weights_.
Referenced by maxError(), MarketModelTest::testAbcdVolatilityFit(), and QuantLib::AbcdCalibration::AbcdError::value().
{
        Size n = times_.size();
        Real error, squaredError = 0.0;
        for (Size i=0; i<times_.size() ; i++) {
            error = (value(times_[i]) - blackVols_[i]);
            squaredError += error * error *(weights_[i]);
        }
        return std::sqrt(n*squaredError/(n-1));
    }
Disposable< Array > QuantLib::AbcdCalibration::errors () const
Definition at line 183 of file abcdcalibration.cpp.
References blackVols_, times_, value(), and weights_.
Referenced by QuantLib::AbcdCalibration::AbcdError::values().
{
        Array results(times_.size());
        for (Size i=0; i<times_.size() ; i++) {
            results[i] = (value(times_[i]) - blackVols_[i])* std::sqrt(weights_[i]);
        }
        return results;
    }
std::vector< Real > QuantLib::AbcdCalibration::k (const std::vector< Real > & t, const std::vector< Real > & blackVols) const
adjustment factors needed to match Black vols
Definition at line 151 of file abcdcalibration.cpp.
References QL_REQUIRE, and value().
Referenced by MarketModelTest::testAbcdVolatilityFit().
{
        QL_REQUIRE(blackVols.size()==t.size(),
               "mismatch between number of times (" << t.size() <<
               ") and blackVols (" << blackVols.size() << ")");
        std::vector<Real> k(t.size());
        for (Size i=0; i<t.size() ; i++) {
            k[i]=blackVols[i]/value(t[i]);
        }
        return k;
    }
Real QuantLib::AbcdCalibration::maxError () const
Definition at line 173 of file abcdcalibration.cpp.
References blackVols_, error(), QL_MIN_REAL, times_, and value().
{
        Real error, maxError = QL_MIN_REAL;
        for (Size i=0; i<times_.size() ; i++) {
            error = std::fabs(value(times_[i]) - blackVols_[i]);
            maxError = std::max(maxError, error);
        }
        return maxError;
    }
Real QuantLib::AbcdCalibration::value (Real x) const
Definition at line 147 of file abcdcalibration.cpp.
References a_, QuantLib::abcdBlackVolatility(), b_, c_, and d_.
Referenced by error(), errors(), k(), and maxError().
{
        return abcdBlackVolatility(x,a_,b_,c_,d_);
    }
Member Data Documentation
Real QuantLib::AbcdCalibration::a_
Definition at line 131 of file abcdcalibration.hpp.
Referenced by a(), compute(), QuantLib::AbcdCalibration::AbcdError::value(), value(), and QuantLib::AbcdCalibration::AbcdError::values().
EndCriteria::Type QuantLib::AbcdCalibration::abcdEndCriteria_ [mutable, private]
Definition at line 137 of file abcdcalibration.hpp.
Referenced by compute(), and endCriteria().
bool QuantLib::AbcdCalibration::aIsFixed_
Definition at line 130 of file abcdcalibration.hpp.
Referenced by compute().
Real QuantLib::AbcdCalibration::b_
Definition at line 131 of file abcdcalibration.hpp.
Referenced by b(), compute(), QuantLib::AbcdCalibration::AbcdError::value(), value(), and QuantLib::AbcdCalibration::AbcdError::values().
bool QuantLib::AbcdCalibration::bIsFixed_
Definition at line 130 of file abcdcalibration.hpp.
Referenced by compute().
std::vector<Real> QuantLib::AbcdCalibration::blackVols_ [private]
Definition at line 143 of file abcdcalibration.hpp.
Referenced by compute(), error(), errors(), and maxError().
Real QuantLib::AbcdCalibration::c_
Definition at line 131 of file abcdcalibration.hpp.
Referenced by c(), compute(), QuantLib::AbcdCalibration::AbcdError::value(), value(), and QuantLib::AbcdCalibration::AbcdError::values().
bool QuantLib::AbcdCalibration::cIsFixed_
Definition at line 130 of file abcdcalibration.hpp.
Referenced by compute().
Real QuantLib::AbcdCalibration::d_
Definition at line 131 of file abcdcalibration.hpp.
Referenced by compute(), d(), QuantLib::AbcdCalibration::AbcdError::value(), value(), and QuantLib::AbcdCalibration::AbcdError::values().
bool QuantLib::AbcdCalibration::dIsFixed_
Definition at line 130 of file abcdcalibration.hpp.
Referenced by compute().
boost::shared_ptr<EndCriteria> QuantLib::AbcdCalibration::endCriteria_ [private]
Definition at line 138 of file abcdcalibration.hpp.
Referenced by AbcdCalibration(), and compute().
boost::shared_ptr<OptimizationMethod> QuantLib::AbcdCalibration::optMethod_ [private]
Definition at line 139 of file abcdcalibration.hpp.
Referenced by AbcdCalibration(), and compute().
std::vector<Real> QuantLib::AbcdCalibration::times_ [private]
Parameters.
Definition at line 143 of file abcdcalibration.hpp.
Referenced by compute(), error(), errors(), and maxError().
boost::shared_ptr<ParametersTransformation> QuantLib::AbcdCalibration::transformation_
Definition at line 132 of file abcdcalibration.hpp.
Referenced by compute(), QuantLib::AbcdCalibration::AbcdError::value(), and QuantLib::AbcdCalibration::AbcdError::values().
bool QuantLib::AbcdCalibration::vegaWeighted_ [private]
Definition at line 141 of file abcdcalibration.hpp.
Referenced by compute().
std::vector<Real> QuantLib::AbcdCalibration::weights_ [mutable, private]
Definition at line 140 of file abcdcalibration.hpp.
Referenced by compute(), error(), and errors().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/abcdcalibration.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/abcdcalibration.cpp