QuantLib: QuantLib::AverageBasketPayoff Class Reference
QuantLib::AverageBasketPayoff Class Reference
#include <basketoption.hpp>
Public Member Functions
AverageBasketPayoff (const boost::shared_ptr< Payoff > &p, const Array &a)
AverageBasketPayoff (const boost::shared_ptr< Payoff > &p, Size n)
Real accumulate (const Array &a) const
Private Attributes
Array weights_
Detailed Description
Definition at line 72 of file basketoption.hpp.
Constructor & Destructor Documentation
QuantLib::AverageBasketPayoff::AverageBasketPayoff (const boost::shared_ptr< Payoff > & p, const Array & a) [inline]
Definition at line 74 of file basketoption.hpp.
        : BasketPayoff(p), weights_(a) {}
QuantLib::AverageBasketPayoff::AverageBasketPayoff (const boost::shared_ptr< Payoff > & p, Size n) [inline]
Definition at line 77 of file basketoption.hpp.
        : BasketPayoff(p), weights_(n, 1.0/static_cast<Real>(n)) {}
Member Function Documentation
Real QuantLib::AverageBasketPayoff::accumulate (const Array & a) const [inline, virtual]
Implements QuantLib::BasketPayoff.
Definition at line 80 of file basketoption.hpp.
References QuantLib::Array::begin(), QuantLib::Array::end(), QuantLib::dsd::inner_product(), and weights_.
{
            return std::inner_product(weights_.begin(),
                                      weights_.end(),
                                      a.begin(), 0.0);
        }
Member Data Documentation
Array QuantLib::AverageBasketPayoff::weights_ [private]
Definition at line 86 of file basketoption.hpp.
Referenced by accumulate().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/basketoption.hpp