QuantLib: anonymous_namespace{mclongstaffschwartzengine.cpp}::AmericanMaxPathPricer Class Reference
anonymous_namespace{mclongstaffschwartzengine.cpp}::AmericanMaxPathPricer Class Reference
Public Member Functions
AmericanMaxPathPricer (const boost::shared_ptr< Payoff > &payoff)
StateType state (const MultiPath &path, Size t) const
Real operator() (const MultiPath &path, Size t) const
std::vector< boost::function1
< Real, StateType > > basisSystem () const
Protected Attributes
const boost::shared_ptr< Payoff > payoff_
Detailed Description
Definition at line 38 of file mclongstaffschwartzengine.cpp.
Constructor & Destructor Documentation
anonymous_namespace{mclongstaffschwartzengine.cpp}::AmericanMaxPathPricer::AmericanMaxPathPricer (const boost::shared_ptr< Payoff > & payoff) [inline]
Definition at line 40 of file mclongstaffschwartzengine.cpp.
        : payoff_(payoff) {
        }
Member Function Documentation
std::vector<boost::function1<Real, StateType> > anonymous_namespace{mclongstaffschwartzengine.cpp}::AmericanMaxPathPricer::basisSystem () const [inline, virtual]
Implements QuantLib::EarlyExercisePathPricer< MultiPath >.
Definition at line 58 of file mclongstaffschwartzengine.cpp.
References QuantLib::LsmBasisSystem::Monomial, and QuantLib::LsmBasisSystem::multiPathBasisSystem().
{
            return LsmBasisSystem::multiPathBasisSystem(2, 2,
                                                        LsmBasisSystem::Monomial);
        }
Real anonymous_namespace{mclongstaffschwartzengine.cpp}::AmericanMaxPathPricer::operator() (const MultiPath & path, Size t) const [inline, virtual]
Implements QuantLib::EarlyExercisePathPricer< MultiPath >.
Definition at line 53 of file mclongstaffschwartzengine.cpp.
References QuantLib::Array::begin(), and QuantLib::Array::end().
{
            const Array tmp = state(path, t);
            return (*payoff_)(*std::max_element(tmp.begin(), tmp.end()));
        }
StateType anonymous_namespace{mclongstaffschwartzengine.cpp}::AmericanMaxPathPricer::state (const MultiPath & path, Size t) const [inline, virtual]
Implements QuantLib::EarlyExercisePathPricer< MultiPath >.
Definition at line 44 of file mclongstaffschwartzengine.cpp.
References QuantLib::MultiPath::assetNumber(), and anonymous_namespace{quantlibbenchmark.cpp}::t.
{
            Array tmp(path.assetNumber());
            for (Size i=0; i<path.assetNumber(); ++i) {
                tmp[i]=path[i][t];
            }
            return tmp;
        }
Member Data Documentation
const boost::shared_ptr<Payoff> anonymous_namespace{mclongstaffschwartzengine.cpp}::AmericanMaxPathPricer::payoff_ [protected]
Definition at line 64 of file mclongstaffschwartzengine.cpp.
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/mclongstaffschwartzengine.cpp