QuantLib: QuantLib::FdmBlackScholesMesher Class Reference
QuantLib::FdmBlackScholesMesher Class Reference
#include <fdmblackscholesmesher.hpp>
Public Member Functions
FdmBlackScholesMesher (Size size, const boost::shared_ptr< GeneralizedBlackScholesProcess > &process, Time maturity, Real strike, Real xMinConstraint=Null< Real >(), Real xMaxConstraint=Null< Real >(), Real eps=0.0001, Real scaleFactor=1.5, const std::pair< Real, Real > &cPoint=(std::pair< Real, Real >(Null< Real >(), Null< Real >())))
Static Public Member Functions
static boost::shared_ptr
< GeneralizedBlackScholesProcess > processHelper (const Handle< Quote > &s0, const Handle< YieldTermStructure > &rTS, const Handle< YieldTermStructure > &qTS, Volatility vol)
Detailed Description
Definition at line 37 of file fdmblackscholesmesher.hpp.
Constructor & Destructor Documentation
QuantLib::FdmBlackScholesMesher::FdmBlackScholesMesher (Size size, const boost::shared_ptr< GeneralizedBlackScholesProcess > & process, Time maturity, Real strike, Real xMinConstraint = Null<Real>(), Real xMaxConstraint = Null<Real>(), Real eps = 0.0001, Real scaleFactor = 1.5, const std::pair< Real, Real > & cPoint = (std::pair<Real, Real>(Null<Real>(), Null<Real>())))
Definition at line 34 of file fdmblackscholesmesher.cpp.
References QuantLib::Fdm1dMesher::dminus_, QuantLib::Fdm1dMesher::dplus_, QuantLib::Fdm1dMesher::locations_, and QL_REQUIRE.
    : Fdm1dMesher(size) {
        const Real S = process->x0();
        QL_REQUIRE(S > 0.0, "negative or null underlying given");
        // Set the grid boundaries
        const Real normInvEps = InverseCumulativeNormal()(1-eps);
        const Real sigmaSqrtT
            = process->blackVolatility()->blackVol(maturity, strike)
                                                        *std::sqrt(maturity);
        Real xMin = std::log(S) - sigmaSqrtT*normInvEps*scaleFactor;
        Real xMax = std::log(S) + sigmaSqrtT*normInvEps*scaleFactor;
        if (xMinConstraint != Null<Real>()) {
            xMin = xMinConstraint;
        }
        if (xMaxConstraint != Null<Real>()) {
            xMax = xMaxConstraint;
        }
        boost::shared_ptr<Fdm1dMesher> helper;
        if (   cPoint.first != Null<Real>()
            && std::log(cPoint.first) >=xMin && std::log(cPoint.first) <=xMax) {
            helper = boost::shared_ptr<Fdm1dMesher>(
                new Concentrating1dMesher(xMin, xMax, size,
                    std::pair<Real,Real>(std::log(cPoint.first),
                                         cPoint.second)));
        }
        else {
            helper = boost::shared_ptr<Fdm1dMesher>(
                                        new Uniform1dMesher(xMin, xMax, size));
        }
        locations_ = helper->locations();
        for (Size i=0; i < locations_.size(); ++i) {
            dplus_[i]  = helper->dplus(i);
            dminus_[i] = helper->dminus(i);
        }
    }
Member Function Documentation
boost::shared_ptr< GeneralizedBlackScholesProcess > QuantLib::FdmBlackScholesMesher::processHelper (const Handle< Quote > & s0, const Handle< YieldTermStructure > & rTS, const Handle< YieldTermStructure > & qTS, Volatility vol) [static]
Definition at line 85 of file fdmblackscholesmesher.cpp.
Referenced by QuantLib::FdHestonRebateEngine::calculate(), QuantLib::FdHestonBarrierEngine::calculate(), QuantLib::FdHestonHullWhiteVanillaEngine::calculate(), and QuantLib::FdHestonVanillaEngine::getSolverDesc().
{
        return boost::shared_ptr<GeneralizedBlackScholesProcess>(
            new GeneralizedBlackScholesProcess(
                s0, qTS, rTS,
                Handle<BlackVolTermStructure>(
                    boost::shared_ptr<BlackVolTermStructure>(
                        new BlackConstantVol(rTS->referenceDate(),
                                             Calendar(),
                                             vol,
                                             rTS->dayCounter())))));
    }
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/meshers/fdmblackscholesmesher.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/meshers/fdmblackscholesmesher.cpp