QuantLib: QuantLib::CapFloorTermVolCurve Class Reference
QuantLib::CapFloorTermVolCurve Class Reference
Cap/floor at-the-money term-volatility vector.
#include <capfloortermvolcurve.hpp>
Public Member Functions
CapFloorTermVolCurve (Natural settlementDays, const Calendar &calendar, BusinessDayConvention bdc, const std::vector< Period > &optionTenors, const std::vector< Handle< Quote > > &vols, const DayCounter &dc=Actual365Fixed())
floating reference date, floating market data
CapFloorTermVolCurve (const Date &settlementDate, const Calendar &calendar, BusinessDayConvention bdc, const std::vector< Period > &optionTenors, const std::vector< Handle< Quote > > &vols, const DayCounter &dc=Actual365Fixed())
fixed reference date, floating market data
CapFloorTermVolCurve (const Date &settlementDate, const Calendar &calendar, BusinessDayConvention bdc, const std::vector< Period > &optionTenors, const std::vector< Volatility > &vols, const DayCounter &dc=Actual365Fixed())
fixed reference date, fixed market data
CapFloorTermVolCurve (Natural settlementDays, const Calendar &calendar, BusinessDayConvention bdc, const std::vector< Period > &optionTenors, const std::vector< Volatility > &vols, const DayCounter &dc=Actual365Fixed())
floating reference date, fixed market data
TermStructure interface
Date maxDate () const
the latest date for which the curve can return values
VolatilityTermStructure interface
Real minStrike () const
the minimum strike for which the term structure can return vols
Real maxStrike () const
the maximum strike for which the term structure can return vols
LazyObject interface
void update ()
void performCalculations () const
some inspectors
const std::vector< Period > & optionTenors () const
const std::vector< Date > & optionDates () const
const std::vector< Time > & optionTimes () const
Protected Member Functions
Volatility volatilityImpl (Time length, Rate) const
implements the actual volatility calculation in derived classes
Private Member Functions
void checkInputs () const
void initializeOptionDatesAndTimes () const
void registerWithMarketData ()
void interpolate ()
Private Attributes
Size nOptionTenors_
std::vector< Period > optionTenors_
std::vector< Date > optionDates_
std::vector< Time > optionTimes_
Date evaluationDate_
std::vector< Handle< Quote > > volHandles_
std::vector< Volatility > vols_
Interpolation interpolation_
Detailed Description
Cap/floor at-the-money term-volatility vector.
This class provides the at-the-money volatility for a given cap/floor interpolating a volatility vector whose elements are the market volatilities of a set of caps/floors with given length.
Definition at line 44 of file capfloortermvolcurve.hpp.
Constructor & Destructor Documentation
QuantLib::CapFloorTermVolCurve::CapFloorTermVolCurve (Natural settlementDays, const Calendar & calendar, BusinessDayConvention bdc, const std::vector< Period > & optionTenors, const std::vector< Handle< Quote > > & vols, const DayCounter & dc = Actual365Fixed())
floating reference date, floating market data
Definition at line 31 of file capfloortermvolcurve.cpp.
References checkInputs(), initializeOptionDatesAndTimes(), interpolate(), and registerWithMarketData().
    : CapFloorTermVolatilityStructure(settlementDays, calendar, bdc, dc),
      nOptionTenors_(optionTenors.size()),
      optionTenors_(optionTenors),
      optionDates_(nOptionTenors_),
      optionTimes_(nOptionTenors_),
      volHandles_(vols),
      vols_(vols.size()) // do not initialize with nOptionTenors_
    {
        checkInputs();
        initializeOptionDatesAndTimes();
        registerWithMarketData();
        interpolate();
    }
QuantLib::CapFloorTermVolCurve::CapFloorTermVolCurve (const Date & settlementDate, const Calendar & calendar, BusinessDayConvention bdc, const std::vector< Period > & optionTenors, const std::vector< Handle< Quote > > & vols, const DayCounter & dc = Actual365Fixed())
fixed reference date, floating market data
Definition at line 53 of file capfloortermvolcurve.cpp.
References checkInputs(), initializeOptionDatesAndTimes(), interpolate(), and registerWithMarketData().
    : CapFloorTermVolatilityStructure(settlementDate, calendar, bdc, dayCounter),
      nOptionTenors_(optionTenors.size()),
      optionTenors_(optionTenors),
      optionDates_(nOptionTenors_),
      optionTimes_(nOptionTenors_),
      volHandles_(vols),
      vols_(vols.size()) // do not initialize with nOptionTenors_
    {
        checkInputs();
        initializeOptionDatesAndTimes();
        registerWithMarketData();
        interpolate();
    }
QuantLib::CapFloorTermVolCurve::CapFloorTermVolCurve (const Date & settlementDate, const Calendar & calendar, BusinessDayConvention bdc, const std::vector< Period > & optionTenors, const std::vector< Volatility > & vols, const DayCounter & dc = Actual365Fixed())
fixed reference date, fixed market data
Definition at line 75 of file capfloortermvolcurve.cpp.
References checkInputs(), initializeOptionDatesAndTimes(), interpolate(), nOptionTenors_, volHandles_, and vols_.
    : CapFloorTermVolatilityStructure(settlementDate, calendar, bdc, dayCounter),
      nOptionTenors_(optionTenors.size()),
      optionTenors_(optionTenors),
      optionDates_(nOptionTenors_),
      optionTimes_(nOptionTenors_),
      volHandles_(vols.size()), // do not initialize with nOptionTenors_
      vols_(vols)
    {
        checkInputs();
        initializeOptionDatesAndTimes();
        // fill dummy handles to allow generic handle-based computations later
        for (Size i=0; i<nOptionTenors_; ++i)
            volHandles_[i] = Handle<Quote>(boost::shared_ptr<Quote>(new
                SimpleQuote(vols_[i])));
        interpolate();
    }
QuantLib::CapFloorTermVolCurve::CapFloorTermVolCurve (Natural settlementDays, const Calendar & calendar, BusinessDayConvention bdc, const std::vector< Period > & optionTenors, const std::vector< Volatility > & vols, const DayCounter & dc = Actual365Fixed())
floating reference date, fixed market data
Definition at line 100 of file capfloortermvolcurve.cpp.
References checkInputs(), initializeOptionDatesAndTimes(), interpolate(), nOptionTenors_, volHandles_, and vols_.
    : CapFloorTermVolatilityStructure(settlementDays, calendar, bdc, dayCounter),
      nOptionTenors_(optionTenors.size()),
      optionTenors_(optionTenors),
      optionDates_(nOptionTenors_),
      optionTimes_(nOptionTenors_),
      volHandles_(vols.size()), // do not initialize with nOptionTenors_
      vols_(vols)
    {
        checkInputs();
        initializeOptionDatesAndTimes();
        // fill dummy handles to allow generic handle-based computations later
        for (Size i=0; i<nOptionTenors_; ++i)
            volHandles_[i] = Handle<Quote>(boost::shared_ptr<Quote>(new
                SimpleQuote(vols_[i])));
        interpolate();
    }
Member Function Documentation
void QuantLib::CapFloorTermVolCurve::checkInputs () const [private]
Definition at line 124 of file capfloortermvolcurve.cpp.
References QuantLib::Days, nOptionTenors_, optionTenors_, QuantLib::io::ordinal(), QL_REQUIRE, and vols_.
Referenced by CapFloorTermVolCurve().
    {
        QL_REQUIRE(!optionTenors_.empty(), "empty option tenor vector");
        QL_REQUIRE(nOptionTenors_==vols_.size(),
                   "mismatch between number of option tenors (" <<
                   nOptionTenors_ << ") and number of volatilities (" <<
                   vols_.size() << ")");
        QL_REQUIRE(optionTenors_[0]>0*Days,
                   "negative first option tenor: " << optionTenors_[0]);
        for (Size i=1; i<nOptionTenors_; ++i)
            QL_REQUIRE(optionTenors_[i]>optionTenors_[i-1],
                       "non increasing option tenor: " << io::ordinal(i) <<
                       " is " << optionTenors_[i-1] << ", " <<
                       io::ordinal(i+1) << " is " << optionTenors_[i]);
    }
void QuantLib::CapFloorTermVolCurve::initializeOptionDatesAndTimes () const [private]
Definition at line 170 of file capfloortermvolcurve.cpp.
References nOptionTenors_, QuantLib::VolatilityTermStructure::optionDateFromTenor(), optionDates_, optionTenors_, optionTimes_, and QuantLib::TermStructure::timeFromReference().
Referenced by CapFloorTermVolCurve(), and update().
    {
        for (Size i=0; i<nOptionTenors_; ++i) {
            optionDates_[i] = optionDateFromTenor(optionTenors_[i]);
            optionTimes_[i] = timeFromReference(optionDates_[i]);
        }
    }
void QuantLib::CapFloorTermVolCurve::interpolate () [private]
Definition at line 146 of file capfloortermvolcurve.cpp.
References interpolation_, optionTimes_, QuantLib::CubicInterpolation::SecondDerivative, QuantLib::CubicInterpolation::Spline, and vols_.
Referenced by CapFloorTermVolCurve().
    {
        interpolation_ = CubicInterpolation(
                                    optionTimes_.begin(), optionTimes_.end(),
                                    vols_.begin(),
                                    CubicInterpolation::Spline, false,
                                    CubicInterpolation::SecondDerivative, 0.0,
                                    CubicInterpolation::SecondDerivative, 0.0);
    }
Date QuantLib::CapFloorTermVolCurve::maxDate () const [inline, virtual]
the latest date for which the curve can return values
Implements QuantLib::TermStructure.
Definition at line 120 of file capfloortermvolcurve.hpp.
References QuantLib::LazyObject::calculate(), QuantLib::VolatilityTermStructure::optionDateFromTenor(), and optionTenors_.
{
        calculate();
        return optionDateFromTenor(optionTenors_.back());
    }
Real QuantLib::CapFloorTermVolCurve::maxStrike () const [inline, virtual]
the maximum strike for which the term structure can return vols
Implements QuantLib::VolatilityTermStructure.
Definition at line 129 of file capfloortermvolcurve.hpp.
References QL_MAX_REAL.
{
        return QL_MAX_REAL;
    }
Real QuantLib::CapFloorTermVolCurve::minStrike () const [inline, virtual]
the minimum strike for which the term structure can return vols
Implements QuantLib::VolatilityTermStructure.
Definition at line 125 of file capfloortermvolcurve.hpp.
References QL_MIN_REAL.
{
        return QL_MIN_REAL;
    }
const std::vector< Date > & QuantLib::CapFloorTermVolCurve::optionDates () const [inline]
Definition at line 146 of file capfloortermvolcurve.hpp.
References QuantLib::LazyObject::calculate(), and optionDates_.
{
        // what if quotes are not available?
        calculate();
        return optionDates_;
    }
const std::vector< Period > & QuantLib::CapFloorTermVolCurve::optionTenors () const [inline]
Definition at line 141 of file capfloortermvolcurve.hpp.
References optionTenors_.
{
        return optionTenors_;
    }
const std::vector< Time > & QuantLib::CapFloorTermVolCurve::optionTimes () const [inline]
Definition at line 153 of file capfloortermvolcurve.hpp.
References QuantLib::LazyObject::calculate(), and optionTimes_.
{
        // what if quotes are not available?
        calculate();
        return optionTimes_;
    }
void QuantLib::CapFloorTermVolCurve::performCalculations () const [virtual]
This method must implement any calculations which must be (re)done in order to calculate the desired results.
Implements QuantLib::LazyObject.
Definition at line 178 of file capfloortermvolcurve.cpp.
References interpolation_, QuantLib::Interpolation::update(), volHandles_, and vols_.
    {
        // check if date recalculation must be called here
        for (Size i=0; i<vols_.size(); ++i)
            vols_[i] = volHandles_[i]->value();
        interpolation_.update();
    }
void QuantLib::CapFloorTermVolCurve::registerWithMarketData () [private]
Definition at line 140 of file capfloortermvolcurve.cpp.
References QuantLib::Observer::registerWith(), and volHandles_.
Referenced by CapFloorTermVolCurve().
    {
        for (Size i=0; i<volHandles_.size(); ++i)
            registerWith(volHandles_[i]);
    }
void QuantLib::CapFloorTermVolCurve::update () [virtual]
This method must be implemented in derived classes. An instance of Observer does not call this method directly: instead, it will be called by the observables the instance registered with when they need to notify any changes.
Reimplemented from QuantLib::LazyObject.
Definition at line 156 of file capfloortermvolcurve.cpp.
References anonymous_namespace{marketmodel.cpp}::d, QuantLib::Settings::evaluationDate(), evaluationDate_, initializeOptionDatesAndTimes(), QuantLib::Singleton< Settings >::instance(), and QuantLib::TermStructure::moving_.
    {
        // recalculate dates if necessary...
        if (moving_) {
            Date d = Settings::instance().evaluationDate();
            if (evaluationDate_ != d) {
                evaluationDate_ = d;
                initializeOptionDatesAndTimes();
            }
        }
        CapFloorTermVolatilityStructure::update();
        LazyObject::update();
    }
Volatility QuantLib::CapFloorTermVolCurve::volatilityImpl (Time length, Rate strike) const [inline, protected, virtual]
implements the actual volatility calculation in derived classes
Implements QuantLib::CapFloorTermVolatilityStructure.
Definition at line 134 of file capfloortermvolcurve.hpp.
References QuantLib::LazyObject::calculate(), and interpolation_.
{
        calculate();
        return interpolation_(t, true);
    }
Member Data Documentation
Date QuantLib::CapFloorTermVolCurve::evaluationDate_ [private]
Definition at line 109 of file capfloortermvolcurve.hpp.
Referenced by update().
Interpolation QuantLib::CapFloorTermVolCurve::interpolation_ [mutable, private]
Definition at line 115 of file capfloortermvolcurve.hpp.
Referenced by interpolate(), performCalculations(), and volatilityImpl().
Size QuantLib::CapFloorTermVolCurve::nOptionTenors_ [private]
Definition at line 105 of file capfloortermvolcurve.hpp.
Referenced by CapFloorTermVolCurve(), checkInputs(), and initializeOptionDatesAndTimes().
std::vector<Date> QuantLib::CapFloorTermVolCurve::optionDates_ [mutable, private]
Definition at line 107 of file capfloortermvolcurve.hpp.
Referenced by initializeOptionDatesAndTimes(), and optionDates().
std::vector<Period> QuantLib::CapFloorTermVolCurve::optionTenors_ [private]
Definition at line 106 of file capfloortermvolcurve.hpp.
Referenced by checkInputs(), initializeOptionDatesAndTimes(), maxDate(), and optionTenors().
std::vector<Time> QuantLib::CapFloorTermVolCurve::optionTimes_ [mutable, private]
Definition at line 108 of file capfloortermvolcurve.hpp.
Referenced by initializeOptionDatesAndTimes(), interpolate(), and optionTimes().
std::vector<Handle<Quote> > QuantLib::CapFloorTermVolCurve::volHandles_ [private]
Definition at line 111 of file capfloortermvolcurve.hpp.
Referenced by CapFloorTermVolCurve(), performCalculations(), and registerWithMarketData().
std::vector<Volatility> QuantLib::CapFloorTermVolCurve::vols_ [mutable, private]
Definition at line 112 of file capfloortermvolcurve.hpp.
Referenced by CapFloorTermVolCurve(), checkInputs(), interpolate(), and performCalculations().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/capfloor/capfloortermvolcurve.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/capfloor/capfloortermvolcurve.cpp