QuantLib: QuantLib::CapHelper Class Reference
QuantLib::CapHelper Class Reference
calibration helper for ATM cap
#include <caphelper.hpp>
Public Member Functions
CapHelper (const Period &length, const Handle< Quote > &volatility, const boost::shared_ptr< IborIndex > &index, Frequency fixedLegFrequency, const DayCounter &fixedLegDayCounter, bool includeFirstSwaplet, const Handle< YieldTermStructure > &termStructure, CalibrationHelper::CalibrationErrorType errorType=CalibrationHelper::RelativePriceError)
virtual void addTimesTo (std::list< Time > &times) const
virtual Real modelValue () const
returns the price of the instrument according to the model
virtual Real blackPrice (Volatility volatility) const
Black price given a volatility.
Private Attributes
boost::shared_ptr< Cap > cap_
Detailed Description
calibration helper for ATM cap
Bug:
This helper does not register with the passed IBOR index and with the evaluation date. Furthermore, the ATM strike rate is not recalculated when any of its observables change.
Definition at line 38 of file caphelper.hpp.
Constructor & Destructor Documentation
QuantLib::CapHelper::CapHelper (const Period & length, const Handle< Quote > & volatility, const boost::shared_ptr< IborIndex > & index, Frequency fixedLegFrequency, const DayCounter & fixedLegDayCounter, bool includeFirstSwaplet, const Handle< YieldTermStructure > & termStructure, CalibrationHelper::CalibrationErrorType errorType = CalibrationHelper::RelativePriceError)
Definition at line 31 of file caphelper.cpp.
References blackPrice(), cap_, QuantLib::CalibrationHelper::engine_, QuantLib::DateGeneration::Forward, QuantLib::Swap::legBPS(), QuantLib::CalibrationHelper::marketValue_, QuantLib::Instrument::NPV(), QuantLib::Instrument::setPricingEngine(), anonymous_namespace{marketmodel.cpp}::startDate, QuantLib::swap(), QuantLib::Unadjusted, QuantLib::CalibrationHelper::volatility_, QuantLib::FixedRateLeg::withCouponRates(), QuantLib::IborLeg::withNotionals(), QuantLib::FixedRateLeg::withNotionals(), QuantLib::IborLeg::withPaymentAdjustment(), and QuantLib::FixedRateLeg::withPaymentAdjustment().
    : CalibrationHelper(volatility,termStructure,errorType) {
        Period indexTenor = index->tenor();
        Rate fixedRate = 0.04; // dummy value
        Date startDate, maturity;
        if (includeFirstSwaplet) {
            startDate = termStructure->referenceDate();
            maturity = termStructure->referenceDate() + length;
        } else {
            startDate = termStructure->referenceDate() + indexTenor;
            maturity = termStructure->referenceDate() + length;
        }
        boost::shared_ptr<IborIndex> dummyIndex(new
            IborIndex("dummy",
                      indexTenor,
                      index->fixingDays(),
                      index->currency(),
                      index->fixingCalendar(),
                      index->businessDayConvention(),
                      index->endOfMonth(),
                      termStructure->dayCounter(),
                      termStructure));
        std::vector<Real> nominals(1,1.0);
        Schedule floatSchedule(startDate, maturity,
                               index->tenor(), index->fixingCalendar(),
                               index->businessDayConvention(),
                               index->businessDayConvention(),
                               DateGeneration::Forward, false);
        Leg floatingLeg = IborLeg(floatSchedule, index)
            .withNotionals(nominals)
            .withPaymentAdjustment(index->businessDayConvention())
            .withFixingDays(0);
        Schedule fixedSchedule(startDate, maturity, Period(fixedLegFrequency),
                               index->fixingCalendar(),
                               Unadjusted, Unadjusted,
                               DateGeneration::Forward, false);
        Leg fixedLeg = FixedRateLeg(fixedSchedule)
            .withNotionals(nominals)
            .withCouponRates(fixedRate, fixedLegDayCounter)
            .withPaymentAdjustment(index->businessDayConvention());
        Swap swap(floatingLeg, fixedLeg);
        swap.setPricingEngine(boost::shared_ptr<PricingEngine>(
                            new DiscountingSwapEngine(termStructure, false)));
        Rate fairRate = fixedRate - swap.NPV()/(swap.legBPS(1)/1.0e-4);
        engine_ = boost::shared_ptr<PricingEngine>();
        cap_ = boost::shared_ptr<Cap>(new Cap(floatingLeg,
                                              std::vector<Rate>(1, fairRate)));
        marketValue_ = blackPrice(volatility_->value());
    }
Member Function Documentation
void QuantLib::CapHelper::addTimesTo (std::list< Time > & times) const [virtual]
Implements QuantLib::CalibrationHelper.
Definition at line 93 of file caphelper.cpp.
References cap_, and QuantLib::CalibrationHelper::termStructure_.
{
        CapFloor::arguments args;
        cap_->setupArguments(&args);
        std::vector<Time> capTimes =
            DiscretizedCapFloor(args,
                                termStructure_->referenceDate(),
                                termStructure_->dayCounter()).mandatoryTimes();
        times.insert(times.end(),
                     capTimes.begin(), capTimes.end());
    }
Real QuantLib::CapHelper::blackPrice (Volatility volatility) const [virtual]
Black price given a volatility.
Implements QuantLib::CalibrationHelper.
Definition at line 109 of file caphelper.cpp.
References cap_, QuantLib::CalibrationHelper::engine_, and QuantLib::CalibrationHelper::termStructure_.
Referenced by CapHelper().
{
        boost::shared_ptr<Quote> vol(new SimpleQuote(sigma));
        boost::shared_ptr<PricingEngine> black(
                                 new BlackCapFloorEngine(termStructure_,
                                                         Handle<Quote>(vol)));
        cap_->setPricingEngine(black);
        Real value = cap_->NPV();
        cap_->setPricingEngine(engine_);
        return value;
    }
Real QuantLib::CapHelper::modelValue () const [virtual]
returns the price of the instrument according to the model
Implements QuantLib::CalibrationHelper.
Definition at line 104 of file caphelper.cpp.
References cap_, and QuantLib::CalibrationHelper::engine_.
{
        cap_->setPricingEngine(engine_);
        return cap_->NPV();
    }
Member Data Documentation
boost::shared_ptr<Cap> QuantLib::CapHelper::cap_ [private]
Definition at line 54 of file caphelper.hpp.
Referenced by addTimesTo(), blackPrice(), CapHelper(), and modelValue().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/shortrate/calibrationhelpers/caphelper.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/shortrate/calibrationhelpers/caphelper.cpp