QuantLib: QuantLib::TrinomialTree::Branching Class Reference
QuantLib::TrinomialTree::Branching Class Reference
Public Member Functions
Branching ()
Size descendant (Size index, Size branch) const
Real probability (Size index, Size branch) const
Size size () const
Integer jMin () const
Integer jMax () const
void add (Integer k, Real p1, Real p2, Real p3)
Private Attributes
std::vector< Integer > k_
std::vector< std::vector< Real > > probs_
Integer kMin_
Integer jMin_
Integer kMax_
Integer jMax_
Detailed Description
Definition at line 66 of file trinomialtree.hpp.
Constructor & Destructor Documentation
QuantLib::TrinomialTree::Branching::Branching () [inline]
Definition at line 105 of file trinomialtree.hpp.
    : probs_(3), kMin_(QL_MAX_INTEGER), jMin_(QL_MAX_INTEGER),
                 kMax_(QL_MIN_INTEGER), jMax_(QL_MIN_INTEGER) {}
Member Function Documentation
void QuantLib::TrinomialTree::Branching::add (Integer k, Real p1, Real p2, Real p3) [inline]
Definition at line 131 of file trinomialtree.hpp.
References QuantLib::anonymous_namespace{zigguratrng.cpp}::k_.
Referenced by QuantLib::TrinomialTree::TrinomialTree().
{
        // store
        k_.push_back(k);
        probs_[0].push_back(p1);
        probs_[1].push_back(p2);
        probs_[2].push_back(p3);
        // maintain invariants
        kMin_ = std::min(kMin_, k);
        jMin_ = kMin_ - 1;
        kMax_ = std::max(kMax_, k);
        jMax_ = kMax_ + 1;
    }
Size QuantLib::TrinomialTree::Branching::descendant (Size index, Size branch) const [inline]
Definition at line 109 of file trinomialtree.hpp.
References QuantLib::anonymous_namespace{zigguratrng.cpp}::k_.
{
        return k_[index] - jMin_ - 1 + branch;
    }
Integer QuantLib::TrinomialTree::Branching::jMax () const [inline]
Definition at line 127 of file trinomialtree.hpp.
Referenced by QuantLib::TrinomialTree::TrinomialTree().
{
        return jMax_;
    }
Integer QuantLib::TrinomialTree::Branching::jMin () const [inline]
Definition at line 123 of file trinomialtree.hpp.
Referenced by QuantLib::TrinomialTree::TrinomialTree().
{
        return jMin_;
    }
Real QuantLib::TrinomialTree::Branching::probability (Size index, Size branch) const [inline]
Definition at line 114 of file trinomialtree.hpp.
{
        return probs_[branch][index];
    }
Size QuantLib::TrinomialTree::Branching::size () const [inline]
Definition at line 119 of file trinomialtree.hpp.
{
        return jMax_ - jMin_ + 1;
    }
Member Data Documentation
Integer QuantLib::TrinomialTree::Branching::jMax_ [private]
Definition at line 78 of file trinomialtree.hpp.
Integer QuantLib::TrinomialTree::Branching::jMin_ [private]
Definition at line 78 of file trinomialtree.hpp.
std::vector<Integer> QuantLib::TrinomialTree::Branching::k_ [private]
Definition at line 76 of file trinomialtree.hpp.
Integer QuantLib::TrinomialTree::Branching::kMax_ [private]
Definition at line 78 of file trinomialtree.hpp.
Integer QuantLib::TrinomialTree::Branching::kMin_ [private]
Definition at line 78 of file trinomialtree.hpp.
std::vector<std::vector<Real> > QuantLib::TrinomialTree::Branching::probs_ [private]
Definition at line 77 of file trinomialtree.hpp.
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/lattices/trinomialtree.hpp