QuantLib: QuantLib::InflationCoupon Class Reference
QuantLib::InflationCoupon Class Reference
Base inflation-coupon class.
#include <inflationcoupon.hpp>
Public Member Functions
InflationCoupon (const Date &paymentDate, Real nominal, const Date &startDate, const Date &endDate, Natural fixingDays, const boost::shared_ptr< InflationIndex > &index, const Period &observationLag, const DayCounter &dayCounter, const Date &refPeriodStart=Date(), const Date &refPeriodEnd=Date())
void setPricer (const boost::shared_ptr< InflationCouponPricer > &)
boost::shared_ptr
< InflationCouponPricer > pricer () const
CashFlow interface
Real amount () const
returns the amount of the cash flow
Coupon interface
Real price (const Handle< YieldTermStructure > &discountingCurve) const
DayCounter dayCounter () const
day counter for accrual calculation
Real accruedAmount (const Date &) const
accrued amount at the given date
Rate rate () const
accrued rate
Inspectors
const boost::shared_ptr
< InflationIndex > & index () const
yoy inflation index
Period observationLag () const
how the coupon observes the index
Natural fixingDays () const
fixing days
virtual Date fixingDate () const
fixing date
virtual Rate indexFixing () const
fixing of the underlying index, as observed by the coupon
Observer interface
void update ()
Visitability
virtual void accept (AcyclicVisitor &)
Protected Member Functions
virtual bool checkPricerImpl (const boost::shared_ptr< InflationCouponPricer > &) const =0
makes sure you were given the correct type of pricer
Protected Attributes
boost::shared_ptr
< InflationCouponPricer > pricer_
boost::shared_ptr< InflationIndex > index_
Period observationLag_
DayCounter dayCounter_
Natural fixingDays_
Detailed Description
Base inflation-coupon class.
The day counter is usually obtained from the inflation term structure that the inflation index uses for forecasting. There is no gearing or spread because these are relevant for YoY coupons but not zero inflation coupons.
Note:
inflation indices do not contain day counters or calendars.
Definition at line 45 of file inflationcoupon.hpp.
Constructor & Destructor Documentation
QuantLib::InflationCoupon::InflationCoupon (const Date & paymentDate, Real nominal, const Date & startDate, const Date & endDate, Natural fixingDays, const boost::shared_ptr< InflationIndex > & index, const Period & observationLag, const DayCounter & dayCounter, const Date & refPeriodStart = Date(), const Date & refPeriodEnd = Date())
Definition at line 27 of file inflationcoupon.cpp.
References index_, QuantLib::Singleton< Settings >::instance(), and QuantLib::Observer::registerWith().
    : Coupon(paymentDate, nominal,
             startDate, endDate, refPeriodStart,refPeriodEnd),  // ref period is before lag
      index_(index), observationLag_(observationLag), dayCounter_(dayCounter),
      fixingDays_(fixingDays)
    {
        registerWith(index_);
        registerWith(Settings::instance().evaluationDate());
    }
Member Function Documentation
void QuantLib::InflationCoupon::accept (AcyclicVisitor & v) [inline, virtual]
Reimplemented from QuantLib::Coupon.
Reimplemented in QuantLib::CappedFlooredYoYInflationCoupon, QuantLib::CPICoupon, and QuantLib::YoYInflationCoupon.
Definition at line 116 of file inflationcoupon.hpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Visitor< T >::visit().
{
        Visitor<InflationCoupon>* v1 =
        dynamic_cast<Visitor<InflationCoupon>*>(&v);
        if (v1 != 0)
            v1->visit(*this);
        else
            Coupon::accept(v);
    }
Real QuantLib::InflationCoupon::accruedAmount (const Date &) const [virtual]
accrued amount at the given date
Implements QuantLib::Coupon.
Definition at line 69 of file inflationcoupon.cpp.
References QuantLib::Coupon::accrualEndDate_, QuantLib::Coupon::accrualStartDate_, dayCounter(), QuantLib::Coupon::nominal(), QuantLib::Coupon::paymentDate_, rate(), QuantLib::Coupon::refPeriodEnd_, QuantLib::Coupon::refPeriodStart_, and QuantLib::DayCounter::yearFraction().
{
        if (d <= accrualStartDate_ || d > paymentDate_) {
            return 0.0;
        } else {
            return nominal() * rate() *
            dayCounter().yearFraction(accrualStartDate_,
                                      std::min(d, accrualEndDate_),
                                      refPeriodStart_,
                                      refPeriodEnd_);
        }
    }
Real QuantLib::InflationCoupon::amount () const [inline, virtual]
returns the amount of the cash flow
Note:
The amount is not discounted, i.e., it is the actual amount paid at the cash flow date.
Implements QuantLib::CashFlow.
Definition at line 62 of file inflationcoupon.hpp.
References QuantLib::Coupon::accrualPeriod(), QuantLib::Coupon::nominal(), and rate().
Referenced by price().
{ return rate() * accrualPeriod() * nominal(); }
virtual bool QuantLib::InflationCoupon::checkPricerImpl (const boost::shared_ptr< InflationCouponPricer > &) const [protected, pure virtual]
makes sure you were given the correct type of pricer
Implemented in QuantLib::CPICoupon, and QuantLib::YoYInflationCoupon.
Referenced by setPricer().
DayCounter QuantLib::InflationCoupon::dayCounter () const [inline, virtual]
day counter for accrual calculation
Implements QuantLib::Coupon.
Definition at line 68 of file inflationcoupon.hpp.
References dayCounter_.
Referenced by accruedAmount().
{ return dayCounter_; }
Date QuantLib::InflationCoupon::fixingDate () const [virtual]
fixing date
Definition at line 82 of file inflationcoupon.cpp.
References QuantLib::Days, fixingDays_, index_, QuantLib::ModifiedPreceding, observationLag_, and QuantLib::Coupon::refPeriodEnd_.
Referenced by indexFixing(), QuantLib::CPICoupon::indexFixing(), QuantLib::CPICouponPricer::optionletPrice(), and QuantLib::YoYInflationCouponPricer::optionletPrice().
{
        // fixing calendar is usually the null calendar for inflation indices
        return index_->fixingCalendar().advance(refPeriodEnd_-observationLag_,
                        -static_cast<Integer>(fixingDays_), Days, ModifiedPreceding);
    }
Natural QuantLib::InflationCoupon::fixingDays () const [inline]
fixing days
Definition at line 80 of file inflationcoupon.hpp.
References fixingDays_.
{ return fixingDays_; }
const boost::shared_ptr<InflationIndex>& QuantLib::InflationCoupon::index () const [inline]
yoy inflation index
Definition at line 76 of file inflationcoupon.hpp.
References index_.
Referenced by QuantLib::CPICoupon::cpiIndex(), QuantLib::CPICouponPricer::initialize(), and QuantLib::YoYInflationCouponPricer::initialize().
{ return index_; }
Rate QuantLib::InflationCoupon::indexFixing () const [virtual]
fixing of the underlying index, as observed by the coupon
Reimplemented in QuantLib::CPICoupon.
Definition at line 95 of file inflationcoupon.cpp.
References fixingDate(), and index_.
Referenced by QuantLib::YoYInflationCouponPricer::adjustedFixing(), and QuantLib::YoYInflationCouponPricer::optionletPrice().
{
        return index_->fixing(fixingDate());
    }
Period QuantLib::InflationCoupon::observationLag () const [inline]
how the coupon observes the index
Definition at line 78 of file inflationcoupon.hpp.
References observationLag_.
{ return observationLag_; }
Real QuantLib::InflationCoupon::price (const Handle< YieldTermStructure > & discountingCurve) const
Definition at line 90 of file inflationcoupon.cpp.
References amount(), and QuantLib::Coupon::date().
{
        return amount() * discountingCurve->discount(date());
    }
boost::shared_ptr< InflationCouponPricer > QuantLib::InflationCoupon::pricer () const [inline]
Definition at line 126 of file inflationcoupon.hpp.
References pricer_.
Referenced by QuantLib::YoYInflationCoupon::checkPricerImpl(), QuantLib::CPICoupon::checkPricerImpl(), QuantLib::CappedFlooredYoYInflationCoupon::rate(), and setPricer().
{
        return pricer_;
    }
Rate QuantLib::InflationCoupon::rate () const [virtual]
accrued rate
Implements QuantLib::Coupon.
Reimplemented in QuantLib::CappedFlooredYoYInflationCoupon.
Definition at line 60 of file inflationcoupon.cpp.
References pricer_, and QL_REQUIRE.
Referenced by accruedAmount(), QuantLib::YoYInflationCoupon::adjustedFixing(), QuantLib::CPICoupon::adjustedFixing(), and amount().
{
        QL_REQUIRE(pricer_, "pricer not set");
        // we know it is the correct type because checkPricerImpl checks on setting
        // in general pricer_ will be a derived class, as will *this on calling
        pricer_->initialize(*this);
        return pricer_->swapletRate();
    }
void QuantLib::InflationCoupon::setPricer (const boost::shared_ptr< InflationCouponPricer > & pricer)
Definition at line 49 of file inflationcoupon.cpp.
References checkPricerImpl(), pricer(), pricer_, QL_REQUIRE, QuantLib::Observer::registerWith(), QuantLib::Observer::unregisterWith(), and update().
{
        QL_REQUIRE(checkPricerImpl(pricer),"pricer given is wrong type");
        if (pricer_)
            unregisterWith(pricer_);
        pricer_ = pricer;
        if (pricer_)
            registerWith(pricer_);
        update();
    }
void QuantLib::InflationCoupon::update () [inline, virtual]
This method must be implemented in derived classes. An instance of Observer does not call this method directly: instead, it will be called by the observables the instance registered with when they need to notify any changes.
Implements QuantLib::Observer.
Reimplemented in QuantLib::CappedFlooredYoYInflationCoupon.
Definition at line 89 of file inflationcoupon.hpp.
References QuantLib::Observable::notifyObservers().
Referenced by setPricer().
{ notifyObservers(); }
Member Data Documentation
DayCounter QuantLib::InflationCoupon::dayCounter_ [protected]
Definition at line 103 of file inflationcoupon.hpp.
Referenced by dayCounter().
Natural QuantLib::InflationCoupon::fixingDays_ [protected]
Definition at line 104 of file inflationcoupon.hpp.
Referenced by fixingDate(), and fixingDays().
boost::shared_ptr<InflationIndex> QuantLib::InflationCoupon::index_ [protected]
Definition at line 101 of file inflationcoupon.hpp.
Referenced by fixingDate(), index(), indexFixing(), and InflationCoupon().
Period QuantLib::InflationCoupon::observationLag_ [protected]
Definition at line 102 of file inflationcoupon.hpp.
Referenced by fixingDate(), and observationLag().
boost::shared_ptr<InflationCouponPricer> QuantLib::InflationCoupon::pricer_ [protected]
Definition at line 100 of file inflationcoupon.hpp.
Referenced by pricer(), rate(), QuantLib::CappedFlooredYoYInflationCoupon::rate(), and setPricer().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/inflationcoupon.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/inflationcoupon.cpp