QuantLib: QuantLib::FdmHullWhiteOp Class Reference
QuantLib::FdmHullWhiteOp Class Reference
#include <fdmhullwhiteop.hpp>
Public Member Functions
FdmHullWhiteOp (const boost::shared_ptr< FdmMesher > &mesher, const boost::shared_ptr< HullWhite > &model, Size direction)
Size size () const
void setTime (Time t1, Time t2)
Time \(t1 <= t2\) is required.
Disposable< Array > apply (const Array &r) const
Disposable< Array > apply_mixed (const Array &r) const
Disposable< Array > apply_direction (Size direction, const Array &r) const
Disposable< Array > solve_splitting (Size direction, const Array &r, Real s) const
Disposable< Array > preconditioner (const Array &r, Real s) const
Disposable< SparseMatrix > toMatrix () const
Private Attributes
const Size direction_
const Array x_
const TripleBandLinearOp dzMap_
TripleBandLinearOp mapT_
const boost::shared_ptr
< HullWhite > model_
Detailed Description
Definition at line 35 of file fdmhullwhiteop.hpp.
Constructor & Destructor Documentation
QuantLib::FdmHullWhiteOp::FdmHullWhiteOp (const boost::shared_ptr< FdmMesher > & mesher, const boost::shared_ptr< HullWhite > & model, Size direction)
Definition at line 32 of file fdmhullwhiteop.cpp.
    : direction_(direction),
      x_(mesher->locations(direction)),
      dzMap_(FirstDerivativeOp(direction, mesher).mult(-x_*model->a()).add(
                SecondDerivativeOp(direction, mesher)
                    .mult(0.5*model->sigma()*model->sigma()
                          *Array(mesher->layout()->size(), 1.0)))),
      mapT_(direction, mesher),
      model_(model) {
    }
Member Function Documentation
Disposable< Array > QuantLib::FdmHullWhiteOp::apply (const Array & r) const [virtual]
Implements QuantLib::FdmLinearOp.
Definition at line 61 of file fdmhullwhiteop.cpp.
References QuantLib::TripleBandLinearOp::apply(), and mapT_.
Referenced by QuantLib::FdmHestonHullWhiteOp::apply(), and QuantLib::FdmHestonHullWhiteOp::apply_direction().
{
        return mapT_.apply(r);
    }
Disposable< Array > QuantLib::FdmHullWhiteOp::apply_direction (Size direction, const Array & r) const [virtual]
Implements QuantLib::FdmLinearOpComposite.
Definition at line 71 of file fdmhullwhiteop.cpp.
References QuantLib::TripleBandLinearOp::apply(), direction_, mapT_, and QuantLib::Array::size().
{
        if (direction == direction_)
            return mapT_.apply(r);
        else {
            Array retVal(r.size(), 0.0);
            return retVal;
        }
    }
Disposable< Array > QuantLib::FdmHullWhiteOp::apply_mixed (const Array & r) const [virtual]
Implements QuantLib::FdmLinearOpComposite.
Definition at line 65 of file fdmhullwhiteop.cpp.
References QuantLib::Array::size().
{
        Array retVal(r.size(), 0.0);
        return retVal;
    }
Disposable< Array > QuantLib::FdmHullWhiteOp::preconditioner (const Array & r, Real s) const [virtual]
Implements QuantLib::FdmLinearOpComposite.
Definition at line 93 of file fdmhullwhiteop.cpp.
References direction_, and solve_splitting().
{
        return solve_splitting(direction_, r, dt);
    }
void QuantLib::FdmHullWhiteOp::setTime (Time t1, Time t2) [virtual]
Time \(t1 <= t2\) is required.
Implements QuantLib::FdmLinearOpComposite.
Definition at line 50 of file fdmhullwhiteop.cpp.
References QuantLib::TripleBandLinearOp::axpyb(), dzMap_, mapT_, model_, QuantLib::anonymous_namespace{bjerksundstenslandengine.cpp}::phi(), and x_.
Referenced by QuantLib::FdmHestonHullWhiteOp::setTime().
{
        const boost::shared_ptr<OneFactorModel::ShortRateDynamics> dynamics =
            model_->dynamics();
        const Real phi = 0.5*(  dynamics->shortRate(t1, 0.0)
                              + dynamics->shortRate(t2, 0.0));
        mapT_.axpyb(Array(), dzMap_, dzMap_, -(x_+phi));
    }
Size QuantLib::FdmHullWhiteOp::size () const [virtual]
Implements QuantLib::FdmLinearOpComposite.
Definition at line 46 of file fdmhullwhiteop.cpp.
{
        return 1u;
    }
Disposable< Array > QuantLib::FdmHullWhiteOp::solve_splitting (Size direction, const Array & r, Real s) const [virtual]
Implements QuantLib::FdmLinearOpComposite.
Definition at line 80 of file fdmhullwhiteop.cpp.
References direction_, mapT_, QuantLib::Array::size(), and QuantLib::TripleBandLinearOp::solve_splitting().
Referenced by preconditioner(), and QuantLib::FdmHestonHullWhiteOp::solve_splitting().
{
        if (direction == direction_) {
            return mapT_.solve_splitting(r, a, 1.0);
        }
        else {
            Array retVal(r.size(), 0.0);
            return retVal;
        }
    }
Disposable< SparseMatrix > QuantLib::FdmHullWhiteOp::toMatrix () const [virtual]
Reimplemented from QuantLib::FdmLinearOp.
Definition at line 98 of file fdmhullwhiteop.cpp.
References mapT_, and QuantLib::TripleBandLinearOp::toMatrix().
Referenced by QuantLib::FdmHestonHullWhiteOp::toMatrix().
{
        return mapT_.toMatrix();
    }
Member Data Documentation
const Size QuantLib::FdmHullWhiteOp::direction_ [private]
Definition at line 59 of file fdmhullwhiteop.hpp.
Referenced by apply_direction(), preconditioner(), and solve_splitting().
const TripleBandLinearOp QuantLib::FdmHullWhiteOp::dzMap_ [private]
Definition at line 61 of file fdmhullwhiteop.hpp.
Referenced by setTime().
TripleBandLinearOp QuantLib::FdmHullWhiteOp::mapT_ [private]
Definition at line 62 of file fdmhullwhiteop.hpp.
Referenced by apply(), apply_direction(), setTime(), solve_splitting(), and toMatrix().
const boost::shared_ptr<HullWhite> QuantLib::FdmHullWhiteOp::model_ [private]
Definition at line 63 of file fdmhullwhiteop.hpp.
Referenced by setTime().
const Array QuantLib::FdmHullWhiteOp::x_ [private]
Definition at line 60 of file fdmhullwhiteop.hpp.
Referenced by setTime().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/operators/fdmhullwhiteop.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/operators/fdmhullwhiteop.cpp