QuantLib: QuantLib::CallableBond Class Reference
QuantLib::CallableBond Class Reference
Callable bond base class.
#include <callablebond.hpp>
Classes
class arguments
class engine
base class for callable fixed rate bond engine
class ImpliedVolHelper
class results
results for a callable bond calculation
Public Member Functions
virtual void setupArguments (PricingEngine::arguments *) const
Inspectors
const CallabilitySchedule & callability () const
return the bond's put/call schedule
Calculations
Volatility impliedVolatility (Real targetValue, const Handle< YieldTermStructure > &discountCurve, Real accuracy, Size maxEvaluations, Volatility minVol, Volatility maxVol) const
returns the Black implied forward yield volatility
Protected Member Functions
CallableBond (Natural settlementDays, const Schedule &schedule, const DayCounter &paymentDayCounter, const Date &issueDate=Date(), const CallabilitySchedule &putCallSchedule=CallabilitySchedule())
Protected Attributes
DayCounter paymentDayCounter_
Frequency frequency_
CallabilitySchedule putCallSchedule_
boost::shared_ptr< PricingEngine > blackEngine_
must be set by derived classes for impliedVolatility() to work
RelinkableHandle< Quote > blackVolQuote_
Black fwd yield volatility quote handle to internal blackEngine_.
RelinkableHandle
< YieldTermStructure > blackDiscountCurve_
Black fwd yield volatility quote handle to internal blackEngine_.
Friends
class ImpliedVolHelper
Detailed Description
Callable bond base class.
Base callable bond class for fixed and zero coupon bonds. Defines commonalities between fixed and zero coupon callable bonds. At present, only European and Bermudan put/call schedules supported (no American optionality), as defined by the Callability class.
Todo:
models/shortrate/calibrationHelpers
OAS/OAD
floating rate callable bonds ?
Definition at line 52 of file callablebond.hpp.
Constructor & Destructor Documentation
QuantLib::CallableBond::CallableBond (Natural settlementDays, const Schedule & schedule, const DayCounter & paymentDayCounter, const Date & issueDate = Date(), const CallabilitySchedule & putCallSchedule = CallabilitySchedule()) [protected]
Definition at line 27 of file callablebond.cpp.
References QuantLib::Schedule::dates(), QuantLib::Bond::maturityDate_, QuantLib::Date::minDate(), putCallSchedule_, and QL_REQUIRE.
    : Bond(settlementDays, schedule.calendar(), issueDate),
      paymentDayCounter_(paymentDayCounter), putCallSchedule_(putCallSchedule) {
        maturityDate_ = schedule.dates().back();
        if (!putCallSchedule_.empty()) {
            Date finalOptionDate = Date::minDate();
            for (Size i=0; i<putCallSchedule_.size();++i) {
                finalOptionDate=std::max(finalOptionDate,
                                         putCallSchedule_[i]->date());
            }
            QL_REQUIRE(finalOptionDate <= maturityDate_ ,
                       "Bond cannot mature before last call/put date");
        }
        // derived classes must set cashflows_ and frequency_
    }
Member Function Documentation
const CallabilitySchedule& QuantLib::CallableBond::callability () const [inline]
return the bond's put/call schedule
Definition at line 60 of file callablebond.hpp.
References putCallSchedule_.
{
            return putCallSchedule_;
        }
Volatility QuantLib::CallableBond::impliedVolatility (Real targetValue, const Handle< YieldTermStructure > & discountCurve, Real accuracy, Size maxEvaluations, Volatility minVol, Volatility maxVol) const
returns the Black implied forward yield volatility
the forward yield volatility, see Hull, Fourth Edition, Chapter 20, pg 536). Relevant only to European put/call schedules
Definition at line 93 of file callablebond.cpp.
References blackDiscountCurve_, QuantLib::Instrument::calculate(), anonymous_namespace{interpolations.cpp}::f(), QuantLib::Bond::isExpired(), QuantLib::RelinkableHandle< T >::linkTo(), QL_REQUIRE, QuantLib::Solver1D< Impl >::setMaxEvaluations(), and QuantLib::Solver1D< Impl >::solve().
{
        calculate();
        QL_REQUIRE(!isExpired(), "instrument expired");
        Volatility guess = 0.5*(minVol + maxVol);
        blackDiscountCurve_.linkTo(*discountCurve, false);
        ImpliedVolHelper f(*this,targetValue);
        Brent solver;
        solver.setMaxEvaluations(maxEvaluations);
        return solver.solve(f, accuracy, guess, minVol, maxVol);
    }
virtual void QuantLib::CallableBond::setupArguments (PricingEngine::arguments *) const [inline, virtual]
When a derived argument structure is defined for an instrument, this method should be overridden to fill it. This is mandatory in case a pricing engine is used.
Reimplemented from QuantLib::Bond.
Reimplemented in QuantLib::CallableFixedRateBond.
Definition at line 79 of file callablebond.hpp.
Referenced by QuantLib::CallableBond::ImpliedVolHelper::ImpliedVolHelper().
{}
Friends And Related Function Documentation
friend class ImpliedVolHelper [friend]
Definition at line 99 of file callablebond.hpp.
Member Data Documentation
RelinkableHandle<YieldTermStructure> QuantLib::CallableBond::blackDiscountCurve_ [mutable, protected]
Black fwd yield volatility quote handle to internal blackEngine_.
Definition at line 97 of file callablebond.hpp.
Referenced by QuantLib::CallableFixedRateBond::CallableFixedRateBond(), and impliedVolatility().
boost::shared_ptr<PricingEngine> QuantLib::CallableBond::blackEngine_ [mutable, protected]
must be set by derived classes for impliedVolatility() to work
Definition at line 93 of file callablebond.hpp.
Referenced by QuantLib::CallableFixedRateBond::CallableFixedRateBond(), and QuantLib::CallableBond::ImpliedVolHelper::ImpliedVolHelper().
RelinkableHandle<Quote> QuantLib::CallableBond::blackVolQuote_ [mutable, protected]
Black fwd yield volatility quote handle to internal blackEngine_.
Definition at line 95 of file callablebond.hpp.
Referenced by QuantLib::CallableFixedRateBond::CallableFixedRateBond(), and QuantLib::CallableBond::ImpliedVolHelper::ImpliedVolHelper().
Frequency QuantLib::CallableBond::frequency_ [protected]
Definition at line 90 of file callablebond.hpp.
Referenced by QuantLib::CallableFixedRateBond::CallableFixedRateBond(), and QuantLib::CallableFixedRateBond::setupArguments().
DayCounter QuantLib::CallableBond::paymentDayCounter_ [protected]
Definition at line 89 of file callablebond.hpp.
Referenced by QuantLib::CallableFixedRateBond::setupArguments().
CallabilitySchedule QuantLib::CallableBond::putCallSchedule_ [protected]
Definition at line 91 of file callablebond.hpp.
Referenced by callability(), CallableBond(), and QuantLib::CallableFixedRateBond::setupArguments().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/callablebonds/callablebond.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/callablebonds/callablebond.cpp