QuantLib: QuantLib::GeneralizedBlackScholesProcess Class Reference
QuantLib::GeneralizedBlackScholesProcess Class Reference
Generalized Black-Scholes stochastic process.
#include <blackscholesprocess.hpp>
Public Member Functions
GeneralizedBlackScholesProcess (const Handle< Quote > &x0, const Handle< YieldTermStructure > &dividendTS, const Handle< YieldTermStructure > &riskFreeTS, const Handle< BlackVolTermStructure > &blackVolTS, const boost::shared_ptr< discretization > &d=boost::shared_ptr< discretization >(new EulerDiscretization))
Time time (const Date &) const
StochasticProcess1D interface
Real x0 () const
returns the initial value of the state variable
Real drift (Time t, Real x) const
Real diffusion (Time t, Real x) const
Real apply (Real x0, Real dx) const
Real expectation (Time t0, Real x0, Time dt) const
Real evolve (Time t0, Real x0, Time dt, Real dw) const
Observer interface
void update ()
Inspectors
const Handle< Quote > & stateVariable () const
const Handle
< YieldTermStructure > & dividendYield () const
const Handle
< YieldTermStructure > & riskFreeRate () const
const Handle
< BlackVolTermStructure > & blackVolatility () const
const Handle
< LocalVolTermStructure > & localVolatility () const
Private Attributes
Handle< Quote > x0_
Handle< YieldTermStructure > riskFreeRate_
Handle< YieldTermStructure > dividendYield_
Handle< BlackVolTermStructure > blackVolatility_
RelinkableHandle
< LocalVolTermStructure > localVolatility_
bool updated_
Detailed Description
Generalized Black-Scholes stochastic process.
This class describes the stochastic process governed by
\[ dS(t, S) = (r(t) - q(t) - \frac{\sigma(t, S)^2}{2}) dt + \sigma dW_t. \]
Definition at line 47 of file blackscholesprocess.hpp.
Constructor & Destructor Documentation
QuantLib::GeneralizedBlackScholesProcess::GeneralizedBlackScholesProcess (const Handle< Quote > & x0, const Handle< YieldTermStructure > & dividendTS, const Handle< YieldTermStructure > & riskFreeTS, const Handle< BlackVolTermStructure > & blackVolTS, const boost::shared_ptr< discretization > & d = boost::shared_ptr<discretization>(new EulerDiscretization))
Definition at line 32 of file blackscholesprocess.cpp.
References blackVolatility_, dividendYield_, QuantLib::Observer::registerWith(), riskFreeRate_, and x0_.
    : StochasticProcess1D(disc), x0_(x0), riskFreeRate_(riskFreeTS),
      dividendYield_(dividendTS), blackVolatility_(blackVolTS),
      updated_(false) {
        registerWith(x0_);
        registerWith(riskFreeRate_);
        registerWith(dividendYield_);
        registerWith(blackVolatility_);
    }
Member Function Documentation
Real QuantLib::GeneralizedBlackScholesProcess::apply (Real x0, Real dx) const [virtual]
applies a change to the asset value. By default, it returns \(x + \Delta x \).
Reimplemented from QuantLib::StochasticProcess1D.
Definition at line 65 of file blackscholesprocess.cpp.
Referenced by QuantLib::ExtendedBlackScholesMertonProcess::evolve(), and evolve().
{
        return x0 * std::exp(dx);
    }
const Handle< BlackVolTermStructure > & QuantLib::GeneralizedBlackScholesProcess::blackVolatility () const
Definition at line 107 of file blackscholesprocess.cpp.
References blackVolatility_.
Referenced by QuantLib::ExtendedBlackScholesMertonProcess::diffusion(), and localVolatility().
{
        return blackVolatility_;
    }
Real QuantLib::GeneralizedBlackScholesProcess::diffusion (Time t, Real x) const [virtual]
Todo:
revise extrapolation
Implements QuantLib::StochasticProcess1D.
Reimplemented in QuantLib::ExtendedBlackScholesMertonProcess, and QuantLib::VegaStressedBlackScholesProcess.
Definition at line 61 of file blackscholesprocess.cpp.
References localVolatility().
Referenced by drift().
{
        return localVolatility()->localVol(t, x, true);
    }
const Handle< YieldTermStructure > & QuantLib::GeneralizedBlackScholesProcess::dividendYield () const
Definition at line 97 of file blackscholesprocess.cpp.
References dividendYield_.
Referenced by QuantLib::FFTVanillaEngine::dividendYield(), QuantLib::ExtendedBlackScholesMertonProcess::drift(), and QuantLib::ExtendedBlackScholesMertonProcess::evolve().
{
        return dividendYield_;
    }
Real QuantLib::GeneralizedBlackScholesProcess::drift (Time t, Real x) const [virtual]
Todo:
revise extrapolation
Implements QuantLib::StochasticProcess1D.
Reimplemented in QuantLib::ExtendedBlackScholesMertonProcess.
Definition at line 51 of file blackscholesprocess.cpp.
References QuantLib::Continuous, diffusion(), dividendYield_, QuantLib::NoFrequency, riskFreeRate_, and anonymous_namespace{distributions.cpp}::sigma.
{
        Real sigma = diffusion(t,x);
        // we could be more anticipatory if we know the right dt
        // for which the drift will be used
        Time t1 = t + 0.0001;
        return riskFreeRate_->forwardRate(t,t1,Continuous,NoFrequency,true)
             - dividendYield_->forwardRate(t,t1,Continuous,NoFrequency,true)
             - 0.5 * sigma * sigma;
    }
Real QuantLib::GeneralizedBlackScholesProcess::evolve (Time t0, Real x0, Time dt, Real dw) const [virtual]
returns the asset value after a time interval \(\Delta t \) according to the given discretization. By default, it returns
\[ E(x_0,t_0,\Delta t) + S(x_0,t_0,\Delta t) \cdot \Delta w \]
where \(E \) is the expectation and \(S \) the standard deviation.
Reimplemented from QuantLib::StochasticProcess1D.
Reimplemented in QuantLib::ExtendedBlackScholesMertonProcess.
Definition at line 75 of file blackscholesprocess.cpp.
References apply(), QuantLib::StochasticProcess1D::discretization_, and QuantLib::StochasticProcess1D::stdDeviation().
{
        return apply(x0, discretization_->drift(*this,t0,x0,dt) +
                         stdDeviation(t0,x0,dt)*dw);
    }
Real QuantLib::GeneralizedBlackScholesProcess::expectation (Time t0, Real x0, Time dt) const [virtual]
Warning:
raises a "not implemented" exception. It should be rewritten to return the expectation E(S) of the process, not exp(E(log S)).
Reimplemented from QuantLib::StochasticProcess1D.
Definition at line 69 of file blackscholesprocess.cpp.
References QL_FAIL.
Referenced by QuantLib::ExtendedBlackScholesMertonProcess::evolve().
{
        QL_FAIL("not implemented");
    }
const Handle< LocalVolTermStructure > & QuantLib::GeneralizedBlackScholesProcess::localVolatility () const
Definition at line 112 of file blackscholesprocess.cpp.
References blackVolatility(), blackVolatility_, dividendYield_, QuantLib::RelinkableHandle< T >::linkTo(), localVolatility_, riskFreeRate_, updated_, and x0_.
Referenced by diffusion().
{
        if (!updated_) {
            // constant Black vol?
            boost::shared_ptr<BlackConstantVol> constVol =
                boost::dynamic_pointer_cast<BlackConstantVol>(
                                                          *blackVolatility());
            if (constVol) {
                // ok, the local vol is constant too.
                localVolatility_.linkTo(
                    boost::shared_ptr<LocalVolTermStructure>(new
                        LocalConstantVol(constVol->referenceDate(),
                                         constVol->blackVol(0.0, x0_->value()),
                                         constVol->dayCounter())));
                updated_ = true;
                return localVolatility_;
            }
            // ok, so it's not constant. Maybe it's strike-independent?
            boost::shared_ptr<BlackVarianceCurve> volCurve =
                boost::dynamic_pointer_cast<BlackVarianceCurve>(
                                                          *blackVolatility());
            if (volCurve) {
                // ok, we can use the optimized algorithm
                localVolatility_.linkTo(
                    boost::shared_ptr<LocalVolTermStructure>(
                        new LocalVolCurve(
                                      Handle<BlackVarianceCurve>(volCurve))));
                updated_ = true;
                return localVolatility_;
            }
            // ok, so it's strike-dependent. Never mind.
            localVolatility_.linkTo(
                      boost::shared_ptr<LocalVolTermStructure>(
                          new LocalVolSurface(blackVolatility_, riskFreeRate_,
                                              dividendYield_, x0_->value())));
            updated_ = true;
            return localVolatility_;
        } else {
            return localVolatility_;
        }
    }
const Handle< YieldTermStructure > & QuantLib::GeneralizedBlackScholesProcess::riskFreeRate () const
Definition at line 102 of file blackscholesprocess.cpp.
References riskFreeRate_.
Referenced by QuantLib::FFTVanillaEngine::discountFactor(), QuantLib::ExtendedBlackScholesMertonProcess::drift(), and QuantLib::ExtendedBlackScholesMertonProcess::evolve().
{
        return riskFreeRate_;
    }
const Handle< Quote > & QuantLib::GeneralizedBlackScholesProcess::stateVariable () const
Definition at line 92 of file blackscholesprocess.cpp.
References x0_.
{
        return x0_;
    }
Time QuantLib::GeneralizedBlackScholesProcess::time (const Date &) const [virtual]
returns the time value corresponding to the given date in the reference system of the stochastic process.
Note:
As a number of processes might not need this functionality, a default implementation is given which raises an exception.
Reimplemented from QuantLib::StochasticProcess.
Definition at line 81 of file blackscholesprocess.cpp.
References anonymous_namespace{marketmodel.cpp}::d, and riskFreeRate_.
{
        return riskFreeRate_->dayCounter().yearFraction(
                                           riskFreeRate_->referenceDate(), d);
    }
void QuantLib::GeneralizedBlackScholesProcess::update () [virtual]
This method must be implemented in derived classes. An instance of Observer does not call this method directly: instead, it will be called by the observables the instance registered with when they need to notify any changes.
Reimplemented from QuantLib::StochasticProcess.
Definition at line 86 of file blackscholesprocess.cpp.
References updated_.
Referenced by QuantLib::VegaStressedBlackScholesProcess::setLowerAssetBorderForStressTest(), QuantLib::VegaStressedBlackScholesProcess::setLowerTimeBorderForStressTest(), QuantLib::VegaStressedBlackScholesProcess::setStressLevel(), QuantLib::VegaStressedBlackScholesProcess::setUpperAssetBorderForStressTest(), and QuantLib::VegaStressedBlackScholesProcess::setUpperTimeBorderForStressTest().
{
        updated_ = false;
        StochasticProcess1D::update();
    }
Real QuantLib::GeneralizedBlackScholesProcess::x0 () const [virtual]
returns the initial value of the state variable
Implements QuantLib::StochasticProcess1D.
Definition at line 47 of file blackscholesprocess.cpp.
References x0_.
{
        return x0_->value();
    }
Member Data Documentation
Handle<BlackVolTermStructure> QuantLib::GeneralizedBlackScholesProcess::blackVolatility_ [private]
Definition at line 87 of file blackscholesprocess.hpp.
Referenced by blackVolatility(), GeneralizedBlackScholesProcess(), and localVolatility().
Handle<YieldTermStructure> QuantLib::GeneralizedBlackScholesProcess::dividendYield_ [private]
Definition at line 86 of file blackscholesprocess.hpp.
Referenced by dividendYield(), drift(), GeneralizedBlackScholesProcess(), and localVolatility().
RelinkableHandle<LocalVolTermStructure> QuantLib::GeneralizedBlackScholesProcess::localVolatility_ [mutable, private]
Definition at line 88 of file blackscholesprocess.hpp.
Referenced by localVolatility().
Handle<YieldTermStructure> QuantLib::GeneralizedBlackScholesProcess::riskFreeRate_ [private]
Definition at line 86 of file blackscholesprocess.hpp.
Referenced by drift(), GeneralizedBlackScholesProcess(), localVolatility(), riskFreeRate(), and time().
bool QuantLib::GeneralizedBlackScholesProcess::updated_ [mutable, private]
Definition at line 89 of file blackscholesprocess.hpp.
Referenced by localVolatility(), and update().
Handle<Quote> QuantLib::GeneralizedBlackScholesProcess::x0_ [private]
Definition at line 85 of file blackscholesprocess.hpp.
Referenced by GeneralizedBlackScholesProcess(), localVolatility(), stateVariable(), and x0().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/processes/blackscholesprocess.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/processes/blackscholesprocess.cpp