QuantLib: QuantLib::ProxyGreekEngine Class Reference
QuantLib::ProxyGreekEngine Class Reference
#include <proxygreekengine.hpp>
Public Member Functions
ProxyGreekEngine (const boost::shared_ptr< MarketModelEvolver > &evolver, const std::vector< std::vector< boost::shared_ptr< ConstrainedEvolver > > > &constrainedEvolvers, const std::vector< std::vector< std::vector< Real > > > &diffWeights, const std::vector< Size > &startIndexOfConstraint, const std::vector< Size > &endIndexOfConstraint, const Clone< MarketModelMultiProduct > &product, Real initialNumeraireValue)
void multiplePathValues (SequenceStatisticsInc &stats, std::vector< std::vector< SequenceStatisticsInc > > &modifiedStats, Size numberOfPaths)
void singlePathValues (std::vector< Real > &values, std::vector< std::vector< std::vector< Real > > > &modifiedValues)
Private Member Functions
void singleEvolverValues (MarketModelEvolver &evolver, std::vector< Real > &values, bool storeRates=false)
Private Attributes
boost::shared_ptr
< MarketModelEvolver > originalEvolver_
std::vector< std::vector
< boost::shared_ptr
< ConstrainedEvolver > > > constrainedEvolvers_
std::vector< std::vector
< std::vector< Real > > > diffWeights_
std::vector< Size > startIndexOfConstraint_
std::vector< Size > endIndexOfConstraint_
Clone< MarketModelMultiProduct > product_
Real initialNumeraireValue_
Size numberProducts_
std::vector< Rate > constraints_
std::valarray< bool > constraintsActive_
std::vector< Real > numerairesHeld_
std::vector< Size > numberCashFlowsThisStep_
std::vector< std::vector
< MarketModelMultiProduct::CashFlow > > cashFlowsGenerated_
std::vector
< MarketModelDiscounter > discounters_
Detailed Description
Definition at line 37 of file proxygreekengine.hpp.
Constructor & Destructor Documentation
QuantLib::ProxyGreekEngine::ProxyGreekEngine (const boost::shared_ptr< MarketModelEvolver > & evolver, const std::vector< std::vector< boost::shared_ptr< ConstrainedEvolver > > > & constrainedEvolvers, const std::vector< std::vector< std::vector< Real > > > & diffWeights, const std::vector< Size > & startIndexOfConstraint, const std::vector< Size > & endIndexOfConstraint, const Clone< MarketModelMultiProduct > & product, Real initialNumeraireValue)
Definition at line 29 of file proxygreekengine.cpp.
References cashFlowsGenerated_, constraints_, constraintsActive_, discounters_, QuantLib::MarketModelMultiProduct::evolution(), QuantLib::EvolutionDescription::evolutionTimes(), QuantLib::MarketModelMultiProduct::maxNumberOfCashFlowsPerProductPerStep(), numberProducts_, QuantLib::MarketModelMultiProduct::possibleCashFlowTimes(), product_, QuantLib::EvolutionDescription::rateTimes(), and anonymous_namespace{marketmodel.cpp}::rateTimes.
    : originalEvolver_(evolver), constrainedEvolvers_(constrainedEvolvers),
      diffWeights_(diffWeights),
      startIndexOfConstraint_(startIndexOfConstraint),
      endIndexOfConstraint_(endIndexOfConstraint),
      product_(product),
      initialNumeraireValue_(initialNumeraireValue),
      numberProducts_(product->numberOfProducts()),
      numerairesHeld_(product->numberOfProducts()),
      numberCashFlowsThisStep_(product->numberOfProducts()),
      cashFlowsGenerated_(product->numberOfProducts()) {
        for (Size i=0; i<numberProducts_; ++i)
            cashFlowsGenerated_[i].resize(
                       product_->maxNumberOfCashFlowsPerProductPerStep());
        const std::vector<Time>& cashFlowTimes =
            product_->possibleCashFlowTimes();
        const std::vector<Rate>& rateTimes = product_->evolution().rateTimes();
        Size n = cashFlowTimes.size();
        discounters_.reserve(n);
        for (Size j=0; j<n; ++j)
            discounters_.push_back(MarketModelDiscounter(cashFlowTimes[j],
                                                         rateTimes));
        const std::vector<Rate>& evolutionTimes =
            product_->evolution().evolutionTimes();
        constraints_.resize(evolutionTimes.size());
        constraintsActive_.resize(evolutionTimes.size());
    }
Member Function Documentation
void QuantLib::ProxyGreekEngine::multiplePathValues (SequenceStatisticsInc & stats, std::vector< std::vector< SequenceStatisticsInc > > & modifiedStats, Size numberOfPaths)
Definition at line 81 of file proxygreekengine.cpp.
References QuantLib::GenericSequenceStatistics< StatisticsType >::add(), constrainedEvolvers_, diffWeights_, anonymous_namespace{matrices.cpp}::N, QuantLib::MarketModelMultiProduct::numberOfProducts(), product_, singlePathValues(), and anonymous_namespace{stats.cpp}::weights.
Referenced by MarketModelTest::testGreeks().
{
        Size N = product_->numberOfProducts();
        std::vector<Real> values(N);
        std::vector<std::vector<std::vector<Real> > > modifiedValues;
        modifiedValues.resize(constrainedEvolvers_.size());
        for (Size i=0; i<modifiedValues.size(); ++i) {
            modifiedValues[i].resize(constrainedEvolvers_[i].size());
            for (Size j=0; j<modifiedValues[i].size(); ++j)
                modifiedValues[i][j].resize(N);
        }
        std::vector<Real> results(N);
        for (Size i=0; i<numberOfPaths; ++i) {
            singlePathValues(values, modifiedValues);
            stats.add(values);
            for (Size j=0; j<diffWeights_.size(); ++j) {
                for (Size k=0; k<diffWeights_[j].size(); ++k) {
                    const std::vector<Real>& weights = diffWeights_[j][k];
                    for (Size l=0; l<N; ++l) {
                        results[l] = weights[0]*values[l];
                        for (Size n=1; n<weights.size(); ++n)
                            results[l] += weights[n]*modifiedValues[j][n-1][l];
                    }
                    modifiedStats[j][k].add(results);
                }
            }
        }
    }
void QuantLib::ProxyGreekEngine::singleEvolverValues (MarketModelEvolver & evolver, std::vector< Real > & values, bool storeRates = false) [private]
Definition at line 116 of file proxygreekengine.cpp.
References QuantLib::MarketModelEvolver::advanceStep(), cashFlowsGenerated_, constraints_, constraintsActive_, QuantLib::MarketModelEvolver::currentState(), QuantLib::MarketModelEvolver::currentStep(), discounters_, QuantLib::CurveState::discountRatio(), endIndexOfConstraint_, initialNumeraireValue_, QuantLib::MarketModelMultiProduct::nextTimeStep(), numberCashFlowsThisStep_, numberProducts_, QuantLib::MarketModelDiscounter::numeraireBonds(), QuantLib::MarketModelEvolver::numeraires(), numerairesHeld_, product_, QuantLib::MarketModelMultiProduct::reset(), startIndexOfConstraint_, QuantLib::MarketModelEvolver::startNewPath(), and QuantLib::CurveState::swapRate().
Referenced by singlePathValues().
{
        std::fill(numerairesHeld_.begin(), numerairesHeld_.end(), 0.0);
        Real weight = evolver.startNewPath();
        product_->reset();
        Real principalInNumerairePortfolio = 1.0;
        if (storeRates)
            constraintsActive_ =false;
        //            std::fill(constraintsActive_.begin(),
        //                    constraintsActive_.end(),
        //                  false);
        //  }
        bool done = false;
        do {
            Size thisStep = evolver.currentStep();
            weight *= evolver.advanceStep();
            done = product_->nextTimeStep(evolver.currentState(),
                                          numberCashFlowsThisStep_,
                                          cashFlowsGenerated_);
            if (storeRates) {
                constraints_[thisStep] = evolver.currentState().swapRate(
                                        startIndexOfConstraint_[thisStep],
                                        endIndexOfConstraint_[thisStep]);
                constraintsActive_[thisStep] = true;
            }
            Size numeraire =
                evolver.numeraires()[thisStep];
            // for each product...
            for (Size i=0; i<numberProducts_; ++i) {
                // ...and each cash flow...
                const std::vector<MarketModelMultiProduct::CashFlow>& cashflows =
                    cashFlowsGenerated_[i];
                for (Size j=0; j<numberCashFlowsThisStep_[i]; ++j) {
                    // ...convert the cash flow to numeraires.
                    // This is done by calculating the number of
                    // numeraire bonds corresponding to such cash flow...
                    const MarketModelDiscounter& discounter =
                        discounters_[cashflows[j].timeIndex];
                    Real bonds = cashflows[j].amount *
                        discounter.numeraireBonds(evolver.currentState(),
                                                  numeraire);
                    // ...and adding the newly bought bonds to the number
                    // of numeraires held.
                    numerairesHeld_[i] +=
                        weight*bonds/principalInNumerairePortfolio;
                }
            }
            if (!done) {
                // The numeraire might change between steps. This implies
                // that we might have to convert the numeraire bonds for
                // this step into a corresponding amount of numeraire
                // bonds for the next step. This can be done by changing
                // the principal of the numeraire and updating the number
                // of bonds in the numeraire portfolio accordingly.
                Size nextNumeraire = evolver.numeraires()[thisStep+1];
                principalInNumerairePortfolio *=
                    evolver.currentState().discountRatio(numeraire,
                                                         nextNumeraire);
            }
        } while (!done);
        for (Size i=0; i<numerairesHeld_.size(); ++i)
            values[i] = numerairesHeld_[i] * initialNumeraireValue_;
    }
void QuantLib::ProxyGreekEngine::singlePathValues (std::vector< Real > & values, std::vector< std::vector< std::vector< Real > > > & modifiedValues)
Definition at line 67 of file proxygreekengine.cpp.
References constrainedEvolvers_, constraints_, constraintsActive_, originalEvolver_, and singleEvolverValues().
Referenced by multiplePathValues().
{
        singleEvolverValues(*originalEvolver_, values, true);
        for (Size i=0; i<constrainedEvolvers_.size(); ++i) {
            for (Size j=0; j<constrainedEvolvers_[i].size(); ++j) {
                constrainedEvolvers_[i][j]->setThisConstraint(
                                            constraints_, constraintsActive_);
                singleEvolverValues(*(constrainedEvolvers_[i][j]),
                                    modifiedValues[i][j]);
            }
        }
    }
Member Data Documentation
std::vector<std::vector<MarketModelMultiProduct::CashFlow> > QuantLib::ProxyGreekEngine::cashFlowsGenerated_ [private]
Definition at line 77 of file proxygreekengine.hpp.
Referenced by ProxyGreekEngine(), and singleEvolverValues().
std::vector<std::vector<boost::shared_ptr<ConstrainedEvolver> > > QuantLib::ProxyGreekEngine::constrainedEvolvers_ [private]
Definition at line 62 of file proxygreekengine.hpp.
Referenced by multiplePathValues(), and singlePathValues().
std::vector<Rate> QuantLib::ProxyGreekEngine::constraints_ [private]
Definition at line 72 of file proxygreekengine.hpp.
Referenced by ProxyGreekEngine(), singleEvolverValues(), and singlePathValues().
std::valarray<bool> QuantLib::ProxyGreekEngine::constraintsActive_ [private]
Definition at line 73 of file proxygreekengine.hpp.
Referenced by ProxyGreekEngine(), singleEvolverValues(), and singlePathValues().
std::vector<std::vector<std::vector<Real> > > QuantLib::ProxyGreekEngine::diffWeights_ [private]
Definition at line 63 of file proxygreekengine.hpp.
Referenced by multiplePathValues().
std::vector<MarketModelDiscounter> QuantLib::ProxyGreekEngine::discounters_ [private]
Definition at line 78 of file proxygreekengine.hpp.
Referenced by ProxyGreekEngine(), and singleEvolverValues().
std::vector<Size> QuantLib::ProxyGreekEngine::endIndexOfConstraint_ [private]
Definition at line 65 of file proxygreekengine.hpp.
Referenced by singleEvolverValues().
Real QuantLib::ProxyGreekEngine::initialNumeraireValue_ [private]
Definition at line 68 of file proxygreekengine.hpp.
Referenced by singleEvolverValues().
std::vector<Size> QuantLib::ProxyGreekEngine::numberCashFlowsThisStep_ [private]
Definition at line 75 of file proxygreekengine.hpp.
Referenced by singleEvolverValues().
Size QuantLib::ProxyGreekEngine::numberProducts_ [private]
Definition at line 69 of file proxygreekengine.hpp.
Referenced by ProxyGreekEngine(), and singleEvolverValues().
std::vector<Real> QuantLib::ProxyGreekEngine::numerairesHeld_ [private]
Definition at line 74 of file proxygreekengine.hpp.
Referenced by singleEvolverValues().
boost::shared_ptr<MarketModelEvolver> QuantLib::ProxyGreekEngine::originalEvolver_ [private]
Definition at line 60 of file proxygreekengine.hpp.
Referenced by singlePathValues().
Clone<MarketModelMultiProduct> QuantLib::ProxyGreekEngine::product_ [private]
Definition at line 66 of file proxygreekengine.hpp.
Referenced by multiplePathValues(), ProxyGreekEngine(), and singleEvolverValues().
std::vector<Size> QuantLib::ProxyGreekEngine::startIndexOfConstraint_ [private]
Definition at line 64 of file proxygreekengine.hpp.
Referenced by singleEvolverValues().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/proxygreekengine.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/proxygreekengine.cpp