QuantLib: QuantLib::DiscountingSwapEngine Class Reference
QuantLib::DiscountingSwapEngine Class Reference
#include <discountingswapengine.hpp>
Public Member Functions
DiscountingSwapEngine (const Handle< YieldTermStructure > &discountCurve=Handle< YieldTermStructure >(), boost::optional< bool > includeSettlementDateFlows=boost::none, Date settlementDate=Date(), Date npvDate=Date())
void calculate () const
Handle< YieldTermStructure > discountCurve () const
Private Attributes
Handle< YieldTermStructure > discountCurve_
boost::optional< bool > includeSettlementDateFlows_
Date settlementDate_
Date npvDate_
Detailed Description
Definition at line 34 of file discountingswapengine.hpp.
Constructor & Destructor Documentation
QuantLib::DiscountingSwapEngine::DiscountingSwapEngine (const Handle< YieldTermStructure > & discountCurve = Handle<YieldTermStructure>(), boost::optional< bool > includeSettlementDateFlows = boost::none, Date settlementDate = Date(), Date npvDate = Date())
Definition at line 27 of file discountingswapengine.cpp.
References discountCurve_, and QuantLib::Observer::registerWith().
    : discountCurve_(discountCurve),
      includeSettlementDateFlows_(includeSettlementDateFlows),
      settlementDate_(settlementDate), npvDate_(npvDate) {
        registerWith(discountCurve_);
    }
Member Function Documentation
void QuantLib::DiscountingSwapEngine::calculate () const [virtual]
Implements QuantLib::PricingEngine.
Definition at line 38 of file discountingswapengine.cpp.
References QuantLib::GenericEngine< Swap::arguments, Swap::results >::arguments_, discountCurve_, QuantLib::Handle< T >::empty(), QuantLib::Swap::results::endDiscounts, QuantLib::Instrument::results::errorEstimate, QuantLib::Settings::includeReferenceDateEvents(), includeSettlementDateFlows_, QuantLib::Singleton< Settings >::instance(), QuantLib::Swap::results::legBPS, QuantLib::Swap::results::legNPV, QuantLib::Swap::arguments::legs, QuantLib::CashFlows::maturityDate(), QuantLib::CashFlows::npvbps(), npvDate_, QuantLib::Swap::results::npvDateDiscount, QuantLib::io::ordinal(), QuantLib::Swap::arguments::payer, QL_FAIL, QL_REQUIRE, QuantLib::GenericEngine< Swap::arguments, Swap::results >::results_, settlementDate_, anonymous_namespace{marketmodel.cpp}::startDate, QuantLib::Swap::results::startDiscounts, QuantLib::Instrument::results::valuationDate, and QuantLib::Instrument::results::value.
{
        QL_REQUIRE(!discountCurve_.empty(),
                   "discounting term structure handle is empty");
        results_.value = 0.0;
        results_.errorEstimate = Null<Real>();
        Date refDate = discountCurve_->referenceDate();
        Date settlementDate = settlementDate_;
        if (settlementDate_==Date()) {
            settlementDate = refDate;
        } else {
            QL_REQUIRE(settlementDate>=refDate,
                       "settlement date (" << settlementDate << ") before "
                       "discount curve reference date (" << refDate << ")");
        }
        results_.valuationDate = npvDate_;
        if (npvDate_==Date()) {
            results_.valuationDate = refDate;
        } else {
            QL_REQUIRE(npvDate_>=refDate,
                       "npv date (" << npvDate_  << ") before "
                       "discount curve reference date (" << refDate << ")");
        }
        results_.npvDateDiscount = discountCurve_->discount(results_.valuationDate);
        Size n = arguments_.legs.size();
        results_.legNPV.resize(n);
        results_.legBPS.resize(n);
        results_.startDiscounts.resize(n);
        results_.endDiscounts.resize(n);
        bool includeRefDateFlows =
            includeSettlementDateFlows_ ?
            *includeSettlementDateFlows_ :
            Settings::instance().includeReferenceDateEvents();
        for (Size i=0; i<n; ++i) {
            try {
                const YieldTermStructure& discount_ref = **discountCurve_;
                CashFlows::npvbps(arguments_.legs[i],
                                  discount_ref,
                                  includeRefDateFlows,
                                  settlementDate,
                                  results_.valuationDate,
                                  results_.legNPV[i],
                                  results_.legBPS[i]);
                results_.legNPV[i] *= arguments_.payer[i];
                results_.legBPS[i] *= arguments_.payer[i];
                Date d1 = CashFlows::startDate(arguments_.legs[i]);
                if (d1>=refDate)
                   results_.startDiscounts[i] = discountCurve_->discount(d1);
                else
                   results_.startDiscounts[i] = Null<DiscountFactor>();
                Date d2 = CashFlows::maturityDate(arguments_.legs[i]);
                if (d2>=refDate)
                   results_.endDiscounts[i] = discountCurve_->discount(d2);
                else
                   results_.endDiscounts[i] = Null<DiscountFactor>();
            } catch (std::exception &e) {
                QL_FAIL(io::ordinal(i+1) << " leg: " << e.what());
            }
            results_.value += results_.legNPV[i];
        }
    }
Handle<YieldTermStructure> QuantLib::DiscountingSwapEngine::discountCurve () const [inline]
Definition at line 43 of file discountingswapengine.hpp.
References discountCurve_.
{
            return discountCurve_;
        }
Member Data Documentation
Handle<YieldTermStructure> QuantLib::DiscountingSwapEngine::discountCurve_ [private]
Definition at line 47 of file discountingswapengine.hpp.
Referenced by calculate(), discountCurve(), and DiscountingSwapEngine().
boost::optional<bool> QuantLib::DiscountingSwapEngine::includeSettlementDateFlows_ [private]
Definition at line 48 of file discountingswapengine.hpp.
Referenced by calculate().
Date QuantLib::DiscountingSwapEngine::npvDate_ [private]
Definition at line 49 of file discountingswapengine.hpp.
Referenced by calculate().
Date QuantLib::DiscountingSwapEngine::settlementDate_ [private]
Definition at line 49 of file discountingswapengine.hpp.
Referenced by calculate().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/swap/discountingswapengine.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/swap/discountingswapengine.cpp