QuantLib: QuantLib::SampledCurve Class Reference
QuantLib::SampledCurve Class Reference
This class contains a sampled curve.
#include <sampledcurve.hpp>
Public Member Functions
SampledCurve (Size gridSize=0)
SampledCurve (const Array &grid)
SampledCurve & operator= (const SampledCurve &)
inspectors
const Array & grid () const
Array & grid ()
const Array & values () const
Array & values ()
Real gridValue (Size i) const
Real & gridValue (Size i)
Real value (Size i) const
Real & value (Size i)
Size size () const
bool empty () const
modifiers
void setGrid (const Array &)
void setValues (const Array &)
template<class F >
void sample (const F &f)
calculations
Real valueAtCenter () const
Real firstDerivativeAtCenter () const
Real secondDerivativeAtCenter () const
utilities
void swap (SampledCurve &)
void setLogGrid (Real min, Real max)
void regridLogGrid (Real min, Real max)
void shiftGrid (Real s)
void scaleGrid (Real s)
void regrid (const Array &new_grid)
template<class T >
void regrid (const Array &new_grid, T func)
template<class T >
const SampledCurve & transform (T x)
template<class T >
const SampledCurve & transformGrid (T x)
Private Attributes
Array grid_
Array values_
Detailed Description
This class contains a sampled curve.
Initially the class will contain one indexed curve
Definition at line 35 of file sampledcurve.hpp.
Constructor & Destructor Documentation
QuantLib::SampledCurve::SampledCurve (Size gridSize = 0) [inline]
Definition at line 155 of file sampledcurve.hpp.
    : grid_(gridSize), values_(gridSize) {}
QuantLib::SampledCurve::SampledCurve (const Array & grid) [inline]
Definition at line 158 of file sampledcurve.hpp.
        : grid_(grid), values_(grid.size()) {}
Member Function Documentation
bool QuantLib::SampledCurve::empty () const [inline]
Definition at line 203 of file sampledcurve.hpp.
References QuantLib::Array::empty(), and grid_.
Referenced by EuropeanOptionTest::testPriceCurve(), and valueAtCenter().
{
        return grid_.empty();
    }
Real QuantLib::SampledCurve::firstDerivativeAtCenter () const
Todo:
replace or complement with a more general function firstDerivativeAt(spot)
Definition at line 33 of file sampledcurve.cpp.
References grid_, QL_REQUIRE, size(), and values_.
{
        QL_REQUIRE(size()>=3,
                   "the size of the curve must be at least 3");
        Size jmid = size()/2;
        if (size() % 2 == 1) {
            return (values_[jmid+1]-values_[jmid-1])/
                (grid_[jmid+1]-grid_[jmid-1]);
        } else {
            return (values_[jmid]-values_[jmid-1])/
                (grid_[jmid]-grid_[jmid-1]);
        }
    }
const Array & QuantLib::SampledCurve::grid () const [inline]
Definition at line 171 of file sampledcurve.hpp.
References grid_.
Referenced by QuantLib::FDVanillaEngine::grid(), QuantLib::FDVanillaEngine::initializeOperator(), QuantLib::operator<<(), and regrid().
{
        return grid_;
    }
Array & QuantLib::SampledCurve::grid () [inline]
Definition at line 167 of file sampledcurve.hpp.
References grid_.
{
        return grid_;
    }
Real QuantLib::SampledCurve::gridValue (Size i) const [inline]
Definition at line 183 of file sampledcurve.hpp.
References grid_.
Referenced by SampledCurveTest::testConstruction(), and EuropeanOptionTest::testPriceCurve().
{
        return grid_[i];
    }
Real & QuantLib::SampledCurve::gridValue (Size i) [inline]
Definition at line 187 of file sampledcurve.hpp.
References grid_.
{
        return grid_[i];
    }
SampledCurve & QuantLib::SampledCurve::operator= (const SampledCurve & from) [inline]
Definition at line 161 of file sampledcurve.hpp.
References swap().
{
        SampledCurve temp(from);
        swap(temp);
        return *this;
    }
void QuantLib::SampledCurve::regrid (const Array & new_grid)
Definition at line 67 of file sampledcurve.cpp.
References QuantLib::Array::begin(), QuantLib::Array::end(), grid(), grid_, QuantLib::CubicInterpolation::SecondDerivative, QuantLib::Array::size(), QuantLib::CubicInterpolation::Spline, QuantLib::Array::swap(), QuantLib::Interpolation::update(), and values_.
Referenced by regridLogGrid(), and SampledCurveTest::testConstruction().
{
        CubicInterpolation priceSpline(grid_.begin(), grid_.end(),
                                       values_.begin(),
                                       CubicInterpolation::Spline, false,
                                       CubicInterpolation::SecondDerivative, 0.0,
                                       CubicInterpolation::SecondDerivative, 0.0);
        priceSpline.update();
        Array newValues(new_grid.size());
        Array::iterator val;
        Array::const_iterator grid;
        for (val = newValues.begin(), grid = new_grid.begin() ;
             grid != new_grid.end();
             val++, grid++) {
            *val = priceSpline(*grid, true);
        }
        values_.swap(newValues);
        grid_ = new_grid;
    }
template<class T > void QuantLib::SampledCurve::regrid (const Array & new_grid, T func) [inline]
Definition at line 103 of file sampledcurve.hpp.
References QuantLib::Array::begin(), QuantLib::Array::end(), grid_, QuantLib::CubicInterpolation::SecondDerivative, QuantLib::Array::size(), QuantLib::CubicInterpolation::Spline, QuantLib::Array::swap(), transform(), and values_.
{
            Array transformed_grid(grid_.size());
            std::transform(grid_.begin(), grid_.end(),
                           transformed_grid.begin(), func);
            CubicInterpolation priceSpline(transformed_grid.begin(),
                                           transformed_grid.end(),
                                           values_.begin(),
                                           CubicInterpolation::Spline, false,
                                           CubicInterpolation::SecondDerivative, 0.0,
                                           CubicInterpolation::SecondDerivative, 0.0);
            priceSpline.update();
            Array newValues = new_grid;
            std::transform(newValues.begin(), newValues.end(),
                           newValues.begin(), func);
            for (Array::iterator j = newValues.begin();
                 j != newValues.end(); j++) {
                *j = priceSpline(*j, true);
            }
            values_.swap(newValues);
            grid_ = new_grid;
        }
void QuantLib::SampledCurve::regridLogGrid (Real min, Real max) [inline]
Definition at line 90 of file sampledcurve.hpp.
References QuantLib::BoundedLogGrid(), regrid(), and size().
{
            regrid(BoundedLogGrid(min, max, size()-1),
                   std::ptr_fun<Real,Real>(std::log));
        }
template<class F > void QuantLib::SampledCurve::sample (const F & f) [inline]
Definition at line 60 of file sampledcurve.hpp.
References QuantLib::Array::begin(), QuantLib::Array::end(), anonymous_namespace{interpolations.cpp}::f(), grid_, and values_.
Referenced by QuantLib::FDVanillaEngine::initializeInitialCondition(), and SampledCurveTest::testConstruction().
{
            Array::iterator i, j;
            for(i=grid_.begin(), j = values_.begin();
                i != grid_.end(); i++, j++)
                *j = f(*i);
        }
void QuantLib::SampledCurve::scaleGrid (Real s) [inline]
Definition at line 97 of file sampledcurve.hpp.
References grid_.
{
            grid_ *= s;
        }
Real QuantLib::SampledCurve::secondDerivativeAtCenter () const
Todo:
replace or complement with a more general function secondDerivativeAt(spot)
Definition at line 46 of file sampledcurve.cpp.
References grid_, QL_REQUIRE, size(), and values_.
{
        QL_REQUIRE(size()>=4,
                   "the size of the curve must be at least 4");
        Size jmid = size()/2;
        if (size() % 2 == 1) {
            Real deltaPlus = (values_[jmid+1]-values_[jmid])/
                (grid_[jmid+1]-grid_[jmid]);
            Real deltaMinus = (values_[jmid]-values_[jmid-1])/
                (grid_[jmid]-grid_[jmid-1]);
            Real dS = (grid_[jmid+1]-grid_[jmid-1])/2.0;
            return (deltaPlus-deltaMinus)/dS;
        } else {
            Real deltaPlus = (values_[jmid+1]-values_[jmid-1])/
                (grid_[jmid+1]-grid_[jmid-1]);
            Real deltaMinus = (values_[jmid]-values_[jmid-2])/
                (grid_[jmid]-grid_[jmid-2]);
            return (deltaPlus-deltaMinus)/
                (grid_[jmid]-grid_[jmid-1]);
        }
    }
void QuantLib::SampledCurve::setGrid (const Array & g) [inline]
Definition at line 207 of file sampledcurve.hpp.
References grid_.
Referenced by setLogGrid().
{
        grid_ = g;
    }
void QuantLib::SampledCurve::setLogGrid (Real min, Real max) [inline]
Definition at line 87 of file sampledcurve.hpp.
References QuantLib::BoundedLogGrid(), setGrid(), and size().
Referenced by QuantLib::FDVanillaEngine::initializeInitialCondition().
{
            setGrid(BoundedLogGrid(min, max, size()-1));
        }
void QuantLib::SampledCurve::setValues (const Array & g) [inline]
Definition at line 211 of file sampledcurve.hpp.
References values_.
{
        values_ = g;
    }
void QuantLib::SampledCurve::shiftGrid (Real s) [inline]
Definition at line 94 of file sampledcurve.hpp.
References grid_.
Referenced by SampledCurveTest::testConstruction().
{
            grid_ += s;
        }
Size QuantLib::SampledCurve::size () const [inline]
Definition at line 199 of file sampledcurve.hpp.
References grid_, and QuantLib::Array::size().
Referenced by QuantLib::FDBermudanEngine< Scheme >::executeIntermediateStep(), firstDerivativeAtCenter(), QuantLib::FDVanillaEngine::initializeBoundaryConditions(), regridLogGrid(), secondDerivativeAtCenter(), QuantLib::FDVanillaEngine::setGridLimits(), setLogGrid(), SampledCurveTest::testConstruction(), EuropeanOptionTest::testPriceCurve(), and valueAtCenter().
{
        return grid_.size();
    }
void QuantLib::SampledCurve::swap (SampledCurve & from) [inline]
Definition at line 215 of file sampledcurve.hpp.
References grid_, QuantLib::Array::swap(), and values_.
Referenced by operator=(), and QuantLib::swap().
{
        using std::swap;
        grid_.swap(from.grid_);
        values_.swap(from.values_);
    }
template<class T > const SampledCurve& QuantLib::SampledCurve::transform (T x) [inline]
Definition at line 129 of file sampledcurve.hpp.
References QuantLib::Array::begin(), QuantLib::Array::end(), and values_.
Referenced by regrid(), and transformGrid().
{
            std::transform(values_.begin(), values_.end(),
                           values_.begin(), x);
            return *this;
        }
template<class T > const SampledCurve& QuantLib::SampledCurve::transformGrid (T x) [inline]
Definition at line 136 of file sampledcurve.hpp.
References QuantLib::Array::begin(), QuantLib::Array::end(), grid_, and transform().
{
            std::transform(grid_.begin(), grid_.end(),
                           grid_.begin(), x);
            return *this;
        }
Real QuantLib::SampledCurve::value (Size i) const [inline]
Definition at line 191 of file sampledcurve.hpp.
References values_.
Referenced by QuantLib::FDBermudanEngine< Scheme >::executeIntermediateStep(), QuantLib::FDVanillaEngine::initializeBoundaryConditions(), SampledCurveTest::testConstruction(), and EuropeanOptionTest::testPriceCurve().
{
        return values_[i];
    }
Real & QuantLib::SampledCurve::value (Size i) [inline]
Definition at line 195 of file sampledcurve.hpp.
References values_.
{
        return values_[i];
    }
Real QuantLib::SampledCurve::valueAtCenter () const
Todo:
replace or complement with a more general function valueAt(spot)
Definition at line 24 of file sampledcurve.cpp.
References empty(), QL_REQUIRE, size(), and values_.
{
        QL_REQUIRE(!empty(), "empty sampled curve");
        Size jmid = size()/2;
        if (size() % 2 == 1)
            return values_[jmid];
        else
            return (values_[jmid]+values_[jmid-1])/2.0;
    }
const Array & QuantLib::SampledCurve::values () const [inline]
Definition at line 175 of file sampledcurve.hpp.
References values_.
Referenced by QuantLib::operator<<(), and SampledCurveTest::testConstruction().
{
        return values_;
    }
Array & QuantLib::SampledCurve::values () [inline]
Definition at line 179 of file sampledcurve.hpp.
References values_.
{
        return values_;
    }
Member Data Documentation
Array QuantLib::SampledCurve::grid_ [private]
Definition at line 143 of file sampledcurve.hpp.
Referenced by empty(), firstDerivativeAtCenter(), grid(), gridValue(), regrid(), sample(), scaleGrid(), secondDerivativeAtCenter(), setGrid(), shiftGrid(), size(), swap(), and transformGrid().
Array QuantLib::SampledCurve::values_ [private]
Definition at line 144 of file sampledcurve.hpp.
Referenced by firstDerivativeAtCenter(), regrid(), sample(), secondDerivativeAtCenter(), setValues(), swap(), transform(), value(), valueAtCenter(), and values().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/sampledcurve.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/math/sampledcurve.cpp