QuantLib: QuantLib::MultiProductPathwiseWrapper Class Reference
QuantLib::MultiProductPathwiseWrapper Class Reference
#include <multisteppathwisewrapper.hpp>
Public Member Functions
MultiProductPathwiseWrapper (const MarketModelPathwiseMultiProduct &innerProduct_)
std::vector< Time > possibleCashFlowTimes () const
Size numberOfProducts () const
Size maxNumberOfCashFlowsPerProductPerStep () const
void reset ()
during simulation put product at start of path
bool nextTimeStep (const CurveState &currentState, std::vector< Size > &numberCashFlowsThisStep, std::vector< std::vector< CashFlow > > &cashFlowsGenerated)
return value indicates whether path is finished, TRUE means done
std::auto_ptr
< MarketModelMultiProduct > clone () const
returns a newly-allocated copy of itself
std::vector< Size > suggestedNumeraires () const
const EvolutionDescription & evolution () const
Private Attributes
Clone
< MarketModelPathwiseMultiProduct > innerProduct_
std::vector< std::vector
< MarketModelPathwiseMultiProduct::CashFlow > > cashFlowsGenerated_
Size numberOfProducts_
Detailed Description
MultiStepPathwiseWrapper Pathwise products do everything that ordinary products do and more. This lets you treat a pathwise product as an ordinary product. So you only have to write the product once.
Tested in MarketModels::testInverseFloater()
Definition at line 39 of file multisteppathwisewrapper.hpp.
Constructor & Destructor Documentation
QuantLib::MultiProductPathwiseWrapper::MultiProductPathwiseWrapper (const MarketModelPathwiseMultiProduct & innerProduct_)
Definition at line 27 of file multisteppathwisewrapper.cpp.
References cashFlowsGenerated_, QuantLib::MarketModelPathwiseMultiProduct::evolution(), and QuantLib::EvolutionDescription::numberOfRates().
Referenced by clone().
        :  innerProduct_(innerProduct), cashFlowsGenerated_ (innerProduct.numberOfProducts(), std::vector<MarketModelPathwiseMultiProduct::CashFlow>(innerProduct.maxNumberOfCashFlowsPerProductPerStep())),
        numberOfProducts_(innerProduct.numberOfProducts())
    {
        for (Size i=0; i < cashFlowsGenerated_.size(); ++i)
            for (Size j=0; j < cashFlowsGenerated_[i].size(); ++j)
                    cashFlowsGenerated_[i][j].amount.resize(1+innerProduct.evolution().numberOfRates());
    }
Member Function Documentation
std::auto_ptr< MarketModelMultiProduct > QuantLib::MultiProductPathwiseWrapper::clone () const [virtual]
returns a newly-allocated copy of itself
Implements QuantLib::MarketModelMultiProduct.
Definition at line 87 of file multisteppathwisewrapper.cpp.
References MultiProductPathwiseWrapper().
        {
                return   std::auto_ptr<MarketModelMultiProduct>(new MultiProductPathwiseWrapper(*this));
        }
const EvolutionDescription & QuantLib::MultiProductPathwiseWrapper::evolution () const [virtual]
Implements QuantLib::MarketModelMultiProduct.
Definition at line 82 of file multisteppathwisewrapper.cpp.
References QuantLib::MarketModelPathwiseMultiProduct::evolution(), and innerProduct_.
        {
            return innerProduct_->evolution();
        }
Size QuantLib::MultiProductPathwiseWrapper::maxNumberOfCashFlowsPerProductPerStep () const [virtual]
Implements QuantLib::MarketModelMultiProduct.
Definition at line 48 of file multisteppathwisewrapper.cpp.
References innerProduct_, and QuantLib::MarketModelPathwiseMultiProduct::maxNumberOfCashFlowsPerProductPerStep().
        {
               return innerProduct_->maxNumberOfCashFlowsPerProductPerStep();
        }
bool QuantLib::MultiProductPathwiseWrapper::nextTimeStep (const CurveState & currentState, std::vector< Size > & numberCashFlowsThisStep, std::vector< std::vector< CashFlow > > & cashFlowsGenerated) [virtual]
return value indicates whether path is finished, TRUE means done
Implements QuantLib::MarketModelMultiProduct.
Definition at line 58 of file multisteppathwisewrapper.cpp.
References cashFlowsGenerated_, innerProduct_, QuantLib::MarketModelPathwiseMultiProduct::nextTimeStep(), and numberOfProducts_.
        {
            bool done = innerProduct_->nextTimeStep(currentState, numberCashFlowsThisStep,cashFlowsGenerated_);
            // tranform the data
            for (Size i=0; i < numberOfProducts_; ++i)
                for (Size j=0; j< numberCashFlowsThisStep[i]; ++j)
                {
                    cashFlowsGenerated[i][j].timeIndex =cashFlowsGenerated_[i][j].timeIndex;
                    cashFlowsGenerated[i][j].amount =cashFlowsGenerated_[i][j].amount[0];
                }
            return done;
        }
Size QuantLib::MultiProductPathwiseWrapper::numberOfProducts () const [virtual]
Implements QuantLib::MarketModelMultiProduct.
Definition at line 43 of file multisteppathwisewrapper.cpp.
References innerProduct_, and QuantLib::MarketModelPathwiseMultiProduct::numberOfProducts().
        {
            return innerProduct_->numberOfProducts();
        }
std::vector< Time > QuantLib::MultiProductPathwiseWrapper::possibleCashFlowTimes () const [virtual]
Implements QuantLib::MarketModelMultiProduct.
Definition at line 38 of file multisteppathwisewrapper.cpp.
References innerProduct_, and QuantLib::MarketModelPathwiseMultiProduct::possibleCashFlowTimes().
        {
            return innerProduct_->possibleCashFlowTimes();
        }
void QuantLib::MultiProductPathwiseWrapper::reset () [virtual]
during simulation put product at start of path
Implements QuantLib::MarketModelMultiProduct.
Definition at line 53 of file multisteppathwisewrapper.cpp.
References innerProduct_, and QuantLib::MarketModelPathwiseMultiProduct::reset().
        {
            innerProduct_->reset();
        }
std::vector< Size > QuantLib::MultiProductPathwiseWrapper::suggestedNumeraires () const [virtual]
Implements QuantLib::MarketModelMultiProduct.
Definition at line 77 of file multisteppathwisewrapper.cpp.
References innerProduct_, and QuantLib::MarketModelPathwiseMultiProduct::suggestedNumeraires().
        {
            return innerProduct_->suggestedNumeraires();
        }
Member Data Documentation
std::vector<std::vector<MarketModelPathwiseMultiProduct::CashFlow> > QuantLib::MultiProductPathwiseWrapper::cashFlowsGenerated_ [private]
Definition at line 57 of file multisteppathwisewrapper.hpp.
Referenced by MultiProductPathwiseWrapper(), and nextTimeStep().
Clone<MarketModelPathwiseMultiProduct> QuantLib::MultiProductPathwiseWrapper::innerProduct_ [private]
Definition at line 56 of file multisteppathwisewrapper.hpp.
Referenced by evolution(), maxNumberOfCashFlowsPerProductPerStep(), nextTimeStep(), numberOfProducts(), possibleCashFlowTimes(), reset(), and suggestedNumeraires().
Size QuantLib::MultiProductPathwiseWrapper::numberOfProducts_ [private]
Definition at line 58 of file multisteppathwisewrapper.hpp.
Referenced by nextTimeStep().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/products/multistep/multisteppathwisewrapper.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/products/multistep/multisteppathwisewrapper.cpp