QuantLib: QuantLib::DefaultProbKey Class Reference
QuantLib::DefaultProbKey Class Reference
#include <defaultprobabilitykey.hpp>
Public Member Functions
DefaultProbKey ()
DefaultProbKey (const std::vector< boost::shared_ptr< DefaultType > > &eventTypes, const Currency cur, Seniority sen)
const Currency & currency () const
Seniority seniority () const
const std::vector
< boost::shared_ptr
< DefaultType > > & eventTypes () const
Size size () const
Protected Attributes
std::vector< boost::shared_ptr
< DefaultType > > eventTypes_
aggregation of event types for which the contract is sensitive.
Currency obligationCurrency_
Currency of the bond and protection leg payment.
Seniority seniority_
Reference bonds seniority.
Detailed Description
Used to index market implied credit curve probabilities. It is a proxy to the defaultable bond or class of bonds which determines the credit contract conditions. It aggregates the atomic default types in a group defining the contract conditions and which serves to index the probability curves calibrated to the market.
Definition at line 41 of file defaultprobabilitykey.hpp.
Constructor & Destructor Documentation
QuantLib::DefaultProbKey::DefaultProbKey ()
Definition at line 52 of file defaultprobabilitykey.cpp.
        : eventTypes_(),
          obligationCurrency_(Currency()),
          seniority_(NoSeniority) {}
QuantLib::DefaultProbKey::DefaultProbKey (const std::vector< boost::shared_ptr< DefaultType > > & eventTypes, const Currency cur, Seniority sen)
Definition at line 57 of file defaultprobabilitykey.cpp.
References eventTypes_, and QL_REQUIRE.
        : eventTypes_(eventTypes),
          obligationCurrency_(cur),
          seniority_(sen) {
        std::set<AtomicDefault::Type> buffer;
        Size numEvents = eventTypes_.size();
        for(Size i=0; i< numEvents; i++)
            buffer.insert(eventTypes_[i]->defaultType());
        QL_REQUIRE(buffer.size() == numEvents,
            "Duplicated event type in contract definition");
    }
Member Function Documentation
const Currency& QuantLib::DefaultProbKey::currency () const [inline]
Definition at line 57 of file defaultprobabilitykey.hpp.
References obligationCurrency_.
Referenced by QuantLib::DefaultEvent::matchesDefaultKey(), and QuantLib::operator==().
{return obligationCurrency_;}
const std::vector<boost::shared_ptr<DefaultType> >& QuantLib::DefaultProbKey::eventTypes () const [inline]
Definition at line 60 of file defaultprobabilitykey.hpp.
References eventTypes_.
Referenced by QuantLib::DefaultEvent::matchesDefaultKey(), and QuantLib::operator==().
{
                return eventTypes_;
        }
Seniority QuantLib::DefaultProbKey::seniority () const [inline]
Definition at line 58 of file defaultprobabilitykey.hpp.
References seniority_.
Referenced by QuantLib::DefaultEvent::matchesDefaultKey(), and QuantLib::operator==().
{return seniority_;}
Size QuantLib::DefaultProbKey::size () const [inline]
Definition at line 63 of file defaultprobabilitykey.hpp.
References eventTypes_.
Referenced by QuantLib::DefaultEvent::matchesDefaultKey().
{return eventTypes_.size();}
Member Data Documentation
std::vector<boost::shared_ptr<DefaultType> > QuantLib::DefaultProbKey::eventTypes_ [protected]
aggregation of event types for which the contract is sensitive.
Definition at line 44 of file defaultprobabilitykey.hpp.
Referenced by DefaultProbKey(), eventTypes(), QuantLib::NorthAmericaCorpDefaultKey::NorthAmericaCorpDefaultKey(), and size().
Currency QuantLib::DefaultProbKey::obligationCurrency_ [protected]
Currency of the bond and protection leg payment.
Definition at line 46 of file defaultprobabilitykey.hpp.
Referenced by currency().
Seniority QuantLib::DefaultProbKey::seniority_ [protected]
Reference bonds seniority.
Definition at line 48 of file defaultprobabilitykey.hpp.
Referenced by seniority().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/defaultprobabilitykey.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/defaultprobabilitykey.cpp