QuantLib: QuantLib::UnitOfMeasure Class Reference
QuantLib::UnitOfMeasure Class Reference
Unit of measure specification
#include <unitofmeasure.hpp>
Classes
struct Data
Public Types
enum Type { Mass, Volume, Energy, Quantity }
Public Member Functions
UnitOfMeasure ()
default constructor
UnitOfMeasure (const std::string &name, const std::string &code, Type unitType)
Inspectors
const std::string & name () const
name, e.g, "Barrels"
const std::string & code () const
code, e.g, "BBL", "MT"
Type unitType () const
unit type (mass, volume...)
Other information
bool empty () const
is this a usable instance?
const Rounding & rounding () const
const UnitOfMeasure & triangulationUnitOfMeasure () const
unit used for triangulation when required
Protected Attributes
boost::shared_ptr< Data > data_
Static Private Attributes
static std::map< std::string,
boost::shared_ptr
< UnitOfMeasure::Data > > unitsOfMeasure_
Related Functions
(Note that these are not member functions.)
bool operator== (const UnitOfMeasure &, const UnitOfMeasure &)
bool operator!= (const UnitOfMeasure &, const UnitOfMeasure &)
std::ostream & operator<< (std::ostream &, const UnitOfMeasure &)
Detailed Description
Unit of measure specification
Definition at line 37 of file unitofmeasure.hpp.
Member Enumeration Documentation
enum QuantLib::UnitOfMeasure::Type
Enumerator:
Mass
Volume
Energy
Quantity
Definition at line 39 of file unitofmeasure.hpp.
{ Mass, Volume, Energy, Quantity };
Constructor & Destructor Documentation
QuantLib::UnitOfMeasure::UnitOfMeasure () [inline]
default constructor
Instances built via this constructor have undefined behavior. Such instances can only act as placeholders and must be reassigned to a valid currency before being used.
Definition at line 105 of file unitofmeasure.hpp.
{}
QuantLib::UnitOfMeasure::UnitOfMeasure (const std::string & name, const std::string & code, UnitOfMeasure::Type unitType)
Definition at line 35 of file unitofmeasure.cpp.
References data_, name(), and unitsOfMeasure_.
{
        std::map<std::string,
            boost::shared_ptr<UnitOfMeasure::Data> >::const_iterator i =
            unitsOfMeasure_.find(name);
        if (i != unitsOfMeasure_.end()) {
            data_ = i->second;
        } else {
            data_ = boost::shared_ptr<UnitOfMeasure::Data>(
                               new UnitOfMeasure::Data(name, code, unitType));
            unitsOfMeasure_[name] = data_;
        }
    }
Member Function Documentation
const std::string & QuantLib::UnitOfMeasure::code () const [inline]
code, e.g, "BBL", "MT"
Definition at line 111 of file unitofmeasure.hpp.
References data_.
Referenced by QuantLib::UnitOfMeasureConversion::Data::Data(), QuantLib::UnitOfMeasureConversionManager::directLookup(), QuantLib::operator<<(), QuantLib::operator==(), and QuantLib::UnitOfMeasureConversionManager::smartLookup().
{
        return data_->code;
    }
bool QuantLib::UnitOfMeasure::empty () const [inline]
is this a usable instance?
Definition at line 123 of file unitofmeasure.hpp.
References data_.
Referenced by QuantLib::UnitOfMeasureConversionManager::lookup(), and QuantLib::operator<<().
{
        return !data_;
    }
const std::string & QuantLib::UnitOfMeasure::name () const [inline]
name, e.g, "Barrels"
Definition at line 107 of file unitofmeasure.hpp.
References data_.
Referenced by UnitOfMeasure().
{
        return data_->name;
    }
const Rounding & QuantLib::UnitOfMeasure::rounding () const [inline]
Definition at line 119 of file unitofmeasure.hpp.
References data_.
Referenced by QuantLib::Quantity::rounded().
{
        return data_->rounding;
    }
const UnitOfMeasure & QuantLib::UnitOfMeasure::triangulationUnitOfMeasure () const [inline]
unit used for triangulation when required
Definition at line 128 of file unitofmeasure.hpp.
References data_.
Referenced by QuantLib::UnitOfMeasureConversionManager::lookup().
{
        return data_->triangulationUnitOfMeasure;
    }
UnitOfMeasure::Type QuantLib::UnitOfMeasure::unitType () const [inline]
unit type (mass, volume...)
Definition at line 115 of file unitofmeasure.hpp.
References data_.
{
        return data_->unitType;
    }
Friends And Related Function Documentation
bool operator!= (const UnitOfMeasure & , const UnitOfMeasure &) [related]
Definition at line 136 of file unitofmeasure.hpp.
{
        return !(c1 == c2);
    }
std::ostream & operator<< (std::ostream & , const UnitOfMeasure &) [related]
Definition at line 24 of file unitofmeasure.cpp.
{
        if (!c.empty())
            return out << c.code();
        else
            return out << "null unit of measure";
    }
bool operator== (const UnitOfMeasure & , const UnitOfMeasure &) [related]
Definition at line 132 of file unitofmeasure.hpp.
{
        return c1.code() == c2.code();
    }
Member Data Documentation
boost::shared_ptr<Data> QuantLib::UnitOfMeasure::data_ [protected]
Definition at line 69 of file unitofmeasure.hpp.
Referenced by QuantLib::BarrelUnitOfMeasure::BarrelUnitOfMeasure(), code(), empty(), QuantLib::GallonUnitOfMeasure::GallonUnitOfMeasure(), QuantLib::KilolitreUnitOfMeasure::KilolitreUnitOfMeasure(), QuantLib::LitreUnitOfMeasure::LitreUnitOfMeasure(), QuantLib::LotUnitOfMeasure::LotUnitOfMeasure(), QuantLib::MBUnitOfMeasure::MBUnitOfMeasure(), QuantLib::MTUnitOfMeasure::MTUnitOfMeasure(), name(), rounding(), QuantLib::TokyoKilolitreUnitOfMeasure::TokyoKilolitreUnitOfMeasure(), triangulationUnitOfMeasure(), UnitOfMeasure(), and unitType().
std::map< std::string, boost::shared_ptr< UnitOfMeasure::Data > > QuantLib::UnitOfMeasure::unitsOfMeasure_ [static, private]
Definition at line 73 of file unitofmeasure.hpp.
Referenced by UnitOfMeasure().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/commodities/unitofmeasure.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/commodities/unitofmeasure.cpp