QuantLib: QuantLib::EquityFXVolSurface Class Reference
QuantLib::EquityFXVolSurface Class Reference
Equity/FX volatility (smile) surface.
#include <equityfxvolsurface.hpp>
Public Member Functions
Constructors
See the TermStructure documentation for issues regarding constructors.
EquityFXVolSurface (const Calendar &cal, BusinessDayConvention bdc=Following, const DayCounter &dc=DayCounter())
EquityFXVolSurface (BusinessDayConvention bdc=Following, const DayCounter &dc=DayCounter())
default constructor
EquityFXVolSurface (const Date &referenceDate, const Calendar &cal=Calendar(), BusinessDayConvention bdc=Following, const DayCounter &dc=DayCounter())
initialize with a fixed reference date
EquityFXVolSurface (Natural settlementDays, const Calendar &, BusinessDayConvention bdc=Following, const DayCounter &dc=DayCounter())
calculate the reference date based on the global evaluation date
Black Volatility
Volatility atmForwardVol (const Date &date1, const Date &date2, bool extrapolate=false) const
forward (at-the-money) volatility
Volatility atmForwardVol (Time time1, Time time2, bool extrapolate=false) const
forward (at-the-money) volatility
Real atmForwardVariance (const Date &date1, const Date &date2, bool extrapolate=false) const
forward (at-the-money) variance
Real atmForwardVariance (Time time1, Time time2, bool extrapolate=false) const
forward (at-the-money) variance
Visitability
virtual void accept (AcyclicVisitor &)
Detailed Description
Equity/FX volatility (smile) surface.
This abstract class defines the interface of concrete Equity/FX volatility (smile) surfaces which will be derived from this one.
Volatilities are assumed to be expressed on an annual basis.
It's only in absence of smile that the concept of (at-the-money) forward volatility makes sense.
Definition at line 42 of file equityfxvolsurface.hpp.
Constructor & Destructor Documentation
QuantLib::EquityFXVolSurface::EquityFXVolSurface (const Calendar & cal, BusinessDayConvention bdc = Following, const DayCounter & dc = DayCounter())
Warning:
term structures initialized by means of this constructor must manage their own reference date by overriding the referenceDate() method.
Definition at line 25 of file equityfxvolsurface.cpp.
    : BlackVolSurface(cal, bdc, dc) {}
QuantLib::EquityFXVolSurface::EquityFXVolSurface (BusinessDayConvention bdc = Following, const DayCounter & dc = DayCounter())
default constructor
Warning:
term structures initialized by means of this constructor must manage their own reference date by overriding the referenceDate() method.
Definition at line 31 of file equityfxvolsurface.cpp.
    : BlackVolSurface(bdc, dc) {}
QuantLib::EquityFXVolSurface::EquityFXVolSurface (const Date & referenceDate, const Calendar & cal = Calendar(), BusinessDayConvention bdc = Following, const DayCounter & dc = DayCounter())
initialize with a fixed reference date
Definition at line 35 of file equityfxvolsurface.cpp.
    : BlackVolSurface(refDate, cal, bdc, dc) {}
QuantLib::EquityFXVolSurface::EquityFXVolSurface (Natural settlementDays, const Calendar & cal, BusinessDayConvention bdc = Following, const DayCounter & dc = DayCounter())
calculate the reference date based on the global evaluation date
Definition at line 41 of file equityfxvolsurface.cpp.
    : BlackVolSurface(settlDays, cal, bdc, dc) {}
Member Function Documentation
void QuantLib::EquityFXVolSurface::accept (AcyclicVisitor & v) [virtual]
Reimplemented from QuantLib::BlackVolSurface.
Definition at line 83 of file equityfxvolsurface.cpp.
References QL_FAIL, anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Visitor< T >::visit().
{
        Visitor<EquityFXVolSurface>* v1 =
            dynamic_cast<Visitor<EquityFXVolSurface>*>(&v);
        if (v1 != 0)
            v1->visit(*this);
        else
            QL_FAIL("not a EquityFXVolSurface term structure visitor");
    }
Real QuantLib::EquityFXVolSurface::atmForwardVariance (const Date & date1, const Date & date2, bool extrapolate = false) const
forward (at-the-money) variance
Definition at line 64 of file equityfxvolsurface.cpp.
References QL_REQUIRE, and QuantLib::TermStructure::timeFromReference().
Referenced by atmForwardVol().
{
        QL_REQUIRE(date1<date2, "wrong dates");
        Time t1 = timeFromReference(date1);
        Time t2 = timeFromReference(date2);
        return atmForwardVariance(t1, t2, extrapolate);
    }
Real QuantLib::EquityFXVolSurface::atmForwardVariance (Time time1, Time time2, bool extrapolate = false) const
forward (at-the-money) variance
Definition at line 73 of file equityfxvolsurface.cpp.
References QuantLib::BlackAtmVolCurve::atmVariance(), QL_ENSURE, and QL_REQUIRE.
{
        QL_REQUIRE(time1<time2, "wrong times");
        Real var1 = atmVariance(time1, extrapolate);
        Real var2 = atmVariance(time2, extrapolate);
        QL_ENSURE(var1<var2, "non-increasing variances");
        return var2-var1;
    }
Volatility QuantLib::EquityFXVolSurface::atmForwardVol (const Date & date1, const Date & date2, bool extrapolate = false) const
forward (at-the-money) volatility
Definition at line 47 of file equityfxvolsurface.cpp.
References QL_REQUIRE, and QuantLib::TermStructure::timeFromReference().
{
        QL_REQUIRE(date1<date2, "wrong dates");
        Time t1 = timeFromReference(date1);
        Time t2 = timeFromReference(date2);
        return atmForwardVol(t1, t2, extrapolate);
    }
Volatility QuantLib::EquityFXVolSurface::atmForwardVol (Time time1, Time time2, bool extrapolate = false) const
forward (at-the-money) volatility
Definition at line 56 of file equityfxvolsurface.cpp.
References atmForwardVariance(), and anonymous_namespace{quantlibbenchmark.cpp}::t.
{
        Real fwdVariance = atmForwardVariance(time1, time2, extrapolate);
        Time t = time2-time1;
        return std::sqrt(fwdVariance/t);
    }
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/volatility/equityfxvolsurface.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/volatility/equityfxvolsurface.cpp