QuantLib: QuantLib::MultiPathGenerator< GSG > Class Template Reference
QuantLib::MultiPathGenerator< GSG > Class Template Reference
Generates a multipath from a random number generator.
#include <multipathgenerator.hpp>
Public Types
typedef Sample< MultiPath > sample_type
Public Member Functions
MultiPathGenerator (const boost::shared_ptr< StochasticProcess > &, const TimeGrid &, GSG generator, bool brownianBridge=false)
const sample_type & next () const
const sample_type & antithetic () const
Private Member Functions
const sample_type & next (bool antithetic) const
Private Attributes
bool brownianBridge_
boost::shared_ptr
< StochasticProcess > process_
GSG generator_
sample_type next_
Detailed Description
template<class GSG>
class QuantLib::MultiPathGenerator< GSG >
Generates a multipath from a random number generator.
RSG is a sample generator which returns a random sequence. It must have the minimal interface:
        RSG {
            Sample<Array> next();
        };
Test:
the generated paths are checked against cached results
Definition at line 50 of file multipathgenerator.hpp.
Member Typedef Documentation
template<class GSG> typedef Sample<MultiPath> QuantLib::MultiPathGenerator< GSG >::sample_type
Definition at line 52 of file multipathgenerator.hpp.
Constructor & Destructor Documentation
template<class GSG> QuantLib::MultiPathGenerator< GSG >::MultiPathGenerator (const boost::shared_ptr< StochasticProcess > & process, const TimeGrid & times, GSG generator, bool brownianBridge = false)
Definition at line 71 of file multipathgenerator.hpp.
References QuantLib::MultiPathGenerator< GSG >::generator_, QL_REQUIRE, and QuantLib::TimeGrid::size().
    : brownianBridge_(brownianBridge), process_(process),
      generator_(generator), next_(MultiPath(process->size(), times), 1.0) {
        QL_REQUIRE(generator_.dimension() ==
                   process->factors()*(times.size()-1),
                   "dimension (" << generator_.dimension()
                   << ") is not equal to ("
                   << process->factors() << " * " << times.size()-1
                   << ") the number of factors "
                   << "times the number of time steps");
        QL_REQUIRE(times.size() > 1,
                   "no times given");
    }
Member Function Documentation
template<class GSG > const MultiPathGenerator< GSG >::sample_type & QuantLib::MultiPathGenerator< GSG >::antithetic () const [inline]
Definition at line 98 of file multipathgenerator.hpp.
Referenced by HybridHestonHullWhiteProcessTest::testCallableEquityPricing(), anonymous_namespace{pathgenerator.cpp}::testMultiple(), LiborMarketModelTest::testSwaptionPricing(), and VPPTest::testVPPPricing().
{
        return next(true);
    }
template<class GSG > const MultiPathGenerator< GSG >::sample_type & QuantLib::MultiPathGenerator< GSG >::next () const [inline]
Definition at line 92 of file multipathgenerator.hpp.
Referenced by HybridHestonHullWhiteProcessTest::testCallableEquityPricing(), SwingOptionTest::testExtOUJumpVanillaEngine(), VPPTest::testGemanRoncoroniProcess(), VPPTest::testKlugeExtOUSpreadOption(), LiborMarketModelProcessTest::testMonteCarloCapletPricing(), anonymous_namespace{pathgenerator.cpp}::testMultiple(), LiborMarketModelTest::testSwaptionPricing(), VPPTest::testVPPPricing(), and HybridHestonHullWhiteProcessTest::testZeroBondPricing().
{
        return next(false);
    }
template<class GSG > const MultiPathGenerator< GSG >::sample_type & QuantLib::MultiPathGenerator< GSG >::next (bool antithetic) const [private]
Definition at line 104 of file multipathgenerator.hpp.
References QuantLib::Array::begin(), QuantLib::anonymous_namespace{yieldtermstructure.cpp}::dt, QuantLib::TimeGrid::dt(), QuantLib::MultiPath::pathSize(), QL_FAIL, and anonymous_namespace{quantlibbenchmark.cpp}::t.
{
        if (brownianBridge_) {
            QL_FAIL("Brownian bridge not supported");
        } else {
            typedef typename GSG::sample_type sequence_type;
            const sequence_type& sequence_ =
                antithetic ? generator_.lastSequence()
                           : generator_.nextSequence();
            Size m = process_->size();
            Size n = process_->factors();
            MultiPath& path = next_.value;
            Array asset = process_->initialValues();
            for (Size j=0; j<m; j++)
                path[j].front() = asset[j];
            Array temp(n);
            next_.weight = sequence_.weight;
            const TimeGrid& timeGrid = path[0].timeGrid();
            Time t, dt;
            for (Size i = 1; i < path.pathSize(); i++) {
                Size offset = (i-1)*n;
                t = timeGrid[i-1];
                dt = timeGrid.dt(i-1);
                if (antithetic)
                    std::transform(sequence_.value.begin()+offset,
                                   sequence_.value.begin()+offset+n,
                                   temp.begin(),
                                   std::negate<Real>());
                else
                    std::copy(sequence_.value.begin()+offset,
                              sequence_.value.begin()+offset+n,
                              temp.begin());
                asset = process_->evolve(t, asset, dt, temp);
                for (Size j=0; j<m; j++)
                    path[j][i] = asset[j];
            }
            return next_;
        }
    }
Member Data Documentation
template<class GSG> bool QuantLib::MultiPathGenerator< GSG >::brownianBridge_ [private]
Definition at line 61 of file multipathgenerator.hpp.
template<class GSG> GSG QuantLib::MultiPathGenerator< GSG >::generator_ [private]
Definition at line 63 of file multipathgenerator.hpp.
Referenced by QuantLib::MultiPathGenerator< GSG >::MultiPathGenerator().
template<class GSG> sample_type QuantLib::MultiPathGenerator< GSG >::next_ [mutable, private]
Definition at line 64 of file multipathgenerator.hpp.
template<class GSG> boost::shared_ptr<StochasticProcess> QuantLib::MultiPathGenerator< GSG >::process_ [private]
Definition at line 62 of file multipathgenerator.hpp.
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/montecarlo/multipathgenerator.hpp