QuantLib: QuantLib::NeumannBC Class Reference
QuantLib::NeumannBC Class Reference
Neumann boundary condition (i.e., constant derivative)
#include <boundarycondition.hpp>
Public Member Functions
NeumannBC (Real value, Side side)
void applyBeforeApplying (TridiagonalOperator &) const
void applyAfterApplying (Array &) const
void applyBeforeSolving (TridiagonalOperator &, Array &rhs) const
void applyAfterSolving (Array &) const
void setTime (Time)
Private Attributes
Real value_
Side side_
Detailed Description
Neumann boundary condition (i.e., constant derivative)
Warning:
The value passed must not be the value of the derivative. Instead, it must be comprehensive of the grid step between the first two points--i.e., it must be the difference between f[0] and f[1].
Todo:
generalize to time-dependent conditions.
Definition at line 76 of file boundarycondition.hpp.
Constructor & Destructor Documentation
QuantLib::NeumannBC::NeumannBC (Real value, NeumannBC::Side side)
Definition at line 24 of file boundarycondition.cpp.
    : value_(value), side_(side) {}
Member Function Documentation
void QuantLib::NeumannBC::applyAfterApplying (Array &) const [virtual]
This method modifies an array \(u \) so that it satisfies the given condition.
Implements QuantLib::BoundaryCondition< TridiagonalOperator >.
Definition at line 40 of file boundarycondition.cpp.
References QuantLib::BoundaryCondition< TridiagonalOperator >::Lower, QL_FAIL, side_, QuantLib::Array::size(), QuantLib::BoundaryCondition< TridiagonalOperator >::Upper, and value_.
{
        switch (side_) {
          case Lower:
            u[0] = u[1] - value_;
            break;
          case Upper:
            u[u.size()-1] = u[u.size()-2] + value_;
            break;
          default:
            QL_FAIL("unknown side for Neumann boundary condition");
        }
    }
void QuantLib::NeumannBC::applyAfterSolving (Array &) const [virtual]
This method modifies an array \(u \) so that it satisfies the given condition.
Implements QuantLib::BoundaryCondition< TridiagonalOperator >.
Definition at line 69 of file boundarycondition.cpp.
{}
void QuantLib::NeumannBC::applyBeforeApplying (TridiagonalOperator &) const [virtual]
This method modifies an operator \(L \) before it is applied to an array \(u \) so that \(v = Lu \) will satisfy the given condition.
Implements QuantLib::BoundaryCondition< TridiagonalOperator >.
Definition at line 27 of file boundarycondition.cpp.
References QuantLib::BoundaryCondition< TridiagonalOperator >::Lower, QL_FAIL, QuantLib::TridiagonalOperator::setFirstRow(), QuantLib::TridiagonalOperator::setLastRow(), side_, and QuantLib::BoundaryCondition< TridiagonalOperator >::Upper.
{
        switch (side_) {
          case Lower:
            L.setFirstRow(-1.0,1.0);
            break;
          case Upper:
            L.setLastRow(-1.0,1.0);
            break;
          default:
            QL_FAIL("unknown side for Neumann boundary condition");
        }
    }
void QuantLib::NeumannBC::applyBeforeSolving (TridiagonalOperator & , Array & rhs) const [virtual]
This method modifies an operator \(L \) before the linear system \(Lu' = u \) is solved so that \(u' \) will satisfy the given condition.
Implements QuantLib::BoundaryCondition< TridiagonalOperator >.
Definition at line 53 of file boundarycondition.cpp.
References QuantLib::BoundaryCondition< TridiagonalOperator >::Lower, QL_FAIL, QuantLib::TridiagonalOperator::setFirstRow(), QuantLib::TridiagonalOperator::setLastRow(), side_, QuantLib::Array::size(), QuantLib::BoundaryCondition< TridiagonalOperator >::Upper, and value_.
{
        switch (side_) {
          case Lower:
            L.setFirstRow(-1.0,1.0);
            rhs[0] = value_;
            break;
          case Upper:
            L.setLastRow(-1.0,1.0);
            rhs[rhs.size()-1] = value_;
            break;
          default:
            QL_FAIL("unknown side for Neumann boundary condition");
        }
    }
void QuantLib::NeumannBC::setTime (Time t) [inline, virtual]
This method sets the current time for time-dependent boundary conditions.
Implements QuantLib::BoundaryCondition< TridiagonalOperator >.
Definition at line 84 of file boundarycondition.hpp.
{}
Member Data Documentation
Side QuantLib::NeumannBC::side_ [private]
Definition at line 87 of file boundarycondition.hpp.
Referenced by applyAfterApplying(), applyBeforeApplying(), and applyBeforeSolving().
Real QuantLib::NeumannBC::value_ [private]
Definition at line 86 of file boundarycondition.hpp.
Referenced by applyAfterApplying(), and applyBeforeSolving().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/boundarycondition.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/boundarycondition.cpp