QuantLib: QuantLib::MakeOIS Class Reference
QuantLib::MakeOIS Class Reference
helper class
#include <makeois.hpp>
Public Member Functions
MakeOIS (const Period &swapTenor, const boost::shared_ptr< OvernightIndex > &overnightIndex, Rate fixedRate=Null< Rate >(), const Period &fwdStart=0 *Days)
operator OvernightIndexedSwap () const
operator boost::shared_ptr< OvernightIndexedSwap > () const
MakeOIS & receiveFixed (bool flag=true)
MakeOIS & withType (OvernightIndexedSwap::Type type)
MakeOIS & withNominal (Real n)
MakeOIS & withSettlementDays (Natural fixingDays)
MakeOIS & withEffectiveDate (const Date &)
MakeOIS & withTerminationDate (const Date &)
MakeOIS & withPaymentFrequency (Frequency f)
MakeOIS & withRule (DateGeneration::Rule r)
MakeOIS & withEndOfMonth (bool flag=true)
MakeOIS & withFixedLegDayCount (const DayCounter &dc)
MakeOIS & withOvernightLegSpread (Spread sp)
MakeOIS & withDiscountingTermStructure (const Handle< YieldTermStructure > &discountingTermStructure)
Private Attributes
Period swapTenor_
boost::shared_ptr< OvernightIndex > overnightIndex_
Rate fixedRate_
Period forwardStart_
Natural fixingDays_
Date effectiveDate_
Date terminationDate_
Frequency paymentFrequency_
DateGeneration::Rule rule_
bool endOfMonth_
OvernightIndexedSwap::Type type_
Real nominal_
Spread overnightSpread_
DayCounter fixedDayCount_
boost::shared_ptr< PricingEngine > engine_
Detailed Description
helper class
This class provides a more comfortable way to instantiate overnight indexed swaps.
Definition at line 37 of file makeois.hpp.
Constructor & Destructor Documentation
QuantLib::MakeOIS::MakeOIS (const Period & swapTenor, const boost::shared_ptr< OvernightIndex > & overnightIndex, Rate fixedRate = Null<Rate>(), const Period & fwdStart = 0*Days)
Definition at line 27 of file makeois.cpp.
    : swapTenor_(swapTenor), overnightIndex_(overnightIndex),
      fixedRate_(fixedRate), forwardStart_(forwardStart),
      fixingDays_(2), paymentFrequency_(Annual),
      rule_(DateGeneration::Forward),
      endOfMonth_(1*Months<=swapTenor && swapTenor<=2*Years ? true : false),
      type_(OvernightIndexedSwap::Payer), nominal_(1.0),
      overnightSpread_(0.0),
      fixedDayCount_(overnightIndex->dayCounter()),
      engine_(new DiscountingSwapEngine(overnightIndex_->forwardingTermStructure())) {}
Member Function Documentation
QuantLib::MakeOIS::operator boost::shared_ptr< OvernightIndexedSwap > () const
Definition at line 46 of file makeois.cpp.
References QuantLib::Calendar::advance(), anonymous_namespace{marketmodel.cpp}::calendar, QuantLib::Days, anonymous_namespace{marketmodel.cpp}::endDate, QuantLib::Settings::evaluationDate(), QuantLib::Singleton< Settings >::instance(), QuantLib::ModifiedFollowing, QL_REQUIRE, and anonymous_namespace{marketmodel.cpp}::startDate.
{
        const Calendar& calendar = overnightIndex_->fixingCalendar();
        Date startDate;
        if (effectiveDate_ != Date())
            startDate = effectiveDate_;
        else {
            Date referenceDate = Settings::instance().evaluationDate();
            Date spotDate = calendar.advance(referenceDate,
                                             fixingDays_*Days);
            startDate = spotDate+forwardStart_;
        }
        Date endDate;
        if (terminationDate_ != Date()) {
            endDate = terminationDate_;
        } else {
            if (endOfMonth_) {
                endDate = calendar.advance(startDate, swapTenor_,
                                           ModifiedFollowing,
                                           endOfMonth_);
            } else {
                endDate = startDate+swapTenor_;
            }
        }
        Schedule schedule(startDate, endDate,
                          Period(paymentFrequency_),
                          calendar,
                          ModifiedFollowing,
                          ModifiedFollowing,
                          rule_,
                          endOfMonth_);
        Rate usedFixedRate = fixedRate_;
        if (fixedRate_ == Null<Rate>()) {
            QL_REQUIRE(!overnightIndex_->forwardingTermStructure().empty(),
                       "null term structure set to this instance of " <<
                       overnightIndex_->name());
            OvernightIndexedSwap temp(type_, nominal_,
                                      schedule,
                                      0.0, // fixed rate
                                      fixedDayCount_,
                                      overnightIndex_, overnightSpread_);
            // ATM on the forecasting curve
            bool includeSettlementDateFlows = false;
            temp.setPricingEngine(boost::shared_ptr<PricingEngine>(
                new DiscountingSwapEngine(
                                   overnightIndex_->forwardingTermStructure(),
                                   includeSettlementDateFlows)));
            usedFixedRate = temp.fairRate();
        }
        boost::shared_ptr<OvernightIndexedSwap> ois(new
            OvernightIndexedSwap(type_, nominal_,
                                 schedule,
                                 usedFixedRate, fixedDayCount_,
                                 overnightIndex_, overnightSpread_));
        ois->setPricingEngine(engine_);
        return ois;
    }
QuantLib::MakeOIS::operator OvernightIndexedSwap () const
Definition at line 41 of file makeois.cpp.
{
        boost::shared_ptr<OvernightIndexedSwap> ois = *this;
        return *ois;
    }
MakeOIS & QuantLib::MakeOIS::receiveFixed (bool flag = true)
Definition at line 109 of file makeois.cpp.
References QuantLib::OvernightIndexedSwap::Payer, QuantLib::OvernightIndexedSwap::Receiver, and type_.
{
        type_ = flag ? OvernightIndexedSwap::Receiver : OvernightIndexedSwap::Payer ;
        return *this;
    }
MakeOIS & QuantLib::MakeOIS::withDiscountingTermStructure (const Handle< YieldTermStructure > & discountingTermStructure)
Definition at line 155 of file makeois.cpp.
References engine_.
Referenced by QuantLib::DatedOISRateHelper::DatedOISRateHelper(), QuantLib::OISRateHelper::initializeDates(), and anonymous_namespace{overnightindexedswap.cpp}::CommonVars::makeSwap().
{
        engine_ = boost::shared_ptr<PricingEngine>(new
                            DiscountingSwapEngine(discountingTermStructure));
        return *this;
    }
MakeOIS & QuantLib::MakeOIS::withEffectiveDate (const Date & effectiveDate)
Definition at line 130 of file makeois.cpp.
References effectiveDate_.
Referenced by QuantLib::DatedOISRateHelper::DatedOISRateHelper(), anonymous_namespace{overnightindexedswap.cpp}::CommonVars::makeSwap(), and QuantLib::OvernightIndexedSwapIndex::underlyingSwap().
{
        effectiveDate_ = effectiveDate;
        return *this;
    }
MakeOIS & QuantLib::MakeOIS::withEndOfMonth (bool flag = true)
Definition at line 167 of file makeois.cpp.
References endOfMonth_.
{
        endOfMonth_ = flag;
        return *this;
    }
MakeOIS & QuantLib::MakeOIS::withFixedLegDayCount (const DayCounter & dc)
Definition at line 162 of file makeois.cpp.
References fixedDayCount_.
Referenced by QuantLib::OvernightIndexedSwapIndex::underlyingSwap().
{
        fixedDayCount_ = dc;
        return *this;
    }
MakeOIS & QuantLib::MakeOIS::withNominal (Real n)
Definition at line 119 of file makeois.cpp.
References nominal_.
Referenced by anonymous_namespace{overnightindexedswap.cpp}::CommonVars::makeSwap().
{
        nominal_ = n;
        return *this;
    }
MakeOIS & QuantLib::MakeOIS::withOvernightLegSpread (Spread sp)
Definition at line 172 of file makeois.cpp.
References overnightSpread_.
Referenced by anonymous_namespace{overnightindexedswap.cpp}::CommonVars::makeSwap().
{
        overnightSpread_ = sp;
        return *this;
    }
MakeOIS & QuantLib::MakeOIS::withPaymentFrequency (Frequency f)
Definition at line 141 of file makeois.cpp.
References anonymous_namespace{interpolations.cpp}::f(), QuantLib::Once, paymentFrequency_, rule_, and QuantLib::DateGeneration::Zero.
{
        paymentFrequency_ = f;
        if (paymentFrequency_==Once)
            rule_ = DateGeneration::Zero;
        return *this;
    }
MakeOIS & QuantLib::MakeOIS::withRule (DateGeneration::Rule r)
Definition at line 148 of file makeois.cpp.
References QuantLib::Once, paymentFrequency_, rule_, and QuantLib::DateGeneration::Zero.
{
        rule_ = r;
        if (r==DateGeneration::Zero)
            paymentFrequency_ = Once;
        return *this;
    }
MakeOIS & QuantLib::MakeOIS::withSettlementDays (Natural fixingDays)
Definition at line 124 of file makeois.cpp.
References effectiveDate_, and fixingDays_.
Referenced by QuantLib::OISRateHelper::initializeDates().
{
        fixingDays_ = fixingDays;
        effectiveDate_ = Date();
        return *this;
    }
MakeOIS & QuantLib::MakeOIS::withTerminationDate (const Date & terminationDate)
Definition at line 135 of file makeois.cpp.
References swapTenor_, and terminationDate_.
Referenced by QuantLib::DatedOISRateHelper::DatedOISRateHelper().
{
        terminationDate_ = terminationDate;
        swapTenor_ = Period();
        return *this;
    }
MakeOIS & QuantLib::MakeOIS::withType (OvernightIndexedSwap::Type type)
Definition at line 114 of file makeois.cpp.
References anonymous_namespace{swaption.cpp}::type, and type_.
{
        type_ = type;
        return *this;
    }
Member Data Documentation
Date QuantLib::MakeOIS::effectiveDate_ [private]
Definition at line 70 of file makeois.hpp.
Referenced by withEffectiveDate(), and withSettlementDays().
bool QuantLib::MakeOIS::endOfMonth_ [private]
Definition at line 73 of file makeois.hpp.
Referenced by withEndOfMonth().
boost::shared_ptr<PricingEngine> QuantLib::MakeOIS::engine_ [private]
Definition at line 81 of file makeois.hpp.
Referenced by withDiscountingTermStructure().
DayCounter QuantLib::MakeOIS::fixedDayCount_ [private]
Definition at line 79 of file makeois.hpp.
Referenced by withFixedLegDayCount().
Rate QuantLib::MakeOIS::fixedRate_ [private]
Definition at line 66 of file makeois.hpp.
Natural QuantLib::MakeOIS::fixingDays_ [private]
Definition at line 69 of file makeois.hpp.
Referenced by withSettlementDays().
Period QuantLib::MakeOIS::forwardStart_ [private]
Definition at line 67 of file makeois.hpp.
Real QuantLib::MakeOIS::nominal_ [private]
Definition at line 76 of file makeois.hpp.
Referenced by withNominal().
boost::shared_ptr<OvernightIndex> QuantLib::MakeOIS::overnightIndex_ [private]
Definition at line 65 of file makeois.hpp.
Spread QuantLib::MakeOIS::overnightSpread_ [private]
Definition at line 78 of file makeois.hpp.
Referenced by withOvernightLegSpread().
Frequency QuantLib::MakeOIS::paymentFrequency_ [private]
Definition at line 71 of file makeois.hpp.
Referenced by withPaymentFrequency(), and withRule().
DateGeneration::Rule QuantLib::MakeOIS::rule_ [private]
Definition at line 72 of file makeois.hpp.
Referenced by withPaymentFrequency(), and withRule().
Period QuantLib::MakeOIS::swapTenor_ [private]
Definition at line 64 of file makeois.hpp.
Referenced by withTerminationDate().
Date QuantLib::MakeOIS::terminationDate_ [private]
Definition at line 70 of file makeois.hpp.
Referenced by withTerminationDate().
OvernightIndexedSwap::Type QuantLib::MakeOIS::type_ [private]
Definition at line 75 of file makeois.hpp.
Referenced by receiveFixed(), and withType().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/makeois.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/makeois.cpp