QuantLib: QuantLib::LMMCurveState Class Reference
QuantLib::LMMCurveState Class Reference
Curve state for Libor market models
#include <lmmcurvestate.hpp>
Public Member Functions
LMMCurveState (const std::vector< Time > &rateTimes)
std::auto_ptr< CurveState > clone () const
Modifiers
void setOnForwardRates (const std::vector< Rate > &fwdRates, Size firstValidIndex=0)
void setOnDiscountRatios (const std::vector< DiscountFactor > &discRatios, Size firstValidIndex=0)
Inspectors
Real discountRatio (Size i, Size j) const
Rate forwardRate (Size i) const
Rate coterminalSwapRate (Size i) const
Rate coterminalSwapAnnuity (Size numeraire, Size i) const
Rate cmSwapRate (Size i, Size spanningForwards) const
Rate cmSwapAnnuity (Size numeraire, Size i, Size spanningForwards) const
const std::vector< Rate > & forwardRates () const
const std::vector< Rate > & coterminalSwapRates () const
const std::vector< Rate > & cmSwapRates (Size spanningForwards) const
Private Attributes
Size first_
std::vector< DiscountFactor > discRatios_
std::vector< Rate > forwardRates_
std::vector< Rate > cmSwapRates_
std::vector< Real > cmSwapAnnuities_
std::vector< Rate > cotSwapRates_
std::vector< Real > cotAnnuities_
Size firstCotAnnuityComped_
Detailed Description
Curve state for Libor market models
This class stores the state of the yield curve associated to the fixed calendar times within the simulation. This is the workhorse discounting object associated to the rate times of the simulation. It's important to pass the rates via an object like this to the product rather than directly to make it easier to switch to other engines such as a coterminal swap rate engine. Many products will not need expired rates and others will only require the first rate.
Definition at line 39 of file lmmcurvestate.hpp.
Constructor & Destructor Documentation
QuantLib::LMMCurveState::LMMCurveState (const std::vector< Time > & rateTimes) [explicit]
Definition at line 28 of file lmmcurvestate.cpp.
Referenced by clone().
    : CurveState(rateTimes),
      first_(numberOfRates_),
      discRatios_(numberOfRates_+1, 1.0),
      forwardRates_(numberOfRates_),
      cmSwapRates_(numberOfRates_),
      cmSwapAnnuities_(numberOfRates_,rateTaus_[numberOfRates_-1]),
      cotSwapRates_(numberOfRates_),
      cotAnnuities_(numberOfRates_,
      rateTaus_[numberOfRates_-1]),
      firstCotAnnuityComped_(numberOfRates_)
    {}
Member Function Documentation
std::auto_ptr<CurveState> QuantLib::LMMCurveState::clone () const [inline, virtual]
Implements QuantLib::CurveState.
Definition at line 80 of file lmmcurvestate.hpp.
References LMMCurveState().
{
            return std::auto_ptr<CurveState>(new LMMCurveState(*this));
        }
Rate QuantLib::LMMCurveState::cmSwapAnnuity (Size numeraire, Size i, Size spanningForwards) const [virtual]
Implements QuantLib::CurveState.
Definition at line 150 of file lmmcurvestate.cpp.
References cmSwapAnnuities_, cmSwapRates_, QuantLib::constantMaturityFromDiscountRatios(), discRatios_, first_, QuantLib::CurveState::numberOfRates_, QL_REQUIRE, and QuantLib::CurveState::rateTaus_.
Referenced by anonymous_namespace{marketmodel_cms.cpp}::checkCMSAndSwaptions(), and SwapForwardMappingsTest::testSwaptionImpliedVolatility().
{
        QL_REQUIRE(first_<numberOfRates_, "curve state not initialized yet");
        QL_REQUIRE(numeraire>=first_ && numeraire<=numberOfRates_,
                   "invalid numeraire");
        QL_REQUIRE(i>=first_ && i<=numberOfRates_, "invalid index");
        // consider lazy evaluation here
        constantMaturityFromDiscountRatios(spanningForwards, first_,
                                           discRatios_, rateTaus_,
                                           cmSwapRates_, cmSwapAnnuities_);
        return cmSwapAnnuities_[i]/discRatios_[numeraire];
    }
Rate QuantLib::LMMCurveState::cmSwapRate (Size i, Size spanningForwards) const [virtual]
Implements QuantLib::CurveState.
Definition at line 165 of file lmmcurvestate.cpp.
References cmSwapAnnuities_, cmSwapRates_, QuantLib::constantMaturityFromDiscountRatios(), discRatios_, first_, QuantLib::CurveState::numberOfRates_, QL_REQUIRE, and QuantLib::CurveState::rateTaus_.
Referenced by SwapForwardMappingsTest::testForwardSwapJacobians(), and SwapForwardMappingsTest::testSwaptionImpliedVolatility().
{
        QL_REQUIRE(first_<numberOfRates_, "curve state not initialized yet");
        QL_REQUIRE(i>=first_ && i<=numberOfRates_, "invalid index");
        // consider lazy evaluation here
        constantMaturityFromDiscountRatios(spanningForwards, first_,
                                           discRatios_, rateTaus_,
                                           cmSwapRates_, cmSwapAnnuities_);
        return cmSwapRates_[i];
    }
const std::vector< Rate > & QuantLib::LMMCurveState::cmSwapRates (Size spanningForwards) const [virtual]
Implements QuantLib::CurveState.
Definition at line 190 of file lmmcurvestate.cpp.
References cmSwapAnnuities_, cmSwapRates_, QuantLib::constantMaturityFromDiscountRatios(), discRatios_, first_, QuantLib::CurveState::numberOfRates_, QL_REQUIRE, and QuantLib::CurveState::rateTaus_.
Referenced by anonymous_namespace{marketmodel_cms.cpp}::setup().
{
        QL_REQUIRE(first_<numberOfRates_, "curve state not initialized yet");
        constantMaturityFromDiscountRatios(spanningForwards, first_,
                                           discRatios_, rateTaus_,
                                           cmSwapRates_, cmSwapAnnuities_);
        return cmSwapRates_;
    }
Rate QuantLib::LMMCurveState::coterminalSwapAnnuity (Size numeraire, Size i) const [virtual]
Implements QuantLib::CurveState.
Definition at line 111 of file lmmcurvestate.cpp.
References cotAnnuities_, discRatios_, first_, firstCotAnnuityComped_, QuantLib::CurveState::numberOfRates_, QL_REQUIRE, and QuantLib::CurveState::rateTaus_.
Referenced by addCoterminalSwapsAndSwaptions(), anonymous_namespace{marketmodel_smm.cpp}::checkCoterminalSwapsAndSwaptions(), coterminalSwapRate(), QuantLib::MarketModelPathwiseCoterminalSwaptionsNumericalDeflated::nextTimeStep(), SwapForwardMappingsTest::testForwardCoterminalMappings(), MarketModelTest::testPathwiseMarketVegas(), and MarketModelTest::testPeriodAdapter().
{
        QL_REQUIRE(first_<numberOfRates_, "curve state not initialized yet");
        QL_REQUIRE(numeraire>=first_ && numeraire<=numberOfRates_,
                   "invalid numeraire");
        QL_REQUIRE(i>=first_ && i<=numberOfRates_, "invalid index");
        //        coterminalFromDiscountRatios(first_,
        //                                   discRatios_, rateTaus_,
        //                                 cotSwapRates_, cotAnnuities_);
        if (firstCotAnnuityComped_ <=i)
            return  cotAnnuities_[i]/discRatios_[numeraire];
        if (firstCotAnnuityComped_ == numberOfRates_)
        {
            cotAnnuities_[numberOfRates_-1] = rateTaus_[numberOfRates_-1]*discRatios_[numberOfRates_];
            --firstCotAnnuityComped_;
        }
        for (int j= static_cast<int>(firstCotAnnuityComped_)-1; j >=static_cast<int>(i); --j)
            cotAnnuities_[j] = cotAnnuities_[j+1]+rateTaus_[j]*discRatios_[j+1];
        firstCotAnnuityComped_ = i;
        return cotAnnuities_[i]/discRatios_[numeraire];
    }
Rate QuantLib::LMMCurveState::coterminalSwapRate (Size i) const [virtual]
Implements QuantLib::CurveState.
Definition at line 138 of file lmmcurvestate.cpp.
References coterminalSwapAnnuity(), discRatios_, first_, QuantLib::CurveState::numberOfRates_, and QL_REQUIRE.
Referenced by QuantLib::MarketModelPathwiseCoterminalSwaptionsNumericalDeflated::nextTimeStep(), MarketModelTest::testPathwiseMarketVegas(), and MarketModelTest::testPeriodAdapter().
{
        QL_REQUIRE(first_<numberOfRates_, "curve state not initialized yet");
        QL_REQUIRE(i>=first_ && i<=numberOfRates_, "invalid index");
        //    coterminalFromDiscountRatios(first_,
        //                               discRatios_, rateTaus_,
        //                             cotSwapRates_, cotAnnuities_);
        //      return cotSwapRates_[i];
        Real res = (discRatios_[i]/ discRatios_[numberOfRates_] -1.0)/coterminalSwapAnnuity(numberOfRates_,i);
        return res;
    }
const std::vector< Rate > & QuantLib::LMMCurveState::coterminalSwapRates () const [virtual]
Implements QuantLib::CurveState.
Definition at line 182 of file lmmcurvestate.cpp.
References cotAnnuities_, QuantLib::coterminalFromDiscountRatios(), cotSwapRates_, discRatios_, first_, QuantLib::CurveState::numberOfRates_, QL_REQUIRE, and QuantLib::CurveState::rateTaus_.
Referenced by addCoterminalSwapsAndSwaptions(), QuantLib::FwdToCotSwapAdapter::FwdToCotSwapAdapter(), anonymous_namespace{marketmodel_smm.cpp}::setup(), anonymous_namespace{marketmodel_smmcapletcalibration.cpp}::setup(), anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::setup(), anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::setup(), SwapForwardMappingsTest::testForwardCoterminalMappings(), and MarketModelTest::testPathwiseMarketVegas().
{
        QL_REQUIRE(first_<numberOfRates_, "curve state not initialized yet");
        coterminalFromDiscountRatios(first_,
                                     discRatios_, rateTaus_,
                                     cotSwapRates_, cotAnnuities_);
        return cotSwapRates_;
    }
Real QuantLib::LMMCurveState::discountRatio (Size i, Size j) const [virtual]
Implements QuantLib::CurveState.
Definition at line 98 of file lmmcurvestate.cpp.
References discRatios_, first_, QuantLib::CurveState::numberOfRates_, and QL_REQUIRE.
Referenced by MarketModelTest::testPathwiseMarketVegas(), and MarketModelTest::testPeriodAdapter().
{
        QL_REQUIRE(first_<numberOfRates_, "curve state not initialized yet");
        QL_REQUIRE(std::min(i, j)>=first_, "invalid index");
        QL_REQUIRE(std::max(i, j)<=numberOfRates_, "invalid index");
        return discRatios_[i]/discRatios_[j];
    }
Rate QuantLib::LMMCurveState::forwardRate (Size i) const [virtual]
Implements QuantLib::CurveState.
Definition at line 105 of file lmmcurvestate.cpp.
References first_, forwardRates_, QuantLib::CurveState::numberOfRates_, and QL_REQUIRE.
Referenced by MarketModelTest::testPeriodAdapter().
{
        QL_REQUIRE(first_<numberOfRates_, "curve state not initialized yet");
        QL_REQUIRE(i>=first_ && i<=numberOfRates_, "invalid index");
        return forwardRates_[i];
    }
const std::vector< Rate > & QuantLib::LMMCurveState::forwardRates () const [virtual]
Implements QuantLib::CurveState.
Definition at line 177 of file lmmcurvestate.cpp.
References first_, forwardRates_, QuantLib::CurveState::numberOfRates_, and QL_REQUIRE.
Referenced by QuantLib::LMMNormalDriftCalculator::compute(), QuantLib::LMMDriftCalculator::compute(), QuantLib::LMMDriftCalculator::computePlain(), QuantLib::LMMNormalDriftCalculator::computePlain(), QuantLib::LMMDriftCalculator::computeReduced(), QuantLib::LMMNormalDriftCalculator::computeReduced(), QuantLib::FwdPeriodAdapter::FwdPeriodAdapter(), MarketModelTest::testPathwiseMarketVegas(), and SwapForwardMappingsTest::testSwaptionImpliedVolatility().
{
        QL_REQUIRE(first_<numberOfRates_, "curve state not initialized yet");
        return forwardRates_;
    }
void QuantLib::LMMCurveState::setOnDiscountRatios (const std::vector< DiscountFactor > & discRatios, Size firstValidIndex = 0)
Definition at line 70 of file lmmcurvestate.cpp.
References discRatios_, first_, firstCotAnnuityComped_, forwardRates_, QuantLib::CurveState::numberOfRates_, QL_REQUIRE, and QuantLib::CurveState::rateTaus_.
Referenced by QuantLib::ForwardForwardMappings::RestrictCurveState().
{
        QL_REQUIRE(discRatios.size()==numberOfRates_+1,
                   "too many discount ratios: " <<
                   numberOfRates_+1 << " required, " <<
                   discRatios.size() << " provided");
        QL_REQUIRE(firstValidIndex<numberOfRates_,
                   "first valid index must be less than " <<
                   numberOfRates_+1 << ": " <<
                   firstValidIndex << " not allowed");
        // first copy input...
        first_ = firstValidIndex;
        std::copy(discRatios.begin()+first_, discRatios.end(),
                  discRatios_.begin()+first_);
        // ...then calculate forwards
        for (Size i=first_; i<numberOfRates_; ++i)
            forwardRates_[i] = (discRatios_[i]/discRatios_[i+1]-1.0) /
                                                                rateTaus_[i];
        // lazy evaluation of:
        // - coterminal swap rates/annuities
        // - constant maturity swap rates/annuities
        firstCotAnnuityComped_ = numberOfRates_;
    }
void QuantLib::LMMCurveState::setOnForwardRates (const std::vector< Rate > & fwdRates, Size firstValidIndex = 0)
Definition at line 41 of file lmmcurvestate.cpp.
References discRatios_, first_, firstCotAnnuityComped_, forwardRates_, QuantLib::CurveState::numberOfRates_, QL_REQUIRE, and QuantLib::CurveState::rateTaus_.
Referenced by addCoterminalSwapsAndSwaptions(), QuantLib::LogNormalFwdRateBalland::advanceStep(), QuantLib::LogNormalFwdRateiBalland::advanceStep(), QuantLib::LogNormalFwdRateEuler::advanceStep(), QuantLib::LogNormalFwdRateIpc::advanceStep(), QuantLib::LogNormalFwdRatePc::advanceStep(), QuantLib::NormalFwdRatePc::advanceStep(), QuantLib::SVDDFwdRatePc::advanceStep(), QuantLib::LogNormalFwdRateEulerConstrained::advanceStep(), QuantLib::CapPseudoDerivative::CapPseudoDerivative(), anonymous_namespace{marketmodel_cms.cpp}::checkCMSAndSwaptions(), anonymous_namespace{marketmodel_smm.cpp}::checkCoterminalSwapsAndSwaptions(), QuantLib::FwdPeriodAdapter::FwdPeriodAdapter(), QuantLib::FwdToCotSwapAdapter::FwdToCotSwapAdapter(), QuantLib::MarketModelPathwiseCoterminalSwaptionsNumericalDeflated::nextTimeStep(), anonymous_namespace{marketmodel_cms.cpp}::setup(), anonymous_namespace{marketmodel_smm.cpp}::setup(), anonymous_namespace{marketmodel_smmcapletcalibration.cpp}::setup(), anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::setup(), anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::setup(), QuantLib::SwapForwardMappings::swaptionImpliedVolatility(), CurveStatesTest::testCMSwapCurveState(), SwapForwardMappingsTest::testForwardCoterminalMappings(), SwapForwardMappingsTest::testForwardSwapJacobians(), MarketModelTest::testPathwiseMarketVegas(), MarketModelTest::testPathwiseVegas(), MarketModelTest::testPeriodAdapter(), and SwapForwardMappingsTest::testSwaptionImpliedVolatility().
{
            QL_REQUIRE(rates.size()==numberOfRates_,
                       "rates mismatch: " <<
                       numberOfRates_ << " required, " <<
                       rates.size() << " provided");
            QL_REQUIRE(firstValidIndex<numberOfRates_,
                       "first valid index must be less than " <<
                       numberOfRates_ << ": " <<
                       firstValidIndex << " not allowed");
        // first copy input...
        first_ = firstValidIndex;
        std::copy(rates.begin()+first_, rates.end(),
                  forwardRates_.begin()+first_);
        // ...then calculate discount ratios
        // taken care at constructor time
        //discRatios_[numberOfRates_] = 1.0;
        for (Size i=first_; i<numberOfRates_; ++i)
            discRatios_[i+1]=discRatios_[i]/(1.0+forwardRates_[i]*rateTaus_[i]);
        // lazy evaluation of:
        // - coterminal swap rates/annuities
        // - constant maturity swap rates/annuities
        firstCotAnnuityComped_ = numberOfRates_;
    }
Member Data Documentation
std::vector<Real> QuantLib::LMMCurveState::cmSwapAnnuities_ [mutable, private]
Definition at line 89 of file lmmcurvestate.hpp.
Referenced by cmSwapAnnuity(), cmSwapRate(), and cmSwapRates().
std::vector<Rate> QuantLib::LMMCurveState::cmSwapRates_ [mutable, private]
Definition at line 88 of file lmmcurvestate.hpp.
Referenced by cmSwapAnnuity(), cmSwapRate(), and cmSwapRates().
std::vector<Real> QuantLib::LMMCurveState::cotAnnuities_ [mutable, private]
Definition at line 91 of file lmmcurvestate.hpp.
Referenced by coterminalSwapAnnuity(), and coterminalSwapRates().
std::vector<Rate> QuantLib::LMMCurveState::cotSwapRates_ [mutable, private]
Definition at line 90 of file lmmcurvestate.hpp.
Referenced by coterminalSwapRates().
std::vector<DiscountFactor> QuantLib::LMMCurveState::discRatios_ [private]
Definition at line 86 of file lmmcurvestate.hpp.
Referenced by cmSwapAnnuity(), cmSwapRate(), cmSwapRates(), coterminalSwapAnnuity(), coterminalSwapRate(), coterminalSwapRates(), discountRatio(), setOnDiscountRatios(), and setOnForwardRates().
Size QuantLib::LMMCurveState::first_ [private]
Definition at line 85 of file lmmcurvestate.hpp.
Referenced by cmSwapAnnuity(), cmSwapRate(), cmSwapRates(), coterminalSwapAnnuity(), coterminalSwapRate(), coterminalSwapRates(), discountRatio(), forwardRate(), forwardRates(), setOnDiscountRatios(), and setOnForwardRates().
Size QuantLib::LMMCurveState::firstCotAnnuityComped_ [mutable, private]
Definition at line 93 of file lmmcurvestate.hpp.
Referenced by coterminalSwapAnnuity(), setOnDiscountRatios(), and setOnForwardRates().
std::vector<Rate> QuantLib::LMMCurveState::forwardRates_ [private]
Definition at line 87 of file lmmcurvestate.hpp.
Referenced by forwardRate(), forwardRates(), setOnDiscountRatios(), and setOnForwardRates().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/curvestates/lmmcurvestate.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/curvestates/lmmcurvestate.cpp