QuantLib: QuantLib::GFunctionFactory::GFunctionExactYield Class Reference
QuantLib::GFunctionFactory::GFunctionExactYield Class Reference
Public Member Functions
GFunctionExactYield (const CmsCoupon &coupon)
Real operator() (Real x)
Real firstDerivative (Real x)
Real secondDerivative (Real x)
Protected Attributes
Real delta_
std::vector< Time > accruals_
Detailed Description
Definition at line 109 of file conundrumpricer.hpp.
Constructor & Destructor Documentation
QuantLib::GFunctionFactory::GFunctionExactYield::GFunctionExactYield (const CmsCoupon & coupon)
Definition at line 564 of file conundrumpricer.cpp.
References anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::accruals_, QuantLib::Coupon::date(), QuantLib::Schedule::date(), QuantLib::FloatingRateCoupon::fixingDate(), QuantLib::Schedule::startDate(), QuantLib::swap(), QuantLib::CmsCoupon::swapIndex(), and QuantLib::DayCounter::yearFraction().
{
        const boost::shared_ptr<SwapIndex>& swapIndex = coupon.swapIndex();
        const boost::shared_ptr<VanillaSwap>& swap =
            swapIndex->underlyingSwap(coupon.fixingDate());
        const Schedule& schedule = swap->fixedSchedule();
        Handle<YieldTermStructure> rateCurve =
            swapIndex->forwardingTermStructure();
        const DayCounter& dc = swapIndex->dayCounter();
        Real swapStartTime = dc.yearFraction(rateCurve->referenceDate(),
                                             schedule.startDate());
        Real swapFirstPaymentTime = dc.yearFraction(rateCurve->referenceDate(),
                                                    schedule.date(1));
        Real paymentTime = dc.yearFraction(rateCurve->referenceDate(),
                                                 coupon.date());
        delta_ = (paymentTime-swapStartTime) / (swapFirstPaymentTime-swapStartTime);
        const Leg& fixedLeg(swap->fixedLeg());
        Size n = fixedLeg.size();
        accruals_.reserve(n);
        for (Size i=0; i<n; ++i) {
            boost::shared_ptr<Coupon> coupon =
                boost::dynamic_pointer_cast<Coupon>(fixedLeg[i]);
            accruals_.push_back(coupon->accrualPeriod());
        }
    }
Member Function Documentation
Real QuantLib::GFunctionFactory::GFunctionExactYield::firstDerivative (Real x) [virtual]
Implements QuantLib::GFunction.
Definition at line 604 of file conundrumpricer.cpp.
References anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::accruals_, anonymous_namespace{marketmodel.cpp}::b, anonymous_namespace{marketmodel.cpp}::c, and QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow().
{
        Real c = -1.;
        Real derC = 0.;
        std::vector<Real> b;
        b.reserve(accruals_.size());
        for (Size i=0; i<accruals_.size(); i++) {
            Real temp = 1.0/(1.0+ accruals_[i]*x);
            b.push_back(temp);
            c *= temp;
            derC += accruals_[i]*temp;
        }
        c += 1.;
        c = 1./c;
        derC *= (c-c*c);
        return -delta_*accruals_[0]*std::pow(b[0],delta_+1.)*x*c+
                std::pow(b[0],delta_)*c+ std::pow(b[0],delta_)*x*derC;
        //Real dx = 1.0e-8;
        //return (operator()(x+dx)-operator()(x-dx))/(2.0*dx);
    }
Real QuantLib::GFunctionFactory::GFunctionExactYield::operator() (Real x) [virtual]
Implements QuantLib::GFunction.
Definition at line 596 of file conundrumpricer.cpp.
References anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::accruals_, and QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow().
{
        Real product = 1.;
        for(Size i=0; i<accruals_.size(); i++) {
            product *= 1./(1.+ accruals_[i]*x);
        }
        return x*std::pow(1.+ accruals_[0]*x,-delta_)*(1./(1.-product));
    }
Real QuantLib::GFunctionFactory::GFunctionExactYield::secondDerivative (Real x) [virtual]
Implements QuantLib::GFunction.
Definition at line 625 of file conundrumpricer.cpp.
References anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::accruals_, anonymous_namespace{marketmodel.cpp}::b, anonymous_namespace{marketmodel.cpp}::c, and QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow().
{
        Real c = -1.;
        Real sum = 0.;
        Real sumOfSquare = 0.;
        std::vector<Real> b;
        b.reserve(accruals_.size());
        for(Size i=0; i<accruals_.size(); i++) {
            Real temp = 1.0/(1.0+ accruals_[i]*x);
            b.push_back(temp);
            c *= temp;
            sum += accruals_[i]*temp;
            sumOfSquare += std::pow(accruals_[i]*temp, 2.0);
        }
        c += 1.;
        c = 1./c;
        Real derC =sum*(c-c*c);
        return (-delta_*accruals_[0]*std::pow(b[0],delta_+1.)*c+ std::pow(b[0],delta_)*derC)*
               (-delta_*accruals_[0]*b[0]*x + 1. + x*(1.-c)*sum)+
                std::pow(b[0],delta_)*c*(delta_*std::pow(accruals_[0]*b[0],2.)*x - delta_* accruals_[0]*b[0] -
                x*derC*sum + (1.-c)*sum - x*(1.-c)*sumOfSquare);
        //Real dx = 1.0e-8;
        //return (firstDerivative(x+dx)-firstDerivative(x-dx))/(2.0*dx);
    }
Member Data Documentation
std::vector<Time> QuantLib::GFunctionFactory::GFunctionExactYield::accruals_ [protected]
Definition at line 120 of file conundrumpricer.hpp.
Real QuantLib::GFunctionFactory::GFunctionExactYield::delta_ [protected]
Definition at line 118 of file conundrumpricer.hpp.
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/conundrumpricer.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/conundrumpricer.cpp