QuantLib: QuantLib::LocalVolTermStructure Class Reference
QuantLib::LocalVolTermStructure Class Reference
#include <localvoltermstructure.hpp>
Public Member Functions
virtual ~LocalVolTermStructure ()
Constructors
See the TermStructure documentation for issues regarding constructors.
LocalVolTermStructure (const Calendar &cal, BusinessDayConvention bdc=Following, const DayCounter &dc=DayCounter())
LocalVolTermStructure (BusinessDayConvention bdc=Following, const DayCounter &dc=DayCounter())
default constructor
LocalVolTermStructure (const Date &referenceDate, const Calendar &cal=Calendar(), BusinessDayConvention bdc=Following, const DayCounter &dc=DayCounter())
initialize with a fixed reference date
LocalVolTermStructure (Natural settlementDays, const Calendar &, BusinessDayConvention bdc=Following, const DayCounter &dc=DayCounter())
calculate the reference date based on the global evaluation date
Local Volatility
Volatility localVol (const Date &d, Real underlyingLevel, bool extrapolate=false) const
Volatility localVol (Time t, Real underlyingLevel, bool extrapolate=false) const
Visitability
virtual void accept (AcyclicVisitor &)
Protected Member Functions
Calculations
These methods must be implemented in derived classes to perform the actual volatility calculations. When they are called, range check has already been performed; therefore, they must assume that extrapolation is required.
virtual Volatility localVolImpl (Time t, Real strike) const =0
local vol calculation
Detailed Description
This abstract class defines the interface of concrete local-volatility term structures which will be derived from this one.
Volatilities are assumed to be expressed on an annual basis.
Definition at line 38 of file localvoltermstructure.hpp.
Constructor & Destructor Documentation
QuantLib::LocalVolTermStructure::LocalVolTermStructure (const Calendar & cal, BusinessDayConvention bdc = Following, const DayCounter & dc = DayCounter())
Warning:
term structures initialized by means of this constructor must manage their own reference date by overriding the referenceDate() method.
Definition at line 25 of file localvoltermstructure.cpp.
    : VolatilityTermStructure(cal, bdc, dc) {}
QuantLib::LocalVolTermStructure::LocalVolTermStructure (BusinessDayConvention bdc = Following, const DayCounter & dc = DayCounter())
default constructor
Warning:
term structures initialized by means of this constructor must manage their own reference date by overriding the referenceDate() method.
Definition at line 31 of file localvoltermstructure.cpp.
    : VolatilityTermStructure(bdc, dc) {}
QuantLib::LocalVolTermStructure::LocalVolTermStructure (const Date & referenceDate, const Calendar & cal = Calendar(), BusinessDayConvention bdc = Following, const DayCounter & dc = DayCounter())
initialize with a fixed reference date
Definition at line 35 of file localvoltermstructure.cpp.
    : VolatilityTermStructure(referenceDate, cal, bdc, dc) {}
QuantLib::LocalVolTermStructure::LocalVolTermStructure (Natural settlementDays, const Calendar & cal, BusinessDayConvention bdc = Following, const DayCounter & dc = DayCounter())
calculate the reference date based on the global evaluation date
Definition at line 41 of file localvoltermstructure.cpp.
    : VolatilityTermStructure(settlementDays, cal, bdc, dc) {}
virtual QuantLib::LocalVolTermStructure::~LocalVolTermStructure () [inline, virtual]
Definition at line 72 of file localvoltermstructure.hpp.
{}
Member Function Documentation
void QuantLib::LocalVolTermStructure::accept (AcyclicVisitor & v) [virtual]
Reimplemented in QuantLib::LocalVolSurface, QuantLib::LocalConstantVol, and QuantLib::LocalVolCurve.
Definition at line 64 of file localvoltermstructure.cpp.
References QL_FAIL, anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Visitor< T >::visit().
{
        Visitor<LocalVolTermStructure>* v1 =
            dynamic_cast<Visitor<LocalVolTermStructure>*>(&v);
        if (v1 != 0)
            v1->visit(*this);
        else
            QL_FAIL("not a local-volatility term structure visitor");
    }
Volatility QuantLib::LocalVolTermStructure::localVol (const Date & d, Real underlyingLevel, bool extrapolate = false) const
Definition at line 47 of file localvoltermstructure.cpp.
References QuantLib::TermStructure::checkRange(), QuantLib::VolatilityTermStructure::checkStrike(), localVolImpl(), anonymous_namespace{quantlibbenchmark.cpp}::t, and QuantLib::TermStructure::timeFromReference().
{
        checkRange(d, extrapolate);
        checkStrike(underlyingLevel, extrapolate);
        Time t = timeFromReference(d);
        return localVolImpl(t, underlyingLevel);
    }
Volatility QuantLib::LocalVolTermStructure::localVol (Time t, Real underlyingLevel, bool extrapolate = false) const
Definition at line 56 of file localvoltermstructure.cpp.
References QuantLib::TermStructure::checkRange(), QuantLib::VolatilityTermStructure::checkStrike(), and localVolImpl().
{
        checkRange(t, extrapolate);
        checkStrike(underlyingLevel, extrapolate);
        return localVolImpl(t, underlyingLevel);
    }
virtual Volatility QuantLib::LocalVolTermStructure::localVolImpl (Time t, Real strike) const [protected, pure virtual]
local vol calculation
Implemented in QuantLib::LocalVolSurface, QuantLib::LocalConstantVol, and QuantLib::LocalVolCurve.
Referenced by localVol().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/equityfx/localvoltermstructure.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/equityfx/localvoltermstructure.cpp