QuantLib: QuantLib::KInterpolatedYoYOptionletVolatilitySurface< Interpolator1D > Class Template Reference
QuantLib::KInterpolatedYoYOptionletVolatilitySurface< Interpolator1D > Class Template Reference
K-interpolated YoY optionlet volatility.
#include <kinterpolatedyoyoptionletvolatilitysurface.hpp>
Constructor
calculate the reference date based on the global evaluation date
boost::shared_ptr
< YoYCapFloorTermPriceSurface > capFloorPrices_
boost::shared_ptr
< YoYInflationCapFloorEngine > yoyInflationCouponPricer_
boost::shared_ptr
< YoYOptionletStripper > yoyOptionletStripper_
Interpolator1D factory1D_
Real slope_
bool lastDateisSet_
Date lastDate_
Interpolation tempKinterpolation_
std::pair< std::vector< Rate >
, std::vector< Volatility > > slice_
KInterpolatedYoYOptionletVolatilitySurface (const Natural settlementDays, const Calendar &, const BusinessDayConvention bdc, const DayCounter &dc, const Period &lag, const boost::shared_ptr< YoYCapFloorTermPriceSurface > &capFloorPrices, const boost::shared_ptr< YoYInflationCapFloorEngine > &pricer, const boost::shared_ptr< YoYOptionletStripper > &yoyOptionletStripper, const Real slope, const Interpolator1D &interpolator=Interpolator1D())
virtual Real minStrike () const
the minimum strike for which the term structure can return vols
virtual Real maxStrike () const
the maximum strike for which the term structure can return vols
virtual Date maxDate () const
the latest date for which the curve can return values
std::pair< std::vector< Rate >
, std::vector< Volatility > > Dslice (const Date &d) const
virtual Volatility volatilityImpl (const Date &d, Rate strike) const
virtual Volatility volatilityImpl (Time length, Rate strike) const
virtual void performCalculations () const
Detailed Description
template<class Interpolator1D>
class QuantLib::KInterpolatedYoYOptionletVolatilitySurface< Interpolator1D >
K-interpolated YoY optionlet volatility.
The stripper provides curves in the T direction along each K. We don't know whether this is interpolating or fitting in the T direction. Our K direction interpolations are not model fitting.
An alternative design would be a FittedYoYOptionletVolatilitySurface taking a model, e.g. SABR in the interest rate world. This could use the same stripping in the T direction along each K.
Bug:
Tests currently fail.
Definition at line 45 of file kinterpolatedyoyoptionletvolatilitysurface.hpp.
Constructor & Destructor Documentation
template<class Interpolator1D > QuantLib::KInterpolatedYoYOptionletVolatilitySurface< Interpolator1D >::KInterpolatedYoYOptionletVolatilitySurface (const Natural settlementDays, const Calendar & cal, const BusinessDayConvention bdc, const DayCounter & dc, const Period & lag, const boost::shared_ptr< YoYCapFloorTermPriceSurface > & capFloorPrices, const boost::shared_ptr< YoYInflationCapFloorEngine > & pricer, const boost::shared_ptr< YoYOptionletStripper > & yoyOptionletStripper, const Real slope, const Interpolator1D & interpolator = Interpolator1D())
Definition at line 92 of file kinterpolatedyoyoptionletvolatilitysurface.hpp.
References QuantLib::KInterpolatedYoYOptionletVolatilitySurface< Interpolator1D >::performCalculations().
    : YoYOptionletVolatilitySurface(settlementDays, cal, bdc, dc, lag,
                                    capFloorPrices->yoyIndex()->frequency(),
                                    capFloorPrices->yoyIndex()->interpolated()),
      capFloorPrices_(capFloorPrices), yoyInflationCouponPricer_(pricer),
      yoyOptionletStripper_(yoyOptionletStripper),
      factory1D_(interpolator), slope_(slope), lastDateisSet_(false) {
        performCalculations();
    }
Member Function Documentation
template<class Interpolator1D > std::pair< std::vector< Rate >, std::vector< Volatility > > QuantLib::KInterpolatedYoYOptionletVolatilitySurface< Interpolator1D >::Dslice (const Date & d) const
Definition at line 168 of file kinterpolatedyoyoptionletvolatilitysurface.hpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v().
{
        // make sure that the correct D slice is in slice_
        Rate strike = (minStrike() + maxStrike())/2.0;
        Volatility v = volatilityImpl(d, strike); v = v+v;//dummy but needed
        return slice_;
    }
template<class Interpolator1D > Date QuantLib::KInterpolatedYoYOptionletVolatilitySurface< Interpolator1D >::maxDate () const [virtual]
the latest date for which the curve can return values
Implements QuantLib::TermStructure.
Definition at line 115 of file kinterpolatedyoyoptionletvolatilitysurface.hpp.
                    {
        Size n = capFloorPrices_->maturities().size();
        return referenceDate()+capFloorPrices_->maturities()[n-1];
    }
template<class Interpolator1D > Real QuantLib::KInterpolatedYoYOptionletVolatilitySurface< Interpolator1D >::maxStrike () const [virtual]
the maximum strike for which the term structure can return vols
Implements QuantLib::YoYOptionletVolatilitySurface.
Definition at line 130 of file kinterpolatedyoyoptionletvolatilitysurface.hpp.
                      {
        return capFloorPrices_->strikes().back();
    }
template<class Interpolator1D > Real QuantLib::KInterpolatedYoYOptionletVolatilitySurface< Interpolator1D >::minStrike () const [virtual]
the minimum strike for which the term structure can return vols
Implements QuantLib::YoYOptionletVolatilitySurface.
Definition at line 123 of file kinterpolatedyoyoptionletvolatilitysurface.hpp.
                      {
        return capFloorPrices_->strikes().front();
    }
template<class Interpolator1D > void QuantLib::KInterpolatedYoYOptionletVolatilitySurface< Interpolator1D >::performCalculations () const [protected, virtual]
Definition at line 137 of file kinterpolatedyoyoptionletvolatilitysurface.hpp.
Referenced by QuantLib::KInterpolatedYoYOptionletVolatilitySurface< Interpolator1D >::KInterpolatedYoYOptionletVolatilitySurface().
{
        // slope is the assumption on the initial caplet volatility change
        yoyOptionletStripper_->initialize(capFloorPrices_,
                                          yoyInflationCouponPricer_,
                                          slope_);
    }
template<class Interpolator1D > Volatility QuantLib::KInterpolatedYoYOptionletVolatilitySurface< Interpolator1D >::volatilityImpl (const Date & d, Rate strike) const [protected, virtual]
Definition at line 148 of file kinterpolatedyoyoptionletvolatilitysurface.hpp.
References anonymous_namespace{marketmodel.cpp}::d.
{
        if (!lastDateisSet_ || d != lastDate_ ) {
            slice_ = yoyOptionletStripper_->slice(d);
            tempKinterpolation_ =
                factory1D_.interpolate( slice_.first.begin(),
                                        slice_.first.end(),
                                        slice_.second.begin() );
            lastDateisSet_ = true;
            lastDate_ = d;
        }
        return tempKinterpolation_(strike);
    }
template<class Interpolator1D > Volatility QuantLib::KInterpolatedYoYOptionletVolatilitySurface< Interpolator1D >::volatilityImpl (Time length, Rate strike) const [protected, virtual]
Implements the actual volatility surface calculation in derived classes e.g. bilinear interpolation. N.B. does not derive the surface.
Implements QuantLib::YoYOptionletVolatilitySurface.
Definition at line 179 of file kinterpolatedyoyoptionletvolatilitysurface.hpp.
References anonymous_namespace{marketmodel.cpp}::d, QuantLib::Days, QuantLib::days(), QuantLib::Years, and QuantLib::years().
{
        Natural years = (Natural)floor(length);
        Natural days = (Natural)floor((length - years) * 365.0);
        Date d = referenceDate() + Period(years, Years) + Period(days, Days);
        return this->volatilityImpl(d, strike);
    }
Member Data Documentation
template<class Interpolator1D > boost::shared_ptr<YoYCapFloorTermPriceSurface> QuantLib::KInterpolatedYoYOptionletVolatilitySurface< Interpolator1D >::capFloorPrices_ [protected]
Definition at line 75 of file kinterpolatedyoyoptionletvolatilitysurface.hpp.
template<class Interpolator1D > Interpolator1D QuantLib::KInterpolatedYoYOptionletVolatilitySurface< Interpolator1D >::factory1D_ [mutable, protected]
Definition at line 79 of file kinterpolatedyoyoptionletvolatilitysurface.hpp.
template<class Interpolator1D > Date QuantLib::KInterpolatedYoYOptionletVolatilitySurface< Interpolator1D >::lastDate_ [mutable, protected]
Definition at line 82 of file kinterpolatedyoyoptionletvolatilitysurface.hpp.
template<class Interpolator1D > bool QuantLib::KInterpolatedYoYOptionletVolatilitySurface< Interpolator1D >::lastDateisSet_ [mutable, protected]
Definition at line 81 of file kinterpolatedyoyoptionletvolatilitysurface.hpp.
template<class Interpolator1D > std::pair<std::vector<Rate>, std::vector<Volatility> > QuantLib::KInterpolatedYoYOptionletVolatilitySurface< Interpolator1D >::slice_ [mutable, protected]
Definition at line 84 of file kinterpolatedyoyoptionletvolatilitysurface.hpp.
template<class Interpolator1D > Real QuantLib::KInterpolatedYoYOptionletVolatilitySurface< Interpolator1D >::slope_ [mutable, protected]
Definition at line 80 of file kinterpolatedyoyoptionletvolatilitysurface.hpp.
template<class Interpolator1D > Interpolation QuantLib::KInterpolatedYoYOptionletVolatilitySurface< Interpolator1D >::tempKinterpolation_ [mutable, protected]
Definition at line 83 of file kinterpolatedyoyoptionletvolatilitysurface.hpp.
template<class Interpolator1D > boost::shared_ptr<YoYInflationCapFloorEngine> QuantLib::KInterpolatedYoYOptionletVolatilitySurface< Interpolator1D >::yoyInflationCouponPricer_ [protected]
Definition at line 76 of file kinterpolatedyoyoptionletvolatilitysurface.hpp.
template<class Interpolator1D > boost::shared_ptr<YoYOptionletStripper> QuantLib::KInterpolatedYoYOptionletVolatilitySurface< Interpolator1D >::yoyOptionletStripper_ [protected]
Definition at line 77 of file kinterpolatedyoyoptionletvolatilitysurface.hpp.
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/inflation/kinterpolatedyoyoptionletvolatilitysurface.hpp