QuantLib: QuantLib::anonymous_namespace{analyticvariancegammaengine.cpp}::Integrand Class Reference
QuantLib::anonymous_namespace{analyticvariancegammaengine.cpp}::Integrand Class Reference
Public Member Functions
Integrand (const boost::shared_ptr< StrikedTypePayoff > &payoff, Real s0, Real t, Real riskFreeDiscount, Real dividendDiscount, Real sigma, Real nu, Real theta)
Real operator() (Real x) const
Private Attributes
boost::shared_ptr
< StrikedTypePayoff > payoff_
Real s0_
Real t_
Real riskFreeDiscount_
Real dividendDiscount_
Rate sigma_
Real nu_
Real theta_
Real omega_
Real gammaDenom_
Detailed Description
Definition at line 31 of file analyticvariancegammaengine.cpp.
Constructor & Destructor Documentation
QuantLib::anonymous_namespace{analyticvariancegammaengine.cpp}::Integrand::Integrand (const boost::shared_ptr< StrikedTypePayoff > & payoff, Real s0, Real t, Real riskFreeDiscount, Real dividendDiscount, Real sigma, Real nu, Real theta) [inline]
Definition at line 33 of file analyticvariancegammaengine.cpp.
References QuantLib::GammaFunction::logValue(), and QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow().
                : payoff_(payoff), s0_(s0), t_(t), riskFreeDiscount_(riskFreeDiscount),
                    dividendDiscount_(dividendDiscount),
                    sigma_(sigma), nu_(nu), theta_(theta) {
                omega_ = std::log(1.0 - theta_ * nu_ - (sigma_ * sigma_ * nu_) / 2.0) / nu_;
                // We can precompute the denominator of the gamma pdf (does not depend on x)
                // shape = t_/nu_, scale = nu_
                GammaFunction gf;
                gammaDenom_ = std::exp(gf.logValue(t_ / nu_)) * std::pow(nu_, t_ / nu_);
            }
Member Function Documentation
Real QuantLib::anonymous_namespace{analyticvariancegammaengine.cpp}::Integrand::operator() (Real x) const [inline]
Definition at line 46 of file analyticvariancegammaengine.cpp.
References QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow(), and QuantLib::BlackCalculator::value().
{
                // Compute adjusted black scholes price
                Real s0_adj = s0_ * std::exp(theta_ * x + omega_ * t_ + (sigma_ * sigma_ * x) / 2.0);
                Real vol_adj = sigma_ * sqrt(x / t_);
                vol_adj *= sqrt(t_);
                BlackScholesCalculator bs(payoff_, s0_adj, dividendDiscount_, vol_adj, riskFreeDiscount_);
                Real bsprice = bs.value();
                // Multiply by gamma distribution
                Real gamp = (std::pow(x, t_ / nu_ - 1.0) * std::exp(-x / nu_)) / gammaDenom_;
                Real result = bsprice * gamp;
                return result;
            }
Member Data Documentation
Real QuantLib::anonymous_namespace{analyticvariancegammaengine.cpp}::Integrand::dividendDiscount_ [private]
Definition at line 66 of file analyticvariancegammaengine.cpp.
Real QuantLib::anonymous_namespace{analyticvariancegammaengine.cpp}::Integrand::gammaDenom_ [private]
Definition at line 71 of file analyticvariancegammaengine.cpp.
Real QuantLib::anonymous_namespace{analyticvariancegammaengine.cpp}::Integrand::nu_ [private]
Definition at line 68 of file analyticvariancegammaengine.cpp.
Real QuantLib::anonymous_namespace{analyticvariancegammaengine.cpp}::Integrand::omega_ [private]
Definition at line 70 of file analyticvariancegammaengine.cpp.
boost::shared_ptr<StrikedTypePayoff> QuantLib::anonymous_namespace{analyticvariancegammaengine.cpp}::Integrand::payoff_ [private]
Definition at line 62 of file analyticvariancegammaengine.cpp.
Real QuantLib::anonymous_namespace{analyticvariancegammaengine.cpp}::Integrand::riskFreeDiscount_ [private]
Definition at line 65 of file analyticvariancegammaengine.cpp.
Real QuantLib::anonymous_namespace{analyticvariancegammaengine.cpp}::Integrand::s0_ [private]
Definition at line 63 of file analyticvariancegammaengine.cpp.
Rate QuantLib::anonymous_namespace{analyticvariancegammaengine.cpp}::Integrand::sigma_ [private]
Definition at line 67 of file analyticvariancegammaengine.cpp.
Real QuantLib::anonymous_namespace{analyticvariancegammaengine.cpp}::Integrand::t_ [private]
Definition at line 64 of file analyticvariancegammaengine.cpp.
Real QuantLib::anonymous_namespace{analyticvariancegammaengine.cpp}::Integrand::theta_ [private]
Definition at line 69 of file analyticvariancegammaengine.cpp.
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/variancegamma/analyticvariancegammaengine.cpp