QuantLib: QuantLib::FdmHestonHullWhiteOp Class Reference
QuantLib::FdmHestonHullWhiteOp Class Reference
#include <fdmhestonhullwhiteop.hpp>
Public Member Functions
FdmHestonHullWhiteOp (const boost::shared_ptr< FdmMesher > &mesher, const boost::shared_ptr< HestonProcess > &hestonProcess, const boost::shared_ptr< HullWhiteProcess > &hwProcess, Real equityShortRateCorrelation)
Size size () const
void setTime (Time t1, Time t2)
Time \(t1 <= t2\) is required.
Disposable< Array > apply (const Array &r) const
Disposable< Array > apply_mixed (const Array &r) const
Disposable< Array > apply_direction (Size direction, const Array &r) const
Disposable< Array > solve_splitting (Size direction, const Array &r, Real s) const
Disposable< Array > preconditioner (const Array &r, Real s) const
Disposable< SparseMatrix > toMatrix () const
Private Attributes
const Real v0_
const Real kappa_
const Real theta_
const Real sigma_
const Real rho_
const boost::shared_ptr
< HullWhite > hwModel_
NinePointLinearOp hestonCorrMap_
NinePointLinearOp equityIrCorrMap_
TripleBandLinearOp dyMap_
FdmHestonHullWhiteEquityPart dxMap_
FdmHullWhiteOp hullWhiteOp_
Detailed Description
Definition at line 63 of file fdmhestonhullwhiteop.hpp.
Constructor & Destructor Documentation
QuantLib::FdmHestonHullWhiteOp::FdmHestonHullWhiteOp (const boost::shared_ptr< FdmMesher > & mesher, const boost::shared_ptr< HestonProcess > & hestonProcess, const boost::shared_ptr< HullWhiteProcess > & hwProcess, Real equityShortRateCorrelation)
Definition at line 76 of file fdmhestonhullwhiteop.cpp.
References QL_REQUIRE.
    : v0_(hestonProcess->v0()),
      kappa_(hestonProcess->kappa()),
      theta_(hestonProcess->theta()),
      sigma_(hestonProcess->sigma()),
      rho_(hestonProcess->rho()),
      hwModel_(new HullWhite(hestonProcess->riskFreeRate(),
                             hwProcess->a(), hwProcess->sigma())),
      hestonCorrMap_(SecondOrderMixedDerivativeOp(0, 1, mesher)
                     .mult(rho_*sigma_*mesher->locations(1))),
      equityIrCorrMap_(SecondOrderMixedDerivativeOp(0, 2, mesher)
                       .mult(Sqrt(mesher->locations(1))
                              * hwProcess->sigma()
                              * equityShortRateCorrelation)),
      dyMap_(SecondDerivativeOp(1u, mesher)
              .mult(0.5*sigma_*sigma_*mesher->locations(1))
            .add(FirstDerivativeOp(1, mesher)
              .mult(kappa_*(theta_ - mesher->locations(1))))),
      dxMap_(mesher, hwModel_, hestonProcess->dividendYield().currentLink()),
      hullWhiteOp_(mesher, hwModel_, 2) {
        QL_REQUIRE(  equityShortRateCorrelation*equityShortRateCorrelation
                   + hestonProcess->rho()*hestonProcess->rho() <= 1.0,
                   "correlation matrix has negative eigenvalues");
    }
Member Function Documentation
Disposable< Array > QuantLib::FdmHestonHullWhiteOp::apply (const Array & r) const [virtual]
Implements QuantLib::FdmLinearOp.
Definition at line 115 of file fdmhestonhullwhiteop.cpp.
References QuantLib::NinePointLinearOp::apply(), QuantLib::FdmHullWhiteOp::apply(), QuantLib::TripleBandLinearOp::apply(), dxMap_, dyMap_, equityIrCorrMap_, QuantLib::FdmHestonHullWhiteEquityPart::getMap(), hestonCorrMap_, and hullWhiteOp_.
{
        return  dyMap_.apply(u) + dxMap_.getMap().apply(u)
              + hullWhiteOp_.apply(u)
              + hestonCorrMap_.apply(u) + equityIrCorrMap_.apply(u);
    }
Disposable< Array > QuantLib::FdmHestonHullWhiteOp::apply_direction (Size direction, const Array & r) const [virtual]
Implements QuantLib::FdmLinearOpComposite.
Definition at line 122 of file fdmhestonhullwhiteop.cpp.
References QuantLib::FdmHullWhiteOp::apply(), QuantLib::TripleBandLinearOp::apply(), dxMap_, dyMap_, QuantLib::FdmHestonHullWhiteEquityPart::getMap(), hullWhiteOp_, and QL_FAIL.
{
        if (direction == 0)
            return dxMap_.getMap().apply(r);
        else if (direction == 1)
            return dyMap_.apply(r);
        else if (direction == 2)
            return hullWhiteOp_.apply(r);
        else
            QL_FAIL("direction too large");
    }
Disposable< Array > QuantLib::FdmHestonHullWhiteOp::apply_mixed (const Array & r) const [virtual]
Implements QuantLib::FdmLinearOpComposite.
Definition at line 134 of file fdmhestonhullwhiteop.cpp.
References QuantLib::NinePointLinearOp::apply(), equityIrCorrMap_, and hestonCorrMap_.
{
        return hestonCorrMap_.apply(r) + equityIrCorrMap_.apply(r);
    }
Disposable< Array > QuantLib::FdmHestonHullWhiteOp::preconditioner (const Array & r, Real s) const [virtual]
Implements QuantLib::FdmLinearOpComposite.
Definition at line 154 of file fdmhestonhullwhiteop.cpp.
References solve_splitting().
{
        return solve_splitting(0, r, dt);
    }
void QuantLib::FdmHestonHullWhiteOp::setTime (Time t1, Time t2) [virtual]
Time \(t1 <= t2\) is required.
Implements QuantLib::FdmLinearOpComposite.
Definition at line 106 of file fdmhestonhullwhiteop.cpp.
References dxMap_, hullWhiteOp_, QuantLib::FdmHullWhiteOp::setTime(), and QuantLib::FdmHestonHullWhiteEquityPart::setTime().
{
        dxMap_.setTime(t1, t2);
        hullWhiteOp_.setTime(t1, t2);
    }
Size QuantLib::FdmHestonHullWhiteOp::size () const [virtual]
Implements QuantLib::FdmLinearOpComposite.
Definition at line 111 of file fdmhestonhullwhiteop.cpp.
{
        return 3;
    }
Disposable< Array > QuantLib::FdmHestonHullWhiteOp::solve_splitting (Size direction, const Array & r, Real s) const [virtual]
Implements QuantLib::FdmLinearOpComposite.
Definition at line 139 of file fdmhestonhullwhiteop.cpp.
References dxMap_, dyMap_, QuantLib::FdmHestonHullWhiteEquityPart::getMap(), hullWhiteOp_, QL_FAIL, QuantLib::TripleBandLinearOp::solve_splitting(), and QuantLib::FdmHullWhiteOp::solve_splitting().
Referenced by preconditioner().
{
        if (direction == 0) {
            return dxMap_.getMap().solve_splitting(r, a, 1.0);
        }
        else if (direction == 1) {
            return dyMap_.solve_splitting(r, a, 1.0);
        }
        else if (direction == 2) {
            return hullWhiteOp_.solve_splitting(2, r, a);
        }
        else
            QL_FAIL("direction too large");
    }
Disposable< SparseMatrix > QuantLib::FdmHestonHullWhiteOp::toMatrix () const [virtual]
Reimplemented from QuantLib::FdmLinearOp.
Definition at line 160 of file fdmhestonhullwhiteop.cpp.
References dxMap_, dyMap_, equityIrCorrMap_, QuantLib::FdmHestonHullWhiteEquityPart::getMap(), hestonCorrMap_, hullWhiteOp_, QuantLib::NinePointLinearOp::toMatrix(), QuantLib::FdmHullWhiteOp::toMatrix(), and QuantLib::TripleBandLinearOp::toMatrix().
{
        SparseMatrix retVal =
                dyMap_.toMatrix() + dxMap_.getMap().toMatrix()
              + hullWhiteOp_.toMatrix()
              + hestonCorrMap_.toMatrix() + equityIrCorrMap_.toMatrix();
        return retVal;
    }
Member Data Documentation
FdmHestonHullWhiteEquityPart QuantLib::FdmHestonHullWhiteOp::dxMap_ [private]
Definition at line 93 of file fdmhestonhullwhiteop.hpp.
Referenced by apply(), apply_direction(), setTime(), solve_splitting(), and toMatrix().
TripleBandLinearOp QuantLib::FdmHestonHullWhiteOp::dyMap_ [private]
Definition at line 92 of file fdmhestonhullwhiteop.hpp.
Referenced by apply(), apply_direction(), solve_splitting(), and toMatrix().
NinePointLinearOp QuantLib::FdmHestonHullWhiteOp::equityIrCorrMap_ [private]
Definition at line 91 of file fdmhestonhullwhiteop.hpp.
Referenced by apply(), apply_mixed(), and toMatrix().
NinePointLinearOp QuantLib::FdmHestonHullWhiteOp::hestonCorrMap_ [private]
Definition at line 90 of file fdmhestonhullwhiteop.hpp.
Referenced by apply(), apply_mixed(), and toMatrix().
FdmHullWhiteOp QuantLib::FdmHestonHullWhiteOp::hullWhiteOp_ [private]
Definition at line 94 of file fdmhestonhullwhiteop.hpp.
Referenced by apply(), apply_direction(), setTime(), solve_splitting(), and toMatrix().
const boost::shared_ptr<HullWhite> QuantLib::FdmHestonHullWhiteOp::hwModel_ [private]
Definition at line 88 of file fdmhestonhullwhiteop.hpp.
const Real QuantLib::FdmHestonHullWhiteOp::kappa_ [private]
Definition at line 87 of file fdmhestonhullwhiteop.hpp.
const Real QuantLib::FdmHestonHullWhiteOp::rho_ [private]
Definition at line 87 of file fdmhestonhullwhiteop.hpp.
const Real QuantLib::FdmHestonHullWhiteOp::sigma_ [private]
Definition at line 87 of file fdmhestonhullwhiteop.hpp.
const Real QuantLib::FdmHestonHullWhiteOp::theta_ [private]
Definition at line 87 of file fdmhestonhullwhiteop.hpp.
const Real QuantLib::FdmHestonHullWhiteOp::v0_ [private]
Definition at line 87 of file fdmhestonhullwhiteop.hpp.
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/operators/fdmhestonhullwhiteop.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/operators/fdmhestonhullwhiteop.cpp