QuantLib: QuantLib::AnalyticDigitalAmericanEngine Class Reference
QuantLib::AnalyticDigitalAmericanEngine Class Reference
Analytic pricing engine for American vanilla options with digital payoff.
#include <analyticdigitalamericanengine.hpp>
Public Member Functions
AnalyticDigitalAmericanEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > &)
void calculate () const
Private Attributes
boost::shared_ptr
< GeneralizedBlackScholesProcess > process_
Detailed Description
Analytic pricing engine for American vanilla options with digital payoff.
Todo:
add more greeks (as of now only delta and rho available)
Test:
the correctness of the returned value in case of cash-or-nothing at-hit digital payoff is tested by reproducing results available in literature.
the correctness of the returned value in case of asset-or-nothing at-hit digital payoff is tested by reproducing results available in literature.
the correctness of the returned value in case of cash-or-nothing at-expiry digital payoff is tested by reproducing results available in literature.
the correctness of the returned value in case of asset-or-nothing at-expiry digital payoff is tested by reproducing results available in literature.
the correctness of the returned greeks in case of cash-or-nothing at-hit digital payoff is tested by reproducing numerical derivatives.
Definition at line 55 of file analyticdigitalamericanengine.hpp.
Constructor & Destructor Documentation
QuantLib::AnalyticDigitalAmericanEngine::AnalyticDigitalAmericanEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > & process)
Definition at line 29 of file analyticdigitalamericanengine.cpp.
References process_, and QuantLib::Observer::registerWith().
    : process_(process) {
        registerWith(process_);
    }
Member Function Documentation
void QuantLib::AnalyticDigitalAmericanEngine::calculate () const [virtual]
Implements QuantLib::PricingEngine.
Definition at line 35 of file analyticdigitalamericanengine.cpp.
References QuantLib::GenericEngine< OneAssetOption::arguments, OneAssetOption::results >::arguments_, QuantLib::AmericanPayoffAtHit::delta(), QuantLib::Greeks::delta, QuantLib::Option::arguments::exercise, QuantLib::AmericanPayoffAtHit::gamma(), QuantLib::Greeks::gamma, QuantLib::Option::arguments::payoff, process_, QL_REQUIRE, QuantLib::GenericEngine< OneAssetOption::arguments, OneAssetOption::results >::results_, QuantLib::AmericanPayoffAtHit::rho(), QuantLib::Greeks::rho, anonymous_namespace{quantlibbenchmark.cpp}::t, QuantLib::AmericanPayoffAtHit::value(), QuantLib::AmericanPayoffAtExpiry::value(), QuantLib::Instrument::results::value, and QuantLib::DayCounter::yearFraction().
{
        boost::shared_ptr<AmericanExercise> ex =
            boost::dynamic_pointer_cast<AmericanExercise>(arguments_.exercise);
        QL_REQUIRE(ex, "non-American exercise given");
        QL_REQUIRE(ex->dates()[0] <=
                   process_->blackVolatility()->referenceDate(),
                   "American option with window exercise not handled yet");
        boost::shared_ptr<StrikedTypePayoff> payoff =
            boost::dynamic_pointer_cast<StrikedTypePayoff>(arguments_.payoff);
        QL_REQUIRE(payoff, "non-striked payoff given");
        Real spot = process_->stateVariable()->value();
        QL_REQUIRE(spot > 0.0, "negative or null underlying given");
        Real variance =
            process_->blackVolatility()->blackVariance(ex->lastDate(),
                                                       payoff->strike());
        Rate dividendDiscount =
            process_->dividendYield()->discount(ex->lastDate());
        Rate riskFreeDiscount =
            process_->riskFreeRate()->discount(ex->lastDate());
        if(ex->payoffAtExpiry()) {
            AmericanPayoffAtExpiry pricer(spot, riskFreeDiscount,
                                          dividendDiscount, variance, payoff);
            results_.value = pricer.value();
        } else {
            AmericanPayoffAtHit pricer(spot, riskFreeDiscount,
                                       dividendDiscount, variance, payoff);
            results_.value = pricer.value();
            results_.delta = pricer.delta();
            results_.gamma = pricer.gamma();
            DayCounter rfdc = process_->riskFreeRate()->dayCounter();
            Time t = rfdc.yearFraction(
                                    process_->riskFreeRate()->referenceDate(),
                                    arguments_.exercise->lastDate());
            results_.rho = pricer.rho(t);
        }
    }
Member Data Documentation
boost::shared_ptr<GeneralizedBlackScholesProcess> QuantLib::AnalyticDigitalAmericanEngine::process_ [private]
Definition at line 61 of file analyticdigitalamericanengine.hpp.
Referenced by AnalyticDigitalAmericanEngine(), and calculate().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/vanilla/analyticdigitalamericanengine.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/vanilla/analyticdigitalamericanengine.cpp