QuantLib: QuantLib::PiecewiseZeroSpreadedTermStructure Class Reference
QuantLib::PiecewiseZeroSpreadedTermStructure Class Reference
Term structure with an added vector of spreads on the zero-yield rate.
#include <piecewisezerospreadedtermstructure.hpp>
Public Member Functions
PiecewiseZeroSpreadedTermStructure (const Handle< YieldTermStructure > &, const std::vector< Handle< Quote > > &spreads, const std::vector< Date > &dates, Compounding comp=Continuous, Frequency freq=NoFrequency, const DayCounter &dc=DayCounter())
YieldTermStructure interface
DayCounter dayCounter () const
the day counter used for date/time conversion
Natural settlementDays () const
the settlementDays used for reference date calculation
Calendar calendar () const
the calendar used for reference and/or option date calculation
const Date & referenceDate () const
the date at which discount = 1.0 and/or variance = 0.0
Date maxDate () const
the latest date for which the curve can return values
Protected Member Functions
Rate zeroYieldImpl (Time) const
returns the spreaded zero yield rate
void update ()
Private Member Functions
void updateTimes ()
Spread calcSpread (Time t) const
Private Attributes
Handle< YieldTermStructure > originalCurve_
std::vector< Handle< Quote > > spreads_
std::vector< Date > dates_
std::vector< Time > times_
Compounding comp_
Frequency freq_
DayCounter dc_
Detailed Description
Term structure with an added vector of spreads on the zero-yield rate.
The zero-yield spread at any given date is linearly interpolated between the input data.
Note:
This term structure will remain linked to the original structure, i.e., any changes in the latter will be reflected in this structure as well.
Definition at line 45 of file piecewisezerospreadedtermstructure.hpp.
Constructor & Destructor Documentation
QuantLib::PiecewiseZeroSpreadedTermStructure::PiecewiseZeroSpreadedTermStructure (const Handle< YieldTermStructure > & h, const std::vector< Handle< Quote > > & spreads, const std::vector< Date > & dates, Compounding comp = Continuous, Frequency freq = NoFrequency, const DayCounter & dc = DayCounter()) [inline]
Definition at line 82 of file piecewisezerospreadedtermstructure.hpp.
References dates_, originalCurve_, QL_REQUIRE, QuantLib::Observer::registerWith(), spreads_, and updateTimes().
    : originalCurve_(h), spreads_(spreads), dates_(dates),
      times_(dates_.size()), comp_(comp), freq_(freq), dc_(dc) {
        QL_REQUIRE(!spreads_.empty(), "no spreads given");
        QL_REQUIRE(spreads_.size() == dates_.size(),
                   "spread and date vector have different sizes");
        registerWith(originalCurve_);
        for (Size i = 0; i < spreads_.size(); i++)
            registerWith(spreads_[i]);
        updateTimes();
    }
Member Function Documentation
Spread QuantLib::PiecewiseZeroSpreadedTermStructure::calcSpread (Time t) const [inline, private]
Definition at line 133 of file piecewisezerospreadedtermstructure.hpp.
References QuantLib::anonymous_namespace{yieldtermstructure.cpp}::dt, spreads_, anonymous_namespace{quantlibbenchmark.cpp}::t, and times_.
Referenced by zeroYieldImpl().
{
        if (t <= times_.front()) {
            return spreads_.front()->value();
        } else if (t >= times_.back()) {
            return spreads_.back()->value();
        } else {
            Size i;
            for (i = 0; i < times_.size(); i++)
                if (times_[i] > t) break;
            Time dt = times_[i] - times_[i-1];
            return spreads_[i]->value() * (t - times_[i-1]) / dt
                + spreads_[i-1]->value() * (times_[i] - t) / dt;
        }
    }
Calendar QuantLib::PiecewiseZeroSpreadedTermStructure::calendar () const [inline, virtual]
the calendar used for reference and/or option date calculation
Reimplemented from QuantLib::TermStructure.
Definition at line 104 of file piecewisezerospreadedtermstructure.hpp.
References originalCurve_.
{
        return originalCurve_->calendar();
    }
DayCounter QuantLib::PiecewiseZeroSpreadedTermStructure::dayCounter () const [inline, virtual]
the day counter used for date/time conversion
Reimplemented from QuantLib::TermStructure.
Definition at line 100 of file piecewisezerospreadedtermstructure.hpp.
References originalCurve_.
{
        return originalCurve_->dayCounter();
    }
Date QuantLib::PiecewiseZeroSpreadedTermStructure::maxDate () const [inline, virtual]
the latest date for which the curve can return values
Implements QuantLib::TermStructure.
Definition at line 117 of file piecewisezerospreadedtermstructure.hpp.
References dates_, and originalCurve_.
{
        return std::min(originalCurve_->maxDate(), dates_.back());
    }
const Date & QuantLib::PiecewiseZeroSpreadedTermStructure::referenceDate () const [inline, virtual]
the date at which discount = 1.0 and/or variance = 0.0
Reimplemented from QuantLib::TermStructure.
Definition at line 113 of file piecewisezerospreadedtermstructure.hpp.
References originalCurve_.
{
        return originalCurve_->referenceDate();
    }
Natural QuantLib::PiecewiseZeroSpreadedTermStructure::settlementDays () const [inline, virtual]
the settlementDays used for reference date calculation
Reimplemented from QuantLib::TermStructure.
Definition at line 108 of file piecewisezerospreadedtermstructure.hpp.
References originalCurve_.
{
        return originalCurve_->settlementDays();
    }
void QuantLib::PiecewiseZeroSpreadedTermStructure::update () [inline, protected, virtual]
This method must be implemented in derived classes. An instance of Observer does not call this method directly: instead, it will be called by the observables the instance registered with when they need to notify any changes.
Reimplemented from QuantLib::YieldTermStructure.
Definition at line 148 of file piecewisezerospreadedtermstructure.hpp.
References updateTimes().
{
        updateTimes();
        ZeroYieldStructure::update();
    }
void QuantLib::PiecewiseZeroSpreadedTermStructure::updateTimes () [inline, private]
Definition at line 153 of file piecewisezerospreadedtermstructure.hpp.
References dates_, QuantLib::TermStructure::timeFromReference(), and times_.
Referenced by PiecewiseZeroSpreadedTermStructure(), and update().
{
        for (Size i = 0; i < dates_.size(); i++)
            times_[i] = timeFromReference(dates_[i]);
    }
Rate QuantLib::PiecewiseZeroSpreadedTermStructure::zeroYieldImpl (Time t) const [inline, protected, virtual]
returns the spreaded zero yield rate
Implements QuantLib::ZeroYieldStructure.
Definition at line 122 of file piecewisezerospreadedtermstructure.hpp.
References calcSpread(), comp_, QuantLib::InterestRate::compounding(), QuantLib::Continuous, QuantLib::InterestRate::dayCounter(), QuantLib::InterestRate::equivalentRate(), freq_, QuantLib::InterestRate::frequency(), QuantLib::NoFrequency, originalCurve_, and QuantLib::YieldTermStructure::zeroRate().
{
        Spread spread = calcSpread(t);
        InterestRate zeroRate = originalCurve_->zeroRate(t, comp_, freq_, true);
        InterestRate spreadedRate(zeroRate + spread,
                                  zeroRate.dayCounter(),
                                  zeroRate.compounding(),
                                  zeroRate.frequency());
        return spreadedRate.equivalentRate(Continuous, NoFrequency, t);
    }
Member Data Documentation
Compounding QuantLib::PiecewiseZeroSpreadedTermStructure::comp_ [private]
Definition at line 73 of file piecewisezerospreadedtermstructure.hpp.
Referenced by zeroYieldImpl().
std::vector<Date> QuantLib::PiecewiseZeroSpreadedTermStructure::dates_ [private]
Definition at line 71 of file piecewisezerospreadedtermstructure.hpp.
Referenced by maxDate(), PiecewiseZeroSpreadedTermStructure(), and updateTimes().
DayCounter QuantLib::PiecewiseZeroSpreadedTermStructure::dc_ [private]
Definition at line 75 of file piecewisezerospreadedtermstructure.hpp.
Frequency QuantLib::PiecewiseZeroSpreadedTermStructure::freq_ [private]
Definition at line 74 of file piecewisezerospreadedtermstructure.hpp.
Referenced by zeroYieldImpl().
Handle<YieldTermStructure> QuantLib::PiecewiseZeroSpreadedTermStructure::originalCurve_ [private]
Definition at line 69 of file piecewisezerospreadedtermstructure.hpp.
Referenced by calendar(), dayCounter(), maxDate(), PiecewiseZeroSpreadedTermStructure(), referenceDate(), settlementDays(), and zeroYieldImpl().
std::vector<Handle<Quote> > QuantLib::PiecewiseZeroSpreadedTermStructure::spreads_ [private]
Definition at line 70 of file piecewisezerospreadedtermstructure.hpp.
Referenced by calcSpread(), and PiecewiseZeroSpreadedTermStructure().
std::vector<Time> QuantLib::PiecewiseZeroSpreadedTermStructure::times_ [private]
Definition at line 72 of file piecewisezerospreadedtermstructure.hpp.
Referenced by calcSpread(), and updateTimes().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/yield/piecewisezerospreadedtermstructure.hpp