QuantLib: QuantLib::FDBermudanEngine< Scheme > Class Template Reference
QuantLib::FDBermudanEngine< Scheme > Class Template Reference
Finite-differences Bermudan engine.
#include <fdbermudanengine.hpp>
Public Member Functions
FDBermudanEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > &process, Size timeSteps=100, Size gridPoints=100, bool timeDependent=false)
void calculate () const
Protected Member Functions
void initializeStepCondition () const
void executeIntermediateStep (Size) const
Protected Attributes
Real extraTermInBermudan
Detailed Description
template<template< class > class Scheme = CrankNicolson>
class QuantLib::FDBermudanEngine< Scheme >
Finite-differences Bermudan engine.
Definition at line 36 of file fdbermudanengine.hpp.
Constructor & Destructor Documentation
template<template< class > class Scheme = CrankNicolson> QuantLib::FDBermudanEngine< Scheme >::FDBermudanEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > & process, Size timeSteps = 100, Size gridPoints = 100, bool timeDependent = false) [inline]
Definition at line 40 of file fdbermudanengine.hpp.
        : FDMultiPeriodEngine<Scheme>(process, timeSteps,
                                      gridPoints, timeDependent) {}
Member Function Documentation
template<template< class > class Scheme = CrankNicolson> void QuantLib::FDBermudanEngine< Scheme >::calculate () const [inline]
Definition at line 47 of file fdbermudanengine.hpp.
References QuantLib::FDMultiPeriodEngine< Scheme >::setupArguments().
{
            this->setupArguments(&arguments_);
            FDMultiPeriodEngine<Scheme>::calculate(&results_);
        }
template<template< class > class Scheme = CrankNicolson> void QuantLib::FDBermudanEngine< Scheme >::executeIntermediateStep (Size) const [inline, protected, virtual]
Implements QuantLib::FDMultiPeriodEngine< Scheme >.
Definition at line 58 of file fdbermudanengine.hpp.
References QuantLib::FDVanillaEngine::intrinsicValues_, QuantLib::FDMultiPeriodEngine< Scheme >::prices_, QuantLib::SampledCurve::size(), and QuantLib::SampledCurve::value().
{
            Size size = this->intrinsicValues_.size();
            for (Size j=0; j<size; j++) {
                this->prices_.value(j) =
                    std::max(this->prices_.value(j),
                             this->intrinsicValues_.value(j));
            }
        }
template<template< class > class Scheme = CrankNicolson> void QuantLib::FDBermudanEngine< Scheme >::initializeStepCondition () const [inline, protected, virtual]
Reimplemented from QuantLib::FDMultiPeriodEngine< Scheme >.
Definition at line 53 of file fdbermudanengine.hpp.
References QuantLib::FDMultiPeriodEngine< Scheme >::stepCondition_.
{
            this->stepCondition_ =
                boost::shared_ptr<StandardStepCondition>(
                                                  new NullCondition<Array>());
        };
Member Data Documentation
template<template< class > class Scheme = CrankNicolson> Real QuantLib::FDBermudanEngine< Scheme >::extraTermInBermudan [protected]
Definition at line 52 of file fdbermudanengine.hpp.
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/vanilla/fdbermudanengine.hpp