QuantLib: QuantLib::SobolRsg Class Reference
QuantLib::SobolRsg Class Reference
Sobol low-discrepancy sequence generator.
#include <sobolrsg.hpp>
Public Types
enum DirectionIntegers {
Unit, Jaeckel, SobolLevitan, SobolLevitanLemieux,
JoeKuoD5, JoeKuoD6, JoeKuoD7, Kuo,
Kuo2, Kuo3
}
typedef Sample< std::vector
< Real > > sample_type
Public Member Functions
SobolRsg (Size dimensionality, unsigned long seed=0, DirectionIntegers directionIntegers=Jaeckel)
void skipTo (unsigned long n)
const std::vector< unsigned
long > & nextInt32Sequence () const
const SobolRsg::sample_type & nextSequence () const
const sample_type & lastSequence () const
Size dimension () const
Private Attributes
Size dimensionality_
unsigned long sequenceCounter_
bool firstDraw_
sample_type sequence_
std::vector< unsigned long > integerSequence_
std::vector< std::vector
< unsigned long > > directionIntegers_
Static Private Attributes
static const int bits_ = 8*sizeof(unsigned long)
static const double normalizationFactor_
Detailed Description
Sobol low-discrepancy sequence generator.
A Gray code counter and bitwise operations are used for very fast sequence generation.
The implementation relies on primitive polynomials modulo two from the book "Monte Carlo Methods in Finance" by Peter Jäckel.
21 200 primitive polynomials modulo two are provided in QuantLib. Jäckel has calculated 8 129 334 polynomials: if you need that many dimensions you can replace the primitivepolynomials.c file included in QuantLib with the one provided in the CD of the "Monte Carlo Methods in Finance" book.
The choice of initialization numbers (also know as free direction integers) is crucial for the homogeneity properties of the sequence. Sobol defines two homogeneity properties: Property A and Property A'.
The unit initialization numbers suggested in "Numerical Recipes in C", 2nd edition, by Press, Teukolsky, Vetterling, and Flannery (section 7.7) fail the test for Property A even for low dimensions.
Bratley and Fox published coefficients of the free direction integers up to dimension 40, crediting unpublished work of Sobol' and Levitan. See Bratley, P., Fox, B.L. (1988) "Algorithm 659: Implementing Sobol's quasirandom sequence generator," ACM Transactions on Mathematical Software 14:88-100. These values satisfy Property A for d<=20 and d = 23, 31, 33, 34, 37; Property A' holds for d<=6.
Jäckel provides in his book (section 8.3) initialization numbers up to dimension 32. Coefficients for d<=8 are the same as in Bradley-Fox, so Property A' holds for d<=6 but Property A holds for d<=32.
The implementation of Lemieux, Cieslak, and Luttmer includes coefficients of the free direction integers up to dimension 360. Coefficients for d<=40 are the same as in Bradley-Fox. For dimension 40<d<=360 the coefficients have been calculated as optimal values based on the "resolution" criterion. See "RandQMC user's guide - A package for randomized quasi-Monte Carlo methods in C," by C. Lemieux, M. Cieslak, and K. Luttmer, version January 13 2004, and references cited there (http://www.math.ucalgary.ca/~lemieux/randqmc.html). The values up to d<=360 has been provided to the QuantLib team by Christiane Lemieux, private communication, September 2004.
For more info on Sobol' sequences see also "Monte Carlo Methods in Financial Engineering," by P. Glasserman, 2004, Springer, section 5.2.3
The Joe--Kuo numbers and the Kuo numbers are due to Stephen Joe and Frances Kuo.
S. Joe and F. Y. Kuo, Constructing Sobol sequences with better two-dimensional projections, preprint Nov 22 2007
See http://web.maths.unsw.edu.au/~fkuo/sobol/ for more information.
Note that the Kuo numbers were generated to work with a different ordering of primitive polynomials for the first 40 or so dimensions which is why we have the Alternative Primitive Polynomials.
Test:
the correctness of the returned values is tested by reproducing known good values.
the correctness of the returned values is tested by checking their discrepancy against known good values.
Definition at line 106 of file sobolrsg.hpp.
Member Typedef Documentation
typedef Sample<std::vector<Real> > QuantLib::SobolRsg::sample_type
Definition at line 108 of file sobolrsg.hpp.
Member Enumeration Documentation
enum QuantLib::SobolRsg::DirectionIntegers
Enumerator:
Unit
Jaeckel
SobolLevitan
SobolLevitanLemieux
JoeKuoD5
JoeKuoD6
JoeKuoD7
Kuo
Kuo2
Kuo3
Definition at line 109 of file sobolrsg.hpp.
{
            Unit, Jaeckel, SobolLevitan, SobolLevitanLemieux,
            JoeKuoD5, JoeKuoD6, JoeKuoD7,
            Kuo, Kuo2, Kuo3 };
Constructor & Destructor Documentation
QuantLib::SobolRsg::SobolRsg (Size dimensionality, unsigned long seed = 0, DirectionIntegers directionIntegers = Jaeckel)
Precondition:
dimensionality must be <= PPMT_MAX_DIM
Definition at line 39718 of file sobolrsg.cpp.
References QuantLib::anonymous_namespace{sobolrsg.cpp}::AltPrimitivePolynomials, bits_, dimensionality_, directionIntegers_, QuantLib::anonymous_namespace{sobolrsg.cpp}::initializers, integerSequence_, Jaeckel, JoeKuoD5, QuantLib::anonymous_namespace{sobolrsg.cpp}::JoeKuoD5initializers, JoeKuoD6, QuantLib::anonymous_namespace{sobolrsg.cpp}::JoeKuoD6initializers, JoeKuoD7, QuantLib::anonymous_namespace{sobolrsg.cpp}::JoeKuoD7initializers, Kuo, Kuo2, QuantLib::anonymous_namespace{sobolrsg.cpp}::Kuo2initializers, Kuo3, QuantLib::anonymous_namespace{sobolrsg.cpp}::Kuo3initializers, QuantLib::anonymous_namespace{sobolrsg.cpp}::Kuoinitializers, QuantLib::anonymous_namespace{sobolrsg.cpp}::Linitializers, QuantLib::anonymous_namespace{sobolrsg.cpp}::maxAltDegree, QuantLib::MersenneTwisterUniformRng::next(), PPMT_MAX_DIM, PrimitivePolynomials, QL_REQUIRE, QuantLib::anonymous_namespace{sobolrsg.cpp}::SLinitializers, SobolLevitan, SobolLevitanLemieux, Unit, and QuantLib::Sample< T >::value.
    : dimensionality_(dimensionality), sequenceCounter_(0), firstDraw_(true),
      sequence_(std::vector<Real> (dimensionality), 1.0),
      integerSequence_(dimensionality, 0),
      directionIntegers_(dimensionality,std::vector<unsigned long>(bits_)) {
        QL_REQUIRE(dimensionality>0,
                   "dimensionality must be greater than 0");
      QL_REQUIRE(dimensionality<=PPMT_MAX_DIM,
               "dimensionality " << dimensionality
                   << " exceeds the number of available "
                   << "primitive polynomials modulo two ("
                   << PPMT_MAX_DIM << ")");
        // initializes coefficient array of the k-th primitive polynomial
        // and degree of the k-th primitive polynomial
        std::vector<unsigned int> degree(dimensionality_);
        std::vector<long> ppmt(dimensionality_);
        bool useAltPolynomials = false;
        if (directionIntegers == Kuo || directionIntegers == Kuo2 || directionIntegers == Kuo3
            || directionIntegers == SobolLevitan || directionIntegers == SobolLevitanLemieux)
            useAltPolynomials = true;
        // degree 0 is not used
        ppmt[0]=0;
        degree[0]=0;
        Size k, index;
        unsigned int currentDegree=1;
        k=1;
        index=0;
        unsigned int altDegree = useAltPolynomials ? maxAltDegree : 0;
        for (; k<std::min<Size>(dimensionality_,altDegree); k++,index++)
        {
            ppmt[k] = AltPrimitivePolynomials[currentDegree-1][index];
            if (ppmt[k]==-1)
            {
                ++currentDegree;
                index=0;
                ppmt[k] = AltPrimitivePolynomials[currentDegree-1][index];
            }
            degree[k] = currentDegree;
        }
        for (; k<dimensionality_; k++,index++)
        {
            ppmt[k] = PrimitivePolynomials[currentDegree-1][index];
            if (ppmt[k]==-1)
            {
                ++currentDegree;
                index=0;
                ppmt[k] = PrimitivePolynomials[currentDegree-1][index];
            }
            degree[k] = currentDegree;
        }
        // initializes bits_ direction integers for each dimension
        // and store them into directionIntegers_[dimensionality_][bits_]
        //
        // In each dimension k with its associated primitive polynomial,
        // the first degree_[k] direction integers can be chosen freely
        // provided that only the l leftmost bits can be non-zero, and
        // that the l-th leftmost bit must be set
        // degenerate (no free direction integers) first dimension
        int j;
        for (j=0; j<bits_; j++)
            directionIntegers_[0][j] = (1UL<<(bits_-j-1));
        Size maxTabulated = 0;
        // dimensions from 2 (k=1) to maxTabulated (k=maxTabulated-1) included
        // are initialized from tabulated coefficients
        switch (directionIntegers) {
            case Unit:
                maxTabulated=dimensionality_;
                for (k=1; k<maxTabulated; k++) {
                    for (Size l=1; l<=degree[k]; l++) {
                        directionIntegers_[k][l-1] = 1UL;
                        directionIntegers_[k][l-1] <<= (bits_-l);
                    }
                }
                break;
            case Jaeckel:
                // maxTabulated=32
                maxTabulated = sizeof(initializers)/sizeof(unsigned long *)+1;
                for (k=1; k<std::min(dimensionality_, maxTabulated); k++) {
                    j = 0;
                    // 0UL marks coefficients' end for a given dimension
                    while (initializers[k-1][j] != 0UL) {
                        directionIntegers_[k][j] = initializers[k-1][j];
                        directionIntegers_[k][j] <<= (bits_-j-1);
                        j++;
                    }
                }
                break;
            case SobolLevitan:
                // maxTabulated=40
                maxTabulated = sizeof(SLinitializers)/sizeof(unsigned long *)+1;
                for (k=1; k<std::min(dimensionality_, maxTabulated); k++) {
                    j = 0;
                    // 0UL marks coefficients' end for a given dimension
                    while (SLinitializers[k-1][j] != 0UL) {
                        directionIntegers_[k][j] = SLinitializers[k-1][j];
                        directionIntegers_[k][j] <<= (bits_-j-1);
                        j++;
                    }
                }
                break;
            case SobolLevitanLemieux:
                // maxTabulated=360
                maxTabulated = sizeof(Linitializers)/sizeof(unsigned long *)+1;
                for (k=1; k<std::min(dimensionality_, maxTabulated); k++) {
                    j = 0;
                    // 0UL marks coefficients' end for a given dimension
                    while (Linitializers[k-1][j] != 0UL) {
                        directionIntegers_[k][j] = Linitializers[k-1][j];
                        directionIntegers_[k][j] <<= (bits_-j-1);
                        j++;
                    }
                }
                break;
            case JoeKuoD5:
                // maxTabulated=1898
                maxTabulated = sizeof(JoeKuoD5initializers)/sizeof(unsigned long *)+1;
                for (k=1; k<std::min(dimensionality_, maxTabulated); k++) {
                    j = 0;
                    // 0UL marks coefficients' end for a given dimension
                    while (JoeKuoD5initializers[k-1][j] != 0UL) {
                        directionIntegers_[k][j] = JoeKuoD5initializers[k-1][j];
                        directionIntegers_[k][j] <<= (bits_-j-1);
                        j++;
                    }
                }
                break;
            case JoeKuoD6:
                // maxTabulated=1799
                maxTabulated = sizeof(JoeKuoD6initializers)/sizeof(unsigned long *)+1;
                for (k=1; k<std::min(dimensionality_, maxTabulated); k++) {
                    j = 0;
                    // 0UL marks coefficients' end for a given dimension
                    while (JoeKuoD6initializers[k-1][j] != 0UL) {
                        directionIntegers_[k][j] = JoeKuoD6initializers[k-1][j];
                        directionIntegers_[k][j] <<= (bits_-j-1);
                        j++;
                    }
                }
                break;
            case JoeKuoD7:
                // maxTabulated=1898
                maxTabulated = sizeof(JoeKuoD7initializers)/sizeof(unsigned long *)+1;
                for (k=1; k<std::min(dimensionality_, maxTabulated); k++) {
                    j = 0;
                    // 0UL marks coefficients' end for a given dimension
                    while (JoeKuoD7initializers[k-1][j] != 0UL) {
                        directionIntegers_[k][j] = JoeKuoD7initializers[k-1][j];
                        directionIntegers_[k][j] <<= (bits_-j-1);
                        j++;
                    }
                }
                break;
            case Kuo:
                // maxTabulated=4925
                maxTabulated = sizeof(Kuoinitializers)/sizeof(unsigned long *)+1;
                for (k=1; k<std::min(dimensionality_, maxTabulated); k++) {
                    j = 0;
                    // 0UL marks coefficients' end for a given dimension
                    while (Kuoinitializers[k-1][j] != 0UL) {
                        directionIntegers_[k][j] = Kuoinitializers[k-1][j];
                        directionIntegers_[k][j] <<= (bits_-j-1);
                        j++;
                    }
                }
                break;
            case Kuo2:
                // maxTabulated=3946
                maxTabulated = sizeof(Kuo2initializers)/sizeof(unsigned long *)+1;
                for (k=1; k<std::min(dimensionality_, maxTabulated); k++) {
                    j = 0;
                    // 0UL marks coefficients' end for a given dimension
                    while (Kuo2initializers[k-1][j] != 0UL) {
                        directionIntegers_[k][j] = Kuo2initializers[k-1][j];
                        directionIntegers_[k][j] <<= (bits_-j-1);
                        j++;
                    }
                }
                break;
            case Kuo3:
                // maxTabulated=4585
                maxTabulated = sizeof(Kuo3initializers)/sizeof(unsigned long *)+1;
                for (k=1; k<std::min(dimensionality_, maxTabulated); k++) {
                    j = 0;
                    // 0UL marks coefficients' end for a given dimension
                    while (Kuo3initializers[k-1][j] != 0UL) {
                        directionIntegers_[k][j] = Kuo3initializers[k-1][j];
                        directionIntegers_[k][j] <<= (bits_-j-1);
                        j++;
                    }
                }
                break;
            default:
                break;
        }
        // random initialization for higher dimensions
        if (dimensionality_>maxTabulated) {
            MersenneTwisterUniformRng uniformRng(seed);
            for (k=maxTabulated; k<dimensionality_; k++) {
                for (Size l=1; l<=degree[k]; l++) {
                    do {
                        // u is in (0,1)
                        Real u = uniformRng.next().value;
                        // the direction integer has at most the
                        // rightmost l bits non-zero
                        directionIntegers_[k][l-1] =
                            (unsigned long)(u*(1UL<<l));
                    } while (!(directionIntegers_[k][l-1] & 1UL));
                    // iterate until the direction integer is odd
                    // that is it has the rightmost bit set
                    // shifting bits_-l bits to the left
                    // we are guaranteed that the l-th leftmost bit
                    // is set, and only the first l leftmost bit
                    // can be non-zero
                    directionIntegers_[k][l-1] <<= (bits_-l);
                }
            }
        }
        // computation of directionIntegers_[k][l] for l>=degree_[k]
        // by recurrence relation
        for (k=1; k<dimensionality_; k++) {
            unsigned int gk = degree[k];
            for (int l=gk; l<bits_; l++) {
                // eq. 8.19 "Monte Carlo Methods in Finance" by P. Jäckel
                unsigned long n = (directionIntegers_[k][l-gk]>>gk);
                // a[k][j] are the coefficients of the monomials in ppmt[k]
                // The highest order coefficient a[k][0] is not actually
                // used in the recurrence relation, and the lowest order
                // coefficient a[k][gk] is always set: this is the reason
                // why the highest and lowest coefficient of
                // the polynomial ppmt[k] are not included in its encoding,
                // provided that its degree is known.
                // That is: a[k][j] = ppmt[k] >> (gk-j-1)
                for (Size j=1; j<gk; j++) {
                    // XORed with a selection of (unshifted) direction
                    // integers controlled by which of the a[k][j] are set
                    if ((ppmt[k] >> (gk-j-1)) & 1UL)
                        n ^= directionIntegers_[k][l-j];
                }
                // a[k][gk] is always set, so directionIntegers_[k][l-gk]
                // will always enter
                n ^= directionIntegers_[k][l-gk];
                directionIntegers_[k][l]=n;
            }
        }
        // in case one needs to check the directionIntegers used
        /* bool printDirectionIntegers = false;
           if (printDirectionIntegers) {
               std::ofstream outStream("directionIntegers.txt");
               for (k=0; k<std::min(32UL,dimensionality_); k++) {
                   outStream << std::endl << k+1       << "\t"
                                          << degree[k] << "\t"
                                          << ppmt[k]   << "\t";
                   for (j=0; j<10; j++) {
                       outStream << io::power_of_two(
                           directionIntegers_[k][j]) << "\t";
                   }
               }
               outStream.close();
           }
        */
        // initialize the Sobol integer/double vectors
        // first draw
        for (k=0; k<dimensionality_; k++) {
            integerSequence_[k]=directionIntegers_[k][0];
        }
    }
Member Function Documentation
Size QuantLib::SobolRsg::dimension () const [inline]
Definition at line 128 of file sobolrsg.hpp.
References dimensionality_.
{ return dimensionality_; }
const sample_type& QuantLib::SobolRsg::lastSequence () const [inline]
Definition at line 127 of file sobolrsg.hpp.
References sequence_.
{ return sequence_; }
const std::vector< unsigned long > & QuantLib::SobolRsg::nextInt32Sequence () const
Definition at line 40032 of file sobolrsg.cpp.
References dimensionality_, directionIntegers_, firstDraw_, integerSequence_, QL_REQUIRE, and sequenceCounter_.
Referenced by nextSequence(), and LowDiscrepancyTest::testSobolSkipping().
    {
        if (firstDraw_) {
            // it was precomputed in the constructor
            firstDraw_ = false;
            return integerSequence_;
        }
        // increment the counter
        sequenceCounter_++;
        // did we overflow?
     QL_REQUIRE(sequenceCounter_ != 0, "period exceeded");
        // instead of using the counter n as new unique generating integer
        // for the n-th draw use the Gray code G(n) as proposed
        // by Antonov and Saleev
        unsigned long n = sequenceCounter_;
        // Find rightmost zero bit of n
        int j = 0;
        while (n & 1) { n >>= 1; j++; }
        for (Size k=0; k<dimensionality_; k++) {
            // XOR the appropriate direction number into each component of
            // the integer sequence to obtain a new Sobol integer for that
            // component
            integerSequence_[k] ^= directionIntegers_[k][j];
        }
        return integerSequence_;
    }
const SobolRsg::sample_type& QuantLib::SobolRsg::nextSequence () const [inline]
Definition at line 120 of file sobolrsg.hpp.
References dimensionality_, nextInt32Sequence(), normalizationFactor_, sequence_, anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Sample< T >::value.
Referenced by InterpolationTest::testMultiSpline(), RiskStatisticsTest::testResults(), and LowDiscrepancyTest::testSobol().
{
            const std::vector<unsigned long>& v = nextInt32Sequence();
            // normalize to get a double in (0,1)
            for (Size k=0; k<dimensionality_; ++k)
                sequence_.value[k] = v[k] * normalizationFactor_;
            return sequence_;
        }
void QuantLib::SobolRsg::skipTo (unsigned long n)
skip to the n-th sample in the low-discrepancy sequence
Definition at line 40013 of file sobolrsg.cpp.
References dimensionality_, directionIntegers_, integerSequence_, M_LN2, anonymous_namespace{matrices.cpp}::N, and sequenceCounter_.
Referenced by LowDiscrepancyTest::testSobolSkipping().
{
        unsigned long N = skip+1;
        unsigned int ops = (unsigned int)(std::log((double)N)/M_LN2)+1;
        // Convert to Gray code
        unsigned long G = N ^ (N>>1);
        for (Size k=0; k<dimensionality_; k++) {
            integerSequence_[k] = 0;
            for (Size index=0; index<ops; index++) {
                if (G>>index & 1)
                    integerSequence_[k] ^= directionIntegers_[k][index];
            }
        }
        sequenceCounter_ = skip;
    }
Member Data Documentation
const int QuantLib::SobolRsg::bits_ = 8*sizeof(unsigned long) [static, private]
Definition at line 130 of file sobolrsg.hpp.
Referenced by SobolRsg().
Size QuantLib::SobolRsg::dimensionality_ [private]
Definition at line 132 of file sobolrsg.hpp.
Referenced by dimension(), nextInt32Sequence(), nextSequence(), skipTo(), and SobolRsg().
std::vector<std::vector<unsigned long> > QuantLib::SobolRsg::directionIntegers_ [private]
Definition at line 137 of file sobolrsg.hpp.
Referenced by nextInt32Sequence(), skipTo(), and SobolRsg().
bool QuantLib::SobolRsg::firstDraw_ [mutable, private]
Definition at line 134 of file sobolrsg.hpp.
Referenced by nextInt32Sequence().
std::vector<unsigned long> QuantLib::SobolRsg::integerSequence_ [mutable, private]
Definition at line 136 of file sobolrsg.hpp.
Referenced by nextInt32Sequence(), skipTo(), and SobolRsg().
const double QuantLib::SobolRsg::normalizationFactor_ [static, private]
Initial value:
        0.5/(1UL<<(SobolRsg::bits_-1))
Definition at line 131 of file sobolrsg.hpp.
Referenced by nextSequence().
sample_type QuantLib::SobolRsg::sequence_ [mutable, private]
Definition at line 135 of file sobolrsg.hpp.
Referenced by lastSequence(), and nextSequence().
unsigned long QuantLib::SobolRsg::sequenceCounter_ [mutable, private]
Definition at line 133 of file sobolrsg.hpp.
Referenced by nextInt32Sequence(), and skipTo().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/randomnumbers/sobolrsg.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/math/randomnumbers/sobolrsg.cpp