QuantLib: VarianceGammaTest Class Reference
VarianceGammaTest Class Reference
#include <variancegamma.hpp>
Static Public Member Functions
static void testVarianceGamma ()
static
boost::unit_test_framework::test_suite * suite ()
Detailed Description
Definition at line 28 of file variancegamma.hpp.
Member Function Documentation
test_suite * VarianceGammaTest::suite () [static]
Definition at line 209 of file variancegamma.cpp.
References QUANTLIB_TEST_CASE, and testVarianceGamma().
Referenced by init_unit_test_suite().
{
    test_suite* suite = BOOST_TEST_SUITE("Variance Gamma tests");
    suite->add(QUANTLIB_TEST_CASE(&VarianceGammaTest::testVarianceGamma));
    return suite;
}
void VarianceGammaTest::testVarianceGamma () [static]
Definition at line 74 of file variancegamma.cpp.
References QuantLib::Option::Call, QuantLib::flatRate(), LENGTH, QuantLib::Option::Put, REPORT_FAILURE, QuantLib::Instrument::setPricingEngine(), anonymous_namespace{distributions.cpp}::sigma, anonymous_namespace{quantlibbenchmark.cpp}::t, and anonymous_namespace{marketmodel.cpp}::todaysDate.
Referenced by suite().
{
    BOOST_MESSAGE("Testing Variance Gamma model "
        "for European options...");
    SavedSettings backup;
    VarianceGammaProcessData processes[] = {
    //    spot,    q,    r,sigma,   nu, theta
        { 6000, 0.00, 0.05, 0.20, 0.05, -0.50 },
        { 6000, 0.02, 0.05, 0.15, 0.01, -0.50 }
    };
    VarianceGammaOptionData options[] = {
    //            type,strike,  t
        { Option::Call, 5550, 1.0},
        { Option::Call, 5600, 1.0},
        { Option::Call, 5650, 1.0},
        { Option::Call, 5700, 1.0},
        { Option::Call, 5750, 1.0},
        { Option::Call, 5800, 1.0},
        { Option::Call, 5850, 1.0},
        { Option::Call, 5900, 1.0},
        { Option::Call, 5950, 1.0},
        { Option::Call, 6000, 1.0},
        { Option::Call, 6050, 1.0},
        { Option::Call, 6100, 1.0},
        { Option::Call, 6150, 1.0},
        { Option::Call, 6200, 1.0},
        { Option::Call, 6250, 1.0},
        { Option::Call, 6300, 1.0},
        { Option::Call, 6350, 1.0},
        { Option::Call, 6400, 1.0},
        { Option::Call, 6450, 1.0},
        { Option::Call, 6500, 1.0},
        { Option::Call, 6550, 1.0},
        { Option::Put,  5550, 1.0}
    };
    Real results[LENGTH(processes)][LENGTH(options)] = {
        {
            955.1637, 922.7529, 890.9872, 859.8739, 829.4197, 799.6303, 770.5104, 742.0640,
            714.2943, 687.2032, 660.7921, 635.0613, 610.0103, 585.6379, 561.9416, 538.9186,
            516.5649, 494.8760, 473.8464, 453.4700, 433.7400, 234.4870
        },
        {
            732.8705, 698.5542, 665.1404, 632.6498, 601.1002, 570.5068, 540.8824, 512.2367,
            484.5766, 457.9064, 432.2273, 407.5381, 383.8346, 361.1102, 339.3559, 318.5599,
            298.7087, 279.7864, 261.7751, 244.6552, 228.4057, 130.9974
        }
    };
    Real tol = 0.01;
    DayCounter dc = Actual360();
    Date today = Date::todaysDate();
    for (Size i=0; i<LENGTH(processes); i++) {
        boost::shared_ptr<SimpleQuote> spot(new SimpleQuote(processes[i].s));
        boost::shared_ptr<SimpleQuote> qRate(new SimpleQuote(processes[i].q));
        boost::shared_ptr<YieldTermStructure> qTS = flatRate(today, qRate, dc);
        boost::shared_ptr<SimpleQuote> rRate(new SimpleQuote(processes[i].r));
        boost::shared_ptr<YieldTermStructure> rTS = flatRate(today, rRate, dc);
        boost::shared_ptr<VarianceGammaProcess> stochProcess(
            new VarianceGammaProcess(Handle<Quote>(spot),
            Handle<YieldTermStructure>(qTS),
            Handle<YieldTermStructure>(rTS),
            processes[i].sigma,
            processes[i].nu,
            processes[i].theta));
        // Analytic engine
        boost::shared_ptr<PricingEngine> analyticEngine(
            new VarianceGammaEngine(stochProcess));
        // FFT engine
        boost::shared_ptr<FFTVarianceGammaEngine> fftEngine(
            new FFTVarianceGammaEngine(stochProcess));
        // which requires a list of options
        std::vector<boost::shared_ptr<Instrument> > optionList;
        std::vector<boost::shared_ptr<StrikedTypePayoff> > payoffs;
        for (Size j=0; j<LENGTH(options); j++)
        {
            Date exDate = today + Integer(options[j].t*360+0.5);
            boost::shared_ptr<Exercise> exercise(new EuropeanExercise(exDate));
            boost::shared_ptr<StrikedTypePayoff> payoff(new
                PlainVanillaPayoff(options[j].type, options[j].strike));
            payoffs.push_back(payoff);
            // Test analytic engine
            boost::shared_ptr<EuropeanOption> option(new EuropeanOption(payoff, exercise));
            option->setPricingEngine(analyticEngine);
            Real calculated = option->NPV();
            Real expected = results[i][j];
            Real error = std::fabs(calculated-expected);
            if (error>tol) {
                REPORT_FAILURE("analytic value", payoff, exercise,
                    processes[i].s, processes[i].q, processes[i].r,
                    today, processes[i].sigma, processes[i].nu,
                    processes[i].theta, expected, calculated,
                    error, tol);
            }
            optionList.push_back(option);
        }
        // Test FFT engine
        // FFT engine is extremely efficient when sent a list of options to calculate first
        fftEngine->precalculate(optionList);
        for (Size j=0; j<LENGTH(options); j++)
        {
            boost::shared_ptr<VanillaOption> option = boost::static_pointer_cast<VanillaOption>(optionList[j]);
            option->setPricingEngine(fftEngine);
            Real calculated = option->NPV();
            Real expected = results[i][j];
            Real error = std::fabs(calculated-expected);
            if (error>tol) {
                boost::shared_ptr<StrikedTypePayoff> payoff =
                    boost::dynamic_pointer_cast<StrikedTypePayoff>(option->payoff());
                REPORT_FAILURE("fft value", payoff, option->exercise(),
                    processes[i].s, processes[i].q, processes[i].r,
                    today, processes[i].sigma, processes[i].nu,
                    processes[i].theta, expected, calculated,
                    error, tol);
            }
        }
    }
}
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/variancegamma.hpp
/home/deriversatile/QuantLib/QuantLibQt/test-suite/variancegamma.cpp