QuantLib: QuantLib::StrippedOptionlet Class Reference
QuantLib::StrippedOptionlet Class Reference
#include <strippedoptionlet.hpp>
Public Member Functions
StrippedOptionlet (Natural settlementDays, const Calendar &calendar, BusinessDayConvention bdc, const boost::shared_ptr< IborIndex > &iborIndex, const std::vector< Date > &optionletDates, const std::vector< Rate > &strikes, const std::vector< std::vector< Handle< Quote > > > &, const DayCounter &dc)
StrippedOptionletBase interface
const std::vector< Rate > & optionletStrikes (Size i) const
const std::vector< Volatility > & optionletVolatilities (Size i) const
const std::vector< Date > & optionletFixingDates () const
const std::vector< Time > & optionletFixingTimes () const
Size optionletMaturities () const
const std::vector< Rate > & atmOptionletRates () const
DayCounter dayCounter () const
Calendar calendar () const
Natural settlementDays () const
BusinessDayConvention businessDayConvention () const
Private Member Functions
void checkInputs () const
void registerWithMarketData ()
void performCalculations () const
Private Attributes
Calendar calendar_
Natural settlementDays_
BusinessDayConvention businessDayConvention_
DayCounter dc_
boost::shared_ptr< IborIndex > iborIndex_
Size nOptionletDates_
std::vector< Date > optionletDates_
std::vector< Time > optionletTimes_
std::vector< Rate > optionletAtmRates_
std::vector< std::vector< Rate > > optionletStrikes_
Size nStrikes_
std::vector< std::vector
< Handle< Quote > > > optionletVolQuotes_
std::vector< std::vector
< Volatility > > optionletVolatilities_
Detailed Description
Helper class to wrap in a StrippedOptionletBase object a matrix of exogenously calculated optionlet (i.e. caplet/floorlet) volatilities (a.k.a. forward-forward volatilities).
Definition at line 37 of file strippedoptionlet.hpp.
Constructor & Destructor Documentation
QuantLib::StrippedOptionlet::StrippedOptionlet (Natural settlementDays, const Calendar & calendar, BusinessDayConvention bdc, const boost::shared_ptr< IborIndex > & iborIndex, const std::vector< Date > & optionletDates, const std::vector< Rate > & strikes, const std::vector< std::vector< Handle< Quote > > > & v, const DayCounter & dc)
Definition at line 30 of file strippedoptionlet.cpp.
References QuantLib::Calendar::advance(), checkInputs(), QuantLib::Days, dc_, QuantLib::Singleton< Settings >::instance(), nOptionletDates_, optionletDates_, optionletTimes_, QuantLib::Observer::registerWith(), registerWithMarketData(), and QuantLib::DayCounter::yearFraction().
    : calendar_(calendar),
      settlementDays_(settlementDays),
      businessDayConvention_(bdc),
      dc_(dc),
      iborIndex_(iborIndex),
      nOptionletDates_(optionletDates.size()),
      optionletDates_(optionletDates),
      optionletTimes_(nOptionletDates_),
      optionletAtmRates_(nOptionletDates_),
      optionletStrikes_(nOptionletDates_, strikes),
      nStrikes_(strikes.size()),
      optionletVolQuotes_(v),
      optionletVolatilities_(nOptionletDates_, vector<Volatility>(nStrikes_))
    {
        checkInputs();
        registerWith(Settings::instance().evaluationDate());
        registerWithMarketData();
        Date refDate = calendar.advance(Settings::instance().evaluationDate(),
                                        settlementDays, Days);
        for (Size i=0; i<nOptionletDates_; ++i)
            optionletTimes_[i] = dc_.yearFraction(refDate, optionletDates_[i]);
    }
Member Function Documentation
const vector< Time > & QuantLib::StrippedOptionlet::atmOptionletRates () const [virtual]
Implements QuantLib::StrippedOptionletBase.
Definition at line 135 of file strippedoptionlet.cpp.
References QuantLib::LazyObject::calculate(), iborIndex_, nOptionletDates_, optionletAtmRates_, and optionletDates_.
{
        calculate();
        for (Size i=0; i<nOptionletDates_; ++i)
            optionletAtmRates_[i] = iborIndex_->fixing(optionletDates_[i], true);
        return optionletAtmRates_;
    }
BusinessDayConvention QuantLib::StrippedOptionlet::businessDayConvention () const [virtual]
Implements QuantLib::StrippedOptionletBase.
Definition at line 154 of file strippedoptionlet.cpp.
References businessDayConvention_.
{
        return businessDayConvention_;
    }
Calendar QuantLib::StrippedOptionlet::calendar () const [virtual]
Implements QuantLib::StrippedOptionletBase.
Definition at line 146 of file strippedoptionlet.cpp.
References calendar_.
{
        return calendar_;
    }
void QuantLib::StrippedOptionlet::checkInputs () const [private]
Definition at line 65 of file strippedoptionlet.cpp.
References QuantLib::Singleton< Settings >::instance(), nOptionletDates_, nStrikes_, optionletDates_, optionletStrikes_, optionletVolQuotes_, QuantLib::io::ordinal(), QL_REQUIRE, and QuantLib::io::rate().
Referenced by StrippedOptionlet().
{
        QL_REQUIRE(!optionletDates_.empty(), "empty optionlet tenor vector");
        QL_REQUIRE(nOptionletDates_==optionletVolQuotes_.size(),
                   "mismatch between number of option tenors (" <<
                   nOptionletDates_ << ") and number of volatility rows (" <<
                   optionletVolQuotes_.size() << ")");
        QL_REQUIRE(optionletDates_[0]>Settings::instance().evaluationDate(),
                   "first option date (" << optionletDates_[0] << ") is in the past");
        for (Size i=1; i<nOptionletDates_; ++i)
            QL_REQUIRE(optionletDates_[i]>optionletDates_[i-1],
                       "non increasing option dates: " << io::ordinal(i) <<
                       " is " << optionletDates_[i-1] << ", " <<
                       io::ordinal(i+1) << " is " << optionletDates_[i]);
        QL_REQUIRE(nStrikes_==optionletVolQuotes_[0].size(),
                   "mismatch between strikes(" << optionletStrikes_[0].size() <<
                   ") and vol columns (" << optionletVolQuotes_[0].size() << ")");
        for (Size j=1; j<nStrikes_; ++j)
            QL_REQUIRE(optionletStrikes_[0][j-1]<optionletStrikes_[0][j],
                       "non increasing strikes: " << io::ordinal(j) <<
                       " is " << io::rate(optionletStrikes_[0][j-1]) << ", " <<
                       io::ordinal(j+1) << " is " << io::rate(optionletStrikes_[0][j]));
    }
DayCounter QuantLib::StrippedOptionlet::dayCounter () const [virtual]
Implements QuantLib::StrippedOptionletBase.
Definition at line 142 of file strippedoptionlet.cpp.
References dc_.
{
        return dc_;
    }
const vector< Date > & QuantLib::StrippedOptionlet::optionletFixingDates () const [virtual]
Implements QuantLib::StrippedOptionletBase.
Definition at line 121 of file strippedoptionlet.cpp.
References QuantLib::LazyObject::calculate(), and optionletDates_.
{
        calculate();
        return optionletDates_;
    }
const vector< Time > & QuantLib::StrippedOptionlet::optionletFixingTimes () const [virtual]
Implements QuantLib::StrippedOptionletBase.
Definition at line 126 of file strippedoptionlet.cpp.
References QuantLib::LazyObject::calculate(), and optionletTimes_.
{
        calculate();
        return optionletTimes_;
    }
Size QuantLib::StrippedOptionlet::optionletMaturities () const [virtual]
Implements QuantLib::StrippedOptionletBase.
Definition at line 131 of file strippedoptionlet.cpp.
References nOptionletDates_.
{
        return nOptionletDates_;
    }
const vector< Rate > & QuantLib::StrippedOptionlet::optionletStrikes (Size i) const [virtual]
Implements QuantLib::StrippedOptionletBase.
Definition at line 103 of file strippedoptionlet.cpp.
References optionletStrikes_, and QL_REQUIRE.
{
        QL_REQUIRE(i<optionletStrikes_.size(),
                   "index (" << i <<
                   ") must be less than optionletStrikes size (" <<
                   optionletStrikes_.size() << ")");
        return optionletStrikes_[i];
    }
const vector< Volatility > & QuantLib::StrippedOptionlet::optionletVolatilities (Size i) const [virtual]
Implements QuantLib::StrippedOptionletBase.
Definition at line 112 of file strippedoptionlet.cpp.
References QuantLib::LazyObject::calculate(), optionletVolatilities_, and QL_REQUIRE.
{
        calculate();
        QL_REQUIRE(i<optionletVolatilities_.size(),
                   "index (" << i <<
                   ") must be less than optionletVolatilities size (" <<
                   optionletVolatilities_.size() << ")");
        return optionletVolatilities_[i];
    }
void QuantLib::StrippedOptionlet::performCalculations () const [private, virtual]
This method must implement any calculations which must be (re)done in order to calculate the desired results.
Implements QuantLib::LazyObject.
Definition at line 97 of file strippedoptionlet.cpp.
References nOptionletDates_, nStrikes_, optionletVolatilities_, and optionletVolQuotes_.
{
        for (Size i=0; i<nOptionletDates_; ++i)
          for (Size j=0; j<nStrikes_; ++j)
            optionletVolatilities_[i][j] = optionletVolQuotes_[i][j]->value();
    }
void QuantLib::StrippedOptionlet::registerWithMarketData () [private]
Definition at line 90 of file strippedoptionlet.cpp.
References nOptionletDates_, nStrikes_, optionletVolQuotes_, and QuantLib::Observer::registerWith().
Referenced by StrippedOptionlet().
    {
        for (Size i=0; i<nOptionletDates_; ++i)
            for (Size j=0; j<nStrikes_; ++j)
                registerWith(optionletVolQuotes_[i][j]);
    }
Natural QuantLib::StrippedOptionlet::settlementDays () const [virtual]
Implements QuantLib::StrippedOptionletBase.
Definition at line 150 of file strippedoptionlet.cpp.
References settlementDays_.
{
        return settlementDays_;
    }
Member Data Documentation
BusinessDayConvention QuantLib::StrippedOptionlet::businessDayConvention_ [private]
Definition at line 70 of file strippedoptionlet.hpp.
Referenced by businessDayConvention().
Calendar QuantLib::StrippedOptionlet::calendar_ [private]
Definition at line 68 of file strippedoptionlet.hpp.
Referenced by calendar().
DayCounter QuantLib::StrippedOptionlet::dc_ [private]
Definition at line 71 of file strippedoptionlet.hpp.
Referenced by dayCounter(), and StrippedOptionlet().
boost::shared_ptr<IborIndex> QuantLib::StrippedOptionlet::iborIndex_ [private]
Definition at line 72 of file strippedoptionlet.hpp.
Referenced by atmOptionletRates().
Size QuantLib::StrippedOptionlet::nOptionletDates_ [private]
Definition at line 74 of file strippedoptionlet.hpp.
Referenced by atmOptionletRates(), checkInputs(), optionletMaturities(), performCalculations(), registerWithMarketData(), and StrippedOptionlet().
Size QuantLib::StrippedOptionlet::nStrikes_ [private]
Definition at line 79 of file strippedoptionlet.hpp.
Referenced by checkInputs(), performCalculations(), and registerWithMarketData().
std::vector<Rate> QuantLib::StrippedOptionlet::optionletAtmRates_ [mutable, private]
Definition at line 77 of file strippedoptionlet.hpp.
Referenced by atmOptionletRates().
std::vector<Date> QuantLib::StrippedOptionlet::optionletDates_ [private]
Definition at line 75 of file strippedoptionlet.hpp.
Referenced by atmOptionletRates(), checkInputs(), optionletFixingDates(), and StrippedOptionlet().
std::vector<std::vector<Rate> > QuantLib::StrippedOptionlet::optionletStrikes_ [private]
Definition at line 78 of file strippedoptionlet.hpp.
Referenced by checkInputs(), and optionletStrikes().
std::vector<Time> QuantLib::StrippedOptionlet::optionletTimes_ [private]
Definition at line 76 of file strippedoptionlet.hpp.
Referenced by optionletFixingTimes(), and StrippedOptionlet().
std::vector<std::vector<Volatility> > QuantLib::StrippedOptionlet::optionletVolatilities_ [mutable, private]
Definition at line 82 of file strippedoptionlet.hpp.
Referenced by optionletVolatilities(), and performCalculations().
std::vector<std::vector<Handle<Quote> > > QuantLib::StrippedOptionlet::optionletVolQuotes_ [private]
Definition at line 81 of file strippedoptionlet.hpp.
Referenced by checkInputs(), performCalculations(), and registerWithMarketData().
Natural QuantLib::StrippedOptionlet::settlementDays_ [private]
Definition at line 69 of file strippedoptionlet.hpp.
Referenced by settlementDays().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/optionlet/strippedoptionlet.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/optionlet/strippedoptionlet.cpp