QuantLib: QuantLib::AnalyticHestonHullWhiteEngine Class Reference
QuantLib::AnalyticHestonHullWhiteEngine Class Reference
Analytic Heston engine incl. stochastic interest rates.
#include <analytichestonhullwhiteengine.hpp>
Public Member Functions
AnalyticHestonHullWhiteEngine (const boost::shared_ptr< HestonModel > &hestonModel, const boost::shared_ptr< HullWhite > &hullWhiteModel, Size integrationOrder=144)
AnalyticHestonHullWhiteEngine (const boost::shared_ptr< HestonModel > &model, const boost::shared_ptr< HullWhite > &hullWhiteModel, Real relTolerance, Size maxEvaluations)
void update ()
void calculate () const
Protected Member Functions
std::complex< Real > addOnTerm (Real phi, Time t, Size j) const
Private Attributes
boost::shared_ptr< HullWhite > hullWhiteModel_
Real m_
Real a_
Real sigma_
Detailed Description
Analytic Heston engine incl. stochastic interest rates.
This class is pricing a european options under the following processes
\[ \begin{array}{rcl} dS(t, S) &=& (r-d) S dt +\sqrt{v} S dW_1 \\ dv(t, S) &=& \kappa (\theta - v) dt + \sigma \sqrt{v} dW_2 \\ dr(t) &=& (\theta(t) - a r) dt + \eta dW_3 \\ dW_1 dW_2 &=& \rho dt \\ dW_1 dW_3 &=& 0 \\ dW_2 dW_3 &=& 0 \\ \end{array} \]
References:
Karel in't Hout, Joris Bierkens, Antoine von der Ploeg, Joe in't Panhuis, A Semi closed-from analytic pricing formula for call options in a hybrid Heston-Hull-White Model.
A. Sepp, Pricing European-Style Options under Jump Diffusion Processes with Stochastic Volatility: Applications of Fourier Transform (<http://math.ut.ee/~spartak/papers/stochjumpvols.pdf>)
Test:
the correctness of the returned value is tested by reproducing results available in web/literature, testing against QuantLib's analytic Heston and Black-Scholes-Merton Hull-White engine
Definition at line 65 of file analytichestonhullwhiteengine.hpp.
Constructor & Destructor Documentation
QuantLib::AnalyticHestonHullWhiteEngine::AnalyticHestonHullWhiteEngine (const boost::shared_ptr< HestonModel > & hestonModel, const boost::shared_ptr< HullWhite > & hullWhiteModel, Size integrationOrder = 144)
Definition at line 25 of file analytichestonhullwhiteengine.cpp.
References hullWhiteModel_, QuantLib::Observer::registerWith(), and update().
    : AnalyticHestonEngine(hestonModel, integrationOrder),
      hullWhiteModel_(hullWhiteModel) {
        update();
        registerWith(hullWhiteModel_);
    }
QuantLib::AnalyticHestonHullWhiteEngine::AnalyticHestonHullWhiteEngine (const boost::shared_ptr< HestonModel > & model, const boost::shared_ptr< HullWhite > & hullWhiteModel, Real relTolerance, Size maxEvaluations)
Definition at line 36 of file analytichestonhullwhiteengine.cpp.
References hullWhiteModel_, QuantLib::Observer::registerWith(), and update().
    : AnalyticHestonEngine(hestonModel, relTolerance, maxEvaluations),
      hullWhiteModel_(hullWhiteModel) {
        update();
        registerWith(hullWhiteModel_);
    }
Member Function Documentation
std::complex< Real > QuantLib::AnalyticHestonHullWhiteEngine::addOnTerm (Real phi, Time t, Size j) const [inline, protected, virtual]
Reimplemented from QuantLib::AnalyticHestonEngine.
Definition at line 95 of file analytichestonhullwhiteengine.hpp.
References m_.
{
        return std::complex<Real>(-m_*u*u, u*(m_-2*m_*(j-1)));
    }
void QuantLib::AnalyticHestonHullWhiteEngine::calculate () const [virtual]
Reimplemented from QuantLib::AnalyticHestonEngine.
Definition at line 54 of file analytichestonhullwhiteengine.cpp.
References a_, QuantLib::GenericEngine< VanillaOption::arguments, VanillaOption::results >::arguments_, QuantLib::Option::arguments::exercise, m_, QuantLib::GenericModelEngine< HestonModel, VanillaOption::arguments, VanillaOption::results >::model_, QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow(), QL_EPSILON, sigma_, and anonymous_namespace{quantlibbenchmark.cpp}::t.
{
        const Real t = model_->process()->time(arguments_.exercise->lastDate());
        if (a_*t > std::pow(QL_EPSILON, 0.25)) {
            m_ = sigma_*sigma_/(2*a_*a_)
                *(t+2/a_*std::exp(-a_*t)-1/(2*a_)*std::exp(-2*a_*t)-3/(2*a_));
        }
        else {
            // low-a algebraic limit
            m_ = 0.5*sigma_*sigma_*t*t*t*(1/3.0-0.25*a_*t+7/60.0*a_*a_*t*t);
        }
        AnalyticHestonEngine::calculate();
    }
void QuantLib::AnalyticHestonHullWhiteEngine::update () [virtual]
This method must be implemented in derived classes. An instance of Observer does not call this method directly: instead, it will be called by the observables the instance registered with when they need to notify any changes.
Reimplemented from QuantLib::GenericEngine< VanillaOption::arguments, VanillaOption::results >.
Definition at line 47 of file analytichestonhullwhiteengine.cpp.
References a_, hullWhiteModel_, and sigma_.
Referenced by AnalyticHestonHullWhiteEngine().
{
        a_ = hullWhiteModel_->params()[0];
        sigma_ = hullWhiteModel_->params()[1];
        AnalyticHestonEngine::update();
    }
Member Data Documentation
Real QuantLib::AnalyticHestonHullWhiteEngine::a_ [mutable, private]
Definition at line 91 of file analytichestonhullwhiteengine.hpp.
Referenced by calculate(), and update().
boost::shared_ptr<HullWhite> QuantLib::AnalyticHestonHullWhiteEngine::hullWhiteModel_ [private]
Definition at line 88 of file analytichestonhullwhiteengine.hpp.
Referenced by AnalyticHestonHullWhiteEngine(), and update().
Real QuantLib::AnalyticHestonHullWhiteEngine::m_ [mutable, private]
Definition at line 90 of file analytichestonhullwhiteengine.hpp.
Referenced by addOnTerm(), and calculate().
Real QuantLib::AnalyticHestonHullWhiteEngine::sigma_ [mutable, private]
Definition at line 91 of file analytichestonhullwhiteengine.hpp.
Referenced by calculate(), and update().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/vanilla/analytichestonhullwhiteengine.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/vanilla/analytichestonhullwhiteengine.cpp