QuantLib: QuantLib::EvolutionDescription Class Reference
QuantLib::EvolutionDescription Class Reference
Market-model evolution description.
#include <evolutiondescription.hpp>
Public Member Functions
EvolutionDescription ()
EvolutionDescription (const std::vector< Time > &rateTimes, const std::vector< Time > &evolutionTimes=std::vector< Time >(), const std::vector< std::pair< Size, Size > > &relevanceRates=std::vector< range >())
const std::vector< Time > & rateTimes () const
const std::vector< Time > & rateTaus () const
const std::vector< Time > & evolutionTimes () const
const std::vector< Size > & firstAliveRate () const
const std::vector< std::pair
< Size, Size > > & relevanceRates () const
Size numberOfRates () const
Size numberOfSteps () const
Private Types
typedef std::pair< Size, Size > range
Private Attributes
Size numberOfRates_
std::vector< Time > rateTimes_
std::vector< Time > evolutionTimes_
std::vector< std::pair< Size,
Size > > relevanceRates_
std::vector< Time > rateTaus_
std::vector< Size > firstAliveRate_
Detailed Description
Market-model evolution description.
This class stores:
evolutionTimes = the times defining the rates that are to be evolved,
rateTimes = the times at which the rates need to be known,
relevanceRates = which rates need to be known at each time.
This class is really just a tuple of evolution and rate times;
there will be n+1 rate times expressing payment and reset times of forward rates.
there will be any number of evolution times.
we also store which part of the rates are relevant for pricing via relevance rates. The important part for the i-th step will then range from relevanceRates[i].first to relevanceRates[i].second. Default values for relevance rates will be 0 and n.
example for n = 5:
           |-----|-----|-----|-----|-----|      (size = 6)
           t0    t1    t2    t3    t4    t5     rateTimes
           f0    f1    f2    f3    f4           forwardRates
           d0    d1    d2    d3    d4    d5     discountBonds
           d0/d0 d1/d0 d2/d0 d3/d0 d4/d0 d5/d0  discountRatios
           sr0   sr1   sr2   sr3   sr4          coterminalSwaps
Definition at line 54 of file evolutiondescription.hpp.
Member Typedef Documentation
typedef std::pair<Size,Size> QuantLib::EvolutionDescription::range [private]
Definition at line 58 of file evolutiondescription.hpp.
Constructor & Destructor Documentation
QuantLib::EvolutionDescription::EvolutionDescription ()
Definition at line 31 of file evolutiondescription.cpp.
{}
QuantLib::EvolutionDescription::EvolutionDescription (const std::vector< Time > & rateTimes, const std::vector< Time > & evolutionTimes = std::vector<Time>(), const std::vector< std::pair< Size, Size > > & relevanceRates = std::vector<range>()) [explicit]
Definition at line 33 of file evolutiondescription.cpp.
References QuantLib::checkIncreasingTimes(), QuantLib::checkIncreasingTimesAndCalculateTaus(), evolutionTimes_, firstAliveRate(), firstAliveRate_, numberOfRates_, numberOfSteps(), QL_REQUIRE, rateTaus_, rateTimes_, relevanceRates(), and relevanceRates_.
    : numberOfRates_(rateTimes.empty() ? 0 : rateTimes.size()-1),
      rateTimes_(rateTimes),
      evolutionTimes_(evolutionTimes.empty() && !rateTimes.empty() ?
                      std::vector<Time>(rateTimes.begin(), rateTimes.end()-1) :
                      evolutionTimes),
      relevanceRates_(relevanceRates),
      rateTaus_(numberOfRates_),
      //effStopTime_(evolutionTimes_.size(), rateTimes_.size()-1),
      firstAliveRate_(evolutionTimes_.size())
    {
        checkIncreasingTimesAndCalculateTaus(rateTimes_, rateTaus_);
        checkIncreasingTimes(evolutionTimes_);
        Size numberOfSteps = evolutionTimes_.size();
        QL_REQUIRE(evolutionTimes_.back()<=rateTimes[rateTimes.size()-2],
                   "The last evolution time (" << evolutionTimes_.back() <<
                   ") is past the last fixing time (" <<
                   rateTimes[numberOfRates_-2] << ")");
        if (relevanceRates.empty())
            relevanceRates_ = std::vector<std::pair<Size,Size> >(
                                numberOfSteps, std::make_pair(0,numberOfRates_));
        else
            QL_REQUIRE(relevanceRates.size() == numberOfSteps,
                       "relevanceRates / evolutionTimes mismatch");
        //for (Size j=0; j<numberOfSteps; ++j) {
        //    for (Size i=0; i<numberOfRates_; ++i)
        //        effStopTime_[j][i] =
        //            std::min(evolutionTimes_[j], rateTimes_[i]);
        //}
        Time currentEvolutionTime = 0.0;
        Size firstAliveRate = 0;
        for (Size j=0; j<numberOfSteps; ++j) {
            while (rateTimes_[firstAliveRate] <= currentEvolutionTime)
                ++firstAliveRate;
            firstAliveRate_[j] = firstAliveRate;
            currentEvolutionTime = evolutionTimes_[j];
        }
    }
Member Function Documentation
const std::vector< Time > & QuantLib::EvolutionDescription::evolutionTimes () const
Definition at line 89 of file evolutiondescription.cpp.
References evolutionTimes_.
Referenced by QuantLib::AbcdVol::AbcdVol(), QuantLib::MarketModelComposite::add(), QuantLib::CTSMMCapletOriginalCalibration::calibrationFunction(), QuantLib::CallSpecifiedMultiProduct::CallSpecifiedMultiProduct(), QuantLib::CallSpecifiedPathwiseMultiProduct::CallSpecifiedPathwiseMultiProduct(), QuantLib::checkCompatibility(), QuantLib::collectNodeData(), QuantLib::FlatVol::FlatVol(), QuantLib::FwdPeriodAdapter::FwdPeriodAdapter(), QuantLib::isInMoneyMarketPlusMeasure(), QuantLib::LongstaffSchwartzExerciseStrategy::LongstaffSchwartzExerciseStrategy(), QuantLib::MarketModelCashRebate::MarketModelCashRebate(), QuantLib::MarketModelPathwiseCashRebate::MarketModelPathwiseCashRebate(), QuantLib::moneyMarketPlusMeasure(), QuantLib::CallSpecifiedMultiProduct::nextTimeStep(), QuantLib::CallSpecifiedPathwiseMultiProduct::nextTimeStep(), QuantLib::ParametricExerciseAdapter::ParametricExerciseAdapter(), QuantLib::PathwiseAccountingEngine::PathwiseAccountingEngine(), QuantLib::PathwiseVegasAccountingEngine::PathwiseVegasAccountingEngine(), QuantLib::PathwiseVegasOuterAccountingEngine::PathwiseVegasOuterAccountingEngine(), QuantLib::CTSMMCapletCalibration::performChecks(), QuantLib::ProxyGreekEngine::ProxyGreekEngine(), QuantLib::rateInstVolDifferences(), QuantLib::rateVolDifferences(), QuantLib::ParametricExerciseAdapter::relevantTimes(), QuantLib::terminalMeasure(), MarketModelTest::testCallableSwapAnderson(), MarketModelTest::testCallableSwapLS(), MarketModelTest::testCallableSwapNaif(), MarketModelTest::testGreeks(), MarketModelTest::testStochVolForwardsAndOptionlets(), QuantLib::MarketModel::timeDependentVolatility(), and QuantLib::UpperBoundEngine::UpperBoundEngine().
{
        return evolutionTimes_;
    }
const std::vector< Size > & QuantLib::EvolutionDescription::firstAliveRate () const
Definition at line 97 of file evolutiondescription.cpp.
References firstAliveRate_.
Referenced by EvolutionDescription(), QuantLib::FwdPeriodAdapter::FwdPeriodAdapter(), QuantLib::PathwiseVegasAccountingEngine::PathwiseVegasAccountingEngine(), QuantLib::PathwiseVegasOuterAccountingEngine::PathwiseVegasOuterAccountingEngine(), and MarketModelTest::testPathwiseVegas().
{
        return firstAliveRate_;
    }
Size QuantLib::EvolutionDescription::numberOfRates () const
Definition at line 105 of file evolutiondescription.cpp.
References numberOfRates_.
Referenced by QuantLib::CTSMMCapletOriginalCalibration::calibrationFunction(), QuantLib::CallSpecifiedPathwiseMultiProduct::CallSpecifiedPathwiseMultiProduct(), QuantLib::CTSMMCapletAlphaFormCalibration::capletAlphaFormCalibration(), QuantLib::CTSMMCapletMaxHomogeneityCalibration::capletMaxHomogeneityCalibration(), QuantLib::capletSwaptionPeriodicCalibration(), anonymous_namespace{marketmodel_cms.cpp}::makeMarketModel(), anonymous_namespace{marketmodel_smm.cpp}::makeMarketModel(), anonymous_namespace{marketmodel_smmcapletcalibration.cpp}::makeMarketModel(), anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::makeMarketModel(), anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::makeMarketModel(), anonymous_namespace{marketmodel.cpp}::makeMarketModel(), QuantLib::MultiProductPathwiseWrapper::MultiProductPathwiseWrapper(), QuantLib::MarketModelPathwiseCashRebate::nextTimeStep(), QuantLib::CTSMMCapletCalibration::performChecks(), and MarketModelTest::testPathwiseVegas().
{
        return numberOfRates_;
    }
Size QuantLib::EvolutionDescription::numberOfSteps () const
Definition at line 109 of file evolutiondescription.cpp.
References evolutionTimes_.
Referenced by QuantLib::CTSMMCapletOriginalCalibration::calibrationFunction(), QuantLib::CTSMMCapletAlphaFormCalibration::capletAlphaFormCalibration(), QuantLib::CTSMMCapletMaxHomogeneityCalibration::capletMaxHomogeneityCalibration(), QuantLib::capletSwaptionPeriodicCalibration(), QuantLib::anonymous_namespace{upperboundengine.cpp}::DecoratedHedge::DecoratedHedge(), EvolutionDescription(), QuantLib::OrthogonalizedBumpFinder::GetVegaBumps(), MarketModelTest::testPathwiseMarketVegas(), and MarketModelTest::testPathwiseVegas().
{
        return evolutionTimes_.size();
    }
const std::vector< Time > & QuantLib::EvolutionDescription::rateTaus () const
Definition at line 85 of file evolutiondescription.cpp.
References rateTaus_.
Referenced by QuantLib::PathwiseVegasAccountingEngine::PathwiseVegasAccountingEngine(), QuantLib::PathwiseVegasOuterAccountingEngine::PathwiseVegasOuterAccountingEngine(), and MarketModelTest::testPathwiseVegas().
{
        return rateTaus_;
    }
const std::vector< Time > & QuantLib::EvolutionDescription::rateTimes () const
Definition at line 81 of file evolutiondescription.cpp.
References rateTimes_.
Referenced by QuantLib::AbcdVol::AbcdVol(), QuantLib::AccountingEngine::AccountingEngine(), QuantLib::MarketModelComposite::add(), QuantLib::CTSMMCapletCalibration::calibrate(), QuantLib::CTSMMCapletOriginalCalibration::calibrationFunction(), QuantLib::CallSpecifiedMultiProduct::CallSpecifiedMultiProduct(), QuantLib::CallSpecifiedPathwiseMultiProduct::CallSpecifiedPathwiseMultiProduct(), QuantLib::CTSMMCapletAlphaFormCalibration::capletAlphaFormCalibration(), QuantLib::CTSMMCapletMaxHomogeneityCalibration::capletMaxHomogeneityCalibration(), QuantLib::capletSwaptionPeriodicCalibration(), QuantLib::checkCompatibility(), QuantLib::collectNodeData(), QuantLib::FlatVolFactory::create(), QuantLib::CTSMMCapletAlphaFormCalibration::CTSMMCapletAlphaFormCalibration(), QuantLib::FlatVol::FlatVol(), QuantLib::isInMoneyMarketPlusMeasure(), QuantLib::isInTerminalMeasure(), QuantLib::LongstaffSchwartzExerciseStrategy::LongstaffSchwartzExerciseStrategy(), anonymous_namespace{marketmodel_smm.cpp}::makeMarketModel(), anonymous_namespace{marketmodel_cms.cpp}::makeMarketModel(), anonymous_namespace{marketmodel_smmcapletcalibration.cpp}::makeMarketModel(), anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::makeMarketModel(), anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::makeMarketModel(), anonymous_namespace{marketmodel.cpp}::makeMarketModel(), QuantLib::moneyMarketPlusMeasure(), QuantLib::PathwiseAccountingEngine::PathwiseAccountingEngine(), QuantLib::PathwiseVegasAccountingEngine::PathwiseVegasAccountingEngine(), QuantLib::PathwiseVegasOuterAccountingEngine::PathwiseVegasOuterAccountingEngine(), QuantLib::CTSMMCapletCalibration::performChecks(), QuantLib::ProxyGreekEngine::ProxyGreekEngine(), QuantLib::SwapForwardMappings::swaptionImpliedVolatility(), QuantLib::terminalMeasure(), SwapForwardMappingsTest::testForwardCoterminalMappings(), SwapForwardMappingsTest::testSwaptionImpliedVolatility(), and QuantLib::UpperBoundEngine::UpperBoundEngine().
{
        return rateTimes_;
    }
const std::vector< std::pair< Size, Size > > & QuantLib::EvolutionDescription::relevanceRates () const
Definition at line 101 of file evolutiondescription.cpp.
References relevanceRates_.
Referenced by EvolutionDescription().
{
        return relevanceRates_;
    }
Member Data Documentation
std::vector<Time> QuantLib::EvolutionDescription::evolutionTimes_ [private]
Definition at line 76 of file evolutiondescription.hpp.
Referenced by EvolutionDescription(), evolutionTimes(), and numberOfSteps().
std::vector<Size> QuantLib::EvolutionDescription::firstAliveRate_ [private]
Definition at line 80 of file evolutiondescription.hpp.
Referenced by EvolutionDescription(), and firstAliveRate().
Size QuantLib::EvolutionDescription::numberOfRates_ [private]
Definition at line 75 of file evolutiondescription.hpp.
Referenced by EvolutionDescription(), and numberOfRates().
std::vector<Time> QuantLib::EvolutionDescription::rateTaus_ [private]
Definition at line 79 of file evolutiondescription.hpp.
Referenced by EvolutionDescription(), and rateTaus().
std::vector<Time> QuantLib::EvolutionDescription::rateTimes_ [private]
Definition at line 76 of file evolutiondescription.hpp.
Referenced by EvolutionDescription(), and rateTimes().
std::vector<std::pair<Size,Size> > QuantLib::EvolutionDescription::relevanceRates_ [private]
Definition at line 77 of file evolutiondescription.hpp.
Referenced by EvolutionDescription(), and relevanceRates().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/evolutiondescription.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/evolutiondescription.cpp