QuantLib: QuantLib::PdeSecondOrderParabolic Class Reference
QuantLib::PdeSecondOrderParabolic Class Reference
#include <pde.hpp>
Public Member Functions
virtual ~PdeSecondOrderParabolic ()
virtual Real diffusion (Time t, Real x) const =0
virtual Real drift (Time t, Real x) const =0
virtual Real discount (Time t, Real x) const =0
virtual void generateOperator (Time t, const TransformedGrid &tg, TridiagonalOperator &L) const
Detailed Description
Definition at line 32 of file pde.hpp.
Constructor & Destructor Documentation
virtual QuantLib::PdeSecondOrderParabolic::~PdeSecondOrderParabolic () [inline, virtual]
Definition at line 34 of file pde.hpp.
{}
Member Function Documentation
virtual Real QuantLib::PdeSecondOrderParabolic::diffusion (Time t, Real x) const [pure virtual]
Implemented in QuantLib::PdeConstantCoeff< PdeClass >, QuantLib::PdeShortRate, and QuantLib::PdeBSM.
Referenced by generateOperator().
virtual Real QuantLib::PdeSecondOrderParabolic::discount (Time t, Real x) const [pure virtual]
Implemented in QuantLib::PdeConstantCoeff< PdeClass >, QuantLib::PdeShortRate, and QuantLib::PdeBSM.
Referenced by generateOperator().
virtual Real QuantLib::PdeSecondOrderParabolic::drift (Time t, Real x) const [pure virtual]
Implemented in QuantLib::PdeConstantCoeff< PdeClass >, QuantLib::PdeShortRate, and QuantLib::PdeBSM.
Referenced by generateOperator().
virtual void QuantLib::PdeSecondOrderParabolic::generateOperator (Time t, const TransformedGrid & tg, TridiagonalOperator & L) const [inline, virtual]
Definition at line 38 of file pde.hpp.
References diffusion(), discount(), drift(), QuantLib::TransformedGrid::dx(), QuantLib::TransformedGrid::dxm(), QuantLib::TransformedGrid::dxp(), QuantLib::TransformedGrid::grid(), QuantLib::TridiagonalOperator::setMidRow(), anonymous_namespace{distributions.cpp}::sigma, and QuantLib::TransformedGrid::size().
Referenced by QuantLib::BSMOperator::BSMOperator().
{
            for (Size i=1; i < tg.size() - 1; i++) {
                Real sigma = diffusion(t, tg.grid(i));
                Real nu = drift(t, tg.grid(i));
                Real r = discount(t, tg.grid(i));
                Real sigma2 = sigma * sigma;
                Real pd = -(sigma2/tg.dxm(i)-nu)/ tg.dx(i);
                Real pu = -(sigma2/tg.dxp(i)+nu)/ tg.dx(i);
                Real pm = sigma2/(tg.dxm(i) * tg.dxp(i))+r;
                L.setMidRow(i, pd,pm,pu);
            }
        }
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/pde.hpp