QuantLib: QuantLib::CommodityType Class Reference
QuantLib::CommodityType Class Reference
commodity type
#include <commoditytype.hpp>
Classes
struct Data
Public Member Functions
CommodityType ()
default constructor
CommodityType (const std::string &code, const std::string &name)
Inspectors
const std::string & code () const
commodity code, e.g, "HO"
const std::string & name () const
name, e.g, "Heating Oil"
Other information
bool empty () const
is this a usable instance?
Protected Attributes
boost::shared_ptr< Data > data_
Static Protected Attributes
static std::map< std::string,
boost::shared_ptr< Data > > commodityTypes_
Related Functions
(Note that these are not member functions.)
bool operator== (const CommodityType &, const CommodityType &)
bool operator!= (const CommodityType &, const CommodityType &)
std::ostream & operator<< (std::ostream &, const CommodityType &)
Detailed Description
commodity type
Definition at line 36 of file commoditytype.hpp.
Constructor & Destructor Documentation
QuantLib::CommodityType::CommodityType () [inline]
default constructor
Instances built via this constructor have undefined behavior. Such instances can only act as placeholders and must be reassigned to a valid currency before being used.
Definition at line 44 of file commoditytype.hpp.
{}
QuantLib::CommodityType::CommodityType (const std::string & code, const std::string & name)
Definition at line 27 of file commoditytype.cpp.
References code(), commodityTypes_, and data_.
{
        std::map<std::string, boost::shared_ptr<CommodityType::Data> >::const_iterator i = commodityTypes_.find(code);
        if (i != commodityTypes_.end())
            data_ = i->second;
        else {
            data_ = boost::shared_ptr<CommodityType::Data>(
                                         new CommodityType::Data(name, code));
            commodityTypes_[code] = data_;
        }
    }
Member Function Documentation
const std::string & QuantLib::CommodityType::code () const [inline]
commodity code, e.g, "HO"
Definition at line 95 of file commoditytype.hpp.
References data_.
Referenced by CommodityType(), QuantLib::UnitOfMeasureConversionManager::directLookup(), QuantLib::operator<<(), QuantLib::operator==(), and QuantLib::UnitOfMeasureConversionManager::smartLookup().
{
        return data_->code;
    }
bool QuantLib::CommodityType::empty () const [inline]
is this a usable instance?
Definition at line 103 of file commoditytype.hpp.
References data_.
Referenced by QuantLib::operator<<().
{
        return !data_;
    }
const std::string & QuantLib::CommodityType::name () const [inline]
name, e.g, "Heating Oil"
Definition at line 99 of file commoditytype.hpp.
References data_.
Referenced by QuantLib::UnitOfMeasureConversion::Data::Data().
{
        return data_->name;
    }
Friends And Related Function Documentation
bool operator!= (const CommodityType & , const CommodityType &) [related]
Definition at line 111 of file commoditytype.hpp.
{
        return !(c1 == c2);
    }
std::ostream & operator<< (std::ostream & , const CommodityType &) [related]
Definition at line 39 of file commoditytype.cpp.
{
        if (!c.empty())
            return out << c.code();
        else
            return out << "null commodity type";
    }
bool operator== (const CommodityType & , const CommodityType &) [related]
Definition at line 107 of file commoditytype.hpp.
{
        return c1.code() == c2.code();
    }
Member Data Documentation
std::map< std::string, boost::shared_ptr< CommodityType::Data > > QuantLib::CommodityType::commodityTypes_ [static, protected]
Definition at line 72 of file commoditytype.hpp.
Referenced by CommodityType().
boost::shared_ptr<Data> QuantLib::CommodityType::data_ [protected]
Definition at line 61 of file commoditytype.hpp.
Referenced by code(), CommodityType(), empty(), and name().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/commodities/commoditytype.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/commodities/commoditytype.cpp