QuantLib: QuantLib::SwaptionVolCube1::Cube Class Reference
QuantLib::SwaptionVolCube1::Cube Class Reference
Public Member Functions
Cube ()
Cube (const std::vector< Date > &optionDates, const std::vector< Period > &swapTenors, const std::vector< Time > &optionTimes, const std::vector< Time > &swapLengths, Size nLayers, bool extrapolation=true)
Cube & operator= (const Cube &o)
Cube (const Cube &)
virtual ~Cube ()
void setElement (Size IndexOfLayer, Size IndexOfRow, Size IndexOfColumn, Real x)
void setPoints (const std::vector< Matrix > &x)
void setPoint (const Date &optionDate, const Period &swapTenor, const Time optionTime, const Time swapLengths, const std::vector< Real > &point)
void setLayer (Size i, const Matrix &x)
void expandLayers (Size i, bool expandOptionTimes, Size j, bool expandSwapLengths)
const std::vector< Date > & optionDates () const
const std::vector< Period > & swapTenors () const
const std::vector< Time > & optionTimes () const
const std::vector< Time > & swapLengths () const
const std::vector< Matrix > & points () const
std::vector< Real > operator() (const Time optionTime, const Time swapLengths) const
void updateInterpolators () const
Matrix browse () const
Private Attributes
std::vector< Time > optionTimes_
std::vector< Time > swapLengths_
std::vector< Date > optionDates_
std::vector< Period > swapTenors_
Size nLayers_
std::vector< Matrix > points_
std::vector< Disposable< Matrix > > transposedPoints_
bool extrapolation_
std::vector< boost::shared_ptr
< Interpolation2D > > interpolators_
Detailed Description
Definition at line 37 of file swaptionvolcube1.hpp.
Constructor & Destructor Documentation
QuantLib::SwaptionVolCube1::Cube::Cube () [inline]
Definition at line 39 of file swaptionvolcube1.hpp.
{}
QuantLib::SwaptionVolCube1::Cube::Cube (const std::vector< Date > & optionDates, const std::vector< Period > & swapTenors, const std::vector< Time > & optionTimes, const std::vector< Time > & swapLengths, Size nLayers, bool extrapolation = true)
Definition at line 590 of file swaptionvolcube1.cpp.
References interpolators_, nLayers_, optionTimes_, points(), QL_REQUIRE, setPoints(), swapLengths_, QuantLib::transpose(), and transposedPoints_.
    : optionTimes_(optionTimes), swapLengths_(swapLengths),
      optionDates_(optionDates), swapTenors_(swapTenors),
      nLayers_(nLayers), extrapolation_(extrapolation) {
        QL_REQUIRE(optionTimes.size()>1,"Cube::Cube(...): optionTimes.size()<2");
        QL_REQUIRE(swapLengths.size()>1,"Cube::Cube(...): swapLengths.size()<2");
        QL_REQUIRE(optionTimes.size()==optionDates.size(),
                   "Cube::Cube(...): optionTimes/optionDates mismatch");
        QL_REQUIRE(swapTenors.size()==swapLengths.size(),
                   "Cube::Cube(...): swapTenors/swapLengths mismatch");
        std::vector<Matrix> points(nLayers_, Matrix(optionTimes_.size(),
                                                    swapLengths_.size(), 0.0));
        for (Size k=0;k<nLayers_;k++) {
            transposedPoints_.push_back(transpose(points[k]));
            boost::shared_ptr<Interpolation2D> interpolation (new
                BilinearInterpolation (optionTimes_.begin(), optionTimes_.end(),
                                       swapLengths_.begin(), swapLengths_.end(),
                                       transposedPoints_[k]));
            interpolators_.push_back(boost::shared_ptr<Interpolation2D>(
                new FlatExtrapolator2D(interpolation)));
            interpolators_[k]->enableExtrapolation();
        }
        setPoints(points);
     }
QuantLib::SwaptionVolCube1::Cube::Cube (const Cube & o)
Definition at line 626 of file swaptionvolcube1.cpp.
References extrapolation_, nLayers_, QuantLib::SwaptionVolatilityDiscrete::optionDates_, optionDates_, QuantLib::SwaptionVolatilityDiscrete::optionTimes_, optionTimes_, points_, QuantLib::SwaptionVolatilityDiscrete::swapLengths_, swapLengths_, QuantLib::SwaptionVolatilityDiscrete::swapTenors_, swapTenors_, and transposedPoints_.
{
        optionTimes_ = o.optionTimes_;
        swapLengths_ = o.swapLengths_;
        optionDates_ = o.optionDates_;
        swapTenors_ = o.swapTenors_;
        nLayers_ = o.nLayers_;
        extrapolation_ = o.extrapolation_;
        transposedPoints_ = o.transposedPoints_;
        for (Size k=0; k<nLayers_; ++k) {
            boost::shared_ptr<Interpolation2D> interpolation (
                new BilinearInterpolation (optionTimes_.begin(), optionTimes_.end(),
                                           swapLengths_.begin(), swapLengths_.end(),
                                           transposedPoints_[k]));
            interpolators_.push_back(boost::shared_ptr<Interpolation2D>(
                new FlatExtrapolator2D(interpolation)));
            interpolators_[k]->enableExtrapolation();
        }
        setPoints(o.points_);
    }
virtual QuantLib::SwaptionVolCube1::Cube::~Cube () [inline, virtual]
Definition at line 48 of file swaptionvolcube1.hpp.
{}
Member Function Documentation
Matrix QuantLib::SwaptionVolCube1::Cube::browse () const
Definition at line 807 of file swaptionvolcube1.cpp.
References QuantLib::SwaptionVolatilityDiscrete::optionTimes_, and QuantLib::SwaptionVolatilityDiscrete::swapLengths_.
Referenced by QuantLib::SwaptionVolCube1::denseSabrParameters(), QuantLib::SwaptionVolCube1::marketVolCube(), QuantLib::SwaptionVolCube1::sparseSabrParameters(), and QuantLib::SwaptionVolCube1::volCubeAtmCalibrated().
{
        Matrix result(swapLengths_.size()*optionTimes_.size(), nLayers_+2, 0.0);
        for (Size i=0; i<swapLengths_.size(); ++i) {
            for (Size j=0; j<optionTimes_.size(); ++j) {
                result[i*optionTimes_.size()+j][0] = swapLengths_[i];
                result[i*optionTimes_.size()+j][1] = optionTimes_[j];
                for (Size k=0; k<nLayers_; ++k)
                    result[i*optionTimes_.size()+j][2+k] = points_[k][j][i];
            }
        }
        return result;
    }
void QuantLib::SwaptionVolCube1::Cube::expandLayers (Size i, bool expandOptionTimes, Size j, bool expandSwapLengths)
Definition at line 739 of file swaptionvolcube1.cpp.
References QuantLib::SwaptionVolatilityDiscrete::optionDates_, QuantLib::SwaptionVolatilityDiscrete::optionTimes_, QL_REQUIRE, QuantLib::SwaptionVolatilityDiscrete::swapLengths_, QuantLib::SwaptionVolatilityDiscrete::swapTenors_, and anonymous_namespace{perturbativebarrieroptionengine.cpp}::v().
{
        QL_REQUIRE(i<=optionTimes_.size(),"Cube::expandLayers: incompatible size 1");
        QL_REQUIRE(j<=swapLengths_.size(),"Cube::expandLayers: incompatible size 2");
        if (expandOptionTimes) {
            optionTimes_.insert(optionTimes_.begin()+i,0.);
            optionDates_.insert(optionDates_.begin()+i, Date());
        }
        if (expandSwapLengths) {
            swapLengths_.insert(swapLengths_.begin()+j,0.);
            swapTenors_.insert(swapTenors_.begin()+j, Period());
        }
        std::vector<Matrix> newPoints(nLayers_,Matrix(optionTimes_.size(),
                                                      swapLengths_.size(), 0.));
        for (Size k=0; k<nLayers_; ++k) {
            for (Size u=0; u<points_[k].rows(); ++u) {
                 Size indexOfRow = u;
                 if (u>=i && expandOptionTimes) indexOfRow = u+1;
                 for (Size v=0; v<points_[k].columns(); ++v) {
                      Size indexOfCol = v;
                      if (v>=j && expandSwapLengths) indexOfCol = v+1;
                      newPoints[k][indexOfRow][indexOfCol]=points_[k][u][v];
                 }
            }
        }
        setPoints(newPoints);
    }
std::vector< Real > QuantLib::SwaptionVolCube1::Cube::operator() (const Time optionTime, const Time swapLengths) const
Definition at line 776 of file swaptionvolcube1.cpp.
References QuantLib::SwaptionVolatilityStructure::swapLength().
{
        std::vector<Real> result;
        for (Size k=0; k<nLayers_; ++k)
            result.push_back(interpolators_[k]->operator()(optionTime, swapLength));
        return result;
    }
SwaptionVolCube1::Cube & QuantLib::SwaptionVolCube1::Cube::operator= (const Cube & o)
Definition at line 647 of file swaptionvolcube1.cpp.
References extrapolation_, nLayers_, QuantLib::SwaptionVolatilityDiscrete::optionDates_, optionDates_, QuantLib::SwaptionVolatilityDiscrete::optionTimes_, optionTimes_, points_, QuantLib::SwaptionVolatilityDiscrete::swapLengths_, swapLengths_, QuantLib::SwaptionVolatilityDiscrete::swapTenors_, swapTenors_, and transposedPoints_.
{
        optionTimes_ = o.optionTimes_;
        swapLengths_ = o.swapLengths_;
        optionDates_ = o.optionDates_;
        swapTenors_ = o.swapTenors_;
        nLayers_ = o.nLayers_;
        extrapolation_ = o.extrapolation_;
        transposedPoints_ = o.transposedPoints_;
        for(Size k=0;k<nLayers_;k++){
            boost::shared_ptr<Interpolation2D> interpolation (
                new BilinearInterpolation (optionTimes_.begin(), optionTimes_.end(),
                                           swapLengths_.begin(), swapLengths_.end(),
                                           transposedPoints_[k]));
            interpolators_.push_back(boost::shared_ptr<Interpolation2D>(
                new FlatExtrapolator2D(interpolation)));
            interpolators_[k]->enableExtrapolation();
        }
        setPoints(o.points_);
        return *this;
    }
const std::vector<Date>& QuantLib::SwaptionVolCube1::Cube::optionDates () const [inline]
Definition at line 65 of file swaptionvolcube1.hpp.
References optionDates_.
Referenced by QuantLib::SwaptionVolCube1::fillVolatilityCube(), QuantLib::SwaptionVolCube1::sabrCalibration(), QuantLib::SwaptionVolCube1::sabrCalibrationSection(), and QuantLib::SwaptionVolCube1::spreadVolInterpolation().
{
                return optionDates_;
            }
const std::vector< Time > & QuantLib::SwaptionVolCube1::Cube::optionTimes () const
Definition at line 785 of file swaptionvolcube1.cpp.
References QuantLib::SwaptionVolatilityDiscrete::optionTimes_.
Referenced by QuantLib::SwaptionVolCube1::createSparseSmiles(), QuantLib::SwaptionVolCube1::fillVolatilityCube(), QuantLib::SwaptionVolCube1::sabrCalibration(), QuantLib::SwaptionVolCube1::sabrCalibrationSection(), and QuantLib::SwaptionVolCube1::spreadVolInterpolation().
{
        return optionTimes_;
    }
const std::vector< Matrix > & QuantLib::SwaptionVolCube1::Cube::points () const
Definition at line 772 of file swaptionvolcube1.cpp.
Referenced by Cube(), QuantLib::SwaptionVolCube1::marketVolCube(), QuantLib::SwaptionVolCube1::sabrCalibration(), and QuantLib::SwaptionVolCube1::sabrCalibrationSection().
{
        return points_;
    }
void QuantLib::SwaptionVolCube1::Cube::setElement (Size IndexOfLayer, Size IndexOfRow, Size IndexOfColumn, Real x)
Definition at line 668 of file swaptionvolcube1.cpp.
References QuantLib::SwaptionVolatilityDiscrete::optionTimes_, QL_REQUIRE, and QuantLib::SwaptionVolatilityDiscrete::swapLengths_.
Referenced by QuantLib::SwaptionVolCube1::performCalculations().
{
        QL_REQUIRE(IndexOfLayer<nLayers_,
            "Cube::setElement: incompatible IndexOfLayer ");
        QL_REQUIRE(IndexOfRow<optionTimes_.size(),
            "Cube::setElement: incompatible IndexOfRow");
        QL_REQUIRE(IndexOfColumn<swapLengths_.size(),
            "Cube::setElement: incompatible IndexOfColumn");
        points_[IndexOfLayer][IndexOfRow][IndexOfColumn] = x;
    }
void QuantLib::SwaptionVolCube1::Cube::setLayer (Size i, const Matrix & x)
Definition at line 693 of file swaptionvolcube1.cpp.
References QuantLib::Matrix::columns(), QuantLib::SwaptionVolatilityDiscrete::optionTimes_, QL_REQUIRE, QuantLib::Matrix::rows(), and QuantLib::SwaptionVolatilityDiscrete::swapLengths_.
Referenced by QuantLib::SwaptionVolCube1::recalibration(), QuantLib::SwaptionVolCube1::sabrCalibration(), and QuantLib::SwaptionVolCube1::spreadVolInterpolation().
{
        QL_REQUIRE(i<nLayers_,
            "Cube::setLayer: incompatible number of layer ");
        QL_REQUIRE(x.rows()==optionTimes_.size(),
            "Cube::setLayer: incompatible size 1");
        QL_REQUIRE(x.columns()==swapLengths_.size(),
            "Cube::setLayer: incompatible size 2");
        points_[i] = x;
    }
void QuantLib::SwaptionVolCube1::Cube::setPoint (const Date & optionDate, const Period & swapTenor, const Time optionTime, const Time swapLengths, const std::vector< Real > & point)
Definition at line 705 of file swaptionvolcube1.cpp.
References QuantLib::SwaptionVolatilityDiscrete::optionDates_, QuantLib::SwaptionVolatilityDiscrete::optionTimes_, QuantLib::SwaptionVolatilityStructure::swapLength(), QuantLib::SwaptionVolatilityDiscrete::swapLengths_, and QuantLib::SwaptionVolatilityDiscrete::swapTenors_.
Referenced by QuantLib::SwaptionVolCube1::fillVolatilityCube(), and QuantLib::SwaptionVolCube1::sabrCalibrationSection().
    {
        const bool expandOptionTimes =
            !(std::binary_search(optionTimes_.begin(),optionTimes_.end(),optionTime));
        const bool expandSwapLengths =
            !(std::binary_search(swapLengths_.begin(),swapLengths_.end(),swapLength));
        std::vector<Real>::const_iterator optionTimesPreviousNode,
                                          swapLengthsPreviousNode;
        optionTimesPreviousNode =
            std::lower_bound(optionTimes_.begin(),optionTimes_.end(),optionTime);
        Size optionTimesIndex = optionTimesPreviousNode - optionTimes_.begin();
        swapLengthsPreviousNode =
            std::lower_bound(swapLengths_.begin(),swapLengths_.end(),swapLength);
        Size swapLengthsIndex = swapLengthsPreviousNode - swapLengths_.begin();
        if (expandOptionTimes || expandSwapLengths)
            expandLayers(optionTimesIndex, expandOptionTimes,
                         swapLengthsIndex, expandSwapLengths);
        for (Size k=0; k<nLayers_; ++k)
            points_[k][optionTimesIndex][swapLengthsIndex] = point[k];
        optionTimes_[optionTimesIndex] = optionTime;
        swapLengths_[swapLengthsIndex] = swapLength;
        optionDates_[optionTimesIndex] = optionDate;
        swapTenors_[swapLengthsIndex] = swapTenor;
    }
void QuantLib::SwaptionVolCube1::Cube::setPoints (const std::vector< Matrix > & x)
Definition at line 681 of file swaptionvolcube1.cpp.
References QuantLib::SwaptionVolatilityDiscrete::optionTimes_, QL_REQUIRE, and QuantLib::SwaptionVolatilityDiscrete::swapLengths_.
Referenced by Cube().
{
        QL_REQUIRE(x.size()==nLayers_,
            "Cube::setPoints: incompatible number of layers ");
        QL_REQUIRE(x[0].rows()==optionTimes_.size(),
            "Cube::setPoints: incompatible size 1");
        QL_REQUIRE(x[0].columns()==swapLengths_.size(),
            "Cube::setPoints: incompatible size 2");
        points_ = x;
    }
const std::vector< Time > & QuantLib::SwaptionVolCube1::Cube::swapLengths () const
Definition at line 790 of file swaptionvolcube1.cpp.
References QuantLib::SwaptionVolatilityDiscrete::swapLengths_.
Referenced by QuantLib::SwaptionVolCube1::createSparseSmiles(), QuantLib::SwaptionVolCube1::fillVolatilityCube(), QuantLib::SwaptionVolCube1::sabrCalibration(), QuantLib::SwaptionVolCube1::sabrCalibrationSection(), and QuantLib::SwaptionVolCube1::spreadVolInterpolation().
{
        return swapLengths_;
    }
const std::vector<Period>& QuantLib::SwaptionVolCube1::Cube::swapTenors () const [inline]
Definition at line 68 of file swaptionvolcube1.hpp.
References swapTenors_.
Referenced by QuantLib::SwaptionVolCube1::fillVolatilityCube(), QuantLib::SwaptionVolCube1::sabrCalibration(), QuantLib::SwaptionVolCube1::sabrCalibrationSection(), and QuantLib::SwaptionVolCube1::spreadVolInterpolation().
{
                return swapTenors_;
            }
void QuantLib::SwaptionVolCube1::Cube::updateInterpolators () const
Definition at line 794 of file swaptionvolcube1.cpp.
References QuantLib::SwaptionVolatilityDiscrete::optionTimes_, QuantLib::SwaptionVolatilityDiscrete::swapLengths_, and QuantLib::transpose().
Referenced by QuantLib::SwaptionVolCube1::fillVolatilityCube(), QuantLib::SwaptionVolCube1::performCalculations(), QuantLib::SwaptionVolCube1::recalibration(), QuantLib::SwaptionVolCube1::sabrCalibrationSection(), and QuantLib::SwaptionVolCube1::spreadVolInterpolation().
{
        for (Size k=0; k<nLayers_; ++k) {
            transposedPoints_[k] = transpose(points_[k]);
            boost::shared_ptr<Interpolation2D> interpolation (
                new BilinearInterpolation (optionTimes_.begin(), optionTimes_.end(),
                                           swapLengths_.begin(), swapLengths_.end(),
                                           transposedPoints_[k]));
            interpolators_[k] = boost::shared_ptr<Interpolation2D>(
                new FlatExtrapolator2D(interpolation));
            interpolators_[k]->enableExtrapolation();
        }
    }
Member Data Documentation
bool QuantLib::SwaptionVolCube1::Cube::extrapolation_ [private]
Definition at line 85 of file swaptionvolcube1.hpp.
Referenced by Cube(), and operator=().
std::vector< boost::shared_ptr<Interpolation2D> > QuantLib::SwaptionVolCube1::Cube::interpolators_ [mutable, private]
Definition at line 86 of file swaptionvolcube1.hpp.
Referenced by Cube().
Size QuantLib::SwaptionVolCube1::Cube::nLayers_ [private]
Definition at line 82 of file swaptionvolcube1.hpp.
Referenced by Cube(), and operator=().
std::vector<Date> QuantLib::SwaptionVolCube1::Cube::optionDates_ [private]
Definition at line 80 of file swaptionvolcube1.hpp.
Referenced by Cube(), operator=(), and optionDates().
std::vector<Time> QuantLib::SwaptionVolCube1::Cube::optionTimes_ [private]
Definition at line 79 of file swaptionvolcube1.hpp.
Referenced by Cube(), and operator=().
std::vector<Matrix> QuantLib::SwaptionVolCube1::Cube::points_ [private]
Definition at line 83 of file swaptionvolcube1.hpp.
Referenced by Cube(), and operator=().
std::vector<Time> QuantLib::SwaptionVolCube1::Cube::swapLengths_ [private]
Definition at line 79 of file swaptionvolcube1.hpp.
Referenced by Cube(), and operator=().
std::vector<Period> QuantLib::SwaptionVolCube1::Cube::swapTenors_ [private]
Definition at line 81 of file swaptionvolcube1.hpp.
Referenced by Cube(), operator=(), and swapTenors().
std::vector<Disposable<Matrix> > QuantLib::SwaptionVolCube1::Cube::transposedPoints_ [mutable, private]
Definition at line 84 of file swaptionvolcube1.hpp.
Referenced by Cube(), and operator=().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/swaption/swaptionvolcube1.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/swaption/swaptionvolcube1.cpp