QuantLib: QuantLib::Parameter Class Reference
QuantLib::Parameter Class Reference
Base class for model arguments.
#include <parameter.hpp>
Classes
class Impl
Base class for model parameter implementation.
Public Member Functions
Parameter ()
const Array & params () const
void setParam (Size i, Real x)
bool testParams (const Array &params) const
Size size () const
Real operator() (Time t) const
const boost::shared_ptr< Impl > & implementation () const
Protected Member Functions
Parameter (Size size, const boost::shared_ptr< Impl > &impl, const Constraint &constraint)
Protected Attributes
boost::shared_ptr< Impl > impl_
Array params_
Constraint constraint_
Detailed Description
Base class for model arguments.
Definition at line 37 of file parameter.hpp.
Constructor & Destructor Documentation
QuantLib::Parameter::Parameter () [inline]
Definition at line 47 of file parameter.hpp.
        : constraint_(NoConstraint()) {}
QuantLib::Parameter::Parameter (Size size, const boost::shared_ptr< Impl > & impl, const Constraint & constraint) [inline, protected]
Definition at line 62 of file parameter.hpp.
        : impl_(impl), params_(size), constraint_(constraint) {}
Member Function Documentation
const boost::shared_ptr<Impl>& QuantLib::Parameter::implementation () const [inline]
Definition at line 58 of file parameter.hpp.
References impl_.
Referenced by QuantLib::BlackKarasinski::tree(), QuantLib::HullWhite::tree(), QuantLib::ExtendedCoxIngersollRoss::tree(), and QuantLib::GeneralizedHullWhite::tree().
{
            return impl_;
        }
Real QuantLib::Parameter::operator() (Time t) const [inline]
Definition at line 55 of file parameter.hpp.
References impl_, and params_.
{
            return impl_->value(params_, t);
        }
const Array& QuantLib::Parameter::params () const [inline]
Definition at line 49 of file parameter.hpp.
References params_.
{ return params_; }
void QuantLib::Parameter::setParam (Size i, Real x) [inline]
Definition at line 50 of file parameter.hpp.
References params_.
Referenced by QuantLib::GeneralizedHullWhite::GeneralizedHullWhite(), and HestonModelTest::testDAXCalibrationOfTimeDependentModel().
{ params_[i] = x; }
Size QuantLib::Parameter::size () const [inline]
Definition at line 54 of file parameter.hpp.
References params_, and QuantLib::Array::size().
Referenced by QuantLib::GeneralizedHullWhite::GeneralizedHullWhite(), QuantLib::GeneralizedHullWhite::speed(), QuantLib::PiecewiseConstantParameter::Impl::value(), and QuantLib::GeneralizedHullWhite::vol().
{ return params_.size(); }
bool QuantLib::Parameter::testParams (const Array & params) const [inline]
Definition at line 51 of file parameter.hpp.
References constraint_, and QuantLib::Constraint::test().
Referenced by QuantLib::ConstantParameter::ConstantParameter().
{
            return constraint_.test(params);
        }
Member Data Documentation
Constraint QuantLib::Parameter::constraint_ [protected]
Definition at line 67 of file parameter.hpp.
Referenced by testParams().
boost::shared_ptr<Impl> QuantLib::Parameter::impl_ [protected]
Definition at line 45 of file parameter.hpp.
Referenced by implementation(), and operator()().
Array QuantLib::Parameter::params_ [protected]
Definition at line 66 of file parameter.hpp.
Referenced by QuantLib::ConstantParameter::ConstantParameter(), operator()(), params(), setParam(), and size().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/parameter.hpp