QuantLib: QuantLib::ExerciseAdapter Class Reference
QuantLib::ExerciseAdapter Class Reference
#include <exerciseadapter.hpp>
Public Member Functions
ExerciseAdapter (const Clone< MarketModelExerciseValue > &exercise, Size numberOfProducts=1)
MarketModelMultiProduct interface
std::vector< Time > possibleCashFlowTimes () const
Size numberOfProducts () const
const EvolutionDescription & evolution () const
Size maxNumberOfCashFlowsPerProductPerStep () const
void reset ()
during simulation put product at start of path
bool nextTimeStep (const CurveState &, std::vector< Size > &, std::vector< std::vector< CashFlow > > &)
return value indicates whether path is finished, TRUE means done
std::auto_ptr
< MarketModelMultiProduct > clone () const
returns a newly-allocated copy of itself
inspectors
const MarketModelExerciseValue & exerciseValue () const
Private Attributes
Clone< MarketModelExerciseValue > exercise_
Size numberOfProducts_
std::valarray< bool > isExerciseTime_
Size currentIndex_
Detailed Description
Definition at line 30 of file exerciseadapter.hpp.
Constructor & Destructor Documentation
QuantLib::ExerciseAdapter::ExerciseAdapter (const Clone< MarketModelExerciseValue > & exercise, Size numberOfProducts = 1)
Definition at line 24 of file exerciseadapter.cpp.
Referenced by clone().
    : MultiProductMultiStep(exercise->evolution().rateTimes()),
      exercise_(exercise), numberOfProducts_(numberOfProducts),
      isExerciseTime_(exercise->isExerciseTime()) {}
Member Function Documentation
std::auto_ptr< MarketModelMultiProduct > QuantLib::ExerciseAdapter::clone () const [virtual]
returns a newly-allocated copy of itself
Implements QuantLib::MarketModelMultiProduct.
Definition at line 52 of file exerciseadapter.cpp.
References ExerciseAdapter().
{
        return std::auto_ptr<MarketModelMultiProduct>(
                                                  new ExerciseAdapter(*this));
    }
const EvolutionDescription & QuantLib::ExerciseAdapter::evolution () const [inline, virtual]
Reimplemented from QuantLib::MultiProductMultiStep.
Definition at line 68 of file exerciseadapter.hpp.
References QuantLib::MarketModelExerciseValue::evolution(), and exercise_.
{
        return exercise_->evolution();
    }
const MarketModelExerciseValue & QuantLib::ExerciseAdapter::exerciseValue () const [inline]
Definition at line 83 of file exerciseadapter.hpp.
References exercise_.
{
        return *exercise_;
    }
Size QuantLib::ExerciseAdapter::maxNumberOfCashFlowsPerProductPerStep () const [inline, virtual]
Implements QuantLib::MarketModelMultiProduct.
Definition at line 73 of file exerciseadapter.hpp.
{
        return 1;
    }
bool QuantLib::ExerciseAdapter::nextTimeStep (const CurveState & currentState, std::vector< Size > & numberCashFlowsThisStep, std::vector< std::vector< CashFlow > > & cashFlowsGenerated) [virtual]
return value indicates whether path is finished, TRUE means done
Implements QuantLib::MarketModelMultiProduct.
Definition at line 31 of file exerciseadapter.cpp.
References currentIndex_, exercise_, isExerciseTime_, QuantLib::MarketModelExerciseValue::nextStep(), and QuantLib::MarketModelExerciseValue::value().
{
        std::fill(numberCashFlowsThisStep.begin(),
                  numberCashFlowsThisStep.end(), 0);
        bool done = false;
        exercise_->nextStep(currentState);
        if (isExerciseTime_[currentIndex_]) {
            MarketModelMultiProduct::CashFlow cashflow =
                exercise_->value(currentState);
            numberCashFlowsThisStep[0] = 1;
            generatedCashFlows[0][0] = cashflow;
            done = true;
        }
        ++currentIndex_;
        return done || currentIndex_ == isExerciseTime_.size();
    }
Size QuantLib::ExerciseAdapter::numberOfProducts () const [inline, virtual]
Implements QuantLib::MarketModelMultiProduct.
Definition at line 64 of file exerciseadapter.hpp.
References numberOfProducts_.
{
        return numberOfProducts_;
    }
std::vector< Time > QuantLib::ExerciseAdapter::possibleCashFlowTimes () const [inline, virtual]
Implements QuantLib::MarketModelMultiProduct.
Definition at line 60 of file exerciseadapter.hpp.
References exercise_, and QuantLib::MarketModelExerciseValue::possibleCashFlowTimes().
{
        return exercise_->possibleCashFlowTimes();
    }
void QuantLib::ExerciseAdapter::reset () [inline, virtual]
during simulation put product at start of path
Implements QuantLib::MarketModelMultiProduct.
Definition at line 77 of file exerciseadapter.hpp.
References currentIndex_, exercise_, and QuantLib::MarketModelExerciseValue::reset().
{
        exercise_->reset();
        currentIndex_ = 0;
    }
Member Data Documentation
Size QuantLib::ExerciseAdapter::currentIndex_ [private]
Definition at line 54 of file exerciseadapter.hpp.
Referenced by nextTimeStep(), and reset().
Clone<MarketModelExerciseValue> QuantLib::ExerciseAdapter::exercise_ [private]
Definition at line 51 of file exerciseadapter.hpp.
Referenced by evolution(), exerciseValue(), nextTimeStep(), possibleCashFlowTimes(), and reset().
std::valarray<bool> QuantLib::ExerciseAdapter::isExerciseTime_ [private]
Definition at line 53 of file exerciseadapter.hpp.
Referenced by nextTimeStep().
Size QuantLib::ExerciseAdapter::numberOfProducts_ [private]
Definition at line 52 of file exerciseadapter.hpp.
Referenced by numberOfProducts().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/products/multistep/exerciseadapter.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/products/multistep/exerciseadapter.cpp