QuantLib: QuantLib::DigitalPathPricer Class Reference
QuantLib::DigitalPathPricer Class Reference
#include <mcdigitalengine.hpp>
Public Member Functions
DigitalPathPricer (const boost::shared_ptr< CashOrNothingPayoff > &payoff, const boost::shared_ptr< AmericanExercise > &exercise, const Handle< YieldTermStructure > &discountTS, const boost::shared_ptr< StochasticProcess1D > &diffProcess, const PseudoRandom::ursg_type &sequenceGen)
Real operator() (const Path &path) const
Private Attributes
boost::shared_ptr
< CashOrNothingPayoff > payoff_
boost::shared_ptr
< AmericanExercise > exercise_
boost::shared_ptr
< StochasticProcess1D > diffProcess_
PseudoRandom::ursg_type sequenceGen_
Handle< YieldTermStructure > discountTS_
Detailed Description
Definition at line 112 of file mcdigitalengine.hpp.
Constructor & Destructor Documentation
QuantLib::DigitalPathPricer::DigitalPathPricer (const boost::shared_ptr< CashOrNothingPayoff > & payoff, const boost::shared_ptr< AmericanExercise > & exercise, const Handle< YieldTermStructure > & discountTS, const boost::shared_ptr< StochasticProcess1D > & diffProcess, const PseudoRandom::ursg_type & sequenceGen)
Definition at line 26 of file mcdigitalengine.cpp.
    : payoff_(payoff), exercise_(exercise), diffProcess_(diffProcess),
      sequenceGen_(sequenceGen), discountTS_(discountTS) {}
Member Function Documentation
Real QuantLib::DigitalPathPricer::operator() (const Path & path) const [virtual]
Implements QuantLib::PathPricer< Path >.
Definition at line 35 of file mcdigitalengine.cpp.
References QuantLib::TimeGrid::back(), QuantLib::Option::Call, diffProcess_, discountTS_, QuantLib::anonymous_namespace{yieldtermstructure.cpp}::dt, QuantLib::TimeGrid::dt(), exercise_, QuantLib::Path::front(), QuantLib::Path::length(), QuantLib::RandomSequenceGenerator< RNG >::nextSequence(), payoff_, QuantLib::Option::Put, QL_FAIL, QL_REQUIRE, sequenceGen_, QuantLib::Path::timeGrid(), and QuantLib::Sample< T >::value.
{
        Size n = path.length();
        QL_REQUIRE(n>1, "the path cannot be empty");
        Real log_asset_price = std::log(path.front());
        Real x, y;
        Volatility vol;
        TimeGrid timeGrid = path.timeGrid();
        Time dt;
        std::vector<Real> u = sequenceGen_.nextSequence().value;
        Real log_strike = std::log(payoff_->strike());
        Size i;
        switch (payoff_->optionType()) {
          case Option::Call:
            for (i=0; i<n-1; i++) {
                x = std::log(path[i+1]/path[i]);
                // terminal or initial vol?
                vol = diffProcess_->diffusion(timeGrid[i+1],
                                              std::exp(log_asset_price));
                // vol = diffProcess_->diffusion(timeGrid[i+2],
                //                               std::exp(log_asset_price+x));
                dt = timeGrid.dt(i);
                y = log_asset_price +
                    0.5*(x + std::sqrt(x*x-2*vol*vol*dt*std::log((1-u[i]))));
                // cross the strike
                if (y >= log_strike) {
                    if (exercise_->payoffAtExpiry()) {
                        return payoff_->cashPayoff() *
                            discountTS_->discount(path.timeGrid().back());
                    } else {
                        // the discount should be calculated at the exercise
                        // time between path.timeGrid()[i+1] and
                        // path.timeGrid()[i+2]
                        return payoff_->cashPayoff() *
                            discountTS_->discount(path.timeGrid()[i+1]);
                    }
                }
                log_asset_price += x;
            }
            break;
          case Option::Put:
            for (i=0; i<n-1; i++) {
                x = std::log(path[i+1]/path[i]);
                // terminal or initial vol?
                // initial (timeGrid[i+1]) for the time being
                vol = diffProcess_->diffusion(timeGrid[i+1],
                                              std::exp(log_asset_price));
                // vol = diffProcess_->diffusion(timeGrid[i+2],
                //                               std::exp(log_asset_price+x));
                dt = timeGrid.dt(i);
                y = log_asset_price +
                    0.5*(x - std::sqrt(x*x - 2*vol*vol*dt*std::log(u[i])));
                if (y <= log_strike) {
                    if (exercise_->payoffAtExpiry()) {
                        return payoff_->cashPayoff() *
                            discountTS_->discount(path.timeGrid().back());
                    } else {
                        // the discount should be calculated at the exercise
                        // time between path.timeGrid()[i+1] and
                        // path.timeGrid()[i+2]
                        return payoff_->cashPayoff() *
                            discountTS_->discount(path.timeGrid()[i+1]);
                    }
                }
                log_asset_price += x;
            }
            break;
          default:
            QL_FAIL("unknown option type");
        }
        return 0.0;
    }
Member Data Documentation
boost::shared_ptr<StochasticProcess1D> QuantLib::DigitalPathPricer::diffProcess_ [private]
Definition at line 124 of file mcdigitalengine.hpp.
Referenced by operator()().
Handle<YieldTermStructure> QuantLib::DigitalPathPricer::discountTS_ [private]
Definition at line 126 of file mcdigitalengine.hpp.
Referenced by operator()().
boost::shared_ptr<AmericanExercise> QuantLib::DigitalPathPricer::exercise_ [private]
Definition at line 123 of file mcdigitalengine.hpp.
Referenced by operator()().
boost::shared_ptr<CashOrNothingPayoff> QuantLib::DigitalPathPricer::payoff_ [private]
Definition at line 122 of file mcdigitalengine.hpp.
Referenced by operator()().
PseudoRandom::ursg_type QuantLib::DigitalPathPricer::sequenceGen_ [private]
Definition at line 125 of file mcdigitalengine.hpp.
Referenced by operator()().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/vanilla/mcdigitalengine.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/vanilla/mcdigitalengine.cpp