QuantLib: QuantLib::BasisIncompleteOrdered Class Reference
QuantLib::BasisIncompleteOrdered Class Reference
#include <basisincompleteordered.hpp>
Public Member Functions
BasisIncompleteOrdered (Size euclideanDimension)
bool addVector (const Array &newVector)
return value indicates if the vector was linearly independent
Size basisSize () const
Size euclideanDimension () const
Matrix getBasisAsRowsInMatrix () const
Private Attributes
std::vector< Array > currentBasis_
Size euclideanDimension_
Array newVector_
Detailed Description
Definition at line 29 of file basisincompleteordered.hpp.
Constructor & Destructor Documentation
QuantLib::BasisIncompleteOrdered::BasisIncompleteOrdered (Size euclideanDimension)
Definition at line 25 of file basisincompleteordered.cpp.
        : euclideanDimension_(euclideanDimension) {}
Member Function Documentation
bool QuantLib::BasisIncompleteOrdered::addVector (const Array & newVector)
return value indicates if the vector was linearly independent
Definition at line 28 of file basisincompleteordered.cpp.
References currentBasis_, euclideanDimension_, QuantLib::dsd::inner_product(), newVector_, QuantLib::norm(), QL_REQUIRE, and QuantLib::Array::size().
Referenced by QuantLib::anonymous_namespace{capletcoterminalmaxhomogeneity.cpp}::singleRateClosestPointFinder().
{
        QL_REQUIRE(newVector1.size() == euclideanDimension_,
            "missized vector passed to "
            "BasisIncompleteOrdered::addVector");
        newVector_ = newVector1;
        if (currentBasis_.size()==euclideanDimension_)
            return false;
        for (Size j=0; j<currentBasis_.size(); ++j) {
            Real innerProd = std::inner_product(newVector_.begin(),
                newVector_.end(),
                currentBasis_[j].begin(), 0.0);
            for (Size k=0; k<euclideanDimension_; ++k)
                newVector_[k] -=innerProd*currentBasis_[j][k];
        }
        Real norm = std::sqrt(std::inner_product(newVector_.begin(),
            newVector_.end(),
            newVector_.begin(), 0.0));
        if (norm<1e-12) // maybe this should be a tolerance
            return false;
        for (Size l=0; l<euclideanDimension_; ++l)
            newVector_[l]/=norm;
        currentBasis_.push_back(newVector_);
        return true;
    }
Size QuantLib::BasisIncompleteOrdered::basisSize () const
Definition at line 63 of file basisincompleteordered.cpp.
References currentBasis_.
{
        return currentBasis_.size();
    }
Size QuantLib::BasisIncompleteOrdered::euclideanDimension () const
Definition at line 67 of file basisincompleteordered.cpp.
References euclideanDimension_.
{
        return euclideanDimension_;
    }
Matrix QuantLib::BasisIncompleteOrdered::getBasisAsRowsInMatrix () const
Definition at line 72 of file basisincompleteordered.cpp.
References currentBasis_, and euclideanDimension_.
Referenced by QuantLib::anonymous_namespace{capletcoterminalmaxhomogeneity.cpp}::singleRateClosestPointFinder().
{
        Matrix basis(currentBasis_.size(), euclideanDimension_);
        for (Size i=0; i<basis.rows(); ++i)
            for (Size j=0; j<basis.columns(); ++j)
                basis[i][j] = currentBasis_[i][j];
        return basis;
    }
Member Data Documentation
std::vector<Array> QuantLib::BasisIncompleteOrdered::currentBasis_ [private]
Definition at line 38 of file basisincompleteordered.hpp.
Referenced by addVector(), basisSize(), and getBasisAsRowsInMatrix().
Size QuantLib::BasisIncompleteOrdered::euclideanDimension_ [private]
Definition at line 39 of file basisincompleteordered.hpp.
Referenced by addVector(), euclideanDimension(), and getBasisAsRowsInMatrix().
Array QuantLib::BasisIncompleteOrdered::newVector_ [private]
Definition at line 40 of file basisincompleteordered.hpp.
Referenced by addVector().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/matrixutilities/basisincompleteordered.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/math/matrixutilities/basisincompleteordered.cpp