QuantLib: QuantLib::SabrSmileSection Class Reference
QuantLib::SabrSmileSection Class Reference
#include <sabrsmilesection.hpp>
Public Member Functions
SabrSmileSection (Time timeToExpiry, Rate forward, const std::vector< Real > &sabrParameters)
SabrSmileSection (const Date &d, Rate forward, const std::vector< Real > &sabrParameters, const DayCounter &dc=Actual365Fixed())
Real minStrike () const
Real maxStrike () const
Real atmLevel () const
Protected Member Functions
Real varianceImpl (Rate strike) const
Volatility volatilityImpl (Rate strike) const
Private Attributes
Real alpha_
Real beta_
Real nu_
Real rho_
Real forward_
Detailed Description
Definition at line 33 of file sabrsmilesection.hpp.
Constructor & Destructor Documentation
QuantLib::SabrSmileSection::SabrSmileSection (Time timeToExpiry, Rate forward, const std::vector< Real > & sabrParameters)
Definition at line 26 of file sabrsmilesection.cpp.
References alpha_, beta_, forward_, nu_, QL_REQUIRE, QuantLib::io::rate(), rho_, and QuantLib::validateSabrParameters().
    : SmileSection(timeToExpiry), forward_(forward) {
        alpha_ = sabrParams[0];
        beta_ = sabrParams[1];
        nu_ = sabrParams[2];
        rho_ = sabrParams[3];
        QL_REQUIRE(forward_>0.0, "at the money forward rate must be "
                   "positive: " << io::rate(forward_) << " not allowed");
        validateSabrParameters(alpha_, beta_, nu_, rho_);
    }
QuantLib::SabrSmileSection::SabrSmileSection (const Date & d, Rate forward, const std::vector< Real > & sabrParameters, const DayCounter & dc = Actual365Fixed())
Definition at line 41 of file sabrsmilesection.cpp.
References alpha_, beta_, forward_, nu_, QL_REQUIRE, QuantLib::io::rate(), rho_, and QuantLib::validateSabrParameters().
    : SmileSection(d, dc), forward_(forward) {
        alpha_ = sabrParams[0];
        beta_ = sabrParams[1];
        nu_ = sabrParams[2];
        rho_ = sabrParams[3];
        QL_REQUIRE(forward_>0.0, "at the money forward rate must be "
                   "positive: " << io::rate(forward_) << " not allowed");
        validateSabrParameters(alpha_, beta_, nu_, rho_);
    }
Member Function Documentation
Real QuantLib::SabrSmileSection::atmLevel () const [inline, virtual]
Implements QuantLib::SmileSection.
Definition at line 44 of file sabrsmilesection.hpp.
References forward_.
{ return forward_; }
Real QuantLib::SabrSmileSection::maxStrike () const [inline, virtual]
Implements QuantLib::SmileSection.
Definition at line 43 of file sabrsmilesection.hpp.
References QL_MAX_REAL.
{ return QL_MAX_REAL; }
Real QuantLib::SabrSmileSection::minStrike () const [inline, virtual]
Implements QuantLib::SmileSection.
Definition at line 42 of file sabrsmilesection.hpp.
{ return 0.0; }
Real QuantLib::SabrSmileSection::varianceImpl (Rate strike) const [protected, virtual]
Reimplemented from QuantLib::SmileSection.
Definition at line 57 of file sabrsmilesection.cpp.
References alpha_, beta_, QuantLib::SmileSection::exerciseTime(), forward_, nu_, rho_, and QuantLib::unsafeSabrVolatility().
{
        Volatility vol = unsafeSabrVolatility(strike, forward_,
            exerciseTime(), alpha_, beta_, nu_, rho_);
        return vol*vol*exerciseTime();
     }
Real QuantLib::SabrSmileSection::volatilityImpl (Rate strike) const [protected, virtual]
Implements QuantLib::SmileSection.
Definition at line 63 of file sabrsmilesection.cpp.
References alpha_, beta_, QuantLib::SmileSection::exerciseTime(), forward_, nu_, rho_, and QuantLib::unsafeSabrVolatility().
{
        return unsafeSabrVolatility(strike, forward_,
            exerciseTime(), alpha_, beta_, nu_, rho_);
     }
Member Data Documentation
Real QuantLib::SabrSmileSection::alpha_ [private]
Definition at line 49 of file sabrsmilesection.hpp.
Referenced by SabrSmileSection(), varianceImpl(), and volatilityImpl().
Real QuantLib::SabrSmileSection::beta_ [private]
Definition at line 49 of file sabrsmilesection.hpp.
Referenced by SabrSmileSection(), varianceImpl(), and volatilityImpl().
Real QuantLib::SabrSmileSection::forward_ [private]
Definition at line 49 of file sabrsmilesection.hpp.
Referenced by atmLevel(), SabrSmileSection(), varianceImpl(), and volatilityImpl().
Real QuantLib::SabrSmileSection::nu_ [private]
Definition at line 49 of file sabrsmilesection.hpp.
Referenced by SabrSmileSection(), varianceImpl(), and volatilityImpl().
Real QuantLib::SabrSmileSection::rho_ [private]
Definition at line 49 of file sabrsmilesection.hpp.
Referenced by SabrSmileSection(), varianceImpl(), and volatilityImpl().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/sabrsmilesection.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/sabrsmilesection.cpp