QuantLib: QuantLib::AmortizingFixedRateBond Class Reference
QuantLib::AmortizingFixedRateBond Class Reference
amortizing fixed-rate bond
#include <amortizingfixedratebond.hpp>
Public Member Functions
AmortizingFixedRateBond (Natural settlementDays, const std::vector< Real > &notionals, const Schedule &schedule, const std::vector< Rate > &coupons, const DayCounter &accrualDayCounter, BusinessDayConvention paymentConvention=Following, const Date &issueDate=Date())
AmortizingFixedRateBond (Natural settlementDays, const Calendar &calendar, Real faceAmount, const Date &startDate, const Period &bondTenor, const Frequency &sinkingFrequency, const Rate coupon, const DayCounter &accrualDayCounter, BusinessDayConvention paymentConvention=Following, const Date &issueDate=Date())
Frequency frequency () const
const DayCounter & dayCounter () const
Protected Attributes
Frequency frequency_
DayCounter dayCounter_
Detailed Description
amortizing fixed-rate bond
Definition at line 35 of file amortizingfixedratebond.hpp.
Constructor & Destructor Documentation
QuantLib::AmortizingFixedRateBond::AmortizingFixedRateBond (Natural settlementDays, const std::vector< Real > & notionals, const Schedule & schedule, const std::vector< Rate > & coupons, const DayCounter & accrualDayCounter, BusinessDayConvention paymentConvention = Following, const Date & issueDate = Date())
Definition at line 27 of file amortizingfixedratebond.cpp.
References QuantLib::Bond::addRedemptionsToCashflows(), QuantLib::Bond::cashflows(), QuantLib::Bond::cashflows_, QuantLib::Schedule::endDate(), QuantLib::Bond::maturityDate_, QL_ENSURE, QuantLib::FixedRateLeg::withCouponRates(), QuantLib::FixedRateLeg::withNotionals(), and QuantLib::FixedRateLeg::withPaymentAdjustment().
    : Bond(settlementDays, schedule.calendar(), issueDate),
      frequency_(schedule.tenor().frequency()),
      dayCounter_(accrualDayCounter) {
        maturityDate_ = schedule.endDate();
        cashflows_ = FixedRateLeg(schedule)
            .withNotionals(notionals)
            .withCouponRates(coupons, accrualDayCounter)
            .withPaymentAdjustment(paymentConvention);
        addRedemptionsToCashflows();
        QL_ENSURE(!cashflows().empty(), "bond with no cashflows!");
    }
QuantLib::AmortizingFixedRateBond::AmortizingFixedRateBond (Natural settlementDays, const Calendar & calendar, Real faceAmount, const Date & startDate, const Period & bondTenor, const Frequency & sinkingFrequency, const Rate coupon, const DayCounter & accrualDayCounter, BusinessDayConvention paymentConvention = Following, const Date & issueDate = Date())
Automatically generates a set of equal coupons, with an amortizing bond. The coupons are equal and the accrual daycount is only used for quoting/settlement purposes - not for calculating the coupons.
Definition at line 164 of file amortizingfixedratebond.cpp.
References QuantLib::Bond::addRedemptionsToCashflows(), QuantLib::Bond::cashflows_, QuantLib::Bond::maturityDate_, QuantLib::anonymous_namespace{amortizingfixedratebond.cpp}::sinkingNotionals(), QuantLib::anonymous_namespace{amortizingfixedratebond.cpp}::sinkingSchedule(), QuantLib::FixedRateLeg::withCouponRates(), QuantLib::FixedRateLeg::withNotionals(), and QuantLib::FixedRateLeg::withPaymentAdjustment().
    : Bond(settlementDays, calendar, issueDate),
      frequency_(sinkingFrequency),
      dayCounter_(accrualDayCounter) {
        maturityDate_ = startDate + bondTenor;
        cashflows_ =
            FixedRateLeg(sinkingSchedule(startDate, bondTenor,
                                         sinkingFrequency, calendar))
            .withNotionals(sinkingNotionals(bondTenor,
                                            sinkingFrequency, coupon,
                                            initialFaceAmount))
            .withCouponRates(coupon, accrualDayCounter)
            .withPaymentAdjustment(paymentConvention);
        addRedemptionsToCashflows();
    }
Member Function Documentation
const DayCounter& QuantLib::AmortizingFixedRateBond::dayCounter () const [inline]
Definition at line 62 of file amortizingfixedratebond.hpp.
References dayCounter_.
{ return dayCounter_; }
Frequency QuantLib::AmortizingFixedRateBond::frequency () const [inline]
Definition at line 61 of file amortizingfixedratebond.hpp.
References frequency_.
{ return frequency_; }
Member Data Documentation
DayCounter QuantLib::AmortizingFixedRateBond::dayCounter_ [protected]
Definition at line 65 of file amortizingfixedratebond.hpp.
Referenced by dayCounter().
Frequency QuantLib::AmortizingFixedRateBond::frequency_ [protected]
Definition at line 64 of file amortizingfixedratebond.hpp.
Referenced by frequency().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/amortizingbonds/amortizingfixedratebond.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/amortizingbonds/amortizingfixedratebond.cpp