QuantLib: QuantLib::CPISwap Class Reference
QuantLib::CPISwap Class Reference
zero-inflation-indexed swap,
#include <cpiswap.hpp>
Classes
class arguments
Arguments for swap calculation
class engine
class results
Results from swap calculation
Public Types
enum Type { Receiver = -1, Payer = 1 }
Public Member Functions
CPISwap (Type type, Real nominal, bool subtractInflationNominal, Spread spread, const DayCounter &floatDayCount, const Schedule &floatSchedule, const BusinessDayConvention &floatRoll, Natural fixingDays, const boost::shared_ptr< IborIndex > &floatIndex, Rate fixedRate, Real baseCPI, const DayCounter &fixedDayCount, const Schedule &fixedSchedule, const BusinessDayConvention &fixedRoll, const Period &observationLag, const boost::shared_ptr< ZeroInflationIndex > &fixedIndex, CPI::InterpolationType observationInterpolation=CPI::AsIndex, Real inflationNominal=Null< Real >())
virtual Real floatLegNPV () const
virtual Spread fairSpread () const
virtual Real fixedLegNPV () const
virtual Rate fairRate () const
virtual Type type () const
virtual Real nominal () const
virtual bool subtractInflationNominal () const
virtual Spread spread () const
virtual const DayCounter & floatDayCount () const
virtual const Schedule & floatSchedule () const
virtual const
BusinessDayConvention & floatPaymentRoll () const
virtual Natural fixingDays () const
virtual const
boost::shared_ptr< IborIndex > & floatIndex () const
virtual Rate fixedRate () const
virtual Real baseCPI () const
virtual const DayCounter & fixedDayCount () const
virtual const Schedule & fixedSchedule () const
virtual const
BusinessDayConvention & fixedPaymentRoll () const
virtual Period observationLag () const
virtual const
boost::shared_ptr
< ZeroInflationIndex > & fixedIndex () const
virtual CPI::InterpolationType observationInterpolation () const
virtual Real inflationNominal () const
virtual const Leg & cpiLeg () const
virtual const Leg & floatLeg () const
void setupArguments (PricingEngine::arguments *args) const
for simple case sufficient to copy base class
void fetchResults (const PricingEngine::results *) const
Private Member Functions
void setupExpired () const
Private Attributes
Type type_
Real nominal_
bool subtractInflationNominal_
Spread spread_
DayCounter floatDayCount_
Schedule floatSchedule_
BusinessDayConvention floatPaymentRoll_
Natural fixingDays_
boost::shared_ptr< IborIndex > floatIndex_
Rate fixedRate_
Real baseCPI_
DayCounter fixedDayCount_
Schedule fixedSchedule_
BusinessDayConvention fixedPaymentRoll_
boost::shared_ptr
< ZeroInflationIndex > fixedIndex_
Period observationLag_
CPI::InterpolationType observationInterpolation_
Real inflationNominal_
Spread fairSpread_
Rate fairRate_
Detailed Description
zero-inflation-indexed swap,
fixed x zero-inflation, i.e. fixed x CPI(i'th fixing)/CPI(base) versus floating + spread
Note that this does ony the inflation-vs-floating-leg. Extension to inflation-vs-fixed-leg. is simple - just replace the floating leg with a fixed leg.
Typically there are notional exchanges at the end: either inflated-notional vs notional; or just (inflated-notional - notional) vs zero. The latter is perhaphs more typical.
Warning:
Setting subtractInflationNominal to true means that the original inflation nominal is subtracted from both nominals before they are exchanged, even if they are different.
This swap can mimic a ZCIIS where [(1+q)^n - 1] is exchanged against (cpi ratio - 1), by using differnt nominals on each leg and setting subtractInflationNominal to true. ALSO - there must be just one date in each schedule.
The two legs can have different schedules, fixing (days vs lag), settlement, and roll conventions. N.B. accrual adjustment periods are already in the schedules. Trade date and swap settlement date are outside the scope of the instrument.
Definition at line 66 of file cpiswap.hpp.
Member Enumeration Documentation
enum QuantLib::CPISwap::Type
Enumerator:
Receiver
Payer
Definition at line 68 of file cpiswap.hpp.
{ Receiver = -1, Payer = 1 };
Constructor & Destructor Documentation
QuantLib::CPISwap::CPISwap (Type type, Real nominal, bool subtractInflationNominal, Spread spread, const DayCounter & floatDayCount, const Schedule & floatSchedule, const BusinessDayConvention & floatRoll, Natural fixingDays, const boost::shared_ptr< IborIndex > & floatIndex, Rate fixedRate, Real baseCPI, const DayCounter & fixedDayCount, const Schedule & fixedSchedule, const BusinessDayConvention & fixedRoll, const Period & observationLag, const boost::shared_ptr< ZeroInflationIndex > & fixedIndex, CPI::InterpolationType observationInterpolation = CPI::AsIndex, Real inflationNominal = Null<Real>())
Definition at line 40 of file cpiswap.cpp.
References QuantLib::Calendar::adjust(), baseCPI_, QuantLib::Schedule::calendar(), cpiLeg(), fixedDayCount_, fixedIndex_, fixedPaymentRoll_, fixedRate_, fixedSchedule_, fixingDays_, floatDayCount_, floatIndex_, floatPaymentRoll_, floatSchedule_, inflationNominal(), inflationNominal_, QuantLib::Swap::legs_, nominal_, observationInterpolation_, observationLag_, Payer, QuantLib::Swap::payer_, QL_REQUIRE, QuantLib::Observer::registerWith(), QuantLib::Schedule::size(), spread_, subtractInflationNominal_, type_, QuantLib::CPILeg::withFixedRates(), QuantLib::IborLeg::withFixingDays(), QuantLib::IborLeg::withNotionals(), QuantLib::CPILeg::withNotionals(), QuantLib::CPILeg::withObservationInterpolation(), QuantLib::IborLeg::withPaymentAdjustment(), QuantLib::CPILeg::withPaymentAdjustment(), QuantLib::IborLeg::withPaymentDayCounter(), QuantLib::CPILeg::withPaymentDayCounter(), QuantLib::IborLeg::withSpreads(), and QuantLib::CPILeg::withSubtractInflationNominal().
    : Swap(2), type_(type), nominal_(nominal), subtractInflationNominal_(subtractInflationNominal),
    spread_(spread), floatDayCount_(floatDayCount), floatSchedule_(floatSchedule),
    floatPaymentRoll_(floatPaymentRoll), fixingDays_(fixingDays),
    floatIndex_(floatIndex),
    fixedRate_(fixedRate), baseCPI_(baseCPI), fixedDayCount_(fixedDayCount), fixedSchedule_(fixedSchedule),
    fixedPaymentRoll_(fixedPaymentRoll), fixedIndex_(fixedIndex),
    observationLag_(observationLag),
    observationInterpolation_(observationInterpolation)
    {
        QL_REQUIRE(floatSchedule_.size()>0,"empty float schedule");
        QL_REQUIRE(fixedSchedule_.size()>0,"empty fixed schedule");
        // \todo if roll!=unadjusted then need calendars ...
        if (inflationNominal==Null<Real>()) inflationNominal_ = nominal_;
        else inflationNominal_ = inflationNominal;
        Leg floatingLeg;
        if (floatSchedule_.size() > 1) {
            floatingLeg = IborLeg(floatSchedule_, floatIndex_)
            .withNotionals(nominal_)
            .withSpreads(spread_)
            .withPaymentDayCounter(floatDayCount_)
            .withPaymentAdjustment(floatPaymentRoll_)
            .withFixingDays(fixingDays_);
        }
        if (floatSchedule_.size()==1 ||
            !subtractInflationNominal_ ||
            (subtractInflationNominal && fabs(nominal_-inflationNominal_)>0.00001)
            )
        {
            Date payNotional;
            if (floatSchedule_.size()==1) { // no coupons
                payNotional = floatSchedule_[0];
                payNotional = floatSchedule_.calendar().adjust(payNotional, floatPaymentRoll_);
            } else { // use the pay date of the last coupon
                payNotional = floatingLeg.back()->date();
            }
            Real floatAmount = subtractInflationNominal_ ? nominal_ - inflationNominal_ : nominal_;
            boost::shared_ptr<CashFlow> nf(new SimpleCashFlow(floatAmount, payNotional));
            floatingLeg.push_back(nf);
        }
        // a CPIleg know about zero legs and inclusion of base inflation notional
        Leg cpiLeg = CPILeg(fixedSchedule_, fixedIndex_,
                            baseCPI_, observationLag_)
        .withNotionals(inflationNominal_)
        .withFixedRates(fixedRate_)
        .withPaymentDayCounter(fixedDayCount_)
        .withPaymentAdjustment(fixedPaymentRoll_)
        .withObservationInterpolation(observationInterpolation_)
        .withSubtractInflationNominal(subtractInflationNominal_);
        Leg::const_iterator i;
        for (i = cpiLeg.begin(); i < cpiLeg.end(); ++i) {
            registerWith(*i);
        }
        for (i = floatingLeg.begin(); i < floatingLeg.end(); ++i) {
            registerWith(*i);
        }
        legs_[0] = cpiLeg;
        legs_[1] = floatingLeg;
        if (type_==Payer) {
            payer_[0] = 1.0;
            payer_[1] = -1.0;
        } else {
            payer_[0] = -1.0;
            payer_[1] = 1.0;
        }
    }
Member Function Documentation
Real QuantLib::CPISwap::baseCPI () const [inline, virtual]
Definition at line 207 of file cpiswap.hpp.
References baseCPI_.
{ return baseCPI_; }
const Leg & QuantLib::CPISwap::cpiLeg () const [inline, virtual]
Definition at line 216 of file cpiswap.hpp.
References QuantLib::Swap::legs_.
Referenced by CPISwapTest::consistency(), CPISwapTest::cpibondconsistency(), and CPISwap().
                                            {//inflation indexed
        return legs_[0];
    }
Rate QuantLib::CPISwap::fairRate () const [virtual]
Definition at line 152 of file cpiswap.cpp.
References QuantLib::Instrument::calculate(), fairRate_, and QL_REQUIRE.
Referenced by QuantLib::CPISwap::results::reset().
{
        calculate();
        QL_REQUIRE(fairRate_ != Null<Rate>(), "result not available");
        return fairRate_;
    }
Spread QuantLib::CPISwap::fairSpread () const [virtual]
Definition at line 158 of file cpiswap.cpp.
References QuantLib::Instrument::calculate(), fairSpread_, and QL_REQUIRE.
Referenced by QuantLib::CPISwap::results::reset().
{
        calculate();
        QL_REQUIRE(fairSpread_ != Null<Spread>(), "result not available");
        return fairSpread_;
    }
void QuantLib::CPISwap::fetchResults (const PricingEngine::results * r) const [virtual]
When a derived result structure is defined for an instrument, this method should be overridden to read from it. This is mandatory in case a pricing engine is used.
Reimplemented from QuantLib::Swap.
Definition at line 184 of file cpiswap.cpp.
References QuantLib::CPISwap::results::fairRate, fairRate_, QuantLib::CPISwap::results::fairSpread, fairSpread_, fixedRate_, QuantLib::Swap::legBPS_, QuantLib::Instrument::NPV_, and spread_.
{
        static const Spread basisPoint = 1.0e-4;
        // copy from VanillaSwap
        // works because similarly simple instrument
        // that we always expect to be priced with a swap engine
        Swap::fetchResults(r);
        const CPISwap::results* results = dynamic_cast<const CPISwap::results*>(r);
        if (results) { // might be a swap engine, so no error is thrown
            fairRate_ = results->fairRate;
            fairSpread_ = results->fairSpread;
        } else {
            fairRate_ = Null<Rate>();
            fairSpread_ = Null<Spread>();
        }
        if (fairRate_ == Null<Rate>()) {
            // calculate it from other results
            if (legBPS_[0] != Null<Real>())
                fairRate_ = fixedRate_ - NPV_/(legBPS_[0]/basisPoint);
        }
        if (fairSpread_ == Null<Spread>()) {
            // ditto
            if (legBPS_[1] != Null<Real>())
                fairSpread_ = spread_ - NPV_/(legBPS_[1]/basisPoint);
        }
    }
const DayCounter & QuantLib::CPISwap::fixedDayCount () const [inline, virtual]
Definition at line 208 of file cpiswap.hpp.
References fixedDayCount_.
{ return fixedDayCount_; }
const boost::shared_ptr< ZeroInflationIndex > & QuantLib::CPISwap::fixedIndex () const [inline, virtual]
Definition at line 212 of file cpiswap.hpp.
References fixedIndex_.
{ return fixedIndex_; }
Real QuantLib::CPISwap::fixedLegNPV () const [virtual]
Definition at line 165 of file cpiswap.cpp.
References QuantLib::Instrument::calculate(), QuantLib::Swap::legNPV_, and QL_REQUIRE.
                                    {//FIXME
        calculate();
        QL_REQUIRE(legNPV_[0] != Null<Real>(), "result not available");
        return legNPV_[0];
    }
const BusinessDayConvention & QuantLib::CPISwap::fixedPaymentRoll () const [inline, virtual]
Definition at line 210 of file cpiswap.hpp.
References fixedPaymentRoll_.
{ return fixedPaymentRoll_; }
Rate QuantLib::CPISwap::fixedRate () const [inline, virtual]
Definition at line 206 of file cpiswap.hpp.
References fixedRate_.
{ return fixedRate_; }
const Schedule & QuantLib::CPISwap::fixedSchedule () const [inline, virtual]
Definition at line 209 of file cpiswap.hpp.
References fixedSchedule_.
{ return fixedSchedule_; }
Natural QuantLib::CPISwap::fixingDays () const [inline, virtual]
Definition at line 202 of file cpiswap.hpp.
References fixingDays_.
{ return fixingDays_; }
const DayCounter & QuantLib::CPISwap::floatDayCount () const [inline, virtual]
Definition at line 199 of file cpiswap.hpp.
References floatDayCount_.
{ return floatDayCount_; }
const boost::shared_ptr< IborIndex > & QuantLib::CPISwap::floatIndex () const [inline, virtual]
Definition at line 203 of file cpiswap.hpp.
References floatIndex_.
{ return floatIndex_; }
const Leg & QuantLib::CPISwap::floatLeg () const [inline, virtual]
Definition at line 220 of file cpiswap.hpp.
References QuantLib::Swap::legs_.
{
        return legs_[1];
    }
Real QuantLib::CPISwap::floatLegNPV () const [virtual]
Definition at line 171 of file cpiswap.cpp.
References QuantLib::Instrument::calculate(), QuantLib::Swap::legNPV_, and QL_REQUIRE.
                                    {//FIXME
        calculate();
        QL_REQUIRE(legNPV_[1] != Null<Real>(), "result not available");
        return legNPV_[1];
    }
const BusinessDayConvention & QuantLib::CPISwap::floatPaymentRoll () const [inline, virtual]
Definition at line 201 of file cpiswap.hpp.
References floatPaymentRoll_.
{ return floatPaymentRoll_; }
const Schedule & QuantLib::CPISwap::floatSchedule () const [inline, virtual]
Definition at line 200 of file cpiswap.hpp.
References floatSchedule_.
{ return floatSchedule_; }
Real QuantLib::CPISwap::inflationNominal () const [inline, virtual]
Definition at line 214 of file cpiswap.hpp.
References inflationNominal_.
Referenced by CPISwap().
{ return inflationNominal_; }
Real QuantLib::CPISwap::nominal () const [inline, virtual]
Definition at line 194 of file cpiswap.hpp.
References nominal_.
{ return nominal_; }
CPI::InterpolationType QuantLib::CPISwap::observationInterpolation () const [inline, virtual]
Definition at line 213 of file cpiswap.hpp.
References observationInterpolation_.
{ return observationInterpolation_; }
Period QuantLib::CPISwap::observationLag () const [inline, virtual]
Definition at line 211 of file cpiswap.hpp.
References observationLag_.
{ return observationLag_; }
void QuantLib::CPISwap::setupArguments (PricingEngine::arguments * args) const [virtual]
for simple case sufficient to copy base class
Reimplemented from QuantLib::Swap.
Definition at line 141 of file cpiswap.cpp.
{
        Swap::setupArguments(args);
        CPISwap::arguments* arguments =
        dynamic_cast<CPISwap::arguments*>(args);
        if (!arguments) return; // it's a swap engine...
    }
void QuantLib::CPISwap::setupExpired () const [private, virtual]
This method must leave the instrument in a consistent state when the expiration condition is met.
Reimplemented from QuantLib::Swap.
Definition at line 177 of file cpiswap.cpp.
References fairRate_, fairSpread_, and QuantLib::Swap::legBPS_.
{
        Swap::setupExpired();
        legBPS_[0] = legBPS_[1] = 0.0;
        fairRate_ = Null<Rate>();
        fairSpread_ = Null<Spread>();
    }
Spread QuantLib::CPISwap::spread () const [inline, virtual]
Definition at line 198 of file cpiswap.hpp.
References spread_.
{ return spread_; }
bool QuantLib::CPISwap::subtractInflationNominal () const [inline, virtual]
Definition at line 195 of file cpiswap.hpp.
References subtractInflationNominal_.
{ return subtractInflationNominal_; }
CPISwap::Type QuantLib::CPISwap::type () const [inline, virtual]
Definition at line 193 of file cpiswap.hpp.
References type_.
{ return type_; }
Member Data Documentation
Real QuantLib::CPISwap::baseCPI_ [private]
Definition at line 152 of file cpiswap.hpp.
Referenced by baseCPI(), and CPISwap().
Rate QuantLib::CPISwap::fairRate_ [mutable, private]
Definition at line 162 of file cpiswap.hpp.
Referenced by fairRate(), fetchResults(), and setupExpired().
Spread QuantLib::CPISwap::fairSpread_ [mutable, private]
Definition at line 161 of file cpiswap.hpp.
Referenced by fairSpread(), fetchResults(), and setupExpired().
DayCounter QuantLib::CPISwap::fixedDayCount_ [private]
Definition at line 153 of file cpiswap.hpp.
Referenced by CPISwap(), and fixedDayCount().
boost::shared_ptr<ZeroInflationIndex> QuantLib::CPISwap::fixedIndex_ [private]
Definition at line 156 of file cpiswap.hpp.
Referenced by CPISwap(), and fixedIndex().
BusinessDayConvention QuantLib::CPISwap::fixedPaymentRoll_ [private]
Definition at line 155 of file cpiswap.hpp.
Referenced by CPISwap(), and fixedPaymentRoll().
Rate QuantLib::CPISwap::fixedRate_ [private]
Definition at line 151 of file cpiswap.hpp.
Referenced by CPISwap(), fetchResults(), and fixedRate().
Schedule QuantLib::CPISwap::fixedSchedule_ [private]
Definition at line 154 of file cpiswap.hpp.
Referenced by CPISwap(), and fixedSchedule().
Natural QuantLib::CPISwap::fixingDays_ [private]
Definition at line 147 of file cpiswap.hpp.
Referenced by CPISwap(), and fixingDays().
DayCounter QuantLib::CPISwap::floatDayCount_ [private]
Definition at line 144 of file cpiswap.hpp.
Referenced by CPISwap(), and floatDayCount().
boost::shared_ptr<IborIndex> QuantLib::CPISwap::floatIndex_ [private]
Definition at line 148 of file cpiswap.hpp.
Referenced by CPISwap(), and floatIndex().
BusinessDayConvention QuantLib::CPISwap::floatPaymentRoll_ [private]
Definition at line 146 of file cpiswap.hpp.
Referenced by CPISwap(), and floatPaymentRoll().
Schedule QuantLib::CPISwap::floatSchedule_ [private]
Definition at line 145 of file cpiswap.hpp.
Referenced by CPISwap(), and floatSchedule().
Real QuantLib::CPISwap::inflationNominal_ [private]
Definition at line 159 of file cpiswap.hpp.
Referenced by CPISwap(), and inflationNominal().
Real QuantLib::CPISwap::nominal_ [private]
Definition at line 139 of file cpiswap.hpp.
Referenced by CPISwap(), and nominal().
CPI::InterpolationType QuantLib::CPISwap::observationInterpolation_ [private]
Definition at line 158 of file cpiswap.hpp.
Referenced by CPISwap(), and observationInterpolation().
Period QuantLib::CPISwap::observationLag_ [private]
Definition at line 157 of file cpiswap.hpp.
Referenced by CPISwap(), and observationLag().
Spread QuantLib::CPISwap::spread_ [private]
Definition at line 143 of file cpiswap.hpp.
Referenced by CPISwap(), fetchResults(), and spread().
bool QuantLib::CPISwap::subtractInflationNominal_ [private]
Definition at line 140 of file cpiswap.hpp.
Referenced by CPISwap(), and subtractInflationNominal().
Type QuantLib::CPISwap::type_ [private]
Definition at line 138 of file cpiswap.hpp.
Referenced by CPISwap(), and type().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/cpiswap.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/cpiswap.cpp