QuantLib: QuantLib::ArithmeticAPOPathPricer Class Reference
QuantLib::ArithmeticAPOPathPricer Class Reference
#include <mc_discr_arith_av_price.hpp>
Public Member Functions
ArithmeticAPOPathPricer (Option::Type type, Real strike, DiscountFactor discount, Real runningSum=0.0, Size pastFixings=0)
Real operator() (const Path &path) const
Private Attributes
PlainVanillaPayoff payoff_
DiscountFactor discount_
Real runningSum_
Size pastFixings_
Detailed Description
Definition at line 79 of file mc_discr_arith_av_price.hpp.
Constructor & Destructor Documentation
QuantLib::ArithmeticAPOPathPricer::ArithmeticAPOPathPricer (Option::Type type, Real strike, DiscountFactor discount, Real runningSum = 0.0, Size pastFixings = 0)
Definition at line 26 of file mc_discr_arith_av_price.cpp.
References QL_REQUIRE.
    : payoff_(type, strike), discount_(discount),
      runningSum_(runningSum), pastFixings_(pastFixings) {
        QL_REQUIRE(strike>=0.0,
            "strike less than zero not allowed");
    }
Member Function Documentation
Real QuantLib::ArithmeticAPOPathPricer::operator() (const Path & path) const [virtual]
Implements QuantLib::PathPricer< Path >.
Definition at line 36 of file mc_discr_arith_av_price.cpp.
References QuantLib::Path::begin(), discount_, QuantLib::Path::end(), QuantLib::Path::length(), QuantLib::TimeGrid::mandatoryTimes(), pastFixings_, payoff_, QL_REQUIRE, runningSum_, and QuantLib::Path::timeGrid().
{
        Size n = path.length();
        QL_REQUIRE(n>1, "the path cannot be empty");
        Real sum;
        Size fixings;
        if (path.timeGrid().mandatoryTimes()[0]==0.0) {
            // include initial fixing
            sum = std::accumulate(path.begin(),path.end(),runningSum_);
            fixings = pastFixings_ + n;
        } else {
            sum = std::accumulate(path.begin()+1,path.end(),runningSum_);
            fixings = pastFixings_ + n - 1;
        }
        Real averagePrice = sum/fixings;
        return discount_ * payoff_(averagePrice);
    }
Member Data Documentation
DiscountFactor QuantLib::ArithmeticAPOPathPricer::discount_ [private]
Definition at line 89 of file mc_discr_arith_av_price.hpp.
Referenced by operator()().
Size QuantLib::ArithmeticAPOPathPricer::pastFixings_ [private]
Definition at line 91 of file mc_discr_arith_av_price.hpp.
Referenced by operator()().
PlainVanillaPayoff QuantLib::ArithmeticAPOPathPricer::payoff_ [private]
Definition at line 88 of file mc_discr_arith_av_price.hpp.
Referenced by operator()().
Real QuantLib::ArithmeticAPOPathPricer::runningSum_ [private]
Definition at line 90 of file mc_discr_arith_av_price.hpp.
Referenced by operator()().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/asian/mc_discr_arith_av_price.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/asian/mc_discr_arith_av_price.cpp