QuantLib: QuantLib::ForwardVanillaEngine< Engine > Class Template Reference
QuantLib::ForwardVanillaEngine< Engine > Class Template Reference
Forward engine for vanilla options
#include <forwardengine.hpp>
Public Member Functions
ForwardVanillaEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > &)
void calculate () const
Protected Member Functions
void setup () const
void getOriginalResults () const
Protected Attributes
boost::shared_ptr
< GeneralizedBlackScholesProcess > process_
boost::shared_ptr< Engine > originalEngine_
VanillaOption::arguments * originalArguments_
const VanillaOption::results * originalResults_
Detailed Description
template<class Engine>
class QuantLib::ForwardVanillaEngine< Engine >
Forward engine for vanilla options
Test:
the correctness of the returned value is tested by reproducing results available in literature.
the correctness of the returned greeks is tested by reproducing numerical derivatives.
Definition at line 48 of file forwardengine.hpp.
Constructor & Destructor Documentation
template<class Engine > QuantLib::ForwardVanillaEngine< Engine >::ForwardVanillaEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > & process)
Definition at line 68 of file forwardengine.hpp.
References QuantLib::ForwardVanillaEngine< Engine >::process_, and QuantLib::Observer::registerWith().
    : process_(process) {
        registerWith(process_);
    }
Member Function Documentation
template<class Engine > void QuantLib::ForwardVanillaEngine< Engine >::calculate () const [virtual]
Implements QuantLib::PricingEngine.
Reimplemented in QuantLib::ForwardPerformanceVanillaEngine< Engine >.
Definition at line 134 of file forwardengine.hpp.
References anonymous_namespace{inflationvolatility.cpp}::setup().
{
        setup();
        originalEngine_->calculate();
        getOriginalResults();
    }
template<class Engine > void QuantLib::ForwardVanillaEngine< Engine >::getOriginalResults () const [protected]
Reimplemented in QuantLib::ForwardPerformanceVanillaEngine< Engine >.
Definition at line 141 of file forwardengine.hpp.
References QuantLib::Continuous, QuantLib::NoFrequency, and QuantLib::DayCounter::yearFraction().
{
        DayCounter rfdc = process_->riskFreeRate()->dayCounter();
        DayCounter divdc = process_->dividendYield()->dayCounter();
        Time resetTime = rfdc.yearFraction(
                                     process_->riskFreeRate()->referenceDate(),
                                     this->arguments_.resetDate);
        DiscountFactor discQ = process_->dividendYield()->discount(
                                                  this->arguments_.resetDate);
        this->results_.value = discQ * originalResults_->value;
        // I need the strike derivative here ...
        this->results_.delta = discQ * (originalResults_->delta +
            this->arguments_.moneyness * originalResults_->strikeSensitivity);
        this->results_.gamma = 0.0;
        this->results_.theta = process_->dividendYield()->
            zeroRate(this->arguments_.resetDate, divdc, Continuous, NoFrequency)
            * this->results_.value;
        this->results_.vega  = discQ * originalResults_->vega;
        this->results_.rho   = discQ *  originalResults_->rho;
        this->results_.dividendRho = - resetTime * this->results_.value
            + discQ * originalResults_->dividendRho;
    }
template<class Engine > void QuantLib::ForwardVanillaEngine< Engine >::setup () const [protected]
Definition at line 76 of file forwardengine.hpp.
References QL_REQUIRE.
{
        boost::shared_ptr<StrikedTypePayoff> argumentsPayoff =
            boost::dynamic_pointer_cast<StrikedTypePayoff>(
                this->arguments_.payoff);
        QL_REQUIRE(argumentsPayoff, "wrong payoff given");
        boost::shared_ptr<StrikedTypePayoff> payoff(
                   new PlainVanillaPayoff(argumentsPayoff->optionType(),
                                          this->arguments_.moneyness *
                                          process_->x0()));
        // maybe the forward value is "better", in some fashion
        // the right level is needed in order to interpolate
        // the vol
        Handle<Quote> spot = process_->stateVariable();
        QL_REQUIRE(spot->value() >= 0.0, "negative or null underlting given");
        Handle<YieldTermStructure> dividendYield(
            boost::shared_ptr<YieldTermStructure>(
               new ImpliedTermStructure(process_->dividendYield(),
                                        this->arguments_.resetDate)));
        Handle<YieldTermStructure> riskFreeRate(
            boost::shared_ptr<YieldTermStructure>(
               new ImpliedTermStructure(process_->riskFreeRate(),
                                        this->arguments_.resetDate)));
        // The following approach is ok if the vol is at most
        // time dependant. It is plain wrong if it is asset dependant.
        // In the latter case the right solution would be stochastic
        // volatility or at least local volatility (which unfortunately
        // implies an unrealistic time-decreasing smile)
        Handle<BlackVolTermStructure> blackVolatility(
            boost::shared_ptr<BlackVolTermStructure>(
                new ImpliedVolTermStructure(process_->blackVolatility(),
                                            this->arguments_.resetDate)));
        boost::shared_ptr<GeneralizedBlackScholesProcess> fwdProcess(
                       new GeneralizedBlackScholesProcess(spot, dividendYield,
                                                          riskFreeRate,
                                                          blackVolatility));
        originalEngine_ = boost::shared_ptr<Engine>(new Engine(fwdProcess));
        originalArguments_ =
            dynamic_cast<VanillaOption::arguments*>(
                                             originalEngine_->getArguments());
        QL_REQUIRE(originalArguments_, "wrong engine type");
        originalResults_ =
            dynamic_cast<const VanillaOption::results*>(
                                               originalEngine_->getResults());
        QL_REQUIRE(originalResults_, "wrong engine type");
        originalArguments_->payoff = payoff;
        originalArguments_->exercise = this->arguments_.exercise;
        originalArguments_->validate();
    }
Member Data Documentation
template<class Engine > VanillaOption::arguments* QuantLib::ForwardVanillaEngine< Engine >::originalArguments_ [mutable, protected]
Definition at line 60 of file forwardengine.hpp.
template<class Engine > boost::shared_ptr<Engine> QuantLib::ForwardVanillaEngine< Engine >::originalEngine_ [mutable, protected]
Definition at line 59 of file forwardengine.hpp.
template<class Engine > const VanillaOption::results* QuantLib::ForwardVanillaEngine< Engine >::originalResults_ [mutable, protected]
Definition at line 61 of file forwardengine.hpp.
template<class Engine > boost::shared_ptr<GeneralizedBlackScholesProcess> QuantLib::ForwardVanillaEngine< Engine >::process_ [protected]
Definition at line 58 of file forwardengine.hpp.
Referenced by QuantLib::ForwardVanillaEngine< Engine >::ForwardVanillaEngine().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/forward/forwardengine.hpp