QuantLib: QuantLib::HullWhite Class Reference
QuantLib::HullWhite Class Reference
Single-factor Hull-White (extended Vasicek) model class.
#include <hullwhite.hpp>
Classes
class Dynamics
Short-rate dynamics in the Hull-White model.
class FittingParameter
Analytical term-structure fitting parameter \(\varphi(t) \).
Public Member Functions
HullWhite (const Handle< YieldTermStructure > &termStructure, Real a=0.1, Real sigma=0.01)
boost::shared_ptr< Lattice > tree (const TimeGrid &grid) const
Return by default a trinomial recombining tree.
boost::shared_ptr
< ShortRateDynamics > dynamics () const
returns the short-rate dynamics
Real discountBondOption (Option::Type type, Real strike, Time maturity, Time bondMaturity) const
Static Public Member Functions
static Rate convexityBias (Real futurePrice, Time t, Time T, Real sigma, Real a)
Protected Member Functions
void generateArguments ()
Real A (Time t, Time T) const
Private Attributes
Parameter phi_
Detailed Description
Single-factor Hull-White (extended Vasicek) model class.
This class implements the standard single-factor Hull-White model defined by
\[ dr_t = (\theta(t) - \alpha r_t)dt + \sigma dW_t \]
where \(\alpha \) and \(\sigma \) are constants.
Test:
calibration results are tested against cached values
Bug:
When the term structure is relinked, the r0 parameter of the underlying Vasicek model is not updated.
Definition at line 48 of file hullwhite.hpp.
Constructor & Destructor Documentation
QuantLib::HullWhite::HullWhite (const Handle< YieldTermStructure > & termStructure, Real a = 0.1, Real sigma = 0.01)
Definition at line 28 of file hullwhite.cpp.
References QuantLib::Vasicek::b_, generateArguments(), QuantLib::Vasicek::lambda_, and QuantLib::Observer::registerWith().
    : Vasicek(termStructure->forwardRate(0.0, 0.0, Continuous, NoFrequency),
                                         a, 0.0, sigma, 0.0),
      TermStructureConsistentModel(termStructure) {
        b_ = NullParameter();
        lambda_ = NullParameter();
        generateArguments();
        registerWith(termStructure);
    }
Member Function Documentation
Real QuantLib::HullWhite::A (Time t, Time T) const [protected, virtual]
Reimplemented from QuantLib::Vasicek.
Definition at line 72 of file hullwhite.cpp.
References QuantLib::Vasicek::B(), QuantLib::Continuous, QuantLib::NoFrequency, QuantLib::Vasicek::sigma(), QuantLib::TermStructureConsistentModel::termStructure(), and QuantLib::CalibratedModel::value().
{
        DiscountFactor discount1 = termStructure()->discount(t);
        DiscountFactor discount2 = termStructure()->discount(T);
        Rate forward = termStructure()->forwardRate(t, t,
                                                    Continuous, NoFrequency);
        Real temp = sigma()*B(t,T);
        Real value = B(t,T)*forward - 0.25*temp*temp*B(0.0,2.0*t);
        return std::exp(value)*discount2/discount1;
    }
Rate QuantLib::HullWhite::convexityBias (Real futurePrice, Time t, Time T, Real sigma, Real a) [static]
Futures convexity bias (i.e., the difference between futures implied rate and forward rate) calculated as in G. Kirikos, D. Novak, "Convexity Conundrums", Risk Magazine, March 1997.
Note:
t and T should be expressed in yearfraction using deposit day counter, F_quoted is futures' market price.
Definition at line 104 of file hullwhite.cpp.
References QuantLib::Vasicek::lambda(), QuantLib::anonymous_namespace{bjerksundstenslandengine.cpp}::phi(), QL_REQUIRE, and anonymous_namespace{quantlibbenchmark.cpp}::t.
Referenced by ShortRateModelTest::testFuturesConvexityBias(), and QuantLib::FuturesConvAdjustmentQuote::value().
{
        QL_REQUIRE(futuresPrice>=0.0,
            "negative futures price (" << futuresPrice << ") not allowed");
        QL_REQUIRE(t>=0.0,
            "negative t (" << t << ") not allowed");
        QL_REQUIRE(T>=t,
            "T (" << T << ") must not be less than t (" << t << ")");
        QL_REQUIRE(sigma>=0.0,
            "negative sigma (" << sigma << ") not allowed");
        QL_REQUIRE(a>=0.0,
            "negative a (" << a << ") not allowed");
        Time deltaT = (T-t);
        Real tempDeltaT = (1.-std::exp(-a*deltaT)) / a;
        Real halfSigmaSquare = sigma*sigma/2.0;
        // lambda adjusts for the fact that the underlying is an interest rate
        Real lambda = halfSigmaSquare * (1.-std::exp(-2.0*a*t)) / a *
            tempDeltaT * tempDeltaT;
        Real tempT = (1.0 - std::exp(-a*t)) / a;
        // phi is the MtM adjustment
        Real phi = halfSigmaSquare * tempDeltaT * tempT * tempT;
        // the adjustment
        Real z = lambda + phi;
        Rate futureRate = (100.0-futuresPrice)/100.0;
        return (1.0-std::exp(-z)) * (futureRate + 1.0/(T-t));
    }
Real QuantLib::HullWhite::discountBondOption (Option::Type type, Real strike, Time maturity, Time bondMaturity) const [virtual]
Reimplemented from QuantLib::Vasicek.
Definition at line 86 of file hullwhite.cpp.
References QuantLib::Vasicek::a(), QuantLib::Vasicek::B(), QuantLib::blackFormula(), anonymous_namespace{interpolations.cpp}::f(), QL_EPSILON, QuantLib::Vasicek::sigma(), QuantLib::TermStructureConsistentModel::termStructure(), and anonymous_namespace{perturbativebarrieroptionengine.cpp}::v().
{
        Real _a = a();
        Real v;
        if (_a < std::sqrt(QL_EPSILON)) {
            v = sigma()*B(maturity, bondMaturity)* std::sqrt(maturity);
        } else {
            v = sigma()*B(maturity, bondMaturity)*
                std::sqrt(0.5*(1.0 - std::exp(-2.0*_a*maturity))/_a);
        }
        Real f = termStructure()->discount(bondMaturity);
        Real k = termStructure()->discount(maturity)*strike;
        return blackFormula(type, k, f, v);
    }
boost::shared_ptr< OneFactorModel::ShortRateDynamics > QuantLib::HullWhite::dynamics () const [inline, virtual]
returns the short-rate dynamics
Reimplemented from QuantLib::Vasicek.
Definition at line 154 of file hullwhite.hpp.
References QuantLib::Vasicek::a(), phi_, and QuantLib::Vasicek::sigma().
{
        return boost::shared_ptr<ShortRateDynamics>(
                                            new Dynamics(phi_, a(), sigma()));
    }
void QuantLib::HullWhite::generateArguments () [protected, virtual]
Reimplemented from QuantLib::CalibratedModel.
Definition at line 82 of file hullwhite.cpp.
References QuantLib::Vasicek::a(), phi_, QuantLib::Vasicek::sigma(), and QuantLib::TermStructureConsistentModel::termStructure().
Referenced by HullWhite().
{
        phi_ = FittingParameter(termStructure(), a(), sigma());
    }
boost::shared_ptr< Lattice > QuantLib::HullWhite::tree (const TimeGrid & grid) const [virtual]
Return by default a trinomial recombining tree.
Reimplemented from QuantLib::OneFactorModel.
Definition at line 40 of file hullwhite.cpp.
References QuantLib::Vasicek::a(), QuantLib::OneFactorAffineModel::discountBond(), QuantLib::anonymous_namespace{yieldtermstructure.cpp}::dt, QuantLib::Parameter::implementation(), QuantLib::anonymous_namespace{bjerksundstenslandengine.cpp}::phi(), QuantLib::TermStructureFittingParameter::NumericalImpl::reset(), QuantLib::Vasicek::sigma(), QuantLib::Array::size(), QuantLib::TimeGrid::size(), QuantLib::TermStructureConsistentModel::termStructure(), and QuantLib::CalibratedModel::value().
{
        TermStructureFittingParameter phi(termStructure());
        boost::shared_ptr<ShortRateDynamics> numericDynamics(
                                             new Dynamics(phi, a(), sigma()));
        boost::shared_ptr<TrinomialTree> trinomial(
                         new TrinomialTree(numericDynamics->process(), grid));
        boost::shared_ptr<ShortRateTree> numericTree(
                         new ShortRateTree(trinomial, numericDynamics, grid));
        typedef TermStructureFittingParameter::NumericalImpl NumericalImpl;
        boost::shared_ptr<NumericalImpl> impl =
            boost::dynamic_pointer_cast<NumericalImpl>(phi.implementation());
        impl->reset();
        for (Size i=0; i<(grid.size() - 1); i++) {
            Real discountBond = termStructure()->discount(grid[i+1]);
            const Array& statePrices = numericTree->statePrices(i);
            Size size = numericTree->size(i);
            Time dt = numericTree->timeGrid().dt(i);
            Real dx = trinomial->dx(i);
            Real x = trinomial->underlying(i,0);
            Real value = 0.0;
            for (Size j=0; j<size; j++) {
                value += statePrices[j]*std::exp(-x*dt);
                x += dx;
            }
            value = std::log(value/discountBond)/dt;
            impl->set(grid[i], value);
        }
        return numericTree;
    }
Member Data Documentation
Parameter QuantLib::HullWhite::phi_ [private]
Definition at line 82 of file hullwhite.hpp.
Referenced by dynamics(), and generateArguments().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/shortrate/onefactormodels/hullwhite.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/shortrate/onefactormodels/hullwhite.cpp