QuantLib: QuantLib::CMSMMDriftCalculator Class Reference
QuantLib::CMSMMDriftCalculator Class Reference
Drift computation for CMS market models.
#include <cmsmmdriftcalculator.hpp>
Public Member Functions
CMSMMDriftCalculator (const Matrix &pseudo, const std::vector< Spread > &displacements, const std::vector< Time > &taus, Size numeraire, Size alive, Size spanningFwds)
void compute (const CMSwapCurveState &cs, std::vector< Real > &drifts) const
Computes the drifts.
Private Attributes
Size numberOfRates_
Size numberOfFactors_
bool isFullFactor_
Size numeraire_
Size alive_
std::vector< Spread > displacements_
std::vector< Real > oneOverTaus_
Matrix C_
Matrix pseudo_
std::vector< Real > tmp_
Matrix PjPnWk_
Matrix wkaj_
Matrix wkajN_
std::vector< Size > downs_
std::vector< Size > ups_
Size spanningFwds_
Detailed Description
Drift computation for CMS market models.
Returns the drift \(\mu \Delta t \). See Mark Joshi, Rapid Computation of Drifts in a Reduced Factor Libor Market Model, Wilmott Magazine, May 2003.
Definition at line 42 of file cmsmmdriftcalculator.hpp.
Constructor & Destructor Documentation
QuantLib::CMSMMDriftCalculator::CMSMMDriftCalculator (const Matrix & pseudo, const std::vector< Spread > & displacements, const std::vector< Time > & taus, Size numeraire, Size alive, Size spanningFwds)
Definition at line 27 of file cmsmmdriftcalculator.cpp.
References alive_, C_, QuantLib::Matrix::columns(), downs_, numberOfRates_, numeraire_, oneOverTaus_, pseudo_, QL_REQUIRE, QuantLib::Matrix::rows(), QuantLib::transpose(), and ups_.
    : numberOfRates_(taus.size()), numberOfFactors_(pseudo.columns()),
      isFullFactor_(numberOfFactors_==numberOfRates_ ? true : false),
      numeraire_(numeraire), alive_(alive),
      displacements_(displacements), oneOverTaus_(taus.size()),
      pseudo_(pseudo), tmp_(taus.size(), 0.0),
      PjPnWk_(numberOfFactors_,1+taus.size()),
      wkaj_(numberOfFactors_, taus.size()),
      wkajN_(numberOfFactors_, taus.size()),
      downs_(taus.size()), ups_(taus.size()),
      spanningFwds_(spanningFwds) {
        // Check requirements
        QL_REQUIRE(numberOfRates_>0, "Dim out of range");
        QL_REQUIRE(displacements.size() == numberOfRates_,
                   "Displacements out of range");
        QL_REQUIRE(pseudo.rows()==numberOfRates_,
                   "pseudo.rows() not consistent with dim");
        QL_REQUIRE(pseudo.columns()>0 && pseudo.columns()<=numberOfRates_,
                   "pseudo.rows() not consistent with pseudo.columns()");
        QL_REQUIRE(alive<numberOfRates_,
                   "Alive out of bounds");
        QL_REQUIRE(numeraire_<=numberOfRates_,
                   "Numeraire larger than dim");
        QL_REQUIRE(numeraire_>=alive,
                   "Numeraire smaller than alive");
        // Precompute 1/taus
        for (Size i=0; i<taus.size(); ++i)
            oneOverTaus_[i] = 1.0/taus[i];
        // Compute covariance matrix from pseudoroot
        const Disposable<Matrix> pT = transpose(pseudo_);
        C_ = pseudo_*pT;
        // Compute lower and upper extrema for (non reduced) drift calculation
        for (Size i=alive_; i<numberOfRates_; ++i) {
            downs_[i] = std::min(i+1, numeraire_);
            ups_[i]   = std::max(i+1, numeraire_);
        }
    }
Member Function Documentation
void QuantLib::CMSMMDriftCalculator::compute (const CMSwapCurveState & cs, std::vector< Real > & drifts) const
Computes the drifts.
Definition at line 75 of file cmsmmdriftcalculator.cpp.
References alive_, QuantLib::CMSwapCurveState::cmSwapAnnuity(), QuantLib::CMSwapCurveState::cmSwapRate(), QuantLib::CMSwapCurveState::discountRatio(), displacements_, numberOfFactors_, QuantLib::CurveState::numberOfRates(), numberOfRates_, numeraire_, PjPnWk_, pseudo_, QL_REQUIRE, QuantLib::CurveState::rateTaus(), QuantLib::Matrix::rows(), spanningFwds_, wkaj_, and wkajN_.
Referenced by CurveStatesTest::testCMSwapCurveState().
{
        #if defined(QL_EXTRA_SAFETY_CHECKS)
        QL_REQUIRE(drifts.size()==cs.numberOfRates(),
                   "drifts.size() <> numberOfRates");
        #endif
        const std::vector<Time>& taus = cs.rateTaus();
        // final bond is numeraire
        // Compute cross variations
        for (Size k=0; k<PjPnWk_.rows(); ++k) {
            PjPnWk_[k][numberOfRates_]=0.0;
            wkaj_[k][numberOfRates_-1]=0.0;
            for (Integer j=static_cast<Integer>(numberOfRates_)-2;
                 j>=static_cast<Integer>(alive_)-1; --j)
            {
                double sr = cs.cmSwapRate(j+1,spanningFwds_);
                Integer endIndex = std::min(j+spanningFwds_+1,numberOfRates_);
                Real first = sr * wkaj_[k][j+1];
                Real second = cs.cmSwapAnnuity(numberOfRates_,j+1,spanningFwds_)
                * (sr+displacements_[j+1])
                *pseudo_[j+1][k];
                Real third = PjPnWk_[k][endIndex];
                PjPnWk_[k][j+1] = first
                + second
                + third;
                if (j>=static_cast<Integer>(alive_))
                {
                    wkaj_[k][j] = wkaj_[k][j+1] + PjPnWk_[k][j+1]*taus[j];
                    if (j+spanningFwds_+1 <= numberOfRates_)
                        wkaj_[k][j] -= PjPnWk_[k][endIndex]*taus[endIndex-1];
                }
            }
        }
        Real PnOverPN = cs.discountRatio(numberOfRates_, numeraire_);
        //Real PnOverPN = 1.0;
        for (Size j=alive_; j<numberOfRates_; ++j)
            for (Size k=0; k<numberOfFactors_; ++k)
                wkajN_[k][j] =  wkaj_[k][j]*PnOverPN
                    -PjPnWk_[k][numeraire_]*PnOverPN*cs.cmSwapAnnuity(numeraire_,j,spanningFwds_);
        for (Size j=alive_; j<numberOfRates_; ++j)
        {
            drifts[j]=0.0;
            for (Size k=0; k<numberOfFactors_; ++k)
            {
                drifts[j] += pseudo_[j][k]*wkajN_[k][j];
            }
            drifts[j] /= -cs.cmSwapAnnuity(numeraire_,j,spanningFwds_);
        }
    }
Member Data Documentation
Size QuantLib::CMSMMDriftCalculator::alive_ [private]
Definition at line 56 of file cmsmmdriftcalculator.hpp.
Referenced by CMSMMDriftCalculator(), and compute().
Matrix QuantLib::CMSMMDriftCalculator::C_ [private]
Definition at line 59 of file cmsmmdriftcalculator.hpp.
Referenced by CMSMMDriftCalculator().
std::vector<Spread> QuantLib::CMSMMDriftCalculator::displacements_ [private]
Definition at line 57 of file cmsmmdriftcalculator.hpp.
Referenced by compute().
std::vector<Size> QuantLib::CMSMMDriftCalculator::downs_ [private]
Definition at line 66 of file cmsmmdriftcalculator.hpp.
Referenced by CMSMMDriftCalculator().
bool QuantLib::CMSMMDriftCalculator::isFullFactor_ [private]
Definition at line 55 of file cmsmmdriftcalculator.hpp.
Size QuantLib::CMSMMDriftCalculator::numberOfFactors_ [private]
Definition at line 54 of file cmsmmdriftcalculator.hpp.
Referenced by compute().
Size QuantLib::CMSMMDriftCalculator::numberOfRates_ [private]
Definition at line 54 of file cmsmmdriftcalculator.hpp.
Referenced by CMSMMDriftCalculator(), and compute().
Size QuantLib::CMSMMDriftCalculator::numeraire_ [private]
Definition at line 56 of file cmsmmdriftcalculator.hpp.
Referenced by CMSMMDriftCalculator(), and compute().
std::vector<Real> QuantLib::CMSMMDriftCalculator::oneOverTaus_ [private]
Definition at line 58 of file cmsmmdriftcalculator.hpp.
Referenced by CMSMMDriftCalculator().
Matrix QuantLib::CMSMMDriftCalculator::PjPnWk_ [mutable, private]
Definition at line 62 of file cmsmmdriftcalculator.hpp.
Referenced by compute().
Matrix QuantLib::CMSMMDriftCalculator::pseudo_ [private]
Definition at line 59 of file cmsmmdriftcalculator.hpp.
Referenced by CMSMMDriftCalculator(), and compute().
Size QuantLib::CMSMMDriftCalculator::spanningFwds_ [private]
Definition at line 67 of file cmsmmdriftcalculator.hpp.
Referenced by compute().
std::vector<Real> QuantLib::CMSMMDriftCalculator::tmp_ [mutable, private]
Definition at line 61 of file cmsmmdriftcalculator.hpp.
std::vector<Size> QuantLib::CMSMMDriftCalculator::ups_ [private]
Definition at line 66 of file cmsmmdriftcalculator.hpp.
Referenced by CMSMMDriftCalculator().
Matrix QuantLib::CMSMMDriftCalculator::wkaj_ [mutable, private]
Definition at line 63 of file cmsmmdriftcalculator.hpp.
Referenced by compute().
Matrix QuantLib::CMSMMDriftCalculator::wkajN_ [mutable, private]
Definition at line 64 of file cmsmmdriftcalculator.hpp.
Referenced by compute().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/driftcomputation/cmsmmdriftcalculator.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/driftcomputation/cmsmmdriftcalculator.cpp