QuantLib: QuantLib::Quantity Class Reference
QuantLib::Quantity Class Reference
Amount of a commodity.
#include <quantity.hpp>
Public Member Functions
Constructors
Quantity ()
Quantity (const CommodityType &commodityType, const UnitOfMeasure &unitOfMeasure, Real amount)
Inspectors
const CommodityType & commodityType () const
const UnitOfMeasure & unitOfMeasure () const
Real amount () const
Quantity rounded () const
Quantity arithmetics
See below for non-member functions and for settings which determine the behavior of the operators.
Quantity operator+ () const
Quantity operator- () const
Quantity & operator+= (const Quantity &)
Quantity & operator-= (const Quantity &)
Quantity & operator*= (Real)
Quantity & operator/= (Real)
Private Attributes
CommodityType commodityType_
UnitOfMeasure unitOfMeasure_
Real amount_
Friends
std::ostream & operator<< (std::ostream &, const Quantity &)
Related Functions
(Note that these are not member functions.)
Quantity operator+ (const Quantity &, const Quantity &)
Quantity operator- (const Quantity &, const Quantity &)
Quantity operator* (const Quantity &, Real)
Quantity operator* (Real, const Quantity &)
Quantity operator/ (const Quantity &, Real)
Real operator/ (const Quantity &, const Quantity &)
bool operator== (const Quantity &, const Quantity &)
bool operator!= (const Quantity &, const Quantity &)
bool operator< (const Quantity &, const Quantity &)
bool operator<= (const Quantity &, const Quantity &)
bool operator> (const Quantity &, const Quantity &)
bool operator>= (const Quantity &, const Quantity &)
bool close (const Quantity &, const Quantity &, Size n=42)
bool close_enough (const Quantity &, const Quantity &, Size n=42)
Conversion settings
These parameters are used for combining quantity amounts in different currencies
enum ConversionType { NoConversion, BaseUnitOfMeasureConversion, AutomatedConversion }
static ConversionType conversionType = Quantity::NoConversion
static UnitOfMeasure baseUnitOfMeasure = UnitOfMeasure()
Detailed Description
Amount of a commodity.
Definition at line 33 of file quantity.hpp.
Member Enumeration Documentation
enum QuantLib::Quantity::ConversionType
Enumerator:
NoConversion
do not perform conversions
BaseUnitOfMeasureConversion
convert both operands to the base unitOfMeasure before converting
AutomatedConversion
return the result in the unitOfMeasure of the first operand
Definition at line 68 of file quantity.hpp.
{
            NoConversion,
            BaseUnitOfMeasureConversion,
            AutomatedConversion
        };
Constructor & Destructor Documentation
QuantLib::Quantity::Quantity () [inline]
Definition at line 125 of file quantity.hpp.
Referenced by operator-(), and rounded().
    : amount_(0.0) {}
QuantLib::Quantity::Quantity (const CommodityType & commodityType, const UnitOfMeasure & unitOfMeasure, Real amount) [inline]
Definition at line 128 of file quantity.hpp.
    : commodityType_(commodityType), unitOfMeasure_(unitOfMeasure),
      amount_(amount) {}
Member Function Documentation
Real QuantLib::Quantity::amount () const [inline]
Definition at line 142 of file quantity.hpp.
References amount_.
Referenced by QuantLib::close(), QuantLib::close_enough(), QuantLib::UnitOfMeasureConversion::convert(), QuantLib::operator/(), QuantLib::operator<(), QuantLib::operator<=(), QuantLib::operator==(), QuantLib::EnergyFuture::performCalculations(), and QuantLib::EnergySwap::quantity().
{
        return amount_;
    }
const CommodityType & QuantLib::Quantity::commodityType () const [inline]
Definition at line 134 of file quantity.hpp.
References commodityType_.
Referenced by QuantLib::UnitOfMeasureConversion::convert(), QuantLib::anonymous_namespace{quantity.cpp}::convertTo(), and QuantLib::EnergyFuture::performCalculations().
{
        return commodityType_;
    }
Quantity & QuantLib::Quantity::operator*= (Real x) [inline]
Definition at line 160 of file quantity.hpp.
References amount_.
{
        amount_ *= x;
        return *this;
    }
Quantity QuantLib::Quantity::operator+ () const [inline]
Definition at line 152 of file quantity.hpp.
{
        return *this;
    }
Quantity & QuantLib::Quantity::operator+= (const Quantity & m)
Definition at line 50 of file quantity.cpp.
References amount_, AutomatedConversion, BaseUnitOfMeasureConversion, conversionType, QuantLib::anonymous_namespace{quantity.cpp}::convertTo(), QuantLib::anonymous_namespace{quantity.cpp}::convertToBase(), QL_FAIL, and unitOfMeasure_.
{
        if (unitOfMeasure_ == m.unitOfMeasure_) {
            amount_ += m.amount_;
        } else if (conversionType == BaseUnitOfMeasureConversion) {
            convertToBase(*this);
            Quantity tmp = m;
            convertToBase(tmp);
            *this += tmp;
        } else if (conversionType == AutomatedConversion) {
            Quantity tmp = m;
            convertTo(tmp, unitOfMeasure_);
            *this += tmp;
        } else {
            QL_FAIL("unitOfMeasure mismatch and no conversion specified");
        }
        return *this;
    }
Quantity QuantLib::Quantity::operator- () const [inline]
Definition at line 156 of file quantity.hpp.
References amount_, commodityType_, Quantity(), and unitOfMeasure_.
{
        return Quantity(commodityType_, unitOfMeasure_, -amount_);
    }
Quantity & QuantLib::Quantity::operator-= (const Quantity & m)
Definition at line 68 of file quantity.cpp.
References amount_, AutomatedConversion, BaseUnitOfMeasureConversion, conversionType, QuantLib::anonymous_namespace{quantity.cpp}::convertTo(), QuantLib::anonymous_namespace{quantity.cpp}::convertToBase(), QL_FAIL, and unitOfMeasure_.
{
        if (unitOfMeasure_ == m.unitOfMeasure_) {
            amount_ -= m.amount_;
        } else if (conversionType == BaseUnitOfMeasureConversion) {
            convertToBase(*this);
            Quantity tmp = m;
            convertToBase(tmp);
            *this -= tmp;
        } else if (conversionType == AutomatedConversion) {
            Quantity tmp = m;
            convertTo(tmp, unitOfMeasure_);
            *this -= tmp;
        } else {
            QL_FAIL("unitOfMeasure mismatch and no conversion specified");
        }
        return *this;
    }
Quantity & QuantLib::Quantity::operator/= (Real x) [inline]
Definition at line 165 of file quantity.hpp.
References amount_.
{
        amount_ /= x;
        return *this;
    }
Quantity QuantLib::Quantity::rounded () const [inline]
Definition at line 146 of file quantity.hpp.
References amount_, commodityType_, Quantity(), QuantLib::UnitOfMeasure::rounding(), and unitOfMeasure_.
Referenced by QuantLib::anonymous_namespace{quantity.cpp}::convertTo().
{
        return Quantity(commodityType_,
                        unitOfMeasure_,
                        unitOfMeasure_.rounding()(amount_));
    }
const UnitOfMeasure & QuantLib::Quantity::unitOfMeasure () const [inline]
Definition at line 138 of file quantity.hpp.
References unitOfMeasure_.
Referenced by QuantLib::close(), QuantLib::close_enough(), QuantLib::UnitOfMeasureConversion::convert(), QuantLib::anonymous_namespace{quantity.cpp}::convertTo(), QuantLib::operator/(), QuantLib::operator<(), QuantLib::operator<=(), QuantLib::operator==(), and QuantLib::EnergyFuture::performCalculations().
{
        return unitOfMeasure_;
    }
Friends And Related Function Documentation
bool close (const Quantity & , const Quantity & , Size n = 42) [related]
Definition at line 163 of file quantity.cpp.
{
        if (m1.unitOfMeasure() == m2.unitOfMeasure()) {
            return close(m1.amount(),m2.amount(),n);
        } else if (Quantity::conversionType
                   == Quantity::BaseUnitOfMeasureConversion) {
            Quantity tmp1 = m1;
            convertToBase(tmp1);
            Quantity tmp2 = m2;
            convertToBase(tmp2);
            return close(tmp1,tmp2,n);
        } else if (Quantity::conversionType == Quantity::AutomatedConversion) {
            Quantity tmp = m2;
            convertTo(tmp, m1.unitOfMeasure());
            return close(m1,tmp,n);
        } else {
            QL_FAIL("unitOfMeasure mismatch and no conversion specified");
        }
    }
bool close_enough (const Quantity & , const Quantity & , Size n = 42) [related]
Definition at line 182 of file quantity.cpp.
{
        if (m1.unitOfMeasure() == m2.unitOfMeasure()) {
            return close_enough(m1.amount(),m2.amount(),n);
        } else if (Quantity::conversionType
                   == Quantity::BaseUnitOfMeasureConversion) {
            Quantity tmp1 = m1;
            convertToBase(tmp1);
            Quantity tmp2 = m2;
            convertToBase(tmp2);
            return close_enough(tmp1,tmp2,n);
        } else if (Quantity::conversionType == Quantity::AutomatedConversion) {
            Quantity tmp = m2;
            convertTo(tmp, m1.unitOfMeasure());
            return close_enough(m1,tmp,n);
        } else {
            QL_FAIL("unitOfMeasure mismatch and no conversion specified");
        }
    }
bool operator!= (const Quantity & , const Quantity &) [related]
Definition at line 199 of file quantity.hpp.
{
        return !(m1 == m2);
    }
Quantity operator* (const Quantity & , Real) [related]
Definition at line 183 of file quantity.hpp.
{
        Quantity tmp = m;
        tmp *= x;
        return tmp;
    }
Quantity operator* (Real , const Quantity &) [related]
Definition at line 189 of file quantity.hpp.
{
        return m*x;
    }
Quantity operator+ (const Quantity & , const Quantity &) [related]
Definition at line 171 of file quantity.hpp.
{
        Quantity tmp = m1;
        tmp += m2;
        return tmp;
    }
Quantity operator- (const Quantity & , const Quantity &) [related]
Definition at line 177 of file quantity.hpp.
{
        Quantity tmp = m1;
        tmp -= m2;
        return tmp;
    }
Quantity operator/ (const Quantity & , Real) [related]
Definition at line 193 of file quantity.hpp.
{
        Quantity tmp = m;
        tmp /= x;
        return tmp;
    }
Real operator/ (const Quantity & , const Quantity &) [related]
Definition at line 86 of file quantity.cpp.
{
        if (m1.unitOfMeasure() == m2.unitOfMeasure()) {
            return m1.amount()/m2.amount();
        } else if (Quantity::conversionType
                   == Quantity::BaseUnitOfMeasureConversion) {
            Quantity tmp1 = m1;
            convertToBase(tmp1);
            Quantity tmp2 = m2;
            convertToBase(tmp2);
            return tmp1/tmp2;
        } else if (Quantity::conversionType == Quantity::AutomatedConversion) {
            Quantity tmp = m2;
            convertTo(tmp, m1.unitOfMeasure());
            return m1/tmp;
        } else {
            QL_FAIL("unitOfMeasure mismatch and no conversion specified");
        }
    }
bool operator< (const Quantity & , const Quantity &) [related]
Definition at line 125 of file quantity.cpp.
{
        if (m1.unitOfMeasure() == m2.unitOfMeasure()) {
            return m1.amount() < m2.amount();
        } else if (Quantity::conversionType
                   == Quantity::BaseUnitOfMeasureConversion) {
            Quantity tmp1 = m1;
            convertToBase(tmp1);
            Quantity tmp2 = m2;
            convertToBase(tmp2);
            return tmp1 < tmp2;
        } else if (Quantity::conversionType == Quantity::AutomatedConversion) {
            Quantity tmp = m2;
            convertTo(tmp, m1.unitOfMeasure());
            return m1 < tmp;
        } else {
            QL_FAIL("unitOfMeasure mismatch and no conversion specified");
        }
    }
std::ostream& operator<< (std::ostream & out, const Quantity & quantity) [friend]
Definition at line 202 of file quantity.cpp.
{
        return out << quantity.commodityType_.code() << " "
                   << quantity.amount_ << " " << quantity.unitOfMeasure_.code();
    }
bool operator<= (const Quantity & , const Quantity &) [related]
Definition at line 144 of file quantity.cpp.
{
        if (m1.unitOfMeasure() == m2.unitOfMeasure()) {
            return m1.amount() <= m2.amount();
        } else if (Quantity::conversionType
                   == Quantity::BaseUnitOfMeasureConversion) {
            Quantity tmp1 = m1;
            convertToBase(tmp1);
            Quantity tmp2 = m2;
            convertToBase(tmp2);
            return tmp1 <= tmp2;
        } else if (Quantity::conversionType == Quantity::AutomatedConversion) {
            Quantity tmp = m2;
            convertTo(tmp, m1.unitOfMeasure());
            return m1 <= tmp;
        } else {
            QL_FAIL("unitOfMeasure mismatch and no conversion specified");
        }
    }
bool operator== (const Quantity & , const Quantity &) [related]
Definition at line 105 of file quantity.cpp.
{
        if (m1.unitOfMeasure() == m2.unitOfMeasure()) {
            return m1.amount() == m2.amount();
        } else if (Quantity::conversionType
                   == Quantity::BaseUnitOfMeasureConversion) {
            Quantity tmp1 = m1;
            convertToBase(tmp1);
            Quantity tmp2 = m2;
            convertToBase(tmp2);
            return tmp1 == tmp2;
        } else if (Quantity::conversionType
                   == Quantity::AutomatedConversion) {
            Quantity tmp = m2;
            convertTo(tmp, m1.unitOfMeasure());
            return m1 == tmp;
        } else {
            QL_FAIL("unitOfMeasure mismatch and no conversion specified");
        }
    }
bool operator> (const Quantity & , const Quantity &) [related]
Definition at line 203 of file quantity.hpp.
{
        return m2 < m1;
    }
bool operator>= (const Quantity & , const Quantity &) [related]
Definition at line 207 of file quantity.hpp.
{
        return m2 <= m1;
    }
Member Data Documentation
Real QuantLib::Quantity::amount_ [private]
Definition at line 85 of file quantity.hpp.
Referenced by amount(), operator*=(), operator+=(), operator-(), operator-=(), operator/=(), QuantLib::operator<<(), and rounded().
UnitOfMeasure QuantLib::Quantity::baseUnitOfMeasure = UnitOfMeasure() [static]
Definition at line 78 of file quantity.hpp.
Referenced by QuantLib::anonymous_namespace{quantity.cpp}::convertToBase().
CommodityType QuantLib::Quantity::commodityType_ [private]
Definition at line 83 of file quantity.hpp.
Referenced by commodityType(), operator-(), QuantLib::operator<<(), and rounded().
Quantity::ConversionType QuantLib::Quantity::conversionType = Quantity::NoConversion [static]
Definition at line 77 of file quantity.hpp.
Referenced by QuantLib::close(), QuantLib::close_enough(), operator+=(), operator-=(), QuantLib::operator/(), QuantLib::operator<(), QuantLib::operator<=(), and QuantLib::operator==().
UnitOfMeasure QuantLib::Quantity::unitOfMeasure_ [private]
Definition at line 84 of file quantity.hpp.
Referenced by operator+=(), operator-(), operator-=(), QuantLib::operator<<(), rounded(), and unitOfMeasure().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/commodities/quantity.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/commodities/quantity.cpp