QuantLib: QuantLib::Observer Class Reference
QuantLib::Observer Class Reference
Object that gets notified when a given observable changes.
#include <observable.hpp>
Inherited by QuantLib::BootstrapHelper< YoYInflationTermStructure >, QuantLib::BootstrapHelper< YoYOptionletVolatilitySurface >, QuantLib::BootstrapHelper< ZeroInflationTermStructure >, QuantLib::GenericEngine< Arguments, Results >, QuantLib::GenericEngine< BarrierOption::arguments, BarrierOption::results >, QuantLib::GenericEngine< BasketOption::arguments, BasketOption::results >, QuantLib::GenericEngine< Bond::arguments, Bond::results >, QuantLib::GenericEngine< CallableBond::arguments, CallableBond::results >, QuantLib::GenericEngine< CapFloor::arguments, CapFloor::results >, QuantLib::GenericEngine< CdsOption::arguments, CdsOption::results >, QuantLib::GenericEngine< CliquetOption::arguments, CliquetOption::results >, QuantLib::GenericEngine< CompoundOption::arguments, CompoundOption::results >, QuantLib::GenericEngine< ContinuousAveragingAsianOption::arguments, ContinuousAveragingAsianOption::results >, QuantLib::GenericEngine< ContinuousFixedLookbackOption::arguments, ContinuousFixedLookbackOption::results >, QuantLib::GenericEngine< ContinuousFloatingLookbackOption::arguments, ContinuousFloatingLookbackOption::results >, QuantLib::GenericEngine< ConvertibleBond::option::arguments, ConvertibleBond::option::results >, QuantLib::GenericEngine< CPICapFloor::arguments, CPICapFloor::results >, QuantLib::GenericEngine< CPISwap::arguments, CPISwap::results >, QuantLib::GenericEngine< CreditDefaultSwap::arguments, CreditDefaultSwap::results >, QuantLib::GenericEngine< DiscreteAveragingAsianOption::arguments, DiscreteAveragingAsianOption::results >, QuantLib::GenericEngine< DividendBarrierOption::arguments, DividendBarrierOption::results >, QuantLib::GenericEngine< DividendVanillaOption::arguments, DividendVanillaOption::results >, QuantLib::GenericEngine< EnergyCommodity::arguments, EnergyCommodity::results >, QuantLib::GenericEngine< EverestOption::arguments, EverestOption::results >, QuantLib::GenericEngine< ForwardOptionArguments< VanillaOption::arguments >, VanillaOption::results >, QuantLib::GenericEngine< HimalayaOption::arguments, HimalayaOption::results >, QuantLib::GenericEngine< Instr::arguments, QuantoOptionResults< Instr::results > >, QuantLib::GenericEngine< MargrabeOption::arguments, MargrabeOption::results >, QuantLib::GenericEngine< MultiAssetOption::arguments, MultiAssetOption::results >, QuantLib::GenericEngine< OneAssetOption::arguments, OneAssetOption::results >, QuantLib::GenericEngine< PagodaOption::arguments, PagodaOption::results >, QuantLib::GenericEngine< PathMultiAssetOption::arguments, PathMultiAssetOption::results >, QuantLib::GenericEngine< SimpleChooserOption::arguments, SimpleChooserOption::results >, QuantLib::GenericEngine< SpreadOption::arguments, SpreadOption::results >, QuantLib::GenericEngine< Swap::arguments, Swap::results >, QuantLib::GenericEngine< Swaption::arguments, Swaption::results >, QuantLib::GenericEngine< SyntheticCDO::arguments, SyntheticCDO::results >, QuantLib::GenericEngine< VanillaOption::arguments, VanillaOption::results >, QuantLib::GenericEngine< VanillaStorageOption::arguments, VanillaStorageOption::results >, QuantLib::GenericEngine< VanillaSwap::arguments, VanillaSwap::results >, QuantLib::GenericEngine< VanillaSwingOption::arguments, VanillaSwingOption::results >, QuantLib::GenericEngine< VanillaVPPOption::arguments, VanillaVPPOption::results >, QuantLib::GenericEngine< VarianceOption::arguments, VarianceOption::results >, QuantLib::GenericEngine< VarianceSwap::arguments, VarianceSwap::results >, QuantLib::GenericEngine< WriterExtensibleOption::arguments, WriterExtensibleOption::results >, QuantLib::GenericEngine< YearOnYearInflationSwap::arguments, YearOnYearInflationSwap::results >, QuantLib::GenericEngine< YoYInflationCapFloor::arguments, YoYInflationCapFloor::results >, QuantLib::GenericEngine< ZeroCouponInflationSwap::arguments, ZeroCouponInflationSwap::results >, QuantLib::BootstrapHelper< TS >, QuantLib::CalibratedModel, QuantLib::CalibrationHelper, QuantLib::Claim, QuantLib::CommodityIndex, QuantLib::CompositeQuote< BinaryFunction >, QuantLib::ConstantRecoveryModel, QuantLib::CotSwapToFwdAdapterFactory, QuantLib::DeltaVolQuote, QuantLib::DerivedQuote< UnaryFunction >, QuantLib::Flag, QuantLib::FlatVolFactory, QuantLib::FloatingRateCoupon, QuantLib::FloatingRateCouponPricer [virtual], QuantLib::ForwardValueQuote, QuantLib::FuturesConvAdjustmentQuote, QuantLib::FwdToCotSwapAdapterFactory, QuantLib::GenericEngine< ArgumentsType, ResultsType >, QuantLib::Handle< T >::Link, QuantLib::IndexedCashFlow, QuantLib::InflationCoupon, QuantLib::InflationCouponPricer [virtual], QuantLib::InflationIndex, QuantLib::InterestRateIndex, QuantLib::LastFixingQuote, QuantLib::LazyObject [virtual], QuantLib::RendistatoBasket, QuantLib::SmileSection [virtual], QuantLib::StochasticProcess, and QuantLib::TermStructure [virtual].
Public Member Functions
Observer ()
Observer (const Observer &)
Observer & operator= (const Observer &)
virtual ~Observer ()
std::pair< std::set
< boost::shared_ptr
< Observable > >::iterator,
bool > registerWith (const boost::shared_ptr< Observable > &)
Size unregisterWith (const boost::shared_ptr< Observable > &)
virtual void update ()=0
Private Types
typedef std::set
< boost::shared_ptr
< Observable > >::iterator iterator
Private Attributes
std::set< boost::shared_ptr
< Observable > > observables_
Detailed Description
Object that gets notified when a given observable changes.
Definition at line 63 of file observable.hpp.
Member Typedef Documentation
typedef std::set<boost::shared_ptr<Observable> >::iterator QuantLib::Observer::iterator [private]
Reimplemented in QuantLib::JointStochasticProcess, and QuantLib::CompositeInstrument.
Definition at line 82 of file observable.hpp.
Constructor & Destructor Documentation
QuantLib::Observer::Observer () [inline]
Definition at line 66 of file observable.hpp.
{}
QuantLib::Observer::Observer (const Observer & o) [inline]
Definition at line 143 of file observable.hpp.
References observables_.
    : observables_(o.observables_) {
        for (iterator i=observables_.begin(); i!=observables_.end(); ++i)
            (*i)->registerObserver(this);
    }
QuantLib::Observer::~Observer () [inline, virtual]
Definition at line 159 of file observable.hpp.
References observables_.
{
        for (iterator i=observables_.begin(); i!=observables_.end(); ++i)
            (*i)->unregisterObserver(this);
    }
Member Function Documentation
Observer & QuantLib::Observer::operator= (const Observer & o) [inline]
Definition at line 149 of file observable.hpp.
References observables_.
{
        iterator i;
        for (i=observables_.begin(); i!=observables_.end(); ++i)
            (*i)->unregisterObserver(this);
        observables_ = o.observables_;
        for (i=observables_.begin(); i!=observables_.end(); ++i)
            (*i)->registerObserver(this);
        return *this;
    }
std::pair< std::set< boost::shared_ptr< Observable > >::iterator, bool > QuantLib::Observer::registerWith (const boost::shared_ptr< Observable > & h) [inline]
Definition at line 165 of file observable.hpp.
References observables_.
Referenced by QuantLib::CompositeInstrument::add(), QuantLib::AmortizingCmsRateBond::AmortizingCmsRateBond(), QuantLib::AmortizingFloatingRateBond::AmortizingFloatingRateBond(), QuantLib::AnalyticAmericanMargrabeEngine::AnalyticAmericanMargrabeEngine(), QuantLib::AnalyticBarrierEngine::AnalyticBarrierEngine(), QuantLib::AnalyticBSMHullWhiteEngine::AnalyticBSMHullWhiteEngine(), QuantLib::AnalyticCapFloorEngine::AnalyticCapFloorEngine(), QuantLib::AnalyticCliquetEngine::AnalyticCliquetEngine(), QuantLib::AnalyticCompoundOptionEngine::AnalyticCompoundOptionEngine(), QuantLib::AnalyticContinuousFixedLookbackEngine::AnalyticContinuousFixedLookbackEngine(), QuantLib::AnalyticContinuousFloatingLookbackEngine::AnalyticContinuousFloatingLookbackEngine(), QuantLib::AnalyticContinuousGeometricAveragePriceAsianEngine::AnalyticContinuousGeometricAveragePriceAsianEngine(), QuantLib::AnalyticDigitalAmericanEngine::AnalyticDigitalAmericanEngine(), QuantLib::AnalyticDiscreteGeometricAveragePriceAsianEngine::AnalyticDiscreteGeometricAveragePriceAsianEngine(), QuantLib::AnalyticDiscreteGeometricAverageStrikeAsianEngine::AnalyticDiscreteGeometricAverageStrikeAsianEngine(), QuantLib::AnalyticDividendEuropeanEngine::AnalyticDividendEuropeanEngine(), QuantLib::AnalyticEuropeanMargrabeEngine::AnalyticEuropeanMargrabeEngine(), QuantLib::AnalyticHestonHullWhiteEngine::AnalyticHestonHullWhiteEngine(), QuantLib::AnalyticPerformanceEngine::AnalyticPerformanceEngine(), QuantLib::AnalyticSimpleChooserEngine::AnalyticSimpleChooserEngine(), QuantLib::AnalyticWriterExtensibleOptionEngine::AnalyticWriterExtensibleOptionEngine(), QuantLib::AssetSwap::AssetSwap(), QuantLib::AssetSwapHelper::AssetSwapHelper(), QuantLib::Basket::Basket(), QuantLib::BinomialConvertibleEngine< T >::BinomialConvertibleEngine(), QuantLib::BinomialVanillaEngine< T >::BinomialVanillaEngine(), QuantLib::BlackCallableFixedRateBondEngine::BlackCallableFixedRateBondEngine(), QuantLib::BlackCapFloorEngine::BlackCapFloorEngine(), QuantLib::BlackCdsOptionEngine::BlackCdsOptionEngine(), QuantLib::BlackConstantVol::BlackConstantVol(), QuantLib::BlackIborQuantoCouponPricer::BlackIborQuantoCouponPricer(), QuantLib::BlackKarasinski::BlackKarasinski(), QuantLib::BlackSwaptionEngine::BlackSwaptionEngine(), QuantLib::BMAIndex::BMAIndex(), QuantLib::BMASwap::BMASwap(), QuantLib::BMASwapRateHelper::BMASwapRateHelper(), QuantLib::Bond::Bond(), QuantLib::BootstrapHelper< TS >::BootstrapHelper(), QuantLib::CalibrationHelper::CalibrationHelper(), QuantLib::CallableBondConstantVolatility::CallableBondConstantVolatility(), QuantLib::CapFloor::CapFloor(), QuantLib::CappedFlooredCoupon::CappedFlooredCoupon(), QuantLib::CappedFlooredYoYInflationCoupon::CappedFlooredYoYInflationCoupon(), QuantLib::CDO::CDO(), QuantLib::CdsHelper::CdsHelper(), QuantLib::CdsOption::CdsOption(), QuantLib::CmsCouponPricer::CmsCouponPricer(), QuantLib::CmsMarket::CmsMarket(), QuantLib::CmsRateBond::CmsRateBond(), QuantLib::CommodityIndex::CommodityIndex(), QuantLib::CompositeQuote< BinaryFunction >::CompositeQuote(), QuantLib::ConstantCapFloorTermVolatility::ConstantCapFloorTermVolatility(), QuantLib::ConstantOptionletVolatility::ConstantOptionletVolatility(), QuantLib::ConstantRecoveryModel::ConstantRecoveryModel(), QuantLib::ConstantSwaptionVolatility::ConstantSwaptionVolatility(), QuantLib::ContinuousArithmeticAsianLevyEngine::ContinuousArithmeticAsianLevyEngine(), QuantLib::ConvertibleBond::ConvertibleBond(), QuantLib::CotSwapToFwdAdapterFactory::CotSwapToFwdAdapterFactory(), QuantLib::CPIBond::CPIBond(), QuantLib::CPICouponPricer::CPICouponPricer(), QuantLib::CPISwap::CPISwap(), QuantLib::CreditDefaultSwap::CreditDefaultSwap(), QuantLib::DatedOISRateHelper::DatedOISRateHelper(), QuantLib::DefaultProbabilityTermStructure::DefaultProbabilityTermStructure(), QuantLib::DeltaVolQuote::DeltaVolQuote(), QuantLib::DerivedQuote< UnaryFunction >::DerivedQuote(), QuantLib::DigitalCoupon::DigitalCoupon(), QuantLib::DiscountingBondEngine::DiscountingBondEngine(), QuantLib::DiscountingSwapEngine::DiscountingSwapEngine(), QuantLib::DriftTermStructure::DriftTermStructure(), QuantLib::EnergyBasisSwap::EnergyBasisSwap(), QuantLib::EnergyFuture::EnergyFuture(), QuantLib::EnergyVanillaSwap::EnergyVanillaSwap(), QuantLib::EurodollarFuturesImpliedStdDevQuote::EurodollarFuturesImpliedStdDevQuote(), QuantLib::ExtendedBlackVarianceCurve::ExtendedBlackVarianceCurve(), QuantLib::ExtendedBlackVarianceSurface::ExtendedBlackVarianceSurface(), QuantLib::FaceValueAccrualClaim::FaceValueAccrualClaim(), QuantLib::FactorSpreadedHazardRateCurve::FactorSpreadedHazardRateCurve(), QuantLib::FDEuropeanEngine< Scheme >::FDEuropeanEngine(), QuantLib::Fdm2dBlackScholesSolver::Fdm2dBlackScholesSolver(), QuantLib::FdmAffineModelTermStructure::FdmAffineModelTermStructure(), QuantLib::FdmBatesSolver::FdmBatesSolver(), QuantLib::FdmBlackScholesSolver::FdmBlackScholesSolver(), QuantLib::FdmExtOUJumpSolver::FdmExtOUJumpSolver(), QuantLib::FdmG2Solver::FdmG2Solver(), QuantLib::FdmHestonHullWhiteSolver::FdmHestonHullWhiteSolver(), QuantLib::FdmHestonSolver::FdmHestonSolver(), QuantLib::FdmHullWhiteSolver::FdmHullWhiteSolver(), QuantLib::FdmKlugeExtOUSolver< N >::FdmKlugeExtOUSolver(), QuantLib::FdmSimple2dBSSolver::FdmSimple2dBSSolver(), QuantLib::FdmSimple2dExtOUSolver::FdmSimple2dExtOUSolver(), QuantLib::FdmSimple3dExtOUJumpSolver::FdmSimple3dExtOUJumpSolver(), QuantLib::FixedRateBondForward::FixedRateBondForward(), QuantLib::FlatForward::FlatForward(), QuantLib::FlatHazardRate::FlatHazardRate(), QuantLib::FlatVolFactory::FlatVolFactory(), QuantLib::FloatingRateBond::FloatingRateBond(), QuantLib::FloatingRateCoupon::FloatingRateCoupon(), QuantLib::Forward::Forward(), QuantLib::ForwardRateAgreement::ForwardRateAgreement(), QuantLib::ForwardSpreadedTermStructure::ForwardSpreadedTermStructure(), QuantLib::ForwardSwapQuote::ForwardSwapQuote(), QuantLib::ForwardValueQuote::ForwardValueQuote(), QuantLib::ForwardVanillaEngine< Engine >::ForwardVanillaEngine(), QuantLib::FuturesConvAdjustmentQuote::FuturesConvAdjustmentQuote(), QuantLib::FuturesRateHelper::FuturesRateHelper(), QuantLib::FwdToCotSwapAdapterFactory::FwdToCotSwapAdapterFactory(), QuantLib::G2::G2(), QuantLib::GeneralizedBlackScholesProcess::GeneralizedBlackScholesProcess(), QuantLib::GeneralizedHullWhite::GeneralizedHullWhite(), QuantLib::GenericModelEngine< GJRGARCHModel, VanillaOption::arguments, VanillaOption::results >::GenericModelEngine(), QuantLib::GJRGARCHModel::GJRGARCHModel(), QuantLib::GJRGARCHProcess::GJRGARCHProcess(), QuantLib::HaganPricer::HaganPricer(), QuantLib::HestonModel::HestonModel(), QuantLib::HestonProcess::HestonProcess(), QuantLib::HullWhite::HullWhite(), QuantLib::IborCouponPricer::IborCouponPricer(), QuantLib::IborIndex::IborIndex(), QuantLib::ImpliedStdDevQuote::ImpliedStdDevQuote(), QuantLib::ImpliedTermStructure::ImpliedTermStructure(), QuantLib::ImpliedVolTermStructure::ImpliedVolTermStructure(), QuantLib::IndexedCashFlow::IndexedCashFlow(), QuantLib::InflationCoupon::InflationCoupon(), QuantLib::InflationIndex::InflationIndex(), QuantLib::InflationTermStructure::InflationTermStructure(), QuantLib::OvernightIndexedSwap::initialize(), QuantLib::IntegralCdsEngine::IntegralCdsEngine(), QuantLib::IntegralHestonVarianceOptionEngine::IntegralHestonVarianceOptionEngine(), QuantLib::InterestRateIndex::InterestRateIndex(), QuantLib::InterpolatedSmileSection< Interpolator >::InterpolatedSmileSection(), QuantLib::JamshidianSwaptionEngine::JamshidianSwaptionEngine(), QuantLib::JointStochasticProcess::JointStochasticProcess(), QuantLib::KirkEngine::KirkEngine(), QuantLib::KirkSpreadOptionEngine::KirkSpreadOptionEngine(), QuantLib::LastFixingQuote::LastFixingQuote(), QuantLib::LfmSwaptionEngine::LfmSwaptionEngine(), QuantLib::LocalConstantVol::LocalConstantVol(), QuantLib::LocalVolCurve::LocalVolCurve(), QuantLib::LocalVolSurface::LocalVolSurface(), QuantLib::MCBarrierEngine< RNG, S >::MCBarrierEngine(), QuantLib::MCDiscreteAveragingAsianEngine< RNG, S >::MCDiscreteAveragingAsianEngine(), QuantLib::MCEuropeanBasketEngine< RNG, S >::MCEuropeanBasketEngine(), QuantLib::MCEverestEngine< RNG, S >::MCEverestEngine(), QuantLib::MCHimalayaEngine< RNG, S >::MCHimalayaEngine(), QuantLib::MCHullWhiteCapFloorEngine< RNG, S >::MCHullWhiteCapFloorEngine(), QuantLib::MCLongstaffSchwartzEngine< GenericEngine, MC, RNG, S >::MCLongstaffSchwartzEngine(), QuantLib::MCLongstaffSchwartzPathEngine< GenericEngine, MC, RNG, S >::MCLongstaffSchwartzPathEngine(), QuantLib::MCPagodaEngine< RNG, S >::MCPagodaEngine(), QuantLib::MCPathBasketEngine< RNG, S >::MCPathBasketEngine(), QuantLib::MCPerformanceEngine< RNG, S >::MCPerformanceEngine(), QuantLib::Merton76Process::Merton76Process(), QuantLib::MidPointCdsEngine::MidPointCdsEngine(), QuantLib::NthToDefault::NthToDefault(), QuantLib::OISRateHelper::OISRateHelper(), QuantLib::OneFactorCopula::OneFactorCopula(), QuantLib::OneFactorGaussianCopula::OneFactorGaussianCopula(), QuantLib::OptionletStripper::OptionletStripper(), QuantLib::OptionletStripper2::OptionletStripper2(), QuantLib::PerturbativeBarrierOptionEngine::PerturbativeBarrierOptionEngine(), QuantLib::PiecewiseTimeDependentHestonModel::PiecewiseTimeDependentHestonModel(), QuantLib::PiecewiseZeroSpreadedTermStructure::PiecewiseZeroSpreadedTermStructure(), QuantLib::ProxyIbor::ProxyIbor(), QuantLib::QuantoEngine< Instr, Engine >::QuantoEngine(), QuantLib::QuantoTermStructure::QuantoTermStructure(), QuantLib::StrippedOptionlet::registerWithMarketData(), QuantLib::SabrVolSurface::registerWithMarketData(), QuantLib::AbcdAtmVolCurve::registerWithMarketData(), QuantLib::CapFloorTermVolCurve::registerWithMarketData(), QuantLib::CapFloorTermVolSurface::registerWithMarketData(), QuantLib::SwaptionVolatilityMatrix::registerWithMarketData(), QuantLib::SwaptionVolCube1::registerWithParametersGuess(), QuantLib::SwaptionVolatilityCube::registerWithVolatilitySpread(), QuantLib::RelativeDateBootstrapHelper< TS >::RelativeDateBootstrapHelper(), QuantLib::RendistatoBasket::RendistatoBasket(), QuantLib::RendistatoCalculator::RendistatoCalculator(), QuantLib::RiskyAssetSwap::RiskyAssetSwap(), QuantLib::RiskyBond::RiskyBond(), QuantLib::SabrInterpolatedSmileSection::SabrInterpolatedSmileSection(), QuantLib::CPICouponPricer::setCapletVolatility(), QuantLib::IborCouponPricer::setCapletVolatility(), QuantLib::YoYInflationCouponPricer::setCapletVolatility(), QuantLib::HaganPricer::setMeanReversion(), QuantLib::InflationCoupon::setPricer(), QuantLib::FloatingRateCoupon::setPricer(), QuantLib::DigitalCoupon::setPricer(), QuantLib::Instrument::setPricingEngine(), QuantLib::CmsCouponPricer::setSwaptionVolatility(), QuantLib::FittedBondDiscountCurve::setup(), QuantLib::YoYInflationCapFloorEngine::setVolatility(), QuantLib::SmileSection::SmileSection(), QuantLib::SpreadedHazardRateCurve::SpreadedHazardRateCurve(), QuantLib::SpreadedOptionletVolatility::SpreadedOptionletVolatility(), QuantLib::SpreadedSmileSection::SpreadedSmileSection(), QuantLib::SpreadedSwaptionVolatility::SpreadedSwaptionVolatility(), QuantLib::StochasticProcessArray::StochasticProcessArray(), QuantLib::Stock::Stock(), QuantLib::StrippedOptionlet::StrippedOptionlet(), QuantLib::StrippedOptionletAdapter::StrippedOptionletAdapter(), QuantLib::StulzEngine::StulzEngine(), QuantLib::Swap::Swap(), QuantLib::Swaption::Swaption(), QuantLib::SwaptionVolatilityCube::SwaptionVolatilityCube(), QuantLib::SwaptionVolatilityDiscrete::SwaptionVolatilityDiscrete(), QuantLib::SyntheticCDO::SyntheticCDO(), QuantLib::TermStructure::TermStructure(), QuoteTest::testForwardValueQuoteAndImpliedStdevQuote(), TermStructureTest::testFSpreadedObs(), TermStructureTest::testImpliedObs(), EuropeanOptionTest::testImpliedVolContainment(), PiecewiseYieldCurveTest::testLiborFixing(), PiecewiseYieldCurveTest::testObservability(), QuoteTest::testObservable(), InstrumentTest::testObservable(), QuoteTest::testObservableHandle(), SwaptionVolatilityCubeTest::testSpreadedCube(), TermStructureTest::testZSpreadedObs(), QuantLib::TreeCallableFixedRateBondEngine::TreeCallableFixedRateBondEngine(), QuantLib::TreeCapFloorEngine::TreeCapFloorEngine(), QuantLib::TreeSwaptionEngine::TreeSwaptionEngine(), QuantLib::TreeVanillaSwapEngine::TreeVanillaSwapEngine(), QuantLib::VanillaSwap::VanillaSwap(), QuantLib::VarianceGammaModel::VarianceGammaModel(), QuantLib::VarianceGammaProcess::VarianceGammaProcess(), QuantLib::YearOnYearInflationSwap::YearOnYearInflationSwap(), QuantLib::YearOnYearInflationSwapHelper::YearOnYearInflationSwapHelper(), QuantLib::YieldTermStructure::YieldTermStructure(), QuantLib::YoYInflationCapFloor::YoYInflationCapFloor(), QuantLib::YoYInflationCapFloorEngine::YoYInflationCapFloorEngine(), QuantLib::YoYInflationCouponPricer::YoYInflationCouponPricer(), QuantLib::YoYInflationIndex::YoYInflationIndex(), QuantLib::ZeroCouponInflationSwap::ZeroCouponInflationSwap(), QuantLib::ZeroCouponInflationSwapHelper::ZeroCouponInflationSwapHelper(), QuantLib::ZeroInflationIndex::ZeroInflationIndex(), and QuantLib::ZeroSpreadedTermStructure::ZeroSpreadedTermStructure().
{
        if (h) {
            h->registerObserver(this);
            return observables_.insert(h);
        }
        return std::make_pair(observables_.end(), false);
    }
Size QuantLib::Observer::unregisterWith (const boost::shared_ptr< Observable > & h) [inline]
Definition at line 174 of file observable.hpp.
References observables_.
Referenced by QuantLib::IborCouponPricer::setCapletVolatility(), QuantLib::HaganPricer::setMeanReversion(), QuantLib::InflationCoupon::setPricer(), QuantLib::FloatingRateCoupon::setPricer(), QuantLib::DigitalCoupon::setPricer(), QuantLib::Instrument::setPricingEngine(), QuantLib::CmsCouponPricer::setSwaptionVolatility(), QuantLib::YoYInflationCapFloorEngine::setVolatility(), and QuoteTest::testForwardValueQuoteAndImpliedStdevQuote().
{
        if (h)
            h->unregisterObserver(this);
        return observables_.erase(h);
    }
virtual void QuantLib::Observer::update () [pure virtual]
This method must be implemented in derived classes. An instance of Observer does not call this method directly: instead, it will be called by the observables the instance registered with when they need to notify any changes.
Implemented in QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >, QuantLib::InterpolatedCPICapFloorTermPriceSurface< Interpolator2D >, QuantLib::PiecewiseYieldCurve< Traits, Interpolator, Bootstrap >, QuantLib::PiecewiseYoYOptionletVolatilityCurve< Interpolator, Bootstrap, Traits >, QuantLib::YieldTermStructure, QuantLib::PiecewiseDefaultCurve< Traits, Interpolator, Bootstrap >, QuantLib::Flag, QuantLib::DefaultProbabilityTermStructure, QuantLib::FittedBondDiscountCurve, QuantLib::StochasticProcess, QuantLib::DigitalCoupon, QuantLib::CappedFlooredYoYInflationCoupon, QuantLib::AssetSwapHelper, QuantLib::RelativeDateBootstrapHelper< TS >, QuantLib::RendistatoBasket, QuantLib::TermStructure, QuantLib::FloatingRateCoupon, QuantLib::InflationIndex, QuantLib::InflationCoupon, QuantLib::PiecewiseYoYInflationCurve< Interpolator, Bootstrap, Traits >, QuantLib::CapFloorTermVolCurve, QuantLib::CapFloorTermVolSurface, QuantLib::BootstrapHelper< TS >, QuantLib::PiecewiseZeroInflationCurve< Interpolator, Bootstrap, Traits >, QuantLib::BootstrapHelper< YoYInflationTermStructure >, QuantLib::BootstrapHelper< ZeroInflationTermStructure >, QuantLib::BootstrapHelper< YoYOptionletVolatilitySurface >, QuantLib::SabrVolSurface, QuantLib::FlatVolFactory, QuantLib::CalibratedModel, QuantLib::CdsHelper, QuantLib::SabrInterpolatedSmileSection, QuantLib::CappedFlooredCoupon, QuantLib::AnalyticHestonHullWhiteEngine, QuantLib::InterpolatedSmileSection< Interpolator >, QuantLib::IndexedCashFlow, QuantLib::FlatForward, QuantLib::GeneralizedBlackScholesProcess, QuantLib::AbcdAtmVolCurve, QuantLib::InflationCouponPricer, QuantLib::HybridHestonHullWhiteProcess, QuantLib::JointStochasticProcess, QuantLib::GenericEngine< ArgumentsType, ResultsType >, QuantLib::GenericEngine< EnergyCommodity::arguments, EnergyCommodity::results >, QuantLib::GenericEngine< ForwardOptionArguments< VanillaOption::arguments >, VanillaOption::results >, QuantLib::GenericEngine< YearOnYearInflationSwap::arguments, YearOnYearInflationSwap::results >, QuantLib::GenericEngine< CPISwap::arguments, CPISwap::results >, QuantLib::GenericEngine< VanillaSwingOption::arguments, VanillaSwingOption::results >, QuantLib::GenericEngine< VarianceSwap::arguments, VarianceSwap::results >, QuantLib::GenericEngine< PagodaOption::arguments, PagodaOption::results >, QuantLib::GenericEngine< MargrabeOption::arguments, MargrabeOption::results >, QuantLib::GenericEngine< Arguments, Results >, QuantLib::GenericEngine< ContinuousFixedLookbackOption::arguments, ContinuousFixedLookbackOption::results >, QuantLib::GenericEngine< CreditDefaultSwap::arguments, CreditDefaultSwap::results >, QuantLib::GenericEngine< CapFloor::arguments, CapFloor::results >, QuantLib::GenericEngine< VanillaStorageOption::arguments, VanillaStorageOption::results >, QuantLib::GenericEngine< SpreadOption::arguments, SpreadOption::results >, QuantLib::GenericEngine< HimalayaOption::arguments, HimalayaOption::results >, QuantLib::GenericEngine< EverestOption::arguments, EverestOption::results >, QuantLib::GenericEngine< MultiAssetOption::arguments, MultiAssetOption::results >, QuantLib::GenericEngine< CompoundOption::arguments, CompoundOption::results >, QuantLib::GenericEngine< CdsOption::arguments, CdsOption::results >, QuantLib::GenericEngine< SyntheticCDO::arguments, SyntheticCDO::results >, QuantLib::GenericEngine< ContinuousFloatingLookbackOption::arguments, ContinuousFloatingLookbackOption::results >, QuantLib::GenericEngine< CliquetOption::arguments, CliquetOption::results >, QuantLib::GenericEngine< OneAssetOption::arguments, OneAssetOption::results >, QuantLib::GenericEngine< DividendBarrierOption::arguments, DividendBarrierOption::results >, QuantLib::GenericEngine< ContinuousAveragingAsianOption::arguments, ContinuousAveragingAsianOption::results >, QuantLib::GenericEngine< PathMultiAssetOption::arguments, PathMultiAssetOption::results >, QuantLib::GenericEngine< VanillaSwap::arguments, VanillaSwap::results >, QuantLib::GenericEngine< ConvertibleBond::option::arguments, ConvertibleBond::option::results >, QuantLib::GenericEngine< VarianceOption::arguments, VarianceOption::results >, QuantLib::GenericEngine< BarrierOption::arguments, BarrierOption::results >, QuantLib::GenericEngine< VanillaVPPOption::arguments, VanillaVPPOption::results >, QuantLib::GenericEngine< Swaption::arguments, Swaption::results >, QuantLib::GenericEngine< WriterExtensibleOption::arguments, WriterExtensibleOption::results >, QuantLib::GenericEngine< YoYInflationCapFloor::arguments, YoYInflationCapFloor::results >, QuantLib::GenericEngine< CallableBond::arguments, CallableBond::results >, QuantLib::GenericEngine< DiscreteAveragingAsianOption::arguments, DiscreteAveragingAsianOption::results >, QuantLib::GenericEngine< VanillaOption::arguments, VanillaOption::results >, QuantLib::GenericEngine< Swap::arguments, Swap::results >, QuantLib::GenericEngine< Instr::arguments, QuantoOptionResults< Instr::results > >, QuantLib::GenericEngine< Bond::arguments, Bond::results >, QuantLib::GenericEngine< ZeroCouponInflationSwap::arguments, ZeroCouponInflationSwap::results >, QuantLib::GenericEngine< DividendVanillaOption::arguments, DividendVanillaOption::results >, QuantLib::GenericEngine< BasketOption::arguments, BasketOption::results >, QuantLib::GenericEngine< CPICapFloor::arguments, CPICapFloor::results >, QuantLib::GenericEngine< SimpleChooserOption::arguments, SimpleChooserOption::results >, QuantLib::DeltaVolQuote, QuantLib::ExtendedBlackVarianceSurface, QuantLib::ConstantRecoveryModel, QuantLib::PiecewiseZeroSpreadedTermStructure, QuantLib::FdHestonHullWhiteVanillaEngine, QuantLib::SwaptionVolatilityDiscrete, QuantLib::ExtendedBlackVarianceCurve, QuantLib::CotSwapToFwdAdapterFactory, QuantLib::FwdToCotSwapAdapterFactory, QuantLib::FdHestonVanillaEngine, QuantLib::InterestRateIndex, QuantLib::FloatingRateCouponPricer, QuantLib::CompositeQuote< BinaryFunction >, QuantLib::StrippedOptionletAdapter, QuantLib::CommodityIndex, QuantLib::FuturesConvAdjustmentQuote, QuantLib::CmsMarket, QuantLib::Handle< T >::Link, QuantLib::CalibrationHelper, QuantLib::LatticeShortRateModelEngine< Arguments, Results >, QuantLib::DerivedQuote< UnaryFunction >, QuantLib::LatticeShortRateModelEngine< CapFloor::arguments, CapFloor::results >, QuantLib::LatticeShortRateModelEngine< VanillaSwap::arguments, VanillaSwap::results >, QuantLib::LatticeShortRateModelEngine< Swaption::arguments, Swaption::results >, QuantLib::LatticeShortRateModelEngine< CallableBond::arguments, CallableBond::results >, QuantLib::SpreadedSmileSection, QuantLib::ForwardSwapQuote, QuantLib::SmileSection, QuantLib::LastFixingQuote, QuantLib::ForwardValueQuote, QuantLib::LazyObject, and QuantLib::Claim.
Member Data Documentation
std::set<boost::shared_ptr<Observable> > QuantLib::Observer::observables_ [private]
Definition at line 81 of file observable.hpp.
Referenced by Observer(), operator=(), registerWith(), unregisterWith(), and ~Observer().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/patterns/observable.hpp