QuantLib: QuantLib::AlphaFinder Class Reference
QuantLib::AlphaFinder Class Reference
#include <alphafinder.hpp>
Public Member Functions
AlphaFinder (boost::shared_ptr< AlphaForm > parametricform)
bool solve (Real alpha0, Integer stepindex, const std::vector< Volatility > &rateonevols, const std::vector< Volatility > &ratetwohomogeneousvols, const std::vector< Real > &correlations, Real w0, Real w1, Real targetVariance, Real tolerance, Real alphaMax, Real alphaMin, Integer steps, Real &alpha, Real &a, Real &b, std::vector< Volatility > &ratetwovols)
bool solveWithMaxHomogeneity (Real alpha0, Integer stepindex, const std::vector< Volatility > &rateonevols, const std::vector< Volatility > &ratetwohomogeneousvols, const std::vector< Real > &correlations, Real w0, Real w1, Real targetVariance, Real tolerance, Real alphaMax, Real alphaMin, Integer steps, Real &alpha, Real &a, Real &b, std::vector< Volatility > &ratetwovols)
Private Member Functions
Real computeLinearPart (Real alpha)
Real computeQuadraticPart (Real alpha)
Real valueAtTurningPoint (Real alpha)
Real minusValueAtTurningPoint (Real alpha)
bool testIfSolutionExists (Real alpha)
bool finalPart (Real alphaFound, Integer stepindex, const std::vector< Volatility > &ratetwohomogeneousvols, Real quadraticPart, Real linearPart, Real constantPart, Real &alpha, Real &a, Real &b, std::vector< Volatility > &ratetwovols)
Real homogeneityfailure (Real alpha)
Private Attributes
boost::shared_ptr< AlphaForm > parametricform_
Integer stepindex_
std::vector< Volatility > rateonevols_
std::vector< Volatility > ratetwohomogeneousvols_
std::vector< Volatility > putativevols_
std::vector< Real > correlations_
Real w0_
Real w1_
Real constantPart_
Real linearPart_
Real quadraticPart_
Real totalVar_
Real targetVariance_
Detailed Description
Definition at line 29 of file alphafinder.hpp.
Constructor & Destructor Documentation
QuantLib::AlphaFinder::AlphaFinder (boost::shared_ptr< AlphaForm > parametricform)
Definition at line 178 of file alphafinder.cpp.
    : parametricform_(parametricform) {}
Member Function Documentation
Real QuantLib::AlphaFinder::computeLinearPart (Real alpha) [private]
Definition at line 182 of file alphafinder.cpp.
References correlations_, parametricform_, rateonevols_, ratetwohomogeneousvols_, stepindex_, w0_, and w1_.
Referenced by homogeneityfailure(), solveWithMaxHomogeneity(), testIfSolutionExists(), and valueAtTurningPoint().
{
        Real cov =0.0;
        parametricform_->setAlpha(alpha);
        for (Integer i=0; i < stepindex_+1; ++i) {
            Real vol1 = ratetwohomogeneousvols_[i]*(*parametricform_)(i);
            cov += vol1*rateonevols_[i]*correlations_[i];
        }
        cov *= 2*w0_*w1_;
        return cov;
    }
Real QuantLib::AlphaFinder::computeQuadraticPart (Real alpha) [private]
Definition at line 196 of file alphafinder.cpp.
References parametricform_, ratetwohomogeneousvols_, stepindex_, and w1_.
Referenced by homogeneityfailure(), solveWithMaxHomogeneity(), testIfSolutionExists(), and valueAtTurningPoint().
{
        Real var =0.0;
        parametricform_->setAlpha(alpha);
        for (Integer i=0; i < stepindex_+1; ++i) {
            Real vol = ratetwohomogeneousvols_[i]*(*parametricform_)(i);
            var+= vol*vol;
        }
        var *= w1_*w1_;
        return var;
    }
bool QuantLib::AlphaFinder::finalPart (Real alphaFound, Integer stepindex, const std::vector< Volatility > & ratetwohomogeneousvols, Real quadraticPart, Real linearPart, Real constantPart, Real & alpha, Real & a, Real & b, std::vector< Volatility > & ratetwovols) [private]
Definition at line 231 of file alphafinder.cpp.
References parametricform_, QuantLib::quadratic::roots(), targetVariance_, and totalVar_.
Referenced by homogeneityfailure(), solve(), solveWithMaxHomogeneity(), and testIfSolutionExists().
{
            alpha = alphaFound;
            quadratic q2(quadraticPart, linearPart, constantPart-targetVariance_ );
            parametricform_->setAlpha(alpha);
            Real y; // dummy
            q2.roots(a,y);
            Real varSoFar=0.0;
            for (Integer i =0; i < stepindex+1; ++i) {
                ratetwovols[i] = ratetwohomogeneousvols[i] *
                                            (*parametricform_)(i) * a;
                varSoFar += ratetwovols[i]* ratetwovols[i];
            }
            Real VarToFind = totalVar_-varSoFar;
            if (VarToFind < 0)
                return false;
            Real requiredSd = std::sqrt(VarToFind);
            b = requiredSd / (ratetwohomogeneousvols[stepindex+1] *
                                            (*parametricform_)(stepindex));
            ratetwovols[stepindex+1] = requiredSd;
            return true;
    }
Real QuantLib::AlphaFinder::homogeneityfailure (Real alpha) [private]
Definition at line 209 of file alphafinder.cpp.
References computeLinearPart(), computeQuadraticPart(), constantPart_, finalPart(), putativevols_, ratetwohomogeneousvols_, and stepindex_.
Referenced by solveWithMaxHomogeneity().
{
        Real dum1, dum2, dum3;
        finalPart(alpha,
                  stepindex_,
                  ratetwohomogeneousvols_,
                  computeQuadraticPart(alpha),
                  computeLinearPart(alpha),
                  constantPart_,
                  dum1,
                  dum2,
                  dum3,
                  putativevols_);
    Real result=0.0;
    for (Size i=0; i<=static_cast<Size>(stepindex_)+1; ++i) {
        Real val =  putativevols_[i]-ratetwohomogeneousvols_[i];
        result +=val*val;
    }
    return result;
}
Real QuantLib::AlphaFinder::minusValueAtTurningPoint (Real alpha) [private]
Definition at line 274 of file alphafinder.cpp.
References valueAtTurningPoint().
Referenced by solve().
{
        return -valueAtTurningPoint(alpha);
    }
bool QuantLib::AlphaFinder::solve (Real alpha0, Integer stepindex, const std::vector< Volatility > & rateonevols, const std::vector< Volatility > & ratetwohomogeneousvols, const std::vector< Real > & correlations, Real w0, Real w1, Real targetVariance, Real tolerance, Real alphaMax, Real alphaMin, Integer steps, Real & alpha, Real & a, Real & b, std::vector< Volatility > & ratetwovols)
Definition at line 296 of file alphafinder.cpp.
References constantPart_, correlations_, finalPart(), linearPart_, minusValueAtTurningPoint(), quadraticPart_, rateonevols_, ratetwohomogeneousvols_, stepindex_, targetVariance_, anonymous_namespace{gaussianquadratures.cpp}::tolerance, totalVar_, valueAtTurningPoint(), w0_, and w1_.
Referenced by QuantLib::CTSMMCapletAlphaFormCalibration::capletAlphaFormCalibration().
{
        stepindex_=stepindex;
        rateonevols_=rateonevols;
        ratetwohomogeneousvols_=ratetwohomogeneousvols;
        correlations_=correlations;
        w0_=w0;
        w1_=w1;
        totalVar_=0;
        for (Size i=0; i <=static_cast<Size>(stepindex)+1; ++i)
            totalVar_+=ratetwohomogeneousvols[i]*ratetwohomogeneousvols[i];
        targetVariance_ = targetVariance;
        // constant part will not depend on alpha
        constantPart_ =0.0;
        for (Integer i=0; i < stepindex+1; ++i)
                constantPart_+=rateonevols[i]*rateonevols[i];
        constantPart_ *= w0*w0;
        // compute linear part with initial alpha
        Real valueAtTP = valueAtTurningPoint(alpha0);
        if (valueAtTP <= targetVariance) {
            finalPart(alpha0,
                      stepindex,
                      ratetwohomogeneousvols,
                      quadraticPart_,
                      linearPart_,
                      constantPart_,
                      alpha,
                      a,
                      b,
                      ratetwovols);
            return true;
        }
        // we now have to solve
        Real bottomValue = valueAtTurningPoint(alphaMin);
        Real bottomAlpha = alphaMin;
        Real topValue = valueAtTurningPoint(alphaMax);
        Real topAlpha = alphaMax;
        Real bilimit = alpha0;
        if (bottomValue > targetVariance && topValue > targetVariance) {
            // see if if ok at some intermediate point by stepping through
            Integer i=1;
            while ( i < steps && topValue> targetVariance) {
                topAlpha = alpha0 + (alphaMax-alpha0)*(i+0.0)/(steps+0.0);
                topValue=valueAtTurningPoint(topAlpha);
                ++i;
            }
            if (topValue <= targetVariance)
                bilimit = alpha0 + (topAlpha-alpha0)*(i-2.0)/(steps+0.0);
        }
        if (bottomValue > targetVariance && topValue > targetVariance) {
            // see if if ok at some intermediate point by stepping through
            Integer i=1;
            while ( i < steps && topValue> targetVariance) {
                bottomAlpha = alpha0 + (alphaMin-alpha0)*(i+0.0)/(steps+0.0);
                bottomValue=valueAtTurningPoint(bottomAlpha);
                ++i;
            }
            if (bottomValue <= targetVariance)
                bilimit = alpha0 +(bottomAlpha-alpha0)*(i-2.0)/(steps+0.0);
        }
        if (bottomValue > targetVariance && topValue > targetVariance)
            return false;
        if (bottomValue <= targetVariance) {
            // then find root of increasing function
            // (or as if increasing function)
            alpha = Bisection<AlphaFinder>(
                                           targetVariance,
                                           bottomAlpha,
                                           bilimit,
                                           tolerance,
                                           *this,
                                           &AlphaFinder::valueAtTurningPoint);
        } else {
            // find root of decreasing function (or as if decreasing function)
            alpha=Bisection<AlphaFinder>(
                                         -targetVariance,
                                         bilimit,
                                         topAlpha,
                                         tolerance,
                                         *this,
                                         &AlphaFinder::minusValueAtTurningPoint);
        }
        finalPart(alpha,
                  stepindex,
                  ratetwohomogeneousvols,
                  quadraticPart_,
                  linearPart_,
                  constantPart_,
                  alpha,
                  a,
                  b,
                  ratetwovols);
        return true;
    }
bool QuantLib::AlphaFinder::solveWithMaxHomogeneity (Real alpha0, Integer stepindex, const std::vector< Volatility > & rateonevols, const std::vector< Volatility > & ratetwohomogeneousvols, const std::vector< Real > & correlations, Real w0, Real w1, Real targetVariance, Real tolerance, Real alphaMax, Real alphaMin, Integer steps, Real & alpha, Real & a, Real & b, std::vector< Volatility > & ratetwovols)
Definition at line 417 of file alphafinder.cpp.
References computeLinearPart(), computeQuadraticPart(), constantPart_, correlations_, finalPart(), homogeneityfailure(), putativevols_, rateonevols_, ratetwohomogeneousvols_, stepindex_, targetVariance_, testIfSolutionExists(), anonymous_namespace{gaussianquadratures.cpp}::tolerance, totalVar_, w0_, and w1_.
Referenced by QuantLib::CTSMMCapletAlphaFormCalibration::capletAlphaFormCalibration().
{
        stepindex_=stepindex;
        rateonevols_=rateonevols;
        ratetwohomogeneousvols_=ratetwohomogeneousvols;
        putativevols_.resize(ratetwohomogeneousvols_.size());
        correlations_=correlations;
        w0_=w0;
        w1_=w1;
        totalVar_=0;
        for (Size i=0; i <=static_cast<Size>(stepindex)+1; ++i)
            totalVar_+=ratetwohomogeneousvols[i]*ratetwohomogeneousvols[i];
        targetVariance_=targetVariance;
        // constant part will not depend on alpha
        constantPart_ =0.0;
        for (Integer i=0; i < stepindex+1; ++i)
            constantPart_+=rateonevols[i]*rateonevols[i];
        constantPart_ *= w0*w0;
        Real alpha1 = alphaMin;
        Real alpha2 = alphaMax;
        // compute linear part with initial alpha
        bool alpha0OK = testIfSolutionExists(alpha0);
        bool alphaMaxOK = testIfSolutionExists(alphaMax);
        bool alphaMinOK = testIfSolutionExists(alphaMin);
        bool foundOKPoint = alpha0OK || alphaMaxOK || alphaMinOK;
        if (foundOKPoint) {
            if (!alphaMinOK) {
                // lower alpha is bad
                if (alpha0OK) {
                    // must die somewhere in between
                    alpha1 = FindLowestOK<AlphaFinder>(
                         alphaMin,
                         alpha0,
                         tolerance,
                        *this,
                         &AlphaFinder::testIfSolutionExists);
                } else {
                    // alphaMaxOK must be true to get here
                    alpha1 = FindLowestOK<AlphaFinder>(
                         alpha0,
                         alphaMax,
                         tolerance,
                        *this,
                         &AlphaFinder::testIfSolutionExists);
                }
            }
            if (!alphaMaxOK) {
                // higher alpha is bad
                alpha2 = FindHighestOK<AlphaFinder>(
                     alpha1,
                     alphaMax,
                     tolerance,
                     *this,
                     &AlphaFinder::testIfSolutionExists);
            } else
                alpha2= alphaMax;
            }
        else {
            // ok let's see if we can find a value of alpha that works
            bool foundUpOK = false;
            bool foundDownOK = false;
            Real alphaUp = alpha0, alphaDown = alpha0;
            Real stepSize = (alphaMax-alpha0)/steps;
            for (Size j=0;
                 j<static_cast<Size>(steps) && !foundUpOK && !foundDownOK;
                 ++j) {
                alphaUp = alpha0+j*stepSize;
                foundUpOK=testIfSolutionExists(alphaUp);
                alphaDown = alpha0-j*stepSize;
                foundDownOK=testIfSolutionExists(alphaDown);
            }
            foundOKPoint = foundUpOK || foundDownOK;
            if (!foundOKPoint)
                return false;
            if (foundUpOK) {
                alpha1 = alphaUp;
                alpha2 = FindHighestOK<AlphaFinder>(
                     alpha1,
                     alphaMax,
                     tolerance,
                     *this,
                     &AlphaFinder::testIfSolutionExists);
            } else {
                alpha2 = alphaDown;
                alpha1 = FindLowestOK<AlphaFinder>(
                     alphaMin,
                     alpha2,
                     tolerance,
                    *this,
                     &AlphaFinder::testIfSolutionExists);
            }
        }
        // we have now found alpha1, alpha2 such that solution exists
        // at endpoints. we now want to minimize within that interval
        bool failed;
        alpha =  Minimize<AlphaFinder>(
                                        alpha1,
                                        alpha2,
                                        tolerance,
                                        *this,
                                        &AlphaFinder::homogeneityfailure,
                                        &AlphaFinder::testIfSolutionExists,
                                        failed) ;
        finalPart(alpha,
                  stepindex,
                  ratetwohomogeneousvols,
                  computeQuadraticPart(alpha),
                  computeLinearPart(alpha),
                  constantPart_,
                  alpha,
                  a,
                  b,
                  ratetwovols);
        return true;;
    }
bool QuantLib::AlphaFinder::testIfSolutionExists (Real alpha) [private]
Definition at line 278 of file alphafinder.cpp.
References computeLinearPart(), computeQuadraticPart(), constantPart_, finalPart(), putativevols_, ratetwohomogeneousvols_, stepindex_, targetVariance_, and valueAtTurningPoint().
Referenced by solveWithMaxHomogeneity().
{
        bool aExists =  valueAtTurningPoint(alpha)<targetVariance_;
        if (!aExists)
            return false;
        Real dum1, dum2, dum3;
        return finalPart(alpha,
                         stepindex_,
                         ratetwohomogeneousvols_,
                         computeQuadraticPart(alpha),
                         computeLinearPart(alpha),
                         constantPart_,
                         dum1,
                         dum2,
                         dum3,
                         putativevols_);
    }
Real QuantLib::AlphaFinder::valueAtTurningPoint (Real alpha) [private]
Definition at line 264 of file alphafinder.cpp.
References computeLinearPart(), computeQuadraticPart(), constantPart_, linearPart_, quadraticPart_, and QuantLib::quadratic::valueAtTurningPoint().
Referenced by minusValueAtTurningPoint(), solve(), and testIfSolutionExists().
{
        linearPart_ = computeLinearPart(alpha);
        quadraticPart_ = computeQuadraticPart(alpha);
        quadratic q(quadraticPart_, linearPart_, constantPart_);
        Real valueAtTP =q.valueAtTurningPoint();
        return valueAtTP;
    }
Member Data Documentation
Real QuantLib::AlphaFinder::constantPart_ [private]
Definition at line 90 of file alphafinder.hpp.
Referenced by homogeneityfailure(), solve(), solveWithMaxHomogeneity(), testIfSolutionExists(), and valueAtTurningPoint().
std::vector<Real> QuantLib::AlphaFinder::correlations_ [private]
Definition at line 88 of file alphafinder.hpp.
Referenced by computeLinearPart(), solve(), and solveWithMaxHomogeneity().
Real QuantLib::AlphaFinder::linearPart_ [private]
Definition at line 90 of file alphafinder.hpp.
Referenced by solve(), and valueAtTurningPoint().
boost::shared_ptr<AlphaForm> QuantLib::AlphaFinder::parametricform_ [private]
Definition at line 84 of file alphafinder.hpp.
Referenced by computeLinearPart(), computeQuadraticPart(), and finalPart().
std::vector<Volatility> QuantLib::AlphaFinder::putativevols_ [private]
Definition at line 87 of file alphafinder.hpp.
Referenced by homogeneityfailure(), solveWithMaxHomogeneity(), and testIfSolutionExists().
Real QuantLib::AlphaFinder::quadraticPart_ [private]
Definition at line 90 of file alphafinder.hpp.
Referenced by solve(), and valueAtTurningPoint().
std::vector<Volatility> QuantLib::AlphaFinder::rateonevols_ [private]
Definition at line 86 of file alphafinder.hpp.
Referenced by computeLinearPart(), solve(), and solveWithMaxHomogeneity().
std::vector<Volatility> QuantLib::AlphaFinder::ratetwohomogeneousvols_ [private]
Definition at line 86 of file alphafinder.hpp.
Referenced by computeLinearPart(), computeQuadraticPart(), homogeneityfailure(), solve(), solveWithMaxHomogeneity(), and testIfSolutionExists().
Integer QuantLib::AlphaFinder::stepindex_ [private]
Definition at line 85 of file alphafinder.hpp.
Referenced by computeLinearPart(), computeQuadraticPart(), homogeneityfailure(), solve(), solveWithMaxHomogeneity(), and testIfSolutionExists().
Real QuantLib::AlphaFinder::targetVariance_ [private]
Definition at line 91 of file alphafinder.hpp.
Referenced by finalPart(), solve(), solveWithMaxHomogeneity(), and testIfSolutionExists().
Real QuantLib::AlphaFinder::totalVar_ [private]
Definition at line 91 of file alphafinder.hpp.
Referenced by finalPart(), solve(), and solveWithMaxHomogeneity().
Real QuantLib::AlphaFinder::w0_ [private]
Definition at line 89 of file alphafinder.hpp.
Referenced by computeLinearPart(), solve(), and solveWithMaxHomogeneity().
Real QuantLib::AlphaFinder::w1_ [private]
Definition at line 89 of file alphafinder.hpp.
Referenced by computeLinearPart(), computeQuadraticPart(), solve(), and solveWithMaxHomogeneity().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/models/alphafinder.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/models/alphafinder.cpp