QuantLib: QuantLib::TreeCapFloorEngine Class Reference
QuantLib::TreeCapFloorEngine Class Reference
Numerical lattice engine for cap/floors.
#include <treecapfloorengine.hpp>
Public Member Functions
void calculate () const
Constructors
Note:
the term structure is only needed when the short-rate model cannot provide one itself.
TreeCapFloorEngine (const boost::shared_ptr< ShortRateModel > &model, Size timeSteps, const Handle< YieldTermStructure > &termStructure=Handle< YieldTermStructure >())
TreeCapFloorEngine (const boost::shared_ptr< ShortRateModel > &model, const TimeGrid &timeGrid, const Handle< YieldTermStructure > &termStructure=Handle< YieldTermStructure >())
Private Attributes
Handle< YieldTermStructure > termStructure_
Detailed Description
Numerical lattice engine for cap/floors.
Definition at line 34 of file treecapfloorengine.hpp.
Constructor & Destructor Documentation
QuantLib::TreeCapFloorEngine::TreeCapFloorEngine (const boost::shared_ptr< ShortRateModel > & model, Size timeSteps, const Handle< YieldTermStructure > & termStructure = Handle<YieldTermStructure>())
Definition at line 26 of file treecapfloorengine.cpp.
References QuantLib::Observer::registerWith(), and termStructure_.
    : LatticeShortRateModelEngine<CapFloor::arguments,
                                  CapFloor::results >(model, timeSteps),
      termStructure_(termStructure) {
        registerWith(termStructure_);
    }
QuantLib::TreeCapFloorEngine::TreeCapFloorEngine (const boost::shared_ptr< ShortRateModel > & model, const TimeGrid & timeGrid, const Handle< YieldTermStructure > & termStructure = Handle<YieldTermStructure>())
Definition at line 36 of file treecapfloorengine.cpp.
References QuantLib::Observer::registerWith(), and termStructure_.
    : LatticeShortRateModelEngine<CapFloor::arguments,
                                  CapFloor::results>(model, timeGrid),
      termStructure_(termStructure) {
        registerWith(termStructure_);
    }
Member Function Documentation
void QuantLib::TreeCapFloorEngine::calculate () const [virtual]
Implements QuantLib::PricingEngine.
Definition at line 46 of file treecapfloorengine.cpp.
References QuantLib::GenericEngine< CapFloor::arguments, CapFloor::results >::arguments_, anonymous_namespace{marketmodel.cpp}::dayCounter, QuantLib::Handle< T >::empty(), QuantLib::CapFloor::arguments::endDates, QuantLib::DiscretizedAsset::initialize(), QuantLib::LatticeShortRateModelEngine< CapFloor::arguments, CapFloor::results >::lattice_, QuantLib::DiscretizedCapFloor::mandatoryTimes(), QuantLib::GenericModelEngine< ShortRateModel, CapFloor::arguments, CapFloor::results >::model_, QuantLib::DiscretizedAsset::presentValue(), QL_REQUIRE, QuantLib::GenericEngine< CapFloor::arguments, CapFloor::results >::results_, QuantLib::DiscretizedAsset::rollback(), QuantLib::CapFloor::arguments::startDates, QuantLib::TermStructureConsistentModel::termStructure(), termStructure_, QuantLib::LatticeShortRateModelEngine< CapFloor::arguments, CapFloor::results >::timeSteps_, and QuantLib::DayCounter::yearFraction().
{
        QL_REQUIRE(!model_.empty(), "no model specified");
        Date referenceDate;
        DayCounter dayCounter;
        boost::shared_ptr<TermStructureConsistentModel> tsmodel =
            boost::dynamic_pointer_cast<TermStructureConsistentModel>(*model_);
        if (tsmodel) {
            referenceDate = tsmodel->termStructure()->referenceDate();
            dayCounter = tsmodel->termStructure()->dayCounter();
        } else {
            referenceDate = termStructure_->referenceDate();
            dayCounter = termStructure_->dayCounter();
        }
        DiscretizedCapFloor capfloor(arguments_, referenceDate, dayCounter);
        boost::shared_ptr<Lattice> lattice;
        if (lattice_) {
            lattice = lattice_;
        } else {
            std::vector<Time> times = capfloor.mandatoryTimes();
            TimeGrid timeGrid(times.begin(), times.end(), timeSteps_);
            lattice = model_->tree(timeGrid);
        }
        Time firstTime = dayCounter.yearFraction(referenceDate,
                                                 arguments_.startDates.front());
        Time lastTime = dayCounter.yearFraction(referenceDate,
                                                arguments_.endDates.back());
        capfloor.initialize(lattice, lastTime);
        capfloor.rollback(firstTime);
        results_.value = capfloor.presentValue();
    }
Member Data Documentation
Handle<YieldTermStructure> QuantLib::TreeCapFloorEngine::termStructure_ [private]
Definition at line 54 of file treecapfloorengine.hpp.
Referenced by calculate(), and TreeCapFloorEngine().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/capfloor/treecapfloorengine.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/capfloor/treecapfloorengine.cpp