QuantLib: QuantLib::InflationIndex Class Reference
QuantLib::InflationIndex Class Reference
Base class for inflation-rate indexes,.
#include <inflationindex.hpp>
Public Member Functions
InflationIndex (const std::string &familyName, const Region &region, bool revised, bool interpolated, Frequency frequency, const Period &availabilitiyLag, const Currency &currency)
Index interface
std::string name () const
Returns the name of the index.
Calendar fixingCalendar () const
bool isValidFixingDate (const Date &fixingDate) const
returns TRUE if the fixing date is a valid one
Rate fixing (const Date &fixingDate, bool forecastTodaysFixing=false) const =0
void addFixing (const Date &fixingDate, Rate fixing, bool forceOverwrite=false)
Observer interface
void update ()
Inspectors
std::string familyName () const
Region region () const
bool revised () const
bool interpolated () const
Frequency frequency () const
Period availabilityLag () const
Currency currency () const
Protected Attributes
Date referenceDate_
std::string familyName_
Region region_
bool revised_
bool interpolated_
Frequency frequency_
Period availabilityLag_
Currency currency_
Private Attributes
std::string name_
Detailed Description
Base class for inflation-rate indexes,.
Definition at line 39 of file inflationindex.hpp.
Constructor & Destructor Documentation
QuantLib::InflationIndex::InflationIndex (const std::string & familyName, const Region & region, bool revised, bool interpolated, Frequency frequency, const Period & availabilitiyLag, const Currency & currency)
An inflation index may return interpolated values. These are linearly interpolated values with act/act convention within a period. Note that stored "fixings" are always flat (constant) within a period and interpolated as needed. This is because interpolation adds an addional availability lag (because you always need the next period to give the previous period's value) and enables storage of the most recent uninterpolated value.
Definition at line 26 of file inflationindex.cpp.
References familyName_, QuantLib::Singleton< Settings >::instance(), QuantLib::Singleton< IndexManager >::instance(), QuantLib::Region::name(), name(), name_, region_, and QuantLib::Observer::registerWith().
    : familyName_(familyName), region_(region),
      revised_(revised), interpolated_(interpolated),
      frequency_(frequency), availabilityLag_(availabilityLag),
      currency_(currency) {
        name_ = region_.name() + " " + familyName_;
        registerWith(Settings::instance().evaluationDate());
        registerWith(IndexManager::instance().notifier(name()));
    }
Member Function Documentation
void QuantLib::InflationIndex::addFixing (const Date & fixingDate, Rate fixing, bool forceOverwrite = false) [virtual]
this method creates all the "fixings" for the relevant period of the index. E.g. for monthly indices it will put the same value in every calendar day in the month.
Reimplemented from QuantLib::Index.
Definition at line 48 of file inflationindex.cpp.
References QuantLib::Index::addFixings(), anonymous_namespace{marketmodel.cpp}::dates, fixing(), frequency_, and QuantLib::inflationPeriod().
{
        std::pair<Date,Date> lim = inflationPeriod(fixingDate, frequency_);
        Size n = lim.second - lim.first + 1;
        std::vector<Date> dates(n);
        std::vector<Rate> rates(n);
        for (Size i=0; i<n; ++i) {
            dates[i] = lim.first + i;
            rates[i] = fixing;
        }
        Index::addFixings(dates.begin(), dates.end(),
                          rates.begin(), forceOverwrite);
    }
Period QuantLib::InflationIndex::availabilityLag () const [inline]
The availability lag describes when the index is available, not how it is used. Specifically the fixing for, say, January, may only be available in April but the index will always return the index value applicable for January as its January fixing (independent of the lag in availability).
Definition at line 240 of file inflationindex.hpp.
References availabilityLag_.
Referenced by InflationTest::testYYIndex(), and InflationTest::testZeroIndex().
{
        return availabilityLag_;
    }
Currency QuantLib::InflationIndex::currency () const [inline]
Definition at line 244 of file inflationindex.hpp.
References currency_.
{
        return currency_;
    }
std::string QuantLib::InflationIndex::familyName () const [inline]
Definition at line 220 of file inflationindex.hpp.
References familyName_.
{
        return familyName_;
    }
Rate QuantLib::InflationIndex::fixing (const Date & fixingDate, bool forecastTodaysFixing = false) const [pure virtual]
Forecasting index values requires an inflation term structure. The inflation term structure (ITS) defines the usual lag (not the index). I.e. an ITS is always relatve to a base date that is earlier than its asof date. This must be so because indices are available only with a lag. However, the index availability lag only sets a minimum lag for the ITS. An ITS may be relative to an earlier date, e.g. an index may have a 2-month delay in publication but the inflation swaps may take as their base the index 3 months before.
Implements QuantLib::Index.
Implemented in QuantLib::YoYInflationIndex, and QuantLib::ZeroInflationIndex.
Referenced by addFixing().
Calendar QuantLib::InflationIndex::fixingCalendar () const [virtual]
Inflation indices do not have fixing calendars. An inflation index value is valid for every day (including weekends) of a calendar period. I.e. it uses the NullCalendar as its fixing calendar.
Implements QuantLib::Index.
Definition at line 43 of file inflationindex.cpp.
References anonymous_namespace{marketmodel.cpp}::c.
{
        static NullCalendar c;
        return c;
    }
Frequency QuantLib::InflationIndex::frequency () const [inline]
Definition at line 236 of file inflationindex.hpp.
References frequency_.
Referenced by QuantLib::ZeroInflationIndex::forecastFixing(), InflationTest::testYYIndex(), and InflationTest::testZeroIndex().
{
        return frequency_;
    }
bool QuantLib::InflationIndex::interpolated () const [inline]
Forecasting index values using an inflation term structure uses the interpolation of the inflation term structure unless interpolation is set to false. In this case the extrapolated values are constant within each period taking the mid-period extrapolated value.
Definition at line 232 of file inflationindex.hpp.
References interpolated_.
Referenced by QuantLib::YoYInflationIndex::fixing(), QuantLib::ZeroInflationIndex::forecastFixing(), QuantLib::YoYInflationIndex::forecastFixing(), InflationTest::testYYIndex(), and InflationTest::testZeroIndex().
{
        return interpolated_;
    }
bool QuantLib::InflationIndex::isValidFixingDate (const Date & fixingDate) const [inline, virtual]
returns TRUE if the fixing date is a valid one
Implements QuantLib::Index.
Definition at line 68 of file inflationindex.hpp.
{ return true; }
std::string QuantLib::InflationIndex::name () const [inline, virtual]
Returns the name of the index.
Warning:
This method is used for output and comparison between indexes. It is not meant to be used for writing switch-on-type code.
Implements QuantLib::Index.
Definition at line 212 of file inflationindex.hpp.
References name_.
Referenced by QuantLib::ZeroInflationIndex::fixing(), QuantLib::YoYInflationIndex::fixing(), QuantLib::ZeroInflationIndex::forecastFixing(), InflationIndex(), InflationTest::testYYIndex(), and InflationTest::testZeroIndex().
{
        return name_;
    }
Region QuantLib::InflationIndex::region () const [inline]
Definition at line 224 of file inflationindex.hpp.
References region_.
{
        return region_;
    }
bool QuantLib::InflationIndex::revised () const [inline]
Definition at line 228 of file inflationindex.hpp.
References revised_.
Referenced by InflationTest::testYYIndex(), and InflationTest::testZeroIndex().
{
        return revised_;
    }
void QuantLib::InflationIndex::update () [inline, virtual]
This method must be implemented in derived classes. An instance of Observer does not call this method directly: instead, it will be called by the observables the instance registered with when they need to notify any changes.
Implements QuantLib::Observer.
Definition at line 216 of file inflationindex.hpp.
References QuantLib::Observable::notifyObservers().
{
        notifyObservers();
    }
Member Data Documentation
Period QuantLib::InflationIndex::availabilityLag_ [protected]
Definition at line 129 of file inflationindex.hpp.
Referenced by availabilityLag(), QuantLib::ZeroInflationIndex::clone(), QuantLib::YoYInflationIndex::clone(), QuantLib::YoYInflationIndex::fixing(), and QuantLib::ZeroInflationIndex::needsForecast().
Currency QuantLib::InflationIndex::currency_ [protected]
Definition at line 130 of file inflationindex.hpp.
Referenced by QuantLib::ZeroInflationIndex::clone(), QuantLib::YoYInflationIndex::clone(), and currency().
std::string QuantLib::InflationIndex::familyName_ [protected]
Definition at line 124 of file inflationindex.hpp.
Referenced by QuantLib::ZeroInflationIndex::clone(), QuantLib::YoYInflationIndex::clone(), familyName(), and InflationIndex().
Frequency QuantLib::InflationIndex::frequency_ [protected]
Definition at line 128 of file inflationindex.hpp.
Referenced by addFixing(), QuantLib::ZeroInflationIndex::clone(), QuantLib::YoYInflationIndex::clone(), QuantLib::ZeroInflationIndex::fixing(), QuantLib::YoYInflationIndex::fixing(), QuantLib::YoYInflationIndex::forecastFixing(), frequency(), and QuantLib::ZeroInflationIndex::needsForecast().
bool QuantLib::InflationIndex::interpolated_ [protected]
Definition at line 127 of file inflationindex.hpp.
Referenced by QuantLib::ZeroInflationIndex::clone(), QuantLib::YoYInflationIndex::clone(), QuantLib::ZeroInflationIndex::fixing(), interpolated(), and QuantLib::ZeroInflationIndex::needsForecast().
std::string QuantLib::InflationIndex::name_ [private]
Definition at line 132 of file inflationindex.hpp.
Referenced by InflationIndex(), and name().
Date QuantLib::InflationIndex::referenceDate_ [protected]
Definition at line 123 of file inflationindex.hpp.
Region QuantLib::InflationIndex::region_ [protected]
Definition at line 125 of file inflationindex.hpp.
Referenced by QuantLib::ZeroInflationIndex::clone(), QuantLib::YoYInflationIndex::clone(), InflationIndex(), and region().
bool QuantLib::InflationIndex::revised_ [protected]
Definition at line 126 of file inflationindex.hpp.
Referenced by QuantLib::ZeroInflationIndex::clone(), QuantLib::YoYInflationIndex::clone(), and revised().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/indexes/inflationindex.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/indexes/inflationindex.cpp