QuantLib: QuantLib::CdsOption Class Reference
QuantLib::CdsOption Class Reference
CDS option.
#include <cdsoption.hpp>
Classes
class arguments
Arguments for CDS-option calculation
class engine
base class for swaption engines
class results
Results from CDS-option calculation
Public Member Functions
CdsOption (const boost::shared_ptr< CreditDefaultSwap > &swap, const boost::shared_ptr< Exercise > &exercise, bool knocksOut=true)
Instrument interface
bool isExpired () const
returns whether the instrument might have value greater than zero.
void setupArguments (PricingEngine::arguments *) const
Inspectors
const boost::shared_ptr
< CreditDefaultSwap > & underlyingSwap () const
Calculations
Rate atmRate () const
Real riskyAnnuity () const
Volatility impliedVolatility (Real price, const Handle< YieldTermStructure > &termStructure, const Handle< DefaultProbabilityTermStructure > &, Real recoveryRate, Real accuracy=1.e-4, Size maxEvaluations=100, Volatility minVol=1.0e-7, Volatility maxVol=4.0) const
Private Member Functions
void setupExpired () const
void fetchResults (const PricingEngine::results *) const
Private Attributes
boost::shared_ptr
< CreditDefaultSwap > swap_
bool knocksOut_
Real riskyAnnuity_
Detailed Description
CDS option.
The side of the swaption is set by choosing the side of the CDS. A receiver CDS option is a right to buy an underlying CDS selling protection and receiving a coupon. A payer CDS option is a right to buy an underlying CDS buying protection and paying coupon.
Definition at line 43 of file cdsoption.hpp.
Constructor & Destructor Documentation
QuantLib::CdsOption::CdsOption (const boost::shared_ptr< CreditDefaultSwap > & swap, const boost::shared_ptr< Exercise > & exercise, bool knocksOut = true)
Definition at line 70 of file cdsoption.cpp.
References QuantLib::Protection::Buyer, knocksOut_, QL_REQUIRE, QuantLib::Observer::registerWith(), and swap_.
    : Option(boost::shared_ptr<Payoff>(new NullPayoff), exercise),
      swap_(swap), knocksOut_(knocksOut) {
        QL_REQUIRE(swap->side() == Protection::Buyer || knocksOut_,
                   "receiver CDS options must knock out");
        QL_REQUIRE(!swap->upfront(), "underlying must be running-spread only");
        registerWith(swap_);
    }
Member Function Documentation
Rate QuantLib::CdsOption::atmRate () const
Definition at line 113 of file cdsoption.cpp.
References swap_.
{
        return swap_->fairSpread();
    }
void QuantLib::CdsOption::fetchResults (const PricingEngine::results * r) const [private, virtual]
When a derived result structure is defined for an instrument, this method should be overridden to read from it. This is mandatory in case a pricing engine is used.
Reimplemented from QuantLib::Instrument.
Definition at line 103 of file cdsoption.cpp.
References QL_ENSURE, QuantLib::CdsOption::results::riskyAnnuity, and riskyAnnuity_.
{
        Option::fetchResults(r);
        const CdsOption::results* results =
            dynamic_cast<const CdsOption::results*>(r);
        QL_ENSURE(results != 0, "wrong results type");
        riskyAnnuity_ = results->riskyAnnuity;
    }
Volatility QuantLib::CdsOption::impliedVolatility (Real price, const Handle< YieldTermStructure > & termStructure, const Handle< DefaultProbabilityTermStructure > & probability, Real recoveryRate, Real accuracy = 1.e-4, Size maxEvaluations = 100, Volatility minVol = 1.0e-7, Volatility maxVol = 4.0) const
Definition at line 123 of file cdsoption.cpp.
References QuantLib::Instrument::calculate(), anonymous_namespace{interpolations.cpp}::f(), isExpired(), QL_REQUIRE, QuantLib::Solver1D< Impl >::setMaxEvaluations(), and QuantLib::Solver1D< Impl >::solve().
{
        calculate();
        QL_REQUIRE(!isExpired(), "instrument expired");
        Volatility guess = 0.10;
        ImpliedVolHelper f(*this, probability, recoveryRate,
                           termStructure, targetValue);
        Brent solver;
        solver.setMaxEvaluations(maxEvaluations);
        return solver.solve(f, accuracy, guess, minVol, maxVol);
    }
bool QuantLib::CdsOption::isExpired () const [virtual]
returns whether the instrument might have value greater than zero.
Implements QuantLib::Instrument.
Definition at line 81 of file cdsoption.cpp.
References QuantLib::Option::exercise_.
Referenced by impliedVolatility().
{
        return detail::simple_event(exercise_->dates().back()).hasOccurred();
    }
Real QuantLib::CdsOption::riskyAnnuity () const
Definition at line 117 of file cdsoption.cpp.
References QuantLib::Instrument::calculate(), QL_REQUIRE, and riskyAnnuity_.
Referenced by QuantLib::CdsOption::results::reset().
{
        calculate();
        QL_REQUIRE(riskyAnnuity_ != Null<Real>(), "risky annuity not provided");
        return riskyAnnuity_;
    }
void QuantLib::CdsOption::setupArguments (PricingEngine::arguments *) const [virtual]
When a derived argument structure is defined for an instrument, this method should be overridden to fill it. This is mandatory in case a pricing engine is used.
Reimplemented from QuantLib::Option.
Definition at line 90 of file cdsoption.cpp.
References QuantLib::CdsOption::arguments::knocksOut, knocksOut_, QL_REQUIRE, QuantLib::CdsOption::arguments::swap, and swap_.
Referenced by QuantLib::anonymous_namespace{cdsoption.cpp}::ImpliedVolHelper::ImpliedVolHelper().
{
        swap_->setupArguments(args);
        Option::setupArguments(args);
        CdsOption::arguments* arguments =
            dynamic_cast<CdsOption::arguments*>(args);
        QL_REQUIRE(arguments != 0, "wrong argument type");
        arguments->swap      = swap_;
        arguments->knocksOut = knocksOut_;
    }
void QuantLib::CdsOption::setupExpired () const [private, virtual]
This method must leave the instrument in a consistent state when the expiration condition is met.
Reimplemented from QuantLib::Instrument.
Definition at line 85 of file cdsoption.cpp.
References riskyAnnuity_.
{
        Instrument::setupExpired();
        riskyAnnuity_ = 0.0;
    }
const boost::shared_ptr<CreditDefaultSwap>& QuantLib::CdsOption::underlyingSwap () const [inline]
Definition at line 59 of file cdsoption.hpp.
References swap_.
{
            return swap_;
        }
Member Data Documentation
bool QuantLib::CdsOption::knocksOut_ [private]
Definition at line 80 of file cdsoption.hpp.
Referenced by CdsOption(), and setupArguments().
Real QuantLib::CdsOption::riskyAnnuity_ [mutable, private]
Definition at line 82 of file cdsoption.hpp.
Referenced by fetchResults(), riskyAnnuity(), and setupExpired().
boost::shared_ptr<CreditDefaultSwap> QuantLib::CdsOption::swap_ [private]
Definition at line 79 of file cdsoption.hpp.
Referenced by atmRate(), CdsOption(), setupArguments(), and underlyingSwap().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/cdsoption.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/cdsoption.cpp