QuantLib: QuantLib::Array Class Reference
QuantLib::Array Class Reference
1-D array used in linear algebra.
#include <array.hpp>
Public Types
typedef Size size_type
typedef Real value_type
typedef Real * iterator
typedef const Real * const_iterator
typedef
boost::reverse_iterator
< iterator > reverse_iterator
typedef
boost::reverse_iterator
< const_iterator > const_reverse_iterator
Public Member Functions
Constructors, destructor, and assignment
Array (Size size=0)
creates the array with the given dimension
Array (Size size, Real value)
creates the array and fills it with value
Array (Size size, Real value, Real increment)
creates the array and fills it according to \(a_{0} = value, a_{i}=a_{i-1}+increment \)
Array (const Array &)
Array (const Disposable< Array > &)
template<class ForwardIterator >
Array (ForwardIterator begin, ForwardIterator end)
creates the array from an iterable sequence
Array & operator= (const Array &)
Array & operator= (const Disposable< Array > &)
bool operator== (const Array &) const
bool operator!= (const Array &) const
Vector algebra
v += x and similar operation involving a scalar value are shortcuts for \(\forall i : v_i = v_i + x \)
v *= w and similar operation involving two vectors are shortcuts for \(\forall i : v_i = v_i \times w_i \)
Precondition:
all arrays involved in an algebraic expression must have the same size.
const Array & operator+= (const Array &)
const Array & operator+= (Real)
const Array & operator-= (const Array &)
const Array & operator-= (Real)
const Array & operator*= (const Array &)
const Array & operator*= (Real)
const Array & operator/= (const Array &)
const Array & operator/= (Real)
Element access
Real operator[] (Size) const
read-only
Real at (Size) const
Real front () const
Real back () const
Real & operator[] (Size)
read-write
Real & at (Size)
Real & front ()
Real & back ()
Inspectors
Size size () const
dimension of the array
bool empty () const
whether the array is empty
Iterator access
const_iterator begin () const
iterator begin ()
const_iterator end () const
iterator end ()
const_reverse_iterator rbegin () const
reverse_iterator rbegin ()
const_reverse_iterator rend () const
reverse_iterator rend ()
Utilities
void swap (Array &)
Private Attributes
boost::scoped_array< Real > data_
Size n_
Related Functions
(Note that these are not member functions.)
Real DotProduct (const Array &, const Array &)
const Disposable< Array > operator+ (const Array &v)
const Disposable< Array > operator- (const Array &v)
const Disposable< Array > operator+ (const Array &, const Array &)
const Disposable< Array > operator+ (const Array &, Real)
const Disposable< Array > operator+ (Real, const Array &)
const Disposable< Array > operator- (const Array &, const Array &)
const Disposable< Array > operator- (const Array &, Real)
const Disposable< Array > operator- (Real, const Array &)
const Disposable< Array > operator* (const Array &, const Array &)
const Disposable< Array > operator* (const Array &, Real)
const Disposable< Array > operator* (Real, const Array &)
const Disposable< Array > operator/ (const Array &, const Array &)
const Disposable< Array > operator/ (const Array &, Real)
const Disposable< Array > operator/ (Real, const Array &)
const Disposable< Array > Abs (const Array &)
const Disposable< Array > Sqrt (const Array &)
const Disposable< Array > Log (const Array &)
const Disposable< Array > Exp (const Array &)
void swap (Array &, Array &)
std::ostream & operator<< (std::ostream &, const Array &)
Detailed Description
1-D array used in linear algebra.
This class implements the concept of vector as used in linear algebra. As such, it is not meant to be used as a container - std::vector should be used instead.
Test:
construction of arrays is checked in a number of cases
Definition at line 51 of file array.hpp.
Member Typedef Documentation
typedef const Real* QuantLib::Array::const_iterator
Definition at line 118 of file array.hpp.
typedef boost::reverse_iterator<const_iterator> QuantLib::Array::const_reverse_iterator
Definition at line 120 of file array.hpp.
typedef Real* QuantLib::Array::iterator
Definition at line 117 of file array.hpp.
typedef boost::reverse_iterator<iterator> QuantLib::Array::reverse_iterator
Definition at line 119 of file array.hpp.
typedef Size QuantLib::Array::size_type
Definition at line 115 of file array.hpp.
typedef Real QuantLib::Array::value_type
Definition at line 116 of file array.hpp.
Constructor & Destructor Documentation
QuantLib::Array::Array (Size size = 0) [inline, explicit]
creates the array with the given dimension
Definition at line 208 of file array.hpp.
    : data_(size ? new Real[size] : (Real*)(0)), n_(size) {}
QuantLib::Array::Array (Size size, Real value) [inline]
creates the array and fills it with value
Definition at line 211 of file array.hpp.
References begin(), and end().
    : data_(size ? new Real[size] : (Real*)(0)), n_(size) {
        std::fill(begin(),end(),value);
    }
QuantLib::Array::Array (Size size, Real value, Real increment) [inline]
creates the array and fills it according to \(a_{0} = value, a_{i}=a_{i-1}+increment \)
Definition at line 216 of file array.hpp.
References begin(), and end().
    : data_(size ? new Real[size] : (Real*)(0)), n_(size) {
        for (iterator i=begin(); i!=end(); i++,value+=increment)
            *i = value;
    }
QuantLib::Array::Array (const Array & from) [inline]
Definition at line 222 of file array.hpp.
References begin(), end(), and n_.
    : data_(from.n_ ? new Real[from.n_] : (Real*)(0)), n_(from.n_) {
        #if defined(QL_PATCH_MSVC) && defined(QL_DEBUG)
        if (n_)
        #endif
        std::copy(from.begin(),from.end(),begin());
    }
QuantLib::Array::Array (const Disposable< Array > & from) [inline]
Definition at line 230 of file array.hpp.
References swap().
    : data_((Real*)(0)), n_(0) {
        swap(const_cast<Disposable<Array>&>(from));
    }
template<class ForwardIterator > QuantLib::Array::Array (ForwardIterator begin, ForwardIterator end) [inline]
creates the array from an iterable sequence
Definition at line 273 of file array.hpp.
References QuantLib::detail::_fill_array_(), data_, and n_.
{
        // Unfortunately, calls such as Array(3, 4) match this constructor.
        // We have to detect integral types and dispatch.
        detail::_fill_array_(*this, data_, n_, begin, end,
                             boost::is_integral<ForwardIterator>());
    }
Member Function Documentation
Real QuantLib::Array::at (Size i) const [inline]
Definition at line 370 of file array.hpp.
References data_, n_, and QL_REQUIRE.
Referenced by QuantLib::Path::at(), and VPPTest::testVPPPricing().
{
        QL_REQUIRE(i<n_,
                   "index (" << i << ") must be less than " << n_ <<
                   ": array access out of range");
        return data_.get()[i];
    }
Real & QuantLib::Array::at (Size i) [inline]
Definition at line 400 of file array.hpp.
References data_, n_, and QL_REQUIRE.
{
        QL_REQUIRE(i<n_,
                   "index (" << i << ") must be less than " << n_ <<
                   ": array access out of range");
        return data_.get()[i];
    }
Real QuantLib::Array::back () const [inline]
Definition at line 384 of file array.hpp.
References data_, n_, and QL_REQUIRE.
Referenced by QuantLib::KlugeExtOUProcess::diffusion(), QuantLib::KlugeExtOUProcess::drift(), QuantLib::KlugeExtOUProcess::evolve(), QuantLib::KlugeExtOUProcess::initialValues(), QuantLib::operator<<(), VPPTest::testKlugeExtOUSpreadOption(), anonymous_namespace{pathgenerator.cpp}::testMultiple(), and VPPTest::testVPPPricing().
{
        #if defined(QL_EXTRA_SAFETY_CHECKS)
        QL_REQUIRE(n_>0, "null Array: array access out of range");
        #endif
        return data_.get()[n_-1];
    }
Real & QuantLib::Array::back () [inline]
Definition at line 414 of file array.hpp.
References data_, n_, and QL_REQUIRE.
{
        #if defined(QL_EXTRA_SAFETY_CHECKS)
        QL_REQUIRE(n_>0, "null Array: array access out of range");
        #endif
        return data_.get()[n_-1];
    }
Array::const_iterator QuantLib::Array::begin () const [inline]
Definition at line 429 of file array.hpp.
References data_.
Referenced by QuantLib::detail::_fill_array_(), QuantLib::Abs(), QuantLib::MinBasketPayoff::accumulate(), QuantLib::MaxBasketPayoff::accumulate(), QuantLib::AverageBasketPayoff::accumulate(), QuantLib::JointStochasticProcess::apply(), QuantLib::FdmArithmeticAverageCondition::applyTo(), QuantLib::FdmSimpleStorageCondition::applyTo(), QuantLib::FdmDividendHandler::applyTo(), QuantLib::TridiagonalOperator::applyTo(), Array(), QuantLib::autocorrelations(), QuantLib::autocovariances(), anonymous_namespace{fdmlinearop.cpp}::axpy(), QuantLib::TripleBandLinearOp::axpyb(), QuantLib::Path::begin(), QuantLib::FdSimpleKlugeExtOUVPPEngine::calculate(), QuantLib::GeneralLinearLeastSquares::calculate(), QuantLib::DotProduct(), QuantLib::detail::double_ft(), QuantLib::JointStochasticProcess::drift(), QuantLib::LiborForwardModelProcess::drift(), QuantLib::KlugeExtOUProcess::drift(), QuantLib::JointStochasticProcess::evolve(), QuantLib::KlugeExtOUProcess::evolve(), QuantLib::LiborForwardModelProcess::evolve(), QuantLib::Exp(), QuantLib::JointStochasticProcess::expectation(), QuantLib::factorReduction(), QuantLib::LevenbergMarquardt::fcn(), QuantLib::genericEarlyExerciseOptimization(), QuantLib::genericLongstaffSchwartzRegression(), QuantLib::JointStochasticProcess::initialValues(), QuantLib::KlugeExtOUProcess::initialValues(), QuantLib::detail::SABRInterpolationImpl< I1, I2 >::interpolationErrors(), QuantLib::Log(), QuantLib::LevenbergMarquardt::minimize(), QuantLib::MultiPathGenerator< GSG >::next(), anonymous_namespace{mclongstaffschwartzengine.cpp}::AmericanMaxPathPricer::operator()(), QuantLib::operator*(), operator*=(), QuantLib::operator+(), operator+=(), QuantLib::operator-(), operator-=(), QuantLib::operator/(), operator/=(), operator==(), QuantLib::outerProduct(), QuantLib::Fdm1DimSolver::performCalculations(), QuantLib::qrDecomposition(), QuantLib::qrSolve(), QuantLib::rankReducedSqrt(), QuantLib::SampledCurve::regrid(), rend(), QuantLib::SampledCurve::sample(), QuantLib::CalibratedModel::setParams(), QuantLib::FdmTimeDepDirichletBoundary::setTime(), QuantLib::JointStochasticProcess::slice(), QuantLib::Sqrt(), QuantLib::SymmetricSchurDecomposition::SymmetricSchurDecomposition(), AutocovariancesTest::testAutoCorrelations(), AutocovariancesTest::testAutoCovariances(), OperatorTest::testConsistency(), ArrayTest::testConstruction(), AutocovariancesTest::testConvolutions(), FastFourierTransformTest::testInverse(), BrownianBridgeTest::testPathGeneration(), BrownianBridgeTest::testVariates(), VPPTest::testVPPIntrinsicValue(), QuantLib::Fdm3DimSolver::thetaAt(), QuantLib::TqrEigenDecomposition::TqrEigenDecomposition(), QuantLib::SampledCurve::transform(), QuantLib::TransformedGrid::TransformedGrid(), QuantLib::SampledCurve::transformGrid(), QuantLib::anonymous_namespace{parametricexercise.cpp}::ValueEstimate::value(), QuantLib::PenaltyFunction< Curve >::value(), and QuantLib::PenaltyFunction< Curve >::values().
{
        return data_.get();
    }
Array::iterator QuantLib::Array::begin () [inline]
Definition at line 433 of file array.hpp.
References data_.
{
        return data_.get();
    }
bool QuantLib::Array::empty () const [inline]
whether the array is empty
Definition at line 425 of file array.hpp.
References n_.
Referenced by QuantLib::TripleBandLinearOp::axpyb(), QuantLib::LongstaffSchwartzMultiPathPricer::calibrate(), QuantLib::SampledCurve::empty(), QuantLib::LfmCovarianceProxy::integratedCovariance(), QuantLib::LfmCovarianceParameterization::integratedCovariance(), QuantLib::LongstaffSchwartzMultiPathPricer::operator()(), QuantLib::ArmijoLineSearch::operator()(), QuantLib::operator<<(), QuantLib::Path::Path(), QuantLib::qrSolve(), QuantLib::BiCGstab::solve(), and ArrayTest::testConstruction().
{
        return n_ == 0;
    }
Array::const_iterator QuantLib::Array::end () const [inline]
Definition at line 437 of file array.hpp.
References data_, and n_.
Referenced by QuantLib::detail::_fill_array_(), QuantLib::Abs(), QuantLib::MinBasketPayoff::accumulate(), QuantLib::MaxBasketPayoff::accumulate(), QuantLib::AverageBasketPayoff::accumulate(), QuantLib::JointStochasticProcess::apply(), QuantLib::FdmArithmeticAverageCondition::applyTo(), QuantLib::FdmSimpleStorageCondition::applyTo(), QuantLib::FdmDividendHandler::applyTo(), QuantLib::TridiagonalOperator::applyTo(), Array(), QuantLib::autocorrelations(), QuantLib::autocovariances(), anonymous_namespace{fdmlinearop.cpp}::axpy(), QuantLib::FdSimpleKlugeExtOUVPPEngine::calculate(), QuantLib::GeneralLinearLeastSquares::calculate(), QuantLib::DotProduct(), QuantLib::detail::double_ft(), QuantLib::JointStochasticProcess::drift(), QuantLib::KlugeExtOUProcess::drift(), QuantLib::Path::end(), QuantLib::KlugeExtOUProcess::evolve(), QuantLib::Exp(), QuantLib::JointStochasticProcess::expectation(), QuantLib::factorReduction(), QuantLib::LevenbergMarquardt::fcn(), QuantLib::genericEarlyExerciseOptimization(), QuantLib::genericLongstaffSchwartzRegression(), QuantLib::JointStochasticProcess::initialValues(), QuantLib::KlugeExtOUProcess::initialValues(), QuantLib::Log(), QuantLib::LevenbergMarquardt::minimize(), anonymous_namespace{mclongstaffschwartzengine.cpp}::AmericanMaxPathPricer::operator()(), QuantLib::operator*(), operator*=(), QuantLib::operator+(), operator+=(), QuantLib::operator-(), operator-=(), QuantLib::operator/(), operator/=(), operator==(), QuantLib::outerProduct(), QuantLib::qrDecomposition(), QuantLib::qrSolve(), QuantLib::rankReducedSqrt(), rbegin(), QuantLib::SampledCurve::regrid(), QuantLib::SampledCurve::sample(), QuantLib::CalibratedModel::setParams(), QuantLib::FdmTimeDepDirichletBoundary::setTime(), QuantLib::Sqrt(), QuantLib::SymmetricSchurDecomposition::SymmetricSchurDecomposition(), AutocovariancesTest::testAutoCorrelations(), AutocovariancesTest::testAutoCovariances(), OperatorTest::testConsistency(), ArrayTest::testConstruction(), AutocovariancesTest::testConvolutions(), FastFourierTransformTest::testInverse(), VPPTest::testVPPIntrinsicValue(), QuantLib::TqrEigenDecomposition::TqrEigenDecomposition(), QuantLib::SampledCurve::transform(), QuantLib::TransformedGrid::TransformedGrid(), QuantLib::SampledCurve::transformGrid(), QuantLib::anonymous_namespace{parametricexercise.cpp}::ValueEstimate::value(), QuantLib::PenaltyFunction< Curve >::value(), and QuantLib::PenaltyFunction< Curve >::values().
{
        return data_.get()+n_;
    }
Array::iterator QuantLib::Array::end () [inline]
Definition at line 441 of file array.hpp.
References data_, and n_.
{
        return data_.get()+n_;
    }
Real QuantLib::Array::front () const [inline]
Definition at line 377 of file array.hpp.
References data_, n_, and QL_REQUIRE.
Referenced by QuantLib::FdmVPPStepCondition::changeState(), QuantLib::KlugeExtOUProcess::evolve(), and VPPTest::testVPPPricing().
{
        #if defined(QL_EXTRA_SAFETY_CHECKS)
        QL_REQUIRE(n_>0, "null Array: array access out of range");
        #endif
        return data_.get()[0];
    }
Real & QuantLib::Array::front () [inline]
Definition at line 407 of file array.hpp.
References data_, n_, and QL_REQUIRE.
{
        #if defined(QL_EXTRA_SAFETY_CHECKS)
        QL_REQUIRE(n_>0, "null Array: array access out of range");
        #endif
        return data_.get()[0];
    }
bool QuantLib::Array::operator!= (const Array & to) const [inline]
Definition at line 291 of file array.hpp.
References operator==().
{
        return !(this->operator==(to));
    }
const Array & QuantLib::Array::operator*= (const Array & v) [inline]
Definition at line 331 of file array.hpp.
References begin(), end(), n_, and QL_REQUIRE.
{
        QL_REQUIRE(n_ == v.n_,
                   "arrays with different sizes (" << n_ << ", "
                   << v.n_ << ") cannot be multiplied");
        std::transform(begin(),end(),v.begin(),begin(),
                       std::multiplies<Real>());
        return *this;
    }
const Array & QuantLib::Array::operator*= (Real x) [inline]
Definition at line 340 of file array.hpp.
References begin(), and end().
{
        std::transform(begin(),end(),begin(),
                       std::bind2nd(std::multiplies<Real>(),x));
        return *this;
    }
const Array & QuantLib::Array::operator+= (const Array & v) [inline]
Definition at line 300 of file array.hpp.
References begin(), end(), n_, and QL_REQUIRE.
{
        QL_REQUIRE(n_ == v.n_,
                   "arrays with different sizes (" << n_ << ", "
                   << v.n_ << ") cannot be added");
        std::transform(begin(),end(),v.begin(),begin(),
                       std::plus<Real>());
        return *this;
    }
const Array & QuantLib::Array::operator+= (Real x) [inline]
Definition at line 310 of file array.hpp.
References begin(), and end().
{
        std::transform(begin(),end(),begin(),
                       std::bind2nd(std::plus<Real>(),x));
        return *this;
    }
const Array & QuantLib::Array::operator-= (const Array & v) [inline]
Definition at line 316 of file array.hpp.
References begin(), end(), n_, and QL_REQUIRE.
{
        QL_REQUIRE(n_ == v.n_,
                   "arrays with different sizes (" << n_ << ", "
                   << v.n_ << ") cannot be subtracted");
        std::transform(begin(),end(),v.begin(),begin(),
                       std::minus<Real>());
        return *this;
    }
const Array & QuantLib::Array::operator-= (Real x) [inline]
Definition at line 325 of file array.hpp.
References begin(), and end().
{
        std::transform(begin(),end(),begin(),
                       std::bind2nd(std::minus<Real>(),x));
        return *this;
    }
const Array & QuantLib::Array::operator/= (const Array & v) [inline]
Definition at line 346 of file array.hpp.
References begin(), end(), n_, and QL_REQUIRE.
{
        QL_REQUIRE(n_ == v.n_,
                   "arrays with different sizes (" << n_ << ", "
                   << v.n_ << ") cannot be divided");
        std::transform(begin(),end(),v.begin(),begin(),
                       std::divides<Real>());
        return *this;
    }
const Array & QuantLib::Array::operator/= (Real x) [inline]
Definition at line 355 of file array.hpp.
References begin(), and end().
{
        std::transform(begin(),end(),begin(),
                       std::bind2nd(std::divides<Real>(),x));
        return *this;
    }
Array & QuantLib::Array::operator= (const Array & from) [inline]
Definition at line 280 of file array.hpp.
References swap().
{
        // strong guarantee
        Array temp(from);
        swap(temp);
        return *this;
    }
Array & QuantLib::Array::operator= (const Disposable< Array > & from) [inline]
Definition at line 295 of file array.hpp.
References swap().
{
        swap(const_cast<Disposable<Array>&>(from));
        return *this;
    }
bool QuantLib::Array::operator== (const Array & to) const [inline]
Definition at line 287 of file array.hpp.
References begin(), end(), and n_.
Referenced by operator!=().
{
        return (n_ == to.n_) && std::equal(begin(), end(), to.begin());
    }
Real QuantLib::Array::operator[] (Size i) const [inline]
read-only
Definition at line 361 of file array.hpp.
References data_, n_, and QL_REQUIRE.
{
        #if defined(QL_EXTRA_SAFETY_CHECKS)
        QL_REQUIRE(i<n_,
                   "index (" << i << ") must be less than " << n_ <<
                   ": array access out of range");
        #endif
        return data_.get()[i];
    }
Real & QuantLib::Array::operator[] (Size i) [inline]
read-write
Definition at line 391 of file array.hpp.
References data_, n_, and QL_REQUIRE.
{
        #if defined(QL_EXTRA_SAFETY_CHECKS)
        QL_REQUIRE(i<n_,
                   "index (" << i << ") must be less than " << n_ <<
                   ": array access out of range");
        #endif
        return data_.get()[i];
    }
Array::const_reverse_iterator QuantLib::Array::rbegin () const [inline]
Definition at line 445 of file array.hpp.
References end().
Referenced by QuantLib::Path::rbegin().
{
        return const_reverse_iterator(end());
    }
Array::reverse_iterator QuantLib::Array::rbegin () [inline]
Definition at line 449 of file array.hpp.
References end().
{
        return reverse_iterator(end());
    }
Array::const_reverse_iterator QuantLib::Array::rend () const [inline]
Definition at line 453 of file array.hpp.
References begin().
Referenced by QuantLib::Path::rend().
{
        return const_reverse_iterator(begin());
    }
Array::reverse_iterator QuantLib::Array::rend () [inline]
Definition at line 457 of file array.hpp.
References begin().
{
        return reverse_iterator(begin());
    }
Size QuantLib::Array::size () const [inline]
dimension of the array
Definition at line 421 of file array.hpp.
References n_.
Referenced by QuantLib::Abs(), QuantLib::SpreadBasketPayoff::accumulate(), QuantLib::BasisIncompleteOrdered::addVector(), QuantLib::DiscretizedConvertible::adjustedGrid(), QuantLib::NinePointLinearOp::apply(), QuantLib::TripleBandLinearOp::apply(), QuantLib::StochasticProcess1D::apply(), QuantLib::FdmG2Op::apply_direction(), QuantLib::FdmHullWhiteOp::apply_direction(), QuantLib::FdmBlackScholesOp::apply_direction(), QuantLib::FdmExtendedOrnsteinUhlenbackOp::apply_direction(), QuantLib::FdmExtOUJumpOp::apply_direction(), QuantLib::FdmHullWhiteOp::apply_mixed(), QuantLib::FdmBlackScholesOp::apply_mixed(), QuantLib::FdmExtendedOrnsteinUhlenbackOp::apply_mixed(), QuantLib::FdmTimeDepDirichletBoundary::applyAfterApplying(), QuantLib::NeumannBC::applyAfterApplying(), QuantLib::DirichletBC::applyAfterApplying(), QuantLib::NeumannBC::applyBeforeSolving(), QuantLib::DirichletBC::applyBeforeSolving(), QuantLib::DiscretizedCallableFixedRateBond::applyCallability(), QuantLib::DiscretizedConvertible::applyCallability(), QuantLib::DiscretizedConvertible::applyConvertibility(), QuantLib::DiscretizedOption::applyExerciseCondition(), QuantLib::DiscretizedVanillaOption::applySpecificCondition(), QuantLib::FdmArithmeticAverageCondition::applyTo(), QuantLib::FdmSimpleStorageCondition::applyTo(), QuantLib::FdmDividendHandler::applyTo(), QuantLib::CurveDependentStepCondition< array_type >::applyTo(), QuantLib::TridiagonalOperator::applyTo(), anonymous_namespace{fdmlinearop.cpp}::axpy(), QuantLib::TripleBandLinearOp::axpyb(), QuantLib::Path::back(), QuantLib::SparseILUPreconditioner::backwardSolve(), QuantLib::FdSimpleKlugeExtOUVPPEngine::calculate(), QuantLib::GeneralLinearLeastSquares::calculate(), QuantLib::LocalBootstrap< Curve >::calculate(), QuantLib::LongstaffSchwartzMultiPathPricer::calibrate(), QuantLib::FdmVPPStepCondition::changeState(), QuantLib::CmsMarketCalibration::compute(), QuantLib::StochasticProcess1D::covariance(), QuantLib::StochasticProcess1D::diffusion(), QuantLib::GeneralLinearLeastSquares::dim(), QuantLib::G2::discountBond(), QuantLib::DotProduct(), QuantLib::StochasticProcess1D::drift(), QuantLib::JointStochasticProcess::evolve(), QuantLib::StochasticProcess1D::evolve(), QuantLib::Exp(), QuantLib::StochasticProcess1D::expectation(), QuantLib::Simplex::extrapolate(), QuantLib::FdmArithmeticAverageCondition::FdmArithmeticAverageCondition(), QuantLib::FdmDividendHandler::FdmDividendHandler(), QuantLib::FdmExtOUJumpOp::FdmExtOUJumpOp(), QuantLib::SparseILUPreconditioner::forwardSolve(), QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::gammaFunc(), QuantLib::BFGS::getUpdatedDirection(), QuantLib::CostFunction::gradient(), QuantLib::LeastSquareFunction::gradient(), QuantLib::TreeLattice1D< BlackScholesLattice< T > >::grid(), QuantLib::ProjectedCostFunction::include(), QuantLib::FdmBatesOp::integro(), QuantLib::LmFixedVolatilityModel::LmFixedVolatilityModel(), QuantLib::lmmTriangularAnglesParametrizationUnconstrained(), QuantLib::Log(), QuantLib::ProjectedCostFunction::mapFreeParameters(), anonymous_namespace{optimizers.cpp}::maxDifference(), QuantLib::LineSearchBasedMethod::minimize(), QuantLib::LevenbergMarquardt::minimize(), QuantLib::Simplex::minimize(), QuantLib::ArmijoLineSearch::operator()(), QuantLib::anonymous_namespace{lsmbasissystem.cpp}::MultiDimFct::operator()(), QuantLib::G2::SwaptionPricingFunction::SolvingFunction::operator()(), QuantLib::operator*(), QuantLib::operator+(), QuantLib::operator-(), QuantLib::operator/(), QuantLib::operator<<(), QuantLib::GaussianQuadrature::order(), QuantLib::Path::Path(), QuantLib::DiscretizedSwap::preAdjustValuesImpl(), QuantLib::DiscretizedCapFloor::preAdjustValuesImpl(), QuantLib::prod(), QuantLib::ProjectedCostFunction::project(), QuantLib::ProjectedCostFunction::ProjectedCostFunction(), QuantLib::qrSolve(), QuantLib::FdmQuantoHelper::quantoAdjustment(), QuantLib::SVD::rank(), QuantLib::SampledCurve::regrid(), QuantLib::DiscretizedConvertible::reset(), QuantLib::anonymous_namespace{capletcoterminalmaxhomogeneity.cpp}::singleRateClosestPointFinder(), QuantLib::SampledCurve::size(), QuantLib::Parameter::size(), QuantLib::GeneralLinearLeastSquares::size(), QuantLib::TransformedGrid::size(), QuantLib::BiCGstab::solve(), QuantLib::FdmG2Op::solve_splitting(), QuantLib::TripleBandLinearOp::solve_splitting(), QuantLib::FdmHullWhiteOp::solve_splitting(), QuantLib::TridiagonalOperator::solveFor(), QuantLib::TridiagonalOperator::SOR(), QuantLib::SparseILUPreconditioner::SparseILUPreconditioner(), QuantLib::Sqrt(), QuantLib::StochasticProcess1D::stdDeviation(), QuantLib::ImplicitEulerScheme::step(), anonymous_namespace{cmsmarketcalibration.cpp}::ParametersConstraint::Impl::test(), QuantLib::PositiveConstraint::Impl::test(), anonymous_namespace{cmsmarketcalibration.cpp}::ParametersConstraint2::Impl::test(), QuantLib::BoundaryConstraint::Impl::test(), OperatorTest::testBSMOperatorConsistency(), ArrayTest::testConstruction(), TqrEigenDecompositionTest::testEigenValueDecomposition(), FastFourierTransformTest::testInverse(), TqrEigenDecompositionTest::testZeroOffDiagEigenValues(), QuantLib::Fdm1DimSolver::thetaAt(), QuantLib::TqrEigenDecomposition::TqrEigenDecomposition(), QuantLib::TransformedGrid::TransformedGrid(), QuantLib::HullWhite::tree(), QuantLib::triangularAnglesParametrization(), QuantLib::triangularAnglesParametrizationRankThreeVectorial(), QuantLib::triangularAnglesParametrizationUnconstrained(), QuantLib::TridiagonalOperator::TridiagonalOperator(), QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::updateAlphaVec(), QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::updateAlphaVec(), anonymous_namespace{cmsmarketcalibration.cpp}::ObjectiveFunction::updateVolatilityCubeAndCmsMarket(), anonymous_namespace{cmsmarketcalibration.cpp}::ObjectiveFunction2::updateVolatilityCubeAndCmsMarket(), anonymous_namespace{optimizers.cpp}::OneDimensionalPolynomialDegreeN::value(), QuantLib::LeastSquareFunction::valueAndGradient(), and anonymous_namespace{optimizers.cpp}::OneDimensionalPolynomialDegreeN::values().
{
        return n_;
    }
void QuantLib::Array::swap (Array & from) [inline]
Definition at line 461 of file array.hpp.
References data_, and n_.
Referenced by Array(), operator=(), QuantLib::SampledCurve::regrid(), QuantLib::SampledCurve::swap(), QuantLib::TridiagonalOperator::swap(), and QuantLib::swap().
{
        using std::swap;
        data_.swap(from.data_);
        swap(n_,from.n_);
    }
Friends And Related Function Documentation
const Disposable< Array > Abs (const Array &) [related]
Definition at line 597 of file array.hpp.
{
        Array result(v.size());
        std::transform(v.begin(),v.end(),result.begin(),
                       std::ptr_fun<Real,Real>(std::fabs));
        return result;
    }
Real DotProduct (const Array & , const Array &) [related]
Definition at line 469 of file array.hpp.
{
        QL_REQUIRE(v1.size() == v2.size(),
                   "arrays with different sizes (" << v1.size() << ", "
                   << v2.size() << ") cannot be multiplied");
        return std::inner_product(v1.begin(),v1.end(),v2.begin(),0.0);
    }
const Disposable< Array > Exp (const Array &) [related]
Definition at line 618 of file array.hpp.
{
        Array result(v.size());
        std::transform(v.begin(),v.end(),result.begin(),
                       std::ptr_fun<Real,Real>(std::exp));
        return result;
    }
const Disposable< Array > Log (const Array &) [related]
Definition at line 611 of file array.hpp.
{
        Array result(v.size());
        std::transform(v.begin(),v.end(),result.begin(),
                       std::ptr_fun<Real,Real>(std::log));
        return result;
    }
const Disposable< Array > operator* (const Array & , const Array &) [related]
Definition at line 545 of file array.hpp.
{
        QL_REQUIRE(v1.size() == v2.size(),
                   "arrays with different sizes (" << v1.size() << ", "
                   << v2.size() << ") cannot be multiplied");
        Array result(v1.size());
        std::transform(v1.begin(),v1.end(),v2.begin(),result.begin(),
                       std::multiplies<Real>());
        return result;
    }
const Disposable< Array > operator* (const Array & , Real) [related]
Definition at line 556 of file array.hpp.
{
        Array result(v1.size());
        std::transform(v1.begin(),v1.end(),result.begin(),
                       std::bind2nd(std::multiplies<Real>(),a));
        return result;
    }
const Disposable< Array > operator* (Real , const Array &) [related]
Definition at line 563 of file array.hpp.
{
        Array result(v2.size());
        std::transform(v2.begin(),v2.end(),result.begin(),
                       std::bind1st(std::multiplies<Real>(),a));
        return result;
    }
const Disposable< Array > operator+ (const Array & v) [related]
Definition at line 480 of file array.hpp.
{
        Array result = v;
        return result;
    }
const Disposable< Array > operator+ (const Array & , const Array &) [related]
Definition at line 495 of file array.hpp.
{
        QL_REQUIRE(v1.size() == v2.size(),
                   "arrays with different sizes (" << v1.size() << ", "
                   << v2.size() << ") cannot be added");
        Array result(v1.size());
        std::transform(v1.begin(),v1.end(),v2.begin(),result.begin(),
                       std::plus<Real>());
        return result;
    }
const Disposable< Array > operator+ (const Array & , Real) [related]
Definition at line 506 of file array.hpp.
{
        Array result(v1.size());
        std::transform(v1.begin(),v1.end(),result.begin(),
                       std::bind2nd(std::plus<Real>(),a));
        return result;
    }
const Disposable< Array > operator+ (Real , const Array &) [related]
Definition at line 513 of file array.hpp.
{
        Array result(v2.size());
        std::transform(v2.begin(),v2.end(),result.begin(),
                       std::bind1st(std::plus<Real>(),a));
        return result;
    }
const Disposable< Array > operator- (const Array & v) [related]
Definition at line 485 of file array.hpp.
{
        Array result(v.size());
        std::transform(v.begin(),v.end(),result.begin(),
                       std::negate<Real>());
        return result;
    }
const Disposable< Array > operator- (const Array & , const Array &) [related]
Definition at line 520 of file array.hpp.
{
        QL_REQUIRE(v1.size() == v2.size(),
                   "arrays with different sizes (" << v1.size() << ", "
                   << v2.size() << ") cannot be subtracted");
        Array result(v1.size());
        std::transform(v1.begin(),v1.end(),v2.begin(),result.begin(),
                       std::minus<Real>());
        return result;
    }
const Disposable< Array > operator- (const Array & , Real) [related]
Definition at line 531 of file array.hpp.
{
        Array result(v1.size());
        std::transform(v1.begin(),v1.end(),result.begin(),
                       std::bind2nd(std::minus<Real>(),a));
        return result;
    }
const Disposable< Array > operator- (Real , const Array &) [related]
Definition at line 538 of file array.hpp.
{
        Array result(v2.size());
        std::transform(v2.begin(),v2.end(),result.begin(),
                       std::bind1st(std::minus<Real>(),a));
        return result;
    }
const Disposable< Array > operator/ (const Array & , const Array &) [related]
Definition at line 570 of file array.hpp.
{
        QL_REQUIRE(v1.size() == v2.size(),
                   "arrays with different sizes (" << v1.size() << ", "
                   << v2.size() << ") cannot be divided");
        Array result(v1.size());
        std::transform(v1.begin(),v1.end(),v2.begin(),result.begin(),
                       std::divides<Real>());
        return result;
    }
const Disposable< Array > operator/ (const Array & , Real) [related]
Definition at line 581 of file array.hpp.
{
        Array result(v1.size());
        std::transform(v1.begin(),v1.end(),result.begin(),
                       std::bind2nd(std::divides<Real>(),a));
        return result;
    }
const Disposable< Array > operator/ (Real , const Array &) [related]
Definition at line 588 of file array.hpp.
{
        Array result(v2.size());
        std::transform(v2.begin(),v2.end(),result.begin(),
                       std::bind1st(std::divides<Real>(),a));
        return result;
    }
std::ostream & operator<< (std::ostream & , const Array &) [related]
Definition at line 629 of file array.hpp.
{
        std::streamsize width = out.width();
        out << "[ ";
        if (!a.empty()) {
            for (Size n=0; n<a.size()-1; ++n)
                out << std::setw(width) << a[n] << "; ";
            out << std::setw(width) << a.back();
        }
        out << " ]";
        return out;
    }
const Disposable< Array > Sqrt (const Array &) [related]
Definition at line 604 of file array.hpp.
{
        Array result(v.size());
        std::transform(v.begin(),v.end(),result.begin(),
                       std::ptr_fun<Real,Real>(std::sqrt));
        return result;
    }
void swap (Array & , Array &) [related]
Definition at line 625 of file array.hpp.
{
        v.swap(w);
    }
Member Data Documentation
boost::scoped_array<Real> QuantLib::Array::data_ [private]
Definition at line 138 of file array.hpp.
Referenced by Array(), at(), back(), begin(), QuantLib::LocalBootstrap< Curve >::calculate(), end(), front(), operator[](), and swap().
Size QuantLib::Array::n_ [private]
Definition at line 139 of file array.hpp.
Referenced by Array(), at(), back(), empty(), end(), front(), operator*=(), operator+=(), operator-=(), operator/=(), operator==(), operator[](), size(), and swap().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/array.hpp