QuantLib: QuantLib::JamshidianSwaptionEngine Class Reference
QuantLib::JamshidianSwaptionEngine Class Reference
Jamshidian swaption engine.
#include <jamshidianswaptionengine.hpp>
Classes
class rStarFinder
Public Member Functions
JamshidianSwaptionEngine (const boost::shared_ptr< OneFactorAffineModel > &model, const Handle< YieldTermStructure > &termStructure=Handle< YieldTermStructure >())
void calculate () const
Private Attributes
Handle< YieldTermStructure > termStructure_
Friends
class rStarFinder
Detailed Description
Jamshidian swaption engine.
Warning:
The engine assumes that the exercise date equals the start date of the passed swap.
Definition at line 39 of file jamshidianswaptionengine.hpp.
Constructor & Destructor Documentation
QuantLib::JamshidianSwaptionEngine::JamshidianSwaptionEngine (const boost::shared_ptr< OneFactorAffineModel > & model, const Handle< YieldTermStructure > & termStructure = Handle<YieldTermStructure>()) [inline]
Note:
the term structure is only needed when the short-rate model cannot provide one itself.
Definition at line 47 of file jamshidianswaptionengine.hpp.
References QuantLib::Observer::registerWith(), and termStructure_.
        : GenericModelEngine<OneFactorAffineModel,
                             Swaption::arguments,
                             Swaption::results>(model),
          termStructure_(termStructure) {
            registerWith(termStructure_);
        }
Member Function Documentation
void QuantLib::JamshidianSwaptionEngine::calculate () const [virtual]
Implements QuantLib::PricingEngine.
Definition at line 53 of file jamshidianswaptionengine.cpp.
References QuantLib::GenericEngine< Swaption::arguments, Swaption::results >::arguments_, QuantLib::Option::Call, anonymous_namespace{marketmodel.cpp}::dayCounter, QuantLib::Exercise::European, QuantLib::Option::arguments::exercise, QuantLib::VanillaSwap::arguments::fixedCoupons, QuantLib::VanillaSwap::arguments::fixedPayDates, QuantLib::VanillaSwap::arguments::nominal, QuantLib::VanillaSwap::Payer, QuantLib::Settlement::Physical, QuantLib::Option::Put, QL_REQUIRE, QuantLib::GenericEngine< Swaption::arguments, Swaption::results >::results_, QuantLib::Solver1D< Impl >::setLowerBound(), QuantLib::Solver1D< Impl >::setMaxEvaluations(), QuantLib::Swaption::arguments::settlementType, QuantLib::Solver1D< Impl >::setUpperBound(), QuantLib::Solver1D< Impl >::solve(), QuantLib::TermStructureConsistentModel::termStructure(), termStructure_, QuantLib::VanillaSwap::arguments::type, QuantLib::Instrument::results::value, and QuantLib::DayCounter::yearFraction().
{
        QL_REQUIRE(arguments_.settlementType==Settlement::Physical,
                   "cash-settled swaptions not priced by Jamshidian engine");
        QL_REQUIRE(arguments_.exercise->type() == Exercise::European,
                   "cannot use the Jamshidian decomposition "
                   "on exotic swaptions");
        Date referenceDate;
        DayCounter dayCounter;
        boost::shared_ptr<TermStructureConsistentModel> tsmodel =
            boost::dynamic_pointer_cast<TermStructureConsistentModel>(*model_);
        if (tsmodel) {
            referenceDate = tsmodel->termStructure()->referenceDate();
            dayCounter = tsmodel->termStructure()->dayCounter();
        } else {
            referenceDate = termStructure_->referenceDate();
            dayCounter = termStructure_->dayCounter();
        }
        std::vector<Real> amounts(arguments_.fixedCoupons);
        amounts.back() += arguments_.nominal;
        Real maturity = dayCounter.yearFraction(referenceDate,
                                                arguments_.exercise->date(0));
        std::vector<Time> fixedPayTimes(arguments_.fixedPayDates.size());
        for (Size i=0; i<fixedPayTimes.size(); i++)
            fixedPayTimes[i] =
                dayCounter.yearFraction(referenceDate,
                                        arguments_.fixedPayDates[i]);
        rStarFinder finder(*model_, arguments_.nominal, maturity,
                           fixedPayTimes, amounts);
        Brent s1d;
        Rate minStrike = -10.0;
        Rate maxStrike = 10.0;
        s1d.setMaxEvaluations(10000);
        s1d.setLowerBound(minStrike);
        s1d.setUpperBound(maxStrike);
        Rate rStar = s1d.solve(finder, 1e-8, 0.05, minStrike, maxStrike);
        Option::Type w = arguments_.type==VanillaSwap::Payer ?
                                                Option::Put : Option::Call;
        Size size = arguments_.fixedCoupons.size();
        Real value = 0.0;
        for (Size i=0; i<size; i++) {
            Real fixedPayTime =
                dayCounter.yearFraction(referenceDate,
                                        arguments_.fixedPayDates[i]);
            Real strike = model_->discountBond(maturity,
                                               fixedPayTime,
                                               rStar);
            Real dboValue = model_->discountBondOption(
                                               w, strike, maturity,
                                               fixedPayTime);
            value += amounts[i]*dboValue;
        }
        results_.value = value;
    }
Friends And Related Function Documentation
friend class rStarFinder [friend]
Definition at line 60 of file jamshidianswaptionengine.hpp.
Member Data Documentation
Handle<YieldTermStructure> QuantLib::JamshidianSwaptionEngine::termStructure_ [private]
Definition at line 59 of file jamshidianswaptionengine.hpp.
Referenced by calculate(), and JamshidianSwaptionEngine().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/swaption/jamshidianswaptionengine.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/swaption/jamshidianswaptionengine.cpp