QuantLib: QuantLib::CommoditySettings Class Reference
QuantLib::CommoditySettings Class Reference
global repository for run-time library settings
#include <commoditysettings.hpp>
Public Member Functions
Currency & currency ()
UnitOfMeasure & unitOfMeasure ()
Private Member Functions
CommoditySettings ()
Private Attributes
Currency currency_
UnitOfMeasure unitOfMeasure_
Friends
class Singleton< CommoditySettings >
Detailed Description
global repository for run-time library settings
Definition at line 34 of file commoditysettings.hpp.
Constructor & Destructor Documentation
QuantLib::CommoditySettings::CommoditySettings () [private]
Definition at line 27 of file commoditysettings.cpp.
    : currency_(USDCurrency()), unitOfMeasure_(BarrelUnitOfMeasure()) {}
Member Function Documentation
Currency & QuantLib::CommoditySettings::currency ()
Definition at line 30 of file commoditysettings.cpp.
References currency_.
Referenced by QuantLib::EnergyCommodity::calculateSecondaryCostAmounts(), QuantLib::EnergyCommodity::calculateUnitCost(), QuantLib::EnergyFuture::performCalculations(), QuantLib::EnergyBasisSwap::performCalculations(), and QuantLib::EnergyVanillaSwap::performCalculations().
{
        return currency_;
    }
UnitOfMeasure & QuantLib::CommoditySettings::unitOfMeasure ()
Definition at line 34 of file commoditysettings.cpp.
References unitOfMeasure_.
Referenced by QuantLib::EnergyCommodity::calculateUnitCost(), QuantLib::EnergyFuture::performCalculations(), QuantLib::EnergyBasisSwap::performCalculations(), and QuantLib::EnergyVanillaSwap::performCalculations().
{
        return unitOfMeasure_;
    }
Friends And Related Function Documentation
friend class Singleton< CommoditySettings > [friend]
Definition at line 35 of file commoditysettings.hpp.
Member Data Documentation
Currency QuantLib::CommoditySettings::currency_ [private]
Definition at line 43 of file commoditysettings.hpp.
Referenced by currency().
UnitOfMeasure QuantLib::CommoditySettings::unitOfMeasure_ [private]
Definition at line 44 of file commoditysettings.hpp.
Referenced by unitOfMeasure().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/commodities/commoditysettings.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/commodities/commoditysettings.cpp