QuantLib: QuantLib::MakeMCBarrierEngine< RNG, S > Class Template Reference
QuantLib::MakeMCBarrierEngine< RNG, S > Class Template Reference
Monte Carlo barrier-option engine factory.
#include <mcbarrierengine.hpp>
Public Member Functions
MakeMCBarrierEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > &)
MakeMCBarrierEngine & withSteps (Size steps)
MakeMCBarrierEngine & withStepsPerYear (Size steps)
MakeMCBarrierEngine & withBrownianBridge (bool b=true)
MakeMCBarrierEngine & withAntitheticVariate (bool b=true)
MakeMCBarrierEngine & withSamples (Size samples)
MakeMCBarrierEngine & withAbsoluteTolerance (Real tolerance)
MakeMCBarrierEngine & withMaxSamples (Size samples)
MakeMCBarrierEngine & withBias (bool b=true)
MakeMCBarrierEngine & withSeed (BigNatural seed)
operator boost::shared_ptr< PricingEngine > () const
Private Attributes
boost::shared_ptr
< GeneralizedBlackScholesProcess > process_
bool brownianBridge_
bool antithetic_
bool biased_
Size steps_
Size stepsPerYear_
Size samples_
Size maxSamples_
Real tolerance_
BigNatural seed_
Detailed Description
template<class RNG = PseudoRandom, class S = Statistics>
class QuantLib::MakeMCBarrierEngine< RNG, S >
Monte Carlo barrier-option engine factory.
Definition at line 115 of file mcbarrierengine.hpp.
Constructor & Destructor Documentation
template<class RNG , class S > QuantLib::MakeMCBarrierEngine< RNG, S >::MakeMCBarrierEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > & process) [inline]
Definition at line 276 of file mcbarrierengine.hpp.
    : process_(process), brownianBridge_(false), antithetic_(false),
      biased_(false), steps_(Null<Size>()), stepsPerYear_(Null<Size>()),
      samples_(Null<Size>()), maxSamples_(Null<Size>()),
      tolerance_(Null<Real>()), seed_(0) {}
Member Function Documentation
template<class RNG , class S > QuantLib::MakeMCBarrierEngine< RNG, S >::operator boost::shared_ptr< PricingEngine > () const [inline]
Definition at line 355 of file mcbarrierengine.hpp.
References QL_REQUIRE, and anonymous_namespace{marketmodel.cpp}::seed_.
{
        QL_REQUIRE(steps_ != Null<Size>() || stepsPerYear_ != Null<Size>(),
                   "number of steps not given");
        QL_REQUIRE(steps_ == Null<Size>() || stepsPerYear_ == Null<Size>(),
                   "number of steps overspecified");
        return boost::shared_ptr<PricingEngine>(new
            MCBarrierEngine<RNG,S>(process_,
                                   steps_,
                                   stepsPerYear_,
                                   brownianBridge_,
                                   antithetic_,
                                   samples_, tolerance_,
                                   maxSamples_,
                                   biased_,
                                   seed_));
    }
template<class RNG , class S > MakeMCBarrierEngine< RNG, S > & QuantLib::MakeMCBarrierEngine< RNG, S >::withAbsoluteTolerance (Real tolerance) [inline]
Definition at line 322 of file mcbarrierengine.hpp.
References QL_REQUIRE, and anonymous_namespace{gaussianquadratures.cpp}::tolerance.
{
        QL_REQUIRE(samples_ == Null<Size>(),
                   "number of samples already set");
        QL_REQUIRE(RNG::allowsErrorEstimate,
                   "chosen random generator policy "
                   "does not allow an error estimate");
        tolerance_ = tolerance;
        return *this;
    }
template<class RNG , class S > MakeMCBarrierEngine< RNG, S > & QuantLib::MakeMCBarrierEngine< RNG, S >::withAntitheticVariate (bool b = true) [inline]
Definition at line 306 of file mcbarrierengine.hpp.
References anonymous_namespace{marketmodel.cpp}::b.
{
        antithetic_ = b;
        return *this;
    }
template<class RNG , class S > MakeMCBarrierEngine< RNG, S > & QuantLib::MakeMCBarrierEngine< RNG, S >::withBias (bool b = true) [inline]
Definition at line 341 of file mcbarrierengine.hpp.
{
        biased_ = biased;
        return *this;
    }
template<class RNG , class S > MakeMCBarrierEngine< RNG, S > & QuantLib::MakeMCBarrierEngine< RNG, S >::withBrownianBridge (bool b = true) [inline]
Definition at line 299 of file mcbarrierengine.hpp.
Referenced by BarrierOptionTest::testBabsiriValues(), and BarrierOptionTest::testBeagleholeValues().
{
        brownianBridge_ = brownianBridge;
        return *this;
    }
template<class RNG , class S > MakeMCBarrierEngine< RNG, S > & QuantLib::MakeMCBarrierEngine< RNG, S >::withMaxSamples (Size samples) [inline]
Definition at line 334 of file mcbarrierengine.hpp.
Referenced by BarrierOptionTest::testBabsiriValues(), and BarrierOptionTest::testBeagleholeValues().
{
        maxSamples_ = samples;
        return *this;
    }
template<class RNG , class S > MakeMCBarrierEngine< RNG, S > & QuantLib::MakeMCBarrierEngine< RNG, S >::withSamples (Size samples) [inline]
Definition at line 313 of file mcbarrierengine.hpp.
References QL_REQUIRE.
Referenced by BarrierOptionTest::testBabsiriValues(), and BarrierOptionTest::testBeagleholeValues().
{
        QL_REQUIRE(tolerance_ == Null<Real>(),
                   "tolerance already set");
        samples_ = samples;
        return *this;
    }
template<class RNG , class S > MakeMCBarrierEngine< RNG, S > & QuantLib::MakeMCBarrierEngine< RNG, S >::withSeed (BigNatural seed) [inline]
Definition at line 348 of file mcbarrierengine.hpp.
References anonymous_namespace{marketmodel.cpp}::seed_.
Referenced by BarrierOptionTest::testBabsiriValues(), and BarrierOptionTest::testBeagleholeValues().
{
        seed_ = seed;
        return *this;
    }
template<class RNG , class S > MakeMCBarrierEngine< RNG, S > & QuantLib::MakeMCBarrierEngine< RNG, S >::withSteps (Size steps) [inline]
Definition at line 285 of file mcbarrierengine.hpp.
{
        steps_ = steps;
        return *this;
    }
template<class RNG , class S > MakeMCBarrierEngine< RNG, S > & QuantLib::MakeMCBarrierEngine< RNG, S >::withStepsPerYear (Size steps) [inline]
Definition at line 292 of file mcbarrierengine.hpp.
{
        stepsPerYear_ = steps;
        return *this;
    }
Member Data Documentation
template<class RNG = PseudoRandom, class S = Statistics> bool QuantLib::MakeMCBarrierEngine< RNG, S >::antithetic_ [private]
Definition at line 133 of file mcbarrierengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> bool QuantLib::MakeMCBarrierEngine< RNG, S >::biased_ [private]
Definition at line 133 of file mcbarrierengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> bool QuantLib::MakeMCBarrierEngine< RNG, S >::brownianBridge_ [private]
Definition at line 133 of file mcbarrierengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> Size QuantLib::MakeMCBarrierEngine< RNG, S >::maxSamples_ [private]
Definition at line 134 of file mcbarrierengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> boost::shared_ptr<GeneralizedBlackScholesProcess> QuantLib::MakeMCBarrierEngine< RNG, S >::process_ [private]
Definition at line 132 of file mcbarrierengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> Size QuantLib::MakeMCBarrierEngine< RNG, S >::samples_ [private]
Definition at line 134 of file mcbarrierengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> BigNatural QuantLib::MakeMCBarrierEngine< RNG, S >::seed_ [private]
Definition at line 136 of file mcbarrierengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> Size QuantLib::MakeMCBarrierEngine< RNG, S >::steps_ [private]
Definition at line 134 of file mcbarrierengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> Size QuantLib::MakeMCBarrierEngine< RNG, S >::stepsPerYear_ [private]
Definition at line 134 of file mcbarrierengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> Real QuantLib::MakeMCBarrierEngine< RNG, S >::tolerance_ [private]
Definition at line 135 of file mcbarrierengine.hpp.
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/barrier/mcbarrierengine.hpp