QuantLib: QuantLib::YearOnYearInflationSwapHelper Class Reference
QuantLib::YearOnYearInflationSwapHelper Class Reference
Year-on-year inflation-swap bootstrap helper.
#include <inflationhelpers.hpp>
Public Member Functions
YearOnYearInflationSwapHelper (const Handle< Quote > &quote, const Period &swapObsLag_, const Date &maturity, const Calendar &calendar, BusinessDayConvention paymentConvention, const DayCounter &dayCounter, const boost::shared_ptr< YoYInflationIndex > &yii)
void setTermStructure (YoYInflationTermStructure *)
sets the term structure to be used for pricing
Real impliedQuote () const
Protected Attributes
Period swapObsLag_
Date maturity_
Calendar calendar_
BusinessDayConvention paymentConvention_
DayCounter dayCounter_
boost::shared_ptr
< YoYInflationIndex > yii_
boost::shared_ptr
< YearOnYearInflationSwap > yyiis_
Detailed Description
Year-on-year inflation-swap bootstrap helper.
Definition at line 62 of file inflationhelpers.hpp.
Constructor & Destructor Documentation
QuantLib::YearOnYearInflationSwapHelper::YearOnYearInflationSwapHelper (const Handle< Quote > & quote, const Period & swapObsLag_, const Date & maturity, const Calendar & calendar, BusinessDayConvention paymentConvention, const DayCounter & dayCounter, const boost::shared_ptr< YoYInflationIndex > & yii)
Definition at line 117 of file inflationhelpers.cpp.
References QuantLib::BootstrapHelper< YoYInflationTermStructure >::earliestDate_, QuantLib::inflationPeriod(), QuantLib::Singleton< Settings >::instance(), QuantLib::BootstrapHelper< YoYInflationTermStructure >::latestDate_, maturity_, QL_REQUIRE, QuantLib::Observer::registerWith(), swapObsLag_, and yii_.
    : BootstrapHelper<YoYInflationTermStructure>(quote),
    swapObsLag_(swapObsLag), maturity_(maturity),
    calendar_(calendar), paymentConvention_(paymentConvention),
    dayCounter_(dayCounter), yii_(yii) {
        if (yii_->interpolated()) {
            // if interpolated then simple
            earliestDate_ = maturity_ - swapObsLag_;
            latestDate_ = maturity_ - swapObsLag_;
        } else {
            // but if NOT interpolated then the value is valid
            // for every day in an inflation period so you actually
            // get an extended validity, however for curve building
            // just put the first date because using that convention
            // for the base date throughout
            std::pair<Date,Date> limStart = inflationPeriod(maturity_ - swapObsLag_,
                                                            yii_->frequency());
            earliestDate_ = limStart.first;
            latestDate_ = limStart.first;
        }
        // check that the observation lag of the swap
        // is compatible with the availability lag of the index AND
        // it's interpolation (assuming the start day is spot)
        if (yii_->interpolated()) {
            Period pShift(yii_->frequency());
            QL_REQUIRE(swapObsLag_ - pShift > yii_->availabilityLag(),
                       "inconsistency between swap observation of index "
                       << swapObsLag_ <<
                       " index availability " << yii_->availabilityLag() <<
                       " index period " << pShift <<
                       " and index availability " << yii_->availabilityLag() <<
                       " need (obsLag-index period) > availLag");
        }
        registerWith(Settings::instance().evaluationDate());
    }
Member Function Documentation
Real QuantLib::YearOnYearInflationSwapHelper::impliedQuote () const [virtual]
Implements QuantLib::BootstrapHelper< YoYInflationTermStructure >.
Definition at line 164 of file inflationhelpers.cpp.
References yyiis_.
{
        // what does the term structure imply?
        // in this case just the same value ... trivial case
        // (would not be so for an inflation-linked bond)
        yyiis_->recalculate();
        return yyiis_->fairRate();
    }
void QuantLib::YearOnYearInflationSwapHelper::setTermStructure (YoYInflationTermStructure *) [virtual]
sets the term structure to be used for pricing
Warning:
Being a pointer and not a shared_ptr, the term structure is not guaranteed to remain allocated for the whole life of the rate helper. It is responsibility of the programmer to ensure that the pointer remains valid. It is advised that this method is called only inside the term structure being bootstrapped, setting the pointer to this, i.e., the term structure itself.
Reimplemented from QuantLib::BootstrapHelper< YoYInflationTermStructure >.
Definition at line 172 of file inflationhelpers.cpp.
References QuantLib::MakeSchedule::backwards(), calendar_, dayCounter_, QuantLib::Settings::evaluationDate(), QuantLib::MakeSchedule::from(), QuantLib::Singleton< Settings >::instance(), maturity_, QuantLib::anonymous_namespace{riskyassetswap.cpp}::no_deletion(), QuantLib::InflationTermStructure::nominalTermStructure(), QuantLib::YearOnYearInflationSwap::Payer, paymentConvention_, QuantLib::BootstrapHelper< YoYInflationTermStructure >::quote(), swapObsLag_, QuantLib::MakeSchedule::to(), QuantLib::Unadjusted, QuantLib::MakeSchedule::withCalendar(), QuantLib::MakeSchedule::withConvention(), QuantLib::MakeSchedule::withTenor(), QuantLib::Years, yii_, and yyiis_.
{
        BootstrapHelper<YoYInflationTermStructure>::setTermStructure(y);
        // set up a new YYIIS
        // but this one does NOT own its inflation term structure
        const bool own = false;
        // The effect of the new inflation term structure is
        // felt via the effect on the inflation index
        Handle<YoYInflationTermStructure> yyts(
            boost::shared_ptr<YoYInflationTermStructure>(y,no_deletion), own);
        boost::shared_ptr<YoYInflationIndex> new_yii = yii_->clone(yyts);
        // always works because tenor is always 1 year so
        // no problem with different days-in-month
        Date from = Settings::instance().evaluationDate();
        Date to = maturity_;
        Schedule fixedSchedule = MakeSchedule().from(from).to(to)
                                    .withTenor(1*Years)
                                    .withConvention(Unadjusted)
                                    .withCalendar(calendar_)// fixed leg gets cal from sched
                                    .backwards();
        Schedule yoySchedule = fixedSchedule;
        Spread spread = 0.0;
        Rate fixedRate = quote()->value();
        Real nominal = 1000000.0;   // has to be something but doesn't matter what
        yyiis_.reset(new YearOnYearInflationSwap(YearOnYearInflationSwap::Payer,
                                                    nominal,
                                                    fixedSchedule,
                                                    fixedRate,
                                                    dayCounter_,
                                                    yoySchedule,
                                                    new_yii,
                                                    swapObsLag_,
                                                    spread,
                                                    dayCounter_,
                                                    calendar_,  // inflation index does not have a calendar
                                                    paymentConvention_));
        // Because very simple instrument only takes
        // standard discounting swap engine.
        yyiis_->setPricingEngine(boost::shared_ptr<PricingEngine>(
                    new DiscountingSwapEngine(y->nominalTermStructure())));
    }
Member Data Documentation
Calendar QuantLib::YearOnYearInflationSwapHelper::calendar_ [protected]
Definition at line 78 of file inflationhelpers.hpp.
Referenced by setTermStructure().
DayCounter QuantLib::YearOnYearInflationSwapHelper::dayCounter_ [protected]
Definition at line 80 of file inflationhelpers.hpp.
Referenced by setTermStructure().
Date QuantLib::YearOnYearInflationSwapHelper::maturity_ [protected]
Definition at line 77 of file inflationhelpers.hpp.
Referenced by setTermStructure(), and YearOnYearInflationSwapHelper().
BusinessDayConvention QuantLib::YearOnYearInflationSwapHelper::paymentConvention_ [protected]
Definition at line 79 of file inflationhelpers.hpp.
Referenced by setTermStructure().
Period QuantLib::YearOnYearInflationSwapHelper::swapObsLag_ [protected]
Definition at line 76 of file inflationhelpers.hpp.
Referenced by setTermStructure(), and YearOnYearInflationSwapHelper().
boost::shared_ptr<YoYInflationIndex> QuantLib::YearOnYearInflationSwapHelper::yii_ [protected]
Definition at line 81 of file inflationhelpers.hpp.
Referenced by setTermStructure(), and YearOnYearInflationSwapHelper().
boost::shared_ptr<YearOnYearInflationSwap> QuantLib::YearOnYearInflationSwapHelper::yyiis_ [protected]
Definition at line 82 of file inflationhelpers.hpp.
Referenced by impliedQuote(), and setTermStructure().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/inflation/inflationhelpers.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/inflation/inflationhelpers.cpp