QuantLib: QuantLib::ExtendedJoshi4 Class Reference
QuantLib::ExtendedJoshi4 Class Reference
#include <extendedbinomialtree.hpp>
Public Member Functions
ExtendedJoshi4 (const boost::shared_ptr< StochasticProcess1D > &, Time end, Size steps, Real strike)
Real underlying (Size i, Size index) const
Real probability (Size, Size, Size branch) const
Protected Member Functions
Real computeUpProb (Real k, Real dj) const
Protected Attributes
Time end_
Size oddSteps_
Real strike_
Real up_
Real down_
Real pu_
Real pd_
Detailed Description
Definition at line 229 of file extendedbinomialtree.hpp.
Constructor & Destructor Documentation
QuantLib::ExtendedJoshi4::ExtendedJoshi4 (const boost::shared_ptr< StochasticProcess1D > & process, Time end, Size steps, Real strike)
Definition at line 238 of file extendedbinomialtree.cpp.
References computeUpProb(), down_, QuantLib::ExtendedBinomialTree< ExtendedJoshi4 >::driftStep(), oddSteps_, pd_, pu_, QL_REQUIRE, up_, and QuantLib::ExtendedBinomialTree< ExtendedJoshi4 >::x0_.
    : ExtendedBinomialTree<ExtendedJoshi4>(process, end,
                                           (steps%2 ? steps : steps+1)),
      end_(end), oddSteps_(steps%2 ? steps : steps+1), strike_(strike) {
        QL_REQUIRE(strike>0.0, "strike " << strike << "must be positive");
        Real variance = process->variance(0.0, x0_, end);
        Real ermqdt = std::exp(this->driftStep(0.0) + 0.5*variance/oddSteps_);
        Real d2 = (std::log(x0_/strike) + this->driftStep(0.0)*oddSteps_ ) /
            std::sqrt(variance);
        pu_ = computeUpProb((oddSteps_-1.0)/2.0,d2 );
        pd_ = 1.0 - pu_;
        Real pdash = computeUpProb((oddSteps_-1.0)/2.0,d2+std::sqrt(variance));
        up_ = ermqdt * pdash / pu_;
        down_ = (ermqdt - pu_ * up_) / (1.0 - pu_);
    }
Member Function Documentation
Real QuantLib::ExtendedJoshi4::computeUpProb (Real k, Real dj) const [protected]
Definition at line 217 of file extendedbinomialtree.cpp.
References anonymous_namespace{marketmodel.cpp}::beta.
Referenced by ExtendedJoshi4(), probability(), and underlying().
{
        Real alpha = dj/(std::sqrt(8.0));
        Real alpha2 = alpha*alpha;
        Real alpha3 = alpha*alpha2;
        Real alpha5 = alpha3*alpha2;
        Real alpha7 = alpha5*alpha2;
        Real beta = -0.375*alpha-alpha3;
        Real gamma = (5.0/6.0)*alpha5 + (13.0/12.0)*alpha3
            +(25.0/128.0)*alpha;
        Real delta = -0.1025 *alpha- 0.9285 *alpha3
            -1.43 *alpha5 -0.5 *alpha7;
        Real p =0.5;
        Real rootk= std::sqrt(k);
        p+= alpha/rootk;
        p+= beta /(k*rootk);
        p+= gamma/(k*k*rootk);
        // delete next line to get results for j three tree
        p+= delta/(k*k*k*rootk);
        return p;
    }
Real QuantLib::ExtendedJoshi4::probability (Size i, Size , Size branch) const
Definition at line 275 of file extendedbinomialtree.cpp.
References computeUpProb(), QuantLib::ExtendedBinomialTree< ExtendedJoshi4 >::driftStep(), QuantLib::ExtendedBinomialTree< ExtendedJoshi4 >::dt_, end_, oddSteps_, strike_, QuantLib::ExtendedBinomialTree< ExtendedJoshi4 >::treeProcess_, and QuantLib::ExtendedBinomialTree< ExtendedJoshi4 >::x0_.
{
        Time stepTime = i*this->dt_;
        Real variance = this->treeProcess_->variance(stepTime, x0_, end_);
        Real d2 = (std::log(x0_/strike_) + this->driftStep(stepTime)*oddSteps_ ) /
            std::sqrt(variance);
        Real pu = computeUpProb((oddSteps_-1.0)/2.0,d2 );
        Real pd = 1.0 - pu;
        return (branch == 1 ? pu : pd);
    }
Real QuantLib::ExtendedJoshi4::underlying (Size i, Size index) const
Definition at line 259 of file extendedbinomialtree.cpp.
References computeUpProb(), QuantLib::ExtendedBinomialTree< ExtendedJoshi4 >::driftStep(), QuantLib::ExtendedBinomialTree< ExtendedJoshi4 >::dt_, end_, oddSteps_, QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow(), strike_, QuantLib::ExtendedBinomialTree< ExtendedJoshi4 >::treeProcess_, and QuantLib::ExtendedBinomialTree< ExtendedJoshi4 >::x0_.
{
        Time stepTime = i*this->dt_;
        Real variance = this->treeProcess_->variance(stepTime, x0_, end_);
        Real ermqdt = std::exp(this->driftStep(stepTime) + 0.5*variance/oddSteps_);
        Real d2 = (std::log(x0_/strike_) + this->driftStep(stepTime)*oddSteps_ ) /
            std::sqrt(variance);
        Real pu = computeUpProb((oddSteps_-1.0)/2.0,d2 );
        Real pdash = computeUpProb((oddSteps_-1.0)/2.0,d2+std::sqrt(variance));
        Real up = ermqdt * pdash / pu;
        Real down = (ermqdt - pu * up) / (1.0 - pu);
        return x0_ * std::pow(down, Real(BigInteger(i)-BigInteger(index)))
            * std::pow(up, Real(index));
    }
Member Data Documentation
Real QuantLib::ExtendedJoshi4::down_ [protected]
Definition at line 242 of file extendedbinomialtree.hpp.
Referenced by ExtendedJoshi4().
Time QuantLib::ExtendedJoshi4::end_ [protected]
Definition at line 240 of file extendedbinomialtree.hpp.
Referenced by probability(), and underlying().
Size QuantLib::ExtendedJoshi4::oddSteps_ [protected]
Definition at line 241 of file extendedbinomialtree.hpp.
Referenced by ExtendedJoshi4(), probability(), and underlying().
Real QuantLib::ExtendedJoshi4::pd_ [protected]
Definition at line 242 of file extendedbinomialtree.hpp.
Referenced by ExtendedJoshi4().
Real QuantLib::ExtendedJoshi4::pu_ [protected]
Definition at line 242 of file extendedbinomialtree.hpp.
Referenced by ExtendedJoshi4().
Real QuantLib::ExtendedJoshi4::strike_ [protected]
Definition at line 242 of file extendedbinomialtree.hpp.
Referenced by probability(), and underlying().
Real QuantLib::ExtendedJoshi4::up_ [protected]
Definition at line 242 of file extendedbinomialtree.hpp.
Referenced by ExtendedJoshi4().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/lattices/extendedbinomialtree.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/lattices/extendedbinomialtree.cpp