QuantLib: QuantLib::Fdm2dBlackScholesSolver Class Reference
QuantLib::Fdm2dBlackScholesSolver Class Reference
#include <fdm2dblackscholessolver.hpp>
Public Member Functions
Fdm2dBlackScholesSolver (const Handle< GeneralizedBlackScholesProcess > &p1, const Handle< GeneralizedBlackScholesProcess > &p2, const Real correlation, const FdmSolverDesc &solverDesc, const FdmSchemeDesc &schemeDesc=FdmSchemeDesc::Hundsdorfer())
Real valueAt (Real x, Real y) const
Real thetaAt (Real x, Real y) const
Real deltaXat (Real x, Real y) const
Real deltaYat (Real x, Real y) const
Real gammaXat (Real x, Real y) const
Real gammaYat (Real x, Real y) const
Protected Member Functions
void performCalculations () const
Private Attributes
const Handle
< GeneralizedBlackScholesProcess > p1_
const Handle
< GeneralizedBlackScholesProcess > p2_
const Real correlation_
const FdmSolverDesc solverDesc_
const FdmSchemeDesc schemeDesc_
boost::shared_ptr< Fdm2DimSolver > solver_
Detailed Description
Definition at line 36 of file fdm2dblackscholessolver.hpp.
Constructor & Destructor Documentation
QuantLib::Fdm2dBlackScholesSolver::Fdm2dBlackScholesSolver (const Handle< GeneralizedBlackScholesProcess > & p1, const Handle< GeneralizedBlackScholesProcess > & p2, const Real correlation, const FdmSolverDesc & solverDesc, const FdmSchemeDesc & schemeDesc = FdmSchemeDesc::Hundsdorfer())
Definition at line 28 of file fdm2dblackscholessolver.cpp.
References p1_, p2_, and QuantLib::Observer::registerWith().
    : p1_(p1),
      p2_(p2),
      correlation_(correlation),
      solverDesc_(solverDesc),
      schemeDesc_(schemeDesc) {
        registerWith(p1_);
        registerWith(p2_);
    }
Member Function Documentation
Real QuantLib::Fdm2dBlackScholesSolver::deltaXat (Real x, Real y) const
Definition at line 73 of file fdm2dblackscholessolver.cpp.
References QuantLib::LazyObject::calculate(), and solver_.
{
        calculate();
        const Real x = std::log(u);
        const Real y = std::log(v);
        return solver_->derivativeX(x, y)/u;
    }
Real QuantLib::Fdm2dBlackScholesSolver::deltaYat (Real x, Real y) const
Definition at line 82 of file fdm2dblackscholessolver.cpp.
References QuantLib::LazyObject::calculate(), solver_, and anonymous_namespace{perturbativebarrieroptionengine.cpp}::v().
{
        calculate();
        const Real x = std::log(u);
        const Real y = std::log(v);
        return solver_->derivativeY(x, y)/v;
    }
Real QuantLib::Fdm2dBlackScholesSolver::gammaXat (Real x, Real y) const
Definition at line 91 of file fdm2dblackscholessolver.cpp.
References QuantLib::LazyObject::calculate(), and solver_.
{
        calculate();
        const Real x = std::log(u);
        const Real y = std::log(v);
        return (solver_->derivativeXX(x, y)
                -solver_->derivativeX(x, y))/(u*u);
    }
Real QuantLib::Fdm2dBlackScholesSolver::gammaYat (Real x, Real y) const
Definition at line 101 of file fdm2dblackscholessolver.cpp.
References QuantLib::LazyObject::calculate(), and solver_.
{
        calculate();
        const Real x = std::log(u);
        const Real y = std::log(v);
        return (solver_->derivativeYY(x, y)
                -solver_->derivativeY(x, y))/(v*v);
    }
void QuantLib::Fdm2dBlackScholesSolver::performCalculations () const [protected, virtual]
This method must implement any calculations which must be (re)done in order to calculate the desired results.
Implements QuantLib::LazyObject.
Definition at line 44 of file fdm2dblackscholessolver.cpp.
References correlation_, QuantLib::Handle< T >::currentLink(), QuantLib::FdmSolverDesc::maturity, QuantLib::FdmSolverDesc::mesher, p1_, p2_, schemeDesc_, solver_, and solverDesc_.
{
        boost::shared_ptr<Fdm2dBlackScholesOp> op(
                new Fdm2dBlackScholesOp(solverDesc_.mesher,
                                        p1_.currentLink(),
                                        p2_.currentLink(),
                                        correlation_,
                                        solverDesc_.maturity));
        solver_ = boost::shared_ptr<Fdm2DimSolver>(
                            new Fdm2DimSolver(solverDesc_, schemeDesc_, op));
    }
Real QuantLib::Fdm2dBlackScholesSolver::thetaAt (Real x, Real y) const
Definition at line 65 of file fdm2dblackscholessolver.cpp.
References QuantLib::LazyObject::calculate(), and solver_.
{
        calculate();
        const Real x = std::log(u);
        const Real y = std::log(v);
        return solver_->thetaAt(x, y);
    }
Real QuantLib::Fdm2dBlackScholesSolver::valueAt (Real x, Real y) const
Definition at line 57 of file fdm2dblackscholessolver.cpp.
References QuantLib::LazyObject::calculate(), and solver_.
{
        calculate();
        const Real x = std::log(u);
        const Real y = std::log(v);
        return solver_->interpolateAt(x, y);
    }
Member Data Documentation
const Real QuantLib::Fdm2dBlackScholesSolver::correlation_ [private]
Definition at line 59 of file fdm2dblackscholessolver.hpp.
Referenced by performCalculations().
const Handle<GeneralizedBlackScholesProcess> QuantLib::Fdm2dBlackScholesSolver::p1_ [private]
Definition at line 57 of file fdm2dblackscholessolver.hpp.
Referenced by Fdm2dBlackScholesSolver(), and performCalculations().
const Handle<GeneralizedBlackScholesProcess> QuantLib::Fdm2dBlackScholesSolver::p2_ [private]
Definition at line 58 of file fdm2dblackscholessolver.hpp.
Referenced by Fdm2dBlackScholesSolver(), and performCalculations().
const FdmSchemeDesc QuantLib::Fdm2dBlackScholesSolver::schemeDesc_ [private]
Definition at line 61 of file fdm2dblackscholessolver.hpp.
Referenced by performCalculations().
boost::shared_ptr<Fdm2DimSolver> QuantLib::Fdm2dBlackScholesSolver::solver_ [mutable, private]
Definition at line 63 of file fdm2dblackscholessolver.hpp.
Referenced by deltaXat(), deltaYat(), gammaXat(), gammaYat(), performCalculations(), thetaAt(), and valueAt().
const FdmSolverDesc QuantLib::Fdm2dBlackScholesSolver::solverDesc_ [private]
Definition at line 60 of file fdm2dblackscholessolver.hpp.
Referenced by performCalculations().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/solvers/fdm2dblackscholessolver.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/solvers/fdm2dblackscholessolver.cpp