QuantLib: QuantLib::CommodityIndex Class Reference
QuantLib::CommodityIndex Class Reference
base class for commodity indexes
#include <commodityindex.hpp>
Public Member Functions
CommodityIndex (const std::string &name, const CommodityType &commodityType, const Currency &currency, const UnitOfMeasure &unitOfMeasure, const Calendar &calendar, Real lotQuantity, const boost::shared_ptr< CommodityCurve > &forwardCurve, const boost::shared_ptr< ExchangeContracts > &exchangeContracts, int nearbyOffset)
void addQuote (const Date &quoteDate, Real quote)
void addQuotes (const std::map< Date, Real > &quotes)
void clearQuotes ()
bool isValidQuoteDate (const Date &quoteDate) const
returns TRUE if the quote date is valid
bool empty () const
bool forwardCurveEmpty () const
const TimeSeries< Real > & quotes () const
Index interface
std::string name () const
Observer interface
void update ()
Inspectors
const CommodityType & commodityType () const
const Currency & currency () const
const UnitOfMeasure & unitOfMeasure () const
const Calendar & calendar () const
const boost::shared_ptr
< CommodityCurve > & forwardCurve () const
Real lotQuantity () const
Real price (const Date &date)
Real forwardPrice (const Date &date) const
Date lastQuoteDate () const
Protected Attributes
std::string name_
CommodityType commodityType_
UnitOfMeasure unitOfMeasure_
Currency currency_
Calendar calendar_
Real lotQuantity_
TimeSeries< Real > quotes_
boost::shared_ptr< CommodityCurve > forwardCurve_
Real forwardCurveUomConversionFactor_
boost::shared_ptr
< ExchangeContracts > exchangeContracts_
Integer nearbyOffset_
Friends
std::ostream & operator<< (std::ostream &, const CommodityIndex &)
Detailed Description
base class for commodity indexes
Definition at line 35 of file commodityindex.hpp.
Constructor & Destructor Documentation
QuantLib::CommodityIndex::CommodityIndex (const std::string & name, const CommodityType & commodityType, const Currency & currency, const UnitOfMeasure & unitOfMeasure, const Calendar & calendar, Real lotQuantity, const boost::shared_ptr< CommodityCurve > & forwardCurve, const boost::shared_ptr< ExchangeContracts > & exchangeContracts, int nearbyOffset)
Definition at line 25 of file commodityindex.cpp.
References QuantLib::CommodityPricingHelper::calculateUomConversionFactor(), commodityType_, forwardCurve_, forwardCurveUomConversionFactor_, QuantLib::IndexManager::getHistory(), QuantLib::Singleton< IndexManager >::instance(), QuantLib::Singleton< Settings >::instance(), name(), quotes_, QuantLib::Observer::registerWith(), QuantLib::IndexManager::setHistory(), and unitOfMeasure_.
    : name_(indexName), commodityType_(commodityType),
      unitOfMeasure_(unitOfMeasure), currency_(currency), calendar_(calendar),
      lotQuantity_(lotQuantity), forwardCurve_(forwardCurve),
      forwardCurveUomConversionFactor_(1),
      exchangeContracts_(exchangeContracts), nearbyOffset_(nearbyOffset) {
        quotes_ = IndexManager::instance().getHistory(indexName);
        IndexManager::instance().setHistory(indexName, quotes_);
        registerWith(Settings::instance().evaluationDate());
        registerWith(IndexManager::instance().notifier(name()));
        if (forwardCurve_ != 0)
            // registerWith(forwardCurve_);
            forwardCurveUomConversionFactor_ =
                CommodityPricingHelper::calculateUomConversionFactor(
                                                commodityType_,
                                                forwardCurve_->unitOfMeasure_,
                                                unitOfMeasure_);
    }
Member Function Documentation
void QuantLib::CommodityIndex::addQuote (const Date & quoteDate, Real quote) [inline]
Definition at line 185 of file commodityindex.hpp.
References QuantLib::IndexManager::getHistory(), QuantLib::Singleton< IndexManager >::instance(), name(), quotes_, and QuantLib::IndexManager::setHistory().
{
        //QL_REQUIRE(isValidQuoteDate(quoteDate),
        //           "Quote date " << quoteDate.weekday() << ", " <<
        //           quoteDate << " is not valid");
        std::string tag = name();
        quotes_ = IndexManager::instance().getHistory(tag);
        quotes_[quoteDate] = quote;
        IndexManager::instance().setHistory(tag, quotes_);
    }
void QuantLib::CommodityIndex::addQuotes (const std::map< Date, Real > & quotes) [inline]
Definition at line 71 of file commodityindex.hpp.
References QuantLib::IndexManager::getHistory(), QuantLib::Singleton< IndexManager >::instance(), name(), quotes_, and QuantLib::IndexManager::setHistory().
{
            std::string tag = name();
            quotes_ = IndexManager::instance().getHistory(tag);
            for (std::map<Date, Real>::const_iterator ii = quotes.begin();
                 ii != quotes.end (); ii++) {
                quotes_[ii->first] = ii->second;
            }
            IndexManager::instance().setHistory(tag, quotes_);
        }
const Calendar & QuantLib::CommodityIndex::calendar () const [inline]
Definition at line 130 of file commodityindex.hpp.
References calendar_.
Referenced by isValidQuoteDate().
{
        return calendar_;
    }
void QuantLib::CommodityIndex::clearQuotes () [inline]
Definition at line 195 of file commodityindex.hpp.
References QuantLib::IndexManager::clearHistory(), QuantLib::Singleton< IndexManager >::instance(), and name().
{
        IndexManager::instance().clearHistory(name());
    }
const CommodityType & QuantLib::CommodityIndex::commodityType () const [inline]
Definition at line 118 of file commodityindex.hpp.
References commodityType_.
{
        return commodityType_;
    }
const Currency & QuantLib::CommodityIndex::currency () const [inline]
Definition at line 126 of file commodityindex.hpp.
References currency_.
{
        return currency_;
    }
bool QuantLib::CommodityIndex::empty () const [inline]
Definition at line 175 of file commodityindex.hpp.
References QuantLib::TimeSeries< T, Container >::empty(), and quotes_.
{
        return quotes_.empty();
    }
const boost::shared_ptr< CommodityCurve > & QuantLib::CommodityIndex::forwardCurve () const [inline]
Definition at line 139 of file commodityindex.hpp.
References forwardCurve_.
{
        return forwardCurve_;
    }
bool QuantLib::CommodityIndex::forwardCurveEmpty () const [inline]
Definition at line 179 of file commodityindex.hpp.
References forwardCurve_.
{
        if (forwardCurve_ != 0)
            return forwardCurve_->empty();
        return false;
    }
Real QuantLib::CommodityIndex::forwardPrice (const Date & date) const [inline]
Definition at line 158 of file commodityindex.hpp.
References exchangeContracts_, forwardCurve_, forwardCurveUomConversionFactor_, name_, nearbyOffset_, and QL_FAIL.
{
        try {
            Real forwardPrice =
                forwardCurve_->price(date, exchangeContracts_, nearbyOffset_);
            return forwardPrice * forwardCurveUomConversionFactor_;
        } catch (const std::exception& e) {
            QL_FAIL("error fetching forward price for index " << name_
                    << ": " << e.what());
        }
    }
bool QuantLib::CommodityIndex::isValidQuoteDate (const Date & quoteDate) const [inline]
returns TRUE if the quote date is valid
Definition at line 199 of file commodityindex.hpp.
References calendar(), and QuantLib::Calendar::isBusinessDay().
{
        return calendar().isBusinessDay(quoteDate);
    }
Date QuantLib::CommodityIndex::lastQuoteDate () const [inline]
Definition at line 169 of file commodityindex.hpp.
References QuantLib::TimeSeries< T, Container >::empty(), QuantLib::TimeSeries< T, Container >::lastDate(), QuantLib::Date::minDate(), and quotes_.
{
        if (quotes_.empty())
            return Date::minDate();
        return quotes_.lastDate();
    }
Real QuantLib::CommodityIndex::lotQuantity () const [inline]
Definition at line 134 of file commodityindex.hpp.
References lotQuantity_.
{
        return lotQuantity_;
    }
std::string QuantLib::CommodityIndex::name () const [inline]
Definition at line 114 of file commodityindex.hpp.
References name_.
Referenced by addQuote(), addQuotes(), clearQuotes(), CommodityIndex(), and QuantLib::operator==().
{
        return name_;
    }
Real QuantLib::CommodityIndex::price (const Date & date) [inline]
Definition at line 147 of file commodityindex.hpp.
References QuantLib::TimeSeries< T, Container >::end(), QuantLib::TimeSeries< T, Container >::find(), and quotes_.
{
        std::map<Date, Real>::const_iterator hq = quotes_.find(date);
        if (hq->second == Null<Real>()) {
            hq++;
            if (hq == quotes_.end())
                //if (hq->second == Null<Real>())
                return Null<Real>();
        }
        return hq->second;
    }
const TimeSeries< Real > & QuantLib::CommodityIndex::quotes () const [inline]
Definition at line 143 of file commodityindex.hpp.
References quotes_.
{
        return quotes_;
    }
const UnitOfMeasure & QuantLib::CommodityIndex::unitOfMeasure () const [inline]
Definition at line 122 of file commodityindex.hpp.
References unitOfMeasure_.
{
        return unitOfMeasure_;
    }
void QuantLib::CommodityIndex::update () [inline, virtual]
This method must be implemented in derived classes. An instance of Observer does not call this method directly: instead, it will be called by the observables the instance registered with when they need to notify any changes.
Implements QuantLib::Observer.
Definition at line 110 of file commodityindex.hpp.
References QuantLib::Observable::notifyObservers().
{
        notifyObservers();
    }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const CommodityIndex & index) [friend]
Definition at line 54 of file commodityindex.cpp.
{
        out << "[" << index.name_ << "] ("
            << index.currency_.code() << "/"
            << index.unitOfMeasure_.code() << ")";
        if (index.forwardCurve_ != 0)
            out << "; forward (" << (*index.forwardCurve_) << ")";
        return out;
    }
Member Data Documentation
Calendar QuantLib::CommodityIndex::calendar_ [protected]
Definition at line 94 of file commodityindex.hpp.
Referenced by calendar().
CommodityType QuantLib::CommodityIndex::commodityType_ [protected]
Definition at line 91 of file commodityindex.hpp.
Referenced by CommodityIndex(), and commodityType().
Currency QuantLib::CommodityIndex::currency_ [protected]
Definition at line 93 of file commodityindex.hpp.
Referenced by currency(), and QuantLib::operator<<().
boost::shared_ptr<ExchangeContracts> QuantLib::CommodityIndex::exchangeContracts_ [protected]
Definition at line 99 of file commodityindex.hpp.
Referenced by forwardPrice().
boost::shared_ptr<CommodityCurve> QuantLib::CommodityIndex::forwardCurve_ [protected]
Definition at line 97 of file commodityindex.hpp.
Referenced by CommodityIndex(), forwardCurve(), forwardCurveEmpty(), forwardPrice(), and QuantLib::operator<<().
Real QuantLib::CommodityIndex::forwardCurveUomConversionFactor_ [protected]
Definition at line 98 of file commodityindex.hpp.
Referenced by CommodityIndex(), and forwardPrice().
Real QuantLib::CommodityIndex::lotQuantity_ [protected]
Definition at line 95 of file commodityindex.hpp.
Referenced by lotQuantity().
std::string QuantLib::CommodityIndex::name_ [protected]
Definition at line 90 of file commodityindex.hpp.
Referenced by forwardPrice(), name(), and QuantLib::operator<<().
Integer QuantLib::CommodityIndex::nearbyOffset_ [protected]
Definition at line 100 of file commodityindex.hpp.
Referenced by forwardPrice().
TimeSeries<Real> QuantLib::CommodityIndex::quotes_ [protected]
Definition at line 96 of file commodityindex.hpp.
Referenced by addQuote(), addQuotes(), CommodityIndex(), empty(), lastQuoteDate(), price(), and quotes().
UnitOfMeasure QuantLib::CommodityIndex::unitOfMeasure_ [protected]
Definition at line 92 of file commodityindex.hpp.
Referenced by CommodityIndex(), QuantLib::operator<<(), and unitOfMeasure().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/commodities/commodityindex.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/commodities/commodityindex.cpp