QuantLib: QuantLib::FdmExpExtOUInnerValueCalculator Class Reference
QuantLib::FdmExpExtOUInnerValueCalculator Class Reference
#include <fdmexpextouinnervaluecalculator.hpp>
Public Types
typedef std::vector< std::pair
< Time, Real > > Shape
Public Member Functions
FdmExpExtOUInnerValueCalculator (const boost::shared_ptr< Payoff > &payoff, const boost::shared_ptr< FdmMesher > &mesher, const boost::shared_ptr< Shape > &shape=boost::shared_ptr< Shape >(), Size direction=0)
Real innerValue (const FdmLinearOpIterator &iter, Time t)
Real avgInnerValue (const FdmLinearOpIterator &iter, Time t)
Private Attributes
const Size direction_
const boost::shared_ptr< Payoff > payoff_
const boost::shared_ptr
< FdmMesher > mesher_
const boost::shared_ptr< Shape > shape_
Detailed Description
Definition at line 34 of file fdmexpextouinnervaluecalculator.hpp.
Member Typedef Documentation
typedef std::vector<std::pair<Time, Real> > QuantLib::FdmExpExtOUInnerValueCalculator::Shape
Definition at line 36 of file fdmexpextouinnervaluecalculator.hpp.
Constructor & Destructor Documentation
QuantLib::FdmExpExtOUInnerValueCalculator::FdmExpExtOUInnerValueCalculator (const boost::shared_ptr< Payoff > & payoff, const boost::shared_ptr< FdmMesher > & mesher, const boost::shared_ptr< Shape > & shape = boost::shared_ptr<Shape>(), Size direction = 0) [inline]
Definition at line 38 of file fdmexpextouinnervaluecalculator.hpp.
        : direction_(direction),
          payoff_(payoff),
          mesher_(mesher),
          shape_(shape) { }
Member Function Documentation
Real QuantLib::FdmExpExtOUInnerValueCalculator::avgInnerValue (const FdmLinearOpIterator & iter, Time t) [inline, virtual]
Implements QuantLib::FdmInnerValueCalculator.
Definition at line 59 of file fdmexpextouinnervaluecalculator.hpp.
References innerValue().
{
            return innerValue(iter, t);
        }
Real QuantLib::FdmExpExtOUInnerValueCalculator::innerValue (const FdmLinearOpIterator & iter, Time t) [inline, virtual]
Implements QuantLib::FdmInnerValueCalculator.
Definition at line 48 of file fdmexpextouinnervaluecalculator.hpp.
References direction_, anonymous_namespace{interpolations.cpp}::f(), mesher_, payoff_, QL_EPSILON, and shape_.
Referenced by avgInnerValue().
{
            const Real u = mesher_->location(iter, direction_);
            Real f = 0;
            if (shape_) {
                f = std::lower_bound(shape_->begin(), shape_->end(),
                   std::pair<Time, Real>(t-std::sqrt(QL_EPSILON), 0.0))->second;
            }
            return payoff_->operator()(std::exp(f + u));
        }
Member Data Documentation
const Size QuantLib::FdmExpExtOUInnerValueCalculator::direction_ [private]
Definition at line 63 of file fdmexpextouinnervaluecalculator.hpp.
Referenced by innerValue().
const boost::shared_ptr<FdmMesher> QuantLib::FdmExpExtOUInnerValueCalculator::mesher_ [private]
Definition at line 65 of file fdmexpextouinnervaluecalculator.hpp.
Referenced by innerValue().
const boost::shared_ptr<Payoff> QuantLib::FdmExpExtOUInnerValueCalculator::payoff_ [private]
Definition at line 64 of file fdmexpextouinnervaluecalculator.hpp.
Referenced by innerValue().
const boost::shared_ptr<Shape> QuantLib::FdmExpExtOUInnerValueCalculator::shape_ [private]
Definition at line 66 of file fdmexpextouinnervaluecalculator.hpp.
Referenced by innerValue().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/finitedifferences/fdmexpextouinnervaluecalculator.hpp