QuantLib: QuantLib::China::SseImpl Class Reference
QuantLib::China::SseImpl Class Reference
Public Member Functions
std::string name () const
bool isWeekend (Weekday) const
bool isBusinessDay (const Date &) const
Detailed Description
Definition at line 58 of file china.hpp.
Member Function Documentation
bool QuantLib::China::SseImpl::isBusinessDay (const Date & date) const [virtual]
Implements QuantLib::Calendar::Impl.
Definition at line 42 of file china.cpp.
References QuantLib::April, anonymous_namespace{marketmodel.cpp}::d, QuantLib::Date::dayOfMonth(), QuantLib::December, QuantLib::February, QuantLib::Calendar::isWeekend(), QuantLib::January, QuantLib::June, QuantLib::May, QuantLib::Date::month(), QuantLib::October, QuantLib::September, QuantLib::Date::weekday(), and QuantLib::Date::year().
{
        Weekday w = date.weekday();
        Day d = date.dayOfMonth();
        Month m = date.month();
        Year y = date.year();
        if (isWeekend(w)
            // New Year's Day
            || (d == 1 && m == January)
            || (y == 2005 && d == 3 && m == January)
            || (y == 2006 && (d == 2 || d == 3) && m == January)
            || (y == 2007 && d <= 3 && m == January)
            || (y == 2007 && d == 31 && m == December)
            || (y == 2009 && d == 2 && m == January)
            || (y == 2011 && d == 3 && m == January)
            // Chinese New Year
            || (y == 2004 && d >= 19 && d <= 28 && m == January)
            || (y == 2005 && d >=  7 && d <= 15 && m == February)
            || (y == 2006 && ((d >= 26 && m == January) ||
                              (d <= 3 && m == February)))
            || (y == 2007 && d >= 17 && d <= 25 && m == February)
            || (y == 2008 && d >= 6 && d <= 12 && m == February)
            || (y == 2009 && d >= 26 && d <= 30 && m == January)
            || (y == 2010 && d >= 15 && d <= 19 && m == January)
            || (y == 2011 && d >= 2 && d <= 8 && m == February)
            // Ching Ming Festival
            || (y <= 2008 && d == 4 && m == April)
            || (y == 2009 && d == 6 && m == April)
            || (y == 2010 && d == 5 && m == April)
            || (y == 2011 && d >=3 && d <= 5 && m == April)
            // Labor Day
            || (y <= 2007 && d >= 1 && d <= 7 && m == May)
            || (y == 2008 && d >= 1 && d <= 2 && m == May)
            || (y == 2009 && d == 1 && m == May)
            || (y == 2010 && d == 3 && m == May)
            || (y == 2011 && d == 2 && m == May)
            // Tuen Ng Festival
            || (y <= 2008 && d == 9 && m == June)
            || (y == 2009 && (d == 28 || d == 29) && m == May)
            || (y == 2010 && d >= 14 && d <= 16 && m == June)
            || (y == 2011 && d >= 4 && d <= 6 && m == June)
            // Mid-Autumn Festival
            || (y <= 2008 && d == 15 && m == September)
            || (y == 2010 && d >= 22 && d <= 24 && m == September)
            || (y == 2011 && d >= 10 && d <= 12 && m == September)
            // National Day
            || (y <= 2007 && d >= 1 && d <= 7 && m == October)
            || (y == 2008 && ((d >= 29 && m == September) ||
                              (d <= 3 && m == October)))
            || (y == 2009 && d >= 1 && d <= 8 && m == October)
            || (y == 2010 && d >= 1 && d <= 7 && m == October)
            || (y == 2011 && d >= 1 && d <= 7 && m == October)
            )
            return false;
        return true;
    }
bool QuantLib::China::SseImpl::isWeekend (Weekday w) const [virtual]
Implements QuantLib::Calendar::Impl.
Definition at line 38 of file china.cpp.
References QuantLib::Saturday, and QuantLib::Sunday.
{
        return w == Saturday || w == Sunday;
    }
std::string QuantLib::China::SseImpl::name () const [inline, virtual]
Implements QuantLib::Calendar::Impl.
Definition at line 60 of file china.hpp.
{ return "Shanghai stock exchange"; }
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/time/calendars/china.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/time/calendars/china.cpp