QuantLib: QuantLib::LiborForwardModel Class Reference
QuantLib::LiborForwardModel Class Reference
Libor forward model
#include <liborforwardmodel.hpp>
Public Member Functions
LiborForwardModel (const boost::shared_ptr< LiborForwardModelProcess > &process, const boost::shared_ptr< LmVolatilityModel > &volaModel, const boost::shared_ptr< LmCorrelationModel > &corrModel)
Rate S_0 (Size alpha, Size beta) const
virtual boost::shared_ptr
< SwaptionVolatilityMatrix > getSwaptionVolatilityMatrix () const
DiscountFactor discount (Time t) const
Implied discount curve.
Real discountBond (Time now, Time maturity, Array factors) const
Real discountBondOption (Option::Type type, Real strike, Time maturity, Time bondMaturity) const
void setParams (const Array &params)
Protected Member Functions
Disposable< Array > w_0 (Size alpha, Size beta) const
Protected Attributes
std::vector< Real > f_
std::vector< Time > accrualPeriod_
const boost::shared_ptr
< LfmCovarianceProxy > covarProxy_
const boost::shared_ptr
< LiborForwardModelProcess > process_
boost::shared_ptr
< SwaptionVolatilityMatrix > swaptionVola
Detailed Description
Libor forward model
References:
Stefan Weber, 2005, Efficient Calibration for Libor Market Models, (<http://workshop.mathfinance.de/2005/papers/weber/slides.pdf>)
Damiano Brigo, Fabio Mercurio, Massimo Morini, 2003, Different Covariance Parameterizations of Libor Market Model and Joint Caps/Swaptions Calibration, (<http://www.business.uts.edu.au/qfrc/conferences/qmf2001/Brigo_D.pdf>
Test:
the correctness is tested using Monte-Carlo Simulation to reproduce swaption npvs, model calibration and exact cap pricing
Definition at line 51 of file liborforwardmodel.hpp.
Constructor & Destructor Documentation
QuantLib::LiborForwardModel::LiborForwardModel (const boost::shared_ptr< LiborForwardModelProcess > & process, const boost::shared_ptr< LmVolatilityModel > & volaModel, const boost::shared_ptr< LmCorrelationModel > & corrModel)
Definition at line 26 of file liborforwardmodel.cpp.
References accrualPeriod_, QuantLib::CalibratedModel::arguments_, f_, and process_.
     : CalibratedModel(volaModel->params().size()+corrModel->params().size()),
       f_(process->size()),
       accrualPeriod_(process->size()),
       covarProxy_(new LfmCovarianceProxy(volaModel, corrModel)),
       process_(process)
     {
         const Size k=volaModel->params().size();
         std::copy(volaModel->params().begin(), volaModel->params().end(),
                   arguments_.begin());
         std::copy(corrModel->params().begin(), corrModel->params().end(),
                   arguments_.begin()+k);
         for (Size i=0; i < process->size(); ++i) {
             accrualPeriod_[i] =  process->accrualEndTimes()[i]
                                - process->accrualStartTimes()[i];
             f_[i] = 1.0/(1.0+accrualPeriod_[i]*process_->initialValues()[i]);
         }
    }
Member Function Documentation
DiscountFactor QuantLib::LiborForwardModel::discount (Time t) const [virtual]
Implied discount curve.
Implements QuantLib::AffineModel.
Definition at line 202 of file liborforwardmodel.cpp.
References process_.
Referenced by discountBond().
{
        return process_->index()->forwardingTermStructure()->discount(t);
    }
Real QuantLib::LiborForwardModel::discountBond (Time now, Time maturity, Array factors) const [virtual]
Implements QuantLib::AffineModel.
Definition at line 206 of file liborforwardmodel.cpp.
References discount().
{
        return discount(maturity);
    }
Real QuantLib::LiborForwardModel::discountBondOption (Option::Type type, Real strike, Time maturity, Time bondMaturity) const [virtual]
Implements QuantLib::AffineModel.
Definition at line 63 of file liborforwardmodel.cpp.
References QuantLib::blackFormula(), QuantLib::Option::Call, covarProxy_, process_, QuantLib::Option::Put, and QL_REQUIRE.
{
        const std::vector<Time> & accrualStartTimes
            = process_->accrualStartTimes();
        const std::vector<Time> & accrualEndTimes
            = process_->accrualEndTimes();
        QL_REQUIRE(   accrualStartTimes.front()<= maturity
                   && accrualStartTimes.back() >= maturity,
                   "capet maturity does not fit to the process");
        const Size i = std::lower_bound(accrualStartTimes.begin(),
                                        accrualStartTimes.end(),
                                        maturity) - accrualStartTimes.begin();
        QL_REQUIRE(   i<process_->size()
                   && std::fabs(maturity - accrualStartTimes[i])
                        < 100*std::numeric_limits<Real>::epsilon()
                   && std::fabs(bondMaturity - accrualEndTimes[i])
                        < 100*std::numeric_limits<Real>::epsilon(),
                   "irregular fixings are not (yet) supported");
        const Real tenor     = accrualEndTimes[i] - accrualStartTimes[i];
        const Real forward   = process_->initialValues()[i];
        const Real capRate   = (1.0/strike - 1.0)/tenor;
        const Volatility var = covarProxy_
            ->integratedCovariance(i, i, process_->fixingTimes()[i]);
        const DiscountFactor dis =
            process_->index()->forwardingTermStructure()->discount(bondMaturity);
        const Real black = blackFormula(
            (type==Option::Put ? Option::Call : Option::Put),
            capRate, forward, std::sqrt(var));
        const Real npv = dis * tenor * black;
        return npv / (1.0 + capRate*tenor);
    }
boost::shared_ptr< SwaptionVolatilityMatrix > QuantLib::LiborForwardModel::getSwaptionVolatilityMatrix () const [virtual]
Definition at line 147 of file liborforwardmodel.cpp.
References anonymous_namespace{marketmodel.cpp}::beta, covarProxy_, anonymous_namespace{swaption.cpp}::exercises, anonymous_namespace{interpolations.cpp}::f(), anonymous_namespace{swaption.cpp}::lengths, process_, S_0(), swaptionVola, anonymous_namespace{marketmodel.cpp}::volatilities, and w_0().
{
        if (swaptionVola) {
            return swaptionVola;
        }
        const boost::shared_ptr<IborIndex> index = process_->index();
        const Date today = process_->fixingDates()[0];
        const Size size=process_->size()/2;
        Matrix volatilities(size, size);
        std::vector<Date> exercises(process_->fixingDates().begin() + 1,
                                    process_->fixingDates().begin() + size+1);
        std::vector<Period> lengths(size);
        for (Size i=0; i < size; ++i) {
            lengths[i] = (i+1)*index->tenor();
        }
        const Array f = process_->initialValues();
        for (Size k=0; k < size; ++k) {
            const Size alpha  =k;
            const Time t_alpha=process_->fixingTimes()[alpha+1];
            Matrix var(size, size);
            for (Size i=alpha+1; i <= k+size; ++i) {
                for (Size j=i; j <= k+size; ++j) {
                    var[i-alpha-1][j-alpha-1] = var[j-alpha-1][i-alpha-1] =
                        covarProxy_->integratedCovariance(i, j, t_alpha);
                }
            }
            for (Size l=1; l <= size; ++l) {
                const Size beta =l + k;
                const Array w = w_0(alpha, beta);
                Real sum=0.0;
                for (Size i=alpha+1; i <= beta; ++i) {
                    for (Size j=alpha+1; j <= beta; ++j) {
                        sum+=w[i]*w[j]*f[i]*f[j]*var[i-alpha-1][j-alpha-1];
                    }
                }
                volatilities[k][l-1] =
                    std::sqrt(sum/t_alpha)/S_0(alpha, beta);
            }
        }
        return swaptionVola = boost::shared_ptr<SwaptionVolatilityMatrix>(
             new SwaptionVolatilityMatrix(today, exercises, lengths,
                                          volatilities,
                                          index->dayCounter()));
    }
Rate QuantLib::LiborForwardModel::S_0 (Size alpha, Size beta) const
Definition at line 129 of file liborforwardmodel.cpp.
References anonymous_namespace{marketmodel.cpp}::beta, anonymous_namespace{interpolations.cpp}::f(), process_, and w_0().
Referenced by getSwaptionVolatilityMatrix().
{
        const Array w = w_0(alpha, beta);
        const Array f = process_->initialValues();
        Rate fwdRate=0.0;
        for (Size i=alpha+1; i <=beta; ++i) {
            fwdRate+=w[i]*f[i];
        }
        return fwdRate;
    }
void QuantLib::LiborForwardModel::setParams (const Array & params) [virtual]
Reimplemented from QuantLib::CalibratedModel.
Definition at line 50 of file liborforwardmodel.cpp.
References QuantLib::CalibratedModel::arguments_, covarProxy_, and swaptionVola.
{
        CalibratedModel::setParams(params);
        const Size k=covarProxy_->volatilityModel()->params().size();
        covarProxy_->volatilityModel()->setParams(
            std::vector<Parameter>(arguments_.begin(), arguments_.begin()+k));
        covarProxy_->correlationModel()->setParams(
            std::vector<Parameter>(arguments_.begin()+k, arguments_.end()));
        swaptionVola = boost::shared_ptr<SwaptionVolatilityMatrix>();
    }
Disposable< Array > QuantLib::LiborForwardModel::w_0 (Size alpha, Size beta) const [protected]
Definition at line 104 of file liborforwardmodel.cpp.
References anonymous_namespace{marketmodel.cpp}::a, accrualPeriod_, anonymous_namespace{marketmodel.cpp}::b, anonymous_namespace{marketmodel.cpp}::beta, f_, and QL_REQUIRE.
Referenced by getSwaptionVolatilityMatrix(), and S_0().
{
        Array omega(beta+1,0.0);
        QL_REQUIRE(alpha<beta, "alpha needs to be smaller than beta");
        Real s=0.0;
        for (Size k=alpha+1; k<=beta; ++k) {
            Real b=accrualPeriod_[k];
            for (Size j=alpha+1; j<=k; ++j) {
                b*=f_[j];
            }
            s+=b;
        }
        for (Size i=alpha+1; i<=beta; ++i) {
            Real a=accrualPeriod_[i];
            for (Size j=alpha+1; j<=i; ++j) {
                a*=f_[j];
            }
            omega[i] = a/s;
        }
        return omega;
    }
Member Data Documentation
std::vector<Time> QuantLib::LiborForwardModel::accrualPeriod_ [protected]
Definition at line 74 of file liborforwardmodel.hpp.
Referenced by LiborForwardModel(), and w_0().
const boost::shared_ptr<LfmCovarianceProxy> QuantLib::LiborForwardModel::covarProxy_ [protected]
Definition at line 76 of file liborforwardmodel.hpp.
Referenced by discountBondOption(), getSwaptionVolatilityMatrix(), and setParams().
std::vector<Real> QuantLib::LiborForwardModel::f_ [protected]
Definition at line 73 of file liborforwardmodel.hpp.
Referenced by LiborForwardModel(), and w_0().
const boost::shared_ptr<LiborForwardModelProcess> QuantLib::LiborForwardModel::process_ [protected]
Definition at line 77 of file liborforwardmodel.hpp.
Referenced by discount(), discountBondOption(), getSwaptionVolatilityMatrix(), LiborForwardModel(), and S_0().
boost::shared_ptr<SwaptionVolatilityMatrix> QuantLib::LiborForwardModel::swaptionVola [mutable, protected]
Definition at line 79 of file liborforwardmodel.hpp.
Referenced by getSwaptionVolatilityMatrix(), and setParams().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/legacy/libormarketmodels/liborforwardmodel.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/legacy/libormarketmodels/liborforwardmodel.cpp