QuantLib: QuantLib::RangeAccrualFloatersCoupon Class Reference
QuantLib::RangeAccrualFloatersCoupon Class Reference
#include <rangeaccrual.hpp>
Public Member Functions
RangeAccrualFloatersCoupon (const Date &paymentDate, Real nominal, const boost::shared_ptr< IborIndex > &index, const Date &startDate, const Date &endDate, Natural fixingDays, const DayCounter &dayCounter, Real gearing, Rate spread, const Date &refPeriodStart, const Date &refPeriodEnd, const boost::shared_ptr< Schedule > &observationsSchedule, Real lowerTrigger, Real upperTrigger)
Real startTime () const
Real endTime () const
Real lowerTrigger () const
Real upperTrigger () const
Size observationsNo () const
const std::vector< Date > & observationDates () const
const std::vector< Real > & observationTimes () const
const boost::shared_ptr< Schedule > observationsSchedule () const
Real priceWithoutOptionality (const Handle< YieldTermStructure > &discountCurve) const
Visitability
virtual void accept (AcyclicVisitor &)
Private Attributes
Real startTime_
Real endTime_
const boost::shared_ptr< Schedule > observationsSchedule_
std::vector< Date > observationDates_
std::vector< Real > observationTimes_
Size observationsNo_
Real lowerTrigger_
Real upperTrigger_
Detailed Description
Definition at line 40 of file rangeaccrual.hpp.
Constructor & Destructor Documentation
QuantLib::RangeAccrualFloatersCoupon::RangeAccrualFloatersCoupon (const Date & paymentDate, Real nominal, const boost::shared_ptr< IborIndex > & index, const Date & startDate, const Date & endDate, Natural fixingDays, const DayCounter & dayCounter, Real gearing, Rate spread, const Date & refPeriodStart, const Date & refPeriodEnd, const boost::shared_ptr< Schedule > & observationsSchedule, Real lowerTrigger, Real upperTrigger)
Definition at line 38 of file rangeaccrual.cpp.
References anonymous_namespace{marketmodel.cpp}::endDate, endTime_, lowerTrigger_, observationDates_, observationsNo_, observationsSchedule_, observationTimes_, QL_REQUIRE, anonymous_namespace{marketmodel.cpp}::startDate, startTime_, and QuantLib::DayCounter::yearFraction().
    : FloatingRateCoupon(paymentDate, nominal, startDate, endDate,
                         fixingDays, index, gearing, spread,
                         refPeriodStart, refPeriodEnd, dayCounter),
    observationsSchedule_(observationsSchedule),
    lowerTrigger_(lowerTrigger),
    upperTrigger_(upperTrigger){
        QL_REQUIRE(lowerTrigger_<upperTrigger,
                   "lowerTrigger_>=upperTrigger");
        QL_REQUIRE(observationsSchedule_->startDate()==startDate,
                   "incompatible start date");
        QL_REQUIRE(observationsSchedule_->endDate()==endDate,
                   "incompatible end date");
        observationDates_ = observationsSchedule_->dates();
        observationDates_.pop_back();                       //remove end date
        observationDates_.erase(observationDates_.begin()); //remove start date
        observationsNo_ = observationDates_.size();
        const Handle<YieldTermStructure>& rateCurve =
            index->forwardingTermStructure();
        Date referenceDate = rateCurve->referenceDate();
        startTime_ = dayCounter.yearFraction(referenceDate, startDate);
        endTime_ = dayCounter.yearFraction(referenceDate, endDate);
        for(Size i=0;i<observationsNo_;i++) {
            observationTimes_.push_back(
                dayCounter.yearFraction(referenceDate, observationDates_[i]));
        }
     }
Member Function Documentation
void QuantLib::RangeAccrualFloatersCoupon::accept (AcyclicVisitor & v) [virtual]
Reimplemented from QuantLib::FloatingRateCoupon.
Definition at line 86 of file rangeaccrual.cpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Visitor< T >::visit().
{
        Visitor<RangeAccrualFloatersCoupon>* v1 =
            dynamic_cast<Visitor<RangeAccrualFloatersCoupon>*>(&v);
        if (v1 != 0)
            v1->visit(*this);
        else
            FloatingRateCoupon::accept(v);
    }
Real QuantLib::RangeAccrualFloatersCoupon::endTime () const [inline]
Definition at line 61 of file rangeaccrual.hpp.
References endTime_.
Referenced by QuantLib::RangeAccrualPricer::initialize().
{return endTime_; }
Real QuantLib::RangeAccrualFloatersCoupon::lowerTrigger () const [inline]
Definition at line 62 of file rangeaccrual.hpp.
References lowerTrigger_.
Referenced by QuantLib::RangeAccrualPricer::initialize().
{return lowerTrigger_; }
const std::vector<Date>& QuantLib::RangeAccrualFloatersCoupon::observationDates () const [inline]
Definition at line 65 of file rangeaccrual.hpp.
References observationDates_.
{
            return observationDates_;
        }
Size QuantLib::RangeAccrualFloatersCoupon::observationsNo () const [inline]
Definition at line 64 of file rangeaccrual.hpp.
References observationsNo_.
Referenced by QuantLib::RangeAccrualPricer::initialize().
{return observationsNo_; }
const boost::shared_ptr<Schedule> QuantLib::RangeAccrualFloatersCoupon::observationsSchedule () const [inline]
Definition at line 71 of file rangeaccrual.hpp.
References observationsSchedule_.
Referenced by QuantLib::RangeAccrualPricer::initialize().
{
            return observationsSchedule_;
        }
const std::vector<Real>& QuantLib::RangeAccrualFloatersCoupon::observationTimes () const [inline]
Definition at line 68 of file rangeaccrual.hpp.
References observationTimes_.
Referenced by QuantLib::RangeAccrualPricer::initialize().
{
            return observationTimes_;
        }
Real QuantLib::RangeAccrualFloatersCoupon::priceWithoutOptionality (const Handle< YieldTermStructure > & discountCurve) const
Definition at line 95 of file rangeaccrual.cpp.
References QuantLib::Coupon::accrualPeriod(), QuantLib::Coupon::date(), QuantLib::FloatingRateCoupon::gearing_, QuantLib::FloatingRateCoupon::indexFixing(), QuantLib::Coupon::nominal(), and QuantLib::FloatingRateCoupon::spread_.
{
        return accrualPeriod() * (gearing_*indexFixing()+spread_) *
               nominal() * discountingCurve->discount(date());
    }
Real QuantLib::RangeAccrualFloatersCoupon::startTime () const [inline]
Definition at line 60 of file rangeaccrual.hpp.
References startTime_.
Referenced by QuantLib::RangeAccrualPricer::initialize().
{return startTime_; }
Real QuantLib::RangeAccrualFloatersCoupon::upperTrigger () const [inline]
Definition at line 63 of file rangeaccrual.hpp.
References upperTrigger_.
Referenced by QuantLib::RangeAccrualPricer::initialize().
{return upperTrigger_; }
Member Data Documentation
Real QuantLib::RangeAccrualFloatersCoupon::endTime_ [private]
Definition at line 84 of file rangeaccrual.hpp.
Referenced by endTime(), and RangeAccrualFloatersCoupon().
Real QuantLib::RangeAccrualFloatersCoupon::lowerTrigger_ [private]
Definition at line 91 of file rangeaccrual.hpp.
Referenced by lowerTrigger(), and RangeAccrualFloatersCoupon().
std::vector<Date> QuantLib::RangeAccrualFloatersCoupon::observationDates_ [private]
Definition at line 87 of file rangeaccrual.hpp.
Referenced by observationDates(), and RangeAccrualFloatersCoupon().
Size QuantLib::RangeAccrualFloatersCoupon::observationsNo_ [private]
Definition at line 89 of file rangeaccrual.hpp.
Referenced by observationsNo(), and RangeAccrualFloatersCoupon().
const boost::shared_ptr<Schedule> QuantLib::RangeAccrualFloatersCoupon::observationsSchedule_ [private]
Definition at line 86 of file rangeaccrual.hpp.
Referenced by observationsSchedule(), and RangeAccrualFloatersCoupon().
std::vector<Real> QuantLib::RangeAccrualFloatersCoupon::observationTimes_ [private]
Definition at line 88 of file rangeaccrual.hpp.
Referenced by observationTimes(), and RangeAccrualFloatersCoupon().
Real QuantLib::RangeAccrualFloatersCoupon::startTime_ [private]
Definition at line 83 of file rangeaccrual.hpp.
Referenced by RangeAccrualFloatersCoupon(), and startTime().
Real QuantLib::RangeAccrualFloatersCoupon::upperTrigger_ [private]
Definition at line 92 of file rangeaccrual.hpp.
Referenced by upperTrigger().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/rangeaccrual.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/rangeaccrual.cpp