QuantLib: QuantLib::MakeVanillaSwap Class Reference
QuantLib::MakeVanillaSwap Class Reference
helper class
#include <makevanillaswap.hpp>
Public Member Functions
MakeVanillaSwap (const Period &swapTenor, const boost::shared_ptr< IborIndex > &iborIndex, Rate fixedRate=Null< Rate >(), const Period &forwardStart=0 *Days)
operator VanillaSwap () const
operator boost::shared_ptr< VanillaSwap > () const
MakeVanillaSwap & receiveFixed (bool flag=true)
MakeVanillaSwap & withType (VanillaSwap::Type type)
MakeVanillaSwap & withNominal (Real n)
MakeVanillaSwap & withEffectiveDate (const Date &)
MakeVanillaSwap & withTerminationDate (const Date &)
MakeVanillaSwap & withRule (DateGeneration::Rule r)
MakeVanillaSwap & withFixedLegTenor (const Period &t)
MakeVanillaSwap & withFixedLegCalendar (const Calendar &cal)
MakeVanillaSwap & withFixedLegConvention (BusinessDayConvention bdc)
MakeVanillaSwap & withFixedLegTerminationDateConvention (BusinessDayConvention bdc)
MakeVanillaSwap & withFixedLegRule (DateGeneration::Rule r)
MakeVanillaSwap & withFixedLegEndOfMonth (bool flag=true)
MakeVanillaSwap & withFixedLegFirstDate (const Date &d)
MakeVanillaSwap & withFixedLegNextToLastDate (const Date &d)
MakeVanillaSwap & withFixedLegDayCount (const DayCounter &dc)
MakeVanillaSwap & withFloatingLegTenor (const Period &t)
MakeVanillaSwap & withFloatingLegCalendar (const Calendar &cal)
MakeVanillaSwap & withFloatingLegConvention (BusinessDayConvention bdc)
MakeVanillaSwap & withFloatingLegTerminationDateConvention (BusinessDayConvention bdc)
MakeVanillaSwap & withFloatingLegRule (DateGeneration::Rule r)
MakeVanillaSwap & withFloatingLegEndOfMonth (bool flag=true)
MakeVanillaSwap & withFloatingLegFirstDate (const Date &d)
MakeVanillaSwap & withFloatingLegNextToLastDate (const Date &d)
MakeVanillaSwap & withFloatingLegDayCount (const DayCounter &dc)
MakeVanillaSwap & withFloatingLegSpread (Spread sp)
MakeVanillaSwap & withDiscountingTermStructure (const Handle< YieldTermStructure > &discountCurve)
MakeVanillaSwap & withPricingEngine (const boost::shared_ptr< PricingEngine > &engine)
Private Attributes
Period swapTenor_
boost::shared_ptr< IborIndex > iborIndex_
Rate fixedRate_
Period forwardStart_
Date effectiveDate_
Date terminationDate_
Calendar fixedCalendar_
Calendar floatCalendar_
VanillaSwap::Type type_
Real nominal_
Period fixedTenor_
Period floatTenor_
BusinessDayConvention fixedConvention_
BusinessDayConvention fixedTerminationDateConvention_
BusinessDayConvention floatConvention_
BusinessDayConvention floatTerminationDateConvention_
DateGeneration::Rule fixedRule_
DateGeneration::Rule floatRule_
bool fixedEndOfMonth_
bool floatEndOfMonth_
Date fixedFirstDate_
Date fixedNextToLastDate_
Date floatFirstDate_
Date floatNextToLastDate_
Spread floatSpread_
DayCounter fixedDayCount_
DayCounter floatDayCount_
boost::shared_ptr< PricingEngine > engine_
Detailed Description
helper class
This class provides a more comfortable way to instantiate standard market swap.
Definition at line 39 of file makevanillaswap.hpp.
Constructor & Destructor Documentation
QuantLib::MakeVanillaSwap::MakeVanillaSwap (const Period & swapTenor, const boost::shared_ptr< IborIndex > & iborIndex, Rate fixedRate = Null<Rate>(), const Period & forwardStart = 0*Days)
Definition at line 31 of file makevanillaswap.cpp.
    : swapTenor_(swapTenor), iborIndex_(index),
      fixedRate_(fixedRate), forwardStart_(forwardStart),
      effectiveDate_(Date()),
      fixedCalendar_(index->fixingCalendar()),
      floatCalendar_(index->fixingCalendar()),
      type_(VanillaSwap::Payer), nominal_(1.0),
      floatTenor_(index->tenor()),
      fixedConvention_(ModifiedFollowing),
      fixedTerminationDateConvention_(ModifiedFollowing),
      floatConvention_(index->businessDayConvention()),
      floatTerminationDateConvention_(index->businessDayConvention()),
      fixedRule_(DateGeneration::Backward), floatRule_(DateGeneration::Backward),
      fixedEndOfMonth_(false), floatEndOfMonth_(false),
      fixedFirstDate_(Date()), fixedNextToLastDate_(Date()),
      floatFirstDate_(Date()), floatNextToLastDate_(Date()),
      floatSpread_(0.0),
      floatDayCount_(index->dayCounter()),
      engine_(new DiscountingSwapEngine(iborIndex_->forwardingTermStructure(),
                                        false))
    {
    }
Member Function Documentation
QuantLib::MakeVanillaSwap::operator boost::shared_ptr< VanillaSwap > () const
Definition at line 62 of file makevanillaswap.cpp.
References QuantLib::Date::advance(), QuantLib::Thirty360::BondBasis, QuantLib::Days, anonymous_namespace{marketmodel.cpp}::endDate, QuantLib::Settings::evaluationDate(), QuantLib::Singleton< Settings >::instance(), QuantLib::Months, QL_REQUIRE, anonymous_namespace{marketmodel.cpp}::startDate, QuantLib::swap(), and QuantLib::Years.
{
        Date startDate;
        if (effectiveDate_ != Date())
            startDate = effectiveDate_;
        else {
            Date referenceDate = Settings::instance().evaluationDate();
            Natural fixingDays = iborIndex_->fixingDays();
            Date spotDate = floatCalendar_.advance(referenceDate,
                                                   fixingDays*Days);
            startDate = spotDate+forwardStart_;
        }
        Date endDate;
        if (terminationDate_ != Date())
            endDate = terminationDate_;
        else
            endDate = startDate+swapTenor_;
        Period fixedTenor;
        if (fixedTenor_ != Period())
            fixedTenor = fixedTenor_;
        else {
            const Currency& curr = iborIndex_->currency();
            if (curr == EURCurrency())
                fixedTenor = Period(1, Years);
            else if (curr == GBPCurrency())
                fixedTenor = Period(6, Months);
            else
                fixedTenor = Period(1, Years);
        }
        Schedule fixedSchedule(startDate, endDate,
                               fixedTenor, fixedCalendar_,
                               fixedConvention_,
                               fixedTerminationDateConvention_,
                               fixedRule_, fixedEndOfMonth_,
                               fixedFirstDate_, fixedNextToLastDate_);
        Schedule floatSchedule(startDate, endDate,
                               floatTenor_, floatCalendar_,
                               floatConvention_,
                               floatTerminationDateConvention_,
                               floatRule_, floatEndOfMonth_,
                               floatFirstDate_, floatNextToLastDate_);
        DayCounter fixedDayCount;
        if (fixedDayCount_ != DayCounter())
            fixedDayCount = fixedDayCount_;
        else {
            const Currency& curr = iborIndex_->currency();
            if (curr == EURCurrency())
                fixedDayCount = Thirty360(Thirty360::BondBasis);
            else if (curr == GBPCurrency())
                fixedDayCount = Actual365Fixed();
            else
                fixedDayCount = Thirty360(Thirty360::BondBasis);
        }
        Rate usedFixedRate = fixedRate_;
        if (fixedRate_ == Null<Rate>()) {
            QL_REQUIRE(!iborIndex_->forwardingTermStructure().empty(),
                       "null term structure set to this instance of " <<
                       iborIndex_->name());
            VanillaSwap temp(type_, nominal_,
                             fixedSchedule,
                             0.0, // fixed rate
                             fixedDayCount,
                             floatSchedule, iborIndex_,
                             floatSpread_, floatDayCount_);
            temp.setPricingEngine(engine_);
            usedFixedRate = temp.fairRate();
        }
        boost::shared_ptr<VanillaSwap> swap(new
            VanillaSwap(type_, nominal_,
                        fixedSchedule,
                        usedFixedRate, fixedDayCount,
                        floatSchedule,
                        iborIndex_, floatSpread_, floatDayCount_));
        swap->setPricingEngine(engine_);
        return swap;
    }
QuantLib::MakeVanillaSwap::operator VanillaSwap () const
Definition at line 57 of file makevanillaswap.cpp.
References QuantLib::swap().
{
        boost::shared_ptr<VanillaSwap> swap = *this;
        return *swap;
    }
MakeVanillaSwap & QuantLib::MakeVanillaSwap::receiveFixed (bool flag = true)
Definition at line 146 of file makevanillaswap.cpp.
References QuantLib::VanillaSwap::Payer, QuantLib::VanillaSwap::Receiver, and type_.
{
        type_ = flag ? VanillaSwap::Receiver : VanillaSwap::Payer ;
        return *this;
    }
MakeVanillaSwap & QuantLib::MakeVanillaSwap::withDiscountingTermStructure (const Handle< YieldTermStructure > & discountCurve)
Definition at line 180 of file makevanillaswap.cpp.
References engine_.
Referenced by QuantLib::SwapRateHelper::initializeDates(), QuantLib::RendistatoCalculator::RendistatoCalculator(), and QuantLib::SwapIndex::underlyingSwap().
{
        bool includeSettlementDateFlows = false;
        engine_ = boost::shared_ptr<PricingEngine>(new
            DiscountingSwapEngine(disc, includeSettlementDateFlows));
        return *this;
    }
MakeVanillaSwap & QuantLib::MakeVanillaSwap::withEffectiveDate (const Date & effectiveDate)
Definition at line 162 of file makevanillaswap.cpp.
References effectiveDate_.
Referenced by SwaptionTest::testCachedValue(), anonymous_namespace{piecewiseyieldcurve.cpp}::testCurveConsistency(), SwaptionTest::testImpliedVolatility(), PiecewiseYieldCurveTest::testJpyLibor(), PiecewiseYieldCurveTest::testLiborFixing(), SwaptionTest::testSpreadDependency(), SwaptionTest::testSpreadTreatment(), SwaptionTest::testStrikeDependency(), SwaptionTest::testVega(), QuantLib::SwapIndex::underlyingSwap(), and QuantLib::MakeCapFloor::withEffectiveDate().
{
        effectiveDate_ = effectiveDate;
        return *this;
    }
MakeVanillaSwap & QuantLib::MakeVanillaSwap::withFixedLegCalendar (const Calendar & cal)
Definition at line 200 of file makevanillaswap.cpp.
References fixedCalendar_.
Referenced by QuantLib::SwapRateHelper::initializeDates(), PiecewiseYieldCurveTest::testJpyLibor(), QuantLib::SwapIndex::underlyingSwap(), and QuantLib::MakeCapFloor::withCalendar().
{
        fixedCalendar_ = cal;
        return *this;
    }
MakeVanillaSwap & QuantLib::MakeVanillaSwap::withFixedLegConvention (BusinessDayConvention bdc)
Definition at line 206 of file makevanillaswap.cpp.
References fixedConvention_.
Referenced by QuantLib::SwapRateHelper::initializeDates(), anonymous_namespace{piecewiseyieldcurve.cpp}::testCurveConsistency(), PiecewiseYieldCurveTest::testJpyLibor(), PiecewiseYieldCurveTest::testLiborFixing(), QuantLib::SwapIndex::underlyingSwap(), and QuantLib::MakeCapFloor::withConvention().
{
        fixedConvention_ = bdc;
        return *this;
    }
MakeVanillaSwap & QuantLib::MakeVanillaSwap::withFixedLegDayCount (const DayCounter & dc)
Definition at line 239 of file makevanillaswap.cpp.
References fixedDayCount_.
Referenced by QuantLib::SwapRateHelper::initializeDates(), anonymous_namespace{piecewiseyieldcurve.cpp}::testCurveConsistency(), PiecewiseYieldCurveTest::testJpyLibor(), PiecewiseYieldCurveTest::testLiborFixing(), QuantLib::SwapIndex::underlyingSwap(), and QuantLib::MakeCapFloor::withDayCount().
{
        fixedDayCount_ = dc;
        return *this;
    }
MakeVanillaSwap & QuantLib::MakeVanillaSwap::withFixedLegEndOfMonth (bool flag = true)
Definition at line 222 of file makevanillaswap.cpp.
References fixedEndOfMonth_.
Referenced by QuantLib::MakeCapFloor::withEndOfMonth().
{
        fixedEndOfMonth_ = flag;
        return *this;
    }
MakeVanillaSwap & QuantLib::MakeVanillaSwap::withFixedLegFirstDate (const Date & d)
Definition at line 227 of file makevanillaswap.cpp.
References anonymous_namespace{marketmodel.cpp}::d, and fixedFirstDate_.
Referenced by QuantLib::MakeCapFloor::withFirstDate().
{
        fixedFirstDate_ = d;
        return *this;
    }
MakeVanillaSwap & QuantLib::MakeVanillaSwap::withFixedLegNextToLastDate (const Date & d)
Definition at line 233 of file makevanillaswap.cpp.
References anonymous_namespace{marketmodel.cpp}::d, and fixedNextToLastDate_.
Referenced by QuantLib::MakeCapFloor::withNextToLastDate().
{
        fixedNextToLastDate_ = d;
        return *this;
    }
MakeVanillaSwap & QuantLib::MakeVanillaSwap::withFixedLegRule (DateGeneration::Rule r)
Definition at line 217 of file makevanillaswap.cpp.
References fixedRule_.
Referenced by QuantLib::MakeCapFloor::withRule().
{
        fixedRule_ = r;
        return *this;
    }
MakeVanillaSwap & QuantLib::MakeVanillaSwap::withFixedLegTenor (const Period & t)
Definition at line 194 of file makevanillaswap.cpp.
References fixedTenor_, and anonymous_namespace{quantlibbenchmark.cpp}::t.
Referenced by QuantLib::SwapRateHelper::initializeDates(), anonymous_namespace{piecewiseyieldcurve.cpp}::testCurveConsistency(), PiecewiseYieldCurveTest::testJpyLibor(), PiecewiseYieldCurveTest::testLiborFixing(), QuantLib::SwapIndex::underlyingSwap(), and QuantLib::MakeCapFloor::withTenor().
{
        fixedTenor_ = t;
        return *this;
    }
MakeVanillaSwap & QuantLib::MakeVanillaSwap::withFixedLegTerminationDateConvention (BusinessDayConvention bdc)
Definition at line 212 of file makevanillaswap.cpp.
References fixedTerminationDateConvention_.
Referenced by QuantLib::SwapRateHelper::initializeDates(), QuantLib::MakeSwaption::operator boost::shared_ptr< Swaption >(), anonymous_namespace{piecewiseyieldcurve.cpp}::testCurveConsistency(), PiecewiseYieldCurveTest::testJpyLibor(), PiecewiseYieldCurveTest::testLiborFixing(), QuantLib::SwapIndex::underlyingSwap(), and QuantLib::MakeCapFloor::withTerminationDateConvention().
{
        fixedTerminationDateConvention_ = bdc;
        return *this;
    }
MakeVanillaSwap & QuantLib::MakeVanillaSwap::withFloatingLegCalendar (const Calendar & cal)
Definition at line 250 of file makevanillaswap.cpp.
References floatCalendar_.
Referenced by QuantLib::SwapRateHelper::initializeDates(), PiecewiseYieldCurveTest::testJpyLibor(), and QuantLib::MakeCapFloor::withCalendar().
{
        floatCalendar_ = cal;
        return *this;
    }
MakeVanillaSwap & QuantLib::MakeVanillaSwap::withFloatingLegConvention (BusinessDayConvention bdc)
Definition at line 256 of file makevanillaswap.cpp.
References floatConvention_.
Referenced by QuantLib::MakeCapFloor::withConvention().
{
        floatConvention_ = bdc;
        return *this;
    }
MakeVanillaSwap & QuantLib::MakeVanillaSwap::withFloatingLegDayCount (const DayCounter & dc)
Definition at line 290 of file makevanillaswap.cpp.
References floatDayCount_.
Referenced by QuantLib::MakeCapFloor::withDayCount().
{
        floatDayCount_ = dc;
        return *this;
    }
MakeVanillaSwap & QuantLib::MakeVanillaSwap::withFloatingLegEndOfMonth (bool flag = true)
Definition at line 272 of file makevanillaswap.cpp.
References floatEndOfMonth_.
Referenced by QuantLib::MakeCapFloor::withEndOfMonth().
{
        floatEndOfMonth_ = flag;
        return *this;
    }
MakeVanillaSwap & QuantLib::MakeVanillaSwap::withFloatingLegFirstDate (const Date & d)
Definition at line 278 of file makevanillaswap.cpp.
References anonymous_namespace{marketmodel.cpp}::d, and floatFirstDate_.
Referenced by QuantLib::MakeCapFloor::withFirstDate().
{
        floatFirstDate_ = d;
        return *this;
    }
MakeVanillaSwap & QuantLib::MakeVanillaSwap::withFloatingLegNextToLastDate (const Date & d)
Definition at line 284 of file makevanillaswap.cpp.
References anonymous_namespace{marketmodel.cpp}::d, and floatNextToLastDate_.
Referenced by QuantLib::MakeCapFloor::withNextToLastDate().
{
        floatNextToLastDate_ = d;
        return *this;
    }
MakeVanillaSwap & QuantLib::MakeVanillaSwap::withFloatingLegRule (DateGeneration::Rule r)
Definition at line 267 of file makevanillaswap.cpp.
References floatRule_.
Referenced by QuantLib::MakeCapFloor::withRule().
{
        floatRule_ = r;
        return *this;
    }
MakeVanillaSwap & QuantLib::MakeVanillaSwap::withFloatingLegSpread (Spread sp)
Definition at line 295 of file makevanillaswap.cpp.
References floatSpread_.
Referenced by SwaptionTest::testImpliedVolatility(), SwaptionTest::testSpreadDependency(), SwaptionTest::testSpreadTreatment(), SwaptionTest::testStrikeDependency(), and SwaptionTest::testVega().
{
        floatSpread_ = sp;
        return *this;
    }
MakeVanillaSwap & QuantLib::MakeVanillaSwap::withFloatingLegTenor (const Period & t)
Definition at line 244 of file makevanillaswap.cpp.
References floatTenor_, and anonymous_namespace{quantlibbenchmark.cpp}::t.
Referenced by QuantLib::MakeCapFloor::withTenor().
{
        floatTenor_ = t;
        return *this;
    }
MakeVanillaSwap & QuantLib::MakeVanillaSwap::withFloatingLegTerminationDateConvention (BusinessDayConvention bdc)
Definition at line 262 of file makevanillaswap.cpp.
References floatTerminationDateConvention_.
Referenced by QuantLib::MakeCapFloor::withTerminationDateConvention().
{
        floatTerminationDateConvention_ = bdc;
        return *this;
    }
MakeVanillaSwap & QuantLib::MakeVanillaSwap::withNominal (Real n)
Definition at line 156 of file makevanillaswap.cpp.
References nominal_.
Referenced by QuantLib::MakeCapFloor::withNominal().
{
        nominal_ = n;
        return *this;
    }
MakeVanillaSwap & QuantLib::MakeVanillaSwap::withPricingEngine (const boost::shared_ptr< PricingEngine > & engine)
Definition at line 188 of file makevanillaswap.cpp.
References engine_.
{
        engine_ = engine;
        return *this;
    }
MakeVanillaSwap & QuantLib::MakeVanillaSwap::withRule (DateGeneration::Rule r)
Definition at line 174 of file makevanillaswap.cpp.
References fixedRule_, and floatRule_.
{
        fixedRule_ = r;
        floatRule_ = r;
        return *this;
    }
MakeVanillaSwap & QuantLib::MakeVanillaSwap::withTerminationDate (const Date & terminationDate)
Definition at line 168 of file makevanillaswap.cpp.
References swapTenor_, and terminationDate_.
{
        terminationDate_ = terminationDate;
        swapTenor_ = Period();
        return *this;
    }
MakeVanillaSwap & QuantLib::MakeVanillaSwap::withType (VanillaSwap::Type type)
Definition at line 151 of file makevanillaswap.cpp.
References anonymous_namespace{swaption.cpp}::type, and type_.
Referenced by SwaptionTest::testImpliedVolatility(), SwaptionTest::testSpreadDependency(), SwaptionTest::testSpreadTreatment(), SwaptionTest::testStrikeDependency(), and SwaptionTest::testVega().
{
        type_ = type;
        return *this;
    }
Member Data Documentation
Date QuantLib::MakeVanillaSwap::effectiveDate_ [private]
Definition at line 89 of file makevanillaswap.hpp.
Referenced by withEffectiveDate().
boost::shared_ptr<PricingEngine> QuantLib::MakeVanillaSwap::engine_ [private]
Definition at line 104 of file makevanillaswap.hpp.
Referenced by withDiscountingTermStructure(), and withPricingEngine().
Calendar QuantLib::MakeVanillaSwap::fixedCalendar_ [private]
Definition at line 90 of file makevanillaswap.hpp.
Referenced by withFixedLegCalendar().
BusinessDayConvention QuantLib::MakeVanillaSwap::fixedConvention_ [private]
Definition at line 95 of file makevanillaswap.hpp.
Referenced by withFixedLegConvention().
DayCounter QuantLib::MakeVanillaSwap::fixedDayCount_ [private]
Definition at line 102 of file makevanillaswap.hpp.
Referenced by withFixedLegDayCount().
bool QuantLib::MakeVanillaSwap::fixedEndOfMonth_ [private]
Definition at line 98 of file makevanillaswap.hpp.
Referenced by withFixedLegEndOfMonth().
Date QuantLib::MakeVanillaSwap::fixedFirstDate_ [private]
Definition at line 99 of file makevanillaswap.hpp.
Referenced by withFixedLegFirstDate().
Date QuantLib::MakeVanillaSwap::fixedNextToLastDate_ [private]
Definition at line 99 of file makevanillaswap.hpp.
Referenced by withFixedLegNextToLastDate().
Rate QuantLib::MakeVanillaSwap::fixedRate_ [private]
Definition at line 86 of file makevanillaswap.hpp.
DateGeneration::Rule QuantLib::MakeVanillaSwap::fixedRule_ [private]
Definition at line 97 of file makevanillaswap.hpp.
Referenced by withFixedLegRule(), and withRule().
Period QuantLib::MakeVanillaSwap::fixedTenor_ [private]
Definition at line 94 of file makevanillaswap.hpp.
Referenced by withFixedLegTenor().
BusinessDayConvention QuantLib::MakeVanillaSwap::fixedTerminationDateConvention_ [private]
Definition at line 95 of file makevanillaswap.hpp.
Referenced by withFixedLegTerminationDateConvention().
Calendar QuantLib::MakeVanillaSwap::floatCalendar_ [private]
Definition at line 90 of file makevanillaswap.hpp.
Referenced by withFloatingLegCalendar().
BusinessDayConvention QuantLib::MakeVanillaSwap::floatConvention_ [private]
Definition at line 96 of file makevanillaswap.hpp.
Referenced by withFloatingLegConvention().
DayCounter QuantLib::MakeVanillaSwap::floatDayCount_ [private]
Definition at line 102 of file makevanillaswap.hpp.
Referenced by withFloatingLegDayCount().
bool QuantLib::MakeVanillaSwap::floatEndOfMonth_ [private]
Definition at line 98 of file makevanillaswap.hpp.
Referenced by withFloatingLegEndOfMonth().
Date QuantLib::MakeVanillaSwap::floatFirstDate_ [private]
Definition at line 100 of file makevanillaswap.hpp.
Referenced by withFloatingLegFirstDate().
Date QuantLib::MakeVanillaSwap::floatNextToLastDate_ [private]
Definition at line 100 of file makevanillaswap.hpp.
Referenced by withFloatingLegNextToLastDate().
DateGeneration::Rule QuantLib::MakeVanillaSwap::floatRule_ [private]
Definition at line 97 of file makevanillaswap.hpp.
Referenced by withFloatingLegRule(), and withRule().
Spread QuantLib::MakeVanillaSwap::floatSpread_ [private]
Definition at line 101 of file makevanillaswap.hpp.
Referenced by withFloatingLegSpread().
Period QuantLib::MakeVanillaSwap::floatTenor_ [private]
Definition at line 94 of file makevanillaswap.hpp.
Referenced by withFloatingLegTenor().
BusinessDayConvention QuantLib::MakeVanillaSwap::floatTerminationDateConvention_ [private]
Definition at line 96 of file makevanillaswap.hpp.
Referenced by withFloatingLegTerminationDateConvention().
Period QuantLib::MakeVanillaSwap::forwardStart_ [private]
Definition at line 87 of file makevanillaswap.hpp.
boost::shared_ptr<IborIndex> QuantLib::MakeVanillaSwap::iborIndex_ [private]
Definition at line 85 of file makevanillaswap.hpp.
Real QuantLib::MakeVanillaSwap::nominal_ [private]
Definition at line 93 of file makevanillaswap.hpp.
Referenced by withNominal().
Period QuantLib::MakeVanillaSwap::swapTenor_ [private]
Definition at line 84 of file makevanillaswap.hpp.
Referenced by withTerminationDate().
Date QuantLib::MakeVanillaSwap::terminationDate_ [private]
Definition at line 89 of file makevanillaswap.hpp.
Referenced by withTerminationDate().
VanillaSwap::Type QuantLib::MakeVanillaSwap::type_ [private]
Definition at line 92 of file makevanillaswap.hpp.
Referenced by receiveFixed(), and withType().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/makevanillaswap.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/makevanillaswap.cpp