QuantLib: QuantLib::ExerciseStrategy< State > Class Template Reference
QuantLib::ExerciseStrategy< State > Class Template Reference
#include <exercisestrategy.hpp>
Public Member Functions
virtual ~ExerciseStrategy ()
virtual std::vector< Time > exerciseTimes () const =0
virtual std::vector< Time > relevantTimes () const =0
virtual void reset ()=0
virtual bool exercise (const State &currentState) const =0
virtual void nextStep (const State &currentState)=0
virtual std::auto_ptr
< ExerciseStrategy< State > > clone () const =0
Detailed Description
template<class State>
class QuantLib::ExerciseStrategy< State >
Definition at line 31 of file exercisestrategy.hpp.
Constructor & Destructor Documentation
template<class State> virtual QuantLib::ExerciseStrategy< State >::~ExerciseStrategy () [inline, virtual]
Definition at line 33 of file exercisestrategy.hpp.
{}
Member Function Documentation
template<class State> virtual std::auto_ptr<ExerciseStrategy<State> > QuantLib::ExerciseStrategy< State >::clone () const [pure virtual]
Implemented in QuantLib::LongstaffSchwartzExerciseStrategy, QuantLib::ParametricExerciseAdapter, and QuantLib::SwapRateTrigger.
template<class State> virtual bool QuantLib::ExerciseStrategy< State >::exercise (const State & currentState) const [pure virtual]
Implemented in QuantLib::LongstaffSchwartzExerciseStrategy, QuantLib::ParametricExerciseAdapter, and QuantLib::SwapRateTrigger.
Referenced by QuantLib::CallSpecifiedMultiProduct::nextTimeStep(), QuantLib::CallSpecifiedPathwiseMultiProduct::nextTimeStep(), and QuantLib::UpperBoundEngine::singlePathValue().
template<class State> virtual std::vector<Time> QuantLib::ExerciseStrategy< State >::exerciseTimes () const [pure virtual]
Implemented in QuantLib::LongstaffSchwartzExerciseStrategy, QuantLib::ParametricExerciseAdapter, and QuantLib::SwapRateTrigger.
Referenced by QuantLib::CallSpecifiedMultiProduct::CallSpecifiedMultiProduct(), QuantLib::CallSpecifiedPathwiseMultiProduct::CallSpecifiedPathwiseMultiProduct(), and QuantLib::UpperBoundEngine::UpperBoundEngine().
template<class State> virtual void QuantLib::ExerciseStrategy< State >::nextStep (const State & currentState) [pure virtual]
Implemented in QuantLib::LongstaffSchwartzExerciseStrategy, QuantLib::ParametricExerciseAdapter, and QuantLib::SwapRateTrigger.
Referenced by QuantLib::CallSpecifiedMultiProduct::nextTimeStep(), and QuantLib::CallSpecifiedPathwiseMultiProduct::nextTimeStep().
template<class State> virtual std::vector<Time> QuantLib::ExerciseStrategy< State >::relevantTimes () const [pure virtual]
Implemented in QuantLib::LongstaffSchwartzExerciseStrategy, QuantLib::ParametricExerciseAdapter, and QuantLib::SwapRateTrigger.
Referenced by QuantLib::CallSpecifiedMultiProduct::CallSpecifiedMultiProduct(), and QuantLib::CallSpecifiedPathwiseMultiProduct::CallSpecifiedPathwiseMultiProduct().
template<class State> virtual void QuantLib::ExerciseStrategy< State >::reset () [pure virtual]
Implemented in QuantLib::LongstaffSchwartzExerciseStrategy, QuantLib::ParametricExerciseAdapter, and QuantLib::SwapRateTrigger.
Referenced by QuantLib::CallSpecifiedMultiProduct::reset(), and QuantLib::CallSpecifiedPathwiseMultiProduct::reset().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/montecarlo/exercisestrategy.hpp