QuantLib: QuantLib::SmileSection Class Reference
QuantLib::SmileSection Class Reference
interest rate volatility smile section
#include <smilesection.hpp>
Public Member Functions
SmileSection (const Date &d, const DayCounter &dc=DayCounter(), const Date &referenceDate=Date())
SmileSection (Time exerciseTime, const DayCounter &dc=DayCounter())
SmileSection ()
virtual ~SmileSection ()
virtual void update ()
virtual Real minStrike () const =0
virtual Real maxStrike () const =0
Real variance (Rate strike) const
Volatility volatility (Rate strike) const
virtual Real atmLevel () const =0
const Date & exerciseDate () const
const Date & referenceDate () const
Time exerciseTime () const
const DayCounter & dayCounter () const
Protected Member Functions
virtual void initializeExerciseTime () const
virtual Real varianceImpl (Rate strike) const
virtual Volatility volatilityImpl (Rate strike) const =0
Private Attributes
bool isFloating_
Date referenceDate_
Date exerciseDate_
DayCounter dc_
Time exerciseTime_
Detailed Description
interest rate volatility smile section
This abstract class provides volatility smile section interface
Definition at line 35 of file smilesection.hpp.
Constructor & Destructor Documentation
QuantLib::SmileSection::SmileSection (const Date & d, const DayCounter & dc = DayCounter(), const Date & referenceDate = Date())
Definition at line 40 of file smilesection.cpp.
References QuantLib::Settings::evaluationDate(), initializeExerciseTime(), QuantLib::Singleton< Settings >::instance(), isFloating_, referenceDate(), referenceDate_, and QuantLib::Observer::registerWith().
    : exerciseDate_(d), dc_(dc) {
        isFloating_ = referenceDate==Date();
        if (isFloating_) {
            registerWith(Settings::instance().evaluationDate());
            referenceDate_ = Settings::instance().evaluationDate();
        } else
            referenceDate_ = referenceDate;
        initializeExerciseTime();
    }
QuantLib::SmileSection::SmileSection (Time exerciseTime, const DayCounter & dc = DayCounter())
Definition at line 53 of file smilesection.cpp.
References exerciseTime_, and QL_REQUIRE.
    : isFloating_(false), referenceDate_(Date()),
      dc_(dc), exerciseTime_(exerciseTime) {
        QL_REQUIRE(exerciseTime_>=0.0,
                   "expiry time must be positive: " <<
                   exerciseTime_ << " not allowed");
    }
QuantLib::SmileSection::SmileSection () [inline]
Definition at line 43 of file smilesection.hpp.
{}
virtual QuantLib::SmileSection::~SmileSection () [inline, virtual]
Definition at line 45 of file smilesection.hpp.
{}
Member Function Documentation
virtual Real QuantLib::SmileSection::atmLevel () const [pure virtual]
Implemented in QuantLib::SabrInterpolatedSmileSection, QuantLib::InterpolatedSmileSection< Interpolator >, QuantLib::FlatSmileSection, QuantLib::SabrSmileSection, and QuantLib::SpreadedSmileSection.
const DayCounter& QuantLib::SmileSection::dayCounter () const [inline]
Reimplemented in QuantLib::SpreadedSmileSection.
Definition at line 56 of file smilesection.hpp.
References dc_.
{ return dc_; }
const Date& QuantLib::SmileSection::exerciseDate () const [inline]
Reimplemented in QuantLib::SpreadedSmileSection.
Definition at line 53 of file smilesection.hpp.
References exerciseDate_.
{ return exerciseDate_; }
Time QuantLib::SmileSection::exerciseTime () const [inline]
Reimplemented in QuantLib::SpreadedSmileSection.
Definition at line 55 of file smilesection.hpp.
References exerciseTime_.
Referenced by QuantLib::SabrInterpolatedSmileSection::createInterpolation(), QuantLib::SabrSmileSection::varianceImpl(), varianceImpl(), QuantLib::SabrInterpolatedSmileSection::varianceImpl(), and QuantLib::SabrSmileSection::volatilityImpl().
{ return exerciseTime_; }
void QuantLib::SmileSection::initializeExerciseTime () const [protected, virtual]
Definition at line 32 of file smilesection.cpp.
References dc_, exerciseDate_, exerciseTime_, QL_REQUIRE, referenceDate_, and QuantLib::DayCounter::yearFraction().
Referenced by SmileSection(), and update().
{
        QL_REQUIRE(exerciseDate_>=referenceDate_,
                   "expiry date (" << exerciseDate_ <<
                   ") must be greater than reference date (" <<
                   referenceDate_ << ")");
        exerciseTime_ = dc_.yearFraction(referenceDate_, exerciseDate_);
    }
virtual Real QuantLib::SmileSection::maxStrike () const [pure virtual]
Implemented in QuantLib::SabrInterpolatedSmileSection, QuantLib::InterpolatedSmileSection< Interpolator >, QuantLib::FlatSmileSection, QuantLib::SabrSmileSection, and QuantLib::SpreadedSmileSection.
virtual Real QuantLib::SmileSection::minStrike () const [pure virtual]
Implemented in QuantLib::SabrInterpolatedSmileSection, QuantLib::InterpolatedSmileSection< Interpolator >, QuantLib::FlatSmileSection, QuantLib::SabrSmileSection, and QuantLib::SpreadedSmileSection.
const Date & QuantLib::SmileSection::referenceDate () const [inline]
Definition at line 80 of file smilesection.hpp.
References QL_REQUIRE, and referenceDate_.
Referenced by SmileSection().
{
        QL_REQUIRE(referenceDate_!=Date(),
                   "referenceDate not available for this instance");
        return referenceDate_;
    }
void QuantLib::SmileSection::update () [virtual]
This method must be implemented in derived classes. An instance of Observer does not call this method directly: instead, it will be called by the observables the instance registered with when they need to notify any changes.
Implements QuantLib::Observer.
Reimplemented in QuantLib::SabrInterpolatedSmileSection, QuantLib::InterpolatedSmileSection< Interpolator >, and QuantLib::SpreadedSmileSection.
Definition at line 25 of file smilesection.cpp.
References QuantLib::Settings::evaluationDate(), initializeExerciseTime(), QuantLib::Singleton< Settings >::instance(), isFloating_, and referenceDate_.
Referenced by QuantLib::InterpolatedSmileSection< Interpolator >::update().
{
        if (isFloating_) {
            referenceDate_ = Settings::instance().evaluationDate();
            initializeExerciseTime();
        }
    }
Real QuantLib::SmileSection::variance (Rate strike) const [inline]
Definition at line 72 of file smilesection.hpp.
References varianceImpl().
{
        return varianceImpl(strike);
    }
Real QuantLib::SmileSection::varianceImpl (Rate strike) const [inline, protected, virtual]
Reimplemented in QuantLib::SabrInterpolatedSmileSection, QuantLib::InterpolatedSmileSection< Interpolator >, and QuantLib::SabrSmileSection.
Definition at line 86 of file smilesection.hpp.
References exerciseTime(), anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and volatilityImpl().
Referenced by variance().
{
        Volatility v = volatilityImpl(strike);
        return v*v*exerciseTime();
    }
Volatility QuantLib::SmileSection::volatility (Rate strike) const [inline]
Definition at line 76 of file smilesection.hpp.
References volatilityImpl().
{
        return volatilityImpl(strike);
    }
virtual Volatility QuantLib::SmileSection::volatilityImpl (Rate strike) const [protected, pure virtual]
Implemented in QuantLib::SabrInterpolatedSmileSection, QuantLib::InterpolatedSmileSection< Interpolator >, QuantLib::SpreadedSmileSection, QuantLib::FlatSmileSection, and QuantLib::SabrSmileSection.
Referenced by varianceImpl(), and volatility().
Member Data Documentation
DayCounter QuantLib::SmileSection::dc_ [private]
Definition at line 65 of file smilesection.hpp.
Referenced by dayCounter(), and initializeExerciseTime().
Date QuantLib::SmileSection::exerciseDate_ [private]
Definition at line 64 of file smilesection.hpp.
Referenced by exerciseDate(), and initializeExerciseTime().
Time QuantLib::SmileSection::exerciseTime_ [mutable, private]
Definition at line 66 of file smilesection.hpp.
Referenced by exerciseTime(), initializeExerciseTime(), and SmileSection().
bool QuantLib::SmileSection::isFloating_ [private]
Definition at line 62 of file smilesection.hpp.
Referenced by SmileSection(), and update().
Date QuantLib::SmileSection::referenceDate_ [mutable, private]
Definition at line 63 of file smilesection.hpp.
Referenced by initializeExerciseTime(), referenceDate(), SmileSection(), and update().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/smilesection.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/smilesection.cpp