QuantLib: QuantLib::SparseILUPreconditioner Class Reference
QuantLib::SparseILUPreconditioner Class Reference
#include <sparseilupreconditioner.hpp>
Public Member Functions
SparseILUPreconditioner (const SparseMatrix &A, Integer lfil=1)
const SparseMatrix & L () const
const SparseMatrix & U () const
Disposable< Array > apply (const Array &b) const
Private Member Functions
Disposable< Array > forwardSolve (const Array &b) const
Disposable< Array > backwardSolve (const Array &y) const
Private Attributes
SparseMatrix L_
SparseMatrix U_
std::vector< Size > lBands_
std::vector< Size > uBands_
Detailed Description
References: Saad, Yousef. 1996, Iterative methods for sparse linear systems, http://www-users.cs.umn.edu/~saad/books.html
Definition at line 40 of file sparseilupreconditioner.hpp.
Constructor & Destructor Documentation
QuantLib::SparseILUPreconditioner::SparseILUPreconditioner (const SparseMatrix & A, Integer lfil = 1)
Definition at line 33 of file sparseilupreconditioner.cpp.
References L_, lBands_, QL_EPSILON, QL_REQUIRE, QuantLib::Array::size(), U_, and uBands_.
    : L_(A.size1(),A.size2()),
      U_(A.size1(),A.size2()) {
        QL_REQUIRE(A.size1() == A.size2(),
                   "sparse ILU preconditioner works only with square matrices");
        for (SparseMatrix::size_type i=0; i < L_.size1(); ++i)
            L_(i,i) = 1.0;
        const Integer n = A.size1();
        std::set<Integer> lBandSet, uBandSet;
        compressed_matrix<Integer> levs(n,n);
        Integer lfilp = lfil + 1;
        for (Integer ii=0; ii<n; ++ii) {
            Array w(n);
            for(Integer k=0; k<n; ++k) {
                w[k] = A(ii,k);
            }
            std::vector<Integer> levii(n, 0);
            for (Integer i=0; i<n; ++i) {
                if(   w[i] > QL_EPSILON
                      || w[i] < -1.0*QL_EPSILON) levii[i] = 1;
            }
            Integer jj = -1;
            while (jj < ii) {
                for (Integer k=jj+1; k<n; ++k) {
                    if(levii[k]) {
                        jj = k;
                        break;
                    }
                }
                if (jj >= ii) {
                    break;
                }
                Integer jlev = levii[jj];
                if (jlev <= lfilp) {
                    std::vector<Integer> nonZeros;
                    std::vector<Real> nonZeroEntries;
                    nonZeros.reserve(uBandSet.size()+1);
                    nonZeroEntries.reserve(uBandSet.size()+1);
                    const Real entry = U_(jj,jj);
                    if(entry > QL_EPSILON || entry < -1.0*QL_EPSILON) {
                        nonZeros.push_back(jj);
                        nonZeroEntries.push_back(entry);
                    }
                    std::set<Integer>::const_iterator iter=uBandSet.begin();
                    std::set<Integer>::const_iterator end =uBandSet.end();
                    for (; iter != end; ++iter) {
                        const Real entry = U_(jj,jj+*iter);
                        if(entry > QL_EPSILON || entry < -1.0*QL_EPSILON) {
                            nonZeros.push_back(jj+*iter);
                            nonZeroEntries.push_back(entry);
                        }
                    }
                    Real fact = w[jj];
                    if(!nonZeroEntries.empty()) {
                        fact /= nonZeroEntries[0];
                    }
                    for (Size k=0; k<nonZeros.size(); ++k) {
                        const Integer j = nonZeros[k] ;
                        const Integer temp = levs(jj,j) + jlev ;
                        if (levii[j] == 0) {
                            if (temp <= lfilp) {
                                w[j] =  - fact*nonZeroEntries[k];
                                levii[j] = temp;
                            }
                        }
                        else {
                            w[j] -= fact*nonZeroEntries[k];
                            levii[j] = std::min(levii[j],temp);
                        }
                    }
                    w[jj] = fact;
                }
            }
            std::vector<Integer> wNonZeros;
            std::vector<Real> wNonZeroEntries;
            wNonZeros.reserve(w.size());
            wNonZeroEntries.reserve(w.size());
            for (Size i=0; i<w.size(); ++i) {
                const Real entry = w[i];
                if(entry > QL_EPSILON || entry < -1.0*QL_EPSILON) {
                    wNonZeros.push_back(i);
                    wNonZeroEntries.push_back(entry);
                }
            }
            std::vector<Integer> leviiNonZeroEntries;
            leviiNonZeroEntries.reserve(levii.size());
            for (Size i=0; i<levii.size(); ++i) {
                const Integer entry = levii[i];
                if(entry > QL_EPSILON || entry < -1.0*QL_EPSILON) {
                    leviiNonZeroEntries.push_back(entry);
                }
            }
            for (Size k=0; k<wNonZeros.size(); ++k) {
                Integer j = wNonZeros[k];
                if (j < ii) {
                    L_(ii,j) = wNonZeroEntries[k];
                    lBandSet.insert(ii-j);
                }
                else {
                    U_(ii,j) = wNonZeroEntries[k];
                    levs(ii,j) = leviiNonZeroEntries[k];
                    if(j-ii > 0) {
                        uBandSet.insert(j-ii);
                    }
                }
            }
        }
        lBands_.resize(lBandSet.size());
        uBands_.resize(uBandSet.size());
        std::copy(lBandSet.begin(), lBandSet.end(), lBands_.begin());
        std::copy(uBandSet.begin(), uBandSet.end(), uBands_.begin());
    }
Member Function Documentation
Disposable< Array > QuantLib::SparseILUPreconditioner::apply (const Array & b) const
Definition at line 161 of file sparseilupreconditioner.cpp.
References backwardSolve(), and forwardSolve().
Referenced by FdmLinearOpTest::testBiCGstab().
{
        return backwardSolve(forwardSolve(b));
    }
Disposable< Array > QuantLib::SparseILUPreconditioner::backwardSolve (const Array & y) const [private]
Definition at line 180 of file sparseilupreconditioner.cpp.
References QuantLib::Array::size(), U_, and uBands_.
Referenced by apply().
{
        Size n = y.size();
        Array x(n, 0.0);
        x[n-1] = y[n-1]/U_(n-1,n-1);
        for (Integer i=n-2; i>=0; --i) {
            x[i] = y[i]/U_(i,i);
            for (Size j=0; j<uBands_.size() && i+uBands_[j] <= n-1; ++j) {
                x[i] -= U_(i,i+uBands_[j])*x[i+uBands_[j]]/U_(i,i);
            }
        }
        return x;
    }
Disposable< Array > QuantLib::SparseILUPreconditioner::forwardSolve (const Array & b) const [private]
Definition at line 165 of file sparseilupreconditioner.cpp.
References L_, lBands_, and QuantLib::Array::size().
Referenced by apply().
{
        Size n = b.size();
        Array y(n, 0.0);
        y[0]=b[0]/L_(0,0);
        for (Size i=1; i<=n-1; ++i) {
            y[i] = b[i]/L_(i,i);
            for (Integer j=lBands_.size()-1;
                 j>=0 && i-lBands_[j] <= i-1; --j) {
                y[i]-=L_(i,i-lBands_[j])*y[i-lBands_[j]]/L_(i,i);
            }
        }
        return y;
    }
const SparseMatrix & QuantLib::SparseILUPreconditioner::L () const
Definition at line 153 of file sparseilupreconditioner.cpp.
References L_.
{
        return L_;
    }
const SparseMatrix & QuantLib::SparseILUPreconditioner::U () const
Definition at line 157 of file sparseilupreconditioner.cpp.
References U_.
{
        return U_;
    }
Member Data Documentation
SparseMatrix QuantLib::SparseILUPreconditioner::L_ [private]
Definition at line 50 of file sparseilupreconditioner.hpp.
Referenced by forwardSolve(), L(), and SparseILUPreconditioner().
std::vector<Size> QuantLib::SparseILUPreconditioner::lBands_ [private]
Definition at line 51 of file sparseilupreconditioner.hpp.
Referenced by forwardSolve(), and SparseILUPreconditioner().
SparseMatrix QuantLib::SparseILUPreconditioner::U_ [private]
Definition at line 50 of file sparseilupreconditioner.hpp.
Referenced by backwardSolve(), SparseILUPreconditioner(), and U().
std::vector<Size> QuantLib::SparseILUPreconditioner::uBands_ [private]
Definition at line 51 of file sparseilupreconditioner.hpp.
Referenced by backwardSolve(), and SparseILUPreconditioner().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/matrixutilities/sparseilupreconditioner.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/math/matrixutilities/sparseilupreconditioner.cpp