QuantLib: TermStructureTest Class Reference
TermStructureTest Class Reference
#include <termstructures.hpp>
Static Public Member Functions
static void testReferenceChange ()
static void testImplied ()
static void testImpliedObs ()
static void testFSpreaded ()
static void testFSpreadedObs ()
static void testZSpreaded ()
static void testZSpreadedObs ()
static
boost::unit_test_framework::test_suite * suite ()
Detailed Description
Definition at line 28 of file termstructures.hpp.
Member Function Documentation
test_suite * TermStructureTest::suite () [static]
Definition at line 302 of file termstructures.cpp.
References QUANTLIB_TEST_CASE, testFSpreaded(), testFSpreadedObs(), testImplied(), testImpliedObs(), testReferenceChange(), testZSpreaded(), and testZSpreadedObs().
Referenced by init_unit_test_suite().
{
    test_suite* suite = BOOST_TEST_SUITE("Term structure tests");
    suite->add(QUANTLIB_TEST_CASE(&TermStructureTest::testReferenceChange));
    suite->add(QUANTLIB_TEST_CASE(&TermStructureTest::testImplied));
    suite->add(QUANTLIB_TEST_CASE(&TermStructureTest::testImpliedObs));
    suite->add(QUANTLIB_TEST_CASE(&TermStructureTest::testFSpreaded));
    suite->add(QUANTLIB_TEST_CASE(&TermStructureTest::testFSpreadedObs));
    suite->add(QUANTLIB_TEST_CASE(&TermStructureTest::testZSpreaded));
    suite->add(QUANTLIB_TEST_CASE(&TermStructureTest::testZSpreadedObs));
    return suite;
}
void TermStructureTest::testFSpreaded () [static]
Definition at line 201 of file termstructures.cpp.
References QuantLib::Continuous, QuantLib::NoFrequency, QuantLib::io::rate(), anonymous_namespace{gaussianquadratures.cpp}::tolerance, and QuantLib::Years.
Referenced by suite().
{
    BOOST_MESSAGE("Testing consistency of forward-spreaded term structure...");
    CommonVars vars;
    Real tolerance = 1.0e-10;
    boost::shared_ptr<Quote> me(new SimpleQuote(0.01));
    Handle<Quote> mh(me);
    boost::shared_ptr<YieldTermStructure> spreaded(
        new ForwardSpreadedTermStructure(
            Handle<YieldTermStructure>(vars.termStructure),mh));
    Date testDate = vars.termStructure->referenceDate() + 5*Years;
    DayCounter tsdc  = vars.termStructure->dayCounter();
    DayCounter sprdc = spreaded->dayCounter();
    Rate forward = vars.termStructure->forwardRate(testDate, testDate, tsdc,
                                                   Continuous, NoFrequency);
    Rate spreadedForward = spreaded->forwardRate(testDate, testDate, sprdc,
                                                 Continuous, NoFrequency);
    if (std::fabs(forward - (spreadedForward-me->value())) > tolerance)
        BOOST_ERROR(
            "unable to reproduce forward from spreaded curve\n"
            << std::setprecision(10)
            << "    calculated: "
            << io::rate(spreadedForward-me->value()) << "\n"
            << "    expected:   " << io::rate(forward));
}
void TermStructureTest::testFSpreadedObs () [static]
Definition at line 229 of file termstructures.cpp.
References QuantLib::Flag::isUp(), QuantLib::RelinkableHandle< T >::linkTo(), QuantLib::Flag::lower(), and QuantLib::Observer::registerWith().
Referenced by suite().
{
    BOOST_MESSAGE("Testing observability of forward-spreaded "
                  "term structure...");
    CommonVars vars;
    boost::shared_ptr<SimpleQuote> me(new SimpleQuote(0.01));
    Handle<Quote> mh(me);
    RelinkableHandle<YieldTermStructure> h; //(vars.dummyTermStructure);
    boost::shared_ptr<YieldTermStructure> spreaded(
        new ForwardSpreadedTermStructure(h,mh));
    Flag flag;
    flag.registerWith(spreaded);
    h.linkTo(vars.termStructure);
    if (!flag.isUp())
        BOOST_ERROR("Observer was not notified of term structure change");
    flag.lower();
    me->setValue(0.005);
    if (!flag.isUp())
        BOOST_ERROR("Observer was not notified of spread change");
}
void TermStructureTest::testImplied () [static]
Definition at line 155 of file termstructures.cpp.
References QuantLib::Date::advance(), QuantLib::Days, QuantLib::Settings::evaluationDate(), QuantLib::Singleton< Settings >::instance(), QL_FIXED, anonymous_namespace{gaussianquadratures.cpp}::tolerance, and QuantLib::Years.
Referenced by suite().
{
    BOOST_MESSAGE("Testing consistency of implied term structure...");
    CommonVars vars;
    Real tolerance = 1.0e-10;
    Date today = Settings::instance().evaluationDate();
    Date newToday = today + 3*Years;
    Date newSettlement = vars.calendar.advance(newToday,
                                               vars.settlementDays,Days);
    Date testDate = newSettlement + 5*Years;
    boost::shared_ptr<YieldTermStructure> implied(
        new ImpliedTermStructure(Handle<YieldTermStructure>(vars.termStructure),
                                 newSettlement));
    DiscountFactor baseDiscount = vars.termStructure->discount(newSettlement);
    DiscountFactor discount = vars.termStructure->discount(testDate);
    DiscountFactor impliedDiscount = implied->discount(testDate);
    if (std::fabs(discount - baseDiscount*impliedDiscount) > tolerance)
        BOOST_ERROR(
            "unable to reproduce discount from implied curve\n"
            << QL_FIXED << std::setprecision(10)
            << "    calculated: " << baseDiscount*impliedDiscount << "\n"
            << "    expected:   " << discount);
}
void TermStructureTest::testImpliedObs () [static]
Definition at line 181 of file termstructures.cpp.
References QuantLib::Date::advance(), QuantLib::Days, QuantLib::Settings::evaluationDate(), QuantLib::Singleton< Settings >::instance(), QuantLib::Flag::isUp(), QuantLib::RelinkableHandle< T >::linkTo(), QuantLib::Observer::registerWith(), and QuantLib::Years.
Referenced by suite().
{
    BOOST_MESSAGE("Testing observability of implied term structure...");
    CommonVars vars;
    Date today = Settings::instance().evaluationDate();
    Date newToday = today + 3*Years;
    Date newSettlement = vars.calendar.advance(newToday,
                                               vars.settlementDays,Days);
    RelinkableHandle<YieldTermStructure> h;
    boost::shared_ptr<YieldTermStructure> implied(
                                  new ImpliedTermStructure(h, newSettlement));
    Flag flag;
    flag.registerWith(implied);
    h.linkTo(vars.termStructure);
    if (!flag.isUp())
        BOOST_ERROR("Observer was not notified of term structure change");
}
void TermStructureTest::testReferenceChange () [static]
Definition at line 120 of file termstructures.cpp.
References QuantLib::close(), QuantLib::days(), QuantLib::Settings::evaluationDate(), QuantLib::flatRate(), QuantLib::Singleton< Settings >::instance(), and LENGTH.
Referenced by suite().
{
    BOOST_MESSAGE("Testing term structure against evaluation date change...");
    CommonVars vars;
    boost::shared_ptr<SimpleQuote> flatRate (new SimpleQuote);
    Handle<Quote> flatRateHandle(flatRate);
    vars.termStructure = boost::shared_ptr<YieldTermStructure>(
                          new FlatForward(vars.settlementDays, NullCalendar(),
                                          flatRateHandle, Actual360()));
    Date today = Settings::instance().evaluationDate();
    flatRate->setValue(.03);
    Integer days[] = { 10, 30, 60, 120, 360, 720 };
    Size i;
    std::vector<DiscountFactor> expected(LENGTH(days));
    for (i=0; i<LENGTH(days); i++)
        expected[i] = vars.termStructure->discount(today+days[i]);
    Settings::instance().evaluationDate() = today+30;
    std::vector<DiscountFactor> calculated(LENGTH(days));
    for (i=0; i<LENGTH(days); i++)
        calculated[i] = vars.termStructure->discount(today+30+days[i]);
    for (i=0; i<LENGTH(days); i++) {
        if (!close(expected[i],calculated[i]))
            BOOST_ERROR("\n  Discount at " << days[i] << " days:\n"
                        << std::setprecision(12)
                        << "    before date change: " << expected[i] << "\n"
                        << "    after date change:  " << calculated[i]);
    }
}
void TermStructureTest::testZSpreaded () [static]
Definition at line 252 of file termstructures.cpp.
References QuantLib::Continuous, QuantLib::NoFrequency, QuantLib::io::rate(), anonymous_namespace{gaussianquadratures.cpp}::tolerance, and QuantLib::Years.
Referenced by suite().
{
    BOOST_MESSAGE("Testing consistency of zero-spreaded term structure...");
    CommonVars vars;
    Real tolerance = 1.0e-10;
    boost::shared_ptr<Quote> me(new SimpleQuote(0.01));
    Handle<Quote> mh(me);
    boost::shared_ptr<YieldTermStructure> spreaded(
        new ZeroSpreadedTermStructure(
            Handle<YieldTermStructure>(vars.termStructure),mh));
    Date testDate = vars.termStructure->referenceDate() + 5*Years;
    DayCounter rfdc  = vars.termStructure->dayCounter();
    Rate zero = vars.termStructure->zeroRate(testDate, rfdc,
                                             Continuous, NoFrequency);
    Rate spreadedZero = spreaded->zeroRate(testDate, rfdc,
                                           Continuous, NoFrequency);
    if (std::fabs(zero - (spreadedZero-me->value())) > tolerance)
        BOOST_ERROR(
            "unable to reproduce zero yield from spreaded curve\n"
            << std::setprecision(10)
            << "    calculated: " << io::rate(spreadedZero-me->value()) << "\n"
            << "    expected:   " << io::rate(zero));
}
void TermStructureTest::testZSpreadedObs () [static]
Definition at line 278 of file termstructures.cpp.
References QuantLib::Flag::isUp(), QuantLib::RelinkableHandle< T >::linkTo(), QuantLib::Flag::lower(), and QuantLib::Observer::registerWith().
Referenced by suite().
{
    BOOST_MESSAGE("Testing observability of zero-spreaded term structure...");
    CommonVars vars;
    boost::shared_ptr<SimpleQuote> me(new SimpleQuote(0.01));
    Handle<Quote> mh(me);
    RelinkableHandle<YieldTermStructure> h(vars.dummyTermStructure);
    boost::shared_ptr<YieldTermStructure> spreaded(
        new ZeroSpreadedTermStructure(h,mh));
    Flag flag;
    flag.registerWith(spreaded);
    h.linkTo(vars.termStructure);
    if (!flag.isUp())
        BOOST_ERROR("Observer was not notified of term structure change");
    flag.lower();
    me->setValue(0.005);
    if (!flag.isUp())
        BOOST_ERROR("Observer was not notified of spread change");
}
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/termstructures.hpp
/home/deriversatile/QuantLib/QuantLibQt/test-suite/termstructures.cpp