QuantLib: QuantLib::TimeSeries< T, Container > Class Template Reference
QuantLib::TimeSeries< T, Container > Class Template Reference
Container for historical data.
#include <timeseries.hpp>
Classes
struct reverse
struct reverse< container, std::bidirectional_iterator_tag >
Public Types
typedef Date key_type
typedef T value_type
Public Member Functions
TimeSeries ()
template<class DateIterator , class ValueIterator >
TimeSeries (DateIterator dBegin, DateIterator dEnd, ValueIterator vBegin)
template<class ValueIterator >
TimeSeries (const Date &firstDate, ValueIterator begin, ValueIterator end)
Inspectors
Date firstDate () const
returns the first date for which a historical datum exists
Date lastDate () const
returns the last date for which a historical datum exists
Size size () const
returns the number of historical data including null ones
bool empty () const
returns whether the series contains any data
Historical data access
T operator[] (const Date &d) const
returns the (possibly null) datum corresponding to the given date
T & operator[] (const Date &d)
Utilities
const_iterator find (const Date &)
std::vector< Date > dates () const
returns the dates for which historical data exist
std::vector< T > values () const
returns the historical data
Private Types
typedef Container::value_type container_value_type
typedef boost::function1< Date,
const container_value_type & > projection_time
typedef boost::function1< T,
const container_value_type & > projection_value
Static Private Member Functions
static const Date & get_time (const container_value_type &v)
static const T & get_value (const container_value_type &v)
Private Attributes
Container values_
Iterators
typedef Container::const_iterator const_iterator
typedef
const_iterator::iterator_category iterator_category
typedef boost::mpl::if_
< boost::mpl::or_
< boost::is_same
< iterator_category,
std::bidirectional_iterator_tag >
, boost::is_base_of
< std::bidirectional_iterator_tag,
iterator_category >
>, std::bidirectional_iterator_tag,
std::input_iterator_tag >
::type enable_reverse
typedef reverse< Container,
enable_reverse >
::const_reverse_iterator const_reverse_iterator
const_iterator cbegin () const
const_iterator cend () const
const_iterator begin () const
const_iterator end () const
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
Projection iterators
typedef
boost::transform_iterator
< projection_time,
const_iterator > const_time_iterator
typedef
boost::transform_iterator
< projection_value,
const_iterator > const_value_iterator
typedef
boost::transform_iterator
< projection_time,
const_reverse_iterator > const_reverse_time_iterator
typedef
boost::transform_iterator
< projection_value,
const_reverse_iterator > const_reverse_value_iterator
const_value_iterator cbegin_values () const
const_value_iterator cend_values () const
const_reverse_value_iterator crbegin_values () const
const_reverse_value_iterator crend_values () const
const_time_iterator cbegin_time () const
const_time_iterator cend_time () const
const_reverse_time_iterator crbegin_time () const
const_reverse_time_iterator crend_time () const
Detailed Description
template<class T, class Container = std::map<Date, T>>
class QuantLib::TimeSeries< T, Container >
Container for historical data.
This class acts as a generic repository for a set of historical data. Any single datum can be accessed through its date, while sets of consecutive data can be accessed through iterators.
Precondition:
The Container type must satisfy the requirements set by the C++ standard for associative containers.
Definition at line 50 of file timeseries.hpp.
Member Typedef Documentation
template<class T, class Container = std::map<Date, T>> typedef Container::const_iterator QuantLib::TimeSeries< T, Container >::const_iterator
Definition at line 110 of file timeseries.hpp.
template<class T, class Container = std::map<Date, T>> typedef reverse<Container, enable_reverse>::const_reverse_iterator QuantLib::TimeSeries< T, Container >::const_reverse_iterator
Definition at line 158 of file timeseries.hpp.
template<class T, class Container = std::map<Date, T>> typedef boost::transform_iterator<projection_time, const_reverse_iterator> QuantLib::TimeSeries< T, Container >::const_reverse_time_iterator
Definition at line 191 of file timeseries.hpp.
template<class T, class Container = std::map<Date, T>> typedef boost::transform_iterator<projection_value, const_reverse_iterator> QuantLib::TimeSeries< T, Container >::const_reverse_value_iterator
Definition at line 194 of file timeseries.hpp.
template<class T, class Container = std::map<Date, T>> typedef boost::transform_iterator<projection_time, const_iterator> QuantLib::TimeSeries< T, Container >::const_time_iterator
Definition at line 186 of file timeseries.hpp.
template<class T, class Container = std::map<Date, T>> typedef boost::transform_iterator<projection_value, const_iterator> QuantLib::TimeSeries< T, Container >::const_value_iterator
Definition at line 188 of file timeseries.hpp.
template<class T, class Container = std::map<Date, T>> typedef Container::value_type QuantLib::TimeSeries< T, Container >::container_value_type [private]
Definition at line 175 of file timeseries.hpp.
template<class T, class Container = std::map<Date, T>> typedef boost::mpl::if_< boost::mpl::or_ < boost::is_same<iterator_category, std::bidirectional_iterator_tag>, boost::is_base_of<std::bidirectional_iterator_tag, iterator_category> >, std::bidirectional_iterator_tag, std::input_iterator_tag>::type QuantLib::TimeSeries< T, Container >::enable_reverse
Definition at line 154 of file timeseries.hpp.
template<class T, class Container = std::map<Date, T>> typedef const_iterator::iterator_category QuantLib::TimeSeries< T, Container >::iterator_category
Definition at line 111 of file timeseries.hpp.
template<class T, class Container = std::map<Date, T>> typedef Date QuantLib::TimeSeries< T, Container >::key_type
Definition at line 52 of file timeseries.hpp.
template<class T, class Container = std::map<Date, T>> typedef boost::function1<Date, const container_value_type&> QuantLib::TimeSeries< T, Container >::projection_time [private]
Definition at line 177 of file timeseries.hpp.
template<class T, class Container = std::map<Date, T>> typedef boost::function1<T, const container_value_type&> QuantLib::TimeSeries< T, Container >::projection_value [private]
Definition at line 179 of file timeseries.hpp.
template<class T, class Container = std::map<Date, T>> typedef T QuantLib::TimeSeries< T, Container >::value_type
Definition at line 53 of file timeseries.hpp.
Constructor & Destructor Documentation
template<class T, class Container = std::map<Date, T>> QuantLib::TimeSeries< T, Container >::TimeSeries () [inline]
Default constructor
Definition at line 58 of file timeseries.hpp.
{}
template<class T, class Container = std::map<Date, T>> template<class DateIterator , class ValueIterator > QuantLib::TimeSeries< T, Container >::TimeSeries (DateIterator dBegin, DateIterator dEnd, ValueIterator vBegin) [inline]
This constructor initializes the history with a set of values passed as two sequences, the first containing dates and the second containing corresponding values.
Definition at line 64 of file timeseries.hpp.
{
            while (dBegin != dEnd)
                values_[*(dBegin++)] = *(vBegin++);
        }
template<class T, class Container = std::map<Date, T>> template<class ValueIterator > QuantLib::TimeSeries< T, Container >::TimeSeries (const Date & firstDate, ValueIterator begin, ValueIterator end) [inline]
This constructor initializes the history with a set of values. Such values are assigned to a corresponding number of consecutive dates starting from firstDate included.
Definition at line 75 of file timeseries.hpp.
{
            Date d = firstDate;
            while (begin != end)
                values_[d++] = *(begin++);
        }
Member Function Documentation
template<class T, class Container = std::map<Date, T>> const_iterator QuantLib::TimeSeries< T, Container >::begin () const [inline]
Definition at line 162 of file timeseries.hpp.
Referenced by QuantLib::ConstantEstimator::calculate(), QuantLib::SimpleLocalEstimator::calculate(), QuantLib::Garch11::calculate(), QuantLib::GarmanKlassAbstract::calculate(), QuantLib::GarmanKlassOpenClose< ParkinsonSigma >::calculate(), QuantLib::IntervalPrice::extractValues(), TimeSeriesTest::testConstruction(), and VolatilityModelsTest::testConstruction().
{ return cbegin(); }
template<class T , class C > TimeSeries< T, C >::const_iterator QuantLib::TimeSeries< T, C >::cbegin () const [inline]
Definition at line 267 of file timeseries.hpp.
Referenced by QuantLib::TimeSeries< Real >::begin(), QuantLib::TimeSeries< Real >::cbegin_time(), and QuantLib::TimeSeries< Real >::cbegin_values().
{
        return values_.begin();
    }
template<class T, class Container = std::map<Date, T>> const_time_iterator QuantLib::TimeSeries< T, Container >::cbegin_time () const [inline]
Definition at line 209 of file timeseries.hpp.
{
            return const_time_iterator(cbegin(), get_time);
        }
template<class T, class Container = std::map<Date, T>> const_value_iterator QuantLib::TimeSeries< T, Container >::cbegin_values () const [inline]
Definition at line 196 of file timeseries.hpp.
{
            return const_value_iterator(cbegin(), get_value);
        }
template<class T , class C > TimeSeries< T, C >::const_iterator QuantLib::TimeSeries< T, C >::cend () const [inline]
Definition at line 273 of file timeseries.hpp.
Referenced by QuantLib::TimeSeries< Real >::cend_time(), QuantLib::TimeSeries< Real >::cend_values(), and QuantLib::TimeSeries< Real >::end().
{
        return values_.end();
    }
template<class T, class Container = std::map<Date, T>> const_time_iterator QuantLib::TimeSeries< T, Container >::cend_time () const [inline]
Definition at line 212 of file timeseries.hpp.
{
            return const_time_iterator(cend(), get_time);
        }
template<class T, class Container = std::map<Date, T>> const_value_iterator QuantLib::TimeSeries< T, Container >::cend_values () const [inline]
Definition at line 199 of file timeseries.hpp.
{
            return const_value_iterator(cend(), get_value);
        }
template<class T, class Container = std::map<Date, T>> const_reverse_iterator QuantLib::TimeSeries< T, Container >::crbegin () const [inline]
Definition at line 164 of file timeseries.hpp.
Referenced by QuantLib::TimeSeries< Real >::crbegin_time(), QuantLib::TimeSeries< Real >::crbegin_values(), and QuantLib::TimeSeries< Real >::rbegin().
{
            return reverse<Container, enable_reverse>(values_).rbegin();
        }
template<class T, class Container = std::map<Date, T>> const_reverse_time_iterator QuantLib::TimeSeries< T, Container >::crbegin_time () const [inline]
Definition at line 215 of file timeseries.hpp.
{
            return const_reverse_time_iterator(crbegin(), get_time);
        }
template<class T, class Container = std::map<Date, T>> const_reverse_value_iterator QuantLib::TimeSeries< T, Container >::crbegin_values () const [inline]
Definition at line 202 of file timeseries.hpp.
{
            return const_reverse_value_iterator(crbegin(), get_value);
        }
template<class T, class Container = std::map<Date, T>> const_reverse_iterator QuantLib::TimeSeries< T, Container >::crend () const [inline]
Definition at line 167 of file timeseries.hpp.
Referenced by QuantLib::TimeSeries< Real >::crend_time(), QuantLib::TimeSeries< Real >::crend_values(), and QuantLib::TimeSeries< Real >::rend().
{
            return reverse<Container, enable_reverse>(values_).rend();
        }
template<class T, class Container = std::map<Date, T>> const_reverse_time_iterator QuantLib::TimeSeries< T, Container >::crend_time () const [inline]
Definition at line 218 of file timeseries.hpp.
{
            return const_reverse_time_iterator(crend(), get_time);
        }
template<class T, class Container = std::map<Date, T>> const_reverse_value_iterator QuantLib::TimeSeries< T, Container >::crend_values () const [inline]
Definition at line 205 of file timeseries.hpp.
{
            return const_reverse_value_iterator(crend(), get_value);
        }
template<class T , class C > std::vector< Date > QuantLib::TimeSeries< T, C >::dates () const
returns the dates for which historical data exist
Definition at line 289 of file timeseries.hpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v().
Referenced by QuantLib::Index::addFixings(), and QuantLib::IntervalPrice::extractComponent().
{
        std::vector<Date> v;
        v.reserve(size());
        std::transform(cbegin(), cend(), std::back_inserter(v),
                       TimeSeries<T,C>::get_time);
        return v;
    }
template<class T , class C > bool QuantLib::TimeSeries< T, C >::empty () const [inline]
returns whether the series contains any data
Definition at line 261 of file timeseries.hpp.
Referenced by QuantLib::CommodityIndex::empty(), and QuantLib::CommodityIndex::lastQuoteDate().
{
        return values_.empty();
    }
template<class T, class Container = std::map<Date, T>> const_iterator QuantLib::TimeSeries< T, Container >::end () const [inline]
Definition at line 163 of file timeseries.hpp.
Referenced by QuantLib::SimpleLocalEstimator::calculate(), QuantLib::Garch11::calculate(), QuantLib::GarmanKlassAbstract::calculate(), QuantLib::GarmanKlassOpenClose< ParkinsonSigma >::calculate(), QuantLib::IntervalPrice::extractValues(), and QuantLib::CommodityIndex::price().
{ return cend(); }
template<class T , class C > TimeSeries< T, C >::const_iterator QuantLib::TimeSeries< T, C >::find (const Date & d) [inline]
Definition at line 279 of file timeseries.hpp.
References anonymous_namespace{marketmodel.cpp}::d.
Referenced by QuantLib::CommodityIndex::price().
{
        const_iterator i = values_.find(d);
        if (i == values_.end()) {
            values_[d] = Null<T>();
            i = values_.find(d);
        }
        return i;
    }
template<class T , class C > Date QuantLib::TimeSeries< T, C >::firstDate () const [inline]
returns the first date for which a historical datum exists
Definition at line 244 of file timeseries.hpp.
References QL_REQUIRE.
Referenced by QuantLib::TimeSeries< Real >::TimeSeries().
{
        QL_REQUIRE(!values_.empty(), "empty timeseries");
        return values_.begin()->first;
    }
template<class T, class Container = std::map<Date, T>> static const Date& QuantLib::TimeSeries< T, Container >::get_time (const container_value_type & v) [inline, static, private]
Definition at line 232 of file timeseries.hpp.
Referenced by QuantLib::TimeSeries< Real >::cbegin_time(), QuantLib::TimeSeries< Real >::cend_time(), QuantLib::TimeSeries< Real >::crbegin_time(), and QuantLib::TimeSeries< Real >::crend_time().
{
            return v.first;
        }
template<class T, class Container = std::map<Date, T>> static const T& QuantLib::TimeSeries< T, Container >::get_value (const container_value_type & v) [inline, static, private]
Definition at line 235 of file timeseries.hpp.
Referenced by QuantLib::TimeSeries< Real >::cbegin_values(), QuantLib::TimeSeries< Real >::cend_values(), QuantLib::TimeSeries< Real >::crbegin_values(), and QuantLib::TimeSeries< Real >::crend_values().
{
            return v.second;
        }
template<class T , class C > Date QuantLib::TimeSeries< T, C >::lastDate () const [inline]
returns the last date for which a historical datum exists
Definition at line 250 of file timeseries.hpp.
References QL_REQUIRE.
Referenced by QuantLib::CommodityIndex::lastQuoteDate().
{
        QL_REQUIRE(!values_.empty(), "empty timeseries");
        return rbegin()->first;
    }
template<class T, class Container = std::map<Date, T>> T QuantLib::TimeSeries< T, Container >::operator[] (const Date & d) const [inline]
returns the (possibly null) datum corresponding to the given date
Definition at line 95 of file timeseries.hpp.
{
            if (values_.find(d) != values_.end())
                return values_[d];
            else
                return Null<T>();
        }
template<class T, class Container = std::map<Date, T>> T& QuantLib::TimeSeries< T, Container >::operator[] (const Date & d) [inline]
Definition at line 101 of file timeseries.hpp.
{
            if (values_.find(d) == values_.end())
                values_[d] = Null<T>();
            return values_[d];
        }
template<class T, class Container = std::map<Date, T>> const_reverse_iterator QuantLib::TimeSeries< T, Container >::rbegin () const [inline]
Definition at line 170 of file timeseries.hpp.
Referenced by QuantLib::TimeSeries< Real >::crbegin().
{ return crbegin(); }
template<class T, class Container = std::map<Date, T>> const_reverse_iterator QuantLib::TimeSeries< T, Container >::rend () const [inline]
Definition at line 171 of file timeseries.hpp.
Referenced by QuantLib::TimeSeries< Real >::crend().
{ return crend(); }
template<class T , class C > Size QuantLib::TimeSeries< T, C >::size () const [inline]
returns the number of historical data including null ones
Definition at line 256 of file timeseries.hpp.
Referenced by QuantLib::ConstantEstimator::calculate(), and QuantLib::IntervalPrice::extractValues().
{
        return values_.size();
    }
template<class T , class C > std::vector< T > QuantLib::TimeSeries< T, C >::values () const
returns the historical data
Definition at line 298 of file timeseries.hpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v().
Referenced by QuantLib::Index::addFixings(), QuantLib::ConstantEstimator::calculate(), and QuantLib::Garch11::costFunction().
{
        std::vector<T> v;
        v.reserve(size());
        std::transform(cbegin(), cend(), std::back_inserter(v),
                       TimeSeries<T,C>::get_value);
        return v;
    }
Member Data Documentation
template<class T, class Container = std::map<Date, T>> Container QuantLib::TimeSeries< T, Container >::values_ [mutable, private]
Definition at line 55 of file timeseries.hpp.
Referenced by QuantLib::TimeSeries< Real >::crbegin(), QuantLib::TimeSeries< Real >::crend(), QuantLib::TimeSeries< Real >::operator[](), and QuantLib::TimeSeries< Real >::TimeSeries().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/timeseries.hpp