QuantLib: QuantLib::FDVanillaEngine Class Reference
QuantLib::FDVanillaEngine Class Reference
Finite-differences pricing engine for BSM one asset options.
#include <fdvanillaengine.hpp>
Public Member Functions
FDVanillaEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > &process, Size timeSteps, Size gridPoints, bool timeDependent=false)
virtual ~FDVanillaEngine ()
const Array & grid () const
Protected Types
typedef BoundaryCondition
< TridiagonalOperator > bc_type
Protected Member Functions
virtual void setupArguments (const PricingEngine::arguments *) const
virtual void setGridLimits () const
virtual void setGridLimits (Real, Time) const
virtual void initializeInitialCondition () const
virtual void initializeBoundaryConditions () const
virtual void initializeOperator () const
virtual Time getResidualTime () const
void ensureStrikeInGrid () const
Protected Attributes
boost::shared_ptr
< GeneralizedBlackScholesProcess > process_
Size timeSteps_
Size gridPoints_
bool timeDependent_
Real requiredGridValue_
Date exerciseDate_
boost::shared_ptr< Payoff > payoff_
TridiagonalOperator finiteDifferenceOperator_
SampledCurve intrinsicValues_
std::vector< boost::shared_ptr
< bc_type > > BCs_
Real sMin_
Real center_
Real sMax_
Private Member Functions
Size safeGridPoints (Size gridPoints, Time residualTime) const
Private Attributes
Real gridLogSpacing_
Static Private Attributes
static const Real safetyZoneFactor_ = 1.1
Detailed Description
Finite-differences pricing engine for BSM one asset options.
The name is a misnomer as this is a base class for any finite difference scheme. Its main job is to handle grid layout.
Definition at line 46 of file fdvanillaengine.hpp.
Member Typedef Documentation
typedef BoundaryCondition<TridiagonalOperator> QuantLib::FDVanillaEngine::bc_type [protected]
Definition at line 76 of file fdvanillaengine.hpp.
Constructor & Destructor Documentation
QuantLib::FDVanillaEngine::FDVanillaEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > & process, Size timeSteps, Size gridPoints, bool timeDependent = false) [inline]
Definition at line 48 of file fdvanillaengine.hpp.
        : process_(process), timeSteps_(timeSteps), gridPoints_(gridPoints),
          timeDependent_(timeDependent),
          intrinsicValues_(gridPoints), BCs_(2) {}
virtual QuantLib::FDVanillaEngine::~FDVanillaEngine () [inline, virtual]
Definition at line 55 of file fdvanillaengine.hpp.
{}
Member Function Documentation
void QuantLib::FDVanillaEngine::ensureStrikeInGrid () const [protected]
Definition at line 68 of file fdvanillaengine.cpp.
References center_, payoff_, safetyZoneFactor_, sMax_, sMin_, and QuantLib::StrikedTypePayoff::strike().
Referenced by setGridLimits().
{
        // ensure strike is included in the grid
        boost::shared_ptr<StrikedTypePayoff> striked_payoff =
            boost::dynamic_pointer_cast<StrikedTypePayoff>(payoff_);
        if (!striked_payoff)
            return;
        Real requiredGridValue = striked_payoff->strike();
        if(sMin_ > requiredGridValue/safetyZoneFactor_){
            sMin_ = requiredGridValue/safetyZoneFactor_;
            // enforce central placement of the underlying
            sMax_ = center_/(sMin_/center_);
        }
        if(sMax_ < requiredGridValue*safetyZoneFactor_){
            sMax_ = requiredGridValue*safetyZoneFactor_;
            // enforce central placement of the underlying
            sMin_ = center_/(sMax_/center_);
        }
    }
Time QuantLib::FDVanillaEngine::getResidualTime () const [protected, virtual]
Definition at line 112 of file fdvanillaengine.cpp.
References exerciseDate_, and process_.
Referenced by initializeOperator(), and setGridLimits().
{
        return process_->time(exerciseDate_);
    }
const Array& QuantLib::FDVanillaEngine::grid () const [inline]
Definition at line 57 of file fdvanillaengine.hpp.
References QuantLib::SampledCurve::grid(), and intrinsicValues_.
{ return intrinsicValues_.grid(); }
void QuantLib::FDVanillaEngine::initializeBoundaryConditions () const [protected, virtual]
Definition at line 101 of file fdvanillaengine.cpp.
References BCs_, intrinsicValues_, QuantLib::BoundaryCondition< TridiagonalOperator >::Lower, QuantLib::SampledCurve::size(), QuantLib::BoundaryCondition< TridiagonalOperator >::Upper, and QuantLib::SampledCurve::value().
{
        BCs_[0] = boost::shared_ptr<bc_type>(new NeumannBC(
                                      intrinsicValues_.value(1)-
                                      intrinsicValues_.value(0),
                                      NeumannBC::Lower));
        BCs_[1] = boost::shared_ptr<bc_type>(new NeumannBC(
                       intrinsicValues_.value(intrinsicValues_.size()-1) -
                       intrinsicValues_.value(intrinsicValues_.size()-2),
                       NeumannBC::Upper));
    }
void QuantLib::FDVanillaEngine::initializeInitialCondition () const [protected, virtual]
Definition at line 88 of file fdvanillaengine.cpp.
References intrinsicValues_, payoff_, QuantLib::SampledCurve::sample(), QuantLib::SampledCurve::setLogGrid(), sMax_, and sMin_.
{
        intrinsicValues_.setLogGrid(sMin_, sMax_);
        intrinsicValues_.sample(*payoff_);
    }
void QuantLib::FDVanillaEngine::initializeOperator () const [protected, virtual]
Definition at line 93 of file fdvanillaengine.cpp.
References finiteDifferenceOperator_, QuantLib::OperatorFactory::getOperator(), getResidualTime(), QuantLib::SampledCurve::grid(), intrinsicValues_, process_, and timeDependent_.
{
        finiteDifferenceOperator_ =
            OperatorFactory::getOperator(process_,
                                         intrinsicValues_.grid(),
                                         getResidualTime(),
                                         timeDependent_);
    }
Size QuantLib::FDVanillaEngine::safeGridPoints (Size gridPoints, Time residualTime) const [private]
Definition at line 117 of file fdvanillaengine.cpp.
Referenced by setGridLimits().
{
        static const Size minGridPoints = 10;
        static const Size minGridPointsPerYear = 2;
        return std::max(gridPoints,
                        residualTime > 1.0 ?
                            static_cast<Size>((minGridPoints +
                                               (residualTime-1.0) *
                                                minGridPointsPerYear))
                            : minGridPoints);
    }
void QuantLib::FDVanillaEngine::setGridLimits () const [protected, virtual]
Reimplemented in QuantLib::FDDividendEngineShiftScale< Scheme >, QuantLib::FDDividendEngineMerton73< Scheme >, and QuantLib::FDDividendEngineBase< Scheme >.
Definition at line 33 of file fdvanillaengine.cpp.
References ensureStrikeInGrid(), getResidualTime(), and process_.
Referenced by QuantLib::FDDividendEngineMerton73< Scheme >::setGridLimits(), and QuantLib::FDDividendEngineShiftScale< Scheme >::setGridLimits().
{
        setGridLimits(process_->stateVariable()->value(),
                      getResidualTime());
        ensureStrikeInGrid();
    }
void QuantLib::FDVanillaEngine::setGridLimits (Real center, Time t) const [protected, virtual]
Definition at line 50 of file fdvanillaengine.cpp.
References center_, gridPoints_, intrinsicValues_, process_, QL_REQUIRE, safeGridPoints(), QuantLib::SampledCurve::size(), sMax_, and sMin_.
{
        QL_REQUIRE(center > 0.0, "negative or null underlying given");
        center_ = center;
        Size newGridPoints = safeGridPoints(gridPoints_, t);
        if (newGridPoints > intrinsicValues_.size()) {
            intrinsicValues_ = SampledCurve(newGridPoints);
        }
        Real volSqrtTime = std::sqrt(process_->blackVolatility()
                                     ->blackVariance(t, center_));
        // the prefactor fine tunes performance at small volatilities
        Real prefactor = 1.0 + 0.02/volSqrtTime;
        Real minMaxFactor = std::exp(4.0 * prefactor * volSqrtTime);
        sMin_ = center_/minMaxFactor;  // underlying grid min value
        sMax_ = center_*minMaxFactor;  // underlying grid max value
    }
void QuantLib::FDVanillaEngine::setupArguments (const PricingEngine::arguments * a) const [protected, virtual]
Reimplemented in QuantLib::FDMultiPeriodEngine< Scheme >, and QuantLib::FDDividendEngineBase< Scheme >.
Definition at line 39 of file fdvanillaengine.cpp.
References anonymous_namespace{marketmodel.cpp}::a, QuantLib::Option::arguments::exercise, exerciseDate_, QuantLib::Option::arguments::payoff, payoff_, QL_REQUIRE, and requiredGridValue_.
{
        const OneAssetOption::arguments * args =
            dynamic_cast<const OneAssetOption::arguments *>(a);
        QL_REQUIRE(args, "incorrect argument type");
        exerciseDate_ = args->exercise->lastDate();
        payoff_ = args->payoff;
        requiredGridValue_ =
            boost::dynamic_pointer_cast<StrikedTypePayoff>(payoff_)->strike();
    }
Member Data Documentation
std::vector<boost::shared_ptr<bc_type> > QuantLib::FDVanillaEngine::BCs_ [mutable, protected]
Definition at line 77 of file fdvanillaengine.hpp.
Referenced by initializeBoundaryConditions().
Real QuantLib::FDVanillaEngine::center_ [mutable, protected]
Definition at line 79 of file fdvanillaengine.hpp.
Referenced by ensureStrikeInGrid(), and setGridLimits().
Date QuantLib::FDVanillaEngine::exerciseDate_ [mutable, protected]
Definition at line 72 of file fdvanillaengine.hpp.
Referenced by getResidualTime(), and setupArguments().
TridiagonalOperator QuantLib::FDVanillaEngine::finiteDifferenceOperator_ [mutable, protected]
Definition at line 74 of file fdvanillaengine.hpp.
Referenced by initializeOperator().
Real QuantLib::FDVanillaEngine::gridLogSpacing_ [mutable, private]
Definition at line 84 of file fdvanillaengine.hpp.
Size QuantLib::FDVanillaEngine::gridPoints_ [protected]
Definition at line 69 of file fdvanillaengine.hpp.
Referenced by setGridLimits().
SampledCurve QuantLib::FDVanillaEngine::intrinsicValues_ [mutable, protected]
Definition at line 75 of file fdvanillaengine.hpp.
Referenced by QuantLib::FDBermudanEngine< Scheme >::executeIntermediateStep(), grid(), initializeBoundaryConditions(), initializeInitialCondition(), initializeOperator(), and setGridLimits().
boost::shared_ptr<Payoff> QuantLib::FDVanillaEngine::payoff_ [mutable, protected]
Definition at line 73 of file fdvanillaengine.hpp.
Referenced by ensureStrikeInGrid(), initializeInitialCondition(), and setupArguments().
boost::shared_ptr<GeneralizedBlackScholesProcess> QuantLib::FDVanillaEngine::process_ [protected]
Definition at line 68 of file fdvanillaengine.hpp.
Referenced by QuantLib::FDDividendEngineBase< Scheme >::getDiscountedDividend(), getResidualTime(), initializeOperator(), setGridLimits(), and QuantLib::FDMultiPeriodEngine< Scheme >::setupArguments().
Real QuantLib::FDVanillaEngine::requiredGridValue_ [mutable, protected]
Definition at line 71 of file fdvanillaengine.hpp.
Referenced by setupArguments().
const Real QuantLib::FDVanillaEngine::safetyZoneFactor_ = 1.1 [static, private]
Definition at line 87 of file fdvanillaengine.hpp.
Referenced by ensureStrikeInGrid().
Real QuantLib::FDVanillaEngine::sMax_ [mutable, protected]
Definition at line 79 of file fdvanillaengine.hpp.
Referenced by ensureStrikeInGrid(), initializeInitialCondition(), and setGridLimits().
Real QuantLib::FDVanillaEngine::sMin_ [mutable, protected]
Definition at line 79 of file fdvanillaengine.hpp.
Referenced by ensureStrikeInGrid(), initializeInitialCondition(), and setGridLimits().
bool QuantLib::FDVanillaEngine::timeDependent_ [protected]
Definition at line 70 of file fdvanillaengine.hpp.
Referenced by initializeOperator().
Size QuantLib::FDVanillaEngine::timeSteps_ [protected]
Definition at line 69 of file fdvanillaengine.hpp.
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/vanilla/fdvanillaengine.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/vanilla/fdvanillaengine.cpp