QuantLib: QuantLib::DirichletBC Class Reference
QuantLib::DirichletBC Class Reference
Neumann boundary condition (i.e., constant value)
#include <boundarycondition.hpp>
Public Member Functions
DirichletBC (Real value, Side side)
void applyBeforeApplying (TridiagonalOperator &) const
void applyAfterApplying (Array &) const
void applyBeforeSolving (TridiagonalOperator &, Array &rhs) const
void applyAfterSolving (Array &) const
void setTime (Time)
Private Attributes
Real value_
Side side_
Detailed Description
Neumann boundary condition (i.e., constant value)
Todo:
generalize to time-dependent conditions.
Definition at line 95 of file boundarycondition.hpp.
Constructor & Destructor Documentation
QuantLib::DirichletBC::DirichletBC (Real value, DirichletBC::Side side)
Definition at line 73 of file boundarycondition.cpp.
    : value_(value), side_(side) {}
Member Function Documentation
void QuantLib::DirichletBC::applyAfterApplying (Array &) const [virtual]
This method modifies an array \(u \) so that it satisfies the given condition.
Implements QuantLib::BoundaryCondition< TridiagonalOperator >.
Definition at line 89 of file boundarycondition.cpp.
References QuantLib::BoundaryCondition< TridiagonalOperator >::Lower, QL_FAIL, side_, QuantLib::Array::size(), QuantLib::BoundaryCondition< TridiagonalOperator >::Upper, and value_.
{
        switch (side_) {
          case Lower:
            u[0] = value_;
            break;
          case Upper:
            u[u.size()-1] = value_;
            break;
          default:
            QL_FAIL("unknown side for Neumann boundary condition");
        }
    }
void QuantLib::DirichletBC::applyAfterSolving (Array &) const [virtual]
This method modifies an array \(u \) so that it satisfies the given condition.
Implements QuantLib::BoundaryCondition< TridiagonalOperator >.
Definition at line 118 of file boundarycondition.cpp.
{}
void QuantLib::DirichletBC::applyBeforeApplying (TridiagonalOperator &) const [virtual]
This method modifies an operator \(L \) before it is applied to an array \(u \) so that \(v = Lu \) will satisfy the given condition.
Implements QuantLib::BoundaryCondition< TridiagonalOperator >.
Definition at line 76 of file boundarycondition.cpp.
References QuantLib::BoundaryCondition< TridiagonalOperator >::Lower, QL_FAIL, QuantLib::TridiagonalOperator::setFirstRow(), QuantLib::TridiagonalOperator::setLastRow(), side_, and QuantLib::BoundaryCondition< TridiagonalOperator >::Upper.
{
        switch (side_) {
          case Lower:
            L.setFirstRow(1.0,0.0);
            break;
          case Upper:
            L.setLastRow(0.0,1.0);
            break;
          default:
            QL_FAIL("unknown side for Neumann boundary condition");
        }
    }
void QuantLib::DirichletBC::applyBeforeSolving (TridiagonalOperator & , Array & rhs) const [virtual]
This method modifies an operator \(L \) before the linear system \(Lu' = u \) is solved so that \(u' \) will satisfy the given condition.
Implements QuantLib::BoundaryCondition< TridiagonalOperator >.
Definition at line 102 of file boundarycondition.cpp.
References QuantLib::BoundaryCondition< TridiagonalOperator >::Lower, QL_FAIL, QuantLib::TridiagonalOperator::setFirstRow(), QuantLib::TridiagonalOperator::setLastRow(), side_, QuantLib::Array::size(), QuantLib::BoundaryCondition< TridiagonalOperator >::Upper, and value_.
{
        switch (side_) {
          case Lower:
            L.setFirstRow(1.0,0.0);
            rhs[0] = value_;
            break;
          case Upper:
            L.setLastRow(0.0,1.0);
            rhs[rhs.size()-1] = value_;
            break;
          default:
            QL_FAIL("unknown side for Neumann boundary condition");
        }
    }
void QuantLib::DirichletBC::setTime (Time t) [inline, virtual]
This method sets the current time for time-dependent boundary conditions.
Implements QuantLib::BoundaryCondition< TridiagonalOperator >.
Definition at line 103 of file boundarycondition.hpp.
{}
Member Data Documentation
Side QuantLib::DirichletBC::side_ [private]
Definition at line 106 of file boundarycondition.hpp.
Referenced by applyAfterApplying(), applyBeforeApplying(), and applyBeforeSolving().
Real QuantLib::DirichletBC::value_ [private]
Definition at line 105 of file boundarycondition.hpp.
Referenced by applyAfterApplying(), and applyBeforeSolving().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/boundarycondition.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/boundarycondition.cpp