QuantLib: QuantLib::ActualActual::AFB_Impl Class Reference
QuantLib::ActualActual::AFB_Impl Class Reference
Public Member Functions
std::string name () const
Time yearFraction (const Date &d1, const Date &d2, const Date &, const Date &) const
Detailed Description
Definition at line 75 of file actualactual.hpp.
Member Function Documentation
std::string QuantLib::ActualActual::AFB_Impl::name () const [inline, virtual]
Implements QuantLib::DayCounter::Impl.
Definition at line 77 of file actualactual.hpp.
{
                return std::string("Actual/Actual (AFB)");
            }
Time QuantLib::ActualActual::AFB_Impl::yearFraction (const Date & d1, const Date & d2, const Date & , const Date &) const [virtual]
Implements QuantLib::DayCounter::Impl.
Definition at line 161 of file actualactual.cpp.
References QuantLib::DayCounter::dayCount(), QuantLib::February, QuantLib::Date::isLeap(), QuantLib::Date::year(), QuantLib::DayCounter::yearFraction(), and QuantLib::Years.
{
        if (d1 == d2)
            return 0.0;
        if (d1 > d2)
            return -yearFraction(d2,d1,Date(),Date());
        Date newD2=d2, temp=d2;
        Time sum = 0.0;
        while (temp > d1) {
            temp = newD2 - 1*Years;
            if (temp.dayOfMonth()==28 && temp.month()==2
                && Date::isLeap(temp.year())) {
                temp += 1;
            }
            if (temp>=d1) {
                sum += 1.0;
                newD2 = temp;
            }
        }
        Real den = 365.0;
        if (Date::isLeap(newD2.year())) {
            temp = Date(29, February, newD2.year());
            if (newD2>temp && d1<=temp)
                den += 1.0;
        } else if (Date::isLeap(d1.year())) {
            temp = Date(29, February, d1.year());
            if (newD2>temp && d1<=temp)
                den += 1.0;
        }
        return sum+dayCount(d1, newD2)/den;
    }
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/time/daycounters/actualactual.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/time/daycounters/actualactual.cpp