QuantLib: QuantLib::UniformGridMesher Class Reference
QuantLib::UniformGridMesher Class Reference
#include <uniformgridmesher.hpp>
Public Member Functions
UniformGridMesher (const boost::shared_ptr< FdmLinearOpLayout > &index, const std::vector< std::pair< Real, Real > > &boundaries)
Real dplus (const FdmLinearOpIterator &, Size direction) const
Real dminus (const FdmLinearOpIterator &, Size direction) const
Real location (const FdmLinearOpIterator &iter, Size direction) const
Disposable< Array > locations (Size direction) const
Private Attributes
boost::scoped_array< Real > dx_
std::vector< std::vector< Real > > locations_
Detailed Description
Definition at line 34 of file uniformgridmesher.hpp.
Constructor & Destructor Documentation
QuantLib::UniformGridMesher::UniformGridMesher (const boost::shared_ptr< FdmLinearOpLayout > & index, const std::vector< std::pair< Real, Real > > & boundaries)
Definition at line 27 of file uniformgridmesher.cpp.
References dx_, locations_, and QL_REQUIRE.
    : FdmMesher (layout),
      dx_       (new Real[layout->dim().size()]),
      locations_(layout->dim().size()) {
        QL_REQUIRE(boundaries.size() == layout->dim().size(),
                   "inconsistent boundaries given");
        for (Size i=0; i < layout->dim().size(); ++i) {
            dx_[i] = (boundaries[i].second - boundaries[i].first)
                / (layout->dim()[i]-1);
            locations_[i] = std::vector<Real>(layout->dim()[i]);
            for (Size j=0; j < layout->dim()[i]; ++j) {
                locations_[i][j] = boundaries[i].first + j*dx_[i];
            }
        }
    }
Member Function Documentation
Real QuantLib::UniformGridMesher::dminus (const FdmLinearOpIterator & , Size direction) const [inline, virtual]
Implements QuantLib::FdmMesher.
Definition at line 43 of file uniformgridmesher.hpp.
References dx_.
Referenced by FdmLinearOpTest::testUniformGridMesher().
{
            return dx_[direction];
        }
Real QuantLib::UniformGridMesher::dplus (const FdmLinearOpIterator & , Size direction) const [inline, virtual]
Implements QuantLib::FdmMesher.
Definition at line 40 of file uniformgridmesher.hpp.
References dx_.
Referenced by FdmLinearOpTest::testUniformGridMesher().
{
            return dx_[direction];
        }
Real QuantLib::UniformGridMesher::location (const FdmLinearOpIterator & iter, Size direction) const [inline, virtual]
Implements QuantLib::FdmMesher.
Definition at line 47 of file uniformgridmesher.hpp.
References QuantLib::FdmLinearOpIterator::coordinates(), and locations_.
{
            return locations_[direction][iter.coordinates()[direction]];
        }
Disposable< Array > QuantLib::UniformGridMesher::locations (Size direction) const [virtual]
Implements QuantLib::FdmMesher.
Definition at line 48 of file uniformgridmesher.cpp.
References anonymous_namespace{marketmodel.cpp}::d, QuantLib::FdmMesher::layout_, and locations_.
{
        Array retVal(layout_->size());
        const FdmLinearOpIterator endIter = layout_->end();
        for (FdmLinearOpIterator iter = layout_->begin();
            iter != endIter; ++iter) {
            retVal[iter.index()] = locations_[d][iter.coordinates()[d]];
        }
        return retVal;
    }
Member Data Documentation
boost::scoped_array<Real> QuantLib::UniformGridMesher::dx_ [private]
Definition at line 55 of file uniformgridmesher.hpp.
Referenced by dminus(), dplus(), and UniformGridMesher().
std::vector<std::vector<Real> > QuantLib::UniformGridMesher::locations_ [private]
Definition at line 56 of file uniformgridmesher.hpp.
Referenced by location(), locations(), and UniformGridMesher().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/meshers/uniformgridmesher.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/meshers/uniformgridmesher.cpp