QuantLib: QuantLib::LmExponentialCorrelationModel Class Reference
QuantLib::LmExponentialCorrelationModel Class Reference
exponential correlation model
#include <lmexpcorrmodel.hpp>
Public Member Functions
LmExponentialCorrelationModel (Size size, Real rho)
Disposable< Matrix > correlation (Time t, const Array &x=Null< Array >()) const
Disposable< Matrix > pseudoSqrt (Time t, const Array &x=Null< Array >()) const
Real correlation (Size i, Size j, Time t, const Array &x) const
bool isTimeIndependent () const
Protected Member Functions
void generateArguments ()
Private Attributes
Matrix corrMatrix_
Matrix pseudoSqrt_
Detailed Description
exponential correlation model
This class describes a exponential correlation model
\[ \rho_{i,j}=e^{(-\beta \|i-j\|)} \]
References:
Damiano Brigo, Fabio Mercurio, Massimo Morini, 2003, Different Covariance Parameterizations of Libor Market Model and Joint Caps/Swaptions Calibration, (<http://www.business.uts.edu.au/qfrc/conferences/qmf2001/Brigo_D.pdf>)
Definition at line 45 of file lmexpcorrmodel.hpp.
Constructor & Destructor Documentation
QuantLib::LmExponentialCorrelationModel::LmExponentialCorrelationModel (Size size, Real rho)
Definition at line 25 of file lmexpcorrmodel.cpp.
References QuantLib::LmCorrelationModel::arguments_, and generateArguments().
   : LmCorrelationModel(size, 1),
     corrMatrix_(size, size),
     pseudoSqrt_(size, size) {
        arguments_[0] = ConstantParameter(rho, PositiveConstraint());
        generateArguments();
    }
Member Function Documentation
Disposable< Matrix > QuantLib::LmExponentialCorrelationModel::correlation (Time t, const Array & x = Null<Array>()) const [virtual]
Implements QuantLib::LmCorrelationModel.
Definition at line 34 of file lmexpcorrmodel.cpp.
References corrMatrix_.
{
        Matrix tmp(corrMatrix_);
        return tmp;
    }
Real QuantLib::LmExponentialCorrelationModel::correlation (Size i, Size j, Time t, const Array & x) const [virtual]
Reimplemented from QuantLib::LmCorrelationModel.
Definition at line 41 of file lmexpcorrmodel.cpp.
References corrMatrix_.
{
        return corrMatrix_[i][j];
    }
void QuantLib::LmExponentialCorrelationModel::generateArguments () [protected, virtual]
Implements QuantLib::LmCorrelationModel.
Definition at line 56 of file lmexpcorrmodel.cpp.
References QuantLib::LmCorrelationModel::arguments_, corrMatrix_, pseudoSqrt(), pseudoSqrt_, QuantLib::LmCorrelationModel::size_, and QuantLib::SalvagingAlgorithm::Spectral.
Referenced by LmExponentialCorrelationModel().
{
        const Real rho = arguments_[0](0.0);
        for (Size i=0; i<size_; ++i) {
            for (Size j=i; j<size_; ++j) {
                corrMatrix_[i][j] = corrMatrix_[j][i]
                    = std::exp(-rho*std::fabs(Real(i)-Real(j)));
            }
        }
        pseudoSqrt_ = QuantLib::pseudoSqrt(corrMatrix_,
                                           SalvagingAlgorithm::Spectral);
    }
bool QuantLib::LmExponentialCorrelationModel::isTimeIndependent () const [virtual]
Reimplemented from QuantLib::LmCorrelationModel.
Definition at line 46 of file lmexpcorrmodel.cpp.
{
        return true;
    }
Disposable< Matrix > QuantLib::LmExponentialCorrelationModel::pseudoSqrt (Time t, const Array & x = Null<Array>()) const [virtual]
Reimplemented from QuantLib::LmCorrelationModel.
Definition at line 50 of file lmexpcorrmodel.cpp.
References pseudoSqrt_.
Referenced by generateArguments().
{
        Matrix tmp(pseudoSqrt_);
        return tmp;
    }
Member Data Documentation
Matrix QuantLib::LmExponentialCorrelationModel::corrMatrix_ [private]
Definition at line 60 of file lmexpcorrmodel.hpp.
Referenced by correlation(), and generateArguments().
Matrix QuantLib::LmExponentialCorrelationModel::pseudoSqrt_ [private]
Definition at line 60 of file lmexpcorrmodel.hpp.
Referenced by generateArguments(), and pseudoSqrt().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/legacy/libormarketmodels/lmexpcorrmodel.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/legacy/libormarketmodels/lmexpcorrmodel.cpp