QuantLib: QuantLib::FdmNdimSolver< N > Class Template Reference
QuantLib::FdmNdimSolver< N > Class Template Reference
#include <fdmndimsolver.hpp>
Public Types
typedef MultiCubicSpline< N >
::data_table data_table
Public Member Functions
FdmNdimSolver (const FdmSolverDesc &solverDesc, const FdmSchemeDesc &schemeDesc, const boost::shared_ptr< FdmLinearOpComposite > &op)
void performCalculations () const
Real interpolateAt (const std::vector< Real > &x) const
Real thetaAt (const std::vector< Real > &x) const
template<>
void setValue (data_table &f, const std::vector< Size > &x, Real value)
Static Public Member Functions
static void setValue (data_table &f, const std::vector< Size > &x, Real value)
Private Attributes
const FdmSolverDesc solverDesc_
const FdmSchemeDesc schemeDesc_
const boost::shared_ptr
< FdmLinearOpComposite > op_
const boost::shared_ptr
< FdmSnapshotCondition > thetaCondition_
const boost::shared_ptr
< FdmStepConditionComposite > conditions_
std::vector< std::vector< Real > > x_
std::vector< Real > initialValues_
const std::vector< bool > extrapolation_
boost::shared_ptr< data_table > f_
boost::shared_ptr
< MultiCubicSpline< N > > interp_
Detailed Description
template<Size N>
class QuantLib::FdmNdimSolver< N >
Definition at line 42 of file fdmndimsolver.hpp.
Member Typedef Documentation
template<Size N> typedef MultiCubicSpline<N>::data_table QuantLib::FdmNdimSolver< N >::data_table
Definition at line 54 of file fdmndimsolver.hpp.
Constructor & Destructor Documentation
template<Size N> QuantLib::FdmNdimSolver< N >::FdmNdimSolver (const FdmSolverDesc & solverDesc, const FdmSchemeDesc & schemeDesc, const boost::shared_ptr< FdmLinearOpComposite > & op) [inline]
Definition at line 76 of file fdmndimsolver.hpp.
References anonymous_namespace{marketmodel.cpp}::c, QuantLib::FdmSolverDesc::calculator, QuantLib::FdmNdimSolver< N >::f_, QuantLib::FdmNdimSolver< N >::initialValues_, QuantLib::FdmSolverDesc::maturity, QuantLib::FdmSolverDesc::mesher, anonymous_namespace{matrices.cpp}::N, QL_REQUIRE, QuantLib::FdmNdimSolver< N >::solverDesc_, and QuantLib::FdmNdimSolver< N >::x_.
    : solverDesc_(solverDesc),
      schemeDesc_(schemeDesc),
      op_(op),
      thetaCondition_(new FdmSnapshotCondition(
        0.99*std::min(1.0/365.0,
                solverDesc.condition->stoppingTimes().empty()
                ? solverDesc.maturity :
                  solverDesc.condition->stoppingTimes().front()))),
      conditions_(FdmStepConditionComposite::joinConditions(thetaCondition_,
                                                        solverDesc.condition)),
      x_            (solverDesc.mesher->layout()->dim().size()),
      initialValues_(solverDesc.mesher->layout()->size()),
      extrapolation_(std::vector<bool>(N, false)) {
        const boost::shared_ptr<FdmMesher> mesher = solverDesc.mesher;
        const boost::shared_ptr<FdmLinearOpLayout> layout = mesher->layout();
        QL_REQUIRE(layout->dim().size() == N, "solver dim " << N
                    << "does not fit to layout dim " << layout->size());
        for (Size i=0; i < N; ++i) {
            x_[i].reserve(layout->dim()[i]);
        }
        const FdmLinearOpIterator endIter = layout->end();
        for (FdmLinearOpIterator iter = layout->begin(); iter != endIter;
             ++iter) {
            initialValues_[iter.index()] = solverDesc_.calculator
                                ->avgInnerValue(iter, solverDesc.maturity);
            const std::vector<Size>& c = iter.coordinates();
            for (Size i=0; i < N; ++i) {
                if (!(std::accumulate(c.begin(), c.end(), 0)-c[i])) {
                    x_[i].push_back(mesher->location(iter, i));
                }
            }
        }
        f_ = boost::shared_ptr<data_table>(new data_table(x_));
    }
Member Function Documentation
template<Size N> Real QuantLib::FdmNdimSolver< N >::interpolateAt (const std::vector< Real > & x) const [inline]
Definition at line 168 of file fdmndimsolver.hpp.
Referenced by FdmLinearOpTest::testFdmHestonHullWhiteOp().
{
        calculate();
        return (*interp_)(x);
    }
template<Size N> void QuantLib::FdmNdimSolver< N >::performCalculations () const [inline, virtual]
This method must implement any calculations which must be (re)done in order to calculate the desired results.
Implements QuantLib::LazyObject.
Definition at line 124 of file fdmndimsolver.hpp.
References QuantLib::anonymous_namespace{zigguratrng.cpp}::f_, anonymous_namespace{optimizers.cpp}::initialValues_, and QuantLib::FdmBackwardSolver::rollback().
{
        Array rhs(initialValues_.size());
        std::copy(initialValues_.begin(), initialValues_.end(), rhs.begin());
        FdmBackwardSolver(op_, solverDesc_.bcSet, conditions_, schemeDesc_)
                 .rollback(rhs, solverDesc_.maturity, 0.0,
                           solverDesc_.timeSteps, solverDesc_.dampingSteps);
        const boost::shared_ptr<FdmLinearOpLayout> layout
                                               = solverDesc_.mesher->layout();
        const FdmLinearOpIterator endIter = layout->end();
        for (FdmLinearOpIterator iter = layout->begin(); iter != endIter;
             ++iter) {
            setValue(*f_, iter.coordinates(), rhs[iter.index()]);
        }
        interp_ = boost::shared_ptr<MultiCubicSpline<N> >(
            new MultiCubicSpline<N>(x_, *f_, extrapolation_));
    }
template<Size N> void QuantLib::FdmNdimSolver< N >::setValue (data_table & f, const std::vector< Size > & x, Real value) [inline, static]
Definition at line 175 of file fdmndimsolver.hpp.
References anonymous_namespace{matrices.cpp}::N.
{
        FdmNdimSolver<N-1>::setValue(f[x[x.size()-N]], x, value);
    }
template<> void QuantLib::FdmNdimSolver< 1 >::setValue (data_table & f, const std::vector< Size > & x, Real value) [inline]
Definition at line 181 of file fdmndimsolver.hpp.
{
        f[x.back()] = value;
    }
template<Size N> Real QuantLib::FdmNdimSolver< N >::thetaAt (const std::vector< Real > & x) const [inline]
Definition at line 147 of file fdmndimsolver.hpp.
References anonymous_namespace{interpolations.cpp}::f(), and QL_REQUIRE.
Referenced by FdmLinearOpTest::testFdmHestonHullWhiteOp().
{
        QL_REQUIRE(conditions_->stoppingTimes().front() > 0.0,
                   "stopping time at zero-> can't calculate theta");
        calculate();
        const Array& rhs = thetaCondition_->getValues();
        const boost::shared_ptr<FdmLinearOpLayout> layout
                                            = solverDesc_.mesher->layout();
        data_table f(x_);
        const FdmLinearOpIterator endIter = layout->end();
        for (FdmLinearOpIterator iter = layout->begin(); iter != endIter;
             ++iter) {
            setValue(f, iter.coordinates(), rhs[iter.index()]);
        }
        return (MultiCubicSpline<N>(x_, f)(x)
                        - interpolateAt(x)) / thetaCondition_->getTime();
    }
Member Data Documentation
template<Size N> const boost::shared_ptr<FdmStepConditionComposite> QuantLib::FdmNdimSolver< N >::conditions_ [private]
Definition at line 64 of file fdmndimsolver.hpp.
template<Size N> const std::vector<bool> QuantLib::FdmNdimSolver< N >::extrapolation_ [private]
Definition at line 68 of file fdmndimsolver.hpp.
template<Size N> boost::shared_ptr<data_table> QuantLib::FdmNdimSolver< N >::f_ [mutable, private]
Definition at line 70 of file fdmndimsolver.hpp.
Referenced by QuantLib::FdmNdimSolver< N >::FdmNdimSolver().
template<Size N> std::vector<Real> QuantLib::FdmNdimSolver< N >::initialValues_ [private]
Definition at line 67 of file fdmndimsolver.hpp.
Referenced by QuantLib::FdmNdimSolver< N >::FdmNdimSolver().
template<Size N> boost::shared_ptr<MultiCubicSpline<N> > QuantLib::FdmNdimSolver< N >::interp_ [mutable, private]
Definition at line 71 of file fdmndimsolver.hpp.
template<Size N> const boost::shared_ptr<FdmLinearOpComposite> QuantLib::FdmNdimSolver< N >::op_ [private]
Definition at line 61 of file fdmndimsolver.hpp.
template<Size N> const FdmSchemeDesc QuantLib::FdmNdimSolver< N >::schemeDesc_ [private]
Definition at line 60 of file fdmndimsolver.hpp.
template<Size N> const FdmSolverDesc QuantLib::FdmNdimSolver< N >::solverDesc_ [private]
Definition at line 59 of file fdmndimsolver.hpp.
Referenced by QuantLib::FdmNdimSolver< N >::FdmNdimSolver().
template<Size N> const boost::shared_ptr<FdmSnapshotCondition> QuantLib::FdmNdimSolver< N >::thetaCondition_ [private]
Definition at line 63 of file fdmndimsolver.hpp.
template<Size N> std::vector<std::vector<Real> > QuantLib::FdmNdimSolver< N >::x_ [private]
Definition at line 66 of file fdmndimsolver.hpp.
Referenced by QuantLib::FdmNdimSolver< N >::FdmNdimSolver().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/solvers/fdmndimsolver.hpp