QuantLib: QuantLib::IntegralHestonVarianceOptionEngine Class Reference
QuantLib::IntegralHestonVarianceOptionEngine Class Reference
integral Heston-model variance-option engine
#include <integralhestonvarianceoptionengine.hpp>
Public Member Functions
IntegralHestonVarianceOptionEngine (const boost::shared_ptr< HestonProcess > &)
void calculate () const
Private Attributes
boost::shared_ptr< HestonProcess > process_
Detailed Description
integral Heston-model variance-option engine
This engine implements the approach described in <http://www.econ.univpm.it/recchioni/finance/w4/>.
Definition at line 38 of file integralhestonvarianceoptionengine.hpp.
Constructor & Destructor Documentation
QuantLib::IntegralHestonVarianceOptionEngine::IntegralHestonVarianceOptionEngine (const boost::shared_ptr< HestonProcess > & process)
Definition at line 362 of file integralhestonvarianceoptionengine.cpp.
References process_, and QuantLib::Observer::registerWith().
    : process_(process) {
        registerWith(process_);
    }
Member Function Documentation
void QuantLib::IntegralHestonVarianceOptionEngine::calculate () const [virtual]
Implements QuantLib::PricingEngine.
Definition at line 368 of file integralhestonvarianceoptionengine.cpp.
References QuantLib::GenericEngine< VarianceOption::arguments, VarianceOption::results >::arguments_, QuantLib::Option::Call, QuantLib::Continuous, QuantLib::Singleton< Settings >::instance(), anonymous_namespace{integralhestonvarianceoptionengine.cpp}::IvopOneDim(), anonymous_namespace{integralhestonvarianceoptionengine.cpp}::IvopTwoDim(), QuantLib::VarianceOption::arguments::maturityDate, QuantLib::VarianceOption::arguments::notional, QuantLib::VarianceOption::arguments::payoff, process_, QL_REQUIRE, QuantLib::GenericEngine< VarianceOption::arguments, VarianceOption::results >::results_, QuantLib::StrikedTypePayoff::strike(), and QuantLib::Instrument::results::value.
{
        QL_REQUIRE(process_->dividendYield().empty(),
                   "this engine does not manage dividend yields");
        Handle<YieldTermStructure> riskFreeRate = process_->riskFreeRate();
        Real epsilon = process_->sigma();
        Real chi = process_->kappa();
        Real theta = process_->theta();
        Real rho = process_->rho();
        Real v0 = process_->v0();
        Time tau = riskFreeRate->dayCounter().yearFraction(
                                        Settings::instance().evaluationDate(),
                                        arguments_.maturityDate);
        Rate r = riskFreeRate->zeroRate(arguments_.maturityDate,
                                        riskFreeRate->dayCounter(),
                                        Continuous);
        boost::shared_ptr<PlainVanillaPayoff> plainPayoff =
            boost::dynamic_pointer_cast<PlainVanillaPayoff>(arguments_.payoff);
        if (plainPayoff && plainPayoff->optionType() == Option::Call) {
            // a specialization for Call options is available
            Real strike = plainPayoff->strike();
            results_.value = IvopOneDim(epsilon, chi, theta, rho,
                                        v0, strike, tau, r)
                * arguments_.notional;
        } else {
            results_.value = IvopTwoDim(epsilon, chi, theta, rho, v0, tau, r,
                                        payoff_adapter(arguments_.payoff))
                * arguments_.notional;
        }
    }
Member Data Documentation
boost::shared_ptr<HestonProcess> QuantLib::IntegralHestonVarianceOptionEngine::process_ [private]
Definition at line 44 of file integralhestonvarianceoptionengine.hpp.
Referenced by calculate(), and IntegralHestonVarianceOptionEngine().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/varianceoption/integralhestonvarianceoptionengine.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/varianceoption/integralhestonvarianceoptionengine.cpp