QuantLib: QuantLib::AverageBMALeg Class Reference
QuantLib::AverageBMALeg Class Reference
helper class building a sequence of average BMA coupons
#include <averagebmacoupon.hpp>
Public Member Functions
AverageBMALeg (const Schedule &schedule, const boost::shared_ptr< BMAIndex > &index)
AverageBMALeg & withNotionals (Real notional)
AverageBMALeg & withNotionals (const std::vector< Real > &notionals)
AverageBMALeg & withPaymentDayCounter (const DayCounter &)
AverageBMALeg & withPaymentAdjustment (BusinessDayConvention)
AverageBMALeg & withGearings (Real gearing)
AverageBMALeg & withGearings (const std::vector< Real > &gearings)
AverageBMALeg & withSpreads (Spread spread)
AverageBMALeg & withSpreads (const std::vector< Spread > &spreads)
operator Leg () const
Private Attributes
Schedule schedule_
boost::shared_ptr< BMAIndex > index_
std::vector< Real > notionals_
DayCounter paymentDayCounter_
BusinessDayConvention paymentAdjustment_
std::vector< Real > gearings_
std::vector< Spread > spreads_
Detailed Description
helper class building a sequence of average BMA coupons
Definition at line 83 of file averagebmacoupon.hpp.
Constructor & Destructor Documentation
QuantLib::AverageBMALeg::AverageBMALeg (const Schedule & schedule, const boost::shared_ptr< BMAIndex > & index)
Definition at line 162 of file averagebmacoupon.cpp.
    : schedule_(schedule), index_(index), paymentAdjustment_(Following) {}
Member Function Documentation
QuantLib::AverageBMALeg::operator Leg () const
Definition at line 211 of file averagebmacoupon.cpp.
References QuantLib::Calendar::adjust(), QuantLib::Schedule::calendar(), anonymous_namespace{marketmodel.cpp}::calendar, QuantLib::Schedule::date(), gearings_, QuantLib::detail::get(), index_, QuantLib::Schedule::isRegular(), notionals_, paymentAdjustment_, paymentDayCounter_, QL_REQUIRE, schedule_, QuantLib::Schedule::size(), spreads_, and QuantLib::Schedule::tenor().
{
        QL_REQUIRE(!notionals_.empty(), "no notional given");
        Leg cashflows;
        // the following is not always correct
        Calendar calendar = schedule_.calendar();
        Date refStart, start, refEnd, end;
        Date paymentDate;
        Size n = schedule_.size()-1;
        for (Size i=0; i<n; ++i) {
            refStart = start = schedule_.date(i);
            refEnd   =   end = schedule_.date(i+1);
            paymentDate = calendar.adjust(end, paymentAdjustment_);
            if (i == 0 && !schedule_.isRegular(i+1))
                refStart = calendar.adjust(end - schedule_.tenor(),
                                           paymentAdjustment_);
            if (i == n-1 && !schedule_.isRegular(i+1))
                refEnd = calendar.adjust(start + schedule_.tenor(),
                                         paymentAdjustment_);
            cashflows.push_back(boost::shared_ptr<CashFlow>(new
                AverageBMACoupon(paymentDate,
                                 detail::get(notionals_, i, notionals_.back()),
                                 start, end,
                                 index_,
                                 detail::get(gearings_, i, 1.0),
                                 detail::get(spreads_, i, 0.0),
                                 refStart, refEnd,
                                 paymentDayCounter_)));
        }
        return cashflows;
    }
AverageBMALeg & QuantLib::AverageBMALeg::withGearings (Real gearing)
Definition at line 189 of file averagebmacoupon.cpp.
References gearings_.
{
        gearings_ = std::vector<Real>(1,gearing);
        return *this;
    }
AverageBMALeg & QuantLib::AverageBMALeg::withGearings (const std::vector< Real > & gearings)
Definition at line 194 of file averagebmacoupon.cpp.
References gearings_.
{
        gearings_ = gearings;
        return *this;
    }
AverageBMALeg & QuantLib::AverageBMALeg::withNotionals (Real notional)
Definition at line 166 of file averagebmacoupon.cpp.
References notionals_.
Referenced by QuantLib::BMASwap::BMASwap().
{
        notionals_ = std::vector<Real>(1,notional);
        return *this;
    }
AverageBMALeg & QuantLib::AverageBMALeg::withNotionals (const std::vector< Real > & notionals)
Definition at line 171 of file averagebmacoupon.cpp.
References notionals_.
{
        notionals_ = notionals;
        return *this;
    }
AverageBMALeg & QuantLib::AverageBMALeg::withPaymentAdjustment (BusinessDayConvention convention)
Definition at line 183 of file averagebmacoupon.cpp.
References paymentAdjustment_.
Referenced by QuantLib::BMASwap::BMASwap().
{
        paymentAdjustment_ = convention;
        return *this;
    }
AverageBMALeg & QuantLib::AverageBMALeg::withPaymentDayCounter (const DayCounter & dayCounter)
Definition at line 177 of file averagebmacoupon.cpp.
References anonymous_namespace{marketmodel.cpp}::dayCounter, and paymentDayCounter_.
Referenced by QuantLib::BMASwap::BMASwap().
{
        paymentDayCounter_ = dayCounter;
        return *this;
    }
AverageBMALeg & QuantLib::AverageBMALeg::withSpreads (Spread spread)
Definition at line 200 of file averagebmacoupon.cpp.
References spreads_.
{
        spreads_ = std::vector<Spread>(1,spread);
        return *this;
    }
AverageBMALeg & QuantLib::AverageBMALeg::withSpreads (const std::vector< Spread > & spreads)
Definition at line 205 of file averagebmacoupon.cpp.
References spreads_.
{
        spreads_ = spreads;
        return *this;
    }
Member Data Documentation
std::vector<Real> QuantLib::AverageBMALeg::gearings_ [private]
Definition at line 102 of file averagebmacoupon.hpp.
Referenced by operator Leg(), and withGearings().
boost::shared_ptr<BMAIndex> QuantLib::AverageBMALeg::index_ [private]
Definition at line 98 of file averagebmacoupon.hpp.
Referenced by operator Leg().
std::vector<Real> QuantLib::AverageBMALeg::notionals_ [private]
Definition at line 99 of file averagebmacoupon.hpp.
Referenced by operator Leg(), and withNotionals().
BusinessDayConvention QuantLib::AverageBMALeg::paymentAdjustment_ [private]
Definition at line 101 of file averagebmacoupon.hpp.
Referenced by operator Leg(), and withPaymentAdjustment().
DayCounter QuantLib::AverageBMALeg::paymentDayCounter_ [private]
Definition at line 100 of file averagebmacoupon.hpp.
Referenced by operator Leg(), and withPaymentDayCounter().
Schedule QuantLib::AverageBMALeg::schedule_ [private]
Definition at line 97 of file averagebmacoupon.hpp.
Referenced by operator Leg().
std::vector<Spread> QuantLib::AverageBMALeg::spreads_ [private]
Definition at line 103 of file averagebmacoupon.hpp.
Referenced by operator Leg(), and withSpreads().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/averagebmacoupon.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/averagebmacoupon.cpp