QuantLib: QuantLib::ForwardRateStructure Class Reference
QuantLib::ForwardRateStructure Class Reference
Forward-rate term structure
#include <forwardstructure.hpp>
Public Member Functions
Constructors
See the TermStructure documentation for issues regarding constructors.
ForwardRateStructure (const DayCounter &dayCounter=DayCounter(), const std::vector< Handle< Quote > > &jumps=std::vector< Handle< Quote > >(), const std::vector< Date > &jumpDates=std::vector< Date >())
ForwardRateStructure (const Date &referenceDate, const Calendar &cal=Calendar(), const DayCounter &dayCounter=DayCounter(), const std::vector< Handle< Quote > > &jumps=std::vector< Handle< Quote > >(), const std::vector< Date > &jumpDates=std::vector< Date >())
ForwardRateStructure (Natural settlementDays, const Calendar &cal, const DayCounter &dayCounter=DayCounter(), const std::vector< Handle< Quote > > &jumps=std::vector< Handle< Quote > >(), const std::vector< Date > &jumpDates=std::vector< Date >())
Protected Member Functions
Calculations
These methods must be implemented in derived classes to perform the actual calculations. When they are called, range check has already been performed; therefore, they must assume that extrapolation is required.
virtual Rate forwardImpl (Time) const =0
instantaneous forward-rate calculation
virtual Rate zeroYieldImpl (Time) const
YieldTermStructure implementation
DiscountFactor discountImpl (Time) const
Detailed Description
Forward-rate term structure
This abstract class acts as an adapter to YieldTermStructure allowing the programmer to implement only the forwardImpl(Time) method in derived classes.
Zero yields and discounts are calculated from forwards.
Forward rates are assumed to be annual continuous compounding.
Definition at line 44 of file forwardstructure.hpp.
Constructor & Destructor Documentation
QuantLib::ForwardRateStructure::ForwardRateStructure (const DayCounter & dayCounter = DayCounter(), const std::vector< Handle< Quote > > & jumps = std::vector<Handle<Quote> >(), const std::vector< Date > & jumpDates = std::vector<Date>())
Definition at line 26 of file forwardstructure.cpp.
    : YieldTermStructure(dc, jumps, jumpDates) {}
QuantLib::ForwardRateStructure::ForwardRateStructure (const Date & referenceDate, const Calendar & cal = Calendar(), const DayCounter & dayCounter = DayCounter(), const std::vector< Handle< Quote > > & jumps = std::vector<Handle<Quote> >(), const std::vector< Date > & jumpDates = std::vector<Date>())
Definition at line 32 of file forwardstructure.cpp.
    : YieldTermStructure(refDate, cal, dc, jumps, jumpDates) {}
QuantLib::ForwardRateStructure::ForwardRateStructure (Natural settlementDays, const Calendar & cal, const DayCounter & dayCounter = DayCounter(), const std::vector< Handle< Quote > > & jumps = std::vector<Handle<Quote> >(), const std::vector< Date > & jumpDates = std::vector<Date>())
Definition at line 40 of file forwardstructure.cpp.
    : YieldTermStructure(settlDays, cal, dc, jumps, jumpDates) {}
Member Function Documentation
DiscountFactor QuantLib::ForwardRateStructure::discountImpl (Time t) const [inline, protected, virtual]
Returns the discount factor for the given date calculating it from the zero rate as \(d(t) = \exp \left(-z(t) t \right) \)
Implements QuantLib::YieldTermStructure.
Definition at line 105 of file forwardstructure.hpp.
References zeroYieldImpl().
{
        if (t == 0.0)     // this acts as a safe guard in cases where
            return 1.0;   // zeroYieldImpl(0.0) would throw.
        Rate r = zeroYieldImpl(t);
        return DiscountFactor(std::exp(-r*t));
    }
virtual Rate QuantLib::ForwardRateStructure::forwardImpl (Time) const [protected, pure virtual]
instantaneous forward-rate calculation
Implemented in QuantLib::InterpolatedForwardCurve< Interpolator >, and QuantLib::ForwardSpreadedTermStructure.
Referenced by zeroYieldImpl().
Rate QuantLib::ForwardRateStructure::zeroYieldImpl (Time t) const [protected, virtual]
Returns the zero yield rate for the given date calculating it from the instantaneous forward rate \(f(t) \) as
\[ z(t) = \int_0^t f(\tau) d\tau \]
Warning:
This default implementation uses an highly inefficient and possibly wildly inaccurate numerical integration. Derived classes should override it if a more efficient implementation is available.
Reimplemented in QuantLib::InterpolatedForwardCurve< Interpolator >, and QuantLib::ForwardSpreadedTermStructure.
Definition at line 48 of file forwardstructure.cpp.
References QuantLib::anonymous_namespace{yieldtermstructure.cpp}::dt, forwardImpl(), anonymous_namespace{matrices.cpp}::N, and anonymous_namespace{quantlibbenchmark.cpp}::t.
Referenced by discountImpl().
{
        if (t == 0.0)
            return forwardImpl(0.0);
        // implement smarter integration if plan to use the following code
        Rate sum = 0.5*forwardImpl(0.0);
        Size N = 1000;
        Time dt = t/N;
        for (Time i=dt; i<t; i+=dt)
            sum += forwardImpl(i);
        sum += 0.5*forwardImpl(t);
        return Rate(sum*dt/t);
    }
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/yield/forwardstructure.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/yield/forwardstructure.cpp