QuantLib: QuantLib::IborLeg Class Reference
QuantLib::IborLeg Class Reference
helper class building a sequence of capped/floored ibor-rate coupons
#include <iborcoupon.hpp>
Public Member Functions
IborLeg (const Schedule &schedule, const boost::shared_ptr< IborIndex > &index)
IborLeg & withNotionals (Real notional)
IborLeg & withNotionals (const std::vector< Real > &notionals)
IborLeg & withPaymentDayCounter (const DayCounter &)
IborLeg & withPaymentAdjustment (BusinessDayConvention)
IborLeg & withFixingDays (Natural fixingDays)
IborLeg & withFixingDays (const std::vector< Natural > &fixingDays)
IborLeg & withGearings (Real gearing)
IborLeg & withGearings (const std::vector< Real > &gearings)
IborLeg & withSpreads (Spread spread)
IborLeg & withSpreads (const std::vector< Spread > &spreads)
IborLeg & withCaps (Rate cap)
IborLeg & withCaps (const std::vector< Rate > &caps)
IborLeg & withFloors (Rate floor)
IborLeg & withFloors (const std::vector< Rate > &floors)
IborLeg & inArrears (bool flag=true)
IborLeg & withZeroPayments (bool flag=true)
operator Leg () const
Private Attributes
Schedule schedule_
boost::shared_ptr< IborIndex > index_
std::vector< Real > notionals_
DayCounter paymentDayCounter_
BusinessDayConvention paymentAdjustment_
std::vector< Natural > fixingDays_
std::vector< Real > gearings_
std::vector< Spread > spreads_
std::vector< Rate > caps_
std::vector< Rate > floors_
bool inArrears_
bool zeroPayments_
Detailed Description
helper class building a sequence of capped/floored ibor-rate coupons
Definition at line 74 of file iborcoupon.hpp.
Constructor & Destructor Documentation
QuantLib::IborLeg::IborLeg (const Schedule & schedule, const boost::shared_ptr< IborIndex > & index)
Definition at line 131 of file iborcoupon.cpp.
    : schedule_(schedule), index_(index),
      paymentAdjustment_(Following),
      inArrears_(false), zeroPayments_(false) {}
Member Function Documentation
IborLeg & QuantLib::IborLeg::inArrears (bool flag = true)
Definition at line 207 of file iborcoupon.cpp.
References inArrears_.
Referenced by QuantLib::AmortizingFloatingRateBond::AmortizingFloatingRateBond(), QuantLib::FloatingRateBond::FloatingRateBond(), AssetSwapTest::testGenericBondImplied(), SwapTest::testInArrears(), AssetSwapTest::testMASWWithGenericBond(), AssetSwapTest::testSpecializedBondVsGenericBond(), AssetSwapTest::testSpecializedBondVsGenericBondUsingAsw(), and AssetSwapTest::testZSpreadWithGenericBond().
{
        inArrears_ = flag;
        return *this;
    }
QuantLib::IborLeg::operator Leg () const
Definition at line 217 of file iborcoupon.cpp.
References caps_, fixingDays_, floors_, gearings_, inArrears_, index_, notionals_, paymentAdjustment_, paymentDayCounter_, schedule_, QuantLib::setCouponPricer(), spreads_, and zeroPayments_.
{
        Leg leg = FloatingLeg<IborIndex, IborCoupon, CappedFlooredIborCoupon>(
                         schedule_, notionals_, index_, paymentDayCounter_,
                         paymentAdjustment_, fixingDays_, gearings_, spreads_,
                         caps_, floors_, inArrears_, zeroPayments_);
        if (caps_.empty() && floors_.empty() && !inArrears_) {
            shared_ptr<IborCouponPricer> pricer(new BlackIborCouponPricer);
            setCouponPricer(leg, pricer);
        }
        return leg;
    }
IborLeg & QuantLib::IborLeg::withCaps (Rate cap)
Definition at line 187 of file iborcoupon.cpp.
References caps_.
Referenced by QuantLib::AmortizingFloatingRateBond::AmortizingFloatingRateBond(), QuantLib::FloatingRateBond::FloatingRateBond(), and anonymous_namespace{capflooredcoupon.cpp}::CommonVars::makeCapFlooredLeg().
{
        caps_ = std::vector<Rate>(1,cap);
        return *this;
    }
IborLeg & QuantLib::IborLeg::withCaps (const std::vector< Rate > & caps)
Definition at line 192 of file iborcoupon.cpp.
References caps_.
{
        caps_ = caps;
        return *this;
    }
IborLeg & QuantLib::IborLeg::withFixingDays (Natural fixingDays)
Definition at line 157 of file iborcoupon.cpp.
References fixingDays_.
Referenced by QuantLib::AmortizingFloatingRateBond::AmortizingFloatingRateBond(), QuantLib::BMASwap::BMASwap(), QuantLib::CPISwap::CPISwap(), QuantLib::FloatingRateBond::FloatingRateBond(), anonymous_namespace{capflooredcoupon.cpp}::CommonVars::makeCapFlooredLeg(), anonymous_namespace{capflooredcoupon.cpp}::CommonVars::makeFloatingLeg(), anonymous_namespace{capfloor.cpp}::CommonVars::makeLeg(), QuantLib::MakeCms::operator boost::shared_ptr< Swap >(), AssetSwapTest::testGenericBondImplied(), SwapTest::testInArrears(), AssetSwapTest::testMASWWithGenericBond(), AssetSwapTest::testSpecializedBondVsGenericBond(), AssetSwapTest::testSpecializedBondVsGenericBondUsingAsw(), and AssetSwapTest::testZSpreadWithGenericBond().
{
        fixingDays_ = std::vector<Natural>(1,fixingDays);
        return *this;
    }
IborLeg & QuantLib::IborLeg::withFixingDays (const std::vector< Natural > & fixingDays)
Definition at line 162 of file iborcoupon.cpp.
References fixingDays_.
{
        fixingDays_ = fixingDays;
        return *this;
    }
IborLeg & QuantLib::IborLeg::withFloors (Rate floor)
Definition at line 197 of file iborcoupon.cpp.
References floors_.
Referenced by QuantLib::AmortizingFloatingRateBond::AmortizingFloatingRateBond(), QuantLib::FloatingRateBond::FloatingRateBond(), and anonymous_namespace{capflooredcoupon.cpp}::CommonVars::makeCapFlooredLeg().
{
        floors_ = std::vector<Rate>(1,floor);
        return *this;
    }
IborLeg & QuantLib::IborLeg::withFloors (const std::vector< Rate > & floors)
Definition at line 202 of file iborcoupon.cpp.
References floors_.
{
        floors_ = floors;
        return *this;
    }
IborLeg & QuantLib::IborLeg::withGearings (Real gearing)
Definition at line 167 of file iborcoupon.cpp.
References gearings_.
Referenced by QuantLib::AmortizingFloatingRateBond::AmortizingFloatingRateBond(), QuantLib::AssetSwap::AssetSwap(), QuantLib::FloatingRateBond::FloatingRateBond(), anonymous_namespace{capflooredcoupon.cpp}::CommonVars::makeCapFlooredLeg(), anonymous_namespace{capflooredcoupon.cpp}::CommonVars::makeFloatingLeg(), and SwapTest::testInArrears().
{
        gearings_ = std::vector<Real>(1,gearing);
        return *this;
    }
IborLeg & QuantLib::IborLeg::withGearings (const std::vector< Real > & gearings)
Definition at line 172 of file iborcoupon.cpp.
References gearings_.
{
        gearings_ = gearings;
        return *this;
    }
IborLeg & QuantLib::IborLeg::withNotionals (Real notional)
Definition at line 137 of file iborcoupon.cpp.
References notionals_.
Referenced by QuantLib::AmortizingFloatingRateBond::AmortizingFloatingRateBond(), QuantLib::AssetSwap::AssetSwap(), QuantLib::BMASwap::BMASwap(), QuantLib::CapHelper::CapHelper(), QuantLib::LiborForwardModelProcess::cashFlows(), QuantLib::ConvertibleFloatingRateBond::ConvertibleFloatingRateBond(), QuantLib::CPISwap::CPISwap(), QuantLib::FloatingRateBond::FloatingRateBond(), anonymous_namespace{capflooredcoupon.cpp}::CommonVars::makeCapFlooredLeg(), anonymous_namespace{capflooredcoupon.cpp}::CommonVars::makeFloatingLeg(), anonymous_namespace{capfloor.cpp}::CommonVars::makeLeg(), QuantLib::MakeCms::operator boost::shared_ptr< Swap >(), AssetSwapTest::testGenericBondImplied(), SwapTest::testInArrears(), AssetSwapTest::testMASWWithGenericBond(), AssetSwapTest::testSpecializedBondVsGenericBond(), AssetSwapTest::testSpecializedBondVsGenericBondUsingAsw(), AssetSwapTest::testZSpreadWithGenericBond(), and QuantLib::VanillaSwap::VanillaSwap().
{
        notionals_ = std::vector<Real>(1,notional);
        return *this;
    }
IborLeg & QuantLib::IborLeg::withNotionals (const std::vector< Real > & notionals)
Definition at line 142 of file iborcoupon.cpp.
References notionals_.
{
        notionals_ = notionals;
        return *this;
    }
IborLeg & QuantLib::IborLeg::withPaymentAdjustment (BusinessDayConvention convention)
Definition at line 152 of file iborcoupon.cpp.
References paymentAdjustment_.
Referenced by QuantLib::AmortizingFloatingRateBond::AmortizingFloatingRateBond(), QuantLib::AssetSwap::AssetSwap(), QuantLib::BMASwap::BMASwap(), QuantLib::CapHelper::CapHelper(), QuantLib::ConvertibleFloatingRateBond::ConvertibleFloatingRateBond(), QuantLib::CPISwap::CPISwap(), QuantLib::FloatingRateBond::FloatingRateBond(), QuantLib::MakeCms::operator boost::shared_ptr< Swap >(), AssetSwapTest::testGenericBondImplied(), AssetSwapTest::testMASWWithGenericBond(), AssetSwapTest::testSpecializedBondVsGenericBond(), AssetSwapTest::testSpecializedBondVsGenericBondUsingAsw(), AssetSwapTest::testZSpreadWithGenericBond(), and QuantLib::VanillaSwap::VanillaSwap().
{
        paymentAdjustment_ = convention;
        return *this;
    }
IborLeg & QuantLib::IborLeg::withPaymentDayCounter (const DayCounter & dayCounter)
Definition at line 147 of file iborcoupon.cpp.
References anonymous_namespace{marketmodel.cpp}::dayCounter, and paymentDayCounter_.
Referenced by QuantLib::AmortizingFloatingRateBond::AmortizingFloatingRateBond(), QuantLib::AssetSwap::AssetSwap(), QuantLib::BMASwap::BMASwap(), QuantLib::LiborForwardModelProcess::cashFlows(), QuantLib::ConvertibleFloatingRateBond::ConvertibleFloatingRateBond(), QuantLib::CPISwap::CPISwap(), QuantLib::FloatingRateBond::FloatingRateBond(), anonymous_namespace{capflooredcoupon.cpp}::CommonVars::makeCapFlooredLeg(), anonymous_namespace{capflooredcoupon.cpp}::CommonVars::makeFloatingLeg(), anonymous_namespace{capfloor.cpp}::CommonVars::makeLeg(), QuantLib::MakeCms::operator boost::shared_ptr< Swap >(), AssetSwapTest::testGenericBondImplied(), SwapTest::testInArrears(), AssetSwapTest::testMASWWithGenericBond(), AssetSwapTest::testSpecializedBondVsGenericBond(), AssetSwapTest::testSpecializedBondVsGenericBondUsingAsw(), AssetSwapTest::testZSpreadWithGenericBond(), and QuantLib::VanillaSwap::VanillaSwap().
{
        paymentDayCounter_ = dayCounter;
        return *this;
    }
IborLeg & QuantLib::IborLeg::withSpreads (Spread spread)
Definition at line 177 of file iborcoupon.cpp.
References spreads_.
Referenced by QuantLib::AmortizingFloatingRateBond::AmortizingFloatingRateBond(), QuantLib::AssetSwap::AssetSwap(), QuantLib::BMASwap::BMASwap(), QuantLib::ConvertibleFloatingRateBond::ConvertibleFloatingRateBond(), QuantLib::CPISwap::CPISwap(), QuantLib::FloatingRateBond::FloatingRateBond(), anonymous_namespace{capflooredcoupon.cpp}::CommonVars::makeCapFlooredLeg(), anonymous_namespace{capflooredcoupon.cpp}::CommonVars::makeFloatingLeg(), AssetSwapTest::testGenericBondImplied(), SwapTest::testInArrears(), AssetSwapTest::testMASWWithGenericBond(), AssetSwapTest::testSpecializedBondVsGenericBond(), AssetSwapTest::testSpecializedBondVsGenericBondUsingAsw(), AssetSwapTest::testZSpreadWithGenericBond(), and QuantLib::VanillaSwap::VanillaSwap().
{
        spreads_ = std::vector<Spread>(1,spread);
        return *this;
    }
IborLeg & QuantLib::IborLeg::withSpreads (const std::vector< Spread > & spreads)
Definition at line 182 of file iborcoupon.cpp.
References spreads_.
{
        spreads_ = spreads;
        return *this;
    }
IborLeg & QuantLib::IborLeg::withZeroPayments (bool flag = true)
Definition at line 212 of file iborcoupon.cpp.
References zeroPayments_.
{
        zeroPayments_ = flag;
        return *this;
    }
Member Data Documentation
std::vector<Rate> QuantLib::IborLeg::caps_ [private]
Definition at line 104 of file iborcoupon.hpp.
Referenced by operator Leg(), and withCaps().
std::vector<Natural> QuantLib::IborLeg::fixingDays_ [private]
Definition at line 101 of file iborcoupon.hpp.
Referenced by operator Leg(), and withFixingDays().
std::vector<Rate> QuantLib::IborLeg::floors_ [private]
Definition at line 104 of file iborcoupon.hpp.
Referenced by operator Leg(), and withFloors().
std::vector<Real> QuantLib::IborLeg::gearings_ [private]
Definition at line 102 of file iborcoupon.hpp.
Referenced by operator Leg(), and withGearings().
bool QuantLib::IborLeg::inArrears_ [private]
Definition at line 105 of file iborcoupon.hpp.
Referenced by inArrears(), and operator Leg().
boost::shared_ptr<IborIndex> QuantLib::IborLeg::index_ [private]
Definition at line 97 of file iborcoupon.hpp.
Referenced by operator Leg().
std::vector<Real> QuantLib::IborLeg::notionals_ [private]
Definition at line 98 of file iborcoupon.hpp.
Referenced by operator Leg(), and withNotionals().
BusinessDayConvention QuantLib::IborLeg::paymentAdjustment_ [private]
Definition at line 100 of file iborcoupon.hpp.
Referenced by operator Leg(), and withPaymentAdjustment().
DayCounter QuantLib::IborLeg::paymentDayCounter_ [private]
Definition at line 99 of file iborcoupon.hpp.
Referenced by operator Leg(), and withPaymentDayCounter().
Schedule QuantLib::IborLeg::schedule_ [private]
Definition at line 96 of file iborcoupon.hpp.
Referenced by operator Leg().
std::vector<Spread> QuantLib::IborLeg::spreads_ [private]
Definition at line 103 of file iborcoupon.hpp.
Referenced by operator Leg(), and withSpreads().
bool QuantLib::IborLeg::zeroPayments_ [private]
Definition at line 105 of file iborcoupon.hpp.
Referenced by operator Leg(), and withZeroPayments().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/iborcoupon.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/iborcoupon.cpp