QuantLib: QuantLib::TimeHomogeneousForwardCorrelation Class Reference
QuantLib::TimeHomogeneousForwardCorrelation Class Reference
#include <timehomogeneousforwardcorrelation.hpp>
Public Member Functions
TimeHomogeneousForwardCorrelation (const Matrix &fwdCorrelation, const std::vector< Time > &rateTimes)
const std::vector< Time > & times () const
const std::vector< Time > & rateTimes () const
const std::vector< Matrix > & correlations () const
Size numberOfRates () const
Static Public Member Functions
static std::vector< Matrix > evolvedMatrices (const Matrix &fwdCorrelation)
Private Attributes
Size numberOfRates_
Matrix fwdCorrelation_
std::vector< Time > rateTimes_
std::vector< Time > times_
std::vector< Matrix > correlations_
Detailed Description
Definition at line 30 of file timehomogeneousforwardcorrelation.hpp.
Constructor & Destructor Documentation
QuantLib::TimeHomogeneousForwardCorrelation::TimeHomogeneousForwardCorrelation (const Matrix & fwdCorrelation, const std::vector< Time > & rateTimes)
Definition at line 28 of file timehomogeneousforwardcorrelation.cpp.
References QuantLib::checkIncreasingTimes(), QuantLib::Matrix::columns(), correlations_, evolvedMatrices(), fwdCorrelation_, numberOfRates_, QL_REQUIRE, QuantLib::Matrix::rows(), and times_.
    : numberOfRates_(rateTimes.empty() ? 0 : rateTimes.size()-1),
      fwdCorrelation_(fwdCorrelation),
      rateTimes_(rateTimes),
      times_(numberOfRates_) {
        checkIncreasingTimes(rateTimes);
        QL_REQUIRE(numberOfRates_>=1,
                   "Rate times must contain at least two values");
        QL_REQUIRE(numberOfRates_==fwdCorrelation.rows(),
                   "mismatch between number of rates (" << numberOfRates_ <<
                   ") and fwdCorrelation rows (" << fwdCorrelation.rows() << ")");
        QL_REQUIRE(numberOfRates_==fwdCorrelation.columns(),
                   "mismatch between number of rates (" << numberOfRates_ <<
                   ") and fwdCorrelation columns (" << fwdCorrelation.columns() << ")");
        std::copy(rateTimes.begin(), rateTimes.end()-1, times_.begin());
        correlations_ = evolvedMatrices(fwdCorrelation_);
    }
Member Function Documentation
const std::vector< Matrix > & QuantLib::TimeHomogeneousForwardCorrelation::correlations () const [virtual]
Implements QuantLib::PiecewiseConstantCorrelation.
Definition at line 82 of file timehomogeneousforwardcorrelation.cpp.
References correlations_.
Referenced by evolvedMatrices().
{
        return correlations_;
    }
std::vector< Matrix > QuantLib::TimeHomogeneousForwardCorrelation::evolvedMatrices (const Matrix & fwdCorrelation) [static]
Definition at line 50 of file timehomogeneousforwardcorrelation.cpp.
References correlations(), numberOfRates(), and QuantLib::Matrix::rows().
Referenced by QuantLib::ExponentialForwardCorrelation::ExponentialForwardCorrelation(), and TimeHomogeneousForwardCorrelation().
{
        Size numberOfRates = fwdCorrelation.rows();
        std::vector<Matrix> correlations(numberOfRates, Matrix(numberOfRates,
                                                               numberOfRates,
                                                               0.0));
        for (Size k=0; k<correlations.size(); ++k) {
            // proper diagonal values
            for (Size i=k; i<numberOfRates; ++i)
                correlations[k][i][i] = 1.0;
            // copy only time homogeneous values
            for (Size i=k; i<numberOfRates; ++i) {
                for (Size j=k; j<i; ++j) {
                    correlations[k][i][j] = correlations[k][j][i] =
                        fwdCorrelation[i-k][j-k];
                }
            }
        }
        return correlations;
    }
Size QuantLib::TimeHomogeneousForwardCorrelation::numberOfRates () const [virtual]
Implements QuantLib::PiecewiseConstantCorrelation.
Definition at line 86 of file timehomogeneousforwardcorrelation.cpp.
References numberOfRates_.
Referenced by evolvedMatrices().
{
        return numberOfRates_;
    }
const std::vector< Time > & QuantLib::TimeHomogeneousForwardCorrelation::rateTimes () const [virtual]
Implements QuantLib::PiecewiseConstantCorrelation.
Definition at line 77 of file timehomogeneousforwardcorrelation.cpp.
References rateTimes_.
{
        return rateTimes_;
    }
const std::vector< Time > & QuantLib::TimeHomogeneousForwardCorrelation::times () const [virtual]
Implements QuantLib::PiecewiseConstantCorrelation.
Definition at line 72 of file timehomogeneousforwardcorrelation.cpp.
References times_.
{
        return times_;
    }
Member Data Documentation
std::vector<Matrix> QuantLib::TimeHomogeneousForwardCorrelation::correlations_ [private]
Definition at line 45 of file timehomogeneousforwardcorrelation.hpp.
Referenced by correlations(), and TimeHomogeneousForwardCorrelation().
Matrix QuantLib::TimeHomogeneousForwardCorrelation::fwdCorrelation_ [private]
Definition at line 43 of file timehomogeneousforwardcorrelation.hpp.
Referenced by TimeHomogeneousForwardCorrelation().
Size QuantLib::TimeHomogeneousForwardCorrelation::numberOfRates_ [private]
Definition at line 42 of file timehomogeneousforwardcorrelation.hpp.
Referenced by numberOfRates(), and TimeHomogeneousForwardCorrelation().
std::vector<Time> QuantLib::TimeHomogeneousForwardCorrelation::rateTimes_ [private]
Definition at line 44 of file timehomogeneousforwardcorrelation.hpp.
Referenced by rateTimes().
std::vector<Time> QuantLib::TimeHomogeneousForwardCorrelation::times_ [private]
Definition at line 44 of file timehomogeneousforwardcorrelation.hpp.
Referenced by TimeHomogeneousForwardCorrelation(), and times().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/correlations/timehomogeneousforwardcorrelation.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/correlations/timehomogeneousforwardcorrelation.cpp