QuantLib: QuoteTest Class Reference
QuoteTest Class Reference
#include <quotes.hpp>
Static Public Member Functions
static void testObservable ()
static void testObservableHandle ()
static void testDerived ()
static void testComposite ()
static void testForwardValueQuoteAndImpliedStdevQuote ()
static
boost::unit_test_framework::test_suite * suite ()
Detailed Description
Definition at line 28 of file quotes.hpp.
Member Function Documentation
test_suite * QuoteTest::suite () [static]
Definition at line 199 of file quotes.cpp.
References QUANTLIB_TEST_CASE, testComposite(), testDerived(), testForwardValueQuoteAndImpliedStdevQuote(), testObservable(), and testObservableHandle().
Referenced by init_unit_test_suite().
{
    test_suite* suite = BOOST_TEST_SUITE("Quote tests");
    suite->add(QUANTLIB_TEST_CASE(&QuoteTest::testObservable));
    suite->add(QUANTLIB_TEST_CASE(&QuoteTest::testObservableHandle));
    suite->add(QUANTLIB_TEST_CASE(&QuoteTest::testDerived));
    suite->add(QUANTLIB_TEST_CASE(&QuoteTest::testComposite));
    suite->add(QUANTLIB_TEST_CASE(
                      &QuoteTest::testForwardValueQuoteAndImpliedStdevQuote));
    return suite;
}
void QuoteTest::testComposite () [static]
Definition at line 104 of file quotes.cpp.
References anonymous_namespace{quotes.cpp}::add(), anonymous_namespace{quotes.cpp}::mul(), anonymous_namespace{quotes.cpp}::sub(), and QuantLib::CompositeQuote< BinaryFunction >::value().
Referenced by suite().
{
    BOOST_MESSAGE("Testing composite quotes...");
    typedef Real (*binary_f)(Real,Real);
    binary_f funcs[3] = { add, mul, sub };
    boost::shared_ptr<Quote> me1(new SimpleQuote(12.0)),
                             me2(new SimpleQuote(13.0));
    Handle<Quote> h1(me1), h2(me2);
    for (Integer i=0; i<3; i++) {
        CompositeQuote<binary_f> composite(h1,h2,funcs[i]);
        Real x = composite.value(),
             y = funcs[i](me1->value(),me2->value());
        if (std::fabs(x-y) > 1.0e-10)
            BOOST_FAIL("composite quote yields " << x << "\n"
                       << "function result is " << y);
    }
}
void QuoteTest::testDerived () [static]
Definition at line 84 of file quotes.cpp.
References anonymous_namespace{quotes.cpp}::add10(), anonymous_namespace{quotes.cpp}::mul10(), anonymous_namespace{quotes.cpp}::sub10(), and QuantLib::DerivedQuote< UnaryFunction >::value().
Referenced by suite().
{
    BOOST_MESSAGE("Testing derived quotes...");
    typedef Real (*unary_f)(Real);
    unary_f funcs[3] = { add10, mul10, sub10 };
    boost::shared_ptr<Quote> me(new SimpleQuote(17.0));
    Handle<Quote> h(me);
    for (Integer i=0; i<3; i++) {
        DerivedQuote<unary_f> derived(h,funcs[i]);
        Real x = derived.value(),
             y = funcs[i](me->value());
        if (std::fabs(x-y) > 1.0e-10)
            BOOST_FAIL("derived quote yields " << x << "\n"
                       << "function result is " << y);
    }
}
void QuoteTest::testForwardValueQuoteAndImpliedStdevQuote () [static]
Definition at line 125 of file quotes.cpp.
References QuantLib::Calendar::advance(), QuantLib::blackFormulaImpliedStdDev(), anonymous_namespace{marketmodel.cpp}::calendar, QuantLib::Option::Call, QuantLib::Settings::evaluationDate(), anonymous_namespace{interpolations.cpp}::f(), QuantLib::Singleton< Settings >::instance(), QuantLib::Flag::isUp(), QuantLib::Flag::lower(), QuantLib::Observer::registerWith(), QuantLib::Observer::unregisterWith(), and QuantLib::Years.
Referenced by suite().
{
    BOOST_MESSAGE(
            "Testing forward-value and implied-standard-deviation quotes...");
    Real forwardRate = .05;
    DayCounter dc = ActualActual();
    Calendar calendar = TARGET();
    boost::shared_ptr<SimpleQuote> forwardQuote(new SimpleQuote(forwardRate));
    Handle<Quote> forwardHandle(forwardQuote);
    Date evaluationDate = Settings::instance().evaluationDate();
    boost::shared_ptr<YieldTermStructure>yc (new FlatForward(
        evaluationDate, forwardHandle, dc));
    Handle<YieldTermStructure> ycHandle(yc);
    Period euriborTenor(1,Years);
    boost::shared_ptr<Index> euribor(new Euribor(euriborTenor, ycHandle));
    Date fixingDate = calendar.advance(evaluationDate, euriborTenor);
    boost::shared_ptr<ForwardValueQuote> forwardValueQuote( new
        ForwardValueQuote(euribor, fixingDate));
    Rate forwardValue =  forwardValueQuote->value();
    Rate expectedForwardValue = euribor->fixing(fixingDate, true);
    // we test if the forward value given by the quote is consistent
    // with the one directly given by the index
    if (std::fabs(forwardValue-expectedForwardValue) > 1.0e-15)
        BOOST_FAIL("Foward Value Quote quote yields " << forwardValue << "\n"
                   << "expected result is " << expectedForwardValue);
    // then we test the observer/observable chain
    Flag f;
    f.registerWith(forwardValueQuote);
    forwardQuote->setValue(0.04);
    if (!f.isUp())
        BOOST_FAIL("Observer was not notified of quote change");
    // and we retest if the values are still matching
    forwardValue =  forwardValueQuote->value();
    expectedForwardValue = euribor->fixing(fixingDate, true);
    if (std::fabs(forwardValue-expectedForwardValue) > 1.0e-15)
        BOOST_FAIL("Foward Value Quote quote yields " << forwardValue << "\n"
                   << "expected result is " << expectedForwardValue);
    // we test the ImpliedStdevQuote class
    f.unregisterWith(forwardValueQuote);
    f.lower();
    Real price = 0.02;
    Rate strike = 0.04;
    Volatility guess = .15;
    Real accuracy = 1.0e-6;
    Option::Type optionType = Option::Call;
    boost::shared_ptr<SimpleQuote> priceQuote(new SimpleQuote(price));
    Handle<Quote> priceHandle(priceQuote);
    boost::shared_ptr<ImpliedStdDevQuote> impliedStdevQuote(new
        ImpliedStdDevQuote(optionType, forwardHandle, priceHandle,
                           strike, guess, accuracy));
    Real impliedStdev = impliedStdevQuote->value();
    Real expectedImpliedStdev =
        blackFormulaImpliedStdDev(optionType, strike,
                                  forwardQuote->value(), price,
                                  1.0, 0.0, guess, 1.0e-6);
    if (std::fabs(impliedStdev-expectedImpliedStdev) > 1.0e-15)
        BOOST_FAIL("\nimpliedStdevQuote yields :" << impliedStdev <<
                   "\nexpected result is       :" << expectedImpliedStdev);
    // then we test the observer/observable chain
    boost::shared_ptr<Quote> quote = impliedStdevQuote;
    f.registerWith(quote);
    forwardQuote->setValue(0.05);
    if (!f.isUp())
        BOOST_FAIL("Observer was not notified of quote change");
    quote->value();
    f.lower();
    quote->value();
    priceQuote->setValue(0.11);
    if (!f.isUp())
        BOOST_FAIL("Observer was not notified of quote change");
}
void QuoteTest::testObservable () [static]
Definition at line 49 of file quotes.cpp.
References anonymous_namespace{interpolations.cpp}::f(), QuantLib::Flag::isUp(), and QuantLib::Observer::registerWith().
Referenced by suite().
{
    BOOST_MESSAGE("Testing observability of quotes...");
    boost::shared_ptr<SimpleQuote> me(new SimpleQuote(0.0));
    Flag f;
    f.registerWith(me);
    me->setValue(3.14);
    if (!f.isUp())
        BOOST_FAIL("Observer was not notified of quote change");
}
void QuoteTest::testObservableHandle () [static]
Definition at line 63 of file quotes.cpp.
References anonymous_namespace{interpolations.cpp}::f(), QuantLib::Flag::isUp(), QuantLib::RelinkableHandle< T >::linkTo(), QuantLib::Flag::lower(), and QuantLib::Observer::registerWith().
Referenced by suite().
{
    BOOST_MESSAGE("Testing observability of quote handles...");
    boost::shared_ptr<SimpleQuote> me1(new SimpleQuote(0.0));
    RelinkableHandle<Quote> h(me1);
    Flag f;
    f.registerWith(h);
    me1->setValue(3.14);
    if (!f.isUp())
        BOOST_FAIL("Observer was not notified of quote change");
    f.lower();
    boost::shared_ptr<SimpleQuote> me2(new SimpleQuote(0.0));
    h.linkTo(me2);
    if (!f.isUp())
        BOOST_FAIL("Observer was not notified of quote change");
}
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/quotes.hpp
/home/deriversatile/QuantLib/QuantLibQt/test-suite/quotes.cpp