QuantLib: QuantLib::SimpleQuote Class Reference
QuantLib::SimpleQuote Class Reference
market element returning a stored value
#include <simplequote.hpp>
Public Member Functions
SimpleQuote (Real value=Null< Real >())
Quote interface
Real value () const
returns the current value
bool isValid () const
returns true if the Quote holds a valid value
Modifiers
Real setValue (Real value=Null< Real >())
returns the difference between the new value and the old value
void reset ()
Private Attributes
Real value_
Detailed Description
market element returning a stored value
Definition at line 33 of file simplequote.hpp.
Constructor & Destructor Documentation
QuantLib::SimpleQuote::SimpleQuote (Real value = Null<Real>()) [inline]
Definition at line 53 of file simplequote.hpp.
    : value_(value) {}
Member Function Documentation
bool QuantLib::SimpleQuote::isValid () const [inline, virtual]
returns true if the Quote holds a valid value
Implements QuantLib::Quote.
Definition at line 61 of file simplequote.hpp.
References value_.
Referenced by value().
{
        return value_!=Null<Real>();
    }
void QuantLib::SimpleQuote::reset () [inline]
Definition at line 74 of file simplequote.hpp.
References setValue().
{
        setValue(Null<Real>());
    }
Real QuantLib::SimpleQuote::setValue (Real value = Null<Real>()) [inline]
returns the difference between the new value and the old value
Definition at line 65 of file simplequote.hpp.
References QuantLib::Observable::notifyObservers(), value(), and value_.
Referenced by QuantLib::anonymous_namespace{impliedvolatility.cpp}::PriceError::operator()(), and reset().
{
        Real diff = value-value_;
        if (diff != 0.0) {
            value_ = value;
            notifyObservers();
        }
        return diff;
    }
Real QuantLib::SimpleQuote::value () const [inline, virtual]
returns the current value
Implements QuantLib::Quote.
Definition at line 56 of file simplequote.hpp.
References isValid(), QL_ENSURE, and value_.
Referenced by setValue().
{
        QL_ENSURE(isValid(), "invalid SimpleQuote");
        return value_;
    }
Member Data Documentation
Real QuantLib::SimpleQuote::value_ [private]
Definition at line 48 of file simplequote.hpp.
Referenced by isValid(), setValue(), and value().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/quotes/simplequote.hpp