QuantLib: QuantLib::Visitor< T > Class Template Reference
QuantLib::Visitor< T > Class Template Reference
Visitor for a specific class
#include <visitor.hpp>
Public Member Functions
virtual ~Visitor ()
virtual void visit (T &)=0
Detailed Description
template<class T>
class QuantLib::Visitor< T >
Visitor for a specific class
Definition at line 40 of file visitor.hpp.
Constructor & Destructor Documentation
template<class T> virtual QuantLib::Visitor< T >::~Visitor () [inline, virtual]
Definition at line 42 of file visitor.hpp.
{}
Member Function Documentation
template<class T> virtual void QuantLib::Visitor< T >::visit (T &) [pure virtual]
Implemented in QuantLib::anonymous_namespace{cashflows.cpp}::BPSCalculator, QuantLib::anonymous_namespace{cashflows.cpp}::BPSCalculator, QuantLib::anonymous_namespace{couponpricer.cpp}::PricerSetter, QuantLib::anonymous_namespace{couponpricer.cpp}::PricerSetter, QuantLib::anonymous_namespace{couponpricer.cpp}::PricerSetter, QuantLib::anonymous_namespace{couponpricer.cpp}::PricerSetter, QuantLib::anonymous_namespace{couponpricer.cpp}::PricerSetter, QuantLib::anonymous_namespace{couponpricer.cpp}::PricerSetter, QuantLib::anonymous_namespace{couponpricer.cpp}::PricerSetter, QuantLib::anonymous_namespace{couponpricer.cpp}::PricerSetter, QuantLib::anonymous_namespace{couponpricer.cpp}::PricerSetter, QuantLib::anonymous_namespace{couponpricer.cpp}::PricerSetter, QuantLib::BlackCalculator::Calculator, QuantLib::BlackCalculator::Calculator, QuantLib::BlackCalculator::Calculator, QuantLib::BlackCalculator::Calculator, and QuantLib::BlackCalculator::Calculator.
Referenced by QuantLib::NullPayoff::accept(), QuantLib::SimpleCashFlow::accept(), QuantLib::OISRateHelper::accept(), QuantLib::Dividend::accept(), QuantLib::Payoff::accept(), QuantLib::DigitalCmsCoupon::accept(), QuantLib::DigitalIborCoupon::accept(), QuantLib::DoubleStickyRatchetPayoff::accept(), QuantLib::ImpliedVolTermStructure::accept(), QuantLib::Event::accept(), QuantLib::BondHelper::accept(), QuantLib::ExtendedBlackVarianceCurve::accept(), QuantLib::CmsCoupon::accept(), QuantLib::IborCoupon::accept(), QuantLib::CashFlow::accept(), QuantLib::YoYInflationCoupon::accept(), QuantLib::SabrVolSurface::accept(), QuantLib::ExtendedBlackVarianceSurface::accept(), QuantLib::OvernightIndexedCoupon::accept(), QuantLib::Redemption::accept(), QuantLib::LocalConstantVol::accept(), QuantLib::LocalVolCurve::accept(), QuantLib::BlackConstantVol::accept(), QuantLib::LocalVolSurface::accept(), QuantLib::Callability::accept(), QuantLib::FixedRateCoupon::accept(), QuantLib::IndexedCashFlow::accept(), QuantLib::AverageBMACoupon::accept(), QuantLib::CommodityCashFlow::accept(), QuantLib::BlackVarianceCurve::accept(), QuantLib::DefaultEvent::DefaultSettlement::accept(), QuantLib::PathPayoff::accept(), QuantLib::DatedOISRateHelper::accept(), QuantLib::RangeAccrualFloatersCoupon::accept(), QuantLib::Coupon::accept(), QuantLib::FloatingTypePayoff::accept(), QuantLib::AmortizingPayment::accept(), QuantLib::CappedFlooredCoupon::accept(), QuantLib::FixedRateBondHelper::accept(), QuantLib::SubPeriodsCoupon::accept(), QuantLib::LocalVolTermStructure::accept(), QuantLib::InterestRateVolSurface::accept(), QuantLib::AbcdAtmVolCurve::accept(), QuantLib::BootstrapHelper< TS >::accept(), QuantLib::BlackVolSurface::accept(), QuantLib::BlackVarianceSurface::accept(), QuantLib::FuturesRateHelper::accept(), QuantLib::InflationCoupon::accept(), QuantLib::EquityFXVolSurface::accept(), QuantLib::BlackAtmVolCurve::accept(), QuantLib::FloatingRateCoupon::accept(), QuantLib::CPICoupon::accept(), QuantLib::PlainVanillaPayoff::accept(), QuantLib::BlackVolTermStructure::accept(), QuantLib::CappedFlooredYoYInflationCoupon::accept(), QuantLib::CappedFlooredIborCoupon::accept(), QuantLib::PercentageStrikePayoff::accept(), QuantLib::DepositRateHelper::accept(), QuantLib::DigitalCoupon::accept(), QuantLib::AssetOrNothingPayoff::accept(), QuantLib::CappedFlooredCmsCoupon::accept(), QuantLib::CashOrNothingPayoff::accept(), QuantLib::DefaultEvent::accept(), QuantLib::BlackVolatilityTermStructure::accept(), QuantLib::GapPayoff::accept(), QuantLib::FraRateHelper::accept(), QuantLib::SuperFundPayoff::accept(), QuantLib::BlackVarianceTermStructure::accept(), QuantLib::SuperSharePayoff::accept(), QuantLib::SwapRateHelper::accept(), and QuantLib::BMASwapRateHelper::accept().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/patterns/visitor.hpp