QuantLib: QuantLib::CostFunction Class Reference
QuantLib::CostFunction Class Reference
Cost function abstract class for optimization problem.
#include <costfunction.hpp>
Public Member Functions
virtual ~CostFunction ()
virtual Real value (const Array &x) const =0
method to overload to compute the cost function value in x
virtual Disposable< Array > values (const Array &x) const =0
method to overload to compute the cost function values in x
virtual void gradient (Array &grad, const Array &x) const
method to overload to compute grad_f, the first derivative of
virtual Real valueAndGradient (Array &grad, const Array &x) const
method to overload to compute grad_f, the first derivative of
virtual Real finiteDifferenceEpsilon () const
Default epsilon for finite difference method :
Detailed Description
Cost function abstract class for optimization problem.
Definition at line 32 of file costfunction.hpp.
Constructor & Destructor Documentation
virtual QuantLib::CostFunction::~CostFunction () [inline, virtual]
Definition at line 34 of file costfunction.hpp.
{}
Member Function Documentation
virtual Real QuantLib::CostFunction::finiteDifferenceEpsilon () const [inline, virtual]
Default epsilon for finite difference method :
Reimplemented in QuantLib::CalibratedModel::CalibrationFunction.
Definition at line 64 of file costfunction.hpp.
Referenced by gradient().
{ return 1e-8; }
virtual void QuantLib::CostFunction::gradient (Array & grad, const Array & x) const [inline, virtual]
method to overload to compute grad_f, the first derivative of
Reimplemented in QuantLib::LeastSquareFunction.
Definition at line 42 of file costfunction.hpp.
References finiteDifferenceEpsilon(), QuantLib::Array::size(), and value().
Referenced by QuantLib::Problem::gradient(), and valueAndGradient().
{
            Real eps = finiteDifferenceEpsilon(), fp, fm;
            Array xx(x);
            for (Size i=0; i<x.size(); i++) {
                xx[i] += eps;
                fp = value(xx);
                xx[i] -= 2.0*eps;
                fm = value(xx);
                grad[i] = 0.5*(fp - fm)/eps;
                xx[i] = x[i];
            }
        }
virtual Real QuantLib::CostFunction::value (const Array & x) const [pure virtual]
method to overload to compute the cost function value in x
Implemented in QuantLib::detail::SABRInterpolationImpl< I1, I2 >::SABRError, QuantLib::FrobeniusCostFunction, QuantLib::anonymous_namespace{pseudosqrt.cpp}::HypersphereCostFunction, anonymous_namespace{optimizers.cpp}::OptimizationBasedCostFunction, QuantLib::LeastSquareFunction, anonymous_namespace{cmsmarketcalibration.cpp}::ObjectiveFunction, QuantLib::PenaltyFunction< Curve >, anonymous_namespace{optimizers.cpp}::OneDimensionalPolynomialDegreeN, QuantLib::AbcdCalibration::AbcdError, QuantLib::CalibratedModel::CalibrationFunction, QuantLib::ProjectedCostFunction, QuantLib::FittedBondDiscountCurve::FittingMethod::FittingCost, and QuantLib::anonymous_namespace{parametricexercise.cpp}::ValueEstimate.
Referenced by gradient(), QuantLib::LevenbergMarquardt::minimize(), QuantLib::ProjectedCostFunction::value(), QuantLib::Problem::value(), and valueAndGradient().
virtual Real QuantLib::CostFunction::valueAndGradient (Array & grad, const Array & x) const [inline, virtual]
method to overload to compute grad_f, the first derivative of
Reimplemented in QuantLib::LeastSquareFunction.
Definition at line 57 of file costfunction.hpp.
References gradient(), and value().
Referenced by QuantLib::Problem::valueAndGradient().
{
            gradient(grad, x);
            return value(x);
        }
virtual Disposable<Array> QuantLib::CostFunction::values (const Array & x) const [pure virtual]
method to overload to compute the cost function values in x
Implemented in QuantLib::detail::SABRInterpolationImpl< I1, I2 >::SABRError, QuantLib::FrobeniusCostFunction, QuantLib::anonymous_namespace{pseudosqrt.cpp}::HypersphereCostFunction, anonymous_namespace{optimizers.cpp}::OptimizationBasedCostFunction, QuantLib::LeastSquareFunction, anonymous_namespace{cmsmarketcalibration.cpp}::ObjectiveFunction, anonymous_namespace{optimizers.cpp}::OneDimensionalPolynomialDegreeN, QuantLib::CalibratedModel::CalibrationFunction, QuantLib::PenaltyFunction< Curve >, QuantLib::AbcdCalibration::AbcdError, QuantLib::ProjectedCostFunction, QuantLib::FittedBondDiscountCurve::FittingMethod::FittingCost, and QuantLib::anonymous_namespace{parametricexercise.cpp}::ValueEstimate.
Referenced by QuantLib::LevenbergMarquardt::minimize(), QuantLib::ProjectedCostFunction::values(), and QuantLib::Problem::values().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/optimization/costfunction.hpp