QuantLib: QuantLib::ConstantSwaptionVolatility Class Reference
QuantLib::ConstantSwaptionVolatility Class Reference
Constant swaption volatility, no time-strike dependence.
#include <swaptionconstantvol.hpp>
Public Member Functions
ConstantSwaptionVolatility (Natural settlementDays, const Calendar &cal, BusinessDayConvention bdc, const Handle< Quote > &volatility, const DayCounter &dc)
floating reference date, floating market data
ConstantSwaptionVolatility (const Date &referenceDate, const Calendar &cal, BusinessDayConvention bdc, const Handle< Quote > &volatility, const DayCounter &dc)
fixed reference date, floating market data
ConstantSwaptionVolatility (Natural settlementDays, const Calendar &cal, BusinessDayConvention bdc, Volatility volatility, const DayCounter &dc)
floating reference date, fixed market data
ConstantSwaptionVolatility (const Date &referenceDate, const Calendar &cal, BusinessDayConvention bdc, Volatility volatility, const DayCounter &dc)
fixed reference date, fixed market data
TermStructure interface
Date maxDate () const
the latest date for which the curve can return values
VolatilityTermStructure interface
Real minStrike () const
the minimum strike for which the term structure can return vols
Real maxStrike () const
the maximum strike for which the term structure can return vols
SwaptionVolatilityStructure interface
const Period & maxSwapTenor () const
the largest length for which the term structure can return vols
Protected Member Functions
boost::shared_ptr< SmileSection > smileSectionImpl (const Date &, const Period &) const
boost::shared_ptr< SmileSection > smileSectionImpl (Time, Time) const
Volatility volatilityImpl (const Date &, const Period &, Rate) const
Volatility volatilityImpl (Time, Time, Rate) const
Private Attributes
Handle< Quote > volatility_
Period maxSwapTenor_
Detailed Description
Constant swaption volatility, no time-strike dependence.
Definition at line 36 of file swaptionconstantvol.hpp.
Constructor & Destructor Documentation
QuantLib::ConstantSwaptionVolatility::ConstantSwaptionVolatility (Natural settlementDays, const Calendar & cal, BusinessDayConvention bdc, const Handle< Quote > & volatility, const DayCounter & dc)
floating reference date, floating market data
Definition at line 28 of file swaptionconstantvol.cpp.
References QuantLib::Observer::registerWith(), and volatility_.
    : SwaptionVolatilityStructure(settlementDays, cal, bdc, dc),
      volatility_(vol), maxSwapTenor_(100*Years) {
        registerWith(volatility_);
    }
QuantLib::ConstantSwaptionVolatility::ConstantSwaptionVolatility (const Date & referenceDate, const Calendar & cal, BusinessDayConvention bdc, const Handle< Quote > & volatility, const DayCounter & dc)
fixed reference date, floating market data
Definition at line 40 of file swaptionconstantvol.cpp.
References QuantLib::Observer::registerWith(), and volatility_.
    : SwaptionVolatilityStructure(referenceDate, cal, bdc, dc),
      volatility_(vol), maxSwapTenor_(100*Years) {
        registerWith(volatility_);
    }
QuantLib::ConstantSwaptionVolatility::ConstantSwaptionVolatility (Natural settlementDays, const Calendar & cal, BusinessDayConvention bdc, Volatility volatility, const DayCounter & dc)
floating reference date, fixed market data
Definition at line 52 of file swaptionconstantvol.cpp.
    : SwaptionVolatilityStructure(settlementDays, cal, bdc, dc),
      volatility_(boost::shared_ptr<Quote>(new SimpleQuote(vol))),
      maxSwapTenor_(100*Years) {}
QuantLib::ConstantSwaptionVolatility::ConstantSwaptionVolatility (const Date & referenceDate, const Calendar & cal, BusinessDayConvention bdc, Volatility volatility, const DayCounter & dc)
fixed reference date, fixed market data
Definition at line 63 of file swaptionconstantvol.cpp.
    : SwaptionVolatilityStructure(referenceDate, cal, bdc, dc),
      volatility_(boost::shared_ptr<Quote>(new SimpleQuote(vol))),
      maxSwapTenor_(100*Years) {}
Member Function Documentation
Date QuantLib::ConstantSwaptionVolatility::maxDate () const [inline, virtual]
the latest date for which the curve can return values
Implements QuantLib::TermStructure.
Definition at line 94 of file swaptionconstantvol.hpp.
{
        return Date::maxDate();
    }
Real QuantLib::ConstantSwaptionVolatility::maxStrike () const [inline, virtual]
the maximum strike for which the term structure can return vols
Implements QuantLib::VolatilityTermStructure.
Definition at line 102 of file swaptionconstantvol.hpp.
References QL_MAX_REAL.
{
        return QL_MAX_REAL;
    }
const Period & QuantLib::ConstantSwaptionVolatility::maxSwapTenor () const [inline, virtual]
the largest length for which the term structure can return vols
Implements QuantLib::SwaptionVolatilityStructure.
Definition at line 106 of file swaptionconstantvol.hpp.
References maxSwapTenor_.
{
        return maxSwapTenor_;
    }
Real QuantLib::ConstantSwaptionVolatility::minStrike () const [inline, virtual]
the minimum strike for which the term structure can return vols
Implements QuantLib::VolatilityTermStructure.
Definition at line 98 of file swaptionconstantvol.hpp.
References QL_MIN_REAL.
{
        return QL_MIN_REAL;
    }
boost::shared_ptr< SmileSection > QuantLib::ConstantSwaptionVolatility::smileSectionImpl (const Date & d, const Period &) const [protected, virtual]
Reimplemented from QuantLib::SwaptionVolatilityStructure.
Definition at line 74 of file swaptionconstantvol.cpp.
References QuantLib::TermStructure::dayCounter(), QuantLib::TermStructure::referenceDate(), and volatility_.
{
        Volatility atmVol = volatility_->value();
        return boost::shared_ptr<SmileSection>(new
            FlatSmileSection(d, atmVol, dayCounter(), referenceDate()));
    }
boost::shared_ptr< SmileSection > QuantLib::ConstantSwaptionVolatility::smileSectionImpl (Time optionTime, Time) const [protected, virtual]
Implements QuantLib::SwaptionVolatilityStructure.
Definition at line 82 of file swaptionconstantvol.cpp.
References QuantLib::TermStructure::dayCounter(), and volatility_.
{
        Volatility atmVol = volatility_->value();
        return boost::shared_ptr<SmileSection>(new
            FlatSmileSection(optionTime, atmVol, dayCounter()));
    }
Volatility QuantLib::ConstantSwaptionVolatility::volatilityImpl (const Date & , const Period & , Rate) const [protected, virtual]
Reimplemented from QuantLib::SwaptionVolatilityStructure.
Definition at line 89 of file swaptionconstantvol.cpp.
References volatility_.
{
        return volatility_->value();
    }
Volatility QuantLib::ConstantSwaptionVolatility::volatilityImpl (Time , Time , Rate) const [protected, virtual]
Implements QuantLib::SwaptionVolatilityStructure.
Definition at line 95 of file swaptionconstantvol.cpp.
References volatility_.
{
        return volatility_->value();
    }
Member Data Documentation
Period QuantLib::ConstantSwaptionVolatility::maxSwapTenor_ [private]
Definition at line 88 of file swaptionconstantvol.hpp.
Referenced by maxSwapTenor().
Handle<Quote> QuantLib::ConstantSwaptionVolatility::volatility_ [private]
Definition at line 87 of file swaptionconstantvol.hpp.
Referenced by ConstantSwaptionVolatility(), smileSectionImpl(), and volatilityImpl().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/swaption/swaptionconstantvol.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/swaption/swaptionconstantvol.cpp