QuantLib: QuantLib::SwapRateHelper Class Reference
QuantLib::SwapRateHelper Class Reference
Rate helper for bootstrapping over swap rates.
#include <ratehelpers.hpp>
Public Member Functions
SwapRateHelper (const Handle< Quote > &rate, const boost::shared_ptr< SwapIndex > &swapIndex, const Handle< Quote > &spread=Handle< Quote >(), const Period &fwdStart=0 *Days, const Handle< YieldTermStructure > &discountingCurve=Handle< YieldTermStructure >())
SwapRateHelper (const Handle< Quote > &rate, const Period &tenor, const Calendar &calendar, Frequency fixedFrequency, BusinessDayConvention fixedConvention, const DayCounter &fixedDayCount, const boost::shared_ptr< IborIndex > &iborIndex, const Handle< Quote > &spread=Handle< Quote >(), const Period &fwdStart=0 *Days, const Handle< YieldTermStructure > &discountingCurve=Handle< YieldTermStructure >())
SwapRateHelper (Rate rate, const Period &tenor, const Calendar &calendar, Frequency fixedFrequency, BusinessDayConvention fixedConvention, const DayCounter &fixedDayCount, const boost::shared_ptr< IborIndex > &iborIndex, const Handle< Quote > &spread=Handle< Quote >(), const Period &fwdStart=0 *Days, const Handle< YieldTermStructure > &discountingCurve=Handle< YieldTermStructure >())
SwapRateHelper (Rate rate, const boost::shared_ptr< SwapIndex > &swapIndex, const Handle< Quote > &spread=Handle< Quote >(), const Period &fwdStart=0 *Days, const Handle< YieldTermStructure > &discountingCurve=Handle< YieldTermStructure >())
RateHelper interface
Real impliedQuote () const
void setTermStructure (YieldTermStructure *)
SwapRateHelper inspectors
Spread spread () const
boost::shared_ptr< VanillaSwap > swap () const
const Period & forwardStart () const
Visitability
void accept (AcyclicVisitor &)
Protected Member Functions
void initializeDates ()
Protected Attributes
Period tenor_
Calendar calendar_
BusinessDayConvention fixedConvention_
Frequency fixedFrequency_
DayCounter fixedDayCount_
boost::shared_ptr< IborIndex > iborIndex_
boost::shared_ptr< VanillaSwap > swap_
RelinkableHandle
< YieldTermStructure > termStructureHandle_
Handle< Quote > spread_
Period fwdStart_
Handle< YieldTermStructure > discountHandle_
RelinkableHandle
< YieldTermStructure > discountRelinkableHandle_
Detailed Description
Rate helper for bootstrapping over swap rates.
Todo:
use input SwapIndex to create the swap
Definition at line 204 of file ratehelpers.hpp.
Constructor & Destructor Documentation
QuantLib::SwapRateHelper::SwapRateHelper (const Handle< Quote > & rate, const boost::shared_ptr< SwapIndex > & swapIndex, const Handle< Quote > & spread = Handle< Quote >(), const Period & fwdStart = 0 *Days, const Handle< YieldTermStructure > & discountingCurve = Handle< YieldTermStructure >())
QuantLib::SwapRateHelper::SwapRateHelper (const Handle< Quote > & rate, const Period & tenor, const Calendar & calendar, Frequency fixedFrequency, BusinessDayConvention fixedConvention, const DayCounter & fixedDayCount, const boost::shared_ptr< IborIndex > & iborIndex, const Handle< Quote > & spread = Handle< Quote >(), const Period & fwdStart = 0 *Days, const Handle< YieldTermStructure > & discountingCurve = Handle< YieldTermStructure >())
QuantLib::SwapRateHelper::SwapRateHelper (Rate rate, const Period & tenor, const Calendar & calendar, Frequency fixedFrequency, BusinessDayConvention fixedConvention, const DayCounter & fixedDayCount, const boost::shared_ptr< IborIndex > & iborIndex, const Handle< Quote > & spread = Handle< Quote >(), const Period & fwdStart = 0 *Days, const Handle< YieldTermStructure > & discountingCurve = Handle< YieldTermStructure >())
QuantLib::SwapRateHelper::SwapRateHelper (Rate rate, const boost::shared_ptr< SwapIndex > & swapIndex, const Handle< Quote > & spread = Handle< Quote >(), const Period & fwdStart = 0 *Days, const Handle< YieldTermStructure > & discountingCurve = Handle< YieldTermStructure >())
Member Function Documentation
void QuantLib::SwapRateHelper::accept (AcyclicVisitor & v) [virtual]
Reimplemented from QuantLib::BootstrapHelper< TS >.
Definition at line 620 of file ratehelpers.cpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Visitor< T >::visit().
{
        Visitor<SwapRateHelper>* v1 =
            dynamic_cast<Visitor<SwapRateHelper>*>(&v);
        if (v1 != 0)
            v1->visit(*this);
        else
            RateHelper::accept(v);
    }
const Period & QuantLib::SwapRateHelper::forwardStart () const [inline]
Definition at line 328 of file ratehelpers.hpp.
References fwdStart_.
{
        return fwdStart_;
    }
Real QuantLib::SwapRateHelper::impliedQuote () const [virtual]
Implements QuantLib::BootstrapHelper< TS >.
Definition at line 606 of file ratehelpers.cpp.
References QuantLib::Handle< T >::empty(), QL_REQUIRE, spread(), spread_, swap_, and QuantLib::BootstrapHelper< TS >::termStructure_.
{
        QL_REQUIRE(termStructure_ != 0, "term structure not set");
        // we didn't register as observers - force calculation
        swap_->recalculate();
        // weak implementation... to be improved
        static const Spread basisPoint = 1.0e-4;
        Real floatingLegNPV = swap_->floatingLegNPV();
        Spread spread = spread_.empty() ? 0.0 : spread_->value();
        Real spreadNPV = swap_->floatingLegBPS()/basisPoint*spread;
        Real totNPV = - (floatingLegNPV+spreadNPV);
        Real result = totNPV/(swap_->fixedLegBPS()/basisPoint);
        return result;
    }
void QuantLib::SwapRateHelper::initializeDates () [protected, virtual]
Implements QuantLib::RelativeDateBootstrapHelper< TS >.
Definition at line 558 of file ratehelpers.cpp.
References calendar_, discountRelinkableHandle_, QuantLib::BootstrapHelper< TS >::earliestDate_, fixedConvention_, fixedDayCount_, fixedFrequency_, fwdStart_, iborIndex_, QuantLib::BootstrapHelper< TS >::latestDate_, swap_, tenor_, QuantLib::MakeVanillaSwap::withDiscountingTermStructure(), QuantLib::MakeVanillaSwap::withFixedLegCalendar(), QuantLib::MakeVanillaSwap::withFixedLegConvention(), QuantLib::MakeVanillaSwap::withFixedLegDayCount(), QuantLib::MakeVanillaSwap::withFixedLegTenor(), QuantLib::MakeVanillaSwap::withFixedLegTerminationDateConvention(), and QuantLib::MakeVanillaSwap::withFloatingLegCalendar().
{
        // 1. do not pass the spread here, as it might be a Quote
        //    i.e. it can dinamically change
        // 2. input discount curve Handle might be empty now but it could
        //    be assigned a curve later; use a RelinkableHandle here
        swap_ = MakeVanillaSwap(tenor_, iborIndex_, 0.0, fwdStart_)
            .withDiscountingTermStructure(discountRelinkableHandle_)
            .withFixedLegDayCount(fixedDayCount_)
            .withFixedLegTenor(Period(fixedFrequency_))
            .withFixedLegConvention(fixedConvention_)
            .withFixedLegTerminationDateConvention(fixedConvention_)
            .withFixedLegCalendar(calendar_)
            .withFloatingLegCalendar(calendar_);
        earliestDate_ = swap_->startDate();
        // Usually...
        latestDate_ = swap_->maturityDate();
        // ...but due to adjustments, the last floating coupon might
        // need a later date for fixing
        #ifdef QL_USE_INDEXED_COUPON
        shared_ptr<FloatingRateCoupon> lastFloating =
            boost::dynamic_pointer_cast<FloatingRateCoupon>(
                                                 swap_->floatingLeg().back());
        Date fixingValueDate =
            iborIndex_->valueDate(lastFloating->fixingDate());
        Date endValueDate = iborIndex_->maturityDate(fixingValueDate);
        latestDate_ = std::max(latestDate_, endValueDate);
        #endif
    }
void QuantLib::SwapRateHelper::setTermStructure (YieldTermStructure * t)
Definition at line 590 of file ratehelpers.cpp.
References discountHandle_, discountRelinkableHandle_, QuantLib::Handle< T >::empty(), QuantLib::RelinkableHandle< T >::linkTo(), QuantLib::anonymous_namespace{riskyassetswap.cpp}::no_deletion(), and termStructureHandle_.
{
        // do not set the relinkable handle as an observer -
        // force recalculation when needed
        bool observer = false;
        shared_ptr<YieldTermStructure> temp(t, no_deletion);
        termStructureHandle_.linkTo(temp, observer);
        if (discountHandle_.empty())
            discountRelinkableHandle_.linkTo(temp, observer);
        else
            discountRelinkableHandle_.linkTo(*discountHandle_, observer);
        RelativeDateRateHelper::setTermStructure(t);
    }
Spread QuantLib::SwapRateHelper::spread () const [inline]
Definition at line 320 of file ratehelpers.hpp.
References QuantLib::Handle< T >::empty(), and spread_.
Referenced by impliedQuote().
{
        return spread_.empty() ? 0.0 : spread_->value();
    }
boost::shared_ptr< VanillaSwap > QuantLib::SwapRateHelper::swap () const [inline]
Definition at line 324 of file ratehelpers.hpp.
References swap_.
{
        return swap_;
    }
Member Data Documentation
Calendar QuantLib::SwapRateHelper::calendar_ [protected]
Definition at line 266 of file ratehelpers.hpp.
Referenced by initializeDates().
Handle<YieldTermStructure> QuantLib::SwapRateHelper::discountHandle_ [protected]
Definition at line 275 of file ratehelpers.hpp.
Referenced by setTermStructure().
RelinkableHandle<YieldTermStructure> QuantLib::SwapRateHelper::discountRelinkableHandle_ [protected]
Definition at line 276 of file ratehelpers.hpp.
Referenced by initializeDates(), and setTermStructure().
BusinessDayConvention QuantLib::SwapRateHelper::fixedConvention_ [protected]
Definition at line 267 of file ratehelpers.hpp.
Referenced by initializeDates().
DayCounter QuantLib::SwapRateHelper::fixedDayCount_ [protected]
Definition at line 269 of file ratehelpers.hpp.
Referenced by initializeDates().
Frequency QuantLib::SwapRateHelper::fixedFrequency_ [protected]
Definition at line 268 of file ratehelpers.hpp.
Referenced by initializeDates().
Period QuantLib::SwapRateHelper::fwdStart_ [protected]
Definition at line 274 of file ratehelpers.hpp.
Referenced by forwardStart(), and initializeDates().
boost::shared_ptr<IborIndex> QuantLib::SwapRateHelper::iborIndex_ [protected]
Definition at line 270 of file ratehelpers.hpp.
Referenced by initializeDates().
Handle<Quote> QuantLib::SwapRateHelper::spread_ [protected]
Definition at line 273 of file ratehelpers.hpp.
Referenced by impliedQuote(), and spread().
boost::shared_ptr<VanillaSwap> QuantLib::SwapRateHelper::swap_ [protected]
Definition at line 271 of file ratehelpers.hpp.
Referenced by impliedQuote(), initializeDates(), and swap().
Period QuantLib::SwapRateHelper::tenor_ [protected]
Definition at line 265 of file ratehelpers.hpp.
Referenced by initializeDates().
RelinkableHandle<YieldTermStructure> QuantLib::SwapRateHelper::termStructureHandle_ [protected]
Definition at line 272 of file ratehelpers.hpp.
Referenced by setTermStructure().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/yield/ratehelpers.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/yield/ratehelpers.cpp