QuantLib: QuantLib::Dividend Class Reference
QuantLib::Dividend Class Reference
Predetermined cash flow.
#include <dividend.hpp>
Public Member Functions
Dividend (const Date &date)
virtual Real amount (Real underlying) const =0
Event interface
Date date () const
CashFlow interface
virtual Real amount () const =0
returns the amount of the cash flow
Visitability
virtual void accept (AcyclicVisitor &)
Protected Attributes
Date date_
Detailed Description
Predetermined cash flow.
This cash flow pays a predetermined amount at a given date.
Definition at line 36 of file dividend.hpp.
Constructor & Destructor Documentation
QuantLib::Dividend::Dividend (const Date & date) [inline]
Definition at line 38 of file dividend.hpp.
        : date_(date) {}
Member Function Documentation
void QuantLib::Dividend::accept (AcyclicVisitor & v) [virtual]
Reimplemented from QuantLib::CashFlow.
Definition at line 25 of file dividend.cpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Visitor< T >::visit().
{
        Visitor<Dividend>* v1 =
            dynamic_cast<Visitor<Dividend>*>(&v);
        if (v1 != 0)
            v1->visit(*this);
        else
            CashFlow::accept(v);
    }
virtual Real QuantLib::Dividend::amount () const [pure virtual]
returns the amount of the cash flow
Note:
The amount is not discounted, i.e., it is the actual amount paid at the cash flow date.
Implements QuantLib::CashFlow.
Implemented in QuantLib::FractionalDividend, and QuantLib::FixedDividend.
Referenced by QuantLib::FDDividendEngineBase< Scheme >::getDividendAmount(), QuantLib::detail::DividendAdder::operator()(), and QuantLib::FDDividendEngineShiftScale< Scheme >::setGridLimits().
virtual Real QuantLib::Dividend::amount (Real underlying) const [pure virtual]
Implemented in QuantLib::FractionalDividend, and QuantLib::FixedDividend.
Date QuantLib::Dividend::date () const [inline, virtual]
Note:
This is inherited from the event class
Implements QuantLib::CashFlow.
Definition at line 42 of file dividend.hpp.
References date_.
{ return date_; }
Member Data Documentation
Date QuantLib::Dividend::date_ [protected]
Definition at line 54 of file dividend.hpp.
Referenced by date().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/dividend.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/dividend.cpp