QuantLib: QuantLib::anonymous_namespace{couponpricer.cpp}::PricerSetter Class Reference
QuantLib::anonymous_namespace{couponpricer.cpp}::PricerSetter Class Reference
Public Member Functions
PricerSetter (const boost::shared_ptr< FloatingRateCouponPricer > &pricer)
void visit (CashFlow &c)
void visit (Coupon &c)
void visit (IborCoupon &c)
void visit (CappedFlooredIborCoupon &c)
void visit (DigitalIborCoupon &c)
void visit (CmsCoupon &c)
void visit (CappedFlooredCmsCoupon &c)
void visit (DigitalCmsCoupon &c)
void visit (RangeAccrualFloatersCoupon &c)
void visit (SubPeriodsCoupon &c)
Private Attributes
const boost::shared_ptr
< FloatingRateCouponPricer > pricer_
Detailed Description
Definition at line 126 of file couponpricer.cpp.
Constructor & Destructor Documentation
QuantLib::anonymous_namespace{couponpricer.cpp}::PricerSetter::PricerSetter (const boost::shared_ptr< FloatingRateCouponPricer > & pricer) [inline]
Definition at line 140 of file couponpricer.cpp.
            : pricer_(pricer) {}
Member Function Documentation
void QuantLib::anonymous_namespace{couponpricer.cpp}::PricerSetter::visit (CashFlow & c) [virtual]
Implements QuantLib::Visitor< CashFlow >.
Definition at line 156 of file couponpricer.cpp.
{
            // nothing to do
        }
void QuantLib::anonymous_namespace{couponpricer.cpp}::PricerSetter::visit (Coupon & c) [virtual]
Implements QuantLib::Visitor< Coupon >.
Definition at line 160 of file couponpricer.cpp.
{
            // nothing to do
        }
void QuantLib::anonymous_namespace{couponpricer.cpp}::PricerSetter::visit (IborCoupon & c) [virtual]
Implements QuantLib::Visitor< IborCoupon >.
Definition at line 164 of file couponpricer.cpp.
References QL_REQUIRE, and QuantLib::FloatingRateCoupon::setPricer().
{
            const boost::shared_ptr<IborCouponPricer> iborCouponPricer =
                boost::dynamic_pointer_cast<IborCouponPricer>(pricer_);
            QL_REQUIRE(iborCouponPricer,
                       "pricer not compatible with Ibor coupon");
            c.setPricer(iborCouponPricer);
        }
void QuantLib::anonymous_namespace{couponpricer.cpp}::PricerSetter::visit (CappedFlooredIborCoupon & c) [virtual]
Implements QuantLib::Visitor< CappedFlooredIborCoupon >.
Definition at line 180 of file couponpricer.cpp.
References QL_REQUIRE, and QuantLib::CappedFlooredCoupon::setPricer().
{
            const boost::shared_ptr<IborCouponPricer> iborCouponPricer =
                boost::dynamic_pointer_cast<IborCouponPricer>(pricer_);
            QL_REQUIRE(iborCouponPricer,
                       "pricer not compatible with Ibor coupon");
            c.setPricer(iborCouponPricer);
        }
void QuantLib::anonymous_namespace{couponpricer.cpp}::PricerSetter::visit (DigitalIborCoupon & c) [virtual]
Implements QuantLib::Visitor< DigitalIborCoupon >.
Definition at line 172 of file couponpricer.cpp.
References QL_REQUIRE, and QuantLib::DigitalCoupon::setPricer().
{
            const boost::shared_ptr<IborCouponPricer> iborCouponPricer =
                boost::dynamic_pointer_cast<IborCouponPricer>(pricer_);
            QL_REQUIRE(iborCouponPricer,
                       "pricer not compatible with Ibor coupon");
            c.setPricer(iborCouponPricer);
        }
void QuantLib::anonymous_namespace{couponpricer.cpp}::PricerSetter::visit (CmsCoupon & c) [virtual]
Implements QuantLib::Visitor< CmsCoupon >.
Definition at line 188 of file couponpricer.cpp.
References QL_REQUIRE, and QuantLib::FloatingRateCoupon::setPricer().
{
            const boost::shared_ptr<CmsCouponPricer> cmsCouponPricer =
                boost::dynamic_pointer_cast<CmsCouponPricer>(pricer_);
            QL_REQUIRE(cmsCouponPricer,
                       "pricer not compatible with CMS coupon");
            c.setPricer(cmsCouponPricer);
        }
void QuantLib::anonymous_namespace{couponpricer.cpp}::PricerSetter::visit (CappedFlooredCmsCoupon & c) [virtual]
Implements QuantLib::Visitor< CappedFlooredCmsCoupon >.
Definition at line 196 of file couponpricer.cpp.
References QL_REQUIRE, and QuantLib::CappedFlooredCoupon::setPricer().
{
            const boost::shared_ptr<CmsCouponPricer> cmsCouponPricer =
                boost::dynamic_pointer_cast<CmsCouponPricer>(pricer_);
            QL_REQUIRE(cmsCouponPricer,
                       "pricer not compatible with CMS coupon");
            c.setPricer(cmsCouponPricer);
        }
void QuantLib::anonymous_namespace{couponpricer.cpp}::PricerSetter::visit (DigitalCmsCoupon & c) [virtual]
Implements QuantLib::Visitor< DigitalCmsCoupon >.
Definition at line 204 of file couponpricer.cpp.
References QL_REQUIRE, and QuantLib::DigitalCoupon::setPricer().
{
            const boost::shared_ptr<CmsCouponPricer> cmsCouponPricer =
                boost::dynamic_pointer_cast<CmsCouponPricer>(pricer_);
            QL_REQUIRE(cmsCouponPricer,
                       "pricer not compatible with CMS coupon");
            c.setPricer(cmsCouponPricer);
        }
void QuantLib::anonymous_namespace{couponpricer.cpp}::PricerSetter::visit (RangeAccrualFloatersCoupon & c) [virtual]
Implements QuantLib::Visitor< RangeAccrualFloatersCoupon >.
Definition at line 212 of file couponpricer.cpp.
References QL_REQUIRE, and QuantLib::FloatingRateCoupon::setPricer().
{
            const boost::shared_ptr<RangeAccrualPricer> rangeAccrualPricer =
                boost::dynamic_pointer_cast<RangeAccrualPricer>(pricer_);
            QL_REQUIRE(rangeAccrualPricer,
                       "pricer not compatible with range-accrual coupon");
            c.setPricer(rangeAccrualPricer);
        }
void QuantLib::anonymous_namespace{couponpricer.cpp}::PricerSetter::visit (SubPeriodsCoupon & c) [virtual]
Implements QuantLib::Visitor< SubPeriodsCoupon >.
Definition at line 220 of file couponpricer.cpp.
References QL_REQUIRE, and QuantLib::FloatingRateCoupon::setPricer().
{
            const boost::shared_ptr<SubPeriodsPricer> subPeriodsPricer =
                boost::dynamic_pointer_cast<SubPeriodsPricer>(pricer_);
            QL_REQUIRE(subPeriodsPricer,
                       "pricer not compatible with sub-period coupon");
            c.setPricer(subPeriodsPricer);
        }
Member Data Documentation
const boost::shared_ptr<FloatingRateCouponPricer> QuantLib::anonymous_namespace{couponpricer.cpp}::PricerSetter::pricer_ [private]
Definition at line 138 of file couponpricer.cpp.
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/couponpricer.cpp