QuantLib: QuantLib::CompositeInstrument Class Reference
QuantLib::CompositeInstrument Class Reference
Composite instrument
#include <compositeinstrument.hpp>
Public Member Functions
void add (const boost::shared_ptr< Instrument > &instrument, Real multiplier=1.0)
adds an instrument to the composite
void subtract (const boost::shared_ptr< Instrument > &instrument, Real multiplier=1.0)
shorts an instrument from the composite
Private Types
typedef std::pair
< boost::shared_ptr
< Instrument >, Real > component
typedef std::list< component >
::iterator iterator
typedef std::list< component >
::const_iterator const_iterator
Private Attributes
std::list< component > components_
Instrument interface
bool isExpired () const
returns whether the instrument might have value greater than zero.
void performCalculations () const
Detailed Description
Composite instrument
This instrument is an aggregate of other instruments. Its NPV is the sum of the NPVs of its components, each possibly multiplied by a given factor.
Example: static replication of a down-and-out barrier option
Warning:
Methods that drive the calculation directly (such as recalculate(), freeze() and others) might not work correctly.
Definition at line 49 of file compositeinstrument.hpp.
Member Typedef Documentation
typedef std::pair<boost::shared_ptr<Instrument>, Real> QuantLib::CompositeInstrument::component [private]
Definition at line 50 of file compositeinstrument.hpp.
typedef std::list<component>::const_iterator QuantLib::CompositeInstrument::const_iterator [private]
Definition at line 52 of file compositeinstrument.hpp.
typedef std::list<component>::iterator QuantLib::CompositeInstrument::iterator [private]
Reimplemented from QuantLib::Observable.
Definition at line 51 of file compositeinstrument.hpp.
Member Function Documentation
void QuantLib::CompositeInstrument::add (const boost::shared_ptr< Instrument > & instrument, Real multiplier = 1.0)
adds an instrument to the composite
Definition at line 24 of file compositeinstrument.cpp.
References components_, QuantLib::Observer::registerWith(), and QuantLib::LazyObject::update().
Referenced by subtract().
{
        components_.push_back(std::make_pair(instrument,multiplier));
        registerWith(instrument);
        update();
    }
bool QuantLib::CompositeInstrument::isExpired () const [virtual]
returns whether the instrument might have value greater than zero.
Implements QuantLib::Instrument.
Definition at line 36 of file compositeinstrument.cpp.
References components_.
{
        for (const_iterator i=components_.begin(); i!=components_.end(); ++i) {
            if (!i->first->isExpired())
                return false;
        }
        return true;
    }
void QuantLib::CompositeInstrument::performCalculations () const [protected, virtual]
In case a pricing engine is not used, this method must be overridden to perform the actual calculations and set any needed results. In case a pricing engine is used, the default implementation can be used.
Reimplemented from QuantLib::Instrument.
Definition at line 44 of file compositeinstrument.cpp.
References components_, and QuantLib::Instrument::NPV_.
{
        NPV_ = 0.0;
        for (const_iterator i=components_.begin(); i!=components_.end(); ++i) {
            NPV_ += i->second * i->first->NPV();
        }
    }
void QuantLib::CompositeInstrument::subtract (const boost::shared_ptr< Instrument > & instrument, Real multiplier = 1.0)
shorts an instrument from the composite
Definition at line 31 of file compositeinstrument.cpp.
References add().
{
        add(instrument, -multiplier);
    }
Member Data Documentation
std::list<component> QuantLib::CompositeInstrument::components_ [private]
Definition at line 67 of file compositeinstrument.hpp.
Referenced by add(), isExpired(), and performCalculations().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/compositeinstrument.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/compositeinstrument.cpp