QuantLib: QuantLib::MCDiscreteAveragingAsianEngine< RNG, S > Class Template Reference
QuantLib::MCDiscreteAveragingAsianEngine< RNG, S > Class Template Reference
Pricing engine for discrete average Asians using Monte Carlo simulation.
#include <mcdiscreteasianengine.hpp>
Public Types
typedef McSimulation
< SingleVariate, RNG, S >
::path_generator_type path_generator_type
typedef McSimulation
< SingleVariate, RNG, S >
::path_pricer_type path_pricer_type
typedef McSimulation
< SingleVariate, RNG, S >
::stats_type stats_type
Public Member Functions
MCDiscreteAveragingAsianEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > &process, bool brownianBridge, bool antitheticVariate, bool controlVariate, Size requiredSamples, Real requiredTolerance, Size maxSamples, BigNatural seed)
void calculate () const
Protected Member Functions
TimeGrid timeGrid () const
boost::shared_ptr
< path_generator_type > pathGenerator () const
Real controlVariateValue () const
Protected Attributes
boost::shared_ptr
< GeneralizedBlackScholesProcess > process_
Size requiredSamples_
Size maxSamples_
Real requiredTolerance_
bool brownianBridge_
BigNatural seed_
Detailed Description
template<class RNG = PseudoRandom, class S = Statistics>
class QuantLib::MCDiscreteAveragingAsianEngine< RNG, S >
Pricing engine for discrete average Asians using Monte Carlo simulation.
Warning:
control-variate calculation is disabled under VC++6.
Definition at line 41 of file mcdiscreteasianengine.hpp.
Member Typedef Documentation
template<class RNG = PseudoRandom, class S = Statistics> typedef McSimulation<SingleVariate,RNG,S>::path_generator_type QuantLib::MCDiscreteAveragingAsianEngine< RNG, S >::path_generator_type
Reimplemented from QuantLib::McSimulation< SingleVariate, RNG, S >.
Reimplemented in QuantLib::MCDiscreteArithmeticAPEngine< RNG, S >, QuantLib::MCDiscreteGeometricAPEngine< RNG, S >, and QuantLib::MCDiscreteArithmeticASEngine< RNG, S >.
Definition at line 47 of file mcdiscreteasianengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> typedef McSimulation<SingleVariate,RNG,S>::path_pricer_type QuantLib::MCDiscreteAveragingAsianEngine< RNG, S >::path_pricer_type
Reimplemented from QuantLib::McSimulation< SingleVariate, RNG, S >.
Reimplemented in QuantLib::MCDiscreteArithmeticAPEngine< RNG, S >, QuantLib::MCDiscreteGeometricAPEngine< RNG, S >, and QuantLib::MCDiscreteArithmeticASEngine< RNG, S >.
Definition at line 49 of file mcdiscreteasianengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> typedef McSimulation<SingleVariate,RNG,S>::stats_type QuantLib::MCDiscreteAveragingAsianEngine< RNG, S >::stats_type
Reimplemented from QuantLib::McSimulation< SingleVariate, RNG, S >.
Reimplemented in QuantLib::MCDiscreteArithmeticAPEngine< RNG, S >, QuantLib::MCDiscreteGeometricAPEngine< RNG, S >, and QuantLib::MCDiscreteArithmeticASEngine< RNG, S >.
Definition at line 51 of file mcdiscreteasianengine.hpp.
Constructor & Destructor Documentation
template<class RNG , class S > QuantLib::MCDiscreteAveragingAsianEngine< RNG, S >::MCDiscreteAveragingAsianEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > & process, bool brownianBridge, bool antitheticVariate, bool controlVariate, Size requiredSamples, Real requiredTolerance, Size maxSamples, BigNatural seed) [inline]
Definition at line 104 of file mcdiscreteasianengine.hpp.
References QuantLib::MCDiscreteAveragingAsianEngine< RNG, S >::process_, and QuantLib::Observer::registerWith().
    : McSimulation<SingleVariate,RNG,S>(antitheticVariate, controlVariate),
      process_(process), requiredSamples_(requiredSamples),
      maxSamples_(maxSamples), requiredTolerance_(requiredTolerance),
      brownianBridge_(brownianBridge), seed_(seed) {
        registerWith(process_);
    }
Member Function Documentation
template<class RNG = PseudoRandom, class S = Statistics> void QuantLib::MCDiscreteAveragingAsianEngine< RNG, S >::calculate () const [inline, virtual]
Implements QuantLib::PricingEngine.
Definition at line 62 of file mcdiscreteasianengine.hpp.
References QuantLib::McSimulation< SingleVariate, RNG, S >::controlVariate_, QuantLib::Instrument::results::errorEstimate, QuantLib::MCDiscreteAveragingAsianEngine< RNG, S >::maxSamples_, QuantLib::McSimulation< SingleVariate, RNG, S >::mcModel_, QuantLib::MCDiscreteAveragingAsianEngine< RNG, S >::requiredSamples_, QuantLib::MCDiscreteAveragingAsianEngine< RNG, S >::requiredTolerance_, QuantLib::GenericEngine< DiscreteAveragingAsianOption::arguments, DiscreteAveragingAsianOption::results >::results_, and QuantLib::Instrument::results::value.
{
            McSimulation<SingleVariate,RNG,S>::calculate(requiredTolerance_,
                                                         requiredSamples_,
                                                         maxSamples_);
            results_.value = this->mcModel_->sampleAccumulator().mean();
            if (this->controlVariate_) {
                // control variate might lead to small negative
                // option values for deep OTM options
                this->results_.value = std::max(0.0, this->results_.value);
            }
            if (RNG::allowsErrorEstimate)
            results_.errorEstimate =
                this->mcModel_->sampleAccumulator().errorEstimate();
        }
template<class RNG , class S > Real QuantLib::MCDiscreteAveragingAsianEngine< RNG, S >::controlVariateValue () const [inline, protected, virtual]
Reimplemented from QuantLib::McSimulation< SingleVariate, RNG, S >.
Definition at line 140 of file mcdiscreteasianengine.hpp.
References QL_REQUIRE, and QuantLib::Instrument::results::value.
{
        boost::shared_ptr<PricingEngine> controlPE =
                this->controlPricingEngine();
            QL_REQUIRE(controlPE,
                       "engine does not provide "
                       "control variation pricing engine");
            DiscreteAveragingAsianOption::arguments* controlArguments =
                dynamic_cast<DiscreteAveragingAsianOption::arguments*>(
                    controlPE->getArguments());
            *controlArguments = arguments_;
            controlPE->calculate();
            const DiscreteAveragingAsianOption::results* controlResults =
                dynamic_cast<const DiscreteAveragingAsianOption::results*>(
                    controlPE->getResults());
            return controlResults->value;
    }
template<class RNG = PseudoRandom, class S = Statistics> boost::shared_ptr<path_generator_type> QuantLib::MCDiscreteAveragingAsianEngine< RNG, S >::pathGenerator () const [inline, protected, virtual]
Implements QuantLib::McSimulation< SingleVariate, RNG, S >.
Definition at line 81 of file mcdiscreteasianengine.hpp.
References QuantLib::MCDiscreteAveragingAsianEngine< RNG, S >::brownianBridge_, QuantLib::MCDiscreteAveragingAsianEngine< RNG, S >::process_, QuantLib::MCDiscreteAveragingAsianEngine< RNG, S >::seed_, QuantLib::TimeGrid::size(), and QuantLib::MCDiscreteAveragingAsianEngine< RNG, S >::timeGrid().
{
            TimeGrid grid = this->timeGrid();
            typename RNG::rsg_type gen =
                RNG::make_sequence_generator(grid.size()-1,seed_);
            return boost::shared_ptr<path_generator_type>(
                         new path_generator_type(process_, grid,
                                                 gen, brownianBridge_));
        }
template<class RNG , class S > TimeGrid QuantLib::MCDiscreteAveragingAsianEngine< RNG, S >::timeGrid () const [inline, protected, virtual]
Implements QuantLib::McSimulation< SingleVariate, RNG, S >.
Definition at line 121 of file mcdiscreteasianengine.hpp.
References anonymous_namespace{quantlibbenchmark.cpp}::t, and QuantLib::DayCounter::yearFraction().
Referenced by QuantLib::MCDiscreteAveragingAsianEngine< RNG, S >::pathGenerator().
{
        Date referenceDate = process_->riskFreeRate()->referenceDate();
        DayCounter voldc = process_->blackVolatility()->dayCounter();
        std::vector<Time> fixingTimes;
        Size i;
        for (i=0; i<arguments_.fixingDates.size(); i++) {
            if (arguments_.fixingDates[i]>=referenceDate) {
                Time t = voldc.yearFraction(referenceDate,
                    arguments_.fixingDates[i]);
                fixingTimes.push_back(t);
            }
        }
        return TimeGrid(fixingTimes.begin(), fixingTimes.end());
    }
Member Data Documentation
template<class RNG = PseudoRandom, class S = Statistics> bool QuantLib::MCDiscreteAveragingAsianEngine< RNG, S >::brownianBridge_ [protected]
Definition at line 95 of file mcdiscreteasianengine.hpp.
Referenced by QuantLib::MCDiscreteAveragingAsianEngine< RNG, S >::pathGenerator().
template<class RNG = PseudoRandom, class S = Statistics> Size QuantLib::MCDiscreteAveragingAsianEngine< RNG, S >::maxSamples_ [protected]
Definition at line 93 of file mcdiscreteasianengine.hpp.
Referenced by QuantLib::MCDiscreteAveragingAsianEngine< RNG, S >::calculate().
template<class RNG = PseudoRandom, class S = Statistics> boost::shared_ptr<GeneralizedBlackScholesProcess> QuantLib::MCDiscreteAveragingAsianEngine< RNG, S >::process_ [protected]
Definition at line 92 of file mcdiscreteasianengine.hpp.
Referenced by QuantLib::MCDiscreteArithmeticAPEngine< RNG, S >::controlPricingEngine(), QuantLib::MCDiscreteAveragingAsianEngine< RNG, S >::MCDiscreteAveragingAsianEngine(), and QuantLib::MCDiscreteAveragingAsianEngine< RNG, S >::pathGenerator().
template<class RNG = PseudoRandom, class S = Statistics> Size QuantLib::MCDiscreteAveragingAsianEngine< RNG, S >::requiredSamples_ [protected]
Definition at line 93 of file mcdiscreteasianengine.hpp.
Referenced by QuantLib::MCDiscreteAveragingAsianEngine< RNG, S >::calculate().
template<class RNG = PseudoRandom, class S = Statistics> Real QuantLib::MCDiscreteAveragingAsianEngine< RNG, S >::requiredTolerance_ [protected]
Definition at line 94 of file mcdiscreteasianengine.hpp.
Referenced by QuantLib::MCDiscreteAveragingAsianEngine< RNG, S >::calculate().
template<class RNG = PseudoRandom, class S = Statistics> BigNatural QuantLib::MCDiscreteAveragingAsianEngine< RNG, S >::seed_ [protected]
Definition at line 96 of file mcdiscreteasianengine.hpp.
Referenced by QuantLib::MCDiscreteAveragingAsianEngine< RNG, S >::pathGenerator().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/asian/mcdiscreteasianengine.hpp