QuantLib: QuantLib::Extrapolator Class Reference
QuantLib::Extrapolator Class Reference
base class for classes possibly allowing extrapolation
#include <extrapolation.hpp>
Public Member Functions
Extrapolator ()
virtual ~Extrapolator ()
modifiers
void enableExtrapolation (bool b=true)
enable extrapolation in subsequent calls
void disableExtrapolation (bool b=true)
disable extrapolation in subsequent calls
inspectors
bool allowsExtrapolation () const
tells whether extrapolation is enabled
Private Attributes
bool extrapolate_
Detailed Description
base class for classes possibly allowing extrapolation
Definition at line 32 of file extrapolation.hpp.
Constructor & Destructor Documentation
QuantLib::Extrapolator::Extrapolator () [inline]
Definition at line 34 of file extrapolation.hpp.
: extrapolate_(false) {}
virtual QuantLib::Extrapolator::~Extrapolator () [inline, virtual]
Definition at line 35 of file extrapolation.hpp.
{}
Member Function Documentation
bool QuantLib::Extrapolator::allowsExtrapolation () const [inline]
tells whether extrapolation is enabled
Definition at line 46 of file extrapolation.hpp.
References extrapolate_.
Referenced by QuantLib::TermStructure::checkRange(), QuantLib::InflationTermStructure::checkRange(), QuantLib::YoYOptionletVolatilitySurface::checkRange(), QuantLib::CPIVolatilitySurface::checkRange(), QuantLib::Interpolation::checkRange(), QuantLib::CallableBondVolatilityStructure::checkRange(), QuantLib::Interpolation2D::checkRange(), QuantLib::VolatilityTermStructure::checkStrike(), and QuantLib::SwaptionVolatilityStructure::checkSwapTenor().
{ return extrapolate_; }
void QuantLib::Extrapolator::disableExtrapolation (bool b = true) [inline]
disable extrapolation in subsequent calls
Definition at line 41 of file extrapolation.hpp.
References anonymous_namespace{marketmodel.cpp}::b, and extrapolate_.
{ extrapolate_ = !b; }
void QuantLib::Extrapolator::enableExtrapolation (bool b = true) [inline]
enable extrapolation in subsequent calls
Definition at line 39 of file extrapolation.hpp.
References anonymous_namespace{marketmodel.cpp}::b, and extrapolate_.
Referenced by QuantLib::InterpolatedYoYCapFloorTermPriceSurface< Interpolator2D, Interpolator1D >::intersect(), QuantLib::SwaptionVolatilityDiscrete::SwaptionVolatilityDiscrete(), InterpolationTest::testAsFunctor(), InterpolationTest::testBackwardFlat(), and InterpolationTest::testForwardFlat().
{ extrapolate_ = b; }
Member Data Documentation
bool QuantLib::Extrapolator::extrapolate_ [private]
Definition at line 49 of file extrapolation.hpp.
Referenced by allowsExtrapolation(), disableExtrapolation(), and enableExtrapolation().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/interpolations/extrapolation.hpp