QuantLib: QuantLib::GaussLobattoIntegral Class Reference
QuantLib::GaussLobattoIntegral Class Reference
Integral of a one-dimensional function.
#include <gausslobattointegral.hpp>
Public Member Functions
GaussLobattoIntegral (Size maxIterations, Real absAccuracy, Real relAccuracy=Null< Real >(), bool useConvergenceEstimate=true)
Protected Member Functions
Real integrate (const boost::function< Real(Real)> &f, Real a, Real b) const
Real adaptivGaussLobattoStep (const boost::function< Real(Real)> &f, Real a, Real b, Real fa, Real fb, Real is) const
Real calculateAbsTolerance (const boost::function< Real(Real)> &f, Real a, Real b) const
Protected Attributes
Real relAccuracy_
const bool useConvergenceEstimate_
Static Protected Attributes
static const Real alpha_ = std::sqrt(2.0/3.0)
static const Real beta_ = 1.0/std::sqrt(5.0)
static const Real x1_ = 0.94288241569547971906
static const Real x2_ = 0.64185334234578130578
static const Real x3_ = 0.23638319966214988028
Detailed Description
Integral of a one-dimensional function.
Given a target accuracy \(\epsilon \), the integral of a function \(f \) between \(a \) and \(b \) is calculated by means of the Gauss-Lobatto formula
References: This algorithm is a C++ implementation of the algorithm outlined in
W. Gander and W. Gautschi, Adaptive Quadrature - Revisited. BIT, 40(1):84-101, March 2000. CS technical report: ftp.inf.ethz.ch/pub/publications/tech-reports/3xx/306.ps.gz
The original MATLAB version can be downloaded here http://www.inf.ethz.ch/personal/gander/adaptlob.m
Definition at line 51 of file gausslobattointegral.hpp.
Constructor & Destructor Documentation
QuantLib::GaussLobattoIntegral::GaussLobattoIntegral (Size maxIterations, Real absAccuracy, Real relAccuracy = Null<Real>(), bool useConvergenceEstimate = true)
Definition at line 35 of file gausslobattointegral.cpp.
    : Integrator(absAccuracy, maxIterations),
      relAccuracy_(relAccuracy),
      useConvergenceEstimate_(useConvergenceEstimate) {
    }
Member Function Documentation
Real QuantLib::GaussLobattoIntegral::adaptivGaussLobattoStep (const boost::function< Real(Real)> & f, Real a, Real b, Real fa, Real fb, Real is) const [protected]
Definition at line 103 of file gausslobattointegral.cpp.
References anonymous_namespace{marketmodel.cpp}::a, alpha_, anonymous_namespace{marketmodel.cpp}::b, beta_, anonymous_namespace{interpolations.cpp}::f(), QuantLib::Integrator::increaseNumberOfEvaluations(), QuantLib::Integrator::maxEvaluations(), QuantLib::Integrator::numberOfEvaluations(), and QL_REQUIRE.
Referenced by integrate().
{
        QL_REQUIRE(numberOfEvaluations() < maxEvaluations(),
                   "max number of iterations reached");
        const Real h=(b-a)/2;
        const Real m=(a+b)/2;
        const Real mll=m-alpha_*h;
        const Real ml =m-beta_*h;
        const Real mr =m+beta_*h;
        const Real mrr=m+alpha_*h;
        const Real fmll= f(mll);
        const Real fml = f(ml);
        const Real fm  = f(m);
        const Real fmr = f(mr);
        const Real fmrr= f(mrr);
        increaseNumberOfEvaluations(5);
        const Real integral2=(h/6)*(fa+fb+5*(fml+fmr));
        const Real integral1=(h/1470)*(77*(fa+fb)
                                       +432*(fmll+fmrr)+625*(fml+fmr)+672*fm);
        // avoid 80 bit logic on x86 cpu
        volatile Real dist = acc + (integral1-integral2);
        if(dist==acc || mll<=a || b<=mrr) {
            QL_REQUIRE(m>a && b>m,"Interval contains no more machine number");
            return integral1;
        }
        else {
            return  adaptivGaussLobattoStep(f,a,mll,fa,fmll,acc)
                  + adaptivGaussLobattoStep(f,mll,ml,fmll,fml,acc)
                  + adaptivGaussLobattoStep(f,ml,m,fml,fm,acc)
                  + adaptivGaussLobattoStep(f,m,mr,fm,fmr,acc)
                  + adaptivGaussLobattoStep(f,mr,mrr,fmr,fmrr,acc)
                  + adaptivGaussLobattoStep(f,mrr,b,fmrr,fb,acc);
        }
    }
Real QuantLib::GaussLobattoIntegral::calculateAbsTolerance (const boost::function< Real(Real)> & f, Real a, Real b) const [protected]
Definition at line 55 of file gausslobattointegral.cpp.
References anonymous_namespace{marketmodel.cpp}::a, QuantLib::Integrator::absoluteAccuracy(), alpha_, anonymous_namespace{marketmodel.cpp}::b, beta_, anonymous_namespace{interpolations.cpp}::f(), QuantLib::Integrator::increaseNumberOfEvaluations(), QL_EPSILON, QL_REQUIRE, relAccuracy_, useConvergenceEstimate_, x1_, x2_, and x3_.
Referenced by integrate().
{
        Real relTol = std::max(relAccuracy_, QL_EPSILON);
        const Real m = (a+b)/2;
        const Real h = (b-a)/2;
        const Real y1 = f(a);
        const Real y3 = f(m-alpha_*h);
        const Real y5 = f(m-beta_*h);
        const Real y7 = f(m);
        const Real y9 = f(m+beta_*h);
        const Real y11= f(m+alpha_*h);
        const Real y13= f(b);
        Real acc=h*(0.0158271919734801831*(y1+y13)
                  +0.0942738402188500455*(f(m-x1_*h)+f(m+x1_*h))
                  +0.1550719873365853963*(y3+y11)
                  +0.1888215739601824544*(f(m-x2_*h)+ f(m+x2_*h))
                  +0.1997734052268585268*(y5+y9)
                  +0.2249264653333395270*(f(m-x3_*h)+f(m+x3_*h))
                  +0.2426110719014077338*y7);
        increaseNumberOfEvaluations(13);
        QL_REQUIRE(acc != 0.0, "can not calculate absolute accuracy from "
                               "relative accuracy");
        Real r = 1.0;
        if (useConvergenceEstimate_) {
            const Real integral2 = (h/6)*(y1+y13+5*(y5+y9));
            const Real integral1 = (h/1470)*(77*(y1+y13)+432*(y3+y11)+
                                             625*(y5+y9)+672*y7);
            if (std::fabs(integral2-acc) != 0.0)
                r = std::fabs(integral1-acc)/std::fabs(integral2-acc);
            if (r == 0.0 || r > 1.0)
                r = 1.0;
        }
        if (relAccuracy_ != Null<Real>())
            return std::min(absoluteAccuracy(), acc*relTol)/(r*QL_EPSILON);
        else {
            return absoluteAccuracy()/(r*QL_EPSILON);
        }
    }
Real QuantLib::GaussLobattoIntegral::integrate (const boost::function< Real(Real)> & f, Real a, Real b) const [protected, virtual]
Implements QuantLib::Integrator.
Definition at line 44 of file gausslobattointegral.cpp.
References adaptivGaussLobattoStep(), calculateAbsTolerance(), anonymous_namespace{interpolations.cpp}::f(), QuantLib::Integrator::increaseNumberOfEvaluations(), and QuantLib::Integrator::setNumberOfEvaluations().
{
        setNumberOfEvaluations(0);
        const Real calcAbsTolerance = calculateAbsTolerance(f, a, b);
        increaseNumberOfEvaluations(2);
        return adaptivGaussLobattoStep(f, a, b, f(a), f(b), calcAbsTolerance);
    }
Member Data Documentation
const Real QuantLib::GaussLobattoIntegral::alpha_ = std::sqrt(2.0/3.0) [static, protected]
Definition at line 70 of file gausslobattointegral.hpp.
Referenced by adaptivGaussLobattoStep(), and calculateAbsTolerance().
const Real QuantLib::GaussLobattoIntegral::beta_ = 1.0/std::sqrt(5.0) [static, protected]
Definition at line 70 of file gausslobattointegral.hpp.
Referenced by adaptivGaussLobattoStep(), and calculateAbsTolerance().
Real QuantLib::GaussLobattoIntegral::relAccuracy_ [protected]
Definition at line 68 of file gausslobattointegral.hpp.
Referenced by calculateAbsTolerance().
const bool QuantLib::GaussLobattoIntegral::useConvergenceEstimate_ [protected]
Definition at line 69 of file gausslobattointegral.hpp.
Referenced by calculateAbsTolerance().
const Real QuantLib::GaussLobattoIntegral::x1_ = 0.94288241569547971906 [static, protected]
Definition at line 70 of file gausslobattointegral.hpp.
Referenced by calculateAbsTolerance().
const Real QuantLib::GaussLobattoIntegral::x2_ = 0.64185334234578130578 [static, protected]
Definition at line 70 of file gausslobattointegral.hpp.
Referenced by calculateAbsTolerance().
const Real QuantLib::GaussLobattoIntegral::x3_ = 0.23638319966214988028 [static, protected]
Definition at line 70 of file gausslobattointegral.hpp.
Referenced by calculateAbsTolerance().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/integrals/gausslobattointegral.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/math/integrals/gausslobattointegral.cpp