QuantLib: QuantLib::NelsonSiegelFitting Class Reference
QuantLib::NelsonSiegelFitting Class Reference
Nelson-Siegel fitting method.
#include <nonlinearfittingmethods.hpp>
Public Member Functions
NelsonSiegelFitting ()
std::auto_ptr
< FittedBondDiscountCurve::FittingMethod > clone () const
clone of the current object
Private Member Functions
Size size () const
total number of coefficients to fit/solve for
DiscountFactor discountFunction (const Array &x, Time t) const
derived classes must set this
Detailed Description
Nelson-Siegel fitting method.
Fits a discount function to the form \(d(t) = \exp^{-r t}, \) where the zero rate \(r\) is defined as
\[ r \equiv c_0 + (c_0 + c_1)*(1 - exp^{-\kappa*t}/(\kappa t) - c_2 exp^{ - \kappa t}. \]
See: Nelson, C. and A. Siegel (1985): "Parsimonious modeling of yield curves for US Treasury bills." NBER Working Paper Series, no 1594.
Definition at line 66 of file nonlinearfittingmethods.hpp.
Constructor & Destructor Documentation
QuantLib::NelsonSiegelFitting::NelsonSiegelFitting ()
Definition at line 66 of file nonlinearfittingmethods.cpp.
Referenced by clone().
    : FittedBondDiscountCurve::FittingMethod(true) {}
Member Function Documentation
std::auto_ptr< FittedBondDiscountCurve::FittingMethod > QuantLib::NelsonSiegelFitting::clone () const [virtual]
clone of the current object
Implements QuantLib::FittedBondDiscountCurve::FittingMethod.
Definition at line 70 of file nonlinearfittingmethods.cpp.
References NelsonSiegelFitting().
{
        return std::auto_ptr<FittedBondDiscountCurve::FittingMethod>(
                                              new NelsonSiegelFitting(*this));
    }
DiscountFactor QuantLib::NelsonSiegelFitting::discountFunction (const Array & x, Time t) const [private, virtual]
derived classes must set this
user-defined discount curve, as a function of time and an array of unknown fitting coefficients \(x_i \).
Implements QuantLib::FittedBondDiscountCurve::FittingMethod.
Definition at line 79 of file nonlinearfittingmethods.cpp.
References anonymous_namespace{marketmodel.cpp}::d, QL_EPSILON, and size().
{
        Real kappa = x[size()-1];
        Real zeroRate = x[0] + (x[1] + x[2])*
                        (1.0 - std::exp(-kappa*t))/
                        ((kappa+QL_EPSILON)*(t+QL_EPSILON)) -
                        (x[2])*std::exp(-kappa*t);
        DiscountFactor d = std::exp(-zeroRate * t) ;
        return d;
    }
Size QuantLib::NelsonSiegelFitting::size () const [private, virtual]
total number of coefficients to fit/solve for
Implements QuantLib::FittedBondDiscountCurve::FittingMethod.
Definition at line 75 of file nonlinearfittingmethods.cpp.
Referenced by discountFunction().
{
        return 4;
    }
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/yield/nonlinearfittingmethods.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/yield/nonlinearfittingmethods.cpp