QuantLib: QuantLib::CapFloorTermVolSurface Class Reference
QuantLib::CapFloorTermVolSurface Class Reference
Cap/floor smile volatility surface.
#include <capfloortermvolsurface.hpp>
Public Member Functions
CapFloorTermVolSurface (Natural settlementDays, const Calendar &calendar, BusinessDayConvention bdc, const std::vector< Period > &optionTenors, const std::vector< Rate > &strikes, const std::vector< std::vector< Handle< Quote > > > &, const DayCounter &dc=Actual365Fixed())
floating reference date, floating market data
CapFloorTermVolSurface (const Date &settlementDate, const Calendar &calendar, BusinessDayConvention bdc, const std::vector< Period > &optionTenors, const std::vector< Rate > &strikes, const std::vector< std::vector< Handle< Quote > > > &, const DayCounter &dc=Actual365Fixed())
fixed reference date, floating market data
CapFloorTermVolSurface (const Date &settlementDate, const Calendar &calendar, BusinessDayConvention bdc, const std::vector< Period > &optionTenors, const std::vector< Rate > &strikes, const Matrix &volatilities, const DayCounter &dc=Actual365Fixed())
fixed reference date, fixed market data
CapFloorTermVolSurface (Natural settlementDays, const Calendar &calendar, BusinessDayConvention bdc, const std::vector< Period > &optionTenors, const std::vector< Rate > &strikes, const Matrix &volatilities, const DayCounter &dc=Actual365Fixed())
floating reference date, fixed market data
TermStructure interface
Date maxDate () const
the latest date for which the curve can return values
VolatilityTermStructure interface
Real minStrike () const
the minimum strike for which the term structure can return vols
Real maxStrike () const
the maximum strike for which the term structure can return vols
LazyObject interface
void update ()
void performCalculations () const
some inspectors
const std::vector< Period > & optionTenors () const
const std::vector< Date > & optionDates () const
const std::vector< Time > & optionTimes () const
const std::vector< Rate > & strikes () const
Protected Member Functions
Volatility volatilityImpl (Time t, Rate strike) const
implements the actual volatility calculation in derived classes
Private Member Functions
void checkInputs () const
void initializeOptionDatesAndTimes () const
void registerWithMarketData ()
void interpolate ()
Private Attributes
Size nOptionTenors_
std::vector< Period > optionTenors_
std::vector< Date > optionDates_
std::vector< Time > optionTimes_
Date evaluationDate_
Size nStrikes_
std::vector< Rate > strikes_
std::vector< std::vector
< Handle< Quote > > > volHandles_
Matrix vols_
Interpolation2D interpolation_
Detailed Description
Cap/floor smile volatility surface.
This class provides the volatility for a given cap/floor interpolating a volatility surface whose elements are the market term volatilities of a set of caps/floors with given length and given strike.
Definition at line 41 of file capfloortermvolsurface.hpp.
Constructor & Destructor Documentation
QuantLib::CapFloorTermVolSurface::CapFloorTermVolSurface (Natural settlementDays, const Calendar & calendar, BusinessDayConvention bdc, const std::vector< Period > & optionTenors, const std::vector< Rate > & strikes, const std::vector< std::vector< Handle< Quote > > > & vols, const DayCounter & dc = Actual365Fixed())
floating reference date, floating market data
Definition at line 29 of file capfloortermvolsurface.cpp.
References checkInputs(), QuantLib::Matrix::columns(), initializeOptionDatesAndTimes(), interpolate(), nOptionTenors_, nStrikes_, QuantLib::io::ordinal(), QL_REQUIRE, registerWithMarketData(), QuantLib::Matrix::rows(), volHandles_, and vols_.
    : CapFloorTermVolatilityStructure(settlementDays, calendar, bdc, dc),
      nOptionTenors_(optionTenors.size()),
      optionTenors_(optionTenors),
      optionDates_(nOptionTenors_),
      optionTimes_(nOptionTenors_),
      nStrikes_(strikes.size()),
      strikes_(strikes),
      volHandles_(vols),
      vols_(vols.size(), vols[0].size())
    {
        checkInputs();
        initializeOptionDatesAndTimes();
        for (Size i=0; i<nOptionTenors_; ++i)
            QL_REQUIRE(volHandles_[i].size()==nStrikes_,
                       io::ordinal(i+1) << " row of vol handles has size " <<
                       volHandles_[i].size() << " instead of " << nStrikes_);
        registerWithMarketData();
        for (Size i=0; i<vols_.rows(); ++i)
            for (Size j=0; j<vols_.columns(); ++j)
                vols_[i][j] = volHandles_[i][j]->value();
        interpolate();
    }
QuantLib::CapFloorTermVolSurface::CapFloorTermVolSurface (const Date & settlementDate, const Calendar & calendar, BusinessDayConvention bdc, const std::vector< Period > & optionTenors, const std::vector< Rate > & strikes, const std::vector< std::vector< Handle< Quote > > > & vols, const DayCounter & dc = Actual365Fixed())
fixed reference date, floating market data
Definition at line 61 of file capfloortermvolsurface.cpp.
References checkInputs(), QuantLib::Matrix::columns(), initializeOptionDatesAndTimes(), interpolate(), nOptionTenors_, nStrikes_, QuantLib::io::ordinal(), QL_REQUIRE, registerWithMarketData(), QuantLib::Matrix::rows(), volHandles_, and vols_.
    : CapFloorTermVolatilityStructure(settlementDate, calendar, bdc, dc),
      nOptionTenors_(optionTenors.size()),
      optionTenors_(optionTenors),
      optionDates_(nOptionTenors_),
      optionTimes_(nOptionTenors_),
      nStrikes_(strikes.size()),
      strikes_(strikes),
      volHandles_(vols),
      vols_(vols.size(), vols[0].size())
    {
        checkInputs();
        initializeOptionDatesAndTimes();
        for (Size i=0; i<nOptionTenors_; ++i)
            QL_REQUIRE(volHandles_[i].size()==nStrikes_,
                       io::ordinal(i+1) << " row of vol handles has size " <<
                       volHandles_[i].size() << " instead of " << nStrikes_);
        registerWithMarketData();
        for (Size i=0; i<vols_.rows(); ++i)
            for (Size j=0; j<vols_.columns(); ++j)
                vols_[i][j] = volHandles_[i][j]->value();
        interpolate();
    }
QuantLib::CapFloorTermVolSurface::CapFloorTermVolSurface (const Date & settlementDate, const Calendar & calendar, BusinessDayConvention bdc, const std::vector< Period > & optionTenors, const std::vector< Rate > & strikes, const Matrix & volatilities, const DayCounter & dc = Actual365Fixed())
fixed reference date, fixed market data
Definition at line 93 of file capfloortermvolsurface.cpp.
References checkInputs(), initializeOptionDatesAndTimes(), interpolate(), nOptionTenors_, nStrikes_, volHandles_, and vols_.
    : CapFloorTermVolatilityStructure(settlementDate, calendar, bdc, dc),
      nOptionTenors_(optionTenors.size()),
      optionTenors_(optionTenors),
      optionDates_(nOptionTenors_),
      optionTimes_(nOptionTenors_),
      nStrikes_(strikes.size()),
      strikes_(strikes),
      volHandles_(vols.rows()),
      vols_(vols)
    {
        checkInputs();
        initializeOptionDatesAndTimes();
        // fill dummy handles to allow generic handle-based computations later
        for (Size i=0; i<nOptionTenors_; ++i) {
            volHandles_[i].resize(nStrikes_);
            for (Size j=0; j<nStrikes_; ++j)
                volHandles_[i][j] = Handle<Quote>(boost::shared_ptr<Quote>(new
                    SimpleQuote(vols_[i][j])));
        }
        interpolate();
    }
QuantLib::CapFloorTermVolSurface::CapFloorTermVolSurface (Natural settlementDays, const Calendar & calendar, BusinessDayConvention bdc, const std::vector< Period > & optionTenors, const std::vector< Rate > & strikes, const Matrix & volatilities, const DayCounter & dc = Actual365Fixed())
floating reference date, fixed market data
Definition at line 124 of file capfloortermvolsurface.cpp.
References checkInputs(), initializeOptionDatesAndTimes(), interpolate(), nOptionTenors_, nStrikes_, volHandles_, and vols_.
    : CapFloorTermVolatilityStructure(settlementDays, calendar, bdc, dc),
      nOptionTenors_(optionTenors.size()),
      optionTenors_(optionTenors),
      optionDates_(nOptionTenors_),
      optionTimes_(nOptionTenors_),
      nStrikes_(strikes.size()),
      strikes_(strikes),
      volHandles_(vols.rows()),
      vols_(vols)
    {
        checkInputs();
        initializeOptionDatesAndTimes();
        // fill dummy handles to allow generic handle-based computations later
        for (Size i=0; i<nOptionTenors_; ++i) {
            volHandles_[i].resize(nStrikes_);
            for (Size j=0; j<nStrikes_; ++j)
                volHandles_[i][j] = Handle<Quote>(boost::shared_ptr<Quote>(new
                    SimpleQuote(vols_[i][j])));
        }
        interpolate();
    }
Member Function Documentation
void QuantLib::CapFloorTermVolSurface::checkInputs () const [private]
Definition at line 154 of file capfloortermvolsurface.cpp.
References QuantLib::Matrix::columns(), QuantLib::Days, nOptionTenors_, nStrikes_, optionTenors_, QuantLib::io::ordinal(), QL_REQUIRE, QuantLib::io::rate(), QuantLib::Matrix::rows(), strikes_, and vols_.
Referenced by CapFloorTermVolSurface().
{
        QL_REQUIRE(!optionTenors_.empty(), "empty option tenor vector");
        QL_REQUIRE(nOptionTenors_==vols_.rows(),
                   "mismatch between number of option tenors (" <<
                   nOptionTenors_ << ") and number of volatility rows (" <<
                   vols_.rows() << ")");
        QL_REQUIRE(optionTenors_[0]>0*Days,
                   "negative first option tenor: " << optionTenors_[0]);
        for (Size i=1; i<nOptionTenors_; ++i)
            QL_REQUIRE(optionTenors_[i]>optionTenors_[i-1],
                       "non increasing option tenor: " << io::ordinal(i) <<
                       " is " << optionTenors_[i-1] << ", " <<
                       io::ordinal(i+1) << " is " << optionTenors_[i]);
        QL_REQUIRE(nStrikes_==vols_.columns(),
                   "mismatch between strikes(" << strikes_.size() <<
                   ") and vol columns (" << vols_.columns() << ")");
        for (Size j=1; j<nStrikes_; ++j)
            QL_REQUIRE(strikes_[j-1]<strikes_[j],
                       "non increasing strikes: " << io::ordinal(j) <<
                       " is " << io::rate(strikes_[j-1]) << ", " <<
                       io::ordinal(j+1) << " is " << io::rate(strikes_[j]));
    }
void QuantLib::CapFloorTermVolSurface::initializeOptionDatesAndTimes () const [private]
Definition at line 209 of file capfloortermvolsurface.cpp.
References nOptionTenors_, QuantLib::VolatilityTermStructure::optionDateFromTenor(), optionDates_, optionTenors_, optionTimes_, and QuantLib::TermStructure::timeFromReference().
Referenced by CapFloorTermVolSurface(), and update().
    {
        for (Size i=0; i<nOptionTenors_; ++i) {
            optionDates_[i] = optionDateFromTenor(optionTenors_[i]);
            optionTimes_[i] = timeFromReference(optionDates_[i]);
        }
    }
void QuantLib::CapFloorTermVolSurface::interpolate () [private]
Definition at line 186 of file capfloortermvolsurface.cpp.
References interpolation_, optionTimes_, strikes_, and vols_.
Referenced by CapFloorTermVolSurface().
    {
        interpolation_ = BicubicSpline(strikes_.begin(),
                                       strikes_.end(),
                                       optionTimes_.begin(),
                                       optionTimes_.end(),
                                       vols_);
    }
Date QuantLib::CapFloorTermVolSurface::maxDate () const [inline, virtual]
the latest date for which the curve can return values
Implements QuantLib::TermStructure.
Definition at line 124 of file capfloortermvolsurface.hpp.
References QuantLib::LazyObject::calculate(), QuantLib::VolatilityTermStructure::optionDateFromTenor(), and optionTenors_.
{
        calculate();
        return optionDateFromTenor(optionTenors_.back());
    }
Real QuantLib::CapFloorTermVolSurface::maxStrike () const [inline, virtual]
the maximum strike for which the term structure can return vols
Implements QuantLib::VolatilityTermStructure.
Definition at line 133 of file capfloortermvolsurface.hpp.
References strikes_.
{
        return strikes_.back();
    }
Real QuantLib::CapFloorTermVolSurface::minStrike () const [inline, virtual]
the minimum strike for which the term structure can return vols
Implements QuantLib::VolatilityTermStructure.
Definition at line 129 of file capfloortermvolsurface.hpp.
References strikes_.
{
        return strikes_.front();
    }
const std::vector< Date > & QuantLib::CapFloorTermVolSurface::optionDates () const [inline]
Definition at line 150 of file capfloortermvolsurface.hpp.
References QuantLib::LazyObject::calculate(), and optionDates_.
{
        // what if quotes are not available?
        calculate();
        return optionDates_;
    }
const std::vector< Period > & QuantLib::CapFloorTermVolSurface::optionTenors () const [inline]
Definition at line 145 of file capfloortermvolsurface.hpp.
References optionTenors_.
{
        return optionTenors_;
    }
const std::vector< Time > & QuantLib::CapFloorTermVolSurface::optionTimes () const [inline]
Definition at line 157 of file capfloortermvolsurface.hpp.
References QuantLib::LazyObject::calculate(), and optionTimes_.
{
        // what if quotes are not available?
        calculate();
        return optionTimes_;
    }
void QuantLib::CapFloorTermVolSurface::performCalculations () const [virtual]
This method must implement any calculations which must be (re)done in order to calculate the desired results.
Implements QuantLib::LazyObject.
Definition at line 217 of file capfloortermvolsurface.cpp.
References interpolation_, nOptionTenors_, nStrikes_, QuantLib::Interpolation2D::update(), volHandles_, and vols_.
    {
        // check if date recalculation must be called here
        for (Size i=0; i<nOptionTenors_; ++i)
            for (Size j=0; j<nStrikes_; ++j)
                vols_[i][j] = volHandles_[i][j]->value();
        interpolation_.update();
    }
void QuantLib::CapFloorTermVolSurface::registerWithMarketData () [private]
Definition at line 179 of file capfloortermvolsurface.cpp.
References nOptionTenors_, nStrikes_, QuantLib::Observer::registerWith(), and volHandles_.
Referenced by CapFloorTermVolSurface().
    {
        for (Size i=0; i<nOptionTenors_; ++i)
            for (Size j=0; j<nStrikes_; ++j)
                registerWith(volHandles_[i][j]);
    }
const std::vector< Rate > & QuantLib::CapFloorTermVolSurface::strikes () const [inline]
Definition at line 163 of file capfloortermvolsurface.hpp.
References strikes_.
{
        return strikes_;
    }
void QuantLib::CapFloorTermVolSurface::update () [virtual]
This method must be implemented in derived classes. An instance of Observer does not call this method directly: instead, it will be called by the observables the instance registered with when they need to notify any changes.
Reimplemented from QuantLib::LazyObject.
Definition at line 195 of file capfloortermvolsurface.cpp.
References anonymous_namespace{marketmodel.cpp}::d, QuantLib::Settings::evaluationDate(), evaluationDate_, initializeOptionDatesAndTimes(), QuantLib::Singleton< Settings >::instance(), and QuantLib::TermStructure::moving_.
    {
        // recalculate dates if necessary...
        if (moving_) {
            Date d = Settings::instance().evaluationDate();
            if (evaluationDate_ != d) {
                evaluationDate_ = d;
                initializeOptionDatesAndTimes();
            }
        }
        CapFloorTermVolatilityStructure::update();
        LazyObject::update();
    }
Volatility QuantLib::CapFloorTermVolSurface::volatilityImpl (Time length, Rate strike) const [inline, protected, virtual]
implements the actual volatility calculation in derived classes
Implements QuantLib::CapFloorTermVolatilityStructure.
Definition at line 138 of file capfloortermvolsurface.hpp.
References QuantLib::LazyObject::calculate(), and interpolation_.
{
        calculate();
        return interpolation_(strike, t, true);
    }
Member Data Documentation
Date QuantLib::CapFloorTermVolSurface::evaluationDate_ [private]
Definition at line 110 of file capfloortermvolsurface.hpp.
Referenced by update().
Interpolation2D QuantLib::CapFloorTermVolSurface::interpolation_ [mutable, private]
Definition at line 119 of file capfloortermvolsurface.hpp.
Referenced by interpolate(), performCalculations(), and volatilityImpl().
Size QuantLib::CapFloorTermVolSurface::nOptionTenors_ [private]
Definition at line 106 of file capfloortermvolsurface.hpp.
Referenced by CapFloorTermVolSurface(), checkInputs(), initializeOptionDatesAndTimes(), performCalculations(), and registerWithMarketData().
Size QuantLib::CapFloorTermVolSurface::nStrikes_ [private]
Definition at line 112 of file capfloortermvolsurface.hpp.
Referenced by CapFloorTermVolSurface(), checkInputs(), performCalculations(), and registerWithMarketData().
std::vector<Date> QuantLib::CapFloorTermVolSurface::optionDates_ [mutable, private]
Definition at line 108 of file capfloortermvolsurface.hpp.
Referenced by initializeOptionDatesAndTimes(), and optionDates().
std::vector<Period> QuantLib::CapFloorTermVolSurface::optionTenors_ [private]
Definition at line 107 of file capfloortermvolsurface.hpp.
Referenced by checkInputs(), initializeOptionDatesAndTimes(), maxDate(), and optionTenors().
std::vector<Time> QuantLib::CapFloorTermVolSurface::optionTimes_ [mutable, private]
Definition at line 109 of file capfloortermvolsurface.hpp.
Referenced by initializeOptionDatesAndTimes(), interpolate(), and optionTimes().
std::vector<Rate> QuantLib::CapFloorTermVolSurface::strikes_ [private]
Definition at line 113 of file capfloortermvolsurface.hpp.
Referenced by checkInputs(), interpolate(), maxStrike(), minStrike(), and strikes().
std::vector<std::vector<Handle<Quote> > > QuantLib::CapFloorTermVolSurface::volHandles_ [private]
Definition at line 115 of file capfloortermvolsurface.hpp.
Referenced by CapFloorTermVolSurface(), performCalculations(), and registerWithMarketData().
Matrix QuantLib::CapFloorTermVolSurface::vols_ [mutable, private]
Definition at line 116 of file capfloortermvolsurface.hpp.
Referenced by CapFloorTermVolSurface(), checkInputs(), interpolate(), and performCalculations().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/capfloor/capfloortermvolsurface.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/capfloor/capfloortermvolsurface.cpp