QuantLib: CashFlowsTest Class Reference
CashFlowsTest Class Reference
#include <cashflows.hpp>
Static Public Member Functions
static void testSettings ()
static void testAccessViolation ()
static
boost::unit_test_framework::test_suite * suite ()
Detailed Description
Definition at line 25 of file cashflows.hpp.
Member Function Documentation
test_suite * CashFlowsTest::suite () [static]
Definition at line 215 of file cashflows.cpp.
References QUANTLIB_TEST_CASE, testAccessViolation(), and testSettings().
Referenced by init_unit_test_suite().
{
    test_suite* suite = BOOST_TEST_SUITE("Cash flows tests");
    suite->add(QUANTLIB_TEST_CASE(&CashFlowsTest::testSettings));
    suite->add(QUANTLIB_TEST_CASE(&CashFlowsTest::testAccessViolation));
    return suite;
}
void CashFlowsTest::testAccessViolation () [static]
Definition at line 170 of file cashflows.cpp.
References QuantLib::April, anonymous_namespace{marketmodel.cpp}::calendar, QuantLib::December, anonymous_namespace{marketmodel.cpp}::endDate, QuantLib::Settings::evaluationDate(), QuantLib::flatRate(), QuantLib::Singleton< Settings >::instance(), QuantLib::ModifiedFollowing, QuantLib::Months, QuantLib::September, anonymous_namespace{marketmodel.cpp}::startDate, anonymous_namespace{marketmodel.cpp}::todaysDate, and QuantLib::io::volatility().
Referenced by suite().
{
    BOOST_MESSAGE("Testing dynamic cast of coupon in Black pricer...");
    SavedSettings backup;
    Date todaysDate(7, April, 2010);
    Date settlementDate(9, April, 2010);
    Settings::instance().evaluationDate() = todaysDate;
    Calendar calendar = TARGET();
    Handle<YieldTermStructure> rhTermStructure(
        flatRate(settlementDate, 0.04875825, Actual365Fixed()));
    Volatility volatility = 0.10;
    Handle<OptionletVolatilityStructure> vol;
    vol = Handle<OptionletVolatilityStructure>(
             boost::shared_ptr<OptionletVolatilityStructure>(
                 new ConstantOptionletVolatility(
                             2,
                             calendar,
                             ModifiedFollowing,
                             volatility,
                             Actual365Fixed())));
    boost::shared_ptr<IborIndex> index3m (new USDLibor(3*Months,
                                                       rhTermStructure));
    Date payDate(20, December, 2013);
    Date startDate(20, September, 2013);
    Date endDate(20, December, 2013);
    Rate spread = 0.0115;
    boost::shared_ptr<IborCouponPricer> pricer(new BlackIborCouponPricer(vol));
    boost::shared_ptr<FloatingRateCoupon> coupon(
        new FloatingRateCoupon(payDate,100, startDate, endDate, 2,
                               index3m, 1.0 , spread / 100));
    coupon->setPricer(pricer);
    try {
        // this caused an access violation in version 1.0
        coupon->amount();
    } catch (Error&) {
        // ok; proper exception thrown
    }
}
void CashFlowsTest::testSettings () [static]
Definition at line 36 of file cashflows.cpp.
References QuantLib::Annual, CHECK_INCLUSION, CHECK_NPV, QuantLib::Continuous, QuantLib::Settings::evaluationDate(), QuantLib::Settings::includeReferenceDateEvents(), QuantLib::Settings::includeTodaysCashFlows(), QuantLib::Singleton< Settings >::instance(), and anonymous_namespace{marketmodel.cpp}::todaysDate.
Referenced by suite().
{
    BOOST_MESSAGE("Testing cash-flow settings...");
    SavedSettings backup;
    Date today = Date::todaysDate();
    Settings::instance().evaluationDate() = today;
    // cash flows at T+0, T+1, T+2
    std::vector<shared_ptr<CashFlow> > leg;
    for (Integer i=0; i<3; ++i)
        leg.push_back(shared_ptr<CashFlow>(new SimpleCashFlow(1.0, today+i)));
    #define CHECK_INCLUSION(n, days, expected) \
    if ((!leg[n]->hasOccurred(today+days)) != expected) { \
        BOOST_ERROR("cashflow at T+" << n << " " \
                    << (expected ? "not" : "") << "included" \
                    << " at T+" << days); \
    }
    // case 1: don't include reference-date payments, no override at
    //         today's date
    Settings::instance().includeReferenceDateEvents() = false;
    Settings::instance().includeTodaysCashFlows() = none;
    CHECK_INCLUSION(0, 0, false);
    CHECK_INCLUSION(0, 1, false);
    CHECK_INCLUSION(1, 0, true);
    CHECK_INCLUSION(1, 1, false);
    CHECK_INCLUSION(1, 2, false);
    CHECK_INCLUSION(2, 1, true);
    CHECK_INCLUSION(2, 2, false);
    CHECK_INCLUSION(2, 3, false);
    // case 2: same, but with explicit setting at today's date
    Settings::instance().includeReferenceDateEvents() = false;
    Settings::instance().includeTodaysCashFlows() = false;
    CHECK_INCLUSION(0, 0, false);
    CHECK_INCLUSION(0, 1, false);
    CHECK_INCLUSION(1, 0, true);
    CHECK_INCLUSION(1, 1, false);
    CHECK_INCLUSION(1, 2, false);
    CHECK_INCLUSION(2, 1, true);
    CHECK_INCLUSION(2, 2, false);
    CHECK_INCLUSION(2, 3, false);
    // case 3: do include reference-date payments, no override at
    //         today's date
    Settings::instance().includeReferenceDateEvents() = true;
    Settings::instance().includeTodaysCashFlows() = none;
    CHECK_INCLUSION(0, 0, true);
    CHECK_INCLUSION(0, 1, false);
    CHECK_INCLUSION(1, 0, true);
    CHECK_INCLUSION(1, 1, true);
    CHECK_INCLUSION(1, 2, false);
    CHECK_INCLUSION(2, 1, true);
    CHECK_INCLUSION(2, 2, true);
    CHECK_INCLUSION(2, 3, false);
    // case 4: do include reference-date payments, explicit (and same)
    //         setting at today's date
    Settings::instance().includeReferenceDateEvents() = true;
    Settings::instance().includeTodaysCashFlows() = true;
    CHECK_INCLUSION(0, 0, true);
    CHECK_INCLUSION(0, 1, false);
    CHECK_INCLUSION(1, 0, true);
    CHECK_INCLUSION(1, 1, true);
    CHECK_INCLUSION(1, 2, false);
    CHECK_INCLUSION(2, 1, true);
    CHECK_INCLUSION(2, 2, true);
    CHECK_INCLUSION(2, 3, false);
    // case 5: do include reference-date payments, override at
    //         today's date
    Settings::instance().includeReferenceDateEvents() = true;
    Settings::instance().includeTodaysCashFlows() = false;
    CHECK_INCLUSION(0, 0, false);
    CHECK_INCLUSION(0, 1, false);
    CHECK_INCLUSION(1, 0, true);
    CHECK_INCLUSION(1, 1, true);
    CHECK_INCLUSION(1, 2, false);
    CHECK_INCLUSION(2, 1, true);
    CHECK_INCLUSION(2, 2, true);
    CHECK_INCLUSION(2, 3, false);
    // no discount to make calculations easier
    InterestRate no_discount(0.0, Actual365Fixed(), Continuous, Annual);
    #define CHECK_NPV(includeRef, expected)                             \
    do {                                                            \
        Real NPV = CashFlows::npv(leg, no_discount, includeRef, today); \
        if (std::fabs(NPV - expected) > 1e-6) {                         \
            BOOST_ERROR("NPV mismatch:\n"                               \
                        << "    calculated: " << NPV << "\n"            \
                        << "    expected: " << expected);               \
        }                                                               \
    } while (false);
    // no override
    Settings::instance().includeTodaysCashFlows() = none;
    CHECK_NPV(false, 2.0);
    CHECK_NPV(true, 3.0);
    // override
    Settings::instance().includeTodaysCashFlows() = false;
    CHECK_NPV(false, 2.0);
    CHECK_NPV(true, 2.0);
}
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/cashflows.hpp
/home/deriversatile/QuantLib/QuantLibQt/test-suite/cashflows.cpp