QuantLib: QuantLib::MakeSwaption Class Reference
QuantLib::MakeSwaption Class Reference
helper class
#include <makeswaption.hpp>
Public Member Functions
MakeSwaption (const boost::shared_ptr< SwapIndex > &swapIndex, const Period &optionTenor, Rate strike=Null< Rate >())
operator Swaption () const
operator boost::shared_ptr< Swaption > () const
MakeSwaption & withSettlementType (Settlement::Type delivery)
MakeSwaption & withOptionConvention (BusinessDayConvention bdc)
MakeSwaption & withExerciseDate (const Date &)
MakeSwaption & withPricingEngine (const boost::shared_ptr< PricingEngine > &engine)
Private Attributes
boost::shared_ptr< SwapIndex > swapIndex_
Settlement::Type delivery_
boost::shared_ptr< VanillaSwap > underlyingSwap_
Period optionTenor_
BusinessDayConvention optionConvention_
Date fixingDate_
Date exerciseDate_
boost::shared_ptr< Exercise > exercise_
Rate strike_
boost::shared_ptr< PricingEngine > engine_
Detailed Description
helper class
This class provides a more comfortable way to instantiate standard market swaption.
Definition at line 44 of file makeswaption.hpp.
Constructor & Destructor Documentation
QuantLib::MakeSwaption::MakeSwaption (const boost::shared_ptr< SwapIndex > & swapIndex, const Period & optionTenor, Rate strike = Null<Rate>())
Definition at line 31 of file makeswaption.cpp.
    : swapIndex_(swapIndex),
      delivery_(Settlement::Physical),
      optionTenor_(optionTenor),
      optionConvention_(ModifiedFollowing),
      strike_(strike) {}
Member Function Documentation
QuantLib::MakeSwaption::operator boost::shared_ptr< Swaption > () const
Definition at line 45 of file makeswaption.cpp.
References QuantLib::Calendar::advance(), QuantLib::Settings::evaluationDate(), QuantLib::Singleton< Settings >::instance(), QL_REQUIRE, and QuantLib::MakeVanillaSwap::withFixedLegTerminationDateConvention().
{
        const Date& evaluationDate = Settings::instance().evaluationDate();
        const Calendar& fixingCalendar = swapIndex_->fixingCalendar();
        fixingDate_ = fixingCalendar.advance(evaluationDate, optionTenor_,
                                             optionConvention_);
        if (exerciseDate_ == Null<Date>()) {
            exercise_ = boost::shared_ptr<Exercise>(new
                EuropeanExercise(fixingDate_));
        } else {
            QL_REQUIRE(exerciseDate_ <= fixingDate_,
                       "exercise date (" << exerciseDate_ << ") must be less "
                       "than or equal to fixing date (" << fixingDate_ << ")");
            exercise_ = boost::shared_ptr<Exercise>(new
                EuropeanExercise(exerciseDate_));
        }
        Rate usedStrike = strike_;
        if (strike_ == Null<Rate>()) {
            // ATM on the forecasting curve
            QL_REQUIRE(!swapIndex_->forwardingTermStructure().empty(),
                       "null term structure set to this instance of " <<
                       swapIndex_->name());
            boost::shared_ptr<VanillaSwap> temp =
                swapIndex_->underlyingSwap(fixingDate_);
            temp->setPricingEngine(boost::shared_ptr<PricingEngine>(
                new DiscountingSwapEngine(
                                        swapIndex_->forwardingTermStructure(),
                                        false)));
            usedStrike = temp->fairRate();
        }
        BusinessDayConvention bdc = swapIndex_->fixedLegConvention();
        underlyingSwap_ =
            MakeVanillaSwap(swapIndex_->tenor(),
                            swapIndex_->iborIndex(), usedStrike)
            .withEffectiveDate(swapIndex_->valueDate(fixingDate_))
            .withFixedLegCalendar(swapIndex_->fixingCalendar())
            .withFixedLegDayCount(swapIndex_->dayCounter())
            .withFixedLegConvention(bdc)
            .withFixedLegTerminationDateConvention(bdc);
        boost::shared_ptr<Swaption> swaption(new
            Swaption(underlyingSwap_, exercise_, delivery_));
        swaption->setPricingEngine(engine_);
        return swaption;
    }
QuantLib::MakeSwaption::operator Swaption () const
Definition at line 40 of file makeswaption.cpp.
{
        boost::shared_ptr<Swaption> swaption = *this;
        return *swaption;
    }
MakeSwaption & QuantLib::MakeSwaption::withExerciseDate (const Date & date)
Definition at line 104 of file makeswaption.cpp.
References exerciseDate_.
{
        exerciseDate_ = date;
        return *this;
    }
MakeSwaption & QuantLib::MakeSwaption::withOptionConvention (BusinessDayConvention bdc)
Definition at line 99 of file makeswaption.cpp.
References optionConvention_.
{
        optionConvention_ = bdc;
        return *this;
    }
MakeSwaption & QuantLib::MakeSwaption::withPricingEngine (const boost::shared_ptr< PricingEngine > & engine)
Definition at line 109 of file makeswaption.cpp.
References engine_.
Referenced by anonymous_namespace{swaptionvolatilitymatrix.cpp}::CommonVars::makeCoherenceTest().
{
        engine_ = engine;
        return *this;
    }
MakeSwaption & QuantLib::MakeSwaption::withSettlementType (Settlement::Type delivery)
Definition at line 93 of file makeswaption.cpp.
References delivery_.
{
        delivery_ = delivery;
        return *this;
    }
Member Data Documentation
Settlement::Type QuantLib::MakeSwaption::delivery_ [private]
Definition at line 61 of file makeswaption.hpp.
Referenced by withSettlementType().
boost::shared_ptr<PricingEngine> QuantLib::MakeSwaption::engine_ [private]
Definition at line 72 of file makeswaption.hpp.
Referenced by withPricingEngine().
boost::shared_ptr<Exercise> QuantLib::MakeSwaption::exercise_ [mutable, private]
Definition at line 68 of file makeswaption.hpp.
Date QuantLib::MakeSwaption::exerciseDate_ [private]
Definition at line 67 of file makeswaption.hpp.
Referenced by withExerciseDate().
Date QuantLib::MakeSwaption::fixingDate_ [mutable, private]
Definition at line 66 of file makeswaption.hpp.
BusinessDayConvention QuantLib::MakeSwaption::optionConvention_ [private]
Definition at line 65 of file makeswaption.hpp.
Referenced by withOptionConvention().
Period QuantLib::MakeSwaption::optionTenor_ [private]
Definition at line 64 of file makeswaption.hpp.
Rate QuantLib::MakeSwaption::strike_ [private]
Definition at line 70 of file makeswaption.hpp.
boost::shared_ptr<SwapIndex> QuantLib::MakeSwaption::swapIndex_ [private]
Definition at line 60 of file makeswaption.hpp.
boost::shared_ptr<VanillaSwap> QuantLib::MakeSwaption::underlyingSwap_ [mutable, private]
Definition at line 62 of file makeswaption.hpp.
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/makeswaption.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/makeswaption.cpp