QuantLib: QuantLib::SyntheticCDO Class Reference
QuantLib::SyntheticCDO Class Reference
Synthetic Collateralized Debt Obligation.
#include <syntheticcdo.hpp>
Classes
class arguments
class engine
CDO base engine.
class results
Public Member Functions
SyntheticCDO (const boost::shared_ptr< Basket > basket, Protection::Side side, const Schedule &schedule, Rate upfrontRate, Rate runningRate, const DayCounter &dayCounter, BusinessDayConvention paymentConvention, const Handle< YieldTermStructure > &yieldTS)
boost::shared_ptr< Basket > basket () const
bool isExpired () const
returns whether the instrument might have value greater than zero.
Rate fairPremium () const
Rate fairUpfrontPremium () const
Rate premiumValue () const
Rate protectionValue () const
Real premiumLegNPV () const
Real protectionLegNPV () const
Real remainingNotional () const
std::vector< Real > expectedTrancheLoss () const
Size error () const
void setupArguments (PricingEngine::arguments *) const
void fetchResults (const PricingEngine::results *) const
Private Member Functions
void setupExpired () const
Private Attributes
boost::shared_ptr< Basket > basket_
Protection::Side side_
Schedule schedule_
Rate upfrontRate_
Rate runningRate_
DayCounter dayCounter_
BusinessDayConvention paymentConvention_
Handle< YieldTermStructure > yieldTS_
Rate fairPremium_
Real premiumValue_
Real protectionValue_
Real upfrontPremiumValue_
Real remainingNotional_
Size error_
std::vector< Real > expectedTrancheLoss_
Detailed Description
Synthetic Collateralized Debt Obligation.
The instrument prices a mezzanine CDO tranche with loss given default between attachment point \(D_1\) and detachment point \(D_2 > D_1 \).
For purchased protection, the instrument value is given by the difference of the protection value \(V_1 \) and premium value \(V_2 \),
\[ V = V_1 - V_2. \]
The protection leg is priced as follows:
Build the probability distribution for volume of defaults \(L \) (before recovery) or Loss Given Default \(LGD = (1-r)\,L \) at times/dates \(t_i, i=1, ..., N\) (premium schedule times with intermediate steps)
Determine the expected value \(E_i = E_{t_i}\,\left[Pay(LGD)\right] \) of the protection payoff \(Pay(LGD) \) at each time \(t_i\) where
\[ Pay(L) = min (D_1, LGD) - min (D_2, LGD) = \left\{ \begin{array}{lcl} \displaystyle 0 &;& LGD < D_1 \\ \displaystyle LGD - D_1 &;& D_1 \leq LGD \leq D_2 \\ \displaystyle D_2 - D_1 &;& LGD > D_2 \end{array} \right. \]
The protection value is then calculated as
\[ V_1 \:=\: \sum_{i=1}^N (E_i - E_{i-1}) \cdot d_i \]
where \(d_i\) is the discount factor at time/date \(t_i \)
The premium is paid on the protected notional amount, initially \(D_2 - D_1. \) This notional amount is reduced by the expected protection payments \(E_i \) at times \(t_i, \) so that the premium value is calculated as
\[ V_2 = m \, \cdot \sum_{i=1}^N \,(D_2 - D_1 - E_i) \cdot \Delta_{i-1,i}\,d_i \]
where \(m \) is the premium rate, \(\Delta_{i-1, i}\) is the day count fraction between date/time \(t_{i-1}\) and \(t_i.\)
The construction of the portfolio loss distribution \(E_i \) is based on the probability bucketing algorithm described in
John Hull and Alan White, "Valuation of a CDO and nth to default CDS without Monte Carlo simulation", Journal of Derivatives 12, 2, 2004
The pricing algorithm allows for varying notional amounts and default termstructures of the underlyings.
Todo:
Investigate and fix cases \(E_{i+1} < E_i. \)
Definition at line 100 of file syntheticcdo.hpp.
Constructor & Destructor Documentation
QuantLib::SyntheticCDO::SyntheticCDO (const boost::shared_ptr< Basket > basket, Protection::Side side, const Schedule & schedule, Rate upfrontRate, Rate runningRate, const DayCounter & dayCounter, BusinessDayConvention paymentConvention, const Handle< YieldTermStructure > & yieldTS)
Definition at line 27 of file syntheticcdo.cpp.
References basket_, QuantLib::Schedule::dates(), QuantLib::Settings::evaluationDate(), QuantLib::Singleton< Settings >::instance(), QL_REQUIRE, QuantLib::Observer::registerWith(), and yieldTS_.
        : basket_(basket),
          side_(side),
          schedule_(schedule),
          upfrontRate_(upfrontRate),
          runningRate_(runningRate),
          dayCounter_(dayCounter),
          paymentConvention_(paymentConvention),
          yieldTS_(yieldTS) {
        QL_REQUIRE (basket->names().size() > 0, "basket is empty");
        registerWith (yieldTS_);
        const boost::shared_ptr<Pool> pool = basket->pool();
        Date today = Settings::instance().evaluationDate();
        // register with probabilities if the corresponding issuer is
        // alive under this name contractual conditions
        for (Size i = 0; i < basket->names().size(); i++) {
            if(!pool->get(basket->names()[i]).
                defaultedBetween(schedule.dates()[0],
                                 today,
                                 basket->defaultKeys()[i]))
            registerWith(pool->get(basket->names()[i]).
                defaultProbability(basket->defaultKeys()[i]));
            // To do: the basket could do this last line on its own without so much
            //    travelling, update its interface? some RR models depend on the
            //    probabilities and they will be registered with them. Strictly
            //    speaking the basket does not need directly to be registered
            //    with the probs.
            /*
                we used to be registering with Issuers which are not observables. However
                this might be what we want: Issuer registration might give us registration
                with probabilities and with creditEvents at the same time.
            */
        }
        // register with recoveries:
        registerWith(basket_);
    }
Member Function Documentation
boost::shared_ptr<Basket> QuantLib::SyntheticCDO::basket () const [inline]
Definition at line 115 of file syntheticcdo.hpp.
References basket_.
Referenced by QuantLib::SyntheticCDO::engine::initialize().
{ return basket_; }
Size QuantLib::SyntheticCDO::error () const
Definition at line 111 of file syntheticcdo.cpp.
References QuantLib::Instrument::calculate(), and error_.
Referenced by QuantLib::SyntheticCDO::results::reset().
{
        calculate();
        return error_;
    }
vector< Real > QuantLib::SyntheticCDO::expectedTrancheLoss () const
Expected tranche loss for all payment dates
Definition at line 106 of file syntheticcdo.cpp.
References QuantLib::Instrument::calculate(), and expectedTrancheLoss_.
Referenced by QuantLib::SyntheticCDO::results::reset().
{
        calculate();
        return expectedTrancheLoss_;
    }
Rate QuantLib::SyntheticCDO::fairPremium () const
Definition at line 95 of file syntheticcdo.cpp.
References QuantLib::Instrument::calculate(), premiumValue_, protectionValue_, runningRate_, and upfrontPremiumValue_.
Referenced by CdoTest::testHW().
{
        calculate();
        return runningRate_
            * (protectionValue_ - upfrontPremiumValue_) / premiumValue_;
    }
Rate QuantLib::SyntheticCDO::fairUpfrontPremium () const
Definition at line 101 of file syntheticcdo.cpp.
References QuantLib::Instrument::calculate(), premiumValue_, protectionValue_, and remainingNotional_.
{
        calculate();
        return (protectionValue_ - premiumValue_) / remainingNotional_;
    }
void QuantLib::SyntheticCDO::fetchResults (const PricingEngine::results * r) const [virtual]
When a derived result structure is defined for an instrument, this method should be overridden to read from it. This is mandatory in case a pricing engine is used.
Reimplemented from QuantLib::Instrument.
Definition at line 140 of file syntheticcdo.cpp.
References QuantLib::SyntheticCDO::results::error, error_, QuantLib::SyntheticCDO::results::expectedTrancheLoss, expectedTrancheLoss_, QuantLib::SyntheticCDO::results::premiumValue, premiumValue_, QuantLib::SyntheticCDO::results::protectionValue, protectionValue_, QL_REQUIRE, QuantLib::SyntheticCDO::results::remainingNotional, remainingNotional_, QuantLib::SyntheticCDO::results::upfrontPremiumValue, and upfrontPremiumValue_.
{
        Instrument::fetchResults(r);
        const SyntheticCDO::results* results
            = dynamic_cast<const SyntheticCDO::results*>(r);
        QL_REQUIRE(results != 0, "wrong result type");
        premiumValue_ = results->premiumValue;
        protectionValue_ = results->protectionValue;
        upfrontPremiumValue_ = results->upfrontPremiumValue;
        remainingNotional_ = results->remainingNotional;
        error_ = results->error;
        expectedTrancheLoss_ = results->expectedTrancheLoss;
    }
bool QuantLib::SyntheticCDO::isExpired () const [virtual]
returns whether the instrument might have value greater than zero.
Implements QuantLib::Instrument.
Definition at line 116 of file syntheticcdo.cpp.
References QuantLib::Schedule::dates(), schedule_, and yieldTS_.
{
        return detail::simple_event(schedule_.dates().back())
               .hasOccurred(yieldTS_->referenceDate());
    }
Real QuantLib::SyntheticCDO::premiumLegNPV () const
Definition at line 83 of file syntheticcdo.cpp.
References QuantLib::Protection::Buyer, QuantLib::Instrument::calculate(), premiumValue_, and side_.
{
        calculate();
        if(side_ == Protection::Buyer) return premiumValue_;
        return -premiumValue_;
    }
Rate QuantLib::SyntheticCDO::premiumValue () const
Definition at line 73 of file syntheticcdo.cpp.
References QuantLib::Instrument::calculate(), and premiumValue_.
Referenced by QuantLib::SyntheticCDO::results::reset().
{
        calculate();
        return premiumValue_;
    }
Real QuantLib::SyntheticCDO::protectionLegNPV () const
Definition at line 89 of file syntheticcdo.cpp.
References QuantLib::Protection::Buyer, QuantLib::Instrument::calculate(), premiumValue_, protectionValue_, and side_.
{
        calculate();
        if(side_ == Protection::Buyer) return -protectionValue_;
        return premiumValue_;
    }
Rate QuantLib::SyntheticCDO::protectionValue () const
Definition at line 78 of file syntheticcdo.cpp.
References QuantLib::Instrument::calculate(), and protectionValue_.
Referenced by QuantLib::SyntheticCDO::results::reset().
{
        calculate();
        return protectionValue_;
    }
Real QuantLib::SyntheticCDO::remainingNotional () const
Total outstanding tranche notional, not wiped out
Definition at line 121 of file syntheticcdo.cpp.
References QuantLib::Instrument::calculate(), and remainingNotional_.
Referenced by QuantLib::SyntheticCDO::results::reset().
{
        calculate();
        return remainingNotional_;
    }
void QuantLib::SyntheticCDO::setupArguments (PricingEngine::arguments *) const [virtual]
When a derived argument structure is defined for an instrument, this method should be overridden to fill it. This is mandatory in case a pricing engine is used.
Reimplemented from QuantLib::Instrument.
Definition at line 126 of file syntheticcdo.cpp.
References QuantLib::SyntheticCDO::arguments::basket, basket_, QuantLib::SyntheticCDO::arguments::dayCounter, dayCounter_, QuantLib::SyntheticCDO::arguments::paymentConvention, paymentConvention_, QL_REQUIRE, QuantLib::SyntheticCDO::arguments::runningRate, runningRate_, QuantLib::SyntheticCDO::arguments::schedule, schedule_, QuantLib::SyntheticCDO::arguments::side, side_, QuantLib::SyntheticCDO::arguments::upfrontRate, upfrontRate_, QuantLib::SyntheticCDO::arguments::yieldTS, and yieldTS_.
{
        SyntheticCDO::arguments* arguments
            = dynamic_cast<SyntheticCDO::arguments*>(args);
        QL_REQUIRE(arguments != 0, "wrong argument type");
        arguments->basket = basket_;
        arguments->side = side_;
        arguments->schedule = schedule_;
        arguments->upfrontRate = upfrontRate_;
        arguments->runningRate = runningRate_;
        arguments->dayCounter = dayCounter_;
        arguments->paymentConvention = paymentConvention_;
        arguments->yieldTS = yieldTS_;
    }
void QuantLib::SyntheticCDO::setupExpired () const [private, virtual]
This method must leave the instrument in a consistent state when the expiration condition is met.
Reimplemented from QuantLib::Instrument.
Definition at line 155 of file syntheticcdo.cpp.
References expectedTrancheLoss_, premiumValue_, protectionValue_, remainingNotional_, and upfrontPremiumValue_.
{
        Instrument::setupExpired();
        premiumValue_ = 0.0;
        protectionValue_ = 0.0;
        upfrontPremiumValue_ = 0.0;
        remainingNotional_ = 1.0;
        expectedTrancheLoss_.clear();
    }
Member Data Documentation
boost::shared_ptr<Basket> QuantLib::SyntheticCDO::basket_ [private]
Definition at line 140 of file syntheticcdo.hpp.
Referenced by basket(), setupArguments(), and SyntheticCDO().
DayCounter QuantLib::SyntheticCDO::dayCounter_ [private]
Definition at line 145 of file syntheticcdo.hpp.
Referenced by setupArguments().
Size QuantLib::SyntheticCDO::error_ [mutable, private]
Definition at line 154 of file syntheticcdo.hpp.
Referenced by error(), and fetchResults().
std::vector<Real> QuantLib::SyntheticCDO::expectedTrancheLoss_ [mutable, private]
Definition at line 155 of file syntheticcdo.hpp.
Referenced by expectedTrancheLoss(), fetchResults(), and setupExpired().
Rate QuantLib::SyntheticCDO::fairPremium_ [mutable, private]
Definition at line 149 of file syntheticcdo.hpp.
BusinessDayConvention QuantLib::SyntheticCDO::paymentConvention_ [private]
Definition at line 146 of file syntheticcdo.hpp.
Referenced by setupArguments().
Real QuantLib::SyntheticCDO::premiumValue_ [mutable, private]
Definition at line 150 of file syntheticcdo.hpp.
Referenced by fairPremium(), fairUpfrontPremium(), fetchResults(), premiumLegNPV(), premiumValue(), protectionLegNPV(), and setupExpired().
Real QuantLib::SyntheticCDO::protectionValue_ [mutable, private]
Definition at line 151 of file syntheticcdo.hpp.
Referenced by fairPremium(), fairUpfrontPremium(), fetchResults(), protectionLegNPV(), protectionValue(), and setupExpired().
Real QuantLib::SyntheticCDO::remainingNotional_ [mutable, private]
Definition at line 153 of file syntheticcdo.hpp.
Referenced by fairUpfrontPremium(), fetchResults(), remainingNotional(), and setupExpired().
Rate QuantLib::SyntheticCDO::runningRate_ [private]
Definition at line 144 of file syntheticcdo.hpp.
Referenced by fairPremium(), and setupArguments().
Schedule QuantLib::SyntheticCDO::schedule_ [private]
Definition at line 142 of file syntheticcdo.hpp.
Referenced by isExpired(), and setupArguments().
Protection::Side QuantLib::SyntheticCDO::side_ [private]
Definition at line 141 of file syntheticcdo.hpp.
Referenced by premiumLegNPV(), protectionLegNPV(), and setupArguments().
Real QuantLib::SyntheticCDO::upfrontPremiumValue_ [mutable, private]
Definition at line 152 of file syntheticcdo.hpp.
Referenced by fairPremium(), fetchResults(), and setupExpired().
Rate QuantLib::SyntheticCDO::upfrontRate_ [private]
Definition at line 143 of file syntheticcdo.hpp.
Referenced by setupArguments().
Handle<YieldTermStructure> QuantLib::SyntheticCDO::yieldTS_ [private]
Definition at line 147 of file syntheticcdo.hpp.
Referenced by isExpired(), setupArguments(), and SyntheticCDO().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/syntheticcdo.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/syntheticcdo.cpp