QuantLib: QuantLib::LogNormalFwdRateEuler Class Reference
QuantLib::LogNormalFwdRateEuler Class Reference
Euler.
#include <lognormalfwdrateeuler.hpp>
Public Member Functions
LogNormalFwdRateEuler (const boost::shared_ptr< MarketModel > &, const BrownianGeneratorFactory &, const std::vector< Size > &numeraires, Size initialStep=0)
const std::vector< Real > & browniansThisStep () const
accessor methods useful for doing pathwise vegas
MarketModel interface
const std::vector< Size > & numeraires () const
Real startNewPath ()
Real advanceStep ()
Size currentStep () const
const CurveState & currentState () const
void setInitialState (const CurveState &)
Private Member Functions
void setForwards (const std::vector< Real > &forwards)
Private Attributes
boost::shared_ptr< MarketModel > marketModel_
std::vector< Size > numeraires_
Size initialStep_
boost::shared_ptr
< BrownianGenerator > generator_
std::vector< std::vector< Real > > fixedDrifts_
Size numberOfRates_
Size numberOfFactors_
LMMCurveState curveState_
Size currentStep_
std::vector< Rate > forwards_
std::vector< Rate > displacements_
std::vector< Rate > logForwards_
std::vector< Rate > initialLogForwards_
std::vector< Real > drifts1_
std::vector< Real > initialDrifts_
std::vector< Real > brownians_
std::vector< Real > correlatedBrownians_
std::vector< Size > alive_
std::vector< LMMDriftCalculator > calculators_
Detailed Description
Euler.
Definition at line 35 of file lognormalfwdrateeuler.hpp.
Constructor & Destructor Documentation
QuantLib::LogNormalFwdRateEuler::LogNormalFwdRateEuler (const boost::shared_ptr< MarketModel > & marketModel, const BrownianGeneratorFactory & factory, const std::vector< Size > & numeraires, Size initialStep = 0)
Definition at line 29 of file lognormalfwdrateeuler.cpp.
References alive_, calculators_, QuantLib::checkCompatibility(), QuantLib::BrownianGeneratorFactory::create(), currentStep_, displacements_, fixedDrifts_, generator_, initialStep_, QuantLib::dsd::inner_product(), marketModel_, numberOfFactors_, numberOfRates_, numeraires(), QuantLib::Matrix::row_begin(), QuantLib::Matrix::row_end(), and setForwards().
    : marketModel_(marketModel),
      numeraires_(numeraires),
      initialStep_(initialStep),
      numberOfRates_(marketModel->numberOfRates()),
      numberOfFactors_(marketModel_->numberOfFactors()),
      curveState_(marketModel->evolution().rateTimes()),
      forwards_(marketModel->initialRates()),
      displacements_(marketModel->displacements()),
      logForwards_(numberOfRates_), initialLogForwards_(numberOfRates_),
      drifts1_(numberOfRates_), initialDrifts_(numberOfRates_),
      brownians_(numberOfFactors_), correlatedBrownians_(numberOfRates_),
      alive_(marketModel->evolution().firstAliveRate())
    {
        checkCompatibility(marketModel->evolution(), numeraires);
        Size steps = marketModel->evolution().numberOfSteps();
        generator_ = factory.create(numberOfFactors_, steps-initialStep_);
        currentStep_ = initialStep_;
        calculators_.reserve(steps);
        fixedDrifts_.reserve(steps);
        for (Size j=0; j<steps; ++j) {
            const Matrix& A = marketModel_->pseudoRoot(j);
            calculators_.push_back(LMMDriftCalculator(A,
                                                   displacements_,
                                                   marketModel->evolution().rateTaus(),
                                                   numeraires[j],
                                                   alive_[j]));
            std::vector<Real> fixed(numberOfRates_);
            for (Size k=0; k<numberOfRates_; ++k) {
                Real variance =
                    std::inner_product(A.row_begin(k), A.row_end(k),
                                       A.row_begin(k), 0.0);
                fixed[k] = -0.5*variance;
            }
            fixedDrifts_.push_back(fixed);
        }
        setForwards(marketModel_->initialRates());
    }
Member Function Documentation
Real QuantLib::LogNormalFwdRateEuler::advanceStep () [virtual]
Implements QuantLib::MarketModelEvolver.
Definition at line 102 of file lognormalfwdrateeuler.cpp.
References alive_, brownians_, calculators_, currentStep_, curveState_, displacements_, drifts1_, fixedDrifts_, forwards_, generator_, initialDrifts_, initialStep_, QuantLib::dsd::inner_product(), logForwards_, marketModel_, numberOfRates_, QuantLib::Matrix::row_begin(), QuantLib::Matrix::row_end(), and QuantLib::LMMCurveState::setOnForwardRates().
    {
        // we're going from T1 to T2
        // a) compute drifts D1 at T1;
        if (currentStep_ > initialStep_) {
            calculators_[currentStep_].compute(forwards_, drifts1_);
        } else {
            std::copy(initialDrifts_.begin(), initialDrifts_.end(),
                      drifts1_.begin());
        }
        // b) evolve forwards up to T2 using D1;
        Real weight = generator_->nextStep(brownians_);
        const Matrix& A = marketModel_->pseudoRoot(currentStep_);
        const std::vector<Real>& fixedDrift = fixedDrifts_[currentStep_];
        Size alive = alive_[currentStep_];
        for (Size i=alive; i<numberOfRates_; i++) {
            logForwards_[i] += drifts1_[i] + fixedDrift[i];
            logForwards_[i] +=
                std::inner_product(A.row_begin(i), A.row_end(i),
                                   brownians_.begin(), 0.0);
            forwards_[i] = std::exp(logForwards_[i]) - displacements_[i];
        }
        // same as PC evolver with two steps dropped
        // c) update curve state
        curveState_.setOnForwardRates(forwards_);
        ++currentStep_;
        return weight;
    }
const std::vector<Real>& QuantLib::LogNormalFwdRateEuler::browniansThisStep () const [inline]
accessor methods useful for doing pathwise vegas
Definition at line 52 of file lognormalfwdrateeuler.hpp.
References brownians_.
        {
            return brownians_;
        }
const CurveState & QuantLib::LogNormalFwdRateEuler::currentState () const [virtual]
Implements QuantLib::MarketModelEvolver.
Definition at line 142 of file lognormalfwdrateeuler.cpp.
References curveState_.
{
        return curveState_;
    }
Size QuantLib::LogNormalFwdRateEuler::currentStep () const [virtual]
Implements QuantLib::MarketModelEvolver.
Definition at line 138 of file lognormalfwdrateeuler.cpp.
References currentStep_.
{
        return currentStep_;
    }
const std::vector< Size > & QuantLib::LogNormalFwdRateEuler::numeraires () const [virtual]
Implements QuantLib::MarketModelEvolver.
Definition at line 77 of file lognormalfwdrateeuler.cpp.
References numeraires_.
Referenced by LogNormalFwdRateEuler(), MarketModelTest::testPathwiseGreeks(), MarketModelTest::testPathwiseMarketVegas(), and MarketModelTest::testPathwiseVegas().
{
        return numeraires_;
    }
void QuantLib::LogNormalFwdRateEuler::setForwards (const std::vector< Real > & forwards) [private]
Definition at line 81 of file lognormalfwdrateeuler.cpp.
References calculators_, displacements_, initialDrifts_, initialLogForwards_, initialStep_, numberOfRates_, and QL_REQUIRE.
Referenced by LogNormalFwdRateEuler(), and setInitialState().
    {
        QL_REQUIRE(forwards.size()==numberOfRates_,
                   "mismatch between forwards and rateTimes");
        for (Size i=0; i<numberOfRates_; ++i)
            initialLogForwards_[i] = std::log(forwards[i] +
                                              displacements_[i]);
        calculators_[initialStep_].compute(forwards, initialDrifts_);
    }
void QuantLib::LogNormalFwdRateEuler::setInitialState (const CurveState & cs) [virtual]
Implements QuantLib::MarketModelEvolver.
Definition at line 91 of file lognormalfwdrateeuler.cpp.
References QuantLib::CurveState::forwardRates(), and setForwards().
{
        setForwards(cs.forwardRates());
    }
Real QuantLib::LogNormalFwdRateEuler::startNewPath () [virtual]
Implements QuantLib::MarketModelEvolver.
Definition at line 95 of file lognormalfwdrateeuler.cpp.
References currentStep_, generator_, initialLogForwards_, initialStep_, and logForwards_.
Referenced by MarketModelTest::testPathwiseMarketVegas().
{
        currentStep_ = initialStep_;
        std::copy(initialLogForwards_.begin(), initialLogForwards_.end(),
                  logForwards_.begin());
        return generator_->nextPath();
    }
Member Data Documentation
std::vector<Size> QuantLib::LogNormalFwdRateEuler::alive_ [private]
Definition at line 75 of file lognormalfwdrateeuler.hpp.
Referenced by advanceStep(), and LogNormalFwdRateEuler().
std::vector<Real> QuantLib::LogNormalFwdRateEuler::brownians_ [private]
Definition at line 74 of file lognormalfwdrateeuler.hpp.
Referenced by advanceStep(), and browniansThisStep().
std::vector<LMMDriftCalculator> QuantLib::LogNormalFwdRateEuler::calculators_ [private]
Definition at line 77 of file lognormalfwdrateeuler.hpp.
Referenced by advanceStep(), LogNormalFwdRateEuler(), and setForwards().
std::vector<Real> QuantLib::LogNormalFwdRateEuler::correlatedBrownians_ [private]
Definition at line 74 of file lognormalfwdrateeuler.hpp.
Size QuantLib::LogNormalFwdRateEuler::currentStep_ [private]
Definition at line 71 of file lognormalfwdrateeuler.hpp.
Referenced by advanceStep(), currentStep(), LogNormalFwdRateEuler(), and startNewPath().
LMMCurveState QuantLib::LogNormalFwdRateEuler::curveState_ [private]
Definition at line 70 of file lognormalfwdrateeuler.hpp.
Referenced by advanceStep(), and currentState().
std::vector<Rate> QuantLib::LogNormalFwdRateEuler::displacements_ [private]
Definition at line 72 of file lognormalfwdrateeuler.hpp.
Referenced by advanceStep(), LogNormalFwdRateEuler(), and setForwards().
std::vector<Real> QuantLib::LogNormalFwdRateEuler::drifts1_ [private]
Definition at line 73 of file lognormalfwdrateeuler.hpp.
Referenced by advanceStep().
std::vector<std::vector<Real> > QuantLib::LogNormalFwdRateEuler::fixedDrifts_ [private]
Definition at line 67 of file lognormalfwdrateeuler.hpp.
Referenced by advanceStep(), and LogNormalFwdRateEuler().
std::vector<Rate> QuantLib::LogNormalFwdRateEuler::forwards_ [private]
Definition at line 72 of file lognormalfwdrateeuler.hpp.
Referenced by advanceStep().
boost::shared_ptr<BrownianGenerator> QuantLib::LogNormalFwdRateEuler::generator_ [private]
Definition at line 65 of file lognormalfwdrateeuler.hpp.
Referenced by advanceStep(), LogNormalFwdRateEuler(), and startNewPath().
std::vector<Real> QuantLib::LogNormalFwdRateEuler::initialDrifts_ [private]
Definition at line 73 of file lognormalfwdrateeuler.hpp.
Referenced by advanceStep(), and setForwards().
std::vector<Rate> QuantLib::LogNormalFwdRateEuler::initialLogForwards_ [private]
Definition at line 72 of file lognormalfwdrateeuler.hpp.
Referenced by setForwards(), and startNewPath().
Size QuantLib::LogNormalFwdRateEuler::initialStep_ [private]
Definition at line 64 of file lognormalfwdrateeuler.hpp.
Referenced by advanceStep(), LogNormalFwdRateEuler(), setForwards(), and startNewPath().
std::vector<Rate> QuantLib::LogNormalFwdRateEuler::logForwards_ [private]
Definition at line 72 of file lognormalfwdrateeuler.hpp.
Referenced by advanceStep(), and startNewPath().
boost::shared_ptr<MarketModel> QuantLib::LogNormalFwdRateEuler::marketModel_ [private]
Definition at line 62 of file lognormalfwdrateeuler.hpp.
Referenced by advanceStep(), and LogNormalFwdRateEuler().
Size QuantLib::LogNormalFwdRateEuler::numberOfFactors_ [private]
Definition at line 69 of file lognormalfwdrateeuler.hpp.
Referenced by LogNormalFwdRateEuler().
Size QuantLib::LogNormalFwdRateEuler::numberOfRates_ [private]
Definition at line 69 of file lognormalfwdrateeuler.hpp.
Referenced by advanceStep(), LogNormalFwdRateEuler(), and setForwards().
std::vector<Size> QuantLib::LogNormalFwdRateEuler::numeraires_ [private]
Definition at line 63 of file lognormalfwdrateeuler.hpp.
Referenced by numeraires().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/evolvers/lognormalfwdrateeuler.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/evolvers/lognormalfwdrateeuler.cpp