QuantLib: QuantLib::FloatingRateCouponPricer Class Reference
QuantLib::FloatingRateCouponPricer Class Reference
generic pricer for floating-rate coupons
#include <couponpricer.hpp>
Public Member Functions
virtual ~FloatingRateCouponPricer ()
required interface
virtual Real swapletPrice () const =0
virtual Rate swapletRate () const =0
virtual Real capletPrice (Rate effectiveCap) const =0
virtual Rate capletRate (Rate effectiveCap) const =0
virtual Real floorletPrice (Rate effectiveFloor) const =0
virtual Rate floorletRate (Rate effectiveFloor) const =0
virtual void initialize (const FloatingRateCoupon &coupon)=0
Observer interface
void update ()
Detailed Description
generic pricer for floating-rate coupons
Definition at line 41 of file couponpricer.hpp.
Constructor & Destructor Documentation
virtual QuantLib::FloatingRateCouponPricer::~FloatingRateCouponPricer () [inline, virtual]
Definition at line 44 of file couponpricer.hpp.
{}
Member Function Documentation
virtual Real QuantLib::FloatingRateCouponPricer::capletPrice (Rate effectiveCap) const [pure virtual]
Implemented in QuantLib::HaganPricer, QuantLib::anonymous_namespace{overnightindexedcoupon.cpp}::OvernightIndexedCouponPricer, QuantLib::SubPeriodsPricer, QuantLib::RangeAccrualPricer, QuantLib::BlackIborCouponPricer, and QuantLib::anonymous_namespace{averagebmacoupon.cpp}::AverageBMACouponPricer.
virtual Rate QuantLib::FloatingRateCouponPricer::capletRate (Rate effectiveCap) const [pure virtual]
Implemented in QuantLib::HaganPricer, QuantLib::anonymous_namespace{overnightindexedcoupon.cpp}::OvernightIndexedCouponPricer, QuantLib::SubPeriodsPricer, QuantLib::RangeAccrualPricer, QuantLib::BlackIborCouponPricer, and QuantLib::anonymous_namespace{averagebmacoupon.cpp}::AverageBMACouponPricer.
virtual Real QuantLib::FloatingRateCouponPricer::floorletPrice (Rate effectiveFloor) const [pure virtual]
Implemented in QuantLib::HaganPricer, QuantLib::anonymous_namespace{overnightindexedcoupon.cpp}::OvernightIndexedCouponPricer, QuantLib::SubPeriodsPricer, QuantLib::RangeAccrualPricer, QuantLib::BlackIborCouponPricer, and QuantLib::anonymous_namespace{averagebmacoupon.cpp}::AverageBMACouponPricer.
virtual Rate QuantLib::FloatingRateCouponPricer::floorletRate (Rate effectiveFloor) const [pure virtual]
Implemented in QuantLib::HaganPricer, QuantLib::anonymous_namespace{overnightindexedcoupon.cpp}::OvernightIndexedCouponPricer, QuantLib::SubPeriodsPricer, QuantLib::RangeAccrualPricer, QuantLib::BlackIborCouponPricer, and QuantLib::anonymous_namespace{averagebmacoupon.cpp}::AverageBMACouponPricer.
virtual void QuantLib::FloatingRateCouponPricer::initialize (const FloatingRateCoupon & coupon) [pure virtual]
Implemented in QuantLib::HaganPricer, QuantLib::SubPeriodsPricer, QuantLib::RangeAccrualPricer, QuantLib::BlackIborCouponPricer, QuantLib::anonymous_namespace{overnightindexedcoupon.cpp}::OvernightIndexedCouponPricer, and QuantLib::anonymous_namespace{averagebmacoupon.cpp}::AverageBMACouponPricer.
virtual Real QuantLib::FloatingRateCouponPricer::swapletPrice () const [pure virtual]
Implemented in QuantLib::AnalyticHaganPricer, QuantLib::NumericHaganPricer, QuantLib::HaganPricer, QuantLib::RangeAccrualPricerByBgm, QuantLib::CompoundingRatePricer, QuantLib::AveragingRatePricer, QuantLib::anonymous_namespace{overnightindexedcoupon.cpp}::OvernightIndexedCouponPricer, QuantLib::BlackIborCouponPricer, and QuantLib::anonymous_namespace{averagebmacoupon.cpp}::AverageBMACouponPricer.
Referenced by QuantLib::RangeAccrualPricer::swapletRate(), and QuantLib::SubPeriodsPricer::swapletRate().
virtual Rate QuantLib::FloatingRateCouponPricer::swapletRate () const [pure virtual]
Implemented in QuantLib::HaganPricer, QuantLib::SubPeriodsPricer, QuantLib::RangeAccrualPricer, QuantLib::BlackIborCouponPricer, QuantLib::anonymous_namespace{overnightindexedcoupon.cpp}::OvernightIndexedCouponPricer, and QuantLib::anonymous_namespace{averagebmacoupon.cpp}::AverageBMACouponPricer.
void QuantLib::FloatingRateCouponPricer::update () [inline, virtual]
This method must be implemented in derived classes. An instance of Observer does not call this method directly: instead, it will be called by the observables the instance registered with when they need to notify any changes.
Implements QuantLib::Observer.
Definition at line 57 of file couponpricer.hpp.
References QuantLib::Observable::notifyObservers().
Referenced by QuantLib::IborCouponPricer::setCapletVolatility(), QuantLib::HaganPricer::setMeanReversion(), and QuantLib::CmsCouponPricer::setSwaptionVolatility().
{notifyObservers();}
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/couponpricer.hpp