QuantLib: QuantLib::OptionletVolatilityStructure Class Reference
QuantLib::OptionletVolatilityStructure Class Reference
Optionlet (caplet/floorlet) volatility structure.
#include <optionletvolatilitystructure.hpp>
Public Member Functions
virtual ~OptionletVolatilityStructure ()
Constructors
See the TermStructure documentation for issues regarding constructors.
OptionletVolatilityStructure (const Calendar &cal, BusinessDayConvention bdc=Following, const DayCounter &dc=DayCounter())
OptionletVolatilityStructure (BusinessDayConvention bdc=Following, const DayCounter &dc=DayCounter())
default constructor
OptionletVolatilityStructure (const Date &referenceDate, const Calendar &cal, BusinessDayConvention bdc, const DayCounter &dc=DayCounter())
initialize with a fixed reference date
OptionletVolatilityStructure (Natural settlementDays, const Calendar &, BusinessDayConvention bdc, const DayCounter &dc=DayCounter())
calculate the reference date based on the global evaluation date
Volatility and Variance
Volatility volatility (const Period &optionTenor, Rate strike, bool extrapolate=false) const
returns the volatility for a given option tenor and strike rate
Volatility volatility (const Date &optionDate, Rate strike, bool extrapolate=false) const
returns the volatility for a given option date and strike rate
Volatility volatility (Time optionTime, Rate strike, bool extrapolate=false) const
returns the volatility for a given option time and strike rate
Real blackVariance (const Period &optionTenor, Rate strike, bool extrapolate=false) const
returns the Black variance for a given option tenor and strike rate
Real blackVariance (const Date &optionDate, Rate strike, bool extrapolate=false) const
returns the Black variance for a given option date and strike rate
Real blackVariance (Time optionTime, Rate strike, bool extrapolate=false) const
returns the Black variance for a given option time and strike rate
boost::shared_ptr< SmileSection > smileSection (const Period &optionTenor, bool extr=false) const
returns the smile for a given option tenor
boost::shared_ptr< SmileSection > smileSection (const Date &optionDate, bool extr=false) const
returns the smile for a given option date
boost::shared_ptr< SmileSection > smileSection (Time optionTime, bool extr=false) const
returns the smile for a given option time
Protected Member Functions
virtual boost::shared_ptr
< SmileSection > smileSectionImpl (const Date &optionDate) const
virtual boost::shared_ptr
< SmileSection > smileSectionImpl (Time optionTime) const =0
implements the actual smile calculation in derived classes
Volatility volatilityImpl (const Date &optionDate, Rate strike) const
virtual Volatility volatilityImpl (Time optionTime, Rate strike) const =0
implements the actual volatility calculation in derived classes
Detailed Description
Optionlet (caplet/floorlet) volatility structure.
This class is purely abstract and defines the interface of concrete structures which will be derived from this one.
Definition at line 38 of file optionletvolatilitystructure.hpp.
Constructor & Destructor Documentation
QuantLib::OptionletVolatilityStructure::OptionletVolatilityStructure (const Calendar & cal, BusinessDayConvention bdc = Following, const DayCounter & dc = DayCounter())
Warning:
term structures initialized by means of this constructor must manage their own reference date by overriding the referenceDate() method.
Definition at line 26 of file optionletvolatilitystructure.cpp.
    : VolatilityTermStructure(cal, bdc, dc) {}
QuantLib::OptionletVolatilityStructure::OptionletVolatilityStructure (BusinessDayConvention bdc = Following, const DayCounter & dc = DayCounter())
default constructor
Warning:
term structures initialized by means of this constructor must manage their own reference date by overriding the referenceDate() method.
Definition at line 33 of file optionletvolatilitystructure.cpp.
    : VolatilityTermStructure(bdc, dc) {}
QuantLib::OptionletVolatilityStructure::OptionletVolatilityStructure (const Date & referenceDate, const Calendar & cal, BusinessDayConvention bdc, const DayCounter & dc = DayCounter())
initialize with a fixed reference date
Definition at line 38 of file optionletvolatilitystructure.cpp.
    : VolatilityTermStructure(referenceDate, cal, bdc, dc) {}
QuantLib::OptionletVolatilityStructure::OptionletVolatilityStructure (Natural settlementDays, const Calendar & cal, BusinessDayConvention bdc, const DayCounter & dc = DayCounter())
calculate the reference date based on the global evaluation date
Definition at line 45 of file optionletvolatilitystructure.cpp.
    : VolatilityTermStructure(settlementDays, cal, bdc, dc) {}
virtual QuantLib::OptionletVolatilityStructure::~OptionletVolatilityStructure () [inline, virtual]
Definition at line 72 of file optionletvolatilitystructure.hpp.
{}
Member Function Documentation
Real QuantLib::OptionletVolatilityStructure::blackVariance (const Period & optionTenor, Rate strike, bool extrapolate = false) const [inline]
returns the Black variance for a given option tenor and strike rate
Definition at line 137 of file optionletvolatilitystructure.hpp.
References QuantLib::VolatilityTermStructure::optionDateFromTenor().
{
        Date optionDate = optionDateFromTenor(optionTenor);
        return blackVariance(optionDate, strike, extrapolate);
    }
Real QuantLib::OptionletVolatilityStructure::blackVariance (const Date & optionDate, Rate strike, bool extrapolate = false) const [inline]
returns the Black variance for a given option date and strike rate
Definition at line 153 of file optionletvolatilitystructure.hpp.
References anonymous_namespace{quantlibbenchmark.cpp}::t, QuantLib::TermStructure::timeFromReference(), anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and volatility().
{
        Volatility v = volatility(optionDate, strike, extrapolate);
        Time t = timeFromReference(optionDate);
        return v*v*t;
    }
Real QuantLib::OptionletVolatilityStructure::blackVariance (Time optionTime, Rate strike, bool extrapolate = false) const [inline]
returns the Black variance for a given option time and strike rate
Definition at line 162 of file optionletvolatilitystructure.hpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and volatility().
{
        Volatility v = volatility(optionTime, strike, extrapolate);
        return v*v*optionTime;
    }
boost::shared_ptr< SmileSection > QuantLib::OptionletVolatilityStructure::smileSection (const Period & optionTenor, bool extr = false) const [inline]
returns the smile for a given option tenor
Definition at line 145 of file optionletvolatilitystructure.hpp.
References QuantLib::VolatilityTermStructure::optionDateFromTenor().
{
        Date optionDate = optionDateFromTenor(optionTenor);
        return smileSection(optionDate, extrapolate);
    }
boost::shared_ptr< SmileSection > QuantLib::OptionletVolatilityStructure::smileSection (const Date & optionDate, bool extr = false) const [inline]
returns the smile for a given option date
Definition at line 189 of file optionletvolatilitystructure.hpp.
References QuantLib::TermStructure::checkRange(), and smileSectionImpl().
{
        checkRange(optionDate, extrapolate);
        return smileSectionImpl(optionDate);
    }
boost::shared_ptr< SmileSection > QuantLib::OptionletVolatilityStructure::smileSection (Time optionTime, bool extr = false) const [inline]
returns the smile for a given option time
Definition at line 196 of file optionletvolatilitystructure.hpp.
References QuantLib::TermStructure::checkRange(), and smileSectionImpl().
{
        checkRange(optionTime, extrapolate);
        return smileSectionImpl(optionTime);
    }
boost::shared_ptr< SmileSection > QuantLib::OptionletVolatilityStructure::smileSectionImpl (const Date & optionDate) const [inline, protected, virtual]
Reimplemented in QuantLib::ConstantOptionletVolatility, and QuantLib::SpreadedOptionletVolatility.
Definition at line 205 of file optionletvolatilitystructure.hpp.
References QuantLib::TermStructure::timeFromReference().
Referenced by smileSection().
{
        return smileSectionImpl(timeFromReference(optionDate));
    }
virtual boost::shared_ptr<SmileSection> QuantLib::OptionletVolatilityStructure::smileSectionImpl (Time optionTime) const [protected, pure virtual]
implements the actual smile calculation in derived classes
Implemented in QuantLib::ConstantOptionletVolatility, QuantLib::StrippedOptionletAdapter, QuantLib::SpreadedOptionletVolatility, and QuantLib::CapletVarianceCurve.
Volatility QuantLib::OptionletVolatilityStructure::volatility (const Period & optionTenor, Rate strike, bool extrapolate = false) const [inline]
returns the volatility for a given option tenor and strike rate
Definition at line 129 of file optionletvolatilitystructure.hpp.
References QuantLib::VolatilityTermStructure::optionDateFromTenor().
Referenced by blackVariance(), and QuantLib::OptionletStripper2::performCalculations().
{
        Date optionDate = optionDateFromTenor(optionTenor);
        return volatility(optionDate, strike, extrapolate);
    }
Volatility QuantLib::OptionletVolatilityStructure::volatility (const Date & optionDate, Rate strike, bool extrapolate = false) const [inline]
returns the volatility for a given option date and strike rate
Definition at line 171 of file optionletvolatilitystructure.hpp.
References QuantLib::TermStructure::checkRange(), QuantLib::VolatilityTermStructure::checkStrike(), and volatilityImpl().
{
        checkRange(optionDate, extrapolate);
        checkStrike(strike, extrapolate);
        return volatilityImpl(optionDate, strike);
    }
Volatility QuantLib::OptionletVolatilityStructure::volatility (Time optionTime, Rate strike, bool extrapolate = false) const [inline]
returns the volatility for a given option time and strike rate
Definition at line 180 of file optionletvolatilitystructure.hpp.
References QuantLib::TermStructure::checkRange(), QuantLib::VolatilityTermStructure::checkStrike(), and volatilityImpl().
{
        checkRange(optionTime, extrapolate);
        checkStrike(strike, extrapolate);
        return volatilityImpl(optionTime, strike);
    }
Volatility QuantLib::OptionletVolatilityStructure::volatilityImpl (const Date & optionDate, Rate strike) const [inline, protected]
Definition at line 210 of file optionletvolatilitystructure.hpp.
References QuantLib::TermStructure::timeFromReference().
Referenced by volatility().
{
        return volatilityImpl(timeFromReference(optionDate), strike);
    }
virtual Volatility QuantLib::OptionletVolatilityStructure::volatilityImpl (Time optionTime, Rate strike) const [protected, pure virtual]
implements the actual volatility calculation in derived classes
Implemented in QuantLib::ConstantOptionletVolatility, QuantLib::StrippedOptionletAdapter, QuantLib::SpreadedOptionletVolatility, and QuantLib::CapletVarianceCurve.
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/optionlet/optionletvolatilitystructure.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/optionlet/optionletvolatilitystructure.cpp