QuantLib: QuantLib::CommodityCurve Class Reference
QuantLib::CommodityCurve Class Reference
Commodity term structure.
#include <commoditycurve.hpp>
Public Member Functions
CommodityCurve (const std::string &name, const CommodityType &commodityType, const Currency &currency, const UnitOfMeasure &unitOfMeasure, const Calendar &calendar, const std::vector< Date > &dates, const std::vector< Real > &prices, const DayCounter &dayCounter=Actual365Fixed())
CommodityCurve (const std::string &name, const CommodityType &commodityType, const Currency &currency, const UnitOfMeasure &unitOfMeasure, const Calendar &calendar, const DayCounter &dayCounter=Actual365Fixed())
Friends
class CommodityIndex
Inspectors
std::ostream & operator<< (std::ostream &out, const CommodityCurve &curve)
std::string name_
CommodityType commodityType_
UnitOfMeasure unitOfMeasure_
Currency currency_
std::vector< Date > dates_
std::vector< Time > times_
std::vector< Real > data_
Interpolation interpolation_
ForwardFlat interpolator_
boost::shared_ptr< CommodityCurve > basisOfCurve_
Real basisOfCurveUomConversionFactor_
const std::string & name () const
const CommodityType & commodityType () const
const UnitOfMeasure & unitOfMeasure () const
const Currency & currency () const
Date maxDate () const
the latest date for which the curve can return values
const std::vector< Time > & times () const
const std::vector< Date > & dates () const
const std::vector< Real > & prices () const
std::vector< std::pair< Date,
Real > > nodes () const
bool empty () const
void setPrices (std::map< Date, Real > &prices)
void setBasisOfCurve (const boost::shared_ptr< CommodityCurve > &basisOfCurve)
Real price (const Date &d, const boost::shared_ptr< ExchangeContracts > &exchangeContracts, Integer nearbyOffset) const
Real basisOfPrice (const Date &d) const
Date underlyingPriceDate (const Date &date, const boost::shared_ptr< ExchangeContracts > &exchangeContracts, Integer nearbyOffset) const
const boost::shared_ptr
< CommodityCurve > & basisOfCurve () const
Real basisOfPriceImpl (Time t) const
Real priceImpl (Time t) const
Detailed Description
Commodity term structure.
Definition at line 37 of file commoditycurve.hpp.
Constructor & Destructor Documentation
QuantLib::CommodityCurve::CommodityCurve (const std::string & name, const CommodityType & commodityType, const Currency & currency, const UnitOfMeasure & unitOfMeasure, const Calendar & calendar, const std::vector< Date > & dates, const std::vector< Real > & prices, const DayCounter & dayCounter = Actual365Fixed())
Definition at line 25 of file commoditycurve.cpp.
References data_, dates_, QuantLib::ForwardFlat::interpolate(), interpolation_, interpolator_, QL_REQUIRE, times_, QuantLib::Interpolation::update(), and QuantLib::DayCounter::yearFraction().
    : TermStructure(dates[0], calendar, dayCounter),
      name_(name), commodityType_(commodityType), unitOfMeasure_(unitOfMeasure),
      currency_(currency), dates_(dates), data_(prices),
      interpolator_(ForwardFlat()), basisOfCurveUomConversionFactor_(1) {
        QL_REQUIRE(dates_.size()>1, "too few dates");
        QL_REQUIRE(data_.size()==dates_.size(), "dates/prices count mismatch");
        times_.resize(dates_.size());
        times_[0]=0.0;
        for (Size i = 1; i < dates_.size(); i++) {
            QL_REQUIRE(dates_[i] > dates_[i-1],
                       "invalid date (" << dates_[i] << ", vs "
                       << dates_[i-1] << ")");
            times_[i] = dayCounter.yearFraction(dates_[0], dates_[i]);
        }
        interpolation_ =
            interpolator_.interpolate(times_.begin(), times_.end(),
                                      data_.begin());
        interpolation_.update();
    }
QuantLib::CommodityCurve::CommodityCurve (const std::string & name, const CommodityType & commodityType, const Currency & currency, const UnitOfMeasure & unitOfMeasure, const Calendar & calendar, const DayCounter & dayCounter = Actual365Fixed())
Definition at line 56 of file commoditycurve.cpp.
    : TermStructure(0, calendar, dayCounter),
      name_(name), commodityType_(commodityType), unitOfMeasure_(unitOfMeasure),
      currency_(currency), interpolator_(ForwardFlat()),
      basisOfCurveUomConversionFactor_(1) {}
Member Function Documentation
const boost::shared_ptr< CommodityCurve > & QuantLib::CommodityCurve::basisOfCurve () const [inline]
Definition at line 138 of file commoditycurve.hpp.
References basisOfCurve_.
Referenced by setBasisOfCurve().
{
        return basisOfCurve_;
    }
Real QuantLib::CommodityCurve::basisOfPrice (const Date & d) const [inline]
Definition at line 149 of file commoditycurve.hpp.
References basisOfPriceImpl(), anonymous_namespace{quantlibbenchmark.cpp}::t, and QuantLib::TermStructure::timeFromReference().
{
        Time t = timeFromReference(d);
        return basisOfPriceImpl(t);
    }
Real QuantLib::CommodityCurve::basisOfPriceImpl (Time t) const [inline, protected]
Definition at line 193 of file commoditycurve.hpp.
References basisOfCurve_, basisOfCurveUomConversionFactor_, name(), and QL_FAIL.
Referenced by basisOfPrice(), and price().
{
        if (basisOfCurve_ != 0) {
            Real basisCurvePriceValue = 0;
            try {
                basisCurvePriceValue =
                    basisOfCurve_->priceImpl(t)
                    * basisOfCurveUomConversionFactor_;
            } catch (const std::exception& e) {
                QL_FAIL("error retrieving price for curve [" << name() <<
                        "]: " << e.what());
            }
            return basisCurvePriceValue + basisOfCurve_->basisOfPriceImpl(t);
        }
        return 0;
    }
const CommodityType& QuantLib::CommodityCurve::commodityType () const
const Currency& QuantLib::CommodityCurve::currency () const
const std::vector< Date > & QuantLib::CommodityCurve::dates () const [inline]
Definition at line 125 of file commoditycurve.hpp.
References dates_.
{
        return dates_;
    }
bool QuantLib::CommodityCurve::empty () const [inline]
Definition at line 133 of file commoditycurve.hpp.
References dates_.
{
        return dates_.empty();
    }
Date QuantLib::CommodityCurve::maxDate () const [inline, virtual]
the latest date for which the curve can return values
Implements QuantLib::TermStructure.
Definition at line 117 of file commoditycurve.hpp.
References dates_.
{
        return dates_.back();
    }
const std::string & QuantLib::CommodityCurve::name () const [inline]
Definition at line 113 of file commoditycurve.hpp.
References name_.
Referenced by basisOfPriceImpl(), QuantLib::operator==(), price(), and underlyingPriceDate().
{
        return name_;
    }
std::vector< std::pair< Date, Real > > QuantLib::CommodityCurve::nodes () const [inline]
Definition at line 142 of file commoditycurve.hpp.
References data_, and dates_.
{
        std::vector<std::pair<Date,Real> > results(dates_.size());
        for (Size i = 0; i < dates_.size(); ++i)
            results[i] = std::make_pair(dates_[i], data_[i]);
        return results;
    }
Real QuantLib::CommodityCurve::price (const Date & d, const boost::shared_ptr< ExchangeContracts > & exchangeContracts, Integer nearbyOffset) const [inline]
Definition at line 155 of file commoditycurve.hpp.
References basisOfPriceImpl(), anonymous_namespace{marketmodel.cpp}::d, name(), priceImpl(), QL_FAIL, anonymous_namespace{quantlibbenchmark.cpp}::t, QuantLib::TermStructure::timeFromReference(), and underlyingPriceDate().
{
        Date date = nearbyOffset > 0 ?
            underlyingPriceDate(d, exchangeContracts, nearbyOffset) : d;
        Time t = timeFromReference(date);
        Real priceValue = 0;
        try {
            priceValue = priceImpl(t);
        } catch (const std::exception& e) {
            QL_FAIL("error retrieving price for curve [" << name() << "]: "
                    << e.what());
        }
        return priceValue + basisOfPriceImpl(t);
    }
Real QuantLib::CommodityCurve::priceImpl (Time t) const [inline, protected]
Definition at line 209 of file commoditycurve.hpp.
References interpolation_.
Referenced by price().
{
        return interpolation_(t, true);
    }
const std::vector< Real > & QuantLib::CommodityCurve::prices () const [inline]
Definition at line 129 of file commoditycurve.hpp.
References data_.
{
        return data_;
    }
void QuantLib::CommodityCurve::setBasisOfCurve (const boost::shared_ptr< CommodityCurve > & basisOfCurve)
Definition at line 88 of file commoditycurve.cpp.
References basisOfCurve(), basisOfCurve_, basisOfCurveUomConversionFactor_, QuantLib::CommodityPricingHelper::calculateUomConversionFactor(), commodityType_, and unitOfMeasure_.
{
        basisOfCurve_ = basisOfCurve;
        basisOfCurveUomConversionFactor_ =
            CommodityPricingHelper::calculateUomConversionFactor(
                                                commodityType_,
                                                basisOfCurve_->unitOfMeasure_,
                                                unitOfMeasure_);
    }
void QuantLib::CommodityCurve::setPrices (std::map< Date, Real > & prices)
Definition at line 67 of file commoditycurve.cpp.
References data_, dates_, QuantLib::TermStructure::dayCounter(), QuantLib::ForwardFlat::interpolate(), interpolation_, interpolator_, QL_REQUIRE, times_, QuantLib::Interpolation::update(), and QuantLib::DayCounter::yearFraction().
{
        QL_REQUIRE(prices.size()>1, "too few prices");
        dates_.empty();
        data_.empty();
        for (std::map<Date, Real>::const_iterator i = prices.begin(); i != prices.end(); i++) {
            dates_.push_back(i->first);
            data_.push_back(i->second);
        }
        times_.resize(dates_.size());
        times_[0]=0.0;
        for (Size i = 1; i < dates_.size(); i++)
            times_[i] = dayCounter().yearFraction(dates_[0], dates_[i]);
        interpolation_ =
            interpolator_.interpolate(times_.begin(), times_.end(),
                                      data_.begin());
        interpolation_.update();
    }
const std::vector< Time > & QuantLib::CommodityCurve::times () const [inline]
Definition at line 121 of file commoditycurve.hpp.
References times_.
{
        return times_;
    }
Date QuantLib::CommodityCurve::underlyingPriceDate (const Date & date, const boost::shared_ptr< ExchangeContracts > & exchangeContracts, Integer nearbyOffset) const [inline]
Definition at line 174 of file commoditycurve.hpp.
References name(), and QL_REQUIRE.
Referenced by price().
{
        QL_REQUIRE(nearbyOffset > 0, "nearby offset must be > 0");
        ExchangeContracts::const_iterator ic =
            exchangeContracts->lower_bound(date);
        if (ic != exchangeContracts->end()) {
            int i;
            for (i = 0; i < nearbyOffset-1 && ic!=exchangeContracts->end(); i++)
                ic++;
            QL_REQUIRE(ic != exchangeContracts->end(),
                       "not enough nearby contracts available for curve ["
                       << name() << "] for date [" << date << "].");
            return ic->second.underlyingStartDate();
        }
        return date;
    }
const UnitOfMeasure& QuantLib::CommodityCurve::unitOfMeasure () const
Friends And Related Function Documentation
friend class CommodityIndex [friend]
Definition at line 38 of file commoditycurve.hpp.
std::ostream& operator<< (std::ostream & out, const CommodityCurve & curve) [friend]
Definition at line 98 of file commoditycurve.cpp.
{
        out << "[" << curve.name_ << "] (" << curve.currency_.code()
            << "/" << curve.unitOfMeasure_.code() << ")";
        if (curve.basisOfCurve_ != 0)
            out << "; basis to (" << (*curve.basisOfCurve_) << ")";
        return out;
    }
Member Data Documentation
boost::shared_ptr<CommodityCurve> QuantLib::CommodityCurve::basisOfCurve_ [protected]
Definition at line 100 of file commoditycurve.hpp.
Referenced by basisOfCurve(), basisOfPriceImpl(), QuantLib::operator<<(), and setBasisOfCurve().
Real QuantLib::CommodityCurve::basisOfCurveUomConversionFactor_ [protected]
Definition at line 101 of file commoditycurve.hpp.
Referenced by basisOfPriceImpl(), and setBasisOfCurve().
CommodityType QuantLib::CommodityCurve::commodityType_ [protected]
Definition at line 92 of file commoditycurve.hpp.
Referenced by setBasisOfCurve().
Currency QuantLib::CommodityCurve::currency_ [protected]
Definition at line 94 of file commoditycurve.hpp.
Referenced by QuantLib::operator<<().
std::vector<Real> QuantLib::CommodityCurve::data_ [mutable, protected]
Definition at line 97 of file commoditycurve.hpp.
Referenced by CommodityCurve(), nodes(), prices(), and setPrices().
std::vector<Date> QuantLib::CommodityCurve::dates_ [mutable, protected]
Definition at line 95 of file commoditycurve.hpp.
Referenced by CommodityCurve(), dates(), empty(), maxDate(), nodes(), and setPrices().
Interpolation QuantLib::CommodityCurve::interpolation_ [mutable, protected]
Definition at line 98 of file commoditycurve.hpp.
Referenced by CommodityCurve(), priceImpl(), and setPrices().
ForwardFlat QuantLib::CommodityCurve::interpolator_ [protected]
Definition at line 99 of file commoditycurve.hpp.
Referenced by CommodityCurve(), and setPrices().
std::string QuantLib::CommodityCurve::name_ [protected]
Definition at line 91 of file commoditycurve.hpp.
Referenced by name(), and QuantLib::operator<<().
std::vector<Time> QuantLib::CommodityCurve::times_ [mutable, protected]
Definition at line 96 of file commoditycurve.hpp.
Referenced by CommodityCurve(), setPrices(), and times().
UnitOfMeasure QuantLib::CommodityCurve::unitOfMeasure_ [protected]
Definition at line 93 of file commoditycurve.hpp.
Referenced by QuantLib::operator<<(), and setBasisOfCurve().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/commodities/commoditycurve.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/commodities/commoditycurve.cpp