QuantLib: QuantLib::G2SwaptionEngine Class Reference
QuantLib::G2SwaptionEngine Class Reference
Swaption priced by means of the Black formula
#include <g2swaptionengine.hpp>
Public Member Functions
G2SwaptionEngine (const boost::shared_ptr< G2 > &model, Real range, Size intervals)
void calculate () const
Private Attributes
Real range_
Size intervals_
Detailed Description
Swaption priced by means of the Black formula
Warning:
The engine assumes that the exercise date equals the start date of the passed swap.
Definition at line 39 of file g2swaptionengine.hpp.
Constructor & Destructor Documentation
QuantLib::G2SwaptionEngine::G2SwaptionEngine (const boost::shared_ptr< G2 > & model, Real range, Size intervals) [inline]
Definition at line 45 of file g2swaptionengine.hpp.
        : GenericModelEngine<G2, Swaption::arguments, Swaption::results>(model),
          range_(range), intervals_(intervals) {}
Member Function Documentation
void QuantLib::G2SwaptionEngine::calculate () const [inline, virtual]
Implements QuantLib::PricingEngine.
Definition at line 50 of file g2swaptionengine.hpp.
References QuantLib::GenericEngine< Swaption::arguments, Swaption::results >::arguments_, QuantLib::VanillaSwap::fixedLegBPS(), QuantLib::VanillaSwap::fixedRate(), QuantLib::VanillaSwap::floatingLegBPS(), intervals_, QuantLib::GenericModelEngine< G2, Swaption::arguments, Swaption::results >::model_, QuantLib::Settlement::Physical, QL_REQUIRE, range_, QuantLib::GenericEngine< Swaption::arguments, Swaption::results >::results_, QuantLib::Instrument::setPricingEngine(), QuantLib::Swaption::arguments::settlementType, QuantLib::VanillaSwap::spread(), QuantLib::Swaption::arguments::swap, QuantLib::swap(), and QuantLib::Instrument::results::value.
{
            QL_REQUIRE(arguments_.settlementType == Settlement::Physical,
                       "cash-settled swaptions not priced with G2 engine");
            // adjust the fixed rate of the swap for the spread on the
            // floating leg (which is not taken into account by the
            // model)
            VanillaSwap swap = *arguments_.swap;
            swap.setPricingEngine(boost::shared_ptr<PricingEngine>(
                  new DiscountingSwapEngine(model_->termStructure(), false)));
            Spread correction = swap.spread() *
                std::fabs(swap.floatingLegBPS() / swap.fixedLegBPS());
            Rate fixedRate = swap.fixedRate() - correction;
            results_.value =  model_->swaption(arguments_, fixedRate,
                                               range_, intervals_);
        }
Member Data Documentation
Size QuantLib::G2SwaptionEngine::intervals_ [private]
Definition at line 69 of file g2swaptionengine.hpp.
Referenced by calculate().
Real QuantLib::G2SwaptionEngine::range_ [private]
Definition at line 68 of file g2swaptionengine.hpp.
Referenced by calculate().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/swaption/g2swaptionengine.hpp