QuantLib: QuantLib::FdmHestonHullWhiteEquityPart Class Reference
QuantLib::FdmHestonHullWhiteEquityPart Class Reference
#include <fdmhestonhullwhiteop.hpp>
Public Member Functions
FdmHestonHullWhiteEquityPart (const boost::shared_ptr< FdmMesher > &mesher, const boost::shared_ptr< HullWhite > &hwModel, const boost::shared_ptr< YieldTermStructure > &qTS)
void setTime (Time t1, Time t2)
const TripleBandLinearOp & getMap () const
Protected Attributes
const Array x_
Array varianceValues_
Array volatilityValues_
const FirstDerivativeOp dxMap_
const TripleBandLinearOp dxxMap_
TripleBandLinearOp mapT_
const boost::shared_ptr
< HullWhite > hwModel_
const boost::shared_ptr
< FdmMesher > mesher_
const boost::shared_ptr
< YieldTermStructure > qTS_
Detailed Description
Definition at line 41 of file fdmhestonhullwhiteop.hpp.
Constructor & Destructor Documentation
QuantLib::FdmHestonHullWhiteEquityPart::FdmHestonHullWhiteEquityPart (const boost::shared_ptr< FdmMesher > & mesher, const boost::shared_ptr< HullWhite > & hwModel, const boost::shared_ptr< YieldTermStructure > & qTS)
Definition at line 32 of file fdmhestonhullwhiteop.cpp.
References mesher_, QuantLib::Sqrt(), varianceValues_, and volatilityValues_.
    : x_(mesher->locations(2)),
      varianceValues_(0.5*mesher->locations(1)),
      dxMap_ (FirstDerivativeOp(0, mesher)),
      dxxMap_(SecondDerivativeOp(0, mesher).mult(0.5*mesher->locations(1))),
      mapT_   (0, mesher),
      hwModel_(hwModel),
      mesher_ (mesher),
      qTS_(qTS) {
        // on the boundary s_min and s_max the second derivative
        // d²V/dS² is zero and due to Ito's Lemma the variance term
        // in the drift should vanish.
        const boost::shared_ptr<FdmLinearOpLayout> layout = mesher_->layout();
        const FdmLinearOpIterator endIter = layout->end();
        for (FdmLinearOpIterator iter = layout->begin(); iter != endIter;
            ++iter) {
            if (   iter.coordinates()[0] == 0
                || iter.coordinates()[0] == layout->dim()[0]-1) {
                varianceValues_[iter.index()] = 0.0;
            }
        }
        volatilityValues_ = Sqrt(2*varianceValues_);
    }
Member Function Documentation
const TripleBandLinearOp & QuantLib::FdmHestonHullWhiteEquityPart::getMap () const
Definition at line 72 of file fdmhestonhullwhiteop.cpp.
References mapT_.
Referenced by QuantLib::FdmHestonHullWhiteOp::apply(), QuantLib::FdmHestonHullWhiteOp::apply_direction(), QuantLib::FdmHestonHullWhiteOp::solve_splitting(), and QuantLib::FdmHestonHullWhiteOp::toMatrix().
{
        return mapT_;
    }
void QuantLib::FdmHestonHullWhiteEquityPart::setTime (Time t1, Time t2)
Definition at line 60 of file fdmhestonhullwhiteop.cpp.
References QuantLib::TripleBandLinearOp::axpyb(), QuantLib::Continuous, dxMap_, dxxMap_, hwModel_, mapT_, QuantLib::anonymous_namespace{bjerksundstenslandengine.cpp}::phi(), qTS_, varianceValues_, and x_.
Referenced by QuantLib::FdmHestonHullWhiteOp::setTime().
{
        const boost::shared_ptr<OneFactorModel::ShortRateDynamics> dynamics =
            hwModel_->dynamics();
        const Real phi = 0.5*(  dynamics->shortRate(t1, 0.0)
                              + dynamics->shortRate(t2, 0.0));
        const Rate q = qTS_->forwardRate(t1, t2, Continuous).rate();
        mapT_.axpyb(x_+phi-varianceValues_-q, dxMap_, dxxMap_, Array());
    }
Member Data Documentation
const FirstDerivativeOp QuantLib::FdmHestonHullWhiteEquityPart::dxMap_ [protected]
Definition at line 54 of file fdmhestonhullwhiteop.hpp.
Referenced by setTime().
const TripleBandLinearOp QuantLib::FdmHestonHullWhiteEquityPart::dxxMap_ [protected]
Definition at line 55 of file fdmhestonhullwhiteop.hpp.
Referenced by setTime().
const boost::shared_ptr<HullWhite> QuantLib::FdmHestonHullWhiteEquityPart::hwModel_ [protected]
Definition at line 58 of file fdmhestonhullwhiteop.hpp.
Referenced by setTime().
TripleBandLinearOp QuantLib::FdmHestonHullWhiteEquityPart::mapT_ [protected]
Definition at line 56 of file fdmhestonhullwhiteop.hpp.
Referenced by getMap(), and setTime().
const boost::shared_ptr<FdmMesher> QuantLib::FdmHestonHullWhiteEquityPart::mesher_ [protected]
Definition at line 59 of file fdmhestonhullwhiteop.hpp.
Referenced by FdmHestonHullWhiteEquityPart().
const boost::shared_ptr<YieldTermStructure> QuantLib::FdmHestonHullWhiteEquityPart::qTS_ [protected]
Definition at line 60 of file fdmhestonhullwhiteop.hpp.
Referenced by setTime().
Array QuantLib::FdmHestonHullWhiteEquityPart::varianceValues_ [protected]
Definition at line 53 of file fdmhestonhullwhiteop.hpp.
Referenced by FdmHestonHullWhiteEquityPart(), and setTime().
Array QuantLib::FdmHestonHullWhiteEquityPart::volatilityValues_ [protected]
Definition at line 53 of file fdmhestonhullwhiteop.hpp.
Referenced by FdmHestonHullWhiteEquityPart().
const Array QuantLib::FdmHestonHullWhiteEquityPart::x_ [protected]
Definition at line 52 of file fdmhestonhullwhiteop.hpp.
Referenced by setTime().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/operators/fdmhestonhullwhiteop.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/operators/fdmhestonhullwhiteop.cpp