QuantLib: QuantLib::FdmStepConditionComposite Class Reference
QuantLib::FdmStepConditionComposite Class Reference
#include <fdmstepconditioncomposite.hpp>
Public Types
typedef std::list
< boost::shared_ptr
< StepCondition< Array > > > Conditions
Public Member Functions
FdmStepConditionComposite (const std::list< std::vector< Time > > &stoppingTimes, const Conditions &conditions)
void applyTo (Array &a, Time t) const
const std::vector< Time > & stoppingTimes () const
const Conditions & conditions () const
Static Public Member Functions
static boost::shared_ptr
< FdmStepConditionComposite > joinConditions (const boost::shared_ptr< FdmSnapshotCondition > &c1, const boost::shared_ptr< FdmStepConditionComposite > &c2)
static boost::shared_ptr
< FdmStepConditionComposite > vanillaComposite (const DividendSchedule &schedule, const boost::shared_ptr< Exercise > &exercise, const boost::shared_ptr< FdmMesher > &mesher, const boost::shared_ptr< FdmInnerValueCalculator > &calculator, const Date &refDate, const DayCounter &dayCounter)
Private Attributes
std::vector< Time > stoppingTimes_
const Conditions conditions_
Detailed Description
Definition at line 43 of file fdmstepconditioncomposite.hpp.
Member Typedef Documentation
typedef std::list<boost::shared_ptr<StepCondition<Array> > > QuantLib::FdmStepConditionComposite::Conditions
Definition at line 45 of file fdmstepconditioncomposite.hpp.
Constructor & Destructor Documentation
QuantLib::FdmStepConditionComposite::FdmStepConditionComposite (const std::list< std::vector< Time > > & stoppingTimes, const Conditions & conditions)
Definition at line 36 of file fdmstepconditioncomposite.cpp.
References stoppingTimes(), and stoppingTimes_.
Referenced by joinConditions(), and vanillaComposite().
    : conditions_(conditions) {
        std::set<Real> allStoppingTimes;
        for (std::list<std::vector<Time> >::const_iterator
             iter = stoppingTimes.begin(); iter != stoppingTimes.end();
             ++iter) {
            allStoppingTimes.insert(iter->begin(), iter->end());
        }
        stoppingTimes_ = std::vector<Time>(allStoppingTimes.begin(),
                                           allStoppingTimes.end());
    }
Member Function Documentation
void QuantLib::FdmStepConditionComposite::applyTo (Array & a, Time t) const [virtual]
Implements QuantLib::StepCondition< Array >.
Definition at line 60 of file fdmstepconditioncomposite.cpp.
References conditions_.
{
        for (Conditions::const_iterator iter = conditions_.begin();
             iter != conditions_.end(); ++iter) {
            (*iter)->applyTo(a, t);
        }
    }
const FdmStepConditionComposite::Conditions & QuantLib::FdmStepConditionComposite::conditions () const
Definition at line 52 of file fdmstepconditioncomposite.cpp.
References conditions_.
Referenced by joinConditions().
{
        return conditions_;
    }
boost::shared_ptr< FdmStepConditionComposite > QuantLib::FdmStepConditionComposite::joinConditions (const boost::shared_ptr< FdmSnapshotCondition > & c1, const boost::shared_ptr< FdmStepConditionComposite > & c2) [static]
Definition at line 68 of file fdmstepconditioncomposite.cpp.
References conditions(), FdmStepConditionComposite(), and stoppingTimes().
{
        std::list<std::vector<Time> > stoppingTimes;
        stoppingTimes.push_back(std::vector<Time>(1, c1->getTime()));
        stoppingTimes.push_back(c2->stoppingTimes());
        FdmStepConditionComposite::Conditions conditions;
        conditions.push_back(c1);
        conditions.push_back(c2);
        return boost::shared_ptr<FdmStepConditionComposite>(
            new FdmStepConditionComposite(stoppingTimes, conditions));
    }
const std::vector< Time > & QuantLib::FdmStepConditionComposite::stoppingTimes () const
Definition at line 56 of file fdmstepconditioncomposite.cpp.
References stoppingTimes_.
Referenced by FdmStepConditionComposite(), joinConditions(), and vanillaComposite().
{
        return stoppingTimes_;
    }
boost::shared_ptr< FdmStepConditionComposite > QuantLib::FdmStepConditionComposite::vanillaComposite (const DividendSchedule & schedule, const boost::shared_ptr< Exercise > & exercise, const boost::shared_ptr< FdmMesher > & mesher, const boost::shared_ptr< FdmInnerValueCalculator > & calculator, const Date & refDate, const DayCounter & dayCounter) [static]
Definition at line 85 of file fdmstepconditioncomposite.cpp.
References QuantLib::Exercise::American, QuantLib::Exercise::Bermudan, anonymous_namespace{marketmodel.cpp}::dayCounter, QuantLib::Exercise::European, FdmStepConditionComposite(), QL_REQUIRE, and stoppingTimes().
Referenced by QuantLib::FdG2SwaptionEngine::calculate(), QuantLib::FdHullWhiteSwaptionEngine::calculate(), QuantLib::FdExtOUJumpVanillaEngine::calculate(), QuantLib::Fd2dBlackScholesVanillaEngine::calculate(), QuantLib::FdBlackScholesRebateEngine::calculate(), QuantLib::FdHestonRebateEngine::calculate(), QuantLib::FdBlackScholesVanillaEngine::calculate(), QuantLib::FdKlugeExtOUSpreadEngine::calculate(), QuantLib::FdHestonHullWhiteVanillaEngine::calculate(), and QuantLib::FdHestonVanillaEngine::getSolverDesc().
{
        std::list<std::vector<Time> > stoppingTimes;
        std::list<boost::shared_ptr<StepCondition<Array> > > stepConditions;
        if(!cashFlow.empty()) {
            boost::shared_ptr<FdmDividendHandler> dividendCondition(
                new FdmDividendHandler(cashFlow, mesher,
                                       refDate, dayCounter, 0));
            stepConditions.push_back(dividendCondition);
            stoppingTimes.push_back(dividendCondition->dividendTimes());
        }
        QL_REQUIRE(   exercise->type() == Exercise::American
                   || exercise->type() == Exercise::European
                   || exercise->type() == Exercise::Bermudan,
                   "exercise type is not supported");
        if (exercise->type() == Exercise::American) {
            stepConditions.push_back(boost::shared_ptr<StepCondition<Array> >(
                          new FdmAmericanStepCondition(mesher,calculator)));
        }
        else if (exercise->type() == Exercise::Bermudan) {
            boost::shared_ptr<FdmBermudanStepCondition> bermudanCondition(
                new FdmBermudanStepCondition(exercise->dates(),
                                             refDate, dayCounter,
                                             mesher, calculator));
            stepConditions.push_back(bermudanCondition);
            stoppingTimes.push_back(bermudanCondition->exerciseTimes());
        }
        return boost::shared_ptr<FdmStepConditionComposite>(
            new FdmStepConditionComposite(stoppingTimes, stepConditions));
    }
Member Data Documentation
const Conditions QuantLib::FdmStepConditionComposite::conditions_ [private]
Definition at line 69 of file fdmstepconditioncomposite.hpp.
Referenced by applyTo(), and conditions().
std::vector<Time> QuantLib::FdmStepConditionComposite::stoppingTimes_ [private]
Definition at line 68 of file fdmstepconditioncomposite.hpp.
Referenced by FdmStepConditionComposite(), and stoppingTimes().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/stepconditions/fdmstepconditioncomposite.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/stepconditions/fdmstepconditioncomposite.cpp