QuantLib: QuantLib::FixedRateBond Class Reference
QuantLib::FixedRateBond Class Reference
fixed-rate bond
#include <fixedratebond.hpp>
Public Member Functions
FixedRateBond (Natural settlementDays, Real faceAmount, const Schedule &schedule, const std::vector< Rate > &coupons, const DayCounter &accrualDayCounter, BusinessDayConvention paymentConvention=Following, Real redemption=100.0, const Date &issueDate=Date(), const Calendar &paymentCalendar=Calendar())
simple annual compounding coupon rates
FixedRateBond (Natural settlementDays, const Calendar &couponCalendar, Real faceAmount, const Date &startDate, const Date &maturityDate, const Period &tenor, const std::vector< Rate > &coupons, const DayCounter &accrualDayCounter, BusinessDayConvention accrualConvention=Following, BusinessDayConvention paymentConvention=Following, Real redemption=100.0, const Date &issueDate=Date(), const Date &stubDate=Date(), DateGeneration::Rule rule=DateGeneration::Backward, bool endOfMonth=false, const Calendar &paymentCalendar=Calendar())
FixedRateBond (Natural settlementDays, Real faceAmount, const Schedule &schedule, const std::vector< InterestRate > &coupons, BusinessDayConvention paymentConvention=Following, Real redemption=100.0, const Date &issueDate=Date(), const Calendar &paymentCalendar=Calendar())
generic compounding and frequency InterestRate coupons
Frequency frequency () const
const DayCounter & dayCounter () const
Protected Attributes
Frequency frequency_
DayCounter dayCounter_
Detailed Description
fixed-rate bond
Test:
calculations are tested by checking results against cached values.
Definition at line 46 of file fixedratebond.hpp.
Constructor & Destructor Documentation
QuantLib::FixedRateBond::FixedRateBond (Natural settlementDays, Real faceAmount, const Schedule & schedule, const std::vector< Rate > & coupons, const DayCounter & accrualDayCounter, BusinessDayConvention paymentConvention = Following, Real redemption = 100.0, const Date & issueDate = Date(), const Calendar & paymentCalendar = Calendar())
simple annual compounding coupon rates
Definition at line 31 of file fixedratebond.cpp.
References QuantLib::Bond::addRedemptionsToCashflows(), QuantLib::Bond::calendar_, QuantLib::Bond::cashflows(), QuantLib::Bond::cashflows_, QuantLib::Schedule::endDate(), QuantLib::Bond::maturityDate_, QL_ENSURE, QuantLib::Bond::redemptions_, QuantLib::FixedRateLeg::withCouponRates(), QuantLib::FixedRateLeg::withNotionals(), QuantLib::FixedRateLeg::withPaymentAdjustment(), and QuantLib::FixedRateLeg::withPaymentCalendar().
     : Bond(settlementDays,
            paymentCalendar==Calendar() ? schedule.calendar() : paymentCalendar,
            issueDate),
      frequency_(schedule.tenor().frequency()),
      dayCounter_(accrualDayCounter) {
        maturityDate_ = schedule.endDate();
        cashflows_ = FixedRateLeg(schedule)
            .withNotionals(faceAmount)
            .withCouponRates(coupons, accrualDayCounter)
            .withPaymentCalendar(calendar_)
            .withPaymentAdjustment(paymentConvention);
        addRedemptionsToCashflows(std::vector<Real>(1, redemption));
        QL_ENSURE(!cashflows().empty(), "bond with no cashflows!");
        QL_ENSURE(redemptions_.size() == 1, "multiple redemptions created");
    }
QuantLib::FixedRateBond::FixedRateBond (Natural settlementDays, const Calendar & couponCalendar, Real faceAmount, const Date & startDate, const Date & maturityDate, const Period & tenor, const std::vector< Rate > & coupons, const DayCounter & accrualDayCounter, BusinessDayConvention accrualConvention = Following, BusinessDayConvention paymentConvention = Following, Real redemption = 100.0, const Date & issueDate = Date(), const Date & stubDate = Date(), DateGeneration::Rule rule = DateGeneration::Backward, bool endOfMonth = false, const Calendar & paymentCalendar = Calendar())
simple annual compounding coupon rates with internal schedule calculation
Definition at line 60 of file fixedratebond.cpp.
References QuantLib::Bond::addRedemptionsToCashflows(), QuantLib::DateGeneration::Backward, QuantLib::Bond::calendar_, QuantLib::Bond::cashflows(), QuantLib::Bond::cashflows_, QuantLib::DateGeneration::Forward, QuantLib::Bond::maturityDate(), QuantLib::Bond::maturityDate_, QL_ENSURE, QL_FAIL, QuantLib::Bond::redemptions_, QuantLib::DateGeneration::ThirdWednesday, QuantLib::DateGeneration::Twentieth, QuantLib::DateGeneration::TwentiethIMM, QuantLib::FixedRateLeg::withCouponRates(), QuantLib::FixedRateLeg::withNotionals(), QuantLib::FixedRateLeg::withPaymentAdjustment(), QuantLib::FixedRateLeg::withPaymentCalendar(), and QuantLib::DateGeneration::Zero.
     : Bond(settlementDays,
            paymentCalendar==Calendar() ? calendar : paymentCalendar,
            issueDate),
      frequency_(tenor.frequency()), dayCounter_(accrualDayCounter) {
        maturityDate_ = maturityDate;
        Date firstDate, nextToLastDate;
        switch (rule) {
          case DateGeneration::Backward:
            firstDate = Date();
            nextToLastDate = stubDate;
            break;
          case DateGeneration::Forward:
            firstDate = stubDate;
            nextToLastDate = Date();
            break;
          case DateGeneration::Zero:
          case DateGeneration::ThirdWednesday:
          case DateGeneration::Twentieth:
          case DateGeneration::TwentiethIMM:
            QL_FAIL("stub date (" << stubDate << ") not allowed with " <<
                    rule << " DateGeneration::Rule");
          default:
            QL_FAIL("unknown DateGeneration::Rule (" << Integer(rule) << ")");
        }
        Schedule schedule(startDate, maturityDate_, tenor,
                          calendar, accrualConvention, accrualConvention,
                          rule, endOfMonth,
                          firstDate, nextToLastDate);
        cashflows_ = FixedRateLeg(schedule)
            .withNotionals(faceAmount)
            .withCouponRates(coupons, accrualDayCounter)
            .withPaymentCalendar(calendar_)
            .withPaymentAdjustment(paymentConvention);
        addRedemptionsToCashflows(std::vector<Real>(1, redemption));
        QL_ENSURE(!cashflows().empty(), "bond with no cashflows!");
        QL_ENSURE(redemptions_.size() == 1, "multiple redemptions created");
    }
QuantLib::FixedRateBond::FixedRateBond (Natural settlementDays, Real faceAmount, const Schedule & schedule, const std::vector< InterestRate > & coupons, BusinessDayConvention paymentConvention = Following, Real redemption = 100.0, const Date & issueDate = Date(), const Calendar & paymentCalendar = Calendar())
generic compounding and frequency InterestRate coupons
Definition at line 120 of file fixedratebond.cpp.
References QuantLib::Bond::addRedemptionsToCashflows(), QuantLib::Bond::calendar_, QuantLib::Bond::cashflows(), QuantLib::Bond::cashflows_, QuantLib::Schedule::endDate(), QuantLib::Bond::maturityDate_, QL_ENSURE, QuantLib::Bond::redemptions_, QuantLib::FixedRateLeg::withCouponRates(), QuantLib::FixedRateLeg::withNotionals(), QuantLib::FixedRateLeg::withPaymentAdjustment(), and QuantLib::FixedRateLeg::withPaymentCalendar().
     : Bond(settlementDays,
            paymentCalendar==Calendar() ? schedule.calendar() : paymentCalendar,
            issueDate),
      frequency_(schedule.tenor().frequency()),
      dayCounter_(coupons[0].dayCounter()) {
        maturityDate_ = schedule.endDate();
        cashflows_ = FixedRateLeg(schedule)
            .withNotionals(faceAmount)
            .withCouponRates(coupons)
            .withPaymentCalendar(calendar_)
            .withPaymentAdjustment(paymentConvention);
        addRedemptionsToCashflows(std::vector<Real>(1, redemption));
        QL_ENSURE(!cashflows().empty(), "bond with no cashflows!");
        QL_ENSURE(redemptions_.size() == 1, "multiple redemptions created");
    }
Member Function Documentation
const DayCounter& QuantLib::FixedRateBond::dayCounter () const [inline]
Definition at line 86 of file fixedratebond.hpp.
References dayCounter_.
{ return dayCounter_; }
Frequency QuantLib::FixedRateBond::frequency () const [inline]
Definition at line 85 of file fixedratebond.hpp.
References frequency_.
{ return frequency_; }
Member Data Documentation
DayCounter QuantLib::FixedRateBond::dayCounter_ [protected]
Definition at line 89 of file fixedratebond.hpp.
Referenced by dayCounter().
Frequency QuantLib::FixedRateBond::frequency_ [protected]
Definition at line 88 of file fixedratebond.hpp.
Referenced by frequency().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/bonds/fixedratebond.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/bonds/fixedratebond.cpp