QuantLib: QuantLib::DiscretizedConvertible Class Reference
QuantLib::DiscretizedConvertible Class Reference
#include <discretizedconvertible.hpp>
Public Member Functions
DiscretizedConvertible (const ConvertibleBond::option::arguments &, const boost::shared_ptr< GeneralizedBlackScholesProcess > &process, const TimeGrid &grid=TimeGrid())
void reset (Size size)
const Array & conversionProbability () const
Array & conversionProbability ()
const Array & spreadAdjustedRate () const
Array & spreadAdjustedRate ()
const Array & dividendValues () const
Array & dividendValues ()
std::vector< Time > mandatoryTimes () const
Protected Member Functions
void postAdjustValuesImpl ()
Protected Attributes
Array conversionProbability_
Array spreadAdjustedRate_
Array dividendValues_
Private Member Functions
Disposable< Array > adjustedGrid () const
void applyConvertibility ()
void applyCallability (Size, bool convertible)
void addCoupon (Size)
Private Attributes
ConvertibleBond::option::arguments arguments_
boost::shared_ptr
< GeneralizedBlackScholesProcess > process_
std::vector< Time > stoppingTimes_
std::vector< Time > callabilityTimes_
std::vector< Time > couponTimes_
std::vector< Time > dividendTimes_
Detailed Description
Definition at line 34 of file discretizedconvertible.hpp.
Constructor & Destructor Documentation
QuantLib::DiscretizedConvertible::DiscretizedConvertible (const ConvertibleBond::option::arguments & args, const boost::shared_ptr< GeneralizedBlackScholesProcess > & process, const TimeGrid & grid = TimeGrid())
Definition at line 27 of file discretizedconvertible.cpp.
References arguments_, QuantLib::ConvertibleBond::option::arguments::callabilityDates, callabilityTimes_, QuantLib::TimeGrid::closestTime(), QuantLib::ConvertibleBond::option::arguments::couponDates, couponTimes_, anonymous_namespace{marketmodel.cpp}::dayCounter, QuantLib::ConvertibleBond::option::arguments::dividendDates, QuantLib::ConvertibleBond::option::arguments::dividends, dividendTimes_, dividendValues_, QuantLib::TimeGrid::empty(), QuantLib::Option::arguments::exercise, process_, QuantLib::ConvertibleBond::option::arguments::settlementDate, stoppingTimes_, and QuantLib::DayCounter::yearFraction().
    : arguments_(args), process_(process) {
        dividendValues_ = Array(arguments_.dividends.size(), 0.0);
        Date settlementDate = process_->riskFreeRate()->referenceDate();
        for (Size i=0; i<arguments_.dividends.size(); i++) {
            if (arguments_.dividends[i]->date() >= settlementDate) {
                dividendValues_[i] =
                    arguments_.dividends[i]->amount() *
                    process_->riskFreeRate()->discount(
                                             arguments_.dividends[i]->date());
            }
        }
        DayCounter dayCounter = process_->riskFreeRate()->dayCounter();
        Date bondSettlement = arguments_.settlementDate;
        stoppingTimes_.resize(arguments_.exercise->dates().size());
        for (Size i=0; i<stoppingTimes_.size(); ++i)
            stoppingTimes_[i] =
                dayCounter.yearFraction(bondSettlement,
                                        arguments_.exercise->date(i));
        callabilityTimes_.resize(arguments_.callabilityDates.size());
        for (Size i=0; i<callabilityTimes_.size(); ++i)
            callabilityTimes_[i] =
                dayCounter.yearFraction(bondSettlement,
                                        arguments_.callabilityDates[i]);
        couponTimes_.resize(arguments_.couponDates.size());
        for (Size i=0; i<couponTimes_.size(); ++i)
            couponTimes_[i] =
                dayCounter.yearFraction(bondSettlement,
                                        arguments_.couponDates[i]);
        dividendTimes_.resize(arguments_.dividendDates.size());
        for (Size i=0; i<dividendTimes_.size(); ++i)
            dividendTimes_[i] =
                dayCounter.yearFraction(bondSettlement,
                                        arguments_.dividendDates[i]);
        if (!grid.empty()) {
            // adjust times to grid
            for (Size i=0; i<stoppingTimes_.size(); i++)
                stoppingTimes_[i] = grid.closestTime(stoppingTimes_[i]);
            for (Size i=0; i<couponTimes_.size(); i++)
                couponTimes_[i] = grid.closestTime(couponTimes_[i]);
            for (Size i=0; i<callabilityTimes_.size(); i++)
                callabilityTimes_[i] = grid.closestTime(callabilityTimes_[i]);
            for (Size i=0; i<dividendTimes_.size(); i++)
                dividendTimes_[i] = grid.closestTime(dividendTimes_[i]);
        }
    }
Member Function Documentation
void QuantLib::DiscretizedConvertible::addCoupon (Size i) [private]
Definition at line 211 of file discretizedconvertible.cpp.
References arguments_, QuantLib::ConvertibleBond::option::arguments::couponAmounts, and QuantLib::DiscretizedAsset::values_.
Referenced by postAdjustValuesImpl().
{
        values_ += arguments_.couponAmounts[i];
    }
Disposable< Array > QuantLib::DiscretizedConvertible::adjustedGrid () const [private]
Definition at line 215 of file discretizedconvertible.cpp.
References arguments_, QuantLib::close(), anonymous_namespace{marketmodel.cpp}::d, QuantLib::ConvertibleBond::option::arguments::dividends, dividendTimes_, QuantLib::DiscretizedAsset::method(), process_, QuantLib::Array::size(), anonymous_namespace{quantlibbenchmark.cpp}::t, and QuantLib::DiscretizedAsset::time().
Referenced by applyCallability(), and applyConvertibility().
{
        Time t = time();
        Array grid = method()->grid(t);
        // add back all dividend amounts in the future
        for (Size i=0; i<arguments_.dividends.size(); i++) {
            Time dividendTime = dividendTimes_[i];
            if (dividendTime >= t || close(dividendTime,t)) {
                const boost::shared_ptr<Dividend>& d = arguments_.dividends[i];
                DiscountFactor dividendDiscount =
                    process_->riskFreeRate()->discount(dividendTime) /
                    process_->riskFreeRate()->discount(t);
                for (Size j=0; j<grid.size(); j++)
                    grid[j] += d->amount(grid[j])*dividendDiscount;
            }
        }
        return grid;
    }
void QuantLib::DiscretizedConvertible::applyCallability (Size i, bool convertible) [private]
Definition at line 164 of file discretizedconvertible.cpp.
References adjustedGrid(), arguments_, QuantLib::Callability::Call, QuantLib::ConvertibleBond::option::arguments::callabilityPrices, QuantLib::ConvertibleBond::option::arguments::callabilityTriggers, QuantLib::ConvertibleBond::option::arguments::callabilityTypes, QuantLib::ConvertibleBond::option::arguments::conversionRatio, QuantLib::Callability::Put, QL_FAIL, QuantLib::ConvertibleBond::option::arguments::redemption, QuantLib::Array::size(), and QuantLib::DiscretizedAsset::values_.
Referenced by postAdjustValuesImpl().
{
        Size j;
        Array grid = adjustedGrid();
        switch (arguments_.callabilityTypes[i]) {
          case Callability::Call:
            if (arguments_.callabilityTriggers[i] != Null<Real>()) {
                Real conversionValue =
                    arguments_.redemption/arguments_.conversionRatio;
                Real trigger =
                    conversionValue*arguments_.callabilityTriggers[i];
                for (j=0; j<values_.size(); j++) {
                    // the callability is conditioned by the trigger...
                    if (grid[j] >= trigger) {
                        // ...and might trigger conversion
                        values_[j] =
                            std::min(std::max(
                                          arguments_.callabilityPrices[i],
                                          arguments_.conversionRatio*grid[j]),
                                     values_[j]);
                    }
                }
            } else if (convertible) {
                for (j=0; j<values_.size(); j++) {
                    // exercising the callability might trigger conversion
                    values_[j] =
                        std::min(std::max(arguments_.callabilityPrices[i],
                                          arguments_.conversionRatio*grid[j]),
                                 values_[j]);
                }
            } else {
                for (j=0; j<values_.size(); j++) {
                    values_[j] = std::min(arguments_.callabilityPrices[i],
                                          values_[j]);
                }
            }
            break;
          case Callability::Put:
            for (j=0; j<values_.size(); j++) {
                values_[j] = std::max(values_[j],
                                      arguments_.callabilityPrices[i]);
            }
            break;
          default:
            QL_FAIL("unknown callability type");
        }
    }
void QuantLib::DiscretizedConvertible::applyConvertibility () [private]
Definition at line 153 of file discretizedconvertible.cpp.
References adjustedGrid(), arguments_, conversionProbability_, QuantLib::ConvertibleBond::option::arguments::conversionRatio, QuantLib::Array::size(), and QuantLib::DiscretizedAsset::values_.
Referenced by postAdjustValuesImpl().
{
        Array grid = adjustedGrid();
        for (Size j=0; j<values_.size(); j++) {
            Real payoff = arguments_.conversionRatio*grid[j];
            if (values_[j] <= payoff) {
                values_[j] = payoff;
                conversionProbability_[j] = 1.0;
            }
        }
    }
const Array& QuantLib::DiscretizedConvertible::conversionProbability () const [inline]
Definition at line 43 of file discretizedconvertible.hpp.
References conversionProbability_.
Referenced by QuantLib::TsiveriotisFernandesLattice< T >::partialRollback().
{
            return conversionProbability_;
        }
Array& QuantLib::DiscretizedConvertible::conversionProbability () [inline]
Definition at line 46 of file discretizedconvertible.hpp.
References conversionProbability_.
{ return conversionProbability_; }
const Array& QuantLib::DiscretizedConvertible::dividendValues () const [inline]
Definition at line 51 of file discretizedconvertible.hpp.
References dividendValues_.
{ return dividendValues_; }
Array& QuantLib::DiscretizedConvertible::dividendValues () [inline]
Definition at line 52 of file discretizedconvertible.hpp.
References dividendValues_.
{ return dividendValues_; }
std::vector<Time> QuantLib::DiscretizedConvertible::mandatoryTimes () const [inline, virtual]
This method returns the times at which the numerical method should stop while rolling back the asset. Typical examples include payment times, exercise times and such.
Note:
The returned values are not guaranteed to be sorted.
Implements QuantLib::DiscretizedAsset.
Definition at line 54 of file discretizedconvertible.hpp.
References callabilityTimes_, couponTimes_, and stoppingTimes_.
{
            std::vector<Time> result;
            std::copy(stoppingTimes_.begin(), stoppingTimes_.end(),
                      std::back_inserter(result));
            std::copy(callabilityTimes_.begin(), callabilityTimes_.end(),
                      std::back_inserter(result));
            std::copy(couponTimes_.begin(), couponTimes_.end(),
                      std::back_inserter(result));
            return result;
        }
void QuantLib::DiscretizedConvertible::postAdjustValuesImpl () [protected, virtual]
This method performs the actual post-adjustment
Reimplemented from QuantLib::DiscretizedAsset.
Definition at line 117 of file discretizedconvertible.cpp.
References addCoupon(), QuantLib::Exercise::American, applyCallability(), applyConvertibility(), arguments_, QuantLib::Exercise::Bermudan, callabilityTimes_, couponTimes_, QuantLib::Exercise::European, QuantLib::Option::arguments::exercise, QuantLib::DiscretizedAsset::isOnTime(), QL_FAIL, stoppingTimes_, and QuantLib::DiscretizedAsset::time().
{
        bool convertible = false;
        switch (arguments_.exercise->type()) {
          case Exercise::American:
            if (time() <= stoppingTimes_[1] && time() >= stoppingTimes_[0])
                convertible = true;
            break;
          case Exercise::European:
            if (isOnTime(stoppingTimes_[0]))
                convertible = true;
            break;
          case Exercise::Bermudan:
            for (Size i=0; i<stoppingTimes_.size(); ++i) {
                if (isOnTime(stoppingTimes_[i]))
                    convertible = true;
            }
            break;
          default:
            QL_FAIL("invalid option type");
        }
        for (Size i=0; i<callabilityTimes_.size(); i++) {
            if (isOnTime(callabilityTimes_[i]))
                applyCallability(i,convertible);
        }
        for (Size i=0; i<couponTimes_.size(); i++) {
            if (isOnTime(couponTimes_[i]))
                addCoupon(i);
        }
        if (convertible)
            applyConvertibility();
    }
void QuantLib::DiscretizedConvertible::reset (Size size) [virtual]
This method should initialize the asset values to an Array of the given size and with values depending on the particular asset.
Implements QuantLib::DiscretizedAsset.
Definition at line 85 of file discretizedconvertible.cpp.
References QuantLib::DiscretizedAsset::adjustValues(), arguments_, QuantLib::Continuous, conversionProbability_, QuantLib::ConvertibleBond::option::arguments::creditSpread, QuantLib::Option::arguments::exercise, QuantLib::NoFrequency, process_, QuantLib::ConvertibleBond::option::arguments::redemption, QuantLib::Array::size(), spreadAdjustedRate_, and QuantLib::DiscretizedAsset::values_.
{
        // Set to bond redemption values
        values_ = Array(size, arguments_.redemption);
        // coupon amounts should be added when adjusting
        // values_ = Array(size, arguments_.cashFlows.back()->amount());
        conversionProbability_ = Array(size, 0.0);
        spreadAdjustedRate_ = Array(size, 0.0);
        DayCounter rfdc  = process_->riskFreeRate()->dayCounter();
        // this takes care of convertibility and conversion probabilities
        adjustValues();
        Real creditSpread = arguments_.creditSpread->value();
        Date exercise = arguments_.exercise->lastDate();
        Rate riskFreeRate =
            process_->riskFreeRate()->zeroRate(exercise, rfdc,
                                               Continuous, NoFrequency);
        // Calculate blended discount rate to be used on roll back.
        for (Size j=0; j<values_.size(); j++) {
           spreadAdjustedRate_[j] =
               conversionProbability_[j] * riskFreeRate +
               (1-conversionProbability_[j])*(riskFreeRate + creditSpread);
        }
    }
const Array& QuantLib::DiscretizedConvertible::spreadAdjustedRate () const [inline]
Definition at line 48 of file discretizedconvertible.hpp.
References spreadAdjustedRate_.
Referenced by QuantLib::TsiveriotisFernandesLattice< T >::partialRollback().
{ return spreadAdjustedRate_; }
Array& QuantLib::DiscretizedConvertible::spreadAdjustedRate () [inline]
Definition at line 49 of file discretizedconvertible.hpp.
References spreadAdjustedRate_.
{ return spreadAdjustedRate_; }
Member Data Documentation
ConvertibleBond::option::arguments QuantLib::DiscretizedConvertible::arguments_ [private]
Definition at line 74 of file discretizedconvertible.hpp.
Referenced by addCoupon(), adjustedGrid(), applyCallability(), applyConvertibility(), DiscretizedConvertible(), postAdjustValuesImpl(), and reset().
std::vector<Time> QuantLib::DiscretizedConvertible::callabilityTimes_ [private]
Definition at line 77 of file discretizedconvertible.hpp.
Referenced by DiscretizedConvertible(), mandatoryTimes(), and postAdjustValuesImpl().
Array QuantLib::DiscretizedConvertible::conversionProbability_ [protected]
Definition at line 67 of file discretizedconvertible.hpp.
Referenced by applyConvertibility(), conversionProbability(), and reset().
std::vector<Time> QuantLib::DiscretizedConvertible::couponTimes_ [private]
Definition at line 78 of file discretizedconvertible.hpp.
Referenced by DiscretizedConvertible(), mandatoryTimes(), and postAdjustValuesImpl().
std::vector<Time> QuantLib::DiscretizedConvertible::dividendTimes_ [private]
Definition at line 79 of file discretizedconvertible.hpp.
Referenced by adjustedGrid(), and DiscretizedConvertible().
Array QuantLib::DiscretizedConvertible::dividendValues_ [protected]
Definition at line 67 of file discretizedconvertible.hpp.
Referenced by DiscretizedConvertible(), and dividendValues().
boost::shared_ptr<GeneralizedBlackScholesProcess> QuantLib::DiscretizedConvertible::process_ [private]
Definition at line 75 of file discretizedconvertible.hpp.
Referenced by adjustedGrid(), DiscretizedConvertible(), and reset().
Array QuantLib::DiscretizedConvertible::spreadAdjustedRate_ [protected]
Definition at line 67 of file discretizedconvertible.hpp.
Referenced by reset(), and spreadAdjustedRate().
std::vector<Time> QuantLib::DiscretizedConvertible::stoppingTimes_ [private]
Definition at line 76 of file discretizedconvertible.hpp.
Referenced by DiscretizedConvertible(), mandatoryTimes(), and postAdjustValuesImpl().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/convertiblebonds/discretizedconvertible.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/convertiblebonds/discretizedconvertible.cpp