QuantLib: QuantLib::FdmBackwardSolver Class Reference
QuantLib::FdmBackwardSolver Class Reference
#include <fdmbackwardsolver.hpp>
Public Types
typedef FdmLinearOp::array_type array_type
Public Member Functions
FdmBackwardSolver (const boost::shared_ptr< FdmLinearOpComposite > &map, const FdmBoundaryConditionSet &bcSet, const boost::shared_ptr< FdmStepConditionComposite > condition, const FdmSchemeDesc &schemeDesc)
void rollback (array_type &a, Time from, Time to, Size steps, Size dampingSteps)
Protected Attributes
const boost::shared_ptr
< FdmLinearOpComposite > map_
const FdmBoundaryConditionSet bcSet_
const boost::shared_ptr
< FdmStepConditionComposite > condition_
const FdmSchemeDesc schemeDesc_
Detailed Description
Definition at line 55 of file fdmbackwardsolver.hpp.
Member Typedef Documentation
typedef FdmLinearOp::array_type QuantLib::FdmBackwardSolver::array_type
Definition at line 57 of file fdmbackwardsolver.hpp.
Constructor & Destructor Documentation
QuantLib::FdmBackwardSolver::FdmBackwardSolver (const boost::shared_ptr< FdmLinearOpComposite > & map, const FdmBoundaryConditionSet & bcSet, const boost::shared_ptr< FdmStepConditionComposite > condition, const FdmSchemeDesc & schemeDesc)
Definition at line 71 of file fdmbackwardsolver.cpp.
    : map_(map), bcSet_(bcSet),
      condition_((condition) ? condition
                             : boost::shared_ptr<FdmStepConditionComposite>(
                                 new FdmStepConditionComposite(
                                     std::list<std::vector<Time> >(),
                                     FdmStepConditionComposite::Conditions()))),
      schemeDesc_(schemeDesc) {
     }
Member Function Documentation
void QuantLib::FdmBackwardSolver::rollback (FdmBackwardSolver::array_type & rhs, Time from, Time to, Size steps, Size dampingSteps)
Definition at line 85 of file fdmbackwardsolver.cpp.
References bcSet_, condition_, QuantLib::FdmSchemeDesc::CraigSneydType, QuantLib::FdmSchemeDesc::DouglasType, QuantLib::FdmSchemeDesc::ExplicitEulerType, QuantLib::FdmSchemeDesc::HundsdorferType, QuantLib::FdmSchemeDesc::ImplicitEulerType, map_, QuantLib::FdmSchemeDesc::ModifiedCraigSneydType, QuantLib::FdmSchemeDesc::mu, QL_FAIL, QuantLib::FiniteDifferenceModel< Evolver >::rollback(), schemeDesc_, QuantLib::FdmSchemeDesc::theta, and QuantLib::FdmSchemeDesc::type.
Referenced by QuantLib::Fdm3DimSolver::performCalculations(), QuantLib::FdmNdimSolver< N >::performCalculations(), QuantLib::Fdm1DimSolver::performCalculations(), QuantLib::Fdm2DimSolver::performCalculations(), and FdmLinearOpTest::testCrankNicolsonWithDamping().
{
        const Time deltaT = from - to;
        const Size allSteps = steps + dampingSteps;
        const Time dampingTo = from - (deltaT*dampingSteps)/allSteps;
        if (   dampingSteps
            && schemeDesc_.type != FdmSchemeDesc::ImplicitEulerType) {
            ImplicitEulerScheme implicitEvolver(map_, bcSet_);
            FiniteDifferenceModel<ImplicitEulerScheme>
                    dampingModel(implicitEvolver, condition_->stoppingTimes());
            dampingModel.rollback(rhs, from, dampingTo,
                                  dampingSteps, *condition_);
        }
        switch (schemeDesc_.type) {
          case FdmSchemeDesc::HundsdorferType:
            {
                HundsdorferScheme hsEvolver(schemeDesc_.theta, schemeDesc_.mu,
                                            map_, bcSet_);
                FiniteDifferenceModel<HundsdorferScheme>
                               hsModel(hsEvolver, condition_->stoppingTimes());
                hsModel.rollback(rhs, dampingTo, to, steps, *condition_);
            }
            break;
          case FdmSchemeDesc::DouglasType:
            {
                DouglasScheme dsEvolver(schemeDesc_.theta, map_, bcSet_);
                FiniteDifferenceModel<DouglasScheme>
                               dsModel(dsEvolver, condition_->stoppingTimes());
                dsModel.rollback(rhs, dampingTo, to, steps, *condition_);
            }
            break;
          case FdmSchemeDesc::CraigSneydType:
            {
                CraigSneydScheme csEvolver(schemeDesc_.theta, schemeDesc_.mu,
                                           map_, bcSet_);
                FiniteDifferenceModel<CraigSneydScheme>
                               csModel(csEvolver, condition_->stoppingTimes());
                csModel.rollback(rhs, dampingTo, to, steps, *condition_);
            }
            break;
          case FdmSchemeDesc::ModifiedCraigSneydType:
            {
                ModifiedCraigSneydScheme csEvolver(schemeDesc_.theta,
                                                   schemeDesc_.mu,
                                                   map_, bcSet_);
                FiniteDifferenceModel<ModifiedCraigSneydScheme>
                              mcsModel(csEvolver, condition_->stoppingTimes());
                mcsModel.rollback(rhs, dampingTo, to, steps, *condition_);
            }
            break;
          case FdmSchemeDesc::ImplicitEulerType:
            {
                ImplicitEulerScheme implicitEvolver(map_, bcSet_);
                FiniteDifferenceModel<ImplicitEulerScheme>
                   implicitModel(implicitEvolver, condition_->stoppingTimes());
                implicitModel.rollback(rhs, from, to, allSteps, *condition_);
            }
            break;
          case FdmSchemeDesc::ExplicitEulerType:
            {
                ExplicitEulerScheme explicitEvolver(map_, bcSet_);
                FiniteDifferenceModel<ExplicitEulerScheme>
                   explicitModel(explicitEvolver, condition_->stoppingTimes());
                explicitModel.rollback(rhs, dampingTo, to, steps, *condition_);
            }
            break;
          default:
            QL_FAIL("Unknown scheme type");
        }
    }
Member Data Documentation
const FdmBoundaryConditionSet QuantLib::FdmBackwardSolver::bcSet_ [protected]
Definition at line 71 of file fdmbackwardsolver.hpp.
Referenced by rollback().
const boost::shared_ptr<FdmStepConditionComposite> QuantLib::FdmBackwardSolver::condition_ [protected]
Definition at line 72 of file fdmbackwardsolver.hpp.
Referenced by rollback().
const boost::shared_ptr<FdmLinearOpComposite> QuantLib::FdmBackwardSolver::map_ [protected]
Definition at line 70 of file fdmbackwardsolver.hpp.
Referenced by rollback().
const FdmSchemeDesc QuantLib::FdmBackwardSolver::schemeDesc_ [protected]
Definition at line 73 of file fdmbackwardsolver.hpp.
Referenced by rollback().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/solvers/fdmbackwardsolver.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/solvers/fdmbackwardsolver.cpp