QuantLib: QuantLib::MakeSchedule Class Reference
QuantLib::MakeSchedule Class Reference
helper class
#include <schedule.hpp>
Public Member Functions
MakeSchedule ()
MakeSchedule & from (const Date &effectiveDate)
MakeSchedule & to (const Date &terminationDate)
MakeSchedule & withTenor (const Period &)
MakeSchedule & withFrequency (Frequency)
MakeSchedule & withCalendar (const Calendar &)
MakeSchedule & withConvention (BusinessDayConvention)
MakeSchedule & withTerminationDateConvention (BusinessDayConvention)
MakeSchedule & withRule (DateGeneration::Rule)
MakeSchedule & forwards ()
MakeSchedule & backwards ()
MakeSchedule & endOfMonth (bool flag=true)
MakeSchedule & withFirstDate (const Date &d)
MakeSchedule & withNextToLastDate (const Date &d)
operator Schedule () const
Private Attributes
Calendar calendar_
Date effectiveDate_
Date terminationDate_
boost::optional< Period > tenor_
boost::optional
< BusinessDayConvention > convention_
boost::optional
< BusinessDayConvention > terminationDateConvention_
DateGeneration::Rule rule_
bool endOfMonth_
Date firstDate_
Date nextToLastDate_
Detailed Description
helper class
This class provides a more comfortable interface to the argument list of Schedule's constructor.
Definition at line 108 of file schedule.hpp.
Constructor & Destructor Documentation
QuantLib::MakeSchedule::MakeSchedule ()
Definition at line 450 of file schedule.cpp.
    : rule_(DateGeneration::Backward), endOfMonth_(false) {}
Member Function Documentation
MakeSchedule & QuantLib::MakeSchedule::backwards ()
Definition at line 499 of file schedule.cpp.
References QuantLib::DateGeneration::Backward, and rule_.
Referenced by CPISwapTest::consistency(), CPISwapTest::cpibondconsistency(), QuantLib::BMASwapRateHelper::initializeDates(), QuantLib::YearOnYearInflationSwapHelper::setTermStructure(), anonymous_namespace{piecewiseyieldcurve.cpp}::testBMACurveConsistency(), ConvertibleBondTest::testBond(), InflationCapFlooredCouponTest::testInstrumentEquality(), ConvertibleBondTest::testOption(), InflationCapFloorTest::testParity(), and InflationTest::testYYTermStructure().
{
        rule_ = DateGeneration::Backward;
        return *this;
    }
MakeSchedule & QuantLib::MakeSchedule::endOfMonth (bool flag = true)
Definition at line 504 of file schedule.cpp.
References endOfMonth_.
Referenced by ScheduleTest::testEndDateWithEomAdjustment().
{
        endOfMonth_ = flag;
        return *this;
    }
MakeSchedule & QuantLib::MakeSchedule::forwards ()
Definition at line 494 of file schedule.cpp.
References QuantLib::DateGeneration::Forward, and rule_.
Referenced by QuantLib::BMAIndex::fixingSchedule(), and ScheduleTest::testEndDateWithEomAdjustment().
{
        rule_ = DateGeneration::Forward;
        return *this;
    }
MakeSchedule & QuantLib::MakeSchedule::from (const Date & effectiveDate)
Definition at line 453 of file schedule.cpp.
References effectiveDate_.
Referenced by anonymous_namespace{inflationcapfloor.cpp}::CommonVars::CommonVars(), anonymous_namespace{inflationcpiswap.cpp}::CommonVars::CommonVars(), anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::CommonVars(), anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::CommonVars(), CPISwapTest::consistency(), CPISwapTest::cpibondconsistency(), QuantLib::BMAIndex::fixingSchedule(), QuantLib::CdsHelper::initializeDates(), QuantLib::BMASwapRateHelper::initializeDates(), QuantLib::OvernightIndexedCoupon::OvernightIndexedCoupon(), QuantLib::YearOnYearInflationSwapHelper::setTermStructure(), anonymous_namespace{piecewiseyieldcurve.cpp}::testBMACurveConsistency(), ConvertibleBondTest::testBond(), ScheduleTest::testDailySchedule(), ScheduleTest::testEndDateWithEomAdjustment(), CreditDefaultSwapTest::testFairSpread(), CreditDefaultSwapTest::testFairUpfront(), NthToDefaultTest::testGauss(), NthToDefaultTest::testGaussStudent(), CdoTest::testHW(), InflationCapFlooredCouponTest::testInstrumentEquality(), ConvertibleBondTest::testOption(), InflationCapFloorTest::testParity(), ConvertibleBondTest::testRegression(), InflationTest::testYYIndex(), InflationTest::testYYTermStructure(), InflationTest::testZeroIndex(), and InflationTest::testZeroTermStructure().
{
        effectiveDate_ = effectiveDate;
        return *this;
    }
QuantLib::MakeSchedule::operator Schedule () const
Definition at line 519 of file schedule.cpp.
References anonymous_namespace{marketmodel.cpp}::calendar, calendar_, convention_, effectiveDate_, QuantLib::Calendar::empty(), endOfMonth_, firstDate_, QuantLib::Following, nextToLastDate_, QL_REQUIRE, rule_, tenor_, terminationDate_, terminationDateConvention_, and QuantLib::Unadjusted.
{
        // check for mandatory arguments
        QL_REQUIRE(effectiveDate_ != Date(), "effective date not provided");
        QL_REQUIRE(terminationDate_ != Date(), "termination date not provided");
        QL_REQUIRE(tenor_, "tenor/frequency not provided");
        // set dynamic defaults:
        BusinessDayConvention convention;
        // if a convention was set, we use it.
        if (convention_) {
            convention = *convention_;
        } else {
            if (!calendar_.empty()) {
                // ...if we set a calendar, we probably want it to be used;
                convention = Following;
            } else {
                // if not, we don't care.
                convention = Unadjusted;
            }
        }
        BusinessDayConvention terminationDateConvention;
        // if set explicitly, we use it;
        if (terminationDateConvention_) {
            terminationDateConvention = *terminationDateConvention_;
        } else {
            // Unadjusted as per ISDA specification
            terminationDateConvention = convention;
        }
        Calendar calendar = calendar_;
        // if no calendar was set...
        if (calendar.empty()) {
            // ...we use a null one.
            calendar = NullCalendar();
        }
        return Schedule(effectiveDate_, terminationDate_, *tenor_, calendar,
                        convention, terminationDateConvention,
                        rule_, endOfMonth_, firstDate_, nextToLastDate_);
    }
MakeSchedule & QuantLib::MakeSchedule::to (const Date & terminationDate)
Definition at line 458 of file schedule.cpp.
References terminationDate_.
Referenced by anonymous_namespace{inflationcapfloor.cpp}::CommonVars::CommonVars(), anonymous_namespace{inflationcpiswap.cpp}::CommonVars::CommonVars(), anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::CommonVars(), anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::CommonVars(), CPISwapTest::consistency(), CPISwapTest::cpibondconsistency(), QuantLib::BMAIndex::fixingSchedule(), QuantLib::CdsHelper::initializeDates(), QuantLib::BMASwapRateHelper::initializeDates(), QuantLib::OvernightIndexedCoupon::OvernightIndexedCoupon(), QuantLib::YearOnYearInflationSwapHelper::setTermStructure(), anonymous_namespace{piecewiseyieldcurve.cpp}::testBMACurveConsistency(), ConvertibleBondTest::testBond(), ScheduleTest::testDailySchedule(), ScheduleTest::testEndDateWithEomAdjustment(), CreditDefaultSwapTest::testFairSpread(), CreditDefaultSwapTest::testFairUpfront(), NthToDefaultTest::testGauss(), NthToDefaultTest::testGaussStudent(), CdoTest::testHW(), InflationCapFlooredCouponTest::testInstrumentEquality(), ConvertibleBondTest::testOption(), InflationCapFloorTest::testParity(), ConvertibleBondTest::testRegression(), InflationTest::testYYIndex(), InflationTest::testYYTermStructure(), InflationTest::testZeroIndex(), and InflationTest::testZeroTermStructure().
{
        terminationDate_ = terminationDate;
        return *this;
    }
MakeSchedule & QuantLib::MakeSchedule::withCalendar (const Calendar & calendar)
Definition at line 473 of file schedule.cpp.
References anonymous_namespace{marketmodel.cpp}::calendar, and calendar_.
Referenced by anonymous_namespace{inflationcapfloor.cpp}::CommonVars::CommonVars(), anonymous_namespace{inflationcpiswap.cpp}::CommonVars::CommonVars(), anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::CommonVars(), anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::CommonVars(), CPISwapTest::consistency(), CPISwapTest::cpibondconsistency(), QuantLib::BMAIndex::fixingSchedule(), QuantLib::CdsHelper::initializeDates(), QuantLib::BMASwapRateHelper::initializeDates(), QuantLib::OvernightIndexedCoupon::OvernightIndexedCoupon(), QuantLib::YearOnYearInflationSwapHelper::setTermStructure(), anonymous_namespace{piecewiseyieldcurve.cpp}::testBMACurveConsistency(), ConvertibleBondTest::testBond(), ScheduleTest::testDailySchedule(), ScheduleTest::testEndDateWithEomAdjustment(), CreditDefaultSwapTest::testFairSpread(), CreditDefaultSwapTest::testFairUpfront(), NthToDefaultTest::testGauss(), NthToDefaultTest::testGaussStudent(), CdoTest::testHW(), InflationCapFlooredCouponTest::testInstrumentEquality(), ConvertibleBondTest::testOption(), InflationCapFloorTest::testParity(), ConvertibleBondTest::testRegression(), InflationTest::testYYIndex(), InflationTest::testYYTermStructure(), InflationTest::testZeroIndex(), and InflationTest::testZeroTermStructure().
{
        calendar_ = calendar;
        return *this;
    }
MakeSchedule & QuantLib::MakeSchedule::withConvention (BusinessDayConvention conv)
Definition at line 478 of file schedule.cpp.
References convention_.
Referenced by anonymous_namespace{inflationcapfloor.cpp}::CommonVars::CommonVars(), anonymous_namespace{inflationcpiswap.cpp}::CommonVars::CommonVars(), anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::CommonVars(), anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::CommonVars(), CPISwapTest::consistency(), CPISwapTest::cpibondconsistency(), QuantLib::BMAIndex::fixingSchedule(), QuantLib::CdsHelper::initializeDates(), QuantLib::YearOnYearInflationSwapHelper::setTermStructure(), ScheduleTest::testDailySchedule(), ScheduleTest::testEndDateWithEomAdjustment(), InflationCapFlooredCouponTest::testInstrumentEquality(), InflationCapFloorTest::testParity(), ConvertibleBondTest::testRegression(), InflationTest::testYYIndex(), InflationTest::testYYTermStructure(), InflationTest::testZeroIndex(), and InflationTest::testZeroTermStructure().
{
        convention_ = conv;
        return *this;
    }
MakeSchedule & QuantLib::MakeSchedule::withFirstDate (const Date & d)
Definition at line 509 of file schedule.cpp.
References anonymous_namespace{marketmodel.cpp}::d, and firstDate_.
{
        firstDate_ = d;
        return *this;
    }
MakeSchedule & QuantLib::MakeSchedule::withFrequency (Frequency frequency)
Definition at line 468 of file schedule.cpp.
References tenor_.
Referenced by QuantLib::BMAIndex::fixingSchedule(), QuantLib::CdsHelper::initializeDates(), anonymous_namespace{piecewiseyieldcurve.cpp}::testBMACurveConsistency(), ConvertibleBondTest::testBond(), ScheduleTest::testDailySchedule(), CreditDefaultSwapTest::testFairSpread(), CreditDefaultSwapTest::testFairUpfront(), and ConvertibleBondTest::testOption().
{
        tenor_ = Period(frequency);
        return *this;
    }
MakeSchedule & QuantLib::MakeSchedule::withNextToLastDate (const Date & d)
Definition at line 514 of file schedule.cpp.
References anonymous_namespace{marketmodel.cpp}::d, and nextToLastDate_.
{
        nextToLastDate_ = d;
        return *this;
    }
MakeSchedule & QuantLib::MakeSchedule::withRule (DateGeneration::Rule r)
Definition at line 489 of file schedule.cpp.
References rule_.
Referenced by QuantLib::CdsHelper::initializeDates(), CreditDefaultSwapTest::testFairSpread(), and CreditDefaultSwapTest::testFairUpfront().
{
        rule_ = r;
        return *this;
    }
MakeSchedule & QuantLib::MakeSchedule::withTenor (const Period & tenor)
Definition at line 463 of file schedule.cpp.
References tenor_.
Referenced by anonymous_namespace{inflationcapfloor.cpp}::CommonVars::CommonVars(), anonymous_namespace{inflationcpiswap.cpp}::CommonVars::CommonVars(), anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::CommonVars(), anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::CommonVars(), CPISwapTest::consistency(), CPISwapTest::cpibondconsistency(), QuantLib::BMASwapRateHelper::initializeDates(), QuantLib::OvernightIndexedCoupon::OvernightIndexedCoupon(), QuantLib::YearOnYearInflationSwapHelper::setTermStructure(), anonymous_namespace{piecewiseyieldcurve.cpp}::testBMACurveConsistency(), ScheduleTest::testEndDateWithEomAdjustment(), NthToDefaultTest::testGauss(), NthToDefaultTest::testGaussStudent(), CdoTest::testHW(), InflationCapFlooredCouponTest::testInstrumentEquality(), InflationCapFloorTest::testParity(), ConvertibleBondTest::testRegression(), InflationTest::testYYIndex(), InflationTest::testYYTermStructure(), InflationTest::testZeroIndex(), and InflationTest::testZeroTermStructure().
{
        tenor_ = tenor;
        return *this;
    }
MakeSchedule & QuantLib::MakeSchedule::withTerminationDateConvention (BusinessDayConvention conv)
Definition at line 483 of file schedule.cpp.
References terminationDateConvention_.
Referenced by QuantLib::CdsHelper::initializeDates(), ScheduleTest::testEndDateWithEomAdjustment(), CreditDefaultSwapTest::testFairSpread(), and CreditDefaultSwapTest::testFairUpfront().
{
        terminationDateConvention_ = conv;
        return *this;
    }
Member Data Documentation
Calendar QuantLib::MakeSchedule::calendar_ [private]
Definition at line 126 of file schedule.hpp.
Referenced by operator Schedule(), and withCalendar().
boost::optional<BusinessDayConvention> QuantLib::MakeSchedule::convention_ [private]
Definition at line 129 of file schedule.hpp.
Referenced by operator Schedule(), and withConvention().
Date QuantLib::MakeSchedule::effectiveDate_ [private]
Definition at line 127 of file schedule.hpp.
Referenced by from(), and operator Schedule().
bool QuantLib::MakeSchedule::endOfMonth_ [private]
Definition at line 132 of file schedule.hpp.
Referenced by endOfMonth(), and operator Schedule().
Date QuantLib::MakeSchedule::firstDate_ [private]
Definition at line 133 of file schedule.hpp.
Referenced by operator Schedule(), and withFirstDate().
Date QuantLib::MakeSchedule::nextToLastDate_ [private]
Definition at line 133 of file schedule.hpp.
Referenced by operator Schedule(), and withNextToLastDate().
DateGeneration::Rule QuantLib::MakeSchedule::rule_ [private]
Definition at line 131 of file schedule.hpp.
Referenced by backwards(), forwards(), operator Schedule(), and withRule().
boost::optional<Period> QuantLib::MakeSchedule::tenor_ [private]
Definition at line 128 of file schedule.hpp.
Referenced by operator Schedule(), withFrequency(), and withTenor().
Date QuantLib::MakeSchedule::terminationDate_ [private]
Definition at line 127 of file schedule.hpp.
Referenced by operator Schedule(), and to().
boost::optional<BusinessDayConvention> QuantLib::MakeSchedule::terminationDateConvention_ [private]
Definition at line 130 of file schedule.hpp.
Referenced by operator Schedule(), and withTerminationDateConvention().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/time/schedule.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/time/schedule.cpp