QuantLib: QuantLib::FdmExtOUJumpOp Class Reference
QuantLib::FdmExtOUJumpOp Class Reference
#include <fdmextoujumpop.hpp>
Public Member Functions
FdmExtOUJumpOp (const boost::shared_ptr< FdmMesher > &mesher, const boost::shared_ptr< ExtOUWithJumpsProcess > &process, const boost::shared_ptr< YieldTermStructure > &rTS, const FdmBoundaryConditionSet &bcSet, Size integroIntegrationOrder)
Size size () const
void setTime (Time t1, Time t2)
Time \(t1 <= t2\) is required.
Disposable< Array > apply (const Array &r) const
Disposable< Array > apply_mixed (const Array &r) const
Disposable< Array > apply_direction (Size direction, const Array &r) const
Disposable< Array > solve_splitting (Size direction, const Array &r, Real s) const
Disposable< Array > preconditioner (const Array &r, Real s) const
Disposable< SparseMatrix > toMatrix () const
Private Member Functions
Disposable< Array > integro (const Array &r) const
Private Attributes
const boost::shared_ptr
< FdmMesher > mesher_
const boost::shared_ptr
< ExtOUWithJumpsProcess > process_
const boost::shared_ptr
< YieldTermStructure > rTS_
const FdmBoundaryConditionSet bcSet_
GaussLaguerreIntegration gaussLaguerreIntegration_
const Array x_
const boost::shared_ptr
< FdmExtendedOrnsteinUhlenbackOp > ouOp_
const TripleBandLinearOp dyMap_
SparseMatrix integroPart_
Detailed Description
References: Kluge, Timo L., 2008. Pricing Swing Options and other Electricity Derivatives, http://eprints.maths.ox.ac.uk/246/1/kluge.pdf
Definition at line 46 of file fdmextoujumpop.hpp.
Constructor & Destructor Documentation
QuantLib::FdmExtOUJumpOp::FdmExtOUJumpOp (const boost::shared_ptr< FdmMesher > & mesher, const boost::shared_ptr< ExtOUWithJumpsProcess > & process, const boost::shared_ptr< YieldTermStructure > & rTS, const FdmBoundaryConditionSet & bcSet, Size integroIntegrationOrder)
Definition at line 53 of file fdmextoujumpop.cpp.
References gaussLaguerreIntegration_, integroPart_, mesher_, process_, QuantLib::Array::size(), anonymous_namespace{stats.cpp}::weights, QuantLib::GaussianQuadrature::weights(), and QuantLib::GaussianQuadrature::x().
    : mesher_ (mesher),
      process_(process),
      rTS_    (rTS),
      bcSet_  (bcSet),
      gaussLaguerreIntegration_(integroIntegrationOrder),
      x_      (mesher->locations(0)),
      ouOp_   (new FdmExtendedOrnsteinUhlenbackOp(
                   mesher,
                   process->getExtendedOrnsteinUhlenbeckProcess(), rTS, bcSet)),
      dyMap_  (FirstDerivativeOp(1, mesher)
                .mult(-process->beta()*mesher->locations(1)))
    {
#if !defined(QL_NO_UBLAS_SUPPORT)
        const Real eta     = process_->eta();
        const Real lambda  = process_->jumpIntensity();
        const Array yInt   = gaussLaguerreIntegration_.x();
        const Array weights= gaussLaguerreIntegration_.weights();
        integroPart_ = SparseMatrix(mesher_->layout()->size(),
                                    mesher_->layout()->size());
        const boost::shared_ptr<FdmLinearOpLayout> layout = mesher_->layout();
        const FdmLinearOpIterator endIter = layout->end();
        Array yLoc(mesher_->layout()->dim()[1]);
        for (FdmLinearOpIterator iter = layout->begin(); iter != endIter;
            ++iter) {
            yLoc[iter.coordinates()[1]] = mesher_->location(iter, 1);
        }
        for (FdmLinearOpIterator iter = layout->begin(); iter != endIter;
            ++iter) {
            const Size diag = iter.index();
            integroPart_(diag, diag) -= lambda;
            const Real y = mesher_->location(iter, 1);
            const Integer yIndex = iter.coordinates()[1];
            for (Size i=0; i < yInt.size(); ++i) {
                const Real weight = std::exp(-yInt[i])*weights[i];
                const Real ys = y + yInt[i]/eta;
                const Integer l = (ys > yLoc.back()) ? yLoc.size()-2
                    : std::upper_bound(yLoc.begin(),
                                       yLoc.end()-1, ys) - yLoc.begin()-1;
                const Real s = (ys-yLoc[l])/(yLoc[l+1]-yLoc[l]);
                integroPart_(diag, layout->neighbourhood(iter, 1, l-yIndex))
                    += weight*lambda*(1-s);
                integroPart_(diag, layout->neighbourhood(iter, 1, l+1-yIndex))
                    += weight*lambda*s;
            }
        }
#endif
    }
Member Function Documentation
Disposable< Array > QuantLib::FdmExtOUJumpOp::apply (const Array & r) const [virtual]
Implements QuantLib::FdmLinearOp.
Definition at line 125 of file fdmextoujumpop.cpp.
References QuantLib::TripleBandLinearOp::apply(), dyMap_, integro(), and ouOp_.
{
        return ouOp_->apply(r) + dyMap_.apply(r) + integro(r);
    }
Disposable< Array > QuantLib::FdmExtOUJumpOp::apply_direction (Size direction, const Array & r) const [virtual]
Implements QuantLib::FdmLinearOpComposite.
Definition at line 133 of file fdmextoujumpop.cpp.
References QuantLib::TripleBandLinearOp::apply(), dyMap_, ouOp_, and QuantLib::Array::size().
{
        if (direction == 0)
            return ouOp_->apply_direction(direction, r);
        else if (direction == 1)
            return dyMap_.apply(r);
        else {
            Array retVal(r.size(), 0.0);
            return retVal;
        }
    }
Disposable< Array > QuantLib::FdmExtOUJumpOp::apply_mixed (const Array & r) const [virtual]
Implements QuantLib::FdmLinearOpComposite.
Definition at line 129 of file fdmextoujumpop.cpp.
References integro().
{
        return  integro(r);
    }
Disposable< Array > QuantLib::FdmExtOUJumpOp::integro (const Array & r) const [private]
Definition at line 232 of file fdmextoujumpop.cpp.
References integroPart_, and QuantLib::prod().
Referenced by apply(), and apply_mixed().
{
        return prod(integroPart_, r);
    }
Disposable< Array > QuantLib::FdmExtOUJumpOp::preconditioner (const Array & r, Real s) const [virtual]
Implements QuantLib::FdmLinearOpComposite.
Definition at line 161 of file fdmextoujumpop.cpp.
References ouOp_.
{
        return ouOp_->solve_splitting(0, r, dt);
    }
void QuantLib::FdmExtOUJumpOp::setTime (Time t1, Time t2) [virtual]
Time \(t1 <= t2\) is required.
Implements QuantLib::FdmLinearOpComposite.
Definition at line 121 of file fdmextoujumpop.cpp.
References ouOp_.
{
        ouOp_->setTime(t1, t2);
    }
Size QuantLib::FdmExtOUJumpOp::size () const [virtual]
Implements QuantLib::FdmLinearOpComposite.
Definition at line 117 of file fdmextoujumpop.cpp.
References mesher_.
{
        return mesher_->layout()->dim().size();;
    }
Disposable< Array > QuantLib::FdmExtOUJumpOp::solve_splitting (Size direction, const Array & r, Real s) const [virtual]
Implements QuantLib::FdmLinearOpComposite.
Definition at line 146 of file fdmextoujumpop.cpp.
References dyMap_, ouOp_, and QuantLib::TripleBandLinearOp::solve_splitting().
{
        if (direction == 0) {
            return ouOp_->solve_splitting(direction, r, a);
        }
        else if (direction == 1) {
            return dyMap_.solve_splitting(r, a, 1.0);
        }
        else {
            Array retVal(r);
            return retVal;
        }
    }
Disposable< SparseMatrix > QuantLib::FdmExtOUJumpOp::toMatrix () const [virtual]
Reimplemented from QuantLib::FdmLinearOp.
Definition at line 236 of file fdmextoujumpop.cpp.
References bcSet_, dyMap_, integroPart_, ouOp_, QL_REQUIRE, and QuantLib::TripleBandLinearOp::toMatrix().
{
        QL_REQUIRE(bcSet_.empty(), "boundary conditions are not supported");
        SparseMatrix retVal = ouOp_->toMatrix()+dyMap_.toMatrix()+integroPart_;
        return retVal;
    }
Member Data Documentation
const FdmBoundaryConditionSet QuantLib::FdmExtOUJumpOp::bcSet_ [private]
Definition at line 75 of file fdmextoujumpop.hpp.
Referenced by toMatrix().
const TripleBandLinearOp QuantLib::FdmExtOUJumpOp::dyMap_ [private]
Definition at line 81 of file fdmextoujumpop.hpp.
Referenced by apply(), apply_direction(), solve_splitting(), and toMatrix().
GaussLaguerreIntegration QuantLib::FdmExtOUJumpOp::gaussLaguerreIntegration_ [private]
Definition at line 76 of file fdmextoujumpop.hpp.
Referenced by FdmExtOUJumpOp().
SparseMatrix QuantLib::FdmExtOUJumpOp::integroPart_ [private]
Definition at line 98 of file fdmextoujumpop.hpp.
Referenced by FdmExtOUJumpOp(), integro(), and toMatrix().
const boost::shared_ptr<FdmMesher> QuantLib::FdmExtOUJumpOp::mesher_ [private]
Definition at line 72 of file fdmextoujumpop.hpp.
Referenced by FdmExtOUJumpOp(), and size().
const boost::shared_ptr<FdmExtendedOrnsteinUhlenbackOp> QuantLib::FdmExtOUJumpOp::ouOp_ [private]
Definition at line 79 of file fdmextoujumpop.hpp.
Referenced by apply(), apply_direction(), preconditioner(), setTime(), solve_splitting(), and toMatrix().
const boost::shared_ptr<ExtOUWithJumpsProcess> QuantLib::FdmExtOUJumpOp::process_ [private]
Definition at line 73 of file fdmextoujumpop.hpp.
Referenced by FdmExtOUJumpOp().
const boost::shared_ptr<YieldTermStructure> QuantLib::FdmExtOUJumpOp::rTS_ [private]
Definition at line 74 of file fdmextoujumpop.hpp.
const Array QuantLib::FdmExtOUJumpOp::x_ [private]
Definition at line 78 of file fdmextoujumpop.hpp.
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/finitedifferences/fdmextoujumpop.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/finitedifferences/fdmextoujumpop.cpp