QuantLib: CurveStatesTest Class Reference
CurveStatesTest Class Reference
#include <curvestates.hpp>
Static Public Member Functions
static void testLMMCurveState ()
static void testCMSwapCurveState ()
static void testCoterminalSwapCurveState ()
static
boost::unit_test_framework::test_suite * suite ()
Detailed Description
Definition at line 29 of file curvestates.hpp.
Member Function Documentation
test_suite * CurveStatesTest::suite () [static]
Definition at line 205 of file curvestates.cpp.
References QUANTLIB_TEST_CASE, and testCMSwapCurveState().
Referenced by init_unit_test_suite().
{
    test_suite* suite = BOOST_TEST_SUITE("Curve States tests");
    //suite->add(QUANTLIB_TEST_CASE(&CurveStatesTest::testLMMCurveState));
    //suite->add(QUANTLIB_TEST_CASE(&CurveStatesTest::testCoterminalSwapCurveState));
    suite->add(QUANTLIB_TEST_CASE(&CurveStatesTest::testCMSwapCurveState));
    return suite;
}
void CurveStatesTest::testCMSwapCurveState () [static]
Definition at line 143 of file curvestates.cpp.
References QuantLib::CMSMMDriftCalculator::compute(), anonymous_namespace{marketmodel.cpp}::rateTimes, QuantLib::CMSwapCurveState::setOnCMSwapRates(), and QuantLib::LMMCurveState::setOnForwardRates().
Referenced by suite().
{
    BOOST_MESSAGE("Testing constant-maturity-swap-market-model curve state...");
    CommonVars vars;
    Size nbRates = vars.todaysForwards.size();
    Size factors = nbRates;
    Matrix pseudo(nbRates, factors, 0.1);
    std::vector<Spread> displacements(nbRates, .0);
    std::vector<Time> rateTimes(nbRates+1);
    std::vector<Time> taus(nbRates, .5);
    std::vector<Rate> forwards(nbRates, 0.0);
    //std::cout << "rate value:"<< std::endl;
    for (Size i = 0; i < forwards.size(); ++i)
        forwards[i] = static_cast<Rate>(i)*.001+.04;
    for (Size i = 0; i < rateTimes.size(); ++i)
        rateTimes[i] = static_cast<Time>(i+1)*.5;
    //BOOST_MESSAGE( << "Rates\nTime\tValue:"<< std::endl;)
    //for (Size i = 0; i < rateTimes.size()-1; ++i){
    //    std::cout << rateTimes[i+1] << "\t"<<io::rate(forwards[i]) << std::endl;
    //}
    Size numeraire = nbRates;
    Size alive = 0;
    Size spanningFwds = 1;
    CMSMMDriftCalculator cmsDriftcalculator(pseudo, displacements, taus,
                                            numeraire, alive, spanningFwds);
    CMSwapCurveState cmsCs(rateTimes, spanningFwds);
    cmsCs.setOnCMSwapRates(forwards);
    std::vector<Real> cmsDrifts(nbRates);
    cmsDriftcalculator.compute(cmsCs,cmsDrifts);
    LMMDriftCalculator lmmDriftcalculator(pseudo, displacements, taus,
                                          numeraire, alive);
    LMMCurveState lmmCs(rateTimes);
    lmmCs.setOnForwardRates(forwards);
    std::vector<Real> lmmDrifts(nbRates);
 /*   std::cout << "drifts:"<< std::endl;
    std::cout << "LMM\t\tCMS"<< std::endl;
    for (Size i = 0; i<nbRates; ++i){
         std::cout << lmmDrifts[i] << "\t\t"<< cmsDrifts[i] << std::endl;
    }*/
//    const std::vector<Rate>& dfs = cs.discountRatios();
    //std::cout << "discounts ratios:"<< std::endl;
    //std::cout << "LMM\tCMS"<< std::endl;
    /*for (Size i = 0; i <nbRates; ++i){
        std::cout << lmmCs.discountRatio(i, nbRates) << "\t"<< cmsCs.discountRatio(i, nbRates) << std::endl;
    }*/
}
void CurveStatesTest::testCoterminalSwapCurveState () [static]
Definition at line 135 of file curvestates.cpp.
{
    BOOST_MESSAGE("Testing coterminal-swap-market-model curve state...");
    CommonVars vars;
}
void CurveStatesTest::testLMMCurveState () [static]
Definition at line 128 of file curvestates.cpp.
{
    BOOST_MESSAGE("Testing Libor-market-model curve state...");
    CommonVars vars;
}
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/curvestates.hpp
/home/deriversatile/QuantLib/QuantLibQt/test-suite/curvestates.cpp