QuantLib: QuantLib::ComplexArray Class Reference
QuantLib::ComplexArray Class Reference
1-D array used in linear algebra.
#include <complexarray.hpp>
Public Types
typedef std::complex< Real > * iterator
typedef const std::complex
< Real > * const_iterator
typedef
boost::reverse_iterator
< iterator > reverse_iterator
typedef
boost::reverse_iterator
< const_iterator > const_reverse_iterator
Public Member Functions
Constructors, destructor, and assignment
ComplexArray (Size size=0)
creates the array with the given dimension
ComplexArray (Size size, std::complex< Real > value)
creates the array and fills it with value
ComplexArray (Size size, std::complex< Real > value, std::complex< Real > increment)
creates the array and fills it according to \(a_{0} = value, a_{i}=a_{i-1}+increment \)
ComplexArray (const ComplexArray &)
ComplexArray (const Disposable< ComplexArray > &)
ComplexArray & operator= (const ComplexArray &)
ComplexArray & operator= (const Disposable< ComplexArray > &)
Vector algebra
v += x and similar operation involving a scalar value are shortcuts for \(\forall i : v_i = v_i + x \)
v *= w and similar operation involving two vectors are shortcuts for \(\forall i : v_i = v_i \times w_i \)
Precondition:
all arrays involved in an algebraic expression must have the same size.
const ComplexArray & operator+= (const ComplexArray &)
const ComplexArray & operator+= (std::complex< Real >)
const ComplexArray & operator-= (const ComplexArray &)
const ComplexArray & operator-= (std::complex< Real >)
const ComplexArray & operator*= (const ComplexArray &)
const ComplexArray & operator*= (std::complex< Real >)
const ComplexArray & operator/= (const ComplexArray &)
const ComplexArray & operator/= (std::complex< Real >)
Element access
std::complex< Real > operator[] (Size) const
read-only
std::complex< Real > at (Size) const
std::complex< Real > front () const
std::complex< Real > back () const
std::complex< Real > & operator[] (Size)
read-write
std::complex< Real > & at (Size)
std::complex< Real > & front ()
std::complex< Real > & back ()
Inspectors
Size size () const
dimension of the array
bool empty () const
whether the array is empty
Iterator access
const_iterator begin () const
iterator begin ()
const_iterator end () const
iterator end ()
const_reverse_iterator rbegin () const
reverse_iterator rbegin ()
const_reverse_iterator rend () const
reverse_iterator rend ()
Utilities
void swap (ComplexArray &)
Private Attributes
boost::scoped_array
< std::complex< Real > > data_
Size n_
Related Functions
(Note that these are not member functions.)
std::complex< Real > DotProduct (const ComplexArray &, const ComplexArray &)
const Disposable< ComplexArray > operator+ (const ComplexArray &v)
const Disposable< ComplexArray > operator- (const ComplexArray &v)
const Disposable< ComplexArray > operator+ (const ComplexArray &, const ComplexArray &)
const Disposable< ComplexArray > operator+ (const ComplexArray &, std::complex< Real >)
const Disposable< ComplexArray > operator+ (std::complex< Real >, const ComplexArray &)
const Disposable< ComplexArray > operator- (const ComplexArray &, const ComplexArray &)
const Disposable< ComplexArray > operator- (const ComplexArray &, std::complex< Real >)
const Disposable< ComplexArray > operator- (std::complex< Real >, const ComplexArray &)
const Disposable< ComplexArray > operator* (const ComplexArray &, const ComplexArray &)
const Disposable< ComplexArray > operator* (const ComplexArray &, std::complex< Real >)
const Disposable< ComplexArray > operator* (std::complex< Real >, const ComplexArray &)
const Disposable< ComplexArray > operator/ (const ComplexArray &, const ComplexArray &)
const Disposable< ComplexArray > operator/ (const ComplexArray &, std::complex< Real >)
const Disposable< ComplexArray > operator/ (std::complex< Real >, const ComplexArray &)
const Disposable< ComplexArray > Abs (const ComplexArray &)
const Disposable< ComplexArray > Sqrt (const ComplexArray &)
const Disposable< ComplexArray > Log (const ComplexArray &)
const Disposable< ComplexArray > Exp (const ComplexArray &)
void swap (ComplexArray &, ComplexArray &)
std::ostream & operator<< (std::ostream &, const ComplexArray &)
Detailed Description
1-D array used in linear algebra.
This class implements the concept of vector as used in linear algebra. As such, it is not meant to be used as a container - std::vector should be used instead.
Test:
construction of arrays is checked in a number of cases
Definition at line 47 of file complexarray.hpp.
Member Typedef Documentation
typedef const std::complex<Real>* QuantLib::ComplexArray::const_iterator
Definition at line 106 of file complexarray.hpp.
typedef boost::reverse_iterator<const_iterator> QuantLib::ComplexArray::const_reverse_iterator
Definition at line 108 of file complexarray.hpp.
typedef std::complex<Real>* QuantLib::ComplexArray::iterator
Definition at line 105 of file complexarray.hpp.
typedef boost::reverse_iterator<iterator> QuantLib::ComplexArray::reverse_iterator
Definition at line 107 of file complexarray.hpp.
Constructor & Destructor Documentation
QuantLib::ComplexArray::ComplexArray (Size size = 0) [inline, explicit]
creates the array with the given dimension
Definition at line 186 of file complexarray.hpp.
    : data_(size ? new std::complex<Real> [size] : (std::complex<Real> *)(0)), n_(size) {}
QuantLib::ComplexArray::ComplexArray (Size size, std::complex< Real > value) [inline]
creates the array and fills it with value
Definition at line 189 of file complexarray.hpp.
References begin(), and end().
    : data_(size ? new std::complex<Real> [size] : (std::complex<Real> *)(0)), n_(size) {
        std::fill(begin(),end(),value);
    }
QuantLib::ComplexArray::ComplexArray (Size size, std::complex< Real > value, std::complex< Real > increment) [inline]
creates the array and fills it according to \(a_{0} = value, a_{i}=a_{i-1}+increment \)
Definition at line 194 of file complexarray.hpp.
References begin(), and end().
    : data_(size ? new std::complex<Real> [size] : (std::complex<Real> *)(0)), n_(size) {
        for (iterator i=begin(); i!=end(); i++,value+=increment)
            *i = value;
    }
QuantLib::ComplexArray::ComplexArray (const ComplexArray & from) [inline]
Definition at line 200 of file complexarray.hpp.
References begin(), and end().
    : data_(from.n_ ? new std::complex<Real> [from.n_] : (std::complex<Real> *)(0)), n_(from.n_) {
        std::copy(from.begin(),from.end(),begin());
    }
QuantLib::ComplexArray::ComplexArray (const Disposable< ComplexArray > & from) [inline]
Definition at line 205 of file complexarray.hpp.
References swap().
    : data_((std::complex<Real> *)(0)), n_(0) {
        swap(const_cast<Disposable<ComplexArray>&>(from));
    }
Member Function Documentation
std::complex< Real > QuantLib::ComplexArray::at (Size i) const [inline]
Definition at line 292 of file complexarray.hpp.
References data_, n_, and QL_REQUIRE.
{
        QL_REQUIRE(i<n_,
                   "index (" << i << ") must be less than " << n_ <<
                   ": array access out of range");
        return data_.get()[i];
    }
std::complex< Real > & QuantLib::ComplexArray::at (Size i) [inline]
Definition at line 322 of file complexarray.hpp.
References data_, n_, and QL_REQUIRE.
{
        QL_REQUIRE(i<n_,
                   "index (" << i << ") must be less than " << n_ <<
                   ": array access out of range");
        return data_.get()[i];
    }
std::complex< Real > QuantLib::ComplexArray::back () const [inline]
Definition at line 306 of file complexarray.hpp.
References data_, n_, and QL_REQUIRE.
Referenced by QuantLib::operator<<().
{
        #if defined(QL_EXTRA_SAFETY_CHECKS)
        QL_REQUIRE(n_>0, "null ComplexArray: array access out of range");
        #endif
        return data_.get()[n_-1];
    }
std::complex< Real > & QuantLib::ComplexArray::back () [inline]
Definition at line 336 of file complexarray.hpp.
References data_, n_, and QL_REQUIRE.
{
        #if defined(QL_EXTRA_SAFETY_CHECKS)
        QL_REQUIRE(n_>0, "null ComplexArray: array access out of range");
        #endif
        return data_.get()[n_-1];
    }
ComplexArray::const_iterator QuantLib::ComplexArray::begin () const [inline]
Definition at line 351 of file complexarray.hpp.
References data_.
Referenced by ComplexArray(), QuantLib::operator*(), operator*=(), QuantLib::operator+(), operator+=(), QuantLib::operator-(), operator-=(), QuantLib::operator/(), operator/=(), and rend().
{
        return data_.get();
    }
ComplexArray::iterator QuantLib::ComplexArray::begin () [inline]
Definition at line 355 of file complexarray.hpp.
References data_.
{
        return data_.get();
    }
bool QuantLib::ComplexArray::empty () const [inline]
whether the array is empty
Definition at line 347 of file complexarray.hpp.
References n_.
Referenced by QuantLib::operator<<().
{
        return n_ == 0;
    }
ComplexArray::const_iterator QuantLib::ComplexArray::end () const [inline]
Definition at line 359 of file complexarray.hpp.
References data_, and n_.
Referenced by ComplexArray(), QuantLib::operator*(), operator*=(), QuantLib::operator+(), operator+=(), QuantLib::operator-(), operator-=(), QuantLib::operator/(), operator/=(), and rbegin().
{
        return data_.get()+n_;
    }
ComplexArray::iterator QuantLib::ComplexArray::end () [inline]
Definition at line 363 of file complexarray.hpp.
References data_, and n_.
{
        return data_.get()+n_;
    }
std::complex< Real > QuantLib::ComplexArray::front () const [inline]
Definition at line 299 of file complexarray.hpp.
References data_, n_, and QL_REQUIRE.
{
        #if defined(QL_EXTRA_SAFETY_CHECKS)
        QL_REQUIRE(n_>0, "null ComplexArray: array access out of range");
        #endif
        return data_.get()[0];
    }
std::complex< Real > & QuantLib::ComplexArray::front () [inline]
Definition at line 329 of file complexarray.hpp.
References data_, n_, and QL_REQUIRE.
{
        #if defined(QL_EXTRA_SAFETY_CHECKS)
        QL_REQUIRE(n_>0, "null ComplexArray: array access out of range");
        #endif
        return data_.get()[0];
    }
const ComplexArray & QuantLib::ComplexArray::operator*= (const ComplexArray & v) [inline]
Definition at line 253 of file complexarray.hpp.
References begin(), end(), n_, and QL_REQUIRE.
{
        QL_REQUIRE(n_ == v.n_,
                   "arrays with different sizes (" << n_ << ", "
                   << v.n_ << ") cannot be multiplied");
        std::transform(begin(),end(),v.begin(),begin(),
                       std::multiplies<std::complex<Real> >());
        return *this;
    }
const ComplexArray & QuantLib::ComplexArray::operator*= (std::complex< Real > x) [inline]
Definition at line 262 of file complexarray.hpp.
References begin(), and end().
{
        std::transform(begin(),end(),begin(),
                       std::bind2nd(std::multiplies<std::complex<Real> >(),x));
        return *this;
    }
const ComplexArray & QuantLib::ComplexArray::operator+= (const ComplexArray & v) [inline]
Definition at line 222 of file complexarray.hpp.
References begin(), end(), n_, and QL_REQUIRE.
{
        QL_REQUIRE(n_ == v.n_,
                   "arrays with different sizes (" << n_ << ", "
                   << v.n_ << ") cannot be added");
        std::transform(begin(),end(),v.begin(),begin(),
                       std::plus<std::complex<Real> >());
        return *this;
    }
const ComplexArray & QuantLib::ComplexArray::operator+= (std::complex< Real > x) [inline]
Definition at line 232 of file complexarray.hpp.
References begin(), and end().
{
        std::transform(begin(),end(),begin(),
                       std::bind2nd(std::plus<std::complex<Real> >(),x));
        return *this;
    }
const ComplexArray & QuantLib::ComplexArray::operator-= (const ComplexArray & v) [inline]
Definition at line 238 of file complexarray.hpp.
References begin(), end(), n_, and QL_REQUIRE.
{
        QL_REQUIRE(n_ == v.n_,
                   "arrays with different sizes (" << n_ << ", "
                   << v.n_ << ") cannot be subtracted");
        std::transform(begin(),end(),v.begin(),begin(),
                       std::minus<std::complex<Real> >());
        return *this;
    }
const ComplexArray & QuantLib::ComplexArray::operator-= (std::complex< Real > x) [inline]
Definition at line 247 of file complexarray.hpp.
References begin(), and end().
{
        std::transform(begin(),end(),begin(),
                       std::bind2nd(std::minus<std::complex<Real> >(),x));
        return *this;
    }
const ComplexArray & QuantLib::ComplexArray::operator/= (const ComplexArray & v) [inline]
Definition at line 268 of file complexarray.hpp.
References begin(), end(), n_, and QL_REQUIRE.
{
        QL_REQUIRE(n_ == v.n_,
                   "arrays with different sizes (" << n_ << ", "
                   << v.n_ << ") cannot be divided");
        std::transform(begin(),end(),v.begin(),begin(),
                       std::divides<std::complex<Real> >());
        return *this;
    }
const ComplexArray & QuantLib::ComplexArray::operator/= (std::complex< Real > x) [inline]
Definition at line 277 of file complexarray.hpp.
References begin(), and end().
{
        std::transform(begin(),end(),begin(),
                       std::bind2nd(std::divides<std::complex<Real> >(),x));
        return *this;
    }
ComplexArray & QuantLib::ComplexArray::operator= (const ComplexArray & from) [inline]
Definition at line 210 of file complexarray.hpp.
References swap().
{
        // strong guarantee
        ComplexArray temp(from);
        swap(temp);
        return *this;
    }
ComplexArray & QuantLib::ComplexArray::operator= (const Disposable< ComplexArray > & from) [inline]
Definition at line 217 of file complexarray.hpp.
References swap().
{
        swap(const_cast<Disposable<ComplexArray>&>(from));
        return *this;
    }
std::complex< Real > QuantLib::ComplexArray::operator[] (Size i) const [inline]
read-only
Definition at line 283 of file complexarray.hpp.
References data_, n_, and QL_REQUIRE.
{
        #if defined(QL_EXTRA_SAFETY_CHECKS)
        QL_REQUIRE(i<n_,
                   "index (" << i << ") must be less than " << n_ <<
                   ": array access out of range");
        #endif
        return data_.get()[i];
    }
std::complex< Real > & QuantLib::ComplexArray::operator[] (Size i) [inline]
read-write
Definition at line 313 of file complexarray.hpp.
References data_, n_, and QL_REQUIRE.
{
        #if defined(QL_EXTRA_SAFETY_CHECKS)
        QL_REQUIRE(i<n_,
                   "index (" << i << ") must be less than " << n_ <<
                   ": array access out of range");
        #endif
        return data_.get()[i];
    }
ComplexArray::const_reverse_iterator QuantLib::ComplexArray::rbegin () const [inline]
Definition at line 367 of file complexarray.hpp.
References end().
{
        return const_reverse_iterator(end());
    }
ComplexArray::reverse_iterator QuantLib::ComplexArray::rbegin () [inline]
Definition at line 371 of file complexarray.hpp.
References end().
{
        return reverse_iterator(end());
    }
ComplexArray::const_reverse_iterator QuantLib::ComplexArray::rend () const [inline]
Definition at line 375 of file complexarray.hpp.
References begin().
{
        return const_reverse_iterator(begin());
    }
ComplexArray::reverse_iterator QuantLib::ComplexArray::rend () [inline]
Definition at line 379 of file complexarray.hpp.
References begin().
{
        return reverse_iterator(begin());
    }
Size QuantLib::ComplexArray::size () const [inline]
dimension of the array
Definition at line 343 of file complexarray.hpp.
References n_.
Referenced by QuantLib::operator*(), QuantLib::operator+(), QuantLib::operator-(), QuantLib::operator/(), and QuantLib::operator<<().
{
        return n_;
    }
void QuantLib::ComplexArray::swap (ComplexArray & from) [inline]
Definition at line 383 of file complexarray.hpp.
References data_, and n_.
Referenced by ComplexArray(), operator=(), and QuantLib::swap().
{
        using std::swap;
        data_.swap(from.data_);
        swap(n_,from.n_);
    }
Friends And Related Function Documentation
const Disposable< ComplexArray > Abs (const ComplexArray &) [related]
std::complex< Real > DotProduct (const ComplexArray & , const ComplexArray &) [related]
const Disposable< ComplexArray > Exp (const ComplexArray &) [related]
const Disposable< ComplexArray > Log (const ComplexArray &) [related]
const Disposable< ComplexArray > operator* (const ComplexArray & , const ComplexArray &) [related]
Definition at line 467 of file complexarray.hpp.
{
        QL_REQUIRE(v1.size() == v2.size(),
                   "arrays with different sizes (" << v1.size() << ", "
                   << v2.size() << ") cannot be multiplied");
        ComplexArray result(v1.size());
        std::transform(v1.begin(),v1.end(),v2.begin(),result.begin(),
                       std::multiplies<std::complex<Real> >());
        return result;
    }
const Disposable< ComplexArray > operator* (const ComplexArray & , std::complex< Real >) [related]
Definition at line 478 of file complexarray.hpp.
{
        ComplexArray result(v1.size());
        std::transform(v1.begin(),v1.end(),result.begin(),
                       std::bind2nd(std::multiplies<std::complex<Real> >(),a));
        return result;
    }
const Disposable< ComplexArray > operator* (std::complex< Real > , const ComplexArray &) [related]
Definition at line 485 of file complexarray.hpp.
{
        ComplexArray result(v2.size());
        std::transform(v2.begin(),v2.end(),result.begin(),
                       std::bind1st(std::multiplies<std::complex<Real> >(),a));
        return result;
    }
const Disposable< ComplexArray > operator+ (const ComplexArray & v) [related]
Definition at line 402 of file complexarray.hpp.
{
        ComplexArray result = v;
        return result;
    }
const Disposable< ComplexArray > operator+ (const ComplexArray & , const ComplexArray &) [related]
Definition at line 417 of file complexarray.hpp.
{
        QL_REQUIRE(v1.size() == v2.size(),
                   "arrays with different sizes (" << v1.size() << ", "
                   << v2.size() << ") cannot be added");
        ComplexArray result(v1.size());
        std::transform(v1.begin(),v1.end(),v2.begin(),result.begin(),
                       std::plus<std::complex<Real> >());
        return result;
    }
const Disposable< ComplexArray > operator+ (const ComplexArray & , std::complex< Real >) [related]
Definition at line 428 of file complexarray.hpp.
{
        ComplexArray result(v1.size());
        std::transform(v1.begin(),v1.end(),result.begin(),
                       std::bind2nd(std::plus<std::complex<Real> >(),a));
        return result;
    }
const Disposable< ComplexArray > operator+ (std::complex< Real > , const ComplexArray &) [related]
Definition at line 435 of file complexarray.hpp.
{
        ComplexArray result(v2.size());
        std::transform(v2.begin(),v2.end(),result.begin(),
                       std::bind1st(std::plus<std::complex<Real> >(),a));
        return result;
    }
const Disposable< ComplexArray > operator- (const ComplexArray & v) [related]
Definition at line 407 of file complexarray.hpp.
{
        ComplexArray result(v.size());
        std::transform(v.begin(),v.end(),result.begin(),
                       std::negate<std::complex<Real> >());
        return result;
    }
const Disposable< ComplexArray > operator- (const ComplexArray & , const ComplexArray &) [related]
Definition at line 442 of file complexarray.hpp.
{
        QL_REQUIRE(v1.size() == v2.size(),
                   "arrays with different sizes (" << v1.size() << ", "
                   << v2.size() << ") cannot be subtracted");
        ComplexArray result(v1.size());
        std::transform(v1.begin(),v1.end(),v2.begin(),result.begin(),
                       std::minus<std::complex<Real> >());
        return result;
    }
const Disposable< ComplexArray > operator- (const ComplexArray & , std::complex< Real >) [related]
Definition at line 453 of file complexarray.hpp.
{
        ComplexArray result(v1.size());
        std::transform(v1.begin(),v1.end(),result.begin(),
                       std::bind2nd(std::minus<std::complex<Real> >(),a));
        return result;
    }
const Disposable< ComplexArray > operator- (std::complex< Real > , const ComplexArray &) [related]
Definition at line 460 of file complexarray.hpp.
{
        ComplexArray result(v2.size());
        std::transform(v2.begin(),v2.end(),result.begin(),
                       std::bind1st(std::minus<std::complex<Real> >(),a));
        return result;
    }
const Disposable< ComplexArray > operator/ (const ComplexArray & , const ComplexArray &) [related]
Definition at line 492 of file complexarray.hpp.
{
        QL_REQUIRE(v1.size() == v2.size(),
                   "arrays with different sizes (" << v1.size() << ", "
                   << v2.size() << ") cannot be divided");
        ComplexArray result(v1.size());
        std::transform(v1.begin(),v1.end(),v2.begin(),result.begin(),
                       std::divides<std::complex<Real> >());
        return result;
    }
const Disposable< ComplexArray > operator/ (const ComplexArray & , std::complex< Real >) [related]
Definition at line 503 of file complexarray.hpp.
{
        ComplexArray result(v1.size());
        std::transform(v1.begin(),v1.end(),result.begin(),
                       std::bind2nd(std::divides<std::complex<Real> >(),a));
        return result;
    }
const Disposable< ComplexArray > operator/ (std::complex< Real > , const ComplexArray &) [related]
Definition at line 510 of file complexarray.hpp.
{
        ComplexArray result(v2.size());
        std::transform(v2.begin(),v2.end(),result.begin(),
                       std::bind1st(std::divides<std::complex<Real> >(),a));
        return result;
    }
std::ostream & operator<< (std::ostream & , const ComplexArray &) [related]
Definition at line 551 of file complexarray.hpp.
{
        std::streamsize width = out.width();
        out << "[ ";
        if (!a.empty()) {
            for (Size n=0; n<a.size()-1; ++n)
                out << std::setw(width) << a[n] << "; ";
            out << std::setw(width) << a.back();
        }
        out << " ]";
        return out;
    }
const Disposable< ComplexArray > Sqrt (const ComplexArray &) [related]
void swap (ComplexArray & , ComplexArray &) [related]
Definition at line 547 of file complexarray.hpp.
{
        v.swap(w);
    }
Member Data Documentation
boost::scoped_array<std::complex<Real> > QuantLib::ComplexArray::data_ [private]
Definition at line 126 of file complexarray.hpp.
Referenced by at(), back(), begin(), end(), front(), operator[](), and swap().
Size QuantLib::ComplexArray::n_ [private]
Definition at line 127 of file complexarray.hpp.
Referenced by at(), back(), empty(), end(), front(), operator*=(), operator+=(), operator-=(), operator/=(), operator[](), size(), and swap().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/math/complexarray.hpp