QuantLib: QuantLib::LossDistHomogeneous Class Reference
QuantLib::LossDistHomogeneous Class Reference
Loss Distribution for Homogeneous Pool.
#include <lossdistribution.hpp>
Public Member Functions
LossDistHomogeneous (Size nBuckets, Real maximum, Real epsilon=1e-6)
Distribution operator() (Real volume, const std::vector< Real > &probabilities) const
Distribution operator() (const std::vector< Real > &volumes, const std::vector< Real > &probabilities) const
Size buckets () const
Real maximum () const
Size size () const
Real volume () const
std::vector< Real > probability () const
std::vector< Real > excessProbability () const
Private Attributes
Size nBuckets_
Real maximum_
Real epsilon_
Size n_
Real volume_
std::vector< Real > probability_
std::vector< Real > excessProbability_
Detailed Description
Loss Distribution for Homogeneous Pool.
Loss Distribution for Homogeneous Pool
Loss distribution for equal volumes but varying probabilities of default.
The method builds the exact loss distribution for a homogeneous pool of underlyings iteratively by computing the convolution of the given loss distribution with the "loss distribution" of an additional credit following
Xiaofong Ma, "Numerical Methods for the Valuation of Synthetic Collateralized Debt Obligations", PhD Thesis, Graduate Department of Computer Science, University of Toronto, 2007 http://www.cs.toronto.edu/pub/reports/na/ma-07-phd.pdf (formula 2.1)
avoiding numerical instability of the algorithm by
John Hull and Alan White, "Valuation of a CDO and nth to default CDS without Monte Carlo simulation", Journal of Derivatives 12, 2, 2004
Definition at line 146 of file lossdistribution.hpp.
Constructor & Destructor Documentation
QuantLib::LossDistHomogeneous::LossDistHomogeneous (Size nBuckets, Real maximum, Real epsilon = 1e-6) [inline]
Definition at line 148 of file lossdistribution.hpp.
            : nBuckets_(nBuckets), maximum_(maximum), epsilon_(epsilon),
              n_(0), volume_(0.0) {}
Member Function Documentation
Size QuantLib::LossDistHomogeneous::buckets () const [inline, virtual]
Implements QuantLib::LossDist.
Definition at line 155 of file lossdistribution.hpp.
References nBuckets_.
{ return nBuckets_; }
std::vector<Real> QuantLib::LossDistHomogeneous::excessProbability () const [inline]
Definition at line 160 of file lossdistribution.hpp.
References excessProbability_.
{ return excessProbability_; }
Real QuantLib::LossDistHomogeneous::maximum () const [inline, virtual]
Implements QuantLib::LossDist.
Definition at line 156 of file lossdistribution.hpp.
References maximum_.
{ return maximum_; }
Distribution QuantLib::LossDistHomogeneous::operator() (Real volume, const std::vector< Real > & probabilities) const
Definition at line 182 of file lossdistribution.cpp.
References QuantLib::Distribution::addAverage(), QuantLib::Distribution::addDensity(), QuantLib::Distribution::dx(), QuantLib::Distribution::locate(), and QuantLib::Distribution::normalize().
{
    //--------------------------------------------------------------------------
        volume_ = volume;
        n_ = p.size();
        probability_.clear();
        probability_.resize(n_+1, 0.0);
        vector<Real> prev;
        probability_[0] = 1.0;
        for (Size k = 0; k < n_; k++) {
            prev = probability_;
            probability_[0] = prev[0] * (1.0 - p[k]);
            for (Size i = 1; i <= k; i++)
                probability_[i] = prev[i-1] * p[k] + prev[i] * (1.0 - p[k]);
            probability_[k+1] = prev[k] * p[k];
        }
        excessProbability_.clear();
        excessProbability_.resize(n_+1, 0.0);
        excessProbability_[n_] = probability_[n_];
        for (int k = n_ - 1; k >= 0; k--)
            excessProbability_[k] = excessProbability_[k+1] + probability_[k];
        Distribution dist (nBuckets_, 0.0, maximum_);
        for (Size i = 0; i <= n_; i++) {
            if (volume * i <= maximum_) {
                Size bucket = dist.locate(volume * i);
                dist.addDensity (bucket, probability_[i] / dist.dx(bucket));
                dist.addAverage (bucket, volume*i);
            }
        }
        dist.normalize();
        return dist;
    }
Distribution QuantLib::LossDistHomogeneous::operator() (const std::vector< Real > & volumes, const std::vector< Real > & probabilities) const [virtual]
Implements QuantLib::LossDist.
Definition at line 220 of file lossdistribution.cpp.
{
    //--------------------------------------------------------------------------
        return operator()(nominals[0], probabilities);
    }
std::vector<Real> QuantLib::LossDistHomogeneous::probability () const [inline]
Definition at line 159 of file lossdistribution.hpp.
References probability_.
{ return probability_; }
Size QuantLib::LossDistHomogeneous::size () const [inline]
Definition at line 157 of file lossdistribution.hpp.
References n_.
{ return n_; }
Real QuantLib::LossDistHomogeneous::volume () const [inline]
Definition at line 158 of file lossdistribution.hpp.
References volume_.
{ return volume_; }
Member Data Documentation
Real QuantLib::LossDistHomogeneous::epsilon_ [private]
Definition at line 164 of file lossdistribution.hpp.
std::vector<Real> QuantLib::LossDistHomogeneous::excessProbability_ [mutable, private]
Definition at line 168 of file lossdistribution.hpp.
Referenced by excessProbability().
Real QuantLib::LossDistHomogeneous::maximum_ [private]
Definition at line 163 of file lossdistribution.hpp.
Referenced by maximum().
Size QuantLib::LossDistHomogeneous::n_ [mutable, private]
Definition at line 165 of file lossdistribution.hpp.
Referenced by size().
Size QuantLib::LossDistHomogeneous::nBuckets_ [private]
Definition at line 162 of file lossdistribution.hpp.
Referenced by buckets().
std::vector<Real> QuantLib::LossDistHomogeneous::probability_ [mutable, private]
Definition at line 167 of file lossdistribution.hpp.
Referenced by probability().
Real QuantLib::LossDistHomogeneous::volume_ [mutable, private]
Definition at line 166 of file lossdistribution.hpp.
Referenced by volume().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/lossdistribution.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/lossdistribution.cpp