QuantLib: QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel > Class Template Reference
QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel > Class Template Reference
#include <kernelinterpolation2d.hpp>
Public Member Functions
KernelInterpolation2DImpl (const I1 &xBegin, const I1 &xEnd, const I2 &yBegin, const I2 &yEnd, const M &zData, const Kernel &kernel)
void calculate ()
Real value (Real x1, Real x2) const
void setInverseResultPrecision (Real invPrec)
Private Member Functions
Real kernelAbs (const Array &X, const Array &Y) const
Real vecNorm (const Array &X) const
Real gammaFunc (const Array &X) const
void updateAlphaVec ()
Private Attributes
Size xSize_
Size ySize_
Size xySize_
Real invPrec_
Array alphaVec_
Array yVec_
Matrix M_
Kernel kernel_
Detailed Description
template<class I1, class I2, class M, class Kernel>
class QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >
Definition at line 55 of file kernelinterpolation2d.hpp.
Constructor & Destructor Documentation
template<class I1 , class I2 , class M , class Kernel > QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::KernelInterpolation2DImpl (const I1 & xBegin, const I1 & xEnd, const I2 & yBegin, const I2 & yEnd, const M & zData, const Kernel & kernel) [inline]
Definition at line 59 of file kernelinterpolation2d.hpp.
References QL_REQUIRE, QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::xSize_, and QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::ySize_.
            : Interpolation2D::templateImpl<I1,I2,M>(xBegin, xEnd,
                                                     yBegin, yEnd, zData),
              xSize_(Size(xEnd-xBegin)), ySize_(Size(yEnd-yBegin)),
              xySize_(xSize_*ySize_), invPrec_(1.0e-10),
              alphaVec_(xySize_), yVec_(xySize_),
              M_(xySize_,xySize_),
              kernel_(kernel) {
                QL_REQUIRE(zData.rows()==xSize_,
                           "Z value matrix has wrong number of rows");
                QL_REQUIRE(zData.columns()==ySize_,
                           "Z value matrix has wrong number of columns");
            }
Member Function Documentation
template<class I1 , class I2 , class M , class Kernel > void QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::calculate () [inline, virtual]
Implements QuantLib::Interpolation2D::Impl.
Definition at line 77 of file kernelinterpolation2d.hpp.
References QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::updateAlphaVec().
{
                updateAlphaVec();
            }
template<class I1 , class I2 , class M , class Kernel > Real QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::gammaFunc (const Array & X) const [inline, private]
Definition at line 120 of file kernelinterpolation2d.hpp.
References QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::kernelAbs(), QuantLib::Array::size(), QuantLib::Interpolation2D::templateImpl< I1, I2, M >::xBegin_, QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::xSize_, QuantLib::Interpolation2D::templateImpl< I1, I2, M >::yBegin_, and QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::ySize_.
Referenced by QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::updateAlphaVec(), and QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::value().
{
                Real res=0.0;
                Array Xn(X.size());
                for(Size j=0; j< ySize_;++j){
                    for(Size i=0; i< xSize_;++i){
                        Xn[0]=this->xBegin_[i];
                        Xn[1]=this->yBegin_[j];
                        res+=kernelAbs(X,Xn);
                    }
                }
                return res;
            }
template<class I1 , class I2 , class M , class Kernel > Real QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::kernelAbs (const Array & X, const Array & Y) const [inline, private]
Definition at line 112 of file kernelinterpolation2d.hpp.
References QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::kernel_, and QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::vecNorm().
Referenced by QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::gammaFunc(), QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::updateAlphaVec(), and QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::value().
{
                return kernel_(vecNorm(X-Y));
            }
template<class I1 , class I2 , class M , class Kernel > void QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::setInverseResultPrecision (Real invPrec) [inline]
Definition at line 105 of file kernelinterpolation2d.hpp.
References QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::invPrec_.
{
                invPrec_=invPrec;
            }
template<class I1 , class I2 , class M , class Kernel > void QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::updateAlphaVec () [inline, private]
Definition at line 136 of file kernelinterpolation2d.hpp.
References QuantLib::Abs(), QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::alphaVec_, QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::gammaFunc(), QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::invPrec_, QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::kernelAbs(), QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::M_, QL_REQUIRE, QuantLib::qrSolve(), QuantLib::Array::size(), QuantLib::Interpolation2D::templateImpl< I1, I2, M >::xBegin_, QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::xSize_, QuantLib::Interpolation2D::templateImpl< I1, I2, M >::yBegin_, QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::ySize_, QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::yVec_, and QuantLib::Interpolation2D::templateImpl< I1, I2, M >::zData_.
Referenced by QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::calculate().
{
                // Function calculates the alpha vector with given
                // fixed pillars+values
                Array Xk(2),Xn(2);
                Size rowCnt=0,colCnt=0;
                Real tmpVar=0.0;
                // write y-vector and M-Matrix
                for(Size j=0; j< ySize_;++j){
                    for(Size i=0; i< xSize_;++i){
                        yVec_[rowCnt]=this->zData_[i][j];
                        // calculate X_k
                        Xk[0]=this->xBegin_[i];
                        Xk[1]=this->yBegin_[j];
                        tmpVar=1/gammaFunc(Xk);
                        colCnt=0;
                        for(Size jM=0; jM< ySize_;++jM){
                            for(Size iM=0; iM< xSize_;++iM){
                                Xn[0]=this->xBegin_[iM];
                                Xn[1]=this->yBegin_[jM];
                                M_[rowCnt][colCnt]=kernelAbs(Xk,Xn)*tmpVar;
                                colCnt++; // increase column counter
                            }// end iM
                        }// end jM
                        rowCnt++; // increase row counter
                    } // end i
                }// end j
                alphaVec_=qrSolve(M_, yVec_);
                // check if inversion worked up to a reasonable precision.
                // I've chosen not to check determinant(M_)!=0 before solving
                Array diffVec=Abs(M_*alphaVec_ - yVec_);
                for (Size i=0; i<diffVec.size(); ++i) {
                    QL_REQUIRE(diffVec[i]<invPrec_,
                               "inversion failed in 2d kernel interpolation");
                }
            }
template<class I1 , class I2 , class M , class Kernel > Real QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::value (Real x1, Real x2) const [inline, virtual]
Implements QuantLib::Interpolation2D::Impl.
Definition at line 81 of file kernelinterpolation2d.hpp.
References QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::alphaVec_, QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::gammaFunc(), QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::kernelAbs(), QuantLib::x1, QuantLib::x2, QuantLib::Interpolation2D::templateImpl< I1, I2, M >::xBegin_, QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::xSize_, QuantLib::Interpolation2D::templateImpl< I1, I2, M >::yBegin_, and QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::ySize_.
{
                Real res=0.0;
                Array X(2),Xn(2);
                X[0]=x1;X[1]=x2;
                Size cnt=0; // counter
                for( Size j=0; j< ySize_;++j){
                    for( Size i=0; i< xSize_;++i){
                        Xn[0]=this->xBegin_[i];
                        Xn[1]=this->yBegin_[j];
                        res+=alphaVec_[cnt]*kernelAbs(X,Xn);
                        cnt++;
                    }
                }
                return res/gammaFunc(X);
            }
template<class I1 , class I2 , class M , class Kernel > Real QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::vecNorm (const Array & X) const [inline, private]
Definition at line 116 of file kernelinterpolation2d.hpp.
References QuantLib::DotProduct().
Referenced by QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::kernelAbs().
{
                return std::sqrt(DotProduct(X,X));
            }
Member Data Documentation
template<class I1 , class I2 , class M , class Kernel > Array QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::alphaVec_ [private]
Definition at line 185 of file kernelinterpolation2d.hpp.
Referenced by QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::updateAlphaVec(), and QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::value().
template<class I1 , class I2 , class M , class Kernel > Real QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::invPrec_ [private]
Definition at line 184 of file kernelinterpolation2d.hpp.
Referenced by QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::setInverseResultPrecision(), and QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::updateAlphaVec().
template<class I1 , class I2 , class M , class Kernel > Kernel QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::kernel_ [private]
Definition at line 187 of file kernelinterpolation2d.hpp.
Referenced by QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::kernelAbs().
template<class I1 , class I2 , class M , class Kernel > Matrix QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::M_ [private]
Definition at line 186 of file kernelinterpolation2d.hpp.
Referenced by QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::updateAlphaVec().
template<class I1 , class I2 , class M , class Kernel > Size QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::xSize_ [private]
Definition at line 183 of file kernelinterpolation2d.hpp.
Referenced by QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::gammaFunc(), QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::KernelInterpolation2DImpl(), QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::updateAlphaVec(), and QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::value().
template<class I1 , class I2 , class M , class Kernel > Size QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::xySize_ [private]
Definition at line 183 of file kernelinterpolation2d.hpp.
template<class I1 , class I2 , class M , class Kernel > Size QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::ySize_ [private]
Definition at line 183 of file kernelinterpolation2d.hpp.
Referenced by QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::gammaFunc(), QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::KernelInterpolation2DImpl(), QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::updateAlphaVec(), and QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::value().
template<class I1 , class I2 , class M , class Kernel > Array QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::yVec_ [private]
Definition at line 185 of file kernelinterpolation2d.hpp.
Referenced by QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::updateAlphaVec().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/interpolations/kernelinterpolation2d.hpp