QuantLib: QuantLib::BondHelper Class Reference
QuantLib::BondHelper Class Reference
fixed-coupon bond helper
#include <bondhelpers.hpp>
Public Member Functions
BondHelper (const Handle< Quote > &cleanPrice, const boost::shared_ptr< Bond > &bond)
RateHelper interface
Real impliedQuote () const
void setTermStructure (YieldTermStructure *)
additional inspectors
boost::shared_ptr< Bond > bond () const
Visitability
void accept (AcyclicVisitor &)
Protected Attributes
boost::shared_ptr< Bond > bond_
RelinkableHandle
< YieldTermStructure > termStructureHandle_
Detailed Description
fixed-coupon bond helper
Warning:
This class assumes that the reference date does not change between calls of setTermStructure().
Definition at line 38 of file bondhelpers.hpp.
Constructor & Destructor Documentation
QuantLib::BondHelper::BondHelper (const Handle< Quote > & cleanPrice, const boost::shared_ptr< Bond > & bond)
Warning:
Setting a pricing engine to the passed bond from external code will cause the bootstrap to fail or to give wrong results. It is advised to discard the bond after creating the helper, so that the helper has sole ownership of it.
Definition at line 33 of file bondhelpers.cpp.
References bond_, QuantLib::BootstrapHelper< TS >::earliestDate_, QuantLib::BootstrapHelper< TS >::latestDate_, and termStructureHandle_.
    : RateHelper(cleanPrice), bond_(new Bond(*bond)) {
        // the bond's last cashflow date, which can be later than
        // bond's maturity date because of adjustment
        latestDate_ = bond_->cashflows().back()->date();
        earliestDate_ = bond_->nextCashFlowDate();
        boost::shared_ptr<PricingEngine> bondEngine(new
            DiscountingBondEngine(termStructureHandle_));
        bond_->setPricingEngine(bondEngine);
    }
Member Function Documentation
void QuantLib::BondHelper::accept (AcyclicVisitor & v) [virtual]
Reimplemented from QuantLib::BootstrapHelper< TS >.
Reimplemented in QuantLib::FixedRateBondHelper.
Definition at line 63 of file bondhelpers.cpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Visitor< T >::visit().
{
        Visitor<BondHelper>* v1 =
            dynamic_cast<Visitor<BondHelper>*>(&v);
        if (v1 != 0)
            v1->visit(*this);
        else
            BootstrapHelper<YieldTermStructure>::accept(v);
    }
boost::shared_ptr< Bond > QuantLib::BondHelper::bond () const [inline]
Definition at line 92 of file bondhelpers.hpp.
References bond_.
{
        return bond_;
    }
Real QuantLib::BondHelper::impliedQuote () const [virtual]
Implements QuantLib::BootstrapHelper< TS >.
Definition at line 56 of file bondhelpers.cpp.
References bond_, QL_REQUIRE, and QuantLib::BootstrapHelper< TS >::termStructure_.
{
        QL_REQUIRE(termStructure_ != 0, "term structure not set");
        // we didn't register as observers - force calculation
        bond_->recalculate();
        return bond_->cleanPrice();
    }
void QuantLib::BondHelper::setTermStructure (YieldTermStructure * t)
Definition at line 47 of file bondhelpers.cpp.
References QuantLib::RelinkableHandle< T >::linkTo(), QuantLib::anonymous_namespace{riskyassetswap.cpp}::no_deletion(), and termStructureHandle_.
{
        // do not set the relinkable handle as an observer -
        // force recalculation when needed
        termStructureHandle_.linkTo(
                 boost::shared_ptr<YieldTermStructure>(t,no_deletion), false);
        BootstrapHelper<YieldTermStructure>::setTermStructure(t);
    }
Member Data Documentation
boost::shared_ptr<Bond> QuantLib::BondHelper::bond_ [protected]
Definition at line 62 of file bondhelpers.hpp.
Referenced by bond(), BondHelper(), and impliedQuote().
RelinkableHandle<YieldTermStructure> QuantLib::BondHelper::termStructureHandle_ [protected]
Definition at line 63 of file bondhelpers.hpp.
Referenced by BondHelper(), and setTermStructure().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/yield/bondhelpers.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/yield/bondhelpers.cpp