QuantLib: QuantLib::Matrix Class Reference
QuantLib::Matrix Class Reference
Matrix used in linear algebra.
#include <matrix.hpp>
Public Types
typedef Real * iterator
typedef const Real * const_iterator
typedef
boost::reverse_iterator
< iterator > reverse_iterator
typedef
boost::reverse_iterator
< const_iterator > const_reverse_iterator
typedef Real * row_iterator
typedef const Real * const_row_iterator
typedef
boost::reverse_iterator
< row_iterator > reverse_row_iterator
typedef
boost::reverse_iterator
< const_row_iterator > const_reverse_row_iterator
typedef step_iterator< iterator > column_iterator
typedef step_iterator
< const_iterator > const_column_iterator
typedef
boost::reverse_iterator
< column_iterator > reverse_column_iterator
typedef
boost::reverse_iterator
< const_column_iterator > const_reverse_column_iterator
Public Member Functions
Constructors, destructor, and assignment
Matrix ()
creates a null matrix
Matrix (Size rows, Size columns)
creates a matrix with the given dimensions
Matrix (Size rows, Size columns, Real value)
creates the matrix and fills it with value
Matrix (const Matrix &)
Matrix (const Disposable< Matrix > &)
Matrix & operator= (const Matrix &)
Matrix & operator= (const Disposable< Matrix > &)
Algebraic operators
const Matrix & operator+= (const Matrix &)
const Matrix & operator-= (const Matrix &)
const Matrix & operator*= (Real)
const Matrix & operator/= (Real)
Iterator access
const_iterator begin () const
iterator begin ()
const_iterator end () const
iterator end ()
const_reverse_iterator rbegin () const
reverse_iterator rbegin ()
const_reverse_iterator rend () const
reverse_iterator rend ()
const_row_iterator row_begin (Size i) const
row_iterator row_begin (Size i)
const_row_iterator row_end (Size i) const
row_iterator row_end (Size i)
const_reverse_row_iterator row_rbegin (Size i) const
reverse_row_iterator row_rbegin (Size i)
const_reverse_row_iterator row_rend (Size i) const
reverse_row_iterator row_rend (Size i)
const_column_iterator column_begin (Size i) const
column_iterator column_begin (Size i)
const_column_iterator column_end (Size i) const
column_iterator column_end (Size i)
const_reverse_column_iterator column_rbegin (Size i) const
reverse_column_iterator column_rbegin (Size i)
const_reverse_column_iterator column_rend (Size i) const
reverse_column_iterator column_rend (Size i)
Element access
const_row_iterator operator[] (Size) const
const_row_iterator at (Size) const
row_iterator operator[] (Size)
row_iterator at (Size)
Disposable< Array > diagonal (void) const
Inspectors
Size rows () const
Size columns () const
bool empty () const
Utilities
void swap (Matrix &)
Private Attributes
boost::scoped_array< Real > data_
Size rows_
Size columns_
Related Functions
(Note that these are not member functions.)
const Disposable< Matrix > operator+ (const Matrix &, const Matrix &)
const Disposable< Matrix > operator- (const Matrix &, const Matrix &)
const Disposable< Matrix > operator* (const Matrix &, Real)
const Disposable< Matrix > operator* (Real, const Matrix &)
const Disposable< Matrix > operator/ (const Matrix &, Real)
const Disposable< Array > operator* (const Array &, const Matrix &)
const Disposable< Array > operator* (const Matrix &, const Array &)
const Disposable< Matrix > operator* (const Matrix &, const Matrix &)
const Disposable< Matrix > transpose (const Matrix &)
const Disposable< Matrix > outerProduct (const Array &v1, const Array &v2)
template<class Iterator1 , class Iterator2 >
const Disposable< Matrix > outerProduct (Iterator1 v1begin, Iterator1 v1end, Iterator2 v2begin, Iterator2 v2end)
void swap (Matrix &, Matrix &)
std::ostream & operator<< (std::ostream &, const Matrix &)
Disposable< Matrix > inverse (const Matrix &m)
Real determinant (const Matrix &m)
const Disposable< Matrix > CholeskyDecomposition (const Matrix &m, bool flexible=false)
const Disposable< Matrix > pseudoSqrt (const Matrix &, SalvagingAlgorithm::Type=SalvagingAlgorithm::None)
Returns the pseudo square root of a real symmetric matrix.
const Disposable< Matrix > rankReducedSqrt (const Matrix &, Size maxRank, Real componentRetainedPercentage, SalvagingAlgorithm::Type)
Returns the rank-reduced pseudo square root of a real symmetric matrix.
Detailed Description
Matrix used in linear algebra.
This class implements the concept of Matrix as used in linear algebra. As such, it is not meant to be used as a container.
Definition at line 39 of file matrix.hpp.
Member Typedef Documentation
typedef step_iterator<iterator> QuantLib::Matrix::column_iterator
Definition at line 75 of file matrix.hpp.
typedef step_iterator<const_iterator> QuantLib::Matrix::const_column_iterator
Definition at line 76 of file matrix.hpp.
typedef const Real* QuantLib::Matrix::const_iterator
Definition at line 67 of file matrix.hpp.
typedef boost::reverse_iterator<const_column_iterator> QuantLib::Matrix::const_reverse_column_iterator
Definition at line 80 of file matrix.hpp.
typedef boost::reverse_iterator<const_iterator> QuantLib::Matrix::const_reverse_iterator
Definition at line 69 of file matrix.hpp.
typedef boost::reverse_iterator<const_row_iterator> QuantLib::Matrix::const_reverse_row_iterator
Definition at line 74 of file matrix.hpp.
typedef const Real* QuantLib::Matrix::const_row_iterator
Definition at line 71 of file matrix.hpp.
typedef Real* QuantLib::Matrix::iterator
Definition at line 66 of file matrix.hpp.
typedef boost::reverse_iterator<column_iterator> QuantLib::Matrix::reverse_column_iterator
Definition at line 78 of file matrix.hpp.
typedef boost::reverse_iterator<iterator> QuantLib::Matrix::reverse_iterator
Definition at line 68 of file matrix.hpp.
typedef boost::reverse_iterator<row_iterator> QuantLib::Matrix::reverse_row_iterator
Definition at line 72 of file matrix.hpp.
typedef Real* QuantLib::Matrix::row_iterator
Definition at line 70 of file matrix.hpp.
Constructor & Destructor Documentation
QuantLib::Matrix::Matrix () [inline]
creates a null matrix
Definition at line 184 of file matrix.hpp.
    : data_((Real*)(0)), rows_(0), columns_(0) {}
QuantLib::Matrix::Matrix (Size rows, Size columns) [inline]
creates a matrix with the given dimensions
Definition at line 187 of file matrix.hpp.
    : data_(rows*columns > 0 ? new Real[rows*columns] : (Real*)(0)),
      rows_(rows), columns_(columns) {}
QuantLib::Matrix::Matrix (Size rows, Size columns, Real value) [inline]
creates the matrix and fills it with value
Definition at line 191 of file matrix.hpp.
References begin(), and end().
    : data_(rows*columns > 0 ? new Real[rows*columns] : (Real*)(0)),
      rows_(rows), columns_(columns) {
        std::fill(begin(),end(),value);
    }
QuantLib::Matrix::Matrix (const Matrix & from) [inline]
Definition at line 197 of file matrix.hpp.
References begin(), empty(), and end().
    : data_(!from.empty() ? new Real[from.rows_*from.columns_] : (Real*)(0)),
      rows_(from.rows_), columns_(from.columns_) {
        #if defined(QL_PATCH_MSVC) && defined(QL_DEBUG)
        if (!from.empty())
        #endif
        std::copy(from.begin(),from.end(),begin());
    }
QuantLib::Matrix::Matrix (const Disposable< Matrix > & from) [inline]
Definition at line 206 of file matrix.hpp.
References swap().
    : data_((Real*)(0)), rows_(0), columns_(0) {
        swap(const_cast<Disposable<Matrix>&>(from));
    }
Member Function Documentation
Matrix::const_row_iterator QuantLib::Matrix::at (Size i) const [inline]
Definition at line 415 of file matrix.hpp.
References QL_REQUIRE, row_begin(), and rows_.
{
        QL_REQUIRE(i < rows_, "matrix access out of range");
        return row_begin(i);
    }
Matrix::row_iterator QuantLib::Matrix::at (Size i) [inline]
Definition at line 424 of file matrix.hpp.
References QL_REQUIRE, row_begin(), and rows_.
{
        QL_REQUIRE(i < rows_, "matrix access out of range");
        return row_begin(i);
    }
Matrix::const_iterator QuantLib::Matrix::begin () const [inline]
Definition at line 264 of file matrix.hpp.
References data_.
Referenced by QuantLib::determinant(), QuantLib::factorReduction(), QuantLib::anonymous_namespace{pseudosqrt.cpp}::hypersphereOptimize(), QuantLib::inverse(), Matrix(), QuantLib::operator*(), operator*=(), QuantLib::operator+(), operator+=(), QuantLib::operator-(), operator-=(), QuantLib::operator/(), operator/=(), QuantLib::Fdm2DimSolver::performCalculations(), QuantLib::qrDecomposition(), QuantLib::qrSolve(), rend(), MatricesTest::testDeterminant(), LiborMarketModelProcessTest::testMonteCarloCapletPricing(), BrownianBridgeTest::testPathGeneration(), and BrownianBridgeTest::testVariates().
{
        return data_.get();
    }
Matrix::iterator QuantLib::Matrix::begin () [inline]
Definition at line 268 of file matrix.hpp.
References data_.
{
        return data_.get();
    }
Matrix::const_column_iterator QuantLib::Matrix::column_begin (Size i) const [inline]
Definition at line 352 of file matrix.hpp.
References columns_, data_, and QL_REQUIRE.
Referenced by QuantLib::GeneralLinearLeastSquares::calculate(), column_rend(), QuantLib::LiborForwardModelProcess::drift(), QuantLib::LiborForwardModelProcess::evolve(), QuantLib::operator*(), QuantLib::qrDecomposition(), QuantLib::SymmetricSchurDecomposition::SymmetricSchurDecomposition(), MatricesTest::testQRSolve(), and QuantLib::TqrEigenDecomposition::TqrEigenDecomposition().
{
        #if defined(QL_EXTRA_SAFETY_CHECKS)
        QL_REQUIRE(i<columns_,
                   "column index (" << i << ") must be less than " << columns_ <<
                   ": matrix cannot be accessed out of range");
        #endif
        return const_column_iterator(data_.get()+i,columns_);
    }
Matrix::column_iterator QuantLib::Matrix::column_begin (Size i) [inline]
Definition at line 361 of file matrix.hpp.
References columns_, data_, and QL_REQUIRE.
{
        #if defined(QL_EXTRA_SAFETY_CHECKS)
        QL_REQUIRE(i<columns_,
                   "column index (" << i << ") must be less than " << columns_ <<
                   ": matrix cannot be accessed out of range");
        #endif
        return column_iterator(data_.get()+i,columns_);
    }
Matrix::const_column_iterator QuantLib::Matrix::column_end (Size i) const [inline]
Definition at line 371 of file matrix.hpp.
References columns_, data_, QL_REQUIRE, and rows_.
Referenced by QuantLib::GeneralLinearLeastSquares::calculate(), column_rbegin(), QuantLib::qrDecomposition(), QuantLib::SymmetricSchurDecomposition::SymmetricSchurDecomposition(), MatricesTest::testQRSolve(), and QuantLib::TqrEigenDecomposition::TqrEigenDecomposition().
{
        #if defined(QL_EXTRA_SAFETY_CHECKS)
        QL_REQUIRE(i<columns_,
                   "column index (" << i << ") must be less than " << columns_ <<
                   ": matrix cannot be accessed out of range");
        #endif
        return const_column_iterator(data_.get()+i+rows_*columns_,columns_);
    }
Matrix::column_iterator QuantLib::Matrix::column_end (Size i) [inline]
Definition at line 380 of file matrix.hpp.
References columns_, data_, QL_REQUIRE, and rows_.
{
        #if defined(QL_EXTRA_SAFETY_CHECKS)
        QL_REQUIRE(i<columns_,
                   "column index (" << i << ") must be less than " << columns_ <<
                   ": matrix cannot be accessed out of range");
        #endif
        return column_iterator(data_.get()+i+rows_*columns_,columns_);
    }
Matrix::const_reverse_column_iterator QuantLib::Matrix::column_rbegin (Size i) const [inline]
Definition at line 390 of file matrix.hpp.
References column_end().
{
        return const_reverse_column_iterator(column_end(i));
    }
Matrix::reverse_column_iterator QuantLib::Matrix::column_rbegin (Size i) [inline]
Definition at line 395 of file matrix.hpp.
References column_end().
{
        return reverse_column_iterator(column_end(i));
    }
Matrix::const_reverse_column_iterator QuantLib::Matrix::column_rend (Size i) const [inline]
Definition at line 400 of file matrix.hpp.
References column_begin().
{
        return const_reverse_column_iterator(column_begin(i));
    }
Matrix::reverse_column_iterator QuantLib::Matrix::column_rend (Size i) [inline]
Definition at line 405 of file matrix.hpp.
References column_begin().
{
        return reverse_column_iterator(column_begin(i));
    }
Size QuantLib::Matrix::columns () const [inline]
Definition at line 441 of file matrix.hpp.
References columns_.
Referenced by QuantLib::BlackVarianceSurface::BlackVarianceSurface(), QuantLib::CapFloorTermVolSurface::CapFloorTermVolSurface(), QuantLib::CTSMMCapletAlphaFormCalibration::capletAlphaFormCalibration(), QuantLib::CTSMMCapletMaxHomogeneityCalibration::capletMaxHomogeneityCalibration(), QuantLib::CapFloorTermVolSurface::checkInputs(), QuantLib::anonymous_namespace{pseudosqrt.cpp}::checkSymmetry(), QuantLib::CholeskyDecomposition(), QuantLib::CMSMMDriftCalculator::CMSMMDriftCalculator(), QuantLib::CovarianceDecomposition::CovarianceDecomposition(), QuantLib::CPICapFloorTermPriceSurface::CPICapFloorTermPriceSurface(), anonymous_namespace{rangeaccrual.cpp}::CommonVars::createVolatilityStructures(), QuantLib::determinant(), diagonal(), QuantLib::JointStochasticProcess::evolve(), QuantLib::factorReduction(), QuantLib::RatePseudoRootJacobianNumerical::getBumps(), QuantLib::RatePseudoRootJacobian::getBumps(), QuantLib::getCovariance(), QuantLib::anonymous_namespace{basisincompleteordered.cpp}::innerProduct(), QuantLib::inverse(), QuantLib::LfmHullWhiteParameterization::LfmHullWhiteParameterization(), QuantLib::LMMDriftCalculator::LMMDriftCalculator(), QuantLib::LMMNormalDriftCalculator::LMMNormalDriftCalculator(), QuantLib::MarketModelCashRebate::MarketModelCashRebate(), QuantLib::MarketModelPathwiseCashRebate::MarketModelPathwiseCashRebate(), anonymous_namespace{covariance.cpp}::norm(), anonymous_namespace{matrices.cpp}::norm(), QuantLib::anonymous_namespace{pseudosqrt.cpp}::normalizePseudoRoot(), QuantLib::anonymous_namespace{pseudosqrt.cpp}::normInf(), QuantLib::anonymous_namespace{basisincompleteordered.cpp}::normSquared(), QuantLib::operator*(), QuantLib::operator+(), QuantLib::operator-(), QuantLib::operator/(), QuantLib::operator<<(), QuantLib::SwaptionVolatilityMatrix::performCalculations(), QuantLib::anonymous_namespace{pseudosqrt.cpp}::projectToPositiveSemidefiniteMatrix(), QuantLib::anonymous_namespace{pseudosqrt.cpp}::projectToUnitDiagonalMatrix(), QuantLib::pseudoSqrt(), QuantLib::qrDecomposition(), QuantLib::qrSolve(), QuantLib::rankReducedSqrt(), QuantLib::SwaptionVolCube1::Cube::setLayer(), QuantLib::SMMDriftCalculator::SMMDriftCalculator(), QuantLib::SVD::SVD(), QuantLib::SwaptionVolatilityMatrix::SwaptionVolatilityMatrix(), QuantLib::SymmetricSchurDecomposition::SymmetricSchurDecomposition(), InterpolationTest::testKernelInterpolation2D(), LiborMarketModelProcessTest::testLambdaBootstrapping(), MatricesTest::testQRDecomposition(), MatricesTest::testQRSolve(), QuantLib::Fdm2DimSolver::thetaAt(), QuantLib::TimeHomogeneousForwardCorrelation::TimeHomogeneousForwardCorrelation(), QuantLib::transpose(), QuantLib::FrobeniusCostFunction::values(), and QuantLib::YoYCapFloorTermPriceSurface::YoYCapFloorTermPriceSurface().
{
        return columns_;
    }
Disposable< Array > QuantLib::Matrix::diagonal (void) const [inline]
Definition at line 429 of file matrix.hpp.
References columns(), and rows().
Referenced by QuantLib::GenericSequenceStatistics< StatisticsType >::correlation(), QuantLib::JointStochasticProcess::covariance(), QuantLib::JointStochasticProcess::evolve(), and LiborMarketModelTest::testCapletPricing().
{
        Size arraySize = std::min<Size>(rows(), columns());
        Array tmp(arraySize);
        for(Size i = 0; i < arraySize; i++)
            tmp[i] = (*this)[i][i];
        return tmp;
    }
bool QuantLib::Matrix::empty () const [inline]
Definition at line 445 of file matrix.hpp.
References columns_, and rows_.
Referenced by QuantLib::LfmHullWhiteParameterization::LfmHullWhiteParameterization(), Matrix(), and QuantLib::transpose().
{
        return rows_ == 0 || columns_ == 0;
    }
Matrix::const_iterator QuantLib::Matrix::end () const [inline]
Definition at line 272 of file matrix.hpp.
References columns_, data_, and rows_.
Referenced by QuantLib::determinant(), QuantLib::factorReduction(), QuantLib::anonymous_namespace{pseudosqrt.cpp}::hypersphereOptimize(), QuantLib::inverse(), Matrix(), QuantLib::operator*(), operator*=(), QuantLib::operator+(), operator+=(), QuantLib::operator-(), operator-=(), QuantLib::operator/(), operator/=(), rbegin(), MatricesTest::testDeterminant(), BrownianBridgeTest::testPathGeneration(), and BrownianBridgeTest::testVariates().
{
        return data_.get()+rows_*columns_;
    }
Matrix::iterator QuantLib::Matrix::end () [inline]
Definition at line 276 of file matrix.hpp.
References columns_, data_, and rows_.
{
        return data_.get()+rows_*columns_;
    }
const Matrix & QuantLib::Matrix::operator*= (Real x) [inline]
Definition at line 252 of file matrix.hpp.
References begin(), and end().
{
        std::transform(begin(),end(),begin(),
                       std::bind2nd(std::multiplies<Real>(),x));
        return *this;
    }
const Matrix & QuantLib::Matrix::operator+= (const Matrix & m) [inline]
Precondition:
all matrices involved in an algebraic expression must have the same size.
Definition at line 230 of file matrix.hpp.
References begin(), columns_, end(), QL_REQUIRE, and rows_.
{
        QL_REQUIRE(rows_ == m.rows_ && columns_ == m.columns_,
                   "matrices with different sizes (" <<
                   m.rows_ << "x" << m.columns_ << ", " <<
                   rows_ << "x" << columns_ << ") cannot be "
                   "added");
        std::transform(begin(),end(),m.begin(),
                       begin(),std::plus<Real>());
        return *this;
    }
const Matrix & QuantLib::Matrix::operator-= (const Matrix & m) [inline]
Definition at line 241 of file matrix.hpp.
References begin(), columns_, end(), QL_REQUIRE, and rows_.
{
        QL_REQUIRE(rows_ == m.rows_ && columns_ == m.columns_,
                   "matrices with different sizes (" <<
                   m.rows_ << "x" << m.columns_ << ", " <<
                   rows_ << "x" << columns_ << ") cannot be "
                   "subtracted");
        std::transform(begin(),end(),m.begin(),begin(),
                       std::minus<Real>());
        return *this;
    }
const Matrix & QuantLib::Matrix::operator/= (Real x) [inline]
Definition at line 258 of file matrix.hpp.
References begin(), and end().
{
        std::transform(begin(),end(),begin(),
                       std::bind2nd(std::divides<Real>(),x));
        return *this;
    }
Matrix & QuantLib::Matrix::operator= (const Matrix & from) [inline]
Definition at line 211 of file matrix.hpp.
References swap().
{
        // strong guarantee
        Matrix temp(from);
        swap(temp);
        return *this;
    }
Matrix & QuantLib::Matrix::operator= (const Disposable< Matrix > & from) [inline]
Reimplemented in QuantLib::Disposable< Matrix >.
Definition at line 218 of file matrix.hpp.
References swap().
{
        swap(const_cast<Disposable<Matrix>&>(from));
        return *this;
    }
Matrix::const_row_iterator QuantLib::Matrix::operator[] (Size i) const [inline]
Definition at line 410 of file matrix.hpp.
References row_begin().
{
        return row_begin(i);
    }
Matrix::row_iterator QuantLib::Matrix::operator[] (Size i) [inline]
Definition at line 420 of file matrix.hpp.
References row_begin().
{
        return row_begin(i);
    }
Matrix::const_reverse_iterator QuantLib::Matrix::rbegin () const [inline]
Definition at line 280 of file matrix.hpp.
References end().
{
        return const_reverse_iterator(end());
    }
Matrix::reverse_iterator QuantLib::Matrix::rbegin () [inline]
Definition at line 284 of file matrix.hpp.
References end().
{
        return reverse_iterator(end());
    }
Matrix::const_reverse_iterator QuantLib::Matrix::rend () const [inline]
Definition at line 288 of file matrix.hpp.
References begin().
{
        return const_reverse_iterator(begin());
    }
Matrix::reverse_iterator QuantLib::Matrix::rend () [inline]
Definition at line 292 of file matrix.hpp.
References begin().
{
        return reverse_iterator(begin());
    }
Matrix::const_row_iterator QuantLib::Matrix::row_begin (Size i) const [inline]
Definition at line 297 of file matrix.hpp.
References columns_, data_, QL_REQUIRE, and rows_.
Referenced by QuantLib::LogNormalFwdRateBalland::advanceStep(), QuantLib::LogNormalFwdRateiBalland::advanceStep(), QuantLib::LogNormalFwdRateEuler::advanceStep(), QuantLib::LogNormalCotSwapRatePc::advanceStep(), QuantLib::LogNormalFwdRateIpc::advanceStep(), QuantLib::LogNormalFwdRatePc::advanceStep(), QuantLib::NormalFwdRatePc::advanceStep(), QuantLib::LogNormalCmSwapRatePc::advanceStep(), QuantLib::SVDDFwdRatePc::advanceStep(), QuantLib::LogNormalFwdRateEulerConstrained::advanceStep(), at(), QuantLib::LMMDriftCalculator::computePlain(), QuantLib::LMMNormalDriftCalculator::computePlain(), QuantLib::coterminalSwapPseudoRoots(), QuantLib::JointStochasticProcess::covariance(), QuantLib::LfmCovarianceProxy::diffusion(), QuantLib::StochasticProcessArray::diffusion(), QuantLib::JointStochasticProcess::evolve(), QuantLib::LiborForwardModelProcess::evolve(), QuantLib::LogNormalCmSwapRatePc::LogNormalCmSwapRatePc(), QuantLib::LogNormalCotSwapRatePc::LogNormalCotSwapRatePc(), QuantLib::LogNormalFwdRateEuler::LogNormalFwdRateEuler(), QuantLib::LogNormalFwdRateEulerConstrained::LogNormalFwdRateEulerConstrained(), QuantLib::LogNormalFwdRatePc::LogNormalFwdRatePc(), QuantLib::LfmCovarianceParameterization::Var_Helper::operator()(), QuantLib::operator*(), operator[](), QuantLib::outerProduct(), QuantLib::qrDecomposition(), row_rend(), QuantLib::StochasticProcessArray::stdDeviation(), QuantLib::SVDDFwdRatePc::SVDDFwdRatePc(), MatricesTest::testDeterminant(), and QuantLib::transpose().
{
        #if defined(QL_EXTRA_SAFETY_CHECKS)
        QL_REQUIRE(i<rows_,
                   "row index (" << i << ") must be less than " << rows_ <<
                   ": matrix cannot be accessed out of range");
        #endif
        return data_.get()+columns_*i;
    }
Matrix::row_iterator QuantLib::Matrix::row_begin (Size i) [inline]
Definition at line 306 of file matrix.hpp.
References columns_, data_, QL_REQUIRE, and rows_.
{
        #if defined(QL_EXTRA_SAFETY_CHECKS)
        QL_REQUIRE(i<rows_,
                   "row index (" << i << ") must be less than " << rows_ <<
                   ": matrix cannot be accessed out of range");
        #endif
        return data_.get()+columns_*i;
    }
Matrix::const_row_iterator QuantLib::Matrix::row_end (Size i) const [inline]
Definition at line 315 of file matrix.hpp.
References columns_, data_, QL_REQUIRE, and rows_.
Referenced by QuantLib::LogNormalFwdRateBalland::advanceStep(), QuantLib::LogNormalFwdRateiBalland::advanceStep(), QuantLib::LogNormalFwdRateIpc::advanceStep(), QuantLib::LogNormalFwdRatePc::advanceStep(), QuantLib::NormalFwdRatePc::advanceStep(), QuantLib::LogNormalCotSwapRatePc::advanceStep(), QuantLib::LogNormalFwdRateEuler::advanceStep(), QuantLib::LogNormalCmSwapRatePc::advanceStep(), QuantLib::SVDDFwdRatePc::advanceStep(), QuantLib::LogNormalFwdRateEulerConstrained::advanceStep(), QuantLib::coterminalSwapPseudoRoots(), QuantLib::JointStochasticProcess::covariance(), QuantLib::LfmCovarianceProxy::diffusion(), QuantLib::StochasticProcessArray::diffusion(), QuantLib::JointStochasticProcess::evolve(), QuantLib::LiborForwardModelProcess::evolve(), QuantLib::LogNormalCmSwapRatePc::LogNormalCmSwapRatePc(), QuantLib::LogNormalCotSwapRatePc::LogNormalCotSwapRatePc(), QuantLib::LogNormalFwdRateEuler::LogNormalFwdRateEuler(), QuantLib::LogNormalFwdRateEulerConstrained::LogNormalFwdRateEulerConstrained(), QuantLib::LogNormalFwdRatePc::LogNormalFwdRatePc(), QuantLib::LfmCovarianceParameterization::Var_Helper::operator()(), QuantLib::operator*(), QuantLib::qrDecomposition(), row_rbegin(), QuantLib::StochasticProcessArray::stdDeviation(), QuantLib::SVDDFwdRatePc::SVDDFwdRatePc(), MatricesTest::testDeterminant(), and QuantLib::transpose().
{
        #if defined(QL_EXTRA_SAFETY_CHECKS)
        QL_REQUIRE(i<rows_,
                   "row index (" << i << ") must be less than " << rows_ <<
                   ": matrix cannot be accessed out of range");
        #endif
        return data_.get()+columns_*(i+1);
    }
Matrix::row_iterator QuantLib::Matrix::row_end (Size i) [inline]
Definition at line 324 of file matrix.hpp.
References columns_, data_, QL_REQUIRE, and rows_.
{
        #if defined(QL_EXTRA_SAFETY_CHECKS)
        QL_REQUIRE(i<rows_,
                   "row index (" << i << ") must be less than " << rows_ <<
                   ": matrix cannot be accessed out of range");
        #endif
        return data_.get()+columns_*(i+1);
    }
Matrix::const_reverse_row_iterator QuantLib::Matrix::row_rbegin (Size i) const [inline]
Definition at line 334 of file matrix.hpp.
References row_end().
{
        return const_reverse_row_iterator(row_end(i));
    }
Matrix::reverse_row_iterator QuantLib::Matrix::row_rbegin (Size i) [inline]
Definition at line 338 of file matrix.hpp.
References row_end().
{
        return reverse_row_iterator(row_end(i));
    }
Matrix::const_reverse_row_iterator QuantLib::Matrix::row_rend (Size i) const [inline]
Definition at line 343 of file matrix.hpp.
References row_begin().
{
        return const_reverse_row_iterator(row_begin(i));
    }
Matrix::reverse_row_iterator QuantLib::Matrix::row_rend (Size i) [inline]
Definition at line 347 of file matrix.hpp.
References row_begin().
{
        return reverse_row_iterator(row_begin(i));
    }
Size QuantLib::Matrix::rows () const [inline]
Definition at line 437 of file matrix.hpp.
References rows_.
Referenced by QuantLib::BlackVarianceSurface::BlackVarianceSurface(), QuantLib::CapFloorTermVolSurface::CapFloorTermVolSurface(), QuantLib::CapFloorTermVolSurface::checkInputs(), QuantLib::anonymous_namespace{pseudosqrt.cpp}::checkSymmetry(), QuantLib::CholeskyDecomposition(), QuantLib::CMSMMDriftCalculator::CMSMMDriftCalculator(), QuantLib::CMSMMDriftCalculator::compute(), QuantLib::coterminalSwapPseudoRoots(), QuantLib::JointStochasticProcess::covariance(), QuantLib::CovarianceDecomposition::CovarianceDecomposition(), QuantLib::CPICapFloorTermPriceSurface::CPICapFloorTermPriceSurface(), anonymous_namespace{rangeaccrual.cpp}::CommonVars::createVolatilityStructures(), QuantLib::determinant(), diagonal(), QuantLib::JointStochasticProcess::evolve(), QuantLib::TimeHomogeneousForwardCorrelation::evolvedMatrices(), QuantLib::factorReduction(), QuantLib::RatePseudoRootJacobianNumerical::getBumps(), QuantLib::RatePseudoRootJacobian::getBumps(), QuantLib::getCovariance(), QuantLib::BFGS::getUpdatedDirection(), QuantLib::anonymous_namespace{pseudosqrt.cpp}::highamImplementation(), QuantLib::anonymous_namespace{pseudosqrt.cpp}::hypersphereOptimize(), QuantLib::inverse(), QuantLib::LfmHullWhiteParameterization::LfmHullWhiteParameterization(), QuantLib::LMMDriftCalculator::LMMDriftCalculator(), QuantLib::LMMNormalDriftCalculator::LMMNormalDriftCalculator(), QuantLib::lmmTriangularAnglesParametrization(), QuantLib::MarketModelCashRebate::MarketModelCashRebate(), QuantLib::MarketModelPathwiseCashRebate::MarketModelPathwiseCashRebate(), anonymous_namespace{covariance.cpp}::norm(), anonymous_namespace{matrices.cpp}::norm(), QuantLib::anonymous_namespace{pseudosqrt.cpp}::normalizePseudoRoot(), QuantLib::anonymous_namespace{pseudosqrt.cpp}::normInf(), QuantLib::operator*(), QuantLib::operator+(), QuantLib::operator-(), QuantLib::operator/(), QuantLib::operator<<(), QuantLib::SwaptionVolatilityMatrix::performCalculations(), QuantLib::anonymous_namespace{pseudosqrt.cpp}::projectToPositiveSemidefiniteMatrix(), QuantLib::anonymous_namespace{pseudosqrt.cpp}::projectToUnitDiagonalMatrix(), QuantLib::pseudoSqrt(), QuantLib::qrDecomposition(), QuantLib::qrSolve(), QuantLib::rankReducedSqrt(), QuantLib::RatePseudoRootJacobian::RatePseudoRootJacobian(), QuantLib::RatePseudoRootJacobianAllElements::RatePseudoRootJacobianAllElements(), QuantLib::RatePseudoRootJacobianNumerical::RatePseudoRootJacobianNumerical(), QuantLib::SwaptionVolCube1::Cube::setLayer(), QuantLib::SMMDriftCalculator::SMMDriftCalculator(), QuantLib::StochasticProcessArray::StochasticProcessArray(), QuantLib::SVD::SVD(), QuantLib::SwaptionVolatilityMatrix::SwaptionVolatilityMatrix(), QuantLib::SymmetricSchurDecomposition::SymmetricSchurDecomposition(), InterpolationTest::testKernelInterpolation2D(), LiborMarketModelProcessTest::testLambdaBootstrapping(), MatricesTest::testQRSolve(), MatricesTest::testSVD(), QuantLib::Fdm2DimSolver::thetaAt(), QuantLib::TimeHomogeneousForwardCorrelation::TimeHomogeneousForwardCorrelation(), QuantLib::TqrEigenDecomposition::TqrEigenDecomposition(), QuantLib::transpose(), QuantLib::triangularAnglesParametrizationRankThree(), QuantLib::FrobeniusCostFunction::values(), and QuantLib::YoYCapFloorTermPriceSurface::YoYCapFloorTermPriceSurface().
{
        return rows_;
    }
void QuantLib::Matrix::swap (Matrix & from) [inline]
Definition at line 223 of file matrix.hpp.
References columns_, data_, and rows_.
Referenced by Matrix(), operator=(), and QuantLib::swap().
{
        using std::swap;
        data_.swap(from.data_);
        swap(rows_,from.rows_);
        swap(columns_,from.columns_);
    }
Friends And Related Function Documentation
const Disposable< Matrix > CholeskyDecomposition (const Matrix & m, bool flexible = false) [related]
Definition at line 24 of file choleskydecomposition.cpp.
{
        Size i, j, size = S.rows();
        QL_REQUIRE(size == S.columns(),
                   "input matrix is not a square matrix");
        #if defined(QL_EXTRA_SAFETY_CHECKS)
        for (i=0; i<S.rows(); i++)
            for (j=0; j<i; j++)
                QL_REQUIRE(S[i][j] == S[j][i],
                           "input matrix is not symmetric");
        #endif
        Matrix result(size, size, 0.0);
        Real sum;
        for (i=0; i<size; i++) {
            for (j=i; j<size; j++) {
                sum = S[i][j];
                for (Integer k=0; k<=Integer(i)-1; k++) {
                    sum -= result[i][k]*result[j][k];
                }
                if (i == j) {
                    QL_REQUIRE(flexible || sum > 0.0,
                               "input matrix is not positive definite");
                    // To handle positive semi-definite matrices take the
                    // square root of sum if positive, else zero.
                    result[i][i] = std::sqrt(std::max<Real>(sum, 0.0));
                } else {
                    // With positive semi-definite matrices is possible
                    // to have result[i][i]==0.0
                    // In this case sum happens to be zero as well
                    result[j][i] =
                        (sum==0.0 ? 0.0 : sum/result[i][i]);
                }
            }
        }
        return result;
    }
Real determinant (const Matrix & m) [related]
Definition at line 75 of file matrix.cpp.
{
        #if !defined(QL_NO_UBLAS_SUPPORT)
        QL_REQUIRE(m.rows() == m.columns(), "matrix is not square");
        boost::numeric::ublas::matrix<Real> a(m.rows(), m.columns());
        std::copy(m.begin(), m.end(), a.data().begin());
        // lu decomposition
        boost::numeric::ublas::permutation_matrix<Size> pert(m.rows());
        /* const Size singular = */ lu_factorize(a, pert);
        Real retVal = 1.0;
        for (Size i=0; i < m.rows(); ++i) {
            if (pert[i] != i)
                retVal *= -a(i,i);
            else
                retVal *=  a(i,i);
        }
        return retVal;
        #else
        QL_FAIL("this version of gcc does not support "
                "the Boost uBLAS library");
        #endif
    }
Disposable< Matrix > inverse (const Matrix & m) [related]
Definition at line 42 of file matrix.cpp.
{
        #if !defined(QL_NO_UBLAS_SUPPORT)
        QL_REQUIRE(m.rows() == m.columns(), "matrix is not square");
        boost::numeric::ublas::matrix<Real> a(m.rows(), m.columns());
        std::copy(m.begin(), m.end(), a.data().begin());
        boost::numeric::ublas::permutation_matrix<Size> pert(m.rows());
        // lu decomposition
        const Size singular = lu_factorize(a, pert);
        QL_REQUIRE(singular == 0, "singular matrix given");
        boost::numeric::ublas::matrix<Real>
            inverse = boost::numeric::ublas::identity_matrix<Real>(m.rows());
        // backsubstitution
        boost::numeric::ublas::lu_substitute(a, pert, inverse);
        Matrix retVal(m.rows(), m.columns());
        std::copy(inverse.data().begin(), inverse.data().end(),
                  retVal.begin());
        return retVal;
        #else
        QL_FAIL("this version of gcc does not support "
                "the Boost uBLAS library");
        #endif
    }
const Disposable< Matrix > operator* (const Matrix & , Real) [related]
Definition at line 477 of file matrix.hpp.
{
        Matrix temp(m.rows(),m.columns());
        std::transform(m.begin(),m.end(),temp.begin(),
                       std::bind2nd(std::multiplies<Real>(),x));
        return temp;
    }
const Disposable< Matrix > operator* (Real , const Matrix &) [related]
Definition at line 484 of file matrix.hpp.
{
        Matrix temp(m.rows(),m.columns());
        std::transform(m.begin(),m.end(),temp.begin(),
                       std::bind2nd(std::multiplies<Real>(),x));
        return temp;
    }
const Disposable< Array > operator* (const Array & , const Matrix &) [related]
Definition at line 498 of file matrix.hpp.
{
        QL_REQUIRE(v.size() == m.rows(),
                   "vectors and matrices with different sizes ("
                   << v.size() << ", " << m.rows() << "x" << m.columns() <<
                   ") cannot be multiplied");
        Array result(m.columns());
        for (Size i=0; i<result.size(); i++)
            result[i] =
                std::inner_product(v.begin(),v.end(),
                                   m.column_begin(i),0.0);
        return result;
    }
const Disposable< Array > operator* (const Matrix & , const Array &) [related]
Definition at line 511 of file matrix.hpp.
{
        QL_REQUIRE(v.size() == m.columns(),
                   "vectors and matrices with different sizes ("
                   << v.size() << ", " << m.rows() << "x" << m.columns() <<
                   ") cannot be multiplied");
        Array result(m.rows());
        for (Size i=0; i<result.size(); i++)
            result[i] =
                std::inner_product(v.begin(),v.end(),m.row_begin(i),0.0);
        return result;
    }
const Disposable< Matrix > operator* (const Matrix & , const Matrix &) [related]
Definition at line 523 of file matrix.hpp.
{
        QL_REQUIRE(m1.columns() == m2.rows(),
                   "matrices with different sizes (" <<
                   m1.rows() << "x" << m1.columns() << ", " <<
                   m2.rows() << "x" << m2.columns() << ") cannot be "
                   "multiplied");
        Matrix result(m1.rows(),m2.columns());
        for (Size i=0; i<result.rows(); i++)
            for (Size j=0; j<result.columns(); j++)
                result[i][j] =
                    std::inner_product(m1.row_begin(i), m1.row_end(i),
                                       m2.column_begin(j), 0.0);
        return result;
    }
const Disposable< Matrix > operator+ (const Matrix & , const Matrix &) [related]
Definition at line 449 of file matrix.hpp.
{
        QL_REQUIRE(m1.rows() == m2.rows() &&
                   m1.columns() == m2.columns(),
                   "matrices with different sizes (" <<
                   m1.rows() << "x" << m1.columns() << ", " <<
                   m2.rows() << "x" << m2.columns() << ") cannot be "
                   "added");
        Matrix temp(m1.rows(),m1.columns());
        std::transform(m1.begin(),m1.end(),m2.begin(),temp.begin(),
                       std::plus<Real>());
        return temp;
    }
const Disposable< Matrix > operator- (const Matrix & , const Matrix &) [related]
Definition at line 463 of file matrix.hpp.
{
        QL_REQUIRE(m1.rows() == m2.rows() &&
                   m1.columns() == m2.columns(),
                   "matrices with different sizes (" <<
                   m1.rows() << "x" << m1.columns() << ", " <<
                   m2.rows() << "x" << m2.columns() << ") cannot be "
                   "subtracted");
        Matrix temp(m1.rows(),m1.columns());
        std::transform(m1.begin(),m1.end(),m2.begin(),temp.begin(),
                       std::minus<Real>());
        return temp;
    }
const Disposable< Matrix > operator/ (const Matrix & , Real) [related]
Definition at line 491 of file matrix.hpp.
{
        Matrix temp(m.rows(),m.columns());
        std::transform(m.begin(),m.end(),temp.begin(),
                       std::bind2nd(std::divides<Real>(),x));
        return temp;
    }
std::ostream & operator<< (std::ostream & , const Matrix &) [related]
Definition at line 579 of file matrix.hpp.
{
        std::streamsize width = out.width();
        for (Size i=0; i<m.rows(); i++) {
            out << "| ";
            for (Size j=0; j<m.columns(); j++)
                out << std::setw(width) << m[i][j] << " ";
            out << "|\n";
        }
        return out;
    }
const Disposable< Matrix > outerProduct (const Array & v1, const Array & v2) [related]
Definition at line 549 of file matrix.hpp.
{
        return outerProduct(v1.begin(), v1.end(), v2.begin(), v2.end());
    }
template<class Iterator1 , class Iterator2 > const Disposable< Matrix > outerProduct (Iterator1 v1begin, Iterator1 v1end, Iterator2 v2begin, Iterator2 v2end) [related]
Definition at line 555 of file matrix.hpp.
{
        Size size1 = std::distance(v1begin, v1end);
        QL_REQUIRE(size1>0, "null first vector");
        Size size2 = std::distance(v2begin, v2end);
        QL_REQUIRE(size2>0, "null second vector");
        Matrix result(size1, size2);
        for (Size i=0; v1begin!=v1end; i++, v1begin++)
            std::transform(v2begin, v2end, result.row_begin(i),
                           std::bind1st(std::multiplies<Real>(), *v1begin));
        return result;
    }
const Disposable< Matrix > pseudoSqrt (const Matrix & , SalvagingAlgorithm::Type = SalvagingAlgorithm::None) [related]
Returns the pseudo square root of a real symmetric matrix.
Given a matrix \(M \), the result \(S \) is defined as the matrix such that \(S S^T = M. \) If the matrix is not positive semi definite, it can return an approximation of the pseudo square root using a (user selected) salvaging algorithm.
For more information see: R. Rebonato and P. Jckel, The most general methodology to create a valid correlation matrix for risk management and option pricing purposes, The Journal of Risk, 2(2), Winter 1999/2000. http://www.rebonato.com/correlationmatrix.pdf
Revised and extended in "Monte Carlo Methods in Finance", by Peter Jckel, Chapter 6.
Precondition:
the given matrix must be symmetric.
Warning:
Higham algorithm only works for correlation matrices.
Test:
the correctness of the results is tested by reproducing known good data.
the correctness of the results is tested by checking returned values against numerical calculations.
Definition at line 352 of file pseudosqrt.cpp.
Referenced by LiborMarketModelTest::testSimpleCovarianceModels().
{
        Size size = matrix.rows();
        #if defined(QL_EXTRA_SAFETY_CHECKS)
        checkSymmetry(matrix);
        #else
        QL_REQUIRE(size == matrix.columns(),
                   "non square matrix: " << size << " rows, " <<
                   matrix.columns() << " columns");
        #endif
        // spectral (a.k.a Principal Component) analysis
        SymmetricSchurDecomposition jd(matrix);
        Matrix diagonal(size, size, 0.0);
        // salvaging algorithm
        Matrix result(size, size);
        bool negative;
        switch (sa) {
          case SalvagingAlgorithm::None:
            // eigenvalues are sorted in decreasing order
            QL_REQUIRE(jd.eigenvalues()[size-1]>=-1e-16,
                       "negative eigenvalue(s) ("
                       << std::scientific << jd.eigenvalues()[size-1]
                       << ")");
            result = CholeskyDecomposition(matrix, true);
            break;
          case SalvagingAlgorithm::Spectral:
            // negative eigenvalues set to zero
            for (Size i=0; i<size; i++)
                diagonal[i][i] =
                    std::sqrt(std::max<Real>(jd.eigenvalues()[i], 0.0));
            result = jd.eigenvectors() * diagonal;
            normalizePseudoRoot(matrix, result);
            break;
          case SalvagingAlgorithm::Hypersphere:
            // negative eigenvalues set to zero
            negative=false;
            for (Size i=0; i<size; ++i){
                diagonal[i][i] =
                    std::sqrt(std::max<Real>(jd.eigenvalues()[i], 0.0));
                if (jd.eigenvalues()[i]<0.0) negative=true;
            }
            result = jd.eigenvectors() * diagonal;
            normalizePseudoRoot(matrix, result);
            if (negative)
                result = hypersphereOptimize(matrix, result, false);
            break;
          case SalvagingAlgorithm::LowerDiagonal:
            // negative eigenvalues set to zero
            negative=false;
            for (Size i=0; i<size; ++i){
                diagonal[i][i] =
                    std::sqrt(std::max<Real>(jd.eigenvalues()[i], 0.0));
                if (jd.eigenvalues()[i]<0.0) negative=true;
            }
            result = jd.eigenvectors() * diagonal;
            normalizePseudoRoot(matrix, result);
            if (negative)
                result = hypersphereOptimize(matrix, result, true);
            break;
          case SalvagingAlgorithm::Higham: {
              int maxIterations = 40;
              Real tol = 1e-6;
              result = highamImplementation(matrix, maxIterations, tol);
              result = CholeskyDecomposition(result, true);
            }
            break;
          default:
            QL_FAIL("unknown salvaging algorithm");
        }
        return result;
    }
const Disposable< Matrix > rankReducedSqrt (const Matrix & , Size maxRank, Real componentRetainedPercentage, SalvagingAlgorithm::Type) [related]
Returns the rank-reduced pseudo square root of a real symmetric matrix.
The result matrix has rank<=maxRank. If maxRank>=size, then the specified percentage of eigenvalues out of the eigenvalues' sum is retained.
If the input matrix is not positive semi definite, it can return an approximation of the pseudo square root using a (user selected) salvaging algorithm.
Precondition:
the given matrix must be symmetric.
Definition at line 433 of file pseudosqrt.cpp.
{
        Size size = matrix.rows();
        #if defined(QL_EXTRA_SAFETY_CHECKS)
        checkSymmetry(matrix);
        #else
        QL_REQUIRE(size == matrix.columns(),
                   "non square matrix: " << size << " rows, " <<
                   matrix.columns() << " columns");
        #endif
        QL_REQUIRE(componentRetainedPercentage>0.0,
                   "no eigenvalues retained");
        QL_REQUIRE(componentRetainedPercentage<=1.0,
                   "percentage to be retained > 100%");
        QL_REQUIRE(maxRank>=1,
                   "max rank required < 1");
        // spectral (a.k.a Principal Component) analysis
        SymmetricSchurDecomposition jd(matrix);
        Array eigenValues = jd.eigenvalues();
        // salvaging algorithm
        switch (sa) {
          case SalvagingAlgorithm::None:
            // eigenvalues are sorted in decreasing order
            QL_REQUIRE(eigenValues[size-1]>=-1e-16,
                       "negative eigenvalue(s) ("
                       << std::scientific << eigenValues[size-1]
                       << ")");
            break;
          case SalvagingAlgorithm::Spectral:
            // negative eigenvalues set to zero
            for (Size i=0; i<size; ++i)
                eigenValues[i] = std::max<Real>(eigenValues[i], 0.0);
            break;
          case SalvagingAlgorithm::Higham:
              {
                  int maxIterations = 40;
                  Real tolerance = 1e-6;
                  Matrix adjustedMatrix = highamImplementation(matrix, maxIterations, tolerance);
                  jd = SymmetricSchurDecomposition(adjustedMatrix);
                  eigenValues = jd.eigenvalues();
              }
              break;
          default:
            QL_FAIL("unknown or invalid salvaging algorithm");
        }
        // factor reduction
        Real enough = componentRetainedPercentage *
                      std::accumulate(eigenValues.begin(),
                                      eigenValues.end(), 0.0);
        if (componentRetainedPercentage == 1.0) {
            // numerical glitches might cause some factors to be discarded
            enough *= 1.1;
        }
        // retain at least one factor
        Real components = eigenValues[0];
        Size retainedFactors = 1;
        for (Size i=1; components<enough && i<size; ++i) {
            components += eigenValues[i];
            retainedFactors++;
        }
        // output is granted to have a rank<=maxRank
        retainedFactors=std::min(retainedFactors, maxRank);
        Matrix diagonal(size, retainedFactors, 0.0);
        for (Size i=0; i<retainedFactors; ++i)
            diagonal[i][i] = std::sqrt(eigenValues[i]);
        Matrix result = jd.eigenvectors() * diagonal;
        normalizePseudoRoot(matrix, result);
        return result;
    }
void swap (Matrix & , Matrix &) [related]
Definition at line 575 of file matrix.hpp.
{
        m1.swap(m2);
    }
const Disposable< Matrix > transpose (const Matrix &) [related]
Definition at line 539 of file matrix.hpp.
{
        Matrix result(m.columns(),m.rows());
        #if defined(QL_PATCH_MSVC) && defined(QL_DEBUG)
        if (!m.empty())
        #endif
        for (Size i=0; i<m.rows(); i++)
            std::copy(m.row_begin(i),m.row_end(i),result.column_begin(i));
        return result;
    }
Member Data Documentation
Size QuantLib::Matrix::columns_ [private]
Definition at line 131 of file matrix.hpp.
Referenced by column_begin(), column_end(), columns(), empty(), end(), operator+=(), operator-=(), row_begin(), row_end(), and swap().
boost::scoped_array<Real> QuantLib::Matrix::data_ [private]
Definition at line 130 of file matrix.hpp.
Referenced by begin(), column_begin(), column_end(), end(), row_begin(), row_end(), and swap().
Size QuantLib::Matrix::rows_ [private]
Definition at line 131 of file matrix.hpp.
Referenced by at(), column_end(), empty(), end(), operator+=(), operator-=(), row_begin(), row_end(), rows(), and swap().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/matrix.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/math/matrixutilities/choleskydecomposition.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/math/matrixutilities/pseudosqrt.hpp