QuantLib: QuantLib::BlackVolTermStructure Class Reference
QuantLib::BlackVolTermStructure Class Reference
Black-volatility term structure.
#include <blackvoltermstructure.hpp>
Public Member Functions
virtual ~BlackVolTermStructure ()
Constructors
See the TermStructure documentation for issues regarding constructors.
BlackVolTermStructure (const Calendar &cal, BusinessDayConvention bdc=Following, const DayCounter &dc=DayCounter())
BlackVolTermStructure (BusinessDayConvention bdc=Following, const DayCounter &dc=DayCounter())
default constructor
BlackVolTermStructure (const Date &referenceDate, const Calendar &cal=Calendar(), BusinessDayConvention bdc=Following, const DayCounter &dc=DayCounter())
initialize with a fixed reference date
BlackVolTermStructure (Natural settlementDays, const Calendar &, BusinessDayConvention bdc=Following, const DayCounter &dc=DayCounter())
calculate the reference date based on the global evaluation date
Black Volatility
Volatility blackVol (const Date &maturity, Real strike, bool extrapolate=false) const
spot volatility
Volatility blackVol (Time maturity, Real strike, bool extrapolate=false) const
spot volatility
Real blackVariance (const Date &maturity, Real strike, bool extrapolate=false) const
spot variance
Real blackVariance (Time maturity, Real strike, bool extrapolate=false) const
spot variance
Volatility blackForwardVol (const Date &date1, const Date &date2, Real strike, bool extrapolate=false) const
forward (at-the-money) volatility
Volatility blackForwardVol (Time time1, Time time2, Real strike, bool extrapolate=false) const
forward (at-the-money) volatility
Real blackForwardVariance (const Date &date1, const Date &date2, Real strike, bool extrapolate=false) const
forward (at-the-money) variance
Real blackForwardVariance (Time time1, Time time2, Real strike, bool extrapolate=false) const
forward (at-the-money) variance
Visitability
virtual void accept (AcyclicVisitor &)
Protected Member Functions
Calculations
These methods must be implemented in derived classes to perform the actual volatility calculations. When they are called, range check has already been performed; therefore, they must assume that extrapolation is required.
virtual Real blackVarianceImpl (Time t, Real strike) const =0
Black variance calculation.
virtual Volatility blackVolImpl (Time t, Real strike) const =0
Black volatility calculation.
Static Private Attributes
static const Time dT = 1.0/365.0
Detailed Description
Black-volatility term structure.
This abstract class defines the interface of concrete Black-volatility term structures which will be derived from this one.
Volatilities are assumed to be expressed on an annual basis.
Definition at line 40 of file blackvoltermstructure.hpp.
Constructor & Destructor Documentation
QuantLib::BlackVolTermStructure::BlackVolTermStructure (const Calendar & cal, BusinessDayConvention bdc = Following, const DayCounter & dc = DayCounter())
Warning:
term structures initialized by means of this constructor must manage their own reference date by overriding the referenceDate() method.
Definition at line 27 of file blackvoltermstructure.cpp.
    : VolatilityTermStructure(cal, bdc, dc) {}
QuantLib::BlackVolTermStructure::BlackVolTermStructure (BusinessDayConvention bdc = Following, const DayCounter & dc = DayCounter())
default constructor
Warning:
term structures initialized by means of this constructor must manage their own reference date by overriding the referenceDate() method.
Definition at line 33 of file blackvoltermstructure.cpp.
    : VolatilityTermStructure(bdc, dc) {}
QuantLib::BlackVolTermStructure::BlackVolTermStructure (const Date & referenceDate, const Calendar & cal = Calendar(), BusinessDayConvention bdc = Following, const DayCounter & dc = DayCounter())
initialize with a fixed reference date
Definition at line 37 of file blackvoltermstructure.cpp.
    : VolatilityTermStructure(refDate, cal, bdc, dc) {}
QuantLib::BlackVolTermStructure::BlackVolTermStructure (Natural settlementDays, const Calendar & cal, BusinessDayConvention bdc = Following, const DayCounter & dc = DayCounter())
calculate the reference date based on the global evaluation date
Definition at line 43 of file blackvoltermstructure.cpp.
    : VolatilityTermStructure(settlDays, cal, bdc, dc) {}
virtual QuantLib::BlackVolTermStructure::~BlackVolTermStructure () [inline, virtual]
Definition at line 74 of file blackvoltermstructure.hpp.
{}
Member Function Documentation
void QuantLib::BlackVolTermStructure::accept (AcyclicVisitor & v) [inline, virtual]
Reimplemented in QuantLib::BlackVarianceTermStructure, QuantLib::BlackVolatilityTermStructure, QuantLib::BlackVarianceSurface, QuantLib::BlackVarianceCurve, QuantLib::BlackConstantVol, QuantLib::ExtendedBlackVarianceSurface, QuantLib::ExtendedBlackVarianceCurve, and QuantLib::ImpliedVolTermStructure.
Definition at line 281 of file blackvoltermstructure.hpp.
References QL_FAIL, anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Visitor< T >::visit().
{
        Visitor<BlackVolTermStructure>* v1 =
            dynamic_cast<Visitor<BlackVolTermStructure>*>(&v);
        if (v1 != 0)
            v1->visit(*this);
        else
            QL_FAIL("not a Black-volatility term structure visitor");
    }
Real QuantLib::BlackVolTermStructure::blackForwardVariance (const Date & date1, const Date & date2, Real strike, bool extrapolate = false) const
forward (at-the-money) variance
Definition at line 94 of file blackvoltermstructure.cpp.
References blackForwardVariance(), QuantLib::TermStructure::checkRange(), QL_REQUIRE, and QuantLib::TermStructure::timeFromReference().
Referenced by blackForwardVariance().
{
        // (redundant) date-based checks
        QL_REQUIRE(date1 <= date2,
                   date1 << " later than " << date2);
        checkRange(date2, extrapolate);
        // using the time implementation
        Time time1 = timeFromReference(date1);
        Time time2 = timeFromReference(date2);
        return blackForwardVariance(time1, time2, strike, extrapolate);
    }
Real QuantLib::BlackVolTermStructure::blackForwardVariance (Time time1, Time time2, Real strike, bool extrapolate = false) const
forward (at-the-money) variance
Definition at line 110 of file blackvoltermstructure.cpp.
References blackVarianceImpl(), QuantLib::TermStructure::checkRange(), QuantLib::VolatilityTermStructure::checkStrike(), QL_ENSURE, and QL_REQUIRE.
{
        QL_REQUIRE(time1 <= time2,
                   time1 << " later than " << time2);
        checkRange(time2, extrapolate);
        checkStrike(strike, extrapolate);
        Real v1 = blackVarianceImpl(time1, strike);
        Real v2 = blackVarianceImpl(time2, strike);
        QL_ENSURE(v2 >= v1,
                  "variances must be non-decreasing");
        return v2-v1;
    }
Volatility QuantLib::BlackVolTermStructure::blackForwardVol (const Date & date1, const Date & date2, Real strike, bool extrapolate = false) const
forward (at-the-money) volatility
Definition at line 49 of file blackvoltermstructure.cpp.
References QuantLib::TermStructure::checkRange(), QL_REQUIRE, and QuantLib::TermStructure::timeFromReference().
{
        // (redundant) date-based checks
        QL_REQUIRE(date1 <= date2,
                   date1 << " later than " << date2);
        checkRange(date2, extrapolate);
        // using the time implementation
        Time time1 = timeFromReference(date1);
        Time time2 = timeFromReference(date2);
        return blackForwardVol(time1, time2, strike, extrapolate);
    }
Volatility QuantLib::BlackVolTermStructure::blackForwardVol (Time time1, Time time2, Real strike, bool extrapolate = false) const
forward (at-the-money) volatility
Definition at line 64 of file blackvoltermstructure.cpp.
References blackVarianceImpl(), QuantLib::TermStructure::checkRange(), QuantLib::VolatilityTermStructure::checkStrike(), QL_ENSURE, and QL_REQUIRE.
{
        QL_REQUIRE(time1 <= time2,
                   time1 << " later than " << time2);
        checkRange(time2, extrapolate);
        checkStrike(strike, extrapolate);
        if (time2==time1) {
            if (time1==0.0) {
                Time epsilon = 1.0e-5;
                Real var = blackVarianceImpl(epsilon, strike);
                return std::sqrt(var/epsilon);
            } else {
                Time epsilon = std::min<Time>(1.0e-5, time1);
                Real var1 = blackVarianceImpl(time1-epsilon, strike);
                Real var2 = blackVarianceImpl(time1+epsilon, strike);
                QL_ENSURE(var2>=var1,
                          "variances must be non-decreasing");
                return std::sqrt((var2-var1)/(2*epsilon));
            }
        } else {
            Real var1 = blackVarianceImpl(time1, strike);
            Real var2 = blackVarianceImpl(time2, strike);
            QL_ENSURE(var2 >= var1,
                      "variances must be non-decreasing");
            return std::sqrt((var2-var1)/(time2-time1));
        }
    }
Real QuantLib::BlackVolTermStructure::blackVariance (const Date & maturity, Real strike, bool extrapolate = false) const [inline]
spot variance
Definition at line 264 of file blackvoltermstructure.hpp.
References blackVarianceImpl(), QuantLib::TermStructure::checkRange(), QuantLib::VolatilityTermStructure::checkStrike(), anonymous_namespace{quantlibbenchmark.cpp}::t, and QuantLib::TermStructure::timeFromReference().
{
        checkRange(d, extrapolate);
        checkStrike(strike, extrapolate);
        Time t = timeFromReference(d);
        return blackVarianceImpl(t, strike);
    }
Real QuantLib::BlackVolTermStructure::blackVariance (Time maturity, Real strike, bool extrapolate = false) const [inline]
spot variance
Definition at line 273 of file blackvoltermstructure.hpp.
References blackVarianceImpl(), QuantLib::TermStructure::checkRange(), and QuantLib::VolatilityTermStructure::checkStrike().
{
        checkRange(t, extrapolate);
        checkStrike(strike, extrapolate);
        return blackVarianceImpl(t, strike);
    }
virtual Real QuantLib::BlackVolTermStructure::blackVarianceImpl (Time t, Real strike) const [protected, pure virtual]
Black variance calculation.
Implemented in QuantLib::BlackVolatilityTermStructure, QuantLib::BlackVarianceSurface, QuantLib::BlackVarianceCurve, QuantLib::ExtendedBlackVarianceSurface, QuantLib::ExtendedBlackVarianceCurve, QuantLib::ImpliedVolTermStructure, and QuantLib::anonymous_namespace{analyticbsmhullwhiteengine.cpp}::ShiftedBlackVolTermStructure.
Referenced by blackForwardVariance(), blackForwardVol(), blackVariance(), and QuantLib::BlackVarianceTermStructure::blackVolImpl().
Volatility QuantLib::BlackVolTermStructure::blackVol (const Date & maturity, Real strike, bool extrapolate = false) const [inline]
spot volatility
Definition at line 247 of file blackvoltermstructure.hpp.
References blackVolImpl(), QuantLib::TermStructure::checkRange(), QuantLib::VolatilityTermStructure::checkStrike(), anonymous_namespace{quantlibbenchmark.cpp}::t, and QuantLib::TermStructure::timeFromReference().
Referenced by QuantLib::CapletVarianceCurve::smileSectionImpl(), and QuantLib::CapletVarianceCurve::volatilityImpl().
{
        checkRange(d, extrapolate);
        checkStrike(strike, extrapolate);
        Time t = timeFromReference(d);
        return blackVolImpl(t, strike);
    }
Volatility QuantLib::BlackVolTermStructure::blackVol (Time maturity, Real strike, bool extrapolate = false) const [inline]
spot volatility
Definition at line 256 of file blackvoltermstructure.hpp.
References blackVolImpl(), QuantLib::TermStructure::checkRange(), and QuantLib::VolatilityTermStructure::checkStrike().
{
        checkRange(t, extrapolate);
        checkStrike(strike, extrapolate);
        return blackVolImpl(t, strike);
    }
virtual Volatility QuantLib::BlackVolTermStructure::blackVolImpl (Time t, Real strike) const [protected, pure virtual]
Black volatility calculation.
Implemented in QuantLib::BlackVarianceTermStructure, QuantLib::BlackConstantVol, and QuantLib::anonymous_namespace{analyticbsmhullwhiteengine.cpp}::ShiftedBlackVolTermStructure.
Referenced by QuantLib::BlackVolatilityTermStructure::blackVarianceImpl(), and blackVol().
Member Data Documentation
const Time QuantLib::BlackVolTermStructure::dT = 1.0/365.0 [static, private]
Definition at line 133 of file blackvoltermstructure.hpp.
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/equityfx/blackvoltermstructure.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/equityfx/blackvoltermstructure.cpp