QuantLib: QuantLib::Integrator Class Reference
QuantLib::Integrator Class Reference
#include <integral.hpp>
Public Member Functions
Integrator (Real absoluteAccuracy, Size maxEvaluations)
virtual ~Integrator ()
Real operator() (const boost::function< Real(Real)> &f, Real a, Real b) const
Real absoluteError () const
Size numberOfEvaluations () const
virtual bool integrationSuccess () const
Modifiers
void setAbsoluteAccuracy (Real)
void setMaxEvaluations (Size)
Inspectors
Real absoluteAccuracy () const
Size maxEvaluations () const
Protected Member Functions
virtual Real integrate (const boost::function< Real(Real)> &f, Real a, Real b) const =0
void setAbsoluteError (Real error) const
void setNumberOfEvaluations (Size evaluations) const
void increaseNumberOfEvaluations (Size increase) const
Private Attributes
Real absoluteAccuracy_
Real absoluteError_
Size maxEvaluations_
Size evaluations_
Detailed Description
Definition at line 30 of file integral.hpp.
Constructor & Destructor Documentation
QuantLib::Integrator::Integrator (Real absoluteAccuracy, Size maxEvaluations)
Definition at line 25 of file integral.cpp.
References QL_EPSILON, and QL_REQUIRE.
    : absoluteAccuracy_(absoluteAccuracy),
      maxEvaluations_(maxEvaluations) {
        QL_REQUIRE(absoluteAccuracy > QL_EPSILON,
                   std::scientific << "required tolerance (" <<
                   absoluteAccuracy << ") not allowed. It must be > " <<
                   QL_EPSILON);
    }
virtual QuantLib::Integrator::~Integrator () [inline, virtual]
Definition at line 34 of file integral.hpp.
{}
Member Function Documentation
Real QuantLib::Integrator::absoluteAccuracy () const
Definition at line 43 of file integral.cpp.
References absoluteAccuracy_.
Referenced by QuantLib::GaussLobattoIntegral::calculateAbsTolerance(), QuantLib::SimpsonIntegral::integrate(), QuantLib::TrapezoidIntegral< Default >::integrate(), QuantLib::GaussKronrodNonAdaptive::integrate(), and QuantLib::GaussKronrodAdaptive::integrate().
{
        return absoluteAccuracy_;
    }
Real QuantLib::Integrator::absoluteError () const
Definition at line 51 of file integral.cpp.
References absoluteError_.
{
        return absoluteError_;
    }
void QuantLib::Integrator::increaseNumberOfEvaluations (Size increase) const [protected]
Definition at line 67 of file integral.cpp.
References evaluations_.
Referenced by QuantLib::GaussLobattoIntegral::adaptivGaussLobattoStep(), QuantLib::GaussLobattoIntegral::calculateAbsTolerance(), QuantLib::GaussLobattoIntegral::integrate(), and QuantLib::GaussKronrodAdaptive::integrateRecursively().
{
        evaluations_ += increase;
    }
virtual Real QuantLib::Integrator::integrate (const boost::function< Real(Real)> & f, Real a, Real b) const [protected, pure virtual]
Implemented in QuantLib::GaussKronrodAdaptive, QuantLib::GaussKronrodNonAdaptive, QuantLib::TrapezoidIntegral< IntegrationPolicy >, QuantLib::TrapezoidIntegral< Default >, QuantLib::GaussLobattoIntegral, QuantLib::SegmentIntegral, and QuantLib::SimpsonIntegral.
Referenced by operator()().
bool QuantLib::Integrator::integrationSuccess () const [virtual]
Definition at line 71 of file integral.cpp.
References absoluteAccuracy_, absoluteError_, evaluations_, and maxEvaluations_.
Referenced by QuantLib::NumericHaganPricer::integrate().
{
        return evaluations_ <= maxEvaluations_
            && absoluteError_ <= absoluteAccuracy_;
    }
Size QuantLib::Integrator::maxEvaluations () const
Definition at line 47 of file integral.cpp.
References maxEvaluations_.
Referenced by QuantLib::GaussLobattoIntegral::adaptivGaussLobattoStep(), QuantLib::SimpsonIntegral::integrate(), QuantLib::TrapezoidIntegral< Default >::integrate(), QuantLib::GaussKronrodAdaptive::integrateRecursively(), and setMaxEvaluations().
{
        return maxEvaluations_;
    }
Size QuantLib::Integrator::numberOfEvaluations () const
Definition at line 59 of file integral.cpp.
References evaluations_.
Referenced by QuantLib::GaussLobattoIntegral::adaptivGaussLobattoStep(), and QuantLib::GaussKronrodAdaptive::integrateRecursively().
{
        return evaluations_;
    }
Real QuantLib::Integrator::operator() (const boost::function< Real(Real)> & f, Real a, Real b) const
Definition at line 76 of file integral.cpp.
References evaluations_, anonymous_namespace{interpolations.cpp}::f(), and integrate().
{
        evaluations_ = 0;
        if (a == b)
            return 0.0;
        if (b > a)
            return integrate(f, a, b);
        else
            return -integrate(f, b, a);
    }
void QuantLib::Integrator::setAbsoluteAccuracy (Real accuracy)
Definition at line 35 of file integral.cpp.
References absoluteAccuracy_.
{
        absoluteAccuracy_= accuracy;
    }
void QuantLib::Integrator::setAbsoluteError (Real error) const [protected]
Definition at line 55 of file integral.cpp.
References absoluteError_.
Referenced by QuantLib::GaussKronrodNonAdaptive::integrate().
{
        absoluteError_ = error;
    }
void QuantLib::Integrator::setMaxEvaluations (Size maxEvaluations)
Definition at line 39 of file integral.cpp.
References maxEvaluations(), and maxEvaluations_.
{
        maxEvaluations_ = maxEvaluations;
    }
void QuantLib::Integrator::setNumberOfEvaluations (Size evaluations) const [protected]
Definition at line 63 of file integral.cpp.
References evaluations_.
Referenced by QuantLib::GaussLobattoIntegral::integrate(), and QuantLib::GaussKronrodNonAdaptive::integrate().
{
        evaluations_ = evaluations;
    }
Member Data Documentation
Real QuantLib::Integrator::absoluteAccuracy_ [private]
Definition at line 66 of file integral.hpp.
Referenced by absoluteAccuracy(), integrationSuccess(), and setAbsoluteAccuracy().
Real QuantLib::Integrator::absoluteError_ [mutable, private]
Definition at line 67 of file integral.hpp.
Referenced by absoluteError(), integrationSuccess(), and setAbsoluteError().
Size QuantLib::Integrator::evaluations_ [mutable, private]
Definition at line 69 of file integral.hpp.
Referenced by increaseNumberOfEvaluations(), integrationSuccess(), numberOfEvaluations(), operator()(), and setNumberOfEvaluations().
Size QuantLib::Integrator::maxEvaluations_ [private]
Definition at line 68 of file integral.hpp.
Referenced by integrationSuccess(), maxEvaluations(), and setMaxEvaluations().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/integrals/integral.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/math/integrals/integral.cpp