QuantLib: QuantLib::FixedRateLeg Class Reference
QuantLib::FixedRateLeg Class Reference
helper class building a sequence of fixed rate coupons
#include <fixedratecoupon.hpp>
Public Member Functions
FixedRateLeg (const Schedule &schedule)
FixedRateLeg & withNotionals (Real)
FixedRateLeg & withNotionals (const std::vector< Real > &)
FixedRateLeg & withCouponRates (Rate, const DayCounter &paymentDayCounter, Compounding comp=Simple, Frequency freq=Annual)
FixedRateLeg & withCouponRates (const std::vector< Rate > &, const DayCounter &paymentDayCounter, Compounding comp=Simple, Frequency freq=Annual)
FixedRateLeg & withCouponRates (const InterestRate &)
FixedRateLeg & withCouponRates (const std::vector< InterestRate > &)
FixedRateLeg & withPaymentAdjustment (BusinessDayConvention)
FixedRateLeg & withFirstPeriodDayCounter (const DayCounter &)
FixedRateLeg & withPaymentCalendar (const Calendar &)
operator Leg () const
Private Attributes
Schedule schedule_
Calendar calendar_
std::vector< Real > notionals_
std::vector< InterestRate > couponRates_
DayCounter firstPeriodDC_
BusinessDayConvention paymentAdjustment_
Detailed Description
helper class building a sequence of fixed rate coupons
Definition at line 80 of file fixedratecoupon.hpp.
Constructor & Destructor Documentation
QuantLib::FixedRateLeg::FixedRateLeg (const Schedule & schedule)
Definition at line 73 of file fixedratecoupon.cpp.
    : schedule_(schedule), calendar_(schedule.calendar()),
      paymentAdjustment_(Following) {}
Member Function Documentation
QuantLib::FixedRateLeg::operator Leg () const
Definition at line 135 of file fixedratecoupon.cpp.
References QuantLib::Calendar::adjust(), QuantLib::Schedule::businessDayConvention(), QuantLib::Schedule::calendar(), calendar_, QuantLib::InterestRate::compounding(), couponRates_, QuantLib::Schedule::date(), QuantLib::InterestRate::dayCounter(), QuantLib::DayCounter::empty(), firstPeriodDC_, QuantLib::InterestRate::frequency(), QuantLib::Schedule::isRegular(), anonymous_namespace{matrices.cpp}::N, notionals_, paymentAdjustment_, QL_REQUIRE, QuantLib::InterestRate::rate(), QuantLib::io::rate(), schedule_, QuantLib::Schedule::size(), and QuantLib::Schedule::tenor().
{
        QL_REQUIRE(!couponRates_.empty(), "no coupon rates given");
        QL_REQUIRE(!notionals_.empty(), "no notional given");
        Leg leg;
        leg.reserve(schedule_.size()-1);
        Calendar schCalendar = schedule_.calendar();
        // first period might be short or long
        Date start = schedule_.date(0), end = schedule_.date(1);
        Date paymentDate = calendar_.adjust(end, paymentAdjustment_);
        InterestRate rate = couponRates_[0];
        Real nominal = notionals_[0];
        if (schedule_.isRegular(1)) {
            QL_REQUIRE(firstPeriodDC_.empty() ||
                       firstPeriodDC_ == rate.dayCounter(),
                       "regular first coupon "
                       "does not allow a first-period day count");
            shared_ptr<CashFlow> temp(new
                FixedRateCoupon(paymentDate, nominal, rate,
                                start, end, start, end));
            leg.push_back(temp);
        } else {
            Date ref = end - schedule_.tenor();
            ref = schCalendar.adjust(ref, schedule_.businessDayConvention());
            InterestRate r(rate.rate(),
                           firstPeriodDC_.empty() ? rate.dayCounter()
                                                  : firstPeriodDC_,
                           rate.compounding(), rate.frequency());
            leg.push_back(shared_ptr<CashFlow>(new
                FixedRateCoupon(paymentDate, nominal, r,
                                start, end, ref, end)));
        }
        // regular periods
        for (Size i=2; i<schedule_.size()-1; ++i) {
            start = end; end = schedule_.date(i);
            paymentDate = calendar_.adjust(end, paymentAdjustment_);
            if ((i-1) < couponRates_.size())
                rate = couponRates_[i-1];
            else
                rate = couponRates_.back();
            if ((i-1) < notionals_.size())
                nominal = notionals_[i-1];
            else
                nominal = notionals_.back();
            leg.push_back(shared_ptr<CashFlow>(new
                FixedRateCoupon(paymentDate, nominal, rate,
                                start, end, start, end)));
        }
        if (schedule_.size() > 2) {
            // last period might be short or long
            Size N = schedule_.size();
            start = end; end = schedule_.date(N-1);
            paymentDate = calendar_.adjust(end, paymentAdjustment_);
            if ((N-2) < couponRates_.size())
                rate = couponRates_[N-2];
            else
                rate = couponRates_.back();
            if ((N-2) < notionals_.size())
                nominal = notionals_[N-2];
            else
                nominal = notionals_.back();
            if (schedule_.isRegular(N-1)) {
                leg.push_back(shared_ptr<CashFlow>(new
                    FixedRateCoupon(paymentDate, nominal, rate,
                                    start, end, start, end)));
            } else {
                Date ref = start + schedule_.tenor();
                ref = schCalendar.adjust(ref, schedule_.businessDayConvention());
                leg.push_back(shared_ptr<CashFlow>(new
                    FixedRateCoupon(paymentDate, nominal, rate,
                                    start, end, start, ref)));
            }
        }
        return leg;
    }
FixedRateLeg & QuantLib::FixedRateLeg::withCouponRates (Rate rate, const DayCounter & paymentDayCounter, Compounding comp = Simple, Frequency freq = Annual)
Definition at line 87 of file fixedratecoupon.cpp.
References couponRates_.
Referenced by QuantLib::AmortizingFixedRateBond::AmortizingFixedRateBond(), QuantLib::MidPointCDOEngine::calculate(), QuantLib::MonteCarloCDOEngine2::calculate(), QuantLib::CallableFixedRateBond::CallableFixedRateBond(), QuantLib::CapHelper::CapHelper(), QuantLib::ConvertibleFixedCouponBond::ConvertibleFixedCouponBond(), QuantLib::CreditDefaultSwap::CreditDefaultSwap(), QuantLib::FixedRateBond::FixedRateBond(), QuantLib::OvernightIndexedSwap::initialize(), anonymous_namespace{capflooredcoupon.cpp}::CommonVars::makeFixedLeg(), anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::makeFixedLeg(), QuantLib::NthToDefault::NthToDefault(), AssetSwapTest::testGenericBondImplied(), SwapTest::testInArrears(), AssetSwapTest::testMASWWithGenericBond(), AssetSwapTest::testSpecializedBondVsGenericBond(), AssetSwapTest::testSpecializedBondVsGenericBondUsingAsw(), AssetSwapTest::testZSpreadWithGenericBond(), QuantLib::VanillaSwap::VanillaSwap(), and QuantLib::YearOnYearInflationSwap::YearOnYearInflationSwap().
{
        couponRates_.resize(1);
        couponRates_[0] = InterestRate(rate, dc, comp, freq);
        return *this;
    }
FixedRateLeg & QuantLib::FixedRateLeg::withCouponRates (const std::vector< Rate > & rates, const DayCounter & paymentDayCounter, Compounding comp = Simple, Frequency freq = Annual)
Definition at line 102 of file fixedratecoupon.cpp.
References couponRates_.
{
        couponRates_.resize(rates.size());
        for (Size i=0; i<rates.size(); ++i)
            couponRates_[i] = InterestRate(rates[i], dc, comp, freq);
        return *this;
    }
FixedRateLeg & QuantLib::FixedRateLeg::withCouponRates (const InterestRate & i)
Definition at line 96 of file fixedratecoupon.cpp.
References couponRates_.
{
        couponRates_.resize(1);
        couponRates_[0] = i;
        return *this;
    }
FixedRateLeg & QuantLib::FixedRateLeg::withCouponRates (const std::vector< InterestRate > & interestRates)
Definition at line 112 of file fixedratecoupon.cpp.
References couponRates_.
{
        couponRates_ = interestRates;
        return *this;
    }
FixedRateLeg & QuantLib::FixedRateLeg::withFirstPeriodDayCounter (const DayCounter & dayCounter)
Definition at line 124 of file fixedratecoupon.cpp.
References anonymous_namespace{marketmodel.cpp}::dayCounter, and firstPeriodDC_.
{
        firstPeriodDC_ = dayCounter;
        return *this;
    }
FixedRateLeg & QuantLib::FixedRateLeg::withNotionals (Real notional)
Definition at line 77 of file fixedratecoupon.cpp.
References notionals_.
Referenced by QuantLib::AmortizingFixedRateBond::AmortizingFixedRateBond(), QuantLib::MidPointCDOEngine::calculate(), QuantLib::MonteCarloCDOEngine2::calculate(), QuantLib::CallableFixedRateBond::CallableFixedRateBond(), QuantLib::CapHelper::CapHelper(), QuantLib::ConvertibleFixedCouponBond::ConvertibleFixedCouponBond(), QuantLib::CreditDefaultSwap::CreditDefaultSwap(), QuantLib::FixedRateBond::FixedRateBond(), QuantLib::OvernightIndexedSwap::initialize(), anonymous_namespace{capflooredcoupon.cpp}::CommonVars::makeFixedLeg(), anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::makeFixedLeg(), QuantLib::NthToDefault::NthToDefault(), AssetSwapTest::testGenericBondImplied(), SwapTest::testInArrears(), AssetSwapTest::testMASWWithGenericBond(), AssetSwapTest::testSpecializedBondVsGenericBond(), AssetSwapTest::testSpecializedBondVsGenericBondUsingAsw(), AssetSwapTest::testZSpreadWithGenericBond(), QuantLib::VanillaSwap::VanillaSwap(), and QuantLib::YearOnYearInflationSwap::YearOnYearInflationSwap().
{
        notionals_ = vector<Real>(1,notional);
        return *this;
    }
FixedRateLeg & QuantLib::FixedRateLeg::withNotionals (const std::vector< Real > & notionals)
Definition at line 82 of file fixedratecoupon.cpp.
References notionals_.
{
        notionals_ = notionals;
        return *this;
    }
FixedRateLeg & QuantLib::FixedRateLeg::withPaymentAdjustment (BusinessDayConvention convention)
Definition at line 118 of file fixedratecoupon.cpp.
References paymentAdjustment_.
Referenced by QuantLib::AmortizingFixedRateBond::AmortizingFixedRateBond(), QuantLib::MidPointCDOEngine::calculate(), QuantLib::MonteCarloCDOEngine2::calculate(), QuantLib::CallableFixedRateBond::CallableFixedRateBond(), QuantLib::CapHelper::CapHelper(), QuantLib::ConvertibleFixedCouponBond::ConvertibleFixedCouponBond(), QuantLib::CreditDefaultSwap::CreditDefaultSwap(), QuantLib::FixedRateBond::FixedRateBond(), QuantLib::NthToDefault::NthToDefault(), QuantLib::VanillaSwap::VanillaSwap(), and QuantLib::YearOnYearInflationSwap::YearOnYearInflationSwap().
{
        paymentAdjustment_ = convention;
        return *this;
    }
FixedRateLeg & QuantLib::FixedRateLeg::withPaymentCalendar (const Calendar & cal)
Definition at line 130 of file fixedratecoupon.cpp.
References calendar_.
Referenced by QuantLib::FixedRateBond::FixedRateBond().
{
        calendar_ = cal;
        return *this;
    }
Member Data Documentation
Calendar QuantLib::FixedRateLeg::calendar_ [private]
Definition at line 101 of file fixedratecoupon.hpp.
Referenced by operator Leg(), and withPaymentCalendar().
std::vector<InterestRate> QuantLib::FixedRateLeg::couponRates_ [private]
Definition at line 103 of file fixedratecoupon.hpp.
Referenced by operator Leg(), and withCouponRates().
DayCounter QuantLib::FixedRateLeg::firstPeriodDC_ [private]
Definition at line 104 of file fixedratecoupon.hpp.
Referenced by operator Leg(), and withFirstPeriodDayCounter().
std::vector<Real> QuantLib::FixedRateLeg::notionals_ [private]
Definition at line 102 of file fixedratecoupon.hpp.
Referenced by operator Leg(), and withNotionals().
BusinessDayConvention QuantLib::FixedRateLeg::paymentAdjustment_ [private]
Definition at line 105 of file fixedratecoupon.hpp.
Referenced by operator Leg(), and withPaymentAdjustment().
Schedule QuantLib::FixedRateLeg::schedule_ [private]
Definition at line 100 of file fixedratecoupon.hpp.
Referenced by operator Leg().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/fixedratecoupon.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/fixedratecoupon.cpp