QuantLib: QuantLib::Distribution Class Reference
QuantLib::Distribution Class Reference
#include <distribution.hpp>
Public Member Functions
Distribution (int nBuckets, Real xmin, Real xmax)
Distribution ()
void add (Real value)
void addDensity (int bucket, Real value)
void addAverage (int bucket, Real value)
void normalize ()
Size size () const
Real x (Size k)
std::vector< Real > & x ()
Real dx (Size k)
std::vector< Real > & dx ()
Real dx (Real x)
Real density (Size k)
Real cumulative (Size k)
Real excess (Size k)
Real cumulativeExcess (Size k)
Real average (Size k)
Real confidenceLevel (Real quantil)
Real cumulativeDensity (Real x)
Real cumulativeExcessProbability (Real a, Real b)
Real expectedValue ()
Real trancheExpectedValue (Real a, Real d)
template<class F >
Real expectedValue (F &f)
void tranche (Real attachmentPoint, Real detachmentPoint)
int locate (Real x)
Private Attributes
int size_
Real xmin_
Real xmax_
std::vector< int > count_
std::vector< Real > x_
std::vector< Real > dx_
std::vector< Real > density_
std::vector< Real > cumulativeDensity_
std::vector< Real > excessProbability_
std::vector< Real > cumulativeExcessProbability_
std::vector< Real > average_
int overFlow_
int underFlow_
bool isNormalized_
Friends
class ManipulateDistribution
Detailed Description
Definition at line 37 of file distribution.hpp.
Constructor & Destructor Documentation
QuantLib::Distribution::Distribution (int nBuckets, Real xmin, Real xmax)
Definition at line 31 of file distribution.cpp.
References dx_, and x_.
        : size_(nBuckets),
          xmin_(xmin), xmax_(xmax), count_(nBuckets),
          x_(nBuckets,0), dx_(nBuckets,0),
          density_(nBuckets,0),
          cumulativeDensity_(nBuckets,0),
          excessProbability_(nBuckets,0),
          cumulativeExcessProbability_(nBuckets,0),
          average_(nBuckets,0),
          overFlow_(0), underFlow_(0),
          isNormalized_(false) {
        for (int i = 0; i < nBuckets; i++) {
            dx_[i] = (xmax - xmin) / nBuckets;
            x_[i] = (i == 0 ? xmin : x_[i-1] + dx_[i-1]);
        }
        // ensure we match exactly the domain, otherwise we might fail the
        //   locate test because of precission mismatches
        dx_.back() = xmax - x_.back();
    }
QuantLib::Distribution::Distribution () [inline]
Definition at line 41 of file distribution.hpp.
{};
Member Function Documentation
void QuantLib::Distribution::add (Real value)
Definition at line 76 of file distribution.cpp.
References average_, count_, dx_, isNormalized_, overFlow_, underFlow_, and x_.
Referenced by QuantLib::LossDistMonteCarlo::operator()().
{
    //-------------------------------------------------------------------------
        isNormalized_ = false;
        if (value < x_.front()) underFlow_++;
        else {
            for (Size i = 0; i < count_.size(); i++) {
                if (x_[i] + dx_[i] > value) {
                    count_[i]++;
                    average_[i] += value;
                    return;
                }
            }
            overFlow_++;
        }
    }
void QuantLib::Distribution::addAverage (int bucket, Real value)
Definition at line 101 of file distribution.cpp.
References average_, isNormalized_, QL_REQUIRE, and size_.
Referenced by QuantLib::LossDistBinomial::operator()(), QuantLib::LossDistHomogeneous::operator()(), and QuantLib::LossDistBucketing::operator()().
{
    //-------------------------------------------------------------------------
        QL_REQUIRE (bucket >= 0 && bucket < size_, "bucket out of range");
        isNormalized_ = false;
        average_[bucket] += value;
    }
void QuantLib::Distribution::addDensity (int bucket, Real value)
Definition at line 93 of file distribution.cpp.
References density_, isNormalized_, QL_REQUIRE, and size_.
Referenced by QuantLib::LossDistBinomial::operator()(), QuantLib::LossDistHomogeneous::operator()(), and QuantLib::LossDistBucketing::operator()().
{
    //-------------------------------------------------------------------------
        QL_REQUIRE (bucket >= 0 && bucket < size_, "bucket out of range");
        isNormalized_ = false;
        density_[bucket] += value;
    }
Real QuantLib::Distribution::average (Size k) [inline]
Definition at line 71 of file distribution.hpp.
References average_.
{ return average_.at(k); }
Real QuantLib::Distribution::confidenceLevel (Real quantil)
Definition at line 149 of file distribution.cpp.
References cumulativeDensity_, dx_, normalize(), size_, and x_.
{
    //-------------------------------------------------------------------------
        normalize();
        for (int i = 0; i < size_; i++) {
            if (cumulativeDensity_[i] > quantil)
                return x_[i] + dx_[i];
        }
        return x_.back() + dx_.back();
    }
Real QuantLib::Distribution::cumulative (Size k) [inline]
Definition at line 59 of file distribution.hpp.
References cumulativeDensity_, and normalize().
{
            normalize();
            return cumulativeDensity_.at(k);
        }
Real QuantLib::Distribution::cumulativeDensity (Real x)
Definition at line 226 of file distribution.cpp.
References cumulativeDensity_, dx_, normalize(), QL_FAIL, QL_REQUIRE, size_, and x_.
Referenced by trancheExpectedValue().
{
    //-------------------------------------------------------------------------
        Real tiny = dx_.back() * 1e-3;
        QL_REQUIRE (x > 0, "x must be positive");
        normalize();
        for (int i = 0; i < size_; i++) {
            if (x_[i] + dx_[i] + tiny >= x)
                return ((x - x_[i]) * cumulativeDensity_[i]
                     + (x_[i] + dx_[i] - x) * cumulativeDensity_[i-1]) / dx_[i];
        }
        QL_FAIL ("x = " << x << " beyond distribution cutoff "
                 << x_.back() + dx_.back());
    }
Real QuantLib::Distribution::cumulativeExcess (Size k) [inline]
Definition at line 67 of file distribution.hpp.
References cumulativeExcessProbability_, and normalize().
{
            normalize();
            return cumulativeExcessProbability_.at(k);
        }
Real QuantLib::Distribution::cumulativeExcessProbability (Real a, Real b)
Definition at line 202 of file distribution.cpp.
References cumulativeExcessProbability_, dx_, excessProbability_, locate(), normalize(), QL_REQUIRE, size_, x_, xmax_, and xmin_.
Referenced by QuantLib::HomogeneousPoolCDOEngine< CDOEngine >::expectedTrancheLoss(), and QuantLib::InhomogeneousPoolCDOEngine< CDOEngine >::expectedTrancheLoss().
{
    //-------------------------------------------------------------------------
        normalize();
        QL_REQUIRE (b <= xmax_,
                 "end of interval " << b << " out of range ["
                 << xmin_ << ", " << xmax_ << "]");
        QL_REQUIRE (a >= xmin_,
                 "start of interval " << a << " out of range ["
                 << xmin_ << ", " << xmax_ << "]");
        int i = locate (a);
        int j = locate (b);
        return cumulativeExcessProbability_[j]-cumulativeExcessProbability_[i];
        Real integral = 0.0;
        for (int i = 0; i < size_; i++) {
            if (x_[i] >= b) break;
            if (x_[i] >= a)
                integral += dx_[i] * excessProbability_[i];
        }
        return integral;
    }
Real QuantLib::Distribution::density (Size k) [inline]
Definition at line 55 of file distribution.hpp.
References density_, and normalize().
Referenced by QuantLib::OneFactorCopula::integral().
{
            normalize();
            return density_.at(k);
        }
Real QuantLib::Distribution::dx (Size k) [inline]
Definition at line 51 of file distribution.hpp.
References dx_.
Referenced by QuantLib::LossDistBinomial::operator()(), and QuantLib::LossDistHomogeneous::operator()().
{ return dx_.at(k); }
std::vector<Real>& QuantLib::Distribution::dx () [inline]
Definition at line 52 of file distribution.hpp.
References dx_.
{ return dx_; }
Real QuantLib::Distribution::dx (Real x)
Definition at line 69 of file distribution.cpp.
References dx_, and locate().
{
    //-------------------------------------------------------------------------
        int i = locate (x);
        return dx_[i];
    }
Real QuantLib::Distribution::excess (Size k) [inline]
Definition at line 63 of file distribution.hpp.
References excessProbability_, and normalize().
{
            normalize();
            return excessProbability_.at(k);
        }
Real QuantLib::Distribution::expectedValue ()
Definition at line 160 of file distribution.cpp.
References density_, dx_, normalize(), size_, x(), and x_.
{
    //-------------------------------------------------------------------------
        normalize();
        Real expected = 0;
        for (int i = 0; i < size_; i++) {
            Real x = x_[i] + dx_[i]/2;
            expected += x * dx_[i] * density_[i];
        }
        return expected;
    }
template<class F > Real QuantLib::Distribution::expectedValue (F & f) [inline]
Definition at line 80 of file distribution.hpp.
References density_, dx_, anonymous_namespace{interpolations.cpp}::f(), normalize(), size_, x(), and x_.
{
            normalize();
            Real expected = 0;
            for (int i = 0; i < size_; i++) {
                Real x = x_[i] + dx_[i]/2;
                expected += f (x) * dx_[i] * density_[i];
            }
            return expected;
        }
int QuantLib::Distribution::locate (Real x)
Definition at line 53 of file distribution.cpp.
References QuantLib::close(), dx_, QL_REQUIRE, and x_.
Referenced by cumulativeExcessProbability(), dx(), QuantLib::LossDistBinomial::operator()(), and QuantLib::LossDistHomogeneous::operator()().
{
    //-------------------------------------------------------------------------
        QL_REQUIRE ((x >= x_.front() || close(x, x_.front())) &&
                    (x <= x_.back() + dx_.back()
                     || close(x, x_.back() + dx_.back())),
                    "coordinate " << x
                    << " out of range [" << x_.front() << "; "
                    << x_.back() + dx_.back() << "]");
        for (Size i = 0; i < x_.size(); i++) {
            if (x_[i] > x)
                return i - 1;
        }
        return x_.size() - 1;
    }
void QuantLib::Distribution::normalize ()
Definition at line 109 of file distribution.cpp.
References average_, count_, cumulativeDensity_, cumulativeExcessProbability_, density_, dx_, excessProbability_, isNormalized_, overFlow_, size_, underFlow_, and x_.
Referenced by confidenceLevel(), cumulative(), cumulativeDensity(), cumulativeExcess(), cumulativeExcessProbability(), density(), excess(), expectedValue(), QuantLib::LossDistBinomial::operator()(), QuantLib::LossDistHomogeneous::operator()(), QuantLib::LossDistMonteCarlo::operator()(), and trancheExpectedValue().
{
    //-------------------------------------------------------------------------
        if (isNormalized_)
            return;
        int count = underFlow_ + overFlow_;
        for (int i = 0; i < size_; i++)
            count += count_[i];
        excessProbability_[0] = 1.0;
        cumulativeExcessProbability_[0] = 0.0;
        for (int i = 0; i < size_; i++) {
            if (count > 0) {
                density_[i] = 1.0 / dx_[i] * count_[i] / count;
                if (count_[i] > 0)
                    average_[i] /= count_[i];
            }
            if (density_[i] == 0.0)
                average_[i] = x_[i] + dx_[i]/2;
            cumulativeDensity_[i] = density_[i] * dx_[i];
            if (i > 0) {
                cumulativeDensity_[i] += cumulativeDensity_[i-1];
                excessProbability_[i] = 1.0 - cumulativeDensity_[i-1];
//                     excessProbability_[i] = excessProbability_[i-1]
//                         - density_[i-1] * dx_[i-1];
//                     cumulativeExcessProbability_[i]
//                         = (excessProbability_[i-1] +
//                            excessProbability_[i]) / 2 * dx_[i-1]
//                         + cumulativeExcessProbability_[i-1];
                cumulativeExcessProbability_[i]
                    = excessProbability_[i-1] * dx_[i-1]
                    + cumulativeExcessProbability_[i-1];
            }
        }
        isNormalized_ = true;
    }
Size QuantLib::Distribution::size () const [inline]
Definition at line 48 of file distribution.hpp.
References size_.
Referenced by QuantLib::ManipulateDistribution::convolve().
{ return size_; }
void QuantLib::Distribution::tranche (Real attachmentPoint, Real detachmentPoint)
Transform the loss distribution into the tranche loss distribution for losses L_T = min(L,D) - min(L,A). The effects are: 1) shift the distribution to the left by A, then 2) cut off at D-A, Pr(L_T > D-A) = 0 3) ensure Pr(L_T >= 0) = 1, i.e. a density spike at L_T = 0
Definition at line 241 of file distribution.cpp.
References count_, cumulativeDensity_, density_, dx_, excessProbability_, QL_REQUIRE, and x_.
{
    //-------------------------------------------------------------------------
        QL_REQUIRE (attachmentPoint < detachmentPoint,
                 "attachment >= detachment point");
        QL_REQUIRE (x_.back() > attachmentPoint && x_.back() > detachmentPoint,
                 "attachment or detachment too large");
        // shift
        while (x_[1] < attachmentPoint) {
            x_.erase(x_.begin());
            dx_.erase(dx_.begin());
            count_.erase(count_.begin());
            density_.erase(density_.begin());
            cumulativeDensity_.erase(cumulativeDensity_.begin());
            excessProbability_.erase(excessProbability_.begin());
        }
        // truncate
        for (Size i = 0; i < x_.size(); i++) {
            x_[i] -= attachmentPoint; // = x_[i-1] + dx_[i-1];
            if (x_[i] > detachmentPoint - attachmentPoint)
                excessProbability_[i] = 0.0;
        }
        // force spike at zero
        excessProbability_[0] = 1.0;
        // update density and cumlated
        for (Size i = 0; i < x_.size(); i++) {
            density_[i] = (excessProbability_[i] - excessProbability_[i+1])
                / dx_[i];
            cumulativeDensity_[i] = density_[i] * dx_[i];
            if (i > 0) cumulativeDensity_[i] += cumulativeDensity_[i-1];
        }
    }
Real QuantLib::Distribution::trancheExpectedValue (Real a, Real d)
Definition at line 172 of file distribution.cpp.
References anonymous_namespace{marketmodel.cpp}::a, cumulativeDensity(), density_, dx_, normalize(), size_, x(), and x_.
Referenced by QuantLib::CDO::expectedTrancheLoss().
{
    //-------------------------------------------------------------------------
        normalize();
        Real expected = 0;
        for (int i = 0; i < size_; i++) {
            Real x = x_[i] + dx_[i]/2;
            if (x < a)
                continue;
            if (x > d)
                break;
            expected += (x - a) * dx_[i] * density_[i];
        }
        expected += (d - a) * (1.0 - cumulativeDensity (d));
        return expected;
    }
Real QuantLib::Distribution::x (Size k) [inline]
Definition at line 49 of file distribution.hpp.
References x_.
{ return x_.at(k); }
std::vector<Real>& QuantLib::Distribution::x () [inline]
Definition at line 50 of file distribution.hpp.
References x_.
Referenced by expectedValue(), and trancheExpectedValue().
{ return x_; }
Friends And Related Function Documentation
friend class ManipulateDistribution [friend]
Definition at line 39 of file distribution.hpp.
Member Data Documentation
std::vector<Real> QuantLib::Distribution::average_ [private]
Definition at line 119 of file distribution.hpp.
Referenced by add(), addAverage(), average(), and normalize().
std::vector<int> QuantLib::Distribution::count_ [private]
Definition at line 108 of file distribution.hpp.
Referenced by add(), normalize(), and tranche().
std::vector<Real> QuantLib::Distribution::cumulativeDensity_ [private]
Definition at line 116 of file distribution.hpp.
Referenced by confidenceLevel(), cumulative(), cumulativeDensity(), normalize(), and tranche().
std::vector<Real> QuantLib::Distribution::cumulativeExcessProbability_ [private]
Definition at line 117 of file distribution.hpp.
Referenced by cumulativeExcess(), cumulativeExcessProbability(), and normalize().
std::vector<Real> QuantLib::Distribution::density_ [private]
Definition at line 116 of file distribution.hpp.
Referenced by addDensity(), QuantLib::ManipulateDistribution::convolve(), density(), expectedValue(), normalize(), tranche(), and trancheExpectedValue().
std::vector<Real> QuantLib::Distribution::dx_ [private]
Definition at line 111 of file distribution.hpp.
Referenced by add(), confidenceLevel(), QuantLib::ManipulateDistribution::convolve(), cumulativeDensity(), cumulativeExcessProbability(), Distribution(), dx(), expectedValue(), locate(), normalize(), tranche(), and trancheExpectedValue().
std::vector<Real> QuantLib::Distribution::excessProbability_ [private]
Definition at line 117 of file distribution.hpp.
Referenced by cumulativeExcessProbability(), excess(), normalize(), and tranche().
bool QuantLib::Distribution::isNormalized_ [private]
Definition at line 122 of file distribution.hpp.
Referenced by add(), addAverage(), addDensity(), and normalize().
int QuantLib::Distribution::overFlow_ [private]
Definition at line 121 of file distribution.hpp.
Referenced by add(), and normalize().
int QuantLib::Distribution::size_ [private]
Definition at line 106 of file distribution.hpp.
Referenced by addAverage(), addDensity(), confidenceLevel(), cumulativeDensity(), cumulativeExcessProbability(), expectedValue(), normalize(), size(), and trancheExpectedValue().
int QuantLib::Distribution::underFlow_ [private]
Definition at line 121 of file distribution.hpp.
Referenced by add(), and normalize().
std::vector<Real> QuantLib::Distribution::x_ [private]
Definition at line 111 of file distribution.hpp.
Referenced by add(), confidenceLevel(), cumulativeDensity(), cumulativeExcessProbability(), Distribution(), expectedValue(), locate(), normalize(), tranche(), trancheExpectedValue(), and x().
Real QuantLib::Distribution::xmax_ [private]
Definition at line 107 of file distribution.hpp.
Referenced by QuantLib::ManipulateDistribution::convolve(), and cumulativeExcessProbability().
Real QuantLib::Distribution::xmin_ [private]
Definition at line 107 of file distribution.hpp.
Referenced by QuantLib::ManipulateDistribution::convolve(), and cumulativeExcessProbability().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/distribution.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/distribution.cpp