QuantLib: QuantLib::TermStructureConsistentModel Class Reference
QuantLib::TermStructureConsistentModel Class Reference
Term-structure consistent model class.
#include <model.hpp>
Public Member Functions
TermStructureConsistentModel (const Handle< YieldTermStructure > &termStructure)
const Handle
< YieldTermStructure > & termStructure () const
Private Attributes
Handle< YieldTermStructure > termStructure_
Detailed Description
Term-structure consistent model class.
This is a base class for models that can reprice exactly any discount bond.
Definition at line 65 of file model.hpp.
Constructor & Destructor Documentation
QuantLib::TermStructureConsistentModel::TermStructureConsistentModel (const Handle< YieldTermStructure > & termStructure) [inline]
Definition at line 67 of file model.hpp.
        : termStructure_(termStructure) {}
Member Function Documentation
const Handle<YieldTermStructure>& QuantLib::TermStructureConsistentModel::termStructure () const [inline]
Definition at line 70 of file model.hpp.
References termStructure_.
Referenced by QuantLib::ExtendedCoxIngersollRoss::A(), QuantLib::HullWhite::A(), QuantLib::G2::A(), QuantLib::AnalyticCapFloorEngine::calculate(), QuantLib::TreeCapFloorEngine::calculate(), QuantLib::TreeCallableFixedRateBondEngine::calculate(), QuantLib::TreeVanillaSwapEngine::calculate(), QuantLib::JamshidianSwaptionEngine::calculate(), QuantLib::TreeSwaptionEngine::calculate(), QuantLib::G2::discount(), QuantLib::HullWhite::discountBondOption(), QuantLib::ExtendedCoxIngersollRoss::discountBondOption(), QuantLib::G2::discountBondOption(), QuantLib::ExtendedCoxIngersollRoss::generateArguments(), QuantLib::HullWhite::generateArguments(), QuantLib::G2::generateArguments(), QuantLib::G2::swaption(), QuantLib::BlackKarasinski::tree(), QuantLib::ExtendedCoxIngersollRoss::tree(), QuantLib::HullWhite::tree(), and QuantLib::GeneralizedHullWhite::tree().
{
            return termStructure_;
        }
Member Data Documentation
Handle<YieldTermStructure> QuantLib::TermStructureConsistentModel::termStructure_ [private]
Definition at line 74 of file model.hpp.
Referenced by termStructure().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/model.hpp