QuantLib: QuantLib::RelativeDateBootstrapHelper< TS > Class Template Reference
QuantLib::RelativeDateBootstrapHelper< TS > Class Template Reference
Bootstrap helper with date schedule relative to global evaluation date.
#include <bootstraphelper.hpp>
Public Member Functions
RelativeDateBootstrapHelper (const Handle< Quote > &quote)
RelativeDateBootstrapHelper (Real quote)
Observer interface
void update ()
Protected Member Functions
virtual void initializeDates ()=0
Protected Attributes
Date evaluationDate_
Detailed Description
template<class TS>
class QuantLib::RelativeDateBootstrapHelper< TS >
Bootstrap helper with date schedule relative to global evaluation date.
Derived classes must takes care of rebuilding the date schedule when the global evaluation date changes
Definition at line 102 of file bootstraphelper.hpp.
Constructor & Destructor Documentation
template<class TS > QuantLib::RelativeDateBootstrapHelper< TS >::RelativeDateBootstrapHelper (const Handle< Quote > & quote)
Definition at line 166 of file bootstraphelper.hpp.
References QuantLib::Settings::evaluationDate(), QuantLib::RelativeDateBootstrapHelper< TS >::evaluationDate_, QuantLib::Singleton< Settings >::instance(), and QuantLib::Observer::registerWith().
    : BootstrapHelper<TS>(quote) {
        this->registerWith(Settings::instance().evaluationDate());
        evaluationDate_ = Settings::instance().evaluationDate();
    }
template<class TS > QuantLib::RelativeDateBootstrapHelper< TS >::RelativeDateBootstrapHelper (Real quote)
Definition at line 174 of file bootstraphelper.hpp.
References QuantLib::Settings::evaluationDate(), QuantLib::RelativeDateBootstrapHelper< TS >::evaluationDate_, QuantLib::Singleton< Settings >::instance(), and QuantLib::Observer::registerWith().
    : BootstrapHelper<TS>(quote) {
        this->registerWith(Settings::instance().evaluationDate());
        evaluationDate_ = Settings::instance().evaluationDate();
    }
Member Function Documentation
template<class TS > virtual void QuantLib::RelativeDateBootstrapHelper< TS >::initializeDates () [protected, pure virtual]
Implemented in QuantLib::BMASwapRateHelper, QuantLib::SwapRateHelper, QuantLib::FraRateHelper, QuantLib::UpfrontCdsHelper, QuantLib::DepositRateHelper, QuantLib::CdsHelper, and QuantLib::OISRateHelper.
Referenced by QuantLib::RelativeDateBootstrapHelper< TS >::update().
template<class TS > void QuantLib::RelativeDateBootstrapHelper< TS >::update () [inline, virtual]
This method must be implemented in derived classes. An instance of Observer does not call this method directly: instead, it will be called by the observables the instance registered with when they need to notify any changes.
Reimplemented from QuantLib::BootstrapHelper< TS >.
Reimplemented in QuantLib::CdsHelper.
Definition at line 108 of file bootstraphelper.hpp.
References QuantLib::Settings::evaluationDate(), QuantLib::RelativeDateBootstrapHelper< TS >::evaluationDate_, QuantLib::RelativeDateBootstrapHelper< TS >::initializeDates(), and QuantLib::Singleton< Settings >::instance().
                      {
            if (evaluationDate_ != Settings::instance().evaluationDate()) {
                evaluationDate_ = Settings::instance().evaluationDate();
                initializeDates();
            }
            BootstrapHelper<TS>::update();
        }
Member Data Documentation
template<class TS > Date QuantLib::RelativeDateBootstrapHelper< TS >::evaluationDate_ [protected]
Definition at line 118 of file bootstraphelper.hpp.
Referenced by QuantLib::CdsHelper::initializeDates(), QuantLib::DepositRateHelper::initializeDates(), QuantLib::UpfrontCdsHelper::initializeDates(), QuantLib::FraRateHelper::initializeDates(), QuantLib::BMASwapRateHelper::initializeDates(), QuantLib::RelativeDateBootstrapHelper< TS >::RelativeDateBootstrapHelper(), and QuantLib::RelativeDateBootstrapHelper< TS >::update().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/bootstraphelper.hpp