QuantLib: QuantLib::BMAIndex Class Reference
QuantLib::BMAIndex Class Reference
Bond Market Association index.
#include <bmaindex.hpp>
Public Member Functions
BMAIndex (const Handle< YieldTermStructure > &h=Handle< YieldTermStructure >())
Index interface
std::string name () const
bool isValidFixingDate (const Date &fixingDate) const
returns TRUE if the fixing date is a valid one
Inspectors
Handle< YieldTermStructure > forwardingTermStructure () const
Date calculations
Date maturityDate (const Date &valueDate) const
Schedule fixingSchedule (const Date &start, const Date &end)
Protected Member Functions
Rate forecastFixing (const Date &fixingDate) const
It can be overridden to implement particular conventions.
Protected Attributes
Handle< YieldTermStructure > termStructure_
Detailed Description
Bond Market Association index.
The BMA index is the short-term tax-exempt reference index of the Bond Market Association. It has tenor one week, is fixed weekly on Wednesdays and is applied with a one-day's fixing gap from Thursdays on for one week. It is the tax-exempt correspondent of the 1M USD-Libor.
Definition at line 40 of file bmaindex.hpp.
Constructor & Destructor Documentation
QuantLib::BMAIndex::BMAIndex (const Handle< YieldTermStructure > & h = Handle<YieldTermStructure>())
Definition at line 43 of file bmaindex.cpp.
References QuantLib::Observer::registerWith().
    : InterestRateIndex("BMA",
                        1 * Weeks,
                        1,
                        USDCurrency(),
                        UnitedStates(UnitedStates::NYSE),
                        ActualActual(ActualActual::ISDA)),
      termStructure_(h) {
        registerWith (h);
    }
Member Function Documentation
Schedule QuantLib::BMAIndex::fixingSchedule (const Date & start, const Date & end)
This method returns a schedule of fixing dates between start and end.
Definition at line 78 of file bmaindex.cpp.
References QuantLib::InterestRateIndex::fixingCalendar(), QuantLib::Following, QuantLib::MakeSchedule::forwards(), QuantLib::MakeSchedule::from(), QuantLib::anonymous_namespace{bmaindex.cpp}::nextWednesday(), QuantLib::anonymous_namespace{bmaindex.cpp}::previousWednesday(), QuantLib::MakeSchedule::to(), QuantLib::Weekly, QuantLib::MakeSchedule::withCalendar(), QuantLib::MakeSchedule::withConvention(), and QuantLib::MakeSchedule::withFrequency().
{
        return MakeSchedule().from(previousWednesday(start))
                             .to(nextWednesday(end))
                             .withFrequency(Weekly)
                             .withCalendar(fixingCalendar())
                             .withConvention(Following)
                             .forwards();
    }
Rate QuantLib::BMAIndex::forecastFixing (const Date & fixingDate) const [protected, virtual]
It can be overridden to implement particular conventions.
Implements QuantLib::InterestRateIndex.
Definition at line 87 of file bmaindex.cpp.
References QuantLib::Calendar::advance(), QuantLib::InterestRateIndex::dayCounter_, QuantLib::Days, QuantLib::Handle< T >::empty(), QuantLib::InterestRateIndex::fixingCalendar(), maturityDate(), name(), QL_REQUIRE, QuantLib::Simple, and termStructure_.
{
        QL_REQUIRE(!termStructure_.empty(),
                   "null term structure set to this instance of " << name());
        Date start = fixingCalendar().advance(fixingDate, 1, Days);
        Date end = maturityDate(start);
        return termStructure_->forwardRate(start, end,
                                           dayCounter_,
                                           Simple);
    }
Handle< YieldTermStructure > QuantLib::BMAIndex::forwardingTermStructure () const
Definition at line 67 of file bmaindex.cpp.
References termStructure_.
{
        return termStructure_;
    }
bool QuantLib::BMAIndex::isValidFixingDate (const Date & fixingDate) const [virtual]
returns TRUE if the fixing date is a valid one
Reimplemented from QuantLib::InterestRateIndex.
Definition at line 54 of file bmaindex.cpp.
References anonymous_namespace{marketmodel.cpp}::d, QuantLib::InterestRateIndex::fixingCalendar(), QuantLib::Calendar::isBusinessDay(), and QuantLib::anonymous_namespace{bmaindex.cpp}::previousWednesday().
{
        Calendar cal = fixingCalendar();
        // either the fixing date is last Wednesday, or all days
        // between last Wednesday included and the fixing date are
        // holidays
        for (Date d = previousWednesday(date); d<date; ++d) {
            if (cal.isBusinessDay(d))
                return false;
        }
        // also, the fixing date itself must be a business day
        return cal.isBusinessDay(date);
    }
Date QuantLib::BMAIndex::maturityDate (const Date & valueDate) const [virtual]
Implements QuantLib::InterestRateIndex.
Definition at line 71 of file bmaindex.cpp.
References QuantLib::Calendar::advance(), QuantLib::Days, QuantLib::InterestRateIndex::fixingCalendar(), QuantLib::InterestRateIndex::fixingDate(), QuantLib::anonymous_namespace{bmaindex.cpp}::nextWednesday(), and QuantLib::anonymous_namespace{bmaindex.cpp}::previousWednesday().
Referenced by forecastFixing().
{
        Calendar cal = fixingCalendar();
        Date fixingDate = cal.advance(valueDate, -1, Days);
        Date nextWednesday = previousWednesday(fixingDate+7);
        return cal.advance(nextWednesday, 1, Days);
    }
std::string QuantLib::BMAIndex::name () const [inline, virtual]
BMA is fixed weekly on Wednesdays.
Reimplemented from QuantLib::InterestRateIndex.
Definition at line 48 of file bmaindex.hpp.
Referenced by forecastFixing().
{ return "BMA"; }
Member Data Documentation
Handle<YieldTermStructure> QuantLib::BMAIndex::termStructure_ [protected]
Definition at line 66 of file bmaindex.hpp.
Referenced by forecastFixing(), and forwardingTermStructure().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/indexes/bmaindex.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/indexes/bmaindex.cpp