QuantLib: QuantLib::OneFactorAffineModel Class Reference
QuantLib::OneFactorAffineModel Class Reference
Single-factor affine base class.
#include <onefactormodel.hpp>
Public Member Functions
OneFactorAffineModel (Size nArguments)
virtual Real discountBond (Time now, Time maturity, Array factors) const
Real discountBond (Time now, Time maturity, Rate rate) const
DiscountFactor discount (Time t) const
Implied discount curve.
Protected Member Functions
virtual Real A (Time t, Time T) const =0
virtual Real B (Time t, Time T) const =0
Detailed Description
Single-factor affine base class.
Single-factor models with an analytical formula for discount bonds should inherit from this class. They must then implement the functions \(A(t,T) \) and \(B(t,T) \) such that
\[ P(t, T, r_t) = A(t,T)e^{ -B(t,T) r_t}. \]
Definition at line 122 of file onefactormodel.hpp.
Constructor & Destructor Documentation
QuantLib::OneFactorAffineModel::OneFactorAffineModel (Size nArguments) [inline]
Definition at line 125 of file onefactormodel.hpp.
        : OneFactorModel(nArguments) {}
Member Function Documentation
virtual Real QuantLib::OneFactorAffineModel::A (Time t, Time T) const [protected, pure virtual]
Implemented in QuantLib::HullWhite, QuantLib::ExtendedCoxIngersollRoss, QuantLib::CoxIngersollRoss, and QuantLib::Vasicek.
Referenced by discountBond().
virtual Real QuantLib::OneFactorAffineModel::B (Time t, Time T) const [protected, pure virtual]
Implemented in QuantLib::CoxIngersollRoss, and QuantLib::Vasicek.
Referenced by discountBond().
DiscountFactor QuantLib::OneFactorAffineModel::discount (Time t) const [virtual]
Implied discount curve.
Implements QuantLib::AffineModel.
Definition at line 103 of file onefactormodel.cpp.
References discountBond(), and QuantLib::OneFactorModel::dynamics().
{
        Real x0 = dynamics()->process()->x0();
        Rate r0 = dynamics()->shortRate(0.0, x0);
        return discountBond(0.0, t, r0);
    }
virtual Real QuantLib::OneFactorAffineModel::discountBond (Time now, Time maturity, Array factors) const [inline, virtual]
Implements QuantLib::AffineModel.
Definition at line 128 of file onefactormodel.hpp.
Referenced by discount(), QuantLib::Vasicek::discountBondOption(), QuantLib::CoxIngersollRoss::discountBondOption(), and QuantLib::HullWhite::tree().
{
            return discountBond(now, maturity, factors[0]);
        }
Real QuantLib::OneFactorAffineModel::discountBond (Time now, Time maturity, Rate rate) const [inline]
Definition at line 134 of file onefactormodel.hpp.
References A(), and B().
{
            return A(now, maturity)*std::exp(-B(now, maturity)*rate);
        }
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/shortrate/onefactormodel.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/shortrate/onefactormodel.cpp