QuantLib: QuantLib::ArmijoLineSearch Class Reference
QuantLib::ArmijoLineSearch Class Reference
Armijo line search.
#include <armijo.hpp>
Public Member Functions
ArmijoLineSearch (Real eps=1e-8, Real alpha=0.05, Real beta=0.65)
Default constructor.
Real operator() (Problem &P, EndCriteria::Type &ecType, const EndCriteria &, const Real t_ini)
Perform line search.
Private Attributes
Real alpha_
Real beta_
Detailed Description
Armijo line search.
Let \(\alpha \) and \(\beta \) be 2 scalars in \([0,1] \). Let \(x \) be the current value of the unknown, \(d \) the search direction and \(t \) the step. Let \(f \) be the function to minimize. The line search stops when \(t \) verifies
\[ f(x + t \cdot d) - f(x) \leq -\alpha t f'(x+t \cdot d) \]
and
\[ f(x+\frac{t}{\beta} \cdot d) - f(x) > -\frac{\alpha}{\beta} t f'(x+t \cdot d) \]
(see Polak, Algorithms and consistent approximations, Optimization, volume 124 of Applied Mathematical Sciences, Springer-Verlag, NY, 1997)
Definition at line 48 of file armijo.hpp.
Constructor & Destructor Documentation
QuantLib::ArmijoLineSearch::ArmijoLineSearch (Real eps = 1e-8, Real alpha = 0.05, Real beta = 0.65) [inline]
Default constructor.
Definition at line 51 of file armijo.hpp.
        : LineSearch(eps), alpha_(alpha), beta_(beta) {}
Member Function Documentation
Real QuantLib::ArmijoLineSearch::operator() (Problem & P, EndCriteria::Type & ecType, const EndCriteria & endCriteria, const Real t_ini) [virtual]
Perform line search.
Implements QuantLib::LineSearch.
Definition at line 26 of file armijo.cpp.
References alpha_, beta_, QuantLib::EndCriteria::checkMaxIterations(), QuantLib::Problem::constraint(), QuantLib::Problem::currentValue(), QuantLib::DotProduct(), QuantLib::Array::empty(), QuantLib::Problem::functionValue(), QuantLib::Problem::gradient(), QuantLib::LineSearch::gradient_, QuantLib::Problem::gradientNormValue(), QuantLib::LineSearch::qpt_, QuantLib::LineSearch::qt_, QuantLib::LineSearch::searchDirection_, QuantLib::Array::size(), QuantLib::LineSearch::succeed_, anonymous_namespace{quantlibbenchmark.cpp}::t, QuantLib::LineSearch::update(), QuantLib::Problem::value(), and QuantLib::LineSearch::xtd_.
    {
        //OptimizationMethod& method = P.method();
        Constraint& constraint = P.constraint();
        succeed_=true;
        bool maxIter = false;
        Real qtold, t = t_ini;
        Size loopNumber = 0;
        Real q0 = P.functionValue();
        Real qp0 = P.gradientNormValue();
        qt_ = q0;
        qpt_ = (gradient_.empty()) ? qp0 : -DotProduct(gradient_,searchDirection_);
        // Initialize gradient
        gradient_ = Array(P.currentValue().size());
        // Compute new point
        xtd_ = P.currentValue();
        t = update(xtd_, searchDirection_, t, constraint);
        // Compute function value at the new point
        qt_ = P.value (xtd_);
        // Enter in the loop if the criterion is not satisfied
        if ((qt_-q0) > -alpha_*t*qpt_) {
            do {
                loopNumber++;
                // Decrease step
                t *= beta_;
                // Store old value of the function
                qtold = qt_;
                // New point value
                xtd_ = P.currentValue();
                t = update(xtd_, searchDirection_, t, constraint);
                // Compute function value at the new point
                qt_ = P.value (xtd_);
                P.gradient (gradient_, xtd_);
                // and it squared norm
                maxIter = endCriteria.checkMaxIterations(loopNumber, ecType);
            } while (
                     (((qt_ - q0) > (-alpha_ * t * qpt_)) ||
                      ((qtold - q0) <= (-alpha_ * t * qpt_ / beta_))) &&
                     (!maxIter));
        }
        if (maxIter)
            succeed_ = false;
        // Compute new gradient
        P.gradient(gradient_, xtd_);
        // and it squared norm
        qpt_ = DotProduct(gradient_, gradient_);
        // Return new step value
        return t;
    }
Member Data Documentation
Real QuantLib::ArmijoLineSearch::alpha_ [private]
Definition at line 62 of file armijo.hpp.
Referenced by operator()().
Real QuantLib::ArmijoLineSearch::beta_ [private]
Definition at line 62 of file armijo.hpp.
Referenced by operator()().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/optimization/armijo.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/math/optimization/armijo.cpp