QuantLib: QuantLib::CTSMMCapletCalibration Class Reference
QuantLib::CTSMMCapletCalibration Class Reference
#include <ctsmmcapletcalibration.hpp>
Public Member Functions
virtual ~CTSMMCapletCalibration ()
CTSMMCapletCalibration (const EvolutionDescription &evolution, const boost::shared_ptr< PiecewiseConstantCorrelation > &corr, const std::vector< boost::shared_ptr< PiecewiseConstantVariance > > &displacedSwapVariances, const std::vector< Volatility > &mktCapletVols, const boost::shared_ptr< CurveState > &cs, Spread displacement)
bool calibrate (Natural numberOfFactors, Natural maxIterations, Real tolerance, Natural innerMaxIterations=100, Real innerTolerance=1e-8)
Natural failures () const
Real deformationSize () const
Real capletRmsError () const
Real capletMaxError () const
Real swaptionRmsError () const
Real swaptionMaxError () const
const std::vector< Matrix > & swapPseudoRoots () const
const Matrix & swapPseudoRoot (Size i) const
const std::vector< Volatility > & mktCapletVols () const
const std::vector< Volatility > & mdlCapletVols () const
const std::vector< Volatility > & mktSwaptionVols () const
const std::vector< Volatility > & mdlSwaptionVols () const
const std::vector< Volatility > & timeDependentCalibratedSwaptionVols (Size i) const
const std::vector< Volatility > & timeDependentUnCalibratedSwaptionVols (Size i) const
const boost::shared_ptr
< CurveState > & curveState () const
std::vector< Spread > displacements () const
Static Public Member Functions
static void performChecks (const EvolutionDescription &evolution, const PiecewiseConstantCorrelation &corr, const std::vector< boost::shared_ptr< PiecewiseConstantVariance > > &displacedSwapVariances, const std::vector< Volatility > &mktCapletVols, const CurveState &cs)
Protected Member Functions
virtual Natural calibrationImpl_ (Natural numberOfFactors, Natural innerMaxIterations, Real innerTolerance)=0
Protected Attributes
EvolutionDescription evolution_
boost::shared_ptr
< PiecewiseConstantCorrelation > corr_
std::vector< boost::shared_ptr
< PiecewiseConstantVariance > > displacedSwapVariances_
std::vector< Volatility > mktCapletVols_
std::vector< Volatility > mdlCapletVols_
std::vector< Volatility > mktSwaptionVols_
std::vector< Volatility > mdlSwaptionVols_
std::vector< std::vector
< Volatility > > timeDependentCalibratedSwaptionVols_
boost::shared_ptr< CurveState > cs_
Spread displacement_
Size numberOfRates_
std::vector< Volatility > usedCapletVols_
bool calibrated_
Natural failures_
Real deformationSize_
Real capletRmsError_
Real capletMaxError_
Real swaptionRmsError_
Real swaptionMaxError_
std::vector< Matrix > swapCovariancePseudoRoots_
Detailed Description
Definition at line 35 of file ctsmmcapletcalibration.hpp.
Constructor & Destructor Documentation
QuantLib::CTSMMCapletCalibration::~CTSMMCapletCalibration () [virtual]
Definition at line 33 of file ctsmmcapletcalibration.cpp.
{}
QuantLib::CTSMMCapletCalibration::CTSMMCapletCalibration (const EvolutionDescription & evolution, const boost::shared_ptr< PiecewiseConstantCorrelation > & corr, const std::vector< boost::shared_ptr< PiecewiseConstantVariance > > & displacedSwapVariances, const std::vector< Volatility > & mktCapletVols, const boost::shared_ptr< CurveState > & cs, Spread displacement)
Definition at line 35 of file ctsmmcapletcalibration.cpp.
References corr_, cs_, displacedSwapVariances_, evolution_, mktCapletVols_, and performChecks().
    : evolution_(evolution),  corr_(corr),
      displacedSwapVariances_(displacedSwapVariances),
      mktCapletVols_(mktCapletVols),
      mdlCapletVols_(evolution_.numberOfRates()),
      mktSwaptionVols_(evolution_.numberOfRates()),
      mdlSwaptionVols_(evolution_.numberOfRates()),
      cs_(cs), displacement_(displacement),
      numberOfRates_(evolution_.numberOfRates())
    {
        performChecks(evolution_, *corr_, displacedSwapVariances_,
                      mktCapletVols_, *cs_);
    }
Member Function Documentation
bool QuantLib::CTSMMCapletCalibration::calibrate (Natural numberOfFactors, Natural maxIterations, Real tolerance, Natural innerMaxIterations = 100, Real innerTolerance = 1e-8)
Definition at line 131 of file ctsmmcapletcalibration.cpp.
References calibrated_, calibrationImpl_(), capletMaxError_, capletRmsError_, cs_, deformationSize_, displacedSwapVariances_, displacement_, displacements(), evolution_, failures_, mdlCapletVols_, mdlSwaptionVols_, mktCapletVols_, mktSwaptionVols_, numberOfRates_, QuantLib::EvolutionDescription::rateTimes(), anonymous_namespace{marketmodel.cpp}::rateTimes, swapCovariancePseudoRoots_, swaptionMaxError_, swaptionRmsError_, timeDependentCalibratedSwaptionVols_, QuantLib::MarketModel::totalCovariance(), and usedCapletVols_.
Referenced by QuantLib::capletSwaptionPeriodicCalibration(), MarketModelSmmCapletHomoCalibrationTest::testFunction(), MarketModelSmmCapletCalibrationTest::testFunction(), and MarketModelSmmCapletAlphaCalibrationTest::testFunction().
{
        // initialize results
        calibrated_ = false;
        failures_ = 987654321; // a positive large number
        deformationSize_ = 987654321;
        capletRmsError_ = swaptionRmsError_ = 987654321;
        capletMaxError_ = swaptionMaxError_ = 987654321;
        // initialize working variables
        usedCapletVols_ = mktCapletVols_;
        for (Size i=0; i<numberOfRates_; ++i)
            mktSwaptionVols_[i]=displacedSwapVariances_[i]->totalVolatility(i);
        std::vector<Spread> displacements(numberOfRates_,
                                          displacement_);
        const std::vector<Time>& rateTimes = evolution_.rateTimes();
        Natural iterations = 0;
        // calibration loop
        do {
            failures_ = calibrationImpl_(numberOfFactors,
                                         innerSolvingMaxIterations,
                                         innerSolvingTolerance);
            boost::shared_ptr<MarketModel> ctsmm(new
                PseudoRootFacade(swapCovariancePseudoRoots_,
                                 rateTimes,
                                 cs_->coterminalSwapRates(),
                                 displacements));
            const Matrix& swaptionTotCovariance =
                ctsmm->totalCovariance(numberOfRates_-1);
            CotSwapToFwdAdapter flmm(ctsmm);
            const Matrix& capletTotCovariance =
                flmm.totalCovariance(numberOfRates_-1);
            // check fit
            capletRmsError_ = swaptionRmsError_ = 0.0;
            capletMaxError_ = swaptionMaxError_ = -1.0;
            for (Size i=0; i<numberOfRates_; ++i) {
                mdlSwaptionVols_[i] = std::sqrt(swaptionTotCovariance[i][i]/rateTimes[i]);
                Real swaptionError = std::fabs(mktSwaptionVols_[i]-mdlSwaptionVols_[i]);
                swaptionRmsError_ += swaptionError*swaptionError;
                swaptionMaxError_ = std::max(swaptionMaxError_, swaptionError);
                mdlCapletVols_[i] = std::sqrt(capletTotCovariance[i][i]/rateTimes[i]);
                Real capletError = std::fabs(mktCapletVols_[i]-mdlCapletVols_[i]);
                capletRmsError_ += capletError*capletError;
                capletMaxError_ = std::max(capletMaxError_, capletError);
                if (i < numberOfRates_-1)
                    usedCapletVols_[i] *= mktCapletVols_[i]/mdlCapletVols_[i];
            }
            swaptionRmsError_ = std::sqrt(swaptionRmsError_/numberOfRates_);
            capletRmsError_ = std::sqrt(capletRmsError_/numberOfRates_);
            ++iterations;
        } while (iterations<maxIterations &&
                 capletRmsError_>capletVolTolerance);
         boost::shared_ptr<MarketModel> ctsmm(new
                PseudoRootFacade(swapCovariancePseudoRoots_,
                                 rateTimes,
                                 cs_->coterminalSwapRates(),
                                 displacements));
         timeDependentCalibratedSwaptionVols_.clear();
         for (Size i=0; i<numberOfRates_; ++i)
             timeDependentCalibratedSwaptionVols_.push_back(
                ctsmm->timeDependentVolatility(i));
        // calculate deformationSize_ ??
        calibrated_ = true;
        return failures_==0;
    }
virtual Natural QuantLib::CTSMMCapletCalibration::calibrationImpl_ (Natural numberOfFactors, Natural innerMaxIterations, Real innerTolerance) [protected, pure virtual]
Implemented in QuantLib::CTSMMCapletAlphaFormCalibration, QuantLib::CTSMMCapletOriginalCalibration, and QuantLib::CTSMMCapletMaxHomogeneityCalibration.
Referenced by calibrate().
Real QuantLib::CTSMMCapletCalibration::capletMaxError () const [inline]
Definition at line 154 of file ctsmmcapletcalibration.hpp.
References calibrated_, capletMaxError_, and QL_REQUIRE.
Referenced by MarketModelSmmCapletAlphaCalibrationTest::testFunction(), MarketModelSmmCapletHomoCalibrationTest::testFunction(), and MarketModelSmmCapletCalibrationTest::testFunction().
{
        QL_REQUIRE(calibrated_, "not successfully calibrated yet");
        return capletMaxError_;
    }
Real QuantLib::CTSMMCapletCalibration::capletRmsError () const [inline]
Definition at line 149 of file ctsmmcapletcalibration.hpp.
References calibrated_, capletRmsError_, and QL_REQUIRE.
Referenced by MarketModelSmmCapletAlphaCalibrationTest::testFunction(), MarketModelSmmCapletHomoCalibrationTest::testFunction(), and MarketModelSmmCapletCalibrationTest::testFunction().
{
        QL_REQUIRE(calibrated_, "not successfully calibrated yet");
        return capletRmsError_;
    }
const boost::shared_ptr< CurveState > & QuantLib::CTSMMCapletCalibration::curveState () const [inline]
Definition at line 185 of file ctsmmcapletcalibration.hpp.
References cs_.
{
        return cs_;
    }
Real QuantLib::CTSMMCapletCalibration::deformationSize () const [inline]
Definition at line 144 of file ctsmmcapletcalibration.hpp.
References calibrated_, deformationSize_, and QL_REQUIRE.
Referenced by MarketModelSmmCapletAlphaCalibrationTest::testFunction(), MarketModelSmmCapletHomoCalibrationTest::testFunction(), and MarketModelSmmCapletCalibrationTest::testFunction().
{
        QL_REQUIRE(calibrated_, "not successfully calibrated yet");
        return deformationSize_;
    }
std::vector< Spread > QuantLib::CTSMMCapletCalibration::displacements () const [inline]
Definition at line 190 of file ctsmmcapletcalibration.hpp.
References displacement_, and numberOfRates_.
Referenced by calibrate().
{
        return std::vector<Volatility>(numberOfRates_, displacement_);
    }
Natural QuantLib::CTSMMCapletCalibration::failures () const [inline]
Definition at line 139 of file ctsmmcapletcalibration.hpp.
References calibrated_, failures_, and QL_REQUIRE.
Referenced by QuantLib::CTSMMCapletOriginalCalibration::calibrationFunction(), QuantLib::CTSMMCapletAlphaFormCalibration::capletAlphaFormCalibration(), QuantLib::CTSMMCapletMaxHomogeneityCalibration::capletMaxHomogeneityCalibration(), MarketModelSmmCapletAlphaCalibrationTest::testFunction(), MarketModelSmmCapletHomoCalibrationTest::testFunction(), and MarketModelSmmCapletCalibrationTest::testFunction().
{
        QL_REQUIRE(calibrated_, "not successfully calibrated yet");
        return failures_;
    }
const std::vector< Volatility > & QuantLib::CTSMMCapletCalibration::mdlCapletVols () const [inline]
Definition at line 123 of file ctsmmcapletcalibration.hpp.
References calibrated_, mdlCapletVols_, and QL_REQUIRE.
{
        QL_REQUIRE(calibrated_, "not successfully calibrated yet");
        return mdlCapletVols_;
    }
const std::vector< Volatility > & QuantLib::CTSMMCapletCalibration::mdlSwaptionVols () const [inline]
Definition at line 134 of file ctsmmcapletcalibration.hpp.
References calibrated_, mdlSwaptionVols_, and QL_REQUIRE.
{
        QL_REQUIRE(calibrated_, "not successfully calibrated yet");
        return mdlSwaptionVols_;
    }
const std::vector< Volatility > & QuantLib::CTSMMCapletCalibration::mktCapletVols () const [inline]
Definition at line 118 of file ctsmmcapletcalibration.hpp.
References mktCapletVols_.
{
        return mktCapletVols_;
    }
const std::vector< Volatility > & QuantLib::CTSMMCapletCalibration::mktSwaptionVols () const [inline]
Definition at line 129 of file ctsmmcapletcalibration.hpp.
References mktSwaptionVols_.
{
        return mktSwaptionVols_;
    }
void QuantLib::CTSMMCapletCalibration::performChecks (const EvolutionDescription & evolution, const PiecewiseConstantCorrelation & corr, const std::vector< boost::shared_ptr< PiecewiseConstantVariance > > & displacedSwapVariances, const std::vector< Volatility > & mktCapletVols, const CurveState & cs) [static]
Definition at line 78 of file ctsmmcapletcalibration.cpp.
References QuantLib::close(), QuantLib::EvolutionDescription::evolutionTimes(), QuantLib::PiecewiseConstantCorrelation::numberOfRates(), QuantLib::CurveState::numberOfRates(), QuantLib::EvolutionDescription::numberOfRates(), QL_REQUIRE, QuantLib::CurveState::rateTimes(), QuantLib::EvolutionDescription::rateTimes(), anonymous_namespace{marketmodel.cpp}::rateTimes, QuantLib::io::sequence(), and QuantLib::PiecewiseConstantCorrelation::times().
Referenced by QuantLib::CTSMMCapletOriginalCalibration::calibrationFunction(), QuantLib::CTSMMCapletAlphaFormCalibration::capletAlphaFormCalibration(), QuantLib::CTSMMCapletMaxHomogeneityCalibration::capletMaxHomogeneityCalibration(), and CTSMMCapletCalibration().
    {
        const std::vector<Time>& evolutionTimes = evolution.evolutionTimes();
        QL_REQUIRE(evolutionTimes==corr.times(),
                   "evolutionTimes "
                   << io::sequence(evolutionTimes)
                   << " not equal to correlation times "
                   << io::sequence(corr.times()));
        const std::vector<Time>& rateTimes = evolution.rateTimes();
        QL_REQUIRE(rateTimes==cs.rateTimes(),
                   "mismatch between EvolutionDescription and "
                   "CurveState rate times");
        Size numberOfRates = evolution.numberOfRates();
        QL_REQUIRE(numberOfRates==displacedSwapVariances.size(),
                   "mismatch between EvolutionDescription number of rates ("
                   << numberOfRates << ") and displacedSwapVariances size ("
                   << displacedSwapVariances.size() << ")");
        QL_REQUIRE(numberOfRates==corr.numberOfRates(),
                   "mismatch between EvolutionDescription number of rates ("
                   << numberOfRates << ") and corr number of rates ("
                   << corr.numberOfRates() << ")");
        QL_REQUIRE(numberOfRates==mktCapletVols.size(),
                   "mismatch between EvolutionDescription number of rates ("
                   << numberOfRates << ") and mktCapletVols size ("
                   << mktCapletVols.size() << ")");
        QL_REQUIRE(numberOfRates==cs.numberOfRates(),
                   "mismatch between EvolutionDescription number of rates ("
                   << numberOfRates << ") and CurveState  number of rates ("
                   << cs.numberOfRates() << ")");
        std::vector<Time> temp(rateTimes.begin(), rateTimes.end()-1);
        QL_REQUIRE(temp==evolutionTimes,
                   "mismatch between evolutionTimes and rateTimes");
        Volatility lastSwaptionVol =
            displacedSwapVariances.back()->totalVolatility(numberOfRates-1);
        QL_REQUIRE(close(lastSwaptionVol, mktCapletVols[numberOfRates-1]),
                   "last caplet vol (" << std::setprecision(16) <<
                   mktCapletVols[numberOfRates-1] <<
                   ") must be equal to last swaption vol (" <<
                   lastSwaptionVol << "); discrepancy is " <<
                   lastSwaptionVol-mktCapletVols[numberOfRates-1]);
    }
const Matrix & QuantLib::CTSMMCapletCalibration::swapPseudoRoot (Size i) const [inline]
Definition at line 176 of file ctsmmcapletcalibration.hpp.
References calibrated_, QL_REQUIRE, and swapCovariancePseudoRoots_.
{
        QL_REQUIRE(calibrated_, "not successfully calibrated yet");
        QL_REQUIRE(i<swapCovariancePseudoRoots_.size(),
                   i << "is an invalid index, must be less than "
                   << swapCovariancePseudoRoots_.size());
        return swapCovariancePseudoRoots_[i];
    }
const std::vector< Matrix > & QuantLib::CTSMMCapletCalibration::swapPseudoRoots () const [inline]
Definition at line 170 of file ctsmmcapletcalibration.hpp.
References calibrated_, QL_REQUIRE, and swapCovariancePseudoRoots_.
Referenced by MarketModelSmmCapletAlphaCalibrationTest::testFunction(), MarketModelSmmCapletHomoCalibrationTest::testFunction(), and MarketModelSmmCapletCalibrationTest::testFunction().
{
        QL_REQUIRE(calibrated_, "not successfully calibrated yet");
        return swapCovariancePseudoRoots_;
    }
Real QuantLib::CTSMMCapletCalibration::swaptionMaxError () const [inline]
Definition at line 164 of file ctsmmcapletcalibration.hpp.
References calibrated_, QL_REQUIRE, and swaptionMaxError_.
Referenced by MarketModelSmmCapletAlphaCalibrationTest::testFunction(), MarketModelSmmCapletHomoCalibrationTest::testFunction(), and MarketModelSmmCapletCalibrationTest::testFunction().
{
        QL_REQUIRE(calibrated_, "not successfully calibrated yet");
        return swaptionMaxError_;
    }
Real QuantLib::CTSMMCapletCalibration::swaptionRmsError () const [inline]
Definition at line 159 of file ctsmmcapletcalibration.hpp.
References calibrated_, QL_REQUIRE, and swaptionRmsError_.
Referenced by MarketModelSmmCapletAlphaCalibrationTest::testFunction(), MarketModelSmmCapletHomoCalibrationTest::testFunction(), and MarketModelSmmCapletCalibrationTest::testFunction().
{
        QL_REQUIRE(calibrated_, "not successfully calibrated yet");
        return swaptionRmsError_;
    }
const std::vector< Volatility > & QuantLib::CTSMMCapletCalibration::timeDependentCalibratedSwaptionVols (Size i) const
Definition at line 70 of file ctsmmcapletcalibration.cpp.
References numberOfRates_, QL_REQUIRE, and timeDependentCalibratedSwaptionVols_.
    {
        QL_REQUIRE(i<numberOfRates_,
                   "index (" << i << ") must less than number of rates (" <<
                   numberOfRates_ << ")");
        return timeDependentCalibratedSwaptionVols_[i];
    }
const std::vector< Volatility > & QuantLib::CTSMMCapletCalibration::timeDependentUnCalibratedSwaptionVols (Size i) const
Definition at line 61 of file ctsmmcapletcalibration.cpp.
References displacedSwapVariances_, numberOfRates_, and QL_REQUIRE.
    {
        QL_REQUIRE(i<numberOfRates_,
                   "index (" << i << ") must less than number of rates (" <<
                   numberOfRates_ << ")");
        return displacedSwapVariances_[i]->volatilities();
    }
Member Data Documentation
bool QuantLib::CTSMMCapletCalibration::calibrated_ [protected]
Definition at line 107 of file ctsmmcapletcalibration.hpp.
Referenced by QuantLib::CTSMMCapletAlphaFormCalibration::alpha(), calibrate(), capletMaxError(), capletRmsError(), deformationSize(), failures(), mdlCapletVols(), mdlSwaptionVols(), swapPseudoRoot(), swapPseudoRoots(), swaptionMaxError(), and swaptionRmsError().
Real QuantLib::CTSMMCapletCalibration::capletMaxError_ [protected]
Definition at line 110 of file ctsmmcapletcalibration.hpp.
Referenced by calibrate(), and capletMaxError().
Real QuantLib::CTSMMCapletCalibration::capletRmsError_ [protected]
Definition at line 110 of file ctsmmcapletcalibration.hpp.
Referenced by calibrate(), and capletRmsError().
boost::shared_ptr<PiecewiseConstantCorrelation> QuantLib::CTSMMCapletCalibration::corr_ [protected]
Definition at line 93 of file ctsmmcapletcalibration.hpp.
Referenced by QuantLib::CTSMMCapletMaxHomogeneityCalibration::calibrationImpl_(), QuantLib::CTSMMCapletOriginalCalibration::calibrationImpl_(), QuantLib::CTSMMCapletAlphaFormCalibration::calibrationImpl_(), and CTSMMCapletCalibration().
boost::shared_ptr<CurveState> QuantLib::CTSMMCapletCalibration::cs_ [protected]
Definition at line 101 of file ctsmmcapletcalibration.hpp.
Referenced by calibrate(), QuantLib::CTSMMCapletMaxHomogeneityCalibration::calibrationImpl_(), QuantLib::CTSMMCapletOriginalCalibration::calibrationImpl_(), QuantLib::CTSMMCapletAlphaFormCalibration::calibrationImpl_(), CTSMMCapletCalibration(), and curveState().
Real QuantLib::CTSMMCapletCalibration::deformationSize_ [protected]
Definition at line 109 of file ctsmmcapletcalibration.hpp.
Referenced by calibrate(), QuantLib::CTSMMCapletMaxHomogeneityCalibration::calibrationImpl_(), and deformationSize().
std::vector<boost::shared_ptr<PiecewiseConstantVariance> > QuantLib::CTSMMCapletCalibration::displacedSwapVariances_ [protected]
Definition at line 95 of file ctsmmcapletcalibration.hpp.
Referenced by calibrate(), QuantLib::CTSMMCapletMaxHomogeneityCalibration::calibrationImpl_(), QuantLib::CTSMMCapletOriginalCalibration::calibrationImpl_(), QuantLib::CTSMMCapletAlphaFormCalibration::calibrationImpl_(), CTSMMCapletCalibration(), and timeDependentUnCalibratedSwaptionVols().
Spread QuantLib::CTSMMCapletCalibration::displacement_ [protected]
Definition at line 102 of file ctsmmcapletcalibration.hpp.
Referenced by calibrate(), QuantLib::CTSMMCapletMaxHomogeneityCalibration::calibrationImpl_(), QuantLib::CTSMMCapletOriginalCalibration::calibrationImpl_(), QuantLib::CTSMMCapletAlphaFormCalibration::calibrationImpl_(), and displacements().
EvolutionDescription QuantLib::CTSMMCapletCalibration::evolution_ [protected]
Definition at line 92 of file ctsmmcapletcalibration.hpp.
Referenced by calibrate(), QuantLib::CTSMMCapletMaxHomogeneityCalibration::calibrationImpl_(), QuantLib::CTSMMCapletOriginalCalibration::calibrationImpl_(), QuantLib::CTSMMCapletAlphaFormCalibration::calibrationImpl_(), and CTSMMCapletCalibration().
Natural QuantLib::CTSMMCapletCalibration::failures_ [protected]
Definition at line 108 of file ctsmmcapletcalibration.hpp.
Referenced by calibrate(), and failures().
std::vector<Volatility> QuantLib::CTSMMCapletCalibration::mdlCapletVols_ [protected]
Definition at line 97 of file ctsmmcapletcalibration.hpp.
Referenced by calibrate(), and mdlCapletVols().
std::vector<Volatility> QuantLib::CTSMMCapletCalibration::mdlSwaptionVols_ [protected]
Definition at line 98 of file ctsmmcapletcalibration.hpp.
Referenced by calibrate(), and mdlSwaptionVols().
std::vector<Volatility> QuantLib::CTSMMCapletCalibration::mktCapletVols_ [protected]
Definition at line 97 of file ctsmmcapletcalibration.hpp.
Referenced by calibrate(), CTSMMCapletCalibration(), and mktCapletVols().
std::vector<Volatility> QuantLib::CTSMMCapletCalibration::mktSwaptionVols_ [protected]
Definition at line 98 of file ctsmmcapletcalibration.hpp.
Referenced by calibrate(), and mktSwaptionVols().
Size QuantLib::CTSMMCapletCalibration::numberOfRates_ [protected]
Definition at line 103 of file ctsmmcapletcalibration.hpp.
Referenced by calibrate(), QuantLib::CTSMMCapletAlphaFormCalibration::CTSMMCapletAlphaFormCalibration(), QuantLib::CTSMMCapletOriginalCalibration::CTSMMCapletOriginalCalibration(), displacements(), timeDependentCalibratedSwaptionVols(), and timeDependentUnCalibratedSwaptionVols().
std::vector<Matrix> QuantLib::CTSMMCapletCalibration::swapCovariancePseudoRoots_ [protected]
Definition at line 112 of file ctsmmcapletcalibration.hpp.
Referenced by calibrate(), QuantLib::CTSMMCapletMaxHomogeneityCalibration::calibrationImpl_(), QuantLib::CTSMMCapletOriginalCalibration::calibrationImpl_(), QuantLib::CTSMMCapletAlphaFormCalibration::calibrationImpl_(), swapPseudoRoot(), and swapPseudoRoots().
Real QuantLib::CTSMMCapletCalibration::swaptionMaxError_ [protected]
Definition at line 111 of file ctsmmcapletcalibration.hpp.
Referenced by calibrate(), and swaptionMaxError().
Real QuantLib::CTSMMCapletCalibration::swaptionRmsError_ [protected]
Definition at line 111 of file ctsmmcapletcalibration.hpp.
Referenced by calibrate(), and swaptionRmsError().
std::vector<std::vector<Volatility> > QuantLib::CTSMMCapletCalibration::timeDependentCalibratedSwaptionVols_ [protected]
Definition at line 99 of file ctsmmcapletcalibration.hpp.
Referenced by calibrate(), and timeDependentCalibratedSwaptionVols().
std::vector<Volatility> QuantLib::CTSMMCapletCalibration::usedCapletVols_ [protected]
Definition at line 105 of file ctsmmcapletcalibration.hpp.
Referenced by calibrate(), QuantLib::CTSMMCapletMaxHomogeneityCalibration::calibrationImpl_(), QuantLib::CTSMMCapletOriginalCalibration::calibrationImpl_(), and QuantLib::CTSMMCapletAlphaFormCalibration::calibrationImpl_().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/models/ctsmmcapletcalibration.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/models/ctsmmcapletcalibration.cpp