QuantLib: QuantLib::Path Class Reference
QuantLib::Path Class Reference
single-factor random walk
#include <path.hpp>
Public Member Functions
Path (const TimeGrid &timeGrid, const Array &values=Array())
inspectors
bool empty () const
Size length () const
Real operator[] (Size i) const
asset value at the \(i \)-th point
Real at (Size i) const
Real & operator[] (Size i)
Real & at (Size i)
Real value (Size i) const
Real & value (Size i)
Time time (Size i) const
time at the \(i \)-th point
Real front () const
initial asset value
Real & front ()
Real back () const
final asset value
Real & back ()
const TimeGrid & timeGrid () const
time grid
Private Attributes
TimeGrid timeGrid_
Array values_
iterators
typedef Array::const_iterator iterator
typedef
Array::const_reverse_iterator reverse_iterator
iterator begin () const
iterator end () const
reverse_iterator rbegin () const
reverse_iterator rend () const
Detailed Description
single-factor random walk
Note:
the path includes the initial asset value as its first point.
Definition at line 39 of file path.hpp.
Member Typedef Documentation
typedef Array::const_iterator QuantLib::Path::iterator
Definition at line 67 of file path.hpp.
typedef Array::const_reverse_iterator QuantLib::Path::reverse_iterator
Definition at line 68 of file path.hpp.
Constructor & Destructor Documentation
QuantLib::Path::Path (const TimeGrid & timeGrid, const Array & values = Array()) [inline]
Definition at line 82 of file path.hpp.
References QuantLib::Array::empty(), QL_REQUIRE, QuantLib::Array::size(), QuantLib::TimeGrid::size(), timeGrid_, and values_.
    : timeGrid_(timeGrid), values_(values) {
        if (values_.empty())
            values_ = Array(timeGrid_.size());
        QL_REQUIRE(values_.size() == timeGrid_.size(),
                   "different number of times and asset values");
    }
Member Function Documentation
Real QuantLib::Path::at (Size i) const [inline]
Definition at line 102 of file path.hpp.
References QuantLib::Array::at(), and values_.
{
        return values_.at(i);
    }
Real & QuantLib::Path::at (Size i) [inline]
Definition at line 110 of file path.hpp.
References QuantLib::Array::at(), and values_.
{
        return values_.at(i);
    }
Real QuantLib::Path::back () const [inline]
final asset value
Definition at line 130 of file path.hpp.
References QuantLib::Array::size(), and values_.
Referenced by QuantLib::ArithmeticASOPathPricer::operator()(), QuantLib::EuropeanGJRGARCHPathPricer::operator()(), QuantLib::EuropeanHestonPathPricer::operator()(), QuantLib::EuropeanPathPricer::operator()(), and anonymous_namespace{pathgenerator.cpp}::testSingle().
{
        return values_[values_.size()-1];
    }
Real & QuantLib::Path::back () [inline]
Definition at line 134 of file path.hpp.
References QuantLib::Array::size(), and values_.
{
        return values_[values_.size()-1];
    }
Path::iterator QuantLib::Path::begin () const [inline]
Definition at line 146 of file path.hpp.
References QuantLib::Array::begin(), and values_.
Referenced by QuantLib::ArithmeticASOPathPricer::operator()(), QuantLib::ArithmeticAPOPathPricer::operator()(), and BrownianBridgeTest::testPathGeneration().
{
        return values_.begin();
    }
bool QuantLib::Path::empty () const [inline]
Definition at line 90 of file path.hpp.
References QuantLib::TimeGrid::empty(), and timeGrid_.
{
        return timeGrid_.empty();
    }
Path::iterator QuantLib::Path::end () const [inline]
Definition at line 150 of file path.hpp.
References QuantLib::Array::end(), and values_.
Referenced by QuantLib::ArithmeticASOPathPricer::operator()(), QuantLib::ArithmeticAPOPathPricer::operator()(), and BrownianBridgeTest::testPathGeneration().
{
        return values_.end();
    }
Real QuantLib::Path::front () const [inline]
initial asset value
Definition at line 122 of file path.hpp.
References values_.
Referenced by QuantLib::PathGenerator< GSG >::next(), QuantLib::GeometricAPOPathPricer::operator()(), QuantLib::DigitalPathPricer::operator()(), QuantLib::BarrierPathPricer::operator()(), and QuantLib::BiasedBarrierPathPricer::operator()().
{
        return values_[0];
    }
Real & QuantLib::Path::front () [inline]
Definition at line 126 of file path.hpp.
References values_.
{
        return values_[0];
    }
Size QuantLib::Path::length () const [inline]
Definition at line 94 of file path.hpp.
References QuantLib::TimeGrid::size(), and timeGrid_.
Referenced by QuantLib::PathGenerator< GSG >::next(), QuantLib::ArithmeticASOPathPricer::operator()(), QuantLib::GeometricAPOPathPricer::operator()(), QuantLib::ArithmeticAPOPathPricer::operator()(), QuantLib::EuropeanPathPricer::operator()(), QuantLib::PerformanceOptionPathPricer::operator()(), QuantLib::DigitalPathPricer::operator()(), QuantLib::BarrierPathPricer::operator()(), QuantLib::VariancePathPricer::operator()(), QuantLib::BiasedBarrierPathPricer::operator()(), and QuantLib::EarlyExerciseTraits< Path >::pathLength().
{
        return timeGrid_.size();
    }
Real QuantLib::Path::operator[] (Size i) const [inline]
asset value at the \(i \)-th point
Definition at line 98 of file path.hpp.
References values_.
{
        return values_[i];
    }
Real & QuantLib::Path::operator[] (Size i) [inline]
Definition at line 106 of file path.hpp.
References values_.
{
        return values_[i];
    }
Path::reverse_iterator QuantLib::Path::rbegin () const [inline]
Definition at line 154 of file path.hpp.
References QuantLib::Array::rbegin(), and values_.
{
        return values_.rbegin();
    }
Path::reverse_iterator QuantLib::Path::rend () const [inline]
Definition at line 158 of file path.hpp.
References QuantLib::Array::rend(), and values_.
{
        return values_.rend();
    }
Time QuantLib::Path::time (Size i) const [inline]
time at the \(i \)-th point
Definition at line 138 of file path.hpp.
References timeGrid_.
{
        return timeGrid_[i];
    }
const TimeGrid & QuantLib::Path::timeGrid () const [inline]
time grid
Definition at line 142 of file path.hpp.
References timeGrid_.
Referenced by QuantLib::ArithmeticASOPathPricer::operator()(), QuantLib::GeometricAPOPathPricer::operator()(), QuantLib::ArithmeticAPOPathPricer::operator()(), QuantLib::DigitalPathPricer::operator()(), QuantLib::BarrierPathPricer::operator()(), QuantLib::VariancePathPricer::operator()(), and QuantLib::detail::Integrand::operator()().
{
        return timeGrid_;
    }
Real QuantLib::Path::value (Size i) const [inline]
Definition at line 114 of file path.hpp.
References values_.
Referenced by QuantLib::PathGenerator< GSG >::next().
{
        return values_[i];
    }
Real & QuantLib::Path::value (Size i) [inline]
Definition at line 118 of file path.hpp.
References values_.
{
        return values_[i];
    }
Member Data Documentation
TimeGrid QuantLib::Path::timeGrid_ [private]
Definition at line 75 of file path.hpp.
Referenced by empty(), length(), Path(), time(), and timeGrid().
Array QuantLib::Path::values_ [private]
Definition at line 76 of file path.hpp.
Referenced by at(), back(), begin(), end(), front(), operator[](), Path(), rbegin(), rend(), and value().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/montecarlo/path.hpp