QuantLib: QuantLib::YoYInflationCoupon Class Reference
QuantLib::YoYInflationCoupon Class Reference
Coupon paying a YoY-inflation type index
#include <yoyinflationcoupon.hpp>
Public Member Functions
YoYInflationCoupon (const Date &paymentDate, Real nominal, const Date &startDate, const Date &endDate, Natural fixingDays, const boost::shared_ptr< YoYInflationIndex > &index, const Period &observationLag, const DayCounter &dayCounter, Real gearing=1.0, Spread spread=0.0, const Date &refPeriodStart=Date(), const Date &refPeriodEnd=Date())
Inspectors
Real gearing () const
index gearing, i.e. multiplicative coefficient for the index
Spread spread () const
spread paid over the fixing of the underlying index
Rate adjustedFixing () const
const boost::shared_ptr
< YoYInflationIndex > & yoyIndex () const
Visitability
virtual void accept (AcyclicVisitor &)
Protected Member Functions
bool checkPricerImpl (const boost::shared_ptr< InflationCouponPricer > &) const
makes sure you were given the correct type of pricer
Protected Attributes
Real gearing_
Spread spread_
Private Attributes
boost::shared_ptr
< YoYInflationIndex > yoyIndex_
Detailed Description
Coupon paying a YoY-inflation type index
Definition at line 35 of file yoyinflationcoupon.hpp.
Constructor & Destructor Documentation
QuantLib::YoYInflationCoupon::YoYInflationCoupon (const Date & paymentDate, Real nominal, const Date & startDate, const Date & endDate, Natural fixingDays, const boost::shared_ptr< YoYInflationIndex > & index, const Period & observationLag, const DayCounter & dayCounter, Real gearing = 1.0, Spread spread = 0.0, const Date & refPeriodStart = Date(), const Date & refPeriodEnd = Date())
Definition at line 29 of file yoyinflationcoupon.cpp.
    : InflationCoupon(paymentDate, nominal, startDate, endDate,
                  fixingDays, yoyIndex, observationLag,
                  dayCounter, refPeriodStart, refPeriodEnd),
    yoyIndex_(yoyIndex), gearing_(gearing), spread_(spread) {}
Member Function Documentation
void QuantLib::YoYInflationCoupon::accept (AcyclicVisitor & v) [virtual]
Reimplemented from QuantLib::InflationCoupon.
Reimplemented in QuantLib::CappedFlooredYoYInflationCoupon.
Definition at line 47 of file yoyinflationcoupon.cpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Visitor< T >::visit().
{
        Visitor<YoYInflationCoupon>* v1 =
        dynamic_cast<Visitor<YoYInflationCoupon>*>(&v);
        if (v1 != 0)
            v1->visit(*this);
        else
            InflationCoupon::accept(v);
    }
Rate QuantLib::YoYInflationCoupon::adjustedFixing () const [inline]
Definition at line 82 of file yoyinflationcoupon.hpp.
References gearing(), QuantLib::InflationCoupon::rate(), and spread().
{
        return (rate()-spread())/gearing();
    }
bool QuantLib::YoYInflationCoupon::checkPricerImpl (const boost::shared_ptr< InflationCouponPricer > &) const [protected, virtual]
makes sure you were given the correct type of pricer
Implements QuantLib::InflationCoupon.
Definition at line 57 of file yoyinflationcoupon.cpp.
References QuantLib::InflationCoupon::pricer().
{
        return boost::dynamic_pointer_cast<YoYInflationCouponPricer>(pricer);
    }
Real QuantLib::YoYInflationCoupon::gearing () const [inline]
index gearing, i.e. multiplicative coefficient for the index
Definition at line 54 of file yoyinflationcoupon.hpp.
References gearing_.
Referenced by adjustedFixing(), QuantLib::CappedFlooredYoYInflationCoupon::effectiveCap(), QuantLib::CappedFlooredYoYInflationCoupon::effectiveFloor(), and QuantLib::YoYInflationCouponPricer::initialize().
{ return gearing_; }
Spread QuantLib::YoYInflationCoupon::spread () const [inline]
spread paid over the fixing of the underlying index
Definition at line 56 of file yoyinflationcoupon.hpp.
References spread_.
Referenced by adjustedFixing(), QuantLib::CappedFlooredYoYInflationCoupon::effectiveCap(), QuantLib::CappedFlooredYoYInflationCoupon::effectiveFloor(), and QuantLib::YoYInflationCouponPricer::initialize().
{ return spread_; }
const boost::shared_ptr< YoYInflationIndex > & QuantLib::YoYInflationCoupon::yoyIndex () const [inline]
Definition at line 78 of file yoyinflationcoupon.hpp.
References yoyIndex_.
{
        return yoyIndex_;
    }
Member Data Documentation
Real QuantLib::YoYInflationCoupon::gearing_ [protected]
Definition at line 72 of file yoyinflationcoupon.hpp.
Referenced by QuantLib::CappedFlooredYoYInflationCoupon::cap(), QuantLib::CappedFlooredYoYInflationCoupon::floor(), gearing(), and QuantLib::CappedFlooredYoYInflationCoupon::setCommon().
Spread QuantLib::YoYInflationCoupon::spread_ [protected]
Definition at line 73 of file yoyinflationcoupon.hpp.
Referenced by spread().
boost::shared_ptr<YoYInflationIndex> QuantLib::YoYInflationCoupon::yoyIndex_ [private]
Definition at line 69 of file yoyinflationcoupon.hpp.
Referenced by yoyIndex().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/yoyinflationcoupon.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/yoyinflationcoupon.cpp