QuantLib: QuantLib::DayCounter Class Reference
QuantLib::DayCounter Class Reference
day counter class
#include <daycounter.hpp>
Classes
class Impl
abstract base class for day counter implementations
Public Member Functions
DayCounter ()
DayCounter interface
bool empty () const
Returns whether or not the day counter is initialized.
std::string name () const
Returns the name of the day counter.
BigInteger dayCount (const Date &, const Date &) const
Returns the number of days between two dates.
Time yearFraction (const Date &, const Date &, const Date &refPeriodStart=Date(), const Date &refPeriodEnd=Date()) const
Returns the period between two dates as a fraction of year.
Protected Member Functions
DayCounter (const boost::shared_ptr< Impl > &impl)
Protected Attributes
boost::shared_ptr< Impl > impl_
Related Functions
(Note that these are not member functions.)
bool operator== (const DayCounter &, const DayCounter &)
bool operator!= (const DayCounter &, const DayCounter &)
std::ostream & operator<< (std::ostream &, const DayCounter &)
Detailed Description
day counter class
This class provides methods for determining the length of a time period according to given market convention, both as a number of days and as a year fraction.
The Bridge pattern is used to provide the base behavior of the day counter.
Definition at line 43 of file daycounter.hpp.
Constructor & Destructor Documentation
QuantLib::DayCounter::DayCounter (const boost::shared_ptr< Impl > & impl) [inline, protected]
This constructor can be invoked by derived classes which define a given implementation.
Definition at line 64 of file daycounter.hpp.
: impl_(impl) {}
QuantLib::DayCounter::DayCounter () [inline]
The default constructor returns a day counter with a null implementation, which is therefore unusable except as a placeholder.
Definition at line 70 of file daycounter.hpp.
{}
Member Function Documentation
BigInteger QuantLib::DayCounter::dayCount (const Date & d1, const Date & d2) const [inline]
Returns the number of days between two dates.
Definition at line 120 of file daycounter.hpp.
References impl_, and QL_REQUIRE.
Referenced by QuantLib::Coupon::accrualDays(), QuantLib::Coupon::accruedDays(), QuantLib::SimpleDayCounter::Impl::dayCount(), QuantLib::Business252::Impl::yearFraction(), QuantLib::ActualActual::ISDA_Impl::yearFraction(), and QuantLib::ActualActual::AFB_Impl::yearFraction().
{
        QL_REQUIRE(impl_, "no implementation provided");
        return impl_->dayCount(d1,d2);
    }
bool QuantLib::DayCounter::empty () const [inline]
Returns whether or not the day counter is initialized.
Definition at line 111 of file daycounter.hpp.
References impl_.
Referenced by QuantLib::FloatingRateCoupon::FloatingRateCoupon(), QuantLib::FixedRateLeg::operator Leg(), QuantLib::operator==(), and QuantLib::SyntheticCDO::arguments::validate().
{
        return !impl_;
    }
std::string QuantLib::DayCounter::name () const [inline]
Returns the name of the day counter.
Warning:
This method is used for output and comparison between day counters. It is not meant to be used for writing switch-on-type code.
Definition at line 115 of file daycounter.hpp.
References impl_, and QL_REQUIRE.
Referenced by QuantLib::IborIndex::forecastFixing(), QuantLib::IborCoupon::IborCoupon(), QuantLib::InterestRateIndex::InterestRateIndex(), QuantLib::operator<<(), QuantLib::operator==(), and DayCounterTest::testActualActual().
{
        QL_REQUIRE(impl_, "no implementation provided");
        return impl_->name();
    }
Time QuantLib::DayCounter::yearFraction (const Date & d1, const Date & d2, const Date & refPeriodStart = Date(), const Date & refPeriodEnd = Date()) const [inline]
Returns the period between two dates as a fraction of year.
Definition at line 126 of file daycounter.hpp.
References impl_, and QL_REQUIRE.
Referenced by QuantLib::Coupon::accrualPeriod(), QuantLib::FloatingRateCoupon::accruedAmount(), QuantLib::InflationCoupon::accruedAmount(), QuantLib::Coupon::accruedPeriod(), QuantLib::ImpliedVolTermStructure::blackVarianceImpl(), QuantLib::AnalyticWriterExtensibleOptionEngine::calculate(), QuantLib::AnalyticSimpleChooserEngine::calculate(), QuantLib::LfmSwaptionEngine::calculate(), QuantLib::AnalyticPerformanceEngine::calculate(), QuantLib::VarianceGammaEngine::calculate(), QuantLib::BlackCdsOptionEngine::calculate(), QuantLib::FdG2SwaptionEngine::calculate(), QuantLib::AnalyticDividendEuropeanEngine::calculate(), QuantLib::FdHullWhiteSwaptionEngine::calculate(), QuantLib::BjerksundStenslandApproximationEngine::calculate(), QuantLib::AnalyticCliquetEngine::calculate(), QuantLib::AnalyticAmericanMargrabeEngine::calculate(), QuantLib::AnalyticCapFloorEngine::calculate(), QuantLib::AnalyticEuropeanMargrabeEngine::calculate(), QuantLib::JumpDiffusionEngine::calculate(), QuantLib::AnalyticDiscreteGeometricAverageStrikeAsianEngine::calculate(), QuantLib::BaroneAdesiWhaleyApproximationEngine::calculate(), QuantLib::TreeCapFloorEngine::calculate(), QuantLib::TreeCallableFixedRateBondEngine::calculate(), QuantLib::AnalyticContinuousGeometricAveragePriceAsianEngine::calculate(), QuantLib::AnalyticDiscreteGeometricAveragePriceAsianEngine::calculate(), QuantLib::BinomialConvertibleEngine< T >::calculate(), QuantLib::JamshidianSwaptionEngine::calculate(), QuantLib::JuQuadraticApproximationEngine::calculate(), QuantLib::AnalyticDigitalAmericanEngine::calculate(), QuantLib::AnalyticEuropeanEngine::calculate(), QuantLib::BinomialVanillaEngine< T >::calculate(), QuantLib::TreeSwaptionEngine::calculate(), QuantLib::MonteCarloCDOEngine2::calculate(), QuantLib::CommodityCurve::CommodityCurve(), QuantLib::InterestRate::compoundFactor(), QuantLib::CallableBondVolatilityStructure::convertDates(), QuantLib::CashFlows::convexity(), QuantLib::MonteCarloCDOEngine1::defaultScenarios(), QuantLib::InterestRate::discountFactor(), QuantLib::ImpliedTermStructure::discountImpl(), QuantLib::DiscretizedCallableFixedRateBond::DiscretizedCallableFixedRateBond(), QuantLib::DiscretizedCapFloor::DiscretizedCapFloor(), QuantLib::DiscretizedConvertible::DiscretizedConvertible(), QuantLib::DiscretizedSwap::DiscretizedSwap(), QuantLib::DiscretizedSwaption::DiscretizedSwaption(), QuantLib::InterestRate::equivalentRate(), QuantLib::SwingExercise::exerciseTimes(), QuantLib::RiskyAssetSwap::fairSpread(), QuantLib::FdmBermudanStepCondition::FdmBermudanStepCondition(), QuantLib::FdmDividendHandler::FdmDividendHandler(), QuantLib::RiskyAssetSwap::fixedAnnuity(), QuantLib::RiskyAssetSwap::floatAnnuity(), QuantLib::IborIndex::forecastFixing(), QuantLib::BlackCallableFixedRateBondEngine::forwardPriceVolatility(), QuantLib::FuturesRateHelper::FuturesRateHelper(), QuantLib::GeneralizedHullWhite::GeneralizedHullWhite(), QuantLib::ForwardPerformanceVanillaEngine< Engine >::getOriginalResults(), QuantLib::ForwardVanillaEngine< Engine >::getOriginalResults(), QuantLib::GFunctionFactory::GFunctionExactYield::GFunctionExactYield(), QuantLib::GFunctionFactory::GFunctionWithShifts::GFunctionWithShifts(), QuantLib::detail::HullWhiteCapFloorPricer::HullWhiteCapFloorPricer(), QuantLib::IborCoupon::IborCoupon(), QuantLib::InterestRate::impliedRate(), QuantLib::Forward::impliedYield(), QuantLib::inflationYearFraction(), QuantLib::InterpolatedDiscountCurve< Interpolator >::initialize(), QuantLib::InterpolatedZeroCurve< Interpolator >::initialize(), QuantLib::InterpolatedForwardCurve< Interpolator >::initialize(), QuantLib::InterpolatedHazardRateCurve< Interpolator >::initialize(), QuantLib::InterpolatedDefaultDensityCurve< Interpolator >::initialize(), QuantLib::HaganPricer::initialize(), QuantLib::SmileSection::initializeExerciseTime(), QuantLib::LiborForwardModelProcess::LiborForwardModelProcess(), QuantLib::anonymous_namespace{cashflows.cpp}::modifiedDuration(), QuantLib::OvernightIndexedCoupon::OvernightIndexedCoupon(), QuantLib::MCHullWhiteCapFloorEngine< RNG, S >::pathGenerator(), QuantLib::MCHullWhiteCapFloorEngine< RNG, S >::pathPricer(), QuantLib::RiskyAssetSwapOption::performCalculations(), QuantLib::OptionletStripper1::performCalculations(), QuantLib::CDO::performCalculations(), QuantLib::FFTVanillaEngine::precalculateExpiry(), QuantLib::FFTVarianceGammaEngine::precalculateExpiry(), QuantLib::RangeAccrualFloatersCoupon::RangeAccrualFloatersCoupon(), QuantLib::RiskyAssetSwap::riskyBondPrice(), QuantLib::Basket::scenarioIncrementalTrancheLosses(), QuantLib::Basket::scenarioTrancheLoss(), QuantLib::MultiplicativePriceSeasonality::seasonalityCorrection(), QuantLib::CommodityCurve::setPrices(), QuantLib::anonymous_namespace{cashflows.cpp}::simpleDuration(), QuantLib::StrippedOptionlet::StrippedOptionlet(), QuantLib::SubPeriodsCoupon::SubPeriodsCoupon(), QuantLib::G2::swaption(), DayCounterTest::testActualActual(), AsianOptionTest::testAnalyticContinuousGeometricAveragePriceGreeks(), AsianOptionTest::testAnalyticDiscreteGeometricAveragePriceGreeks(), HybridHestonHullWhiteProcessTest::testAnalyticHestonHullWhitePricing(), BatesModelTest::testAnalyticVsBlack(), HestonModelTest::testAnalyticVsBlack(), HestonModelTest::testAnalyticVsCached(), HestonModelTest::testBlackCalibration(), DayCounterTest::testBusiness252(), CreditDefaultSwapTest::testCachedMarketValue(), HybridHestonHullWhiteProcessTest::testCallableEquityPricing(), HybridHestonHullWhiteProcessTest::testCompareBsmHWandHestonHW(), DefaultProbabilityCurveTest::testDefaultProbability(), HybridHestonHullWhiteProcessTest::testDiscretizationError(), DividendOptionTest::testEuropeanGreeks(), SwingOptionTest::testExtOUJumpSwingOption(), SwingOptionTest::testExtOUJumpVanillaEngine(), FdmLinearOpTest::testFdmHestonHullWhiteOp(), DefaultProbabilityCurveTest::testFlatHazardRate(), QuantoOptionTest::testForwardGreeks(), anonymous_namespace{forwardoption.cpp}::testForwardGreeks(), MargrabeOptionTest::testGreeks(), JumpDiffusionTest::testGreeks(), EuropeanOptionTest::testGreeks(), QuantoOptionTest::testGreeks(), VPPTest::testKlugeExtOUSpreadOption(), HybridHestonHullWhiteProcessTest::testMcPureHestonPricing(), HybridHestonHullWhiteProcessTest::testMcVanillaPricing(), PiecewiseYieldCurveTest::testObservability(), DayCounterTest::testOne(), anonymous_namespace{cliquetoption.cpp}::testOptionGreeks(), DayCounterTest::testSimple(), VPPTest::testVPPPricing(), HybridHestonHullWhiteProcessTest::testZeroBondPricing(), QuantLib::YoYOptionletVolatilitySurface::timeFromBase(), QuantLib::CPIVolatilitySurface::timeFromBase(), QuantLib::TermStructure::timeFromReference(), QuantLib::MCDiscreteAveragingAsianEngine< RNG, S >::timeGrid(), QuantLib::MCHullWhiteCapFloorEngine< RNG, S >::timeGrid(), QuantLib::FittedBondDiscountCurve::FittingMethod::FittingCost::value(), QuantLib::FuturesConvAdjustmentQuote::value(), QuantLib::SimpleDayCounter::Impl::yearFraction(), QuantLib::ActualActual::ISDA_Impl::yearFraction(), and QuantLib::ActualActual::AFB_Impl::yearFraction().
{
            QL_REQUIRE(impl_, "no implementation provided");
            return impl_->yearFraction(d1,d2,refPeriodStart,refPeriodEnd);
    }
Friends And Related Function Documentation
bool operator!= (const DayCounter & , const DayCounter &) [related]
Definition at line 138 of file daycounter.hpp.
{
        return !(d1 == d2);
    }
std::ostream & operator<< (std::ostream & , const DayCounter &) [related]
Definition at line 142 of file daycounter.hpp.
{
        return out << d.name();
    }
bool operator== (const DayCounter & , const DayCounter &) [related]
Returns true iff the two day counters belong to the same derived class.
Definition at line 133 of file daycounter.hpp.
{
        return (d1.empty() && d2.empty())
            || (!d1.empty() && !d2.empty() && d1.name() == d2.name());
    }
Member Data Documentation
boost::shared_ptr<Impl> QuantLib::DayCounter::impl_ [protected]
Definition at line 60 of file daycounter.hpp.
Referenced by dayCount(), empty(), name(), and yearFraction().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/time/daycounter.hpp