QuantLib: QuantLib::RecoveryRateQuote Class Reference
QuantLib::RecoveryRateQuote Class Reference
Stores a recovery rate market quote and the associated seniority.
#include <recoveryratequote.hpp>
Public Member Functions
RecoveryRateQuote (Real value=Null< Real >(), Seniority seniority=NoSeniority)
Quote interface
Real value () const
returns the current value
Seniority seniority () const
bool isValid () const
returns true if the Quote holds a valid value
Modifiers
Real setValue (Real value=Null< Real >())
returns the difference between the new value and the old value
void reset ()
Static Public Member Functions
static Real conventionalRecovery (Seniority sen)
template<Size N>
static const std::map
< Seniority, Real > makeIsdaMap (const Real(&(arrayIsdaRR))[N])
Private Attributes
Seniority seniority_
Real recoveryRate_
Static Private Attributes
static const Real IsdaConvRecoveries []
Friends
std::map< Seniority, Real > makeIsdaConvMap ()
Helper function for conventional recoveries. Returns the ISDA.
Detailed Description
Stores a recovery rate market quote and the associated seniority.
Definition at line 30 of file recoveryratequote.hpp.
Constructor & Destructor Documentation
QuantLib::RecoveryRateQuote::RecoveryRateQuote (Real value = Null<Real>(), Seniority seniority = NoSeniority)
Definition at line 37 of file recoveryratequote.cpp.
References QL_REQUIRE.
        : seniority_(seniority), recoveryRate_(value) {
            QL_REQUIRE(value == Null<Real>() ||
                (value >= 0. && value <= 1.),
                "Recovery value must be a fractional unit.");
    }
Member Function Documentation
static Real QuantLib::RecoveryRateQuote::conventionalRecovery (Seniority sen) [inline, static]
Returns a map with the ISDA conventional (values by default) of the recovery rate per each ISDA seniority.
Definition at line 36 of file recoveryratequote.hpp.
References IsdaConvRecoveries.
{
            return IsdaConvRecoveries[sen];
        }
bool QuantLib::RecoveryRateQuote::isValid () const [inline, virtual]
returns true if the Quote holds a valid value
Implements QuantLib::Quote.
Definition at line 79 of file recoveryratequote.hpp.
References recoveryRate_.
Referenced by value().
{
        // not to be consufed with proper initialization [0-1]
        return recoveryRate_!=Null<Real>();/* &&
            seniority_ != NoSeniority;*/
    }
template<Size N> const std::map< Seniority, Real > QuantLib::RecoveryRateQuote::makeIsdaMap (const Real(&(arrayIsdaRR))[N]) [static]
Turn a set of recoveries into a seniority-recovery map (intended to be used in an event construction)
Definition at line 95 of file recoveryratequote.hpp.
References anonymous_namespace{matrices.cpp}::N.
Referenced by QuantLib::makeIsdaConvMap().
{
        // TO DO: include check on sizes... not to go beyond enum sizes.
        // TO DO: check Reals are valid, i.e. non Null and within [0-1] range
        std::map<Seniority, Real> isdaMap;
        for(Size i=0; i<N; i++) {
            Seniority isdaType = Seniority(i);//compiler dependent?
            isdaMap[isdaType] = arrayIsdaRR[i];
        }
        return isdaMap;
    }
void QuantLib::RecoveryRateQuote::reset ()
Definition at line 54 of file recoveryratequote.cpp.
References QuantLib::NoSeniority, seniority_, and setValue().
{
        setValue(Null<Real>());
        seniority_ = NoSeniority;
    }
Seniority QuantLib::RecoveryRateQuote::seniority () const [inline]
Definition at line 70 of file recoveryratequote.hpp.
References seniority_.
{
        return seniority_;
    }
Real QuantLib::RecoveryRateQuote::setValue (Real value = Null<Real>())
returns the difference between the new value and the old value
Definition at line 45 of file recoveryratequote.cpp.
References QuantLib::Observable::notifyObservers(), recoveryRate_, and value().
Referenced by reset().
{
        Real diff = value-recoveryRate_;
        if (diff != 0.0) {
            recoveryRate_ = value;
            notifyObservers();
        }
        return diff;
    }
Real QuantLib::RecoveryRateQuote::value () const [inline, virtual]
returns the current value
Implements QuantLib::Quote.
Definition at line 74 of file recoveryratequote.hpp.
References isValid(), QL_ENSURE, and recoveryRate_.
Referenced by setValue().
{
        QL_ENSURE(isValid(), "invalid Recovery Quote");
        return recoveryRate_;
    }
Friends And Related Function Documentation
std::map<Seniority, Real> makeIsdaConvMap () [friend]
Helper function for conventional recoveries. Returns the ISDA.
Definition at line 32 of file recoveryratequote.cpp.
{
        return RecoveryRateQuote::makeIsdaMap(
            RecoveryRateQuote::IsdaConvRecoveries);
    }
Member Data Documentation
const Real QuantLib::RecoveryRateQuote::IsdaConvRecoveries [static, private]
Initial value:
  {
        0.65,
        0.4,
        0.2,
        0.2,
        0.15
    }
Definition at line 63 of file recoveryratequote.hpp.
Referenced by conventionalRecovery(), and QuantLib::makeIsdaConvMap().
Real QuantLib::RecoveryRateQuote::recoveryRate_ [private]
Definition at line 67 of file recoveryratequote.hpp.
Referenced by isValid(), setValue(), and value().
Seniority QuantLib::RecoveryRateQuote::seniority_ [private]
Definition at line 65 of file recoveryratequote.hpp.
Referenced by reset(), and seniority().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/recoveryratequote.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/recoveryratequote.cpp