QuantLib: SpreadOptionTest Class Reference
SpreadOptionTest Class Reference
#include <spreadoption.hpp>
Static Public Member Functions
static void testKirkEngine ()
static
boost::unit_test_framework::test_suite * suite ()
Detailed Description
Definition at line 28 of file spreadoption.hpp.
Member Function Documentation
test_suite * SpreadOptionTest::suite () [static]
Definition at line 161 of file spreadoption.cpp.
References QUANTLIB_TEST_CASE, and testKirkEngine().
Referenced by init_unit_test_suite().
{
    test_suite* suite = BOOST_TEST_SUITE("Spread option tests");
    suite->add(QUANTLIB_TEST_CASE(&SpreadOptionTest::testKirkEngine));
    return suite;
}
void SpreadOptionTest::testKirkEngine () [static]
Definition at line 64 of file spreadoption.cpp.
References QuantLib::Option::Call, QuantLib::flatRate(), QuantLib::flatVol(), LENGTH, Case::length, QuantLib::Instrument::NPV(), Case::r, REPORT_FAILURE, Case::result, QuantLib::Instrument::setPricingEngine(), Case::sigma1, Case::sigma2, anonymous_namespace{marketmodel.cpp}::todaysDate, anonymous_namespace{gaussianquadratures.cpp}::tolerance, and Case::X.
Referenced by suite().
{
    BOOST_MESSAGE("Testing Kirk approximation for spread options...");
    /* The example data below are from "complete guide to option
       pricing formulas", Espen Gaarder Haug, p 60 */
    Case cases[] = {
        {  28.0,  20.0, 7.0, 0.05, 0.29, 0.36,  0.42, 90,  2.1670 },
        { 122.0, 120.0, 3.0, 0.10, 0.20, 0.20, -0.5,  36,  4.7530 },
        { 122.0, 120.0, 3.0, 0.10, 0.20, 0.20,  0.0,  36,  3.7970 },
        { 122.0, 120.0, 3.0, 0.10, 0.20, 0.20,  0.5,  36,  2.5537 },
        { 122.0, 120.0, 3.0, 0.10, 0.20, 0.20, -0.5, 180, 10.7517 },
        { 122.0, 120.0, 3.0, 0.10, 0.20, 0.20,  0.0, 180,  8.7020 },
        { 122.0, 120.0, 3.0, 0.10, 0.20, 0.20,  0.5, 180,  6.0257 },
        { 122.0, 120.0, 3.0, 0.10, 0.25, 0.20, -0.5,  36,  5.4275 },
        { 122.0, 120.0, 3.0, 0.10, 0.25, 0.20,  0.0,  36,  4.3712 },
        { 122.0, 120.0, 3.0, 0.10, 0.25, 0.20,  0.5,  36,  3.0086 },
        { 122.0, 120.0, 3.0, 0.10, 0.25, 0.20, -0.5, 180, 12.1941 },
        { 122.0, 120.0, 3.0, 0.10, 0.25, 0.20,  0.0, 180,  9.9340 },
        { 122.0, 120.0, 3.0, 0.10, 0.25, 0.20,  0.5, 180,  7.0067 },
        { 122.0, 120.0, 3.0, 0.10, 0.20, 0.25, -0.5,  36,  5.4061 },
        { 122.0, 120.0, 3.0, 0.10, 0.20, 0.25,  0.0,  36,  4.3451 },
        { 122.0, 120.0, 3.0, 0.10, 0.20, 0.25,  0.5,  36,  2.9723 },
        { 122.0, 120.0, 3.0, 0.10, 0.20, 0.25, -0.5, 180, 12.1483 },
        { 122.0, 120.0, 3.0, 0.10, 0.20, 0.25,  0.0, 180,  9.8780 },
        { 122.0, 120.0, 3.0, 0.10, 0.20, 0.25,  0.5, 180,  6.9284 }
    };
    for (Size i=0; i<LENGTH(cases); ++i) {
        // First step: preparing the test values
        // Useful dates
        DayCounter dc = Actual360();
        Date today = Date::todaysDate();
        Date exerciseDate = today  + cases[i].length;
        // Futures values
        boost::shared_ptr<SimpleQuote> F1(new SimpleQuote(cases[i].F1));
        boost::shared_ptr<SimpleQuote> F2(new SimpleQuote(cases[i].F2));
        // Risk-free interest rate
        Rate riskFreeRate = cases[i].r;
        boost::shared_ptr<YieldTermStructure> forwardRate =
            flatRate(today,riskFreeRate,dc);
        // Correlation
        boost::shared_ptr<Quote> rho(new SimpleQuote(cases[i].rho));
        // Volatilities
        Volatility vol1 = cases[i].sigma1;
        Volatility vol2 = cases[i].sigma2;
        boost::shared_ptr<BlackVolTermStructure> volTS1 =
            flatVol(today,vol1,dc);
        boost::shared_ptr<BlackVolTermStructure> volTS2 =
            flatVol(today,vol2,dc);
        // Black-Scholes Processes
        // The BlackProcess is the relevant class for futures contracts
        boost::shared_ptr<BlackProcess> stochProcess1(
                     new BlackProcess(Handle<Quote>(F1),
                                      Handle<YieldTermStructure>(forwardRate),
                                      Handle<BlackVolTermStructure>(volTS1)));
        boost::shared_ptr<BlackProcess> stochProcess2(
                     new BlackProcess(Handle<Quote>(F2),
                                      Handle<YieldTermStructure>(forwardRate),
                                      Handle<BlackVolTermStructure>(volTS2)));
        // Creating the pricing engine
        boost::shared_ptr<PricingEngine> engine(
                      new KirkSpreadOptionEngine(stochProcess1, stochProcess2,
                                                 Handle<Quote>(rho)));
        // Finally, create the option:
        Option::Type type = Option::Call;
        Real strike = cases[i].X;
        boost::shared_ptr<PlainVanillaPayoff> payoff(
                                        new PlainVanillaPayoff(type, strike));
        boost::shared_ptr<Exercise> exercise(
                                          new EuropeanExercise(exerciseDate));
        SpreadOption option(payoff, exercise);
        option.setPricingEngine(engine);
        // And test the data
        Real calculated = option.NPV();
        Real expected = cases[i].result;
        Real tolerance = 1e-4;
        if (std::fabs(calculated-expected) > tolerance) {
            REPORT_FAILURE("value",
                           payoff, exercise,
                           expected, calculated, tolerance);
        }
    }
}
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/spreadoption.hpp
/home/deriversatile/QuantLib/QuantLibQt/test-suite/spreadoption.cpp