QuantLib: QuantLib::Clone< T > Class Template Reference
QuantLib::Clone< T > Class Template Reference
cloning proxy to an underlying object
#include <clone.hpp>
Public Member Functions
Clone ()
Clone (std::auto_ptr< T >)
Clone (const T &)
Clone (const Clone< T > &)
Clone< T > & operator= (const T &)
Clone< T > & operator= (const Clone< T > &)
T & operator* () const
T * operator-> () const
bool empty () const
void swap (Clone< T > &t)
Private Attributes
boost::scoped_ptr< T > ptr_
Related Functions
(Note that these are not member functions.)
template<class T >
void swap (Clone< T > &, Clone< T > &)
Detailed Description
template<class T>
class QuantLib::Clone< T >
cloning proxy to an underlying object
When copied, this class will make a clone of its underlying object (which must provide a clone() method returning a std::auto_ptr to a newly-allocated instance.)
Definition at line 40 of file clone.hpp.
Constructor & Destructor Documentation
template<class T > QuantLib::Clone< T >::Clone () [inline]
Definition at line 64 of file clone.hpp.
{}
template<class T> QuantLib::Clone< T >::Clone (std::auto_ptr< T > p) [inline]
Definition at line 67 of file clone.hpp.
    : ptr_(p) {}
template<class T> QuantLib::Clone< T >::Clone (const T & t) [inline]
Definition at line 71 of file clone.hpp.
    : ptr_(t.clone().release()) {}
template<class T> QuantLib::Clone< T >::Clone (const Clone< T > & t) [inline]
Definition at line 75 of file clone.hpp.
    : ptr_(t.empty() ? (T*)(0) : t->clone().release()) {}
Member Function Documentation
template<class T > bool QuantLib::Clone< T >::empty () const [inline]
Definition at line 102 of file clone.hpp.
Referenced by QuantLib::CallSpecifiedMultiProduct::CallSpecifiedMultiProduct(), QuantLib::CallSpecifiedPathwiseMultiProduct::CallSpecifiedPathwiseMultiProduct(), and QuantLib::Clone< T >::operator=().
{
        return !ptr_;
    }
template<class T > T & QuantLib::Clone< T >::operator* () const [inline]
Definition at line 91 of file clone.hpp.
References QL_REQUIRE.
{
        QL_REQUIRE(!this->empty(), "no underlying objects");
        return *(this->ptr_);
    }
template<class T > T * QuantLib::Clone< T >::operator-> () const [inline]
Definition at line 97 of file clone.hpp.
{
        return this->ptr_.get();
    }
template<class T> Clone< T > & QuantLib::Clone< T >::operator= (const T & t) [inline]
Definition at line 79 of file clone.hpp.
{
        ptr_.reset(t.clone().release());
        return *this;
    }
template<class T> Clone< T > & QuantLib::Clone< T >::operator= (const Clone< T > & t) [inline]
Definition at line 85 of file clone.hpp.
References QuantLib::Clone< T >::empty().
{
        ptr_.reset(t.empty() ? (T*)(0) : t->clone().release());
        return *this;
    }
template<class T> void QuantLib::Clone< T >::swap (Clone< T > & t) [inline]
Definition at line 107 of file clone.hpp.
References QuantLib::Clone< T >::ptr_.
Referenced by QuantLib::swap().
{
        this->ptr_.swap(t.ptr_);
    }
Friends And Related Function Documentation
template<class T > void swap (Clone< T > & , Clone< T > &) [related]
Definition at line 112 of file clone.hpp.
{
        t.swap(u);
    }
Member Data Documentation
template<class T> boost::scoped_ptr<T> QuantLib::Clone< T >::ptr_ [private]
Definition at line 53 of file clone.hpp.
Referenced by QuantLib::Clone< T >::swap().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/utilities/clone.hpp