QuantLib: NthToDefaultTest Class Reference
NthToDefaultTest Class Reference
#include <nthtodefault.hpp>
Static Public Member Functions
static void testGauss ()
static void testGaussStudent ()
static
boost::unit_test_framework::test_suite * suite ()
Detailed Description
Definition at line 28 of file nthtodefault.hpp.
Member Function Documentation
test_suite * NthToDefaultTest::suite () [static]
Definition at line 307 of file nthtodefault.cpp.
References QUANTLIB_TEST_CASE, testGauss(), and testGaussStudent().
Referenced by init_unit_test_suite().
{
    test_suite* suite = BOOST_TEST_SUITE("Nth-to-default tests");
    suite->add(QUANTLIB_TEST_CASE(&NthToDefaultTest::testGauss));
    suite->add(QUANTLIB_TEST_CASE(&NthToDefaultTest::testGaussStudent));
    return suite;
}
void NthToDefaultTest::testGauss () [static]
Definition at line 93 of file nthtodefault.cpp.
References QuantLib::August, anonymous_namespace{marketmodel.cpp}::c, QuantLib::Continuous, QuantLib::Settings::evaluationDate(), QuantLib::NthToDefault::fairPremium(), QuantLib::CreditDefaultSwap::fairSpread(), QuantLib::Following, QuantLib::MakeSchedule::from(), anonymous_namespace{nthtodefault.cpp}::hwCorrelation, anonymous_namespace{nthtodefault.cpp}::hwData, QuantLib::Singleton< Settings >::instance(), LENGTH, anonymous_namespace{brownianbridge.cpp}::maxDiff(), QuantLib::Months, QL_REQUIRE, QuantLib::io::rate(), QuantLib::Protection::Seller, QuantLib::September, QuantLib::Instrument::setPricingEngine(), anonymous_namespace{nthtodefault.cpp}::hwDatum::spread, QuantLib::MakeSchedule::to(), QuantLib::Weeks, QuantLib::MakeSchedule::withCalendar(), QuantLib::MakeSchedule::withTenor(), and QuantLib::Years.
Referenced by suite().
{
    BOOST_MESSAGE("Testing nth-to-default against Hull-White values "
                  "with Gaussian copula...");
    SavedSettings backup;
    /*************************
     * Tolerances
     */
    Real relTolerance = 0.015; // relative difference
    Real absTolerance = 1; // absolute difference in bp
    Period timeUnit = 1*Weeks; // required to reach accuracy
    Size names = 10;
    QL_REQUIRE (LENGTH(hwData) == names, "hwData length does not match");
    Real rate = 0.05;
    DayCounter dc = Actual365Fixed();
    Compounding cmp = Continuous; // Simple;
    Real recovery = 0.4;
    vector<Real> lambda (names, 0.01);
    Schedule schedule = MakeSchedule().from(Date (1, September, 2006))
                                      .to(Date (1, September, 2011))
                                      .withTenor(3*Months)
                                      .withCalendar(TARGET());
    Date asofDate(31, August, 2006);
    Settings::instance().evaluationDate() = asofDate;
    vector<Date> gridDates;
    gridDates.push_back (asofDate);
    gridDates.push_back (TARGET().advance (asofDate, Period (1, Years)));
    gridDates.push_back (TARGET().advance (asofDate, Period (5, Years)));
    gridDates.push_back (TARGET().advance (asofDate, Period (7, Years)));
    boost::shared_ptr<YieldTermStructure> yieldPtr (
                                   new FlatForward (asofDate, rate, dc, cmp));
    Handle<YieldTermStructure> yieldHandle (yieldPtr);
    vector<Handle<DefaultProbabilityTermStructure> > probabilities;
    Period maxTerm (10, Years);
    for (Size i = 0; i < lambda.size(); i++) {
        Handle<Quote> h(boost::shared_ptr<Quote>(new SimpleQuote(lambda[i])));
        boost::shared_ptr<DefaultProbabilityTermStructure> ptr (
                                         new FlatHazardRate(asofDate, h, dc));
        probabilities.push_back(Handle<DefaultProbabilityTermStructure>(ptr));
    }
    boost::shared_ptr<SimpleQuote> simpleQuote (new SimpleQuote(0.0));
    Handle<Quote> correlationHandle (simpleQuote);
    boost::shared_ptr<OneFactorCopula> gaussianCopula (
                             new OneFactorGaussianCopula (correlationHandle));
    Handle<OneFactorCopula> copula (gaussianCopula);
    vector<Handle<DefaultProbabilityTermStructure> > singleProbability;
    singleProbability.push_back (probabilities[0]);
    CreditDefaultSwap cds (Protection::Seller, 100.0, 0.02,
                           schedule, Following, Actual360());
    cds.setPricingEngine(boost::shared_ptr<PricingEngine>(
                             new IntegralCdsEngine(timeUnit, probabilities[0],
                                                   recovery, yieldHandle)));
    NthToDefault ftd (1, singleProbability, recovery, copula,
                      Protection::Seller, 100.0, schedule, 0.02,
                      Actual360(), true, yieldHandle, timeUnit);
    Real diff, maxDiff = 0;
    for (Real c = 0; c <= 0.8; c += 0.1) {
        simpleQuote->setValue (c);
        diff = 1e4 * cds.fairSpread() - 1e4 * ftd.fairPremium();
        maxDiff = max (maxDiff, fabs (diff));
    }
    Real tinyTolerance = 0.1;
    BOOST_REQUIRE_MESSAGE (maxDiff < tinyTolerance,
                           "tolerance " << tinyTolerance << " exceeded");
    vector<NthToDefault> ntd;
    for (Size i = 1; i <= probabilities.size(); i++)
        ntd.push_back (NthToDefault (i, probabilities, recovery,
                                     copula, Protection::Seller,
                                     100.0, schedule, 0.02, Actual360(),
                                     true, yieldHandle, timeUnit));
    QL_REQUIRE (LENGTH(hwCorrelation) == 3,
                "correlation length does not match");
    maxDiff = 0;
    for (Size j = 0; j < LENGTH(hwCorrelation); j++) {
        simpleQuote->setValue (hwCorrelation[j]);
        for (Size i = 0; i < ntd.size(); i++) {
            QL_REQUIRE (ntd[i].rank() == hwData[i].rank, "rank does not match");
            QL_REQUIRE (LENGTH(hwCorrelation) == LENGTH(hwData[i].spread),
                        "vector length does not match");
            diff = 1e4 * ntd[i].fairPremium() - hwData[i].spread[j];
            maxDiff = max (maxDiff, fabs (diff));
            BOOST_CHECK_MESSAGE (fabs(diff/hwData[i].spread[j]) < relTolerance
                                 || fabs(diff) < absTolerance,
                                 "tolerance " << relTolerance << "|"
                                 << absTolerance << " exceeded");
        }
    }
}
void NthToDefaultTest::testGaussStudent () [static]
Definition at line 203 of file nthtodefault.cpp.
References QuantLib::August, QuantLib::Continuous, QuantLib::Settings::evaluationDate(), QuantLib::MakeSchedule::from(), anonymous_namespace{nthtodefault.cpp}::hwCorrelation, anonymous_namespace{nthtodefault.cpp}::hwDataDist, QuantLib::Singleton< Settings >::instance(), LENGTH, QuantLib::RelinkableHandle< T >::linkTo(), anonymous_namespace{brownianbridge.cpp}::maxDiff(), QuantLib::Months, QL_REQUIRE, QuantLib::io::rate(), QuantLib::Protection::Seller, QuantLib::September, anonymous_namespace{nthtodefault.cpp}::hwDatumDist::spread, QuantLib::MakeSchedule::to(), QuantLib::Weeks, QuantLib::MakeSchedule::withCalendar(), QuantLib::MakeSchedule::withTenor(), and QuantLib::Years.
Referenced by suite().
{
    BOOST_MESSAGE ("Testing nth-to-default against Hull-White values "
                   "with Gaussian and Student copula...");
    SavedSettings backup;
    /*************************
     * Tolerances
     */
    Real relTolerance = 0.015; // relative difference
    Real absTolerance = 1; // absolute difference in bp
    Period timeUnit = 1*Weeks; // required to reach accuracy
    Size names = 10;
    QL_REQUIRE (LENGTH(hwDataDist) == names,
                "hwDataDist length does not match");
    Real rate = 0.05;
    DayCounter dc = Actual365Fixed();
    Compounding cmp = Continuous; // Simple;
    Real recovery = 0.4;
    vector<Real> lambda (names, 0.01);
    Schedule schedule = MakeSchedule().from(Date (1, September, 2006))
                                      .to(Date (1, September, 2011))
                                      .withTenor(3*Months)
                                      .withCalendar(TARGET());
    Date asofDate(31, August, 2006);
    Settings::instance().evaluationDate() = asofDate;
    vector<Date> gridDates;
    gridDates.push_back (asofDate);
    gridDates.push_back (TARGET().advance (asofDate, Period (1, Years)));
    gridDates.push_back (TARGET().advance (asofDate, Period (5, Years)));
    gridDates.push_back (TARGET().advance (asofDate, Period (7, Years)));
    boost::shared_ptr<YieldTermStructure> yieldPtr (new FlatForward (asofDate, rate, dc, cmp));
    Handle<YieldTermStructure> yieldHandle (yieldPtr);
    vector<Handle<DefaultProbabilityTermStructure> > probabilities;
    Period maxTerm (10, Years);
    for (Size i = 0; i < lambda.size(); i++) {
        Handle<Quote> h(boost::shared_ptr<Quote>(new SimpleQuote(lambda[i])));
        boost::shared_ptr<DefaultProbabilityTermStructure> ptr (
                                         new FlatHazardRate(asofDate, h, dc));
        probabilities.push_back(Handle<DefaultProbabilityTermStructure>(ptr));
    }
    boost::shared_ptr<SimpleQuote> simpleQuote (new SimpleQuote(0.3));
    Handle<Quote> correlationHandle (simpleQuote);
    boost::shared_ptr<OneFactorCopula> gaussianCopula (
                             new OneFactorGaussianCopula (correlationHandle));
    boost::shared_ptr<OneFactorCopula> studentCopula (
                        new OneFactorStudentCopula (correlationHandle, 5, 5));
    RelinkableHandle<OneFactorCopula> copula;
    vector<NthToDefault> ntd;
    for (Size i = 1; i <= probabilities.size(); i++)
        ntd.push_back (NthToDefault (i, probabilities, recovery,
                                     copula, Protection::Seller,
                                     100.0, schedule, 0.02, Actual360(),
                                     true, yieldHandle, timeUnit));
    QL_REQUIRE (LENGTH(hwCorrelation) == 3,
                "correlation length does not match");
    Real maxDiff = 0;
    simpleQuote->setValue (0.3);
    copula.linkTo (gaussianCopula);
    for (Size i = 0; i < ntd.size(); i++) {
        QL_REQUIRE (ntd[i].rank() == hwDataDist[i].rank, "rank does not match");
        Real diff = 1e4 * ntd[i].fairPremium() - hwDataDist[i].spread[0];
        maxDiff = max (maxDiff, fabs (diff));
        BOOST_CHECK_MESSAGE (fabs(diff / hwDataDist[i].spread[0]) ||
                             fabs(diff) < absTolerance,
                             "tolerance " << relTolerance << "|"
                             << absTolerance << " exceeded");
    }
    copula.linkTo (studentCopula);
    maxDiff = 0;
    for (Size i = 0; i < ntd.size(); i++) {
        QL_REQUIRE (ntd[i].rank() == hwDataDist[i].rank, "rank does not match");
        Real diff = 1e4 * ntd[i].fairPremium() - hwDataDist[i].spread[3];
        maxDiff = max (maxDiff, fabs (diff));
        BOOST_CHECK_MESSAGE (fabs(diff / hwDataDist[i].spread[3]) ||
                             fabs(diff) < absTolerance,
                             "tolerance " << relTolerance << "|"
                             << absTolerance << " exceeded");
    }
}
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/nthtodefault.hpp
/home/deriversatile/QuantLib/QuantLibQt/test-suite/nthtodefault.cpp