QuantLib: QuantLib::VanillaSwap::results Class Reference
QuantLib::VanillaSwap::results Class Reference
Results from simple swap calculation
#include <vanillaswap.hpp>
Public Member Functions
void reset ()
Public Attributes
Rate fairRate
Spread fairSpread
Detailed Description
Results from simple swap calculation
Definition at line 156 of file vanillaswap.hpp.
Member Function Documentation
void QuantLib::VanillaSwap::results::reset () [virtual]
Reimplemented from QuantLib::Swap::results.
Definition at line 234 of file vanillaswap.cpp.
References QuantLib::VanillaSwap::fairRate(), QuantLib::VanillaSwap::fairSpread(), and anonymous_namespace{inflationvolatility.cpp}::reset().
{
        Swap::results::reset();
        fairRate = Null<Rate>();
        fairSpread = Null<Spread>();
    }
Member Data Documentation
Rate QuantLib::VanillaSwap::results::fairRate
Definition at line 158 of file vanillaswap.hpp.
Referenced by QuantLib::VanillaSwap::fetchResults().
Spread QuantLib::VanillaSwap::results::fairSpread
Definition at line 159 of file vanillaswap.hpp.
Referenced by QuantLib::VanillaSwap::fetchResults().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/vanillaswap.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/vanillaswap.cpp