QuantLib: QuantLib::detail::LinearInterpolationImpl< I1, I2 > Class Template Reference
QuantLib::detail::LinearInterpolationImpl< I1, I2 > Class Template Reference
#include <linearinterpolation.hpp>
Public Member Functions
LinearInterpolationImpl (const I1 &xBegin, const I1 &xEnd, const I2 &yBegin)
void update ()
Real value (Real x) const
Real primitive (Real x) const
Real derivative (Real x) const
Real secondDerivative (Real) const
Private Attributes
std::vector< Real > primitiveConst_
std::vector< Real > s_
Detailed Description
template<class I1, class I2>
class QuantLib::detail::LinearInterpolationImpl< I1, I2 >
Definition at line 36 of file linearinterpolation.hpp.
Constructor & Destructor Documentation
template<class I1 , class I2 > QuantLib::detail::LinearInterpolationImpl< I1, I2 >::LinearInterpolationImpl (const I1 & xBegin, const I1 & xEnd, const I2 & yBegin) [inline]
Definition at line 39 of file linearinterpolation.hpp.
            : Interpolation::templateImpl<I1,I2>(xBegin, xEnd, yBegin),
              primitiveConst_(xEnd-xBegin), s_(xEnd-xBegin) {}
Member Function Documentation
template<class I1 , class I2 > Real QuantLib::detail::LinearInterpolationImpl< I1, I2 >::derivative (Real x) const [inline, virtual]
Implements QuantLib::Interpolation::Impl.
Definition at line 62 of file linearinterpolation.hpp.
References QuantLib::Interpolation::templateImpl< I1, I2 >::locate(), and QuantLib::detail::LinearInterpolationImpl< I1, I2 >::s_.
{
                Size i = this->locate(x);
                return s_[i];
            }
template<class I1 , class I2 > Real QuantLib::detail::LinearInterpolationImpl< I1, I2 >::primitive (Real x) const [inline, virtual]
Implements QuantLib::Interpolation::Impl.
Definition at line 56 of file linearinterpolation.hpp.
References QuantLib::Interpolation::templateImpl< I1, I2 >::locate(), QuantLib::detail::LinearInterpolationImpl< I1, I2 >::primitiveConst_, QuantLib::detail::LinearInterpolationImpl< I1, I2 >::s_, QuantLib::Interpolation::templateImpl< I1, I2 >::xBegin_, and QuantLib::Interpolation::templateImpl< I1, I2 >::yBegin_.
{
                Size i = this->locate(x);
                Real dx = x-this->xBegin_[i];
                return primitiveConst_[i] +
                    dx*(this->yBegin_[i] + 0.5*dx*s_[i]);
            }
template<class I1 , class I2 > Real QuantLib::detail::LinearInterpolationImpl< I1, I2 >::secondDerivative (Real) const [inline, virtual]
Implements QuantLib::Interpolation::Impl.
Definition at line 66 of file linearinterpolation.hpp.
{
                return 0.0;
            }
template<class I1 , class I2 > void QuantLib::detail::LinearInterpolationImpl< I1, I2 >::update () [inline, virtual]
Implements QuantLib::Interpolation::Impl.
Definition at line 43 of file linearinterpolation.hpp.
References QuantLib::detail::LinearInterpolationImpl< I1, I2 >::primitiveConst_, QuantLib::detail::LinearInterpolationImpl< I1, I2 >::s_, QuantLib::Interpolation::templateImpl< I1, I2 >::xBegin_, QuantLib::Interpolation::templateImpl< I1, I2 >::xEnd_, and QuantLib::Interpolation::templateImpl< I1, I2 >::yBegin_.
{
                primitiveConst_[0] = 0.0;
                for (Size i=1; i<Size(this->xEnd_-this->xBegin_); ++i) {
                    Real dx = this->xBegin_[i]-this->xBegin_[i-1];
                    s_[i-1] = (this->yBegin_[i]-this->yBegin_[i-1])/dx;
                    primitiveConst_[i] = primitiveConst_[i-1]
                        + dx*(this->yBegin_[i-1] +0.5*dx*s_[i-1]);
                }
            }
template<class I1 , class I2 > Real QuantLib::detail::LinearInterpolationImpl< I1, I2 >::value (Real x) const [inline, virtual]
Implements QuantLib::Interpolation::Impl.
Definition at line 52 of file linearinterpolation.hpp.
References QuantLib::Interpolation::templateImpl< I1, I2 >::locate(), QuantLib::detail::LinearInterpolationImpl< I1, I2 >::s_, QuantLib::Interpolation::templateImpl< I1, I2 >::xBegin_, and QuantLib::Interpolation::templateImpl< I1, I2 >::yBegin_.
{
                Size i = this->locate(x);
                return this->yBegin_[i] + (x-this->xBegin_[i])*s_[i];
            }
Member Data Documentation
template<class I1 , class I2 > std::vector<Real> QuantLib::detail::LinearInterpolationImpl< I1, I2 >::primitiveConst_ [private]
Definition at line 70 of file linearinterpolation.hpp.
Referenced by QuantLib::detail::LinearInterpolationImpl< I1, I2 >::primitive(), and QuantLib::detail::LinearInterpolationImpl< I1, I2 >::update().
template<class I1 , class I2 > std::vector<Real> QuantLib::detail::LinearInterpolationImpl< I1, I2 >::s_ [private]
Definition at line 70 of file linearinterpolation.hpp.
Referenced by QuantLib::detail::LinearInterpolationImpl< I1, I2 >::derivative(), QuantLib::detail::LinearInterpolationImpl< I1, I2 >::primitive(), QuantLib::detail::LinearInterpolationImpl< I1, I2 >::update(), and QuantLib::detail::LinearInterpolationImpl< I1, I2 >::value().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/interpolations/linearinterpolation.hpp