QuantLib: QuantLib::FFTVanillaEngine Class Reference
QuantLib::FFTVanillaEngine Class Reference
FFT Pricing engine vanilla options under a Black Scholes process.
#include <fftvanillaengine.hpp>
Public Member Functions
FFTVanillaEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > &process, Real logStrikeSpacing=0.001)
virtual std::auto_ptr< FFTEngine > clone () const
Protected Member Functions
virtual void precalculateExpiry (Date d)
virtual std::complex< Real > complexFourierTransform (std::complex< Real > u) const
virtual Real discountFactor (Date d) const
virtual Real dividendYield (Date d) const
Private Attributes
DiscountFactor dividendDiscount_
DiscountFactor riskFreeDiscount_
Time t_
Real var_
Detailed Description
FFT Pricing engine vanilla options under a Black Scholes process.
Test:
the correctness of the returned values is tested by comparison with Black Scholes pricing.
Definition at line 38 of file fftvanillaengine.hpp.
Constructor & Destructor Documentation
QuantLib::FFTVanillaEngine::FFTVanillaEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > & process, Real logStrikeSpacing = 0.001)
Definition at line 27 of file fftvanillaengine.cpp.
Referenced by clone().
        : FFTEngine(process, logStrikeSpacing)
    {
    }
Member Function Documentation
std::auto_ptr< FFTEngine > QuantLib::FFTVanillaEngine::clone () const [virtual]
Implements QuantLib::FFTEngine.
Definition at line 33 of file fftvanillaengine.cpp.
References FFTVanillaEngine(), QuantLib::FFTEngine::lambda_, and QuantLib::FFTEngine::process_.
    {
        boost::shared_ptr<GeneralizedBlackScholesProcess> process =
            boost::dynamic_pointer_cast<GeneralizedBlackScholesProcess>(process_);
        return std::auto_ptr<FFTEngine>(new FFTVanillaEngine(process, lambda_));
    }
std::complex< Real > QuantLib::FFTVanillaEngine::complexFourierTransform (std::complex< Real > u) const [protected, virtual]
Implements QuantLib::FFTEngine.
Definition at line 60 of file fftvanillaengine.cpp.
References dividendDiscount_, QuantLib::anonymous_namespace{bjerksundstenslandengine.cpp}::phi(), QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow(), QuantLib::FFTEngine::process_, riskFreeDiscount_, t_, and var_.
    {
        std::complex<Real> i1(0, 1);
        Real s = process_->x0();
        std::complex<Real> phi = std::exp(i1 * u * (log(s) - (var_ * t_) / 2.0)
            - (var_ * u * u * t_) / 2.0);
        phi = phi * std::pow(dividendDiscount_/ riskFreeDiscount_, i1 * u);
        return phi;
    }
Real QuantLib::FFTVanillaEngine::discountFactor (Date d) const [protected, virtual]
Implements QuantLib::FFTEngine.
Definition at line 72 of file fftvanillaengine.cpp.
References QuantLib::FFTEngine::process_, and QuantLib::GeneralizedBlackScholesProcess::riskFreeRate().
    {
        boost::shared_ptr<GeneralizedBlackScholesProcess> process =
            boost::dynamic_pointer_cast<GeneralizedBlackScholesProcess>(process_);
        return process->riskFreeRate()->discount(d);
    }
Real QuantLib::FFTVanillaEngine::dividendYield (Date d) const [protected, virtual]
Implements QuantLib::FFTEngine.
Definition at line 79 of file fftvanillaengine.cpp.
References QuantLib::GeneralizedBlackScholesProcess::dividendYield(), and QuantLib::FFTEngine::process_.
    {
        boost::shared_ptr<GeneralizedBlackScholesProcess> process =
            boost::dynamic_pointer_cast<GeneralizedBlackScholesProcess>(process_);
        return process->dividendYield()->discount(d);
    }
void QuantLib::FFTVanillaEngine::precalculateExpiry (Date d) [protected, virtual]
Implements QuantLib::FFTEngine.
Definition at line 40 of file fftvanillaengine.cpp.
References anonymous_namespace{marketmodel.cpp}::d, dividendDiscount_, QuantLib::FFTEngine::process_, QL_REQUIRE, riskFreeDiscount_, t_, var_, and QuantLib::DayCounter::yearFraction().
    {
        boost::shared_ptr<GeneralizedBlackScholesProcess> process =
            boost::dynamic_pointer_cast<GeneralizedBlackScholesProcess>(process_);
        dividendDiscount_ =
            process->dividendYield()->discount(d);
        riskFreeDiscount_ =
            process->riskFreeRate()->discount(d);
        DayCounter rfdc  = process->riskFreeRate()->dayCounter();
        t_ = rfdc.yearFraction(process->riskFreeRate()->referenceDate(), d);
        boost::shared_ptr<BlackConstantVol> constVol = boost::dynamic_pointer_cast<BlackConstantVol>
            (*(process->blackVolatility()));
        QL_REQUIRE(constVol, "Constant volatility required");
        Real vol = constVol->blackVol(0.0, 0.0);
        var_ = vol*vol;
    }
Member Data Documentation
DiscountFactor QuantLib::FFTVanillaEngine::dividendDiscount_ [private]
Definition at line 51 of file fftvanillaengine.hpp.
Referenced by complexFourierTransform(), and precalculateExpiry().
DiscountFactor QuantLib::FFTVanillaEngine::riskFreeDiscount_ [private]
Definition at line 52 of file fftvanillaengine.hpp.
Referenced by complexFourierTransform(), and precalculateExpiry().
Time QuantLib::FFTVanillaEngine::t_ [private]
Definition at line 53 of file fftvanillaengine.hpp.
Referenced by complexFourierTransform(), and precalculateExpiry().
Real QuantLib::FFTVanillaEngine::var_ [private]
Definition at line 54 of file fftvanillaengine.hpp.
Referenced by complexFourierTransform(), and precalculateExpiry().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/variancegamma/fftvanillaengine.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/variancegamma/fftvanillaengine.cpp