QuantLib: QuantLib::MonteCarloCDOEngine1 Class Reference
QuantLib::MonteCarloCDOEngine1 Class Reference
CDO engine, Monte Carlo for the exptected tranche loss distribution.
#include <syntheticcdoengines.hpp>
Public Member Functions
MonteCarloCDOEngine1 (boost::shared_ptr< RandomDefaultModel > rdm, Size samples)
Private Member Functions
void defaultScenarios () const
void initialize () const
Real expectedTrancheLoss (const Date &d) const
Private Attributes
boost::shared_ptr
< RandomDefaultModel > rdm_
Size samples_
Detailed Description
CDO engine, Monte Carlo for the exptected tranche loss distribution.
Definition at line 104 of file syntheticcdoengines.hpp.
Constructor & Destructor Documentation
QuantLib::MonteCarloCDOEngine1::MonteCarloCDOEngine1 (boost::shared_ptr< RandomDefaultModel > rdm, Size samples) [inline]
Definition at line 106 of file syntheticcdoengines.hpp.
            : rdm_(rdm), samples_(samples) {}
Member Function Documentation
void QuantLib::MonteCarloCDOEngine1::defaultScenarios () const [private]
Definition at line 164 of file syntheticcdoengines.cpp.
References anonymous_namespace{marketmodel.cpp}::dates, QL_REQUIRE, and QuantLib::DayCounter::yearFraction().
Referenced by initialize().
{
        results_.expectedTrancheLoss.clear();
        const vector<Date>& dates = arguments_.schedule.dates();
        Date today = Settings::instance().evaluationDate();
        Real tmax = ActualActual().yearFraction(today, dates.back());
        QL_REQUIRE(tmax >= 0, "tmax < 0");
        /*
          1) Generate a vector of random default times in the single-factor
             Gaussian Copula framework
          2) Work out cumulative portfolio and tranche loss for each scenario
          3) Map cumulative tranche losses to schedule dates
          4) Average over many scenarios
         */
        const boost::shared_ptr<Pool> pool = remainingBasket_->pool();
        vector<vector<Real> > cumulativeTrancheLoss(samples_, vector<Real>());
        results_.expectedTrancheLoss.resize(dates.size(), 0.0);
        for (Size i = 0; i < samples_; i++) {
            rdm_->nextSequence(tmax);
            cumulativeTrancheLoss[i].resize(dates.size(), 0.0);
            remainingBasket_->updateScenarioLoss();
            for (Size k = 0; k < dates.size(); k++) {
                cumulativeTrancheLoss[i][k]
                    = remainingBasket_->scenarioTrancheLoss(dates[k]);
                // aggregate
                results_.expectedTrancheLoss[k] += cumulativeTrancheLoss[i][k];
            }
        }
        // normalize
        for (Size i = 0; i < dates.size(); i++)
            results_.expectedTrancheLoss[i] /= samples_;
    }
Real QuantLib::MonteCarloCDOEngine1::expectedTrancheLoss (const Date & d) const [inline, private, virtual]
Implements QuantLib::MidPointCDOEngine.
Definition at line 139 of file syntheticcdoengines.hpp.
References QuantLib::GenericEngine< SyntheticCDO::arguments, SyntheticCDO::results >::arguments_, QuantLib::Schedule::dates(), anonymous_namespace{marketmodel.cpp}::dates, QuantLib::SyntheticCDO::results::expectedTrancheLoss, QuantLib::GenericEngine< SyntheticCDO::arguments, SyntheticCDO::results >::results_, and QuantLib::SyntheticCDO::arguments::schedule.
{
            const std::vector<Date>& dates = arguments_.schedule.dates();
            Real L = 0.0;
            for (Size i = 0; i < dates.size(); i++)
                if (d >= dates[i])
                    L = results_.expectedTrancheLoss[i];
                else
                    break;
            return L;
        }
void QuantLib::MonteCarloCDOEngine1::initialize () const [inline, private, virtual]
Reimplemented from QuantLib::SyntheticCDO::engine.
Definition at line 112 of file syntheticcdoengines.hpp.
References anonymous_namespace{marketmodel.cpp}::a, QuantLib::GenericEngine< SyntheticCDO::arguments, SyntheticCDO::results >::arguments_, QuantLib::SyntheticCDO::arguments::basket, anonymous_namespace{marketmodel.cpp}::d, defaultScenarios(), QuantLib::Settings::evaluationDate(), QuantLib::Singleton< Settings >::instance(), QuantLib::SyntheticCDO::engine::remainingBasket_, QuantLib::SyntheticCDO::results::remainingNotional, QuantLib::GenericEngine< SyntheticCDO::arguments, SyntheticCDO::results >::results_, QuantLib::SyntheticCDO::arguments::schedule, QuantLib::Schedule::startDate(), QuantLib::SyntheticCDO::results::xMax, and QuantLib::SyntheticCDO::results::xMin.
{
            Date today = Settings::instance().evaluationDate();
            Date start = this->arguments_.schedule.startDate();
            boost::shared_ptr<Basket>& basket = this->arguments_.basket;
            std::vector<std::string> names = basket->remainingNames(start, today);
            std::vector<Real> notionals
                = basket->remainingNotionals(start, today);
            Real a = basket->remainingAttachmentRatio(start, today);
            Real d = basket->remainingDetachmentRatio(start, today);
            const boost::shared_ptr<Pool> pool = basket->pool();
            remainingBasket_ =
                boost::shared_ptr<Basket>(new Basket(names, notionals,
                                                     pool,
                                                     basket->remainingDefaultKeys(start, today),
                                                     basket->remainingRecModels(start, today),
                                                     a, d));
            this->results_.xMin = remainingBasket_->attachmentAmount();
            this->results_.xMax = remainingBasket_->detachmentAmount();
            this->results_.remainingNotional = results_.xMax - results_.xMin;
            // This sets the vector results_.expectedTrancheLoss for each
            // schedule date by Monte Carlo simulation
            defaultScenarios();
        }
Member Data Documentation
boost::shared_ptr<RandomDefaultModel> QuantLib::MonteCarloCDOEngine1::rdm_ [private]
Definition at line 150 of file syntheticcdoengines.hpp.
Size QuantLib::MonteCarloCDOEngine1::samples_ [private]
Definition at line 151 of file syntheticcdoengines.hpp.
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/syntheticcdoengines.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/syntheticcdoengines.cpp