QuantLib: QuantLib::PaymentTerm Class Reference
QuantLib::PaymentTerm Class Reference
#include <paymentterm.hpp>
Classes
struct Data
Public Types
enum EventType { TradeDate, PricingDate }
Public Member Functions
PaymentTerm ()
PaymentTerm (const std::string &name, EventType eventType, Integer offsetDays, const Calendar &calendar)
Date getPaymentDate (const Date &date) const
Inspectors
const std::string & name () const
name, e.g, "Pricing end + 5 days"
EventType eventType () const
Integer offsetDays () const
const Calendar & calendar () const
bool empty () const
Protected Attributes
boost::shared_ptr< Data > data_
Static Protected Attributes
static std::map< std::string,
boost::shared_ptr< Data > > paymentTerms_
Related Functions
(Note that these are not member functions.)
bool operator== (const PaymentTerm &, const PaymentTerm &)
bool operator!= (const PaymentTerm &, const PaymentTerm &)
std::ostream & operator<< (std::ostream &, const PaymentTerm &)
Detailed Description
Definition at line 32 of file paymentterm.hpp.
Member Enumeration Documentation
enum QuantLib::PaymentTerm::EventType
Enumerator:
TradeDate
PricingDate
Definition at line 34 of file paymentterm.hpp.
{ TradeDate, PricingDate };
Constructor & Destructor Documentation
QuantLib::PaymentTerm::PaymentTerm () [inline]
Definition at line 89 of file paymentterm.hpp.
{}
QuantLib::PaymentTerm::PaymentTerm (const std::string & name, PaymentTerm::EventType eventType, Integer offsetDays, const Calendar & calendar)
Definition at line 27 of file paymentterm.cpp.
References data_, name(), and paymentTerms_.
{
        std::map<std::string, boost::shared_ptr<PaymentTerm::Data> >::const_iterator i = paymentTerms_.find(name);
        if (i != paymentTerms_.end())
            data_ = i->second;
        else {
            data_ = boost::shared_ptr<PaymentTerm::Data>(
                                 new PaymentTerm::Data(name, eventType,
                                                       offsetDays, calendar));
            paymentTerms_[name] = data_;
        }
    }
Member Function Documentation
const Calendar& QuantLib::PaymentTerm::calendar () const
bool QuantLib::PaymentTerm::empty () const [inline]
Definition at line 107 of file paymentterm.hpp.
References data_.
Referenced by QuantLib::operator<<().
{
        return !data_;
    }
PaymentTerm::EventType QuantLib::PaymentTerm::eventType () const [inline]
Definition at line 95 of file paymentterm.hpp.
References data_.
{
        return data_->eventType;
    }
Date QuantLib::PaymentTerm::getPaymentDate (const Date & date) const [inline]
Definition at line 103 of file paymentterm.hpp.
References data_.
Referenced by QuantLib::CommodityPricingHelper::createPricingPeriods().
{
        return data_->calendar.adjust(date + data_->offsetDays);
    }
const std::string & QuantLib::PaymentTerm::name () const [inline]
name, e.g, "Pricing end + 5 days"
Definition at line 91 of file paymentterm.hpp.
References data_.
Referenced by QuantLib::operator<<(), QuantLib::operator==(), and PaymentTerm().
{
        return data_->name;
    }
Integer QuantLib::PaymentTerm::offsetDays () const [inline]
Definition at line 99 of file paymentterm.hpp.
References data_.
{
        return data_->offsetDays;
    }
Friends And Related Function Documentation
bool operator!= (const PaymentTerm & , const PaymentTerm &) [related]
Definition at line 115 of file paymentterm.hpp.
{
        return !(c1 == c2);
    }
std::ostream & operator<< (std::ostream & , const PaymentTerm &) [related]
Definition at line 42 of file paymentterm.cpp.
{
        if (!c.empty())
            return out << c.name();
        else
            return out << "null payment term type";
    }
bool operator== (const PaymentTerm & , const PaymentTerm &) [related]
Definition at line 111 of file paymentterm.hpp.
{
        return c1.name() == c2.name();
    }
Member Data Documentation
boost::shared_ptr<Data> QuantLib::PaymentTerm::data_ [protected]
Definition at line 53 of file paymentterm.hpp.
Referenced by empty(), eventType(), getPaymentDate(), name(), offsetDays(), and PaymentTerm().
std::map< std::string, boost::shared_ptr< PaymentTerm::Data > > QuantLib::PaymentTerm::paymentTerms_ [static, protected]
Definition at line 66 of file paymentterm.hpp.
Referenced by PaymentTerm().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/commodities/paymentterm.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/commodities/paymentterm.cpp