QuantLib: QuantLib::CapPseudoDerivative Class Reference
QuantLib::CapPseudoDerivative Class Reference
#include <swaptionpseudojacobian.hpp>
Public Member Functions
CapPseudoDerivative (boost::shared_ptr< MarketModel > inputModel, Real strike, Size startIndex, Size endIndex, Real firstDF)
const Matrix & volatilityDerivative (Size i) const
const Matrix & priceDerivative (Size i) const
Real impliedVolatility () const
Private Attributes
boost::shared_ptr< MarketModel > inputModel_
std::vector< Matrix > volatilityDerivatives_
std::vector< Matrix > priceDerivatives_
Real impliedVolatility_
Real vega_
Real firstDF_
Detailed Description
In order to compute market vegas, we need a class that gives the derivative of a cap implied vol against changes in pseudo-root elements. This is that class.
The operation is non-trivial because the cap implied vol has a complicated relationship with the caplet implied vols.
This is tested in the pathwise vegas routine in MarketModels.cpp
Definition at line 78 of file swaptionpseudojacobian.hpp.
Constructor & Destructor Documentation
QuantLib::CapPseudoDerivative::CapPseudoDerivative (boost::shared_ptr< MarketModel > inputModel, Real strike, Size startIndex, Size endIndex, Real firstDF)
Definition at line 234 of file swaptionpseudojacobian.cpp.
References QuantLib::blackFormula(), QuantLib::blackFormulaVolDerivative(), QuantLib::Option::Call, anonymous_namespace{marketmodel.cpp}::displacement, anonymous_namespace{interpolations.cpp}::f(), firstDF_, impliedVolatility_, priceDerivatives_, QL_REQUIRE, QuantLib::io::rate(), QuantLib::Solver1D< Impl >::setMaxEvaluations(), QuantLib::LMMCurveState::setOnForwardRates(), QuantLib::Solver1D< Impl >::solve(), vega_, and volatilityDerivatives_.
                                     : firstDF_(firstDF)
    {
        QL_REQUIRE(startIndex < endIndex, "for a cap pseudo derivative the start of the cap must be before the end");
        QL_REQUIRE( endIndex <= inputModel->numberOfRates(), "for a cap pseudo derivative the end of the cap must before the end of the rates");
        Size numberCaplets = endIndex-startIndex;
        Size numberRates = inputModel->numberOfRates();
        Size factors = inputModel->numberOfFactors();
        LMMCurveState curve(inputModel->evolution().rateTimes());
        curve.setOnForwardRates(inputModel->initialRates());
        const Matrix& totalCovariance(inputModel->totalCovariance(inputModel->numberOfSteps()-1));
        std::vector<Real> displacedImpliedVols(numberCaplets);
        std::vector<Real> annuities(numberCaplets);
        std::vector<Real> capletPrices(numberCaplets);
        std::vector<Real> initialRates(numberCaplets);
        std::vector<Real> expiries(numberCaplets);
        Real capPrice =0.0;
        Real guess=0.0;
        Real minVol = 1e10;
        Real maxVol =0.0;
        for (Size j = startIndex; j < endIndex; ++j)
        {
            Size capletIndex = j - startIndex;
            Time resetTime = inputModel->evolution().rateTimes()[j];
            expiries[capletIndex] =  resetTime;
            Real sd = std::sqrt(totalCovariance[j][j]);
            displacedImpliedVols[capletIndex] = std::sqrt(totalCovariance[j][j]/resetTime);
            Real forward = inputModel->initialRates()[j];
            initialRates[capletIndex] = forward;
            Real annuity = curve.discountRatio(j+1,0)* inputModel->evolution().rateTaus()[j]*firstDF_;
            annuities[capletIndex] = annuity;
            Real displacement =  inputModel->displacements()[j];
            guess+=  displacedImpliedVols[capletIndex]*(forward+displacement)/forward;
            minVol =std::min(minVol, displacedImpliedVols[capletIndex]);
            maxVol =std::max(maxVol, displacedImpliedVols[capletIndex]*(forward+displacement)/forward);
            Real capletPrice = blackFormula(Option::Call,
                strike,
                forward,
                sd,
                annuity,
                displacement
                );
            capletPrices[capletIndex] = capletPrice;
            capPrice += capletPrice;
        }
        guess/=numberCaplets;
        for (Size step =0; step < inputModel->evolution().numberOfSteps(); ++step)
        {
            Matrix thisDerivative(numberRates,factors,0.0);
            for (Size rate =std::max(inputModel->evolution().firstAliveRate()[step],startIndex);
                rate < endIndex; ++rate)
            {
                for (Size f=0; f < factors; ++f)
                {
                    Real expiry = inputModel->evolution().rateTimes()[rate];
                    Real volDerivative = inputModel->pseudoRoot(step)[rate][f]
                    /(displacedImpliedVols[rate-startIndex]*expiry);
                    Real capletVega = blackFormulaVolDerivative(strike,inputModel->initialRates()[rate],
                        displacedImpliedVols[rate-startIndex]*std::sqrt(expiry),
                        expiry,
                        annuities[rate-startIndex],
                        inputModel->displacements()[rate]);
                    // note that the cap derivative  is equal to one of the caplet ones so we lose a loop
                    thisDerivative[rate][f] = volDerivative*capletVega;
                }
            }
            priceDerivatives_.push_back(thisDerivative);
        }
        QuickCap capPricer(strike, annuities, initialRates, expiries,capPrice);
        Size maxEvaluations = 1000;
        Real accuracy = 1E-6;
        Brent solver;
        solver.setMaxEvaluations(maxEvaluations);
        impliedVolatility_ =   solver.solve(capPricer,accuracy,guess,minVol*0.99,maxVol*1.01);
        vega_ = capPricer.vega(impliedVolatility_);
        for (Size step =0; step < inputModel->evolution().numberOfSteps(); ++step)
        {
            Matrix thisDerivative(numberRates,factors,0.0);
            for (Size rate =std::max(inputModel->evolution().firstAliveRate()[step],startIndex);
                rate < endIndex; ++rate)
            {
                for (Size f=0; f < factors; ++f)
                {
                    thisDerivative[rate][f] = priceDerivatives_[step][rate][f]/vega_;
                }
            }
            volatilityDerivatives_.push_back(thisDerivative);
        }
    }
Member Function Documentation
Real QuantLib::CapPseudoDerivative::impliedVolatility () const
Definition at line 378 of file swaptionpseudojacobian.cpp.
References impliedVolatility_.
Referenced by MarketModelTest::testPathwiseMarketVegas(), and MarketModelTest::testPathwiseVegas().
    {
        return impliedVolatility_;
    }
const Matrix & QuantLib::CapPseudoDerivative::priceDerivative (Size i) const
Definition at line 366 of file swaptionpseudojacobian.cpp.
References priceDerivatives_.
Referenced by MarketModelTest::testPathwiseVegas().
    {
        return priceDerivatives_[i];
    }
const Matrix & QuantLib::CapPseudoDerivative::volatilityDerivative (Size i) const
Definition at line 371 of file swaptionpseudojacobian.cpp.
References volatilityDerivatives_.
Referenced by QuantLib::VolatilityBumpInstrumentJacobian::derivativesVolatility(), MarketModelTest::testPathwiseMarketVegas(), and MarketModelTest::testPathwiseVegas().
    {
        return volatilityDerivatives_[i];
    }
Member Data Documentation
Real QuantLib::CapPseudoDerivative::firstDF_ [private]
Definition at line 104 of file swaptionpseudojacobian.hpp.
Referenced by CapPseudoDerivative().
Real QuantLib::CapPseudoDerivative::impliedVolatility_ [private]
Definition at line 102 of file swaptionpseudojacobian.hpp.
Referenced by CapPseudoDerivative(), and impliedVolatility().
boost::shared_ptr<MarketModel> QuantLib::CapPseudoDerivative::inputModel_ [private]
Definition at line 96 of file swaptionpseudojacobian.hpp.
std::vector<Matrix> QuantLib::CapPseudoDerivative::priceDerivatives_ [private]
Definition at line 100 of file swaptionpseudojacobian.hpp.
Referenced by CapPseudoDerivative(), and priceDerivative().
Real QuantLib::CapPseudoDerivative::vega_ [private]
Definition at line 103 of file swaptionpseudojacobian.hpp.
Referenced by CapPseudoDerivative().
std::vector<Matrix> QuantLib::CapPseudoDerivative::volatilityDerivatives_ [private]
Definition at line 98 of file swaptionpseudojacobian.hpp.
Referenced by CapPseudoDerivative(), and volatilityDerivative().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/pathwisegreeks/swaptionpseudojacobian.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/pathwisegreeks/swaptionpseudojacobian.cpp