QuantLib: QuantLib::CmsMarket Class Reference
QuantLib::CmsMarket Class Reference
set of CMS quotes
#include <cmsmarket.hpp>
Public Member Functions
CmsMarket (const std::vector< Period > &swapLengths, const std::vector< boost::shared_ptr< SwapIndex > > &swapIndexes, const boost::shared_ptr< IborIndex > &iborIndex, const std::vector< std::vector< Handle< Quote > > > &bidAskSpreads, const std::vector< boost::shared_ptr< HaganPricer > > &pricers, const Handle< YieldTermStructure > &discountingTS)
void reprice (const Handle< SwaptionVolatilityStructure > &volStructure, Real meanReversion)
const std::vector< Period > & swapTenors () const
const Matrix & impliedCmsSpreads ()
const Matrix & spreadErrors ()
Matrix browse () const
Real weightedSpreadError (const Matrix &weights)
Real weightedSpotNpvError (const Matrix &weights)
Real weightedFwdNpvError (const Matrix &weights)
Disposable< Array > weightedSpreadErrors (const Matrix &weights)
Disposable< Array > weightedSpotNpvErrors (const Matrix &weights)
Disposable< Array > weightedFwdNpvErrors (const Matrix &weights)
LazyObject interface
void update ()
Private Member Functions
void performCalculations () const
Real weightedMean (const Matrix &var, const Matrix &weights)
Disposable< Array > weightedMeans (const Matrix &var, const Matrix &weights)
Private Attributes
std::vector< Period > swapLengths_
std::vector< boost::shared_ptr
< SwapIndex > > swapIndexes_
boost::shared_ptr< IborIndex > iborIndex_
std::vector< std::vector
< Handle< Quote > > > bidAskSpreads_
std::vector< boost::shared_ptr
< HaganPricer > > pricers_
Handle< YieldTermStructure > discTS_
Size nExercise_
Size nSwapIndexes_
std::vector< Period > swapTenors_
Matrix spotFloatLegNPV_
Matrix spotFloatLegBPS_
Matrix mktBidSpreads_
Matrix mktAskSpreads_
Matrix mktSpreads_
Matrix mdlSpreads_
Matrix errSpreads_
Matrix mktSpotCmsLegNPV_
Matrix mdlSpotCmsLegNPV_
Matrix errSpotCmsLegNPV_
Matrix mktFwdCmsLegNPV_
Matrix mdlFwdCmsLegNPV_
Matrix errFwdCmsLegNPV_
std::vector< std::vector
< boost::shared_ptr< Swap > > > spotSwaps_
std::vector< std::vector
< boost::shared_ptr< Swap > > > fwdSwaps_
Detailed Description
set of CMS quotes
Definition at line 42 of file cmsmarket.hpp.
Constructor & Destructor Documentation
QuantLib::CmsMarket::CmsMarket (const std::vector< Period > & swapLengths, const std::vector< boost::shared_ptr< SwapIndex > > & swapIndexes, const boost::shared_ptr< IborIndex > & iborIndex, const std::vector< std::vector< Handle< Quote > > > & bidAskSpreads, const std::vector< boost::shared_ptr< HaganPricer > > & pricers, const Handle< YieldTermStructure > & discountingTS)
Definition at line 35 of file cmsmarket.cpp.
References bidAskSpreads_, discTS_, fwdSwaps_, iborIndex_, nExercise_, nSwapIndexes_, performCalculations(), pricers_, QL_REQUIRE, QuantLib::Observer::registerWith(), spotSwaps_, swapIndexes_, swapLengths_, swapTenors_, QuantLib::MakeCms::withCmsCouponPricer(), QuantLib::MakeCms::withDiscountingTermStructure(), and QuantLib::Years.
    : swapLengths_(swapLengths),
      swapIndexes_(swapIndexes),
      iborIndex_(iborIndex),
      bidAskSpreads_(bidAskSpreads),
      pricers_(pricers),
      discTS_(discountingTS),
      nExercise_(swapLengths_.size()),
      nSwapIndexes_(swapIndexes_.size()),
      swapTenors_(nSwapIndexes_),
      spotFloatLegNPV_(nExercise_, nSwapIndexes_),
      spotFloatLegBPS_(nExercise_, nSwapIndexes_),
      mktBidSpreads_(nExercise_, nSwapIndexes_),
      mktAskSpreads_(nExercise_, nSwapIndexes_),
      mktSpreads_(nExercise_, nSwapIndexes_),
      mdlSpreads_(nExercise_, nSwapIndexes_),
      errSpreads_(nExercise_, nSwapIndexes_),
      mktSpotCmsLegNPV_(nExercise_, nSwapIndexes_),
      mdlSpotCmsLegNPV_(nExercise_, nSwapIndexes_),
      errSpotCmsLegNPV_(nExercise_, nSwapIndexes_),
      mktFwdCmsLegNPV_(nExercise_, nSwapIndexes_),
      mdlFwdCmsLegNPV_(nExercise_, nSwapIndexes_),
      errFwdCmsLegNPV_(nExercise_, nSwapIndexes_),
      spotSwaps_(nExercise_, vector<shared_ptr<Swap> >(nSwapIndexes_)),
      fwdSwaps_(nExercise_, vector<shared_ptr<Swap> >(nSwapIndexes_))
    {
        QL_REQUIRE(2*nSwapIndexes_==bidAskSpreads[0].size(),
                   "2*nSwapIndexes_!=bidAskSpreads columns()");
        QL_REQUIRE(nExercise_==bidAskSpreads.size(),
                   "nExercise_==bidAskSpreads rows()");
        for (Size j=0; j<nSwapIndexes_; ++j) {
            swapTenors_[j] = swapIndexes_[j]->tenor();
            // pricers
            registerWith(pricers_[j]);
            for (Size i=0; i<nExercise_; ++i) {
                // market Spread
                registerWith(bidAskSpreads_[i][j*2]);
                registerWith(bidAskSpreads_[i][j*2+1]);
            }
        }
        Period start(0, Years);
        for (Size i=0; i<nExercise_; ++i) {
            if (i>0) start = swapLengths_[i-1];
            for (Size j=0; j<nSwapIndexes_; ++j) {
                // never evaluate the spot swap, only its ibor floating leg
                spotSwaps_[i][j] = MakeCms(swapLengths_[i],
                                           swapIndexes_[j],
                                           iborIndex_, 0.0,
                                           Period())
                                   .operator shared_ptr<Swap>();
                fwdSwaps_[i][j]  = MakeCms(swapLengths_[i]-start,
                                           swapIndexes_[j],
                                           iborIndex_, 0.0,
                                           start)
                                   .withCmsCouponPricer(pricers_[j])
                                   .withDiscountingTermStructure(discTS_)
                                   .operator shared_ptr<Swap>();
            }
        }
        // probably useless
        performCalculations();
     }
Member Function Documentation
Matrix QuantLib::CmsMarket::browse () const
Definition at line 228 of file cmsmarket.cpp.
References QuantLib::LazyObject::calculate(), errFwdCmsLegNPV_, errSpotCmsLegNPV_, errSpreads_, mdlFwdCmsLegNPV_, mdlSpotCmsLegNPV_, mdlSpreads_, mktAskSpreads_, mktBidSpreads_, mktFwdCmsLegNPV_, mktSpotCmsLegNPV_, mktSpreads_, nExercise_, nSwapIndexes_, swapLengths_, and swapTenors_.
{
        calculate();
        //Matrix result(nExercise_*nSwapIndexes_, 15);
        Matrix result(nExercise_*nSwapIndexes_, 14);
            for (Size j=0; j<nSwapIndexes_; ++j) {
                for (Size i=0; i<nExercise_; ++i) {
                result[j*nSwapIndexes_+i][0] = swapTenors_[j].length();
                result[j*nSwapIndexes_+i][1] = swapLengths_[i].length();
                // Spreads
                result[j*nSwapIndexes_+i][2] = mktBidSpreads_[i][j]*10000;
                result[j*nSwapIndexes_+i][3] = mktAskSpreads_[i][j]*10000;
                result[j*nSwapIndexes_+i][4] = mktSpreads_[i][j]*10000;
                result[j*nSwapIndexes_+i][5] = mdlSpreads_[i][j]*10000;
                result[j*nSwapIndexes_+i][6] = errSpreads_[i][j]*10000;
                if (mdlSpreads_[i][j]>mktAskSpreads_[i][j])
                    result[j*nSwapIndexes_+i][7] = (mdlSpreads_[i][j] -
                                                mktAskSpreads_[i][j])*10000;
                else if (mdlSpreads_[i][j]<mktBidSpreads_[i][j])
                    result[j*nSwapIndexes_+i][7] = (mktBidSpreads_[i][j] -
                                                mdlSpreads_[i][j])*10000;
                else
                    result[j*nSwapIndexes_+i][7] = 0.0;
                // spot CMS Leg NPVs
                result[j*nSwapIndexes_+i][ 8] = mktSpotCmsLegNPV_[i][j];
                result[j*nSwapIndexes_+i][ 9] = mdlSpotCmsLegNPV_[i][j];
                result[j*nSwapIndexes_+i][10] = errSpotCmsLegNPV_[i][j];
                // forward CMS Leg NPVs
                result[j*nSwapIndexes_+i][11] = mktFwdCmsLegNPV_[i][j];
                result[j*nSwapIndexes_+i][12] = mdlFwdCmsLegNPV_[i][j];
                result[j*nSwapIndexes_+i][13] = errFwdCmsLegNPV_[i][j];
            }
        }
        return result;
    }
const Matrix& QuantLib::CmsMarket::impliedCmsSpreads () [inline]
Definition at line 60 of file cmsmarket.hpp.
References mdlSpreads_.
{ return mdlSpreads_; }
void QuantLib::CmsMarket::performCalculations () const [private, virtual]
This method must implement any calculations which must be (re)done in order to calculate the desired results.
Implements QuantLib::LazyObject.
Definition at line 113 of file cmsmarket.cpp.
References bidAskSpreads_, QuantLib::CashFlows::bps(), discTS_, errFwdCmsLegNPV_, errSpotCmsLegNPV_, errSpreads_, fwdSwaps_, mdlFwdCmsLegNPV_, mdlSpotCmsLegNPV_, mdlSpreads_, mktAskSpreads_, mktBidSpreads_, mktFwdCmsLegNPV_, mktSpotCmsLegNPV_, mktSpreads_, nExercise_, QuantLib::CashFlows::npv(), nSwapIndexes_, spotFloatLegBPS_, spotFloatLegNPV_, and spotSwaps_.
Referenced by CmsMarket(), reprice(), weightedFwdNpvError(), weightedFwdNpvErrors(), weightedSpotNpvError(), weightedSpotNpvErrors(), weightedSpreadError(), and weightedSpreadErrors().
{
        for (Size j=0; j<nSwapIndexes_; ++j) {
          Real mktPrevPart = 0.0, mdlPrevPart = 0.0;
          for (Size i=0; i<nExercise_; ++i) {
            // **** market
            mktBidSpreads_[i][j] = bidAskSpreads_[i][j*2]->value();
            mktAskSpreads_[i][j] = bidAskSpreads_[i][j*2+1]->value();
            mktSpreads_[i][j] = (mktBidSpreads_[i][j]+mktAskSpreads_[i][j])/2;
            const Leg& spotFloatLeg = spotSwaps_[i][j]->leg(1);
            spotFloatLegNPV_[i][j] = CashFlows::npv(spotFloatLeg,
                                                    **discTS_,
                                                    false, discTS_->referenceDate());
            spotFloatLegBPS_[i][j] = CashFlows::bps(spotFloatLeg,
                                                    **discTS_,
                                                    false, discTS_->referenceDate());
            // imply the spot CMS leg NPV from the spot ibor floating leg NPV
            mktSpotCmsLegNPV_[i][j] = -(spotFloatLegNPV_[i][j] +
                                spotFloatLegBPS_[i][j]*mktSpreads_[i][j]/1e-4);
            // fwd CMS legs can be computed as differences between spot legs
            mktFwdCmsLegNPV_[i][j] = mktSpotCmsLegNPV_[i][j] - mktPrevPart;
            mktPrevPart = mktSpotCmsLegNPV_[i][j];
            // **** model
            // calculate the forward swap (the time consuming part)
            mdlFwdCmsLegNPV_[i][j] = fwdSwaps_[i][j]->legNPV(0);
            errFwdCmsLegNPV_[i][j] = mdlFwdCmsLegNPV_[i][j] -
                                                mktFwdCmsLegNPV_[i][j];
            // spot CMS legs can be computed as incremental sum of forward legs
            mdlSpotCmsLegNPV_[i][j] = mdlPrevPart + mdlFwdCmsLegNPV_[i][j];
            mdlPrevPart = mdlSpotCmsLegNPV_[i][j];
            errSpotCmsLegNPV_[i][j] = mdlSpotCmsLegNPV_[i][j] -
                                                mktSpotCmsLegNPV_[i][j];
            // equilibriums spread over ibor leg
            Real npv = spotFloatLegNPV_[i][j] + mdlSpotCmsLegNPV_[i][j];
            mdlSpreads_[i][j] = - npv/spotFloatLegBPS_[i][j]*1e-4;
            errSpreads_[i][j] = mdlSpreads_[i][j] - mktSpreads_[i][j];
          }
        }
    }
void QuantLib::CmsMarket::reprice (const Handle< SwaptionVolatilityStructure > & volStructure, Real meanReversion)
Definition at line 160 of file cmsmarket.cpp.
References nSwapIndexes_, performCalculations(), and pricers_.
{
        Handle<Quote> meanReversionQuote(shared_ptr<Quote>(new
                                                SimpleQuote(meanReversion)));
        for (Size j=0; j<nSwapIndexes_; ++j) {
            // ??
            // set new volatility structure and new mean reversion
            pricers_[j]->setSwaptionVolatility(v);
            pricers_[j]->setMeanReversion(meanReversionQuote);
        }
        performCalculations();
    }
const Matrix& QuantLib::CmsMarket::spreadErrors () [inline]
Definition at line 61 of file cmsmarket.hpp.
References errSpreads_.
{ return errSpreads_; }
const std::vector<Period>& QuantLib::CmsMarket::swapTenors () const [inline]
Definition at line 59 of file cmsmarket.hpp.
References swapTenors_.
{ return swapTenors_;}
void QuantLib::CmsMarket::update () [inline, virtual]
This method must be implemented in derived classes. An instance of Observer does not call this method directly: instead, it will be called by the observables the instance registered with when they need to notify any changes.
Reimplemented from QuantLib::LazyObject.
Definition at line 53 of file cmsmarket.hpp.
{ LazyObject::update();}
Real QuantLib::CmsMarket::weightedFwdNpvError (const Matrix & weights)
Definition at line 173 of file cmsmarket.cpp.
References errFwdCmsLegNPV_, performCalculations(), and weightedMean().
{
        performCalculations();
        return weightedMean(errFwdCmsLegNPV_, w);
    }
Disposable< Array > QuantLib::CmsMarket::weightedFwdNpvErrors (const Matrix & weights)
Definition at line 190 of file cmsmarket.cpp.
References errFwdCmsLegNPV_, performCalculations(), and weightedMeans().
{
        performCalculations();
        return weightedMeans(errFwdCmsLegNPV_, w);
    }
Real QuantLib::CmsMarket::weightedMean (const Matrix & var, const Matrix & weights) [private]
Definition at line 205 of file cmsmarket.cpp.
References nExercise_, and nSwapIndexes_.
Referenced by weightedFwdNpvError(), weightedSpotNpvError(), and weightedSpreadError().
{
        Real mean = 0.0;
        for (Size i=0; i<nExercise_; ++i) {
            for (Size j=0; j<nSwapIndexes_; ++j) {
                mean += w[i][j]*var[i][j]*var[i][j];
            }
        }
        mean = std::sqrt(mean/(nExercise_*nSwapIndexes_));
        return mean;
    }
Disposable< Array > QuantLib::CmsMarket::weightedMeans (const Matrix & var, const Matrix & weights) [private]
Definition at line 217 of file cmsmarket.cpp.
References nExercise_, and nSwapIndexes_.
Referenced by weightedFwdNpvErrors(), weightedSpotNpvErrors(), and weightedSpreadErrors().
{
        Array weightedVars(nExercise_*nSwapIndexes_);
        for (Size i=0; i<nExercise_; ++i) {
            for (Size j=0; j<nSwapIndexes_; ++j) {
                weightedVars[i*nSwapIndexes_+j] = std::sqrt(w[i][j])*var[i][j];
            }
        }
        return weightedVars;
    }
Real QuantLib::CmsMarket::weightedSpotNpvError (const Matrix & weights)
Definition at line 178 of file cmsmarket.cpp.
References errSpotCmsLegNPV_, performCalculations(), and weightedMean().
{
        performCalculations();
        return weightedMean(errSpotCmsLegNPV_, w);
    }
Disposable< Array > QuantLib::CmsMarket::weightedSpotNpvErrors (const Matrix & weights)
Definition at line 195 of file cmsmarket.cpp.
References errSpotCmsLegNPV_, performCalculations(), and weightedMeans().
{
        performCalculations();
        return weightedMeans(errSpotCmsLegNPV_, w);
    }
Real QuantLib::CmsMarket::weightedSpreadError (const Matrix & weights)
Definition at line 183 of file cmsmarket.cpp.
References errSpreads_, performCalculations(), and weightedMean().
{
        performCalculations();
        return weightedMean(errSpreads_, w);
    }
Disposable< Array > QuantLib::CmsMarket::weightedSpreadErrors (const Matrix & weights)
Definition at line 200 of file cmsmarket.cpp.
References errSpreads_, performCalculations(), and weightedMeans().
{
        performCalculations();
        return weightedMeans(errSpreads_, w);
    }
Member Data Documentation
std::vector<std::vector<Handle<Quote> > > QuantLib::CmsMarket::bidAskSpreads_ [private]
Definition at line 82 of file cmsmarket.hpp.
Referenced by CmsMarket(), and performCalculations().
Handle<YieldTermStructure> QuantLib::CmsMarket::discTS_ [private]
Definition at line 84 of file cmsmarket.hpp.
Referenced by CmsMarket(), and performCalculations().
Matrix QuantLib::CmsMarket::errFwdCmsLegNPV_ [mutable, private]
Definition at line 110 of file cmsmarket.hpp.
Referenced by browse(), performCalculations(), weightedFwdNpvError(), and weightedFwdNpvErrors().
Matrix QuantLib::CmsMarket::errSpotCmsLegNPV_ [mutable, private]
Definition at line 103 of file cmsmarket.hpp.
Referenced by browse(), performCalculations(), weightedSpotNpvError(), and weightedSpotNpvErrors().
Matrix QuantLib::CmsMarket::errSpreads_ [mutable, private]
Definition at line 96 of file cmsmarket.hpp.
Referenced by browse(), performCalculations(), spreadErrors(), weightedSpreadError(), and weightedSpreadErrors().
std::vector<std::vector<boost::shared_ptr<Swap> > > QuantLib::CmsMarket::fwdSwaps_ [private]
Definition at line 113 of file cmsmarket.hpp.
Referenced by CmsMarket(), and performCalculations().
boost::shared_ptr<IborIndex> QuantLib::CmsMarket::iborIndex_ [private]
Definition at line 81 of file cmsmarket.hpp.
Referenced by CmsMarket().
Matrix QuantLib::CmsMarket::mdlFwdCmsLegNPV_ [mutable, private]
Definition at line 108 of file cmsmarket.hpp.
Referenced by browse(), and performCalculations().
Matrix QuantLib::CmsMarket::mdlSpotCmsLegNPV_ [mutable, private]
Definition at line 101 of file cmsmarket.hpp.
Referenced by browse(), and performCalculations().
Matrix QuantLib::CmsMarket::mdlSpreads_ [mutable, private]
Definition at line 94 of file cmsmarket.hpp.
Referenced by browse(), impliedCmsSpreads(), and performCalculations().
Matrix QuantLib::CmsMarket::mktAskSpreads_ [mutable, private]
Definition at line 92 of file cmsmarket.hpp.
Referenced by browse(), and performCalculations().
Matrix QuantLib::CmsMarket::mktBidSpreads_ [mutable, private]
Definition at line 92 of file cmsmarket.hpp.
Referenced by browse(), and performCalculations().
Matrix QuantLib::CmsMarket::mktFwdCmsLegNPV_ [mutable, private]
Definition at line 106 of file cmsmarket.hpp.
Referenced by browse(), and performCalculations().
Matrix QuantLib::CmsMarket::mktSpotCmsLegNPV_ [mutable, private]
Definition at line 99 of file cmsmarket.hpp.
Referenced by browse(), and performCalculations().
Matrix QuantLib::CmsMarket::mktSpreads_ [mutable, private]
Definition at line 92 of file cmsmarket.hpp.
Referenced by browse(), and performCalculations().
Size QuantLib::CmsMarket::nExercise_ [private]
Definition at line 86 of file cmsmarket.hpp.
Referenced by browse(), CmsMarket(), performCalculations(), weightedMean(), and weightedMeans().
Size QuantLib::CmsMarket::nSwapIndexes_ [private]
Definition at line 87 of file cmsmarket.hpp.
Referenced by browse(), CmsMarket(), performCalculations(), reprice(), weightedMean(), and weightedMeans().
std::vector<boost::shared_ptr<HaganPricer> > QuantLib::CmsMarket::pricers_ [private]
Definition at line 83 of file cmsmarket.hpp.
Referenced by CmsMarket(), and reprice().
Matrix QuantLib::CmsMarket::spotFloatLegBPS_ [mutable, private]
Definition at line 89 of file cmsmarket.hpp.
Referenced by performCalculations().
Matrix QuantLib::CmsMarket::spotFloatLegNPV_ [mutable, private]
Definition at line 89 of file cmsmarket.hpp.
Referenced by performCalculations().
std::vector<std::vector<boost::shared_ptr<Swap> > > QuantLib::CmsMarket::spotSwaps_ [private]
Definition at line 112 of file cmsmarket.hpp.
Referenced by CmsMarket(), and performCalculations().
std::vector<boost::shared_ptr<SwapIndex> > QuantLib::CmsMarket::swapIndexes_ [private]
Definition at line 80 of file cmsmarket.hpp.
Referenced by CmsMarket().
std::vector<Period> QuantLib::CmsMarket::swapLengths_ [private]
Definition at line 79 of file cmsmarket.hpp.
Referenced by browse(), and CmsMarket().
std::vector<Period> QuantLib::CmsMarket::swapTenors_ [private]
Definition at line 88 of file cmsmarket.hpp.
Referenced by browse(), CmsMarket(), and swapTenors().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/swaption/cmsmarket.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/swaption/cmsmarket.cpp