QuantLib: CdoTest Class Reference
CdoTest Class Reference
#include <cdo.hpp>
Static Public Member Functions
static void testHW ()
static
boost::unit_test_framework::test_suite * suite ()
Detailed Description
Definition at line 28 of file cdo.hpp.
Member Function Documentation
test_suite * CdoTest::suite () [static]
Definition at line 260 of file cdo.cpp.
References QUANTLIB_TEST_CASE, and testHW().
Referenced by init_unit_test_suite().
{
    test_suite* suite = BOOST_TEST_SUITE("CDO tests");
    suite->add(QUANTLIB_TEST_CASE(&CdoTest::testHW));
    return suite;
}
void CdoTest::testHW () [static]
Definition at line 73 of file cdo.cpp.
References QuantLib::August, anonymous_namespace{cdo.cpp}::check(), QuantLib::Continuous, QuantLib::Settings::evaluationDate(), QuantLib::SyntheticCDO::fairPremium(), QuantLib::CDO::fairPremium(), QuantLib::Following, QuantLib::MakeSchedule::from(), anonymous_namespace{cdo.cpp}::hwAttachment, anonymous_namespace{cdo.cpp}::hwData7, anonymous_namespace{cdo.cpp}::hwDetachment, QuantLib::Singleton< Settings >::instance(), LENGTH, QuantLib::RelinkableHandle< T >::linkTo(), QuantLib::Months, QL_REQUIRE, QuantLib::io::rate(), QuantLib::Protection::Seller, QuantLib::SeniorSec, QuantLib::September, QuantLib::Instrument::setPricingEngine(), QuantLib::MakeSchedule::to(), anonymous_namespace{cdo.cpp}::hwDatum::trancheSpread, QuantLib::Weeks, QuantLib::MakeSchedule::withCalendar(), QuantLib::MakeSchedule::withTenor(), and QuantLib::Years.
Referenced by suite().
                     {
    BOOST_MESSAGE ("Testing CDO premiums against Hull-White values...");
    SavedSettings backup;
    Size poolSize = 100;
    Real lambda = 0.01;
    // nBuckets and period determine the computation time
    Size nBuckets = 200;
    Period period = 1*Months;
    Real rate = 0.05;
    DayCounter daycount = Actual360();
    Compounding cmp = Continuous; // Simple;
    Real recovery = 0.4;
    vector<Real> nominals(poolSize, 100.0);
    Real premium = 0.02;
    Period maxTerm (5, Years);
    Schedule schedule = MakeSchedule().from(Date (1, September, 2006))
                                      .to(Date (1, September, 2011))
                                      .withTenor(Period (3, Months))
                                      .withCalendar(TARGET());
    Date asofDate = Date(31, August, 2006);
    Settings::instance().evaluationDate() = asofDate;
    boost::shared_ptr<YieldTermStructure> yieldPtr(
                                              new FlatForward (asofDate, rate,
                                                               daycount, cmp));
    Handle<YieldTermStructure> yieldHandle (yieldPtr);
    Handle<Quote> hazardRate(boost::shared_ptr<Quote>(new SimpleQuote(lambda)));
    vector<Handle<DefaultProbabilityTermStructure> > basket;
    boost::shared_ptr<DefaultProbabilityTermStructure> ptr (
               new FlatHazardRate (asofDate,
                                   hazardRate,
                                   ActualActual()));
    boost::shared_ptr<Pool> pool (new Pool());
    vector<string> names;
    // probability key items
    vector<Issuer> issuers;
    vector<pair<DefaultProbKey,
           Handle<DefaultProbabilityTermStructure> > > probabilities;
    probabilities.push_back(std::make_pair(
        NorthAmericaCorpDefaultKey(EURCurrency(),
                                   SeniorSec,
                                   Period(0,Weeks),
                                   10.),
       ptr));
    for (Size i=0; i<poolSize; ++i) {
        ostringstream o;
        o << "issuer-" << i;
        names.push_back(o.str());
        basket.push_back(Handle<DefaultProbabilityTermStructure>(ptr));
        issuers.push_back(Issuer(probabilities));
        pool->add(names.back(), issuers.back());
    }
    boost::shared_ptr<SimpleQuote> correlation (new SimpleQuote(0.0));
    Handle<Quote> hCorrelation (correlation);
    boost::shared_ptr<OneFactorCopula> pGaussianCopula (
                            new OneFactorGaussianCopula (hCorrelation));
    RelinkableHandle<OneFactorCopula> hCopula (pGaussianCopula);
    boost::shared_ptr<RandomDefaultModel> rdm(new
        GaussianRandomDefaultModel(pool,
                                   std::vector<DefaultProbKey>(poolSize,
                                    NorthAmericaCorpDefaultKey(EURCurrency(),
                                                               SeniorSec)),
                                   hCopula,
                                   1.e-6,
                                   42));
    boost::shared_ptr<PricingEngine> engine1(
                          new IHPIntegralCDOEngine(hCopula, nBuckets));
    boost::shared_ptr<PricingEngine> engine2(
                          new IHPMidPointCDOEngine(hCopula, nBuckets));
    boost::shared_ptr<PricingEngine> engine3(
                          new HPIntegralCDOEngine(hCopula, nBuckets));
    boost::shared_ptr<PricingEngine> engine4(
                          new HPMidPointCDOEngine(hCopula, nBuckets));
    boost::shared_ptr<PricingEngine> engine5(
                          new MonteCarloCDOEngine1(rdm, 10000));
    boost::shared_ptr<PricingEngine> engine6(
                          new MonteCarloCDOEngine2(rdm, 10000));
    boost::shared_ptr<PricingEngine> engine7(
                          new GLHPMidPointCDOEngine(hCopula));
    QL_REQUIRE (LENGTH(hwAttachment) == LENGTH(hwDetachment),
                "data length does not match");
    for (Size i = 0; i < LENGTH(hwData7); i++) {
        correlation->setValue (hwData7[i].correlation);
        QL_REQUIRE (LENGTH(hwAttachment) == LENGTH(hwData7[i].trancheSpread),
                    "data length does not match");
        if (hwData7[i].nm == -1 && hwData7[i].nz == -1)
            hCopula.linkTo (pGaussianCopula);
        else if (hwData7[i].nm > 0 && hwData7[i].nz > 0) {
            boost::shared_ptr<OneFactorCopula> pStudentCopula (
                                  new OneFactorStudentCopula (hCorrelation,
                                                              hwData7[i].nm,
                                                              hwData7[i].nz));
            hCopula.linkTo (pStudentCopula);
        }
        else if (hwData7[i].nm > 0 && hwData7[i].nz == -1) {
            boost::shared_ptr<OneFactorCopula> pSGCopula (
                          new OneFactorStudentGaussianCopula (hCorrelation,
                                                              hwData7[i].nm));
            hCopula.linkTo (pSGCopula);
        }
        else if (hwData7[i].nm == -1 && hwData7[i].nz > 0) {
            boost::shared_ptr<OneFactorCopula> pGSCopula (
                          new OneFactorGaussianStudentCopula (hCorrelation,
                                                              hwData7[i].nz));
            hCopula.linkTo (pGSCopula);
        }
        else {
            continue;
        }
        for (Size j = 0; j < LENGTH(hwAttachment); j ++) {
            boost::shared_ptr<Basket> basketPtr (
                new Basket(names,
                           nominals,
                           pool,
                           std::vector<DefaultProbKey>(
                                names.size(),
                                NorthAmericaCorpDefaultKey(EURCurrency(),
                                                           SeniorSec)),
                           std::vector<boost::shared_ptr<RecoveryRateModel> > (
                                names.size(),
                                boost::shared_ptr<RecoveryRateModel>(
                                    new ConstantRecoveryModel(recovery,
                                                              SeniorSec))),
                           hwAttachment[j],
                           hwDetachment[j]));
            CDO cdo (hwAttachment[j], hwDetachment[j],
                     nominals, basket, hCopula,
                     true, schedule, premium, daycount, recovery, 0.0,
                     yieldHandle, nBuckets, period);
            SyntheticCDO cdoe(basketPtr, Protection::Seller,
                              schedule, 0.0, premium, daycount, Following,
                              yieldHandle);
            check(i, j, "performCalculations", cdo.fairPremium() * 1e4,
                  hwData7[i].trancheSpread[j], 1, 0.02);
            cdoe.setPricingEngine(engine1);
            check(i, j, "IHPIntegralEngine", cdoe.fairPremium() * 1e4,
                  hwData7[i].trancheSpread[j], 1, 0.03);
            cdoe.setPricingEngine(engine2);
            check(i, j, "IHPMidPointEngine", cdoe.fairPremium() * 1e4,
                  hwData7[i].trancheSpread[j], 1, 0.04);
            cdoe.setPricingEngine(engine3);
            check(i, j, "HPIntegralEngine", cdoe.fairPremium() * 1e4,
                  hwData7[i].trancheSpread[j], 1, 0.03);
            cdoe.setPricingEngine(engine4);
            check(i, j, "HPMidPointEngine", cdoe.fairPremium() * 1e4,
                  hwData7[i].trancheSpread[j], 1, 0.04);
            cdoe.setPricingEngine(engine5);
            check(i, j, "McEngine1 10k", cdoe.fairPremium() * 1e4,
                  hwData7[i].trancheSpread[j], 1, 0.07);
            cdoe.setPricingEngine(engine6);
            check(i, j, "McEngine2 10k", cdoe.fairPremium() * 1e4,
                  hwData7[i].trancheSpread[j], 1, 0.07);
            cdoe.setPricingEngine(engine7);
            check(i, j, "Gaussian LHP", cdoe.fairPremium() * 1e4,
                  hwData7[i].trancheSpread[j], 10, 0.5);
        }
    }
}
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/cdo.hpp
/home/deriversatile/QuantLib/QuantLibQt/test-suite/cdo.cpp