QuantLib: QuantLib::VolatilityBumpInstrumentJacobian Class Reference
QuantLib::VolatilityBumpInstrumentJacobian Class Reference
#include <bumpinstrumentjacobian.hpp>
Classes
struct Cap
struct Swaption
Public Member Functions
VolatilityBumpInstrumentJacobian (const VegaBumpCollection &bumps, const std::vector< Swaption > &swaptions, const std::vector< Cap > &caps)
const VegaBumpCollection & getInputBumps () const
const std::vector< Real > derivativesVolatility (Size j) const
const std::vector< Real > onePercentBump (Size j) const
const Matrix & getAllOnePercentBumps () const
Private Attributes
VegaBumpCollection bumps_
std::vector< Swaption > swaptions_
std::vector< Cap > caps_
std::valarray< bool > computed_
bool allComputed_
std::vector< std::vector< Real > > derivatives_
std::vector< std::vector< Real > > onePercentBumps_
Matrix bumpMatrix_
Detailed Description
Definition at line 32 of file bumpinstrumentjacobian.hpp.
Constructor & Destructor Documentation
QuantLib::VolatilityBumpInstrumentJacobian::VolatilityBumpInstrumentJacobian (const VegaBumpCollection & bumps, const std::vector< Swaption > & swaptions, const std::vector< Cap > & caps)
Definition at line 30 of file bumpinstrumentjacobian.cpp.
References allComputed_, derivatives_, and onePercentBumps_.
        : bumps_(bumps), swaptions_(swaptions), caps_(caps), computed_(false,swaptions.size()+caps.size()),
        derivatives_(swaptions.size()+caps.size(),std::vector<Real>(bumps.numberBumps())),
        bumpMatrix_(swaptions.size()+caps.size(),bumps_.numberBumps())
    {
        onePercentBumps_ = derivatives_;
        allComputed_=false;
    }
Member Function Documentation
const std::vector< Real > QuantLib::VolatilityBumpInstrumentJacobian::derivativesVolatility (Size j) const
Definition at line 42 of file bumpinstrumentjacobian.cpp.
References QuantLib::VegaBumpCollection::allBumps(), QuantLib::VegaBumpCollection::associatedModel(), bumpMatrix_, bumps_, caps_, computed_, derivatives_, anonymous_namespace{interpolations.cpp}::f(), QuantLib::VegaBumpCollection::numberBumps(), onePercentBumps_, QL_REQUIRE, swaptions_, anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::CapPseudoDerivative::volatilityDerivative().
Referenced by getAllOnePercentBumps(), and onePercentBump().
    {
        QL_REQUIRE(j < swaptions_.size()+caps_.size(), "too high index passed to VolatilityBumpInstrumentJacobian::derivativesVolatility");
        if (computed_[j])
            return derivatives_[j];
        derivatives_[j].resize(bumps_.numberBumps());
        onePercentBumps_[j].resize(bumps_.numberBumps());
        Real sizesq=0.0;
        computed_[j] = true;
        Size initj = j;
        if ( j < swaptions_.size()) // ok its a swaptions
        {
            SwaptionPseudoDerivative thisPseudo(bumps_.associatedModel(), swaptions_[j].startIndex_,swaptions_[j].endIndex_);
            for (Size k=0;  k < bumps_.numberBumps(); ++k)
            {
                Real v =0.0;
                for (Size i= bumps_.allBumps()[k].stepBegin(); i < bumps_.allBumps()[k].stepEnd(); ++i)
                {
                    const Matrix& fullDerivative = thisPseudo.volatilityDerivative(i);
                    for (Size f= bumps_.allBumps()[k].factorBegin(); f < bumps_.allBumps()[k].factorEnd(); ++f)
                        for (Size r= bumps_.allBumps()[k].rateBegin(); r < bumps_.allBumps()[k].rateEnd(); ++r)
                            v += fullDerivative[r][f];
                }
                derivatives_[j][k] =v;
                sizesq+= v*v;
            }
        }
        else // its a cap
        {
            j-= swaptions_.size();
            CapPseudoDerivative thisPseudo(bumps_.associatedModel(), caps_[j].strike_, caps_[j].startIndex_,caps_[j].endIndex_,1.0); // ifrst df shouldn't make any difference
            for (Size k=0;  k < bumps_.numberBumps(); ++k)
            {
                Real v =0.0;
                for (Size i= bumps_.allBumps()[k].stepBegin(); i < bumps_.allBumps()[k].stepEnd(); ++i)
                {
                    const Matrix& fullDerivative = thisPseudo.volatilityDerivative(i);
                    for (Size f= bumps_.allBumps()[k].factorBegin(); f < bumps_.allBumps()[k].factorEnd(); ++f)
                        for (Size r= bumps_.allBumps()[k].rateBegin(); r < bumps_.allBumps()[k].rateEnd(); ++r)
                            v += fullDerivative[r][f];
                }
                sizesq += v*v;
                derivatives_[initj][k] =v;
            }
        }
        for (Size k=0; k < bumps_.numberBumps(); ++k)
        {
            bumpMatrix_[initj][k] = onePercentBumps_[initj][k] = 0.01 * derivatives_[initj][k]/sizesq;
        }
     return derivatives_[initj];
    }
const Matrix & QuantLib::VolatilityBumpInstrumentJacobian::getAllOnePercentBumps () const
Definition at line 128 of file bumpinstrumentjacobian.cpp.
References allComputed_, bumpMatrix_, caps_, derivativesVolatility(), and swaptions_.
Referenced by QuantLib::OrthogonalizedBumpFinder::GetVegaBumps().
    {
        if (!allComputed_)
             for (Size i=0; i <swaptions_.size()+caps_.size(); ++i)
                derivativesVolatility(i);
        allComputed_ =true;
        return bumpMatrix_;
    }
const VegaBumpCollection& QuantLib::VolatilityBumpInstrumentJacobian::getInputBumps () const [inline]
Definition at line 56 of file bumpinstrumentjacobian.hpp.
References bumps_.
Referenced by QuantLib::OrthogonalizedBumpFinder::GetVegaBumps().
        {
            return bumps_;
        }
const std::vector< Real > QuantLib::VolatilityBumpInstrumentJacobian::onePercentBump (Size j) const
Definition at line 120 of file bumpinstrumentjacobian.cpp.
References derivativesVolatility(), and onePercentBumps_.
    {
        derivativesVolatility(j);
        return onePercentBumps_[j];
    }
Member Data Documentation
bool QuantLib::VolatilityBumpInstrumentJacobian::allComputed_ [mutable, private]
Definition at line 73 of file bumpinstrumentjacobian.hpp.
Referenced by getAllOnePercentBumps(), and VolatilityBumpInstrumentJacobian().
Matrix QuantLib::VolatilityBumpInstrumentJacobian::bumpMatrix_ [mutable, private]
Definition at line 77 of file bumpinstrumentjacobian.hpp.
Referenced by derivativesVolatility(), and getAllOnePercentBumps().
VegaBumpCollection QuantLib::VolatilityBumpInstrumentJacobian::bumps_ [private]
Definition at line 69 of file bumpinstrumentjacobian.hpp.
Referenced by derivativesVolatility(), and getInputBumps().
std::vector<Cap> QuantLib::VolatilityBumpInstrumentJacobian::caps_ [private]
Definition at line 71 of file bumpinstrumentjacobian.hpp.
Referenced by derivativesVolatility(), and getAllOnePercentBumps().
std::valarray<bool> QuantLib::VolatilityBumpInstrumentJacobian::computed_ [mutable, private]
Definition at line 72 of file bumpinstrumentjacobian.hpp.
Referenced by derivativesVolatility().
std::vector<std::vector<Real> > QuantLib::VolatilityBumpInstrumentJacobian::derivatives_ [mutable, private]
Definition at line 74 of file bumpinstrumentjacobian.hpp.
Referenced by derivativesVolatility(), and VolatilityBumpInstrumentJacobian().
std::vector<std::vector<Real> > QuantLib::VolatilityBumpInstrumentJacobian::onePercentBumps_ [mutable, private]
Definition at line 76 of file bumpinstrumentjacobian.hpp.
Referenced by derivativesVolatility(), onePercentBump(), and VolatilityBumpInstrumentJacobian().
std::vector<Swaption> QuantLib::VolatilityBumpInstrumentJacobian::swaptions_ [private]
Definition at line 70 of file bumpinstrumentjacobian.hpp.
Referenced by derivativesVolatility(), and getAllOnePercentBumps().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/pathwisegreeks/bumpinstrumentjacobian.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/pathwisegreeks/bumpinstrumentjacobian.cpp