QuantLib: QuantLib::MCEuropeanBasketEngine< RNG, S > Class Template Reference
QuantLib::MCEuropeanBasketEngine< RNG, S > Class Template Reference
Pricing engine for European basket options using Monte Carlo simulation.
#include <mceuropeanbasketengine.hpp>
Public Types
typedef McSimulation
< MultiVariate, RNG, S >
::path_generator_type path_generator_type
typedef McSimulation
< MultiVariate, RNG, S >
::path_pricer_type path_pricer_type
typedef McSimulation
< MultiVariate, RNG, S >
::stats_type stats_type
Public Member Functions
MCEuropeanBasketEngine (const boost::shared_ptr< StochasticProcessArray > &, Size timeSteps, Size timeStepsPerYear, bool brownianBridge, bool antitheticVariate, Size requiredSamples, Real requiredTolerance, Size maxSamples, BigNatural seed)
void calculate () const
Protected Member Functions
TimeGrid timeGrid () const
boost::shared_ptr
< path_generator_type > pathGenerator () const
boost::shared_ptr
< path_pricer_type > pathPricer () const
Protected Attributes
boost::shared_ptr
< StochasticProcessArray > processes_
Size timeSteps_
Size timeStepsPerYear_
Size requiredSamples_
Size maxSamples_
Real requiredTolerance_
bool brownianBridge_
BigNatural seed_
Detailed Description
template<class RNG = PseudoRandom, class S = Statistics>
class QuantLib::MCEuropeanBasketEngine< RNG, S >
Pricing engine for European basket options using Monte Carlo simulation.
Test:
the correctness of the returned value is tested by reproducing results available in literature.
Definition at line 43 of file mceuropeanbasketengine.hpp.
Member Typedef Documentation
template<class RNG = PseudoRandom, class S = Statistics> typedef McSimulation<MultiVariate,RNG,S>::path_generator_type QuantLib::MCEuropeanBasketEngine< RNG, S >::path_generator_type
Reimplemented from QuantLib::McSimulation< MultiVariate, RNG, S >.
Definition at line 47 of file mceuropeanbasketengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> typedef McSimulation<MultiVariate,RNG,S>::path_pricer_type QuantLib::MCEuropeanBasketEngine< RNG, S >::path_pricer_type
Reimplemented from QuantLib::McSimulation< MultiVariate, RNG, S >.
Definition at line 49 of file mceuropeanbasketengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> typedef McSimulation<MultiVariate,RNG,S>::stats_type QuantLib::MCEuropeanBasketEngine< RNG, S >::stats_type
Reimplemented from QuantLib::McSimulation< MultiVariate, RNG, S >.
Definition at line 51 of file mceuropeanbasketengine.hpp.
Constructor & Destructor Documentation
template<class RNG , class S > QuantLib::MCEuropeanBasketEngine< RNG, S >::MCEuropeanBasketEngine (const boost::shared_ptr< StochasticProcessArray > & processes, Size timeSteps, Size timeStepsPerYear, bool brownianBridge, bool antitheticVariate, Size requiredSamples, Real requiredTolerance, Size maxSamples, BigNatural seed) [inline]
Definition at line 143 of file mceuropeanbasketengine.hpp.
References QuantLib::MCEuropeanBasketEngine< RNG, S >::processes_, QL_REQUIRE, and QuantLib::Observer::registerWith().
    : McSimulation<MultiVariate,RNG,S>(antitheticVariate, false),
      processes_(processes), timeSteps_(timeSteps),
      timeStepsPerYear_(timeStepsPerYear),
      requiredSamples_(requiredSamples), maxSamples_(maxSamples),
      requiredTolerance_(requiredTolerance),
      brownianBridge_(brownianBridge), seed_(seed) {
        QL_REQUIRE(timeSteps != Null<Size>() ||
                   timeStepsPerYear != Null<Size>(),
                   "no time steps provided");
        QL_REQUIRE(timeSteps == Null<Size>() ||
                   timeStepsPerYear == Null<Size>(),
                   "both time steps and time steps per year were provided");
        QL_REQUIRE(timeSteps != 0,
                   "timeSteps must be positive, " << timeSteps <<
                   " not allowed");
        QL_REQUIRE(timeStepsPerYear != 0,
                   "timeStepsPerYear must be positive, " << timeStepsPerYear <<
                   " not allowed");
        registerWith(processes_);
    }
Member Function Documentation
template<class RNG = PseudoRandom, class S = Statistics> void QuantLib::MCEuropeanBasketEngine< RNG, S >::calculate () const [inline, virtual]
Implements QuantLib::PricingEngine.
Definition at line 62 of file mceuropeanbasketengine.hpp.
References QuantLib::Instrument::results::errorEstimate, QuantLib::MCEuropeanBasketEngine< RNG, S >::maxSamples_, QuantLib::McSimulation< MultiVariate, RNG, S >::mcModel_, QuantLib::MCEuropeanBasketEngine< RNG, S >::requiredSamples_, QuantLib::MCEuropeanBasketEngine< RNG, S >::requiredTolerance_, QuantLib::GenericEngine< BasketOption::arguments, BasketOption::results >::results_, and QuantLib::Instrument::results::value.
{
            McSimulation<MultiVariate,RNG,S>::calculate(requiredTolerance_,
                                                        requiredSamples_,
                                                        maxSamples_);
            results_.value = this->mcModel_->sampleAccumulator().mean();
            if (RNG::allowsErrorEstimate)
            results_.errorEstimate =
                this->mcModel_->sampleAccumulator().errorEstimate();
        }
template<class RNG = PseudoRandom, class S = Statistics> boost::shared_ptr<path_generator_type> QuantLib::MCEuropeanBasketEngine< RNG, S >::pathGenerator () const [inline, protected, virtual]
Implements QuantLib::McSimulation< MultiVariate, RNG, S >.
Definition at line 74 of file mceuropeanbasketengine.hpp.
References QuantLib::GenericEngine< BasketOption::arguments, BasketOption::results >::arguments_, QuantLib::MCEuropeanBasketEngine< RNG, S >::brownianBridge_, QuantLib::MCEuropeanBasketEngine< RNG, S >::processes_, QL_REQUIRE, QuantLib::MCEuropeanBasketEngine< RNG, S >::seed_, QuantLib::TimeGrid::size(), and QuantLib::MCEuropeanBasketEngine< RNG, S >::timeGrid().
{
            boost::shared_ptr<BasketPayoff> payoff =
                boost::dynamic_pointer_cast<BasketPayoff>(
                                                          arguments_.payoff);
            QL_REQUIRE(payoff, "non-basket payoff given");
            Size numAssets = processes_->size();
            TimeGrid grid = timeGrid();
            typename RNG::rsg_type gen =
                RNG::make_sequence_generator(numAssets*(grid.size()-1),seed_);
            return boost::shared_ptr<path_generator_type>(
                         new path_generator_type(processes_,
                                                 grid, gen, brownianBridge_));
        }
template<class RNG , class S > boost::shared_ptr< typename MCEuropeanBasketEngine< RNG, S >::path_pricer_type > QuantLib::MCEuropeanBasketEngine< RNG, S >::pathPricer () const [inline, protected, virtual]
Implements QuantLib::McSimulation< MultiVariate, RNG, S >.
Definition at line 192 of file mceuropeanbasketengine.hpp.
References QL_REQUIRE.
{
        boost::shared_ptr<BasketPayoff> payoff =
            boost::dynamic_pointer_cast<BasketPayoff>(arguments_.payoff);
        QL_REQUIRE(payoff, "non-basket payoff given");
        boost::shared_ptr<GeneralizedBlackScholesProcess> process =
            boost::dynamic_pointer_cast<GeneralizedBlackScholesProcess>(
                                                      processes_->process(0));
        QL_REQUIRE(process, "Black-Scholes process required");
        return boost::shared_ptr<
                    typename MCEuropeanBasketEngine<RNG,S>::path_pricer_type>(
            new EuropeanMultiPathPricer(payoff,
                                        process->riskFreeRate()->discount(
                                           arguments_.exercise->lastDate())));
    }
template<class RNG , class S > TimeGrid QuantLib::MCEuropeanBasketEngine< RNG, S >::timeGrid () const [inline, protected, virtual]
Implements QuantLib::McSimulation< MultiVariate, RNG, S >.
Definition at line 175 of file mceuropeanbasketengine.hpp.
References QL_FAIL.
Referenced by QuantLib::MCEuropeanBasketEngine< RNG, S >::pathGenerator().
{
        Time residualTime = processes_->time(
                                       this->arguments_.exercise->lastDate());
        if (timeSteps_ != Null<Size>()) {
            return TimeGrid(residualTime, timeSteps_);
        } else if (timeStepsPerYear_ != Null<Size>()) {
            Size steps = static_cast<Size>(timeStepsPerYear_*residualTime);
            return TimeGrid(residualTime, std::max<Size>(steps, 1));
        } else {
            QL_FAIL("time steps not specified");
        }
    }
Member Data Documentation
template<class RNG = PseudoRandom, class S = Statistics> bool QuantLib::MCEuropeanBasketEngine< RNG, S >::brownianBridge_ [protected]
Definition at line 98 of file mceuropeanbasketengine.hpp.
Referenced by QuantLib::MCEuropeanBasketEngine< RNG, S >::pathGenerator().
template<class RNG = PseudoRandom, class S = Statistics> Size QuantLib::MCEuropeanBasketEngine< RNG, S >::maxSamples_ [protected]
Definition at line 96 of file mceuropeanbasketengine.hpp.
Referenced by QuantLib::MCEuropeanBasketEngine< RNG, S >::calculate().
template<class RNG = PseudoRandom, class S = Statistics> boost::shared_ptr<StochasticProcessArray> QuantLib::MCEuropeanBasketEngine< RNG, S >::processes_ [protected]
Definition at line 93 of file mceuropeanbasketengine.hpp.
Referenced by QuantLib::MCEuropeanBasketEngine< RNG, S >::MCEuropeanBasketEngine(), and QuantLib::MCEuropeanBasketEngine< RNG, S >::pathGenerator().
template<class RNG = PseudoRandom, class S = Statistics> Size QuantLib::MCEuropeanBasketEngine< RNG, S >::requiredSamples_ [protected]
Definition at line 95 of file mceuropeanbasketengine.hpp.
Referenced by QuantLib::MCEuropeanBasketEngine< RNG, S >::calculate().
template<class RNG = PseudoRandom, class S = Statistics> Real QuantLib::MCEuropeanBasketEngine< RNG, S >::requiredTolerance_ [protected]
Definition at line 97 of file mceuropeanbasketengine.hpp.
Referenced by QuantLib::MCEuropeanBasketEngine< RNG, S >::calculate().
template<class RNG = PseudoRandom, class S = Statistics> BigNatural QuantLib::MCEuropeanBasketEngine< RNG, S >::seed_ [protected]
Definition at line 99 of file mceuropeanbasketengine.hpp.
Referenced by QuantLib::MCEuropeanBasketEngine< RNG, S >::pathGenerator().
template<class RNG = PseudoRandom, class S = Statistics> Size QuantLib::MCEuropeanBasketEngine< RNG, S >::timeSteps_ [protected]
Definition at line 94 of file mceuropeanbasketengine.hpp.
template<class RNG = PseudoRandom, class S = Statistics> Size QuantLib::MCEuropeanBasketEngine< RNG, S >::timeStepsPerYear_ [protected]
Definition at line 94 of file mceuropeanbasketengine.hpp.
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/basket/mceuropeanbasketengine.hpp