QuantLib: QuantLib::Problem Class Reference
QuantLib::Problem Class Reference
Constrained optimization problem.
#include <problem.hpp>
Public Member Functions
Problem (CostFunction &costFunction, Constraint &constraint, const Array &initialValue=Array())
default constructor
void reset ()
Real value (const Array &x)
call cost function computation and increment evaluation counter
Disposable< Array > values (const Array &x)
call cost values computation and increment evaluation counter
void gradient (Array &grad_f, const Array &x)
call cost function gradient computation and increment
Real valueAndGradient (Array &grad_f, const Array &x)
call cost function computation and it gradient
Constraint & constraint () const
Constraint.
CostFunction & costFunction () const
Cost function.
void setCurrentValue (const Array &currentValue)
const Array & currentValue () const
current value of the local minimum
void setFunctionValue (Real functionValue)
Real functionValue () const
value of cost function
void setGradientNormValue (Real squaredNorm)
Real gradientNormValue () const
value of cost function gradient norm
Integer functionEvaluation () const
number of evaluation of cost function
Integer gradientEvaluation () const
number of evaluation of cost function gradient
Protected Attributes
CostFunction & costFunction_
Unconstrained cost function.
Constraint & constraint_
Constraint.
Array currentValue_
current value of the local minimum
Real functionValue_
function and gradient norm values at the curentValue_ (i.e. the last step)
Real squaredNorm_
Integer functionEvaluation_
number of evaluation of cost function and its gradient
Integer gradientEvaluation_
Detailed Description
Constrained optimization problem.
Definition at line 36 of file problem.hpp.
Constructor & Destructor Documentation
QuantLib::Problem::Problem (CostFunction & costFunction, Constraint & constraint, const Array & initialValue = Array()) [inline]
default constructor
Definition at line 39 of file problem.hpp.
        : costFunction_(costFunction), constraint_(constraint),
          currentValue_(initialValue) {}
Member Function Documentation
Constraint& QuantLib::Problem::constraint () const [inline]
Constraint.
Definition at line 65 of file problem.hpp.
References constraint_.
Referenced by QuantLib::Simplex::extrapolate(), QuantLib::LevenbergMarquardt::fcn(), QuantLib::Simplex::minimize(), and QuantLib::ArmijoLineSearch::operator()().
{ return constraint_; }
CostFunction& QuantLib::Problem::costFunction () const [inline]
Cost function.
Definition at line 68 of file problem.hpp.
References costFunction_.
Referenced by QuantLib::LevenbergMarquardt::minimize().
{ return costFunction_; }
const Array& QuantLib::Problem::currentValue () const [inline]
current value of the local minimum
Definition at line 75 of file problem.hpp.
References currentValue_.
Referenced by QuantLib::FittedBondDiscountCurve::FittingMethod::calculate(), QuantLib::CalibratedModel::calibrate(), QuantLib::CmsMarketCalibration::compute(), QuantLib::AbcdCalibration::compute(), QuantLib::genericEarlyExerciseOptimization(), QuantLib::BFGS::getUpdatedDirection(), QuantLib::anonymous_namespace{pseudosqrt.cpp}::hypersphereOptimize(), QuantLib::LevenbergMarquardt::minimize(), QuantLib::LineSearchBasedMethod::minimize(), QuantLib::Simplex::minimize(), QuantLib::ArmijoLineSearch::operator()(), QuantLib::NonLinearLeastSquare::perform(), setCurrentValue(), OptimizersTest::test(), and QuantLib::detail::SABRInterpolationImpl< I1, I2 >::update().
{ return currentValue_; }
Integer QuantLib::Problem::functionEvaluation () const [inline]
number of evaluation of cost function
Definition at line 91 of file problem.hpp.
References functionEvaluation_.
Referenced by QuantLib::FittedBondDiscountCurve::FittingMethod::calculate(), and OptimizersTest::test().
{ return functionEvaluation_; }
Real QuantLib::Problem::functionValue () const [inline]
value of cost function
Definition at line 82 of file problem.hpp.
References functionValue_.
Referenced by QuantLib::FittedBondDiscountCurve::FittingMethod::calculate(), QuantLib::ArmijoLineSearch::operator()(), QuantLib::NonLinearLeastSquare::perform(), and setFunctionValue().
{ return functionValue_; }
void QuantLib::Problem::gradient (Array & grad_f, const Array & x) [inline]
call cost function gradient computation and increment
Definition at line 120 of file problem.hpp.
References costFunction_, QuantLib::CostFunction::gradient(), and gradientEvaluation_.
Referenced by QuantLib::ArmijoLineSearch::operator()().
{
        ++gradientEvaluation_;
        costFunction_.gradient(grad_f, x);
    }
Integer QuantLib::Problem::gradientEvaluation () const [inline]
number of evaluation of cost function gradient
Definition at line 94 of file problem.hpp.
References gradientEvaluation_.
Referenced by OptimizersTest::test().
{ return gradientEvaluation_; }
Real QuantLib::Problem::gradientNormValue () const [inline]
value of cost function gradient norm
Definition at line 88 of file problem.hpp.
References squaredNorm_.
Referenced by QuantLib::ConjugateGradient::getUpdatedDirection(), and QuantLib::ArmijoLineSearch::operator()().
{ return squaredNorm_; }
void QuantLib::Problem::reset () [inline]
Warning:
it does not reset the current minumum to any initial value
Definition at line 133 of file problem.hpp.
References functionEvaluation_, functionValue_, gradientEvaluation_, and squaredNorm_.
Referenced by QuantLib::LevenbergMarquardt::minimize(), QuantLib::LineSearchBasedMethod::minimize(), and QuantLib::Simplex::minimize().
{
        functionEvaluation_ = gradientEvaluation_ = 0;
        functionValue_ = squaredNorm_ = Null<Real>();
    }
void QuantLib::Problem::setCurrentValue (const Array & currentValue) [inline]
Definition at line 70 of file problem.hpp.
References currentValue(), and currentValue_.
Referenced by QuantLib::LevenbergMarquardt::minimize(), QuantLib::LineSearchBasedMethod::minimize(), QuantLib::Simplex::minimize(), and OptimizersTest::test().
{
            currentValue_=currentValue;
        }
void QuantLib::Problem::setFunctionValue (Real functionValue) [inline]
Definition at line 77 of file problem.hpp.
References functionValue(), and functionValue_.
Referenced by QuantLib::LevenbergMarquardt::minimize(), QuantLib::LineSearchBasedMethod::minimize(), and QuantLib::Simplex::minimize().
{
            functionValue_=functionValue;
        }
void QuantLib::Problem::setGradientNormValue (Real squaredNorm) [inline]
Definition at line 84 of file problem.hpp.
References squaredNorm_.
Referenced by QuantLib::LineSearchBasedMethod::minimize().
{
            squaredNorm_=squaredNorm;
        }
Real QuantLib::Problem::value (const Array & x) [inline]
call cost function computation and increment evaluation counter
Definition at line 110 of file problem.hpp.
References costFunction_, functionEvaluation_, and QuantLib::CostFunction::value().
Referenced by QuantLib::Simplex::extrapolate(), QuantLib::Simplex::minimize(), and QuantLib::ArmijoLineSearch::operator()().
{
        ++functionEvaluation_;
        return costFunction_.value(x);
    }
Real QuantLib::Problem::valueAndGradient (Array & grad_f, const Array & x) [inline]
call cost function computation and it gradient
Definition at line 126 of file problem.hpp.
References costFunction_, functionEvaluation_, gradientEvaluation_, and QuantLib::CostFunction::valueAndGradient().
Referenced by QuantLib::LineSearchBasedMethod::minimize().
{
        ++functionEvaluation_;
        ++gradientEvaluation_;
        return costFunction_.valueAndGradient(grad_f, x);
    }
Disposable< Array > QuantLib::Problem::values (const Array & x) [inline]
call cost values computation and increment evaluation counter
Definition at line 115 of file problem.hpp.
References costFunction_, functionEvaluation_, and QuantLib::CostFunction::values().
Referenced by QuantLib::CalibratedModel::calibrate(), QuantLib::LevenbergMarquardt::fcn(), and OptimizersTest::test().
{
        ++functionEvaluation_;
        return costFunction_.values(x);
    }
Member Data Documentation
Constraint& QuantLib::Problem::constraint_ [protected]
Constraint.
Definition at line 100 of file problem.hpp.
Referenced by constraint().
CostFunction& QuantLib::Problem::costFunction_ [protected]
Unconstrained cost function.
Definition at line 98 of file problem.hpp.
Referenced by costFunction(), gradient(), value(), valueAndGradient(), and values().
Array QuantLib::Problem::currentValue_ [protected]
current value of the local minimum
Definition at line 102 of file problem.hpp.
Referenced by currentValue(), and setCurrentValue().
Integer QuantLib::Problem::functionEvaluation_ [protected]
number of evaluation of cost function and its gradient
Definition at line 106 of file problem.hpp.
Referenced by functionEvaluation(), reset(), value(), valueAndGradient(), and values().
Real QuantLib::Problem::functionValue_ [protected]
function and gradient norm values at the curentValue_ (i.e. the last step)
Definition at line 104 of file problem.hpp.
Referenced by functionValue(), reset(), and setFunctionValue().
Integer QuantLib::Problem::gradientEvaluation_ [protected]
Definition at line 106 of file problem.hpp.
Referenced by gradient(), gradientEvaluation(), reset(), and valueAndGradient().
Real QuantLib::Problem::squaredNorm_ [protected]
Definition at line 104 of file problem.hpp.
Referenced by gradientNormValue(), reset(), and setGradientNormValue().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/optimization/problem.hpp