QuantLib: QuantLib::LastFixingQuote Class Reference
QuantLib::LastFixingQuote Class Reference
Quote adapter for the last fixing available of a given Index.
#include <lastfixingquote.hpp>
Public Member Functions
LastFixingQuote (const boost::shared_ptr< Index > &index)
Quote interface
Real value () const
returns the current value
bool isValid () const
returns true if the Quote holds a valid value
Observer interface
void update ()
LastFixingQuote interface
const boost::shared_ptr< Index > & index () const
Date referenceDate () const
Protected Attributes
boost::shared_ptr< Index > index_
Detailed Description
Quote adapter for the last fixing available of a given Index.
Definition at line 34 of file lastfixingquote.hpp.
Constructor & Destructor Documentation
QuantLib::LastFixingQuote::LastFixingQuote (const boost::shared_ptr< Index > & index)
Definition at line 24 of file lastfixingquote.cpp.
References index_, and QuantLib::Observer::registerWith().
    : index_(index) {
        registerWith(index_);
    }
Member Function Documentation
const boost::shared_ptr<Index>& QuantLib::LastFixingQuote::index () const [inline]
Definition at line 49 of file lastfixingquote.hpp.
References index_.
{ return index_; }
bool QuantLib::LastFixingQuote::isValid () const [virtual]
returns true if the Quote holds a valid value
Implements QuantLib::Quote.
Definition at line 35 of file lastfixingquote.cpp.
References index_.
Referenced by value().
{
        return !index_->timeSeries().empty();
    }
Date QuantLib::LastFixingQuote::referenceDate () const
Definition at line 39 of file lastfixingquote.cpp.
References index_.
Referenced by value().
{
        return index_->timeSeries().lastDate();
    }
void QuantLib::LastFixingQuote::update () [inline, virtual]
This method must be implemented in derived classes. An instance of Observer does not call this method directly: instead, it will be called by the observables the instance registered with when they need to notify any changes.
Implements QuantLib::Observer.
Definition at line 45 of file lastfixingquote.hpp.
References QuantLib::Observable::notifyObservers().
{ notifyObservers(); }
Real QuantLib::LastFixingQuote::value () const [virtual]
returns the current value
Implements QuantLib::Quote.
Definition at line 29 of file lastfixingquote.cpp.
References index_, isValid(), QL_ENSURE, and referenceDate().
{
        QL_ENSURE(isValid(),
                  index_->name() << " has no fixing");
        return index_->fixing(referenceDate());
    }
Member Data Documentation
boost::shared_ptr<Index> QuantLib::LastFixingQuote::index_ [protected]
Definition at line 53 of file lastfixingquote.hpp.
Referenced by index(), isValid(), LastFixingQuote(), referenceDate(), and value().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/quotes/lastfixingquote.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/quotes/lastfixingquote.cpp