QuantLib: QuantLib::detail::BicubicSplineImpl< I1, I2, M > Class Template Reference
QuantLib::detail::BicubicSplineImpl< I1, I2, M > Class Template Reference
#include <bicubicsplineinterpolation.hpp>
Public Member Functions
BicubicSplineImpl (const I1 &xBegin, const I1 &xEnd, const I2 &yBegin, const I2 &yEnd, const M &zData)
void calculate ()
Real value (Real x, Real y) const
Real derivativeX (Real x, Real y) const
Real secondDerivativeX (Real x, Real y) const
Real derivativeY (Real x, Real y) const
Real secondDerivativeY (Real x, Real y) const
Real derivativeXY (Real x, Real y) const
Private Attributes
std::vector< Interpolation > splines_
Detailed Description
template<class I1, class I2, class M>
class QuantLib::detail::BicubicSplineImpl< I1, I2, M >
Definition at line 45 of file bicubicsplineinterpolation.hpp.
Constructor & Destructor Documentation
template<class I1 , class I2 , class M > QuantLib::detail::BicubicSplineImpl< I1, I2, M >::BicubicSplineImpl (const I1 & xBegin, const I1 & xEnd, const I2 & yBegin, const I2 & yEnd, const M & zData) [inline]
Definition at line 49 of file bicubicsplineinterpolation.hpp.
References QuantLib::detail::BicubicSplineImpl< I1, I2, M >::calculate().
            : Interpolation2D::templateImpl<I1,I2,M>(xBegin,xEnd,
                                                     yBegin,yEnd,
                                                     zData) {
                calculate();
            }
Member Function Documentation
template<class I1 , class I2 , class M > void QuantLib::detail::BicubicSplineImpl< I1, I2, M >::calculate () [inline, virtual]
Implements QuantLib::Interpolation2D::Impl.
Definition at line 57 of file bicubicsplineinterpolation.hpp.
References QuantLib::CubicInterpolation::SecondDerivative, QuantLib::CubicInterpolation::Spline, QuantLib::detail::BicubicSplineImpl< I1, I2, M >::splines_, QuantLib::Interpolation2D::templateImpl< I1, I2, M >::xBegin_, QuantLib::Interpolation2D::templateImpl< I1, I2, M >::xEnd_, and QuantLib::Interpolation2D::templateImpl< I1, I2, M >::zData_.
Referenced by QuantLib::detail::BicubicSplineImpl< I1, I2, M >::BicubicSplineImpl().
{
                splines_.reserve(this->zData_.rows());
                for (Size i=0; i<(this->zData_.rows()); ++i)
                    splines_.push_back(CubicInterpolation(
                                this->xBegin_, this->xEnd_,
                                this->zData_.row_begin(i),
                                CubicInterpolation::Spline, false,
                                CubicInterpolation::SecondDerivative, 0.0,
                                CubicInterpolation::SecondDerivative, 0.0));
            }
template<class I1 , class I2 , class M > Real QuantLib::detail::BicubicSplineImpl< I1, I2, M >::derivativeX (Real x, Real y) const [inline, virtual]
Implements QuantLib::detail::BicubicSplineDerivatives.
Definition at line 80 of file bicubicsplineinterpolation.hpp.
References QuantLib::Interpolation::derivative(), QuantLib::CubicInterpolation::SecondDerivative, QuantLib::CubicInterpolation::Spline, QuantLib::detail::BicubicSplineImpl< I1, I2, M >::value(), QuantLib::Interpolation2D::templateImpl< I1, I2, M >::xBegin_, QuantLib::Interpolation2D::templateImpl< I1, I2, M >::xEnd_, and QuantLib::Interpolation2D::templateImpl< I1, I2, M >::zData_.
{
                std::vector<Real> section(this->zData_.columns());
                for (Size i=0; i < section.size(); ++i) {
                    section[i] = value(this->xBegin_[i], y);
                }
                return CubicInterpolation(
                    this->xBegin_, this->xEnd_,
                    section.begin(),
                    CubicInterpolation::Spline, false,
                    CubicInterpolation::SecondDerivative, 0.0,
                    CubicInterpolation::SecondDerivative, 0.0).derivative(x);
            }
template<class I1 , class I2 , class M > Real QuantLib::detail::BicubicSplineImpl< I1, I2, M >::derivativeXY (Real x, Real y) const [inline, virtual]
Implements QuantLib::detail::BicubicSplineDerivatives.
Definition at line 136 of file bicubicsplineinterpolation.hpp.
References QuantLib::Interpolation::derivative(), QuantLib::detail::BicubicSplineImpl< I1, I2, M >::derivativeY(), QuantLib::CubicInterpolation::SecondDerivative, QuantLib::CubicInterpolation::Spline, QuantLib::Interpolation2D::templateImpl< I1, I2, M >::xBegin_, QuantLib::Interpolation2D::templateImpl< I1, I2, M >::xEnd_, and QuantLib::Interpolation2D::templateImpl< I1, I2, M >::zData_.
{
                std::vector<Real> section(this->zData_.columns());
                for (Size i=0; i < section.size(); ++i) {
                    section[i] = derivativeY(this->xBegin_[i], y);
                }
                return CubicInterpolation(
                    this->xBegin_, this->xEnd_,
                    section.begin(),
                    CubicInterpolation::Spline, false,
                    CubicInterpolation::SecondDerivative, 0.0,
                    CubicInterpolation::SecondDerivative, 0.0).derivative(x);
            }
template<class I1 , class I2 , class M > Real QuantLib::detail::BicubicSplineImpl< I1, I2, M >::derivativeY (Real x, Real y) const [inline, virtual]
Implements QuantLib::detail::BicubicSplineDerivatives.
Definition at line 109 of file bicubicsplineinterpolation.hpp.
References QuantLib::Interpolation::derivative(), QuantLib::CubicInterpolation::SecondDerivative, QuantLib::CubicInterpolation::Spline, QuantLib::detail::BicubicSplineImpl< I1, I2, M >::splines_, QuantLib::Interpolation2D::templateImpl< I1, I2, M >::yBegin_, and QuantLib::Interpolation2D::templateImpl< I1, I2, M >::yEnd_.
Referenced by QuantLib::detail::BicubicSplineImpl< I1, I2, M >::derivativeXY().
{
                std::vector<Real> section(splines_.size());
                for (Size i=0; i<splines_.size(); i++)
                    section[i]=splines_[i](x,true);
                return CubicInterpolation(
                    this->yBegin_, this->yEnd_,
                    section.begin(),
                    CubicInterpolation::Spline, false,
                    CubicInterpolation::SecondDerivative, 0.0,
                    CubicInterpolation::SecondDerivative, 0.0).derivative(y);
            }
template<class I1 , class I2 , class M > Real QuantLib::detail::BicubicSplineImpl< I1, I2, M >::secondDerivativeX (Real x, Real y) const [inline, virtual]
Implements QuantLib::detail::BicubicSplineDerivatives.
Definition at line 94 of file bicubicsplineinterpolation.hpp.
References QuantLib::Interpolation::secondDerivative(), QuantLib::CubicInterpolation::SecondDerivative, QuantLib::CubicInterpolation::Spline, QuantLib::detail::BicubicSplineImpl< I1, I2, M >::value(), QuantLib::Interpolation2D::templateImpl< I1, I2, M >::xBegin_, QuantLib::Interpolation2D::templateImpl< I1, I2, M >::xEnd_, and QuantLib::Interpolation2D::templateImpl< I1, I2, M >::zData_.
{
                std::vector<Real> section(this->zData_.columns());
                for (Size i=0; i < section.size(); ++i) {
                    section[i] = value(this->xBegin_[i], y);
                }
                return CubicInterpolation(
                    this->xBegin_, this->xEnd_,
                    section.begin(),
                    CubicInterpolation::Spline, false,
                    CubicInterpolation::SecondDerivative, 0.0,
                    CubicInterpolation::SecondDerivative, 0.0)
                                                          .secondDerivative(x);
            }
template<class I1 , class I2 , class M > Real QuantLib::detail::BicubicSplineImpl< I1, I2, M >::secondDerivativeY (Real x, Real y) const [inline, virtual]
Implements QuantLib::detail::BicubicSplineDerivatives.
Definition at line 122 of file bicubicsplineinterpolation.hpp.
References QuantLib::Interpolation::secondDerivative(), QuantLib::CubicInterpolation::SecondDerivative, QuantLib::CubicInterpolation::Spline, QuantLib::detail::BicubicSplineImpl< I1, I2, M >::splines_, QuantLib::Interpolation2D::templateImpl< I1, I2, M >::yBegin_, and QuantLib::Interpolation2D::templateImpl< I1, I2, M >::yEnd_.
{
                std::vector<Real> section(splines_.size());
                for (Size i=0; i<splines_.size(); i++)
                    section[i]=splines_[i](x,true);
                return CubicInterpolation(
                    this->yBegin_, this->yEnd_,
                    section.begin(),
                    CubicInterpolation::Spline, false,
                    CubicInterpolation::SecondDerivative, 0.0,
                    CubicInterpolation::SecondDerivative, 0.0)
                                                        .secondDerivative(y);
            }
template<class I1 , class I2 , class M > Real QuantLib::detail::BicubicSplineImpl< I1, I2, M >::value (Real x, Real y) const [inline, virtual]
Implements QuantLib::Interpolation2D::Impl.
Definition at line 67 of file bicubicsplineinterpolation.hpp.
References QuantLib::CubicInterpolation::SecondDerivative, QuantLib::CubicInterpolation::Spline, QuantLib::detail::BicubicSplineImpl< I1, I2, M >::splines_, QuantLib::Interpolation2D::templateImpl< I1, I2, M >::yBegin_, and QuantLib::Interpolation2D::templateImpl< I1, I2, M >::yEnd_.
Referenced by QuantLib::detail::BicubicSplineImpl< I1, I2, M >::derivativeX(), and QuantLib::detail::BicubicSplineImpl< I1, I2, M >::secondDerivativeX().
{
                std::vector<Real> section(splines_.size());
                for (Size i=0; i<splines_.size(); i++)
                    section[i]=splines_[i](x,true);
                CubicInterpolation spline(this->yBegin_, this->yEnd_,
                                          section.begin(),
                                          CubicInterpolation::Spline, false,
                                          CubicInterpolation::SecondDerivative, 0.0,
                                          CubicInterpolation::SecondDerivative, 0.0);
                return spline(y,true);
            }
Member Data Documentation
template<class I1 , class I2 , class M > std::vector<Interpolation> QuantLib::detail::BicubicSplineImpl< I1, I2, M >::splines_ [private]
Definition at line 151 of file bicubicsplineinterpolation.hpp.
Referenced by QuantLib::detail::BicubicSplineImpl< I1, I2, M >::calculate(), QuantLib::detail::BicubicSplineImpl< I1, I2, M >::derivativeY(), QuantLib::detail::BicubicSplineImpl< I1, I2, M >::secondDerivativeY(), and QuantLib::detail::BicubicSplineImpl< I1, I2, M >::value().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/interpolations/bicubicsplineinterpolation.hpp