QuantLib: QuantLib::MultiStepSwap Class Reference
QuantLib::MultiStepSwap Class Reference
#include <multistepswap.hpp>
Public Member Functions
MultiStepSwap (const std::vector< Time > &rateTimes, const std::vector< Real > &fixedAccruals, const std::vector< Real > &floatingAccruals, const std::vector< Time > &paymentTimes, Rate fixedRate, bool payer=true)
MarketModelMultiProduct interface
std::vector< Time > possibleCashFlowTimes () const
Size numberOfProducts () const
Size maxNumberOfCashFlowsPerProductPerStep () const
void reset ()
during simulation put product at start of path
bool nextTimeStep (const CurveState &currentState, std::vector< Size > &numberCashFlowsThisStep, std::vector< std::vector< CashFlow > > &cashFlowsGenerated)
return value indicates whether path is finished, TRUE means done
std::auto_ptr
< MarketModelMultiProduct > clone () const
returns a newly-allocated copy of itself
Private Attributes
std::vector< Real > fixedAccruals_
std::vector< Real > floatingAccruals_
std::vector< Time > paymentTimes_
Rate fixedRate_
bool payer_
Real multiplier_
Size lastIndex_
Size currentIndex_
Detailed Description
Definition at line 29 of file multistepswap.hpp.
Constructor & Destructor Documentation
QuantLib::MultiStepSwap::MultiStepSwap (const std::vector< Time > & rateTimes, const std::vector< Real > & fixedAccruals, const std::vector< Real > & floatingAccruals, const std::vector< Time > & paymentTimes, Rate fixedRate, bool payer = true)
Definition at line 26 of file multistepswap.cpp.
References QuantLib::checkIncreasingTimes().
Referenced by clone().
    : MultiProductMultiStep(rateTimes),
      fixedAccruals_(fixedAccruals), floatingAccruals_(floatingAccruals),
      paymentTimes_(paymentTimes), fixedRate_(fixedRate), payer_(payer),
      multiplier_(payer ? 1.0 : -1.0), lastIndex_(rateTimes.size()-1) {
        checkIncreasingTimes(paymentTimes);
    }
Member Function Documentation
std::auto_ptr< MarketModelMultiProduct > QuantLib::MultiStepSwap::clone () const [virtual]
returns a newly-allocated copy of itself
Implements QuantLib::MarketModelMultiProduct.
Definition at line 62 of file multistepswap.cpp.
References MultiStepSwap().
{
        return std::auto_ptr<MarketModelMultiProduct>(
                                                 new MultiStepSwap(*this));
    }
Size QuantLib::MultiStepSwap::maxNumberOfCashFlowsPerProductPerStep () const [inline, virtual]
Implements QuantLib::MarketModelMultiProduct.
Definition at line 73 of file multistepswap.hpp.
{
        return 2;
    }
bool QuantLib::MultiStepSwap::nextTimeStep (const CurveState & currentState, std::vector< Size > & numberCashFlowsThisStep, std::vector< std::vector< CashFlow > > & cashFlowsGenerated) [virtual]
return value indicates whether path is finished, TRUE means done
Implements QuantLib::MarketModelMultiProduct.
Definition at line 39 of file multistepswap.cpp.
References currentIndex_, fixedAccruals_, fixedRate_, floatingAccruals_, QuantLib::CurveState::forwardRate(), lastIndex_, and multiplier_.
    {
        Rate liborRate = currentState.forwardRate(currentIndex_);
        genCashFlows[0][0].timeIndex = currentIndex_;
        genCashFlows[0][0].amount =
            -multiplier_*fixedRate_*fixedAccruals_[currentIndex_];
        genCashFlows[0][1].timeIndex = currentIndex_;
        genCashFlows[0][1].amount =
            multiplier_*liborRate*floatingAccruals_[currentIndex_];
        numberCashFlowsThisStep[0] = 2;
        ++currentIndex_;
        return (currentIndex_ == lastIndex_);
    }
Size QuantLib::MultiStepSwap::numberOfProducts () const [inline, virtual]
Implements QuantLib::MarketModelMultiProduct.
Definition at line 68 of file multistepswap.hpp.
{
        return 1;
    }
std::vector< Time > QuantLib::MultiStepSwap::possibleCashFlowTimes () const [inline, virtual]
Implements QuantLib::MarketModelMultiProduct.
Definition at line 64 of file multistepswap.hpp.
References paymentTimes_.
{
        return paymentTimes_;
    }
void QuantLib::MultiStepSwap::reset () [inline, virtual]
during simulation put product at start of path
Implements QuantLib::MarketModelMultiProduct.
Definition at line 77 of file multistepswap.hpp.
References currentIndex_.
{
       currentIndex_=0;
    }
Member Data Documentation
Size QuantLib::MultiStepSwap::currentIndex_ [private]
Definition at line 57 of file multistepswap.hpp.
Referenced by nextTimeStep(), and reset().
std::vector<Real> QuantLib::MultiStepSwap::fixedAccruals_ [private]
Definition at line 50 of file multistepswap.hpp.
Referenced by nextTimeStep().
Rate QuantLib::MultiStepSwap::fixedRate_ [private]
Definition at line 52 of file multistepswap.hpp.
Referenced by nextTimeStep().
std::vector<Real> QuantLib::MultiStepSwap::floatingAccruals_ [private]
Definition at line 50 of file multistepswap.hpp.
Referenced by nextTimeStep().
Size QuantLib::MultiStepSwap::lastIndex_ [private]
Definition at line 55 of file multistepswap.hpp.
Referenced by nextTimeStep().
Real QuantLib::MultiStepSwap::multiplier_ [private]
Definition at line 54 of file multistepswap.hpp.
Referenced by nextTimeStep().
bool QuantLib::MultiStepSwap::payer_ [private]
Definition at line 53 of file multistepswap.hpp.
std::vector<Time> QuantLib::MultiStepSwap::paymentTimes_ [private]
Definition at line 51 of file multistepswap.hpp.
Referenced by possibleCashFlowTimes().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/products/multistep/multistepswap.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/products/multistep/multistepswap.cpp