QuantLib: QuantLib::MultiProductMultiStep Class Reference
QuantLib::MultiProductMultiStep Class Reference
Multiple-step market-model product.
#include <multiproductmultistep.hpp>
Public Member Functions
MultiProductMultiStep (const std::vector< Time > &rateTimes)
MarketModelMultiProduct interface
std::vector< Size > suggestedNumeraires () const
const EvolutionDescription & evolution () const
Protected Attributes
std::vector< Time > rateTimes_
EvolutionDescription evolution_
Detailed Description
Multiple-step market-model product.
This is the abstract base class that encapsulates the notion of a MarketModelMultiProduct which can be evaluated in a more than one step (aka Rebonato's long jump).
Definition at line 34 of file multiproductmultistep.hpp.
Constructor & Destructor Documentation
QuantLib::MultiProductMultiStep::MultiProductMultiStep (const std::vector< Time > & rateTimes)
Definition at line 25 of file multiproductmultistep.cpp.
References evolution_, QL_REQUIRE, and rateTimes_.
    : rateTimes_(rateTimes) {
        QL_REQUIRE(rateTimes_.size()>1,
                   "Rate times must contain at least two values");
        Size n = rateTimes_.size()-1;
        std::vector<Time> evolutionTimes(n);
        std::vector<std::pair<Size,Size> > relevanceRates(n);
        for (Size i=0; i<n; ++i) {
            evolutionTimes[i] = rateTimes_[i];
            relevanceRates[i] = std::make_pair(i, i+1);
        }
        evolution_ = EvolutionDescription(rateTimes_, evolutionTimes,
                                          relevanceRates);
    }
Member Function Documentation
const EvolutionDescription & QuantLib::MultiProductMultiStep::evolution () const [virtual]
Implements QuantLib::MarketModelMultiProduct.
Reimplemented in QuantLib::ExerciseAdapter.
Definition at line 42 of file multiproductmultistep.cpp.
References evolution_.
Referenced by SwapForwardMappingsTest::testForwardCoterminalMappings(), MarketModelTest::testGreeks(), MarketModelTest::testPathwiseMarketVegas(), MarketModelTest::testPathwiseVegas(), MarketModelTest::testPeriodAdapter(), and SwapForwardMappingsTest::testSwaptionImpliedVolatility().
{
        return evolution_;
    }
std::vector< Size > QuantLib::MultiProductMultiStep::suggestedNumeraires () const [virtual]
Implements QuantLib::MarketModelMultiProduct.
Definition at line 46 of file multiproductmultistep.cpp.
References rateTimes_.
Referenced by MarketModelTest::testPeriodAdapter().
    {
        Size n = rateTimes_.size()-1;
        std::vector<Size> numeraires(n);
        // MoneyMarketPlus(1)
        for (Size i=0; i<n; ++i)
            numeraires[i]=i+1;
        return numeraires;
    }
Member Data Documentation
EvolutionDescription QuantLib::MultiProductMultiStep::evolution_ [protected]
Definition at line 44 of file multiproductmultistep.hpp.
Referenced by evolution(), and MultiProductMultiStep().
std::vector<Time> QuantLib::MultiProductMultiStep::rateTimes_ [protected]
Definition at line 43 of file multiproductmultistep.hpp.
Referenced by MultiProductMultiStep(), QuantLib::MultiStepPeriodCapletSwaptions::nextTimeStep(), and suggestedNumeraires().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/products/multiproductmultistep.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/products/multiproductmultistep.cpp