QuantLib: QuantLib::IborIndex Class Reference
QuantLib::IborIndex Class Reference
base class for Inter-Bank-Offered-Rate indexes (e.g. Libor, etc.)
#include <iborindex.hpp>
Public Member Functions
IborIndex (const std::string &familyName, const Period &tenor, Natural settlementDays, const Currency &currency, const Calendar &fixingCalendar, BusinessDayConvention convention, bool endOfMonth, const DayCounter &dayCounter, const Handle< YieldTermStructure > &h=Handle< YieldTermStructure >())
InterestRateIndex interface
Date maturityDate (const Date &valueDate) const
Rate forecastFixing (const Date &fixingDate) const
It can be overridden to implement particular conventions.
Inspectors
BusinessDayConvention businessDayConvention () const
bool endOfMonth () const
Handle< YieldTermStructure > forwardingTermStructure () const
the curve used to forecast fixings
Other methods
virtual boost::shared_ptr
< IborIndex > clone (const Handle< YieldTermStructure > &forwarding) const
returns a copy of itself linked to a different forwarding curve
Protected Attributes
BusinessDayConvention convention_
Handle< YieldTermStructure > termStructure_
bool endOfMonth_
Private Member Functions
Rate forecastFixing (const Date &valueDate, const Date &endDate, Time t) const
Friends
class IborCoupon
Detailed Description
base class for Inter-Bank-Offered-Rate indexes (e.g. Libor, etc.)
Definition at line 35 of file iborindex.hpp.
Constructor & Destructor Documentation
QuantLib::IborIndex::IborIndex (const std::string & familyName, const Period & tenor, Natural settlementDays, const Currency & currency, const Calendar & fixingCalendar, BusinessDayConvention convention, bool endOfMonth, const DayCounter & dayCounter, const Handle< YieldTermStructure > & h = Handle<YieldTermStructure>())
Definition at line 27 of file iborindex.cpp.
References QuantLib::Observer::registerWith(), and termStructure_.
Referenced by clone().
    : InterestRateIndex(familyName, tenor, settlementDays, currency,
                        fixingCalendar, dayCounter),
      convention_(convention), termStructure_(h), endOfMonth_(endOfMonth) {
        registerWith(termStructure_);
      }
Member Function Documentation
BusinessDayConvention QuantLib::IborIndex::businessDayConvention () const
Definition at line 61 of file iborindex.cpp.
References convention_.
Referenced by clone(), and anonymous_namespace{piecewiseyieldcurve.cpp}::CommonVars::CommonVars().
{
        return convention_;
    }
boost::shared_ptr< IborIndex > QuantLib::IborIndex::clone (const Handle< YieldTermStructure > & forwarding) const [virtual]
returns a copy of itself linked to a different forwarding curve
Reimplemented in QuantLib::OvernightIndex, and QuantLib::Libor.
Definition at line 69 of file iborindex.cpp.
References businessDayConvention(), QuantLib::InterestRateIndex::currency(), QuantLib::InterestRateIndex::dayCounter(), endOfMonth(), QuantLib::InterestRateIndex::familyName(), QuantLib::InterestRateIndex::fixingCalendar(), QuantLib::InterestRateIndex::fixingDays(), IborIndex(), and QuantLib::InterestRateIndex::tenor().
{
        return boost::shared_ptr<IborIndex>(
                                        new IborIndex(familyName(),
                                                      tenor(),
                                                      fixingDays(),
                                                      currency(),
                                                      fixingCalendar(),
                                                      businessDayConvention(),
                                                      endOfMonth(),
                                                      dayCounter(),
                                                      h));
    }
bool QuantLib::IborIndex::endOfMonth () const [inline]
Definition at line 55 of file iborindex.hpp.
References endOfMonth_.
Referenced by clone(), anonymous_namespace{piecewiseyieldcurve.cpp}::CommonVars::CommonVars(), QuantLib::EURLibor::maturityDate(), and QuantLib::Libor::maturityDate().
{ return endOfMonth_; }
Rate QuantLib::IborIndex::forecastFixing (const Date & fixingDate) const [virtual]
It can be overridden to implement particular conventions.
Implements QuantLib::InterestRateIndex.
Reimplemented in QuantLib::ProxyIbor.
Definition at line 42 of file iborindex.cpp.
References QuantLib::InterestRateIndex::dayCounter_, maturityDate(), QuantLib::DayCounter::name(), QL_REQUIRE, anonymous_namespace{quantlibbenchmark.cpp}::t, QuantLib::InterestRateIndex::valueDate(), and QuantLib::DayCounter::yearFraction().
{
        Date d1 = valueDate(fixingDate);
        Date d2 = maturityDate(d1);
        Time t = dayCounter_.yearFraction(d1, d2);
        QL_REQUIRE(t>0.0,
                   "\n cannot calculate forward rate between " <<
                   d1 << " and " << d2 <<
                   ":\n non positive time (" << t <<
                   ") using " << dayCounter_.name() << " daycounter");
        return forecastFixing(d1, d2, t);
    }
Rate QuantLib::IborIndex::forecastFixing (const Date & valueDate, const Date & endDate, Time t) const [inline, private]
Definition at line 106 of file iborindex.hpp.
References QuantLib::Handle< T >::empty(), QuantLib::InterestRateIndex::name(), QL_REQUIRE, anonymous_namespace{quantlibbenchmark.cpp}::t, and termStructure_.
{
        QL_REQUIRE(!termStructure_.empty(),
                   "null term structure set to this instance of " << name());
        DiscountFactor disc1 = termStructure_->discount(d1);
        DiscountFactor disc2 = termStructure_->discount(d2);
        return (disc1/disc2 - 1.0) / t;
    }
Handle< YieldTermStructure > QuantLib::IborIndex::forwardingTermStructure () const
the curve used to forecast fixings
Definition at line 65 of file iborindex.cpp.
References termStructure_.
{
        return termStructure_;
    }
Date QuantLib::IborIndex::maturityDate (const Date & valueDate) const [virtual]
Implements QuantLib::InterestRateIndex.
Reimplemented in QuantLib::Libor, and QuantLib::EURLibor.
Definition at line 54 of file iborindex.cpp.
References QuantLib::Calendar::advance(), convention_, endOfMonth_, QuantLib::InterestRateIndex::fixingCalendar(), and QuantLib::InterestRateIndex::tenor_.
Referenced by forecastFixing().
{
        return fixingCalendar().advance(valueDate,
                                        tenor_,
                                        convention_,
                                        endOfMonth_);
    }
Friends And Related Function Documentation
friend class IborCoupon [friend]
Definition at line 85 of file iborindex.hpp.
Member Data Documentation
BusinessDayConvention QuantLib::IborIndex::convention_ [protected]
Definition at line 66 of file iborindex.hpp.
Referenced by businessDayConvention(), maturityDate(), QuantLib::EURLibor::maturityDate(), and QuantLib::Libor::maturityDate().
bool QuantLib::IborIndex::endOfMonth_ [protected]
Definition at line 68 of file iborindex.hpp.
Referenced by endOfMonth(), and maturityDate().
Handle<YieldTermStructure> QuantLib::IborIndex::termStructure_ [protected]
Definition at line 67 of file iborindex.hpp.
Referenced by forecastFixing(), forwardingTermStructure(), and IborIndex().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/indexes/iborindex.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/indexes/iborindex.cpp