QuantLib: QuantLib::ModifiedCraigSneydScheme Class Reference
QuantLib::ModifiedCraigSneydScheme Class Reference
modified Craig-Sneyd scheme
#include <modifiedcraigsneydscheme.hpp>
Public Types
typedef OperatorTraits
< FdmLinearOp > traits
typedef traits::operator_type operator_type
typedef traits::array_type array_type
typedef traits::bc_set bc_set
typedef traits::condition_type condition_type
Public Member Functions
ModifiedCraigSneydScheme (Real theta, Real mu, const boost::shared_ptr< FdmLinearOpComposite > &map, const bc_set &bcSet=bc_set())
void step (array_type &a, Time t)
void setStep (Time dt)
Protected Attributes
Time dt_
const Real theta_
const Real mu_
const boost::shared_ptr
< FdmLinearOpComposite > & map_
const BoundaryConditionSchemeHelper bcSet_
Detailed Description
modified Craig-Sneyd scheme
References: K. J. in ’t Hout and S. Foulon, ADI finite difference schemes for option pricing in the Heston model with correlation, http://arxiv.org/pdf/0811.3427
Definition at line 40 of file modifiedcraigsneydscheme.hpp.
Member Typedef Documentation
typedef traits::array_type QuantLib::ModifiedCraigSneydScheme::array_type
Definition at line 45 of file modifiedcraigsneydscheme.hpp.
typedef traits::bc_set QuantLib::ModifiedCraigSneydScheme::bc_set
Definition at line 46 of file modifiedcraigsneydscheme.hpp.
typedef traits::condition_type QuantLib::ModifiedCraigSneydScheme::condition_type
Definition at line 47 of file modifiedcraigsneydscheme.hpp.
typedef traits::operator_type QuantLib::ModifiedCraigSneydScheme::operator_type
Definition at line 44 of file modifiedcraigsneydscheme.hpp.
typedef OperatorTraits<FdmLinearOp> QuantLib::ModifiedCraigSneydScheme::traits
Definition at line 43 of file modifiedcraigsneydscheme.hpp.
Constructor & Destructor Documentation
QuantLib::ModifiedCraigSneydScheme::ModifiedCraigSneydScheme (Real theta, Real mu, const boost::shared_ptr< FdmLinearOpComposite > & map, const bc_set & bcSet = bc_set())
Definition at line 24 of file modifiedcraigsneydscheme.cpp.
        : dt_(Null<Real>()),
        theta_(theta),
        mu_   (mu),
        map_  (map),
        bcSet_(bcSet) {
    }
Member Function Documentation
void QuantLib::ModifiedCraigSneydScheme::setStep (Time dt)
Definition at line 65 of file modifiedcraigsneydscheme.cpp.
References QuantLib::anonymous_namespace{yieldtermstructure.cpp}::dt, and dt_.
{
        dt_=dt;
    }
void QuantLib::ModifiedCraigSneydScheme::step (array_type & a, Time t)
Definition at line 35 of file modifiedcraigsneydscheme.cpp.
References QuantLib::BoundaryConditionSchemeHelper::applyAfterApplying(), QuantLib::BoundaryConditionSchemeHelper::applyAfterSolving(), QuantLib::BoundaryConditionSchemeHelper::applyBeforeApplying(), bcSet_, dt_, map_, mu_, QL_REQUIRE, QuantLib::BoundaryConditionSchemeHelper::setTime(), and theta_.
{
        QL_REQUIRE(t-dt_ > -1e-8, "a step towards negative time given");
        map_->setTime(std::max(0.0, t-dt_), t);
        bcSet_.setTime(std::max(0.0, t-dt_));
        bcSet_.applyBeforeApplying(*map_);
        Array y = a + dt_*map_->apply(a);
        bcSet_.applyAfterApplying(y);
        Array y0 = y;
        for (Size i=0; i < map_->size(); ++i) {
            Array rhs = y - theta_*dt_*map_->apply_direction(i, a);
            y = map_->solve_splitting(i, rhs, -theta_*dt_);
        }
        bcSet_.applyBeforeApplying(*map_);
        Array yt =  y0 + mu_*dt_*map_->apply_mixed(y-a)
                  +(0.5-mu_)*dt_*map_->apply(y-a);;
        bcSet_.applyAfterApplying(yt);
        for (Size i=0; i < map_->size(); ++i) {
            Array rhs = yt - theta_*dt_*map_->apply_direction(i, a);
            yt = map_->solve_splitting(i, rhs, -theta_*dt_);
        }
        bcSet_.applyAfterSolving(yt);
        a = yt;
    }
Member Data Documentation
const BoundaryConditionSchemeHelper QuantLib::ModifiedCraigSneydScheme::bcSet_ [protected]
Definition at line 62 of file modifiedcraigsneydscheme.hpp.
Referenced by step().
Time QuantLib::ModifiedCraigSneydScheme::dt_ [protected]
Definition at line 58 of file modifiedcraigsneydscheme.hpp.
Referenced by setStep(), and step().
const boost::shared_ptr<FdmLinearOpComposite>& QuantLib::ModifiedCraigSneydScheme::map_ [protected]
Definition at line 61 of file modifiedcraigsneydscheme.hpp.
Referenced by step().
const Real QuantLib::ModifiedCraigSneydScheme::mu_ [protected]
Definition at line 60 of file modifiedcraigsneydscheme.hpp.
Referenced by step().
const Real QuantLib::ModifiedCraigSneydScheme::theta_ [protected]
Definition at line 59 of file modifiedcraigsneydscheme.hpp.
Referenced by step().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/schemes/modifiedcraigsneydscheme.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/schemes/modifiedcraigsneydscheme.cpp