QuantLib: QuantLib::DefaultDensityStructure Class Reference
QuantLib::DefaultDensityStructure Class Reference
Default-density term structure.
#include <defaultdensitystructure.hpp>
Public Member Functions
Constructors
See the TermStructure documentation for issues regarding constructors.
DefaultDensityStructure (const DayCounter &dayCounter=DayCounter(), const std::vector< Handle< Quote > > &jumps=std::vector< Handle< Quote > >(), const std::vector< Date > &jumpDates=std::vector< Date >())
DefaultDensityStructure (const Date &referenceDate, const Calendar &cal=Calendar(), const DayCounter &dayCounter=DayCounter(), const std::vector< Handle< Quote > > &jumps=std::vector< Handle< Quote > >(), const std::vector< Date > &jumpDates=std::vector< Date >())
DefaultDensityStructure (Natural settlementDays, const Calendar &cal, const DayCounter &dayCounter=DayCounter(), const std::vector< Handle< Quote > > &jumps=std::vector< Handle< Quote > >(), const std::vector< Date > &jumpDates=std::vector< Date >())
Protected Member Functions
DefaultProbabilityTermStructure implementation
Probability survivalProbabilityImpl (Time) const
survival probability calculation
Detailed Description
Default-density term structure.
This abstract class acts as an adapter to DefaultProbabilityTermStructure allowing the programmer to implement only the defaultDensityImpl(Time) method in derived classes.
Survival/default probabilities and hazard rates are calculated from default densities.
Definition at line 43 of file defaultdensitystructure.hpp.
Constructor & Destructor Documentation
QuantLib::DefaultDensityStructure::DefaultDensityStructure (const DayCounter & dayCounter = DayCounter(), const std::vector< Handle< Quote > > & jumps = std::vector<Handle<Quote> >(), const std::vector< Date > & jumpDates = std::vector<Date>())
Definition at line 51 of file defaultdensitystructure.cpp.
    : DefaultProbabilityTermStructure(dc, jumps, jumpDates) {}
QuantLib::DefaultDensityStructure::DefaultDensityStructure (const Date & referenceDate, const Calendar & cal = Calendar(), const DayCounter & dayCounter = DayCounter(), const std::vector< Handle< Quote > > & jumps = std::vector<Handle<Quote> >(), const std::vector< Date > & jumpDates = std::vector<Date>())
Definition at line 57 of file defaultdensitystructure.cpp.
    : DefaultProbabilityTermStructure(refDate, cal, dc, jumps, jumpDates) {}
QuantLib::DefaultDensityStructure::DefaultDensityStructure (Natural settlementDays, const Calendar & cal, const DayCounter & dayCounter = DayCounter(), const std::vector< Handle< Quote > > & jumps = std::vector<Handle<Quote> >(), const std::vector< Date > & jumpDates = std::vector<Date>())
Definition at line 65 of file defaultdensitystructure.cpp.
    : DefaultProbabilityTermStructure(settlDays, cal, dc, jumps, jumpDates) {}
Member Function Documentation
Probability QuantLib::DefaultDensityStructure::survivalProbabilityImpl (Time t) const [protected, virtual]
survival probability calculation
implemented in terms of the default density \(p(t) \) as
\[ S(t) = 1 - \int_0^t p(\tau) d\tau. \]
Warning:
This default implementation uses numerical integration, which might be inefficient and inaccurate. Derived classes should override it if a more efficient implementation is available.
Implements QuantLib::DefaultProbabilityTermStructure.
Reimplemented in QuantLib::InterpolatedDefaultDensityCurve< Interpolator >.
Definition at line 73 of file defaultdensitystructure.cpp.
References QuantLib::DefaultProbabilityTermStructure::defaultDensityImpl(), anonymous_namespace{interpolations.cpp}::f(), and QuantLib::anonymous_namespace{defaultdensitystructure.cpp}::remap().
{
        static GaussChebyshevIntegration integral(48);
        // this stores the address of the method to integrate (so that
        // we don't have to insert its full expression inside the
        // integral below--it's long enough already)
        Real (DefaultDensityStructure::*f)(Time) const =
            &DefaultDensityStructure::defaultDensityImpl;
        // the Gauss-Chebyshev quadratures integrate over [-1,1],
        // hence the remapping (and the Jacobian term t/2)
        Probability P = 1.0 - integral(remap(bind(f,this,_1), t)) * t/2.0;
        //QL_ENSURE(P >= 0.0, "negative survival probability");
        return std::max<Real>(P, 0.0);
    }
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/credit/defaultdensitystructure.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/credit/defaultdensitystructure.cpp