QuantLib: QuantLib::PrimeNumbers Class Reference
QuantLib::PrimeNumbers Class Reference
Prime numbers calculator.
#include <primenumbers.hpp>
Static Public Member Functions
static BigNatural get (Size absoluteIndex)
Get and store one after another.
Private Member Functions
PrimeNumbers ()
Static Private Member Functions
static BigNatural nextPrimeNumber ()
Static Private Attributes
static std::vector< BigNatural > primeNumbers_
Detailed Description
Prime numbers calculator.
Taken from "Monte Carlo Methods in Finance", by Peter Jäckel
Definition at line 45 of file primenumbers.hpp.
Constructor & Destructor Documentation
QuantLib::PrimeNumbers::PrimeNumbers () [inline, private]
Definition at line 50 of file primenumbers.hpp.
{}
Member Function Documentation
BigNatural QuantLib::PrimeNumbers::get (Size absoluteIndex) [static]
Get and store one after another.
Definition at line 47 of file primenumbers.cpp.
References QuantLib::anonymous_namespace{primenumbers.cpp}::firstPrimes, nextPrimeNumber(), and primeNumbers_.
Referenced by QuantLib::FaureRsg::FaureRsg().
{
        if (primeNumbers_.empty()) {
            Size n = sizeof(firstPrimes)/sizeof(firstPrimes[0]);
            primeNumbers_.insert(primeNumbers_.end(),
                                 firstPrimes, firstPrimes+n);
        }
        while (primeNumbers_.size()<=absoluteIndex)
            nextPrimeNumber();
        return primeNumbers_[absoluteIndex];
    }
BigNatural QuantLib::PrimeNumbers::nextPrimeNumber () [static, private]
Definition at line 58 of file primenumbers.cpp.
References primeNumbers_.
Referenced by get().
{
        BigNatural p, n, m = primeNumbers_.back();
        do {
            // skip the even numbers
            m += 2;
            n = static_cast<BigNatural>(std::sqrt(Real(m)));
            // i=1 since the even numbers have already been skipped
            Size i = 1;
            do {
                p = primeNumbers_[i];
                ++i;
            } while ( m%p && p<=n );
        } while ( p<=n );
        primeNumbers_.push_back(m);
        return m;
    }
Member Data Documentation
std::vector< BigNatural > QuantLib::PrimeNumbers::primeNumbers_ [static, private]
Definition at line 52 of file primenumbers.hpp.
Referenced by get(), and nextPrimeNumber().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/primenumbers.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/math/primenumbers.cpp