QuantLib: QuantLib::CappedFlooredCoupon Class Reference
QuantLib::CappedFlooredCoupon Class Reference
Capped and/or floored floating-rate coupon.
#include <capflooredcoupon.hpp>
Public Member Functions
CappedFlooredCoupon (const boost::shared_ptr< FloatingRateCoupon > &underlying, Rate cap=Null< Rate >(), Rate floor=Null< Rate >())
Rate cap () const
cap
Rate floor () const
floor
Rate effectiveCap () const
effective cap of fixing
Rate effectiveFloor () const
effective floor of fixing
Coupon interface
Rate rate () const
accrued rate
Rate convexityAdjustment () const
convexity adjustment
Observer interface
void update ()
Visitability
boost::shared_ptr
< FloatingRateCoupon > underlying_
bool isCapped_
bool isFloored_
Rate cap_
Rate floor_
virtual void accept (AcyclicVisitor &)
bool isCapped () const
bool isFloored () const
void setPricer (const boost::shared_ptr< FloatingRateCouponPricer > &pricer)
Detailed Description
Capped and/or floored floating-rate coupon.
The payoff \(P \) of a capped floating-rate coupon is:
\[ P = N \times T \times \min(a L + b, C). \]
The payoff of a floored floating-rate coupon is:
\[ P = N \times T \times \max(a L + b, F). \]
The payoff of a collared floating-rate coupon is:
\[ P = N \times T \times \min(\max(a L + b, F), C). \]
where \(N \) is the notional, \(T \) is the accrual time, \(L \) is the floating rate, \(a \) is its gearing, \(b \) is the spread, and \(C \) and \(F \) the strikes.
They can be decomposed in the following manner. Decomposition of a capped floating rate coupon:
\[ R = \min(a L + b, C) = (a L + b) + \min(C - b - \xi |a| L, 0) \]
where \(\xi = sgn(a) \). Then:
\[ R = (a L + b) + |a| \min(\frac{C - b}{|a|} - \xi L, 0) \]
Definition at line 57 of file capflooredcoupon.hpp.
Constructor & Destructor Documentation
QuantLib::CappedFlooredCoupon::CappedFlooredCoupon (const boost::shared_ptr< FloatingRateCoupon > & underlying, Rate cap = Null<Rate>(), Rate floor = Null<Rate>())
Definition at line 27 of file capflooredcoupon.cpp.
References cap(), cap_, floor(), floor_, QuantLib::FloatingRateCoupon::gearing_, isCapped_, isFloored_, QL_REQUIRE, and QuantLib::Observer::registerWith().
    : FloatingRateCoupon(underlying->date(),
                         underlying->nominal(),
                         underlying->accrualStartDate(),
                         underlying->accrualEndDate(),
                         underlying->fixingDays(),
                         underlying->index(),
                         underlying->gearing(),
                         underlying->spread(),
                         underlying->referencePeriodStart(),
                         underlying->referencePeriodEnd(),
                         underlying->dayCounter(),
                         underlying->isInArrears()),
      underlying_(underlying),
      isCapped_(false), isFloored_(false) {
        if (gearing_ > 0) {
            if (cap != Null<Rate>()) {
                isCapped_ = true;
                cap_ = cap;
            }
            if (floor != Null<Rate>()) {
                floor_ = floor;
                isFloored_ = true;
            }
        } else {
              if (cap != Null<Rate>()){
                floor_ = cap;
                isFloored_ = true;
              }
              if (floor != Null<Rate>()){
                isCapped_ = true;
                cap_ = floor;
              }
        }
        if (isCapped_ && isFloored_) {
            QL_REQUIRE(cap >= floor,
                       "cap level (" << cap <<
                       ") less than floor level (" << floor << ")");
        }
        registerWith(underlying);
    }
Member Function Documentation
void QuantLib::CappedFlooredCoupon::accept (AcyclicVisitor & v) [virtual]
Reimplemented from QuantLib::FloatingRateCoupon.
Reimplemented in QuantLib::CappedFlooredCmsCoupon, and QuantLib::CappedFlooredIborCoupon.
Definition at line 130 of file capflooredcoupon.cpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Visitor< T >::visit().
{
        typedef FloatingRateCoupon super;
        Visitor<CappedFlooredCoupon>* v1 =
            dynamic_cast<Visitor<CappedFlooredCoupon>*>(&v);
        if (v1 != 0)
            v1->visit(*this);
        else
            super::accept(v);
    }
Rate QuantLib::CappedFlooredCoupon::cap () const
cap
Definition at line 96 of file capflooredcoupon.cpp.
References cap_, floor_, QuantLib::FloatingRateCoupon::gearing_, isCapped_, and isFloored_.
Referenced by CappedFlooredCoupon().
{
        if ( (gearing_ > 0) && isCapped_)
                return cap_;
        if ( (gearing_ < 0) && isFloored_)
            return floor_;
        return Null<Rate>();
    }
Rate QuantLib::CappedFlooredCoupon::convexityAdjustment () const [virtual]
convexity adjustment
Reimplemented from QuantLib::FloatingRateCoupon.
Definition at line 92 of file capflooredcoupon.cpp.
References underlying_.
{
        return underlying_->convexityAdjustment();
    }
Rate QuantLib::CappedFlooredCoupon::effectiveCap () const
effective cap of fixing
Definition at line 112 of file capflooredcoupon.cpp.
References cap_, QuantLib::FloatingRateCoupon::gearing(), isCapped_, and QuantLib::FloatingRateCoupon::spread().
Referenced by rate().
{
        if (isCapped_)
            return (cap_ - spread())/gearing();
        else
            return Null<Rate>();
    }
Rate QuantLib::CappedFlooredCoupon::effectiveFloor () const
effective floor of fixing
Definition at line 119 of file capflooredcoupon.cpp.
References floor_, QuantLib::FloatingRateCoupon::gearing(), isFloored_, and QuantLib::FloatingRateCoupon::spread().
Referenced by rate().
{
        if (isFloored_)
            return (floor_ - spread())/gearing();
        else
            return Null<Rate>();
    }
Rate QuantLib::CappedFlooredCoupon::floor () const
floor
Definition at line 104 of file capflooredcoupon.cpp.
References cap_, floor_, QuantLib::FloatingRateCoupon::gearing_, isCapped_, and isFloored_.
Referenced by CappedFlooredCoupon().
{
        if ( (gearing_ > 0) && isFloored_)
            return floor_;
        if ( (gearing_ < 0) && isCapped_)
            return cap_;
        return Null<Rate>();
    }
bool QuantLib::CappedFlooredCoupon::isCapped () const [inline]
Definition at line 85 of file capflooredcoupon.hpp.
References isCapped_.
{return isCapped_;}
bool QuantLib::CappedFlooredCoupon::isFloored () const [inline]
Definition at line 86 of file capflooredcoupon.hpp.
References isFloored_.
{return isFloored_;}
Rate QuantLib::CappedFlooredCoupon::rate () const [virtual]
accrued rate
Reimplemented from QuantLib::FloatingRateCoupon.
Definition at line 80 of file capflooredcoupon.cpp.
References effectiveCap(), effectiveFloor(), isCapped_, isFloored_, QL_REQUIRE, and underlying_.
Referenced by QuantLib::DigitalCoupon::callOptionRate(), and QuantLib::DigitalCoupon::putOptionRate().
{
        QL_REQUIRE(underlying_->pricer(), "pricer not set");
        Rate swapletRate = underlying_->rate();
        Rate floorletRate = 0.;
        if(isFloored_)
            floorletRate = underlying_->pricer()->floorletRate(effectiveFloor());
        Rate capletRate = 0.;
        if(isCapped_)
            capletRate = underlying_->pricer()->capletRate(effectiveCap());
        return swapletRate + floorletRate - capletRate;
    }
void QuantLib::CappedFlooredCoupon::setPricer (const boost::shared_ptr< FloatingRateCouponPricer > & pricer)
Reimplemented from QuantLib::FloatingRateCoupon.
Definition at line 74 of file capflooredcoupon.cpp.
References underlying_.
Referenced by CmsTest::testFairRate(), and QuantLib::anonymous_namespace{couponpricer.cpp}::PricerSetter::visit().
{
        FloatingRateCoupon::setPricer(pricer);
        underlying_->setPricer(pricer);
    }
void QuantLib::CappedFlooredCoupon::update () [virtual]
This method must be implemented in derived classes. An instance of Observer does not call this method directly: instead, it will be called by the observables the instance registered with when they need to notify any changes.
Reimplemented from QuantLib::FloatingRateCoupon.
Definition at line 126 of file capflooredcoupon.cpp.
References QuantLib::Observable::notifyObservers().
{
        notifyObservers();
    }
Member Data Documentation
Rate QuantLib::CappedFlooredCoupon::cap_ [protected]
Definition at line 95 of file capflooredcoupon.hpp.
Referenced by cap(), CappedFlooredCoupon(), effectiveCap(), and floor().
Rate QuantLib::CappedFlooredCoupon::floor_ [protected]
Definition at line 95 of file capflooredcoupon.hpp.
Referenced by cap(), CappedFlooredCoupon(), effectiveFloor(), and floor().
bool QuantLib::CappedFlooredCoupon::isCapped_ [protected]
Definition at line 94 of file capflooredcoupon.hpp.
Referenced by cap(), CappedFlooredCoupon(), effectiveCap(), floor(), isCapped(), and rate().
bool QuantLib::CappedFlooredCoupon::isFloored_ [protected]
Definition at line 94 of file capflooredcoupon.hpp.
Referenced by cap(), CappedFlooredCoupon(), effectiveFloor(), floor(), isFloored(), and rate().
boost::shared_ptr<FloatingRateCoupon> QuantLib::CappedFlooredCoupon::underlying_ [protected]
Definition at line 93 of file capflooredcoupon.hpp.
Referenced by convexityAdjustment(), rate(), and setPricer().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/capflooredcoupon.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/capflooredcoupon.cpp