QuantLib: QuantLib::ExtendedCoxRossRubinstein Class Reference
QuantLib::ExtendedCoxRossRubinstein Class Reference
Cox-Ross-Rubinstein (multiplicative) equal jumps binomial tree.
#include <extendedbinomialtree.hpp>
Public Member Functions
ExtendedCoxRossRubinstein (const boost::shared_ptr< StochasticProcess1D > &, Time end, Size steps, Real strike)
Protected Member Functions
Real dxStep (Time stepTime) const
Real probUp (Time stepTime) const
Detailed Description
Cox-Ross-Rubinstein (multiplicative) equal jumps binomial tree.
Definition at line 150 of file extendedbinomialtree.hpp.
Constructor & Destructor Documentation
QuantLib::ExtendedCoxRossRubinstein::ExtendedCoxRossRubinstein (const boost::shared_ptr< StochasticProcess1D > & process, Time end, Size steps, Real strike)
Definition at line 43 of file extendedbinomialtree.cpp.
References QuantLib::ExtendedBinomialTree< ExtendedCoxRossRubinstein >::driftStep(), QuantLib::ExtendedBinomialTree< ExtendedCoxRossRubinstein >::dt_, QuantLib::ExtendedEqualJumpsBinomialTree< ExtendedCoxRossRubinstein >::dx_, QuantLib::ExtendedEqualJumpsBinomialTree< ExtendedCoxRossRubinstein >::pd_, QuantLib::ExtendedEqualJumpsBinomialTree< ExtendedCoxRossRubinstein >::pu_, QL_REQUIRE, and QuantLib::ExtendedBinomialTree< ExtendedCoxRossRubinstein >::x0_.
    : ExtendedEqualJumpsBinomialTree<ExtendedCoxRossRubinstein>(
                                                        process, end, steps) {
        dx_ = process->stdDeviation(0.0, x0_, dt_);
        pu_ = 0.5 + 0.5*this->driftStep(0.0)/dx_;
        pd_ = 1.0 - pu_;
        QL_REQUIRE(pu_<=1.0, "negative probability");
        QL_REQUIRE(pu_>=0.0, "negative probability");
    }
Member Function Documentation
Real QuantLib::ExtendedCoxRossRubinstein::dxStep (Time stepTime) const [protected, virtual]
Implements QuantLib::ExtendedEqualJumpsBinomialTree< ExtendedCoxRossRubinstein >.
Definition at line 57 of file extendedbinomialtree.cpp.
References QuantLib::ExtendedBinomialTree< ExtendedCoxRossRubinstein >::dt_, QuantLib::ExtendedBinomialTree< ExtendedCoxRossRubinstein >::treeProcess_, and QuantLib::ExtendedBinomialTree< ExtendedCoxRossRubinstein >::x0_.
Referenced by probUp().
{
        return this->treeProcess_->stdDeviation(stepTime, x0_, dt_);
    }
Real QuantLib::ExtendedCoxRossRubinstein::probUp (Time stepTime) const [protected, virtual]
Implements QuantLib::ExtendedEqualJumpsBinomialTree< ExtendedCoxRossRubinstein >.
Definition at line 61 of file extendedbinomialtree.cpp.
References QuantLib::ExtendedBinomialTree< ExtendedCoxRossRubinstein >::driftStep(), and dxStep().
{
        return 0.5 + 0.5*this->driftStep(stepTime)/dxStep(stepTime);
    }
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/lattices/extendedbinomialtree.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/lattices/extendedbinomialtree.cpp