QuantLib: QuantLib::LazyObject Class Reference
QuantLib::LazyObject Class Reference
Framework for calculation on demand and result caching.
#include <lazyobject.hpp>
Public Member Functions
LazyObject ()
virtual ~LazyObject ()
Observer interface
void update ()
Protected Attributes
bool calculated_
bool frozen_
Calculations
These methods do not modify the structure of the object and are therefore declared as const. Data members which will be calculated on demand need to be declared as mutable.
void recalculate ()
void freeze ()
void unfreeze ()
virtual void calculate () const
virtual void performCalculations () const =0
Detailed Description
Framework for calculation on demand and result caching.
Definition at line 33 of file lazyobject.hpp.
Constructor & Destructor Documentation
QuantLib::LazyObject::LazyObject () [inline]
Definition at line 99 of file lazyobject.hpp.
    : calculated_(false), frozen_(false) {}
virtual QuantLib::LazyObject::~LazyObject () [inline, virtual]
Definition at line 37 of file lazyobject.hpp.
{}
Member Function Documentation
void QuantLib::LazyObject::calculate () const [inline, protected, virtual]
This method performs all needed calculations by calling the performCalculations method.
Warning:
Objects cache the results of the previous calculation. Such results will be returned upon later invocations of calculate. When the results depend on arguments which could change between invocations, the lazy object must register itself as observer of such objects for the calculations to be performed again when they change.
Should this method be redefined in derived classes, LazyObject::calculate() should be called in the overriding method.
Reimplemented in QuantLib::Instrument.
Definition at line 145 of file lazyobject.hpp.
References calculated_, frozen_, and performCalculations().
Referenced by QuantLib::SabrInterpolatedSmileSection::alpha(), QuantLib::OptionletStripper2::atmCapFloorPrices(), QuantLib::OptionletStripper2::atmCapFloorStrikes(), QuantLib::SabrInterpolatedSmileSection::atmLevel(), QuantLib::OptionletStripper::atmOptionletRates(), QuantLib::StrippedOptionlet::atmOptionletRates(), QuantLib::AbcdAtmVolCurve::atmVolImpl(), QuantLib::Basket::basketLGD(), QuantLib::SabrInterpolatedSmileSection::beta(), QuantLib::CmsMarket::browse(), QuantLib::OptionletStripper1::capFloorPrices(), QuantLib::OptionletStripper1::capFloorVolatilities(), QuantLib::FdmBlackScholesSolver::deltaAt(), QuantLib::FdmBatesSolver::deltaAt(), QuantLib::FdmHestonSolver::deltaAt(), QuantLib::Fdm2dBlackScholesSolver::deltaXat(), QuantLib::Fdm2dBlackScholesSolver::deltaYat(), QuantLib::SwaptionVolCube1::denseSabrParameters(), QuantLib::Fdm2DimSolver::derivativeX(), QuantLib::Fdm1DimSolver::derivativeX(), QuantLib::Fdm1DimSolver::derivativeXX(), QuantLib::Fdm2DimSolver::derivativeXX(), QuantLib::Fdm2DimSolver::derivativeXY(), QuantLib::Fdm2DimSolver::derivativeY(), QuantLib::Fdm2DimSolver::derivativeYY(), QuantLib::FlatForward::discountImpl(), QuantLib::FittedBondDiscountCurve::discountImpl(), QuantLib::RendistatoCalculator::duration(), QuantLib::RendistatoCalculator::durations(), QuantLib::SabrInterpolatedSmileSection::endCriteria(), QuantLib::RendistatoCalculator::equivalentSwap(), QuantLib::RendistatoCalculator::equivalentSwapDuration(), QuantLib::RendistatoCalculator::equivalentSwapLength(), QuantLib::RendistatoCalculator::equivalentSwapRate(), QuantLib::RendistatoCalculator::equivalentSwapYield(), QuantLib::FittedBondDiscountCurve::fitResults(), QuantLib::ForwardSwapQuote::fixingDate(), QuantLib::FdmBlackScholesSolver::gammaAt(), QuantLib::FdmBatesSolver::gammaAt(), QuantLib::FdmHestonSolver::gammaAt(), QuantLib::Fdm2dBlackScholesSolver::gammaXat(), QuantLib::Fdm2dBlackScholesSolver::gammaYat(), QuantLib::OneFactorCopula::integral(), QuantLib::Fdm2DimSolver::interpolateAt(), QuantLib::Fdm1DimSolver::interpolateAt(), QuantLib::Fdm3DimSolver::interpolateAt(), QuantLib::Basket::LGDs(), QuantLib::SwaptionVolCube1::marketVolCube(), QuantLib::AbcdAtmVolCurve::maxDate(), QuantLib::CapFloorTermVolCurve::maxDate(), QuantLib::CapFloorTermVolSurface::maxDate(), QuantLib::FittedBondDiscountCurve::maxDate(), QuantLib::SabrInterpolatedSmileSection::maxError(), QuantLib::SabrInterpolatedSmileSection::maxStrike(), QuantLib::FdmHestonSolver::meanVarianceDeltaAt(), QuantLib::FdmHestonSolver::meanVarianceGammaAt(), QuantLib::SabrInterpolatedSmileSection::minStrike(), QuantLib::SabrInterpolatedSmileSection::nu(), QuantLib::OneFactorGaussianStudentCopula::OneFactorGaussianStudentCopula(), QuantLib::OneFactorStudentCopula::OneFactorStudentCopula(), QuantLib::OneFactorStudentGaussianCopula::OneFactorStudentGaussianCopula(), QuantLib::CapFloorTermVolCurve::optionDates(), QuantLib::CapFloorTermVolSurface::optionDates(), QuantLib::OptionletStripper::optionletAccrualPeriods(), QuantLib::OptionletStripper::optionletFixingDates(), QuantLib::StrippedOptionlet::optionletFixingDates(), QuantLib::OptionletStripper::optionletFixingTimes(), QuantLib::StrippedOptionlet::optionletFixingTimes(), QuantLib::OptionletStripper::optionletPaymentDates(), QuantLib::OptionletStripper1::optionletPrices(), QuantLib::OptionletStripper::optionletStrikes(), QuantLib::OptionletStripper::optionletVolatilities(), QuantLib::StrippedOptionlet::optionletVolatilities(), QuantLib::CapFloorTermVolCurve::optionTimes(), QuantLib::CapFloorTermVolSurface::optionTimes(), recalculate(), QuantLib::SabrInterpolatedSmileSection::rho(), QuantLib::SabrInterpolatedSmileSection::rmsError(), QuantLib::SwaptionVolCube1::smileSection(), QuantLib::SwaptionVolCube2::smileSectionImpl(), QuantLib::SwaptionVolCube1::sparseSabrParameters(), QuantLib::OptionletStripper2::spreadsVol(), QuantLib::ForwardSwapQuote::startDate(), QuantLib::RendistatoCalculator::swapDurations(), QuantLib::RendistatoCalculator::swapRates(), QuantLib::RendistatoCalculator::swapYields(), QuantLib::OptionletStripper1::switchStrike(), QuantLib::Fdm2DimSolver::thetaAt(), QuantLib::Fdm1DimSolver::thetaAt(), QuantLib::Fdm3DimSolver::thetaAt(), QuantLib::Fdm2dBlackScholesSolver::thetaAt(), QuantLib::FdmBatesSolver::thetaAt(), QuantLib::FdmSimple2dBSSolver::thetaAt(), QuantLib::FdmHestonHullWhiteSolver::thetaAt(), QuantLib::FdmHestonSolver::thetaAt(), QuantLib::Basket::updateScenarioLoss(), QuantLib::ForwardSwapQuote::value(), QuantLib::EurodollarFuturesImpliedStdDevQuote::value(), QuantLib::ImpliedStdDevQuote::value(), QuantLib::FdmHullWhiteSolver::valueAt(), QuantLib::FdmG2Solver::valueAt(), QuantLib::FdmExtOUJumpSolver::valueAt(), QuantLib::Fdm2dBlackScholesSolver::valueAt(), QuantLib::FdmSimple2dBSSolver::valueAt(), QuantLib::FdmBatesSolver::valueAt(), QuantLib::FdmHestonHullWhiteSolver::valueAt(), QuantLib::FdmBlackScholesSolver::valueAt(), QuantLib::FdmHestonSolver::valueAt(), QuantLib::FdmSimple3dExtOUJumpSolver::valueAt(), QuantLib::FdmSimple2dExtOUSolver::valueAt(), QuantLib::FdmKlugeExtOUSolver< N >::valueAt(), QuantLib::ForwardSwapQuote::valueDate(), QuantLib::SabrInterpolatedSmileSection::varianceImpl(), QuantLib::StrippedOptionletAdapter::volatilityImpl(), QuantLib::SabrInterpolatedSmileSection::volatilityImpl(), QuantLib::CapFloorTermVolCurve::volatilityImpl(), QuantLib::CapFloorTermVolSurface::volatilityImpl(), QuantLib::SwaptionVolatilityMatrix::volatilityImpl(), QuantLib::SwaptionVolCube1::volCubeAtmCalibrated(), and QuantLib::RendistatoCalculator::yields().
{
        if (!calculated_ && !frozen_) {
            calculated_ = true;   // prevent infinite recursion in
                                  // case of bootstrapping
            try {
                performCalculations();
            } catch (...) {
                calculated_ = false;
                throw;
            }
        }
    }
void QuantLib::LazyObject::freeze () [inline]
This method constrains the object to return the presently cached results on successive invocations, even if arguments upon which they depend should change.
Definition at line 132 of file lazyobject.hpp.
References frozen_.
{
        frozen_ = true;
    }
virtual void QuantLib::LazyObject::performCalculations () const [protected, pure virtual]
This method must implement any calculations which must be (re)done in order to calculate the desired results.
Implemented in QuantLib::PiecewiseYieldCurve< Traits, Interpolator, Bootstrap >, QuantLib::OneFactorStudentGaussianCopula, QuantLib::Basket, QuantLib::PiecewiseYoYOptionletVolatilityCurve< Interpolator, Bootstrap, Traits >, QuantLib::PiecewiseDefaultCurve< Traits, Interpolator, Bootstrap >, QuantLib::FittedBondDiscountCurve, QuantLib::CDO, QuantLib::RendistatoCalculator, QuantLib::FixedRateBondForward, QuantLib::Forward, QuantLib::OneFactorGaussianStudentCopula, QuantLib::SwaptionVolCube1, QuantLib::ForwardRateAgreement, QuantLib::NthToDefault, QuantLib::Instrument, QuantLib::SwaptionVolatilityMatrix, QuantLib::PiecewiseYoYInflationCurve< Interpolator, Bootstrap, Traits >, QuantLib::PiecewiseZeroInflationCurve< Interpolator, Bootstrap, Traits >, QuantLib::CapFloorTermVolCurve, QuantLib::CapFloorTermVolSurface, QuantLib::SabrInterpolatedSmileSection, QuantLib::FlatForward, QuantLib::RiskyBond, QuantLib::AbcdAtmVolCurve, QuantLib::CmsMarket, QuantLib::ConvertibleBond, QuantLib::InterpolatedSmileSection< Interpolator >, QuantLib::StrippedOptionlet, QuantLib::SwaptionVolatilityDiscrete, QuantLib::OneFactorStudentCopula, QuantLib::CompositeInstrument, QuantLib::FdmHestonSolver, QuantLib::FdmKlugeExtOUSolver< N >, QuantLib::EnergyVanillaSwap, QuantLib::EnergyBasisSwap, QuantLib::RiskyAssetSwap, QuantLib::FdmHestonHullWhiteSolver, QuantLib::FdmBatesSolver, QuantLib::OptionletStripper1, QuantLib::OneFactorGaussianCopula, QuantLib::FdmSimple2dExtOUSolver, QuantLib::FdmSimple3dExtOUJumpSolver, QuantLib::SwaptionVolCube2, QuantLib::OptionletStripper2, QuantLib::StrippedOptionletAdapter, QuantLib::FdmBlackScholesSolver, QuantLib::ForwardSwapQuote, QuantLib::Fdm2dBlackScholesSolver, QuantLib::Fdm2DimSolver, QuantLib::FdmSimple2dBSSolver, QuantLib::Fdm1DimSolver, QuantLib::EurodollarFuturesImpliedStdDevQuote, QuantLib::ImpliedStdDevQuote, QuantLib::FdmExtOUJumpSolver, QuantLib::FdmNdimSolver< N >, QuantLib::EnergyFuture, QuantLib::FdmG2Solver, QuantLib::FdmHullWhiteSolver, QuantLib::Fdm3DimSolver, QuantLib::RiskyAssetSwapOption, and QuantLib::Stock.
Referenced by calculate().
void QuantLib::LazyObject::recalculate () [inline]
This method force the recalculation of any results which would otherwise be cached. It is not declared as const since it needs to call the non-const notifyObservers method.
Note:
Explicit invocation of this method is not necessary if the object registered itself as observer with the structures on which such results depend. It is strongly advised to follow this policy when possible.
Definition at line 118 of file lazyobject.hpp.
References calculate(), calculated_, frozen_, and QuantLib::Observable::notifyObservers().
Referenced by anonymous_namespace{piecewiseyieldcurve.cpp}::testCurveCopy().
{
        bool wasFrozen = frozen_;
        calculated_ = frozen_ = false;
        try {
            calculate();
        } catch (...) {
            frozen_ = wasFrozen;
            notifyObservers();
            throw;
        }
        frozen_ = wasFrozen;
        notifyObservers();
    }
void QuantLib::LazyObject::unfreeze () [inline]
This method reverts the effect of the freeze method, thus re-enabling recalculations.
Definition at line 136 of file lazyobject.hpp.
References frozen_, and QuantLib::Observable::notifyObservers().
{
        // send notifications, just in case we lost any,
        // but only once, i.e. if it was frozen
        if (frozen_) {
            frozen_ = false;
            notifyObservers();
        }
    }
void QuantLib::LazyObject::update () [inline, virtual]
This method must be implemented in derived classes. An instance of Observer does not call this method directly: instead, it will be called by the observables the instance registered with when they need to notify any changes.
Implements QuantLib::Observer.
Reimplemented in QuantLib::PiecewiseYieldCurve< Traits, Interpolator, Bootstrap >, QuantLib::PiecewiseYoYOptionletVolatilityCurve< Interpolator, Bootstrap, Traits >, QuantLib::PiecewiseDefaultCurve< Traits, Interpolator, Bootstrap >, QuantLib::FittedBondDiscountCurve, QuantLib::PiecewiseYoYInflationCurve< Interpolator, Bootstrap, Traits >, QuantLib::CapFloorTermVolCurve, QuantLib::CapFloorTermVolSurface, QuantLib::PiecewiseZeroInflationCurve< Interpolator, Bootstrap, Traits >, QuantLib::SabrInterpolatedSmileSection, QuantLib::InterpolatedSmileSection< Interpolator >, QuantLib::FlatForward, QuantLib::AbcdAtmVolCurve, QuantLib::SwaptionVolatilityDiscrete, QuantLib::StrippedOptionletAdapter, QuantLib::CmsMarket, and QuantLib::ForwardSwapQuote.
Definition at line 102 of file lazyobject.hpp.
References calculated_, frozen_, and QuantLib::Observable::notifyObservers().
Referenced by QuantLib::CompositeInstrument::add(), QuantLib::Instrument::setPricingEngine(), QuantLib::InterpolatedSmileSection< Interpolator >::update(), QuantLib::PiecewiseZeroInflationCurve< Interpolator, Bootstrap, Traits >::update(), QuantLib::PiecewiseYoYInflationCurve< Interpolator, Bootstrap, Traits >::update(), QuantLib::PiecewiseDefaultCurve< Traits, Interpolator, Bootstrap >::update(), QuantLib::PiecewiseYoYOptionletVolatilityCurve< Interpolator, Bootstrap, Traits >::update(), and QuantLib::PiecewiseYieldCurve< Traits, Interpolator, Bootstrap >::update().
{
        // forwards notifications only the first time
        if (calculated_) {
            // set to false early
            // 1) to prevent infinite recursion
            // 2) otherways non-lazy observers would be served obsolete
            //    data because of calculated_ being still true
            calculated_ = false;
            // observers don't expect notifications from frozen objects
            if (!frozen_)
                notifyObservers();
                // exiting notifyObservers() calculated_ could be
                // already true because of non-lazy observers
        }
    }
Member Data Documentation
bool QuantLib::LazyObject::calculated_ [mutable, protected]
Definition at line 93 of file lazyobject.hpp.
Referenced by calculate(), QuantLib::Instrument::calculate(), recalculate(), and update().
bool QuantLib::LazyObject::frozen_ [mutable, protected]
Definition at line 93 of file lazyobject.hpp.
Referenced by calculate(), freeze(), recalculate(), unfreeze(), and update().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/patterns/lazyobject.hpp