QuantLib: QuantLib::DayCounter::Impl Class Reference
QuantLib::DayCounter::Impl Class Reference
abstract base class for day counter implementations
#include <daycounter.hpp>
Public Member Functions
virtual ~Impl ()
virtual std::string name () const =0
virtual BigInteger dayCount (const Date &d1, const Date &d2) const
to be overloaded by more complex day counters
virtual Time yearFraction (const Date &d1, const Date &d2, const Date &refPeriodStart, const Date &refPeriodEnd) const =0
Detailed Description
abstract base class for day counter implementations
Definition at line 46 of file daycounter.hpp.
Constructor & Destructor Documentation
virtual QuantLib::DayCounter::Impl::~Impl () [inline, virtual]
Definition at line 48 of file daycounter.hpp.
{}
Member Function Documentation
virtual BigInteger QuantLib::DayCounter::Impl::dayCount (const Date & d1, const Date & d2) const [inline, virtual]
to be overloaded by more complex day counters
Reimplemented in QuantLib::Thirty360::IT_Impl, QuantLib::Thirty360::EU_Impl, QuantLib::Thirty360::US_Impl, QuantLib::SimpleDayCounter::Impl, QuantLib::Business252::Impl, and QuantLib::OneDayCounter::Impl.
Definition at line 51 of file daycounter.hpp.
Referenced by QuantLib::Actual360::Impl::yearFraction(), QuantLib::Actual365Fixed::Impl::yearFraction(), and QuantLib::ActualActual::ISMA_Impl::yearFraction().
{
                return (d2-d1);
            }
virtual std::string QuantLib::DayCounter::Impl::name () const [pure virtual]
Implemented in QuantLib::Thirty360::IT_Impl, QuantLib::ActualActual::AFB_Impl, QuantLib::Thirty360::EU_Impl, QuantLib::ActualActual::ISDA_Impl, QuantLib::Thirty360::US_Impl, QuantLib::ActualActual::ISMA_Impl, QuantLib::SimpleDayCounter::Impl, QuantLib::Actual365Fixed::Impl, QuantLib::Business252::Impl, QuantLib::Actual360::Impl, and QuantLib::OneDayCounter::Impl.
virtual Time QuantLib::DayCounter::Impl::yearFraction (const Date & d1, const Date & d2, const Date & refPeriodStart, const Date & refPeriodEnd) const [pure virtual]
Implemented in QuantLib::Thirty360::IT_Impl, QuantLib::ActualActual::AFB_Impl, QuantLib::Thirty360::EU_Impl, QuantLib::ActualActual::ISDA_Impl, QuantLib::Thirty360::US_Impl, QuantLib::ActualActual::ISMA_Impl, QuantLib::SimpleDayCounter::Impl, QuantLib::Actual365Fixed::Impl, QuantLib::Business252::Impl, QuantLib::Actual360::Impl, and QuantLib::OneDayCounter::Impl.
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/time/daycounter.hpp