QuantLib: QuantLib::OptionletStripper2 Class Reference
QuantLib::OptionletStripper2 Class Reference
#include <optionletstripper2.hpp>
Classes
class ObjectiveFunction
Public Member Functions
OptionletStripper2 (const boost::shared_ptr< OptionletStripper1 > &optionletStripper1, const Handle< CapFloorTermVolCurve > &atmCapFloorTermVolCurve)
std::vector< Rate > atmCapFloorStrikes () const
std::vector< Real > atmCapFloorPrices () const
std::vector< Volatility > spreadsVol () const
LazyObject interface
void performCalculations () const
Private Member Functions
std::vector< Volatility > spreadsVolImplied () const
Private Attributes
const boost::shared_ptr
< OptionletStripper1 > stripper1_
const Handle
< CapFloorTermVolCurve > atmCapFloorTermVolCurve_
DayCounter dc_
Size nOptionExpiries_
std::vector< Rate > atmCapFloorStrikes_
std::vector< Real > atmCapFloorPrices_
std::vector< Volatility > spreadsVolImplied_
std::vector< boost::shared_ptr
< CapFloor > > caps_
Size maxEvaluations_
Real accuracy_
Detailed Description
Helper class to extend an OptionletStripper1 object stripping additional optionlet (i.e. caplet/floorlet) volatilities (a.k.a. forward-forward volatilities) from the (cap/floor) At-The-Money term volatilities of a CapFloorTermVolCurve.
Definition at line 42 of file optionletstripper2.hpp.
Constructor & Destructor Documentation
QuantLib::OptionletStripper2::OptionletStripper2 (const boost::shared_ptr< OptionletStripper1 > & optionletStripper1, const Handle< CapFloorTermVolCurve > & atmCapFloorTermVolCurve)
Definition at line 35 of file optionletstripper2.cpp.
References atmCapFloorTermVolCurve_, dc_, QL_REQUIRE, QuantLib::Observer::registerWith(), and stripper1_.
    : OptionletStripper(optionletStripper1->termVolSurface(),
                        optionletStripper1->iborIndex()),
      stripper1_(optionletStripper1),
      atmCapFloorTermVolCurve_(atmCapFloorTermVolCurve),
      dc_(stripper1_->termVolSurface()->dayCounter()),
      nOptionExpiries_(atmCapFloorTermVolCurve->optionTenors().size()),
      atmCapFloorStrikes_(nOptionExpiries_),
      atmCapFloorPrices_(nOptionExpiries_),
      spreadsVolImplied_(nOptionExpiries_),
      caps_(nOptionExpiries_),
      maxEvaluations_(10000),
      accuracy_(1.e-6) {
        registerWith(stripper1_);
        registerWith(atmCapFloorTermVolCurve_);
        QL_REQUIRE(dc_ == atmCapFloorTermVolCurve->dayCounter(),
                   "different day counters provided");
     }
Member Function Documentation
std::vector< Real > QuantLib::OptionletStripper2::atmCapFloorPrices () const
Definition at line 147 of file optionletstripper2.cpp.
References atmCapFloorPrices_, and QuantLib::LazyObject::calculate().
{
        calculate();
        return atmCapFloorPrices_;
    }
std::vector< Rate > QuantLib::OptionletStripper2::atmCapFloorStrikes () const
Definition at line 142 of file optionletstripper2.cpp.
References atmCapFloorStrikes_, and QuantLib::LazyObject::calculate().
{
        calculate();
        return atmCapFloorStrikes_;
    }
void QuantLib::OptionletStripper2::performCalculations () const [virtual]
This method must implement any calculations which must be (re)done in order to calculate the desired results.
Implements QuantLib::LazyObject.
Definition at line 57 of file optionletstripper2.cpp.
References atmCapFloorPrices_, atmCapFloorStrikes_, atmCapFloorTermVolCurve_, QuantLib::OptionletStripper::atmOptionletRate_, QuantLib::CapFloor::Cap, caps_, QuantLib::Days, dc_, QuantLib::OptionletStripper::iborIndex_, nOptionExpiries_, QuantLib::OptionletStripper::optionletAccrualPeriods_, QuantLib::OptionletStripper::optionletDates_, QuantLib::OptionletStripper::optionletPaymentDates_, QuantLib::OptionletStripper::optionletStrikes_, QuantLib::OptionletStripper::optionletTimes_, QuantLib::OptionletStripper::optionletVolatilities_, spreadsVolImplied(), spreadsVolImplied_, stripper1_, QuantLib::OptionletVolatilityStructure::volatility(), and QuantLib::MakeCapFloor::withPricingEngine().
{
        optionletDates_ = stripper1_->optionletFixingDates();
        optionletPaymentDates_ = stripper1_->optionletPaymentDates();
        optionletAccrualPeriods_ = stripper1_->optionletAccrualPeriods();
        optionletTimes_ = stripper1_->optionletFixingTimes();
        atmOptionletRate_ = stripper1_->atmOptionletRates();
        for (Size i=0; i<optionletTimes_.size(); ++i) {
            optionletStrikes_[i] = stripper1_->optionletStrikes(i);
            optionletVolatilities_[i] = stripper1_->optionletVolatilities(i);
        }
        // atmCapFloorTermVolCurve data
        const std::vector<Period>& optionExpiriesTenors =
                                    atmCapFloorTermVolCurve_->optionTenors();
        const std::vector<Time>& optionExpiriesTimes =
                                    atmCapFloorTermVolCurve_->optionTimes();
        for (Size j=0; j<nOptionExpiries_; ++j) {
            Volatility atmOptionVol = atmCapFloorTermVolCurve_->volatility(
                optionExpiriesTimes[j], 33.3333); // dummy strike
            boost::shared_ptr<BlackCapFloorEngine> engine(new
                    BlackCapFloorEngine(iborIndex_->forwardingTermStructure(),
                                        atmOptionVol, dc_));
            caps_[j] = MakeCapFloor(CapFloor::Cap,
                                    optionExpiriesTenors[j],
                                    iborIndex_,
                                    Null<Rate>(),
                                    0*Days).withPricingEngine(engine);
            atmCapFloorStrikes_[j] =
                caps_[j]->atmRate(**iborIndex_->forwardingTermStructure());
            atmCapFloorPrices_[j] = caps_[j]->NPV();
        }
        spreadsVolImplied_ = spreadsVolImplied();
        StrippedOptionletAdapter adapter(stripper1_);
        Volatility unadjustedVol, adjustedVol;
        for (Size j=0; j<nOptionExpiries_; ++j) {
            for (Size i=0; i<optionletVolatilities_.size(); ++i) {
                if (i<=caps_[j]->floatingLeg().size()) {
                    unadjustedVol = adapter.volatility(optionletTimes_[i],
                                                       atmCapFloorStrikes_[j]);
                    adjustedVol = unadjustedVol + spreadsVolImplied_[j];
                    // insert adjusted volatility
                    std::vector<Rate>::const_iterator previous =
                        std::lower_bound(optionletStrikes_[i].begin(),
                                         optionletStrikes_[i].end(),
                                         atmCapFloorStrikes_[j]);
                    Size insertIndex = previous - optionletStrikes_[i].begin();
                    optionletStrikes_[i].insert(
                                optionletStrikes_[i].begin() + insertIndex,
                                atmCapFloorStrikes_[j]);
                    optionletVolatilities_[i].insert(
                                optionletVolatilities_[i].begin() + insertIndex,
                                adjustedVol);
                }
            }
        }
    }
std::vector< Volatility > QuantLib::OptionletStripper2::spreadsVol () const
Definition at line 137 of file optionletstripper2.cpp.
References QuantLib::LazyObject::calculate(), and spreadsVolImplied_.
{
        calculate();
        return spreadsVolImplied_;
    }
std::vector< Volatility > QuantLib::OptionletStripper2::spreadsVolImplied () const [private]
Definition at line 122 of file optionletstripper2.cpp.
References accuracy_, atmCapFloorPrices_, caps_, anonymous_namespace{interpolations.cpp}::f(), maxEvaluations_, nOptionExpiries_, QuantLib::Solver1D< Impl >::setMaxEvaluations(), QuantLib::Solver1D< Impl >::solve(), and stripper1_.
Referenced by performCalculations().
{
        Brent solver;
        std::vector<Volatility> result(nOptionExpiries_);
        Volatility guess = 0.0001, minSpread = -0.1, maxSpread = 0.1;
        for (Size j=0; j<nOptionExpiries_; ++j) {
            ObjectiveFunction f(stripper1_, caps_[j], atmCapFloorPrices_[j]);
            solver.setMaxEvaluations(maxEvaluations_);
            Volatility root = solver.solve(f, accuracy_, guess,
                                           minSpread, maxSpread);
            result[j] = root;
        }
        return result;
    }
Member Data Documentation
Real QuantLib::OptionletStripper2::accuracy_ [private]
Definition at line 82 of file optionletstripper2.hpp.
Referenced by spreadsVolImplied().
std::vector<Real> QuantLib::OptionletStripper2::atmCapFloorPrices_ [mutable, private]
Definition at line 78 of file optionletstripper2.hpp.
Referenced by atmCapFloorPrices(), performCalculations(), and spreadsVolImplied().
std::vector<Rate> QuantLib::OptionletStripper2::atmCapFloorStrikes_ [mutable, private]
Definition at line 77 of file optionletstripper2.hpp.
Referenced by atmCapFloorStrikes(), and performCalculations().
const Handle<CapFloorTermVolCurve> QuantLib::OptionletStripper2::atmCapFloorTermVolCurve_ [private]
Definition at line 74 of file optionletstripper2.hpp.
Referenced by OptionletStripper2(), and performCalculations().
std::vector<boost::shared_ptr<CapFloor> > QuantLib::OptionletStripper2::caps_ [mutable, private]
Definition at line 80 of file optionletstripper2.hpp.
Referenced by performCalculations(), and spreadsVolImplied().
DayCounter QuantLib::OptionletStripper2::dc_ [private]
Definition at line 75 of file optionletstripper2.hpp.
Referenced by OptionletStripper2(), and performCalculations().
Size QuantLib::OptionletStripper2::maxEvaluations_ [private]
Definition at line 81 of file optionletstripper2.hpp.
Referenced by spreadsVolImplied().
Size QuantLib::OptionletStripper2::nOptionExpiries_ [private]
Definition at line 76 of file optionletstripper2.hpp.
Referenced by performCalculations(), and spreadsVolImplied().
std::vector<Volatility> QuantLib::OptionletStripper2::spreadsVolImplied_ [mutable, private]
Definition at line 79 of file optionletstripper2.hpp.
Referenced by performCalculations(), and spreadsVol().
const boost::shared_ptr<OptionletStripper1> QuantLib::OptionletStripper2::stripper1_ [private]
Definition at line 73 of file optionletstripper2.hpp.
Referenced by OptionletStripper2(), performCalculations(), and spreadsVolImplied().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/optionlet/optionletstripper2.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/optionlet/optionletstripper2.cpp