QuantLib: QuantLib::FwdToCotSwapAdapter Class Reference
QuantLib::FwdToCotSwapAdapter Class Reference
#include <fwdtocotswapadapter.hpp>
Public Member Functions
FwdToCotSwapAdapter (const boost::shared_ptr< MarketModel > &forwardModel)
MarketModel interface
const std::vector< Rate > & initialRates () const
const std::vector< Spread > & displacements () const
const EvolutionDescription & evolution () const
Size numberOfRates () const
Size numberOfFactors () const
Size numberOfSteps () const
const Matrix & pseudoRoot (Size i) const
Private Attributes
boost::shared_ptr< MarketModel > fwdModel_
Size numberOfFactors_
Size numberOfRates_
Size numberOfSteps_
std::vector< Rate > initialRates_
std::vector< Matrix > pseudoRoots_
Detailed Description
Definition at line 31 of file fwdtocotswapadapter.hpp.
Constructor & Destructor Documentation
QuantLib::FwdToCotSwapAdapter::FwdToCotSwapAdapter (const boost::shared_ptr< MarketModel > & forwardModel)
Definition at line 30 of file fwdtocotswapadapter.cpp.
References QuantLib::LMMCurveState::coterminalSwapRates(), QuantLib::SwapForwardMappings::coterminalSwapZedMatrix(), displacements(), fwdModel_, initialRates_, numberOfSteps_, QuantLib::io::ordinal(), pseudoRoots_, QL_REQUIRE, anonymous_namespace{marketmodel.cpp}::rateTimes, and QuantLib::LMMCurveState::setOnForwardRates().
    : fwdModel_(fwdModel),
      numberOfFactors_(fwdModel->numberOfFactors()),
      numberOfRates_(fwdModel->numberOfRates()),
      numberOfSteps_(fwdModel->numberOfSteps()),
      pseudoRoots_(numberOfSteps_, Matrix(numberOfRates_, numberOfFactors_))
    {
        const std::vector<Spread>& displacements =
            fwdModel_->displacements();
        for (Size i = 1; i<displacements.size(); ++i) {
            QL_REQUIRE(displacements[i]==displacements[0],
                       io::ordinal(i+1) << " displacement (" <<
                       displacements[i] << ") not equal to the previous ones"
                       " (" << displacements[0] << ")");
        }
        const std::vector<Time>& rateTimes =
            fwdModel_->evolution().rateTimes();
        // we must ensure we step through all rateTimes
        const std::vector<Time>& evolutionTimes =
            fwdModel_->evolution().evolutionTimes();
        for (Size i = 0;
             i<rateTimes.size() && rateTimes[i]<=evolutionTimes.back(); ++i) {
            QL_REQUIRE(std::find(evolutionTimes.begin(), evolutionTimes.end(),
                                 rateTimes[i])!=evolutionTimes.end(),
                                 "skipping " << io::ordinal(i+1) << " rate time");
        }
        LMMCurveState cs(rateTimes);
        const std::vector<Rate>& initialFwdRates =
            fwdModel_->initialRates();
        cs.setOnForwardRates(initialFwdRates);
        initialRates_ = cs.coterminalSwapRates();
        Matrix zedMatrix = SwapForwardMappings::coterminalSwapZedMatrix(
            cs, displacements[0]);
        const std::vector<Size>& alive =
            fwdModel_->evolution().firstAliveRate();
        for (Size k = 0; k<numberOfSteps_; ++k) {
            pseudoRoots_[k]=zedMatrix*fwdModel_->pseudoRoot(k);
            for (Size i=0; i<alive[k]; ++i)
                std::fill(pseudoRoots_[k].row_begin(i),
                          pseudoRoots_[k].row_end(i),
                          0.0);
        }
    }
Member Function Documentation
const std::vector< Spread > & QuantLib::FwdToCotSwapAdapter::displacements () const [inline, virtual]
Implements QuantLib::MarketModel.
Definition at line 74 of file fwdtocotswapadapter.hpp.
References fwdModel_.
Referenced by FwdToCotSwapAdapter().
{
        return fwdModel_->displacements();
    }
const EvolutionDescription & QuantLib::FwdToCotSwapAdapter::evolution () const [inline, virtual]
Implements QuantLib::MarketModel.
Definition at line 79 of file fwdtocotswapadapter.hpp.
References fwdModel_.
{
        return fwdModel_->evolution();
    }
const std::vector< Rate > & QuantLib::FwdToCotSwapAdapter::initialRates () const [inline, virtual]
Implements QuantLib::MarketModel.
Definition at line 69 of file fwdtocotswapadapter.hpp.
References initialRates_.
{
        return initialRates_;
    }
Size QuantLib::FwdToCotSwapAdapter::numberOfFactors () const [inline, virtual]
Implements QuantLib::MarketModel.
Definition at line 87 of file fwdtocotswapadapter.hpp.
References fwdModel_.
{
        return fwdModel_->numberOfFactors();
    }
Size QuantLib::FwdToCotSwapAdapter::numberOfRates () const [inline, virtual]
Implements QuantLib::MarketModel.
Definition at line 83 of file fwdtocotswapadapter.hpp.
References fwdModel_.
{
        return fwdModel_->numberOfRates();
    }
Size QuantLib::FwdToCotSwapAdapter::numberOfSteps () const [inline, virtual]
Implements QuantLib::MarketModel.
Definition at line 91 of file fwdtocotswapadapter.hpp.
References fwdModel_.
{
        return fwdModel_->numberOfSteps();
    }
const Matrix & QuantLib::FwdToCotSwapAdapter::pseudoRoot (Size i) const [inline, virtual]
Implements QuantLib::MarketModel.
Definition at line 95 of file fwdtocotswapadapter.hpp.
References pseudoRoots_.
{
        return pseudoRoots_[i];
    }
Member Data Documentation
boost::shared_ptr<MarketModel> QuantLib::FwdToCotSwapAdapter::fwdModel_ [private]
Definition at line 46 of file fwdtocotswapadapter.hpp.
Referenced by displacements(), evolution(), FwdToCotSwapAdapter(), numberOfFactors(), numberOfRates(), and numberOfSteps().
std::vector<Rate> QuantLib::FwdToCotSwapAdapter::initialRates_ [private]
Definition at line 48 of file fwdtocotswapadapter.hpp.
Referenced by FwdToCotSwapAdapter(), and initialRates().
Size QuantLib::FwdToCotSwapAdapter::numberOfFactors_ [private]
Definition at line 47 of file fwdtocotswapadapter.hpp.
Size QuantLib::FwdToCotSwapAdapter::numberOfRates_ [private]
Definition at line 47 of file fwdtocotswapadapter.hpp.
Size QuantLib::FwdToCotSwapAdapter::numberOfSteps_ [private]
Definition at line 47 of file fwdtocotswapadapter.hpp.
Referenced by FwdToCotSwapAdapter().
std::vector<Matrix> QuantLib::FwdToCotSwapAdapter::pseudoRoots_ [private]
Definition at line 49 of file fwdtocotswapadapter.hpp.
Referenced by FwdToCotSwapAdapter(), and pseudoRoot().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/models/fwdtocotswapadapter.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/models/fwdtocotswapadapter.cpp