QuantLib: QuantLib::ExchangeRateManager Class Reference
QuantLib::ExchangeRateManager Class Reference
exchange-rate repository
#include <exchangeratemanager.hpp>
Classes
struct Entry
Public Member Functions
void add (const ExchangeRate &, const Date &startDate=Date::minDate(), const Date &endDate=Date::maxDate())
Add an exchange rate.
ExchangeRate lookup (const Currency &source, const Currency &target, Date date=Date(), ExchangeRate::Type type=ExchangeRate::Derived) const
void clear ()
remove the added exchange rates
Private Types
typedef BigInteger Key
Private Member Functions
ExchangeRateManager ()
Key hash (const Currency &, const Currency &) const
bool hashes (Key, const Currency &) const
void addKnownRates ()
ExchangeRate directLookup (const Currency &source, const Currency &target, const Date &date) const
ExchangeRate smartLookup (const Currency &source, const Currency &target, const Date &date, std::list< Integer > forbiddenCodes=std::list< Integer >()) const
const ExchangeRate * fetch (const Currency &source, const Currency &target, const Date &date) const
Private Attributes
std::map< Key, std::list< Entry > > data_
Friends
class Singleton< ExchangeRateManager >
Detailed Description
exchange-rate repository
Test:
lookup of direct, triangulated, and derived exchange rates is tested.
Definition at line 40 of file exchangeratemanager.hpp.
Member Typedef Documentation
typedef BigInteger QuantLib::ExchangeRateManager::Key [private]
Definition at line 81 of file exchangeratemanager.hpp.
Constructor & Destructor Documentation
QuantLib::ExchangeRateManager::ExchangeRateManager () [private]
Definition at line 41 of file exchangeratemanager.cpp.
References addKnownRates().
{
        addKnownRates();
    }
Member Function Documentation
void QuantLib::ExchangeRateManager::add (const ExchangeRate & rate, const Date & startDate = Date::minDate(), const Date & endDate = Date::maxDate())
Add an exchange rate.
The given rate is valid between the given dates.
Note:
If two rates are given between the same currencies and with overlapping date ranges, the latest one added takes precedence during lookup.
Definition at line 45 of file exchangeratemanager.cpp.
References data_, hash(), QuantLib::ExchangeRate::source(), and QuantLib::ExchangeRate::target().
Referenced by addKnownRates(), MoneyTest::testAutomated(), MoneyTest::testBaseCurrency(), ExchangeRateTest::testDirectLookup(), ExchangeRateTest::testSmartLookup(), and ExchangeRateTest::testTriangulatedLookup().
{
        Key k = hash(rate.source(), rate.target());
        data_[k].push_front(Entry(rate,startDate,endDate));
    }
void QuantLib::ExchangeRateManager::addKnownRates () [private]
Definition at line 100 of file exchangeratemanager.cpp.
References add(), QuantLib::February, QuantLib::January, QuantLib::July, and QuantLib::Date::maxDate().
Referenced by clear(), and ExchangeRateManager().
{
        // currencies obsoleted by Euro
        add(ExchangeRate(EURCurrency(), ATSCurrency(), 13.7603),
            Date(1,January,1999), Date::maxDate());
        add(ExchangeRate(EURCurrency(), BEFCurrency(), 40.3399),
            Date(1,January,1999), Date::maxDate());
        add(ExchangeRate(EURCurrency(), DEMCurrency(), 1.95583),
            Date(1,January,1999), Date::maxDate());
        add(ExchangeRate(EURCurrency(), ESPCurrency(), 166.386),
            Date(1,January,1999), Date::maxDate());
        add(ExchangeRate(EURCurrency(), FIMCurrency(), 5.94573),
            Date(1,January,1999), Date::maxDate());
        add(ExchangeRate(EURCurrency(), FRFCurrency(), 6.55957),
            Date(1,January,1999), Date::maxDate());
        add(ExchangeRate(EURCurrency(), GRDCurrency(), 340.750),
            Date(1,January,2001), Date::maxDate());
        add(ExchangeRate(EURCurrency(), IEPCurrency(), 0.787564),
            Date(1,January,1999), Date::maxDate());
        add(ExchangeRate(EURCurrency(), ITLCurrency(), 1936.27),
            Date(1,January,1999), Date::maxDate());
        add(ExchangeRate(EURCurrency(), LUFCurrency(), 40.3399),
            Date(1,January,1999), Date::maxDate());
        add(ExchangeRate(EURCurrency(), NLGCurrency(), 2.20371),
            Date(1,January,1999), Date::maxDate());
        add(ExchangeRate(EURCurrency(), PTECurrency(), 200.482),
            Date(1,January,1999), Date::maxDate());
        // other obsoleted currencies
        add(ExchangeRate(TRYCurrency(), TRLCurrency(), 1000000.0),
            Date(1,January,2005), Date::maxDate());
        add(ExchangeRate(RONCurrency(), ROLCurrency(), 10000.0),
            Date(1,July,2005), Date::maxDate());
        add(ExchangeRate(PENCurrency(), PEICurrency(), 1000000.0),
            Date(1,July,1991), Date::maxDate());
        add(ExchangeRate(PEICurrency(), PEHCurrency(), 1000.0),
            Date(1,February,1985), Date::maxDate());
    }
void QuantLib::ExchangeRateManager::clear ()
remove the added exchange rates
Definition at line 84 of file exchangeratemanager.cpp.
References addKnownRates(), and data_.
Referenced by MoneyTest::testAutomated(), MoneyTest::testBaseCurrency(), ExchangeRateTest::testDirectLookup(), ExchangeRateTest::testSmartLookup(), and ExchangeRateTest::testTriangulatedLookup().
{
        data_.clear();
        addKnownRates();
    }
ExchangeRate QuantLib::ExchangeRateManager::directLookup (const Currency & source, const Currency & target, const Date & date) const [private]
Definition at line 137 of file exchangeratemanager.cpp.
References QuantLib::Currency::code(), fetch(), QL_FAIL, and QuantLib::io::rate().
Referenced by lookup().
{
        if (const ExchangeRate* rate = fetch(source,target,date))
            return *rate;
        else
            QL_FAIL("no direct conversion available from "
                    << source.code() << " to " << target.code()
                    << " for " << date);
    }
const ExchangeRate * QuantLib::ExchangeRateManager::fetch (const Currency & source, const Currency & target, const Date & date) const [private]
Definition at line 194 of file exchangeratemanager.cpp.
References data_, and hash().
Referenced by directLookup(), and smartLookup().
{
        const std::list<Entry>& rates = data_[hash(source,target)];
        std::list<Entry>::const_iterator i =
            std::find_if(rates.begin(), rates.end(), valid_at(date));
        return i == rates.end() ?
            (const ExchangeRate*) 0 :
            &(i->rate);
    }
ExchangeRateManager::Key QuantLib::ExchangeRateManager::hash (const Currency & c1, const Currency & c2) const [private]
Definition at line 89 of file exchangeratemanager.cpp.
References QuantLib::Currency::numericCode().
Referenced by add(), and fetch().
{
        return Key(std::min(c1.numericCode(),c2.numericCode()))*1000
             + Key(std::max(c1.numericCode(),c2.numericCode()));
    }
bool QuantLib::ExchangeRateManager::hashes (ExchangeRateManager::Key k, const Currency & c) const [private]
Definition at line 95 of file exchangeratemanager.cpp.
References QuantLib::Currency::numericCode().
Referenced by smartLookup().
{
        return c.numericCode() == k % 1000 || c.numericCode() == k/1000;
    }
ExchangeRate QuantLib::ExchangeRateManager::lookup (const Currency & source, const Currency & target, Date date = Date(), ExchangeRate::Type type = ExchangeRate::Derived) const
Lookup the exchange rate between two currencies at a given date. If the given type is Direct, only direct exchange rates will be returned if available; if Derived, direct rates are still preferred but derived rates are allowed.
Warning:
if two or more exchange-rate chains are possible which allow to specify a requested rate, it is unspecified which one is returned.
Definition at line 52 of file exchangeratemanager.cpp.
References QuantLib::ExchangeRate::chain(), QuantLib::ExchangeRate::Direct, directLookup(), QuantLib::Currency::empty(), QuantLib::Singleton< ExchangeRateManager >::instance(), smartLookup(), and QuantLib::Currency::triangulationCurrency().
Referenced by QuantLib::CommodityPricingHelper::calculateFxConversionFactor(), QuantLib::EnergyCommodity::calculateFxConversionFactor(), QuantLib::anonymous_namespace{money.cpp}::convertTo(), ExchangeRateTest::testDirectLookup(), ExchangeRateTest::testSmartLookup(), and ExchangeRateTest::testTriangulatedLookup().
{
        if (source == target)
            return ExchangeRate(source,target,1.0);
        if (date == Date())
            date = Settings::instance().evaluationDate();
        if (type == ExchangeRate::Direct) {
            return directLookup(source,target,date);
        } else if (!source.triangulationCurrency().empty()) {
            const Currency& link = source.triangulationCurrency();
            if (link == target)
                return directLookup(source,link,date);
            else
                return ExchangeRate::chain(directLookup(source,link,date),
                                           lookup(link,target,date));
        } else if (!target.triangulationCurrency().empty()) {
            const Currency& link = target.triangulationCurrency();
            if (source == link)
                return directLookup(link,target,date);
            else
                return ExchangeRate::chain(lookup(source,link,date),
                                           directLookup(link,target,date));
        } else {
            return smartLookup(source,target,date);
        }
    }
ExchangeRate QuantLib::ExchangeRateManager::smartLookup (const Currency & source, const Currency & target, const Date & date, std::list< Integer > forbiddenCodes = std::list<Integer>()) const [private]
Definition at line 148 of file exchangeratemanager.cpp.
References QuantLib::ExchangeRate::chain(), QuantLib::Currency::code(), data_, fetch(), hashes(), QuantLib::Currency::numericCode(), QL_FAIL, QuantLib::ExchangeRateManager::Entry::rate, QuantLib::ExchangeRate::source(), and QuantLib::ExchangeRate::target().
Referenced by lookup().
{
        // direct exchange rates are preferred.
        if (const ExchangeRate* direct = fetch(source,target,date))
            return *direct;
        // if none is found, turn to smart lookup. The source currency
        // is forbidden to subsequent lookups in order to avoid cycles.
        forbidden.push_back(source.numericCode());
        std::map<Key, std::list<Entry> >::const_iterator i;
        for (i = data_.begin(); i != data_.end(); ++i) {
            // we look for exchange-rate data which involve our source
            // currency...
            if (hashes(i->first, source) && !(i->second.empty())) {
                // ...whose other currency is not forbidden...
                const Entry& e = i->second.front();
                const Currency& other =
                    source == e.rate.source() ?
                        e.rate.target() : e.rate.source();
                if (std::find(forbidden.begin(),forbidden.end(),
                              other.numericCode()) == forbidden.end()) {
                    // ...and which carries information for the requested date.
                    if (const ExchangeRate* head = fetch(source,other,date)) {
                        // if we can get to the target from here...
                        try {
                            ExchangeRate tail = smartLookup(other,target,date,
                                                            forbidden);
                            // ..we're done.
                            return ExchangeRate::chain(*head,tail);
                        } catch (Error&) {
                            // otherwise, we just discard this rate.
                            ;
                        }
                    }
                }
            }
        }
        // if the loop completed, we have no way to return the requested rate.
        QL_FAIL("no conversion available from "
                << source.code() << " to " << target.code()
                << " for " << date);
    }
Friends And Related Function Documentation
friend class Singleton< ExchangeRateManager > [friend]
Definition at line 41 of file exchangeratemanager.hpp.
Member Data Documentation
std::map<Key, std::list<Entry> > QuantLib::ExchangeRateManager::data_ [mutable, private]
Definition at line 82 of file exchangeratemanager.hpp.
Referenced by add(), clear(), fetch(), and smartLookup().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/currencies/exchangeratemanager.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/currencies/exchangeratemanager.cpp