QuantLib: QuantLib::detail::LogInterpolationImpl< I1, I2, Interpolator > Class Template Reference
QuantLib::detail::LogInterpolationImpl< I1, I2, Interpolator > Class Template Reference
#include <loginterpolation.hpp>
Public Member Functions
LogInterpolationImpl (const I1 &xBegin, const I1 &xEnd, const I2 &yBegin, const Interpolator &factory=Interpolator())
void update ()
Real value (Real x) const
Real primitive (Real) const
Real derivative (Real x) const
Real secondDerivative (Real x) const
Private Attributes
std::vector< Real > logY_
Interpolation interpolation_
Detailed Description
template<class I1, class I2, class Interpolator>
class QuantLib::detail::LogInterpolationImpl< I1, I2, Interpolator >
Definition at line 37 of file loginterpolation.hpp.
Constructor & Destructor Documentation
template<class I1 , class I2 , class Interpolator > QuantLib::detail::LogInterpolationImpl< I1, I2, Interpolator >::LogInterpolationImpl (const I1 & xBegin, const I1 & xEnd, const I2 & yBegin, const Interpolator & factory = Interpolator()) [inline]
Definition at line 40 of file loginterpolation.hpp.
References QuantLib::detail::LogInterpolationImpl< I1, I2, Interpolator >::interpolation_, QuantLib::detail::LogInterpolationImpl< I1, I2, Interpolator >::logY_, QuantLib::Interpolation::templateImpl< I1, I2 >::xBegin_, and QuantLib::Interpolation::templateImpl< I1, I2 >::xEnd_.
            : Interpolation::templateImpl<I1,I2>(xBegin, xEnd, yBegin),
              logY_(xEnd-xBegin) {
                interpolation_ = factory.interpolate(this->xBegin_,
                                                     this->xEnd_,
                                                     logY_.begin());
            }
Member Function Documentation
template<class I1 , class I2 , class Interpolator > Real QuantLib::detail::LogInterpolationImpl< I1, I2, Interpolator >::derivative (Real x) const [inline, virtual]
Implements QuantLib::Interpolation::Impl.
Definition at line 64 of file loginterpolation.hpp.
References QuantLib::Interpolation::derivative(), QuantLib::detail::LogInterpolationImpl< I1, I2, Interpolator >::interpolation_, and QuantLib::detail::LogInterpolationImpl< I1, I2, Interpolator >::value().
Referenced by QuantLib::detail::LogInterpolationImpl< I1, I2, Interpolator >::secondDerivative().
{
                return value(x)*interpolation_.derivative(x, true);
            }
template<class I1 , class I2 , class Interpolator > Real QuantLib::detail::LogInterpolationImpl< I1, I2, Interpolator >::primitive (Real) const [inline, virtual]
Implements QuantLib::Interpolation::Impl.
Definition at line 61 of file loginterpolation.hpp.
References QL_FAIL.
{
                QL_FAIL("LogInterpolation primitive not implemented");
            }
template<class I1 , class I2 , class Interpolator > Real QuantLib::detail::LogInterpolationImpl< I1, I2, Interpolator >::secondDerivative (Real x) const [inline, virtual]
Implements QuantLib::Interpolation::Impl.
Definition at line 67 of file loginterpolation.hpp.
References QuantLib::detail::LogInterpolationImpl< I1, I2, Interpolator >::derivative(), QuantLib::Interpolation::derivative(), QuantLib::detail::LogInterpolationImpl< I1, I2, Interpolator >::interpolation_, QuantLib::Interpolation::secondDerivative(), and QuantLib::detail::LogInterpolationImpl< I1, I2, Interpolator >::value().
{
                return derivative(x)*interpolation_.derivative(x, true) +
                            value(x)*interpolation_.secondDerivative(x, true);
            }
template<class I1 , class I2 , class Interpolator > void QuantLib::detail::LogInterpolationImpl< I1, I2, Interpolator >::update () [inline, virtual]
Implements QuantLib::Interpolation::Impl.
Definition at line 49 of file loginterpolation.hpp.
References QuantLib::detail::LogInterpolationImpl< I1, I2, Interpolator >::interpolation_, QuantLib::detail::LogInterpolationImpl< I1, I2, Interpolator >::logY_, QL_REQUIRE, QuantLib::Interpolation::update(), and QuantLib::Interpolation::templateImpl< I1, I2 >::yBegin_.
{
                for (Size i=0; i<logY_.size(); ++i) {
                    QL_REQUIRE(this->yBegin_[i]>0.0,
                               "invalid value (" << this->yBegin_[i]
                               << ") at index " << i);
                    logY_[i] = std::log(this->yBegin_[i]);
                }
                interpolation_.update();
            }
template<class I1 , class I2 , class Interpolator > Real QuantLib::detail::LogInterpolationImpl< I1, I2, Interpolator >::value (Real x) const [inline, virtual]
Implements QuantLib::Interpolation::Impl.
Definition at line 58 of file loginterpolation.hpp.
References QuantLib::detail::LogInterpolationImpl< I1, I2, Interpolator >::interpolation_.
Referenced by QuantLib::detail::LogInterpolationImpl< I1, I2, Interpolator >::derivative(), and QuantLib::detail::LogInterpolationImpl< I1, I2, Interpolator >::secondDerivative().
{
                return std::exp(interpolation_(x, true));
            }
Member Data Documentation
template<class I1 , class I2 , class Interpolator > Interpolation QuantLib::detail::LogInterpolationImpl< I1, I2, Interpolator >::interpolation_ [private]
Definition at line 73 of file loginterpolation.hpp.
Referenced by QuantLib::detail::LogInterpolationImpl< I1, I2, Interpolator >::derivative(), QuantLib::detail::LogInterpolationImpl< I1, I2, Interpolator >::LogInterpolationImpl(), QuantLib::detail::LogInterpolationImpl< I1, I2, Interpolator >::secondDerivative(), QuantLib::detail::LogInterpolationImpl< I1, I2, Interpolator >::update(), and QuantLib::detail::LogInterpolationImpl< I1, I2, Interpolator >::value().
template<class I1 , class I2 , class Interpolator > std::vector<Real> QuantLib::detail::LogInterpolationImpl< I1, I2, Interpolator >::logY_ [private]
Definition at line 72 of file loginterpolation.hpp.
Referenced by QuantLib::detail::LogInterpolationImpl< I1, I2, Interpolator >::LogInterpolationImpl(), and QuantLib::detail::LogInterpolationImpl< I1, I2, Interpolator >::update().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/interpolations/loginterpolation.hpp