QuantLib: QuantLib::detail::BilinearInterpolationImpl< I1, I2, M > Class Template Reference
QuantLib::detail::BilinearInterpolationImpl< I1, I2, M > Class Template Reference
#include <bilinearinterpolation.hpp>
Public Member Functions
BilinearInterpolationImpl (const I1 &xBegin, const I1 &xEnd, const I2 &yBegin, const I2 &yEnd, const M &zData)
void calculate ()
Real value (Real x, Real y) const
Detailed Description
template<class I1, class I2, class M>
class QuantLib::detail::BilinearInterpolationImpl< I1, I2, M >
Definition at line 35 of file bilinearinterpolation.hpp.
Constructor & Destructor Documentation
template<class I1 , class I2 , class M > QuantLib::detail::BilinearInterpolationImpl< I1, I2, M >::BilinearInterpolationImpl (const I1 & xBegin, const I1 & xEnd, const I2 & yBegin, const I2 & yEnd, const M & zData) [inline]
Definition at line 38 of file bilinearinterpolation.hpp.
References QuantLib::detail::BilinearInterpolationImpl< I1, I2, M >::calculate().
            : Interpolation2D::templateImpl<I1,I2,M>(xBegin,xEnd,
                                                     yBegin,yEnd,
                                                     zData) {
                calculate();
            }
Member Function Documentation
template<class I1 , class I2 , class M > void QuantLib::detail::BilinearInterpolationImpl< I1, I2, M >::calculate () [inline, virtual]
Implements QuantLib::Interpolation2D::Impl.
Definition at line 46 of file bilinearinterpolation.hpp.
Referenced by QuantLib::detail::BilinearInterpolationImpl< I1, I2, M >::BilinearInterpolationImpl().
{}
template<class I1 , class I2 , class M > Real QuantLib::detail::BilinearInterpolationImpl< I1, I2, M >::value (Real x, Real y) const [inline, virtual]
Implements QuantLib::Interpolation2D::Impl.
Definition at line 47 of file bilinearinterpolation.hpp.
References QuantLib::Interpolation2D::templateImpl< I1, I2, M >::locateX(), QuantLib::Interpolation2D::templateImpl< I1, I2, M >::locateY(), anonymous_namespace{quantlibbenchmark.cpp}::t, QuantLib::Interpolation2D::templateImpl< I1, I2, M >::xBegin_, QuantLib::Interpolation2D::templateImpl< I1, I2, M >::yBegin_, and QuantLib::Interpolation2D::templateImpl< I1, I2, M >::zData_.
{
                Size i = this->locateX(x), j = this->locateY(y);
                Real z1 = this->zData_[j][i];
                Real z2 = this->zData_[j][i+1];
                Real z3 = this->zData_[j+1][i];
                Real z4 = this->zData_[j+1][i+1];
                Real t=(x-this->xBegin_[i])/
                    (this->xBegin_[i+1]-this->xBegin_[i]);
                Real u=(y-this->yBegin_[j])/
                    (this->yBegin_[j+1]-this->yBegin_[j]);
                return (1.0-t)*(1.0-u)*z1 + t*(1.0-u)*z2
                     + (1.0-t)*u*z3 + t*u*z4;
            }
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/interpolations/bilinearinterpolation.hpp