QuantLib: QuantLib::UpperBoundEngine Class Reference
QuantLib::UpperBoundEngine Class Reference
Market-model engine for upper-bound estimation.
#include <upperboundengine.hpp>
Public Member Functions
UpperBoundEngine (const boost::shared_ptr< MarketModelEvolver > &evolver, const std::vector< boost::shared_ptr< MarketModelEvolver > > &innerEvolvers, const MarketModelMultiProduct &underlying, const MarketModelExerciseValue &rebate, const MarketModelMultiProduct &hedge, const MarketModelExerciseValue &hedgeRebate, const ExerciseStrategy< CurveState > &hedgeStrategy, Real initialNumeraireValue)
void multiplePathValues (Statistics &stats, Size outerPaths, Size innerPaths)
std::pair< Real, Real > singlePathValue (Size innerPaths)
Private Member Functions
Real collectCashFlows (Size currentStep, Real principalInNumerairePortfolio, Size beginProduct, Size endProduct) const
Private Attributes
boost::shared_ptr
< MarketModelEvolver > evolver_
std::vector< boost::shared_ptr
< MarketModelEvolver > > innerEvolvers_
MultiProductComposite composite_
Real initialNumeraireValue_
Size underlyingSize_
Size rebateSize_
Size hedgeSize_
Size hedgeRebateSize_
Size underlyingOffset_
Size rebateOffset_
Size hedgeOffset_
Size hedgeRebateOffset_
Size numberOfProducts_
Size numberOfSteps_
std::valarray< bool > isExerciseTime_
std::vector< Size > numberCashFlowsThisStep_
std::vector< std::vector
< MarketModelMultiProduct::CashFlow > > cashFlowsGenerated_
std::vector
< MarketModelDiscounter > discounters_
Detailed Description
Market-model engine for upper-bound estimation.
Precondition:
product and hedge must have the same rate times and exercise times
Definition at line 43 of file upperboundengine.hpp.
Constructor & Destructor Documentation
QuantLib::UpperBoundEngine::UpperBoundEngine (const boost::shared_ptr< MarketModelEvolver > & evolver, const std::vector< boost::shared_ptr< MarketModelEvolver > > & innerEvolvers, const MarketModelMultiProduct & underlying, const MarketModelExerciseValue & rebate, const MarketModelMultiProduct & hedge, const MarketModelExerciseValue & hedgeRebate, const ExerciseStrategy< CurveState > & hedgeStrategy, Real initialNumeraireValue)
Definition at line 110 of file upperboundengine.cpp.
References QuantLib::MarketModelComposite::add(), cashFlowsGenerated_, composite_, discounters_, QuantLib::MarketModelComposite::evolution(), QuantLib::EvolutionDescription::evolutionTimes(), QuantLib::ExerciseStrategy< State >::exerciseTimes(), QuantLib::MarketModelComposite::finalize(), hedgeOffset_, hedgeRebateOffset_, hedgeRebateSize_, hedgeSize_, isExerciseTime_, QuantLib::isInSubset(), QuantLib::MultiProductComposite::maxNumberOfCashFlowsPerProductPerStep(), numberCashFlowsThisStep_, QuantLib::MultiProductComposite::numberOfProducts(), QuantLib::MarketModelMultiProduct::numberOfProducts(), numberOfProducts_, numberOfSteps_, QuantLib::MarketModelComposite::possibleCashFlowTimes(), QuantLib::EvolutionDescription::rateTimes(), anonymous_namespace{marketmodel.cpp}::rateTimes, rebateOffset_, rebateSize_, underlyingOffset_, and underlyingSize_.
    : evolver_(evolver), innerEvolvers_(innerEvolvers),
      composite_(MultiProductComposite()),
      initialNumeraireValue_(initialNumeraireValue) {
        composite_.add(underlying);
        composite_.add(ExerciseAdapter(rebate));
        composite_.add(hedge);
        composite_.add(ExerciseAdapter(hedgeRebate));
        composite_.add(DecoratedHedge(CallSpecifiedMultiProduct(
                           hedge,hedgeStrategy,ExerciseAdapter(hedgeRebate))));
        composite_.finalize();
        underlyingOffset_ = 0;
        underlyingSize_ = underlying.numberOfProducts();
        rebateOffset_ = underlyingSize_;
        rebateSize_ = 1;
        hedgeOffset_ = underlyingSize_+rebateSize_;
        hedgeSize_ = hedge.numberOfProducts();
        hedgeRebateOffset_ = underlyingSize_+rebateSize_+hedgeSize_;
        hedgeRebateSize_ = 1;
        numberOfProducts_ = composite_.numberOfProducts();
        const std::vector<Time>& evolutionTimes =
            composite_.evolution().evolutionTimes();
        numberOfSteps_ = evolutionTimes.size();
        isExerciseTime_.resize(evolutionTimes.size());
        isExerciseTime_ = isInSubset(evolutionTimes,
                                     hedgeStrategy.exerciseTimes());
        numberCashFlowsThisStep_.resize(numberOfProducts_);
        cashFlowsGenerated_.resize(numberOfProducts_);
        for (Size i=0; i<numberOfProducts_; ++i)
            cashFlowsGenerated_[i].resize(
                          composite_.maxNumberOfCashFlowsPerProductPerStep());
        const std::vector<Time>& cashFlowTimes =
            composite_.possibleCashFlowTimes();
        const std::vector<Rate>& rateTimes =
            composite_.evolution().rateTimes();
        Size n =cashFlowTimes.size();
        discounters_.reserve(n);
        for (Size j=0; j<n; ++j)
            discounters_.push_back(MarketModelDiscounter(cashFlowTimes[j],
                                                         rateTimes));
    }
Member Function Documentation
Real QuantLib::UpperBoundEngine::collectCashFlows (Size currentStep, Real principalInNumerairePortfolio, Size beginProduct, Size endProduct) const [private]
Definition at line 325 of file upperboundengine.cpp.
References cashFlowsGenerated_, discounters_, evolver_, numberCashFlowsThisStep_, and QuantLib::MarketModelDiscounter::numeraireBonds().
Referenced by singlePathValue().
{
        Size numeraire = evolver_->numeraires()[currentStep];
        Real numeraireUnits = 0.0;
        // For each product in range...
        for (Size i=beginProduct; i<endProduct; ++i) {
            // ...and for each cash flow...
            const std::vector<MarketModelMultiProduct::CashFlow>& cashflows =
                cashFlowsGenerated_[i];
            for (Size j=0; j<numberCashFlowsThisStep_[i]; ++j) {
                // ...convert the cash flow to numeraires.  This is
                // done by calculating the number of numeraire bonds
                // corresponding to such cash flow...
                const MarketModelDiscounter& discounter =
                    discounters_[cashflows[j].timeIndex];
                // ...and adding the newly bought bonds to the total
                numeraireUnits += cashflows[j].amount *
                    discounter.numeraireBonds(evolver_->currentState(),
                                              numeraire);
            }
        }
        return numeraireUnits/principalInNumerairePortfolio;
    }
void QuantLib::UpperBoundEngine::multiplePathValues (Statistics & stats, Size outerPaths, Size innerPaths)
Definition at line 170 of file upperboundengine.cpp.
References singlePathValue().
Referenced by MarketModelTest::testCallableSwapAnderson(), MarketModelTest::testCallableSwapLS(), and MarketModelTest::testCallableSwapNaif().
{
        for (Size i=0; i<outerPaths; ++i) {
            std::pair<Real,Real> result = singlePathValue(innerPaths);
            stats.add(result.first, result.second);
        }
    }
std::pair< Real, Real > QuantLib::UpperBoundEngine::singlePathValue (Size innerPaths)
Definition at line 180 of file upperboundengine.cpp.
References cashFlowsGenerated_, collectCashFlows(), composite_, evolver_, QuantLib::ExerciseStrategy< State >::exercise(), hedgeOffset_, hedgeRebateOffset_, hedgeRebateSize_, hedgeSize_, initialNumeraireValue_, innerEvolvers_, isExerciseTime_, QuantLib::MarketModelComposite::item(), QuantLib::AccountingEngine::multiplePathValues(), QuantLib::MultiProductComposite::nextTimeStep(), numberCashFlowsThisStep_, numberOfSteps_, QL_MIN_REAL, rebateOffset_, rebateSize_, QuantLib::MarketModelComposite::reset(), underlyingOffset_, and underlyingSize_.
Referenced by multiplePathValues().
{
        DecoratedHedge& callable =
            dynamic_cast<DecoratedHedge&>(composite_.item(4));
        const ExerciseStrategy<CurveState>& strategy = callable.strategy();
        Real maximumValue = QL_MIN_REAL;
        Real numerairesHeld = 0.0;
        Real weight = evolver_->startNewPath();
        callable.clear();
        composite_.reset();
        callable.disableCallability();
        Real principalInNumerairePortfolio = 1.0;
        Size exercise = 0;
        for (Size k=0; k<numberOfSteps_; ++k) {
            weight *= evolver_->advanceStep();
            composite_.nextTimeStep(evolver_->currentState(),
                                    numberCashFlowsThisStep_,
                                    cashFlowsGenerated_);
            // First, we accumulate cash flows from both the
            // underlying...
            Real underlyingCashFlows =
                collectCashFlows(k,
                                 principalInNumerairePortfolio,
                                 underlyingOffset_,
                                 underlyingOffset_+underlyingSize_);
            // ...and the hedge
            Real hedgeCashFlows =
                collectCashFlows(k,
                                 principalInNumerairePortfolio,
                                 hedgeOffset_,
                                 hedgeOffset_+hedgeSize_);
            // we do the same for the rebates. Warning: this relies on
            // the fact that on each exercise date an ExerciseAdapter
            // generates a cash-flow equal to the exercise value
            Real rebateCashFlow =
                collectCashFlows(k,
                                 principalInNumerairePortfolio,
                                 rebateOffset_,
                                 rebateOffset_+rebateSize_);
            Real hedgeRebateCashFlow =
                collectCashFlows(k,
                                 principalInNumerairePortfolio,
                                  hedgeRebateOffset_,
                                 hedgeRebateOffset_+hedgeRebateSize_);
            numerairesHeld += underlyingCashFlows - hedgeCashFlows;
            // Second, we do the upper-bound thing
            if (isExerciseTime_[k]) {
                Real unexercisedHedgeValue = 0.0;
                if (k != numberOfSteps_-1) {
                    // Here, we setup the relevant inner evolver and
                    // the decorated callable hedge such that their
                    // reset() method brings them to the current point
                    // rather than the beginning of the path.
                    boost::shared_ptr<MarketModelEvolver> currentEvolver =
                        innerEvolvers_[exercise++];
                    currentEvolver->setInitialState(evolver_->currentState());
                    callable.stopRecording();
                    callable.enableCallability();
                    callable.save();
                    // This allows us to write:
                    AccountingEngine engine(currentEvolver, callable,
                                            1.0); // this causes the result
                                                  // to be in numeraire units
                    SequenceStatisticsInc innerStats(callable.numberOfProducts());
                    engine.multiplePathValues(innerStats, innerPaths);
                    const std::vector<Real>& values = innerStats.mean();
                    unexercisedHedgeValue =
                        std::accumulate(values.begin(), values.end(), 0.0)
                        / principalInNumerairePortfolio;
                    callable.disableCallability();
                    callable.startRecording();
                }
                // Now, we can calculate the total value of our hedged
                // portfolio...
                Real portfolioValue = numerairesHeld;
                if (strategy.exercise(evolver_->currentState())) {
                    // get the rebates...
                    portfolioValue +=
                        rebateCashFlow - hedgeRebateCashFlow;
                    // ...and reinvest to rehedge
                    numerairesHeld +=
                        unexercisedHedgeValue - hedgeRebateCashFlow;
                } else {
                    portfolioValue +=
                        rebateCashFlow - unexercisedHedgeValue;
                }
                // ...and use it to update the maximum value
                maximumValue = std::max(maximumValue, portfolioValue);
            }
            // Lastly, we do the homework for next step (if any)
            if (k<numberOfSteps_-1) {
                // The numeraire might change between steps. This implies
                // that we might have to convert the numeraire bonds for
                // this step into a corresponding amount of numeraire
                // bonds for the next step. This can be done by changing
                // the principal of the numeraire and updating the number
                // of bonds in the numeraire portfolio accordingly.
                Size numeraire = evolver_->numeraires()[k];
                Size nextNumeraire = evolver_->numeraires()[k+1];
                principalInNumerairePortfolio *=
                    evolver_->currentState().discountRatio(numeraire,
                                                           nextNumeraire);
            }
        }
        // finally, we update the maximum with the total accumulated
        // cash flows (in case we never exercised)
        maximumValue = std::max(maximumValue, numerairesHeld);
        // all done; we just convert the result back to cash
        maximumValue *= initialNumeraireValue_;
        return std::make_pair(maximumValue, weight);
    }
Member Data Documentation
std::vector<std::vector<MarketModelMultiProduct::CashFlow> > QuantLib::UpperBoundEngine::cashFlowsGenerated_ [private]
Definition at line 79 of file upperboundengine.hpp.
Referenced by collectCashFlows(), singlePathValue(), and UpperBoundEngine().
MultiProductComposite QuantLib::UpperBoundEngine::composite_ [private]
Definition at line 67 of file upperboundengine.hpp.
Referenced by singlePathValue(), and UpperBoundEngine().
std::vector<MarketModelDiscounter> QuantLib::UpperBoundEngine::discounters_ [private]
Definition at line 80 of file upperboundengine.hpp.
Referenced by collectCashFlows(), and UpperBoundEngine().
boost::shared_ptr<MarketModelEvolver> QuantLib::UpperBoundEngine::evolver_ [private]
Definition at line 65 of file upperboundengine.hpp.
Referenced by collectCashFlows(), and singlePathValue().
Size QuantLib::UpperBoundEngine::hedgeOffset_ [private]
Definition at line 71 of file upperboundengine.hpp.
Referenced by singlePathValue(), and UpperBoundEngine().
Size QuantLib::UpperBoundEngine::hedgeRebateOffset_ [private]
Definition at line 71 of file upperboundengine.hpp.
Referenced by singlePathValue(), and UpperBoundEngine().
Size QuantLib::UpperBoundEngine::hedgeRebateSize_ [private]
Definition at line 70 of file upperboundengine.hpp.
Referenced by singlePathValue(), and UpperBoundEngine().
Size QuantLib::UpperBoundEngine::hedgeSize_ [private]
Definition at line 70 of file upperboundengine.hpp.
Referenced by singlePathValue(), and UpperBoundEngine().
Real QuantLib::UpperBoundEngine::initialNumeraireValue_ [private]
Definition at line 69 of file upperboundengine.hpp.
Referenced by singlePathValue().
std::vector<boost::shared_ptr<MarketModelEvolver> > QuantLib::UpperBoundEngine::innerEvolvers_ [private]
Definition at line 66 of file upperboundengine.hpp.
Referenced by singlePathValue().
std::valarray<bool> QuantLib::UpperBoundEngine::isExerciseTime_ [private]
Definition at line 74 of file upperboundengine.hpp.
Referenced by singlePathValue(), and UpperBoundEngine().
std::vector<Size> QuantLib::UpperBoundEngine::numberCashFlowsThisStep_ [private]
Definition at line 77 of file upperboundengine.hpp.
Referenced by collectCashFlows(), singlePathValue(), and UpperBoundEngine().
Size QuantLib::UpperBoundEngine::numberOfProducts_ [private]
Definition at line 72 of file upperboundengine.hpp.
Referenced by UpperBoundEngine().
Size QuantLib::UpperBoundEngine::numberOfSteps_ [private]
Definition at line 73 of file upperboundengine.hpp.
Referenced by singlePathValue(), and UpperBoundEngine().
Size QuantLib::UpperBoundEngine::rebateOffset_ [private]
Definition at line 71 of file upperboundengine.hpp.
Referenced by singlePathValue(), and UpperBoundEngine().
Size QuantLib::UpperBoundEngine::rebateSize_ [private]
Definition at line 70 of file upperboundengine.hpp.
Referenced by singlePathValue(), and UpperBoundEngine().
Size QuantLib::UpperBoundEngine::underlyingOffset_ [private]
Definition at line 71 of file upperboundengine.hpp.
Referenced by singlePathValue(), and UpperBoundEngine().
Size QuantLib::UpperBoundEngine::underlyingSize_ [private]
Definition at line 70 of file upperboundengine.hpp.
Referenced by singlePathValue(), and UpperBoundEngine().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/callability/upperboundengine.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/callability/upperboundengine.cpp