QuantLib: QuantLib::yoyInflationLeg Class Reference
QuantLib::yoyInflationLeg Class Reference
#include <yoyinflationcoupon.hpp>
Public Member Functions
yoyInflationLeg (const Schedule &schedule, const Calendar &cal, const boost::shared_ptr< YoYInflationIndex > &index, const Period &observationLag)
yoyInflationLeg & withNotionals (Real notional)
yoyInflationLeg & withNotionals (const std::vector< Real > &notionals)
yoyInflationLeg & withPaymentDayCounter (const DayCounter &)
yoyInflationLeg & withPaymentAdjustment (BusinessDayConvention)
yoyInflationLeg & withFixingDays (Natural fixingDays)
yoyInflationLeg & withFixingDays (const std::vector< Natural > &fixingDays)
yoyInflationLeg & withGearings (Real gearing)
yoyInflationLeg & withGearings (const std::vector< Real > &gearings)
yoyInflationLeg & withSpreads (Spread spread)
yoyInflationLeg & withSpreads (const std::vector< Spread > &spreads)
yoyInflationLeg & withCaps (Rate cap)
yoyInflationLeg & withCaps (const std::vector< Rate > &caps)
yoyInflationLeg & withFloors (Rate floor)
yoyInflationLeg & withFloors (const std::vector< Rate > &floors)
operator Leg () const
Private Attributes
Schedule schedule_
boost::shared_ptr
< YoYInflationIndex > index_
Period observationLag_
std::vector< Real > notionals_
DayCounter paymentDayCounter_
BusinessDayConvention paymentAdjustment_
Calendar paymentCalendar_
std::vector< Natural > fixingDays_
std::vector< Real > gearings_
std::vector< Spread > spreads_
std::vector< Rate > caps_
std::vector< Rate > floors_
Detailed Description
Helper class building a sequence of capped/floored yoy inflation coupons payoff is: spread + gearing x index
Definition at line 91 of file yoyinflationcoupon.hpp.
Constructor & Destructor Documentation
QuantLib::yoyInflationLeg::yoyInflationLeg (const Schedule & schedule, const Calendar & cal, const boost::shared_ptr< YoYInflationIndex > & index, const Period & observationLag)
Definition at line 65 of file yoyinflationcoupon.cpp.
    : schedule_(schedule), index_(index),
      observationLag_(observationLag),
      paymentAdjustment_(ModifiedFollowing),
      paymentCalendar_(paymentCalendar) {}
Member Function Documentation
QuantLib::yoyInflationLeg::operator Leg () const
Definition at line 145 of file yoyinflationcoupon.cpp.
References QuantLib::Calendar::adjust(), QuantLib::Schedule::businessDayConvention(), QuantLib::Schedule::calendar(), anonymous_namespace{marketmodel.cpp}::calendar, caps_, QuantLib::Schedule::date(), QuantLib::detail::effectiveFixedRate(), fixingDays_, floors_, gearings_, QuantLib::detail::get(), index_, QuantLib::Schedule::isRegular(), QuantLib::detail::noOption(), notionals_, observationLag_, paymentAdjustment_, paymentCalendar_, paymentDayCounter_, QL_REQUIRE, schedule_, QuantLib::Schedule::size(), spreads_, and QuantLib::Schedule::tenor().
{
        Size n = schedule_.size()-1;
        QL_REQUIRE(!notionals_.empty(), "no notional given");
        QL_REQUIRE(notionals_.size() <= n,
                   "too many nominals (" << notionals_.size() <<
                   "), only " << n << " required");
        QL_REQUIRE(gearings_.size()<=n,
                   "too many gearings (" << gearings_.size() <<
                   "), only " << n << " required");
        QL_REQUIRE(spreads_.size()<=n,
                   "too many spreads (" << spreads_.size() <<
                   "), only " << n << " required");
        QL_REQUIRE(caps_.size()<=n,
                   "too many caps (" << caps_.size() <<
                   "), only " << n << " required");
        QL_REQUIRE(floors_.size()<=n,
                   "too many floors (" << floors_.size() <<
                   "), only " << n << " required");
        Leg leg; leg.reserve(n);
        Calendar calendar = paymentCalendar_;
        Date refStart, start, refEnd, end;
        for (Size i=0; i<n; ++i) {
            refStart = start = schedule_.date(i);
            refEnd   =   end = schedule_.date(i+1);
            Date paymentDate = calendar.adjust(end, paymentAdjustment_);
            if (i==0   && !schedule_.isRegular(i+1)) {
                BusinessDayConvention bdc = schedule_.businessDayConvention();
                refStart = schedule_.calendar().adjust(end - schedule_.tenor(), bdc);
            }
            if (i==n-1 && !schedule_.isRegular(i+1)) {
                BusinessDayConvention bdc = schedule_.businessDayConvention();
                refEnd = schedule_.calendar().adjust(start + schedule_.tenor(), bdc);
            }
            if (detail::get(gearings_, i, 1.0) == 0.0) { // fixed coupon
                leg.push_back(boost::shared_ptr<CashFlow>(new
                            FixedRateCoupon(paymentDate,
                            detail::get(notionals_, i, 1.0),
                            detail::effectiveFixedRate(spreads_,caps_,
                                    floors_,i),
                                    paymentDayCounter_,
                                    start, end, refStart, refEnd)));
            } else { // yoy inflation coupon
                if (detail::noOption(caps_, floors_, i)) { // just swaplet
                    boost::shared_ptr<YoYInflationCoupon> coup(new
                            YoYInflationCoupon(
                            paymentDate,
                            detail::get(notionals_, i, 1.0),
                            start, end,
                            detail::get(fixingDays_, i, 0),
                            index_,
                            observationLag_,
                            paymentDayCounter_,
                            detail::get(gearings_, i, 1.0),
                            detail::get(spreads_, i, 0.0),
                            refStart, refEnd));
                    // in this case you can set a pricer
                    // straight away because it only provides computation - not data
                    boost::shared_ptr<YoYInflationCouponPricer> pricer(
                                            new YoYInflationCouponPricer);
                    coup->setPricer(pricer);
                    leg.push_back(boost::dynamic_pointer_cast<CashFlow>(coup));
                } else {    // cap/floorlet
                    leg.push_back(boost::shared_ptr<CashFlow>(new
                            CappedFlooredYoYInflationCoupon(
                            paymentDate,
                            detail::get(notionals_, i, 1.0),
                            start, end,
                            detail::get(fixingDays_, i, 0),
                            index_,
                            observationLag_,
                            paymentDayCounter_,
                            detail::get(gearings_, i, 1.0),
                            detail::get(spreads_, i, 0.0),
                            detail::get(caps_,   i, Null<Rate>()),
                            detail::get(floors_, i, Null<Rate>()),
                            refStart, refEnd)));
                }
            }
        }
        return leg;
    }
yoyInflationLeg & QuantLib::yoyInflationLeg::withCaps (Rate cap)
Definition at line 124 of file yoyinflationcoupon.cpp.
References caps_.
Referenced by anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::makeYoYCapFlooredLeg().
{
        caps_ = std::vector<Rate>(1,cap);
        return *this;
    }
yoyInflationLeg & QuantLib::yoyInflationLeg::withCaps (const std::vector< Rate > & caps)
Definition at line 129 of file yoyinflationcoupon.cpp.
References caps_.
{
        caps_ = caps;
        return *this;
    }
yoyInflationLeg & QuantLib::yoyInflationLeg::withFixingDays (Natural fixingDays)
Definition at line 94 of file yoyinflationcoupon.cpp.
References fixingDays_.
{
        fixingDays_ = std::vector<Natural>(1,fixingDays);
        return *this;
    }
yoyInflationLeg & QuantLib::yoyInflationLeg::withFixingDays (const std::vector< Natural > & fixingDays)
Definition at line 99 of file yoyinflationcoupon.cpp.
References fixingDays_.
{
        fixingDays_ = fixingDays;
        return *this;
    }
yoyInflationLeg & QuantLib::yoyInflationLeg::withFloors (Rate floor)
Definition at line 134 of file yoyinflationcoupon.cpp.
References floors_.
Referenced by anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::makeYoYCapFlooredLeg().
{
        floors_ = std::vector<Rate>(1,floor);
        return *this;
    }
yoyInflationLeg & QuantLib::yoyInflationLeg::withFloors (const std::vector< Rate > & floors)
Definition at line 139 of file yoyinflationcoupon.cpp.
References floors_.
{
        floors_ = floors;
        return *this;
    }
yoyInflationLeg & QuantLib::yoyInflationLeg::withGearings (Real gearing)
Definition at line 104 of file yoyinflationcoupon.cpp.
References gearings_.
Referenced by anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::makeYoYCapFlooredLeg(), and anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::makeYoYLeg().
{
        gearings_ = std::vector<Real>(1,gearing);
        return *this;
    }
yoyInflationLeg & QuantLib::yoyInflationLeg::withGearings (const std::vector< Real > & gearings)
Definition at line 109 of file yoyinflationcoupon.cpp.
References gearings_.
{
        gearings_ = gearings;
        return *this;
    }
yoyInflationLeg & QuantLib::yoyInflationLeg::withNotionals (Real notional)
Definition at line 74 of file yoyinflationcoupon.cpp.
References notionals_.
Referenced by anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::makeYoYCapFlooredLeg(), anonymous_namespace{inflationcapfloor.cpp}::CommonVars::makeYoYLeg(), anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::makeYoYLeg(), QuantLib::MakeYoYInflationCapFloor::operator boost::shared_ptr< YoYInflationCapFloor >(), and QuantLib::YearOnYearInflationSwap::YearOnYearInflationSwap().
{
        notionals_ = std::vector<Real>(1,notional);
        return *this;
    }
yoyInflationLeg & QuantLib::yoyInflationLeg::withNotionals (const std::vector< Real > & notionals)
Definition at line 79 of file yoyinflationcoupon.cpp.
References notionals_.
{
        notionals_ = notionals;
        return *this;
    }
yoyInflationLeg & QuantLib::yoyInflationLeg::withPaymentAdjustment (BusinessDayConvention convention)
Definition at line 89 of file yoyinflationcoupon.cpp.
References paymentAdjustment_.
Referenced by anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::makeYoYCapFlooredLeg(), anonymous_namespace{inflationcapfloor.cpp}::CommonVars::makeYoYLeg(), anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::makeYoYLeg(), QuantLib::MakeYoYInflationCapFloor::operator boost::shared_ptr< YoYInflationCapFloor >(), and QuantLib::YearOnYearInflationSwap::YearOnYearInflationSwap().
{
        paymentAdjustment_ = convention;
        return *this;
    }
yoyInflationLeg & QuantLib::yoyInflationLeg::withPaymentDayCounter (const DayCounter & dayCounter)
Definition at line 84 of file yoyinflationcoupon.cpp.
References anonymous_namespace{marketmodel.cpp}::dayCounter, and paymentDayCounter_.
Referenced by anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::makeYoYCapFlooredLeg(), anonymous_namespace{inflationcapfloor.cpp}::CommonVars::makeYoYLeg(), anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::makeYoYLeg(), QuantLib::MakeYoYInflationCapFloor::operator boost::shared_ptr< YoYInflationCapFloor >(), and QuantLib::YearOnYearInflationSwap::YearOnYearInflationSwap().
{
        paymentDayCounter_ = dayCounter;
        return *this;
    }
yoyInflationLeg & QuantLib::yoyInflationLeg::withSpreads (Spread spread)
Definition at line 114 of file yoyinflationcoupon.cpp.
References spreads_.
Referenced by anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::makeYoYCapFlooredLeg(), anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::makeYoYLeg(), and QuantLib::YearOnYearInflationSwap::YearOnYearInflationSwap().
{
        spreads_ = std::vector<Spread>(1,spread);
        return *this;
    }
yoyInflationLeg & QuantLib::yoyInflationLeg::withSpreads (const std::vector< Spread > & spreads)
Definition at line 119 of file yoyinflationcoupon.cpp.
References spreads_.
{
        spreads_ = spreads;
        return *this;
    }
Member Data Documentation
std::vector<Rate> QuantLib::yoyInflationLeg::caps_ [private]
Definition at line 122 of file yoyinflationcoupon.hpp.
Referenced by operator Leg(), and withCaps().
std::vector<Natural> QuantLib::yoyInflationLeg::fixingDays_ [private]
Definition at line 119 of file yoyinflationcoupon.hpp.
Referenced by operator Leg(), and withFixingDays().
std::vector<Rate> QuantLib::yoyInflationLeg::floors_ [private]
Definition at line 122 of file yoyinflationcoupon.hpp.
Referenced by operator Leg(), and withFloors().
std::vector<Real> QuantLib::yoyInflationLeg::gearings_ [private]
Definition at line 120 of file yoyinflationcoupon.hpp.
Referenced by operator Leg(), and withGearings().
boost::shared_ptr<YoYInflationIndex> QuantLib::yoyInflationLeg::index_ [private]
Definition at line 113 of file yoyinflationcoupon.hpp.
Referenced by operator Leg().
std::vector<Real> QuantLib::yoyInflationLeg::notionals_ [private]
Definition at line 115 of file yoyinflationcoupon.hpp.
Referenced by operator Leg(), and withNotionals().
Period QuantLib::yoyInflationLeg::observationLag_ [private]
Definition at line 114 of file yoyinflationcoupon.hpp.
Referenced by operator Leg().
BusinessDayConvention QuantLib::yoyInflationLeg::paymentAdjustment_ [private]
Definition at line 117 of file yoyinflationcoupon.hpp.
Referenced by operator Leg(), and withPaymentAdjustment().
Calendar QuantLib::yoyInflationLeg::paymentCalendar_ [private]
Definition at line 118 of file yoyinflationcoupon.hpp.
Referenced by operator Leg().
DayCounter QuantLib::yoyInflationLeg::paymentDayCounter_ [private]
Definition at line 116 of file yoyinflationcoupon.hpp.
Referenced by operator Leg(), and withPaymentDayCounter().
Schedule QuantLib::yoyInflationLeg::schedule_ [private]
Definition at line 112 of file yoyinflationcoupon.hpp.
Referenced by operator Leg().
std::vector<Spread> QuantLib::yoyInflationLeg::spreads_ [private]
Definition at line 121 of file yoyinflationcoupon.hpp.
Referenced by operator Leg(), and withSpreads().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/yoyinflationcoupon.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/yoyinflationcoupon.cpp