QuantLib: QuantLib::SimplePolynomialFitting Class Reference
QuantLib::SimplePolynomialFitting Class Reference
Simple polynomial fitting method.
#include <nonlinearfittingmethods.hpp>
Public Member Functions
SimplePolynomialFitting (Natural degree, bool constrainAtZero=true)
std::auto_ptr
< FittedBondDiscountCurve::FittingMethod > clone () const
clone of the current object
Private Member Functions
Size size () const
total number of coefficients to fit/solve for
DiscountFactor discountFunction (const Array &x, Time t) const
derived classes must set this
Private Attributes
Size size_
Detailed Description
Simple polynomial fitting method.
Definition at line 147 of file nonlinearfittingmethods.hpp.
Constructor & Destructor Documentation
QuantLib::SimplePolynomialFitting::SimplePolynomialFitting (Natural degree, bool constrainAtZero = true)
Definition at line 187 of file nonlinearfittingmethods.cpp.
Referenced by clone().
    : FittedBondDiscountCurve::FittingMethod(constrainAtZero),
      size_(constrainAtZero ? degree : degree+1) {}
Member Function Documentation
std::auto_ptr< FittedBondDiscountCurve::FittingMethod > QuantLib::SimplePolynomialFitting::clone () const [virtual]
clone of the current object
Implements QuantLib::FittedBondDiscountCurve::FittingMethod.
Definition at line 193 of file nonlinearfittingmethods.cpp.
References SimplePolynomialFitting().
{
        return std::auto_ptr<FittedBondDiscountCurve::FittingMethod>(
                                          new SimplePolynomialFitting(*this));
    }
DiscountFactor QuantLib::SimplePolynomialFitting::discountFunction (const Array & x, Time t) const [private, virtual]
derived classes must set this
user-defined discount curve, as a function of time and an array of unknown fitting coefficients \(x_i \).
Implements QuantLib::FittedBondDiscountCurve::FittingMethod.
Definition at line 202 of file nonlinearfittingmethods.cpp.
References QuantLib::FittedBondDiscountCurve::FittingMethod::constrainAtZero_, anonymous_namespace{marketmodel.cpp}::d, QuantLib::BernsteinPolynomial::get(), and size_.
{
        DiscountFactor d = 0.0;
        if (!constrainAtZero_) {
            for (Size i=0; i<size_; ++i)
                d += x[i] * BernsteinPolynomial::get(i,i,t);
        } else {
            d = 1.0;
            for (Size i=0; i<size_; ++i)
                d += x[i] * BernsteinPolynomial::get(i+1,i+1,t);
        }
        return d;
    }
Size QuantLib::SimplePolynomialFitting::size () const [private, virtual]
total number of coefficients to fit/solve for
Implements QuantLib::FittedBondDiscountCurve::FittingMethod.
Definition at line 198 of file nonlinearfittingmethods.cpp.
References size_.
{
        return size_;
    }
Member Data Documentation
Size QuantLib::SimplePolynomialFitting::size_ [private]
Definition at line 156 of file nonlinearfittingmethods.hpp.
Referenced by discountFunction(), and size().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/yield/nonlinearfittingmethods.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/yield/nonlinearfittingmethods.cpp