QuantLib: QuantLib::AnalyticWriterExtensibleOptionEngine Class Reference
QuantLib::AnalyticWriterExtensibleOptionEngine Class Reference
Analytic engine for writer-extensible options.
#include <analyticwriterextensibleoptionengine.hpp>
Public Member Functions
AnalyticWriterExtensibleOptionEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > &process)
void calculate () const
Private Attributes
boost::shared_ptr
< GeneralizedBlackScholesProcess > process_
Detailed Description
Analytic engine for writer-extensible options.
Definition at line 33 of file analyticwriterextensibleoptionengine.hpp.
Constructor & Destructor Documentation
QuantLib::AnalyticWriterExtensibleOptionEngine::AnalyticWriterExtensibleOptionEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > & process)
Definition at line 28 of file analyticwriterextensibleoptionengine.cpp.
References process_, and QuantLib::Observer::registerWith().
    : process_(process) {
        registerWith(process_);
    }
Member Function Documentation
void QuantLib::AnalyticWriterExtensibleOptionEngine::calculate () const [virtual]
Implements QuantLib::PricingEngine.
Definition at line 34 of file analyticwriterextensibleoptionengine.cpp.
References QuantLib::GenericEngine< WriterExtensibleOption::arguments, WriterExtensibleOption::results >::arguments_, anonymous_namespace{marketmodel.cpp}::b, QuantLib::blackFormula(), QuantLib::Option::Call, QuantLib::Continuous, QuantLib::Option::arguments::exercise, QuantLib::WriterExtensibleOption::arguments::exercise2, QuantLib::NoFrequency, QuantLib::Option::arguments::payoff, QuantLib::WriterExtensibleOption::arguments::payoff2, QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow(), process_, QL_REQUIRE, QuantLib::GenericEngine< WriterExtensibleOption::arguments, WriterExtensibleOption::results >::results_, QuantLib::Instrument::results::value, QuantLib::io::volatility(), and QuantLib::DayCounter::yearFraction().
{
        // We take all the arguments:
        boost::shared_ptr<PlainVanillaPayoff> payoff1 =
            boost::dynamic_pointer_cast<PlainVanillaPayoff>(arguments_.payoff);
        QL_REQUIRE(payoff1, "not a plain vanilla payoff");
        boost::shared_ptr<PlainVanillaPayoff> payoff2 =
            boost::dynamic_pointer_cast<PlainVanillaPayoff>(arguments_.payoff2);
        QL_REQUIRE(payoff2, "not a plain vanilla payoff");
        boost::shared_ptr<Exercise> exercise1 = arguments_.exercise;
        boost::shared_ptr<Exercise> exercise2 = arguments_.exercise2;
        // We create and apply the calculate process:
        Option::Type type = payoff1->optionType();
        // STEP 1:
        // S = spot
        Real spot = process_->stateVariable()->value();
        // For the B&S formulae:
        DayCounter dividendDC = process_->dividendYield()->dayCounter();
        Rate dividend = process_->dividendYield()->zeroRate(
                  exercise1->lastDate(), dividendDC, Continuous, NoFrequency);
        DayCounter riskFreeDC = process_->riskFreeRate()->dayCounter();
        Rate riskFree = process_->riskFreeRate()->zeroRate(
                  exercise1->lastDate(), riskFreeDC, Continuous, NoFrequency);
        // The time to maturity:
        Time t1 = riskFreeDC.yearFraction(
                                    process_->riskFreeRate()->referenceDate(),
                                    arguments_.exercise->lastDate());
        Time t2 = riskFreeDC.yearFraction(
                                    process_->riskFreeRate()->referenceDate(),
                                    arguments_.exercise2->lastDate());
        // b = r-q:
        Real b = riskFree - dividend;
        Real forwardPrice = spot * std::exp(b*t1);
        Volatility volatility = process_->blackVolatility()->blackVol(
                                    exercise1->lastDate(), payoff1->strike());
        Real stdDev = volatility*std::sqrt(t1);
        Real discount = std::exp(-riskFree*t1);
        // Call the B&S method:
        Real black = blackFormula(type, payoff1->strike(),
                                  forwardPrice, stdDev, discount);
        // STEP 2:
        // Standard bivariate normal distribution:
        Real ro = std::sqrt(t1/t2);
        Real z1 = (std::log(spot/payoff2->strike()) +
                   (b+std::pow(volatility, 2)/2)*t2)/(volatility*std::sqrt(t2));
        Real z2 = (std::log(spot/payoff1->strike()) +
                   (b+std::pow(volatility, 2)/2)*t1)/(volatility*std::sqrt(t1));
        // Call the bivariate method:
        BivariateCumulativeNormalDistributionWe04DP biv(-ro);
        // STEP 3:
        Real bivariate1, bivariate2, result;
        // Final computing:
        if (type == Option::Call) {
            // Call case:
            bivariate1 = biv(z1, -z2);
            bivariate2 = biv(z1-volatility*std::sqrt(t2),
                             -z2+volatility*std::sqrt(t1));
            result = black + spot*std::exp((b-riskFree)*t2)*bivariate1
                - payoff2->strike()*std::exp((-riskFree)*t2)*bivariate2;
        } else {
            // Put case:
            bivariate1 = biv(-z1, z2);
            bivariate2 = biv(-z1+volatility*std::sqrt(t2),
                             z2-volatility*std::sqrt(t1));
            result = black - spot*std::exp((b-riskFree)*t2)*bivariate1
                + payoff2->strike()*std::exp((-riskFree)*t2)*bivariate2;
        }
        // Save the result:
        results_.value = result;
    }
Member Data Documentation
boost::shared_ptr<GeneralizedBlackScholesProcess> QuantLib::AnalyticWriterExtensibleOptionEngine::process_ [private]
Definition at line 40 of file analyticwriterextensibleoptionengine.hpp.
Referenced by AnalyticWriterExtensibleOptionEngine(), and calculate().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/exoticoptions/analyticwriterextensibleoptionengine.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/exoticoptions/analyticwriterextensibleoptionengine.cpp