QuantLib: QuantLib::SwaptionPseudoDerivative Class Reference
QuantLib::SwaptionPseudoDerivative Class Reference
#include <swaptionpseudojacobian.hpp>
Public Member Functions
SwaptionPseudoDerivative (boost::shared_ptr< MarketModel > inputModel, Size startIndex, Size endIndex)
const Matrix & varianceDerivative (Size i) const
const Matrix & volatilityDerivative (Size i) const
Real impliedVolatility () const
Real variance () const
Real expiry () const
Private Attributes
boost::shared_ptr< MarketModel > inputModel_
std::vector< Matrix > varianceDerivatives_
std::vector< Matrix > volatilityDerivatives_
Real impliedVolatility_
Real expiry_
Real variance_
Detailed Description
Definition at line 38 of file swaptionpseudojacobian.hpp.
Constructor & Destructor Documentation
QuantLib::SwaptionPseudoDerivative::SwaptionPseudoDerivative (boost::shared_ptr< MarketModel > inputModel, Size startIndex, Size endIndex)
Definition at line 34 of file swaptionpseudojacobian.cpp.
References QuantLib::SwapForwardMappings::coterminalSwapZedMatrix(), expiry_, anonymous_namespace{interpolations.cpp}::f(), impliedVolatility_, QuantLib::io::rate(), variance_, varianceDerivatives_, and volatilityDerivatives_.
    {
        std::vector<Real> subRateTimes(inputModel->evolution().rateTimes().begin()+startIndex,
            inputModel->evolution().rateTimes().begin()+endIndex+1);
        std::vector<Real> subForwards(inputModel->initialRates().begin()+startIndex,inputModel->initialRates().begin()+endIndex);
        LMMCurveState cs(subRateTimes);
        cs.setOnForwardRates(subForwards);
        Matrix zed(SwapForwardMappings::coterminalSwapZedMatrix(cs,inputModel->displacements()[0]));
        Size factors = inputModel->numberOfFactors();
        //first compute variance and implied vol
        variance_=0.0;
        Size index=0;
        while (index <  inputModel->evolution().numberOfSteps() && inputModel->evolution().firstAliveRate()[index] <= startIndex)
        {
            const Matrix& thisPseudo = inputModel->pseudoRoot(index);
            Real thisVariance_ =0.0;
            for (Size j=startIndex; j < endIndex; ++j)
                for (Size k=startIndex; k < endIndex; ++k)
                    for (Size f=0; f < factors; ++f)
                        thisVariance_+= zed[0][j-startIndex]*thisPseudo[j][f]*thisPseudo[k][f]*zed[0][k-startIndex];
            variance_ += thisVariance_;
            ++index;
        }
        Size stopIndex = index;
        expiry_ = subRateTimes[0];
        impliedVolatility_ = std::sqrt(variance_/expiry_);
        Real scale = 0.5*(1.0/expiry_)/impliedVolatility_;
        Size numberRates = inputModel->evolution().numberOfRates();
        Matrix thisDerivative(numberRates, factors,0.0);
        Matrix nullDerivative(numberRates, factors,0.0);
        index =0;
        while (index < stopIndex)
        {
            const Matrix& thisPseudo = inputModel->pseudoRoot(index);
            for (Size rate=startIndex; rate<endIndex; ++rate)
            {
                Size zIndex = rate -startIndex;
                for (Size f =0; f < factors; ++f)
                {
                    double sum=0.0;
                    for (Size rate2 = startIndex; rate2<endIndex; ++rate2)
                    {
                        Size zIndex2 = rate2-startIndex;
                        sum += zed[0][zIndex2] * thisPseudo[rate2][f];
                    }
                    sum *= 2.0*zed[0][zIndex];
                    thisDerivative[rate][f] =sum;
                }
            }
            varianceDerivatives_.push_back(thisDerivative);
            for ( Size rate=startIndex; rate<endIndex; ++rate)
                for (Size f =0; f < factors; ++f)
                    thisDerivative[rate][f] *= scale;
            volatilityDerivatives_.push_back(thisDerivative);
            ++index;
        }
        for (; index < inputModel->evolution().numberOfSteps(); ++index)
        {
            varianceDerivatives_.push_back(nullDerivative);
            volatilityDerivatives_.push_back(nullDerivative);
        }
    }
Member Function Documentation
Real QuantLib::SwaptionPseudoDerivative::expiry () const
Definition at line 149 of file swaptionpseudojacobian.cpp.
References expiry_.
    {
        return expiry_;
    }
Real QuantLib::SwaptionPseudoDerivative::impliedVolatility () const
Definition at line 141 of file swaptionpseudojacobian.cpp.
References impliedVolatility_.
    {
        return impliedVolatility_;
    }
Real QuantLib::SwaptionPseudoDerivative::variance () const
Definition at line 145 of file swaptionpseudojacobian.cpp.
References variance_.
    {
        return variance_;
    }
const Matrix & QuantLib::SwaptionPseudoDerivative::varianceDerivative (Size i) const
Definition at line 131 of file swaptionpseudojacobian.cpp.
References varianceDerivatives_.
    {
        return varianceDerivatives_[i];
    }
const Matrix & QuantLib::SwaptionPseudoDerivative::volatilityDerivative (Size i) const
Definition at line 136 of file swaptionpseudojacobian.cpp.
References volatilityDerivatives_.
Referenced by MarketModelTest::testPathwiseMarketVegas(), and MarketModelTest::testPathwiseVegas().
    {
        return volatilityDerivatives_[i];
    }
Member Data Documentation
Real QuantLib::SwaptionPseudoDerivative::expiry_ [private]
Definition at line 61 of file swaptionpseudojacobian.hpp.
Referenced by expiry(), and SwaptionPseudoDerivative().
Real QuantLib::SwaptionPseudoDerivative::impliedVolatility_ [private]
Definition at line 60 of file swaptionpseudojacobian.hpp.
Referenced by impliedVolatility(), and SwaptionPseudoDerivative().
boost::shared_ptr<MarketModel> QuantLib::SwaptionPseudoDerivative::inputModel_ [private]
Definition at line 56 of file swaptionpseudojacobian.hpp.
Real QuantLib::SwaptionPseudoDerivative::variance_ [private]
Definition at line 62 of file swaptionpseudojacobian.hpp.
Referenced by SwaptionPseudoDerivative(), and variance().
std::vector<Matrix> QuantLib::SwaptionPseudoDerivative::varianceDerivatives_ [private]
Definition at line 57 of file swaptionpseudojacobian.hpp.
Referenced by SwaptionPseudoDerivative(), and varianceDerivative().
std::vector<Matrix> QuantLib::SwaptionPseudoDerivative::volatilityDerivatives_ [private]
Definition at line 58 of file swaptionpseudojacobian.hpp.
Referenced by SwaptionPseudoDerivative(), and volatilityDerivative().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/pathwisegreeks/swaptionpseudojacobian.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/pathwisegreeks/swaptionpseudojacobian.cpp