QuantLib: QuantLib::SwaptionVolCube2 Class Reference
QuantLib::SwaptionVolCube2 Class Reference
#include <swaptionvolcube2.hpp>
Public Member Functions
SwaptionVolCube2 (const Handle< SwaptionVolatilityStructure > &atmVolStructure, const std::vector< Period > &optionTenors, const std::vector< Period > &swapTenors, const std::vector< Spread > &strikeSpreads, const std::vector< std::vector< Handle< Quote > > > &volSpreads, const boost::shared_ptr< SwapIndex > &swapIndexBase, const boost::shared_ptr< SwapIndex > &shortSwapIndexBase, bool vegaWeightedSmileFit)
LazyObject interface
void performCalculations () const
SwaptionVolatilityCube inspectors
const Matrix & volSpreads (Size i) const
boost::shared_ptr< SmileSection > smileSectionImpl (const Date &optionDate, const Period &swapTenor) const
boost::shared_ptr< SmileSection > smileSectionImpl (Time optionTime, Time swapLength) const
Private Attributes
std::vector< Interpolation2D > volSpreadsInterpolator_
std::vector< Matrix > volSpreadsMatrix_
Detailed Description
Definition at line 32 of file swaptionvolcube2.hpp.
Constructor & Destructor Documentation
QuantLib::SwaptionVolCube2::SwaptionVolCube2 (const Handle< SwaptionVolatilityStructure > & atmVolStructure, const std::vector< Period > & optionTenors, const std::vector< Period > & swapTenors, const std::vector< Spread > & strikeSpreads, const std::vector< std::vector< Handle< Quote > > > & volSpreads, const boost::shared_ptr< SwapIndex > & swapIndexBase, const boost::shared_ptr< SwapIndex > & shortSwapIndexBase, bool vegaWeightedSmileFit)
The swaption vol cube is made up of ordered swaption vol surface layers, each layer referring to a swap index of a given length (in years), all indexes belonging to the same family. In order to identify the family (and its market conventions) an index of whatever length from that family must be passed in as swapIndexBase.
Often for short swap length the swap index family is different, e.g. the EUR case: swap vs 6M Euribor is used for length>1Y, while swap vs 3M Euribor is used for the 1Y length. The shortSwapIndexBase is used to identify this second family.
Definition at line 28 of file swaptionvolcube2.cpp.
    : SwaptionVolatilityCube(atmVolStructure, optionTenors, swapTenors,
                             strikeSpreads, volSpreads, swapIndexBase,
                             shortSwapIndexBase,
                             vegaWeightedSmileFit),
      volSpreadsInterpolator_(nStrikes_),
      volSpreadsMatrix_(nStrikes_, Matrix(optionTenors.size(), swapTenors.size(), 0.0)) {
    }
Member Function Documentation
void QuantLib::SwaptionVolCube2::performCalculations () const [virtual]
This method must implement any calculations which must be (re)done in order to calculate the desired results.
set volSpreadsMatrix_ by volSpreads_ quotes
create volSpreadsInterpolator_
Reimplemented from QuantLib::SwaptionVolatilityDiscrete.
Definition at line 45 of file swaptionvolcube2.cpp.
References QuantLib::SwaptionVolatilityDiscrete::nOptionTenors_, QuantLib::SwaptionVolatilityCube::nStrikes_, QuantLib::SwaptionVolatilityDiscrete::nSwapTenors_, QuantLib::SwaptionVolatilityDiscrete::optionTimes_, QuantLib::SwaptionVolatilityDiscrete::swapLengths_, QuantLib::SwaptionVolatilityCube::volSpreads_, volSpreadsInterpolator_, and volSpreadsMatrix_.
{
        SwaptionVolatilityDiscrete::performCalculations();
        for (Size i=0; i<nStrikes_; i++)
            for (Size j=0; j<nOptionTenors_; j++)
                for (Size k=0; k<nSwapTenors_; k++) {
                    volSpreadsMatrix_[i][j][k] =
                        volSpreads_[j*nSwapTenors_+k][i]->value();
                }
        for (Size i=0; i<nStrikes_; i++) {
            volSpreadsInterpolator_[i] = BilinearInterpolation(
                swapLengths_.begin(), swapLengths_.end(),
                optionTimes_.begin(), optionTimes_.end(),
                volSpreadsMatrix_[i]);
            volSpreadsInterpolator_[i].enableExtrapolation();
        }
    }
boost::shared_ptr< SmileSection > QuantLib::SwaptionVolCube2::smileSectionImpl (const Date & optionDate, const Period & swapTenor) const [virtual]
Reimplemented from QuantLib::SwaptionVolatilityStructure.
Definition at line 77 of file swaptionvolcube2.cpp.
References QuantLib::SwaptionVolatilityCube::atmStrike(), QuantLib::SwaptionVolatilityCube::atmVol_, QuantLib::LazyObject::calculate(), QuantLib::SwaptionVolatilityCube::nStrikes_, QuantLib::SwaptionVolatilityCube::strikeSpreads_, QuantLib::SwaptionVolatilityStructure::swapLength(), QuantLib::TermStructure::timeFromReference(), and volSpreadsInterpolator_.
Referenced by smileSectionImpl().
{
        calculate();
        Rate atmForward = atmStrike(optionDate, swapTenor);
        Volatility atmVol = atmVol_->volatility(optionDate,
                                                swapTenor,
                                                atmForward);
        Time optionTime = timeFromReference(optionDate);
        Real exerciseTimeSqrt = std::sqrt(optionTime);
        std::vector<Real> strikes, stdDevs;
        strikes.reserve(nStrikes_);
        stdDevs.reserve(nStrikes_);
        Time length = swapLength(swapTenor);
        for (Size i=0; i<nStrikes_; ++i) {
            strikes.push_back(atmForward + strikeSpreads_[i]);
            stdDevs.push_back(exerciseTimeSqrt*(
                atmVol + volSpreadsInterpolator_[i](length, optionTime)));
        }
        return boost::shared_ptr<SmileSection>(new
            InterpolatedSmileSection<Linear>(optionTime,
                                             strikes,
                                             stdDevs,
                                             atmVol));
    }
boost::shared_ptr< SmileSection > QuantLib::SwaptionVolCube2::smileSectionImpl (Time optionTime, Time swapLength) const [virtual]
Implements QuantLib::SwaptionVolatilityStructure.
Definition at line 66 of file swaptionvolcube2.cpp.
References QuantLib::Months, QuantLib::SwaptionVolatilityDiscrete::optionInterpolator_, and smileSectionImpl().
{
        Date optionDate = Date(static_cast<BigInteger>(
            optionInterpolator_(optionTime)));
        Rounding rounder(0);
        Period swapTenor(static_cast<Integer>(rounder(swapLength*12.0)), Months);
        return smileSectionImpl(optionDate, swapTenor);
    }
const Matrix& QuantLib::SwaptionVolCube2::volSpreads (Size i) const [inline]
Definition at line 61 of file swaptionvolcube2.hpp.
References volSpreadsMatrix_.
{ return volSpreadsMatrix_[i]; }
Member Data Documentation
std::vector<Interpolation2D> QuantLib::SwaptionVolCube2::volSpreadsInterpolator_ [mutable, private]
Definition at line 70 of file swaptionvolcube2.hpp.
Referenced by performCalculations(), and smileSectionImpl().
std::vector<Matrix> QuantLib::SwaptionVolCube2::volSpreadsMatrix_ [mutable, private]
Definition at line 71 of file swaptionvolcube2.hpp.
Referenced by performCalculations(), and volSpreads().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/swaption/swaptionvolcube2.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/swaption/swaptionvolcube2.cpp