QuantLib: QuantLib::Handle< T > Class Template Reference
QuantLib::Handle< T > Class Template Reference
Shared handle to an observable.
#include <handle.hpp>
Classes
class Link
Public Member Functions
const boost::shared_ptr< T > & currentLink () const
dereferencing
const boost::shared_ptr< T > & operator-> () const
const boost::shared_ptr< T > & operator* () const
bool empty () const
checks if the contained shared pointer points to anything
operator boost::shared_ptr< Observable > () const
allows registration as observable
template<class U >
bool operator== (const Handle< U > &other)
equality test
template<class U >
bool operator!= (const Handle< U > &other)
disequality test
template<class U >
bool operator< (const Handle< U > &other)
strict weak ordering
Constructors
Warning:
registerAsObserver is left as a backdoor in case the programmer cannot guarantee that the object pointed to will remain alive for the whole lifetime of the handle---namely, it should be set to false when the passed shared pointer does not own the pointee (this should only happen in a controlled environment, so that the programmer is aware of it). Failure to do so can very likely result in a program crash. If the programmer does want the handle to register as observer of such a shared pointer, it is his responsibility to ensure that the handle gets destroyed before the pointed object does.
Handle (const boost::shared_ptr< T > &p=boost::shared_ptr< T >(), bool registerAsObserver=true)
Handle (T *p, bool registerAsObserver=true)
Protected Attributes
boost::shared_ptr< Link > link_
Detailed Description
template<class T>
class QuantLib::Handle< T >
Shared handle to an observable.
All copies of an instance of this class refer to the same observable by means of a relinkable smart pointer. When such pointer is relinked to another observable, the change will be propagated to all the copies.
Precondition:
Class T must inherit from Observable
Definition at line 41 of file handle.hpp.
Constructor & Destructor Documentation
template<class T> QuantLib::Handle< T >::Handle (const boost::shared_ptr< T > & p = boost::shared_ptr<T>(), bool registerAsObserver = true) [inline, explicit]
Definition at line 75 of file handle.hpp.
        : link_(new Link(p,registerAsObserver)) {}
template<class T> QuantLib::Handle< T >::Handle (T * p, bool registerAsObserver = true) [inline, explicit]
Definition at line 79 of file handle.hpp.
        : link_(new Link(boost::shared_ptr<T>(p),registerAsObserver)) {}
Member Function Documentation
template<class T > const boost::shared_ptr< T > & QuantLib::Handle< T >::currentLink () const [inline]
dereferencing
Definition at line 152 of file handle.hpp.
References QuantLib::Handle< T >::empty(), QuantLib::Handle< T >::link_, and QL_REQUIRE.
Referenced by QuantLib::FdG2SwaptionEngine::calculate(), QuantLib::FdHullWhiteSwaptionEngine::calculate(), QuantLib::FdBatesVanillaEngine::calculate(), QuantLib::FdmHullWhiteSolver::performCalculations(), QuantLib::FdmG2Solver::performCalculations(), QuantLib::FdmExtOUJumpSolver::performCalculations(), QuantLib::FdmSimple2dBSSolver::performCalculations(), QuantLib::Fdm2dBlackScholesSolver::performCalculations(), QuantLib::FdmBlackScholesSolver::performCalculations(), QuantLib::FdmSimple3dExtOUJumpSolver::performCalculations(), QuantLib::FdmSimple2dExtOUSolver::performCalculations(), QuantLib::FdmBatesSolver::performCalculations(), QuantLib::FdmHestonHullWhiteSolver::performCalculations(), QuantLib::FdmKlugeExtOUSolver< N >::performCalculations(), QuantLib::FdmHestonSolver::performCalculations(), anonymous_namespace{inflationvolatility.cpp}::setupPriceSurface(), and FdHestonTest::testFdmHestonBarrierVsBlackScholes().
{
        QL_REQUIRE(!empty(), "empty Handle cannot be dereferenced");
        return link_->currentLink();
    }
template<class T > bool QuantLib::Handle< T >::empty () const [inline]
checks if the contained shared pointer points to anything
Definition at line 170 of file handle.hpp.
References QuantLib::Handle< T >::link_.
Referenced by QuantLib::ContinuousArithmeticAsianLevyEngine::calculate(), QuantLib::DiscountingBondEngine::calculate(), QuantLib::IntegralCdsEngine::calculate(), QuantLib::MidPointCdsEngine::calculate(), QuantLib::DiscountingSwapEngine::calculate(), QuantLib::AnalyticCapFloorEngine::calculate(), QuantLib::TreeCapFloorEngine::calculate(), QuantLib::TreeCallableFixedRateBondEngine::calculate(), QuantLib::TreeVanillaSwapEngine::calculate(), QuantLib::TreeSwaptionEngine::calculate(), QuantLib::FuturesRateHelper::convexityAdjustment(), QuantLib::CPICapFloorTermPriceSurface::CPICapFloorTermPriceSurface(), QuantLib::CPICouponPricer::CPICouponPricer(), QuantLib::Handle< T >::currentLink(), QuantLib::BMAIndex::forecastFixing(), QuantLib::IborIndex::forecastFixing(), QuantLib::FuturesRateHelper::impliedQuote(), QuantLib::AssetSwapHelper::impliedQuote(), QuantLib::SwapRateHelper::impliedQuote(), QuantLib::ForwardSwapQuote::isValid(), QuantLib::EurodollarFuturesImpliedStdDevQuote::isValid(), QuantLib::ImpliedStdDevQuote::isValid(), QuantLib::FuturesConvAdjustmentQuote::isValid(), QuantLib::DeltaVolQuote::isValid(), QuantLib::Handle< T >::operator*(), QuantLib::Handle< T >::operator->(), QuantLib::Stock::performCalculations(), QuantLib::ForwardSwapQuote::performCalculations(), QuantLib::FdmBatesSolver::performCalculations(), QuantLib::FdmHestonSolver::performCalculations(), QuantLib::NthToDefault::performCalculations(), QuantLib::Forward::performCalculations(), QuantLib::CDO::performCalculations(), QuantLib::InterpolatedCPICapFloorTermPriceSurface< Interpolator2D >::performCalculations(), QuantLib::CPICouponPricer::setCapletVolatility(), QuantLib::YoYInflationCouponPricer::setCapletVolatility(), QuantLib::SwapRateHelper::setTermStructure(), QuantLib::YoYInflationCapFloorEngine::setVolatility(), QuantLib::SwapRateHelper::spread(), QuantLib::anonymous_namespace{overnightindexedcoupon.cpp}::OvernightIndexedCouponPricer::swapletRate(), QuantLib::SwaptionVolatilityCube::SwaptionVolatilityCube(), QuantLib::SyntheticCDO::arguments::validate(), and QuantLib::YoYInflationCouponPricer::YoYInflationCouponPricer().
{
        return link_->empty();
    }
template<class T > QuantLib::Handle< T >::operator boost::shared_ptr< Observable > () const [inline]
allows registration as observable
Definition at line 175 of file handle.hpp.
References QuantLib::Handle< T >::link_.
{
        return link_;
    }
template<class T> template<class U > bool QuantLib::Handle< T >::operator!= (const Handle< U > & other) [inline]
disequality test
Definition at line 97 of file handle.hpp.
{ return link_!=other.link_; }
template<class T > const boost::shared_ptr< T > & QuantLib::Handle< T >::operator* () const [inline]
Definition at line 164 of file handle.hpp.
References QuantLib::Handle< T >::empty(), QuantLib::Handle< T >::link_, and QL_REQUIRE.
{
        QL_REQUIRE(!empty(), "empty Handle cannot be dereferenced");
        return link_->currentLink();
    }
template<class T > const boost::shared_ptr< T > & QuantLib::Handle< T >::operator-> () const [inline]
Definition at line 158 of file handle.hpp.
References QuantLib::Handle< T >::empty(), QuantLib::Handle< T >::link_, and QL_REQUIRE.
{
        QL_REQUIRE(!empty(), "empty Handle cannot be dereferenced");
        return link_->currentLink();
    }
template<class T> template<class U > bool QuantLib::Handle< T >::operator< (const Handle< U > & other) [inline]
strict weak ordering
Definition at line 100 of file handle.hpp.
{ return link_ < other.link_; }
template<class T> template<class U > bool QuantLib::Handle< T >::operator== (const Handle< U > & other) [inline]
equality test
Definition at line 94 of file handle.hpp.
{ return link_==other.link_; }
Member Data Documentation
template<class T> boost::shared_ptr<Link> QuantLib::Handle< T >::link_ [protected]
Definition at line 56 of file handle.hpp.
Referenced by QuantLib::Handle< T >::currentLink(), QuantLib::Handle< T >::empty(), QuantLib::Handle< T >::operator boost::shared_ptr< Observable >(), QuantLib::Handle< HestonModel >::operator!=(), QuantLib::Handle< T >::operator*(), QuantLib::Handle< T >::operator->(), QuantLib::Handle< HestonModel >::operator<(), and QuantLib::Handle< HestonModel >::operator==().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/handle.hpp