QuantLib: QuantLib::FdmG2Op Class Reference
QuantLib::FdmG2Op Class Reference
#include <fdmg2op.hpp>
Public Member Functions
FdmG2Op (const boost::shared_ptr< FdmMesher > &mesher, const boost::shared_ptr< G2 > &model, Size direction1, Size direction2)
Size size () const
void setTime (Time t1, Time t2)
Time \(t1 <= t2\) is required.
Disposable< Array > apply (const Array &r) const
Disposable< Array > apply_mixed (const Array &r) const
Disposable< Array > apply_direction (Size direction, const Array &r) const
Disposable< Array > solve_splitting (Size direction, const Array &r, Real s) const
Disposable< Array > preconditioner (const Array &r, Real s) const
Disposable< SparseMatrix > toMatrix () const
Private Attributes
const Size direction1_
const Size direction2_
const Array x_
const Array y_
const TripleBandLinearOp dxMap_
const TripleBandLinearOp dyMap_
NinePointLinearOp corrMap_
TripleBandLinearOp mapX_
TripleBandLinearOp mapY_
const boost::shared_ptr< G2 > model_
Detailed Description
Definition at line 36 of file fdmg2op.hpp.
Constructor & Destructor Documentation
QuantLib::FdmG2Op::FdmG2Op (const boost::shared_ptr< FdmMesher > & mesher, const boost::shared_ptr< G2 > & model, Size direction1, Size direction2)
Definition at line 34 of file fdmg2op.cpp.
    : direction1_(direction1),
      direction2_(direction2),
      x_(mesher->locations(direction1)),
      y_(mesher->locations(direction2)),
      dxMap_(FirstDerivativeOp(direction1, mesher).mult(-x_*model->a()).add(
                SecondDerivativeOp(direction1, mesher)
                    .mult(0.5*model->sigma()*model->sigma()
                          *Array(mesher->layout()->size(), 1.0)))),
      dyMap_(FirstDerivativeOp(direction2, mesher).mult(-y_*model->b()).add(
                SecondDerivativeOp(direction2, mesher)
                    .mult(0.5*model->eta()*model->eta()
                          *Array(mesher->layout()->size(), 1.0)))),
      corrMap_(SecondOrderMixedDerivativeOp(direction1, direction2, mesher)
              .mult(Array(mesher->layout()->size(),
                          model->rho()*model->sigma()*model->eta()))),
      mapX_(direction1, mesher),
      mapY_(direction2, mesher),
      model_(model) {
    }
Member Function Documentation
Disposable< Array > QuantLib::FdmG2Op::apply (const Array & r) const [virtual]
Implements QuantLib::FdmLinearOp.
Definition at line 75 of file fdmg2op.cpp.
References QuantLib::TripleBandLinearOp::apply(), apply_mixed(), mapX_, and mapY_.
{
        return mapX_.apply(r) + mapY_.apply(r) + apply_mixed(r);
    }
Disposable< Array > QuantLib::FdmG2Op::apply_direction (Size direction, const Array & r) const [virtual]
Implements QuantLib::FdmLinearOpComposite.
Definition at line 84 of file fdmg2op.cpp.
References QuantLib::TripleBandLinearOp::apply(), direction1_, direction2_, mapX_, mapY_, and QuantLib::Array::size().
{
        if (direction == direction1_) {
            return mapX_.apply(r);
        }
        else if (direction == direction2_) {
            return mapY_.apply(r);
        }
        else {
            Array retVal(r.size(), 0.0);
            return retVal;
        }
    }
Disposable< Array > QuantLib::FdmG2Op::apply_mixed (const Array & r) const [virtual]
Implements QuantLib::FdmLinearOpComposite.
Definition at line 79 of file fdmg2op.cpp.
References QuantLib::NinePointLinearOp::apply(), and corrMap_.
Referenced by apply().
{
        return corrMap_.apply(r);
    }
Disposable< Array > QuantLib::FdmG2Op::preconditioner (const Array & r, Real s) const [virtual]
Implements QuantLib::FdmLinearOpComposite.
Definition at line 112 of file fdmg2op.cpp.
References direction1_, and solve_splitting().
{
        return solve_splitting(direction1_, r, dt);
    }
void QuantLib::FdmG2Op::setTime (Time t1, Time t2) [virtual]
Time \(t1 <= t2\) is required.
Implements QuantLib::FdmLinearOpComposite.
Definition at line 62 of file fdmg2op.cpp.
References QuantLib::TripleBandLinearOp::axpyb(), dxMap_, dyMap_, mapX_, mapY_, model_, QuantLib::anonymous_namespace{bjerksundstenslandengine.cpp}::phi(), x_, and y_.
{
        const boost::shared_ptr<TwoFactorModel::ShortRateDynamics> dynamics =
            model_->dynamics();
        const Real phi = 0.5*(  dynamics->shortRate(t1, 0.0, 0.0)
                              + dynamics->shortRate(t2, 0.0, 0.0));
        const Array hr = -0.5*(x_ + y_ + phi);
        mapX_.axpyb(Array(), dxMap_, dxMap_, hr);
        mapY_.axpyb(Array(), dyMap_, dyMap_, hr);
    }
Size QuantLib::FdmG2Op::size () const [virtual]
Implements QuantLib::FdmLinearOpComposite.
Definition at line 58 of file fdmg2op.cpp.
{
        return 2u;
    }
Disposable< Array > QuantLib::FdmG2Op::solve_splitting (Size direction, const Array & r, Real s) const [virtual]
Implements QuantLib::FdmLinearOpComposite.
Definition at line 98 of file fdmg2op.cpp.
References direction1_, direction2_, mapX_, mapY_, QuantLib::Array::size(), and QuantLib::TripleBandLinearOp::solve_splitting().
Referenced by preconditioner().
{
        if (direction == direction1_) {
            return mapX_.solve_splitting(r, a, 1.0);
        }
        else if (direction == direction2_) {
            return mapY_.solve_splitting(r, a, 1.0);
        }
        else {
            Array retVal(r.size(), 0.0);
            return retVal;
        }
    }
Disposable< SparseMatrix > QuantLib::FdmG2Op::toMatrix () const [virtual]
Reimplemented from QuantLib::FdmLinearOp.
Definition at line 117 of file fdmg2op.cpp.
References corrMap_, mapX_, mapY_, QuantLib::NinePointLinearOp::toMatrix(), and QuantLib::TripleBandLinearOp::toMatrix().
{
        SparseMatrix retVal =
            mapX_.toMatrix() + mapY_.toMatrix() + corrMap_.toMatrix();
        return retVal;
    }
Member Data Documentation
NinePointLinearOp QuantLib::FdmG2Op::corrMap_ [private]
Definition at line 62 of file fdmg2op.hpp.
Referenced by apply_mixed(), and toMatrix().
const Size QuantLib::FdmG2Op::direction1_ [private]
Definition at line 58 of file fdmg2op.hpp.
Referenced by apply_direction(), preconditioner(), and solve_splitting().
const Size QuantLib::FdmG2Op::direction2_ [private]
Definition at line 58 of file fdmg2op.hpp.
Referenced by apply_direction(), and solve_splitting().
const TripleBandLinearOp QuantLib::FdmG2Op::dxMap_ [private]
Definition at line 60 of file fdmg2op.hpp.
Referenced by setTime().
const TripleBandLinearOp QuantLib::FdmG2Op::dyMap_ [private]
Definition at line 60 of file fdmg2op.hpp.
Referenced by setTime().
TripleBandLinearOp QuantLib::FdmG2Op::mapX_ [private]
Definition at line 63 of file fdmg2op.hpp.
Referenced by apply(), apply_direction(), setTime(), solve_splitting(), and toMatrix().
TripleBandLinearOp QuantLib::FdmG2Op::mapY_ [private]
Definition at line 63 of file fdmg2op.hpp.
Referenced by apply(), apply_direction(), setTime(), solve_splitting(), and toMatrix().
const boost::shared_ptr<G2> QuantLib::FdmG2Op::model_ [private]
Definition at line 65 of file fdmg2op.hpp.
Referenced by setTime().
const Array QuantLib::FdmG2Op::x_ [private]
Definition at line 59 of file fdmg2op.hpp.
Referenced by setTime().
const Array QuantLib::FdmG2Op::y_ [private]
Definition at line 59 of file fdmg2op.hpp.
Referenced by setTime().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/operators/fdmg2op.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/operators/fdmg2op.cpp