QuantLib: QuantLib::ProjectedCostFunction Class Reference
QuantLib::ProjectedCostFunction Class Reference
Parameterized cost function.
#include <projectedcostfunction.hpp>
Public Member Functions
ProjectedCostFunction (const CostFunction &costFunction, const Array &parametersValues, const std::vector< bool > &parametersFreedoms)
virtual Disposable< Array > project (const Array &parameters) const
returns the subset of free parameters corresponding
virtual Disposable< Array > include (const Array &projectedParameters) const
returns whole set of parameters corresponding to the set
CostFunction interface
virtual Real value (const Array &freeParameters) const
method to overload to compute the cost function value in x
virtual Disposable< Array > values (const Array &freeParameters) const
method to overload to compute the cost function values in x
Private Member Functions
void mapFreeParameters (const Array &parametersValues) const
Private Attributes
Size numberOfFreeParameters_
const Array fixedParameters_
Array actualParameters_
const std::vector< bool > & parametersFreedoms_
const CostFunction & costFunction_
Detailed Description
Parameterized cost function.
This class creates a proxy cost function which can depend on any arbitrary subset of parameters (the other being fixed)
Definition at line 37 of file projectedcostfunction.hpp.
Constructor & Destructor Documentation
QuantLib::ProjectedCostFunction::ProjectedCostFunction (const CostFunction & costFunction, const Array & parametersValues, const std::vector< bool > & parametersFreedoms)
Definition at line 25 of file projectedcostfunction.cpp.
References fixedParameters_, numberOfFreeParameters_, parametersFreedoms_, QL_REQUIRE, and QuantLib::Array::size().
    :numberOfFreeParameters_(0),
     fixedParameters_(parametersValues),
     actualParameters_(parametersValues),
     parametersFreedoms_(parametersFreedoms),
     costFunction_(costFunction){
         QL_REQUIRE(fixedParameters_.size()==parametersFreedoms_.size(),
             "fixedParameters_.size()!=parametersFreedoms_.size()");
         for (Size i=0; i<parametersFreedoms_.size(); i++)
            if(!parametersFreedoms_[i]) numberOfFreeParameters_++;
         QL_REQUIRE(numberOfFreeParameters_>0,"numberOfFreeParameters==0");
    }
Member Function Documentation
Disposable< Array > QuantLib::ProjectedCostFunction::include (const Array & projectedParameters) const [virtual]
returns whole set of parameters corresponding to the set
Definition at line 75 of file projectedcostfunction.cpp.
References fixedParameters_, numberOfFreeParameters_, parametersFreedoms_, QL_REQUIRE, and QuantLib::Array::size().
{
        QL_REQUIRE(projectedParameters.size()==numberOfFreeParameters_,
                   "projectedParameters.size()!=numberOfFreeParameters");
        Array y(fixedParameters_);
        Size i = 0;
        for (Size j=0; j<y.size(); j++)
            if(!parametersFreedoms_[j])
                y[j] = projectedParameters[i++];
        return y;
    }
void QuantLib::ProjectedCostFunction::mapFreeParameters (const Array & parametersValues) const [private]
Definition at line 43 of file projectedcostfunction.cpp.
References QL_REQUIRE, and QuantLib::Array::size().
Referenced by value(), and values().
{
        QL_REQUIRE(parametersValues.size()==numberOfFreeParameters_,
                   "parametersValues.size()!=numberOfFreeParameters");
        Size i = 0;
        for (Size j=0; j<actualParameters_.size(); j++)
            if(!parametersFreedoms_[j])
                actualParameters_[j] = parametersValues[i++];
    }
Disposable< Array > QuantLib::ProjectedCostFunction::project (const Array & parameters) const [virtual]
returns the subset of free parameters corresponding
Definition at line 64 of file projectedcostfunction.cpp.
References QL_REQUIRE, and QuantLib::Array::size().
{
        QL_REQUIRE(parameters.size()==parametersFreedoms_.size(),
            "parameters.size()!=parametersFreedoms_.size()");
        Array projectedParameters(numberOfFreeParameters_);
        Size i = 0;
        for (Size j=0; j<parametersFreedoms_.size(); j++)
            if(!parametersFreedoms_[j])
                projectedParameters[i++] = parameters[j];
        return projectedParameters;
    }
Real QuantLib::ProjectedCostFunction::value (const Array & x) const [virtual]
method to overload to compute the cost function value in x
Implements QuantLib::CostFunction.
Definition at line 52 of file projectedcostfunction.cpp.
References actualParameters_, costFunction_, mapFreeParameters(), and QuantLib::CostFunction::value().
{
        mapFreeParameters(freeParameters);
        return costFunction_.value(actualParameters_);
    }
Disposable< Array > QuantLib::ProjectedCostFunction::values (const Array & x) const [virtual]
method to overload to compute the cost function values in x
Implements QuantLib::CostFunction.
Definition at line 57 of file projectedcostfunction.cpp.
References actualParameters_, costFunction_, mapFreeParameters(), and QuantLib::CostFunction::values().
{
        mapFreeParameters(freeParameters);
        return costFunction_.values(actualParameters_);
    }
Member Data Documentation
Array QuantLib::ProjectedCostFunction::actualParameters_ [mutable, private]
Definition at line 63 of file projectedcostfunction.hpp.
Referenced by value(), and values().
const CostFunction& QuantLib::ProjectedCostFunction::costFunction_ [private]
Definition at line 65 of file projectedcostfunction.hpp.
Referenced by value(), and values().
const Array QuantLib::ProjectedCostFunction::fixedParameters_ [private]
Definition at line 62 of file projectedcostfunction.hpp.
Referenced by include(), and ProjectedCostFunction().
Size QuantLib::ProjectedCostFunction::numberOfFreeParameters_ [private]
Definition at line 61 of file projectedcostfunction.hpp.
Referenced by include(), and ProjectedCostFunction().
const std::vector<bool>& QuantLib::ProjectedCostFunction::parametersFreedoms_ [private]
Definition at line 64 of file projectedcostfunction.hpp.
Referenced by include(), and ProjectedCostFunction().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/optimization/projectedcostfunction.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/math/optimization/projectedcostfunction.cpp