QuantLib: QuantLib::ArithmeticASOPathPricer Class Reference
QuantLib::ArithmeticASOPathPricer Class Reference
#include <mc_discr_arith_av_strike.hpp>
Public Member Functions
ArithmeticASOPathPricer (Option::Type type, DiscountFactor discount, Real runningSum=0.0, Size pastFixings=0)
Real operator() (const Path &path) const
Private Attributes
Option::Type type_
DiscountFactor discount_
Real runningSum_
Size pastFixings_
Detailed Description
Definition at line 59 of file mc_discr_arith_av_strike.hpp.
Constructor & Destructor Documentation
QuantLib::ArithmeticASOPathPricer::ArithmeticASOPathPricer (Option::Type type, DiscountFactor discount, Real runningSum = 0.0, Size pastFixings = 0)
Definition at line 24 of file mc_discr_arith_av_strike.cpp.
    : type_(type), discount_(discount),
      runningSum_(runningSum), pastFixings_(pastFixings) {}
Member Function Documentation
Real QuantLib::ArithmeticASOPathPricer::operator() (const Path & path) const [virtual]
Implements QuantLib::PathPricer< Path >.
Definition at line 32 of file mc_discr_arith_av_strike.cpp.
References QuantLib::Path::back(), QuantLib::Path::begin(), discount_, QuantLib::Path::end(), QuantLib::Path::length(), QuantLib::TimeGrid::mandatoryTimes(), pastFixings_, QL_REQUIRE, runningSum_, QuantLib::Path::timeGrid(), and type_.
{
        Size n = path.length();
        QL_REQUIRE(n > 1, "the path cannot be empty");
        Real averageStrike;
        if (path.timeGrid().mandatoryTimes()[0]==0.0) {
            // include initial fixing
            averageStrike =
                std::accumulate(path.begin(),path.end(),runningSum_) /
                (pastFixings_ + n);
        } else {
            averageStrike =
                std::accumulate(path.begin()+1,path.end(),runningSum_) /
                (pastFixings_ + n - 1);
        }
        return discount_
            * PlainVanillaPayoff(type_, averageStrike)(path.back());
    }
Member Data Documentation
DiscountFactor QuantLib::ArithmeticASOPathPricer::discount_ [private]
Definition at line 68 of file mc_discr_arith_av_strike.hpp.
Referenced by operator()().
Size QuantLib::ArithmeticASOPathPricer::pastFixings_ [private]
Definition at line 70 of file mc_discr_arith_av_strike.hpp.
Referenced by operator()().
Real QuantLib::ArithmeticASOPathPricer::runningSum_ [private]
Definition at line 69 of file mc_discr_arith_av_strike.hpp.
Referenced by operator()().
Option::Type QuantLib::ArithmeticASOPathPricer::type_ [private]
Definition at line 67 of file mc_discr_arith_av_strike.hpp.
Referenced by operator()().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/asian/mc_discr_arith_av_strike.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/asian/mc_discr_arith_av_strike.cpp