QuantLib: QuantLib::KlugeExtOUProcess Class Reference
QuantLib::KlugeExtOUProcess Class Reference
#include <klugeextouprocess.hpp>
Public Member Functions
KlugeExtOUProcess (Real rho, const boost::shared_ptr< ExtOUWithJumpsProcess > &kluge, const boost::shared_ptr< ExtendedOrnsteinUhlenbeckProcess > &extOU)
Size size () const
returns the number of dimensions of the stochastic process
Size factors () const
returns the number of independent factors of the process
Disposable< Array > initialValues () const
returns the initial values of the state variables
Disposable< Array > drift (Time t, const Array &x) const
returns the drift part of the equation, i.e., \(\mu(t, \mathrm{x}_t) \)
Disposable< Matrix > diffusion (Time t, const Array &x) const
returns the diffusion part of the equation, i.e. \(\sigma(t, \mathrm{x}_t) \)
Disposable< Array > evolve (Time t0, const Array &x0, Time dt, const Array &dw) const
boost::shared_ptr
< ExtOUWithJumpsProcess > getKlugeProcess () const
boost::shared_ptr
< ExtendedOrnsteinUhlenbeckProcess > getExtOUProcess () const
Real rho () const
Private Attributes
const Real rho_
const Real sqrtMRho_
const boost::shared_ptr
< ExtOUWithJumpsProcess > klugeProcess_
const boost::shared_ptr
< ExtendedOrnsteinUhlenbeckProcess > ouProcess_
Detailed Description
This class describes a correlated Kluge - extended Ornstein-Uhlenbeck process governed by
\[ \begin{array}{rcl} P_t &=& \exp(p_t + X_t + Y_t) \\ dX_t &=& -\alpha X_tdt + \sigma_x dW_t^x \\ dY_t &=& -\beta Y_{t-}dt + J_tdN_t \\ \omega(J) &=& \eta e^{-\eta J} \\ G_t &=& \exp(g_t + U_t) \\ dU_t &=& -\kappa U_tdt + \sigma_udW_t^u \\ \rho &=& \mathrm{corr} (dW_t^x, dW_t^u) \end{array} \]
References: B. Hambly, S. Howison, T. Kluge, Modelling spikes and pricing swing options in electricity markets, http://people.maths.ox.ac.uk/hambly/PDF/Papers/elec.pdf
Definition at line 56 of file klugeextouprocess.hpp.
Constructor & Destructor Documentation
QuantLib::KlugeExtOUProcess::KlugeExtOUProcess (Real rho, const boost::shared_ptr< ExtOUWithJumpsProcess > & kluge, const boost::shared_ptr< ExtendedOrnsteinUhlenbeckProcess > & extOU)
Definition at line 27 of file klugeextouprocess.cpp.
    : rho_         (rho),
      sqrtMRho_    (std::sqrt(1-rho*rho)),
      klugeProcess_(klugeProcess),
      ouProcess_   (ouProcess) {
    }
Member Function Documentation
Disposable< Matrix > QuantLib::KlugeExtOUProcess::diffusion (Time t, const Array & x) const [virtual]
returns the diffusion part of the equation, i.e. \(\sigma(t, \mathrm{x}_t) \)
Implements QuantLib::StochasticProcess.
Definition at line 63 of file klugeextouprocess.cpp.
References QuantLib::Array::back(), factors(), klugeProcess_, ouProcess_, rho_, size(), and sqrtMRho_.
             {
        Matrix retVal(size(), factors(), 0.0);
        Volatility vol = ouProcess_->diffusion(t, x.back());
        retVal[0][0]              = klugeProcess_->diffusion(t, x)[0][0];
        retVal[size()][0]         = rho_*vol;
        retVal[size()][factors()] = sqrtMRho_*vol;
        return retVal;
    }
Disposable< Array > QuantLib::KlugeExtOUProcess::drift (Time t, const Array & x) const [virtual]
returns the drift part of the equation, i.e., \(\mu(t, \mathrm{x}_t) \)
Implements QuantLib::StochasticProcess.
Definition at line 54 of file klugeextouprocess.cpp.
References QuantLib::Array::back(), QuantLib::Array::begin(), QuantLib::Array::end(), klugeProcess_, ouProcess_, and size().
{
        Array retVal(size());
        Array mu = klugeProcess_->drift(t, x);
        std::copy(mu.begin(), mu.end(), retVal.begin());
        retVal.back() = ouProcess_->drift(t, x.back());
        return retVal;
    }
Disposable< Array > QuantLib::KlugeExtOUProcess::evolve (Time t0, const Array & x0, Time dt, const Array & dw) const [virtual]
returns the asset value after a time interval \(\Delta t \) according to the given discretization. By default, it returns
\[ E(\mathrm{x}_0,t_0,\Delta t) + S(\mathrm{x}_0,t_0,\Delta t) \cdot \Delta \mathrm{w} \]
where \(E \) is the expectation and \(S \) the standard deviation.
Reimplemented from QuantLib::StochasticProcess.
Definition at line 76 of file klugeextouprocess.cpp.
References QuantLib::Array::back(), QuantLib::Array::begin(), QuantLib::anonymous_namespace{yieldtermstructure.cpp}::dt, QuantLib::Array::end(), QuantLib::Array::front(), klugeProcess_, ouProcess_, rho_, size(), and sqrtMRho_.
{
        Array retVal(size());
        Array ev = klugeProcess_->evolve(t0, x0, dt, dw);
        std::copy(ev.begin(), ev.end(), retVal.begin());
        const Real dz = dw.back()*sqrtMRho_ + dw.front()*rho_;
        retVal.back() = ouProcess_->evolve(t0, x0.back(), dt, dz);
        return retVal;
    }
Size QuantLib::KlugeExtOUProcess::factors () const [virtual]
returns the number of independent factors of the process
Reimplemented from QuantLib::StochasticProcess.
Definition at line 41 of file klugeextouprocess.cpp.
References klugeProcess_.
Referenced by diffusion().
{
        return klugeProcess_->factors() + 1;
    }
boost::shared_ptr< ExtendedOrnsteinUhlenbeckProcess > QuantLib::KlugeExtOUProcess::getExtOUProcess () const
Definition at line 94 of file klugeextouprocess.cpp.
References ouProcess_.
{
        return ouProcess_;
    }
boost::shared_ptr< ExtOUWithJumpsProcess > QuantLib::KlugeExtOUProcess::getKlugeProcess () const
Definition at line 90 of file klugeextouprocess.cpp.
References klugeProcess_.
{
        return klugeProcess_;
    }
Disposable< Array > QuantLib::KlugeExtOUProcess::initialValues () const [virtual]
returns the initial values of the state variables
Implements QuantLib::StochasticProcess.
Definition at line 45 of file klugeextouprocess.cpp.
References QuantLib::Array::back(), QuantLib::Array::begin(), QuantLib::Array::end(), klugeProcess_, ouProcess_, and size().
{
        Array retVal(size());
        const Array x0 = klugeProcess_->initialValues();
        std::copy(x0.begin(), x0.end(), retVal.begin());
        retVal.back() = ouProcess_->x0();
        return retVal;
    }
Real QuantLib::KlugeExtOUProcess::rho () const
Definition at line 98 of file klugeextouprocess.cpp.
References rho_.
{
        return rho_;
    }
Size QuantLib::KlugeExtOUProcess::size () const [virtual]
returns the number of dimensions of the stochastic process
Implements QuantLib::StochasticProcess.
Definition at line 37 of file klugeextouprocess.cpp.
References klugeProcess_.
Referenced by diffusion(), drift(), evolve(), and initialValues().
{
        return klugeProcess_->size() + 1;
    }
Member Data Documentation
const boost::shared_ptr<ExtOUWithJumpsProcess> QuantLib::KlugeExtOUProcess::klugeProcess_ [private]
Definition at line 80 of file klugeextouprocess.hpp.
Referenced by diffusion(), drift(), evolve(), factors(), getKlugeProcess(), initialValues(), and size().
const boost::shared_ptr<ExtendedOrnsteinUhlenbeckProcess> QuantLib::KlugeExtOUProcess::ouProcess_ [private]
Definition at line 81 of file klugeextouprocess.hpp.
Referenced by diffusion(), drift(), evolve(), getExtOUProcess(), and initialValues().
const Real QuantLib::KlugeExtOUProcess::rho_ [private]
Definition at line 79 of file klugeextouprocess.hpp.
Referenced by diffusion(), evolve(), and rho().
const Real QuantLib::KlugeExtOUProcess::sqrtMRho_ [private]
Definition at line 79 of file klugeextouprocess.hpp.
Referenced by diffusion(), and evolve().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/processes/klugeextouprocess.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/processes/klugeextouprocess.cpp