QuantLib: QuantLib::CashFlows Class Reference
QuantLib::CashFlows Class Reference
cashflow-analysis functions
#include <cashflows.hpp>
Static Public Member Functions
Date functions
static Date startDate (const Leg &leg)
static Date maturityDate (const Leg &leg)
static bool isExpired (const Leg &leg, bool includeSettlementDateFlows, Date settlementDate=Date())
CashFlow functions
static Leg::const_reverse_iterator previousCashFlow (const Leg &leg, bool includeSettlementDateFlows, Date settlementDate=Date())
the last cashflow paying before or at the given date
static Leg::const_iterator nextCashFlow (const Leg &leg, bool includeSettlementDateFlows, Date settlementDate=Date())
the first cashflow paying after the given date
static Date previousCashFlowDate (const Leg &leg, bool includeSettlementDateFlows, Date settlementDate=Date())
static Date nextCashFlowDate (const Leg &leg, bool includeSettlementDateFlows, Date settlementDate=Date())
static Real previousCashFlowAmount (const Leg &leg, bool includeSettlementDateFlows, Date settlementDate=Date())
static Real nextCashFlowAmount (const Leg &leg, bool includeSettlementDateFlows, Date settlementDate=Date())
Coupon inspectors
static Rate previousCouponRate (const Leg &leg, bool includeSettlementDateFlows, Date settlementDate=Date())
static Rate nextCouponRate (const Leg &leg, bool includeSettlementDateFlows, Date settlementDate=Date())
static Real nominal (const Leg &leg, bool includeSettlementDateFlows, Date settlDate=Date())
static Date accrualStartDate (const Leg &leg, bool includeSettlementDateFlows, Date settlDate=Date())
static Date accrualEndDate (const Leg &leg, bool includeSettlementDateFlows, Date settlementDate=Date())
static Date referencePeriodStart (const Leg &leg, bool includeSettlementDateFlows, Date settlDate=Date())
static Date referencePeriodEnd (const Leg &leg, bool includeSettlementDateFlows, Date settlDate=Date())
static Time accrualPeriod (const Leg &leg, bool includeSettlementDateFlows, Date settlementDate=Date())
static BigInteger accrualDays (const Leg &leg, bool includeSettlementDateFlows, Date settlementDate=Date())
static Time accruedPeriod (const Leg &leg, bool includeSettlementDateFlows, Date settlementDate=Date())
static BigInteger accruedDays (const Leg &leg, bool includeSettlementDateFlows, Date settlementDate=Date())
static Real accruedAmount (const Leg &leg, bool includeSettlementDateFlows, Date settlementDate=Date())
YieldTermStructure functions
static Real npv (const Leg &leg, const YieldTermStructure &discountCurve, bool includeSettlementDateFlows, Date settlementDate=Date(), Date npvDate=Date())
NPV of the cash flows.
static Real bps (const Leg &leg, const YieldTermStructure &discountCurve, bool includeSettlementDateFlows, Date settlementDate=Date(), Date npvDate=Date())
Basis-point sensitivity of the cash flows.
static void npvbps (const Leg &leg, const YieldTermStructure &discountCurve, bool includeSettlementDateFlows, Date settlementDate, Date npvDate, Real &npv, Real &bps)
NPV and BPS of the cash flows.
static Rate atmRate (const Leg &leg, const YieldTermStructure &discountCurve, bool includeSettlementDateFlows, Date settlementDate=Date(), Date npvDate=Date(), Real npv=Null< Real >())
At-the-money rate of the cash flows.
Yield (a.k.a. Internal Rate of Return, i.e. IRR) functions
static Real npv (const Leg &leg, const InterestRate &yield, bool includeSettlementDateFlows, Date settlementDate=Date(), Date npvDate=Date())
NPV of the cash flows.
static Real npv (const Leg &leg, Rate yield, const DayCounter &dayCounter, Compounding compounding, Frequency frequency, bool includeSettlementDateFlows, Date settlementDate=Date(), Date npvDate=Date())
static Real bps (const Leg &leg, const InterestRate &yield, bool includeSettlementDateFlows, Date settlementDate=Date(), Date npvDate=Date())
Basis-point sensitivity of the cash flows.
static Real bps (const Leg &leg, Rate yield, const DayCounter &dayCounter, Compounding compounding, Frequency frequency, bool includeSettlementDateFlows, Date settlementDate=Date(), Date npvDate=Date())
static Rate yield (const Leg &leg, Real npv, const DayCounter &dayCounter, Compounding compounding, Frequency frequency, bool includeSettlementDateFlows, Date settlementDate=Date(), Date npvDate=Date(), Real accuracy=1.0e-10, Size maxIterations=100, Rate guess=0.05)
Implied internal rate of return.
static Time duration (const Leg &leg, const InterestRate &yield, Duration::Type type, bool includeSettlementDateFlows, Date settlementDate=Date(), Date npvDate=Date())
Cash-flow duration.
static Time duration (const Leg &leg, Rate yield, const DayCounter &dayCounter, Compounding compounding, Frequency frequency, Duration::Type type, bool includeSettlementDateFlows, Date settlementDate=Date(), Date npvDate=Date())
static Real convexity (const Leg &leg, const InterestRate &yield, bool includeSettlementDateFlows, Date settlementDate=Date(), Date npvDate=Date())
Cash-flow convexity.
static Real convexity (const Leg &leg, Rate yield, const DayCounter &dayCounter, Compounding compounding, Frequency frequency, bool includeSettlementDateFlows, Date settlementDate=Date(), Date npvDate=Date())
static Real basisPointValue (const Leg &leg, const InterestRate &yield, bool includeSettlementDateFlows, Date settlementDate=Date(), Date npvDate=Date())
Basis-point value.
static Real basisPointValue (const Leg &leg, Rate yield, const DayCounter &dayCounter, Compounding compounding, Frequency frequency, bool includeSettlementDateFlows, Date settlementDate=Date(), Date npvDate=Date())
static Real yieldValueBasisPoint (const Leg &leg, const InterestRate &yield, bool includeSettlementDateFlows, Date settlementDate=Date(), Date npvDate=Date())
Yield value of a basis point.
static Real yieldValueBasisPoint (const Leg &leg, Rate yield, const DayCounter &dayCounter, Compounding compounding, Frequency frequency, bool includeSettlementDateFlows, Date settlementDate=Date(), Date npvDate=Date())
Z-spread functions
static Real npv (const Leg &leg, const boost::shared_ptr< YieldTermStructure > &discount, Spread zSpread, const DayCounter &dayCounter, Compounding compounding, Frequency frequency, bool includeSettlementDateFlows, Date settlementDate=Date(), Date npvDate=Date())
NPV of the cash flows.
static Spread zSpread (const Leg &leg, Real npv, const boost::shared_ptr< YieldTermStructure > &, const DayCounter &dayCounter, Compounding compounding, Frequency frequency, bool includeSettlementDateFlows, Date settlementDate=Date(), Date npvDate=Date(), Real accuracy=1.0e-10, Size maxIterations=100, Rate guess=0.0)
implied Z-spread.
static Spread zSpread (const Leg &leg, const boost::shared_ptr< YieldTermStructure > &d, Real npv, const DayCounter &dayCounter, Compounding compounding, Frequency frequency, bool includeSettlementDateFlows, Date settlementDate=Date(), Date npvDate=Date(), Real accuracy=1.0e-10, Size maxIterations=100, Rate guess=0.0)
deprecated implied Z-spread.
Private Member Functions
CashFlows ()
CashFlows (const CashFlows &)
Detailed Description
cashflow-analysis functions
Todo:
add tests
Definition at line 41 of file cashflows.hpp.
Constructor & Destructor Documentation
QuantLib::CashFlows::CashFlows () [private]
QuantLib::CashFlows::CashFlows (const CashFlows &) [private]
Member Function Documentation
BigInteger QuantLib::CashFlows::accrualDays (const Leg & leg, bool includeSettlementDateFlows, Date settlementDate = Date()) [static]
Definition at line 335 of file cashflows.cpp.
References QuantLib::Coupon::accrualDays(), and nextCashFlow().
{
        Leg::const_iterator cf = nextCashFlow(leg,
                                              includeSettlementDateFlows,
                                              settlementDate);
        if (cf==leg.end()) return 0;
        Date paymentDate = (*cf)->date();
        for (; cf<leg.end() && (*cf)->date()==paymentDate; ++cf) {
            shared_ptr<Coupon> cp = dynamic_pointer_cast<Coupon>(*cf);
            if (cp)
                return cp->accrualDays();
        }
        return 0;
    }
Date QuantLib::CashFlows::accrualEndDate (const Leg & leg, bool includeSettlementDateFlows, Date settlementDate = Date()) [static]
Definition at line 267 of file cashflows.cpp.
References QuantLib::Coupon::accrualEndDate(), and nextCashFlow().
{
        Leg::const_iterator cf = nextCashFlow(leg,
                                              includeSettlementDateFlows,
                                              settlementDate);
        if (cf==leg.end()) return Date();
        Date paymentDate = (*cf)->date();
        for (; cf<leg.end() && (*cf)->date()==paymentDate; ++cf) {
            shared_ptr<Coupon> cp = dynamic_pointer_cast<Coupon>(*cf);
            if (cp)
                return cp->accrualEndDate();
        }
        return Date();
    }
Time QuantLib::CashFlows::accrualPeriod (const Leg & leg, bool includeSettlementDateFlows, Date settlementDate = Date()) [static]
Definition at line 318 of file cashflows.cpp.
References QuantLib::Coupon::accrualPeriod(), and nextCashFlow().
{
        Leg::const_iterator cf = nextCashFlow(leg,
                                              includeSettlementDateFlows,
                                              settlementDate);
        if (cf==leg.end()) return 0;
        Date paymentDate = (*cf)->date();
        for (; cf<leg.end() && (*cf)->date()==paymentDate; ++cf) {
            shared_ptr<Coupon> cp = dynamic_pointer_cast<Coupon>(*cf);
            if (cp)
                return cp->accrualPeriod();
        }
        return 0;
    }
Date QuantLib::CashFlows::accrualStartDate (const Leg & leg, bool includeSettlementDateFlows, Date settlDate = Date()) [static]
Definition at line 250 of file cashflows.cpp.
References QuantLib::Coupon::accrualStartDate(), and nextCashFlow().
{
        Leg::const_iterator cf = nextCashFlow(leg,
                                              includeSettlementDateFlows,
                                              settlementDate);
        if (cf==leg.end()) return Date();
        Date paymentDate = (*cf)->date();
        for (; cf<leg.end() && (*cf)->date()==paymentDate; ++cf) {
            shared_ptr<Coupon> cp = dynamic_pointer_cast<Coupon>(*cf);
            if (cp)
                return cp->accrualStartDate();
        }
        return Date();
    }
Real QuantLib::CashFlows::accruedAmount (const Leg & leg, bool includeSettlementDateFlows, Date settlementDate = Date()) [static]
Definition at line 386 of file cashflows.cpp.
References QuantLib::Coupon::accruedAmount(), and nextCashFlow().
{
        Leg::const_iterator cf = nextCashFlow(leg,
                                              includeSettlementDateFlows,
                                              settlementDate);
        if (cf==leg.end()) return 0.0;
        Date paymentDate = (*cf)->date();
        Real result = 0.0;
        for (; cf<leg.end() && (*cf)->date()==paymentDate; ++cf) {
            shared_ptr<Coupon> cp = dynamic_pointer_cast<Coupon>(*cf);
            if (cp)
                result += cp->accruedAmount(settlementDate);
        }
        return result;
    }
BigInteger QuantLib::CashFlows::accruedDays (const Leg & leg, bool includeSettlementDateFlows, Date settlementDate = Date()) [static]
Definition at line 369 of file cashflows.cpp.
References QuantLib::Coupon::accruedDays(), and nextCashFlow().
{
        Leg::const_iterator cf = nextCashFlow(leg,
                                              includeSettlementDateFlows,
                                              settlementDate);
        if (cf==leg.end()) return 0;
        Date paymentDate = (*cf)->date();
        for (; cf<leg.end() && (*cf)->date()==paymentDate; ++cf) {
            shared_ptr<Coupon> cp = dynamic_pointer_cast<Coupon>(*cf);
            if (cp)
                return cp->accruedDays(settlementDate);
        }
        return 0;
    }
Time QuantLib::CashFlows::accruedPeriod (const Leg & leg, bool includeSettlementDateFlows, Date settlementDate = Date()) [static]
Definition at line 352 of file cashflows.cpp.
References QuantLib::Coupon::accruedPeriod(), and nextCashFlow().
{
        Leg::const_iterator cf = nextCashFlow(leg,
                                              includeSettlementDateFlows,
                                              settlementDate);
        if (cf==leg.end()) return 0;
        Date paymentDate = (*cf)->date();
        for (; cf<leg.end() && (*cf)->date()==paymentDate; ++cf) {
            shared_ptr<Coupon> cp = dynamic_pointer_cast<Coupon>(*cf);
            if (cp)
                return cp->accruedPeriod(settlementDate);
        }
        return 0;
    }
Rate QuantLib::CashFlows::atmRate (const Leg & leg, const YieldTermStructure & discountCurve, bool includeSettlementDateFlows, Date settlementDate = Date(), Date npvDate = Date(), Real npv = Null<Real>()) [static]
At-the-money rate of the cash flows.
The result is the fixed rate for which a fixed rate cash flow vector, equivalent to the input vector, has the required NPV according to the given term structure. If the required NPV is not given, the input cash flow vector's NPV is used instead.
Definition at line 506 of file cashflows.cpp.
References QuantLib::anonymous_namespace{cashflows.cpp}::basisPoint_, bps(), QuantLib::Settings::evaluationDate(), QuantLib::Singleton< Settings >::instance(), npvbps(), and QL_REQUIRE.
Referenced by QuantLib::MakeYoYInflationCapFloor::operator boost::shared_ptr< YoYInflationCapFloor >().
{
        QL_REQUIRE(!leg.empty(), "empty leg");
        if (settlementDate == Date())
            settlementDate = Settings::instance().evaluationDate();
        if (npvDate == Date())
            npvDate = settlementDate;
        Real bps = 0.0;
        if (npv==Null<Real>())
            CashFlows::npvbps(leg, discountCurve,
                              includeSettlementDateFlows,
                              settlementDate, npvDate,
                              npv, bps);
        else
            bps = CashFlows::bps(leg, discountCurve,
                                 includeSettlementDateFlows,
                                 settlementDate, npvDate);
        return basisPoint_*npv/bps;
    }
Real QuantLib::CashFlows::basisPointValue (const Leg & leg, const InterestRate & yield, bool includeSettlementDateFlows, Date settlementDate = Date(), Date npvDate = Date()) [static]
Basis-point value.
Obtained by setting dy = 0.0001 in the 2nd-order Taylor series expansion.
Definition at line 987 of file cashflows.cpp.
References convexity(), duration(), QuantLib::Settings::evaluationDate(), QuantLib::Singleton< Settings >::instance(), QuantLib::Duration::Modified, QuantLib::anonymous_namespace{cashflows.cpp}::modifiedDuration(), and npv().
Referenced by basisPointValue().
{
        if (leg.empty())
            return 0.0;
        if (settlementDate == Date())
            settlementDate = Settings::instance().evaluationDate();
        if (npvDate == Date())
            npvDate = settlementDate;
        Real npv = CashFlows::npv(leg, y,
                                  includeSettlementDateFlows,
                                  settlementDate, npvDate);
        Real modifiedDuration = CashFlows::duration(leg, y,
                                                    Duration::Modified,
                                                    includeSettlementDateFlows,
                                                    settlementDate, npvDate);
        Real convexity = CashFlows::convexity(leg, y,
                                              includeSettlementDateFlows,
                                              settlementDate, npvDate);
        Real delta = -modifiedDuration*npv;
        Real gamma = (convexity/100.0)*npv;
        Real shift = 0.0001;
        delta *= shift;
        gamma *= shift*shift;
        return delta + 0.5*gamma;
    }
Real QuantLib::CashFlows::basisPointValue (const Leg & leg, Rate yield, const DayCounter & dayCounter, Compounding compounding, Frequency frequency, bool includeSettlementDateFlows, Date settlementDate = Date(), Date npvDate = Date()) [static]
Definition at line 1021 of file cashflows.cpp.
References basisPointValue().
{
        return basisPointValue(leg, InterestRate(yield, dc, comp, freq),
                               includeSettlementDateFlows,
                               settlementDate, npvDate);
    }
Real QuantLib::CashFlows::bps (const Leg & leg, const YieldTermStructure & discountCurve, bool includeSettlementDateFlows, Date settlementDate = Date(), Date npvDate = Date()) [static]
Basis-point sensitivity of the cash flows.
The result is the change in NPV due to a uniform 1-basis-point change in the rate paid by the cash flows. The change for each coupon is discounted according to the given term structure.
Definition at line 454 of file cashflows.cpp.
References QuantLib::anonymous_namespace{cashflows.cpp}::basisPoint_, QuantLib::YieldTermStructure::discount(), QuantLib::Settings::evaluationDate(), and QuantLib::Singleton< Settings >::instance().
Referenced by atmRate(), bps(), QuantLib::BlackSwaptionEngine::calculate(), and QuantLib::CmsMarket::performCalculations().
{
        if (leg.empty())
            return 0.0;
        if (settlementDate == Date())
            settlementDate = Settings::instance().evaluationDate();
        if (npvDate == Date())
            npvDate = settlementDate;
        BPSCalculator calc(discountCurve);
        for (Size i=0; i<leg.size(); ++i) {
            if (!leg[i]->hasOccurred(settlementDate,
                                     includeSettlementDateFlows))
                leg[i]->accept(calc);
        }
        return basisPoint_*calc.result()/discountCurve.discount(npvDate);
    }
Real QuantLib::CashFlows::bps (const Leg & leg, const InterestRate & yield, bool includeSettlementDateFlows, Date settlementDate = Date(), Date npvDate = Date()) [static]
Basis-point sensitivity of the cash flows.
The result is the change in NPV due to a uniform 1-basis-point change in the rate paid by the cash flows. The change for each coupon is discounted according to the given constant interest rate. The result is affected by the choice of the interest-rate compounding and the relative frequency and day counter.
Definition at line 809 of file cashflows.cpp.
References bps(), QuantLib::InterestRate::compounding(), QuantLib::InterestRate::dayCounter(), QuantLib::Settings::evaluationDate(), QuantLib::flatRate(), QuantLib::InterestRate::frequency(), QuantLib::Singleton< Settings >::instance(), and QuantLib::InterestRate::rate().
{
        if (leg.empty())
            return 0.0;
        if (settlementDate == Date())
            settlementDate = Settings::instance().evaluationDate();
        if (npvDate == Date())
            npvDate = settlementDate;
        FlatForward flatRate(settlementDate, yield.rate(), yield.dayCounter(),
                             yield.compounding(), yield.frequency());
        return bps(leg, flatRate,
                   includeSettlementDateFlows,
                   settlementDate, npvDate);
    }
Real QuantLib::CashFlows::bps (const Leg & leg, Rate yield, const DayCounter & dayCounter, Compounding compounding, Frequency frequency, bool includeSettlementDateFlows, Date settlementDate = Date(), Date npvDate = Date()) [static]
Definition at line 831 of file cashflows.cpp.
References bps().
{
        return bps(leg, InterestRate(yield, dc, comp, freq),
                   includeSettlementDateFlows,
                   settlementDate, npvDate);
    }
Real QuantLib::CashFlows::convexity (const Leg & leg, const InterestRate & yield, bool includeSettlementDateFlows, Date settlementDate = Date(), Date npvDate = Date()) [static]
Cash-flow convexity.
The convexity of a string of cash flows is defined as
\[ C = \frac{1}{P} \frac{\partial^2 P}{\partial y^2} \]
where \(P \) is the present value of the cash flows according to the given IRR \(y \).
Definition at line 915 of file cashflows.cpp.
References anonymous_namespace{marketmodel.cpp}::c, QuantLib::Compounded, QuantLib::InterestRate::compounding(), QuantLib::Continuous, QuantLib::InterestRate::dayCounter(), QuantLib::InterestRate::discountFactor(), QuantLib::Settings::evaluationDate(), QuantLib::InterestRate::frequency(), QuantLib::Singleton< Settings >::instance(), anonymous_namespace{matrices.cpp}::N, QL_FAIL, QuantLib::InterestRate::rate(), QuantLib::Simple, QuantLib::SimpleThenCompounded, anonymous_namespace{quantlibbenchmark.cpp}::t, and QuantLib::DayCounter::yearFraction().
Referenced by basisPointValue(), and convexity().
{
        if (leg.empty())
            return 0.0;
        if (settlementDate == Date())
            settlementDate = Settings::instance().evaluationDate();
        if (npvDate == Date())
            npvDate = settlementDate;
        const DayCounter& dc = y.dayCounter();
        Real P = 0.0;
        Real d2Pdy2 = 0.0;
        Rate r = y.rate();
        Natural N = y.frequency();
        for (Size i=0; i<leg.size(); ++i) {
            if (!leg[i]->hasOccurred(settlementDate,
                                     includeSettlementDateFlows)) {
                Time t = dc.yearFraction(npvDate,
                                         leg[i]->date());
                Real c = leg[i]->amount();
                DiscountFactor B = y.discountFactor(t);
                P += c * B;
                switch (y.compounding()) {
                  case Simple:
                    d2Pdy2 += c * 2.0*B*B*B*t*t;
                    break;
                  case Compounded:
                    d2Pdy2 += c * B*t*(N*t+1)/(N*(1+r/N)*(1+r/N));
                    break;
                  case Continuous:
                    d2Pdy2 += c * B*t*t;
                    break;
                  case SimpleThenCompounded:
                    if (t<=1.0/N)
                        d2Pdy2 += c * 2.0*B*B*B*t*t;
                    else
                        d2Pdy2 += c * B*t*(N*t+1)/(N*(1+r/N)*(1+r/N));
                    break;
                  default:
                    QL_FAIL("unknown compounding convention (" <<
                            Integer(y.compounding()) << ")");
                }
            }
        }
        if (P == 0.0)
            // no cashflows
            return 0.0;
        return d2Pdy2/P;
    }
Real QuantLib::CashFlows::convexity (const Leg & leg, Rate yield, const DayCounter & dayCounter, Compounding compounding, Frequency frequency, bool includeSettlementDateFlows, Date settlementDate = Date(), Date npvDate = Date()) [static]
Definition at line 974 of file cashflows.cpp.
References convexity().
{
        return convexity(leg, InterestRate(yield, dc, comp, freq),
                         includeSettlementDateFlows,
                         settlementDate, npvDate);
    }
Time QuantLib::CashFlows::duration (const Leg & leg, const InterestRate & yield, Duration::Type type, bool includeSettlementDateFlows, Date settlementDate = Date(), Date npvDate = Date()) [static]
Cash-flow duration.
The simple duration of a string of cash flows is defined as
\[ D_{\mathrm{simple}} = \frac{\sum t_i c_i B(t_i)}{\sum c_i B(t_i)} \]
where \(c_i \) is the amount of the \(i \)-th cash flow, \(t_i \) is its payment time, and \(B(t_i) \) is the corresponding discount according to the passed yield.
The modified duration is defined as
\[ D_{\mathrm{modified}} = -\frac{1}{P} \frac{\partial P}{\partial y} \]
where \(P \) is the present value of the cash flows according to the given IRR \(y \).
The Macaulay duration is defined for a compounded IRR as
\[ D_{\mathrm{Macaulay}} = \left(1 + \frac{y}{N} \right) D_{\mathrm{modified}} \]
where \(y \) is the IRR and \(N \) is the number of cash flows per year.
Definition at line 866 of file cashflows.cpp.
References QuantLib::Settings::evaluationDate(), QuantLib::Singleton< Settings >::instance(), QuantLib::Duration::Macaulay, QuantLib::anonymous_namespace{cashflows.cpp}::macaulayDuration(), QuantLib::Duration::Modified, QuantLib::anonymous_namespace{cashflows.cpp}::modifiedDuration(), QL_FAIL, QuantLib::Duration::Simple, and QuantLib::anonymous_namespace{cashflows.cpp}::simpleDuration().
Referenced by basisPointValue(), duration(), QuantLib::BlackCallableFixedRateBondEngine::forwardPriceVolatility(), and yieldValueBasisPoint().
{
        if (leg.empty())
            return 0.0;
        if (settlementDate == Date())
            settlementDate = Settings::instance().evaluationDate();
        if (npvDate == Date())
            npvDate = settlementDate;
        switch (type) {
          case Duration::Simple:
            return simpleDuration(leg, rate,
                                  includeSettlementDateFlows,
                                  settlementDate, npvDate);
          case Duration::Modified:
            return modifiedDuration(leg, rate,
                                    includeSettlementDateFlows,
                                    settlementDate, npvDate);
          case Duration::Macaulay:
            return macaulayDuration(leg, rate,
                                    includeSettlementDateFlows,
                                    settlementDate, npvDate);
          default:
            QL_FAIL("unknown duration type");
        }
    }
Time QuantLib::CashFlows::duration (const Leg & leg, Rate yield, const DayCounter & dayCounter, Compounding compounding, Frequency frequency, Duration::Type type, bool includeSettlementDateFlows, Date settlementDate = Date(), Date npvDate = Date()) [static]
Definition at line 900 of file cashflows.cpp.
References duration().
{
        return duration(leg, InterestRate(yield, dc, comp, freq),
                        type,
                        includeSettlementDateFlows,
                        settlementDate, npvDate);
    }
bool QuantLib::CashFlows::isExpired (const Leg & leg, bool includeSettlementDateFlows, Date settlementDate = Date()) [static]
Definition at line 67 of file cashflows.cpp.
References QuantLib::Settings::evaluationDate(), and QuantLib::Singleton< Settings >::instance().
    {
        if (leg.empty())
            return true;
        if (settlementDate == Date())
            settlementDate = Settings::instance().evaluationDate();
        for (Size i=leg.size(); i>0; --i)
            if (!leg[i-1]->hasOccurred(settlementDate,
                                       includeSettlementDateFlows))
                return false;
        return true;
    }
Date QuantLib::CashFlows::maturityDate (const Leg & leg) [static]
Definition at line 53 of file cashflows.cpp.
References anonymous_namespace{marketmodel.cpp}::c, anonymous_namespace{marketmodel.cpp}::d, QuantLib::Date::minDate(), and QL_REQUIRE.
Referenced by QuantLib::DiscountingSwapEngine::calculate(), and QuantLib::Swap::maturityDate().
{
        QL_REQUIRE(!leg.empty(), "empty leg");
        Date d = Date::minDate();
        for (Size i=0; i<leg.size(); ++i) {
            shared_ptr<Coupon> c = dynamic_pointer_cast<Coupon>(leg[i]);
            if (c)
                d = std::max(d, c->accrualEndDate());
            else
                d = std::max(d, leg[i]->date());
        }
        return d;
    }
Leg::const_iterator QuantLib::CashFlows::nextCashFlow (const Leg & leg, bool includeSettlementDateFlows, Date settlementDate = Date()) [static]
the first cashflow paying after the given date
Definition at line 103 of file cashflows.cpp.
References QuantLib::Settings::evaluationDate(), and QuantLib::Singleton< Settings >::instance().
Referenced by accrualDays(), accrualEndDate(), accrualPeriod(), accrualStartDate(), accruedAmount(), accruedDays(), accruedPeriod(), nextCashFlowAmount(), nextCashFlowDate(), nextCouponRate(), nominal(), referencePeriodEnd(), and referencePeriodStart().
{
        if (leg.empty())
            return leg.end();
        if (settlementDate == Date())
            settlementDate = Settings::instance().evaluationDate();
        Leg::const_iterator i;
        for (i = leg.begin(); i<leg.end(); ++i) {
            if ( ! (*i)->hasOccurred(settlementDate, includeSettlementDateFlows) )
                return i;
        }
        return leg.end();
    }
Real QuantLib::CashFlows::nextCashFlowAmount (const Leg & leg, bool includeSettlementDateFlows, Date settlementDate = Date()) [static]
Definition at line 160 of file cashflows.cpp.
References nextCashFlow().
{
        Leg::const_iterator cf;
        cf = nextCashFlow(leg, includeSettlementDateFlows, settlementDate);
        if (cf==leg.end())
            return Real();
        Date paymentDate = (*cf)->date();
        Real result = 0.0;
        for (; cf<leg.end() && (*cf)->date()==paymentDate; ++cf)
            result += (*cf)->amount();
        return result;
    }
Date QuantLib::CashFlows::nextCashFlowDate (const Leg & leg, bool includeSettlementDateFlows, Date settlementDate = Date()) [static]
Definition at line 132 of file cashflows.cpp.
References nextCashFlow().
{
        Leg::const_iterator cf;
        cf = nextCashFlow(leg, includeSettlementDateFlows, settlementDate);
        if (cf==leg.end())
            return Date();
        return (*cf)->date();
    }
Rate QuantLib::CashFlows::nextCouponRate (const Leg & leg, bool includeSettlementDateFlows, Date settlementDate = Date()) [static]
Definition at line 225 of file cashflows.cpp.
References nextCashFlow().
{
        Leg::const_iterator cf;
        cf = nextCashFlow(leg, includeSettlementDateFlows, settlementDate);
        return aggregateRate<Leg::const_iterator>(leg, cf, leg.end());
    }
Real QuantLib::CashFlows::nominal (const Leg & leg, bool includeSettlementDateFlows, Date settlDate = Date()) [static]
Definition at line 233 of file cashflows.cpp.
References nextCashFlow(), and QuantLib::Coupon::nominal().
{
        Leg::const_iterator cf = nextCashFlow(leg,
                                              includeSettlementDateFlows,
                                              settlementDate);
        if (cf==leg.end()) return 0.0;
        Date paymentDate = (*cf)->date();
        for (; cf<leg.end() && (*cf)->date()==paymentDate; ++cf) {
            shared_ptr<Coupon> cp = dynamic_pointer_cast<Coupon>(*cf);
            if (cp)
                return cp->nominal();
        }
        return 0.0;
    }
Real QuantLib::CashFlows::npv (const Leg & leg, const YieldTermStructure & discountCurve, bool includeSettlementDateFlows, Date settlementDate = Date(), Date npvDate = Date()) [static]
NPV of the cash flows.
The NPV is the sum of the cash flows, each discounted according to the given term structure.
Definition at line 428 of file cashflows.cpp.
References QuantLib::YieldTermStructure::discount(), QuantLib::Settings::evaluationDate(), and QuantLib::Singleton< Settings >::instance().
Referenced by basisPointValue(), QuantLib::DiscountingBondEngine::calculate(), QuantLib::BlackCallableFixedRateBondEngine::calculate(), QuantLib::BondFunctions::cleanPrice(), QuantLib::BlackCallableFixedRateBondEngine::forwardPriceVolatility(), npv(), QuantLib::anonymous_namespace{cashflows.cpp}::IrrFinder::operator()(), QuantLib::anonymous_namespace{cashflows.cpp}::ZSpreadFinder::operator()(), QuantLib::CmsMarket::performCalculations(), InflationCapFlooredCouponTest::testInstrumentEquality(), and yieldValueBasisPoint().
{
        if (leg.empty())
            return 0.0;
        if (settlementDate == Date())
            settlementDate = Settings::instance().evaluationDate();
        if (npvDate == Date())
            npvDate = settlementDate;
        Real totalNPV = 0.0;
        for (Size i=0; i<leg.size(); ++i) {
            if (!leg[i]->hasOccurred(settlementDate,
                                     includeSettlementDateFlows))
                totalNPV += leg[i]->amount() *
                            discountCurve.discount(leg[i]->date());
        }
        return totalNPV/discountCurve.discount(npvDate);
    }
Real QuantLib::CashFlows::npv (const Leg & leg, const InterestRate & yield, bool includeSettlementDateFlows, Date settlementDate = Date(), Date npvDate = Date()) [static]
NPV of the cash flows.
The IRR is the interest rate at which the NPV of the cash flows equals the dirty price.
The NPV is the sum of the cash flows, each discounted according to the given constant interest rate. The result is affected by the choice of the interest-rate compounding and the relative frequency and day counter.
Definition at line 745 of file cashflows.cpp.
References QuantLib::InterestRate::discountFactor(), QuantLib::Settings::evaluationDate(), QuantLib::Singleton< Settings >::instance(), npv(), and QuantLib::Years.
{
        if (leg.empty())
            return 0.0;
        if (settlementDate == Date())
            settlementDate = Settings::instance().evaluationDate();
        if (npvDate == Date())
            npvDate = settlementDate;
        Real npv = 0.0;
        DiscountFactor discount = 1.0;
        Date lastDate = Date();
        for (Size i=0; i<leg.size(); ++i) {
            if (leg[i]->hasOccurred(settlementDate,
                                    includeSettlementDateFlows))
                continue;
            Date couponDate = leg[i]->date();
            Real amount = leg[i]->amount();
            if (lastDate == Date()) {
                // first not-expired coupon
                if (i > 0) {
                    lastDate = leg[i-1]->date();
                } else {
                    shared_ptr<Coupon> coupon =
                        boost::dynamic_pointer_cast<Coupon>(leg[i]);
                    if (coupon)
                        lastDate = coupon->accrualStartDate();
                    else
                        lastDate = couponDate - 1*Years;
                }
                discount *= y.discountFactor(npvDate, couponDate,
                                             lastDate, couponDate);
            } else  {
                discount *= y.discountFactor(lastDate, couponDate);
            }
            lastDate = couponDate;
            npv += amount * discount;
        }
        return npv;
    }
Real QuantLib::CashFlows::npv (const Leg & leg, Rate yield, const DayCounter & dayCounter, Compounding compounding, Frequency frequency, bool includeSettlementDateFlows, Date settlementDate = Date(), Date npvDate = Date()) [static]
Definition at line 796 of file cashflows.cpp.
References npv().
{
        return npv(leg, InterestRate(yield, dc, comp, freq),
                   includeSettlementDateFlows,
                   settlementDate, npvDate);
    }
static Real QuantLib::CashFlows::npv (const Leg & leg, const boost::shared_ptr< YieldTermStructure > & discount, Spread zSpread, const DayCounter & dayCounter, Compounding compounding, Frequency frequency, bool includeSettlementDateFlows, Date settlementDate = Date(), Date npvDate = Date()) [static]
NPV of the cash flows.
For details on z-spread refer to: "Credit Spreads Explained", Lehman Brothers European Fixed Income Research - March 2004, D. O'Kane
The NPV is the sum of the cash flows, each discounted according to the z-spreaded term structure. The result is affected by the choice of the z-spread compounding and the relative frequency and day counter.
void QuantLib::CashFlows::npvbps (const Leg & leg, const YieldTermStructure & discountCurve, bool includeSettlementDateFlows, Date settlementDate, Date npvDate, Real & npv, Real & bps) [static]
NPV and BPS of the cash flows.
The NPV and BPS of the cash flows calculated together for performance reason
Definition at line 477 of file cashflows.cpp.
References QuantLib::CashFlow::accept(), QuantLib::CashFlow::amount(), QuantLib::anonymous_namespace{cashflows.cpp}::basisPoint_, anonymous_namespace{marketmodel.cpp}::d, QuantLib::CashFlow::date(), QuantLib::YieldTermStructure::discount(), and QuantLib::CashFlow::hasOccurred().
Referenced by atmRate(), and QuantLib::DiscountingSwapEngine::calculate().
{
        npv = 0.0;
        if (leg.empty()) {
            bps = 0.0;
            return;
        }
        BPSCalculator calc(discountCurve);
        for (Size i=0; i<leg.size(); ++i) {
            CashFlow& cf = *leg[i];
            if (!cf.hasOccurred(settlementDate,
                                includeSettlementDateFlows)) {
                npv += cf.amount() *
                       discountCurve.discount(cf.date());
                cf.accept(calc);
            }
        }
        DiscountFactor d = discountCurve.discount(npvDate);
        npv /= d;
        bps = basisPoint_ * calc.result() / d;
    }
Leg::const_reverse_iterator QuantLib::CashFlows::previousCashFlow (const Leg & leg, bool includeSettlementDateFlows, Date settlementDate = Date()) [static]
the last cashflow paying before or at the given date
Definition at line 85 of file cashflows.cpp.
References QuantLib::Settings::evaluationDate(), and QuantLib::Singleton< Settings >::instance().
Referenced by previousCashFlowAmount(), previousCashFlowDate(), and previousCouponRate().
{
        if (leg.empty())
            return leg.rend();
        if (settlementDate == Date())
            settlementDate = Settings::instance().evaluationDate();
        Leg::const_reverse_iterator i;
        for (i = leg.rbegin(); i<leg.rend(); ++i) {
            if ( (*i)->hasOccurred(settlementDate, includeSettlementDateFlows) )
                return i;
        }
        return leg.rend();
    }
Real QuantLib::CashFlows::previousCashFlowAmount (const Leg & leg, bool includeSettlementDateFlows, Date settlementDate = Date()) [static]
Definition at line 144 of file cashflows.cpp.
References previousCashFlow().
{
        Leg::const_reverse_iterator cf;
        cf = previousCashFlow(leg, includeSettlementDateFlows, settlementDate);
        if (cf==leg.rend())
            return Real();
        Date paymentDate = (*cf)->date();
        Real result = 0.0;
        for (; cf<leg.rend() && (*cf)->date()==paymentDate; ++cf)
            result += (*cf)->amount();
        return result;
    }
Date QuantLib::CashFlows::previousCashFlowDate (const Leg & leg, bool includeSettlementDateFlows, Date settlementDate = Date()) [static]
Definition at line 120 of file cashflows.cpp.
References previousCashFlow().
{
        Leg::const_reverse_iterator cf;
        cf = previousCashFlow(leg, includeSettlementDateFlows, settlementDate);
        if (cf==leg.rend())
            return Date();
        return (*cf)->date();
    }
Rate QuantLib::CashFlows::previousCouponRate (const Leg & leg, bool includeSettlementDateFlows, Date settlementDate = Date()) [static]
Definition at line 216 of file cashflows.cpp.
References previousCashFlow().
{
        Leg::const_reverse_iterator cf;
        cf = previousCashFlow(leg, includeSettlementDateFlows, settlementDate);
        return aggregateRate<Leg::const_reverse_iterator>(leg, cf, leg.rend());
    }
Date QuantLib::CashFlows::referencePeriodEnd (const Leg & leg, bool includeSettlementDateFlows, Date settlDate = Date()) [static]
Definition at line 301 of file cashflows.cpp.
References nextCashFlow(), and QuantLib::Coupon::referencePeriodEnd().
{
        Leg::const_iterator cf = nextCashFlow(leg,
                                              includeSettlementDateFlows,
                                              settlementDate);
        if (cf==leg.end()) return Date();
        Date paymentDate = (*cf)->date();
        for (; cf<leg.end() && (*cf)->date()==paymentDate; ++cf) {
            shared_ptr<Coupon> cp = dynamic_pointer_cast<Coupon>(*cf);
            if (cp)
                return cp->referencePeriodEnd();
        }
        return Date();
    }
Date QuantLib::CashFlows::referencePeriodStart (const Leg & leg, bool includeSettlementDateFlows, Date settlDate = Date()) [static]
Definition at line 284 of file cashflows.cpp.
References nextCashFlow(), and QuantLib::Coupon::referencePeriodStart().
{
        Leg::const_iterator cf = nextCashFlow(leg,
                                              includeSettlementDateFlows,
                                              settlementDate);
        if (cf==leg.end()) return Date();
        Date paymentDate = (*cf)->date();
        for (; cf<leg.end() && (*cf)->date()==paymentDate; ++cf) {
            shared_ptr<Coupon> cp = dynamic_pointer_cast<Coupon>(*cf);
            if (cp)
                return cp->referencePeriodStart();
        }
        return Date();
    }
Date QuantLib::CashFlows::startDate (const Leg & leg) [static]
Definition at line 39 of file cashflows.cpp.
References anonymous_namespace{marketmodel.cpp}::c, anonymous_namespace{marketmodel.cpp}::d, QuantLib::Date::maxDate(), and QL_REQUIRE.
Referenced by QuantLib::Swap::startDate().
{
        QL_REQUIRE(!leg.empty(), "empty leg");
        Date d = Date::maxDate();
        for (Size i=0; i<leg.size(); ++i) {
            shared_ptr<Coupon> c = dynamic_pointer_cast<Coupon>(leg[i]);
            if (c)
                d = std::min(d, c->accrualStartDate());
            else
                d = std::min(d, leg[i]->date());
        }
        return d;
    }
Rate QuantLib::CashFlows::yield (const Leg & leg, Real npv, const DayCounter & dayCounter, Compounding compounding, Frequency frequency, bool includeSettlementDateFlows, Date settlementDate = Date(), Date npvDate = Date(), Real accuracy = 1.0e-10, Size maxIterations = 100, Rate guess = 0.05) [static]
Implied internal rate of return.
The function verifies the theoretical existance of an IRR and numerically establishes the IRR to the desired precision.
Definition at line 844 of file cashflows.cpp.
References QuantLib::Solver1D< Impl >::setMaxEvaluations(), and QuantLib::Solver1D< Impl >::solve().
Referenced by QuantLib::BlackCallableFixedRateBondEngine::forwardPriceVolatility().
{
        //Brent solver;
        NewtonSafe solver;
        solver.setMaxEvaluations(maxIterations);
        IrrFinder objFunction(leg, npv,
                              dayCounter, compounding, frequency,
                              includeSettlementDateFlows,
                              settlementDate, npvDate);
        return solver.solve(objFunction, accuracy, guess, guess/10.0);
    }
Real QuantLib::CashFlows::yieldValueBasisPoint (const Leg & leg, const InterestRate & yield, bool includeSettlementDateFlows, Date settlementDate = Date(), Date npvDate = Date()) [static]
Yield value of a basis point.
The yield value of a one basis point change in price is the derivative of the yield with respect to the price multiplied by 0.01
Definition at line 1034 of file cashflows.cpp.
References duration(), QuantLib::Settings::evaluationDate(), QuantLib::Singleton< Settings >::instance(), QuantLib::Duration::Modified, QuantLib::anonymous_namespace{cashflows.cpp}::modifiedDuration(), and npv().
Referenced by yieldValueBasisPoint().
{
        if (leg.empty())
            return 0.0;
        if (settlementDate == Date())
            settlementDate = Settings::instance().evaluationDate();
        if (npvDate == Date())
            npvDate = settlementDate;
        Real npv = CashFlows::npv(leg, y,
                                  includeSettlementDateFlows,
                                  settlementDate, npvDate);
        Real modifiedDuration = CashFlows::duration(leg, y,
                                                    Duration::Modified,
                                                    includeSettlementDateFlows,
                                                    settlementDate, npvDate);
        Real shift = 0.01;
        return (1.0/(-npv*modifiedDuration))*shift;
    }
Real QuantLib::CashFlows::yieldValueBasisPoint (const Leg & leg, Rate yield, const DayCounter & dayCounter, Compounding compounding, Frequency frequency, bool includeSettlementDateFlows, Date settlementDate = Date(), Date npvDate = Date()) [static]
Definition at line 1060 of file cashflows.cpp.
References yieldValueBasisPoint().
{
        return yieldValueBasisPoint(leg, InterestRate(yield, dc, comp, freq),
                                    includeSettlementDateFlows,
                                    settlementDate, npvDate);
    }
static Spread QuantLib::CashFlows::zSpread (const Leg & leg, Real npv, const boost::shared_ptr< YieldTermStructure > & , const DayCounter & dayCounter, Compounding compounding, Frequency frequency, bool includeSettlementDateFlows, Date settlementDate = Date(), Date npvDate = Date(), Real accuracy = 1.0e-10, Size maxIterations = 100, Rate guess = 0.0) [static]
implied Z-spread.
Referenced by zSpread().
static Spread QuantLib::CashFlows::zSpread (const Leg & leg, const boost::shared_ptr< YieldTermStructure > & d, Real npv, const DayCounter & dayCounter, Compounding compounding, Frequency frequency, bool includeSettlementDateFlows, Date settlementDate = Date(), Date npvDate = Date(), Real accuracy = 1.0e-10, Size maxIterations = 100, Rate guess = 0.0) [inline, static]
deprecated implied Z-spread.
Definition at line 385 of file cashflows.hpp.
References zSpread().
{
            return zSpread(leg, npv, d, dayCounter, compounding, frequency,
                           includeSettlementDateFlows, settlementDate, npvDate,
                           accuracy, maxIterations, guess);
        }
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/cashflows.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/cashflows.cpp