QuantLib: QuantLib::Simplex Class Reference
QuantLib::Simplex Class Reference
Multi-dimensional simplex class.
#include <simplex.hpp>
Public Member Functions
Simplex (Real lambda)
virtual EndCriteria::Type minimize (Problem &P, const EndCriteria &endCriteria)
minimize the optimization problem P
Private Member Functions
Real extrapolate (Problem &P, Size iHighest, Real &factor) const
Private Attributes
Real lambda_
std::vector< Array > vertices_
Array values_
Array sum_
Detailed Description
Multi-dimensional simplex class.
Definition at line 39 of file simplex.hpp.
Constructor & Destructor Documentation
QuantLib::Simplex::Simplex (Real lambda) [inline]
Constructor taking as input the characteristic length
Definition at line 42 of file simplex.hpp.
: lambda_(lambda) {}
Member Function Documentation
Real QuantLib::Simplex::extrapolate (Problem & P, Size iHighest, Real & factor) const [private]
Definition at line 58 of file simplex.cpp.
References QuantLib::Problem::constraint(), QL_EPSILON, QuantLib::Array::size(), sum_, QuantLib::Constraint::test(), QuantLib::Problem::value(), values_, and vertices_.
Referenced by minimize().
{
        Array pTry;
        do {
            Size dimensions = values_.size() - 1;
            Real factor1 = (1.0 - factor)/dimensions;
            Real factor2 = factor1 - factor;
            #if defined(QL_ARRAY_EXPRESSIONS)
            pTry = sum_*factor1 - vertices_[iHighest]*factor2;
            #else
            // composite expressions fail to compile with gcc 3.4 on windows
            pTry = sum_*factor1;
            pTry -= vertices_[iHighest]*factor2;
            #endif
            factor *= 0.5;
        } while (!P.constraint().test(pTry) && std::fabs(factor) > QL_EPSILON);
        if (std::fabs(factor) <= QL_EPSILON) {
            return values_[iHighest];
        }
        factor *= 2.0;
        Real vTry = P.value(pTry);
        if (vTry < values_[iHighest]) {
            values_[iHighest] = vTry;
            #if defined(QL_ARRAY_EXPRESSIONS)
            sum_ += pTry - vertices_[iHighest];
            #else
            sum_ += pTry;
            sum_ -= vertices_[iHighest];
            #endif
            vertices_[iHighest] = pTry;
        }
        return vTry;
    }
EndCriteria::Type QuantLib::Simplex::minimize (Problem & P, const EndCriteria & endCriteria) [virtual]
minimize the optimization problem P
Implements QuantLib::OptimizationMethod.
Definition at line 96 of file simplex.cpp.
References QuantLib::EndCriteria::checkMaxIterations(), QuantLib::EndCriteria::checkStationaryPoint(), QuantLib::anonymous_namespace{simplex.cpp}::computeSimplexSize(), QuantLib::Problem::constraint(), QuantLib::Problem::currentValue(), extrapolate(), lambda_, QuantLib::EndCriteria::maxStationaryStateIterations(), anonymous_namespace{optimizers.cpp}::maxStationaryStateIterations_, QuantLib::EndCriteria::None, QL_EPSILON, QL_FAIL, QuantLib::Problem::reset(), QuantLib::EndCriteria::rootEpsilon(), QuantLib::Problem::setCurrentValue(), QuantLib::Problem::setFunctionValue(), QuantLib::Array::size(), QuantLib::EndCriteria::StationaryFunctionValue, sum_, QuantLib::Constraint::update(), QuantLib::Problem::value(), values_, and vertices_.
Referenced by QuantLib::FittedBondDiscountCurve::FittingMethod::calculate().
{
        // set up of the problem
        //Real ftol = endCriteria.functionEpsilon();    // end criteria on f(x) (see Numerical Recipes in C++, p.410)
        Real xtol = endCriteria.rootEpsilon();          // end criteria on x (see GSL v. 1.9, http://www.gnu.org/software/gsl/)
        Size maxStationaryStateIterations_
            = endCriteria.maxStationaryStateIterations();
        EndCriteria::Type ecType = EndCriteria::None;
        P.reset();
        Array x_ = P.currentValue();
        Integer iterationNumber_=0;
        // Initialize vertices of the simplex
        bool end = false;
        Size n = x_.size(), i;
        vertices_ = std::vector<Array>(n+1, x_);
        for (i=0; i<n; i++) {
            Array direction(n, 0.0);
            direction[i] = 1.0;
            P.constraint().update(vertices_[i+1], direction, lambda_);
        }
        // Initialize function values at the vertices of the simplex
        values_ = Array(n+1, 0.0);
        for (i=0; i<=n; i++)
            values_[i] = P.value(vertices_[i]);
        // Loop looking for minimum
        do {
            sum_ = Array(n, 0.0);
            Size i;
            for (i=0; i<=n; i++)
                sum_ += vertices_[i];
            // Determine the best (iLowest), worst (iHighest)
            // and 2nd worst (iNextHighest) vertices
            Size iLowest = 0;
            Size iHighest, iNextHighest;
            if (values_[0]<values_[1]) {
                iHighest = 1;
                iNextHighest = 0;
            } else {
                iHighest = 0;
                iNextHighest = 1;
            }
            for (i=1;i<=n; i++) {
                if (values_[i]>values_[iHighest]) {
                    iNextHighest = iHighest;
                    iHighest = i;
                } else {
                    if ((values_[i]>values_[iNextHighest]) && i!=iHighest)
                        iNextHighest = i;
                }
                if (values_[i]<values_[iLowest])
                    iLowest = i;
            }
            // Now compute accuracy, update iteration number and check end criteria
            //Real low = values_[iLowest];
            //Real high = values_[iHighest];
            //Real rtol = 2.0*std::fabs(high - low)/
            //    (std::fabs(high) + std::fabs(low) + QL_EPSILON);
            //++iterationNumber_;
            //if (rtol < ftol ||
            //    endCriteria.checkMaxIterations(iterationNumber_, ecType)) {
            // GSL exit strategy on x (see GSL v. 1.9, http://www.gnu.org/software/gsl
            Real simplexSize = computeSimplexSize(vertices_);
            ++iterationNumber_;
            if (simplexSize < xtol ||
                endCriteria.checkMaxIterations(iterationNumber_, ecType)) {
                endCriteria.checkStationaryPoint(0.0, 0.0,
                    maxStationaryStateIterations_, ecType);
                endCriteria.checkMaxIterations(iterationNumber_, ecType);
                x_ = vertices_[iLowest];
                Real low = values_[iLowest];
                P.setFunctionValue(low);
                P.setCurrentValue(x_);
                return ecType;
            }
            // If end criteria is not met, continue
            Real factor = -1.0;
            Real vTry = extrapolate(P, iHighest, factor);
            if ((vTry <= values_[iLowest]) && (factor == -1.0)) {
                factor = 2.0;
                extrapolate(P, iHighest, factor);
            } else if (std::fabs(factor) > QL_EPSILON) {
                if (vTry >= values_[iNextHighest]) {
                    Real vSave = values_[iHighest];
                    factor = 0.5;
                    vTry = extrapolate(P, iHighest, factor);
                    if (vTry >= vSave && std::fabs(factor) > QL_EPSILON) {
                        for (Size i=0; i<=n; i++) {
                            if (i!=iLowest) {
                                #if defined(QL_ARRAY_EXPRESSIONS)
                                vertices_[i] =
                                    0.5*(vertices_[i] + vertices_[iLowest]);
                                #else
                                vertices_[i] += vertices_[iLowest];
                                vertices_[i] *= 0.5;
                                #endif
                                values_[i] = P.value(vertices_[i]);
                            }
                        }
                    }
                }
            }
            // If can't extrapolate given the constraints, exit
            if (std::fabs(factor) <= QL_EPSILON) {
                x_ = vertices_[iLowest];
                Real low = values_[iLowest];
                P.setFunctionValue(low);
                P.setCurrentValue(x_);
                return EndCriteria::StationaryFunctionValue;
            }
        } while (end == false);
        QL_FAIL("optimization failed: unexpected behaviour");
    }
Member Data Documentation
Real QuantLib::Simplex::lambda_ [private]
Definition at line 49 of file simplex.hpp.
Referenced by minimize().
Array QuantLib::Simplex::sum_ [mutable, private]
Definition at line 51 of file simplex.hpp.
Referenced by extrapolate(), and minimize().
Array QuantLib::Simplex::values_ [mutable, private]
Definition at line 51 of file simplex.hpp.
Referenced by extrapolate(), and minimize().
std::vector<Array> QuantLib::Simplex::vertices_ [mutable, private]
Definition at line 50 of file simplex.hpp.
Referenced by extrapolate(), and minimize().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/optimization/simplex.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/math/optimization/simplex.cpp