QuantLib: QuantLib::CPICoupon Class Reference
QuantLib::CPICoupon Class Reference
Coupon paying the performance of a CPI (zero inflation) index
#include <cpicoupon.hpp>
Public Member Functions
CPICoupon (Real baseCPI, const Date &paymentDate, Real nominal, const Date &startDate, const Date &endDate, Natural fixingDays, const boost::shared_ptr< ZeroInflationIndex > &index, const Period &observationLag, CPI::InterpolationType observationInterpolation, const DayCounter &dayCounter, Real fixedRate, Spread spread=0.0, const Date &refPeriodStart=Date(), const Date &refPeriodEnd=Date())
Inspectors
Real fixedRate () const
fixed rate that will be inflated by the index ratio
Spread spread () const
spread paid over the fixing of the underlying index
Rate adjustedFixing () const
adjusted fixing (already divided by the base fixing)
Rate indexFixing () const
allows for a different interpolation from the index
Rate baseCPI () const
base value for the CPI index
CPI::InterpolationType observationInterpolation () const
how do you observe the index? as-is, flat, linear?
Rate indexObservation (const Date &onDate) const
utility method, calls indexFixing
boost::shared_ptr
< ZeroInflationIndex > cpiIndex () const
index used
Visitability
virtual void accept (AcyclicVisitor &)
Protected Member Functions
bool checkPricerImpl (const boost::shared_ptr< InflationCouponPricer > &) const
makes sure you were given the correct type of pricer
Rate indexFixing (const Date &) const
Protected Attributes
Real baseCPI_
Real fixedRate_
Spread spread_
CPI::InterpolationType observationInterpolation_
Detailed Description
Coupon paying the performance of a CPI (zero inflation) index
The performance is relative to the index value on the base date.
The other inflation value is taken from the refPeriodEnd date with observation lag, so any roll/calendar etc. will be built in by the caller. By default this is done in the InflationCoupon which uses ModifiedPreceding with fixing days assumed positive meaning earlier, i.e. always stay in same month (relative to referencePeriodEnd).
This is more sophisticated than an IndexedCashFlow because it does date calculations itself.
Todo:
we do not do any convexity adjustment for lags different to the natural ZCIIS lag that was used to create the forward inflation curve.
Definition at line 63 of file cpicoupon.hpp.
Constructor & Destructor Documentation
QuantLib::CPICoupon::CPICoupon (Real baseCPI, const Date & paymentDate, Real nominal, const Date & startDate, const Date & endDate, Natural fixingDays, const boost::shared_ptr< ZeroInflationIndex > & index, const Period & observationLag, CPI::InterpolationType observationInterpolation, const DayCounter & dayCounter, Real fixedRate, Spread spread = 0.0, const Date & refPeriodStart = Date(), const Date & refPeriodEnd = Date())
Definition at line 33 of file cpicoupon.cpp.
References baseCPI_, and QL_REQUIRE.
    : InflationCoupon(paymentDate, nominal, startDate, endDate,
                      fixingDays, zeroIndex, observationLag,
                      dayCounter, refPeriodStart, refPeriodEnd),
        baseCPI_(baseCPI), fixedRate_(fixedRate), spread_(spread),
        observationInterpolation_(observationInterpolation) {
            QL_REQUIRE(fabs(baseCPI_) > 1e-16,
                       "|baseCPI_| < 1e-16, future divide-by-zero problem");
        }
Member Function Documentation
void QuantLib::CPICoupon::accept (AcyclicVisitor & v) [virtual]
Reimplemented from QuantLib::InflationCoupon.
Definition at line 59 of file cpicoupon.cpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Visitor< T >::visit().
{
        Visitor<CPICoupon>* v1 =
        dynamic_cast<Visitor<CPICoupon>*>(&v);
        if (v1 != 0)
            v1->visit(*this);
        else
            InflationCoupon::accept(v);
    }
Rate QuantLib::CPICoupon::adjustedFixing () const [inline]
adjusted fixing (already divided by the base fixing)
Definition at line 228 of file cpicoupon.hpp.
References fixedRate(), QuantLib::InflationCoupon::rate(), and spread().
{
        return (rate()-spread())/fixedRate();
    }
Rate QuantLib::CPICoupon::baseCPI () const [inline]
base value for the CPI index
Warning:
make sure that the interpolation used to create this is what you are using for the fixing, i.e. the observationInterpolation.
Definition at line 236 of file cpicoupon.hpp.
References baseCPI_.
Referenced by QuantLib::CPICouponPricer::adjustedFixing().
{
        return baseCPI_;
    }
bool QuantLib::CPICoupon::checkPricerImpl (const boost::shared_ptr< InflationCouponPricer > &) const [protected, virtual]
makes sure you were given the correct type of pricer
Implements QuantLib::InflationCoupon.
Definition at line 69 of file cpicoupon.cpp.
References QuantLib::InflationCoupon::pricer().
{
        return boost::dynamic_pointer_cast<CPICouponPricer>(pricer);
    }
boost::shared_ptr< ZeroInflationIndex > QuantLib::CPICoupon::cpiIndex () const [inline]
index used
Definition at line 248 of file cpicoupon.hpp.
References QuantLib::InflationCoupon::index().
Referenced by indexFixing().
{
        return boost::dynamic_pointer_cast<ZeroInflationIndex>(index());
    }
Real QuantLib::CPICoupon::fixedRate () const [inline]
fixed rate that will be inflated by the index ratio
Definition at line 220 of file cpicoupon.hpp.
References fixedRate_.
Referenced by adjustedFixing(), and QuantLib::CPICouponPricer::initialize().
{
        return fixedRate_;
    }
Rate QuantLib::CPICoupon::indexFixing () const [inline, virtual]
allows for a different interpolation from the index
Reimplemented from QuantLib::InflationCoupon.
Definition at line 232 of file cpicoupon.hpp.
References QuantLib::InflationCoupon::fixingDate().
Referenced by QuantLib::CPICouponPricer::adjustedFixing(), indexObservation(), and QuantLib::CPICouponPricer::optionletPrice().
{
        return indexFixing(fixingDate());
    }
Rate QuantLib::CPICoupon::indexFixing (const Date & d) const [protected]
Definition at line 75 of file cpicoupon.cpp.
References QuantLib::CPI::AsIndex, cpiIndex(), QuantLib::Days, QuantLib::inflationPeriod(), QuantLib::CPI::Linear, and observationInterpolation().
{
        // you may want to modify the interpolation of the index
        // this gives you the chance
        Rate I1;
        // what interpolation do we use? Index / flat / linear
        if (observationInterpolation() == CPI::AsIndex) {
            I1 = cpiIndex()->fixing(d);
        } else {
            // work out what it should be
            std::pair<Date,Date> dd = inflationPeriod(d, cpiIndex()->frequency());
            Real indexStart = cpiIndex()->fixing(dd.first);
            if (observationInterpolation() == CPI::Linear) {
                Real indexEnd = cpiIndex()->fixing(dd.second+Period(1,Days));
                // linear interpolation
                I1 = indexStart + (indexEnd - indexStart) * (d - dd.first)
                / (Real)( (dd.second+Period(1,Days)) - dd.first); // can't get to next period's value within current period
            } else {
                // no interpolation, i.e. flat = constant, so use start-of-period value
                I1 = indexStart;
            }
        }
        return I1;
    }
Rate QuantLib::CPICoupon::indexObservation (const Date & onDate) const [inline]
utility method, calls indexFixing
Definition at line 244 of file cpicoupon.hpp.
References indexFixing().
{
        return indexFixing(onDate);
    }
CPI::InterpolationType QuantLib::CPICoupon::observationInterpolation () const [inline]
how do you observe the index? as-is, flat, linear?
Definition at line 240 of file cpicoupon.hpp.
References observationInterpolation_.
Referenced by indexFixing().
{
        return observationInterpolation_;
    }
Real QuantLib::CPICoupon::spread () const [inline]
spread paid over the fixing of the underlying index
Definition at line 224 of file cpicoupon.hpp.
References spread_.
Referenced by adjustedFixing(), and QuantLib::CPICouponPricer::initialize().
{
        return spread_;
    }
Member Data Documentation
Real QuantLib::CPICoupon::baseCPI_ [protected]
Definition at line 110 of file cpicoupon.hpp.
Referenced by baseCPI(), and CPICoupon().
Real QuantLib::CPICoupon::fixedRate_ [protected]
Definition at line 111 of file cpicoupon.hpp.
Referenced by fixedRate().
CPI::InterpolationType QuantLib::CPICoupon::observationInterpolation_ [protected]
Definition at line 113 of file cpicoupon.hpp.
Referenced by observationInterpolation().
Spread QuantLib::CPICoupon::spread_ [protected]
Definition at line 112 of file cpicoupon.hpp.
Referenced by spread().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/cpicoupon.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/cpicoupon.cpp