QuantLib: QuantLib::CashOrNothingPayoff Class Reference
QuantLib::CashOrNothingPayoff Class Reference
Binary cash-or-nothing payoff.
#include <payoffs.hpp>
Public Member Functions
CashOrNothingPayoff (Option::Type type, Real strike, Real cashPayoff)
Real cashPayoff () const
Payoff interface
std::string name () const
std::string description () const
Real operator() (Real price) const
virtual void accept (AcyclicVisitor &)
Protected Attributes
Real cashPayoff_
Detailed Description
Binary cash-or-nothing payoff.
Definition at line 151 of file payoffs.hpp.
Constructor & Destructor Documentation
QuantLib::CashOrNothingPayoff::CashOrNothingPayoff (Option::Type type, Real strike, Real cashPayoff) [inline]
Definition at line 153 of file payoffs.hpp.
        : StrikedTypePayoff(type, strike), cashPayoff_(cashPayoff) {}
Member Function Documentation
void QuantLib::CashOrNothingPayoff::accept (AcyclicVisitor & v) [virtual]
Reimplemented from QuantLib::Payoff.
Definition at line 159 of file payoffs.cpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Visitor< T >::visit().
{
        Visitor<CashOrNothingPayoff>* v1 =
            dynamic_cast<Visitor<CashOrNothingPayoff>*>(&v);
        if (v1 != 0)
            v1->visit(*this);
        else
            Payoff::accept(v);}
Real QuantLib::CashOrNothingPayoff::cashPayoff () const [inline]
Definition at line 164 of file payoffs.hpp.
References cashPayoff_.
Referenced by description(), and QuantLib::BlackCalculator::Calculator::visit().
{ return cashPayoff_;}
std::string QuantLib::CashOrNothingPayoff::description () const [virtual]
Reimplemented from QuantLib::StrikedTypePayoff.
Definition at line 142 of file payoffs.cpp.
References cashPayoff().
{
        std::ostringstream result;
        result << StrikedTypePayoff::description() << ", " << cashPayoff() << " cash payoff";
        return result.str();
    }
std::string QuantLib::CashOrNothingPayoff::name () const [inline, virtual]
Warning:
This method is used for output and comparison between payoffs. It is not meant to be used for writing switch-on-type code.
Implements QuantLib::Payoff.
Definition at line 159 of file payoffs.hpp.
{ return "CashOrNothing";}
Real QuantLib::CashOrNothingPayoff::operator() (Real price) const [virtual]
Implements QuantLib::Payoff.
Definition at line 148 of file payoffs.cpp.
References QuantLib::Option::Call, cashPayoff_, QuantLib::Option::Put, QL_FAIL, QuantLib::StrikedTypePayoff::strike_, and QuantLib::TypePayoff::type_.
{
        switch (type_) {
          case Option::Call:
            return (price-strike_ > 0.0 ? cashPayoff_ : 0.0);
          case Option::Put:
            return (strike_-price > 0.0 ? cashPayoff_ : 0.0);
          default:
            QL_FAIL("unknown/illegal option type");
        }
    }
Member Data Documentation
Real QuantLib::CashOrNothingPayoff::cashPayoff_ [protected]
Definition at line 166 of file payoffs.hpp.
Referenced by cashPayoff(), and operator()().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/payoffs.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/payoffs.cpp