QuantLib: AutocovariancesTest Class Reference
AutocovariancesTest Class Reference
#include <autocovariances.hpp>
Static Public Member Functions
static void testConvolutions ()
static void testAutoCovariances ()
static void testAutoCorrelations ()
static
boost::unit_test_framework::test_suite * suite ()
Detailed Description
Definition at line 28 of file autocovariances.hpp.
Member Function Documentation
test_suite * AutocovariancesTest::suite () [static]
Definition at line 87 of file autocovariances.cpp.
References QUANTLIB_TEST_CASE, testAutoCorrelations(), testAutoCovariances(), and testConvolutions().
Referenced by init_unit_test_suite().
{
    test_suite* suite = BOOST_TEST_SUITE("auto-covariance tests");
    suite->add(QUANTLIB_TEST_CASE(&AutocovariancesTest::testConvolutions));
    suite->add(QUANTLIB_TEST_CASE(&AutocovariancesTest::testAutoCovariances));
    suite->add(QUANTLIB_TEST_CASE(&AutocovariancesTest::testAutoCorrelations));
    return suite;
}
void AutocovariancesTest::testAutoCorrelations () [static]
Definition at line 61 of file autocovariances.cpp.
References QuantLib::autocorrelations(), QuantLib::Array::begin(), QuantLib::DotProduct(), QuantLib::Array::end(), and QL_SCIENTIFIC.
Referenced by suite().
{
    BOOST_MESSAGE("Testing auto-correlations...");
    Array x(10, 1, 1);
    Array acorf(6);
    Real mean = autocorrelations(x.begin(), x.end(), acorf.begin(), 5, true);
    Real expected[] = { 9.166667, 0.77777778, 0.51515152,
                        0.21212121, -0.13131313, -0.51515152 };
    if (std::fabs(mean-5.5) > 1.0e-6) {
        BOOST_ERROR("Mean: \n"
                    << "    calculated:   " << mean << "\n"
                    << "    expected:     " << 5.5);
    }
    Array delta = acorf - Array(expected, expected+6);
    if (DotProduct(delta, delta) > 1.0e-6)
        BOOST_ERROR("Autocovariances: \n"
                    << std::setprecision(4) << QL_SCIENTIFIC
                    << "    calculated:   " << acorf << "\n"
                    << "    expected:     " << Array(expected, expected+6));
    delta = x - Array(10, -4.5, 1);
    if (DotProduct(delta, delta) > 1.0e-6)
        BOOST_ERROR("Centering: \n"
                    << std::setprecision(4) << QL_SCIENTIFIC
                    << "    calculated:   " << x << "\n"
                    << "    expected:     " << Array(10, -4.5, 1));
}
void AutocovariancesTest::testAutoCovariances () [static]
Definition at line 42 of file autocovariances.cpp.
References QuantLib::autocovariances(), QuantLib::Array::begin(), QuantLib::DotProduct(), QuantLib::Array::end(), and QL_SCIENTIFIC.
Referenced by suite().
{
    BOOST_MESSAGE("Testing auto-covariances...");
    Array x(10, 1, 1);
    Array acovf(6);
    Real mean = autocovariances(x.begin(), x.end(), acovf.begin(), 5, false);
    Real expected[] = { 8.25, 6.416667, 4.25, 1.75, -1.08333, -4.25 };
    if (std::fabs(mean-5.5) > 1.0e-6) {
        BOOST_ERROR("Mean: \n"
                    << "    calculated:   " << mean << "\n"
                    << "    expected:     " << 5.5);
    }
    Array delta = acovf - Array(expected, expected+6);
    if (DotProduct(delta, delta) > 1.0e-6)
        BOOST_ERROR("Autocovariances: \n"
                    << std::setprecision(4) << QL_SCIENTIFIC
                    << "    calculated:   " << acovf << "\n"
                    << "    expected:     " << Array(expected, expected+6));
}
void AutocovariancesTest::testConvolutions () [static]
Definition at line 28 of file autocovariances.cpp.
References QuantLib::Array::begin(), QuantLib::convolutions(), QuantLib::DotProduct(), QuantLib::Array::end(), and QL_SCIENTIFIC.
Referenced by suite().
{
    BOOST_MESSAGE("Testing convolutions...");
    Array x(10, 1, 1);
    Array conv(6);
    convolutions(x.begin(), x.end(), conv.begin(), 5);
    Real expected[] = { 385, 330, 276, 224, 175, 130 };
    Array delta = conv - Array(expected, expected+6);
    if (DotProduct(delta, delta) > 1.0e-6)
        BOOST_ERROR("Convolution: \n"
                    << std::setprecision(4) << QL_SCIENTIFIC
                    << "    calculated:   " << conv << "\n"
                    << "    expected:     " << Array(expected, expected+6));
}
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/autocovariances.hpp
/home/deriversatile/QuantLib/QuantLibQt/test-suite/autocovariances.cpp