QuantLib: QuantLib::BlackVarianceTermStructure Class Reference
QuantLib::BlackVarianceTermStructure Class Reference
Black variance term structure.
#include <blackvoltermstructure.hpp>
Public Member Functions
Constructors
See the TermStructure documentation for issues regarding constructors.
BlackVarianceTermStructure (const Calendar &cal, BusinessDayConvention bdc=Following, const DayCounter &dc=DayCounter())
BlackVarianceTermStructure (BusinessDayConvention bdc=Following, const DayCounter &dc=DayCounter())
default constructor
BlackVarianceTermStructure (const Date &referenceDate, const Calendar &cal=Calendar(), BusinessDayConvention bdc=Following, const DayCounter &dc=DayCounter())
initialize with a fixed reference date
BlackVarianceTermStructure (Natural settlementDays, const Calendar &, BusinessDayConvention bdc=Following, const DayCounter &dc=DayCounter())
calculate the reference date based on the global evaluation date
Visitability
virtual void accept (AcyclicVisitor &)
Protected Member Functions
Volatility blackVolImpl (Time t, Real strike) const
Detailed Description
Black variance term structure.
This abstract class acts as an adapter to VolTermStructure allowing the programmer to implement only the blackVarianceImpl(Time, Real, bool) method in derived classes.
Volatility are assumed to be expressed on an annual basis.
Definition at line 197 of file blackvoltermstructure.hpp.
Constructor & Destructor Documentation
QuantLib::BlackVarianceTermStructure::BlackVarianceTermStructure (const Calendar & cal, BusinessDayConvention bdc = Following, const DayCounter & dc = DayCounter())
Warning:
term structures initialized by means of this constructor must manage their own reference date by overriding the referenceDate() method.
Definition at line 153 of file blackvoltermstructure.cpp.
    : BlackVolTermStructure(cal, bdc, dc) {}
QuantLib::BlackVarianceTermStructure::BlackVarianceTermStructure (BusinessDayConvention bdc = Following, const DayCounter & dc = DayCounter())
default constructor
Warning:
term structures initialized by means of this constructor must manage their own reference date by overriding the referenceDate() method.
Definition at line 160 of file blackvoltermstructure.cpp.
    : BlackVolTermStructure(bdc, dc) {}
QuantLib::BlackVarianceTermStructure::BlackVarianceTermStructure (const Date & referenceDate, const Calendar & cal = Calendar(), BusinessDayConvention bdc = Following, const DayCounter & dc = DayCounter())
initialize with a fixed reference date
Definition at line 165 of file blackvoltermstructure.cpp.
    : BlackVolTermStructure(refDate, cal, bdc, dc) {}
QuantLib::BlackVarianceTermStructure::BlackVarianceTermStructure (Natural settlementDays, const Calendar & cal, BusinessDayConvention bdc = Following, const DayCounter & dc = DayCounter())
calculate the reference date based on the global evaluation date
Definition at line 172 of file blackvoltermstructure.cpp.
    : BlackVolTermStructure(settlementDays, cal, bdc, dc) {}
Member Function Documentation
void QuantLib::BlackVarianceTermStructure::accept (AcyclicVisitor & v) [inline, virtual]
Reimplemented from QuantLib::BlackVolTermStructure.
Reimplemented in QuantLib::BlackVarianceSurface, QuantLib::BlackVarianceCurve, QuantLib::ExtendedBlackVarianceSurface, QuantLib::ExtendedBlackVarianceCurve, and QuantLib::ImpliedVolTermStructure.
Definition at line 314 of file blackvoltermstructure.hpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Visitor< T >::visit().
{
        Visitor<BlackVarianceTermStructure>* v1 =
            dynamic_cast<Visitor<BlackVarianceTermStructure>*>(&v);
        if (v1 != 0)
            v1->visit(*this);
        else
            BlackVolTermStructure::accept(v);
    }
Volatility QuantLib::BlackVarianceTermStructure::blackVolImpl (Time t, Real strike) const [inline, protected, virtual]
Returns the volatility for the given strike and date calculating it from the variance.
Implements QuantLib::BlackVolTermStructure.
Definition at line 307 of file blackvoltermstructure.hpp.
References QuantLib::BlackVolTermStructure::blackVarianceImpl(), and anonymous_namespace{quantlibbenchmark.cpp}::t.
{
        Time nonZeroMaturity = (t==0.0 ? 0.00001 : t);
        Real var = blackVarianceImpl(nonZeroMaturity, strike);
        return std::sqrt(var/nonZeroMaturity);
    }
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/equityfx/blackvoltermstructure.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/equityfx/blackvoltermstructure.cpp