QuantLib: ChooserOptionTest Class Reference
ChooserOptionTest Class Reference
#include <chooseroption.hpp>
Static Public Member Functions
static void testAnalyticSimpleChooserEngine ()
static
boost::unit_test_framework::test_suite * suite ()
Detailed Description
Definition at line 25 of file chooseroption.hpp.
Member Function Documentation
test_suite * ChooserOptionTest::suite () [static]
Definition at line 101 of file chooseroption.cpp.
References QUANTLIB_TEST_CASE, and testAnalyticSimpleChooserEngine().
Referenced by init_unit_test_suite().
{
    test_suite* suite = BOOST_TEST_SUITE("Chooser option tests");
    suite->add(QUANTLIB_TEST_CASE(
        &ChooserOptionTest::testAnalyticSimpleChooserEngine));
    return suite;
}
void ChooserOptionTest::testAnalyticSimpleChooserEngine () [static]
Definition at line 52 of file chooseroption.cpp.
References QuantLib::flatRate(), QuantLib::flatVol(), QuantLib::Instrument::NPV(), REPORT_FAILURE, QuantLib::Instrument::setPricingEngine(), anonymous_namespace{marketmodel.cpp}::todaysDate, and anonymous_namespace{gaussianquadratures.cpp}::tolerance.
Referenced by suite().
{
    BOOST_MESSAGE("Testing analytic simple chooser option...");
    /* The data below are from
       "Complete Guide to Option Pricing Formulas", Espen Gaarder Haug
       pages 39-40
    */
    DayCounter dc = Actual360();
    Date today = Date::todaysDate();
    boost::shared_ptr<SimpleQuote> spot(new SimpleQuote(50.0));
    boost::shared_ptr<SimpleQuote> qRate(new SimpleQuote(0.0));
    boost::shared_ptr<YieldTermStructure> qTS = flatRate(today, qRate, dc);
    boost::shared_ptr<SimpleQuote> rRate(new SimpleQuote(0.08));
    boost::shared_ptr<YieldTermStructure> rTS = flatRate(today, rRate, dc);
    boost::shared_ptr<SimpleQuote> vol(new SimpleQuote(0.25));
    boost::shared_ptr<BlackVolTermStructure> volTS = flatVol(today, vol, dc);
    boost::shared_ptr<BlackScholesMertonProcess> stochProcess(new
        BlackScholesMertonProcess(Handle<Quote>(spot),
                                  Handle<YieldTermStructure>(qTS),
                                  Handle<YieldTermStructure>(rTS),
                                  Handle<BlackVolTermStructure>(volTS)));
    boost::shared_ptr<PricingEngine> engine(
        new AnalyticSimpleChooserEngine(stochProcess));
    Real strike = 50.0;
    Date exerciseDate = today + 180;
    boost::shared_ptr<Exercise> exercise(new EuropeanExercise(exerciseDate));
    Date choosingDate = today + 90;
    SimpleChooserOption option(choosingDate,strike,exercise);
    option.setPricingEngine(engine);
    Real calculated = option.NPV();
     Real expected = 6.1071;
    Real tolerance = 3e-5;
    if (std::fabs(calculated-expected) > tolerance) {
        REPORT_FAILURE("value", choosingDate,
                       exercise, spot->value(),
                       qRate->value(), rRate->value(), today,
                       vol->value(), expected, calculated, tolerance);
    }
}
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/chooseroption.hpp
/home/deriversatile/QuantLib/QuantLibQt/test-suite/chooseroption.cpp