QuantLib: QuantLib::CovarianceDecomposition Class Reference
QuantLib::CovarianceDecomposition Class Reference
Covariance decomposition into correlation and variances.
#include <getcovariance.hpp>
Public Member Functions
CovarianceDecomposition (const Matrix &covarianceMatrix, Real tolerance=1.0e-12)
const Array & variances () const
const Array & standardDeviations () const
const Matrix & correlationMatrix () const
Private Attributes
Array variances_
Array stdDevs_
Matrix correlationMatrix_
Detailed Description
Covariance decomposition into correlation and variances.
Extracts the correlation matrix and the vector of variances out of the input covariance matrix.
Note that only the lower symmetric part of the covariance matrix is used.
Precondition:
The covariance matrix must be symmetric.
Test:
cross checked with getCovariance
Definition at line 95 of file getcovariance.hpp.
Constructor & Destructor Documentation
QuantLib::CovarianceDecomposition::CovarianceDecomposition (const Matrix & covarianceMatrix, Real tolerance = 1.0e-12)
Precondition:
covarianceMatrix must be symmetric
Definition at line 24 of file getcovariance.cpp.
References QuantLib::Matrix::columns(), correlationMatrix_, QL_REQUIRE, QuantLib::Matrix::rows(), stdDevs_, and variances_.
    : variances_(cov.diagonal()), stdDevs_(Array(cov.rows())),
      correlationMatrix_(Matrix(cov.rows(), cov.rows()))
    {
        Size size = cov.rows();
        QL_REQUIRE(size==cov.columns(),
                   "input covariance matrix must be square, it is [" <<
                   size << "x" << cov.rows() << "]");
        for (Size i=0; i<size; ++i)
        {
            stdDevs_[i] = std::sqrt(variances_[i]);
            correlationMatrix_[i][i] = 1.0;
            for (Size j=0; j<i; ++j)
            {
                QL_REQUIRE(std::fabs(cov[i][j]-cov[j][i]) <= tolerance,
                           "invalid covariance matrix:" <<
                           "\nc[" << i << ", " << j << "] = " <<
                           cov[i][j] << "\nc[" << j << ", " << i <<
                           "] = " << cov[j][i]);
                correlationMatrix_[i][j] = correlationMatrix_[j][i] =
                    cov[i][j]/(stdDevs_[i]*stdDevs_[j]);
            }
        }
    }
Member Function Documentation
const Matrix& QuantLib::CovarianceDecomposition::correlationMatrix () const [inline]
returns the correlation matrix
Definition at line 106 of file getcovariance.hpp.
References correlationMatrix_.
Referenced by QuantLib::CotSwapFromFwdCorrelation::CotSwapFromFwdCorrelation(), and CovarianceTest::testCovariance().
{ return correlationMatrix_; }
const Array& QuantLib::CovarianceDecomposition::standardDeviations () const [inline]
returns the standard deviations Array
Definition at line 104 of file getcovariance.hpp.
References stdDevs_.
Referenced by CovarianceTest::testCovariance().
{return stdDevs_; }
const Array& QuantLib::CovarianceDecomposition::variances () const [inline]
returns the variances Array
Definition at line 102 of file getcovariance.hpp.
References variances_.
{ return variances_; }
Member Data Documentation
Matrix QuantLib::CovarianceDecomposition::correlationMatrix_ [private]
Definition at line 109 of file getcovariance.hpp.
Referenced by correlationMatrix(), and CovarianceDecomposition().
Array QuantLib::CovarianceDecomposition::stdDevs_ [private]
Definition at line 108 of file getcovariance.hpp.
Referenced by CovarianceDecomposition(), and standardDeviations().
Array QuantLib::CovarianceDecomposition::variances_ [private]
Definition at line 108 of file getcovariance.hpp.
Referenced by CovarianceDecomposition(), and variances().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/matrixutilities/getcovariance.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/math/matrixutilities/getcovariance.cpp