QuantLib: QuantLib::VariancePathPricer Class Reference
QuantLib::VariancePathPricer Class Reference
#include <mcvarianceswapengine.hpp>
Public Member Functions
VariancePathPricer (const boost::shared_ptr< GeneralizedBlackScholesProcess > &process)
Real operator() (const Path &path) const
Private Attributes
boost::shared_ptr
< GeneralizedBlackScholesProcess > process_
Detailed Description
Definition at line 154 of file mcvarianceswapengine.hpp.
Constructor & Destructor Documentation
QuantLib::VariancePathPricer::VariancePathPricer (const boost::shared_ptr< GeneralizedBlackScholesProcess > & process) [inline]
Definition at line 156 of file mcvarianceswapengine.hpp.
        : process_(process) {}
Member Function Documentation
Real QuantLib::VariancePathPricer::operator() (const Path & path) const [inline, virtual]
Implements QuantLib::PathPricer< Path >.
Definition at line 338 of file mcvarianceswapengine.hpp.
References QuantLib::TimeGrid::back(), QuantLib::anonymous_namespace{yieldtermstructure.cpp}::dt, QuantLib::TimeGrid::dt(), anonymous_namespace{interpolations.cpp}::f(), QuantLib::TimeGrid::front(), QuantLib::Path::length(), process_, QL_REQUIRE, anonymous_namespace{quantlibbenchmark.cpp}::t, and QuantLib::Path::timeGrid().
{
        QL_REQUIRE(path.length() > 0, "the path cannot be empty");
        Time t0 = path.timeGrid().front();
        Time t = path.timeGrid().back();
        Time dt = path.timeGrid().dt(0);
        SegmentIntegral integrator(static_cast<Size>(t/dt));
        detail::Integrand f(path, process_);
        return integrator(f,t0,t)/t;
    }
Member Data Documentation
boost::shared_ptr<GeneralizedBlackScholesProcess> QuantLib::VariancePathPricer::process_ [private]
Definition at line 161 of file mcvarianceswapengine.hpp.
Referenced by operator()().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/forward/mcvarianceswapengine.hpp