QuantLib: QuantLib::RendistatoCalculator Class Reference
QuantLib::RendistatoCalculator Class Reference
#include <btp.hpp>
Public Member Functions
RendistatoCalculator (const boost::shared_ptr< RendistatoBasket > &basket, const boost::shared_ptr< Euribor > &euriborIndex, const Handle< YieldTermStructure > &discountCurve)
Calculations
Rate yield () const
Time duration () const
const std::vector< Rate > & yields () const
const std::vector< Time > & durations () const
const std::vector< Time > & swapLengths () const
const std::vector< Rate > & swapRates () const
const std::vector< Rate > & swapYields () const
const std::vector< Time > & swapDurations () const
Equivalent Swap proxy
boost::shared_ptr< VanillaSwap > equivalentSwap () const
Rate equivalentSwapRate () const
Rate equivalentSwapYield () const
Time equivalentSwapDuration () const
Time equivalentSwapLength () const
Spread equivalentSwapSpread () const
Protected Member Functions
LazyObject interface
void performCalculations () const
Private Attributes
boost::shared_ptr
< RendistatoBasket > basket_
boost::shared_ptr< Euribor > euriborIndex_
Handle< YieldTermStructure > discountCurve_
std::vector< Rate > yields_
std::vector< Time > durations_
Time duration_
Size equivalentSwapIndex_
Size nSwaps_
std::vector< boost::shared_ptr
< VanillaSwap > > swaps_
std::vector< Time > swapLenghts_
std::vector< Time > swapBondDurations_
std::vector< Rate > swapBondYields_
std::vector< Rate > swapRates_
Detailed Description
Definition at line 108 of file btp.hpp.
Constructor & Destructor Documentation
QuantLib::RendistatoCalculator::RendistatoCalculator (const boost::shared_ptr< RendistatoBasket > & basket, const boost::shared_ptr< Euribor > & euriborIndex, const Handle< YieldTermStructure > & discountCurve)
Definition at line 135 of file btp.cpp.
References basket_, QuantLib::Days, discountCurve_, euriborIndex_, nSwaps_, QuantLib::Observer::registerWith(), swapLenghts_, swaps_, QuantLib::MakeVanillaSwap::withDiscountingTermStructure(), and QuantLib::Years.
    : basket_(basket),
      euriborIndex_(euriborIndex), discountCurve_(discountCurve),
      yields_(basket_->size(), 0.05), durations_(basket_->size()),
      nSwaps_(15), // TODO: generalize number of swaps and their lenghts
      swaps_(nSwaps_),
      swapLenghts_(nSwaps_), swapBondDurations_(nSwaps_, Null<Time>()),
      swapBondYields_(nSwaps_, 0.05), swapRates_(nSwaps_, Null<Rate>())
    {
        registerWith(basket_);
        registerWith(euriborIndex_);
        registerWith(discountCurve_);
        Rate dummyRate = 0.05;
        for (Size i=0; i<nSwaps_; ++i) {
            swapLenghts_[i] = i+1;
            swaps_[i] = MakeVanillaSwap(
                swapLenghts_[i]*Years, euriborIndex_, dummyRate, 1*Days)
                                .withDiscountingTermStructure(discountCurve_);
        }
    }
Member Function Documentation
Time QuantLib::RendistatoCalculator::duration () const [inline]
Definition at line 197 of file btp.hpp.
References QuantLib::LazyObject::calculate(), and duration_.
Referenced by performCalculations().
{
        calculate();
        return duration_;
    }
const std::vector< Time > & QuantLib::RendistatoCalculator::durations () const [inline]
Definition at line 207 of file btp.hpp.
References QuantLib::LazyObject::calculate(), and durations_.
{
        calculate();
        return durations_;
    }
boost::shared_ptr< VanillaSwap > QuantLib::RendistatoCalculator::equivalentSwap () const [inline]
Definition at line 232 of file btp.hpp.
References QuantLib::LazyObject::calculate(), equivalentSwapIndex_, and swaps_.
{
        calculate();
        return swaps_[equivalentSwapIndex_];
    }
Time QuantLib::RendistatoCalculator::equivalentSwapDuration () const [inline]
Definition at line 247 of file btp.hpp.
References QuantLib::LazyObject::calculate(), equivalentSwapIndex_, and swapBondDurations_.
{
        calculate();
        return swapBondDurations_[equivalentSwapIndex_];
    }
Time QuantLib::RendistatoCalculator::equivalentSwapLength () const [inline]
Definition at line 252 of file btp.hpp.
References QuantLib::LazyObject::calculate(), equivalentSwapIndex_, and swapLenghts_.
{
        calculate();
        return swapLenghts_[equivalentSwapIndex_];
    }
Rate QuantLib::RendistatoCalculator::equivalentSwapRate () const [inline]
Definition at line 237 of file btp.hpp.
References QuantLib::LazyObject::calculate(), equivalentSwapIndex_, and swapRates_.
Referenced by equivalentSwapSpread().
{
        calculate();
        return swapRates_[equivalentSwapIndex_];
    }
Spread QuantLib::RendistatoCalculator::equivalentSwapSpread () const [inline]
Definition at line 257 of file btp.hpp.
References equivalentSwapRate(), and yield().
{
        return yield() - equivalentSwapRate();
    }
Rate QuantLib::RendistatoCalculator::equivalentSwapYield () const [inline]
Definition at line 242 of file btp.hpp.
References QuantLib::LazyObject::calculate(), equivalentSwapIndex_, and swapBondYields_.
{
        calculate();
        return swapBondYields_[equivalentSwapIndex_];
    }
void QuantLib::RendistatoCalculator::performCalculations () const [protected, virtual]
This method must implement any calculations which must be (re)done in order to calculate the desired results.
Implements QuantLib::LazyObject.
Definition at line 160 of file btp.cpp.
References QuantLib::Annual, basket_, QuantLib::Compounded, duration(), duration_, durations_, equivalentSwapIndex_, QuantLib::Following, QuantLib::dsd::inner_product(), QuantLib::ActualActual::ISMA, QuantLib::Duration::Modified, nSwaps_, swapBondDurations_, swapBondYields_, swapRates_, swaps_, yield(), and yields_.
{
        const std::vector<boost::shared_ptr<BTP> >& btps = basket_->btps();
        const std::vector<Handle<Quote> >& quotes = basket_->cleanPriceQuotes();
        Date bondSettlementDate = btps[0]->settlementDate();
        for (Size i=0; i<basket_->size(); ++i) {
            yields_[i] = BondFunctions::yield(
                *btps[i], quotes[i]->value(),
                ActualActual(ActualActual::ISMA), Compounded, Annual,
                bondSettlementDate,
                // accuracy, maxIterations, guess
                1.0e-10, 100, yields_[i]);
            durations_[i] = BondFunctions::duration(
                *btps[i], yields_[i],
                ActualActual(ActualActual::ISMA), Compounded, Annual,
                Duration::Modified, bondSettlementDate);
        }
        duration_ = std::inner_product(basket_->weights().begin(),
                                       basket_->weights().end(),
                                       durations_.begin(), 0.0);
        Natural settlDays = 3;
        DayCounter fixedDayCount = swaps_[0]->fixedDayCount();
        equivalentSwapIndex_ = nSwaps_-1;
        swapRates_[0]= swaps_[0]->fairRate();
        FixedRateBond swapBond(settlDays,
                               100.0,      // faceAmount
                               swaps_[0]->fixedSchedule(),
                               std::vector<Rate>(1, swapRates_[0]),
                               fixedDayCount,
                               Following, // paymentConvention
                               100.0);    // redemption
        swapBondYields_[0] = BondFunctions::yield(swapBond,
            100.0, // floating leg NPV including end payment
            ActualActual(ActualActual::ISMA), Compounded, Annual,
            bondSettlementDate,
            // accuracy, maxIterations, guess
            1.0e-10, 100, swapBondYields_[0]);
        swapBondDurations_[0] = BondFunctions::duration(
            swapBond, swapBondYields_[0],
            ActualActual(ActualActual::ISMA), Compounded, Annual,
            Duration::Modified, bondSettlementDate);
        for (Size i=1; i<nSwaps_; ++i) {
            swapRates_[i]= swaps_[i]->fairRate();
            FixedRateBond swapBond(settlDays,
                                   100.0,      // faceAmount
                                   swaps_[i]->fixedSchedule(),
                                   std::vector<Rate>(1, swapRates_[i]),
                                   fixedDayCount,
                                   Following, // paymentConvention
                                   100.0);    // redemption
            swapBondYields_[i] = BondFunctions::yield(swapBond,
                100.0, // floating leg NPV including end payment
                ActualActual(ActualActual::ISMA), Compounded, Annual,
                bondSettlementDate,
                // accuracy, maxIterations, guess
                1.0e-10, 100, swapBondYields_[i]);
            swapBondDurations_[i] = BondFunctions::duration(
                swapBond, swapBondYields_[i],
                ActualActual(ActualActual::ISMA), Compounded, Annual,
                Duration::Modified, bondSettlementDate);
            if (swapBondDurations_[i] > duration_) {
                equivalentSwapIndex_ = i-1;
                break; // exit the loop
            }
        }
        return;
    }
const std::vector< Time > & QuantLib::RendistatoCalculator::swapDurations () const [inline]
Definition at line 226 of file btp.hpp.
References QuantLib::LazyObject::calculate(), and swapBondDurations_.
{
        calculate();
        return swapBondDurations_;
    }
const std::vector< Time > & QuantLib::RendistatoCalculator::swapLengths () const [inline]
Definition at line 212 of file btp.hpp.
References swapLenghts_.
{
        return swapLenghts_;
    }
const std::vector< Rate > & QuantLib::RendistatoCalculator::swapRates () const [inline]
Definition at line 216 of file btp.hpp.
References QuantLib::LazyObject::calculate(), and swapRates_.
{
        calculate();
        return swapRates_;
    }
const std::vector< Rate > & QuantLib::RendistatoCalculator::swapYields () const [inline]
Definition at line 221 of file btp.hpp.
References QuantLib::LazyObject::calculate(), and swapBondYields_.
{
        calculate();
        return swapBondYields_;
    }
Rate QuantLib::RendistatoCalculator::yield () const [inline]
Definition at line 191 of file btp.hpp.
References basket_, QuantLib::dsd::inner_product(), and yields().
Referenced by equivalentSwapSpread(), and performCalculations().
{
        return std::inner_product(basket_->weights().begin(),
                                  basket_->weights().end(),
                                  yields().begin(), 0.0);
    }
const std::vector< Rate > & QuantLib::RendistatoCalculator::yields () const [inline]
Definition at line 202 of file btp.hpp.
References QuantLib::LazyObject::calculate(), and yields_.
Referenced by yield().
{
        calculate();
        return yields_;
    }
Member Data Documentation
boost::shared_ptr<RendistatoBasket> QuantLib::RendistatoCalculator::basket_ [private]
Definition at line 141 of file btp.hpp.
Referenced by performCalculations(), RendistatoCalculator(), and yield().
Handle<YieldTermStructure> QuantLib::RendistatoCalculator::discountCurve_ [private]
Definition at line 143 of file btp.hpp.
Referenced by RendistatoCalculator().
Time QuantLib::RendistatoCalculator::duration_ [mutable, private]
Definition at line 147 of file btp.hpp.
Referenced by duration(), and performCalculations().
std::vector<Time> QuantLib::RendistatoCalculator::durations_ [mutable, private]
Definition at line 146 of file btp.hpp.
Referenced by durations(), and performCalculations().
Size QuantLib::RendistatoCalculator::equivalentSwapIndex_ [mutable, private]
Definition at line 148 of file btp.hpp.
Referenced by equivalentSwap(), equivalentSwapDuration(), equivalentSwapLength(), equivalentSwapRate(), equivalentSwapYield(), and performCalculations().
boost::shared_ptr<Euribor> QuantLib::RendistatoCalculator::euriborIndex_ [private]
Definition at line 142 of file btp.hpp.
Referenced by RendistatoCalculator().
Size QuantLib::RendistatoCalculator::nSwaps_ [private]
Definition at line 150 of file btp.hpp.
Referenced by performCalculations(), and RendistatoCalculator().
std::vector<Time> QuantLib::RendistatoCalculator::swapBondDurations_ [mutable, private]
Definition at line 153 of file btp.hpp.
Referenced by equivalentSwapDuration(), performCalculations(), and swapDurations().
std::vector<Rate> QuantLib::RendistatoCalculator::swapBondYields_ [mutable, private]
Definition at line 154 of file btp.hpp.
Referenced by equivalentSwapYield(), performCalculations(), and swapYields().
std::vector<Time> QuantLib::RendistatoCalculator::swapLenghts_ [private]
Definition at line 152 of file btp.hpp.
Referenced by equivalentSwapLength(), RendistatoCalculator(), and swapLengths().
std::vector<Rate> QuantLib::RendistatoCalculator::swapRates_ [mutable, private]
Definition at line 154 of file btp.hpp.
Referenced by equivalentSwapRate(), performCalculations(), and swapRates().
std::vector<boost::shared_ptr<VanillaSwap> > QuantLib::RendistatoCalculator::swaps_ [mutable, private]
Definition at line 151 of file btp.hpp.
Referenced by equivalentSwap(), performCalculations(), and RendistatoCalculator().
std::vector<Rate> QuantLib::RendistatoCalculator::yields_ [mutable, private]
Definition at line 145 of file btp.hpp.
Referenced by performCalculations(), and yields().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/bonds/btp.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/instruments/bonds/btp.cpp