QuantLib: QuantLib::CappedFlooredYoYInflationCoupon Class Reference
QuantLib::CappedFlooredYoYInflationCoupon Class Reference
Capped or floored inflation coupon.
#include <capflooredinflationcoupon.hpp>
Public Member Functions
CappedFlooredYoYInflationCoupon (const boost::shared_ptr< YoYInflationCoupon > &underlying, Rate cap=Null< Rate >(), Rate floor=Null< Rate >())
CappedFlooredYoYInflationCoupon (const Date &paymentDate, Real nominal, const Date &startDate, const Date &endDate, Natural fixingDays, const boost::shared_ptr< YoYInflationIndex > &index, const Period &observationLag, const DayCounter &dayCounter, Real gearing=1.0, Spread spread=0.0, const Rate cap=Null< Rate >(), const Rate floor=Null< Rate >(), const Date &refPeriodStart=Date(), const Date &refPeriodEnd=Date())
bool isCapped () const
bool isFloored () const
void setPricer (const boost::shared_ptr< YoYInflationCouponPricer > &)
augmented Coupon interface
Rate rate () const
swap(let) rate
Rate cap () const
cap
Rate floor () const
floor
Rate effectiveCap () const
effective cap of fixing
Rate effectiveFloor () const
effective floor of fixing
Observer interface
void update ()
Visitability
virtual void accept (AcyclicVisitor &v)
Protected Member Functions
virtual void setCommon (Rate cap, Rate floor)
Protected Attributes
boost::shared_ptr
< YoYInflationCoupon > underlying_
bool isFloored_
bool isCapped_
Rate cap_
Rate floor_
Detailed Description
Capped or floored inflation coupon.
Essentially a copy of the nominal version but taking a different index and a set of pricers (not just one).
The payoff \(P \) of a capped inflation-rate coupon with paysWithin = true is:
\[ P = N \times T \times \min(a L + b, C). \]
where \(N \) is the notional, \(T \) is the accrual time, \(L \) is the inflation rate, \(a \) is its gearing, \(b \) is the spread, and \(C \) and \(F \) the strikes.
The payoff of a floored inflation-rate coupon is:
\[ P = N \times T \times \max(a L + b, F). \]
The payoff of a collared inflation-rate coupon is:
\[ P = N \times T \times \min(\max(a L + b, F), C). \]
If paysWithin = false then the inverse is returned (this provides for instrument cap and caplet prices).
They can be decomposed in the following manner. Decomposition of a capped floating rate coupon when paysWithin = true:
\[ R = \min(a L + b, C) = (a L + b) + \min(C - b - \xi |a| L, 0) \]
where \(\xi = sgn(a) \). Then:
\[ R = (a L + b) + |a| \min(\frac{C - b}{|a|} - \xi L, 0) \]
Definition at line 66 of file capflooredinflationcoupon.hpp.
Constructor & Destructor Documentation
QuantLib::CappedFlooredYoYInflationCoupon::CappedFlooredYoYInflationCoupon (const boost::shared_ptr< YoYInflationCoupon > & underlying, Rate cap = Null<Rate>(), Rate floor = Null<Rate>())
Definition at line 57 of file capflooredinflationcoupon.cpp.
References QuantLib::Observer::registerWith(), and setCommon().
    : YoYInflationCoupon(underlying->date(),
                         underlying->nominal(),
                         underlying->accrualStartDate(),
                         underlying->accrualEndDate(),
                         underlying->fixingDays(),
                         underlying->yoyIndex(),
                         underlying->observationLag(),
                         underlying->dayCounter(),
                         underlying->gearing(),
                         underlying->spread(),
                         underlying->referencePeriodStart(),
                         underlying->referencePeriodEnd()),
      underlying_(underlying), isFloored_(false), isCapped_(false) {
        setCommon(cap, floor);
        registerWith(underlying);
    }
QuantLib::CappedFlooredYoYInflationCoupon::CappedFlooredYoYInflationCoupon (const Date & paymentDate, Real nominal, const Date & startDate, const Date & endDate, Natural fixingDays, const boost::shared_ptr< YoYInflationIndex > & index, const Period & observationLag, const DayCounter & dayCounter, Real gearing = 1.0, Spread spread = 0.0, const Rate cap = Null<Rate>(), const Rate floor = Null<Rate>(), const Date & refPeriodStart = Date(), const Date & refPeriodEnd = Date()) [inline]
Definition at line 75 of file capflooredinflationcoupon.hpp.
References cap(), floor(), and setCommon().
        : YoYInflationCoupon(paymentDate, nominal, startDate, endDate,
                             fixingDays, index, observationLag,  dayCounter,
                             gearing, spread, refPeriodStart, refPeriodEnd),
          isFloored_(false), isCapped_(false) {
            setCommon(cap, floor);
        }
Member Function Documentation
void QuantLib::CappedFlooredYoYInflationCoupon::accept (AcyclicVisitor & v) [virtual]
Reimplemented from QuantLib::YoYInflationCoupon.
Definition at line 152 of file capflooredinflationcoupon.cpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Visitor< T >::visit().
{
        typedef YoYInflationCoupon super;
        Visitor<CappedFlooredYoYInflationCoupon>* v1 =
            dynamic_cast<Visitor<CappedFlooredYoYInflationCoupon>*>(&v);
        if (v1 != 0)
            v1->visit(*this);
        else
            super::accept(v);
    }
Rate QuantLib::CappedFlooredYoYInflationCoupon::cap () const
cap
Definition at line 119 of file capflooredinflationcoupon.cpp.
References cap_, floor_, QuantLib::YoYInflationCoupon::gearing_, isCapped_, and isFloored_.
Referenced by CappedFlooredYoYInflationCoupon(), and setCommon().
{
        if ( (gearing_ > 0) && isCapped_)
            return cap_;
        if ( (gearing_ < 0) && isFloored_)
            return floor_;
        return Null<Rate>();
    }
Rate QuantLib::CappedFlooredYoYInflationCoupon::effectiveCap () const
effective cap of fixing
Definition at line 137 of file capflooredinflationcoupon.cpp.
References cap_, QuantLib::YoYInflationCoupon::gearing(), and QuantLib::YoYInflationCoupon::spread().
Referenced by rate().
{
        return  (cap_ - spread())/gearing();
    }
Rate QuantLib::CappedFlooredYoYInflationCoupon::effectiveFloor () const
effective floor of fixing
Definition at line 142 of file capflooredinflationcoupon.cpp.
References floor_, QuantLib::YoYInflationCoupon::gearing(), and QuantLib::YoYInflationCoupon::spread().
Referenced by rate().
{
        return  (floor_ - spread())/gearing();
    }
Rate QuantLib::CappedFlooredYoYInflationCoupon::floor () const
floor
Definition at line 128 of file capflooredinflationcoupon.cpp.
References cap_, floor_, QuantLib::YoYInflationCoupon::gearing_, isCapped_, and isFloored_.
Referenced by CappedFlooredYoYInflationCoupon(), and setCommon().
{
        if ( (gearing_ > 0) && isFloored_)
            return floor_;
        if ( (gearing_ < 0) && isCapped_)
            return cap_;
        return Null<Rate>();
    }
bool QuantLib::CappedFlooredYoYInflationCoupon::isCapped () const [inline]
Definition at line 120 of file capflooredinflationcoupon.hpp.
References isCapped_.
{ return isCapped_; }
bool QuantLib::CappedFlooredYoYInflationCoupon::isFloored () const [inline]
Definition at line 121 of file capflooredinflationcoupon.hpp.
References isFloored_.
{ return isFloored_; }
Rate QuantLib::CappedFlooredYoYInflationCoupon::rate () const [virtual]
swap(let) rate
Reimplemented from QuantLib::InflationCoupon.
Definition at line 87 of file capflooredinflationcoupon.cpp.
References effectiveCap(), effectiveFloor(), isCapped_, isFloored_, QuantLib::InflationCoupon::pricer(), QuantLib::InflationCoupon::pricer_, QL_REQUIRE, and underlying_.
{
        Rate swapletRate = underlying_ ? underlying_->rate() : YoYInflationCoupon::rate();
        if(isFloored_ || isCapped_) {
            if (underlying_) {
                QL_REQUIRE(underlying_->pricer(), "pricer not set");
            } else {
                QL_REQUIRE(pricer_, "pricer not set");
            }
        }
        Rate floorletRate = 0.;
        if(isFloored_) {
            floorletRate =
            underlying_ ?
            underlying_->pricer()->floorletRate(effectiveFloor()) :
            pricer()->floorletRate(effectiveFloor())
            ;
        }
        Rate capletRate = 0.;
        if(isCapped_) {
            capletRate =
            underlying_ ?
            underlying_->pricer()->capletRate(effectiveCap()) :
            pricer()->capletRate(effectiveCap())
            ;
        }
        return swapletRate + floorletRate - capletRate;
    }
void QuantLib::CappedFlooredYoYInflationCoupon::setCommon (Rate cap, Rate floor) [protected, virtual]
Definition at line 25 of file capflooredinflationcoupon.cpp.
References cap(), cap_, floor(), floor_, QuantLib::YoYInflationCoupon::gearing_, isCapped_, isFloored_, and QL_REQUIRE.
Referenced by CappedFlooredYoYInflationCoupon().
{
        isCapped_ = false;
        isFloored_ = false;
        if (gearing_ > 0) {
            if (cap != Null<Rate>()) {
                isCapped_ = true;
                cap_ = cap;
            }
            if (floor != Null<Rate>()) {
                floor_ = floor;
                isFloored_ = true;
            }
        } else {
            if (cap != Null<Rate>()){
                floor_ = cap;
                isFloored_ = true;
            }
            if (floor != Null<Rate>()){
                isCapped_ = true;
                cap_ = floor;
            }
        }
        if (isCapped_ && isFloored_) {
            QL_REQUIRE(cap >= floor, "cap level (" << cap <<
                       ") less than floor level (" << floor << ")");
        }
    }
void QuantLib::CappedFlooredYoYInflationCoupon::setPricer (const boost::shared_ptr< YoYInflationCouponPricer > & pricer)
Definition at line 79 of file capflooredinflationcoupon.cpp.
References underlying_.
{
        YoYInflationCoupon::setPricer(pricer);
        if (underlying_) underlying_->setPricer(pricer);
    }
void QuantLib::CappedFlooredYoYInflationCoupon::update () [virtual]
This method must be implemented in derived classes. An instance of Observer does not call this method directly: instead, it will be called by the observables the instance registered with when they need to notify any changes.
Reimplemented from QuantLib::InflationCoupon.
Definition at line 147 of file capflooredinflationcoupon.cpp.
References QuantLib::Observable::notifyObservers().
{
        notifyObservers();
    }
Member Data Documentation
Rate QuantLib::CappedFlooredYoYInflationCoupon::cap_ [protected]
Definition at line 132 of file capflooredinflationcoupon.hpp.
Referenced by cap(), effectiveCap(), floor(), and setCommon().
Rate QuantLib::CappedFlooredYoYInflationCoupon::floor_ [protected]
Definition at line 132 of file capflooredinflationcoupon.hpp.
Referenced by cap(), effectiveFloor(), floor(), and setCommon().
bool QuantLib::CappedFlooredYoYInflationCoupon::isCapped_ [protected]
Definition at line 131 of file capflooredinflationcoupon.hpp.
Referenced by cap(), floor(), isCapped(), rate(), and setCommon().
bool QuantLib::CappedFlooredYoYInflationCoupon::isFloored_ [protected]
Definition at line 131 of file capflooredinflationcoupon.hpp.
Referenced by cap(), floor(), isFloored(), rate(), and setCommon().
boost::shared_ptr<YoYInflationCoupon> QuantLib::CappedFlooredYoYInflationCoupon::underlying_ [protected]
Definition at line 130 of file capflooredinflationcoupon.hpp.
Referenced by rate(), and setPricer().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/capflooredinflationcoupon.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/capflooredinflationcoupon.cpp