QuantLib: QuantLib::JumpDiffusionEngine Class Reference
QuantLib::JumpDiffusionEngine Class Reference
Jump-diffusion engine for vanilla options.
#include <jumpdiffusionengine.hpp>
Public Member Functions
JumpDiffusionEngine (const boost::shared_ptr< Merton76Process > &, Real relativeAccuracy_=1e-4, Size maxIterations=100)
void calculate () const
Private Attributes
boost::shared_ptr
< Merton76Process > process_
Real relativeAccuracy_
Size maxIterations_
Detailed Description
Jump-diffusion engine for vanilla options.
Test:
the correctness of the returned value is tested by reproducing results available in literature.
the correctness of the returned greeks is tested by reproducing numerical derivatives.
Definition at line 42 of file jumpdiffusionengine.hpp.
Constructor & Destructor Documentation
QuantLib::JumpDiffusionEngine::JumpDiffusionEngine (const boost::shared_ptr< Merton76Process > & process, Real relativeAccuracy_ = 1e-4, Size maxIterations = 100)
Definition at line 31 of file jumpdiffusionengine.cpp.
References process_.
    : process_(process), relativeAccuracy_(relativeAccuracy),
      maxIterations_(maxIterations) {
        registerWith(process_);
    }
Member Function Documentation
void QuantLib::JumpDiffusionEngine::calculate () const
Definition at line 41 of file jumpdiffusionengine.cpp.
References QuantLib::AnalyticEuropeanEngine::calculate(), QuantLib::Option::arguments::exercise, maxIterations_, QuantLib::io::ordinal(), QuantLib::Option::arguments::payoff, process_, QL_ENSURE, QL_EPSILON, QL_REQUIRE, relativeAccuracy_, anonymous_namespace{quantlibbenchmark.cpp}::t, anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), QuantLib::Option::arguments::validate(), QuantLib::Instrument::results::value, and QuantLib::DayCounter::yearFraction().
{
        Real jumpSquareVol = process_->logJumpVolatility()->value()
            * process_->logJumpVolatility()->value();
        Real muPlusHalfSquareVol = process_->logMeanJump()->value()
            + 0.5*jumpSquareVol;
        // mean jump size
        Real k = std::exp(muPlusHalfSquareVol) - 1.0;
        Real lambda = (k+1.0) * process_->jumpIntensity()->value();
        boost::shared_ptr<StrikedTypePayoff> payoff =
            boost::dynamic_pointer_cast<StrikedTypePayoff>(arguments_.payoff);
        QL_REQUIRE(payoff, "non-striked payoff given");
        Real variance =
            process_->blackVolatility()->blackVariance(
                                              arguments_.exercise->lastDate(),
                                              payoff->strike());
        DayCounter voldc = process_->blackVolatility()->dayCounter();
        Calendar volcal = process_->blackVolatility()->calendar();
        Date volRefDate = process_->blackVolatility()->referenceDate();
        Time t = voldc.yearFraction(volRefDate,
                                    arguments_.exercise->lastDate());
        Rate riskFreeRate = -std::log(process_->riskFreeRate()->discount(
                                          arguments_.exercise->lastDate()))/t;
        Date rateRefDate = process_->riskFreeRate()->referenceDate();
        PoissonDistribution p(lambda*t);
        Handle<Quote> stateVariable = process_->stateVariable();
        Handle<YieldTermStructure> dividendTS = process_->dividendYield();
        RelinkableHandle<YieldTermStructure> riskFreeTS(
                                                   *process_->riskFreeRate());
        RelinkableHandle<BlackVolTermStructure> volTS(
                                                *process_->blackVolatility());
        boost::shared_ptr<GeneralizedBlackScholesProcess> bsProcess(
                 new GeneralizedBlackScholesProcess(stateVariable, dividendTS,
                                                    riskFreeTS, volTS));
        AnalyticEuropeanEngine baseEngine(bsProcess);
        VanillaOption::arguments* baseArguments =
            dynamic_cast<VanillaOption::arguments*>(baseEngine.getArguments());
        baseArguments->payoff   = arguments_.payoff;
        baseArguments->exercise = arguments_.exercise;
        baseArguments->validate();
        const VanillaOption::results* baseResults =
            dynamic_cast<const VanillaOption::results*>(
                                                     baseEngine.getResults());
        results_.value       = 0.0;
        results_.delta       = 0.0;
        results_.gamma       = 0.0;
        results_.theta       = 0.0;
        results_.vega        = 0.0;
        results_.rho         = 0.0;
        results_.dividendRho = 0.0;
        Real r, v, weight, lastContribution = 1.0;
        Size i;
        Real theta_correction;
        // Haug arbitrary criterium is:
        //for (i=0; i<11; i++) {
        for (i=0;  (lastContribution>relativeAccuracy_ && i<maxIterations_)
                 || i < Size(lambda*t); i++) {
            // constant vol/rate assumption. It should be relaxed
            v = std::sqrt((variance + i*jumpSquareVol)/t);
            r = riskFreeRate - process_->jumpIntensity()->value()*k
                + i*muPlusHalfSquareVol/t;
            riskFreeTS.linkTo(boost::shared_ptr<YieldTermStructure>(new
                FlatForward(rateRefDate, r, voldc)));
            volTS.linkTo(boost::shared_ptr<BlackVolTermStructure>(new
                BlackConstantVol(rateRefDate, volcal, v, voldc)));
            baseArguments->validate();
            baseEngine.calculate();
            weight = p(Size(i));
            results_.value       += weight * baseResults->value;
            results_.delta       += weight * baseResults->delta;
            results_.gamma       += weight * baseResults->gamma;
            results_.vega        += weight * (std::sqrt(variance/t)/v)*
                                                           baseResults->vega;
            // theta modified
            theta_correction = baseResults->vega*((i*jumpSquareVol)/
                                                  (2.0*v*t*t)) +
                baseResults->rho*i*muPlusHalfSquareVol/(t*t);
            results_.theta += weight *(baseResults->theta + theta_correction +
                                  lambda*baseResults->value);
            if(i != 0){
                 results_.theta -= (p(Size(i-1))*lambda* baseResults->value);
            }
            //end theta calculation
            results_.rho         += weight * baseResults->rho;
            results_.dividendRho += weight * baseResults->dividendRho;
            lastContribution = std::fabs(baseResults->value /
                (std::fabs(results_.value)>QL_EPSILON ? results_.value : 1.0));
            lastContribution = std::max<Real>(lastContribution,
                std::fabs(baseResults->delta /
               (std::fabs(results_.delta)>QL_EPSILON ? results_.delta : 1.0)));
            lastContribution = std::max<Real>(lastContribution,
                std::fabs(baseResults->gamma /
               (std::fabs(results_.gamma)>QL_EPSILON ? results_.gamma : 1.0)));
            lastContribution = std::max<Real>(lastContribution,
                std::fabs(baseResults->theta /
               (std::fabs(results_.theta)>QL_EPSILON ? results_.theta : 1.0)));
            lastContribution = std::max<Real>(lastContribution,
                std::fabs(baseResults->vega /
               (std::fabs(results_.vega)>QL_EPSILON ? results_.vega : 1.0)));
            lastContribution = std::max<Real>(lastContribution,
                std::fabs(baseResults->rho /
               (std::fabs(results_.rho)>QL_EPSILON ? results_.rho : 1.0)));
            lastContribution = std::max<Real>(lastContribution,
                std::fabs(baseResults->dividendRho /
               (std::fabs(results_.dividendRho)>QL_EPSILON ?
                                          results_.dividendRho : 1.0)));
            lastContribution *= weight;
        }
        QL_ENSURE(i<maxIterations_,
                  i << " iterations have been not enough to reach "
                  << "the required " << relativeAccuracy_
                  << " accuracy. The " << io::ordinal(i)
                  << " addendum was " << lastContribution
                  << " while the running sum was " << results_.value);
    }
Member Data Documentation
Size QuantLib::JumpDiffusionEngine::maxIterations_ [private]
Definition at line 51 of file jumpdiffusionengine.hpp.
Referenced by calculate().
boost::shared_ptr<Merton76Process> QuantLib::JumpDiffusionEngine::process_ [private]
Definition at line 49 of file jumpdiffusionengine.hpp.
Referenced by calculate(), and JumpDiffusionEngine().
Real QuantLib::JumpDiffusionEngine::relativeAccuracy_ [private]
Definition at line 50 of file jumpdiffusionengine.hpp.
Referenced by calculate().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/vanilla/jumpdiffusionengine.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/vanilla/jumpdiffusionengine.cpp