QuantLib: QuantLib::TreeCallableFixedRateBondEngine Class Reference
QuantLib::TreeCallableFixedRateBondEngine Class Reference
Numerical lattice engine for callable fixed rate bonds.
#include <treecallablebondengine.hpp>
Public Member Functions
void calculate () const
Constructors
Note:
the term structure is only needed when the short-rate model cannot provide one itself.
TreeCallableFixedRateBondEngine (const boost::shared_ptr< ShortRateModel > &, const Size timeSteps, const Handle< YieldTermStructure > &termStructure=Handle< YieldTermStructure >())
TreeCallableFixedRateBondEngine (const boost::shared_ptr< ShortRateModel > &, const TimeGrid &timeGrid, const Handle< YieldTermStructure > &termStructure=Handle< YieldTermStructure >())
Private Attributes
Handle< YieldTermStructure > termStructure_
Detailed Description
Numerical lattice engine for callable fixed rate bonds.
Definition at line 34 of file treecallablebondengine.hpp.
Constructor & Destructor Documentation
QuantLib::TreeCallableFixedRateBondEngine::TreeCallableFixedRateBondEngine (const boost::shared_ptr< ShortRateModel > & model, const Size timeSteps, const Handle< YieldTermStructure > & termStructure = Handle<YieldTermStructure>())
Definition at line 25 of file treecallablebondengine.cpp.
References QuantLib::Observer::registerWith(), and termStructure_.
    : LatticeShortRateModelEngine<CallableBond::arguments,
                                  CallableBond::results>(model, timeSteps),
      termStructure_(termStructure) {
        registerWith(termStructure_);
    }
QuantLib::TreeCallableFixedRateBondEngine::TreeCallableFixedRateBondEngine (const boost::shared_ptr< ShortRateModel > & model, const TimeGrid & timeGrid, const Handle< YieldTermStructure > & termStructure = Handle<YieldTermStructure>())
Definition at line 35 of file treecallablebondengine.cpp.
References QuantLib::Observer::registerWith(), and termStructure_.
    : LatticeShortRateModelEngine<CallableBond::arguments,
                                  CallableBond::results>(model, timeGrid),
      termStructure_(termStructure) {
        registerWith(termStructure_);
    }
Member Function Documentation
void QuantLib::TreeCallableFixedRateBondEngine::calculate () const [virtual]
Implements QuantLib::PricingEngine.
Definition at line 45 of file treecallablebondengine.cpp.
References QuantLib::GenericEngine< CallableBond::arguments, CallableBond::results >::arguments_, anonymous_namespace{marketmodel.cpp}::dayCounter, QuantLib::Handle< T >::empty(), QuantLib::DiscretizedAsset::initialize(), QuantLib::LatticeShortRateModelEngine< CallableBond::arguments, CallableBond::results >::lattice_, QuantLib::DiscretizedCallableFixedRateBond::mandatoryTimes(), QuantLib::GenericModelEngine< ShortRateModel, CallableBond::arguments, CallableBond::results >::model_, QuantLib::DiscretizedAsset::presentValue(), QL_REQUIRE, QuantLib::CallableBond::arguments::redemptionDate, QuantLib::GenericEngine< CallableBond::arguments, CallableBond::results >::results_, QuantLib::DiscretizedAsset::rollback(), QuantLib::Bond::results::settlementValue, QuantLib::TermStructureConsistentModel::termStructure(), termStructure_, QuantLib::LatticeShortRateModelEngine< CallableBond::arguments, CallableBond::results >::timeSteps_, QuantLib::Instrument::results::value, and QuantLib::DayCounter::yearFraction().
{
        QL_REQUIRE(!model_.empty(), "no model specified");
        Date referenceDate;
        DayCounter dayCounter;
        boost::shared_ptr<TermStructureConsistentModel> tsmodel =
            boost::dynamic_pointer_cast<TermStructureConsistentModel>(*model_);
        if (tsmodel) {
            referenceDate = tsmodel->termStructure()->referenceDate();
            dayCounter = tsmodel->termStructure()->dayCounter();
        } else {
            referenceDate = termStructure_->referenceDate();
            dayCounter = termStructure_->dayCounter();
        }
        DiscretizedCallableFixedRateBond callableBond(arguments_,
                                                      referenceDate,
                                                      dayCounter);
        boost::shared_ptr<Lattice> lattice;
        if (lattice_) {
            lattice = lattice_;
        } else {
            std::vector<Time> times = callableBond.mandatoryTimes();
            TimeGrid timeGrid(times.begin(), times.end(), timeSteps_);
            lattice = model_->tree(timeGrid);
        }
        Time redemptionTime =
            dayCounter.yearFraction(referenceDate,
                                    arguments_.redemptionDate);
        callableBond.initialize(lattice, redemptionTime);
        callableBond.rollback(0.0);
        results_.value = results_.settlementValue = callableBond.presentValue();
    }
Member Data Documentation
Handle<YieldTermStructure> QuantLib::TreeCallableFixedRateBondEngine::termStructure_ [private]
Definition at line 56 of file treecallablebondengine.hpp.
Referenced by calculate(), and TreeCallableFixedRateBondEngine().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/callablebonds/treecallablebondengine.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/callablebonds/treecallablebondengine.cpp