QuantLib: QuantLib::MCLongstaffSchwartzEngine< GenericEngine, MC, RNG, S > Class Template Reference
QuantLib::MCLongstaffSchwartzEngine< GenericEngine, MC, RNG, S > Class Template Reference
Longstaff-Schwarz Monte Carlo engine for early exercise options.
#include <mclongstaffschwartzengine.hpp>
Public Types
typedef MC< RNG >::path_type path_type
typedef McSimulation< MC, RNG,
S >::stats_type stats_type
typedef McSimulation< MC, RNG,
S >::path_pricer_type path_pricer_type
typedef McSimulation< MC, RNG,
S >::path_generator_type path_generator_type
Public Member Functions
MCLongstaffSchwartzEngine (const boost::shared_ptr< StochasticProcess > &process, Size timeSteps, Size timeStepsPerYear, bool brownianBridge, bool antitheticVariate, bool controlVariate, Size requiredSamples, Real requiredTolerance, Size maxSamples, BigNatural seed, Size nCalibrationSamples=Null< Size >())
void calculate () const
Protected Member Functions
virtual boost::shared_ptr
< LongstaffSchwartzPathPricer
< path_type > > lsmPathPricer () const =0
TimeGrid timeGrid () const
boost::shared_ptr
< path_pricer_type > pathPricer () const
boost::shared_ptr
< path_generator_type > pathGenerator () const
Protected Attributes
boost::shared_ptr
< StochasticProcess > process_
const Size timeSteps_
const Size timeStepsPerYear_
const bool brownianBridge_
const Size requiredSamples_
const Real requiredTolerance_
const Size maxSamples_
const Size seed_
const Size nCalibrationSamples_
boost::shared_ptr
< LongstaffSchwartzPathPricer
< path_type > > pathPricer_
Detailed Description
template<class GenericEngine, template< class > class MC, class RNG, class S = Statistics>
class QuantLib::MCLongstaffSchwartzEngine< GenericEngine, MC, RNG, S >
Longstaff-Schwarz Monte Carlo engine for early exercise options.
References:
Francis Longstaff, Eduardo Schwartz, 2001. Valuing American Options by Simulation: A Simple Least-Squares Approach, The Review of Financial Studies, Volume 14, No. 1, 113-147
Test:
the correctness of the returned value is tested by reproducing results available in web/literature
Definition at line 45 of file mclongstaffschwartzengine.hpp.
Member Typedef Documentation
template<class GenericEngine, template< class > class MC, class RNG, class S = Statistics> typedef McSimulation<MC,RNG,S>::path_generator_type QuantLib::MCLongstaffSchwartzEngine< GenericEngine, MC, RNG, S >::path_generator_type
Reimplemented from QuantLib::McSimulation< MC, RNG, S >.
Definition at line 54 of file mclongstaffschwartzengine.hpp.
template<class GenericEngine, template< class > class MC, class RNG, class S = Statistics> typedef McSimulation<MC,RNG,S>::path_pricer_type QuantLib::MCLongstaffSchwartzEngine< GenericEngine, MC, RNG, S >::path_pricer_type
Reimplemented from QuantLib::McSimulation< MC, RNG, S >.
Definition at line 52 of file mclongstaffschwartzengine.hpp.
template<class GenericEngine, template< class > class MC, class RNG, class S = Statistics> typedef MC<RNG>::path_type QuantLib::MCLongstaffSchwartzEngine< GenericEngine, MC, RNG, S >::path_type
Definition at line 48 of file mclongstaffschwartzengine.hpp.
template<class GenericEngine, template< class > class MC, class RNG, class S = Statistics> typedef McSimulation<MC,RNG,S>::stats_type QuantLib::MCLongstaffSchwartzEngine< GenericEngine, MC, RNG, S >::stats_type
Reimplemented from QuantLib::McSimulation< MC, RNG, S >.
Definition at line 50 of file mclongstaffschwartzengine.hpp.
Constructor & Destructor Documentation
template<class GenericEngine , template< class > class MC, class RNG , class S > QuantLib::MCLongstaffSchwartzEngine< GenericEngine, MC, RNG, S >::MCLongstaffSchwartzEngine (const boost::shared_ptr< StochasticProcess > & process, Size timeSteps, Size timeStepsPerYear, bool brownianBridge, bool antitheticVariate, bool controlVariate, Size requiredSamples, Real requiredTolerance, Size maxSamples, BigNatural seed, Size nCalibrationSamples = Null<Size>()) [inline]
Definition at line 96 of file mclongstaffschwartzengine.hpp.
References QuantLib::MCLongstaffSchwartzEngine< GenericEngine, MC, RNG, S >::process_, QL_REQUIRE, and QuantLib::Observer::registerWith().
    : McSimulation<MC,RNG,S> (antitheticVariate, controlVariate),
      process_            (process),
      timeSteps_          (timeSteps),
      timeStepsPerYear_   (timeStepsPerYear),
      brownianBridge_     (brownianBridge),
      requiredSamples_    (requiredSamples),
      requiredTolerance_  (requiredTolerance),
      maxSamples_         (maxSamples),
      seed_               (seed),
      nCalibrationSamples_( (nCalibrationSamples == Null<Size>())
                            ? 2048 : nCalibrationSamples) {
        QL_REQUIRE(timeSteps != Null<Size>() ||
                   timeStepsPerYear != Null<Size>(),
                   "no time steps provided");
        QL_REQUIRE(timeSteps == Null<Size>() ||
                   timeStepsPerYear == Null<Size>(),
                   "both time steps and time steps per year were provided");
        QL_REQUIRE(timeSteps != 0,
                   "timeSteps must be positive, " << timeSteps <<
                   " not allowed");
        QL_REQUIRE(timeStepsPerYear != 0,
                   "timeStepsPerYear must be positive, " << timeStepsPerYear <<
                   " not allowed");
        this->registerWith(process_);
    }
Member Function Documentation
template<class GenericEngine , template< class > class MC, class RNG , class S > void QuantLib::MCLongstaffSchwartzEngine< GenericEngine, MC, RNG, S >::calculate () const [inline, virtual]
Implements QuantLib::PricingEngine.
Reimplemented in QuantLib::MCAmericanEngine< RNG, S >.
Definition at line 148 of file mclongstaffschwartzengine.hpp.
References QuantLib::McSimulation< MC, RNG, S >::calculate().
{
        pathPricer_ = this->lsmPathPricer();
        this->mcModel_ = boost::shared_ptr<MonteCarloModel<MC,RNG,S> >(
                          new MonteCarloModel<MC,RNG,S>
                              (pathGenerator(), pathPricer_,
                               stats_type(), this->antitheticVariate_));
        this->mcModel_->addSamples(nCalibrationSamples_);
        this->pathPricer_->calibrate();
        McSimulation<MC,RNG,S>::calculate(requiredTolerance_,
                                          requiredSamples_,
                                          maxSamples_);
        this->results_.value = this->mcModel_->sampleAccumulator().mean();
        if (RNG::allowsErrorEstimate) {
            this->results_.errorEstimate =
                this->mcModel_->sampleAccumulator().errorEstimate();
        }
    }
template<class GenericEngine, template< class > class MC, class RNG, class S = Statistics> virtual boost::shared_ptr<LongstaffSchwartzPathPricer<path_type> > QuantLib::MCLongstaffSchwartzEngine< GenericEngine, MC, RNG, S >::lsmPathPricer () const [protected, pure virtual]
Implemented in anonymous_namespace{mclongstaffschwartzengine.cpp}::MCAmericanMaxEngine< RNG >, QuantLib::MCAmericanEngine< RNG, S >, and QuantLib::MCAmericanBasketEngine< RNG >.
template<class GenericEngine , template< class > class MC, class RNG , class S > boost::shared_ptr< typename MCLongstaffSchwartzEngine< GenericEngine, MC, RNG, S >::path_generator_type > QuantLib::MCLongstaffSchwartzEngine< GenericEngine, MC, RNG, S >::pathGenerator () const [inline, protected, virtual]
Implements QuantLib::McSimulation< MC, RNG, S >.
Definition at line 190 of file mclongstaffschwartzengine.hpp.
References anonymous_namespace{marketmodel.cpp}::seed_, and QuantLib::TimeGrid::size().
{
        Size dimensions = process_->factors();
        TimeGrid grid = this->timeGrid();
        typename RNG::rsg_type generator =
            RNG::make_sequence_generator(dimensions*(grid.size()-1),seed_);
        return boost::shared_ptr<path_generator_type>(
                   new path_generator_type(process_,
                                           grid, generator, brownianBridge_));
    }
template<class GenericEngine , template< class > class MC, class RNG , class S > boost::shared_ptr< typename MCLongstaffSchwartzEngine< GenericEngine, MC, RNG, S >::path_pricer_type > QuantLib::MCLongstaffSchwartzEngine< GenericEngine, MC, RNG, S >::pathPricer () const [inline, protected, virtual]
Implements QuantLib::McSimulation< MC, RNG, S >.
Definition at line 139 of file mclongstaffschwartzengine.hpp.
References QL_REQUIRE.
{
        QL_REQUIRE(pathPricer_, "path pricer unknown");
        return pathPricer_;
    }
template<class GenericEngine , template< class > class MC, class RNG , class S > TimeGrid QuantLib::MCLongstaffSchwartzEngine< GenericEngine, MC, RNG, S >::timeGrid () const [inline, protected, virtual]
Implements QuantLib::McSimulation< MC, RNG, S >.
Definition at line 171 of file mclongstaffschwartzengine.hpp.
References QL_FAIL, and anonymous_namespace{quantlibbenchmark.cpp}::t.
              {
        Date lastExerciseDate = this->arguments_.exercise->lastDate();
        Time t = process_->time(lastExerciseDate);
        if (this->timeSteps_ != Null<Size>()) {
            return TimeGrid(t, this->timeSteps_);
        } else if (this->timeStepsPerYear_ != Null<Size>()) {
            Size steps = static_cast<Size>(this->timeStepsPerYear_*t);
            return TimeGrid(t, std::max<Size>(steps, 1));
        } else {
            QL_FAIL("time steps not specified");
        }
    }
Member Data Documentation
template<class GenericEngine, template< class > class MC, class RNG, class S = Statistics> const bool QuantLib::MCLongstaffSchwartzEngine< GenericEngine, MC, RNG, S >::brownianBridge_ [protected]
Definition at line 82 of file mclongstaffschwartzengine.hpp.
template<class GenericEngine, template< class > class MC, class RNG, class S = Statistics> const Size QuantLib::MCLongstaffSchwartzEngine< GenericEngine, MC, RNG, S >::maxSamples_ [protected]
Definition at line 85 of file mclongstaffschwartzengine.hpp.
template<class GenericEngine, template< class > class MC, class RNG, class S = Statistics> const Size QuantLib::MCLongstaffSchwartzEngine< GenericEngine, MC, RNG, S >::nCalibrationSamples_ [protected]
Definition at line 87 of file mclongstaffschwartzengine.hpp.
template<class GenericEngine, template< class > class MC, class RNG, class S = Statistics> boost::shared_ptr<LongstaffSchwartzPathPricer<path_type> > QuantLib::MCLongstaffSchwartzEngine< GenericEngine, MC, RNG, S >::pathPricer_ [mutable, protected]
Definition at line 90 of file mclongstaffschwartzengine.hpp.
template<class GenericEngine, template< class > class MC, class RNG, class S = Statistics> boost::shared_ptr<StochasticProcess> QuantLib::MCLongstaffSchwartzEngine< GenericEngine, MC, RNG, S >::process_ [protected]
Definition at line 79 of file mclongstaffschwartzengine.hpp.
Referenced by QuantLib::MCLongstaffSchwartzEngine< GenericEngine, MC, RNG, S >::MCLongstaffSchwartzEngine().
template<class GenericEngine, template< class > class MC, class RNG, class S = Statistics> const Size QuantLib::MCLongstaffSchwartzEngine< GenericEngine, MC, RNG, S >::requiredSamples_ [protected]
Definition at line 83 of file mclongstaffschwartzengine.hpp.
template<class GenericEngine, template< class > class MC, class RNG, class S = Statistics> const Real QuantLib::MCLongstaffSchwartzEngine< GenericEngine, MC, RNG, S >::requiredTolerance_ [protected]
Definition at line 84 of file mclongstaffschwartzengine.hpp.
template<class GenericEngine, template< class > class MC, class RNG, class S = Statistics> const Size QuantLib::MCLongstaffSchwartzEngine< GenericEngine, MC, RNG, S >::seed_ [protected]
Definition at line 86 of file mclongstaffschwartzengine.hpp.
template<class GenericEngine, template< class > class MC, class RNG, class S = Statistics> const Size QuantLib::MCLongstaffSchwartzEngine< GenericEngine, MC, RNG, S >::timeSteps_ [protected]
Definition at line 80 of file mclongstaffschwartzengine.hpp.
template<class GenericEngine, template< class > class MC, class RNG, class S = Statistics> const Size QuantLib::MCLongstaffSchwartzEngine< GenericEngine, MC, RNG, S >::timeStepsPerYear_ [protected]
Definition at line 81 of file mclongstaffschwartzengine.hpp.
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/mclongstaffschwartzengine.hpp