QuantLib: QuantLib::FDMultiPeriodEngine< Scheme > Class Template Reference
QuantLib::FDMultiPeriodEngine< Scheme > Class Template Reference
#include <fdmultiperiodengine.hpp>
Protected Types
typedef FiniteDifferenceModel
< Scheme< TridiagonalOperator > > model_type
Protected Member Functions
FDMultiPeriodEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > &process, Size timeSteps=100, Size gridPoints=100, bool timeDependent=false)
virtual void setupArguments (const PricingEngine::arguments *args, const std::vector< boost::shared_ptr< Event > > &schedule) const
virtual void setupArguments (const PricingEngine::arguments *a) const
virtual void calculate (PricingEngine::results *) const
virtual void executeIntermediateStep (Size step) const =0
virtual void initializeStepCondition () const
virtual void initializeModel () const
Time getDividendTime (Size i) const
Protected Attributes
std::vector< boost::shared_ptr
< Event > > events_
std::vector< Time > stoppingTimes_
Size timeStepPerPeriod_
SampledCurve prices_
boost::shared_ptr
< StandardStepCondition > stepCondition_
boost::shared_ptr< model_type > model_
Detailed Description
template<template< class > class Scheme = CrankNicolson>
class QuantLib::FDMultiPeriodEngine< Scheme >
Definition at line 37 of file fdmultiperiodengine.hpp.
Member Typedef Documentation
template<template< class > class Scheme = CrankNicolson> typedef FiniteDifferenceModel<Scheme<TridiagonalOperator> > QuantLib::FDMultiPeriodEngine< Scheme >::model_type [protected]
Definition at line 39 of file fdmultiperiodengine.hpp.
Constructor & Destructor Documentation
template<template< class > class Scheme> QuantLib::FDMultiPeriodEngine< Scheme >::FDMultiPeriodEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > & process, Size timeSteps = 100, Size gridPoints = 100, bool timeDependent = false) [protected]
Definition at line 91 of file fdmultiperiodengine.hpp.
    : FDVanillaEngine(process, timeSteps, gridPoints, timeDependent),
      timeStepPerPeriod_(timeSteps) {}
Member Function Documentation
template<template< class > class Scheme> void QuantLib::FDMultiPeriodEngine< Scheme >::calculate (PricingEngine::results * r) const [protected, virtual]
Definition at line 98 of file fdmultiperiodengine.hpp.
References QuantLib::Instrument::results::additionalResults, QuantLib::Greeks::delta, QuantLib::anonymous_namespace{yieldtermstructure.cpp}::dt, anonymous_namespace{marketmodel.cpp}::endDate, QuantLib::Greeks::gamma, QL_REQUIRE, and QuantLib::Instrument::results::value.
{
        OneAssetOption::results *results =
            dynamic_cast<OneAssetOption::results *>(r);
        QL_REQUIRE(results, "incorrect argument type");
        Time beginDate, endDate;
        Size dateNumber = stoppingTimes_.size();
        bool lastDateIsResTime = false;
        Integer firstIndex = -1;
        Integer lastIndex = dateNumber - 1;
        bool firstDateIsZero = false;
        Time firstNonZeroDate = getResidualTime();
        Real dateTolerance = 1e-6;
        if (dateNumber > 0) {
            QL_REQUIRE(getDividendTime(0) >= 0,
                       "first date (" << getDividendTime(0)
                       << ") cannot be negative");
            if(getDividendTime(0) < getResidualTime() * dateTolerance ){
                firstDateIsZero = true;
                firstIndex = 0;
                if(dateNumber >= 2)
                    firstNonZeroDate = getDividendTime(1);
            }
            if (std::fabs(getDividendTime(lastIndex) - getResidualTime())
                < dateTolerance) {
                lastDateIsResTime = true;
                lastIndex = Integer(dateNumber) - 2;
            }
            if (!firstDateIsZero)
                firstNonZeroDate = getDividendTime(0);
            if (dateNumber >= 2) {
                for (Size j = 1; j < dateNumber; j++)
                    QL_REQUIRE(getDividendTime(j-1) < getDividendTime(j),
                               "dates must be in increasing order: "
                               << getDividendTime(j-1)
                               << " is not strictly smaller than "
                               << getDividendTime(j));
            }
        }
        Time dt = getResidualTime()/(timeStepPerPeriod_*(dateNumber+1));
        // Ensure that dt is always smaller than the first non-zero date
        if (firstNonZeroDate <= dt)
            dt = firstNonZeroDate/2.0;
        setGridLimits();
        initializeInitialCondition();
        initializeOperator();
        initializeBoundaryConditions();
        initializeModel();
        initializeStepCondition();
        prices_ = intrinsicValues_;
        if(lastDateIsResTime)
            executeIntermediateStep(dateNumber - 1);
        Integer j = lastIndex;
        do {
            if (j == Integer(dateNumber) - 1)
                beginDate = getResidualTime();
            else
                beginDate = getDividendTime(j+1);
            if (j >= 0)
                endDate = getDividendTime(j);
            else
                endDate = dt;
            model_->rollback(prices_.values(),
                             beginDate, endDate,
                             timeStepPerPeriod_, *stepCondition_);
            if (j >= 0)
                executeIntermediateStep(j);
        } while (--j >= firstIndex);
        model_->rollback(prices_.values(), dt, 0, 1, *stepCondition_);
        if(firstDateIsZero)
            executeIntermediateStep(0);
        results->value = prices_.valueAtCenter();
        results->delta = prices_.firstDerivativeAtCenter();
        results->gamma = prices_.secondDerivativeAtCenter();
        results->additionalResults["priceCurve"] = prices_;
    }
template<template< class > class Scheme = CrankNicolson> virtual void QuantLib::FDMultiPeriodEngine< Scheme >::executeIntermediateStep (Size step) const [protected, pure virtual]
Implemented in QuantLib::FDDividendEngineShiftScale< Scheme >, QuantLib::FDDividendEngineMerton73< Scheme >, QuantLib::FDBermudanEngine< Scheme >, and QuantLib::FDDividendEngineBase< Scheme >.
template<template< class > class Scheme = CrankNicolson> Time QuantLib::FDMultiPeriodEngine< Scheme >::getDividendTime (Size i) const [inline, protected]
Definition at line 82 of file fdmultiperiodengine.hpp.
References QuantLib::FDMultiPeriodEngine< Scheme >::stoppingTimes_.
{
            return stoppingTimes_[i];
        }
template<template< class > class Scheme> void QuantLib::FDMultiPeriodEngine< Scheme >::initializeModel () const [protected, virtual]
Definition at line 197 of file fdmultiperiodengine.hpp.
{
        model_ = boost::shared_ptr<model_type>(
                              new model_type(finiteDifferenceOperator_,BCs_));
    }
template<template< class > class Scheme> void QuantLib::FDMultiPeriodEngine< Scheme >::initializeStepCondition () const [protected, virtual]
Reimplemented in QuantLib::FDShoutCondition< FDDividendEngine< Scheme > >, QuantLib::FDShoutCondition< FDDividendEngineShiftScale< Scheme > >, QuantLib::FDShoutCondition< FDDividendEngineMerton73< Scheme > >, QuantLib::FDBermudanEngine< Scheme >, QuantLib::FDAmericanCondition< FDDividendEngine< Scheme > >, QuantLib::FDAmericanCondition< FDDividendEngineShiftScale< Scheme > >, and QuantLib::FDAmericanCondition< FDDividendEngineMerton73< Scheme > >.
Definition at line 191 of file fdmultiperiodengine.hpp.
{
        stepCondition_ = boost::shared_ptr<StandardStepCondition>(
                                                  new NullCondition<Array>());
    }
template<template< class > class Scheme = CrankNicolson> virtual void QuantLib::FDMultiPeriodEngine< Scheme >::setupArguments (const PricingEngine::arguments * args, const std::vector< boost::shared_ptr< Event > > & schedule) const [inline, protected, virtual]
Definition at line 50 of file fdmultiperiodengine.hpp.
References QuantLib::FDMultiPeriodEngine< Scheme >::events_, QuantLib::FDVanillaEngine::process_, and QuantLib::FDMultiPeriodEngine< Scheme >::stoppingTimes_.
Referenced by QuantLib::FDBermudanEngine< Scheme >::calculate(), QuantLib::FDDividendEngineBase< Scheme >::setupArguments(), and QuantLib::FDMultiPeriodEngine< Scheme >::setupArguments().
{
            FDVanillaEngine::setupArguments(args);
            events_ = schedule;
            stoppingTimes_.clear();
            Size n = schedule.size();
            stoppingTimes_.reserve(n);
            for (Size i=0; i<n; ++i)
                stoppingTimes_.push_back(process_->time(events_[i]->date()));
        }
template<template< class > class Scheme = CrankNicolson> virtual void QuantLib::FDMultiPeriodEngine< Scheme >::setupArguments (const PricingEngine::arguments * a) const [inline, protected, virtual]
Reimplemented from QuantLib::FDVanillaEngine.
Reimplemented in QuantLib::FDDividendEngineBase< Scheme >.
Definition at line 62 of file fdmultiperiodengine.hpp.
References anonymous_namespace{marketmodel.cpp}::a, QuantLib::FDMultiPeriodEngine< Scheme >::events_, QuantLib::Option::arguments::exercise, QuantLib::FDVanillaEngine::process_, QL_REQUIRE, QuantLib::FDMultiPeriodEngine< Scheme >::setupArguments(), and QuantLib::FDMultiPeriodEngine< Scheme >::stoppingTimes_.
{
            FDVanillaEngine::setupArguments(a);
            const OneAssetOption::arguments *args =
                dynamic_cast<const OneAssetOption::arguments*>(a);
            QL_REQUIRE(args, "incorrect argument type");
            events_.clear();
            Size n = args->exercise->dates().size();
            stoppingTimes_.resize(n);
            for (Size i=0; i<n; ++i)
                stoppingTimes_[i] =
                      process_->time(args->exercise->date(i));
        }
Member Data Documentation
template<template< class > class Scheme = CrankNicolson> std::vector<boost::shared_ptr<Event> > QuantLib::FDMultiPeriodEngine< Scheme >::events_ [mutable, protected]
Definition at line 45 of file fdmultiperiodengine.hpp.
Referenced by QuantLib::FDDividendEngineBase< Scheme >::getDiscountedDividend(), QuantLib::FDDividendEngineBase< Scheme >::getDividendAmount(), and QuantLib::FDMultiPeriodEngine< Scheme >::setupArguments().
template<template< class > class Scheme = CrankNicolson> boost::shared_ptr<model_type> QuantLib::FDMultiPeriodEngine< Scheme >::model_ [mutable, protected]
Definition at line 78 of file fdmultiperiodengine.hpp.
template<template< class > class Scheme = CrankNicolson> SampledCurve QuantLib::FDMultiPeriodEngine< Scheme >::prices_ [mutable, protected]
Definition at line 48 of file fdmultiperiodengine.hpp.
Referenced by QuantLib::FDBermudanEngine< Scheme >::executeIntermediateStep().
template<template< class > class Scheme = CrankNicolson> boost::shared_ptr<StandardStepCondition > QuantLib::FDMultiPeriodEngine< Scheme >::stepCondition_ [mutable, protected]
Definition at line 77 of file fdmultiperiodengine.hpp.
Referenced by QuantLib::FDBermudanEngine< Scheme >::initializeStepCondition().
template<template< class > class Scheme = CrankNicolson> std::vector<Time> QuantLib::FDMultiPeriodEngine< Scheme >::stoppingTimes_ [mutable, protected]
Definition at line 46 of file fdmultiperiodengine.hpp.
Referenced by QuantLib::FDMultiPeriodEngine< Scheme >::getDividendTime(), and QuantLib::FDMultiPeriodEngine< Scheme >::setupArguments().
template<template< class > class Scheme = CrankNicolson> Size QuantLib::FDMultiPeriodEngine< Scheme >::timeStepPerPeriod_ [protected]
Definition at line 47 of file fdmultiperiodengine.hpp.
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/vanilla/fdmultiperiodengine.hpp