QuantLib: QuantLib::ZeroInflationIndex Class Reference
QuantLib::ZeroInflationIndex Class Reference
Base class for zero inflation indices.
#include <inflationindex.hpp>
Public Member Functions
ZeroInflationIndex (const std::string &familyName, const Region &region, bool revised, bool interpolated, Frequency frequency, const Period &availabilityLag, const Currency &currency, const Handle< ZeroInflationTermStructure > &ts=Handle< ZeroInflationTermStructure >())
Always use the evaluation date as the reference date.
Index interface
Rate fixing (const Date &fixingDate, bool forecastTodaysFixing=false) const
Other methods
Handle
< ZeroInflationTermStructure > zeroInflationTermStructure () const
boost::shared_ptr
< ZeroInflationIndex > clone (const Handle< ZeroInflationTermStructure > &h) const
Private Member Functions
bool needsForecast (const Date &fixingDate) const
Rate forecastFixing (const Date &fixingDate) const
Private Attributes
Handle
< ZeroInflationTermStructure > zeroInflation_
Detailed Description
Base class for zero inflation indices.
Definition at line 137 of file inflationindex.hpp.
Constructor & Destructor Documentation
QuantLib::ZeroInflationIndex::ZeroInflationIndex (const std::string & familyName, const Region & region, bool revised, bool interpolated, Frequency frequency, const Period & availabilityLag, const Currency & currency, const Handle< ZeroInflationTermStructure > & ts = Handle<ZeroInflationTermStructure>())
Always use the evaluation date as the reference date.
Definition at line 65 of file inflationindex.cpp.
References QuantLib::Observer::registerWith(), and zeroInflation_.
Referenced by clone().
    : InflationIndex(familyName, region, revised, interpolated,
                     frequency, availabilityLag, currency),
      zeroInflation_(zeroInflation) {
        registerWith(zeroInflation_);
    }
Member Function Documentation
boost::shared_ptr< ZeroInflationIndex > QuantLib::ZeroInflationIndex::clone (const Handle< ZeroInflationTermStructure > & h) const
Definition at line 177 of file inflationindex.cpp.
References QuantLib::InflationIndex::availabilityLag_, QuantLib::InflationIndex::currency_, QuantLib::InflationIndex::familyName_, QuantLib::InflationIndex::frequency_, QuantLib::InflationIndex::interpolated_, QuantLib::InflationIndex::region_, QuantLib::InflationIndex::revised_, and ZeroInflationIndex().
{
        return boost::shared_ptr<ZeroInflationIndex>(
                      new ZeroInflationIndex(familyName_, region_, revised_,
                                             interpolated_, frequency_,
                                             availabilityLag_, currency_, h));
    }
Rate QuantLib::ZeroInflationIndex::fixing (const Date & fixingDate, bool forecastTodaysFixing = false) const [virtual]
Warning:
the forecastTodaysFixing parameter (required by the Index interface) is currently ignored.
Implements QuantLib::InflationIndex.
Definition at line 80 of file inflationindex.cpp.
References forecastFixing(), QuantLib::InflationIndex::frequency_, QuantLib::inflationPeriod(), QuantLib::InflationIndex::interpolated_, QuantLib::InflationIndex::name(), needsForecast(), QL_REQUIRE, and QuantLib::Index::timeSeries().
Referenced by forecastFixing().
{
        if (!needsForecast(aFixingDate)) {
            const TimeSeries<Real>& ts = timeSeries();
            Real pastFixing = ts[aFixingDate];
            QL_REQUIRE(pastFixing != Null<Real>(),
                       "Missing " << name() << " fixing for " << aFixingDate);
            Real theFixing = pastFixing;
            if (interpolated_) {
                // fixings stored flat & for every day
                std::pair<Date,Date> lim =
                    inflationPeriod(aFixingDate, frequency_);
                if (aFixingDate == lim.first) {
                    // we don't actually need the next fixing
                    theFixing = pastFixing;
                } else {
                    Date fixingDate2 = aFixingDate + Period(frequency_);
                    Real pastFixing2 = ts[fixingDate2];
                    QL_REQUIRE(pastFixing2 != Null<Real>(),
                               "Missing " << name() << " fixing for " << fixingDate2);
                    // now linearly interpolate
                    Real daysInPeriod = lim.second+1 - lim.first;
                    theFixing = pastFixing
                        + (pastFixing2-pastFixing)*(aFixingDate-lim.first)/daysInPeriod;
                }
            }
            return theFixing;
        } else {
            return forecastFixing(aFixingDate);
        }
    }
Rate QuantLib::ZeroInflationIndex::forecastFixing (const Date & fixingDate) const [private]
Definition at line 149 of file inflationindex.cpp.
References QuantLib::Days, fixing(), QuantLib::InflationIndex::frequency(), QuantLib::inflationPeriod(), QuantLib::InflationIndex::interpolated(), QuantLib::InflationIndex::name(), needsForecast(), QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow(), QL_REQUIRE, anonymous_namespace{quantlibbenchmark.cpp}::t, and zeroInflation_.
Referenced by fixing().
{
        // the term structure is relative to the fixing value at the base date.
        Date baseDate = zeroInflation_->baseDate();
        QL_REQUIRE(!needsForecast(baseDate),
                   name() << " index fixing at base date is not available");
        Real baseFixing = fixing(baseDate);
        Date effectiveFixingDate;
        if (interpolated()) {
            effectiveFixingDate = fixingDate;
        } else {
            // start of period is the convention
            // so it's easier to do linear interpolation on fixings
            effectiveFixingDate = inflationPeriod(fixingDate, frequency()).first;
        }
        // no observation lag because it is the fixing for the date
        // but if index is not interpolated then that fixing is constant
        // for each period, hence the t uses the effectiveFixingDate
        // However, it's slightly safe to get the zeroRate with the
        // fixingDate to avoid potential problems at the edges of periods
        Time t = zeroInflation_->dayCounter().yearFraction(baseDate, effectiveFixingDate);
        bool forceLinearInterpolation = false;
        Rate zero = zeroInflation_->zeroRate(fixingDate, Period(0,Days), forceLinearInterpolation);
        // Annual compounding is the convention for zero inflation rates (or quotes)
        return baseFixing * std::pow(1.0 + zero, t);
    }
bool QuantLib::ZeroInflationIndex::needsForecast (const Date & fixingDate) const [private]
Definition at line 113 of file inflationindex.cpp.
References QuantLib::InflationIndex::availabilityLag_, QuantLib::Settings::evaluationDate(), anonymous_namespace{interpolations.cpp}::f(), QuantLib::InflationIndex::frequency_, QuantLib::inflationPeriod(), QuantLib::Singleton< Settings >::instance(), QuantLib::InflationIndex::interpolated_, and QuantLib::Index::timeSeries().
Referenced by fixing(), and forecastFixing().
{
        // Stored fixings are always non-interpolated.
        // If an interpolated fixing is required then
        // the availability lag + one inflation period
        // must have passed to use historical fixings
        // (because you need the next one to interpolate).
        // The interpolation is calculated (linearly) on demand.
        Date today = Settings::instance().evaluationDate();
        Date todayMinusLag = today - availabilityLag_;
        Date historicalFixingKnown =
            inflationPeriod(todayMinusLag, frequency_).first-1;
        Date latestNeededDate = fixingDate;
        if (interpolated_) { // might need the next one too
            std::pair<Date,Date> p = inflationPeriod(fixingDate, frequency_);
            if (fixingDate > p.first)
                latestNeededDate += Period(frequency_);
        }
        if (latestNeededDate <= historicalFixingKnown) {
            // the fixing date is well before the availability lag, so
            // we know that fixings were provided.
            return false;
        } else {
            // we're not sure, but the fixing might be there so we
            // check.  Todo: check which fixings are not possible, to
            // avoid using fixings in the future
            Real f = timeSeries()[latestNeededDate];
            return (f == Null<Real>());
        }
    }
Handle< ZeroInflationTermStructure > QuantLib::ZeroInflationIndex::zeroInflationTermStructure () const [inline]
Definition at line 249 of file inflationindex.hpp.
References zeroInflation_.
{
        return zeroInflation_;
    }
Member Data Documentation
Handle<ZeroInflationTermStructure> QuantLib::ZeroInflationIndex::zeroInflation_ [private]
Definition at line 167 of file inflationindex.hpp.
Referenced by forecastFixing(), ZeroInflationIndex(), and zeroInflationTermStructure().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/indexes/inflationindex.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/indexes/inflationindex.cpp