QuantLib: QuantLib::BlackDeltaCalculator Class Reference
QuantLib::BlackDeltaCalculator Class Reference
Black delta calculator class.
#include <blackdeltacalculator.hpp>
Public Member Functions
BlackDeltaCalculator (Option::Type ot, DeltaVolQuote::DeltaType dt, Real spot, DiscountFactor dDiscount, DiscountFactor fDiscount, Real stdDev)
Real deltaFromStrike (Real strike) const
Real strikeFromDelta (Real delta) const
Real cumD1 (Real strike) const
Real cumD2 (Real strike) const
Real nD1 (Real strike) const
Real nD2 (Real strike) const
void setDeltaType (DeltaVolQuote::DeltaType dt)
void setOptionType (Option::Type ot)
Real atmStrike (DeltaVolQuote::AtmType atmT) const
Private Member Functions
Real strikeFromDelta (Real delta, DeltaVolQuote::DeltaType dt) const
Private Attributes
DeltaVolQuote::DeltaType dt_
Option::Type ot_
DiscountFactor dDiscount_
DiscountFactor fDiscount_
Real stdDev_
Real spot_
Real forward_
Integer phi_
Real d1_
Real d2_
Real fExpPos_
Real fExpNeg_
Detailed Description
Black delta calculator class.
Class includes many operations needed for different applications in FX markets, which has special quoation mechanisms, since every price can be expressed in both numeraires.
Definition at line 39 of file blackdeltacalculator.hpp.
Constructor & Destructor Documentation
QuantLib::BlackDeltaCalculator::BlackDeltaCalculator (Option::Type ot, DeltaVolQuote::DeltaType dt, Real spot, DiscountFactor dDiscount, DiscountFactor fDiscount, Real stdDev)
Definition at line 24 of file blackdeltacalculator.cpp.
References dDiscount_, fDiscount_, fExpNeg_, fExpPos_, forward_, QL_REQUIRE, spot_, and stdDev_.
                                    :
    dt_(dt), ot_(ot),
    dDiscount_(dDiscount), fDiscount_(fDiscount),
    stdDev_(stdDev), spot_(spot),
    forward_(spot*fDiscount/dDiscount), phi_(Integer(ot)) {
        QL_REQUIRE(spot_>0.0,
                   "positive spot value required: " <<
                   spot_ << " not allowed");
        QL_REQUIRE(dDiscount_>0.0,
                   "positive domestic discount factor required: " <<
                   dDiscount_ << " not allowed");
        QL_REQUIRE(fDiscount_>0.0,
                   "positive foreign discount factor required: " <<
                   fDiscount_ << " not allowed");
        QL_REQUIRE(stdDev_>=0.0,
                   "non-negative standard deviation required: "
                   << stdDev_ << " not allowed");
        fExpPos_    =forward_*exp(0.5*stdDev_*stdDev_);
        fExpNeg_    =forward_*exp(-0.5*stdDev_*stdDev_);
    }
Member Function Documentation
Real QuantLib::BlackDeltaCalculator::atmStrike (DeltaVolQuote::AtmType atmT) const
Definition at line 177 of file blackdeltacalculator.cpp.
References QuantLib::DeltaVolQuote::AtmDeltaNeutral, QuantLib::DeltaVolQuote::AtmFwd, QuantLib::DeltaVolQuote::AtmGammaMax, QuantLib::DeltaVolQuote::AtmPutCall50, QuantLib::DeltaVolQuote::AtmVegaMax, dt_, fExpNeg_, fExpPos_, forward_, QuantLib::DeltaVolQuote::Fwd, QL_FAIL, QL_REQUIRE, and QuantLib::DeltaVolQuote::Spot.
Referenced by BlackDeltaCalculatorTest::testAtmCalcs().
{
        Real res=0.0;
        switch(atmT) {
          case DeltaVolQuote::AtmDeltaNeutral:
            if(dt_==DeltaVolQuote::Spot || dt_==DeltaVolQuote::Fwd){
                res=fExpPos_;
            } else {
                res=fExpNeg_;
            }
            break;
          case DeltaVolQuote::AtmFwd:
            res=forward_;
            break;
          case DeltaVolQuote::AtmGammaMax: case DeltaVolQuote::AtmVegaMax:
            res=fExpPos_;
            break;
          case DeltaVolQuote::AtmPutCall50:
            QL_REQUIRE(dt_==DeltaVolQuote::Fwd,
                       "|PutDelta|=CallDelta=0.50 only possible for forward delta.");
            res=fExpPos_;
            break;
          default:
            QL_FAIL("invalid atm type");
        }
        return res;
    }
Real QuantLib::BlackDeltaCalculator::cumD1 (Real strike) const
Definition at line 212 of file blackdeltacalculator.cpp.
References d1_, anonymous_namespace{interpolations.cpp}::f(), forward_, phi_, QL_EPSILON, and stdDev_.
Referenced by deltaFromStrike().
{
        Real d1_=0.0;
        Real cum_d1_pos_ = 1.0; // N(d1)
        Real cum_d1_neg_ = 0.0; // N(-d1)
        CumulativeNormalDistribution f;
        if (stdDev_>=QL_EPSILON) {
            if(strike>0) {
                d1_ = std::log(forward_/strike)/stdDev_ + 0.5*stdDev_;
                return f(phi_*d1_);
            }
        } else {
            if (forward_<strike) {
                cum_d1_pos_ = 0.0;
                cum_d1_neg_ = 1.0;
            } else if(forward_==strike){
                d1_ = 0.5*stdDev_;
                return f(phi_*d1_);
            }
        }
        if (phi_>0) { // if Call
            return cum_d1_pos_;
        } else {
            return cum_d1_neg_;
        }
    }
Real QuantLib::BlackDeltaCalculator::cumD2 (Real strike) const
Definition at line 260 of file blackdeltacalculator.cpp.
References d2_, anonymous_namespace{interpolations.cpp}::f(), forward_, phi_, QL_EPSILON, and stdDev_.
Referenced by deltaFromStrike(), and QuantLib::BlackDeltaPremiumAdjustedMaxStrikeClass::operator()().
{
        Real d2_=0.0;
        Real cum_d2_pos_= 1.0;  // N(d2)
        Real cum_d2_neg_= 0.0;  // N(-d2)
        CumulativeNormalDistribution f;
        if (stdDev_>=QL_EPSILON){
            if(strike>0){
                d2_ = std::log(forward_/strike)/stdDev_ - 0.5*stdDev_;
                return f(phi_*d2_);
            }
        } else {
            if (forward_<strike) {
                cum_d2_pos_= 0.0;
                cum_d2_neg_= 1.0;
            } else if (forward_==strike) {
                d2_ = -0.5*stdDev_;
                return(f(phi_*d2_));
            }
        }
        if (phi_>0) { // if Call
            return cum_d2_pos_;
        } else {
            return cum_d2_neg_;
        }
    }
Real QuantLib::BlackDeltaCalculator::deltaFromStrike (Real strike) const
Definition at line 54 of file blackdeltacalculator.cpp.
References cumD1(), cumD2(), dt_, fDiscount_, forward_, QuantLib::DeltaVolQuote::Fwd, QuantLib::DeltaVolQuote::PaFwd, QuantLib::DeltaVolQuote::PaSpot, phi_, QL_FAIL, QL_REQUIRE, and QuantLib::DeltaVolQuote::Spot.
Referenced by QuantLib::BlackDeltaPremiumAdjustedSolverClass::operator()(), BlackDeltaCalculatorTest::testAtmCalcs(), BlackDeltaCalculatorTest::testDeltaValues(), and BlackDeltaCalculatorTest::testPutCallParity().
{
        QL_REQUIRE(strike >=0.0,
                   "positive strike value required: " <<
                   strike << " not allowed");
        Real res=0.0;
        switch(dt_){
          case DeltaVolQuote::Spot:
            res=phi_*fDiscount_*cumD1(strike);
            break;
          case DeltaVolQuote::Fwd:
            res=phi_*cumD1(strike);
            break;
          case DeltaVolQuote::PaSpot:
            res=phi_*fDiscount_*cumD2(strike)*strike/forward_;
            break;
          case DeltaVolQuote::PaFwd:
            res=phi_*cumD2(strike)*strike/forward_;
            break;
          default:
            QL_FAIL("invalid delta type");
        }
        return res;
    }
Real QuantLib::BlackDeltaCalculator::nD1 (Real strike) const
Definition at line 243 of file blackdeltacalculator.cpp.
References d1_, QuantLib::CumulativeNormalDistribution::derivative(), anonymous_namespace{interpolations.cpp}::f(), forward_, QL_EPSILON, and stdDev_.
{
        Real d1_=0.0;
        Real n_d1_ = 0.0; // n(d1)
        if (stdDev_>=QL_EPSILON){
            if(strike>0){
                d1_ = std::log(forward_/strike)/stdDev_ + 0.5*stdDev_;
                CumulativeNormalDistribution f;
                n_d1_ = f.derivative(d1_);
            }
        }
        return n_d1_;
    }
Real QuantLib::BlackDeltaCalculator::nD2 (Real strike) const
Definition at line 295 of file blackdeltacalculator.cpp.
References d2_, QuantLib::CumulativeNormalDistribution::derivative(), anonymous_namespace{interpolations.cpp}::f(), forward_, QL_EPSILON, and stdDev_.
Referenced by QuantLib::BlackDeltaPremiumAdjustedMaxStrikeClass::operator()().
{
        Real d2_=0.0;
        Real n_d2_= 0.0; // n(d2)
        if (stdDev_>=QL_EPSILON){
            if(strike>0){
                d2_ = std::log(forward_/strike)/stdDev_ - 0.5*stdDev_;
                CumulativeNormalDistribution f;
                n_d2_ = f.derivative(d2_);
            }
        }
        return n_d2_;
    }
void QuantLib::BlackDeltaCalculator::setDeltaType (DeltaVolQuote::DeltaType dt)
Definition at line 312 of file blackdeltacalculator.cpp.
References QuantLib::anonymous_namespace{yieldtermstructure.cpp}::dt, and dt_.
Referenced by BlackDeltaCalculatorTest::testAtmCalcs().
{
        dt_=dt;
    }
void QuantLib::BlackDeltaCalculator::setOptionType (Option::Type ot)
Definition at line 316 of file blackdeltacalculator.cpp.
References ot_, and phi_.
Referenced by BlackDeltaCalculatorTest::testAtmCalcs().
{
        ot_=ot;
        phi_=Integer(ot_);
    }
Real QuantLib::BlackDeltaCalculator::strikeFromDelta (Real delta) const
Definition at line 85 of file blackdeltacalculator.cpp.
References dt_.
Referenced by strikeFromDelta(), and BlackDeltaCalculatorTest::testDeltaValues().
{
        return(strikeFromDelta(delta, dt_));
    }
Real QuantLib::BlackDeltaCalculator::strikeFromDelta (Real delta, DeltaVolQuote::DeltaType dt) const [private]
Definition at line 89 of file blackdeltacalculator.cpp.
References dDiscount_, anonymous_namespace{interpolations.cpp}::f(), fDiscount_, forward_, QuantLib::DeltaVolQuote::Fwd, ot_, QuantLib::DeltaVolQuote::PaFwd, QuantLib::DeltaVolQuote::PaSpot, phi_, QL_FAIL, QL_REQUIRE, QuantLib::Solver1D< Impl >::setMaxEvaluations(), QuantLib::Solver1D< Impl >::solve(), QuantLib::DeltaVolQuote::Spot, spot_, stdDev_, and strikeFromDelta().
{
        Real res=0.0;
        Real arg=0.0;
        InverseCumulativeNormal f;
        QL_REQUIRE(delta*phi_>=0.0, "Option type and delta are incoherent.");
        switch (dt) {
          case DeltaVolQuote::Spot:
            QL_REQUIRE(std::fabs(delta)<=fDiscount_,
                       "Spot delta out of range.");
            arg=-phi_*f(phi_*delta/fDiscount_)*stdDev_+0.5*stdDev_*stdDev_;
            res=forward_*exp(arg);
            break;
          case DeltaVolQuote::Fwd:
            QL_REQUIRE(std::fabs(delta)<=1.0,
                       "Forward delta out of range.");
            arg=-phi_*f(phi_*delta)*stdDev_+0.5*stdDev_*stdDev_;
            res=forward_*exp(arg);
            break;
          case DeltaVolQuote::PaSpot:
          case DeltaVolQuote::PaFwd: {
              // This has to be solved numerically. One of the
              // problems is that the premium adjusted call delta is
              // not monotonic in strike, such that two solutions
              // might occur. The one right to the max of the delta is
              // considered to be the correct strike.  Some proper
              // interval bounds for the strike need to be chosen, the
              // numerics can otherwise be very unreliable and
              // unstable.  I've chosen Brent over Newton, since the
              // interval can be specified explicitly and we can not
              // run into the area on the left of the maximum.  The
              // put delta doesn't have this property and can be
              // solved without any problems, but also numerically.
              BlackDeltaPremiumAdjustedSolverClass f(
                       ot_, dt , spot_,dDiscount_, fDiscount_, stdDev_,delta);
              Brent solver;
              solver.setMaxEvaluations(1000);
              Real accuracy = 1.0e-10;
              Real rightLimit=0.0;
              Real leftLimit=0.0;
              // Strike of not premium adjusted is always to the right of premium adjusted
              if (dt==DeltaVolQuote::PaSpot) {
                  rightLimit=strikeFromDelta(delta, DeltaVolQuote::Spot);
              } else {
                  rightLimit=strikeFromDelta(delta, DeltaVolQuote::Fwd);
              }
              if (phi_<0) { // if put
                  res=solver.solve(f, accuracy, rightLimit, 0.0, spot_*100.0);
                  break;
              } else {
                  // find out the left limit which is the strike
                  // corresponding to the value where premium adjusted
                  // deltas have their maximum.
                  BlackDeltaPremiumAdjustedMaxStrikeClass g(
                               ot_,dt, spot_,dDiscount_, fDiscount_, stdDev_);
                  leftLimit=solver.solve(g, accuracy, rightLimit*0.5,
                                         0.0, rightLimit);
                  Real guess=leftLimit+(rightLimit-leftLimit)*0.5;
                  res=solver.solve(f, accuracy, guess, leftLimit, rightLimit);
              } // end if phi<0 else
              break;
          }
          default:
            QL_FAIL("invalid delta type");
        }
        return res;
    }
Member Data Documentation
Real QuantLib::BlackDeltaCalculator::d1_ [private]
Definition at line 81 of file blackdeltacalculator.hpp.
Referenced by cumD1(), and nD1().
Real QuantLib::BlackDeltaCalculator::d2_ [private]
Definition at line 81 of file blackdeltacalculator.hpp.
Referenced by cumD2(), and nD2().
DiscountFactor QuantLib::BlackDeltaCalculator::dDiscount_ [private]
Definition at line 77 of file blackdeltacalculator.hpp.
Referenced by BlackDeltaCalculator(), and strikeFromDelta().
DeltaVolQuote::DeltaType QuantLib::BlackDeltaCalculator::dt_ [private]
Definition at line 75 of file blackdeltacalculator.hpp.
Referenced by atmStrike(), deltaFromStrike(), setDeltaType(), and strikeFromDelta().
DiscountFactor QuantLib::BlackDeltaCalculator::fDiscount_ [private]
Definition at line 77 of file blackdeltacalculator.hpp.
Referenced by BlackDeltaCalculator(), deltaFromStrike(), and strikeFromDelta().
Real QuantLib::BlackDeltaCalculator::fExpNeg_ [private]
Definition at line 81 of file blackdeltacalculator.hpp.
Referenced by atmStrike(), and BlackDeltaCalculator().
Real QuantLib::BlackDeltaCalculator::fExpPos_ [private]
Definition at line 81 of file blackdeltacalculator.hpp.
Referenced by atmStrike(), and BlackDeltaCalculator().
Real QuantLib::BlackDeltaCalculator::forward_ [private]
Definition at line 79 of file blackdeltacalculator.hpp.
Referenced by atmStrike(), BlackDeltaCalculator(), cumD1(), cumD2(), deltaFromStrike(), nD1(), nD2(), and strikeFromDelta().
Option::Type QuantLib::BlackDeltaCalculator::ot_ [private]
Definition at line 76 of file blackdeltacalculator.hpp.
Referenced by setOptionType(), and strikeFromDelta().
Integer QuantLib::BlackDeltaCalculator::phi_ [private]
Definition at line 80 of file blackdeltacalculator.hpp.
Referenced by cumD1(), cumD2(), deltaFromStrike(), setOptionType(), and strikeFromDelta().
Real QuantLib::BlackDeltaCalculator::spot_ [private]
Definition at line 79 of file blackdeltacalculator.hpp.
Referenced by BlackDeltaCalculator(), and strikeFromDelta().
Real QuantLib::BlackDeltaCalculator::stdDev_ [private]
Definition at line 79 of file blackdeltacalculator.hpp.
Referenced by BlackDeltaCalculator(), cumD1(), cumD2(), nD1(), nD2(), and strikeFromDelta().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/fx/blackdeltacalculator.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/fx/blackdeltacalculator.cpp