QuantLib: QuantLib::TimeGrid Class Reference
QuantLib::TimeGrid Class Reference
time grid class
#include <timegrid.hpp>
Public Member Functions
Constructors
TimeGrid ()
TimeGrid (Time end, Size steps)
Regularly spaced time-grid.
template<class Iterator >
TimeGrid (Iterator begin, Iterator end)
Time grid with mandatory time points.
template<class Iterator >
TimeGrid (Iterator begin, Iterator end, Size steps)
Time grid with mandatory time points.
Time grid interface
Size index (Time t) const
returns the index i such that grid[i] = t
Size closestIndex (Time t) const
returns the index i such that grid[i] is closest to t
Time closestTime (Time t) const
returns the time on the grid closest to the given t
const std::vector< Time > & mandatoryTimes () const
Time dt (Size i) const
Private Attributes
std::vector< Time > times_
std::vector< Time > dt_
std::vector< Time > mandatoryTimes_
sequence interface
typedef std::vector< Time >
::const_iterator const_iterator
typedef std::vector< Time >
::const_reverse_iterator const_reverse_iterator
Time operator[] (Size i) const
Time at (Size i) const
Size size () const
bool empty () const
const_iterator begin () const
const_iterator end () const
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
Time front () const
Time back () const
Detailed Description
time grid class
Todo:
what was the rationale for limiting the grid to positive times? Investigate and see whether we can use it for negative ones as well.
Definition at line 40 of file timegrid.hpp.
Member Typedef Documentation
typedef std::vector<Time>::const_iterator QuantLib::TimeGrid::const_iterator
Definition at line 152 of file timegrid.hpp.
typedef std::vector<Time>::const_reverse_iterator QuantLib::TimeGrid::const_reverse_iterator
Definition at line 154 of file timegrid.hpp.
Constructor & Destructor Documentation
QuantLib::TimeGrid::TimeGrid () [inline]
Definition at line 44 of file timegrid.hpp.
{}
QuantLib::TimeGrid::TimeGrid (Time end, Size steps)
Regularly spaced time-grid.
Definition at line 26 of file timegrid.cpp.
References dt(), dt_, end(), mandatoryTimes_, QL_REQUIRE, and times_.
{
        // We seem to assume that the grid begins at 0.
        // Let's enforce the assumption for the time being
        // (even though I'm not sure that I agree.)
        QL_REQUIRE(end > 0.0,
                   "negative times not allowed");
        Time dt = end/steps;
        times_.reserve(steps+1);
        for (Size i=0; i<=steps; i++)
            times_.push_back(dt*i);
        mandatoryTimes_ = std::vector<Time>(1);
        mandatoryTimes_[0] = end;
        dt_ = std::vector<Time>(steps,dt);
    }
template<class Iterator > QuantLib::TimeGrid::TimeGrid (Iterator begin, Iterator end) [inline]
Time grid with mandatory time points.
Mandatory points are guaranteed to belong to the grid. No additional points are added.
Definition at line 52 of file timegrid.hpp.
References QuantLib::close_enough(), dt_, mandatoryTimes_, QL_REQUIRE, and times_.
        : mandatoryTimes_(begin, end) {
            std::sort(mandatoryTimes_.begin(),mandatoryTimes_.end());
            // We seem to assume that the grid begins at 0.
            // Let's enforce the assumption for the time being
            // (even though I'm not sure that I agree.)
            QL_REQUIRE(mandatoryTimes_.front() >= 0.0,
                       "negative times not allowed");
            std::vector<Time>::iterator e =
                std::unique(mandatoryTimes_.begin(),mandatoryTimes_.end(),
                            std::ptr_fun(close_enough));
            mandatoryTimes_.resize(e - mandatoryTimes_.begin());
            if (mandatoryTimes_[0] > 0.0)
                times_.push_back(0.0);
            times_.insert(times_.end(),
                          mandatoryTimes_.begin(), mandatoryTimes_.end());
            std::adjacent_difference(times_.begin()+1,times_.end(),
                                     std::back_inserter(dt_));
        }
template<class Iterator > QuantLib::TimeGrid::TimeGrid (Iterator begin, Iterator end, Size steps) [inline]
Time grid with mandatory time points.
Mandatory points are guaranteed to belong to the grid. Additional points are then added with regular spacing between pairs of mandatory times in order to reach the desired number of steps.
Definition at line 82 of file timegrid.hpp.
References QuantLib::close_enough(), dt(), dt_, mandatoryTimes_, QL_REQUIRE, anonymous_namespace{quantlibbenchmark.cpp}::t, and times_.
        : mandatoryTimes_(begin, end) {
            std::sort(mandatoryTimes_.begin(),mandatoryTimes_.end());
            // We seem to assume that the grid begins at 0.
            // Let's enforce the assumption for the time being
            // (even though I'm not sure that I agree.)
            QL_REQUIRE(mandatoryTimes_.front() >= 0.0,
                       "negative times not allowed");
            std::vector<Time>::iterator e =
                std::unique(mandatoryTimes_.begin(),mandatoryTimes_.end(),
                            std::ptr_fun(close_enough));
            mandatoryTimes_.resize(e - mandatoryTimes_.begin());
            Time last = mandatoryTimes_.back();
            Time dtMax;
            // The resulting timegrid have points at times listed in the input
            // list. Between these points, there are inner-points which are
            // regularly spaced.
            if (steps == 0) {
                std::vector<Time> diff;
                std::adjacent_difference(mandatoryTimes_.begin(),
                                         mandatoryTimes_.end(),
                                         std::back_inserter(diff));
                if (diff.front()==0.0)
                    diff.erase(diff.begin());
                dtMax = *(std::min_element(diff.begin(), diff.end()));
            } else {
                dtMax = last/steps;
            }
            Time periodBegin = 0.0;
            times_.push_back(periodBegin);
            for (std::vector<Time>::const_iterator t=mandatoryTimes_.begin();
                                                   t<mandatoryTimes_.end();
                                                   t++) {
                Time periodEnd = *t;
                if (periodEnd != 0.0) {
                    // the nearest integer
                    Size nSteps = Size((periodEnd - periodBegin)/dtMax+0.5);
                    // at least one time step!
                    nSteps = (nSteps!=0 ? nSteps : 1);
                    Time dt = (periodEnd - periodBegin)/nSteps;
                    times_.reserve(nSteps);
                    for (Size n=1; n<=nSteps; ++n)
                        times_.push_back(periodBegin + n*dt);
                }
                periodBegin = periodEnd;
            }
            std::adjacent_difference(times_.begin()+1,times_.end(),
                                     std::back_inserter(dt_));
        }
Member Function Documentation
Time QuantLib::TimeGrid::at (Size i) const [inline]
Definition at line 157 of file timegrid.hpp.
References times_.
{ return times_.at(i); }
Time QuantLib::TimeGrid::back () const [inline]
Definition at line 165 of file timegrid.hpp.
References times_.
Referenced by QuantLib::DigitalPathPricer::operator()(), and QuantLib::VariancePathPricer::operator()().
{ return times_.back(); }
const_iterator QuantLib::TimeGrid::begin () const [inline]
Definition at line 160 of file timegrid.hpp.
References times_.
Referenced by closestIndex().
{ return times_.begin(); }
Size QuantLib::TimeGrid::closestIndex (Time t) const
returns the index i such that grid[i] is closest to t
Definition at line 80 of file timegrid.cpp.
References begin(), end(), size(), anonymous_namespace{quantlibbenchmark.cpp}::t, and times_.
Referenced by closestTime(), index(), and SwingOptionTest::testExtOUJumpSwingOption().
{
        const_iterator begin = times_.begin(), end = times_.end();
        const_iterator result = std::lower_bound(begin, end, t);
        if (result == begin) {
            return 0;
        } else if (result == end) {
            return size()-1;
        } else {
            Time dt1 = *result - t;
            Time dt2 = t - *(result-1);
            if (dt1 < dt2)
                return result-begin;
            else
                return (result-begin)-1;
        }
    }
Time QuantLib::TimeGrid::closestTime (Time t) const [inline]
returns the time on the grid closest to the given t
Definition at line 142 of file timegrid.hpp.
References closestIndex(), and times_.
Referenced by QuantLib::DiscretizedConvertible::DiscretizedConvertible(), and QuantLib::DiscretizedVanillaOption::DiscretizedVanillaOption().
{
            return times_[closestIndex(t)];
        }
Time QuantLib::TimeGrid::dt (Size i) const [inline]
Definition at line 148 of file timegrid.hpp.
References dt_.
Referenced by QuantLib::MultiPathGenerator< GSG >::next(), QuantLib::DigitalPathPricer::operator()(), QuantLib::BarrierPathPricer::operator()(), QuantLib::VariancePathPricer::operator()(), QuantLib::detail::Integrand::operator()(), TimeGrid(), and QuantLib::TrinomialTree::TrinomialTree().
{ return dt_[i]; }
bool QuantLib::TimeGrid::empty () const [inline]
Definition at line 159 of file timegrid.hpp.
References times_.
Referenced by QuantLib::DiscretizedConvertible::DiscretizedConvertible(), QuantLib::DiscretizedVanillaOption::DiscretizedVanillaOption(), and QuantLib::Path::empty().
{ return times_.empty(); }
const_iterator QuantLib::TimeGrid::end () const [inline]
Definition at line 161 of file timegrid.hpp.
References times_.
Referenced by closestIndex(), and TimeGrid().
{ return times_.end(); }
Time QuantLib::TimeGrid::front () const [inline]
Definition at line 164 of file timegrid.hpp.
References times_.
Referenced by QuantLib::VariancePathPricer::operator()().
{ return times_.front(); }
Size QuantLib::TimeGrid::index (Time t) const
returns the index i such that grid[i] = t
Definition at line 43 of file timegrid.cpp.
References QuantLib::close_enough(), closestIndex(), QL_FAIL, and times_.
Referenced by QuantLib::TreeLattice1D< BlackScholesLattice< T > >::grid(), QuantLib::DiscretizedAsset::isOnTime(), QuantLib::MCAmericanPathEngine< RNG >::lsmPathPricer(), and QuantLib::MCPathBasketEngine< RNG, S >::pathPricer().
{
        Size i = closestIndex(t);
        if (close_enough(t,times_[i])) {
            return i;
        } else {
            if (t < times_.front()) {
                QL_FAIL("using inadequate time grid: all nodes "
                        "are later than the required time t = "
                        << std::setprecision(12) << t
                        << " (earliest node is t1 = "
                        << std::setprecision(12) << times_.front() << ")");
            } else if (t > times_.back()) {
                QL_FAIL("using inadequate time grid: all nodes "
                        "are earlier than the required time t = "
                        << std::setprecision(12) << t
                        << " (latest node is t1 = "
                        << std::setprecision(12) << times_.back() << ")");
            } else {
                Size j, k;
                if (t > times_[i]) {
                    j = i;
                    k = i+1;
                } else {
                    j = i-1;
                    k = i;
                }
                QL_FAIL("using inadequate time grid: the nodes closest "
                        "to the required time t = "
                        << std::setprecision(12) << t
                        << " are t1 = "
                        << std::setprecision(12) << times_[j]
                        << " and t2 = "
                        << std::setprecision(12) << times_[k]);
            }
        }
    }
const std::vector<Time>& QuantLib::TimeGrid::mandatoryTimes () const [inline]
Definition at line 145 of file timegrid.hpp.
References mandatoryTimes_.
Referenced by QuantLib::MCAmericanPathEngine< RNG >::lsmPathPricer(), QuantLib::ArithmeticASOPathPricer::operator()(), QuantLib::GeometricAPOPathPricer::operator()(), QuantLib::ArithmeticAPOPathPricer::operator()(), and QuantLib::MCPathBasketEngine< RNG, S >::pathPricer().
{
            return mandatoryTimes_;
        }
Time QuantLib::TimeGrid::operator[] (Size i) const [inline]
Definition at line 156 of file timegrid.hpp.
References times_.
{ return times_[i]; }
const_reverse_iterator QuantLib::TimeGrid::rbegin () const [inline]
Definition at line 162 of file timegrid.hpp.
References times_.
{ return times_.rbegin(); }
const_reverse_iterator QuantLib::TimeGrid::rend () const [inline]
Definition at line 163 of file timegrid.hpp.
References times_.
{ return times_.rend(); }
Size QuantLib::TimeGrid::size () const [inline]
Definition at line 158 of file timegrid.hpp.
References times_.
Referenced by QuantLib::AnalyticPTDHestonEngine::calculate(), closestIndex(), QuantLib::MCHestonHullWhiteEngine< RNG, S >::controlPathGenerator(), QuantLib::AnalyticPTDHestonEngine::Fj_Helper::Fj_Helper(), QuantLib::Path::length(), QuantLib::LongstaffSchwartzPathPricer< PathType >::LongstaffSchwartzPathPricer(), QuantLib::MultiPathGenerator< GSG >::MultiPathGenerator(), QuantLib::Path::Path(), QuantLib::PathGenerator< GSG >::PathGenerator(), QuantLib::MCPerformanceEngine< RNG, S >::pathGenerator(), QuantLib::MCHimalayaEngine< RNG, S >::pathGenerator(), QuantLib::MCPagodaEngine< RNG, S >::pathGenerator(), QuantLib::MCVanillaEngine< SingleVariate, RNG, S >::pathGenerator(), QuantLib::MCLongstaffSchwartzPathEngine< GenericEngine, MC, RNG, S >::pathGenerator(), QuantLib::MCEverestEngine< RNG, S >::pathGenerator(), QuantLib::MCEuropeanBasketEngine< RNG, S >::pathGenerator(), QuantLib::MCPathBasketEngine< RNG, S >::pathGenerator(), QuantLib::MCLongstaffSchwartzEngine< GenericEngine, MC, RNG, S >::pathGenerator(), QuantLib::MCDiscreteAveragingAsianEngine< RNG, S >::pathGenerator(), QuantLib::MCBarrierEngine< RNG, S >::pathGenerator(), QuantLib::MCVarianceSwapEngine< RNG, S >::pathGenerator(), QuantLib::MCHullWhiteCapFloorEngine< RNG, S >::pathGenerator(), QuantLib::MCDigitalEngine< RNG, S >::pathPricer(), QuantLib::MCBarrierEngine< RNG, S >::pathPricer(), QuantLib::OneFactorModel::ShortRateTree::ShortRateTree(), SwingOptionTest::testExtOUJumpVanillaEngine(), VPPTest::testGemanRoncoroniProcess(), VPPTest::testKlugeExtOUSpreadOption(), QuantLib::BlackKarasinski::tree(), QuantLib::HullWhite::tree(), QuantLib::GeneralizedHullWhite::tree(), and QuantLib::TrinomialTree::TrinomialTree().
{ return times_.size(); }
Member Data Documentation
std::vector<Time> QuantLib::TimeGrid::dt_ [private]
Definition at line 169 of file timegrid.hpp.
Referenced by dt(), and TimeGrid().
std::vector<Time> QuantLib::TimeGrid::mandatoryTimes_ [private]
Definition at line 170 of file timegrid.hpp.
Referenced by mandatoryTimes(), and TimeGrid().
std::vector<Time> QuantLib::TimeGrid::times_ [private]
Definition at line 168 of file timegrid.hpp.
Referenced by at(), back(), begin(), closestIndex(), closestTime(), empty(), end(), front(), index(), operator[](), rbegin(), rend(), size(), and TimeGrid().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/timegrid.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/timegrid.cpp