QuantLib: QuantLib::AnalyticHaganPricer Class Reference
QuantLib::AnalyticHaganPricer Class Reference
CMS-coupon pricer.
#include <conundrumpricer.hpp>
Public Member Functions
AnalyticHaganPricer (const Handle< SwaptionVolatilityStructure > &swaptionVol, GFunctionFactory::YieldCurveModel modelOfYieldCurve, const Handle< Quote > &meanReversion)
Protected Member Functions
Real optionletPrice (Option::Type optionType, Real strike) const
Real swapletPrice () const
Detailed Description
CMS-coupon pricer.
Definition at line 315 of file conundrumpricer.hpp.
Constructor & Destructor Documentation
QuantLib::AnalyticHaganPricer::AnalyticHaganPricer (const Handle< SwaptionVolatilityStructure > & swaptionVol, GFunctionFactory::YieldCurveModel modelOfYieldCurve, const Handle< Quote > & meanReversion)
Definition at line 447 of file conundrumpricer.cpp.
    : HaganPricer(swaptionVol, modelOfYieldCurve, meanReversion)
      { }
Member Function Documentation
Real QuantLib::AnalyticHaganPricer::optionletPrice (Option::Type optionType, Real strike) const [protected, virtual]
Implements QuantLib::HaganPricer.
Definition at line 455 of file conundrumpricer.cpp.
References QuantLib::Coupon::accrualPeriod(), QuantLib::HaganPricer::annuity_, QuantLib::HaganPricer::coupon_, QuantLib::HaganPricer::discount_, QuantLib::HaganPricer::fixingDate_, QuantLib::HaganPricer::gFunction_, QuantLib::HaganPricer::swapRateValue_, QuantLib::HaganPricer::swapTenor_, and QuantLib::CmsCouponPricer::swaptionVolatility().
{
        Real variance = swaptionVolatility()->blackVariance(fixingDate_,
                                                           swapTenor_,
                                                           swapRateValue_);
        Real firstDerivativeOfGAtForwardValue = gFunction_->firstDerivative(
                                                        swapRateValue_);
        Real price = 0;
        Real CK = (*vanillaOptionPricer_)(strike, optionType, annuity_);
        price += (discount_/annuity_)*CK;
        const Real sqrtSigma2T = std::sqrt(variance);
        const Real lnRoverK =  std::log(swapRateValue_/strike);
        const Real d32 = (lnRoverK+1.5*variance)/sqrtSigma2T;
        const Real d12 =  (lnRoverK+.5*variance)/sqrtSigma2T;
        const Real dminus12 =  (lnRoverK-.5*variance)/sqrtSigma2T;
        CumulativeNormalDistribution cumulativeOfNormal;
        const Real N32 = cumulativeOfNormal(optionType*d32);
        const Real N12 = cumulativeOfNormal(optionType*d12);
        const Real Nminus12 = cumulativeOfNormal(optionType*dminus12);
        price += optionType * firstDerivativeOfGAtForwardValue * annuity_ *
            swapRateValue_ * (swapRateValue_ * std::exp(variance) * N32-
            (swapRateValue_+strike) * N12 + strike * Nminus12);
        price *= coupon_->accrualPeriod();
        return price;
    }
Real QuantLib::AnalyticHaganPricer::swapletPrice () const [protected, virtual]
Implements QuantLib::HaganPricer.
Definition at line 485 of file conundrumpricer.cpp.
References QuantLib::Coupon::accrualPeriod(), QuantLib::HaganPricer::annuity_, QuantLib::HaganPricer::coupon_, QuantLib::HaganPricer::discount_, QuantLib::Settings::evaluationDate(), QuantLib::HaganPricer::fixingDate_, QuantLib::HaganPricer::gearing_, QuantLib::HaganPricer::gFunction_, QuantLib::Singleton< Settings >::instance(), QuantLib::HaganPricer::spread_, QuantLib::HaganPricer::spreadLegValue_, QuantLib::CmsCoupon::swapIndex(), QuantLib::HaganPricer::swapRateValue_, QuantLib::HaganPricer::swapTenor_, and QuantLib::CmsCouponPricer::swaptionVolatility().
{
        Date today = Settings::instance().evaluationDate();
        if (fixingDate_ <= today) {
            // the fixing is determined
            const Rate Rs = coupon_->swapIndex()->fixing(fixingDate_);
            Rate price = (gearing_*Rs + spread_)*(coupon_->accrualPeriod()*discount_);
            return price;
        } else {
            Real variance(swaptionVolatility()->blackVariance(fixingDate_,
                                                               swapTenor_,
                                                               swapRateValue_));
            Real firstDerivativeOfGAtForwardValue(gFunction_->firstDerivative(
                                                            swapRateValue_));
            Real price = 0;
            price += discount_*swapRateValue_;
            price += firstDerivativeOfGAtForwardValue*annuity_*swapRateValue_*
                     swapRateValue_*(std::exp(variance)-1.);
            return gearing_ * price * coupon_->accrualPeriod() + spreadLegValue_;
        }
    }
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/conundrumpricer.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/conundrumpricer.cpp