QuantLib: QuantLib::RichardsonExtrapolation Class Reference
QuantLib::RichardsonExtrapolation Class Reference
Richardson Extrapolation.
#include <richardsonextrapolation.hpp>
Public Member Functions
RichardsonExtrapolation (const boost::function< Real(Real)> &f, Real delta_h, Real n=Null< Real >())
Real operator() (Real t=2.0) const
Real operator() (Real t, Real s) const
Private Attributes
const Real delta_h_
const Real fdelta_h_
const Real n_
const boost::function< Real(Real)> f_
Detailed Description
Richardson Extrapolation.
Richardson Extrapolation is a sequence acceleration technique for
\[ f(\Delta h) = f_0 + \alpha\cdot (\Delta h)^n + O((\Delta h)^{n+1}) \]
References: http://en.wikipedia.org/wiki/Richardson_extrapolation
Definition at line 43 of file richardsonextrapolation.hpp.
Constructor & Destructor Documentation
QuantLib::RichardsonExtrapolation::RichardsonExtrapolation (const boost::function< Real(Real)> & f, Real delta_h, Real n = Null<Real>())
Richardon Extrapolation
Parameters:
f function to be extrapolated to delta_h -> 0
delta_h step size
n if known, n is the order of convergence
Definition at line 46 of file richardsonextrapolation.cpp.
    : delta_h_(delta_h),
      fdelta_h_(f(delta_h)),
      n_(n),
      f_(f) {
    }
Member Function Documentation
Real QuantLib::RichardsonExtrapolation::operator() (Real t = 2.0) const
Extrapolation for known order of convergence
Parameters:
t scaling factor for the step size
Definition at line 55 of file richardsonextrapolation.cpp.
References delta_h_, f_, fdelta_h_, n_, QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow(), and QL_REQUIRE.
{
        QL_REQUIRE(t > 1, "scaling factor must be greater than 1");
        QL_REQUIRE(n_ != Null<Real>(), "order of convergence must be known");
        const Real tk = std::pow(t,n_);
        return (tk*f_(delta_h_/t)-fdelta_h_)/(tk-1.0);
    }
Real QuantLib::RichardsonExtrapolation::operator() (Real t, Real s) const
Extrapolation for unknown order of convergence
Parameters:
t first scaling factor for the step size
s second scaling factor for the step size
Definition at line 65 of file richardsonextrapolation.cpp.
References delta_h_, f_, fdelta_h_, QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow(), QL_REQUIRE, and QuantLib::Solver1D< Impl >::solve().
          {
        QL_REQUIRE(t > 1 && s > 1, "scaling factors must be greater than 1");
        const Real ft = f_(delta_h_/t);
        const Real fs = f_(delta_h_/s);
        const Real k = Brent().solve(RichardsonEqn(fdelta_h_, ft, fs, t, s),
                                     1e-8, 0.05, 10);
        const Real ts = std::pow(s,k);
        return (ts*fs-fdelta_h_)/(ts-1.0);
    }
Member Data Documentation
const Real QuantLib::RichardsonExtrapolation::delta_h_ [private]
Definition at line 66 of file richardsonextrapolation.hpp.
Referenced by operator()().
const boost::function<Real (Real)> QuantLib::RichardsonExtrapolation::f_ [private]
Definition at line 69 of file richardsonextrapolation.hpp.
Referenced by operator()().
const Real QuantLib::RichardsonExtrapolation::fdelta_h_ [private]
Definition at line 67 of file richardsonextrapolation.hpp.
Referenced by operator()().
const Real QuantLib::RichardsonExtrapolation::n_ [private]
Definition at line 68 of file richardsonextrapolation.hpp.
Referenced by operator()().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/richardsonextrapolation.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/math/richardsonextrapolation.cpp