QuantLib: QuantLib::JointStochasticProcess Class Reference
QuantLib::JointStochasticProcess Class Reference
#include <jointstochasticprocess.hpp>
Classes
struct CachingKey
Public Member Functions
JointStochasticProcess (const std::vector< boost::shared_ptr< StochasticProcess > > &l, Size factors=Null< Size >())
Size size () const
returns the number of dimensions of the stochastic process
Size factors () const
returns the number of independent factors of the process
Disposable< Array > initialValues () const
returns the initial values of the state variables
Disposable< Array > drift (Time t, const Array &x) const
returns the drift part of the equation, i.e., \(\mu(t, \mathrm{x}_t) \)
Disposable< Array > expectation (Time t0, const Array &x0, Time dt) const
Disposable< Matrix > diffusion (Time t, const Array &x) const
returns the diffusion part of the equation, i.e. \(\sigma(t, \mathrm{x}_t) \)
Disposable< Matrix > covariance (Time t0, const Array &x0, Time dt) const
Disposable< Matrix > stdDeviation (Time t0, const Array &x0, Time dt) const
Disposable< Array > apply (const Array &x0, const Array &dx) const
Disposable< Array > evolve (Time t0, const Array &x0, Time dt, const Array &dw) const
virtual void preEvolve (Time t0, const Array &x0, Time dt, const Array &dw) const =0
virtual Disposable< Array > postEvolve (Time t0, const Array &x0, Time dt, const Array &dw, const Array &y0) const =0
virtual DiscountFactor numeraire (Time t, const Array &x) const =0
virtual bool correlationIsStateDependent () const =0
virtual Disposable< Matrix > crossModelCorrelation (Time t0, const Array &x0) const =0
const std::vector
< boost::shared_ptr
< StochasticProcess > > & constituents () const
void update ()
Time time (const Date &date) const
Protected Member Functions
Disposable< Array > slice (const Array &x, Size i) const
Protected Attributes
std::vector< boost::shared_ptr
< StochasticProcess > > l_
Private Types
typedef std::vector
< boost::shared_ptr
< StochasticProcess >
>::const_iterator const_iterator
typedef std::vector
< boost::shared_ptr
< StochasticProcess >
>::iterator iterator
Private Attributes
Size size_
Size factors_
Size modelFactors_
std::vector< Size > vsize_
std::vector< Size > vfactors_
std::map< CachingKey, Matrix > correlationCache_
Detailed Description
Definition at line 34 of file jointstochasticprocess.hpp.
Member Typedef Documentation
typedef std::vector<boost::shared_ptr<StochasticProcess> >::const_iterator QuantLib::JointStochasticProcess::const_iterator [private]
Definition at line 80 of file jointstochasticprocess.hpp.
typedef std::vector<boost::shared_ptr<StochasticProcess> >::iterator QuantLib::JointStochasticProcess::iterator [private]
Reimplemented from QuantLib::Observable.
Definition at line 83 of file jointstochasticprocess.hpp.
Constructor & Destructor Documentation
QuantLib::JointStochasticProcess::JointStochasticProcess (const std::vector< boost::shared_ptr< StochasticProcess > > & l, Size factors = Null<Size>())
Definition at line 30 of file jointstochasticprocess.cpp.
References factors_, l_, modelFactors_, QL_REQUIRE, QuantLib::Observer::registerWith(), size_, vfactors_, and vsize_.
    : l_      (l),
      size_   (0),
      factors_(factors),
      modelFactors_(0) {
        for (const_iterator iter=l_.begin(); iter != l_.end(); ++iter) {
            registerWith(*iter);
        }
        vsize_.reserve   (l_.size()+1);
        vfactors_.reserve(l_.size()+1);
        for (const_iterator iter = l_.begin(); iter != l_.end(); ++iter) {
            vsize_.push_back(size_);
            size_ += (*iter)->size();
            vfactors_.push_back(modelFactors_);
            modelFactors_ += (*iter)->factors();
        }
        vsize_.push_back(size_);
        vfactors_.push_back(modelFactors_);
        if (factors_ == Null<Size>()) {
            factors_ = modelFactors_;
        } else {
            QL_REQUIRE(factors_ <= size_, "too many factors given");
        }
    }
Member Function Documentation
Disposable< Array > QuantLib::JointStochasticProcess::apply (const Array & x0, const Array & dx) const [virtual]
applies a change to the asset value. By default, it returns \(\mathrm{x} + \Delta \mathrm{x} \).
Reimplemented from QuantLib::StochasticProcess.
Definition at line 175 of file jointstochasticprocess.cpp.
References QuantLib::Array::begin(), QuantLib::Array::end(), l_, size(), slice(), and vsize_.
{
        Array retVal(size());
        for (Size i=0; i < l_.size(); ++i) {
            const Array& pApply = l_[i]->apply(slice(x0,i), slice(dx,i));
            std::copy(pApply.begin(), pApply.end(),
                      retVal.begin()+vsize_[i]);
        }
        return retVal;
    }
const std::vector< boost::shared_ptr< StochasticProcess > > & QuantLib::JointStochasticProcess::constituents () const
Definition at line 299 of file jointstochasticprocess.cpp.
References l_.
{
        return l_;
    }
virtual bool QuantLib::JointStochasticProcess::correlationIsStateDependent () const [pure virtual]
Referenced by evolve().
Disposable< Matrix > QuantLib::JointStochasticProcess::covariance (Time t0, const Array & x0, Time dt) const [virtual]
returns the covariance \(V(\mathrm{x}_{t_0 + \Delta t} | \mathrm{x}_{t_0} = \mathrm{x}_0) \) of the process after a time interval \(\Delta t \) according to the given discretization. This method can be overridden in derived classes which want to hard-code a particular discretization.
Reimplemented from QuantLib::StochasticProcess.
Definition at line 134 of file jointstochasticprocess.cpp.
References crossModelCorrelation(), QuantLib::Matrix::diagonal(), l_, QuantLib::Matrix::row_begin(), QuantLib::Matrix::row_end(), QuantLib::Matrix::rows(), size(), slice(), QuantLib::Sqrt(), QuantLib::io::volatility(), and vsize_.
Referenced by diffusion(), evolve(), and stdDeviation().
{
        // get the model intrinsic covariance matrix
        Matrix retVal(size(), size(), 0.0);
        for (Size j=0; j < l_.size(); ++j) {
            const Size vs = vsize_[j];
            const Matrix& pCov = l_[j]->covariance(t0, slice(x0,j), dt);
            for (Size i=0; i < pCov.rows(); ++i) {
                std::copy(pCov.row_begin(i), pCov.row_end(i),
                          retVal.row_begin(vs+i) + vs);
            }
        }
        // add the cross model covariance matrix
        const Array& volatility = Sqrt(retVal.diagonal());
        Matrix crossModelCovar = this->crossModelCorrelation(t0, x0);
        for (Size i=0; i < size(); ++i) {
            for (Size j=0; j < size(); ++j) {
                crossModelCovar[i][j] *= volatility[i]*volatility[j];
            }
        }
        retVal += crossModelCovar;
        return retVal;
    }
virtual Disposable<Matrix> QuantLib::JointStochasticProcess::crossModelCorrelation (Time t0, const Array & x0) const [pure virtual]
Referenced by covariance().
Disposable< Matrix > QuantLib::JointStochasticProcess::diffusion (Time t, const Array & x) const [virtual]
returns the diffusion part of the equation, i.e. \(\sigma(t, \mathrm{x}_t) \)
Implements QuantLib::StochasticProcess.
Definition at line 126 of file jointstochasticprocess.cpp.
References covariance(), QuantLib::anonymous_namespace{yieldtermstructure.cpp}::dt, and QuantLib::pseudoSqrt().
{
        // might need some improvement in the future
        const Time dt = 0.001;
        return pseudoSqrt(covariance(t, x, dt)/dt);
    }
Disposable< Array > QuantLib::JointStochasticProcess::drift (Time t, const Array & x) const [virtual]
returns the drift part of the equation, i.e., \(\mu(t, \mathrm{x}_t) \)
Implements QuantLib::StochasticProcess.
Definition at line 94 of file jointstochasticprocess.cpp.
References QuantLib::Array::begin(), QuantLib::Array::end(), l_, size(), slice(), and vsize_.
{
        Array retVal(size());
        for (Size i=0; i < l_.size(); ++i) {
            const Array& pDrift = l_[i]->drift(t, slice(x,i));
            std::copy(pDrift.begin(), pDrift.end(),
                      retVal.begin()+vsize_[i]);
        }
        return retVal;
    }
Disposable< Array > QuantLib::JointStochasticProcess::evolve (Time t0, const Array & x0, Time dt, const Array & dw) const [virtual]
returns the asset value after a time interval \(\Delta t \) according to the given discretization. By default, it returns
\[ E(\mathrm{x}_0,t_0,\Delta t) + S(\mathrm{x}_0,t_0,\Delta t) \cdot \Delta \mathrm{w} \]
where \(E \) is the expectation and \(S \) the standard deviation.
Reimplemented from QuantLib::StochasticProcess.
Definition at line 189 of file jointstochasticprocess.cpp.
References QuantLib::Array::begin(), QuantLib::Matrix::columns(), correlationCache_, correlationIsStateDependent(), covariance(), QuantLib::Matrix::diagonal(), factors_, QuantLib::dsd::inner_product(), l_, modelFactors_, postEvolve(), preEvolve(), QL_EPSILON, QuantLib::rankReducedSqrt(), QuantLib::Matrix::row_begin(), QuantLib::Matrix::row_end(), QuantLib::Matrix::rows(), QuantLib::SVD::singularValues(), size(), QuantLib::Array::size(), slice(), QuantLib::SalvagingAlgorithm::Spectral, QuantLib::Sqrt(), QuantLib::transpose(), QuantLib::SVD::U(), QuantLib::SVD::V(), vfactors_, and vsize_.
{
        Array dv(modelFactors_);
        if (   correlationIsStateDependent()
            || correlationCache_.count(CachingKey(t0, dt)) == 0) {
            Matrix cov  = covariance(t0, x0, dt);
            const Array& sqrtDiag = Sqrt(cov.diagonal());
            for (Size i=0; i < cov.rows(); ++i) {
                for (Size j=i; j < cov.columns(); ++j) {
                    const Real div = sqrtDiag[i]*sqrtDiag[j];
                    cov[i][j] = cov[j][i] = ( div > 0) ? cov[i][j]/div : 0.0;
                }
            }
            Matrix diff(size(), modelFactors_, 0.0);
            for (Size j = 0; j < l_.size(); ++j) {
                const Size vs = vsize_   [j];
                const Size vf = vfactors_[j];
                Matrix stdDev = l_[j]->stdDeviation(t0, slice(x0,j), dt);
                for (Size i=0; i < stdDev.rows(); ++i) {
                    const Volatility vol = std::sqrt(
                        std::inner_product(stdDev.row_begin(i),
                                           stdDev.row_end(i),
                                           stdDev.row_begin(i), 0.0));
                    if (vol > 0.0) {
                        std::transform(stdDev.row_begin(i), stdDev.row_end(i),
                                       stdDev.row_begin(i),
                                       std::bind2nd(std::divides<Real>(),
                                                    vol));
                    }
                    else {
                        // keep the svd happy
                        std::fill(stdDev.row_begin(i), stdDev.row_end(i),
                                  100*i*QL_EPSILON);
                    }
                }
                SVD svd(stdDev);
                const Array& s = svd.singularValues();
                Matrix w(s.size(), s.size(), 0.0);
                for (Size i=0; i < s.size(); ++i) {
                    if (std::fabs(s[i]) > std::sqrt(QL_EPSILON)) {
                        w[i][i] = 1.0/s[i];
                    }
                }
                const Matrix inv = svd.U() * w * transpose(svd.V());
                for (Size i=0; i < stdDev.rows(); ++i) {
                    std::copy(inv.row_begin(i), inv.row_end(i),
                              diff.row_begin(i+vs)+vf);
                }
            }
            Matrix rs = rankReducedSqrt(cov, factors_, 1.0,
                                        SalvagingAlgorithm::Spectral);
            if (rs.columns() < factors_) {
                // less eigenvalues than expected factors.
                // fill the rest with zero's.
                Matrix tmp = Matrix(cov.rows(), factors_, 0.0);
                for (Size i=0; i < cov.rows(); ++i) {
                    std::copy(rs.row_begin(i), rs.row_end(i),
                              tmp.row_begin(i));
                }
                rs = tmp;
            }
            const Matrix m = transpose(diff) * rs;
            if (!correlationIsStateDependent()) {
                correlationCache_[CachingKey(t0,dt)] = m;
            }
            dv = m*dw;
        }
        else {
            if (!correlationIsStateDependent()) {
                dv = correlationCache_[CachingKey(t0,dt)] * dw;
            }
        }
        this->preEvolve(t0, x0, dt, dv);
        Array retVal(size());
        for (const_iterator iter = l_.begin(); iter != l_.end(); ++iter) {
            const Size i = iter - l_.begin();
            Array dz((*iter)->factors());
            std::copy(dv.begin()+vfactors_[i],
                      dv.begin()+vfactors_[i] + (*iter)->factors(),
                      dz.begin());
            Array x((*iter)->size());
            std::copy(x0.begin()+vsize_[i],
                      x0.begin()+vsize_[i] + (*iter)->size(),
                      x.begin());
            const Array r = (*iter)->evolve(t0, x, dt, dz);
            std::copy(r.begin(), r.end(), retVal.begin()+vsize_[i]);
        }
        return this->postEvolve(t0, x0, dt, dv, retVal);
    }
Disposable< Array > QuantLib::JointStochasticProcess::expectation (Time t0, const Array & x0, Time dt) const [virtual]
returns the expectation \(E(\mathrm{x}_{t_0 + \Delta t} | \mathrm{x}_{t_0} = \mathrm{x}_0) \) of the process after a time interval \(\Delta t \) according to the given discretization. This method can be overridden in derived classes which want to hard-code a particular discretization.
Reimplemented from QuantLib::StochasticProcess.
Definition at line 109 of file jointstochasticprocess.cpp.
References QuantLib::Array::begin(), QuantLib::Array::end(), l_, size(), slice(), and vsize_.
{
        Array retVal(size());
        for (Size i=0; i < l_.size(); ++i) {
            const Array& pExpectation = l_[i]->expectation(t0, slice(x0,i), dt);
            std::copy(pExpectation.begin(), pExpectation.end(),
                      retVal.begin()+ vsize_[i]);
        }
        return retVal;
    }
Size QuantLib::JointStochasticProcess::factors () const [virtual]
returns the number of independent factors of the process
Reimplemented from QuantLib::StochasticProcess.
Definition at line 67 of file jointstochasticprocess.cpp.
References factors_.
{
        return factors_;
    }
Disposable< Array > QuantLib::JointStochasticProcess::initialValues () const [virtual]
returns the initial values of the state variables
Implements QuantLib::StochasticProcess.
Definition at line 80 of file jointstochasticprocess.cpp.
References QuantLib::Array::begin(), QuantLib::Array::end(), l_, size(), and vsize_.
{
        Array retVal(size());
        for (const_iterator iter = l_.begin(); iter != l_.end(); ++iter) {
            const Array& pInitValues = (*iter)->initialValues();
            std::copy(pInitValues.begin(), pInitValues.end(),
                      retVal.begin()+vsize_[iter - l_.begin()]);
        }
        return retVal;
    }
virtual DiscountFactor QuantLib::JointStochasticProcess::numeraire (Time t, const Array & x) const [pure virtual]
virtual Disposable<Array> QuantLib::JointStochasticProcess::postEvolve (Time t0, const Array & x0, Time dt, const Array & dw, const Array & y0) const [pure virtual]
Referenced by evolve().
virtual void QuantLib::JointStochasticProcess::preEvolve (Time t0, const Array & x0, Time dt, const Array & dw) const [pure virtual]
Referenced by evolve().
Size QuantLib::JointStochasticProcess::size () const [virtual]
returns the number of dimensions of the stochastic process
Implements QuantLib::StochasticProcess.
Definition at line 63 of file jointstochasticprocess.cpp.
References size_.
Referenced by apply(), covariance(), drift(), evolve(), expectation(), and initialValues().
{
        return size_;
    }
Disposable< Array > QuantLib::JointStochasticProcess::slice (const Array & x, Size i) const [protected]
Definition at line 71 of file jointstochasticprocess.cpp.
References QuantLib::Array::begin(), and vsize_.
Referenced by apply(), covariance(), drift(), evolve(), and expectation().
{
        // cut out the ith process' variables
        Size n = vsize_[i+1]-vsize_[i];
        Array y(n);
        std::copy(x.begin()+vsize_[i], x.begin()+vsize_[i+1], y.begin());
        return y;
    }
Disposable< Matrix > QuantLib::JointStochasticProcess::stdDeviation (Time t0, const Array & x0, Time dt) const [virtual]
returns the standard deviation \(S(\mathrm{x}_{t_0 + \Delta t} | \mathrm{x}_{t_0} = \mathrm{x}_0) \) of the process after a time interval \(\Delta t \) according to the given discretization. This method can be overridden in derived classes which want to hard-code a particular discretization.
Reimplemented from QuantLib::StochasticProcess.
Definition at line 168 of file jointstochasticprocess.cpp.
References covariance(), and QuantLib::pseudoSqrt().
{
        return pseudoSqrt(covariance(t0, x0, dt));
    }
Time QuantLib::JointStochasticProcess::time (const Date &) const [virtual]
returns the time value corresponding to the given date in the reference system of the stochastic process.
Note:
As a number of processes might not need this functionality, a default implementation is given which raises an exception.
Reimplemented from QuantLib::StochasticProcess.
Definition at line 303 of file jointstochasticprocess.cpp.
References l_, and QL_REQUIRE.
{
        QL_REQUIRE(l_.size() > 0, "process list is empty");
        return l_[0]->time(date);
    }
void QuantLib::JointStochasticProcess::update () [virtual]
This method must be implemented in derived classes. An instance of Observer does not call this method directly: instead, it will be called by the observables the instance registered with when they need to notify any changes.
Reimplemented from QuantLib::StochasticProcess.
Definition at line 309 of file jointstochasticprocess.cpp.
References correlationCache_.
{
        // clear all caches
        correlationCache_.clear();
        this->StochasticProcess::update();
    }
Member Data Documentation
std::map<CachingKey, Matrix> QuantLib::JointStochasticProcess::correlationCache_ [mutable, private]
Definition at line 100 of file jointstochasticprocess.hpp.
Referenced by evolve(), and update().
Size QuantLib::JointStochasticProcess::factors_ [private]
Definition at line 85 of file jointstochasticprocess.hpp.
Referenced by evolve(), factors(), and JointStochasticProcess().
std::vector<boost::shared_ptr<StochasticProcess> > QuantLib::JointStochasticProcess::l_ [protected]
Definition at line 74 of file jointstochasticprocess.hpp.
Referenced by apply(), constituents(), covariance(), drift(), evolve(), expectation(), initialValues(), JointStochasticProcess(), and time().
Size QuantLib::JointStochasticProcess::modelFactors_ [private]
Definition at line 85 of file jointstochasticprocess.hpp.
Referenced by evolve(), and JointStochasticProcess().
Size QuantLib::JointStochasticProcess::size_ [private]
Definition at line 85 of file jointstochasticprocess.hpp.
Referenced by JointStochasticProcess(), and size().
std::vector<Size> QuantLib::JointStochasticProcess::vfactors_ [private]
Definition at line 86 of file jointstochasticprocess.hpp.
Referenced by evolve(), and JointStochasticProcess().
std::vector<Size> QuantLib::JointStochasticProcess::vsize_ [private]
Definition at line 86 of file jointstochasticprocess.hpp.
Referenced by apply(), covariance(), drift(), evolve(), expectation(), initialValues(), JointStochasticProcess(), and slice().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/processes/jointstochasticprocess.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/processes/jointstochasticprocess.cpp