QuantLib: QuantLib::SMMDriftCalculator Class Reference
QuantLib::SMMDriftCalculator Class Reference
Drift computation for coterminal swap market models.
#include <smmdriftcalculator.hpp>
Public Member Functions
SMMDriftCalculator (const Matrix &pseudo, const std::vector< Spread > &displacements, const std::vector< Time > &taus, Size numeraire, Size alive)
void compute (const CoterminalSwapCurveState &cs, std::vector< Real > &drifts) const
Computes the drifts.
Private Attributes
Size numberOfRates_
Size numberOfFactors_
bool isFullFactor_
Size numeraire_
Size alive_
std::vector< Spread > displacements_
std::vector< Real > oneOverTaus_
Matrix C_
Matrix pseudo_
std::vector< Real > tmp_
Matrix wkaj_
Matrix wkpj_
Matrix wkajshifted_
Detailed Description
Drift computation for coterminal swap market models.
Returns the drift \(\mu \Delta t \). See Mark Joshi, Lorenzo Liesch, Effective Implementation Of Generic Market Models.
Definition at line 40 of file smmdriftcalculator.hpp.
Constructor & Destructor Documentation
QuantLib::SMMDriftCalculator::SMMDriftCalculator (const Matrix & pseudo, const std::vector< Spread > & displacements, const std::vector< Time > & taus, Size numeraire, Size alive)
Definition at line 26 of file smmdriftcalculator.cpp.
References C_, QuantLib::Matrix::columns(), numberOfRates_, numeraire_, oneOverTaus_, pseudo_, QL_REQUIRE, QuantLib::Matrix::rows(), and QuantLib::transpose().
    : numberOfRates_(taus.size()), numberOfFactors_(pseudo.columns()),
      isFullFactor_(numberOfFactors_==numberOfRates_ ? true : false),
      numeraire_(numeraire), alive_(alive),
      displacements_(displacements), oneOverTaus_(taus.size()),
      pseudo_(pseudo),
      tmp_(taus.size(), 0.0),
      // zero initialization required for (used by) the last element
      wkaj_(pseudo_.columns(), pseudo_.rows(), 0.0),
      wkpj_(pseudo_.columns(), pseudo_.rows()+1, 0.0),
      wkajshifted_(pseudo_.columns(), pseudo_.rows(), 0.0)
      /*,
      downs_(taus.size()), ups_(taus.size())*/ {
        // Check requirements
        QL_REQUIRE(numberOfRates_>0, "Dim out of range");
        QL_REQUIRE(displacements.size() == numberOfRates_,
            "Displacements out of range");
        QL_REQUIRE(pseudo.rows()==numberOfRates_,
            "pseudo.rows() not consistent with dim");
        QL_REQUIRE(pseudo.columns()>0 && pseudo.columns()<=numberOfRates_,
            "pseudo.rows() not consistent with pseudo.columns()");
        QL_REQUIRE(alive<numberOfRates_, "Alive out of bounds");
        QL_REQUIRE(numeraire_<=numberOfRates_, "Numeraire larger than dim");
        QL_REQUIRE(numeraire_>=alive, "Numeraire smaller than alive");
        // Precompute 1/taus
        for (Size i=0; i<taus.size(); ++i)
            oneOverTaus_[i] = 1.0/taus[i];
        // Compute covariance matrix from pseudoroot
        const Disposable<Matrix> pT = transpose(pseudo_);
        C_ = pseudo_*pT;
        // Compute lower and upper extrema for (non reduced) drift calculation
        //for (Size i=alive_; i<numberOfRates_; ++i) {
        //    downs_[i] = std::min(i+1, numeraire_);
        //    ups_[i]   = std::max(i+1, numeraire_);
        //}
    }
Member Function Documentation
void QuantLib::SMMDriftCalculator::compute (const CoterminalSwapCurveState & cs, std::vector< Real > & drifts) const
Computes the drifts.
Definition at line 72 of file smmdriftcalculator.cpp.
References alive_, QuantLib::CoterminalSwapCurveState::coterminalSwapAnnuity(), QuantLib::CoterminalSwapCurveState::coterminalSwapRates(), QuantLib::CoterminalSwapCurveState::discountRatio(), displacements_, numberOfFactors_, QuantLib::CurveState::numberOfRates(), numberOfRates_, numeraire_, pseudo_, QL_REQUIRE, QuantLib::CurveState::rateTaus(), wkaj_, wkajshifted_, and wkpj_.
{
        #if defined(QL_EXTRA_SAFETY_CHECKS)
        QL_REQUIRE(drifts.size()==cs.numberOfRates(),
                   "drifts.size() <> numberOfRates");
        #endif
        // Compute drifts with factor reduction,
        // using the pseudo square root of the covariance matrix.
        const std::vector<Rate>& SR=cs.coterminalSwapRates();
        // calculates and stores wkaj_, wkpj1_
        // assuming terminal bond measure
        // eq 5.4-5.7
        const std::vector<Time>& taus=cs.rateTaus();
        for (Size k=0; k<numberOfFactors_; ++k) {
                // taken care in the constructor
                // wkpj1_[k][numberOfRates_-1]= 0.0;
                // wkaj_[k][numberOfRates_-1] = 0.0;
            for (Integer j=numberOfRates_-2; j>=static_cast<Integer>(alive_)-1; --j) {
                 // < W(k) | P(j+1)/P(n) > =
                 // = SR(j+1) a(j+1,k) A(j+1) / P(n) + SR(j+1) < W(k) | A(j+1)/P(n) >
                Real annuity = cs.coterminalSwapAnnuity(numberOfRates_,j+1);
                wkpj_[k][j+1]= SR[j+1] *
                            ( pseudo_[j+1][k] * annuity +  wkaj_[k][j+1] )+
                            pseudo_[j+1][k]*displacements_[j+1]* annuity;
                if (j >=static_cast<Integer>(alive_))
                    wkaj_[k][j] = wkpj_[k][j+1]*taus[j ]+wkaj_[k][j+1];
            }
          }
        double numeraireRatio = cs.discountRatio(numberOfRates_,numeraire_);
// change to work for general numeraire
        for (Size k=0; k<numberOfFactors_; ++k) {
            // compute < Wk, PN/pn>
            for (Size j=alive_; j<numberOfRates_; ++j)
            {
                wkajshifted_[k][j] = -wkaj_[k][j]/cs.coterminalSwapAnnuity(numberOfRates_,j)
                                    + wkpj_[k][numeraire_]
                                                *numeraireRatio;
            }
        }
        // eq 5.3 (in log coordinates)
        for (Size j=alive_; j<numberOfRates_; ++j) {
            drifts[j] = 0.0;
            for (Size k=0; k<numberOfFactors_; ++k) {
                drifts[j] += wkajshifted_[k][j]*pseudo_[j][k];
            }
        }
    }
Member Data Documentation
Size QuantLib::SMMDriftCalculator::alive_ [private]
Definition at line 53 of file smmdriftcalculator.hpp.
Referenced by compute().
Matrix QuantLib::SMMDriftCalculator::C_ [private]
Definition at line 56 of file smmdriftcalculator.hpp.
Referenced by SMMDriftCalculator().
std::vector<Spread> QuantLib::SMMDriftCalculator::displacements_ [private]
Definition at line 54 of file smmdriftcalculator.hpp.
Referenced by compute().
bool QuantLib::SMMDriftCalculator::isFullFactor_ [private]
Definition at line 52 of file smmdriftcalculator.hpp.
Size QuantLib::SMMDriftCalculator::numberOfFactors_ [private]
Definition at line 51 of file smmdriftcalculator.hpp.
Referenced by compute().
Size QuantLib::SMMDriftCalculator::numberOfRates_ [private]
Definition at line 51 of file smmdriftcalculator.hpp.
Referenced by compute(), and SMMDriftCalculator().
Size QuantLib::SMMDriftCalculator::numeraire_ [private]
Definition at line 53 of file smmdriftcalculator.hpp.
Referenced by compute(), and SMMDriftCalculator().
std::vector<Real> QuantLib::SMMDriftCalculator::oneOverTaus_ [private]
Definition at line 55 of file smmdriftcalculator.hpp.
Referenced by SMMDriftCalculator().
Matrix QuantLib::SMMDriftCalculator::pseudo_ [private]
Definition at line 56 of file smmdriftcalculator.hpp.
Referenced by compute(), and SMMDriftCalculator().
std::vector<Real> QuantLib::SMMDriftCalculator::tmp_ [mutable, private]
Definition at line 58 of file smmdriftcalculator.hpp.
Matrix QuantLib::SMMDriftCalculator::wkaj_ [mutable, private]
Definition at line 59 of file smmdriftcalculator.hpp.
Referenced by compute().
Matrix QuantLib::SMMDriftCalculator::wkajshifted_ [mutable, private]
Definition at line 61 of file smmdriftcalculator.hpp.
Referenced by compute().
Matrix QuantLib::SMMDriftCalculator::wkpj_ [mutable, private]
Definition at line 60 of file smmdriftcalculator.hpp.
Referenced by compute().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/driftcomputation/smmdriftcalculator.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/driftcomputation/smmdriftcalculator.cpp