QuantLib: QuantLib::CPICouponPricer Class Reference
QuantLib::CPICouponPricer Class Reference
base pricer for capped/floored CPI coupons N.B. vol-dependent parts are a TODO
#include <cpicouponpricer.hpp>
Public Member Functions
CPICouponPricer (const Handle< CPIVolatilitySurface > &capletVol=Handle< CPIVolatilitySurface >())
virtual Handle
< CPIVolatilitySurface > capletVolatility () const
virtual void setCapletVolatility (const Handle< CPIVolatilitySurface > &capletVol)
InflationCouponPricer interface
virtual Real swapletPrice () const
virtual Rate swapletRate () const
virtual Real capletPrice (Rate effectiveCap) const
virtual Rate capletRate (Rate effectiveCap) const
virtual Real floorletPrice (Rate effectiveFloor) const
virtual Rate floorletRate (Rate effectiveFloor) const
virtual void initialize (const InflationCoupon &)
Protected Member Functions
virtual Real optionletPrice (Option::Type optionType, Real effStrike) const
can replace this if really required
virtual Real optionletPriceImp (Option::Type, Real strike, Real forward, Real stdDev) const
virtual Rate adjustedFixing (Rate fixing=Null< Rate >()) const
Protected Attributes
Handle< CPIVolatilitySurface > capletVol_
data
const CPICoupon * coupon_
Real gearing_
Spread spread_
Real discount_
Real spreadLegValue_
Detailed Description
base pricer for capped/floored CPI coupons N.B. vol-dependent parts are a TODO
Note:
this pricer can already do swaplets but to get volatility-dependent coupons you need to implement the descendents.
Definition at line 39 of file cpicouponpricer.hpp.
Constructor & Destructor Documentation
QuantLib::CPICouponPricer::CPICouponPricer (const Handle< CPIVolatilitySurface > & capletVol = Handle<CPIVolatilitySurface>())
Definition at line 25 of file cpicouponpricer.cpp.
References capletVol_, QuantLib::Handle< T >::empty(), and QuantLib::Observer::registerWith().
    : capletVol_(capletVol) {
        if( !capletVol_.empty() ) registerWith(capletVol_);
    }
Member Function Documentation
Rate QuantLib::CPICouponPricer::adjustedFixing (Rate fixing = Null<Rate>()) const [protected, virtual]
Definition at line 101 of file cpicouponpricer.cpp.
References QuantLib::CPICoupon::baseCPI(), coupon_, and QuantLib::CPICoupon::indexFixing().
Referenced by optionletPrice(), swapletPrice(), and swapletRate().
{
        if (fixing == Null<Rate>())
            fixing = coupon_->indexFixing() / coupon_->baseCPI();
        //std::cout << " adjustedFixing " << fixing << std::endl;
        // no adjustment
        return fixing;
    }
Real QuantLib::CPICouponPricer::capletPrice (Rate effectiveCap) const [virtual]
Implements QuantLib::InflationCouponPricer.
Definition at line 45 of file cpicouponpricer.cpp.
References QuantLib::Option::Call, gearing_, and optionletPrice().
Referenced by capletRate().
{
        Real capletPrice = optionletPrice(Option::Call, effectiveCap);
        return gearing_ * capletPrice;
    }
Rate QuantLib::CPICouponPricer::capletRate (Rate effectiveCap) const [virtual]
Implements QuantLib::InflationCouponPricer.
Definition at line 56 of file cpicouponpricer.cpp.
References QuantLib::Coupon::accrualPeriod(), capletPrice(), coupon_, and discount_.
{
        return capletPrice(effectiveCap)/(coupon_->accrualPeriod()*discount_);
    }
virtual Handle<CPIVolatilitySurface> QuantLib::CPICouponPricer::capletVolatility () const [inline, virtual]
Definition at line 44 of file cpicouponpricer.hpp.
References capletVol_.
Referenced by optionletPrice().
{
            return capletVol_;
        }
Real QuantLib::CPICouponPricer::floorletPrice (Rate effectiveFloor) const [virtual]
Implements QuantLib::InflationCouponPricer.
Definition at line 40 of file cpicouponpricer.cpp.
References gearing_, optionletPrice(), and QuantLib::Option::Put.
Referenced by floorletRate().
{
        Real floorletPrice = optionletPrice(Option::Put, effectiveFloor);
        return gearing_ * floorletPrice;
    }
Rate QuantLib::CPICouponPricer::floorletRate (Rate effectiveFloor) const [virtual]
Implements QuantLib::InflationCouponPricer.
Definition at line 51 of file cpicouponpricer.cpp.
References QuantLib::Coupon::accrualPeriod(), coupon_, discount_, and floorletPrice().
{
        return floorletPrice(effectiveFloor)/
        (coupon_->accrualPeriod()*discount_);
    }
void QuantLib::CPICouponPricer::initialize (const InflationCoupon & coupon) [virtual]
Implements QuantLib::InflationCouponPricer.
Definition at line 111 of file cpicouponpricer.cpp.
References QuantLib::Coupon::accrualPeriod(), coupon_, QuantLib::Coupon::date(), discount_, QuantLib::CPICoupon::fixedRate(), gearing_, QuantLib::InflationCoupon::index(), QuantLib::InflationCouponPricer::paymentDate_, QuantLib::InflationCouponPricer::rateCurve_, QuantLib::CPICoupon::spread(), spread_, and spreadLegValue_.
{
        coupon_ = dynamic_cast<const CPICoupon*>(&coupon);
        gearing_ = coupon_->fixedRate();
        spread_ = coupon_->spread();
        paymentDate_ = coupon_->date();
        rateCurve_ = boost::dynamic_pointer_cast<ZeroInflationIndex>(coupon.index())
            ->zeroInflationTermStructure()
            ->nominalTermStructure();
        // past or future fixing is managed in YoYInflationIndex::fixing()
        // use yield curve from index (which sets discount)
        discount_ = 1.0;
        if (paymentDate_ > rateCurve_->referenceDate())
            discount_ = rateCurve_->discount(paymentDate_);
        spreadLegValue_ = spread_ * coupon_->accrualPeriod()* discount_;
    }
Real QuantLib::CPICouponPricer::optionletPrice (Option::Type optionType, Real effStrike) const [protected, virtual]
can replace this if really required
Definition at line 71 of file cpicouponpricer.cpp.
References anonymous_namespace{marketmodel.cpp}::a, QuantLib::Coupon::accrualPeriod(), adjustedFixing(), anonymous_namespace{marketmodel.cpp}::b, QuantLib::Option::Call, capletVolatility(), coupon_, discount_, QuantLib::InflationCoupon::fixingDate(), QuantLib::CPICoupon::indexFixing(), QuantLib::Singleton< Settings >::instance(), optionletPriceImp(), and QL_REQUIRE.
Referenced by capletPrice(), and floorletPrice().
{
        Date fixingDate = coupon_->fixingDate();
        if (fixingDate <= Settings::instance().evaluationDate()) {
            // the amount is determined
            Real a, b;
            if (optionType==Option::Call) {
                a = coupon_->indexFixing();
                b = effStrike;
            } else {
                a = effStrike;
                b = coupon_->indexFixing();
            }
            return std::max(a - b, 0.0)* coupon_->accrualPeriod()*discount_;
        } else {
            // not yet determined, use Black/DD1/Bachelier/whatever from Impl
            QL_REQUIRE(!capletVolatility().empty(),
                       "missing optionlet volatility");
            Real stdDev =
            std::sqrt(capletVolatility()->totalVariance(fixingDate,
                                                        effStrike));
            Rate fixing = optionletPriceImp(optionType,
                                            effStrike,
                                            adjustedFixing(),
                                            stdDev);
            return fixing * coupon_->accrualPeriod() * discount_;
        }
    }
Real QuantLib::CPICouponPricer::optionletPriceImp (Option::Type optionType, Real strike, Real forward, Real stdDev) const [protected, virtual]
usually only need implement this (of course they may need to re-implement initialize too ...)
Definition at line 61 of file cpicouponpricer.cpp.
References QL_FAIL.
Referenced by optionletPrice().
{
        QL_FAIL("you must implement this to get a vol-dependent price");
        return effStrike*forward*stdDev*optionType;
    }
void QuantLib::CPICouponPricer::setCapletVolatility (const Handle< CPIVolatilitySurface > & capletVol) [virtual]
Definition at line 32 of file cpicouponpricer.cpp.
References capletVol_, QuantLib::Handle< T >::empty(), QL_REQUIRE, and QuantLib::Observer::registerWith().
{
        QL_REQUIRE(!capletVol.empty(),"empty capletVol handle")
        capletVol_ = capletVol;
        registerWith(capletVol_);
    }
Real QuantLib::CPICouponPricer::swapletPrice () const [virtual]
Implements QuantLib::InflationCouponPricer.
Definition at line 132 of file cpicouponpricer.cpp.
References QuantLib::Coupon::accrualPeriod(), adjustedFixing(), coupon_, discount_, gearing_, and spreadLegValue_.
{
        Real swapletPrice = adjustedFixing() * coupon_->accrualPeriod() * discount_;
        //std::cout << swapletPrice << " SWAPLET price" << std::endl;
        return gearing_ * swapletPrice + spreadLegValue_;
    }
Rate QuantLib::CPICouponPricer::swapletRate () const [virtual]
Implements QuantLib::InflationCouponPricer.
Definition at line 140 of file cpicouponpricer.cpp.
References adjustedFixing(), gearing_, and spread_.
{
        // This way we do not require the index to have
        // a yield curve, i.e. we do not get the problem
        // that a discounting-instrument-pricer is used
        // with a different yield curve
        //std::cout << (gearing_ * adjustedFixing() + spread_) << " SWAPLET rate" << gearing_ << " " << spread_ << std::endl;
        return gearing_ * adjustedFixing() + spread_;
    }
Member Data Documentation
Handle<CPIVolatilitySurface> QuantLib::CPICouponPricer::capletVol_ [protected]
data
Definition at line 76 of file cpicouponpricer.hpp.
Referenced by capletVolatility(), CPICouponPricer(), and setCapletVolatility().
const CPICoupon* QuantLib::CPICouponPricer::coupon_ [protected]
Definition at line 77 of file cpicouponpricer.hpp.
Referenced by adjustedFixing(), capletRate(), floorletRate(), initialize(), optionletPrice(), and swapletPrice().
Real QuantLib::CPICouponPricer::discount_ [protected]
Definition at line 80 of file cpicouponpricer.hpp.
Referenced by capletRate(), floorletRate(), initialize(), optionletPrice(), and swapletPrice().
Real QuantLib::CPICouponPricer::gearing_ [protected]
Definition at line 78 of file cpicouponpricer.hpp.
Referenced by capletPrice(), floorletPrice(), initialize(), swapletPrice(), and swapletRate().
Spread QuantLib::CPICouponPricer::spread_ [protected]
Definition at line 79 of file cpicouponpricer.hpp.
Referenced by initialize(), and swapletRate().
Real QuantLib::CPICouponPricer::spreadLegValue_ [protected]
Definition at line 81 of file cpicouponpricer.hpp.
Referenced by initialize(), and swapletPrice().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/cpicouponpricer.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/cpicouponpricer.cpp