QuantLib: QuantLib::BermudanSwaptionExerciseValue Class Reference
QuantLib::BermudanSwaptionExerciseValue Class Reference
#include <bermudanswaptionexercisevalue.hpp>
Public Member Functions
BermudanSwaptionExerciseValue (const std::vector< Time > &rateTimes, const std::vector< boost::shared_ptr< Payoff > > &)
Size numberOfExercises () const
const EvolutionDescription & evolution () const
std::vector< Time > possibleCashFlowTimes () const
void nextStep (const CurveState &)
void reset ()
std::valarray< bool > isExerciseTime () const
MarketModelMultiProduct::CashFlow value (const CurveState &) const
std::auto_ptr
< MarketModelExerciseValue > clone () const
Private Attributes
Size numberOfExercises_
std::vector< Time > rateTimes_
std::vector< boost::shared_ptr
< Payoff > > payoffs_
EvolutionDescription evolution_
Size currentIndex_
MarketModelMultiProduct::CashFlow cf_
Detailed Description
Definition at line 33 of file bermudanswaptionexercisevalue.hpp.
Constructor & Destructor Documentation
QuantLib::BermudanSwaptionExerciseValue::BermudanSwaptionExerciseValue (const std::vector< Time > & rateTimes, const std::vector< boost::shared_ptr< Payoff > > & payoffs)
Definition at line 27 of file bermudanswaptionexercisevalue.cpp.
References QuantLib::checkIncreasingTimes(), evolution_, numberOfExercises_, QL_REQUIRE, and rateTimes_.
Referenced by clone().
    : numberOfExercises_(rateTimes.empty() ? 0 : rateTimes.size()-1),
      rateTimes_(rateTimes),
      payoffs_(payoffs), currentIndex_(0) {
        checkIncreasingTimes(rateTimes);
        QL_REQUIRE(numberOfExercises_>0,
                   "Rate times must contain at least two values");
        std::vector<Time> evolveTimes(rateTimes_);
        evolveTimes.pop_back();
        evolution_ = EvolutionDescription(rateTimes_,evolveTimes);
    }
Member Function Documentation
std::auto_ptr< MarketModelExerciseValue > QuantLib::BermudanSwaptionExerciseValue::clone () const [virtual]
Implements QuantLib::MarketModelExerciseValue.
Definition at line 83 of file bermudanswaptionexercisevalue.cpp.
References BermudanSwaptionExerciseValue().
{
        return std::auto_ptr<MarketModelExerciseValue>(
                                    new BermudanSwaptionExerciseValue(*this));
    }
const EvolutionDescription & QuantLib::BermudanSwaptionExerciseValue::evolution () const [virtual]
Implements QuantLib::MarketModelExerciseValue.
Definition at line 47 of file bermudanswaptionexercisevalue.cpp.
References evolution_.
{
        return evolution_;
    }
std::valarray< bool > QuantLib::BermudanSwaptionExerciseValue::isExerciseTime () const [virtual]
Implements QuantLib::MarketModelExerciseValue.
Definition at line 73 of file bermudanswaptionexercisevalue.cpp.
References numberOfExercises_.
{
        return std::valarray<bool>(true,numberOfExercises_);
    }
void QuantLib::BermudanSwaptionExerciseValue::nextStep (const CurveState & state) [virtual]
Implements QuantLib::MarketModelExerciseValue.
Definition at line 60 of file bermudanswaptionexercisevalue.cpp.
References QuantLib::MarketModelMultiProduct::CashFlow::amount, cf_, QuantLib::CurveState::coterminalSwapAnnuity(), QuantLib::CurveState::coterminalSwapRate(), currentIndex_, payoffs_, QuantLib::MarketModelMultiProduct::CashFlow::timeIndex, and value().
{
        const Payoff& p = (*payoffs_[currentIndex_]);
        Real value = state.coterminalSwapAnnuity(currentIndex_, currentIndex_) *
            p(state.coterminalSwapRate(currentIndex_));
     //   value /= state.discountRatios()[currentIndex_];
        value =  std::max(value, 0.0);
        cf_.timeIndex = currentIndex_;
        cf_.amount = value;
        ++currentIndex_;
    }
Size QuantLib::BermudanSwaptionExerciseValue::numberOfExercises () const [virtual]
Implements QuantLib::MarketModelExerciseValue.
Definition at line 42 of file bermudanswaptionexercisevalue.cpp.
References numberOfExercises_.
{
        return numberOfExercises_;
    }
std::vector< Time > QuantLib::BermudanSwaptionExerciseValue::possibleCashFlowTimes () const [virtual]
Implements QuantLib::MarketModelExerciseValue.
Definition at line 52 of file bermudanswaptionexercisevalue.cpp.
References rateTimes_.
{
        return rateTimes_;
    }
void QuantLib::BermudanSwaptionExerciseValue::reset () [virtual]
Implements QuantLib::MarketModelExerciseValue.
Definition at line 56 of file bermudanswaptionexercisevalue.cpp.
References currentIndex_.
{
        currentIndex_=0;
    }
MarketModelMultiProduct::CashFlow QuantLib::BermudanSwaptionExerciseValue::value (const CurveState &) const [virtual]
Implements QuantLib::MarketModelExerciseValue.
Definition at line 78 of file bermudanswaptionexercisevalue.cpp.
References cf_.
Referenced by nextStep().
{
         return cf_;
    }
Member Data Documentation
MarketModelMultiProduct::CashFlow QuantLib::BermudanSwaptionExerciseValue::cf_ [private]
Definition at line 54 of file bermudanswaptionexercisevalue.hpp.
Referenced by nextStep(), and value().
Size QuantLib::BermudanSwaptionExerciseValue::currentIndex_ [private]
Definition at line 53 of file bermudanswaptionexercisevalue.hpp.
Referenced by nextStep(), and reset().
EvolutionDescription QuantLib::BermudanSwaptionExerciseValue::evolution_ [private]
Definition at line 51 of file bermudanswaptionexercisevalue.hpp.
Referenced by BermudanSwaptionExerciseValue(), and evolution().
Size QuantLib::BermudanSwaptionExerciseValue::numberOfExercises_ [private]
Definition at line 48 of file bermudanswaptionexercisevalue.hpp.
Referenced by BermudanSwaptionExerciseValue(), isExerciseTime(), and numberOfExercises().
std::vector<boost::shared_ptr<Payoff> > QuantLib::BermudanSwaptionExerciseValue::payoffs_ [private]
Definition at line 50 of file bermudanswaptionexercisevalue.hpp.
Referenced by nextStep().
std::vector<Time> QuantLib::BermudanSwaptionExerciseValue::rateTimes_ [private]
Definition at line 49 of file bermudanswaptionexercisevalue.hpp.
Referenced by BermudanSwaptionExerciseValue(), and possibleCashFlowTimes().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/callability/bermudanswaptionexercisevalue.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/callability/bermudanswaptionexercisevalue.cpp