QuantLib: OptimizersTest Class Reference
OptimizersTest Class Reference
#include <optimizers.hpp>
Static Public Member Functions
static void test ()
static void nestedOptimizationTest ()
static
boost::unit_test_framework::test_suite * suite ()
Detailed Description
Definition at line 27 of file optimizers.hpp.
Member Function Documentation
void OptimizersTest::nestedOptimizationTest () [static]
Definition at line 323 of file optimizers.cpp.
References QuantLib::LevenbergMarquardt::minimize().
Referenced by suite().
{
    BOOST_MESSAGE("Testing nested optimizations...");
    OptimizationBasedCostFunction optimizationBasedCostFunction;
    NoConstraint constraint;
    Array initialValues(1, 0.0);
    Problem problem(optimizationBasedCostFunction, constraint,
                    initialValues);
    LevenbergMarquardt optimizationMethod;
    //Simplex optimizationMethod(0.1);
    //ConjugateGradient optimizationMethod;
    //SteepestDescent optimizationMethod;
    EndCriteria endCriteria(1000, 100, 1e-5, 1e-5, 1e-5);
    optimizationMethod.minimize(problem, endCriteria);
}
test_suite * OptimizersTest::suite () [static]
Definition at line 339 of file optimizers.cpp.
References nestedOptimizationTest(), QUANTLIB_TEST_CASE, and test().
Referenced by init_unit_test_suite().
{
    test_suite* suite = BOOST_TEST_SUITE("Optimizers tests");
    suite->add(QUANTLIB_TEST_CASE(&OptimizersTest::test));
    suite->add(QUANTLIB_TEST_CASE(&OptimizersTest::nestedOptimizationTest));
    return suite;
}
void OptimizersTest::test () [static]
Definition at line 242 of file optimizers.cpp.
References anonymous_namespace{optimizers.cpp}::constraints_, anonymous_namespace{optimizers.cpp}::costFunctions_, QuantLib::Problem::currentValue(), anonymous_namespace{optimizers.cpp}::endCriterias_, QuantLib::EndCriteria::functionEpsilon(), QuantLib::Problem::functionEvaluation(), QuantLib::Problem::gradientEvaluation(), anonymous_namespace{optimizers.cpp}::initialValues_, anonymous_namespace{optimizers.cpp}::maxDifference(), QuantLib::EndCriteria::MaxIterations, QuantLib::EndCriteria::None, anonymous_namespace{optimizers.cpp}::optimizationMethods_, QuantLib::EndCriteria::rootEpsilon(), QuantLib::Problem::setCurrentValue(), anonymous_namespace{inflationvolatility.cpp}::setup(), QuantLib::EndCriteria::Unknown, QuantLib::Problem::values(), anonymous_namespace{optimizers.cpp}::xMinExpected_, and anonymous_namespace{optimizers.cpp}::yMinExpected_.
Referenced by suite().
{
    BOOST_MESSAGE("Testing optimizers...");
    setup();
    // Loop over problems (currently there is only 1 problem)
    for (Size i=0; i<costFunctions_.size(); ++i) {
        Problem problem(*costFunctions_[i], *constraints_[i],
                        initialValues_[i]);
        Array initialValues = problem.currentValue();
        // Loop over optimizers
        for (Size j=0; j<(optimizationMethods_[i]).size(); ++j) {
            Real rootEpsilon = endCriterias_[i]->rootEpsilon();
            Size endCriteriaTests = 1;
           // Loop over rootEpsilon
            for (Size k=0; k<endCriteriaTests; ++k) {
                problem.setCurrentValue(initialValues);
                EndCriteria endCriteria(
                            endCriterias_[i]->maxIterations(),
                            endCriterias_[i]->maxStationaryStateIterations(),
                            rootEpsilon,
                            endCriterias_[i]->functionEpsilon(),
                            endCriterias_[i]->gradientNormEpsilon());
                rootEpsilon *= .1;
                EndCriteria::Type endCriteriaResult =
                    optimizationMethods_[i][j].optimizationMethod->minimize(
                    problem, endCriteria);
                Array xMinCalculated = problem.currentValue();
                Array yMinCalculated = problem.values(xMinCalculated);
                // Check optimization results vs known solution
                bool completed;
                switch (endCriteriaResult) {
                  case EndCriteria::None:
                  case EndCriteria::MaxIterations:
                  case EndCriteria::Unknown:
                    completed = false;
                  default:
                    completed = true;
                }
                Real xError = maxDifference(xMinCalculated,xMinExpected_[i]);
                Real yError = maxDifference(yMinCalculated,yMinExpected_[i]);
                bool correct = (xError <= endCriteria.rootEpsilon() ||
                                yError <= endCriteria.functionEpsilon());
                if ((!completed) || (!correct))
                    BOOST_ERROR("costFunction # = " << i <<
                                "\nOptimizer: " <<
                                optimizationMethods_[i][j].name <<
                                "\n    function evaluations: " <<
                                problem.functionEvaluation()  <<
                                "\n    gradient evaluations: " <<
                                problem.gradientEvaluation() <<
                                "\n    x expected:           " <<
                                xMinExpected_[i] <<
                                "\n    x calculated:         " <<
                                std::setprecision(9) << xMinCalculated <<
                                "\n    x difference:         " <<
                                xMinExpected_[i]- xMinCalculated <<
                                "\n    rootEpsilon:          " <<
                                std::setprecision(9) <<
                                endCriteria.rootEpsilon() <<
                                "\n    y expected:           " <<
                                yMinExpected_[i] <<
                                "\n    y calculated:         " <<
                                std::setprecision(9) << yMinCalculated <<
                                "\n    y difference:         " <<
                                yMinExpected_[i]- yMinCalculated <<
                                "\n    functionEpsilon:      " <<
                                std::setprecision(9) <<
                                endCriteria.functionEpsilon() <<
                                "\n    endCriteriaResult:    " <<
                                endCriteriaResult);
            }
        }
    }
}
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/optimizers.hpp
/home/deriversatile/QuantLib/QuantLibQt/test-suite/optimizers.cpp