QuantLib: QuantLib::LfmHullWhiteParameterization Class Reference
QuantLib::LfmHullWhiteParameterization Class Reference
Libor market model parameterization based on Hull White paper
#include <lfmhullwhiteparam.hpp>
Public Member Functions
LfmHullWhiteParameterization (const boost::shared_ptr< LiborForwardModelProcess > &process, const boost::shared_ptr< OptionletVolatilityStructure > &capletVol, const Matrix &correlation=Matrix(), Size factors=1)
Disposable< Matrix > diffusion (Time t, const Array &x=Null< Array >()) const
Disposable< Matrix > covariance (Time t, const Array &x=Null< Array >()) const
Disposable< Matrix > integratedCovariance (Time t, const Array &x=Null< Array >()) const
Protected Member Functions
Size nextIndexReset (Time t) const
Protected Attributes
Matrix diffusion_
Matrix covariance_
std::vector< Time > fixingTimes_
Detailed Description
Libor market model parameterization based on Hull White paper
Hull, John, White, Alan, 1999, Forward Rate Volatilities, Swap Rate Volatilities and the Implementation of the Libor Market Model (<http://www.rotman.utoronto.ca/~amackay/fin/libormktmodel2.pdf>)
Test:
the correctness is tested by Monte-Carlo reproduction of caplet & ratchet npvs and comparison with Black pricing.
Definition at line 41 of file lfmhullwhiteparam.hpp.
Constructor & Destructor Documentation
QuantLib::LfmHullWhiteParameterization::LfmHullWhiteParameterization (const boost::shared_ptr< LiborForwardModelProcess > & process, const boost::shared_ptr< OptionletVolatilityStructure > & capletVol, const Matrix & correlation = Matrix(), Size factors = 1)
Definition at line 25 of file lfmhullwhiteparam.cpp.
References QuantLib::Matrix::columns(), covariance_, anonymous_namespace{marketmodel.cpp}::dayCounter, diffusion_, QuantLib::Matrix::empty(), QuantLib::LfmCovarianceParameterization::factors_, QuantLib::dsd::inner_product(), QuantLib::pseudoSqrt(), QL_REQUIRE, QuantLib::Matrix::rows(), QuantLib::LfmCovarianceParameterization::size_, QuantLib::SalvagingAlgorithm::Spectral, and QuantLib::transpose().
    : LfmCovarianceParameterization(process->size(), factors),
      diffusion_  (size_-1, factors_),
      fixingTimes_(process->fixingTimes()) {
        Matrix sqrtCorr(size_-1, factors_, 1.0);
        if (correlation.empty()) {
            QL_REQUIRE(factors_ == 1,
                       "correlation matrix must be given for "
                       "multi factor models");
        } else {
            QL_REQUIRE(   correlation.rows() == size_-1
                       && correlation.rows() == correlation.columns(),
                       "wrong dimesion of the correlation matrix");
            QL_REQUIRE(factors_ <= size_-1,
                       "too many factors for given LFM process");
            Matrix tmpSqrtCorr = pseudoSqrt(correlation,
                                            SalvagingAlgorithm::Spectral);
            // reduce to n factor model
            // "Reconstructing a valid correlation matrix from invalid data"
            // (<http://www.quarchome.org/correlationmatrix.pdf>)
            for (Size i=0; i < size_-1; ++i) {
                std::transform(
                    tmpSqrtCorr[i], tmpSqrtCorr[i]+factors_, sqrtCorr[i],
                    std::bind2nd(std::divides<Real>(),
                                 std::sqrt(std::inner_product(
                                     tmpSqrtCorr[i],tmpSqrtCorr[i]+factors_,
                                     tmpSqrtCorr[i], 0.0))));
            }
        }
        std::vector<Volatility> lambda;
        const DayCounter dayCounter = process->index()->dayCounter();
        const std::vector<Time> fixingTimes = process->fixingTimes();
        const std::vector<Date> fixingDates = process->fixingDates();
        for (Size i = 1; i < size_; ++i) {
            double cumVar = 0.0;
            for (Size j = 1; j < i; ++j) {
                cumVar +=  lambda[i-j-1] * lambda[i-j-1]
                         * (fixingTimes[j+1] - fixingTimes[j]);
            }
            const Volatility vol =  capletVol->volatility(fixingDates[i], 0.0);
            const Volatility var = vol * vol
                * capletVol->dayCounter().yearFraction(fixingDates[0],
                                                       fixingDates[i]);
            lambda.push_back(std::sqrt(  (var - cumVar)
                                       / (fixingTimes[1] - fixingTimes[0])) );
            for (Size q=0; q<factors_; ++q) {
                diffusion_[i-1][q] = sqrtCorr[i-1][q] * lambda.back();
            }
        }
        covariance_ = diffusion_ * transpose(diffusion_);
    }
Member Function Documentation
Disposable< Matrix > QuantLib::LfmHullWhiteParameterization::covariance (Time t, const Array & x = Null<Array>()) const [virtual]
Reimplemented from QuantLib::LfmCovarianceParameterization.
Definition at line 110 of file lfmhullwhiteparam.cpp.
References covariance_, nextIndexReset(), and QuantLib::LfmCovarianceParameterization::size_.
Referenced by LiborMarketModelTest::testCapletPricing().
{
        Matrix tmp(size_, size_, 0.0);
        const Size m = nextIndexReset(t);
        for (Size k=m; k<size_; ++k) {
            for (Size i=m; i<size_; ++i) {
                tmp[k][i] = covariance_[k-m][i-m];
            }
        }
        return tmp;
    }
Disposable< Matrix > QuantLib::LfmHullWhiteParameterization::diffusion (Time t, const Array & x = Null<Array>()) const [virtual]
Implements QuantLib::LfmCovarianceParameterization.
Definition at line 97 of file lfmhullwhiteparam.cpp.
References diffusion_, QuantLib::LfmCovarianceParameterization::factors_, nextIndexReset(), and QuantLib::LfmCovarianceParameterization::size_.
{
        Matrix tmp(size_, factors_, 0.0);
        const Size m = nextIndexReset(t);
        for (Size k=m; k<size_; ++k) {
            for (Size q=0; q<factors_; ++q) {
                tmp[k][q] = diffusion_[k-m][q];
            }
        }
        return tmp;
    }
Disposable< Matrix > QuantLib::LfmHullWhiteParameterization::integratedCovariance (Time t, const Array & x = Null<Array>()) const [virtual]
Reimplemented from QuantLib::LfmCovarianceParameterization.
Definition at line 124 of file lfmhullwhiteparam.cpp.
References covariance_, QuantLib::anonymous_namespace{yieldtermstructure.cpp}::dt, fixingTimes_, QuantLib::LfmCovarianceParameterization::size_, and anonymous_namespace{quantlibbenchmark.cpp}::t.
{
        Matrix tmp(size_, size_, 0.0);
        Size last = std::lower_bound(fixingTimes_.begin(),
                                        fixingTimes_.end(), t)
                      - fixingTimes_.begin();
        for (Size i=0; i<last; ++i) {
            const Time dt = ((i+1<last)? fixingTimes_[i+1] : t )
                - fixingTimes_[i];
            for (Size k=i; k<size_-1; ++k) {
                for (Size l=i; l<size_-1; ++l) {
                    tmp[k+1][l+1]+= covariance_[k-i][l-i]*dt;
                }
            }
        }
        return tmp;
    }
Size QuantLib::LfmHullWhiteParameterization::nextIndexReset (Time t) const [protected]
Definition at line 91 of file lfmhullwhiteparam.cpp.
References fixingTimes_, and anonymous_namespace{quantlibbenchmark.cpp}::t.
Referenced by covariance(), and diffusion().
{
        return std::upper_bound(fixingTimes_.begin(), fixingTimes_.end(), t)
                 - fixingTimes_.begin();
    }
Member Data Documentation
Matrix QuantLib::LfmHullWhiteParameterization::covariance_ [protected]
Definition at line 58 of file lfmhullwhiteparam.hpp.
Referenced by covariance(), integratedCovariance(), and LfmHullWhiteParameterization().
Matrix QuantLib::LfmHullWhiteParameterization::diffusion_ [protected]
Definition at line 58 of file lfmhullwhiteparam.hpp.
Referenced by diffusion(), and LfmHullWhiteParameterization().
std::vector<Time> QuantLib::LfmHullWhiteParameterization::fixingTimes_ [protected]
Definition at line 59 of file lfmhullwhiteparam.hpp.
Referenced by integratedCovariance(), and nextIndexReset().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/legacy/libormarketmodels/lfmhullwhiteparam.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/legacy/libormarketmodels/lfmhullwhiteparam.cpp