QuantLib: QuantLib::RecursiveCdoEngine< CDOEngine, copulaT > Class Template Reference
QuantLib::RecursiveCdoEngine< CDOEngine, copulaT > Class Template Reference
#include <recursivecdoengine.hpp>
Public Member Functions
RecursiveCdoEngine (const Handle< Quote > &correl, Size nbuckets=1, Size quadOrder=20)
Single correlation construction.
RecursiveCdoEngine (const Handle< Quote > &correl, const Matrix &correlMtrx, Size nbuckets=1, Size quadOrder=20)
Correlation name to name single factor construction.
void update ()
Real expectedTrancheLoss (const Date &date) const
Protected Member Functions
void initialize () const
Protected Attributes
const Handle< Quote > correlQuote_
RelinkableHandle< copulaT > copula_
Private Member Functions
Real integratorLoss (const Date &date, Real mktFactor) const
Weights the conditional portfolio loss by the mkt factor.
Real expectedConditionalLoss (const Date &date, Real mktFactor) const
Portfolio loss conditional to the market factor value.
Private Attributes
Size nBuckets_
const GaussHermiteIntegration integral_
std::vector< Real > wk_
Real loss_unit_
std::vector< Real > oneFactorCorrels_
name to name factor loadings (betas). In the single factor copula:
Detailed Description
template<class CDOEngine, class copulaT>
class QuantLib::RecursiveCdoEngine< CDOEngine, copulaT >
Recursive STCDO pricing for a heterogeneous pool of names. The pool names are heterogeneous in their default probabilities, notionals and recovery rates. Correlations are pairwise. The recursive pricing algorithm used here is described in Andersen, Sidenius and Basu; "All your hedges in one basket", Risk, November 2003, pages 67-72
Notice that using copulas other than Gaussian it is only an approximation (see remark on p.68).
Definition at line 45 of file recursivecdoengine.hpp.
Constructor & Destructor Documentation
template<class CDOEngine, class copulaT> QuantLib::RecursiveCdoEngine< CDOEngine, copulaT >::RecursiveCdoEngine (const Handle< Quote > & correl, Size nbuckets = 1, Size quadOrder = 20) [inline]
Single correlation construction.
Definition at line 51 of file recursivecdoengine.hpp.
        : correlQuote_(correl), copula_(), nBuckets_(nbuckets),
          integral_(quadOrder), wk_()
        {
            this->registerWith(correl);
        }
template<class CDOEngine, class copulaT> QuantLib::RecursiveCdoEngine< CDOEngine, copulaT >::RecursiveCdoEngine (const Handle< Quote > & correl, const Matrix & correlMtrx, Size nbuckets = 1, Size quadOrder = 20) [inline]
Correlation name to name single factor construction.
Definition at line 61 of file recursivecdoengine.hpp.
        : correlQuote_(correl), copula_(), nBuckets_(nbuckets),
          integral_(quadOrder), wk_(),
          oneFactorCorrels_(factorReduction(correlMtrx))
        {
            // at least
            QL_REQUIRE(!oneFactorCorrels_.empty(),
                "Invalid correlation parameter matrix.");
        }
Member Function Documentation
template<class CDOEngine , class copulaT > Real QuantLib::RecursiveCdoEngine< CDOEngine, copulaT >::expectedConditionalLoss (const Date & date, Real mktFactor) const [private]
Portfolio loss conditional to the market factor value.
Definition at line 203 of file recursivecdoengine.hpp.
Referenced by QuantLib::RecursiveCdoEngine< CDOEngine, OneFactorStudentCopula >::integratorLoss().
{
        const std::vector<std::string>& names = this->remainingBasket_->names();
        // eq. 10 p.68
        // attainable losses distribution, recursive algorithm
        std::vector<Probability> uncDefProb =
            this->remainingBasket_->probabilities(date);;
        std::map<Real, Probability> pIndepDistrib;
        // K=0
        pIndepDistrib.insert(std::make_pair(0., 1.));
        for(Size iName=0; iName<names.size(); iName++) {
            Real nameLoss = wk_[iName];
            // to do: allow for matrix constructor and uncoment this
            // correlQuote_->setValue(oneFactorCorrels_[iName]);
            Probability pDef =
                copula_->conditionalProbability(uncDefProb[iName],
                                                mktFactor);
            // iterate on all possible losses in the distribution:
            std::map<Real, Probability> pDistTemp;
            std::map<Real, Probability>::iterator distIt =
                pIndepDistrib.begin();
            while(distIt != pIndepDistrib.end()) {
                // update prob if this name does not default
                std::map<Real, Probability>::iterator matchIt
                    = pDistTemp.find(distIt->first);
                if(matchIt != pDistTemp.end()) {
                    matchIt->second += distIt->second * (1.-pDef);
                }else{
                    pDistTemp.insert(std::make_pair(distIt->first,
                        distIt->second * (1.-pDef)));
                }
                // and if it does
                matchIt = pDistTemp.find(distIt->first + wk_[iName]);
                if(matchIt != pDistTemp.end()) {
                    matchIt->second += distIt->second * pDef;
                }else{
                    pDistTemp.insert(std::make_pair(
                        distIt->first+wk_[iName], distIt->second * pDef));
                }
                distIt++;
            }
            // copy back
            pIndepDistrib = pDistTemp;
        }
        // get the expected value subject to the value of the market
        //   factor.
        Real expLoss = 0.;
        //---------------------------------------------------------------
        /* This is the original (easy to read) loop which I have partially
             unroll below to take profit of the fact that once we go over
             the tranche top the loss amount is fixed:
        std::map<Real, Probability>::iterator distIt =
            pIndepDistrib.begin();
        while(distIt != pIndepDistrib.end()) {
            Real loss = distIt->first * loss_unit_
                                ;
            loss = std::max(std::min(loss,
                results_.xMax)-results_.xMin, 0.);
            expLoss += loss * distIt->second;
            distIt++;
        }
        return expLoss ;
        */
        //---------------------------------------------------------------
        Real relativeMax = this->results_.xMax / loss_unit_;
        Real relativeMin = this->results_.xMin / loss_unit_;
        Size relativeMaxIdx = std::ceil(relativeMax);
        Size relativeMinIdx = std::floor(relativeMin);
        std::map<Real, Probability>::iterator
            distIt = pIndepDistrib.lower_bound(relativeMinIdx),
            itTop  = pIndepDistrib.lower_bound(relativeMax);
        for(; distIt != itTop; distIt++)
            expLoss += std::max(std::min(distIt->first, relativeMax)
                                -relativeMin, 0.) * distIt->second;
        Real sumProbs = 0.;
        for(;distIt != pIndepDistrib.end(); distIt++)
            sumProbs += distIt->second;
        return expLoss * loss_unit_ + this->results_.remainingNotional * sumProbs;
    }
template<class CDOEngine, class copulaT> Real QuantLib::RecursiveCdoEngine< CDOEngine, copulaT >::expectedTrancheLoss (const Date & date) const [inline]
Definition at line 103 of file recursivecdoengine.hpp.
{
            return
                integral_(boost::bind(
                    &RecursiveCdoEngine<CDOEngine, copulaT>::integratorLoss,
                    this,
                    date,
                    _1)
                );
        }
template<class CDOEngine , class copulaT > void QuantLib::RecursiveCdoEngine< CDOEngine, copulaT >::initialize () const [protected]
Definition at line 137 of file recursivecdoengine.hpp.
References anonymous_namespace{marketmodel.cpp}::a, anonymous_namespace{marketmodel.cpp}::d, QuantLib::Schedule::dates(), anonymous_namespace{marketmodel.cpp}::dates, QuantLib::Settings::evaluationDate(), QuantLib::Singleton< Settings >::instance(), and QL_REQUIRE.
{
        wk_.clear();
        Date today = Settings::instance().evaluationDate();
        Date start = this->arguments_.schedule.startDate();
        boost::shared_ptr<Basket>& basket = this->arguments_.basket;
        /*
          Remove defaulted names and adjust the subordination.
        */
        std::vector<std::string> names =
            basket->remainingNames(start, today);
        std::vector<Real> notionals
            = basket->remainingNotionals(start, today);
        Real a = basket->remainingAttachmentRatio(start, today);
        Real d = basket->remainingDetachmentRatio(start, today);
        const boost::shared_ptr<Pool> pool = basket->pool();
        this->remainingBasket_ =
            boost::shared_ptr<Basket>(new Basket(names, notionals, pool,
                                                basket->remainingDefaultKeys(start, today),
                                                basket->remainingRecModels(start, today),
                                                 a, d));
        this->results_.xMin = this->remainingBasket_->attachmentAmount();
        this->results_.xMax = this->remainingBasket_->detachmentAmount();
        this->results_.remainingNotional =
            this->results_.xMax - this->results_.xMin;
        //----------------------------------------------------------------
        if(oneFactorCorrels_.empty())
            oneFactorCorrels_ = std::vector<Real>(names.size(),
                                    correlQuote_->value());
        // check size of factors:
        QL_REQUIRE(oneFactorCorrels_.size() == names.size(),
            "Size of matrix must match number of names in the basket.");
        //
        std::vector<Real> lgdsTmp, lgds = this->remainingBasket_->LGDs();
        lgdsTmp = lgds;
        std::remove(lgds.begin(), lgds.end(), 0.);
        loss_unit_ = *(std::min_element(lgds.begin(), lgds.end()))
            / nBuckets_;
        for(Size i = 0; i<names.size(); i++)
            wk_.push_back(std::floor(lgdsTmp[i]/loss_unit_ + .5));
        // Could not check parameters at construction time because we
        //   had no arguments yet, do it now:
        if(oneFactorCorrels_.size() == 1)
            oneFactorCorrels_ =
                std::vector<Real>(pool->size(), oneFactorCorrels_[0]);
        else
            QL_REQUIRE(oneFactorCorrels_.size() == this->remainingBasket_->size(),
                "Incompatible correl matrix, pool size.");
        //----------------------------------------------------------------
        const std::vector<Date>& dates = this->arguments_.schedule.dates();
        for (Size i = 0; i < dates.size(); i++) {
            if (dates[i] <= today)
                this->results_.expectedTrancheLoss.push_back(0.0);
            else {
                Real L = expectedTrancheLoss(dates[i]);
                this->results_.expectedTrancheLoss.push_back(L);
            }
        }
    }
template<class CDOEngine, class copulaT> Real QuantLib::RecursiveCdoEngine< CDOEngine, copulaT >::integratorLoss (const Date & date, Real mktFactor) const [inline, private]
Weights the conditional portfolio loss by the mkt factor.
Definition at line 78 of file recursivecdoengine.hpp.
{
            return expectedConditionalLoss(date, mktFactor) *
               copula_->density(mktFactor);
        }
template<class CDOEngine , class copulaT > void QuantLib::RecursiveCdoEngine< CDOEngine, copulaT >::update ()
Definition at line 130 of file recursivecdoengine.hpp.
{
        oneFactorCorrels_.clear();
        CDOEngine::update();
    }
Member Data Documentation
template<class CDOEngine, class copulaT> RelinkableHandle<copulaT> QuantLib::RecursiveCdoEngine< CDOEngine, copulaT >::copula_ [mutable, protected]
Definition at line 114 of file recursivecdoengine.hpp.
Referenced by QuantLib::RecursiveCdoEngine< CDOEngine, OneFactorStudentCopula >::integratorLoss().
template<class CDOEngine, class copulaT> const Handle<Quote> QuantLib::RecursiveCdoEngine< CDOEngine, copulaT >::correlQuote_ [protected]
Definition at line 113 of file recursivecdoengine.hpp.
template<class CDOEngine, class copulaT> const GaussHermiteIntegration QuantLib::RecursiveCdoEngine< CDOEngine, copulaT >::integral_ [private]
Definition at line 118 of file recursivecdoengine.hpp.
Referenced by QuantLib::RecursiveCdoEngine< CDOEngine, OneFactorStudentCopula >::expectedTrancheLoss().
template<class CDOEngine, class copulaT> Real QuantLib::RecursiveCdoEngine< CDOEngine, copulaT >::loss_unit_ [mutable, private]
Definition at line 120 of file recursivecdoengine.hpp.
template<class CDOEngine, class copulaT> Size QuantLib::RecursiveCdoEngine< CDOEngine, copulaT >::nBuckets_ [private]
Definition at line 117 of file recursivecdoengine.hpp.
template<class CDOEngine, class copulaT> std::vector<Real> QuantLib::RecursiveCdoEngine< CDOEngine, copulaT >::oneFactorCorrels_ [mutable, private]
name to name factor loadings (betas). In the single factor copula:
Definition at line 125 of file recursivecdoengine.hpp.
Referenced by QuantLib::RecursiveCdoEngine< CDOEngine, OneFactorStudentCopula >::RecursiveCdoEngine().
template<class CDOEngine, class copulaT> std::vector<Real> QuantLib::RecursiveCdoEngine< CDOEngine, copulaT >::wk_ [mutable, private]
Definition at line 119 of file recursivecdoengine.hpp.
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/recursivecdoengine.hpp