QuantLib: QuantLib::UnitOfMeasureConversionManager Class Reference
QuantLib::UnitOfMeasureConversionManager Class Reference
repository of conversion factors between units of measure
#include <unitofmeasureconversionmanager.hpp>
Public Member Functions
UnitOfMeasureConversion lookup (const CommodityType &commodityType, const UnitOfMeasure &, const UnitOfMeasure &, UnitOfMeasureConversion::Type type=UnitOfMeasureConversion::Derived) const
void add (const UnitOfMeasureConversion &)
void clear ()
Private Member Functions
UnitOfMeasureConversionManager ()
void addKnownConversionFactors ()
UnitOfMeasureConversion directLookup (const CommodityType &commodityType, const UnitOfMeasure &source, const UnitOfMeasure &target) const
UnitOfMeasureConversion smartLookup (const CommodityType &commodityType, const UnitOfMeasure &source, const UnitOfMeasure &target, std::list< std::string > forbidden=std::list< std::string >()) const
Private Attributes
std::list
< UnitOfMeasureConversion > data_
Friends
class Singleton< UnitOfMeasureConversionManager >
Detailed Description
repository of conversion factors between units of measure
Test:
lookup of direct unit of measure conversion is tested.
Definition at line 36 of file unitofmeasureconversionmanager.hpp.
Constructor & Destructor Documentation
QuantLib::UnitOfMeasureConversionManager::UnitOfMeasureConversionManager () [private]
Definition at line 56 of file unitofmeasureconversionmanager.cpp.
References addKnownConversionFactors().
    : Singleton<UnitOfMeasureConversionManager>() {
        addKnownConversionFactors();
    }
Member Function Documentation
void QuantLib::UnitOfMeasureConversionManager::add (const UnitOfMeasureConversion & c)
Definition at line 61 of file unitofmeasureconversionmanager.cpp.
References data_, and QuantLib::anonymous_namespace{unitofmeasureconversionmanager.cpp}::matches().
Referenced by addKnownConversionFactors().
{
        // not fast, but hopefully we won't have a lot of entries.
        for (list<UnitOfMeasureConversion>::iterator i = data_.begin();
             i != data_.end(); ++i) {
            if (matches(*i, c)) {
                data_.erase(i);
                break;
            }
        }
        data_.push_back(c);
    }
void QuantLib::UnitOfMeasureConversionManager::addKnownConversionFactors () [private]
Definition at line 107 of file unitofmeasureconversionmanager.cpp.
References add().
Referenced by clear(), and UnitOfMeasureConversionManager().
{
        add(UnitOfMeasureConversion(NullCommodityType(),
                                    MBUnitOfMeasure(),
                                    BarrelUnitOfMeasure(),
                                    1000));
        add(UnitOfMeasureConversion(NullCommodityType(),
                                    BarrelUnitOfMeasure(),
                                    GallonUnitOfMeasure(),
                                    42));
        add(UnitOfMeasureConversion(NullCommodityType(),
                                    GallonUnitOfMeasure(),
                                    MBUnitOfMeasure(),
                                    1000 * 42));
        add(UnitOfMeasureConversion(NullCommodityType(),
                                    LitreUnitOfMeasure(),
                                    GallonUnitOfMeasure(),
                                    3.78541));
        add(UnitOfMeasureConversion(NullCommodityType(),
                                    BarrelUnitOfMeasure(),
                                    LitreUnitOfMeasure(),
                                    158.987));
        add(UnitOfMeasureConversion(NullCommodityType(),
                                    KilolitreUnitOfMeasure(),
                                    BarrelUnitOfMeasure(),
                                    6.28981));
        add(UnitOfMeasureConversion(NullCommodityType(),
                                    TokyoKilolitreUnitOfMeasure(),
                                    BarrelUnitOfMeasure(),
                                    6.28981));
    }
void QuantLib::UnitOfMeasureConversionManager::clear ()
Definition at line 102 of file unitofmeasureconversionmanager.cpp.
References addKnownConversionFactors(), and data_.
{
        data_.clear();
        addKnownConversionFactors();
    }
UnitOfMeasureConversion QuantLib::UnitOfMeasureConversionManager::directLookup (const CommodityType & commodityType, const UnitOfMeasure & source, const UnitOfMeasure & target) const [private]
Definition at line 138 of file unitofmeasureconversionmanager.cpp.
References QuantLib::CommodityType::code(), QuantLib::UnitOfMeasure::code(), data_, QuantLib::anonymous_namespace{unitofmeasureconversionmanager.cpp}::matches(), and QL_FAIL.
Referenced by lookup(), and smartLookup().
{
        for (list<UnitOfMeasureConversion>::const_iterator i = data_.begin();
             i != data_.end(); ++i) {
            if (matches(*i, commodityType, source, target)) {
                return *i;
            }
        }
        // Here, the code used to look for conversions with null
        // commodity type as a fall-back.  However, this would only
        // affect direct lookups and not other matches being tried in
        // the smart-lookup loop.  To implement the complete fall-back
        // strategy, we should either duplicate the loop (as we would
        // duplicate it here---smelly) or change the 'matches'
        // functions so that a null commodity type matches. However,
        // in the second case we would also have to take care that
        // conversions with a null type be at the end of the list so
        // that they don't supersede specific types. We'll have to
        // think a bit about this, so no fall-back for the time being.
        QL_FAIL("no direct conversion available from "
                << commodityType.code() << " " << source.code()
                << " to " << target.code());
    }
UnitOfMeasureConversion QuantLib::UnitOfMeasureConversionManager::lookup (const CommodityType & commodityType, const UnitOfMeasure & source, const UnitOfMeasure & target, UnitOfMeasureConversion::Type type = UnitOfMeasureConversion::Derived) const
Definition at line 74 of file unitofmeasureconversionmanager.cpp.
References QuantLib::UnitOfMeasureConversion::chain(), QuantLib::UnitOfMeasureConversion::Direct, directLookup(), QuantLib::UnitOfMeasure::empty(), smartLookup(), and QuantLib::UnitOfMeasure::triangulationUnitOfMeasure().
Referenced by QuantLib::CommodityPricingHelper::calculateUomConversionFactor(), QuantLib::EnergyCommodity::calculateUomConversionFactor(), QuantLib::anonymous_namespace{quantity.cpp}::convertTo(), and CommodityUnitOfMeasureTest::testDirect().
{
        if (type == UnitOfMeasureConversion::Direct) {
            return directLookup(commodityType,source,target);
        } else if (!source.triangulationUnitOfMeasure().empty()) {
            const UnitOfMeasure& link = source.triangulationUnitOfMeasure();
            if (link == target)
                return directLookup(commodityType,source,link);
            else
                return UnitOfMeasureConversion::chain(
                                      directLookup(commodityType,source,link),
                                      lookup(commodityType,link,target));
        } else if (!target.triangulationUnitOfMeasure().empty()) {
            const UnitOfMeasure& link = target.triangulationUnitOfMeasure();
            if (source == link)
                return directLookup(commodityType,link,target);
            else
                return UnitOfMeasureConversion::chain(
                                     lookup(commodityType,source,link),
                                     directLookup(commodityType,link,target));
        } else {
            return smartLookup(commodityType,source,target);
        }
    }
UnitOfMeasureConversion QuantLib::UnitOfMeasureConversionManager::smartLookup (const CommodityType & commodityType, const UnitOfMeasure & source, const UnitOfMeasure & target, std::list< std::string > forbidden = std::list<std::string>()) const [private]
Definition at line 167 of file unitofmeasureconversionmanager.cpp.
References QuantLib::UnitOfMeasureConversion::chain(), QuantLib::CommodityType::code(), QuantLib::UnitOfMeasure::code(), data_, directLookup(), QuantLib::anonymous_namespace{unitofmeasureconversionmanager.cpp}::matches(), and QL_FAIL.
Referenced by lookup().
{
        try {
            return directLookup(commodityType,source,target);
        } catch (Error&) {
            ; // no direct conversion available; turn to smart lookup.
        }
        // The source unit is forbidden to subsequent lookups in order
        // to avoid cycles.
        forbidden.push_back(source.code());
        for (list<UnitOfMeasureConversion>::const_iterator i = data_.begin();
             i != data_.end(); ++i) {
            // we look for conversion data which involve our source unit...
            if (matches(*i, commodityType, source)) {
                const UnitOfMeasure& other =
                    source == i->source() ? i->target() : i->source();
                if (find(forbidden.begin(),forbidden.end(),
                         other.code()) == forbidden.end()) {
                    // if we can get to the target from here...
                    try {
                        UnitOfMeasureConversion tail =
                            smartLookup(commodityType,other,target);
                        // ..we're done.
                        return UnitOfMeasureConversion::chain(*i,tail);
                    } catch (Error&) {
                        // otherwise, we just discard this conversion.
                        ;
                    }
                }
            }
        }
        // if the loop completed, we have no way to return the
        // requested conversion.
        QL_FAIL("no conversion available for "
                << commodityType.code() << " from "
                << source.code() << " to " << target.code());
    }
Friends And Related Function Documentation
friend class Singleton< UnitOfMeasureConversionManager > [friend]
Definition at line 38 of file unitofmeasureconversionmanager.hpp.
Member Data Documentation
std::list<UnitOfMeasureConversion> QuantLib::UnitOfMeasureConversionManager::data_ [private]
Definition at line 51 of file unitofmeasureconversionmanager.hpp.
Referenced by add(), clear(), directLookup(), and smartLookup().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/commodities/unitofmeasureconversionmanager.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/commodities/unitofmeasureconversionmanager.cpp