QuantLib: QuantLib::MersenneTwisterUniformRng Class Reference
QuantLib::MersenneTwisterUniformRng Class Reference
Uniform random number generator.
#include <mt19937uniformrng.hpp>
Public Types
typedef Sample< Real > sample_type
Public Member Functions
MersenneTwisterUniformRng (unsigned long seed=0)
MersenneTwisterUniformRng (const std::vector< unsigned long > &seeds)
sample_type next () const
Real nextReal () const
return a random number in the (0.0, 1.0)-interval
unsigned long nextInt32 () const
return a random integer in the [0,0xffffffff]-interval
Private Member Functions
void seedInitialization (unsigned long seed)
void twist () const
Private Attributes
unsigned long mt [N]
Size mti
Static Private Attributes
static const Size N = 624
static const Size M = 397
static const unsigned long MATRIX_A = 0x9908b0dfUL
static const unsigned long UPPER_MASK = 0x80000000UL
static const unsigned long LOWER_MASK = 0x7fffffffUL
Detailed Description
Uniform random number generator.
Mersenne Twister random number generator of period 2**19937-1
For more details see http://www.math.keio.ac.jp/matumoto/emt.html
Test:
the correctness of the returned values is tested by checking them against known good results.
Definition at line 41 of file mt19937uniformrng.hpp.
Member Typedef Documentation
typedef Sample<Real> QuantLib::MersenneTwisterUniformRng::sample_type
Definition at line 46 of file mt19937uniformrng.hpp.
Constructor & Destructor Documentation
QuantLib::MersenneTwisterUniformRng::MersenneTwisterUniformRng (unsigned long seed = 0) [explicit]
if the given seed is 0, a random seed will be chosen based on clock()
Definition at line 82 of file mt19937uniformrng.cpp.
References seedInitialization().
{
        seedInitialization(seed);
    }
QuantLib::MersenneTwisterUniformRng::MersenneTwisterUniformRng (const std::vector< unsigned long > & seeds) [explicit]
Definition at line 102 of file mt19937uniformrng.cpp.
References mt, N, seedInitialization(), and UPPER_MASK.
{
        seedInitialization(19650218UL);
        Size i=1, j=0, k = (N>seeds.size() ? N : seeds.size());
        for (; k; k--) {
            mt[i] = (mt[i] ^ ((mt[i-1] ^ (mt[i-1] >> 30)) * 1664525UL))
                + seeds[j] + j; /* non linear */
            mt[i] &= 0xffffffffUL; /* for WORDSIZE > 32 machines */
            i++; j++;
            if (i>=N) { mt[0] = mt[N-1]; i=1; }
            if (j>=seeds.size()) j=0;
        }
        for (k=N-1; k; k--) {
            mt[i] = (mt[i] ^ ((mt[i-1] ^ (mt[i-1] >> 30)) * 1566083941UL))
                - i; /* non linear */
            mt[i] &= 0xffffffffUL; /* for WORDSIZE > 32 machines */
            i++;
            if (i>=N) { mt[0] = mt[N-1]; i=1; }
        }
        mt[0] = UPPER_MASK; /*MSB is 1; assuring non-zero initial array*/
    }
Member Function Documentation
sample_type QuantLib::MersenneTwisterUniformRng::next () const [inline]
returns a sample with weight 1.0 containing a random number in the (0.0, 1.0) interval
Definition at line 54 of file mt19937uniformrng.hpp.
References nextReal().
Referenced by QuantLib::LossDistMonteCarlo::operator()(), QuantLib::SobolRsg::SobolRsg(), FdmLinearOpTest::testBiCGstab(), MatricesTest::testDeterminant(), MatricesTest::testOrthogonalProjection(), MatricesTest::testQRSolve(), and MersenneTwisterTest::testValues().
{ return sample_type(nextReal(),1.0); }
unsigned long QuantLib::MersenneTwisterUniformRng::nextInt32 () const [inline]
return a random integer in the [0,0xffffffff]-interval
Definition at line 60 of file mt19937uniformrng.hpp.
References mt, mti, N, and twist().
Referenced by QuantLib::SeedGenerator::get(), QuantLib::SeedGenerator::initialize(), QuantLib::ZigguratRng::nextGaussian(), nextReal(), and MersenneTwisterTest::testValues().
{
            if (mti==N)
                twist(); /* generate N words at a time */
            unsigned long y = mt[mti++];
            /* Tempering */
            y ^= (y >> 11);
            y ^= (y << 7) & 0x9d2c5680UL;
            y ^= (y << 15) & 0xefc60000UL;
            y ^= (y >> 18);
            return y;
        }
Real QuantLib::MersenneTwisterUniformRng::nextReal () const [inline]
return a random number in the (0.0, 1.0)-interval
Definition at line 56 of file mt19937uniformrng.hpp.
References nextInt32().
Referenced by next(), and QuantLib::ZigguratRng::nextGaussian().
{
            return (Real(nextInt32()) + 0.5)/4294967296.0;
        }
void QuantLib::MersenneTwisterUniformRng::seedInitialization (unsigned long seed) [private]
Definition at line 86 of file mt19937uniformrng.cpp.
References QuantLib::SeedGenerator::get(), QuantLib::Singleton< SeedGenerator >::instance(), mt, mti, and N.
Referenced by MersenneTwisterUniformRng().
{
        /* initializes mt with a seed */
        unsigned long s = (seed != 0 ? seed : SeedGenerator::instance().get());
        mt[0]= s & 0xffffffffUL;
        for (mti=1; mti<N; mti++) {
            mt[mti] =
                (1812433253UL * (mt[mti-1] ^ (mt[mti-1] >> 30)) + mti);
            /* See Knuth TAOCP Vol2. 3rd Ed. P.106 for multiplier. */
            /* In the previous versions, MSBs of the seed affect   */
            /* only MSBs of the array mt[].                        */
            /* 2002/01/09 modified by Makoto Matsumoto             */
            mt[mti] &= 0xffffffffUL;
            /* for >32 bit machines */
        }
    }
void QuantLib::MersenneTwisterUniformRng::twist () const [private]
Definition at line 125 of file mt19937uniformrng.cpp.
References LOWER_MASK, M, MATRIX_A, mt, mti, N, and UPPER_MASK.
Referenced by nextInt32().
{
        static const unsigned long mag01[2]={0x0UL, MATRIX_A};
        /* mag01[x] = x * MATRIX_A  for x=0,1 */
        Size kk;
        unsigned long y;
        for (kk=0;kk<N-M;kk++) {
            y = (mt[kk]&UPPER_MASK)|(mt[kk+1]&LOWER_MASK);
            mt[kk] = mt[kk+M] ^ (y >> 1) ^ mag01[y & 0x1UL];
        }
        for (;kk<N-1;kk++) {
            y = (mt[kk]&UPPER_MASK)|(mt[kk+1]&LOWER_MASK);
            mt[kk] = mt[kk+(M-N)] ^ (y >> 1) ^ mag01[y & 0x1UL];
        }
        y = (mt[N-1]&UPPER_MASK)|(mt[0]&LOWER_MASK);
        mt[N-1] = mt[M-1] ^ (y >> 1) ^ mag01[y & 0x1UL];
        mti = 0;
    }
Member Data Documentation
const unsigned long QuantLib::MersenneTwisterUniformRng::LOWER_MASK = 0x7fffffffUL [static, private]
Definition at line 78 of file mt19937uniformrng.hpp.
Referenced by twist().
const Size QuantLib::MersenneTwisterUniformRng::M = 397 [static, private]
Definition at line 44 of file mt19937uniformrng.hpp.
Referenced by twist().
const unsigned long QuantLib::MersenneTwisterUniformRng::MATRIX_A = 0x9908b0dfUL [static, private]
Definition at line 78 of file mt19937uniformrng.hpp.
Referenced by twist().
unsigned long QuantLib::MersenneTwisterUniformRng::mt[N] [mutable, private]
Definition at line 76 of file mt19937uniformrng.hpp.
Referenced by MersenneTwisterUniformRng(), nextInt32(), seedInitialization(), and twist().
Size QuantLib::MersenneTwisterUniformRng::mti [mutable, private]
Definition at line 77 of file mt19937uniformrng.hpp.
Referenced by nextInt32(), seedInitialization(), and twist().
const Size QuantLib::MersenneTwisterUniformRng::N = 624 [static, private]
Definition at line 43 of file mt19937uniformrng.hpp.
Referenced by MersenneTwisterUniformRng(), nextInt32(), seedInitialization(), and twist().
const unsigned long QuantLib::MersenneTwisterUniformRng::UPPER_MASK = 0x80000000UL [static, private]
Definition at line 78 of file mt19937uniformrng.hpp.
Referenced by MersenneTwisterUniformRng(), and twist().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/randomnumbers/mt19937uniformrng.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/math/randomnumbers/mt19937uniformrng.cpp