QuantLib: QuantLib::TridiagonalOperator Class Reference
QuantLib::TridiagonalOperator Class Reference
Base implementation for tridiagonal operator.
#include <tridiagonaloperator.hpp>
Classes
class TimeSetter
encapsulation of time-setting logic
Public Types
typedef Array array_type
Public Member Functions
TridiagonalOperator (Size size=0)
TridiagonalOperator (const Array &low, const Array &mid, const Array &high)
TridiagonalOperator (const Disposable< TridiagonalOperator > &)
TridiagonalOperator & operator= (const Disposable< TridiagonalOperator > &)
Inspectors
Size size () const
bool isTimeDependent () const
const Array & lowerDiagonal () const
const Array & diagonal () const
const Array & upperDiagonal () const
Modifiers
void setFirstRow (Real, Real)
void setMidRow (Size, Real, Real, Real)
void setMidRows (Real, Real, Real)
void setLastRow (Real, Real)
void setTime (Time t)
Utilities
void swap (TridiagonalOperator &)
Protected Attributes
Size n_
Array diagonal_
Array lowerDiagonal_
Array upperDiagonal_
Array temp_
boost::shared_ptr< TimeSetter > timeSetter_
Friends
Disposable< TridiagonalOperator > operator+ (const TridiagonalOperator &)
Disposable< TridiagonalOperator > operator- (const TridiagonalOperator &)
Disposable< TridiagonalOperator > operator+ (const TridiagonalOperator &, const TridiagonalOperator &)
Disposable< TridiagonalOperator > operator- (const TridiagonalOperator &, const TridiagonalOperator &)
Disposable< TridiagonalOperator > operator* (Real, const TridiagonalOperator &)
Disposable< TridiagonalOperator > operator* (const TridiagonalOperator &, Real)
Disposable< TridiagonalOperator > operator/ (const TridiagonalOperator &, Real)
Operator interface
Disposable< Array > applyTo (const Array &v) const
apply operator to a given array
Disposable< Array > solveFor (const Array &rhs) const
solve linear system for a given right-hand side
void solveFor (const Array &rhs, Array &result) const
Disposable< Array > SOR (const Array &rhs, Real tol) const
solve linear system with SOR approach
static Disposable
< TridiagonalOperator > identity (Size size)
identity instance
Detailed Description
Base implementation for tridiagonal operator.
Warning:
to use real time-dependant algebra, you must overload the corresponding operators in the inheriting time-dependent class.
Definition at line 42 of file tridiagonaloperator.hpp.
Member Typedef Documentation
typedef Array QuantLib::TridiagonalOperator::array_type
Definition at line 65 of file tridiagonaloperator.hpp.
Constructor & Destructor Documentation
QuantLib::TridiagonalOperator::TridiagonalOperator (Size size = 0) [explicit]
Definition at line 25 of file tridiagonaloperator.cpp.
References diagonal_, lowerDiagonal_, n_, QL_FAIL, size(), temp_, and upperDiagonal_.
{
        if (size>=2) {
            n_ = size;
            diagonal_      = Array(size);
            lowerDiagonal_ = Array(size-1);
            upperDiagonal_ = Array(size-1);
            temp_          = Array(size);
        } else if (size==0) {
            n_ = 0;
            diagonal_      = Array(0);
            lowerDiagonal_ = Array(0);
            upperDiagonal_ = Array(0);
            temp_          = Array(0);
        } else {
            QL_FAIL("invalid size (" << size << ") for tridiagonal operator "
                    "(must be null or >= 2)");
        }
    }
QuantLib::TridiagonalOperator::TridiagonalOperator (const Array & low, const Array & mid, const Array & high)
Definition at line 44 of file tridiagonaloperator.cpp.
References n_, QL_REQUIRE, and QuantLib::Array::size().
    : n_(mid.size()),
      diagonal_(mid), lowerDiagonal_(low), upperDiagonal_(high), temp_(n_) {
        QL_REQUIRE(low.size() == n_-1,
                   "low diagonal vector of size " << low.size() <<
                   " instead of " << n_-1);
        QL_REQUIRE(high.size() == n_-1,
                   "high diagonal vector of size " << high.size() <<
                   " instead of " << n_-1);
    }
QuantLib::TridiagonalOperator::TridiagonalOperator (const Disposable< TridiagonalOperator > & from)
Definition at line 57 of file tridiagonaloperator.cpp.
References swap().
{
        swap(const_cast<Disposable<TridiagonalOperator>&>(from));
    }
Member Function Documentation
Disposable< Array > QuantLib::TridiagonalOperator::applyTo (const Array & v) const
apply operator to a given array
Definition at line 62 of file tridiagonaloperator.cpp.
References QuantLib::Array::begin(), diagonal_, QuantLib::Array::end(), lowerDiagonal_, n_, QL_REQUIRE, QuantLib::Array::size(), and upperDiagonal_.
Referenced by OperatorTest::testConsistency(), and OperatorTest::testTridiagonal().
{
        QL_REQUIRE(n_!=0,
                   "uninitialized TridiagonalOperator");
        QL_REQUIRE(v.size()==n_,
                   "vector of the wrong size " << v.size() <<
                   " instead of " << n_);
        Array result(n_);
        std::transform(diagonal_.begin(), diagonal_.end(),
                       v.begin(),
                       result.begin(),
                       std::multiplies<Real>());
        // matricial product
        result[0] += upperDiagonal_[0]*v[1];
        for (Size j=1; j<=n_-2; j++)
            result[j] += lowerDiagonal_[j-1]*v[j-1]+
                upperDiagonal_[j]*v[j+1];
        result[n_-1] += lowerDiagonal_[n_-2]*v[n_-2];
        return result;
    }
const Array& QuantLib::TridiagonalOperator::diagonal (void) const [inline]
Definition at line 96 of file tridiagonaloperator.hpp.
References diagonal_.
Referenced by OperatorTest::testBSMOperatorConsistency().
{ return diagonal_; }
Disposable< TridiagonalOperator > QuantLib::TridiagonalOperator::identity (Size size) [static]
identity instance
Definition at line 163 of file tridiagonaloperator.cpp.
References anonymous_namespace{matrices.cpp}::I.
{
        TridiagonalOperator I(Array(size-1, 0.0),     // lower diagonal
                              Array(size,   1.0),     // diagonal
                              Array(size-1, 0.0));    // upper diagonal
        return I;
    }
bool QuantLib::TridiagonalOperator::isTimeDependent () const [inline]
Definition at line 94 of file tridiagonaloperator.hpp.
References timeSetter_.
{ return !!timeSetter_; }
const Array& QuantLib::TridiagonalOperator::lowerDiagonal () const [inline]
Definition at line 95 of file tridiagonaloperator.hpp.
References lowerDiagonal_.
Referenced by OperatorTest::testBSMOperatorConsistency().
{ return lowerDiagonal_; }
TridiagonalOperator & QuantLib::TridiagonalOperator::operator= (const Disposable< TridiagonalOperator > & from) [inline]
Definition at line 131 of file tridiagonaloperator.hpp.
References swap().
{
        swap(const_cast<Disposable<TridiagonalOperator>&>(from));
        return *this;
    }
void QuantLib::TridiagonalOperator::setFirstRow (Real valB, Real valC) [inline]
Definition at line 137 of file tridiagonaloperator.hpp.
References diagonal_, and upperDiagonal_.
Referenced by QuantLib::NeumannBC::applyBeforeApplying(), QuantLib::DirichletBC::applyBeforeApplying(), QuantLib::NeumannBC::applyBeforeSolving(), QuantLib::DirichletBC::applyBeforeSolving(), QuantLib::DMinus::DMinus(), QuantLib::DPlus::DPlus(), QuantLib::DPlusDMinus::DPlusDMinus(), QuantLib::DZero::DZero(), OperatorTest::testTridiagonal(), and QuantLib::detail::CubicInterpolationImpl< I1, I2 >::update().
{
        diagonal_[0]      = valB;
        upperDiagonal_[0] = valC;
    }
void QuantLib::TridiagonalOperator::setLastRow (Real valA, Real valB) [inline]
Definition at line 164 of file tridiagonaloperator.hpp.
References diagonal_, lowerDiagonal_, and n_.
Referenced by QuantLib::NeumannBC::applyBeforeApplying(), QuantLib::DirichletBC::applyBeforeApplying(), QuantLib::NeumannBC::applyBeforeSolving(), QuantLib::DirichletBC::applyBeforeSolving(), QuantLib::DMinus::DMinus(), QuantLib::DPlus::DPlus(), QuantLib::DPlusDMinus::DPlusDMinus(), QuantLib::DZero::DZero(), OperatorTest::testTridiagonal(), and QuantLib::detail::CubicInterpolationImpl< I1, I2 >::update().
{
        lowerDiagonal_[n_-2] = valA;
        diagonal_[n_-1]      = valB;
    }
void QuantLib::TridiagonalOperator::setMidRow (Size i, Real valA, Real valB, Real valC) [inline]
Definition at line 143 of file tridiagonaloperator.hpp.
References diagonal_, lowerDiagonal_, n_, QL_REQUIRE, and upperDiagonal_.
Referenced by QuantLib::PdeSecondOrderParabolic::generateOperator(), and QuantLib::detail::CubicInterpolationImpl< I1, I2 >::update().
{
        QL_REQUIRE(i>=1 && i<=n_-2,
                   "out of range in TridiagonalSystem::setMidRow");
        lowerDiagonal_[i-1] = valA;
        diagonal_[i]        = valB;
        upperDiagonal_[i]   = valC;
    }
void QuantLib::TridiagonalOperator::setMidRows (Real valA, Real valB, Real valC) [inline]
Definition at line 154 of file tridiagonaloperator.hpp.
References diagonal_, lowerDiagonal_, n_, and upperDiagonal_.
Referenced by QuantLib::BSMOperator::BSMOperator(), QuantLib::DMinus::DMinus(), QuantLib::DPlus::DPlus(), QuantLib::DPlusDMinus::DPlusDMinus(), QuantLib::DZero::DZero(), and OperatorTest::testTridiagonal().
{
        for (Size i=1; i<=n_-2; i++) {
            lowerDiagonal_[i-1] = valA;
            diagonal_[i]        = valB;
            upperDiagonal_[i]   = valC;
        }
    }
void QuantLib::TridiagonalOperator::setTime (Time t) [inline]
Definition at line 170 of file tridiagonaloperator.hpp.
References timeSetter_.
Referenced by QuantLib::PdeOperator< PdeClass >::PdeOperator().
{
        if (timeSetter_)
            timeSetter_->setTime(t, *this);
    }
Size QuantLib::TridiagonalOperator::size () const [inline]
Definition at line 93 of file tridiagonaloperator.hpp.
References n_.
Referenced by TridiagonalOperator().
{ return n_; }
Disposable< Array > QuantLib::TridiagonalOperator::solveFor (const Array & rhs) const
solve linear system for a given right-hand side
Definition at line 84 of file tridiagonaloperator.cpp.
References QuantLib::Array::size().
Referenced by OperatorTest::testTridiagonal(), and QuantLib::detail::CubicInterpolationImpl< I1, I2 >::update().
{
        Array result(rhs.size());
        solveFor(rhs, result);
        return result;
    }
void QuantLib::TridiagonalOperator::solveFor (const Array & rhs, Array & result) const
solve linear system for a given right-hand side without result Array allocation. The rhs and result parameters can be the same Array, in which case rhs will be changed
Definition at line 91 of file tridiagonaloperator.cpp.
References QuantLib::close(), diagonal_, lowerDiagonal_, n_, QL_ENSURE, QL_REQUIRE, QuantLib::Array::size(), temp_, and upperDiagonal_.
{
        QL_REQUIRE(n_!=0,
                   "uninitialized TridiagonalOperator");
        QL_REQUIRE(rhs.size()==n_,
                   "rhs vector of size " << rhs.size() <<
                   " instead of " << n_);
        Real bet = diagonal_[0];
        QL_REQUIRE(!close(bet, 0.0),
                   "diagonal's first element (" << bet <<
                   ") cannot be close to zero");
        result[0] = rhs[0]/bet;
        for (Size j=1; j<=n_-1; ++j) {
            temp_[j] = upperDiagonal_[j-1]/bet;
            bet = diagonal_[j]-lowerDiagonal_[j-1]*temp_[j];
            QL_ENSURE(!close(bet, 0.0), "division by zero");
            result[j] = (rhs[j] - lowerDiagonal_[j-1]*result[j-1])/bet;
        }
        // cannot be j>=0 with Size j
        for (Size j=n_-2; j>0; --j)
            result[j] -= temp_[j+1]*result[j+1];
        result[0] -= temp_[1]*result[1];
    }
Disposable< Array > QuantLib::TridiagonalOperator::SOR (const Array & rhs, Real tol) const
solve linear system with SOR approach
Definition at line 117 of file tridiagonaloperator.cpp.
References diagonal_, lowerDiagonal_, n_, QL_REQUIRE, QuantLib::Array::size(), and upperDiagonal_.
Referenced by OperatorTest::testTridiagonal().
{
        QL_REQUIRE(n_!=0,
                   "uninitialized TridiagonalOperator");
        QL_REQUIRE(rhs.size()==n_,
                   "rhs vector of size " << rhs.size() <<
                   " instead of " << n_);
        // initial guess
        Array result = rhs;
        // solve tridiagonal system with SOR technique
        Real omega = 1.5;
        Real err = 2.0*tol;
        Real temp;
        for (Size sorIteration=0; err>tol ; ++sorIteration) {
            QL_REQUIRE(sorIteration<100000,
                       "tolerance (" << tol << ") not reached in " <<
                       sorIteration << " iterations. " <<
                       "The error still is " << err);
            temp = omega * (rhs[0]     -
                            upperDiagonal_[0]   * result[1]-
                            diagonal_[0]        * result[0])/diagonal_[0];
            err = temp*temp;
            result[0] += temp;
            Size i;
            for (i=1; i<n_-1 ; ++i) {
                temp = omega *(rhs[i]     -
                               upperDiagonal_[i]   * result[i+1]-
                               diagonal_[i]        * result[i] -
                               lowerDiagonal_[i-1] * result[i-1])/diagonal_[i];
                err += temp * temp;
                result[i] += temp;
            }
            temp = omega * (rhs[i]     -
                            diagonal_[i]        * result[i] -
                            lowerDiagonal_[i-1] * result[i-1])/diagonal_[i];
            err += temp*temp;
            result[i] += temp;
        }
        return result;
    }
void QuantLib::TridiagonalOperator::swap (TridiagonalOperator & from) [inline]
Definition at line 175 of file tridiagonaloperator.hpp.
References diagonal_, lowerDiagonal_, n_, QuantLib::Array::swap(), temp_, timeSetter_, and upperDiagonal_.
Referenced by operator=(), QuantLib::swap(), and TridiagonalOperator().
{
        using std::swap;
        swap(n_, from.n_);
        diagonal_.swap(from.diagonal_);
        lowerDiagonal_.swap(from.lowerDiagonal_);
        upperDiagonal_.swap(from.upperDiagonal_);
        temp_.swap(from.temp_);
        swap(timeSetter_, from.timeSetter_);
    }
const Array& QuantLib::TridiagonalOperator::upperDiagonal () const [inline]
Definition at line 97 of file tridiagonaloperator.hpp.
References upperDiagonal_.
Referenced by OperatorTest::testBSMOperatorConsistency().
{ return upperDiagonal_; }
Friends And Related Function Documentation
Disposable<TridiagonalOperator> operator* (Real a, const TridiagonalOperator & D) [friend]
Definition at line 224 of file tridiagonaloperator.hpp.
{
        Array low = D.lowerDiagonal_ * a,
            mid = D.diagonal_ * a,
            high = D.upperDiagonal_ * a;
        TridiagonalOperator result(low, mid, high);
        return result;
    }
Disposable<TridiagonalOperator> operator* (const TridiagonalOperator & D, Real a) [friend]
Definition at line 234 of file tridiagonaloperator.hpp.
                      {
        Array low = D.lowerDiagonal_ * a,
            mid = D.diagonal_ * a,
            high = D.upperDiagonal_ * a;
        TridiagonalOperator result(low, mid, high);
        return result;
    }
Disposable<TridiagonalOperator> operator+ (const TridiagonalOperator & D) [friend]
Definition at line 189 of file tridiagonaloperator.hpp.
{
        TridiagonalOperator D1 = D;
        return D1;
    }
Disposable<TridiagonalOperator> operator+ (const TridiagonalOperator & D1, const TridiagonalOperator & D2) [friend]
Definition at line 204 of file tridiagonaloperator.hpp.
{
        Array low = D1.lowerDiagonal_ + D2.lowerDiagonal_,
            mid = D1.diagonal_ + D2.diagonal_,
            high = D1.upperDiagonal_ + D2.upperDiagonal_;
        TridiagonalOperator result(low, mid, high);
        return result;
    }
Disposable<TridiagonalOperator> operator- (const TridiagonalOperator & D) [friend]
Definition at line 195 of file tridiagonaloperator.hpp.
{
        Array low = -D.lowerDiagonal_,
            mid = -D.diagonal_,
            high = -D.upperDiagonal_;
        TridiagonalOperator result(low, mid, high);
        return result;
    }
Disposable<TridiagonalOperator> operator- (const TridiagonalOperator & D1, const TridiagonalOperator & D2) [friend]
Definition at line 214 of file tridiagonaloperator.hpp.
{
        Array low = D1.lowerDiagonal_ - D2.lowerDiagonal_,
            mid = D1.diagonal_ - D2.diagonal_,
            high = D1.upperDiagonal_ - D2.upperDiagonal_;
        TridiagonalOperator result(low, mid, high);
        return result;
    }
Disposable<TridiagonalOperator> operator/ (const TridiagonalOperator & D, Real a) [friend]
Definition at line 244 of file tridiagonaloperator.hpp.
                      {
        Array low = D.lowerDiagonal_ / a,
            mid = D.diagonal_ / a,
            high = D.upperDiagonal_ / a;
        TridiagonalOperator result(low, mid, high);
        return result;
    }
Member Data Documentation
Array QuantLib::TridiagonalOperator::diagonal_ [protected]
Definition at line 120 of file tridiagonaloperator.hpp.
Referenced by applyTo(), diagonal(), QuantLib::operator*(), QuantLib::operator+(), QuantLib::operator-(), QuantLib::operator/(), setFirstRow(), setLastRow(), setMidRow(), setMidRows(), solveFor(), SOR(), swap(), and TridiagonalOperator().
Array QuantLib::TridiagonalOperator::lowerDiagonal_ [protected]
Definition at line 120 of file tridiagonaloperator.hpp.
Referenced by applyTo(), lowerDiagonal(), QuantLib::operator*(), QuantLib::operator+(), QuantLib::operator-(), QuantLib::operator/(), setLastRow(), setMidRow(), setMidRows(), solveFor(), SOR(), swap(), and TridiagonalOperator().
Size QuantLib::TridiagonalOperator::n_ [protected]
Definition at line 119 of file tridiagonaloperator.hpp.
Referenced by applyTo(), setLastRow(), setMidRow(), setMidRows(), size(), solveFor(), SOR(), swap(), and TridiagonalOperator().
Array QuantLib::TridiagonalOperator::temp_ [mutable, protected]
Definition at line 121 of file tridiagonaloperator.hpp.
Referenced by solveFor(), swap(), and TridiagonalOperator().
boost::shared_ptr<TimeSetter> QuantLib::TridiagonalOperator::timeSetter_ [protected]
Definition at line 122 of file tridiagonaloperator.hpp.
Referenced by isTimeDependent(), QuantLib::PdeOperator< PdeClass >::PdeOperator(), setTime(), and swap().
Array QuantLib::TridiagonalOperator::upperDiagonal_ [protected]
Definition at line 120 of file tridiagonaloperator.hpp.
Referenced by applyTo(), QuantLib::operator*(), QuantLib::operator+(), QuantLib::operator-(), QuantLib::operator/(), setFirstRow(), setMidRow(), setMidRows(), solveFor(), SOR(), swap(), TridiagonalOperator(), and upperDiagonal().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/tridiagonaloperator.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/tridiagonaloperator.cpp