QuantLib: QuantLib::MargrabeOption Class Reference
QuantLib::MargrabeOption Class Reference
Margrabe option on two assets.
#include <margrabeoption.hpp>
Classes
class arguments
Extra arguments for Margrabe option.
class engine
Margrabe option engine base class
class results
Extra results for Margrabe option.
Public Member Functions
MargrabeOption (Integer Q1, Integer Q2, const boost::shared_ptr< Exercise > &)
void setupArguments (PricingEngine::arguments *) const
Real delta1 () const
Real delta2 () const
Real gamma1 () const
Real gamma2 () const
void fetchResults (const PricingEngine::results *) const
Protected Attributes
Integer Q1_
Integer Q2_
Real delta1_
Real delta2_
Real gamma1_
Real gamma2_
Detailed Description
Margrabe option on two assets.
This option gives the holder the right to exchange Q2 stocks of the second asset for Q1 stocks of the first at expiration.
Definition at line 37 of file margrabeoption.hpp.
Constructor & Destructor Documentation
QuantLib::MargrabeOption::MargrabeOption (Integer Q1, Integer Q2, const boost::shared_ptr< Exercise > & exercise)
Definition at line 25 of file margrabeoption.cpp.
    : MultiAssetOption(boost::shared_ptr<Payoff>(new NullPayoff), exercise),
      Q1_(Q1),
      Q2_(Q2) {}
Member Function Documentation
Real QuantLib::MargrabeOption::delta1 () const
Definition at line 32 of file margrabeoption.cpp.
References QuantLib::Instrument::calculate(), delta1_, and QL_REQUIRE.
Referenced by MargrabeOptionTest::testEuroExchangeTwoAssets(), and MargrabeOptionTest::testGreeks().
{
        calculate();
        QL_REQUIRE(delta1_ != Null<Real>(), "delta1 not provided");
        return delta1_;
    }
Real QuantLib::MargrabeOption::delta2 () const
Definition at line 38 of file margrabeoption.cpp.
References QuantLib::Instrument::calculate(), delta2_, and QL_REQUIRE.
Referenced by MargrabeOptionTest::testEuroExchangeTwoAssets(), and MargrabeOptionTest::testGreeks().
{
        calculate();
        QL_REQUIRE(delta2_ != Null<Real>(), "delta2 not provided");
        return delta2_;
    }
void QuantLib::MargrabeOption::fetchResults (const PricingEngine::results * r) const [virtual]
When a derived result structure is defined for an instrument, this method should be overridden to read from it. This is mandatory in case a pricing engine is used.
Reimplemented from QuantLib::MultiAssetOption.
Definition at line 79 of file margrabeoption.cpp.
References QuantLib::MargrabeOption::results::delta1, delta1_, QuantLib::MargrabeOption::results::delta2, delta2_, QuantLib::MargrabeOption::results::gamma1, gamma1_, QuantLib::MargrabeOption::results::gamma2, gamma2_, and QL_REQUIRE.
{
        MultiAssetOption::fetchResults(r);
        const MargrabeOption::results* results =
            dynamic_cast<const MargrabeOption::results*>(r);
        QL_REQUIRE(results != 0, "wrong result type");
        delta1_          = results->delta1;
        delta2_          = results->delta2;
        gamma1_          = results->gamma1;
        gamma2_          = results->gamma2;
    }
Real QuantLib::MargrabeOption::gamma1 () const
Definition at line 44 of file margrabeoption.cpp.
References QuantLib::Instrument::calculate(), gamma1_, and QL_REQUIRE.
Referenced by MargrabeOptionTest::testEuroExchangeTwoAssets(), and MargrabeOptionTest::testGreeks().
{
        calculate();
        QL_REQUIRE(gamma1_ != Null<Real>(), "gamma1 not provided");
        return gamma1_;
    }
Real QuantLib::MargrabeOption::gamma2 () const
Definition at line 50 of file margrabeoption.cpp.
References QuantLib::Instrument::calculate(), gamma2_, and QL_REQUIRE.
Referenced by MargrabeOptionTest::testEuroExchangeTwoAssets(), and MargrabeOptionTest::testGreeks().
{
        calculate();
        QL_REQUIRE(gamma2_ != Null<Real>(), "gamma2 not provided");
        return gamma2_;
    }
void QuantLib::MargrabeOption::setupArguments (PricingEngine::arguments *) const [virtual]
When a derived argument structure is defined for an instrument, this method should be overridden to fill it. This is mandatory in case a pricing engine is used.
Reimplemented from QuantLib::MultiAssetOption.
Definition at line 56 of file margrabeoption.cpp.
References QuantLib::MargrabeOption::arguments::Q1, Q1_, QuantLib::MargrabeOption::arguments::Q2, Q2_, and QL_REQUIRE.
{
        MultiAssetOption::setupArguments(args);
        MargrabeOption::arguments* moreArgs =
            dynamic_cast<MargrabeOption::arguments*>(args);
        QL_REQUIRE(moreArgs != 0,
                   "wrong argument type");
        moreArgs->Q1 = Q1_;
        moreArgs->Q2 = Q2_;
    }
Member Data Documentation
Real QuantLib::MargrabeOption::delta1_ [mutable, protected]
Definition at line 54 of file margrabeoption.hpp.
Referenced by delta1(), and fetchResults().
Real QuantLib::MargrabeOption::delta2_ [mutable, protected]
Definition at line 54 of file margrabeoption.hpp.
Referenced by delta2(), and fetchResults().
Real QuantLib::MargrabeOption::gamma1_ [mutable, protected]
Definition at line 54 of file margrabeoption.hpp.
Referenced by fetchResults(), and gamma1().
Real QuantLib::MargrabeOption::gamma2_ [mutable, protected]
Definition at line 54 of file margrabeoption.hpp.
Referenced by fetchResults(), and gamma2().
Integer QuantLib::MargrabeOption::Q1_ [protected]
Definition at line 52 of file margrabeoption.hpp.
Referenced by setupArguments().
Integer QuantLib::MargrabeOption::Q2_ [protected]
Definition at line 53 of file margrabeoption.hpp.
Referenced by setupArguments().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/exoticoptions/margrabeoption.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/exoticoptions/margrabeoption.cpp