QuantLib: QuantLib::RangeAccrualPricerByBgm Class Reference
QuantLib::RangeAccrualPricerByBgm Class Reference
#include <rangeaccrual.hpp>
Public Member Functions
RangeAccrualPricerByBgm (Real correlation, const boost::shared_ptr< SmileSection > &smilesOnExpiry, const boost::shared_ptr< SmileSection > &smilesOnPayment, bool withSmile, bool byCallSpread)
Observer interface
virtual Real swapletPrice () const
Protected Member Functions
Real drift (Real U, Real lambdaS, Real lambdaT, Real correlation) const
Real derDriftDerLambdaS (Real U, Real lambdaS, Real lambdaT, Real correlation) const
Real derDriftDerLambdaT (Real U, Real lambdaS, Real lambdaT, Real correlation) const
Real lambda (Real U, Real lambdaS, Real lambdaT) const
Real derLambdaDerLambdaS (Real U) const
Real derLambdaDerLambdaT (Real U) const
std::vector< Real > driftsOverPeriod (Real U, Real lambdaS, Real lambdaT, Real correlation) const
std::vector< Real > lambdasOverPeriod (Real U, Real lambdaS, Real lambdaT) const
Real digitalRangePrice (Real lowerTrigger, Real upperTrigger, Real initialValue, Real expiry, Real deflator) const
Real digitalPrice (Real strike, Real initialValue, Real expiry, Real deflator) const
Real digitalPriceWithoutSmile (Real strike, Real initialValue, Real expiry, Real deflator) const
Real digitalPriceWithSmile (Real strike, Real initialValue, Real expiry, Real deflator) const
Real callSpreadPrice (Real previousInitialValue, Real nextInitialValue, Real previousStrike, Real nextStrike, Real deflator, Real previousVariance, Real nextVariance) const
Real smileCorrection (Real strike, Real initialValue, Real expiry, Real deflator) const
Private Attributes
Real correlation_
bool withSmile_
bool byCallSpread_
boost::shared_ptr< SmileSection > smilesOnExpiry_
boost::shared_ptr< SmileSection > smilesOnPayment_
Real eps_
Detailed Description
Definition at line 125 of file rangeaccrual.hpp.
Constructor & Destructor Documentation
QuantLib::RangeAccrualPricerByBgm::RangeAccrualPricerByBgm (Real correlation, const boost::shared_ptr< SmileSection > & smilesOnExpiry, const boost::shared_ptr< SmileSection > & smilesOnPayment, bool withSmile, bool byCallSpread)
Definition at line 168 of file rangeaccrual.cpp.
    : correlation_(correlation),
      withSmile_(withSmile),
      byCallSpread_(byCallSpread),
      smilesOnExpiry_(smilesOnExpiry),
      smilesOnPayment_(smilesOnPayment),
      eps_(1.0e-8) {
    }
Member Function Documentation
Real QuantLib::RangeAccrualPricerByBgm::callSpreadPrice (Real previousInitialValue, Real nextInitialValue, Real previousStrike, Real nextStrike, Real deflator, Real previousVariance, Real nextVariance) const [protected]
Definition at line 503 of file rangeaccrual.cpp.
References QuantLib::blackFormula(), QuantLib::Option::Call, and QL_ENSURE.
Referenced by digitalPriceWithSmile().
{
         const Real nextCall =
            blackFormula(Option::Call, nextStrike, nextForward, std::sqrt(nextVariance), deflator);
         const Real previousCall =
            blackFormula(Option::Call, previousStrike, previousForward, std::sqrt(previousVariance), deflator);
         QL_ENSURE(nextCall <previousCall,"RangeAccrualPricerByBgm::callSpreadPrice: nextCall > previousCall"
            "\n nextCall: strike :" << nextStrike << "; variance: " << nextVariance <<
            " adjusted initial value " << nextForward <<
            "\n previousCall: strike :" << previousStrike << "; variance: " << previousVariance <<
            " adjusted initial value " << previousForward );
         const Real result = (previousCall-nextCall)/(nextStrike-previousStrike);
         return result;
    }
Real QuantLib::RangeAccrualPricerByBgm::derDriftDerLambdaS (Real U, Real lambdaS, Real lambdaT, Real correlation) const [protected]
Definition at line 268 of file rangeaccrual.cpp.
References QuantLib::RangeAccrualPricer::accrualFactor_, QuantLib::RangeAccrualPricer::endTime_, QuantLib::RangeAccrualPricer::initialValues_, and QuantLib::RangeAccrualPricer::startTime_.
{
        Real result;
        const Real p = (U-startTime_)/accrualFactor_;
        const Real q = (endTime_-U)/accrualFactor_;
        const Real L0T = initialValues_.back();
        const Real driftBeforeFixing =
                p*accrualFactor_*L0T/(1.+L0T*accrualFactor_)*(q*lambdaT*correlation) +
                2*q*lambdaS + p*lambdaT*correlation;
        const Real driftAfterFixing = 0.;
        if(startTime_ > 0){result = driftBeforeFixing;}
        else {result = driftAfterFixing;}
        return result;
    }
Real QuantLib::RangeAccrualPricerByBgm::derDriftDerLambdaT (Real U, Real lambdaS, Real lambdaT, Real correlation) const [protected]
Definition at line 299 of file rangeaccrual.cpp.
References QuantLib::RangeAccrualPricer::accrualFactor_, QuantLib::RangeAccrualPricer::endTime_, QuantLib::RangeAccrualPricer::initialValues_, and QuantLib::RangeAccrualPricer::startTime_.
{
        Real result;
        const Real p = (U-startTime_)/accrualFactor_;
        const Real q = (endTime_-U)/accrualFactor_;
        const Real L0T = initialValues_.back();
        const Real driftBeforeFixing =
                p*accrualFactor_*L0T/(1.+L0T*accrualFactor_)*(2*p*lambdaT + q*lambdaS*correlation) +
                + p*lambdaS*correlation;
        const Real driftAfterFixing = (p*accrualFactor_*L0T/(1.+L0T*accrualFactor_)-0.5)*2*lambdaT;
        if(startTime_ > 0){result = driftBeforeFixing;}
        else {result = driftAfterFixing;}
        return result;
    }
Real QuantLib::RangeAccrualPricerByBgm::derLambdaDerLambdaS (Real U) const [protected]
Definition at line 289 of file rangeaccrual.cpp.
References QuantLib::RangeAccrualPricer::accrualFactor_, QuantLib::RangeAccrualPricer::endTime_, and QuantLib::RangeAccrualPricer::startTime_.
Referenced by smileCorrection().
{
        if (startTime_>0) {
            Real q = (endTime_-U)/accrualFactor_;
            return q;
        } else
            return 0.0;
    }
Real QuantLib::RangeAccrualPricerByBgm::derLambdaDerLambdaT (Real U) const [protected]
Definition at line 320 of file rangeaccrual.cpp.
References QuantLib::RangeAccrualPricer::accrualFactor_, and QuantLib::RangeAccrualPricer::startTime_.
Referenced by smileCorrection().
{
        if (startTime_>0) {
            Real p = (U-startTime_)/accrualFactor_;
            return p;
        } else
            return 0.0;
    }
Real QuantLib::RangeAccrualPricerByBgm::digitalPrice (Real strike, Real initialValue, Real expiry, Real deflator) const [protected]
Definition at line 344 of file rangeaccrual.cpp.
References digitalPriceWithoutSmile(), digitalPriceWithSmile(), eps_, and withSmile_.
Referenced by digitalRangePrice().
{
        Real result = deflator;
        if(strike>eps_/2){
            if(withSmile_)
                result = digitalPriceWithSmile(strike, initialValue, expiry, deflator);
            else
                result = digitalPriceWithoutSmile(strike, initialValue, expiry, deflator);
        }
        return result;
    }
Real QuantLib::RangeAccrualPricerByBgm::digitalPriceWithoutSmile (Real strike, Real initialValue, Real expiry, Real deflator) const [protected]
Definition at line 358 of file rangeaccrual.cpp.
References correlation_, driftsOverPeriod(), lambdasOverPeriod(), QuantLib::anonymous_namespace{bjerksundstenslandengine.cpp}::phi(), QL_REQUIRE, smilesOnExpiry_, smilesOnPayment_, and QuantLib::RangeAccrualPricer::startTime_.
Referenced by digitalPrice(), and digitalPriceWithSmile().
{
        Real lambdaS = smilesOnExpiry_->volatility(strike);
        Real lambdaT = smilesOnPayment_->volatility(strike);
        std::vector<Real> lambdaU = lambdasOverPeriod(expiry, lambdaS, lambdaT);
        const Real variance =
            startTime_*lambdaU[0]*lambdaU[0]+(expiry-startTime_)*lambdaU[1]*lambdaU[1];
        Real lambdaSATM = smilesOnExpiry_->volatility(initialValue);
        Real lambdaTATM = smilesOnPayment_->volatility(initialValue);
        //drift of Lognormal process (of Libor) "a_U()" nel paper
        std::vector<Real> muU = driftsOverPeriod(expiry, lambdaSATM, lambdaTATM, correlation_);
        const Real adjustment = (startTime_*muU[0]+(expiry-startTime_)*muU[1]);
       Real d2 = (std::log(initialValue/strike) + adjustment - 0.5*variance)/std::sqrt(variance);
       CumulativeNormalDistribution phi;
       const Real result = deflator*phi(d2);
       QL_REQUIRE(result > 0.,
           "RangeAccrualPricerByBgm::digitalPriceWithoutSmile: result< 0. Result:"<<result);
       QL_REQUIRE(result/deflator <= 1.,
            "RangeAccrualPricerByBgm::digitalPriceWithoutSmile: result/deflator > 1. Ratio: "
            << result/deflator << " result: " << result<< " deflator: " << deflator);
        return result;
    }
Real QuantLib::RangeAccrualPricerByBgm::digitalPriceWithSmile (Real strike, Real initialValue, Real expiry, Real deflator) const [protected]
Definition at line 391 of file rangeaccrual.cpp.
References byCallSpread_, callSpreadPrice(), correlation_, digitalPriceWithoutSmile(), driftsOverPeriod(), eps_, lambdasOverPeriod(), QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow(), QL_REQUIRE, smileCorrection(), smilesOnExpiry_, smilesOnPayment_, and QuantLib::RangeAccrualPricer::startTime_.
Referenced by digitalPrice().
{
        Real result;
        if (byCallSpread_) {
            // Previous strike
            const Real previousStrike = strike - eps_/2;
            Real lambdaS = smilesOnExpiry_->volatility(previousStrike);
            Real lambdaT = smilesOnPayment_->volatility(previousStrike);
            //drift of Lognormal process (of Libor) "a_U()" nel paper
            std::vector<Real> lambdaU = lambdasOverPeriod(expiry, lambdaS, lambdaT);
            const Real previousVariance = std::max(startTime_, 0.)*lambdaU[0]*lambdaU[0]+
                         std::min(expiry-startTime_, expiry)*lambdaU[1]*lambdaU[1];
            Real lambdaSATM = smilesOnExpiry_->volatility(initialValue);
            Real lambdaTATM = smilesOnPayment_->volatility(initialValue);
            std::vector<Real> muU = driftsOverPeriod(expiry, lambdaSATM, lambdaTATM, correlation_);
            const Real previousAdjustment = std::exp(std::max(startTime_, 0.)*muU[0] +
                                         std::min(expiry-startTime_, expiry)*muU[1]);
            const Real previousForward = initialValue * previousAdjustment ;
            // Next strike
            const Real nextStrike = strike + eps_/2;
            lambdaS = smilesOnExpiry_->volatility(nextStrike);
            lambdaT = smilesOnPayment_->volatility(nextStrike);
            lambdaU = lambdasOverPeriod(expiry, lambdaS, lambdaT);
            const Real nextVariance = std::max(startTime_, 0.)*lambdaU[0]*lambdaU[0]+
                         std::min(expiry-startTime_, expiry)*lambdaU[1]*lambdaU[1];
            //drift of Lognormal process (of Libor) "a_U()" nel paper
            muU = driftsOverPeriod(expiry, lambdaSATM, lambdaTATM, correlation_);
            const Real nextAdjustment = std::exp(std::max(startTime_, 0.)*muU[0] +
                                         std::min(expiry-startTime_, expiry)*muU[1]);
            const Real nextForward = initialValue * nextAdjustment ;
            result = callSpreadPrice(previousForward,nextForward,previousStrike, nextStrike,
                                                    deflator, previousVariance, nextVariance);
        }
        else{
            result = digitalPriceWithoutSmile(strike, initialValue, expiry, deflator)+
                     smileCorrection(strike, initialValue, expiry, deflator);
        }
        QL_REQUIRE(result > -std::pow(eps_,.5),
            "RangeAccrualPricerByBgm::digitalPriceWithSmile: result< 0 Result:"<<result);
        QL_REQUIRE(result/deflator <=  1.0 + std::pow(eps_,.2),
            "RangeAccrualPricerByBgm::digitalPriceWithSmile: result/deflator > 1. Ratio: "
            << result/deflator << " result: " << result<< " deflator: " << deflator);
        return result;
    }
Real QuantLib::RangeAccrualPricerByBgm::digitalRangePrice (Real lowerTrigger, Real upperTrigger, Real initialValue, Real expiry, Real deflator) const [protected]
Definition at line 330 of file rangeaccrual.cpp.
References digitalPrice(), and QL_REQUIRE.
Referenced by swapletPrice().
{
            const Real lowerPrice = digitalPrice(lowerTrigger, initialValue, expiry, deflator);
            const Real upperPrice = digitalPrice(upperTrigger, initialValue, expiry, deflator);
            const Real result =  lowerPrice - upperPrice;
            QL_REQUIRE(result >0.,
                "RangeAccrualPricerByBgm::digitalRangePrice:\n digitalPrice("<<upperTrigger<<
                "): "<<upperPrice<<" >  digitalPrice("<<lowerTrigger<<"): "<<lowerPrice);
            return result;
    }
Real QuantLib::RangeAccrualPricerByBgm::drift (Real U, Real lambdaS, Real lambdaT, Real correlation) const [protected]
Definition at line 232 of file rangeaccrual.cpp.
References QuantLib::RangeAccrualPricer::accrualFactor_, QuantLib::RangeAccrualPricer::endTime_, QuantLib::RangeAccrualPricer::initialValues_, and QuantLib::RangeAccrualPricer::startTime_.
{
        Real result;
        const Real p = (U-startTime_)/accrualFactor_;
        const Real q = (endTime_-U)/accrualFactor_;
        const Real L0T = initialValues_.back();
        const Real driftBeforeFixing =
                p*accrualFactor_*L0T/(1.+L0T*accrualFactor_)*(p*lambdaT*lambdaT + q*lambdaS*lambdaT*correlation) +
                q*lambdaS*lambdaS + p*lambdaS*lambdaT*correlation;
        const Real driftAfterFixing = (p*accrualFactor_*L0T/(1.+L0T*accrualFactor_)-0.5)*lambdaT*lambdaT;
        if(startTime_ > 0){result = driftBeforeFixing;}
        else {result = driftAfterFixing;}
        return result;
    }
std::vector< Real > QuantLib::RangeAccrualPricerByBgm::driftsOverPeriod (Real U, Real lambdaS, Real lambdaT, Real correlation) const [protected]
Definition at line 194 of file rangeaccrual.cpp.
References QuantLib::RangeAccrualPricer::accrualFactor_, QuantLib::RangeAccrualPricer::endTime_, QuantLib::RangeAccrualPricer::initialValues_, lambda(), and QuantLib::RangeAccrualPricer::startTime_.
Referenced by digitalPriceWithoutSmile(), digitalPriceWithSmile(), and smileCorrection().
{
        std::vector<Real> result;
        const Real p = (U-startTime_)/accrualFactor_;
        const Real q = (endTime_-U)/accrualFactor_;
        const Real L0T = initialValues_.back();
        const Real driftBeforeFixing =
                p*accrualFactor_*L0T/(1.+L0T*accrualFactor_)*(p*lambdaT*lambdaT + q*lambdaS*lambdaT*correlation) +
                q*lambdaS*lambdaS + p*lambdaS*lambdaT*correlation
                -0.5*lambda(U,lambdaS,lambdaT)*lambda(U,lambdaS,lambdaT);
        const Real driftAfterFixing = (p*accrualFactor_*L0T/(1.+L0T*accrualFactor_)-0.5)*lambdaT*lambdaT;
        result.push_back(driftBeforeFixing);
        result.push_back(driftAfterFixing);
        return result;
    }
Real QuantLib::RangeAccrualPricerByBgm::lambda (Real U, Real lambdaS, Real lambdaT) const [protected]
Definition at line 253 of file rangeaccrual.cpp.
References QuantLib::RangeAccrualPricer::accrualFactor_, QuantLib::RangeAccrualPricer::endTime_, and QuantLib::RangeAccrualPricer::startTime_.
Referenced by driftsOverPeriod().
{
        Real result;
        const Real p = (U-startTime_)/accrualFactor_;
        const Real q = (endTime_-U)/accrualFactor_;
        if(startTime_ > 0){result = q*lambdaS + p*lambdaT;}
        else {result = lambdaT;}
        return result;
    }
std::vector< Real > QuantLib::RangeAccrualPricerByBgm::lambdasOverPeriod (Real U, Real lambdaS, Real lambdaT) const [protected]
Definition at line 216 of file rangeaccrual.cpp.
References QuantLib::RangeAccrualPricer::accrualFactor_, QuantLib::RangeAccrualPricer::endTime_, and QuantLib::RangeAccrualPricer::startTime_.
Referenced by digitalPriceWithoutSmile(), digitalPriceWithSmile(), and smileCorrection().
{
        std::vector<Real> result;
        const Real p = (U-startTime_)/accrualFactor_;
        const Real q = (endTime_-U)/accrualFactor_;
        const Real lambdaBeforeFixing = q*lambdaS + p*lambdaT;
        const Real lambdaAfterFixing = lambdaT;
        result.push_back(lambdaBeforeFixing);
        result.push_back(lambdaAfterFixing);
        return result;
    }
Real QuantLib::RangeAccrualPricerByBgm::smileCorrection (Real strike, Real initialValue, Real expiry, Real deflator) const [protected]
Definition at line 447 of file rangeaccrual.cpp.
References correlation_, derLambdaDerLambdaS(), derLambdaDerLambdaT(), driftsOverPeriod(), eps_, lambdasOverPeriod(), QuantLib::anonymous_namespace{bjerksundstenslandengine.cpp}::phi(), QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow(), QL_REQUIRE, smilesOnExpiry_, smilesOnPayment_, and QuantLib::RangeAccrualPricer::startTime_.
Referenced by digitalPriceWithSmile().
{
        const Real previousStrike = strike - eps_/2;
        const Real nextStrike = strike + eps_/2;
        const Real derSmileS = (smilesOnExpiry_->volatility(nextStrike)-
                                 smilesOnExpiry_->volatility(previousStrike))/eps_;
        const Real derSmileT = (smilesOnPayment_->volatility(nextStrike)-
                                 smilesOnPayment_->volatility(previousStrike))/eps_;
        Real lambdaS = smilesOnExpiry_->volatility(strike);
        Real lambdaT = smilesOnPayment_->volatility(strike);
        //Real lambdaU = lambda(expiry, lambdaS, lambdaT);
        Real derLambdaDerK = derLambdaDerLambdaS(expiry) * derSmileS +
                             derLambdaDerLambdaT(expiry) * derSmileT;
        //Real derDriftDerK = derDriftDerLambdaS(expiry, lambdaS, lambdaT, correlation_)*derSmileS +
        //                      derDriftDerLambdaT(expiry, lambdaS, lambdaT, correlation_)*derSmileT +
        //                      lambdaU * derLambdaDerK;
        Real lambdaSATM = smilesOnExpiry_->volatility(forward);
        Real lambdaTATM = smilesOnPayment_->volatility(forward);
        std::vector<Real> lambdasOverPeriodU = lambdasOverPeriod(expiry, lambdaS, lambdaT);
        //drift of Lognormal process (of Libor) "a_U()" nel paper
        std::vector<Real> muU = driftsOverPeriod(expiry, lambdaSATM, lambdaTATM, correlation_);
        const Real variance = std::max(startTime_, 0.)*lambdasOverPeriodU[0]*lambdasOverPeriodU[0] +
                       std::min(expiry-startTime_, expiry)*lambdasOverPeriodU[1]*lambdasOverPeriodU[1];
        const Real forwardAdjustment = std::exp(std::max(startTime_, 0.)*muU[0] +
                                         std::min(expiry-startTime_, expiry)*muU[1]);
        const Real forwardAdjusted = forward * forwardAdjustment;
        const Real d1 = (std::log(forwardAdjusted/strike)+0.5*variance)/std::sqrt(variance);
        const Real sqrtOfTimeToExpiry = (std::max(startTime_, 0.)*lambdasOverPeriodU[0] +
                                std::min(expiry-startTime_, expiry)*lambdasOverPeriodU[1])*
                                (1./std::sqrt(variance));
        CumulativeNormalDistribution phi;
        NormalDistribution psi;
        Real result = - forwardAdjusted*psi(d1)*sqrtOfTimeToExpiry*derLambdaDerK ;
                       // - forwardAdjusted*phi(d1)*expiry*derDriftDerK;
        result *= deflator;
        QL_REQUIRE(std::fabs(result/deflator) <= 1.0 + std::pow(eps_,.2),
            "RangeAccrualPricerByBgm::smileCorrection: abs(result/deflator) > 1. Ratio: "
            << result/deflator << " result: " << result<< " deflator: " << deflator);
        return result;
    }
Real QuantLib::RangeAccrualPricerByBgm::swapletPrice () const [virtual]
Implements QuantLib::FloatingRateCouponPricer.
Definition at line 182 of file rangeaccrual.cpp.
References QuantLib::RangeAccrualPricer::accrualFactor_, digitalRangePrice(), QuantLib::RangeAccrualPricer::discount_, QuantLib::RangeAccrualPricer::gearing_, QuantLib::RangeAccrualPricer::initialValues_, QuantLib::RangeAccrualPricer::lowerTrigger_, QuantLib::RangeAccrualPricer::observationsNo_, QuantLib::RangeAccrualPricer::observationTimes_, QuantLib::RangeAccrualPricer::spreadLegValue_, and QuantLib::RangeAccrualPricer::upperTrigger_.
{
        Real result = 0.;
        const Real deflator = discount_*initialValues_[0];
        for(Size i=0;i<observationsNo_;i++){
            Real digitalFloater = digitalRangePrice(lowerTrigger_, upperTrigger_,initialValues_[i+1],
                                                     observationTimes_[i], deflator);
            result += digitalFloater;
        }
        return gearing_ *(result*accrualFactor_/observationsNo_)+ spreadLegValue_;
    }
Member Data Documentation
bool QuantLib::RangeAccrualPricerByBgm::byCallSpread_ [private]
Definition at line 193 of file rangeaccrual.hpp.
Referenced by digitalPriceWithSmile().
Real QuantLib::RangeAccrualPricerByBgm::correlation_ [private]
Definition at line 191 of file rangeaccrual.hpp.
Referenced by digitalPriceWithoutSmile(), digitalPriceWithSmile(), and smileCorrection().
Real QuantLib::RangeAccrualPricerByBgm::eps_ [private]
Definition at line 197 of file rangeaccrual.hpp.
Referenced by digitalPrice(), digitalPriceWithSmile(), and smileCorrection().
boost::shared_ptr<SmileSection> QuantLib::RangeAccrualPricerByBgm::smilesOnExpiry_ [private]
Definition at line 195 of file rangeaccrual.hpp.
Referenced by digitalPriceWithoutSmile(), digitalPriceWithSmile(), and smileCorrection().
boost::shared_ptr<SmileSection> QuantLib::RangeAccrualPricerByBgm::smilesOnPayment_ [private]
Definition at line 196 of file rangeaccrual.hpp.
Referenced by digitalPriceWithoutSmile(), digitalPriceWithSmile(), and smileCorrection().
bool QuantLib::RangeAccrualPricerByBgm::withSmile_ [private]
Definition at line 192 of file rangeaccrual.hpp.
Referenced by digitalPrice().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/rangeaccrual.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/rangeaccrual.cpp