QuantLib: QuantLib::AnalyticHestonEngine::Integration Class Reference
QuantLib::AnalyticHestonEngine::Integration Class Reference
#include <analytichestonengine.hpp>
Public Member Functions
Real calculate (Real c_inf, const boost::function1< Real, Real > &f) const
Size numberOfEvaluations () const
bool isAdaptiveIntegration () const
Static Public Member Functions
static Integration gaussLaguerre (Size integrationOrder=128)
static Integration gaussLegendre (Size integrationOrder=128)
static Integration gaussChebyshev (Size integrationOrder=128)
static Integration gaussChebyshev2nd (Size integrationOrder=128)
static Integration gaussLobatto (Real relTolerance, Real absTolerance, Size maxEvaluations=1000)
static Integration gaussKronrod (Real absTolerance, Size maxEvaluations=1000)
static Integration simpson (Real absTolerance, Size maxEvaluations=1000)
static Integration trapezoid (Real absTolerance, Size maxEvaluations=1000)
Private Types
enum Algorithm {
GaussLobatto, GaussKronrod, Simpson, Trapezoid,
GaussLaguerre, GaussLegendre, GaussChebyshev, GaussChebyshev2nd
}
Private Member Functions
Integration (Algorithm intAlgo, const boost::shared_ptr< GaussianQuadrature > &quadrature)
Integration (Algorithm intAlgo, const boost::shared_ptr< Integrator > &integrator)
Private Attributes
const Algorithm intAlgo_
const boost::shared_ptr
< Integrator > integrator_
const boost::shared_ptr
< GaussianQuadrature > gaussianQuadrature_
Detailed Description
Definition at line 140 of file analytichestonengine.hpp.
Member Enumeration Documentation
enum QuantLib::AnalyticHestonEngine::Integration::Algorithm [private]
Enumerator:
GaussLobatto
GaussKronrod
Simpson
Trapezoid
GaussLaguerre
GaussLegendre
GaussChebyshev
GaussChebyshev2nd
Definition at line 170 of file analytichestonengine.hpp.
            { GaussLobatto, GaussKronrod, Simpson, Trapezoid,
              GaussLaguerre, GaussLegendre,
              GaussChebyshev, GaussChebyshev2nd };
Constructor & Destructor Documentation
QuantLib::AnalyticHestonEngine::Integration::Integration (Algorithm intAlgo, const boost::shared_ptr< GaussianQuadrature > & quadrature) [private]
Definition at line 428 of file analytichestonengine.cpp.
    : intAlgo_(intAlgo),
      gaussianQuadrature_(gaussianQuadrature) { }
QuantLib::AnalyticHestonEngine::Integration::Integration (Algorithm intAlgo, const boost::shared_ptr< Integrator > & integrator) [private]
Definition at line 422 of file analytichestonengine.cpp.
    : intAlgo_(intAlgo),
      integrator_(integrator) { }
Member Function Documentation
Real QuantLib::AnalyticHestonEngine::Integration::calculate (Real c_inf, const boost::function1< Real, Real > & f) const
Definition at line 521 of file analytichestonengine.cpp.
References anonymous_namespace{interpolations.cpp}::f(), QL_EPSILON, and QL_FAIL.
Referenced by QuantLib::AnalyticHestonEngine::doCalculation().
{
        Real retVal;
        switch(intAlgo_) {
          case GaussLaguerre:
            retVal = gaussianQuadrature_->operator()(f);
            break;
          case GaussLegendre:
          case GaussChebyshev:
          case GaussChebyshev2nd:
            retVal = gaussianQuadrature_->operator()(
                boost::function1<Real, Real>(
                    if_then_else_return ( (boost::lambda::_1+1.0)*c_inf
                                          > QL_EPSILON,
                        boost::lambda::bind(f, -boost::lambda::bind(
                            std::ptr_fun<Real,Real>(std::log),
                            0.5*boost::lambda::_1+0.5 )/c_inf )
                                          /((boost::lambda::_1+1.0)*c_inf),
                        boost::lambda::bind(constant<Real, Real>(0.0),
                                            boost::lambda::_1))));
            break;
          case Simpson:
          case Trapezoid:
          case GaussLobatto:
          case GaussKronrod:
            retVal = integrator_->operator()(
                boost::function1<Real, Real>(
                    if_then_else_return ( boost::lambda::_1*c_inf > QL_EPSILON,
                        boost::lambda::bind(f,-boost::lambda::bind(
                            std::ptr_fun<Real,Real>(std::log),
                            boost::lambda::_1)/c_inf) /(boost::lambda::_1*c_inf),
                        boost::lambda::bind(constant<Real, Real>(0.0),
                                            boost::lambda::_1))),
                0.0, 1.0);
            break;
          default:
              QL_FAIL("unknwon integration algorithm");
        }
        return retVal;
     }
AnalyticHestonEngine::Integration QuantLib::AnalyticHestonEngine::Integration::gaussChebyshev (Size integrationOrder = 128) [static]
Definition at line 489 of file analytichestonengine.cpp.
Referenced by HestonModelTest::testDifferentIntegrals().
{
        return Integration(GaussChebyshev,
                           boost::shared_ptr<GaussianQuadrature>(
                               new GaussChebyshevIntegration(intOrder)));
    }
AnalyticHestonEngine::Integration QuantLib::AnalyticHestonEngine::Integration::gaussChebyshev2nd (Size integrationOrder = 128) [static]
Definition at line 496 of file analytichestonengine.cpp.
Referenced by HestonModelTest::testDifferentIntegrals().
{
        return Integration(GaussChebyshev2nd,
                           boost::shared_ptr<GaussianQuadrature>(
                               new GaussChebyshev2ndIntegration(intOrder)));
    }
AnalyticHestonEngine::Integration QuantLib::AnalyticHestonEngine::Integration::gaussKronrod (Real absTolerance, Size maxEvaluations = 1000) [static]
Definition at line 447 of file analytichestonengine.cpp.
{
        return Integration(GaussKronrod,
                           boost::shared_ptr<Integrator>(
                               new GaussKronrodAdaptive(absTolerance,
                                                        maxEvaluations)));
    }
AnalyticHestonEngine::Integration QuantLib::AnalyticHestonEngine::Integration::gaussLaguerre (Size integrationOrder = 128) [static]
Definition at line 474 of file analytichestonengine.cpp.
References QL_REQUIRE.
Referenced by MarketModelTest::testStochVolForwardsAndOptionlets().
{
        QL_REQUIRE(intOrder <= 192, "maximum integraton order (192) exceeded");
        return Integration(GaussLaguerre,
                           boost::shared_ptr<GaussianQuadrature>(
                               new GaussLaguerreIntegration(intOrder)));
    }
AnalyticHestonEngine::Integration QuantLib::AnalyticHestonEngine::Integration::gaussLegendre (Size integrationOrder = 128) [static]
Definition at line 482 of file analytichestonengine.cpp.
Referenced by HestonModelTest::testDifferentIntegrals().
{
        return Integration(GaussLegendre,
                           boost::shared_ptr<GaussianQuadrature>(
                               new GaussLegendreIntegration(intOrder)));
    }
AnalyticHestonEngine::Integration QuantLib::AnalyticHestonEngine::Integration::gaussLobatto (Real relTolerance, Real absTolerance, Size maxEvaluations = 1000) [static]
Definition at line 435 of file analytichestonengine.cpp.
{
        return Integration(GaussLobatto,
                           boost::shared_ptr<Integrator>(
                               new GaussLobattoIntegral(maxEvaluations,
                                                        absTolerance,
                                                        relTolerance,
                                                        false)));
    }
bool QuantLib::AnalyticHestonEngine::Integration::isAdaptiveIntegration () const
Definition at line 514 of file analytichestonengine.cpp.
Referenced by QuantLib::AnalyticHestonEngine::AnalyticHestonEngine().
{
        return intAlgo_ == GaussLobatto
            || intAlgo_ == GaussKronrod
            || intAlgo_ == Simpson
            || intAlgo_ == Trapezoid;
    }
Size QuantLib::AnalyticHestonEngine::Integration::numberOfEvaluations () const
Definition at line 502 of file analytichestonengine.cpp.
References QL_FAIL.
Referenced by QuantLib::AnalyticHestonEngine::doCalculation().
{
        if (integrator_) {
            return integrator_->numberOfEvaluations();
        }
        else if (gaussianQuadrature_) {
            return gaussianQuadrature_->order();
        }
        else {
            QL_FAIL("neither Integrator nor GaussianQuadrature given");
        }
    }
AnalyticHestonEngine::Integration QuantLib::AnalyticHestonEngine::Integration::simpson (Real absTolerance, Size maxEvaluations = 1000) [static]
Definition at line 456 of file analytichestonengine.cpp.
{
        return Integration(Simpson,
                           boost::shared_ptr<Integrator>(
                               new SimpsonIntegral(absTolerance,
                                                   maxEvaluations)));
    }
AnalyticHestonEngine::Integration QuantLib::AnalyticHestonEngine::Integration::trapezoid (Real absTolerance, Size maxEvaluations = 1000) [static]
Definition at line 465 of file analytichestonengine.cpp.
{
        return Integration(Trapezoid,
                           boost::shared_ptr<Integrator>(
                              new TrapezoidIntegral<Default>(absTolerance,
                                                             maxEvaluations)));
    }
Member Data Documentation
const boost::shared_ptr<GaussianQuadrature> QuantLib::AnalyticHestonEngine::Integration::gaussianQuadrature_ [private]
Definition at line 183 of file analytichestonengine.hpp.
const Algorithm QuantLib::AnalyticHestonEngine::Integration::intAlgo_ [private]
Definition at line 181 of file analytichestonengine.hpp.
const boost::shared_ptr<Integrator> QuantLib::AnalyticHestonEngine::Integration::integrator_ [private]
Definition at line 182 of file analytichestonengine.hpp.
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/vanilla/analytichestonengine.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/vanilla/analytichestonengine.cpp