QuantLib: QuantLib::CmsCouponPricer Class Reference
QuantLib::CmsCouponPricer Class Reference
base pricer for vanilla CMS coupons
#include <couponpricer.hpp>
Public Member Functions
CmsCouponPricer (const Handle< SwaptionVolatilityStructure > &v=Handle< SwaptionVolatilityStructure >())
Handle
< SwaptionVolatilityStructure > swaptionVolatility () const
void setSwaptionVolatility (const Handle< SwaptionVolatilityStructure > &v=Handle< SwaptionVolatilityStructure >())
Private Attributes
Handle
< SwaptionVolatilityStructure > swaptionVol_
Detailed Description
base pricer for vanilla CMS coupons
Definition at line 115 of file couponpricer.hpp.
Constructor & Destructor Documentation
QuantLib::CmsCouponPricer::CmsCouponPricer (const Handle< SwaptionVolatilityStructure > & v = Handle<SwaptionVolatilityStructure>()) [inline]
Definition at line 117 of file couponpricer.hpp.
References QuantLib::Observer::registerWith(), and swaptionVol_.
        : swaptionVol_(v) { registerWith(swaptionVol_); }
Member Function Documentation
void QuantLib::CmsCouponPricer::setSwaptionVolatility (const Handle< SwaptionVolatilityStructure > & v = Handle<SwaptionVolatilityStructure>()) [inline]
Definition at line 124 of file couponpricer.hpp.
References QuantLib::Observer::registerWith(), swaptionVol_, QuantLib::Observer::unregisterWith(), QuantLib::FloatingRateCouponPricer::update(), and anonymous_namespace{perturbativebarrieroptionengine.cpp}::v().
{
            unregisterWith(swaptionVol_);
            swaptionVol_ = v;
            registerWith(swaptionVol_);
            update();
        }
Handle<SwaptionVolatilityStructure> QuantLib::CmsCouponPricer::swaptionVolatility () const [inline]
Definition at line 121 of file couponpricer.hpp.
References swaptionVol_.
Referenced by QuantLib::HaganPricer::initialize(), QuantLib::AnalyticHaganPricer::optionletPrice(), QuantLib::NumericHaganPricer::resetUpperLimit(), and QuantLib::AnalyticHaganPricer::swapletPrice().
{
            return swaptionVol_;
        }
Member Data Documentation
Handle<SwaptionVolatilityStructure> QuantLib::CmsCouponPricer::swaptionVol_ [private]
Definition at line 133 of file couponpricer.hpp.
Referenced by CmsCouponPricer(), setSwaptionVolatility(), and swaptionVolatility().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/cashflows/couponpricer.hpp