QuantLib: QuantLib::AmericanBasketPathPricer Class Reference
QuantLib::AmericanBasketPathPricer Class Reference
#include <mcamericanbasketengine.hpp>
Public Member Functions
AmericanBasketPathPricer (Size assetNumber, const boost::shared_ptr< Payoff > &payoff, Size polynomOrder=2, LsmBasisSystem::PolynomType polynomType=LsmBasisSystem::Monomial)
Array state (const MultiPath &path, Size t) const
Real operator() (const MultiPath &path, Size t) const
std::vector< boost::function1
< Real, Array > > basisSystem () const
Protected Member Functions
Real payoff (const Array &state) const
Protected Attributes
const Size assetNumber_
const boost::shared_ptr< Payoff > payoff_
Real scalingValue_
std::vector< boost::function1
< Real, Array > > v_
Detailed Description
Definition at line 94 of file mcamericanbasketengine.hpp.
Constructor & Destructor Documentation
QuantLib::AmericanBasketPathPricer::AmericanBasketPathPricer (Size assetNumber, const boost::shared_ptr< Payoff > & payoff, Size polynomOrder = 2, LsmBasisSystem::PolynomType polynomType = LsmBasisSystem::Monomial)
Definition at line 30 of file mcamericanbasketengine.cpp.
References QuantLib::LsmBasisSystem::Chebyshev2nd, QuantLib::LsmBasisSystem::Hermite, QuantLib::LsmBasisSystem::Hyperbolic, QuantLib::LsmBasisSystem::Laguerre, QuantLib::LsmBasisSystem::Monomial, payoff(), payoff_, QL_REQUIRE, scalingValue_, and v_.
    : assetNumber_ (assetNumber),
      payoff_      (payoff),
      scalingValue_(1.0),
      v_           (LsmBasisSystem::multiPathBasisSystem(assetNumber_,
                                                         polynomOrder,
                                                         polynomType)) {
        QL_REQUIRE(   polynomType == LsmBasisSystem::Monomial
                   || polynomType == LsmBasisSystem::Laguerre
                   || polynomType == LsmBasisSystem::Hermite
                   || polynomType == LsmBasisSystem::Hyperbolic
                   || polynomType == LsmBasisSystem::Chebyshev2nd,
                   "insufficient polynom type");
        const boost::shared_ptr<BasketPayoff> basketPayoff
            = boost::dynamic_pointer_cast<BasketPayoff>(payoff_);
        QL_REQUIRE(basketPayoff, "payoff not a basket payoff");
        const boost::shared_ptr<StrikedTypePayoff> strikePayoff
            = boost::dynamic_pointer_cast<StrikedTypePayoff>(basketPayoff->basePayoff());
        if (strikePayoff) {
            scalingValue_/=strikePayoff->strike();
        }
        v_.push_back(boost::bind(&AmericanBasketPathPricer::payoff,
                                 this, _1));
    }
Member Function Documentation
std::vector< boost::function1< Real, Array > > QuantLib::AmericanBasketPathPricer::basisSystem () const [virtual]
Implements QuantLib::EarlyExercisePathPricer< MultiPath >.
Definition at line 89 of file mcamericanbasketengine.cpp.
References v_.
{
        return v_;
    }
Real QuantLib::AmericanBasketPathPricer::operator() (const MultiPath & path, Size t) const [virtual]
Implements QuantLib::EarlyExercisePathPricer< MultiPath >.
Definition at line 83 of file mcamericanbasketengine.cpp.
References payoff(), and state().
{
        return this->payoff(this->state(path, t));
    }
Real QuantLib::AmericanBasketPathPricer::payoff (const Array & state) const [protected]
Definition at line 74 of file mcamericanbasketengine.cpp.
References payoff_, QL_REQUIRE, and scalingValue_.
Referenced by AmericanBasketPathPricer(), and operator()().
{
        const boost::shared_ptr<BasketPayoff> basketPayoff
            = boost::dynamic_pointer_cast<BasketPayoff>(payoff_);
        QL_REQUIRE(basketPayoff, "payoff not a basket payoff");
        Real value = basketPayoff->accumulate(state);
        return (*payoff_)(value/scalingValue_);
    }
Array QuantLib::AmericanBasketPathPricer::state (const MultiPath & path, Size t) const [virtual]
Implements QuantLib::EarlyExercisePathPricer< MultiPath >.
Definition at line 62 of file mcamericanbasketengine.cpp.
References QuantLib::MultiPath::assetNumber(), assetNumber_, QL_REQUIRE, scalingValue_, and anonymous_namespace{quantlibbenchmark.cpp}::t.
Referenced by operator()().
{
        QL_REQUIRE(path.assetNumber() == assetNumber_, "invalid multipath");
        Array tmp(assetNumber_);
        for (Size i=0; i<assetNumber_; ++i) {
            tmp[i] = path[i][t]*scalingValue_;
        }
        return tmp;
    }
Member Data Documentation
const Size QuantLib::AmericanBasketPathPricer::assetNumber_ [protected]
Definition at line 111 of file mcamericanbasketengine.hpp.
Referenced by state().
const boost::shared_ptr<Payoff> QuantLib::AmericanBasketPathPricer::payoff_ [protected]
Definition at line 112 of file mcamericanbasketengine.hpp.
Referenced by AmericanBasketPathPricer(), and payoff().
Real QuantLib::AmericanBasketPathPricer::scalingValue_ [protected]
Definition at line 114 of file mcamericanbasketengine.hpp.
Referenced by AmericanBasketPathPricer(), payoff(), and state().
std::vector<boost::function1<Real, Array> > QuantLib::AmericanBasketPathPricer::v_ [protected]
Definition at line 115 of file mcamericanbasketengine.hpp.
Referenced by AmericanBasketPathPricer(), and basisSystem().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/basket/mcamericanbasketengine.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/basket/mcamericanbasketengine.cpp