QuantLib: QuantLib::BlackAtmVolCurve Class Reference
QuantLib::BlackAtmVolCurve Class Reference
Black at-the-money (no-smile) volatility curve.
#include <blackatmvolcurve.hpp>
Public Member Functions
virtual ~BlackAtmVolCurve ()
Constructors
See the TermStructure documentation for issues regarding constructors.
BlackAtmVolCurve (const Calendar &cal, BusinessDayConvention bdc=Following, const DayCounter &dc=DayCounter())
BlackAtmVolCurve (BusinessDayConvention bdc=Following, const DayCounter &dc=DayCounter())
default constructor
BlackAtmVolCurve (const Date &referenceDate, const Calendar &cal=Calendar(), BusinessDayConvention bdc=Following, const DayCounter &dc=DayCounter())
initialize with a fixed reference date
BlackAtmVolCurve (Natural settlementDays, const Calendar &, BusinessDayConvention bdc=Following, const DayCounter &dc=DayCounter())
calculate the reference date based on the global evaluation date
Black at-the-money spot volatility
Volatility atmVol (const Period &optionTenor, bool extrapolate=false) const
spot at-the-money volatility
Volatility atmVol (const Date &maturity, bool extrapolate=false) const
spot at-the-money volatility
Volatility atmVol (Time maturity, bool extrapolate=false) const
spot at-the-money volatility
Real atmVariance (const Period &optionTenor, bool extrapolate=false) const
spot at-the-money variance
Real atmVariance (const Date &maturity, bool extrapolate=false) const
spot at-the-money variance
Real atmVariance (Time maturity, bool extrapolate=false) const
spot at-the-money variance
Visitability
virtual void accept (AcyclicVisitor &)
Protected Member Functions
Calculations
These methods must be implemented in derived classes to perform the actual volatility calculations. When they are called, range check has already been performed; therefore, they must assume that extrapolation is required.
virtual Real atmVarianceImpl (Time t) const =0
spot at-the-money variance calculation
virtual Volatility atmVolImpl (Time t) const =0
spot at-the-money volatility calculation
Detailed Description
Black at-the-money (no-smile) volatility curve.
This abstract class defines the interface of concrete Black at-the-money (no-smile) volatility curves which will be derived from this one.
Volatilities are assumed to be expressed on an annual basis.
Definition at line 40 of file blackatmvolcurve.hpp.
Constructor & Destructor Documentation
QuantLib::BlackAtmVolCurve::BlackAtmVolCurve (const Calendar & cal, BusinessDayConvention bdc = Following, const DayCounter & dc = DayCounter())
Warning:
term structures initialized by means of this constructor must manage their own reference date by overriding the referenceDate() method.
Definition at line 25 of file blackatmvolcurve.cpp.
    : VolatilityTermStructure(cal, bdc, dc) {}
QuantLib::BlackAtmVolCurve::BlackAtmVolCurve (BusinessDayConvention bdc = Following, const DayCounter & dc = DayCounter())
default constructor
Warning:
term structures initialized by means of this constructor must manage their own reference date by overriding the referenceDate() method.
Definition at line 31 of file blackatmvolcurve.cpp.
    : VolatilityTermStructure(bdc, dc) {}
QuantLib::BlackAtmVolCurve::BlackAtmVolCurve (const Date & referenceDate, const Calendar & cal = Calendar(), BusinessDayConvention bdc = Following, const DayCounter & dc = DayCounter())
initialize with a fixed reference date
Definition at line 35 of file blackatmvolcurve.cpp.
    : VolatilityTermStructure(refDate, cal, bdc, dc) {}
QuantLib::BlackAtmVolCurve::BlackAtmVolCurve (Natural settlementDays, const Calendar & cal, BusinessDayConvention bdc = Following, const DayCounter & dc = DayCounter())
calculate the reference date based on the global evaluation date
Definition at line 41 of file blackatmvolcurve.cpp.
    : VolatilityTermStructure(settlDays, cal, bdc, dc) {}
virtual QuantLib::BlackAtmVolCurve::~BlackAtmVolCurve () [inline, virtual]
Definition at line 74 of file blackatmvolcurve.hpp.
{}
Member Function Documentation
void QuantLib::BlackAtmVolCurve::accept (AcyclicVisitor & v) [virtual]
Reimplemented in QuantLib::EquityFXVolSurface, QuantLib::BlackVolSurface, QuantLib::AbcdAtmVolCurve, QuantLib::InterestRateVolSurface, and QuantLib::SabrVolSurface.
Definition at line 83 of file blackatmvolcurve.cpp.
References QL_FAIL, anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and QuantLib::Visitor< T >::visit().
{
        Visitor<BlackAtmVolCurve>* v1 =
            dynamic_cast<Visitor<BlackAtmVolCurve>*>(&v);
        if (v1 != 0)
            v1->visit(*this);
        else
            QL_FAIL("not a BlackAtmVolCurve visitor");
    }
Real QuantLib::BlackAtmVolCurve::atmVariance (const Period & optionTenor, bool extrapolate = false) const
spot at-the-money variance
Definition at line 65 of file blackatmvolcurve.cpp.
References anonymous_namespace{marketmodel.cpp}::d, and QuantLib::VolatilityTermStructure::optionDateFromTenor().
Referenced by QuantLib::EquityFXVolSurface::atmForwardVariance(), and atmVariance().
{
        Date d = optionDateFromTenor(optionTenor);
        return atmVariance(d, extrapolate);
    }
Real QuantLib::BlackAtmVolCurve::atmVariance (const Date & maturity, bool extrapolate = false) const
spot at-the-money variance
Definition at line 71 of file blackatmvolcurve.cpp.
References atmVariance(), anonymous_namespace{quantlibbenchmark.cpp}::t, and QuantLib::TermStructure::timeFromReference().
{
        Time t = timeFromReference(d);
        return atmVariance(t, extrapolate);
    }
Real QuantLib::BlackAtmVolCurve::atmVariance (Time maturity, bool extrapolate = false) const
spot at-the-money variance
Definition at line 77 of file blackatmvolcurve.cpp.
References atmVarianceImpl(), and QuantLib::TermStructure::checkRange().
{
        checkRange(t, extrapolate);
        return atmVarianceImpl(t);
    }
virtual Real QuantLib::BlackAtmVolCurve::atmVarianceImpl (Time t) const [protected, pure virtual]
spot at-the-money variance calculation
Implemented in QuantLib::BlackVolSurface, and QuantLib::AbcdAtmVolCurve.
Referenced by atmVariance().
Volatility QuantLib::BlackAtmVolCurve::atmVol (const Period & optionTenor, bool extrapolate = false) const
spot at-the-money volatility
Definition at line 47 of file blackatmvolcurve.cpp.
References anonymous_namespace{marketmodel.cpp}::d, and QuantLib::VolatilityTermStructure::optionDateFromTenor().
Referenced by atmVol().
{
        Date d = optionDateFromTenor(optionTenor);
        return atmVol(d, extrapolate);
    }
Volatility QuantLib::BlackAtmVolCurve::atmVol (const Date & maturity, bool extrapolate = false) const
spot at-the-money volatility
Definition at line 53 of file blackatmvolcurve.cpp.
References atmVol(), anonymous_namespace{quantlibbenchmark.cpp}::t, and QuantLib::TermStructure::timeFromReference().
{
        Time t = timeFromReference(d);
        return atmVol(t, extrapolate);
    }
Volatility QuantLib::BlackAtmVolCurve::atmVol (Time maturity, bool extrapolate = false) const
spot at-the-money volatility
Definition at line 59 of file blackatmvolcurve.cpp.
References atmVolImpl(), and QuantLib::TermStructure::checkRange().
{
        checkRange(t, extrapolate);
        return atmVolImpl(t);
    }
virtual Volatility QuantLib::BlackAtmVolCurve::atmVolImpl (Time t) const [protected, pure virtual]
spot at-the-money volatility calculation
Implemented in QuantLib::BlackVolSurface, and QuantLib::AbcdAtmVolCurve.
Referenced by atmVol().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/volatility/blackatmvolcurve.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/volatility/blackatmvolcurve.cpp