QuantLib: QuantLib::DiscretizedVanillaOption Class Reference
QuantLib::DiscretizedVanillaOption Class Reference
#include <discretizedvanillaoption.hpp>
Public Member Functions
DiscretizedVanillaOption (const VanillaOption::arguments &, const StochasticProcess &process, const TimeGrid &grid=TimeGrid())
void reset (Size size)
std::vector< Time > mandatoryTimes () const
Protected Member Functions
void postAdjustValuesImpl ()
Private Member Functions
void applySpecificCondition ()
Private Attributes
VanillaOption::arguments arguments_
std::vector< Time > stoppingTimes_
Detailed Description
Definition at line 34 of file discretizedvanillaoption.hpp.
Constructor & Destructor Documentation
QuantLib::DiscretizedVanillaOption::DiscretizedVanillaOption (const VanillaOption::arguments & args, const StochasticProcess & process, const TimeGrid & grid = TimeGrid())
Definition at line 26 of file discretizedvanillaoption.cpp.
References QuantLib::TimeGrid::closestTime(), QuantLib::TimeGrid::empty(), QuantLib::Option::arguments::exercise, stoppingTimes_, and QuantLib::StochasticProcess::time().
    : arguments_(args) {
        stoppingTimes_.resize(args.exercise->dates().size());
        for (Size i=0; i<stoppingTimes_.size(); ++i) {
            stoppingTimes_[i] =
                process.time(args.exercise->date(i));
            if (!grid.empty()) {
                // adjust to the given grid
                stoppingTimes_[i] = grid.closestTime(stoppingTimes_[i]);
            }
        }
    }
Member Function Documentation
void QuantLib::DiscretizedVanillaOption::applySpecificCondition () [private]
Definition at line 71 of file discretizedvanillaoption.cpp.
References arguments_, QuantLib::DiscretizedAsset::method(), QuantLib::Option::arguments::payoff, QuantLib::Array::size(), QuantLib::DiscretizedAsset::time(), and QuantLib::DiscretizedAsset::values_.
Referenced by postAdjustValuesImpl().
{
        Array grid = method()->grid(time());
        for (Size j=0; j<values_.size(); j++) {
            values_[j] = std::max(values_[j],
                                  (*arguments_.payoff)(grid[j]));
        }
    }
std::vector<Time> QuantLib::DiscretizedVanillaOption::mandatoryTimes () const [inline, virtual]
This method returns the times at which the numerical method should stop while rolling back the asset. Typical examples include payment times, exercise times and such.
Note:
The returned values are not guaranteed to be sorted.
Implements QuantLib::DiscretizedAsset.
Definition at line 42 of file discretizedvanillaoption.hpp.
References stoppingTimes_.
{
            return stoppingTimes_;
        }
void QuantLib::DiscretizedVanillaOption::postAdjustValuesImpl () [protected, virtual]
This method performs the actual post-adjustment
Reimplemented from QuantLib::DiscretizedAsset.
Definition at line 47 of file discretizedvanillaoption.cpp.
References QuantLib::Exercise::American, applySpecificCondition(), arguments_, QuantLib::Exercise::Bermudan, QuantLib::Exercise::European, QuantLib::Option::arguments::exercise, QuantLib::DiscretizedAsset::isOnTime(), QL_FAIL, stoppingTimes_, and QuantLib::DiscretizedAsset::time().
{
        Time now = time();
        switch (arguments_.exercise->type()) {
          case Exercise::American:
            if (now <= stoppingTimes_[1] &&
                now >= stoppingTimes_[0])
                applySpecificCondition();
            break;
          case Exercise::European:
            if (isOnTime(stoppingTimes_[0]))
                applySpecificCondition();
            break;
          case Exercise::Bermudan:
            for (Size i=0; i<stoppingTimes_.size(); i++) {
                if (isOnTime(stoppingTimes_[i]))
                    applySpecificCondition();
            }
            break;
          default:
            QL_FAIL("invalid option type");
        }
    }
void QuantLib::DiscretizedVanillaOption::reset (Size size) [virtual]
This method should initialize the asset values to an Array of the given size and with values depending on the particular asset.
Implements QuantLib::DiscretizedAsset.
Definition at line 42 of file discretizedvanillaoption.cpp.
References QuantLib::DiscretizedAsset::adjustValues(), and QuantLib::DiscretizedAsset::values_.
{
        values_ = Array(size, 0.0);
        adjustValues();
    }
Member Data Documentation
VanillaOption::arguments QuantLib::DiscretizedVanillaOption::arguments_ [private]
Definition at line 49 of file discretizedvanillaoption.hpp.
Referenced by applySpecificCondition(), and postAdjustValuesImpl().
std::vector<Time> QuantLib::DiscretizedVanillaOption::stoppingTimes_ [private]
Definition at line 50 of file discretizedvanillaoption.hpp.
Referenced by DiscretizedVanillaOption(), mandatoryTimes(), and postAdjustValuesImpl().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/vanilla/discretizedvanillaoption.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/vanilla/discretizedvanillaoption.cpp