QuantLib: QuantLib::Business252::Impl Class Reference
QuantLib::Business252::Impl Class Reference
Public Member Functions
std::string name () const
BigInteger dayCount (const Date &d1, const Date &d2) const
to be overloaded by more complex day counters
Time yearFraction (const Date &d1, const Date &d2, const Date &, const Date &) const
Impl (Calendar c)
Private Attributes
Calendar calendar_
Detailed Description
Definition at line 38 of file business252.hpp.
Constructor & Destructor Documentation
QuantLib::Business252::Impl::Impl (Calendar c) [inline]
Definition at line 49 of file business252.hpp.
References anonymous_namespace{marketmodel.cpp}::c, and calendar_.
{ calendar_ = c; }
Member Function Documentation
BigInteger QuantLib::Business252::Impl::dayCount (const Date & d1, const Date & d2) const [virtual]
to be overloaded by more complex day counters
Reimplemented from QuantLib::DayCounter::Impl.
Definition at line 78 of file business252.cpp.
References QuantLib::anonymous_namespace{business252.cpp}::businessDays(), anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::calendar_, anonymous_namespace{marketmodel.cpp}::d, QuantLib::January, QuantLib::Date::month(), QuantLib::anonymous_namespace{business252.cpp}::monthlyFigures_, QuantLib::Months, QuantLib::anonymous_namespace{business252.cpp}::sameMonth(), QuantLib::anonymous_namespace{business252.cpp}::sameYear(), QuantLib::Date::year(), QuantLib::anonymous_namespace{business252.cpp}::yearlyFigures_, and QuantLib::Years.
{
        if (sameMonth(d1,d2) || d1 >= d2) {
            // we treat the case of d1 > d2 here, since we'd need a
            // second cache to get it right (our cached figures are
            // for first included, last excluded and might have to be
            // changed going the other way.)
            return calendar_.businessDaysBetween(d1, d2);
        } else if (sameYear(d1,d2)) {
            Cache& cache = monthlyFigures_[calendar_.name()];
            BigInteger total = 0;
            Date d;
            // first, we get to the beginning of next month.
            d = Date(1,d1.month(),d1.year()) + 1*Months;
            total += calendar_.businessDaysBetween(d1, d);
            // then, we add any whole months (whose figures might be
            // cached already) in the middle of our period.
            while (!sameMonth(d,d2)) {
                total += businessDays(cache, calendar_,
                                      d.month(), d.year());
                d += 1*Months;
            }
            // finally, we get to the end of the period.
            total += calendar_.businessDaysBetween(d, d2);
            return total;
        } else {
            Cache& cache = monthlyFigures_[calendar_.name()];
            OuterCache& outerCache = yearlyFigures_[calendar_.name()];
            BigInteger total = 0;
            Date d;
            // first, we get to the beginning of next year.
            // The first bit gets us to the end of this month...
            d = Date(1,d1.month(),d1.year()) + 1*Months;
            total += calendar_.businessDaysBetween(d1, d);
            // ...then we add any remaining months, possibly cached
            for (Integer m = Integer(d1.month())+1; m <= 12; ++m) {
                total += businessDays(cache, calendar_,
                                      Month(m), d.year());
            }
            // then, we add any whole year in the middle of our period.
            d = Date(1,January,d1.year()+1);
            while (!sameYear(d,d2)) {
                total += businessDays(outerCache, cache,
                                      calendar_, d.year());
                d += 1*Years;
            }
            // finally, we get to the end of the period.
            // First, we add whole months...
            for (Integer m = 1; m<Integer(d2.month()); ++m) {
                total += businessDays(cache, calendar_,
                                      Month(m), d2.year());
            }
            // ...then the last bit.
            d = Date(1,d2.month(),d2.year());
            total += calendar_.businessDaysBetween(d, d2);
            return total;
        }
    }
std::string QuantLib::Business252::Impl::name () const [virtual]
Implements QuantLib::DayCounter::Impl.
Definition at line 72 of file business252.cpp.
References calendar_, and QuantLib::Calendar::name().
{
        std::ostringstream out;
        out << "Business/252(" << calendar_.name() << ")";
        return out.str();
    }
Time QuantLib::Business252::Impl::yearFraction (const Date & d1, const Date & d2, const Date & , const Date &) const [virtual]
Implements QuantLib::DayCounter::Impl.
Definition at line 137 of file business252.cpp.
References QuantLib::DayCounter::dayCount().
{
        return dayCount(d1, d2)/252.0;
    }
Member Data Documentation
Calendar QuantLib::Business252::Impl::calendar_ [private]
Definition at line 40 of file business252.hpp.
Referenced by Impl(), and name().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/time/daycounters/business252.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/time/daycounters/business252.cpp