QuantLib: QuantLib::Lattice Class Reference
QuantLib::Lattice Class Reference
Lattice (tree, finite-differences) base class
#include <numericalmethod.hpp>
Public Member Functions
Lattice (const TimeGrid &timeGrid)
virtual ~Lattice ()
virtual Disposable< Array > grid (Time) const =0
Inspectors
const TimeGrid & timeGrid () const
Numerical method interface
These methods are to be used by discretized assets and must be overridden by developers implementing numerical methods. Users are advised to use the corresponding methods of DiscretizedAsset instead.
virtual void initialize (DiscretizedAsset &, Time time) const =0
initialize an asset at the given time.
virtual void rollback (DiscretizedAsset &, Time to) const =0
virtual void partialRollback (DiscretizedAsset &, Time to) const =0
virtual Real presentValue (DiscretizedAsset &) const =0
computes the present value of an asset.
Protected Attributes
TimeGrid t_
Detailed Description
Lattice (tree, finite-differences) base class
Definition at line 36 of file numericalmethod.hpp.
Constructor & Destructor Documentation
QuantLib::Lattice::Lattice (const TimeGrid & timeGrid) [inline]
Definition at line 38 of file numericalmethod.hpp.
: t_(timeGrid) {}
virtual QuantLib::Lattice::~Lattice () [inline, virtual]
Definition at line 39 of file numericalmethod.hpp.
{}
Member Function Documentation
virtual Disposable<Array> QuantLib::Lattice::grid (Time) const [pure virtual]
Implemented in QuantLib::TreeLattice2D< Impl, T >, QuantLib::TreeLattice2D< TwoFactorModel::ShortRateTree, TrinomialTree >, QuantLib::TreeLattice1D< Impl >, QuantLib::TreeLattice1D< OneFactorModel::ShortRateTree >, and QuantLib::TreeLattice1D< BlackScholesLattice< T > >.
virtual void QuantLib::Lattice::initialize (DiscretizedAsset & , Time time) const [pure virtual]
initialize an asset at the given time.
Implemented in QuantLib::TreeLattice< Impl >, QuantLib::TreeLattice< OneFactorModel::ShortRateTree >, QuantLib::TreeLattice< TwoFactorModel::ShortRateTree >, and QuantLib::TreeLattice< BlackScholesLattice< T > >.
virtual void QuantLib::Lattice::partialRollback (DiscretizedAsset & , Time to) const [pure virtual]
Roll back an asset until the given time, but do not perform the final adjustment.
Warning:
In version 0.3.7 and earlier, this method was called rollAlmostBack method and performed pre-adjustment. This is no longer true; when migrating your code, you'll have to replace calls such as:
                     method->rollAlmostBack(asset,t);
with the two statements:
                     method->partialRollback(asset,t);
                     asset->preAdjustValues();
Implemented in QuantLib::TreeLattice< Impl >, QuantLib::TreeLattice< OneFactorModel::ShortRateTree >, QuantLib::TreeLattice< TwoFactorModel::ShortRateTree >, QuantLib::TreeLattice< BlackScholesLattice< T > >, and QuantLib::TsiveriotisFernandesLattice< T >.
virtual Real QuantLib::Lattice::presentValue (DiscretizedAsset &) const [pure virtual]
computes the present value of an asset.
Implemented in QuantLib::TreeLattice< Impl >, QuantLib::TreeLattice< OneFactorModel::ShortRateTree >, QuantLib::TreeLattice< TwoFactorModel::ShortRateTree >, and QuantLib::TreeLattice< BlackScholesLattice< T > >.
virtual void QuantLib::Lattice::rollback (DiscretizedAsset & , Time to) const [pure virtual]
Roll back an asset until the given time, performing any needed adjustment.
Implemented in QuantLib::TreeLattice< Impl >, QuantLib::TreeLattice< OneFactorModel::ShortRateTree >, QuantLib::TreeLattice< TwoFactorModel::ShortRateTree >, QuantLib::TreeLattice< BlackScholesLattice< T > >, and QuantLib::TsiveriotisFernandesLattice< T >.
const TimeGrid& QuantLib::Lattice::timeGrid () const [inline]
Definition at line 43 of file numericalmethod.hpp.
References t_.
Referenced by QuantLib::OneFactorModel::ShortRateTree::discount(), QuantLib::TwoFactorModel::ShortRateTree::discount(), QuantLib::TreeLattice1D< BlackScholesLattice< T > >::grid(), and QuantLib::OneFactorModel::ShortRateTree::Helper::Helper().
{ return t_; }
Member Data Documentation
TimeGrid QuantLib::Lattice::t_ [protected]
Definition at line 94 of file numericalmethod.hpp.
Referenced by QuantLib::OneFactorModel::ShortRateTree::ShortRateTree(), and timeGrid().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/numericalmethod.hpp