QuantLib: QuantLib::AmortizingFloatingRateBond Class Reference
QuantLib::AmortizingFloatingRateBond Class Reference
amortizing floating-rate bond (possibly capped and/or floored)
#include <amortizingfloatingratebond.hpp>
Public Member Functions
AmortizingFloatingRateBond (Natural settlementDays, const std::vector< Real > &notional, const Schedule &schedule, const boost::shared_ptr< IborIndex > &index, const DayCounter &accrualDayCounter, BusinessDayConvention paymentConvention=Following, Natural fixingDays=Null< Natural >(), const std::vector< Real > &gearings=std::vector< Real >(1, 1.0), const std::vector< Spread > &spreads=std::vector< Spread >(1, 0.0), const std::vector< Rate > &caps=std::vector< Rate >(), const std::vector< Rate > &floors=std::vector< Rate >(), bool inArrears=false, const Date &issueDate=Date())
Detailed Description
amortizing floating-rate bond (possibly capped and/or floored)
Definition at line 35 of file amortizingfloatingratebond.hpp.
Constructor & Destructor Documentation
QuantLib::AmortizingFloatingRateBond::AmortizingFloatingRateBond (Natural settlementDays, const std::vector< Real > & notional, const Schedule & schedule, const boost::shared_ptr< IborIndex > & index, const DayCounter & accrualDayCounter, BusinessDayConvention paymentConvention = Following, Natural fixingDays = Null<Natural>(), const std::vector< Real > & gearings = std::vector<Real>(1, 1.0), const std::vector< Spread > & spreads = std::vector<Spread>(1, 0.0), const std::vector< Rate > & caps = std::vector<Rate>(), const std::vector< Rate > & floors = std::vector<Rate>(), bool inArrears = false, const Date & issueDate = Date())
Definition at line 28 of file amortizingfloatingratebond.cpp.
References QuantLib::Bond::addRedemptionsToCashflows(), QuantLib::Bond::cashflows(), QuantLib::Bond::cashflows_, QuantLib::Schedule::endDate(), QuantLib::IborLeg::inArrears(), QuantLib::Bond::maturityDate_, QL_ENSURE, QuantLib::Observer::registerWith(), QuantLib::IborLeg::withCaps(), QuantLib::IborLeg::withFixingDays(), QuantLib::IborLeg::withFloors(), QuantLib::IborLeg::withGearings(), QuantLib::IborLeg::withNotionals(), QuantLib::IborLeg::withPaymentAdjustment(), QuantLib::IborLeg::withPaymentDayCounter(), and QuantLib::IborLeg::withSpreads().
    : Bond(settlementDays, schedule.calendar(), issueDate) {
        maturityDate_ = schedule.endDate();
        cashflows_ = IborLeg(schedule, index)
            .withNotionals(notionals)
            .withPaymentDayCounter(paymentDayCounter)
            .withPaymentAdjustment(paymentConvention)
            .withFixingDays(fixingDays)
            .withGearings(gearings)
            .withSpreads(spreads)
            .withCaps(caps)
            .withFloors(floors)
            .inArrears(inArrears);
        addRedemptionsToCashflows();
        QL_ENSURE(!cashflows().empty(), "bond with no cashflows!");
        registerWith(index);
    }
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/amortizingbonds/amortizingfloatingratebond.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/amortizingbonds/amortizingfloatingratebond.cpp