QuantLib: QuantLib::BlackCapFloorEngine Class Reference
QuantLib::BlackCapFloorEngine Class Reference
Black-formula cap/floor engine.
#include <blackcapfloorengine.hpp>
Public Member Functions
BlackCapFloorEngine (const Handle< YieldTermStructure > &discountCurve, Volatility vol, const DayCounter &dc=Actual365Fixed())
BlackCapFloorEngine (const Handle< YieldTermStructure > &discountCurve, const Handle< Quote > &vol, const DayCounter &dc=Actual365Fixed())
BlackCapFloorEngine (const Handle< YieldTermStructure > &discountCurve, const Handle< OptionletVolatilityStructure > &vol)
void calculate () const
Handle< YieldTermStructure > termStructure ()
Handle
< OptionletVolatilityStructure > volatility ()
Private Attributes
Handle< YieldTermStructure > discountCurve_
Handle
< OptionletVolatilityStructure > vol_
Detailed Description
Black-formula cap/floor engine.
Definition at line 38 of file blackcapfloorengine.hpp.
Constructor & Destructor Documentation
QuantLib::BlackCapFloorEngine::BlackCapFloorEngine (const Handle< YieldTermStructure > & discountCurve, Volatility vol, const DayCounter & dc = Actual365Fixed())
Definition at line 30 of file blackcapfloorengine.cpp.
References discountCurve_, and QuantLib::Observer::registerWith().
    : discountCurve_(discountCurve),
      vol_(boost::shared_ptr<OptionletVolatilityStructure>(new
          ConstantOptionletVolatility(0, NullCalendar(), Following, v, dc))) {
        registerWith(discountCurve_);
    }
QuantLib::BlackCapFloorEngine::BlackCapFloorEngine (const Handle< YieldTermStructure > & discountCurve, const Handle< Quote > & vol, const DayCounter & dc = Actual365Fixed())
Definition at line 40 of file blackcapfloorengine.cpp.
References discountCurve_, QuantLib::Observer::registerWith(), and vol_.
    : discountCurve_(discountCurve),
      vol_(boost::shared_ptr<OptionletVolatilityStructure>(new
          ConstantOptionletVolatility(0, NullCalendar(), Following, v, dc))) {
        registerWith(discountCurve_);
        registerWith(vol_);
    }
QuantLib::BlackCapFloorEngine::BlackCapFloorEngine (const Handle< YieldTermStructure > & discountCurve, const Handle< OptionletVolatilityStructure > & vol)
Definition at line 51 of file blackcapfloorengine.cpp.
References discountCurve_, QuantLib::Observer::registerWith(), and vol_.
    : discountCurve_(discountCurve), vol_(volatility) {
        registerWith(discountCurve_);
        registerWith(vol_);
    }
Member Function Documentation
void QuantLib::BlackCapFloorEngine::calculate () const [virtual]
Implements QuantLib::PricingEngine.
Definition at line 59 of file blackcapfloorengine.cpp.
References QuantLib::CapFloor::arguments::accrualTimes, QuantLib::GenericEngine< CapFloor::arguments, CapFloor::results >::arguments_, QuantLib::blackFormula(), QuantLib::blackFormulaStdDevDerivative(), QuantLib::Option::Call, QuantLib::CapFloor::Cap, QuantLib::CapFloor::arguments::capRates, QuantLib::CapFloor::Collar, anonymous_namespace{marketmodel.cpp}::d, discountCurve_, QuantLib::CapFloor::arguments::endDates, QuantLib::CapFloor::arguments::fixingDates, QuantLib::CapFloor::Floor, QuantLib::CapFloor::arguments::floorRates, QuantLib::CapFloor::arguments::forwards, QuantLib::CapFloor::arguments::gearings, QuantLib::CapFloor::arguments::nominals, QuantLib::Option::Put, QuantLib::GenericEngine< CapFloor::arguments, CapFloor::results >::results_, QuantLib::CapFloor::arguments::startDates, QuantLib::CapFloor::arguments::type, and vol_.
{
        Real value = 0.0;
        Real vega = 0.0;
        Size optionlets = arguments_.startDates.size();
        std::vector<Real> values(optionlets, 0.0);
        std::vector<Real> vegas(optionlets, 0.0);
        std::vector<Real> stdDevs(optionlets, 0.0);
        CapFloor::Type type = arguments_.type;
        Date today = vol_->referenceDate();
        Date settlement = discountCurve_->referenceDate();
        for (Size i=0; i<optionlets; ++i) {
            Date paymentDate = arguments_.endDates[i];
            // handling of settlementDate, npvDate and includeSettlementFlows
            // should be implemented.
            // For the time being just discard expired caplets
            if (paymentDate > settlement) {
                DiscountFactor d = arguments_.nominals[i] *
                                   arguments_.gearings[i] *
                                   discountCurve_->discount(paymentDate) *
                                   arguments_.accrualTimes[i];
                Rate forward = arguments_.forwards[i];
                Date fixingDate = arguments_.fixingDates[i];
                Time sqrtTime = 0.0;
                if (fixingDate > today)
                    sqrtTime = std::sqrt(vol_->timeFromReference(fixingDate));
                if (type == CapFloor::Cap || type == CapFloor::Collar) {
                    Rate strike = arguments_.capRates[i];
                    if (sqrtTime>0.0) {
                        stdDevs[i] = std::sqrt(vol_->blackVariance(fixingDate,
                                                                   strike));
                        vegas[i] = blackFormulaStdDevDerivative(
                            strike, forward, stdDevs[i], d) * sqrtTime;
                    }
                    // include caplets with past fixing date
                    values[i] = blackFormula(Option::Call, strike,
                                             forward, stdDevs[i], d);
                }
                if (type == CapFloor::Floor || type == CapFloor::Collar) {
                    Rate strike = arguments_.floorRates[i];
                    Real floorletVega = 0.0;
                    if (sqrtTime>0.0) {
                        stdDevs[i] = std::sqrt(vol_->blackVariance(fixingDate,
                                                                   strike));
                        floorletVega = blackFormulaStdDevDerivative(
                            strike, forward, stdDevs[i], d) * sqrtTime;
                    }
                    Real floorlet = blackFormula(Option::Put, strike,
                                                 forward, stdDevs[i], d);
                    if (type == CapFloor::Floor) {
                        values[i] = floorlet;
                        vegas[i] = floorletVega;
                    } else {
                        // a collar is long a cap and short a floor
                        values[i] -= floorlet;
                        vegas[i] -= floorletVega;
                    }
                }
                value += values[i];
                vega += vegas[i];
            }
        }
        results_.value = value;
        results_.additionalResults["vega"] = vega;
        results_.additionalResults["optionletsPrice"] = values;
        results_.additionalResults["optionletsVega"] = vegas;
        results_.additionalResults["optionletsAtmForward"] = arguments_.forwards;
        if (type != CapFloor::Collar)
            results_.additionalResults["optionletsStdDev"] = stdDevs;
    }
Handle<YieldTermStructure> QuantLib::BlackCapFloorEngine::termStructure () [inline]
Definition at line 49 of file blackcapfloorengine.hpp.
References discountCurve_.
{ return discountCurve_; }
Handle<OptionletVolatilityStructure> QuantLib::BlackCapFloorEngine::volatility () [inline]
Definition at line 50 of file blackcapfloorengine.hpp.
References vol_.
{ return vol_; }
Member Data Documentation
Handle<YieldTermStructure> QuantLib::BlackCapFloorEngine::discountCurve_ [private]
Definition at line 52 of file blackcapfloorengine.hpp.
Referenced by BlackCapFloorEngine(), calculate(), and termStructure().
Handle<OptionletVolatilityStructure> QuantLib::BlackCapFloorEngine::vol_ [private]
Definition at line 53 of file blackcapfloorengine.hpp.
Referenced by BlackCapFloorEngine(), calculate(), and volatility().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/capfloor/blackcapfloorengine.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/capfloor/blackcapfloorengine.cpp