QuantLib: QuantLib::SwaptionVolatilityStructure Class Reference
QuantLib::SwaptionVolatilityStructure Class Reference
Swaption-volatility structure
#include <swaptionvolstructure.hpp>
Public Member Functions
virtual ~SwaptionVolatilityStructure ()
Time swapLength (const Period &swapTenor) const
implements the conversion between swap tenor and swap (time) length
Time swapLength (const Date &start, const Date &end) const
implements the conversion between swap dates and swap (time) length
Constructors
See the TermStructure documentation for issues regarding constructors.
SwaptionVolatilityStructure (const Calendar &calendar, BusinessDayConvention bdc, const DayCounter &dc=DayCounter())
SwaptionVolatilityStructure (BusinessDayConvention bdc, const DayCounter &dc=DayCounter())
SwaptionVolatilityStructure (const Date &referenceDate, const Calendar &calendar, BusinessDayConvention bdc, const DayCounter &dc=DayCounter())
initialize with a fixed reference date
SwaptionVolatilityStructure (Natural settlementDays, const Calendar &, BusinessDayConvention bdc, const DayCounter &dc=DayCounter())
calculate the reference date based on the global evaluation date
Volatility, variance and smile
Volatility volatility (const Period &optionTenor, const Period &swapTenor, Rate strike, bool extrapolate=false) const
returns the volatility for a given option tenor and swap tenor
Volatility volatility (const Date &optionDate, const Period &swapTenor, Rate strike, bool extrapolate=false) const
returns the volatility for a given option date and swap tenor
Volatility volatility (Time optionTime, const Period &swapTenor, Rate strike, bool extrapolate=false) const
returns the volatility for a given option time and swap tenor
Volatility volatility (const Period &optionTenor, Time swapLength, Rate strike, bool extrapolate=false) const
returns the volatility for a given option tenor and swap length
Volatility volatility (const Date &optionDate, Time swapLength, Rate strike, bool extrapolate=false) const
returns the volatility for a given option date and swap length
Volatility volatility (Time optionTime, Time swapLength, Rate strike, bool extrapolate=false) const
returns the volatility for a given option time and swap length
Real blackVariance (const Period &optionTenor, const Period &swapTenor, Rate strike, bool extrapolate=false) const
returns the Black variance for a given option tenor and swap tenor
Real blackVariance (const Date &optionDate, const Period &swapTenor, Rate strike, bool extrapolate=false) const
returns the Black variance for a given option date and swap tenor
Real blackVariance (Time optionTime, const Period &swapTenor, Rate strike, bool extrapolate=false) const
returns the Black variance for a given option time and swap tenor
Real blackVariance (const Period &optionTenor, Time swapLength, Rate strike, bool extrapolate=false) const
returns the Black variance for a given option tenor and swap length
Real blackVariance (const Date &optionDate, Time swapLength, Rate strike, bool extrapolate=false) const
returns the Black variance for a given option date and swap length
Real blackVariance (Time optionTime, Time swapLength, Rate strike, bool extrapolate=false) const
returns the Black variance for a given option time and swap length
boost::shared_ptr< SmileSection > smileSection (const Period &optionTenor, const Period &swapTenor, bool extr=false) const
returns the smile for a given option tenor and swap tenor
boost::shared_ptr< SmileSection > smileSection (const Date &optionDate, const Period &swapTenor, bool extr=false) const
returns the smile for a given option date and swap tenor
boost::shared_ptr< SmileSection > smileSection (Time optionTime, const Period &swapTenor, bool extr=false) const
returns the smile for a given option time and swap tenor
boost::shared_ptr< SmileSection > smileSection (const Period &optionTenor, Time swapLength, bool extr=false) const
returns the smile for a given option tenor and swap length
boost::shared_ptr< SmileSection > smileSection (const Date &optionDate, Time swapLength, bool extr=false) const
returns the smile for a given option date and swap length
boost::shared_ptr< SmileSection > smileSection (Time optionTime, Time swapLength, bool extr=false) const
returns the smile for a given option time and swap length
Limits
virtual const Period & maxSwapTenor () const =0
the largest length for which the term structure can return vols
Time maxSwapLength () const
the largest swapLength for which the term structure can return vols
Protected Member Functions
virtual boost::shared_ptr
< SmileSection > smileSectionImpl (const Date &optionDate, const Period &swapTenor) const
virtual boost::shared_ptr
< SmileSection > smileSectionImpl (Time optionTime, Time swapLength) const =0
virtual Volatility volatilityImpl (const Date &optionDate, const Period &swapTenor, Rate strike) const
virtual Volatility volatilityImpl (Time optionTime, Time swapLength, Rate strike) const =0
void checkSwapTenor (const Period &swapTenor, bool extrapolate) const
void checkSwapTenor (Time swapLength, bool extrapolate) const
Detailed Description
Swaption-volatility structure
This abstract class defines the interface of concrete swaption volatility structures which will be derived from this one.
Definition at line 39 of file swaptionvolstructure.hpp.
Constructor & Destructor Documentation
QuantLib::SwaptionVolatilityStructure::SwaptionVolatilityStructure (const Calendar & calendar, BusinessDayConvention bdc, const DayCounter & dc = DayCounter())
Warning:
term structures initialized by means of this constructor must manage their own reference date by overriding the referenceDate() method.
Definition at line 28 of file swaptionvolstructure.cpp.
    : VolatilityTermStructure(cal, bdc, dc) {}
QuantLib::SwaptionVolatilityStructure::SwaptionVolatilityStructure (BusinessDayConvention bdc, const DayCounter & dc = DayCounter())
Warning:
term structures initialized by means of this constructor must manage their own reference date by overriding the referenceDate() method.
Definition at line 35 of file swaptionvolstructure.cpp.
    : VolatilityTermStructure(bdc, dc) {}
QuantLib::SwaptionVolatilityStructure::SwaptionVolatilityStructure (const Date & referenceDate, const Calendar & calendar, BusinessDayConvention bdc, const DayCounter & dc = DayCounter())
initialize with a fixed reference date
Definition at line 40 of file swaptionvolstructure.cpp.
    : VolatilityTermStructure(referenceDate, calendar, bdc, dc) {}
QuantLib::SwaptionVolatilityStructure::SwaptionVolatilityStructure (Natural settlementDays, const Calendar & calendar, BusinessDayConvention bdc, const DayCounter & dc = DayCounter())
calculate the reference date based on the global evaluation date
Definition at line 47 of file swaptionvolstructure.cpp.
    : VolatilityTermStructure(settlementDays, calendar, bdc, dc) {}
virtual QuantLib::SwaptionVolatilityStructure::~SwaptionVolatilityStructure () [inline, virtual]
Definition at line 72 of file swaptionvolstructure.hpp.
{}
Member Function Documentation
Real QuantLib::SwaptionVolatilityStructure::blackVariance (const Period & optionTenor, const Period & swapTenor, Rate strike, bool extrapolate = false) const [inline]
returns the Black variance for a given option tenor and swap tenor
Definition at line 216 of file swaptionvolstructure.hpp.
References QuantLib::VolatilityTermStructure::optionDateFromTenor().
Referenced by blackVariance().
{
        Date optionDate = optionDateFromTenor(optionTenor);
        return blackVariance(optionDate, swapTenor, strike, extrapolate);
    }
Real QuantLib::SwaptionVolatilityStructure::blackVariance (const Date & optionDate, const Period & swapTenor, Rate strike, bool extrapolate = false) const [inline]
returns the Black variance for a given option date and swap tenor
Definition at line 243 of file swaptionvolstructure.hpp.
References QuantLib::TermStructure::timeFromReference(), anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and volatility().
{
        Volatility v = volatility(optionDate, swapTenor, strike, extrapolate);
        Time optionTime = timeFromReference(optionDate);
        return v*v*optionTime;
    }
Real QuantLib::SwaptionVolatilityStructure::blackVariance (Time optionTime, const Period & swapTenor, Rate strike, bool extrapolate = false) const [inline]
returns the Black variance for a given option time and swap tenor
Definition at line 253 of file swaptionvolstructure.hpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and volatility().
{
        Volatility v = volatility(optionTime, swapTenor, strike, extrapolate);
        return v*v*optionTime;
    }
Real QuantLib::SwaptionVolatilityStructure::blackVariance (const Period & optionTenor, Time swapLength, Rate strike, bool extrapolate = false) const [inline]
returns the Black variance for a given option tenor and swap length
Definition at line 225 of file swaptionvolstructure.hpp.
References blackVariance(), and QuantLib::VolatilityTermStructure::optionDateFromTenor().
{
        Date optionDate = optionDateFromTenor(optionTenor);
        return blackVariance(optionDate, swapLength, strike, extrapolate);
    }
Real QuantLib::SwaptionVolatilityStructure::blackVariance (const Date & optionDate, Time swapLength, Rate strike, bool extrapolate = false) const [inline]
returns the Black variance for a given option date and swap length
Definition at line 262 of file swaptionvolstructure.hpp.
References QuantLib::TermStructure::timeFromReference(), anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and volatility().
{
        Volatility v = volatility(optionDate, swapLength, strike, extrapolate);
        Time optionTime = timeFromReference(optionDate);
        return v*v*optionTime;
    }
Real QuantLib::SwaptionVolatilityStructure::blackVariance (Time optionTime, Time swapLength, Rate strike, bool extrapolate = false) const [inline]
returns the Black variance for a given option time and swap length
Definition at line 272 of file swaptionvolstructure.hpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), and volatility().
{
        Volatility v = volatility(optionTime, swapLength, strike, extrapolate);
        return v*v*optionTime;
    }
void QuantLib::SwaptionVolatilityStructure::checkSwapTenor (const Period & swapTenor, bool extrapolate) const [protected]
Definition at line 78 of file swaptionvolstructure.cpp.
References QuantLib::Extrapolator::allowsExtrapolation(), QuantLib::Period::length(), maxSwapTenor(), and QL_REQUIRE.
Referenced by smileSection(), and volatility().
{
        QL_REQUIRE(swapTenor.length() > 0,
                   "non-positive swap tenor (" << swapTenor << ") given");
        QL_REQUIRE(extrapolate || allowsExtrapolation() ||
                   swapTenor <= maxSwapTenor(),
                   "swap tenor (" << swapTenor << ") is past max tenor ("
                   << maxSwapTenor() << ")");
    }
void QuantLib::SwaptionVolatilityStructure::checkSwapTenor (Time swapLength, bool extrapolate) const [protected]
Definition at line 88 of file swaptionvolstructure.cpp.
References QuantLib::Extrapolator::allowsExtrapolation(), maxSwapLength(), and QL_REQUIRE.
{
        QL_REQUIRE(swapLength > 0.0,
                   "non-positive swap length (" << swapLength << ") given");
        QL_REQUIRE(extrapolate || allowsExtrapolation() ||
                   swapLength <= maxSwapLength(),
                   "swap tenor (" << swapLength << ") is past max tenor ("
                   << maxSwapLength() << ")");
    }
Time QuantLib::SwaptionVolatilityStructure::maxSwapLength () const [inline]
the largest swapLength for which the term structure can return vols
Definition at line 363 of file swaptionvolstructure.hpp.
References maxSwapTenor(), and swapLength().
Referenced by checkSwapTenor().
{
        return swapLength(maxSwapTenor());
    }
virtual const Period& QuantLib::SwaptionVolatilityStructure::maxSwapTenor () const [pure virtual]
the largest length for which the term structure can return vols
Implemented in QuantLib::SwaptionVolatilityMatrix, QuantLib::ConstantSwaptionVolatility, QuantLib::SwaptionVolatilityCube, and QuantLib::SpreadedSwaptionVolatility.
Referenced by checkSwapTenor(), and maxSwapLength().
boost::shared_ptr< SmileSection > QuantLib::SwaptionVolatilityStructure::smileSection (const Period & optionTenor, const Period & swapTenor, bool extr = false) const [inline]
returns the smile for a given option tenor and swap tenor
Definition at line 234 of file swaptionvolstructure.hpp.
References QuantLib::VolatilityTermStructure::optionDateFromTenor().
{
        Date optionDate = optionDateFromTenor(optionTenor);
        return smileSection(optionDate, swapTenor, extrapolate);
    }
boost::shared_ptr< SmileSection > QuantLib::SwaptionVolatilityStructure::smileSection (const Date & optionDate, const Period & swapTenor, bool extr = false) const [inline]
returns the smile for a given option date and swap tenor
Definition at line 328 of file swaptionvolstructure.hpp.
References QuantLib::TermStructure::checkRange(), checkSwapTenor(), and smileSectionImpl().
{
        checkSwapTenor(swapTenor, extrapolate);
        checkRange(optionDate, extrapolate);
        return smileSectionImpl(optionDate, swapTenor);
    }
boost::shared_ptr<SmileSection> QuantLib::SwaptionVolatilityStructure::smileSection (Time optionTime, const Period & swapTenor, bool extr = false) const
returns the smile for a given option time and swap tenor
boost::shared_ptr<SmileSection> QuantLib::SwaptionVolatilityStructure::smileSection (const Period & optionTenor, Time swapLength, bool extr = false) const
returns the smile for a given option tenor and swap length
boost::shared_ptr<SmileSection> QuantLib::SwaptionVolatilityStructure::smileSection (const Date & optionDate, Time swapLength, bool extr = false) const
returns the smile for a given option date and swap length
boost::shared_ptr< SmileSection > QuantLib::SwaptionVolatilityStructure::smileSection (Time optionTime, Time swapLength, bool extr = false) const [inline]
returns the smile for a given option time and swap length
Definition at line 337 of file swaptionvolstructure.hpp.
References QuantLib::TermStructure::checkRange(), checkSwapTenor(), and smileSectionImpl().
{
        checkSwapTenor(swapLength, extrapolate);
        checkRange(optionTime, extrapolate);
        return smileSectionImpl(optionTime, swapLength);
    }
boost::shared_ptr< SmileSection > QuantLib::SwaptionVolatilityStructure::smileSectionImpl (const Date & optionDate, const Period & swapTenor) const [inline, protected, virtual]
Reimplemented in QuantLib::ConstantSwaptionVolatility, QuantLib::SwaptionVolCube2, and QuantLib::SpreadedSwaptionVolatility.
Definition at line 348 of file swaptionvolstructure.hpp.
References swapLength(), and QuantLib::TermStructure::timeFromReference().
Referenced by smileSection(), and QuantLib::SwaptionVolatilityCube::volatilityImpl().
{
        return smileSectionImpl(timeFromReference(optionDate),
                                swapLength(swapT));
    }
virtual boost::shared_ptr<SmileSection> QuantLib::SwaptionVolatilityStructure::smileSectionImpl (Time optionTime, Time swapLength) const [protected, pure virtual]
Implemented in QuantLib::SwaptionVolatilityMatrix, QuantLib::SwaptionVolCube1, QuantLib::ConstantSwaptionVolatility, QuantLib::SwaptionVolCube2, and QuantLib::SpreadedSwaptionVolatility.
Time QuantLib::SwaptionVolatilityStructure::swapLength (const Period & swapTenor) const
implements the conversion between swap tenor and swap (time) length
Definition at line 55 of file swaptionvolstructure.cpp.
References QuantLib::Period::length(), QuantLib::Months, QL_FAIL, QL_REQUIRE, QuantLib::Period::units(), and QuantLib::Years.
Referenced by QuantLib::SwaptionVolatilityDiscrete::initializeSwapLengths(), QuantLib::SwaptionVolatilityMatrix::locate(), maxSwapLength(), QuantLib::SwaptionVolCube1::Cube::operator()(), QuantLib::SwaptionVolCube1::Cube::setPoint(), QuantLib::SwaptionVolCube2::smileSectionImpl(), smileSectionImpl(), QuantLib::SwaptionVolCube1::spreadVolInterpolation(), volatility(), and volatilityImpl().
{
        QL_REQUIRE(p.length()>0,
                   "non-positive swap tenor (" << p << ") given");
        switch (p.units()) {
          case Months:
            return p.length()/12.0;
          case Years:
            return static_cast<Time>(p.length());
          default:
            QL_FAIL("invalid Time Unit (" << p.units() << ") for swap length");
        }
    }
Time QuantLib::SwaptionVolatilityStructure::swapLength (const Date & start, const Date & end) const
implements the conversion between swap dates and swap (time) length
Definition at line 68 of file swaptionvolstructure.cpp.
References QL_REQUIRE.
{
        QL_REQUIRE(end>start, "swap end date (" << end <<
                   ") must be greater than start (" << start << ")");
        Time result = (end-start)/365.25*12.0; // month unit
        result = ClosestRounding(0)(result);
        result /= 12.0; // year unit
        return result;
    }
Volatility QuantLib::SwaptionVolatilityStructure::volatility (const Period & optionTenor, const Period & swapTenor, Rate strike, bool extrapolate = false) const [inline]
returns the volatility for a given option tenor and swap tenor
Definition at line 198 of file swaptionvolstructure.hpp.
References QuantLib::VolatilityTermStructure::optionDateFromTenor().
Referenced by blackVariance(), anonymous_namespace{swaptionvolatilitycube.cpp}::CommonVars::makeAtmVolTest(), anonymous_namespace{swaptionvolatilitycube.cpp}::CommonVars::makeVolSpreadsTest(), and volatility().
{
        Date optionDate = optionDateFromTenor(optionTenor);
        return volatility(optionDate, swapTenor, strike, extrapolate);
    }
Volatility QuantLib::SwaptionVolatilityStructure::volatility (const Date & optionDate, const Period & swapTenor, Rate strike, bool extrapolate = false) const [inline]
returns the volatility for a given option date and swap tenor
Definition at line 282 of file swaptionvolstructure.hpp.
References QuantLib::TermStructure::checkRange(), QuantLib::VolatilityTermStructure::checkStrike(), checkSwapTenor(), and volatilityImpl().
{
        checkSwapTenor(swapTenor, extrapolate);
        checkRange(optionDate, extrapolate);
        checkStrike(strike, extrapolate);
        return volatilityImpl(optionDate, swapTenor, strike);
    }
Volatility QuantLib::SwaptionVolatilityStructure::volatility (Time optionTime, const Period & swapTenor, Rate strike, bool extrapolate = false) const [inline]
returns the volatility for a given option time and swap tenor
Definition at line 305 of file swaptionvolstructure.hpp.
References QuantLib::TermStructure::checkRange(), QuantLib::VolatilityTermStructure::checkStrike(), checkSwapTenor(), swapLength(), and volatilityImpl().
{
        checkSwapTenor(swapTenor, extrapolate);
        checkRange(optionTime, extrapolate);
        checkStrike(strike, extrapolate);
        Time length = swapLength(swapTenor);
        return volatilityImpl(optionTime, length, strike);
    }
Volatility QuantLib::SwaptionVolatilityStructure::volatility (const Period & optionTenor, Time swapLength, Rate strike, bool extrapolate = false) const [inline]
returns the volatility for a given option tenor and swap length
Definition at line 207 of file swaptionvolstructure.hpp.
References QuantLib::VolatilityTermStructure::optionDateFromTenor(), and volatility().
{
        Date optionDate = optionDateFromTenor(optionTenor);
        return volatility(optionDate, swapLength, strike, extrapolate);
    }
Volatility QuantLib::SwaptionVolatilityStructure::volatility (const Date & optionDate, Time swapLength, Rate strike, bool extrapolate = false) const [inline]
returns the volatility for a given option date and swap length
Definition at line 293 of file swaptionvolstructure.hpp.
References QuantLib::TermStructure::checkRange(), QuantLib::VolatilityTermStructure::checkStrike(), checkSwapTenor(), QuantLib::TermStructure::timeFromReference(), and volatilityImpl().
{
        checkSwapTenor(swapLength, extrapolate);
        checkRange(optionDate, extrapolate);
        checkStrike(strike, extrapolate);
        Time optionTime = timeFromReference(optionDate);
        return volatilityImpl(optionTime, swapLength, strike);
    }
Volatility QuantLib::SwaptionVolatilityStructure::volatility (Time optionTime, Time swapLength, Rate strike, bool extrapolate = false) const [inline]
returns the volatility for a given option time and swap length
Definition at line 317 of file swaptionvolstructure.hpp.
References QuantLib::TermStructure::checkRange(), QuantLib::VolatilityTermStructure::checkStrike(), checkSwapTenor(), and volatilityImpl().
{
        checkSwapTenor(swapLength, extrapolate);
        checkRange(optionTime, extrapolate);
        checkStrike(strike, extrapolate);
        return volatilityImpl(optionTime, swapLength, strike);
    }
Volatility QuantLib::SwaptionVolatilityStructure::volatilityImpl (const Date & optionDate, const Period & swapTenor, Rate strike) const [inline, protected, virtual]
Reimplemented in QuantLib::SwaptionVolatilityCube, QuantLib::ConstantSwaptionVolatility, and QuantLib::SpreadedSwaptionVolatility.
Definition at line 355 of file swaptionvolstructure.hpp.
References swapLength(), and QuantLib::TermStructure::timeFromReference().
Referenced by volatility().
{
        return volatilityImpl(timeFromReference(optionDate),
                              swapLength(swapTenor),
                              strike);
    }
virtual Volatility QuantLib::SwaptionVolatilityStructure::volatilityImpl (Time optionTime, Time swapLength, Rate strike) const [protected, pure virtual]
Implemented in QuantLib::SwaptionVolatilityMatrix, QuantLib::ConstantSwaptionVolatility, QuantLib::SwaptionVolatilityCube, and QuantLib::SpreadedSwaptionVolatility.
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/swaption/swaptionvolstructure.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/termstructures/volatility/swaption/swaptionvolstructure.cpp