QuantLib: QuantLib::AnalyticEuropeanMargrabeEngine Class Reference
QuantLib::AnalyticEuropeanMargrabeEngine Class Reference
Analytic engine for European Margrabe option.
#include <analyticeuropeanmargrabeengine.hpp>
Public Member Functions
AnalyticEuropeanMargrabeEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > &process1, const boost::shared_ptr< GeneralizedBlackScholesProcess > &process2, Real correlation)
void calculate () const
Private Attributes
boost::shared_ptr
< GeneralizedBlackScholesProcess > process1_
boost::shared_ptr
< GeneralizedBlackScholesProcess > process2_
Real rho_
Detailed Description
Analytic engine for European Margrabe option.
This class implements formulae from "The Value of an Option to Exchange One Asset for Another", W. Margrabe, Journal of Finance, 33 (March 1978), 177-186.
Test:
the correctness of the returned value is tested by reproducing results available in literature.
Definition at line 41 of file analyticeuropeanmargrabeengine.hpp.
Constructor & Destructor Documentation
QuantLib::AnalyticEuropeanMargrabeEngine::AnalyticEuropeanMargrabeEngine (const boost::shared_ptr< GeneralizedBlackScholesProcess > & process1, const boost::shared_ptr< GeneralizedBlackScholesProcess > & process2, Real correlation)
Definition at line 27 of file analyticeuropeanmargrabeengine.cpp.
References process1_, process2_, and QuantLib::Observer::registerWith().
    : process1_(process1), process2_(process2), rho_(correlation) {
        registerWith(process1_);
        registerWith(process2_);
    }
Member Function Documentation
void QuantLib::AnalyticEuropeanMargrabeEngine::calculate () const [virtual]
Implements QuantLib::PricingEngine.
Definition at line 36 of file analyticeuropeanmargrabeengine.cpp.
References QuantLib::GenericEngine< MargrabeOption::arguments, MargrabeOption::results >::arguments_, QuantLib::MargrabeOption::results::delta1, QuantLib::MargrabeOption::results::delta2, QuantLib::Exercise::European, QuantLib::Option::arguments::exercise, QuantLib::MargrabeOption::results::gamma1, QuantLib::MargrabeOption::results::gamma2, QuantLib::norm(), QuantLib::Option::arguments::payoff, process1_, process2_, QuantLib::MargrabeOption::arguments::Q1, QuantLib::MargrabeOption::arguments::Q2, QL_REQUIRE, QuantLib::GenericEngine< MargrabeOption::arguments, MargrabeOption::results >::results_, QuantLib::Greeks::rho, rho_, anonymous_namespace{quantlibbenchmark.cpp}::t, QuantLib::Greeks::theta, QuantLib::Instrument::results::value, and QuantLib::DayCounter::yearFraction().
{
        QL_REQUIRE(arguments_.exercise->type() == Exercise::European,
                   "not an European Option");
        boost::shared_ptr<EuropeanExercise> exercise =
            boost::dynamic_pointer_cast<EuropeanExercise>(arguments_.exercise);
        QL_REQUIRE(exercise, "not an European Option");
        boost::shared_ptr<NullPayoff> payoff =
            boost::dynamic_pointer_cast<NullPayoff>(arguments_.payoff);
        QL_REQUIRE(payoff, "non a Null Payoff type");
        Integer quantity1 = arguments_.Q1;
        Integer quantity2 = arguments_.Q2;
        Real s1  = process1_->stateVariable()->value();
        Real s2  = process2_->stateVariable()->value();
        Real variance1 = process1_->blackVolatility()->blackVariance(
                                                exercise->lastDate(), s1);
        Real variance2 = process2_->blackVolatility()->blackVariance(
                                                exercise->lastDate(), s2);
        DiscountFactor riskFreeDiscount =
            process1_->riskFreeRate()->discount(exercise->lastDate());
        DiscountFactor dividendDiscount1 =
            process1_->dividendYield()->discount(exercise->lastDate());
        DiscountFactor dividendDiscount2 =
            process2_->dividendYield()->discount(exercise->lastDate());
        Real forward1 = process1_->stateVariable()->value() *
            dividendDiscount1 / riskFreeDiscount;
        Real forward2 = process2_->stateVariable()->value() *
            dividendDiscount2 / riskFreeDiscount;
        Real stdDev1 = std::sqrt(variance1);
        Real stdDev2 = std::sqrt(variance2);
        Real variance = variance1 + variance2 - 2*rho_*stdDev1*stdDev2;
        Real stdDev = std::sqrt(variance);
        Real d1 = (std::log((quantity1*forward1)/(quantity2*forward2))
                   + 0.5*variance) / stdDev;
        Real d2 = d1 - stdDev;
        Real Nd1, Nd2, nd1, nd2;
        CumulativeNormalDistribution cum;
        NormalDistribution norm;
        Nd1 = cum(d1);
        Nd2 = cum(d2);
        nd1 = norm(d1);
        nd2 = norm(d2);
        DayCounter rfdc  = process1_->riskFreeRate()->dayCounter();
        Time t = rfdc.yearFraction(process1_->riskFreeRate()->referenceDate(),
                                  arguments_.exercise->lastDate());
        Real sqt = std::sqrt(t);
        Real q1  = -std::log(dividendDiscount1)/(sqt*sqt);
        Real q2  = -std::log(dividendDiscount2)/(sqt*sqt);
        results_.value =
            riskFreeDiscount * (quantity1*forward1*Nd1 - quantity2*forward2*Nd2);
        // Greeks
        results_.delta1 = riskFreeDiscount*(quantity1*forward1*Nd1)/s1;
        results_.delta2 = -riskFreeDiscount*(quantity2*forward2*Nd2)/s2;
        results_.gamma1 = (riskFreeDiscount*(quantity1*forward1*nd1)/s1)/(quantity1*s1*stdDev);
        results_.gamma2 = (-riskFreeDiscount*(quantity2*forward2*nd2)/s2)/(-quantity2*s2*stdDev);
        Real vega       = riskFreeDiscount*(quantity1*forward1*nd1)*sqt;
        results_.theta  = -((stdDev*vega/sqt)/(2*t)-(q1*quantity1*s1*results_.delta1)-(q2*quantity2*s2*results_.delta2));
        results_.rho    = 0.0;
    }
Member Data Documentation
boost::shared_ptr<GeneralizedBlackScholesProcess> QuantLib::AnalyticEuropeanMargrabeEngine::process1_ [private]
Definition at line 49 of file analyticeuropeanmargrabeengine.hpp.
Referenced by AnalyticEuropeanMargrabeEngine(), and calculate().
boost::shared_ptr<GeneralizedBlackScholesProcess> QuantLib::AnalyticEuropeanMargrabeEngine::process2_ [private]
Definition at line 50 of file analyticeuropeanmargrabeengine.hpp.
Referenced by AnalyticEuropeanMargrabeEngine(), and calculate().
Real QuantLib::AnalyticEuropeanMargrabeEngine::rho_ [private]
Definition at line 51 of file analyticeuropeanmargrabeengine.hpp.
Referenced by calculate().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/exoticoptions/analyticeuropeanmargrabeengine.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/exoticoptions/analyticeuropeanmargrabeengine.cpp