QuantLib: QuantLib::UnitOfMeasureConversion Class Reference
QuantLib::UnitOfMeasureConversion Class Reference
#include <unitofmeasureconversion.hpp>
Classes
struct Data
Public Types
enum Type { Direct, Derived }
Public Member Functions
Constructors
UnitOfMeasureConversion ()
UnitOfMeasureConversion (const CommodityType &commodityType, const UnitOfMeasure &source, const UnitOfMeasure &target, Real conversionFactor)
Inspectors
const UnitOfMeasure & source () const
the source UOM.
const UnitOfMeasure & target () const
the target UOM.
const CommodityType & commodityType () const
the commodity type.
Type type () const
the type
Real conversionFactor () const
the conversion factor
const std::string & code () const
Protected Member Functions
UnitOfMeasureConversion (const UnitOfMeasureConversion &r1, const UnitOfMeasureConversion &r2)
Protected Attributes
boost::shared_ptr< Data > data_
Utility methods
Quantity convert (const Quantity &quantity) const
apply the conversion factor to a cash amount
static UnitOfMeasureConversion chain (const UnitOfMeasureConversion &r1, const UnitOfMeasureConversion &r2)
chain two conversion factors
Detailed Description
Definition at line 35 of file unitofmeasureconversion.hpp.
Member Enumeration Documentation
enum QuantLib::UnitOfMeasureConversion::Type
Enumerator:
Direct
given directly by the user
Derived
derived from conversion factors between other uoms
Definition at line 37 of file unitofmeasureconversion.hpp.
                  { Direct,
                    Derived
        };
Constructor & Destructor Documentation
QuantLib::UnitOfMeasureConversion::UnitOfMeasureConversion () [inline]
Definition at line 108 of file unitofmeasureconversion.hpp.
Referenced by QuantLib::UnitOfMeasureConversion::Data::Data().
{}
QuantLib::UnitOfMeasureConversion::UnitOfMeasureConversion (const CommodityType & commodityType, const UnitOfMeasure & source, const UnitOfMeasure & target, Real conversionFactor)
the conversionFactor \(r \) is given with the convention that a unit of the source is worth \(r \) units of the target.
Definition at line 29 of file unitofmeasureconversion.cpp.
References data_, and Direct.
{
        data_ = shared_ptr<UnitOfMeasureConversion::Data>(
              new UnitOfMeasureConversion::Data(commodityType, source, target,
                                                conversionFactor, Direct));
    }
QuantLib::UnitOfMeasureConversion::UnitOfMeasureConversion (const UnitOfMeasureConversion & r1, const UnitOfMeasureConversion & r2) [protected]
Definition at line 39 of file unitofmeasureconversion.cpp.
References data_.
{
        data_ = shared_ptr<UnitOfMeasureConversion::Data>(
                                   new UnitOfMeasureConversion::Data(r1, r2));
    }
Member Function Documentation
UnitOfMeasureConversion QuantLib::UnitOfMeasureConversion::chain (const UnitOfMeasureConversion & r1, const UnitOfMeasureConversion & r2) [static]
chain two conversion factors
Definition at line 95 of file unitofmeasureconversion.cpp.
References data_, Derived, and QL_FAIL.
Referenced by QuantLib::UnitOfMeasureConversionManager::lookup(), and QuantLib::UnitOfMeasureConversionManager::smartLookup().
{
        UnitOfMeasureConversion result(r1, r2);
        result.data_->type = Derived;
        if (r1.data_->source == r2.data_->source) {
            result.data_->source = r1.data_->target;
            result.data_->target = r2.data_->target;
            result.data_->conversionFactor =
                r2.data_->conversionFactor/r1.data_->conversionFactor;
        } else if (r1.data_->source == r2.data_->target) {
            result.data_->source = r1.data_->target;
            result.data_->target = r2.data_->source;
            result.data_->conversionFactor =
                1.0/(r1.data_->conversionFactor*r2.data_->conversionFactor);
        } else if (r1.data_->target == r2.data_->source) {
            result.data_->source = r1.data_->source;
            result.data_->target = r2.data_->target;
            result.data_->conversionFactor =
                r1.data_->conversionFactor*r2.data_->conversionFactor;
        } else if (r1.data_->target == r2.data_->target) {
            result.data_->source = r1.data_->source;
            result.data_->target = r2.data_->source;
            result.data_->conversionFactor =
                r1.data_->conversionFactor/r2.data_->conversionFactor;
        } else {
            QL_FAIL("conversion factors not chainable");
        }
        return result;
    }
const std::string & QuantLib::UnitOfMeasureConversion::code () const [inline]
Definition at line 130 of file unitofmeasureconversion.hpp.
References data_.
{
        return data_->code;
    }
const CommodityType & QuantLib::UnitOfMeasureConversion::commodityType () const [inline]
the commodity type.
Definition at line 110 of file unitofmeasureconversion.hpp.
References data_.
Referenced by QuantLib::anonymous_namespace{unitofmeasureconversionmanager.cpp}::matches().
{
        return data_->commodityType;
    }
Real QuantLib::UnitOfMeasureConversion::conversionFactor () const [inline]
the conversion factor
Definition at line 122 of file unitofmeasureconversion.hpp.
References data_.
Referenced by QuantLib::CommodityPricingHelper::calculateUomConversionFactor(), and QuantLib::EnergyCommodity::calculateUomConversionFactor().
{
        return data_->conversionFactor;
    }
Quantity QuantLib::UnitOfMeasureConversion::convert (const Quantity & quantity) const
apply the conversion factor to a cash amount
Definition at line 62 of file unitofmeasureconversion.cpp.
References QuantLib::Quantity::amount(), QuantLib::Quantity::commodityType(), data_, Derived, Direct, QL_FAIL, and QuantLib::Quantity::unitOfMeasure().
Referenced by QuantLib::anonymous_namespace{quantity.cpp}::convertTo(), and CommodityUnitOfMeasureTest::testDirect().
{
        switch (data_->type) {
          case Direct:
            if (quantity.unitOfMeasure() == data_->source)
                return Quantity(quantity.commodityType(),
                                data_->target,
                                quantity.amount()*data_->conversionFactor);
            else if (quantity.unitOfMeasure() == data_->target)
                return Quantity(quantity.commodityType(),
                                data_->source,
                                quantity.amount()/data_->conversionFactor);
            else
                QL_FAIL("direct conversion not applicable");
          case Derived:
            if (quantity.unitOfMeasure()
                == data_->conversionFactorChain.first->source() ||
                quantity.unitOfMeasure()
                == data_->conversionFactorChain.first->target())
                return data_->conversionFactorChain.second->convert(
                       data_->conversionFactorChain.first->convert(quantity));
            else if (quantity.unitOfMeasure()
                     == data_->conversionFactorChain.second->source() ||
                     quantity.unitOfMeasure()
                     == data_->conversionFactorChain.second->target())
                return data_->conversionFactorChain.first->convert(
                      data_->conversionFactorChain.second->convert(quantity));
            else
                QL_FAIL("derived conversion factor not applicable");
          default:
            QL_FAIL("unknown conversion-factor type");
        }
    }
const UnitOfMeasure & QuantLib::UnitOfMeasureConversion::source () const [inline]
the source UOM.
Definition at line 114 of file unitofmeasureconversion.hpp.
References data_.
Referenced by QuantLib::anonymous_namespace{unitofmeasureconversionmanager.cpp}::matches().
{
        return data_->source;
    }
const UnitOfMeasure & QuantLib::UnitOfMeasureConversion::target () const [inline]
the target UOM.
Definition at line 118 of file unitofmeasureconversion.hpp.
References data_.
Referenced by QuantLib::anonymous_namespace{unitofmeasureconversionmanager.cpp}::matches().
{
        return data_->target;
    }
UnitOfMeasureConversion::Type QuantLib::UnitOfMeasureConversion::type () const [inline]
the type
Definition at line 126 of file unitofmeasureconversion.hpp.
References data_.
{
        return data_->type;
    }
Member Data Documentation
boost::shared_ptr<Data> QuantLib::UnitOfMeasureConversion::data_ [protected]
Definition at line 82 of file unitofmeasureconversion.hpp.
Referenced by chain(), code(), commodityType(), conversionFactor(), convert(), source(), target(), type(), and UnitOfMeasureConversion().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/commodities/unitofmeasureconversion.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/commodities/unitofmeasureconversion.cpp