QuantLib: QuantLib::OneFactorStudentGaussianCopula Class Reference
QuantLib::OneFactorStudentGaussianCopula Class Reference
One-factor Student t - Gaussian Copula.
#include <onefactorstudentcopula.hpp>
Public Member Functions
OneFactorStudentGaussianCopula (const Handle< Quote > &correlation, int nm, Real maximum=10, Size integrationSteps=200)
Real density (Real m) const
Density function of M.
Real cumulativeZ (Real z) const
Cumulative distribution of Z.
Private Member Functions
void performCalculations () const
Observer interface.
Real cumulativeYintegral (Real y) const
Private Attributes
StudentDistribution density_
CumulativeNormalDistribution cumulative_
int nm_
Real scaleM_
Detailed Description
One-factor Student t - Gaussian Copula.
The copula model
\[ Y_i = a_i\,M+\sqrt{1-a_i^2}\:Z_i \]
is specified here by setting the probability density functions for \(Z_i \) (\(D_Z \)) to a Gaussian and for \(M \) (\(D_M \)) to a Student t-distribution with \(N_m \) degrees of freedom.
The variance of the Student t-distribution with \(\nu \) degrees of freedom is \(\nu / (\nu - 2) \). Since the copula approach requires zero mean and unit variance distributions, \(M \) is scaled by \(\sqrt{(N_m - 2) / N_m}. \)
Todo:
Improve performance/accuracy of the calculation of inverse cumulative Y. Tabulate and store it for selected correlations?
Definition at line 161 of file onefactorstudentcopula.hpp.
Constructor & Destructor Documentation
QuantLib::OneFactorStudentGaussianCopula::OneFactorStudentGaussianCopula (const Handle< Quote > & correlation, int nm, Real maximum = 10, Size integrationSteps = 200)
Definition at line 191 of file onefactorstudentcopula.cpp.
References QuantLib::LazyObject::calculate(), nm_, QL_REQUIRE, and scaleM_.
    : OneFactorCopula (correlation, maximum, integrationSteps),
      density_ (nm), nm_(nm) {
    //-------------------------------------------------------------------------
        QL_REQUIRE (nm > 2, "degrees of freedom must be > 2");
        scaleM_ = std::sqrt (Real (nm_ - 2) / nm_);
        calculate ();
    }
Member Function Documentation
Real QuantLib::OneFactorStudentGaussianCopula::cumulativeYintegral (Real y) const [private]
Definition at line 227 of file onefactorstudentcopula.cpp.
References anonymous_namespace{marketmodel.cpp}::c, QuantLib::OneFactorCopula::correlation_, QuantLib::OneFactorCopula::dm(), QuantLib::OneFactorCopula::m(), nm_, scaleM_, and QuantLib::OneFactorCopula::steps().
Referenced by performCalculations().
{
    //-------------------------------------------------------------------------
        Real c = correlation_->value();
        if (c == 0)
            return CumulativeNormalDistribution()(y);
        if (c == 1)
            return CumulativeStudentDistribution(nm_)(y / scaleM_);
        StudentDistribution dm (nm_);
        NormalDistribution dz;
        // FIXME:
        // Find a sensitive way of setting these parameters,
        // e.g. depending on nm and nz, and the desired table range
        Real minimum = -10;
        Real maximum = +10;
        int steps = 400;
        Real delta = (maximum - minimum) / steps;
        Real cumulated = 0;
        if (c < 0.5) {
            // outer integral -> 1 for c -> 0
            // inner integral -> cumulativeNormal(y) for c-> 0
            for (Real m = minimum + delta/2; m < maximum; m += delta)
                for (Real z = minimum + delta/2;
                     z < (y - std::sqrt(c) * m) / std::sqrt (1. - c);
                     z += delta)
                    cumulated += dm (m / scaleM_) / scaleM_ * dz (z);
        }
        else {
            // outer integral -> 1 for c -> 1
            // inner integral -> cumulativeStudent(nm)(y) for c-> 1
            for (Real z = minimum + delta/2; z < maximum; z += delta)
                for (Real m = minimum + delta/2;
                     m < (y - std::sqrt(1.0 - c) * z) / std::sqrt(c);
                     m += delta)
                    cumulated += dm (m / scaleM_) / scaleM_ * dz (z);
        }
        return cumulated * delta * delta;
    }
Real QuantLib::OneFactorStudentGaussianCopula::cumulativeZ (Real z) const [inline, virtual]
Cumulative distribution of Z.
Derived classes must override this method and ensure zero mean and unit variance.
Implements QuantLib::OneFactorCopula.
Definition at line 191 of file onefactorstudentcopula.hpp.
References cumulative_.
{
        return cumulative_(z);
    }
Real QuantLib::OneFactorStudentGaussianCopula::density (Real m) const [inline, virtual]
Density function of M.
Derived classes must override this method and ensure zero mean and unit variance.
Implements QuantLib::OneFactorCopula.
Definition at line 187 of file onefactorstudentcopula.hpp.
References density_, and scaleM_.
{
        return density_(m / scaleM_) / scaleM_;
    }
void QuantLib::OneFactorStudentGaussianCopula::performCalculations () const [private, virtual]
Observer interface.
Implements QuantLib::LazyObject.
Definition at line 207 of file onefactorstudentcopula.cpp.
References anonymous_namespace{marketmodel.cpp}::c, QuantLib::OneFactorCopula::cumulativeY_, cumulativeYintegral(), QuantLib::OneFactorCopula::steps(), and QuantLib::OneFactorCopula::y_.
{
    //-------------------------------------------------------------------------
        y_.clear();
        cumulativeY_.clear();
        // FIXME:
        // compute F(ymin) and F(ymax) for the fattest case nm = nz = 2
        // set a desired confidence and work out ymin, ymax
        Real ymin = -10;
        Real ymax = +10;
        Size steps = 200;
        for (Size i = 0; i <= steps; i++) {
            Real y = ymin + (ymax - ymin) * i / steps;
            Real c = cumulativeYintegral (y);
            y_.push_back (y);
            cumulativeY_.push_back (c);
        }
    }
Member Data Documentation
CumulativeNormalDistribution QuantLib::OneFactorStudentGaussianCopula::cumulative_ [private]
Definition at line 176 of file onefactorstudentcopula.hpp.
Referenced by cumulativeZ().
StudentDistribution QuantLib::OneFactorStudentGaussianCopula::density_ [private]
Definition at line 175 of file onefactorstudentcopula.hpp.
Referenced by density().
int QuantLib::OneFactorStudentGaussianCopula::nm_ [private]
Definition at line 177 of file onefactorstudentcopula.hpp.
Referenced by cumulativeYintegral(), and OneFactorStudentGaussianCopula().
Real QuantLib::OneFactorStudentGaussianCopula::scaleM_ [private]
Definition at line 179 of file onefactorstudentcopula.hpp.
Referenced by cumulativeYintegral(), density(), and OneFactorStudentGaussianCopula().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/onefactorstudentcopula.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/experimental/credit/onefactorstudentcopula.cpp