QuantLib: QuantLib::PiecewiseTimeDependentHestonModel Class Reference
QuantLib::PiecewiseTimeDependentHestonModel Class Reference
Piecewise time dependent Heston model.
#include <piecewisetimedependenthestonmodel.hpp>
Public Member Functions
PiecewiseTimeDependentHestonModel (const Handle< YieldTermStructure > &riskFreeRate, const Handle< YieldTermStructure > &dividendYield, const Handle< Quote > &s0, Real v0, const Parameter &theta, const Parameter &kappa, const Parameter &sigma, const Parameter &rho, const TimeGrid &timeGrid)
Real theta (Time t) const
Real kappa (Time t) const
Real sigma (Time t) const
Real rho (Time t) const
Real v0 () const
Real s0 () const
const TimeGrid & timeGrid () const
const Handle
< YieldTermStructure > & dividendYield () const
const Handle
< YieldTermStructure > & riskFreeRate () const
Protected Attributes
const Handle< Quote > s0_
const Handle< YieldTermStructure > riskFreeRate_
const Handle< YieldTermStructure > dividendYield_
const TimeGrid timeGrid_
Detailed Description
Piecewise time dependent Heston model.
References:
Heston, Steven L., 1993. A Closed-Form Solution for Options with Stochastic Volatility with Applications to Bond and Currency Options. The review of Financial Studies, Volume 6, Issue 2, 327-343.
A. Elices, Models with time-dependent parameters using transform methods: application to Heston’s model, http://arxiv.org/pdf/0708.2020
Definition at line 44 of file piecewisetimedependenthestonmodel.hpp.
Constructor & Destructor Documentation
QuantLib::PiecewiseTimeDependentHestonModel::PiecewiseTimeDependentHestonModel (const Handle< YieldTermStructure > & riskFreeRate, const Handle< YieldTermStructure > & dividendYield, const Handle< Quote > & s0, Real v0, const Parameter & theta, const Parameter & kappa, const Parameter & sigma, const Parameter & rho, const TimeGrid & timeGrid)
Definition at line 25 of file piecewisetimedependenthestonmodel.cpp.
References QuantLib::CalibratedModel::arguments_, kappa(), QuantLib::Observer::registerWith(), rho(), sigma(), and theta().
    : CalibratedModel(5),
      s0_           (s0),
      riskFreeRate_ (riskFreeRate),
      dividendYield_(dividendYield),
      timeGrid_     (timeGrid) {
        arguments_[0] = theta;
        arguments_[1] = kappa;
        arguments_[2] = sigma;
        arguments_[3] = rho;
        arguments_[4] = ConstantParameter(v0, PositiveConstraint());
        registerWith(s0);
        registerWith(riskFreeRate);
        registerWith(dividendYield);
    }
Member Function Documentation
const Handle< YieldTermStructure > & QuantLib::PiecewiseTimeDependentHestonModel::dividendYield () const
Definition at line 57 of file piecewisetimedependenthestonmodel.cpp.
References dividendYield_.
{
        return dividendYield_;
    }
Real QuantLib::PiecewiseTimeDependentHestonModel::kappa (Time t) const [inline]
Definition at line 60 of file piecewisetimedependenthestonmodel.hpp.
References QuantLib::CalibratedModel::arguments_, and anonymous_namespace{quantlibbenchmark.cpp}::t.
Referenced by PiecewiseTimeDependentHestonModel().
{ return arguments_[1](t); }
Real QuantLib::PiecewiseTimeDependentHestonModel::rho (Time t) const [inline]
Definition at line 64 of file piecewisetimedependenthestonmodel.hpp.
References QuantLib::CalibratedModel::arguments_, and anonymous_namespace{quantlibbenchmark.cpp}::t.
Referenced by PiecewiseTimeDependentHestonModel().
{ return arguments_[3](t); }
const Handle< YieldTermStructure > & QuantLib::PiecewiseTimeDependentHestonModel::riskFreeRate () const
Definition at line 62 of file piecewisetimedependenthestonmodel.cpp.
References riskFreeRate_.
{
        return riskFreeRate_;
    }
Real QuantLib::PiecewiseTimeDependentHestonModel::s0 () const [inline]
Definition at line 68 of file piecewisetimedependenthestonmodel.hpp.
References s0_.
{ return s0_->value(); }
Real QuantLib::PiecewiseTimeDependentHestonModel::sigma (Time t) const [inline]
Definition at line 62 of file piecewisetimedependenthestonmodel.hpp.
References QuantLib::CalibratedModel::arguments_, and anonymous_namespace{quantlibbenchmark.cpp}::t.
Referenced by PiecewiseTimeDependentHestonModel().
{ return arguments_[2](t); }
Real QuantLib::PiecewiseTimeDependentHestonModel::theta (Time t) const [inline]
Definition at line 58 of file piecewisetimedependenthestonmodel.hpp.
References QuantLib::CalibratedModel::arguments_, and anonymous_namespace{quantlibbenchmark.cpp}::t.
Referenced by PiecewiseTimeDependentHestonModel().
{ return arguments_[0](t); }
const TimeGrid & QuantLib::PiecewiseTimeDependentHestonModel::timeGrid () const
Definition at line 52 of file piecewisetimedependenthestonmodel.cpp.
References timeGrid_.
{
        return timeGrid_;
    }
Real QuantLib::PiecewiseTimeDependentHestonModel::v0 () const [inline]
Definition at line 66 of file piecewisetimedependenthestonmodel.hpp.
References QuantLib::CalibratedModel::arguments_.
{ return arguments_[4](0.0); }
Member Data Documentation
const Handle<YieldTermStructure> QuantLib::PiecewiseTimeDependentHestonModel::dividendYield_ [protected]
Definition at line 78 of file piecewisetimedependenthestonmodel.hpp.
Referenced by dividendYield().
const Handle<YieldTermStructure> QuantLib::PiecewiseTimeDependentHestonModel::riskFreeRate_ [protected]
Definition at line 77 of file piecewisetimedependenthestonmodel.hpp.
Referenced by riskFreeRate().
const Handle<Quote> QuantLib::PiecewiseTimeDependentHestonModel::s0_ [protected]
Definition at line 76 of file piecewisetimedependenthestonmodel.hpp.
Referenced by s0().
const TimeGrid QuantLib::PiecewiseTimeDependentHestonModel::timeGrid_ [protected]
Definition at line 79 of file piecewisetimedependenthestonmodel.hpp.
Referenced by timeGrid().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/equity/piecewisetimedependenthestonmodel.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/equity/piecewisetimedependenthestonmodel.cpp