QuantLib: QuantLib::anonymous_namespace{swaptionpseudojacobian.cpp}::QuickCap Class Reference
QuantLib::anonymous_namespace{swaptionpseudojacobian.cpp}::QuickCap Class Reference
Public Member Functions
QuickCap (Real Strike, const std::vector< Real > &annuities, const std::vector< Real > &currentRates, const std::vector< Real > &expiries, Real price)
Real operator() (Real volatility) const
Real vega (Real volatility) const
Private Attributes
Real strike_
const std::vector< Real > & annuities_
const std::vector< Real > & currentRates_
const std::vector< Real > & expiries_
Real price_
Detailed Description
Definition at line 159 of file swaptionpseudojacobian.cpp.
Constructor & Destructor Documentation
QuantLib::anonymous_namespace{swaptionpseudojacobian.cpp}::QuickCap::QuickCap (Real Strike, const std::vector< Real > & annuities, const std::vector< Real > & currentRates, const std::vector< Real > & expiries, Real price)
Definition at line 183 of file swaptionpseudojacobian.cpp.
            :
        strike_(Strike),
            annuities_(annuities),
            currentRates_(currentRates),
            expiries_(expiries),
            price_(price)
        {
        }
Member Function Documentation
Real QuantLib::anonymous_namespace{swaptionpseudojacobian.cpp}::QuickCap::operator() (Real volatility) const
Definition at line 197 of file swaptionpseudojacobian.cpp.
References annuities_, QuantLib::blackFormula(), QuantLib::Option::Call, currentRates_, expiries_, price_, and strike_.
        {
            Real price =0.0;
            for (Size i=0; i < annuities_.size(); ++i)
            {
                price += blackFormula(Option::Call,strike_,
                    currentRates_[i],
                    volatility*std::sqrt(expiries_[i]),
                    annuities_[i]);
            }
            return price-price_;
        }
Real QuantLib::anonymous_namespace{swaptionpseudojacobian.cpp}::QuickCap::vega (Real volatility) const
Definition at line 212 of file swaptionpseudojacobian.cpp.
References QuantLib::blackFormulaVolDerivative(), and QuantLib::io::volatility().
        {
            Real vega =0.0;
            for (Size i=0; i < annuities_.size(); ++i)
            {
                vega+= blackFormulaVolDerivative(strike_,currentRates_[i],
                                                 volatility*std::sqrt(expiries_[i]),
                                                 expiries_[i],
                                                 annuities_[i],
                                                 0.0);
            }
            return vega;
        }
Member Data Documentation
const std::vector<Real>& QuantLib::anonymous_namespace{swaptionpseudojacobian.cpp}::QuickCap::annuities_ [private]
Definition at line 176 of file swaptionpseudojacobian.cpp.
Referenced by operator()().
const std::vector<Real>& QuantLib::anonymous_namespace{swaptionpseudojacobian.cpp}::QuickCap::currentRates_ [private]
Definition at line 177 of file swaptionpseudojacobian.cpp.
Referenced by operator()().
const std::vector<Real>& QuantLib::anonymous_namespace{swaptionpseudojacobian.cpp}::QuickCap::expiries_ [private]
Definition at line 178 of file swaptionpseudojacobian.cpp.
Referenced by operator()().
Real QuantLib::anonymous_namespace{swaptionpseudojacobian.cpp}::QuickCap::price_ [private]
Definition at line 179 of file swaptionpseudojacobian.cpp.
Referenced by operator()().
Real QuantLib::anonymous_namespace{swaptionpseudojacobian.cpp}::QuickCap::strike_ [private]
Definition at line 175 of file swaptionpseudojacobian.cpp.
Referenced by operator()().
The documentation for this class was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/pathwisegreeks/swaptionpseudojacobian.cpp