QuantLib: QuantLib::Fdm1DimSolver Class Reference
QuantLib::Fdm1DimSolver Class Reference
#include <fdm1dimsolver.hpp>
Public Member Functions
Fdm1DimSolver (const FdmSolverDesc &solverDesc, const FdmSchemeDesc &schemeDesc, const boost::shared_ptr< FdmLinearOpComposite > &op)
Real interpolateAt (Real x) const
Real thetaAt (Real x) const
Real derivativeX (Real x) const
Real derivativeXX (Real x) const
Protected Member Functions
void performCalculations () const
Private Attributes
const FdmSolverDesc solverDesc_
const FdmSchemeDesc schemeDesc_
const boost::shared_ptr
< FdmLinearOpComposite > op_
const boost::shared_ptr
< FdmSnapshotCondition > thetaCondition_
const boost::shared_ptr
< FdmStepConditionComposite > conditions_
std::vector< Real > x_
std::vector< Real > initialValues_
Array resultValues_
boost::shared_ptr
< CubicInterpolation > interpolation_
Detailed Description
Definition at line 38 of file fdm1dimsolver.hpp.
Constructor & Destructor Documentation
QuantLib::Fdm1DimSolver::Fdm1DimSolver (const FdmSolverDesc & solverDesc, const FdmSchemeDesc & schemeDesc, const boost::shared_ptr< FdmLinearOpComposite > & op)
Definition at line 31 of file fdm1dimsolver.cpp.
References QuantLib::FdmSolverDesc::calculator, initialValues_, QuantLib::FdmSolverDesc::maturity, QuantLib::FdmSolverDesc::mesher, solverDesc_, and x_.
    : solverDesc_(solverDesc),
      schemeDesc_(schemeDesc),
      op_(op),
      thetaCondition_(new FdmSnapshotCondition(
        0.99*std::min(1.0/365.0,
           solverDesc.condition->stoppingTimes().empty()
                    ? solverDesc.maturity
                    : solverDesc.condition->stoppingTimes().front()))),
      conditions_(FdmStepConditionComposite::joinConditions(thetaCondition_,
                                                         solverDesc.condition)),
      x_            (solverDesc.mesher->layout()->size()),
      initialValues_(solverDesc.mesher->layout()->size()),
      resultValues_ (solverDesc.mesher->layout()->size()) {
        const boost::shared_ptr<FdmMesher> mesher = solverDesc.mesher;
        const boost::shared_ptr<FdmLinearOpLayout> layout = mesher->layout();
        const FdmLinearOpIterator endIter = layout->end();
        for (FdmLinearOpIterator iter = layout->begin(); iter != endIter;
             ++iter) {
            initialValues_[iter.index()]
                 = solverDesc_.calculator->avgInnerValue(iter,
                                                         solverDesc.maturity);
            x_[iter.index()] = mesher->location(iter, 0);
        }
    }
Member Function Documentation
Real QuantLib::Fdm1DimSolver::derivativeX (Real x) const
Definition at line 98 of file fdm1dimsolver.cpp.
References QuantLib::LazyObject::calculate(), and interpolation_.
{
        calculate();
        return interpolation_->derivative(x);
    }
Real QuantLib::Fdm1DimSolver::derivativeXX (Real x) const
Definition at line 103 of file fdm1dimsolver.cpp.
References QuantLib::LazyObject::calculate(), and interpolation_.
{
        calculate();
        return interpolation_->secondDerivative(x);
    }
Real QuantLib::Fdm1DimSolver::interpolateAt (Real x) const
Definition at line 77 of file fdm1dimsolver.cpp.
References QuantLib::LazyObject::calculate(), and interpolation_.
Referenced by thetaAt().
{
        calculate();
        return interpolation_->operator()(x);
    }
void QuantLib::Fdm1DimSolver::performCalculations () const [protected, virtual]
This method must implement any calculations which must be (re)done in order to calculate the desired results.
Implements QuantLib::LazyObject.
Definition at line 63 of file fdm1dimsolver.cpp.
References QuantLib::FdmSolverDesc::bcSet, QuantLib::Array::begin(), conditions_, QuantLib::FdmSolverDesc::dampingSteps, initialValues_, interpolation_, QuantLib::FdmSolverDesc::maturity, op_, resultValues_, QuantLib::FdmBackwardSolver::rollback(), schemeDesc_, solverDesc_, QuantLib::FdmSolverDesc::timeSteps, and x_.
{
        Array rhs(initialValues_.size());
        std::copy(initialValues_.begin(), initialValues_.end(), rhs.begin());
        FdmBackwardSolver(op_, solverDesc_.bcSet, conditions_, schemeDesc_)
            .rollback(rhs, solverDesc_.maturity, 0.0,
                      solverDesc_.timeSteps, solverDesc_.dampingSteps);
        std::copy(rhs.begin(), rhs.end(), resultValues_.begin());
        interpolation_ = boost::shared_ptr<CubicInterpolation>(new
            MonotonicCubicNaturalSpline(x_.begin(), x_.end(),
                                        resultValues_.begin()));
    }
Real QuantLib::Fdm1DimSolver::thetaAt (Real x) const
Definition at line 82 of file fdm1dimsolver.cpp.
References QuantLib::LazyObject::calculate(), conditions_, interpolateAt(), QL_REQUIRE, resultValues_, QuantLib::Array::size(), thetaCondition_, and x_.
{
        QL_REQUIRE(conditions_->stoppingTimes().front() > 0.0,
                   "stopping time at zero-> can't calculate theta");
        calculate();
        Array thetaValues(resultValues_.size());
        const Array& rhs = thetaCondition_->getValues();
        std::copy(rhs.begin(), rhs.end(), thetaValues.begin());
        Real temp = MonotonicCubicNaturalSpline(
            x_.begin(), x_.end(), thetaValues.begin())(x);
        return ( temp - interpolateAt(x) ) / thetaCondition_->getTime();
    }
Member Data Documentation
const boost::shared_ptr<FdmStepConditionComposite> QuantLib::Fdm1DimSolver::conditions_ [private]
Definition at line 59 of file fdm1dimsolver.hpp.
Referenced by performCalculations(), and thetaAt().
std::vector<Real> QuantLib::Fdm1DimSolver::initialValues_ [private]
Definition at line 61 of file fdm1dimsolver.hpp.
Referenced by Fdm1DimSolver(), and performCalculations().
boost::shared_ptr<CubicInterpolation> QuantLib::Fdm1DimSolver::interpolation_ [mutable, private]
Definition at line 63 of file fdm1dimsolver.hpp.
Referenced by derivativeX(), derivativeXX(), interpolateAt(), and performCalculations().
const boost::shared_ptr<FdmLinearOpComposite> QuantLib::Fdm1DimSolver::op_ [private]
Definition at line 56 of file fdm1dimsolver.hpp.
Referenced by performCalculations().
Array QuantLib::Fdm1DimSolver::resultValues_ [mutable, private]
Definition at line 62 of file fdm1dimsolver.hpp.
Referenced by performCalculations(), and thetaAt().
const FdmSchemeDesc QuantLib::Fdm1DimSolver::schemeDesc_ [private]
Definition at line 55 of file fdm1dimsolver.hpp.
Referenced by performCalculations().
const FdmSolverDesc QuantLib::Fdm1DimSolver::solverDesc_ [private]
Definition at line 54 of file fdm1dimsolver.hpp.
Referenced by Fdm1DimSolver(), and performCalculations().
const boost::shared_ptr<FdmSnapshotCondition> QuantLib::Fdm1DimSolver::thetaCondition_ [private]
Definition at line 58 of file fdm1dimsolver.hpp.
Referenced by thetaAt().
std::vector<Real> QuantLib::Fdm1DimSolver::x_ [private]
Definition at line 61 of file fdm1dimsolver.hpp.
Referenced by Fdm1DimSolver(), performCalculations(), and thetaAt().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/solvers/fdm1dimsolver.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/solvers/fdm1dimsolver.cpp