QuantLib: QuantLib::TriggeredSwapExercise Class Reference
QuantLib::TriggeredSwapExercise Class Reference
#include <triggeredswapexercise.hpp>
Public Member Functions
TriggeredSwapExercise (const std::vector< Time > &rateTimes, const std::vector< Time > &exerciseTimes, const std::vector< Rate > &strikes)
Size numberOfExercises () const
const EvolutionDescription & evolution () const
void nextStep (const CurveState &)
void reset ()
std::valarray< bool > isExerciseTime () const
void values (const CurveState &, std::vector< Real > &results) const
std::vector< Size > numberOfVariables () const
std::vector< Size > numberOfParameters () const
bool exercise (Size exerciseNumber, const std::vector< Real > &parameters, const std::vector< Real > &variables) const
void guess (Size exerciseNumber, std::vector< Real > &parameters) const
std::auto_ptr
< MarketModelParametricExercise > clone () const
Private Attributes
std::vector< Time > rateTimes_
std::vector< Time > exerciseTimes_
std::vector< Rate > strikes_
Size currentStep_
std::vector< Size > rateIndex_
EvolutionDescription evolution_
Detailed Description
Definition at line 28 of file triggeredswapexercise.hpp.
Constructor & Destructor Documentation
QuantLib::TriggeredSwapExercise::TriggeredSwapExercise (const std::vector< Time > & rateTimes, const std::vector< Time > & exerciseTimes, const std::vector< Rate > & strikes)
Definition at line 26 of file triggeredswapexercise.cpp.
References rateIndex_.
Referenced by clone().
    : rateTimes_(rateTimes), exerciseTimes_(exerciseTimes),
      strikes_(strikes), currentStep_(0), rateIndex_(exerciseTimes.size()),
      evolution_(rateTimes, exerciseTimes) {
        Size j = 0;
        for (Size i=0; i<exerciseTimes.size(); ++i) {
            while (j < rateTimes.size() && rateTimes[j] < exerciseTimes[i])
                ++j;
            rateIndex_[i] = j;
        }
    }
Member Function Documentation
std::auto_ptr< MarketModelParametricExercise > QuantLib::TriggeredSwapExercise::clone () const [virtual]
Implements QuantLib::MarketModelParametricExercise.
Definition at line 90 of file triggeredswapexercise.cpp.
References TriggeredSwapExercise().
{
        return std::auto_ptr<MarketModelParametricExercise>(
                                            new TriggeredSwapExercise(*this));
    }
const EvolutionDescription & QuantLib::TriggeredSwapExercise::evolution () const [virtual]
Implements QuantLib::MarketModelNodeDataProvider.
Definition at line 45 of file triggeredswapexercise.cpp.
References evolution_.
{
        return evolution_;
    }
bool QuantLib::TriggeredSwapExercise::exercise (Size exerciseNumber, const std::vector< Real > & parameters, const std::vector< Real > & variables) const [virtual]
Implements QuantLib::ParametricExercise.
Definition at line 76 of file triggeredswapexercise.cpp.
{
        return variables[0] >= parameters[0];
    }
void QuantLib::TriggeredSwapExercise::guess (Size exerciseNumber, std::vector< Real > & parameters) const [virtual]
Implements QuantLib::ParametricExercise.
Definition at line 83 of file triggeredswapexercise.cpp.
References strikes_.
{
        parameters.resize(1);
        parameters[0] = strikes_.at(exerciseIndex);
    }
std::valarray< bool > QuantLib::TriggeredSwapExercise::isExerciseTime () const [virtual]
Implements QuantLib::MarketModelNodeDataProvider.
Definition at line 57 of file triggeredswapexercise.cpp.
References numberOfExercises().
{
        return std::valarray<bool>(true,numberOfExercises());
    }
void QuantLib::TriggeredSwapExercise::nextStep (const CurveState &) [virtual]
Implements QuantLib::MarketModelNodeDataProvider.
Definition at line 49 of file triggeredswapexercise.cpp.
References currentStep_.
{
        ++currentStep_;
    }
Size QuantLib::TriggeredSwapExercise::numberOfExercises () const [virtual]
Implements QuantLib::MarketModelNodeDataProvider.
Definition at line 41 of file triggeredswapexercise.cpp.
References exerciseTimes_.
Referenced by isExerciseTime(), numberOfParameters(), and numberOfVariables().
{
        return exerciseTimes_.size();
    }
std::vector< Size > QuantLib::TriggeredSwapExercise::numberOfParameters () const [virtual]
Implements QuantLib::ParametricExercise.
Definition at line 72 of file triggeredswapexercise.cpp.
References numberOfExercises().
{
        return std::vector<Size>(numberOfExercises(), 1);
    }
std::vector< Size > QuantLib::TriggeredSwapExercise::numberOfVariables () const [virtual]
Implements QuantLib::ParametricExercise.
Definition at line 68 of file triggeredswapexercise.cpp.
References numberOfExercises().
{
        return std::vector<Size>(numberOfExercises(), 1);
    }
void QuantLib::TriggeredSwapExercise::reset () [virtual]
Implements QuantLib::MarketModelNodeDataProvider.
Definition at line 53 of file triggeredswapexercise.cpp.
References currentStep_.
{
        currentStep_ = 0;
    }
void QuantLib::TriggeredSwapExercise::values (const CurveState & state, std::vector< Real > & results) const [virtual]
Implements QuantLib::MarketModelNodeDataProvider.
Definition at line 61 of file triggeredswapexercise.cpp.
References QuantLib::CurveState::coterminalSwapRate(), currentStep_, and rateIndex_.
{
        Size swapIndex = rateIndex_[currentStep_-1];
        results.resize(1);
        results[0] = state.coterminalSwapRate(swapIndex);
    }
Member Data Documentation
Size QuantLib::TriggeredSwapExercise::currentStep_ [private]
Definition at line 57 of file triggeredswapexercise.hpp.
Referenced by nextStep(), reset(), and values().
EvolutionDescription QuantLib::TriggeredSwapExercise::evolution_ [private]
Definition at line 59 of file triggeredswapexercise.hpp.
Referenced by evolution().
std::vector<Time> QuantLib::TriggeredSwapExercise::exerciseTimes_ [private]
Definition at line 55 of file triggeredswapexercise.hpp.
Referenced by numberOfExercises().
std::vector<Size> QuantLib::TriggeredSwapExercise::rateIndex_ [private]
Definition at line 58 of file triggeredswapexercise.hpp.
Referenced by TriggeredSwapExercise(), and values().
std::vector<Time> QuantLib::TriggeredSwapExercise::rateTimes_ [private]
Definition at line 55 of file triggeredswapexercise.hpp.
std::vector<Rate> QuantLib::TriggeredSwapExercise::strikes_ [private]
Definition at line 56 of file triggeredswapexercise.hpp.
Referenced by guess().
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/callability/triggeredswapexercise.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/models/marketmodels/callability/triggeredswapexercise.cpp