QuantLib: QuantLib::DateParser Class Reference
QuantLib::DateParser Class Reference
#include <dataparsers.hpp>
Static Public Member Functions
static std::vector< std::string > split (const std::string &str, char delim)
static Date parse (const std::string &str, const std::string &fmt)
static Date parseISO (const std::string &str)
Detailed Description
Definition at line 48 of file dataparsers.hpp.
Member Function Documentation
Date QuantLib::DateParser::parse (const std::string & str, const std::string & fmt) [static]
Definition at line 115 of file dataparsers.cpp.
References anonymous_namespace{marketmodel.cpp}::d, split(), anonymous_namespace{quotes.cpp}::sub(), and QuantLib::io::to_integer().
{
        std::vector<std::string> slist;
        std::vector<std::string> flist;
        Integer d=0, m=0, y=0;
        slist = split(str,'/');
        flist = split(fmt,'/');
        if (slist.size() != flist.size())
            return Null<Date>();
        Size i;
        for (i=0;i<flist.size();i++) {
            std::string sub = flist[i];
            if (boost::algorithm::to_lower_copy(sub) == "dd")
                //  d = boost::lexical_cast<Integer>(slist[i]);
                d = io::to_integer(slist[i]);
            else if (boost::algorithm::to_lower_copy(sub) == "mm")
                //     m = boost::lexical_cast<Integer>(slist[i]);
                m = io::to_integer( slist[i]);
            else if (boost::algorithm::to_lower_copy(sub) == "yyyy") {
                //     y = boost::lexical_cast<Integer>(slist[i]);
                y = io::to_integer(slist[i]);
                if (y < 100)
                    y += 2000;
            }
        }
        return Date(d,Month(m),y);
    }
Date QuantLib::DateParser::parseISO (const std::string & str) [static]
Definition at line 143 of file dataparsers.cpp.
References QL_REQUIRE, and QuantLib::io::to_integer().
Referenced by DateTest::isoDates().
{
        QL_REQUIRE(str.size() == 10 && str[4] == '-' && str[7] == '-',
                   "invalid format");
        Integer year = //boost::lexical_cast<Integer>(str.substr(0, 4));
            io::to_integer(str.substr(0, 4));
        Month month =
            //  static_cast<Month>(boost::lexical_cast<Integer>(str.substr(5, 2)));
            static_cast<Month>(io::to_integer(str.substr(5, 2)));
        Integer day = //boost::lexical_cast<Integer>(str.substr(8, 2));
            static_cast<Month>(io::to_integer(str.substr(8, 2)));
        return Date(day, month, year);
    }
std::vector< std::string > QuantLib::DateParser::split (const std::string & str, char delim) [static]
Definition at line 101 of file dataparsers.cpp.
Referenced by parse().
{
        std::vector<std::string> list;
        Size sx= str.find(delim), so=0;
        while (sx != std::string::npos) {
            list.push_back(str.substr(so,sx));
            so += sx+1;
            sx = str.substr(so).find(delim);
        }
        list.push_back(str.substr(so));
        return list;
    }
The documentation for this class was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/utilities/dataparsers.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/utilities/dataparsers.cpp