QuantLib: Output manipulators
Output manipulators
Functions
detail::short_date_holder QuantLib::io::short_date (const Date &)
output dates in short format (mm/dd/yyyy)
detail::long_date_holder QuantLib::io::long_date (const Date &)
output dates in long format (Month ddth, yyyy)
detail::iso_date_holder QuantLib::io::iso_date (const Date &)
output dates in ISO format (yyyy-mm-dd)
detail::long_period_holder QuantLib::io::long_period (const Period &)
output periods in long format (e.g. "2 weeks")
detail::short_period_holder QuantLib::io::short_period (const Period &)
output periods in short format (e.g. "2w")
detail::ordinal_holder QuantLib::io::ordinal (Size)
outputs naturals as 1st, 2nd, 3rd...
detail::percent_holder QuantLib::io::percent (Real)
output reals as percentages
detail::percent_holder QuantLib::io::rate (Rate)
output rates and spreads as percentages
detail::percent_holder QuantLib::io::volatility (Volatility)
output volatilities as percentages
template<class Container >
detail::sequence_holder
< typename
Container::const_iterator > QuantLib::io::sequence (const Container &c)
output STL-compliant containers as space-separated sequences
Variables
detail::long_weekday_holder QuantLib::io::long_weekday (Weekday)
output weekdays in long format
detail::short_weekday_holder QuantLib::io::short_weekday (Weekday)
output weekdays in short format (three letters)
detail::shortest_weekday_holder QuantLib::io::shortest_weekday (Weekday)
output weekdays in shortest format (two letters)
detail::null_checker< T > QuantLib::io::checknull (T)
check for nulls before output
detail::power_of_two_holder< T > QuantLib::io::power_of_two (T)
output integers as powers of two
Detailed Description
Helper functions for creating formatted output.
Function Documentation
detail::iso_date_holder QuantLib::io::iso_date (const Date &)
output dates in ISO format (yyyy-mm-dd)
Definition at line 498 of file date.cpp.
Referenced by QuantLib::EnergyFuture::performCalculations(), QuantLib::EnergyBasisSwap::performCalculations(), and QuantLib::EnergyVanillaSwap::performCalculations().
{
            return detail::iso_date_holder(d);
        }
detail::long_date_holder QuantLib::io::long_date (const Date &)
output dates in long format (Month ddth, yyyy)
Definition at line 494 of file date.cpp.
Referenced by QuantLib::operator<<().
{
            return detail::long_date_holder(d);
        }
detail::long_period_holder QuantLib::io::long_period (const Period &)
output periods in long format (e.g. "2 weeks")
Definition at line 472 of file period.cpp.
{
            return detail::long_period_holder(p);
        }
detail::ordinal_holder QuantLib::io::ordinal (Size n) [inline]
outputs naturals as 1st, 2nd, 3rd...
Definition at line 116 of file dataformatters.hpp.
Referenced by QuantLib::DiscountingSwapEngine::calculate(), QuantLib::IterativeBootstrap< Curve >::calculate(), QuantLib::JumpDiffusionEngine::calculate(), QuantLib::LocalBootstrap< Curve >::calculate(), QuantLib::CapFloorTermVolSurface::CapFloorTermVolSurface(), anonymous_namespace{marketmodel_cms.cpp}::checkCMSAndSwaptions(), QuantLib::checkCompatibility(), anonymous_namespace{marketmodel_smm.cpp}::checkCoterminalSwapsAndSwaptions(), anonymous_namespace{marketmodel.cpp}::checkForwardsAndOptionlets(), QuantLib::StrippedOptionlet::checkInputs(), QuantLib::SabrVolSurface::checkInputs(), QuantLib::AbcdAtmVolCurve::checkInputs(), QuantLib::CapFloorTermVolCurve::checkInputs(), QuantLib::CapFloorTermVolSurface::checkInputs(), anonymous_namespace{marketmodel.cpp}::checkMultiProductCompositeResults(), anonymous_namespace{marketmodel.cpp}::checkNormalForwardsAndOptionlets(), QuantLib::SwaptionVolatilityDiscrete::checkOptionDates(), QuantLib::SwaptionVolatilityDiscrete::checkOptionTenors(), anonymous_namespace{stats.cpp}::checkSequence(), QuantLib::SwaptionVolatilityDiscrete::checkSwapTenors(), QuantLib::CotSwapToFwdAdapter::CotSwapToFwdAdapter(), QuantLib::YieldTermStructure::discount(), QuantLib::FwdToCotSwapAdapter::FwdToCotSwapAdapter(), QuantLib::getCovariance(), QuantLib::detail::operator<<(), QuantLib::CapFloor::optionlet(), QuantLib::YoYInflationCapFloor::optionlet(), QuantLib::FittedBondDiscountCurve::performCalculations(), QuantLib::RendistatoBasket::RendistatoBasket(), QuantLib::DefaultProbabilityTermStructure::survivalProbability(), QuantLib::SwaptionVolatilityCube::SwaptionVolatilityCube(), InterpolationTest::testAsFunctor(), InterpolationTest::testBackwardFlat(), OperatorTest::testBSMOperatorConsistency(), ArrayTest::testConstruction(), SampledCurveTest::testConstruction(), anonymous_namespace{piecewiseyieldcurve.cpp}::testCurveConsistency(), MarketModelTest::testDriftCalculator(), LowDiscrepancyTest::testFaure(), InterpolationTest::testForwardFlat(), MarketModelSmmCapletAlphaCalibrationTest::testFunction(), MarketModelSmmCapletHomoCalibrationTest::testFunction(), MarketModelSmmCapletCalibrationTest::testFunction(), MarketModelTest::testGreeks(), LowDiscrepancyTest::testHalton(), MarketModelTest::testIsInSubset(), anonymous_namespace{pathgenerator.cpp}::testMultiple(), MarketModelTest::testPeriodAdapter(), MarketModelSmmCapletHomoCalibrationTest::testPeriodFunction(), LowDiscrepancyTest::testSobol(), QuantLib::DividendBarrierOption::arguments::validate(), and QuantLib::DividendVanillaOption::arguments::validate().
{
            return detail::ordinal_holder(n);
        }
detail::percent_holder QuantLib::io::percent (Real x) [inline]
output reals as percentages
Definition at line 125 of file dataformatters.hpp.
Referenced by anonymous_namespace{marketmodel_cms.cpp}::checkCMSAndSwaptions(), and anonymous_namespace{marketmodel_smm.cpp}::checkCoterminalSwapsAndSwaptions().
{
            return detail::percent_holder(x);
        }
detail::percent_holder QuantLib::io::rate (Rate r) [inline]
output rates and spreads as percentages
Definition at line 129 of file dataformatters.hpp.
Referenced by QuantLib::CapPseudoDerivative::CapPseudoDerivative(), anonymous_namespace{marketmodel.cpp}::checkCallableSwap(), anonymous_namespace{marketmodel_cms.cpp}::checkCMSAndSwaptions(), anonymous_namespace{marketmodel_smm.cpp}::checkCoterminalSwapsAndSwaptions(), anonymous_namespace{marketmodel.cpp}::checkForwardsAndOptionlets(), QuantLib::StrippedOptionlet::checkInputs(), QuantLib::CapFloorTermVolSurface::checkInputs(), anonymous_namespace{marketmodel.cpp}::checkMultiProductCompositeResults(), anonymous_namespace{marketmodel.cpp}::checkNormalForwardsAndOptionlets(), anonymous_namespace{termstructures.cpp}::CommonVars::CommonVars(), anonymous_namespace{inflationcpiswap.cpp}::CommonVars::CommonVars(), anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::CommonVars(), anonymous_namespace{piecewiseyieldcurve.cpp}::CommonVars::CommonVars(), QuantLib::anonymous_namespace{quantity.cpp}::convertTo(), QuantLib::anonymous_namespace{money.cpp}::convertTo(), QuantLib::ExchangeRateManager::directLookup(), QuantLib::OrthogonalizedBumpFinder::GetVegaBumps(), QuantLib::InterpolatedZeroCurve< Interpolator >::initialize(), anonymous_namespace{swaptionvolatilitycube.cpp}::CommonVars::makeAtmVolTest(), anonymous_namespace{inflationcpiswap.cpp}::makeHelpers(), anonymous_namespace{inflationcapfloor.cpp}::makeHelpers(), anonymous_namespace{inflation.cpp}::makeHelpers(), anonymous_namespace{inflationcpicapfloor.cpp}::makeHelpers(), anonymous_namespace{inflationcapflooredcoupon.cpp}::makeHelpers(), anonymous_namespace{swaptionvolatilitycube.cpp}::CommonVars::makeVolSpreadsTest(), QuantLib::FixedRateLeg::operator Leg(), QuantLib::operator<<(), QuantLib::OptionletStripper1::performCalculations(), QuantLib::SwaptionVolCube1::sabrCalibration(), QuantLib::SabrSmileSection::SabrSmileSection(), QuantLib::sabrVolatility(), QuantLib::anonymous_namespace{overnightindexedcoupon.cpp}::OvernightIndexedCouponPricer::swapletRate(), QuantLib::SwaptionPseudoDerivative::SwaptionPseudoDerivative(), MarketModelTest::testAbcdVolatilityFit(), DigitalCouponTest::testAssetOrNothing(), DigitalCouponTest::testAssetOrNothingDeepInTheMoney(), DigitalCouponTest::testAssetOrNothingDeepOutTheMoney(), CapFloorTest::testATMRate(), OvernightIndexedSwapTest::testBootstrap(), anonymous_namespace{defaultprobabilitycurves.cpp}::testBootstrapFromSpread(), anonymous_namespace{defaultprobabilitycurves.cpp}::testBootstrapFromUpfront(), BondTest::testCached(), MarketModelTest::testCallableSwapAnderson(), MarketModelTest::testCallableSwapLS(), MarketModelTest::testCallableSwapNaif(), DigitalCouponTest::testCallPutParity(), DigitalCouponTest::testCashOrNothing(), DigitalCouponTest::testCashOrNothingDeepInTheMoney(), DigitalCouponTest::testCashOrNothingDeepOutTheMoney(), CmsTest::testCmsSwap(), InflationCapFloorTest::testConsistency(), CapFloorTest::testConsistency(), InterestRateTest::testConversions(), anonymous_namespace{piecewiseyieldcurve.cpp}::testCurveConsistency(), SwapTest::testFairRate(), CmsTest::testFairRate(), OvernightIndexedSwapTest::testFairRate(), OvernightIndexedSwapTest::testFairSpread(), SwapTest::testFairSpread(), CreditDefaultSwapTest::testFairSpread(), CreditDefaultSwapTest::testFairUpfront(), OptionletStripperTest::testFlatTermVolatilityStripping1(), OptionletStripperTest::testFlatTermVolatilityStripping2(), TermStructureTest::testFSpreaded(), MarketModelSmmCapletHomoCalibrationTest::testFunction(), MarketModelSmmCapletCalibrationTest::testFunction(), MarketModelSmmCapletAlphaCalibrationTest::testFunction(), NthToDefaultTest::testGauss(), NthToDefaultTest::testGaussStudent(), CdoTest::testHW(), EuropeanOptionTest::testImpliedVol(), SwaptionTest::testImpliedVolatility(), CapFloorTest::testImpliedVolatility(), RangeAccrualTest::testInfiniteRange(), InflationCapFlooredCouponTest::testInstrumentEquality(), PiecewiseYieldCurveTest::testJpyLibor(), PiecewiseYieldCurveTest::testLiborFixing(), AssetSwapTest::testMarketASWSpread(), AssetSwapTest::testMASWWithGenericBond(), SwaptionVolatilityCubeTest::testObservability(), CmsTest::testParity(), InflationCapFloorTest::testParity(), CapFloorTest::testParity(), MarketModelTest::testPathwiseMarketVegas(), MarketModelTest::testPathwiseVegas(), MarketModelSmmCapletHomoCalibrationTest::testPeriodFunction(), SwapTest::testRateDependency(), DigitalCouponTest::testReplicationType(), SwaptionTest::testSpreadDependency(), SwapTest::testSpreadDependency(), SwaptionVolatilityCubeTest::testSpreadedCube(), SwaptionTest::testSpreadTreatment(), SwaptionTest::testStrikeDependency(), CapFloorTest::testStrikeDependency(), OptionletStripperTest::testTermVolatilityStripping1(), OptionletStripperTest::testTermVolatilityStripping2(), BondTest::testTheoretical(), CapFloorTest::testVega(), SwaptionTest::testVega(), BondTest::testYield(), InflationTest::testYYTermStructure(), InflationTest::testZeroTermStructure(), BondTest::testZspread(), TermStructureTest::testZSpreaded(), QuantLib::detail::SABRInterpolationImpl< I1, I2 >::update(), QuantLib::HazardRate::updateGuess(), QuantLib::ZeroYield::updateGuess(), and QuantLib::detail::SABRInterpolationImpl< I1, I2 >::value().
{
            return detail::percent_holder(r);
        }
template<class Container > detail::sequence_holder< typename Container::const_iterator > QuantLib::io::sequence (const Container & c) [inline]
output STL-compliant containers as space-separated sequences
Definition at line 139 of file dataformatters.hpp.
Referenced by QuantLib::ExponentialForwardCorrelation::ExponentialForwardCorrelation(), QuantLib::CTSMMCapletCalibration::performChecks(), MarketModelSmmCapletHomoCalibrationTest::testFunction(), MarketModelSmmCapletCalibrationTest::testFunction(), MarketModelSmmCapletAlphaCalibrationTest::testFunction(), and MarketModelSmmCapletHomoCalibrationTest::testPeriodFunction().
{
            return detail::sequence_holder<typename Container::const_iterator>(
                                                           c.begin(), c.end());
        }
detail::short_date_holder QuantLib::io::short_date (const Date &)
output dates in short format (mm/dd/yyyy)
Definition at line 490 of file date.cpp.
{
            return detail::short_date_holder(d);
        }
detail::short_period_holder QuantLib::io::short_period (const Period &)
output periods in short format (e.g. "2w")
Definition at line 476 of file period.cpp.
Referenced by QuantLib::InterestRateIndex::InterestRateIndex(), and QuantLib::operator<<().
{
            return detail::short_period_holder(p);
        }
detail::percent_holder QuantLib::io::volatility (Volatility v) [inline]
output volatilities as percentages
Definition at line 133 of file dataformatters.hpp.
Referenced by QuantLib::HestonModelHelper::blackPrice(), QuantLib::AnalyticWriterExtensibleOptionEngine::calculate(), QuantLib::ContinuousArithmeticAsianLevyEngine::calculate(), QuantLib::AnalyticSimpleChooserEngine::calculate(), QuantLib::LfmSwaptionEngine::calculate(), QuantLib::AnalyticAmericanMargrabeEngine::calculate(), QuantLib::AnalyticDiscreteGeometricAverageStrikeAsianEngine::calculate(), QuantLib::AnalyticContinuousGeometricAveragePriceAsianEngine::calculate(), QuantLib::QuantoEngine< Instr, Engine >::calculate(), QuantLib::detail::ImpliedVolatilityHelper::clone(), anonymous_namespace{capflooredcoupon.cpp}::CommonVars::CommonVars(), anonymous_namespace{convertiblebonds.cpp}::CommonVars::CommonVars(), anonymous_namespace{inflationcpiswap.cpp}::CommonVars::CommonVars(), anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::CommonVars(), anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::CommonVars(), QuantLib::coterminalSwapPseudoRoots(), QuantLib::LfmCovarianceProxy::covariance(), QuantLib::JointStochasticProcess::covariance(), anonymous_namespace{swingoption.cpp}::createKlugeProcess(), anonymous_namespace{vpp.cpp}::createKlugeProcess(), anonymous_namespace{swaptionvolatilitycube.cpp}::CommonVars::makeAtmVolTest(), anonymous_namespace{swaptionvolatilitymatrix.cpp}::CommonVars::makeCoherenceTest(), anonymous_namespace{swaptionvolatilitycube.cpp}::CommonVars::makeVolSpreadsTest(), CashFlowsTest::testAccessViolation(), MCLongstaffSchwartzEngineTest::testAmericanMaxOption(), MCLongstaffSchwartzEngineTest::testAmericanOption(), DigitalCouponTest::testAssetOrNothingDeepInTheMoney(), DigitalCouponTest::testAssetOrNothingDeepOutTheMoney(), CapFloorTest::testATMRate(), BarrierOptionTest::testBabsiriValues(), BarrierOptionTest::testBeagleholeValues(), HestonModelTest::testBlackCalibration(), ShortRateModelTest::testCachedHullWhite(), DigitalCouponTest::testCallPutParity(), DigitalCouponTest::testCashOrNothingDeepInTheMoney(), DigitalCouponTest::testCashOrNothingDeepOutTheMoney(), InflationCapFloorTest::testConsistency(), CapFloorTest::testConsistency(), EuropeanOptionTest::testImpliedVol(), SwaptionTest::testImpliedVolatility(), CapFloorTest::testImpliedVolatility(), InflationCapFlooredCouponTest::testInstrumentEquality(), AsianOptionTest::testLevyEngine(), AsianOptionTest::testMCDiscreteArithmeticAveragePrice(), AsianOptionTest::testMCDiscreteArithmeticAverageStrike(), SwaptionVolatilityCubeTest::testObservability(), InflationCapFloorTest::testParity(), CapFloorTest::testParity(), DigitalCouponTest::testReplicationType(), LiborMarketModelTest::testSimpleCovarianceModels(), VPPTest::testSimpleExtOUStorageEngine(), CapFloorTest::testStrikeDependency(), and QuantLib::anonymous_namespace{swaptionpseudojacobian.cpp}::QuickCap::vega().
{
            return detail::percent_holder(v);
        }
Variable Documentation
detail::null_checker<T> QuantLib::io::checknull(T)
check for nulls before output
detail::long_weekday_holder QuantLib::io::long_weekday(Weekday)
output weekdays in long format
Referenced by QuantLib::operator<<().
detail::power_of_two_holder<T> QuantLib::io::power_of_two(T)
output integers as powers of two
detail::short_weekday_holder QuantLib::io::short_weekday(Weekday)
output weekdays in short format (three letters)
detail::shortest_weekday_holder QuantLib::io::shortest_weekday(Weekday)
output weekdays in shortest format (two letters)