QuantLib: anonymous_namespace{optimizers.cpp} Namespace Reference
anonymous_namespace{optimizers.cpp} Namespace Reference
Classes
class OneDimensionalPolynomialDegreeN
class OptimizationBasedCostFunction
struct NamedOptimizationMethod
Enumerations
enum OptimizationMethodType {
simplex, levenbergMarquardt, conjugateGradient, steepestDescent,
bfgs
}
Functions
std::string optimizationMethodTypeToString (OptimizationMethodType type)
boost::shared_ptr
< OptimizationMethod > makeOptimizationMethod (OptimizationMethodType optimizationMethodType, Real simplexLambda, Real levenbergMarquardtEpsfcn, Real levenbergMarquardtXtol, Real levenbergMarquardtGtol)
std::vector
< NamedOptimizationMethod > makeOptimizationMethods (OptimizationMethodType optimizationMethodTypes[], Size optimizationMethodNb, Real simplexLambda, Real levenbergMarquardtEpsfcn, Real levenbergMarquardtXtol, Real levenbergMarquardtGtol)
Real maxDifference (const Array &a, const Array &b)
void setup ()
Variables
std::vector< boost::shared_ptr
< CostFunction > > costFunctions_
std::vector< boost::shared_ptr
< Constraint > > constraints_
std::vector< Array > initialValues_
std::vector< Size > maxIterations_
std::vector< Size > maxStationaryStateIterations_
std::vector< Real > rootEpsilons_
std::vector< Real > functionEpsilons_
std::vector< Real > gradientNormEpsilons_
std::vector< boost::shared_ptr
< EndCriteria > > endCriterias_
std::vector< std::vector
< NamedOptimizationMethod > > optimizationMethods_
std::vector< Array > xMinExpected_
std::vector< Array > yMinExpected_
Enumeration Type Documentation
enum anonymous_namespace{optimizers.cpp}::OptimizationMethodType
Enumerator:
simplex
levenbergMarquardt
conjugateGradient
steepestDescent
bfgs
Definition at line 102 of file optimizers.cpp.
                                {simplex,
                                 levenbergMarquardt,
                                 conjugateGradient,
                                 steepestDescent,
                                 bfgs};
Function Documentation
boost::shared_ptr<OptimizationMethod> anonymous_namespace{optimizers.cpp}::makeOptimizationMethod (OptimizationMethodType optimizationMethodType, Real simplexLambda, Real levenbergMarquardtEpsfcn, Real levenbergMarquardtXtol, Real levenbergMarquardtGtol)
Definition at line 131 of file optimizers.cpp.
References bfgs, conjugateGradient, levenbergMarquardt, QL_FAIL, simplex, and steepestDescent.
Referenced by makeOptimizationMethods().
{
        switch (optimizationMethodType) {
          case simplex:
            return boost::shared_ptr<OptimizationMethod>(
                new Simplex(simplexLambda));
          case levenbergMarquardt:
            return boost::shared_ptr<OptimizationMethod>(
                new LevenbergMarquardt(levenbergMarquardtEpsfcn,
                                       levenbergMarquardtXtol,
                                       levenbergMarquardtGtol));
          case conjugateGradient:
            return boost::shared_ptr<OptimizationMethod>(new ConjugateGradient);
          case steepestDescent:
            return boost::shared_ptr<OptimizationMethod>(new SteepestDescent);
          case bfgs:
            return boost::shared_ptr<OptimizationMethod>(new BFGS);
          default:
            QL_FAIL("unknown OptimizationMethod type");
        }
    }
std::vector<NamedOptimizationMethod> anonymous_namespace{optimizers.cpp}::makeOptimizationMethods (OptimizationMethodType optimizationMethodTypes[], Size optimizationMethodNb, Real simplexLambda, Real levenbergMarquardtEpsfcn, Real levenbergMarquardtXtol, Real levenbergMarquardtGtol)
Definition at line 158 of file optimizers.cpp.
References makeOptimizationMethod(), anonymous_namespace{optimizers.cpp}::NamedOptimizationMethod::name, anonymous_namespace{optimizers.cpp}::NamedOptimizationMethod::optimizationMethod, and optimizationMethodTypeToString().
Referenced by setup().
{
        std::vector<NamedOptimizationMethod> results;
        for (Size i=0; i<optimizationMethodNb; ++i) {
            NamedOptimizationMethod namedOptimizationMethod;
            namedOptimizationMethod.optimizationMethod = makeOptimizationMethod(
                optimizationMethodTypes[i],
                simplexLambda,
                levenbergMarquardtEpsfcn,
                levenbergMarquardtXtol,
                levenbergMarquardtGtol);
            namedOptimizationMethod.name
                = optimizationMethodTypeToString(optimizationMethodTypes[i]);
            results.push_back(namedOptimizationMethod);
        }
        return results;
    }
Real anonymous_namespace{optimizers.cpp}::maxDifference (const Array & a, const Array & b)
Definition at line 181 of file optimizers.cpp.
References anonymous_namespace{marketmodel.cpp}::b, anonymous_namespace{brownianbridge.cpp}::maxDiff(), and QuantLib::Array::size().
Referenced by OptimizersTest::test().
{
        Array diff = a-b;
        Real maxDiff = 0.0;
        for (Size i=0; i<diff.size(); ++i)
            maxDiff = std::max(maxDiff, std::fabs(diff[i]));
        return maxDiff;
    }
std::string anonymous_namespace{optimizers.cpp}::optimizationMethodTypeToString (OptimizationMethodType type)
Definition at line 108 of file optimizers.cpp.
References bfgs, conjugateGradient, levenbergMarquardt, QL_FAIL, simplex, and steepestDescent.
Referenced by makeOptimizationMethods().
{
        switch (type) {
          case simplex:
            return "Simplex";
          case levenbergMarquardt:
            return "Levenberg Marquardt";
          case conjugateGradient:
            return "Conjugate Gradient";
          case steepestDescent:
            return "Steepest Descent";
          case bfgs:
            return "BFGS";
          default:
            QL_FAIL("unknown OptimizationMethod type");
        }
    }
void anonymous_namespace{optimizers.cpp}::setup ()
Definition at line 191 of file optimizers.cpp.
References anonymous_namespace{marketmodel.cpp}::a, anonymous_namespace{marketmodel.cpp}::b, bfgs, anonymous_namespace{marketmodel.cpp}::c, conjugateGradient, LENGTH, levenbergMarquardt, makeOptimizationMethods(), and simplex.
                 {
        // Cost function n. 1: 1D polynomial of degree 2 (parabolic function y=a*x^2+b*x+c)
        const Real a = 1;   // required a > 0
        const Real b = 1;
        const Real c = 1;
        Array coefficients(3);
        coefficients[0]= c;
        coefficients[1]= b;
        coefficients[2]= a;
        costFunctions_.push_back(boost::shared_ptr<CostFunction>(
            new OneDimensionalPolynomialDegreeN(coefficients)));
        // Set constraint for optimizers: unconstrained problem
        constraints_.push_back(boost::shared_ptr<Constraint>(new NoConstraint()));
        // Set initial guess for optimizer
        Array initialValue(1);
        initialValue[0] = -100;
        initialValues_.push_back(initialValue);
        // Set end criteria for optimizer
        maxIterations_.push_back(10000);                // maxIterations
        maxStationaryStateIterations_.push_back(100);   // MaxStationaryStateIterations
        rootEpsilons_.push_back(1e-8);                  // rootEpsilon
        functionEpsilons_.push_back(1e-8);              // functionEpsilon
        gradientNormEpsilons_.push_back(1e-8);          // gradientNormEpsilon
        endCriterias_.push_back(boost::shared_ptr<EndCriteria>(
            new EndCriteria(maxIterations_.back(), maxStationaryStateIterations_.back(),
                            rootEpsilons_.back(), functionEpsilons_.back(),
                            gradientNormEpsilons_.back())));
        // Set optimization methods for optimizer
        OptimizationMethodType optimizationMethodTypes[] = {
            simplex, levenbergMarquardt, conjugateGradient, bfgs//, steepestDescent
        };
        Real simplexLambda = 0.1;                   // characteristic search length for simplex
        Real levenbergMarquardtEpsfcn = 1.0e-8;     // parameters specific for Levenberg-Marquardt
        Real levenbergMarquardtXtol   = 1.0e-8;     //
        Real levenbergMarquardtGtol   = 1.0e-8;     //
        optimizationMethods_.push_back(makeOptimizationMethods(
            optimizationMethodTypes, LENGTH(optimizationMethodTypes),
            simplexLambda, levenbergMarquardtEpsfcn, levenbergMarquardtXtol,
            levenbergMarquardtGtol));
        // Set expected results for optimizer
        Array xMinExpected(1),yMinExpected(1);
        xMinExpected[0] = -b/(2.0*a);
        yMinExpected[0] = -(b*b-4.0*a*c)/(4.0*a);
        xMinExpected_.push_back(xMinExpected);
        yMinExpected_.push_back(yMinExpected);
    }
Variable Documentation
std::vector<boost::shared_ptr<Constraint> > anonymous_namespace{optimizers.cpp}::constraints_
Definition at line 39 of file optimizers.cpp.
Referenced by OptimizersTest::test().
std::vector<boost::shared_ptr<CostFunction> > anonymous_namespace{optimizers.cpp}::costFunctions_
Definition at line 36 of file optimizers.cpp.
Referenced by OptimizersTest::test().
std::vector<boost::shared_ptr<EndCriteria> > anonymous_namespace{optimizers.cpp}::endCriterias_
Definition at line 43 of file optimizers.cpp.
Referenced by OptimizersTest::test().
std::vector<Real> anonymous_namespace{optimizers.cpp}::functionEpsilons_
Definition at line 42 of file optimizers.cpp.
std::vector<Real> anonymous_namespace{optimizers.cpp}::gradientNormEpsilons_
Definition at line 42 of file optimizers.cpp.
std::vector<Array> anonymous_namespace{optimizers.cpp}::initialValues_
Definition at line 40 of file optimizers.cpp.
Referenced by QuantLib::FdmNdimSolver< N >::performCalculations(), and OptimizersTest::test().
std::vector<Size> anonymous_namespace{optimizers.cpp}::maxIterations_
Definition at line 41 of file optimizers.cpp.
std::vector<Size> anonymous_namespace{optimizers.cpp}::maxStationaryStateIterations_
Definition at line 41 of file optimizers.cpp.
Referenced by QuantLib::LineSearchBasedMethod::minimize(), and QuantLib::Simplex::minimize().
std::vector<std::vector<NamedOptimizationMethod> > anonymous_namespace{optimizers.cpp}::optimizationMethods_
Definition at line 44 of file optimizers.cpp.
Referenced by OptimizersTest::test().
std::vector<Real> anonymous_namespace{optimizers.cpp}::rootEpsilons_
Definition at line 42 of file optimizers.cpp.
std::vector<Array> anonymous_namespace{optimizers.cpp}::xMinExpected_
Definition at line 45 of file optimizers.cpp.
Referenced by OptimizersTest::test().
std::vector<Array> anonymous_namespace{optimizers.cpp}::yMinExpected_
Definition at line 45 of file optimizers.cpp.
Referenced by OptimizersTest::test().