QuantLib: anonymous_namespace{inflation.cpp} Namespace Reference
anonymous_namespace{inflation.cpp} Namespace Reference
Classes
struct Datum
Functions
boost::shared_ptr
< YieldTermStructure > nominalTermStructure ()
template<class T , class U , class I >
std::vector< boost::shared_ptr
< BootstrapHelper< T > > > makeHelpers (Datum iiData[], Size N, const boost::shared_ptr< I > &ii, const Period &observationLag, const Calendar &calendar, const BusinessDayConvention &bdc, const DayCounter &dc)
Function Documentation
template<class T , class U , class I > std::vector<boost::shared_ptr<BootstrapHelper<T> > > anonymous_namespace{inflation.cpp}::makeHelpers (Datum iiData[], Size N, const boost::shared_ptr< I > & ii, const Period & observationLag, const Calendar & calendar, const BusinessDayConvention & bdc, const DayCounter & dc)
Definition at line 64 of file inflation.cpp.
References anonymous_namespace{inflation.cpp}::Datum::date, anonymous_namespace{matrices.cpp}::N, and QuantLib::io::rate().
Referenced by anonymous_namespace{inflationcapfloor.cpp}::CommonVars::CommonVars(), anonymous_namespace{inflationcpiswap.cpp}::CommonVars::CommonVars(), anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::CommonVars(), anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::CommonVars(), InflationTest::testYYTermStructure(), and InflationTest::testZeroTermStructure().
{
        std::vector<boost::shared_ptr<BootstrapHelper<T> > > instruments;
        for (Size i=0; i<N; i++) {
            Date maturity = iiData[i].date;
            Handle<Quote> quote(boost::shared_ptr<Quote>(
                new SimpleQuote(iiData[i].rate/100.0)));
            boost::shared_ptr<BootstrapHelper<T> > anInstrument(new U(
                quote, observationLag, maturity,
                calendar, bdc, dc, ii));
            instruments.push_back(anInstrument);
        }
        return instruments;
    }
boost::shared_ptr<YieldTermStructure> anonymous_namespace{inflation.cpp}::nominalTermStructure ()
Definition at line 57 of file inflation.cpp.
References QuantLib::August.
Referenced by QuantLib::InterpolatedCPICapFloorTermPriceSurface< Interpolator2D >::performCalculations(), InflationTest::testYYTermStructure(), and InflationTest::testZeroTermStructure().
{
        Date evaluationDate(13, August, 2007);
        return boost::shared_ptr<YieldTermStructure>(
            new FlatForward(evaluationDate, 0.05, Actual360()));
    }