QuantLib: QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp} Namespace Reference
QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp} Namespace Reference
Functions
template<int n>
Real pow (Real x)
template<>
Real pow< 1 > (Real x)
Function Documentation
template<int n> Real QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow (Real x) [inline]
Definition at line 40 of file analyticgjrgarchengine.cpp.
Referenced by QuantLib::AnalyticContinuousFloatingLookbackEngine::A(), QuantLib::AnalyticContinuousFixedLookbackEngine::A(), QuantLib::anonymous_namespace{bjerksundstenslandengine.cpp}::americanCallApproximation(), QuantLib::AmericanPayoffAtExpiry::AmericanPayoffAtExpiry(), QuantLib::AmericanPayoffAtHit::AmericanPayoffAtHit(), QuantLib::AnalyticContinuousFixedLookbackEngine::B(), QuantLib::AnalyticBarrierEngine::C(), QuantLib::InverseCumulativePoisson::calcSummand(), QuantLib::AnalyticWriterExtensibleOptionEngine::calculate(), QuantLib::KirkSpreadOptionEngine::calculate(), QuantLib::BaroneAdesiWhaleyApproximationEngine::calculate(), QuantLib::AnalyticBSMHullWhiteEngine::calculate(), QuantLib::AnalyticGJRGARCHEngine::calculate(), QuantLib::JuQuadraticApproximationEngine::calculate(), QuantLib::AnalyticHestonHullWhiteEngine::calculate(), QuantLib::Histogram::calculate(), QuantLib::OneFactorCopula::checkMoments(), QuantLib::FFTVanillaEngine::complexFourierTransform(), QuantLib::FFTVarianceGammaEngine::complexFourierTransform(), QuantLib::InterestRate::compoundFactor(), QuantLib::AnalyticBarrierEngine::D(), QuantLib::GFunctionFactory::GFunctionWithShifts::der2Rs_derX2(), QuantLib::GFunctionFactory::GFunctionWithShifts::der2Z_derX2(), QuantLib::RangeAccrualPricerByBgm::digitalPriceWithSmile(), QuantLib::AnalyticBarrierEngine::E(), QuantLib::ExtendedBlackScholesMertonProcess::evolve(), QuantLib::exponentialCorrelations(), QuantLib::AnalyticBarrierEngine::F(), anonymous_namespace{interpolations.cpp}::f(), QuantLib::ZeroCouponInflationSwap::fairRate(), QuantLib::FdmHestonVarianceMesher::FdmHestonVarianceMesher(), QuantLib::GFunctionFactory::GFunctionStandard::firstDerivative(), QuantLib::GFunctionFactory::GFunctionExactYield::firstDerivative(), QuantLib::ZeroInflationIndex::forecastFixing(), QuantLib::BernsteinPolynomial::get(), QuantLib::MarketModelPathwiseDiscounter::getFactors(), QuantLib::LatticeRule::getRule(), QuantLib::BFGS::getUpdatedDirection(), QuantLib::InterestRate::impliedRate(), QuantLib::anonymous_namespace{analyticvariancegammaengine.cpp}::Integrand::Integrand(), anonymous_namespace{integralhestonvarianceoptionengine.cpp}::IvopOneDim(), anonymous_namespace{integralhestonvarianceoptionengine.cpp}::IvopTwoDim(), QuantLib::GaussJacobiPolynomial::mu_0(), QuantLib::ClaytonCopulaRng< RNG >::next(), QuantLib::FarlieGumbelMorgensternCopulaRng< RNG >::next(), QuantLib::MarketModelDiscounter::numeraireBonds(), QuantLib::ClaytonCopula::operator()(), QuantLib::GumbelCopula::operator()(), QuantLib::MarshallOlkinCopula::operator()(), QuantLib::anonymous_namespace{richardsonextrapolation.cpp}::RichardsonEqn::operator()(), QuantLib::GalambosCopula::operator()(), QuantLib::HuslerReissCopula::operator()(), QuantLib::PlackettCopula::operator()(), QuantLib::anonymous_namespace{analyticvariancegammaengine.cpp}::Integrand::operator()(), QuantLib::StudentDistribution::operator()(), QuantLib::RichardsonExtrapolation::operator()(), QuantLib::GeometricAPOPathPricer::operator()(), QuantLib::Rounding::operator()(), QuantLib::GFunctionFactory::GFunctionStandard::operator()(), QuantLib::GFunctionFactory::GFunctionExactYield::operator()(), QuantLib::InterpolatedCPICapFloorTermPriceSurface< Interpolator2D >::performCalculations(), QuantLib::anonymous_namespace{bjerksundstenslandengine.cpp}::phi(), QuantLib::LossDist::probabilityOfNEvents(), QuantLib::rescaleError(), QuantLib::DiscrepancyStatistics::reset(), QuantLib::MultiplicativePriceSeasonality::seasonalityCorrection(), QuantLib::GFunctionFactory::GFunctionStandard::secondDerivative(), QuantLib::GFunctionFactory::GFunctionExactYield::secondDerivative(), QuantLib::GFunctionFactory::GFunctionWithShifts::secondDerivative(), QuantLib::anonymous_namespace{amortizingfixedratebond.cpp}::sinkingNotionals(), QuantLib::RangeAccrualPricerByBgm::smileCorrection(), QuantLib::SVD::SVD(), LowDiscrepancyTest::testFaure(), anonymous_namespace{lowdiscrepancysequences.cpp}::testGeneratorDiscrepancy(), LowDiscrepancyTest::testHalton(), DigitalOptionTest::testMCCashAtHit(), RiskStatisticsTest::testResults(), LowDiscrepancyTest::testSobol(), InflationTest::testZeroTermStructure(), QuantLib::Tian::underlying(), QuantLib::LeisenReimer::underlying(), QuantLib::Joshi4::underlying(), QuantLib::ExtendedTian::underlying(), QuantLib::ExtendedLeisenReimer::underlying(), QuantLib::ExtendedJoshi4::underlying(), QuantLib::unsafeSabrVolatility(), anonymous_namespace{optimizers.cpp}::OneDimensionalPolynomialDegreeN::value(), QuantLib::GaussLaguerrePolynomial::w(), QuantLib::GaussHermitePolynomial::w(), QuantLib::GaussJacobiPolynomial::w(), CPISwapTest::zciisconsistency(), and QuantLib::ZeroCouponInflationSwap::ZeroCouponInflationSwap().
{
            return x*pow<n-1>(x);
        }
template<> Real QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow< 1 > (Real x) [inline]
Definition at line 45 of file analyticgjrgarchengine.cpp.
{
            return x;
        }