QuantLib: QuantLib::anonymous_namespace{amortizingfixedratebond.cpp} Namespace Reference
QuantLib::anonymous_namespace{amortizingfixedratebond.cpp} Namespace Reference
Functions
Real initialNotional (const Leg &coupons)
std::pair< Integer, Integer > daysMinMax (const Period &p)
bool isSubPeriod (const Period &subPeriod, const Period &superPeriod, Integer &numSubPeriods)
Schedule sinkingSchedule (const Date &startDate, const Period &maturityTenor, const Frequency &sinkingFrequency, const Calendar &paymentCalendar)
std::vector< Real > sinkingNotionals (const Period &maturityTenor, const Frequency &sinkingFrequency, Rate couponRate, Real initialNotional)
Function Documentation
std::pair<Integer,Integer> QuantLib::anonymous_namespace{amortizingfixedratebond.cpp}::daysMinMax (const Period & p)
Definition at line 62 of file amortizingfixedratebond.cpp.
References QuantLib::Days, QuantLib::Period::length(), QuantLib::Months, QL_FAIL, QuantLib::Period::units(), QuantLib::Weeks, and QuantLib::Years.
Referenced by isSubPeriod(), and QuantLib::operator<().
{
            switch (p.units()) {
              case Days:
                return std::make_pair(p.length(), p.length());
              case Weeks:
                return std::make_pair(7*p.length(), 7*p.length());
              case Months:
                return std::make_pair(28*p.length(), 31*p.length());
              case Years:
                return std::make_pair(365*p.length(), 366*p.length());
              default:
                QL_FAIL("unknown time unit (" << Integer(p.units()) << ")");
            }
        }
Real QuantLib::anonymous_namespace{amortizingfixedratebond.cpp}::initialNotional (const Leg & coupons)
Definition at line 53 of file amortizingfixedratebond.cpp.
References QL_REQUIRE.
Referenced by sinkingNotionals().
{
            boost::shared_ptr<FixedRateCoupon> coupon =
                boost::dynamic_pointer_cast<FixedRateCoupon>(coupons.front());
            QL_REQUIRE(coupon,
                       "Coupon input is not a fixed rate coupon");
            return coupon->nominal();
        }
bool QuantLib::anonymous_namespace{amortizingfixedratebond.cpp}::isSubPeriod (const Period & subPeriod, const Period & superPeriod, Integer & numSubPeriods)
Definition at line 77 of file amortizingfixedratebond.cpp.
References daysMinMax().
Referenced by sinkingNotionals().
{
            std::pair<Integer, Integer> superDays(daysMinMax(superPeriod));
            std::pair<Integer, Integer> subDays(daysMinMax(subPeriod));
            //obtain the approximate time ratio
            Real minPeriodRatio =
                ((Real)superDays.first)/((Real)subDays.second);
            Real maxPeriodRatio =
                ((Real)superDays.second)/((Real)subDays.first);
            Integer lowRatio = static_cast<Integer>(std::floor(minPeriodRatio));
            Integer highRatio = static_cast<Integer>(std::ceil(maxPeriodRatio));
            try {
                for(Integer i=lowRatio; i <= highRatio; ++i) {
                    Period testPeriod = subPeriod * i;
                    if(testPeriod == superPeriod) {
                        numSubPeriods = i;
                        return true;
                    }
                }
            } catch(Error e) {
                return false;
            }
            return false;
        }
std::vector<Real> QuantLib::anonymous_namespace{amortizingfixedratebond.cpp}::sinkingNotionals (const Period & maturityTenor, const Frequency & sinkingFrequency, Rate couponRate, Real initialNotional)
Definition at line 119 of file amortizingfixedratebond.cpp.
References initialNotional(), isSubPeriod(), QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow(), and QL_REQUIRE.
Referenced by QuantLib::AmortizingFixedRateBond::AmortizingFixedRateBond().
{
            Period freqPeriod(sinkingFrequency);
            Integer nPeriods;
            QL_REQUIRE(isSubPeriod(freqPeriod, maturityTenor, nPeriods),
                       "Bond frequency is incompatible with the maturity tenor");
            std::vector<Real> notionals(nPeriods+1);
            notionals.front() = initialNotional;
            Real coupon = couponRate / static_cast<Real>(sinkingFrequency);
            Real compoundedInterest = 1.0;
            Real totalValue = std::pow(1.0+coupon, nPeriods);
            for(Size i = 0; i < (Size)nPeriods-1; ++i) {
                compoundedInterest *= (1.0 + coupon);
                Real currentNotional =
                    initialNotional*(compoundedInterest - (compoundedInterest-1.0)/(1.0 - 1.0/totalValue));
                notionals[i+1] = currentNotional;
            }
            notionals.back() = 0.0;
            return notionals;
        }
Schedule QuantLib::anonymous_namespace{amortizingfixedratebond.cpp}::sinkingSchedule (const Date & startDate, const Period & maturityTenor, const Frequency & sinkingFrequency, const Calendar & paymentCalendar)
Definition at line 107 of file amortizingfixedratebond.cpp.
References QuantLib::DateGeneration::Backward, and QuantLib::Unadjusted.
Referenced by QuantLib::AmortizingFixedRateBond::AmortizingFixedRateBond().
{
            Period freqPeriod(sinkingFrequency);
            Date maturityDate(startDate + maturityTenor);
            Schedule retVal(startDate, maturityDate, freqPeriod,
                            paymentCalendar, Unadjusted, Unadjusted,
                            DateGeneration::Backward, false);
            return retVal;
        }