QuantLib: anonymous_namespace{europeanoption.cpp} Namespace Reference
anonymous_namespace{europeanoption.cpp} Namespace Reference
Classes
struct EuropeanOptionData
Enumerations
enum EngineType {
Analytic, JR, CRR, EQP,
TGEO, TIAN, LR, JOSHI,
FiniteDifferences, Integral, PseudoMonteCarlo, QuasiMonteCarlo,
FFT
}
Functions
boost::shared_ptr
< GeneralizedBlackScholesProcess > makeProcess (const boost::shared_ptr< Quote > &u, const boost::shared_ptr< YieldTermStructure > &q, const boost::shared_ptr< YieldTermStructure > &r, const boost::shared_ptr< BlackVolTermStructure > &vol)
boost::shared_ptr< VanillaOption > makeOption (const boost::shared_ptr< StrikedTypePayoff > &payoff, const boost::shared_ptr< Exercise > &exercise, const boost::shared_ptr< Quote > &u, const boost::shared_ptr< YieldTermStructure > &q, const boost::shared_ptr< YieldTermStructure > &r, const boost::shared_ptr< BlackVolTermStructure > &vol, EngineType engineType, Size binomialSteps, Size samples)
std::string engineTypeToString (EngineType type)
Integer timeToDays (Time t)
void testEngineConsistency (EngineType engine, Size binomialSteps, Size samples, std::map< std::string, Real > tolerance, bool testGreeks=false)
Enumeration Type Documentation
enum anonymous_namespace{europeanoption.cpp}::EngineType
Enumerator:
Analytic
JR
CRR
EQP
TGEO
TIAN
LR
JOSHI
FiniteDifferences
Integral
PseudoMonteCarlo
QuasiMonteCarlo
FFT
Definition at line 81 of file europeanoption.cpp.
                    { Analytic,
                      JR, CRR, EQP, TGEO, TIAN, LR, JOSHI,
                      FiniteDifferences,
                      Integral,
                      PseudoMonteCarlo, QuasiMonteCarlo,
                      FFT };
Function Documentation
std::string anonymous_namespace{europeanoption.cpp}::engineTypeToString (EngineType type)
Definition at line 188 of file europeanoption.cpp.
References Analytic, CRR, EQP, FFT, FiniteDifferences, Integral, JOSHI, JR, LR, PseudoMonteCarlo, QL_FAIL, QuasiMonteCarlo, TGEO, and TIAN.
{
        switch (type) {
          case Analytic:
            return "analytic";
          case JR:
            return "Jarrow-Rudd";
          case CRR:
            return "Cox-Ross-Rubinstein";
          case EQP:
            return "EQP";
          case TGEO:
            return "Trigeorgis";
          case TIAN:
            return "Tian";
          case LR:
            return "LeisenReimer";
          case JOSHI:
            return "Joshi";
          case FiniteDifferences:
            return "FiniteDifferences";
          case Integral:
            return "Integral";
          case PseudoMonteCarlo:
            return "MonteCarlo";
          case QuasiMonteCarlo:
            return "Quasi-MonteCarlo";
          case FFT:
            return "FFT";
          default:
            QL_FAIL("unknown engine type");
        }
    }
boost::shared_ptr<VanillaOption> anonymous_namespace{europeanoption.cpp}::makeOption (const boost::shared_ptr< StrikedTypePayoff > & payoff, const boost::shared_ptr< Exercise > & exercise, const boost::shared_ptr< Quote > & u, const boost::shared_ptr< YieldTermStructure > & q, const boost::shared_ptr< YieldTermStructure > & r, const boost::shared_ptr< BlackVolTermStructure > & vol, EngineType engineType, Size binomialSteps, Size samples)
Definition at line 101 of file europeanoption.cpp.
References Analytic, CRR, EQP, FFT, FiniteDifferences, Integral, JOSHI, JR, LR, makeProcess(), PseudoMonteCarlo, QL_FAIL, QuasiMonteCarlo, TGEO, TIAN, QuantLib::MakeMCEuropeanEngine< RNG, S >::withSamples(), and QuantLib::MakeMCEuropeanEngine< RNG, S >::withSeed().
Referenced by anonymous_namespace{extendedtrees.cpp}::testEngineConsistency(), testEngineConsistency(), and EuropeanOptionTest::testImpliedVol().
{
        boost::shared_ptr<GeneralizedBlackScholesProcess> stochProcess =
            makeProcess(u,q,r,vol);
        boost::shared_ptr<PricingEngine> engine;
        switch (engineType) {
          case Analytic:
            engine = boost::shared_ptr<PricingEngine>(
                                    new AnalyticEuropeanEngine(stochProcess));
            break;
          case JR:
            engine = boost::shared_ptr<PricingEngine>(
                        new BinomialVanillaEngine<JarrowRudd>(stochProcess,
                                                              binomialSteps));
            break;
          case CRR:
            engine = boost::shared_ptr<PricingEngine>(
                 new BinomialVanillaEngine<CoxRossRubinstein>(stochProcess,
                                                              binomialSteps));
          case EQP:
            engine = boost::shared_ptr<PricingEngine>(
                 new BinomialVanillaEngine<AdditiveEQPBinomialTree>(
                                                              stochProcess,
                                                              binomialSteps));
            break;
          case TGEO:
            engine = boost::shared_ptr<PricingEngine>(
                        new BinomialVanillaEngine<Trigeorgis>(stochProcess,
                                                              binomialSteps));
            break;
          case TIAN:
            engine = boost::shared_ptr<PricingEngine>(
                new BinomialVanillaEngine<Tian>(stochProcess, binomialSteps));
            break;
          case LR:
            engine = boost::shared_ptr<PricingEngine>(
                      new BinomialVanillaEngine<LeisenReimer>(stochProcess,
                                                              binomialSteps));
            break;
          case JOSHI:
            engine = boost::shared_ptr<PricingEngine>(
              new BinomialVanillaEngine<Joshi4>(stochProcess, binomialSteps));
            break;
          case FiniteDifferences:
            engine = boost::shared_ptr<PricingEngine>(
                            new FDEuropeanEngine<CrankNicolson>(stochProcess,
                                                                binomialSteps,
                                                                samples));
            break;
          case Integral:
            engine = boost::shared_ptr<PricingEngine>(
                                            new IntegralEngine(stochProcess));
            break;
          case PseudoMonteCarlo:
            engine = MakeMCEuropeanEngine<PseudoRandom>(stochProcess)
                .withSteps(1)
                .withSamples(samples)
                .withSeed(42);
            break;
          case QuasiMonteCarlo:
            engine = MakeMCEuropeanEngine<LowDiscrepancy>(stochProcess)
                .withSteps(1)
                .withSamples(samples);
            break;
          case FFT:
              engine = boost::shared_ptr<PricingEngine>(
                                          new FFTVanillaEngine(stochProcess));
            break;
          default:
            QL_FAIL("unknown engine type");
        }
        boost::shared_ptr<VanillaOption> option(
            new EuropeanOption(payoff, exercise));
        option->setPricingEngine(engine);
        return option;
    }
boost::shared_ptr<GeneralizedBlackScholesProcess> anonymous_namespace{europeanoption.cpp}::makeProcess (const boost::shared_ptr< Quote > & u, const boost::shared_ptr< YieldTermStructure > & q, const boost::shared_ptr< YieldTermStructure > & r, const boost::shared_ptr< BlackVolTermStructure > & vol)
Definition at line 89 of file europeanoption.cpp.
Referenced by anonymous_namespace{extendedtrees.cpp}::makeOption(), makeOption(), EuropeanOptionTest::testImpliedVol(), LiborMarketModelProcessTest::testLambdaBootstrapping(), EuropeanOptionTest::testLocalVolatility(), and LiborMarketModelProcessTest::testMonteCarloCapletPricing().
{
        return boost::shared_ptr<BlackScholesMertonProcess>(
           new BlackScholesMertonProcess(Handle<Quote>(u),
                                         Handle<YieldTermStructure>(q),
                                         Handle<YieldTermStructure>(r),
                                         Handle<BlackVolTermStructure>(vol)));
    }
void anonymous_namespace{europeanoption.cpp}::testEngineConsistency (EngineType engine, Size binomialSteps, Size samples, std::map< std::string, Real > tolerance, bool testGreeks = false)
Definition at line 1009 of file europeanoption.cpp.
References Analytic, QuantLib::Option::Call, QuantLib::flatRate(), QuantLib::flatVol(), LENGTH, anonymous_namespace{swaption.cpp}::lengths, makeOption(), QuantLib::Option::Put, QL_TEST_START_TIMING, QuantLib::relativeError(), REPORT_FAILURE, anonymous_namespace{marketmodel.cpp}::todaysDate, and anonymous_namespace{perturbativebarrieroptionengine.cpp}::v().
Referenced by ExtendedTreesTest::testCRRBinomialEngines(), EuropeanOptionTest::testCRRBinomialEngines(), ExtendedTreesTest::testEQPBinomialEngines(), EuropeanOptionTest::testEQPBinomialEngines(), EuropeanOptionTest::testFdEngines(), EuropeanOptionTest::testFFTEngines(), EuropeanOptionTest::testIntegralEngines(), ExtendedTreesTest::testJOSHIBinomialEngines(), EuropeanOptionTest::testJOSHIBinomialEngines(), ExtendedTreesTest::testJRBinomialEngines(), EuropeanOptionTest::testJRBinomialEngines(), ExtendedTreesTest::testLRBinomialEngines(), EuropeanOptionTest::testLRBinomialEngines(), EuropeanOptionTest::testMcEngines(), EuropeanOptionTest::testQmcEngines(), ExtendedTreesTest::testTGEOBinomialEngines(), EuropeanOptionTest::testTGEOBinomialEngines(), ExtendedTreesTest::testTIANBinomialEngines(), and EuropeanOptionTest::testTIANBinomialEngines().
{
        QL_TEST_START_TIMING
            std::map<std::string,Real> calculated, expected;
        // test options
        Option::Type types[] = { Option::Call, Option::Put };
        Real strikes[] = { 75.0, 100.0, 125.0 };
        Integer lengths[] = { 1 };
        // test data
        Real underlyings[] = { 100.0 };
        Rate qRates[] = { 0.00, 0.05 };
        Rate rRates[] = { 0.01, 0.05, 0.15 };
        Volatility vols[] = { 0.11, 0.50, 1.20 };
        DayCounter dc = Actual360();
        Date today = Date::todaysDate();
        boost::shared_ptr<SimpleQuote> spot(new SimpleQuote(0.0));
        boost::shared_ptr<SimpleQuote> vol(new SimpleQuote(0.0));
        boost::shared_ptr<BlackVolTermStructure> volTS = flatVol(today,vol,dc);
        boost::shared_ptr<SimpleQuote> qRate(new SimpleQuote(0.0));
        boost::shared_ptr<YieldTermStructure> qTS = flatRate(today,qRate,dc);
        boost::shared_ptr<SimpleQuote> rRate(new SimpleQuote(0.0));
        boost::shared_ptr<YieldTermStructure> rTS = flatRate(today,rRate,dc);
        for (Size i=0; i<LENGTH(types); i++) {
          for (Size j=0; j<LENGTH(strikes); j++) {
            for (Size k=0; k<LENGTH(lengths); k++) {
              Date exDate = today + lengths[k]*360;
              boost::shared_ptr<Exercise> exercise(
                                                new EuropeanExercise(exDate));
              boost::shared_ptr<StrikedTypePayoff> payoff(new
                                    PlainVanillaPayoff(types[i], strikes[j]));
              // reference option
              boost::shared_ptr<VanillaOption> refOption =
                  makeOption(payoff, exercise, spot, qTS, rTS, volTS,
                             Analytic, Null<Size>(), Null<Size>());
              // option to check
              boost::shared_ptr<VanillaOption> option =
                  makeOption(payoff, exercise, spot, qTS, rTS, volTS,
                             engine, binomialSteps, samples);
              for (Size l=0; l<LENGTH(underlyings); l++) {
                for (Size m=0; m<LENGTH(qRates); m++) {
                  for (Size n=0; n<LENGTH(rRates); n++) {
                    for (Size p=0; p<LENGTH(vols); p++) {
                      Real u = underlyings[l];
                      Rate q = qRates[m],
                           r = rRates[n];
                      Volatility v = vols[p];
                      spot->setValue(u);
                      qRate->setValue(q);
                      rRate->setValue(r);
                      vol->setValue(v);
                      expected.clear();
                      calculated.clear();
                      // FLOATING_POINT_EXCEPTION
                      expected["value"] = refOption->NPV();
                      calculated["value"] = option->NPV();
                      if (testGreeks && option->NPV() > spot->value()*1.0e-5) {
                           expected["delta"] = refOption->delta();
                           expected["gamma"] = refOption->gamma();
                           expected["theta"] = refOption->theta();
                           calculated["delta"] = option->delta();
                           calculated["gamma"] = option->gamma();
                           calculated["theta"] = option->theta();
                      }
                      std::map<std::string,Real>::iterator it;
                      for (it = calculated.begin();
                           it != calculated.end(); ++it) {
                          std::string greek = it->first;
                          Real expct = expected  [greek],
                               calcl = calculated[greek],
                               tol   = tolerance [greek];
                          Real error = relativeError(expct,calcl,u);
                          if (error > tol) {
                              REPORT_FAILURE(greek, payoff, exercise,
                                             u, q, r, today, v,
                                             expct, calcl, error, tol);
                          }
                      }
                    }
                  }
                }
              }
            }
          }
        }
    }
Integer anonymous_namespace{europeanoption.cpp}::timeToDays (Time t)
Definition at line 221 of file europeanoption.cpp.
{
        // FLOATING_POINT_EXCEPTION
        return Integer(t*360+0.5);
    }