QuantLib: QuantLib::anonymous_namespace{unitofmeasureconversionmanager.cpp} Namespace Reference
QuantLib::anonymous_namespace{unitofmeasureconversionmanager.cpp} Namespace Reference
Functions
bool matches (const UnitOfMeasureConversion &c1, const UnitOfMeasureConversion &c2)
bool matches (const UnitOfMeasureConversion &c, const CommodityType &commodityType, const UnitOfMeasure &source, const UnitOfMeasure &target)
bool matches (const UnitOfMeasureConversion &c, const CommodityType &commodityType, const UnitOfMeasure &source)
Function Documentation
bool QuantLib::anonymous_namespace{unitofmeasureconversionmanager.cpp}::matches (const UnitOfMeasureConversion & c1, const UnitOfMeasureConversion & c2)
Definition at line 31 of file unitofmeasureconversionmanager.cpp.
References QuantLib::UnitOfMeasureConversion::commodityType(), QuantLib::UnitOfMeasureConversion::source(), and QuantLib::UnitOfMeasureConversion::target().
Referenced by QuantLib::UnitOfMeasureConversionManager::add(), QuantLib::UnitOfMeasureConversionManager::directLookup(), and QuantLib::UnitOfMeasureConversionManager::smartLookup().
{
            return c1.commodityType() == c2.commodityType() &&
                ((c1.source() == c2.source() && c1.target() == c2.target())
                 || (c1.source() == c2.target() && c1.target() == c2.source()));
        }
bool QuantLib::anonymous_namespace{unitofmeasureconversionmanager.cpp}::matches (const UnitOfMeasureConversion & c, const CommodityType & commodityType, const UnitOfMeasure & source, const UnitOfMeasure & target)
Definition at line 38 of file unitofmeasureconversionmanager.cpp.
References QuantLib::UnitOfMeasureConversion::commodityType(), QuantLib::UnitOfMeasureConversion::source(), and QuantLib::UnitOfMeasureConversion::target().
{
            return c.commodityType() == commodityType &&
                ((c.source() == source && c.target() == target)
                 || (c.source() == target && c.target() == source));
        }
bool QuantLib::anonymous_namespace{unitofmeasureconversionmanager.cpp}::matches (const UnitOfMeasureConversion & c, const CommodityType & commodityType, const UnitOfMeasure & source)
Definition at line 47 of file unitofmeasureconversionmanager.cpp.
References QuantLib::UnitOfMeasureConversion::commodityType(), QuantLib::UnitOfMeasureConversion::source(), and QuantLib::UnitOfMeasureConversion::target().
{
            return c.commodityType() == commodityType &&
                (c.source() == source || c.target() == source);
        }