QuantLib: QuantLib::anonymous_namespace{discretizedcallablefixedratebond.cpp} Namespace Reference
QuantLib::anonymous_namespace{discretizedcallablefixedratebond.cpp} Namespace Reference
Functions
bool withinPreviousWeek (Time t1, Time t2)
bool withinNextWeek (Time t1, Time t2)
Function Documentation
bool QuantLib::anonymous_namespace{discretizedcallablefixedratebond.cpp}::withinNextWeek (Time t1, Time t2)
Definition at line 31 of file discretizedcallablefixedratebond.cpp.
References QuantLib::anonymous_namespace{yieldtermstructure.cpp}::dt.
Referenced by QuantLib::DiscretizedCallableFixedRateBond::DiscretizedCallableFixedRateBond(), and QuantLib::DiscretizedSwaption::DiscretizedSwaption().
{
            static const Time dt = 1.0/52;
            return t1 <= t2 && t2 <= t1+dt;
        }
bool QuantLib::anonymous_namespace{discretizedcallablefixedratebond.cpp}::withinPreviousWeek (Time t1, Time t2)
Definition at line 26 of file discretizedcallablefixedratebond.cpp.
References QuantLib::anonymous_namespace{yieldtermstructure.cpp}::dt.
Referenced by QuantLib::DiscretizedSwaption::DiscretizedSwaption().
{
            static const Time dt = 1.0/52;
            return t1-dt <= t2 && t2 <= t1;
        }