QuantLib: QuantLib::anonymous_namespace{stulzengine.cpp} Namespace Reference
QuantLib::anonymous_namespace{stulzengine.cpp} Namespace Reference
Functions
Real euroTwoAssetMinBasketCall (Real forward1, Real forward2, Real strike, DiscountFactor riskFreeDiscount, Real variance1, Real variance2, Real rho)
Real euroTwoAssetMaxBasketCall (Real forward1, Real forward2, Real strike, DiscountFactor riskFreeDiscount, Real variance1, Real variance2, Real rho)
Function Documentation
Real QuantLib::anonymous_namespace{stulzengine.cpp}::euroTwoAssetMaxBasketCall (Real forward1, Real forward2, Real strike, DiscountFactor riskFreeDiscount, Real variance1, Real variance2, Real rho)
Definition at line 80 of file stulzengine.cpp.
References QuantLib::blackFormula(), QuantLib::Option::Call, and euroTwoAssetMinBasketCall().
Referenced by QuantLib::StulzEngine::calculate().
{
            boost::shared_ptr<StrikedTypePayoff> payoff(new
                PlainVanillaPayoff(Option::Call, strike));
            Real black1 = blackFormula(payoff->optionType(), payoff->strike(),
                forward1, std::sqrt(variance1)) * riskFreeDiscount;
            Real black2 = blackFormula(payoff->optionType(), payoff->strike(),
                forward2, std::sqrt(variance2)) * riskFreeDiscount;
            return black1 + black2 -
                euroTwoAssetMinBasketCall(forward1, forward2, strike,
                                          riskFreeDiscount,
                                          variance1, variance2, rho);
        }
Real QuantLib::anonymous_namespace{stulzengine.cpp}::euroTwoAssetMinBasketCall (Real forward1, Real forward2, Real strike, DiscountFactor riskFreeDiscount, Real variance1, Real variance2, Real rho)
Definition at line 34 of file stulzengine.cpp.
References anonymous_namespace{marketmodel.cpp}::beta.
Referenced by QuantLib::StulzEngine::calculate(), and euroTwoAssetMaxBasketCall().
{
            Real stdDev1 = std::sqrt(variance1);
            Real stdDev2 = std::sqrt(variance2);
            Real variance = variance1 + variance2 - 2*rho*stdDev1*stdDev2;
            Real stdDev = std::sqrt(variance);
            Real modRho1 = (rho * stdDev2 - stdDev1) / stdDev;
            Real modRho2 = (rho * stdDev1 - stdDev2) / stdDev;
            Real D1 = (std::log(forward1/forward2) + 0.5*variance) / stdDev;
            Real alfa, beta, gamma;
            if (strike != 0.0) {
                BivariateCumulativeNormalDistribution bivCNorm =
                    BivariateCumulativeNormalDistribution(rho);
                BivariateCumulativeNormalDistribution bivCNormMod2 =
                    BivariateCumulativeNormalDistribution(modRho2);
                BivariateCumulativeNormalDistribution bivCNormMod1 =
                    BivariateCumulativeNormalDistribution(modRho1);
                Real D1_1 =
                    (std::log(forward1/strike) + 0.5*variance1) / stdDev1;
                Real D1_2 =
                    (std::log(forward2/strike) + 0.5*variance2) / stdDev2;
                alfa = bivCNormMod1(D1_1, -D1);
                beta = bivCNormMod2(D1_2, D1 - stdDev);
                gamma = bivCNorm(D1_1 - stdDev1, D1_2 - stdDev2);
            } else {
                CumulativeNormalDistribution cum;
                alfa = cum(-D1);
                beta = cum(D1 - stdDev);
                gamma = 1.0;
            }
            return riskFreeDiscount *
                (forward1*alfa + forward2*beta - strike*gamma);
        }