QuantLib: QuantLib::anonymous_namespace{bjerksundstenslandengine.cpp} Namespace Reference
QuantLib::anonymous_namespace{bjerksundstenslandengine.cpp} Namespace Reference
Functions
Real phi (Real S, Real gamma, Real H, Real I, Real rT, Real bT, Real variance)
Real americanCallApproximation (Real S, Real X, Real rfD, Real dD, Real variance)
Variables
CumulativeNormalDistribution cumNormalDist
Function Documentation
Real QuantLib::anonymous_namespace{bjerksundstenslandengine.cpp}::americanCallApproximation (Real S, Real X, Real rfD, Real dD, Real variance)
Definition at line 46 of file bjerksundstenslandengine.cpp.
References anonymous_namespace{marketmodel.cpp}::beta, anonymous_namespace{matrices.cpp}::I, phi(), QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow(), and QL_REQUIRE.
Referenced by QuantLib::BjerksundStenslandApproximationEngine::calculate().
{
            Real bT = std::log(dD/rfD);
            Real rT = std::log(1.0/rfD);
            Real beta = (0.5 - bT/variance) +
                std::sqrt(std::pow((bT/variance - 0.5), Real(2.0))
                          + 2.0 * rT/variance);
            Real BInfinity = beta / (beta - 1.0) * X;
            // Real B0 = std::max(X, std::log(rfD) / std::log(dD) * X);
            Real B0 = std::max(X, rT / (rT - bT) * X);
            Real ht = -(bT + 2.0*std::sqrt(variance)) * B0 / (BInfinity - B0);
            // investigate what happen to I for dD->0.0
            Real I = B0 + (BInfinity - B0) * (1 - std::exp(ht));
            QL_REQUIRE(I >= X,
                       "Bjerksund-Stensland approximation not applicable "
                       "to this set of parameters");
            if (S >= I) {
                return S - X;
            } else {
                // investigate what happen to alpha for dD->0.0
                Real alpha = (I - X) * std::pow(I, (-beta));
                return alpha * std::pow(S, beta)
                    - alpha * phi(S, beta, I, I, rT, bT, variance)
                    +         phi(S,  1.0, I, I, rT, bT, variance)
                    -         phi(S,  1.0, X, I, rT, bT, variance)
                    -    X *  phi(S,  0.0, I, I, rT, bT, variance)
                    +    X *  phi(S,  0.0, X, I, rT, bT, variance);
            }
        }
Real QuantLib::anonymous_namespace{bjerksundstenslandengine.cpp}::phi (Real S, Real gamma, Real H, Real I, Real rT, Real bT, Real variance)
Definition at line 32 of file bjerksundstenslandengine.cpp.
References cumNormalDist, anonymous_namespace{marketmodel.cpp}::d, and QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow().
Referenced by QuantLib::LogNormalFwdRateEulerConstrained::advanceStep(), americanCallApproximation(), QuantLib::bachelierBlackFormula(), QuantLib::blackFormula(), QuantLib::blackFormulaCashItmProbability(), QuantLib::AnalyticCompoundOptionEngine::calculate(), QuantLib::JuQuadraticApproximationEngine::calculate(), QuantLib::FFTVarianceGammaEngine::complexFourierTransform(), QuantLib::FFTVanillaEngine::complexFourierTransform(), QuantLib::HullWhite::convexityBias(), QuantLib::RangeAccrualPricerByBgm::digitalPriceWithoutSmile(), QuantLib::GaussianLHPCDOEngine< CDOEngine >::expectedTrancheLoss(), QuantLib::AnalyticPTDHestonEngine::Fj_Helper::operator()(), QuantLib::AnalyticHestonEngine::Fj_Helper::operator()(), QuantLib::G2::SwaptionPricingFunction::operator()(), QuantLib::FdmG2Op::setTime(), QuantLib::FdmHullWhiteOp::setTime(), QuantLib::FdmHestonHullWhiteEquityPart::setTime(), QuantLib::RangeAccrualPricerByBgm::smileCorrection(), DigitalCouponTest::testAssetOrNothing(), QuantLib::BlackKarasinski::tree(), QuantLib::ExtendedCoxIngersollRoss::tree(), QuantLib::HullWhite::tree(), QuantLib::GeneralizedHullWhite::tree(), QuantLib::triangularAnglesParametrizationRankThree(), and QuantLib::ExtendedCoxIngersollRoss::FittingParameter::Impl::value().
{
            Real lambda = (-rT + gamma * bT + 0.5 * gamma * (gamma - 1.0)
                * variance);
            Real d = -(std::log(S / H) + (bT + (gamma - 0.5) * variance) )
                / std::sqrt(variance);
            Real kappa = 2.0 * bT / variance + (2.0 * gamma - 1.0);
            return std::exp(lambda) * std::pow(S, gamma) * (cumNormalDist(d)
                - std::pow((I / S), kappa) *
                cumNormalDist(d - 2.0 * std::log(I/S) / std::sqrt(variance)));
        }
Variable Documentation
CumulativeNormalDistribution QuantLib::anonymous_namespace{bjerksundstenslandengine.cpp}::cumNormalDist
Definition at line 30 of file bjerksundstenslandengine.cpp.
Referenced by QuantLib::BaroneAdesiWhaleyApproximationEngine::calculate(), QuantLib::JuQuadraticApproximationEngine::calculate(), QuantLib::BaroneAdesiWhaleyApproximationEngine::criticalPrice(), QuantLib::BivariateCumulativeNormalDistributionDr78::operator()(), and phi().