QuantLib: anonymous_namespace{interpolations.cpp} Namespace Reference
anonymous_namespace{interpolations.cpp} Namespace Reference
Classes
class errorFunction
struct NotThrown
Functions
std::vector< Real > xRange (Real start, Real finish, Size points)
std::vector< Real > gaussian (const std::vector< Real > &x)
std::vector< Real > parabolic (const std::vector< Real > &x)
template<class I , class J >
void checkValues (const char *type, const CubicInterpolation &cubic, I xBegin, I xEnd, J yBegin)
void check1stDerivativeValue (const char *type, const CubicInterpolation &cubic, Real x, Real value)
void check2ndDerivativeValue (const char *type, const CubicInterpolation &cubic, Real x, Real value)
void checkNotAKnotCondition (const char *type, const CubicInterpolation &cubic)
void checkSymmetry (const char *type, const CubicInterpolation &cubic, Real xMin)
template<class F >
errorFunction< F > make_error_function (const F &f)
Real multif (Real s, Real t, Real u, Real v, Real w)
Real epanechnikovKernel (Real u)
Real f (Real h)
Function Documentation
void anonymous_namespace{interpolations.cpp}::check1stDerivativeValue (const char * type, const CubicInterpolation & cubic, Real x, Real value)
Definition at line 95 of file interpolations.cpp.
References QuantLib::Interpolation::derivative(), QL_SCIENTIFIC, and anonymous_namespace{gaussianquadratures.cpp}::tolerance.
Referenced by InterpolationTest::testDerivativeEndConditions(), InterpolationTest::testSplineOnGenericValues(), and InterpolationTest::testSplineOnRPN15AValues().
{
        Real tolerance = 1.0e-14;
        Real interpolated = cubic.derivative(x);
        Real error = std::fabs(interpolated-value);
        if (error > tolerance) {
            BOOST_ERROR(type << " interpolation first derivative failure\n"
                        << "at x = " << x
                        << "\n    interpolated value: " << interpolated
                        << "\n    expected value:     " << value
                        << QL_SCIENTIFIC
                        << "\n    error:              " << error);
        }
    }
void anonymous_namespace{interpolations.cpp}::check2ndDerivativeValue (const char * type, const CubicInterpolation & cubic, Real x, Real value)
Definition at line 112 of file interpolations.cpp.
References QL_SCIENTIFIC, QuantLib::Interpolation::secondDerivative(), and anonymous_namespace{gaussianquadratures.cpp}::tolerance.
Referenced by InterpolationTest::testDerivativeEndConditions(), and InterpolationTest::testSplineOnRPN15AValues().
{
        Real tolerance = 1.0e-13;
        Real interpolated = cubic.secondDerivative(x);
        Real error = std::fabs(interpolated-value);
        if (error > tolerance) {
            BOOST_ERROR(type << " interpolation second derivative failure\n"
                        << "at x = " << x
                        << "\n    interpolated value: " << interpolated
                        << "\n    expected value:     " << value
                        << QL_SCIENTIFIC
                        << "\n    error:              " << error);
        }
    }
void anonymous_namespace{interpolations.cpp}::checkNotAKnotCondition (const char * type, const CubicInterpolation & cubic)
Definition at line 129 of file interpolations.cpp.
References anonymous_namespace{marketmodel.cpp}::c, QuantLib::CubicInterpolation::cCoefficients(), and anonymous_namespace{gaussianquadratures.cpp}::tolerance.
Referenced by InterpolationTest::testSimmetricEndConditions(), InterpolationTest::testSplineOnGaussianValues(), InterpolationTest::testSplineOnGenericValues(), and InterpolationTest::testSplineOnRPN15AValues().
{
        Real tolerance = 1.0e-14;
        const std::vector<Real>& c = cubic.cCoefficients();
        if (std::fabs(c[0]-c[1]) > tolerance) {
            BOOST_ERROR(type << " interpolation failure"
                        << "\n    cubic coefficient of the first"
                        << " polinomial is " << c[0]
                        << "\n    cubic coefficient of the second"
                        << " polinomial is " << c[1]);
        }
        Size n = c.size();
        if (std::fabs(c[n-2]-c[n-1]) > tolerance) {
            BOOST_ERROR(type << " interpolation failure"
                        << "\n    cubic coefficient of the 2nd to last"
                        << " polinomial is " << c[n-2]
                        << "\n    cubic coefficient of the last"
                        << " polinomial is " << c[n-1]);
        }
    }
void anonymous_namespace{interpolations.cpp}::checkSymmetry (const char * type, const CubicInterpolation & cubic, Real xMin)
Definition at line 150 of file interpolations.cpp.
References anonymous_namespace{gaussianquadratures.cpp}::tolerance.
{
        Real tolerance = 1.0e-15;
        for (Real x = xMin; x < 0.0; x += 0.1) {
            Real y1 = cubic(x), y2 = cubic(-x);
            if (std::fabs(y1-y2) > tolerance) {
                BOOST_ERROR(type << " interpolation not symmetric"
                            << "\n    x = " << x
                            << "\n    g(x)  = " << y1
                            << "\n    g(-x) = " << y2
                            << "\n    error:  " << std::fabs(y1-y2));
            }
        }
    }
template<class I , class J > void anonymous_namespace{interpolations.cpp}::checkValues (const char * type, const CubicInterpolation & cubic, I xBegin, I xEnd, J yBegin)
Definition at line 77 of file interpolations.cpp.
References QL_SCIENTIFIC, and anonymous_namespace{gaussianquadratures.cpp}::tolerance.
Referenced by InterpolationTest::testDerivativeEndConditions(), InterpolationTest::testSimmetricEndConditions(), InterpolationTest::testSplineOnGaussianValues(), InterpolationTest::testSplineOnGenericValues(), and InterpolationTest::testSplineOnRPN15AValues().
{
        Real tolerance = 2.0e-15;
        while (xBegin != xEnd) {
            Real interpolated = cubic(*xBegin);
            if (std::fabs(interpolated-*yBegin) > tolerance) {
                BOOST_ERROR(type << " interpolation failed at x = " << *xBegin
                            << QL_SCIENTIFIC
                            << "\n    interpolated value: " << interpolated
                            << "\n    expected value:     " << *yBegin
                            << "\n    error:              "
                            << std::fabs(interpolated-*yBegin));
            }
            ++xBegin; ++yBegin;
        }
    }
Real anonymous_namespace{interpolations.cpp}::epanechnikovKernel (Real u)
Definition at line 189 of file interpolations.cpp.
Referenced by InterpolationTest::testKernelInterpolation2D().
{
        if(std::fabs(u)<=1){
            return (3.0/4.0)*(1-u*u);
        }else{
            return 0.0;
        }
    }
Real anonymous_namespace{interpolations.cpp}::f (Real h)
Definition at line 1615 of file interpolations.cpp.
References QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow().
Referenced by QuantLib::GaussLobattoIntegral::adaptivGaussLobattoStep(), QuantLib::AmericanPayoffAtExpiry::AmericanPayoffAtExpiry(), QuantLib::AmericanPayoffAtHit::AmericanPayoffAtHit(), QuantLib::FdmLogInnerValue::avgInnerValueCalc(), QuantLib::blackFormulaImpliedStdDev(), QuantLib::AnalyticSimpleChooserEngine::calculate(), QuantLib::VarianceGammaEngine::calculate(), QuantLib::IntegralEngine::calculate(), QuantLib::AnalyticCompoundOptionEngine::calculate(), QuantLib::KirkEngine::calculate(), QuantLib::AnalyticDiscreteGeometricAverageStrikeAsianEngine::calculate(), QuantLib::detail::ImpliedVolatilityHelper::calculate(), QuantLib::AnalyticHestonEngine::Integration::calculate(), QuantLib::GaussLobattoIntegral::calculateAbsTolerance(), QuantLib::CalibratedModel::calibrate(), QuantLib::CapPseudoDerivative::CapPseudoDerivative(), QuantLib::clip(), QuantLib::SwapForwardMappings::cmSwapZedMatrix(), QuantLib::SwapForwardMappings::coinitialSwapZedMatrix(), QuantLib::compose(), QuantLib::compose3(), QuantLib::ReplicatingVarianceSwapEngine::computeLogPayoff(), QuantLib::ReplicatingVarianceSwapEngine::computeOptionWeights(), QuantLib::ReplicatingVarianceSwapEngine::computeReplicatingPortfolio(), QuantLib::SwapForwardMappings::coterminalSwapForwardJacobian(), QuantLib::SwapForwardMappings::coterminalSwapZedMatrix(), QuantLib::BlackDeltaCalculator::cumD1(), QuantLib::BlackDeltaCalculator::cumD2(), QuantLib::VolatilityBumpInstrumentJacobian::derivativesVolatility(), QuantLib::Vasicek::discountBondOption(), QuantLib::HullWhite::discountBondOption(), QuantLib::G2::discountBondOption(), QuantLib::HullWhiteProcess::drift(), QuantLib::LiborForwardModelProcess::drift(), QuantLib::HullWhiteForwardProcess::drift(), QuantLib::LiborForwardModelProcess::evolve(), QuantLib::GeneralStatistics::expectationValue(), QuantLib::Distribution::expectedValue(), QuantLib::genericEarlyExerciseOptimization(), QuantLib::RatePseudoRootJacobian::getBumps(), QuantLib::RatePseudoRootJacobianAllElements::getBumps(), QuantLib::LiborForwardModel::getSwaptionVolatilityMatrix(), QuantLib::CreditDefaultSwap::impliedHazardRate(), QuantLib::CalibrationHelper::impliedVolatility(), QuantLib::CdsOption::impliedVolatility(), QuantLib::CallableBond::impliedVolatility(), QuantLib::CapFloor::impliedVolatility(), QuantLib::Swaption::impliedVolatility(), QuantLib::BlackCalculator::initialize(), QuantLib::FdmExtOUJumpModelInnerValue::innerValue(), QuantLib::FdmExpExtOUInnerValueCalculator::innerValue(), anonymous_namespace{vpp.cpp}::PathGasPrice::innerValue(), anonymous_namespace{vpp.cpp}::PathSparkSpreadPrice::innerValue(), QuantLib::OneFactorCopula::integral(), QuantLib::SimpsonIntegral::integrate(), QuantLib::SegmentIntegral::integrate(), QuantLib::GaussLobattoIntegral::integrate(), QuantLib::TrapezoidIntegral< Default >::integrate(), QuantLib::GaussKronrodNonAdaptive::integrate(), QuantLib::Default::integrate(), QuantLib::GaussKronrodAdaptive::integrate(), QuantLib::MidPoint::integrate(), QuantLib::NumericHaganPricer::integrate(), QuantLib::GaussKronrodAdaptive::integrateRecursively(), QuantLib::FdmBatesOp::integro(), QuantLib::VegaBumpCollection::isFull(), QuantLib::VegaBumpCollection::isNonOverlapping(), make_error_function(), QuantLib::PathwiseVegasOuterAccountingEngine::multiplePathValues(), QuantLib::BlackDeltaCalculator::nD1(), QuantLib::BlackDeltaCalculator::nD2(), QuantLib::ZeroInflationIndex::needsForecast(), QuantLib::ZigguratRng::nextGaussian(), QuantLib::HaltonRsg::nextSequence(), QuantLib::Integrator::operator()(), QuantLib::anonymous_namespace{defaultdensitystructure.cpp}::remapper< F >::operator()(), QuantLib::anonymous_namespace{hazardratestructure.cpp}::remapper< F >::operator()(), QuantLib::GaussianQuadrature::operator()(), QuantLib::BivariateCumulativeNormalDistributionWe04DP::operator()(), QuantLib::VariancePathPricer::operator()(), QuantLib::LossDistBucketing::operator()(), QuantLib::TabulatedGaussLegendre::operator()(), QuantLib::Period::Period(), QuantLib::anonymous_namespace{defaultdensitystructure.cpp}::remap(), QuantLib::anonymous_namespace{hazardratestructure.cpp}::remap(), QuantLib::LiborForwardModel::S_0(), QuantLib::SampledCurve::sample(), QuantLib::MultiplicativePriceSeasonality::seasonalityCorrection(), QuantLib::PathwiseAccountingEngine::singlePathValues(), QuantLib::PathwiseVegasAccountingEngine::singlePathValues(), QuantLib::PathwiseVegasOuterAccountingEngine::singlePathValues(), QuantLib::Solver1D< Ridder >::solve(), QuantLib::Bisection::solveImpl(), QuantLib::Brent::solveImpl(), QuantLib::FalsePosition::solveImpl(), QuantLib::Ridder::solveImpl(), QuantLib::Secant::solveImpl(), QuantLib::FiniteDifferenceNewtonSafe::solveImpl(), QuantLib::NewtonSafe::solveImpl(), QuantLib::Newton::solveImpl(), QuantLib::OptionletStripper2::spreadsVolImplied(), QuantLib::BlackDeltaCalculator::strikeFromDelta(), QuantLib::DefaultDensityStructure::survivalProbabilityImpl(), QuantLib::HazardRateStructure::survivalProbabilityImpl(), QuantLib::SVD::SVD(), QuantLib::SwapForwardMappings::swaptionImpliedVolatility(), QuantLib::SwaptionPseudoDerivative::SwaptionPseudoDerivative(), InterpolationTest::testAsFunctor(), InterpolationTest::testBackwardFlat(), InterpolationTest::testBicubicDerivatives(), anonymous_namespace{piecewiseyieldcurve.cpp}::testBMACurveConsistency(), InterpolationTest::testDerivativeEndConditions(), MatricesTest::testDeterminant(), SwingOptionTest::testExtendedOrnsteinUhlenbeckProcess(), InterpolationTest::testForwardFlat(), QuoteTest::testForwardValueQuoteAndImpliedStdevQuote(), VPPTest::testGemanRoncoroniProcess(), EuropeanOptionTest::testImpliedVolContainment(), InterpolationTest::testKernelInterpolation(), VPPTest::testKlugeExtOUSpreadOption(), PiecewiseYieldCurveTest::testLiborFixing(), LinearLeastSquaresRegressionTest::testMultiDimRegression(), InterpolationTest::testNonRestrictiveHymanFilter(), PiecewiseYieldCurveTest::testObservability(), QuoteTest::testObservable(), InstrumentTest::testObservable(), QuoteTest::testObservableHandle(), MarketModelTest::testPathwiseVegas(), InflationTest::testPeriod(), InterpolationTest::testRichardsonExtrapolation(), InterpolationTest::testSimmetricEndConditions(), anonymous_namespace{integrals.cpp}::testSingle(), InterpolationTest::testSplineErrorOnGaussianValues(), InterpolationTest::testSplineOnGaussianValues(), InterpolationTest::testSplineOnGenericValues(), InterpolationTest::testSplineOnRPN15AValues(), SwaptionVolatilityCubeTest::testSpreadedCube(), QuantLib::FdmNdimSolver< N >::thetaAt(), QuantLib::detail::ConvexMonotoneImpl< I1, I2 >::update(), QuantLib::CalibratedModel::value(), QuantLib::VegaBumpCollection::VegaBumpCollection(), and QuantLib::MakeOIS::withPaymentFrequency().
                   {
        return std::pow( 1.0 + h, 1/h);
    }
std::vector<Real> anonymous_namespace{interpolations.cpp}::gaussian (const std::vector< Real > & x)
Definition at line 62 of file interpolations.cpp.
{
        std::vector<Real> y(x.size());
        for (Size i=0; i<x.size(); i++)
            y[i] = std::exp(-x[i]*x[i]);
        return y;
    }
template<class F > errorFunction<F> anonymous_namespace{interpolations.cpp}::make_error_function (const F & f)
Definition at line 179 of file interpolations.cpp.
References f().
Referenced by InterpolationTest::testSplineErrorOnGaussianValues().
{
        return errorFunction<F>(f);
    }
Real anonymous_namespace{interpolations.cpp}::multif (Real s, Real t, Real u, Real v, Real w)
Definition at line 183 of file interpolations.cpp.
Referenced by InterpolationTest::testMultiSpline().
{
        return std::sqrt(s * std::sinh(std::log(t)) +
                         std::exp(std::sin(u) * std::sin(3 * v)) +
                         std::sinh(std::log(v * w)));
    }
std::vector<Real> anonymous_namespace{interpolations.cpp}::parabolic (const std::vector< Real > & x)
Definition at line 69 of file interpolations.cpp.
Referenced by InterpolationTest::testDerivativeEndConditions(), and InterpolationTest::testNonRestrictiveHymanFilter().
{
        std::vector<Real> y(x.size());
        for (Size i=0; i<x.size(); i++)
            y[i] = -x[i]*x[i];
        return y;
    }
std::vector<Real> anonymous_namespace{interpolations.cpp}::xRange (Real start, Real finish, Size points)
Definition at line 53 of file interpolations.cpp.
Referenced by InterpolationTest::testDerivativeEndConditions(), InterpolationTest::testNonRestrictiveHymanFilter(), InterpolationTest::testSimmetricEndConditions(), InterpolationTest::testSplineErrorOnGaussianValues(), and InterpolationTest::testSplineOnGaussianValues().
{
        std::vector<Real> x(points);
        Real dx = (finish-start)/(points-1);
        for (Size i=0; i<points-1; i++)
            x[i] = start+i*dx;
        x[points-1] = finish;
        return x;
    }