QuantLib: QuantLib::anonymous_namespace{lsmbasissystem.cpp} Namespace Reference
QuantLib::anonymous_namespace{lsmbasissystem.cpp} Namespace Reference
Classes
class MonomialFct
class MultiDimFct
Typedefs
typedef std::vector
< boost::function1< Real, Real > > VF_R
typedef std::vector
< boost::function1< Real,
Array > > VF_A
typedef std::vector
< std::vector< Size > > VV
Functions
void check_tuples (const VV &v, Size dim, Size order)
VV next_order_tuples (const VV &v)
Variables
Real(GaussianOrthogonalPolynomial::* ptr_w)(Size, Real) const
Typedef Documentation
typedef std::vector<boost::function1<Real, Array> > QuantLib::anonymous_namespace{lsmbasissystem.cpp}::VF_A
Definition at line 38 of file lsmbasissystem.cpp.
typedef std::vector<boost::function1<Real, Real> > QuantLib::anonymous_namespace{lsmbasissystem.cpp}::VF_R
Definition at line 37 of file lsmbasissystem.cpp.
typedef std::vector<std::vector<Size> > QuantLib::anonymous_namespace{lsmbasissystem.cpp}::VV
Definition at line 39 of file lsmbasissystem.cpp.
Function Documentation
void QuantLib::anonymous_namespace{lsmbasissystem.cpp}::check_tuples (const VV & v, Size dim, Size order)
Definition at line 78 of file lsmbasissystem.cpp.
References QL_REQUIRE.
Referenced by next_order_tuples().
{
            for(Size i=0; i<v.size(); ++i) {
                QL_REQUIRE(dim==v[i].size(), "wrong tuple size");
                QL_REQUIRE(order==std::accumulate(v[i].begin(), v[i].end(), 0u),
                    "wrong tuple order");
            }
        }
VV QuantLib::anonymous_namespace{lsmbasissystem.cpp}::next_order_tuples (const VV & v)
Definition at line 87 of file lsmbasissystem.cpp.
References check_tuples().
Referenced by QuantLib::LsmBasisSystem::multiPathBasisSystem().
{
            const Size order = std::accumulate(v[0].begin(), v[0].end(), 0u);
            const Size dim = v[0].size();
            check_tuples(v, dim, order);
            // the set of unique tuples
            std::set<std::vector<Size> > tuples;
            std::vector<Size> x;
            for(Size i=0; i<dim; ++i) {
                // increase i-th value in every tuple by 1
                for(Size j=0; j<v.size(); ++j) {
                    x = v[j];
                    x[i] += 1;
                    tuples.insert(x);
                }
            }
            VV ret(tuples.begin(), tuples.end());
            return ret;
        }
Variable Documentation
Real(GaussianOrthogonalPolynomial::* QuantLib::anonymous_namespace{lsmbasissystem.cpp}::ptr_w)(Size, Real) const
Initial value:
            &GaussianOrthogonalPolynomial::weightedValue
Definition at line 40 of file lsmbasissystem.cpp.
Referenced by QuantLib::LsmBasisSystem::pathBasisSystem().