QuantLib: anonymous_namespace{errors.cpp} Namespace Reference
anonymous_namespace{errors.cpp} Namespace Reference
Functions
std::string trim (const std::string &file)
std::string format (const std::string &file, long line, const std::string &function, const std::string &message)
Function Documentation
std::string anonymous_namespace{errors.cpp}::format (const std::string & file, long line, const std::string & function, const std::string & message)
Definition at line 63 of file errors.cpp.
Referenced by boost::assertion_failed(), QuantLib::Error::Error(), and QuantLib::operator<<().
{
        std::ostringstream msg;
        #ifdef QL_ERROR_LINES
        msg << "\n" << file << ":" << line << ": ";
        #endif
        #ifdef QL_ERROR_FUNCTIONS
        if (function != "(unknown)")
            msg << "In function `" << function << "': \n";
        #endif
        msg << message;
        return msg.str();
    }
std::string anonymous_namespace{errors.cpp}::trim (const std::string & file)
Definition at line 25 of file errors.cpp.
{
        // find last path separator
        std::string::size_type n = file.find_last_of("/\\");
        if (n == std::string::npos)
            // return the whole thing--it's a naked file name anyway
            return file;
        else
            // keep the file name only
            return file.substr(n+1);
    }