QuantLib: anonymous_namespace{integrals.cpp} Namespace Reference
anonymous_namespace{integrals.cpp} Namespace Reference
Functions
template<class T >
void testSingle (const T &I, const std::string &tag, const boost::function< Real(Real)> &f, Real xMin, Real xMax, Real expected)
template<class T >
void testSeveral (const T &I)
Variables
Real tolerance = 1.0e-6
Function Documentation
template<class T > void anonymous_namespace{integrals.cpp}::testSeveral (const T & I)
Definition at line 52 of file integrals.cpp.
References M_PI, and anonymous_namespace{gaussianquadratures.cpp}::testSingle().
Referenced by IntegralTest::testGaussKronrodAdaptive(), IntegralTest::testGaussKronrodNonAdaptive(), IntegralTest::testGaussLobatto(), IntegralTest::testMidPointTrapezoid(), IntegralTest::testSegment(), IntegralTest::testSimpson(), and IntegralTest::testTrapezoid().
{
        testSingle(I, "f(x) = 1",
                   constant<Real,Real>(1.0), 0.0, 1.0, 1.0);
        testSingle(I, "f(x) = x",
                   identity<Real>(),           0.0, 1.0, 0.5);
        testSingle(I, "f(x) = x^2",
                   square<Real>(),             0.0, 1.0, 1.0/3.0);
        testSingle(I, "f(x) = sin(x)",
                   std::ptr_fun<Real,Real>(std::sin), 0.0, M_PI, 2.0);
        testSingle(I, "f(x) = cos(x)",
                   std::ptr_fun<Real,Real>(std::cos), 0.0, M_PI, 0.0);
        testSingle(I, "f(x) = Gaussian(x)",
                   NormalDistribution(), -10.0, 10.0, 1.0);
        testSingle(I, "f(x) = Abcd2(x)",
                   AbcdSquared(0.07, 0.07, 0.5, 0.1, 8.0, 10.0), 5.0, 6.0,
                   AbcdFunction(0.07, 0.07, 0.5, 0.1).covariance(5.0, 6.0, 8.0, 10.0));
    }
template<class T > void anonymous_namespace{integrals.cpp}::testSingle (const T & I, const std::string & tag, const boost::function< Real(Real)> & f, Real xMin, Real xMax, Real expected)
Definition at line 39 of file integrals.cpp.
References anonymous_namespace{interpolations.cpp}::f(), and anonymous_namespace{matrices.cpp}::I.
{
        Real calculated = I(f,xMin,xMax);
        if (std::fabs(calculated-expected) > tolerance) {
            BOOST_FAIL(std::setprecision(10)
                       << "integrating " << tag
                       << "    calculated: " << calculated
                       << "    expected:   " << expected);
        }
    }
Variable Documentation
Real anonymous_namespace{integrals.cpp}::tolerance = 1.0e-6
Definition at line 36 of file integrals.cpp.