QuantLib: anonymous_namespace{piecewiseyieldcurve.cpp} Namespace Reference
anonymous_namespace{piecewiseyieldcurve.cpp} Namespace Reference
Classes
struct Datum
struct BondDatum
struct CommonVars
Functions
template<class T , class I , template< class C > class B>
void testCurveConsistency (CommonVars &vars, const I &interpolator=I(), Real tolerance=1.0e-9)
template<class T , class I , template< class C > class B>
void testBMACurveConsistency (CommonVars &vars, const I &interpolator=I(), Real tolerance=1.0e-9)
template<class T , class I >
void testCurveCopy (CommonVars &vars, const I &interpolator=I())
Variables
Datum depositData []
Datum fraData []
Datum swapData []
BondDatum bondData []
Datum bmaData []
Function Documentation
template<class T , class I , template< class C > class B> void anonymous_namespace{piecewiseyieldcurve.cpp}::testBMACurveConsistency (CommonVars & vars, const I & interpolator = I(), Real tolerance = 1.0e-9)
Definition at line 397 of file piecewiseyieldcurve.cpp.
References QuantLib::Calendar::adjust(), QuantLib::Calendar::advance(), QuantLib::MakeSchedule::backwards(), anonymous_namespace{piecewiseyieldcurve.cpp}::CommonVars::bmaConvention, anonymous_namespace{piecewiseyieldcurve.cpp}::CommonVars::bmaDayCounter, anonymous_namespace{piecewiseyieldcurve.cpp}::CommonVars::bmaFrequency, anonymous_namespace{piecewiseyieldcurve.cpp}::CommonVars::bmaHelpers, anonymous_namespace{piecewiseyieldcurve.cpp}::CommonVars::bmas, anonymous_namespace{piecewiseyieldcurve.cpp}::CommonVars::calendar, QuantLib::Days, QuantLib::Settings::evaluationDate(), anonymous_namespace{interpolations.cpp}::f(), anonymous_namespace{piecewiseyieldcurve.cpp}::CommonVars::fractions, QuantLib::MakeSchedule::from(), QuantLib::Singleton< Settings >::instance(), QuantLib::JoinHolidays, QuantLib::RelinkableHandle< T >::linkTo(), QuantLib::Months, anonymous_namespace{piecewiseyieldcurve.cpp}::Datum::n, QuantLib::BMASwap::Payer, anonymous_namespace{piecewiseyieldcurve.cpp}::Datum::rate, anonymous_namespace{piecewiseyieldcurve.cpp}::CommonVars::settlement, anonymous_namespace{piecewiseyieldcurve.cpp}::CommonVars::settlementDays, QuantLib::swap(), anonymous_namespace{piecewiseyieldcurve.cpp}::CommonVars::termStructure, QuantLib::MakeSchedule::to(), anonymous_namespace{piecewiseyieldcurve.cpp}::CommonVars::today, QuantLib::Date::todaysDate(), anonymous_namespace{gaussianquadratures.cpp}::tolerance, anonymous_namespace{piecewiseyieldcurve.cpp}::Datum::units, QuantLib::Date::weekday(), QuantLib::MakeSchedule::withCalendar(), QuantLib::MakeSchedule::withFrequency(), and QuantLib::MakeSchedule::withTenor().
Referenced by PiecewiseYieldCurveTest::testConvexMonotoneForwardConsistency().
{
        // re-adjust settlement
        vars.calendar = JointCalendar(BMAIndex().fixingCalendar(),
                                      USDLibor(3*Months).fixingCalendar(),
                                      JoinHolidays);
        vars.today = vars.calendar.adjust(Date::todaysDate());
        Settings::instance().evaluationDate() = vars.today;
        vars.settlement =
            vars.calendar.advance(vars.today,vars.settlementDays,Days);
        Handle<YieldTermStructure> riskFreeCurve(
            boost::shared_ptr<YieldTermStructure>(
                        new FlatForward(vars.settlement, 0.04, Actual360())));
        boost::shared_ptr<BMAIndex> bmaIndex(new BMAIndex);
        boost::shared_ptr<IborIndex> liborIndex(
                                        new USDLibor(3*Months,riskFreeCurve));
        for (Size i=0; i<vars.bmas; ++i) {
            Handle<Quote> f(vars.fractions[i]);
            vars.bmaHelpers[i] = boost::shared_ptr<RateHelper>(
                      new BMASwapRateHelper(f, bmaData[i].n*bmaData[i].units,
                                            vars.settlementDays,
                                            vars.calendar,
                                            Period(vars.bmaFrequency),
                                            vars.bmaConvention,
                                            vars.bmaDayCounter,
                                            bmaIndex,
                                            liborIndex));
        }
        Weekday w = vars.today.weekday();
        Date lastWednesday =
            (w >= 4) ? vars.today - (w - 4) : vars.today + (4 - w - 7);
        Date lastFixing = bmaIndex->fixingCalendar().adjust(lastWednesday);
        bmaIndex->addFixing(lastFixing, 0.03);
        vars.termStructure = boost::shared_ptr<YieldTermStructure>(new
            PiecewiseYieldCurve<T,I,B>(vars.settlement, vars.bmaHelpers,
                                       Actual360(),
                                       1.0e-12,
                                       interpolator));
        RelinkableHandle<YieldTermStructure> curveHandle;
        curveHandle.linkTo(vars.termStructure);
        // check BMA swaps
        boost::shared_ptr<BMAIndex> bma(new BMAIndex(curveHandle));
        boost::shared_ptr<IborIndex> libor3m(new USDLibor(3*Months,
                                                          riskFreeCurve));
        for (Size i=0; i<vars.bmas; i++) {
            Period tenor = bmaData[i].n*bmaData[i].units;
            Schedule bmaSchedule =
                MakeSchedule().from(vars.settlement)
                              .to(vars.settlement+tenor)
                              .withFrequency(vars.bmaFrequency)
                              .withCalendar(bma->fixingCalendar())
                              .withConvention(vars.bmaConvention)
                              .backwards();
            Schedule liborSchedule =
                MakeSchedule().from(vars.settlement)
                              .to(vars.settlement+tenor)
                              .withTenor(libor3m->tenor())
                              .withCalendar(libor3m->fixingCalendar())
                              .withConvention(libor3m->businessDayConvention())
                              .endOfMonth(libor3m->endOfMonth())
                              .backwards();
            BMASwap swap(BMASwap::Payer, 100.0,
                         liborSchedule, 0.75, 0.0,
                         libor3m, libor3m->dayCounter(),
                         bmaSchedule, bma, vars.bmaDayCounter);
            swap.setPricingEngine(boost::shared_ptr<PricingEngine>(
              new DiscountingSwapEngine(libor3m->forwardingTermStructure())));
            Real expectedFraction = bmaData[i].rate/100,
                 estimatedFraction = swap.fairLiborFraction();
            Real error = std::fabs(expectedFraction-estimatedFraction);
            if (error > tolerance) {
                BOOST_ERROR(bmaData[i].n << " year(s) BMA swap:\n"
                            << std::setprecision(8)
                            << "\n estimated libor fraction: " << estimatedFraction
                            << "\n expected libor fraction:  " << expectedFraction
                            << "\n error:          " << error
                            << "\n tolerance:      " << tolerance);
            }
        }
    }
template<class T , class I , template< class C > class B> void anonymous_namespace{piecewiseyieldcurve.cpp}::testCurveConsistency (CommonVars & vars, const I & interpolator = I(), Real tolerance = 1.0e-9)
Definition at line 271 of file piecewiseyieldcurve.cpp.
References QuantLib::Calendar::advance(), anonymous_namespace{piecewiseyieldcurve.cpp}::CommonVars::bondConvention, anonymous_namespace{piecewiseyieldcurve.cpp}::CommonVars::bondDayCounter, anonymous_namespace{piecewiseyieldcurve.cpp}::CommonVars::bondHelpers, anonymous_namespace{piecewiseyieldcurve.cpp}::CommonVars::bondRedemption, anonymous_namespace{piecewiseyieldcurve.cpp}::CommonVars::bonds, anonymous_namespace{piecewiseyieldcurve.cpp}::CommonVars::bondSettlementDays, anonymous_namespace{piecewiseyieldcurve.cpp}::CommonVars::calendar, QuantLib::Bond::cleanPrice(), anonymous_namespace{piecewiseyieldcurve.cpp}::CommonVars::deposits, QuantLib::VanillaSwap::fairRate(), anonymous_namespace{piecewiseyieldcurve.cpp}::CommonVars::fixedLegConvention, anonymous_namespace{piecewiseyieldcurve.cpp}::CommonVars::fixedLegDayCounter, anonymous_namespace{piecewiseyieldcurve.cpp}::CommonVars::fixedLegFrequency, QuantLib::InterestRateIndex::fixing(), QuantLib::ForwardRateAgreement::forwardRate(), anonymous_namespace{piecewiseyieldcurve.cpp}::CommonVars::fraHelpers, anonymous_namespace{piecewiseyieldcurve.cpp}::CommonVars::fras, anonymous_namespace{piecewiseyieldcurve.cpp}::CommonVars::instruments, QuantLib::RelinkableHandle< T >::linkTo(), QuantLib::Position::Long, QuantLib::Months, anonymous_namespace{piecewiseyieldcurve.cpp}::Datum::n, anonymous_namespace{piecewiseyieldcurve.cpp}::BondDatum::n, QuantLib::io::ordinal(), anonymous_namespace{piecewiseyieldcurve.cpp}::BondDatum::price, anonymous_namespace{piecewiseyieldcurve.cpp}::Datum::rate, QuantLib::io::rate(), anonymous_namespace{piecewiseyieldcurve.cpp}::CommonVars::schedules, QuantLib::Instrument::setPricingEngine(), anonymous_namespace{piecewiseyieldcurve.cpp}::CommonVars::settlement, QuantLib::swap(), anonymous_namespace{piecewiseyieldcurve.cpp}::CommonVars::swaps, anonymous_namespace{piecewiseyieldcurve.cpp}::CommonVars::termStructure, anonymous_namespace{piecewiseyieldcurve.cpp}::CommonVars::today, anonymous_namespace{gaussianquadratures.cpp}::tolerance, anonymous_namespace{piecewiseyieldcurve.cpp}::Datum::units, anonymous_namespace{piecewiseyieldcurve.cpp}::BondDatum::units, QuantLib::Weeks, QuantLib::MakeVanillaSwap::withEffectiveDate(), QuantLib::MakeVanillaSwap::withFixedLegConvention(), QuantLib::MakeVanillaSwap::withFixedLegDayCount(), QuantLib::MakeVanillaSwap::withFixedLegTenor(), QuantLib::MakeVanillaSwap::withFixedLegTerminationDateConvention(), and QuantLib::Years.
{
        vars.termStructure = boost::shared_ptr<YieldTermStructure>(new
            PiecewiseYieldCurve<T,I,B>(vars.settlement, vars.instruments,
                                       Actual360(),
                                       interpolator));
        RelinkableHandle<YieldTermStructure> curveHandle;
        curveHandle.linkTo(vars.termStructure);
        // check deposits
        for (Size i=0; i<vars.deposits; i++) {
            Euribor index(depositData[i].n*depositData[i].units,curveHandle);
            Rate expectedRate  = depositData[i].rate/100,
                 estimatedRate = index.fixing(vars.today);
            if (std::fabs(expectedRate-estimatedRate) > tolerance) {
                BOOST_ERROR(
                    depositData[i].n << " "
                    << (depositData[i].units == Weeks ? "week(s)" : "month(s)")
                    << " deposit:"
                    << std::setprecision(8)
                    << "\n    estimated rate: " << io::rate(estimatedRate)
                    << "\n    expected rate:  " << io::rate(expectedRate));
            }
        }
        // check swaps
        boost::shared_ptr<IborIndex> euribor6m(new Euribor6M(curveHandle));
        for (Size i=0; i<vars.swaps; i++) {
            Period tenor = swapData[i].n*swapData[i].units;
            VanillaSwap swap = MakeVanillaSwap(tenor, euribor6m, 0.0)
                .withEffectiveDate(vars.settlement)
                .withFixedLegDayCount(vars.fixedLegDayCounter)
                .withFixedLegTenor(Period(vars.fixedLegFrequency))
                .withFixedLegConvention(vars.fixedLegConvention)
                .withFixedLegTerminationDateConvention(vars.fixedLegConvention);
            Rate expectedRate = swapData[i].rate/100,
                 estimatedRate = swap.fairRate();
            Spread error = std::fabs(expectedRate-estimatedRate);
            if (error > tolerance) {
                BOOST_ERROR(
                    swapData[i].n << " year(s) swap:\n"
                    << std::setprecision(8)
                    << "\n estimated rate: " << io::rate(estimatedRate)
                    << "\n expected rate:  " << io::rate(expectedRate)
                    << "\n error:          " << io::rate(error)
                    << "\n tolerance:      " << io::rate(tolerance));
            }
        }
        // check bonds
        vars.termStructure = boost::shared_ptr<YieldTermStructure>(new
            PiecewiseYieldCurve<T,I,B>(vars.settlement, vars.bondHelpers,
                                       Actual360(),
                                       interpolator));
        curveHandle.linkTo(vars.termStructure);
        for (Size i=0; i<vars.bonds; i++) {
            Date maturity = vars.calendar.advance(vars.today,
                                                  bondData[i].n,
                                                  bondData[i].units);
            Date issue = vars.calendar.advance(maturity,
                                               -bondData[i].length,
                                               Years);
            std::vector<Rate> coupons(1, bondData[i].coupon/100.0);
            FixedRateBond bond(vars.bondSettlementDays, 100.0,
                               vars.schedules[i], coupons,
                               vars.bondDayCounter, vars.bondConvention,
                               vars.bondRedemption, issue);
            boost::shared_ptr<PricingEngine> bondEngine(
                                      new DiscountingBondEngine(curveHandle));
            bond.setPricingEngine(bondEngine);
            Real expectedPrice = bondData[i].price,
                 estimatedPrice = bond.cleanPrice();
            Real error = std::fabs(expectedPrice-estimatedPrice);
            if (error > tolerance) {
                BOOST_ERROR(io::ordinal(i+1) << " bond failure:" <<
                            std::setprecision(8) <<
                            "\n  estimated price: " << estimatedPrice <<
                            "\n  expected price:  " << expectedPrice <<
                            "\n  error:           " << error);
            }
        }
        // check FRA
        vars.termStructure = boost::shared_ptr<YieldTermStructure>(new
            PiecewiseYieldCurve<T,I>(vars.settlement, vars.fraHelpers,
                                     Actual360(),
                                     interpolator));
        curveHandle.linkTo(vars.termStructure);
        boost::shared_ptr<IborIndex> euribor3m(new Euribor3M(curveHandle));
        for (Size i=0; i<vars.fras; i++) {
            Date start =
                vars.calendar.advance(vars.settlement,
                                      fraData[i].n,
                                      fraData[i].units,
                                      euribor3m->businessDayConvention(),
                                      euribor3m->endOfMonth());
            Date end = vars.calendar.advance(start, 3, Months,
                                             euribor3m->businessDayConvention(),
                                             euribor3m->endOfMonth());
            ForwardRateAgreement fra(start, end, Position::Long,
                                     fraData[i].rate/100, 100.0,
                                     euribor3m, curveHandle);
            Rate expectedRate = fraData[i].rate/100,
                 estimatedRate = fra.forwardRate();
            if (std::fabs(expectedRate-estimatedRate) > tolerance) {
                BOOST_ERROR(io::ordinal(i+1) << " FRA failure:" <<
                            std::setprecision(8) <<
                            "\n  estimated rate: " << io::rate(estimatedRate) <<
                            "\n  expected rate:  " << io::rate(expectedRate));
            }
        }
    }
template<class T , class I > void anonymous_namespace{piecewiseyieldcurve.cpp}::testCurveCopy (CommonVars & vars, const I & interpolator = I())
Definition at line 845 of file piecewiseyieldcurve.cpp.
References QuantLib::close(), QuantLib::Continuous, anonymous_namespace{piecewiseyieldcurve.cpp}::CommonVars::instruments, anonymous_namespace{piecewiseyieldcurve.cpp}::CommonVars::rates, QuantLib::LazyObject::recalculate(), anonymous_namespace{piecewiseyieldcurve.cpp}::CommonVars::settlement, anonymous_namespace{quantlibbenchmark.cpp}::t, and anonymous_namespace{swaption.cpp}::type.
{
        PiecewiseYieldCurve<T,I> curve(vars.settlement, vars.instruments,
                                       Actual360(),
                                       1.0e-12,
                                       interpolator);
        // necessary to trigger bootstrap
        curve.recalculate();
        typedef typename T::template curve<I>::type base_curve;
        base_curve copiedCurve = curve;
        // the two curves should be the same.
        Time t = 2.718;
        Rate r1 = curve.zeroRate(t, Continuous);
        Rate r2 = copiedCurve.zeroRate(t, Continuous);
        if (!close(r1, r2)) {
            BOOST_ERROR("failed to link original and copied curve");
        }
        for (Size i=0; i<vars.rates.size(); ++i) {
            vars.rates[i]->setValue(vars.rates[i]->value() + 0.001);
        }
        // now the original curve should have changed; the copied
        // curve should not.
        Rate r3 = curve.zeroRate(t, Continuous);
        Rate r4 = copiedCurve.zeroRate(t, Continuous);
        if (close(r1, r3)) {
            BOOST_ERROR("failed to modify original curve");
        }
        if (!close(r2,r4)) {
            BOOST_ERROR(
                    "failed to break link between original and copied curve");
        }
    }
Variable Documentation
Datum anonymous_namespace{piecewiseyieldcurve.cpp}::bmaData[]
Initial value:
 {
        {  1, Years, 67.56 },
        {  2, Years, 68.00 },
        {  3, Years, 68.25 },
        {  4, Years, 68.50 },
        {  5, Years, 68.81 },
        {  7, Years, 69.50 },
        { 10, Years, 70.44 },
        { 15, Years, 71.69 },
        { 20, Years, 72.69 },
        { 30, Years, 73.81 }
    }
Definition at line 114 of file piecewiseyieldcurve.cpp.
BondDatum anonymous_namespace{piecewiseyieldcurve.cpp}::bondData[]
Initial value:
 {
        {  6, Months, 5, Semiannual, 4.75, 101.320 },
        {  1, Years,  3, Semiannual, 2.75, 100.590 },
        {  2, Years,  5, Semiannual, 5.00, 105.650 },
        {  5, Years, 11, Semiannual, 5.50, 113.610 },
        { 10, Years, 11, Semiannual, 3.75, 104.070 }
    }
Definition at line 106 of file piecewiseyieldcurve.cpp.
Datum anonymous_namespace{piecewiseyieldcurve.cpp}::depositData[]
Initial value:
 {
        { 1, Weeks,  4.559 },
        { 1, Months, 4.581 },
        { 2, Months, 4.573 },
        { 3, Months, 4.557 },
        { 6, Months, 4.496 },
        { 9, Months, 4.490 }
    }
Definition at line 71 of file piecewiseyieldcurve.cpp.
Datum anonymous_namespace{piecewiseyieldcurve.cpp}::fraData[]
Initial value:
 {
        { 1, Months, 4.581 },
        { 2, Months, 4.573 },
        { 3, Months, 4.557 },
        { 6, Months, 4.496 },
        { 9, Months, 4.490 }
    }
Definition at line 80 of file piecewiseyieldcurve.cpp.
Datum anonymous_namespace{piecewiseyieldcurve.cpp}::swapData[]
Initial value:
 {
        {  1, Years, 4.54 },
        {  2, Years, 4.63 },
        {  3, Years, 4.75 },
        {  4, Years, 4.86 },
        {  5, Years, 4.99 },
        {  6, Years, 5.11 },
        {  7, Years, 5.23 },
        {  8, Years, 5.33 },
        {  9, Years, 5.41 },
        { 10, Years, 5.47 },
        { 12, Years, 5.60 },
        { 15, Years, 5.75 },
        { 20, Years, 5.89 },
        { 25, Years, 5.95 },
        { 30, Years, 5.96 }
    }
Definition at line 88 of file piecewiseyieldcurve.cpp.