QuantLib: QuantLib::io Namespace Reference
QuantLib::io Namespace Reference
Functions
detail::short_date_holder short_date (const Date &)
output dates in short format (mm/dd/yyyy)
detail::long_date_holder long_date (const Date &)
output dates in long format (Month ddth, yyyy)
detail::iso_date_holder iso_date (const Date &)
output dates in ISO format (yyyy-mm-dd)
detail::long_period_holder long_period (const Period &)
output periods in long format (e.g. "2 weeks")
detail::short_period_holder short_period (const Period &)
output periods in short format (e.g. "2w")
detail::long_weekday_holder long_weekday (Weekday d)
detail::short_weekday_holder short_weekday (Weekday d)
detail::shortest_weekday_holder shortest_weekday (Weekday d)
detail::ordinal_holder ordinal (Size)
outputs naturals as 1st, 2nd, 3rd...
detail::percent_holder percent (Real)
output reals as percentages
detail::percent_holder rate (Rate)
output rates and spreads as percentages
detail::percent_holder volatility (Volatility)
output volatilities as percentages
template<class Container >
detail::sequence_holder
< typename
Container::const_iterator > sequence (const Container &c)
output STL-compliant containers as space-separated sequences
template<typename T >
detail::null_checker< T > checknull (T x)
template<typename T >
detail::power_of_two_holder< T > power_of_two (T n)
Integer to_integer (const std::string &str)
Variables
detail::long_weekday_holder long_weekday (Weekday)
output weekdays in long format
detail::short_weekday_holder short_weekday (Weekday)
output weekdays in short format (three letters)
detail::shortest_weekday_holder shortest_weekday (Weekday)
output weekdays in shortest format (two letters)
detail::null_checker< T > checknull (T)
check for nulls before output
detail::power_of_two_holder< T > power_of_two (T)
output integers as powers of two
Function Documentation
template<typename T > detail::null_checker<T> QuantLib::io::checknull (T x) [inline]
Definition at line 112 of file dataformatters.hpp.
{
            return detail::null_checker<T>(x);
        }
detail::long_weekday_holder QuantLib::io::long_weekday (Weekday d)
Definition at line 108 of file weekday.cpp.
{
            return detail::long_weekday_holder(d);
        }
template<typename T > detail::power_of_two_holder<T> QuantLib::io::power_of_two (T n) [inline]
Definition at line 121 of file dataformatters.hpp.
{
            return detail::power_of_two_holder<T>(n);
        }
detail::short_weekday_holder QuantLib::io::short_weekday (Weekday d)
Definition at line 112 of file weekday.cpp.
{
            return detail::short_weekday_holder(d);
        }
detail::shortest_weekday_holder QuantLib::io::shortest_weekday (Weekday d)
Definition at line 116 of file weekday.cpp.
{
            return detail::shortest_weekday_holder(d);
        }
Integer QuantLib::io::to_integer (const std::string & str)
Definition at line 40 of file dataparsers.cpp.
Referenced by QuantLib::ECB::date(), QuantLib::IMM::date(), QuantLib::ECB::nextCode(), QuantLib::DateParser::parse(), QuantLib::DateParser::parseISO(), and QuantLib::PeriodParser::parseOnePeriod().
{
        #ifndef x64
            return  boost::lexical_cast<Integer>(str.c_str());
        #else
            return std::atoi(str.c_str());
        #endif
        }