QuantLib: anonymous_namespace{inflationvolatility.cpp} Namespace Reference
anonymous_namespace{inflationvolatility.cpp} Namespace Reference
Functions
void no_deletion (void *)
void reset ()
void setup ()
void setupPriceSurface ()
Variables
Handle< YieldTermStructure > nominalEUR
Handle< YieldTermStructure > nominalGBP
RelinkableHandle
< YoYInflationTermStructure > yoyEU
RelinkableHandle
< YoYInflationTermStructure > yoyUK
vector< Rate > cStrikesEU
vector< Rate > fStrikesEU
vector< Period > cfMaturitiesEU
boost::shared_ptr< Matrix > cPriceEU
boost::shared_ptr< Matrix > fPriceEU
boost::shared_ptr
< YoYInflationIndex > yoyIndexUK
boost::shared_ptr
< YoYInflationIndex > yoyIndexEU
vector< Rate > cStrikesUK
vector< Rate > fStrikesUK
vector< Period > cfMaturitiesUK
boost::shared_ptr< Matrix > cPriceUK
boost::shared_ptr< Matrix > fPriceUK
boost::shared_ptr
< InterpolatedYoYCapFloorTermPriceSurface
< Bicubic, Cubic > > priceSurfEU
Function Documentation
void anonymous_namespace{inflationvolatility.cpp}::no_deletion (void *)
Definition at line 57 of file inflationvolatility.cpp.
{}
void anonymous_namespace{inflationvolatility.cpp}::reset ()
Definition at line 83 of file inflationvolatility.cpp.
References cfMaturitiesEU, cfMaturitiesUK, cPriceEU, cPriceUK, cStrikesEU, cStrikesUK, fPriceEU, fPriceUK, fStrikesEU, fStrikesUK, QuantLib::RelinkableHandle< T >::linkTo(), nominalEUR, nominalGBP, priceSurfEU, yoyEU, yoyIndexEU, yoyIndexUK, and yoyUK.
Referenced by QuantLib::anonymous_namespace{upperboundengine.cpp}::DecoratedHedge::reset(), QuantLib::EverestOption::results::reset(), QuantLib::ConvergenceStatistics< T, U >::reset(), QuantLib::CdsOption::results::reset(), QuantLib::GenericSequenceStatistics< StatisticsType >::reset(), QuantLib::AssetSwap::results::reset(), QuantLib::Swap::results::reset(), QuantLib::CPICapFloor::results::reset(), QuantLib::YearOnYearInflationSwap::results::reset(), QuantLib::VanillaSwap::results::reset(), QuantLib::SyntheticCDO::results::reset(), QuantLib::CPISwap::results::reset(), QuantLib::CreditDefaultSwap::results::reset(), QuantoOptionTest::testForwardGreeks(), anonymous_namespace{forwardoption.cpp}::testForwardGreeks(), QuantoOptionTest::testForwardPerformanceValues(), QuantoOptionTest::testForwardValues(), CliquetOptionTest::testMcPerformance(), anonymous_namespace{cliquetoption.cpp}::testOptionGreeks(), ForwardOptionTest::testPerformanceValues(), CliquetOptionTest::testValues(), ForwardOptionTest::testValues(), InflationVolTest::testYoYPriceSurfaceToATM(), and InflationVolTest::testYoYPriceSurfaceToVol().
                 {
        nominalEUR = Handle<YieldTermStructure>();
        nominalGBP = Handle<YieldTermStructure>();
        priceSurfEU.reset();
        yoyEU.linkTo(boost::shared_ptr<YoYInflationTermStructure>());
        yoyUK.linkTo(boost::shared_ptr<YoYInflationTermStructure>());
        yoyIndexUK.reset();
        yoyIndexEU.reset();
        cPriceEU.reset();
        fPriceEU.reset();
        cPriceUK.reset();
        fPriceUK.reset();
        yoyIndexUK.reset();
        cStrikesEU.clear();
        fStrikesEU.clear();
        cStrikesUK.clear();
        fStrikesUK.clear();
        cfMaturitiesEU.clear();
        cfMaturitiesUK.clear();
    }
void anonymous_namespace{inflationvolatility.cpp}::setup ()
Definition at line 105 of file inflationvolatility.cpp.
References QuantLib::Calendar::advance(), cfMaturitiesEU, cPriceEU, cStrikesEU, anonymous_namespace{marketmodel.cpp}::d, QuantLib::Days, fPriceEU, fStrikesEU, LENGTH, QuantLib::RelinkableHandle< T >::linkTo(), QuantLib::ModifiedFollowing, QuantLib::Monthly, QuantLib::Months, nominalEUR, nominalGBP, QuantLib::Years, yoyEU, yoyIndexEU, yoyIndexUK, and yoyUK.
Referenced by QuantLib::ForwardPerformanceVanillaEngine< Engine >::calculate(), QuantLib::ForwardVanillaEngine< Engine >::calculate(), OptimizersTest::test(), MarketModelTest::testAbcdVolatilityCompare(), MarketModelTest::testAbcdVolatilityFit(), MarketModelTest::testAbcdVolatilityIntegration(), MarketModelTest::testAllMultiStepProducts(), MarketModelTest::testCallableSwapAnderson(), MarketModelTest::testCallableSwapLS(), MarketModelTest::testCallableSwapNaif(), MatricesTest::testDeterminant(), MarketModelTest::testDriftCalculator(), MatricesTest::testEigenvectors(), MarketModelSmmCapletAlphaCalibrationTest::testFunction(), MarketModelSmmCapletCalibrationTest::testFunction(), MarketModelSmmCapletHomoCalibrationTest::testFunction(), MarketModelTest::testGreeks(), MatricesTest::testHighamSqrt(), MatricesTest::testInverse(), MarketModelTest::testInverseFloater(), MarketModelTest::testIsInSubset(), testMultiProductComposite(), MarketModelCmsTest::testMultiStepCmSwapsAndSwaptions(), MarketModelSmmTest::testMultiStepCoterminalSwapsAndSwaptions(), MarketModelTest::testOneStepForwardsAndOptionlets(), MarketModelTest::testOneStepNormalForwardsAndOptionlets(), MarketModelTest::testPathwiseGreeks(), MarketModelTest::testPathwiseMarketVegas(), MarketModelTest::testPathwiseVegas(), MarketModelTest::testPeriodAdapter(), MarketModelSmmCapletHomoCalibrationTest::testPeriodFunction(), MatricesTest::testQRDecomposition(), MatricesTest::testQRSolve(), MatricesTest::testSqrt(), MarketModelTest::testStochVolForwardsAndOptionlets(), MatricesTest::testSVD(), InflationVolTest::testYoYPriceSurfaceToATM(), and InflationVolTest::testYoYPriceSurfaceToVol().
                 {
        // make sure of the evaluation date
        Date eval = Date(Day(23), Month(11), Year(2007));
        Settings::instance().evaluationDate() = eval;
        yoyIndexUK = boost::shared_ptr<YoYInflationIndex>(new YYUKRPIr(true, yoyUK));
        yoyIndexEU = boost::shared_ptr<YoYInflationIndex>(new YYEUHICPr(true, yoyEU));
        // nominal yield curve (interpolated; times assume year parts have 365 days)
        Real timesEUR[] = {0.0109589, 0.0684932, 0.263014, 0.317808, 0.567123, 0.816438,
               1.06575, 1.31507, 1.56438, 2.0137, 3.01918, 4.01644,
               5.01644, 6.01644, 7.01644, 8.01644, 9.02192, 10.0192,
               12.0192, 15.0247, 20.0301, 25.0356, 30.0329, 40.0384,
               50.0466};
        Real ratesEUR[] = {0.0415600, 0.0426840, 0.0470980, 0.0458506, 0.0449550, 0.0439784,
               0.0431887, 0.0426604, 0.0422925, 0.0424591, 0.0421477, 0.0421853,
               0.0424016, 0.0426969, 0.0430804, 0.0435011, 0.0439368, 0.0443825,
               0.0452589, 0.0463389, 0.0472636, 0.0473401, 0.0470629, 0.0461092,
               0.0450794};
        Real timesGBP[] = {0.008219178, 0.010958904, 0.01369863,  0.019178082,  0.073972603,
               0.323287671, 0.57260274,  0.821917808, 1.071232877,  1.320547945,
               1.506849315, 2.002739726, 3.002739726, 4.002739726,  5.005479452,
               6.010958904, 7.008219178, 8.005479452, 9.008219178, 10.00821918,
               12.01369863, 15.0109589,  20.01369863, 25.01917808,  30.02191781,
               40.03287671, 50.03561644, 60.04109589, 70.04931507};
        Real ratesGBP[] = {0.0577363, 0.0582314, 0.0585265, 0.0587165, 0.0596598,
               0.0612506, 0.0589676, 0.0570512, 0.0556147, 0.0546082,
               0.0549492, 0.053801, 0.0529333, 0.0524068, 0.0519712,
               0.0516615, 0.0513711, 0.0510433, 0.0507974, 0.0504833,
               0.0498998, 0.0490464, 0.04768, 0.0464862, 0.045452,
               0.0437699, 0.0425311, 0.0420073, 0.041151};
        vector <Real> r;
        vector <Date> d;
        Size nTimesEUR = LENGTH(timesEUR);
        Size nTimesGBP = LENGTH(timesGBP);
        for (Size i = 0; i < nTimesEUR; i++) {
            r.push_back(ratesEUR[i]);
            Size ys = (Size)floor(timesEUR[i]);
            Size ds = (Size)((timesEUR[i]-(Real)ys)*365);
            Date dd = eval + Period(ys,Years) + Period(ds,Days);
            d.push_back( dd );
        }
        boost::shared_ptr<InterpolatedZeroCurve<Cubic> >
            euriborTS(new InterpolatedZeroCurve<Cubic>(d, r, Actual365Fixed()));
        Handle<YieldTermStructure> nominalHeur(euriborTS, false);
        nominalEUR = nominalHeur;   // copy to global
        d.clear();
        r.clear();
        for (Size i = 0; i < nTimesGBP; i++) {
            r.push_back(ratesGBP[i]);
            Size ys = (Size)floor(timesGBP[i]);
            Size ds = (Size)((timesGBP[i]-(Real)ys)*365);
            Date dd = eval + Period(ys,Years) + Period(ds,Days);
            d.push_back( dd );
        }
        boost::shared_ptr<InterpolatedZeroCurve<Cubic> >
            gbpLiborTS(new InterpolatedZeroCurve<Cubic>(d, r, Actual365Fixed()));
        Handle<YieldTermStructure> nominalHgbp(gbpLiborTS, false);
        nominalGBP = nominalHgbp;   // copy to global
        // times = years - lag, where the lag is 2 months or 2/12
        // because this data is derived from cap/floor data that
        // is based on a 2 month lag.
        // note that these are NOT swap rates
        // also not that the first value MUST be in the base period
        // i.e. the first rate is for a negative time
        Real yoyEUrates[] = {0.0237951,
             0.0238749, 0.0240334, 0.0241934, 0.0243567, 0.0245323,
             0.0247213, 0.0249348, 0.0251768, 0.0254337, 0.0257258,
             0.0260217, 0.0263006, 0.0265538, 0.0267803, 0.0269378,
             0.0270608, 0.0271363, 0.0272, 0.0272512, 0.0272927,
             0.027317, 0.0273615, 0.0273811, 0.0274063, 0.0274307,
             0.0274625, 0.027527, 0.0275952, 0.0276734, 0.027794};
        d.clear();
        r.clear();
        Date baseDate = TARGET().advance(eval, -2, Months, ModifiedFollowing);
        for (Size i = 0; i < LENGTH(yoyEUrates); i++) {
            Date dd = TARGET().advance(baseDate, i, Years, ModifiedFollowing);
            d.push_back(dd);
            r.push_back(yoyEUrates[i]);
        }
        bool indexIsInterpolated = true;    // actually false for UKRPI but smooth surfaces are
                                            // better for finding intersections etc
        boost::shared_ptr<InterpolatedYoYInflationCurve<Linear> >
            pYTSEU( new InterpolatedYoYInflationCurve<Linear>(
                    eval, TARGET(), Actual365Fixed(), Period(2,Months), Monthly,
                    indexIsInterpolated, nominalGBP, d, r) );
        yoyEU.linkTo(pYTSEU);
        // price data
        const Size ncStrikesEU = 6;
        const Size nfStrikesEU = 6;
        const Size ncfMaturitiesEU = 7;
        Real capStrikesEU[ncStrikesEU] = {0.02, 0.025, 0.03, 0.035, 0.04, 0.05};
        Period capMaturitiesEU[ncfMaturitiesEU] = {3*Years, 5*Years, 7*Years,
            10*Years, 15*Years, 20*Years, 30*Years};
        Real capPricesEU[ncStrikesEU][ncfMaturitiesEU] =
            {{116.225, 204.945, 296.285, 434.29, 654.47, 844.775, 1132.33},
                {34.305, 71.575, 114.1, 184.33, 307.595, 421.395, 602.35},
                {6.37, 19.085, 35.635, 66.42, 127.69, 189.685, 296.195},
                {1.325, 5.745, 12.585, 26.945, 58.95, 94.08, 158.985},
                {0.501, 2.37, 5.38, 13.065, 31.91, 53.95, 96.97},
                {0.501, 0.695, 1.47, 4.415, 12.86, 23.75, 46.7}};
        Real floorStrikesEU[nfStrikesEU] = {-0.01, 0.00, 0.005, 0.01, 0.015, 0.02};
        Real floorPricesEU[nfStrikesEU][ncfMaturitiesEU] =
            {{0.501, 0.851, 2.44, 6.645, 16.23, 26.85, 46.365},
                {0.501, 2.236, 5.555, 13.075, 28.46, 44.525, 73.08},
                {1.025, 3.935, 9.095, 19.64, 39.93, 60.375, 96.02},
                {2.465, 7.885, 16.155, 31.6, 59.34, 86.21, 132.045},
                {6.9, 17.92, 32.085, 56.08, 95.95, 132.85, 194.18},
                {23.52, 47.625, 74.085, 114.355, 175.72, 229.565, 316.285}};
        // now load the data into vector and Matrix classes
        cStrikesEU.clear();
        fStrikesEU.clear();
        cfMaturitiesEU.clear();
        for(Size i = 0; i < ncStrikesEU; i++) cStrikesEU.push_back(capStrikesEU[i]);
        for(Size i = 0; i < nfStrikesEU; i++) fStrikesEU.push_back(floorStrikesEU[i]);
        for(Size i = 0; i < ncfMaturitiesEU; i++) cfMaturitiesEU.push_back(capMaturitiesEU[i]);
        boost::shared_ptr<Matrix> tcPriceEU(new Matrix(ncStrikesEU, ncfMaturitiesEU));
        boost::shared_ptr<Matrix> tfPriceEU(new Matrix(nfStrikesEU, ncfMaturitiesEU));
        for(Size i = 0; i < ncStrikesEU; i++) {
            for(Size j = 0; j < ncfMaturitiesEU; j++) {
                (*tcPriceEU)[i][j] = capPricesEU[i][j];
            }
        }
        for(Size i = 0; i < nfStrikesEU; i++) {
            for(Size j = 0; j < ncfMaturitiesEU; j++) {
                (*tfPriceEU)[i][j] = floorPricesEU[i][j];
            }
        }
        cPriceEU = tcPriceEU;   // copy to global
        fPriceEU = tfPriceEU;
    }
void anonymous_namespace{inflationvolatility.cpp}::setupPriceSurface ()
Definition at line 252 of file inflationvolatility.cpp.
References cfMaturitiesEU, cPriceEU, cStrikesEU, QuantLib::Handle< T >::currentLink(), fPriceEU, fStrikesEU, QuantLib::ModifiedFollowing, QuantLib::Months, nominalEUR, priceSurfEU, and yoyIndexEU.
Referenced by InflationVolTest::testYoYPriceSurfaceToATM(), and InflationVolTest::testYoYPriceSurfaceToVol().
{
        // construct:
        //  calendar, business day convention, and day counter are
        //  taken from the nominal base give the reference date for
        //  the inflation options (generally 2 or 3 months before
        //  nominal reference date)
        Natural fixingDays = 0;
        Size lag = 3;// must be 3 because we use an interpolated index (EU)
        Period yyLag = Period(lag,Months);
        Rate baseRate = 1; // not really used
        DayCounter dc = Actual365Fixed();
        TARGET cal;
        BusinessDayConvention bdc = ModifiedFollowing;
        boost::shared_ptr<QuantLib::YieldTermStructure> pn =
            nominalEUR.currentLink();
        Handle<QuantLib::YieldTermStructure> n(pn,false);
        boost::shared_ptr<InterpolatedYoYCapFloorTermPriceSurface<Bicubic,Cubic> >
        cfEUprices(new InterpolatedYoYCapFloorTermPriceSurface<Bicubic,Cubic>(
                                       fixingDays,
                                       yyLag, yoyIndexEU, baseRate,
                                       n, dc,
                                       cal,    bdc,
                                       cStrikesEU, fStrikesEU, cfMaturitiesEU,
                                       (*cPriceEU), (*fPriceEU)));
        priceSurfEU = cfEUprices;
    }
Variable Documentation
vector<Period> anonymous_namespace{inflationvolatility.cpp}::cfMaturitiesEU
Definition at line 68 of file inflationvolatility.cpp.
Referenced by reset(), setup(), and setupPriceSurface().
vector<Period> anonymous_namespace{inflationvolatility.cpp}::cfMaturitiesUK
Definition at line 77 of file inflationvolatility.cpp.
Referenced by anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::CommonVars(), and reset().
boost::shared_ptr<Matrix> anonymous_namespace{inflationvolatility.cpp}::cPriceEU
Definition at line 69 of file inflationvolatility.cpp.
Referenced by reset(), setup(), and setupPriceSurface().
boost::shared_ptr<Matrix> anonymous_namespace{inflationvolatility.cpp}::cPriceUK
Definition at line 78 of file inflationvolatility.cpp.
Referenced by anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::CommonVars(), and reset().
vector<Rate> anonymous_namespace{inflationvolatility.cpp}::cStrikesEU
Definition at line 66 of file inflationvolatility.cpp.
Referenced by reset(), setup(), and setupPriceSurface().
vector<Rate> anonymous_namespace{inflationvolatility.cpp}::cStrikesUK
Definition at line 75 of file inflationvolatility.cpp.
Referenced by anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::CommonVars(), and reset().
boost::shared_ptr<Matrix> anonymous_namespace{inflationvolatility.cpp}::fPriceEU
Definition at line 70 of file inflationvolatility.cpp.
Referenced by reset(), setup(), and setupPriceSurface().
boost::shared_ptr<Matrix> anonymous_namespace{inflationvolatility.cpp}::fPriceUK
Definition at line 79 of file inflationvolatility.cpp.
Referenced by anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::CommonVars(), and reset().
vector<Rate> anonymous_namespace{inflationvolatility.cpp}::fStrikesEU
Definition at line 67 of file inflationvolatility.cpp.
Referenced by reset(), setup(), and setupPriceSurface().
vector<Rate> anonymous_namespace{inflationvolatility.cpp}::fStrikesUK
Definition at line 76 of file inflationvolatility.cpp.
Referenced by anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::CommonVars(), and reset().
Handle<YieldTermStructure> anonymous_namespace{inflationvolatility.cpp}::nominalEUR
Definition at line 60 of file inflationvolatility.cpp.
Referenced by reset(), setup(), and setupPriceSurface().
Handle<YieldTermStructure> anonymous_namespace{inflationvolatility.cpp}::nominalGBP
Definition at line 61 of file inflationvolatility.cpp.
Referenced by reset(), and setup().
boost::shared_ptr<InterpolatedYoYCapFloorTermPriceSurface<Bicubic,Cubic> > anonymous_namespace{inflationvolatility.cpp}::priceSurfEU
Definition at line 81 of file inflationvolatility.cpp.
Referenced by reset(), setupPriceSurface(), InflationVolTest::testYoYPriceSurfaceToATM(), and InflationVolTest::testYoYPriceSurfaceToVol().
RelinkableHandle<YoYInflationTermStructure> anonymous_namespace{inflationvolatility.cpp}::yoyEU
Definition at line 63 of file inflationvolatility.cpp.
Referenced by reset(), and setup().
boost::shared_ptr<YoYInflationIndex> anonymous_namespace{inflationvolatility.cpp}::yoyIndexEU
Definition at line 73 of file inflationvolatility.cpp.
Referenced by reset(), setup(), setupPriceSurface(), and InflationVolTest::testYoYPriceSurfaceToVol().
boost::shared_ptr<YoYInflationIndex> anonymous_namespace{inflationvolatility.cpp}::yoyIndexUK
Definition at line 72 of file inflationvolatility.cpp.
Referenced by reset(), and setup().
RelinkableHandle<YoYInflationTermStructure> anonymous_namespace{inflationvolatility.cpp}::yoyUK
Definition at line 64 of file inflationvolatility.cpp.
Referenced by reset(), and setup().