QuantLib: anonymous_namespace{defaultprobabilitycurves.cpp} Namespace Reference
anonymous_namespace{defaultprobabilitycurves.cpp} Namespace Reference
Functions
template<class T , class I >
void testBootstrapFromSpread ()
template<class T , class I >
void testBootstrapFromUpfront ()
Function Documentation
template<class T , class I > void anonymous_namespace{defaultprobabilitycurves.cpp}::testBootstrapFromSpread ()
Definition at line 143 of file defaultprobabilitycurves.cpp.
References QuantLib::Calendar::adjust(), QuantLib::Protection::Buyer, anonymous_namespace{marketmodel.cpp}::calendar, anonymous_namespace{marketmodel.cpp}::dayCounter, anonymous_namespace{marketmodel.cpp}::endDate, QuantLib::Settings::evaluationDate(), QuantLib::CreditDefaultSwap::fairSpread(), QuantLib::Following, QuantLib::Settings::includeTodaysCashFlows(), QuantLib::Singleton< Settings >::instance(), QuantLib::RelinkableHandle< T >::linkTo(), QuantLib::Quarterly, QuantLib::io::rate(), QuantLib::Instrument::setPricingEngine(), anonymous_namespace{marketmodel.cpp}::startDate, anonymous_namespace{gaussianquadratures.cpp}::tolerance, QuantLib::DateGeneration::TwentiethIMM, QuantLib::Unadjusted, and QuantLib::Years.
{
        Calendar calendar = TARGET();
        Date today = Settings::instance().evaluationDate();
        Integer settlementDays = 1;
        std::vector<Real> quote;
        quote.push_back(0.005);
        quote.push_back(0.006);
        quote.push_back(0.007);
        quote.push_back(0.009);
        std::vector<Integer> n;
        n.push_back(1);
        n.push_back(2);
        n.push_back(3);
        n.push_back(5);
        Frequency frequency = Quarterly;
        BusinessDayConvention convention = Following;
        DateGeneration::Rule rule = DateGeneration::TwentiethIMM;
        DayCounter dayCounter = Thirty360();
        Real recoveryRate = 0.4;
        RelinkableHandle<YieldTermStructure> discountCurve;
        discountCurve.linkTo(boost::shared_ptr<YieldTermStructure>(
                                    new FlatForward(today,0.06,Actual360())));
        std::vector<boost::shared_ptr<DefaultProbabilityHelper> > helpers;
        for(Size i=0; i<n.size(); i++)
            helpers.push_back(
                boost::shared_ptr<DefaultProbabilityHelper>(
                    new SpreadCdsHelper(quote[i], Period(n[i], Years),
                                        settlementDays, calendar,
                                        frequency, convention, rule,
                                        dayCounter, recoveryRate,
                                        discountCurve)));
        RelinkableHandle<DefaultProbabilityTermStructure> piecewiseCurve;
        piecewiseCurve.linkTo(
            boost::shared_ptr<DefaultProbabilityTermStructure>(
                new PiecewiseDefaultCurve<T,I>(today, helpers,
                                               Thirty360())));
        Real notional = 1.0;
        double tolerance = 1.0e-6;
        // ensure apple-to-apple comparison
        SavedSettings backup;
        Settings::instance().includeTodaysCashFlows() = true;
        for (Size i=0; i<n.size(); i++) {
            Date protectionStart = today + settlementDays;
            Date startDate = calendar.adjust(protectionStart, convention);
            Date endDate = today + n[i]*Years;
            Schedule schedule(startDate, endDate, Period(frequency), calendar,
                              convention, Unadjusted, rule, false);
            CreditDefaultSwap cds(Protection::Buyer, notional, quote[i],
                                  schedule, convention, dayCounter,
                                  true, true, protectionStart);
            cds.setPricingEngine(boost::shared_ptr<PricingEngine>(
                           new MidPointCdsEngine(piecewiseCurve, recoveryRate,
                                                 discountCurve)));
            // test
            Rate inputRate = quote[i];
            Rate computedRate = cds.fairSpread();
            if (std::fabs(inputRate - computedRate) > tolerance)
                BOOST_ERROR(
                    "\nFailed to reproduce fair spread for " << n[i] <<
                    "Y credit-default swaps\n"
                    << std::setprecision(10)
                    << "    computed rate: " << io::rate(computedRate) << "\n"
                    << "    input rate:    " << io::rate(inputRate));
        }
    }
template<class T , class I > void anonymous_namespace{defaultprobabilitycurves.cpp}::testBootstrapFromUpfront ()
Definition at line 227 of file defaultprobabilitycurves.cpp.
References QuantLib::Calendar::adjust(), QuantLib::Protection::Buyer, anonymous_namespace{marketmodel.cpp}::calendar, anonymous_namespace{marketmodel.cpp}::dayCounter, anonymous_namespace{marketmodel.cpp}::endDate, QuantLib::Settings::evaluationDate(), QuantLib::CreditDefaultSwap::fairUpfront(), QuantLib::Following, QuantLib::Settings::includeTodaysCashFlows(), QuantLib::Singleton< Settings >::instance(), QuantLib::RelinkableHandle< T >::linkTo(), QuantLib::Quarterly, QuantLib::io::rate(), QuantLib::Instrument::setPricingEngine(), anonymous_namespace{marketmodel.cpp}::startDate, anonymous_namespace{gaussianquadratures.cpp}::tolerance, QuantLib::DateGeneration::TwentiethIMM, QuantLib::Unadjusted, and QuantLib::Years.
{
        Calendar calendar = TARGET();
        Date today = Settings::instance().evaluationDate();
        Integer settlementDays = 0;
        std::vector<Real> quote;
        quote.push_back(0.01);
        quote.push_back(0.02);
        quote.push_back(0.04);
        quote.push_back(0.06);
        std::vector<Integer> n;
        n.push_back(2);
        n.push_back(3);
        n.push_back(5);
        n.push_back(7);
        Rate fixedRate = 0.05;
        Frequency frequency = Quarterly;
        BusinessDayConvention convention = Following;
        DateGeneration::Rule rule = DateGeneration::TwentiethIMM;
        DayCounter dayCounter = Thirty360();
        Real recoveryRate = 0.4;
        RelinkableHandle<YieldTermStructure> discountCurve;
        discountCurve.linkTo(boost::shared_ptr<YieldTermStructure>(
                                    new FlatForward(today,0.06,Actual360())));
        std::vector<boost::shared_ptr<DefaultProbabilityHelper> > helpers;
        for(Size i=0; i<n.size(); i++)
            helpers.push_back(
                boost::shared_ptr<DefaultProbabilityHelper>(
                    new UpfrontCdsHelper(quote[i], fixedRate,
                                         Period(n[i], Years),
                                         settlementDays, calendar,
                                         frequency, convention, rule,
                                         dayCounter, recoveryRate,
                                         discountCurve)));
        RelinkableHandle<DefaultProbabilityTermStructure> piecewiseCurve;
        piecewiseCurve.linkTo(
            boost::shared_ptr<DefaultProbabilityTermStructure>(
                new PiecewiseDefaultCurve<T,I>(today, helpers,
                                               Thirty360())));
        Real notional = 1.0;
        double tolerance = 1.0e-6;
        SavedSettings backup;
        // ensure apple-to-apple comparison
        Settings::instance().includeTodaysCashFlows() = true;
        for (Size i=0; i<n.size(); i++) {
            Date protectionStart = today + settlementDays;
            Date startDate = calendar.adjust(protectionStart, convention);
            Date endDate = today + n[i]*Years;
            Schedule schedule(startDate, endDate, Period(frequency), calendar,
                              convention, Unadjusted, rule, false);
            CreditDefaultSwap cds(Protection::Buyer, notional,
                                  quote[i], fixedRate,
                                  schedule, convention, dayCounter,
                                  true, true, protectionStart);
            cds.setPricingEngine(boost::shared_ptr<PricingEngine>(
                           new MidPointCdsEngine(piecewiseCurve, recoveryRate,
                                                 discountCurve, true)));
            // test
            Rate inputUpfront = quote[i];
            Rate computedUpfront = cds.fairUpfront();
            if (std::fabs(inputUpfront - computedUpfront) > tolerance)
                BOOST_ERROR(
                    "\nFailed to reproduce fair upfront for " << n[i] <<
                    "Y credit-default swaps\n"
                    << std::setprecision(10)
                    << "    computed: " << io::rate(computedUpfront) << "\n"
                    << "    expected: " << io::rate(inputUpfront));
        }
    }