QuantLib: anonymous_namespace{marketmodel_cms.cpp} Namespace Reference
anonymous_namespace{marketmodel_cms.cpp} Namespace Reference
Enumerations
enum MarketModelType { ExponentialCorrelationFlatVolatility, ExponentialCorrelationAbcdVolatility }
enum MeasureType { ProductSuggested, Terminal, MoneyMarket, MoneyMarketPlus }
enum EvolverType { Ipc, Pc, NormalPc }
Functions
void setup ()
const boost::shared_ptr
< SequenceStatisticsInc > simulate (const boost::shared_ptr< MarketModelEvolver > &evolver, const MarketModelMultiProduct &product)
std::string marketModelTypeToString (MarketModelType type)
boost::shared_ptr< MarketModel > makeMarketModel (const EvolutionDescription &evolution, Size numberOfFactors, MarketModelType marketModelType, Spread rateBump=0.0, Volatility volBump=0.0)
std::string measureTypeToString (MeasureType type)
std::vector< Size > makeMeasure (const MarketModelMultiProduct &product, MeasureType measureType)
std::string evolverTypeToString (EvolverType type)
boost::shared_ptr
< MarketModelEvolver > makeMarketModelEvolver (const boost::shared_ptr< MarketModel > &marketModel, const std::vector< Size > &numeraires, const BrownianGeneratorFactory &generatorFactory, EvolverType evolverType, Size initialStep=0)
void checkCMSAndSwaptions (const SequenceStatisticsInc &stats, const Rate fixedRate, const std::vector< boost::shared_ptr< StrikedTypePayoff > > &displacedPayoff, const boost::shared_ptr< MarketModel >, const std::string &config)
Variables
Date todaysDate
Date startDate
Date endDate
std::vector< Time > rateTimes
std::vector< Real > accruals
Calendar calendar
DayCounter dayCounter
std::vector< Rate > todaysForwards
std::vector< Rate > todaysCMSwapRates
std::vector< Real > cMSwapAnnuity
Spread displacement
std::vector< DiscountFactor > todaysDiscounts
std::vector< Volatility > volatilities
std::vector< Volatility > blackVols
Real a
Real b
Real c
Real d
Real longTermCorrelation
Real beta
Size measureOffset_
unsigned long seed_
Size paths_
Size trainingPaths_
bool printReport_ = false
Size spanningForwards
Enumeration Type Documentation
enum anonymous_namespace{marketmodel_cms.cpp}::EvolverType
Enumerator:
Ipc
Pc
NormalPc
Definition at line 332 of file marketmodel_cms.cpp.
{ Ipc, Pc, NormalPc};
enum anonymous_namespace{marketmodel_cms.cpp}::MarketModelType
Enumerator:
ExponentialCorrelationFlatVolatility
ExponentialCorrelationAbcdVolatility
Definition at line 184 of file marketmodel_cms.cpp.
                         { ExponentialCorrelationFlatVolatility,
                           ExponentialCorrelationAbcdVolatility/*,
                           CalibratedMM*/
    };
enum anonymous_namespace{marketmodel_cms.cpp}::MeasureType
Enumerator:
ProductSuggested
Terminal
MoneyMarket
MoneyMarketPlus
Definition at line 267 of file marketmodel_cms.cpp.
                     { ProductSuggested, Terminal,
                       MoneyMarket, MoneyMarketPlus };
Function Documentation
void anonymous_namespace{marketmodel_cms.cpp}::checkCMSAndSwaptions (const SequenceStatisticsInc & stats, const Rate fixedRate, const std::vector< boost::shared_ptr< StrikedTypePayoff > > & displacedPayoff, const boost::shared_ptr< MarketModel > , const std::string & config)
Definition at line 366 of file marketmodel_cms.cpp.
References QuantLib::LMMCurveState::cmSwapAnnuity(), QuantLib::GenericSequenceStatistics< StatisticsType >::errorEstimate(), QuantLib::GenericSequenceStatistics< StatisticsType >::mean(), anonymous_namespace{matrices.cpp}::N, QuantLib::io::ordinal(), QuantLib::io::percent(), QL_MIN_REAL, QuantLib::io::rate(), and QuantLib::LMMCurveState::setOnForwardRates().
Referenced by MarketModelCmsTest::testMultiStepCmSwapsAndSwaptions().
{
        std::vector<Real> results = stats.mean();
        std::vector<Real> errors = stats.errorEstimate();
        std::vector<Real> discrepancies(todaysForwards.size());
        Size N = todaysForwards.size();
        // check Swaps
        Real maxError = QL_MIN_REAL;
        LMMCurveState curveState_lmm(rateTimes);
        curveState_lmm.setOnForwardRates(todaysForwards);
        std::vector<Real> expectedNPVs(todaysCMSwapRates.size());
        Real errorThreshold = 0.5;
        for (Size i=0; i<N; ++i) {
            Real expectedNPV = curveState_lmm.cmSwapAnnuity(i, i, spanningForwards)
                * (todaysCMSwapRates[i]-fixedRate) * todaysDiscounts[i];
            expectedNPVs[i] = expectedNPV;
            discrepancies[i] = (results[i]-expectedNPVs[i])/errors[i];
            maxError = std::max(std::fabs(discrepancies[i]), maxError);
        }
        if (maxError > errorThreshold) {
            BOOST_MESSAGE(config);
            for (Size i=0; i<N; ++i) {
                BOOST_MESSAGE(io::ordinal(i+1) << " CMS NPV: "
                              << io::rate(results[i])
                              << " +- " << io::rate(errors[i])
                              << "; expected: " << io::rate(expectedNPVs[i])
                              << "; discrepancy/error = "
                              << discrepancies[N-1-i]
                              << " standard errors");
            }
            BOOST_ERROR("test failed");
        }
        // check Swaptions
        maxError = 0;
        std::vector<Rate> expectedSwaptions(N);
        std::vector<Real> stdDevSwaptions(N);
        for (Size i=0; i<N; ++i) {
            Real expectedSwaption =
                BlackCalculator(displacedPayoff[i],
                                todaysCMSwapRates[i]+displacement,
                                volatilities[i]*std::sqrt(rateTimes[i]),
                                curveState_lmm.cmSwapAnnuity(i,i, spanningForwards)
                                * todaysDiscounts[i]).value();
            expectedSwaptions[i] = expectedSwaption;
            discrepancies[i] = (results[N+i]-expectedSwaptions[i])/errors[N+i];
            maxError = std::max(std::fabs(discrepancies[i]), maxError);
        }
        errorThreshold = 2.0;
        if (maxError > errorThreshold) {
            BOOST_MESSAGE(config);
            for (Size i=1; i<=N; ++i) {
                BOOST_MESSAGE(io::ordinal(i) << " Swaption: "
                              << io::rate(results[2*N-i])
                              << " +- " << io::rate(errors[2*N-i])
                              << "; expected: " << io::rate(expectedSwaptions[N-i])
                              << "; discrepancy/error = "
                              << io::percent(discrepancies[N-i])
                              << " standard errors");
            }
            BOOST_ERROR("test failed");
        }
    }
std::string anonymous_namespace{marketmodel_cms.cpp}::evolverTypeToString (EvolverType type)
Definition at line 334 of file marketmodel_cms.cpp.
References anonymous_namespace{marketmodel.cpp}::Ipc, anonymous_namespace{marketmodel.cpp}::NormalPc, anonymous_namespace{marketmodel.cpp}::Pc, and QL_FAIL.
{
        switch (type) {
          case Ipc:
            return "iterative predictor corrector";
          case Pc:
            return "predictor corrector";
          case NormalPc:
            return "predictor corrector for normal case";
          default:
            QL_FAIL("unknown MarketModelEvolver type");
        }
    }
boost::shared_ptr<MarketModel> anonymous_namespace{marketmodel_cms.cpp}::makeMarketModel (const EvolutionDescription & evolution, Size numberOfFactors, MarketModelType marketModelType, Spread rateBump = 0.0, Volatility volBump = 0.0)
Definition at line 202 of file marketmodel_cms.cpp.
References anonymous_namespace{marketmodel.cpp}::beta, anonymous_namespace{marketmodel.cpp}::displacement, anonymous_namespace{marketmodel.cpp}::ExponentialCorrelationAbcdVolatility, anonymous_namespace{marketmodel.cpp}::ExponentialCorrelationFlatVolatility, QuantLib::exponentialCorrelations(), anonymous_namespace{marketmodel.cpp}::longTermCorrelation, QuantLib::EvolutionDescription::numberOfRates(), QL_FAIL, and QuantLib::EvolutionDescription::rateTimes().
{
        std::vector<Time> fixingTimes(evolution.rateTimes());
        fixingTimes.pop_back();
        boost::shared_ptr<LmVolatilityModel> volModel(new
            LmExtLinearExponentialVolModel(fixingTimes, 0.5, 0.6, 0.1, 0.1));
        boost::shared_ptr<LmCorrelationModel> corrModel(new
            LmLinearExponentialCorrelationModel(evolution.numberOfRates(),
                                                longTermCorrelation, beta));
        std::vector<Rate> bumpedRates(todaysCMSwapRates.size());
        LMMCurveState curveState_lmm(rateTimes);
        curveState_lmm.setOnForwardRates(todaysForwards);
        std::vector<Rate> usedRates =
            curveState_lmm.cmSwapRates(spanningForwards);
        std::transform(usedRates.begin(), usedRates.end(),
                       bumpedRates.begin(),
                       std::bind1st(std::plus<Rate>(), rateBump));
        std::vector<Volatility> bumpedVols(volatilities.size());
        std::transform(volatilities.begin(), volatilities.end(),
                       bumpedVols.begin(),
                       std::bind1st(std::plus<Rate>(), volBump));
        Matrix correlations = exponentialCorrelations(evolution.rateTimes(),
                                                      longTermCorrelation,
                                                      beta);
        boost::shared_ptr<PiecewiseConstantCorrelation> corr(new
            TimeHomogeneousForwardCorrelation(correlations,
                                              evolution.rateTimes()));
        switch (marketModelType) {
          case ExponentialCorrelationFlatVolatility:
            return boost::shared_ptr<MarketModel>(new
                FlatVol(bumpedVols,
                               corr,
                               evolution,
                               numberOfFactors,
                               bumpedRates,
                               std::vector<Spread>(bumpedRates.size(),
                                                   displacement)));
          case ExponentialCorrelationAbcdVolatility:
            return boost::shared_ptr<MarketModel>(new
                AbcdVol(0.0,0.0,1.0,1.0,
                               bumpedVols,
                               corr,
                               evolution,
                               numberOfFactors,
                               bumpedRates,
                               std::vector<Spread>(bumpedRates.size(),
                                                   displacement)));
          //case CalibratedMM:
          //    return boost::shared_ptr<MarketModel>(new
          //        CalibratedMarketModel(volModel, corrModel,
          //                              evolution,
          //                              numberOfFactors,
          //                              bumpedForwards,
          //                              displacement));
          default:
            QL_FAIL("unknown MarketModel type");
        }
    }
boost::shared_ptr<MarketModelEvolver> anonymous_namespace{marketmodel_cms.cpp}::makeMarketModelEvolver (const boost::shared_ptr< MarketModel > & marketModel, const std::vector< Size > & numeraires, const BrownianGeneratorFactory & generatorFactory, EvolverType evolverType, Size initialStep = 0)
Definition at line 347 of file marketmodel_cms.cpp.
References anonymous_namespace{marketmodel.cpp}::Pc, and QL_FAIL.
{
        switch (evolverType) {
          case Pc:
            return boost::shared_ptr<MarketModelEvolver>(new
                LogNormalCmSwapRatePc(spanningForwards,
                                    marketModel, generatorFactory,
                                    numeraires,
                                    initialStep));
          default:
            QL_FAIL("unknown ConstantMaturitySwapMarketModelEvolver type");
        }
    }
std::vector<Size> anonymous_namespace{marketmodel_cms.cpp}::makeMeasure (const MarketModelMultiProduct & product, MeasureType measureType)
Definition at line 285 of file marketmodel_cms.cpp.
References anonymous_namespace{marketmodel.cpp}::a, QuantLib::checkCompatibility(), QuantLib::MarketModelMultiProduct::evolution(), QuantLib::isInMoneyMarketMeasure(), QuantLib::isInMoneyMarketPlusMeasure(), QuantLib::isInTerminalMeasure(), anonymous_namespace{marketmodel.cpp}::measureTypeToString(), anonymous_namespace{marketmodel.cpp}::MoneyMarket, QuantLib::moneyMarketMeasure(), anonymous_namespace{marketmodel.cpp}::MoneyMarketPlus, QuantLib::moneyMarketPlusMeasure(), anonymous_namespace{marketmodel.cpp}::ProductSuggested, QL_FAIL, QuantLib::MarketModelMultiProduct::suggestedNumeraires(), anonymous_namespace{marketmodel.cpp}::Terminal, and QuantLib::terminalMeasure().
{
        std::vector<Size> result;
        EvolutionDescription evolution(product.evolution());
        switch (measureType) {
          case ProductSuggested:
            result = product.suggestedNumeraires();
            break;
          case Terminal:
            result = terminalMeasure(evolution);
            if (!isInTerminalMeasure(evolution, result)) {
                Array a(result.size());
                std::copy(result.begin(), result.end(), a.begin());
                BOOST_ERROR("failure in verifying Terminal measure:\n" << a);
            }
            break;
          case MoneyMarket:
            result = moneyMarketMeasure(evolution);
            if (!isInMoneyMarketMeasure(evolution, result)) {
                Array a(result.size());
                std::copy(result.begin(), result.end(), a.begin());
                BOOST_ERROR("failure in verifying MoneyMarket measure:\n" << a);
            }
            break;
          case MoneyMarketPlus:
            result = moneyMarketPlusMeasure(evolution, measureOffset_);
            if (!isInMoneyMarketPlusMeasure(evolution, result,
                                            measureOffset_)) {
                Array a(result.size());
                std::copy(result.begin(), result.end(), a.begin());
                BOOST_ERROR("failure in verifying MoneyMarketPlus(" <<
                            measureOffset_ << ") measure:\n" << a);
            }
            break;
          default:
            QL_FAIL("unknown measure type");
        }
        checkCompatibility(evolution, result);
        if (printReport_) {
            Array num(result.size());
            std::copy(result.begin(), result.end(), num.begin());
            BOOST_MESSAGE("    " << measureTypeToString(measureType) << ": "
                          << num);
        }
        return result;
    }
std::string anonymous_namespace{marketmodel_cms.cpp}::marketModelTypeToString (MarketModelType type)
Definition at line 189 of file marketmodel_cms.cpp.
References anonymous_namespace{marketmodel.cpp}::ExponentialCorrelationAbcdVolatility, anonymous_namespace{marketmodel.cpp}::ExponentialCorrelationFlatVolatility, and QL_FAIL.
{
        switch (type) {
          case ExponentialCorrelationFlatVolatility:
            return "Exp. Corr. Flat Vol.";
          case ExponentialCorrelationAbcdVolatility:
            return "Exp. Corr. Abcd Vol.";
            //case CalibratedMM:
            //    return "CalibratedMarketModel";
          default:
            QL_FAIL("unknown MarketModelEvolver type");
        }
    }
std::string anonymous_namespace{marketmodel_cms.cpp}::measureTypeToString (MeasureType type)
Definition at line 270 of file marketmodel_cms.cpp.
References anonymous_namespace{marketmodel.cpp}::MoneyMarket, anonymous_namespace{marketmodel.cpp}::MoneyMarketPlus, anonymous_namespace{marketmodel.cpp}::ProductSuggested, QL_FAIL, and anonymous_namespace{marketmodel.cpp}::Terminal.
{
        switch (type) {
          case ProductSuggested:
            return "ProductSuggested measure";
          case Terminal:
            return "Terminal measure";
          case MoneyMarket:
            return "Money Market measure";
          case MoneyMarketPlus:
            return "Money Market Plus measure";
          default:
            QL_FAIL("unknown measure type");
        }
    }
void anonymous_namespace{marketmodel_cms.cpp}::setup ()
Definition at line 82 of file marketmodel_cms.cpp.
References QuantLib::DateGeneration::Backward, QuantLib::LMMCurveState::cmSwapRates(), anonymous_namespace{marketmodel.cpp}::dates, anonymous_namespace{marketmodel.cpp}::displacement, QuantLib::Settings::evaluationDate(), QuantLib::Following, QuantLib::Singleton< Settings >::instance(), QuantLib::Semiannual, QuantLib::LMMCurveState::setOnForwardRates(), QuantLib::Schedule::size(), and QuantLib::Years.
                 {
        // Times
        calendar = NullCalendar();
        todaysDate = Settings::instance().evaluationDate();
        //startDate = todaysDate + 5*Years;
        endDate = todaysDate + 10*Years;
        Schedule dates(todaysDate, endDate, Period(Semiannual),
                       calendar, Following, Following,
                       DateGeneration::Backward, false);
        rateTimes = std::vector<Time>(dates.size()-1);
        accruals = std::vector<Real>(rateTimes.size()-1);
        dayCounter = SimpleDayCounter();
        for (Size i=1; i<dates.size(); ++i)
            rateTimes[i-1] = dayCounter.yearFraction(todaysDate, dates[i]);
        for (Size i=1; i<rateTimes.size(); ++i)
            accruals[i-1] = rateTimes[i] - rateTimes[i-1];
        // Rates & displacement
        todaysForwards = std::vector<Rate>(accruals.size());
        displacement = 0.02;
        for (Size i=0; i<todaysForwards.size(); ++i)
            todaysForwards[i] = 0.03 + 0.0010*i;
        LMMCurveState curveState_lmm(rateTimes);
        curveState_lmm.setOnForwardRates(todaysForwards);
        // until ConstantMaturitySwap is ready
        spanningForwards = todaysForwards.size();
        todaysCMSwapRates = curveState_lmm.cmSwapRates(spanningForwards);
        // Discounts
        todaysDiscounts = std::vector<DiscountFactor>(rateTimes.size());
        todaysDiscounts[0] = 0.95;
        for (Size i=1; i<rateTimes.size(); ++i)
            todaysDiscounts[i] = todaysDiscounts[i-1] /
                (1.0+todaysForwards[i-1]*accruals[i-1]);
        // Swaption Volatilities
        Volatility mktVols[] = {0.15541283,
                                0.18719678,
                                0.20890740,
                                0.22318179,
                                0.23212717,
                                0.23731450,
                                0.23988649,
                                0.24066384,
                                0.24023111,
                                0.23900189,
                                0.23726699,
                                0.23522952,
                                0.23303022,
                                0.23076564,
                                0.22850101,
                                0.22627951,
                                0.22412881,
                                0.22206569,
                                0.22009939
        };
        a = -0.0597;
        b =  0.1677;
        c =  0.5403;
        d =  0.1710;
        volatilities = std::vector<Volatility>(todaysCMSwapRates.size());
        blackVols = std::vector<Volatility>(todaysCMSwapRates.size());
        for (Size i=0; i<todaysCMSwapRates.size(); i++) {
            volatilities[i] = todaysCMSwapRates[i]*mktVols[i]/
                (todaysCMSwapRates[i]+displacement);
            blackVols[i]= mktVols[i];
        }
        // Cap/Floor Correlation
        longTermCorrelation = 0.5;
        beta = 0.2;
        measureOffset_ = 5;
        // Monte Carlo
        seed_ = 42;
        #ifdef _DEBUG
        paths_ = 127;
        trainingPaths_ = 31;
        #else
        paths_ = 32767; //262144-1; //; // 2^15-1
        trainingPaths_ = 8191; // 2^13-1
        #endif
    }
const boost::shared_ptr<SequenceStatisticsInc> anonymous_namespace{marketmodel_cms.cpp}::simulate (const boost::shared_ptr< MarketModelEvolver > & evolver, const MarketModelMultiProduct & product)
Definition at line 170 of file marketmodel_cms.cpp.
References QuantLib::AccountingEngine::multiplePathValues(), and QuantLib::MarketModelMultiProduct::numberOfProducts().
{
        Size initialNumeraire = evolver->numeraires().front();
        Real initialNumeraireValue = todaysDiscounts[initialNumeraire];
        AccountingEngine engine(evolver, product, initialNumeraireValue);
        boost::shared_ptr<SequenceStatisticsInc> stats(
                          new SequenceStatisticsInc(product.numberOfProducts()));
        engine.multiplePathValues(*stats, paths_);
        return stats;
    }
Variable Documentation
Real anonymous_namespace{marketmodel_cms.cpp}::a
Definition at line 74 of file marketmodel_cms.cpp.
std::vector<Real> anonymous_namespace{marketmodel_cms.cpp}::accruals
Definition at line 66 of file marketmodel_cms.cpp.
Real anonymous_namespace{marketmodel_cms.cpp}::b
Definition at line 74 of file marketmodel_cms.cpp.
Real anonymous_namespace{marketmodel_cms.cpp}::beta
Definition at line 75 of file marketmodel_cms.cpp.
std::vector<Volatility> anonymous_namespace{marketmodel_cms.cpp}::blackVols
Definition at line 73 of file marketmodel_cms.cpp.
Real anonymous_namespace{marketmodel_cms.cpp}::c
Definition at line 74 of file marketmodel_cms.cpp.
Calendar anonymous_namespace{marketmodel_cms.cpp}::calendar
Definition at line 67 of file marketmodel_cms.cpp.
std::vector<Real> anonymous_namespace{marketmodel_cms.cpp}::cMSwapAnnuity
Definition at line 70 of file marketmodel_cms.cpp.
Real anonymous_namespace{marketmodel_cms.cpp}::d
Definition at line 74 of file marketmodel_cms.cpp.
DayCounter anonymous_namespace{marketmodel_cms.cpp}::dayCounter
Definition at line 68 of file marketmodel_cms.cpp.
Spread anonymous_namespace{marketmodel_cms.cpp}::displacement
Definition at line 71 of file marketmodel_cms.cpp.
Date anonymous_namespace{marketmodel_cms.cpp}::endDate
Definition at line 64 of file marketmodel_cms.cpp.
Real anonymous_namespace{marketmodel_cms.cpp}::longTermCorrelation
Definition at line 75 of file marketmodel_cms.cpp.
Size anonymous_namespace{marketmodel_cms.cpp}::measureOffset_
Definition at line 76 of file marketmodel_cms.cpp.
Size anonymous_namespace{marketmodel_cms.cpp}::paths_
Definition at line 78 of file marketmodel_cms.cpp.
bool anonymous_namespace{marketmodel_cms.cpp}::printReport_ = false
Definition at line 79 of file marketmodel_cms.cpp.
std::vector<Time> anonymous_namespace{marketmodel_cms.cpp}::rateTimes
Definition at line 65 of file marketmodel_cms.cpp.
unsigned long anonymous_namespace{marketmodel_cms.cpp}::seed_
Definition at line 77 of file marketmodel_cms.cpp.
Size anonymous_namespace{marketmodel_cms.cpp}::spanningForwards
Definition at line 80 of file marketmodel_cms.cpp.
Referenced by QuantLib::LogNormalCmSwapRatePc::LogNormalCmSwapRatePc(), and SwapForwardMappingsTest::testForwardSwapJacobians().
Date anonymous_namespace{marketmodel_cms.cpp}::startDate
Definition at line 64 of file marketmodel_cms.cpp.
std::vector<Rate> anonymous_namespace{marketmodel_cms.cpp}::todaysCMSwapRates
Definition at line 69 of file marketmodel_cms.cpp.
Date anonymous_namespace{marketmodel_cms.cpp}::todaysDate
Definition at line 64 of file marketmodel_cms.cpp.
std::vector<DiscountFactor> anonymous_namespace{marketmodel_cms.cpp}::todaysDiscounts
Definition at line 72 of file marketmodel_cms.cpp.
std::vector<Rate> anonymous_namespace{marketmodel_cms.cpp}::todaysForwards
Definition at line 69 of file marketmodel_cms.cpp.
Size anonymous_namespace{marketmodel_cms.cpp}::trainingPaths_
Definition at line 78 of file marketmodel_cms.cpp.
std::vector<Volatility> anonymous_namespace{marketmodel_cms.cpp}::volatilities
Definition at line 73 of file marketmodel_cms.cpp.