QuantLib: QuantLib Namespace Reference
QuantLib Namespace Reference
Namespaces
namespace anonymous_namespace{alphafinder.cpp}
namespace anonymous_namespace{amortizingfixedratebond.cpp}
namespace anonymous_namespace{analyticbsmhullwhiteengine.cpp}
namespace anonymous_namespace{analyticgjrgarchengine.cpp}
namespace anonymous_namespace{analyticvariancegammaengine.cpp}
namespace anonymous_namespace{averagebmacoupon.cpp}
namespace anonymous_namespace{basisincompleteordered.cpp}
namespace anonymous_namespace{bivariatenormaldistribution.cpp}
namespace anonymous_namespace{bjerksundstenslandengine.cpp}
namespace anonymous_namespace{bmaindex.cpp}
namespace anonymous_namespace{bondhelpers.cpp}
namespace anonymous_namespace{business252.cpp}
namespace anonymous_namespace{capfloor.cpp}
namespace anonymous_namespace{capletcoterminalmaxhomogeneity.cpp}
namespace anonymous_namespace{cashflows.cpp}
namespace anonymous_namespace{cdsoption.cpp}
namespace anonymous_namespace{conundrumpricer.cpp}
namespace anonymous_namespace{couponpricer.cpp}
namespace anonymous_namespace{creditdefaultswap.cpp}
namespace anonymous_namespace{defaultdensitystructure.cpp}
namespace anonymous_namespace{defaultprobabilityhelpers.cpp}
namespace anonymous_namespace{discretizedcallablefixedratebond.cpp}
namespace anonymous_namespace{discretizedswaption.cpp}
namespace anonymous_namespace{euribor.cpp}
namespace anonymous_namespace{eurlibor.cpp}
namespace anonymous_namespace{exchangeratemanager.cpp}
namespace anonymous_namespace{factorial.cpp}
namespace anonymous_namespace{fdsimpleextoustorageengine.cpp}
namespace anonymous_namespace{fdsimpleklugeextouvppengine.cpp}
namespace anonymous_namespace{generalizedhullwhite.cpp}
namespace anonymous_namespace{hazardratestructure.cpp}
namespace anonymous_namespace{histogram.cpp}
namespace anonymous_namespace{impliedvolatility.cpp}
namespace anonymous_namespace{inflationhelpers.cpp}
namespace anonymous_namespace{integralengine.cpp}
namespace anonymous_namespace{issuer.cpp}
namespace anonymous_namespace{latticerules.cpp}
namespace anonymous_namespace{libor.cpp}
namespace anonymous_namespace{lsmbasissystem.cpp}
namespace anonymous_namespace{model.cpp}
namespace anonymous_namespace{money.cpp}
namespace anonymous_namespace{oisratehelper.cpp}
namespace anonymous_namespace{overnightindexedcoupon.cpp}
namespace anonymous_namespace{parametricexercise.cpp}
namespace anonymous_namespace{period.cpp}
namespace anonymous_namespace{perturbativebarrieroptionengine.cpp}
namespace anonymous_namespace{primenumbers.cpp}
namespace anonymous_namespace{pseudosqrt.cpp}
namespace anonymous_namespace{quantity.cpp}
namespace anonymous_namespace{randomdefaultmodel.cpp}
namespace anonymous_namespace{ratehelpers.cpp}
namespace anonymous_namespace{richardsonextrapolation.cpp}
namespace anonymous_namespace{riskyassetswap.cpp}
namespace anonymous_namespace{schedule.cpp}
namespace anonymous_namespace{simpledaycounter.cpp}
namespace anonymous_namespace{simplex.cpp}
namespace anonymous_namespace{sobolbrowniangenerator.cpp}
namespace anonymous_namespace{sobolrsg.cpp}
namespace anonymous_namespace{spherecylinder.cpp}
namespace anonymous_namespace{stulzengine.cpp}
namespace anonymous_namespace{svd.cpp}
namespace anonymous_namespace{swaption.cpp}
namespace anonymous_namespace{swaptionpseudojacobian.cpp}
namespace anonymous_namespace{unitofmeasureconversionmanager.cpp}
namespace anonymous_namespace{upperboundengine.cpp}
namespace anonymous_namespace{vanillaswingoption.cpp}
namespace anonymous_namespace{vanillavppoption.cpp}
namespace anonymous_namespace{yieldtermstructure.cpp}
namespace anonymous_namespace{yoyoptionlethelpers.cpp}
namespace anonymous_namespace{zigguratrng.cpp}
namespace detail
namespace details
namespace dsd
namespace ForwardForwardMappings
namespace io
namespace MINPACK
Classes
class CashFlow
Base class for cash flows.
struct earlier_than< CashFlow >
class AverageBMACoupon
Average BMA coupon.
class AverageBMALeg
helper class building a sequence of average BMA coupons
class CappedFlooredCoupon
Capped and/or floored floating-rate coupon.
class CappedFlooredIborCoupon
class CappedFlooredCmsCoupon
class CappedFlooredYoYInflationCoupon
Capped or floored inflation coupon.
class CashFlows
cashflow-analysis functions
class CmsCoupon
CMS coupon class.
class CmsLeg
helper class building a sequence of capped/floored cms-rate coupons
class VanillaOptionPricer
class BlackVanillaOptionPricer
class GFunction
class GFunctionFactory
class HaganPricer
CMS-coupon pricer.
class NumericHaganPricer
CMS-coupon pricer.
class AnalyticHaganPricer
CMS-coupon pricer.
class Coupon
coupon accruing over a fixed period
class FloatingRateCouponPricer
generic pricer for floating-rate coupons
class IborCouponPricer
base pricer for capped/floored Ibor coupons
class BlackIborCouponPricer
Black-formula pricer for capped/floored Ibor coupons.
class CmsCouponPricer
base pricer for vanilla CMS coupons
struct CPI
class CPICoupon
Coupon paying the performance of a CPI (zero inflation) index
class CPICashFlow
Cash flow paying the performance of a CPI (zero inflation) index.
class CPILeg
Helper class building a sequence of capped/floored CPI coupons.
class CPICouponPricer
base pricer for capped/floored CPI coupons N.B. vol-dependent parts are a TODO
class DigitalCmsCoupon
Cms-rate coupon with digital digital call/put option.
class DigitalCmsLeg
helper class building a sequence of digital ibor-rate coupons
class DigitalCoupon
Digital-payoff coupon.
class DigitalIborCoupon
Ibor rate coupon with digital digital call/put option.
class DigitalIborLeg
helper class building a sequence of digital ibor-rate coupons
class Dividend
Predetermined cash flow.
class FixedDividend
Predetermined cash flow.
class FractionalDividend
Predetermined cash flow.
struct Duration
duration type
class FixedRateCoupon
Coupon paying a fixed interest rate
class FixedRateLeg
helper class building a sequence of fixed rate coupons
class FloatingRateCoupon
base floating-rate coupon class
class IborCoupon
Coupon paying a Libor-type index
class IborLeg
helper class building a sequence of capped/floored ibor-rate coupons
class IndexedCashFlow
Cash flow dependent on an index ratio.
class InflationCoupon
Base inflation-coupon class.
class InflationCouponPricer
Base inflation-coupon pricer.
class YoYInflationCouponPricer
base pricer for capped/floored YoY inflation coupons
class BlackYoYInflationCouponPricer
Black-formula pricer for capped/floored yoy inflation coupons.
class UnitDisplacedBlackYoYInflationCouponPricer
Unit-Displaced-Black-formula pricer for capped/floored yoy inflation coupons.
class BachelierYoYInflationCouponPricer
Bachelier-formula pricer for capped/floored yoy inflation coupons.
class OvernightIndexedCoupon
overnight coupon
class OvernightLeg
helper class building a sequence of overnight coupons
class RangeAccrualFloatersCoupon
class RangeAccrualPricer
class RangeAccrualPricerByBgm
class RangeAccrualLeg
helper class building a sequence of range-accrual floating-rate coupons
struct Replication
Digital option replication strategy.
class DigitalReplication
class SimpleCashFlow
Predetermined cash flow.
class Redemption
Bond redemption.
class AmortizingPayment
Amortizing payment.
class TimeBasket
Distribution over a number of dates.
class YoYInflationCoupon
Coupon paying a YoY-inflation type index
class yoyInflationLeg
class ZARCurrency
South-African rand.
class ARSCurrency
Argentinian peso.
class BRLCurrency
Brazilian real.
class CADCurrency
Canadian dollar.
class CLPCurrency
Chilean peso.
class COPCurrency
Colombian peso.
class MXNCurrency
Mexican peso.
class PENCurrency
Peruvian nuevo sol.
class PEICurrency
Peruvian inti.
class PEHCurrency
Peruvian sol.
class TTDCurrency
Trinidad & Tobago dollar.
class USDCurrency
U.S. dollar.
class VEBCurrency
Venezuelan bolivar.
class BDTCurrency
Bangladesh taka.
class CNYCurrency
Chinese yuan.
class HKDCurrency
Honk Kong dollar.
class ILSCurrency
Israeli shekel.
class INRCurrency
Indian rupee.
class IQDCurrency
Iraqi dinar.
class IRRCurrency
Iranian rial.
class JPYCurrency
Japanese yen.
class KRWCurrency
South-Korean won.
class KWDCurrency
Kuwaiti dinar.
class NPRCurrency
Nepal rupee.
class PKRCurrency
Pakistani rupee.
class SARCurrency
Saudi riyal.
class SGDCurrency
Singapore dollar
class THBCurrency
Thai baht.
class TWDCurrency
Taiwan dollar
class BGLCurrency
Bulgarian lev.
class BYRCurrency
Belarussian ruble.
class CHFCurrency
Swiss franc.
class CYPCurrency
Cyprus pound.
class CZKCurrency
Czech koruna.
class DKKCurrency
Danish krone.
class EEKCurrency
Estonian kroon.
class EURCurrency
European Euro.
class GBPCurrency
British pound sterling.
class HUFCurrency
Hungarian forint.
class ISKCurrency
Icelandic krona.
class LTLCurrency
Lithuanian litas.
class LVLCurrency
Latvian lat.
class MTLCurrency
Maltese lira.
class NOKCurrency
Norwegian krone.
class PLNCurrency
Polish zloty.
class ROLCurrency
Romanian leu.
class RONCurrency
Romanian new leu.
class SEKCurrency
Swedish krona.
class SITCurrency
Slovenian tolar.
class SKKCurrency
Slovak koruna.
class TRLCurrency
Turkish lira.
class TRYCurrency
New Turkish lira.
class ATSCurrency
Austrian shilling.
class BEFCurrency
Belgian franc.
class DEMCurrency
Deutsche mark.
class ESPCurrency
Spanish peseta.
class FIMCurrency
Finnish markka.
class FRFCurrency
French franc.
class GRDCurrency
Greek drachma.
class IEPCurrency
Irish punt.
class ITLCurrency
Italian lira.
class LUFCurrency
Luxembourg franc.
class NLGCurrency
Dutch guilder.
class PTECurrency
Portuguese escudo.
class ExchangeRateManager
exchange-rate repository
class AUDCurrency
Australian dollar.
class NZDCurrency
New Zealand dollar.
class Currency
Currency specification
struct Protection
information on a default-protection contract
class DiscretizedAsset
Discretized asset class used by numerical methods.
class DiscretizedDiscountBond
Useful discretized discount bond asset.
class DiscretizedOption
Discretized option on a given asset.
class Error
Base error class.
class Event
Base class for event.
class ExchangeRate
exchange rate between two currencies
class Exercise
Base exercise class.
class EarlyExercise
Early-exercise base class.
class AmericanExercise
American exercise.
class BermudanExercise
Bermudan exercise.
class EuropeanExercise
European exercise.
class AmortizingCmsRateBond
amortizing CMS-rate bond
class AmortizingFixedRateBond
amortizing fixed-rate bond
class AmortizingFloatingRateBond
amortizing floating-rate bond (possibly capped and/or floored)
class PerturbativeBarrierOptionEngine
perturbative barrier-option engine
class BlackCallableFixedRateBondEngine
Black-formula callable fixed rate bond engine.
class BlackCallableZeroCouponBondEngine
Black-formula callable zero coupon bond engine.
class CallableBond
Callable bond base class.
class CallableFixedRateBond
callable/puttable fixed rate bond
class CallableZeroCouponBond
callable/puttable zero coupon bond
class CallableBondConstantVolatility
Constant callable-bond volatility, no time-strike dependence.
class CallableBondVolatilityStructure
Callable-bond volatility structure.
class DiscretizedCallableFixedRateBond
class TreeCallableFixedRateBondEngine
Numerical lattice engine for callable fixed rate bonds.
class TreeCallableZeroCouponBondEngine
Numerical lattice engine for callable zero coupon bonds.
struct PricingError
class Commodity
Commodity base class.
class CommodityCashFlow
class CommodityCurve
Commodity term structure.
class CommodityIndex
base class for commodity indexes
class CommodityPricingHelper
commodity index helper
class CommoditySettings
global repository for run-time library settings
class CommodityType
commodity type
class NullCommodityType
class CommodityUnitCost
class DateInterval
Date interval described by a number of a given time unit.
class EnergyBasisSwap
Energy basis swap.
struct EnergyDailyPosition
class EnergyCommodity
Energy commodity class.
class EnergyFuture
Energy future.
class EnergySwap
class EnergyVanillaSwap
Vanilla energy swap.
class ExchangeContract
class PaymentTerm
class BarrelUnitOfMeasure
class MTUnitOfMeasure
class MBUnitOfMeasure
class GallonUnitOfMeasure
class LitreUnitOfMeasure
class KilolitreUnitOfMeasure
class TokyoKilolitreUnitOfMeasure
class PricingPeriod
Time pricingperiod described by a number of a given time unit.
class Quantity
Amount of a commodity.
class UnitOfMeasure
Unit of measure specification
class LotUnitOfMeasure
class UnitOfMeasureConversion
class UnitOfMeasureConversionManager
repository of conversion factors between units of measure
class AnalyticCompoundOptionEngine
Pricing engine for compound options using analytical formulae.
class ImpliedSpotHelper
class CompoundOption
Compound option on a single asset.
class BinomialConvertibleEngine
Binomial Tsiveriotis-Fernandes engine for convertible bonds.
class SoftCallability
callability leaving to the holder the possibility to convert
class ConvertibleBond
base class for convertible bonds
class ConvertibleZeroCouponBond
convertible zero-coupon bond
class ConvertibleFixedCouponBond
convertible fixed-coupon bond
class ConvertibleFloatingRateBond
convertible floating-rate bond
class DiscretizedConvertible
class TsiveriotisFernandesLattice
Binomial lattice approximating the Tsiveriotis-Fernandes model.
class ProxyIbor
IborIndex calculated as proxy of some other IborIndex.
class BlackIborQuantoCouponPricer
class SubPeriodsCoupon
class SubPeriodsPricer
class AveragingRatePricer
class CompoundingRatePricer
class Basket
class BlackCdsOptionEngine
Black-formula CDS-option engine.
class CDO
collateralized debt obligation
class CdsOption
CDS option.
class DefaultEvent
Credit event on a bond of a certain seniority(ies)/currency.
struct earlier_than< DefaultEvent >
class FailureToPayEvent
class BankruptcyEvent
class DefaultProbKey
class NorthAmericaCorpDefaultKey
ISDA standard default contractual key for corporate US debt.
struct AtomicDefault
Atomic (single contractual event) default events.
struct Restructuring
Restructuring type.
class DefaultType
Atomic credit-event type.
class FailureToPay
Failure to Pay atomic event type.
class Distribution
class ManipulateDistribution
class FactorSpreadedHazardRateCurve
Default-probability structure with a multiplicative spread on hazard rates.
class Issuer
class Loss
class LossDist
Probability formulas and algorithms.
class ProbabilityOfNEvents
Probability of N events.
class ProbabilityOfAtLeastNEvents
Probability of at least N events.
class BinomialProbabilityOfAtLeastNEvents
Probability of at least N events.
class LossDistBinomial
Binomial loss distribution.
class LossDistHomogeneous
Loss Distribution for Homogeneous Pool.
class LossDistBucketing
Loss distribution with Hull-White bucketing.
class LossDistMonteCarlo
Loss distribution with Monte Carlo simulation.
class NthToDefault
N-th to default swap.
class OneFactorCopula
Abstract base class for one-factor copula models.
class OneFactorGaussianCopula
One-factor Gaussian Copula.
class OneFactorStudentCopula
One-factor Double Student t-Copula.
class OneFactorGaussianStudentCopula
One-factor Gaussian-Student t-Copula.
class OneFactorStudentGaussianCopula
One-factor Student t - Gaussian Copula.
class Pool
class RandomDefaultModel
Base class for random default models.
class GaussianRandomDefaultModel
class RecoveryRateModel
class ConstantRecoveryModel
class RecoveryRateQuote
Stores a recovery rate market quote and the associated seniority.
class RecursiveCdoEngine
class GaussianRecursiveCdoEngine
Specialization for Gaussian copula, the integration still remains.
class StudentRecursiveCdoEngine
class RiskyAssetSwap
Risky asset-swap instrument.
class AssetSwapHelper
class RiskyAssetSwapOption
Option on risky asset swap
class RiskyBond
class RiskyFixedBond
class RiskyFloatingBond
class SpreadedHazardRateCurve
Default-probability structure with an additive spread on hazard rates.
class SyntheticCDO
Synthetic Collateralized Debt Obligation.
class MidPointCDOEngine
CDO base engine taking schedule steps.
class IntegralCDOEngine
CDO base engine taking (possibly) small time steps.
class MonteCarloCDOEngine1
CDO engine, Monte Carlo for the exptected tranche loss distribution.
class MonteCarloCDOEngine2
CDO engine, Monte Carlo for the sample payoff.
class HomogeneousPoolCDOEngine
CDO engine, loss distribution convolution for finite homogeneous pool.
class InhomogeneousPoolCDOEngine
CDO engine, loss disctribution bucketing for finite inhomogeneous pool.
class GaussianLHPCDOEngine
class AnalyticAmericanMargrabeEngine
Analytic engine for American Margrabe option.
class AnalyticEuropeanMargrabeEngine
Analytic engine for European Margrabe option.
class AnalyticSimpleChooserEngine
Pricing engine for European Simple Chooser option.
class AnalyticWriterExtensibleOptionEngine
Analytic engine for writer-extensible options.
class ContinuousArithmeticAsianLevyEngine
class EverestOption
class HimalayaOption
Himalaya option.
class KirkSpreadOptionEngine
Kirk approximation for European spread option on futures.
class MargrabeOption
Margrabe option on two assets.
class MCEverestEngine
class MakeMCEverestEngine
Monte Carlo Everest-option engine factory.
class EverestMultiPathPricer
class MCHimalayaEngine
class MakeMCHimalayaEngine
Monte Carlo Himalaya-option engine factory.
class HimalayaMultiPathPricer
class MCPagodaEngine
Pricing engine for pagoda options using Monte Carlo simulation.
class MakeMCPagodaEngine
Monte Carlo pagoda-option engine factory.
class PagodaMultiPathPricer
class PagodaOption
Roofed Asian option on a number of assets.
class SimpleChooserOption
Simple chooser option.
class SpreadOption
Spread option on two assets.
class WriterExtensibleOption
Writer-extensible option.
class FdExtOUJumpVanillaEngine
class FdKlugeExtOUSpreadEngine
class FdmExpExtOUInnerValueCalculator
class FdmExtendedOrnsteinUhlenbackOp
class FdmExtOUJumpModelInnerValue
class FdmExtOUJumpOp
class FdmExtOUJumpSolver
class FdmKlugeExtOUOp
class FdmKlugeExtOUSolver
class FdmSimple2dExtOUSolver
class FdmSimple3dExtOUJumpSolver
class FdmSpreadPayoffInnerValue
class FdmVPPStepCondition
class FdSimpleExtOUJumpSwingEngine
class FdSimpleExtOUStorageEngine
class FdSimpleKlugeExtOUVPPEngine
class Glued1dMesher
class VanillaVPPOption
class BlackDeltaCalculator
Black delta calculator class.
class BlackDeltaPremiumAdjustedSolverClass
class BlackDeltaPremiumAdjustedMaxStrikeClass
class DeltaVolQuote
Class for the quotation of delta vs vol.
class InterpolatingCPICapFloorEngine
class CPICapFloorTermPriceSurface
Provides cpi cap/floor prices by interpolation and put/call parity (not cap/floor/swap* parity).
class InterpolatedCPICapFloorTermPriceSurface
class GenericRegion
Generic geographical/economic region.
class GenericCPI
Generic CPI index.
class YYGenericCPI
Genuine year-on-year Generic CPI (i.e. not a ratio)
class YYGenericCPIr
Fake year-on-year GenericCPI (i.e. a ratio)
class InterpolatedYoYOptionletStripper
class KInterpolatedYoYOptionletVolatilitySurface
K-interpolated YoY optionlet volatility.
class YoYInflationVolatilityTraits
traits for inflation-volatility bootstrap
class PiecewiseYoYOptionletVolatilityCurve
Piecewise year-on-year inflation volatility term structure.
class Polynomial2DSpline
polynomial2D-spline interpolation between discrete points
class Polynomial
polynomial2D-spline-interpolation factory
class YoYCapFloorTermPriceSurface
Abstract base class, inheriting from InflationTermStructure.
class InterpolatedYoYCapFloorTermPriceSurface
class InterpolatedYoYOptionletVolatilityCurve
Interpolated flat smile surface.
class YoYOptionletHelper
Year-on-year inflation-volatility bootstrap helper.
class YoYOptionletStripper
Interface for inflation cap stripping, i.e. from price surfaces.
class ExtendedBinomialTree
Binomial tree base class.
class ExtendedEqualProbabilitiesBinomialTree
Base class for equal probabilities binomial tree.
class ExtendedEqualJumpsBinomialTree
Base class for equal jumps binomial tree.
class ExtendedJarrowRudd
Jarrow-Rudd (multiplicative) equal probabilities binomial tree.
class ExtendedCoxRossRubinstein
Cox-Ross-Rubinstein (multiplicative) equal jumps binomial tree.
class ExtendedAdditiveEQPBinomialTree
Additive equal probabilities binomial tree.
class ExtendedTrigeorgis
Trigeorgis (additive equal jumps) binomial tree
class ExtendedTian
Tian tree: third moment matching, multiplicative approach
class ExtendedLeisenReimer
Leisen & Reimer tree: multiplicative approach.
class ExtendedJoshi4
class ClaytonCopulaRng
Clayton copula random-number generator.
class ComplexArray
1-D array used in linear algebra.
class FarlieGumbelMorgensternCopulaRng
Farlie-Gumbel-Morgenstern copula random-number generator.
class FastFourierTransform
FFT implementation.
class FrankCopulaRng
Frank copula random-number generator.
class ZigguratRng
Ziggurat random-number generator.
struct Ziggurat
class AdaptedPathPayoff
class LongstaffSchwartzMultiPathPricer
Longstaff-Schwarz path pricer for early exercise options.
class MCAmericanPathEngine
least-square Monte Carlo engine
class MakeMCAmericanPathEngine
Monte Carlo American basket-option engine factory.
class MCLongstaffSchwartzPathEngine
Longstaff-Schwarz Monte Carlo engine for early exercise options.
class MCPathBasketEngine
Pricing engine for path dependent basket options using.
class EuropeanPathMultiPathPricer
class MakeMCPathBasketEngine
Monte Carlo Path Basket engine factory.
class PathMultiAssetOption
Base class for path-dependent options on multiple assets.
class PathPayoff
Abstract base class for path-dependent option payoffs.
class ExtendedBlackScholesMertonProcess
experimental Black-Scholes-Merton stochastic process
class ExtendedOrnsteinUhlenbeckProcess
Extended Ornstein-Uhlenbeck process class.
class ExtOUWithJumpsProcess
class GemanRoncoroniProcess
Geman-Roncoroni process class.
class KlugeExtOUProcess
class VegaStressedBlackScholesProcess
Black-Scholes process which supports local vega stress tests.
class GeneralizedHullWhite
Generalized Hull-White model class.
class GeneralizedOrnsteinUhlenbeckProcess
Piecewise linear Ornstein-Uhlenbeck process class.
class VarianceGammaEngine
Variance Gamma Pricing engine for European vanilla options using integral approach.
class FFTEngine
Base class for FFT pricing engines for European vanilla options.
class FFTVanillaEngine
FFT Pricing engine vanilla options under a Black Scholes process.
class FFTVarianceGammaEngine
FFT engine for vanilla options under a Variance Gamma process.
class VarianceGammaModel
Variance Gamma model.
class VarianceGammaProcess
Variance gamma process.
class IntegralHestonVarianceOptionEngine
integral Heston-model variance-option engine
class VarianceOption
Variance option.
class AbcdAtmVolCurve
Abcd-interpolated at-the-money (no-smile) volatility curve.
class BlackAtmVolCurve
Black at-the-money (no-smile) volatility curve.
class BlackVolSurface
Black volatility (smile) surface.
class EquityFXVolSurface
Equity/FX volatility (smile) surface.
class ExtendedBlackVarianceCurve
Black volatility curve modelled as variance curve.
class ExtendedBlackVarianceSurface
Black volatility surface modelled as variance surface.
class InterestRateVolSurface
Interest rate volatility (smile) surface.
class SabrVolSurface
SABR volatility (smile) surface.
struct VolatilityCube
class Handle
Shared handle to an observable.
class RelinkableHandle
Relinkable handle to an observable.
class Index
purely virtual base class for indexes
class BMAIndex
Bond Market Association index.
class AUDLibor
AUD LIBOR rate
class CADLibor
CAD LIBOR rate
class CADLiborON
Overnight CAD Libor index.
class Cdor
CDOR rate
class CHFLibor
CHF LIBOR rate
class DailyTenorCHFLibor
base class for the one day deposit BBA CHF LIBOR indexes
class DKKLibor
DKK LIBOR rate
class Eonia
Eonia (Euro Overnight Index Average) rate fixed by the ECB.
class Euribor
Euribor index
class Euribor365
Actual/365 Euribor index.
class EuriborSW
1-week Euribor index
class Euribor2W
2-weeks Euribor index
class Euribor3W
3-weeks Euribor index
class Euribor1M
1-month Euribor index
class Euribor2M
2-months Euribor index
class Euribor3M
3-months Euribor index
class Euribor4M
4-months Euribor index
class Euribor5M
5-months Euribor index
class Euribor6M
6-months Euribor index
class Euribor7M
7-months Euribor index
class Euribor8M
8-months Euribor index
class Euribor9M
9-months Euribor index
class Euribor10M
10-months Euribor index
class Euribor11M
11-months Euribor index
class Euribor1Y
1-year Euribor index
class Euribor365_SW
1-week Euribor365 index
class Euribor365_2W
2-weeks Euribor365 index
class Euribor365_3W
3-weeks Euribor365 index
class Euribor365_1M
1-month Euribor365 index
class Euribor365_2M
2-months Euribor365 index
class Euribor365_3M
3-months Euribor365 index
class Euribor365_4M
4-months Euribor365 index
class Euribor365_5M
5-months Euribor365 index
class Euribor365_6M
6-months Euribor365 index
class Euribor365_7M
7-months Euribor365 index
class Euribor365_8M
8-months Euribor365 index
class Euribor365_9M
9-months Euribor365 index
class Euribor365_10M
10-months Euribor365 index
class Euribor365_11M
11-months Euribor365 index
class Euribor365_1Y
1-year Euribor365 index
class EURLibor
base class for all BBA EUR LIBOR indexes but the O/N
class DailyTenorEURLibor
base class for the one day deposit BBA EUR LIBOR indexes
class EURLiborON
Overnight EUR Libor index.
class EURLiborSW
1-week EUR Libor index
class EURLibor2W
2-weeks EUR Libor index
class EURLibor1M
1-month EUR Libor index
class EURLibor2M
2-months EUR Libor index
class EURLibor3M
3-months EUR Libor index
class EURLibor4M
4-months EUR Libor index
class EURLibor5M
5-months EUR Libor index
class EURLibor6M
6-months EUR Libor index
class EURLibor7M
7-months EUR Libor index
class EURLibor8M
8-months EUR Libor index
class EURLibor9M
9-months EUR Libor index
class EURLibor10M
10-months EUR Libor index
class EURLibor11M
11-months EUR Libor index
class EURLibor1Y
1-year EUR Libor index
class GBPLibor
GBP LIBOR rate
class DailyTenorGBPLibor
base class for the one day deposit BBA GBP LIBOR indexes
class GBPLiborON
Overnight GBP Libor index.
class Jibar
JIBAR rate
class JPYLibor
JPY LIBOR rate
class DailyTenorJPYLibor
base class for the one day deposit BBA JPY LIBOR indexes
class Libor
base class for all BBA LIBOR indexes but the EUR, O/N, and S/N ones
class DailyTenorLibor
base class for all O/N-S/N BBA LIBOR indexes but the EUR ones
class NZDLibor
NZD LIBOR rate
class SEKLibor
SEK LIBOR rate
class Sonia
Sonia (Sterling Overnight Index Average) rate.
class Tibor
JPY TIBOR index
class TRLibor
TRY LIBOR rate
class USDLibor
USD LIBOR rate
class DailyTenorUSDLibor
base class for the one day deposit BBA USD LIBOR indexes
class USDLiborON
Overnight USD Libor index.
class Zibor
CHF ZIBOR rate
class IborIndex
base class for Inter-Bank-Offered-Rate indexes (e.g. Libor, etc.)
class OvernightIndex
class IndexManager
global repository for past index fixings
class AUCPI
AU CPI index (either quarterly or annual)
class YYAUCPI
Genuine year-on-year AU CPI (i.e. not a ratio)
class YYAUCPIr
Fake year-on-year AUCPI (i.e. a ratio)
class EUHICP
EU HICP index.
class EUHICPXT
EU HICPXT index.
class YYEUHICP
Genuine year-on-year EU HICP (i.e. not a ratio of EU HICP)
class YYEUHICPXT
Genuine year-on-year EU HICPXT.
class YYEUHICPr
Fake year-on-year EU HICP (i.e. a ratio of EU HICP)
class FRHICP
FR HICP index.
class YYFRHICP
Genuine year-on-year FR HICP (i.e. not a ratio)
class YYFRHICPr
Fake year-on-year FR HICP (i.e. a ratio)
class UKRPI
UK Retail Price Inflation Index.
class YYUKRPI
Genuine year-on-year UK RPI (i.e. not a ratio of UK RPI)
class YYUKRPIr
Fake year-on-year UK RPI (i.e. a ratio of UK RPI)
class USCPI
US CPI index.
class YYUSCPI
Genuine year-on-year US CPI (i.e. not a ratio of US CPI)
class YYUSCPIr
Fake year-on-year US CPI (i.e. a ratio of US CPI)
class InflationIndex
Base class for inflation-rate indexes,.
class ZeroInflationIndex
Base class for zero inflation indices.
class YoYInflationIndex
Base class for year-on-year inflation indices.
class InterestRateIndex
base class for interest rate indexes
class Region
Region class, used for inflation applicability.
class AustraliaRegion
Australia as geographical/economic region.
class EURegion
European Union as geographical/economic region.
class FranceRegion
France as geographical/economic region.
class UKRegion
United Kingdom as geographical/economic region.
class USRegion
USA as geographical/economic region.
class ChfLiborSwapIsdaFix
ChfLiborSwapIsdaFix index base class
class EuriborSwapIsdaFixA
EuriborSwapIsdaFixA index base class
class EuriborSwapIsdaFixB
EuriborSwapIsdaFixB index base class
class EuriborSwapIfrFix
EuriborSwapIfrFix index base class
class EurLiborSwapIsdaFixA
EurLiborSwapIsdaFixA index base class
class EurLiborSwapIsdaFixB
EurLiborSwapIsdaFixB index base class
class EurLiborSwapIfrFix
EurLiborSwapIfrFix index base class
class GbpLiborSwapIsdaFix
GbpLiborSwapIsdaFix index base class
class JpyLiborSwapIsdaFixAm
JpyLiborSwapIsdaFixAm index base class
class JpyLiborSwapIsdaFixPm
JpyLiborSwapIsdaFixPm index base class
class UsdLiborSwapIsdaFixAm
UsdLiborSwapIsdaFixAm index base class
class UsdLiborSwapIsdaFixPm
UsdLiborSwapIsdaFixPm index base class
class SwapIndex
base class for swap-rate indexes
class OvernightIndexedSwapIndex
base class for overnight indexed swap indexes
class Instrument
Abstract instrument class.
class ContinuousAveragingAsianOption
Continuous-averaging Asian option.
class DiscreteAveragingAsianOption
Discrete-averaging Asian option.
class AssetSwap
Bullet bond vs Libor swap.
struct Average
Placeholder for enumerated averaging types.
class BarrierOption
Barrier option on a single asset.
struct Barrier
Placeholder for enumerated barrier types.
class BasketPayoff
class MinBasketPayoff
class MaxBasketPayoff
class AverageBasketPayoff
class SpreadBasketPayoff
class BasketOption
Basket option on a number of assets.
class BMASwap
swap paying Libor against BMA coupons
class Bond
Base bond class.
class CCTEU
class BTP
Italian BTP (Buono Poliennali del Tesoro) fixed rate bond.
class RendistatoBasket
class RendistatoCalculator
class RendistatoEquivalentSwapLengthQuote
RendistatoCalculator equivalent swap lenth Quote adapter.
class RendistatoEquivalentSwapSpreadQuote
RendistatoCalculator equivalent swap spread Quote adapter.
class CmsRateBond
CMS-rate bond.
class CPIBond
class FixedRateBond
fixed-rate bond
class FloatingRateBond
floating-rate bond (possibly capped and/or floored)
class ZeroCouponBond
zero-coupon bond
class Callability
instrument callability
class CapFloor
Base class for cap-like instruments.
class Cap
Concrete cap class.
class Floor
Concrete floor class.
class Collar
Concrete collar class.
class Claim
Claim associated to a default event.
class FaceValueClaim
Claim on a notional.
class FaceValueAccrualClaim
Claim on the notional of a reference security, including accrual.
class CliquetOption
cliquet (Ratchet) option
class CompositeInstrument
Composite instrument
class CPICapFloor
CPI cap or floor.
class CPISwap
zero-inflation-indexed swap,
class CreditDefaultSwap
Credit default swap.
class DividendBarrierOption
Single-asset barrier option with discrete dividends.
class DividendVanillaOption
Single-asset vanilla option (no barriers) with discrete dividends.
class EuropeanOption
European option on a single asset.
class FixedRateBondForward
Forward contract on a fixed-rate bond
class Forward
Abstract base forward class.
class ForwardTypePayoff
Class for forward type payoffs.
class ForwardRateAgreement
class ForwardOptionArguments
Arguments for forward (strike-resetting) option calculation
class ForwardVanillaOption
Forward version of a vanilla option
class YoYInflationCapFloor
Base class for yoy inflation cap-like instruments.
class YoYInflationCap
Concrete YoY Inflation cap class.
class YoYInflationFloor
Concrete YoY Inflation floor class.
class YoYInflationCollar
Concrete YoY Inflation collar class.
class ContinuousFloatingLookbackOption
Continuous-floating lookback option.
class ContinuousFixedLookbackOption
Continuous-fixed lookback option.
class MakeCapFloor
helper class
class MakeCms
helper class for instantiating CMS
class MakeOIS
helper class
class MakeSwaption
helper class
class MakeVanillaSwap
helper class
class MakeYoYInflationCapFloor
helper class
class MultiAssetOption
Base class for options on multiple assets.
class OneAssetOption
Base class for options on a single asset.
class OvernightIndexedSwap
Overnight indexed swap: fix vs compounded overnight rate.
class NullPayoff
Dummy payoff class.
class TypePayoff
Intermediate class for put/call payoffs.
class FloatingTypePayoff
Payoff based on a floating strike
class StrikedTypePayoff
Intermediate class for payoffs based on a fixed strike.
class PlainVanillaPayoff
Plain-vanilla payoff.
class PercentageStrikePayoff
Payoff with strike expressed as percentage
class AssetOrNothingPayoff
Binary asset-or-nothing payoff.
class CashOrNothingPayoff
Binary cash-or-nothing payoff.
class GapPayoff
Binary gap payoff.
class SuperFundPayoff
Binary supershare and superfund payoffs.
class SuperSharePayoff
Binary supershare payoff.
class QuantoBarrierOption
Quanto version of a barrier option.
class QuantoForwardVanillaOption
Quanto version of a forward vanilla option.
class QuantoOptionResults
Results from quanto option calculation
class QuantoVanillaOption
quanto version of a vanilla option
class DoubleStickyRatchetPayoff
Intermediate class for single/double sticky/ratchet payoffs.
class RatchetPayoff
Ratchet payoff (single option)
class StickyPayoff
Sticky payoff (single option)
class RatchetMaxPayoff
RatchetMax payoff (double option)
class RatchetMinPayoff
RatchetMin payoff (double option)
class StickyMaxPayoff
StickyMax payoff (double option)
class StickyMinPayoff
StickyMin payoff (double option)
class Stock
Simple stock class.
class Swap
Interest rate swap.
struct Settlement
settlement information
class Swaption
Swaption class
class VanillaOption
Vanilla option (no discrete dividends, no barriers) on a single asset.
class VanillaStorageOption
base option class
class VanillaSwap
Plain-vanilla swap: fix vs floating leg.
class SwingExercise
Swing exercise.
class VanillaSwingOption
base option class
class VarianceSwap
Variance swap.
class YearOnYearInflationSwap
Year-on-year inflation-indexed swap.
class ZeroCouponInflationSwap
Zero-coupon inflation-indexed swap.
class InterestRate
Concrete interest rate class.
class LfmCovarianceParameterization
Libor market model parameterization
class LfmCovarianceProxy
proxy for a libor forward model covariance parameterization
class LfmHullWhiteParameterization
Libor market model parameterization based on Hull White paper
class LiborForwardModelProcess
libor-forward-model process
class LfmSwaptionEngine
Libor forward model swaption engine based on Black formula
class LiborForwardModel
Libor forward model
class LmConstWrapperCorrelationModel
class LmConstWrapperVolatilityModel
caplet const volatility model
class LmCorrelationModel
libor forward correlation model
class LmExponentialCorrelationModel
exponential correlation model
class LmExtLinearExponentialVolModel
extended linear exponential volatility model
class LmFixedVolatilityModel
class LmLinearExponentialCorrelationModel
linear exponential correlation model
class LmLinearExponentialVolatilityModel
linear exponential volatility model
class LmVolatilityModel
caplet volatility model
class Array
1-D array used in linear algebra.
class Null< Array >
specialization of null template for this class
class BernsteinPolynomial
class of Bernstein polynomials
class BSpline
B-spline basis functions.
struct earlier_than< boost::shared_ptr< T > >
class AliMikhailHaqCopula
Ali-Mikhail-Haq copula.
class ClaytonCopula
Clayton copula.
class FarlieGumbelMorgensternCopula
Farlie-Gumbel-Morgenstern copula.
class FrankCopula
Frank copula.
class GalambosCopula
Galambos copula.
class GaussianCopula
Gaussian copula.
class GumbelCopula
Gumbel copula.
class HuslerReissCopula
Husler-Reiss copula.
class IndependentCopula
independent copula
class MarshallOlkinCopula
Marshall-Olkin copula.
class MaxCopula
max copula
class MinCopula
min copula
class PlackettCopula
Plackett copula.
class Curve
abstract curve class
class TestCurve
class BinomialDistribution
Binomial probability distribution function.
class CumulativeBinomialDistribution
Cumulative binomial distribution function.
class BivariateCumulativeNormalDistributionDr78
Cumulative bivariate normal distribution function.
class BivariateCumulativeNormalDistributionWe04DP
Cumulative bivariate normal distibution function (West 2004)
class ChiSquareDistribution
class NonCentralChiSquareDistribution
class InverseNonCentralChiSquareDistribution
class GammaDistribution
class GammaFunction
Gamma function class.
class NormalDistribution
Normal distribution function.
class CumulativeNormalDistribution
Cumulative normal distribution function.
class InverseCumulativeNormal
Inverse cumulative normal distribution function.
class MoroInverseCumulativeNormal
Moro Inverse cumulative normal distribution class.
class PoissonDistribution
Poisson distribution function.
class CumulativePoissonDistribution
Cumulative Poisson distribution function.
class InverseCumulativePoisson
Inverse cumulative Poisson distribution function.
class StudentDistribution
Student t-distribution.
class CumulativeStudentDistribution
Cumulative Student t-distribution.
class InverseCumulativeStudent
Inverse cumulative Student t-distribution.
class Domain
domain abstract lcass
class UniversalDomain
class NullDomain
class BoundedDomain
class RectangularDomain
class ErrorFunction
Error function
class Factorial
Factorial numbers calculator
class constant
class identity
class square
class cube
class fourth_power
class everywhere
class nowhere
class equal_within
class clipped_function
class composed_function
class binary_compose3_function
class GeneralLinearLeastSquares
general linear least squares regression
class GaussianOrthogonalPolynomial
orthogonal polynomial for Gaussian quadratures
class GaussLaguerrePolynomial
Gauss-Laguerre polynomial.
class GaussHermitePolynomial
Gauss-Hermite polynomial.
class GaussJacobiPolynomial
Gauss-Jacobi polynomial.
class GaussLegendrePolynomial
Gauss-Legendre polynomial.
class GaussChebyshevPolynomial
Gauss-Chebyshev polynomial.
class GaussChebyshev2ndPolynomial
Gauss-Chebyshev polynomial (second kind)
class GaussGegenbauerPolynomial
Gauss-Gegenbauer polynomial.
class GaussHyperbolicPolynomial
Gauss hyperbolic polynomial.
class GaussianQuadrature
Integral of a 1-dimensional function using the Gauss quadratures method.
class GaussLaguerreIntegration
generalized Gauss-Laguerre integration
class GaussHermiteIntegration
generalized Gauss-Hermite integration
class GaussJacobiIntegration
Gauss-Jacobi integration.
class GaussHyperbolicIntegration
Gauss-Hyperbolic integration.
class GaussLegendreIntegration
Gauss-Legendre integration.
class GaussChebyshevIntegration
Gauss-Chebyshev integration.
class GaussChebyshev2ndIntegration
Gauss-Chebyshev integration (second kind)
class GaussGegenbauerIntegration
Gauss-Gegenbauer integration.
class TabulatedGaussLegendre
tabulated Gauss-Legendre quadratures
class GaussLobattoIntegral
Integral of a one-dimensional function.
class Integrator
class GaussKronrodNonAdaptive
Integral of a 1-dimensional function using the Gauss-Kronrod methods.
class GaussKronrodAdaptive
Integral of a 1-dimensional function using the Gauss-Kronrod methods.
class SegmentIntegral
Integral of a one-dimensional function.
class SimpsonIntegral
Integral of a one-dimensional function.
class TrapezoidIntegral
Integral of a one-dimensional function.
struct Default
struct MidPoint
class Interpolation
base class for 1-D interpolations.
class AbcdInterpolation
Abcd interpolation between discrete points.
class Abcd
Abcd interpolation factory and traits
class BackwardFlatInterpolation
Backward-flat interpolation between discrete points.
class BackwardFlat
Backward-flat interpolation factory and traits.
class BicubicSpline
bicubic-spline interpolation between discrete points
class Bicubic
bicubic-spline-interpolation factory
class BilinearInterpolation
bilinear interpolation between discrete points
class Bilinear
bilinear-interpolation factory
class ConvexMonotoneInterpolation
Convex monotone yield-curve interpolation method.
class ConvexMonotone
Convex-monotone interpolation factory and traits.
class CubicInterpolation
Cubic interpolation between discrete points.
class CubicNaturalSpline
class MonotonicCubicNaturalSpline
class CubicSplineOvershootingMinimization1
class CubicSplineOvershootingMinimization2
class AkimaCubicInterpolation
class KrugerCubic
class FritschButlandCubic
class Parabolic
class MonotonicParabolic
class Cubic
Cubic interpolation factory and traits
class Extrapolator
base class for classes possibly allowing extrapolation
class FlatExtrapolator2D
class ForwardFlatInterpolation
Forward-flat interpolation between discrete points.
class ForwardFlat
Forward-flat interpolation factory and traits.
class Interpolation2D
base class for 2-D interpolations.
class KernelInterpolation
Kernel interpolation between discrete points.
class KernelInterpolation2D
class LinearInterpolation
Linear interpolation between discrete points
class Linear
Linear-interpolation factory and traits
class LogLinearInterpolation
log-linear interpolation between discrete points
class LogLinear
log-linear interpolation factory and traits
class LogCubicInterpolation
log-cubic interpolation between discrete points
class LogCubic
log-cubic interpolation factory and traits
class LogCubicNaturalSpline
class MonotonicLogCubicNaturalSpline
class KrugerLogCubic
class FritschButlandLogCubic
class LogParabolic
class MonotonicLogParabolic
class MixedLinearCubicInterpolation
mixed linear/cubic interpolation between discrete points
class MixedLinearCubic
mixed linear/cubic interpolation factory and traits
class MixedLinearCubicNaturalSpline
class MixedLinearMonotonicCubicNaturalSpline
class MixedLinearKrugerCubic
class MixedLinearFritschButlandCubic
class MixedLinearParabolic
class MixedLinearMonotonicParabolic
class MultiCubicSpline
N-dimensional cubic spline interpolation between discrete points.
class SABRInterpolation
SABR smile interpolation between discrete volatility points.
class SABR
SABR interpolation factory and traits
class KernelFunction
class GaussianKernel
Gaussian kernel function.
class LexicographicalView
Lexicographical 2-D view of a contiguous set of data.
class LinearRegression
class LinearLeastSquaresRegression
class Matrix
Matrix used in linear algebra.
class BasisIncompleteOrdered
class OrthogonalProjections
struct BiCGStabResult
class BiCGstab
class CovarianceDecomposition
Covariance decomposition into correlation and variances.
struct SalvagingAlgorithm
algorithm used for matricial pseudo square root
class SparseILUPreconditioner
class SVD
Singular value decomposition.
class SymmetricSchurDecomposition
symmetric threshold Jacobi algorithm.
class FrobeniusCostFunction
class TqrEigenDecomposition
tridiag. QR eigen decomposition with explicite shift aka Wilkinson
class ArmijoLineSearch
Armijo line search.
class BFGS
Broyden-Fletcher-Goldfarb-Shanno algorithm.
class ConjugateGradient
Multi-dimensional Conjugate Gradient class.
class Constraint
Base constraint class.
class NoConstraint
No constraint.
class PositiveConstraint
Constraint imposing positivity to all arguments
class BoundaryConstraint
Constraint imposing all arguments to be in [low,high]
class CompositeConstraint
Constraint enforcing both given sub-constraints
class CostFunction
Cost function abstract class for optimization problem.
class ParametersTransformation
class EndCriteria
Criteria to end optimization process:
class LeastSquareProblem
Base class for least square problem.
class LeastSquareFunction
Cost function for least-square problems.
class NonLinearLeastSquare
Non-linear least-square method.
class LevenbergMarquardt
Levenberg-Marquardt optimization method.
class LineSearch
Base class for line search.
class LineSearchBasedMethod
class OptimizationMethod
Abstract class for constrained optimization method.
class Problem
Constrained optimization problem.
class ProjectedCostFunction
Parameterized cost function.
class Simplex
Multi-dimensional simplex class.
class SphereCylinderOptimizer
class SteepestDescent
Multi-dimensional steepest-descent class.
class PrimeNumbers
Prime numbers calculator.
class quadratic
class BoxMullerGaussianRng
Gaussian random number generator.
class CLGaussianRng
Gaussian random number generator.
class FaureRsg
Faure low-discrepancy sequence generator.
class HaltonRsg
Halton low-discrepancy sequence generator.
class InverseCumulativeRng
Inverse cumulative random number generator.
class InverseCumulativeRsg
Inverse cumulative random sequence generator.
class KnuthUniformRng
Uniform random number generator.
class LatticeRsg
class LatticeRule
class LecuyerUniformRng
Uniform random number generator.
class MersenneTwisterUniformRng
Uniform random number generator.
class RandomizedLDS
Randomized (random shift) low-discrepancy sequence.
class RandomSequenceGenerator
Random sequence generator based on a pseudo-random number generator.
class Ranlux3UniformRng
Uniform random number generator.
class Ranlux4UniformRng
struct GenericPseudoRandom
struct GenericLowDiscrepancy
class SeedGenerator
Random seed generator.
class SobolBrownianBridgeRsg
class SobolRsg
Sobol low-discrepancy sequence generator.
class RichardsonExtrapolation
Richardson Extrapolation.
class Rounding
basic rounding class
class UpRounding
Up-rounding.
class DownRounding
Down-rounding.
class ClosestRounding
Closest rounding.
class CeilingTruncation
Ceiling truncation.
class FloorTruncation
Floor truncation.
class SampledCurve
This class contains a sampled curve.
class Solver1D
Base class for 1-D solvers.
class Bisection
Bisection 1-D solver
class Brent
Brent 1-D solver
class FalsePosition
False position 1-D solver.
class FiniteDifferenceNewtonSafe
safe Newton 1-D solver with finite difference derivatives
class Newton
Newton 1-D solver
class NewtonSafe
safe Newton 1-D solver
class Ridder
Ridder 1-D solver
class Secant
Secant 1-D solver
class DoublingConvergenceSteps
class ConvergenceStatistics
statistics class with convergence table
class DiscrepancyStatistics
Statistic tool for sequences with discrepancy calculation.
class GenericGaussianStatistics
Statistics tool for gaussian-assumption risk measures.
class StatsHolder
Helper class for precomputed distributions.
class GeneralStatistics
Statistics tool.
class Histogram
Histogram class.
class IncrementalStatistics
Statistics tool based on incremental accumulation.
class GenericRiskStatistics
empirical-distribution risk measures
class GenericSequenceStatistics
Statistics analysis of N-dimensional (sequence) data.
class Surface
Surface abstract class
class TestSurface
class TransformedGrid
transformed grid
class LogGrid
class AmericanCondition
American exercise condition.
class BoundaryCondition
Abstract boundary condition class for finite difference problems.
class NeumannBC
Neumann boundary condition (i.e., constant derivative)
class DirichletBC
Neumann boundary condition (i.e., constant value)
class BSMOperator
Black-Scholes-Merton differential operator.
class CrankNicolson
Crank-Nicolson scheme for finite difference methods.
class DMinus
\(D_{-} \) matricial representation
class DPlus
\(D_{+} \) matricial representation
class DPlusDMinus
\(D_{+}D_{-} \) matricial representation
class DZero
\(D_{0} \) matricial representation
class ExplicitEuler
Forward Euler scheme for finite difference methods
class FiniteDifferenceModel
Generic finite difference model.
class ImplicitEuler
Backward Euler scheme for finite difference methods.
class Concentrating1dMesher
class ExponentialJump1dMesher
class Fdm1dMesher
class FdmBlackScholesMesher
class FdmBlackScholesMultiStrikeMesher
class FdmHestonVarianceMesher
class FdmMesher
class FdmMesherComposite
class FdmSimpleProcess1dMesher
class Uniform1dMesher
class UniformGridMesher
class MixedScheme
Mixed (explicit/implicit) scheme for finite difference methods.
class OperatorFactory
Black-Scholes-Merton differential operator.
class Fdm2dBlackScholesOp
class FdmBatesOp
class FdmBlackScholesOp
class FdmG2Op
class FdmHestonHullWhiteEquityPart
class FdmHestonHullWhiteOp
class FdmHestonEquityPart
class FdmHestonVariancePart
class FdmHestonOp
class FdmHullWhiteOp
class FdmLinearOp
class FdmLinearOpComposite
class FdmLinearOpIterator
class FdmLinearOpLayout
class FirstDerivativeOp
class NinePointLinearOp
class SecondDerivativeOp
class SecondOrderMixedDerivativeOp
class TripleBandLinearOp
class OperatorTraits
class StepConditionSet
Parallel evolver for multiple arrays.
class BoundaryConditionSet
class ParallelEvolverTraits
class ParallelEvolver
class PdeSecondOrderParabolic
class PdeConstantCoeff
class GenericTimeSetter
class PdeOperator
class PdeBSM
class PdeShortRate
class BoundaryConditionSchemeHelper
class CraigSneydScheme
class DouglasScheme
class ExplicitEulerScheme
class HundsdorferScheme
class ImplicitEulerScheme
class ModifiedCraigSneydScheme
modified Craig-Sneyd scheme
class ShoutCondition
Shout option condition.
class Fdm1DimSolver
class Fdm2dBlackScholesSolver
class Fdm2DimSolver
class Fdm3DimSolver
struct FdmSchemeDesc
class FdmBackwardSolver
class FdmBatesSolver
class FdmBlackScholesSolver
class FdmG2Solver
class FdmHestonHullWhiteSolver
class FdmHestonSolver
class FdmHullWhiteSolver
class FdmNdimSolver
class FdmSimple2dBSSolver
struct FdmSolverDesc
class StepCondition
condition to be applied at every time step
class CurveDependentStepCondition
class NullCondition
null step condition
class FdmAmericanStepCondition
class FdmArithmeticAverageCondition
class FdmBermudanStepCondition
class FdmSimpleStorageCondition
class FdmSimpleSwingCondition
class FdmSnapshotCondition
class FdmStepConditionComposite
class TRBDF2
TR-BDF2 scheme for finite difference methods.
class TridiagonalOperator
Base implementation for tridiagonal operator.
class FdmAffineModelSwapInnerValue
class FdmAffineModelTermStructure
class FdmDirichletBoundary
class FdmDividendHandler
class FdmIndicesOnBoundary
class FdmInnerValueCalculator
class FdmLogInnerValue
class FdmLogBasketInnerValue
class FdmZeroInnerValue
class FdmQuantoHelper
class FdmTimeDepDirichletBoundary
class ZeroCondition
Zero exercise condition.
class BinomialTree
Binomial tree base class.
class EqualProbabilitiesBinomialTree
Base class for equal probabilities binomial tree.
class EqualJumpsBinomialTree
Base class for equal jumps binomial tree.
class JarrowRudd
Jarrow-Rudd (multiplicative) equal probabilities binomial tree.
class CoxRossRubinstein
Cox-Ross-Rubinstein (multiplicative) equal jumps binomial tree.
class AdditiveEQPBinomialTree
Additive equal probabilities binomial tree.
class Trigeorgis
Trigeorgis (additive equal jumps) binomial tree
class Tian
Tian tree: third moment matching, multiplicative approach
class LeisenReimer
Leisen & Reimer tree: multiplicative approach.
class Joshi4
class BlackScholesLattice
Simple binomial lattice approximating the Black-Scholes model.
class TreeLattice
Tree-based lattice-method base class.
class TreeLattice1D
One-dimensional tree-based lattice.
class TreeLattice2D
Two-dimensional tree-based lattice.
class Tree
Tree approximating a single-factor diffusion
class TrinomialTree
Recombining trinomial tree class.
class BrownianBridge
Builds Wiener process paths using Gaussian variates.
class EarlyExerciseTraits
class EarlyExerciseTraits< Path >
class EarlyExerciseTraits< MultiPath >
class EarlyExercisePathPricer
base class for early exercise path pricers
class ExerciseStrategy
class LongstaffSchwartzPathPricer
Longstaff-Schwarz path pricer for early exercise options.
class LsmBasisSystem
struct SingleVariate
default Monte Carlo traits for single-variate models
struct MultiVariate
default Monte Carlo traits for multi-variate models
class MonteCarloModel
General-purpose Monte Carlo model for path samples.
class MultiPath
Correlated multiple asset paths.
class MultiPathGenerator
Generates a multipath from a random number generator.
struct NodeData
class ParametricExercise
class Path
single-factor random walk
class PathGenerator
Generates random paths using a sequence generator.
class PathPricer
base class for path pricers
struct Sample
weighted sample
class CalibrationHelper
liquid market instrument used during calibration
class BatesModel
Bates stochastic-volatility model.
class BatesDetJumpModel
class BatesDoubleExpModel
class BatesDoubleExpDetJumpModel
class GJRGARCHModel
GJR-GARCH model for the stochastic volatility of an asset.
class HestonModel
Heston model for the stochastic volatility of an asset.
class HestonModelHelper
calibration helper for Heston model
class PiecewiseTimeDependentHestonModel
Piecewise time dependent Heston model.
class AccountingEngine
Engine collecting cash flows along a market-model simulation.
class BrownianGenerator
class BrownianGeneratorFactory
class MTBrownianGenerator
Mersenne-twister Brownian generator for market-model simulations.
class MTBrownianGeneratorFactory
class SobolBrownianGenerator
Sobol Brownian generator for market-model simulations.
class SobolBrownianGeneratorFactory
class BermudanSwaptionExerciseValue
class MarketModelExerciseValue
class LongstaffSchwartzExerciseStrategy
class MarketModelBasisSystem
class MarketModelParametricExercise
class MarketModelNodeDataProvider
class NothingExerciseValue
class ParametricExerciseAdapter
class SwapBasisSystem
class SwapForwardBasisSystem
class SwapRateTrigger
class TriggeredSwapExercise
class UpperBoundEngine
Market-model engine for upper-bound estimation.
class ConstrainedEvolver
Constrained market-model evolver.
class CotSwapFromFwdCorrelation
class ExponentialForwardCorrelation
class TimeHomogeneousForwardCorrelation
class CurveState
Curve state for market-model simulations
class CMSwapCurveState
Curve state for constant-maturity-swap market models
class CoterminalSwapCurveState
Curve state for coterminal-swap market models
class LMMCurveState
Curve state for Libor market models
class MarketModelDiscounter
class CMSMMDriftCalculator
Drift computation for CMS market models.
class LMMDriftCalculator
Drift computation for log-normal Libor market models.
class LMMNormalDriftCalculator
Drift computation for normal Libor market models.
class SMMDriftCalculator
Drift computation for coterminal swap market models.
class EvolutionDescription
Market-model evolution description.
class MarketModelEvolver
Market-model evolver.
class LogNormalCmSwapRatePc
Predictor-Corrector.
class LogNormalCotSwapRatePc
Predictor-Corrector.
class LogNormalFwdRateBalland
Iterative Predictor-Corrector.
class LogNormalFwdRateEuler
Euler.
class LogNormalFwdRateEulerConstrained
euler stepping
class LogNormalFwdRateiBalland
Iterative Predictor-Corrector.
class LogNormalFwdRateIpc
Iterative Predictor-Corrector.
class LogNormalFwdRatePc
Predictor-Corrector.
class MarketModelVolProcess
class NormalFwdRatePc
Predictor-Corrector.
class SVDDFwdRatePc
class SquareRootAndersen
class HistoricalForwardRatesAnalysis
class HistoricalForwardRatesAnalysisImpl
Historical correlation class
class HistoricalRatesAnalysis
Historical rate analysis class
class MarketModel
base class for market models
class MarketModelFactory
base class for market-model factories
class AbcdVol
Abcd-interpolated volatility structure
class AlphaFinder
class AlphaForm
class AlphaFormInverseLinear
class AlphaFormLinearHyperbolic
class CTSMMCapletAlphaFormCalibration
class CTSMMCapletMaxHomogeneityCalibration
class CTSMMCapletOriginalCalibration
class CotSwapToFwdAdapter
class CotSwapToFwdAdapterFactory
class CTSMMCapletCalibration
class FlatVol
class FlatVolFactory
class FwdPeriodAdapter
class FwdToCotSwapAdapter
class FwdToCotSwapAdapterFactory
class PiecewiseConstantAbcdVariance
class PiecewiseConstantVariance
class PseudoRootFacade
class VolatilityInterpolationSpecifier
class VolatilityInterpolationSpecifierabcd
class MarketModelMultiProduct
market-model product
class PathwiseAccountingEngine
Engine collecting cash flows along a market-model simulation for doing pathwise computation of Deltas.
class PathwiseVegasAccountingEngine
Engine collecting cash flows along a market-model simulation for doing pathwise computation of Deltas and vegas.
class PathwiseVegasOuterAccountingEngine
Engine collecting cash flows along a market-model simulation for doing pathwise computation of Deltas and vegas.
class MarketModelPathwiseDiscounter
class VolatilityBumpInstrumentJacobian
class OrthogonalizedBumpFinder
class RatePseudoRootJacobianNumerical
class RatePseudoRootJacobian
class RatePseudoRootJacobianAllElements
class SwaptionPseudoDerivative
class CapPseudoDerivative
class VegaBumpCluster
class VegaBumpCollection
class MarketModelPathwiseMultiProduct
market-model pathwise product
class PiecewiseConstantCorrelation
class MarketModelComposite
Composition of two or more market-model products.
class MultiProductComposite
Composition of one or more market-model products.
class MultiProductMultiStep
Multiple-step market-model product.
class MultiProductOneStep
Single-step market-model product.
class CallSpecifiedMultiProduct
class MarketModelCashRebate
class ExerciseAdapter
class MultiStepCoinitialSwaps
class MultiStepCoterminalSwaps
class MultiStepCoterminalSwaptions
class MultiStepForwards
class MultiStepInverseFloater
class MultiStepNothing
class MultiStepOptionlets
class MultiProductPathwiseWrapper
class MultiStepPeriodCapletSwaptions
class MultiStepRatchet
class MultiStepSwap
class MultiStepSwaption
class MultiStepTarn
class OneStepCoinitialSwaps
class OneStepCoterminalSwaps
class OneStepForwards
class OneStepOptionlets
class CallSpecifiedPathwiseMultiProduct
class MarketModelPathwiseMultiCaplet
market-model pathwise caplet
class MarketModelPathwiseMultiDeflatedCaplet
class MarketModelPathwiseMultiDeflatedCap
class MarketModelPathwiseCashRebate
class MarketModelPathwiseInverseFloater
class MarketModelPathwiseSwap
class MarketModelPathwiseCoterminalSwaptionsDeflated
class MarketModelPathwiseCoterminalSwaptionsNumericalDeflated
class SingleProductComposite
Composition of one or more market-model products.
class ProxyGreekEngine
class SwapForwardMappings
class AffineModel
Affine model class.
class TermStructureConsistentModel
Term-structure consistent model class.
class CalibratedModel
Calibrated model class.
class ShortRateModel
Abstract short-rate model class.
class Parameter
Base class for model arguments.
class ConstantParameter
Standard constant parameter \(a(t) = a \).
class NullParameter
Parameter which is always zero \(a(t) = 0 \)
class PiecewiseConstantParameter
Piecewise-constant parameter.
class TermStructureFittingParameter
Deterministic time-dependent parameter used for yield-curve fitting.
class CapHelper
calibration helper for ATM cap
class SwaptionHelper
calibration helper for ATM swaption
class OneFactorModel
Single-factor short-rate model abstract class.
class OneFactorAffineModel
Single-factor affine base class.
class BlackKarasinski
Standard Black-Karasinski model class.
class CoxIngersollRoss
Cox-Ingersoll-Ross model class.
class ExtendedCoxIngersollRoss
Extended Cox-Ingersoll-Ross model class.
class HullWhite
Single-factor Hull-White (extended Vasicek) model class.
class Vasicek
Vasicek model class
class TwoFactorModel
Abstract base-class for two-factor models.
class G2
Two-additive-factor gaussian model class.
class ConstantEstimator
Constant-estimator volatility model.
class Garch11
GARCH volatility model.
class GarmanKlassAbstract
Garman-Klass volatility model.
class GarmanKlassSimpleSigma
class GarmanKlassOpenClose
class GarmanKlassSigma1
class ParkinsonSigma
class GarmanKlassSigma3
class GarmanKlassSigma4
class GarmanKlassSigma5
class GarmanKlassSigma6
class SimpleLocalEstimator
Local-estimator volatility model.
class Money
amount of cash
class Lattice
Lattice (tree, finite-differences) base class
class Option
base option class
class Greeks
additional option results
class MoreGreeks
more additional option results
class Composite
Composite pattern.
class CuriouslyRecurringTemplate
Support for the curiously recurring template pattern.
class LazyObject
Framework for calculation on demand and result caching.
class Observable
Object that notifies its changes to a set of observers.
class Observer
Object that gets notified when a given observable changes.
class Singleton
Basic support for the singleton pattern.
class AcyclicVisitor
degenerate base class for the Acyclic Visitor pattern
class Visitor
Visitor for a specific class
class Payoff
Abstract base class for option payoffs.
struct Position
class IntervalPrice
interval price
class Null< IntervalPrice >
class PricingEngine
interface for pricing engines
class GenericEngine
template base class for option pricing engines
class AmericanPayoffAtExpiry
Analytic formula for American exercise payoff at-expiry options.
class AmericanPayoffAtHit
Analytic formula for American exercise payoff at-hit options.
class AnalyticContinuousGeometricAveragePriceAsianEngine
Pricing engine for European continuous geometric average price Asian.
class AnalyticDiscreteGeometricAveragePriceAsianEngine
Pricing engine for European discrete geometric average price Asian.
class AnalyticDiscreteGeometricAverageStrikeAsianEngine
Pricing engine for European discrete geometric average-strike Asian option.
class FdBlackScholesAsianEngine
class MCDiscreteArithmeticAPEngine
Monte Carlo pricing engine for discrete arithmetic average price Asian.
class ArithmeticAPOPathPricer
class MakeMCDiscreteArithmeticAPEngine
class MCDiscreteArithmeticASEngine
Monte Carlo pricing engine for discrete arithmetic average-strike Asian.
class ArithmeticASOPathPricer
class MakeMCDiscreteArithmeticASEngine
class MCDiscreteGeometricAPEngine
Monte Carlo pricing engine for discrete geometric average price Asian.
class GeometricAPOPathPricer
class MakeMCDiscreteGeometricAPEngine
class MCDiscreteAveragingAsianEngine
Pricing engine for discrete average Asians using Monte Carlo simulation.
class AnalyticBarrierEngine
Pricing engine for barrier options using analytical formulae.
class FdBlackScholesBarrierEngine
Finite-Differences Black Scholes barrier option engine.
class FdBlackScholesRebateEngine
Finite-Differences Black Scholes barrier option rebate helper engine.
class FdHestonBarrierEngine
Finite-Differences Heston Barrier Option engine.
class FdHestonRebateEngine
Finite-Differences Heston Barrier Option rebate helper engine.
class MCBarrierEngine
Pricing engine for barrier options using Monte Carlo simulation.
class MakeMCBarrierEngine
Monte Carlo barrier-option engine factory.
class BarrierPathPricer
class BiasedBarrierPathPricer
class Fd2dBlackScholesVanillaEngine
Two dimensional finite-differences Black Scholes vanilla option engine.
class KirkEngine
Pricing engine for spread option on two futures.
class MCAmericanBasketEngine
least-square Monte Carlo engine
class MakeMCAmericanBasketEngine
Monte Carlo American basket-option engine factory.
class AmericanBasketPathPricer
class MCEuropeanBasketEngine
Pricing engine for European basket options using Monte Carlo simulation.
class MakeMCEuropeanBasketEngine
Monte Carlo basket-option engine factory.
class EuropeanMultiPathPricer
class StulzEngine
Pricing engine for 2D European Baskets.
class BlackCalculator
Black 1976 calculator class.
class BlackImpliedStdDevHelper
class BlackScholesCalculator
Black-Scholes 1973 calculator class.
struct BondFunctions
Bond adapters of CashFlows functions.
class DiscountingBondEngine
class AnalyticCapFloorEngine
Analytic engine for cap/floor.
class BlackCapFloorEngine
Black-formula cap/floor engine.
class DiscretizedCapFloor
class MCHullWhiteCapFloorEngine
Monte Carlo Hull-White engine for cap/floors.
class MakeMCHullWhiteCapFloorEngine
Monte Carlo Hull-White cap-floor engine factory.
class TreeCapFloorEngine
Numerical lattice engine for cap/floors.
class AnalyticCliquetEngine
Pricing engine for Cliquet options using analytical formulae.
class AnalyticPerformanceEngine
Pricing engine for performance options using analytical formulae.
class MCPerformanceEngine
Pricing engine for performance options using Monte Carlo simulation.
class MakeMCPerformanceEngine
Monte Carlo performance-option engine factory.
class PerformanceOptionPathPricer
class IntegralCdsEngine
class MidPointCdsEngine
class ForwardVanillaEngine
Forward engine for vanilla options
class ForwardPerformanceVanillaEngine
Forward performance engine for vanilla options
class MCVarianceSwapEngine
Variance-swap pricing engine using Monte Carlo simulation,.
class MakeMCVarianceSwapEngine
Monte Carlo variance-swap engine factory.
class VariancePathPricer
class ReplicatingVarianceSwapEngine
Variance-swap pricing engine using replicating cost,.
class GenericModelEngine
Base class for some pricing engine on a particular model.
class YoYInflationCapFloorEngine
Base YoY inflation cap/floor engine.
class YoYInflationBlackCapFloorEngine
Black-formula inflation cap/floor engine (standalone, i.e. no coupon pricer)
class YoYInflationUnitDisplacedBlackCapFloorEngine
Unit Displaced Black-formula inflation cap/floor engine (standalone, i.e. no coupon pricer)
class YoYInflationBachelierCapFloorEngine
Unit Displaced Black-formula inflation cap/floor engine (standalone, i.e. no coupon pricer)
class LatticeShortRateModelEngine
Engine for a short-rate model specialized on a lattice.
class AnalyticContinuousFixedLookbackEngine
Pricing engine for European continuous fixed-strike lookback.
class AnalyticContinuousFloatingLookbackEngine
Pricing engine for European continuous floating-strike lookback.
class MCLongstaffSchwartzEngine
Longstaff-Schwarz Monte Carlo engine for early exercise options.
class McSimulation
base class for Monte Carlo engines
class QuantoEngine
Quanto engine.
class DiscountingSwapEngine
class DiscretizedSwap
class TreeVanillaSwapEngine
Numerical lattice engine for simple swaps.
class BlackSwaptionEngine
Black-formula swaption engine.
class DiscretizedSwaption
class FdG2SwaptionEngine
class FdHullWhiteSwaptionEngine
class G2SwaptionEngine
Swaption priced by means of the Black formula
class JamshidianSwaptionEngine
Jamshidian swaption engine.
class TreeSwaptionEngine
Numerical lattice engine for swaptions.
class AnalyticBSMHullWhiteEngine
analytic european option pricer including stochastic interest rates
class AnalyticDigitalAmericanEngine
Analytic pricing engine for American vanilla options with digital payoff.
class AnalyticDividendEuropeanEngine
Analytic pricing engine for European options with discrete dividends.
class AnalyticEuropeanEngine
Pricing engine for European vanilla options using analytical formulae.
class AnalyticGJRGARCHEngine
GJR-GARCH(1,1) engine.
class AnalyticHestonEngine
analytic Heston-model engine based on Fourier transform
class AnalyticHestonHullWhiteEngine
Analytic Heston engine incl. stochastic interest rates.
class AnalyticPTDHestonEngine
analytic piecewise constant time dependent Heston-model engine
class BaroneAdesiWhaleyApproximationEngine
Barone-Adesi and Whaley pricing engine for American options (1987)
class BatesEngine
Bates model engines based on Fourier transform.
class BatesDetJumpEngine
class BatesDoubleExpEngine
class BatesDoubleExpDetJumpEngine
class BinomialVanillaEngine
Pricing engine for vanilla options using binomial trees.
class BjerksundStenslandApproximationEngine
Bjerksund and Stensland pricing engine for American options (1993)
class DiscretizedVanillaOption
class FDAmericanEngine
Finite-differences pricing engine for American one asset options.
class FdBatesVanillaEngine
Partial Integro FiniteDifferences Bates Vanilla Option engine.
class FDBermudanEngine
Finite-differences Bermudan engine.
class FdBlackScholesVanillaEngine
class FDAmericanCondition
class FDShoutCondition
class FDDividendAmericanEngine
Finite-differences pricing engine for dividend American options.
class FDDividendAmericanEngineMerton73
class FDDividendAmericanEngineShiftScale
class FDDividendEngineBase
Abstract base class for dividend engines.
class FDDividendEngineMerton73
Finite-differences pricing engine for dividend options using escowed dividends model.
class FDDividendEngineShiftScale
Finite-differences engine for dividend options using shifted dividends.
class FDDividendEngine
class FDDividendEuropeanEngine
Finite-differences pricing engine for dividend European options.
class FDDividendEuropeanEngineMerton73
class FDDividendEuropeanEngineShiftScale
class FDDividendShoutEngine
Finite-differences shout engine with dividends.
class FDDividendShoutEngineMerton73
class FDDividendShoutEngineShiftScale
class FDEuropeanEngine
Pricing engine for European options using finite-differences.
class FdHestonHullWhiteVanillaEngine
Finite-Differences Heston Hull-White Vanilla Option engine.
class FdHestonVanillaEngine
Finite-Differences Heston Vanilla Option engine.
class FDMultiPeriodEngine
class FDShoutEngine
Finite-differences pricing engine for shout vanilla options.
class FdSimpleBSSwingEngine
class FDStepConditionEngine
Finite-differences pricing engine for American-style vanilla options.
class FDVanillaEngine
Finite-differences pricing engine for BSM one asset options.
class FDEngineAdapter
class IntegralEngine
Pricing engine for European vanilla options using integral approach.
class JumpDiffusionEngine
Jump-diffusion engine for vanilla options.
class JuQuadraticApproximationEngine
Pricing engine for American options with Ju quadratic approximation.
class MCAmericanEngine
American Monte Carlo engine.
class AmericanPathPricer
class MakeMCAmericanEngine
Monte Carlo American engine factory.
class MCDigitalEngine
Pricing engine for digital options using Monte Carlo simulation.
class MakeMCDigitalEngine
Monte Carlo digital engine factory.
class DigitalPathPricer
class MCEuropeanEngine
European option pricing engine using Monte Carlo simulation.
class MakeMCEuropeanEngine
Monte Carlo European engine factory.
class EuropeanPathPricer
class MCEuropeanGJRGARCHEngine
Monte Carlo GJR-GARCH-model engine for European options.
class MakeMCEuropeanGJRGARCHEngine
Monte Carlo GJR-GARCH European engine factory.
class EuropeanGJRGARCHPathPricer
class MCEuropeanHestonEngine
Monte Carlo Heston-model engine for European options.
class MakeMCEuropeanHestonEngine
Monte Carlo Heston European engine factory.
class EuropeanHestonPathPricer
class MCHestonHullWhiteEngine
class MakeMCHestonHullWhiteEngine
Monte Carlo Heston/Hull-White engine factory.
class HestonHullWhitePathPricer
class MCVanillaEngine
Pricing engine for vanilla options using Monte Carlo simulation.
class BatesProcess
Square-root stochastic-volatility Bates process.
class GeneralizedBlackScholesProcess
Generalized Black-Scholes stochastic process.
class BlackScholesProcess
Black-Scholes (1973) stochastic process.
class BlackScholesMertonProcess
Merton (1973) extension to the Black-Scholes stochastic process.
class BlackProcess
Black (1976) stochastic process.
class GarmanKohlagenProcess
Garman-Kohlhagen (1983) stochastic process.
class EndEulerDiscretization
Euler end-point discretization for stochastic processes.
class EulerDiscretization
Euler discretization for stochastic processes.
class ForwardMeasureProcess
forward-measure stochastic process
class ForwardMeasureProcess1D
forward-measure 1-D stochastic process
class G2Process
G2 stochastic process
class G2ForwardProcess
Forward G2 stochastic process
class GeometricBrownianMotionProcess
Geometric brownian-motion process.
class GJRGARCHProcess
Stochastic-volatility GJR-GARCH(1,1) process.
class HestonProcess
Square-root stochastic-volatility Heston process.
class HullWhiteProcess
Hull-White stochastic process.
class HullWhiteForwardProcess
Forward Hull-White stochastic process
class HybridHestonHullWhiteProcess
Hybrid Heston Hull-White stochastic process.
class JointStochasticProcess
class Merton76Process
Merton-76 jump-diffusion process.
class OrnsteinUhlenbeckProcess
Ornstein-Uhlenbeck process class.
class SquareRootProcess
Square-root process class.
class StochasticProcessArray
Array of correlated 1-D stochastic processes
class Quote
purely virtual base class for market observables
class CompositeQuote
market element whose value depends on two other market element
class DerivedQuote
market quote whose value depends on another quote
class EurodollarFuturesImpliedStdDevQuote
quote for the Eurodollar-future implied standard deviation
class ForwardSwapQuote
Quote for a forward starting swap.
class ForwardValueQuote
quote for the forward value of an index
class FuturesConvAdjustmentQuote
quote for the futures-convexity adjustment of an index
class ImpliedStdDevQuote
quote for the implied standard deviation of an underlying
class LastFixingQuote
Quote adapter for the last fixing available of a given Index.
class SimpleQuote
market element returning a stored value
class Settings
global repository for run-time library settings
class SavedSettings
class StochasticProcess
multi-dimensional stochastic process class.
class StochasticProcess1D
1-dimensional stochastic process
class TermStructure
Basic term-structure functionality.
class BootstrapError
bootstrap error
class BootstrapHelper
Base helper class for bootstrapping.
class RelativeDateBootstrapHelper
Bootstrap helper with date schedule relative to global evaluation date.
class DefaultDensityStructure
Default-density term structure.
class CdsHelper
class SpreadCdsHelper
Spread-quoted CDS hazard rate bootstrap helper.
class UpfrontCdsHelper
Upfront-quoted CDS hazard rate bootstrap helper.
class FlatHazardRate
Flat hazard-rate curve.
class HazardRateStructure
Hazard-rate term structure.
class InterpolatedDefaultDensityCurve
DefaultProbabilityTermStructure based on interpolation of default densities.
class InterpolatedHazardRateCurve
DefaultProbabilityTermStructure based on interpolation of hazard rates.
class InterpolatedSurvivalProbabilityCurve
DefaultProbabilityTermStructure based on interpolation of survival probabilities.
class PiecewiseDefaultCurve
Piecewise default-probability term structure.
struct SurvivalProbability
Survival-Probability-curve traits.
struct HazardRate
Hazard-rate-curve traits.
struct DefaultDensity
Default-density-curve traits.
class SurvivalProbabilityStructure
Hazard-rate term structure.
class DefaultProbabilityTermStructure
Default probability term structure.
class ZeroCouponInflationSwapHelper
Zero-coupon inflation-swap bootstrap helper.
class YearOnYearInflationSwapHelper
Year-on-year inflation-swap bootstrap helper.
class ZeroInflationTraits
Bootstrap traits to use for PiecewiseZeroInflationCurve.
class YoYInflationTraits
Bootstrap traits to use for PiecewiseZeroInflationCurve.
class InterpolatedYoYInflationCurve
Inflation term structure based on interpolated year-on-year rates.
class InterpolatedZeroInflationCurve
Inflation term structure based on the interpolation of zero rates.
class PiecewiseYoYInflationCurve
Piecewise year-on-year inflation term structure.
class PiecewiseZeroInflationCurve
Piecewise zero-inflation term structure.
class Seasonality
A transformation of an existing inflation swap rate.
class MultiplicativePriceSeasonality
Multiplicative seasonality in the price index (CPI/RPI/HICP/etc).
class InflationTermStructure
Interface for inflation term structures.
class ZeroInflationTermStructure
Interface for zero inflation term structures.
class YoYInflationTermStructure
Base class for year-on-year inflation term structures.
class InterpolatedCurve
Helper class to build interpolated term structures.
class IterativeBootstrap
Universal piecewise-term-structure boostrapper.
class PenaltyFunction
class LocalBootstrap
Localised-term-structure bootstrapper for most curve types.
class AbcdFunction
Abcd functional form for instantaneous volatility
class AbcdSquared
class AbcdCalibration
class CapFloorTermVolatilityStructure
Cap/floor term-volatility structure.
class CapFloorTermVolCurve
Cap/floor at-the-money term-volatility vector.
class CapFloorTermVolSurface
Cap/floor smile volatility surface.
class ConstantCapFloorTermVolatility
Constant caplet volatility, no time-strike dependence.
class BlackConstantVol
Constant Black volatility, no time-strike dependence.
class BlackVarianceCurve
Black volatility curve modelled as variance curve.
class BlackVarianceSurface
Black volatility surface modelled as variance surface.
class BlackVolTermStructure
Black-volatility term structure.
class BlackVolatilityTermStructure
Black-volatility term structure.
class BlackVarianceTermStructure
Black variance term structure.
class ImpliedVolTermStructure
Implied vol term structure at a given date in the future.
class LocalConstantVol
Constant local volatility, no time-strike dependence.
class LocalVolCurve
Local volatility curve derived from a Black curve.
class LocalVolSurface
Local volatility surface derived from a Black vol surface.
class LocalVolTermStructure
class FlatSmileSection
class ConstantCPIVolatility
Constant surface, no K or T dependence.
class CPIVolatilitySurface
zero inflation (i.e. CPI/RPI/HICP/etc.) volatility structures
class YoYOptionletVolatilitySurface
class ConstantYoYOptionletVolatility
Constant surface, no K or T dependence.
class InterpolatedSmileSection
class CapletVarianceCurve
class ConstantOptionletVolatility
Constant caplet volatility, no time-strike dependence.
class OptionletStripper
class OptionletStripper1
class OptionletStripper2
class OptionletVolatilityStructure
Optionlet (caplet/floorlet) volatility structure.
class SpreadedOptionletVolatility
class StrippedOptionlet
class StrippedOptionletAdapter
class StrippedOptionletBase
class SabrInterpolatedSmileSection
class SabrSmileSection
class SmileSection
interest rate volatility smile section
class SpreadedSmileSection
class CmsMarket
set of CMS quotes
class CmsMarketCalibration
class SpreadedSwaptionVolatility
class ConstantSwaptionVolatility
Constant swaption volatility, no time-strike dependence.
class SwaptionVolatilityCube
swaption-volatility cube
class SwaptionVolCube1
class SwaptionVolCube2
class SwaptionVolatilityDiscrete
class SwaptionVolatilityMatrix
At-the-money swaption-volatility matrix.
class SwaptionVolatilityStructure
Swaption-volatility structure
class VolatilityTermStructure
Volatility term structure.
class BondHelper
fixed-coupon bond helper
class FixedRateBondHelper
struct Discount
Discount-curve traits.
struct ZeroYield
Zero-curve traits.
struct ForwardRate
Forward-curve traits.
class InterpolatedDiscountCurve
YieldTermStructure based on interpolation of discount factors.
class DriftTermStructure
Drift term structure.
class FittedBondDiscountCurve
Discount curve fitted to a set of fixed-coupon bonds.
class FlatForward
Flat interest-rate curve.
class InterpolatedForwardCurve
YieldTermStructure based on interpolation of forward rates.
class ForwardSpreadedTermStructure
Term structure with added spread on the instantaneous forward rate.
class ForwardRateStructure
Forward-rate term structure
class ImpliedTermStructure
Implied term structure at a given date in the future.
class ExponentialSplinesFitting
Exponential-splines fitting method.
class NelsonSiegelFitting
Nelson-Siegel fitting method.
class SvenssonFitting
Svensson Fitting method.
class CubicBSplinesFitting
CubicSpline B-splines fitting method.
class SimplePolynomialFitting
Simple polynomial fitting method.
class OISRateHelper
Rate helper for bootstrapping over Overnight Indexed Swap rates.
class DatedOISRateHelper
Rate helper for bootstrapping over Overnight Indexed Swap rates.
class PiecewiseYieldCurve
Piecewise yield term structure.
class PiecewiseZeroSpreadedTermStructure
Term structure with an added vector of spreads on the zero-yield rate.
class QuantoTermStructure
Quanto term structure.
class FuturesRateHelper
Rate helper for bootstrapping over IborIndex futures prices.
class DepositRateHelper
Rate helper for bootstrapping over deposit rates.
class FraRateHelper
Rate helper for bootstrapping over FRA rates.
class SwapRateHelper
Rate helper for bootstrapping over swap rates.
class BMASwapRateHelper
Rate helper for bootstrapping over BMA swap rates.
class InterpolatedZeroCurve
YieldTermStructure based on interpolation of zero rates.
class ZeroSpreadedTermStructure
Term structure with an added spread on the zero yield rate.
class ZeroYieldStructure
Zero-yield term structure.
class YieldTermStructure
Interest-rate term structure.
class Calendar
calendar class
class Argentina
Argentinian calendars.
class Australia
Australian calendar.
class BespokeCalendar
Bespoke calendar.
class Brazil
Brazilian calendar.
class Canada
Canadian calendar.
class China
Chinese calendar.
class CzechRepublic
Czech calendars.
class Denmark
Danish calendar.
class Finland
Finnish calendar.
class Germany
German calendars.
class HongKong
Hong Kong calendars.
class Hungary
Hungarian calendar.
class Iceland
Icelandic calendars.
class India
Indian calendars.
class Indonesia
Indonesian calendars
class Italy
Italian calendars.
class Japan
Japanese calendar.
class JointCalendar
Joint calendar.
class Mexico
Mexican calendars
class NewZealand
New Zealand calendar.
class Norway
Norwegian calendar.
class NullCalendar
Calendar for reproducing theoretical calculations.
class Poland
Polish calendar.
class Russia
Russian calendar.
class SaudiArabia
Saudi Arabian calendar.
class Singapore
Singapore calendars
class Slovakia
Slovak calendars.
class SouthAfrica
South-African calendar.
class SouthKorea
South Korean calendars.
class Sweden
Swedish calendar.
class Switzerland
Swiss calendar.
class Taiwan
Taiwanese calendars.
class TARGET
TARGET calendar
class Turkey
Turkish calendar.
class Ukraine
Ukrainian calendars.
class UnitedKingdom
United Kingdom calendars.
class UnitedStates
United States calendars.
class WeekendsOnly
Weekends-only calendar.
class Date
Concrete date class.
class Null< Date >
specialization of Null template for the Date class
struct DateGeneration
Date-generation rule.
class DayCounter
day counter class
class Actual360
Actual/360 day count convention.
class Actual365Fixed
Actual/365 (Fixed) day count convention.
class ActualActual
Actual/Actual day count.
class Business252
Business/252 day count convention.
class OneDayCounter
1/1 day count convention
class SimpleDayCounter
Simple day counter for reproducing theoretical calculations.
class Thirty360
30/360 day count convention
struct ECB
European Central Bank reserve maintenance dates.
struct IMM
Main cycle of the International Money Market (a.k.a. IMM) months.
class Period
class Schedule
Payment schedule.
class MakeSchedule
helper class
class TimeGrid
time grid class
class TimeSeries
Container for historical data.
class Clone
cloning proxy to an underlying object
class PeriodParser
class DateParser
class Disposable
generic disposable object with move semantics
class Null
class ObservableValue
observable and assignable proxy to concrete value
class step_iterator
Iterator advancing in constant steps.
class LocalVolatilityEstimator
class VolatilityCompositor
struct SwaptionTenors
struct SwaptionMarketConventions
struct AtmVolatility
class Flag
class IndexHistoryCleaner
Typedefs
typedef std::vector
< boost::shared_ptr< CashFlow > > Leg
Sequence of cash-flows.
typedef std::map< std::string,
boost::any > SecondaryCosts
typedef std::map< std::string,
Money > SecondaryCostAmounts
typedef std::vector< PricingError > PricingErrors
typedef std::map< Date,
boost::shared_ptr
< CommodityCashFlow > > CommodityCashFlows
typedef std::map< Date,
EnergyDailyPosition > EnergyDailyPositions
typedef std::map< Date,
ExchangeContract > ExchangeContracts
typedef std::vector
< boost::shared_ptr
< PricingPeriod > > PricingPeriods
typedef std::set
< boost::shared_ptr
< DefaultEvent >, earlier_than
< boost::shared_ptr
< DefaultEvent > > > DefaultEventSet
typedef
GaussianRecursiveCdoEngine
< MidPointCDOEngine > GaussRecCDOEngine
typedef
StudentRecursiveCdoEngine
< MidPointCDOEngine > StudentRecCDOEngine
typedef
HomogeneousPoolCDOEngine
< MidPointCDOEngine > HPMidPointCDOEngine
typedef
HomogeneousPoolCDOEngine
< IntegralCDOEngine > HPIntegralCDOEngine
typedef
InhomogeneousPoolCDOEngine
< MidPointCDOEngine > IHPMidPointCDOEngine
typedef
InhomogeneousPoolCDOEngine
< IntegralCDOEngine > IHPIntegralCDOEngine
typedef GaussianLHPCDOEngine
< MidPointCDOEngine > GLHPMidPointCDOEngine
typedef GaussianLHPCDOEngine
< IntegralCDOEngine > GLHPIntegralCDOEngine
typedef std::vector
< boost::shared_ptr
< Callability > > CallabilitySchedule
typedef std::vector
< boost::shared_ptr< Dividend > > DividendSchedule
typedef
BivariateCumulativeNormalDistributionWe04DP BivariateCumulativeNormalDistribution
default bivariate implementation
typedef NormalDistribution GaussianDistribution
typedef InverseCumulativeNormal InvCumulativeNormalDistribution
typedef detail::SplineGrid SplineGrid
typedef
boost::numeric::ublas::compressed_matrix
< Real > SparseMatrix
typedef GenericPseudoRandom
< MersenneTwisterUniformRng,
InverseCumulativeNormal > PseudoRandom
default traits for pseudo-random number generation
typedef GenericPseudoRandom
< MersenneTwisterUniformRng,
InverseCumulativePoisson > PoissonPseudoRandom
traits for Poisson-distributed pseudo-random number generation
typedef GenericLowDiscrepancy
< SobolRsg,
InverseCumulativeNormal > LowDiscrepancy
default traits for low-discrepancy sequence generation
typedef SampledCurve SampledCurveSet
typedef
GenericGaussianStatistics
< GeneralStatistics > GaussianStatistics
default gaussian statistic tool
typedef GenericRiskStatistics
< GaussianStatistics > RiskStatistics
default risk measures tool
typedef
GenericSequenceStatistics
< Statistics > SequenceStatistics
default multi-dimensional statistics tool
typedef
GenericSequenceStatistics
< IncrementalStatistics > SequenceStatisticsInc
typedef RiskStatistics Statistics
default statistics tool
typedef PdeOperator< PdeBSM > BSMTermOperator
Black-Scholes-Merton differential operator.
typedef FiniteDifferenceModel
< CrankNicolson
< TridiagonalOperator > > StandardFiniteDifferenceModel
default choice for finite-difference model
typedef FiniteDifferenceModel
< ParallelEvolver
< CrankNicolson
< TridiagonalOperator > > > StandardSystemFiniteDifferenceModel
default choice for parallel finite-difference model
typedef StepCondition< Array > StandardStepCondition
default choice for step condition
typedef
CurveDependentStepCondition
< Array > StandardCurveDependentStepCondition
typedef PdeOperator< PdeShortRate > OneFactorOperator
Interest-rate single factor model differential operator.
typedef OperatorTraits
< FdmLinearOp >::bc_set FdmBoundaryConditionSet
typedef
MarketModelMultiProduct::CashFlow CashFlow
typedef BootstrapHelper
< DefaultProbabilityTermStructure > DefaultProbabilityHelper
alias for default-probability bootstrap helpers
typedef
RelativeDateBootstrapHelper
< DefaultProbabilityTermStructure > RelativeDateDefaultProbabilityHelper
typedef Real Probability
probability
typedef
InterpolatedYoYInflationCurve
< Linear > YoYInflationCurve
typedef
InterpolatedZeroInflationCurve
< Linear > ZeroInflationCurve
typedef std::vector
< std::vector
< boost::shared_ptr< CapFloor > > > CapFloorMatrix
typedef
InterpolatedDiscountCurve
< LogLinear > DiscountCurve
Term structure based on log-linear interpolation of discount factors.
typedef
InterpolatedForwardCurve
< BackwardFlat > ForwardCurve
Term structure based on flat interpolation of forward rates.
typedef BootstrapHelper
< YieldTermStructure > RateHelper
typedef
RelativeDateBootstrapHelper
< YieldTermStructure > RelativeDateRateHelper
typedef InterpolatedZeroCurve
< Linear > ZeroCurve
Term structure based on linear interpolation of zero yields.
typedef Integer Day
Day number.
typedef Integer Year
Year number.
typedef QL_INTEGER Integer
integer number
typedef QL_BIG_INTEGER BigInteger
large integer number
typedef unsigned QL_INTEGER Natural
positive integer
typedef unsigned QL_BIG_INTEGER BigNatural
large positive integer
typedef QL_REAL Real
real number
typedef Real Decimal
decimal number
typedef std::size_t Size
size of a container
typedef Real Time
continuous quantity with 1-year units
typedef Real DiscountFactor
discount factor between dates
typedef Real Rate
interest rates
typedef Real Spread
spreads on interest rates
typedef Real Volatility
volatility
Enumerations
enum Compounding { Simple = 0, Compounded = 1, Continuous = 2, SimpleThenCompounded }
Interest rate coumpounding rule.
enum Seniority {
SecDom = 0, SnrFor, SubLT2, JrSubT2,
PrefT1, NoSeniority, SeniorSec = SecDom, SeniorUnSec = SnrFor,
SubTier1 = PrefT1, SubUpperTier2 = JrSubT2, SubLoweTier2 = SubLT2
}
Seniority of a bond.
enum SensitivityAnalysis { OneSide, Centered }
Finite differences calculation.
enum PriceType {
Bid, Ask, Last, Close,
Mid, MidEquivalent, MidSafe
}
Price types.
enum BusinessDayConvention {
Following, ModifiedFollowing, Preceding, ModifiedPreceding,
Unadjusted
}
Business Day conventions.
enum JointCalendarRule { JoinHolidays, JoinBusinessDays }
rules for joining calendars
enum Month {
January = 1, February = 2, March = 3, April = 4,
May = 5, June = 6, July = 7, August = 8,
September = 9, October = 10, November = 11, December = 12,
Jan = 1, Feb = 2, Mar = 3, Apr = 4,
Jun = 6, Jul = 7, Aug = 8, Sep = 9,
Oct = 10, Nov = 11, Dec = 12
}
Month names.
enum Frequency {
NoFrequency = -1, Once = 0, Annual = 1, Semiannual = 2,
EveryFourthMonth = 3, Quarterly = 4, Bimonthly = 6, Monthly = 12,
EveryFourthWeek = 13, Biweekly = 26, Weekly = 52, Daily = 365,
OtherFrequency = 999
}
Frequency of events.
enum TimeUnit { Days, Weeks, Months, Years }
Units used to describe time periods.
enum Weekday {
Sunday = 1, Monday = 2, Tuesday = 3, Wednesday = 4,
Thursday = 5, Friday = 6, Saturday = 7, Sun = 1,
Mon = 2, Tue = 3, Wed = 4, Thu = 5,
Fri = 6, Sat = 7
}
Functions
template<typename InterestRateIndexType , typename FloatingCouponType , typename CappedFlooredCouponType >
Leg FloatingLeg (const Schedule &schedule, const std::vector< Real > &nominals, const boost::shared_ptr< InterestRateIndexType > &index, const DayCounter &paymentDayCounter, BusinessDayConvention paymentAdj, const std::vector< Natural > &fixingDays, const std::vector< Real > &gearings, const std::vector< Spread > &spreads, const std::vector< Rate > &caps, const std::vector< Rate > &floors, bool isInArrears, bool isZero)
template<typename InterestRateIndexType , typename FloatingCouponType , typename DigitalCouponType >
Leg FloatingDigitalLeg (const Schedule &schedule, const std::vector< Real > &nominals, const boost::shared_ptr< InterestRateIndexType > &index, const DayCounter &paymentDayCounter, BusinessDayConvention paymentAdj, const std::vector< Natural > &fixingDays, const std::vector< Real > &gearings, const std::vector< Spread > &spreads, bool isInArrears, const std::vector< Rate > &callStrikes, Position::Type callPosition, bool isCallATMIncluded, const std::vector< Rate > &callDigitalPayoffs, const std::vector< Rate > &putStrikes, Position::Type putPosition, bool isPutATMIncluded, const std::vector< Rate > &putDigitalPayoffs, const boost::shared_ptr< DigitalReplication > &replication)
std::ostream & operator<< (std::ostream &out, GFunctionFactory::YieldCurveModel type)
void setCouponPricer (const Leg &leg, const boost::shared_ptr< FloatingRateCouponPricer > &pricer)
void setCouponPricers (const Leg &leg, const std::vector< boost::shared_ptr< FloatingRateCouponPricer > > &pricers)
std::vector< boost::shared_ptr
< Dividend > > DividendVector (const std::vector< Date > &dividendDates, const std::vector< Real > &dividends)
helper function building a sequence of fixed dividends
std::ostream & operator<< (std::ostream &out, Duration::Type d)
std::ostream & operator<< (std::ostream &out, Replication::Type r)
std::ostream & operator<< (std::ostream &out, const Currency &c)
bool operator== (const Currency &c1, const Currency &c2)
bool operator!= (const Currency &c1, const Currency &c2)
std::ostream & operator<< (std::ostream &out, const SecondaryCostAmounts &secondaryCostAmounts)
std::ostream & operator<< (std::ostream &out, const PricingError &error)
std::ostream & operator<< (std::ostream &out, const PricingErrors &errors)
std::ostream & operator<< (std::ostream &out, const CommodityCurve &curve)
bool operator== (const CommodityCurve &c1, const CommodityCurve &c2)
std::ostream & operator<< (std::ostream &out, const CommodityIndex &index)
bool operator== (const CommodityIndex &i1, const CommodityIndex &i2)
std::ostream & operator<< (std::ostream &out, const CommodityType &c)
bool operator== (const CommodityType &c1, const CommodityType &c2)
bool operator!= (const CommodityType &c1, const CommodityType &c2)
std::ostream & operator<< (std::ostream &out, const CommodityUnitCost &unitCost)
std::ostream & operator<< (std::ostream &out, const DateInterval &di)
std::ostream & operator<< (std::ostream &out, const PaymentTerm &c)
bool operator== (const PaymentTerm &c1, const PaymentTerm &c2)
bool operator!= (const PaymentTerm &c1, const PaymentTerm &c2)
Real operator/ (const Quantity &m1, const Quantity &m2)
bool operator== (const Quantity &m1, const Quantity &m2)
bool operator< (const Quantity &m1, const Quantity &m2)
bool operator<= (const Quantity &m1, const Quantity &m2)
bool close (const Quantity &m1, const Quantity &m2, Size n)
bool close_enough (const Quantity &m1, const Quantity &m2, Size n)
std::ostream & operator<< (std::ostream &out, const Quantity &quantity)
Quantity operator+ (const Quantity &m1, const Quantity &m2)
Quantity operator- (const Quantity &m1, const Quantity &m2)
Quantity operator* (const Quantity &m, Real x)
Quantity operator* (Real x, const Quantity &m)
Quantity operator/ (const Quantity &m, Real x)
bool operator!= (const Quantity &m1, const Quantity &m2)
bool operator> (const Quantity &m1, const Quantity &m2)
bool operator>= (const Quantity &m1, const Quantity &m2)
std::ostream & operator<< (std::ostream &out, const UnitOfMeasure &c)
bool operator== (const UnitOfMeasure &c1, const UnitOfMeasure &c2)
bool operator!= (const UnitOfMeasure &c1, const UnitOfMeasure &c2)
bool operator== (const DefaultEvent &lhs, const DefaultEvent &rhs)
bool operator!= (const DefaultEvent &lhs, const DefaultEvent &rhs)
bool operator== (const DefaultProbKey &lhs, const DefaultProbKey &rhs)
bool operator== (const DefaultType &lhs, const DefaultType &rhs)
bool operator< (const Loss &l1, const Loss &l2)
bool operator> (const Loss &l1, const Loss &l2)
bool operator== (const Loss &l1, const Loss &l2)
bool operator!= (const Loss &l1, const Loss &l2)
std::map< Seniority, Real > makeIsdaConvMap ()
Helper function for conventional recoveries. Returns the ISDA.
template<typename ForwardIterator , typename OutputIterator >
void convolutions (ForwardIterator begin, ForwardIterator end, OutputIterator out, std::size_t maxLag)
Convolutions of the input sequence.
template<typename ForwardIterator , typename OutputIterator >
void autocovariances (ForwardIterator begin, ForwardIterator end, OutputIterator out, std::size_t maxLag)
Unbiased auto-covariances.
template<typename ForwardIterator , typename OutputIterator >
Real autocovariances (ForwardIterator begin, ForwardIterator end, OutputIterator out, std::size_t maxLag, bool reuse)
Unbiased auto-covariances.
template<typename ForwardIterator , typename OutputIterator >
void autocorrelations (ForwardIterator begin, ForwardIterator end, OutputIterator out, std::size_t maxLag)
Unbiased auto-correlations.
template<typename ForwardIterator , typename OutputIterator >
Real autocorrelations (ForwardIterator begin, ForwardIterator end, OutputIterator out, std::size_t maxLag, bool reuse)
Unbiased auto-correlations.
const Disposable< ComplexArray > operator+ (const ComplexArray &v)
const Disposable< ComplexArray > operator- (const ComplexArray &v)
const Disposable< ComplexArray > operator+ (const ComplexArray &v1, const ComplexArray &v2)
const Disposable< ComplexArray > operator+ (const ComplexArray &v1, std::complex< Real > a)
const Disposable< ComplexArray > operator+ (std::complex< Real > a, const ComplexArray &v2)
const Disposable< ComplexArray > operator- (const ComplexArray &v1, const ComplexArray &v2)
const Disposable< ComplexArray > operator- (const ComplexArray &v1, std::complex< Real > a)
const Disposable< ComplexArray > operator- (std::complex< Real > a, const ComplexArray &v2)
const Disposable< ComplexArray > operator* (const ComplexArray &v1, const ComplexArray &v2)
const Disposable< ComplexArray > operator* (const ComplexArray &v1, std::complex< Real > a)
const Disposable< ComplexArray > operator* (std::complex< Real > a, const ComplexArray &v2)
const Disposable< ComplexArray > operator/ (const ComplexArray &v1, const ComplexArray &v2)
const Disposable< ComplexArray > operator/ (const ComplexArray &v1, std::complex< Real > a)
const Disposable< ComplexArray > operator/ (std::complex< Real > a, const ComplexArray &v2)
void swap (ComplexArray &v, ComplexArray &w)
std::ostream & operator<< (std::ostream &out, const ComplexArray &a)
std::ostream & operator<< (std::ostream &out, SensitivityAnalysis s)
Real aggregateNPV (const vector< shared_ptr< Instrument > > &instruments, const vector< Real > &quant)
pair< Real, Real > parallelAnalysis (const vector< Handle< SimpleQuote > > &quotes, const vector< shared_ptr< Instrument > > &instruments, const vector< Real > &quantities, Real shift, SensitivityAnalysis type, Real referenceNpv)
pair< Real, Real > bucketAnalysis (Handle< SimpleQuote > quote, const vector< shared_ptr< Instrument > > &instruments, const vector< Real > &quantities, Real shift, SensitivityAnalysis type, Real referenceNpv)
void bucketAnalysis (std::vector< Real > &deltaVector,std::vector< Real > &gammaVector,std::vector< Real > &referenceValues, Handle< SimpleQuote > quote, const std::vector< Handle< Quote > > &parameters, Real shift=0.0001, SensitivityAnalysis type=Centered)
(bucket) parameters' sensitivity analysis for a (single) SimpleQuote
pair< vector< Real >, vector
< Real > > bucketAnalysis (const vector< Handle< SimpleQuote > > &quotes, const vector< shared_ptr< Instrument > > &instr, const vector< Real > &quant, Real shift, SensitivityAnalysis type)
void bucketAnalysis (std::vector< std::vector< Real > > &deltaMatrix,std::vector< std::vector< Real > > &gammaMatrix,const std::vector< Handle< SimpleQuote > > &quotes, const std::vector< Handle< Quote > > &parameters, Real shift=0.0001, SensitivityAnalysis type=Centered)
bucket parameters' sensitivity analysis for a SimpleQuote vector
pair< vector< vector< Real >
>, vector< vector< Real > > > bucketAnalysis (const vector< vector< Handle< SimpleQuote > > > &quotes, const vector< shared_ptr< Instrument > > &instr, const vector< Real > &quant, Real shift, SensitivityAnalysis type)
Real aggregateNPV (const std::vector< boost::shared_ptr< Instrument > > &, const std::vector< Real > &quantities)
utility fuction for weighted sum of NPVs
std::pair< Real, Real > parallelAnalysis (const std::vector< Handle< SimpleQuote > > &, const std::vector< boost::shared_ptr< Instrument > > &, const std::vector< Real > &quantities, Real shift=0.0001, SensitivityAnalysis type=Centered, Real referenceNpv=Null< Real >())
parallel shift PV01 sensitivity analysis for a SimpleQuote vector
std::pair< Real, Real > parallelAnalysis (const std::vector< std::vector< Handle< SimpleQuote > > > &, const std::vector< boost::shared_ptr< Instrument > > &, const std::vector< Real > &quantities, Real shift=0.0001, SensitivityAnalysis type=Centered, Real referenceNpv=Null< Real >())
parallel shift PV01 sensitivity analysis for a SimpleQuote matrix
std::pair< Real, Real > bucketAnalysis (Handle< SimpleQuote > quote, const std::vector< boost::shared_ptr< Instrument > > &, const std::vector< Real > &quantities, Real shift=0.0001, SensitivityAnalysis type=Centered, Real referenceNpv=Null< Real >())
(bucket) PV01 sensitivity analysis for a (single) SimpleQuote
std::pair< std::vector< Real >
, std::vector< Real > > bucketAnalysis (const std::vector< Handle< SimpleQuote > > &quotes, const std::vector< boost::shared_ptr< Instrument > > &, const std::vector< Real > &quantities, Real shift=0.0001, SensitivityAnalysis type=Centered)
bucket PV01 sensitivity analysis for a SimpleQuote vector
std::pair< std::vector
< std::vector< Real >
>, std::vector< std::vector
< Real > > > bucketAnalysis (const std::vector< std::vector< Handle< SimpleQuote > > > &, const std::vector< boost::shared_ptr< Instrument > > &, const std::vector< Real > &quantities, Real shift=0.0001, SensitivityAnalysis type=Centered)
bucket sensitivity analysis for a SimpleQuote matrix
Real fInverse_ (Real x)
Disposable< Array > CenteredGrid (Real center, Real dx, Size steps)
Disposable< Array > BoundedGrid (Real xMin, Real xMax, Size steps)
Disposable< Array > BoundedLogGrid (Real xMin, Real xMax, Size steps)
bool operator== (const Region &r1, const Region &r2)
bool operator!= (const Region &r1, const Region &r2)
std::ostream & operator<< (std::ostream &out, Average::Type type)
std::ostream & operator<< (std::ostream &out, Barrier::Type type)
std::ostream & operator<< (std::ostream &out, CapFloor::Type t)
std::ostream & operator<< (std::ostream &out, CPISwap::Type t)
std::ostream & operator<< (std::ostream &out, YoYInflationCapFloor::Type t)
std::ostream & operator<< (std::ostream &out, Settlement::Type t)
std::ostream & operator<< (std::ostream &out, VanillaSwap::Type t)
std::ostream & operator<< (std::ostream &out, YearOnYearInflationSwap::Type t)
std::ostream & operator<< (std::ostream &out, const InterestRate &ir)
Real DotProduct (const Array &v1, const Array &v2)
const Disposable< Array > operator+ (const Array &v)
const Disposable< Array > operator- (const Array &v)
const Disposable< Array > operator+ (const Array &v1, const Array &v2)
const Disposable< Array > operator+ (const Array &v1, Real a)
const Disposable< Array > operator+ (Real a, const Array &v2)
const Disposable< Array > operator- (const Array &v1, const Array &v2)
const Disposable< Array > operator- (const Array &v1, Real a)
const Disposable< Array > operator- (Real a, const Array &v2)
const Disposable< Array > operator* (const Array &v1, const Array &v2)
const Disposable< Array > operator* (const Array &v1, Real a)
const Disposable< Array > operator* (Real a, const Array &v2)
const Disposable< Array > operator/ (const Array &v1, const Array &v2)
const Disposable< Array > operator/ (const Array &v1, Real a)
const Disposable< Array > operator/ (Real a, const Array &v2)
const Disposable< Array > Abs (const Array &v)
const Disposable< Array > Sqrt (const Array &v)
const Disposable< Array > Log (const Array &v)
const Disposable< Array > Exp (const Array &v)
void swap (Array &v, Array &w)
std::ostream & operator<< (std::ostream &out, const Array &a)
Real betaContinuedFraction (Real a, Real b, Real x, Real accuracy, Integer maxIteration)
Real incompleteBetaFunction (Real a, Real b, Real x, Real accuracy=1e-16, Integer maxIteration=100)
Incomplete Beta function.
Real betaFunction (Real z, Real w)
bool close (Real x, Real y)
bool close (Real x, Real y, Size n)
bool close_enough (Real x, Real y)
bool close_enough (Real x, Real y, Size n)
Real binomialCoefficientLn (BigNatural n, BigNatural k)
Real binomialCoefficient (BigNatural n, BigNatural k)
Real PeizerPrattMethod2Inversion (Real z, BigNatural n)
template<class F , class R >
clipped_function< F, R > clip (const F &f, const R &r)
template<class F , class G >
composed_function< F, G > compose (const F &f, const G &g)
template<class F , class G , class H >
binary_compose3_function< F, G, H > compose3 (const F &f, const G &g, const H &h)
Real incompleteGammaFunction (Real a, Real x, Real accuracy=1.0e-13, Integer maxIteration=100)
Incomplete Gamma function.
Real incompleteGammaFunctionSeriesRepr (Real a, Real x, Real accuracy, Integer maxIteration)
Real incompleteGammaFunctionContinuedFractionRepr (Real a, Real x, Real accuracy, Integer maxIteration)
static Real rescaleError (Real err, const Real resultAbs, const Real resultAsc)
Disposable< Matrix > inverse (const Matrix &m)
Real determinant (const Matrix &m)
const Disposable< Matrix > operator+ (const Matrix &m1, const Matrix &m2)
const Disposable< Matrix > operator- (const Matrix &m1, const Matrix &m2)
const Disposable< Matrix > operator* (const Matrix &m, Real x)
const Disposable< Matrix > operator* (Real x, const Matrix &m)
const Disposable< Matrix > operator/ (const Matrix &m, Real x)
const Disposable< Array > operator* (const Array &v, const Matrix &m)
const Disposable< Array > operator* (const Matrix &m, const Array &v)
const Disposable< Matrix > operator* (const Matrix &m1, const Matrix &m2)
const Disposable< Matrix > transpose (const Matrix &m)
const Disposable< Matrix > outerProduct (const Array &v1, const Array &v2)
template<class Iterator1 , class Iterator2 >
const Disposable< Matrix > outerProduct (Iterator1 v1begin, Iterator1 v1end, Iterator2 v2begin, Iterator2 v2end)
void swap (Matrix &m1, Matrix &m2)
std::ostream & operator<< (std::ostream &out, const Matrix &m)
const Disposable< Matrix > CholeskyDecomposition (const Matrix &S, bool flexible)
Disposable< std::vector< Real > > factorReduction (Matrix mtrx, Size maxIters)
template<class DataIterator >
Disposable< Matrix > getCovariance (DataIterator stdDevBegin, DataIterator stdDevEnd, const Matrix &corr, Real tolerance=1.0e-12)
Calculation of covariance from correlation and standard deviations.
const Disposable< Matrix > pseudoSqrt (const Matrix &matrix, SalvagingAlgorithm::Type sa)
const Disposable< Matrix > rankReducedSqrt (const Matrix &matrix, Size maxRank, Real componentRetainedPercentage, SalvagingAlgorithm::Type sa)
Disposable< std::vector< Size > > qrDecomposition (const Matrix &A, Matrix &q, Matrix &r, bool pivot=true)
QR decompoisition.
Disposable< Array > qrSolve (const Matrix &a, const Array &b, bool pivot=true, const Array &d=Array())
QR Solve.
Disposable< Array > prod (const SparseMatrix &A, const Array &x)
Disposable< Matrix > triangularAnglesParametrization (const Array &angles, Size matrixSize, Size rank)
Returns the Triangular Angles Parametrized correlation matrix.
Disposable< Matrix > lmmTriangularAnglesParametrization (const Array &angles, Size matrixSize, Size rank)
Disposable< Matrix > triangularAnglesParametrizationUnconstrained (const Array &x, Size matrixSize, Size rank)
Disposable< Matrix > lmmTriangularAnglesParametrizationUnconstrained (const Array &x, Size matrixSize, Size rank)
Disposable< Matrix > triangularAnglesParametrizationRankThree (Real alpha, Real t0, Real epsilon, Size nbRows)
Returns the rank reduced Triangular Angles Parametrized correlation matrix.
Disposable< Matrix > triangularAnglesParametrizationRankThreeVectorial (const Array &parameters, Size nbRows)
std::ostream & operator<< (std::ostream &out, EndCriteria::Type ec)
std::vector< Real > sphereCylinderOptimizerClosest (Real r, Real s, Real alpha, Real z1, Real z2, Real z3, Natural maxIterations, Real tolerance, Real zweight)
void swap (SampledCurve &, SampledCurve &)
std::ostream & operator<< (std::ostream &out, const SampledCurve &a)
void swap (TridiagonalOperator &, TridiagonalOperator &)
Disposable< TridiagonalOperator > operator+ (const TridiagonalOperator &D)
Disposable< TridiagonalOperator > operator- (const TridiagonalOperator &D)
Disposable< TridiagonalOperator > operator+ (const TridiagonalOperator &D1, const TridiagonalOperator &D2)
Disposable< TridiagonalOperator > operator- (const TridiagonalOperator &D1, const TridiagonalOperator &D2)
Disposable< TridiagonalOperator > operator* (Real a, const TridiagonalOperator &D)
Disposable< TridiagonalOperator > operator* (const TridiagonalOperator &D, Real a)
Disposable< TridiagonalOperator > operator/ (const TridiagonalOperator &D, Real a)
Real genericLongstaffSchwartzRegression (std::vector< std::vector< NodeData > > &simulationData, std::vector< std::vector< Real > > &basisCoefficients)
returns the biased estimate obtained while regressing
Real genericEarlyExerciseOptimization (std::vector< std::vector< NodeData > > &simulationData, const ParametricExercise &exercise, std::vector< std::vector< Real > > &parameters, const EndCriteria &endCriteria, OptimizationMethod &method)
returns the biased estimate obtained while optimizing
void collectNodeData (MarketModelEvolver &evolver, MarketModelMultiProduct &product, MarketModelNodeDataProvider &dataProvider, MarketModelExerciseValue &rebate, MarketModelExerciseValue &control, Size numberOfPaths, std::vector< std::vector< NodeData > > &collectedData)
Disposable< Matrix > exponentialCorrelations (const std::vector< Time > &rateTimes, Real longTermCorr, Real beta, Real gamma, Time time)
void forwardsFromDiscountRatios (const Size firstValidIndex, const std::vector< DiscountFactor > &ds, const std::vector< Time > &taus, std::vector< Rate > &fwds)
void coterminalFromDiscountRatios (const Size firstValidIndex, const std::vector< DiscountFactor > &discountFactors, const std::vector< Time > &taus, std::vector< Rate > &cotSwapRates, std::vector< Real > &cotSwapAnnuities)
void constantMaturityFromDiscountRatios (const Size spanningForwards, const Size firstValidIndex, const std::vector< DiscountFactor > &ds, const std::vector< Time > &taus, std::vector< Rate > &constMatSwapRates, std::vector< Real > &constMatSwapAnnuities)
void checkCompatibility (const EvolutionDescription &evolution, const std::vector< Size > &numeraires)
bool isInTerminalMeasure (const EvolutionDescription &evolution, const std::vector< Size > &numeraires)
bool isInMoneyMarketPlusMeasure (const EvolutionDescription &evolution, const std::vector< Size > &numeraires, Size offset)
bool isInMoneyMarketMeasure (const EvolutionDescription &evolution, const std::vector< Size > &numeraires)
std::vector< Size > terminalMeasure (const EvolutionDescription &evolution)
Terminal measure: the last bond is used as numeraire.
std::vector< Size > moneyMarketPlusMeasure (const EvolutionDescription &ev, Size offset)
std::vector< Size > moneyMarketMeasure (const EvolutionDescription &evol)
template<class Traits , class Interpolator >
void historicalForwardRatesAnalysis (SequenceStatistics &statistics, std::vector< Date > &skippedDates, std::vector< std::string > &skippedDatesErrorMessage, std::vector< Date > &failedDates, std::vector< std::string > &failedDatesErrorMessage, std::vector< Period > &fixingPeriods, const Date &startDate, const Date &endDate, const Period &step, const boost::shared_ptr< InterestRateIndex > &fwdIndex, const Period &initialGap, const Period &horizon, const std::vector< boost::shared_ptr< IborIndex > > &iborIndexes, const std::vector< boost::shared_ptr< SwapIndex > > &swapIndexes, const DayCounter &yieldCurveDayCounter, Real yieldCurveAccuracy=1.0e-12, const Interpolator &i=Interpolator())
void historicalRatesAnalysis (SequenceStatistics &statistics, std::vector< Date > &skippedDates, std::vector< std::string > &skippedDatesErrorMessage, const Date &startDate, const Date &endDate, const Period &step, const std::vector< boost::shared_ptr< InterestRateIndex > > &indexes)
std::vector< Volatility > rateVolDifferences (const MarketModel &marketModel1, const MarketModel &marketModel2)
std::vector< Spread > rateInstVolDifferences (const MarketModel &marketModel1, const MarketModel &marketModel2, Size index)
std::vector< Matrix > coterminalSwapPseudoRoots (const PiecewiseConstantCorrelation &piecewiseConstantCorrelation, const std::vector< boost::shared_ptr< PiecewiseConstantVariance > > &piecewiseConstantVariances)
std::vector< Real > coterminalSwapPseudoRoots (const PiecewiseConstantCorrelation &, const std::vector< boost::shared_ptr< PiecewiseConstantVariance > > &, const std::vector< Time > &)
Integer capletSwaptionPeriodicCalibration (const EvolutionDescription &evolution, const boost::shared_ptr< PiecewiseConstantCorrelation > &corr, VolatilityInterpolationSpecifier &displacedSwapVariances, const std::vector< Volatility > &capletVols, const boost::shared_ptr< CurveState > &cs, const Spread displacement, Real caplet0Swaption1Priority, Size numberOfFactors, Size period, Size max1dIterations, Real tolerance1d, Size maxUnperiodicIterations, Real toleranceUnperiodic, Size maxPeriodIterations, Real periodTolerance, Real &, Real &totalSwaptionError, std::vector< Matrix > &swapCovariancePseudoRoots, std::vector< Real > &finalScales, Size &iterationsDone, Real &errorImprovement, Matrix &modelSwaptionVolsMatrix)
Real flatVolCovariance (Time t1, Time t2, Time T, Time S, Volatility v1, Volatility v2)
void mergeTimes (const std::vector< std::vector< Time > > &times, std::vector< Time > &mergedTimes, std::vector< std::valarray< bool > > &isPresent)
std::valarray< bool > isInSubset (const std::vector< Time > &set, const std::vector< Time > &subset)
void checkIncreasingTimes (const std::vector< Time > &times)
check for strictly increasing times, first time greater than zero
void checkIncreasingTimesAndCalculateTaus (const std::vector< Time > &times, std::vector< Time > &taus)
Decimal operator/ (const Money &m1, const Money &m2)
bool operator== (const Money &m1, const Money &m2)
bool operator< (const Money &m1, const Money &m2)
bool operator<= (const Money &m1, const Money &m2)
bool close (const Money &m1, const Money &m2, Size n)
bool close_enough (const Money &m1, const Money &m2, Size n)
std::ostream & operator<< (std::ostream &out, const Money &m)
Money operator+ (const Money &m1, const Money &m2)
Money operator- (const Money &m1, const Money &m2)
Money operator* (const Money &m, Decimal x)
Money operator* (Decimal x, const Money &m)
Money operator/ (const Money &m, Decimal x)
bool operator!= (const Money &m1, const Money &m2)
bool operator> (const Money &m1, const Money &m2)
bool operator>= (const Money &m1, const Money &m2)
Money operator* (Decimal value, const Currency &c)
Money operator* (const Currency &c, Decimal value)
std::ostream & operator<< (std::ostream &out, Option::Type type)
std::ostream & operator<< (std::ostream &out, Position::Type p)
Real midEquivalent (const Real bid, const Real ask, const Real last, const Real close)
Real midSafe (const Real bid, const Real ask)
Real blackFormula (Option::Type optionType, Real strike, Real forward, Real stdDev, Real discount, Real displacement)
Real blackFormula (const boost::shared_ptr< PlainVanillaPayoff > &payoff, Real forward, Real stdDev, Real discount, Real displacement)
Real blackFormulaImpliedStdDevApproximation (Option::Type optionType, Real strike, Real forward, Real blackPrice, Real discount, Real displacement)
Real blackFormulaImpliedStdDevApproximation (const boost::shared_ptr< PlainVanillaPayoff > &payoff, Real forward, Real blackPrice, Real discount, Real displacement)
Real blackFormulaImpliedStdDev (Option::Type optionType, Real strike, Real forward, Real blackPrice, Real discount, Real displacement, Real guess, Real accuracy, Natural maxIterations)
Real blackFormulaImpliedStdDev (const boost::shared_ptr< PlainVanillaPayoff > &payoff, Real forward, Real blackPrice, Real discount, Real displacement, Real guess, Real accuracy, Natural maxIterations)
Real blackFormulaCashItmProbability (Option::Type optionType, Real strike, Real forward, Real stdDev, Real displacement)
Real blackFormulaCashItmProbability (const boost::shared_ptr< PlainVanillaPayoff > &payoff, Real forward, Real stdDev, Real displacement)
Real blackFormulaVolDerivative (Rate strike, Rate forward, Real stdDev, Real expiry, Real discount, Real displacement)
Real blackFormulaStdDevDerivative (Rate strike, Rate forward, Real stdDev, Real discount, Real displacement)
Real blackFormulaStdDevDerivative (const boost::shared_ptr< PlainVanillaPayoff > &payoff, Real forward, Real stdDev, Real discount, Real displacement)
Real bachelierBlackFormula (Option::Type optionType, Real strike, Real forward, Real stdDev, Real discount)
Real bachelierBlackFormula (const boost::shared_ptr< PlainVanillaPayoff > &payoff, Real forward, Real stdDev, Real discount)
Real blackScholesTheta (const boost::shared_ptr< GeneralizedBlackScholesProcess > &, Real value, Real delta, Real gamma)
default theta calculation for Black-Scholes options
Real defaultThetaPerDay (Real theta)
default theta-per-day calculation
std::ostream & operator<< (std::ostream &out, const Settings::DateProxy &p)
std::pair< Date, Date > inflationPeriod (const Date &, Frequency)
utility function giving the inflation period for a given date
Time inflationYearFraction (Frequency f, bool indexIsInterpolated, const DayCounter &dayCounter, const Date &d1, const Date &d2)
void validateAbcdParameters (Real a, Real, Real c, Real d)
Real abcdBlackVolatility (Time u, Real a, Real b, Real c, Real d)
Real unsafeSabrVolatility (Rate strike, Rate forward, Time expiryTime, Real alpha, Real beta, Real nu, Real rho)
void validateSabrParameters (Real alpha, Real beta, Real nu, Real rho)
Real sabrVolatility (Rate strike, Rate forward, Time expiryTime, Real alpha, Real beta, Real nu, Real rho)
std::ostream & operator<< (std::ostream &out, BusinessDayConvention b)
bool operator== (const Calendar &c1, const Calendar &c2)
bool operator!= (const Calendar &c1, const Calendar &c2)
std::ostream & operator<< (std::ostream &out, const Calendar &c)
std::ostream & operator<< (std::ostream &out, Month m)
std::ostream & operator<< (std::ostream &out, const Date &d)
BigInteger operator- (const Date &d1, const Date &d2)
bool operator== (const Date &d1, const Date &d2)
bool operator!= (const Date &d1, const Date &d2)
bool operator< (const Date &d1, const Date &d2)
bool operator<= (const Date &d1, const Date &d2)
bool operator> (const Date &d1, const Date &d2)
bool operator>= (const Date &d1, const Date &d2)
std::ostream & operator<< (std::ostream &out, DateGeneration::Rule r)
bool operator== (const DayCounter &d1, const DayCounter &d2)
bool operator!= (const DayCounter &d1, const DayCounter &d2)
std::ostream & operator<< (std::ostream &out, const DayCounter &d)
std::ostream & operator<< (std::ostream &out, Frequency f)
Real years (const Period &p)
Real months (const Period &p)
Real weeks (const Period &p)
Real days (const Period &p)
bool operator< (const Period &p1, const Period &p2)
Period operator+ (const Period &p1, const Period &p2)
Period operator- (const Period &p1, const Period &p2)
Period operator/ (const Period &p, Integer n)
std::ostream & operator<< (std::ostream &out, const Period &p)
template<typename T >
Period operator* (T n, TimeUnit units)
template<typename T >
Period operator* (TimeUnit units, T n)
Period operator- (const Period &p)
Period operator* (Integer n, const Period &p)
Period operator* (const Period &p, Integer n)
bool operator== (const Period &p1, const Period &p2)
bool operator!= (const Period &p1, const Period &p2)
bool operator> (const Period &p1, const Period &p2)
bool operator<= (const Period &p1, const Period &p2)
bool operator>= (const Period &p1, const Period &p2)
std::ostream & operator<< (std::ostream &out, const TimeUnit &timeunit)
std::ostream & operator<< (std::ostream &out, const Weekday &w)
template<class T >
void swap (Clone< T > &t, Clone< T > &u)
std::string payoffTypeToString (const boost::shared_ptr< Payoff > &h)
std::string exerciseTypeToString (const boost::shared_ptr< Exercise > &h)
boost::shared_ptr
< YieldTermStructure > flatRate (const Date &today, const boost::shared_ptr< Quote > &forward, const DayCounter &dc)
boost::shared_ptr
< YieldTermStructure > flatRate (const Date &today, Rate forward, const DayCounter &dc)
boost::shared_ptr
< YieldTermStructure > flatRate (const boost::shared_ptr< Quote > &forward, const DayCounter &dc)
boost::shared_ptr
< YieldTermStructure > flatRate (Rate forward, const DayCounter &dc)
boost::shared_ptr
< BlackVolTermStructure > flatVol (const Date &today, const boost::shared_ptr< Quote > &vol, const DayCounter &dc)
boost::shared_ptr
< BlackVolTermStructure > flatVol (const Date &today, Volatility vol, const DayCounter &dc)
boost::shared_ptr
< BlackVolTermStructure > flatVol (const boost::shared_ptr< Quote > &vol, const DayCounter &dc)
boost::shared_ptr
< BlackVolTermStructure > flatVol (Volatility vol, const DayCounter &dc)
Real relativeError (Real x1, Real x2, Real reference)
template<class Iterator >
Real norm (const Iterator &begin, const Iterator &end, Real h)
Variables
static const Real x1 [5]
static const Real w10 [5]
static const Real x2 [5]
static const Real w21a [5]
static const Real w21b [6]
static const Real x3 [11]
static const Real w43a [10]
static const Real w43b [12]
static const Real x4 [22]
static const Real w87a [21]
static const Real w87b [23]
static const Real g7w []
static const Real k15w []
static const Real k15t []
static std::set< Date > knownDateSet
Detailed Description
abstract base class implementation specifies how to decide volatility structure for additional synthetic rates which are interleaved
implementation specifies how to decide volatility structure for additional synthetic rates which are interleaved
here we work with abcd curves and interpolate the a, b, c and d
Classes for computing derivative of the map taking rates one step to the next with respect to a change in the pseudo-root. We do it both numerically and analytically to provide an easy test of the analytic method. This is useful for pathwise vegas.
Evolution is log Euler.
One is tested against the other in MarketModelTest::testPathwiseVegas
In order to compute market vegas, we need a class that gives the derivative of a swaption implied vol against changes in pseudo-root elements. This is that class.
This is tested in the pathwise vegas routine in MarketModels.cpp
When bumping vols, bumping every pseudo-root element individually seems excessive so we need to couple some together.
Typedef Documentation
typedef QL_BIG_INTEGER QuantLib::BigInteger
large integer number
Definition at line 39 of file types.hpp.
typedef unsigned QL_BIG_INTEGER QuantLib::BigNatural
large positive integer
Definition at line 46 of file types.hpp.
typedef BivariateCumulativeNormalDistributionWe04DP QuantLib::BivariateCumulativeNormalDistribution
default bivariate implementation
Definition at line 104 of file bivariatenormaldistribution.hpp.
typedef PdeOperator<PdeBSM> QuantLib::BSMTermOperator
Black-Scholes-Merton differential operator.
Test:
coefficients are tested against constant BSM operator
Definition at line 39 of file bsmtermoperator.hpp.
typedef std::vector<boost::shared_ptr<Callability> > QuantLib::CallabilitySchedule
Definition at line 86 of file callabilityschedule.hpp.
typedef std::vector<std::vector<boost::shared_ptr<CapFloor> > > QuantLib::CapFloorMatrix
Definition at line 35 of file optionletstripper1.hpp.
typedef MarketModelMultiProduct::CashFlow QuantLib::CashFlow
Definition at line 34 of file collectnodedata.cpp.
typedef std::map<Date, boost::shared_ptr<CommodityCashFlow> > QuantLib::CommodityCashFlows
Definition at line 87 of file commoditycashflow.hpp.
typedef Integer QuantLib::Day
Day number.
Definition at line 41 of file date.hpp.
typedef Real QuantLib::Decimal
decimal number
Definition at line 54 of file types.hpp.
typedef std::set<boost::shared_ptr<DefaultEvent>, earlier_than<boost::shared_ptr<DefaultEvent> > > QuantLib::DefaultEventSet
Definition at line 38 of file issuer.hpp.
typedef BootstrapHelper<DefaultProbabilityTermStructure> QuantLib::DefaultProbabilityHelper
alias for default-probability bootstrap helpers
Definition at line 37 of file defaultprobabilityhelpers.hpp.
typedef InterpolatedDiscountCurve<LogLinear> QuantLib::DiscountCurve
Term structure based on log-linear interpolation of discount factors.
Log-linear interpolation guarantees piecewise-constant forward rates.
Definition at line 109 of file discountcurve.hpp.
typedef Real QuantLib::DiscountFactor
discount factor between dates
Definition at line 66 of file types.hpp.
typedef std::vector<boost::shared_ptr<Dividend> > QuantLib::DividendSchedule
Definition at line 33 of file dividendschedule.hpp.
typedef std::map<Date, EnergyDailyPosition> QuantLib::EnergyDailyPositions
Definition at line 52 of file energycommodity.hpp.
typedef std::map<Date, ExchangeContract> QuantLib::ExchangeContracts
Definition at line 77 of file exchangecontract.hpp.
typedef OperatorTraits<FdmLinearOp>::bc_set QuantLib::FdmBoundaryConditionSet
Definition at line 32 of file fdmboundaryconditionset.hpp.
typedef InterpolatedForwardCurve<BackwardFlat> QuantLib::ForwardCurve
Term structure based on flat interpolation of forward rates.
Definition at line 107 of file forwardcurve.hpp.
typedef NormalDistribution QuantLib::GaussianDistribution
Definition at line 56 of file normaldistribution.hpp.
typedef GenericGaussianStatistics<GeneralStatistics> QuantLib::GaussianStatistics
default gaussian statistic tool
Definition at line 110 of file gaussianstatistics.hpp.
typedef GaussianRecursiveCdoEngine<MidPointCDOEngine> QuantLib::GaussRecCDOEngine
Definition at line 348 of file recursivecdoengine.hpp.
typedef GaussianLHPCDOEngine<IntegralCDOEngine> QuantLib::GLHPIntegralCDOEngine
Definition at line 282 of file syntheticcdoengines.hpp.
typedef GaussianLHPCDOEngine<MidPointCDOEngine> QuantLib::GLHPMidPointCDOEngine
Definition at line 281 of file syntheticcdoengines.hpp.
typedef HomogeneousPoolCDOEngine<IntegralCDOEngine> QuantLib::HPIntegralCDOEngine
Definition at line 276 of file syntheticcdoengines.hpp.
typedef HomogeneousPoolCDOEngine<MidPointCDOEngine> QuantLib::HPMidPointCDOEngine
Definition at line 275 of file syntheticcdoengines.hpp.
typedef InhomogeneousPoolCDOEngine<IntegralCDOEngine> QuantLib::IHPIntegralCDOEngine
Definition at line 279 of file syntheticcdoengines.hpp.
typedef InhomogeneousPoolCDOEngine<MidPointCDOEngine> QuantLib::IHPMidPointCDOEngine
Definition at line 278 of file syntheticcdoengines.hpp.
typedef QL_INTEGER QuantLib::Integer
integer number
Definition at line 35 of file types.hpp.
typedef InverseCumulativeNormal QuantLib::InvCumulativeNormalDistribution
Definition at line 178 of file normaldistribution.hpp.
typedef std::vector<boost::shared_ptr<CashFlow> > QuantLib::Leg
Sequence of cash-flows.
Definition at line 69 of file cashflow.hpp.
typedef GenericLowDiscrepancy<SobolRsg, InverseCumulativeNormal> QuantLib::LowDiscrepancy
default traits for low-discrepancy sequence generation
Definition at line 105 of file rngtraits.hpp.
typedef unsigned QL_INTEGER QuantLib::Natural
positive integer
Definition at line 43 of file types.hpp.
typedef PdeOperator<PdeShortRate> QuantLib::OneFactorOperator
Interest-rate single factor model differential operator.
Definition at line 36 of file onefactoroperator.hpp.
typedef GenericPseudoRandom<MersenneTwisterUniformRng, InverseCumulativePoisson> QuantLib::PoissonPseudoRandom
traits for Poisson-distributed pseudo-random number generation
Test:
sequence generators are generated and tested by comparing samples against known good values.
Definition at line 78 of file rngtraits.hpp.
typedef std::vector<PricingError> QuantLib::PricingErrors
Definition at line 55 of file commodity.hpp.
typedef std::vector<boost::shared_ptr<PricingPeriod> > QuantLib::PricingPeriods
Definition at line 49 of file pricingperiod.hpp.
typedef Real QuantLib::Probability
probability
Definition at line 37 of file defaulttermstructure.hpp.
typedef GenericPseudoRandom<MersenneTwisterUniformRng, InverseCumulativeNormal> QuantLib::PseudoRandom
default traits for pseudo-random number generation
Test:
a sequence generator is generated and tested by comparing samples against known good values.
Definition at line 71 of file rngtraits.hpp.
typedef Real QuantLib::Rate
interest rates
Definition at line 70 of file types.hpp.
typedef BootstrapHelper<YieldTermStructure> QuantLib::RateHelper
Definition at line 39 of file ratehelpers.hpp.
typedef QL_REAL QuantLib::Real
real number
Definition at line 50 of file types.hpp.
typedef RelativeDateBootstrapHelper<DefaultProbabilityTermStructure> QuantLib::RelativeDateDefaultProbabilityHelper
Definition at line 43 of file defaultprobabilityhelpers.hpp.
typedef RelativeDateBootstrapHelper<YieldTermStructure> QuantLib::RelativeDateRateHelper
Definition at line 43 of file ratehelpers.hpp.
typedef GenericRiskStatistics<GaussianStatistics> QuantLib::RiskStatistics
default risk measures tool
Test:
the correctness of the returned values is tested by checking them against numerical calculations.
Definition at line 124 of file riskstatistics.hpp.
typedef SampledCurve QuantLib::SampledCurveSet
Definition at line 150 of file sampledcurve.hpp.
typedef std::map<std::string, Money> QuantLib::SecondaryCostAmounts
Definition at line 35 of file commodity.hpp.
typedef std::map<std::string, boost::any> QuantLib::SecondaryCosts
Definition at line 34 of file commodity.hpp.
typedef GenericSequenceStatistics<Statistics> QuantLib::SequenceStatistics
default multi-dimensional statistics tool
Test:
the correctness of the returned values is tested by checking them against numerical calculations.
Definition at line 154 of file sequencestatistics.hpp.
typedef GenericSequenceStatistics<IncrementalStatistics> QuantLib::SequenceStatisticsInc
Definition at line 155 of file sequencestatistics.hpp.
typedef std::size_t QuantLib::Size
size of a container
Definition at line 58 of file types.hpp.
typedef boost::numeric::ublas::compressed_matrix<Real> QuantLib::SparseMatrix
Definition at line 45 of file sparsematrix.hpp.
typedef detail::SplineGrid QuantLib::SplineGrid
Definition at line 452 of file multicubicspline.hpp.
typedef Real QuantLib::Spread
spreads on interest rates
Definition at line 74 of file types.hpp.
typedef CurveDependentStepCondition<Array> QuantLib::StandardCurveDependentStepCondition
Definition at line 44 of file fdtypedefs.hpp.
typedef FiniteDifferenceModel< CrankNicolson<TridiagonalOperator> > QuantLib::StandardFiniteDifferenceModel
default choice for finite-difference model
Definition at line 35 of file fdtypedefs.hpp.
typedef StepCondition<Array> QuantLib::StandardStepCondition
default choice for step condition
Definition at line 43 of file fdtypedefs.hpp.
typedef FiniteDifferenceModel<ParallelEvolver< CrankNicolson<TridiagonalOperator> > > QuantLib::StandardSystemFiniteDifferenceModel
default choice for parallel finite-difference model
Definition at line 40 of file fdtypedefs.hpp.
typedef RiskStatistics QuantLib::Statistics
default statistics tool
Test:
the correctness of the returned values is tested by checking them against numerical calculations.
Definition at line 35 of file statistics.hpp.
typedef StudentRecursiveCdoEngine<MidPointCDOEngine> QuantLib::StudentRecCDOEngine
Definition at line 349 of file recursivecdoengine.hpp.
typedef Real QuantLib::Time
continuous quantity with 1-year units
Definition at line 62 of file types.hpp.
typedef Real QuantLib::Volatility
volatility
Definition at line 78 of file types.hpp.
typedef Integer QuantLib::Year
Year number.
Definition at line 75 of file date.hpp.
typedef InterpolatedYoYInflationCurve<Linear> QuantLib::YoYInflationCurve
Definition at line 97 of file interpolatedyoyinflationcurve.hpp.
typedef InterpolatedZeroCurve<Linear> QuantLib::ZeroCurve
Term structure based on linear interpolation of zero yields.
Definition at line 106 of file zerocurve.hpp.
typedef InterpolatedZeroInflationCurve<Linear> QuantLib::ZeroInflationCurve
Definition at line 93 of file interpolatedzeroinflationcurve.hpp.
Enumeration Type Documentation
enum QuantLib::BusinessDayConvention
Business Day conventions.
These conventions specify the algorithm used to adjust a date in case it is not a valid business day.
Enumerator:
Following
Choose the first business day after the given holiday.
ModifiedFollowing
Choose the first business day after the given holiday unless it belongs to a different month, in which case choose the first business day before the holiday.
Preceding
Choose the first business day before the given holiday.
ModifiedPreceding
Choose the first business day before the given holiday unless it belongs to a different month, in which case choose the first business day after the holiday.
Unadjusted
Do not adjust.
Definition at line 40 of file businessdayconvention.hpp.
{
        // ISDA
        Following,
        ModifiedFollowing,
        Preceding,
        // NON ISDA
        ModifiedPreceding,
        Unadjusted
    };
enum QuantLib::Compounding
Interest rate coumpounding rule.
Enumerator:
Simple
\(1+rt \)
Compounded
\((1+r)^t \)
Continuous
\(e^{rt} \)
SimpleThenCompounded
Simple up to the first period then Compounded.
Definition at line 32 of file compounding.hpp.
                     { Simple = 0,
                       Compounded = 1,
                       Continuous = 2,
                       SimpleThenCompounded
    };
enum QuantLib::Frequency
Frequency of events.
Enumerator:
NoFrequency
null frequency
Once
only once, e.g., a zero-coupon
Annual
once a year
Semiannual
twice a year
EveryFourthMonth
every fourth month
Quarterly
every third month
Bimonthly
every second month
Monthly
once a month
EveryFourthWeek
every fourth week
Biweekly
every second week
Weekly
once a week
Daily
once a day
OtherFrequency
some other unknown frequency
Definition at line 37 of file frequency.hpp.
                   { NoFrequency = -1,
                     Once = 0,
                     Annual = 1,
                     Semiannual = 2,
                     EveryFourthMonth = 3,
                     Quarterly = 4,
                     Bimonthly = 6,
                     Monthly = 12,
                     EveryFourthWeek = 13,
                     Biweekly = 26,
                     Weekly = 52,
                     Daily = 365,
                     OtherFrequency = 999
    };
enum QuantLib::JointCalendarRule
rules for joining calendars
Enumerator:
JoinHolidays
A date is a holiday for the joint calendar if it is a holiday for any of the given calendars
JoinBusinessDays
A date is a business day for the joint calendar if it is a business day for any of the given calendars
Definition at line 32 of file jointcalendar.hpp.
                           { JoinHolidays,
                             JoinBusinessDays
    };
enum QuantLib::Month
Month names.
Enumerator:
January
February
March
April
May
June
July
August
September
October
November
December
Jan
Feb
Mar
Apr
Jun
Jul
Aug
Sep
Oct
Nov
Dec
Definition at line 45 of file date.hpp.
               { January   = 1,
                 February  = 2,
                 March     = 3,
                 April     = 4,
                 May       = 5,
                 June      = 6,
                 July      = 7,
                 August    = 8,
                 September = 9,
                 October   = 10,
                 November  = 11,
                 December  = 12,
                 Jan = 1,
                 Feb = 2,
                 Mar = 3,
                 Apr = 4,
                 Jun = 6,
                 Jul = 7,
                 Aug = 8,
                 Sep = 9,
                 Oct = 10,
                 Nov = 11,
                 Dec = 12
    };
enum QuantLib::PriceType
Price types.
Enumerator:
Bid
Bid price.
Ask
Ask price.
Last
Last price.
Close
Close price.
Mid
Mid price, calculated as the arithmetic average of bid and ask prices.
MidEquivalent
Mid equivalent price, calculated as a) the arithmetic average of bid and ask prices when both are available; b) either the bid or the ask price if any of them is available; c) the last price; or d) the close price.
MidSafe
Safe Mid price, returns the mid price only if both bid and ask are available.
Definition at line 35 of file prices.hpp.
                   {
         Bid,
         Ask,
         Last,
         Close,
         Mid,
         MidEquivalent,
         MidSafe
    };
enum QuantLib::Seniority
Seniority of a bond.
They are also ISDA tier/seniorities used for CDS conventional spreads.
Enumerator:
SecDom
SnrFor
SubLT2
JrSubT2
PrefT1
NoSeniority
SeniorSec
SeniorUnSec
SubTier1
SubUpperTier2
SubLoweTier2
Definition at line 37 of file defaulttype.hpp.
                   {
        SecDom = 0,
        SnrFor,
        SubLT2,
        JrSubT2,
        PrefT1,
        // Unassigned value, allows for default RR quote
        NoSeniority,
        // markit parlance
        SeniorSec     = SecDom,
        SeniorUnSec   = SnrFor,
        SubTier1      = PrefT1,
        SubUpperTier2 = JrSubT2,
        SubLoweTier2  = SubLT2
    };
enum QuantLib::SensitivityAnalysis
Finite differences calculation.
Enumerator:
OneSide
Centered
Definition at line 42 of file sensitivityanalysis.hpp.
{
        OneSide,
        Centered
    };
enum QuantLib::TimeUnit
Units used to describe time periods.
Enumerator:
Days
Weeks
Months
Years
Definition at line 37 of file timeunit.hpp.
                  { Days,
                    Weeks,
                    Months,
                    Years
    };
enum QuantLib::Weekday
Day's serial number MOD 7; WEEKDAY Excel function is the same except for Sunday = 7.
Enumerator:
Sunday
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sun
Mon
Tue
Wed
Thu
Fri
Sat
Definition at line 41 of file weekday.hpp.
                 { Sunday    = 1,
                   Monday    = 2,
                   Tuesday   = 3,
                   Wednesday = 4,
                   Thursday  = 5,
                   Friday    = 6,
                   Saturday  = 7,
                   Sun = 1,
                   Mon = 2,
                   Tue = 3,
                   Wed = 4,
                   Thu = 5,
                   Fri = 6,
                   Sat = 7
    };
Function Documentation
Real QuantLib::abcdBlackVolatility (Time u, Real a, Real b, Real c, Real d) [inline]
Definition at line 129 of file abcd.hpp.
References QuantLib::AbcdFunction::volatility().
Referenced by QuantLib::AbcdCalibration::value().
{
        AbcdFunction model(a,b,c,d);
        return model.volatility(0.,u,u);
    }
const Disposable<Array> QuantLib::Abs (const Array & v) [related]
Definition at line 597 of file array.hpp.
References QuantLib::Array::begin(), QuantLib::Array::end(), and QuantLib::Array::size().
Referenced by QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::updateAlphaVec(), and QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::updateAlphaVec().
{
        Array result(v.size());
        std::transform(v.begin(),v.end(),result.begin(),
                       std::ptr_fun<Real,Real>(std::fabs));
        return result;
    }
Real QuantLib::aggregateNPV (const vector< shared_ptr< Instrument > > & instruments, const vector< Real > & quant)
Definition at line 42 of file sensitivityanalysis.cpp.
References QL_REQUIRE.
Referenced by bucketAnalysis(), and parallelAnalysis().
{
        Size n = instruments.size();
        Real npv = 0.0;
        if (quant.empty() || (quant.size()==1 && quant[0]==1.0)) {
            for (Size k=0; k<n; ++k)
                npv += instruments[k]->NPV();
        } else {
            QL_REQUIRE(quant.size()==n,
                       "dimension mismatch between instruments (" << n <<
                       ") and quantities (" << quant.size() << ")");
            for (Size k=0; k<n; ++k)
                npv += quant[k] * instruments[k]->NPV();
        }
        return npv;
    }
Real QuantLib::aggregateNPV (const std::vector< boost::shared_ptr< Instrument > > & , const std::vector< Real > & quantities)
utility fuction for weighted sum of NPVs
template<typename ForwardIterator , typename OutputIterator > void QuantLib::autocorrelations (ForwardIterator begin, ForwardIterator end, OutputIterator out, std::size_t maxLag)
Unbiased auto-correlations.
Results are calculated via FFT. The first element of the output is the unbiased sample variance.
Precondition:
Input data are supposed to be centered (i.e., zero mean).
The size of the output sequence must be maxLag + 1
Definition at line 142 of file autocovariance.hpp.
References QuantLib::detail::double_ft(), and QL_REQUIRE.
Referenced by autocorrelations(), and AutocovariancesTest::testAutoCorrelations().
{
        using namespace detail;
        std::size_t nData = std::distance(begin, end);
        QL_REQUIRE(maxLag < nData,
                   "number of correlations must be less than data size");
        const std::vector<std::complex<Real> >& ft = double_ft(begin, end);
        std::size_t nFrq = ft.size();
        Real variance = ft[0].real() / (nFrq * nData);
        *out++ = variance * nData / Real(nData-1);
        for (std::size_t k = 1; k <= maxLag; ++k)
            *out++ = ft[k].real() / (variance * nFrq * (nData - k));
    }
template<typename ForwardIterator , typename OutputIterator > Real QuantLib::autocorrelations (ForwardIterator begin, ForwardIterator end, OutputIterator out, std::size_t maxLag, bool reuse)
Unbiased auto-correlations.
Results are calculated via FFT. The first element of the output is the unbiased sample variance.
This overload accepts non-centered data, removes the mean and returns it as a result. The centered sequence is written back into the input sequence if the reuse parameter is true.
Precondition:
The size of the output sequence must be maxLag + 1
Definition at line 167 of file autocovariance.hpp.
References autocorrelations(), QuantLib::Array::begin(), QuantLib::Array::end(), and QuantLib::detail::remove_mean().
{
        using namespace detail;
        Real mean = 0.0;
        if (reuse) {
            mean = remove_mean(begin, end, begin);
            autocorrelations(begin, end, out, maxLag);
        } else {
            Array tmp(std::distance(begin, end));
            mean = remove_mean(begin, end, tmp.begin());
            autocorrelations(tmp.begin(), tmp.end(), out, maxLag);
        }
        return mean;
    }
template<typename ForwardIterator , typename OutputIterator > void QuantLib::autocovariances (ForwardIterator begin, ForwardIterator end, OutputIterator out, std::size_t maxLag)
Unbiased auto-covariances.
Results are calculated via FFT.
Precondition:
Input data are supposed to be centered (i.e., zero mean).
The size of the output sequence must be maxLag + 1
Definition at line 95 of file autocovariance.hpp.
References QuantLib::detail::double_ft(), and QL_REQUIRE.
Referenced by autocovariances(), and AutocovariancesTest::testAutoCovariances().
{
        using namespace detail;
        std::size_t nData = std::distance(begin, end);
        QL_REQUIRE(maxLag < nData,
                   "number of covariances must be less than data size");
        const std::vector<std::complex<Real> >& ft = double_ft(begin, end);
        std::size_t nFrq = ft.size();
        for (std::size_t k = 0; k <= maxLag; ++k)
            *out++ = ft[k].real() / (nFrq * (nData - k));
    }
template<typename ForwardIterator , typename OutputIterator > Real QuantLib::autocovariances (ForwardIterator begin, ForwardIterator end, OutputIterator out, std::size_t maxLag, bool reuse)
Unbiased auto-covariances.
Results are calculated via FFT.
This overload accepts non-centered data, removes the mean and returns it as a result. The centered sequence is written back into the input sequence if the reuse parameter is true.
Precondition:
The size of the output sequence must be maxLag + 1
Definition at line 117 of file autocovariance.hpp.
References autocovariances(), QuantLib::Array::begin(), QuantLib::Array::end(), and QuantLib::detail::remove_mean().
{
        using namespace detail;
        Real mean = 0.0;
        if (reuse) {
            mean = remove_mean(begin, end, begin);
            autocovariances(begin, end, out, maxLag);
        } else {
            Array tmp(std::distance(begin, end));
            mean = remove_mean(begin, end, tmp.begin());
            autocovariances(tmp.begin(), tmp.end(), out, maxLag);
        }
        return mean;
    }
Real QuantLib::bachelierBlackFormula (Option::Type optionType, Real strike, Real forward, Real stdDev, Real discount = 1.0)
Black style formula when forward is normal rather than log-normal. This is essentially the model of Bachelier.
Warning:
Bachelier model needs absolute volatility, not percentage volatility. Standard deviation is absoluteVolatility*sqrt(timeToMaturity)
Definition at line 349 of file blackformula.cpp.
References anonymous_namespace{marketmodel.cpp}::d, QuantLib::CumulativeNormalDistribution::derivative(), QuantLib::anonymous_namespace{bjerksundstenslandengine.cpp}::phi(), QL_ENSURE, and QL_REQUIRE.
Referenced by bachelierBlackFormula(), anonymous_namespace{marketmodel.cpp}::checkNormalForwardsAndOptionlets(), QuantLib::YoYInflationBachelierCapFloorEngine::optionletImpl(), and QuantLib::BachelierYoYInflationCouponPricer::optionletPriceImp().
    {
        QL_REQUIRE(stdDev>=0.0,
                   "stdDev (" << stdDev << ") must be non-negative");
        QL_REQUIRE(discount>0.0,
                   "discount (" << discount << ") must be positive");
        Real d = (forward-strike)*optionType, h = d/stdDev;
        if (stdDev==0.0)
            return discount*std::max(d, 0.0);
        CumulativeNormalDistribution phi;
        Real result = discount*(stdDev*phi.derivative(h) + d*phi(h));
        QL_ENSURE(result>=0.0,
                  "negative value (" << result << ") for " <<
                  stdDev << " stdDev, " <<
                  optionType << " option, " <<
                  strike << " strike , " <<
                  forward << " forward");
        return result;
    }
Real QuantLib::bachelierBlackFormula (const boost::shared_ptr< PlainVanillaPayoff > & payoff, Real forward, Real stdDev, Real discount = 1.0)
Black style formula when forward is normal rather than log-normal. This is essentially the model of Bachelier.
Warning:
Bachelier model needs absolute volatility, not percentage volatility. Standard deviation is absoluteVolatility*sqrt(timeToMaturity)
Definition at line 373 of file blackformula.cpp.
References bachelierBlackFormula().
{
        return bachelierBlackFormula(payoff->optionType(),
            payoff->strike(), forward, stdDev, discount);
    }
Real QuantLib::betaContinuedFraction (Real a, Real b, Real x, Real accuracy, Integer maxIteration)
Definition at line 29 of file beta.cpp.
References anonymous_namespace{marketmodel.cpp}::b, anonymous_namespace{marketmodel.cpp}::c, anonymous_namespace{marketmodel.cpp}::d, QL_EPSILON, and QL_FAIL.
Referenced by incompleteBetaFunction().
{
        Real aa, del;
        Real qab = a+b;
        Real qap = a+1.0;
        Real qam = a-1.0;
        Real c = 1.0;
        Real d = 1.0-qab*x/qap;
        if (std::fabs(d) < QL_EPSILON)
            d = QL_EPSILON;
        d = 1.0/d;
        Real result = d;
        Integer m, m2;
        for (m=1; m<=maxIteration; m++) {
            m2=2*m;
            aa=m*(b-m)*x/((qam+m2)*(a+m2));
            d=1.0+aa*d;
            if (std::fabs(d) < QL_EPSILON) d=QL_EPSILON;
            c=1.0+aa/c;
            if (std::fabs(c) < QL_EPSILON) c=QL_EPSILON;
            d=1.0/d;
            result *= d*c;
            aa = -(a+m)*(qab+m)*x/((a+m2)*(qap+m2));
            d=1.0+aa*d;
            if (std::fabs(d) < QL_EPSILON) d=QL_EPSILON;
            c=1.0+aa/c;
            if (std::fabs(c) < QL_EPSILON) c=QL_EPSILON;
            d=1.0/d;
            del=d*c;
            result *= del;
            if (std::fabs(del-1.0) < accuracy)
                return result;
        }
        QL_FAIL("a or b too big, or maxIteration too small in betacf");
    }
Real QuantLib::betaFunction (Real z, Real w) [inline]
Definition at line 31 of file beta.hpp.
{
    return std::exp(GammaFunction().logValue(z) +
                    GammaFunction().logValue(w) -
                    GammaFunction().logValue(z+w));
    }
Real QuantLib::binomialCoefficient (BigNatural n, BigNatural k) [inline]
Definition at line 40 of file binomialdistribution.hpp.
References binomialCoefficientLn().
{
        return std::floor(0.5+std::exp(binomialCoefficientLn(n, k)));
    }
Real QuantLib::binomialCoefficientLn (BigNatural n, BigNatural k) [inline]
Definition at line 32 of file binomialdistribution.hpp.
References QuantLib::Factorial::ln(), and QL_REQUIRE.
Referenced by binomialCoefficient().
{
        QL_REQUIRE(n>=k, "n<k not allowed");
        return Factorial::ln(n)-Factorial::ln(k)-Factorial::ln(n-k);
    }
Real QuantLib::blackFormula (Option::Type optionType, Real strike, Real forward, Real stdDev, Real discount = 1.0, Real displacement = 0.0)
Black 1976 formula
Warning:
instead of volatility it uses standard deviation, i.e. volatility*sqrt(timeToMaturity)
Definition at line 45 of file blackformula.cpp.
References QuantLib::Option::Call, anonymous_namespace{blackformula.cpp}::checkParameters(), anonymous_namespace{marketmodel.cpp}::displacement, QuantLib::anonymous_namespace{bjerksundstenslandengine.cpp}::phi(), QL_ENSURE, and QL_REQUIRE.
Referenced by blackFormula(), QuantLib::HestonModelHelper::blackPrice(), QuantLib::AnalyticWriterExtensibleOptionEngine::calculate(), QuantLib::LfmSwaptionEngine::calculate(), QuantLib::BlackCdsOptionEngine::calculate(), QuantLib::BlackCapFloorEngine::calculate(), QuantLib::BlackSwaptionEngine::calculate(), QuantLib::BlackCallableFixedRateBondEngine::calculate(), QuantLib::JuQuadraticApproximationEngine::calculate(), QuantLib::RangeAccrualPricerByBgm::callSpreadPrice(), QuantLib::CapPseudoDerivative::CapPseudoDerivative(), QuantLib::BaroneAdesiWhaleyApproximationEngine::criticalPrice(), QuantLib::Vasicek::discountBondOption(), QuantLib::HullWhite::discountBondOption(), QuantLib::LiborForwardModel::discountBondOption(), QuantLib::G2::discountBondOption(), QuantLib::anonymous_namespace{stulzengine.cpp}::euroTwoAssetMaxBasketCall(), QuantLib::BlackVanillaOptionPricer::operator()(), QuantLib::anonymous_namespace{swaptionpseudojacobian.cpp}::QuickCap::operator()(), QuantLib::YoYInflationBlackCapFloorEngine::optionletImpl(), QuantLib::YoYInflationUnitDisplacedBlackCapFloorEngine::optionletImpl(), QuantLib::BlackIborCouponPricer::optionletPrice(), QuantLib::BlackYoYInflationCouponPricer::optionletPriceImp(), QuantLib::UnitDisplacedBlackYoYInflationCouponPricer::optionletPriceImp(), BatesModelTest::testAnalyticVsBlack(), HestonModelTest::testAnalyticVsBlack(), MarketModelTest::testInverseFloater(), and MarketModelTest::testPathwiseVegas().
    {
        checkParameters(strike, forward, displacement);
        QL_REQUIRE(stdDev>=0.0,
                   "stdDev (" << stdDev << ") must be non-negative");
        QL_REQUIRE(discount>0.0,
                   "discount (" << discount << ") must be positive");
        if (stdDev==0.0)
            return std::max((forward-strike)*optionType, Real(0.0))*discount;
        forward = forward + displacement;
        strike = strike + displacement;
        // since displacement is non-negative strike==0 iff displacement==0
        // so returning forward*discount is OK
        if (strike==0.0)
            return (optionType==Option::Call ? forward*discount : 0.0);
        Real d1 = std::log(forward/strike)/stdDev + 0.5*stdDev;
        Real d2 = d1 - stdDev;
        CumulativeNormalDistribution phi;
        Real nd1 = phi(optionType*d1);
        Real nd2 = phi(optionType*d2);
        Real result = discount * optionType * (forward*nd1 - strike*nd2);
        QL_ENSURE(result>=0.0,
                  "negative value (" << result << ") for " <<
                  stdDev << " stdDev, " <<
                  optionType << " option, " <<
                  strike << " strike , " <<
                  forward << " forward");
        return result;
    }
Real QuantLib::blackFormula (const boost::shared_ptr< PlainVanillaPayoff > & payoff, Real forward, Real stdDev, Real discount = 1.0, Real displacement = 0.0)
Black 1976 formula
Warning:
instead of volatility it uses standard deviation, i.e. volatility*sqrt(timeToMaturity)
Definition at line 84 of file blackformula.cpp.
References blackFormula(), and anonymous_namespace{marketmodel.cpp}::displacement.
{
        return blackFormula(payoff->optionType(),
            payoff->strike(), forward, stdDev, discount, displacement);
    }
Real QuantLib::blackFormulaCashItmProbability (Option::Type optionType, Real strike, Real forward, Real stdDev, Real displacement = 0.0)
Black 1976 probability of being in the money (in the bond martingale measure), i.e. N(d2). It is a risk-neutral probability, not the real world one.
Warning:
instead of volatility it uses standard deviation, i.e. volatility*sqrt(timeToMaturity)
Definition at line 268 of file blackformula.cpp.
References QuantLib::Option::Call, anonymous_namespace{blackformula.cpp}::checkParameters(), anonymous_namespace{marketmodel.cpp}::displacement, and QuantLib::anonymous_namespace{bjerksundstenslandengine.cpp}::phi().
Referenced by blackFormulaCashItmProbability(), and DigitalCouponTest::testCashOrNothing().
{
        checkParameters(strike, forward, displacement);
        if (stdDev==0.0)
            return (forward*optionType > strike*optionType ? 1.0 : 0.0);
        forward = forward + displacement;
        strike = strike + displacement;
        if (strike==0.0)
            return (optionType==Option::Call ? 1.0 : 0.0);
        Real d2 = std::log(forward/strike)/stdDev - 0.5*stdDev;
        CumulativeNormalDistribution phi;
        return phi(optionType*d2);
    }
Real QuantLib::blackFormulaCashItmProbability (const boost::shared_ptr< PlainVanillaPayoff > & payoff, Real forward, Real stdDev, Real displacement = 0.0)
Black 1976 probability of being in the money (in the bond martingale measure), i.e. N(d2). It is a risk-neutral probability, not the real world one.
Warning:
instead of volatility it uses standard deviation, i.e. volatility*sqrt(timeToMaturity)
Definition at line 287 of file blackformula.cpp.
References blackFormulaCashItmProbability(), and anonymous_namespace{marketmodel.cpp}::displacement.
{
        return blackFormulaCashItmProbability(payoff->optionType(),
            payoff->strike(), forward, stdDev , displacement);
    }
Real QuantLib::blackFormulaImpliedStdDev (Option::Type optionType, Real strike, Real forward, Real blackPrice, Real discount = 1.0, Real displacement = 0.0, Real guess = Null< Real >(), Real accuracy = 1.0e-6, Natural maxIterations = 100)
Black 1976 implied standard deviation, i.e. volatility*sqrt(timeToMaturity)
Definition at line 195 of file blackformula.cpp.
References blackFormulaImpliedStdDevApproximation(), QuantLib::Option::Call, anonymous_namespace{blackformula.cpp}::checkParameters(), anonymous_namespace{marketmodel.cpp}::displacement, anonymous_namespace{interpolations.cpp}::f(), QuantLib::Option::Put, QL_ENSURE, QL_REQUIRE, QuantLib::Solver1D< Impl >::setMaxEvaluations(), and QuantLib::Solver1D< Impl >::solve().
Referenced by blackFormulaImpliedStdDev(), QuantLib::EurodollarFuturesImpliedStdDevQuote::performCalculations(), QuantLib::ImpliedStdDevQuote::performCalculations(), QuantLib::OptionletStripper1::performCalculations(), and QuoteTest::testForwardValueQuoteAndImpliedStdevQuote().
    {
        checkParameters(strike, forward, displacement);
        QL_REQUIRE(discount>0.0,
                   "discount (" << discount << ") must be positive");
        QL_REQUIRE(blackPrice>=0.0,
                   "option price (" << blackPrice << ") must be non-negative");
        // check the price of the "other" option implied by put-call paity
        Real otherOptionPrice = blackPrice - optionType*(forward-strike)*discount;
        QL_REQUIRE(otherOptionPrice>=0.0,
                   "negative " << Option::Type(-1*optionType) <<
                   " price (" << otherOptionPrice <<
                   ") implied by put-call parity. No solution exists for " <<
                   optionType << " strike " << strike <<
                   ", forward " << forward <<
                   ", price " << blackPrice <<
                   ", deflator " << discount);
        // solve for the out-of-the-money option which has
        // greater vega/price ratio, i.e.
        // it is numerically more robust for implied vol calculations
        if (optionType==Option::Put && strike>forward) {
            optionType = Option::Call;
            blackPrice = otherOptionPrice;
        }
        if (optionType==Option::Call && strike<forward) {
            optionType = Option::Put;
            blackPrice = otherOptionPrice;
        }
        strike = strike + displacement;
        forward = forward + displacement;
        if (guess==Null<Real>())
            guess = blackFormulaImpliedStdDevApproximation(
                optionType, strike, forward, blackPrice, discount, displacement);
        else
            QL_REQUIRE(guess>=0.0,
                       "stdDev guess (" << guess << ") must be non-negative");
        BlackImpliedStdDevHelper f(optionType, strike, forward,
                                   blackPrice/discount);
        NewtonSafe solver;
        solver.setMaxEvaluations(maxIterations);
        Real minSdtDev = 0.0, maxStdDev = 24.0; // 24 = 300% * sqrt(60)
        Real stdDev = solver.solve(f, accuracy, guess, minSdtDev, maxStdDev);
        QL_ENSURE(stdDev>=0.0,
                  "stdDev (" << stdDev << ") must be non-negative");
        return stdDev;
    }
Real QuantLib::blackFormulaImpliedStdDev (const boost::shared_ptr< PlainVanillaPayoff > & payoff, Real forward, Real blackPrice, Real discount = 1.0, Real displacement = 0.0, Real guess = Null< Real >(), Real accuracy = 1.0e-6, Natural maxIterations = 100)
Black 1976 implied standard deviation, i.e. volatility*sqrt(timeToMaturity)
Definition at line 255 of file blackformula.cpp.
References blackFormulaImpliedStdDev(), and anonymous_namespace{marketmodel.cpp}::displacement.
{
        return blackFormulaImpliedStdDev(payoff->optionType(), payoff->strike(),
            forward, blackPrice, discount, displacement, guess, accuracy, maxIterations);
    }
Real QuantLib::blackFormulaImpliedStdDevApproximation (Option::Type optionType, Real strike, Real forward, Real blackPrice, Real discount = 1.0, Real displacement = 0.0)
Approximated Black 1976 implied standard deviation, i.e. volatility*sqrt(timeToMaturity).
It is calculated using Brenner and Subrahmanyan (1988) and Feinstein (1988) approximation for at-the-money forward option, with the extended moneyness approximation by Corrado and Miller (1996)
Definition at line 93 of file blackformula.cpp.
References anonymous_namespace{blackformula.cpp}::checkParameters(), anonymous_namespace{marketmodel.cpp}::displacement, M_PI, QL_ENSURE, and QL_REQUIRE.
Referenced by blackFormulaImpliedStdDev(), and blackFormulaImpliedStdDevApproximation().
    {
        checkParameters(strike, forward, displacement);
        QL_REQUIRE(blackPrice>=0.0,
                   "blackPrice (" << blackPrice << ") must be non-negative");
        QL_REQUIRE(discount>0.0,
                   "discount (" << discount << ") must be positive");
        Real stdDev;
        forward = forward + displacement;
        strike = strike + displacement;
        if (strike==forward)
            // Brenner-Subrahmanyan (1988) and Feinstein (1988) ATM approx.
            stdDev = blackPrice/discount*std::sqrt(2.0 * M_PI)/forward;
        else {
            // Corrado and Miller extended moneyness approximation
            Real moneynessDelta = optionType*(forward-strike);
            Real moneynessDelta_2 = moneynessDelta/2.0;
            Real temp = blackPrice/discount - moneynessDelta_2;
            Real moneynessDelta_PI = moneynessDelta*moneynessDelta/M_PI;
            Real temp2 = temp*temp-moneynessDelta_PI;
            if (temp2<0.0) // approximation breaks down, 2 alternatives:
                // 1. zero it
                temp2=0.0;
                // 2. Manaster-Koehler (1982) efficient Newton-Raphson seed
                //return std::fabs(std::log(forward/strike))*std::sqrt(2.0);
            temp2 = std::sqrt(temp2);
            temp += temp2;
            temp *= std::sqrt(2.0 * M_PI);
            stdDev = temp/(forward+strike);
        }
        QL_ENSURE(stdDev>=0.0,
                  "stdDev (" << stdDev << ") must be non-negative");
        return stdDev;
    }
Real QuantLib::blackFormulaImpliedStdDevApproximation (const boost::shared_ptr< PlainVanillaPayoff > & payoff, Real forward, Real blackPrice, Real discount = 1.0, Real displacement = 0.0)
Approximated Black 1976 implied standard deviation, i.e. volatility*sqrt(timeToMaturity).
It is calculated using Brenner and Subrahmanyan (1988) and Feinstein (1988) approximation for at-the-money forward option, with the extended moneyness approximation by Corrado and Miller (1996)
Definition at line 134 of file blackformula.cpp.
References blackFormulaImpliedStdDevApproximation(), and anonymous_namespace{marketmodel.cpp}::displacement.
{
        return blackFormulaImpliedStdDevApproximation(payoff->optionType(),
            payoff->strike(), forward, blackPrice, discount, displacement);
    }
Real QuantLib::blackFormulaStdDevDerivative (Real strike, Real forward, Real stdDev, Real discount = 1.0, Real displacement = 0.0)
Black 1976 formula for standard deviation derivative
Warning:
instead of volatility it uses standard deviation, i.e. volatility*sqrt(timeToMaturity), and it returns the derivative with respect to the standard deviation. If T is the time to maturity Black vega would be blackStdDevDerivative(strike, forward, stdDev)*sqrt(T)
Definition at line 311 of file blackformula.cpp.
References anonymous_namespace{blackformula.cpp}::checkParameters(), QuantLib::CumulativeNormalDistribution::derivative(), anonymous_namespace{marketmodel.cpp}::displacement, and QL_REQUIRE.
Referenced by blackFormulaStdDevDerivative(), blackFormulaVolDerivative(), QuantLib::BlackCapFloorEngine::calculate(), QuantLib::BlackSwaptionEngine::calculate(), and QuantLib::detail::SABRInterpolationImpl< I1, I2 >::update().
    {
        checkParameters(strike, forward, displacement);
        QL_REQUIRE(stdDev>=0.0,
                   "stdDev (" << stdDev << ") must be non-negative");
        QL_REQUIRE(discount>0.0,
                   "discount (" << discount << ") must be positive");
        forward = forward + displacement;
        strike = strike + displacement;
        if (stdDev==0.0) {
            if (forward>strike)
                return discount * forward;
            else
                return 0.0;
        }
        Real d1 = std::log(forward/strike)/stdDev + .5*stdDev;
        return discount * forward *
            CumulativeNormalDistribution().derivative(d1);
    }
Real QuantLib::blackFormulaStdDevDerivative (const boost::shared_ptr< PlainVanillaPayoff > & payoff, Real forward, Real stdDev, Real discount = 1.0, Real displacement = 0.0)
Black 1976 formula for standard deviation derivative
Warning:
instead of volatility it uses standard deviation, i.e. volatility*sqrt(timeToMaturity), and it returns the derivative with respect to the standard deviation. If T is the time to maturity Black vega would be blackStdDevDerivative(strike, forward, stdDev)*sqrt(T)
Definition at line 338 of file blackformula.cpp.
References blackFormulaStdDevDerivative(), and anonymous_namespace{marketmodel.cpp}::displacement.
{
        return blackFormulaStdDevDerivative(payoff->strike(), forward,
                                     stdDev, discount, displacement);
    }
Real QuantLib::blackFormulaVolDerivative (Real strike, Real forward, Real stdDev, Real expiry, Real discount = 1.0, Real displacement = 0.0)
Black 1976 formula for derivative with respect to implied vol, this is basically the vega, but if you want 1% change multiply by 1%
Definition at line 297 of file blackformula.cpp.
References blackFormulaStdDevDerivative().
Referenced by QuantLib::CapPseudoDerivative::CapPseudoDerivative(), MarketModelTest::testPathwiseMarketVegas(), and QuantLib::anonymous_namespace{swaptionpseudojacobian.cpp}::QuickCap::vega().
    {
        return  blackFormulaStdDevDerivative(strike,
                                     forward,
                                     stdDev,
                                     discount,
                                     displacement)*std::sqrt(expiry);
    }
Real QuantLib::blackScholesTheta (const boost::shared_ptr< GeneralizedBlackScholesProcess > & p, Real value, Real delta, Real gamma)
default theta calculation for Black-Scholes options
Definition at line 25 of file greeks.cpp.
References Continuous, and anonymous_namespace{perturbativebarrieroptionengine.cpp}::v().
Referenced by QuantLib::AnalyticDiscreteGeometricAveragePriceAsianEngine::calculate(), QuantLib::FDEuropeanEngine< Scheme >::calculate(), and QuantLib::BinomialVanillaEngine< T >::calculate().
{
        Real u = p->stateVariable()->value();
        Rate r = p->riskFreeRate()->zeroRate(0.0, Continuous);
        Rate q = p->dividendYield()->zeroRate(0.0, Continuous);
        Volatility v = p->localVolatility()->localVol(0.0, u);
        return r*value -(r-q)*u*delta - 0.5*v*v*u*u*gamma;
    }
Disposable< Array > QuantLib::BoundedGrid (Real xMin, Real xMax, Size steps) [inline]
Definition at line 45 of file grid.hpp.
Referenced by SampledCurveTest::testConstruction(), and TransformedGridTest::testConstruction().
{
        Array result(steps+1);
        Real x=xMin, dx=(xMax-xMin)/steps;
        for (Size i=0; i<steps+1; i++, x+=dx)
            result[i] = x;
        return result;
    }
Disposable< Array > QuantLib::BoundedLogGrid (Real xMin, Real xMax, Size steps) [inline]
Definition at line 54 of file grid.hpp.
Referenced by QuantLib::SampledCurve::regridLogGrid(), and QuantLib::SampledCurve::setLogGrid().
{
        Array result(steps+1);
        Real gridLogSpacing = (std::log(xMax) - std::log(xMin)) /
            (steps);
        Real edx = std::exp(gridLogSpacing);
        result[0] = xMin;
        for (Size j=1; j < steps+1; j++) {
            result[j] = result[j-1]*edx;
        }
        return result;
    }
std::pair<Real, Real> QuantLib::bucketAnalysis (Handle< SimpleQuote > quote, const std::vector< boost::shared_ptr< Instrument > > & , const std::vector< Real > & quantities, Real shift = 0.0001, SensitivityAnalysis type = Centered, Real referenceNpv = Null< Real >())
(bucket) PV01 sensitivity analysis for a (single) SimpleQuote
returns a pair of first and second derivative values calculated as prescribed by SensitivityAnalysis. Second derivative might not be available depending on SensitivityAnalysis value.
Empty quantities vector is considered as unit vector. The same if the vector is of size one.
pair<Real, Real> QuantLib::bucketAnalysis (Handle< SimpleQuote > quote, const vector< shared_ptr< Instrument > > & instruments, const vector< Real > & quantities, Real shift, SensitivityAnalysis type, Real referenceNpv)
Definition at line 120 of file sensitivityanalysis.cpp.
References aggregateNPV(), Centered, OneSide, QL_FAIL, and QL_REQUIRE.
Referenced by bucketAnalysis().
    {
        QL_REQUIRE(shift!=0.0, "zero shift not allowed");
        pair<Real, Real> result(0.0, 0.0);
        if (instruments.empty()) return result;
        if (referenceNpv==Null<Real>())
            referenceNpv = aggregateNPV(instruments, quantities);
        if (!quote->isValid()) return result;
        Real quoteValue = quote->value();
        try {
            quote->setValue(quoteValue+shift);
            Real npv = aggregateNPV(instruments, quantities);
            switch (type) {
              case OneSide:
                result.first = (npv-referenceNpv)/shift;
                result.second = Null<Real>();
                break;
              case Centered:
                {
                quote->setValue(quoteValue-shift);
                Real npv2 = aggregateNPV(instruments, quantities);
                result.first = (npv-npv2)/(2.0*shift);
                result.second = (npv-2.0*referenceNpv+npv2)/(shift*shift);
                }
                break;
              default:
                  QL_FAIL("unknown SensitivityAnalysis (" <<
                          Integer(type) << ")");
            }
            quote->setValue(quoteValue);
        } catch (...) {
            quote->setValue(quoteValue);
            throw;
        }
        return result;
    }
std::pair<std::vector<Real>, std::vector<Real> > QuantLib::bucketAnalysis (const std::vector< Handle< SimpleQuote > > & quotes, const std::vector< boost::shared_ptr< Instrument > > & , const std::vector< Real > & quantities, Real shift = 0.0001, SensitivityAnalysis type = Centered)
bucket PV01 sensitivity analysis for a SimpleQuote vector
returns a pair of first and second derivative vectors calculated as prescribed by SensitivityAnalysis. Second derivative might not be available depending on SensitivityAnalysis value.
Empty quantities vector is considered as unit vector. The same if the vector is of size one.
The (bucket) SimpleQuotes are tweaked one by one separately.
void QuantLib::bucketAnalysis (std::vector< Real > & deltaVector, std::vector< Real > & gammaVector, std::vector< Real > & referenceValues, Handle< SimpleQuote > quote, const std::vector< Handle< Quote > > & parameters, Real shift = 0.0001, SensitivityAnalysis type = Centered)
(bucket) parameters' sensitivity analysis for a (single) SimpleQuote
returns a vector (one element for each paramet) of pair of first and second derivative values calculated as prescribed by SensitivityAnalysis. Second derivative might not be available depending on SensitivityAnalysis value.
Empty quantities vector is considered as unit vector. The same if the vector is of size one.
Definition at line 169 of file sensitivityanalysis.cpp.
References Centered, OneSide, QL_FAIL, and QL_REQUIRE.
    {
        QL_REQUIRE(shift!=0.0, "zero shift not allowed");
        QL_REQUIRE(!params.empty(), "empty parameters vector");
        Size m = params.size();
        deltaVector.resize(m);
        gammaVector.resize(m);
        if (!quote->isValid()) {
            for (Size j=0; j<m; ++j) {
                deltaVector[j]=Null<Real>();
                gammaVector[j]=Null<Real>();
            }
            return;
        }
        Real quoteValue = quote->value();
        if (!refVals.empty()) {
            QL_REQUIRE(refVals.size()==m,
                       "referenceValues has size " <<
                       refVals.size() << ", instead of " << m);
        } else {
            // calculate parameters' reference values
            refVals = vector<Real>(m, Null<Real>());
            for (Size j=0; j<m; ++j) {
                if (params[j]->isValid()) // fault tolerant
                    refVals[j] = params[j]->value();
            }
        }
        try {
            switch (type) {
              case OneSide:
                {
                    quote->setValue(quoteValue+shift);
                    for (Size j=0; j<m; ++j) {
                        gammaVector[j] = Null<Real>();
                        if (refVals[j] != Null<Real>())
                            deltaVector[j] = (params[j]->value()-refVals[j])/shift;
                        else
                            deltaVector[j] = Null<Real>();
                    }
                }
                break;
              case Centered:
                {
                    quote->setValue(quoteValue+shift);
                    vector<Real> plus(m);
                    for (Size j=0; j<m; ++j) {
                        if (refVals[j] != Null<Real>())
                            plus[j] = params[j]->value();
                    }
                    quote->setValue(quoteValue-shift);
                    for (Size j=0; j<m; ++j) {
                        if (refVals[j] != Null<Real>()) {
                            Real minus = params[j]->value();
                            deltaVector[j] = (plus[j]-minus)/(2.0*shift);
                            gammaVector[j] = (plus[j]-2.0*refVals[j]+minus)/(shift*shift);
                        } else {
                            deltaVector[j] = Null<Real>();
                            gammaVector[j] = Null<Real>();
                        }
                    }
                }
                break;
              default:
                  QL_FAIL("unknown SensitivityAnalysis (" <<
                          Integer(type) << ")");
            } // end switch
            // restore the quote to its original state
            quote->setValue(quoteValue);
            return;
        } catch (...) {
            // restore the quote to its original state
            quote->setValue(quoteValue);
            throw;
        }
    }
std::pair<std::vector<std::vector<Real> >, std::vector<std::vector<Real> > > QuantLib::bucketAnalysis (const std::vector< std::vector< Handle< SimpleQuote > > > & , const std::vector< boost::shared_ptr< Instrument > > & , const std::vector< Real > & quantities, Real shift = 0.0001, SensitivityAnalysis type = Centered)
bucket sensitivity analysis for a SimpleQuote matrix
returns a pair of first and second derivative metrices calculated as prescribed by SensitivityAnalysis. Second derivative might not be available depending on SensitivityAnalysis value.
Empty quantities vector is considered as unit vector. The same if the vector is of size one.
The (bucket) SimpleQuotes are tweaked one by one separately.
pair<vector<Real>, vector<Real> > QuantLib::bucketAnalysis (const vector< Handle< SimpleQuote > > & quotes, const vector< shared_ptr< Instrument > > & instr, const vector< Real > & quant, Real shift, SensitivityAnalysis type)
Definition at line 263 of file sensitivityanalysis.cpp.
References aggregateNPV(), bucketAnalysis(), and QL_REQUIRE.
    {
        QL_REQUIRE(!quotes.empty(), "empty SimpleQuote vector");
        Size n = quotes.size();
        pair<vector<Real>, vector<Real> > result(vector<Real>(n, 0.0),
                                                 vector<Real>(n, 0.0));
        if (instr.empty()) return result;
        Real npv = aggregateNPV(instr, quant);
        pair<Real, Real> tmp;
        for (Size i=0; i<n; ++i) {
            tmp = bucketAnalysis(quotes[i], instr, quant, shift, type, npv);
            result.first[i] = tmp.first;
            result.second[i] = tmp.second;
        }
        return result;
    }
void QuantLib::bucketAnalysis (std::vector< std::vector< Real > > & deltaMatrix, std::vector< std::vector< Real > > & gammaMatrix, const std::vector< Handle< SimpleQuote > > & quotes, const std::vector< Handle< Quote > > & parameters, Real shift = 0.0001, SensitivityAnalysis type = Centered)
bucket parameters' sensitivity analysis for a SimpleQuote vector
returns a vector (one element for each paramet) of pair of first and second derivative vectors calculated as prescribed by SensitivityAnalysis. Second derivative might not be available depending on SensitivityAnalysis value.
Empty quantities vector is considered as unit vector. The same if the vector is of size one.
The (bucket) SimpleQuotes are tweaked one by one separately.
Definition at line 289 of file sensitivityanalysis.cpp.
References bucketAnalysis(), and QL_REQUIRE.
    {
        QL_REQUIRE(!quotes.empty(), "empty SimpleQuote vector");
        QL_REQUIRE(!parameters.empty(), "empty parameters vector");
        Size n = quotes.size();
        deltaMatrix.resize(n);
        gammaMatrix.resize(n);
        Size m = parameters.size();
        vector<Real> referenceValues(m, Null<Real>());
        for (Size i=0; i<m; ++i) {
            if (parameters[i]->isValid())
                referenceValues[i] = parameters[i]->value();
        }
        for (Size i=0; i<n; ++i) {
            bucketAnalysis(deltaMatrix[i], gammaMatrix[i], referenceValues,
                           quotes[i], parameters, shift, type);
        }
        return;
    }
pair<vector<vector<Real> >, vector<vector<Real> > > QuantLib::bucketAnalysis (const vector< vector< Handle< SimpleQuote > > > & quotes, const vector< shared_ptr< Instrument > > & instr, const vector< Real > & quant, Real shift, SensitivityAnalysis type)
Definition at line 319 of file sensitivityanalysis.cpp.
References aggregateNPV(), bucketAnalysis(), and QL_REQUIRE.
    {
        QL_REQUIRE(!quotes.empty(), "empty SimpleQuote range");
        Size n = quotes.size();
        vector<vector<Real> > first(n);
        vector<vector<Real> > second(n);
        for (Size i=0; i<n; ++i) {
            Size tmp = quotes[i].size();
            first[i] = vector<Real>(tmp, 0.0);
            second[i] = vector<Real>(tmp, 0.0);
        }
        pair<vector<vector<Real> >, vector<vector<Real> > >
            result(first, second);
        if (instr.empty()) return result;
        Real npv = aggregateNPV(instr, quant);
        pair<Real, Real> tmp;
        for (Size i=0; i<n; ++i) {
          for (Size j=0; j<quotes[i].size(); ++j) {
            tmp = bucketAnalysis(quotes[i][j], instr, quant, shift, type, npv);
            result.first[i][j] = tmp.first;
            result.second[i][j] = tmp.second;
          }
        }
        return result;
    }
Integer QuantLib::capletSwaptionPeriodicCalibration (const EvolutionDescription & evolution, const boost::shared_ptr< PiecewiseConstantCorrelation > & corr, VolatilityInterpolationSpecifier & displacedSwapVariances, const std::vector< Volatility > & capletVols, const boost::shared_ptr< CurveState > & cs, const Spread displacement, Real caplet0Swaption1Priority, Size numberOfFactors, Size period, Size max1dIterations, Real tolerance1d, Size maxUnperiodicIterations, Real toleranceUnperiodic, Size maxPeriodIterations, Real periodTolerance, Real & , Real & totalSwaptionError, std::vector< Matrix > & swapCovariancePseudoRoots, std::vector< Real > & finalScales, Size & iterationsDone, Real & errorImprovement, Matrix & modelSwaptionVolsMatrix)
Definition at line 41 of file capletcoterminalperiodic.cpp.
References QuantLib::CTSMMCapletCalibration::calibrate(), anonymous_namespace{marketmodel.cpp}::displacement, QuantLib::VolatilityInterpolationSpecifier::getNoBigRates(), QuantLib::VolatilityInterpolationSpecifier::interpolatedVariances(), QuantLib::EvolutionDescription::numberOfRates(), QuantLib::EvolutionDescription::numberOfSteps(), QuantLib::VolatilityInterpolationSpecifier::originalVariances(), QL_REQUIRE, QuantLib::EvolutionDescription::rateTimes(), QuantLib::VolatilityInterpolationSpecifier::setLastCapletVol(), and QuantLib::VolatilityInterpolationSpecifier::setScalingFactors().
Referenced by MarketModelSmmCapletHomoCalibrationTest::testPeriodFunction().
    {
        Size numberSmallRates = evolution.numberOfRates();
        Size numberSmallSteps = evolution.numberOfSteps();
        QL_REQUIRE( numberSmallSteps == numberSmallRates,
            "periodic calibration class requires evolution to the reset of each rate");
        Size numberBigRates = numberSmallRates/period;
        Size offset = numberSmallRates % period;
        std::vector<Spread> newDisplacements(numberBigRates,displacement);
        QL_REQUIRE(displacedSwapVariances.getNoBigRates() == numberBigRates,
            "mismatch between number of swap variances given and number of rates and period");
        Integer failures=0;
        std::vector<Real> scalingFactors(numberBigRates);
        for (Size i=0; i < numberBigRates; ++i)
            scalingFactors[i] =1.0;
        displacedSwapVariances.setLastCapletVol(*capletVols.rbegin());
        std::vector<Real> marketSwaptionVols(numberBigRates);
        for (Size i=0; i < numberBigRates; ++i) {
            marketSwaptionVols[i] =
                displacedSwapVariances.originalVariances()[i]->totalVolatility(i);
        }
        std::vector<Real> modelSwaptionVols(numberBigRates);
        Real periodSwaptionRmsError;
        iterationsDone = 0;
        Real previousError = 1.0e+10; // very large number
        modelSwaptionVolsMatrix =Matrix(maxPeriodIterations,numberBigRates,0.0);
        do
        {
            displacedSwapVariances.setScalingFactors(scalingFactors);
            CTSMMCapletMaxHomogeneityCalibration unperiodicCalibrator(
                evolution,
                corr,
                displacedSwapVariances.interpolatedVariances(),
                capletVols,
                cs,
                displacement,
                caplet0Swaption1Priority);
            failures= unperiodicCalibrator.calibrate(numberOfFactors, maxUnperiodicIterations,toleranceUnperiodic,max1dIterations,tolerance1d);
            swapCovariancePseudoRoots = unperiodicCalibrator.swapPseudoRoots();
            boost::shared_ptr<MarketModel> smm(new
                PseudoRootFacade(swapCovariancePseudoRoots,
                evolution.rateTimes(),
                cs->coterminalSwapRates(),
                std::vector<Spread>(evolution.numberOfRates(), displacement)));
            boost::shared_ptr<MarketModel> flmm(new CotSwapToFwdAdapter(smm));
            Matrix capletTotCovariance = flmm->totalCovariance(numberSmallRates-1);
            boost::shared_ptr<MarketModel> periodflmm( new FwdPeriodAdapter(flmm, period,
                offset,
                newDisplacements));
            boost::shared_ptr<MarketModel> periodsmm(new FwdToCotSwapAdapter(periodflmm));
            Matrix swaptionTotCovariance(periodsmm->totalCovariance(periodsmm->numberOfSteps()-1));
            totalSwaptionError=0.0;
            for (Size i=0; i < numberBigRates; ++i)
            {
                modelSwaptionVols[i] = std::sqrt(swaptionTotCovariance[i][i]/periodsmm->evolution().rateTimes()[i]);
                Real scale = marketSwaptionVols[i]/modelSwaptionVols[i];
                scalingFactors[i] *= scale; // since applied to vol
                totalSwaptionError +=  (marketSwaptionVols[i]-modelSwaptionVols[i])* (marketSwaptionVols[i]-modelSwaptionVols[i]);
            }
            for (Size i=0; i < numberBigRates; ++i)
                modelSwaptionVolsMatrix[iterationsDone][i] = modelSwaptionVols[i];
            periodSwaptionRmsError = std::sqrt(totalSwaptionError/numberBigRates);
            errorImprovement = previousError -periodSwaptionRmsError;
            previousError = periodSwaptionRmsError;
        }
        while (errorImprovement> periodTolerance/10.0 && periodSwaptionRmsError >periodTolerance && ++iterationsDone < maxPeriodIterations);
        finalScales = scalingFactors;
        return failures;
    }
Disposable< Array > QuantLib::CenteredGrid (Real center, Real dx, Size steps) [inline]
Definition at line 37 of file grid.hpp.
{
        Array result(steps+1);
        for (Size i=0; i<steps+1; i++)
            result[i] = center + (i - steps/2.0)*dx;
        return result;
    }
void QuantLib::checkCompatibility (const EvolutionDescription & evolution, const std::vector< Size > & numeraires)
Check that there is one numeraire for each evolution time. Each numeraire must be an index amongst the rate times so it ranges from 0 to n. Each numeraire must not have expired before the end of the step.
Definition at line 113 of file evolutiondescription.cpp.
References QuantLib::EvolutionDescription::evolutionTimes(), QuantLib::io::ordinal(), QL_REQUIRE, QuantLib::EvolutionDescription::rateTimes(), and anonymous_namespace{marketmodel.cpp}::rateTimes.
Referenced by QuantLib::LogNormalCmSwapRatePc::LogNormalCmSwapRatePc(), QuantLib::LogNormalCotSwapRatePc::LogNormalCotSwapRatePc(), QuantLib::LogNormalFwdRateBalland::LogNormalFwdRateBalland(), QuantLib::LogNormalFwdRateEuler::LogNormalFwdRateEuler(), QuantLib::LogNormalFwdRateEulerConstrained::LogNormalFwdRateEulerConstrained(), QuantLib::LogNormalFwdRateiBalland::LogNormalFwdRateiBalland(), QuantLib::LogNormalFwdRateIpc::LogNormalFwdRateIpc(), QuantLib::LogNormalFwdRatePc::LogNormalFwdRatePc(), QuantLib::LongstaffSchwartzExerciseStrategy::LongstaffSchwartzExerciseStrategy(), anonymous_namespace{marketmodel_smm.cpp}::makeMeasure(), anonymous_namespace{marketmodel_cms.cpp}::makeMeasure(), anonymous_namespace{marketmodel_smmcapletcalibration.cpp}::makeMeasure(), anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::makeMeasure(), anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::makeMeasure(), anonymous_namespace{marketmodel.cpp}::makeMeasure(), QuantLib::NormalFwdRatePc::NormalFwdRatePc(), and QuantLib::SVDDFwdRatePc::SVDDFwdRatePc().
    {
        const std::vector<Time>& evolutionTimes = evolution.evolutionTimes();
        Size n = evolutionTimes.size();
        QL_REQUIRE(numeraires.size() == n,
                   "Size mismatch between numeraires (" << numeraires.size()
                   << ") and evolution times (" << n << ")");
        const std::vector<Time>& rateTimes = evolution.rateTimes();
        for (Size i=0; i<n-1; i++)
            QL_REQUIRE(rateTimes[numeraires[i]] >= evolutionTimes[i],
                       io::ordinal(i+1) << " step, evolution time " <<
                       evolutionTimes[i] << ": the numeraire (" << numeraires[i] <<
                       "), corresponding to rate time " <<
                       rateTimes[numeraires[i]] << ", is expired");
    }
void QuantLib::checkIncreasingTimes (const std::vector< Time > & times)
check for strictly increasing times, first time greater than zero
Definition at line 95 of file utilities.cpp.
References QL_REQUIRE.
Referenced by QuantLib::BermudanSwaptionExerciseValue::BermudanSwaptionExerciseValue(), QuantLib::EvolutionDescription::EvolutionDescription(), exponentialCorrelations(), QuantLib::ExponentialForwardCorrelation::ExponentialForwardCorrelation(), QuantLib::MarketModelCashRebate::MarketModelCashRebate(), QuantLib::MarketModelDiscounter::MarketModelDiscounter(), QuantLib::MarketModelPathwiseCashRebate::MarketModelPathwiseCashRebate(), QuantLib::MarketModelPathwiseCoterminalSwaptionsDeflated::MarketModelPathwiseCoterminalSwaptionsDeflated(), QuantLib::MarketModelPathwiseCoterminalSwaptionsNumericalDeflated::MarketModelPathwiseCoterminalSwaptionsNumericalDeflated(), QuantLib::MarketModelPathwiseDiscounter::MarketModelPathwiseDiscounter(), QuantLib::MarketModelPathwiseInverseFloater::MarketModelPathwiseInverseFloater(), QuantLib::MarketModelPathwiseMultiCaplet::MarketModelPathwiseMultiCaplet(), QuantLib::MarketModelPathwiseMultiDeflatedCaplet::MarketModelPathwiseMultiDeflatedCaplet(), QuantLib::MarketModelPathwiseSwap::MarketModelPathwiseSwap(), QuantLib::MultiStepCoinitialSwaps::MultiStepCoinitialSwaps(), QuantLib::MultiStepCoterminalSwaps::MultiStepCoterminalSwaps(), QuantLib::MultiStepCoterminalSwaptions::MultiStepCoterminalSwaptions(), QuantLib::MultiStepForwards::MultiStepForwards(), QuantLib::MultiStepInverseFloater::MultiStepInverseFloater(), QuantLib::MultiStepOptionlets::MultiStepOptionlets(), QuantLib::MultiStepPeriodCapletSwaptions::MultiStepPeriodCapletSwaptions(), QuantLib::MultiStepRatchet::MultiStepRatchet(), QuantLib::MultiStepSwap::MultiStepSwap(), QuantLib::NothingExerciseValue::NothingExerciseValue(), QuantLib::OneStepCoinitialSwaps::OneStepCoinitialSwaps(), QuantLib::OneStepCoterminalSwaps::OneStepCoterminalSwaps(), QuantLib::OneStepForwards::OneStepForwards(), QuantLib::OneStepOptionlets::OneStepOptionlets(), QuantLib::PiecewiseConstantAbcdVariance::PiecewiseConstantAbcdVariance(), QuantLib::PseudoRootFacade::PseudoRootFacade(), QuantLib::SwapRateTrigger::SwapRateTrigger(), and QuantLib::TimeHomogeneousForwardCorrelation::TimeHomogeneousForwardCorrelation().
{
        Size nTimes = times.size();
        QL_REQUIRE(nTimes>0,
                   "at least one time is required");
        QL_REQUIRE(times[0]>0.0,
                   "first time (" << times[0] <<
                   ") must be greater than zero");
        for (Size i=0; i<nTimes-1; ++i)
            QL_REQUIRE(times[i+1]-times[i]>0,
                       "non increasing rate times: "
                       "times[" << i   << "]=" << times[i] << ", "
                       "times[" << i+1 << "]=" << times[i+1]);
    }
void QuantLib::checkIncreasingTimesAndCalculateTaus (const std::vector< Time > & times, std::vector< Time > & taus)
Definition at line 109 of file utilities.cpp.
References QL_REQUIRE.
Referenced by QuantLib::CurveState::CurveState(), and QuantLib::EvolutionDescription::EvolutionDescription().
{
        Size nTimes = times.size();
        QL_REQUIRE(nTimes>1,
                   "at least two times are required, " << nTimes << " provided");
        QL_REQUIRE(times[0]>0.0,
                   "first time (" << times[0] <<
                   ") must be greater than zero");
        if (taus.size()!=nTimes-1)
            taus.resize(nTimes-1);
        for (Size i=0; i<nTimes-1; ++i) {
            taus[i]=times[i+1]-times[i];
            QL_REQUIRE(taus[i]>0,
                       "non increasing rate times: "
                       "times[" << i   << "]=" << times[i] << ", "
                       "times[" << i+1 << "]=" << times[i+1]);
        }
    }
const Disposable<Matrix> QuantLib::CholeskyDecomposition (const Matrix & S, bool flexible) [related]
Definition at line 24 of file choleskydecomposition.cpp.
References QuantLib::Matrix::columns(), QL_REQUIRE, and QuantLib::Matrix::rows().
Referenced by QuantLib::anonymous_namespace{pseudosqrt.cpp}::hypersphereOptimize(), and pseudoSqrt().
{
        Size i, j, size = S.rows();
        QL_REQUIRE(size == S.columns(),
                   "input matrix is not a square matrix");
        #if defined(QL_EXTRA_SAFETY_CHECKS)
        for (i=0; i<S.rows(); i++)
            for (j=0; j<i; j++)
                QL_REQUIRE(S[i][j] == S[j][i],
                           "input matrix is not symmetric");
        #endif
        Matrix result(size, size, 0.0);
        Real sum;
        for (i=0; i<size; i++) {
            for (j=i; j<size; j++) {
                sum = S[i][j];
                for (Integer k=0; k<=Integer(i)-1; k++) {
                    sum -= result[i][k]*result[j][k];
                }
                if (i == j) {
                    QL_REQUIRE(flexible || sum > 0.0,
                               "input matrix is not positive definite");
                    // To handle positive semi-definite matrices take the
                    // square root of sum if positive, else zero.
                    result[i][i] = std::sqrt(std::max<Real>(sum, 0.0));
                } else {
                    // With positive semi-definite matrices is possible
                    // to have result[i][i]==0.0
                    // In this case sum happens to be zero as well
                    result[j][i] =
                        (sum==0.0 ? 0.0 : sum/result[i][i]);
                }
            }
        }
        return result;
    }
template<class F , class R > clipped_function<F,R> QuantLib::clip (const F & f, const R & r)
Definition at line 107 of file functional.hpp.
References anonymous_namespace{interpolations.cpp}::f().
Referenced by QuantLib::GenericRiskStatistics< S >::shortfall().
{
        return clipped_function<F,R>(f,r);
    }
bool QuantLib::close (Real x, Real y) [inline]
Follows somewhat the advice of Knuth on checking for floating-point equality. The closeness relationship is:
\[ \mathrm{close}(x,y,n) \equiv |x-y| \leq \varepsilon |x| \wedge |x-y| \leq \varepsilon |y| \]
where \(\varepsilon \) is \(n \) times the machine accuracy; \(n \) equals 42 if not given.
Definition at line 59 of file comparison.hpp.
References close().
{
        return close(x,y,42);
    }
bool QuantLib::close (Real x, Real y, Size n) [inline]
Definition at line 63 of file comparison.hpp.
References QL_EPSILON, and anonymous_namespace{gaussianquadratures.cpp}::tolerance.
{
        Real diff = std::fabs(x-y), tolerance = n*QL_EPSILON;
        // FLOATING_POINT_EXCEPTION
        return diff <= tolerance*std::fabs(x) &&
               diff <= tolerance*std::fabs(y);
    }
bool QuantLib::close (const Money & m1, const Money & m2, Size n) [related]
Definition at line 158 of file money.cpp.
References QuantLib::Money::AutomatedConversion, QuantLib::Money::BaseCurrencyConversion, close(), QuantLib::Money::conversionType, QuantLib::anonymous_namespace{quantity.cpp}::convertTo(), QuantLib::anonymous_namespace{quantity.cpp}::convertToBase(), QuantLib::Money::currency(), QL_FAIL, and QuantLib::Money::value().
{
        if (m1.currency() == m2.currency()) {
            return close(m1.value(),m2.value(),n);
        } else if (Money::conversionType == Money::BaseCurrencyConversion) {
            Money tmp1 = m1;
            convertToBase(tmp1);
            Money tmp2 = m2;
            convertToBase(tmp2);
            return close(tmp1,tmp2,n);
        } else if (Money::conversionType == Money::AutomatedConversion) {
            Money tmp = m2;
            convertTo(tmp, m1.currency());
            return close(m1,tmp,n);
        } else {
            QL_FAIL("currency mismatch and no conversion specified");
        }
    }
bool QuantLib::close (const Quantity & m1, const Quantity & m2, Size n) [related]
Definition at line 163 of file quantity.cpp.
References QuantLib::Quantity::amount(), QuantLib::Quantity::AutomatedConversion, QuantLib::Quantity::BaseUnitOfMeasureConversion, QuantLib::Quantity::conversionType, QuantLib::anonymous_namespace{quantity.cpp}::convertTo(), QuantLib::anonymous_namespace{quantity.cpp}::convertToBase(), QL_FAIL, and QuantLib::Quantity::unitOfMeasure().
Referenced by QuantLib::Index::addFixings(), QuantLib::DiscretizedConvertible::adjustedGrid(), QuantLib::Bond::calculateNotionalsFromCashflows(), QuantLib::CallableFixedRateBond::CallableFixedRateBond(), QuantLib::anonymous_namespace{pseudosqrt.cpp}::checkSymmetry(), close(), QuantLib::ExponentialForwardCorrelation::ExponentialForwardCorrelation(), QuantLib::InterpolatedDiscountCurve< Interpolator >::initialize(), QuantLib::InterpolatedHazardRateCurve< Interpolator >::initialize(), QuantLib::InterpolatedForwardCurve< Interpolator >::initialize(), QuantLib::InterpolatedZeroCurve< Interpolator >::initialize(), QuantLib::InterpolatedDefaultDensityCurve< Interpolator >::initialize(), QuantLib::BlackCalculator::initialize(), QuantLib::InterpolatedYoYInflationCurve< Interpolator >::InterpolatedYoYInflationCurve(), QuantLib::InterpolatedZeroInflationCurve< Interpolator >::InterpolatedZeroInflationCurve(), QuantLib::Interpolation::templateImpl< I1, I2 >::isInRange(), QuantLib::Interpolation2D::templateImpl< I1, I2, M >::isInRange(), QuantLib::Distribution::locate(), anonymous_namespace{swaptionvolatilitymatrix.cpp}::CommonVars::makeCoherenceTest(), midEquivalent(), QuantLib::TsiveriotisFernandesLattice< T >::partialRollback(), QuantLib::TreeLattice< Impl >::partialRollback(), QuantLib::CTSMMCapletCalibration::performChecks(), QuantLib::Solver1D< Ridder >::solve(), QuantLib::TridiagonalOperator::solveFor(), QuantLib::Bisection::solveImpl(), QuantLib::Brent::solveImpl(), QuantLib::FalsePosition::solveImpl(), QuantLib::Ridder::solveImpl(), QuantLib::Secant::solveImpl(), RoundingTest::testCeiling(), RoundingTest::testClosest(), anonymous_namespace{piecewiseyieldcurve.cpp}::testCurveCopy(), RngTraitsTest::testCustomPoisson(), RngTraitsTest::testDefaultPoisson(), ExchangeRateTest::testDerived(), ExchangeRateTest::testDirect(), CommodityUnitOfMeasureTest::testDirect(), ExchangeRateTest::testDirectLookup(), RoundingTest::testDown(), RoundingTest::testFloor(), TimeSeriesTest::testIntervalPrice(), DistributionTest::testInverseCumulativePoisson(), AsianOptionTest::testPastFixings(), TermStructureTest::testReferenceChange(), RiskStatisticsTest::testResults(), ExchangeRateTest::testSmartLookup(), ExchangeRateTest::testTriangulatedLookup(), RoundingTest::testUp(), QuantLib::BlackCalculator::theta(), and unsafeSabrVolatility().
{
        if (m1.unitOfMeasure() == m2.unitOfMeasure()) {
            return close(m1.amount(),m2.amount(),n);
        } else if (Quantity::conversionType
                   == Quantity::BaseUnitOfMeasureConversion) {
            Quantity tmp1 = m1;
            convertToBase(tmp1);
            Quantity tmp2 = m2;
            convertToBase(tmp2);
            return close(tmp1,tmp2,n);
        } else if (Quantity::conversionType == Quantity::AutomatedConversion) {
            Quantity tmp = m2;
            convertTo(tmp, m1.unitOfMeasure());
            return close(m1,tmp,n);
        } else {
            QL_FAIL("unitOfMeasure mismatch and no conversion specified");
        }
    }
bool QuantLib::close_enough (Real x, Real y) [inline]
Follows somewhat the advice of Knuth on checking for floating-point equality. The closeness relationship is:
\[ \mathrm{close}(x,y,n) \equiv |x-y| \leq \varepsilon |x| \vee |x-y| \leq \varepsilon |y| \]
where \(\varepsilon \) is \(n \) times the machine accuracy; \(n \) equals 42 if not given.
Definition at line 70 of file comparison.hpp.
References close_enough().
{
        return close_enough(x,y,42);
    }
bool QuantLib::close_enough (Real x, Real y, Size n) [inline]
Definition at line 74 of file comparison.hpp.
References QL_EPSILON, and anonymous_namespace{gaussianquadratures.cpp}::tolerance.
{
        Real diff = std::fabs(x-y), tolerance = n*QL_EPSILON;
        return diff <= tolerance*std::fabs(x) ||
               diff <= tolerance*std::fabs(y);
    }
bool QuantLib::close_enough (const Money & m1, const Money & m2, Size n) [related]
Definition at line 176 of file money.cpp.
References QuantLib::Money::AutomatedConversion, QuantLib::Money::BaseCurrencyConversion, close_enough(), QuantLib::Money::conversionType, QuantLib::anonymous_namespace{quantity.cpp}::convertTo(), QuantLib::anonymous_namespace{quantity.cpp}::convertToBase(), QuantLib::Money::currency(), QL_FAIL, and QuantLib::Money::value().
{
        if (m1.currency() == m2.currency()) {
            return close_enough(m1.value(),m2.value(),n);
        } else if (Money::conversionType == Money::BaseCurrencyConversion) {
            Money tmp1 = m1;
            convertToBase(tmp1);
            Money tmp2 = m2;
            convertToBase(tmp2);
            return close_enough(tmp1,tmp2,n);
        } else if (Money::conversionType == Money::AutomatedConversion) {
            Money tmp = m2;
            convertTo(tmp, m1.currency());
            return close_enough(m1,tmp,n);
        } else {
            QL_FAIL("currency mismatch and no conversion specified");
        }
    }
bool QuantLib::close_enough (const Quantity & m1, const Quantity & m2, Size n) [related]
Definition at line 182 of file quantity.cpp.
References QuantLib::Quantity::amount(), QuantLib::Quantity::AutomatedConversion, QuantLib::Quantity::BaseUnitOfMeasureConversion, QuantLib::Quantity::conversionType, QuantLib::anonymous_namespace{quantity.cpp}::convertTo(), QuantLib::anonymous_namespace{quantity.cpp}::convertToBase(), QL_FAIL, and QuantLib::Quantity::unitOfMeasure().
Referenced by QuantLib::Histogram::calculate(), QuantLib::TermStructure::checkRange(), close_enough(), QuantLib::TimeGrid::index(), QuantLib::DiscretizedAsset::isOnTime(), QuantLib::DiscretizedAsset::postAdjustValues(), QuantLib::DiscretizedAsset::preAdjustValues(), QuantLib::InverseCumulativeNormal::tail_value(), and QuantLib::TimeGrid::TimeGrid().
{
        if (m1.unitOfMeasure() == m2.unitOfMeasure()) {
            return close_enough(m1.amount(),m2.amount(),n);
        } else if (Quantity::conversionType
                   == Quantity::BaseUnitOfMeasureConversion) {
            Quantity tmp1 = m1;
            convertToBase(tmp1);
            Quantity tmp2 = m2;
            convertToBase(tmp2);
            return close_enough(tmp1,tmp2,n);
        } else if (Quantity::conversionType == Quantity::AutomatedConversion) {
            Quantity tmp = m2;
            convertTo(tmp, m1.unitOfMeasure());
            return close_enough(m1,tmp,n);
        } else {
            QL_FAIL("unitOfMeasure mismatch and no conversion specified");
        }
    }
void QuantLib::collectNodeData (MarketModelEvolver & evolver, MarketModelMultiProduct & product, MarketModelNodeDataProvider & dataProvider, MarketModelExerciseValue & rebate, MarketModelExerciseValue & control, Size numberOfPaths, std::vector< std::vector< NodeData > > & collectedData)
Definition at line 36 of file collectnodedata.cpp.
References QuantLib::MarketModelEvolver::advanceStep(), QuantLib::CashFlow::amount(), QuantLib::NodeData::controlValue, QuantLib::NodeData::cumulatedCashFlows, QuantLib::MarketModelEvolver::currentState(), QuantLib::MarketModelEvolver::currentStep(), anonymous_namespace{stats.cpp}::data, QuantLib::CurveState::discountRatio(), QuantLib::MarketModelExerciseValue::evolution(), QuantLib::MarketModelNodeDataProvider::evolution(), QuantLib::MarketModelMultiProduct::evolution(), QuantLib::EvolutionDescription::evolutionTimes(), anonymous_namespace{swaption.cpp}::exercises, QuantLib::NodeData::exerciseValue, QuantLib::MarketModelExerciseValue::isExerciseTime(), isInSubset(), QuantLib::NodeData::isValid, QuantLib::MarketModelMultiProduct::maxNumberOfCashFlowsPerProductPerStep(), QuantLib::MarketModelNodeDataProvider::nextStep(), QuantLib::MarketModelExerciseValue::nextStep(), QuantLib::MarketModelMultiProduct::nextTimeStep(), QuantLib::MarketModelMultiProduct::numberOfProducts(), QuantLib::MarketModelEvolver::numeraires(), QuantLib::MarketModelExerciseValue::possibleCashFlowTimes(), QuantLib::MarketModelMultiProduct::possibleCashFlowTimes(), QL_REQUIRE, QuantLib::EvolutionDescription::rateTimes(), anonymous_namespace{marketmodel.cpp}::rateTimes, QuantLib::MarketModelNodeDataProvider::reset(), QuantLib::MarketModelExerciseValue::reset(), QuantLib::MarketModelMultiProduct::reset(), QuantLib::MarketModelEvolver::startNewPath(), anonymous_namespace{perturbativebarrieroptionengine.cpp}::v(), QuantLib::MarketModelExerciseValue::value(), QuantLib::NodeData::values, and QuantLib::MarketModelNodeDataProvider::values().
Referenced by MarketModelTest::testCallableSwapAnderson(), and MarketModelTest::testCallableSwapLS().
{
        std::vector<Real> numerairesHeld;
        QL_REQUIRE(product.numberOfProducts() == 1,
                   "a single product is required");
        // TODO: check that all objects have compatible evolutions
        // (same rate times; evolution times for product, basis
        // system, rebate and control must be subsets of the passed
        // evolution times; rebate, control and basis system must have
        // the same exercise---not evolution---times)
        std::vector<Size> numberCashFlowsThisStep(1);
        std::vector<std::vector<CashFlow> > cashFlowsGenerated(1);
        cashFlowsGenerated[0].resize(
                           product.maxNumberOfCashFlowsPerProductPerStep());
        std::vector<Time> rateTimes = product.evolution().rateTimes();
        std::vector<Time> cashFlowTimes = product.possibleCashFlowTimes();
        std::vector<Time> rebateTimes = rebate.possibleCashFlowTimes();
        std::vector<Time> controlTimes = control.possibleCashFlowTimes();
        Size i, n;
        n = cashFlowTimes.size();
        std::vector<MarketModelDiscounter> productDiscounters;
        productDiscounters.reserve(n);
        for (i=0; i<n; ++i)
            productDiscounters.push_back(
                                     MarketModelDiscounter(cashFlowTimes[i],
                                                           rateTimes));
        n = rebateTimes.size();
        std::vector<MarketModelDiscounter> rebateDiscounters;
        rebateDiscounters.reserve(n);
        for (i=0; i<n; ++i)
            rebateDiscounters.push_back(
                                     MarketModelDiscounter(rebateTimes[i],
                                                           rateTimes));
        n = controlTimes.size();
        std::vector<MarketModelDiscounter> controlDiscounters;
        controlDiscounters.reserve(n);
        for (i=0; i<n; ++i)
            controlDiscounters.push_back(
                                     MarketModelDiscounter(controlTimes[i],
                                                           rateTimes));
        EvolutionDescription evolution = product.evolution();
        const std::vector<Size>& numeraires = evolver.numeraires();
        std::vector<Time> evolutionTimes = evolution.evolutionTimes();
        std::valarray<bool> isProductTime =
            isInSubset(evolutionTimes,
                       product.evolution().evolutionTimes());
        std::valarray<bool> isRebateTime =
            isInSubset(evolutionTimes,
                       rebate.evolution().evolutionTimes());
        std::valarray<bool> isControlTime =
            isInSubset(evolutionTimes,
                       control.evolution().evolutionTimes());
        std::valarray<bool> isBasisTime =
            isInSubset(evolutionTimes,
                       dataProvider.evolution().evolutionTimes());
        std::valarray<bool> isExerciseTime(false,evolutionTimes.size());
        std::valarray<bool> v = rebate.isExerciseTime();
        Size exercises = 0;
        for (i=0; i<evolutionTimes.size(); ++i) {
            if (isRebateTime[i]) {
                isExerciseTime[i] = v[exercises];
                ++exercises;
            }
        }
        collectedData.resize(exercises+1);
        for (i=0; i<collectedData.size(); ++i)
            collectedData[i].resize(numberOfPaths);
        for (i=0; i<numberOfPaths; ++i) {
            evolver.startNewPath();
            product.reset();
            rebate.reset();
            control.reset();
            dataProvider.reset();
            Real principalInNumerairePortfolio = 1.0;
            bool done = false;
            Size nextExercise = 0;
            collectedData[0][i].cumulatedCashFlows = 0.0;
            do {
                Size currentStep = evolver.currentStep();
                evolver.advanceStep();
                const CurveState& currentState = evolver.currentState();
                Size numeraire = numeraires[currentStep];
                if (isRebateTime[currentStep])
                    rebate.nextStep(currentState);
                if (isControlTime[currentStep])
                    control.nextStep(currentState);
                if (isBasisTime[currentStep])
                    dataProvider.nextStep(currentState);
                if (isExerciseTime[currentStep]) {
                    NodeData& data = collectedData[nextExercise+1][i];
                    CashFlow exerciseValue = rebate.value(currentState);
                    data.exerciseValue =
                        exerciseValue.amount *
                        rebateDiscounters[exerciseValue.timeIndex]
                           .numeraireBonds(currentState, numeraire) /
                        principalInNumerairePortfolio;
                    dataProvider.values(currentState,
                                        data.values);
                    CashFlow controlValue = control.value(currentState);
                    data.controlValue =
                        controlValue.amount *
                        controlDiscounters[controlValue.timeIndex]
                           .numeraireBonds(currentState, numeraire) /
                        principalInNumerairePortfolio;
                    data.cumulatedCashFlows = 0.0;
                    data.isValid = true;
                    ++nextExercise;
                }
                if (isProductTime[currentStep]) {
                    done = product.nextTimeStep(currentState,
                                                numberCashFlowsThisStep,
                                                cashFlowsGenerated);
                    for (Size j=0; j<numberCashFlowsThisStep[0]; ++j) {
                        const CashFlow& cf = cashFlowsGenerated[0][j];
                        collectedData[nextExercise][i].cumulatedCashFlows +=
                            cf.amount *
                            productDiscounters[cf.timeIndex]
                                .numeraireBonds(currentState, numeraire) /
                            principalInNumerairePortfolio;
                    }
                }
                if (!done) {
                    Size nextNumeraire = numeraires[currentStep+1];
                    principalInNumerairePortfolio *=
                        currentState.discountRatio(numeraire,
                                                   nextNumeraire);
                }
            }
            while (!done);
            // fill the remaining (un)collected data with nulls
            for (Size j = nextExercise; j < exercises; ++j) {
                NodeData& data = collectedData[j+1][i];
                data.exerciseValue = data.controlValue = 0.0;
                data.cumulatedCashFlows = 0.0;
                data.isValid = false;
            }
        }
    }
template<class F , class G > composed_function<F,G> QuantLib::compose (const F & f, const G & g)
Definition at line 127 of file functional.hpp.
References anonymous_namespace{interpolations.cpp}::f().
Referenced by QuantLib::FdmLogInnerValue::avgInnerValueCalc(), QuantLib::FdmHestonVarianceMesher::FdmHestonVarianceMesher(), QuantLib::GeneralStatistics::kurtosis(), QuantLib::InverseNonCentralChiSquareDistribution::operator()(), QuantLib::GenericRiskStatistics< S >::regret(), QuantLib::GeneralStatistics::skewness(), and QuantLib::GeneralStatistics::variance().
{
        return composed_function<F,G>(f,g);
    }
template<class F , class G , class H > binary_compose3_function<F, G, H> QuantLib::compose3 (const F & f, const G & g, const H & h)
Definition at line 156 of file functional.hpp.
References anonymous_namespace{interpolations.cpp}::f().
{
        return binary_compose3_function<F, G, H>(f, g, h);
    }
void QuantLib::constantMaturityFromDiscountRatios (const Size spanningForwards, const Size firstValidIndex, const std::vector< DiscountFactor > & ds, const std::vector< Time > & taus, std::vector< Rate > & constMatSwapRates, std::vector< Real > & constMatSwapAnnuities)
Definition at line 88 of file curvestate.cpp.
References QL_REQUIRE.
Referenced by QuantLib::CMSwapCurveState::cmSwapAnnuity(), QuantLib::CoterminalSwapCurveState::cmSwapAnnuity(), QuantLib::LMMCurveState::cmSwapAnnuity(), QuantLib::CMSwapCurveState::cmSwapRate(), QuantLib::CoterminalSwapCurveState::cmSwapRate(), QuantLib::LMMCurveState::cmSwapRate(), QuantLib::CMSwapCurveState::cmSwapRates(), QuantLib::CoterminalSwapCurveState::cmSwapRates(), and QuantLib::LMMCurveState::cmSwapRates().
{
        Size nConstMatSwapRates = constMatSwapRates.size();
        QL_REQUIRE(taus.size()==nConstMatSwapRates,
                   "taus.size()!=nConstMatSwapRates");
        QL_REQUIRE(constMatSwapAnnuities.size()==nConstMatSwapRates,
                   "constMatSwapAnnuities.size()!=nConstMatSwapRates");
        QL_REQUIRE(ds.size()==nConstMatSwapRates+1,
                   "ds.size()!=nConstMatSwapRates+1");
        // compute the first cmsrate and cmsannuity
        constMatSwapAnnuities[firstValidIndex]=0.;
        Size lastIndex = std::min(firstValidIndex+spanningForwards,nConstMatSwapRates);
        for (Size i=firstValidIndex; i<lastIndex; ++i) {
            constMatSwapAnnuities[firstValidIndex]+= taus[i] * ds[i+1];
        }
        constMatSwapRates[firstValidIndex] =
            (ds[firstValidIndex]-ds[lastIndex])/
                constMatSwapAnnuities[firstValidIndex];
        Size oldLastIndex = lastIndex;
        // compute all the other cmas rates and cms annuities
        for (Size i=firstValidIndex+1; i<nConstMatSwapRates; ++i) {
            Size lastIndex = std::min(i+spanningForwards,nConstMatSwapRates);
            constMatSwapAnnuities[i] = constMatSwapAnnuities[i-1]
                                       - taus[i-1] * ds[i];
            if (lastIndex!=oldLastIndex)
               constMatSwapAnnuities[i] += taus[lastIndex-1] * ds[lastIndex];
            constMatSwapRates[i] = (ds[i]-ds[lastIndex])
                /constMatSwapAnnuities[i];
            oldLastIndex = lastIndex;
        }
    }
template<typename ForwardIterator , typename OutputIterator > void QuantLib::convolutions (ForwardIterator begin, ForwardIterator end, OutputIterator out, std::size_t maxLag)
Convolutions of the input sequence.
Calculates x[0]*x[n]+x[1]*x[n+1]+x[2]*x[n+2]+... for n = 0,1,...,maxLag via FFT.
Precondition:
The size of the output sequence must be maxLag + 1
Definition at line 77 of file autocovariance.hpp.
References QuantLib::detail::double_ft(), and QL_REQUIRE.
Referenced by AutocovariancesTest::testConvolutions().
{
        using namespace detail;
        std::size_t nData = std::distance(begin, end);
        QL_REQUIRE(maxLag < nData, "maxLag must be less than data size");
        const std::vector<std::complex<Real> >& ft = double_ft(begin, end);
        std::size_t nFrq = ft.size();
        for (std::size_t k = 0; k <= maxLag; ++k)
            *out++ = ft[k].real() / nFrq;
    }
void QuantLib::coterminalFromDiscountRatios (const Size firstValidIndex, const std::vector< DiscountFactor > & discountFactors, const std::vector< Time > & taus, std::vector< Rate > & cotSwapRates, std::vector< Real > & cotSwapAnnuities)
Definition at line 58 of file curvestate.cpp.
References QL_REQUIRE.
Referenced by QuantLib::CMSwapCurveState::coterminalSwapAnnuity(), QuantLib::CMSwapCurveState::coterminalSwapRate(), QuantLib::CMSwapCurveState::coterminalSwapRates(), and QuantLib::LMMCurveState::coterminalSwapRates().
    {
        Size nCotSwapRates = cotSwapRates.size();
        QL_REQUIRE(taus.size()==nCotSwapRates,
                   "taus.size()!=cotSwapRates.size()");
        QL_REQUIRE(cotSwapAnnuities.size()==nCotSwapRates,
                   "cotSwapAnnuities.size()!=cotSwapRates.size()");
        QL_REQUIRE(discountFactors.size()==nCotSwapRates+1,
                   "discountFactors.size()!=cotSwapRates.size()+1");
        cotSwapAnnuities[nCotSwapRates-1] =
            taus[nCotSwapRates-1]*discountFactors[nCotSwapRates];
        cotSwapRates[nCotSwapRates-1] =
            (discountFactors[nCotSwapRates-1]-discountFactors[nCotSwapRates])
                /cotSwapAnnuities[nCotSwapRates-1];
        for (Size i=nCotSwapRates-1; i>firstValidIndex; --i) {
            cotSwapAnnuities[i-1] = cotSwapAnnuities[i] + taus[i-1] * discountFactors[i];
            cotSwapRates[i-1] =
                (discountFactors[i-1]-discountFactors[nCotSwapRates])
                /cotSwapAnnuities[i-1];
        }
    }
std::vector<Real> QuantLib::coterminalSwapPseudoRoots (const PiecewiseConstantCorrelation & , const std::vector< boost::shared_ptr< PiecewiseConstantVariance > > & , const std::vector< Time > &)
std::vector<Matrix> QuantLib::coterminalSwapPseudoRoots (const PiecewiseConstantCorrelation & piecewiseConstantCorrelation, const std::vector< boost::shared_ptr< PiecewiseConstantVariance > > & piecewiseConstantVariances)
Definition at line 88 of file marketmodeldifferences.cpp.
References QuantLib::PiecewiseConstantCorrelation::correlation(), QL_ENSURE, anonymous_namespace{marketmodel.cpp}::rateTimes, QuantLib::Matrix::row_begin(), QuantLib::Matrix::row_end(), QuantLib::Matrix::rows(), QuantLib::PiecewiseConstantCorrelation::times(), and QuantLib::io::volatility().
{
            QL_ENSURE(piecewiseConstantCorrelation.times()
                == piecewiseConstantVariances.front()->rateTimes(),
                "correlations and volatilities intertave");
            std::vector<Matrix> peudoRoots;
            const std::vector<Time>& rateTimes
                = piecewiseConstantVariances.front()->rateTimes();
            for (Size i=1; i<rateTimes.size(); ++i) {
                Time sqrtTau = std::sqrt(rateTimes[i]-rateTimes[i-1]);
                const Matrix& correlations
                    = piecewiseConstantCorrelation.correlation(i);
                Matrix pseudoRoot(correlations.rows(), correlations.rows());
                for (Size j=0; j<correlations.rows(); ++j) {
                    Real volatility
                      = piecewiseConstantVariances[j]->volatility(i)*sqrtTau;
                    std::transform(correlations.row_begin(j),
                                   correlations.row_end(j),
                                   pseudoRoot.row_begin(j),
                                   std::bind2nd(std::multiplies<Real>(),
                                                            volatility));
                }
                peudoRoots.push_back(pseudoRoot);
            }
            return peudoRoots;
    }
Real QuantLib::days (const Period & p) [related]
Definition at line 326 of file period.cpp.
References Days, QuantLib::Period::length(), Months, QL_FAIL, QuantLib::Period::units(), Weeks, and Years.
Referenced by QuantLib::Date::operator+=(), QuantLib::Date::operator-=(), QuantLib::anonymous_namespace{averagebmacoupon.cpp}::AverageBMACouponPricer::swapletRate(), TermStructureTest::testReferenceChange(), and QuantLib::KInterpolatedYoYOptionletVolatilitySurface< Interpolator1D >::volatilityImpl().
{
        if (p.length()==0) return 0.0;
        switch (p.units()) {
          case Days:
              return p.length();
          case Weeks:
              return p.length()*7.0;
          case Months:
            QL_FAIL("cannot convert Months into Days");
          case Years:
            QL_FAIL("cannot convert Years into Days");
          default:
            QL_FAIL("unknown time unit (" << Integer(p.units()) << ")");
        }
    }
Real QuantLib::defaultThetaPerDay (Real theta)
default theta-per-day calculation
Definition at line 37 of file greeks.cpp.
{
        return theta/365.0;
    }
Real QuantLib::determinant (const Matrix & m) [related]
Definition at line 75 of file matrix.cpp.
References anonymous_namespace{marketmodel.cpp}::a, QuantLib::Matrix::begin(), QuantLib::Matrix::columns(), QuantLib::Matrix::end(), QL_FAIL, QL_REQUIRE, and QuantLib::Matrix::rows().
Referenced by MatricesTest::testDeterminant().
{
        #if !defined(QL_NO_UBLAS_SUPPORT)
        QL_REQUIRE(m.rows() == m.columns(), "matrix is not square");
        boost::numeric::ublas::matrix<Real> a(m.rows(), m.columns());
        std::copy(m.begin(), m.end(), a.data().begin());
        // lu decomposition
        boost::numeric::ublas::permutation_matrix<Size> pert(m.rows());
        /* const Size singular = */ lu_factorize(a, pert);
        Real retVal = 1.0;
        for (Size i=0; i < m.rows(); ++i) {
            if (pert[i] != i)
                retVal *= -a(i,i);
            else
                retVal *=  a(i,i);
        }
        return retVal;
        #else
        QL_FAIL("this version of gcc does not support "
                "the Boost uBLAS library");
        #endif
    }
std::vector< boost::shared_ptr< Dividend > > QuantLib::DividendVector (const std::vector< Date > & dividendDates, const std::vector< Real > & dividends)
helper function building a sequence of fixed dividends
Definition at line 35 of file dividend.cpp.
References anonymous_namespace{marketmodel.cpp}::d, and QL_REQUIRE.
{
        QL_REQUIRE(dividendDates.size() == dividends.size(),
                   "size mismatch between dividend dates and amounts");
        std::vector<Date>::const_iterator dd;
        std::vector<Real>::const_iterator d;
        std::vector<boost::shared_ptr<Dividend> > items;
        items.reserve(dividendDates.size());
        for (dd = dividendDates.begin(), d = dividends.begin();
             dd != dividendDates.end(); dd++, d++) {
            items.push_back(boost::shared_ptr<Dividend>(new
                FixedDividend(*d, *dd)));
        }
        return items;
    }
Real QuantLib::DotProduct (const Array & v1, const Array & v2) [related]
Definition at line 469 of file array.hpp.
References QuantLib::Array::begin(), QuantLib::Array::end(), QuantLib::dsd::inner_product(), QL_REQUIRE, and QuantLib::Array::size().
Referenced by QuantLib::anonymous_namespace{simplex.cpp}::computeSimplexSize(), QuantLib::LineSearchBasedMethod::minimize(), anonymous_namespace{matrices.cpp}::norm(), QuantLib::BiCGstab::norm2(), QuantLib::ArmijoLineSearch::operator()(), QuantLib::EuropeanPathMultiPathPricer::operator()(), QuantLib::TreeLattice< Impl >::presentValue(), QuantLib::BiCGstab::solve(), AutocovariancesTest::testAutoCorrelations(), AutocovariancesTest::testAutoCovariances(), FdmLinearOpTest::testBiCGstab(), AutocovariancesTest::testConvolutions(), QuantLib::LeastSquareFunction::value(), QuantLib::FrobeniusCostFunction::value(), QuantLib::LeastSquareFunction::valueAndGradient(), and QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::vecNorm().
{
        QL_REQUIRE(v1.size() == v2.size(),
                   "arrays with different sizes (" << v1.size() << ", "
                   << v2.size() << ") cannot be multiplied");
        return std::inner_product(v1.begin(),v1.end(),v2.begin(),0.0);
    }
std::string QuantLib::exerciseTypeToString (const boost::shared_ptr< Exercise > & h)
Definition at line 47 of file utilities.cpp.
References CHECK_DOWNCAST, and QL_FAIL.
{
        CHECK_DOWNCAST(EuropeanExercise, "European");
        CHECK_DOWNCAST(AmericanExercise, "American");
        CHECK_DOWNCAST(BermudanExercise, "Bermudan");
        QL_FAIL("unknown exercise type");
    }
const Disposable<Array> QuantLib::Exp (const Array & v) [related]
Definition at line 618 of file array.hpp.
References QuantLib::Array::begin(), QuantLib::Array::end(), and QuantLib::Array::size().
Referenced by VPPTest::testKlugeExtOUSpreadOption().
{
        Array result(v.size());
        std::transform(v.begin(),v.end(),result.begin(),
                       std::ptr_fun<Real,Real>(std::exp));
        return result;
    }
Disposable< Matrix > QuantLib::exponentialCorrelations (const std::vector< Time > & rateTimes, Real longTermCorr = 0.5, Real beta = 0.2, Real gamma = 1.0, Time t = 0.0)
Exponential correlation L = long term correlation beta = exponential decay of correlation between far away forward rates gamma = exponent for time to go t = time dependence
Definition at line 31 of file expcorrelations.cpp.
References checkIncreasingTimes(), QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow(), and QL_REQUIRE.
Referenced by QuantLib::FlatVolFactory::create(), QuantLib::ExponentialForwardCorrelation::ExponentialForwardCorrelation(), anonymous_namespace{marketmodel_cms.cpp}::makeMarketModel(), anonymous_namespace{marketmodel_smm.cpp}::makeMarketModel(), anonymous_namespace{marketmodel_smmcapletcalibration.cpp}::makeMarketModel(), anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::makeMarketModel(), anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::makeMarketModel(), anonymous_namespace{marketmodel.cpp}::makeMarketModel(), SwapForwardMappingsTest::testForwardCoterminalMappings(), and SwapForwardMappingsTest::testSwaptionImpliedVolatility().
{
        // preliminary checks
        checkIncreasingTimes(rateTimes);
        QL_REQUIRE(longTermCorr<=1.0 && longTermCorr>=0.0,
                   "Long term correlation (" << longTermCorr <<
                   ") outside [0;1] interval");
        QL_REQUIRE(beta>=0.0,
                   "beta (" << beta <<
                   ") must be greater than zero");
        QL_REQUIRE(gamma<=1.0 && gamma>=0.0,
                   "gamma (" << gamma <<
                   ") outside [0;1] interval");
        // Calculate correlation matrix
        Size nbRows = rateTimes.size()-1;
        Matrix correlations(nbRows, nbRows, 0.0);
        for (Size i=0; i<nbRows; ++i) {
            // correlation is defined only between
            // (alive) stochastic rates...
            if (time<=rateTimes[i]) {
                correlations[i][i] = 1.0;
                for (Size j=0; j<i; ++j) {
                    if (time<=rateTimes[j]) {
                        correlations[i][j] = correlations[j][i] =
                            longTermCorr + (1.0-longTermCorr) *
                            std::exp(-beta*std::fabs(
                                std::pow(rateTimes[i]-time, gamma) -
                                std::pow(rateTimes[j]-time, gamma)
                                )
                            );
                    }
                }
            }
        }
        return correlations;
    }
Disposable< std::vector< Real > > QuantLib::factorReduction (Matrix mtrx, Size maxIters = 25)
Iterative procedure to compute a correlation matrix reduction to a single factor dependence vector by minimizing the residuals.
It assumes that such a reduction is possible, notice that if the dependence can not be reduced to one factor the correlation factors might be above 1.
The matrix passed is destroyed.
See for instance: "Modern Factor Analysis", Harry H. Harman, University Of Chicago Press, 1976. Chapter 9 is relevant to this context.
Definition at line 27 of file factorreduction.cpp.
References QuantLib::Matrix::begin(), QuantLib::Array::begin(), QuantLib::Matrix::columns(), QuantLib::SymmetricSchurDecomposition::eigenvalues(), QuantLib::Matrix::end(), QuantLib::Array::end(), QL_REQUIRE, QuantLib::Matrix::rows(), and anonymous_namespace{gaussianquadratures.cpp}::tolerance.
{
        static Real tolerance = 1.e-6;
        QL_REQUIRE(mtrx.rows() == mtrx.columns(),
                   "Input matrix is not square");
        const Size n = mtrx.columns();
        #if defined(QL_EXTRA_SAFETY_CHECKS)
        // check symmetry
        for (Size iRow=0; iRow<mtrx.rows(); iRow++)
            for (Size iCol=0; iCol<iRow; iCol++)
                QL_REQUIRE(mtrx[iRow][iCol] == mtrx[iCol][iRow],
                           "input matrix is not symmetric");
        QL_REQUIRE(*std::max_element(mtrx.begin(), mtrx.end()) <=1 &&
            *std::min_element(mtrx.begin(), mtrx.end()) >=-1,
                    "input matrix data is not correlation data");
        #endif
        // Initial guess value
        std::vector<Real> previousCorrels(n, 0.);
        for(Size iCol=0; iCol<n; iCol++) {
            for(Size iRow=0; iRow<n; iRow++)
                previousCorrels[iCol] +=
                    mtrx[iRow][iCol] * mtrx[iRow][iCol];
            previousCorrels[iCol] =
                std::sqrt((previousCorrels[iCol]-1.)/(n-1.));
        }
        // iterative solution
        Size iteration = 0;
        Real distance;
        do {
            // patch Matrix diagonal
            for(Size iCol=0; iCol<n; iCol++)
                mtrx[iCol][iCol] =
                    previousCorrels[iCol];
            // compute eigenvector decomposition
            SymmetricSchurDecomposition ssDec(mtrx);
            //const Matrix& eigenVect = ssDec.eigenvectors();
            const Array&  eigenVals = ssDec.eigenvalues();
            Array::const_iterator itMaxEval =
                std::max_element(eigenVals.begin(), eigenVals.end());
            // We do not need the max value, only the position of the
            //   corresponding eigenvector
            Size iMax = std::distance(eigenVals.begin(), itMaxEval);
            std::vector<Real> newCorrels, distances;
            for(Size iCol=0; iCol<n; iCol++) {
                Real thisCorrel = mtrx[iMax][iCol];
                newCorrels.push_back(thisCorrel);
                // strictly is:
                // abs(\sqrt{\rho}- \sqrt{\rho_{old}})/\sqrt{\rho_{old}}
                distances.push_back(
                    std::abs(thisCorrel - previousCorrels[iCol])/
                        previousCorrels[iCol]);
            }
            previousCorrels = newCorrels;
            distance = *std::max_element(distances.begin(), distances.end());
        }while(distance > tolerance && ++iteration <= maxIters );
        // test it did not go up to the max iteration and the matrix can
        //   be reduced to one factor.
        QL_REQUIRE(iteration < maxIters,
                   "convergence not reached after " <<
                   iteration << " iterations");
        #if defined(QL_EXTRA_SAFETY_CHECKS)
        QL_REQUIRE(*std::max_element(previousCorrels.begin(),
                                     previousCorrels.end()) <=1 &&
                   *std::min_element(previousCorrels.begin(),
                                     previousCorrels.end()) >=-1,
                "matrix can not be decomposed to a single factor dependence");
        #endif
        return previousCorrels;
    }
Real QuantLib::fInverse_ (Real x)
Definition at line 56 of file generalizedhullwhite.cpp.
Referenced by QuantLib::GeneralizedHullWhite::Helper::operator()().
{
        return std::exp(x);
    }
boost::shared_ptr< YieldTermStructure > QuantLib::flatRate (const Date & today, const boost::shared_ptr< Quote > & forward, const DayCounter & dc)
Definition at line 58 of file utilities.cpp.
Referenced by QuantLib::CashFlows::bps(), anonymous_namespace{digitalcoupon.cpp}::CommonVars::CommonVars(), anonymous_namespace{capfloor.cpp}::CommonVars::CommonVars(), anonymous_namespace{capflooredcoupon.cpp}::CommonVars::CommonVars(), anonymous_namespace{cms.cpp}::CommonVars::CommonVars(), anonymous_namespace{convertiblebonds.cpp}::CommonVars::CommonVars(), anonymous_namespace{assetswap.cpp}::CommonVars::CommonVars(), anonymous_namespace{swap.cpp}::CommonVars::CommonVars(), anonymous_namespace{swaption.cpp}::CommonVars::CommonVars(), anonymous_namespace{swaptionvolatilitycube.cpp}::CommonVars::CommonVars(), anonymous_namespace{overnightindexedswap.cpp}::CommonVars::CommonVars(), flatRate(), anonymous_namespace{hestonmodel.cpp}::getDAXCalibrationMarketData(), QuantLib::CreditDefaultSwap::impliedHazardRate(), anonymous_namespace{hybridhestonhullwhiteprocess.cpp}::makeHestonProcess(), CashFlowsTest::testAccessViolation(), HestonModelTest::testAlanLewisReferencePrices(), MargrabeOptionTest::testAmericanExchangeTwoAssets(), BatesModelTest::testAnalyticAndMcVsJumpDiffusion(), LookbackOptionTest::testAnalyticContinuousFixedLookback(), LookbackOptionTest::testAnalyticContinuousFloatingLookback(), AsianOptionTest::testAnalyticContinuousGeometricAveragePrice(), AsianOptionTest::testAnalyticContinuousGeometricAveragePriceGreeks(), AsianOptionTest::testAnalyticDiscreteGeometricAveragePrice(), AsianOptionTest::testAnalyticDiscreteGeometricAveragePriceGreeks(), AsianOptionTest::testAnalyticDiscreteGeometricAverageStrike(), ChooserOptionTest::testAnalyticSimpleChooserEngine(), BatesModelTest::testAnalyticVsBlack(), HestonModelTest::testAnalyticVsBlack(), HestonModelTest::testAnalyticVsCached(), BatesModelTest::testAnalyticVsMCPricing(), WriterExtensibleOptionTest::testAnalyticWriterExtensibleOptionEngine(), DigitalOptionTest::testAssetAtExpiryOrNothingAmericanValues(), DigitalOptionTest::testAssetAtHitOrNothingAmericanValues(), DigitalCouponTest::testAssetOrNothing(), DigitalOptionTest::testAssetOrNothingEuropeanValues(), BarrierOptionTest::testBabsiriValues(), AmericanOptionTest::testBaroneAdesiWhaleyValues(), BasketOptionTest::testBarraquandThreeValues(), QuantoOptionTest::testBarrierValues(), BarrierOptionTest::testBeagleholeValues(), AmericanOptionTest::testBjerksundStenslandValues(), HestonModelTest::testBlackCalibration(), HybridHestonHullWhiteProcessTest::testBsmHullWhiteEngine(), OperatorTest::testBSMOperatorConsistency(), HimalayaOptionTest::testCached(), PagodaOptionTest::testCached(), EverestOptionTest::testCached(), BondTest::testCached(), BondTest::testCachedFixed(), BondTest::testCachedFloating(), ShortRateModelTest::testCachedHullWhite(), OvernightIndexedSwapTest::testCachedValue(), SwaptionTest::testCachedValue(), SwapTest::testCachedValue(), CapFloorTest::testCachedValue(), BermudanSwaptionTest::testCachedValues(), BondTest::testCachedZero(), HybridHestonHullWhiteProcessTest::testCallableEquityPricing(), DigitalOptionTest::testCashAtExpiryOrNothingAmericanValues(), DigitalOptionTest::testCashAtHitOrNothingAmericanGreeks(), DigitalOptionTest::testCashAtHitOrNothingAmericanValues(), DigitalCouponTest::testCashOrNothing(), DigitalOptionTest::testCashOrNothingEuropeanValues(), FdmLinearOpTest::testCrankNicolsonWithDamping(), GJRGARCHModelTest::testDAXCalibration(), BatesModelTest::testDAXCalibration(), HestonModelTest::testDifferentIntegrals(), anonymous_namespace{extendedtrees.cpp}::testEngineConsistency(), anonymous_namespace{europeanoption.cpp}::testEngineConsistency(), GJRGARCHModelTest::testEngines(), MargrabeOptionTest::testEuroExchangeTwoAssets(), DividendOptionTest::testEuropeanEndLimit(), DividendOptionTest::testEuropeanGreeks(), DividendOptionTest::testEuropeanKnownValue(), DividendOptionTest::testEuropeanStartLimit(), DividendOptionTest::testEuropeanValues(), BasketOptionTest::testEuroTwoValues(), SwingOptionTest::testExtOUJumpSwingOption(), SwingOptionTest::testExtOUJumpVanillaEngine(), HestonModelTest::testFdBarrierVsCached(), SwingOptionTest::testFdBSSwingOption(), anonymous_namespace{dividendoption.cpp}::testFdDegenerate(), DividendOptionTest::testFdEuropeanValues(), anonymous_namespace{americanoption.cpp}::testFdGreeks(), anonymous_namespace{dividendoption.cpp}::testFdGreeks(), FdHestonTest::testFdmHestonAmerican(), FdmLinearOpTest::testFdmHestonAmerican(), FdHestonTest::testFdmHestonBarrier(), FdmLinearOpTest::testFdmHestonBarrier(), FdHestonTest::testFdmHestonBarrierVsBlackScholes(), FdHestonTest::testFdmHestonBlackScholes(), FdHestonTest::testFdmHestonConvergence(), FdHestonTest::testFdmHestonEuropeanWithDividends(), FdmLinearOpTest::testFdmHestonExpress(), HybridHestonHullWhiteProcessTest::testFdmHestonHullWhiteEngine(), FdHestonTest::testFdmHestonIkonenToivanen(), AmericanOptionTest::testFdValues(), HestonModelTest::testFdVanillaVsCached(), QuantoOptionTest::testForwardGreeks(), anonymous_namespace{forwardoption.cpp}::testForwardGreeks(), QuantoOptionTest::testForwardPerformanceValues(), QuantoOptionTest::testForwardValues(), DigitalOptionTest::testGapEuropeanValues(), VPPTest::testGemanRoncoroniProcess(), MargrabeOptionTest::testGreeks(), JumpDiffusionTest::testGreeks(), QuantoOptionTest::testGreeks(), EuropeanOptionTest::testGreeks(), EuropeanOptionTest::testGreekValues(), BarrierOptionTest::testHaugValues(), HybridHestonHullWhiteProcessTest::testHestonHullWhiteCalibration(), CreditDefaultSwapTest::testImpliedHazardRate(), EuropeanOptionTest::testImpliedVol(), CapFloorTest::testImpliedVolatility(), EuropeanOptionTest::testImpliedVolContainment(), SwapTest::testInArrears(), LiborMarketModelProcessTest::testInitialisation(), VarianceOptionTest::testIntegralHeston(), AmericanOptionTest::testJuValues(), HestonModelTest::testKahlJaeckelCase(), SpreadOptionTest::testKirkEngine(), VPPTest::testKlugeExtOUSpreadOption(), AsianOptionTest::testLevyEngine(), BarrierOptionTest::testLocalVolAndHestonComparison(), EuropeanOptionTest::testLocalVolatility(), DigitalOptionTest::testMCCashAtHit(), AsianOptionTest::testMCDiscreteArithmeticAveragePrice(), AsianOptionTest::testMCDiscreteArithmeticAverageStrike(), AsianOptionTest::testMCDiscreteGeometricAveragePrice(), CliquetOptionTest::testMcPerformance(), VarianceSwapTest::testMCVarianceSwap(), HestonModelTest::testMcVsCached(), JumpDiffusionTest::testMerton76(), PathGeneratorTest::testMultiPathGenerator(), HestonModelTest::testMultipleStrikesEngine(), BasketOptionTest::testOddSamples(), BasketOptionTest::testOneDAmericanValues(), anonymous_namespace{cliquetoption.cpp}::testOptionGreeks(), AsianOptionTest::testPastFixings(), PathGeneratorTest::testPathGenerator(), ForwardOptionTest::testPerformanceValues(), BarrierOptionTest::testPerturbative(), EuropeanOptionTest::testPriceCurve(), TermStructureTest::testReferenceChange(), VarianceSwapTest::testReplicatingVarianceSwap(), VPPTest::testSimpleExtOUStorageEngine(), BasketOptionTest::testTavellaValues(), BondTest::testTheoretical(), CliquetOptionTest::testValues(), ForwardOptionTest::testValues(), EuropeanOptionTest::testValues(), QuantoOptionTest::testValues(), VarianceGammaTest::testVarianceGamma(), VPPTest::testVPPPricing(), HybridHestonHullWhiteProcessTest::testZeroBondPricing(), and BondTest::testZspread().
{
        return boost::shared_ptr<YieldTermStructure>(
                          new FlatForward(today, Handle<Quote>(forward), dc));
    }
boost::shared_ptr< YieldTermStructure > QuantLib::flatRate (const Date & today, Rate forward, const DayCounter & dc)
Definition at line 66 of file utilities.cpp.
References flatRate().
{
        return flatRate(
               today, boost::shared_ptr<Quote>(new SimpleQuote(forward)), dc);
    }
boost::shared_ptr< YieldTermStructure > QuantLib::flatRate (const boost::shared_ptr< Quote > & forward, const DayCounter & dc)
Definition at line 72 of file utilities.cpp.
{
        return boost::shared_ptr<YieldTermStructure>(
              new FlatForward(0, NullCalendar(), Handle<Quote>(forward), dc));
    }
boost::shared_ptr< YieldTermStructure > QuantLib::flatRate (Rate forward, const DayCounter & dc)
Definition at line 79 of file utilities.cpp.
References flatRate().
{
        return flatRate(boost::shared_ptr<Quote>(new SimpleQuote(forward)),
                        dc);
    }
boost::shared_ptr< BlackVolTermStructure > QuantLib::flatVol (const Date & today, const boost::shared_ptr< Quote > & vol, const DayCounter & dc)
Definition at line 86 of file utilities.cpp.
Referenced by QuantLib::BinomialConvertibleEngine< T >::calculate(), QuantLib::BinomialVanillaEngine< T >::calculate(), anonymous_namespace{convertiblebonds.cpp}::CommonVars::CommonVars(), anonymous_namespace{rangeaccrual.cpp}::CommonVars::CommonVars(), anonymous_namespace{rangeaccrual.cpp}::CommonVars::createSmileSections(), anonymous_namespace{rangeaccrual.cpp}::CommonVars::createVolatilityStructures(), flatVol(), anonymous_namespace{optionletstripper.cpp}::CommonVars::setFlatTermVolCurve(), anonymous_namespace{optionletstripper.cpp}::CommonVars::setFlatTermVolSurface(), MargrabeOptionTest::testAmericanExchangeTwoAssets(), BatesModelTest::testAnalyticAndMcVsJumpDiffusion(), LookbackOptionTest::testAnalyticContinuousFixedLookback(), LookbackOptionTest::testAnalyticContinuousFloatingLookback(), AsianOptionTest::testAnalyticContinuousGeometricAveragePrice(), AsianOptionTest::testAnalyticContinuousGeometricAveragePriceGreeks(), AsianOptionTest::testAnalyticDiscreteGeometricAveragePrice(), AsianOptionTest::testAnalyticDiscreteGeometricAveragePriceGreeks(), AsianOptionTest::testAnalyticDiscreteGeometricAverageStrike(), ChooserOptionTest::testAnalyticSimpleChooserEngine(), WriterExtensibleOptionTest::testAnalyticWriterExtensibleOptionEngine(), DigitalOptionTest::testAssetAtExpiryOrNothingAmericanValues(), DigitalOptionTest::testAssetAtHitOrNothingAmericanValues(), DigitalCouponTest::testAssetOrNothing(), DigitalOptionTest::testAssetOrNothingEuropeanValues(), BarrierOptionTest::testBabsiriValues(), AmericanOptionTest::testBaroneAdesiWhaleyValues(), BasketOptionTest::testBarraquandThreeValues(), QuantoOptionTest::testBarrierValues(), BarrierOptionTest::testBeagleholeValues(), AmericanOptionTest::testBjerksundStenslandValues(), HybridHestonHullWhiteProcessTest::testBsmHullWhiteEngine(), HybridHestonHullWhiteProcessTest::testBsmHullWhitePricing(), OperatorTest::testBSMOperatorConsistency(), HimalayaOptionTest::testCached(), PagodaOptionTest::testCached(), EverestOptionTest::testCached(), DigitalOptionTest::testCashAtExpiryOrNothingAmericanValues(), DigitalOptionTest::testCashAtHitOrNothingAmericanGreeks(), DigitalOptionTest::testCashAtHitOrNothingAmericanValues(), DigitalCouponTest::testCashOrNothing(), DigitalOptionTest::testCashOrNothingEuropeanValues(), HybridHestonHullWhiteProcessTest::testCompareBsmHWandHestonHW(), FdmLinearOpTest::testCrankNicolsonWithDamping(), BatesModelTest::testDAXCalibration(), HybridHestonHullWhiteProcessTest::testDiscretizationError(), anonymous_namespace{extendedtrees.cpp}::testEngineConsistency(), anonymous_namespace{europeanoption.cpp}::testEngineConsistency(), MargrabeOptionTest::testEuroExchangeTwoAssets(), DividendOptionTest::testEuropeanEndLimit(), DividendOptionTest::testEuropeanGreeks(), DividendOptionTest::testEuropeanKnownValue(), DividendOptionTest::testEuropeanStartLimit(), DividendOptionTest::testEuropeanValues(), BasketOptionTest::testEuroTwoValues(), SwingOptionTest::testFdBSSwingOption(), anonymous_namespace{dividendoption.cpp}::testFdDegenerate(), DividendOptionTest::testFdEuropeanValues(), anonymous_namespace{americanoption.cpp}::testFdGreeks(), anonymous_namespace{dividendoption.cpp}::testFdGreeks(), FdHestonTest::testFdmHestonBarrierVsBlackScholes(), FdHestonTest::testFdmHestonBlackScholes(), HybridHestonHullWhiteProcessTest::testFdmHestonHullWhiteEngine(), AmericanOptionTest::testFdValues(), HestonModelTest::testFdVanillaVsCached(), OptionletStripperTest::testFlatTermVolatilityStripping2(), QuantoOptionTest::testForwardGreeks(), anonymous_namespace{forwardoption.cpp}::testForwardGreeks(), QuantoOptionTest::testForwardPerformanceValues(), QuantoOptionTest::testForwardValues(), DigitalOptionTest::testGapEuropeanValues(), MargrabeOptionTest::testGreeks(), JumpDiffusionTest::testGreeks(), EuropeanOptionTest::testGreeks(), QuantoOptionTest::testGreeks(), EuropeanOptionTest::testGreekValues(), BarrierOptionTest::testHaugValues(), HybridHestonHullWhiteProcessTest::testHestonHullWhiteCalibration(), EuropeanOptionTest::testImpliedVol(), EuropeanOptionTest::testImpliedVolContainment(), AmericanOptionTest::testJuValues(), SpreadOptionTest::testKirkEngine(), AsianOptionTest::testLevyEngine(), DigitalOptionTest::testMCCashAtHit(), AsianOptionTest::testMCDiscreteArithmeticAveragePrice(), AsianOptionTest::testMCDiscreteArithmeticAverageStrike(), AsianOptionTest::testMCDiscreteGeometricAveragePrice(), CliquetOptionTest::testMcPerformance(), HybridHestonHullWhiteProcessTest::testMcVanillaPricing(), JumpDiffusionTest::testMerton76(), PathGeneratorTest::testMultiPathGenerator(), BasketOptionTest::testOddSamples(), BasketOptionTest::testOneDAmericanValues(), anonymous_namespace{cliquetoption.cpp}::testOptionGreeks(), AsianOptionTest::testPastFixings(), PathGeneratorTest::testPathGenerator(), ForwardOptionTest::testPerformanceValues(), EuropeanOptionTest::testPriceCurve(), BasketOptionTest::testTavellaValues(), OptionletStripperTest::testTermVolatilityStripping2(), ForwardOptionTest::testValues(), CliquetOptionTest::testValues(), EuropeanOptionTest::testValues(), and QuantoOptionTest::testValues().
{
        return boost::shared_ptr<BlackVolTermStructure>(new
            BlackConstantVol(today, NullCalendar(), Handle<Quote>(vol), dc));
    }
boost::shared_ptr< BlackVolTermStructure > QuantLib::flatVol (const Date & today, Volatility vol, const DayCounter & dc)
Definition at line 94 of file utilities.cpp.
References flatVol().
{
        return flatVol(today,
                       boost::shared_ptr<Quote>(new SimpleQuote(vol)),
                       dc);
    }
boost::shared_ptr< BlackVolTermStructure > QuantLib::flatVol (const boost::shared_ptr< Quote > & vol, const DayCounter & dc)
Definition at line 102 of file utilities.cpp.
{
        return boost::shared_ptr<BlackVolTermStructure>(new
            BlackConstantVol(0, NullCalendar(), Handle<Quote>(vol), dc));
    }
boost::shared_ptr< BlackVolTermStructure > QuantLib::flatVol (Volatility vol, const DayCounter & dc)
Definition at line 109 of file utilities.cpp.
References flatVol().
{
        return flatVol(boost::shared_ptr<Quote>(new SimpleQuote(vol)), dc);
    }
Real QuantLib::flatVolCovariance (Time t1, Time t2, Time T, Time S, Volatility v1, Volatility v2)
Definition at line 31 of file flatvol.cpp.
References QL_REQUIRE.
Referenced by QuantLib::FlatVol::FlatVol().
{
        QL_REQUIRE(t1<=t2,
                   "integrations bounds (" << t1 <<
                   "," << t2 << ") are in reverse order");
        Time cutOff = std::min(S,T);
        if (t1>=cutOff) {
            return 0.0;
        } else {
            cutOff = std::min(t2, cutOff);
            return (cutOff - t1)*v1*v2;
        }
    }
template<typename InterestRateIndexType , typename FloatingCouponType , typename DigitalCouponType > Leg QuantLib::FloatingDigitalLeg (const Schedule & schedule, const std::vector< Real > & nominals, const boost::shared_ptr< InterestRateIndexType > & index, const DayCounter & paymentDayCounter, BusinessDayConvention paymentAdj, const std::vector< Natural > & fixingDays, const std::vector< Real > & gearings, const std::vector< Spread > & spreads, bool isInArrears, const std::vector< Rate > & callStrikes, Position::Type callPosition, bool isCallATMIncluded, const std::vector< Rate > & callDigitalPayoffs, const std::vector< Rate > & putStrikes, Position::Type putPosition, bool isPutATMIncluded, const std::vector< Rate > & putDigitalPayoffs, const boost::shared_ptr< DigitalReplication > & replication)
Definition at line 159 of file cashflowvectors.hpp.
References QuantLib::Calendar::adjust(), QuantLib::Schedule::businessDayConvention(), QuantLib::Schedule::calendar(), anonymous_namespace{marketmodel.cpp}::calendar, QuantLib::Schedule::date(), QuantLib::detail::get(), QuantLib::Schedule::isRegular(), QL_REQUIRE, QuantLib::Schedule::size(), and QuantLib::Schedule::tenor().
    {
        Size n = schedule.size()-1;
        QL_REQUIRE(!nominals.empty(), "no notional given");
        QL_REQUIRE(nominals.size() <= n,
                   "too many nominals (" << nominals.size() <<
                   "), only " << n << " required");
        QL_REQUIRE(gearings.size()<=n,
                   "too many gearings (" << gearings.size() <<
                   "), only " << n << " required");
        QL_REQUIRE(spreads.size()<=n,
                   "too many spreads (" << spreads.size() <<
                   "), only " << n << " required");
        QL_REQUIRE(callStrikes.size()<=n,
                   "too many call rates (" << callStrikes.size() <<
                   "), only " << n << " required");
        QL_REQUIRE(putStrikes.size()<=n,
                   "too many put rates (" << putStrikes.size() <<
                   "), only " << n << " required");
        Leg leg; leg.reserve(n);
        // the following is not always correct
        Calendar calendar = schedule.calendar();
        Date refStart, start, refEnd, end;
        Date paymentDate;
        for (Size i=0; i<n; ++i) {
            refStart = start = schedule.date(i);
            refEnd   =   end = schedule.date(i+1);
            paymentDate = calendar.adjust(end, paymentAdj);
            if (i==0   && !schedule.isRegular(i+1)) {
                BusinessDayConvention bdc = schedule.businessDayConvention();
                refStart = calendar.adjust(end - schedule.tenor(), bdc);
            }
            if (i==n-1 && !schedule.isRegular(i+1)) {
                BusinessDayConvention bdc = schedule.businessDayConvention();
                refEnd = calendar.adjust(start + schedule.tenor(), bdc);
            }
            if (detail::get(gearings, i, 1.0) == 0.0) { // fixed coupon
                leg.push_back(boost::shared_ptr<CashFlow>(new
                    FixedRateCoupon(paymentDate,
                                    detail::get(nominals, i, 1.0),
                                    detail::get(spreads, i, 1.0),
                                    paymentDayCounter,
                                    start, end, refStart, refEnd)));
            } else { // floating digital coupon
                boost::shared_ptr<FloatingCouponType> underlying(new
                    FloatingCouponType(paymentDate,
                                       detail::get(nominals, i, 1.0),
                                       start, end,
                                       detail::get(fixingDays, i, index->fixingDays()),
                                       index,
                                       detail::get(gearings, i, 1.0),
                                       detail::get(spreads, i, 0.0),
                                       refStart, refEnd,
                                       paymentDayCounter, isInArrears));
                leg.push_back(boost::shared_ptr<CashFlow>(new
                    DigitalCouponType(
                             underlying,
                             detail::get(callStrikes, i, Null<Real>()),
                             callPosition,
                             isCallATMIncluded,
                             detail::get(callDigitalPayoffs, i, Null<Real>()),
                             detail::get(putStrikes, i, Null<Real>()),
                             putPosition,
                             isPutATMIncluded,
                             detail::get(putDigitalPayoffs, i, Null<Real>()),
                             replication)));
            }
        }
        return leg;
    }
template<typename InterestRateIndexType , typename FloatingCouponType , typename CappedFlooredCouponType > Leg QuantLib::FloatingLeg (const Schedule & schedule, const std::vector< Real > & nominals, const boost::shared_ptr< InterestRateIndexType > & index, const DayCounter & paymentDayCounter, BusinessDayConvention paymentAdj, const std::vector< Natural > & fixingDays, const std::vector< Real > & gearings, const std::vector< Spread > & spreads, const std::vector< Rate > & caps, const std::vector< Rate > & floors, bool isInArrears, bool isZero)
Definition at line 59 of file cashflowvectors.hpp.
References QuantLib::Calendar::adjust(), QuantLib::Schedule::businessDayConvention(), QuantLib::Schedule::calendar(), anonymous_namespace{marketmodel.cpp}::calendar, QuantLib::Schedule::date(), QuantLib::detail::effectiveFixedRate(), QuantLib::detail::get(), QuantLib::Schedule::isRegular(), QuantLib::detail::noOption(), QL_REQUIRE, QuantLib::Schedule::size(), and QuantLib::Schedule::tenor().
{
        Size n = schedule.size()-1;
        QL_REQUIRE(!nominals.empty(), "no notional given");
        QL_REQUIRE(nominals.size() <= n,
                   "too many nominals (" << nominals.size() <<
                   "), only " << n << " required");
        QL_REQUIRE(gearings.size()<=n,
                   "too many gearings (" << gearings.size() <<
                   "), only " << n << " required");
        QL_REQUIRE(spreads.size()<=n,
                   "too many spreads (" << spreads.size() <<
                   "), only " << n << " required");
        QL_REQUIRE(caps.size()<=n,
                   "too many caps (" << caps.size() <<
                   "), only " << n << " required");
        QL_REQUIRE(floors.size()<=n,
                   "too many floors (" << floors.size() <<
                   "), only " << n << " required");
        QL_REQUIRE(!isZero || !isInArrears,
                   "in-arrears and zero features are not compatible");
        Leg leg; leg.reserve(n);
        // the following is not always correct
        Calendar calendar = schedule.calendar();
        Date refStart, start, refEnd, end;
        Date lastPaymentDate = calendar.adjust(schedule.date(n), paymentAdj);
        for (Size i=0; i<n; ++i) {
            refStart = start = schedule.date(i);
            refEnd   =   end = schedule.date(i+1);
            Date paymentDate =
                isZero ? lastPaymentDate : calendar.adjust(end, paymentAdj);
            if (i==0   && !schedule.isRegular(i+1)) {
                BusinessDayConvention bdc = schedule.businessDayConvention();
                refStart = calendar.adjust(end - schedule.tenor(), bdc);
            }
            if (i==n-1 && !schedule.isRegular(i+1)) {
                BusinessDayConvention bdc = schedule.businessDayConvention();
                refEnd = calendar.adjust(start + schedule.tenor(), bdc);
            }
            if (detail::get(gearings, i, 1.0) == 0.0) { // fixed coupon
                leg.push_back(boost::shared_ptr<CashFlow>(new
                    FixedRateCoupon(paymentDate,
                                    detail::get(nominals, i, 1.0),
                                    detail::effectiveFixedRate(spreads,caps,
                                                               floors,i),
                                    paymentDayCounter,
                                    start, end, refStart, refEnd)));
            } else { // floating coupon
                if (detail::noOption(caps, floors, i))
                    leg.push_back(boost::shared_ptr<CashFlow>(new
                        FloatingCouponType(
                            paymentDate,
                            detail::get(nominals, i, 1.0),
                            start, end,
                            detail::get(fixingDays, i, index->fixingDays()),
                            index,
                            detail::get(gearings, i, 1.0),
                            detail::get(spreads, i, 0.0),
                            refStart, refEnd,
                            paymentDayCounter, isInArrears)));
                else {
                    leg.push_back(boost::shared_ptr<CashFlow>(new
                        CappedFlooredCouponType(
                               paymentDate,
                               detail::get(nominals, i, 1.0),
                               start, end,
                               detail::get(fixingDays, i, index->fixingDays()),
                               index,
                               detail::get(gearings, i, 1.0),
                               detail::get(spreads, i, 0.0),
                               detail::get(caps,   i, Null<Rate>()),
                               detail::get(floors, i, Null<Rate>()),
                               refStart, refEnd,
                               paymentDayCounter,
                               isInArrears)));
                }
            }
        }
        return leg;
    }
void QuantLib::forwardsFromDiscountRatios (const Size firstValidIndex, const std::vector< DiscountFactor > & ds, const std::vector< Time > & taus, std::vector< Rate > & fwds)
Definition at line 45 of file curvestate.cpp.
References QL_REQUIRE.
Referenced by QuantLib::CMSwapCurveState::forwardRate(), QuantLib::CoterminalSwapCurveState::forwardRate(), QuantLib::CMSwapCurveState::forwardRates(), and QuantLib::CoterminalSwapCurveState::forwardRates().
{
        QL_REQUIRE(taus.size()==fwds.size(),
                   "taus.size()!=fwds.size()");
        QL_REQUIRE(ds.size()==fwds.size()+1,
                   "ds.size()!=fwds.size()+1");
        for (Size i=firstValidIndex; i<fwds.size(); ++i)
            fwds[i] = (ds[i]-ds[i+1])/(ds[i+1]*taus[i]);
    }
Real QuantLib::genericEarlyExerciseOptimization (std::vector< std::vector< NodeData > > & simulationData, const ParametricExercise & exercise, std::vector< std::vector< Real > > & parameters, const EndCriteria & endCriteria, OptimizationMethod & method)
returns the biased estimate obtained while optimizing
Definition at line 81 of file parametricexercise.cpp.
References QuantLib::Array::begin(), anonymous_namespace{marketmodel.cpp}::c, QuantLib::Problem::currentValue(), QuantLib::Array::end(), QuantLib::ParametricExercise::exercise(), anonymous_namespace{interpolations.cpp}::f(), QuantLib::ParametricExercise::guess(), QuantLib::OptimizationMethod::minimize(), and QuantLib::ParametricExercise::numberOfParameters().
Referenced by MarketModelTest::testCallableSwapAnderson().
{
        Size steps = simulationData.size();
        parameters.resize(steps-1);
        for (Size i=steps-1; i!=0; --i) {
            const std::vector<NodeData>& exerciseData = simulationData[i];
            parameters[i-1].resize(exercise.numberOfParameters()[i-1]);
            // optimize
            ValueEstimate f(exerciseData, exercise, i-1);
            Array guess(parameters[i-1].size());
            exercise.guess(i-1, parameters[i-1]);
            std::copy(parameters[i-1].begin(), parameters[i-1].end(),
                      guess.begin());
            NoConstraint c;
            Problem p(f, c, guess);
            method.minimize(p, endCriteria);
            Array result = p.currentValue();
            std::copy(result.begin(), result.end(),
                      parameters[i-1].begin());
            std::vector<NodeData>& previousData = simulationData[i-1];
            for (Size j=0; j<previousData.size(); ++j) {
                if (exerciseData[j].isValid) {
                    if (exercise.exercise(i-1,
                                          parameters[i-1],
                                          exerciseData[j].values))
                        previousData[j].cumulatedCashFlows +=
                            exerciseData[j].exerciseValue;
                    else
                        previousData[j].cumulatedCashFlows +=
                            exerciseData[j].cumulatedCashFlows;
                }
            }
        }
        Real sum = 0.0;
        const std::vector<NodeData>& initialData = simulationData.front();
        for (Size i=0; i<initialData.size(); ++i)
            sum += initialData[i].cumulatedCashFlows;
        return sum/initialData.size();
    }
Real QuantLib::genericLongstaffSchwartzRegression (std::vector< std::vector< NodeData > > & simulationData, std::vector< std::vector< Real > > & basisCoefficients)
returns the biased estimate obtained while regressing
Definition at line 26 of file genericlsregression.cpp.
References QuantLib::GenericSequenceStatistics< StatisticsType >::add(), QuantLib::Array::begin(), QuantLib::GenericSequenceStatistics< StatisticsType >::covariance(), QuantLib::Array::end(), QuantLib::dsd::inner_product(), QuantLib::GenericSequenceStatistics< StatisticsType >::mean(), anonymous_namespace{matrices.cpp}::N, and QuantLib::SVD::solveFor().
Referenced by MarketModelTest::testCallableSwapLS().
{
        Size steps = simulationData.size();
        basisCoefficients.resize(steps-1);
        for (Size i=steps-1; i!=0; --i) {
            std::vector<NodeData>& exerciseData = simulationData[i];
            // 1) find the covariance matrix of basis function values and
            //    deflated cash-flows
            Size N = exerciseData.front().values.size();
            std::vector<Real> temp(N+1);
            SequenceStatistics stats(N+1);
            Size j;
            for (j=0; j<exerciseData.size(); ++j) {
                if (exerciseData[j].isValid) {
                    std::copy(exerciseData[j].values.begin(),
                              exerciseData[j].values.end(),
                              temp.begin());
                    temp.back() = exerciseData[j].cumulatedCashFlows
                                - exerciseData[j].controlValue;
                    stats.add(temp);
                }
            }
            std::vector<Real> means = stats.mean();
            Matrix covariance = stats.covariance();
            Matrix C(N,N);
            Array target(N);
            for (Size k=0; k<N; ++k) {
                target[k] = covariance[k][N] + means[k]*means[N];
                for (Size l=0; l<=k; ++l)
                    C[k][l] = C[l][k] = covariance[k][l] + means[k]*means[l];
            }
            // 2) solve for least squares regression
            Array alphas = SVD(C).solveFor(target);
            basisCoefficients[i-1].resize(N);
            std::copy(alphas.begin(), alphas.end(),
                      basisCoefficients[i-1].begin());
            // 3) use exercise strategy to divide paths into exercise and
            //    non-exercise domains
            for (j=0; j<exerciseData.size(); ++j) {
                if (exerciseData[j].isValid) {
                    Real exerciseValue = exerciseData[j].exerciseValue;
                    Real continuationValue =
                        exerciseData[j].cumulatedCashFlows;
                    Real estimatedContinuationValue =
                        std::inner_product(
                                 exerciseData[j].values.begin(),
                                 exerciseData[j].values.end(),
                                 alphas.begin(),
                                 exerciseData[j].controlValue);
                    // for exercise paths, add deflated rebate to
                    // deflated cash-flows at previous time frame;
                    // for non-exercise paths, add deflated cash-flows to
                    // deflated cash-flows at previous time frame
                    Real value = estimatedContinuationValue <= exerciseValue ?
                                 exerciseValue :
                                 continuationValue;
                    simulationData[i-1][j].cumulatedCashFlows += value;
                }
            }
        }
        // the value of the product can now be estimated by averaging
        // over all paths
        Statistics estimate;
        std::vector<NodeData>& estimatedData = simulationData[0];
        for (Size j=0; j<estimatedData.size(); ++j)
            estimate.add(estimatedData[j].cumulatedCashFlows);
        return estimate.mean();
    }
template<class DataIterator > Disposable<Matrix> QuantLib::getCovariance (DataIterator stdDevBegin, DataIterator stdDevEnd, const Matrix & corr, Real tolerance = 1.0e-12)
Calculation of covariance from correlation and standard deviations.
Combines the correlation matrix and the vector of standard deviations to return the covariance matrix.
Note that only the symmetric part of the correlation matrix is used. Also it is assumed that the diagonal member of the correlation matrix equals one.
Precondition:
The correlation matrix must be symmetric with the diagonal members equal to one.
Test:
tested on know values and cross checked with CovarianceDecomposition
Definition at line 49 of file getcovariance.hpp.
References QuantLib::Matrix::columns(), QuantLib::io::ordinal(), QL_REQUIRE, QuantLib::Matrix::rows(), and anonymous_namespace{gaussianquadratures.cpp}::tolerance.
Referenced by CovarianceTest::testCovariance().
{
        Size size = std::distance(stdDevBegin, stdDevEnd);
        QL_REQUIRE(corr.rows() == size,
                   "dimension mismatch between volatilities (" << size <<
                   ") and correlation rows (" << corr.rows() << ")");
        QL_REQUIRE(corr.columns() == size,
                   "correlation matrix is not square: " << size <<
                   " rows and " << corr.columns() << " columns");
        Matrix covariance(size,size);
        Size i, j;
        DataIterator iIt, jIt;
        for (i=0, iIt=stdDevBegin; i<size; ++i, ++iIt){
            for (j=0, jIt=stdDevBegin; j<i; ++j, ++jIt){
                QL_REQUIRE(std::fabs(corr[i][j]-corr[j][i]) <= tolerance,
                           "correlation matrix not symmetric:"
                           << "\nc[" << i << "," << j << "] = " << corr[i][j]
                           << "\nc[" << j << "," << i << "] = " << corr[j][i]);
                covariance[i][i] = (*iIt) * (*iIt);
                covariance[i][j] = (*iIt) * (*jIt) *
                    0.5 * (corr[i][j] + corr[j][i]);
                covariance[j][i] = covariance[i][j];
            }
            QL_REQUIRE(std::fabs(corr[i][i]-1.0) <= tolerance,
                       "invalid correlation matrix, "
                       << "diagonal element of the " << io::ordinal(i+1)
                       << " row is " << corr[i][i] << " instead of 1.0");
            covariance[i][i] = (*iIt) * (*iIt);
        }
        return covariance;
    }
template<class Traits , class Interpolator > void QuantLib::historicalForwardRatesAnalysis (SequenceStatistics & statistics, std::vector< Date > & skippedDates, std::vector< std::string > & skippedDatesErrorMessage, std::vector< Date > & failedDates, std::vector< std::string > & failedDatesErrorMessage, std::vector< Period > & fixingPeriods, const Date & startDate, const Date & endDate, const Period & step, const boost::shared_ptr< InterestRateIndex > & fwdIndex, const Period & initialGap, const Period & horizon, const std::vector< boost::shared_ptr< IborIndex > > & iborIndexes, const std::vector< boost::shared_ptr< SwapIndex > > & swapIndexes, const DayCounter & yieldCurveDayCounter, Real yieldCurveAccuracy = 1.0e-12, const Interpolator & i = Interpolator())
Definition at line 43 of file historicalforwardratesanalysis.hpp.
References QuantLib::GenericSequenceStatistics< StatisticsType >::add(), QuantLib::Calendar::advance(), anonymous_namespace{marketmodel.cpp}::d, Days, anonymous_namespace{marketmodel.cpp}::endDate, QuantLib::Settings::enforcesTodaysHistoricFixings(), QuantLib::Settings::evaluationDate(), Following, QuantLib::Singleton< Settings >::instance(), QuantLib::GenericSequenceStatistics< StatisticsType >::reset(), Simple, and swap().
Referenced by QuantLib::HistoricalForwardRatesAnalysisImpl< Traits, Interpolator >::HistoricalForwardRatesAnalysisImpl().
{
        statistics.reset();
        skippedDates.clear();
        skippedDatesErrorMessage.clear();
        failedDates.clear();
        failedDatesErrorMessage.clear();
        fixingPeriods.clear();
        SavedSettings backup;
        Settings::instance().enforcesTodaysHistoricFixings() = true;
        std::vector<boost::shared_ptr<RateHelper> > rateHelpers;
        // Create DepositRateHelper
        std::vector<boost::shared_ptr<SimpleQuote> > iborQuotes;
        std::vector<boost::shared_ptr<IborIndex> >::const_iterator ibor;
        for (ibor=iborIndexes.begin(); ibor!=iborIndexes.end(); ++ibor) {
            boost::shared_ptr<SimpleQuote> quote(new SimpleQuote);
            iborQuotes.push_back(quote);
            Handle<Quote> quoteHandle(quote);
            rateHelpers.push_back(boost::shared_ptr<RateHelper> (new
                DepositRateHelper(quoteHandle,
                                  (*ibor)->tenor(),
                                  (*ibor)->fixingDays(),
                                  (*ibor)->fixingCalendar(),
                                  (*ibor)->businessDayConvention(),
                                  (*ibor)->endOfMonth(),
                                  (*ibor)->dayCounter())));
        }
        // Create SwapRateHelper
        std::vector<boost::shared_ptr<SimpleQuote> > swapQuotes;
        std::vector<boost::shared_ptr<SwapIndex> >::const_iterator swap;
        for (swap=swapIndexes.begin(); swap!=swapIndexes.end(); ++swap) {
            boost::shared_ptr<SimpleQuote> quote(new SimpleQuote);
            swapQuotes.push_back(quote);
            Handle<Quote> quoteHandle(quote);
            rateHelpers.push_back(boost::shared_ptr<RateHelper> (new
                SwapRateHelper(quoteHandle,
                               (*swap)->tenor(),
                               (*swap)->fixingCalendar(),
                               (*swap)->fixedLegTenor().frequency(),
                               (*swap)->fixedLegConvention(),
                               (*swap)->dayCounter(),
                               (*swap)->iborIndex())));
        }
        // Set up the forward rates time grid
        Period indexTenor = fwdIndex->tenor();
        Period fixingPeriod = initialGap;
        while (fixingPeriod<=horizon) {
            fixingPeriods.push_back(fixingPeriod);
            fixingPeriod += indexTenor;
        }
        Size nRates = fixingPeriods.size();
        statistics.reset(nRates);
        std::vector<Rate> fwdRates(nRates);
        std::vector<Rate> prevFwdRates(nRates);
        std::vector<Rate> fwdRatesDiff(nRates);
        DayCounter indexDayCounter = fwdIndex->dayCounter();
        Calendar cal = fwdIndex->fixingCalendar();
        // Bootstrap the yield curve at the currentDate
        Natural settlementDays = 0;
        PiecewiseYieldCurve<Traits, Interpolator> yc(settlementDays,
                                                     cal,
                                                     rateHelpers,
                                                     yieldCurveDayCounter,
                                                     std::vector<Handle<Quote> >(),
                                                     std::vector<Date>(),
                                                     yieldCurveAccuracy,
                                                     i);
        // start with a valid business date
        Date currentDate = cal.advance(startDate, 1*Days, Following);
        bool isFirst = true;
        // Loop over the historical dataset
        for (; currentDate<=endDate;
            currentDate = cal.advance(currentDate, step, Following)) {
            // move the evaluationDate to currentDate
            // and update ratehelpers dates...
            Settings::instance().evaluationDate() = currentDate;
            try {
                // update the quotes...
                for (Size i=0; i<iborIndexes.size(); ++i) {
                    Rate fixing = iborIndexes[i]->fixing(currentDate, false);
                    iborQuotes[i]->setValue(fixing);
                }
                for (Size i=0; i<swapIndexes.size(); ++i) {
                    Rate fixing = swapIndexes[i]->fixing(currentDate, false);
                    swapQuotes[i]->setValue(fixing);
                }
            } catch (std::exception& e) {
                skippedDates.push_back(currentDate);
                skippedDatesErrorMessage.push_back(e.what());
                continue;
            }
            try {
                for (Size i=0; i<nRates; ++i) {
                    // Time-to-go forwards
                    Date d = currentDate + fixingPeriods[i];
                    fwdRates[i] = yc.forwardRate(d,
                                                 indexTenor,
                                                 indexDayCounter,
                                                 Simple);
                }
            } catch (std::exception& e) {
                failedDates.push_back(currentDate);
                failedDatesErrorMessage.push_back(e.what());
                continue;
            }
            // From 2nd step onwards, calculate forward rate
            // relative differences
            if (!isFirst){
                for (Size i=0; i<nRates; ++i)
                    fwdRatesDiff[i] = fwdRates[i]/prevFwdRates[i] -1.0;
                // add observation
                statistics.add(fwdRatesDiff.begin(), fwdRatesDiff.end());
            }
            else
                isFirst = false;
            // Store last calculated forward rates
            std::swap(prevFwdRates, fwdRates);
        }
    }
void QuantLib::historicalRatesAnalysis (SequenceStatistics & statistics, std::vector< Date > & skippedDates, std::vector< std::string > & skippedDatesErrorMessage, const Date & startDate, const Date & endDate, const Period & step, const std::vector< boost::shared_ptr< InterestRateIndex > > & indexes)
Definition at line 26 of file historicalratesanalysis.cpp.
References QuantLib::GenericSequenceStatistics< StatisticsType >::add(), QuantLib::Calendar::advance(), Days, anonymous_namespace{marketmodel.cpp}::endDate, Following, QuantLib::GenericSequenceStatistics< StatisticsType >::reset(), and swap().
Referenced by QuantLib::HistoricalRatesAnalysis::HistoricalRatesAnalysis().
{
        skippedDates.clear();
        skippedDatesErrorMessage.clear();
        Size nRates = indexes.size();
        statistics.reset(nRates);
        std::vector<Rate> sample(nRates);
        std::vector<Rate> prevSample(nRates);
        std::vector<Rate> sampleDiff(nRates);
        Calendar cal = indexes[0]->fixingCalendar();
        // start with a valid business date
        Date currentDate = cal.advance(startDate, 1*Days, Following);
        bool isFirst = true;
        // Loop over the historical dataset
        for (; currentDate<=endDate;
            currentDate = cal.advance(currentDate, step, Following)) {
            try {
                for (Size i=0; i<nRates; ++i) {
                    Rate fixing = indexes[i]->fixing(currentDate, false);
                    sample[i] = fixing;
                }
            } catch (std::exception& e) {
                skippedDates.push_back(currentDate);
                skippedDatesErrorMessage.push_back(e.what());
                continue;
            }
            // From 2nd step onwards, calculate forward rate
            // relative differences
            if (!isFirst){
                for (Size i=0; i<nRates; ++i)
                    sampleDiff[i] = sample[i]/prevSample[i] -1.0;
                // add observation
                statistics.add(sampleDiff.begin(), sampleDiff.end());
            }
            else
                isFirst = false;
            // Store last calculated forward rates
            std::swap(prevSample, sample);
        }
    }
Real QuantLib::incompleteBetaFunction (Real a, Real b, Real x, Real accuracy = 1e-16, Integer maxIteration = 100)
Incomplete Beta function.
Incomplete Beta function
The implementation of the algorithm was inspired by "Numerical Recipes in C", 2nd edition, Press, Teukolsky, Vetterling, Flannery, chapter 6
Definition at line 67 of file beta.cpp.
References anonymous_namespace{marketmodel.cpp}::a, anonymous_namespace{marketmodel.cpp}::b, betaContinuedFraction(), and QL_REQUIRE.
Referenced by QuantLib::CumulativeStudentDistribution::operator()(), and QuantLib::CumulativeBinomialDistribution::operator()().
{
    QL_REQUIRE(a > 0.0, "a must be greater than zero");
    QL_REQUIRE(b > 0.0, "b must be greater than zero");
    if (x == 0.0)
        return 0.0;
    else if (x == 1.0)
        return 1.0;
    else
        QL_REQUIRE(x>0.0 && x<1.0, "x must be in [0,1]");
    Real result = std::exp(GammaFunction().logValue(a+b) -
        GammaFunction().logValue(a) - GammaFunction().logValue(b) +
        a*std::log(x) + b*std::log(1.0-x));
    if (x < (a+1.0)/(a+b+2.0))
        return result *
            betaContinuedFraction(a, b, x, accuracy, maxIteration)/a;
    else
        return 1.0 - result *
            betaContinuedFraction(b, a, 1.0-x, accuracy, maxIteration)/b;
    }
Real QuantLib::incompleteGammaFunction (Real a, Real x, Real accuracy = 1.0e-13, Integer maxIteration = 100)
Incomplete Gamma function.
Incomplete Gamma function
The implementation of the algorithm was inspired by "Numerical Recipes in C", 2nd edition, Press, Teukolsky, Vetterling, Flannery, chapter 6
Definition at line 32 of file incompletegamma.cpp.
References incompleteGammaFunctionContinuedFractionRepr(), incompleteGammaFunctionSeriesRepr(), and QL_REQUIRE.
Referenced by QuantLib::CumulativePoissonDistribution::operator()().
{
        QL_REQUIRE(a>0.0, "non-positive a is not allowed");
        QL_REQUIRE(x>=0.0, "negative x non allowed");
        if (x < (a+1.0)) {
            // Use the series representation
            return incompleteGammaFunctionSeriesRepr(a, x,
                accuracy, maxIteration);
        } else {
            // Use the continued fraction representation
            return 1.0-incompleteGammaFunctionContinuedFractionRepr(a, x,
                accuracy, maxIteration);
        }
    }
Real QuantLib::incompleteGammaFunctionContinuedFractionRepr (Real a, Real x, Real accuracy, Integer maxIteration)
Definition at line 72 of file incompletegamma.cpp.
References anonymous_namespace{marketmodel.cpp}::a, anonymous_namespace{marketmodel.cpp}::b, anonymous_namespace{marketmodel.cpp}::c, anonymous_namespace{marketmodel.cpp}::d, QuantLib::GammaFunction::logValue(), QL_EPSILON, and QL_FAIL.
Referenced by incompleteGammaFunction().
{
        Integer i;
        Real an, b, c, d, del, h;
        Real gln = GammaFunction().logValue(a);
        b=x+1.0-a;
        c=1.0/QL_EPSILON;
        d=1.0/b;
        h=d;
        for (i=1; i<=maxIteration; i++) {
            an = -i*(i-a);
            b += 2.0;
            d=an*d+b;
            if (std::fabs(d) < QL_EPSILON) d=QL_EPSILON;
            c=b+an/c;
            if (std::fabs(c) < QL_EPSILON) c=QL_EPSILON;
            d=1.0/d;
            del=d*c;
            h *= del;
            if (std::fabs(del-1.0) < accuracy) {
                return std::exp(-x+a*std::log(x)-gln)*h;
            }
        }
        QL_FAIL("accuracy not reached");
    }
Real QuantLib::incompleteGammaFunctionSeriesRepr (Real a, Real x, Real accuracy, Integer maxIteration)
Definition at line 52 of file incompletegamma.cpp.
References anonymous_namespace{marketmodel.cpp}::a, QuantLib::GammaFunction::logValue(), and QL_FAIL.
Referenced by incompleteGammaFunction().
{
        if (x==0.0) return 0.0;
        Real gln = GammaFunction().logValue(a);
        Real ap=a;
        Real del=1.0/a;
        Real sum=del;
        for (Integer n=1; n<=maxIteration; n++) {
            ++ap;
            del *= x/ap;
            sum += del;
            if (std::fabs(del) < std::fabs(sum)*accuracy) {
                return sum*std::exp(-x+a*std::log(x)-gln);
            }
        }
        QL_FAIL("accuracy not reached");
    }
std::pair< Date, Date > QuantLib::inflationPeriod (const Date & d, Frequency frequency)
utility function giving the inflation period for a given date
Definition at line 283 of file inflationtermstructure.cpp.
References Annual, December, anonymous_namespace{marketmodel.cpp}::endDate, QuantLib::Date::endOfMonth(), January, QuantLib::Date::month(), Monthly, QL_FAIL, Quarterly, Semiannual, anonymous_namespace{marketmodel.cpp}::startDate, and QuantLib::Date::year().
Referenced by QuantLib::InflationIndex::addFixing(), QuantLib::CPICashFlow::amount(), QuantLib::YoYOptionletVolatilitySurface::baseDate(), QuantLib::CPIVolatilitySurface::baseDate(), QuantLib::InterpolatingCPICapFloorEngine::calculate(), QuantLib::MultiplicativePriceSeasonality::correctYoYRate(), QuantLib::MultiplicativePriceSeasonality::correctZeroRate(), QuantLib::ZeroInflationIndex::fixing(), QuantLib::YoYInflationIndex::fixing(), QuantLib::ZeroInflationIndex::forecastFixing(), QuantLib::YoYInflationIndex::forecastFixing(), QuantLib::CPICoupon::indexFixing(), inflationYearFraction(), QuantLib::ZeroInflationTraits::initialDate(), QuantLib::YoYInflationTraits::initialDate(), QuantLib::InterpolatedYoYInflationCurve< Interpolator >::InterpolatedYoYInflationCurve(), QuantLib::InterpolatedZeroInflationCurve< Interpolator >::InterpolatedZeroInflationCurve(), QuantLib::MultiplicativePriceSeasonality::isConsistent(), QuantLib::InterpolatedZeroInflationCurve< Interpolator >::maxDate(), QuantLib::ZeroInflationIndex::needsForecast(), QuantLib::MultiplicativePriceSeasonality::seasonalityFactor(), InflationTest::testPeriod(), InflationTest::testYYIndex(), InflationTest::testZeroIndex(), InflationTest::testZeroTermStructure(), QuantLib::YoYOptionletVolatilitySurface::timeFromBase(), QuantLib::CPIVolatilitySurface::timeFromBase(), QuantLib::CPIVolatilitySurface::volatility(), QuantLib::YoYOptionletVolatilitySurface::volatility(), QuantLib::YearOnYearInflationSwapHelper::YearOnYearInflationSwapHelper(), QuantLib::YoYInflationTermStructure::yoyRate(), QuantLib::ZeroCouponInflationSwapHelper::ZeroCouponInflationSwapHelper(), and QuantLib::ZeroInflationTermStructure::zeroRate().
{
        Month month = d.month();
        Year year = d.year();
        Month startMonth, endMonth;
        switch (frequency) {
          case Annual:
            startMonth = January;
            endMonth = December;
            break;
          case Semiannual:
            startMonth = Month(6*((month-1)/6) + 1);
            endMonth = Month(startMonth + 5);
            break;
          case Quarterly:
            startMonth = Month(3*((month-1)/3) + 1);
            endMonth = Month(startMonth + 2);
            break;
          case Monthly:
            startMonth = endMonth = month;
            break;
          default:
            QL_FAIL("Frequency not handled: " << frequency);
            break;
        };
        Date startDate = Date(1, startMonth, year);
        Date endDate = Date::endOfMonth(Date(1, endMonth, year));
        return std::make_pair(startDate,endDate);
    }
Time QuantLib::inflationYearFraction (Frequency , bool indexIsInterpolated, const DayCounter & , const Date & , const Date &)
utility function giving the time between two dates depending on index frequency and interpolation, and a day counter
Definition at line 318 of file inflationtermstructure.cpp.
References inflationPeriod(), anonymous_namespace{quantlibbenchmark.cpp}::t, and QuantLib::DayCounter::yearFraction().
Referenced by QuantLib::ZeroCouponInflationSwap::fairRate(), and QuantLib::ZeroCouponInflationSwap::ZeroCouponInflationSwap().
{
        Time t=0;
        if (indexIsInterpolated) {
            // N.B. we do not use linear interpolation between flat
            // fixing forecasts for forecasts.  This avoids awkwardnesses
            // when bootstrapping the inflation curve.
            t = dayCounter.yearFraction(d1, d2);
        } else {
            // I.e. fixing is constant for the whole inflation period.
            // Use the value for half way along the period.
            // But the inflation time is the time between period starts
            std::pair<Date,Date> limD1 = inflationPeriod(d1, f);
            std::pair<Date,Date> limD2 = inflationPeriod(d2, f);
            t = dayCounter.yearFraction(limD1.first, limD2.first);
        }
        return t;
    }
Disposable<Matrix> QuantLib::inverse (const Matrix & m) [related]
Definition at line 42 of file matrix.cpp.
References anonymous_namespace{marketmodel.cpp}::a, QuantLib::Matrix::begin(), QuantLib::Matrix::columns(), QuantLib::Matrix::end(), QL_FAIL, QL_REQUIRE, and QuantLib::Matrix::rows().
Referenced by QuantLib::CTSMMCapletOriginalCalibration::calibrationFunction(), QuantLib::CTSMMCapletAlphaFormCalibration::capletAlphaFormCalibration(), QuantLib::CTSMMCapletMaxHomogeneityCalibration::capletMaxHomogeneityCalibration(), QuantLib::CotSwapToFwdAdapter::CotSwapToFwdAdapter(), QuantLib::GaussianLHPCDOEngine< CDOEngine >::expectedTrancheLoss(), QuantLib::SVD::solveFor(), MatricesTest::testInverse(), and QuantLib::detail::CubicInterpolationImpl< I1, I2 >::update().
{
        #if !defined(QL_NO_UBLAS_SUPPORT)
        QL_REQUIRE(m.rows() == m.columns(), "matrix is not square");
        boost::numeric::ublas::matrix<Real> a(m.rows(), m.columns());
        std::copy(m.begin(), m.end(), a.data().begin());
        boost::numeric::ublas::permutation_matrix<Size> pert(m.rows());
        // lu decomposition
        const Size singular = lu_factorize(a, pert);
        QL_REQUIRE(singular == 0, "singular matrix given");
        boost::numeric::ublas::matrix<Real>
            inverse = boost::numeric::ublas::identity_matrix<Real>(m.rows());
        // backsubstitution
        boost::numeric::ublas::lu_substitute(a, pert, inverse);
        Matrix retVal(m.rows(), m.columns());
        std::copy(inverse.data().begin(), inverse.data().end(),
                  retVal.begin());
        return retVal;
        #else
        QL_FAIL("this version of gcc does not support "
                "the Boost uBLAS library");
        #endif
    }
bool QuantLib::isInMoneyMarketMeasure (const EvolutionDescription & evolution, const std::vector< Size > & numeraires)
Definition at line 157 of file evolutiondescription.cpp.
References isInMoneyMarketPlusMeasure().
Referenced by anonymous_namespace{marketmodel_smm.cpp}::makeMeasure(), anonymous_namespace{marketmodel_cms.cpp}::makeMeasure(), anonymous_namespace{marketmodel_smmcapletcalibration.cpp}::makeMeasure(), anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::makeMeasure(), anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::makeMeasure(), and anonymous_namespace{marketmodel.cpp}::makeMeasure().
{
        return isInMoneyMarketPlusMeasure(evolution, numeraires, 0);
    }
bool QuantLib::isInMoneyMarketPlusMeasure (const EvolutionDescription & evolution, const std::vector< Size > & numeraires, Size offset)
Definition at line 138 of file evolutiondescription.cpp.
References QuantLib::EvolutionDescription::evolutionTimes(), QL_REQUIRE, QuantLib::EvolutionDescription::rateTimes(), and anonymous_namespace{marketmodel.cpp}::rateTimes.
Referenced by isInMoneyMarketMeasure(), anonymous_namespace{marketmodel_smm.cpp}::makeMeasure(), anonymous_namespace{marketmodel_cms.cpp}::makeMeasure(), anonymous_namespace{marketmodel_smmcapletcalibration.cpp}::makeMeasure(), anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::makeMeasure(), anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::makeMeasure(), and anonymous_namespace{marketmodel.cpp}::makeMeasure().
{
        bool res = true;
        const std::vector<Time>& rateTimes = evolution.rateTimes();
        Size maxNumeraire=rateTimes.size()-1;
        QL_REQUIRE(offset<=maxNumeraire,
                   "offset (" << offset <<
                   ") is greater than the max allowed value for numeraire ("
                   << maxNumeraire << ")");
        const std::vector<Time>& evolutionTimes = evolution.evolutionTimes();
        for (Size i=0, j=0; i<evolutionTimes.size(); ++i) {
            while (rateTimes[j] < evolutionTimes[i])
                j++;
            res = (numeraires[i] == std::min(j+offset, maxNumeraire)) && res;
        }
        return res;
    }
std::valarray< bool > QuantLib::isInSubset (const std::vector< Time > & set, const std::vector< Time > & subset)
Look for elements of a set in a subset. Returns a vector of booleans such that: element set[i] present/not present in subset.
Precondition:
both vectors must be strictly increasing.
Definition at line 59 of file utilities.cpp.
References QL_REQUIRE.
Referenced by collectNodeData(), QuantLib::LongstaffSchwartzExerciseStrategy::LongstaffSchwartzExerciseStrategy(), MarketModelTest::testCallableSwapAnderson(), MarketModelTest::testCallableSwapLS(), MarketModelTest::testCallableSwapNaif(), MarketModelTest::testIsInSubset(), and QuantLib::UpperBoundEngine::UpperBoundEngine().
{
        std::valarray<bool> result(false,set.size());
        Size dimsubSet = subset.size();
        if (dimsubSet==0)
            return result;
        Size dimSet = set.size();
        Time setElement, subsetElement;
        QL_REQUIRE(dimSet >= dimsubSet,
                   "set is required to be larger or equal than subset");
        for (Size i=0; i<dimSet; ++i) {  // loop in set
            Size j=0;
            setElement = set[i];
            for (;;) {              // loop in subset
                subsetElement = subset[j];
                result[i] = false;
                // if smaller no hope, leave false and go to next i
                if (setElement < subsetElement)
                    break;
                // if match, set result[i] to true and go to next i
                if (setElement == subsetElement) {
                    result[i] = true;
                    break;
                }
                // if larger, leave false if at the end or go to next j
                if (j == dimsubSet-1)
                    break;
                ++j;
            }
        }
        return result;
    }
bool QuantLib::isInTerminalMeasure (const EvolutionDescription & evolution, const std::vector< Size > & numeraires)
Definition at line 131 of file evolutiondescription.cpp.
References QuantLib::EvolutionDescription::rateTimes(), and anonymous_namespace{marketmodel.cpp}::rateTimes.
Referenced by QuantLib::LogNormalFwdRateiBalland::LogNormalFwdRateiBalland(), QuantLib::LogNormalFwdRateIpc::LogNormalFwdRateIpc(), anonymous_namespace{marketmodel_smm.cpp}::makeMeasure(), anonymous_namespace{marketmodel_cms.cpp}::makeMeasure(), anonymous_namespace{marketmodel_smmcapletcalibration.cpp}::makeMeasure(), anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::makeMeasure(), anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::makeMeasure(), anonymous_namespace{marketmodel.cpp}::makeMeasure(), MarketModelTest::testCallableSwapAnderson(), MarketModelTest::testCallableSwapLS(), MarketModelTest::testCallableSwapNaif(), testMultiProductComposite(), MarketModelCmsTest::testMultiStepCmSwapsAndSwaptions(), MarketModelSmmTest::testMultiStepCoterminalSwapsAndSwaptions(), MarketModelTest::testOneStepForwardsAndOptionlets(), and MarketModelTest::testOneStepNormalForwardsAndOptionlets().
{
        const std::vector<Time>& rateTimes = evolution.rateTimes();
        return *std::min_element(numeraires.begin(), numeraires.end()) ==
                                                          rateTimes.size()-1;
    }
Disposable< Matrix > QuantLib::lmmTriangularAnglesParametrization (const Array & angles, Size matrixSize, Size rank)
Definition at line 57 of file tapcorrelations.cpp.
References QuantLib::Matrix::rows().
Referenced by lmmTriangularAnglesParametrizationUnconstrained().
{
        Matrix m(matrixSize, matrixSize);
        for (Size i=0; i<m.rows(); ++i) {
            Real cosPhi, sinPhi;
            if (i>0) {
                cosPhi = std::cos(angles[i-1]);
                sinPhi = std::sin(angles[i-1]);
            } else {
                cosPhi = 1.0;
                sinPhi = 0.0;
            }
            for (Size j=0; j<i; ++j)
                m[i][j] = sinPhi * m[i-1][j];
            m[i][i] = cosPhi;
            for (Size j=i+1; j<m.rows(); ++j)
                m[i][j] = 0.0;
        }
        return m;
    }
Disposable< Matrix > QuantLib::lmmTriangularAnglesParametrizationUnconstrained (const Array & x, Size matrixSize, Size rank)
Definition at line 93 of file tapcorrelations.cpp.
References lmmTriangularAnglesParametrization(), M_PI, and QuantLib::Array::size().
{
        Array angles(x.size());
        //we convert the unconstrained parameters in angles
        for (Size i = 0; i < x.size(); ++i)
            angles[i] = M_PI*.5 - std::atan(x[i]);
        return lmmTriangularAnglesParametrization(angles, matrixSize, rank);
    }
const Disposable<Array> QuantLib::Log (const Array & v) [related]
Definition at line 611 of file array.hpp.
References QuantLib::Array::begin(), QuantLib::Array::end(), and QuantLib::Array::size().
{
        Array result(v.size());
        std::transform(v.begin(),v.end(),result.begin(),
                       std::ptr_fun<Real,Real>(std::log));
        return result;
    }
std::map< Seniority, Real > QuantLib::makeIsdaConvMap ()
Helper function for conventional recoveries. Returns the ISDA.
Definition at line 32 of file recoveryratequote.cpp.
References QuantLib::RecoveryRateQuote::IsdaConvRecoveries, and QuantLib::RecoveryRateQuote::makeIsdaMap().
Referenced by QuantLib::BankruptcyEvent::BankruptcyEvent().
{
        return RecoveryRateQuote::makeIsdaMap(
            RecoveryRateQuote::IsdaConvRecoveries);
    }
void QuantLib::mergeTimes (const std::vector< std::vector< Time > > & times, std::vector< Time > & mergedTimes, std::vector< std::valarray< bool > > & isPresent)
Definition at line 29 of file utilities.cpp.
Referenced by QuantLib::CallSpecifiedMultiProduct::CallSpecifiedMultiProduct(), QuantLib::CallSpecifiedPathwiseMultiProduct::CallSpecifiedPathwiseMultiProduct(), and QuantLib::MarketModelComposite::finalize().
{
        std::vector<Time> allTimes;
        for (Size i=0; i<times.size(); i++) {
            allTimes.insert(allTimes.end(),
                            times[i].begin(),
                            times[i].end());
        }
        // ...sort and compact the vector mergedTimes...
        std::sort(allTimes.begin(), allTimes.end());
        std::vector<Time>::iterator end = std::unique(allTimes.begin(),
                                                      allTimes.end());
        //mergedTimes.clear(); // shouldn't be cleared?
        mergedTimes.insert(mergedTimes.end(),
                           allTimes.begin(), end);
        isPresent.resize(times.size());
        for (Size i=0; i<times.size(); i++) {
            isPresent[i].resize(allTimes.size());
            for (Size j=0; j<allTimes.size(); j++) {
                isPresent[i][j] = std::binary_search(times[i].begin(),
                                                     times[i].end(),
                                                     allTimes[j]);
            }
        }
    }
Real QuantLib::midEquivalent (const Real bid, const Real ask, const Real last, const Real close)
return the MidEquivalent price, i.e. the mid if available, or a suitable substitute if the proper mid is not available
Definition at line 27 of file prices.cpp.
References close(), and QL_REQUIRE.
    {
        if (bid != Null<Real>() && bid > 0.0) {
            if (ask != Null<Real>() && ask > 0.0) return ((bid+ask)/2.0);
            else                                  return bid;
        } else {
            if (ask != Null<Real>() && ask > 0.0)          return ask;
            else if (last != Null<Real>() && last > 0.0)   return last;
            else {
                QL_REQUIRE(close != Null<Real>() && close > 0.0,
                           "all input prices are invalid");
                return close;
            }
        }
    }
Real QuantLib::midSafe (const Real bid, const Real ask)
return the MidSafe price, i.e. the mid only if both bid and ask prices are available
Definition at line 46 of file prices.cpp.
References QL_REQUIRE.
    {
        QL_REQUIRE(bid != Null<Real>() && bid > 0.0,
                   "invalid bid price");
        QL_REQUIRE(ask != Null<Real>() && ask > 0.0,
                   "invalid ask price");
        return (bid+ask)/2.0;
    }
std::vector< Size > QuantLib::moneyMarketMeasure (const EvolutionDescription &)
Discretely compounded money market account measure: for each step the first unexpired bond is used as numeraire.
Definition at line 188 of file evolutiondescription.cpp.
References moneyMarketPlusMeasure().
Referenced by anonymous_namespace{marketmodel_smm.cpp}::makeMeasure(), anonymous_namespace{marketmodel_cms.cpp}::makeMeasure(), anonymous_namespace{marketmodel_smmcapletcalibration.cpp}::makeMeasure(), anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::makeMeasure(), anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::makeMeasure(), anonymous_namespace{marketmodel.cpp}::makeMeasure(), QuantLib::PathwiseVegasAccountingEngine::PathwiseVegasAccountingEngine(), and QuantLib::PathwiseVegasOuterAccountingEngine::PathwiseVegasOuterAccountingEngine().
{
        return moneyMarketPlusMeasure(evol, 0);
    }
std::vector< Size > QuantLib::moneyMarketPlusMeasure (const EvolutionDescription & , Size offset = 1)
Offsetted discretely compounded money market account measure: for each step the offset-th unexpired bond is used as numeraire. When offset=0 the result is the usual discretely compounded money market account measure
Definition at line 168 of file evolutiondescription.cpp.
References QuantLib::EvolutionDescription::evolutionTimes(), QL_REQUIRE, QuantLib::EvolutionDescription::rateTimes(), and anonymous_namespace{marketmodel.cpp}::rateTimes.
Referenced by anonymous_namespace{marketmodel_smm.cpp}::makeMeasure(), anonymous_namespace{marketmodel_cms.cpp}::makeMeasure(), anonymous_namespace{marketmodel_smmcapletcalibration.cpp}::makeMeasure(), anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::makeMeasure(), anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::makeMeasure(), anonymous_namespace{marketmodel.cpp}::makeMeasure(), moneyMarketMeasure(), and MarketModelTest::testDriftCalculator().
{
        const std::vector<Time>& rateTimes = ev.rateTimes();
        Size maxNumeraire = rateTimes.size()-1;
        QL_REQUIRE(offset<=maxNumeraire,
                   "offset (" << offset <<
                   ") is greater than the max allowed value for numeraire ("
                   << maxNumeraire << ")");
        const std::vector<Time>& evolutionTimes = ev.evolutionTimes();
        Size n = evolutionTimes.size();
        std::vector<Size> numeraires(n);
        for (Size i=0, j=0; i<n; ++i) {
            while (rateTimes[j] < evolutionTimes[i])
                j++;
            numeraires[i] = std::min(j+offset, maxNumeraire);
        }
        return numeraires;
    }
Real QuantLib::months (const Period & p) [related]
Definition at line 292 of file period.cpp.
References Days, QuantLib::Period::length(), Months, QL_FAIL, QuantLib::Period::units(), Weeks, and Years.
Referenced by QuantLib::ActualActual::ISMA_Impl::yearFraction().
{
        if (p.length()==0) return 0.0;
        switch (p.units()) {
          case Days:
            QL_FAIL("cannot convert Days into Months");
          case Weeks:
            QL_FAIL("cannot convert Weeks into Months");
          case Months:
              return p.length();
          case Years:
              return p.length()*12.0;
          default:
            QL_FAIL("unknown time unit (" << Integer(p.units()) << ")");
        }
    }
template<class Iterator > Real QuantLib::norm (const Iterator & begin, const Iterator & end, Real h)
Definition at line 154 of file utilities.hpp.
References anonymous_namespace{matrices.cpp}::I.
Referenced by QuantLib::BasisIncompleteOrdered::addVector(), QuantLib::AnalyticEuropeanMargrabeEngine::calculate(), QuantLib::anonymous_namespace{pseudosqrt.cpp}::normalizePseudoRoot(), QuantLib::anonymous_namespace{pseudosqrt.cpp}::normInf(), QuantLib::OrthogonalProjections::OrthogonalProjections(), OperatorTest::testConsistency(), MatricesTest::testEigenvectors(), MatricesTest::testHighamSqrt(), MatricesTest::testInverse(), DistributionTest::testNormal(), MatricesTest::testQRDecomposition(), MatricesTest::testQRSolve(), CovarianceTest::testRankReduction(), CovarianceTest::testSalvagingMatrix(), MatricesTest::testSqrt(), and MatricesTest::testSVD().
{
        // squared values
        std::vector<Real> f2(end-begin);
        std::transform(begin,end,begin,f2.begin(),
                       std::multiplies<Real>());
        // numeric integral of f^2
        Real I = h * (std::accumulate(f2.begin(),f2.end(),0.0)
                      - 0.5*f2.front() - 0.5*f2.back());
        return std::sqrt(I);
    }
bool QuantLib::operator!= (const Loss & l1, const Loss & l2) [inline]
Definition at line 46 of file loss.hpp.
References QuantLib::Loss::time.
{
        return (l1.time != l2.time);
    }
bool QuantLib::operator!= (const Region & r1, const Region & r2) [related]
Definition at line 108 of file region.hpp.
References QuantLib::Region::name().
{
        return !(r1.name() == r2.name());
    }
bool QuantLib::operator!= (const CommodityType & c1, const CommodityType & c2) [related]
Definition at line 111 of file commoditytype.hpp.
{
        return !(c1 == c2);
    }
bool QuantLib::operator!= (const PaymentTerm & c1, const PaymentTerm & c2) [related]
Definition at line 115 of file paymentterm.hpp.
{
        return !(c1 == c2);
    }
bool QuantLib::operator!= (const UnitOfMeasure & c1, const UnitOfMeasure & c2) [related]
Definition at line 136 of file unitofmeasure.hpp.
{
        return !(c1 == c2);
    }
bool QuantLib::operator!= (const DayCounter & d1, const DayCounter & d2) [related]
Definition at line 138 of file daycounter.hpp.
{
        return !(d1 == d2);
    }
bool QuantLib::operator!= (const Currency & c1, const Currency & c2) [related]
Definition at line 159 of file currency.hpp.
{
        return !(c1 == c2);
    }
bool QuantLib::operator!= (const Period & p1, const Period & p2) [related]
Definition at line 165 of file period.hpp.
{
        return !(p1 == p2);
    }
bool QuantLib::operator!= (const DefaultEvent & lhs, const DefaultEvent & rhs) [inline]
Definition at line 183 of file defaultevent.hpp.
{
        return !(lhs == rhs);
    }
bool QuantLib::operator!= (const Quantity & m1, const Quantity & m2) [related]
Definition at line 199 of file quantity.hpp.
{
        return !(m1 == m2);
    }
bool QuantLib::operator!= (const Money & m1, const Money & m2) [related]
Definition at line 203 of file money.hpp.
{
        return !(m1 == m2);
    }
bool QuantLib::operator!= (const Calendar & c1, const Calendar & c2) [related]
Definition at line 224 of file calendar.hpp.
{
        return !(c1 == c2);
    }
bool QuantLib::operator!= (const Date & d1, const Date & d2) [related]
Definition at line 304 of file date.hpp.
References QuantLib::Date::serialNumber().
{
        return (d1.serialNumber() != d2.serialNumber());
    }
template<typename T > Period QuantLib::operator* (T n, TimeUnit units) [related]
Definition at line 140 of file period.hpp.
{
        return Period(Integer(n),units);
    }
template<typename T > Period QuantLib::operator* (TimeUnit units, T n) [related]
Definition at line 145 of file period.hpp.
{
        return Period(Integer(n),units);
    }
Period QuantLib::operator* (Integer n, const Period & p) [related]
Definition at line 153 of file period.hpp.
References QuantLib::Period::length(), and QuantLib::Period::units().
{
        return Period(n*p.length(),p.units());
    }
Period QuantLib::operator* (const Period & p, Integer n) [related]
Definition at line 157 of file period.hpp.
References QuantLib::Period::length(), and QuantLib::Period::units().
{
        return Period(n*p.length(),p.units());
    }
Quantity QuantLib::operator* (const Quantity & m, Real x) [related]
Definition at line 183 of file quantity.hpp.
{
        Quantity tmp = m;
        tmp *= x;
        return tmp;
    }
Money QuantLib::operator* (const Money & m, Decimal x) [related]
Definition at line 187 of file money.hpp.
{
        Money tmp = m;
        tmp *= x;
        return tmp;
    }
Quantity QuantLib::operator* (Real x, const Quantity & m) [related]
Definition at line 189 of file quantity.hpp.
{
        return m*x;
    }
Money QuantLib::operator* (Decimal x, const Money & m) [related]
Definition at line 193 of file money.hpp.
{
        return m*x;
    }
Money QuantLib::operator* (Decimal value, const Currency & c) [related]
Definition at line 215 of file money.hpp.
{
        return Money(value,c);
    }
Money QuantLib::operator* (const Currency & c, Decimal value) [related]
Definition at line 219 of file money.hpp.
{
        return Money(value,c);
    }
Disposable<TridiagonalOperator> QuantLib::operator* (Real a, const TridiagonalOperator & D) [inline]
Definition at line 224 of file tridiagonaloperator.hpp.
References anonymous_namespace{marketmodel.cpp}::a, QuantLib::TridiagonalOperator::diagonal_, QuantLib::TridiagonalOperator::lowerDiagonal_, and QuantLib::TridiagonalOperator::upperDiagonal_.
{
        Array low = D.lowerDiagonal_ * a,
            mid = D.diagonal_ * a,
            high = D.upperDiagonal_ * a;
        TridiagonalOperator result(low, mid, high);
        return result;
    }
Disposable<TridiagonalOperator> QuantLib::operator* (const TridiagonalOperator & D, Real a) [inline]
Definition at line 234 of file tridiagonaloperator.hpp.
References anonymous_namespace{marketmodel.cpp}::a, QuantLib::TridiagonalOperator::diagonal_, QuantLib::TridiagonalOperator::lowerDiagonal_, and QuantLib::TridiagonalOperator::upperDiagonal_.
                      {
        Array low = D.lowerDiagonal_ * a,
            mid = D.diagonal_ * a,
            high = D.upperDiagonal_ * a;
        TridiagonalOperator result(low, mid, high);
        return result;
    }
const Disposable<ComplexArray> QuantLib::operator* (const ComplexArray & v1, const ComplexArray & v2) [related]
Definition at line 467 of file complexarray.hpp.
References QuantLib::ComplexArray::begin(), QuantLib::ComplexArray::end(), QL_REQUIRE, and QuantLib::ComplexArray::size().
{
        QL_REQUIRE(v1.size() == v2.size(),
                   "arrays with different sizes (" << v1.size() << ", "
                   << v2.size() << ") cannot be multiplied");
        ComplexArray result(v1.size());
        std::transform(v1.begin(),v1.end(),v2.begin(),result.begin(),
                       std::multiplies<std::complex<Real> >());
        return result;
    }
const Disposable<Matrix> QuantLib::operator* (const Matrix & m, Real x) [related]
Definition at line 477 of file matrix.hpp.
References QuantLib::Matrix::begin(), QuantLib::Matrix::columns(), QuantLib::Matrix::end(), and QuantLib::Matrix::rows().
{
        Matrix temp(m.rows(),m.columns());
        std::transform(m.begin(),m.end(),temp.begin(),
                       std::bind2nd(std::multiplies<Real>(),x));
        return temp;
    }
const Disposable<ComplexArray> QuantLib::operator* (const ComplexArray & v1, std::complex< Real > a) [related]
Definition at line 478 of file complexarray.hpp.
References QuantLib::ComplexArray::begin(), QuantLib::ComplexArray::end(), and QuantLib::ComplexArray::size().
{
        ComplexArray result(v1.size());
        std::transform(v1.begin(),v1.end(),result.begin(),
                       std::bind2nd(std::multiplies<std::complex<Real> >(),a));
        return result;
    }
const Disposable<Matrix> QuantLib::operator* (Real x, const Matrix & m) [related]
Definition at line 484 of file matrix.hpp.
References QuantLib::Matrix::begin(), QuantLib::Matrix::columns(), QuantLib::Matrix::end(), and QuantLib::Matrix::rows().
{
        Matrix temp(m.rows(),m.columns());
        std::transform(m.begin(),m.end(),temp.begin(),
                       std::bind2nd(std::multiplies<Real>(),x));
        return temp;
    }
const Disposable<ComplexArray> QuantLib::operator* (std::complex< Real > a, const ComplexArray & v2) [related]
Definition at line 485 of file complexarray.hpp.
References QuantLib::ComplexArray::begin(), QuantLib::ComplexArray::end(), and QuantLib::ComplexArray::size().
{
        ComplexArray result(v2.size());
        std::transform(v2.begin(),v2.end(),result.begin(),
                       std::bind1st(std::multiplies<std::complex<Real> >(),a));
        return result;
    }
const Disposable<Array> QuantLib::operator* (const Array & v, const Matrix & m) [related]
Definition at line 498 of file matrix.hpp.
References QuantLib::Array::begin(), QuantLib::Matrix::column_begin(), QuantLib::Matrix::columns(), QuantLib::Array::end(), QuantLib::dsd::inner_product(), QL_REQUIRE, QuantLib::Matrix::rows(), and QuantLib::Array::size().
{
        QL_REQUIRE(v.size() == m.rows(),
                   "vectors and matrices with different sizes ("
                   << v.size() << ", " << m.rows() << "x" << m.columns() <<
                   ") cannot be multiplied");
        Array result(m.columns());
        for (Size i=0; i<result.size(); i++)
            result[i] =
                std::inner_product(v.begin(),v.end(),
                                   m.column_begin(i),0.0);
        return result;
    }
const Disposable<Array> QuantLib::operator* (const Matrix & m, const Array & v) [related]
Definition at line 511 of file matrix.hpp.
References QuantLib::Array::begin(), QuantLib::Matrix::columns(), QuantLib::Array::end(), QuantLib::dsd::inner_product(), QL_REQUIRE, QuantLib::Matrix::row_begin(), QuantLib::Matrix::rows(), and QuantLib::Array::size().
{
        QL_REQUIRE(v.size() == m.columns(),
                   "vectors and matrices with different sizes ("
                   << v.size() << ", " << m.rows() << "x" << m.columns() <<
                   ") cannot be multiplied");
        Array result(m.rows());
        for (Size i=0; i<result.size(); i++)
            result[i] =
                std::inner_product(v.begin(),v.end(),m.row_begin(i),0.0);
        return result;
    }
const Disposable<Matrix> QuantLib::operator* (const Matrix & m1, const Matrix & m2) [related]
Definition at line 523 of file matrix.hpp.
References QuantLib::Matrix::column_begin(), QuantLib::Matrix::columns(), QuantLib::dsd::inner_product(), QL_REQUIRE, QuantLib::Matrix::row_begin(), QuantLib::Matrix::row_end(), and QuantLib::Matrix::rows().
{
        QL_REQUIRE(m1.columns() == m2.rows(),
                   "matrices with different sizes (" <<
                   m1.rows() << "x" << m1.columns() << ", " <<
                   m2.rows() << "x" << m2.columns() << ") cannot be "
                   "multiplied");
        Matrix result(m1.rows(),m2.columns());
        for (Size i=0; i<result.rows(); i++)
            for (Size j=0; j<result.columns(); j++)
                result[i][j] =
                    std::inner_product(m1.row_begin(i), m1.row_end(i),
                                       m2.column_begin(j), 0.0);
        return result;
    }
const Disposable<Array> QuantLib::operator* (const Array & v1, const Array & v2) [related]
Definition at line 545 of file array.hpp.
References QuantLib::Array::begin(), QuantLib::Array::end(), QL_REQUIRE, and QuantLib::Array::size().
{
        QL_REQUIRE(v1.size() == v2.size(),
                   "arrays with different sizes (" << v1.size() << ", "
                   << v2.size() << ") cannot be multiplied");
        Array result(v1.size());
        std::transform(v1.begin(),v1.end(),v2.begin(),result.begin(),
                       std::multiplies<Real>());
        return result;
    }
const Disposable<Array> QuantLib::operator* (const Array & v1, Real a) [related]
Definition at line 556 of file array.hpp.
References QuantLib::Array::begin(), QuantLib::Array::end(), and QuantLib::Array::size().
{
        Array result(v1.size());
        std::transform(v1.begin(),v1.end(),result.begin(),
                       std::bind2nd(std::multiplies<Real>(),a));
        return result;
    }
const Disposable<Array> QuantLib::operator* (Real a, const Array & v2) [related]
Definition at line 563 of file array.hpp.
References QuantLib::Array::begin(), QuantLib::Array::end(), and QuantLib::Array::size().
{
        Array result(v2.size());
        std::transform(v2.begin(),v2.end(),result.begin(),
                       std::bind1st(std::multiplies<Real>(),a));
        return result;
    }
Quantity QuantLib::operator+ (const Quantity & m1, const Quantity & m2) [related]
Definition at line 171 of file quantity.hpp.
{
        Quantity tmp = m1;
        tmp += m2;
        return tmp;
    }
Money QuantLib::operator+ (const Money & m1, const Money & m2) [related]
Definition at line 175 of file money.hpp.
{
        Money tmp = m1;
        tmp += m2;
        return tmp;
    }
Disposable<TridiagonalOperator> QuantLib::operator+ (const TridiagonalOperator & D) [inline]
Definition at line 189 of file tridiagonaloperator.hpp.
{
        TridiagonalOperator D1 = D;
        return D1;
    }
Disposable<TridiagonalOperator> QuantLib::operator+ (const TridiagonalOperator & D1, const TridiagonalOperator & D2) [inline]
Definition at line 204 of file tridiagonaloperator.hpp.
References QuantLib::TridiagonalOperator::diagonal_, QuantLib::TridiagonalOperator::lowerDiagonal_, and QuantLib::TridiagonalOperator::upperDiagonal_.
{
        Array low = D1.lowerDiagonal_ + D2.lowerDiagonal_,
            mid = D1.diagonal_ + D2.diagonal_,
            high = D1.upperDiagonal_ + D2.upperDiagonal_;
        TridiagonalOperator result(low, mid, high);
        return result;
    }
Period QuantLib::operator+ (const Period & p1, const Period & p2) [related]
Definition at line 376 of file period.cpp.
{
        Period result = p1;
        result += p2;
        return result;
    }
const Disposable<ComplexArray> QuantLib::operator+ (const ComplexArray & v) [related]
Definition at line 402 of file complexarray.hpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v().
{
        ComplexArray result = v;
        return result;
    }
const Disposable<ComplexArray> QuantLib::operator+ (const ComplexArray & v1, const ComplexArray & v2) [related]
Definition at line 417 of file complexarray.hpp.
References QuantLib::ComplexArray::begin(), QuantLib::ComplexArray::end(), QL_REQUIRE, and QuantLib::ComplexArray::size().
{
        QL_REQUIRE(v1.size() == v2.size(),
                   "arrays with different sizes (" << v1.size() << ", "
                   << v2.size() << ") cannot be added");
        ComplexArray result(v1.size());
        std::transform(v1.begin(),v1.end(),v2.begin(),result.begin(),
                       std::plus<std::complex<Real> >());
        return result;
    }
const Disposable<ComplexArray> QuantLib::operator+ (const ComplexArray & v1, std::complex< Real > a) [related]
Definition at line 428 of file complexarray.hpp.
References QuantLib::ComplexArray::begin(), QuantLib::ComplexArray::end(), and QuantLib::ComplexArray::size().
{
        ComplexArray result(v1.size());
        std::transform(v1.begin(),v1.end(),result.begin(),
                       std::bind2nd(std::plus<std::complex<Real> >(),a));
        return result;
    }
const Disposable<ComplexArray> QuantLib::operator+ (std::complex< Real > a, const ComplexArray & v2) [related]
Definition at line 435 of file complexarray.hpp.
References QuantLib::ComplexArray::begin(), QuantLib::ComplexArray::end(), and QuantLib::ComplexArray::size().
{
        ComplexArray result(v2.size());
        std::transform(v2.begin(),v2.end(),result.begin(),
                       std::bind1st(std::plus<std::complex<Real> >(),a));
        return result;
    }
const Disposable<Matrix> QuantLib::operator+ (const Matrix & m1, const Matrix & m2) [related]
Definition at line 449 of file matrix.hpp.
References QuantLib::Matrix::begin(), QuantLib::Matrix::columns(), QuantLib::Matrix::end(), QL_REQUIRE, and QuantLib::Matrix::rows().
{
        QL_REQUIRE(m1.rows() == m2.rows() &&
                   m1.columns() == m2.columns(),
                   "matrices with different sizes (" <<
                   m1.rows() << "x" << m1.columns() << ", " <<
                   m2.rows() << "x" << m2.columns() << ") cannot be "
                   "added");
        Matrix temp(m1.rows(),m1.columns());
        std::transform(m1.begin(),m1.end(),m2.begin(),temp.begin(),
                       std::plus<Real>());
        return temp;
    }
const Disposable<Array> QuantLib::operator+ (const Array & v) [related]
Definition at line 480 of file array.hpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v().
{
        Array result = v;
        return result;
    }
const Disposable<Array> QuantLib::operator+ (const Array & v1, const Array & v2) [related]
Definition at line 495 of file array.hpp.
References QuantLib::Array::begin(), QuantLib::Array::end(), QL_REQUIRE, and QuantLib::Array::size().
{
        QL_REQUIRE(v1.size() == v2.size(),
                   "arrays with different sizes (" << v1.size() << ", "
                   << v2.size() << ") cannot be added");
        Array result(v1.size());
        std::transform(v1.begin(),v1.end(),v2.begin(),result.begin(),
                       std::plus<Real>());
        return result;
    }
const Disposable<Array> QuantLib::operator+ (const Array & v1, Real a) [related]
Definition at line 506 of file array.hpp.
References QuantLib::Array::begin(), QuantLib::Array::end(), and QuantLib::Array::size().
{
        Array result(v1.size());
        std::transform(v1.begin(),v1.end(),result.begin(),
                       std::bind2nd(std::plus<Real>(),a));
        return result;
    }
const Disposable<Array> QuantLib::operator+ (Real a, const Array & v2) [related]
Definition at line 513 of file array.hpp.
References QuantLib::Array::begin(), QuantLib::Array::end(), and QuantLib::Array::size().
{
        Array result(v2.size());
        std::transform(v2.begin(),v2.end(),result.begin(),
                       std::bind1st(std::plus<Real>(),a));
        return result;
    }
Period QuantLib::operator- (const Period & p) [related]
Definition at line 149 of file period.hpp.
References QuantLib::Period::length(), and QuantLib::Period::units().
{
        return Period(-p.length(),p.units());
    }
Quantity QuantLib::operator- (const Quantity & m1, const Quantity & m2) [related]
Definition at line 177 of file quantity.hpp.
{
        Quantity tmp = m1;
        tmp -= m2;
        return tmp;
    }
Money QuantLib::operator- (const Money & m1, const Money & m2) [related]
Definition at line 181 of file money.hpp.
{
        Money tmp = m1;
        tmp -= m2;
        return tmp;
    }
Disposable<TridiagonalOperator> QuantLib::operator- (const TridiagonalOperator & D) [inline]
Definition at line 195 of file tridiagonaloperator.hpp.
References QuantLib::TridiagonalOperator::diagonal_, QuantLib::TridiagonalOperator::lowerDiagonal_, and QuantLib::TridiagonalOperator::upperDiagonal_.
{
        Array low = -D.lowerDiagonal_,
            mid = -D.diagonal_,
            high = -D.upperDiagonal_;
        TridiagonalOperator result(low, mid, high);
        return result;
    }
Disposable<TridiagonalOperator> QuantLib::operator- (const TridiagonalOperator & D1, const TridiagonalOperator & D2) [inline]
Definition at line 214 of file tridiagonaloperator.hpp.
References QuantLib::TridiagonalOperator::diagonal_, QuantLib::TridiagonalOperator::lowerDiagonal_, and QuantLib::TridiagonalOperator::upperDiagonal_.
{
        Array low = D1.lowerDiagonal_ - D2.lowerDiagonal_,
            mid = D1.diagonal_ - D2.diagonal_,
            high = D1.upperDiagonal_ - D2.upperDiagonal_;
        TridiagonalOperator result(low, mid, high);
        return result;
    }
BigInteger QuantLib::operator- (const Date & d1, const Date & d2) [related]
Definition at line 296 of file date.hpp.
References QuantLib::Date::serialNumber().
{
        return d1.serialNumber()-d2.serialNumber();
    }
Period QuantLib::operator- (const Period & p1, const Period & p2) [related]
Definition at line 382 of file period.cpp.
{
        return p1+(-p2);
    }
const Disposable<ComplexArray> QuantLib::operator- (const ComplexArray & v) [related]
Definition at line 407 of file complexarray.hpp.
References QuantLib::ComplexArray::begin(), QuantLib::ComplexArray::end(), and QuantLib::ComplexArray::size().
{
        ComplexArray result(v.size());
        std::transform(v.begin(),v.end(),result.begin(),
                       std::negate<std::complex<Real> >());
        return result;
    }
const Disposable<ComplexArray> QuantLib::operator- (const ComplexArray & v1, const ComplexArray & v2) [related]
Definition at line 442 of file complexarray.hpp.
References QuantLib::ComplexArray::begin(), QuantLib::ComplexArray::end(), QL_REQUIRE, and QuantLib::ComplexArray::size().
{
        QL_REQUIRE(v1.size() == v2.size(),
                   "arrays with different sizes (" << v1.size() << ", "
                   << v2.size() << ") cannot be subtracted");
        ComplexArray result(v1.size());
        std::transform(v1.begin(),v1.end(),v2.begin(),result.begin(),
                       std::minus<std::complex<Real> >());
        return result;
    }
const Disposable<ComplexArray> QuantLib::operator- (const ComplexArray & v1, std::complex< Real > a) [related]
Definition at line 453 of file complexarray.hpp.
References QuantLib::ComplexArray::begin(), QuantLib::ComplexArray::end(), and QuantLib::ComplexArray::size().
{
        ComplexArray result(v1.size());
        std::transform(v1.begin(),v1.end(),result.begin(),
                       std::bind2nd(std::minus<std::complex<Real> >(),a));
        return result;
    }
const Disposable<ComplexArray> QuantLib::operator- (std::complex< Real > a, const ComplexArray & v2) [related]
Definition at line 460 of file complexarray.hpp.
References QuantLib::ComplexArray::begin(), QuantLib::ComplexArray::end(), and QuantLib::ComplexArray::size().
{
        ComplexArray result(v2.size());
        std::transform(v2.begin(),v2.end(),result.begin(),
                       std::bind1st(std::minus<std::complex<Real> >(),a));
        return result;
    }
const Disposable<Matrix> QuantLib::operator- (const Matrix & m1, const Matrix & m2) [related]
Definition at line 463 of file matrix.hpp.
References QuantLib::Matrix::begin(), QuantLib::Matrix::columns(), QuantLib::Matrix::end(), QL_REQUIRE, and QuantLib::Matrix::rows().
{
        QL_REQUIRE(m1.rows() == m2.rows() &&
                   m1.columns() == m2.columns(),
                   "matrices with different sizes (" <<
                   m1.rows() << "x" << m1.columns() << ", " <<
                   m2.rows() << "x" << m2.columns() << ") cannot be "
                   "subtracted");
        Matrix temp(m1.rows(),m1.columns());
        std::transform(m1.begin(),m1.end(),m2.begin(),temp.begin(),
                       std::minus<Real>());
        return temp;
    }
const Disposable<Array> QuantLib::operator- (const Array & v) [related]
Definition at line 485 of file array.hpp.
References QuantLib::Array::begin(), QuantLib::Array::end(), and QuantLib::Array::size().
{
        Array result(v.size());
        std::transform(v.begin(),v.end(),result.begin(),
                       std::negate<Real>());
        return result;
    }
const Disposable<Array> QuantLib::operator- (const Array & v1, const Array & v2) [related]
Definition at line 520 of file array.hpp.
References QuantLib::Array::begin(), QuantLib::Array::end(), QL_REQUIRE, and QuantLib::Array::size().
{
        QL_REQUIRE(v1.size() == v2.size(),
                   "arrays with different sizes (" << v1.size() << ", "
                   << v2.size() << ") cannot be subtracted");
        Array result(v1.size());
        std::transform(v1.begin(),v1.end(),v2.begin(),result.begin(),
                       std::minus<Real>());
        return result;
    }
const Disposable<Array> QuantLib::operator- (const Array & v1, Real a) [related]
Definition at line 531 of file array.hpp.
References QuantLib::Array::begin(), QuantLib::Array::end(), and QuantLib::Array::size().
{
        Array result(v1.size());
        std::transform(v1.begin(),v1.end(),result.begin(),
                       std::bind2nd(std::minus<Real>(),a));
        return result;
    }
const Disposable<Array> QuantLib::operator- (Real a, const Array & v2) [related]
Definition at line 538 of file array.hpp.
References QuantLib::Array::begin(), QuantLib::Array::end(), and QuantLib::Array::size().
{
        Array result(v2.size());
        std::transform(v2.begin(),v2.end(),result.begin(),
                       std::bind1st(std::minus<Real>(),a));
        return result;
    }
Decimal QuantLib::operator/ (const Money & m1, const Money & m2) [related]
Definition at line 86 of file money.cpp.
References QuantLib::Money::AutomatedConversion, QuantLib::Money::BaseCurrencyConversion, QuantLib::Money::conversionType, QuantLib::anonymous_namespace{quantity.cpp}::convertTo(), QuantLib::anonymous_namespace{quantity.cpp}::convertToBase(), QuantLib::Money::currency(), QL_FAIL, and QuantLib::Money::value().
{
        if (m1.currency() == m2.currency()) {
            return m1.value()/m2.value();
        } else if (Money::conversionType == Money::BaseCurrencyConversion) {
            Money tmp1 = m1;
            convertToBase(tmp1);
            Money tmp2 = m2;
            convertToBase(tmp2);
            return tmp1/tmp2;
        } else if (Money::conversionType == Money::AutomatedConversion) {
            Money tmp = m2;
            convertTo(tmp, m1.currency());
            return m1/tmp;
        } else {
            QL_FAIL("currency mismatch and no conversion specified");
        }
    }
Real QuantLib::operator/ (const Quantity & m1, const Quantity & m2) [related]
Definition at line 86 of file quantity.cpp.
References QuantLib::Quantity::amount(), QuantLib::Quantity::AutomatedConversion, QuantLib::Quantity::BaseUnitOfMeasureConversion, QuantLib::Quantity::conversionType, QuantLib::anonymous_namespace{quantity.cpp}::convertTo(), QuantLib::anonymous_namespace{quantity.cpp}::convertToBase(), QL_FAIL, and QuantLib::Quantity::unitOfMeasure().
{
        if (m1.unitOfMeasure() == m2.unitOfMeasure()) {
            return m1.amount()/m2.amount();
        } else if (Quantity::conversionType
                   == Quantity::BaseUnitOfMeasureConversion) {
            Quantity tmp1 = m1;
            convertToBase(tmp1);
            Quantity tmp2 = m2;
            convertToBase(tmp2);
            return tmp1/tmp2;
        } else if (Quantity::conversionType == Quantity::AutomatedConversion) {
            Quantity tmp = m2;
            convertTo(tmp, m1.unitOfMeasure());
            return m1/tmp;
        } else {
            QL_FAIL("unitOfMeasure mismatch and no conversion specified");
        }
    }
Quantity QuantLib::operator/ (const Quantity & m, Real x) [related]
Definition at line 193 of file quantity.hpp.
{
        Quantity tmp = m;
        tmp /= x;
        return tmp;
    }
Money QuantLib::operator/ (const Money & m, Decimal x) [related]
Definition at line 197 of file money.hpp.
{
        Money tmp = m;
        tmp /= x;
        return tmp;
    }
Disposable<TridiagonalOperator> QuantLib::operator/ (const TridiagonalOperator & D, Real a) [inline]
Definition at line 244 of file tridiagonaloperator.hpp.
References anonymous_namespace{marketmodel.cpp}::a, QuantLib::TridiagonalOperator::diagonal_, QuantLib::TridiagonalOperator::lowerDiagonal_, and QuantLib::TridiagonalOperator::upperDiagonal_.
                      {
        Array low = D.lowerDiagonal_ / a,
            mid = D.diagonal_ / a,
            high = D.upperDiagonal_ / a;
        TridiagonalOperator result(low, mid, high);
        return result;
    }
Period QuantLib::operator/ (const Period & p, Integer n) [related]
Definition at line 386 of file period.cpp.
{
        Period result = p;
        result /= n;
        return result;
    }
const Disposable<Matrix> QuantLib::operator/ (const Matrix & m, Real x) [related]
Definition at line 491 of file matrix.hpp.
References QuantLib::Matrix::begin(), QuantLib::Matrix::columns(), QuantLib::Matrix::end(), and QuantLib::Matrix::rows().
{
        Matrix temp(m.rows(),m.columns());
        std::transform(m.begin(),m.end(),temp.begin(),
                       std::bind2nd(std::divides<Real>(),x));
        return temp;
    }
const Disposable<ComplexArray> QuantLib::operator/ (const ComplexArray & v1, const ComplexArray & v2) [related]
Definition at line 492 of file complexarray.hpp.
References QuantLib::ComplexArray::begin(), QuantLib::ComplexArray::end(), QL_REQUIRE, and QuantLib::ComplexArray::size().
{
        QL_REQUIRE(v1.size() == v2.size(),
                   "arrays with different sizes (" << v1.size() << ", "
                   << v2.size() << ") cannot be divided");
        ComplexArray result(v1.size());
        std::transform(v1.begin(),v1.end(),v2.begin(),result.begin(),
                       std::divides<std::complex<Real> >());
        return result;
    }
const Disposable<ComplexArray> QuantLib::operator/ (const ComplexArray & v1, std::complex< Real > a) [related]
Definition at line 503 of file complexarray.hpp.
References QuantLib::ComplexArray::begin(), QuantLib::ComplexArray::end(), and QuantLib::ComplexArray::size().
{
        ComplexArray result(v1.size());
        std::transform(v1.begin(),v1.end(),result.begin(),
                       std::bind2nd(std::divides<std::complex<Real> >(),a));
        return result;
    }
const Disposable<ComplexArray> QuantLib::operator/ (std::complex< Real > a, const ComplexArray & v2) [related]
Definition at line 510 of file complexarray.hpp.
References QuantLib::ComplexArray::begin(), QuantLib::ComplexArray::end(), and QuantLib::ComplexArray::size().
{
        ComplexArray result(v2.size());
        std::transform(v2.begin(),v2.end(),result.begin(),
                       std::bind1st(std::divides<std::complex<Real> >(),a));
        return result;
    }
const Disposable<Array> QuantLib::operator/ (const Array & v1, const Array & v2) [related]
Definition at line 570 of file array.hpp.
References QuantLib::Array::begin(), QuantLib::Array::end(), QL_REQUIRE, and QuantLib::Array::size().
{
        QL_REQUIRE(v1.size() == v2.size(),
                   "arrays with different sizes (" << v1.size() << ", "
                   << v2.size() << ") cannot be divided");
        Array result(v1.size());
        std::transform(v1.begin(),v1.end(),v2.begin(),result.begin(),
                       std::divides<Real>());
        return result;
    }
const Disposable<Array> QuantLib::operator/ (const Array & v1, Real a) [related]
Definition at line 581 of file array.hpp.
References QuantLib::Array::begin(), QuantLib::Array::end(), and QuantLib::Array::size().
{
        Array result(v1.size());
        std::transform(v1.begin(),v1.end(),result.begin(),
                       std::bind2nd(std::divides<Real>(),a));
        return result;
    }
const Disposable<Array> QuantLib::operator/ (Real a, const Array & v2) [related]
Definition at line 588 of file array.hpp.
References QuantLib::Array::begin(), QuantLib::Array::end(), and QuantLib::Array::size().
{
        Array result(v2.size());
        std::transform(v2.begin(),v2.end(),result.begin(),
                       std::bind1st(std::divides<Real>(),a));
        return result;
    }
bool QuantLib::operator< (const Loss & l1, const Loss & l2) [inline]
Definition at line 37 of file loss.hpp.
References QuantLib::Loss::time.
{
        return (l1.time < l2.time);
    }
bool QuantLib::operator< (const Money & m1, const Money & m2) [related]
Definition at line 122 of file money.cpp.
References QuantLib::Money::AutomatedConversion, QuantLib::Money::BaseCurrencyConversion, QuantLib::Money::conversionType, QuantLib::anonymous_namespace{quantity.cpp}::convertTo(), QuantLib::anonymous_namespace{quantity.cpp}::convertToBase(), QuantLib::Money::currency(), QL_FAIL, and QuantLib::Money::value().
{
        if (m1.currency() == m2.currency()) {
            return m1.value() < m2.value();
        } else if (Money::conversionType == Money::BaseCurrencyConversion) {
            Money tmp1 = m1;
            convertToBase(tmp1);
            Money tmp2 = m2;
            convertToBase(tmp2);
            return tmp1 < tmp2;
        } else if (Money::conversionType == Money::AutomatedConversion) {
            Money tmp = m2;
            convertTo(tmp, m1.currency());
            return m1 < tmp;
        } else {
            QL_FAIL("currency mismatch and no conversion specified");
        }
    }
bool QuantLib::operator< (const Quantity & m1, const Quantity & m2) [related]
Definition at line 125 of file quantity.cpp.
References QuantLib::Quantity::amount(), QuantLib::Quantity::AutomatedConversion, QuantLib::Quantity::BaseUnitOfMeasureConversion, QuantLib::Quantity::conversionType, QuantLib::anonymous_namespace{quantity.cpp}::convertTo(), QuantLib::anonymous_namespace{quantity.cpp}::convertToBase(), QL_FAIL, and QuantLib::Quantity::unitOfMeasure().
{
        if (m1.unitOfMeasure() == m2.unitOfMeasure()) {
            return m1.amount() < m2.amount();
        } else if (Quantity::conversionType
                   == Quantity::BaseUnitOfMeasureConversion) {
            Quantity tmp1 = m1;
            convertToBase(tmp1);
            Quantity tmp2 = m2;
            convertToBase(tmp2);
            return tmp1 < tmp2;
        } else if (Quantity::conversionType == Quantity::AutomatedConversion) {
            Quantity tmp = m2;
            convertTo(tmp, m1.unitOfMeasure());
            return m1 < tmp;
        } else {
            QL_FAIL("unitOfMeasure mismatch and no conversion specified");
        }
    }
bool QuantLib::operator< (const Date & d1, const Date & d2) [related]
Definition at line 308 of file date.hpp.
References QuantLib::Date::serialNumber().
{
        return (d1.serialNumber() < d2.serialNumber());
    }
bool QuantLib::operator< (const Period & p1, const Period & p2) [related]
Definition at line 343 of file period.cpp.
References Days, QuantLib::anonymous_namespace{amortizingfixedratebond.cpp}::daysMinMax(), QuantLib::Period::length(), Months, QL_FAIL, QuantLib::Period::units(), Weeks, and Years.
{
        // special cases
        if (p1.length() == 0)
            return p2.length() > 0;
        if (p2.length() == 0)
            return p1.length() < 0;
        // exact comparisons
        if (p1.units() == p2.units())
            return p1.length() < p2.length();
        if (p1.units() == Months && p2.units() == Years)
            return p1.length() < 12*p2.length();
        if (p1.units() == Years && p2.units() == Months)
            return 12*p1.length() < p2.length();
        if (p1.units() == Days && p2.units() == Weeks)
            return p1.length() < 7*p2.length();
        if (p1.units() == Weeks && p2.units() == Days)
            return 7*p1.length() < p2.length();
        // inexact comparisons (handled by converting to days and using limits)
        std::pair<Integer, Integer> p1lim = daysMinMax(p1);
        std::pair<Integer, Integer> p2lim = daysMinMax(p2);
        if (p1lim.second < p2lim.first)
            return true;
        else if (p1lim.first > p2lim.second)
            return false;
        else
            QL_FAIL("undecidable comparison between " << p1 << " and " << p2);
    }
std::ostream& QuantLib::operator<< (std::ostream & out, const UnitOfMeasure & c) [related]
Definition at line 24 of file unitofmeasure.cpp.
References QuantLib::UnitOfMeasure::code(), and QuantLib::UnitOfMeasure::empty().
{
        if (!c.empty())
            return out << c.code();
        else
            return out << "null unit of measure";
    }
std::ostream& QuantLib::operator<< (std::ostream & out, const DateInterval & di)
Definition at line 24 of file dateinterval.cpp.
References QuantLib::DateInterval::endDate_, and QuantLib::DateInterval::startDate_.
{
        if (di.startDate_ == Date() || di.endDate_ == Date())
            return out << "Null<DateInterval>()";
        return out << di.startDate_ << " to " << di.endDate_;
    }
std::ostream& QuantLib::operator<< (std::ostream & out, const Currency & c) [related]
Definition at line 24 of file currency.cpp.
References QuantLib::Currency::code(), and QuantLib::Currency::empty().
{
        if (!c.empty())
            return out << c.code();
        else
            return out << "null currency";
    }
std::ostream & QuantLib::operator<< (std::ostream & out, const CommodityUnitCost & unitCost)
Definition at line 24 of file commodityunitcost.cpp.
References QuantLib::CommodityUnitCost::amount(), QuantLib::Currency::code(), QuantLib::UnitOfMeasure::code(), QuantLib::Money::currency(), QuantLib::CommodityUnitCost::unitOfMeasure(), and QuantLib::Money::value().
{
        out << unitCost.amount().value() << " "
            << unitCost.amount().currency().code() << "/"
            << unitCost.unitOfMeasure().code();
        return out;
    }
std::ostream& QuantLib::operator<< (std::ostream & out, Position::Type p) [related]
Definition at line 26 of file position.cpp.
References QuantLib::Position::Long, QL_FAIL, and QuantLib::Position::Short.
{
        switch (p) {
          case Position::Long :
            return out << "Long";
          case Position::Short :
            return out << "Short";
          default:
            QL_FAIL("unknown Position Type (" << Integer(p) << ")");
        }
    }
std::ostream& QuantLib::operator<< (std::ostream & out, Replication::Type r) [related]
Definition at line 26 of file replication.cpp.
References QuantLib::Replication::Central, QL_FAIL, QuantLib::Replication::Sub, and QuantLib::Replication::Super.
{
        switch (r) {
          case Replication::Sub :
            return out << "Sub";
          case Replication::Central :
            return out << "Central";
          case Replication::Super :
            return out << "Super";
          default:
            QL_FAIL("unknown Replication Type (" << Integer(r) << ")");
        }
    }
std::ostream& QuantLib::operator<< (std::ostream & out, DateGeneration::Rule r) [related]
Definition at line 27 of file dategenerationrule.cpp.
References QuantLib::DateGeneration::Backward, QuantLib::DateGeneration::CDS, QuantLib::DateGeneration::Forward, QuantLib::DateGeneration::OldCDS, QL_FAIL, QuantLib::DateGeneration::ThirdWednesday, QuantLib::DateGeneration::Twentieth, QuantLib::DateGeneration::TwentiethIMM, and QuantLib::DateGeneration::Zero.
{
        switch (r) {
          case DateGeneration::Backward:
            return out << "Backward";
          case DateGeneration::Forward:
            return out << "Forward";
          case DateGeneration::Zero:
            return out << "Zero";
          case DateGeneration::ThirdWednesday:
            return out << "ThirdWednesday";
          case DateGeneration::Twentieth:
            return out << "Twentieth";
          case DateGeneration::TwentiethIMM:
            return out << "TwentiethIMM";
          case DateGeneration::OldCDS:
            return out << "OldCDS";
          case DateGeneration::CDS:
            return out << "CDS";
          default:
            QL_FAIL("unknown DateGeneration::Rule (" << Integer(r) << ")");
        }
    }
std::ostream& QuantLib::operator<< (std::ostream & out, const TimeUnit & timeunit)
Definition at line 28 of file timeunit.cpp.
References Days, Months, QL_FAIL, Weeks, and Years.
{
        switch (timeunit) {
            case Years:
                return out << "Years";
            case Months:
                return out << "Months";
            case Weeks:
                return out << "Weeks";
            case Days:
                return out << "Days";
            default:
                QL_FAIL("unknown TimeUnit");
        }
    }
std::ostream& QuantLib::operator<< (std::ostream & out, BusinessDayConvention b)
Definition at line 28 of file businessdayconvention.cpp.
References Following, ModifiedFollowing, ModifiedPreceding, Preceding, QL_FAIL, and Unadjusted.
{
        switch (b) {
          case Following:
            return out << "Following";
          case ModifiedFollowing:
            return out << "Modified Following";
          case Preceding:
            return out << "Preceding";
          case ModifiedPreceding:
            return out << "Modified Preceding";
          case Unadjusted:
            return out << "Unadjusted";
          default:
            QL_FAIL("unknown BusinessDayConvention (" << Integer(b) << ")");
        }
    }
std::ostream& QuantLib::operator<< (std::ostream & out, Frequency f)
Definition at line 29 of file frequency.cpp.
References Annual, Bimonthly, Biweekly, Daily, EveryFourthMonth, EveryFourthWeek, Monthly, NoFrequency, Once, OtherFrequency, QL_FAIL, Quarterly, Semiannual, and Weekly.
{
        switch (f) {
          case NoFrequency:
            return out << "No-Frequency";
          case Once:
            return out << "Once";
          case Annual:
            return out << "Annual";
          case Semiannual:
            return out << "Semiannual";
          case EveryFourthMonth:
            return out << "Every-Fourth-Month";
          case Quarterly:
            return out << "Quarterly";
          case Bimonthly:
            return out << "Bimonthly";
          case Monthly:
            return out << "Monthly";
          case EveryFourthWeek:
            return out << "Every-fourth-week";
          case Biweekly:
            return out << "Biweekly";
          case Weekly:
            return out << "Weekly";
          case Daily:
            return out << "Daily";
          case OtherFrequency:
            return out << "Unknown frequency";
          default:
            QL_FAIL("unknown frequency (" << Integer(f) << ")");
        }
    }
std::ostream & QuantLib::operator<< (std::ostream & out, Average::Type type)
Definition at line 28 of file averagetype.cpp.
References QuantLib::Average::Arithmetic, QuantLib::Average::Geometric, and QL_FAIL.
{
        switch (type) {
          case Average::Arithmetic:
            return out << "Arithmetic";
          case Average::Geometric:
            return out << "Geometric";
          default:
            QL_FAIL("unknown Average::Type (" << Integer(type) << ")");
        }
    }
std::ostream & QuantLib::operator<< (std::ostream & out, Barrier::Type type)
Definition at line 28 of file barriertype.cpp.
References QuantLib::Barrier::DownIn, QuantLib::Barrier::DownOut, QL_FAIL, QuantLib::Barrier::UpIn, and QuantLib::Barrier::UpOut.
{
        switch (type) {
          case Barrier::DownIn:
            return out << "Down&In";
          case Barrier::UpIn:
            return out << "Up&In";
          case Barrier::DownOut:
            return out << "Down&Out";
          case Barrier::UpOut:
            return out << "Up&Out";
          default:
            QL_FAIL("unknown Barrier::Type (" << Integer(type) << ")");
        }
    }
std::ostream& QuantLib::operator<< (std::ostream & out, Duration::Type d)
Definition at line 28 of file duration.cpp.
References QuantLib::Duration::Macaulay, QuantLib::Duration::Modified, QL_FAIL, and QuantLib::Duration::Simple.
{
        switch (d) {
          case Duration::Simple:
            return out << "Simple";
          case Duration::Macaulay:
            return out << "Macaulay";
          case Duration::Modified:
            return out << "Modified";
          default:
            QL_FAIL("unknown Duration::Type (" << Integer(d) << ")");
        }
    }
std::ostream& QuantLib::operator<< (std::ostream & out, const Settings::DateProxy & p)
Definition at line 29 of file settings.cpp.
{
        return out << Date(p);
    }
std::ostream& QuantLib::operator<< (std::ostream & out, SensitivityAnalysis s)
Definition at line 30 of file sensitivityanalysis.cpp.
References Centered, OneSide, and QL_FAIL.
{
        switch (s) {
          case OneSide:
            return out << "OneSide";
          case Centered:
            return out << "Centered";
          default:
            QL_FAIL("unknown SensitivityAnalysis (" << Integer(s) << ")");
        }
    }
std::ostream& QuantLib::operator<< (std::ostream & out, const Weekday & w)
Definition at line 32 of file weekday.cpp.
References QuantLib::io::long_weekday.
{
        return out << io::long_weekday(w);
    }
std::ostream & QuantLib::operator<< (std::ostream & out, YoYInflationCapFloor::Type t)
Definition at line 31 of file inflationcapfloor.cpp.
References QuantLib::YoYInflationCapFloor::Cap, QuantLib::YoYInflationCapFloor::Collar, QuantLib::YoYInflationCapFloor::Floor, and QL_FAIL.
{
        switch (t) {
            case YoYInflationCapFloor::Cap:
                return out << "YoYInflationCap";
            case YoYInflationCapFloor::Floor:
                return out << "YoYInflationFloor";
            case YoYInflationCapFloor::Collar:
                return out << "YoYInflationCollar";
            default:
                QL_FAIL("unknown YoYInflationCapFloor::Type (" << Integer(t) << ")");
        }
    }
std::ostream& QuantLib::operator<< (std::ostream & out, const CommodityType & c) [related]
Definition at line 39 of file commoditytype.cpp.
References QuantLib::CommodityType::code(), and QuantLib::CommodityType::empty().
{
        if (!c.empty())
            return out << c.code();
        else
            return out << "null commodity type";
    }
std::ostream& QuantLib::operator<< (std::ostream & out, const PaymentTerm & c) [related]
Definition at line 42 of file paymentterm.cpp.
References QuantLib::PaymentTerm::empty(), and QuantLib::PaymentTerm::name().
{
        if (!c.empty())
            return out << c.name();
        else
            return out << "null payment term type";
    }
std::ostream & QuantLib::operator<< (std::ostream & out, const SecondaryCostAmounts & secondaryCostAmounts)
Definition at line 44 of file commodity.cpp.
{
        std::string currencyCode;
        Real totalAmount = 0;
        out << "secondary costs" << std::endl;
        for (SecondaryCostAmounts::const_iterator i = secondaryCostAmounts.begin();
             i != secondaryCostAmounts.end(); i++) {
            Real amount = i->second.value();
            if (currencyCode == "")
                currencyCode = i->second.currency().code();
            totalAmount += amount;
            out << std::setw(28) << std::left << i->first
                << std::setw(12) << std::right << std::fixed
                << std::setprecision(2) << amount << " " << currencyCode
                << std::endl;
        }
        out << std::setw(28) << std::left << "total"
            << std::setw(12) << std::right << std::fixed
            << std::setprecision(2) << totalAmount << " " << currencyCode
            << std::endl;
        return out;
    }
std::ostream& QuantLib::operator<< (std::ostream & out, const CommodityIndex & index)
Definition at line 54 of file commodityindex.cpp.
References QuantLib::Currency::code(), QuantLib::UnitOfMeasure::code(), QuantLib::CommodityIndex::currency_, QuantLib::CommodityIndex::forwardCurve_, QuantLib::CommodityIndex::name_, and QuantLib::CommodityIndex::unitOfMeasure_.
{
        out << "[" << index.name_ << "] ("
            << index.currency_.code() << "/"
            << index.unitOfMeasure_.code() << ")";
        if (index.forwardCurve_ != 0)
            out << "; forward (" << (*index.forwardCurve_) << ")";
        return out;
    }
std::ostream & QuantLib::operator<< (std::ostream & out, const PricingError & error)
Definition at line 69 of file commodity.cpp.
References QuantLib::PricingError::detail, QuantLib::PricingError::Error, QuantLib::PricingError::error, QuantLib::PricingError::errorLevel, QuantLib::PricingError::Fatal, QuantLib::PricingError::Info, and QuantLib::PricingError::Warning.
{
        switch (error.errorLevel) {
          case PricingError::Info:
            out << "info: ";
            break;
          case PricingError::Warning:
            out << "warning: ";
            break;
          case PricingError::Error:
            out << "*** error: ";
            break;
          case PricingError::Fatal:
            out << "*** fatal: ";
            break;
        }
        out << error.error;
        if (error.detail != "")
            out << ": " << error.detail;
        return out;
    }
std::ostream & QuantLib::operator<< (std::ostream & out, Settlement::Type t)
Definition at line 88 of file swaption.cpp.
References QuantLib::Settlement::Cash, QuantLib::Settlement::Physical, and QL_FAIL.
{
        switch (t) {
          case Settlement::Physical:
            return out << "Delivery";
          case Settlement::Cash:
            return out << "Cash";
          default:
            QL_FAIL("unknown Settlement::Type(" << Integer(t) << ")");
        }
    }
std::ostream & QuantLib::operator<< (std::ostream & out, const PricingErrors & errors)
Definition at line 90 of file commodity.cpp.
{
        if (errors.size() > 0) {
            out << "*** pricing errors" << std::endl;
            for (PricingErrors::const_iterator i = errors.begin();
                 i != errors.end(); i++)
                out << *i << std::endl;
        }
        return out;
    }
std::ostream & QuantLib::operator<< (std::ostream & out, CapFloor::Type t)
Definition at line 91 of file capfloor.cpp.
References QuantLib::CapFloor::Cap, QuantLib::CapFloor::Collar, QuantLib::CapFloor::Floor, and QL_FAIL.
{
        switch (t) {
          case CapFloor::Cap:
            return out << "Cap";
          case CapFloor::Floor:
            return out << "Floor";
          case CapFloor::Collar:
            return out << "Collar";
          default:
            QL_FAIL("unknown CapFloor::Type (" << Integer(t) << ")");
        }
    }
std::ostream& QuantLib::operator<< (std::ostream & out, const CommodityCurve & curve)
Definition at line 98 of file commoditycurve.cpp.
References QuantLib::CommodityCurve::basisOfCurve_, QuantLib::Currency::code(), QuantLib::UnitOfMeasure::code(), QuantLib::CommodityCurve::currency_, QuantLib::CommodityCurve::name_, and QuantLib::CommodityCurve::unitOfMeasure_.
{
        out << "[" << curve.name_ << "] (" << curve.currency_.code()
            << "/" << curve.unitOfMeasure_.code() << ")";
        if (curve.basisOfCurve_ != 0)
            out << "; basis to (" << (*curve.basisOfCurve_) << ")";
        return out;
    }
std::ostream& QuantLib::operator<< (std::ostream & out, Option::Type type) [related]
Definition at line 104 of file option.hpp.
References QuantLib::Option::Call, QuantLib::Option::Put, and QL_FAIL.
{
        switch (type) {
          case Option::Call:
            return out << "Call";
          case Option::Put:
            return out << "Put";
          default:
            QL_FAIL("unknown option type");
        }
    }
std::ostream& QuantLib::operator<< (std::ostream & out, const InterestRate & ir) [related]
Definition at line 106 of file interestrate.cpp.
References Compounded, QuantLib::InterestRate::compounding(), Continuous, QuantLib::InterestRate::dayCounter(), QuantLib::InterestRate::frequency(), QuantLib::DayCounter::name(), NoFrequency, Once, QL_FAIL, QuantLib::InterestRate::rate(), QuantLib::io::rate(), Simple, and SimpleThenCompounded.
{
        if (ir.rate() == Null<Rate>())
            return out << "null interest rate";
        out << io::rate(ir.rate()) << " " << ir.dayCounter().name() << " ";
        switch (ir.compounding()) {
          case Simple:
            out << "simple compounding";
            break;
          case Compounded:
            switch (ir.frequency()) {
              case NoFrequency:
              case Once:
                QL_FAIL(ir.frequency() << " frequency not allowed "
                        "for this interest rate");
              default:
                out << ir.frequency() <<" compounding";
            }
            break;
          case Continuous:
            out << "continuous compounding";
            break;
          case SimpleThenCompounded:
            switch (ir.frequency()) {
              case NoFrequency:
              case Once:
                QL_FAIL(ir.frequency() << " frequency not allowed "
                        "for this interest rate");
              default:
                out << "simple compounding up to "
                    << Integer(12/ir.frequency()) << " months, then "
                    << ir.frequency() << " compounding";
            }
            break;
          default:
            QL_FAIL("unknown compounding convention ("
                    << Integer(ir.compounding()) << ")");
        }
        return out;
    }
std::ostream& QuantLib::operator<< (std::ostream & out, const DayCounter & d) [related]
Definition at line 142 of file daycounter.hpp.
References QuantLib::DayCounter::name().
{
        return out << d.name();
    }
std::ostream & QuantLib::operator<< (std::ostream & out, EndCriteria::Type ec)
Definition at line 160 of file endcriteria.cpp.
References QuantLib::EndCriteria::MaxIterations, QuantLib::EndCriteria::None, QL_FAIL, QuantLib::EndCriteria::StationaryFunctionAccuracy, QuantLib::EndCriteria::StationaryFunctionValue, QuantLib::EndCriteria::StationaryPoint, QuantLib::EndCriteria::Unknown, and QuantLib::EndCriteria::ZeroGradientNorm.
{
        switch (ec) {
        case QuantLib::EndCriteria::None:
            return out << "None";
        case QuantLib::EndCriteria::MaxIterations:
            return out << "MaxIterations";
        case QuantLib::EndCriteria::StationaryPoint:
            return out << "StationaryPoint";
        case QuantLib::EndCriteria::StationaryFunctionValue:
            return out << "StationaryFunctionValue";
        case QuantLib::EndCriteria::StationaryFunctionAccuracy:
            return out << "StationaryFunctionAccuracy";
        case QuantLib::EndCriteria::ZeroGradientNorm:
            return out << "ZeroGradientNorm";
        case QuantLib::EndCriteria::Unknown:
            return out << "Unknown";
        default:
            QL_FAIL("unknown EndCriteria::Type (" << Integer(ec) << ")");
        }
    }
std::ostream& QuantLib::operator<< (std::ostream & out, GFunctionFactory::YieldCurveModel type) [inline]
Definition at line 179 of file conundrumpricer.hpp.
References QuantLib::GFunctionFactory::ExactYield, QuantLib::GFunctionFactory::NonParallelShifts, QuantLib::GFunctionFactory::ParallelShifts, QL_FAIL, and QuantLib::GFunctionFactory::Standard.
{
        switch (type) {
          case GFunctionFactory::Standard:
            return out << "Standard";
          case GFunctionFactory::ExactYield:
            return out << "ExactYield";
          case GFunctionFactory::ParallelShifts:
            return out << "ParallelShifts";
          case GFunctionFactory::NonParallelShifts:
            return out << "NonParallelShifts";
          default:
            QL_FAIL("unknown option type");
        }
    }
std::ostream& QuantLib::operator<< (std::ostream & out, const Money & m) [related]
Definition at line 195 of file money.cpp.
References QuantLib::Currency::code(), QuantLib::Money::currency(), QuantLib::Currency::format(), anonymous_namespace{errors.cpp}::format(), QuantLib::Money::rounded(), QuantLib::Currency::symbol(), and QuantLib::Money::value().
{
        #if defined(QL_PATCH_MSVC71) && BOOST_VERSION > 103600
        // boost::format doesn't work with VC7 - simplified output
        return out << m.currency().code() << " "
                   << m.rounded().value();
        #else
        boost::format fmt(m.currency().format());
        fmt.exceptions(boost::io::all_error_bits ^
                       boost::io::too_many_args_bit);
        return out << fmt % m.rounded().value()
                          % m.currency().code()
                          % m.currency().symbol();
        #endif
    }
std::ostream& QuantLib::operator<< (std::ostream & out, const Quantity & quantity)
Definition at line 202 of file quantity.cpp.
References QuantLib::Quantity::amount_, QuantLib::CommodityType::code(), QuantLib::UnitOfMeasure::code(), QuantLib::Quantity::commodityType_, and QuantLib::Quantity::unitOfMeasure_.
{
        return out << quantity.commodityType_.code() << " "
                   << quantity.amount_ << " " << quantity.unitOfMeasure_.code();
    }
std::ostream& QuantLib::operator<< (std::ostream & out, const SampledCurve & a) [inline]
Definition at line 225 of file sampledcurve.hpp.
References QuantLib::SampledCurve::grid(), and QuantLib::SampledCurve::values().
{
        out << "[ " << a.grid() << "; "
            << a.values() << " ]";
        return out;
    }
std::ostream & QuantLib::operator<< (std::ostream & out, CPISwap::Type t)
Definition at line 225 of file cpiswap.cpp.
References QuantLib::CPISwap::Payer, QL_FAIL, and QuantLib::CPISwap::Receiver.
{
        switch (t) {
            case CPISwap::Payer:
                return out << "Payer";
            case CPISwap::Receiver:
                return out << "Receiver";
            default:
                QL_FAIL("unknown CPISwap::Type(" << Integer(t) << ")");
        }
    }
std::ostream& QuantLib::operator<< (std::ostream & out, const Calendar & c) [related]
Definition at line 228 of file calendar.hpp.
References QuantLib::Calendar::name().
{
        return out << c.name();
    }
std::ostream & QuantLib::operator<< (std::ostream & out, YearOnYearInflationSwap::Type t)
Definition at line 237 of file yearonyearinflationswap.cpp.
References QuantLib::YearOnYearInflationSwap::Payer, QL_FAIL, and QuantLib::YearOnYearInflationSwap::Receiver.
{
        switch (t) {
            case YearOnYearInflationSwap::Payer:
                return out << "Payer";
            case YearOnYearInflationSwap::Receiver:
                return out << "Receiver";
            default:
                QL_FAIL("unknown VanillaSwap::Type(" << Integer(t) << ")");
        }
    }
std::ostream & QuantLib::operator<< (std::ostream & out, VanillaSwap::Type t)
Definition at line 240 of file vanillaswap.cpp.
References QuantLib::VanillaSwap::Payer, QL_FAIL, and QuantLib::VanillaSwap::Receiver.
{
        switch (t) {
          case VanillaSwap::Payer:
            return out << "Payer";
          case VanillaSwap::Receiver:
            return out << "Receiver";
          default:
            QL_FAIL("unknown VanillaSwap::Type(" << Integer(t) << ")");
        }
    }
std::ostream& QuantLib::operator<< (std::ostream & out, const Period & p) [related]
Definition at line 394 of file period.cpp.
References QuantLib::io::short_period().
{
        return out << io::short_period(p);
    }
std::ostream& QuantLib::operator<< (std::ostream & out, Month m)
Definition at line 400 of file date.cpp.
References April, August, December, February, January, July, June, March, May, November, October, QL_FAIL, and September.
{
        switch (m) {
          case January:
            return out << "January";
          case February:
            return out << "February";
          case March:
            return out << "March";
          case April:
            return out << "April";
          case May:
            return out << "May";
          case June:
            return out << "June";
          case July:
            return out << "July";
          case August:
            return out << "August";
          case September:
            return out << "September";
          case October:
            return out << "October";
          case November:
            return out << "November";
          case December:
            return out << "December";
          default:
            QL_FAIL("unknown month (" << Integer(m) << ")");
        }
    }
std::ostream& QuantLib::operator<< (std::ostream & out, const Date & d) [related]
Definition at line 434 of file date.cpp.
References QuantLib::io::long_date().
{
        return out << io::long_date(d);
    }
std::ostream& QuantLib::operator<< (std::ostream & out, const ComplexArray & a) [related]
Definition at line 551 of file complexarray.hpp.
References QuantLib::ComplexArray::back(), QuantLib::ComplexArray::empty(), and QuantLib::ComplexArray::size().
{
        std::streamsize width = out.width();
        out << "[ ";
        if (!a.empty()) {
            for (Size n=0; n<a.size()-1; ++n)
                out << std::setw(width) << a[n] << "; ";
            out << std::setw(width) << a.back();
        }
        out << " ]";
        return out;
    }
std::ostream& QuantLib::operator<< (std::ostream & out, const Matrix & m) [related]
Definition at line 579 of file matrix.hpp.
References QuantLib::Matrix::columns(), and QuantLib::Matrix::rows().
{
        std::streamsize width = out.width();
        for (Size i=0; i<m.rows(); i++) {
            out << "| ";
            for (Size j=0; j<m.columns(); j++)
                out << std::setw(width) << m[i][j] << " ";
            out << "|\n";
        }
        return out;
    }
std::ostream& QuantLib::operator<< (std::ostream & out, const Array & a) [related]
Definition at line 629 of file array.hpp.
References QuantLib::Array::back(), QuantLib::Array::empty(), and QuantLib::Array::size().
{
        std::streamsize width = out.width();
        out << "[ ";
        if (!a.empty()) {
            for (Size n=0; n<a.size()-1; ++n)
                out << std::setw(width) << a[n] << "; ";
            out << std::setw(width) << a.back();
        }
        out << " ]";
        return out;
    }
bool QuantLib::operator<= (const Money & m1, const Money & m2) [related]
Definition at line 140 of file money.cpp.
References QuantLib::Money::AutomatedConversion, QuantLib::Money::BaseCurrencyConversion, QuantLib::Money::conversionType, QuantLib::anonymous_namespace{quantity.cpp}::convertTo(), QuantLib::anonymous_namespace{quantity.cpp}::convertToBase(), QuantLib::Money::currency(), QL_FAIL, and QuantLib::Money::value().
{
        if (m1.currency() == m2.currency()) {
            return m1.value() <= m2.value();
        } else if (Money::conversionType == Money::BaseCurrencyConversion) {
            Money tmp1 = m1;
            convertToBase(tmp1);
            Money tmp2 = m2;
            convertToBase(tmp2);
            return tmp1 <= tmp2;
        } else if (Money::conversionType == Money::AutomatedConversion) {
            Money tmp = m2;
            convertTo(tmp, m1.currency());
            return m1 <= tmp;
        } else {
            QL_FAIL("currency mismatch and no conversion specified");
        }
    }
bool QuantLib::operator<= (const Quantity & m1, const Quantity & m2) [related]
Definition at line 144 of file quantity.cpp.
References QuantLib::Quantity::amount(), QuantLib::Quantity::AutomatedConversion, QuantLib::Quantity::BaseUnitOfMeasureConversion, QuantLib::Quantity::conversionType, QuantLib::anonymous_namespace{quantity.cpp}::convertTo(), QuantLib::anonymous_namespace{quantity.cpp}::convertToBase(), QL_FAIL, and QuantLib::Quantity::unitOfMeasure().
{
        if (m1.unitOfMeasure() == m2.unitOfMeasure()) {
            return m1.amount() <= m2.amount();
        } else if (Quantity::conversionType
                   == Quantity::BaseUnitOfMeasureConversion) {
            Quantity tmp1 = m1;
            convertToBase(tmp1);
            Quantity tmp2 = m2;
            convertToBase(tmp2);
            return tmp1 <= tmp2;
        } else if (Quantity::conversionType == Quantity::AutomatedConversion) {
            Quantity tmp = m2;
            convertTo(tmp, m1.unitOfMeasure());
            return m1 <= tmp;
        } else {
            QL_FAIL("unitOfMeasure mismatch and no conversion specified");
        }
    }
bool QuantLib::operator<= (const Period & p1, const Period & p2) [related]
Definition at line 173 of file period.hpp.
{
        return !(p1 > p2);
    }
bool QuantLib::operator<= (const Date & d1, const Date & d2) [related]
Definition at line 312 of file date.hpp.
References QuantLib::Date::serialNumber().
{
        return (d1.serialNumber() <= d2.serialNumber());
    }
bool QuantLib::operator== (const DefaultType & lhs, const DefaultType & rhs)
Equality is the criteria for indexing the curves. This depends only on the atomic types and not on idiosincracies of derived type as mentioned in the functional documentation (specific event characteristics are relevant to credit event matching but not to the probability meaning). operator== is also used to remove duplicates in some containers. This ensures we do not have two equal events (despite having different characteristics) in those containers. This makes sense, theres no logic in having two FailureToPay in a contract even if they have different characteristics.
Definition at line 35 of file defaulttype.cpp.
References QuantLib::DefaultType::defaultType(), and QuantLib::DefaultType::restructuringType().
{
        return (lhs.defaultType() == rhs.defaultType()) &&
            (lhs.restructuringType() == rhs.restructuringType());
    }
bool QuantLib::operator== (const DefaultProbKey & lhs, const DefaultProbKey & rhs)
Definition at line 37 of file defaultprobabilitykey.cpp.
References QuantLib::DefaultProbKey::currency(), QuantLib::DefaultProbKey::eventTypes(), and QuantLib::DefaultProbKey::seniority().
{
        if(lhs.seniority() != rhs.seniority()) return false;
        if(lhs.currency() != rhs.currency()) return false;
        Size mySize = rhs.eventTypes().size();
        if(mySize != lhs.eventTypes().size()) return false;
        // the all types must be equal in the weak sense.
        for(Size i=0; i<mySize; i++) {
            if(std::find_if(lhs.eventTypes().begin(), lhs.eventTypes().end(),
                *_1 == *rhs.eventTypes()[i]) == lhs.eventTypes().end())
                return false;
        }// naah, I bet this can be done with a double lambda
        return true;
    }
bool QuantLib::operator== (const Loss & l1, const Loss & l2) [inline]
Definition at line 43 of file loss.hpp.
References QuantLib::Loss::time.
{
        return (l1.time == l2.time);
    }
bool QuantLib::operator== (const Region & r1, const Region & r2) [related]
Definition at line 104 of file region.hpp.
References QuantLib::Region::name().
{
        return r1.name() == r2.name();
    }
bool QuantLib::operator== (const Money & m1, const Money & m2) [related]
Definition at line 104 of file money.cpp.
References QuantLib::Money::AutomatedConversion, QuantLib::Money::BaseCurrencyConversion, QuantLib::Money::conversionType, QuantLib::anonymous_namespace{quantity.cpp}::convertTo(), QuantLib::anonymous_namespace{quantity.cpp}::convertToBase(), QuantLib::Money::currency(), QL_FAIL, and QuantLib::Money::value().
{
        if (m1.currency() == m2.currency()) {
            return m1.value() == m2.value();
        } else if (Money::conversionType == Money::BaseCurrencyConversion) {
            Money tmp1 = m1;
            convertToBase(tmp1);
            Money tmp2 = m2;
            convertToBase(tmp2);
            return tmp1 == tmp2;
        } else if (Money::conversionType == Money::AutomatedConversion) {
            Money tmp = m2;
            convertTo(tmp, m1.currency());
            return m1 == tmp;
        } else {
            QL_FAIL("currency mismatch and no conversion specified");
        }
    }
bool QuantLib::operator== (const Quantity & m1, const Quantity & m2) [related]
Definition at line 105 of file quantity.cpp.
References QuantLib::Quantity::amount(), QuantLib::Quantity::AutomatedConversion, QuantLib::Quantity::BaseUnitOfMeasureConversion, QuantLib::Quantity::conversionType, QuantLib::anonymous_namespace{quantity.cpp}::convertTo(), QuantLib::anonymous_namespace{quantity.cpp}::convertToBase(), QL_FAIL, and QuantLib::Quantity::unitOfMeasure().
{
        if (m1.unitOfMeasure() == m2.unitOfMeasure()) {
            return m1.amount() == m2.amount();
        } else if (Quantity::conversionType
                   == Quantity::BaseUnitOfMeasureConversion) {
            Quantity tmp1 = m1;
            convertToBase(tmp1);
            Quantity tmp2 = m2;
            convertToBase(tmp2);
            return tmp1 == tmp2;
        } else if (Quantity::conversionType
                   == Quantity::AutomatedConversion) {
            Quantity tmp = m2;
            convertTo(tmp, m1.unitOfMeasure());
            return m1 == tmp;
        } else {
            QL_FAIL("unitOfMeasure mismatch and no conversion specified");
        }
    }
bool QuantLib::operator== (const CommodityIndex & i1, const CommodityIndex & i2) [inline]
Definition at line 106 of file commodityindex.hpp.
References QuantLib::CommodityIndex::name().
{
        return i1.name() == i2.name();
    }
bool QuantLib::operator== (const CommodityType & c1, const CommodityType & c2) [related]
Definition at line 107 of file commoditytype.hpp.
References QuantLib::CommodityType::code().
{
        return c1.code() == c2.code();
    }
bool QuantLib::operator== (const CommodityCurve & c1, const CommodityCurve & c2) [inline]
Definition at line 109 of file commoditycurve.hpp.
References QuantLib::CommodityCurve::name().
{
        return c1.name() == c2.name();
    }
bool QuantLib::operator== (const PaymentTerm & c1, const PaymentTerm & c2) [related]
Definition at line 111 of file paymentterm.hpp.
References QuantLib::PaymentTerm::name().
{
        return c1.name() == c2.name();
    }
bool QuantLib::operator== (const UnitOfMeasure & c1, const UnitOfMeasure & c2) [related]
Definition at line 132 of file unitofmeasure.hpp.
References QuantLib::UnitOfMeasure::code().
{
        return c1.code() == c2.code();
    }
bool QuantLib::operator== (const DayCounter & d1, const DayCounter & d2) [related]
Definition at line 133 of file daycounter.hpp.
References QuantLib::DayCounter::empty(), and QuantLib::DayCounter::name().
{
        return (d1.empty() && d2.empty())
            || (!d1.empty() && !d2.empty() && d1.name() == d2.name());
    }
bool QuantLib::operator== (const DefaultEvent & lhs, const DefaultEvent & rhs)
Two credit events are the same independently of their settlement member data. This has the side effect of overwritting different settlements from the same credit event when, say, inserting in a map. But on the other hand one given event can only have one settlement. This means we can not have two restructuring events on a bond on the same date.
Definition at line 149 of file defaultevent.cpp.
References QuantLib::DefaultEvent::currency(), QuantLib::DefaultEvent::date(), QuantLib::DefaultEvent::defaultType(), and QuantLib::DefaultEvent::eventSeniority().
{
        return (lhs.currency() == rhs.currency()) &&
            (lhs.defaultType() == rhs.defaultType()) &&
            (lhs.date() == rhs.date()) &&
            (lhs.eventSeniority() == rhs.eventSeniority());
    }
bool QuantLib::operator== (const Currency & c1, const Currency & c2) [related]
Definition at line 155 of file currency.hpp.
References QuantLib::Currency::name().
{
        return c1.name() == c2.name();
    }
bool QuantLib::operator== (const Period & p1, const Period & p2) [related]
Definition at line 161 of file period.hpp.
{
        return !(p1 < p2 || p2 < p1);
    }
bool QuantLib::operator== (const Calendar & c1, const Calendar & c2) [related]
Definition at line 219 of file calendar.hpp.
References QuantLib::Calendar::empty(), and QuantLib::Calendar::name().
{
        return (c1.empty() && c2.empty())
            || (!c1.empty() && !c2.empty() && c1.name() == c2.name());
    }
bool QuantLib::operator== (const Date & d1, const Date & d2) [related]
Definition at line 300 of file date.hpp.
References QuantLib::Date::serialNumber().
{
        return (d1.serialNumber() == d2.serialNumber());
    }
bool QuantLib::operator> (const Loss & l1, const Loss & l2) [inline]
Definition at line 40 of file loss.hpp.
References QuantLib::Loss::time.
{
        return (l1.time > l2.time);
    }
bool QuantLib::operator> (const Period & p1, const Period & p2) [related]
Definition at line 169 of file period.hpp.
{
        return p2 < p1;
    }
bool QuantLib::operator> (const Quantity & m1, const Quantity & m2) [related]
Definition at line 203 of file quantity.hpp.
{
        return m2 < m1;
    }
bool QuantLib::operator> (const Money & m1, const Money & m2) [related]
Definition at line 207 of file money.hpp.
{
        return m2 < m1;
    }
bool QuantLib::operator> (const Date & d1, const Date & d2) [related]
Definition at line 316 of file date.hpp.
References QuantLib::Date::serialNumber().
{
        return (d1.serialNumber() > d2.serialNumber());
    }
bool QuantLib::operator>= (const Period & p1, const Period & p2) [related]
Definition at line 177 of file period.hpp.
{
        return !(p1 < p2);
    }
bool QuantLib::operator>= (const Quantity & m1, const Quantity & m2) [related]
Definition at line 207 of file quantity.hpp.
{
        return m2 <= m1;
    }
bool QuantLib::operator>= (const Money & m1, const Money & m2) [related]
Definition at line 211 of file money.hpp.
{
        return m2 <= m1;
    }
bool QuantLib::operator>= (const Date & d1, const Date & d2) [related]
Definition at line 320 of file date.hpp.
References QuantLib::Date::serialNumber().
{
        return (d1.serialNumber() >= d2.serialNumber());
    }
const Disposable<Matrix> QuantLib::outerProduct (const Array & v1, const Array & v2) [related]
Definition at line 549 of file matrix.hpp.
References QuantLib::Array::begin(), and QuantLib::Array::end().
Referenced by QuantLib::GenericSequenceStatistics< StatisticsType >::add(), and QuantLib::GenericSequenceStatistics< StatisticsType >::covariance().
{
        return outerProduct(v1.begin(), v1.end(), v2.begin(), v2.end());
    }
template<class Iterator1 , class Iterator2 > const Disposable<Matrix> QuantLib::outerProduct (Iterator1 v1begin, Iterator1 v1end, Iterator2 v2begin, Iterator2 v2end) [related]
Definition at line 555 of file matrix.hpp.
References QL_REQUIRE, and QuantLib::Matrix::row_begin().
{
        Size size1 = std::distance(v1begin, v1end);
        QL_REQUIRE(size1>0, "null first vector");
        Size size2 = std::distance(v2begin, v2end);
        QL_REQUIRE(size2>0, "null second vector");
        Matrix result(size1, size2);
        for (Size i=0; v1begin!=v1end; i++, v1begin++)
            std::transform(v2begin, v2end, result.row_begin(i),
                           std::bind1st(std::multiplies<Real>(), *v1begin));
        return result;
    }
pair<Real, Real> QuantLib::parallelAnalysis (const vector< Handle< SimpleQuote > > & quotes, const vector< shared_ptr< Instrument > > & instruments, const vector< Real > & quantities, Real shift, SensitivityAnalysis type, Real referenceNpv)
Definition at line 60 of file sensitivityanalysis.cpp.
References aggregateNPV(), Centered, OneSide, QL_FAIL, and QL_REQUIRE.
    {
        QL_REQUIRE(!quotes.empty(), "empty SimpleQuote vector");
        Size n = quotes.size();
        QL_REQUIRE(shift!=0.0, "zero shift not allowed");
        pair<Real, Real> result(0.0, 0.0);
        if (instruments.empty()) return result;
        if (referenceNpv==Null<Real>())
            referenceNpv = aggregateNPV(instruments, quantities);
        vector<Real> quoteValues(n, Null<Real>());
        for (Size i=0; i<n; ++i)
            if (quotes[i]->isValid())
                quoteValues[i] = quotes[i]->value();
        try {
            for (Size i=0; i<n; ++i)
                if (quotes[i]->isValid())
                    quotes[i]->setValue(quoteValues[i]+shift);
            Real npv = aggregateNPV(instruments, quantities);
            switch (type) {
              case OneSide:
                result.first = (npv-referenceNpv)/shift;
                result.second = Null<Real>();
                break;
              case Centered:
                {
                for (Size i=0; i<n; ++i)
                    if (quotes[i]->isValid())
                        quotes[i]->setValue(quoteValues[i]-shift);
                Real npv2 = aggregateNPV(instruments, quantities);
                result.first = (npv-npv2)/(2.0*shift);
                result.second = (npv-2.0*referenceNpv+npv2)/(shift*shift);
                }
                break;
              default:
                  QL_FAIL("unknown SensitivityAnalysis (" <<
                          Integer(type) << ")");
            }
            for (Size i=0; i<n; ++i)
                if (quotes[i]->isValid())
                    quotes[i]->setValue(quoteValues[i]);
        } catch (...) {
            for (Size i=0; i<n; ++i)
                if (quoteValues[i]!=Null<Real>())
                    quotes[i]->setValue(quoteValues[i]);
            throw;
        }
        return result;
    }
std::pair<Real, Real> QuantLib::parallelAnalysis (const std::vector< Handle< SimpleQuote > > & , const std::vector< boost::shared_ptr< Instrument > > & , const std::vector< Real > & quantities, Real shift = 0.0001, SensitivityAnalysis type = Centered, Real referenceNpv = Null< Real >())
parallel shift PV01 sensitivity analysis for a SimpleQuote vector
returns a pair of first and second derivative values calculated as prescribed by SensitivityAnalysis. Second derivative might not be available depending on SensitivityAnalysis value.
Empty quantities vector is considered as unit vector. The same if the vector is just one single element equal to one.
All SimpleQuotes are tweaked together in a parallel fashion.
std::pair<Real, Real> QuantLib::parallelAnalysis (const std::vector< std::vector< Handle< SimpleQuote > > > & , const std::vector< boost::shared_ptr< Instrument > > & , const std::vector< Real > & quantities, Real shift = 0.0001, SensitivityAnalysis type = Centered, Real referenceNpv = Null< Real >())
parallel shift PV01 sensitivity analysis for a SimpleQuote matrix
returns a pair of first and second derivative values calculated as prescribed by SensitivityAnalysis. Second derivative might not be available depending on SensitivityAnalysis value.
Empty quantities vector is considered as unit vector. The same if the vector is of size one.
All SimpleQuotes are tweaked together in a parallel fashion.
std::string QuantLib::payoffTypeToString (const boost::shared_ptr< Payoff > & h)
Definition at line 35 of file utilities.cpp.
References CHECK_DOWNCAST, and QL_FAIL.
{
        CHECK_DOWNCAST(PlainVanillaPayoff, "plain-vanilla");
        CHECK_DOWNCAST(CashOrNothingPayoff, "cash-or-nothing");
        CHECK_DOWNCAST(AssetOrNothingPayoff, "asset-or-nothing");
        CHECK_DOWNCAST(SuperSharePayoff, "super-share");
        CHECK_DOWNCAST(GapPayoff, "gap");
        QL_FAIL("unknown payoff type");
    }
Real QuantLib::PeizerPrattMethod2Inversion (Real z, BigNatural n) [inline]
Given an odd integer n and a real number z it returns p such that: 1 - CumulativeBinomialDistribution((n-1)/2, n, p) = CumulativeNormalDistribution(z)
Precondition:
n must be odd
Definition at line 135 of file binomialdistribution.hpp.
Referenced by QuantLib::ExtendedLeisenReimer::ExtendedLeisenReimer(), QuantLib::LeisenReimer::LeisenReimer(), QuantLib::ExtendedLeisenReimer::probability(), and QuantLib::ExtendedLeisenReimer::underlying().
{
        QL_REQUIRE(n%2==1,
                   "n must be an odd number: " << n << " not allowed");
        Real result = (z/(n+1.0/3.0+0.1/(n+1.0)));
        result *= result;
        result = std::exp(-result*(n+1.0/6.0));
        result = 0.5 + (z>0 ? 1 : -1) * std::sqrt((0.25 * (1.0-result)));
        return result;
    }
Disposable<Array> QuantLib::prod (const SparseMatrix & A, const Array & x) [inline]
Definition at line 47 of file sparsematrix.hpp.
References anonymous_namespace{marketmodel.cpp}::b, QuantLib::Array::size(), and anonymous_namespace{quantlibbenchmark.cpp}::t.
Referenced by QuantLib::FdmExtOUJumpOp::integro(), and MarketModelTest::testPathwiseMarketVegas().
{
        Array b(x.size());
        for (Size i=0; i < A.filled1()-1; ++i) {
            const Size begin = A.index1_data()[i];
            const Size end   = A.index1_data()[i+1];
            Real t=0;
            for (Size j=begin; j < end; ++j) {
                t += A.value_data()[j]*x[A.index2_data()[j]];
            }
            b[i]=t;
        }
        return b;
    }
const Disposable<Matrix> QuantLib::pseudoSqrt (const Matrix & matrix, SalvagingAlgorithm::Type sa) [related]
Definition at line 352 of file pseudosqrt.cpp.
References QuantLib::anonymous_namespace{pseudosqrt.cpp}::checkSymmetry(), CholeskyDecomposition(), QuantLib::Matrix::columns(), QuantLib::SalvagingAlgorithm::Higham, QuantLib::anonymous_namespace{pseudosqrt.cpp}::highamImplementation(), QuantLib::SalvagingAlgorithm::Hypersphere, QuantLib::anonymous_namespace{pseudosqrt.cpp}::hypersphereOptimize(), QuantLib::SalvagingAlgorithm::LowerDiagonal, QuantLib::SalvagingAlgorithm::None, QuantLib::anonymous_namespace{pseudosqrt.cpp}::normalizePseudoRoot(), QL_FAIL, QL_REQUIRE, QuantLib::Matrix::rows(), and QuantLib::SalvagingAlgorithm::Spectral.
Referenced by QuantLib::JointStochasticProcess::diffusion(), QuantLib::LfmHullWhiteParameterization::LfmHullWhiteParameterization(), QuantLib::JointStochasticProcess::stdDeviation(), MatricesTest::testHighamSqrt(), CovarianceTest::testRankReduction(), CovarianceTest::testSalvagingMatrix(), and MatricesTest::testSqrt().
{
        Size size = matrix.rows();
        #if defined(QL_EXTRA_SAFETY_CHECKS)
        checkSymmetry(matrix);
        #else
        QL_REQUIRE(size == matrix.columns(),
                   "non square matrix: " << size << " rows, " <<
                   matrix.columns() << " columns");
        #endif
        // spectral (a.k.a Principal Component) analysis
        SymmetricSchurDecomposition jd(matrix);
        Matrix diagonal(size, size, 0.0);
        // salvaging algorithm
        Matrix result(size, size);
        bool negative;
        switch (sa) {
          case SalvagingAlgorithm::None:
            // eigenvalues are sorted in decreasing order
            QL_REQUIRE(jd.eigenvalues()[size-1]>=-1e-16,
                       "negative eigenvalue(s) ("
                       << std::scientific << jd.eigenvalues()[size-1]
                       << ")");
            result = CholeskyDecomposition(matrix, true);
            break;
          case SalvagingAlgorithm::Spectral:
            // negative eigenvalues set to zero
            for (Size i=0; i<size; i++)
                diagonal[i][i] =
                    std::sqrt(std::max<Real>(jd.eigenvalues()[i], 0.0));
            result = jd.eigenvectors() * diagonal;
            normalizePseudoRoot(matrix, result);
            break;
          case SalvagingAlgorithm::Hypersphere:
            // negative eigenvalues set to zero
            negative=false;
            for (Size i=0; i<size; ++i){
                diagonal[i][i] =
                    std::sqrt(std::max<Real>(jd.eigenvalues()[i], 0.0));
                if (jd.eigenvalues()[i]<0.0) negative=true;
            }
            result = jd.eigenvectors() * diagonal;
            normalizePseudoRoot(matrix, result);
            if (negative)
                result = hypersphereOptimize(matrix, result, false);
            break;
          case SalvagingAlgorithm::LowerDiagonal:
            // negative eigenvalues set to zero
            negative=false;
            for (Size i=0; i<size; ++i){
                diagonal[i][i] =
                    std::sqrt(std::max<Real>(jd.eigenvalues()[i], 0.0));
                if (jd.eigenvalues()[i]<0.0) negative=true;
            }
            result = jd.eigenvectors() * diagonal;
            normalizePseudoRoot(matrix, result);
            if (negative)
                result = hypersphereOptimize(matrix, result, true);
            break;
          case SalvagingAlgorithm::Higham: {
              int maxIterations = 40;
              Real tol = 1e-6;
              result = highamImplementation(matrix, maxIterations, tol);
              result = CholeskyDecomposition(result, true);
            }
            break;
          default:
            QL_FAIL("unknown salvaging algorithm");
        }
        return result;
    }
Disposable< std::vector< Size > > QuantLib::qrDecomposition (const Matrix & A, Matrix & q, Matrix & r, bool pivot = true)
QR decompoisition.
This implementation is based on MINPACK (<http://www.netlib.org/minpack>, <http://www.netlib.org/cephes/linalg.tgz>)
This subroutine uses householder transformations with column pivoting (optional) to compute a qr factorization of the m by n matrix A. That is, qrfac determines an orthogonal matrix q, a permutation matrix p, and an upper trapezoidal matrix r with diagonal elements of nonincreasing magnitude, such that A*p = q*r.
Return value ipvt is an integer array of length n, which defines the permutation matrix p such that A*p = q*r. Column j of p is column ipvt(j) of the identity matrix.
See lmdiff.cpp for further details.
Definition at line 29 of file qrdecomposition.cpp.
References QuantLib::Matrix::begin(), QuantLib::Array::begin(), QuantLib::Matrix::column_begin(), QuantLib::Matrix::column_end(), QuantLib::Matrix::columns(), QuantLib::Array::end(), QuantLib::dsd::inner_product(), QuantLib::MINPACK::qrfac(), QuantLib::Matrix::row_begin(), QuantLib::Matrix::row_end(), QuantLib::Matrix::rows(), anonymous_namespace{quantlibbenchmark.cpp}::t, and transpose().
Referenced by qrSolve(), and MatricesTest::testQRDecomposition().
{
        Matrix mT = transpose(M);
        const Size m = M.rows();
        const Size n = M.columns();
        boost::scoped_array<int> lipvt(new int[n]);
        boost::scoped_array<double> rdiag(new double[n]);
        boost::scoped_array<double> wa(new double[n]);
        MINPACK::qrfac(m, n, mT.begin(), 0, (pivot)?1:0,
                       lipvt.get(), n, rdiag.get(), rdiag.get(), wa.get());
        if (r.columns() != n || r.rows() !=n)
            r = Matrix(n, n);
        for (Size i=0; i < n; ++i) {
            std::fill(r.row_begin(i), r.row_begin(i)+i, 0.0);
            r[i][i] = rdiag[i];
            if (i < m) {
                std::copy(mT.column_begin(i)+i+1, mT.column_end(i),
                          r.row_begin(i)+i+1);
            }
            else {
                std::fill(r.row_begin(i)+i+1, r.row_end(i), 0.0);
            }
        }
        if (q.rows() != m || q.columns() != n)
            q = Matrix(m, n);
        Array w(m);
        for (Size k=0; k < m; ++k) {
            std::fill(w.begin(), w.end(), 0.0);
            w[k] = 1.0;
            for (Size j=0; j < std::min(n, m); ++j) {
                const Real t3 = mT[j][j];
                if (t3 != 0.0) {
                    const Real t
                        = std::inner_product(mT.row_begin(j)+j, mT.row_end(j),
                                             w.begin()+j, 0.0)/t3;
                    for (Size i=j; i<m; ++i) {
                        w[i]-=mT[j][i]*t;
                    }
                }
                q[k][j] = w[j];
            }
            std::fill(q.row_begin(k) + std::min(n, m), q.row_end(k), 0.0);
        }
        std::vector<Size> ipvt(n);
        if (pivot) {
            std::copy(lipvt.get(), lipvt.get()+n, ipvt.begin());
        }
        else {
            for (Size i=0; i < n; ++i)
                ipvt[i] = i;
        }
        return ipvt;
    }
Disposable< Array > QuantLib::qrSolve (const Matrix & a, const Array & b, bool pivot = true, const Array & d = Array())
QR Solve.
This implementation is based on MINPACK (<http://www.netlib.org/minpack>, <http://www.netlib.org/cephes/linalg.tgz>)
Given an m by n matrix A, an n by n diagonal matrix d, and an m-vector b, the problem is to determine an x which solves the system
A*x = b , d*x = 0 ,
in the least squares sense.
d is an input array of length n which must contain the diagonal elements of the matrix d.
See lmdiff.cpp for further details.
Definition at line 93 of file qrdecomposition.cpp.
References anonymous_namespace{marketmodel.cpp}::b, QuantLib::Matrix::begin(), QuantLib::Array::begin(), QuantLib::Matrix::columns(), QuantLib::Array::empty(), QuantLib::Array::end(), QL_REQUIRE, qrDecomposition(), QuantLib::MINPACK::qrsolv(), QuantLib::Matrix::rows(), QuantLib::Array::size(), and transpose().
Referenced by MatricesTest::testQRSolve(), QuantLib::detail::KernelInterpolationImpl< I1, I2, Kernel >::updateAlphaVec(), and QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::updateAlphaVec().
{
        const Size m = a.rows();
        const Size n = a.columns();
        QL_REQUIRE(b.size() == m, "dimensions of A and b don't match");
        QL_REQUIRE(d.size() == n || d.empty(),
                   "dimensions of A and d don't match");
        Matrix q(m, n), r(n, n);
        std::vector<Size> lipvt = qrDecomposition(a, q, r, pivot);
        boost::scoped_array<int> ipvt(new int[n]);
        std::copy(lipvt.begin(), lipvt.end(), ipvt.get());
        Matrix aT = transpose(a);
        Matrix rT = transpose(r);
        boost::scoped_array<double> sdiag(new double[n]);
        boost::scoped_array<double> wa(new double[n]);
        Array ld(n, 0.0);
        if (!d.empty()) {
            std::copy(d.begin(), d.end(), ld.begin());
        }
        Array x(n);
        Array qtb = transpose(q)*b;
        MINPACK::qrsolv(n, rT.begin(), n, ipvt.get(),
                        ld.begin(), qtb.begin(),
                        x.begin(), sdiag.get(), wa.get());
        return x;
    }
const Disposable<Matrix> QuantLib::rankReducedSqrt (const Matrix & matrix, Size maxRank, Real componentRetainedPercentage, SalvagingAlgorithm::Type sa) [related]
Definition at line 433 of file pseudosqrt.cpp.
References QuantLib::Array::begin(), QuantLib::anonymous_namespace{pseudosqrt.cpp}::checkSymmetry(), QuantLib::Matrix::columns(), QuantLib::SymmetricSchurDecomposition::eigenvalues(), QuantLib::SymmetricSchurDecomposition::eigenvectors(), QuantLib::Array::end(), QuantLib::SalvagingAlgorithm::Higham, QuantLib::anonymous_namespace{pseudosqrt.cpp}::highamImplementation(), QuantLib::SalvagingAlgorithm::None, QuantLib::anonymous_namespace{pseudosqrt.cpp}::normalizePseudoRoot(), QL_FAIL, QL_REQUIRE, QuantLib::Matrix::rows(), QuantLib::SalvagingAlgorithm::Spectral, and anonymous_namespace{gaussianquadratures.cpp}::tolerance.
Referenced by QuantLib::AbcdVol::AbcdVol(), QuantLib::CTSMMCapletOriginalCalibration::calibrationFunction(), QuantLib::CTSMMCapletAlphaFormCalibration::capletAlphaFormCalibration(), QuantLib::CTSMMCapletMaxHomogeneityCalibration::capletMaxHomogeneityCalibration(), QuantLib::JointStochasticProcess::evolve(), QuantLib::FlatVol::FlatVol(), QuantLib::LmLinearExponentialCorrelationModel::generateArguments(), and CovarianceTest::testRankReduction().
{
        Size size = matrix.rows();
        #if defined(QL_EXTRA_SAFETY_CHECKS)
        checkSymmetry(matrix);
        #else
        QL_REQUIRE(size == matrix.columns(),
                   "non square matrix: " << size << " rows, " <<
                   matrix.columns() << " columns");
        #endif
        QL_REQUIRE(componentRetainedPercentage>0.0,
                   "no eigenvalues retained");
        QL_REQUIRE(componentRetainedPercentage<=1.0,
                   "percentage to be retained > 100%");
        QL_REQUIRE(maxRank>=1,
                   "max rank required < 1");
        // spectral (a.k.a Principal Component) analysis
        SymmetricSchurDecomposition jd(matrix);
        Array eigenValues = jd.eigenvalues();
        // salvaging algorithm
        switch (sa) {
          case SalvagingAlgorithm::None:
            // eigenvalues are sorted in decreasing order
            QL_REQUIRE(eigenValues[size-1]>=-1e-16,
                       "negative eigenvalue(s) ("
                       << std::scientific << eigenValues[size-1]
                       << ")");
            break;
          case SalvagingAlgorithm::Spectral:
            // negative eigenvalues set to zero
            for (Size i=0; i<size; ++i)
                eigenValues[i] = std::max<Real>(eigenValues[i], 0.0);
            break;
          case SalvagingAlgorithm::Higham:
              {
                  int maxIterations = 40;
                  Real tolerance = 1e-6;
                  Matrix adjustedMatrix = highamImplementation(matrix, maxIterations, tolerance);
                  jd = SymmetricSchurDecomposition(adjustedMatrix);
                  eigenValues = jd.eigenvalues();
              }
              break;
          default:
            QL_FAIL("unknown or invalid salvaging algorithm");
        }
        // factor reduction
        Real enough = componentRetainedPercentage *
                      std::accumulate(eigenValues.begin(),
                                      eigenValues.end(), 0.0);
        if (componentRetainedPercentage == 1.0) {
            // numerical glitches might cause some factors to be discarded
            enough *= 1.1;
        }
        // retain at least one factor
        Real components = eigenValues[0];
        Size retainedFactors = 1;
        for (Size i=1; components<enough && i<size; ++i) {
            components += eigenValues[i];
            retainedFactors++;
        }
        // output is granted to have a rank<=maxRank
        retainedFactors=std::min(retainedFactors, maxRank);
        Matrix diagonal(size, retainedFactors, 0.0);
        for (Size i=0; i<retainedFactors; ++i)
            diagonal[i][i] = std::sqrt(eigenValues[i]);
        Matrix result = jd.eigenvectors() * diagonal;
        normalizePseudoRoot(matrix, result);
        return result;
    }
std::vector< Spread > QuantLib::rateInstVolDifferences (const MarketModel & marketModel1, const MarketModel & marketModel2, Size index)
Definition at line 55 of file marketmodeldifferences.cpp.
References QuantLib::MarketModel::covariance(), QuantLib::anonymous_namespace{yieldtermstructure.cpp}::dt, QuantLib::MarketModel::evolution(), QuantLib::EvolutionDescription::evolutionTimes(), QuantLib::MarketModel::initialRates(), and QL_ENSURE.
{
        QL_ENSURE(marketModel1.initialRates() == marketModel2.initialRates(),
                  "initialRates do not match");
        const EvolutionDescription& evolutionDescription1
                                           = marketModel1.evolution();
        const EvolutionDescription& evolutionDescription2
                                           = marketModel2.evolution();
        QL_ENSURE(evolutionDescription1.evolutionTimes()
                  == evolutionDescription2.evolutionTimes(),
                  "Evolution times do not match");
        QL_ENSURE(index<evolutionDescription1.numberOfSteps(),
            "the index given is greater than the number of steps");
        const std::vector<Time>& evolutionTimes
            = evolutionDescription1.evolutionTimes();
        std::vector<Spread> result(evolutionTimes.size());
        Time previousEvolutionTime = 0;
        for (Size i=0; i<evolutionTimes.size(); ++i) {
            Time currentEvolutionTime = evolutionTimes[i];
            Time dt = currentEvolutionTime - previousEvolutionTime;
            const Matrix& covariance1 = marketModel1.covariance(i);
            const Matrix& covariance2 = marketModel2.covariance(i);
            Real diff = covariance1[index][index] - covariance2[index][index];
            result[i] = std::sqrt(diff/dt);
            previousEvolutionTime = currentEvolutionTime;
        }
        return result;
    }
std::vector< Volatility > QuantLib::rateVolDifferences (const MarketModel & marketModel1, const MarketModel & marketModel2)
Definition at line 27 of file marketmodeldifferences.cpp.
References QuantLib::MarketModel::evolution(), QuantLib::EvolutionDescription::evolutionTimes(), QuantLib::MarketModel::initialRates(), QuantLib::MarketModel::numberOfSteps(), QL_ENSURE, and QuantLib::MarketModel::totalCovariance().
{
        QL_ENSURE(marketModel1.initialRates() == marketModel2.initialRates(),
                  "initialRates do not match");
        const EvolutionDescription& evolutionDescription1
                                           = marketModel1.evolution();
        const EvolutionDescription& evolutionDescription2
                                           = marketModel2.evolution();
        QL_ENSURE(evolutionDescription1.evolutionTimes()
                  == evolutionDescription2.evolutionTimes(),
                  "Evolution times do not match");
        const Matrix& totalCovariance1
            = marketModel1.totalCovariance(marketModel1.numberOfSteps()-1);
        const Matrix& totalCovariance2
            = marketModel2.totalCovariance(marketModel2.numberOfSteps()-1);
        const std::vector<Time>& maturities =
            evolutionDescription1.evolutionTimes();
        std::vector<Volatility> result(totalCovariance1.columns());
        for (Size i=0; i<totalCovariance1.columns(); ++i) {
            Real diff = totalCovariance1[i][i]-totalCovariance2[i][i];
            result[i] = std::sqrt(diff/maturities[i]);
        }
        return result;
    }
Real QuantLib::relativeError (Real x1, Real x2, Real reference)
Definition at line 115 of file utilities.cpp.
Referenced by AsianOptionTest::testAnalyticContinuousGeometricAveragePriceGreeks(), AsianOptionTest::testAnalyticDiscreteGeometricAveragePriceGreeks(), CapFloorTest::testATMRate(), BasketOptionTest::testBarraquandThreeValues(), DigitalOptionTest::testCashAtHitOrNothingAmericanGreeks(), anonymous_namespace{extendedtrees.cpp}::testEngineConsistency(), anonymous_namespace{europeanoption.cpp}::testEngineConsistency(), DividendOptionTest::testEuropeanGreeks(), BasketOptionTest::testEuroTwoValues(), anonymous_namespace{americanoption.cpp}::testFdGreeks(), anonymous_namespace{dividendoption.cpp}::testFdGreeks(), QuantoOptionTest::testForwardGreeks(), anonymous_namespace{forwardoption.cpp}::testForwardGreeks(), MargrabeOptionTest::testGreeks(), EuropeanOptionTest::testGreeks(), QuantoOptionTest::testGreeks(), EuropeanOptionTest::testImpliedVol(), BasketOptionTest::testOddSamples(), BasketOptionTest::testOneDAmericanValues(), anonymous_namespace{cliquetoption.cpp}::testOptionGreeks(), and BasketOptionTest::testTavellaValues().
{
        if (reference != 0.0)
            return std::fabs(x1-x2)/reference;
        else
            // fall back to absolute error
            return std::fabs(x1-x2);
    }
static Real QuantLib::rescaleError (Real err, const Real resultAbs, const Real resultAsc) [static]
Definition at line 25 of file kronrodintegral.cpp.
References QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow(), QL_EPSILON, and QL_MIN_POSITIVE_REAL.
Referenced by QuantLib::GaussKronrodNonAdaptive::integrate().
{
        err = std::fabs(err) ;
        if (resultAsc != 0 && err != 0){
            Real scale = std::pow((200 * err / resultAsc), 1.5) ;
            if (scale < 1)
                err = resultAsc * scale ;
            else
                err = resultAsc ;
            }
        if (resultAbs > QL_MIN_POSITIVE_REAL / (50 * QL_EPSILON )){
            Real min_err = 50 * QL_EPSILON  * resultAbs ;
            if (min_err > err)
                err = min_err ;
            }
        return err ;
    }
Real QuantLib::sabrVolatility (Rate strike, Rate forward, Time expiryTime, Real alpha, Real beta, Real nu, Real rho)
Definition at line 83 of file sabr.cpp.
References QL_REQUIRE, QuantLib::io::rate(), unsafeSabrVolatility(), and validateSabrParameters().
Referenced by InterpolationTest::testSabrInterpolation(), and QuantLib::detail::SABRInterpolationImpl< I1, I2 >::value().
{
        QL_REQUIRE(strike>0.0, "strike must be positive: "
                               << io::rate(strike) << " not allowed");
        QL_REQUIRE(forward>0.0, "at the money forward rate must be "
                   "positive: " << io::rate(forward) << " not allowed");
        QL_REQUIRE(expiryTime>=0.0, "expiry time must be non-negative: "
                                   << expiryTime << " not allowed");
        validateSabrParameters(alpha, beta, nu, rho);
        return unsafeSabrVolatility(strike, forward, expiryTime,
                                    alpha, beta, nu, rho);
    }
void QuantLib::setCouponPricer (const Leg & leg, const boost::shared_ptr< FloatingRateCouponPricer > & pricer)
Definition at line 230 of file couponpricer.cpp.
Referenced by anonymous_namespace{capflooredcoupon.cpp}::CommonVars::makeCapFlooredLeg(), QuantLib::MakeCms::operator boost::shared_ptr< Swap >(), QuantLib::IborLeg::operator Leg(), QuantLib::RiskyFloatingBond::RiskyFloatingBond(), ConvertibleBondTest::testBond(), BondTest::testCachedFloating(), CmsTest::testCmsSwap(), AssetSwapTest::testGenericBondImplied(), AssetSwapTest::testImpliedValue(), SwapTest::testInArrears(), AssetSwapTest::testMarketASWSpread(), AssetSwapTest::testMASWWithGenericBond(), AssetSwapTest::testSpecializedBondVsGenericBond(), AssetSwapTest::testSpecializedBondVsGenericBondUsingAsw(), AssetSwapTest::testZSpread(), and AssetSwapTest::testZSpreadWithGenericBond().
{
        PricerSetter setter(pricer);
        for (Size i=0; i<leg.size(); ++i) {
            leg[i]->accept(setter);
        }
    }
void QuantLib::setCouponPricers (const Leg & leg, const std::vector< boost::shared_ptr< FloatingRateCouponPricer > > & pricers)
Definition at line 239 of file couponpricer.cpp.
References QL_REQUIRE.
{
        Size nCashFlows = leg.size();
        QL_REQUIRE(nCashFlows>0, "no cashflows");
        Size nPricers = pricers.size();
        QL_REQUIRE(nCashFlows >= nPricers,
                   "mismatch between leg size (" << nCashFlows <<
                   ") and number of pricers (" << nPricers << ")");
        for (Size i=0; i<nCashFlows; ++i) {
            PricerSetter setter(i<nPricers ? pricers[i] : pricers[nPricers-1]);
            leg[i]->accept(setter);
        }
    }
std::vector< Real > QuantLib::sphereCylinderOptimizerClosest (Real r, Real s, Real alpha, Real z1, Real z2, Real z3, Natural maxIterations, Real tolerance, Real zweight)
Definition at line 194 of file spherecylinder.cpp.
References QuantLib::SphereCylinderOptimizer::findByProjection(), QuantLib::SphereCylinderOptimizer::findClosest(), QuantLib::SphereCylinderOptimizer::isIntersectionNonEmpty(), and QL_REQUIRE.
    {
        SphereCylinderOptimizer optimizer(r, s, alpha, z1, z2, z3, zweight);
        std::vector<Real> y(3);
        QL_REQUIRE(optimizer.isIntersectionNonEmpty(),
                   "intersection empty so no solution");
        if (maxIterations ==0)
            optimizer.findByProjection(y[0], y[1], y[2]);
        else
            optimizer.findClosest(maxIterations, tolerance, y[0], y[1], y[2]);
        return y;
     }
const Disposable<Array> QuantLib::Sqrt (const Array & v) [related]
Definition at line 604 of file array.hpp.
References QuantLib::Array::begin(), QuantLib::Array::end(), and QuantLib::Array::size().
Referenced by QuantLib::GeneralLinearLeastSquares::calculate(), QuantLib::JointStochasticProcess::covariance(), QuantLib::JointStochasticProcess::evolve(), QuantLib::FdmHestonEquityPart::FdmHestonEquityPart(), QuantLib::FdmHestonHullWhiteEquityPart::FdmHestonHullWhiteEquityPart(), and LiborMarketModelTest::testCapletPricing().
{
        Array result(v.size());
        std::transform(v.begin(),v.end(),result.begin(),
                       std::ptr_fun<Real,Real>(std::sqrt));
        return result;
    }
template<class T > void QuantLib::swap (Clone< T > & t, Clone< T > & u) [related]
Definition at line 112 of file clone.hpp.
References QuantLib::Clone< T >::swap().
{
        t.swap(u);
    }
void QuantLib::swap (TridiagonalOperator & L1, TridiagonalOperator & L2) [inline]
Definition at line 253 of file tridiagonaloperator.hpp.
References QuantLib::TridiagonalOperator::swap().
{
        L1.swap(L2);
    }
void QuantLib::swap (SampledCurve & c1, SampledCurve & c2) [inline]
Definition at line 221 of file sampledcurve.hpp.
References QuantLib::SampledCurve::swap().
{
        c1.swap(c2);
    }
void QuantLib::swap (ComplexArray & v, ComplexArray & w) [related]
Definition at line 547 of file complexarray.hpp.
References QuantLib::ComplexArray::swap().
Referenced by QuantLib::LfmSwaptionEngine::calculate(), QuantLib::BjerksundStenslandApproximationEngine::calculate(), QuantLib::G2SwaptionEngine::calculate(), QuantLib::BlackSwaptionEngine::calculate(), QuantLib::TreeVanillaSwapEngine::calculate(), QuantLib::CapHelper::CapHelper(), QuantLib::SabrInterpolatedSmileSection::createInterpolation(), QuantLib::Disposable< T >::Disposable(), QuantLib::GFunctionFactory::GFunctionExactYield::GFunctionExactYield(), QuantLib::GFunctionFactory::GFunctionWithShifts::GFunctionWithShifts(), historicalForwardRatesAnalysis(), historicalRatesAnalysis(), QuantLib::HaganPricer::initialize(), anonymous_namespace{swap.cpp}::CommonVars::makeSwap(), anonymous_namespace{bermudanswaption.cpp}::CommonVars::makeSwap(), QuantLib::MakeCms::operator boost::shared_ptr< Swap >(), QuantLib::MakeVanillaSwap::operator boost::shared_ptr< VanillaSwap >(), QuantLib::MakeCms::operator Swap(), QuantLib::MakeVanillaSwap::operator VanillaSwap(), QuantLib::Disposable< T >::operator=(), QuantLib::AdaptedPathPayoff::ValuationData::setExerciseData(), QuantLib::SVD::SVD(), CapFloorTest::testATMRate(), anonymous_namespace{piecewiseyieldcurve.cpp}::testBMACurveConsistency(), OvernightIndexedSwapTest::testBootstrap(), CdsOptionTest::testCached(), OvernightIndexedSwapTest::testCachedValue(), SwaptionTest::testCachedValue(), SwapTest::testCachedValue(), anonymous_namespace{piecewiseyieldcurve.cpp}::testCurveConsistency(), SwapTest::testFairRate(), OvernightIndexedSwapTest::testFairRate(), SwapTest::testFairSpread(), OvernightIndexedSwapTest::testFairSpread(), SwaptionTest::testImpliedVolatility(), SwapTest::testInArrears(), InflationCapFlooredCouponTest::testInstrumentEquality(), PiecewiseYieldCurveTest::testJpyLibor(), PiecewiseYieldCurveTest::testLiborFixing(), InflationCapFloorTest::testParity(), CapFloorTest::testParity(), SwapTest::testRateDependency(), SwaptionTest::testSpreadDependency(), SwapTest::testSpreadDependency(), SwaptionTest::testSpreadTreatment(), SwaptionTest::testStrikeDependency(), ShortRateModelTest::testSwaps(), and SwaptionTest::testVega().
{
        v.swap(w);
    }
void QuantLib::swap (Matrix & m1, Matrix & m2) [related]
Definition at line 575 of file matrix.hpp.
References QuantLib::Matrix::swap().
{
        m1.swap(m2);
    }
void QuantLib::swap (Array & v, Array & w) [related]
Definition at line 625 of file array.hpp.
References QuantLib::Array::swap().
{
        v.swap(w);
    }
std::vector< Size > QuantLib::terminalMeasure (const EvolutionDescription & evolution)
Terminal measure: the last bond is used as numeraire.
Definition at line 162 of file evolutiondescription.cpp.
References QuantLib::EvolutionDescription::evolutionTimes(), and QuantLib::EvolutionDescription::rateTimes().
Referenced by anonymous_namespace{marketmodel_smm.cpp}::makeMeasure(), anonymous_namespace{marketmodel_cms.cpp}::makeMeasure(), anonymous_namespace{marketmodel_smmcapletcalibration.cpp}::makeMeasure(), anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::makeMeasure(), anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::makeMeasure(), anonymous_namespace{marketmodel.cpp}::makeMeasure(), and QuantLib::MarketModelComposite::suggestedNumeraires().
    {
        return std::vector<Size>(evolution.evolutionTimes().size(),
                                 evolution.rateTimes().size()-1);
    }
const Disposable<Matrix> QuantLib::transpose (const Matrix & m) [related]
Definition at line 539 of file matrix.hpp.
References QuantLib::Matrix::columns(), QuantLib::Matrix::empty(), QuantLib::Matrix::row_begin(), QuantLib::Matrix::row_end(), and QuantLib::Matrix::rows().
Referenced by addCoterminalSwapsAndSwaptions(), QuantLib::CTSMMCapletOriginalCalibration::calibrationFunction(), QuantLib::CMSMMDriftCalculator::CMSMMDriftCalculator(), QuantLib::StochasticProcessArray::correlation(), QuantLib::CotSwapFromFwdCorrelation::CotSwapFromFwdCorrelation(), QuantLib::G2Process::covariance(), QuantLib::StochasticProcessArray::covariance(), QuantLib::MarketModel::covariance(), QuantLib::LfmCovarianceParameterization::covariance(), QuantLib::EulerDiscretization::covariance(), QuantLib::EndEulerDiscretization::covariance(), QuantLib::G2ForwardProcess::covariance(), QuantLib::SwaptionVolCube1::Cube::Cube(), QuantLib::JointStochasticProcess::evolve(), QuantLib::LmLinearExponentialCorrelationModel::generateArguments(), QuantLib::LeastSquareFunction::gradient(), QuantLib::anonymous_namespace{pseudosqrt.cpp}::hypersphereOptimize(), QuantLib::LfmHullWhiteParameterization::LfmHullWhiteParameterization(), QuantLib::LMMDriftCalculator::LMMDriftCalculator(), QuantLib::LMMNormalDriftCalculator::LMMNormalDriftCalculator(), anonymous_namespace{libormarketmodelprocess.cpp}::makeProcess(), QuantLib::anonymous_namespace{pseudosqrt.cpp}::projectToPositiveSemidefiniteMatrix(), qrDecomposition(), qrSolve(), QuantLib::anonymous_namespace{capletcoterminalmaxhomogeneity.cpp}::singleRateClosestPointFinder(), QuantLib::SMMDriftCalculator::SMMDriftCalculator(), QuantLib::SVD::solveFor(), QuantLib::SVD::SVD(), MatricesTest::testEigenvectors(), MarketModelSmmCapletCalibrationTest::testFunction(), MarketModelSmmCapletHomoCalibrationTest::testFunction(), MarketModelSmmCapletAlphaCalibrationTest::testFunction(), MatricesTest::testQRDecomposition(), MatricesTest::testQRSolve(), CovarianceTest::testRankReduction(), CovarianceTest::testSalvagingMatrix(), LiborMarketModelTest::testSimpleCovarianceModels(), MatricesTest::testSqrt(), MatricesTest::testSVD(), QuantLib::detail::CubicInterpolationImpl< I1, I2 >::update(), QuantLib::SwaptionVolCube1::Cube::updateInterpolators(), QuantLib::anonymous_namespace{pseudosqrt.cpp}::HypersphereCostFunction::value(), QuantLib::LeastSquareFunction::valueAndGradient(), and QuantLib::FrobeniusCostFunction::values().
{
        Matrix result(m.columns(),m.rows());
        #if defined(QL_PATCH_MSVC) && defined(QL_DEBUG)
        if (!m.empty())
        #endif
        for (Size i=0; i<m.rows(); i++)
            std::copy(m.row_begin(i),m.row_end(i),result.column_begin(i));
        return result;
    }
Disposable< Matrix > QuantLib::triangularAnglesParametrization (const Array & angles, Size matrixSize, Size rank)
Returns the Triangular Angles Parametrized correlation matrix.
The matrix \(m \) is filled with values corresponding to angles given in the \(angles \) vector. See equation (24) in "Parameterizing correlations: a geometric interpretation" by Francesco Rapisarda, Damiano Brigo, Fabio Mercurio
Test:
the correctness of the results is tested by reproducing known good data.
the correctness of the results is tested by checking returned values against numerical calculations.
Definition at line 25 of file tapcorrelations.cpp.
References QL_REQUIRE, and QuantLib::Array::size().
Referenced by triangularAnglesParametrizationUnconstrained().
{
        // what if rank == 1?
        QL_REQUIRE((rank-1) * (2*matrixSize - rank) == 2*angles.size(),
                    "rank-1) * (matrixSize - rank/2) == angles.size()");
        Matrix m(matrixSize, matrixSize);
        // first row filling
        m[0][0] = 1.0;
        for (Size j=1; j<matrixSize; ++j)
            m[0][j] = 0.0;
        // next ones...
        Size k = 0; //angles index
        for (Size i=1; i<m.rows(); ++i) {
            Real sinProduct = 1.0;
            Size bound = std::min(i,rank-1);
            for (Size j=0; j<bound; ++j) {
                m[i][j] = std::cos(angles[k]);
                m[i][j] *= sinProduct;
                sinProduct *= std::sin(angles[k]);
                ++k;
            }
            m[i][bound] = sinProduct;
            for (Size j=bound+1; j<m.rows(); ++j)
                m[i][j] = 0;
        }
        return m;
    }
Disposable< Matrix > QuantLib::triangularAnglesParametrizationRankThree (Real alpha, Real t0, Real epsilon, Size nbRows)
Returns the rank reduced Triangular Angles Parametrized correlation matrix.
The matrix \(m \) is filled with values corresponding to angles corresponding to the 3D spherical spiral paramterized by \(alpha \), \(t0 \), \(epsilon \) values. See equation (32) in "Parameterizing correlations: a geometric interpretation" by Francesco Rapisarda, Damiano Brigo, Fabio Mercurio
Test:
the correctness of the results is tested by reproducing known good data.
the correctness of the results is tested by checking returned values against numerical calculations.
Definition at line 104 of file tapcorrelations.cpp.
References QuantLib::anonymous_namespace{bjerksundstenslandengine.cpp}::phi(), QuantLib::Matrix::rows(), and anonymous_namespace{quantlibbenchmark.cpp}::t.
Referenced by triangularAnglesParametrizationRankThreeVectorial().
{
        Matrix m(matrixSize, 3);
        for (Size i=0; i<m.rows(); ++i) {
            Real t = t0 * (1 - std::exp(epsilon*Real(i)));
            Real phi = std::atan(alpha * t);
            m[i][0] = std::cos(t)*std::cos(phi);
            m[i][1] = std::sin(t)*std::cos(phi);
            m[i][2] = -std::sin(phi);
        }
        return m;
    }
Disposable< Matrix > QuantLib::triangularAnglesParametrizationRankThreeVectorial (const Array & parameters, Size nbRows)
Definition at line 118 of file tapcorrelations.cpp.
References QL_REQUIRE, QuantLib::Array::size(), and triangularAnglesParametrizationRankThree().
{
        QL_REQUIRE(parameters.size() == 3,
                   "the parameter array must contain exactly 3 values" );
        return triangularAnglesParametrizationRankThree(parameters[0],
                                                        parameters[1],
                                                        parameters[2],
                                                        nbRows);
    }
Disposable< Matrix > QuantLib::triangularAnglesParametrizationUnconstrained (const Array & x, Size matrixSize, Size rank)
Definition at line 82 of file tapcorrelations.cpp.
References M_PI, QuantLib::Array::size(), and triangularAnglesParametrization().
{
        Array angles(x.size());
        //we convert the unconstrained parameters in angles
        for (Size i = 0; i < x.size(); ++i)
            angles[i] = M_PI*.5 - std::atan(x[i]);
        return triangularAnglesParametrization(angles, matrixSize, rank);
    }
Real QuantLib::unsafeSabrVolatility (Rate strike, Rate forward, Time expiryTime, Real alpha, Real beta, Real nu, Real rho)
Definition at line 29 of file sabr.cpp.
References anonymous_namespace{marketmodel.cpp}::beta, close(), anonymous_namespace{marketmodel.cpp}::d, QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow(), and QL_EPSILON.
Referenced by sabrVolatility(), QuantLib::SabrSmileSection::varianceImpl(), and QuantLib::SabrSmileSection::volatilityImpl().
{
        const Real oneMinusBeta = 1.0-beta;
        const Real A = std::pow(forward*strike, oneMinusBeta);
        const Real sqrtA= std::sqrt(A);
        Real logM;
        if (!close(forward, strike))
            logM = std::log(forward/strike);
        else {
            const Real epsilon = (forward-strike)/strike;
            logM = epsilon - .5 * epsilon * epsilon ;
        }
        const Real z = (nu/alpha)*sqrtA*logM;
        const Real B = 1.0-2.0*rho*z+z*z;
        const Real C = oneMinusBeta*oneMinusBeta*logM*logM;
        const Real tmp = (std::sqrt(B)+z-rho)/(1.0-rho);
        const Real xx = std::log(tmp);
        const Real D = sqrtA*(1.0+C/24.0+C*C/1920.0);
        const Real d = 1.0 + expiryTime *
            (oneMinusBeta*oneMinusBeta*alpha*alpha/(24.0*A)
                                + 0.25*rho*beta*nu*alpha/sqrtA
                                    +(2.0-3.0*rho*rho)*(nu*nu/24.0));
        Real multiplier;
        // computations become precise enough if the square of z worth
        // slightly more than the precision machine (hence the m)
        static const Real m = 10;
        if (std::fabs(z*z)>QL_EPSILON * m)
            multiplier = z/xx;
        else {
            multiplier = 1.0 - 0.5*rho*z - (3.0*rho*rho-2.0)*z*z/12.0;
        }
        return (alpha/D)*multiplier*d;
    }
void QuantLib::validateAbcdParameters (Real a, Real , Real c, Real d) [inline]
Definition at line 30 of file abcd.hpp.
References QL_REQUIRE.
Referenced by QuantLib::detail::AbcdCoeffHolder::AbcdCoeffHolder(), QuantLib::AbcdFunction::AbcdFunction(), and QuantLib::AbcdCalibration::compute().
{
        QL_REQUIRE(a+d>=0,
                   "a (" << a << ") + d (" << d << ") must be non negative");
        QL_REQUIRE(c>=0,
                   "c (" << c << ") must be non negative");
        QL_REQUIRE(d>=0,
                   "d (" << d << ") must be non negative");
    }
void QuantLib::validateSabrParameters (Real alpha, Real beta, Real nu, Real rho)
Definition at line 69 of file sabr.cpp.
References QL_REQUIRE.
Referenced by QuantLib::detail::SABRCoeffHolder::SABRCoeffHolder(), QuantLib::SabrSmileSection::SabrSmileSection(), and sabrVolatility().
{
        QL_REQUIRE(alpha>0.0, "alpha must be positive: "
                              << alpha << " not allowed");
        QL_REQUIRE(beta>=0.0 && beta<=1.0, "beta must be in (0.0, 1.0): "
                                         << beta << " not allowed");
        QL_REQUIRE(nu>=0.0, "nu must be non negative: "
                            << nu << " not allowed");
        QL_REQUIRE(rho*rho<1.0, "rho square must be less than one: "
                                << rho << " not allowed");
    }
Real QuantLib::weeks (const Period & p) [related]
Definition at line 309 of file period.cpp.
References Days, QuantLib::Period::length(), Months, QL_FAIL, QuantLib::Period::units(), Weeks, and Years.
{
        if (p.length()==0) return 0.0;
        switch (p.units()) {
          case Days:
              return p.length()/7.0;
          case Weeks:
              return p.length();
          case Months:
            QL_FAIL("cannot convert Months into Weeks");
          case Years:
            QL_FAIL("cannot convert Years into Weeks");
          default:
            QL_FAIL("unknown time unit (" << Integer(p.units()) << ")");
        }
    }
Real QuantLib::years (const Period & p) [related]
Definition at line 275 of file period.cpp.
References Days, QuantLib::Period::length(), Months, QL_FAIL, QuantLib::Period::units(), Weeks, and Years.
Referenced by anonymous_namespace{swaptionvolatilitymatrix.cpp}::CommonVars::makeCoherenceTest(), anonymous_namespace{americanoption.cpp}::testFdGreeks(), and QuantLib::KInterpolatedYoYOptionletVolatilitySurface< Interpolator1D >::volatilityImpl().
{
        if (p.length()==0) return 0.0;
        switch (p.units()) {
          case Days:
            QL_FAIL("cannot convert Days into Years");
          case Weeks:
            QL_FAIL("cannot convert Weeks into Years");
          case Months:
              return p.length()/12.0;
          case Years:
              return p.length();
          default:
            QL_FAIL("unknown time unit (" << Integer(p.units()) << ")");
        }
    }
Variable Documentation
const Real QuantLib::g7w[] [static]
Initial value:
 { 0.417959183673469,
                                0.381830050505119,
                                0.279705391489277,
                                0.129484966168870 }
Definition at line 357 of file kronrodintegral.cpp.
Referenced by QuantLib::GaussKronrodAdaptive::integrateRecursively().
const Real QuantLib::k15t[] [static]
Initial value:
 { 0.000000000000000,
                                 0.207784955007898,
                                 0.405845151377397,
                                 0.586087235467691,
                                 0.741531185599394,
                                 0.864864423359769,
                                 0.949107912342758,
                                 0.991455371120813 }
Definition at line 372 of file kronrodintegral.cpp.
Referenced by QuantLib::GaussKronrodAdaptive::integrateRecursively().
const Real QuantLib::k15w[] [static]
Initial value:
 { 0.209482141084728,
                                 0.204432940075298,
                                 0.190350578064785,
                                 0.169004726639267,
                                 0.140653259715525,
                                 0.104790010322250,
                                 0.063092092629979,
                                 0.022935322010529 }
Definition at line 362 of file kronrodintegral.cpp.
Referenced by QuantLib::GaussKronrodAdaptive::integrateRecursively().
std::set<Date> QuantLib::knownDateSet [static]
Definition at line 31 of file ecb.cpp.
Referenced by QuantLib::ECB::addDate(), QuantLib::ECB::knownDates(), and QuantLib::ECB::removeDate().
const Real QuantLib::w10[5] [static]
Initial value:
 {
        0.066671344308688137593568809893332,
        0.149451349150580593145776339657697,
        0.219086362515982043995534934228163,
        0.269266719309996355091226921569469,
        0.295524224714752870173892994651338
        }
Definition at line 59 of file kronrodintegral.cpp.
Referenced by QuantLib::GaussKronrodNonAdaptive::integrate().
const Real QuantLib::w21a[5] [static]
Initial value:
 {
        0.032558162307964727478818972459390,
        0.075039674810919952767043140916190,
        0.109387158802297641899210590325805,
        0.134709217311473325928054001771707,
        0.147739104901338491374841515972068
        }
Definition at line 77 of file kronrodintegral.cpp.
Referenced by QuantLib::GaussKronrodNonAdaptive::integrate().
const Real QuantLib::w21b[6] [static]
Initial value:
 {
        0.011694638867371874278064396062192,
        0.054755896574351996031381300244580,
        0.093125454583697605535065465083366,
        0.123491976262065851077958109831074,
        0.142775938577060080797094273138717,
        0.149445554002916905664936468389821
        }
Definition at line 86 of file kronrodintegral.cpp.
Referenced by QuantLib::GaussKronrodNonAdaptive::integrate().
const Real QuantLib::w43a[10] [static]
Initial value:
 {
        0.016296734289666564924281974617663,
        0.037522876120869501461613795898115,
        0.054694902058255442147212685465005,
        0.067355414609478086075553166302174,
        0.073870199632393953432140695251367,
        0.005768556059769796184184327908655,
        0.027371890593248842081276069289151,
        0.046560826910428830743339154433824,
        0.061744995201442564496240336030883,
        0.071387267268693397768559114425516
        }
Definition at line 111 of file kronrodintegral.cpp.
Referenced by QuantLib::GaussKronrodNonAdaptive::integrate().
const Real QuantLib::w43b[12] [static]
Initial value:
 {
        0.001844477640212414100389106552965,
        0.010798689585891651740465406741293,
        0.021895363867795428102523123075149,
        0.032597463975345689443882222526137,
        0.042163137935191811847627924327955,
        0.050741939600184577780189020092084,
        0.058379395542619248375475369330206,
        0.064746404951445885544689259517511,
        0.069566197912356484528633315038405,
        0.072824441471833208150939535192842,
        0.074507751014175118273571813842889,
        0.074722147517403005594425168280423
        }
Definition at line 125 of file kronrodintegral.cpp.
Referenced by QuantLib::GaussKronrodNonAdaptive::integrate().
const Real QuantLib::w87a[21] [static]
Initial value:
 {
        0.008148377384149172900002878448190,
        0.018761438201562822243935059003794,
        0.027347451050052286161582829741283,
        0.033677707311637930046581056957588,
        0.036935099820427907614589586742499,
        0.002884872430211530501334156248695,
        0.013685946022712701888950035273128,
        0.023280413502888311123409291030404,
        0.030872497611713358675466394126442,
        0.035693633639418770719351355457044,
        0.000915283345202241360843392549948,
        0.005399280219300471367738743391053,
        0.010947679601118931134327826856808,
        0.016298731696787335262665703223280,
        0.021081568889203835112433060188190,
        0.025370969769253827243467999831710,
        0.029189697756475752501446154084920,
        0.032373202467202789685788194889595,
        0.034783098950365142750781997949596,
        0.036412220731351787562801163687577,
        0.037253875503047708539592001191226
        }
Definition at line 167 of file kronrodintegral.cpp.
Referenced by QuantLib::GaussKronrodNonAdaptive::integrate().
const Real QuantLib::w87b[23] [static]
Initial value:
 {
        0.000274145563762072350016527092881,
        0.001807124155057942948341311753254,
        0.004096869282759164864458070683480,
        0.006758290051847378699816577897424,
        0.009549957672201646536053581325377,
        0.012329447652244853694626639963780,
        0.015010447346388952376697286041943,
        0.017548967986243191099665352925900,
        0.019938037786440888202278192730714,
        0.022194935961012286796332102959499,
        0.024339147126000805470360647041454,
        0.026374505414839207241503786552615,
        0.028286910788771200659968002987960,
        0.030052581128092695322521110347341,
        0.031646751371439929404586051078883,
        0.033050413419978503290785944862689,
        0.034255099704226061787082821046821,
        0.035262412660156681033782717998428,
        0.036076989622888701185500318003895,
        0.036698604498456094498018047441094,
        0.037120549269832576114119958413599,
        0.037334228751935040321235449094698,
        0.037361073762679023410321241766599
        }
Definition at line 192 of file kronrodintegral.cpp.
Referenced by QuantLib::GaussKronrodNonAdaptive::integrate().
const Real QuantLib::x1[5] [static]
Initial value:
 {
        0.973906528517171720077964012084452,
        0.865063366688984510732096688423493,
        0.679409568299024406234327365114874,
        0.433395394129247190799265943165784,
        0.148874338981631210884826001129720
        }
Definition at line 50 of file kronrodintegral.cpp.
Referenced by QuantLib::AnalyticBarrierEngine::A(), QuantLib::AnalyticGJRGARCHEngine::calculate(), QuantLib::SphereCylinderOptimizer::findClosest(), QuantLib::GaussKronrodNonAdaptive::integrate(), QuantLib::Interpolation::templateImpl< I1, I2 >::isInRange(), QuantLib::Interpolation2D::templateImpl< I1, I2, M >::isInRange(), QuantLib::SymmetricSchurDecomposition::jacobiRotate_(), QuantLib::BoxMullerGaussianRng< RNG >::next(), and QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::value().
const Real QuantLib::x2[5] [static]
Initial value:
 {
        0.995657163025808080735527280689003,
        0.930157491355708226001207180059508,
        0.780817726586416897063717578345042,
        0.562757134668604683339000099272694,
        0.294392862701460198131126603103866
        }
Definition at line 68 of file kronrodintegral.cpp.
Referenced by QuantLib::AnalyticBarrierEngine::B(), QuantLib::AnalyticBarrierEngine::E(), QuantLib::SphereCylinderOptimizer::findClosest(), QuantLib::GaussKronrodNonAdaptive::integrate(), QuantLib::Interpolation::templateImpl< I1, I2 >::isInRange(), QuantLib::Interpolation2D::templateImpl< I1, I2, M >::isInRange(), QuantLib::SymmetricSchurDecomposition::jacobiRotate_(), QuantLib::BoxMullerGaussianRng< RNG >::next(), QuantLib::SphereCylinderOptimizer::objectiveFunction(), QuantLib::NonCentralChiSquareDistribution::operator()(), InterpolationTest::testAsFunctor(), and QuantLib::detail::KernelInterpolation2DImpl< I1, I2, M, Kernel >::value().
const Real QuantLib::x3[11] [static]
Initial value:
 {
        0.999333360901932081394099323919911,
        0.987433402908088869795961478381209,
        0.954807934814266299257919200290473,
        0.900148695748328293625099494069092,
        0.825198314983114150847066732588520,
        0.732148388989304982612354848755461,
        0.622847970537725238641159120344323,
        0.499479574071056499952214885499755,
        0.364901661346580768043989548502644,
        0.222254919776601296498260928066212,
        0.074650617461383322043914435796506
        }
Definition at line 96 of file kronrodintegral.cpp.
Referenced by QuantLib::SphereCylinderOptimizer::findClosest(), QuantLib::GaussKronrodNonAdaptive::integrate(), and QuantLib::SphereCylinderOptimizer::objectiveFunction().
const Real QuantLib::x4[22] [static]
Initial value:
 {
        0.999902977262729234490529830591582,
        0.997989895986678745427496322365960,
        0.992175497860687222808523352251425,
        0.981358163572712773571916941623894,
        0.965057623858384619128284110607926,
        0.943167613133670596816416634507426,
        0.915806414685507209591826430720050,
        0.883221657771316501372117548744163,
        0.845710748462415666605902011504855,
        0.803557658035230982788739474980964,
        0.757005730685495558328942793432020,
        0.706273209787321819824094274740840,
        0.651589466501177922534422205016736,
        0.593223374057961088875273770349144,
        0.531493605970831932285268948562671,
        0.466763623042022844871966781659270,
        0.399424847859218804732101665817923,
        0.329874877106188288265053371824597,
        0.258503559202161551802280975429025,
        0.185695396568346652015917141167606,
        0.111842213179907468172398359241362,
        0.037352123394619870814998165437704
        }
Definition at line 141 of file kronrodintegral.cpp.
Referenced by QuantLib::GaussKronrodNonAdaptive::integrate().