QuantLib: anonymous_namespace{fdmlinearop.cpp} Namespace Reference
anonymous_namespace{fdmlinearop.cpp} Namespace Reference
Classes
class FdmHestonExpressCondition
class ExpressPayoff
struct multiplies
Functions
boost::shared_ptr
< HybridHestonHullWhiteProcess > createHestonHullWhite (Time maturity)
FdmSolverDesc createSolverDesc (const std::vector< Size > &dim, const boost::shared_ptr< HybridHestonHullWhiteProcess > &process)
Disposable< Array > axpy (const boost::numeric::ublas::compressed_matrix< Real > &A, const Array &x)
Function Documentation
Disposable<Array> anonymous_namespace{fdmlinearop.cpp}::axpy (const boost::numeric::ublas::compressed_matrix< Real > & A, const Array & x)
Definition at line 1065 of file fdmlinearop.cpp.
References QuantLib::Array::begin(), QuantLib::Array::end(), and QuantLib::Array::size().
Referenced by FdmLinearOpTest::testBiCGstab().
{
        boost::numeric::ublas::vector<Real> tmpX(x.size()), y(x.size());
        std::copy(x.begin(), x.end(), tmpX.begin());
        boost::numeric::ublas::axpy_prod(A, tmpX, y);
        Array retVal(y.begin(), y.end());
        return retVal;
    }
boost::shared_ptr<HybridHestonHullWhiteProcess> anonymous_namespace{fdmlinearop.cpp}::createHestonHullWhite (Time maturity)
Definition at line 856 of file fdmlinearop.cpp.
References anonymous_namespace{marketmodel.cpp}::dates, QuantLib::Settings::evaluationDate(), QuantLib::Singleton< Settings >::instance(), and QuantLib::Years.
Referenced by FdmLinearOpTest::testFdmHestonHullWhiteOp().
                       {
        DayCounter dc = Actual365Fixed();
        const Date today = Settings::instance().evaluationDate();
        Handle<Quote> s0(boost::shared_ptr<Quote>(new SimpleQuote(100.0)));
        std::vector<Date> dates;
        std::vector<Rate> rates, divRates;
        for (Size i=0; i <= 25; ++i) {
            dates.push_back(today+Period(i, Years));
            rates.push_back(0.05);
            divRates.push_back(0.02);
        }
        const Handle<YieldTermStructure> rTS(
           boost::shared_ptr<YieldTermStructure>(new ZeroCurve(dates, rates, dc)));
        const Handle<YieldTermStructure> qTS(
           boost::shared_ptr<YieldTermStructure>(
                                              new ZeroCurve(dates, divRates, dc)));
        const Real v0 = 0.04;
        boost::shared_ptr<HestonProcess> hestonProcess(
            new HestonProcess(rTS, qTS, s0, v0, 1.0, v0*0.75, 0.4, -0.7));
        boost::shared_ptr<HullWhiteForwardProcess> hwFwdProcess(
                            new HullWhiteForwardProcess(rTS, 0.00883, 0.01));
        hwFwdProcess->setForwardMeasureTime(maturity);
        const Real equityShortRateCorr = -0.7;
        return boost::shared_ptr<HybridHestonHullWhiteProcess>(
                new HybridHestonHullWhiteProcess(hestonProcess, hwFwdProcess,
                                                 equityShortRateCorr));
    }
FdmSolverDesc anonymous_namespace{fdmlinearop.cpp}::createSolverDesc (const std::vector< Size > & dim, const boost::shared_ptr< HybridHestonHullWhiteProcess > & process)
Definition at line 893 of file fdmlinearop.cpp.
References QuantLib::Option::Call.
Referenced by FdmLinearOpTest::testFdmHestonHullWhiteOp().
{
        const Time maturity
                    = process->hullWhiteProcess()->getForwardMeasureTime();
        boost::shared_ptr<FdmLinearOpLayout> layout(new FdmLinearOpLayout(dim));
        std::vector<boost::shared_ptr<Fdm1dMesher> > mesher1d;
        mesher1d.push_back(boost::shared_ptr<Fdm1dMesher>(
                new Uniform1dMesher(std::log(22.0), std::log(440.0), dim[0])));
        mesher1d.push_back(boost::shared_ptr<Fdm1dMesher>(
                new FdmHestonVarianceMesher(dim[1], process->hestonProcess(),
                                            maturity)));
        mesher1d.push_back(boost::shared_ptr<Fdm1dMesher>(
                new Uniform1dMesher(-0.15, 0.15, dim[2])));
        boost::shared_ptr<FdmMesher> mesher(
                                     new FdmMesherComposite(layout, mesher1d));
        const FdmBoundaryConditionSet boundaries;
        std::list<std::vector<Time> > stoppingTimes;
        std::list<boost::shared_ptr<StepCondition<Array> > > stepConditions;
        boost::shared_ptr<FdmStepConditionComposite> conditions(
            new FdmStepConditionComposite(
                                     std::list<std::vector<Time> >(),
                                     FdmStepConditionComposite::Conditions()));
        boost::shared_ptr<StrikedTypePayoff> payoff(
                                  new PlainVanillaPayoff(Option::Call, 160.0));
        boost::shared_ptr<FdmInnerValueCalculator> calculator(
                                       new FdmLogInnerValue(payoff, mesher, 0));
        const Size tGrid = 100;
        const Size dampingSteps = 0;
        FdmSolverDesc desc = { mesher, boundaries,
                               conditions, calculator,
                               maturity, tGrid, dampingSteps };
        return desc;
    }