QuantLib: QuantLib::detail Namespace Reference
QuantLib::detail Namespace Reference
Classes
class simple_event
class Polynomial2DSplineImpl
class ImpliedVolatilityHelper
helper class for one-asset implied-volatility calculation
class AbcdCoeffHolder
class AbcdInterpolationImpl
class BackwardFlatInterpolationImpl
class BicubicSplineDerivatives
class BicubicSplineImpl
class BilinearInterpolationImpl
class SectionHelper
class ConvexMonotoneImpl
class ComboHelper
class EverywhereConstantHelper
class ConvexMonotone2Helper
class ConvexMonotone3Helper
class ConvexMonotone4Helper
class ConvexMonotone4MinHelper
class ConstantGradHelper
class QuadraticHelper
class QuadraticMinHelper
class CoefficientHolder
class CubicInterpolationImpl
class ForwardFlatInterpolationImpl
class KernelInterpolationImpl
class KernelInterpolation2DImpl
class LinearInterpolationImpl
class LogInterpolationImpl
class MixedInterpolationImpl
struct EmptyArg
struct EmptyRes
struct EmptyDim
struct DataTable
struct DataTable< Real >
struct Data
struct Data< std::vector< Real >, EmptyArg >
struct Point
struct Point< Real, EmptyArg >
struct Point< Real, EmptyRes >
struct Point< Size, EmptyDim >
struct Point< base_data_table, EmptyRes >
class base_cubic_spline
class n_cubic_spline
class base_cubic_splint
class n_cubic_splint
struct Int2Type
struct Int2Type< 2 >
struct Int2Type< 3 >
struct Int2Type< 4 >
struct Int2Type< 5 >
struct Int2Type< 6 >
struct Int2Type< 7 >
struct Int2Type< 8 >
struct Int2Type< 9 >
struct Int2Type< 10 >
struct Int2Type< 11 >
struct Int2Type< 12 >
struct Int2Type< 13 >
struct Int2Type< 14 >
struct Int2Type< 15 >
class SABRCoeffHolder
class SABRInterpolationImpl
class HullWhiteCapFloorPricer
class Integrand
class DividendAdder
class BootstrapHelperSorter
struct short_date_holder
struct long_date_holder
struct iso_date_holder
struct long_period_holder
struct short_period_holder
struct long_weekday_holder
struct short_weekday_holder
struct shortest_weekday_holder
struct null_checker
struct ordinal_holder
struct power_of_two_holder
struct percent_holder
struct sequence_holder
struct FloatingPointNull< true >
struct FloatingPointNull< false >
class Tracing
class quantlib_test_case
Typedefs
typedef std::vector
< std::vector< Real > > SplineGrid
typedef DataTable< Real > base_data_table
typedef Data< std::vector
< Real >, EmptyArg > base_data
typedef Point< Real, EmptyArg > base_arg_type
typedef Point< Real, EmptyRes > base_return_type
typedef Point< Size, EmptyDim > base_dimensions
typedef Point< base_data_table,
EmptyRes > base_output_data
typedef base_cubic_spline cubic_spline_01
typedef n_cubic_spline
< cubic_spline_01 > cubic_spline_02
typedef n_cubic_spline
< cubic_spline_02 > cubic_spline_03
typedef n_cubic_spline
< cubic_spline_03 > cubic_spline_04
typedef n_cubic_spline
< cubic_spline_04 > cubic_spline_05
typedef n_cubic_spline
< cubic_spline_05 > cubic_spline_06
typedef n_cubic_spline
< cubic_spline_06 > cubic_spline_07
typedef n_cubic_spline
< cubic_spline_07 > cubic_spline_08
typedef n_cubic_spline
< cubic_spline_08 > cubic_spline_09
typedef n_cubic_spline
< cubic_spline_09 > cubic_spline_10
typedef n_cubic_spline
< cubic_spline_10 > cubic_spline_11
typedef n_cubic_spline
< cubic_spline_11 > cubic_spline_12
typedef n_cubic_spline
< cubic_spline_12 > cubic_spline_13
typedef n_cubic_spline
< cubic_spline_13 > cubic_spline_14
typedef n_cubic_spline
< cubic_spline_14 > cubic_spline_15
typedef base_cubic_splint cubic_splint_01
typedef n_cubic_splint
< cubic_splint_01 > cubic_splint_02
typedef n_cubic_splint
< cubic_splint_02 > cubic_splint_03
typedef n_cubic_splint
< cubic_splint_03 > cubic_splint_04
typedef n_cubic_splint
< cubic_splint_04 > cubic_splint_05
typedef n_cubic_splint
< cubic_splint_05 > cubic_splint_06
typedef n_cubic_splint
< cubic_splint_06 > cubic_splint_07
typedef n_cubic_splint
< cubic_splint_07 > cubic_splint_08
typedef n_cubic_splint
< cubic_splint_08 > cubic_splint_09
typedef n_cubic_splint
< cubic_splint_09 > cubic_splint_10
typedef n_cubic_splint
< cubic_splint_10 > cubic_splint_11
typedef n_cubic_splint
< cubic_splint_11 > cubic_splint_12
typedef n_cubic_splint
< cubic_splint_12 > cubic_splint_13
typedef n_cubic_splint
< cubic_splint_13 > cubic_splint_14
typedef n_cubic_splint
< cubic_splint_14 > cubic_splint_15
Functions
Rate effectiveFixedRate (const std::vector< Spread > &spreads, const std::vector< Rate > &caps, const std::vector< Rate > &floors, Size i)
bool noOption (const std::vector< Rate > &caps, const std::vector< Rate > &floors, Size i)
template<typename ForwardIterator >
std::vector< std::complex< Real > > double_ft (ForwardIterator begin, ForwardIterator end)
template<typename InputIterator , typename OutputIterator >
Real remove_mean (InputIterator begin, InputIterator end, OutputIterator out)
template<class I >
void _fill_array_ (Array &a, boost::scoped_array< Real > &data_, Size &n_, I begin, I end, const boost::true_type &)
template<class I >
void _fill_array_ (Array &a, boost::scoped_array< Real > &data_, Size &n_, I begin, I end, const boost::false_type &)
std::ostream & operator<< (std::ostream &out, const short_date_holder &holder)
std::ostream & operator<< (std::ostream &out, const long_date_holder &holder)
std::ostream & operator<< (std::ostream &out, const iso_date_holder &holder)
std::ostream & operator<< (std::ostream &out, const long_period_holder &holder)
std::ostream & operator<< (std::ostream &out, const short_period_holder &holder)
std::ostream & operator<< (std::ostream &out, const long_weekday_holder &holder)
std::ostream & operator<< (std::ostream &out, const short_weekday_holder &holder)
std::ostream & operator<< (std::ostream &out, const shortest_weekday_holder &holder)
std::ostream & operator<< (std::ostream &out, const ordinal_holder &holder)
std::ostream & operator<< (std::ostream &out, const percent_holder &holder)
template<typename T >
std::ostream & operator<< (std::ostream &, const null_checker< T > &)
template<typename T >
std::ostream & operator<< (std::ostream &, const power_of_two_holder< T > &)
template<typename I >
std::ostream & operator<< (std::ostream &, const sequence_holder< I > &)
template<class T , class U >
T get (const std::vector< T > &v, Size i, U defaultValue)
Variables
const Real avgHazardRate = 0.01
const Real maxHazardRate = 1.0
const Rate avgInflation = 0.02
const Rate maxInflation = 0.5
const Real avgRate = 0.05
const Real maxRate = 1.0
Typedef Documentation
typedef Point<Real, EmptyArg> QuantLib::detail::base_arg_type
Definition at line 168 of file multicubicspline.hpp.
typedef Data<std::vector<Real>, EmptyArg> QuantLib::detail::base_data
Definition at line 120 of file multicubicspline.hpp.
typedef DataTable<Real> QuantLib::detail::base_data_table
Definition at line 85 of file multicubicspline.hpp.
typedef Point<Size, EmptyDim> QuantLib::detail::base_dimensions
Definition at line 210 of file multicubicspline.hpp.
typedef Point<base_data_table, EmptyRes> QuantLib::detail::base_output_data
Definition at line 226 of file multicubicspline.hpp.
typedef Point<Real, EmptyRes> QuantLib::detail::base_return_type
Definition at line 189 of file multicubicspline.hpp.
typedef base_cubic_spline QuantLib::detail::cubic_spline_01
Definition at line 340 of file multicubicspline.hpp.
typedef n_cubic_spline<cubic_spline_01> QuantLib::detail::cubic_spline_02
Definition at line 341 of file multicubicspline.hpp.
typedef n_cubic_spline<cubic_spline_02> QuantLib::detail::cubic_spline_03
Definition at line 342 of file multicubicspline.hpp.
typedef n_cubic_spline<cubic_spline_03> QuantLib::detail::cubic_spline_04
Definition at line 343 of file multicubicspline.hpp.
typedef n_cubic_spline<cubic_spline_04> QuantLib::detail::cubic_spline_05
Definition at line 344 of file multicubicspline.hpp.
typedef n_cubic_spline<cubic_spline_05> QuantLib::detail::cubic_spline_06
Definition at line 345 of file multicubicspline.hpp.
typedef n_cubic_spline<cubic_spline_06> QuantLib::detail::cubic_spline_07
Definition at line 346 of file multicubicspline.hpp.
typedef n_cubic_spline<cubic_spline_07> QuantLib::detail::cubic_spline_08
Definition at line 347 of file multicubicspline.hpp.
typedef n_cubic_spline<cubic_spline_08> QuantLib::detail::cubic_spline_09
Definition at line 348 of file multicubicspline.hpp.
typedef n_cubic_spline<cubic_spline_09> QuantLib::detail::cubic_spline_10
Definition at line 349 of file multicubicspline.hpp.
typedef n_cubic_spline<cubic_spline_10> QuantLib::detail::cubic_spline_11
Definition at line 350 of file multicubicspline.hpp.
typedef n_cubic_spline<cubic_spline_11> QuantLib::detail::cubic_spline_12
Definition at line 351 of file multicubicspline.hpp.
typedef n_cubic_spline<cubic_spline_12> QuantLib::detail::cubic_spline_13
Definition at line 352 of file multicubicspline.hpp.
typedef n_cubic_spline<cubic_spline_13> QuantLib::detail::cubic_spline_14
Definition at line 353 of file multicubicspline.hpp.
typedef n_cubic_spline<cubic_spline_14> QuantLib::detail::cubic_spline_15
Definition at line 354 of file multicubicspline.hpp.
typedef base_cubic_splint QuantLib::detail::cubic_splint_01
Definition at line 356 of file multicubicspline.hpp.
typedef n_cubic_splint<cubic_splint_01> QuantLib::detail::cubic_splint_02
Definition at line 357 of file multicubicspline.hpp.
typedef n_cubic_splint<cubic_splint_02> QuantLib::detail::cubic_splint_03
Definition at line 358 of file multicubicspline.hpp.
typedef n_cubic_splint<cubic_splint_03> QuantLib::detail::cubic_splint_04
Definition at line 359 of file multicubicspline.hpp.
typedef n_cubic_splint<cubic_splint_04> QuantLib::detail::cubic_splint_05
Definition at line 360 of file multicubicspline.hpp.
typedef n_cubic_splint<cubic_splint_05> QuantLib::detail::cubic_splint_06
Definition at line 361 of file multicubicspline.hpp.
typedef n_cubic_splint<cubic_splint_06> QuantLib::detail::cubic_splint_07
Definition at line 362 of file multicubicspline.hpp.
typedef n_cubic_splint<cubic_splint_07> QuantLib::detail::cubic_splint_08
Definition at line 363 of file multicubicspline.hpp.
typedef n_cubic_splint<cubic_splint_08> QuantLib::detail::cubic_splint_09
Definition at line 364 of file multicubicspline.hpp.
typedef n_cubic_splint<cubic_splint_09> QuantLib::detail::cubic_splint_10
Definition at line 365 of file multicubicspline.hpp.
typedef n_cubic_splint<cubic_splint_10> QuantLib::detail::cubic_splint_11
Definition at line 366 of file multicubicspline.hpp.
typedef n_cubic_splint<cubic_splint_11> QuantLib::detail::cubic_splint_12
Definition at line 367 of file multicubicspline.hpp.
typedef n_cubic_splint<cubic_splint_12> QuantLib::detail::cubic_splint_13
Definition at line 368 of file multicubicspline.hpp.
typedef n_cubic_splint<cubic_splint_13> QuantLib::detail::cubic_splint_14
Definition at line 369 of file multicubicspline.hpp.
typedef n_cubic_splint<cubic_splint_14> QuantLib::detail::cubic_splint_15
Definition at line 370 of file multicubicspline.hpp.
typedef std::vector<std::vector<Real> > QuantLib::detail::SplineGrid
Definition at line 38 of file multicubicspline.hpp.
Function Documentation
template<class I > void QuantLib::detail::_fill_array_ (Array & a, boost::scoped_array< Real > & data_, Size & n_, I begin, I end, const boost::true_type &) [inline]
Definition at line 238 of file array.hpp.
References QuantLib::Array::begin(), and QuantLib::Array::end().
Referenced by QuantLib::Array::Array().
{
            // we got redirected here from a call like Array(3, 4)
            // because it matched the constructor below exactly with
            // ForwardIterator = int.  What we wanted was fill an
            // Array with a given value, which we do here.
            Size n = begin;
            Real value = end;
            data_.reset(n ? new Real[n] : (Real*)(0));
            n_ = n;
            std::fill(a.begin(),a.end(),value);
        }
template<class I > void QuantLib::detail::_fill_array_ (Array & a, boost::scoped_array< Real > & data_, Size & n_, I begin, I end, const boost::false_type &) [inline]
Definition at line 255 of file array.hpp.
References QuantLib::Array::begin().
{
            // true iterators
            Size n = std::distance(begin, end);
            data_.reset(n ? new Real[n] : (Real*)(0));
            n_ = n;
            #if defined(QL_PATCH_MSVC) && defined(QL_DEBUG)
            if (n_)
            #endif
            std::copy(begin, end, a.begin());
        }
template<typename ForwardIterator > std::vector<std::complex<Real> > QuantLib::detail::double_ft (ForwardIterator begin, ForwardIterator end)
Definition at line 39 of file autocovariance.hpp.
References QuantLib::Array::begin(), QuantLib::Array::end(), QuantLib::FastFourierTransform::min_order(), QuantLib::FastFourierTransform::output_size(), and QuantLib::FastFourierTransform::transform().
Referenced by QuantLib::autocorrelations(), QuantLib::autocovariances(), and QuantLib::convolutions().
{
            std::size_t nData = std::distance(begin, end);
            std::size_t order = FastFourierTransform::min_order(nData) + 1;
            FastFourierTransform fft(order);
            std::vector<std::complex<Real> > ft(fft.output_size());
            fft.transform(begin, end, ft.begin());
            Array tmp(ft.size(), 0.0);
            std::transform(ft.begin(), ft.end(), tmp.begin(), std::norm<Real>);
            std::fill(ft.begin(), ft.end(), std::complex<Real>());
            fft.transform(tmp.begin(), tmp.end(), ft.begin());
            return ft;
        }
Rate QuantLib::detail::effectiveFixedRate (const std::vector< Spread > & spreads, const std::vector< Rate > & caps, const std::vector< Rate > & floors, Size i)
Definition at line 36 of file cashflowvectors.cpp.
Referenced by QuantLib::FloatingLeg(), QuantLib::yoyInflationLeg::operator Leg(), and QuantLib::CPILeg::operator Leg().
{
            Rate result = get(spreads, i, 0.0);
            Rate floor = get(floors, i, Null<Rate>());
            if (floor!=Null<Rate>())
                result = std::max(floor, result);
            Rate cap = get(caps, i, Null<Rate>());
            if (cap!=Null<Rate>())
                result = std::min(cap, result);
            return result;
        }
template<class T , class U > T QuantLib::detail::get (const std::vector< T > & v, Size i, U defaultValue)
Definition at line 35 of file vectors.hpp.
References anonymous_namespace{perturbativebarrieroptionengine.cpp}::v().
Referenced by QuantLib::InverseCumulativePoisson::calcSummand(), QuantLib::FloatingDigitalLeg(), QuantLib::FloatingLeg(), QuantLib::HaltonRsg::nextSequence(), QuantLib::OvernightLeg::operator Leg(), QuantLib::AverageBMALeg::operator Leg(), QuantLib::yoyInflationLeg::operator Leg(), QuantLib::CPILeg::operator Leg(), and FactorialTest::testFactorial().
{
            if (v.empty()) {
                return static_cast<T>(defaultValue);
            } else if (i < v.size()) {
                return v[i];
            } else {
                return v.back();
            }
        }
bool QuantLib::detail::noOption (const std::vector< Rate > & caps, const std::vector< Rate > & floors, Size i)
Definition at line 50 of file cashflowvectors.cpp.
Referenced by QuantLib::FloatingLeg(), QuantLib::yoyInflationLeg::operator Leg(), and QuantLib::CPILeg::operator Leg().
{
            return (get(caps,   i, Null<Rate>()) == Null<Rate>()) &&
                   (get(floors, i, Null<Rate>()) == Null<Rate>());
        }
std::ostream & QuantLib::detail::operator<< (std::ostream & out, const ordinal_holder & holder)
Definition at line 26 of file dataformatters.cpp.
References QuantLib::detail::ordinal_holder::n.
{
            Size n = holder.n;
            out << n;
            if (n == Size(11) || n == Size(12) || n == Size(13)) {
                out << "th";
            } else {
                switch (n % 10) {
                  case 1:  out << "st";  break;
                  case 2:  out << "nd";  break;
                  case 3:  out << "rd";  break;
                  default: out << "th";
                }
            }
            return out;
        }
template<typename T > std::ostream & QuantLib::detail::operator<< (std::ostream & out, const null_checker< T > & checker) [inline]
Definition at line 149 of file dataformatters.hpp.
References QuantLib::detail::null_checker< T >::value.
{
            if (checker.value == Null<T>())
                return out << "null";
            else
                return out << checker.value;
        }
std::ostream & QuantLib::detail::operator<< (std::ostream & out, const long_weekday_holder & holder)
Definition at line 38 of file weekday.cpp.
References QuantLib::detail::long_weekday_holder::d, QuantLib::Friday, QuantLib::Monday, QL_FAIL, QuantLib::Saturday, QuantLib::Sunday, QuantLib::Thursday, QuantLib::Tuesday, and QuantLib::Wednesday.
{
            switch (holder.d) {
              case Sunday:
                return out << "Sunday";
              case Monday:
                return out << "Monday";
              case Tuesday:
                return out << "Tuesday";
              case Wednesday:
                return out << "Wednesday";
              case Thursday:
                return out << "Thursday";
              case Friday:
                return out << "Friday";
              case Saturday:
                return out << "Saturday";
              default:
                QL_FAIL("unknown weekday");
            }
        }
std::ostream & QuantLib::detail::operator<< (std::ostream & out, const percent_holder & holder)
Definition at line 43 of file dataformatters.cpp.
References QuantLib::detail::percent_holder::value.
{
            std::ios::fmtflags flags = out.flags();
            Size width = (Size)out.width();
            if (width > 2)
                out.width(width-2); // eat space used by percent sign
            out << std::fixed;
            if (holder.value == Null<Real>())
                out << "null";
            else
                out << holder.value * 100.0 << " %";
            out.flags(flags);
            return out;
        }
template<typename T > std::ostream & QuantLib::detail::operator<< (std::ostream & out, const power_of_two_holder< T > & holder) [inline]
Definition at line 158 of file dataformatters.hpp.
References QuantLib::detail::power_of_two_holder< T >::n.
{
            if (holder.n == Null<T>())
                return out << "null";
            T n = holder.n;
            Integer power = 0;
            if (n != 0) {
                while (!(n & 1UL)) {
                    power++;
                    n >>= 1;
                }
            }
            return out << n << "*2^" << power;
        }
std::ostream & QuantLib::detail::operator<< (std::ostream & out, const short_weekday_holder & holder)
Definition at line 60 of file weekday.cpp.
References QuantLib::detail::short_weekday_holder::d, QuantLib::Friday, QuantLib::Monday, QL_FAIL, QuantLib::Saturday, QuantLib::Sunday, QuantLib::Thursday, QuantLib::Tuesday, and QuantLib::Wednesday.
{
            switch (holder.d) {
              case Sunday:
                return out << "Sun";
              case Monday:
                return out << "Mon";
              case Tuesday:
                return out << "Tue";
              case Wednesday:
                return out << "Wed";
              case Thursday:
                return out << "Thu";
              case Friday:
                return out << "Fri";
              case Saturday:
                return out << "Sat";
              default:
                QL_FAIL("unknown weekday");
            }
        }
template<typename I > std::ostream & QuantLib::detail::operator<< (std::ostream & out, const sequence_holder< I > & holder) [inline]
Definition at line 175 of file dataformatters.hpp.
References QuantLib::detail::sequence_holder< InputIterator >::begin, QuantLib::detail::sequence_holder< InputIterator >::end, and anonymous_namespace{matrices.cpp}::I.
{
            out << "( ";
            for (I i = holder.begin; i != holder.end; ++i)
                out << *i << " ";
            out << ")";
            return out;
        }
std::ostream & QuantLib::detail::operator<< (std::ostream & out, const shortest_weekday_holder & holder)
Definition at line 82 of file weekday.cpp.
References QuantLib::detail::shortest_weekday_holder::d, QuantLib::Friday, QuantLib::Monday, QL_FAIL, QuantLib::Saturday, QuantLib::Sunday, QuantLib::Thursday, QuantLib::Tuesday, and QuantLib::Wednesday.
{
            switch (holder.d) {
              case Sunday:
                return out << "Su";
              case Monday:
                return out << "Mo";
              case Tuesday:
                return out << "Tu";
              case Wednesday:
                return out << "We";
              case Thursday:
                return out << "Th";
              case Friday:
                return out << "Fr";
              case Saturday:
                return out << "Sa";
              default:
                QL_FAIL("unknown weekday");
            }
        }
std::ostream & QuantLib::detail::operator<< (std::ostream & out, const long_period_holder & holder)
Definition at line 400 of file period.cpp.
References QuantLib::Days, QuantLib::Period::length(), QuantLib::Months, QuantLib::detail::long_period_holder::p, QL_FAIL, QuantLib::Period::units(), QuantLib::Weeks, and QuantLib::Years.
{
            Integer n = holder.p.length();
            Integer m = 0;
            switch (holder.p.units()) {
              case Days:
                if (n>=7) {
                    m = n/7;
                    out << m << (m == 1 ? " week " : " weeks ");
                    n = n%7;
                }
                if (n != 0 || m == 0)
                    return out << n << (n == 1 ? " day" : " days");
                else
                    return out;
              case Weeks:
                return out << n << (n == 1 ? " week" : " weeks");
              case Months:
                if (n>=12) {
                    m = n/12;
                    out << m << (m == 1 ? " year " : " years ");
                    n = n%12;
                }
                if (n != 0 || m == 0)
                    return out << n << (n == 1 ? " month" : " months");
                else
                    return out;
              case Years:
                return out << n << (n == 1 ? " year" : " years");
              default:
                QL_FAIL("unknown time unit (" << Integer(holder.p.units()) << ")");
            }
        }
std::ostream & QuantLib::detail::operator<< (std::ostream & out, const short_period_holder & holder)
Definition at line 434 of file period.cpp.
References QuantLib::Days, QuantLib::Period::length(), QuantLib::Months, QuantLib::detail::short_period_holder::p, QL_FAIL, QuantLib::Period::units(), QuantLib::Weeks, and QuantLib::Years.
{
            Integer n = holder.p.length();
            Integer m = 0;
            switch (holder.p.units()) {
              case Days:
                if (n>=7) {
                    m = n/7;
                    out << m << "W";
                    n = n%7;
                }
                if (n != 0 || m == 0)
                    return out << n << "D";
                else
                    return out;
              case Weeks:
                return out << n << "W";
              case Months:
                if (n>=12) {
                    m = n/12;
                    out << n/12 << "Y";
                    n = n%12;
                }
                if (n != 0 || m == 0)
                    return out << n << "M";
                else
                    return out;
              case Years:
                return out << n << "Y";
              default:
                QL_FAIL("unknown time unit (" << Integer(holder.p.units()) << ")");
            }
        }
std::ostream & QuantLib::detail::operator<< (std::ostream & out, const short_date_holder & holder)
Definition at line 440 of file date.cpp.
References anonymous_namespace{marketmodel.cpp}::d, QuantLib::detail::short_date_holder::d, QuantLib::Date::dayOfMonth(), QuantLib::Date::month(), and QuantLib::Date::year().
{
            const Date& d = holder.d;
            if (d == Date()) {
                out << "null date";
            } else {
                Integer dd = d.dayOfMonth(), mm = Integer(d.month()),
                        yyyy = d.year();
                char filler = out.fill();
                out << std::setw(2) << std::setfill('0') << mm << "/";
                out << std::setw(2) << std::setfill('0') << dd << "/";
                out << yyyy;
                out.fill(filler);
            }
            return out;
        }
std::ostream & QuantLib::detail::operator<< (std::ostream & out, const long_date_holder & holder)
Definition at line 457 of file date.cpp.
References anonymous_namespace{marketmodel.cpp}::d, QuantLib::detail::long_date_holder::d, QuantLib::Date::dayOfMonth(), QuantLib::Date::month(), QuantLib::io::ordinal(), and QuantLib::Date::year().
{
            const Date& d = holder.d;
            if (d == Date()) {
                out << "null date";
            } else {
                out << d.month() << " ";
                out << io::ordinal(d.dayOfMonth()) << ", ";
                out << d.year();
            }
            return out;
        }
std::ostream & QuantLib::detail::operator<< (std::ostream & out, const iso_date_holder & holder)
Definition at line 470 of file date.cpp.
References anonymous_namespace{marketmodel.cpp}::d, QuantLib::detail::iso_date_holder::d, QuantLib::Date::dayOfMonth(), QuantLib::Date::month(), and QuantLib::Date::year().
{
            const Date& d = holder.d;
            if (d == Date()) {
                out << "null date";
            } else {
                Integer dd = d.dayOfMonth(), mm = Integer(d.month()),
                        yyyy = d.year();
                char filler = out.fill();
                out << yyyy << "-";
                out << std::setw(2) << std::setfill('0') << mm << "-";
                out << std::setw(2) << std::setfill('0') << dd;
                out.fill(filler);
            }
            return out;
        }
template<typename InputIterator , typename OutputIterator > Real QuantLib::detail::remove_mean (InputIterator begin, InputIterator end, OutputIterator out)
Definition at line 56 of file autocovariance.hpp.
Referenced by QuantLib::autocorrelations(), and QuantLib::autocovariances().
{
            Real mean(0.0);
            std::size_t n = 1;
            for (InputIterator it = begin; it != end; ++it, ++n)
                mean = (mean*Real(n-1) + *it)/n;
            std::transform(begin, end, out,
                           std::bind2nd(std::minus<Real>(), mean));
            return mean;
        }
Variable Documentation
const Real QuantLib::detail::avgHazardRate = 0.01
Definition at line 39 of file probabilitytraits.hpp.
Referenced by QuantLib::SurvivalProbability::guess(), QuantLib::HazardRate::guess(), QuantLib::DefaultDensity::guess(), QuantLib::HazardRate::initialValue(), and QuantLib::DefaultDensity::initialValue().
const Rate QuantLib::detail::avgInflation = 0.02
Definition at line 36 of file inflationtraits.hpp.
Referenced by QuantLib::ZeroInflationTraits::guess(), and QuantLib::YoYInflationTraits::guess().
const Real QuantLib::detail::avgRate = 0.05
Definition at line 37 of file bootstraptraits.hpp.
Referenced by QuantLib::Discount::guess(), QuantLib::ZeroYield::guess(), QuantLib::ForwardRate::guess(), QuantLib::ZeroYield::initialValue(), and QuantLib::ForwardRate::initialValue().
const Real QuantLib::detail::maxHazardRate = 1.0
Definition at line 40 of file probabilitytraits.hpp.
Referenced by QuantLib::HazardRate::maxValueAfter(), QuantLib::DefaultDensity::maxValueAfter(), and QuantLib::SurvivalProbability::minValueAfter().
const Rate QuantLib::detail::maxInflation = 0.5
Definition at line 37 of file inflationtraits.hpp.
Referenced by QuantLib::ZeroInflationTraits::maxValueAfter(), QuantLib::YoYInflationTraits::maxValueAfter(), QuantLib::ZeroInflationTraits::minValueAfter(), and QuantLib::YoYInflationTraits::minValueAfter().
const Real QuantLib::detail::maxRate = 1.0
Definition at line 38 of file bootstraptraits.hpp.
Referenced by QuantLib::Discount::maxValueAfter(), QuantLib::ZeroYield::maxValueAfter(), QuantLib::ForwardRate::maxValueAfter(), QuantLib::Discount::minValueAfter(), QuantLib::ZeroYield::minValueAfter(), and QuantLib::ForwardRate::minValueAfter().