QuantLib: QuantLib::dsd Namespace Reference
QuantLib::dsd Namespace Reference
Functions
template<class InputIterator1 , class InputIterator2 , class T >
T inner_product (InputIterator1 f1, InputIterator1 l1, InputIterator2 f2, T init)
inner_product implementation using Duff's device
Function Documentation
template<class InputIterator1 , class InputIterator2 , class T > T QuantLib::dsd::inner_product (InputIterator1 f1, InputIterator1 l1, InputIterator2 f2, T init) [inline]
inner_product implementation using Duff's device
See http://www.lysator.liu.se/c/duffs-device.html and http://en.wikipedia.org/wiki/Duff's_device
Todo:
investigate the possible advantages of using boost implementation, see: <boost/numeric/ublas/detail/duff.hpp> <boost/numeric/ublas/functional.hpp> <boostnumeric/ublas/detail/matrix_assign.hpp> <boost/numeric/ublas/detail/vector_assign.hpp>
Definition at line 43 of file duffsdeviceinnerproduct.hpp.
Referenced by QuantLib::AverageBasketPayoff::accumulate(), QuantLib::BasisIncompleteOrdered::addVector(), QuantLib::LogNormalFwdRateBalland::advanceStep(), QuantLib::LogNormalFwdRateiBalland::advanceStep(), QuantLib::NormalFwdRatePc::advanceStep(), QuantLib::LogNormalCotSwapRatePc::advanceStep(), QuantLib::LogNormalFwdRateEuler::advanceStep(), QuantLib::LogNormalFwdRateIpc::advanceStep(), QuantLib::LogNormalFwdRatePc::advanceStep(), QuantLib::LogNormalCmSwapRatePc::advanceStep(), QuantLib::SVDDFwdRatePc::advanceStep(), QuantLib::LogNormalFwdRateEulerConstrained::advanceStep(), QuantLib::GeneralLinearLeastSquares::calculate(), QuantLib::LMMDriftCalculator::computePlain(), QuantLib::LMMNormalDriftCalculator::computePlain(), QuantLib::DotProduct(), QuantLib::LiborForwardModelProcess::drift(), QuantLib::JointStochasticProcess::evolve(), QuantLib::LiborForwardModelProcess::evolve(), QuantLib::LongstaffSchwartzExerciseStrategy::exercise(), QuantLib::genericLongstaffSchwartzRegression(), QuantLib::FdmLinearOpLayout::index(), QuantLib::LfmHullWhiteParameterization::LfmHullWhiteParameterization(), QuantLib::LogNormalCmSwapRatePc::LogNormalCmSwapRatePc(), QuantLib::LogNormalCotSwapRatePc::LogNormalCotSwapRatePc(), QuantLib::LogNormalFwdRateEuler::LogNormalFwdRateEuler(), QuantLib::LogNormalFwdRateEulerConstrained::LogNormalFwdRateEulerConstrained(), QuantLib::LogNormalFwdRatePc::LogNormalFwdRatePc(), QuantLib::LfmCovarianceParameterization::Var_Helper::operator()(), QuantLib::operator*(), QuantLib::RendistatoCalculator::performCalculations(), QuantLib::qrDecomposition(), QuantLib::SVDDFwdRatePc::SVDDFwdRatePc(), MatricesTest::testQRSolve(), QuantLib::TripleBandLinearOp::TripleBandLinearOp(), and QuantLib::RendistatoCalculator::yield().
{
        switch ((l1-f1) % 8) {
        case  0: while (f1 != l1) { init = init + *f1 * *f2; ++f1; ++f2;
        case  7:                    init = init + *f1 * *f2; ++f1; ++f2;
        case  6:                    init = init + *f1 * *f2; ++f1; ++f2;
        case  5:                    init = init + *f1 * *f2; ++f1; ++f2;
        case  4:                    init = init + *f1 * *f2; ++f1; ++f2;
        case  3:                    init = init + *f1 * *f2; ++f1; ++f2;
        case  2:                    init = init + *f1 * *f2; ++f1; ++f2;
        case  1:                    init = init + *f1 * *f2; ++f1; ++f2;
                 }
        }
        // slightly different implementation
        //switch ( (l1-f1) % 8 ) while ( f1 != l1 ) {
        //case  8: init = init + *f1 * *f2; ++f1; ++f2;
        //case  7: init = init + *f1 * *f2; ++f1; ++f2;
        //case  6: init = init + *f1 * *f2; ++f1; ++f2;
        //case  5: init = init + *f1 * *f2; ++f1; ++f2;
        //case  4: init = init + *f1 * *f2; ++f1; ++f2;
        //case  3: init = init + *f1 * *f2; ++f1; ++f2;
        //case  2: init = init + *f1 * *f2; ++f1; ++f2;
        //case  1: init = init + *f1 * *f2; ++f1; ++f2;
        //case  0: ;
        //}
        // the following implementation crashes (probably when l1==f1)
        //switch ((l1-f1) % 8) {
        //case  0: do { init = init + *f1 * *f2; ++f1; ++f2;
        //case  7:      init = init + *f1 * *f2; ++f1; ++f2;
        //case  6:      init = init + *f1 * *f2; ++f1; ++f2;
        //case  5:      init = init + *f1 * *f2; ++f1; ++f2;
        //case  4:      init = init + *f1 * *f2; ++f1; ++f2;
        //case  3:      init = init + *f1 * *f2; ++f1; ++f2;
        //case  2:      init = init + *f1 * *f2; ++f1; ++f2;
        //case  1:      init = init + *f1 * *f2; ++f1; ++f2;
        //      } while (f1 != l1);
        //}
        return init;
    }