QuantLib: anonymous_namespace{swapforwardmappings.cpp} Namespace Reference
anonymous_namespace{swapforwardmappings.cpp} Namespace Reference
Classes
class MarketModelData
Functions
const boost::shared_ptr
< SequenceStatisticsInc > simulate (const std::vector< Real > todaysDiscounts, const boost::shared_ptr< MarketModelEvolver > &evolver, const MarketModelMultiProduct &product)
MultiStepCoterminalSwaptions makeMultiStepCoterminalSwaptions (const std::vector< Time > &rateTimes, Real strike)
Function Documentation
MultiStepCoterminalSwaptions anonymous_namespace{swapforwardmappings.cpp}::makeMultiStepCoterminalSwaptions (const std::vector< Time > & rateTimes, Real strike)
Definition at line 169 of file swapforwardmappings.cpp.
References QuantLib::Option::Call, and anonymous_namespace{marketmodel.cpp}::paymentTimes.
Referenced by SwapForwardMappingsTest::testForwardCoterminalMappings().
{
            std::vector<Time> paymentTimes(rateTimes.begin(), rateTimes.end()-1);
            std::vector<boost::shared_ptr<StrikedTypePayoff> > payoffs(paymentTimes.size());
            for (Size i = 0; i < payoffs.size(); ++i){
                payoffs[i] = boost::shared_ptr<StrikedTypePayoff>(new
                    PlainVanillaPayoff(Option::Call, strike));
            }
            return MultiStepCoterminalSwaptions (rateTimes,
                paymentTimes, payoffs);
    }
const boost::shared_ptr<SequenceStatisticsInc> anonymous_namespace{swapforwardmappings.cpp}::simulate (const std::vector< Real > todaysDiscounts, const boost::shared_ptr< MarketModelEvolver > & evolver, const MarketModelMultiProduct & product)
Definition at line 147 of file swapforwardmappings.cpp.
References QuantLib::AccountingEngine::multiplePathValues(), QuantLib::MarketModelMultiProduct::numberOfProducts(), and anonymous_namespace{marketmodel.cpp}::paths_.
    {
        Size paths_;
#ifdef _DEBUG
        paths_ = 127;// //
#else
        paths_ = 32767; //262144-1; // //; // 2^15-1
#endif
        Size initialNumeraire = evolver->numeraires().front();
        Real initialNumeraireValue = todaysDiscounts[initialNumeraire];
        AccountingEngine engine(evolver, product, initialNumeraireValue);
        boost::shared_ptr<SequenceStatisticsInc> stats(new
            SequenceStatisticsInc(product.numberOfProducts()));
        engine.multiplePathValues(*stats, paths_);
        return stats;
    }