QuantLib: anonymous_namespace{libormarketmodel.cpp} Namespace Reference
anonymous_namespace{libormarketmodel.cpp} Namespace Reference
Functions
boost::shared_ptr< IborIndex > makeIndex (std::vector< Date > dates, std::vector< Rate > rates)
boost::shared_ptr< IborIndex > makeIndex ()
boost::shared_ptr
< OptionletVolatilityStructure > makeCapVolCurve (const Date &todaysDate)
Function Documentation
boost::shared_ptr<OptionletVolatilityStructure> anonymous_namespace{libormarketmodel.cpp}::makeCapVolCurve (const Date & todaysDate)
Definition at line 93 of file libormarketmodel.cpp.
References anonymous_namespace{marketmodel.cpp}::dates, and makeIndex().
Referenced by anonymous_namespace{libormarketmodelprocess.cpp}::makeProcess(), and LiborMarketModelTest::testCapletPricing().
{
        Volatility vols[] = {14.40, 17.15, 16.81, 16.64, 16.17,
                             15.78, 15.40, 15.21, 14.86};
        std::vector<Date> dates;
        std::vector<Volatility> capletVols;
        boost::shared_ptr<LiborForwardModelProcess> process(
                               new LiborForwardModelProcess(10, makeIndex()));
        for (Size i=0; i < 9; ++i) {
            capletVols.push_back(vols[i]/100);
            dates.push_back(process->fixingDates()[i+1]);
        }
        return boost::shared_ptr<CapletVarianceCurve>(
                         new CapletVarianceCurve(todaysDate, dates,
                                                 capletVols, Actual360()));
    }
boost::shared_ptr<IborIndex> anonymous_namespace{libormarketmodel.cpp}::makeIndex (std::vector< Date > dates, std::vector< Rate > rates)
Definition at line 58 of file libormarketmodel.cpp.
References anonymous_namespace{marketmodel.cpp}::dayCounter, QuantLib::Days, QuantLib::Settings::evaluationDate(), QuantLib::Singleton< Settings >::instance(), QuantLib::RelinkableHandle< T >::linkTo(), QuantLib::September, and anonymous_namespace{marketmodel.cpp}::todaysDate.
Referenced by anonymous_namespace{libormarketmodelprocess.cpp}::makeCapVolCurve(), makeCapVolCurve(), makeIndex(), anonymous_namespace{libormarketmodelprocess.cpp}::makeProcess(), LiborMarketModelTest::testCalibration(), LiborMarketModelTest::testCapletPricing(), LiborMarketModelTest::testSimpleCovarianceModels(), and LiborMarketModelTest::testSwaptionPricing().
{
        DayCounter dayCounter = Actual360();
        RelinkableHandle<YieldTermStructure> termStructure;
        boost::shared_ptr<IborIndex> index(new Euribor6M(termStructure));
        Date todaysDate =
            index->fixingCalendar().adjust(Date(4,September,2005));
        Settings::instance().evaluationDate() = todaysDate;
        dates[0] = index->fixingCalendar().advance(todaysDate,
                                                   index->fixingDays(), Days);
        termStructure.linkTo(boost::shared_ptr<YieldTermStructure>(
                                    new ZeroCurve(dates, rates, dayCounter)));
        return index;
    }
boost::shared_ptr<IborIndex> anonymous_namespace{libormarketmodel.cpp}::makeIndex ()
Definition at line 80 of file libormarketmodel.cpp.
References anonymous_namespace{marketmodel.cpp}::dates, makeIndex(), and QuantLib::September.
{
        std::vector<Date> dates;
        std::vector<Rate> rates;
        dates.push_back(Date(4,September,2005));
        dates.push_back(Date(4,September,2018));
        rates.push_back(0.039);
        rates.push_back(0.041);
        return makeIndex(dates, rates);
    }