QuantLib: QuantLib::anonymous_namespace{cashflows.cpp} Namespace Reference
QuantLib::anonymous_namespace{cashflows.cpp} Namespace Reference
Classes
class BPSCalculator
class IrrFinder
class ZSpreadFinder
Functions
template<typename Iter >
Rate aggregateRate (const Leg &leg, Iter first, Iter last)
template<class T >
Integer sign (T x)
Real simpleDuration (const Leg &leg, const InterestRate &y, bool includeSettlementDateFlows, Date settlementDate, Date npvDate)
Real modifiedDuration (const Leg &leg, const InterestRate &y, bool includeSettlementDateFlows, Date settlementDate, Date npvDate)
Real macaulayDuration (const Leg &leg, const InterestRate &y, bool includeSettlementDateFlows, Date settlementDate, Date npvDate)
Variables
const Spread basisPoint_ = 1.0e-4
Function Documentation
template<typename Iter > Rate QuantLib::anonymous_namespace{cashflows.cpp}::aggregateRate (const Leg & leg, Iter first, Iter last)
Definition at line 180 of file cashflows.cpp.
References QL_ENSURE, and QL_REQUIRE.
{
            if (first==last) return 0.0;
            Date paymentDate = (*first)->date();
            bool firstCouponFound = false;
            Real nominal = 0.0;
            Time accrualPeriod = 0.0;
            DayCounter dc;
            Rate result = 0.0;
            for (; first<last && (*first)->date()==paymentDate; ++first) {
                shared_ptr<Coupon> cp = dynamic_pointer_cast<Coupon>(*first);
                if (cp) {
                    if (firstCouponFound) {
                        QL_REQUIRE(nominal       == cp->nominal() &&
                                   accrualPeriod == cp->accrualPeriod() &&
                                   dc            == cp->dayCounter(),
                                   "cannot aggregate two different coupons on "
                                   << paymentDate);
                    } else {
                        firstCouponFound = true;
                        nominal = cp->nominal();
                        accrualPeriod = cp->accrualPeriod();
                        dc = cp->dayCounter();
                    }
                    result += cp->rate();
                }
            }
            QL_ENSURE(firstCouponFound,
                      "no coupon paid at cashflow date " << paymentDate);
            return result;
        }
Real QuantLib::anonymous_namespace{cashflows.cpp}::macaulayDuration (const Leg & leg, const InterestRate & y, bool includeSettlementDateFlows, Date settlementDate, Date npvDate)
Definition at line 636 of file cashflows.cpp.
References QuantLib::Compounded, QuantLib::InterestRate::compounding(), QuantLib::InterestRate::frequency(), modifiedDuration(), QL_REQUIRE, and QuantLib::InterestRate::rate().
Referenced by QuantLib::CashFlows::duration().
{
            QL_REQUIRE(y.compounding() == Compounded,
                       "compounded rate required");
            return (1.0+y.rate()/y.frequency()) *
                modifiedDuration(leg, y,
                                 includeSettlementDateFlows,
                                 settlementDate, npvDate);
        }
Real QuantLib::anonymous_namespace{cashflows.cpp}::modifiedDuration (const Leg & leg, const InterestRate & y, bool includeSettlementDateFlows, Date settlementDate, Date npvDate)
Definition at line 580 of file cashflows.cpp.
References anonymous_namespace{marketmodel.cpp}::c, QuantLib::Compounded, QuantLib::InterestRate::compounding(), QuantLib::Continuous, QuantLib::InterestRate::dayCounter(), QuantLib::InterestRate::discountFactor(), QuantLib::Settings::evaluationDate(), QuantLib::InterestRate::frequency(), QuantLib::Singleton< Settings >::instance(), anonymous_namespace{matrices.cpp}::N, QL_FAIL, QuantLib::InterestRate::rate(), QuantLib::Simple, QuantLib::SimpleThenCompounded, anonymous_namespace{quantlibbenchmark.cpp}::t, and QuantLib::DayCounter::yearFraction().
Referenced by QuantLib::CashFlows::basisPointValue(), QuantLib::anonymous_namespace{cashflows.cpp}::IrrFinder::derivative(), QuantLib::CashFlows::duration(), macaulayDuration(), and QuantLib::CashFlows::yieldValueBasisPoint().
{
            if (leg.empty())
                return 0.0;
            if (settlementDate == Date())
                settlementDate = Settings::instance().evaluationDate();
            if (npvDate == Date())
                npvDate = settlementDate;
            Real P = 0.0;
            Real dPdy = 0.0;
            Rate r = y.rate();
            Natural N = y.frequency();
            const DayCounter& dc = y.dayCounter();
            for (Size i=0; i<leg.size(); ++i) {
                if (!leg[i]->hasOccurred(settlementDate,
                                         includeSettlementDateFlows)) {
                    Time t = dc.yearFraction(npvDate,
                                             leg[i]->date());
                    Real c = leg[i]->amount();
                    DiscountFactor B = y.discountFactor(t);
                    P += c * B;
                    switch (y.compounding()) {
                      case Simple:
                        dPdy -= c * B*B * t;
                        break;
                      case Compounded:
                        dPdy -= c * t * B/(1+r/N);
                        break;
                      case Continuous:
                        dPdy -= c * B * t;
                        break;
                      case SimpleThenCompounded:
                        if (t<=1.0/N)
                            dPdy -= c * B*B * t;
                        else
                            dPdy -= c * t * B/(1+r/N);
                        break;
                      default:
                        QL_FAIL("unknown compounding convention (" <<
                                Integer(y.compounding()) << ")");
                    }
                }
            }
            if (P == 0.0) // no cashflows
                return 0.0;
            return -dPdy/P; // reverse derivative sign
        }
template<class T > Integer QuantLib::anonymous_namespace{cashflows.cpp}::sign (T x)
Definition at line 537 of file cashflows.cpp.
Referenced by QuantLib::anonymous_namespace{cashflows.cpp}::IrrFinder::checkSign(), QuantLib::SymmetricSchurDecomposition::SymmetricSchurDecomposition(), and QuantLib::TqrEigenDecomposition::TqrEigenDecomposition().
{
            static T zero = T();
            if (x == zero)
                return 0;
            else if (x > zero)
                return 1;
            else
                return -1;
        }
Real QuantLib::anonymous_namespace{cashflows.cpp}::simpleDuration (const Leg & leg, const InterestRate & y, bool includeSettlementDateFlows, Date settlementDate, Date npvDate)
Definition at line 547 of file cashflows.cpp.
References anonymous_namespace{marketmodel.cpp}::c, QuantLib::InterestRate::dayCounter(), QuantLib::InterestRate::discountFactor(), QuantLib::Settings::evaluationDate(), QuantLib::Singleton< Settings >::instance(), anonymous_namespace{quantlibbenchmark.cpp}::t, and QuantLib::DayCounter::yearFraction().
Referenced by QuantLib::CashFlows::duration().
{
            if (leg.empty())
                return 0.0;
            if (settlementDate == Date())
                settlementDate = Settings::instance().evaluationDate();
            if (npvDate == Date())
                npvDate = settlementDate;
            Real P = 0.0;
            Real dPdy = 0.0;
            const DayCounter& dc = y.dayCounter();
            for (Size i=0; i<leg.size(); ++i) {
                if (!leg[i]->hasOccurred(settlementDate,
                                         includeSettlementDateFlows)) {
                    Time t = dc.yearFraction(npvDate,
                                             leg[i]->date());
                    Real c = leg[i]->amount();
                    DiscountFactor B = y.discountFactor(t);
                    P += c * B;
                    dPdy += t * c * B;
                }
            }
            if (P == 0.0) // no cashflows
                return 0.0;
            return dPdy/P;
        }
Variable Documentation
const Spread QuantLib::anonymous_namespace{cashflows.cpp}::basisPoint_ = 1.0e-4
Definition at line 425 of file cashflows.cpp.
Referenced by QuantLib::CashFlows::atmRate(), QuantLib::CashFlows::bps(), and QuantLib::CashFlows::npvbps().