QuantLib: QuantLib::anonymous_namespace{basisincompleteordered.cpp} Namespace Reference
QuantLib::anonymous_namespace{basisincompleteordered.cpp} Namespace Reference
Functions
Real normSquared (const Matrix &v, Size row)
Real norm (const Matrix &v, Size row)
Real innerProduct (const Matrix &v, Size row1, const Matrix &w, Size row2)
Real normSquared (const std::vector< Real > &v)
Real norm (const std::vector< Real > &v)
Function Documentation
Real QuantLib::anonymous_namespace{basisincompleteordered.cpp}::innerProduct (const Matrix & v, Size row1, const Matrix & w, Size row2)
Definition at line 98 of file basisincompleteordered.cpp.
References QuantLib::Matrix::columns().
Referenced by QuantLib::OrthogonalProjections::OrthogonalProjections().
        {
            Real x=0.0;
            for (Size i=0; i < v.columns(); ++i)
                x += v[row1][i]*w[row2][i];
            return x;
        }
Real QuantLib::anonymous_namespace{basisincompleteordered.cpp}::norm (const Matrix & v, Size row)
Definition at line 93 of file basisincompleteordered.cpp.
References normSquared().
Referenced by QuantLib::OneFactorCopula::checkMoments().
        {
            return std::sqrt(normSquared( v,  row));
        }
Real QuantLib::anonymous_namespace{basisincompleteordered.cpp}::norm (const std::vector< Real > & v)
Definition at line 117 of file basisincompleteordered.cpp.
References normSquared().
        {
            return std::sqrt(normSquared(v));
        }
Real QuantLib::anonymous_namespace{basisincompleteordered.cpp}::normSquared (const Matrix & v, Size row)
Definition at line 83 of file basisincompleteordered.cpp.
References QuantLib::Matrix::columns().
Referenced by norm(), and QuantLib::OrthogonalProjections::OrthogonalProjections().
        {
            Real x=0.0;
            for (Size i=0; i < v.columns(); ++i)
                x += v[row][i]*v[row][i];
            return x;
        }
Real QuantLib::anonymous_namespace{basisincompleteordered.cpp}::normSquared (const std::vector< Real > & v)
Definition at line 108 of file basisincompleteordered.cpp.
        {
            Real x=0.0;
            for (Size i=0; i < v.size(); ++i)
                x += v[i]*v[i];
            return x;
        }