QuantLib: QuantLib::anonymous_namespace{business252.cpp} Namespace Reference
QuantLib::anonymous_namespace{business252.cpp} Namespace Reference
Typedefs
typedef std::map< Year,
std::map< Month, BigInteger > > Cache
typedef std::map< Year,
BigInteger > OuterCache
Functions
bool sameYear (const Date &d1, const Date &d2)
bool sameMonth (const Date &d1, const Date &d2)
BigInteger businessDays (Cache &cache, const Calendar &calendar, Month month, Year year)
BigInteger businessDays (OuterCache &outerCache, Cache &cache, const Calendar &calendar, Year year)
Variables
std::map< std::string, Cache > monthlyFigures_
std::map< std::string, OuterCache > yearlyFigures_
Typedef Documentation
typedef std::map<Year, std::map<Month, BigInteger> > QuantLib::anonymous_namespace{business252.cpp}::Cache
Definition at line 28 of file business252.cpp.
typedef std::map<Year, BigInteger> QuantLib::anonymous_namespace{business252.cpp}::OuterCache
Definition at line 29 of file business252.cpp.
Function Documentation
BigInteger QuantLib::anonymous_namespace{business252.cpp}::businessDays (Cache & cache, const Calendar & calendar, Month month, Year year)
Definition at line 42 of file business252.cpp.
References QuantLib::Calendar::businessDaysBetween(), and QuantLib::Months.
Referenced by businessDays(), and QuantLib::Business252::Impl::dayCount().
{
            if (cache[year][month] == 0) {
                // calculate and store.
                Date d1 = Date(1,month,year);
                Date d2 = d1 + 1*Months;
                cache[year][month] = calendar.businessDaysBetween(d1, d2);
            }
            return cache[year][month];
        }
BigInteger QuantLib::anonymous_namespace{business252.cpp}::businessDays (OuterCache & outerCache, Cache & cache, const Calendar & calendar, Year year)
Definition at line 54 of file business252.cpp.
References businessDays().
{
            if (outerCache[year] == 0) {
                // calculate and store.
                BigInteger total = 0;
                for (Integer i=1; i<=12; ++i) {
                    total += businessDays(cache,calendar,
                                          Month(i), year);
                }
                outerCache[year] = total;
            }
            return outerCache[year];
        }
bool QuantLib::anonymous_namespace{business252.cpp}::sameMonth (const Date & d1, const Date & d2)
Definition at line 38 of file business252.cpp.
References QuantLib::Date::month(), and QuantLib::Date::year().
Referenced by QuantLib::Business252::Impl::dayCount().
{
            return d1.year() == d2.year() && d1.month() == d2.month();
        }
bool QuantLib::anonymous_namespace{business252.cpp}::sameYear (const Date & d1, const Date & d2)
Definition at line 34 of file business252.cpp.
References QuantLib::Date::year().
Referenced by QuantLib::Business252::Impl::dayCount().
{
            return d1.year() == d2.year();
        }
Variable Documentation
std::map<std::string, Cache> QuantLib::anonymous_namespace{business252.cpp}::monthlyFigures_
Definition at line 31 of file business252.cpp.
Referenced by QuantLib::Business252::Impl::dayCount().
std::map<std::string, OuterCache> QuantLib::anonymous_namespace{business252.cpp}::yearlyFigures_
Definition at line 32 of file business252.cpp.
Referenced by QuantLib::Business252::Impl::dayCount().