QuantLib: anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp} Namespace Reference
anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp} Namespace Reference
Enumerations
enum MarketModelType { ExponentialCorrelationFlatVolatility, ExponentialCorrelationAbcdVolatility }
enum MeasureType { ProductSuggested, Terminal, MoneyMarket, MoneyMarketPlus }
enum EvolverType { Ipc, Pc, NormalPc }
Functions
void setup ()
const boost::shared_ptr
< SequenceStatisticsInc > simulate (const boost::shared_ptr< MarketModelEvolver > &evolver, const MarketModelMultiProduct &product)
std::string marketModelTypeToString (MarketModelType type)
boost::shared_ptr< MarketModel > makeMarketModel (const EvolutionDescription &evolution, Size numberOfFactors, MarketModelType marketModelType, Spread rateBump=0.0, Volatility volBump=0.0)
std::string measureTypeToString (MeasureType type)
std::vector< Size > makeMeasure (const MarketModelMultiProduct &product, MeasureType measureType)
std::string evolverTypeToString (EvolverType type)
boost::shared_ptr
< MarketModelEvolver > makeMarketModelEvolver (const boost::shared_ptr< MarketModel > &marketModel, const std::vector< Size > &numeraires, const BrownianGeneratorFactory &generatorFactory, EvolverType evolverType, Size initialStep=0)
Variables
Date todaysDate_
Date startDate_
Date endDate_
std::vector< Time > rateTimes_
std::vector< Real > accruals_
Calendar calendar_
DayCounter dayCounter_
std::vector< Rate > todaysForwards_
std::vector< Rate > todaysSwaps_
std::vector< Real > coterminalAnnuity_
Size numberOfFactors_
Real alpha_
Real alphaMax_
Real alphaMin_
Spread displacement_
std::vector< DiscountFactor > todaysDiscounts_
std::vector< Volatility > swaptionDisplacedVols_
std::vector< Volatility > swaptionVols_
std::vector< Volatility > capletDisplacedVols_
std::vector< Volatility > capletVols_
Real a_
Real b_
Real c_
Real d_
Real longTermCorrelation_
Real beta_
Size measureOffset_
unsigned long seed_
Size paths_
Size trainingPaths_
bool printReport_ = false
Enumeration Type Documentation
enum anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::EvolverType
Enumerator:
Ipc
Pc
NormalPc
Definition at line 381 of file marketmodel_smmcaplethomocalibration.cpp.
{ Ipc, Pc , NormalPc};
enum anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::MarketModelType
Enumerator:
ExponentialCorrelationFlatVolatility
ExponentialCorrelationAbcdVolatility
Definition at line 235 of file marketmodel_smmcaplethomocalibration.cpp.
                         { ExponentialCorrelationFlatVolatility,
                           ExponentialCorrelationAbcdVolatility/*,
                           CalibratedMM*/
    };
enum anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::MeasureType
Enumerator:
ProductSuggested
Terminal
MoneyMarket
MoneyMarketPlus
Definition at line 318 of file marketmodel_smmcaplethomocalibration.cpp.
                     { ProductSuggested, Terminal,
                       MoneyMarket, MoneyMarketPlus };
Function Documentation
std::string anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::evolverTypeToString (EvolverType type)
Definition at line 383 of file marketmodel_smmcaplethomocalibration.cpp.
References anonymous_namespace{marketmodel.cpp}::Ipc, anonymous_namespace{marketmodel.cpp}::NormalPc, anonymous_namespace{marketmodel.cpp}::Pc, and QL_FAIL.
{
        switch (type) {
          case Ipc:
            return "iterative predictor corrector";
          case Pc:
            return "predictor corrector";
          case NormalPc:
            return "predictor corrector for normal case";
          default:
            QL_FAIL("unknown MarketModelEvolver type");
        }
    }
boost::shared_ptr<MarketModel> anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::makeMarketModel (const EvolutionDescription & evolution, Size numberOfFactors, MarketModelType marketModelType, Spread rateBump = 0.0, Volatility volBump = 0.0)
Definition at line 254 of file marketmodel_smmcaplethomocalibration.cpp.
References anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::beta_, anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::displacement_, anonymous_namespace{marketmodel.cpp}::ExponentialCorrelationAbcdVolatility, anonymous_namespace{marketmodel.cpp}::ExponentialCorrelationFlatVolatility, QuantLib::exponentialCorrelations(), anonymous_namespace{marketmodel_smmcapletalphacalibration.cpp}::longTermCorrelation_, QuantLib::EvolutionDescription::numberOfRates(), QL_FAIL, and QuantLib::EvolutionDescription::rateTimes().
{
        std::vector<Time> fixingTimes(evolution.rateTimes());
        fixingTimes.pop_back();
        boost::shared_ptr<LmVolatilityModel> volModel(new
            LmExtLinearExponentialVolModel(fixingTimes, 0.5, 0.6, 0.1, 0.1));
        boost::shared_ptr<LmCorrelationModel> corrModel(new
            LmLinearExponentialCorrelationModel(evolution.numberOfRates(),
                                                longTermCorrelation_, beta_));
        std::vector<Rate> bumpedRates(todaysForwards_.size());
        LMMCurveState curveState_lmm(rateTimes_);
        curveState_lmm.setOnForwardRates(todaysForwards_);
        std::vector<Rate> usedRates = curveState_lmm.coterminalSwapRates();
        std::transform(usedRates.begin(), usedRates.end(),
                       bumpedRates.begin(),
                       std::bind1st(std::plus<Rate>(), rateBump));
        std::vector<Volatility> bumpedVols(swaptionDisplacedVols_.size());
        std::transform(swaptionDisplacedVols_.begin(), swaptionDisplacedVols_.end(),
                       bumpedVols.begin(),
                       std::bind1st(std::plus<Rate>(), volBump));
        Matrix correlations = exponentialCorrelations(evolution.rateTimes(),
                                                      longTermCorrelation_,
                                                      beta_);
        boost::shared_ptr<PiecewiseConstantCorrelation> corr(new
            TimeHomogeneousForwardCorrelation(correlations,
                                              evolution.rateTimes()));
        switch (marketModelType) {
          case ExponentialCorrelationFlatVolatility:
            return boost::shared_ptr<MarketModel>(new
                FlatVol(bumpedVols,
                               corr,
                               evolution,
                               numberOfFactors,
                               bumpedRates,
                               std::vector<Spread>(bumpedRates.size(),
                               displacement_)));
          case ExponentialCorrelationAbcdVolatility:
            return boost::shared_ptr<MarketModel>(new
                AbcdVol(0.0,0.0,1.0,1.0,
                               bumpedVols,
                               corr,
                               evolution,
                               numberOfFactors,
                               bumpedRates,
                               std::vector<Spread>(bumpedRates.size(),
                               displacement_)));
            //case CalibratedMM:
            //    return boost::shared_ptr<MarketModel>(new
            //        CalibratedMarketModel(volModel, corrModel,
            //                              evolution,
            //                              numberOfFactors,
            //                              bumpedForwards,
            //                              displacement));
          default:
            QL_FAIL("unknown MarketModel type");
        }
    }
boost::shared_ptr<MarketModelEvolver> anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::makeMarketModelEvolver (const boost::shared_ptr< MarketModel > & marketModel, const std::vector< Size > & numeraires, const BrownianGeneratorFactory & generatorFactory, EvolverType evolverType, Size initialStep = 0)
Definition at line 396 of file marketmodel_smmcaplethomocalibration.cpp.
References anonymous_namespace{marketmodel.cpp}::Pc, and QL_FAIL.
{
        switch (evolverType) {
          case Pc:
            return boost::shared_ptr<MarketModelEvolver>(new
                LogNormalCotSwapRatePc(marketModel, generatorFactory,
                                            numeraires,
                                            initialStep));
          default:
            QL_FAIL("unknown CoterminalSwapMarketModelEvolver type");
        }
    }
std::vector<Size> anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::makeMeasure (const MarketModelMultiProduct & product, MeasureType measureType)
Definition at line 336 of file marketmodel_smmcaplethomocalibration.cpp.
References anonymous_namespace{marketmodel.cpp}::a, QuantLib::checkCompatibility(), QuantLib::MarketModelMultiProduct::evolution(), QuantLib::isInMoneyMarketMeasure(), QuantLib::isInMoneyMarketPlusMeasure(), QuantLib::isInTerminalMeasure(), anonymous_namespace{marketmodel.cpp}::measureTypeToString(), anonymous_namespace{marketmodel.cpp}::MoneyMarket, QuantLib::moneyMarketMeasure(), anonymous_namespace{marketmodel.cpp}::MoneyMarketPlus, QuantLib::moneyMarketPlusMeasure(), anonymous_namespace{marketmodel.cpp}::ProductSuggested, QL_FAIL, QuantLib::MarketModelMultiProduct::suggestedNumeraires(), anonymous_namespace{marketmodel.cpp}::Terminal, and QuantLib::terminalMeasure().
{
        std::vector<Size> result;
        EvolutionDescription evolution(product.evolution());
        switch (measureType) {
          case ProductSuggested:
            result = product.suggestedNumeraires();
            break;
          case Terminal:
            result = terminalMeasure(evolution);
            if (!isInTerminalMeasure(evolution, result)) {
                Array a(result.size());
                std::copy(result.begin(), result.end(), a.begin());
                BOOST_ERROR("\nfailure in verifying Terminal measure:\n" << a);
            }
            break;
          case MoneyMarket:
            result = moneyMarketMeasure(evolution);
            if (!isInMoneyMarketMeasure(evolution, result)) {
                Array a(result.size());
                std::copy(result.begin(), result.end(), a.begin());
                BOOST_ERROR("\nfailure in verifying MoneyMarket measure:\n" << a);
            }
            break;
          case MoneyMarketPlus:
            result = moneyMarketPlusMeasure(evolution, measureOffset_);
            if (!isInMoneyMarketPlusMeasure(evolution, result, measureOffset_)) {
                Array a(result.size());
                std::copy(result.begin(), result.end(), a.begin());
                BOOST_ERROR("\nfailure in verifying MoneyMarketPlus(" <<
                            measureOffset_ << ") measure:\n" << a);
            }
            break;
          default:
            QL_FAIL("unknown measure type");
        }
        checkCompatibility(evolution, result);
        if (printReport_) {
            Array num(result.size());
            std::copy(result.begin(), result.end(), num.begin());
            BOOST_MESSAGE("    " << measureTypeToString(measureType) << ": " << num);
        }
        return result;
    }
std::string anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::marketModelTypeToString (MarketModelType type)
Definition at line 240 of file marketmodel_smmcaplethomocalibration.cpp.
References anonymous_namespace{marketmodel.cpp}::ExponentialCorrelationAbcdVolatility, anonymous_namespace{marketmodel.cpp}::ExponentialCorrelationFlatVolatility, and QL_FAIL.
{
        switch (type) {
          case ExponentialCorrelationFlatVolatility:
            return "Exp. Corr. Flat Vol.";
          case ExponentialCorrelationAbcdVolatility:
            return "Exp. Corr. Abcd Vol.";
            //case CalibratedMM:
            //    return "CalibratedMarketModel";
          default:
            QL_FAIL("unknown MarketModelEvolver type");
        }
    }
std::string anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::measureTypeToString (MeasureType type)
Definition at line 321 of file marketmodel_smmcaplethomocalibration.cpp.
References anonymous_namespace{marketmodel.cpp}::MoneyMarket, anonymous_namespace{marketmodel.cpp}::MoneyMarketPlus, anonymous_namespace{marketmodel.cpp}::ProductSuggested, QL_FAIL, and anonymous_namespace{marketmodel.cpp}::Terminal.
{
        switch (type) {
          case ProductSuggested:
            return "ProductSuggested measure";
          case Terminal:
            return "Terminal measure";
          case MoneyMarket:
            return "Money Market measure";
          case MoneyMarketPlus:
            return "Money Market Plus measure";
          default:
            QL_FAIL("unknown measure type");
        }
    }
void anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::setup ()
Definition at line 104 of file marketmodel_smmcaplethomocalibration.cpp.
References QuantLib::DateGeneration::Backward, QuantLib::LMMCurveState::coterminalSwapRates(), anonymous_namespace{marketmodel.cpp}::dates, QuantLib::Settings::evaluationDate(), QuantLib::Following, QuantLib::Singleton< Settings >::instance(), QuantLib::Months, QuantLib::Semiannual, QuantLib::LMMCurveState::setOnForwardRates(), and QuantLib::Schedule::size().
                 {
        // Times
        calendar_ = NullCalendar();
        todaysDate_ = Settings::instance().evaluationDate();
        //startDate = todaysDate + 5*Years;
        endDate_ = todaysDate_ + 66*Months;
        Schedule dates(todaysDate_, endDate_, Period(Semiannual),
                       calendar_, Following, Following, DateGeneration::Backward, false);
        rateTimes_ = std::vector<Time>(dates.size()-1);
        accruals_ = std::vector<Real>(rateTimes_.size()-1);
        dayCounter_ = SimpleDayCounter();
        for (Size i=1; i<dates.size(); ++i)
            rateTimes_[i-1] = dayCounter_.yearFraction(todaysDate_, dates[i]);
        for (Size i=1; i<rateTimes_.size(); ++i)
            accruals_[i-1] = rateTimes_[i] - rateTimes_[i-1];
        // Rates & displacement
        todaysForwards_ = std::vector<Rate>(accruals_.size());
        numberOfFactors_ = 3;
        alpha_ = 0.0;
        alphaMax_ = 1.0;
        alphaMin_ = -1.0;
        displacement_ = 0.0;
        for (Size i=0; i<todaysForwards_.size(); ++i) {
            // FLOATING_POINT_EXCEPTION
            todaysForwards_[i] = 0.03 + 0.0025*i;
            //    todaysForwards_[i] = 0.03;
        }
        LMMCurveState curveState_lmm(rateTimes_);
        curveState_lmm.setOnForwardRates(todaysForwards_);
        todaysSwaps_ = curveState_lmm.coterminalSwapRates();
        // Discounts
        todaysDiscounts_ = std::vector<DiscountFactor>(rateTimes_.size());
        todaysDiscounts_[0] = 0.95;
        for (Size i=1; i<rateTimes_.size(); ++i)
            todaysDiscounts_[i] = todaysDiscounts_[i-1] /
                (1.0+todaysForwards_[i-1]*accruals_[i-1]);
        //Volatility mktSwaptionVols[] = {
        //                        0.15541283,
        //                        0.18719678,
        //                        0.20890740,
        //                        0.22318179,
        //                        0.23212717,
        //                        0.23731450,
        //                        0.23988649,
        //                        0.24066384,
        //                        0.24023111,
        //                        0.23900189,
        //                        0.23726699,
        //                        0.23522952,
        //                        0.23303022,
        //                        0.23076564,
        //                        0.22850101,
        //                        0.22627951,
        //                        0.22412881,
        //                        0.22206569,
        //                        0.22009939
        //};
        //a = -0.0597;
        //b =  0.1677;
        //c =  0.5403;
        //d =  0.1710;
        a_ = 0.0;
        b_ = 0.17;
        c_ = 1.0;
        d_ = 0.10;
        Volatility mktCapletVols[] = {
            0.1640,
            0.1740,
            0.1840,
            0.1940,
            0.1840,
            0.1740,
            0.1640,
            0.1540,
            0.1440,
            0.1340376439125532
        };
        //swaptionDisplacedVols = std::vector<Volatility>(todaysSwaps.size());
        //swaptionVols = std::vector<Volatility>(todaysSwaps.size());
        //capletDisplacedVols = std::vector<Volatility>(todaysSwaps.size());
        capletVols_.resize(todaysSwaps_.size());
        for (Size i=0; i<todaysSwaps_.size(); i++) {
            //    swaptionDisplacedVols[i] = todaysSwaps[i]*mktSwaptionVols[i]/
            //                              (todaysSwaps[i]+displacement);
            //    swaptionVols[i]= mktSwaptionVols[i];
            //    capletDisplacedVols[i] = todaysForwards[i]*mktCapletVols[i]/
            //                            (todaysForwards[i]+displacement);
            capletVols_[i]= mktCapletVols[i];
        }
        // Cap/Floor Correlation
        longTermCorrelation_ = 0.5;
        beta_ = 0.2;
        measureOffset_ = 5;
        // Monte Carlo
        seed_ = 42;
#ifdef _DEBUG
        paths_ = 127;
        trainingPaths_ = 31;
#else
        paths_ = 32767; //262144-1; //; // 2^15-1
        trainingPaths_ = 8191; // 2^13-1
#endif
    }
const boost::shared_ptr<SequenceStatisticsInc> anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::simulate (const boost::shared_ptr< MarketModelEvolver > & evolver, const MarketModelMultiProduct & product)
Definition at line 220 of file marketmodel_smmcaplethomocalibration.cpp.
References QuantLib::AccountingEngine::multiplePathValues(), and QuantLib::MarketModelMultiProduct::numberOfProducts().
    {
        Size initialNumeraire = evolver->numeraires().front();
        Real initialNumeraireValue = todaysDiscounts_[initialNumeraire];
        AccountingEngine engine(evolver, product, initialNumeraireValue);
        boost::shared_ptr<SequenceStatisticsInc> stats(
                          new SequenceStatisticsInc(product.numberOfProducts()));
        engine.multiplePathValues(*stats, paths_);
        return stats;
    }
Variable Documentation
Real anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::a_
Definition at line 97 of file marketmodel_smmcaplethomocalibration.cpp.
std::vector<Real> anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::accruals_
Definition at line 86 of file marketmodel_smmcaplethomocalibration.cpp.
Real anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::alpha_
Definition at line 92 of file marketmodel_smmcaplethomocalibration.cpp.
Real anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::alphaMax_
Definition at line 92 of file marketmodel_smmcaplethomocalibration.cpp.
Real anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::alphaMin_
Definition at line 92 of file marketmodel_smmcaplethomocalibration.cpp.
Real anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::b_
Definition at line 97 of file marketmodel_smmcaplethomocalibration.cpp.
Real anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::beta_
Definition at line 98 of file marketmodel_smmcaplethomocalibration.cpp.
Real anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::c_
Definition at line 97 of file marketmodel_smmcaplethomocalibration.cpp.
Calendar anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::calendar_
Definition at line 87 of file marketmodel_smmcaplethomocalibration.cpp.
std::vector<Volatility> anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::capletDisplacedVols_
Definition at line 96 of file marketmodel_smmcaplethomocalibration.cpp.
std::vector<Volatility> anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::capletVols_
Definition at line 96 of file marketmodel_smmcaplethomocalibration.cpp.
std::vector<Real> anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::coterminalAnnuity_
Definition at line 90 of file marketmodel_smmcaplethomocalibration.cpp.
Real anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::d_
Definition at line 97 of file marketmodel_smmcaplethomocalibration.cpp.
DayCounter anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::dayCounter_
Definition at line 88 of file marketmodel_smmcaplethomocalibration.cpp.
Spread anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::displacement_
Definition at line 93 of file marketmodel_smmcaplethomocalibration.cpp.
Date anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::endDate_
Definition at line 84 of file marketmodel_smmcaplethomocalibration.cpp.
Real anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::longTermCorrelation_
Definition at line 98 of file marketmodel_smmcaplethomocalibration.cpp.
Size anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::measureOffset_
Definition at line 99 of file marketmodel_smmcaplethomocalibration.cpp.
Size anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::numberOfFactors_
Definition at line 91 of file marketmodel_smmcaplethomocalibration.cpp.
Size anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::paths_
Definition at line 101 of file marketmodel_smmcaplethomocalibration.cpp.
bool anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::printReport_ = false
Definition at line 102 of file marketmodel_smmcaplethomocalibration.cpp.
std::vector<Time> anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::rateTimes_
Definition at line 85 of file marketmodel_smmcaplethomocalibration.cpp.
unsigned long anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::seed_
Definition at line 100 of file marketmodel_smmcaplethomocalibration.cpp.
Date anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::startDate_
Definition at line 84 of file marketmodel_smmcaplethomocalibration.cpp.
std::vector<Volatility> anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::swaptionDisplacedVols_
Definition at line 95 of file marketmodel_smmcaplethomocalibration.cpp.
std::vector<Volatility> anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::swaptionVols_
Definition at line 95 of file marketmodel_smmcaplethomocalibration.cpp.
Date anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::todaysDate_
Definition at line 84 of file marketmodel_smmcaplethomocalibration.cpp.
std::vector<DiscountFactor> anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::todaysDiscounts_
Definition at line 94 of file marketmodel_smmcaplethomocalibration.cpp.
std::vector<Rate> anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::todaysForwards_
Definition at line 89 of file marketmodel_smmcaplethomocalibration.cpp.
std::vector<Rate> anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::todaysSwaps_
Definition at line 89 of file marketmodel_smmcaplethomocalibration.cpp.
Size anonymous_namespace{marketmodel_smmcaplethomocalibration.cpp}::trainingPaths_
Definition at line 101 of file marketmodel_smmcaplethomocalibration.cpp.