QuantLib: QuantLib::anonymous_namespace{pseudosqrt.cpp} Namespace Reference
QuantLib::anonymous_namespace{pseudosqrt.cpp} Namespace Reference
Classes
class HypersphereCostFunction
Functions
void checkSymmetry (const Matrix &matrix)
void normalizePseudoRoot (const Matrix &matrix, Matrix &pseudo)
const Disposable< Matrix > hypersphereOptimize (const Matrix &targetMatrix, const Matrix &currentRoot, const bool lowerDiagonal)
Real normInf (const Matrix &M)
const Disposable< Matrix > projectToUnitDiagonalMatrix (const Matrix &M)
const Disposable< Matrix > projectToPositiveSemidefiniteMatrix (Matrix &M)
const Disposable< Matrix > highamImplementation (const Matrix &A, const Size maxIterations, const Real &tolerance)
Function Documentation
void QuantLib::anonymous_namespace{pseudosqrt.cpp}::checkSymmetry (const Matrix & matrix)
Definition at line 34 of file pseudosqrt.cpp.
References QuantLib::close(), QuantLib::Matrix::columns(), QL_REQUIRE, and QuantLib::Matrix::rows().
Referenced by QuantLib::pseudoSqrt(), QuantLib::rankReducedSqrt(), and InterpolationTest::testSimmetricEndConditions().
{
            Size size = matrix.rows();
            QL_REQUIRE(size == matrix.columns(),
                       "non square matrix: " << size << " rows, " <<
                       matrix.columns() << " columns");
            for (Size i=0; i<size; ++i)
                for (Size j=0; j<i; ++j)
                    QL_REQUIRE(close(matrix[i][j], matrix[j][i]),
                               "non symmetric matrix: " <<
                               "[" << i << "][" << j << "]=" << matrix[i][j] <<
                               ", [" << j << "][" << i << "]=" << matrix[j][i]);
        }
const Disposable<Matrix> QuantLib::anonymous_namespace{pseudosqrt.cpp}::highamImplementation (const Matrix & A, const Size maxIterations, const Real & tolerance)
Definition at line 313 of file pseudosqrt.cpp.
References normInf(), projectToPositiveSemidefiniteMatrix(), projectToUnitDiagonalMatrix(), and QuantLib::Matrix::rows().
Referenced by QuantLib::pseudoSqrt(), and QuantLib::rankReducedSqrt().
{
            Size size = A.rows();
            Matrix R, Y(A), X(A), deltaS(size, size, 0.0);
            Matrix lastX(X);
            Matrix lastY(Y);
            for (Size i=0; i<maxIterations; ++i) {
                R = Y - deltaS;
                X = projectToPositiveSemidefiniteMatrix(R);
                deltaS = X - R;
                Y = projectToUnitDiagonalMatrix(X);
                // convergence test
                if (std::max(normInf(X-lastX)/normInf(X),
                        std::max(normInf(Y-lastY)/normInf(Y),
                                normInf(Y-X)/normInf(Y)))
                        <= tolerance)
                {
                    break;
                }
                lastX = X;
                lastY = Y;
            }
            // ensure we return a symmetric matrix
            for (Size i=0; i<size; ++i)
                for (Size j=0; j<i; ++j)
                    Y[i][j] = Y[j][i];
            return Y;
        }
const Disposable<Matrix> QuantLib::anonymous_namespace{pseudosqrt.cpp}::hypersphereOptimize (const Matrix & targetMatrix, const Matrix & currentRoot, const bool lowerDiagonal)
Definition at line 138 of file pseudosqrt.cpp.
References QuantLib::Matrix::begin(), QuantLib::CholeskyDecomposition(), QuantLib::Problem::currentValue(), QuantLib::Matrix::end(), QuantLib::LineSearchBasedMethod::minimize(), QuantLib::Matrix::rows(), and QuantLib::transpose().
Referenced by QuantLib::pseudoSqrt().
{
            Size i,j,k,size = targetMatrix.rows();
            Matrix result(currentRoot);
            Array variance(size, 0);
            for (i=0; i<size; i++){
                variance[i]=std::sqrt(targetMatrix[i][i]);
            }
            if (lowerDiagonal) {
                Matrix approxMatrix(result*transpose(result));
                result = CholeskyDecomposition(approxMatrix, true);
                for (i=0; i<size; i++) {
                    for (j=0; j<size; j++) {
                        result[i][j]/=std::sqrt(approxMatrix[i][i]);
                    }
                }
            } else {
                for (i=0; i<size; i++) {
                    for (j=0; j<size; j++) {
                        result[i][j]/=variance[i];
                    }
                }
            }
            ConjugateGradient optimize;
            EndCriteria endCriteria(100, 10, 1e-8, 1e-8, 1e-8);
            HypersphereCostFunction costFunction(targetMatrix, variance,
                                                 lowerDiagonal);
            NoConstraint constraint;
            // hypersphere vector optimization
            if (lowerDiagonal) {
                Array theta(size * (size-1)/2);
                const Real eps=1e-16;
                for (i=1; i<size; i++) {
                    for (j=0; j<i; j++) {
                        theta[i*(i-1)/2+j]=result[i][j];
                        if (theta[i*(i-1)/2+j]>1-eps)
                            theta[i*(i-1)/2+j]=1-eps;
                        if (theta[i*(i-1)/2+j]<-1+eps)
                            theta[i*(i-1)/2+j]=-1+eps;
                        for (k=0; k<j; k++) {
                            theta[i*(i-1)/2+j] /= std::sin(theta[i*(i-1)/2+k]);
                            if (theta[i*(i-1)/2+j]>1-eps)
                                theta[i*(i-1)/2+j]=1-eps;
                            if (theta[i*(i-1)/2+j]<-1+eps)
                                theta[i*(i-1)/2+j]=-1+eps;
                        }
                        theta[i*(i-1)/2+j] = std::acos(theta[i*(i-1)/2+j]);
                        if (j==i-1) {
                            if (result[i][i]<0)
                                theta[i*(i-1)/2+j]=-theta[i*(i-1)/2+j];
                        }
                    }
                }
                Problem p(costFunction, constraint, theta);
                optimize.minimize(p, endCriteria);
                theta = p.currentValue();
                std::fill(result.begin(),result.end(),1.0);
                for (i=0; i<size; i++) {
                    for (k=0; k<size; k++) {
                        if (k>i) {
                            result[i][k]=0;
                        } else {
                            for (j=0; j<=k; j++) {
                                if (j == k && k!=i)
                                    result[i][k] *=
                                        std::cos(theta[i*(i-1)/2+j]);
                                else if (j!=i)
                                    result[i][k] *=
                                        std::sin(theta[i*(i-1)/2+j]);
                            }
                        }
                    }
                }
            } else {
                Array theta(size * (size-1));
                const Real eps=1e-16;
                for (i=0; i<size; i++) {
                    for (j=0; j<size-1; j++) {
                        theta[j*size+i]=result[i][j];
                        if (theta[j*size+i]>1-eps)
                            theta[j*size+i]=1-eps;
                        if (theta[j*size+i]<-1+eps)
                            theta[j*size+i]=-1+eps;
                        for (k=0;k<j;k++) {
                            theta[j*size+i] /= std::sin(theta[k*size+i]);
                            if (theta[j*size+i]>1-eps)
                                theta[j*size+i]=1-eps;
                            if (theta[j*size+i]<-1+eps)
                                theta[j*size+i]=-1+eps;
                        }
                        theta[j*size+i] = std::acos(theta[j*size+i]);
                        if (j==size-2) {
                            if (result[i][j+1]<0)
                                theta[j*size+i]=-theta[j*size+i];
                        }
                    }
                }
                Problem p(costFunction, constraint, theta);
                optimize.minimize(p, endCriteria);
                theta=p.currentValue();
                std::fill(result.begin(),result.end(),1.0);
                for (i=0; i<size; i++) {
                    for (k=0; k<size; k++) {
                        for (j=0; j<=k; j++) {
                            if (j == k && k!=size-1)
                                result[i][k] *= std::cos(theta[j*size+i]);
                            else if (j!=size-1)
                                result[i][k] *= std::sin(theta[j*size+i]);
                        }
                    }
                }
            }
            for (i=0; i<size; i++) {
                for (j=0; j<size; j++) {
                    result[i][j]*=variance[i];
                }
            }
            return result;
        }
void QuantLib::anonymous_namespace{pseudosqrt.cpp}::normalizePseudoRoot (const Matrix & matrix, Matrix & pseudo)
Definition at line 47 of file pseudosqrt.cpp.
References QuantLib::Matrix::columns(), QuantLib::norm(), QL_REQUIRE, and QuantLib::Matrix::rows().
Referenced by QuantLib::pseudoSqrt(), and QuantLib::rankReducedSqrt().
{
            Size size = matrix.rows();
            QL_REQUIRE(size == pseudo.rows(),
                       "matrix/pseudo mismatch: matrix rows are " << size <<
                       " while pseudo rows are " << pseudo.columns());
            Size pseudoCols = pseudo.columns();
            // row normalization
            for (Size i=0; i<size; ++i) {
                Real norm = 0.0;
                for (Size j=0; j<pseudoCols; ++j)
                    norm += pseudo[i][j]*pseudo[i][j];
                if (norm>0.0) {
                    Real normAdj = std::sqrt(matrix[i][i]/norm);
                    for (Size j=0; j<pseudoCols; ++j)
                        pseudo[i][j] *= normAdj;
                }
            }
        }
Real QuantLib::anonymous_namespace{pseudosqrt.cpp}::normInf (const Matrix & M)
Definition at line 266 of file pseudosqrt.cpp.
References QuantLib::Matrix::columns(), QuantLib::norm(), and QuantLib::Matrix::rows().
Referenced by highamImplementation().
{
            Size rows = M.rows();
            Size cols = M.columns();
            Real norm = 0.0;
            for (Size i=0; i<rows; ++i) {
                Real colSum = 0.0;
                for (Size j=0; j<cols; ++j)
                    colSum += std::fabs(M[i][j]);
                norm = std::max(norm, colSum);
            }
            return norm;
        }
const Disposable<Matrix> QuantLib::anonymous_namespace{pseudosqrt.cpp}::projectToPositiveSemidefiniteMatrix (Matrix & M)
Definition at line 295 of file pseudosqrt.cpp.
References QuantLib::Matrix::columns(), QuantLib::SymmetricSchurDecomposition::eigenvalues(), QuantLib::SymmetricSchurDecomposition::eigenvectors(), QL_REQUIRE, QuantLib::Matrix::rows(), and QuantLib::transpose().
Referenced by highamImplementation().
{
            Size size = M.rows();
            QL_REQUIRE(size == M.columns(),
                       "matrix not square");
            Matrix diagonal(size, size, 0.0);
            SymmetricSchurDecomposition jd(M);
            for (Size i=0; i<size; ++i)
                diagonal[i][i] = std::max<Real>(jd.eigenvalues()[i], 0.0);
            Matrix result =
                jd.eigenvectors()*diagonal*transpose(jd.eigenvectors());
            return result;
        }
const Disposable<Matrix> QuantLib::anonymous_namespace{pseudosqrt.cpp}::projectToUnitDiagonalMatrix (const Matrix & M)
Definition at line 281 of file pseudosqrt.cpp.
References QuantLib::Matrix::columns(), QL_REQUIRE, and QuantLib::Matrix::rows().
Referenced by highamImplementation().
{
            Size size = M.rows();
            QL_REQUIRE(size == M.columns(),
                       "matrix not square");
            Matrix result(M);
            for (Size i=0; i<size; ++i)
                result[i][i] = 1.0;
            return result;
        }