QuantLib: anonymous_namespace{solvers.cpp} Namespace Reference
anonymous_namespace{solvers.cpp} Namespace Reference
Classes
class Foo
Functions
template<class S >
void test (const S &solver, const std::string &name)
Function Documentation
template<class S > void anonymous_namespace{solvers.cpp}::test (const S & solver, const std::string & name)
Definition at line 42 of file solvers.cpp.
References LENGTH.
Referenced by QuantLib::Garch11::costFunction(), init_unit_test_suite(), MatricesTest::testOrthogonalProjection(), Solver1DTest::testResults(), and RiskStatisticsTest::testResults().
{
        Real accuracy[] = { 1.0e-4, 1.0e-6, 1.0e-8 };
        Real expected = 1.0;
        for (Size i=0; i<LENGTH(accuracy); i++) {
            Real root = solver.solve(Foo(),accuracy[i],1.5,0.1);
            if (std::fabs(root-expected) > accuracy[i]) {
                BOOST_FAIL(name << " solver:\n"
                           << "    expected:   " << expected << "\n"
                           << "    calculated: " << root << "\n"
                           << "    accuracy:   " << accuracy[i]);
            }
            root = solver.solve(Foo(),accuracy[i],1.5,0.0,1.0);
            if (std::fabs(root-expected) > accuracy[i]) {
                BOOST_FAIL(name << " solver (bracketed):\n"
                           << "    expected:   " << expected << "\n"
                           << "    calculated: " << root << "\n"
                           << "    accuracy:   " << accuracy[i]);
            }
        }
    }