QuantLib: QuantLib::anonymous_namespace{sobolbrowniangenerator.cpp} Namespace Reference
QuantLib::anonymous_namespace{sobolbrowniangenerator.cpp} Namespace Reference
Functions
void fillByFactor (std::vector< std::vector< Size > > &M, Size factors, Size steps)
void fillByStep (std::vector< std::vector< Size > > &M, Size factors, Size steps)
void fillByDiagonal (std::vector< std::vector< Size > > &M, Size factors, Size steps)
Function Documentation
void QuantLib::anonymous_namespace{sobolbrowniangenerator.cpp}::fillByDiagonal (std::vector< std::vector< Size > > & M, Size factors, Size steps)
Definition at line 44 of file sobolbrowniangenerator.cpp.
Referenced by QuantLib::SobolBrownianGenerator::SobolBrownianGenerator().
{
            // starting position of the current diagonal
            Size i0 = 0, j0 = 0;
            // current position
            Size i=0, j=0;
            Size counter = 0;
            while (counter < factors*steps) {
                M[i][j] = counter++;
                if (i == 0 || j == steps-1) {
                    // we completed a diagonal and have to start a new one
                    if (i0 < factors-1) {
                        // we start the path of the next factor
                        i0 = i0+1;
                        j0 = 0;
                    } else {
                        // we move along the path of the last factor
                        i0 = factors-1;
                        j0 = j0+1;
                    }
                    i = i0;
                    j = j0;
                } else {
                    // we move along the diagonal
                    i = i-1;
                    j = j+1;
                }
            }
        }
void QuantLib::anonymous_namespace{sobolbrowniangenerator.cpp}::fillByFactor (std::vector< std::vector< Size > > & M, Size factors, Size steps)
Definition at line 27 of file sobolbrowniangenerator.cpp.
Referenced by QuantLib::SobolBrownianGenerator::SobolBrownianGenerator().
{
            Size counter = 0;
            for (Size i=0; i<factors; ++i)
                for (Size j=0; j<steps; ++j)
                    M[i][j] = counter++;
        }
void QuantLib::anonymous_namespace{sobolbrowniangenerator.cpp}::fillByStep (std::vector< std::vector< Size > > & M, Size factors, Size steps)
Definition at line 35 of file sobolbrowniangenerator.cpp.
Referenced by QuantLib::SobolBrownianGenerator::SobolBrownianGenerator().
{
            Size counter = 0;
            for (Size j=0; j<steps; ++j)
                for (Size i=0; i<factors; ++i)
                    M[i][j] = counter++;
        }