QuantLib: anonymous_namespace{hybridhestonhullwhiteprocess.cpp} Namespace Reference
anonymous_namespace{hybridhestonhullwhiteprocess.cpp} Namespace Reference
Classes
struct HestonModelData
struct HullWhiteModelData
struct SchemeData
struct VanillaOptionData
class HestonHullWhiteCorrelationConstraint
Functions
boost::shared_ptr< HestonProcess > makeHestonProcess (const HestonModelData &params)
boost::shared_ptr< VanillaOption > makeVanillaOption (const VanillaOptionData &params)
Variables
HestonModelData hestonModels []
HullWhiteModelData hullWhiteModels []
SchemeData schemes []
Function Documentation
boost::shared_ptr<HestonProcess> anonymous_namespace{hybridhestonhullwhiteprocess.cpp}::makeHestonProcess (const HestonModelData & params)
Definition at line 1015 of file hybridhestonhullwhiteprocess.cpp.
References anonymous_namespace{marketmodel.cpp}::dayCounter, QuantLib::flatRate(), anonymous_namespace{hybridhestonhullwhiteprocess.cpp}::HestonModelData::kappa, anonymous_namespace{hybridhestonhullwhiteprocess.cpp}::HestonModelData::q, anonymous_namespace{hybridhestonhullwhiteprocess.cpp}::HestonModelData::r, anonymous_namespace{hybridhestonhullwhiteprocess.cpp}::HestonModelData::rho, anonymous_namespace{hybridhestonhullwhiteprocess.cpp}::HestonModelData::sigma, anonymous_namespace{hybridhestonhullwhiteprocess.cpp}::HestonModelData::theta, and anonymous_namespace{hybridhestonhullwhiteprocess.cpp}::HestonModelData::v0.
Referenced by HybridHestonHullWhiteProcessTest::testBsmHullWhitePricing(), and HybridHestonHullWhiteProcessTest::testSpatialDiscretizatinError().
{
        Handle<Quote> spot(
                boost::shared_ptr<SimpleQuote>(new SimpleQuote(100)));
        DayCounter dayCounter = Actual365Fixed();
        Handle<YieldTermStructure> rTS(flatRate(params.r, dayCounter));
        Handle<YieldTermStructure> qTS(flatRate(params.q, dayCounter));
        return boost::shared_ptr<HestonProcess>(new HestonProcess(
                   rTS, qTS, spot, params.v0, params.kappa,
                   params.theta, params.sigma, params.rho));
    }
boost::shared_ptr<VanillaOption> anonymous_namespace{hybridhestonhullwhiteprocess.cpp}::makeVanillaOption (const VanillaOptionData & params)
Definition at line 1030 of file hybridhestonhullwhiteprocess.cpp.
References QuantLib::Days, QuantLib::Singleton< Settings >::instance(), anonymous_namespace{hybridhestonhullwhiteprocess.cpp}::VanillaOptionData::maturity, anonymous_namespace{hybridhestonhullwhiteprocess.cpp}::VanillaOptionData::optionType, and anonymous_namespace{hybridhestonhullwhiteprocess.cpp}::VanillaOptionData::strike.
Referenced by HybridHestonHullWhiteProcessTest::testBsmHullWhitePricing(), and HybridHestonHullWhiteProcessTest::testSpatialDiscretizatinError().
{
        Date maturity = Date(Settings::instance().evaluationDate())
                                          + Period(Size(params.maturity*365), Days);
        boost::shared_ptr<Exercise> exercise(new EuropeanExercise(maturity));
        boost::shared_ptr<StrikedTypePayoff> payoff(
                    new PlainVanillaPayoff(params.optionType, params.strike));
        return boost::shared_ptr<VanillaOption>(
                                          new VanillaOption(payoff, exercise));
    }
Variable Documentation
HestonModelData anonymous_namespace{hybridhestonhullwhiteprocess.cpp}::hestonModels[]
Initial value:
 {
        {"'t Hout case 1", 0.04, 1.5, 0.04, 0.3, -0.9, 0.025, 0.0},
        {"'t Hout case 2", 0.12, 3.0, 0.12, 0.04, 0.6, 0.01, 0.04},
        {"'t Hout case 3", 0.0707,0.6067, 0.0707, 0.2928, -0.7571, 0.03, 0.0},
        {"'t Hout case 4", 0.06, 2.5, 0.06, 0.5, -0.1, 0.0507, 0.0469},
        {"Ikonen-Toivanen", 0.0625, 5, 0.16, 0.9, 0.1, 0.1, 0.0},
        {"Kahl-Jaeckel", 0.16, 1.0, 0.16, 2.0, -0.8, 0.0, 0.0},
        {"Equity case", 0.07, 2.0, 0.04, 0.55, -0.8, 0.03, 0.035 },
        {"high correlation", 0.07, 1.0, 0.04, 0.55,  0.995, 0.02, 0.04 },
        {"low Vol-Of-Vol", 0.07, 1.0, 0.04, 0.001, -0.75, 0.04, 0.03 },
        {"kappaEqSigRho", 0.07, 0.4, 0.04, 0.5, 0.8, 0.03, 0.03 }
    }
Definition at line 965 of file hybridhestonhullwhiteprocess.cpp.
HullWhiteModelData anonymous_namespace{hybridhestonhullwhiteprocess.cpp}::hullWhiteModels[]
Initial value:
 {
        {"EUR-2003", 0.00883, 0.00631 }
    }
Definition at line 991 of file hybridhestonhullwhiteprocess.cpp.
Referenced by HybridHestonHullWhiteProcessTest::testBsmHullWhitePricing().
SchemeData anonymous_namespace{hybridhestonhullwhiteprocess.cpp}::schemes[]
Initial value:
 {
        { "HV2", FdmSchemeDesc::Hundsdorfer() },
        { "HV1", FdmSchemeDesc::ModifiedHundsdorfer() },
        { "CS" , FdmSchemeDesc::CraigSneyd() },
        { "MCS", FdmSchemeDesc::ModifiedCraigSneyd() },
        { "DS" , FdmSchemeDesc::Douglas() }
    }
Definition at line 1001 of file hybridhestonhullwhiteprocess.cpp.
Referenced by HybridHestonHullWhiteProcessTest::testBsmHullWhitePricing(), FdHestonTest::testFdmHestonConvergence(), and HybridHestonHullWhiteProcessTest::testSpatialDiscretizatinError().