QuantLib: anonymous_namespace{integralhestonvarianceoptionengine.cpp} Namespace Reference
anonymous_namespace{integralhestonvarianceoptionengine.cpp} Namespace Reference
Classes
struct payoff_adapter
Typedefs
typedef std::complex< double > Complex
Functions
double IvopOneDim (double eps, double chi, double theta, double rho, double v0, double eprice, double tau, double rtax)
double IvopTwoDim (double eps, double chi, double theta, double rho, double v0, double tau, double rtax, const boost::function< double(double)> &payoff)
Typedef Documentation
typedef std::complex<double> anonymous_namespace{integralhestonvarianceoptionengine.cpp}::Complex
Definition at line 52 of file integralhestonvarianceoptionengine.cpp.
Function Documentation
double anonymous_namespace{integralhestonvarianceoptionengine.cpp}::IvopOneDim (double eps, double chi, double theta, double rho, double v0, double eprice, double tau, double rtax)
Definition at line 54 of file integralhestonvarianceoptionengine.cpp.
References anonymous_namespace{marketmodel.cpp}::beta, anonymous_namespace{perturbativebarrieroptionengine.cpp}::ff(), QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow(), QL_ENSURE, and QL_FAIL.
Referenced by QuantLib::IntegralHestonVarianceOptionEngine::calculate().
    {
        double i0=0.0, s=0.0, ss=0.0;
        boost::scoped_array<double> xiv(new double[2048*2048+1]);
        double nris=0.0;
        int j=0,mm=0;
        double pi=0,pi2=0;
        double dstep=0;
        double option=0, impart=0;
        boost::scoped_array<Complex> ff(new Complex[2048*2048]);
        Complex xi;
        Complex ui,beta,zita,gamma,csum,vero;
        Complex contrib, caux, caux1,caux2,caux3;
        ui=Complex(0.0,1.0);
        /*
         **********************************************************
         **   i0: initial integrated variance i0=0
         **********************************************************
         */
        i0=0.0;
        s=2.0*chi*theta/(eps*eps)-1.0;
        s=s+1;
        /*
         *************************************************
         ** Start integration procedure
         *************************************************
         */
        pi= 3.14159265358979324;
        pi2=2.0*pi;
        s=2.0*chi*theta/(eps*eps)-1.0;
        /*
         ****************************************
         ** Note that s must be greater than zero
         ****************************************
         */
        if(s<=0)
        {
            QL_FAIL("this parameter must be greater than zero-> " << s);
        }
        ss=s+1;
        /*
         *************************************************
         ** Start integration procedure
         *************************************************
         **************************************************************
         ** The oscillatory integral that approximates the price of
         ** the realized variance option is computed using the method
         ** proposed by Bailey, Swarztrauber in the paper published in
         ** Siam Journal on Scientific Computing Vol 15(5) 1994
         ** p. 1105-1110
         **************************************************************
         **************************************************************
         ** dstep: real number, generally a power of two, that must be
         **        assigned to determine the grid of
         **        integration. Hint: dstep=256 or 512 (dstep<=2048)
         **************************************************************
         */
        dstep=256.0;
        nris=std::sqrt(pi2)/dstep;
        mm=(int)(pi2/(nris*nris));
        /*
         ******************************************
         **  Definition of the integration grid  **
         ******************************************
         */
        for (j=0;j<=mm-1;j++)
        {
            xiv[j+1]=(double)(j-mm/2)*nris;
        }
        for (j=0;j<=mm-1;j++)
        {
            xi=xiv[j+1];
            caux=chi*chi;
            caux1=2.0*eps*eps;
            caux1=caux1*xi;
            caux1=caux1*ui;
            caux2=caux1+caux;
            zita=0.5*std::sqrt(caux2);
            caux1=std::exp(-2.0*tau*zita);
            beta=0.5*chi+zita;
            beta=beta+caux1*(zita-0.5*chi);
            gamma=1.0-caux1;
            caux=-ss*tau;
            caux2=caux*(zita-0.5*chi);
            caux=ss*std::log(2.0*(zita/beta));
            caux3=-v0*ui*xi*(gamma/beta);
            caux=caux+caux3;
            caux=caux+caux2;
            ff[j+1]=std::exp(caux);
            if(std::sqrt(std::imag(xi)*std::imag(xi)+std::real(xi)*std::real(xi))>1.e-06)
            {
                contrib=-eprice/(ui*xi);
                caux=ui*xi;
                caux=caux*eprice;
                caux=std::exp(caux);
                caux=caux-1.0;
                caux2=ui*xi*ui*xi;
                contrib=contrib+caux/caux2;
            }
            else
            {
                contrib=eprice*eprice*0.5;
            }
            ff[j+1]=ff[j+1]*contrib;
        }
        csum=0.0;
        for (j=0;j<=mm-1;j++)
        {
            caux=std::pow(-1.0,j);
            caux2=-2.0*pi*(double)(mm*j)*0.5/(double)mm;
            caux3=ui*caux2;
            csum=csum+ff[j+1]*caux*std::exp(caux3);
        }
        csum=csum*std::sqrt(std::pow(-1.0,mm))*nris/pi2;
        vero=i0-eprice+theta*tau+(1.0-std::exp(-chi*tau))*(v0-theta)/chi;
        csum=csum+vero;
        option=std::exp(-rtax*tau)*std::real(csum);
        impart=std::imag(csum);
        QL_ENSURE(impart <= 1e-12,
                  "imaginary part option (must be zero) = " << impart);
        return option;
    }
double anonymous_namespace{integralhestonvarianceoptionengine.cpp}::IvopTwoDim (double eps, double chi, double theta, double rho, double v0, double tau, double rtax, const boost::function< double(double)> & payoff)
Definition at line 198 of file integralhestonvarianceoptionengine.cpp.
References anonymous_namespace{marketmodel.cpp}::beta, anonymous_namespace{perturbativebarrieroptionengine.cpp}::ff(), QuantLib::anonymous_namespace{analyticgjrgarchengine.cpp}::pow(), and QL_FAIL.
Referenced by QuantLib::IntegralHestonVarianceOptionEngine::calculate().
{
        double i0=0.0, s=0.0, ss=0.0;
        boost::scoped_array<double> xiv(new double[2048*2048+1]);
        boost::scoped_array<double> ivet(new double[2048*2048+1]);
        double nris=0.0;
        int j=0,mm=0,k=0;
        double pi=0,pi2=0;
        double dstep=0;
        double ip=0;
        double payoffval=0;
        double option=0/*, impart=0*/;
        double sumr=0,sumi=0;
        Complex dxi,z;
        boost::scoped_array<Complex> ff(new Complex[2048*2048]);
        Complex xi;
        Complex ui,beta,zita,gamma,csum,vero;
        Complex contrib, caux, caux1,caux2,caux3;
        ui=Complex(0.0,1.0);
        /*
         **********************************************************
         **   i0: initial integrated variance i0=0
         **********************************************************
         */
        i0=0.0;
        s=2.0*chi*theta/(eps*eps)-1.0;
        s=s+1;
        /*
         *************************************************
         ** Start integration procedure
         *************************************************
         */
        pi= 3.14159265358979324;
        pi2=2.0*pi;
        s=2.0*chi*theta/(eps*eps)-1.0;
        /*
         ****************************************
         ** Note that s must be greater than zero
         ****************************************
         */
        if(s<=0)
        {
            QL_FAIL("this parameter must be greater than zero-> " << s);
        }
        ss=s+1;
        /*
         *************************************************
         ** Start integration procedure
         *************************************************
         **************************************************************
         ** The oscillatory integral that approximates the price of
         ** the realized variance option is computed using the method
         ** proposed by Bailey, Swarztrauber in the paper published in
         ** Siam Journal on Scientific Computing Vol 15(5) 1994
         ** p. 1105-1110
         **************************************************************
         **************************************************************
         ** dstep: real number, generally a power of two that must be
         **        assigned to determine the grid of
         **        integration. Hint: dstep=256 or 512 (dstep<=2048)
         **************************************************************
         */
        dstep=64.0;
        nris=std::sqrt(pi2)/dstep;
        mm=(int)(pi2/(nris*nris));
        /*
         ******************************************
         **  Definition of the integration grid  **
         ******************************************
         */
        for (j=0;j<=mm-1;j++)
        {
            xiv[j+1]=(double)(j-mm/2)*nris;
            ivet[j+1]=(double)(j-mm/2)*pi2/((double)mm*nris);
        }
        for (j=0;j<=mm-1;j++)
        {
            xi=xiv[j+1];
            caux=chi*chi;
            caux1=2.0*eps*eps;
            caux1=caux1*xi;
            caux1=caux1*ui;
            caux2=caux1+caux;
            zita=0.5*std::sqrt(caux2);
            caux1=std::exp(-2.0*tau*zita);
            beta=0.5*chi+zita;
            beta=beta+caux1*(zita-0.5*chi);
            gamma=1.0-caux1;
            caux=-ss*tau;
            caux2=caux*(zita-0.5*chi);
            caux=ss*std::log(2.0*(zita/beta));
            caux3=-v0*ui*xi*(gamma/beta);
            caux=caux+caux3;
            caux=caux+caux2;
            ff[j+1]=std::exp(caux);
        }
        sumr=0.0;
        sumi=0.0;
        for (k=0;k<=mm-1;k++)
        {
            ip=i0-ivet[k+1];
            payoffval=payoff(ip);
            dxi=2.0*pi*(double)k/(double)mm*ui;
            csum=0.0;
            for (j=0;j<=mm-1;j++)
            {
                z=-(double)j*dxi;
                caux=std::pow(-1.0,j);
                csum=csum+ff[j+1]*caux*std::exp(z);
            }
            csum=csum*std::pow(-1.0,k)*nris/pi2;
            sumr=sumr+payoffval*std::real(csum);
            sumi=sumi+payoffval*std::imag(csum);
        }
        sumr=sumr*nris;
        sumi=sumi*nris;
        option=std::exp(-rtax*tau)*sumr;
        //impart=sumi;
        //QL_ENSURE(impart <= 1e-3,
        //          "imaginary part option (must be close to zero) = " << impart);
        return option;
    }