QuantLib: QuantLib::ForwardForwardMappings Namespace Reference
QuantLib::ForwardForwardMappings Namespace Reference
Functions
Disposable< Matrix > ForwardForwardJacobian (const CurveState &cs, Size multiplier, Size offset)
Disposable< Matrix > YMatrix (const CurveState &cs, const std::vector< Spread > &shortDisplacements, const std::vector< Spread > &longDisplacements, Size Multiplier, Size offset)
LMMCurveState RestrictCurveState (const CurveState &cs, Size multiplier, Size offSet)
Function Documentation
Disposable< Matrix > QuantLib::ForwardForwardMappings::ForwardForwardJacobian (const CurveState & cs, Size multiplier, Size offset)
Returns the dg[i]/df[j] jacobian between forward rates with tenor multipler and forward rates with tenor 1
Definition at line 29 of file forwardforwardmappings.cpp.
References QuantLib::CurveState::discountRatio(), QuantLib::CurveState::numberOfRates(), QL_REQUIRE, QuantLib::CurveState::rateTaus(), and QuantLib::CurveState::rateTimes().
Referenced by YMatrix().
        {
        Size n = cs.numberOfRates();
        QL_REQUIRE(offset < multiplier, "offset  must be less than period in"
            "  forward forward mappings");
        Size k = (n-offset)/multiplier;
        const std::vector<Time>& tau = cs.rateTaus();
        Matrix jacobian = Matrix(k, n, 0.0);
        Size m=offset;
        for (Size l=0; l < k; ++l)
            {
            Real df = cs.discountRatio(m,m+multiplier);
            Real bigTau = cs.rateTimes()[m+multiplier]
            -  cs.rateTimes()[m];
            for (Size r=0; r < multiplier; ++r, ++m)
                {
                Real value = df * tau[m]*cs.discountRatio(m+1,m)-1;
                value /= bigTau;
                jacobian[l][m]=-value;
                }
            }
        return jacobian;
        }
LMMCurveState QuantLib::ForwardForwardMappings::RestrictCurveState (const CurveState & cs, Size multiplier, Size offSet)
replaces curve state with curve state based on periodic subset of times
Definition at line 108 of file forwardforwardmappings.cpp.
References QuantLib::CurveState::discountRatio(), QuantLib::CurveState::numberOfRates(), QL_REQUIRE, QuantLib::CurveState::rateTimes(), and QuantLib::LMMCurveState::setOnDiscountRatios().
Referenced by QuantLib::FwdPeriodAdapter::FwdPeriodAdapter(), and MarketModelTest::testPeriodAdapter().
        {
           Size n = cs.numberOfRates();
           QL_REQUIRE(offset < multiplier, "offset  must be less than period in"
           "  forward forward mappings");
           Size k = (n-offset)/multiplier;
           std::vector<Time> times(k+1);
           std::vector<DiscountFactor> discRatios(k+1);
           for (Size i=0; i < k+1; ++i)
           {
               times[i] = cs.rateTimes()[i*multiplier+offset];
               discRatios[i] = cs.discountRatio(i*multiplier+offset,0);
           }
           LMMCurveState newState(times);
           newState.setOnDiscountRatios(discRatios);
           return newState;
        }
Disposable< Matrix > QuantLib::ForwardForwardMappings::YMatrix (const CurveState & cs, const std::vector< Spread > & shortDisplacements, const std::vector< Spread > & longDisplacements, Size Multiplier, Size offset)
Returns the Y matrix to switch base forward rates with tenor multipler and forward rates with tenor 1
Definition at line 64 of file forwardforwardmappings.cpp.
References QuantLib::CurveState::discountRatio(), ForwardForwardJacobian(), QuantLib::CurveState::forwardRate(), QuantLib::CurveState::numberOfRates(), QL_REQUIRE, and QuantLib::CurveState::rateTimes().
Referenced by QuantLib::FwdPeriodAdapter::FwdPeriodAdapter().
        {
        Size n = cs.numberOfRates();
        QL_REQUIRE(offset < multiplier, "offset  must be less than period in"
            "  forward forward mappings");
        Size k = (n-offset)/multiplier;
        QL_REQUIRE(shortDisplacements.size() == n , "shortDisplacements must be of size"
            " equal to number of rates");
        QL_REQUIRE(longDisplacements.size() == k , "longDisplacements must be of size"
            " equal to (number of rates minus offset) divided by multiplier");
        Matrix jacobian(ForwardForwardJacobian(cs,multiplier,offset));
        for (Size i=0; i < k ; ++i)
            {
            Real tau = cs.rateTimes()[(i+1)*multiplier+offset]
            -  cs.rateTimes()[i*multiplier+offset];
            Real longForward = (cs.discountRatio((i+1)*multiplier+offset,i*multiplier+offset)-1.0)
                /tau;
            Real longForwardDisplaced = longForward+ longDisplacements[i];
            for (Size j=0; j < n; ++j)
                {
                Real shortForward = cs.forwardRate(j);
                Real shortForwardDisplaced = shortForward+shortDisplacements[j];
                jacobian[i][j] *= shortForwardDisplaced/longForwardDisplaced;
                }
            }
        return jacobian;
        }