QuantLib: /home/deriversatile/QuantLib/QuantLibQt/test-suite/quantlibtestsuite.cpp File Reference
quantlibtestsuite.cpp File Reference
#include <ql/types.hpp>
#include <ql/settings.hpp>
#include <ql/version.hpp>
#include <boost/test/unit_test.hpp>
#include <boost/timer.hpp>
#include "utilities.hpp"
#include "americanoption.hpp"
#include "array.hpp"
#include "asianoptions.hpp"
#include "assetswap.hpp"
#include "autocovariances.hpp"
#include "barrieroption.hpp"
#include "basketoption.hpp"
#include "batesmodel.hpp"
#include "bermudanswaption.hpp"
#include "blackdeltacalculator.hpp"
#include "bonds.hpp"
#include "brownianbridge.hpp"
#include "calendars.hpp"
#include "capfloor.hpp"
#include "capflooredcoupon.hpp"
#include "cashflows.hpp"
#include "cdo.hpp"
#include "cdsoption.hpp"
#include "chooseroption.hpp"
#include "cliquetoption.hpp"
#include "cms.hpp"
#include "commodityunitofmeasure.hpp"
#include "compoundoption.hpp"
#include "convertiblebonds.hpp"
#include "covariance.hpp"
#include "creditdefaultswap.hpp"
#include "curvestates.hpp"
#include "dates.hpp"
#include "daycounters.hpp"
#include "defaultprobabilitycurves.hpp"
#include "digitalcoupon.hpp"
#include "digitaloption.hpp"
#include "distributions.hpp"
#include "dividendoption.hpp"
#include "europeanoption.hpp"
#include "everestoption.hpp"
#include "exchangerate.hpp"
#include "extendedtrees.hpp"
#include "factorial.hpp"
#include "fastfouriertransform.hpp"
#include "fdheston.hpp"
#include "fdmlinearop.hpp"
#include "forwardoption.hpp"
#include "gaussianquadratures.hpp"
#include "gjrgarchmodel.hpp"
#include "hestonmodel.hpp"
#include "himalayaoption.hpp"
#include "hybridhestonhullwhiteprocess.hpp"
#include "inflation.hpp"
#include "inflationcapfloor.hpp"
#include "inflationcapflooredcoupon.hpp"
#include "inflationcpicapfloor.hpp"
#include "inflationcpiswap.hpp"
#include "inflationvolatility.hpp"
#include "instruments.hpp"
#include "integrals.hpp"
#include "interestrates.hpp"
#include "interpolations.hpp"
#include "libormarketmodel.hpp"
#include "libormarketmodelprocess.hpp"
#include "linearleastsquaresregression.hpp"
#include "jumpdiffusion.hpp"
#include "lookbackoptions.hpp"
#include "lowdiscrepancysequences.hpp"
#include "margrabeoption.hpp"
#include "marketmodel.hpp"
#include "marketmodel_smmcapletalphacalibration.hpp"
#include "marketmodel_smmcapletcalibration.hpp"
#include "marketmodel_smmcaplethomocalibration.hpp"
#include "marketmodel_smm.hpp"
#include "marketmodel_cms.hpp"
#include "matrices.hpp"
#include "mclongstaffschwartzengine.hpp"
#include "mersennetwister.hpp"
#include "money.hpp"
#include "nthtodefault.hpp"
#include "operators.hpp"
#include "optimizers.hpp"
#include "optionletstripper.hpp"
#include "overnightindexedswap.hpp"
#include "pagodaoption.hpp"
#include "pathgenerator.hpp"
#include "period.hpp"
#include "piecewiseyieldcurve.hpp"
#include "quantooption.hpp"
#include "quotes.hpp"
#include "riskstats.hpp"
#include "rngtraits.hpp"
#include "rounding.hpp"
#include "sampledcurve.hpp"
#include "schedule.hpp"
#include "shortratemodels.hpp"
#include "solvers.hpp"
#include "spreadoption.hpp"
#include "swingoption.hpp"
#include "surface.hpp"
#include "stats.hpp"
#include "swap.hpp"
#include "swapforwardmappings.hpp"
#include "swaption.hpp"
#include "swaptionvolatilitycube.hpp"
#include "swaptionvolatilitymatrix.hpp"
#include "termstructures.hpp"
#include "timeseries.hpp"
#include "tqreigendecomposition.hpp"
#include "tracing.hpp"
#include "transformedgrid.hpp"
#include "variancegamma.hpp"
#include "varianceoption.hpp"
#include "varianceswaps.hpp"
#include "volatilitymodels.hpp"
#include "vpp.hpp"
#include "writerextensibleoption.hpp"
#include <iostream>
#include <iomanip>
Namespaces
namespace anonymous_namespace{quantlibtestsuite.cpp}
Functions
void anonymous_namespace{quantlibtestsuite.cpp}::startTimer ()
void anonymous_namespace{quantlibtestsuite.cpp}::stopTimer ()
void anonymous_namespace{quantlibtestsuite.cpp}::configure ()
test_suite * init_unit_test_suite (int, char *[])
Variables
boost::timer anonymous_namespace{quantlibtestsuite.cpp}::t
Function Documentation
test_suite* init_unit_test_suite (int , char * [])
Definition at line 206 of file quantlibtestsuite.cpp.
References anonymous_namespace{quantlibtestsuite.cpp}::configure(), QL_LIB_NAME, QL_VERSION, QUANTLIB_TEST_CASE, anonymous_namespace{quantlibbenchmark.cpp}::startTimer(), anonymous_namespace{quantlibbenchmark.cpp}::stopTimer(), EverestOptionTest::suite(), PagodaOptionTest::suite(), ChooserOptionTest::suite(), HimalayaOptionTest::suite(), CashFlowsTest::suite(), MargrabeOptionTest::suite(), ArrayTest::suite(), MarketModelSmmCapletAlphaCalibrationTest::suite(), MarketModelSmmCapletCalibrationTest::suite(), MersenneTwisterTest::suite(), OptimizersTest::suite(), RiskStatisticsTest::suite(), CdsOptionTest::suite(), SampledCurveTest::suite(), CdoTest::suite(), Solver1DTest::suite(), SpreadOptionTest::suite(), SurfaceTest::suite(), TracingTest::suite(), TransformedGridTest::suite(), CommodityUnitOfMeasureTest::suite(), VarianceGammaTest::suite(), VarianceOptionTest::suite(), VolatilityModelsTest::suite(), WriterExtensibleOptionTest::suite(), BermudanSwaptionTest::suite(), InstrumentTest::suite(), InterestRateTest::suite(), JumpDiffusionTest::suite(), LookbackOptionTest::suite(), BrownianBridgeTest::suite(), MCLongstaffSchwartzEngineTest::suite(), NthToDefaultTest::suite(), CapFlooredCouponTest::suite(), PathGeneratorTest::suite(), PeriodTest::suite(), VarianceSwapTest::suite(), FactorialTest::suite(), ScheduleTest::suite(), GJRGARCHModelTest::suite(), CompoundOptionTest::suite(), LinearLeastSquaresRegressionTest::suite(), MarketModelCmsTest::suite(), MarketModelSmmCapletHomoCalibrationTest::suite(), MoneyTest::suite(), AutocovariancesTest::suite(), FastFourierTransformTest::suite(), ShortRateModelTest::suite(), CmsTest::suite(), SwaptionVolatilityMatrixTest::suite(), TqrEigenDecompositionTest::suite(), TimeSeriesTest::suite(), InflationCapFloorTest::suite(), LiborMarketModelProcessTest::suite(), ConvertibleBondTest::suite(), DateTest::suite(), LiborMarketModelTest::suite(), DayCounterTest::suite(), CliquetOptionTest::suite(), InflationCapFlooredCouponTest::suite(), OperatorTest::suite(), CPISwapTest::suite(), OvernightIndexedSwapTest::suite(), ForwardOptionTest::suite(), InflationVolTest::suite(), StatisticsTest::suite(), SwapForwardMappingsTest::suite(), RngTraitsTest::suite(), BatesModelTest::suite(), CovarianceTest::suite(), BlackDeltaCalculatorTest::suite(), CreditDefaultSwapTest::suite(), CurveStatesTest::suite(), ExchangeRateTest::suite(), InflationTest::suite(), OptionletStripperTest::suite(), BarrierOptionTest::suite(), BasketOptionTest::suite(), GaussianQuadraturesTest::suite(), VPPTest::suite(), SwingOptionTest::suite(), RoundingTest::suite(), QuoteTest::suite(), DistributionTest::suite(), SwapTest::suite(), IntegralTest::suite(), TermStructureTest::suite(), ExtendedTreesTest::suite(), SwaptionTest::suite(), SwaptionVolatilityCubeTest::suite(), FdHestonTest::suite(), BondTest::suite(), InflationCPICapFloorTest::suite(), CapFloorTest::suite(), QuantoOptionTest::suite(), AmericanOptionTest::suite(), DefaultProbabilityCurveTest::suite(), DigitalCouponTest::suite(), AssetSwapTest::suite(), DigitalOptionTest::suite(), DividendOptionTest::suite(), MatricesTest::suite(), AsianOptionTest::suite(), HybridHestonHullWhiteProcessTest::suite(), HestonModelTest::suite(), FdmLinearOpTest::suite(), MarketModelSmmTest::suite(), MarketModelTest::suite(), EuropeanOptionTest::suite(), InterpolationTest::suite(), LowDiscrepancyTest::suite(), PiecewiseYieldCurveTest::suite(), CalendarTest::suite(), and anonymous_namespace{solvers.cpp}::test().
{
    std::string header =
        " Testing "
            #ifdef BOOST_MSVC
            QL_LIB_NAME
            #else
            "QuantLib " QL_VERSION
            #endif
        "\n  QL_NEGATIVE_RATES "
            #ifdef QL_NEGATIVE_RATES
            "       defined"
            #else
            "     undefined"
            #endif
        "\n  QL_EXTRA_SAFETY_CHECKS "
            #ifdef QL_EXTRA_SAFETY_CHECKS
            "  defined"
            #else
            "undefined"
            #endif
        "\n  QL_DISABLE_DEPRECATED "
            #ifdef QL_DISABLE_DEPRECATED
            "   defined"
            #else
            " undefined"
            #endif
        "\n  QL_USE_INDEXED_COUPON "
            #ifdef QL_USE_INDEXED_COUPON
            "   defined"
            #else
            " undefined"
            #endif
         ;
    std::string rule = std::string(35, '=');
    BOOST_MESSAGE(rule);
    BOOST_MESSAGE(header);
    BOOST_MESSAGE(rule);
    test_suite* test = BOOST_TEST_SUITE("QuantLib test suite");
    test->add(QUANTLIB_TEST_CASE(startTimer));
    test->add(QUANTLIB_TEST_CASE(configure));
    test->add(AmericanOptionTest::suite());
    test->add(ArrayTest::suite());
    test->add(AsianOptionTest::suite());
    test->add(AssetSwapTest::suite()); // fails with QL_USE_INDEXED_COUPON
    test->add(AutocovariancesTest::suite());
    test->add(BarrierOptionTest::suite());
    test->add(BasketOptionTest::suite());
    test->add(BatesModelTest::suite());
    test->add(BermudanSwaptionTest::suite());
    test->add(BlackDeltaCalculatorTest::suite());
    test->add(BondTest::suite());
    test->add(BrownianBridgeTest::suite());
    test->add(CalendarTest::suite());
    test->add(CapFloorTest::suite());
    test->add(CapFlooredCouponTest::suite());
    test->add(CashFlowsTest::suite());
    test->add(CdsOptionTest::suite());
    test->add(CdoTest::suite());
    test->add(ChooserOptionTest::suite());
    test->add(CliquetOptionTest::suite());
    test->add(CmsTest::suite());
    test->add(CommodityUnitOfMeasureTest::suite());
    test->add(CompoundOptionTest::suite());
    test->add(ConvertibleBondTest::suite());
    test->add(CovarianceTest::suite());
    test->add(CreditDefaultSwapTest::suite());
    test->add(CurveStatesTest::suite());
    test->add(DateTest::suite());
    test->add(DayCounterTest::suite());
    test->add(DefaultProbabilityCurveTest::suite());
    test->add(DigitalCouponTest::suite()); // might fail with QL_USE_INDEXED_COUPON
    test->add(DigitalOptionTest::suite());
    test->add(DistributionTest::suite());
    test->add(DividendOptionTest::suite());
    test->add(EuropeanOptionTest::suite());
    test->add(EverestOptionTest::suite());
    test->add(ExchangeRateTest::suite());
    test->add(ExtendedTreesTest::suite());
    test->add(FactorialTest::suite());
    test->add(FastFourierTransformTest::suite());
    test->add(FdHestonTest::suite());
    test->add(FdmLinearOpTest::suite());
    test->add(ForwardOptionTest::suite());
    test->add(GaussianQuadraturesTest::suite());
    test->add(GJRGARCHModelTest::suite());
    test->add(HestonModelTest::suite());
    test->add(HimalayaOptionTest::suite());
    test->add(HybridHestonHullWhiteProcessTest::suite());
    test->add(InflationTest::suite());                  // in general inflation & tests
    test->add(InflationCapFloorTest::suite());          // use indexed coupons, i.e.
    test->add(InflationCapFlooredCouponTest::suite());  // QL_USE_INDEXED_COUPON has no effect
    test->add(CPISwapTest::suite());                    //
    test->add(InflationCPICapFloorTest::suite());       //
    test->add(InflationVolTest::suite());               //
    test->add(InstrumentTest::suite());
    test->add(IntegralTest::suite());
    test->add(InterestRateTest::suite());
    test->add(InterpolationTest::suite());
    test->add(JumpDiffusionTest::suite());
    test->add(LinearLeastSquaresRegressionTest::suite());
    test->add(LookbackOptionTest::suite());
    test->add(LowDiscrepancyTest::suite());
    test->add(MargrabeOptionTest::suite());
    test->add(MarketModelTest::suite());
    test->add(MarketModelCmsTest::suite());
    test->add(MarketModelSmmTest::suite());
    test->add(MarketModelSmmCapletAlphaCalibrationTest::suite());
    test->add(MarketModelSmmCapletCalibrationTest::suite());
    test->add(MarketModelSmmCapletHomoCalibrationTest::suite());
    test->add(MatricesTest::suite());
    test->add(MCLongstaffSchwartzEngineTest::suite());
    test->add(MersenneTwisterTest::suite());
    test->add(MoneyTest::suite());
    test->add(NthToDefaultTest::suite());
    test->add(OperatorTest::suite());
    test->add(OptimizersTest::suite());
    test->add(OptionletStripperTest::suite());
    test->add(OvernightIndexedSwapTest::suite());
    test->add(PagodaOptionTest::suite());
    test->add(PathGeneratorTest::suite());
    test->add(PeriodTest::suite());
    test->add(PiecewiseYieldCurveTest::suite());
    test->add(QuantoOptionTest::suite());
    test->add(QuoteTest::suite());
    test->add(RiskStatisticsTest::suite());
    test->add(RngTraitsTest::suite());
    test->add(RoundingTest::suite());
    test->add(SampledCurveTest::suite());
    test->add(ScheduleTest::suite());
    test->add(ShortRateModelTest::suite()); // fails with QL_USE_INDEXED_COUPON
    test->add(Solver1DTest::suite());
    test->add(SpreadOptionTest::suite());
    test->add(SwingOptionTest::suite());
    test->add(StatisticsTest::suite());
    test->add(SurfaceTest::suite());
    test->add(SwapTest::suite());
    test->add(SwapForwardMappingsTest::suite());
    test->add(SwaptionTest::suite());
    test->add(SwaptionVolatilityCubeTest::suite());
    test->add(SwaptionVolatilityMatrixTest::suite());
    test->add(TermStructureTest::suite());
    test->add(TimeSeriesTest::suite());
    test->add(TqrEigenDecompositionTest::suite());
    test->add(TracingTest::suite());
    test->add(TransformedGridTest::suite());
    test->add(VarianceGammaTest::suite());
    test->add(VarianceOptionTest::suite());
    test->add(VarianceSwapTest::suite());
    test->add(VolatilityModelsTest::suite());
    test->add(VPPTest::suite());
    test->add(WriterExtensibleOptionTest::suite());
    //tests for deprecated classes
    test->add(LiborMarketModelTest::suite());
    test->add(LiborMarketModelProcessTest::suite());
    test->add(QUANTLIB_TEST_CASE(stopTimer));
    return test;
}