QuantLib: /home/deriversatile/QuantLib/QuantLibQt/test-suite/quantlibbenchmark.cpp File Reference
quantlibbenchmark.cpp File Reference
#include <ql/types.hpp>
#include <ql/version.hpp>
#include <boost/test/unit_test.hpp>
#include <boost/timer.hpp>
#include <iostream>
#include <iomanip>
#include <list>
#include <string>
#include "utilities.hpp"
#include "americanoption.hpp"
#include "asianoptions.hpp"
#include "barrieroption.hpp"
#include "basketoption.hpp"
#include "batesmodel.hpp"
#include "convertiblebonds.hpp"
#include "digitaloption.hpp"
#include "dividendoption.hpp"
#include "europeanoption.hpp"
#include "fdheston.hpp"
#include "hestonmodel.hpp"
#include "interpolations.hpp"
#include "jumpdiffusion.hpp"
#include "marketmodel_smm.hpp"
#include "marketmodel_cms.hpp"
#include "lowdiscrepancysequences.hpp"
#include "quantooption.hpp"
#include "riskstats.hpp"
#include "shortratemodels.hpp"
Classes
class anonymous_namespace{quantlibbenchmark.cpp}::Benchmark
Namespaces
namespace anonymous_namespace{quantlibbenchmark.cpp}
Functions
void anonymous_namespace{quantlibbenchmark.cpp}::startTimer ()
void anonymous_namespace{quantlibbenchmark.cpp}::stopTimer ()
void anonymous_namespace{quantlibbenchmark.cpp}::printResults ()
test_suite * init_unit_test_suite (int, char *[])
Variables
boost::timer anonymous_namespace{quantlibbenchmark.cpp}::t
std::list< double > anonymous_namespace{quantlibbenchmark.cpp}::runTimes
std::list< Benchmark > anonymous_namespace{quantlibbenchmark.cpp}::bm
Function Documentation
test_suite* init_unit_test_suite (int , char * [])
Definition at line 222 of file quantlibbenchmark.cpp.
References anonymous_namespace{quantlibbenchmark.cpp}::bm, anonymous_namespace{quantlibbenchmark.cpp}::printResults(), QUANTLIB_TEST_CASE, anonymous_namespace{quantlibbenchmark.cpp}::startTimer(), anonymous_namespace{quantlibbenchmark.cpp}::stopTimer(), anonymous_namespace{solvers.cpp}::test(), BarrierOptionTest::testBabsiriValues(), ConvertibleBondTest::testBond(), HestonModelTest::testDAXCalibration(), BatesModelTest::testDAXCalibration(), BasketOptionTest::testEuroTwoValues(), AmericanOptionTest::testFdAmericanGreeks(), DividendOptionTest::testFdAmericanGreeks(), EuropeanOptionTest::testFdEngines(), DividendOptionTest::testFdEuropeanGreeks(), FdHestonTest::testFdmHestonAmerican(), AmericanOptionTest::testFdShoutGreeks(), QuantoOptionTest::testForwardGreeks(), JumpDiffusionTest::testGreeks(), EuropeanOptionTest::testImpliedVol(), DigitalOptionTest::testMCCashAtHit(), AsianOptionTest::testMCDiscreteArithmeticAveragePrice(), EuropeanOptionTest::testMcEngines(), LowDiscrepancyTest::testMersenneTwisterDiscrepancy(), MarketModelCmsTest::testMultiStepCmSwapsAndSwaptions(), MarketModelSmmTest::testMultiStepCoterminalSwapsAndSwaptions(), BasketOptionTest::testOddSamples(), EuropeanOptionTest::testPriceCurve(), RiskStatisticsTest::testResults(), InterpolationTest::testSabrInterpolation(), ShortRateModelTest::testSwaps(), and BasketOptionTest::testTavellaValues().
{
    bm.push_back(Benchmark("AmericanOption::FdAmericanGreeks",
        &AmericanOptionTest::testFdAmericanGreeks, 518.31));
    bm.push_back(Benchmark("AmericanOption::FdShoutGreeks",
        &AmericanOptionTest::testFdShoutGreeks, 546.58));
    bm.push_back(Benchmark("AsianOption::MCArithmeticAveragePrice",
        &AsianOptionTest::testMCDiscreteArithmeticAveragePrice, 5186.13));
    bm.push_back(Benchmark("BarrierOption::BabsiriValues",
        &BarrierOptionTest::testBabsiriValues, 880.8));
    bm.push_back(Benchmark("BasketOption::EuroTwoValues",
        &BasketOptionTest::testEuroTwoValues, 340.04));
    bm.push_back(Benchmark("BasketOption::TavellaValues",
        &BasketOptionTest::testTavellaValues, 933.80));
    bm.push_back(Benchmark("BasketOption::OddSamples",
        &BasketOptionTest::testOddSamples, 642.46));
    bm.push_back(Benchmark("BatesModel::DAXCalibration",
        &BatesModelTest::testDAXCalibration, 1993.35));
    bm.push_back(Benchmark("ConvertibleBondTest::testBond",
        &ConvertibleBondTest::testBond, 159.85));
    bm.push_back(Benchmark("DigitalOption::MCCashAtHit",
        &DigitalOptionTest::testMCCashAtHit,995.87));
    bm.push_back(Benchmark("DividendOption::FdEuropeanGreeks",
        &DividendOptionTest::testFdEuropeanGreeks, 949.52));
    bm.push_back(Benchmark("DividendOption::FdAmericanGreeks",
        &DividendOptionTest::testFdAmericanGreeks, 1113.74));
    bm.push_back(Benchmark("EuropeanOption::FdMcEngines",
        &EuropeanOptionTest::testMcEngines, 1988.63));
    bm.push_back(Benchmark("EuropeanOption::ImpliedVol",
        &EuropeanOptionTest::testImpliedVol, 131.51));
    bm.push_back(Benchmark("EuropeanOption::FdEngines",
        &EuropeanOptionTest::testFdEngines, 148.43));
    bm.push_back(Benchmark("EuropeanOption::PriceCurve",
        &EuropeanOptionTest::testPriceCurve, 414.76));
    bm.push_back(Benchmark("FdHestonTest::testFdmHestonAmerican",
        &FdHestonTest::testFdmHestonAmerican, 234.21));
    bm.push_back(Benchmark("HestonModel::DAXCalibration",
        &HestonModelTest::testDAXCalibration, 555.19));
    bm.push_back(Benchmark("InterpolationTest::testSabrInterpolation",
        &InterpolationTest::testSabrInterpolation, 2266.06));
    bm.push_back(Benchmark("JumpDiffusion::Greeks",
        &JumpDiffusionTest::testGreeks, 433.77));
    bm.push_back(Benchmark("MarketModelCmsTest::testCmSwapsSwaptions",
        &MarketModelCmsTest::testMultiStepCmSwapsAndSwaptions,
        11497.73));
    bm.push_back(Benchmark("MarketModelSmmTest::testMultiSmmSwaptions",
        &MarketModelSmmTest::testMultiStepCoterminalSwapsAndSwaptions,
        11244.95));
    bm.push_back(Benchmark("QuantoOption::ForwardGreeks",
        &QuantoOptionTest::testForwardGreeks, 90.98));
    bm.push_back(Benchmark("RandomNumber::MersenneTwisterDescrepancy",
        &LowDiscrepancyTest::testMersenneTwisterDiscrepancy, 951.98));
    bm.push_back(Benchmark("RiskStatistics::Results",
        &RiskStatisticsTest::testResults, 300.28));
    bm.push_back(Benchmark("ShortRateModel::Swaps",
        &ShortRateModelTest::testSwaps, 454.73));
    test_suite* test = BOOST_TEST_SUITE("QuantLib benchmark suite");
    for (std::list<Benchmark>::const_iterator iter = bm.begin();
         iter != bm.end(); ++iter) {
        test->add(QUANTLIB_TEST_CASE(startTimer));
        test->add(iter->getTestCase());
        test->add(QUANTLIB_TEST_CASE(stopTimer));
    }
    test->add(QUANTLIB_TEST_CASE(printResults));
    return test;
}