QuantLib: anonymous_namespace{inflationcapfloor.cpp}::CommonVars Struct Reference
anonymous_namespace{inflationcapfloor.cpp}::CommonVars Struct Reference
Public Member Functions
CommonVars ()
Leg makeYoYLeg (const Date &startDate, Integer length)
boost::shared_ptr< PricingEngine > makeEngine (Volatility volatility, Size which)
boost::shared_ptr
< YoYInflationCapFloor > makeYoYCapFloor (YoYInflationCapFloor::Type type, const Leg &leg, Rate strike, Volatility volatility, Size which)
Public Attributes
Frequency frequency
std::vector< Real > nominals
Calendar calendar
BusinessDayConvention convention
Natural fixingDays
Date evaluationDate
Natural settlementDays
Date settlement
Period observationLag
DayCounter dc
boost::shared_ptr< YYUKRPIr > iir
RelinkableHandle
< YieldTermStructure > nominalTS
boost::shared_ptr
< YoYInflationTermStructure > yoyTS
RelinkableHandle
< YoYInflationTermStructure > hy
SavedSettings backup
Detailed Description
Definition at line 85 of file inflationcapfloor.cpp.
Constructor & Destructor Documentation
anonymous_namespace{inflationcapfloor.cpp}::CommonVars::CommonVars () [inline]
Definition at line 109 of file inflationcapfloor.cpp.
References QuantLib::Calendar::adjust(), QuantLib::Calendar::advance(), QuantLib::Annual, QuantLib::August, anonymous_namespace{marketmodel.cpp}::calendar, QuantLib::Days, QuantLib::Settings::evaluationDate(), QuantLib::MakeSchedule::from(), QuantLib::Singleton< Settings >::instance(), QuantLib::January, LENGTH, anonymous_namespace{inflation.cpp}::makeHelpers(), QuantLib::ModifiedFollowing, QuantLib::Months, QuantLib::Schedule::size(), QuantLib::MakeSchedule::to(), QuantLib::MakeSchedule::withCalendar(), QuantLib::MakeSchedule::withConvention(), and QuantLib::MakeSchedule::withTenor().
                     {
            // option variables
            nominals = std::vector<Real>(1,1000000);
            frequency = Annual;
            // usual setup
            calendar = UnitedKingdom();
            convention = ModifiedFollowing;
            Date today(13, August, 2007);
            evaluationDate = calendar.adjust(today);
            Settings::instance().evaluationDate() = evaluationDate;
            settlementDays = 0;
            fixingDays = 0;
            settlement = calendar.advance(today,settlementDays,Days);
            dc = Thirty360();
            // yoy index
            //      fixing data
            Date from(1, January, 2005);
            Date to(13, August, 2007);
            Schedule rpiSchedule = MakeSchedule().from(from).to(to)
            .withTenor(1*Months)
            .withCalendar(UnitedKingdom())
            .withConvention(ModifiedFollowing);
            Real fixData[] = { 189.9, 189.9, 189.6, 190.5, 191.6, 192.0,
                192.2, 192.2, 192.6, 193.1, 193.3, 193.6,
                194.1, 193.4, 194.2, 195.0, 196.5, 197.7,
                198.5, 198.5, 199.2, 200.1, 200.4, 201.1,
                202.7, 201.6, 203.1, 204.4, 205.4, 206.2,
                207.3, -999.0, -999 };
            // link from yoy index to yoy TS
            bool interp = false;
            iir = boost::shared_ptr<YYUKRPIr>(new YYUKRPIr(interp, hy));
            for (Size i=0; i<rpiSchedule.size();i++) {
                iir->addFixing(rpiSchedule[i], fixData[i]);
            }
            boost::shared_ptr<YieldTermStructure> nominalFF(
                new FlatForward(evaluationDate, 0.05, ActualActual()));
            nominalTS.linkTo(nominalFF);
            // now build the YoY inflation curve
            Period observationLag = Period(2,Months);
            Datum yyData[] = {
                { Date(13, August, 2008), 2.95 },
                { Date(13, August, 2009), 2.95 },
                { Date(13, August, 2010), 2.93 },
                { Date(15, August, 2011), 2.955 },
                { Date(13, August, 2012), 2.945 },
                { Date(13, August, 2013), 2.985 },
                { Date(13, August, 2014), 3.01 },
                { Date(13, August, 2015), 3.035 },
                { Date(13, August, 2016), 3.055 },  // note that
                { Date(13, August, 2017), 3.075 },  // some dates will be on
                { Date(13, August, 2019), 3.105 },  // holidays but the payment
                { Date(15, August, 2022), 3.135 },  // calendar will roll them
                { Date(13, August, 2027), 3.155 },
                { Date(13, August, 2032), 3.145 },
                { Date(13, August, 2037), 3.145 }
            };
            // now build the helpers ...
            std::vector<boost::shared_ptr<BootstrapHelper<YoYInflationTermStructure> > > helpers =
            makeHelpers<YoYInflationTermStructure,YearOnYearInflationSwapHelper,
            YoYInflationIndex>(yyData, LENGTH(yyData), iir,
                               observationLag,
                               calendar, convention, dc);
            Rate baseYYRate = yyData[0].rate/100.0;
            boost::shared_ptr<PiecewiseYoYInflationCurve<Linear> > pYYTS(
                new PiecewiseYoYInflationCurve<Linear>(
                        evaluationDate, calendar, dc, observationLag,
                        iir->frequency(),iir->interpolated(), baseYYRate,
                        Handle<YieldTermStructure>(nominalTS), helpers));
            pYYTS->recalculate();
            yoyTS = boost::dynamic_pointer_cast<YoYInflationTermStructure>(pYYTS);
            // make sure that the index has the latest yoy term structure
            hy.linkTo(pYYTS);
        }
Member Function Documentation
boost::shared_ptr<PricingEngine> anonymous_namespace{inflationcapfloor.cpp}::CommonVars::makeEngine (Volatility volatility, Size which) [inline]
Definition at line 206 of file inflationcapfloor.cpp.
References anonymous_namespace{marketmodel.cpp}::calendar, and QL_FAIL.
{
            boost::shared_ptr<YoYInflationIndex>
            yyii = boost::dynamic_pointer_cast<YoYInflationIndex>(iir);
            Handle<YoYOptionletVolatilitySurface>
                vol(boost::shared_ptr<ConstantYoYOptionletVolatility>(
                    new ConstantYoYOptionletVolatility(volatility,
                                                       settlementDays,
                                                       calendar,
                                                       convention,
                                                       dc,
                                                       observationLag,
                                                       frequency,
                                                       iir->interpolated())));
            switch (which) {
                case 0:
                    return boost::shared_ptr<PricingEngine>(
                            new YoYInflationBlackCapFloorEngine(iir, vol));
                    break;
                case 1:
                    return boost::shared_ptr<PricingEngine>(
                            new YoYInflationUnitDisplacedBlackCapFloorEngine(iir, vol));
                    break;
                case 2:
                    return boost::shared_ptr<PricingEngine>(
                            new YoYInflationBachelierCapFloorEngine(iir, vol));
                    break;
                default:
                    BOOST_FAIL("unknown engine request: which = "<<which
                               <<"should be 0=Black,1=DD,2=Bachelier");
                    break;
            }
            // make compiler happy
            QL_FAIL("never get here - no engine resolution");
        }
boost::shared_ptr<YoYInflationCapFloor> anonymous_namespace{inflationcapfloor.cpp}::CommonVars::makeYoYCapFloor (YoYInflationCapFloor::Type type, const Leg & leg, Rate strike, Volatility volatility, Size which) [inline]
Definition at line 247 of file inflationcapfloor.cpp.
References QuantLib::YoYInflationCapFloor::Cap, QuantLib::YoYInflationCapFloor::Floor, and QL_FAIL.
{
            boost::shared_ptr<YoYInflationCapFloor> result;
            switch (type) {
                case YoYInflationCapFloor::Cap:
                    result = boost::shared_ptr<YoYInflationCapFloor>(
                        new YoYInflationCap(leg, std::vector<Rate>(1, strike)));
                    break;
                case YoYInflationCapFloor::Floor:
                    result = boost::shared_ptr<YoYInflationCapFloor>(
                        new YoYInflationFloor(leg, std::vector<Rate>(1, strike)));
                    break;
                default:
                    QL_FAIL("unknown YoYInflation cap/floor type");
            }
            result->setPricingEngine(makeEngine(volatility, which));
            return result;
        }
Leg anonymous_namespace{inflationcapfloor.cpp}::CommonVars::makeYoYLeg (const Date & startDate, Integer length) [inline]
Definition at line 192 of file inflationcapfloor.cpp.
References QuantLib::Calendar::advance(), anonymous_namespace{marketmodel.cpp}::calendar, anonymous_namespace{marketmodel.cpp}::endDate, QuantLib::DateGeneration::Forward, QuantLib::Unadjusted, QuantLib::yoyInflationLeg::withNotionals(), QuantLib::yoyInflationLeg::withPaymentAdjustment(), QuantLib::yoyInflationLeg::withPaymentDayCounter(), and QuantLib::Years.
{
            boost::shared_ptr<YoYInflationIndex> ii =
                boost::dynamic_pointer_cast<YoYInflationIndex>(iir);
            Date endDate = calendar.advance(startDate,length*Years,Unadjusted);
            Schedule schedule(startDate, endDate, Period(frequency), calendar,
                              Unadjusted,Unadjusted,// ref periods & acc periods
                              DateGeneration::Forward, false);
            return yoyInflationLeg(schedule, calendar, ii, observationLag)
            .withNotionals(nominals)
            .withPaymentDayCounter(dc)
            .withPaymentAdjustment(convention);
        }
Member Data Documentation
SavedSettings anonymous_namespace{inflationcapfloor.cpp}::CommonVars::backup
Definition at line 106 of file inflationcapfloor.cpp.
Calendar anonymous_namespace{inflationcapfloor.cpp}::CommonVars::calendar
Definition at line 90 of file inflationcapfloor.cpp.
BusinessDayConvention anonymous_namespace{inflationcapfloor.cpp}::CommonVars::convention
Definition at line 91 of file inflationcapfloor.cpp.
DayCounter anonymous_namespace{inflationcapfloor.cpp}::CommonVars::dc
Definition at line 97 of file inflationcapfloor.cpp.
Date anonymous_namespace{inflationcapfloor.cpp}::CommonVars::evaluationDate
Definition at line 93 of file inflationcapfloor.cpp.
Natural anonymous_namespace{inflationcapfloor.cpp}::CommonVars::fixingDays
Definition at line 92 of file inflationcapfloor.cpp.
Frequency anonymous_namespace{inflationcapfloor.cpp}::CommonVars::frequency
Definition at line 88 of file inflationcapfloor.cpp.
RelinkableHandle<YoYInflationTermStructure> anonymous_namespace{inflationcapfloor.cpp}::CommonVars::hy
Definition at line 102 of file inflationcapfloor.cpp.
boost::shared_ptr<YYUKRPIr> anonymous_namespace{inflationcapfloor.cpp}::CommonVars::iir
Definition at line 98 of file inflationcapfloor.cpp.
std::vector<Real> anonymous_namespace{inflationcapfloor.cpp}::CommonVars::nominals
Definition at line 89 of file inflationcapfloor.cpp.
RelinkableHandle<YieldTermStructure> anonymous_namespace{inflationcapfloor.cpp}::CommonVars::nominalTS
Definition at line 100 of file inflationcapfloor.cpp.
Period anonymous_namespace{inflationcapfloor.cpp}::CommonVars::observationLag
Definition at line 96 of file inflationcapfloor.cpp.
Date anonymous_namespace{inflationcapfloor.cpp}::CommonVars::settlement
Definition at line 95 of file inflationcapfloor.cpp.
Natural anonymous_namespace{inflationcapfloor.cpp}::CommonVars::settlementDays
Definition at line 94 of file inflationcapfloor.cpp.
boost::shared_ptr<YoYInflationTermStructure> anonymous_namespace{inflationcapfloor.cpp}::CommonVars::yoyTS
Definition at line 101 of file inflationcapfloor.cpp.
The documentation for this struct was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/inflationcapfloor.cpp