QuantLib: anonymous_namespace{convertiblebonds.cpp}::CommonVars Struct Reference
anonymous_namespace{convertiblebonds.cpp}::CommonVars Struct Reference
Public Member Functions
CommonVars ()
Public Attributes
Date today
Date issueDate
Date maturityDate
Calendar calendar
DayCounter dayCounter
Frequency frequency
Natural settlementDays
RelinkableHandle< Quote > underlying
RelinkableHandle
< YieldTermStructure > dividendYield
RelinkableHandle
< YieldTermStructure > riskFreeRate
RelinkableHandle
< BlackVolTermStructure > volatility
boost::shared_ptr
< BlackScholesMertonProcess > process
RelinkableHandle< Quote > creditSpread
CallabilitySchedule no_callability
DividendSchedule no_dividends
Real faceAmount
Real redemption
Real conversionRatio
SavedSettings backup
Detailed Description
Definition at line 50 of file convertiblebonds.cpp.
Constructor & Destructor Documentation
anonymous_namespace{convertiblebonds.cpp}::CommonVars::CommonVars () [inline]
Definition at line 74 of file convertiblebonds.cpp.
References QuantLib::Calendar::adjust(), QuantLib::Calendar::advance(), QuantLib::Annual, anonymous_namespace{marketmodel.cpp}::calendar, anonymous_namespace{marketmodel.cpp}::dayCounter, QuantLib::Days, QuantLib::Settings::evaluationDate(), QuantLib::flatRate(), QuantLib::flatVol(), QuantLib::Singleton< Settings >::instance(), QuantLib::Date::todaysDate(), QuantLib::detail::percent_holder::value, QuantLib::io::volatility(), and QuantLib::Years.
                     {
            calendar = TARGET();
            today = calendar.adjust(Date::todaysDate());
            Settings::instance().evaluationDate() = today;
            dayCounter = Actual360();
            frequency = Annual;
            settlementDays = 3;
            issueDate = calendar.advance(today,2,Days);
            maturityDate = calendar.advance(issueDate, 10, Years);
            // reset to avoid inconsistencies as the schedule is backwards
            issueDate = calendar.advance(maturityDate, -10, Years);
            underlying.linkTo(boost::shared_ptr<Quote>(new SimpleQuote(50.0)));
            dividendYield.linkTo(flatRate(today, 0.02, dayCounter));
            riskFreeRate.linkTo(flatRate(today, 0.05, dayCounter));
            volatility.linkTo(flatVol(today, 0.15, dayCounter));
            process = boost::shared_ptr<BlackScholesMertonProcess>(
                    new BlackScholesMertonProcess(underlying, dividendYield,
                                                  riskFreeRate, volatility));
            creditSpread.linkTo(
                            boost::shared_ptr<Quote>(new SimpleQuote(0.005)));
            // it fails with 1000000
            // faceAmount = 1000000.0;
            faceAmount = 100.0;
            redemption = 100.0;
            conversionRatio = redemption/underlying->value();
        }
Member Data Documentation
SavedSettings anonymous_namespace{convertiblebonds.cpp}::CommonVars::backup
Definition at line 71 of file convertiblebonds.cpp.
Calendar anonymous_namespace{convertiblebonds.cpp}::CommonVars::calendar
Definition at line 53 of file convertiblebonds.cpp.
Real anonymous_namespace{convertiblebonds.cpp}::CommonVars::conversionRatio
Definition at line 68 of file convertiblebonds.cpp.
RelinkableHandle<Quote> anonymous_namespace{convertiblebonds.cpp}::CommonVars::creditSpread
Definition at line 63 of file convertiblebonds.cpp.
DayCounter anonymous_namespace{convertiblebonds.cpp}::CommonVars::dayCounter
Definition at line 54 of file convertiblebonds.cpp.
RelinkableHandle<YieldTermStructure> anonymous_namespace{convertiblebonds.cpp}::CommonVars::dividendYield
Definition at line 59 of file convertiblebonds.cpp.
Real anonymous_namespace{convertiblebonds.cpp}::CommonVars::faceAmount
Definition at line 68 of file convertiblebonds.cpp.
Frequency anonymous_namespace{convertiblebonds.cpp}::CommonVars::frequency
Definition at line 55 of file convertiblebonds.cpp.
Date anonymous_namespace{convertiblebonds.cpp}::CommonVars::issueDate
Definition at line 52 of file convertiblebonds.cpp.
Date anonymous_namespace{convertiblebonds.cpp}::CommonVars::maturityDate
Definition at line 52 of file convertiblebonds.cpp.
CallabilitySchedule anonymous_namespace{convertiblebonds.cpp}::CommonVars::no_callability
Definition at line 65 of file convertiblebonds.cpp.
DividendSchedule anonymous_namespace{convertiblebonds.cpp}::CommonVars::no_dividends
Definition at line 66 of file convertiblebonds.cpp.
boost::shared_ptr<BlackScholesMertonProcess> anonymous_namespace{convertiblebonds.cpp}::CommonVars::process
Definition at line 61 of file convertiblebonds.cpp.
Real anonymous_namespace{convertiblebonds.cpp}::CommonVars::redemption
Definition at line 68 of file convertiblebonds.cpp.
RelinkableHandle<YieldTermStructure> anonymous_namespace{convertiblebonds.cpp}::CommonVars::riskFreeRate
Definition at line 59 of file convertiblebonds.cpp.
Natural anonymous_namespace{convertiblebonds.cpp}::CommonVars::settlementDays
Definition at line 56 of file convertiblebonds.cpp.
Date anonymous_namespace{convertiblebonds.cpp}::CommonVars::today
Definition at line 52 of file convertiblebonds.cpp.
RelinkableHandle<Quote> anonymous_namespace{convertiblebonds.cpp}::CommonVars::underlying
Definition at line 58 of file convertiblebonds.cpp.
RelinkableHandle<BlackVolTermStructure> anonymous_namespace{convertiblebonds.cpp}::CommonVars::volatility
Definition at line 60 of file convertiblebonds.cpp.
The documentation for this struct was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/convertiblebonds.cpp