QuantLib: anonymous_namespace{digitalcoupon.cpp}::CommonVars Struct Reference
anonymous_namespace{digitalcoupon.cpp}::CommonVars Struct Reference
Public Member Functions
CommonVars ()
Public Attributes
Date today
Date settlement
Real nominal
Calendar calendar
boost::shared_ptr< IborIndex > index
Natural fixingDays
RelinkableHandle
< YieldTermStructure > termStructure
Real optionTolerance
Real blackTolerance
SavedSettings backup
Detailed Description
Definition at line 41 of file digitalcoupon.cpp.
Constructor & Destructor Documentation
anonymous_namespace{digitalcoupon.cpp}::CommonVars::CommonVars () [inline]
Definition at line 56 of file digitalcoupon.cpp.
References QuantLib::Calendar::adjust(), anonymous_namespace{marketmodel.cpp}::calendar, QuantLib::Days, QuantLib::Settings::evaluationDate(), QuantLib::flatRate(), QuantLib::Singleton< Settings >::instance(), and QuantLib::Date::todaysDate().
                     {
            fixingDays = 2;
            nominal = 1000000.0;
            index = boost::shared_ptr<IborIndex>(new Euribor6M(termStructure));
            calendar = index->fixingCalendar();
            today = calendar.adjust(Date::todaysDate());
            Settings::instance().evaluationDate() = today;
            settlement = calendar.advance(today,fixingDays,Days);
            termStructure.linkTo(flatRate(settlement,0.05,Actual365Fixed()));
            optionTolerance = 1.e-04;
            blackTolerance = 1e-10;
        }
Member Data Documentation
SavedSettings anonymous_namespace{digitalcoupon.cpp}::CommonVars::backup
Definition at line 53 of file digitalcoupon.cpp.
Real anonymous_namespace{digitalcoupon.cpp}::CommonVars::blackTolerance
Definition at line 50 of file digitalcoupon.cpp.
Calendar anonymous_namespace{digitalcoupon.cpp}::CommonVars::calendar
Definition at line 45 of file digitalcoupon.cpp.
Natural anonymous_namespace{digitalcoupon.cpp}::CommonVars::fixingDays
Definition at line 47 of file digitalcoupon.cpp.
boost::shared_ptr<IborIndex> anonymous_namespace{digitalcoupon.cpp}::CommonVars::index
Definition at line 46 of file digitalcoupon.cpp.
Real anonymous_namespace{digitalcoupon.cpp}::CommonVars::nominal
Definition at line 44 of file digitalcoupon.cpp.
Real anonymous_namespace{digitalcoupon.cpp}::CommonVars::optionTolerance
Definition at line 49 of file digitalcoupon.cpp.
Date anonymous_namespace{digitalcoupon.cpp}::CommonVars::settlement
Definition at line 43 of file digitalcoupon.cpp.
RelinkableHandle<YieldTermStructure> anonymous_namespace{digitalcoupon.cpp}::CommonVars::termStructure
Definition at line 48 of file digitalcoupon.cpp.
Date anonymous_namespace{digitalcoupon.cpp}::CommonVars::today
Definition at line 43 of file digitalcoupon.cpp.
The documentation for this struct was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/digitalcoupon.cpp