QuantLib: anonymous_namespace{swaptionvolatilitymatrix.cpp}::CommonVars Struct Reference
anonymous_namespace{swaptionvolatilitymatrix.cpp}::CommonVars Struct Reference
Public Member Functions
CommonVars ()
void makeObservabilityTest (const std::string &description, const boost::shared_ptr< SwaptionVolatilityStructure > &vol, bool mktDataFloating, bool referenceDateFloating)
void makeCoherenceTest (const std::string &description, const boost::shared_ptr< SwaptionVolatilityDiscrete > &vol)
Public Attributes
Date referenceDate
SwaptionMarketConventions conventions
AtmVolatility atm
RelinkableHandle
< YieldTermStructure > termStructure
RelinkableHandle
< SwaptionVolatilityStructure > atmVolMatrix
Real tolerance
SavedSettings backup
Detailed Description
Definition at line 38 of file swaptionvolatilitymatrix.cpp.
Constructor & Destructor Documentation
anonymous_namespace{swaptionvolatilitymatrix.cpp}::CommonVars::CommonVars () [inline]
Definition at line 51 of file swaptionvolatilitymatrix.cpp.
References QuantLib::Settings::evaluationDate(), QuantLib::Singleton< Settings >::instance(), and QuantLib::Date::todaysDate().
                     {
            conventions.setConventions();
            atm.setMarketData();
            Settings::instance().evaluationDate() =
                conventions.calendar.adjust(Date::todaysDate());
            atmVolMatrix = RelinkableHandle<SwaptionVolatilityStructure>(
                boost::shared_ptr<SwaptionVolatilityStructure>(new
                    SwaptionVolatilityMatrix(conventions.calendar,
                                             conventions.optionBdc,
                                             atm.tenors.options,
                                             atm.tenors.swaps,
                                             atm.volsHandle,
                                             conventions.dayCounter)));
            termStructure.linkTo(
                boost::shared_ptr<YieldTermStructure>(new
                    FlatForward(0, conventions.calendar,
                                0.05, Actual365Fixed())));
        }
Member Function Documentation
void anonymous_namespace{swaptionvolatilitymatrix.cpp}::CommonVars::makeCoherenceTest (const std::string & description, const boost::shared_ptr< SwaptionVolatilityDiscrete > & vol) [inline]
Definition at line 112 of file swaptionvolatilitymatrix.cpp.
References QuantLib::close(), QuantLib::Option::exercise(), QuantLib::Swaption::impliedVolatility(), QuantLib::Instrument::NPV(), anonymous_namespace{gaussianquadratures.cpp}::tolerance, QuantLib::Swaption::underlyingSwap(), QuantLib::io::volatility(), QuantLib::MakeSwaption::withPricingEngine(), and QuantLib::years().
{
            for (Size i=0; i<atm.tenors.options.size(); ++i) {
                Date optionDate =
                    vol->optionDateFromTenor(atm.tenors.options[i]);
                if (optionDate!=vol->optionDates()[i])
                    BOOST_FAIL(
                         "optionDateFromTenor failure for " <<
                         description << ":"
                         "\n       option tenor: " << atm.tenors.options[i] <<
                         "\nactual option date : " << optionDate <<
                         "\n  exp. option date : " << vol->optionDates()[i]);
                Time optionTime = vol->timeFromReference(optionDate);
                if (!close(optionTime,vol->optionTimes()[i]))
                    BOOST_FAIL(
                         "timeFromReference failure for " <<
                         description << ":"
                         "\n       option tenor: " << atm.tenors.options[i] <<
                         "\n       option date : " << optionDate <<
                         "\nactual option time : " << optionTime <<
                         "\n  exp. option time : " << vol->optionTimes()[i]);
            }
            boost::shared_ptr<BlackSwaptionEngine> engine(new
                BlackSwaptionEngine(termStructure,
                                    Handle<SwaptionVolatilityStructure>(vol)));
            for (Size j=0; j<atm.tenors.swaps.size(); j++) {
                Time swapLength = vol->swapLength(atm.tenors.swaps[j]);
                if (!close(swapLength,years(atm.tenors.swaps[j])))
                    BOOST_FAIL("convertSwapTenor failure for " <<
                               description << ":"
                               "\n        swap tenor : " << atm.tenors.swaps[j] <<
                               "\n actual swap length: " << swapLength <<
                               "\n   exp. swap length: " << years(atm.tenors.swaps[j]));
                boost::shared_ptr<SwapIndex> swapIndex(new
                    EuriborSwapIsdaFixA(atm.tenors.swaps[j], termStructure));
                for (Size i=0; i<atm.tenors.options.size(); ++i) {
                    Real error, tolerance = 1.0e-16;
                    Volatility actVol, expVol = atm.vols[i][j];
                    actVol = vol->volatility(atm.tenors.options[i],
                                             atm.tenors.swaps[j], 0.05, true);
                    error = std::abs(expVol-actVol);
                    if (error>tolerance)
                        BOOST_FAIL(
                              "recovery of atm vols failed for " <<
                              description << ":"
                              "\noption tenor = " << atm.tenors.options[i] <<
                              "\n swap length = " << atm.tenors.swaps[j] <<
                              "\nexpected vol = " << io::volatility(expVol) <<
                              "\n  actual vol = " << io::volatility(actVol) <<
                              "\n       error = " << io::volatility(error) <<
                              "\n   tolerance = " << tolerance);
                    Date optionDate =
                        vol->optionDateFromTenor(atm.tenors.options[i]);
                    actVol = vol->volatility(optionDate,
                                             atm.tenors.swaps[j], 0.05, true);
                    error = std::abs(expVol-actVol);
                    if (error>tolerance)
                        BOOST_FAIL(
                             "recovery of atm vols failed for " <<
                             description << ":"
                             "\noption tenor: " << atm.tenors.options[i] <<
                             "\noption date : " << optionDate <<
                             "\n  swap tenor: " << atm.tenors.swaps[j] <<
                             "\n   exp. vol: " << io::volatility(expVol) <<
                             "\n actual vol: " << io::volatility(actVol) <<
                             "\n      error: " << io::volatility(error) <<
                             "\n  tolerance: " << tolerance);
                    Time optionTime = vol->timeFromReference(optionDate);
                    actVol = vol->volatility(optionTime, swapLength,
                                             0.05, true);
                    error = std::abs(expVol-actVol);
                    if (error>tolerance)
                        BOOST_FAIL(
                             "recovery of atm vols failed for " <<
                             description << ":"
                             "\noption tenor: " << atm.tenors.options[i] <<
                             "\noption time : " << optionTime <<
                             "\n  swap tenor: " << atm.tenors.swaps[j] <<
                             "\n swap length: " << swapLength <<
                             "\n    exp. vol: " << io::volatility(expVol) <<
                             "\n  actual vol: " << io::volatility(actVol) <<
                             "\n       error: " << io::volatility(error) <<
                             "\n   tolerance: " << tolerance);
                    // ATM swaption
                    Swaption swaption =
                        MakeSwaption(swapIndex, atm.tenors.options[i])
                        .withPricingEngine(engine);
                    Date exerciseDate = swaption.exercise()->dates().front();
                    if (exerciseDate!=vol->optionDates()[i])
                        BOOST_FAIL(
                             "\noptionDateFromTenor mismatch for " <<
                             description << ":"
                             "\n      option tenor: " << atm.tenors.options[i] <<
                             "\nactual option date: " << exerciseDate <<
                             "\n  exp. option date: " << vol->optionDates()[i]);
                    Date start = swaption.underlyingSwap()->startDate();
                    Date end = swaption.underlyingSwap()->maturityDate();
                    Time swapLength2 = vol->swapLength(start, end);
                    if (!close(swapLength2,swapLength))
                        BOOST_FAIL("\nswapLength failure for " <<
                                   description << ":"
                                   "\n   exp. swap length: " << swapLength <<
                                   "\n actual swap length: " << swapLength2 <<
                                   "\n        swap tenor : " << atm.tenors.swaps[j] <<
                                   "\n  swap index tenor : " << swapIndex->tenor() <<
                                   "\n        option date: " << exerciseDate <<
                                   "\n         start date: " << start <<
                                   "\n      maturity date: " << end
                                   );
                    Real npv = swaption.NPV();
                    actVol = swaption.impliedVolatility(npv, termStructure,
                                                        expVol*0.98, 1e-6);
                    error = std::abs(expVol-actVol);
                    Real tolerance2 = 0.000001;
                    if (error>tolerance2)
                        BOOST_FAIL(
                             "recovery of atm vols through BlackSwaptionEngine failed for " <<
                             description << ":"
                             "\noption tenor: " << atm.tenors.options[i] <<
                             "\noption time : " << optionTime <<
                             "\n  swap tenor: " << atm.tenors.swaps[j] <<
                             "\n swap length: " << swapLength <<
                             "\n   exp. vol: " << io::volatility(expVol) <<
                             "\n actual vol: " << io::volatility(actVol) <<
                             "\n      error: " << io::volatility(error) <<
                             "\n  tolerance: " << tolerance2);
                }
            }
        }
void anonymous_namespace{swaptionvolatilitymatrix.cpp}::CommonVars::makeObservabilityTest (const std::string & description, const boost::shared_ptr< SwaptionVolatilityStructure > & vol, bool mktDataFloating, bool referenceDateFloating) [inline]
Definition at line 71 of file swaptionvolatilitymatrix.cpp.
References QuantLib::Settings::evaluationDate(), QuantLib::Singleton< Settings >::instance(), and QuantLib::Years.
{
            Rate dummyStrike = .02;
            Date referenceDate = Settings::instance().evaluationDate();
            Volatility initialVol = vol->volatility(
                        referenceDate + atm.tenors.options[0],
                        atm.tenors.swaps[0], dummyStrike, false);
            // testing evaluation date change ...
            Settings::instance().evaluationDate() =
                referenceDate - Period(1, Years);
            Volatility newVol =  vol->volatility(
                        referenceDate + atm.tenors.options[0],
                        atm.tenors.swaps[0], dummyStrike, false);
            Settings::instance().evaluationDate() = referenceDate;
            if (referenceDateFloating && (initialVol == newVol))
                BOOST_ERROR(description <<
                            " the volatility should change when the reference date is changed !");
            if (!referenceDateFloating && (initialVol != newVol))
                BOOST_ERROR(description <<
                            " the volatility should not change when the reference date is changed !");
            // test market data change...
            if (mktDataFloating){
                Volatility initialVolatility = atm.volsHandle[0][0]->value();
                boost::dynamic_pointer_cast<SimpleQuote>(
                              atm.volsHandle[0][0].currentLink())->setValue(10);
                newVol = vol->volatility(
                    referenceDate + atm.tenors.options[0],
                    atm.tenors.swaps[0], dummyStrike, false);
                boost::dynamic_pointer_cast<SimpleQuote>(
                    atm.volsHandle[0][0].currentLink())
                    ->setValue(initialVolatility);
                if (initialVol == newVol)
                    BOOST_ERROR(description << " the volatility should change when"
                                " the market data is changed !");
            }
        }
Member Data Documentation
AtmVolatility anonymous_namespace{swaptionvolatilitymatrix.cpp}::CommonVars::atm
Definition at line 42 of file swaptionvolatilitymatrix.cpp.
RelinkableHandle<SwaptionVolatilityStructure> anonymous_namespace{swaptionvolatilitymatrix.cpp}::CommonVars::atmVolMatrix
Definition at line 44 of file swaptionvolatilitymatrix.cpp.
SavedSettings anonymous_namespace{swaptionvolatilitymatrix.cpp}::CommonVars::backup
Definition at line 48 of file swaptionvolatilitymatrix.cpp.
SwaptionMarketConventions anonymous_namespace{swaptionvolatilitymatrix.cpp}::CommonVars::conventions
Definition at line 41 of file swaptionvolatilitymatrix.cpp.
Date anonymous_namespace{swaptionvolatilitymatrix.cpp}::CommonVars::referenceDate
Definition at line 40 of file swaptionvolatilitymatrix.cpp.
RelinkableHandle<YieldTermStructure> anonymous_namespace{swaptionvolatilitymatrix.cpp}::CommonVars::termStructure
Definition at line 43 of file swaptionvolatilitymatrix.cpp.
Real anonymous_namespace{swaptionvolatilitymatrix.cpp}::CommonVars::tolerance
Definition at line 45 of file swaptionvolatilitymatrix.cpp.
The documentation for this struct was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/swaptionvolatilitymatrix.cpp