QuantLib: anonymous_namespace{termstructures.cpp}::CommonVars Struct Reference
anonymous_namespace{termstructures.cpp}::CommonVars Struct Reference
Public Member Functions
CommonVars ()
Public Attributes
Calendar calendar
Natural settlementDays
boost::shared_ptr
< YieldTermStructure > termStructure
boost::shared_ptr
< YieldTermStructure > dummyTermStructure
SavedSettings backup
Detailed Description
Definition at line 48 of file termstructures.cpp.
Constructor & Destructor Documentation
anonymous_namespace{termstructures.cpp}::CommonVars::CommonVars () [inline]
Definition at line 59 of file termstructures.cpp.
References QuantLib::Calendar::adjust(), QuantLib::Calendar::advance(), QuantLib::Annual, anonymous_namespace{marketmodel.cpp}::calendar, QuantLib::Days, anonymous_namespace{overnightindexedswap.cpp}::depositData, QuantLib::Settings::evaluationDate(), QuantLib::Singleton< Settings >::instance(), LENGTH, QuantLib::ModifiedFollowing, QuantLib::Months, QuantLib::io::rate(), anonymous_namespace{overnightindexedswap.cpp}::swapData, QuantLib::Date::todaysDate(), QuantLib::Unadjusted, and QuantLib::Years.
                     {
            calendar = TARGET();
            settlementDays = 2;
            Date today = calendar.adjust(Date::todaysDate());
            Settings::instance().evaluationDate() = today;
            Date settlement = calendar.advance(today,settlementDays,Days);
            Datum depositData[] = {
                { 1, Months, 4.581 },
                { 2, Months, 4.573 },
                { 3, Months, 4.557 },
                { 6, Months, 4.496 },
                { 9, Months, 4.490 }
            };
            Datum swapData[] = {
                {  1, Years, 4.54 },
                {  5, Years, 4.99 },
                { 10, Years, 5.47 },
                { 20, Years, 5.89 },
                { 30, Years, 5.96 }
            };
            Size deposits = LENGTH(depositData),
                swaps = LENGTH(swapData);
            std::vector<boost::shared_ptr<RateHelper> > instruments(
                                                              deposits+swaps);
            for (Size i=0; i<deposits; i++) {
                instruments[i] = boost::shared_ptr<RateHelper>(new
                    DepositRateHelper(depositData[i].rate/100,
                                      depositData[i].n*depositData[i].units,
                                      settlementDays, calendar,
                                      ModifiedFollowing, true,
                                      Actual360()));
            }
            boost::shared_ptr<IborIndex> index(new IborIndex("dummy",
                                                             6*Months,
                                                             settlementDays,
                                                             Currency(),
                                                             calendar,
                                                             ModifiedFollowing,
                                                             false,
                                                             Actual360()));
            for (Size i=0; i<swaps; ++i) {
                instruments[i+deposits] = boost::shared_ptr<RateHelper>(new
                    SwapRateHelper(swapData[i].rate/100,
                                   swapData[i].n*swapData[i].units,
                                   calendar,
                                   Annual, Unadjusted, Thirty360(),
                                   index));
            }
            termStructure = boost::shared_ptr<YieldTermStructure>(new
                PiecewiseYieldCurve<Discount,LogLinear>(settlement,
                                                        instruments, Actual360()));
            dummyTermStructure = boost::shared_ptr<YieldTermStructure>(new
                PiecewiseYieldCurve<Discount,LogLinear>(settlement,
                                                        instruments, Actual360()));
        }
Member Data Documentation
SavedSettings anonymous_namespace{termstructures.cpp}::CommonVars::backup
Definition at line 56 of file termstructures.cpp.
Calendar anonymous_namespace{termstructures.cpp}::CommonVars::calendar
Definition at line 50 of file termstructures.cpp.
boost::shared_ptr<YieldTermStructure> anonymous_namespace{termstructures.cpp}::CommonVars::dummyTermStructure
Definition at line 53 of file termstructures.cpp.
Natural anonymous_namespace{termstructures.cpp}::CommonVars::settlementDays
Definition at line 51 of file termstructures.cpp.
boost::shared_ptr<YieldTermStructure> anonymous_namespace{termstructures.cpp}::CommonVars::termStructure
Definition at line 52 of file termstructures.cpp.
The documentation for this struct was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/termstructures.cpp