QuantLib: anonymous_namespace{swaption.cpp}::CommonVars Struct Reference
anonymous_namespace{swaption.cpp}::CommonVars Struct Reference
Public Member Functions
boost::shared_ptr< Swaption > makeSwaption (const boost::shared_ptr< VanillaSwap > &swap, const Date &exercise, Volatility volatility, Settlement::Type settlementType=Settlement::Physical)
boost::shared_ptr< PricingEngine > makeEngine (Volatility volatility)
CommonVars ()
Public Attributes
Date today
Date settlement
Real nominal
Calendar calendar
BusinessDayConvention fixedConvention
Frequency fixedFrequency
DayCounter fixedDayCount
BusinessDayConvention floatingConvention
Period floatingTenor
boost::shared_ptr< IborIndex > index
Natural settlementDays
RelinkableHandle
< YieldTermStructure > termStructure
SavedSettings backup
Detailed Description
Definition at line 50 of file swaption.cpp.
Constructor & Destructor Documentation
anonymous_namespace{swaption.cpp}::CommonVars::CommonVars () [inline]
Definition at line 97 of file swaption.cpp.
References QuantLib::Calendar::adjust(), QuantLib::Calendar::advance(), QuantLib::Annual, anonymous_namespace{marketmodel.cpp}::calendar, QuantLib::Days, QuantLib::Settings::evaluationDate(), QuantLib::flatRate(), QuantLib::Singleton< Settings >::instance(), QuantLib::Date::todaysDate(), and QuantLib::Unadjusted.
                     {
            settlementDays = 2;
            nominal = 1000000.0;
            fixedConvention = Unadjusted;
            fixedFrequency = Annual;
            fixedDayCount = Thirty360();
            index = boost::shared_ptr<IborIndex>(new Euribor6M(termStructure));
            floatingConvention = index->businessDayConvention();
            floatingTenor = index->tenor();
            calendar = index->fixingCalendar();
            today = calendar.adjust(Date::todaysDate());
            Settings::instance().evaluationDate() = today;
            settlement = calendar.advance(today,settlementDays,Days);
            termStructure.linkTo(flatRate(settlement,0.05,Actual365Fixed()));
        }
Member Function Documentation
boost::shared_ptr<PricingEngine> anonymous_namespace{swaption.cpp}::CommonVars::makeEngine (Volatility volatility) [inline]
Definition at line 90 of file swaption.cpp.
{
            Handle<Quote> h(boost::shared_ptr<Quote>(
                                                new SimpleQuote(volatility)));
            return boost::shared_ptr<PricingEngine>(
                                  new BlackSwaptionEngine(termStructure, h));
        }
boost::shared_ptr<Swaption> anonymous_namespace{swaption.cpp}::CommonVars::makeSwaption (const boost::shared_ptr< VanillaSwap > & swap, const Date & exercise, Volatility volatility, Settlement::Type settlementType = Settlement::Physical) [inline]
Definition at line 71 of file swaption.cpp.
{
            Handle<Quote> vol(boost::shared_ptr<Quote>(
                                                new SimpleQuote(volatility)));
            boost::shared_ptr<PricingEngine> engine(
                                new BlackSwaptionEngine(termStructure, vol));
            boost::shared_ptr<Swaption> result(new
                Swaption(swap,
                         boost::shared_ptr<Exercise>(
                                              new EuropeanExercise(exercise)),
                         settlementType));
            result->setPricingEngine(engine);
            return result;
        }
Member Data Documentation
SavedSettings anonymous_namespace{swaption.cpp}::CommonVars::backup
Definition at line 68 of file swaption.cpp.
Calendar anonymous_namespace{swaption.cpp}::CommonVars::calendar
Definition at line 54 of file swaption.cpp.
BusinessDayConvention anonymous_namespace{swaption.cpp}::CommonVars::fixedConvention
Definition at line 56 of file swaption.cpp.
DayCounter anonymous_namespace{swaption.cpp}::CommonVars::fixedDayCount
Definition at line 58 of file swaption.cpp.
Frequency anonymous_namespace{swaption.cpp}::CommonVars::fixedFrequency
Definition at line 57 of file swaption.cpp.
BusinessDayConvention anonymous_namespace{swaption.cpp}::CommonVars::floatingConvention
Definition at line 60 of file swaption.cpp.
Period anonymous_namespace{swaption.cpp}::CommonVars::floatingTenor
Definition at line 61 of file swaption.cpp.
boost::shared_ptr<IborIndex> anonymous_namespace{swaption.cpp}::CommonVars::index
Definition at line 62 of file swaption.cpp.
Real anonymous_namespace{swaption.cpp}::CommonVars::nominal
Definition at line 53 of file swaption.cpp.
Date anonymous_namespace{swaption.cpp}::CommonVars::settlement
Definition at line 52 of file swaption.cpp.
Natural anonymous_namespace{swaption.cpp}::CommonVars::settlementDays
Definition at line 64 of file swaption.cpp.
RelinkableHandle<YieldTermStructure> anonymous_namespace{swaption.cpp}::CommonVars::termStructure
Definition at line 65 of file swaption.cpp.
Date anonymous_namespace{swaption.cpp}::CommonVars::today
Definition at line 52 of file swaption.cpp.
The documentation for this struct was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/swaption.cpp