QuantLib: QuantLib::detail::DataTable< X > Struct Template Reference
QuantLib::detail::DataTable< X > Struct Template Reference
#include <multicubicspline.hpp>
Public Member Functions
DataTable (const std::vector< Size >::const_iterator &i)
DataTable (const SplineGrid::const_iterator &i)
template<class U >
DataTable (const std::vector< U > &v)
Size size () const
const X & operator[] (Size n) const
X & operator[] (Size n)
Public Attributes
std::vector< X > data_table_
Detailed Description
template<class X>
struct QuantLib::detail::DataTable< X >
Definition at line 46 of file multicubicspline.hpp.
Constructor & Destructor Documentation
template<class X > QuantLib::detail::DataTable< X >::DataTable (const std::vector< Size >::const_iterator & i) [inline]
Definition at line 47 of file multicubicspline.hpp.
References QuantLib::detail::DataTable< X >::data_table_.
{
                std::vector<X> temp(*i, X(i + 1));
                data_table_.swap(temp);
            }
template<class X > QuantLib::detail::DataTable< X >::DataTable (const SplineGrid::const_iterator & i) [inline]
Definition at line 51 of file multicubicspline.hpp.
References QuantLib::detail::DataTable< X >::data_table_.
{
                std::vector<X> temp(i->size(), X(i + 1));
                data_table_.swap(temp);
            }
template<class X > template<class U > QuantLib::detail::DataTable< X >::DataTable (const std::vector< U > & v) [inline]
Definition at line 55 of file multicubicspline.hpp.
References QuantLib::detail::DataTable< X >::data_table_, and anonymous_namespace{perturbativebarrieroptionengine.cpp}::v().
{
                DataTable temp(v.begin());
                data_table_.swap(temp.data_table_);
            }
Member Function Documentation
template<class X > const X& QuantLib::detail::DataTable< X >::operator[] (Size n) const [inline]
Definition at line 62 of file multicubicspline.hpp.
References QuantLib::detail::DataTable< X >::data_table_.
{return data_table_[n];}
template<class X > X& QuantLib::detail::DataTable< X >::operator[] (Size n) [inline]
Definition at line 63 of file multicubicspline.hpp.
References QuantLib::detail::DataTable< X >::data_table_.
{return data_table_[n];}
template<class X > Size QuantLib::detail::DataTable< X >::size () const [inline]
Definition at line 59 of file multicubicspline.hpp.
References QuantLib::detail::DataTable< X >::data_table_.
Referenced by QuantLib::detail::n_cubic_spline< X >::n_cubic_spline(), and QuantLib::detail::n_cubic_splint< X >::n_cubic_splint().
{
                return data_table_.size();
            }
Member Data Documentation
template<class X > std::vector<X> QuantLib::detail::DataTable< X >::data_table_
Definition at line 64 of file multicubicspline.hpp.
Referenced by QuantLib::detail::DataTable< X >::DataTable(), QuantLib::detail::DataTable< Real >::DataTable(), QuantLib::detail::DataTable< X >::operator[](), QuantLib::detail::DataTable< Real >::operator[](), QuantLib::detail::DataTable< X >::size(), and QuantLib::detail::DataTable< Real >::size().
The documentation for this struct was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/ql/math/interpolations/multicubicspline.hpp