QuantLib: anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars Struct Reference
anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars Struct Reference
Public Member Functions
CommonVars ()
Public Attributes
Size length
Date startDate
Rate baseZeroRate
Real volatility
Frequency frequency
std::vector< Real > nominals
Calendar calendar
BusinessDayConvention convention
Natural fixingDays
Date evaluationDate
Natural settlementDays
Date settlement
Period observationLag
Period contractObservationLag
CPI::InterpolationType contractObservationInterpolation
DayCounter dcZCIIS
DayCounter dcNominal
std::vector< Date > zciisD
std::vector< Rate > zciisR
boost::shared_ptr< UKRPI > ii
RelinkableHandle
< ZeroInflationIndex > hii
Size zciisDataLength
RelinkableHandle
< YieldTermStructure > nominalUK
RelinkableHandle
< ZeroInflationTermStructure > cpiUK
RelinkableHandle
< ZeroInflationTermStructure > hcpi
vector< Rate > cStrikesUK
vector< Rate > fStrikesUK
vector< Period > cfMaturitiesUK
boost::shared_ptr< Matrix > cPriceUK
boost::shared_ptr< Matrix > fPriceUK
boost::shared_ptr
< CPICapFloorTermPriceSurface > cpiCFsurfUK
SavedSettings backup
Detailed Description
Definition at line 87 of file inflationcpicapfloor.cpp.
Constructor & Destructor Documentation
anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::CommonVars () [inline]
Definition at line 129 of file inflationcpicapfloor.cpp.
References QuantLib::Calendar::adjust(), QuantLib::Calendar::advance(), QuantLib::Annual, QuantLib::August, anonymous_namespace{marketmodel.cpp}::calendar, anonymous_namespace{inflationvolatility.cpp}::cfMaturitiesUK, anonymous_namespace{inflationvolatility.cpp}::cPriceUK, anonymous_namespace{inflationvolatility.cpp}::cStrikesUK, QuantLib::Days, QuantLib::December, QuantLib::Settings::evaluationDate(), QuantLib::CPI::Flat, anonymous_namespace{inflationvolatility.cpp}::fPriceUK, QuantLib::MakeSchedule::from(), anonymous_namespace{inflationvolatility.cpp}::fStrikesUK, QuantLib::Singleton< Settings >::instance(), QuantLib::July, QuantLib::June, anonymous_namespace{inflation.cpp}::makeHelpers(), QuantLib::March, QuantLib::ModifiedFollowing, QuantLib::Months, QuantLib::io::rate(), QuantLib::September, QuantLib::Schedule::size(), anonymous_namespace{marketmodel.cpp}::startDate, QuantLib::MakeSchedule::to(), QuantLib::io::volatility(), QuantLib::MakeSchedule::withCalendar(), QuantLib::MakeSchedule::withConvention(), QuantLib::MakeSchedule::withTenor(), and QuantLib::Years.
                     {
            //std::cout <<"CommonVars" << std::endl;
            // option variables
            nominals = std::vector<Real>(1,1000000);  // 1M
            frequency = Annual;
            // usual setup
            volatility = 0.01;
            length = 7;
            calendar = UnitedKingdom();
            convention = ModifiedFollowing;
            Date today(1, June, 2010);
            evaluationDate = calendar.adjust(today);
            Settings::instance().evaluationDate() = evaluationDate;
            settlementDays = 0;
            fixingDays = 0;
            settlement = calendar.advance(today,settlementDays,Days);
            startDate = settlement;
            dcZCIIS = ActualActual();
            dcNominal = ActualActual();
            // uk rpi index
            //      fixing data
            Date from(1, July, 2007);
            Date to(1, June, 2010);
            Schedule rpiSchedule = MakeSchedule().from(from).to(to)
            .withTenor(1*Months)
            .withCalendar(UnitedKingdom())
            .withConvention(ModifiedFollowing);
            Real fixData[] = {
                206.1, 207.3, 208.0, 208.9, 209.7, 210.9,
                209.8, 211.4, 212.1, 214.0, 215.1, 216.8,   //  2008
                216.5, 217.2, 218.4, 217.7, 216.0, 212.9,
                210.1, 211.4, 211.3, 211.5, 212.8, 213.4,   //  2009
                213.4, 214.4, 215.3, 216.0, 216.6, 218.0,
                217.9, 219.2, 220.7, 222.8, -999, -999,     //  2010
                -999};
            // link from cpi index to cpi TS
            bool interp = false;// this MUST be false because the observation lag is only 2 months
                                // for ZCIIS; but not for contract if the contract uses a bigger lag.
            ii = boost::shared_ptr<UKRPI>(new UKRPI(interp, hcpi));
            for (Size i=0; i<rpiSchedule.size();i++) {
                ii->addFixing(rpiSchedule[i], fixData[i], true);// force overwrite in case multiple use
            };
            Datum nominalData[] = {
                { Date( 2, June, 2010), 0.499997 },
                { Date( 3, June, 2010), 0.524992 },
                { Date( 8, June, 2010), 0.524974 },
                { Date( 15, June, 2010), 0.549942 },
                { Date( 22, June, 2010), 0.549913 },
                { Date( 1, July, 2010), 0.574864 },
                { Date( 2, August, 2010), 0.624668 },
                { Date( 1, September, 2010), 0.724338 },
                { Date( 16, September, 2010), 0.769461 },
                { Date( 1, December, 2010), 0.997501 },
                //{ Date( 16, December, 2010), 0.838164 },
                { Date( 17, March, 2011), 0.916996 },
                { Date( 16, June, 2011), 0.984339 },
                { Date( 22, September, 2011), 1.06085 },
                { Date( 22, December, 2011), 1.141788 },
                { Date( 1, June, 2012), 1.504426 },
                { Date( 3, June, 2013), 1.92064 },
                { Date( 2, June, 2014), 2.290824 },
                { Date( 1, June, 2015), 2.614394 },
                { Date( 1, June, 2016), 2.887445 },
                { Date( 1, June, 2017), 3.122128 },
                { Date( 1, June, 2018), 3.322511 },
                { Date( 3, June, 2019), 3.483997 },
                { Date( 1, June, 2020), 3.616896 },
                { Date( 1, June, 2022), 3.8281 },
                { Date( 2, June, 2025), 4.0341 },
                { Date( 3, June, 2030), 4.070854 },
                { Date( 1, June, 2035), 4.023202 },
                { Date( 1, June, 2040), 3.954748 },
                { Date( 1, June, 2050), 3.870953 },
                { Date( 1, June, 2060), 3.85298 },
                { Date( 2, June, 2070), 3.757542 },
                { Date( 3, June, 2080), 3.651379 }
            };
            const Size nominalDataLength = 33-1;
            std::vector<Date> nomD;
            std::vector<Rate> nomR;
            for (Size i = 0; i < nominalDataLength; i++) {
                nomD.push_back(nominalData[i].date);
                nomR.push_back(nominalData[i].rate/100.0);
            }
            boost::shared_ptr<YieldTermStructure>   nominalTS
            =   boost::shared_ptr<InterpolatedZeroCurve<Linear>
            >(new InterpolatedZeroCurve<Linear>(nomD,nomR,dcNominal));
            nominalUK.linkTo(nominalTS);
            // now build the zero inflation curve
            observationLag = Period(2,Months);
            contractObservationLag = Period(3,Months);
            contractObservationInterpolation = CPI::Flat;
            Datum zciisData[] = {
                { Date(1, June, 2011), 3.087 },
                { Date(1, June, 2012), 3.12 },
                { Date(1, June, 2013), 3.059 },
                { Date(1, June, 2014), 3.11 },
                { Date(1, June, 2015), 3.15 },
                { Date(1, June, 2016), 3.207 },
                { Date(1, June, 2017), 3.253 },
                { Date(1, June, 2018), 3.288 },
                { Date(1, June, 2019), 3.314 },
                { Date(1, June, 2020), 3.401 },
                { Date(1, June, 2022), 3.458 },
                { Date(1, June, 2025), 3.52 },
                { Date(1, June, 2030), 3.655 },
                { Date(1, June, 2035), 3.668 },
                { Date(1, June, 2040), 3.695 },
                { Date(1, June, 2050), 3.634 },
                { Date(1, June, 2060), 3.629 },
            };
            zciisDataLength = 17;
            for (Size i = 0; i < zciisDataLength; i++) {
                zciisD.push_back(zciisData[i].date);
                zciisR.push_back(zciisData[i].rate);
            }
            // now build the helpers ...
            std::vector<boost::shared_ptr<BootstrapHelper<ZeroInflationTermStructure> > > helpers =
            makeHelpers<ZeroInflationTermStructure,ZeroCouponInflationSwapHelper,
            ZeroInflationIndex>(zciisData, zciisDataLength, ii,
                                observationLag,
                                calendar, convention, dcZCIIS);
            // we can use historical or first ZCIIS for this
            // we know historical is WAY off market-implied, so use market implied flat.
            baseZeroRate = zciisData[0].rate/100.0;
            boost::shared_ptr<PiecewiseZeroInflationCurve<Linear> > pCPIts(
                                new PiecewiseZeroInflationCurve<Linear>(
                                    evaluationDate, calendar, dcZCIIS, observationLag,
                                    ii->frequency(),ii->interpolated(), baseZeroRate,
                                    Handle<YieldTermStructure>(nominalTS), helpers));
            pCPIts->recalculate();
            cpiUK.linkTo(pCPIts);
            hii.linkTo(ii);
            // make sure that the index has the latest zero inflation term structure
            hcpi.linkTo(pCPIts);
            // cpi CF price surf data
            Period cfMat[] = {3*Years, 5*Years, 7*Years, 10*Years, 15*Years, 20*Years, 30*Years};
            Real cStrike[] = {3, 4, 5, 6};
            Real fStrike[] = {-1, 0, 1, 2};
            Size ncStrikes = 4, nfStrikes = 4, ncfMaturities = 7;
            Real cPrice[7][4] = {
                {227.6, 100.27, 38.8, 14.94},
                {345.32, 127.9, 40.59, 14.11},
                {477.95, 170.19, 50.62, 16.88},
                {757.81, 303.95, 107.62, 43.61},
                {1140.73, 481.89, 168.4, 63.65},
                {1537.6, 607.72, 172.27, 54.87},
                {2211.67, 839.24, 184.75, 45.03}};
            Real fPrice[7][4] = {
                {15.62, 28.38, 53.61, 104.6},
                {21.45, 36.73, 66.66, 129.6},
                {24.45, 42.08, 77.04, 152.24},
                {39.25, 63.52, 109.2, 203.44},
                {36.82, 63.62, 116.97, 232.73},
                {39.7, 67.47, 121.79, 238.56},
                {41.48, 73.9, 139.75, 286.75}};
            // now load the data into vector and Matrix classes
            cStrikesUK.clear();
            fStrikesUK.clear();
            cfMaturitiesUK.clear();
            for(Size i = 0; i < ncStrikes; i++) cStrikesUK.push_back(cStrike[i]);
            for(Size i = 0; i < nfStrikes; i++) fStrikesUK.push_back(fStrike[i]);
            for(Size i = 0; i < ncfMaturities; i++) cfMaturitiesUK.push_back(cfMat[i]);
            cPriceUK = boost::shared_ptr<Matrix>(new Matrix(ncStrikes, ncfMaturities));
            fPriceUK = boost::shared_ptr<Matrix>(new Matrix(nfStrikes, ncfMaturities));
            for(Size i = 0; i < ncStrikes; i++) {
                for(Size j = 0; j < ncfMaturities; j++) {
                    (*cPriceUK)[i][j] = cPrice[j][i]/10000.0;
                }
            }
            for(Size i = 0; i < nfStrikes; i++) {
                for(Size j = 0; j < ncfMaturities; j++) {
                    (*fPriceUK)[i][j] = fPrice[j][i]/10000.0;
                }
            }
        }
Member Data Documentation
SavedSettings anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::backup
Definition at line 126 of file inflationcpicapfloor.cpp.
Rate anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::baseZeroRate
Definition at line 92 of file inflationcpicapfloor.cpp.
Calendar anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::calendar
Definition at line 97 of file inflationcpicapfloor.cpp.
vector<Period> anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::cfMaturitiesUK
Definition at line 118 of file inflationcpicapfloor.cpp.
CPI::InterpolationType anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::contractObservationInterpolation
Definition at line 104 of file inflationcpicapfloor.cpp.
Period anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::contractObservationLag
Definition at line 103 of file inflationcpicapfloor.cpp.
BusinessDayConvention anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::convention
Definition at line 98 of file inflationcpicapfloor.cpp.
boost::shared_ptr<CPICapFloorTermPriceSurface> anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::cpiCFsurfUK
Definition at line 122 of file inflationcpicapfloor.cpp.
RelinkableHandle<ZeroInflationTermStructure> anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::cpiUK
Definition at line 113 of file inflationcpicapfloor.cpp.
boost::shared_ptr<Matrix> anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::cPriceUK
Definition at line 119 of file inflationcpicapfloor.cpp.
vector<Rate> anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::cStrikesUK
Definition at line 116 of file inflationcpicapfloor.cpp.
DayCounter anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::dcNominal
Definition at line 105 of file inflationcpicapfloor.cpp.
DayCounter anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::dcZCIIS
Definition at line 105 of file inflationcpicapfloor.cpp.
Date anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::evaluationDate
Definition at line 100 of file inflationcpicapfloor.cpp.
Natural anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::fixingDays
Definition at line 99 of file inflationcpicapfloor.cpp.
boost::shared_ptr<Matrix> anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::fPriceUK
Definition at line 120 of file inflationcpicapfloor.cpp.
Frequency anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::frequency
Definition at line 95 of file inflationcpicapfloor.cpp.
vector<Rate> anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::fStrikesUK
Definition at line 117 of file inflationcpicapfloor.cpp.
RelinkableHandle<ZeroInflationTermStructure> anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::hcpi
Definition at line 114 of file inflationcpicapfloor.cpp.
RelinkableHandle<ZeroInflationIndex> anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::hii
Definition at line 109 of file inflationcpicapfloor.cpp.
boost::shared_ptr<UKRPI> anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::ii
Definition at line 108 of file inflationcpicapfloor.cpp.
Size anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::length
Definition at line 90 of file inflationcpicapfloor.cpp.
std::vector<Real> anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::nominals
Definition at line 96 of file inflationcpicapfloor.cpp.
RelinkableHandle<YieldTermStructure> anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::nominalUK
Definition at line 112 of file inflationcpicapfloor.cpp.
Period anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::observationLag
Definition at line 103 of file inflationcpicapfloor.cpp.
Date anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::settlement
Definition at line 102 of file inflationcpicapfloor.cpp.
Natural anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::settlementDays
Definition at line 101 of file inflationcpicapfloor.cpp.
Date anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::startDate
Definition at line 91 of file inflationcpicapfloor.cpp.
Real anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::volatility
Definition at line 93 of file inflationcpicapfloor.cpp.
std::vector<Date> anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::zciisD
Definition at line 106 of file inflationcpicapfloor.cpp.
Size anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::zciisDataLength
Definition at line 110 of file inflationcpicapfloor.cpp.
std::vector<Rate> anonymous_namespace{inflationcpicapfloor.cpp}::CommonVars::zciisR
Definition at line 107 of file inflationcpicapfloor.cpp.
The documentation for this struct was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/inflationcpicapfloor.cpp