QuantLib: QuantLib::FdmSchemeDesc Struct Reference
QuantLib::FdmSchemeDesc Struct Reference
#include <fdmbackwardsolver.hpp>
Public Types
enum FdmSchemeType {
HundsdorferType, DouglasType, CraigSneydType, ModifiedCraigSneydType,
ImplicitEulerType, ExplicitEulerType
}
Public Member Functions
FdmSchemeDesc (FdmSchemeType type, Real theta, Real mu)
Static Public Member Functions
static FdmSchemeDesc Douglas ()
static FdmSchemeDesc ImplicitEuler ()
static FdmSchemeDesc ExplicitEuler ()
static FdmSchemeDesc CraigSneyd ()
static FdmSchemeDesc ModifiedCraigSneyd ()
static FdmSchemeDesc Hundsdorfer ()
static FdmSchemeDesc ModifiedHundsdorfer ()
Public Attributes
const FdmSchemeType type
const Real theta
const Real mu
Detailed Description
Definition at line 35 of file fdmbackwardsolver.hpp.
Member Enumeration Documentation
enum QuantLib::FdmSchemeDesc::FdmSchemeType
Enumerator:
HundsdorferType
DouglasType
CraigSneydType
ModifiedCraigSneydType
ImplicitEulerType
ExplicitEulerType
Definition at line 36 of file fdmbackwardsolver.hpp.
                           { HundsdorferType, DouglasType,
                             CraigSneydType, ModifiedCraigSneydType,
                             ImplicitEulerType, ExplicitEulerType };
Constructor & Destructor Documentation
QuantLib::FdmSchemeDesc::FdmSchemeDesc (FdmSchemeType type, Real theta, Real mu)
Definition at line 37 of file fdmbackwardsolver.cpp.
Referenced by CraigSneyd(), Douglas(), ExplicitEuler(), Hundsdorfer(), ImplicitEuler(), ModifiedCraigSneyd(), and ModifiedHundsdorfer().
    : type(aType), theta(aTheta), mu(aMu) { }
Member Function Documentation
FdmSchemeDesc QuantLib::FdmSchemeDesc::CraigSneyd () [static]
Definition at line 44 of file fdmbackwardsolver.cpp.
References CraigSneydType, and FdmSchemeDesc().
Referenced by FdHestonTest::testFdmHestonConvergence().
{
        return FdmSchemeDesc(FdmSchemeDesc::CraigSneydType,0.5, 0.5);
    }
FdmSchemeDesc QuantLib::FdmSchemeDesc::Douglas () [static]
Definition at line 40 of file fdmbackwardsolver.cpp.
References DouglasType, and FdmSchemeDesc().
Referenced by FdmLinearOpTest::testCrankNicolsonWithDamping(), BarrierOptionTest::testLocalVolAndHestonComparison(), and EuropeanOptionTest::testLocalVolatility().
{
        return FdmSchemeDesc(FdmSchemeDesc::DouglasType, 0.5, 0.0);
    }
FdmSchemeDesc QuantLib::FdmSchemeDesc::ExplicitEuler () [static]
Definition at line 63 of file fdmbackwardsolver.cpp.
References ExplicitEulerType, and FdmSchemeDesc().
Referenced by FdHestonTest::testFdmHestonBlackScholes().
{
        return FdmSchemeDesc(FdmSchemeDesc::ExplicitEulerType, 0.0, 0.0);
    }
FdmSchemeDesc QuantLib::FdmSchemeDesc::Hundsdorfer () [static]
Definition at line 53 of file fdmbackwardsolver.cpp.
References FdmSchemeDesc(), and HundsdorferType.
Referenced by FdHestonTest::testFdmHestonConvergence(), and FdmLinearOpTest::testFdmHestonHullWhiteOp().
{
        return FdmSchemeDesc(FdmSchemeDesc::HundsdorferType,
                             0.5+std::sqrt(3.0)/6, 0.5);
    }
FdmSchemeDesc QuantLib::FdmSchemeDesc::ImplicitEuler () [static]
Definition at line 67 of file fdmbackwardsolver.cpp.
References FdmSchemeDesc(), and ImplicitEulerType.
{
        return FdmSchemeDesc(FdmSchemeDesc::ImplicitEulerType, 0.0, 0.0);
    }
FdmSchemeDesc QuantLib::FdmSchemeDesc::ModifiedCraigSneyd () [static]
Definition at line 48 of file fdmbackwardsolver.cpp.
References FdmSchemeDesc(), and ModifiedCraigSneydType.
Referenced by FdHestonTest::testFdmHestonConvergence().
{
        return FdmSchemeDesc(FdmSchemeDesc::ModifiedCraigSneydType,
                             1.0/3.0, 1.0/3.0);
    }
FdmSchemeDesc QuantLib::FdmSchemeDesc::ModifiedHundsdorfer () [static]
Definition at line 58 of file fdmbackwardsolver.cpp.
References FdmSchemeDesc(), and HundsdorferType.
Referenced by FdHestonTest::testFdmHestonConvergence().
{
        return FdmSchemeDesc(FdmSchemeDesc::HundsdorferType,
                             1.0-std::sqrt(2.0)/2, 0.5);
    }
Member Data Documentation
const Real QuantLib::FdmSchemeDesc::mu
Definition at line 43 of file fdmbackwardsolver.hpp.
Referenced by QuantLib::FdmBackwardSolver::rollback().
const Real QuantLib::FdmSchemeDesc::theta
Definition at line 43 of file fdmbackwardsolver.hpp.
Referenced by QuantLib::FdmBackwardSolver::rollback().
const FdmSchemeType QuantLib::FdmSchemeDesc::type
Definition at line 42 of file fdmbackwardsolver.hpp.
Referenced by QuantLib::FdmBackwardSolver::rollback().
The documentation for this struct was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/solvers/fdmbackwardsolver.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/methods/finitedifferences/solvers/fdmbackwardsolver.cpp