QuantLib: anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars Struct Reference
anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars Struct Reference
Public Member Functions
CommonVars ()
Leg makeYoYLeg (const Date &startDate, Integer length, const Rate gearing=1.0, const Rate spread=0.0)
Leg makeFixedLeg (const Date &startDate, Integer length)
Leg makeYoYCapFlooredLeg (Size which, const Date &startDate, Integer length, const std::vector< Rate > caps, const std::vector< Rate > floors, Volatility volatility, const Rate gearing=1.0, const Rate spread=0.0)
boost::shared_ptr< PricingEngine > makeEngine (Volatility volatility, Size which)
boost::shared_ptr
< YoYInflationCapFloor > makeYoYCapFloor (YoYInflationCapFloor::Type type, const Leg &leg, Rate strike, Volatility volatility, Size which)
Public Attributes
Size length
Date startDate
Real volatility
Frequency frequency
std::vector< Real > nominals
Calendar calendar
BusinessDayConvention convention
Natural fixingDays
Date evaluationDate
Natural settlementDays
Date settlement
Period observationLag
DayCounter dc
boost::shared_ptr< YYUKRPIr > iir
RelinkableHandle
< YieldTermStructure > nominalTS
boost::shared_ptr
< YoYInflationTermStructure > yoyTS
RelinkableHandle
< YoYInflationTermStructure > hy
SavedSettings backup
Detailed Description
Definition at line 88 of file inflationcapflooredcoupon.cpp.
Constructor & Destructor Documentation
anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::CommonVars () [inline]
Definition at line 116 of file inflationcapflooredcoupon.cpp.
References QuantLib::Calendar::adjust(), QuantLib::Calendar::advance(), QuantLib::Annual, QuantLib::August, anonymous_namespace{marketmodel.cpp}::calendar, QuantLib::Days, QuantLib::Settings::evaluationDate(), QuantLib::MakeSchedule::from(), QuantLib::Singleton< Settings >::instance(), QuantLib::January, LENGTH, anonymous_namespace{inflation.cpp}::makeHelpers(), QuantLib::ModifiedFollowing, QuantLib::Months, QuantLib::Schedule::size(), anonymous_namespace{marketmodel.cpp}::startDate, QuantLib::MakeSchedule::to(), QuantLib::io::volatility(), QuantLib::MakeSchedule::withCalendar(), QuantLib::MakeSchedule::withConvention(), and QuantLib::MakeSchedule::withTenor().
                     {
            // option variables
            nominals = std::vector<Real>(1,1000000);
            frequency = Annual;
            // usual setup
            volatility = 0.01;
            length = 7;
            calendar = UnitedKingdom();
            convention = ModifiedFollowing;
            Date today(13, August, 2007);
            evaluationDate = calendar.adjust(today);
            Settings::instance().evaluationDate() = evaluationDate;
            settlementDays = 0;
            fixingDays = 0;
            settlement = calendar.advance(today,settlementDays,Days);
            startDate = settlement;
            dc = Thirty360();
            // yoy index
            //      fixing data
            Date from(1, January, 2005);
            Date to(13, August, 2007);
            Schedule rpiSchedule = MakeSchedule().from(from).to(to)
            .withTenor(1*Months)
            .withCalendar(UnitedKingdom())
            .withConvention(ModifiedFollowing);
            Real fixData[] = { 189.9, 189.9, 189.6, 190.5, 191.6, 192.0,
                192.2, 192.2, 192.6, 193.1, 193.3, 193.6,
                194.1, 193.4, 194.2, 195.0, 196.5, 197.7,
                198.5, 198.5, 199.2, 200.1, 200.4, 201.1,
                202.7, 201.6, 203.1, 204.4, 205.4, 206.2,
                207.3, -999.0, -999 };
            // link from yoy index to yoy TS
            bool interp = false;
            iir = boost::shared_ptr<YYUKRPIr>(new YYUKRPIr(interp, hy));
            for (Size i=0; i<rpiSchedule.size();i++) {
                iir->addFixing(rpiSchedule[i], fixData[i]);
            }
            boost::shared_ptr<YieldTermStructure> nominalFF(
                        new FlatForward(evaluationDate, 0.05, ActualActual()));
            nominalTS.linkTo(nominalFF);
            // now build the YoY inflation curve
            Period observationLag = Period(2,Months);
            Datum yyData[] = {
                { Date(13, August, 2008), 2.95 },
                { Date(13, August, 2009), 2.95 },
                { Date(13, August, 2010), 2.93 },
                { Date(15, August, 2011), 2.955 },
                { Date(13, August, 2012), 2.945 },
                { Date(13, August, 2013), 2.985 },
                { Date(13, August, 2014), 3.01 },
                { Date(13, August, 2015), 3.035 },
                { Date(13, August, 2016), 3.055 },  // note that
                { Date(13, August, 2017), 3.075 },  // some dates will be on
                { Date(13, August, 2019), 3.105 },  // holidays but the payment
                { Date(15, August, 2022), 3.135 },  // calendar will roll them
                { Date(13, August, 2027), 3.155 },
                { Date(13, August, 2032), 3.145 },
                { Date(13, August, 2037), 3.145 }
            };
            // now build the helpers ...
            std::vector<boost::shared_ptr<BootstrapHelper<YoYInflationTermStructure> > > helpers =
            makeHelpers<YoYInflationTermStructure,YearOnYearInflationSwapHelper,
            YoYInflationIndex>(yyData, LENGTH(yyData), iir,
                               observationLag,
                               calendar, convention, dc);
            Rate baseYYRate = yyData[0].rate/100.0;
            boost::shared_ptr<PiecewiseYoYInflationCurve<Linear> > pYYTS(
                            new PiecewiseYoYInflationCurve<Linear>(
                                evaluationDate, calendar, dc, observationLag,
                                iir->frequency(),iir->interpolated(), baseYYRate,
                                Handle<YieldTermStructure>(nominalTS), helpers));
            pYYTS->recalculate();
            yoyTS = boost::dynamic_pointer_cast<YoYInflationTermStructure>(pYYTS);
            // make sure that the index has the latest yoy term structure
            hy.linkTo(pYYTS);
        }
Member Function Documentation
boost::shared_ptr<PricingEngine> anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::makeEngine (Volatility volatility, Size which) [inline]
Definition at line 307 of file inflationcapflooredcoupon.cpp.
References anonymous_namespace{marketmodel.cpp}::calendar, and QL_FAIL.
{
            boost::shared_ptr<YoYInflationIndex>
            yyii = boost::dynamic_pointer_cast<YoYInflationIndex>(iir);
            Handle<YoYOptionletVolatilitySurface>
            vol(boost::shared_ptr<ConstantYoYOptionletVolatility>(
                    new ConstantYoYOptionletVolatility(volatility,
                            settlementDays,
                            calendar,
                            convention,
                            dc,
                            observationLag,
                            frequency,
                            iir->interpolated())));
            switch (which) {
                case 0:
                    return boost::shared_ptr<PricingEngine>(
                            new YoYInflationBlackCapFloorEngine(iir, vol));
                    break;
                case 1:
                    return boost::shared_ptr<PricingEngine>(
                            new YoYInflationUnitDisplacedBlackCapFloorEngine(iir, vol));
                    break;
                case 2:
                    return boost::shared_ptr<PricingEngine>(
                            new YoYInflationBachelierCapFloorEngine(iir, vol));
                    break;
                default:
                    BOOST_FAIL("unknown engine request: which = "<<which
                               <<"should be 0=Black,1=DD,2=Bachelier");
                    break;
            }
            // make compiler happy
            QL_FAIL("never get here - no engine resolution");
        }
Leg anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::makeFixedLeg (const Date & startDate, Integer length) [inline]
Definition at line 223 of file inflationcapflooredcoupon.cpp.
References QuantLib::Calendar::advance(), anonymous_namespace{marketmodel.cpp}::calendar, anonymous_namespace{marketmodel.cpp}::endDate, QuantLib::DateGeneration::Forward, QuantLib::FixedRateLeg::withCouponRates(), QuantLib::FixedRateLeg::withNotionals(), and QuantLib::Years.
{
            Date endDate = calendar.advance(startDate, length, Years,
                                            convention);
            Schedule schedule(startDate, endDate, Period(frequency), calendar,
                              convention, convention,
                              DateGeneration::Forward, false);
            std::vector<Rate> coupons(length, 0.0);
            return FixedRateLeg(schedule)
            .withNotionals(nominals)
            .withCouponRates(coupons, dc);
        }
boost::shared_ptr<YoYInflationCapFloor> anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::makeYoYCapFloor (YoYInflationCapFloor::Type type, const Leg & leg, Rate strike, Volatility volatility, Size which) [inline]
Definition at line 347 of file inflationcapflooredcoupon.cpp.
References QuantLib::YoYInflationCapFloor::Cap, QuantLib::YoYInflationCapFloor::Floor, and QL_FAIL.
{
            boost::shared_ptr<YoYInflationCapFloor> result;
            switch (type) {
                case YoYInflationCapFloor::Cap:
                    result = boost::shared_ptr<YoYInflationCapFloor>(
                                new YoYInflationCap(leg, std::vector<Rate>(1, strike)));
                    break;
                case YoYInflationCapFloor::Floor:
                    result = boost::shared_ptr<YoYInflationCapFloor>(
                                new YoYInflationFloor(leg, std::vector<Rate>(1, strike)));
                    break;
                default:
                    QL_FAIL("unknown YoYInflation cap/floor type");
            }
            result->setPricingEngine(makeEngine(volatility, which));
            return result;
        }
Leg anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::makeYoYCapFlooredLeg (Size which, const Date & startDate, Integer length, const std::vector< Rate > caps, const std::vector< Rate > floors, Volatility volatility, const Rate gearing = 1.0, const Rate spread = 0.0) [inline]
Definition at line 238 of file inflationcapflooredcoupon.cpp.
References QuantLib::Calendar::advance(), anonymous_namespace{marketmodel.cpp}::calendar, anonymous_namespace{marketmodel.cpp}::endDate, QuantLib::DateGeneration::Forward, QuantLib::Unadjusted, QuantLib::yoyInflationLeg::withCaps(), QuantLib::yoyInflationLeg::withFloors(), QuantLib::yoyInflationLeg::withGearings(), QuantLib::yoyInflationLeg::withNotionals(), QuantLib::yoyInflationLeg::withPaymentAdjustment(), QuantLib::yoyInflationLeg::withPaymentDayCounter(), QuantLib::yoyInflationLeg::withSpreads(), and QuantLib::Years.
{
            Handle<YoYOptionletVolatilitySurface>
            vol(boost::shared_ptr<ConstantYoYOptionletVolatility>(
                            new ConstantYoYOptionletVolatility(volatility,
                                settlementDays,
                                calendar,
                                convention,
                                dc,
                                observationLag,
                                frequency,
                                iir->interpolated())));
            boost::shared_ptr<YoYInflationCouponPricer> pricer;
            switch (which) {
                case 0:
                    pricer = boost::shared_ptr<YoYInflationCouponPricer>(
                            new BlackYoYInflationCouponPricer(vol));
                    break;
                case 1:
                    pricer = boost::shared_ptr<YoYInflationCouponPricer>(
                            new UnitDisplacedBlackYoYInflationCouponPricer(vol));
                    break;
                case 2:
                    pricer = boost::shared_ptr<YoYInflationCouponPricer>(
                            new BachelierYoYInflationCouponPricer(vol));
                    break;
                default:
                    BOOST_FAIL("unknown coupon pricer request: which = "<<which
                               <<"should be 0=Black,1=DD,2=Bachelier");
                    break;
            }
            std::vector<Rate> gearingVector(length, gearing);
            std::vector<Spread> spreadVector(length, spread);
            boost::shared_ptr<YoYInflationIndex> ii =
            boost::dynamic_pointer_cast<YoYInflationIndex>(iir);
            Date endDate = calendar.advance(startDate,length*Years,Unadjusted);
            Schedule schedule(startDate, endDate, Period(frequency), calendar,
                              Unadjusted,Unadjusted,// ref periods & acc periods
                              DateGeneration::Forward, false);
            Leg yoyLeg =  yoyInflationLeg(schedule, calendar, ii, observationLag)
            .withNotionals(nominals)
            .withPaymentDayCounter(dc)
            .withPaymentAdjustment(convention)
            .withGearings(gearingVector)
            .withSpreads(spreadVector)
            .withCaps(caps)
            .withFloors(floors);
            for(Size i=0; i<yoyLeg.size(); i++) {
                boost::dynamic_pointer_cast<YoYInflationCoupon>(yoyLeg[i])->setPricer(pricer);
            }
            //setCouponPricer(iborLeg, pricer);
            return yoyLeg;
        }
Leg anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::makeYoYLeg (const Date & startDate, Integer length, const Rate gearing = 1.0, const Rate spread = 0.0) [inline]
Definition at line 202 of file inflationcapflooredcoupon.cpp.
References QuantLib::Calendar::advance(), anonymous_namespace{marketmodel.cpp}::calendar, anonymous_namespace{marketmodel.cpp}::endDate, QuantLib::DateGeneration::Forward, QuantLib::Unadjusted, QuantLib::yoyInflationLeg::withGearings(), QuantLib::yoyInflationLeg::withNotionals(), QuantLib::yoyInflationLeg::withPaymentAdjustment(), QuantLib::yoyInflationLeg::withPaymentDayCounter(), QuantLib::yoyInflationLeg::withSpreads(), and QuantLib::Years.
{
            boost::shared_ptr<YoYInflationIndex> ii =
            boost::dynamic_pointer_cast<YoYInflationIndex>(iir);
            Date endDate = calendar.advance(startDate,length*Years,Unadjusted);
            Schedule schedule(startDate, endDate, Period(frequency), calendar,
                              Unadjusted,Unadjusted,// ref periods & acc periods
                              DateGeneration::Forward, false);
            std::vector<Rate> gearingVector(length, gearing);
            std::vector<Spread> spreadVector(length, spread);
            return yoyInflationLeg(schedule, calendar, ii, observationLag)
            .withNotionals(nominals)
            .withPaymentDayCounter(dc)
            .withGearings(gearingVector)
            .withSpreads(spreadVector)
            .withPaymentAdjustment(convention);
        }
Member Data Documentation
SavedSettings anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::backup
Definition at line 113 of file inflationcapflooredcoupon.cpp.
Calendar anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::calendar
Definition at line 97 of file inflationcapflooredcoupon.cpp.
BusinessDayConvention anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::convention
Definition at line 98 of file inflationcapflooredcoupon.cpp.
DayCounter anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::dc
Definition at line 104 of file inflationcapflooredcoupon.cpp.
Date anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::evaluationDate
Definition at line 100 of file inflationcapflooredcoupon.cpp.
Natural anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::fixingDays
Definition at line 99 of file inflationcapflooredcoupon.cpp.
Frequency anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::frequency
Definition at line 95 of file inflationcapflooredcoupon.cpp.
RelinkableHandle<YoYInflationTermStructure> anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::hy
Definition at line 109 of file inflationcapflooredcoupon.cpp.
boost::shared_ptr<YYUKRPIr> anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::iir
Definition at line 105 of file inflationcapflooredcoupon.cpp.
Size anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::length
Definition at line 91 of file inflationcapflooredcoupon.cpp.
std::vector<Real> anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::nominals
Definition at line 96 of file inflationcapflooredcoupon.cpp.
RelinkableHandle<YieldTermStructure> anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::nominalTS
Definition at line 107 of file inflationcapflooredcoupon.cpp.
Period anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::observationLag
Definition at line 103 of file inflationcapflooredcoupon.cpp.
Date anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::settlement
Definition at line 102 of file inflationcapflooredcoupon.cpp.
Natural anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::settlementDays
Definition at line 101 of file inflationcapflooredcoupon.cpp.
Date anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::startDate
Definition at line 92 of file inflationcapflooredcoupon.cpp.
Real anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::volatility
Definition at line 93 of file inflationcapflooredcoupon.cpp.
boost::shared_ptr<YoYInflationTermStructure> anonymous_namespace{inflationcapflooredcoupon.cpp}::CommonVars::yoyTS
Definition at line 108 of file inflationcapflooredcoupon.cpp.
The documentation for this struct was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/inflationcapflooredcoupon.cpp