QuantLib: QuantLib::IMM Struct Reference
QuantLib::IMM Struct Reference
Main cycle of the International Money Market (a.k.a. IMM) months.
#include <imm.hpp>
Public Types
enum Month {
F = 1, G = 2, H = 3, J = 4,
K = 5, M = 6, N = 7, Q = 8,
U = 9, V = 10, X = 11, Z = 12
}
Static Public Member Functions
static bool isIMMdate (const Date &d, bool mainCycle=true)
returns whether or not the given date is an IMM date
static bool isIMMcode (const std::string &in, bool mainCycle=true)
returns whether or not the given string is an IMM code
static std::string code (const Date &immDate)
static Date date (const std::string &immCode, const Date &referenceDate=Date())
static Date nextDate (const Date &d=Date(), bool mainCycle=true)
next IMM date following the given date
static Date nextDate (const std::string &immCode, bool mainCycle=true, const Date &referenceDate=Date())
next IMM date following the given IMM code
static std::string nextCode (const Date &d=Date(), bool mainCycle=true)
next IMM code following the given date
static std::string nextCode (const std::string &immCode, bool mainCycle=true, const Date &referenceDate=Date())
next IMM code following the given code
Detailed Description
Main cycle of the International Money Market (a.k.a. IMM) months.
Definition at line 35 of file imm.hpp.
Member Enumeration Documentation
enum QuantLib::IMM::Month
Enumerator:
F
G
H
J
K
M
N
Q
U
V
X
Z
Definition at line 36 of file imm.hpp.
                   { F =  1, G =  2, H =  3,
                     J =  4, K =  5, M =  6,
                     N =  7, Q =  8, U =  9,
                     V = 10, X = 11, Z = 12 };
Member Function Documentation
std::string QuantLib::IMM::code (const Date & immDate) [static]
returns the IMM code for the given date (e.g. H3 for March 20th, 2013).
Warning:
It raises an exception if the input date is not an IMM date
Definition at line 72 of file imm.cpp.
References QuantLib::April, QuantLib::August, QuantLib::December, QuantLib::February, isIMMcode(), isIMMdate(), QuantLib::January, QuantLib::July, QuantLib::June, QuantLib::March, QuantLib::May, QuantLib::Date::month(), QuantLib::November, QuantLib::October, QL_ENSURE, QL_FAIL, QL_REQUIRE, QuantLib::September, and QuantLib::Date::year().
Referenced by date(), DateTest::immDates(), and nextCode().
{
        QL_REQUIRE(isIMMdate(date, false),
                   date << " is not an IMM date");
        std::ostringstream IMMcode;
        unsigned int y = date.year() % 10;
        switch(date.month()) {
          case January:
            IMMcode << 'F' << y;
            break;
          case February:
            IMMcode << 'G' << y;
            break;
          case March:
            IMMcode << 'H' << y;
            break;
          case April:
            IMMcode << 'J' << y;
            break;
          case May:
            IMMcode << 'K' << y;
            break;
          case June:
            IMMcode << 'M' << y;
            break;
          case July:
            IMMcode << 'N' << y;
            break;
          case August:
            IMMcode << 'Q' << y;
            break;
          case September:
            IMMcode << 'U' << y;
            break;
          case October:
            IMMcode << 'V' << y;
            break;
          case November:
            IMMcode << 'X' << y;
            break;
          case December:
            IMMcode << 'Z' << y;
            break;
          default:
            QL_FAIL("not an IMM month (and it should have been)");
        }
        #if defined(QL_EXTRA_SAFETY_CHECKS)
        QL_ENSURE(isIMMcode(IMMcode.str(), false),
                  "the result " << IMMcode.str() <<
                  " is an invalid IMM code");
        #endif
        return IMMcode.str();
    }
Date QuantLib::IMM::date (const std::string & immCode, const Date & referenceDate = Date()) [static]
returns the IMM date for the given IMM code (e.g. March 20th, 2013 for H3).
Warning:
It raises an exception if the input string is not an IMM code
Definition at line 127 of file imm.cpp.
References QuantLib::April, QuantLib::August, code(), QuantLib::December, QuantLib::February, QuantLib::Singleton< Settings >::instance(), isIMMcode(), QuantLib::January, QuantLib::July, QuantLib::June, QuantLib::March, QuantLib::May, nextDate(), QuantLib::November, QuantLib::October, QL_FAIL, QL_REQUIRE, QuantLib::September, QuantLib::io::to_integer(), and QuantLib::Date::year().
Referenced by DateTest::immDates(), nextCode(), and nextDate().
{
        QL_REQUIRE(isIMMcode(immCode, false),
                   immCode << " is not a valid IMM code");
        Date referenceDate = (refDate != Date() ?
                              refDate :
                              Date(Settings::instance().evaluationDate()));
        std::string code = to_upper_copy(immCode);
        std::string ms = code.substr(0,1);
        QuantLib::Month m;
        if (ms=="F")      m = January;
        else if (ms=="G") m = February;
        else if (ms=="H") m = March;
        else if (ms=="J") m = April;
        else if (ms=="K") m = May;
        else if (ms=="M") m = June;
        else if (ms=="N") m = July;
        else if (ms=="Q") m = August;
        else if (ms=="U") m = September;
        else if (ms=="V") m = October;
        else if (ms=="X") m = November;
        else if (ms=="Z") m = December;
        else QL_FAIL("invalid IMM month letter");
//        Year y = boost::lexical_cast<Year>(); // lexical_cast causes compilation errors with x64
        Year y= io::to_integer(code.substr(1,1));
        /* year<1900 are not valid QuantLib years: to avoid a run-time
           exception few lines below we need to add 10 years right away */
        if (y==0 && referenceDate.year()<=1909) y+=10;
        Year referenceYear = (referenceDate.year() % 10);
        y += referenceDate.year() - referenceYear;
        Date result = IMM::nextDate(Date(1, m, y), false);
        if (result<referenceDate)
            return IMM::nextDate(Date(1, m, y+10), false);
        return result;
    }
bool QuantLib::IMM::isIMMcode (const std::string & in, bool mainCycle = true) [static]
returns whether or not the given string is an IMM code
Definition at line 54 of file imm.cpp.
Referenced by code(), and date().
{
        if (in.length() != 2)
            return false;
        string str1("0123456789");
        string::size_type loc = str1.find(in.substr(1,1), 0);
        if (loc == string::npos)
            return false;
        if (mainCycle) str1 = "hmzuHMZU";
        else           str1 = "fghjkmnquvxzFGHJKMNQUVXZ";
        loc = str1.find(in.substr(0,1), 0);
        if (loc == string::npos)
            return false;
        return true;
    }
bool QuantLib::IMM::isIMMdate (const Date & d, bool mainCycle = true) [static]
returns whether or not the given date is an IMM date
Definition at line 33 of file imm.cpp.
References anonymous_namespace{marketmodel.cpp}::d, QuantLib::Date::dayOfMonth(), QuantLib::December, QuantLib::June, QuantLib::March, QuantLib::Date::month(), QuantLib::September, QuantLib::Wednesday, and QuantLib::Date::weekday().
Referenced by code(), QuantLib::FuturesRateHelper::FuturesRateHelper(), DateTest::immDates(), and QuantLib::Schedule::Schedule().
{
        if (date.weekday()!=Wednesday)
            return false;
        Day d = date.dayOfMonth();
        if (d<15 || d>21)
            return false;
        if (!mainCycle) return true;
        switch (date.month()) {
          case March:
          case June:
          case September:
          case December:
            return true;
          default:
            return false;
        }
    }
std::string QuantLib::IMM::nextCode (const Date & d = Date(), bool mainCycle = true) [static]
next IMM code following the given date
returns the IMM code for next contract listed in the International Money Market section of the Chicago Mercantile Exchange.
Definition at line 200 of file imm.cpp.
References code(), date(), and nextDate().
{
        Date date = nextDate(d, mainCycle);
        return code(date);
    }
std::string QuantLib::IMM::nextCode (const std::string & immCode, bool mainCycle = true, const Date & referenceDate = Date()) [static]
next IMM code following the given code
returns the IMM code for next contract listed in the International Money Market section of the Chicago Mercantile Exchange.
Definition at line 206 of file imm.cpp.
References code(), date(), and nextDate().
{
        Date date = nextDate(immCode, mainCycle, referenceDate);
        return code(date);
    }
Date QuantLib::IMM::nextDate (const Date & d = Date(), bool mainCycle = true) [static]
next IMM date following the given date
returns the 1st delivery date for next contract listed in the International Money Market section of the Chicago Mercantile Exchange.
Definition at line 168 of file imm.cpp.
References date(), QuantLib::Date::dayOfMonth(), QuantLib::Singleton< Settings >::instance(), QuantLib::Date::month(), QuantLib::Date::nthWeekday(), QuantLib::Wednesday, and QuantLib::Date::year().
Referenced by date(), QuantLib::FuturesRateHelper::FuturesRateHelper(), DateTest::immDates(), nextCode(), and nextDate().
{
        Date refDate = (date == Date() ?
                        Date(Settings::instance().evaluationDate()) :
                        date);
        Year y = refDate.year();
        QuantLib::Month m = refDate.month();
        Size offset = mainCycle ? 3 : 1;
        Size skipMonths = offset-(m%offset);
        if (skipMonths != offset || refDate.dayOfMonth() > 21) {
            skipMonths += Size(m);
            if (skipMonths<=12) {
                m = QuantLib::Month(skipMonths);
            } else {
                m = QuantLib::Month(skipMonths-12);
                y += 1;
            }
        }
        Date result = Date::nthWeekday(3, Wednesday, m, y);
        if (result<=refDate)
            result = nextDate(Date(22, m, y), mainCycle);
        return result;
    }
Date QuantLib::IMM::nextDate (const std::string & immCode, bool mainCycle = true, const Date & referenceDate = Date()) [static]
next IMM date following the given IMM code
returns the 1st delivery date for next contract listed in the International Money Market section of the Chicago Mercantile Exchange.
Definition at line 193 of file imm.cpp.
References date(), and nextDate().
{
        Date immDate = date(IMMcode, referenceDate);
        return nextDate(immDate+1, mainCycle);
    }
The documentation for this struct was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/time/imm.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/time/imm.cpp