QuantLib: anonymous_namespace{swap.cpp}::CommonVars Struct Reference
anonymous_namespace{swap.cpp}::CommonVars Struct Reference
Public Member Functions
boost::shared_ptr< VanillaSwap > makeSwap (Integer length, Rate fixedRate, Spread floatingSpread)
CommonVars ()
Public Attributes
Date today
Date settlement
VanillaSwap::Type type
Real nominal
Calendar calendar
BusinessDayConvention fixedConvention
BusinessDayConvention floatingConvention
Frequency fixedFrequency
Frequency floatingFrequency
DayCounter fixedDayCount
boost::shared_ptr< IborIndex > index
Natural settlementDays
RelinkableHandle
< YieldTermStructure > termStructure
SavedSettings backup
Detailed Description
Definition at line 44 of file swap.cpp.
Constructor & Destructor Documentation
anonymous_namespace{swap.cpp}::CommonVars::CommonVars () [inline]
Definition at line 83 of file swap.cpp.
References QuantLib::Calendar::adjust(), QuantLib::Annual, anonymous_namespace{marketmodel.cpp}::calendar, QuantLib::Days, QuantLib::Settings::evaluationDate(), QuantLib::flatRate(), QuantLib::Singleton< Settings >::instance(), QuantLib::ModifiedFollowing, QuantLib::VanillaSwap::Payer, QuantLib::Semiannual, QuantLib::Date::todaysDate(), and QuantLib::Unadjusted.
                     {
            type = VanillaSwap::Payer;
            settlementDays = 2;
            nominal = 100.0;
            fixedConvention = Unadjusted;
            floatingConvention = ModifiedFollowing;
            fixedFrequency = Annual;
            floatingFrequency = Semiannual;
            fixedDayCount = Thirty360();
            index = boost::shared_ptr<IborIndex>(new
                Euribor(Period(floatingFrequency), termStructure));
            calendar = index->fixingCalendar();
            today = calendar.adjust(Date::todaysDate());
            Settings::instance().evaluationDate() = today;
            settlement = calendar.advance(today,settlementDays,Days);
            termStructure.linkTo(flatRate(settlement,0.05,Actual365Fixed()));
        }
Member Function Documentation
boost::shared_ptr<VanillaSwap> anonymous_namespace{swap.cpp}::CommonVars::makeSwap (Integer length, Rate fixedRate, Spread floatingSpread) [inline]
Definition at line 61 of file swap.cpp.
References QuantLib::Calendar::advance(), anonymous_namespace{marketmodel.cpp}::calendar, QuantLib::DateGeneration::Forward, QuantLib::swap(), and QuantLib::Years.
{
            Date maturity = calendar.advance(settlement,length,Years,
                                             floatingConvention);
            Schedule fixedSchedule(settlement,maturity,Period(fixedFrequency),
                                   calendar,fixedConvention,fixedConvention,
                                   DateGeneration::Forward,false);
            Schedule floatSchedule(settlement,maturity,
                                   Period(floatingFrequency),
                                   calendar,floatingConvention,
                                   floatingConvention,
                                   DateGeneration::Forward,false);
            boost::shared_ptr<VanillaSwap> swap(
                new VanillaSwap(type, nominal,
                                fixedSchedule, fixedRate, fixedDayCount,
                                floatSchedule, index, floatingSpread,
                                index->dayCounter()));
            swap->setPricingEngine(boost::shared_ptr<PricingEngine>(
                                  new DiscountingSwapEngine(termStructure)));
            return swap;
        }
Member Data Documentation
SavedSettings anonymous_namespace{swap.cpp}::CommonVars::backup
Definition at line 58 of file swap.cpp.
Calendar anonymous_namespace{swap.cpp}::CommonVars::calendar
Definition at line 49 of file swap.cpp.
BusinessDayConvention anonymous_namespace{swap.cpp}::CommonVars::fixedConvention
Definition at line 50 of file swap.cpp.
DayCounter anonymous_namespace{swap.cpp}::CommonVars::fixedDayCount
Definition at line 52 of file swap.cpp.
Frequency anonymous_namespace{swap.cpp}::CommonVars::fixedFrequency
Definition at line 51 of file swap.cpp.
BusinessDayConvention anonymous_namespace{swap.cpp}::CommonVars::floatingConvention
Definition at line 50 of file swap.cpp.
Frequency anonymous_namespace{swap.cpp}::CommonVars::floatingFrequency
Definition at line 51 of file swap.cpp.
boost::shared_ptr<IborIndex> anonymous_namespace{swap.cpp}::CommonVars::index
Definition at line 53 of file swap.cpp.
Real anonymous_namespace{swap.cpp}::CommonVars::nominal
Definition at line 48 of file swap.cpp.
Date anonymous_namespace{swap.cpp}::CommonVars::settlement
Definition at line 46 of file swap.cpp.
Natural anonymous_namespace{swap.cpp}::CommonVars::settlementDays
Definition at line 54 of file swap.cpp.
RelinkableHandle<YieldTermStructure> anonymous_namespace{swap.cpp}::CommonVars::termStructure
Definition at line 55 of file swap.cpp.
Date anonymous_namespace{swap.cpp}::CommonVars::today
Definition at line 46 of file swap.cpp.
VanillaSwap::Type anonymous_namespace{swap.cpp}::CommonVars::type
Definition at line 47 of file swap.cpp.
The documentation for this struct was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/swap.cpp