QuantLib: anonymous_namespace{curvestates.cpp}::CommonVars Struct Reference
anonymous_namespace{curvestates.cpp}::CommonVars Struct Reference
Public Member Functions
CommonVars ()
Public Attributes
Date todaysDate
Date startDate
Date endDate
std::vector< Time > rateTimes
std::vector< Time > paymentTimes
std::vector< Real > accruals
Calendar calendar
DayCounter dayCounter
std::vector< Rate > todaysForwards
std::vector< Rate > todaysCoterminalSwapRates
std::vector< Real > coterminalAnnuity
Spread displacement
std::vector< DiscountFactor > todaysDiscounts
SavedSettings backup
Detailed Description
Definition at line 51 of file curvestates.cpp.
Constructor & Destructor Documentation
anonymous_namespace{curvestates.cpp}::CommonVars::CommonVars () [inline]
Definition at line 66 of file curvestates.cpp.
References anonymous_namespace{marketmodel.cpp}::accruals, QuantLib::DateGeneration::Backward, anonymous_namespace{marketmodel.cpp}::calendar, anonymous_namespace{marketmodel.cpp}::coterminalAnnuity, anonymous_namespace{marketmodel.cpp}::dates, anonymous_namespace{marketmodel.cpp}::dayCounter, anonymous_namespace{marketmodel.cpp}::displacement, anonymous_namespace{marketmodel.cpp}::endDate, QuantLib::Settings::evaluationDate(), QuantLib::Following, QuantLib::Singleton< Settings >::instance(), anonymous_namespace{matrices.cpp}::N, anonymous_namespace{marketmodel.cpp}::paymentTimes, anonymous_namespace{marketmodel.cpp}::rateTimes, QuantLib::Semiannual, QuantLib::Schedule::size(), anonymous_namespace{marketmodel.cpp}::todaysCoterminalSwapRates, anonymous_namespace{marketmodel.cpp}::todaysDate, anonymous_namespace{marketmodel.cpp}::todaysDiscounts, anonymous_namespace{marketmodel.cpp}::todaysForwards, and QuantLib::Years.
                     {
            // Times
            calendar = NullCalendar();
            todaysDate = Settings::instance().evaluationDate();
            //startDate = todaysDate + 5*Years;
            endDate = todaysDate + 10*Years;
            Schedule dates(todaysDate, endDate, Period(Semiannual),
                           calendar, Following, Following,
                           DateGeneration::Backward, false);
            rateTimes = std::vector<Time>(dates.size()-1);
            paymentTimes = std::vector<Time>(rateTimes.size()-1);
            accruals = std::vector<Real>(rateTimes.size()-1);
            dayCounter = SimpleDayCounter();
            for (Size i=1; i<dates.size(); ++i)
                rateTimes[i-1] = dayCounter.yearFraction(todaysDate, dates[i]);
            std::copy(rateTimes.begin()+1, rateTimes.end(),
                      paymentTimes.begin());
            for (Size i=1; i<rateTimes.size(); ++i)
                accruals[i-1] = rateTimes[i] - rateTimes[i-1];
            // Rates & displacement
            todaysForwards = std::vector<Rate>(paymentTimes.size());
            displacement = 0.0;
            for (Size i=0; i<todaysForwards.size(); ++i)
                todaysForwards[i] = 0.03 + 0.0010*i;
            // Discounts
            todaysDiscounts = std::vector<DiscountFactor>(rateTimes.size());
            todaysDiscounts[0] = 0.95;
            for (Size i=1; i<rateTimes.size(); ++i)
                todaysDiscounts[i] = todaysDiscounts[i-1] /
                    (1.0+todaysForwards[i-1]*accruals[i-1]);
            // Coterminal swap rates & annuities
            Size N = todaysForwards.size();
            todaysCoterminalSwapRates = std::vector<Rate>(N);
            coterminalAnnuity = std::vector<Real>(N);
            Real floatingLeg = 0.0;
            for (Size i=1; i<=N; ++i) {
                if (i==1) {
                    coterminalAnnuity[N-1] = accruals[N-1]*todaysDiscounts[N];
                } else {
                    coterminalAnnuity[N-i] = coterminalAnnuity[N-i+1] +
                        accruals[N-i]*todaysDiscounts[N-i+1];
                }
                floatingLeg = todaysDiscounts[N-i]-todaysDiscounts[N];
                todaysCoterminalSwapRates[N-i] =
                    floatingLeg/coterminalAnnuity[N-i];
            }
            std::vector<Time> evolutionTimes(rateTimes.size()-1);
            std::copy(rateTimes.begin(), rateTimes.end()-1,
                      evolutionTimes.begin());
            EvolutionDescription evolution(rateTimes,evolutionTimes);
            std::vector<Real> rateTaus = evolution.rateTaus();
            std::vector<Size> alive = evolution.firstAliveRate();
        }
Member Data Documentation
std::vector<Real> anonymous_namespace{curvestates.cpp}::CommonVars::accruals
Definition at line 55 of file curvestates.cpp.
SavedSettings anonymous_namespace{curvestates.cpp}::CommonVars::backup
Definition at line 64 of file curvestates.cpp.
Calendar anonymous_namespace{curvestates.cpp}::CommonVars::calendar
Definition at line 56 of file curvestates.cpp.
std::vector<Real> anonymous_namespace{curvestates.cpp}::CommonVars::coterminalAnnuity
Definition at line 59 of file curvestates.cpp.
DayCounter anonymous_namespace{curvestates.cpp}::CommonVars::dayCounter
Definition at line 57 of file curvestates.cpp.
Spread anonymous_namespace{curvestates.cpp}::CommonVars::displacement
Definition at line 60 of file curvestates.cpp.
Date anonymous_namespace{curvestates.cpp}::CommonVars::endDate
Definition at line 53 of file curvestates.cpp.
std::vector<Time> anonymous_namespace{curvestates.cpp}::CommonVars::paymentTimes
Definition at line 54 of file curvestates.cpp.
std::vector<Time> anonymous_namespace{curvestates.cpp}::CommonVars::rateTimes
Definition at line 54 of file curvestates.cpp.
Date anonymous_namespace{curvestates.cpp}::CommonVars::startDate
Definition at line 53 of file curvestates.cpp.
std::vector<Rate> anonymous_namespace{curvestates.cpp}::CommonVars::todaysCoterminalSwapRates
Definition at line 58 of file curvestates.cpp.
Date anonymous_namespace{curvestates.cpp}::CommonVars::todaysDate
Definition at line 53 of file curvestates.cpp.
std::vector<DiscountFactor> anonymous_namespace{curvestates.cpp}::CommonVars::todaysDiscounts
Definition at line 61 of file curvestates.cpp.
std::vector<Rate> anonymous_namespace{curvestates.cpp}::CommonVars::todaysForwards
Definition at line 58 of file curvestates.cpp.
The documentation for this struct was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/curvestates.cpp