QuantLib: anonymous_namespace{bonds.cpp}::CommonVars Struct Reference
anonymous_namespace{bonds.cpp}::CommonVars Struct Reference
Public Member Functions
CommonVars ()
Public Attributes
Calendar calendar
Date today
Real faceAmount
SavedSettings backup
Detailed Description
Definition at line 51 of file bonds.cpp.
Constructor & Destructor Documentation
anonymous_namespace{bonds.cpp}::CommonVars::CommonVars () [inline]
Definition at line 61 of file bonds.cpp.
References QuantLib::Calendar::adjust(), anonymous_namespace{marketmodel.cpp}::calendar, QuantLib::Settings::evaluationDate(), QuantLib::Singleton< Settings >::instance(), and QuantLib::Date::todaysDate().
                     {
            calendar = TARGET();
            today = calendar.adjust(Date::todaysDate());
            Settings::instance().evaluationDate() = today;
            faceAmount = 1000000.0;
        }
Member Data Documentation
SavedSettings anonymous_namespace{bonds.cpp}::CommonVars::backup
Definition at line 58 of file bonds.cpp.
Calendar anonymous_namespace{bonds.cpp}::CommonVars::calendar
Definition at line 53 of file bonds.cpp.
Real anonymous_namespace{bonds.cpp}::CommonVars::faceAmount
Definition at line 55 of file bonds.cpp.
Date anonymous_namespace{bonds.cpp}::CommonVars::today
Definition at line 54 of file bonds.cpp.
The documentation for this struct was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/bonds.cpp