QuantLib: QuantLib::BondFunctions Struct Reference
QuantLib::BondFunctions Struct Reference
Bond adapters of CashFlows functions.
#include <bondfunctions.hpp>
Static Public Member Functions
Date inspectors
static Date startDate (const Bond &bond)
static Date maturityDate (const Bond &bond)
static bool isTradable (const Bond &bond, Date settlementDate=Date())
CashFlow inspectors
static Leg::const_reverse_iterator previousCashFlow (const Bond &bond, Date refDate=Date())
static Leg::const_iterator nextCashFlow (const Bond &bond, Date refDate=Date())
static Date previousCashFlowDate (const Bond &bond, Date refDate=Date())
static Date nextCashFlowDate (const Bond &bond, Date refDate=Date())
static Real previousCashFlowAmount (const Bond &bond, Date refDate=Date())
static Real nextCashFlowAmount (const Bond &bond, Date refDate=Date())
Coupon inspectors
static Rate previousCouponRate (const Bond &bond, Date settlementDate=Date())
static Rate nextCouponRate (const Bond &bond, Date settlementDate=Date())
static Date accrualStartDate (const Bond &bond, Date settlementDate=Date())
static Date accrualEndDate (const Bond &bond, Date settlementDate=Date())
static Date referencePeriodStart (const Bond &bond, Date settlementDate=Date())
static Date referencePeriodEnd (const Bond &bond, Date settlementDate=Date())
static Time accrualPeriod (const Bond &bond, Date settlementDate=Date())
static BigInteger accrualDays (const Bond &bond, Date settlementDate=Date())
static Time accruedPeriod (const Bond &bond, Date settlementDate=Date())
static BigInteger accruedDays (const Bond &bond, Date settlementDate=Date())
static Real accruedAmount (const Bond &bond, Date settlementDate=Date())
YieldTermStructure functions
static Real cleanPrice (const Bond &bond, const YieldTermStructure &discountCurve, Date settlementDate=Date())
static Real bps (const Bond &bond, const YieldTermStructure &discountCurve, Date settlementDate=Date())
static Rate atmRate (const Bond &bond, const YieldTermStructure &discountCurve, Date settlementDate=Date(), Real cleanPrice=Null< Real >())
Yield (a.k.a. Internal Rate of Return, i.e. IRR) functions
static Real cleanPrice (const Bond &bond, const InterestRate &yield, Date settlementDate=Date())
static Real cleanPrice (const Bond &bond, Rate yield, const DayCounter &dayCounter, Compounding compounding, Frequency frequency, Date settlementDate=Date())
static Real bps (const Bond &bond, const InterestRate &yield, Date settlementDate=Date())
static Real bps (const Bond &bond, Rate yield, const DayCounter &dayCounter, Compounding compounding, Frequency frequency, Date settlementDate=Date())
static Rate yield (const Bond &bond, Real cleanPrice, const DayCounter &dayCounter, Compounding compounding, Frequency frequency, Date settlementDate=Date(), Real accuracy=1.0e-10, Size maxIterations=100, Rate guess=0.05)
static Time duration (const Bond &bond, const InterestRate &yield, Duration::Type type=Duration::Modified, Date settlementDate=Date())
static Time duration (const Bond &bond, Rate yield, const DayCounter &dayCounter, Compounding compounding, Frequency frequency, Duration::Type type=Duration::Modified, Date settlementDate=Date())
static Real convexity (const Bond &bond, const InterestRate &yield, Date settlementDate=Date())
static Real convexity (const Bond &bond, Rate yield, const DayCounter &dayCounter, Compounding compounding, Frequency frequency, Date settlementDate=Date())
static Real basisPointValue (const Bond &bond, const InterestRate &yield, Date settlementDate=Date())
static Real basisPointValue (const Bond &bond, Rate yield, const DayCounter &dayCounter, Compounding compounding, Frequency frequency, Date settlementDate=Date())
static Real yieldValueBasisPoint (const Bond &bond, const InterestRate &yield, Date settlementDate=Date())
static Real yieldValueBasisPoint (const Bond &bond, Rate yield, const DayCounter &dayCounter, Compounding compounding, Frequency frequency, Date settlementDate=Date())
Z-spread functions
static Real cleanPrice (const Bond &bond, const boost::shared_ptr< YieldTermStructure > &discount, Spread zSpread, const DayCounter &dayCounter, Compounding compounding, Frequency frequency, Date settlementDate=Date())
static Spread zSpread (const Bond &bond, Real cleanPrice, const boost::shared_ptr< YieldTermStructure > &, const DayCounter &dayCounter, Compounding compounding, Frequency frequency, Date settlementDate=Date(), Real accuracy=1.0e-10, Size maxIterations=100, Rate guess=0.0)
Detailed Description
Bond adapters of CashFlows functions.
See CashFlows for functions' documentation.
These adapters calls into CashFlows functions passing as input the Bond cashflows, the dirty price (i.e. npv) calculated from clean price, the bond settlement date (unless another date is given), zero ex-dividend days, and excluding any cashflow on the settlement date.
Prices are always clean, as per market convention.
Definition at line 52 of file bondfunctions.hpp.
Member Function Documentation
BigInteger QuantLib::BondFunctions::accrualDays (const Bond & bond, Date settlementDate = Date()) [static]
Definition at line 188 of file bondfunctions.cpp.
References QuantLib::Bond::cashflows(), isTradable(), QuantLib::Bond::maturityDate(), QL_REQUIRE, and QuantLib::Bond::settlementDate().
{
        if (settlement == Date())
            settlement = bond.settlementDate();
        QL_REQUIRE(BondFunctions::isTradable(bond, settlement),
                   "non tradable at " << settlement <<
                   " (maturity being " << bond.maturityDate() << ")");
        return CashFlows::accrualDays(bond.cashflows(),
                                      false, settlement);
    }
Date QuantLib::BondFunctions::accrualEndDate (const Bond & bond, Date settlementDate = Date()) [static]
Definition at line 136 of file bondfunctions.cpp.
References QuantLib::Bond::cashflows(), isTradable(), QuantLib::Bond::maturityDate(), QL_REQUIRE, and QuantLib::Bond::settlementDate().
{
        if (settlement == Date())
            settlement = bond.settlementDate();
        QL_REQUIRE(BondFunctions::isTradable(bond, settlement),
                   "non tradable at " << settlement <<
                   " (maturity being " << bond.maturityDate() << ")");
        return CashFlows::accrualEndDate(bond.cashflows(),
                                         false, settlement);
    }
Time QuantLib::BondFunctions::accrualPeriod (const Bond & bond, Date settlementDate = Date()) [static]
Definition at line 175 of file bondfunctions.cpp.
References QuantLib::Bond::cashflows(), isTradable(), QuantLib::Bond::maturityDate(), QL_REQUIRE, and QuantLib::Bond::settlementDate().
{
        if (settlement == Date())
            settlement = bond.settlementDate();
        QL_REQUIRE(BondFunctions::isTradable(bond, settlement),
                   "non tradable at " << settlement <<
                   " (maturity being " << bond.maturityDate() << ")");
        return CashFlows::accrualPeriod(bond.cashflows(),
                                        false, settlement);
    }
Date QuantLib::BondFunctions::accrualStartDate (const Bond & bond, Date settlementDate = Date()) [static]
Definition at line 123 of file bondfunctions.cpp.
References QuantLib::Bond::cashflows(), isTradable(), QuantLib::Bond::maturityDate(), QL_REQUIRE, and QuantLib::Bond::settlementDate().
{
        if (settlement == Date())
            settlement = bond.settlementDate();
        QL_REQUIRE(BondFunctions::isTradable(bond, settlement),
                   "non tradable at " << settlement <<
                   " (maturity being " << bond.maturityDate() << ")");
        return CashFlows::accrualStartDate(bond.cashflows(),
                                           false, settlement);
    }
Real QuantLib::BondFunctions::accruedAmount (const Bond & bond, Date settlementDate = Date()) [static]
Definition at line 227 of file bondfunctions.cpp.
References QuantLib::Bond::cashflows(), isTradable(), QuantLib::Bond::maturityDate(), QuantLib::Bond::notional(), QL_REQUIRE, and QuantLib::Bond::settlementDate().
{
        if (settlement == Date())
            settlement = bond.settlementDate();
        QL_REQUIRE(BondFunctions::isTradable(bond, settlement),
                   "non tradable at " << settlement <<
                   " (maturity being " << bond.maturityDate() << ")");
        return CashFlows::accruedAmount(bond.cashflows(),
                                        false, settlement) *
            100.0 / bond.notional(settlement);
    }
BigInteger QuantLib::BondFunctions::accruedDays (const Bond & bond, Date settlementDate = Date()) [static]
Definition at line 214 of file bondfunctions.cpp.
References QuantLib::Bond::cashflows(), isTradable(), QuantLib::Bond::maturityDate(), QL_REQUIRE, and QuantLib::Bond::settlementDate().
{
        if (settlement == Date())
            settlement = bond.settlementDate();
        QL_REQUIRE(BondFunctions::isTradable(bond, settlement),
                   "non tradable at " << settlement <<
                   " (maturity being " << bond.maturityDate() << ")");
        return CashFlows::accruedDays(bond.cashflows(),
                                      false, settlement);
    }
Time QuantLib::BondFunctions::accruedPeriod (const Bond & bond, Date settlementDate = Date()) [static]
Definition at line 201 of file bondfunctions.cpp.
References QuantLib::Bond::cashflows(), isTradable(), QuantLib::Bond::maturityDate(), QL_REQUIRE, and QuantLib::Bond::settlementDate().
{
        if (settlement == Date())
            settlement = bond.settlementDate();
        QL_REQUIRE(BondFunctions::isTradable(bond, settlement),
                   "non tradable at " << settlement <<
                   " (maturity being " << bond.maturityDate() << ")");
        return CashFlows::accruedPeriod(bond.cashflows(),
                                        false, settlement);
    }
Rate QuantLib::BondFunctions::atmRate (const Bond & bond, const YieldTermStructure & discountCurve, Date settlementDate = Date(), Real cleanPrice = Null<Real>()) [static]
Definition at line 275 of file bondfunctions.cpp.
References QuantLib::Bond::accruedAmount(), QuantLib::Bond::cashflows(), isTradable(), QuantLib::Bond::maturityDate(), QL_REQUIRE, and QuantLib::Bond::settlementDate().
{
        if (settlement == Date())
            settlement = bond.settlementDate();
        QL_REQUIRE(BondFunctions::isTradable(bond, settlement),
                   "non tradable at " << settlement <<
                   " (maturity being " << bond.maturityDate() << ")");
        Real dirtyPrice = cleanPrice==Null<Real>() ? Null<Real>() :
                          cleanPrice + bond.accruedAmount(settlement);
        return CashFlows::atmRate(bond.cashflows(), discountCurve,
                                  false, settlement, settlement,
                                  dirtyPrice);
    }
Real QuantLib::BondFunctions::basisPointValue (const Bond & bond, const InterestRate & yield, Date settlementDate = Date()) [static]
Definition at line 421 of file bondfunctions.cpp.
References QuantLib::Bond::cashflows(), isTradable(), QuantLib::Bond::maturityDate(), QL_REQUIRE, QuantLib::Bond::settlementDate(), and yield().
Referenced by basisPointValue().
{
        if (settlement == Date())
            settlement = bond.settlementDate();
        QL_REQUIRE(BondFunctions::isTradable(bond, settlement),
                   "non tradable at " << settlement <<
                   " (maturity being " << bond.maturityDate() << ")");
        return CashFlows::basisPointValue(bond.cashflows(), yield,
                                          false, settlement);
    }
Real QuantLib::BondFunctions::basisPointValue (const Bond & bond, Rate yield, const DayCounter & dayCounter, Compounding compounding, Frequency frequency, Date settlementDate = Date()) [static]
Definition at line 435 of file bondfunctions.cpp.
References basisPointValue(), and QuantLib::Bond::cashflows().
{
        InterestRate y(yield, dayCounter, compounding, frequency);
        return CashFlows::basisPointValue(bond.cashflows(), y,
                                          false, settlement);
    }
Real QuantLib::BondFunctions::bps (const Bond & bond, const YieldTermStructure & discountCurve, Date settlementDate = Date()) [static]
Definition at line 260 of file bondfunctions.cpp.
References QuantLib::Bond::cashflows(), isTradable(), QuantLib::Bond::maturityDate(), QuantLib::Bond::notional(), QL_REQUIRE, and QuantLib::Bond::settlementDate().
Referenced by bps().
{
        if (settlement == Date())
            settlement = bond.settlementDate();
        QL_REQUIRE(BondFunctions::isTradable(bond, settlement),
                   "non tradable at " << settlement <<
                   " (maturity being " << bond.maturityDate() << ")");
        return CashFlows::bps(bond.cashflows(), discountCurve,
                              false, settlement) *
            100.0 / bond.notional(settlement);
    }
Real QuantLib::BondFunctions::bps (const Bond & bond, const InterestRate & yield, Date settlementDate = Date()) [static]
Definition at line 320 of file bondfunctions.cpp.
References bps(), QuantLib::Bond::cashflows(), isTradable(), QuantLib::Bond::maturityDate(), QuantLib::Bond::notional(), QL_REQUIRE, QuantLib::Bond::settlementDate(), and yield().
{
        if (settlement == Date())
            settlement = bond.settlementDate();
        QL_REQUIRE(BondFunctions::isTradable(bond, settlement),
                   "non tradable at " << settlement <<
                   " (maturity being " << bond.maturityDate() << ")");
        return CashFlows::bps(bond.cashflows(), yield,
                              false, settlement) *
            100.0 / bond.notional(settlement);
    }
Real QuantLib::BondFunctions::bps (const Bond & bond, Rate yield, const DayCounter & dayCounter, Compounding compounding, Frequency frequency, Date settlementDate = Date()) [static]
Definition at line 335 of file bondfunctions.cpp.
References bps().
{
        InterestRate y(yield, dayCounter, compounding, frequency);
        return bps(bond, y, settlement);
    }
Real QuantLib::BondFunctions::cleanPrice (const Bond & bond, const YieldTermStructure & discountCurve, Date settlementDate = Date()) [static]
Definition at line 243 of file bondfunctions.cpp.
References QuantLib::Bond::accruedAmount(), QuantLib::Bond::cashflows(), isTradable(), QuantLib::Bond::maturityDate(), QuantLib::Bond::notional(), QuantLib::CashFlows::npv(), QL_REQUIRE, and QuantLib::Bond::settlementDate().
Referenced by cleanPrice(), BondTest::testBrazilianCached(), BondTest::testCached(), BondTest::testTheoretical(), BondTest::testYield(), BondTest::testZspread(), AssetSwapTest::testZSpread(), and AssetSwapTest::testZSpreadWithGenericBond().
{
        if (settlement == Date())
            settlement = bond.settlementDate();
        QL_REQUIRE(BondFunctions::isTradable(bond, settlement),
                   "non tradable at " << settlement <<
                   " settlement date (maturity being " <<
                   bond.maturityDate() << ")");
        Real dirtyPrice = CashFlows::npv(bond.cashflows(), discountCurve,
                                         false, settlement) *
            100.0 / bond.notional(settlement);
        return dirtyPrice - bond.accruedAmount(settlement);
    }
Real QuantLib::BondFunctions::cleanPrice (const Bond & bond, const InterestRate & yield, Date settlementDate = Date()) [static]
Definition at line 294 of file bondfunctions.cpp.
References QuantLib::Bond::accruedAmount(), QuantLib::Bond::cashflows(), isTradable(), QuantLib::Bond::maturityDate(), QuantLib::Bond::notional(), QuantLib::CashFlows::npv(), QL_REQUIRE, QuantLib::Bond::settlementDate(), and yield().
{
        if (settlement == Date())
            settlement = bond.settlementDate();
        QL_REQUIRE(BondFunctions::isTradable(bond, settlement),
                   "non tradable at " << settlement <<
                   " (maturity being " << bond.maturityDate() << ")");
        Real dirtyPrice = CashFlows::npv(bond.cashflows(), yield,
                                         false, settlement) *
            100.0 / bond.notional(settlement);
        return dirtyPrice - bond.accruedAmount(settlement);
    }
Real QuantLib::BondFunctions::cleanPrice (const Bond & bond, Rate yield, const DayCounter & dayCounter, Compounding compounding, Frequency frequency, Date settlementDate = Date()) [static]
Definition at line 310 of file bondfunctions.cpp.
References cleanPrice().
{
        InterestRate y(yield, dayCounter, compounding, frequency);
        return cleanPrice(bond, y, settlement);
    }
static Real QuantLib::BondFunctions::cleanPrice (const Bond & bond, const boost::shared_ptr< YieldTermStructure > & discount, Spread zSpread, const DayCounter & dayCounter, Compounding compounding, Frequency frequency, Date settlementDate = Date()) [static]
Real QuantLib::BondFunctions::convexity (const Bond & bond, const InterestRate & yield, Date settlementDate = Date()) [static]
Definition at line 397 of file bondfunctions.cpp.
References QuantLib::Bond::cashflows(), isTradable(), QuantLib::Bond::maturityDate(), QL_REQUIRE, QuantLib::Bond::settlementDate(), and yield().
Referenced by convexity().
{
        if (settlement == Date())
            settlement = bond.settlementDate();
        QL_REQUIRE(BondFunctions::isTradable(bond, settlement),
                   "non tradable at " << settlement <<
                   " (maturity being " << bond.maturityDate() << ")");
        return CashFlows::convexity(bond.cashflows(), yield,
                                    false, settlement);
    }
Real QuantLib::BondFunctions::convexity (const Bond & bond, Rate yield, const DayCounter & dayCounter, Compounding compounding, Frequency frequency, Date settlementDate = Date()) [static]
Definition at line 411 of file bondfunctions.cpp.
References convexity().
{
        InterestRate y(yield, dayCounter, compounding, frequency);
        return convexity(bond, y, settlement);
    }
Time QuantLib::BondFunctions::duration (const Bond & bond, const InterestRate & yield, Duration::Type type = Duration::Modified, Date settlementDate = Date()) [static]
Definition at line 370 of file bondfunctions.cpp.
References QuantLib::Bond::cashflows(), isTradable(), QuantLib::Bond::maturityDate(), QL_REQUIRE, QuantLib::Bond::settlementDate(), anonymous_namespace{swaption.cpp}::type, and yield().
Referenced by duration(), and QuantLib::FittedBondDiscountCurve::FittingMethod::init().
{
        if (settlement == Date())
            settlement = bond.settlementDate();
        QL_REQUIRE(BondFunctions::isTradable(bond, settlement),
                   "non tradable at " << settlement <<
                   " (maturity being " << bond.maturityDate() << ")");
        return CashFlows::duration(bond.cashflows(), yield,
                                   type,
                                   false, settlement);
    }
Time QuantLib::BondFunctions::duration (const Bond & bond, Rate yield, const DayCounter & dayCounter, Compounding compounding, Frequency frequency, Duration::Type type = Duration::Modified, Date settlementDate = Date()) [static]
Definition at line 386 of file bondfunctions.cpp.
References duration().
{
        InterestRate y(yield, dayCounter, compounding, frequency);
        return duration(bond, y, type, settlement);
    }
bool QuantLib::BondFunctions::isTradable (const Bond & bond, Date settlementDate = Date()) [static]
Definition at line 42 of file bondfunctions.cpp.
References QuantLib::Bond::notional(), and QuantLib::Bond::settlementDate().
Referenced by accrualDays(), accrualEndDate(), accrualPeriod(), accrualStartDate(), accruedAmount(), accruedDays(), accruedPeriod(), atmRate(), basisPointValue(), bps(), cleanPrice(), convexity(), duration(), QuantLib::FittedBondDiscountCurve::performCalculations(), referencePeriodEnd(), referencePeriodStart(), yield(), yieldValueBasisPoint(), and zSpread().
{
        if (settlement == Date())
            settlement = bond.settlementDate();
        return bond.notional(settlement)!=0.0;
    }
Date QuantLib::BondFunctions::maturityDate (const Bond & bond) [static]
Definition at line 38 of file bondfunctions.cpp.
References QuantLib::Bond::cashflows().
{
        return CashFlows::maturityDate(bond.cashflows());
    }
Leg::const_iterator QuantLib::BondFunctions::nextCashFlow (const Bond & bond, Date refDate = Date()) [static]
Definition at line 60 of file bondfunctions.cpp.
References QuantLib::Bond::cashflows(), and QuantLib::Bond::settlementDate().
{
        if (settlement == Date())
            settlement = bond.settlementDate();
        return CashFlows::nextCashFlow(bond.cashflows(),
                                       false, settlement);
    }
Real QuantLib::BondFunctions::nextCashFlowAmount (const Bond & bond, Date refDate = Date()) [static]
Definition at line 96 of file bondfunctions.cpp.
References QuantLib::Bond::cashflows(), and QuantLib::Bond::settlementDate().
{
        if (settlement == Date())
            settlement = bond.settlementDate();
        return CashFlows::nextCashFlowAmount(bond.cashflows(),
                                             false, settlement);
    }
Date QuantLib::BondFunctions::nextCashFlowDate (const Bond & bond, Date refDate = Date()) [static]
Definition at line 78 of file bondfunctions.cpp.
References QuantLib::Bond::cashflows(), and QuantLib::Bond::settlementDate().
{
        if (settlement == Date())
            settlement = bond.settlementDate();
        return CashFlows::nextCashFlowDate(bond.cashflows(),
                                           false, settlement);
    }
Rate QuantLib::BondFunctions::nextCouponRate (const Bond & bond, Date settlementDate = Date()) [static]
Definition at line 114 of file bondfunctions.cpp.
References QuantLib::Bond::cashflows(), and QuantLib::Bond::settlementDate().
{
        if (settlement == Date())
            settlement = bond.settlementDate();
        return CashFlows::nextCouponRate(bond.cashflows(),
                                         false, settlement);
    }
Leg::const_reverse_iterator QuantLib::BondFunctions::previousCashFlow (const Bond & bond, Date refDate = Date()) [static]
Definition at line 51 of file bondfunctions.cpp.
References QuantLib::Bond::cashflows(), and QuantLib::Bond::settlementDate().
{
        if (settlement == Date())
            settlement = bond.settlementDate();
        return CashFlows::previousCashFlow(bond.cashflows(),
                                           false, settlement);
    }
Real QuantLib::BondFunctions::previousCashFlowAmount (const Bond & bond, Date refDate = Date()) [static]
Definition at line 87 of file bondfunctions.cpp.
References QuantLib::Bond::cashflows(), and QuantLib::Bond::settlementDate().
{
        if (settlement == Date())
            settlement = bond.settlementDate();
        return CashFlows::previousCashFlowAmount(bond.cashflows(),
                                                 false, settlement);
    }
Date QuantLib::BondFunctions::previousCashFlowDate (const Bond & bond, Date refDate = Date()) [static]
Definition at line 69 of file bondfunctions.cpp.
References QuantLib::Bond::cashflows(), and QuantLib::Bond::settlementDate().
{
        if (settlement == Date())
            settlement = bond.settlementDate();
        return CashFlows::previousCashFlowDate(bond.cashflows(),
                                               false, settlement);
    }
Rate QuantLib::BondFunctions::previousCouponRate (const Bond & bond, Date settlementDate = Date()) [static]
Definition at line 105 of file bondfunctions.cpp.
References QuantLib::Bond::cashflows(), and QuantLib::Bond::settlementDate().
{
        if (settlement == Date())
            settlement = bond.settlementDate();
        return CashFlows::previousCouponRate(bond.cashflows(),
                                             false, settlement);
    }
Date QuantLib::BondFunctions::referencePeriodEnd (const Bond & bond, Date settlementDate = Date()) [static]
Definition at line 162 of file bondfunctions.cpp.
References QuantLib::Bond::cashflows(), isTradable(), QuantLib::Bond::maturityDate(), QL_REQUIRE, and QuantLib::Bond::settlementDate().
{
        if (settlement == Date())
            settlement = bond.settlementDate();
        QL_REQUIRE(BondFunctions::isTradable(bond, settlement),
                   "non tradable at " << settlement <<
                   " (maturity being " << bond.maturityDate() << ")");
        return CashFlows::referencePeriodEnd(bond.cashflows(),
                                             false, settlement);
    }
Date QuantLib::BondFunctions::referencePeriodStart (const Bond & bond, Date settlementDate = Date()) [static]
Definition at line 149 of file bondfunctions.cpp.
References QuantLib::Bond::cashflows(), isTradable(), QuantLib::Bond::maturityDate(), QL_REQUIRE, and QuantLib::Bond::settlementDate().
{
        if (settlement == Date())
            settlement = bond.settlementDate();
        QL_REQUIRE(BondFunctions::isTradable(bond, settlement),
                   "non tradable at " << settlement <<
                   " (maturity being " << bond.maturityDate() << ")");
        return CashFlows::referencePeriodStart(bond.cashflows(),
                                               false, settlement);
    }
Date QuantLib::BondFunctions::startDate (const Bond & bond) [static]
Definition at line 34 of file bondfunctions.cpp.
References QuantLib::Bond::cashflows().
{
        return CashFlows::startDate(bond.cashflows());
    }
Rate QuantLib::BondFunctions::yield (const Bond & bond, Real cleanPrice, const DayCounter & dayCounter, Compounding compounding, Frequency frequency, Date settlementDate = Date(), Real accuracy = 1.0e-10, Size maxIterations = 100, Rate guess = 0.05) [static]
Definition at line 345 of file bondfunctions.cpp.
References QuantLib::Bond::accruedAmount(), QuantLib::Bond::cashflows(), anonymous_namespace{marketmodel.cpp}::dayCounter, isTradable(), QuantLib::Bond::maturityDate(), QuantLib::Bond::notional(), QL_REQUIRE, and QuantLib::Bond::settlementDate().
Referenced by basisPointValue(), bps(), cleanPrice(), convexity(), duration(), QuantLib::FittedBondDiscountCurve::FittingMethod::init(), BondTest::testCached(), BondTest::testTheoretical(), BondTest::testYield(), and yieldValueBasisPoint().
{
        if (settlement == Date())
            settlement = bond.settlementDate();
        QL_REQUIRE(BondFunctions::isTradable(bond, settlement),
                   "non tradable at " << settlement <<
                   " (maturity being " << bond.maturityDate() << ")");
        Real dirtyPrice = cleanPrice + bond.accruedAmount(settlement);
        dirtyPrice /= 100.0 / bond.notional(settlement);
        return CashFlows::yield(bond.cashflows(), dirtyPrice,
                                dayCounter, compounding, frequency,
                                false, settlement, settlement,
                                accuracy, maxIterations, guess);
    }
Real QuantLib::BondFunctions::yieldValueBasisPoint (const Bond & bond, const InterestRate & yield, Date settlementDate = Date()) [static]
Definition at line 446 of file bondfunctions.cpp.
References QuantLib::Bond::cashflows(), isTradable(), QuantLib::Bond::maturityDate(), QL_REQUIRE, QuantLib::Bond::settlementDate(), and yield().
Referenced by yieldValueBasisPoint().
{
        if (settlement == Date())
            settlement = bond.settlementDate();
        QL_REQUIRE(BondFunctions::isTradable(bond, settlement),
                   "non tradable at " << settlement <<
                   " (maturity being " << bond.maturityDate() << ")");
        return CashFlows::yieldValueBasisPoint(bond.cashflows(), yield,
                                               false, settlement);
    }
Real QuantLib::BondFunctions::yieldValueBasisPoint (const Bond & bond, Rate yield, const DayCounter & dayCounter, Compounding compounding, Frequency frequency, Date settlementDate = Date()) [static]
Definition at line 460 of file bondfunctions.cpp.
References QuantLib::Bond::cashflows(), and yieldValueBasisPoint().
{
        InterestRate y(yield, dayCounter, compounding, frequency);
        return CashFlows::yieldValueBasisPoint(bond.cashflows(), y,
                                               false, settlement);
    }
Spread QuantLib::BondFunctions::zSpread (const Bond & bond, Real cleanPrice, const boost::shared_ptr< YieldTermStructure > & , const DayCounter & dayCounter, Compounding compounding, Frequency frequency, Date settlementDate = Date(), Real accuracy = 1.0e-10, Size maxIterations = 100, Rate guess = 0.0) [static]
Definition at line 492 of file bondfunctions.cpp.
References QuantLib::Bond::accruedAmount(), QuantLib::Bond::cashflows(), anonymous_namespace{marketmodel.cpp}::d, anonymous_namespace{marketmodel.cpp}::dayCounter, isTradable(), QuantLib::Bond::maturityDate(), QuantLib::Bond::notional(), QL_REQUIRE, and QuantLib::Bond::settlementDate().
Referenced by BondTest::testZspread().
{
        if (settlement == Date())
            settlement = bond.settlementDate();
        QL_REQUIRE(BondFunctions::isTradable(bond, settlement),
                   "non tradable at " << settlement <<
                   " (maturity being " << bond.maturityDate() << ")");
        Real dirtyPrice = cleanPrice + bond.accruedAmount(settlement);
        dirtyPrice /= 100.0 / bond.notional(settlement);
        return CashFlows::zSpread(bond.cashflows(),
                                  d,
                                  dirtyPrice,
                                  dayCounter, compounding, frequency,
                                  false, settlement, settlement,
                                  accuracy, maxIterations, guess);
    }
The documentation for this struct was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/bond/bondfunctions.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/pricingengines/bond/bondfunctions.cpp