QuantLib: anonymous_namespace{assetswap.cpp}::CommonVars Struct Reference
anonymous_namespace{assetswap.cpp}::CommonVars Struct Reference
Public Member Functions
CommonVars ()
Public Attributes
boost::shared_ptr< IborIndex > iborIndex
boost::shared_ptr< SwapIndex > swapIndex
boost::shared_ptr
< IborCouponPricer > pricer
boost::shared_ptr
< CmsCouponPricer > cmspricer
Spread spread
Spread nonnullspread
Real faceAmount
Compounding compounding
RelinkableHandle
< YieldTermStructure > termStructure
SavedSettings backup
IndexHistoryCleaner indexCleaner
Detailed Description
Definition at line 64 of file assetswap.cpp.
Constructor & Destructor Documentation
anonymous_namespace{assetswap.cpp}::CommonVars::CommonVars () [inline]
Definition at line 81 of file assetswap.cpp.
References QuantLib::Annual, QuantLib::April, anonymous_namespace{marketmodel.cpp}::calendar, QuantLib::Continuous, QuantLib::Settings::evaluationDate(), QuantLib::flatRate(), QuantLib::Following, QuantLib::Singleton< Settings >::instance(), QuantLib::Semiannual, QuantLib::GFunctionFactory::Standard, QuantLib::Unadjusted, and QuantLib::Years.
                     {
            Natural swapSettlementDays = 2;
            faceAmount = 100.0;
            BusinessDayConvention fixedConvention = Unadjusted;
            compounding = Continuous;
            Frequency fixedFrequency = Annual;
            Frequency floatingFrequency = Semiannual;
            iborIndex = boost::shared_ptr<IborIndex>(
                     new Euribor(Period(floatingFrequency), termStructure));
            Calendar calendar = iborIndex->fixingCalendar();
            swapIndex= boost::shared_ptr<SwapIndex>(
                new SwapIndex("EuriborSwapIsdaFixA", 10*Years, swapSettlementDays,
                              iborIndex->currency(), calendar,
                              Period(fixedFrequency), fixedConvention,
                              iborIndex->dayCounter(), iborIndex));
            spread = 0.0;
            nonnullspread = 0.003;
            Date today(24,April,2007);
            Settings::instance().evaluationDate() = today;
            //Date today = Settings::instance().evaluationDate();
            termStructure.linkTo(flatRate(today, 0.05, Actual365Fixed()));
            pricer = boost::shared_ptr<IborCouponPricer>(new
                                                        BlackIborCouponPricer);
            Handle<SwaptionVolatilityStructure> swaptionVolatilityStructure(
                boost::shared_ptr<SwaptionVolatilityStructure>(new
                    ConstantSwaptionVolatility(today, NullCalendar(),Following,
                                               0.2, Actual365Fixed())));
            Handle<Quote> meanReversionQuote(boost::shared_ptr<Quote>(new
                SimpleQuote(0.01)));
            cmspricer = boost::shared_ptr<CmsCouponPricer>(new
                AnalyticHaganPricer(swaptionVolatilityStructure,
                                    GFunctionFactory::Standard,
                                    meanReversionQuote));
        }
Member Data Documentation
SavedSettings anonymous_namespace{assetswap.cpp}::CommonVars::backup
Definition at line 77 of file assetswap.cpp.
boost::shared_ptr<CmsCouponPricer> anonymous_namespace{assetswap.cpp}::CommonVars::cmspricer
Definition at line 69 of file assetswap.cpp.
Compounding anonymous_namespace{assetswap.cpp}::CommonVars::compounding
Definition at line 73 of file assetswap.cpp.
Real anonymous_namespace{assetswap.cpp}::CommonVars::faceAmount
Definition at line 72 of file assetswap.cpp.
boost::shared_ptr<IborIndex> anonymous_namespace{assetswap.cpp}::CommonVars::iborIndex
Definition at line 66 of file assetswap.cpp.
IndexHistoryCleaner anonymous_namespace{assetswap.cpp}::CommonVars::indexCleaner
Definition at line 78 of file assetswap.cpp.
Spread anonymous_namespace{assetswap.cpp}::CommonVars::nonnullspread
Definition at line 71 of file assetswap.cpp.
boost::shared_ptr<IborCouponPricer> anonymous_namespace{assetswap.cpp}::CommonVars::pricer
Definition at line 68 of file assetswap.cpp.
Spread anonymous_namespace{assetswap.cpp}::CommonVars::spread
Definition at line 70 of file assetswap.cpp.
boost::shared_ptr<SwapIndex> anonymous_namespace{assetswap.cpp}::CommonVars::swapIndex
Definition at line 67 of file assetswap.cpp.
RelinkableHandle<YieldTermStructure> anonymous_namespace{assetswap.cpp}::CommonVars::termStructure
Definition at line 74 of file assetswap.cpp.
The documentation for this struct was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/assetswap.cpp