QuantLib: QuantLib::ECB Struct Reference
QuantLib::ECB Struct Reference
European Central Bank reserve maintenance dates.
#include <ecb.hpp>
Static Public Member Functions
static const std::set< Date > & knownDates ()
static void addDate (const Date &d)
static void removeDate (const Date &d)
static Date date (Month m, Year y)
maintenance period start date in the given month/year
static Date date (const std::string &ecbCode, const Date &referenceDate=Date())
static std::string code (const Date &ecbDate)
static Date nextDate (const Date &d=Date())
next maintenance period start date following the given date
static Date nextDate (const std::string &ecbCode, const Date &referenceDate=Date())
next maintenance period start date following the given ECB code
static std::vector< Date > nextDates (const Date &d=Date())
next maintenance period start dates following the given date
static std::vector< Date > nextDates (const std::string &ecbCode, const Date &referenceDate=Date())
next maintenance period start dates following the given code
static bool isECBdate (const Date &d)
static bool isECBcode (const std::string &in)
returns whether or not the given string is an ECB code
static std::string nextCode (const Date &d=Date())
next ECB code following the given date
static std::string nextCode (const std::string &ecbCode)
next ECB code following the given code
Detailed Description
European Central Bank reserve maintenance dates.
Definition at line 34 of file ecb.hpp.
Member Function Documentation
void QuantLib::ECB::addDate (const Date & d) [static]
Definition at line 57 of file ecb.cpp.
References knownDates(), and QuantLib::knownDateSet.
Referenced by DateTest::ecbDates().
{
        knownDates(); // just to ensure inizialization
        knownDateSet.insert(d);
    }
string QuantLib::ECB::code (const Date & ecbDate) [static]
returns the ECB code for the given date (e.g. MAR10 for March xxth, 2010).
Warning:
It raises an exception if the input date is not an ECB date
Definition at line 105 of file ecb.cpp.
References QuantLib::April, QuantLib::August, QuantLib::December, QuantLib::February, isECBcode(), isECBdate(), QuantLib::January, QuantLib::July, QuantLib::June, QuantLib::March, QuantLib::May, QuantLib::Date::month(), QuantLib::November, QuantLib::October, QL_ENSURE, QL_FAIL, QL_REQUIRE, QuantLib::September, and QuantLib::Date::year().
Referenced by date(), isECBcode(), and nextCode().
{
        QL_REQUIRE(isECBdate(ecbDate),
                   ecbDate << " is not a valid ECB date");
        std::ostringstream ECBcode;
        unsigned int y = ecbDate.year() % 100;
        string padding;
        if (y < 10)
            padding = "0";
        switch(ecbDate.month()) {
          case January:
            ECBcode << "JAN" << padding << y;
            break;
          case February:
            ECBcode << "FEB" << padding << y;
            break;
          case March:
            ECBcode << "MAR" << padding << y;
            break;
          case April:
            ECBcode << "APR" << padding << y;
            break;
          case May:
            ECBcode << "MAY" << padding << y;
            break;
          case June:
            ECBcode << "JUN" << padding << y;
            break;
          case July:
            ECBcode << "JUL" << padding << y;
            break;
          case August:
            ECBcode << "AUG" << padding << y;
            break;
          case September:
            ECBcode << "SEP" << padding << y;
            break;
          case October:
            ECBcode << "OCT" << padding << y;
            break;
          case November:
            ECBcode << "NOV" << padding << y;
            break;
          case December:
            ECBcode << "DEC" << padding << y;
            break;
          default:
            QL_FAIL("not an ECB month (and it should have been)");
        }
        #if defined(QL_EXTRA_SAFETY_CHECKS)
        QL_ENSURE(isECBcode(ECBcode.str()),
                  "the result " << ECBcode.str() <<
                  " is an invalid ECB code");
        #endif
        return ECBcode.str();
    }
static Date QuantLib::ECB::date (Month m, Year y) [inline, static]
maintenance period start date in the given month/year
Definition at line 41 of file ecb.hpp.
References nextDate().
Referenced by isECBdate(), nextDate(), and nextDates().
                                 { return nextDate(Date(1, m, y) - 1); }
Date QuantLib::ECB::date (const std::string & ecbCode, const Date & referenceDate = Date()) [static]
returns the ECB date for the given ECB code (e.g. March xxth, 2013 for MAR10).
Warning:
It raises an exception if the input string is not an ECB code
Definition at line 67 of file ecb.cpp.
References QuantLib::April, QuantLib::August, code(), QuantLib::December, QuantLib::February, QuantLib::Singleton< Settings >::instance(), isECBcode(), QuantLib::January, QuantLib::July, QuantLib::June, QuantLib::March, QuantLib::May, QuantLib::Date::minDate(), nextDate(), QuantLib::November, QuantLib::October, QL_FAIL, QL_REQUIRE, QuantLib::September, QuantLib::io::to_integer(), and QuantLib::Date::year().
{
        QL_REQUIRE(isECBcode(ecbCode),
                   ecbCode << " is not a valid ECB code");
        string code = to_upper_copy(ecbCode);
        string monthString = code.substr(0, 3);
        Month m;
        if (monthString=="JAN")      m = January;
        else if (monthString=="FEB") m = February;
        else if (monthString=="MAR") m = March;
        else if (monthString=="APR") m = April;
        else if (monthString=="MAY") m = May;
        else if (monthString=="JUN") m = June;
        else if (monthString=="JUL") m = July;
        else if (monthString=="AUG") m = August;
        else if (monthString=="SEP") m = September;
        else if (monthString=="OCT") m = October;
        else if (monthString=="NOV") m = November;
        else if (monthString=="DEC") m = December;
        else QL_FAIL("not an ECB month (and it should have been)");
        // lexical_cast causes compilation errors with x64
        //Year y = boost::lexical_cast<Year>(code.substr(3, 2));
        Year y = io::to_integer(code.substr(3, 2));
        Date referenceDate = (refDate != Date() ?
                              refDate :
                              Date(Settings::instance().evaluationDate()));
        Year referenceYear = (referenceDate.year() % 100);
        y += referenceDate.year() - referenceYear;
        if (y<Date::minDate().year())
            return ECB::nextDate(Date::minDate());
        return ECB::nextDate(Date(1, m, y));
    }
bool QuantLib::ECB::isECBcode (const std::string & in) [static]
returns whether or not the given string is an ECB code
Definition at line 193 of file ecb.cpp.
References code().
Referenced by code(), date(), and nextCode().
{
        if (ecbCode.length() != 5)
            return false;
        string code = to_upper_copy(ecbCode);
        string str1("0123456789");
        string::size_type loc = str1.find(code.substr(3, 1), 0);
        if (loc == string::npos)
            return false;
        loc = str1.find(code.substr(4, 1), 0);
        if (loc == string::npos)
            return false;
        string monthString = code.substr(0, 3);
        if (monthString=="JAN")      return true;
        else if (monthString=="FEB") return true;
        else if (monthString=="MAR") return true;
        else if (monthString=="APR") return true;
        else if (monthString=="MAY") return true;
        else if (monthString=="JUN") return true;
        else if (monthString=="JUL") return true;
        else if (monthString=="AUG") return true;
        else if (monthString=="SEP") return true;
        else if (monthString=="OCT") return true;
        else if (monthString=="NOV") return true;
        else if (monthString=="DEC") return true;
        else return false;
    }
static bool QuantLib::ECB::isECBdate (const Date & d) [inline, static]
returns whether or not the given date is a maintenance period start date
Definition at line 81 of file ecb.hpp.
References date(), and nextDate().
Referenced by code(), and DateTest::ecbDates().
{
            Date date = nextDate(d-1);
            return d==date;
        }
const std::set< Date > & QuantLib::ECB::knownDates () [static]
Definition at line 33 of file ecb.cpp.
References QuantLib::knownDateSet.
Referenced by addDate(), DateTest::ecbDates(), nextDate(), nextDates(), and removeDate().
{
        // one-off inizialization
        static const BigInteger knownDatesArray[] = {
              38371, 38391, 38420, 38455, 38483, 38511, 38546, 38574, 38602, 38637, 38665, 38692 // 2005
            , 38735, 38756, 38784, 38819, 38847, 38883, 38910, 38938, 38966, 39001, 39029, 39064 // 2006
            , 39099, 39127, 39155, 39190, 39217, 39246, 39274, 39302, 39337, 39365, 39400, 39428 // 2007
            , 39463, 39491, 39519, 39554, 39582, 39610, 39638, 39673, 39701, 39729, 39764, 39792 // 2008
            , 39834, 39855, 39883, 39911, 39946, 39974, 40002, 40037, 40065, 40100, 40128, 40155 // 2009
            , 40198, 40219, 40247, 40282, 40310, 40345, 40373, 40401, 40429, 40464, 40492, 40520 // 2010
            , 40562, 40583, 40611, 40646, 40674, 40709, 40737, 40765, 40800, 40828, 40856, 40891 // 2011
            // http://www.ecb.europa.eu/press/pr/date/2011/html/pr110520.en.html
            , 40926, 40954, 40982, 41010, 41038, 41073, 41101, 41129, 41164, 41192, 41227, 41255 // 2012
            , 41290, 41318, 41346, 41374, 41402, 41437, 41465, 41493, 41528, 41556, 41591, 41619 // 2013
        };
        if (knownDateSet.empty()) {
            Size n = sizeof(knownDatesArray)/sizeof(BigInteger);
            for (Size i=0; i<n; ++i)
                knownDateSet.insert(Date(knownDatesArray[i]));
        }
        return knownDateSet;
    }
static std::string QuantLib::ECB::nextCode (const Date & d = Date()) [inline, static]
next ECB code following the given date
Definition at line 90 of file ecb.hpp.
References code(), and nextDate().
{
            return code(nextDate(d));
        }
string QuantLib::ECB::nextCode (const std::string & ecbCode) [static]
next ECB code following the given code
Definition at line 224 of file ecb.cpp.
References code(), isECBcode(), QL_ENSURE, QL_FAIL, QL_REQUIRE, and QuantLib::io::to_integer().
{
        QL_REQUIRE(isECBcode(ecbCode),
                   ecbCode << " is not a valid ECB code");
        string code = to_upper_copy(ecbCode);
        std::ostringstream result;
        string monthString = code.substr(0, 3);
        if (monthString=="JAN")      result << "FEB" << code.substr(3, 2);
        else if (monthString=="FEB") result << "MAR" << code.substr(3, 2);
        else if (monthString=="MAR") result << "APR" << code.substr(3, 2);
        else if (monthString=="APR") result << "MAY" << code.substr(3, 2);
        else if (monthString=="MAY") result << "JUN" << code.substr(3, 2);
        else if (monthString=="JUN") result << "JUL" << code.substr(3, 2);
        else if (monthString=="JUL") result << "AUG" << code.substr(3, 2);
        else if (monthString=="AUG") result << "SEP" << code.substr(3, 2);
        else if (monthString=="SEP") result << "OCT" << code.substr(3, 2);
        else if (monthString=="OCT") result << "NOV" << code.substr(3, 2);
        else if (monthString=="NOV") result << "DEC" << code.substr(3, 2);
        else if (monthString=="DEC") {
            // lexical_cast causes compilation errors with x64
            //Year y = boost::lexical_cast<Year>(code.substr(3, 2));
            unsigned int y = (io::to_integer(code.substr(3, 2)) + 1) % 100;
            string padding;
            if (y < 10)
                padding = "0";
            result << "JAN" << padding << y;
        } else QL_FAIL("not an ECB month (and it should have been)");
        #if defined(QL_EXTRA_SAFETY_CHECKS)
        QL_ENSURE(isECBcode(result.str()),
                  "the result " << result.str() <<
                  " is an invalid ECB code");
        #endif
        return result.str();
    }
Date QuantLib::ECB::nextDate (const Date & d = Date()) [static]
next maintenance period start date following the given date
Definition at line 166 of file ecb.cpp.
References anonymous_namespace{marketmodel.cpp}::d, date(), QuantLib::Settings::evaluationDate(), QuantLib::Singleton< Settings >::instance(), knownDates(), and QL_REQUIRE.
Referenced by date(), DateTest::ecbDates(), isECBdate(), nextCode(), and nextDate().
{
        Date d = (date == Date() ?
                  Settings::instance().evaluationDate() :
                  date);
        std::set<Date>::const_iterator i =
            std::upper_bound(knownDates().begin(), knownDates().end(), d);
        QL_REQUIRE(i!=knownDates().end(),
                   "ECB dates after " << *(--knownDates().end()) << " are unknown");
        return Date(*i);
    }
static Date QuantLib::ECB::nextDate (const std::string & ecbCode, const Date & referenceDate = Date()) [inline, static]
next maintenance period start date following the given ECB code
Definition at line 65 of file ecb.hpp.
References date(), and nextDate().
{
            return nextDate(date(ecbCode, referenceDate));
        }
std::vector< Date > QuantLib::ECB::nextDates (const Date & d = Date()) [static]
next maintenance period start dates following the given date
Definition at line 179 of file ecb.cpp.
References anonymous_namespace{marketmodel.cpp}::d, date(), QuantLib::Settings::evaluationDate(), QuantLib::Singleton< Settings >::instance(), knownDates(), and QL_REQUIRE.
Referenced by DateTest::ecbDates(), and nextDates().
{
        Date d = (date == Date() ?
                  Settings::instance().evaluationDate() :
                  date);
        std::set<Date>::const_iterator i =
            std::upper_bound(knownDates().begin(), knownDates().end(), d);
        QL_REQUIRE(i!=knownDates().end(),
                   "ECB dates after " << *knownDates().end() << " are unknown");
        return std::vector<Date>(i, knownDates().end());
    }
static std::vector<Date> QuantLib::ECB::nextDates (const std::string & ecbCode, const Date & referenceDate = Date()) [inline, static]
next maintenance period start dates following the given code
Definition at line 74 of file ecb.hpp.
References date(), and nextDates().
{
            return nextDates(date(ecbCode, referenceDate));
        }
void QuantLib::ECB::removeDate (const Date & d) [static]
Definition at line 62 of file ecb.cpp.
References knownDates(), and QuantLib::knownDateSet.
Referenced by DateTest::ecbDates().
{
        knownDates(); // just to ensure inizialization
        knownDateSet.erase(d);
    }
The documentation for this struct was generated from the following files:
/home/deriversatile/QuantLib/QuantLibQt/ql/time/ecb.hpp
/home/deriversatile/QuantLib/QuantLibQt/ql/time/ecb.cpp