QuantLib: anonymous_namespace{inflationcpiswap.cpp}::CommonVars Struct Reference
anonymous_namespace{inflationcpiswap.cpp}::CommonVars Struct Reference
Public Member Functions
CommonVars ()
Public Attributes
Size length
Date startDate
Real volatility
Frequency frequency
std::vector< Real > nominals
Calendar calendar
BusinessDayConvention convention
Natural fixingDays
Date evaluationDate
Natural settlementDays
Date settlement
Period observationLag
Period contractObservationLag
CPI::InterpolationType contractObservationInterpolation
DayCounter dcZCIIS
DayCounter dcNominal
std::vector< Date > zciisD
std::vector< Rate > zciisR
boost::shared_ptr< UKRPI > ii
Size zciisDataLength
RelinkableHandle
< YieldTermStructure > nominalTS
boost::shared_ptr
< ZeroInflationTermStructure > cpiTS
RelinkableHandle
< ZeroInflationTermStructure > hcpi
SavedSettings backup
Detailed Description
Definition at line 78 of file inflationcpiswap.cpp.
Constructor & Destructor Documentation
anonymous_namespace{inflationcpiswap.cpp}::CommonVars::CommonVars () [inline]
Definition at line 110 of file inflationcpiswap.cpp.
References QuantLib::Calendar::adjust(), QuantLib::Calendar::advance(), QuantLib::Annual, anonymous_namespace{marketmodel.cpp}::calendar, QuantLib::Days, QuantLib::December, QuantLib::Settings::evaluationDate(), QuantLib::February, QuantLib::CPI::Flat, QuantLib::MakeSchedule::from(), QuantLib::Singleton< Settings >::instance(), QuantLib::July, QuantLib::June, anonymous_namespace{inflation.cpp}::makeHelpers(), QuantLib::March, QuantLib::May, QuantLib::ModifiedFollowing, QuantLib::Months, QuantLib::November, QuantLib::io::rate(), QuantLib::September, QuantLib::Schedule::size(), anonymous_namespace{marketmodel.cpp}::startDate, QuantLib::MakeSchedule::to(), QuantLib::io::volatility(), QuantLib::MakeSchedule::withCalendar(), QuantLib::MakeSchedule::withConvention(), and QuantLib::MakeSchedule::withTenor().
                     {
            // option variables
            nominals = std::vector<Real>(1,1000000);  // 1M
            frequency = Annual;
            // usual setup
            volatility = 0.01;
            length = 7;
            calendar = UnitedKingdom();
            convention = ModifiedFollowing;
            Date today(25, November, 2009);
            evaluationDate = calendar.adjust(today);
            Settings::instance().evaluationDate() = evaluationDate;
            settlementDays = 0;
            fixingDays = 0;
            settlement = calendar.advance(today,settlementDays,Days);
            startDate = settlement;
            dcZCIIS = ActualActual();
            dcNominal = ActualActual();
            // uk rpi index
            //      fixing data
            Date from(20, July, 2007);
            //Date from(20, July, 2008);
            Date to(20, November, 2009);
            Schedule rpiSchedule = MakeSchedule().from(from).to(to)
            .withTenor(1*Months)
            .withCalendar(UnitedKingdom())
            .withConvention(ModifiedFollowing);
            Real fixData[] = {
                206.1, 207.3, 208.0, 208.9, 209.7, 210.9,
                209.8, 211.4, 212.1, 214.0, 215.1, 216.8,
                216.5, 217.2, 218.4, 217.7, 216,
                212.9, 210.1, 211.4, 211.3, 211.5,
                212.8, 213.4, 213.4, 213.4, 214.4,
                -999.0, -999.0 };
            // link from cpi index to cpi TS
            bool interp = false;// this MUST be false because the observation lag is only 2 months
                                // for ZCIIS; but not for contract if the contract uses a bigger lag.
            ii = boost::shared_ptr<UKRPI>(new UKRPI(interp, hcpi));
            for (Size i=0; i<rpiSchedule.size();i++) {
                ii->addFixing(rpiSchedule[i], fixData[i], true);// force overwrite in case multiple use
            };
            Datum nominalData[] = {
                { Date(26, November, 2009), 0.475 },
                { Date(2, December, 2009), 0.47498 },
                { Date(29, December, 2009), 0.49988 },
                { Date(25, February, 2010), 0.59955 },
                { Date(18, March, 2010), 0.65361 },
                { Date(25, May, 2010), 0.82830 },
                //  { Date(17, June, 2010), 0.7 },  // can't boostrap with this data point
                { Date(16, September, 2010), 0.78960 },
                { Date(16, December, 2010), 0.93762 },
                { Date(17, March, 2011), 1.12037 },
                { Date(16, June, 2011), 1.31308 },
                { Date(22, September, 2011),1.52011 },
                { Date(25, November, 2011), 1.78399 },
                { Date(26, November, 2012), 2.41170 },
                { Date(25, November, 2013), 2.83935 },
                { Date(25, November, 2014), 3.12888 },
                { Date(25, November, 2015), 3.34298 },
                { Date(25, November, 2016), 3.50632 },
                { Date(27, November, 2017), 3.63666 },
                { Date(26, November, 2018), 3.74723 },
                { Date(25, November, 2019), 3.83988 },
                { Date(25, November, 2021), 4.00508 },
                { Date(25, November, 2024), 4.16042 },
                { Date(26, November, 2029), 4.15577 },
                { Date(27, November, 2034), 4.04933 },
                { Date(25, November, 2039), 3.95217 },
                { Date(25, November, 2049), 3.80932 },
                { Date(25, November, 2059), 3.80849 },
                { Date(25, November, 2069), 3.72677 },
                { Date(27, November, 2079), 3.63082 }
            };
            const Size nominalDataLength = 30-1;
            std::vector<Date> nomD;
            std::vector<Rate> nomR;
            for (Size i = 0; i < nominalDataLength; i++) {
                nomD.push_back(nominalData[i].date);
                nomR.push_back(nominalData[i].rate/100.0);
            }
            boost::shared_ptr<YieldTermStructure> nominal =
            boost::shared_ptr<InterpolatedZeroCurve<Linear>
            >(new InterpolatedZeroCurve<Linear>(nomD,nomR,dcNominal));
            nominalTS.linkTo(nominal);
            // now build the zero inflation curve
            observationLag = Period(2,Months);
            contractObservationLag = Period(3,Months);
            contractObservationInterpolation = CPI::Flat;
            Datum zciisData[] = {
                { Date(25, November, 2010), 3.0495 },
                { Date(25, November, 2011), 2.93 },
                { Date(26, November, 2012), 2.9795 },
                { Date(25, November, 2013), 3.029 },
                { Date(25, November, 2014), 3.1425 },
                { Date(25, November, 2015), 3.211 },
                { Date(25, November, 2016), 3.2675 },
                { Date(25, November, 2017), 3.3625 },
                { Date(25, November, 2018), 3.405 },
                { Date(25, November, 2019), 3.48 },
                { Date(25, November, 2021), 3.576 },
                { Date(25, November, 2024), 3.649 },
                { Date(26, November, 2029), 3.751 },
                { Date(27, November, 2034), 3.77225 },
                { Date(25, November, 2039), 3.77 },
                { Date(25, November, 2049), 3.734 },
                { Date(25, November, 2059), 3.714 },
            };
            zciisDataLength = 17;
            for (Size i = 0; i < zciisDataLength; i++) {
                zciisD.push_back(zciisData[i].date);
                zciisR.push_back(zciisData[i].rate);
            }
            // now build the helpers ...
            std::vector<boost::shared_ptr<BootstrapHelper<ZeroInflationTermStructure> > > helpers =
            makeHelpers<ZeroInflationTermStructure,ZeroCouponInflationSwapHelper,
            ZeroInflationIndex>(zciisData, zciisDataLength, ii,
                                observationLag,
                                calendar, convention, dcZCIIS);
            // we can use historical or first ZCIIS for this
            // we know historical is WAY off market-implied, so use market implied flat.
            Rate baseZeroRate = zciisData[0].rate/100.0;
            boost::shared_ptr<PiecewiseZeroInflationCurve<Linear> > pCPIts(
                                new PiecewiseZeroInflationCurve<Linear>(
                                    evaluationDate, calendar, dcZCIIS, observationLag,
                                    ii->frequency(),ii->interpolated(), baseZeroRate,
                                    Handle<YieldTermStructure>(nominalTS), helpers));
            pCPIts->recalculate();
            cpiTS = boost::dynamic_pointer_cast<ZeroInflationTermStructure>(pCPIts);
            // make sure that the index has the latest zero inflation term structure
            hcpi.linkTo(pCPIts);
        }
Member Data Documentation
SavedSettings anonymous_namespace{inflationcpiswap.cpp}::CommonVars::backup
Definition at line 107 of file inflationcpiswap.cpp.
Calendar anonymous_namespace{inflationcpiswap.cpp}::CommonVars::calendar
Definition at line 87 of file inflationcpiswap.cpp.
CPI::InterpolationType anonymous_namespace{inflationcpiswap.cpp}::CommonVars::contractObservationInterpolation
Definition at line 94 of file inflationcpiswap.cpp.
Period anonymous_namespace{inflationcpiswap.cpp}::CommonVars::contractObservationLag
Definition at line 93 of file inflationcpiswap.cpp.
BusinessDayConvention anonymous_namespace{inflationcpiswap.cpp}::CommonVars::convention
Definition at line 88 of file inflationcpiswap.cpp.
boost::shared_ptr<ZeroInflationTermStructure> anonymous_namespace{inflationcpiswap.cpp}::CommonVars::cpiTS
Definition at line 102 of file inflationcpiswap.cpp.
DayCounter anonymous_namespace{inflationcpiswap.cpp}::CommonVars::dcNominal
Definition at line 95 of file inflationcpiswap.cpp.
DayCounter anonymous_namespace{inflationcpiswap.cpp}::CommonVars::dcZCIIS
Definition at line 95 of file inflationcpiswap.cpp.
Date anonymous_namespace{inflationcpiswap.cpp}::CommonVars::evaluationDate
Definition at line 90 of file inflationcpiswap.cpp.
Natural anonymous_namespace{inflationcpiswap.cpp}::CommonVars::fixingDays
Definition at line 89 of file inflationcpiswap.cpp.
Frequency anonymous_namespace{inflationcpiswap.cpp}::CommonVars::frequency
Definition at line 85 of file inflationcpiswap.cpp.
RelinkableHandle<ZeroInflationTermStructure> anonymous_namespace{inflationcpiswap.cpp}::CommonVars::hcpi
Definition at line 103 of file inflationcpiswap.cpp.
boost::shared_ptr<UKRPI> anonymous_namespace{inflationcpiswap.cpp}::CommonVars::ii
Definition at line 98 of file inflationcpiswap.cpp.
Size anonymous_namespace{inflationcpiswap.cpp}::CommonVars::length
Definition at line 81 of file inflationcpiswap.cpp.
std::vector<Real> anonymous_namespace{inflationcpiswap.cpp}::CommonVars::nominals
Definition at line 86 of file inflationcpiswap.cpp.
RelinkableHandle<YieldTermStructure> anonymous_namespace{inflationcpiswap.cpp}::CommonVars::nominalTS
Definition at line 101 of file inflationcpiswap.cpp.
Period anonymous_namespace{inflationcpiswap.cpp}::CommonVars::observationLag
Definition at line 93 of file inflationcpiswap.cpp.
Date anonymous_namespace{inflationcpiswap.cpp}::CommonVars::settlement
Definition at line 92 of file inflationcpiswap.cpp.
Natural anonymous_namespace{inflationcpiswap.cpp}::CommonVars::settlementDays
Definition at line 91 of file inflationcpiswap.cpp.
Date anonymous_namespace{inflationcpiswap.cpp}::CommonVars::startDate
Definition at line 82 of file inflationcpiswap.cpp.
Real anonymous_namespace{inflationcpiswap.cpp}::CommonVars::volatility
Definition at line 83 of file inflationcpiswap.cpp.
std::vector<Date> anonymous_namespace{inflationcpiswap.cpp}::CommonVars::zciisD
Definition at line 96 of file inflationcpiswap.cpp.
Size anonymous_namespace{inflationcpiswap.cpp}::CommonVars::zciisDataLength
Definition at line 99 of file inflationcpiswap.cpp.
std::vector<Rate> anonymous_namespace{inflationcpiswap.cpp}::CommonVars::zciisR
Definition at line 97 of file inflationcpiswap.cpp.
The documentation for this struct was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/inflationcpiswap.cpp