QuantLib: anonymous_namespace{swaptionvolatilitycube.cpp}::CommonVars Struct Reference
anonymous_namespace{swaptionvolatilitycube.cpp}::CommonVars Struct Reference
Public Member Functions
void makeAtmVolTest (const SwaptionVolatilityCube &volCube, Real tolerance)
void makeVolSpreadsTest (const SwaptionVolatilityCube &volCube, Real tolerance)
CommonVars ()
Public Attributes
SwaptionMarketConventions conventions
AtmVolatility atm
RelinkableHandle
< SwaptionVolatilityStructure > atmVolMatrix
VolatilityCube cube
RelinkableHandle
< YieldTermStructure > termStructure
boost::shared_ptr< SwapIndex > swapIndexBase
boost::shared_ptr< SwapIndex > shortSwapIndexBase
bool vegaWeighedSmileFit
SavedSettings backup
Detailed Description
Definition at line 37 of file swaptionvolatilitycube.cpp.
Constructor & Destructor Documentation
anonymous_namespace{swaptionvolatilitycube.cpp}::CommonVars::CommonVars () [inline]
Definition at line 118 of file swaptionvolatilitycube.cpp.
References QuantLib::flatRate(), and QuantLib::Years.
                     {
            conventions.setConventions();
            // ATM swaptionvolmatrix
            atm.setMarketData();
            atmVolMatrix = RelinkableHandle<SwaptionVolatilityStructure>(
                boost::shared_ptr<SwaptionVolatilityStructure>(new
                    SwaptionVolatilityMatrix(conventions.calendar,
                                             conventions.optionBdc,
                                             atm.tenors.options,
                                             atm.tenors.swaps,
                                             atm.volsHandle,
                                             conventions.dayCounter)));
            // Swaptionvolcube
            cube.setMarketData();
            termStructure.linkTo(flatRate(0.05, Actual365Fixed()));
            swapIndexBase = boost::shared_ptr<SwapIndex>(new
                EuriborSwapIsdaFixA(2*Years, termStructure));
            shortSwapIndexBase = boost::shared_ptr<SwapIndex>(new
                EuriborSwapIsdaFixA(1*Years, termStructure));
            vegaWeighedSmileFit=false;
        }
Member Function Documentation
void anonymous_namespace{swaptionvolatilitycube.cpp}::CommonVars::makeAtmVolTest (const SwaptionVolatilityCube & volCube, Real tolerance) [inline]
Definition at line 53 of file swaptionvolatilitycube.cpp.
References QuantLib::SwaptionVolatilityCube::atmStrike(), QuantLib::io::rate(), QuantLib::SwaptionVolatilityStructure::volatility(), and QuantLib::io::volatility().
{
            for (Size i=0; i<atm.tenors.options.size(); i++) {
              for (Size j=0; j<atm.tenors.swaps.size(); j++) {
                Rate strike = volCube.atmStrike(atm.tenors.options[i],
                                                atm.tenors.swaps[j]);
                Volatility expVol =
                    atmVolMatrix->volatility(atm.tenors.options[i],
                                             atm.tenors.swaps[j],
                                             strike, true);
                Volatility actVol = volCube.volatility(atm.tenors.options[i],
                                                       atm.tenors.swaps[j],
                                                       strike, true);
                Volatility error = std::abs(expVol-actVol);
                if (error>tolerance)
                  BOOST_ERROR("\nrecovery of atm vols failed:"
                              "\nexpiry time = " << atm.tenors.options[i] <<
                              "\nswap length = " << atm.tenors.swaps[j] <<
                              "\n atm strike = " << io::rate(strike) <<
                              "\n   exp. vol = " << io::volatility(expVol) <<
                              "\n actual vol = " << io::volatility(actVol) <<
                              "\n      error = " << io::volatility(error) <<
                              "\n  tolerance = " << tolerance);
              }
            }
        }
void anonymous_namespace{swaptionvolatilitycube.cpp}::CommonVars::makeVolSpreadsTest (const SwaptionVolatilityCube & volCube, Real tolerance) [inline]
Definition at line 81 of file swaptionvolatilitycube.cpp.
References QuantLib::SwaptionVolatilityCube::atmStrike(), QuantLib::io::rate(), QuantLib::SwaptionVolatilityStructure::volatility(), and QuantLib::io::volatility().
{
            for (Size i=0; i<cube.tenors.options.size(); i++) {
              for (Size j=0; j<cube.tenors.swaps.size(); j++) {
                for (Size k=0; k<cube.strikeSpreads.size(); k++) {
                  Rate atmStrike = volCube.atmStrike(cube.tenors.options[i],
                                                     cube.tenors.swaps[j]);
                  Volatility atmVol =
                      atmVolMatrix->volatility(cube.tenors.options[i],
                                               cube.tenors.swaps[j],
                                               atmStrike, true);
                  Volatility vol =
                      volCube.volatility(cube.tenors.options[i],
                                         cube.tenors.swaps[j],
                                         atmStrike+cube.strikeSpreads[k], true);
                  Volatility spread = vol-atmVol;
                  Volatility expVolSpread =
                      cube.volSpreads[i*cube.tenors.swaps.size()+j][k];
                  Volatility error = std::abs(expVolSpread-spread);
                  if (error>tolerance)
                      BOOST_FAIL("\nrecovery of smile vol spreads failed:"
                                 "\n    option tenor = " << cube.tenors.options[i] <<
                                 "\n      swap tenor = " << cube.tenors.swaps[j] <<
                                 "\n      atm strike = " << io::rate(atmStrike) <<
                                 "\n   strike spread = " << io::rate(cube.strikeSpreads[k]) <<
                                 "\n         atm vol = " << io::volatility(atmVol) <<
                                 "\n      smiled vol = " << io::volatility(vol) <<
                                 "\n      vol spread = " << io::volatility(spread) <<
                                 "\n exp. vol spread = " << io::volatility(expVolSpread) <<
                                 "\n           error = " << io::volatility(error) <<
                                 "\n       tolerance = " << tolerance);
                }
              }
            }
        }
Member Data Documentation
AtmVolatility anonymous_namespace{swaptionvolatilitycube.cpp}::CommonVars::atm
Definition at line 40 of file swaptionvolatilitycube.cpp.
RelinkableHandle<SwaptionVolatilityStructure> anonymous_namespace{swaptionvolatilitycube.cpp}::CommonVars::atmVolMatrix
Definition at line 41 of file swaptionvolatilitycube.cpp.
SavedSettings anonymous_namespace{swaptionvolatilitycube.cpp}::CommonVars::backup
Definition at line 50 of file swaptionvolatilitycube.cpp.
SwaptionMarketConventions anonymous_namespace{swaptionvolatilitycube.cpp}::CommonVars::conventions
Definition at line 39 of file swaptionvolatilitycube.cpp.
VolatilityCube anonymous_namespace{swaptionvolatilitycube.cpp}::CommonVars::cube
Definition at line 42 of file swaptionvolatilitycube.cpp.
boost::shared_ptr<SwapIndex> anonymous_namespace{swaptionvolatilitycube.cpp}::CommonVars::shortSwapIndexBase
Definition at line 46 of file swaptionvolatilitycube.cpp.
boost::shared_ptr<SwapIndex> anonymous_namespace{swaptionvolatilitycube.cpp}::CommonVars::swapIndexBase
Definition at line 46 of file swaptionvolatilitycube.cpp.
RelinkableHandle<YieldTermStructure> anonymous_namespace{swaptionvolatilitycube.cpp}::CommonVars::termStructure
Definition at line 44 of file swaptionvolatilitycube.cpp.
bool anonymous_namespace{swaptionvolatilitycube.cpp}::CommonVars::vegaWeighedSmileFit
Definition at line 47 of file swaptionvolatilitycube.cpp.
The documentation for this struct was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/swaptionvolatilitycube.cpp