QuantLib: anonymous_namespace{capfloor.cpp}::CommonVars Struct Reference
anonymous_namespace{capfloor.cpp}::CommonVars Struct Reference
Public Member Functions
CommonVars ()
Leg makeLeg (const Date &startDate, Integer length)
boost::shared_ptr< PricingEngine > makeEngine (Volatility volatility)
boost::shared_ptr< CapFloor > makeCapFloor (CapFloor::Type type, const Leg &leg, Rate strike, Volatility volatility)
Public Attributes
Date settlement
std::vector< Real > nominals
BusinessDayConvention convention
Frequency frequency
boost::shared_ptr< IborIndex > index
Calendar calendar
Natural fixingDays
RelinkableHandle
< YieldTermStructure > termStructure
SavedSettings backup
Detailed Description
Definition at line 46 of file capfloor.cpp.
Constructor & Destructor Documentation
anonymous_namespace{capfloor.cpp}::CommonVars::CommonVars () [inline]
Definition at line 62 of file capfloor.cpp.
References anonymous_namespace{marketmodel.cpp}::calendar, QuantLib::Days, QuantLib::Settings::evaluationDate(), QuantLib::flatRate(), QuantLib::Singleton< Settings >::instance(), QuantLib::ActualActual::ISDA, QuantLib::ModifiedFollowing, QuantLib::Semiannual, and QuantLib::Date::todaysDate().
                     {
            nominals = std::vector<Real>(1,100);
            frequency = Semiannual;
            index = boost::shared_ptr<IborIndex>(new Euribor6M(termStructure));
            calendar = index->fixingCalendar();
            convention = ModifiedFollowing;
            Date today = calendar.adjust(Date::todaysDate());
            Settings::instance().evaluationDate() = today;
            Natural settlementDays = 2;
            fixingDays = 2;
            settlement = calendar.advance(today,settlementDays,Days);
            termStructure.linkTo(flatRate(settlement,0.05,
                                          ActualActual(ActualActual::ISDA)));
        }
Member Function Documentation
boost::shared_ptr<CapFloor> anonymous_namespace{capfloor.cpp}::CommonVars::makeCapFloor (CapFloor::Type type, const Leg & leg, Rate strike, Volatility volatility) [inline]
Definition at line 97 of file capfloor.cpp.
References QuantLib::CapFloor::Cap, QuantLib::CapFloor::Floor, and QL_FAIL.
{
            boost::shared_ptr<CapFloor> result;
            switch (type) {
              case CapFloor::Cap:
                result = boost::shared_ptr<CapFloor>(
                                  new Cap(leg, std::vector<Rate>(1, strike)));
                break;
              case CapFloor::Floor:
                result = boost::shared_ptr<CapFloor>(
                                new Floor(leg, std::vector<Rate>(1, strike)));
                break;
              default:
                QL_FAIL("unknown cap/floor type");
            }
            result->setPricingEngine(makeEngine(volatility));
            return result;
        }
boost::shared_ptr<PricingEngine> anonymous_namespace{capfloor.cpp}::CommonVars::makeEngine (Volatility volatility) [inline]
Definition at line 90 of file capfloor.cpp.
{
            Handle<Quote> vol(boost::shared_ptr<Quote>(
                                                new SimpleQuote(volatility)));
            return boost::shared_ptr<PricingEngine>(
                                new BlackCapFloorEngine(termStructure, vol));
        }
Leg anonymous_namespace{capfloor.cpp}::CommonVars::makeLeg (const Date & startDate, Integer length) [inline]
Definition at line 78 of file capfloor.cpp.
References QuantLib::Calendar::advance(), anonymous_namespace{marketmodel.cpp}::calendar, anonymous_namespace{marketmodel.cpp}::endDate, QuantLib::DateGeneration::Forward, QuantLib::IborLeg::withFixingDays(), QuantLib::IborLeg::withNotionals(), QuantLib::IborLeg::withPaymentDayCounter(), and QuantLib::Years.
{
            Date endDate = calendar.advance(startDate,length*Years,convention);
            Schedule schedule(startDate, endDate, Period(frequency), calendar,
                              convention, convention,
                              DateGeneration::Forward, false);
            return IborLeg(schedule, index)
                .withNotionals(nominals)
                .withPaymentDayCounter(index->dayCounter())
                .withPaymentAdjustment(convention)
                .withFixingDays(fixingDays);
        }
Member Data Documentation
SavedSettings anonymous_namespace{capfloor.cpp}::CommonVars::backup
Definition at line 59 of file capfloor.cpp.
Calendar anonymous_namespace{capfloor.cpp}::CommonVars::calendar
Definition at line 53 of file capfloor.cpp.
BusinessDayConvention anonymous_namespace{capfloor.cpp}::CommonVars::convention
Definition at line 50 of file capfloor.cpp.
Natural anonymous_namespace{capfloor.cpp}::CommonVars::fixingDays
Definition at line 54 of file capfloor.cpp.
Frequency anonymous_namespace{capfloor.cpp}::CommonVars::frequency
Definition at line 51 of file capfloor.cpp.
boost::shared_ptr<IborIndex> anonymous_namespace{capfloor.cpp}::CommonVars::index
Definition at line 52 of file capfloor.cpp.
std::vector<Real> anonymous_namespace{capfloor.cpp}::CommonVars::nominals
Definition at line 49 of file capfloor.cpp.
Date anonymous_namespace{capfloor.cpp}::CommonVars::settlement
Definition at line 48 of file capfloor.cpp.
RelinkableHandle<YieldTermStructure> anonymous_namespace{capfloor.cpp}::CommonVars::termStructure
Definition at line 55 of file capfloor.cpp.
The documentation for this struct was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/capfloor.cpp