QuantLib: anonymous_namespace{bermudanswaption.cpp}::CommonVars Struct Reference
anonymous_namespace{bermudanswaption.cpp}::CommonVars Struct Reference
Public Member Functions
CommonVars ()
boost::shared_ptr< VanillaSwap > makeSwap (Rate fixedRate)
Public Attributes
Date today
Date settlement
Calendar calendar
Integer startYears
Integer length
VanillaSwap::Type type
Real nominal
BusinessDayConvention fixedConvention
BusinessDayConvention floatingConvention
Frequency fixedFrequency
Frequency floatingFrequency
DayCounter fixedDayCount
boost::shared_ptr< IborIndex > index
Natural settlementDays
RelinkableHandle
< YieldTermStructure > termStructure
SavedSettings backup
Detailed Description
Definition at line 37 of file bermudanswaption.cpp.
Constructor & Destructor Documentation
anonymous_namespace{bermudanswaption.cpp}::CommonVars::CommonVars () [inline]
Definition at line 58 of file bermudanswaption.cpp.
References QuantLib::Calendar::adjust(), QuantLib::Date::advance(), QuantLib::Annual, anonymous_namespace{marketmodel.cpp}::calendar, QuantLib::Days, QuantLib::ModifiedFollowing, QuantLib::VanillaSwap::Payer, QuantLib::Semiannual, QuantLib::Date::todaysDate(), and QuantLib::Unadjusted.
                     {
            startYears = 1;
            length = 5;
            type = VanillaSwap::Payer;
            nominal = 1000.0;
            settlementDays = 2;
            fixedConvention = Unadjusted;
            floatingConvention = ModifiedFollowing;
            fixedFrequency = Annual;
            floatingFrequency = Semiannual;
            fixedDayCount = Thirty360();
            index = boost::shared_ptr<IborIndex>(new Euribor6M(termStructure));
            calendar = index->fixingCalendar();
            today = calendar.adjust(Date::todaysDate());
            settlement = calendar.advance(today,settlementDays,Days);
        }
Member Function Documentation
boost::shared_ptr<VanillaSwap> anonymous_namespace{bermudanswaption.cpp}::CommonVars::makeSwap (Rate fixedRate) [inline]
Definition at line 76 of file bermudanswaption.cpp.
References QuantLib::Calendar::advance(), anonymous_namespace{marketmodel.cpp}::calendar, QuantLib::DateGeneration::Forward, QuantLib::swap(), and QuantLib::Years.
{
            Date start = calendar.advance(settlement, startYears, Years);
            Date maturity = calendar.advance(start, length, Years);
            Schedule fixedSchedule(start, maturity,
                                   Period(fixedFrequency),
                                   calendar,
                                   fixedConvention,
                                   fixedConvention,
                                   DateGeneration::Forward, false);
            Schedule floatSchedule(start, maturity,
                                   Period(floatingFrequency),
                                   calendar,
                                   floatingConvention,
                                   floatingConvention,
                                   DateGeneration::Forward, false);
            boost::shared_ptr<VanillaSwap> swap(
                      new VanillaSwap(type, nominal,
                                      fixedSchedule, fixedRate, fixedDayCount,
                                      floatSchedule, index, 0.0,
                                      index->dayCounter()));
            swap->setPricingEngine(boost::shared_ptr<PricingEngine>(
                                   new DiscountingSwapEngine(termStructure)));
            return swap;
        }
Member Data Documentation
SavedSettings anonymous_namespace{bermudanswaption.cpp}::CommonVars::backup
Definition at line 55 of file bermudanswaption.cpp.
Calendar anonymous_namespace{bermudanswaption.cpp}::CommonVars::calendar
Definition at line 40 of file bermudanswaption.cpp.
BusinessDayConvention anonymous_namespace{bermudanswaption.cpp}::CommonVars::fixedConvention
Definition at line 46 of file bermudanswaption.cpp.
DayCounter anonymous_namespace{bermudanswaption.cpp}::CommonVars::fixedDayCount
Definition at line 48 of file bermudanswaption.cpp.
Frequency anonymous_namespace{bermudanswaption.cpp}::CommonVars::fixedFrequency
Definition at line 47 of file bermudanswaption.cpp.
BusinessDayConvention anonymous_namespace{bermudanswaption.cpp}::CommonVars::floatingConvention
Definition at line 46 of file bermudanswaption.cpp.
Frequency anonymous_namespace{bermudanswaption.cpp}::CommonVars::floatingFrequency
Definition at line 47 of file bermudanswaption.cpp.
boost::shared_ptr<IborIndex> anonymous_namespace{bermudanswaption.cpp}::CommonVars::index
Definition at line 49 of file bermudanswaption.cpp.
Integer anonymous_namespace{bermudanswaption.cpp}::CommonVars::length
Definition at line 43 of file bermudanswaption.cpp.
Real anonymous_namespace{bermudanswaption.cpp}::CommonVars::nominal
Definition at line 45 of file bermudanswaption.cpp.
Date anonymous_namespace{bermudanswaption.cpp}::CommonVars::settlement
Definition at line 39 of file bermudanswaption.cpp.
Natural anonymous_namespace{bermudanswaption.cpp}::CommonVars::settlementDays
Definition at line 50 of file bermudanswaption.cpp.
Integer anonymous_namespace{bermudanswaption.cpp}::CommonVars::startYears
Definition at line 43 of file bermudanswaption.cpp.
RelinkableHandle<YieldTermStructure> anonymous_namespace{bermudanswaption.cpp}::CommonVars::termStructure
Definition at line 52 of file bermudanswaption.cpp.
Date anonymous_namespace{bermudanswaption.cpp}::CommonVars::today
Definition at line 39 of file bermudanswaption.cpp.
VanillaSwap::Type anonymous_namespace{bermudanswaption.cpp}::CommonVars::type
Definition at line 44 of file bermudanswaption.cpp.
The documentation for this struct was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/bermudanswaption.cpp