QuantLib: anonymous_namespace{overnightindexedswap.cpp}::CommonVars Struct Reference
anonymous_namespace{overnightindexedswap.cpp}::CommonVars Struct Reference
Public Member Functions
shared_ptr< OvernightIndexedSwap > makeSwap (Period length, Rate fixedRate, Spread spread)
CommonVars ()
Public Attributes
Date today
Date settlement
OvernightIndexedSwap::Type type
Real nominal
Calendar calendar
Natural settlementDays
Period fixedEoniaPeriod
Period floatingEoniaPeriod
DayCounter fixedEoniaDayCount
BusinessDayConvention fixedEoniaConvention
BusinessDayConvention floatingEoniaConvention
shared_ptr< Eonia > eoniaIndex
RelinkableHandle
< YieldTermStructure > eoniaTermStructure
Frequency fixedSwapFrequency
DayCounter fixedSwapDayCount
BusinessDayConvention fixedSwapConvention
shared_ptr< IborIndex > swapIndex
RelinkableHandle
< YieldTermStructure > swapTermStructure
SavedSettings backup
Detailed Description
Definition at line 154 of file overnightindexedswap.cpp.
Constructor & Destructor Documentation
anonymous_namespace{overnightindexedswap.cpp}::CommonVars::CommonVars () [inline]
Definition at line 188 of file overnightindexedswap.cpp.
References QuantLib::Annual, anonymous_namespace{marketmodel.cpp}::calendar, QuantLib::Days, QuantLib::Settings::evaluationDate(), QuantLib::February, QuantLib::flatRate(), QuantLib::Following, QuantLib::Singleton< Settings >::instance(), QuantLib::ModifiedFollowing, QuantLib::OvernightIndexedSwap::Payer, and QuantLib::Years.
                     {
            type = OvernightIndexedSwap::Payer;
            settlementDays = 2;
            nominal = 100.0;
            fixedEoniaConvention = ModifiedFollowing;
            floatingEoniaConvention = ModifiedFollowing;
            fixedEoniaPeriod = 1*Years;
            floatingEoniaPeriod = 1*Years;
            fixedEoniaDayCount = Actual360();
            eoniaIndex = shared_ptr<Eonia>(new Eonia(eoniaTermStructure));
            fixedSwapConvention = ModifiedFollowing;
            fixedSwapFrequency = Annual;
            fixedSwapDayCount = Thirty360();
            swapIndex = shared_ptr<IborIndex>(new Euribor3M(swapTermStructure));
            calendar = eoniaIndex->fixingCalendar();
            today = Date(5, February, 2009);
            //today = calendar.adjust(Date::todaysDate());
            Settings::instance().evaluationDate() = today;
            settlement = calendar.advance(today,settlementDays*Days,Following);
            eoniaTermStructure.linkTo(flatRate(settlement, 0.05,
                                               Actual365Fixed()));
        }
Member Function Documentation
shared_ptr<OvernightIndexedSwap> anonymous_namespace{overnightindexedswap.cpp}::CommonVars::makeSwap (Period length, Rate fixedRate, Spread spread) [inline]
Definition at line 178 of file overnightindexedswap.cpp.
References QuantLib::MakeOIS::withDiscountingTermStructure(), QuantLib::MakeOIS::withEffectiveDate(), QuantLib::MakeOIS::withNominal(), and QuantLib::MakeOIS::withOvernightLegSpread().
{
            return MakeOIS(length, eoniaIndex, fixedRate)
                .withEffectiveDate(settlement)
                .withOvernightLegSpread(spread)
                .withNominal(nominal)
                .withDiscountingTermStructure(eoniaTermStructure);
        }
Member Data Documentation
SavedSettings anonymous_namespace{overnightindexedswap.cpp}::CommonVars::backup
Definition at line 175 of file overnightindexedswap.cpp.
Calendar anonymous_namespace{overnightindexedswap.cpp}::CommonVars::calendar
Definition at line 159 of file overnightindexedswap.cpp.
shared_ptr<Eonia> anonymous_namespace{overnightindexedswap.cpp}::CommonVars::eoniaIndex
Definition at line 165 of file overnightindexedswap.cpp.
RelinkableHandle<YieldTermStructure> anonymous_namespace{overnightindexedswap.cpp}::CommonVars::eoniaTermStructure
Definition at line 166 of file overnightindexedswap.cpp.
BusinessDayConvention anonymous_namespace{overnightindexedswap.cpp}::CommonVars::fixedEoniaConvention
Definition at line 164 of file overnightindexedswap.cpp.
DayCounter anonymous_namespace{overnightindexedswap.cpp}::CommonVars::fixedEoniaDayCount
Definition at line 163 of file overnightindexedswap.cpp.
Period anonymous_namespace{overnightindexedswap.cpp}::CommonVars::fixedEoniaPeriod
Definition at line 162 of file overnightindexedswap.cpp.
BusinessDayConvention anonymous_namespace{overnightindexedswap.cpp}::CommonVars::fixedSwapConvention
Definition at line 170 of file overnightindexedswap.cpp.
DayCounter anonymous_namespace{overnightindexedswap.cpp}::CommonVars::fixedSwapDayCount
Definition at line 169 of file overnightindexedswap.cpp.
Frequency anonymous_namespace{overnightindexedswap.cpp}::CommonVars::fixedSwapFrequency
Definition at line 168 of file overnightindexedswap.cpp.
BusinessDayConvention anonymous_namespace{overnightindexedswap.cpp}::CommonVars::floatingEoniaConvention
Definition at line 164 of file overnightindexedswap.cpp.
Period anonymous_namespace{overnightindexedswap.cpp}::CommonVars::floatingEoniaPeriod
Definition at line 162 of file overnightindexedswap.cpp.
Real anonymous_namespace{overnightindexedswap.cpp}::CommonVars::nominal
Definition at line 158 of file overnightindexedswap.cpp.
Date anonymous_namespace{overnightindexedswap.cpp}::CommonVars::settlement
Definition at line 156 of file overnightindexedswap.cpp.
Natural anonymous_namespace{overnightindexedswap.cpp}::CommonVars::settlementDays
Definition at line 160 of file overnightindexedswap.cpp.
shared_ptr<IborIndex> anonymous_namespace{overnightindexedswap.cpp}::CommonVars::swapIndex
Definition at line 171 of file overnightindexedswap.cpp.
RelinkableHandle<YieldTermStructure> anonymous_namespace{overnightindexedswap.cpp}::CommonVars::swapTermStructure
Definition at line 172 of file overnightindexedswap.cpp.
Date anonymous_namespace{overnightindexedswap.cpp}::CommonVars::today
Definition at line 156 of file overnightindexedswap.cpp.
OvernightIndexedSwap::Type anonymous_namespace{overnightindexedswap.cpp}::CommonVars::type
Definition at line 157 of file overnightindexedswap.cpp.
The documentation for this struct was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/overnightindexedswap.cpp