QuantLib: anonymous_namespace{capflooredcoupon.cpp}::CommonVars Struct Reference
anonymous_namespace{capflooredcoupon.cpp}::CommonVars Struct Reference
Public Member Functions
CommonVars ()
Leg makeFixedLeg (const Date &startDate, Integer length)
Leg makeFloatingLeg (const Date &startDate, Integer length, const Rate gearing=1.0, const Rate spread=0.0)
Leg makeCapFlooredLeg (const Date &startDate, Integer length, const std::vector< Rate > caps, const std::vector< Rate > floors, Volatility volatility, const Rate gearing=1.0, const Rate spread=0.0)
boost::shared_ptr< PricingEngine > makeEngine (Volatility volatility)
boost::shared_ptr< CapFloor > makeCapFloor (CapFloor::Type type, const Leg &leg, Rate capStrike, Rate floorStrike, Volatility volatility)
Public Attributes
Date today
Date settlement
Date startDate
Calendar calendar
Real nominal
std::vector< Real > nominals
BusinessDayConvention convention
Frequency frequency
boost::shared_ptr< IborIndex > index
Natural settlementDays
Natural fixingDays
RelinkableHandle
< YieldTermStructure > termStructure
std::vector< Rate > caps
std::vector< Rate > floors
Integer length
Volatility volatility
SavedSettings backup
Detailed Description
Definition at line 45 of file capflooredcoupon.cpp.
Constructor & Destructor Documentation
anonymous_namespace{capflooredcoupon.cpp}::CommonVars::CommonVars () [inline]
Definition at line 65 of file capflooredcoupon.cpp.
References QuantLib::Annual, anonymous_namespace{marketmodel.cpp}::calendar, QuantLib::Days, QuantLib::Settings::evaluationDate(), QuantLib::flatRate(), QuantLib::Singleton< Settings >::instance(), QuantLib::ActualActual::ISDA, QuantLib::ModifiedFollowing, anonymous_namespace{marketmodel.cpp}::startDate, QuantLib::Date::todaysDate(), and QuantLib::io::volatility().
                     {
            length = 20;           //years
            volatility = 0.20;
            nominal = 100.;
            nominals = std::vector<Real>(length,nominal);
            frequency = Annual;
            index = boost::shared_ptr<IborIndex>(new Euribor1Y(termStructure));
            calendar = index->fixingCalendar();
            convention = ModifiedFollowing;
            today = calendar.adjust(Date::todaysDate());
            Settings::instance().evaluationDate() = today;
            settlementDays = 2;
            fixingDays = 2;
            settlement = calendar.advance(today,settlementDays,Days);
            startDate = settlement;
            termStructure.linkTo(flatRate(settlement,0.05,
                                          ActualActual(ActualActual::ISDA)));
        }
Member Function Documentation
boost::shared_ptr<CapFloor> anonymous_namespace{capflooredcoupon.cpp}::CommonVars::makeCapFloor (CapFloor::Type type, const Leg & leg, Rate capStrike, Rate floorStrike, Volatility volatility) [inline]
Definition at line 161 of file capflooredcoupon.cpp.
References QuantLib::CapFloor::Cap, QuantLib::CapFloor::Collar, QuantLib::CapFloor::Floor, and QL_FAIL.
{
            boost::shared_ptr<CapFloor> result;
            switch (type) {
              case CapFloor::Cap:
                result = boost::shared_ptr<CapFloor>(
                               new Cap(leg, std::vector<Rate>(1, capStrike)));
                break;
              case CapFloor::Floor:
                result = boost::shared_ptr<CapFloor>(
                           new Floor(leg, std::vector<Rate>(1, floorStrike)));
                break;
              case CapFloor::Collar:
                result = boost::shared_ptr<CapFloor>(
                               new Collar(leg,
                                          std::vector<Rate>(1, capStrike),
                                          std::vector<Rate>(1, floorStrike)));
                break;
              default:
                QL_FAIL("unknown cap/floor type");
            }
            result->setPricingEngine(makeEngine(volatility));
            return result;
        }
Leg anonymous_namespace{capflooredcoupon.cpp}::CommonVars::makeCapFlooredLeg (const Date & startDate, Integer length, const std::vector< Rate > caps, const std::vector< Rate > floors, Volatility volatility, const Rate gearing = 1.0, const Rate spread = 0.0) [inline]
Definition at line 119 of file capflooredcoupon.cpp.
References QuantLib::Calendar::advance(), anonymous_namespace{marketmodel.cpp}::calendar, anonymous_namespace{marketmodel.cpp}::endDate, QuantLib::Following, QuantLib::DateGeneration::Forward, QuantLib::setCouponPricer(), QuantLib::IborLeg::withCaps(), QuantLib::IborLeg::withFixingDays(), QuantLib::IborLeg::withFloors(), QuantLib::IborLeg::withGearings(), QuantLib::IborLeg::withNotionals(), QuantLib::IborLeg::withPaymentDayCounter(), QuantLib::IborLeg::withSpreads(), and QuantLib::Years.
{
            Date endDate = calendar.advance(startDate,length,Years,convention);
            Schedule schedule(startDate,endDate,Period(frequency),calendar,
                              convention,convention,
                              DateGeneration::Forward,false);
            Handle<OptionletVolatilityStructure> vol(
                boost::shared_ptr<OptionletVolatilityStructure>(new
                    ConstantOptionletVolatility(0, calendar, Following,
                                                volatility,Actual365Fixed())));
            boost::shared_ptr<IborCouponPricer> pricer(new
                BlackIborCouponPricer(vol));
            std::vector<Rate> gearingVector(length, gearing);
            std::vector<Spread> spreadVector(length, spread);
            Leg iborLeg = IborLeg(schedule, index)
                .withNotionals(nominals)
                .withPaymentDayCounter(index->dayCounter())
                .withPaymentAdjustment(convention)
                .withFixingDays(fixingDays)
                .withGearings(gearingVector)
                .withSpreads(spreadVector)
                .withCaps(caps)
                .withFloors(floors);
            setCouponPricer(iborLeg, pricer);
            return iborLeg;
        }
boost::shared_ptr<PricingEngine> anonymous_namespace{capflooredcoupon.cpp}::CommonVars::makeEngine (Volatility volatility) [inline]
Definition at line 154 of file capflooredcoupon.cpp.
{
            Handle<Quote> vol(boost::shared_ptr<Quote>(
                                                new SimpleQuote(volatility)));
            return boost::shared_ptr<PricingEngine>(
                                 new BlackCapFloorEngine(termStructure, vol));
        }
Leg anonymous_namespace{capflooredcoupon.cpp}::CommonVars::makeFixedLeg (const Date & startDate, Integer length) [inline]
Definition at line 85 of file capflooredcoupon.cpp.
References QuantLib::Calendar::advance(), anonymous_namespace{marketmodel.cpp}::calendar, anonymous_namespace{marketmodel.cpp}::endDate, QuantLib::DateGeneration::Forward, QuantLib::FixedRateLeg::withCouponRates(), QuantLib::FixedRateLeg::withNotionals(), and QuantLib::Years.
{
            Date endDate = calendar.advance(startDate, length, Years,
                                            convention);
            Schedule schedule(startDate, endDate, Period(frequency), calendar,
                              convention, convention,
                              DateGeneration::Forward, false);
            std::vector<Rate> coupons(length, 0.0);
            return FixedRateLeg(schedule)
                .withNotionals(nominals)
                .withCouponRates(coupons, Thirty360());
        }
Leg anonymous_namespace{capflooredcoupon.cpp}::CommonVars::makeFloatingLeg (const Date & startDate, Integer length, const Rate gearing = 1.0, const Rate spread = 0.0) [inline]
Definition at line 99 of file capflooredcoupon.cpp.
References QuantLib::Calendar::advance(), anonymous_namespace{marketmodel.cpp}::calendar, anonymous_namespace{marketmodel.cpp}::endDate, QuantLib::DateGeneration::Forward, QuantLib::IborLeg::withFixingDays(), QuantLib::IborLeg::withGearings(), QuantLib::IborLeg::withNotionals(), QuantLib::IborLeg::withPaymentDayCounter(), QuantLib::IborLeg::withSpreads(), and QuantLib::Years.
{
            Date endDate = calendar.advance(startDate,length,Years,convention);
            Schedule schedule(startDate,endDate,Period(frequency),calendar,
                              convention,convention,
                              DateGeneration::Forward,false);
            std::vector<Real> gearingVector(length, gearing);
            std::vector<Spread> spreadVector(length, spread);
            return IborLeg(schedule, index)
                .withNotionals(nominals)
                .withPaymentDayCounter(index->dayCounter())
                .withPaymentAdjustment(convention)
                .withFixingDays(fixingDays)
                .withGearings(gearingVector)
                .withSpreads(spreadVector);
        }
Member Data Documentation
SavedSettings anonymous_namespace{capflooredcoupon.cpp}::CommonVars::backup
Definition at line 62 of file capflooredcoupon.cpp.
Calendar anonymous_namespace{capflooredcoupon.cpp}::CommonVars::calendar
Definition at line 48 of file capflooredcoupon.cpp.
std::vector<Rate> anonymous_namespace{capflooredcoupon.cpp}::CommonVars::caps
Definition at line 56 of file capflooredcoupon.cpp.
BusinessDayConvention anonymous_namespace{capflooredcoupon.cpp}::CommonVars::convention
Definition at line 51 of file capflooredcoupon.cpp.
Natural anonymous_namespace{capflooredcoupon.cpp}::CommonVars::fixingDays
Definition at line 54 of file capflooredcoupon.cpp.
std::vector<Rate> anonymous_namespace{capflooredcoupon.cpp}::CommonVars::floors
Definition at line 57 of file capflooredcoupon.cpp.
Frequency anonymous_namespace{capflooredcoupon.cpp}::CommonVars::frequency
Definition at line 52 of file capflooredcoupon.cpp.
boost::shared_ptr<IborIndex> anonymous_namespace{capflooredcoupon.cpp}::CommonVars::index
Definition at line 53 of file capflooredcoupon.cpp.
Integer anonymous_namespace{capflooredcoupon.cpp}::CommonVars::length
Definition at line 58 of file capflooredcoupon.cpp.
Real anonymous_namespace{capflooredcoupon.cpp}::CommonVars::nominal
Definition at line 49 of file capflooredcoupon.cpp.
std::vector<Real> anonymous_namespace{capflooredcoupon.cpp}::CommonVars::nominals
Definition at line 50 of file capflooredcoupon.cpp.
Date anonymous_namespace{capflooredcoupon.cpp}::CommonVars::settlement
Definition at line 47 of file capflooredcoupon.cpp.
Natural anonymous_namespace{capflooredcoupon.cpp}::CommonVars::settlementDays
Definition at line 54 of file capflooredcoupon.cpp.
Date anonymous_namespace{capflooredcoupon.cpp}::CommonVars::startDate
Definition at line 47 of file capflooredcoupon.cpp.
RelinkableHandle<YieldTermStructure> anonymous_namespace{capflooredcoupon.cpp}::CommonVars::termStructure
Definition at line 55 of file capflooredcoupon.cpp.
Date anonymous_namespace{capflooredcoupon.cpp}::CommonVars::today
Definition at line 47 of file capflooredcoupon.cpp.
Volatility anonymous_namespace{capflooredcoupon.cpp}::CommonVars::volatility
Definition at line 59 of file capflooredcoupon.cpp.
The documentation for this struct was generated from the following file:
/home/deriversatile/QuantLib/QuantLibQt/test-suite/capflooredcoupon.cpp