QuantLib: /home/deriversatile/QuantLib/QuantLibQt/test-suite/marketmodel.cpp File Reference
marketmodel.cpp File Reference
#include "marketmodel.hpp"
#include "utilities.hpp"
#include <ql/models/marketmodels/accountingengine.hpp>
#include <ql/models/marketmodels/browniangenerators/mtbrowniangenerator.hpp>
#include <ql/models/marketmodels/browniangenerators/sobolbrowniangenerator.hpp>
#include <ql/models/marketmodels/callability/collectnodedata.hpp>
#include <ql/models/marketmodels/callability/lsstrategy.hpp>
#include <ql/models/marketmodels/callability/nothingexercisevalue.hpp>
#include <ql/models/marketmodels/callability/parametricexerciseadapter.hpp>
#include <ql/models/marketmodels/callability/swapbasissystem.hpp>
#include <ql/models/marketmodels/callability/swapratetrigger.hpp>
#include <ql/models/marketmodels/callability/triggeredswapexercise.hpp>
#include <ql/models/marketmodels/callability/upperboundengine.hpp>
#include <ql/models/marketmodels/curvestates/lmmcurvestate.hpp>
#include <ql/models/marketmodels/driftcomputation/lmmdriftcalculator.hpp>
#include <ql/models/marketmodels/evolvers/lognormalfwdrateeuler.hpp>
#include <ql/models/marketmodels/evolvers/lognormalfwdrateeulerconstrained.hpp>
#include <ql/models/marketmodels/evolvers/lognormalfwdrateipc.hpp>
#include <ql/models/marketmodels/evolvers/lognormalfwdrateballand.hpp>
#include <ql/models/marketmodels/evolvers/lognormalfwdratepc.hpp>
#include <ql/models/marketmodels/evolvers/normalfwdratepc.hpp>
#include <ql/models/marketmodels/discounter.hpp>
#include <ql/models/marketmodels/models/abcdvol.hpp>
#include <ql/models/marketmodels/models/flatvol.hpp>
#include <ql/models/marketmodels/correlations/expcorrelations.hpp>
#include <ql/models/marketmodels/correlations/timehomogeneousforwardcorrelation.hpp>
#include <ql/models/marketmodels/products/multiproductcomposite.hpp>
#include <ql/models/marketmodels/products/multistep/callspecifiedmultiproduct.hpp>
#include <ql/models/marketmodels/products/multistep/exerciseadapter.hpp>
#include <ql/models/marketmodels/products/multistep/multistepcoinitialswaps.hpp>
#include <ql/models/marketmodels/products/multistep/multistepcoterminalswaps.hpp>
#include <ql/models/marketmodels/products/multistep/multistepcoterminalswaptions.hpp>
#include <ql/models/marketmodels/products/multistep/multistepperiodcapletswaptions.hpp>
#include <ql/models/marketmodels/products/multistep/multistepforwards.hpp>
#include <ql/models/marketmodels/products/multistep/multistepnothing.hpp>
#include <ql/models/marketmodels/products/multistep/multistepoptionlets.hpp>
#include <ql/models/marketmodels/products/multistep/multistepswap.hpp>
#include <ql/models/marketmodels/products/onestep/onestepforwards.hpp>
#include <ql/models/marketmodels/products/onestep/onestepoptionlets.hpp>
#include <ql/models/marketmodels/forwardforwardmappings.hpp>
#include <ql/models/marketmodels/proxygreekengine.hpp>
#include <ql/models/marketmodels/swapforwardmappings.hpp>
#include <ql/models/marketmodels/models/fwdperiodadapter.hpp>
#include <ql/models/marketmodels/models/fwdtocotswapadapter.hpp>
#include <ql/models/marketmodels/models/cotswaptofwdadapter.hpp>
#include <ql/models/marketmodels/utilities.hpp>
#include <ql/methods/montecarlo/genericlsregression.hpp>
#include <ql/legacy/libormarketmodels/lmlinexpcorrmodel.hpp>
#include <ql/legacy/libormarketmodels/lmextlinexpvolmodel.hpp>
#include <ql/time/schedule.hpp>
#include <ql/time/calendars/nullcalendar.hpp>
#include <ql/time/daycounters/simpledaycounter.hpp>
#include <ql/pricingengines/blackformula.hpp>
#include <ql/pricingengines/blackcalculator.hpp>
#include <ql/utilities/dataformatters.hpp>
#include <ql/math/integrals/segmentintegral.hpp>
#include <ql/math/statistics/convergencestatistics.hpp>
#include <ql/termstructures/volatility/abcd.hpp>
#include <ql/termstructures/volatility/abcdcalibration.hpp>
#include <ql/math/functional.hpp>
#include <ql/math/optimization/simplex.hpp>
#include <ql/quotes/simplequote.hpp>
#include <sstream>
#include <ql/models/marketmodels/products/pathwise/pathwiseproductcaplet.hpp>
#include <ql/models/marketmodels/products/pathwise/pathwiseproductswaption.hpp>
#include <ql/models/marketmodels/pathwiseaccountingengine.hpp>
#include <ql/models/marketmodels/pathwisegreeks/ratepseudorootjacobian.hpp>
#include <ql/models/marketmodels/pathwisegreeks/swaptionpseudojacobian.hpp>
#include <ql/models/marketmodels/models/pseudorootfacade.hpp>
#include <ql/models/marketmodels/pathwisegreeks/bumpinstrumentjacobian.hpp>
#include <ql/models/marketmodels/evolvers/volprocesses/squarerootandersen.hpp>
#include <ql/models/marketmodels/evolvers/svddfwdratepc.hpp>
#include <ql/processes/hestonprocess.hpp>
#include <ql/models/equity/hestonmodel.hpp>
#include <ql/time/daycounters/actualactual.hpp>
#include <ql/pricingengines/vanilla/analytichestonengine.hpp>
#include <ql/models/marketmodels/products/multistep/multistepinversefloater.hpp>
#include <ql/models/marketmodels/products/pathwise/pathwiseproductinversefloater.hpp>
#include <ql/models/marketmodels/products/multistep/multisteppathwisewrapper.hpp>
Classes
struct anonymous_namespace{marketmodel.cpp}::SubProductExpectedValues
Namespaces
namespace anonymous_namespace{marketmodel.cpp}
Defines
#define BEGIN(x) (x+0)
#define END(x) (x+LENGTH(x))
Enumerations
enum anonymous_namespace{marketmodel.cpp}::MarketModelType { anonymous_namespace{marketmodel.cpp}::ExponentialCorrelationFlatVolatility, anonymous_namespace{marketmodel.cpp}::ExponentialCorrelationAbcdVolatility }
enum anonymous_namespace{marketmodel.cpp}::MeasureType { anonymous_namespace{marketmodel.cpp}::ProductSuggested, anonymous_namespace{marketmodel.cpp}::Terminal, anonymous_namespace{marketmodel.cpp}::MoneyMarket, anonymous_namespace{marketmodel.cpp}::MoneyMarketPlus }
enum anonymous_namespace{marketmodel.cpp}::EvolverType { anonymous_namespace{marketmodel.cpp}::Ipc, anonymous_namespace{marketmodel.cpp}::Balland, anonymous_namespace{marketmodel.cpp}::Pc, anonymous_namespace{marketmodel.cpp}::NormalPc }
Functions
void anonymous_namespace{marketmodel.cpp}::setup ()
const boost::shared_ptr
< SequenceStatisticsInc > anonymous_namespace{marketmodel.cpp}::simulate (const boost::shared_ptr< MarketModelEvolver > &evolver, const MarketModelMultiProduct &product)
std::string anonymous_namespace{marketmodel.cpp}::marketModelTypeToString (MarketModelType type)
boost::shared_ptr< MarketModel > anonymous_namespace{marketmodel.cpp}::makeMarketModel (bool logNormal, const EvolutionDescription &evolution, Size numberOfFactors, MarketModelType marketModelType, Spread forwardBump=0.0, Volatility volBump=0.0)
std::string anonymous_namespace{marketmodel.cpp}::measureTypeToString (MeasureType type)
std::vector< Size > anonymous_namespace{marketmodel.cpp}::makeMeasure (const MarketModelMultiProduct &product, MeasureType measureType)
std::string anonymous_namespace{marketmodel.cpp}::evolverTypeToString (EvolverType type)
boost::shared_ptr
< MarketModelEvolver > anonymous_namespace{marketmodel.cpp}::makeMarketModelEvolver (const boost::shared_ptr< MarketModel > &marketModel, const std::vector< Size > &numeraires, const BrownianGeneratorFactory &generatorFactory, EvolverType evolverType, Size initialStep=0)
void anonymous_namespace{marketmodel.cpp}::checkMultiProductCompositeResults (const SequenceStatisticsInc &stats, const std::vector< SubProductExpectedValues > &subProductExpectedValues, const std::string &config)
void anonymous_namespace{marketmodel.cpp}::checkForwardsAndOptionlets (const SequenceStatisticsInc &stats, const std::vector< Rate > &forwardStrikes, const std::vector< boost::shared_ptr< StrikedTypePayoff > > &displacedPayoffs, const std::string &config)
void anonymous_namespace{marketmodel.cpp}::checkNormalForwardsAndOptionlets (const SequenceStatisticsInc &stats, const std::vector< Rate > &forwardStrikes, const std::vector< boost::shared_ptr< PlainVanillaPayoff > > &displacedPayoffs, const std::string &config)
void anonymous_namespace{marketmodel.cpp}::checkCallableSwap (const SequenceStatisticsInc &stats, const std::string &config)
void testMultiProductComposite (const MarketModelMultiProduct &product, const std::vector< SubProductExpectedValues > &subProductExpectedValues, const std::string &testDescription)
void addForwards (MultiProductComposite &product, std::vector< SubProductExpectedValues > &subProductExpectedValues)
void addOptionLets (MultiProductComposite &product, std::vector< SubProductExpectedValues > &subProductExpectedValues)
void addCoinitialSwaps (MultiProductComposite &product, std::vector< SubProductExpectedValues > &subProductExpectedValues)
void addCoterminalSwapsAndSwaptions (MultiProductComposite &product, std::vector< SubProductExpectedValues > &subProductExpectedValues)
Variables
Date anonymous_namespace{marketmodel.cpp}::todaysDate
Date anonymous_namespace{marketmodel.cpp}::startDate
Date anonymous_namespace{marketmodel.cpp}::endDate
Schedule anonymous_namespace{marketmodel.cpp}::dates
std::vector< Time > anonymous_namespace{marketmodel.cpp}::rateTimes
std::vector< Time > anonymous_namespace{marketmodel.cpp}::paymentTimes
std::vector< Real > anonymous_namespace{marketmodel.cpp}::accruals
Calendar anonymous_namespace{marketmodel.cpp}::calendar
DayCounter anonymous_namespace{marketmodel.cpp}::dayCounter
std::vector< Rate > anonymous_namespace{marketmodel.cpp}::todaysForwards
std::vector< Rate > anonymous_namespace{marketmodel.cpp}::todaysCoterminalSwapRates
Rate anonymous_namespace{marketmodel.cpp}::meanForward
std::vector< Real > anonymous_namespace{marketmodel.cpp}::coterminalAnnuity
Spread anonymous_namespace{marketmodel.cpp}::displacement
std::vector< DiscountFactor > anonymous_namespace{marketmodel.cpp}::todaysDiscounts
std::vector< Volatility > anonymous_namespace{marketmodel.cpp}::volatilities
std::vector< Volatility > anonymous_namespace{marketmodel.cpp}::blackVols
std::vector< Volatility > anonymous_namespace{marketmodel.cpp}::normalVols
std::vector< Volatility > anonymous_namespace{marketmodel.cpp}::swaptionsVolatilities
std::vector< Volatility > anonymous_namespace{marketmodel.cpp}::swaptionsBlackVols
Real anonymous_namespace{marketmodel.cpp}::a
Real anonymous_namespace{marketmodel.cpp}::b
Real anonymous_namespace{marketmodel.cpp}::c
Real anonymous_namespace{marketmodel.cpp}::d
Real anonymous_namespace{marketmodel.cpp}::longTermCorrelation
Real anonymous_namespace{marketmodel.cpp}::beta
Size anonymous_namespace{marketmodel.cpp}::measureOffset_
unsigned long anonymous_namespace{marketmodel.cpp}::seed_
Size anonymous_namespace{marketmodel.cpp}::paths_
Size anonymous_namespace{marketmodel.cpp}::trainingPaths_
bool anonymous_namespace{marketmodel.cpp}::printReport_ = false
Define Documentation
#define BEGIN (x) (x+0)
Definition at line 119 of file marketmodel.cpp.
#define END (x) (x+LENGTH(x))
Definition at line 120 of file marketmodel.cpp.
Function Documentation
void addCoinitialSwaps (MultiProductComposite & product, std::vector< SubProductExpectedValues > & subProductExpectedValues)
Definition at line 1177 of file marketmodel.cpp.
References anonymous_namespace{marketmodel.cpp}::accruals, QuantLib::MarketModelComposite::add(), anonymous_namespace{marketmodel.cpp}::paymentTimes, anonymous_namespace{marketmodel.cpp}::rateTimes, anonymous_namespace{marketmodel.cpp}::todaysDiscounts, and anonymous_namespace{marketmodel.cpp}::todaysForwards.
Referenced by MarketModelTest::testAllMultiStepProducts().
{
                           // create the products...
                           Real fixedRate = 0.04;
                           MultiStepCoinitialSwaps multiStepCoinitialSwaps(rateTimes, accruals, accruals,
                               paymentTimes, fixedRate);
                           product.add(multiStepCoinitialSwaps);
                           // computing and storing expected values
                           subProductExpectedValues.push_back(SubProductExpectedValues("coinitial swap"));
                           subProductExpectedValues.back().testBias = false;
                           subProductExpectedValues.back().errorThreshold = 2.32;
                           Real coinitialSwapValue = 0;
                           for (Size i=0; i<todaysForwards.size(); ++i) {
                               coinitialSwapValue += (todaysForwards[i]-fixedRate)
                                   *accruals[i]*todaysDiscounts[i+1];
                               subProductExpectedValues.back().values.push_back(coinitialSwapValue);
                           }
}
void addCoterminalSwapsAndSwaptions (MultiProductComposite & product, std::vector< SubProductExpectedValues > & subProductExpectedValues)
Definition at line 1197 of file marketmodel.cpp.
References anonymous_namespace{marketmodel.cpp}::accruals, QuantLib::MarketModelComposite::add(), QuantLib::Option::Call, QuantLib::LMMCurveState::coterminalSwapAnnuity(), QuantLib::LMMCurveState::coterminalSwapRates(), QuantLib::SwapForwardMappings::coterminalSwapZedMatrix(), anonymous_namespace{marketmodel.cpp}::displacement, QuantLib::MarketModelComposite::evolution(), anonymous_namespace{marketmodel.cpp}::ExponentialCorrelationFlatVolatility, QuantLib::MarketModelComposite::finalize(), anonymous_namespace{marketmodel.cpp}::makeMarketModel(), anonymous_namespace{marketmodel.cpp}::paymentTimes, anonymous_namespace{marketmodel.cpp}::rateTimes, QuantLib::LMMCurveState::setOnForwardRates(), anonymous_namespace{marketmodel.cpp}::todaysCoterminalSwapRates, anonymous_namespace{marketmodel.cpp}::todaysDiscounts, anonymous_namespace{marketmodel.cpp}::todaysForwards, and QuantLib::transpose().
Referenced by MarketModelTest::testAllMultiStepProducts().
{
                                        Real fixedRate = 0.04;
                                        MultiStepCoterminalSwaps swaps(rateTimes, accruals, accruals,
                                            paymentTimes, fixedRate);
                                        std::vector<boost::shared_ptr<StrikedTypePayoff> > payoffs(todaysForwards.size());
                                        for (Size i = 0; i < payoffs.size(); ++i)
                                            payoffs[i] = boost::shared_ptr<StrikedTypePayoff>(new
                                            PlainVanillaPayoff(Option::Call, todaysForwards[i]));
                                        MultiStepCoterminalSwaptions swaptions(rateTimes,
                                            rateTimes, payoffs);
                                        product.add(swaps);
                                        product.add(swaptions);
                                        subProductExpectedValues.push_back(SubProductExpectedValues("coterminal swap"));
                                        subProductExpectedValues.back().testBias = false;
                                        subProductExpectedValues.back().errorThreshold = 2.32;
                                        LMMCurveState curveState(rateTimes);  // not the best way to detect errors in LMMCurveState...
                                        curveState.setOnForwardRates(todaysForwards);
                                        std::vector<Rate> atmRates = curveState.coterminalSwapRates();
                                        for (Size i=0; i<todaysForwards.size(); ++i) {
                                            Real expectedNPV = curveState.coterminalSwapAnnuity(0, i) * (atmRates[i]-fixedRate) *
                                                todaysDiscounts.front();
                                            subProductExpectedValues.back().values.push_back(expectedNPV);
                                        }
                                        // we clone the prooduct to be able to finalize it and call evolution function member on it
                                        MultiProductComposite productClone = product;
                                        productClone.finalize();
                                        subProductExpectedValues.push_back(SubProductExpectedValues("coterminal swaption"));
                                        subProductExpectedValues.back().testBias = false;
                                        subProductExpectedValues.back().errorThreshold = 2.32;
                                        const Spread displacement = 0;
                                        Matrix jacobian =
                                            SwapForwardMappings::coterminalSwapZedMatrix(
                                            curveState, displacement);
                                        bool logNormal = true;
                                        EvolutionDescription evolution = productClone.evolution();
                                        Size factors = todaysForwards.size();
                                        MarketModelType marketModelType = ExponentialCorrelationFlatVolatility;
                                        boost::shared_ptr<MarketModel> marketModel =
                                            makeMarketModel(logNormal, evolution, factors, marketModelType);
                                        for (Size i=0; i<todaysForwards.size(); ++i) {
                                            const Matrix& forwardsCovariance = marketModel->totalCovariance(i);
                                            Matrix cotSwapsCovariance =
                                                jacobian * forwardsCovariance * transpose(jacobian);
                                            boost::shared_ptr<PlainVanillaPayoff> payoff(
                                                new PlainVanillaPayoff(Option::Call, todaysForwards[i]+displacement));
                                            Real expectedSwaption =
                                                BlackCalculator(payoff,
                                                todaysCoterminalSwapRates[i]+displacement,
                                                std::sqrt(cotSwapsCovariance[i][i]),
                                                curveState.coterminalSwapAnnuity(0,i) *
                                                todaysDiscounts[0]).value();
                                            subProductExpectedValues.back().values.push_back(expectedSwaption);
                                        }
}
void addForwards (MultiProductComposite & product, std::vector< SubProductExpectedValues > & subProductExpectedValues)
Definition at line 1120 of file marketmodel.cpp.
References anonymous_namespace{marketmodel.cpp}::accruals, QuantLib::MarketModelComposite::add(), anonymous_namespace{marketmodel.cpp}::paymentTimes, anonymous_namespace{marketmodel.cpp}::rateTimes, anonymous_namespace{marketmodel.cpp}::todaysDiscounts, and anonymous_namespace{marketmodel.cpp}::todaysForwards.
Referenced by MarketModelTest::testAllMultiStepProducts().
{
                     // create forwards and add them to the product...
                     std::vector<Rate> forwardStrikes(todaysForwards.size());
                     for (Size i=0; i<todaysForwards.size(); ++i)
                         forwardStrikes[i] = todaysForwards[i] + 0.01;
                     MultiStepForwards forwards(rateTimes, accruals,
                         paymentTimes, forwardStrikes);
                     product.add(forwards);
                     // computing and storing expected values
                     subProductExpectedValues.push_back(SubProductExpectedValues("Forward"));
                     subProductExpectedValues.back().errorThreshold = 2.50;
                     for (Size i=0; i<todaysForwards.size(); ++i) {
                         subProductExpectedValues.back().values.push_back(
                             (todaysForwards[i]-forwardStrikes[i])
                             *accruals[i]*todaysDiscounts[i+1]);
                     }
}
void addOptionLets (MultiProductComposite & product, std::vector< SubProductExpectedValues > & subProductExpectedValues)
Definition at line 1143 of file marketmodel.cpp.
References anonymous_namespace{marketmodel.cpp}::accruals, QuantLib::MarketModelComposite::add(), QuantLib::Option::Call, anonymous_namespace{marketmodel.cpp}::displacement, anonymous_namespace{marketmodel.cpp}::paymentTimes, anonymous_namespace{marketmodel.cpp}::rateTimes, anonymous_namespace{marketmodel.cpp}::todaysDiscounts, anonymous_namespace{marketmodel.cpp}::todaysForwards, and anonymous_namespace{marketmodel.cpp}::volatilities.
Referenced by MarketModelTest::testAllMultiStepProducts().
{
                       // create the products...
                       std::vector<boost::shared_ptr<Payoff> > optionletPayoffs(todaysForwards.size());
                       std::vector<boost::shared_ptr<StrikedTypePayoff> >
                           displacedPayoffs(todaysForwards.size());
                       for (Size i=0; i<todaysForwards.size(); ++i) {
                           optionletPayoffs[i] = boost::shared_ptr<Payoff>(new
                               PlainVanillaPayoff(Option::Call, todaysForwards[i]));
                           //CashOrNothingPayoff(Option::Call, todaysForwards[i], 0.01));
                           displacedPayoffs[i] = boost::shared_ptr<StrikedTypePayoff>(new
                               PlainVanillaPayoff(Option::Call, todaysForwards[i]+displacement));
                           //CashOrNothingPayoff(Option::Call, todaysForwards[i]+displacement, 0.01));
                       }
                       MultiStepOptionlets optionlets(rateTimes, accruals,
                           paymentTimes, optionletPayoffs);
                       product.add(optionlets);
                       // computing and storing expected values
                       subProductExpectedValues.push_back(SubProductExpectedValues("Caplet"));
                       subProductExpectedValues.back().errorThreshold = 2.50;
                       for (Size i=0; i<todaysForwards.size(); ++i) {
                           subProductExpectedValues.back().values.push_back(
                               BlackCalculator(displacedPayoffs[i],
                               todaysForwards[i]+displacement,
                               volatilities[i]*std::sqrt(rateTimes[i]),
                               todaysDiscounts[i+1]*accruals[i]).value());
                       }
}
void testMultiProductComposite (const MarketModelMultiProduct & product, const std::vector< SubProductExpectedValues > & subProductExpectedValues, const std::string & testDescription)
Definition at line 1047 of file marketmodel.cpp.
References anonymous_namespace{marketmodel.cpp}::Balland, anonymous_namespace{marketmodel.cpp}::checkMultiProductCompositeResults(), QuantLib::SobolBrownianGenerator::Diagonal, QuantLib::MarketModelMultiProduct::evolution(), anonymous_namespace{marketmodel.cpp}::evolverTypeToString(), anonymous_namespace{marketmodel.cpp}::ExponentialCorrelationAbcdVolatility, anonymous_namespace{marketmodel.cpp}::ExponentialCorrelationFlatVolatility, anonymous_namespace{marketmodel.cpp}::Ipc, QuantLib::isInTerminalMeasure(), LENGTH, anonymous_namespace{marketmodel.cpp}::makeMarketModel(), anonymous_namespace{marketmodel.cpp}::makeMarketModelEvolver(), anonymous_namespace{marketmodel.cpp}::makeMeasure(), anonymous_namespace{marketmodel.cpp}::marketModelTypeToString(), anonymous_namespace{marketmodel.cpp}::measureTypeToString(), anonymous_namespace{marketmodel.cpp}::MoneyMarket, anonymous_namespace{marketmodel.cpp}::MoneyMarketPlus, anonymous_namespace{marketmodel.cpp}::Pc, anonymous_namespace{marketmodel.cpp}::printReport_, anonymous_namespace{marketmodel.cpp}::seed_, anonymous_namespace{inflationvolatility.cpp}::setup(), anonymous_namespace{marketmodel.cpp}::simulate(), anonymous_namespace{marketmodel.cpp}::Terminal, and anonymous_namespace{marketmodel.cpp}::todaysForwards.
Referenced by MarketModelTest::testAllMultiStepProducts().
{
                                   BOOST_MESSAGE("Testing exact repricing of "
                                       << testDescription
                                       << "in a lognormal forward rate market model...");
                                   setup();
                                   EvolutionDescription evolution = product.evolution();
                                   MarketModelType marketModels[] = {
                                       // CalibratedMM,
                                       ExponentialCorrelationFlatVolatility,
                                       ExponentialCorrelationAbcdVolatility };
                                       for (Size j=0; j<LENGTH(marketModels); j++) {
                                           Size testedFactors[] = { 4, 8,
                                               todaysForwards.size()};
                                           for (Size m=0; m<LENGTH(testedFactors); ++m) {
                                               Size factors = testedFactors[m];
                                               // Composite's ProductSuggested is the Terminal one
                                               MeasureType measures[] = { // ProductSuggested,
                                                   Terminal,
                                                   MoneyMarketPlus,
                                                   MoneyMarket};
                                                   for (Size k=0; k<LENGTH(measures); k++) {
                                                       std::vector<Size> numeraires = makeMeasure(product, measures[k]);
                                                       bool logNormal = true;
                                                       boost::shared_ptr<MarketModel> marketModel =
                                                           makeMarketModel(logNormal, evolution, factors, marketModels[j]);
                                                       EvolverType evolvers[] = { Pc, Balland, Ipc };
                                                       boost::shared_ptr<MarketModelEvolver> evolver;
                                                       Size stop =
                                                           isInTerminalMeasure(evolution, numeraires) ? 0 : 1;
                                                       for (Size i=0; i<LENGTH(evolvers)-stop; i++) {
                                                           for (Size n=0; n<1; n++) {
                                                               //MTBrownianGeneratorFactory generatorFactory(seed_);
                                                               SobolBrownianGeneratorFactory generatorFactory(
                                                                   SobolBrownianGenerator::Diagonal, seed_);
                                                               evolver = makeMarketModelEvolver(marketModel,
                                                                   numeraires,
                                                                   generatorFactory,
                                                                   evolvers[i]);
                                                               std::ostringstream config;
                                                               config <<
                                                                   marketModelTypeToString(marketModels[j]) << ", " <<
                                                                   factors << (factors>1 ? (factors==todaysForwards.size() ? " (full) factors, " : " factors, ") : " factor,") <<
                                                                   measureTypeToString(measures[k]) << ", " <<
                                                                   evolverTypeToString(evolvers[i]) << ", " <<
                                                                   "MT BGF";
                                                               if (printReport_)
                                                                   BOOST_MESSAGE("    " << config.str());
                                                               boost::shared_ptr<SequenceStatisticsInc> stats =
                                                                   simulate(evolver, product);
                                                               checkMultiProductCompositeResults(*stats,
                                                                   subProductExpectedValues,
                                                                   config.str());
                                                           }
                                                       }
                                                   }
                                           }
                                       }
}